### ISSUE TITLE
What is this startup error? ("strip" operator replaced with "before strip")

### ISSUE THREAD

**Issue by TheMattVid** [kangarko/ChatControl#1]
http://pastebin.com/JdgVkN0G

**Comment by TheMattVid** [comment]
Version is 5.1.5, but I don't know if it ever occurred prior.

**Comment by TheMattVid** [comment]
Just checked. I was running 5.0.8 and I didn't have the issue.

**Comment by kangarko** [comment]
This is not a startup error, it is a reminder. Please open rules/rules.txt file and change the operator "strip" to "before strip". After doing this and restarting the server, this message will no longer be displayed.

**Comment by TheMattVid** [comment]
Oh, thanks. I didn't realize that this was directly related to a line/lines in the config and that they needed to be changed. Thanks for the help!
