### ISSUE TITLE
Override permission.

### ISSUE THREAD

**Issue by kristiantomov** [kangarko/ChatControl#10]
What is the permission so the plugin ignore certian groups ?

**Comment by kangarko** [comment]
Do you mean the Groups section in settings.yml? If so, you need to give **chatcontrol.group.NAME** permission to the player to assign him into certain group (NAME is the name of the group).

If you are using multiple groups, you need to negate the parent group to make it effective 

>Moderator:
>  permissions:
>    - chatcontrol.group.moderator
>
>Admin:
>  inheritance:
>    - Moderator
>  permissions:
>    - -chatcontrol.group.moderator
>    - chatcontrol.group.admin
