### ISSUE TITLE
Bypass advertising filter under certain commands

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#100]
The default filter for IP addresses working pretty well, also when using characters like `-` or `,`.
Unfortunately this is causing trouble on other side.

For example when trying to set flags an a plot like this:
`/p set flag use 63,68,116,55` this will be caught as advertisment.

CHC offers an option to ignore the filter on certain events as in this case a command.
However I don't want to allow bypassing the IP filter using commands in general.

So is there a way to bypass certain rules if they are matching in a special situation like a particular command?

CHC 5.3.0 (yes, still on free even though I own the pro for a while now)

**Comment by kangarko** [comment]
In rules, you can use the 'ignore string' operator which would literally include the part of the command the rule should 

But I recommend you use the handlers, as they contain a specialized section for adding commands to ignore:

An example:
```
advertisement:
  Ignored_In_Commands:
    - /auction
    - /register
    - /reg
```
