### ISSUE TITLE
Error when trying to change the chat.txt

### ISSUE THREAD

**Issue by MuroHasegawa** [kangarko/ChatControl#100]
Getting this when I edit the chat.txt file.

http://pastebin.com/tWHGQB1n

**Comment by kangarko** [comment]
You have ? in front of the line which makes the program think you are adding an operator.

**Comment by deswryn21** [comment]
I think this error also appears when you try to save the file on Notepad or Wordpad. It is suggested that you use Notepad++ for editing and saving the txt files.

**Comment by MuroHasegawa** [comment]
@deswryn21 You were right, I was using notepad to edit the files, not sure why though lol. Anyway editing the files with NP++ worked. Thanks for the help!
