### ISSUE TITLE
1.16.5: KingdomsX placeholders not parsing in ChatControl

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl#1000]
Hello,

When parsing KingdomsX placeholders ChatControlRed does not display some of them properly. I spoke with the author of KingdomsX and he stated that its something on the end of ChatControl.

I would like to get this resolved for myself and other ChatControl users as I have noticed at least 10 others with the same issue, I am willing to provide any details or testing needed to contribute to this issue.

KingdomsX is also becoming more popular and I feel it would be in ChatControl's interest to add support for it.

Thanks

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Thanks for reporting. You can use PlaceholderAPI to see if they support our plugin's placeholders, or see the Listener Priorities section of our Wiki to try tweaking our event listener. If that still won't work then unfortunately it looks like a major incompatibility.
