### ISSUE TITLE
1.16.5: Seems that the command whitelist does not support multiple args on commands, only one arg

### ISSUE THREAD

**Issue by PedroMPagani** [kangarko/ChatControl#1001]
Hey, mind checking out if you can delay commands with multiple args?
Because i can't, one guy hired me to fix that issue but i don't like deobfuscation as the source is not public so, the issue seems to be that whitelist commands only work with args[0], i looked at the code and seems to be true, if there's like /home <b>, it wont delay bcs the only thing thats checked is the args 0

**Comment by kangarko** [comment]
No sorry, we only check the first argument of the command.
