### ISSUE TITLE
ChatControl doesn't seem to do anything.

### ISSUE THREAD

**Issue by mrouie** [kangarko/ChatControl#101]
I've been using ChatControl in the past and it seemed to have been an amazing plugin. Then it suddenly stopped working, it is updated to the latest version (5.0.8b). It loads, but none of the commands or features work. There's also no error message.

**Comment by kangarko** [comment]
What is you bukkit version? Can you post me your starting log from the server?

**Comment by mrouie** [comment]
I am using Spigot and the version is 1.8.3-R0.1-SNAPSHOT

My startup log is posted here. http://pastebin.com/Psgair4q

**Comment by kangarko** [comment]
Apparently you have a syntax error in one of the rules OR you have opened/edited the files in some editor that damages the encoding (notepad/wordpad on windows do that)

**Comment by mrouie** [comment]
It's probably a syntax error, I use Notepad++ which shouldn't ever have problems editing files such as these. Thanks for the help!

**Comment by kangarko** [comment]
So it's fixed ? :)

**Comment by mrouie** [comment]
My rules.txt is quite heavily filled, so it will take some time for me to find the mistake, but it will be fixed soon. Thanks for the help! Your plugin is amazing!

**Comment by kangarko** [comment]
Considering fixed. Please contact me again if any issues occur.
