### ISSUE TITLE
1.16.5 How to enable colors on signs?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#1010]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Old color formats nor hex colors are working on signs.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Old color formats nor hex colors are working on signs.

Hey,
Sign colors aren't handled by the plugin as far as I know. If you'd like to use colors on your signs (regular colors and hex ones), you'll have to install a plugin like EssentialsX.
