### ISSUE TITLE
Paper 1.16.5 & Java 16: The plugin wont load 

### ISSUE THREAD

**Issue by Korinocho** [kangarko/ChatControl#1013]
The plugin wont load because i updated my Java version to 16.0.1 due to Paper announce that they will use it as minimum Java version.
These are the errors that i get:
![image](https://user-images.githubusercontent.com/21372197/119136949-a4b05b00-ba16-11eb-889e-f71d11cffdae.png)

Server: Paper #705 1.16.5
ChatControl Version: 10.4.2
Java version: 16.0.1
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: true

**Comment by kangarko** [comment]
Read that error message then act accordingly thank you
