### ISSUE TITLE
1.16.5: Mail has weird issues after server restart (Waterfall)

### ISSUE THREAD

**Issue by Seeroh** [kangarko/ChatControl#1016]
As title says, the mail system has some weird issues with Bungee(Waterfall, in my case.) There are no error messages, and I can find nothing in the config that would change this behavior. I'll upload my debug if needed, but I don't believe it's a config issue. Basically, after a server restart, all mail has disappeared. 

Steps I followed to double check what was going on.

1) Checked ChatControl_Mail table in database, it was empty
2) Sent a mail to an alt
3) Verified ChatControl_Mail table had newly generated mail data
4) Issued a server restart
5) Checked table after restart, table was empty, no mail to read using `/mail read`

--------------------------------

Actually, just playing around with it, I can't even fully pin down what the heck is going on. One time I checked, and I couldn't see any mail in the database, or in game. Another time, the table was empty, I sent mail, and then mail that had already been deleted was returned. Either way, there is something buggy related to mail being sent via MySQL, and across servers. Best case scenario, mail "might" return after a different mail is sent. Worst case is it just disappears altogether on server restart.

Tested this using two servers running on Waterfall with both having Bungee Integration enabled, MySQL enabled, and UUID_Lookup set to false.

--------------------------------

I did try with a clean install, no MySQL, no Bungee integration (with `UUID_Lookup: false` in mysql.yml), and sent mails did seem to persist after a restart, so I'm pretty sure this is related to Waterfall or just basic BungeeCord.

Minecraft Version: 1.6.5
MySQL: True
BungeeCord: True

**Comment by kangarko** [comment]
From my understanding you've tried the mail system without mysql and without bungeecord and it worked. Now you have both options on and it breaks. Before I go ahead and investigate, can you please try with mysql on, and bungeecord off? Just to point me in the right direction, thank you.

**Comment by Seeroh** [comment]
Just tested with Bungee integration disabled, and MySQL on, same results.

I am using MariaDB if that means anything for this, though I feel doubtful. Everything works fine, until a restart occurs.

**Comment by kangarko** [comment]
Sorry for the delay, I will get back to this asap in 24-48h

**Comment by kangarko** [comment]
https://www.loom.com/share/36c1b23c778f4b298ebddcb9bd28c9b9

Assuming it got away after I fixed the bug I got in the video, closing in good faith but lemme know below if you'll still experience it. Sorry again for the week's delay!
