### ISSUE TITLE
1.16.5: How to ignore commands for advertisement filter?

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl#1017]
Hello I am trying to figure out how to make my advertisement filters ignore commands being ran as they are triggering for stuff like /co tp (CoreProtect). Some help would be appreciated.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Hello I am trying to figure out how to make my advertisement filters ignore commands being ran as they are triggering for stuff like /co tp (CoreProtect). Some help would be appreciated.
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey,
It looks like an issue with your advertisement filters. If a command like `/co tp` is detected as an ad, then you configured your filters wrongly I guess.
Use a website like https://regex101.com/ for your regex.

**Comment by kangarko** [comment]
<img width="485" alt="Screenshot 2021-05-23 at 20 28 37" src="https://user-images.githubusercontent.com/1918426/119272274-7644a280-bc05-11eb-9c40-5f45fd833204.png">
In your rules/groups.rs file, configure ignore command for the advertisement group as per instructions in that file and/or our Wiki.
