### ISSUE TITLE
1.16.5: Finding Channel being used for Javascript Variable

### ISSUE THREAD

**Issue by Seeroh** [kangarko/ChatControl#1018]
I'm looking for a way to use the channel being spoken in, in a javascript variable. I know of the placeholder {chatcontrolred_channel}, and that almost does the trick for me, but it doesn't work properly if I use /ch send [channel].

To explain better, if I'm in Global, my variable works properly by using {chatcontrol_channel}, but if I did /ch send local, the variable would still show the output for Global, instead of Local.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> I'm looking for a way to use the channel being spoken in, in a javascript variable. I know of the placeholder {chatcontrolred_channel}, and that almost does the trick for me, but it doesn't work properly if I use /ch send [channel].
> 
> To explain better, if I'm in Global, my variable works properly by using {chatcontrol_channel}, but if I did /ch send local, the variable would still show the output for Global, instead of Local.
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
You could try with `{chatcontrolred_player_in_channel_<channel>}`. To get more infos about the internal variables, take a look at our wiki : https://github.com/kangarko/ChatControl-Red/wiki/Variables
However, I don't know if what you're trying to do is currently possible.

**Comment by kangarko** [comment]
Thanks to Banana for answering!  No sorry the variable will always print the player's write channel not the one initiated from /ch send command.

**Comment by Seeroh** [comment]
Would you be able to implement a variable for which channel a message is being sent to, or is that out of the realm of possibility?

**Comment by kangarko** [comment]
Thanks, however we're not planning to do this right now. ChatControl is not obfuscated, you can just get a developer to create an API hook for that matters.
