### ISSUE TITLE
1.16.5 Warning messages do not appear

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#1019]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Mute is getting done. Warning points are being assigned. But warning messages do not appear. What to do?
```

  Sets:
    global:
      3:
      - 'warn &7You must obey the &2rules &7else you will be &4punished&7.'
      10:
      - 'warn &c**** &lHey &c{player} ****'
      - 'warn &7-> &cThis is your &6final &cwarning!'
      30:
      - 'mute player {player} 1h &cMuted for breaking the rules'
    swear:
      3:
      - 'warn &cYou have received first warning for swearing.'
      6:
      - 'warn &cPlease do not swear, otherwise an action will be taken!'
      8:
      - 'mute player {player} 1h &cInappropriate language (last warning)'
    spam:
      6:
      - 'warn &cPlease do not act like a spammer.'
      10:
      - 'warn &cPlease do not spam, otherwise you will be banned.'
      12:
      - 'mute player {player} 1h &cSpamming the chat (last warning)'
    fastmessages:
      8:
      - 'warn &cPlease slow down chat messages.'
      12:
      - 'warn &cSlow down chat, otherwise you will be banned.'
      16:
      - 'mute player {player} 1h &cSlow down chat (last warning)'
```

**Comment by kangarko** [comment]
<img width="839" alt="Screenshot 2021-05-29 at 18 24 52" src="https://user-images.githubusercontent.com/1918426/120077547-2e14fc80-c0ab-11eb-9a11-99509d32396b.png">
Cannot reproduce, I was getting the messages normally.

Set Debug to [points] in settings.yml and check if any other plugin can be interfering

**Comment by kangarko** [comment]
Also check that the formula with math expression is not returning 0

**Comment by kangarko** [comment]
The next release will have one more debug line with the expression to help you see if it's 0

**Comment by nikitushu2** [comment]
Strangely it works now: [https://paste.gg/p/anonymous/6c564c61ff7a4cd89467d894aa2aa351](https://paste.gg/p/anonymous/6c564c61ff7a4cd89467d894aa2aa351)

But the line "You can only send commands in seconds" is bugged (it lacks the count of seconds). I remember I resetted the localization based on your advice here: [https://github.com/kangarko/ChatControl-Red/issues/989](https://github.com/kangarko/ChatControl-Red/issues/989), and it worked. But now it appeared again:

![Minecraft_ 1 16 5 - Multiplayer (3rd-party Server) 30_05_2021 8 37 53](https://user-images.githubusercontent.com/32280863/120093436-f6e23200-c122-11eb-9f62-18f93ec21b58.png)


Sorry, I am confused, I don't know why some issue fixes itself through the time while the other fixed one appears again.

**Comment by kangarko** [comment]
Send me your messages_en.yml file as you have it right now. Also check out https://github.com/kangarko/ChatControl-Red/wiki/Use-Right-Encoding and ensure you used the right tool to save the file in the right encoding. Also do not use PlugMan or anything like that to reload.

**Comment by kangarko** [comment]
Ensure you have Checker.Period key in your locale file set to:

"You can only send {type_amount} {type} in {period_amount} {period}." which you didn't have in the file you sent me on the other ticket. That's why it was empty. We updated the variables :)
