### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by The3Pointed** [kangarko/ChatControl#102]
Where is the config file located? I cannot find it anywhere in the /plugins directory

**Comment by The3Pointed** [comment]
Other than that i have 0 problems

**Comment by EvilOlaf** [comment]
CHC creates a folder called `ChatControl` within the `plugins` folder. If it doesn't at startup check your console logs if there are problems at startup. Either it has not been loaded or your `plugins` folder is not writable. Either way check your logs.

**Comment by kangarko** [comment]
What @EvilOlaf says. It's not possible that the plugin starts without problems and won't create its folder.
