### ISSUE TITLE
Essentials /nick not supported

### ISSUE THREAD

**Issue by TheoBr** [kangarko/ChatControl#102]
I'm assuming this is some conflict with Vault, but it seems like ChatAlert got around it. See: http://www.curse.com/bukkit-plugins/minecraft/chatalert

**Comment by kangarko** [comment]
Hey, thanks for the advice. I am currently working on something else, but I will try to fix it soon.

**Comment by TheoBr** [comment]
Of course man, if I have time this week I'll try to as well. Haven't touched any MC code in awhile, but it shouldn't be too bad since that code already conveniently exists

**Comment by Okane84** [comment]
i could confirm that in tab list the nickname changes, it does not in the chat lines. thank you for working on it

**Comment by Karrade** [comment]
im new to minecraft code i know a little java but here is chatalerts git for the essentials hook if anyone more experienced wants to push it through

https://github.com/jacklin213/ChatAlert/blob/master/src/me/jacklin213/chatalert/ChatAlert.java

**Comment by kangarko** [comment]
The %displayname variable that usually fetches the nick you are talking about will be implemented upon the next release.

**Comment by kangarko** [comment]
Implemented.
