### ISSUE TITLE
1.16.5: Support for TownyAdvanced's Ally Chat

### ISSUE THREAD

**Issue by UserDerezzed** [kangarko/ChatControl#1020]
Hey there, kangarko! Not sure if you remember me but I was one of the beta testers for CHC Red.

I'm hoping to see support for TownyAdvanced's Ally Chat system by using the same format that the Town and Nation chat use (the Party system for CHC channels.) This is the one thing preventing me from enabling CHC channels across my Towny network, as we have a Towny Siege server and being able to communicate with Allies is crucial. Hopefully this isn't too big of a task, I'm hoping you can just copy/paste the same code from Nation and Town to enable this.

Thanks!

**Comment by kangarko** [comment]
Sorry for the delay! Can you please be more specific how you want this to work?

I think we have the Party option of "NATION" and "TOWN", so essentially you want to add another party option of "ALLY" ?

**Comment by UserDerezzed** [comment]
No worries on the delay! Life gets busy sometimes.

Yep! The Party options of NATION and TOWN work great in my testing, just looking for the ALLY chat to be added as well :) Thanks!

**Comment by kangarko** [comment]
Added as "towny-ally" Party option!
