### ISSUE TITLE
1.16.5: Links

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1021]
I want to put clickable links with hover text and title in timed messages that are stored in `timed.rs` file. How can I define such a message? Thank you.

Minecraft Version: 1.X.Z
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> I want to put clickable links with hover text and title in timed messages that are stored in `timed.rs` file. How can I define such a message? Thank you.
> 
> Minecraft Version: 1.X.Z
> MySQL: false
> BungeeCord: false

Hey!
To do so, you must use JSON messages. There's no other way to store the message in the timed.rs file. Another way would be to create a format file for the timed message, but then the message won't be stored in the timed.rs file, but in it's own format file.
Regarding JSON messages, take a look at this page : https://github.com/kangarko/ChatControl-Red/wiki/JSON
