### ISSUE TITLE
1.16.5: Is it possible to have a click event in a CHC book?

### ISSUE THREAD

**Issue by mav2020** [kangarko/ChatControl#1023]
I am running ChatControl-Red-10.4.3 and am wondering if there is a way to have a click event within a chc book. I was hoping to have it open a different book and/or open a URL. I tried several things including using a variable, but either I did it wrong or it just isn't possible. So I figured I would ask. Thanks.

Minecraft Version: Paper 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey!
As far as I know you can't do this with the plugin, but you should be able to generated your book using a tool like this one : https://minecraft.tools/en/book.php then use `/chc book save` to do so.

**Comment by mav2020** [comment]
Oh, ok, I didn't think about doing /chc book save with a book that wasn't created with /chc book new. Thanks for the tip.
