### ISSUE TITLE
1.15.2: How can I set "ignore usernames" in rules/groups?

### ISSUE THREAD

**Issue by ArtNRG** [kangarko/ChatControl#1024]
Minecraft Version: 1.15.2
MySQL: true
BungeeCord: true

How can I set "ignore usernames" in rules/groups?
For example, I don't want to mute players for "/m TPLFUC kaboom" - the player TPLFUC is online and sender become muted after "FUC k" part of the message.
I don't want to modify rules, they were tested for years.

**Comment by ElBananaa** [comment]
Hey!
As far as I know, there's no `ignore username` variable. However, to do so you could either use the `ignore permission` variable, or you could use : `save key <key> <value>` (E.g. `save key player-tpfluc TPLFUC ` then under this variable : `ignore key player-tpfluc`.
