### ISSUE TITLE
1.16.5: API: Event for currently selected channel is always called

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1025]
Hello, I integrate the CCR with CMI jails and a little bit other custom stuff. There is a small problem that the Event is called twice when player uses a `global` or `trade` channel, once with the proper channel and once with `ranged`.

I use prefixes to make it easy for players. E.g `!` for global and `№` for trade:
```
match ^(\!)(.*)
then command channel send global $2
then deny
dont verbose
```
 So I think that you forget to set the Event to canceled state for `ranged` channel after the rule cancels the original message with `then deny`.
 
 I suppose it is not specific to the ranged chat, it works like this with any channel that is selected as the current one. E.g if players selects `custom1` channel, but still writes `!hello`. Both events for `custom1` and `global` will be called.
```
@EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onGlobalChat(ChatChannelEvent event) {
        if (event.getSender() instanceof Player) {
            Player player = (Player) event.getSender();
            if (cmiPlayerManager.getUser(player).isJailed()) {
                if (event.getChannel().getName().equals("global") ||
                        event.getChannel().getName().equals("trade")) {
                    //LOGIC FOR GLOBAL CHAT
                }
                else if (event.getChannel().getName().equals("ranged")) {
                    //LOGIC FOR RANGED CHAT
                }
            }
        }
    }
```

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Thanks got that patched right now!
