### ISSUE TITLE
Details about some permissions [mail all]

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#1026]
Regarding the subdivision of commands, whether the permissions can be subdivided, such as [/mail send all], the permission [chatcontrol.command.mail.all] is required.
In addition, I have a small question about Tag. If I want to change other players, how do I choose? It seems that I cannot choose other players.
Can you change the options and permissions of others [chatcontrol.command.tag.other]

For most people who use this plug-in, I think these new additions are needed. I think that sending emails to all players is limited to management, which can reduce malicious sending by players.
Or manage other people’s tags

**Comment by kangarko** [comment]
Thanks, I will add two new permissions for sending mail to all and to online players.

You can use /chc tag command instead of the /tag command to set tag of other players.
