### ISSUE TITLE
1.16.5:  issues with Mythicmobs player disguised mobs using LibDisguises not displaying name

### ISSUE THREAD

**Issue by Maitlans** [kangarko/ChatControl#1028]
Minecraft Version: 1.6.5
MySQL: false
BungeeCord: false

Whenever I add the plugin mobs disguised as players will lose their names it'll just be an empty super tiny transparent tag with nothing on it. Whenever the plugin is removed the names are fixed and show up properly, There doesn't seem to be any out the ordinary logs. Thank you

**Comment by kangarko** [comment]
Unfortunately that's incompatibility with our Tag feature,

Set Tag.Apply_On to [] in settings.yml to disable the feature and stop this from happening

**Comment by Maitlans** [comment]
> Unfortunately that's incompatibility with our Tag feature,
> 
> Set Tag.Apply_On to [] in settings.yml to disable the feature and stop this from happening

It does semi fix it, but whenever the server is restarted and I login the mobs will have their names blank again until they die and after that it's fixed, it happens every time a restart happens.

**Comment by kangarko** [comment]
Are you sure it's ChatControl Red? We don't have any feature altering NPCs names if you disable the Tag feature

**Comment by Maitlans** [comment]
> Are you sure it's ChatControl Red? We don't have any feature altering NPCs names if you disable the Tag feature

Hey yes, when I remove ChatControl Red it works fine, so I  learned a bit more about the issue, it'll spawn the NPCs without a name if they're spawned and no players are around, but if a player is near when they spawn it'll spawn with the proper name.

**Comment by Maitlans** [comment]
@kangarko Could you please get back to me? This is a crucial issue for me. Thanks.
