### ISSUE TITLE
Enabling chat formatter causes plugin to disable itself.

### ISSUE THREAD

**Issue by magmu** [kangarko/ChatControl#103]
http://pastebin.com/bAEPZAAF is my startup log.

I really don't know what I've done wrong, I put Vault in place edited the file to enable formatting and this is where I'm at. All the files have only been edited with vim. Am I missing a required plugin or something for this feature?

**Comment by kangarko** [comment]
You have enabled chat formatter but no permissions or chat plugin was found (e.g. PermissionsEx, EssentialsChat)
