### ISSUE TITLE
Channel suggestions

### ISSUE THREAD

**Issue by PascalBrassat** [kangarko/ChatControl#103]
Hello, I have started messing with this plugin today, and I think it would really benefit if the following were added;

1. Ability to create channels ingame
2. Ability to set passwords to channels
3. Make it so that you can do /ch g instead of /ch join g or whatever. 
4. Is it possible to toggle the vanish thing where it forces you to do /ch send (channel name) (Message)
5. is there an outright way to disable the join/leave messages (I found just clearing the files works for now)
6. I found that the tab complete restrictor doesn't really work, although maybe I am doing something wrong.
7. Adding aliases for channels, so doing /ch join s instead of /ch join staff 

Thanks so far this plugin is awesome!

**Comment by pabjr17** [comment]
A few more comments;

- Is it possible to toggle the vanish thing where it forces you to do /ch send (channel name) (Message)
- is there an outright way to disable the join/leave messages (I found just clearing the files works for now)
- I found that the tab complete restrictor doesn't really work, although maybe I am doing something wrong.

**Comment by kangarko** [comment]
Thanks!

1.  and 2. Maybe in the future 👍 
3. You can do so already now, read Wiki -> Custom Commands
4. Sure, I will add an option to disable that.
5. Yes, to stop ChatControl from handling your join/leave messages remove them from Messages.Apply_On, if you want to hide them simply clear your messages/ .rs files.
6. What does not work?
7. Answered in 3)
