### ISSUE TITLE
Message broadcaster per permission

### ISSUE THREAD

**Issue by stevenscruz** [kangarko/ChatControl#103]
Is there a way in which i can make certain groups receive certain auto broadcaster messages?
Here is an example:

Groups:
- Guest
   permission: chc.group.guest
- Donator
   permission: chc.group.donator
- Admin
   permission: chc.group.admin

Message:
  Guest:
     Messages:
     - Have you considered donating?
  Donator:
     Messages:
     - Thanks for supporting the server!
  Admin:
     Messages:
     -  Don't forget to check user reports with /report check [player]

I feel like something like this will be a great feature if it isn't already!

**Comment by kangarko** [comment]
Hey, such feature is not present. You can configure different messages per world, but not per permission. I am leaving this open as a suggestion, but keep in mind, that if it will be added, it will be added to the premium version.

**Comment by stevenscruz** [comment]
Yeah that would be great.

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Pro/issues/65
