### ISSUE TITLE
1.12.2: ChatControlRed does not support the localization: messages_es.yml

### ISSUE THREAD

**Issue by Bruneitor123** [kangarko/ChatControl#1032]
Minecraft Version: 1.12.2 (Using ViaVersion, ViaRewind and ViaBackwards)
MySQL: true
BungeeCord: true

Hello! I've been configuring ChatControl Red as soon as I got the copy and I just tried to start the server, nonetheless there's this error here that I've been getting and It looks like it's a problem from you, the error is as the title say, FYI the error log is here:
[error.log](https://github.com/kangarko/ChatControl-Red/files/6565769/error.log)

**Comment by TheIntolerant** [comment]
Hey,
As it says in the log, ChatControlRed does not support Spanish, the log itself tells you how to fix this issue.
> FoException Report: ChatControlRed does not support the localization: messages_es.yml (For custom locale, set the Locale to 'en' and edit your English file instead)

At this moment in time ChatControlRed only has support for English and French.

**Comment by Bruneitor123** [comment]
Thank you very much for the clarification! I was a little bit confused because in the docs it said spanish support, but I read again and it was ChatControl Pro, hehe. I will start to translate the file by myself, and if whenever I finish I'll upload it here if It helps you to start supporting Spanish.

**Comment by TheIntolerant** [comment]
I have made the same mistake lol so I completely understand

**Comment by kangarko** [comment]
Sure, if you upload messages_es.yml translated from English to Spanish for ChatControl Red I'll gladly include it and give you all the credits :)
