### ISSUE TITLE
1.16.5 "Move before typing new commands" may make players stuck in some situations

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#1033]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

In Creative server if a player was closed with blocks on another plot and if he joins back (when the owner of that plot is not online), then the player can not only type anything but also he is not able to break blocks, thus making him stuck forever.

Is there any way to prevent this situation somehow? Maybe allowing only a particular command to be typed? What do you think?

**Comment by TheIntolerant** [comment]
Hey, you can do any of the following

-----------------------------------------

**Option 1**

In *settings.yml* go to ``Anti_bot.Block_Commands_Until_Moved`` and put ``@blacklist`` on the first line then commands. Which means only these commands will be allowed.
Example:
```yml
  Block_Commands_Until_Moved:
  - "@blacklist"
  - /login
  - /register
  - /reg
  - /l
  - /spawn
```
This will make the following commands bypass this feature.

-----------------------------------------

**Option 2**

In *settings.yml* set ``Anti_bot.Block_Chat_Until_Moved`` to ``false``
This will completely disable this feature.

-----------------------------------------

**Option 3**

Assign the permission node ``chatcontrol.bypass.move`` to users on that specific server/world.

**Comment by kangarko** [comment]
Thanks to gone for providing excellent guidance on what you can consider doing :)
