### ISSUE TITLE
{server_name} not working

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1037]
![image](https://user-images.githubusercontent.com/29138111/120278512-f5159b80-c2e7-11eb-9e56-7f12d8224dff.png)

Also, I cant find (read) and (write) at Localizations

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true
![image](https://user-images.githubusercontent.com/29138111/120278588-0c548900-c2e8-11eb-8d79-101c919130f2.png)

**Comment by ElBananaa** [comment]
> ![image](https://user-images.githubusercontent.com/29138111/120278512-f5159b80-c2e7-11eb-9e56-7f12d8224dff.png)
> 
> Also, I cant find (read) and (write) at Localizations
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> ![image](https://user-images.githubusercontent.com/29138111/120278588-0c548900-c2e8-11eb-8d79-101c919130f2.png)

Hey!
Which version of the plugin are you using?
Are you sure your entire setup is up to date? I just tried with the latest version of LuckPerms/EssentialsX/ProtocolLib (b503)/Chc-Red 10.4.5, and it worked perfectly fine for me.

Also, in your `server.properties`, make sure you used a correct `server-name=` value. The server-name can't contain spaces/special characters.

**Comment by waiching514** [comment]
![image](https://user-images.githubusercontent.com/29138111/120404026-08704780-c378-11eb-802d-c932f728e4f0.png)
here is my placeholder and server.properties:
![image](https://user-images.githubusercontent.com/29138111/120403892-b92a1700-c377-11eb-9f6d-311ccbfe984d.png)

![image](https://user-images.githubusercontent.com/29138111/120403996-f5f60e00-c377-11eb-9ff2-483ecd337a02.png)

**Comment by mav2020** [comment]
Did you ever do this?
`/papi ecloud download Server`
PlaceholderAPI will take over the server name, but if you haven't loaded the extension it might the problem.

**Comment by waiching514** [comment]
yes

**Comment by mav2020** [comment]
What do you get if you put this in?
`/papi parse me %server_name%`

**Comment by waiching514** [comment]
It can show the server name

**Comment by mav2020** [comment]
Can you post the relevant format code showing how the server is called?
Also, for the 'read/write' in localization, do you mean this part?
```
  Tooltip_Join_Write: '&2Click to join this channel for writing.'
  Tooltip_Join_Read: '&2Click to join this channel for reading.'
```

**Comment by waiching514** [comment]
> Can you post the relevant format code showing how the server is called?
> Also, for the 'read/write' in localization, do you mean this part?
> 
> ```
>   Tooltip_Join_Write: '&2Click to join this channel for writing.'
>   Tooltip_Join_Read: '&2Click to join this channel for reading.'
> ```

I mean /ch list (read) and (write)

**Comment by kangarko** [comment]
If you use PlaceholderAPI then you need to install the server expansion pack or use any other relevant expansion to show the server's name
