### ISSUE TITLE
Whitelist words that contain a swear word....

### ISSUE THREAD

**Issue by Jawakotb** [kangarko/ChatControl#104]
I am sorry to ask this but I must have missed it somewhere in the tuts you have, but how can I 'whitelist' a word that contains a blacklisted word.  In particular, I need to whitelist 'titan'.

Love the plugin!
Thanks in advance for your help.

**Comment by kangarko** [comment]
Hey, simply open the rules/rules.txt file, which is the main one, find following line:

`# Blocks 'titt'`

and replace the whole line that starts with 'match' with following:

`match \b(t+(\W|\d|_)*i+(\W|\d|_)*t+(\W|\d|_)*(t|s)+(\W|\d|_)*)`

Now, words like titan, titanium and their derivates will be ignore, but words like titt or tits remain blocked. This change will be pushed into the plugin, though.
