### ISSUE TITLE
The leave message cannot display the player's prefix

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#1044]
If i use
```rs
group default
message:
- &7{player_prefix+}{display_name}{player_suffix} &fLeave Server
```
The same format, but the prefix and suffix are displayed when the player joins, but there is no other name since the beginning.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> If i use
> 
> ```rust
> group default
> message:
> - &7{player_prefix+}{display_name}{player_suffix} &fLeave Server
> ```
> 
> The same format, but the prefix and suffix are displayed when the player joins, but there is no other name since the beginning.
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
Can you confirm that Vault is installed and up to date? Same for ChatControl?
As said on the wiki, these placeholders require Vault (https://github.com/kangarko/ChatControl-Red/wiki/Variables#native-variables)

**Comment by BearLeonLight** [comment]
> > If i use
> > ```rust
> > group default
> > message:
> > - &7{player_prefix+}{display_name}{player_suffix} &fLeave Server
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The same format, but the prefix and suffix are displayed when the player joins, but there is no other name since the beginning.
> > Minecraft Version: 1.16.5
> > MySQL: true
> > BungeeCord: true
> 
> Hey!
> Can you confirm that Vault is installed and up to date? Same for ChatControl?
> As said on the wiki, these placeholders require Vault (https://github.com/kangarko/ChatControl-Red/wiki/Variables#native-variables)

As described in my question, the normal prefix can be displayed when it is added in the same format, but it will not be displayed for leaving. If there is no Vault, it will not even be displayed for joining.
I also make sure I have Vault and PAPI installed.

**Comment by kangarko** [comment]
It's because the data are not available since the player has already left. 

As last resort you can check if you don't have "quit" in Messages.Async because this is known to cause the problem.
