### ISSUE TITLE
timed messages bug with script

### ISSUE THREAD

**Issue by C0ffeL0Ve** [kangarko/ChatControl#1045]
My server uses the levelledmobs plugin(it alters the health and damage of a mob) and i made a simple script to only show a certain timed message if a player is under the level 50, my problem is that yesterday the script worked and it did not show the messages when i configured and now is showing the message, i think it is a bug.

for clarification i will paste the timed.rs rules and the script that i made inside the variables from chatcontrol-red

timed.rs

```
# mundo world inside cave
group caverna
delay 180 second
require sender script {player_inside_cave}
require sender world world
prefix &8&l[&4&l!&8&l]
message:
- The messages and other messages and messages.

```

ChatControlRed/variables/player-inside-cave.yml

```
# Where should this variable be used?
#
# FORMAT = used in your formats with {syntax}, players cannot use it
# MESSAGE = players can use it with [syntax] in their chat messages

Type: format
Key: player_inside_cave
Value: '''{y}'' < ''50'' ? ''true'' : ''false'''
Sender_Condition: ''
Sender_Permission: ''
Receiver_Condition: ''
Receiver_Permission: ''
```

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

ChatcontrolRed version 10.4.5

I really need this timed.rs to work and in the wiki that i read it should be working i think.

**Comment by ElBananaa** [comment]
Hey!
This looks like a weird issue. I'll try to reproduce this issue asap, but it'll probably be tomorrow.
In the meantime, could you provide the `general.txt` file generated in your `/chc debug` output zip file?
We don't need the entire zip file, so if you'd like to keep your configuration private, you can. :)

**Comment by C0ffeL0Ve** [comment]
im sorry if this sounds a little selfish but is there a way that i can send it privately? by my way of thinking showing the general txt is equal to showing the entire debug file

**Comment by ElBananaa** [comment]
> im sorry if this sounds a little selfish but is there a way that i can send it privately? by my way of thinking showing the general txt is equal to showing the entire debug file

Hey!
Sure, send it to matej@mineacademy.org

**Comment by C0ffeL0Ve** [comment]
> > im sorry if this sounds a little selfish but is there a way that i can send it privately? by my way of thinking showing the general txt is equal to showing the entire debug file
> 
> Hey!
> Sure, send it to [matej@mineacademy.org](mailto:matej@mineacademy.org)

I've send a message to matej with the entire debug file

**Comment by kangarko** [comment]
This script will work:


```
# Where should this variable be used?
#
# FORMAT = used in your formats with {syntax}, players cannot use it
# MESSAGE = players can use it with [syntax] in their chat messages
Type: format

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand"
Key: player_inside_cave

# The value the key will be replaced to.
# This uses JavaScript and must return a boolean value.
Value: player.getLocation().getBlockY() < 80

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: ''

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

# See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
# and only show the message to those receivers for which the condition returns true.
Receiver_Condition: ''

# What permission must the message receiver have in order for this variable to display to them?
Receiver_Permission: ''
```
