### ISSUE TITLE
TAB LIST SMALL FEATURE

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#1047]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)

this is something i and so many people will want and will drop so many tablist plugins (NameTagEdit, Animated Tablist, TAB, Animated NameTag , ...) because of this simple feature Priority

2. What would happen if we won't implement this feature? How's your server being affected?

we should set an actual plugin feature that is already there to (Tab_List: Enabled: false) and use another plugin like NameTagEdit and put our format to (%chatcontrolred_prefix_tag%%chatcontrolred_nick%%chatcontrolred_suffix_tag%) because it's have priority system (NameTagEditis light but i can insure you that it's buggy time to time)

this plugin is one of the best plugin in the world and is unmatched, it's have everything , mysql support, bungee support, nick name mails and so much stuff, it even have tablist and tab complete option the one thing i suggest in tablist part to add vault prefix and suffix priority in the tab list, like (prefix.2.abc)permission is higher priority then (prefix.1.ab) like group weights

**Comment by kangarko** [comment]
Thanks, however we're not a tab-list plugin but a chat plugin, we won't support much larger feature set besides what's already in the Tag section of settings.yml
