### ISSUE TITLE
Message conditions and rule options of messenger

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#1048]
I request new rules and conditions. I hope to add conditions. If the message recipient is Discord, ignore it and not send the message to Discord. I hope it can be added.
```
{receiver_is_player} The message receiver is the player
{receiver_is_console} The message receiver is the console
{receiver_is_discord} The message receiver is console discord
```
Because I added a Time message, I set it to be displayed only to unregistered players, but it will be sent to Discord. At present, I have to create another in-game channel and set Discrod=false to solve it, but it will reach other The Time message will not be displayed on Discord.

In addition, is it possible to add execution commands, such as when the time is up, from the background, the player, and the OP, select an execution command. The target of the command can be the player receiving the message, all players, and random players.

1
```
1.1 It is very helpful for not wanting to send announcements, or specific messages to Discord or just display them on Discord.
1.2 Then it is very useful for time rewards and random rewards. I want to give 2 players diamonds every 1H. I hope that it can be processed through Time without using another sword.
```
2.
```
2.1 If there is no such function, I don't know how to use this plug-in to realize the time message, and only send the message to Discord for the player's display step.
2.2 It turns out that I need to send messages and commands that need to be processed by other inserts, but the format and other settings will run out or even be out of sync.
```

**Comment by kangarko** [comment]
Thanks, we're not considering adding those right now but I've placed them onto our roadmap
