### ISSUE TITLE
[ChatControl] Unhandled exception

### ISSUE THREAD

**Issue by Dasco** [kangarko/ChatControl#105]
Upon executing commands, I'm getting this error: [Server thread/ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl

Server running git-Spigot-2f787db-501372f (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

Pastebin: http://pastebin.com/GKd6ebjf

**Comment by Dasco** [comment]
The problem seems to be that the plugin chatcontrol and ProtocolLib aren't working together.(http://www.spigotmc.org/resources/chatcontrol.271/)

chatcontrol version: v5.0.8b
ProtocolLib version: 3.6.3-SNAPSHOT

**Comment by kangarko** [comment]
Please update ProtocolLib to its latest development build
