### ISSUE TITLE
Players get kicked out of their channels

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#105]
> For the first issue, open join.rs and look for `message:` key that is empty. Remove that key.
> 
> Regarding the other issue, I will add "Bungee" option for channels so you can disable that channel from sending over BungeeCord

Continued on from [https://github.com/kangarko/ChatControl-Red/issues/92](https://github.com/kangarko/ChatControl-Red/issues/92)

I think that error message wasn't to do with my issue then. It would appear at random points, everyone online the server gets kicked out the channel they're in? Nothing shows in console or anything? Is there anything in the plugin that kicks players out of the channel if I use /ch join to force join them to a channel even if they don't have permission for that channel?

**Comment by kangarko** [comment]
We may check if players have permissions to be in their channel if the cache gets cleared. The cache gets cleared after some time to save memory, so ensure players have permissions to be in their channels in their proper mode.

However, those removals are printed to console with "@" messages. This is our code:

https://bitbucket.org/kangarko/chatcontrol-red/src/35b04db6816b299d8161507173a3a1c11493f718/src/main/java/org/mineacademy/chatcontrol/PlayerCache.java#lines-201

**Comment by kangarko** [comment]
Please test the next version going out today for this issue.
