### ISSUE TITLE
error

### ISSUE THREAD

**Issue by moniemntim** [kangarko/ChatControl#1050]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

------------------------------------[ 05.06.2021 18:18:27 ]-----------------------------------
ChatControlRed 10.2.3 encountered a FoException
Running Paper 1.16.5-R0.1-SNAPSHOT and Java 11.0.11
Plugins: LuckPerms v5.2.76, PartyAndFriendsGUI v1.0.215-E, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, ProtocolLib v4.5.1, ChatControlRed v10.2.3
----------------------------------------------------------------------------------------------

More Information: 
Unknown action named: PLAYERS_SYNC_NAMES. Available: remove_message, clear_chat, forward_command, mute, sound, channel, spy, toast, announcement, me, motd, notify, plain_broadcast, plain_message, simplecomponent_message, json_broadcast, list_players_request, list_players_response, db_update, reply_update, mail_sync, players_sync
FoException Report: Unknown action named: PLAYERS_SYNC_NAMES. Available: remove_message, clear_chat, forward_command, mute, sound, channel, spy, toast, announcement, me, motd, notify, plain_broadcast, plain_message, simplecomponent_message, json_broadcast, list_players_request, list_players_response, db_update, reply_update, mail_sync, players_sync
	 at org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60)
	 at org.mineacademy.chatcontrol.lib.bungee.message.Message.setAction(Message.java:84)
	 at org.mineacademy.chatcontrol.lib.bungee.message.IncomingMessage.<init>(IncomingMessage.java:70)
	 at org.mineacademy.chatcontrol.lib.bungee.BungeeListener.onPluginMessageReceived(BungeeListener.java:38)
	 at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
	 at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2910)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> ## ------------------------------------[ 05.06.2021 18:18:27 ]-----------------------------------
> ChatControlRed 10.2.3 encountered a FoException
> Running Paper 1.16.5-R0.1-SNAPSHOT and Java 11.0.11
> Plugins: LuckPerms v5.2.76, PartyAndFriendsGUI v1.0.215-E, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, ProtocolLib v4.5.1, ChatControlRed v10.2.3
> More Information:
> Unknown action named: PLAYERS_SYNC_NAMES. Available: remove_message, clear_chat, forward_command, mute, sound, channel, spy, toast, announcement, me, motd, notify, plain_broadcast, plain_message, simplecomponent_message, json_broadcast, list_players_request, list_players_response, db_update, reply_update, mail_sync, players_sync
> FoException Report: Unknown action named: PLAYERS_SYNC_NAMES. Available: remove_message, clear_chat, forward_command, mute, sound, channel, spy, toast, announcement, me, motd, notify, plain_broadcast, plain_message, simplecomponent_message, json_broadcast, list_players_request, list_players_response, db_update, reply_update, mail_sync, players_sync
> at org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60)
> at org.mineacademy.chatcontrol.lib.bungee.message.Message.setAction(Message.java:84)
> at org.mineacademy.chatcontrol.lib.bungee.message.IncomingMessage.(IncomingMessage.java:70)
> at org.mineacademy.chatcontrol.lib.bungee.BungeeListener.onPluginMessageReceived(BungeeListener.java:38)
> at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
> at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2910)

Hey!
Please update to the latest version of the plugin and try again. Same for protocolLib.

**Comment by kangarko** [comment]
Update ChatControl Red and BungeeControl Red
