### ISSUE TITLE
1.16.5: correct command registration

### ISSUE THREAD

**Issue by Toki-teki** [kangarko/ChatControl#1051]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Can I register my custom commands correctly so that they can be seen by the "Plugin Hide Pro" plugin?
I use it for tab completer

I know the Tab completer is in your plugin but it doesn't hide BungeeCord commands

**Comment by kangarko** [comment]
We register our commands using the Foundation framework which injects them directly into Bukkit's command map and are not planning to change that. I am afraid I won't be able to help you with your custom development.
