### ISSUE TITLE
Helpop 

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#1052]
Wanting to understand how helpop works and it states to look at the chat.yml file but i don't have a chat.yml file?

Also a descriptive wiki would be a good idea so i don't have to bother you with every single question and believe me, i have a lot of questions and will have more no doubt.

Thanks.

**Comment by 00Hrtz** [comment]
Ok so by just running the helpop command with a message it's saying in not so many words that i have to create a helpop channel, i'll do that but some further info would be appreciated, not sure why i can't find the chat.yml file.

**Comment by ElBananaa** [comment]
Hey,
It looks like there's absolutely no helpop feature in the plugin as you can see on[ this video,](https://i.gyazo.com/e5c08d9cc2da4d8f94cf4218b37acf86.mp4) it looks like your issue is related to another plugin.

**Comment by 00Hrtz** [comment]
No that's incorrect, ill show you exactly what's inside the helpop.yml file that's in chatcontrolreds files on my Server. this is the first time ive seen it myself so i never created it and i'm the only admin/op.

The helpop.yml file in CCR says as follows.

`
 -----------------------------------------------------------------------------------------
 The default chat format used in the global channel.
 -----------------------------------------------------------------------------------------

The parts of this format.
Parts:
  
 See the chat.yml format file for a tutorial on how this works.
  everything:
    Message: '&8[&dHelpOp&8] &f{player_name}&7: &f{message}'`

`

**Comment by 00Hrtz** [comment]
And how can it be related to another plugin when Chat Control Red is the only Chat plugin on my Server?

The fact i never new what helpop even was until today, also the fact i am and have always been the only person with access to my server files along with the fact i have had no other chat plugin on my server other then chat control red and finally, the fact a helpop.yml sits happily in my chat control red formats folder suggests otherwise. Not to mention it's code layout matches how chat control red says it should.

**Comment by ElBananaa** [comment]
> No that's incorrect, ill show you exactly what's inside the helpop.yml file that's in chatcontrolreds files on my Server. this is the first time ive seen it myself so i never created it and i'm the only admin/op.
> 
> The helpop.yml file in CCR says as follows.
> 
> ## `
> ## The default chat format used in the global channel.
> The parts of this format.
> Parts:
> 
> See the chat.yml format file for a tutorial on how this works.
> everything:
> Message: '&8[&dHelpOp&8] &f{player_name}&7: &f{message}'`
> 
> `

Alright, after a file reset, it looks like the HelpOp file is now present.
To explain what HelpOp is, it's basically a channel in which your messages are sent to the staff, and only the staff can see them.
This is something that already exists since a while in plugins such as EssentialsX.

The setup is pretty simple, it works like any other channel.

**Comment by 00Hrtz** [comment]
Thank you, for a moment there i thought i was going insane and losing my marbles.
