### ISSUE TITLE
PNG Message

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#1053]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

I've checked the tutorial page but can''t find the answer to this question.

![unknown](https://user-images.githubusercontent.com/66942713/120906212-70ac7b00-c64f-11eb-8c9f-011e65e36c3e.png)

Is it possible to do this with CCR, have a png display with a message along side it post by command in a private message to a player?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: false
> 
> I've checked the tutorial page but can''t find the answer to this question.
> 
> ![unknown](https://user-images.githubusercontent.com/66942713/120906212-70ac7b00-c64f-11eb-8c9f-011e65e36c3e.png)
> 
> Is it possible to do this with CCR, have a png display with a message along side it post by command in a private message to a player?

Hey!
Yes this is totally possible to do this with the plugin.
Actually, the image shown ingame is a special character which was changed in a resource pack.
Here's a tutorial to do this : https://www.reddit.com/r/admincraft/comments/llrgty/does_anyone_know_how_to_put_a_image_on_the/

**Comment by 00Hrtz** [comment]
I followed the instructions to the letter.

created a 75x75 pixel png image  named sir_craftypants.png, added the file locations namespace customitems..

added the following code to the default.json file

{"file":"customitems:font/sir_craftypants.png","chars":["\ue238"],"height":9,"ascent":5,"type":"bitmap"}

Uploaded and loaded the resource pack on the server, even though i'm admin/opped, i disabled deny unicode. 

typed \ue238 in chat and all that appeared was \ue238.

**Comment by kangarko** [comment]
No sorry that's a different way of showing those images. We only support our own custom low-resolution parser right now.

**Comment by ElBananaa** [comment]
> I followed the instructions to the letter.
> 
> created a 75x75 pixel png image named sir_craftypants.png, added the file locations namespace customitems..
> 
> added the following code to the default.json file
> 
> {"file":"customitems:font/sir_craftypants.png","chars":["\ue238"],"height":9,"ascent":5,"type":"bitmap"}
> 
> Uploaded and loaded the resource pack on the server, even though i'm admin/opped, i disabled deny unicode.
> 
> typed \ue238 in chat and all that appeared was \ue238.

Hey!
It didn't work because you don't have to type `\ue238` but the actual character. As you can see on this website (https://www.fileformat.info/info/unicode/char/e238/index.htm) the character is actually ``. (You can find it near : `string.toUpperCase()`.

**Comment by 00Hrtz** [comment]
> 
> 
> > I followed the instructions to the letter.
> > created a 75x75 pixel png image named sir_craftypants.png, added the file locations namespace customitems..
> > added the following code to the default.json file
> > {"file":"customitems:font/sir_craftypants.png","chars":["\ue238"],"height":9,"ascent":5,"type":"bitmap"}
> > Uploaded and loaded the resource pack on the server, even though i'm admin/opped, i disabled deny unicode.
> > typed \ue238 in chat and all that appeared was \ue238.
> 
> Hey!
> It didn't work because you don't have to type `\ue238` but the actual character. As you can see on this website (https://www.fileformat.info/info/unicode/char/e238/index.htm) the character is actually ``. (You can find it near : `string.toUpperCase()`.

My images didn't work because the metadata was missing from my font/default.json file, I've fixes it now and my image ranks and images are working in luckperms ranks and chat.
