### ISSUE TITLE
TAG Customname Bug

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#1054]
in TAG part
   true = alter player's custom name (may show above him) if he sets a nick
   false = feature disabled
 Change_Customname: true
that don't work and true or false don't matter at all, above name don't change even player have nick prefix and suffix at the same time

Minecraft Version: 1.16.5 **(Edited as the author specified a wrong version)**
MySQL: true
BungeeCord: true
plugins: ChatControlRed, Luckperms, Vault

**Comment by kangarko** [comment]
Not supported for Minecraft 1.4.5

**Comment by FakEEE14** [comment]
my bad i set the plugin version
1.16.5

**Comment by ElBananaa** [comment]
The author opened a new issue : #1061 
@FakEEE14 Next time, please either continue on your actual issue, and wait for us to reopen it, or open a new issue, but don't comment on both ;)

**Comment by FakEEE14** [comment]
sorry i think the closed one don't used
never happen again

**Comment by ElBananaa** [comment]
> sorry i think the closed one don't used
> never happen again

No worries haha, ;)
