### ISSUE TITLE
1.16.5: New line tags don't appear to function correctly

### ISSUE THREAD

**Issue by ScottGB** [kangarko/ChatControl#1055]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Unsure this is a bug but \n doesn't work in my configs, so I try the alternatives but it automatically gets put back to \n.

In BungeeCord settings.yml

**Comment by kangarko** [comment]
Try using software described at to save files:

https://github.com/kangarko/ChatControl-Red/wiki/Use-Right-Encoding

There's a tiny chance it's your system's issue with line separators. We've tested this on Windows and macOS, if you're on Linux it can and should work also but you may need to google it up.

**Comment by ScottGB** [comment]
Issue persists when using other editors, mentioned in the link. They automatically convert |- into \n

This is happening in BungeeControl. I also noticed that HEX colours don't appear to work in BungeeControl

**Comment by kangarko** [comment]
Apologies, unable to fix, cannot track why this is caused :/

Yeah we didn't implement HEX support for BungeeControl just yet, this may come in the next version(s).
