### ISSUE TITLE
1.16.5: Incompatible with PremiumVanish

### ISSUE THREAD

**Issue by masterhacka** [kangarko/ChatControl#1059]
Hi there,

I am using ChatControl and PremiumVanish on my servers. Normally when typing a message whilst vanisehd it isn't send and you have to confirm it. Unfortunately with ChatControl the message is sent anyway. I hope you can help me

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Hi there,
> 
> I am using ChatControl and PremiumVanish on my servers. Normally when typing a message whilst vanisehd it isn't send and you have to confirm it. Unfortunately with ChatControl the message is sent anyway. I hope you can help me
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
This issue has been reported multiple times with the plugin after a plugin reload, make sure you have the `Chat_Listener_Priority: HIGH` in ChatControlRed settings file, and all the `CompatibilityOptions` set to `HIGH` in PremiumVanish config file, then restart the server. Once again, avoid reloading ChatControlRed as this can cause issues. Let us know if it fixes the issue.

**Comment by masterhacka** [comment]
My configs are already set up like this. Before I did use ChatControlPro but without Bungeecord and everything worked great. Unfortunately with ChatControlRed and Bungeecord it doesn‘t work.

**Comment by ElBananaa** [comment]
> My configs are already set up like this. Before I did use ChatControlPro but without Bungeecord and everything worked great. Unfortunately with ChatControlRed and Bungeecord it doesn‘t work.

It's pretty weird. It works perfectly fine on my side. Let's wait for Kangarko to see if there's anything he could do about it.

**Comment by kangarko** [comment]
Does it work (i.e. PremiumVanish asks if you really want to send a chat message) if you turn Bungee off for ChatControl Red?

You can also use our own anti accidental typing feature by setting Channels.Prevent_Vanish_Chat to true in settings.yml for Bukkit server's ChatControl Red config.

**Comment by masterhacka** [comment]
Probably it could work but I want to use global chattint, so I can't disable it right now.

Your own accidental typing feature works perfectly!

**Comment by kangarko** [comment]
Thanks! If you need any more help just let me know below.
