### ISSUE TITLE
does ChatControl monitor for command spamming?

### ISSUE THREAD

**Issue by Jawakotb** [kangarko/ChatControl#106]
I think it does, but I am confused as to where I can modify and/or disable this feature.

Any assistance is greatly appreciated.
Thanks!

**Comment by EvilOlaf** [comment]
You can disable this by giving your players the bypass permission.

**Comment by kangarko** [comment]
There are two ways of lowering command spamming.

a) Enforce so players must wait between sending their next message, in seconds. This is found below. Set to 0 to disable.
`Anti_Spam.Commands.Delay_Between_Commands`

b) Block players' message that is too similar to their previous one. This is found below. Set to 0 to disable. The number is how much similar in percent the message should be to be blocked. It is eighty by default, meaning a message 80% or more similar to the previous one will be blocked.
`Anti_Spam.Commands.Similar_Percentage_Block`
