### ISSUE TITLE
Replace repeated characters

### ISSUE THREAD

**Issue by MineTheCube** [kangarko/ChatControl#106]
I read the main page of plugin and its configuration, but I didn't found how to replace repeated characters.

I mean things like that: "heeeeeeey !!!!!!!" > "hey !", or at least block theses messages.

Can you add this feature ?

**Comment by kangarko** [comment]
Anti spam can heavily be improved by adding custom filters. Unfortunately I am not good with regular expressions, so you might ask f. ex. on spigot forums or use some regex tester.

**Comment by MineTheCube** [comment]
The regex to match 3 or more repeated chars is `/(.)\1{2,}/`.

But can't we replace them ? Like `/(.)\1{2,}/` by `/$1/`, so "heeeeey !" will be replaced by "hey !" without blocking it..

Maybe in chat.txt, but do references work in these rules ? (I can't test it for now, sorry)

**Comment by kangarko** [comment]
Yes you can use (for example) following rules to replace repeated characters to two repeats maximum:

# for one character
match ([^0-9])(?=\1\1+)
then replace

# for two repeated characters
match (..)(?=\1\1+)
then replace

# for three repeated characters 
# fixes "lollollollollol"
match (...)(?=\1\1+)
then replace

**Comment by MineTheCube** [comment]
Ok, so I put this in rules/chat.txt:
```
match (.)\1*(?=\1\1)
then replace
```
It removes everything followed by 2 repeated characters. E.g; "Heeeeeeey" becomes "Heey".

**Comment by kangarko** [comment]
So it is working properly?

**Comment by MineTheCube** [comment]
Oh forgot to mention that yes, it works just fine ! :)

**Comment by kangarko** [comment]
Allright :)
