### ISSUE TITLE
Gradient issue continues

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#106]
In #95 there were 2 questions, and 1 of them didn't get any answer asa i saw. And i tested it myself, when you try tu put gradient into formats, after plugin or server reloads - in changes its format and throws an error because this format is not like it is supposed to be

This is how gradient looks like after a reload/restart:
![image](https://user-images.githubusercontent.com/62369973/99638248-ff143300-2a56-11eb-9d82-999464c6e911.png)
 And there is an error:
https://pastebin.com/Dj7W3a03

**Comment by kangarko** [comment]
Thank you, sorry for not clarifying it — I will patch this to the next version.
