### ISSUE TITLE
1.16.5: Item from death message shows incorrectly

### ISSUE THREAD

**Issue by YusakiDev** [kangarko/ChatControl#1060]
When You kill a player with Enchantments that is not Minecraft it will disappear (Ecoenchants)
It also displays the enchants roman number incorrectly as it turns back into a normal enchant format.

kill message: https://i.imgur.com/4Vfw0Pf.png

Actual Item: https://i.imgur.com/63q5DTp.png

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> When You kill a player with Enchantments that is not Minecraft it will disappear (Ecoenchants)
> It also displays the enchants roman number incorrectly as it turns back into a normal enchant format.
> 
> kill message: https://i.imgur.com/4Vfw0Pf.png
> 
> Actual Item: https://i.imgur.com/63q5DTp.png
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false

Hey!
This is due to the fact that the variable `/plugins/ChatControlRed/variables/killer-item.yml` is only getting vanilla enchants. But feel free to edit the variable to work with EcoEnchants

**Comment by kangarko** [comment]
I am sorry, as these variables utilize JavaScript we're unable to provide custom coding for you and hook into a third party plugin
