### ISSUE TITLE
1.16.5: Change_Customname not working 

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#1061]
in TAG part
true = alter player's custom name (may show above him) if he sets a nick
false = feature disabled
Change_Customname: true
that don't work and true or false don't matter at all, above name don't change even player have nick prefix and suffix at the same time

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true
plugins: ChatControlRed, Luckperms, Vault

**Comment by ElBananaa** [comment]
> in TAG part
> true = alter player's custom name (may show above him) if he sets a nick
> false = feature disabled
> Change_Customname: true
> that don't work and true or false don't matter at all, above name don't change even player have nick prefix and suffix at the same time
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> plugins: ChatControlRed, Luckperms, Vault

Hey!
I'm not sure what's causing this issue. In your settings file, under `Tag.Apply_On`, make sure it looks like that : `Apply_On: [prefix,nick,suffix]`

**Comment by FakEEE14** [comment]
yeah all functions work but not this one

**Comment by ElBananaa** [comment]
> yeah all functions work but not this one

It's kinda weird. I don't know if ProtocolLib is required for this, I don't think so, but would you mind trying to install it and see if it works?

**Comment by FakEEE14** [comment]
i did this and still don't work
latest 505 protocolib

**Comment by kangarko** [comment]
Likely another plugin that's causing it, try only using ChatControl Red on the server. Also use Paper not any other fork.

**Comment by FakEEE14** [comment]
i'm using paper 772 build but this was from early 600 that didn't work
there is no other plugins installed than luckperms , vault , protocolib and chatcontrolred

**Comment by broken1arrow** [comment]
> i'm using paper 772 build but this was from early 600 that didn't work
> there is no other plugins installed than luckperms , vault , protocolib and chatcontrolred

Do it works now?

**Comment by ElBananaa** [comment]
Hey!
Sorry for the delay.
So, after a few tests, I can confirm that both both `Change_Displayname` and `Change_Customname` features aren't working.
Tests were ran on a completely fresh setup, with only Vault, ProtocolLib b605, Chc-red v10.4.9 under java 16 (I'm using NashornPlus v1.1.0), and paper 1.16.5 b778. There's no other plugins.

**Comment by kangarko** [comment]
Thanks and sorry for the big delay. I just checked and it seems this method no longer works for Players. I will remove it from the next release to prevent confusion and try finding a library for this since implementing this on our own is a bit of a complex project.
