### ISSUE TITLE
Possible to detect bungee online status before warning about offline?

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#1063]
ChatControlRed outputs this warning when the server is offline.
```
[15:06:38] [Server thread/INFO]: Warning: Your server is in offline mode, where UUIDs generate for every username. We recommend setting UUID_Lookup to false in mysql.yml to avoid data issues.
```

However it is required for the main server to be offline when behind a proxy such as BungeeCord. Is it possible to check for ``bungeecord: true`` status in spigot.yml or ``bungee-online-mode: true`` in paper.yml before warning? Or check for a BungeeCord ping? I assume this would be an entirely cosmetic improvement since functionally it shouldn't matter as long as the proxy is online.

**Comment by ElBananaa** [comment]
> ChatControlRed outputs this warning when the server is offline.
> 
> ```
> [15:06:38] [Server thread/INFO]: Warning: Your server is in offline mode, where UUIDs generate for every username. We recommend setting UUID_Lookup to false in mysql.yml to avoid data issues.
> ```
> 
> However it is required for the main server to be offline when behind a proxy such as BungeeCord. Is it possible to check for `bungeecord: true` status in spigot.yml or `bungee-online-mode: true` in paper.yml before warning? Or check for a BungeeCord ping? I assume this would be an entirely cosmetic improvement since functionally it shouldn't matter as long as the proxy is online.

Hey!
As you said in your message, this is only a warning. I don't think silencing this warning is a good idea since it's only a useful message. One more line in your log file won't change anything, If your proxy is running in online-mode, then don't worry about it, it won't cause any issues.

**Comment by kangarko** [comment]
This would make no difference, I still recommend you go with the UUID_Lookup option as suggested in that message and see if that causes anything, it should not, except that it will reset a player's data when he changes Mojang's username.
