### ISSUE TITLE
1.16.5: BungeeControl switch event error

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1067]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

This is the error I still get on a switch: https://pastebin.com/hDxkWGVj

Wonder if that also causes the join/quit message to show as vanilla minecraft sometimes:

![image](https://user-images.githubusercontent.com/5664135/121169093-f00a9c00-c853-11eb-902d-173d69136f36.png)

https://media.discordapp.net/attachments/184638760720400384/851523294708105266/unknown.png

**Comment by kangarko** [comment]
Thanks, should be patched now
