### ISSUE TITLE
Vanished players and ranged chat

### ISSUE THREAD

**Issue by C0ffeL0Ve** [kangarko/ChatControl#1068]
I encountered an issue that When i activate vanish and start to look into the player, when they type something on the chat i get busted, i have created a Local channel with range and when they type something on there it doesnt apper the message that they are alone.

is there some way of fixing this?

Minecraft Version: 1.X.Z
MySQL: true/false
BungeeCord: true/false

**Comment by ElBananaa** [comment]
Hey!
Sorry for the delay. As far as I know, this issue has never been reported before. Unfortunately, I'm unable to try to reproduce your issue for now, so let's wait for Kangarko.
In the meantime, could you please update your message with the correct informations regarding your server version, your usage of mysql and your usage of bungeecord?

**Comment by kangarko** [comment]
Seems like your ChatControl Red is outdated, update it please. If I am mistaken comment below :)
