### ISSUE TITLE
1.16.5: ChatControlRed not working on OpenJDK 16.0.1 (Debian 10.7)

### ISSUE THREAD

**Issue by ImSapphire** [kangarko/ChatControl#1069]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false
![image](https://user-images.githubusercontent.com/48931512/121260471-0413c500-c877-11eb-8f21-72ec0e77fc18.png)
Whenever I set OpenJDK 16.0.1 as the default Java version, this error shows up in console. I can't send a debug ZIP as the plugin is disabled.
![image](https://user-images.githubusercontent.com/48931512/121260656-39b8ae00-c877-11eb-8bcc-f19bdf37692c.png)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> ![image](https://user-images.githubusercontent.com/48931512/121260471-0413c500-c877-11eb-8f21-72ec0e77fc18.png)
> Whenever I set OpenJDK 16.0.1 as the default Java version, this error shows up in console. I can't send a debug ZIP as the plugin is disabled.
> ![image](https://user-images.githubusercontent.com/48931512/121260656-39b8ae00-c877-11eb-8bcc-f19bdf37692c.png)

Hey!
As said on the wiki page, you need to use NashornPlus with java 15+ (https://mineacademy.org/nashorn/) :)
