### ISSUE TITLE
little bug with clearchat, and suggestions for next Update 5.0.9

### ISSUE THREAD

**Issue by CloudeLecaw** [kangarko/ChatControl#107]
Current found Bugs:
    - The clear commands clears the whole chat and ignore the argument

    Ideas for next version:
    - placeholder %group, %group_prefix, %group_suffix and %displayedname (for /nick commands for exemple)
    - a Chatformat for each Permissiongroup (not needed if the placeholders would be there)
    - maybe the spy can turn into a commandwatcher with bypass permission and the abilities to ignore own commands. (whispering private messagesetc, these all are commands too, so why not?)
    - extand the clear command so u can give users permissions to clear just their own chat.
    (When many players are very chatty this is a very very useful feature)
    - a list in the setting of whitelisted urls that the users can post (ip of the server or www.google.com, etc..)
    -a better featue for the name notification: Currently u have to write the Full name. but when Names get longer then mostly players just use Shorts like just "cloud" for my name. An information sound when 4 letters equal of a playername would be cool and maybe the name can get colored in chat? (color chooseable in the settings)
    - maybe a bit better extantion of the filters. Currenly lets say i have the word Spammer on my list
    an someone write "Sppaaammmeeerrr" then the word cant scaned as Spammer from the plugin.
    -a globalmute command that completly mutes/unmutes the chat
- negation of permission works a bit not really usefull....
example:
my admins have some neagtions:
    - -chatcontrol.bypass.cap
    - -chatcontrol.bypass.replace
    - -chatcontrol.bypass.capitalize
    - -chatcontrol.bypass.punctuate
normal this now should activate the chat replacer, the capfilter and the capitalizefilter
but without the neagtion of     - -chatcontrol.bypass.rules nothing happens.
problem: if they got the negation of     - -chatcontrol.bypass.rules
then all filter work on them :3 also the commands, swear, etc...

    Edit:
    - take a look over the basic advertice filter :D
    i added a few thing in it and added some new. now the filter blocks urls, and ips :)
    before that players was able write in chat example "hallo.de" and other URLs.
    (u forgot some \b in the settings of it)

    I am using:
    Spigot 1.8.3
    latest ProtocolLib
    latest Version of ChatControl 5.0.8b

**Comment by kangarko** [comment]
Responded at spigot forums.
