### ISSUE TITLE
Problem Blocked Commands

### ISSUE THREAD

**Issue by ireeskenz** [kangarko/ChatControl#107]
Hi, i have problem with our beautiful Plugin. Firstly in the log i have this : http://pastebin.com/n3KFn3rC

But plugins is still working except blocked commands : /bukkit:pl

Here is my file "Commands.txt" : http://pastebin.com/dq5BPTcn

**Comment by kangarko** [comment]
The console error is not complete, thus I cannot locate the problem.

To the rule, insert a \ before the :
match ^/bukkit\:plugins

and ensure you are not operator, since they are ignored.
