### ISSUE TITLE
MythicMobs ID Matching

### ISSUE THREAD

**Issue by xGlitchette** [kangarko/ChatControl#1070]
ChatControlRed currently only has the ability for custom MythicMobs death messages based on their name; This can be seen as problematic as changing the boss' name (such as health bars) break the message and skip over it.

1. This would benefit people using MythicMobs and chc together as chc completely overrides the death messages which mm can set as well, and it's painful to comment out all the other deathmessages (it uses yml (#) comments in a js(//) file.

2. If this feature was not implemented, It'd be quite bothersome to make  custom death messages for every mob, and would limit creativity in that aspect

**Comment by kangarko** [comment]
Thank you very much! Right now we do have other priorities but if I am taking look over death messages system I'll go over your suggestion.
