### ISSUE TITLE
1.16.5: How to connect to API?

### ISSUE THREAD

**Issue by jackderick** [kangarko/ChatControl#1071]
Hello, I'm pretty new to using API and Coding in general.

In my experience in using API from other plugins I just need to include dependencies in pom.xml

But for chat control red I didn't see any dependencies for me to add to use the API

**Comment by ElBananaa** [comment]
> Hello, I'm pretty new to using API and Coding in general.
> 
> In my experience in using API from other plugins I just need to include dependencies in pom.xml
> 
> But for chat control red I didn't see any dependencies for me to add to use the API

Hey!
The plugin API is inside the plugin, so simply add ChatControlRed to your plugin.

**Comment by kangarko** [comment]
Download the ChatControl Red jar, import it as system dependency in pom.xml, then get the ChatControlAPI class where you can start.
