### ISSUE TITLE
1.16.5 Can't get the chat to work, and I believe the plugin keeps resetting nicks

### ISSUE THREAD

**Issue by CrispyDairy** [kangarko/ChatControl#1072]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by CrispyDairy** [comment]
I can't get the chat to work, no matter what I change in the configs. It just keeps using regular minecraft chat. Also, I believe the plugin keeps resetting people's /nick on server restart. I've now spent 2 hours trying to figure this out, but haven't gotten anywhere. I even followed the first-format.yml guide here on github.

**Comment by ElBananaa** [comment]
> I can't get the chat to work, no matter what I change in the configs. It just keeps using regular minecraft chat. Also, I believe the plugin keeps resetting people's /nick on server restart. I've now spent 2 hours trying to figure this out, but haven't gotten anywhere. I even followed the first-format.yml guide here on github.

Hey!
You need to follow the ingame setup intructions which can be found here : https://github.com/kangarko/ChatControl-Red/wiki/Installation
Informations are also given in your console output and in the chat ^^

Once this is done, simply turn on the channel system in the plugin settings.

**Comment by CrispyDairy** [comment]
Alright, I'll do that once the server restarts in an hour. I'll let you know if I encounter any issues after that, and if not I'll close this thread myself :)

**Comment by CrispyDairy** [comment]
Yeah, this is still an issue. The plugin won't replace regular vanilla chat

**Comment by CrispyDairy** [comment]
Can the issue be that our server runs on purpur?

**Comment by TheIntolerant** [comment]
I believe banana once said, he uses purpur so I assume using that server software should be fine. Plus I know a few others that use purpur.

**Comment by TheIntolerant** [comment]
I could be wrong about this so forgive me if I am, I believe you need vault for chat to work. If that isn't the issue, your next best cause of action would be to provide your **/chc debug** file either as an upload on this ticket or email it to kangarko.

**Comment by CrispyDairy** [comment]
I got it working! The issue was a missing # from what was supposed to be a comment
