### ISSUE TITLE
1.16.5: Can't switch channels

### ISSUE THREAD

**Issue by CrispyDairy** [kangarko/ChatControl#1074]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Can't switch channels. I could switch from standard to ranged, but when I try to switch back it says command failed.

https://pastebin.com/Zve3ySDR

**Comment by CrispyDairy** [comment]
Closed by accident

**Comment by kangarko** [comment]
Update to next version, if the error persists then post it below.

**Comment by CrispyDairy** [comment]
Alright, well while I'm here, whats the permission to give people the ability to delete individual messages? The thing in chat.yml

**Comment by TheIntolerant** [comment]
It should say in that file

**Comment by CrispyDairy** [comment]
The original report is still and issue, also after giving that permission, they can only view the x, but when they click it it says no permission

**Comment by TheIntolerant** [comment]
Let's continue this on #1081

**Comment by kangarko** [comment]
Closing, lets continue on there. The original error will be fully patched on the next version.
