### ISSUE TITLE
1.16.5: Bossbar only works for 1 person & Customizing the bossbar color/duration/segmentation using the <bossbar> identifier in the rules

### ISSUE THREAD

**Issue by JustDriessen** [kangarko/ChatControl#1078]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6641101/debug.zip)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

When using a timed message with bossbar the only person that is receiving it is the first one that joined the game. Also I have to have the option Messages: on in the config to have the bossbar appear, this is a bit weird because I can add a message in the config aswell. This is not needed due to that.

**Comment by JustDriessen** [comment]
This is what I did in timed.rs:

group bossbar
delay 8000 second
require receiver world Risnox_Towny_Spawn
message:
- Testing messages
then bossbar GREEN SEGMENTED_10 10 Testing message

Wondering if I did something wrong?
Doesn't seem to work without message: option, and it only gives the bossbar to the first person that joined the server

**Comment by ElBananaa** [comment]
> This is what I did in timed.rs:
> 
> group bossbar
> delay 8000 second
> require receiver world Risnox_Towny_Spawn
> message:
> 
> * Testing messages
>   then bossbar GREEN SEGMENTED_10 10 Testing message
> 
> Wondering if I did something wrong?
> Doesn't seem to work without message: option, and it only gives the bossbar to the first person that joined the server

Hey!
I believe the `then bossbar` operator is made to be sent to only one player. So it's either a specified player when you use the `{player}` placeholder in the message, either the latest player who joined.
To send a bossbar to all online players, you need to use the command `/chc announce bossbar`. So, this is how you message should look like : 
```
group bossbar
delay 10 second
require receiver world Risnox_Towny_Spawn
message:
- Zoiets denk ik
then console chc announce bossbar style:SEGMENTED_10 color:GREEN Kipnuggets ofzo iets
```

**Comment by JustDriessen** [comment]
Ah yeah I see the bossbar did work, but is there a way to not have something show up in chat and only have the bossbar at the stop @ElBananaa ?

**Comment by ElBananaa** [comment]
> Ah yeah I see the bossbar did work, but is there a way to not have something show up in chat and only have the bossbar at the stop @ElBananaa ?

Of course you can, here's an example: 
```
group bossbar
delay 15 seconds
message:
- <bossbar> Kipnuggets ofzo iets
```
However, I don't know if you can customize the color, the duration or the style. You'll have to wait for @kangarko for this, but he's on vacations until the 2nd of july ^^

**Comment by JustDriessen** [comment]
Okay the bossbar works now, I would only like to have an option to change its color.

Please someone let me know how to add another color to my bossbar, thanks in advance

**Comment by ElBananaa** [comment]
> Okay the bossbar works now, I would only like to have an option to change its color.
> 
> Please someone let me know how to add another color to my bossbar, thanks in advance

Hey!
Sorry for the delay.
I don't believe this is currently possible using this method.
Kangarko should be back in a few days, so you'll be able to see this with him ^^

**Comment by kangarko** [comment]
Thanks for catching this up Banana! Unfortunately our parser is pretty simple and does not support arguments for the `<X>` parameters at the moment.
