### ISSUE TITLE
Perm nodes

### ISSUE THREAD

**Issue by Tikkle** [kangarko/ChatControl#108]
Okay so,

The owner of the server doesnt want to be spammed with a shit ton of blocking notifications, so i negated the perms right?

    - -chatcontrol.notify.ad
    - -chatcontrol.notify.swear

The dont work. He still sees them. So we de-opped him. He doesnt see them. Re-op him. He sees them. I think the problem is on ur side because I've tried almost everything in the book. Could you make it so that it looks for the perms and not the fact that they're op and its like "OH, you HAVE to be notified cause ur opped!"

**Comment by EvilOlaf** [comment]
If you properly setup your permission system there should be no need for being permanent OP ;)

The permission nodes you mentioned are not true by default, so negating does not have any effect. Seems like also an issue with your permission setup.

What permission system do you use?

**Comment by Tikkle** [comment]
Pex. I have it set up correctly. The owner just insists on being op.

**Comment by EvilOlaf** [comment]
Try `Op_Has_Permissions: true` set to `false`

**Comment by Tikkle** [comment]
Is this in the settings file?

**Comment by Tikkle** [comment]
THank you.
