### ISSUE TITLE
How to disable this message?

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [kangarko/ChatControl#108]
I don't want to define a handler for each of the smiley replacements, it would be useful if you could simply put "dont verbose" like the in the packets file.
![image](https://cloud.githubusercontent.com/assets/3297866/7338690/83f34e2c-ec54-11e4-99de-541fe89b17d9.png)

**Comment by kangarko** [comment]
In settings.yml, set Verbose to false.

**Comment by TheOnlyRealTGS** [comment]
Thank you.
