### ISSUE TITLE
1.16.5: Placeholders are not working in PM formats

### ISSUE THREAD

**Issue by TotallyNotApi** [kangarko/ChatControl#1080]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

debug.zip - https://ufile.io/b3ns4vzw

I'm trying to use PAPI placeholders in PM formats, but they are not being replaced (the placeholders are working - they are working in chat format)
In the same file, placeholder {message} is not working in Hover while other placeholders are working.

**Comment by TheIntolerant** [comment]
Hey, what specific placeholders are not working in PM formats? Also, I checked the debug file and just something to note but for Papi placeholders to work in chatcontrol, {} is used not %%. So try that and see if that fixes your issue.

**Comment by TotallyNotApi** [comment]
> Hey, what specific placeholders are not working in PM formats? Also, I checked the debug file and just something to note but for Papi placeholders to work in chatcontrol, {} is used not %%. So try that and see if that fixes your issue.

    Unfortunately, replacing %% with {} doesnt work either.

Im trying to use placeholders from my own Expansion and from ItemsAdder, I've tried several placeholders from other Expansions and nada.

As I said before, the same placeholders are working for example in default chat format, the only issue is with the PM formats - idk how is this even possible xd, I though all the formats are processed same

**Comment by TotallyNotApi** [comment]
Somehow it works with the latest update, but there is a problem with insertion CHC Placeholder inside the PAPI placeholder.

Example:
`{zeta_getMessageBlock_{message}}` - It translates only the "{message}" placeholder, that comes from CHC

Another issue is with using the placeholder {message} inside hover text.

**Comment by kangarko** [comment]
I apologies, using multiple placeholders within a placeholder is not supported at the moment.
