### ISSUE TITLE
1.16.5: Player joining a new read channel , old write channel will got kick

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1084]
I tried debug mode on channel and mysql do not have any problem,
Also tried set op is still happen

Also, I tried Max_Read_Channels: 3->10 still happen
I can join 3 channel at same time but I cant joining writing channel first

e.g.
I set player permission is
chatcontrol.channel.join
chatcontrol.channel.join.global.write
chatcontrol.channel.join.p.read
chatcontrol.channel.join.$.read

when player join "p(read)" channel will leave a "global(write)" channel (debug/showtips not showing player leave the write channel)
when player join "$(read)" channel will leave a "global(write)" channel (debug/showtips not showing player leave the write channel)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> I tried debug mode on channel and mysql do not have any problem,
> Also tried set op is still happen
> 
> Also, I tried Max_Read_Channels: 3->10 still happen
> I can join 3 channel at same time but I cant joining writing channel first
> 
> e.g.
> I set player permission is
> chatcontrol.channel.join
> chatcontrol.channel.join.global.write
> chatcontrol.channel.join.p.read
> chatcontrol.channel.join.$.read
> 
> when player join "p(read)" channel will leave a "global(write)" channel (debug/showtips not showing player leave the write channel)
> when player join "$(read)" channel will leave a "global(write)" channel (debug/showtips not showing player leave the write channel)
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey,
This is a pretty weird issue, I can't seem to reproduce it. Would you mind providing us your `/chc debug` file?

**Comment by waiching514** [comment]
https://ufile.io/euxn95hd
this is my test server file, not using mysql, but still having same problem

**Comment by ElBananaa** [comment]
Hey!
Thanks for sharing your debug file.
I could finally reproduce this issue with your version of the plugin this time.
Everytime you try to join a channel in read mode, it works fine, but the channel which is in write mode is automatically left apparently.

So, as example, let's say I join three channels in read mode : The  `standard` channel, the `admin` channel and the `global` channel, everything works fine, then I'll join a 4th channel (like `ranged`) in write mode, it still works fine. However, as soon as I'll join a 5th channel in read mode, I'll automatically leave my channel in write mode, even tho I have `Max_Read_Channels: 10` in my settings.

Unfortunately, there's not much we can do about it, you'll have to wait for Kangarko, which is on vacations until the 2nd of july, to get a fix for this issue

**Comment by kangarko** [comment]
I am here, will handle this in 1-3 days.

**Comment by kangarko** [comment]
Thanks, fixed, apologies for the delay.
