### ISSUE TITLE
1.16.5: Player not connected through BungeeCord despite joining through the proxy.

### ISSUE THREAD

**Issue by MasonX3** [kangarko/ChatControl#1086]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

When I try to join my "admin" channel, it gives me the message:

`[x] Player 'MasonX3' is not connected through BungeeCord.`

I joined through my Waterfall proxy, and it has worked fine until it just stopped working randomly. I have disabled joining the servers It continues to say this, even though I am able to send messages with the `/ch send admin test`.

This is happening on both of my servers with pretty well the same plugin list. 

No errors are logged in ChatControl or in the console from what I am able to see. 

Does this have to do with the BungeeChatAPI being weird or have I missed something?

Latest Log:
https://pastebin.com/QfL4Qnhv

Debug: 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6644381/debug.zip)

**Comment by ElBananaa** [comment]
Hey!
It's a pretty weird issue.
Try updating to the latest version of NashornPlus (1.1.0). https://bitbucket.org/kangarko/nashornplus/downloads/ (And don't forget to use NashornPlus v1.1.0 on the proxy as well if it runs under Java 15+)
If it doesn't work, for some people, reinstalling the plugin on all your servers and on the proxy fixed the issue, so give it a try (Also make sure your server softwares (Paper/waterfall) are both up-to-date.

**Comment by MasonX3** [comment]
Even with upgrading to the latest builds that are available for 1.16, the issue is still present unfortunately.

**Comment by ElBananaa** [comment]
This is a weird issue, and I have no ways to try to reproduce it, so my hand are currently tie. I think you'll have to wait for Kangarko which is on vacations until the 2nd of july, to get an answer regarding this issue. Someone might've experienced the same issue and fixed it tho, so there's a chance that another user could help you with this. I'll try to run a few tests and go throught our tickets to see if I can find anything else related to your issue a bit later today, but i don't guarantee anything ^^

**Comment by braceyourself07** [comment]
Just wanted to add my datapoint... vast majority of players on the network are just fine, but one player in particular gets this error when trying to change his nick:
Screenshot: https://brdv.coffee/storage/uploads/4/nUyqQlpooQ7P.png

**Comment by ElBananaa** [comment]
> Just wanted to add my datapoint... vast majority of players on the network are just fine, but one player in particular gets this error when trying to change his nick:
> Screenshot: https://brdv.coffee/storage/uploads/4/nUyqQlpooQ7P.png

Hey!
I believe the command to change your own nick is `/chc tag nick <newNick>`. Did he use this command?

@MasonX3 Sorry for the delay, I'm kinda busy lately, and I have no ways to try to reproduce your issue. However, can you confirm that it still happens, even under the latest version of the plugin?

**Comment by braceyourself07** [comment]
He had only used the /nick alias, but I will have him try the direct /chc tag nick command and see if that works. Thanks for the suggestion.

**Comment by braceyourself07** [comment]
When they use /chc tag nick they get a permission error for chatcontrol.command.tag.admin so that seems to be an admin command to change the tag directly

**Comment by ElBananaa** [comment]
> When they use /chc tag nick they get a permission error for chatcontrol.command.tag.admin so that seems to be an admin command to change the tag directly

Alright, and what happens if you try to change this player's nick using the command I gave you above? Do you have the same error?
If so, I'm kinda curious, your server runs in online mode or in offline mode? And did this player recently change his minecraft username on minecraft website?

**Comment by braceyourself07** [comment]
I can change it for them successfully.  Our servers run in offline mode in order to connect to BungeeCord (we use Waterfall) but the Bungee network is in online mode.  Yes, actually they did change their name on May 16.  Is there possibly something I should try purging in the ChatControl mysql database?

**Comment by braceyourself07** [comment]
Now that I had changed it myself, I had him try again.  It looks like the command works in the logs, but he gets no response and the nick remains the same. And if I clear the nick and he tries, it does not add the nick and still does not produce any error message now. 

[20:33:01] [Server thread/INFO]: [pm] mikedmd -> VeliNam: can you try changing your nick       
[20:33:08] [Server thread/INFO]: VeliNam issued server command: /nick veli
[20:33:08] [Server thread/INFO]: *--------- Rule match (command) for VeliNam ---------    
[20:33:08] [Server thread/INFO]: MATCH: ^\/nick (.*)
[20:33:08] [Server thread/INFO]: CATCH: /nick veli
[20:33:08] [Server thread/INFO]: Original message cancelled.             
[20:33:08] [Server thread/INFO]: [ChatControlRed 10.4.4] Command /tag nick veli took 9.21 ms

[20:35:37] [Server thread/INFO]: VeliNam issued server command: /nick VeliNam2
[20:35:37] [Server thread/INFO]: *--------- Rule match (command) for VeliNam ---------
[20:35:37] [Server thread/INFO]: MATCH: ^\/nick (.*)
[20:35:37] [Server thread/INFO]: CATCH: /nick VeliNam2
[20:35:37] [Server thread/INFO]: Original message cancelled.
[20:35:37] [Server thread/INFO]: [ChatControlRed 10.4.4] Command /tag nick VeliNam2 took 8.04 ms

**Comment by ElBananaa** [comment]
> Now that I had changed it myself, I had him try again. It looks like the command works in the logs, but he gets no response and the nick remains the same. And if I clear the nick and he tries, it does not add the nick and still does not produce any error message now.
> 
> [20:33:01] [Server thread/INFO]: [pm] mikedmd -> VeliNam: can you try changing your nick
> [20:33:08] [Server thread/INFO]: VeliNam issued server command: /nick veli
> [20:33:08] [Server thread/INFO]: _--------- Rule match (command) for VeliNam --------- [20:33:08] [Server thread/INFO]: MATCH: ^/nick (._)
> [20:33:08] [Server thread/INFO]: CATCH: /nick veli
> [20:33:08] [Server thread/INFO]: Original message cancelled.
> [20:33:08] [Server thread/INFO]: [ChatControlRed 10.4.4] Command /tag nick veli took 9.21 ms
> 
> [20:35:37] [Server thread/INFO]: VeliNam issued server command: /nick VeliNam2
> [20:35:37] [Server thread/INFO]: _--------- Rule match (command) for VeliNam --------- [20:35:37] [Server thread/INFO]: MATCH: ^/nick (._)
> [20:35:37] [Server thread/INFO]: CATCH: /nick VeliNam2
> [20:35:37] [Server thread/INFO]: Original message cancelled.
> [20:35:37] [Server thread/INFO]: [ChatControlRed 10.4.4] Command /tag nick VeliNam2 took 8.04 ms

I don't recommend editing the database for now. I'm not sure what the issue is, however we've had issues with minecraft name changes in the past. Idk if it's related but there's a chance it is. For now, if you think this can wait, I'd suggest waiting for Kangarko, which is currently on vacations until the 2nd of july, to take a deeper look at your issue.

**Comment by kangarko** [comment]
Hey! Please update to the latest ChatControl Red if you haven't already. In the mysql.yml file there's a flag UUID_Lookup you can try toggling on/off depending on what you have there already, that should solve the issue you're having behind a proxy. Seems like the user has changed his Mojang's username and now is facing this issue. @ElBananaa something to know ;)
