### ISSUE TITLE
1.16.5: Unhandled exception listening to AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by StarozytnySky** [kangarko/ChatControl#1087]
Error: https://pastebin.com/SStnELGd

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

**Comment by TheIntolerant** [comment]
Hey,
This issue is with your chat.rs file in /rules.
Do you mind uploading that file here and I can help fix it.

**Comment by StarozytnySky** [comment]
Chat.rs [https://pastebin.com/a4S7qPwB](url)

**Comment by ElBananaa** [comment]
Hi,
I believe your issue is caused by this part of your char rule file : 
```
match <3
then replace &4❤&f
```
Basically, you're usign a non utf8 character in the file resulting in an error.
Try with the following instead : 
```
match <3
then replace &4♥&f
```

**Comment by StarozytnySky** [comment]
I try everything and still i have error. I try delete this part and use other. Before it worked, maybe it appeared after the change  from java 11 to java 16... I have no way to check it now.

**Comment by ElBananaa** [comment]
> I try everything and still i have error. I try delete this part and use other. Before it worked, maybe it appeared after the change from java 11 to java 16... I have no way to check it now.

It might be an issue caused by java 16 yes. Wait for Kangarko to get back from vacation (2nd of july) to see what he can do to fix this ^^

**Comment by kangarko** [comment]
This is a Java 16 related issue that will be patched in the next version.
