### ISSUE TITLE
1.16.5: Issue with creating mysql table (specified key too long?)

### ISSUE THREAD

**Issue by Alexz1008** [kangarko/ChatControl#1088]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hey there,

I can't do /chc debug because the plugin isn't able to turn on since it gets stuck creating a mysql table. The question I have is simply how to get around this error: https://pastebin.com/c3NjHJb8

I googled the specified index too large issue and couldn't really figure out any way to fix it. So I instead just copied the sql statement and changed the UUID VARCHAR size from 255 to 80, and the table was created fine. Unfortunately, even if the table already exists, the sql exception will still happen. I don't see anyone else with this problem, so maybe I need to update sql? 

I tried following https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes but I'm not really fluent in sql enough to understand. Any help will be appreciated, as I need mysql to run because I intend to run this plugin on bungeecord.

Not sure if this is enough, but to prove that I've bought the plugin, this is my account on mc-market:
https://www.mc-market.org/members/239832/
In the "information" section, I set my homepage to link to my github account that I'm posting with here.

Thanks for any help you can give me!

**Comment by Alexz1008** [comment]
Uh, alright, so actually creating the table manually worked (I don't know why, but I restarted the server a few times and it worked even though I didn't change anything whatsoever??). I'm leaving this issue here so you can see it, you may want to lower the UUID Varchar, but I guess if I'm the only one who had this issue it may not be important. Feel free to close this once you see it!

**Comment by kangarko** [comment]
Thank you <3
