### ISSUE TITLE
1.16.5: Censoring match word for "asshole"

### ISSUE THREAD

**Issue by SecretarySami** [kangarko/ChatControl#1089]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hello , I just had a quick question regarding adding a more advanced filter for the word asshole. I was trying to filter the match word a$$hole and I'm struggling a bit to get it to censor it.

**Comment by TheIntolerant** [comment]
As the default rule is
```
# Blocks 'asshole'
match \b(a+(\W|\d|_)*s+(\W|\d|_)*s+(\W|\d|_)*h+(\W|\d|_)*o+(\W|\d|_)*l+(\W|\d|_)*e+(\W|\d|_)*)
group swear
```
Normally if I wanted to do this, I would just do ``(s|$)`` where the ``s`` is in this rule for the word. However, in RegEx ``$`` aka the dollar sign is the anchor for the end of the string. This would result in the rule not working correctly, therefore we should do ``(s|\$)`` so ChatControl does not treat the ``$`` as an anchor instead the regex rule treats the dollar sign as a literal character. As ``\`` converts metacharacters to literal characters.

So the rule above should look something like
```
# Blocks 'asshole'
match \b(a+(\W|\d|_)*(s|\$)+(\W|\d|_)*(s|\$)+(\W|\d|_)*h+(\W|\d|_)*o+(\W|\d|_)*l+(\W|\d|_)*e+(\W|\d|_)*)
group swear
```

Also a tip for testing rules, you can use this website: <https://regex101.com/>
Just make sure you enable the ``global, multi lines, insensitive, unicode`` flags, so on the right it looks like this:

![Capture](https://user-images.githubusercontent.com/48093184/122082378-4d4db100-ce43-11eb-87e2-25e7f0bdf3cd.JPG)

**Comment by SecretarySami** [comment]
Awesome thank you, I'll try this out!

**Comment by SecretarySami** [comment]
https://i.imgur.com/l3KGFp2.png
So after having that in my rules config and applying the changes players are now able to say both 'asshole' & 'a$$hole' 
Little confused aha

**Comment by TheIntolerant** [comment]
@SecretarySami re-read what I said :P
I just explained why it needs to be:
``(s|\$)``
And NOT this
``(s|$)``

To help you understand how RegEx works and hopefully troubleshoot the chatcontrol rules yourself. That is why I went into detail about it. Since you used ``$`` and not ``\$`` chatcontrol sees ``$`` as an anchor for the end of the string. In other words think of ``$`` as ``THE END`` That is why you need to use ``\`` before the dollar sign so ChatControl converts the metacharacters to literal characters, instead of it thinking, this is the end of the string.

As the whole string should be "asshole" etc not, "a". Since you put the dollar sign without ``\`` in front it thinks you are indicating the end of the string and thus the plugin doesn't understand what you are trying to do, that is why people can now say both "asshole" and "a$$hole" instead of it blocking both words.

**Comment by SecretarySami** [comment]
> @SecretarySami re-read what I said :P
> I just explained why it needs to be:
> `(s|\$)`
> And NOT this
> `(s|$)`
> 
> To help you understand how RegEx works and hopefully troubleshoot the chatcontrol rules yourself. That is why I went into detail about it. Since you used `$` and not `\$` chatcontrol sees `$` as an anchor for the end of the string. In other words think of `$` as `THE END` That is why you need to use `\` before the dollar sign so ChatControl converts the metacharacters to literal characters, instead of it thinking, this is the end of the string.
> 
> As the whole string should be "asshole" etc not, "a". Since you put the dollar sign without `\` in front it thinks you are indicating the end of the string and thus the plugin doesn't understand what you are trying to do, that is why people can now say both "asshole" and "a$$hole" instead of it blocking both words.

.... my paste didnt work LOL

**Comment by SecretarySami** [comment]
thank you!, sorry for wasting your time. I really appreciate it :)

**Comment by TheIntolerant** [comment]
Hopefully I haven't overloaded you with too much information as learning how to effectively use RegEx took me a while but now I am pretty confident with it. So I thought I would explain why the backslash is used with the dollar sign and the issue with solely using the dollar sign, as that symbol is used to indicate the end of a string.

**Comment by SecretarySami** [comment]
I'm really new to all of this , like even looking at configs so its taking me a bit to learn even the simplest things. Though I really appreciate the amazing response :)
This can be closed whenever !

**Comment by kangarko** [comment]
Thanks @gone-incognito for all the help <3
