### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by BlackBeltPanda** [kangarko/ChatControl#109]
ChatControl version: v5.0.8
Spigot version: 1.8.1 & 1.8.3

I get the following error every couple of minutes:
http://pastebin.com/raw.php?i=pU9kAeiH

**Comment by lizardfreak321** [comment]
This is the error I get http://pastebin.com/GxT3Ybqs

Spigot 1.8.3.
It only happens when I enable chat formatter. Note: It happens with the default message format too.

**Comment by BlackBeltPanda** [comment]
lizardfreak321, your error is different; you should start a new ticket.

**Comment by lizardfreak321** [comment]
Done

**Comment by kangarko** [comment]
Please test against 5.0.9

**Comment by kangarko** [comment]
I think I've fixed it, if it occurs again please let me know.
