### ISSUE TITLE
Ignoring gamemode isn't working

### ISSUE THREAD

**Issue by MikroAcse** [kangarko/ChatControl#109]
This rule:
```
match ^//exp
ignore gamemode survival
then warn &bYou cannot use this in creative mode!
then deny
```
Doesn't work for me. Always blocking the action.

**Comment by kangarko** [comment]
Apparently the check is missing in the free version.
Thanks for noticing! A new version will be released tonight.

**Comment by MikroAcse** [comment]
Thank you very much! I've suggested this feature before premium version released, so I'm little confused. But I'm happy that you fixed it.

**Comment by kangarko** [comment]
The code is already in premium. Must've implemented it sometime when doing code inspection, but forget to merge it downstream.

**Comment by MikroAcse** [comment]
Thank you again! C:
