### ISSUE TITLE
People getting disconnected from channels

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl#109]
<img width="708" alt="Screenshot_2020-11-19_at_10 26 08" src="https://user-images.githubusercontent.com/1918426/99647680-67ace100-2a52-11eb-9ad0-488e754c9f42.png">

**Comment by kangarko** [comment]
Also 
<img width="714" alt="Screenshot 2020-11-19 at 10 32 09" src="https://user-images.githubusercontent.com/1918426/99647748-7e533800-2a52-11eb-9e8d-b30f6a7cf767.png">

**Comment by kangarko** [comment]
@DoogiePC alright so regarding channels being disconnected, ensure players have chatcontrol.channel.join.{channel}.{mode} for the proper channel and the proper mode, or both write/read. 

Next version will add debug messages for private messages starting with "@", if that happens again, please do not open a new ticket, just comment below and I see it :)

**Comment by broken1arrow** [comment]
I don´t know if start new tread. But players some not have read perms on a channel get read even if they left the channel. 
I get disconnected from channels one time (has not see it after, it was in the first versions).

I´m he use bungee cord (can be some compatible issues)? But i can see if I get same issue.

**Comment by kangarko** [comment]
Thanks, I identified and solved the problem of channels no properly leaving when players lacked read permission
