### ISSUE TITLE
BungeeControl-Red message group

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1091]
Can supporting toggle message from BungeeControl-Red message?

If I setup this on bungeecord
![image](https://user-images.githubusercontent.com/29138111/122165017-2c6c7680-ceaa-11eb-80dc-ecdddcfb25e1.png)
I cant /chc message toggle join default and /toggle join default

**Comment by kangarko** [comment]
No sorry we can't control bungee-related stuff in the messages part from a bukkit/spigot server
