### ISSUE TITLE
1.16.5: Java 16 issue (yes, nashorn installed)

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1093]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true
Java: 16

I have this error when I want to use my emotes, like :heart: 

Error: https://pastebin.com/sQkxVNRf

Debug zip: https://ufile.io/065z34jl

**Comment by Squeej** [comment]
Yeah I came here to report the same issue with Java 16/Nahorn. Pretty much any chat rule is ignored allowing swears to bypass, and emotes will break the chat format for that message. Most chat channels are broken/inaccessible, giving the "Oups!" error message when trying to join them. 

![sc test](https://user-images.githubusercontent.com/71758114/122328504-a7528300-cee4-11eb-9fe2-d803e07ff4b3.jpg)

**Comment by kangarko** [comment]
Thanks, will be patched.
