### ISSUE TITLE
Cannot complete "tour"

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl#1094]
Minecraft Version: 1.16.5 (Paper-775)
MySQL: false
BungeeCord: false
CHC: 10.4.7

Did this WITHOUT the migrate: migrating settings manually.  Upon server start I cannot chat it says something like "you must complete tour with /chc tour start" so I do that, go through all the pages and the last one says to "/chc tour confirm" which I do... and it says to read terms of service and the command will be given in this - except it isn't.  The only mention of an unlock is the "network unlock" section, but this doesn't include a command, only tells you what to do if you have already run that command, which isn't possible to do since it isn't documented anywhere, so CHC is locked forever, no channels can be joined, no chat can even be attempted.  Please advise.

**Comment by vitya0717** [comment]
I interested, how did you do, I don't know either..

**Comment by mrcoffee1026** [comment]
It IS in the terms in conditions, it just doesn't mention "command" or anything you might normally search for.  It's about half way through the page shows something like "type /chc tour ... in game" which is what you're looking for.
