### ISSUE TITLE
1.16.5: Change announcement prefix

### ISSUE THREAD

**Issue by JustDriessen** [kangarko/ChatControl#1098]
Dear Chat Control,

I was wondering if I am able to change the overall look and prefix of the /chat announce command.
It now shows the default ! Announcement ! prefix and I was wondering if I could change the overall look of the default message atm.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

**Comment by JustDriessen** [comment]
I was looking for the Announcement prefix, wasn't there but I did see a lot of placeholders, probably with a hard coded message behind the code.

**Comment by ElBananaa** [comment]
> I was looking for the Announcement prefix, wasn't there but I did see a lot of placeholders, probably with a hard coded message behind the code.

Hey!
The prefixes can be found in your localization file, under the `Prefix:` part.
