### ISSUE TITLE
1.16.5: How to send message on chat channel via API

### ISSUE THREAD

**Issue by addstar** [kangarko/ChatControl#1100]
We're are migrating our bungee network to ChatControl-Red and we have several plugins (server+bungee) that need to send messages to chat channels (eg. to broadcast messages). Currently testing with the latest versions (ChatControl 10.4.8 + BungeeControl 3.4.8).

I've already got ChatControl imported into our projects so accessing the plugin instance is not a problem, but the [API page](https://github.com/kangarko/ChatControl-Red/wiki/API) is fairly vague and doesn't give any info about **_sending_** chat messages. I can see plenty of useful events in the API but can you outline the classes/methods I should use to have my own plugins send messages on chat channels? Both on bungee side and server side.

On the server side, I tried sending some plugin messages (via `plugin:chcred`) but had no luck with that. Not even sure if we should use plugin messages or access the interface directly with the plugin instance.

Thanks.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true/

**Comment by kangarko** [comment]
Hey!

Sorry for the confusion. I added some handy methods into ChatControlAPI class in the next version for your convenience:

<img width="1238" alt="Screenshot 2021-06-19 at 15 16 12" src="https://user-images.githubusercontent.com/1918426/122643653-4d82d080-d111-11eb-8d13-2c76748ae9f7.png">

Closing, but let me know below in case you need anything else!

**Comment by addstar** [comment]
This is great, I now see how I to send messages now (before next release) - thanks for the fast response @kangarko !

Could you also tell me how I would do this in Bungee plugins? There doesn't seem to be the same classes.

**Comment by kangarko** [comment]
What do you mean? This is not supported on BungeeControl Red, because we send channel message to BungeeCord from Spigot upstream.

**Comment by addstar** [comment]
Oh sorry, I don't think I was clear.

We have a bungee plugin we maintain that uses our current/old chat system to send a message on a chat channel. Since we are migrating to ChatControl, I'm wondering if this is possible to do with BungeeControl? Or could we just send a plugin message to ChatControl to do this, even if it's not officially supported? What would be the best way to initiate a chat channel message _from_ bungee (not from a server plugin)?Thanks.

**Comment by kangarko** [comment]
Hey! Apologies for the delay, to send a message to a chat channel from bungee, you'd have to write a bungee-only plugin that'll send a plugin message packet to bukkit, where you'd have a bukkit-only plugin invoking the ChatControlAPI#sendMessage call in our plugin on bukkit. Adding API calls to BungeeControl Red directly is problematic because we use a large amount of proprietary components: https://i.imgur.com/qPkctfe.png

**Comment by addstar** [comment]
All good, I was aware you were on vacation so I didn't expect it straight away :slightly_smiling_face: Thanks for your reply.

I figured I might have to do that, that's no problem. Easy enough to do, thanks! :+1:
