### ISSUE TITLE
1.16.5: unable to filter the word $hit

### ISSUE THREAD

**Issue by SecretarySami** [kangarko/ChatControl#1105]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

So i'm attempting to filter the word $hit using this 
https://i.imgur.com/sURcrpM.png
But it's still allowing it to go through, i'm not entirely sure where the issue is O.o

Also have a couple other questions as well if you have time :) not sure if i should open another github post of if its okay to ask in the same one

**Comment by TheIntolerant** [comment]
Just to explain the issue, basically ``\b`` acts as a word boundary. So making a rule like
 ``\b(s+(\W|\d|_)*h+(\W|\d|_)*i+(\W|\d|_)*t+(\W|\d|_)*)\b``
would match ``shit`` but not ``shithead`` but if I remove the ``\b`` at the end, it would match both ``shit`` and ``shithead`` but not ``bigshit`` because of the ``\b`` at the start.

Now you understand that ``\b`` acts as a word boundary, it must be noted that ``\B`` acts as a non-word boundary.
This is important to understand as ``$`` is considered a non-word character, therefore ``\b`` will not work in this rule as it currently stands.

So to get ``$hit`` and ``shit`` to be blocked in the same rule, you need to make the rule only apply ``\b`` for the ``s`` and ``\B`` only apply to the ``$``. You can do this make making the rule like this:
```
match ((\bs|\B\$)+(\W|\d|_)*h+(\W|\d|_)*i+(\W|\d|_)*t+(\W|\d|_)*)
```

**Comment by TheIntolerant** [comment]
and feel free to ask any other questions you have.

**Comment by SecretarySami** [comment]
> and feel free to ask any other questions you have.

Awesome I'll try that out soon, but my other question is for censoring numbers what exactly is the format O.o I assumed it would be like the following - (i|\1) but that doesn't seem to work. 

I was also struggling with getting more than two instances of words/spelling to filter 
For example 
Shit
Sh!t
And sh1t
I would like to have all three i 1 and ! To be filtered for the word however I don't know how to do more than one eep

And I apologize for being a little oblivious when it comes to this stuff aha , don't mean to waste your time or be a bother at all, truly just trying to learn :)
And I really do appreciate the well detailed support you're giving.

**Comment by TheIntolerant** [comment]
```
match ((\bs|\B\$)+(\W|\d|_)*h+(\W|\d|_)*(i|1|\!)+(\W|\d|_)*t+(\W|\d|_)*)
```
should work as shown below when testing with https://regex101.com/
![Capture](https://user-images.githubusercontent.com/48093184/122670358-0bd35200-d205-11eb-8c7b-984df0aaa423.JPG)

**Comment by TheIntolerant** [comment]
``\1`` will return a string with the contents from the first capture group. This is why I used ``(i|1|\!)`` and not ``(i|\1|\!)``

**Comment by TheIntolerant** [comment]
RegEx can be a pain to learn but if you go to https://regex101.com/
and put in a regex rule like shown above, and it explains what is happening as well as providing a reference explaining what ``\b`` etc does and what each component means when you hover over the part of the RegEx (Regular expression) as shown in the next screenshot 
![Capture](https://user-images.githubusercontent.com/48093184/122670633-5f926b00-d206-11eb-9718-a72a50358559.PNG)

**Comment by TheIntolerant** [comment]
Also note: on the right of that RegEx in the screenshot, it says ``/gmiu`` it is important you make sure all those flags are selected
```
global
multi line
insensitive
unicode
```

**Comment by SecretarySami** [comment]
> RegEx can be a pain to learn but if you go to https://regex101.com/
> and put in a regex rule like shown above, and it explains what is happening as well as providing a reference explaining what `\b` etc does and what each component means when you hover over the part of the RegEx (Regular expression) as shown in the next screenshot
> ![Capture](https://user-images.githubusercontent.com/48093184/122670633-5f926b00-d206-11eb-9718-a72a50358559.PNG)

so now i have this one 
#Blocks 'douche'
match \b(d+(\W|\d|_)*(o|0)+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*h+(\W|\d|_)*(e|3)+(\W|\d|_)*)
group swear
That will not filter and my first thought was okay, maybe i needed to change the /b 
but that didn't work and now i'm a little confused again xD 

really sorry for all the questions ahhh

**Comment by ElBananaa** [comment]
> > RegEx can be a pain to learn but if you go to https://regex101.com/
> > and put in a regex rule like shown above, and it explains what is happening as well as providing a reference explaining what `\b` etc does and what each component means when you hover over the part of the RegEx (Regular expression) as shown in the next screenshot
> > ![Capture](https://user-images.githubusercontent.com/48093184/122670633-5f926b00-d206-11eb-9718-a72a50358559.PNG)
> 
> so now i have this one
> #Blocks 'douche'
> match \b(d+(\W|\d|_)*(o|0)+(\W|\d|_)_u+(\W|\d|_)*c+(\W|\d|_)_h+(\W|\d|_)_(e|3)+(\W|\d|_)_)
> group swear
> That will not filter and my first thought was okay, maybe i needed to change the /b
> but that didn't work and now i'm a little confused again xD
> 
> really sorry for all the questions ahhh

Hey,
You must've done a mistake in your regex. I'm not really good with regex, but give this one a shot : `\b(d+(\W|\d|)*(o|0)+(\W|\d|)u+(\W|\d|)c+(\W|\d|)h+(\W|\d|)+(e|3)+(\W|\d|_))`

**Comment by SecretarySami** [comment]
> > > RegEx can be a pain to learn but if you go to https://regex101.com/
> > > and put in a regex rule like shown above, and it explains what is happening as well as providing a reference explaining what `\b` etc does and what each component means when you hover over the part of the RegEx (Regular expression) as shown in the next screenshot
> > > ![Capture](https://user-images.githubusercontent.com/48093184/122670633-5f926b00-d206-11eb-9718-a72a50358559.PNG)
> > 
> > 
> > so now i have this one
> > #Blocks 'douche'
> > match \b(d+(\W|\d|_)*(o|0)+(\W|\d|_)_u+(\W|\d|_)*c+(\W|\d|_)_h+(\W|\d|_)_(e|3)+(\W|\d|_)_)
> > group swear
> > That will not filter and my first thought was okay, maybe i needed to change the /b
> > but that didn't work and now i'm a little confused again xD
> > really sorry for all the questions ahhh
> 
> Hey,
> You must've done a mistake in your regex. I'm not really good with regex, but give this one a shot : `\b(d+(\W|\d|)*(o|0)+(\W|\d|)u+(\W|\d|)c+(\W|\d|)h+(\W|\d|)+(e|3)+(\W|\d|_))`

didn't work O.o ahhh

**Comment by SecretarySami** [comment]
#Blocks 'douche'
match \b(d+(\W|\d|_)*(o|0)+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*h+(\W|\d|_)*(e|3)+(\W|\d|_)*)
group swear

This one worked, but i'm having a few issues with this 

https://i.imgur.com/pElrqTF.png
Everytime i uncomment out "homo" it causes issues with "tiddies"

Like the match is incorrect

**Comment by SecretarySami** [comment]
so , was attempting to filter out homosexual and it's only filtering out the first part of the word O.o
https://i.imgur.com/nE8LU7f.png

**Comment by ElBananaa** [comment]
> so , was attempting to filter out homosexual and it's only filtering out the first part of the word O.o
> https://i.imgur.com/nE8LU7f.png

I'm not sure to understand why would you filter homosexual, but that's up to you ^^
Anyways, could you please provide us the regex used?

**Comment by SecretarySami** [comment]
> > so , was attempting to filter out homosexual and it's only filtering out the first part of the word O.o
> > https://i.imgur.com/nE8LU7f.png
> 
> I'm not sure to understand why would you filter homosexual, but that's up to you ^^
> Anyways, could you please provide us the regex used?

```
# Blocks 'homosexual'
match ((\bh|\B\#)(\W|\d|_)*(o|0)+(\W|\d|_)*m+(\W|\d|_)*(o|0)+(\W|\d|_)*(s|\$)+(\W|\d|_)*(e|3)+(\W|\d|_)*x+(\W|\d|_)*u+(\W|\d|_)*(a|\@)+(\W|\d|_)*l+(\W|\d|_)*)
group swear
```

yep my bad !

**Comment by SecretarySami** [comment]
there is a \ in front of the # it's just not showing on the post aha

**Comment by ElBananaa** [comment]
> > > so , was attempting to filter out homosexual and it's only filtering out the first part of the word O.o
> > > https://i.imgur.com/nE8LU7f.png
> > 
> > 
> > I'm not sure to understand why would you filter homosexual, but that's up to you ^^
> > Anyways, could you please provide us the regex used?
> 
> ```
> # Blocks 'homosexual'
> match ((\bh|\B\#)(\W|\d|_)*(o|0)+(\W|\d|_)*m+(\W|\d|_)*(o|0)+(\W|\d|_)*(s|\$)+(\W|\d|_)*(e|3)+(\W|\d|_)*x+(\W|\d|_)*u+(\W|\d|_)*(a|\@)+(\W|\d|_)*l+(\W|\d|_)*)
> group swear
> ```
> 
> yep my bad !

It seems to be working perfectly fine on my side
![image](https://user-images.githubusercontent.com/53318613/122688191-1e588600-d21b-11eb-9c00-3af6787a8245.png)

**Comment by SecretarySami** [comment]
> > > > so , was attempting to filter out homosexual and it's only filtering out the first part of the word O.o
> > > > https://i.imgur.com/nE8LU7f.png
> > > 
> > > 
> > > I'm not sure to understand why would you filter homosexual, but that's up to you ^^
> > > Anyways, could you please provide us the regex used?
> > 
> > 
> > ```
> > # Blocks 'homosexual'
> > match ((\bh|\B\#)(\W|\d|_)*(o|0)+(\W|\d|_)*m+(\W|\d|_)*(o|0)+(\W|\d|_)*(s|\$)+(\W|\d|_)*(e|3)+(\W|\d|_)*x+(\W|\d|_)*u+(\W|\d|_)*(a|\@)+(\W|\d|_)*l+(\W|\d|_)*)
> > group swear
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > yep my bad !
> 
> It seems to be working perfectly fine on my side
> ![image](https://user-images.githubusercontent.com/53318613/122688191-1e588600-d21b-11eb-9c00-3af6787a8245.png)

don't get it aha https://i.imgur.com/Q41G9yP.png
doesn't want to filter sexual for me

**Comment by SecretarySami** [comment]
based off console it looks like homo is catching it before it can fully filter O.o https://i.imgur.com/ECNUlnI.png


after commenting out homo and just having homosexual it filters the whole word but now homo is able to be said ahhhh

**Comment by TheIntolerant** [comment]
The chat filter works from top to button and that is how each rule is processed so if you wish to make a rule processed before another rule, make sure that specific rule is above the other one.

**Comment by SecretarySami** [comment]
> The chat filter works from top to button and that is how each rule is processed so if you wish to make a rule processed before another rule, make sure that specific rule is above the other one.

oh my god thank you xD

**Comment by SecretarySami** [comment]
that's everything ! I really really appreciate all the amazing support you all have given me while I attempt to learn this aha 

I hope you all have an amazing day!
