### ISSUE TITLE
Global chat alias command spam on console

### ISSUE THREAD

**Issue by C0ffeL0Ve** [kangarko/ChatControl#1106]
My issue is that the console is spaming double messages when the user type the alias command for global chat and this is troubling me to monitor the players.

This is the script that i copied from gone-incognition response from a similar issue:
```
# Catch "/g" command and send usage.
match ^\/g$
dont verbose
then warn &cDescrição: Envie uma mensagem para o chat global.
then warn &cUso: /g <mensagem>
then deny
```
The outcome is this:
```
[21:49:59 INFO]: Allaskaa issued server command: /g tem comando pra ver vantagem ou valor aqui ?
[21:49:59 INFO]: [global] Allaskaa: Tem comando pra ver vantagem ou valor aqui ?
```
every user type on global to chat globally so imagine double messages like this from 20 users at a time.

I also tried inserting a script on the command.yml to do the same thing as /g and the outcome is double messages+ bug from the rules when a user type something as spam.

is there a way to hide the double command from the console?

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false
chatcontrolred: 10.4.9

**Comment by ElBananaa** [comment]
Hey!
I believe you can use the `Console_Filter` option in the plugin settings file, so it would look like this: (Don't use this feature if you use MultiCraft.
```yaml
  Messages:
  - 'issued server command: /g'
```

An other way would be to use a prefix like `!` instead of a command, to send a global message.
There's a premade rule that should work in your `/rules/chat.rs` file, it looks like that : 
```
# Send messages starting with "!" to global channel
#match ^(\!)(.*)
#then command channel send global $2
#then deny
#dont verbose
```
Simply remove the comments and adapt the rule to your channel name, and it should work.
```
# Send messages starting with "!" to global channel
match ^(\!)(.*)
then command channel send global $2
then deny
dont verbose

**Comment by C0ffeL0Ve** [comment]
> Hey!
> I believe you can use the `Console_Filter` option in the plugin settings file, so it would look like this: (Don't use this feature if you use MultiCraft.
> 
> ```yaml
>   Messages:
>   - 'issued server command: /g'
> ```
> 
> An other way would be to use a prefix like `!` instead of a command, to send a global message.
> There's a premade rule that should work in your `/rules/chat.rs` file, it looks like that :
> 
> ```
> # Send messages starting with "!" to global channel
> #match ^(\!)(.*)
> #then command channel send global $2
> #then deny
> #dont verbose
> ```
> 
> Simply remove the comments and adapt the rule to your channel name, and it should work.
> 
> ```
> # Send messages starting with "!" to global channel
> match ^(\!)(.*)
> then command channel send global $2
> then deny
> dont verbose
> ```

I was actually planning on using only ! at first, but the users from my country are used to type /g instead of ! and when i enable the ! the message that is sent dont look as good as the message from /g
example
!hello blabla
[Global][rank] CoffeL0V:hello blabla

as if
/g hello blabla
[Global][rank] CoffeL0V: hello blabla

players tend to put a space after ! and not put a space after the ! so that bothers me a little

thank you its fixed, if i have looked more thoroughly i would be able to fix myself, sorry for that
