### ISSUE TITLE
Chatcontrolred network bug

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1107]
When I only change Chatcontrolpro to ChatcontrolRed (I tested any thing no wrong on my test server)
Server reach 170 - 180 online will got kicked by [proxy] Lost connection to server.
![image](https://user-images.githubusercontent.com/29138111/122858378-c6ba3780-d34c-11eb-8d91-6aacb1100fe4.png)
I had tested 1 day only change ChatcontrolRed to Chatcontrolpro to cause the problem

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> When I only change Chatcontrolpro to ChatcontrolRed (I tested any thing no wrong on my test server)
> Server reach 170 - 180 online will got kicked by [proxy] Lost connection to server.
> ![image](https://user-images.githubusercontent.com/29138111/122858378-c6ba3780-d34c-11eb-8d91-6aacb1100fe4.png)
> I had tested 1 day only change ChatcontrolRed to Chatcontrolpro to cause the problem
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
I believe your issue is related to #964. As for now, I recommend using ChatControlPro until the 2nd of july since Kangarko is on vacations until then.

**Comment by kangarko** [comment]
Let's continue on the other ticket as Banana has mentioned, will be having a look this week.
