### ISSUE TITLE
Network Discord

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1108]
When server running multi server Discord, player send message on Discord to game, If 8 server installed Discord, Chatcontrol will log 8 times, also the rules will runs 8 times on discord

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> When server running multi server Discord, player send message on Discord to game, If 8 server installed Discord, Chatcontrol will log 8 times, also the rules will runs 8 times on discord
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
Sorry for the delay, I completely lost the track of your issue.
I don't know if the plugin is intended to work with multiple discord guilds for a single game server, this might be the reason of your issue. However, I'll leave this open so Kangarko could give you a final answer in a few days! :)

**Comment by kangarko** [comment]
ChatControl is not intended to be used with multiple discords, you need to disable our discord hook and use another plugin such as DiscordSRV for that
