### ISSUE TITLE
[6.9.0]Colored chat global messages not working

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl#111]
i noticed if a user is not in the same server where i send the colored global message it dont see colours:
Prof: http://i.imgur.com/8MdMnQv.png

**Comment by EvilOlaf** [comment]
6.9.0 probably means you are using the premium version. So please state your issue report in the proper repository which is available here: https://github.com/kangarko/ChatControl-Pro/issues/

**Comment by xion87** [comment]
ops you are right! >.<
