### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by lizardfreak321** [kangarko/ChatControl#111]
This is the error I get http://pastebin.com/GxT3Ybqs
It is similar to BlackBeltPanda's.

Spigot 1.8.3.
It only happens when I enable chat formatter. Note: It happens with the default message format too.

**Comment by kangarko** [comment]
Please test against 5.0.9

**Comment by lizardfreak321** [comment]
No more errors!

**Comment by kangarko** [comment]
Hurray! :)
