### ISSUE TITLE
#101 Gradient question

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#111]
In #101 i asked about {#03c4ff>}Text{#03ffd1<} gradient format and the answer was that it is supported, but i do not see how.
![image](https://user-images.githubusercontent.com/62369973/99650931-10653b80-2a67-11eb-9fec-2187c5d3b79c.png)
![image](https://user-images.githubusercontent.com/62369973/99651525-c466c680-2a67-11eb-91d1-0a30d88fbd9a.png)

Secondly, i can't understand how to use gradient at all XD here is an example: 
![image](https://user-images.githubusercontent.com/62369973/99651399-9a150900-2a67-11eb-9db9-fa759e274447.png)
![image](https://user-images.githubusercontent.com/62369973/99651431-a305da80-2a67-11eb-87e8-4b940626fe27.png)

**Comment by OfT3N** [comment]
UPD: "Secondly" part is no longer actual

**Comment by kangarko** [comment]
Thanks, in the next version you simply create gradients like this:

```
Parts:
  Player:
    Message: '{player_name}: '
    Gradient: '#03c4ff - #03ffb3'
```

Make sure the Message key has no & colors nor the {message} variable otherwise it won't work.
