### ISSUE TITLE
Information about ChatControl RED

### ISSUE THREAD

**Issue by LordYarkan** [kangarko/ChatControl#1111]
My nickname in spigot: LordYarkan

Hello, I sent an email but they did not answer. I bought the ChatcontrolPRO 8 and they did not update more, I saw in the description that those who bought the chatcontrolPro can have the privilege of downloading ChatControl RED

Minecraft Version: 1.16.5 Papermc
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey,
I'm sorry, Kangarko must've forgot to answer you.
ChatControlRed is a completely new plugin which was rewritten from scratch. For this reason, the free upgrade is only available for those who bought ChatControlPro on November 15th 2020, or later. If you bought the plugin at this date or later, go to this page (https://mineacademy.org/chatcontrol-red/), scroll a bit, and you'll find a part named : `Upgrade From ChatControl Pro`
If you bought the plugin before this date, this won't apply to you. However, if you wish to, I could leave this issue open, so Kangarko could take a look at it when he gets back from vacation (beginning of july), and you can see this directly with him. :)

**Comment by LordYarkan** [comment]
No, I bought it on February 20 :(

**Comment by kangarko** [comment]
Send me your MCMarket username to matej@mineacademy.org and I'll see what I can do :)
