### ISSUE TITLE
1.17 Error loading chatcontrol red

### ISSUE THREAD

**Issue by mcer10081** [kangarko/ChatControl#1112]
Chatcontrol Red disables on server startup
logs: https://pastebin.com/5xAKizwz

NashornPlus 1.1.0
Vault 1.7.3
Minecraft Version: 1.17
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Chatcontrol Red disables on server startup
> logs: https://pastebin.com/5xAKizwz
> 
> NashornPlus 1.1.0
> Vault 1.7.3
> Minecraft Version: 1.17
> MySQL: true
> BungeeCord: true

Hey!
Please update your ProtocolLib to the latest dev build (https://ci.dmulloy2.net/job/ProtocolLib/522/) and it should fix your issue

**Comment by mcer10081** [comment]
> > Chatcontrol Red disables on server startup
> > logs: https://pastebin.com/5xAKizwz
> > NashornPlus 1.1.0
> > Vault 1.7.3
> > Minecraft Version: 1.17
> > MySQL: true
> > BungeeCord: true
> 
> Hey!
> Please update your ProtocolLib to the latest dev build (https://ci.dmulloy2.net/job/ProtocolLib/522/) and it should fix your issue

Okay, I tried this, it loads now but it's spamming console with an error. Other than that it seems to be working fine now
Here is the error: https://pastebin.com/CzmaESKJ

**Comment by ElBananaa** [comment]
> > > Chatcontrol Red disables on server startup
> > > logs: https://pastebin.com/5xAKizwz
> > > NashornPlus 1.1.0
> > > Vault 1.7.3
> > > Minecraft Version: 1.17
> > > MySQL: true
> > > BungeeCord: true
> > 
> > 
> > Hey!
> > Please update your ProtocolLib to the latest dev build (https://ci.dmulloy2.net/job/ProtocolLib/522/) and it should fix your issue
> 
> Okay, I tried this, it loads now but it's spamming console with an error. Other than that it seems to be working fine now
> Here is the error: https://pastebin.com/CzmaESKJ

It looks like there's either something missing/corrupted in your database, or you didn't update the plugin everywhere (proxy & servers). So make sure you use the latest version of BungeeControlRed with NashornPlus v1.1.0 (latest) on the proxy, and same thing with Chc-red/nashornplus/protocolLib on all your servers)

**Comment by kangarko** [comment]
Can you please try updating to the latest ChatControl Red and BungeeControl Red on the whole network? Do not reload any of the servers, you need to stop your network when updating.

**Comment by mcer10081** [comment]
Updating ChatControl Red and BungeeControl Red everywhere worked, thanks.

**Comment by kangarko** [comment]
Thanks!
