### ISSUE TITLE
Way to change hex format

### ISSUE THREAD

**Issue by UserDerezzed** [kangarko/ChatControl#1113]
Hey there.

Not sure why this has been closed in the past (#559) but this is a serious need.

Because ChatControl uses only the # symbol before Hex colors, this means that for many plugins that use the &# format, they don't format the color and instead show the hex code. So you have to decide between having a random & in your prefix or having no color and displaying a hex code for everything else. We should really have the option to customize the hex code format so that it works for every plugin. This is a huge problem for my server at the moment because every rank in the chat has a random & in the prefix.

**Comment by ElBananaa** [comment]
> Hey there.
> 
> Not sure why this has been closed in the past (#559) but this is a serious need.
> 
> Because ChatControl uses only the # symbol before Hex colors, this means that for many plugins that use the &# format, they don't format the color and instead show the hex code. So you have to decide between having a random & in your prefix or having no color and displaying a hex code for everything else. We should really have the option to customize the hex code format so that it works for every plugin. This is a huge problem for my server at the moment because every rank in the chat has a random & in the prefix.

Hey! The plugin also uses the `{#rrggbb}` format. Dit you try it?

**Comment by UserDerezzed** [comment]
Yes, however every other plugin besides ChatControl faces the same issue. It displays the Hex code instead of using it as a color. The majority of plugins use the &#rrggbb format.
<img width="399" alt="Screen Shot 2021-06-25 at 11 28 09 AM" src="https://user-images.githubusercontent.com/25561419/123469834-6f180800-d5a8-11eb-905a-0d03dfc23fb1.png">
For example, Essentials incompatibility.

<img width="244" alt="Screen Shot 2021-06-25 at 11 29 18 AM" src="https://user-images.githubusercontent.com/25561419/123469963-9a9af280-d5a8-11eb-88e2-53f217e6a1d9.png">
And if I want everything else to work properly, there is an extra & in the prefix.

**Comment by ElBananaa** [comment]
> Yes, however every other plugin besides ChatControl faces the same issue. It displays the Hex code instead of using it as a color. The majority of plugins use the &#rrggbb format.
> <img alt="Screen Shot 2021-06-25 at 11 28 09 AM" width="399" src="https://user-images.githubusercontent.com/25561419/123469834-6f180800-d5a8-11eb-905a-0d03dfc23fb1.png">
> For example, Essentials incompatibility.
> 
> <img alt="Screen Shot 2021-06-25 at 11 29 18 AM" width="244" src="https://user-images.githubusercontent.com/25561419/123469963-9a9af280-d5a8-11eb-88e2-53f217e6a1d9.png">
> 
> And if I want everything else to work properly, there is an extra & in the prefix.

Hey!
Sorry for the delay, I completely lost the track of your suggestion.
I already asked Kangarko multiple times about adding more hex formats to the plugin, and he told me that this would be a performance hit. However, I never thought about suggesting to simply allow us to customize the format. However, the issue would be the same here : Some plugins don't support the `&#rrggbb` format, so, imo, the best thing to do would be to keep a format which can't be edited (Either `#rrggbb` or `{#rrggbb}`) and letting us edit the other format.

(I also noticed in the settings file the comments only talk about the `#rrggbb` format at the top of the file in the comment : `To use HEX colors, use #123456 syntax: "Hello #123456world."` but don't say anything about the other format. Same thing ingame when using `/chc color`. Idk if this is intended, but it would be nice to update the comments I guess)

**Comment by kangarko** [comment]
Thanks, I will look into removing the trailing & when `#XXXXXX` format is being used.

**Comment by kangarko** [comment]
Fixed.
