### ISSUE TITLE
1.8.8 & 1.17 - Issue with the log file structure

### ISSUE THREAD

**Issue by AlfreDGR** [kangarko/ChatControl#1116]
[error.log](https://github.com/kangarko/ChatControl-Red/files/6717616/error.log)

Minecraft Version: 1.8.8
MySQL: false
BungeeCord: false

**Comment by TheIntolerant** [comment]
Hey,
Could you please upload your death.rs file, in the messages folder, here?
Thanks

**Comment by ElBananaa** [comment]
> [error.log](https://github.com/kangarko/ChatControl-Red/files/6717616/error.log)
> Minecraft Version: 1.8.8
> MySQL: false
> BungeeCord: false

Hey, you're using a way too old version of the plugin. Please update to the latest version and try again.

**Comment by AlfreDGR** [comment]
Supported MC Versions:
1.2.5 — 1.8.8 — 1.17 (all in between) 
...

**Comment by gone-incognito** [comment]
Yes, those are the supported versions. However as there have been multiple updates including several regarding how death messages work, you should update chatcontrol red to the latest version 10.4.9. As you are currently using 10.2.6

**Comment by TheIntolerant** [comment]
I think there may have been a slight misunderstanding, what banana meant by "update to the latest version" was updating the plugin chatcontrol, not the version the server runs on.

**Comment by AlfreDGR** [comment]
The chat control is updated to the latest version available

**Comment by ElBananaa** [comment]
> The chat control is updated to the latest version available

Hey!
It is not. (Or at least, not on the log file you sent us). Please send us an updated log file file the error. I'll take a look at it asap.

**Comment by AlfreDGR** [comment]
```------------------------------------[ 28.06.2021 18:02:49 ]-----------------------------------
ChatControlRed 10.4.9 encountered a FoException
Running Paper 1.17-R0.1-SNAPSHOT and Java 16.0.1
Plugins: PlaceholderAPI v2.10.10-DEV-null, PlugMan v2.1.7, NametagEdit v4.5.0, SkinsRestorer v14.1.0, EasyBackupCore v3.3.6, MultitoolPlusPro v3.5.0, LuckPerms v5.3.48, Votifier v2.7.2, EasyBackup v3.3.6, ProtocolLib v4.7.0-SNAPSHOT-b526, AdvancedCrates v2.0.109, 40ServidoresMC v2.5, FeatherBoard v5.0.1a, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, HolographicDisplays v2.4.8, ZHorse v1.8.2, ChestCommands v4.0.3, WorldEdit v7.3.0-SNAPSHOT+5836-183ae4a, PinataParty v2.29.1, HeadDatabase v4.14.1, SuperLobby v4.3.3, LogBlock v1.16.5.2-SNAPSHOT (build #132), PlotSquared v6.0.4-Premium, WorldGuard v7.0.6-SNAPSHOT+2121-32d16a7, CraftBook5 v5.0.0-SNAPSHOT+4719-6de2ee2, Multiverse-Core v4.3.1-SNAPSHOT-b847, Citizens v2.0.28-SNAPSHOT (build 2328), mcMMO v2.1.199, JPremium vCLEARED-Backend-1.11.3, ChestShop v3.12.1-SNAPSHOT (build 313), WarpSystem v5.0.3, GriefDefender v2.0.0-DEV, DeathChestPro v3.5.2, Spartan vBuild 415.1, Multiverse-Inventories v4.2.3-SNAPSHOT-b512, Multiverse-NetherPortals v4.2.2-SNAPSHOT-b801, Towny v0.97.0.8, WorldBorder v1.16.4, TownyChat v0.88, Shopkeepers v2.13.1, DiscordSRV v1.23.1-SNAPSHOT, TownyGUI v5.0, ChatControlRed v10.4.9, WildStacker v3.6.0-DEVb147, CMILib v1.0.2.4, BottledExp v3.0.0.0, MobFarmManager v1.6.0.0, Jobs v5.0.0.1, TradeMe v6.1.0.0, CMI v9.0.0.3, zAuctionHouseV3 v3.0.3.1, VotingPlugin v6.4, zAuctionHouse-Discord v1.0.3, MCPerks v1.17.5
----------------------------------------------------------------------------------------------

More Information: 
Log line size does not match structure: (8) [Date, Type, Sender, Receiver, Content, ChannelName, RuleName, RuleGroupName]. Line: (1)                                                                                                                                                                                                                                                                                                                                               
FoException Report: Log line size does not match structure: (8) [Date, Type, Sender, Receiver, Content, ChannelName, RuleName, RuleGroupName]. Line: (1)                                                                                                                                                                                                                                                                                                                                               
	 at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.chatcontrol.model.Log.fromLine(Log.java:373)
	 at org.mineacademy.chatcontrol.model.Log.lambda$purgeOldEntries$0(Log.java:354)
	 at java.base/java.util.ArrayList.removeIf(ArrayList.java:1682)
	 at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	 at org.mineacademy.chatcontrol.model.Log.purgeOldEntries(Log.java:352)
	 at org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:179)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:317)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
	 at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
	 at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
----------------------------------------------------------------------------------------------
```

**Comment by AlfreDGR** [comment]
------------------------------------[ 28.06.2021 18:02:49 ]-----------------------------------
ChatControlRed 10.4.9 encountered a FoException
Running Paper 1.17-R0.1-SNAPSHOT and Java 16.0.1
Plugins: PlaceholderAPI v2.10.10-DEV-null, PlugMan v2.1.7, NametagEdit v4.5.0, SkinsRestorer v14.1.0, EasyBackupCore v3.3.6, MultitoolPlusPro v3.5.0, LuckPerms v5.3.48, Votifier v2.7.2, EasyBackup v3.3.6, ProtocolLib v4.7.0-SNAPSHOT-b526, AdvancedCrates v2.0.109, 40ServidoresMC v2.5, FeatherBoard v5.0.1a, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, HolographicDisplays v2.4.8, ZHorse v1.8.2, ChestCommands v4.0.3, WorldEdit v7.3.0-SNAPSHOT+5836-183ae4a, PinataParty v2.29.1, HeadDatabase v4.14.1, SuperLobby v4.3.3, LogBlock v1.16.5.2-SNAPSHOT (build #132), PlotSquared v6.0.4-Premium, WorldGuard v7.0.6-SNAPSHOT+2121-32d16a7, CraftBook5 v5.0.0-SNAPSHOT+4719-6de2ee2, Multiverse-Core v4.3.1-SNAPSHOT-b847, Citizens v2.0.28-SNAPSHOT (build 2328), mcMMO v2.1.199, JPremium vCLEARED-Backend-1.11.3, ChestShop v3.12.1-SNAPSHOT (build 313), WarpSystem v5.0.3, GriefDefender v2.0.0-DEV, DeathChestPro v3.5.2, Spartan vBuild 415.1, Multiverse-Inventories v4.2.3-SNAPSHOT-b512, Multiverse-NetherPortals v4.2.2-SNAPSHOT-b801, Towny v0.97.0.8, WorldBorder v1.16.4, TownyChat v0.88, Shopkeepers v2.13.1, DiscordSRV v1.23.1-SNAPSHOT, TownyGUI v5.0, ChatControlRed v10.4.9, WildStacker v3.6.0-DEVb147, CMILib v1.0.2.4, BottledExp v3.0.0.0, MobFarmManager v1.6.0.0, Jobs v5.0.0.1, TradeMe v6.1.0.0, CMI v9.0.0.3, zAuctionHouseV3 v3.0.3.1, VotingPlugin v6.4, zAuctionHouse-Discord v1.0.3, MCPerks v1.17.5
----------------------------------------------------------------------------------------------

More Information: 
Log line size does not match structure: (8) [Date, Type, Sender, Receiver, Content, ChannelName, RuleName, RuleGroupName]. Line: (1)                                                                                                                                                                                                                                                                                                                                               
FoException Report: Log line size does not match structure: (8) [Date, Type, Sender, Receiver, Content, ChannelName, RuleName, RuleGroupName]. Line: (1)                                                                                                                                                                                                                                                                                                                                               
	 at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.chatcontrol.model.Log.fromLine(Log.java:373)
	 at org.mineacademy.chatcontrol.model.Log.lambda$purgeOldEntries$0(Log.java:354)
	 at java.base/java.util.ArrayList.removeIf(ArrayList.java:1682)
	 at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	 at org.mineacademy.chatcontrol.model.Log.purgeOldEntries(Log.java:352)
	 at org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:179)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:317)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
	 at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
	 at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
----------------------------------------------------------------------------------------------

**Comment by ElBananaa** [comment]
> ```
> ChatControlRed 10.4.9 encountered a FoException
> Running Paper 1.17-R0.1-SNAPSHOT and Java 16.0.1
> Plugins: PlaceholderAPI v2.10.10-DEV-null, PlugMan v2.1.7, NametagEdit v4.5.0, SkinsRestorer v14.1.0, EasyBackupCore v3.3.6, MultitoolPlusPro v3.5.0, LuckPerms v5.3.48, Votifier v2.7.2, EasyBackup v3.3.6, ProtocolLib v4.7.0-SNAPSHOT-b526, AdvancedCrates v2.0.109, 40ServidoresMC v2.5, FeatherBoard v5.0.1a, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, HolographicDisplays v2.4.8, ZHorse v1.8.2, ChestCommands v4.0.3, WorldEdit v7.3.0-SNAPSHOT+5836-183ae4a, PinataParty v2.29.1, HeadDatabase v4.14.1, SuperLobby v4.3.3, LogBlock v1.16.5.2-SNAPSHOT (build #132), PlotSquared v6.0.4-Premium, WorldGuard v7.0.6-SNAPSHOT+2121-32d16a7, CraftBook5 v5.0.0-SNAPSHOT+4719-6de2ee2, Multiverse-Core v4.3.1-SNAPSHOT-b847, Citizens v2.0.28-SNAPSHOT (build 2328), mcMMO v2.1.199, JPremium vCLEARED-Backend-1.11.3, ChestShop v3.12.1-SNAPSHOT (build 313), WarpSystem v5.0.3, GriefDefender v2.0.0-DEV, DeathChestPro v3.5.2, Spartan vBuild 415.1, Multiverse-Inventories v4.2.3-SNAPSHOT-b512, Multiverse-NetherPortals v4.2.2-SNAPSHOT-b801, Towny v0.97.0.8, WorldBorder v1.16.4, TownyChat v0.88, Shopkeepers v2.13.1, DiscordSRV v1.23.1-SNAPSHOT, TownyGUI v5.0, ChatControlRed v10.4.9, WildStacker v3.6.0-DEVb147, CMILib v1.0.2.4, BottledExp v3.0.0.0, MobFarmManager v1.6.0.0, Jobs v5.0.0.1, TradeMe v6.1.0.0, CMI v9.0.0.3, zAuctionHouseV3 v3.0.3.1, VotingPlugin v6.4, zAuctionHouse-Discord v1.0.3, MCPerks v1.17.5
> ----------------------------------------------------------------------------------------------
> 
> More Information: 
> Log line size does not match structure: (8) [Date, Type, Sender, Receiver, Content, ChannelName, RuleName, RuleGroupName]. Line: (1)                                                                                                                                                                                                                                                                                                                                               
> FoException Report: Log line size does not match structure: (8) [Date, Type, Sender, Receiver, Content, ChannelName, RuleName, RuleGroupName]. Line: (1)                                                                                                                                                                                                                                                                                                                                               
> 	 at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
> 	 at org.mineacademy.chatcontrol.model.Log.fromLine(Log.java:373)
> 	 at org.mineacademy.chatcontrol.model.Log.lambda$purgeOldEntries$0(Log.java:354)
> 	 at java.base/java.util.ArrayList.removeIf(ArrayList.java:1682)
> 	 at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
> 	 at org.mineacademy.chatcontrol.model.Log.purgeOldEntries(Log.java:352)
> 	 at org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:179)
> 	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:317)
> 	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> 	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
> 	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
> 	 at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
> 	 at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
> ----------------------------------------------------------------------------------------------
> ```

Alright, so there's a few things I don't understand.
On the first log file, your server was under paper 1.8.8, and now it runs on paper 1.17, so these issues are absolutely not related, why did you specify "1.8.8" in your server version then? Can I edit you post to suit the issue, or is this on another server?
Also, you need to install NashornPlus with java 15+ for the plugin to work correctly. You can find it here : https://bitbucket.org/kangarko/nashornplus/downloads/. Install the latest version (simply drop the jar file in your plugin folder), and let me know if the issue persists.

**Comment by AlfreDGR** [comment]
I have 2 servers one with 1.8.8 and other with 1.17

**Comment by AlfreDGR** [comment]
1.8.8
[error.log](https://github.com/kangarko/ChatControl-Red/files/6729538/error.log)

**Comment by AlfreDGR** [comment]
1.17

[error.log](https://github.com/kangarko/ChatControl-Red/files/6729542/error.log)

**Comment by sxphirus** [comment]
try deleting ```log.csv``` inside of your chatcontrolred folder

(or alternatively fixing it, but deleting is the easier of the two if you dont need the data it contains)

**Comment by ElBananaa** [comment]
Hey!
As sxphirus said, try deleting your log file on both server, then restart them, and let us know if it fixed the issue.

**Comment by kangarko** [comment]
Remove your log.csv file and it will work, updating from some ancient version must have corrupted it.
