### ISSUE TITLE
1.16.5: Conflict with ultra customizer and revealing old messages after relog.

### ISSUE THREAD

**Issue by MuriloWentz** [kangarko/ChatControl#1117]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false
---------------------------------
Hey again, im having a issue with the Delete Message feature.

https://www.youtube.com/watch?v=dD5YyltHTw4

When i Log in, a player has joined message show up in chat, then when i delete a message from the chat, this same message from previous times i joined gets revealed too. So i think thats a issue from CHC.

As you can see, after i type "/skin" twice, a Gui opens because of the rules sistem, and you cant see any message in chat because of ultra customizer. then i delete a message with my OP account, and every message hidden by Ultra Customizer gets revealed.

in the video my mouse didnt show up, sorry about that, you will still be able to understand whats happening.

**Comment by MuriloWentz** [comment]
[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/6719310/debug.1.zip)

**Comment by ElBananaa** [comment]
Hi,
I think we've previously had issues like yours with the plugin, that were caused by the plugin, due to a ProtocolLib update. I'd suggest waiting for Kangarko to get back from vacations to get this solved (on the 2nd of july) ^^

**Comment by MuriloWentz** [comment]
Np bro, im reporting everything i cant solve so kangarko can take a look when he come back, no problems about that. 

Thanks for you atention

**Comment by kangarko** [comment]
I unfortunately cannot resolve this right now since there's no easy way to determine whether or not the packet message is coming from UltraCustomizer or not, it's a third party plugin incompatibility issue.
