### ISSUE TITLE
1.16.5: Awaiting refund request

### ISSUE THREAD

**Issue by HRZNzero** [kangarko/ChatControl#1120]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

We've made a refund request via email (_atlacyorigin@gmail.com_) on the 23.06.2021.
We've received **neither** an answer/reply nor have we been refunded.
The refund-request was made _within the 30 day_ refund-timefframe as the original purchase was made on **06.06.2021**.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> We've made a refund request via email (_[atlacyorigin@gmail.com](mailto:atlacyorigin@gmail.com)_) on the 23.06.2021.
> We've received **neither** an answer/reply nor have we been refunded.
> The refund-request was made _within the 30 day_ refund-timefframe as the original purchase was made on **06.06.2021**.

Hey!
I'm sorry to read that the plugin doesn't suit you. You didn't receive an answeR to your refund request due to the fact that Kangarko is currently on vacations, until the 2nd of july, so you should get an answer near the beginning of july ^^

**Comment by HRZNzero** [comment]
Thanks for the ETA and the quick and friendly reply :)

Sincerely,
Zero

**Comment by kangarko** [comment]
Thanks, I'll handle this as soon as possible however I am still out of workspace for the next few days.
