### ISSUE TITLE
Civs integration

### ISSUE THREAD

**Issue by Effendil** [kangarko/ChatControl#1121]
Can you add integration of the Channels from the Plugin https://www.spigotmc.org/resources/civs.67350/

I think civs is more and more popular and grow a community that love that Plugin so it is a nice feature to have the channels for it.

i cant use the channels from civs because chatcontrol override all formats from them sadly.

**Comment by MuriloWentz** [comment]
heyy , can you add integration with SimpleClans channels too?

i want to use the rules sistem to create a clan chat toggle command, and atm creating this feature is only possible with CHC channels. Thanks! <3

https://www.spigotmc.org/resources/simpleclans.71242/

**Comment by kangarko** [comment]
Thanks! However we're busy with other priorities right now and won't plan on adding this additional third party support, thank you for your understanding.
