### ISSUE TITLE
1.16.5: Unable to use exclamation marks in chat messages (!)

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl#1123]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false
Chatcontrol Red: 10.4.8

If message includes "!", entire message is not sent to channel.  There is no rule match, not even anything in the log that happens it is as though the message was never typed.  I've tried a variety of positions for the placement of the !, but it doesn't appear to matter wherein the message the character is included, it completely kills the message.  I could only find anything about special treatment of "!" at the start of the message in some already included - although commented out - rules which I did not enable having to do with discord, so this seems to be an entirely different thing.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> Chatcontrol Red: 10.4.8
> 
> If message includes "!", entire message is not sent to channel. There is no rule match, not even anything in the log that happens it is as though the message was never typed. I've tried a variety of positions for the placement of the !, but it doesn't appear to matter wherein the message the character is included, it completely kills the message. I could only find anything about special treatment of "!" at the start of the message in some already included - although commented out - rules which I did not enable having to do with discord, so this seems to be an entirely different thing.

Hi,
Could you please provide us your `/chc debug` output file?

**Comment by mrcoffee1026** [comment]
yep: https://ufile.io/z521oz5c

**Comment by ElBananaa** [comment]
> yep: https://ufile.io/z521oz5c

Hey!
Thanks for sharing your debug file.
After looking a quick look at it, I was able to identify the source of your issue.
In `plugins\ChatControlRed\rules\global.rs`, line 54, 56 and 57, you forgot to comment the rule : 
```
# Uncomment to forward any message starting with ! to bungee channel
match (\!)(.*)
#then command ch send bungee $2
dont verbose
then deny
```
Which should look like : 
```
# Uncomment to forward any message starting with ! to bungee channel
#match (\!)(.*)
#then command ch send bungee $2
#dont verbose
#then deny
```

**Comment by mrcoffee1026** [comment]
I didn't "forget", that's uncommented by default.  However, the rule is supposed to apply if the message STARTS with an exclamation point, not if it simply contains one.  Shouldn't the match be something like ^(\!)(.*)$ to accomplish that?  As it is right now it just matches ALL exclamation points used in the message at all like "welcome back!" is a match, for example.

And thank you for the find of that default, I'd have never have seen that, I ignored the discord and bungee stuff since I wasn't using it.

**Comment by ElBananaa** [comment]
> I didn't "forget", that's uncommented by default. However, the rule is supposed to apply if the message STARTS with an exclamation point, not if it simply contains one. Shouldn't the match be something like ^(!)(.*)$ to accomplish that? As it is right now it just matches ALL exclamation points used in the message at all like "welcome back!" is a match, for example.
> 
> And thank you for the find of that default, I'd have never have seen that, I ignored the discord and bungee stuff since I wasn't using it.

I'm not really sure about it tbho. I'm not used to regex so I couldn't tell, but I guess this is how it should work normally.

**Comment by mrcoffee1026** [comment]
Well this is how regex normally functions, yes... but not the way this plugin is supposed to function by way of the documentation within that very file: "# Uncomment to forward any message starting with ! to bungee channel", Except, as we've already stated, the directive that removes the statement from chat "then deny" is uncommented by default, and while this documenation states this should be matching any statement "starting with !" : `^\!.*$`, it instead matches any statement that **contains** ! : `(\!)(.*)` The .* further ruins the match since the dot matches any or none, the * will match any characters or any length of characters... the two together means the ! can be at the end of the phrase and since the ^ and $ are not included (^ would means "starts with" and $ means "ends with"), the ! will match anywhere within in the entire phrase.  "I am NOT typing a discord command!" is a match as is "!this is a discord command"  This needs revised in the default for the config to fix, and should be commented out by default.

**Comment by ElBananaa** [comment]
> Well this is how regex normally functions, yes... but not the way this plugin is supposed to function by way of the documentation within that very file: "# Uncomment to forward any message starting with ! to bungee channel", Except, as we've already stated, the directive that removes the statement from chat "then deny" is uncommented by default, and while this documenation states this should be matching any statement "starting with !" : `^\!.*$`, it instead matches any statement that **contains** ! : `(\!)(.*)` The .* further ruins the match since the dot matches any or none, the * will match any characters or any length of characters... the two together means the ! can be at the end of the phrase and since the ^ and $ are not included (^ would means "starts with" and $ means "ends with"), the ! will match anywhere within in the entire phrase. "I am NOT typing a discord command!" is a match as is "!this is a discord command" This needs revised in the default for the config to fix, and should be commented out by default.

After taking a quick look at the true default file, as you can see on this screenshot, I can guarantee you that the comments are in the file by default, which means you must've removed them, or you previously used a very old version of the plugin which had this issue. The screenshot was taken from the plugin source page, so yes, this is commented by default.
![image](https://user-images.githubusercontent.com/53318613/123862029-1fc73400-d928-11eb-8e25-f472187f4b08.png)

As for the other part of the issue, I'll send a DM to Kangarko so he could take a look at it. ^^

**Comment by kangarko** [comment]
Thanks, I will fix that and ship a new version with default settings including ^ at the start to only match this when the message does start with an exclamation mark.
