### ISSUE TITLE
1.17: Multiple questions

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl#1125]
`ChatcontrolRed [03:02:18] [Server thread/INFO]: Warning: Your server is in offline mode, where UUIDs generate for every username. We recommend setting UUID_Lookup to false in mysql.yml to avoid data issues.`

Why does this show up? If I am using offline mode but have spigot with bungeecord true this does not really matter does it?

`ChatcontrolRed [03:02:18] [Server thread/INFO]: Update settings.yml at 'Messages.Async' -> '[]'`

what does this want me to exactly do?

`ChatcontrolRed [03:02:19] [Server thread/INFO]: Warning: Detected ViaVersion. If you're getting kicked out, set Integration.ProtocolLib.Listen_For_Packets and Tab_Complete.Enabled both to false in settings.yml.`

This also pops up but I have not really had issues?

Minecraft Version: 1.17
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> `ChatcontrolRed [03:02:18] [Server thread/INFO]: Warning: Your server is in offline mode, where UUIDs generate for every username. We recommend setting UUID_Lookup to false in mysql.yml to avoid data issues.`
> 
> Why does this show up? If I am using offline mode but have spigot with bungeecord true this does not really matter does it?
> 
> `ChatcontrolRed [03:02:18] [Server thread/INFO]: Update settings.yml at 'Messages.Async' -> '[]'`
> 
> what does this want me to exactly do?
> 
> `ChatcontrolRed [03:02:19] [Server thread/INFO]: Warning: Detected ViaVersion. If you're getting kicked out, set Integration.ProtocolLib.Listen_For_Packets and Tab_Complete.Enabled both to false in settings.yml.`
> 
> This also pops up but I have not really had issues?
> 
> Minecraft Version: 1.17
> MySQL: true
> BungeeCord: true

Hey,
The first thing is 9nly a warning, dont pay attention to it if your network runs in online mode.

For the 2nd thing this should only appear when updating the plugin. Basically, ot means the feature Message.Async in the settings file was updated.

Regarding the 3rd warning, well, it's just an advice if you encounter issues with ViaVersion installed. If you dont have these issues, then no need to do anything.
