### ISSUE TITLE
1.16.5: Issue filtering shit and ignoring words like shhhh it

### ISSUE THREAD

**Issue by SecretarySami** [kangarko/ChatControl#1127]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Okay so currently i'm attempting to ignore the string's "shh(xany amount of H) it" and filter "shit" , however it is no longer filtering the word shit 
https://i.imgur.com/wTWWjez.png
Little lost as to what happened as i had it working fine a bit ago

**Comment by ElBananaa** [comment]
Hey!
Try pasting your rule on this website and see if it is matched correctly or not : https://regex101.com/
Also, would you mind providing us the rule? It'll be easier to test your rule if we need to ^^

**Comment by SecretarySami** [comment]
> Hey!
> Try pasting your rule on this website and see if it is matched correctly or not : https://regex101.com/
> Also, would you mind providing us the rule? It'll be easier to test your rule if we need to ^^

here's the rules that im having issues with currently 

# Blocks 'shit'
match \b((s|5|1|\$)+(\W|\d|_)*h+(\W|\d|_)*(i|1|l|||\!)+(\W|\d|_)*(t|\+)+(\W|\d|_)*)
ignore string shh it'll||'s hit|shhh it|shhhh it|shhhhh it|shhhhhh it|shhhhhhh it
group swear

# Blocks 'bullshit'
match ((\bb|\B\ß|\Bt)+(\W|\d|_)*(u|h|\@|\_)+(\W|\d|_)*(l|i|1|l|||\!)+(\W|\d|_)*(l|s|5|1|\$)+(\W|\d|_)*(s|5|1|\$)+(\W|\d|_)*(h|\#)+(\W|\d|_)*(i|1|l|||\!)+(\W|\d|_)*(t|\+)+(\W|\d|_)*) 
ignore string shh it'll||'s hit|shhh it|shhhh it|shhhhh it|shhhhhh it|shhhhhhh it
group swear


(yes i have shhhhh it typed a bunch of times aha, our players keep increasing the amount of h's they have and it keeps filtering eep 

when i place the match into regex is shows this https://i.imgur.com/I0vGgQH.png

**Comment by ElBananaa** [comment]
> > Hey!
> > Try pasting your rule on this website and see if it is matched correctly or not : https://regex101.com/
> > Also, would you mind providing us the rule? It'll be easier to test your rule if we need to ^^
> 
> here's the rules that im having issues with currently
> 
> # Blocks 'shit'
> match \b((s|5|1|$)+(\W|\d|_)*h+(\W|\d|_)_(i|1|l|||!)+(\W|\d|_)_(t|+)+(\W|\d|_)*)
> ignore string shh it'll||'s hit|shhh it|shhhh it|shhhhh it|shhhhhh it|shhhhhhh it
> group swear
> 
> # Blocks 'bullshit'
> match ((\bb|\B\ß|\Bt)+(\W|\d|_)*(u|h|@|_)+(\W|\d|_)_(l|i|1|l|||!)+(\W|\d|_)_(l|s|5|1|$)+(\W|\d|_)*(s|5|1|$)+(\W|\d|_)_(h|#)+(\W|\d|_)_(i|1|l|||!)+(\W|\d|_)*(t|+)+(\W|\d|_)*)
> ignore string shh it'll||'s hit|shhh it|shhhh it|shhhhh it|shhhhhh it|shhhhhhh it
> group swear
> 
> (yes i have shhhhh it typed a bunch of times aha, our players keep increasing the amount of h's they have and it keeps filtering eep
> 
> when i place the match into regex is shows this https://i.imgur.com/I0vGgQH.png

Thanks.
Try replacing your first rule with this one, it should fix your issue : 
```
# Blocks 'shit'
match \b((|s|5|1|\$|)+(\W|\d|)*h+(\W|\d|)(I|i|1|l||!)+(\W|\d|_|)(t|\+)+(\W|\d|_)*)
ignore string shh it'll||'s hit|shhh it|shhhh it|shhhhh it|shhhhhh it|shhhhhhh it
group swear
```

**Comment by SecretarySami** [comment]
> Blocks 'shit'
> match \b((|s|5|1|\$|)+(\W|\d|)*h+(\W|\d|)(I|i|1|l||!)+(\W|\d|_|)(t|\+)+(\W|\d|_)*)
> ignore string shh it'll||'s hit|shhh it|shhhh it|shhhhh it|shhhhhh it|shhhhhhh it
> group swear

received this in chat https://i.imgur.com/KpMl0iN.png

**Comment by ElBananaa** [comment]
> > Blocks 'shit'
> > match \b((|s|5|1|$|)+(\W|\d|)_h+(\W|\d|)(I|i|1|l||!)+(\W|\d|_|)(t|+)+(\W|\d|_)_)
> > ignore string shh it'll||'s hit|shhh it|shhhh it|shhhhh it|shhhhhh it|shhhhhhh it
> > group swear
> 
> received this in chat https://i.imgur.com/KpMl0iN.png

Oh yeah right, that's because the `Blocks 'shit'` part isn't comment. Simply add a `#` before and reload the plugin. It should fix the issue.

**Comment by SecretarySami** [comment]
> > > Blocks 'shit'
> > > match \b((|s|5|1|$|)+(\W|\d|)_h+(\W|\d|)(I|i|1|l||!)+(\W|\d|_|)(t|+)+(\W|\d|_)_)
> > > ignore string shh it'll||'s hit|shhh it|shhhh it|shhhhh it|shhhhhh it|shhhhhhh it
> > > group swear
> > 
> > 
> > received this in chat https://i.imgur.com/KpMl0iN.png
> 
> Oh yeah right, that's because the `Blocks 'shit'` part isn't comment. Simply add a `#` before and reload the plugin. It should fix the issue.

Will retry this in a moment.  My apologies for the slow replies and hassle 😅

**Comment by SecretarySami** [comment]
> > > Blocks 'shit'
> > > match \b((|s|5|1|$|)+(\W|\d|)_h+(\W|\d|)(I|i|1|l||!)+(\W|\d|_|)(t|+)+(\W|\d|_)_)
> > > ignore string shh it'll||'s hit|shhh it|shhhh it|shhhhh it|shhhhhh it|shhhhhhh it
> > > group swear
> > 
> > 
> > received this in chat https://i.imgur.com/KpMl0iN.png
> 
> Oh yeah right, that's because the `Blocks 'shit'` part isn't comment. Simply add a `#` before and reload the plugin. It should fix the issue.

Thank you!

**Comment by SecretarySami** [comment]
nvm that's not why, i removed it and it's still able to be said

**Comment by SecretarySami** [comment]
# Blocks 'bullshit'
match ((\bb|\B\ß|\Bt)+(\W|\d|_)*(u|h|\@|\_)+(\W|\d|_)*(l|i|1|l|||\!)+(\W|\d|_)*(l|s|5|1|\$)+(\W|\d|_)*(s|5|1|\$)+(\W|\d|_)*(h|\#)+(\W|\d|_)*(i|1|l|||\!)+(\W|\d|_)*(t|\+)+(\W|\d|_)*) 
ignore string shh it'll|'s hit|
group swear

Now seems this is the only one im having issues with

**Comment by ElBananaa** [comment]
> ((\bb|\B\ß|\Bt)+(\W|\d|_)*(u|h|@|_)+(\W|\d|_)_(l|i|1|l|||!)+(\W|\d|_)_(l|s|5|1|$)+(\W|\d|_)*(s|5|1|$)+(\W|\d|_)_(h|#)+(\W|\d|_)_(i|1|l|||!)+(\W|\d|_)*(t|+)+(\W|\d|_)*)

Try with this rule, it should also work. Also keep in mind that we can't make all your rules for you, so here's a useful tool to test your regex rules : https://regex101.com/
```
# Blocks 'bullshit'
match \b((b|\ß)+(\W|\d|)*(u|h|@|_)+(\W|\d|)(l|i|1|l||!|)+(\W|\d|)(l|s|5|1|\$|)+(\W|\d|)*(s|5|1|\$)+(\W|\d|)(h|#)+(\W|\d|)(i|1|l||!)+(\W|\d|)*(t|\+)+(\W|\d|)*)
ignore string shh it'll|'s hit|
group swear
```

**Comment by SecretarySami** [comment]
Hello, i know this has been closed however do to this being im assuming related to the above i'm commenting on this one .
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true
https://i.imgur.com/CXIR5KW.png

After removing all the ignore strings thinking that one of those is having to do with being able to say the word "shit"
# Blocks 'shit'
match \b((|s|\$|)+(\W|\d|)*h+(\W|\d|)(I|i|1|l||!)+(\W|\d|_|)(t|\+)+(\W|\d|_)*)
ignore string 
group swear

# Blocks 'bullshit'
match \b((b|\ß)+(\W|\d|)*(u|h|@|_)+(\W|\d|)(l|i|1|l||!|)+(\W|\d|)(l|s|1|\$|)+(\W|\d|)*(s|\$)+(\W|\d|)(h|#)+(\W|\d|)(i|1|l||!)+(\W|\d|)*(t|\+)+(\W|\d|)*)
ignore string 
group swear
And using the Match given above both words are able to be said and in our console - https://i.imgur.com/0ikkhnd.png
It is not even triggering the filter anymore O.o i'm not sure if there's an actual issue or if you could just tell me if this is on my end ?
