### ISSUE TITLE
Gradient Generator Suggestion!

### ISSUE THREAD

**Issue by MuriloWentz** [kangarko/ChatControl#1128]
![image](https://user-images.githubusercontent.com/50129175/124327453-59818000-db5e-11eb-8a4a-ee2e179d8237.png)

Hey kangarko! can you add a Gradient generator format for config files? just like the example above used by CMI.
1. How it would benefit others? It will allow every one generate gradients easily instead of creating one hex by hex.

2. What would happen if we won't implement this feature? people will have to create gradients by hand and they may not be perfect.

Thank you for providing us such a beautifully coded minecraft plugin! I LOVE ChatControlRED 100% <3

**Comment by kangarko** [comment]
Thanks for your suggestion! I believe it's already on our roadmap however due to other priorities it's not on the table right now.
