### ISSUE TITLE
1.17: plotsqaured-plot no longer working.

### ISSUE THREAD

**Issue by toxinyx** [kangarko/ChatControl#1129]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6757322/debug.zip)

On 1.16.5, we had this:

> Local:
>       Format: '&e[L] &r{pl_prefix}%essentials_nickname% &e>> {message}'
>       Party: plotsquared-plot

and it worked. Now we have 1.17, and the exact same code no longer works: when someone talks in /l, anybody on the same plot won't see it. It's now just a single-user chat.

and yes: EVERYONE has the right permissions. When I do /ch list it also says that the users are in Local on read mode.
I already asked the p2 devs if they dropped support (since I didn't really know how it worked) with plotsquared-version 6. and thhe response i got was:
> That wouldn't be something we monitor and would require them to do a minor update most likely

Minecraft Version: 1.17.0
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6757322/debug.zip)
> 
> On 1.16.5, we had this:
> 
> > Local:
> > Format: '&e[L] &r{pl_prefix}%essentials_nickname% &e>> {message}'
> > Party: plotsquared-plot
> 
> and it worked. Now we have 1.17, and the exact same code no longer works: when someone talks in /l, anybody on the same plot won't see it. It's now just a single-user chat.
> 
> and yes: EVERYONE has the right permissions. When I do /ch list it also says that the users are in Local on read mode.
> I already asked the p2 devs if they dropped support (since I didn't really know how it worked) with plotsquared-version 6. and thhe response i got was:
> 
> > That wouldn't be something we monitor and would require them to do a minor update most likely
> 
> Minecraft Version: 1.17.0
> MySQL: false
> BungeeCord: false

Hey! If you are using plotsquared v6, this issue is normal. CHC-Red doesn't support this version of the plugin yet. There's no ETA for the support of this plugin, however, I don't thiink it'll take much time to add suport for it since the api changes are really small.

**Comment by toxinyx** [comment]
> Hey! If you are using plotsquared v6, this issue is normal. CHC-Red doesn't support this version of the plugin yet. There's no ETA for the support of this plugin, however, I don't thiink it'll take much time to add suport for it since the api changes are really small.

Okay yeah, that’s what I thought ahah. I just wanted to make sure that it wasn’t a one off thing that I was having issues with. That’s fine, thank you :D

**Comment by kangarko** [comment]
I will update to PlotSquared 6 in the next version :)
