### ISSUE TITLE
Sender-permission and reciever-permission suggestion

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#113]
Add integration with popular permission managers (LuckPerms at least), to be able to check player's groups list or the main(highest priority) group, because permission check works badly for players with * in permissions or for groups that inherit other groups permissions.

![image](https://user-images.githubusercontent.com/62369973/99683841-d3fb0500-2a91-11eb-9ca0-38bda94c9722.png)
![image](https://user-images.githubusercontent.com/62369973/99683863-d9f0e600-2a91-11eb-92cc-ad21cf722e4b.png)

The second way is to add the ability to make one format part display different messages depending on the condition or the permission

**Comment by kangarko** [comment]
Thank you for your suggestion!
