### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by LordYarkan** [kangarko/ChatControl#1130]

**Comment by LordYarkan** [comment]
😬 the plugin is expensive, it hurts to buy it again the chatcontrol :(

**Comment by MuriloWentz** [comment]
You have chatcontrol pro?

**Comment by LordYarkan** [comment]
Yes, I bought it for in the year 2020

**Comment by MuriloWentz** [comment]
scroll all the way down this page: https://mineacademy.org/chatcontrol-red/

**Comment by LordYarkan** [comment]
Thank you very much, I already sent my email :). I hope I can rate

**Comment by MuriloWentz** [comment]
You're welcome friend!

**Comment by ElBananaa** [comment]
Hi,
Why did you open this issue? There's absolutely no content in your main message.
Do you still need help or may I close this issue?

**Comment by LordYarkan** [comment]
If you close it please, I must wait 5 days for the answer

**Comment by MuriloWentz** [comment]
> If you close it please, I must wait 5 days for the answer

what you mean? looks like i helped you already, do you still need help with something?

**Comment by LordYarkan** [comment]
Then I will return to see what happened, I will wait 5 days for the mail to arrive. Close the ticked. I'll contact you later

**Comment by kangarko** [comment]
I just reviewed and approved all applications, if you haven't been approved send your MCMarket username to matej@mineacademy.org manually :)
