### ISSUE TITLE
1.16.5: Specified Key Value Too Long on Startup

### ISSUE THREAD

**Issue by mattc4t** [kangarko/ChatControl#1132]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

On startup after updating all servers in a bungee network to ChatControl Red, I see the following error:

Error on updating MySQL with: CREATE TABLE IF NOT EXISTS `ChatControl` ( `UUID` varchar(255) NOT NULL, `Name` text, `Nick` text, `Data` longtext, `LastModified` bigint(20) DEFAULT NULL, PRIMARY KEY (`UUID`)) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
MySQLSyntaxErrorException **Specified key was too long;  
[error.log](https://github.com/kangarko/ChatControl-Red/files/6762370/error.log)
max key length is 767 bytes**

ChatControl Red then unloads itself after experiencing the error.

**Workaround**
I worked around this issue by manually creating the table in phpMyAdmin and specifying varchar(64) for the UUID field instead of varchar(255).

I experienced a similar error for the table creation for ChatControl_Mail table and applied the same workaround...  

Perhaps the Unicode collation explodes the total size of the 256-character field x4 to 1024 bytes, which would exceed the maximum key length for MySQL...

**Comment by kangarko** [comment]
Thanks, I narrowed the key size to 64 as you suggested and that fixed the problem.

**Comment by mattc4t** [comment]
Great!  Thank you!

Matthew
