### ISSUE TITLE
nick bug

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#1133]
Minecraft Version: 1.17
MySQL: true
BungeeCord: true

you can't (/tag nick off) if player off exist

**Comment by kangarko** [comment]
You can only do this when the player is registered and online.

**Comment by FakEEE14** [comment]
i mean player with name OFF exist you can't /tag nick off , because it's says you can't impersenate

**Comment by kangarko** [comment]
Sorry this is an incompatibility, we rarely see players with the name of OFF and ChatControl is not designed to work with them

**Comment by FakEEE14** [comment]
easy way to ban player named OFF :D
