### ISSUE TITLE
Help needed with assigning img prefixes and luckperms to CCR groups.

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#1134]
Hi

I'm wanting to assign img to groups prefixes and know how to create the prefixes, i.e. %img_:name:% 

I've created the groups in settings.yml but i do not know how to assign the img prefixes to the groups, or how to connect my luckperms groups to the chat control groups so that luckperms knows which group to assign each player?

I see the "TIP: Making Player Prefixes" section of the wiki under Format but not sure where to place them, bit confuses as the groups section is in the settings.yml but this prefix section is under formats.

**Comment by 00Hrtz** [comment]
OK so im not sure if this is correct but i've assigned all my groups in luckperms with `chatcontrol.group.name` permission.

I just need to find out how to assign prefixes and suffixes to the groups i've set in settings.yml

**Comment by 00Hrtz** [comment]
I've tried doing it but it's throwing errors and the instructions are very vague  

https://paste.helpch.at/sebokuhaju.py

**Comment by kangarko** [comment]
Do not use groups to assign player prefixes/suffixes, the recommended way is to use LuckPerms to create these.

I do not think we currently support assigning an image to a group if I am not mistaken.
