### ISSUE TITLE
1.16.5 Paper: Remove messages permission not working

### ISSUE THREAD

**Issue by Zalaee** [kangarko/ChatControl#1135]
permission - chatcontrol.removemessages doesn't seem to work.
Yes it shows the red [x] upon adding the permission but when you click it, it doesn't work.
Clicking works only if player is set as Op.
Even after applying permission chatcontrol.* the problem still exists.

Minecraft Version: 1.16.5 Paper
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Does having an operator status resolve this? I will try to reproduce this in 1-3 days

**Comment by Zalaee** [comment]
Yes if i'm on operator it works as intended. I'm setting up perms for staff and upon testing it, it doesn't work.

**Comment by kangarko** [comment]
I am unfortunately not able to reproduce:

![a](https://i.imgur.com/aZEl2v6.gif)

This might be due to other plugin or a misconfiguration in your permissions plugin, check these please.
