### ISSUE TITLE
1.16.5: RGB HEX Color formats issues

### ISSUE THREAD

**Issue by Jmaniacs** [kangarko/ChatControl#1136]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hi, my luckperms prefixes are bad writen by the plugin. In discord and in game, look at the photos.
Thank you
![image](https://user-images.githubusercontent.com/45721052/124522824-8c2bb280-ddc2-11eb-93e6-1fdefef4aeef.png)
![image](https://user-images.githubusercontent.com/45721052/124522832-90f06680-ddc2-11eb-89a7-601bffe01062.png)

**Comment by UserDerezzed** [comment]
Duplicate of #1113

**Comment by ElBananaa** [comment]
Hey,
As said by relavis, an issue is already open regarding hex color support improvement.
I'm closing this issue, updates will be given on #1113
