### ISSUE TITLE
1.16.5: No Quit Messages on One Server

### ISSUE THREAD

**Issue by DavidSelberg** [kangarko/ChatControl#1138]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6767307/debug.zip)

I'm having an issue where quit messages don't show up on one of my servers (on a bungee network). They work on other servers, and I still see join messages on that server. I don't see any errors in console and my settings.yml match exactly between servers.

**Comment by DavidSelberg** [comment]
I am also seeing the following in my bungee console (though I'm not sure if it's related):
`07.07 02:02:06 [Server] WARN Event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@29a0bfdb, receiver=bdkanerva), cancelled=false, tag=plugin:chcred) took 323ms to process!
07.07 02:02:06 [Server] WARN Event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@9a8f8b6, receiver=lilybull), cancelled=false, tag=plugin:chcred) took 281ms to process!
07.07 02:02:06 [Server] WARN Event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@1b4e800d, receiver=bcuziwasbored), cancelled=false, tag=plugin:chcred) took 445ms to process!
07.07 02:02:06 [Server] WARN Event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@29a0bfdb, receiver=bdkanerva), cancelled=false, tag=plugin:chcred) took 1,047ms to process!
07.07 02:02:06 [Server] WARN Event ChatEvent(super=TargetedEvent(sender=PenniBoii, receiver=net.md_5.bungee.ServerConnection@55530831), cancelled=false, message=/lag) took 7,016ms to process!`

**Comment by kangarko** [comment]
The debug file you uploaded only contains the default quit message:

![a](https://i.imgur.com/dof5zQg.png)

Just to confirm this is configured not to show it as per Messages.Apply_On key in settings.yml so I assume you are talking about the configuration from BungeeControl Red. Please ZIP me that plugin folder.

**Comment by DavidSelberg** [comment]
[BungeeControl-Red.zip](https://github.com/kangarko/ChatControl-Red/files/6796519/BungeeControl-Red.zip)
Here's the zip file for my bungee.

**Comment by DavidSelberg** [comment]
What I'm trying to do is have join/leave messages show up when people join/leave the network, but not when they switch servers. It works on all of the other servers, but that one, in particular, has no leave messages period.

**Comment by kangarko** [comment]
Just as a test set Messages_New.Ignored_Servers to be an empty list of []. You also need to set Messages.Enabled to false since using both messaging systems is unsupported.

**Comment by kangarko** [comment]
If that still won't help then unfortunately it's likely that's another plugin causing it, I'd advise just testing ChatControl and its bungee extension for that server

**Comment by DavidSelberg** [comment]
Okay, I'm still seeing a second join message (not sure where it's coming from) but the quit messages are fixed. I have to figure out if there's a second plugin sending join messages. Thanks for your help!
