### ISSUE TITLE
1.16.5: DiscordSRV duplicate text. 

### ISSUE THREAD

**Issue by WolverStones** [kangarko/ChatControl#1139]
Hi, I have a question, I have a bungee server and I use admin chat which I have connected to the Discord room. Everything works just I have one problem when I send the text from Discord to the server so it duplicates, probably it's because I have more servers connected but I would like to know if it can be solved so that it does not duplicate.

![image](https://user-images.githubusercontent.com/7571437/124592618-ef1e5780-de5d-11eb-9e45-d6d04fb66550.png)

https://ufile.io/55lsr1tx
Minecraft Version: 1.16.5 
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Yes if you have multiple servers connected to Discord then the message will duplicate, unfortunately due to technical reasons there is no workaround for this right now. You can however use another plugin or DiscordSRV to handle MC>Discord sending for the time being.
