### ISSUE TITLE
[1.16.3] And another error while saving Gradients :D

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#114]
What it used to be like:
![image](https://user-images.githubusercontent.com/62369973/99688621-1246f300-2a97-11eb-8b6f-7a42d168e7ca.png)

What is it like after a restart:
![image](https://user-images.githubusercontent.com/62369973/99688655-1d018800-2a97-11eb-8798-82bdcab3f66e.png)

And here comes the error:
https://pastebin.com/FS1Xf5Nr

**Comment by kangarko** [comment]
Interesting I'll test it out.

**Comment by kangarko** [comment]
Thanks I found and fixed that bug!
