### ISSUE TITLE
Color tips

### ISSUE THREAD

**Issue by DeusNinja** [kangarko/ChatControl#114]
Seems to be a minor bug, not sure though, here's what I've got
If I create a tip line which starts with a color code, it removes that world with the color code and the rest of the message is the last color used in the prefix of the tips settings. 

I've been bypassing this by adding a character infront of all my tips, as it seems to allow color codes which are not the first thing on the tip. 
This is a screenshot of the message, I attempted to set &cGriefing as the first word in the tip message
http://prntscr.com/be5u0f
This is my work around for now..
http://prntscr.com/be5t6o

ps, I really enjoy your plugin, it makes running my server 100x better. Keep up the great work!
#premiumCC

**Comment by kangarko** [comment]
Have you tried putting the entire message in ' ' quotes? Or in " "

**Comment by DeusNinja** [comment]
I have tried single quotes, I'll test with the double quotes and let you know how it goes.

**Comment by kangarko** [comment]
@DeusNinja is it working?

**Comment by kangarko** [comment]
Please let me know if it occurs again.
