### ISSUE TITLE
1.16.5: Default Message Variables Issue/Question

### ISSUE THREAD

**Issue by jpalip** [kangarko/ChatControl#1140]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6771979/debug.zip)

Hello I'm trying to use the default [item] variable in chat and I haven't changed the item.yml at all its still the default generated file, however whenever any player says "[item]" in chat it does not work it just displays [item] instead of the actual item in the players hand. I also did not receive any errors at all it just doesn't work.

I am using EssentialsXChat as well to format the chat so I'm not sure if that has an effect on this.

Server Version: Paper MC v778 (1.16.5)
ChatControlRed Version: 10.4.9

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6771979/debug.zip)
> 
> Hello I'm trying to use the default [item] variable in chat and I haven't changed the item.yml at all its still the default generated file, however whenever any player says "[item]" in chat it does not work it just displays [item] instead of the actual item in the players hand. I also did not receive any errors at all it just doesn't work.
> 
> I am using EssentialsXChat as well to format the chat so I'm not sure if that has an effect on this.
> 
> Server Version: Paper MC v778 (1.16.5)
> ChatControlRed Version: 10.4.9

Hey,
We do not recommend using 2 chat plugins, so I'd suggest removing EssentialsXChat in a first place, then also enable the channels feature in ChatControl's settings file.

**Comment by kangarko** [comment]
The other chat plugin is the fact why there is incompatibility, use our plugin to manage chat or the other one without our [item] feautre.
