### ISSUE TITLE
1.17.1: Discord messages not going through to chat 

### ISSUE THREAD

**Issue by SecretarySami** [kangarko/ChatControl#1141]
The current issue I'm experiencing is that chat messages from discord are not appearing in in game chat. https://youtu.be/yZJTw13LY2w

We are also experiencing the same issue except reversed, where our discord messages are in fact going through however the in game messages are not showing up in the discord channel

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by Skizzles** [comment]
I spoke with DiscordSRV regarding this and they believe it's CHC's issue.

**Comment by kangarko** [comment]
Please set the Debug key in our settings.yml to [discord] and post me the Minecraft console log when you type a Discord message that should go into Minecraft but it doesn't.

**Comment by SecretarySami** [comment]
> [discord]

This is the only thing that showed up in console after turning the debug on - 
[01:36:57 INFO]: [DiscordSRV] Chat: SrAdmin Sami > test

**Comment by Skizzles** [comment]
Was an issue with discordsrv, it wanted the channels moved around for some reason.

**Comment by kangarko** [comment]
There must be more messages than this, post me your full console output when you type a message on Discord. Or set debug to ["*"] for the few moments to test it.

**Comment by kangarko** [comment]
I also advise to watch the training video at the link below to ensure you have followed all the steps:

https://github.com/kangarko/ChatControl-Red/wiki/Discord

**Comment by kangarko** [comment]
If you still need help after that video then comment below here please.
