### ISSUE TITLE
1.17.1: Groups when chatting from discord

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl#1142]
Minecraft Version: 117.1
MySQL: true
BungeeCord: false

So, this might not be a bug but I suppose it's something overlooked. There is this option to make groups and change settings like message_delay,... However, this message delay does not get applied when chatting through discord.

We give some players the "slowmode" which gives them a Message delay of 20 seconds, and we don't want to give everybody the 20 seconds slowmode when chatting through discord, only certain people.

Thank you already!

**Comment by kangarko** [comment]
Thanks, however due to technical reasons the discord sender is not a player where we can apply these group-specific checks, so we default to the global option.
