### ISSUE TITLE
1.17.1: General format chat doesn't work

### ISSUE THREAD

**Issue by JustDriessen** [kangarko/ChatControl#1146]
When updating from a previous version to a newer version for 1.17 with the nashornplus plugin the chat stopped working, after installing te new update that just got released, my general chat still doesn't appear to be working. Got Spy chat instead. When NashornPlus is on my server it works tho. Was wondering if there is a way to not have the NashornPlus in my server and have the general working.

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: false

**Comment by ElBananaa** [comment]
> When updating from a previous version to a newer version for 1.17 with the nashornplus plugin the chat stopped working, after installing te new update that just got released, my general chat still doesn't appear to be working. Got Spy chat instead. When NashornPlus is on my server it works tho. Was wondering if there is a way to not have the NashornPlus in my server and have the general working.
> 
> Minecraft Version: 1.17.1
> MySQL: true
> BungeeCord: false

Hey!
NashornPlus is needed for 1.17+ versions or more generally for servers running with java 15+.

**Comment by SiuanSong** [comment]
Where is this requirement for the NashornPlus library stated?  I do not see it on the ChatControl Red product page nor in the README.

**Comment by ElBananaa** [comment]
> Where is this requirement for the NashornPlus library stated? I do not see it on the ChatControl Red product page nor in the README.

Right, it's not on the main plugin page nor on the wiki. However, it's stated in your server log that this is required when using java 15+. Here's the link to download NashornPlus: https://mineacademy.org/nashorn/

**Comment by SiuanSong** [comment]
Okay, might be a good idea to add it to both of those.  Most people don't typically look at the server log to see what dependencies a plugin requires.

**Comment by ElBananaa** [comment]
@kangarko ^^

**Comment by kangarko** [comment]
Thanks, added a note regarding this.
