### ISSUE TITLE
1.16.5: Critism and Suggestions/Questions

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#1147]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

I have some constructive critism and suggestions, as a long user and tester of chc-free, chc pro and chc red

Hey, chc red is an amazing plugin and iam using it for a long time. But iam now struggeling, to code my own little chat plugin to replace chc red.

I have to say, that chc is getting heavier and heavier. 
with 1.17+, i have to install nashorn-engine, for no reason. I dont use JavaScript and i find the js integration extrem heavy and useless in some cases. The plugin also have some extremly unneeded features, which makes the plugin not lightweight anymore. "/tag", "/spy", "js", "deathmessages", "mail" I have a suggestion for a lite version of chc red, called: chc red-lite which only contains rules, anti-spam and not the tag/msg stuff

I would also suggest to make an addon based system, instead of java script. so peoples can write "modules" for chc red. So you can give /tag /msg /book and all that stuff as extra modules, so i can configure chc for my needs. The modules also add the needed config options. so i only have options in the config that are needed.

The next thing is the extreme lack of customization. The help and all that stuff like /channels and so on could be multiline messaes without hardcoded spaces and new lines. So it is extremly hard/impossible to fit on my servers design.

My Suggestions:
- remove js (All what i have to install externally is bad)
- create module based addon system with a /modules/ folder
- give /tag /msg, /spy, mail, deathmessages, discord integration  as extra modules
- config is extrem heavy - add config options based on installed modules instead of 1 heavy config
- remove the /mute command. It is completly unnessesary because so many servers using a punishment plugin. So the feature is only making the plugin heavier
- Most of the features are completely overpowered like a spy menu

Create a lite version (Included in chc red)
This will contain:
- Chat formating
- rules/regions
- anti spam

Things i very like on chc-red that makes me struggeling replacing it... ;(
- The rule system is so amazing
- the chat formatting
- color and rgb support
- the anti-spam with groups

I hope you will read this and thinking about this. 

Joey

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> I have some constructive critism and suggestions, as a long user and tester of chc-free, chc pro and chc red
> 
> Hey, chc red is an amazing plugin and iam using it for a long time. But iam now struggeling, to code my own little chat plugin to replace chc red.
> 
> I have to say, that chc is getting heavier and heavier.
> with 1.17+, i have to install nashorn-engine, for no reason. I dont use JavaScript and i find the js integration extrem heavy and useless in some cases. The plugin also have some extremly unneeded features, which makes the plugin not lightweight anymore. "/tag", "/spy", "js", "deathmessages", "mail" I have a suggestion for a lite version of chc red, called: chc red-lite which only contains rules, anti-spam and not the tag/msg stuff
> 
> I would also suggest to make an addon based system, instead of java script. so peoples can write "modules" for chc red. So you can give /tag /msg /book and all that stuff as extra modules, so i can configure chc for my needs. The modules also add the needed config options. so i only have options in the config that are needed.
> 
> The next thing is the extreme lack of customization. The help and all that stuff like /channels and so on could be multiline messaes without hardcoded spaces and new lines. So it is extremly hard/impossible to fit on my servers design.
> 
> My Suggestions:
> 
> * remove js (All what i have to install externally is bad)
> * create module based addon system with a /modules/ folder
> * give /tag /msg, /spy, mail, deathmessages, discord integration  as extra modules
> * config is extrem heavy - add config options based on installed modules instead of 1 heavy config
> * remove the /mute command. It is completly unnessesary because so many servers using a punishment plugin. So the feature is only making the plugin heavier
> * Most of the features are completely overpowered like a spy menu
> 
> Create a lite version (Included in chc red)
> This will contain:
> 
> * Chat formating
> * rules/regions
> * anti spam
> 
> Things i very like on chc-red that makes me struggeling replacing it... ;(
> 
> * The rule system is so amazing
> * the chat formatting
> * color and rgb support
> * the anti-spam with groups
> 
> I hope you will read this and thinking about this.
> 
> Joey

Hey!
There are a lot of problems with your suggestion:
- It'll require a massive rewrite of the plugin which could take several weeks/months.
- It's based on the fact that you feel like the js system is useless, however, a lot of current users are using it (me included).
- Some users also use the mute system
- The spy system is one of the best feature of the plugin, it's complete, well made and works perfectly, so why would it be removed?
- Making a lite version would be even more time consuming. What's the point of making a lite version if the main version is already supposed to work with a module system, except the fact that it'll require twice more time & work to maintain? (Time that Kangarko already doesn't have).

Finally, I don't understand why would you replace the plugin? Is it laggy? If so, I'd suggest giving us timings report & spark sampler?
In my opinion, you have some good ideas, but I think they're unachievable with the plugin in it's current state.

**Comment by DevJoey** [comment]
Yea i know that this is a huge change. I dont want any features to be removed. This is only a suggestion to make those features as seperate "modules"! I struggle with replacing chc because i cannot make the plugin fit 100% in my servers design, because some messages like "help", "chatlog header/design" are not customizeable. chc has a lot of messages and i can translate them but the design (like headers, lines usw) cannot be removed/customized. It would be better if the chc messages for /channels is multiline with placeholders. So i cann simple add/remove lines, that i dont want and make it so fit my servers design. and this with all messages using a header and so on.

The next, that would be nice is an option, to completely disable that java script stuff. I dont want an additional plugin (nashorn) on my server for a feature, that iam not unsing.

I have recoded my complete server system to a module based one. I only have 3 plugins and one core which has a module folder. So i cann simple extend it without installing multiple plugins. This also provides me a powerful api to interact with my server. That system is so beautiful, that i suggested the same principe to chc-red, to make it more scaleable.

**Comment by kangarko** [comment]
Thanks. The reason we are requiring Nashorn is that our library still uses it. It will also be used through out the plugin even if you don't see this, it was unneeded as an external plugin however Java 15 removed it from its jar so now we have to ship it separately.

I won't make another ChatControl or modules, it's already too much work for one person, however you can disable all of these commands off completely and performance won't be affected in this case.

You can customize the main and the channels command headers completely in our localization file, there's two keys responsible for this using the two "Header_Alternative" keys you can find.

If there's anything else that's not customizable, you can just create a custom rule for this using rules/command.rs that will print out a fully customized message using the examples provided there.

Other than that I do appreciate your feedback.
