### ISSUE TITLE
1.16.5: Whitelists not being respected: Whitelist_Delay, Whitelist_Similarity

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl#1148]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

relevent setting:
```
    # Regular expressions that, if match the message, will prevent delay check from applying.
    Whitelist_Delay:
    - ':D'
    - 'xD'
    - 'ty'
    - 'yw'
    - 'brb'
    - 'ha'
    - 'haha'
    - 'hahaha'
    - 'welcome'
    - 'wb'
    - 'hey'
    - 'hi'
    - 'sof'
    - 'thanks'
    - 'thnx'
    - 'thanx'
    - 'hello'
    - 'hey'
    - 'rip'
    - 'lol'
    - 'xD'
    - 'welcome back'
    
    # Regular expressions that, if match the message, will prevent similarity check from applying.
    Whitelist_Similarity:
    - ':D'
    - 'xD'
    - 'ty'
    - 'yw'
    - 'brb'
    - 'ha'
    - 'haha'
    - 'hahaha'
    - 'welcome'
    - 'wb'
    - 'hey'
    - 'hi'
    - 'sof'
    - 'thanks'
    - 'thnx'
    - 'thanx'
    - 'hello'
    - 'hey'
    - 'rip'
    - 'lol'
    - 'xD'
    - '^hello \w+$'
    - '^hey \w+$'
    - '^hi \w+$'
    - 'welcome back'

```
attempted typing "wb" in chat after another player and...
![download](https://user-images.githubusercontent.com/3322491/125208014-07c3ae80-e25e-11eb-902a-64364b5b911a.png)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> relevent setting:
> 
> ```
>     # Regular expressions that, if match the message, will prevent delay check from applying.
>     Whitelist_Delay:
>     - ':D'
>     - 'xD'
>     - 'ty'
>     - 'yw'
>     - 'brb'
>     - 'ha'
>     - 'haha'
>     - 'hahaha'
>     - 'welcome'
>     - 'wb'
>     - 'hey'
>     - 'hi'
>     - 'sof'
>     - 'thanks'
>     - 'thnx'
>     - 'thanx'
>     - 'hello'
>     - 'hey'
>     - 'rip'
>     - 'lol'
>     - 'xD'
>     - 'welcome back'
>     
>     # Regular expressions that, if match the message, will prevent similarity check from applying.
>     Whitelist_Similarity:
>     - ':D'
>     - 'xD'
>     - 'ty'
>     - 'yw'
>     - 'brb'
>     - 'ha'
>     - 'haha'
>     - 'hahaha'
>     - 'welcome'
>     - 'wb'
>     - 'hey'
>     - 'hi'
>     - 'sof'
>     - 'thanks'
>     - 'thnx'
>     - 'thanx'
>     - 'hello'
>     - 'hey'
>     - 'rip'
>     - 'lol'
>     - 'xD'
>     - '^hello \w+$'
>     - '^hey \w+$'
>     - '^hi \w+$'
>     - 'welcome back'
> ```
> 
> attempted typing "wb" in chat after another player and...
> ![download](https://user-images.githubusercontent.com/3322491/125208014-07c3ae80-e25e-11eb-902a-64364b5b911a.png)

Hey!
Could you please update to the latest version of the plugin & try again?

**Comment by mrcoffee1026** [comment]
same problem.  Note: only happens if 2 different people say the word.

**Comment by ElBananaa** [comment]
> same problem. Note: only happens if 2 different people say the word.

Oh I see, is the parrot feature enabled?
If so, try to turn it off.

**Comment by mrcoffee1026** [comment]
Yes that was the problem.  I duplicated my whitelist and placed it on the parrot feature as well now all is right with the world, thanks!
