### ISSUE TITLE
Regional Range + Commands for Quit & Join Messages [Suggestion]

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl#1149]
**Regional Range**
The range of the channels allows a 'region' variable that only allows the channel range to be in the region. So if they aren't in the region they cannot see the messages from that specified channel.

**Ingame Commands for creating leave + join messages**
Allow an in-game command to set the leave and join message with a specific permission so we can implement a way for players to donate for custom leave + join messages (be nice :D)

Also wanna say all the new updates have been amazing keep up the amazing work!

**Comment by kangarko** [comment]
Thanks for your suggestions! However right now we're pretty busy with recording our training programs and are not looking into expanding on this features for the time being.
