### ISSUE TITLE
custom text files - ChatControl 

### ISSUE THREAD

**Issue by DeusNinja** [kangarko/ChatControl#115]
I was thinking that with how limited essentials custom.txt is, it would be quite useful to have a similar feature in ChatControl, where you can create as many custom text files as you'd like, with permission nodes to be able to use them. If each file is separate, you could use chapters instead of having to have the next page be a different chapter within essentials custom.txt. Not sure if I've properly articulated myself, but that's the best I can come up with. perhaps an example:

**a custom text file for new players:**
/newbie - this will display the first chapter of the custom text, which has a table of contents with all the other chapters.
/newbie claim - guide on how to claim.
/newbie build - a guide explaining where you can go to build
/newbie events - an explanation of server events.

currently with essentials custom text I've only been able to use the single custom.txt file so any of my custom text have alias such as
/customtext newbie ~ /newbie
and cannot create aliases for any sub chapters for those like in the example above.

**summary:** 
The main differance between this idea and essentials custom text, would be the permissions, where a player would need chatcontrol.customtext.[file name here] to be able to pull that file.
As well as the chapters working for each custom .txt that is added without needing furhter permissions. 

I'm not sure if this is a feature you'd like to add, I just feel as though this would be a useful addition to the massive list of features for CC.

**Comment by kangarko** [comment]
You've already posted in forums, besides this is a section for the free version.
