### ISSUE TITLE
Anti Caps + a couple suggestions

### ISSUE THREAD

**Issue by UnusualToast** [kangarko/ChatControl#115]
Is there a way to set the anticaps to change "SOMETHING BLAH" to "something blah", instead of "Something blah"? You know, without the first letter being capitalized.

Also, my EssentialsChat group tags don't show in chat. It's set as " Message_Format: '%pl_prefix%player: %message' ". Please help. Should show as "[S][Trusted] Nickname: message", but it only shows "[S]Nickname: message". ([S] from Multiverse, [Trusted] from Essentials.)

Suggestion: I'd like to set a minimum # of players for Delay_Between_Messages to be active. Is there a way to do that? I used ChatLimiter for that, but seems like ChatControl overrides it.

Thanks for the amazing plugin!

**Comment by kangarko** [comment]
>Is there a way to set the anticaps to change "SOMETHING BLAH" to "something blah", instead of >"Something blah"? You know, without the first letter being capitalized.
No it is not possible to have this separately. If you have Grammar.Insert_Dot and Grammar.Capitalise enabled than the message is going to be edited appropriately after being lowered by the anti-caps filter.

 >Also, my EssentialsChat group tags don't show in chat.
Strange issue, I am relying on Vault and getting the prefix from there. Can you run /vault-info and tell me what is says?

> I'd like to set a minimum # of players for Delay_Between_Messages to be active.
Currently, you can only disable almost all checks (including rules) by editing Minimum_Players_To_Enable_Checks. I know this is not the best way and thus I am wanting to improve it later.

Thank you for using this plugin and I wish you the best of service :)

**Comment by UnusualToast** [comment]
[Without Vault](http://puu.sh/hQHP7.png) and [with Vault](http://puu.sh/hQI2y.png). I'm not using Multiverse in these situations, but I'll keep testing a couple stuff.

Using [this](http://dev.bukkit.org/bukkit-plugins/vault/files/50-vault-1-5-3/) Vault version.

**Comment by kangarko** [comment]
What does [S] means? If you have prefixchat enabled in your multiverse config.yml, it is interfering with chatcontrol.

And what is [Trusted]? Is it group from, f. example permissionsEx?

**Comment by UnusualToast** [comment]
These might explain a bit more: [With ChatControl](http://puu.sh/hQIyE.png) and [without it](http://puu.sh/hQIDr.png).

Yes, I do have prefixchat enabled in Multiverse.

**Comment by kangarko** [comment]
Please try disabling prefixchat and using %world variable in chatcontrol's formatter instead.

**Comment by UnusualToast** [comment]
Same behaviour? [ChatControl and Multiverse](http://puu.sh/hQJ78.png)

**Comment by kangarko** [comment]
Really strange, just tested and it works fine for me (chatcontrol's %world).
Try shutdown the server and ensure the prefixchat is really false, because multiverse restore the variable on shutdown.

**Comment by UnusualToast** [comment]
Where are you setting the prefixes? (Please see my edits above)

**Comment by kangarko** [comment]
oh, EssentialsChat is overriding the ChatControl. You need to disable either EssentialsChat or Chatcontrol's formatter.

**Comment by UnusualToast** [comment]
Oh, I see it now. Vault does not grab the EssentialsChat formatting because it is more than a simple group tag. I was thinking that Essentials would hook into %pl_prefix. My bad. Please remove the [bug] label :P

Also, could you please confirm this?

>If you have Grammar.Insert_Dot and Grammar.Capitalise enabled than the message is going to be edited appropriately after being lowered by the anti-caps filter.

I have them both disabled, and Anticaps still capitalizes the first letter. Is that intended?

**Comment by kangarko** [comment]
Yes it does capitalizes it.

**Comment by UnusualToast** [comment]
So what did you mean with

>No it is not possible to have this separately.

I'd like to turn that off, so anticaps turns "ANTICAPS" into "anticaps" and not "Anticaps". Grammar.Capitalise is disabled. Is that a bug, or intended behaviour?

Anyway, thank you for your help. Please keep up the good work! :D

**Comment by kangarko** [comment]
I have forgotten this, sry. I will look into it later.
