### ISSUE TITLE
1.17: Listener Priorities (CHC-Red and BM)

### ISSUE THREAD

**Issue by toxinyx** [kangarko/ChatControl#1150]
I've been trying for the last few days to figure this and I can't. I've tried a few combos and I just... can't.

Does anyone know what priorities CHC-Red and BM need to be so that this doesnt happen?
![2021-07-12_15 34 53](https://user-images.githubusercontent.com/86858026/125306044-c3501580-e326-11eb-91fb-80735feccada.png)
I've tried setting CHC-Red to HIGH and BM on normal but it doesn't work.
If anyone knows, I'd appreciate it

Minecraft Version: 1.17.0
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> I've been trying for the last few days to figure this and I can't. I've tried a few combos and I just... can't.
> 
> Does anyone know what priorities CHC-Red and BM need to be so that this doesnt happen?
> ![2021-07-12_15 34 53](https://user-images.githubusercontent.com/86858026/125306044-c3501580-e326-11eb-91fb-80735feccada.png)
> I've tried setting CHC-Red to HIGH and BM on normal but it doesn't work.
> If anyone knows, I'd appreciate it
> 
> Minecraft Version: 1.17.0
> MySQL: false
> BungeeCord: false

Hey!
You need to restart your server in order to apply changes made to the listener priority for the plugin.
Also, since you want BM to overtake CHC-Red, I think you should try to give BM a higher priority than CHC-Red.
I'd suggest looking at the wiki page regarding punishment plugins, and trying to play with all the different listener priorities to find a config that will suit you.

**Comment by toxinyx** [comment]
So I switched punishment plugins (because we ended up buying one) and it doesn't happen anymore.
But the same chat bypass still happens when things like message_delay is added to a channel. I'm really confused.

**Comment by ElBananaa** [comment]
> So I switched punishment plugins (because we ended up buying one) and it doesn't happen anymore.
> But the same chat bypass still happens when things like message_delay is added to a channel. I'm really confused.

Hey!
I'm glad to ear that you fixed your issue.
I'd suggest opening another issue regarding the bypass thing since, I guess, this isn't supposed to happen.
