### ISSUE TITLE
1.17.1: LiteBans Integration with ChatControl

### ISSUE THREAD

**Issue by CoutovyLp** [kangarko/ChatControl#1151]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false but I have BungeeCord server, but I haven´t set it on true
Debug: https://ufile.io/vtsn5jw5

Hello. I bought LiteBans, but it looks that, the warnings etc. don´t work with ChatCotrol. In game, when I use some command from LiteBans it´s not doing nothing, but if I do it from console it works.. It sends the message. How can I fix it or it is LiteBans bug?

**Comment by ElBananaa** [comment]
Hey!
You need to play with the Listener Priority in Chatcontrol's settings file.
Here's a link to the wiki page regarding this : https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities#punishment-plugins-for-example-litebans

You may also want to disable some features like the mute system so Litebans' mute system could work properly.

**Comment by kangarko** [comment]
Thanks to Banana for explaining this!
