### ISSUE TITLE
1.17: Command Cooldown

### ISSUE THREAD

**Issue by toxinyx** [kangarko/ChatControl#1152]
I have all of the command delays and stuff set to 0, to disable them, but the commands still take 3 seconds to allow. Some commands are permanently stuck at 3 seconds as well so you can never do them either. 

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6812519/debug.zip)

Minecraft Version: 1.17.0
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey!
Sorry for the delay.
I'm unable to reproduce your issue under a fresh setup. Could you please provide us more informations? (like the commands you're trying to use etc)

**Comment by toxinyx** [comment]
It’s every command that has a timer. Our /near alias (which is an alias for /p near,) is stuck on the permanent 3 second delay if you’re not opped. 

The least I can reduce it down to is 3 seconds (that’s when I set it in the config as “0”) but it doesn’t get disabled.

**Comment by kangarko** [comment]
Can you try removing everything in rules/command.rs file and keeping the file empty? Or it may be another plugin causing this.

**Comment by toxinyx** [comment]
rules/command.rs was emptied and still produces the same result. I assumed it was CHC-Red since the cooldown error/message has the [x] next to it, which only CHC-Red has (installed on my server.)

**Comment by toxinyx** [comment]
Okay so I figured out the issue. I overlooked the 'Triggers' section in the config. My bad, apologies
