### ISSUE TITLE
1.12.2 [X] Remove Button is not working

### ISSUE THREAD

**Issue by VyperzDev** [kangarko/ChatControl#1153]
Minecraft Version: 1.12.2
MySQL: true
BungeeCord: true
Java: 11

Hello, I've noticed when I try to remove messages with the [X] button. it no longer works. I have no clue why.

https://gyazo.com/80231f560223355ab1b7b0da24f7dee1

There are no errors in the console at all.

**Comment by ElBananaa** [comment]
Hey!
Sorry for the delay.
This feature requires ProtocolLib. Are you using the latest version of the plugin compatible with your current server version?

**Comment by VyperzDev** [comment]
We are using the Latest ProtocolLib and Chatcontrol Red

**Comment by VyperzDev** [comment]
[error.log](https://github.com/kangarko/ChatControl-Red/files/6835758/error.log)

**Comment by ElBananaa** [comment]
Hey!
Thanks for the log file.
So, apparently, there's something wrong with your setup.
As you can see, you always get an error like this one : 
```log
Failed to save spy-mail.yml
FileNotFoundException plugins/ChatControlRed/formats/spy-mail.yml (Permission denied)
```
It looks like the plugin can't browse/read/write any files, causing the issue, so in case your server is hosted using a VPS or a Dedicated Server, I think you have an issue with your file permissions, I'd suggest taking a look at them.
In case you're using a mutualized host, I'd suggest making a backup of the entire plugin, then making a fresh install. If it doesn't work, try to reach your host support.

**Comment by VyperzDev** [comment]
Okay, but that shouldn't effect why the x button isn't working

**Comment by ElBananaa** [comment]
> Okay, but that shouldn't effect why the x button isn't working

I'm unable to reproduce your issue on my side with a fresh install, so I guess it might be a reason.
I can't help you if you don't want to give a shot to the things I suggested above...

**Comment by ElBananaa** [comment]
Alright, I just removed my previous message, since after running deeper tests, I was finally able to reproduce the issue.
I don't really know how/why it only happens now, but it does.
This was tested on a fresh install under the latest version of paper 1.12.2, ProtocolLib v4.7.0, Vault & Chc-red v10.5.0.

Let's wait for @kangarko to take a look at this issue.
In the meantime, i'd still suggest fixing your other issue since this can lead to other problems.

**Comment by kangarko** [comment]
Thanks Banana for testing, I will come back to this tomorrow early!

**Comment by kangarko** [comment]
Fixed.
