### ISSUE TITLE
Pre-purchase questions

### ISSUE THREAD

**Issue by msmanui** [kangarko/ChatControl#1155]
Hi there. Im interesting in purchasing ChatControl-Red. But i would like to know if i can enable the chat across some selected servers. For example between ONLY lobbies to share the chat. 

1. ¿What that work?
2. Would the command like /msg Auto-Tab-Complete with the player name even his in another server?
3. Would any placeholder api of the list, would work across server? the other player would see all correclty?

**Comment by ElBananaa** [comment]
> Hi there. Im interesting in purchasing ChatControl-Red. But i would like to know if i can enable the chat across some selected servers. For example between ONLY lobbies to share the chat.
> 
> 1. ¿What that work?
> 2. Would the command like /msg Auto-Tab-Complete with the player name even his in another server?
> 3. Would any placeholder api of the list, would work across server? the other player would see all correclty?

Hey,
- Yes the plugin supports cross-server chat. You can also create multiple cross-server chats for diferent or even the same servers. However, I'd like to warn you now : The plugin doesn't support Velocity **yet**.

- I'm not sure about it, but if i'm not wrong, the tab completion should work cross server for private messages.

- Most PAPI placeholders are working with the plugin, however, some "complicated" placeholders such as placeholders with multiple "variables" (like `%parseother_{username}_{placeholder_without_percent_signs}%` may not work (properly). The plugin also has its own placeholders. You can find more informations about them on this page : https://github.com/kangarko/ChatControl-Red/wiki/Variables

**Comment by msmanui** [comment]
> > Hi there. Im interesting in purchasing ChatControl-Red. But i would like to know if i can enable the chat across some selected servers. For example between ONLY lobbies to share the chat.
> > 
> > 1. ¿What that work?
> > 2. Would the command like /msg Auto-Tab-Complete with the player name even his in another server?
> > 3. Would any placeholder api of the list, would work across server? the other player would see all correclty?
> 
> Hey,
> 
> * Yes the plugin supports cross-server chat. You can also create multiple cross-server chats for diferent or even the same servers. However, I'd like to warn you now : The plugin doesn't support Velocity **yet**.
> * I'm not sure about it, but if i'm not wrong, the tab completion should work cross server for private messages.
> * Most PAPI placeholders are working with the plugin, however, some "complicated" placeholders such as placeholders with multiple "variables" (like `%parseother_{username}_{placeholder_without_percent_signs}%` may not work (properly). The plugin also has its own placeholders. You can find more informations about them on this page : https://github.com/kangarko/ChatControl-Red/wiki/Variables

Hi there! Thanks for your reply.

1. ¿Can you confirm if ChatControl Red has tab completition across server for private mssages?
2. The placeholder i would need is one from LuckPerms and the other DeluxeTags (%deluxetags_tag%). 

I need confirmation that all i ask is working correctly. Thanks!

**Comment by ElBananaa** [comment]
> > > Hi there. Im interesting in purchasing ChatControl-Red. But i would like to know if i can enable the chat across some selected servers. For example between ONLY lobbies to share the chat.
> > > 
> > > 1. ¿What that work?
> > > 2. Would the command like /msg Auto-Tab-Complete with the player name even his in another server?
> > > 3. Would any placeholder api of the list, would work across server? the other player would see all correclty?
> > 
> > 
> > Hey,
> > 
> > * Yes the plugin supports cross-server chat. You can also create multiple cross-server chats for diferent or even the same servers. However, I'd like to warn you now : The plugin doesn't support Velocity **yet**.
> > * I'm not sure about it, but if i'm not wrong, the tab completion should work cross server for private messages.
> > * Most PAPI placeholders are working with the plugin, however, some "complicated" placeholders such as placeholders with multiple "variables" (like `%parseother_{username}_{placeholder_without_percent_signs}%` may not work (properly). The plugin also has its own placeholders. You can find more informations about them on this page : https://github.com/kangarko/ChatControl-Red/wiki/Variables
> 
> Hi there! Thanks for your reply.
> 
> 1. ¿Can you confirm if ChatControl Red has tab completition across server for private mssages?
> 2. The placeholder i would need is one from LuckPerms and the other DeluxeTags (%deluxetags_tag%).
> 
> I need confirmation that all i ask is working correctly. Thanks!

Regarding the placeholders, I can guarantee you that these will work. I'm using both LuckPerms and DeluxeTags with the plugin on my own server and don't have any issues.

Regarding tab completion, I took a look at the wiki, and yes, as said on there, tab completion is supported for nicknames. Here's a link to the wiki if you want more infos : https://github.com/kangarko/ChatControl-Red/wiki/BungeeCord#step-4-restart

**Comment by kangarko** [comment]
Thanks Banana for catching up! Closing now, if you have any more questions feel free to post them below!
