### ISSUE TITLE
1.17.1: QUESTION: spy placeholders

### ISSUE THREAD

**Issue by DaveDevil** [kangarko/ChatControl#1156]
Hello! I'm trying to figure out how to use this placeholder:
{chatcontrolred_player_is_spying_<channel>}

it seems that it's working perfectly when i use a chat channel, but I'm looking for something that works even in private_messages, anvil, book, commands spy.

Thanks for the support!

**Comment by kangarko** [comment]
Sorry this is unsupported outside of a normal chat message.
