### ISSUE TITLE
1.16.5: Timed Message link 

### ISSUE THREAD

**Issue by WolverStones** [kangarko/ChatControl#1157]
I have a question, I have a link in the format discord.northville.cz and for example with cmi I can make a link from it which can be clicked as if it had https:// it is possible in timed.rs for example with CMI it can be done like this <T> &fHere you will find all important information</T> <H> &7Click to open the link</H> <URL>https://wiki.northville.cz/</URL>
<T>&f about our server @ &b&nwiki.northville.cz</T> <H>&7Click to open link</H> <URL> https://wiki.northville.cz/</URL> https://www.zrips.net/cmi/custom-text/ 

My timed.rs file:
```# ---------------------------------------------------------------------------------
# Timed messages broadcaster. Uses the same syntax as files in rules/ folder but
# operators are slightly different. For documentation and a quick tutorial, see:
# https://github.com/kangarko/ChatControl-Red/wiki/messages
#
# They are read like a newspaper and each player only sees one message,
# that is the first one we can send to him. We select 1 message randomly from 
# "messages:" list.
# ---------------------------------------------------------------------------------

# You can run limited time offers and even make clickable links by referencing
# to a format from /formats in your message.
#group special
#expires 31 Dec 2021, 15:00
#then sound ENTITY_ARROW_HIT_PLAYER, 1.0, 0.1
#delay 6 seconds
#message:
#- special-offer

# This group will simply send messages everywhere.
#group global
#delay 1 second
#message:
#- Hey, {player}, did you know that we are running ChatControl?
#- Check out &ahttps://mineacademy.org/plugins

# This group will send messages only to the given worlds.
#group hardcore
#require sender world hardcore|hardcore_nether|hardcore_end
#message:
#- Grief is not permitted what-so-ever and every griefer will be banned.
#- Can you survive the night on {world} world?

# This group will only send messages to the creative world.
#group creative
#require sender world creative
#message:
#- Welcome on Creative world. Enjoy your gamemode :)
#- This is an example of multi-line.
#  Use it if the new '\ and n' character
#  is not working on your server.
#- This is another message, this time only on one line!
group imported-1
prefix 
delay 240 seconds
messages:
- &7
  &6                &lNorthVille Official Wiki
  &f       Najdeš tu všechny důležité informace 
  &f        o našem serveru @ &b&nwiki.northville.cz
  &7
- &7
  &f                      &lNorthVille
  &f     Prohlédni si store @ &b&nstore.northville.cz
  &7
- &7
  &2                    &lNorthVille Report
  &f   Pokud najdeš hráče který cheatuje, vulgárně
  &f  se vyjadřuje nebo porušuje pravidla serveru
  &f     použij příkaz &2/report <hráč> <důvod> &fpro 
  &f         nahlášení hráče online Staff členům.
  &7
- &7
  &c                   &lNorthVille Security
  &f         Máš pocit že někdo používá tvůj účet?
  &f       Můžeš si změnit své heslo pomocí příkazu
  &c  /changepassword <aktuální heslo> <nové heslo>
  &7
- &7
  &6           &lNorthVille Support Tickety
  &f   Potřebuješ poradit nebo pomoct, ale nikdo
  &f   ze Staff není online? Můžeš vytvořit ticket
  &f   na který odpovíme co nejrychleji, obvykle
  &f         do 24 hodin od založení ticketu.
  &7
  &d   &nsupport.northville.cz&7 - &b&ndiscord.northville.cz
  &7
- &7
  &a                         &lNorthVille
  &f      Pokud se chceš přepojit na jiný server,
  &f         nemusíš chodit na /hub, jediné co ti
  &f      stačí je napsat &a/server &fa přepojit se.
  &7
- &7
  &b                    &lNorthVille Discord
  &f      Připoj se na náš serverový Discord pro 
  &f     &ekomunikaci &fs ostatními hráči, čtení &eoznámení&f,
  &f   zapojení se do &eeventů (giveaways)&f, propojení
  &e     VIP &fa mnoho dalšího @ &b&ndiscord.northville.cz
  &7
- &7
  &4                &lNorthVille Rules
  &f     Je nutné dodržovat naše podmínky
  &f     a pravidla @ &c&nwiki.northville.cz/rules
  &7
```

**Comment by ElBananaa** [comment]
> I have a question, I have a link in the format discord.northville.cz and for example with cmi I can make a link from it which can be clicked as if it had https:// it is possible in timed.rs for example with CMI it can be done like this &fHere you will find all important information &7Click to open the link https://wiki.northville.cz/
> &f about our server @ &b&nwiki.northville.cz &7Click to open link https://wiki.northville.cz/ https://www.zrips.net/cmi/custom-text/
> 
> My timed.rs file:
> 
> ```
> # Timed messages broadcaster. Uses the same syntax as files in rules/ folder but
> # operators are slightly different. For documentation and a quick tutorial, see:
> # https://github.com/kangarko/ChatControl-Red/wiki/messages
> #
> # They are read like a newspaper and each player only sees one message,
> # that is the first one we can send to him. We select 1 message randomly from 
> # "messages:" list.
> # ---------------------------------------------------------------------------------
> 
> # You can run limited time offers and even make clickable links by referencing
> # to a format from /formats in your message.
> #group special
> #expires 31 Dec 2021, 15:00
> #then sound ENTITY_ARROW_HIT_PLAYER, 1.0, 0.1
> #delay 6 seconds
> #message:
> #- special-offer
> 
> # This group will simply send messages everywhere.
> #group global
> #delay 1 second
> #message:
> #- Hey, {player}, did you know that we are running ChatControl?
> #- Check out &ahttps://mineacademy.org/plugins
> 
> # This group will send messages only to the given worlds.
> #group hardcore
> #require sender world hardcore|hardcore_nether|hardcore_end
> #message:
> #- Grief is not permitted what-so-ever and every griefer will be banned.
> #- Can you survive the night on {world} world?
> 
> # This group will only send messages to the creative world.
> #group creative
> #require sender world creative
> #message:
> #- Welcome on Creative world. Enjoy your gamemode :)
> #- This is an example of multi-line.
> #  Use it if the new '\ and n' character
> #  is not working on your server.
> #- This is another message, this time only on one line!
> group imported-1
> prefix 
> delay 240 seconds
> messages:
> - &7
>   &6                &lNorthVille Official Wiki
>   &f       Najdeš tu všechny důležité informace 
>   &f        o našem serveru @ &b&nwiki.northville.cz
>   &7
> - &7
>   &f                      &lNorthVille
>   &f     Prohlédni si store @ &b&nstore.northville.cz
>   &7
> - &7
>   &2                    &lNorthVille Report
>   &f   Pokud najdeš hráče který cheatuje, vulgárně
>   &f  se vyjadřuje nebo porušuje pravidla serveru
>   &f     použij příkaz &2/report <hráč> <důvod> &fpro 
>   &f         nahlášení hráče online Staff členům.
>   &7
> - &7
>   &c                   &lNorthVille Security
>   &f         Máš pocit že někdo používá tvůj účet?
>   &f       Můžeš si změnit své heslo pomocí příkazu
>   &c  /changepassword <aktuální heslo> <nové heslo>
>   &7
> - &7
>   &6           &lNorthVille Support Tickety
>   &f   Potřebuješ poradit nebo pomoct, ale nikdo
>   &f   ze Staff není online? Můžeš vytvořit ticket
>   &f   na který odpovíme co nejrychleji, obvykle
>   &f         do 24 hodin od založení ticketu.
>   &7
>   &d   &nsupport.northville.cz&7 - &b&ndiscord.northville.cz
>   &7
> - &7
>   &a                         &lNorthVille
>   &f      Pokud se chceš přepojit na jiný server,
>   &f         nemusíš chodit na /hub, jediné co ti
>   &f      stačí je napsat &a/server &fa přepojit se.
>   &7
> - &7
>   &b                    &lNorthVille Discord
>   &f      Připoj se na náš serverový Discord pro 
>   &f     &ekomunikaci &fs ostatními hráči, čtení &eoznámení&f,
>   &f   zapojení se do &eeventů (giveaways)&f, propojení
>   &e     VIP &fa mnoho dalšího @ &b&ndiscord.northville.cz
>   &7
> - &7
>   &4                &lNorthVille Rules
>   &f     Je nutné dodržovat naše podmínky
>   &f     a pravidla @ &c&nwiki.northville.cz/rules
>   &7
> ```

Hey!
Yes you can include a link in your timed messages.
There's 2 ways of doing it.

- First way : Make a JSON message. You can find all informations about how to proceed on our wiki page : https://github.com/kangarko/ChatControl-Red/wiki/JSON

- Second way : Create a format (in `formats/`) which will be used in your timed message. You can find more informations about how it works on these pages : https://github.com/kangarko/ChatControl-Red/wiki/Messages & https://github.com/kangarko/ChatControl-Red/wiki/Formats

**Comment by WolverStones** [comment]
> > I have a question, I have a link in the format discord.northville.cz and for example with cmi I can make a link from it which can be clicked as if it had https:// it is possible in timed.rs for example with CMI it can be done like this &fHere you will find all important information &7Click to open the link https://wiki.northville.cz/
> > &f about our server @ &b&nwiki.northville.cz &7Click to open link https://wiki.northville.cz/ https://www.zrips.net/cmi/custom-text/
> > My timed.rs file:
> > ```
> > # Timed messages broadcaster. Uses the same syntax as files in rules/ folder but
> > # operators are slightly different. For documentation and a quick tutorial, see:
> > # https://github.com/kangarko/ChatControl-Red/wiki/messages
> > #
> > # They are read like a newspaper and each player only sees one message,
> > # that is the first one we can send to him. We select 1 message randomly from 
> > # "messages:" list.
> > # ---------------------------------------------------------------------------------
> > 
> > # You can run limited time offers and even make clickable links by referencing
> > # to a format from /formats in your message.
> > #group special
> > #expires 31 Dec 2021, 15:00
> > #then sound ENTITY_ARROW_HIT_PLAYER, 1.0, 0.1
> > #delay 6 seconds
> > #message:
> > #- special-offer
> > 
> > # This group will simply send messages everywhere.
> > #group global
> > #delay 1 second
> > #message:
> > #- Hey, {player}, did you know that we are running ChatControl?
> > #- Check out &ahttps://mineacademy.org/plugins
> > 
> > # This group will send messages only to the given worlds.
> > #group hardcore
> > #require sender world hardcore|hardcore_nether|hardcore_end
> > #message:
> > #- Grief is not permitted what-so-ever and every griefer will be banned.
> > #- Can you survive the night on {world} world?
> > 
> > # This group will only send messages to the creative world.
> > #group creative
> > #require sender world creative
> > #message:
> > #- Welcome on Creative world. Enjoy your gamemode :)
> > #- This is an example of multi-line.
> > #  Use it if the new '\ and n' character
> > #  is not working on your server.
> > #- This is another message, this time only on one line!
> > group imported-1
> > prefix 
> > delay 240 seconds
> > messages:
> > - &7
> >   &6                &lNorthVille Official Wiki
> >   &f       Najdeš tu všechny důležité informace 
> >   &f        o našem serveru @ &b&nwiki.northville.cz
> >   &7
> > - &7
> >   &f                      &lNorthVille
> >   &f     Prohlédni si store @ &b&nstore.northville.cz
> >   &7
> > - &7
> >   &2                    &lNorthVille Report
> >   &f   Pokud najdeš hráče který cheatuje, vulgárně
> >   &f  se vyjadřuje nebo porušuje pravidla serveru
> >   &f     použij příkaz &2/report <hráč> <důvod> &fpro 
> >   &f         nahlášení hráče online Staff členům.
> >   &7
> > - &7
> >   &c                   &lNorthVille Security
> >   &f         Máš pocit že někdo používá tvůj účet?
> >   &f       Můžeš si změnit své heslo pomocí příkazu
> >   &c  /changepassword <aktuální heslo> <nové heslo>
> >   &7
> > - &7
> >   &6           &lNorthVille Support Tickety
> >   &f   Potřebuješ poradit nebo pomoct, ale nikdo
> >   &f   ze Staff není online? Můžeš vytvořit ticket
> >   &f   na který odpovíme co nejrychleji, obvykle
> >   &f         do 24 hodin od založení ticketu.
> >   &7
> >   &d   &nsupport.northville.cz&7 - &b&ndiscord.northville.cz
> >   &7
> > - &7
> >   &a                         &lNorthVille
> >   &f      Pokud se chceš přepojit na jiný server,
> >   &f         nemusíš chodit na /hub, jediné co ti
> >   &f      stačí je napsat &a/server &fa přepojit se.
> >   &7
> > - &7
> >   &b                    &lNorthVille Discord
> >   &f      Připoj se na náš serverový Discord pro 
> >   &f     &ekomunikaci &fs ostatními hráči, čtení &eoznámení&f,
> >   &f   zapojení se do &eeventů (giveaways)&f, propojení
> >   &e     VIP &fa mnoho dalšího @ &b&ndiscord.northville.cz
> >   &7
> > - &7
> >   &4                &lNorthVille Rules
> >   &f     Je nutné dodržovat naše podmínky
> >   &f     a pravidla @ &c&nwiki.northville.cz/rules
> >   &7
> > ```
> 
> Hey!
> Yes you can include a link in your timed messages.
> There's 2 ways of doing it.
> 
> * First way : Make a JSON message. You can find all informations about how to proceed on our wiki page : https://github.com/kangarko/ChatControl-Red/wiki/JSON
> * Second way : Create a format (in `formats/`) which will be used in your timed message. You can find more informations about how it works on these pages : https://github.com/kangarko/ChatControl-Red/wiki/Messages & https://github.com/kangarko/ChatControl-Red/wiki/Formats

Thanks i use formats/ a work fine.
