### ISSUE TITLE
1.17.1:unable to message across platform

### ISSUE THREAD

**Issue by SecretarySami** [kangarko/ChatControl#1160]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Issue: Unable to message a player across platform despite them being online. When attempting to message a player even on the same mode as you it states that the player is not online. 
https://screenshots.skizzles.me/wAnA3/XOjULeqi03.mp4

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1
> MySQL: true
> BungeeCord: true
> 
> Issue: Unable to message a player across platform despite them being online. When attempting to message a player even on the same mode as you it states that the player is not online.
> https://screenshots.skizzles.me/wAnA3/XOjULeqi03.mp4

Hey!
Is your server running in online-mode or in offline mode? (I know bungee setups require the servers to be in offline mode, but you can still enabled online-mode on the proxy itself, that's what I'd like to know).
In `/plugins/ChatControlRed/mysql.yml`, try to set `UUID_Lookup:` to `false` then restart your servers and your proxy. Does it help with your issue?

**Comment by Skizzles** [comment]
Hello @ElBananaa 

We are running bungeecord in online mode, should we still set UUID_Lookup to false?

**Comment by ElBananaa** [comment]
> Hello @ElBananaa
> 
> We are running bungeecord in online mode, should we still set UUID_Lookup to false?

Hey,
I'd suggest giving it a shot yeah (don't forget to restart the servers and the proxy).
Let us know if it still happens after.

**Comment by DoogiePC** [comment]
I've done that and it still doesn't work. I've tried it on both settings

**Comment by Skizzles** [comment]
@ElBananaa This can be closed, I figured out that when 2 servers in a bungeecord network share the same name in server.properties then it causes this issue. Or if the name does not match the server the user is on.

Resolved by updating that value.

**Comment by ElBananaa** [comment]
> @ElBananaa This can be closed, I figured out that when 2 servers in a bungeecord network share the same name in server.properties then it causes this issue. Or if the name does not match the server the user is on.
> 
> Resolved by updating that value.

Alright, thanks for the info! 😃
@DoogiePC Could you try what skizzles suggested above if that's not already done?

**Comment by kangarko** [comment]
Thanks, I've added a warning to mineacademy.org/server-properties and settings.yml

Doogie if you're still facing issues after testing what Banana said? I remember you from the other ticket on the bug after changing Mojang's username, please check with the player if they've changed their username just to be safe: https://github.com/kangarko/ChatControl-Red/issues/309

Comment below and I'll reopen this
