### ISSUE TITLE
1.16.5: Automatic replacement of letters like čřžý

### ISSUE THREAD

**Issue by WolverStones** [kangarko/ChatControl#1161]
Hello, i need help I have set up a command for sending messages to the admin channel (admin chat) but I came across one problem in case I use characters such as `čřýž` in this command so they will be automatically overwritten to `crzye` which I don't want. How do I turn off this auto-rewrite? 

```
# -----------------------------------------------------------------------------------------------
# Create a /acsend command that sends messages to a channel.
# -----------------------------------------------------------------------------------------------

# Catch "/ac" command and send usage.
match ^\/ac$
dont verbose
then warn &cPopis: Odešle zprávu do staff chatu.
then warn &cPoužití: /acsend <zpráva>
then deny

# Catch "/ac <zpráva>" and redirect to the admin channel.
match ^(\/ac) (.*)
dont verbose
then command channel send admin $2
then deny
```

**Comment by TheIntolerant** [comment]
To turn this off, in ``settings.yml`` set ``Rules.Strip_Accents`` to ``false``
Just keep in mind, with this off, people can use accents to bypass the chat filter.

**Comment by ElBananaa** [comment]
Hey!
Thanks gone-incognito for answering them.
I'm closing this issue but feel free to keep commenting down below if you still need help.
