### ISSUE TITLE
1.8.8 : Remove channel switch message

### ISSUE THREAD

**Issue by huntingzap** [kangarko/ChatControl#1162]
Hello, I was wondering how do I remove the channel joining text? 
![1d020026ce9212f8daae224c979c7f92](https://user-images.githubusercontent.com/42100710/126265842-2dc2912f-2677-46e4-879d-3e7fffde350c.png)

I want to make it where by default everyone joins the global channel. This is working but every time someone new joins, it sends a message saying they join the global group. I just want to remove the message saying that they joined the global group when it's their first join. Any way to do this?

**Comment by TheIntolerant** [comment]
Hey, to remove this, go into this ``plugins/ChatControlRed/localization`` and set ``Join.Notification`` to none.
So it looks like ``Notification: none``

**Comment by ElBananaa** [comment]
Hey!
Thanks gone-incognito for answering them.
I'm closing this issue but feel free to keep commenting down below if you still need help.
