### ISSUE TITLE
1.17.1: Everyone has the discord prefix

### ISSUE THREAD

**Issue by CrispyDairy** [kangarko/ChatControl#1164]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Everyone ingame has the discord prefix, I don't know why. I'm using the default chat format

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1
> MySQL: false
> BungeeCord: false
> 
> Everyone ingame has the discord prefix, I don't know why. I'm using the default chat format

Hey,
Please provide us your `/chc debug` output file.

**Comment by CrispyDairy** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6857633/debug.zip)

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6857633/debug.zip)

Thanks.
As I said on your previous issue, install NashornPlus (https://mineacademy.org/nashorn/) and update the plugin to v10.5.0, and it'll fix the issue.

**Comment by CrispyDairy** [comment]
Ah sorry about that, thought it was a permission issue or something

**Comment by ElBananaa** [comment]
> Ah sorry about that, thought it was a permission issue or something

It's alright. May I close the issue? ^^

**Comment by CrispyDairy** [comment]
Yeap, just restarted the server and it works
