### ISSUE TITLE
1.16.4: Error spam

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#1166]
https://gist.github.com/MithrandirCraft/f35ad221c691f8c1f49558712fbfc756

This error shows up as spam as long as someone is online and chatcontrolred is loaded.

Minecraft Version: 1.16.4
Java 16
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> https://gist.github.com/MithrandirCraft/f35ad221c691f8c1f49558712fbfc756
> 
> This error shows up as spam as long as someone is online and chatcontrolred is loaded.
> 
> Minecraft Version: 1.16.4
> Java 16
> MySQL: true
> BungeeCord: true

Hey!
Please make sure you are using the latest version of the plugin and its dependencies, according to your server version (ProtocolLib, Vault, NashornPlus).
If this is the case, I'd suggest making a backup of your database, and regenerating it. I believe such issues were present in a pretty old version of the plugin, and also needed a plugin db reset to be fixed.

**Comment by kangarko** [comment]
Update BungeeControl Red and ChatControl Red. This is caused by inconsistently updated Bungee network.
