### ISSUE TITLE
1.17.1: Spy placeholders not working properly

### ISSUE THREAD

**Issue by DaveDevil** [kangarko/ChatControl#1167]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Having 4 channels, for example hub, server1, server2, server3

Do the command /spy toggle chat server1, it correctly activates the spy of the server1 channel. It lists that channel in /spy status too.

Check the placeholder status with:
/papi parse me %chatcontrolred_player_is_spying_channel_<channel name>%

it returns TRUE for all channels:

%chatcontrolred_player_is_spying_channel_server1%: true
%chatcontrolred_player_is_spying_channel_server2%: true
%chatcontrolred_player_is_spying_channel_server3%: true

even if that channel's spy is not active.

**Comment by kangarko** [comment]
Does it work if you type /spy list to refresh the data?

**Comment by DaveDevil** [comment]
Yes, /spy list is updating correctly listing only the one I activated. It seems to be only a placeholder problem.

P.s. is it also possible to have similar placeholders for book, anvil, private messages etc spy too?

**Comment by kangarko** [comment]
Unfortunately the placeholder is pulled without calling our update method, that is the reason. Thanks for letting me know.

This should work properly if mysql is disabled. On mysql servers I will try looking for an alternative solution but at present this stands as "wontfix"
