### ISSUE TITLE
1.17.1: How to disable joined channel message

### ISSUE THREAD

**Issue by CrispyDairy** [kangarko/ChatControl#1169]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

I'm probaply just being dumb, but I can't find an option, or permission anywhere to disable the "player has joined channel..." message when someone joins a channel. Is there one?

**Comment by kangarko** [comment]
Hi! Please see the localization file: https://github.com/kangarko/ChatControl-Red/wiki/Localization

Use the CTRL+F function to look for this message or its parts, should be under the key Channel.Join or Commands.Channel.Join.

Regards,
Matej
