### ISSUE TITLE
MyCommand plugin bug

### ISSUE THREAD

**Issue by xAphex** [kangarko/ChatControl#117]
Hello, my name is Gabriel, in the past 2 days i have been having this problem, and got annoyed of it, so basically this plugin called "MyCommand" allows you to create a custom command for a command, so for example you can make a /hub as an alias for /spawn, so when you do /hub it will run the command /spawn, the problem with this is that in "ChatControl" i configured the settings.yml to do 1 command every 2 seconds, so in "MyCommand" plugin it will launch the first command (/hub) but it will say **wait 2 more seconds before the next command** because it runs /spawn, so basically when you type /hub it will run 2 command at the same time!

I hope this problem/bug gets fixed as it's very annoying!

Thank you,
-Gabriel

**Comment by kangarko** [comment]
I see. If the plugin is using method player.chat() then there is very little I can do, because I cannot see the difference if it was the player or any plugin, unfortunately.
I will look in to it.

**Comment by xAphex** [comment]
@kangarko Ok, hope it get's fixed soon,
and good luck with your work!

**Comment by kangarko** [comment]
Sorry I don't see any solution here, please use commands.yml (which is built in bukkit by default) for adding command aliases. Documentation is at http://wiki.bukkit.org/Commands.yml
