### ISSUE TITLE
1.16.5: Debug console output in /list command (v10.5.0)

### ISSUE THREAD

**Issue by addstar** [kangarko/ChatControl#1170]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Only a minor spam issue, but in 10.5.0 there was a debug statement introduced (with a typo ;) every time someone uses the `/list` command:
```
4:48:40 [INFO]: add5tar issued server command: /list
15:06:50 [INFO]: Sneding: {....
```

I checked the source and it's in `listener/BungeeListener.java`:
```
for (SerializedMap playersPart : ListPlayers.compilePlayers(senderSeeVanished, prefix)) {
  System.out.println("Sneding: " + playersPart);

  BungeeUtil.tellBungee((BungeeAction)Bungee.BungeePacket.LIST_PLAYERS_RESPONSE, new Object[] { requesterUUID, playersPart });
}
```

Obviously doesn't cause any issues except spamming console, but figured it should be reported :slightly_smiling_face:

**Comment by kangarko** [comment]
Thanks, fixed!
