### ISSUE TITLE
killer_item problem

### ISSUE THREAD

**Issue by ttt0** [kangarko/ChatControl#1173]
https://prnt.sc/1eun7xs When someone kills someone, it doesn't say what they killed in the chat.

**Comment by ElBananaa** [comment]
Hey!
Which version of the plugin are you using?
Is there any error?
What does the message in the screenshot means?
What's your server version?

**Comment by ttt0** [comment]
ChatControl-Red-10.5.0
no errors
1.17.1 

what I mean is that when a player kills someone, it doesn't write what he killed with it.

**Comment by ElBananaa** [comment]
> ChatControl-Red-10.5.0
> no errors
> 1.17.1
> 
> what I mean is that when a player kills someone, it doesn't write what he killed with it.

Alright, could you please provide us your `/chc debug` file?

**Comment by ttt0** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6871270/debug.zip)

**Comment by ElBananaa** [comment]
Thanks.
It looks like you haven't correctly setup the plugin.
As said in your error.log file, you need to define a correct `server-name` in your server.properties. (It doesn't support spaces/special characters/accents) : 
```
More Information: 
Detected getServerName call, please configure your 'server-name' in server.properties according to mineacademy.org/server-properties
FoException Report: Detected getServerName call, please configure your 'server-name' in server.properties according to mineacademy.org/server-properties
	 at org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.chatcontrol.lib.remain.Remain.getServerName(Remain.java:2320)
	 at org.mineacademy.chatcontrol.SyncedCache$Builder.collect(SyncedCache.java:358)
	 at org.mineacademy.chatcontrol.SyncedCache$Builder.toLine(SyncedCache.java:396)
	 at org.mineacademy.chatcontrol.model.Bungee$SyncTask.run(Bungee.java:57)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
```

You also need to install NashornPlus (https://mineacademy.org/nashorn/) so the plugin could work properly (It's needed since you use a version of java above java 15.)

Once everything said above is done, try again, and it should work properly.

**Comment by ttt0** [comment]
Thank you for the help man I appreciate it
