### ISSUE TITLE
1.16.5: accent removed with emojis

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1175]
Debug :
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6872685/debug.zip)

Minecraft Version: 1.16.5 (Airplane, but I can reproduce the bug on paper !!)
Plugin version : 10.5.1
Server langage : french
MySQL: false
BungeeCord: false

The emoji (for example replace :) with an emoji) remove accent in the whole sentences (such as é è à ù )
![Screenshot_5267](https://user-images.githubusercontent.com/31826333/126874021-e73aafdb-f2c6-4994-a92c-48d583629de8.png)

Another example : when the plugin "correct you" because you 'flood' it will remove accent from your message
![Screenshot_5268](https://user-images.githubusercontent.com/31826333/126874052-0c4f6d88-3c94-470a-ad72-586a85eac797.png)

**Comment by ElBananaa** [comment]
Issue solved in PM with the user.
For people encountering similar issues, set `Strip_Accents:` to `false` in your `settings.yml`.
