### ISSUE TITLE
Have the {recipient} placeholder be compatible with other plugin placeholders

### ISSUE THREAD

**Issue by starwarsfreak219** [kangarko/ChatControl#1176]
So some explanation on this feature. I know that there is the {recipient_prefix} placeholder, but would like to have other recipient placeholders like {recipient_deluxetags_tag} (As an example, it will show the recipients currently equipped tag from the plugin DeluxeTags). It would also be nice to see other recipient attributes like economy, tokens (if using a tokens plugin like TokenEnchant), etc.

1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)

     This would benefit others by allowing them to show recipient information like economy, tags, and other attributes that may be useful to show in a private message. I use DeluxeTags as an example as I use DeluxeTags as a way to show what donator rank a player is, along with some staff ranks.

2. What would happen if we won't implement this feature? How's your server being affected?

     While not implementing this wouldn't be a deal breaker, and wouldn't affect much, it would make it nice to show things that players may have purchased when they message other players (like tags from the plugin DeluxeTags), or even show information when hovering over a PM (like balance, tokens, world information, etc).

**Comment by starwarsfreak219** [comment]
Forgot to mention version information:

I am currently using the plugin on a test server running 1.17.1 along with the ChatControl-Red version 10.5.1. PlaceholderAPI is also the latest version (2.10.10)

**Comment by ElBananaa** [comment]
Hey!
I don't know if this is the right place for suggesting these placeholders. You should probably see with deluxetags/TokenEnchant developers for these placeholders

**Comment by kangarko** [comment]
Thanks for your suggestion, however we do not support third party private messaging plugins in the moment.

**Comment by starwarsfreak219** [comment]
> Thanks for your suggestion, however we do not support third party private messaging plugins in the moment.

I am using ChatControl for private messaging. :/

**Comment by ElBananaa** [comment]
> > Thanks for your suggestion, however we do not support third party private messaging plugins in the moment.
> 
> I am using ChatControl for private messaging. :/

It looks like a misunderstanding on Kangarko's side. I sent him a PM about it, no worries ^^
EDIT: Reopening this suggestion

**Comment by kangarko** [comment]
Sorry about that! Put this onto my roadmap for next week, I will see if it is technically feasible.

**Comment by kangarko** [comment]
I reviewed the current system, it is technically challenging to implement since we run all variable parsing only for one player and I do not want to create a mess. Not right now, but I may return to it in the future when rewriting full code.
