### ISSUE TITLE
Paper 1.16.5, CHR 10.4.9: How make a new line

### ISSUE THREAD

**Issue by Korinocho** [kangarko/ChatControl#1177]
Hi! I would like to know how to make a new line when executing some command like /chc announce chat.
Tried using \n but i will just print it. Maybe there is something like <newline>?

Thanks!

**Comment by kangarko** [comment]
Hey, you can just use the | delimiter instead.

**Comment by Korinocho** [comment]
Thank!! Btw, can i center new lines? Tried something like this 
![image](https://user-images.githubusercontent.com/21372197/126900970-4dc87b6a-f67d-496e-99d9-e63159f731de.png)
 but it wont work like desired. I already centered the line in the messages_en file like this:
![image](https://user-images.githubusercontent.com/21372197/126900941-8da97d81-3042-4fa2-ac3c-f11ccfc9e923.png)

**Comment by ElBananaa** [comment]
> Thank!! Btw, can i center new lines? Tried something like this
> ![image](https://user-images.githubusercontent.com/21372197/126900970-4dc87b6a-f67d-496e-99d9-e63159f731de.png)
> but it wont work like desired. I already centered the line in the messages_en file like this:
> ![image](https://user-images.githubusercontent.com/21372197/126900941-8da97d81-3042-4fa2-ac3c-f11ccfc9e923.png)

Hi,
I believe the `<center>` argument doesn't work everywhere, and I think this is intended. However, I'd suggest waiting for an answer from @kangarko

**Comment by bchewy** [comment]
How does one use the | delimiter?

Message: '|'
Message:
 - '|'

Message: |
Message:
- |

None of the above worked for me when trying to create a new line

**Comment by Korinocho** [comment]
It works like this:
"Line 1 | Line 2"
will look like this:
"Line 1
Line 2"

**Comment by bchewy** [comment]
got it to work, thanks!
