### ISSUE TITLE
Advertisement Blocker Question

### ISSUE THREAD

**Issue by TheMattVid** [kangarko/ChatControl#118]
This plugin is wonderful for blocking advertisers, but I have one problem not related to this plugin, and I need your advice.

I don't know if it's from a different plugin or integrated into bukkit/spigot, but on almost every server, dots are stripped from IP addresses. This used to be fine for me, but now it's bad. If the dot wasn't stripped, the message would be blocked altogether by ChatControl, but instead, the message still gets sent without the dot. How do I prevent the dot from being removed so ChatControl can do its job?

**Comment by kangarko** [comment]
>When url is entered in chat, all the dots are replaced by spaces (e.g. www.google.com -> www google >com)
>- This change is not coming from ChatControl. Essentials is known to do that, try adding your players >  permission essentials.chat.url and essentials.msg.url for private messages.
