### ISSUE TITLE
Please do not repeat the same (or similar) command.

### ISSUE THREAD

**Issue by dentoffe** [kangarko/ChatControl#118]
I keep getting this if a player types /kit and then 3 secconds later again.
This is my config http://pastebin.com/Av9mh2qL
I clearly disabled it by setting the value to 100 didn't I? Is there something else I'm missing? Thanks

**Comment by kangarko** [comment]
Your **Anti_Spam.Commands.Similar_Percentage_Block** is still set to 80%. Set it to '100'.

For maximal convenience, we use separate config values for commands and messages. From what I can see, you´ve only disabled the latter one.
