### ISSUE TITLE
1.17.1 Join group sender_ Group

### ISSUE THREAD

**Issue by EiupNiow** [kangarko/ChatControl#1181]
Can you not only judge by permission in chat channel? It will be convenient to join a group to judge, because I don't know what happens. My default group gives xx.xx permission. My member is closed, but he will still have it, so he displays two titles

**Comment by ElBananaa** [comment]
> Can you not only judge by permission in chat channel? It will be convenient to join a group to judge, because I don't know what happens. My default group gives xx.xx permission. My member is closed, but he will still have it, so he displays two titles

Hey!
Sorry for the delay.
I'm not sure to understand, could you please explain your issue a bit further, and provide us informations about your server (Like version, are you using mysql? is it a single server or is it linked to other servers? Is ChatControlRed up to date? Are the dependencies up to date? etc...)

**Comment by EiupNiow** [comment]
My server version is 1.17.1. I don't use mysql. It's a single server

In version chatcontrol-red-10.5.0, I want you to add a function to the chat channel to judge the player group, such as send_ Group: VIP, which can be displayed by people in the VIP group

**Comment by ElBananaa** [comment]
> My server version is 1.17.1. I don't use mysql. It's a single server
> 
> In version chatcontrol-red-10.5.0, I want you to add a function to the chat channel to judge the player group, such as send_ Group: VIP, which can be displayed by people in the VIP group

Thanks for the infos.
Why don't you simply use the group placeholder in your format system, so it'll only show one group for each player, which is their main group?

**Comment by kangarko** [comment]
This is actually quite easy, you just create a separate format section showing the part of the format if the sender is in your group and then use the Sender_Permission setting the permission the sender must have for this format part to show.

You can see an example of this in formats/chat.rs, just search for "vip-prefix" in the default file.
