### ISSUE TITLE
1.17.1: Auto Join Worlds Channel

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#1182]
I would like my players to auto join the channel of the world they are in when they join the world, how do i do this, I've checked the Wiki but can not find the answer.

so when they join world a, they join world channel a and when they leave to join world b, they leave channel a and join world channel b

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: false
Multiverse: true

**Comment by ElBananaa** [comment]
Hey!
There's an example of how to do so in the `rules/chat.rs` file:
```
# -----------------------------------------------------------------------------------------------
# An example of automatically switching channels depending on player's world when he chats.
# You may also want to go into your localization file and hide these messages by setting 
# Channels.Join sections to '' for keys "Success", "Leave_Reading" to prevent message spam
# when channels are automatically switched.
# -----------------------------------------------------------------------------------------------

# Switches channel for user if not in child-spawn channel while in a spawn world
#match (.*)
#require world childspawn
#ignore channel child-spawn
#then console channel join child-spawn write {player}|channel sendas {player} child-spawn $0
#then deny

# Switches channel for user if not in child-survival channel while in a survival world
#match (.*)
#require world childsurvival|childsurvival_nether|childsurvival_the_end
#ignore channel child-survival
#then console channel join child-survival write {player}|channel sendas {player} child-survival $0
#then deny

# Switches channel for user if not in child-creative channel while in a plot world
#match (.*)
#require world childplot
#ignore channel child-creative
#then console channel join child-creative write {player}|channel sendas {player} child-creative $0
#then deny
```

**Comment by 00Hrtz** [comment]
> 
> 
> Hey!
> There's an example of how to do so in the `rules/chat.rs` file:
> 
> ```
> # -----------------------------------------------------------------------------------------------
> # An example of automatically switching channels depending on player's world when he chats.
> # You may also want to go into your localization file and hide these messages by setting 
> # Channels.Join sections to '' for keys "Success", "Leave_Reading" to prevent message spam
> # when channels are automatically switched.
> # -----------------------------------------------------------------------------------------------
> 
> # Switches channel for user if not in child-spawn channel while in a spawn world
> #match (.*)
> #require world childspawn
> #ignore channel child-spawn
> #then console channel join child-spawn write {player}|channel sendas {player} child-spawn $0
> #then deny
> 
> # Switches channel for user if not in child-survival channel while in a survival world
> #match (.*)
> #require world childsurvival|childsurvival_nether|childsurvival_the_end
> #ignore channel child-survival
> #then console channel join child-survival write {player}|channel sendas {player} child-survival $0
> #then deny
> 
> # Switches channel for user if not in child-creative channel while in a plot world
> #match (.*)
> #require world childplot
> #ignore channel child-creative
> #then console channel join child-creative write {player}|channel sendas {player} child-creative $0
> #then deny
> ```

there's nothing in my chat.rs concerning auto channel change but, thank you for the extra information.

Where would i place these settings exactly and please can you explain what child means.

**Comment by ElBananaa** [comment]
> > Hey!
> > There's an example of how to do so in the `rules/chat.rs` file:
> > ```
> > # -----------------------------------------------------------------------------------------------
> > # An example of automatically switching channels depending on player's world when he chats.
> > # You may also want to go into your localization file and hide these messages by setting 
> > # Channels.Join sections to '' for keys "Success", "Leave_Reading" to prevent message spam
> > # when channels are automatically switched.
> > # -----------------------------------------------------------------------------------------------
> > 
> > # Switches channel for user if not in child-spawn channel while in a spawn world
> > #match (.*)
> > #require world childspawn
> > #ignore channel child-spawn
> > #then console channel join child-spawn write {player}|channel sendas {player} child-spawn $0
> > #then deny
> > 
> > # Switches channel for user if not in child-survival channel while in a survival world
> > #match (.*)
> > #require world childsurvival|childsurvival_nether|childsurvival_the_end
> > #ignore channel child-survival
> > #then console channel join child-survival write {player}|channel sendas {player} child-survival $0
> > #then deny
> > 
> > # Switches channel for user if not in child-creative channel while in a plot world
> > #match (.*)
> > #require world childplot
> > #ignore channel child-creative
> > #then console channel join child-creative write {player}|channel sendas {player} child-creative $0
> > #then deny
> > ```
> 
> there's nothing in my chat.rs concerning auto channel change but, thank you for the extra information.
> 
> Where would i place these settings exactly and please can you explain what child means.

Hey!
That's weird, I took this part from the original file itself. I might be missing if you're updating from an old version of the plugin I guess.
You can place it wherever you want. In the default file, it's located near the top of the file, right under the `Forwarding messages to other channels.` section.
Child doesn't mean anything here, it's only a channel name used for the example. Let's say your world is named SuperWorld and your channel is named SuperChanel, it would look like this:

```rs
# Switches channel for user if not in SuperChanel channel while in the SuperWorld world
match (.*)
require world SuperWorld
ignore channel SuperChanel 
then console channel join SuperChanel write {player}|channel sendas {player} SuperChanel $0
then deny
```

**Comment by 00Hrtz** [comment]
> 
> 
> > > Hey!
> > > There's an example of how to do so in the `rules/chat.rs` file:
> > > ```
> > > # -----------------------------------------------------------------------------------------------
> > > # An example of automatically switching channels depending on player's world when he chats.
> > > # You may also want to go into your localization file and hide these messages by setting 
> > > # Channels.Join sections to '' for keys "Success", "Leave_Reading" to prevent message spam
> > > # when channels are automatically switched.
> > > # -----------------------------------------------------------------------------------------------
> > > 
> > > # Switches channel for user if not in child-spawn channel while in a spawn world
> > > #match (.*)
> > > #require world childspawn
> > > #ignore channel child-spawn
> > > #then console channel join child-spawn write {player}|channel sendas {player} child-spawn $0
> > > #then deny
> > > 
> > > # Switches channel for user if not in child-survival channel while in a survival world
> > > #match (.*)
> > > #require world childsurvival|childsurvival_nether|childsurvival_the_end
> > > #ignore channel child-survival
> > > #then console channel join child-survival write {player}|channel sendas {player} child-survival $0
> > > #then deny
> > > 
> > > # Switches channel for user if not in child-creative channel while in a plot world
> > > #match (.*)
> > > #require world childplot
> > > #ignore channel child-creative
> > > #then console channel join child-creative write {player}|channel sendas {player} child-creative $0
> > > #then deny
> > > ```
> > 
> > 
> > there's nothing in my chat.rs concerning auto channel change but, thank you for the extra information.
> > Where would i place these settings exactly and please can you explain what child means.
> 
> Hey!
> That's weird, I took this part from the original file itself. I might be missing if you're updating from an old version of the plugin I guess.
> You can place it wherever you want. In the default file, it's located near the top of the file, right under the `Forwarding messages to other channels.` section.
> Child doesn't mean anything here, it's only a channel name used for the example. Let's say your world is named SuperWorld and your channel is named SuperChanel, it would look like this:
> 
> ```rust
> # Switches channel for user if not in SuperChanel channel while in the SuperWorld world
> match (.*)
> require world SuperWorld
> ignore channel SuperChanel 
> then console channel join SuperChanel write {player}|channel sendas {player} SuperChanel $0
> then deny
> ```

Thank you so much for your help, i reinstalled the plugin to refresh all the files, thanks for making it easier to understand. Appreciated.

**Comment by SirCraftypants** [comment]
Hi, i have an issue now that i've set all the worlds channels to auto.

Now Global, Ranged and helpop channels don't work, i join the channels and type, but you stay in the channel of the world you're in, is there a solution to this?
