### ISSUE TITLE
1.16.5 : heavy task

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1183]
Minecraft Version: 1.165 Airplane
MySQL: false
BungeeCord: false
Plugin version : 10.5.1
Debug :
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6880930/debug.zip)

Problem : 
There is an heavy task in the plugin (related to 'toolclick' that I don't use so I would like to toggle it OFF

![Screenshot_5310](https://user-images.githubusercontent.com/31826333/127052535-d15585b4-9105-4747-ac79-8fd2792bd751.png)

This event of toollistener take 80% of the plugin consumption
![Screenshot_5311](https://user-images.githubusercontent.com/31826333/127052711-dda799a6-ec65-4655-98e8-27334e5156d2.png)

Here is the spark : 
https://spark.lucko.me/XTKl9MbbPu

**Comment by ElBananaa** [comment]
Quick note for Kangarko : Some plugins use a command to initiate their tool system, so events like the `onToolClick` aren't checked at all until a command like `/chc region start` is executed, and stop being checked as soon as the region is created or the player disconnects. Hope this could help finding a way to improve this ^^

**Comment by kangarko** [comment]
Thanks, seems like recent Minecraft versions store ItemStack metadata in a slower way. When players click anything we compare their ItemStack in their hands with the ItemStack of the tool used to created regions.

I will investigate how to compare this faster, however for now I added a settings.yml toggle called Register_Tools that you can disable after you create your /chc region regions. Thank you.
