### ISSUE TITLE
Players Can't See Own Chat on 1.17.1

### ISSUE THREAD

**Issue by blockswerker** [kangarko/ChatControl#1185]
Minecraft Version: Purpur 1.17.1
MySQL: false
BungeeCord: false

Hello! I copied my settings from 1.16.5 to a 1.17.1 server and for some reason players cannot see their own chat. I can see thier chat as OP. I gave all players chatcontrol.chat.write. Any advice would be helpful, thanks!

**Comment by blockswerker** [comment]
Oh for some reason I have to give chatcontrol.chat.write and chatcontrol.chat.read explicitly on 1.17.1.

**Comment by ElBananaa** [comment]
> Minecraft Version: Purpur 1.17.1
> MySQL: false
> BungeeCord: false
> 
> Hello! I copied my settings from 1.16.5 to a 1.17.1 server and for some reason players cannot see their own chat. I can see thier chat as OP. I gave all players chatcontrol.chat.write. Any advice would be helpful, thanks!



> Oh for some reason I have to give chatcontrol.chat.write and chatcontrol.chat.read explicitly on 1.17.1.

Hey!
Yes, this permission has always been necessary in order to read/write in the chat. Even on previous versions (At least, for me).
May I close this issue since it looks like you fixed it?

**Comment by ElBananaa** [comment]
Closing this issue since it has been fixed by its author.
