### ISSUE TITLE
Togglable Swear Filter

### ISSUE THREAD

**Issue by NoobcoreNetwork** [kangarko/ChatControl#1186]
So, I was looking at using a plugin to have a 'toggleable' swear filter for the kids on my server, so they won't see words like 'f***' as an example across the network (bungeecord)

So the player could do /toggleswears or something

But then I thought, Would it be hard to have this in chat control? It makes more sense for the chat plugin to have this feature in my opinion. But I'm unsure how or where the 'swear' strings would be stored.

is it possible to get this integrated into chat control? I think it's a useful idea and would be a nice feature

Thanks!

**Comment by kangarko** [comment]
Hey! Thanks for suggesting this. Our previous generation ChatControl Pro had this feature however it never worked as intended and the technical implementation makes it difficult to implement to Red, so we decided not to include it right now. Evaluating a chat message for every online player to see if he has a rule turned off would also drain performance noticeably.
