### ISSUE TITLE
swear

### ISSUE THREAD

**Issue by ttt0** [kangarko/ChatControl#1187]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

They can swear on my server I couldn't find what can I do for this, what setting should I open.

**Comment by TheIntolerant** [comment]
It should be working by default, can you run "/chc debug" and upload the debug file here, thanks.

**Comment by kangarko** [comment]
Likely a problem with another plugin, deinstall all other plugins except for ChatControl Red then try installing them one-by-one to see which one causes it, likely another chat-plugin. Also check your permissions if players do not accidentally have a bypass permission. If none of this helps, post us your debug file below, and I will read it.
