### ISSUE TITLE
Error: Wont Work Or Load

### ISSUE THREAD

**Issue by Bowbuck2** [kangarko/ChatControl#119]
Getting This Error Spammed 

http://pastie.org/10891158

**Comment by EvilOlaf** [comment]
Your version of CHC is updated. Update and try again.

**Comment by kangarko** [comment]
The sound names has been changed in Minecraft 1.9. You are on 1.7 so you need to adjust the names.

Look for '**ENTITY_CHICKEN_EGG**' and change it to '**CHICKEN_EGG_POP**' in your settings.yml
