### ISSUE TITLE
Default Chat Status

### ISSUE THREAD

**Issue by TheMattVid** [kangarko/ChatControl#119]
I use this plugin to turn off chat in my lobby, but I have to run the command every time I reboot the server. It would be nice if ChatControl had a setting to set a server's chat to be on or off by default.

**Comment by kangarko** [comment]
I don't understand your issue, you want to turn the server chat off? What command are you running after reboot? There are plugins to automatize running commands, perhaps you can use them.

**Comment by TheMattVid** [comment]
Every time I reboot, I run /chc mute

A permanent config option of this would be helpful.

**Comment by kangarko** [comment]
There are tons of plugins allowing you to automatically run specified command upon server startup, please use them.
