### ISSUE TITLE
1.17.1: Can not use Global/Ranged/Helpop Channels when Auto Channel Join set.

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#1190]
Hi, I have set it so that all my players auto join the channel of the world they join, but now when i try to join global, ranged or helpop channels, it keeps you in the world channel of the world you're in.

Is there a solution to this?

**Comment by ElBananaa** [comment]
Hey!
This is due to the fact that the plugin will automatically join players to the channel assigned to their world, as you asked in your previous ticket. I'm not sure to understand the issue tbho. You said you want them to automatically join the channel of the world they're in, but now you don't want to anymore?

**Comment by 00Hrtz** [comment]
> 
> 
> Hey!
> This is due to the fact that the plugin will automatically join players to the channel assigned to their world, as you asked in your previous ticket. I'm not sure to understand the issue tbho. You said you want them to automatically join the channel of the world they're in, but now you don't want to anymore?

Not at all, i said i wanted them to auto join the channel of the world the player enters yes, objective achieved. But i also want everyone to be able to use Global Channel and Helpop Channel as well.

So in other words, they are in a world channel but they can also manually join and use global/helpop channel by command as well

**Comment by ElBananaa** [comment]
> > Hey!
> > This is due to the fact that the plugin will automatically join players to the channel assigned to their world, as you asked in your previous ticket. I'm not sure to understand the issue tbho. You said you want them to automatically join the channel of the world they're in, but now you don't want to anymore?
> 
> Not at all, i said i wanted them to auto join the channel of the world the player enters yes, objective achieved. But i also want everyone to be able to use Global Channel and Helpop Channel as well.
> 
> So in other words, they are in a world channel but they can also manually join and use global/helpop channel by command as well

Idk if this can be achieved, however, I'm not sure about how this could be done if it is possible. I'll try a few things later tonight or tomorrow.

**Comment by 00Hrtz** [comment]
I was thinking along the lines of using chat id's like

/global message
/helpop message

sending to their channels but you stay in the worlds channel.

**Comment by ElBananaa** [comment]
> I was thinking along the lines of using chat id's like
> 
> /global message
> /helpop message
> 
> sending to their channels but you stay in the worlds channel.

Oh, if you want something like that, it's pretty easy to achieve. You can find some examples about how to do so in the chat.rs file or in the commands.rs file.

Either you can use a symbol at the beginning of your message, like the example below, in the chat.rs.
```rs
# Send messages starting with "$" to helpop chat
match ^(\$)(.*)
require perm chatcontrol.channel.autojoin.helpop.read
then command ch send helpop $2
then deny
dont verbose
```

Or you can use this example if you'd rather use a command like `/helpop` : 

```rs
# Catch "/helpop" command and send usage.
#match ^\/helpop$
#dont verbose
#then warn &cDescription: Send a message to online staff members.
#then warn &cUsage: /helpop <message>
#then deny

# Catch "/helpop <message>" and redirect to the helpop channel.
#match ^(\/helpop) (.*)
#dont verbose
#then command channel send helpop $2
#then deny
```

**Comment by 00Hrtz** [comment]
I tried this below but it's not working


 Catch "/global" command and send usage.
match ^\/global
dont verbose
then warn &cDescription: Send a message to global channel.
then warn &cUsage: /global <message>
then deny

 Catch "/global <message>" and redirect to the global channel.
match ^(\/global) (.*)
dont verbose
then command channel send global $0
then deny

**Comment by ElBananaa** [comment]
> I tried this below but it's not working
> 
> Catch "/global" command and send usage.
> match ^/global
> dont verbose
> then warn &cDescription: Send a message to global channel.
> then warn &cUsage: /global
> then deny
> 
> Catch "/global " and redirect to the global channel.
> match ^(/global) (.*)
> dont verbose
> then command channel send global $0
> then deny

Alright, could you give more informations? What do you mean exactly by "it's no working"?
Also, don't uncomment the first line as it could break the plugin.
This is how it should look like in your commands.rs file:
```rs
#Catch "/global" command and send usage.
match ^/global
dont verbose
then warn &cDescription: Send a message to global channel.
then warn &cUsage: /global
then deny

#Catch "/global " and redirect to the global channel.
match ^(/global) (.*)
dont verbose
then command channel send global $0
then deny
```

**Comment by 00Hrtz** [comment]
Ok so i've done exactly as you said and this is what i get when i type /global in chat

![2021-07-30](https://user-images.githubusercontent.com/66942713/127676986-9c42108b-6234-4a16-ad93-9614b06233ca.png)

and this is what i get after typing /global hello and sending in chat

![2021-07-30 (1)](https://user-images.githubusercontent.com/66942713/127677102-93e23f3f-091b-44da-a0f0-147fa7ee730a.png)

But nothing is actually sent to the global chat channel, the global channel is how its set as default.

**Comment by ElBananaa** [comment]
> Ok so i've done exactly as you said and this is what i get when i type /global in chat
> 
> ![2021-07-30](https://user-images.githubusercontent.com/66942713/127676986-9c42108b-6234-4a16-ad93-9614b06233ca.png)
> 
> and this is what i get after typing /global hello and sending in chat
> 
> ![2021-07-30 (1)](https://user-images.githubusercontent.com/66942713/127677102-93e23f3f-091b-44da-a0f0-147fa7ee730a.png)
> 
> But nothing is actually sent to the global chat channel, the global channel is how its set as default.

Oh ok, alright.
Try with : 
```rs
#Catch "/global" command and send usage.
match ^\/global$
dont verbose
then warn &cDescription: Send a message to global channel.
then warn &cUsage: /global
then deny

#Catch "/global " and redirect to the global channel.
match ^(\/global) (.*)
dont verbose
then command channel send global $0
then deny
```

**Comment by 00Hrtz** [comment]
> 
> 
> > Ok so i've done exactly as you said and this is what i get when i type /global in chat
> > ![2021-07-30](https://user-images.githubusercontent.com/66942713/127676986-9c42108b-6234-4a16-ad93-9614b06233ca.png)
> > and this is what i get after typing /global hello and sending in chat
> > ![2021-07-30 (1)](https://user-images.githubusercontent.com/66942713/127677102-93e23f3f-091b-44da-a0f0-147fa7ee730a.png)
> > But nothing is actually sent to the global chat channel, the global channel is how its set as default.
> 
> Oh ok, alright.
> Try with :
> 
> ```rust
> #Catch "/global" command and send usage.
> match ^\/global$
> dont verbose
> then warn &cDescription: Send a message to global channel.
> then warn &cUsage: /global
> then deny
> 
> #Catch "/global " and redirect to the global channel.
> match ^(\/global) (.*)
> dont verbose
> then command channel send global $0
> then deny
> ```

Yes, i tried that also and results exactly the same, i even restarted the server after trying with a plugin reload but still the same.

**Comment by ElBananaa** [comment]
Hmmm... That's weird, it's working fine for me.
Try placing it near the top of your `rules/command.rs` file, and also replace `then command channel send global $0` with `then command channel send global $2`

If it still doesn't work, I'd need you to provide us your `/chc debug` file since I can't reproduce the issue on my side on a fresh install

**Comment by SirCraftypants** [comment]
I ran /chc debug but i can not locate any debug.zip, where is it located?

**Comment by 00Hrtz** [comment]
> 
> 
> Hmmm... That's weird, it's working fine for me.
> Try placing it near the top of your `rules/command.rs` file, and also replace `then command channel send global $0` with `then command channel send global $2`
> 
> If it still doesn't work, I'd need you to provide us your `/chc debug` file since I can't reproduce the issue on my side on a fresh install

https://ufile.io/6xn2qspc

**Comment by ElBananaa** [comment]
> > Hmmm... That's weird, it's working fine for me.
> > Try placing it near the top of your `rules/command.rs` file, and also replace `then command channel send global $0` with `then command channel send global $2`
> > If it still doesn't work, I'd need you to provide us your `/chc debug` file since I can't reproduce the issue on my side on a fresh install
> 
> https://ufile.io/6xn2qspc

Alright, it seems to be working fine for me even with your config. Update the plugin to v10.5.1 and try again.

**Comment by 00Hrtz** [comment]
> 
> 
> > > Hmmm... That's weird, it's working fine for me.
> > > Try placing it near the top of your `rules/command.rs` file, and also replace `then command channel send global $0` with `then command channel send global $2`
> > > If it still doesn't work, I'd need you to provide us your `/chc debug` file since I can't reproduce the issue on my side on a fresh install
> > 
> > 
> > https://ufile.io/6xn2qspc
> 
> Alright, it seems to be working fine for me even with your config. Update the plugin to v10.5.1 and try again.

updated and still the same.

**Comment by 00Hrtz** [comment]
oh no, it's working now, but the /global command still shows up red, is there a way to make the /global command white in chat?

**Comment by ElBananaa** [comment]
> oh no, it's working now, but the /global command still shows up red, is there a way to make the /global command white in chat?

Yes, you can using the `commands.yml` file in your server root directory:
```yaml
aliases:
  global:
  - channel send global $1-
```

**Comment by 00Hrtz** [comment]
> 
> 
> > oh no, it's working now, but the /global command still shows up red, is there a way to make the /global command white in chat?
> 
> Yes, you can using the `commands.yml` file in your server root directory:
> 
> ```yaml
> aliases:
>   global:
>   - channel send global $1-
> ```

thank you very much for all you help and for your patience.

**Comment by ElBananaa** [comment]
I'm glad I could help.
I'm closing the issue, feel free to comment down below if you need anything else.

**Comment by 00Hrtz** [comment]
> 
> 
> I'm glad I could help.
> I'm closing the issue, feel free to comment down below if you need anything else.

I have an issue, i set up the global channel as stated, placed all worlds under the global channel. give all the permissions but players can not see each others global messages. Here's a list of all permissions i've given the group.

- chatcontrol.channel.autojoin.global.read
- chatcontrol.channel.autojoin.helpop.read
- chatcontrol.channel.autojoin.lobby.read
- chatcontrol.channel.autojoin.arcade.read
- chatcontrol.channel.autojoin.buildbattle.read
- chatcontrol.channel.autojoin.hidenseek.read
- chatcontrol.channel.autojoin.thelab.read
- chatcontrol.channel.autojoin.creative.read
- chatcontrol.channel.autojoin.farmworld.read
- chatcontrol.channel.autojoin.gallery.read
- chatcontrol.channel.autojoin.islandworld.read
- chatcontrol.channel.autojoin.citysquare.read
- chatcontrol.channel.autojoin.theshire.read
- chatcontrol.channel.autojoin.parkourpirates.read
- chatcontrol.channel.autojoin.parkour.read
- chatcontrol.channel.autojoin.skygames.read
- chatcontrol.channel.autojoin.skyblock.read
- chatcontrol.channel.autojoin.survival.read
- chatcontrol.channel.autojoin.lobby.write
- chatcontrol.channel.autojoin.arcade.write
- chatcontrol.channel.autojoin.buildbattle.write
- chatcontrol.channel.autojoin.hidenseek.write
- chatcontrol.channel.autojoin.thelab.write
- chatcontrol.channel.autojoin.creative.write
- chatcontrol.channel.autojoin.farmworld.write
- chatcontrol.channel.autojoin.gallery.write
- chatcontrol.channel.autojoin.islandworld.write
- chatcontrol.channel.autojoin.citysquare.write
- chatcontrol.channel.autojoin.theshire.write
- chatcontrol.channel.autojoin.parkourpirates.write
- chatcontrol.channel.autojoin.parkour.write
- chatcontrol.channel.autojoin.skygames.write
- chatcontrol.channel.autojoin.skyblock.write
- chatcontrol.channel.autojoin.survival.write
- chatcontrol.channel.join.global.read
- chatcontrol.channel.join.helpop.read
- chatcontrol.channel.join.lobby.read
- chatcontrol.channel.join.arcade.read
- chatcontrol.channel.join.buildbattle.read
- chatcontrol.channel.join.hidenseek.read
- chatcontrol.channel.join.thelab.read
- chatcontrol.channel.join.creative.read
- chatcontrol.channel.join.farmworld.read
- chatcontrol.channel.join.gallery.read
- chatcontrol.channel.join.islandworld.read
- chatcontrol.channel.join.citysquare.read
- chatcontrol.channel.join.theshire.read
- chatcontrol.channel.join.parkourpirates.read
- chatcontrol.channel.join.parkour.read
- chatcontrol.channel.join.skygames.read
- chatcontrol.channel.join.skyblock.read
- chatcontrol.channel.join.survival.read
- chatcontrol.channel.join.global.write
- chatcontrol.channel.join.helpop.write
- chatcontrol.channel.join.lobby.write
- chatcontrol.channel.join.arcade.write
- chatcontrol.channel.join.buildbattle.write
- chatcontrol.channel.join.hidenseek.write
- chatcontrol.channel.join.thelab.write
- chatcontrol.channel.join.creative.write
- chatcontrol.channel.join.farmworld.write
- chatcontrol.channel.join.gallery.write
- chatcontrol.channel.join.islandworld.write
- chatcontrol.channel.join.citysquare.write
- chatcontrol.channel.join.theshire.write
- chatcontrol.channel.join.parkourpirates.write
- chatcontrol.channel.join.parkour.write
- chatcontrol.channel.join.skygames.write
- chatcontrol.channel.join.skyblock.write
- chatcontrol.channel.join.survival.write
- chatcontrol.channel.leave.global.read
- chatcontrol.channel.leave.helpop.read
- chatcontrol.channel.leave.lobby.read
- chatcontrol.channel.leave.arcade.read
- chatcontrol.channel.leave.buildbattle.read
- chatcontrol.channel.leave.hidenseek.read
- chatcontrol.channel.leave.thelab.read
- chatcontrol.channel.leave.creative.read
- chatcontrol.channel.leave.farmworld.read
- chatcontrol.channel.leave.gallery.read
- chatcontrol.channel.leave.islandworld.read
- chatcontrol.channel.leave.citysquare.read
- chatcontrol.channel.leave.theshire.read
- chatcontrol.channel.leave.parkourpirates.read
- chatcontrol.channel.leave.parkour.read
- chatcontrol.channel.leave.skygames.read
- chatcontrol.channel.leave.skyblock.read
- chatcontrol.channel.leave.survival.read
- chatcontrol.channel.send.global
- chatcontrol.channel.send.helpop
- chatcontrol.channel.send.lobby
- chatcontrol.channel.send.arcade
- chatcontrol.channel.send.buildbattle
- chatcontrol.channel.send.hidenseek
- chatcontrol.channel.send.thelab
- chatcontrol.channel.send.creative
- chatcontrol.channel.send.farmworld
- chatcontrol.channel.send.gallery
- chatcontrol.channel.send.islandworld
- chatcontrol.channel.send.citysquare
- chatcontrol.channel.send.theshire
- chatcontrol.channel.send.parkourpirates
- chatcontrol.channel.send.parkour
- chatcontrol.channel.send.skygames
- chatcontrol.channel.send.skyblock
- chatcontrol.channel.send.survival
- chatcontrol.channel.send
- chatcontrol.chat.read
- chatcontrol.chat.write
- chatcontrol.command.color
- chatcontrol.command.reply
- chatcontrol.command.tell
- chatcontrol.group.default

**Comment by ElBananaa** [comment]
> > I'm glad I could help.
> > I'm closing the issue, feel free to comment down below if you need anything else.
> 
> I have an issue, i set up the global channel as stated, placed all worlds under the global channel. give all the permissions but players can not see each others global messages. Here's a list of all permissions i've given the group.
> 
> * chatcontrol.channel.autojoin.global.read
> * chatcontrol.channel.autojoin.helpop.read
> * chatcontrol.channel.autojoin.lobby.read
> * chatcontrol.channel.autojoin.arcade.read
> * chatcontrol.channel.autojoin.buildbattle.read
> * chatcontrol.channel.autojoin.hidenseek.read
> * chatcontrol.channel.autojoin.thelab.read
> * chatcontrol.channel.autojoin.creative.read
> * chatcontrol.channel.autojoin.farmworld.read
> * chatcontrol.channel.autojoin.gallery.read
> * chatcontrol.channel.autojoin.islandworld.read
> * chatcontrol.channel.autojoin.citysquare.read
> * chatcontrol.channel.autojoin.theshire.read
> * chatcontrol.channel.autojoin.parkourpirates.read
> * chatcontrol.channel.autojoin.parkour.read
> * chatcontrol.channel.autojoin.skygames.read
> * chatcontrol.channel.autojoin.skyblock.read
> * chatcontrol.channel.autojoin.survival.read
> * chatcontrol.channel.autojoin.lobby.write
> * chatcontrol.channel.autojoin.arcade.write
> * chatcontrol.channel.autojoin.buildbattle.write
> * chatcontrol.channel.autojoin.hidenseek.write
> * chatcontrol.channel.autojoin.thelab.write
> * chatcontrol.channel.autojoin.creative.write
> * chatcontrol.channel.autojoin.farmworld.write
> * chatcontrol.channel.autojoin.gallery.write
> * chatcontrol.channel.autojoin.islandworld.write
> * chatcontrol.channel.autojoin.citysquare.write
> * chatcontrol.channel.autojoin.theshire.write
> * chatcontrol.channel.autojoin.parkourpirates.write
> * chatcontrol.channel.autojoin.parkour.write
> * chatcontrol.channel.autojoin.skygames.write
> * chatcontrol.channel.autojoin.skyblock.write
> * chatcontrol.channel.autojoin.survival.write
> * chatcontrol.channel.join.global.read
> * chatcontrol.channel.join.helpop.read
> * chatcontrol.channel.join.lobby.read
> * chatcontrol.channel.join.arcade.read
> * chatcontrol.channel.join.buildbattle.read
> * chatcontrol.channel.join.hidenseek.read
> * chatcontrol.channel.join.thelab.read
> * chatcontrol.channel.join.creative.read
> * chatcontrol.channel.join.farmworld.read
> * chatcontrol.channel.join.gallery.read
> * chatcontrol.channel.join.islandworld.read
> * chatcontrol.channel.join.citysquare.read
> * chatcontrol.channel.join.theshire.read
> * chatcontrol.channel.join.parkourpirates.read
> * chatcontrol.channel.join.parkour.read
> * chatcontrol.channel.join.skygames.read
> * chatcontrol.channel.join.skyblock.read
> * chatcontrol.channel.join.survival.read
> * chatcontrol.channel.join.global.write
> * chatcontrol.channel.join.helpop.write
> * chatcontrol.channel.join.lobby.write
> * chatcontrol.channel.join.arcade.write
> * chatcontrol.channel.join.buildbattle.write
> * chatcontrol.channel.join.hidenseek.write
> * chatcontrol.channel.join.thelab.write
> * chatcontrol.channel.join.creative.write
> * chatcontrol.channel.join.farmworld.write
> * chatcontrol.channel.join.gallery.write
> * chatcontrol.channel.join.islandworld.write
> * chatcontrol.channel.join.citysquare.write
> * chatcontrol.channel.join.theshire.write
> * chatcontrol.channel.join.parkourpirates.write
> * chatcontrol.channel.join.parkour.write
> * chatcontrol.channel.join.skygames.write
> * chatcontrol.channel.join.skyblock.write
> * chatcontrol.channel.join.survival.write
> * chatcontrol.channel.leave.global.read
> * chatcontrol.channel.leave.helpop.read
> * chatcontrol.channel.leave.lobby.read
> * chatcontrol.channel.leave.arcade.read
> * chatcontrol.channel.leave.buildbattle.read
> * chatcontrol.channel.leave.hidenseek.read
> * chatcontrol.channel.leave.thelab.read
> * chatcontrol.channel.leave.creative.read
> * chatcontrol.channel.leave.farmworld.read
> * chatcontrol.channel.leave.gallery.read
> * chatcontrol.channel.leave.islandworld.read
> * chatcontrol.channel.leave.citysquare.read
> * chatcontrol.channel.leave.theshire.read
> * chatcontrol.channel.leave.parkourpirates.read
> * chatcontrol.channel.leave.parkour.read
> * chatcontrol.channel.leave.skygames.read
> * chatcontrol.channel.leave.skyblock.read
> * chatcontrol.channel.leave.survival.read
> * chatcontrol.channel.send.global
> * chatcontrol.channel.send.helpop
> * chatcontrol.channel.send.lobby
> * chatcontrol.channel.send.arcade
> * chatcontrol.channel.send.buildbattle
> * chatcontrol.channel.send.hidenseek
> * chatcontrol.channel.send.thelab
> * chatcontrol.channel.send.creative
> * chatcontrol.channel.send.farmworld
> * chatcontrol.channel.send.gallery
> * chatcontrol.channel.send.islandworld
> * chatcontrol.channel.send.citysquare
> * chatcontrol.channel.send.theshire
> * chatcontrol.channel.send.parkourpirates
> * chatcontrol.channel.send.parkour
> * chatcontrol.channel.send.skygames
> * chatcontrol.channel.send.skyblock
> * chatcontrol.channel.send.survival
> * chatcontrol.channel.send
> * chatcontrol.chat.read
> * chatcontrol.chat.write
> * chatcontrol.command.color
> * chatcontrol.command.reply
> * chatcontrol.command.tell
> * chatcontrol.group.default

Make sure all players are in the global channel in read mode using `/ch list`, and also make sure your `Max_Read_Channels` option in the settings file is high enough.
