### ISSUE TITLE
Cluster support

### ISSUE THREAD

**Issue by msmanui** [kangarko/ChatControl#1191]
Currently this plugin is not useful for networks as u are force to use the tab complete across the whole bungee players and not specifying a list of servers to be share. I dont want a player of Survival autocompleting players of Skyblock.

Soporting server cluster with ID
So all servers with that id, will share the players tab-complete.

bungee_options:
  enable_bungee_mode: true
  server_id: sv2
  cluster_id: 0
  tab_complete_cross_server:
    enabled: true
    delay: 60
So every server with the same cluster_ID, will share the tab complete.
This is the plugin which implements:
https://www.spigotmc.org/resources/⭐-huskhomes-1-17-x-⭐-simple-intuitive-teleportation-suite-with-cross-server-support.83767/

**Comment by kangarko** [comment]
We are no longer adding feature updates to ChatControl Free.

**Comment by msmanui** [comment]
> We are no longer adding feature updates to ChatControl Free.
I have chatControl red...

**Comment by msmanui** [comment]
> We are no longer adding feature updates to ChatControl Free.



I do have ChatControl-Red and this plugin is lucking of Cluster feature which is an essential feature... If not im force to have a msg complete for 1000 players in my whole network...

**Comment by ElBananaa** [comment]
> > We are no longer adding feature updates to ChatControl Free.
> 
> I do have ChatControl-Red and this plugin is lucking of Cluster feature which is an essential feature... If not im force to have a msg complete for 1000 players in my whole network...

Hey!
Sorry, I think Kangarko got confused, reopening this issue due to the misunderstanding. ^^

**Comment by kangarko** [comment]
I apologies, I accidentally opened the wrong ticket to reply to to you.

I do not think we can support the cluster feature, I have never dealt with it nor I have the time to learn about it, but you can resort to disabling our tab completion feature by setting Integration.ProtocolLib.Listen_For_Packets to false in settings.yml for now.

**Comment by ElBananaa** [comment]
Hey!
Since someone else also asked for this feature, it looks like it is now being studied. Please refer to #1221
