### ISSUE TITLE
Deny Silently as Option for Anti-Spam

### ISSUE THREAD

**Issue by blockswerker** [kangarko/ChatControl#1192]
I'd like to see `deny silently` as an option for all anti-spam, instead of the current message the spammer sees ("You may not send a message that is 100% identical.."). This is possible with rules such as swears and ads, but it doesn't seem to be available for the auto-moderation options in `settings.yml`.

1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)

I think this is in the spirit of ChatControl-Red, it's even in the marketing text on Spigot: _"Silence bad players without them knowing: SILENT message cancellation. Make the spammer think everyone saw his spam, while in reality only he saw it and staff was alerted — even if staff is on another server or offline."_

2. What would happen if we won't implement this feature? How's your server being affected?

Currently, once spammers know they are being denied they adjust their settings for maximum efficiency. ChatControl-Red is good enough to block 80% of the messages but giving the spammer less insight into what is going on would be helpful.

**Comment by kangarko** [comment]
You can set this message to "none" in your localization so that nothing will be sent.
