### ISSUE TITLE
1.16.5: Third-Party Name and Chat Color

### ISSUE THREAD

**Issue by blockswerker** [kangarko/ChatControl#1194]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hello, I use access to name and chat color as reward for voters via a plugin called UltraColor. I set this up before I adopted ChatControl-Red. I give players 26 hours of access for each vote and I chose that plugin because it allows me reset a player's chat and name color when they run out of time (the reset command is tied to their access to the command).

I see that ChatControl-Red is allowing their custom chat color to show in my channels, but custom name colors are being stripped. Is there a setting or formatting change I need to make to allow the custom name colors?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Hello, I use access to name and chat color as reward for voters via a plugin called UltraColor. I set this up before I adopted ChatControl-Red. I give players 26 hours of access for each vote and I chose that plugin because it allows me reset a player's chat and name color when they run out of time (the reset command is tied to their access to the command).
> 
> I see that ChatControl-Red is allowing their custom chat color to show in my channels, but custom name colors are being stripped. Is there a setting or formatting change I need to make to allow the custom name colors?

Hey!
As shown on the plugin page, it has a few placeholders that you can use : `%ucolor_chat_color%`, `%ucolor_name_color%`, `%ucolor_chat_color_name%` and `%ucolor_name_color_name%`.
In your case, I'd suggest placing `{ucolor_name_color}` before the `{player}` placeholder in your format file, and it should work.

**Comment by blockswerker** [comment]
Thank you! The formatting of the placeholders was not obvious to me, I greatly appreciate the help with this.

**Comment by ElBananaa** [comment]
I'm glad I could help you on this!
I'm closing the issue, but feel free to keep commenting down below if you need anything else.

**Comment by blockswerker** [comment]
I've updated my format file (chat.yml) and it works except that incoming chat from Discord actually displays as "[Discord] (ucolor_name_color}" in game chat. Is there a way to have entirely separate treatments for Discord and game chat that still uses a format file? Essentially, I want to put Format_Discord: in chat.yml.

**Comment by kangarko** [comment]
Yes you can put Format_Discord key to settings.yml in the channel configuration and render completely different format on Discord messages:

![a](https://i.imgur.com/3ElXdei.png)

**Comment by blockswerker** [comment]
Apologies for editing this a few times, I think we're close to a solution.

Format_Discord doesn't seem to be working. If I enter "chat_from_discord" and create "chat_from_discord.yml" it's not using that format even after a reboot. Instead of printing the formatted message on the Discord server it prints "chat_from_discord" in the discord channel.

That's not behaving as expected, but it's also not my problem: My problem is that chat FROM Discord is going through my "chat.yml" format and picking up formatting that it can't resolve, {ucolor_name_color}.

Is it possible to format chat FROM Discord seperately from in-game chat?

**Comment by kangarko** [comment]
Check the Discord setup video in the Wiki to ensure you've connected it right. I do think it should then pick on the Format_Discord option
