### ISSUE TITLE
Suggestion: afk feature

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#1196]
1. Some of us prefer chc over essentials, requiring us to download a separate plugin for the for the afk feature

2. Doesn’t seem like it’s a game breaker but would certainly compliment the rest of the plugin. I assume it wouldn’t be too much to implement

Thank you for your consideration:D

**Comment by kangarko** [comment]
Thank, however there is less than <2 people requesting this for over a year and I feel like this would just bloat the plugin even more with extra features, we may introduce extensions to ChatControl to cover this.
