### ISSUE TITLE
1.16.5: Error loading configuration in settings.yml!

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1198]
##Reading done##

On bootup the chatcontrol plugin tries to connect to the mysql db. unfortunaly the console returns errors while connecting

Console errors (~line 500): https://pastebin.com/BynxMyE4
the SQL connection is working, because i have other plugins running to that same MySQL db. So it cannot be the username/password/portforward or the SSL connection.

i suspect that the message "Error loading configuration in settings.yml!"  --> "Problematic section: MySQL" is a part of the problem. due to the fact that my "setting.yml" file does not have a "MySQL" part. 

NOTE that the "settings.yml" file is a clean file where i only changed the bungeecord integration flag.

settings.yml file :  https://pastebin.com/xLFF8Thm   (*note that pastebin marks the setting.yml file as offensive*)

mysql.yml file :  https://pastebin.com/T1xmgDmT

Minecraft Version: papermc 1.16.5 #783 (latest)
MySQL: true
BungeeCord: true

Creating this ticket took around 45 minutes due to all your demands for reading al your 'read this first' and 'do this that way' requisites.. this creates a huge difficulty for people to help you improve the plugin by reporting stuff. perhaps for simple questions create a discord server.

**Comment by ElBananaa** [comment]
> ##Reading done##
> 
> On bootup the chatcontrol plugin tries to connect to the mysql db. unfortunaly the console returns errors while connecting
> 
> Console errors (~line 500): https://pastebin.com/BynxMyE4
> the SQL connection is working, because i have other plugins running to that same MySQL db. So it cannot be the username/password/portforward or the SSL connection.
> 
> i suspect that the message "Error loading configuration in settings.yml!" --> "Problematic section: MySQL" is a part of the problem. due to the fact that my "setting.yml" file does not have a "MySQL" part.
> 
> NOTE that the "settings.yml" file is a clean file where i only changed the bungeecord integration flag.
> 
> settings.yml file : https://pastebin.com/xLFF8Thm (_note that pastebin marks the setting.yml file as offensive_)
> 
> mysql.yml file : https://pastebin.com/T1xmgDmT
> 
> Minecraft Version: papermc 1.16.5 #783 (latest)
> MySQL: true
> BungeeCord: true
> 
> Creating this ticket took around 45 minutes due to all your demands for reading al your 'read this first' and 'do this that way' requisites.. this creates a huge difficulty for people to help you improve the plugin by reporting stuff.

Hey,
I think your username/password formats aren't supported by the plugin. Could you try creating a test database with a password and a username like 'chctest' and see if it works with these credentials.

I'm not sure to understand why it took you 45 minutes to create a ticket, the text is pretty short and shouldn't take more than a few mins to read. This is necessary for us because if we don't force people to follow some rules and a format, we would be all losing more time.

**Comment by donvdp** [comment]
Wow thanks for your quick reply !

Ive just tried creating a test database called "test"   
username = test
password = 12345678

i get the same error message with this config:
https://pastebin.com/sLfABZBZ

Line 13 of the mysql.yml file says something about overwriting mysql settings in the setting.yml file. but i cannot find that section in the settings.yml file. Could this perhaps be the error ? that there is missing data in the settings.yml file ?

the contents of my error.log file keeps returning the same errors:
https://pastebin.com/tMMvwXa8

Above error log shows text about "closed zip" ? I dont understand.

**Comment by ElBananaa** [comment]
> Wow thanks for your quick reply !
> 
> Ive just tried creating a test database called "test"
> username = test
> password = 12345678
> 
> i get the same error message with this config:
> https://pastebin.com/sLfABZBZ
> 
> Line 13 of the mysql.yml file says something about overwriting mysql settings in the setting.yml file. but i cannot find that section in the settings.yml file. Could this perhaps be the error ? that there is missing data in the settings.yml file ?
> 
> the contents of my error.log file keeps returning the same errors:
> https://pastebin.com/tMMvwXa8
> 
> Above error log shows text about "closed zip" ? I dont understand.

You're welcome!
As far as I know, everything was moved out from the settings file to the mysql file, so this message is surely an oudated message.
From what I can see now in your latest.log (https://pastebin.com/BynxMyE4), other plugins such as PlotSquared have the same issue, and it gives me multiple ideas regarding how to solve this.

- First of all, the issue might be related to the max amount of mysql connections being exceeded. I'd suggest taking a look at tutorials about "How to increase mysql maximum connection amount" if you're using a VPS or a dedicated server. If you're using a mutualized host, I'd suggest trying to reach their support and asking about more informations/an upgrade of the amount of mysql connections.

- There's an issue with another plugin causing mysql related issues. In this case I'd suggest creating a test server with only ChatControlRed, Vault, ProtocolLib and NashornPlus, and trying to connect this server to a completely brand new test database with a new user. If you try this at first, and it still doesn't work, then I'd suggest doing what I said in the first place.

In the meantime, to get more informations about what happens, in the plugin settings file, please set `Debug:` to `Debug: [mysql]` and restart the server.
Hopefully, this will give us more informations in case this is something related to the plugin.

**Comment by donvdp** [comment]
Hi there and good morning. After a few pots of coffee I got it working. the debugging function realy helped.

Creating a test server with nothing else on it but the plugs you mentioned did the trick. From all the plugins i was running it seemed that "FeatherBoard-5.0.3b.jar" was causing the nashorn enigine to fail.

All actions related to chat and such returned with this error:
![image](https://user-images.githubusercontent.com/10013800/128314174-a55ebd42-45b0-492e-b9ec-b11540265445.png)

when in fact i have all the propper dependencies installed and up to date. When i disable "FeatherBoard-5.0.3b.jar" the java errors go away. im not sure why or how this is causing an error.

Would this be an error that i report here ?

**Comment by ElBananaa** [comment]
> Hi there and good morning. After a few pots of coffee I got it working. the debugging function realy helped.
> 
> Creating a test server with nothing else on it but the plugs you mentioned did the trick. From all the plugins i was running it seemed that "FeatherBoard-5.0.3b.jar" was causing the nashorn enigine to fail.
> 
> All actions related to chat and such returned with this error:
> ![image](https://user-images.githubusercontent.com/10013800/128314174-a55ebd42-45b0-492e-b9ec-b11540265445.png)
> 
> when in fact i have all the propper dependencies installed and up to date. When i disable "FeatherBoard-5.0.3b.jar" the java errors go away. im not sure why or how this is causing an error.
> 
> Would this be an error that i report here ?

Hey,
I'm glad to know that you found the cause of the issue, however, it seems like it's a pretty weird error. I'd suggest trying to reach MaximVDW to at least know if the issue could be caused by Featherboard, and wait for an answer from Kangarko in the meantime.

**Comment by kangarko** [comment]
I am unfortunately unable to fix Featherboard crashing our Nashorn library. You can try deinstalling our Nashorn library in case Featherboard already installs it, or talk to Maxim, its developer. Best of luck and if there is anything on our end we can do for you just comment below!

PS: Discord support coming up this quarter :)
