### ISSUE TITLE
Op issues

### ISSUE THREAD

**Issue by Zeruul** [kangarko/ChatControl#120]
Hello!
I am trying to allow operators to be able to use the ChatControl commands while still being impacted by the grammatical rules of the plugin. For example, I would like them to be able to speak with auto-capitalization and punctuation, while not being denied the use of /gm, /heal, /chc reload, etc. In the config, I set Op_Has_Permissions to false so that the grammatical rules will still impact them. However, despite the fact that I have given them the permission to use commands such as /chc reload, mute, etc., along with the permission to bypass the ChatControl rules (using PermissionsEx), operators are denied access to these commands. It seems like the ChatControl config takes ultimate priority and basically counters the changes made in my permissions plugin. Is there a way to allow operators to use the grammatical functions of the plugin while still being able to access these other commands? I appreciate any suggestions very much.
Thank you!

**Comment by ThemInspectors** [comment]
Could you please paste your configs and other stuff?

**Comment by Zeruul** [comment]
I actually just recently found a possible solution. Since capitalization/punctuation are their own permission, I simply used "negative" permissions (- -chatcontrol.bypass.punctuate) (- -chatcontrol.bypass.capitalize) to remove the bypass permission from admins, who I have given all permissions with '*'. But that still means that they cannot be ops in order to be impacted by these grammatical rules. Perhaps consider adding an option in the configuration that can either enable or disable the punctuation/capitalization rules impacting ops; or allow for permissions plugins to take priority so that negative permissions outweigh the Op_Has_Permissions option in the config. @kangarko Thank you.

**Comment by kangarko** [comment]
Hello, thank you for taking time to find the solution yourself ;) The logic has been improved in the pro version and that config key has been as such removed. But I believe that due how the plugin works, giving negative permissions is an optimal solution.
