### ISSUE TITLE
Swear Bypass Report

### ISSUE THREAD

**Issue by TheMattVid** [kangarko/ChatControl#120]
This plugin's swear filter is almost always flawless, preventing the many well known methods to get around it, including spaces and special characters.

Somehow, someone was able to use special characters in their messages. These are the messages sent. They look normal in Minecraft chat, but from the console they are clearly different.

fuck

 fuck all of u cunts

If you are to copy and paste these messages into your own textbox, you can see how they work. They aren't actually special alphabetic characters, but instead, special symbols that appear over the preceding letters. This needs to be prevented.

**Comment by TheMattVid** [comment]
Perhaps instead of blocking characters, this issue can be fixed by making it so that only certain characters are accepted.

I have been told by the person who used this method that there are 21 different characters that do this, and it is somewhat a cause for concern.

**Comment by kangarko** [comment]
I will look more precise into that issue later.

You can temporary deny such characters by creating a filter that blocks non-english/unicode characters. I can try to strip all non standard characters from the message before it is checked against a filter, but this might cause problems for for example Cyrillic alphabet, or similar.

**Comment by kangarko** [comment]
Hey @TheMattVid , sorry for the delay, I almost missed this issue. Notice this is not a bug to chatcontrol, it is issue only regarding the filter not being able to catch up the message.

I have tested out this filter and found out that is working and filtering these special characters:

match \b(f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
handle as swear

**Comment by TheMattVid** [comment]
It would be way to difficult to block out the characters individually for every single swear. There are too many special characters and too many swears.

I only want players to be able to type in standard keyboard characters on my server. All other messages should be blocked off with the player receiving a message like "Only standard keyboard characters may be used."

**Comment by kangarko** [comment]
>It would be way to difficult to block out the characters individually for every single swear. There are too many special characters and too many swears.
You don't need to block out all the characters individually because the filter above will block all of them. Unfortunately, you need to create a filter for every swear, but this shouldn't take that much time if you would only change the characters in the filter above:
```
match \b(**f**+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
```

**Comment by TheMattVid** [comment]
I found this. It matches all characters not on a standard keyboard and it will make my life a whole lot easier.

**Comment by kangarko** [comment]
Allright, so you found a suitable solution?

**Comment by TheMattVid** [comment]
Yes, if I block messages that match that string, then all bypasses will pretty much be patched for me. This even includes other weird dot characters people use to advertise. I am very satisfied.

**Comment by kangarko** [comment]
Ok that's good, I am closing this issue then.
