### ISSUE TITLE
1.16.4 | String cannot be cast to SimpleTime error in Checker when chatting

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#120]
https://pastebin.com/fjRMN2gh error.log

https://pastebin.com/UR9ScAeN console

https://i.gyazo.com/a47db6dd7e9d41b5ee4ad55ac738444c.png picture

It would seem for some reason, chat just completely doesn't work for some players? I have no idea why but this is what console gives. ^

**Comment by DoogiePC** [comment]
For some reason it is anyone if I give them the "president" rank? Their chat just breaks?

**Comment by kangarko** [comment]
Thanks, may I see your settings.yml?

 I also noticed error about LiteBans, next version will print this in full so we can fix that.

**Comment by DoogiePC** [comment]
https://pastebin.com/PbqFDgcu - settings.yml

**Comment by kangarko** [comment]
Hurray I fixed that!
