### ISSUE TITLE
1.16.5: Variable Hover Limit?

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl#1202]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I seem to have an issue with my items in chat.

When I put certain items in chat it doesn't seem to be hovering.
![6PtnTjN](https://user-images.githubusercontent.com/16086663/128086159-b882cb0c-bcb4-4f02-a9aa-e380a594ef5d.png)

![GKv3WVe](https://user-images.githubusercontent.com/16086663/128086259-0e908649-0fac-494c-964b-79e15e9f9beb.png)

Whereas other items do work?
![8huO0zy](https://user-images.githubusercontent.com/16086663/128086512-d8e4822c-509e-4ec6-b724-db90203c8211.png)
![EbZAfVH](https://user-images.githubusercontent.com/16086663/128086478-9a5f14c2-f3ea-4a66-8ed9-f4f29d4d27d1.png)

Here is my variable config.

https://hastebin.com/kuniceniru.php

Is there potentially a limit on how many characters show when hovering?

PS there is no error in console with this

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, I seem to have an issue with my items in chat.
> 
> When I put certain items in chat it doesn't seem to be hovering.
> ![6PtnTjN](https://user-images.githubusercontent.com/16086663/128086159-b882cb0c-bcb4-4f02-a9aa-e380a594ef5d.png)
> 
> ![GKv3WVe](https://user-images.githubusercontent.com/16086663/128086259-0e908649-0fac-494c-964b-79e15e9f9beb.png)
> 
> Whereas other items do work?
> ![8huO0zy](https://user-images.githubusercontent.com/16086663/128086512-d8e4822c-509e-4ec6-b724-db90203c8211.png)
> ![EbZAfVH](https://user-images.githubusercontent.com/16086663/128086478-9a5f14c2-f3ea-4a66-8ed9-f4f29d4d27d1.png)
> 
> Here is my variable config.
> 
> https://hastebin.com/kuniceniru.php
> 
> Is there potentially a limit on how many characters show when hovering?
> 
> PS there is no error in console with this

Hey!
I believe yes, there's a hover limit. I'm not sure about it, but I think it's a minecraft-related issue, so I don't know if there's much Kangarko could do about it.
I'll leave this issue open so Kangarko could review it ^^

**Comment by kangarko** [comment]
Looks like you are running into our JSON limitter which, if you exceed 50,000 letters in your message (encoded into JSON a basic message can get to this size fairly quickly) we then remove the interactive elements from it.

You can probably try setting Strip_Oversized_Json to false in settings.yml, but no guarantees.
