### ISSUE TITLE
1.17.1:issue getting "anal" to filter 

### ISSUE THREAD

**Issue by SecretarySami** [kangarko/ChatControl#1203]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

So I was recently made aware that the word "anal" was no longer filtering , however I have not touched my match in weeks.
I was originally using this match -

```rs
Blocks 'anal'
match ((\ba|\B@)+(\W|\d|)*n+(\W|\d|)(a|@)+(\W|\d|_)(i|1|l|!)+(\W|\d|_)*)
ignore string a an|an a|analog|an all|an almost|an alt|an alarm|an algorithm|an albino|an alot|an almond|an album|analyze|an alligator|a na|ana|anas|anakin
group swear
```

Then tried this one -

```rs
Blocks 'anal'
match \b(a+(\W|\d|)*n+(\W|\d|)a+(\W|\d|)*l+(\W|\d|))
ignore string a an|an a|analog|an all|an almost|an alt|an alarm|an algorithm|an albino|an alot|an almond|an album|analyze|an alligator|a na|ana|anas|anakin
group swear
```

it's not seeming to block the word despite it being in there, i'm not sure where i went wrong on it and i'm still struggling to figure out regex.

**Comment by ElBananaa** [comment]
Hey!
It looks like a few things aren't right with your rule.
First of all, keep the `Blocks 'anal'` part commented, so it should look like
```rs
#Blocks 'anal'
match \b(a+(\W|\d|)*n+(\W|\d|)a+(\W|\d|)*l+(\W|\d|))
ignore string a an|an a|analog|an all|an almost|an alt|an alarm|an algorithm|an albino|an alot|an almond|an album|analyze|an alligator|a na|ana|anas|anakin
group swear
```

Let me know if it changes anything.
Regarding regex, we recommend using a tool such as https://regex101.com/ to test them.
Finally, if it doesn't work after this change, please provide us your debug file (`/chc debug`) so we can took a deeper look at your files. ^^

**Comment by SecretarySami** [comment]
> Hey!
> It looks like a few things aren't right with your rule.
> First of all, keep the `Blocks 'anal'` part commented, so it should look like
> 
> ```rust
> #Blocks 'anal'
> match \b(a+(\W|\d|)*n+(\W|\d|)a+(\W|\d|)*l+(\W|\d|))
> ignore string a an|an a|analog|an all|an almost|an alt|an alarm|an algorithm|an albino|an alot|an almond|an album|analyze|an alligator|a na|ana|anas|anakin
> group swear
> ```
> 
> Let me know if it changes anything.
> Regarding regex, we recommend using a tool such as https://regex101.com/ to test them.
> Finally, if it doesn't work after this change, please provide us your debug file (`/chc debug`) so we can took a deeper look at your files. ^^

https://i.imgur.com/UgnFArZ.png
tried with your match , still isnt working, will turn on debug once i wake up!

**Comment by kangarko** [comment]
You had a too loose "ignore string" operator which whitelisted pretty much everything. This one works:

```
match \b(a+(\W|\d|)*n+(\W|\d|)a+(\W|\d|)*l+(\W|\d|))
ignore string analog|an almost|an alt|an alarm|an algorithm|an albino|an alot|an almond|an album|analyze|an alligator
group swear
```
