### ISSUE TITLE
Chat & general plugin setup

### ISSUE THREAD

**Issue by MadisonMadi** [kangarko/ChatControl#1206]
Minecraft Version: 1.12.2
MySQL: false
BungeeCord: false

Hello, ive come here with the question. how can i make custom join messages. and where. for each rank i have in LuckPerms
Second. how and where can you edit the chat so you can make your chat look nice. example is this 
![image](https://user-images.githubusercontent.com/17278366/128421848-5d07d569-113c-476d-bce1-3d6229dee815.png)
I have no idea at all. wiki doesn't help me with this at all where to find it or how to add it. this plugin is rather very complicated imo.. but thats just my opinion but this plugin is the best one out there so please i need quite a huge amount of help and will probably regulary ask for questions im sorry

**Comment by ElBananaa** [comment]
Hey!

- Regarding join messages, you can find everything you need in the `message/join.rs` file. You use our `require sender perm` operator to do so : https://github.com/kangarko/ChatControl-Red/wiki/Messages#require-sender-perm-permission-and-require-receiver-perm-permission.
Here's an example:
```rs
# group staff_message
# require sender perm chatcontrol.joinmessage.staff
# message: 
# - &8[&2+&8] &7Welcome &b{player} &7to the server!
# - &8[&2+&8] &7Bless &9{player} &7for joining!
# - &8[&2+&8] &7All say hey to &e{player} &7for joining!
# - &8[&2+&8] &7Watch out for &c{player} &7joining!
```

- To customize the chat, you first need to set `Channels.Enabled` to `true` in the settings file. (it's near the top of the file). Once this is done, all you have to do is edit the formats files you can find in `formats/`. The format file named `chat.yml` is the default format for the general chat, and contains a lot of comments explaining how the whole system works. Once again, I highly suggest reading our wiki, almost any basic and important information is on there. https://github.com/kangarko/ChatControl-Red/wiki/Formats

**Comment by kangarko** [comment]
Thanks Banana for helping out! Closing this, if you got any more questions feel free to ask below.
