### ISSUE TITLE
Bungeecord - Latest | Pupur 1.17.1: ChatControl staff channel with secondary chat plugin

### ISSUE THREAD

**Issue by Xeravax** [kangarko/ChatControl#1209]
# Server Information
**Minecraft Version**: 1.17.1
**MySQL**: `true`
**BungeeCord**: `true`

# Issue/Question
Currently, I'm using the plugin [KingdomCraft](https://kingdomcraft.be/) and this plugin has their own chat system. With it's internal channels for each "kingdom". However, we want to use chatcontrol for a part to get staff channels across our entire bungeecord. However, in the survival server this is overriden by the kingdomcraft plugin. 

Does anyone have an idea how to get this to work? We'd really like to use chatcontrol to it's full possibility. However, due to this issue we can't.

**Comment by ElBananaa** [comment]
> # Server Information
> **Minecraft Version**: 1.17.1
> **MySQL**: `true`
> **BungeeCord**: `true`
> 
> # Issue/Question
> Currently, I'm using the plugin [KingdomCraft](https://kingdomcraft.be/) and this plugin has their own chat system. With it's internal channels for each "kingdom". However, we want to use chatcontrol for a part to get staff channels across our entire bungeecord. However, in the survival server this is overriden by the kingdomcraft plugin.
> 
> Does anyone have an idea how to get this to work? We'd really like to use chatcontrol to it's full possibility. However, due to this issue we can't.

Hey!
Try to play arround with the listener priority in ChatControl's config file: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

**Comment by Xeravax** [comment]
Hi there @ElBananaa, It can filter just fine that's not an issue. Where I'm getting stuck at is using channels without breaking the chat Kingdomcraft manages

**Comment by ElBananaa** [comment]
Oh, this is a compatibility issue then. It means either Kangarko or Kingdomcraft author need to add compatibility for the other plugin in their own plugin. ^^

**Comment by kangarko** [comment]
Unfortunately if you were not able to resolve this by adjusting the Listener_Priority option, it means that plugin is incompatible with us. You will have to turn off channel system either on our or their end, or possibly contact them to integrate us. Due to time constrains I am not able to take onto another integration project at this time.

**Comment by Xeravax** [comment]
No problem, thanks anyway
