### ISSUE TITLE
Server Connection Delay is Flawed

### ISSUE THREAD

**Issue by TheMattVid** [kangarko/ChatControl#121]
ChatControl has the nice feature that prevents players from reconnecting immediately. The problem is that it is not working correctly. The recent connection of any other player will disallow the connection of any given player.

For example, if I have a player who goes from Server A to Server B and I try to go from Server A to Server B right afterward, I will not be allowed to and it will tell me to wait 3 seconds. This is flawed because I am not reconnecting to Server B. I am connecting to Server B for the first time all day. The 3 second delay is only supposed to check for my own recent logins, not all other players. If I go from Server B to Server A and right back to Server B, this 3 second delay is expected.

**Comment by kangarko** [comment]
Hello,
are you using bungecoords? If so, I am afraid I can't help you, since I don't own any bungee server so I can't replicate the bug.

**Comment by TheMattVid** [comment]
I had IP-forwarding set to off. Now that it's on, this probably won't be an issue.

**Comment by kangarko** [comment]
Do you still have this issue? If so, disable the feature in chatcontrol and set connection-throttle to 0 in bukkit.yml. If the issue won't persist, set the connection-throttle back to default or your value and if the issue comes up then, it will mean that it is bukkit's fault.

**Comment by TheMattVid** [comment]
No, I'm fairly confident that the IP-forwarding fixed my problem. This issue is now nonexistent.

**Comment by kangarko** [comment]
Okay, closing then :)
