### ISSUE TITLE
Member with DOT in there name

### ISSUE THREAD

**Issue by ItsMetri** [kangarko/ChatControl#121]
Funny story, a player on my server has DOT in their name. So they cannot be added to a faction or said in chat. Also, what's the permission so I can allow staff members to post links and not be counted as an advertisement.

**Comment by xknat** [comment]
funny that there should never be a name with a . in it

**Comment by kangarko** [comment]
You'll find the ad and swear bypass permission in handlers.yml.

In such case you'll need to manually add his name to the 'ignore string' operator in rules.txt like so:

`ignore string minecraft:|youtube.com|imgur.com|his.name`

Where _his.name_ is the actual name.
