### ISSUE TITLE
Console spam when players join multiple Channels

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#1210]
https://paste.helpch.at/rulacapibe.cs

How can i prevent the console being notified of players joining channels please?

**Comment by ElBananaa** [comment]
Hey!
To do so you can either remove the message from the localization file, or setting Show_Tips to false in the settings file.

**Comment by 00Hrtz** [comment]
> 
> 
> Hey!
> To do so you can either remove the message from the localization file, or setting Show_Tips to false in the settings file.

Thank you
