### ISSUE TITLE
Completing /chc tour

### ISSUE THREAD

**Issue by VENAdministration** [kangarko/ChatControl#1212]
Whenever I run the command and go through the steps, followed by /chc tour confirm, I cannot find a way to actually end the tour. The plugin will not let me perform commands on anything, and I read the terms and found no command to let me start using the plugin. I tried reloading, or restarting and it is as if I never completed the tour.

**Comment by TheIntolerant** [comment]
Run /chc mothman, assuming you agree to all the terms etc

**Comment by ElBananaa** [comment]
Hey!
I'm closing the issue since gone-incognito gave the command.
To find this command, you must read the message sent ingame/in the console after typing `/chc tour confirm`, which tells you to find it in our terms ^^
