### ISSUE TITLE
[Suggestion] Discord Integration with DiscordSRV use Discord Nickname instead of Discord Username

### ISSUE THREAD

**Issue by EdiTzZ** [kangarko/ChatControl#1215]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

If you're sending a message from Discord to Minecraft, the message will be edited to my Discord Username (EdiTzZ). Is it possible to change this to my Discord Nickname? Because I've auto-sync for nicknames and roles enabled and its better to identify the players :)

![Animation](https://user-images.githubusercontent.com/16694199/128609202-d59d341b-6332-4ca9-989b-7f86940e2db1.gif)

I cannot find it in the wiki...
Thanks :)

**Comment by ElBananaa** [comment]
Hey!
As far as I know, this isn't possible in the plugin right now.
Let's wait for kangarko to review this as a suggestion ^^

**Comment by kangarko** [comment]
Right now, the only way to not use our message redirection feature is to toggle off the Send_Messages_As_Bot key in Integration.Discord section of settings.yml. I believe the username wont be changed after that.
