### ISSUE TITLE
[Suggestion] Emote tab complete

### ISSUE THREAD

**Issue by ScottGB** [kangarko/ChatControl#1219]
Create a way so that when you type a colon ( : ) into chat, you can tab-complete emotes - you can designate a emote to show up in the rules by maybe adding something like "tab-complete permission.node".

In game it would show like so:
![image](https://user-images.githubusercontent.com/59319698/128655148-d74d1a41-7eb2-406c-9fad-d74aeba39479.png)

1. How it would benefit others? Due to larger servers, many people desire this ability now - and many many server owners have emotes.

2. What would happen if we won't implement this feature? How's your server being affected? This will create friction with users as they don't know the codes - therefore having to look them up.

**Comment by kangarko** [comment]
Thanks for your suggestion, however we are not interested in adding more such features  to the plugin because with each one it just gets more and more complex. I am trying to keep things simple and lean.

You can use ItemsAdder plugin if you need this feature.
