### ISSUE TITLE
Server Password Suggestion

### ISSUE THREAD

**Issue by TheMattVid** [kangarko/ChatControl#122]
I want players to need to type a password to be able to chat.

I don't mean the sort of password where players create their own password and login every time they enter the server.

I am referring to a one time code that players have to type in to gain the ability to chat. Ideally, ChatControl will have a file to list the players that have typed the code and they must be in the file to chat.

My main purpose is that I plan to create a youtube video that players must watch before they play on my server. At the end, I will put this code.

Also, the code should be configurable and perhaps in the form of a command.

**Comment by kangarko** [comment]
I think this is too far away from the original purpose of the plugin. You might need to use an additional plugin to cover your needs. Thanks for your understanding.
