### ISSUE TITLE
1.16.4 | chat image of size 0 throw an error

### ISSUE THREAD

**Issue by Qw4rtz** [kangarko/ChatControl#122]
When running `/chc a image creeper-head.png 0 wow` I get the error below:

`[✕] Failed to broadcast image from 'plugins/ChatControlRed/images/creeper-head.png': java.awt.image.ImagingOpException: Unable to invert transform AffineTransform[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]. Please see console for more information.`

It should not try and say it is not possible instead, even though it didn't crash anything that would looks better.
Anyways, the feature is great 😄

**Comment by kangarko** [comment]
Thank you, you did really break the plugin so congratulations!
