### ISSUE TITLE
Prefix Help

### ISSUE THREAD

**Issue by SoHo224** [kangarko/ChatControl#122]
How do i add prefixes to my name? like Owner? also how do you add default prefixes to new players? like guest. Thanks!

**Comment by EvilOlaf** [comment]
Use a permission management plugin like PermissionsEx that allows to define user groups with particular pre- and suffixes.
Also get Vault to allow CHC to use those.

**Comment by kangarko** [comment]
What @EvilOlaf said. You can use %pl_prefix and %pl_suffix variables to display them in chat formatter.
