### ISSUE TITLE
1.17: Name-Change Database Issue

### ISSUE THREAD

**Issue by toxinyx** [kangarko/ChatControl#1220]
One of my players changed their username today: upon doing the change channel command for any channel, it doesn't work. It shows this:
![unknown (4)](https://user-images.githubusercontent.com/86858026/128655124-1bf313ec-8dbf-4705-bfc0-86209e35f1ae.png)
But before the name change, it was working fine. 

debug:
https://ufile.io/e3me40pf

Minecraft Version: 1.17
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
What was the old username of FamilyJuless please do you remember?

**Comment by toxinyx** [comment]
> What was the old username of FamilyJuless please do you remember?

JuleVcrne

**Comment by kangarko** [comment]
Sorry I need one more piece of data, are you running cracked or online mode server?

**Comment by toxinyx** [comment]
It’s not a cracked server, so it’s an online mode one

**Comment by toxinyx** [comment]
It’s happened with another member. They went by goblinman_meade, changed their name to tillygoesbyburr today and now can’t do /channel join local

**Comment by kangarko** [comment]
Let's continue at https://github.com/kangarko/ChatControl-Red/issues/1240
