### ISSUE TITLE
Suggestion: Support for cluster_id

### ISSUE THREAD

**Issue by 7wOv6ySCjo** [kangarko/ChatControl#1221]
I see that the plugin don't have support for cluster_id or cross-server. You assume that we will only use a single group-server on ALL (!) the network?

**Comment by 7wOv6ySCjo** [comment]
and what would happen if I try to auto-complete the name of a player in the chat-box that is on ANOTHER group-server? ... please, add this option to the plugin.

**Comment by TheIntolerant** [comment]
Based on kangarko's response in #1191 unfortunately I do not think this is something that will be added.

**Comment by kangarko** [comment]
Yes we group all servers in your BungeeCord together. Just to give me an example is there a cluster support in BungeeCord/Waterfall or is it just up to plugin authors to implement it? I.e. I have seen this manually implemented for HuskHomes plugin...

**Comment by 7wOv6ySCjo** [comment]
> Yes we group all servers in your BungeeCord together. Just to give me an example is there a cluster support in BungeeCord/Waterfall or is it just up to plugin authors to implement it? I.e. I have seen this manually implemented for HuskHomes plugin...

Exactly. It is necessary for the author to add this function to the plugin. HuskHomes has it and I was wondering why this plugin does not. It really is necessary. Especially in commands like /tell and in the chat-box of the game. We don't want that when it tries to auto-complete it shows players from another group/server not specified in the ChatControl config.

![720aac048c349ef6b4b421c9c4e5d6bb](https://user-images.githubusercontent.com/44591651/128987470-74c17cef-d4b4-46cf-b7fc-6e86cb3b9486.png)

**Comment by kangarko** [comment]
I see. Due to time constrains I am not going to implement this right now, but I am leaving this ticket open to have a look in a few weeks or a month.

**Comment by 7wOv6ySCjo** [comment]
I have a correction to make. The "players in chat-box" solution is already implemented by another TAB plugin we have. It seems that the one in charge of enabling this function is the "SCOREBOARDS". So it is not up to CCR to take care of this.

At this point there are two major limitations with this plugin.
The first one: the plugin doesn't seem to support more than 160-260 players at the same time because of a [packet problem](https://github.com/kangarko/ChatControl-Red/issues/964).
The second one: it does not support cluster_id or cross-server implementation showing other players from other servers in commands like /tell, /ignore, etc.

Because of this we are still considering whether or not to use ChatControlRed or to look for another solution that does not have these limitations.
It's a pity that two limitations don't allow us to enjoy the rest of all the other features but that's the Minecraft industry nowadays if you want to progress.

I can come to understand your situation over the time but always the best time to do things is _now_.

Thank you very much for your attention.

**Comment by ElBananaa** [comment]
> I have a correction to make. The "players in chat-box" solution is already implemented by another TAB plugin we have. It seems that the one in charge of enabling this function is the "SCOREBOARDS". So it is not up to CCR to take care of this.
> 
> At this point there are two major limitations with this plugin.
> The first one: the plugin doesn't seem to support more than 160-260 players at the same time because of a [packet problem](https://github.com/kangarko/ChatControl-Red/issues/964).
> The second one: it does not support cluster_id or cross-server implementation showing other players from other servers in commands like /tell, /ignore, etc.
> 
> Because of this we are still considering whether or not to use ChatControlRed or to look for another solution that does not have these limitations.
> It's a pity that two limitations don't allow us to enjoy the rest of all the other features but that's the Minecraft industry nowadays if you want to progress.
> 
> I can come to understand your situation over the time but always the best time to do things is _now_.
> 
> Thank you very much for your attention.

Hey!
We completely understand your situation, and it's only up to you to decide whether you'll buy a plugin or not. Unfortunately, as Kangarko said, due to time limitations on his side, this is a bit complicated to implement now.

Regarding the max player limitations, I believe solutions are already being studied, however, due to the changes these solutions may require, it can take a certain amount of time. Anyways, the best way to get a real status on this is to get an answer from kangarko ^^

**Comment by kangarko** [comment]
I see how these two limitations pose an inconvenience for larger networks. I have scheduled extra time in the coming days until Sep 1st to have a look and try to rewrite our cross server synchronization. Keeping this open for future communication.

**Comment by 7wOv6ySCjo** [comment]
> I see how these two limitations pose an inconvenience for larger networks. I have scheduled extra time in the coming days until Sep 1st to have a look and try to rewrite our cross server synchronization. Keeping this open for future communication.

Thank you kangarko, good work. It will be worth it because it will be the best cross-server solution. Good luck.

**Comment by kangarko** [comment]
@7wOv6ySCjo got it working at a early alpha stage, I can send you a test build once it is stable and tested by myself

**Comment by kangarko** [comment]
Implemented and scheduled for release today as beta, please post bug reports below this comment and I will get a notification.
