### ISSUE TITLE
1.17.1: Message Wrong?

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#1222]
Hey I dont think the anti-spam message is meant to look like this
<img width="515" alt="Screenshot 2021-08-10 at 11 18 59" src="https://user-images.githubusercontent.com/73852683/128852140-e32e8beb-9169-4d57-9263-ce0573addc92.png">

**To reproduce**
Sent a message
Sent a message again within the 3 seconds
Message sent to player

_Also different question but how is data stored if I didn't use mysql?_

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: false

**Comment by kangarko** [comment]
Reset your Checker section of localization/messages_en.yml by removing it.
