### ISSUE TITLE
1.16.5: Missing JavaScript library

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1225]
Hi there, when executing ingame command "/spy menu" the console outputs a few java script errors. See picture below:
![image](https://user-images.githubusercontent.com/10013800/129116818-b8783221-7a52-484d-82b7-b53d0ed0000c.png)

so for each item in the invenory of the ingame GUI spy menu i get the error: 
"Warning: Not running script because JavaScript library is missing (install Oracle Java 8 or 11)"
Printed in the console.

i Do have the dependency "NashornPlus-1.1.0.jar" installed and it is working. see picture below:
![image](https://user-images.githubusercontent.com/10013800/129117005-c370e88e-ad55-4bab-8f7c-2ec4bdd8d552.png)

functionality of the buttons do work though, when clicking items in the menu the spy function for that item does toggle.

Minecraft Version: Papermc 1.16.5 Java 16
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey!
I believe this issue is related to FeatherBoard, as said in one of your previous issue (c.f. #1198). I'd suggest trying what Kangarko said there for now ^^

**Comment by donvdp** [comment]
roger that, thanks for the quick reply !

**Comment by kangarko** [comment]
Really strange, going to try reproducing myself in a few days with Featherboard..

**Comment by ElBananaa** [comment]
Hey!
Just wanted to let you know that, after running tests on my end for another issue, I noticed that I don't have the following error.
This was tester on a completely fresh local (Windows 10 computer with Java 16.0.2) setup with updated plugins, the very latest version of Featherboard.
The files (without ChatControlRed & Featherboard jars) can be found on the issue mentioned above this message).
This is the latest.log file : https://gist.github.com/ElBananaa/2ebcef9beb0bdcd34247deb83d31a71f

**Comment by donvdp** [comment]
here are my specs

![image](https://user-images.githubusercontent.com/10013800/129925824-8f69109f-66a7-4836-a009-d82ab5571e23.png)
![image](https://user-images.githubusercontent.com/10013800/129925983-b7c7b628-3c58-4e1c-b266-9c57d7826495.png)
![image](https://user-images.githubusercontent.com/10013800/129926032-f057df7b-1dbe-4f49-8410-18a035802b60.png)

**Comment by kangarko** [comment]
Still haven't received access to FeatherBoard, will keep an eye on this and comment below.

If Banana wasn't able to reproduce on a fresh install with FeatherBoard, NashornPlus and ChatControl, it may also indicate the Java distro you're using may be at the cause. Try using Oracle Java 16 JDK, not OpenJDK or any other fork if any.

**Comment by Maximvdw** [comment]
Featherboard 5 fixes this issue. It will download nashorn according to the spigot library api under the scope of the class loader that loads the Plugin.

**Comment by kangarko** [comment]
@Maximvdw the problem is that we also download Nashorn through and load it as plugin mineacademy.org/nashorn, so in theory the user could just remove our plugin and use the library that you load that spigot makes available for all plugins

**Comment by donvdp** [comment]
i am already running Featherboard 5.

![image](https://user-images.githubusercontent.com/10013800/130374925-fd31e441-e08e-4bfe-aa65-46808c8c083a.png)

**Comment by Maximvdw** [comment]
Spigot introduced the library api to avoid such issues, when using it on a Plugin level you basically load the library for all plugins without versioning. My suggestion would be to follow the Library api that was introduced in 1.16.5.

AFAIK the library api is on a Plugin level and does not add it to the class loaders of all plugins. Maybe you could use the library api as well instead?

**Comment by kangarko** [comment]
Thanks Maxim, I will use the library API starting the next version. Then you can remove NashornPlus.jar and just use FeatherBoard and our plugin.

**Comment by Maximvdw** [comment]
To give some insight: I myself use the library api -> check for the class to be loaded at runtime - if no I download it the old fashion way using URLClassLoader reflection (e.g. when the user is using a version below 1.16.5)

For completeness for others: https://www.spigotmc.org/threads/spigot-bungeecord-1-17-1-17-1.510208/#post-4184317

**Comment by kangarko** [comment]
Thanks for sharing! We will still keep NashornPlus library around for edge cases (e.g. user has Java 16 installed for Minecraft <1.15) but the libraries extention to Spigot API solves the problem for the vast majority of users.
