### ISSUE TITLE
1.16.5: multiple join messages

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1226]
Hi there, i have

When players join the server there are 2 join messages.
1: the default yellow "<player> joined the game." message
2: the message from the join.rs file in ChatControlRed/messages filder
![image](https://user-images.githubusercontent.com/10013800/129175330-4c9df2a0-e174-4aa4-9491-108bd21b82e1.png)

I do have Essentials installed but put that listeren to "lowest" to prevent essentials from overwriting the join message.
I have also put the ChatControlRed Listeren to "HIGHEST". but this also does not seem to be doing the trick.

Could this possible by a bug ?

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

My Plugins:
![image](https://user-images.githubusercontent.com/10013800/129175787-218e4114-a4fd-4c7a-bb7a-8731b20fb8c5.png)

join.rs file: https://pastebin.com/HJt4yQ31
settings.yml file: https://pastebin.com/3ug9VUzu

**Comment by ElBananaa** [comment]
> Hi there, i have
> 
> When players join the server there are 2 join messages.
> 1: the default yellow " joined the game." message
> 2: the message from the join.rs file in ChatControlRed/messages filder
> ![image](https://user-images.githubusercontent.com/10013800/129175330-4c9df2a0-e174-4aa4-9491-108bd21b82e1.png)
> 
> I do have Essentials installed but put that listeren to "lowest" to prevent essentials from overwriting the join message.
> I have also put the ChatControlRed Listeren to "HIGHEST". but this also does not seem to be doing the trick.
> 
> Could this possible by a bug ?
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> My Plugins:
> ![image](https://user-images.githubusercontent.com/10013800/129175787-218e4114-a4fd-4c7a-bb7a-8731b20fb8c5.png)
> 
> join.rs file: https://pastebin.com/HJt4yQ31
> settings.yml file: https://pastebin.com/3ug9VUzu

Hey!
I am unable to reproduce your issue on my side.
Could you please try to reproduce it on a test server with only chatcontrol, essentials and the needed depebdencies (vault, protocolLib, nashornplus), and let us know if it changes anything.
If it does, then it most likely means that one of your plugin might be breaking the behavior of the rules system, I believe.

**Comment by donvdp** [comment]
after the tedious process of trial and error with each of my plugins I have noted that the essentials plugins were the cause of this double login message bonanza.

for reference, on installing i used the latest version of essentials:
- EssentialsX-2.19.0-dev+232-b84207f
- EssentialsXChat-2.19.0-dev+232-b84207f
- EssentialsXSpawn-2.19.0-dev+232-b84207f

yesterday there were 15 improvements and new releases so ive updated to versions:
- EssentialsX-2.19.0-dev+248-1179caa
- EssentialsXChat-2.19.0-dev+248-1179caa
- EssentialsXSpawn-2.19.0-dev+248-1179caa

And now its working propperly.

cause and effect are not always apparent so im sorry for spamming you guys with this issue.

**Comment by donvdp** [comment]
i spoke too soon, This issue still persists. I dont know what is causing this issue. im testing right now.

**Comment by donvdp** [comment]
After disabeling the essentials plugin this problem is gone, but i need essentials, since im basing allot of features on my server on it. 

I dont know if i need to keep this ticket open or start one in essentials, but it seems to me that ChatControlRED should overwrite the join message right ?

Extra info: This is only the join messages, quit and death and such are not affected.

I have the listener of ChatControlRed on "HIGH" and the listener for essentials "lowest"

essentials config:
![image](https://user-images.githubusercontent.com/10013800/129461961-1841eeff-700a-45f4-b2bb-e81d5a966d90.png)

ChatControlRed config:
![image](https://user-images.githubusercontent.com/10013800/129461969-731e6b61-d509-4162-9ec5-e65a05e397c1.png)

**Comment by ElBananaa** [comment]
> After disabeling the essentials plugin this problem is gone, but i need essentials, since im basing allot of features on my server on it.
> 
> I dont know if i need to keep this ticket open or start one in essentials, but it seems to me that ChatControlRED should overwrite the join message right ?
> 
> Extra info: This is only the join messages, quit and death and such are not affected.
> 
> I have the listener of ChatControlRed on "HIGH" and the listener for essentials "lowest"
> 
> essentials config:
> ![image](https://user-images.githubusercontent.com/10013800/129461961-1841eeff-700a-45f4-b2bb-e81d5a966d90.png)
> 
> ChatControlRed config:
> ![image](https://user-images.githubusercontent.com/10013800/129461969-731e6b61-d509-4162-9ec5-e65a05e397c1.png)

Hey!
Could you please try to reproduce the issue under the latest EssentialsX stable build?
Also, try increasing chatcontrol's listener priority to see if it helps.
Here are some more informations about it : https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

**Comment by donvdp** [comment]
Hi there El Banana,

Ive set the listener to "HIGHEST" 
![image](https://user-images.githubusercontent.com/10013800/129474813-a8394eb8-065c-498b-87cb-c85c44326e58.png)

And changed essentialsx version to the stable 2.18.2.0 build.
![image](https://user-images.githubusercontent.com/10013800/129474795-73176554-87d1-4e15-8e59-390ac964696d.png)


unfortunately as you can see the yellow "Donssie joined the game" is still there.

**Comment by ElBananaa** [comment]
> Hi there El Banana,
> 
> Ive set the listener to "HIGHEST"
> ![image](https://user-images.githubusercontent.com/10013800/129474813-a8394eb8-065c-498b-87cb-c85c44326e58.png)
> 
> And changed essentialsx version to the stable 2.18.2.0 build.
> ![image](https://user-images.githubusercontent.com/10013800/129474795-73176554-87d1-4e15-8e59-390ac964696d.png)
> 
> unfortunately as you can see the yellow "Donssie joined the game" is still there.

Hey!
Alright, I think I found the issue.
Please try to remove EssentialsXChat. Didn't notice this one was present until I saw your latest screenshot. Having two plugin handling the chat isn't a really good idea. Removing it should fix the issue, and you'll still be able to use all essentialsx features

**Comment by donvdp** [comment]
Hi there El Bananaa, i do not want to disable the EssentialsXChat.jar file because ChatcontrolRed handles the /nick different. 

But for sake of argument i will test this for you.

Unfortunatly what you suggest does not work. it realy is a bugg in ChatControlRed. Can you fix it ?

![image](https://user-images.githubusercontent.com/10013800/129522073-5096d584-3ce5-40f9-84be-a80f67147971.png)

**Comment by ElBananaa** [comment]
Hey
I'm kinda curious, which version of Java are you using on your server?

EDIT: After running tests on a fresh install, with and without EssentialsXChat, I am unable to reproduce your issue.

Without EssentialsXChat:
![image](https://user-images.githubusercontent.com/53318613/129594164-a58efa75-3f67-4aa8-95b1-990234765b30.png)

With EssentialsXChat:
![image](https://user-images.githubusercontent.com/53318613/129594286-b33d681b-c9e4-4ab4-b7be-f0728bb7df92.png)

So, I don't think this bug is caused by ChatControlRed.

**Comment by donvdp** [comment]
Im runnig the prison server in a java 16 enviroment. And my others servers that are having the same issue are running on java 14.

All are running in a docker with pterodactyl.

We have upgraded from being a long time chatcontrol pro user to chatcontrolred. On our survival, skyblock and factions servers the only upgrade we did is change the chatcontrol plugin. 

The prison server running java 16 is a pilot for the upcomming mandatory upgrade to java 16 for mc 1.18 and is completely new.

Tonight i tested the switching off of the chatcontrolred plugin and reactivated the chatcontrolpro plugin. This problem does no longer appear. So it seems to me that this problem is surrounding the chatcontrolred plugin. Im sorry that you could not reproduce the results on your own. But we have the problem.

Would you recommend us asking for a refund? Since we do not seem to be finding the cause of the problem?

**Comment by ElBananaa** [comment]
> Im runnig the prison server in a java 16 enviroment. And my others servers that are having the same issue are running on java 14.
> 
> All are running in a docker with pterodactyl.
> 
> We have upgraded from being a long time chatcontrol pro user to chatcontrolred. On our survival, skyblock and factions servers the only upgrade we did is change the chatcontrol plugin.
> 
> The prison server running java 16 is a pilot for the upcomming mandatory upgrade to java 16 for mc 1.18 and is completely new.
> 
> Tonight i tested the switching off of the chatcontrolred plugin and reactivated the chatcontrolpro plugin. This problem does no longer appear. So it seems to me that this problem is surrounding the chatcontrolred plugin. Im sorry that you could not reproduce the results on your own. But we have the problem.
> 
> Would you recommend us asking for a refund? Since we do not seem to be finding the cause of the problem?

You're free to do whatever you want. If you'd like to be refunded, then feel free to reach kangarko on his email : matej@minecademy.org
If you'd rather wait for him to see if there's anything he can do about it then you're free to wait a few days to see if there's anything he can do.

**Comment by donvdp** [comment]
While i wait for Kangarko there must be something that i can do.

Perhaps you coulds share your files with the clean install ? Then i can compare them with my server?

**Comment by donvdp** [comment]
I have some time available today and went forward to see if i can get a problem free 'fresh server' just like you El Bananaa.

Here is what i have done:

1) create new server, i used the same versions as my other server. Java 16 PaperMC version 1.16.5 # 783.
![image](https://user-images.githubusercontent.com/10013800/129727416-6d17667c-7d69-4b8d-aff8-47b32697100d.png)
![image](https://user-images.githubusercontent.com/10013800/129727468-e93beb88-e195-411e-b5c1-1e838a2d77c1.png)
![image](https://user-images.githubusercontent.com/10013800/129727496-90a751b9-3523-4034-9d06-a90148eab164.png)

2)  do a first run to check if everything works out of the box. ofcourse it did.

3) install all mandatory plugins + essentialsX

![image](https://user-images.githubusercontent.com/10013800/129727624-fe0017fe-dc3b-4eb5-a5da-6ce10862902f.png)
![image](https://user-images.githubusercontent.com/10013800/129727639-2ad0a779-4e78-49ff-a30f-d0952c20c301.png)

4) complete the ChatControlRed 10.5.4 tour

5) edit join.rs file to contain my custom join message
![image](https://user-images.githubusercontent.com/10013800/129729098-7e54f3d1-cc2d-4c50-9634-60e0e00eb4a4.png)

6) edit the settings.yml file to set the joinmessage to be controlled by ChatControlRed.
![image](https://user-images.githubusercontent.com/10013800/129729183-a656ce3d-a70b-4399-90e2-304d0547407b.png)

7) reboot server. just in case (i knows its not mandatory)

8) test join/leave with my test user "Donssie".
![image](https://user-images.githubusercontent.com/10013800/129729311-12e01c4e-ebce-40dd-a260-06aecff71890.png)

The join messages seem to work just fine now. And now to add all the plugins that i use on my lava 16 prison server:
![image](https://user-images.githubusercontent.com/10013800/129729482-75480b5f-9114-4bac-b9de-cd66bf054751.png)


After adding each plugin i will reboot the server and test join/leave with my test account to see when this goes haywire. This might take some time lol. ill edit this comment once done.

Continuing adding plugins one by one:
1) FeatherBoard-5.0.3b.jar - no errors 
CONSOLE ERRORS:

![image](https://user-images.githubusercontent.com/10013800/129739381-8158e3ea-6a61-4c78-9956-2f3e376b3ae1.png)
but this is known and kangarko is testing this in ticket #1225

2) helper # 363.jar  - no errors
3) CMILib1.0.3.5.jar - no errors
4) UltimateStatistics-b81.jar - no error
5) worldedit-bukkit-7.2.6-beta-02.jar - no errors
6) worldguard-bukkit-7.0.5-dist.jar - no errors
7) WorldGuardExtraFlags.jar - no errors
8) Boss-3.10.6.jar - no errors
9) Citizens-2.0.28#6.jar - no errors
10) CoreProtect-20.1.jar - no errors
11) CrazyCrates[v1.10.1] # 109.jar - no errors
12) UltraPrisonCore-1.4.9-BETA.jar  - **ERROR**

![image](https://user-images.githubusercontent.com/10013800/129760900-23c2f67a-e28c-4db4-a84c-887cadbd911f.png)

So UltraPrisonCore uses a dependency called "Helper" --> JAR: helper # 363.jar


ok im cleaning the server and starting with a fresh install. executing steps 1 thru 8 again. and then only adding this UltraPrisonCore and its dependencies: 1) Helper, 2) Worldguard and 3) Worldedit plugin. See if this reproduces it.

Negative: Having a clean setup with below plugins does not reproduce the double join message problem.... im so confused..

overview of all active plugins:
![image](https://user-images.githubusercontent.com/10013800/129738118-521ba014-b2b5-4caa-929c-8f6bd73e6df0.png)
![image](https://user-images.githubusercontent.com/10013800/129738147-5a11927f-577d-4224-89bb-d7d04aa073d3.png)

Since this does not reproduce it i will continue to add other plugins from the list above untill i get the error again:
1) featherboard - no errors (only console error)

Again after adding FeatherBoard-5.0.3b.jar i notice the Console outputting the ChatControlRed Missing java version/distribution error (see screenshot below). Featherboard and ChatControlRed seem to be clashing somewhere, but the join messages still appear to be working so moving on.

![image](https://user-images.githubusercontent.com/10013800/129738698-b9d9df57-3a75-48f6-82ab-1454a3c7f711.png)

2) CMILib1.0.3.5.jar - no errors
3) Boss-3.10.6.jar - no errors
4) Citizens-2.0.28#6.jar - no error
5) WorldGuardExtraFlags.jar - no error
6) UltimateStatistics-b81.jar - no error
7) CrazyCrates[v1.10.1]# 109.jar - no error
8) CoreProtect-20.1.jar - no error

![image](https://user-images.githubusercontent.com/10013800/129741895-a37e5920-8e27-4d8b-90d0-9521d37bf832.png)

So at this point i am back to the same level of plugins as before. And now i dont have the double join message... i have no idea what is going on here, but ill continue with my list of 57 plugins from the prison server untill i get the error again.

9) JetsPrisonMines-4.2.5.jar - no error
10) InteractiveBoard-14.1.jar - no error
11) BungeeTabListPlus_BukkitBridge-3.5.0-b1105.jar - no error
12) armorstandeditor-1.16-25.jar - no error
13) AutoRestart-v4.2.1.jar - no error
14) nbt-api-2.8.0.jar - no error
15) GadgetsMenu-5.0.4.jar - no error
16) SelectionVisualizer3.0.5.0.jar - no error
17) LibsDisguises-10.0.26-Premium.jar - no error
18) HolographicDisplays-2.4.9.jar - no error
19) HolographicExtension-1.10.9.jar - no error
20) DeluxeMenus-1.13.3-Release.jar - no error
21) DiscordSRV-Build-1.23.0.jar - no error
22) CoinFlipper.jar - no error
23) GSit-6.0.2.0.jar - no error
24) HeadDatabase-4.14.1.jar - no error
25) LevelTools-1.6.5-SNAPSHOT.jar - no error
26) LiteBans-2.7.5.jar - no error
27) LuckPerms-Bukkit-5.3.55.jar - no error
28) MVdWPlaceholderAPI-3.1.1.jar - no error
29) Minepacks-2.4.2.jar - no error
30) MyCommand-5.7.1.jar - no error
31) nuvotifier-2.7.3.jar - no error
32) RedisConnect-1.3.jar - no error
33) spark-1.6.1.jar - no error
34) TAB v2.8.8.jar - no error
35) VoteParty-2.27.jar - no error
36) QuickShop-4.0.5.0.jar - no error
37) CraftingStore.jar - no error
38) OpenInv-4.1.8.jar - no error
39) PlayTimes-1.3.4.jar - no error
40) ServerHub.jar - no error
41) ServerSelectorX-Connector-2.1.2.jar - no error
42) TradeSystem_v1.2.1.jar - no error
43) PlotSquared-Bukkit-6.0.7-Premium.jar - no error

Together with the already 'clean server' loaded 14 plugins thats 57 total. All plugins loaded and still no duplicated join messages error.
![image](https://user-images.githubusercontent.com/10013800/129750606-c58a4af2-352a-465a-8436-5d409aac9b95.png)
redist and discordsrv = red because they arnt configured propperly.


So possibly this has to do with the sequence in wich i add the plugins to the server. so ill go ahead and remove chatcontrolred and reboot the server. then i will re-add chatcontrolred again and reboot again. see if that makes a change.

Result: Everything continues to work fine. omg i dont know how to reproduce this..

Trying to disable essentialsx and rebooting, then enabeling essentialsx again and rebooting..

result: im a nerd. and i cant find how to break it anymore..

Going back to my first attempt where i added 11 plugins and broke it. Because now im doubting everything in my life, and starting to blame that realy good spacecake that i ate before...

CLEAN SERVER:
![image](https://user-images.githubusercontent.com/10013800/129754202-3c8a71f3-a91d-4d57-ac97-a8aa60e68aa6.png)
![image](https://user-images.githubusercontent.com/10013800/129754265-45390328-d921-47d3-a6e9-29c671527d70.png)

so ive not been able to reproduce this issue with a clean installation of all the plugins. and the reproduction of the problem above in my first attempt i also wasnt able to reproduce for a second time. This is some magic mushroom shit right here...

So next ill start with essentials to use my 'bad' servers'config file and edit the settings one by one. reloading /rebooting the server everytime i made a change. I have made about 50 changed to the stock essentials config.yml file so this will take me some time:

Result: i was not able to reproduce the error anymore. so i left the test server as it is. up and running. perhaps this is a bug that will unfold over time ? i dont know anymore.. :(

**Comment by ElBananaa** [comment]
Hey!
Thanks for the **really** extensive tests.
Here's the setup I used to try to reproduce your issue. (I volontarily CHC-Red jar file since it's a premium & closed-source plugin, but I'm using the very latest version available on McMarket. As for Java, I'm using Java-16.0.2 for Windows x64 (which can be found here: https://www.oracle.com/java/technologies/javase-jdk16-downloads.html)
https://we.tl/t-S70n1n5NpX

EDIT: I'm also unable to reproduce any issue with Featherboard.

**Comment by donvdp** [comment]
thanks ! for your files. 

Since im not able to reproduce thus 'bug' im not sure how to call it.
But i still have it on my origional servers, and i found a way to temporarily fix this issue. 

By doing "/essentials reload" ingame the double join messages no longer show. However when i reboot the server i do get the double join messages again.

**Comment by ElBananaa** [comment]
> thanks ! for your files.
> 
> Since im not able to reproduce thus 'bug' im not sure how to call it.
> But i still have it on my origional servers, and i found a way to temporarily fix this issue.
> 
> By doing "/essentials reload" ingame the double join messages no longer show. However when i reboot the server i do get the double join messages again.

Did you copy your EssentialsX files on your test server, or did you let the jar file generate new files?

**Comment by donvdp** [comment]
let it generate new ones. 

I have found the error after trial and error pahhh. been at it since 1500u and its almost 0100u now :'-)

What is causing this error seems to be essentialsX. When changing the "allow-silent-join-quit" variable the unwanted join message appears. I have toggled this variable a few times and rebooted the server and i can definetly say that this is the root cause. ive disabled this functionality since i am the only one using it on the server and reported this bug to essentials.

OMG what a work was this and i am REALY realy sorry for bothering you guys with this error.

New fresh config
![image](https://user-images.githubusercontent.com/10013800/129810436-721b2cb4-02f3-483f-bca1-81364bb90359.png)

Old config
![image](https://user-images.githubusercontent.com/10013800/129810442-d8240f77-94a4-4b8e-81b6-6153f0a7531c.png)

**Comment by ElBananaa** [comment]
It's alright. I'm glad you found a way to fix your issue :)

**Comment by kangarko** [comment]
Holy crap that was ungodly amount of testing and debugging, thanks @donvdp for the patience! I will put a notice to ChatControl if allow-silent-join-quit is on true so that people don't have to waste their time and know that it may cause issues if being enabled.
