### ISSUE TITLE
1.16.5 : Possible to disable a task ?

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1227]
Plugin version : 10.5.3
Minecraft Version: 1.16.5 (Airplane)
MySQL: false
BungeeCord: false (my server is under velocity, but bungeecord is FALSE in my config

I got a task "BungeeSyncTask" in spark sometimes, I don't know why, as I don't use bungeecord features at all.
<img width="315" alt="Screenshot_5527" src="https://user-images.githubusercontent.com/31826333/129277739-6751c503-bd5d-43b4-83fb-133884b67a49.png">

Debug : 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6978891/debug.zip)

**Comment by kangarko** [comment]
Thanks, I will disable it when bungee is off!
