### ISSUE TITLE
1.16.5 possible dupe messages in discord?

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1229]
Hi there. me again. sorry for spamming your git lately

I’ve linked a discord channel to and ingame channel "admin". but now I sometimes receive duplicated discord messages inside discord, whenever I send messages from discord to minecraft ingame.

So, when I send an adminchat ingame (via command: /chc send admin <message>) it gets received in discord just fine. that works all fine!

When I send a message from discord to minecraft I sometimes get duplicated messaged back in discord. Sometimes it’s just 1, sometimes its 5, and it can be anywhere in between.

At first, I thought I might be at fault with the discord SRV plugin. so, I went over there and submitted a ticket. But they tell me it’s probably being forwarded by my ingame chat handler (that’s ChatControlRed). It got a bit technical so in order for me to get a sense of things i made a small drawing, outlining my setup. 

In an attempt to understand how the data packets flow I drew a few lines. I don’t know if they are correct but at least I’ve tried haha

![image](https://user-images.githubusercontent.com/10013800/129390293-1671e7b7-0fb9-4eae-b229-8b1fd42ce96e.png)

what i see in discord when i tried to send a few messaged from discord to minecraft:

![image](https://user-images.githubusercontent.com/10013800/129390917-4b54dc88-a5d8-4a6d-8d21-fcaf9fb3e7ea.png)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by WolverStones** [comment]
https://github.com/kangarko/ChatControl-Red/issues/1139

**Comment by donvdp** [comment]
i know its related WolverStones, but unlike that post 1139 i already use discordSRV in order to atempt to fix the duping. but it doesnt seem to work.

**Comment by donvdp** [comment]
Discussed with the DiscordSRV people on there discord, but they refer me to ChatControlRed developers. See chat from below.

![image](https://user-images.githubusercontent.com/10013800/129462520-7a2660ad-6409-4b3f-9868-3876fc608c2b.png)

**Comment by ElBananaa** [comment]
Hey!
Sorry for the delay!
Unfortunately, I don't know much about DiscordSRV integration.
I'd suggest waiting for Kangarko to take a look at this issue in a few days ^^

**Comment by donvdp** [comment]
Ok, ill wait =) thanks for the update!

**Comment by donvdp** [comment]
small bump ?

**Comment by kangarko** [comment]
Let's continue at https://github.com/kangarko/ChatControl-Red/issues/1205
