### ISSUE TITLE
Error on chat

### ISSUE THREAD

**Issue by Qballl** [kangarko/ChatControl#123]
Im getting this error http://pastebin.com/xXGMf1nZ when players chat and chat doesnt get formatted. Please help

**Comment by ThemInspectors** [comment]
You should have more evidence, like Vault version, permission plugins w/ version And any other chat managers

**Comment by kangarko** [comment]
Please provide me your settings.yml
Are you using other plugins that format chat?

**Comment by Qballl** [comment]
Here is the settings http://paste.md-5.net/veqolucoyo.coffee and all other chat formatting plugins have the formatting set to false

**Comment by kangarko** [comment]
Your configuration seems disorded, as it contains parts from the premium plugin and yet you are on the free version. Please regenerate it.

**Comment by Qballl** [comment]
Ok

**Comment by Qballl** [comment]
Well regening the config fixed it
