### ISSUE TITLE
1.17.1: Messages sent to partychat, send to chatc

### ISSUE THREAD

**Issue by CrispyDairy** [kangarko/ChatControl#1230]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false
![image](https://user-images.githubusercontent.com/81482501/129416847-cae9b00a-4f80-42fb-98a0-7d2e834a7f21.png)
So, messages that I sent to partychat with it toggled on, also send to chatc standard channel. I've set listener priority to: Chat_Listener_Priority: LOW
But its still doing it.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1
> MySQL: false
> BungeeCord: false
> ![image](https://user-images.githubusercontent.com/81482501/129416847-cae9b00a-4f80-42fb-98a0-7d2e834a7f21.png)
> So, messages that I sent to partychat with it toggled on, also send to chatc standard channel. I've set listener priority to: Chat_Listener_Priority: LOW
> But its still doing it.

Hey!
This is pretty weird.
I'd suggest trying to reach PartyChat developer to see if there's anything that can be done on their plugin, and in the meantime, wait for Kangarko to see if he can do anything on chatcontrol's side.

**Comment by CrispyDairy** [comment]
Will do, while I wait, could I help on a quick question. Is it possible to make a specific death message for a certain player's kills.

We're having a lore event on our server, where I'm acting like a boss. So i want to set the kill message that sends when I kill a player, to not include my name.

Don't know if that explanation made sense lol

**Comment by ElBananaa** [comment]
Yes you can, the messages in the death.rs files work like a rule, so you can use these conditions, as example : https://github.com/kangarko/ChatControl-Red/wiki/Messages#death-messages-conditions
Or simply use `require sender script "{player}" == "YouNickHere"` in your custom death message.
Here's an example with one of my death message : 
```rs
group entity-attack-by-cave-spider
require sender script "{player}" == "ElBananaa"
require cause ENTITY_ATTACK
require killer CAVE_SPIDER
message: 
- &8(( &c☠ &8)) &eElBananaa &7was killed by a &eCave Spider&7.
```

**Comment by CrispyDairy** [comment]
So if I wanted it to have a custom death message linked to the killer, I'd just change it to require sender script "{killer}" == "ElBananaa"?

**Comment by ElBananaa** [comment]
> So if I wanted it to have a custom death message linked to the killer, I'd just change it to require sender script "{killer}" == "ElBananaa"?

Yes, that's it.

**Comment by CrispyDairy** [comment]
So, the partychat plugin creator can't help with this, because chatc isn't open source.

**Comment by ElBananaa** [comment]
> So, the partychat plugin creator can't help with this, because chatc isn't open source.

I see.
Ask them to reach Kangarko via email: matej@mineacademy.org so they can sort this out together ^^

**Comment by CrispyDairy** [comment]
Oh forgot to say that I did that, they said they'd get in touch.

Also, does chatc work with essx discord?

**Comment by kangarko** [comment]
Hey! I am not sure what you mean with "essx discord", but I recommend you check out our Wiki regarding our Discord integration to see what we can do. I replied to the email from PartyChat developer, hopefully this gets resolved!

**Comment by CrispyDairy** [comment]
I mean the essentialx discord addon, thinking of switching from discordsrv to that.
Also great!

**Comment by kangarko** [comment]
We will likely not function with Essentials Discord, we only support DiscordSRV for now.

**Comment by kangarko** [comment]
Closing, will follow up with PartyChat developer on this when he comes back, and will let you know in the plugin's changelog when this gets resolved :)
