### ISSUE TITLE
Question about chat formats

### ISSUE THREAD

**Issue by LordYarkan** [kangarko/ChatControl#1231]
To use chat formats, should you use yes or yes channels? o Can the formats be used without the need to use channels?

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by LordYarkan** [comment]
I want to put hex codes to the gradient, is it possible to do it?
https://htmlcolorcodes.com/es/

**Comment by ElBananaa** [comment]
Hey!
No, you need to turn on the channel system to format the chat. If you don't want to enable the channel system, a lot of features won't work (rules, formatting, custom placeholders...)
You can use HEX colors with the plugin, and gradients are only supported in some parts of the format files, however, if you wish to use gradients, you should be able to combine the plugin with the PAPI Gradient expansion (https://api.extendedclip.com/expansions/gradient/).

**Comment by ElBananaa** [comment]
Hi there,
@LordYarkan May I close this issue, or do you need help with anything else?

**Comment by LordYarkan** [comment]
I have a problem, when I set op from the console, it grabs all the chat format prefixes, how can I avoid that?
Will you have a group compatibility mode with luckperms? to avoid all the hassle with permissions?

**Comment by ElBananaa** [comment]
> I have a problem, when I set op from the console, it grabs all the chat format prefixes, how can I avoid that?
> Will you have a group compatibility mode with luckperms? to avoid all the hassle with permissions?

Hey,
I don't understand what's the issue with either the console or the permissions

**Comment by LordYarkan** [comment]
Excuse me, I use Google translate
in formats I add prefix to the vips and more ranges, until there it is fine. but when I put operator mode on the server and I talk in the chat I have all the prefixes of all the ranges that I have created.
Is there a way for chatcontrolred to recognize luckperms groups, without using permissions?
Or is there another way to avoid that?

**Comment by LordYarkan** [comment]
Excuse me, I use Google translate
in formats I add prefix to the vips and more ranges, until there it is fine. but when I put operator mode on the server and I talk in the chat I have all the prefixes of all the ranges that I have created.
Is there a way for chatcontrolred to recognize luckperms groups, without using permissions?
Or is there another way to avoid that?

**Comment by LordYarkan** [comment]
> Hey,
> I don't understand what's the issue with either the console or the permissions

Excuse me, I use Google translate
in formats I add prefix to the vips and more ranges, until there it is fine. but when I put operator mode on the server and I talk in the chat I have all the prefixes of all the ranges that I have created.
Is there a way for chatcontrolred to recognize luckperms groups, without using permissions?
Or is there another way to avoid that?

**Comment by ElBananaa** [comment]
Hey!
It's alright.
Ok, I understand this a bit better now. Yes, you can check for the user's rank instead of checking for a permission.
To do so, in your format file, you can use the `Sender_Condition` variable.
Here's an example:
```yaml
  vip-prefix: 
    Message: "&8[&6VIP&8] "
    Sender_Condition: '''{luckperms_primary_group_name}'' == ''Vip'''
  donator-prefix: 
    Message: "&8[&6Donator&8] "
    Sender_Condition: '''{luckperms_primary_group_name}'' == ''Donator'''
```

**Comment by kangarko** [comment]
Thanks for Banana for answering, I am closing this in good faith it has been resolved, feel free to respond below if you got any more questions.
