### ISSUE TITLE
a question before buying a plugin

### ISSUE THREAD

**Issue by dimactek96** [kangarko/ChatControl#1233]
Good evening, I would like to know before purchasing the plug-in, is there any Russian language in it? How well does this plugin work with the cmi plugin? Thanks in advance for your reply.

**Comment by ElBananaa** [comment]
> Good evening, I would like to know before purchasing the plug-in, is there any Russian language in it? How well does this plugin work with the cmi plugin? Thanks in advance for your reply.

Hey!
No, there's no official translation for Russian.
The plugin should work with CMI if some features such as their chat system, their pm system and other features that are already present in chatcontrolred are disable, so chatcontrol can take over them.

**Comment by dimactek96** [comment]
Are there any instructions for setting up if there is cmi?

**Comment by ElBananaa** [comment]
No, there isn't.
However, we do give a few tips on this page regarding compatibility issues https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues

**Comment by ElBananaa** [comment]
Hey!
@dimactek96 Is there anything else you'd like to know, or may I close this?

**Comment by kangarko** [comment]
Closing, let us know below should you have any more questions.
