### ISSUE TITLE
Admin Chat Suggestion

### ISSUE THREAD

**Issue by Karrade** [kangarko/ChatControl#124]
I think it would be awesome to add an Admin channel that would allow me to remove the last chat plugin that isnt chatcontrol.

command would be: /ac
and that would toggle the admin chat on or off
also configurable chat colors.. example: all &7 configurable color
&7[Modname: &7message&7]

maybe a sound and message when you enter and leave admin chat also a sound when a message is sent in admin chat?

hope this sounds good to you.

**Comment by kangarko** [comment]
Sorry this is little to do with the purpose and idea of ChatControl.
