### ISSUE TITLE
1.17.1: Player is not online on this server even though the player is online

### ISSUE THREAD

**Issue by starwarsfreak219** [kangarko/ChatControl#1240]
After the recent update, when a player is trying to message someone, or does anything that may require the player to be online, it will instead return an error saying that the player is not online, even though said player is online. I noticed this with the command "/motd" and the command for messaging "/msg {player} {message}".

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by starwarsfreak219** [comment]
Plugin version is 10.5.4

**Comment by ElBananaa** [comment]
> After the recent update, when a player is trying to message someone, or does anything that may require the player to be online, it will instead return an error saying that the player is not online, even though said player is online. I noticed this with the command "/motd" and the command for messaging "/msg {player} {message}".
> 
> Minecraft Version: 1.17.1
> MySQL: false
> BungeeCord: false

Hey!
Did the player recently changed their minecraft username? Also, is this a premium or a cracked server? Same thing, is this a premium or a cracked account?

**Comment by starwarsfreak219** [comment]
No name changes were made recently, and the server is set to online mode. Downgrading to 10.5.3 resolved the issue, so I have reason to believe something in the recent update broke it.

**Comment by ElBananaa** [comment]
> No name changes were made recently, and the server is set to online mode. Downgrading to 10.5.3 resolved the issue, so I have reason to believe something in the recent update broke it.

Great!
I'm glad you found a tempfix for your issue.
Let's wait for Kangarko to have a look at it so it can be fixed in the next update ^^

**Comment by Bronzwar** [comment]
i have same issue on 1.12.2. and 1.16.5.

**Comment by kangarko** [comment]
Let's continue here, I am going to dedicate time to this asap later today and in the next few days: https://github.com/kangarko/ChatControl-Red/issues/1220

**Comment by starwarsfreak219** [comment]
Hey @kangarko, I don't believe that the issue you linked is the same issue that I am describing. None of the players have changed their name since joining the server from what I tested. You can view the name change history for both players who were messaging here:
starwarsfreak219: https://namemc.com/profile/starwarsfreak219.1 (never had a name change)
xstunia: https://namemc.com/profile/xstunia.1 (hasn't had a name change in 5 years)

**Comment by kangarko** [comment]
@starwarsfreak219 is this still an issue as of yesterdays release? I am going to spend more work on this today

**Comment by starwarsfreak219** [comment]
Hey @kangarko, unfortunately yesterday's release is giving me a startup error... #1260. Something I did test to see if I could just get the latest working was replacing the .class file that was throwing the issue with an identical one in an older version of the plugin. After doing that, this issue seemed to have been fixed. Will be able to confirm once there is an official release for a fix to #1260.

**Comment by kangarko** [comment]
Looks like MCMarket has corrupted the jar, I will reupload it today.

**Comment by kangarko** [comment]
Okay so todays version should solve the issue but I am working on rewriting this storage system completely, the next release will be out in a few days (we need to test it thoroughly first), you can grab it once it is ready and these problems should be gone. Feel free to reply below if you need any more help.

**Comment by starwarsfreak219** [comment]
Looks like this issue is fixed. Thanks! ☺

**Comment by toxinyx** [comment]
i hate to be an issue but I just upgraded to the latest release and… the issue I reported (and you redirected me here) is still here but now it’s happening for **every** player, including myself, not just players who have changed their username.

**Comment by kangarko** [comment]
Use the next version that will be released today, try changing UUID_Lookup option to false or true to see if one of the options helps.

**Comment by kangarko** [comment]
Also ensure to reload the whole network, stop every server including stopping BungeeCord. Not doing that will result in this problem. Also do not use /bcreload since we had issues reported with it, I am likely going to remove it if it is not possible to fix.

**Comment by toxinyx** [comment]
This new release has seemed to fix it without anything needed changing. Thank you! :)
