### ISSUE TITLE
Smiley Issue

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#1241]
Hi, I'm trying to set up so that when a player types `:)` it sends an emoji placeholder of `:smile:`  instead

this is how its set up

match (:)()
then replace `:smile:`

what happens when `:)` is sent.

[17:23:48 INFO]: MATCH: (:)()
[17:23:48 INFO]: CATCH: `:)`
[17:23:48 INFO]: UPDATE: `:smile:)`
[17:23:48 INFO]: [citysquare] Sir_Craftypants: `:smile:)`

As you can see it keeps placing a closed bracket on the end of the placeholder, is there a way to prevent that?

**Comment by ElBananaa** [comment]
Hey!
Try with `match (:\))()` instead of your current match rule, let me know if it fixes the issue.

**Comment by 00Hrtz** [comment]
> (:\))()

Yeah that removed the closed bracket. 

If i type `:smile:` in chat it appears as 😄 but when this smiley replace does it, it only shows as the placeholder `:smile:`

Any idea how i can correct it?

**Comment by ElBananaa** [comment]
> > (:))()
> 
> Yeah that removed the closed bracket.
> 
> If i type `:smile:` in chat it appears as 😄 but when this smiley replace does it, it only shows as the placeholder `:smile:`
> 
> Any idea how i can correct it?

Which plugin are you using for smileys? I think the issues is caused by the fact that the way messages are checked doesn't support chatcontrol's channel and/or rules system. So if the plugin you use also provides placeholders for smileys (such as %smiley_yourSmileyNameHere%, you could try with it.
If it doesn't, then i'll suggest waiting for Kangarko if he can do anything about it, and, in the meantime, try to reach the other plugin author to see if there's anything they could try on their side. ^^

**Comment by 00Hrtz** [comment]
> 
> 
> > > (:))()
> > 
> > 
> > Yeah that removed the closed bracket.
> > If i type `:smile:` in chat it appears as 😄 but when this smiley replace does it, it only shows as the placeholder `:smile:`
> > Any idea how i can correct it?
> 
> Which plugin are you using for smileys? I think the issues is caused by the fact that the way messages are checked doesn't support chatcontrol's channel and/or rules system. So if the plugin you use also provides placeholders for smileys (such as %smiley_yourSmileyNameHere%, you could try with it.
> If it doesn't, then i'll suggest waiting for Kangarko if he can do anything about it, and, in the meantime, try to reach the other plugin author to see if there's anything they could try on their side. ^^

Itemsadder, tried with {}, %% and :: but none work.

I'm wondering, i think they're sent in console.

**Comment by ElBananaa** [comment]
> > > > (:))()
> > > 
> > > 
> > > Yeah that removed the closed bracket.
> > > If i type `:smile:` in chat it appears as 😄 but when this smiley replace does it, it only shows as the placeholder `:smile:`
> > > Any idea how i can correct it?
> > 
> > 
> > Which plugin are you using for smileys? I think the issues is caused by the fact that the way messages are checked doesn't support chatcontrol's channel and/or rules system. So if the plugin you use also provides placeholders for smileys (such as %smiley_yourSmileyNameHere%, you could try with it.
> > If it doesn't, then i'll suggest waiting for Kangarko if he can do anything about it, and, in the meantime, try to reach the other plugin author to see if there's anything they could try on their side. ^^
> 
> Itemsadder, tried with {}, %% and :: but none work.
> 
> I'm wondering, i think they're sent in console.

Alright, so according to #853 it should work with `{img_name}`. Try this one to see if it helps.
If it doesn't, then let's wait for Kangarko ^^

**Comment by 00Hrtz** [comment]
> {img_name}

It works, awesome.

Thank you very much.
