### ISSUE TITLE
1.16.5 Domain/URL filter problem

### ISSUE THREAD

**Issue by DotDotas** [kangarko/ChatControl#1244]
Hello, im having some troubles with your Domain/URL filter rule. When i type "come" filter blocks that word because of advertisement. I think that's because of the "com" any ideas how to fix it?
Minecraft Version: 1.16.5 PaperSpigot
MySQL: false
BungeeCord: false

**Comment by TheIntolerant** [comment]
Hey, is there any chance you could do ``/chc debug`` and upload the file here, so I can see what is being logged?

**Comment by DotDotas** [comment]
Here u go

**Comment by TheIntolerant** [comment]
In your ``global.rs`` file inside the rules folder of chatcontrol, under ``# Domain/URL filter.``, where you see ``match`` under that rule, edit it so it looks something like

``match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|(?<! )c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|(?<! )m(| +)e|i(| +)o)\b``

**Comment by DotDotas** [comment]
All good now, thank you.
