### ISSUE TITLE
1.17.1: Mail writing causing error in console

### ISSUE THREAD

**Issue by Thornbush42** [kangarko/ChatControl#1245]
Minecraft Version: 1.17.1

MySQL: false 
(but error also shows on our MySQL Bungee setup)

BungeeCord: false 
(but error also shows on our MySQL Bungee setup)

Debug.zip: https://ufile.io/m3geazi0

Plugins used: ChatControlRed (Latest), ProtocolLib (Latest), Vault (Latest), NashornPlus (Latest)
Server software: Paper

Detailed explanation of what's happening: 
I am doing "/mail new", writing text, title it, and upon signing it and the book disappearing, a huge error is shown in the console. I am only using the necessary plugins for ChatControlRed to actually work on this test server, and it has the same behaviour and error after signing as the main fully-packed server has, so it surely cannot be an incompatibility. All this said, the mail does appear to actually send and be received.

Server log if needed: https://pastebin.com/3va2ZyK4

**Comment by ElBananaa** [comment]
Hey!
Thanks for reporting this issue!
Since 1.17, I believe changes were made to how the ItemStack checks work, which causes this issue.
Someone else also reported a similar issue in #1237.
Kangarko will probably have a look at your issue in a few days. ^^

**Comment by kangarko** [comment]
Seems like Book_Anti_Crash option is causing this. I updated to ProtocolLib the latest snapshot and could not reproduce this error: https://i.imgur.com/tVKiMqy.png

As last resort just disable that option in settings.yml, since Spigot should prevent books from crashing server in 1.17.1 anyways
