### ISSUE TITLE
1.16.5 Item variable

### ISSUE THREAD

**Issue by Zalaee** [kangarko/ChatControl#1246]
Is it possible to make so item variable also shows amount of items. For example if i input in chat [item] while holding 5 diamonds it will only show items name but not the amount. Would be better if it said ''5x Diamond''
Minecraft Version: 1.16.5 paper
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> Is it possible to make so item variable also shows amount of items. For example if i input in chat [item] while holding 5 diamonds it will only show items name but not the amount. Would be better if it said ''5x Diamond''
> Minecraft Version: 1.16.5 paper
> MySQL: false
> BungeeCord: false

Hey!
Yes it's totally possible.
Here's a version that does what you want. It also adds color so the text looks a bit better. (If you wish to change the color, simply replace `#42f595` with whatever you want. It supports hex and regular colors.
```rs
Value: |-
    displayName();
    
    function displayName() {
      var item = player.getItemInHand();
      var amount = player.getItemInHand().getAmount();
      var textColor = '#42f595';
    
      var air = Java.type("org.bukkit.Material").AIR;
     
      if (item == null || item.getType() == air) 
        throw "event handled: You must be holding an item to use [item]!";
    
      var metadata = item.getItemMeta();
      
      if (metadata != null && metadata.hasDisplayName())
        return metadata.getDisplayName();
    
      var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
      var name = item.getType().name().toLowerCase().replace('_', ' ').replace('_', ' ');
    
      return textColor + amount + "x " + wordUtils.capitalize(name);
    }
```

Here's a screenshot of how it looks ingame
![image](https://user-images.githubusercontent.com/53318613/129805428-73cf77c1-38a6-4f12-b426-d686ff9c2e4c.png)

**Comment by Zalaee** [comment]
Value: |-
    displayName();
    
    function displayName() {
      var item = player.getItemInHand();
      var amount = player.getItemInHand().getAmount();
      var textColor = '#ABFF7B';
      var textColorr = '#FFF57B';
    
      var air = Java.type("org.bukkit.Material").AIR;
     
      if (item == null || item.getType() == air) 
        throw "event handled: You must be holding an item to use [item]!";
    
      var metadata = item.getItemMeta();
      
      if (metadata != null && metadata.hasDisplayName())
        return textColor + amount + "x " + textColorr + metadata.getDisplayName();
    
      var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
      var name = item.getType().name().toLowerCase().replace('_', ' ').replace('_', ' ');
    
      return textColor + amount + "x " + textColorr + wordUtils.capitalize(name);
    }


Did some changes into it and now it looks like this. The version you gave me didnt work properly with items that have display names. But this one does it correctly. Thanks for help!
