### ISSUE TITLE
Inquiry regarding the tag feature

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1247]
I looked around the wiki but I can't find a full and detailed explanation for the tag feature.

So using "/tag" players can set custom prefix, nuckname, suffix. In "settings.yml" I see there's an option to set a maximum nickname length. Does that apply to prefix and suffix or only the nickname?

What is the intended or practical purpose for letting players set a prefix or suffix?
Are we able to make a list of prefixes and suffixes for players to choose from?

**Comment by kangarko** [comment]
Hey there!

At present you can use our in-built option to limit a nick's length. You should be able to achieve the same for prefixes and suffixes using rules in rules/command.rs, let me know if you are interested in this and maybe I can put together a regex for this.

A practical use for prefix/suffix is purely a decorative function in the game chat. We do not support a list of predefined prefixes/suffixes, would you be interested in this?

**Comment by kangarko** [comment]
Closing to clean our issues log, comment below and I will continue our discussion
