### ISSUE TITLE
1.17.1: Bug with capital checker

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1248]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

When the players minecraft name is fully capitalized, and you start a normal sentence with the first letter being a capital, the plugin will warn the player and remove the capital (Omdat jij became omdat jij because of the players name)

![image](https://user-images.githubusercontent.com/5664135/129915229-8b950295-613e-4c67-8dc8-afc45913bb84.png)

**Comment by kangarko** [comment]
Thanks, will be fixed.
