### ISSUE TITLE
Permissions the see behind the ******

### ISSUE THREAD

**Issue by Mouro001** [kangarko/ChatControl#125]
Hey! I am moderator on a server that use your plugin.
In this server have Founders, Directors, Managers, Admins, Co-Admins and Moderators
I asked to staff why Co-Admins see behind the ****** the bad words and moderators doesnt.
There is some special permission to bypass that?

**Comment by kangarko** [comment]
Yes but the permission can be changed in the handlers.yml file. I would recommend asking the owner.
