### ISSUE TITLE
1.17.1: Players can use ranged chat to spot CMI-vanished players

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1250]
When players use ranged chat they don't see message "There is nobody nearby" when there is some CMI-vanished player around. I tried to fix this using API:

```
@EventHandler(priority = EventPriority.MONITOR)
    public void onGlobalChat(ChatChannelEvent event) {
        if (event.getSender() instanceof Player) {
            Player player = (Player) event.getSender();
            if (event.getChannel().getName().equals("ranged") && !player.hasPermission("cmi.seevanished")) {
                event.getRecipients().removeIf(recipient -> recipient.getGameMode().equals(GameMode.SPECTATOR) ||
                        CMI.getInstance().getPlayerManager().getUser(recipient.getUniqueId()).isVanished());
            }
        }
    }
```
But still, spectator players who ARE NOT vanished are invisible to the player, but VANISHED SPECTATORS become visible. This looks to me like some internal CCR issue. Vanished players are impossible to hide using api.

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
I have edited the code to exclude spectators from visible receivers, that should do the trick.
