### ISSUE TITLE
1.17.1: Players cannot write DMs

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1251]
After updating from 10.5.0 to 10.5.4 players cannot write DMs. They receive message that the player is not online.

https://ufile.io/p16i27p8

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> After updating from 10.5.0 to 10.5.4 players cannot write DMs. They receive message that the player is not online.
> 
> https://ufile.io/p16i27p8
> 
> Minecraft Version: 1.17.1
> MySQL: false
> BungeeCord: false

Hey!
I believe Kangarko put the wrong BungeControl jar file in the latest update. Switch back to ChatControlRed v10.5.3 and BungeeControlRed 3.5.3, and let us know if it fixes the issue.

**Comment by radiant-ai** [comment]
> > After updating from 10.5.0 to 10.5.4 players cannot write DMs. They receive message that the player is not online.
> > https://ufile.io/p16i27p8
> > Minecraft Version: 1.17.1
> > MySQL: false
> > BungeeCord: false
> 
> Hey!
> I believe Kangarko put the wrong BungeControl jar file in the latest update. Switch back to ChatControlRed v10.5.3 and BungeeControlRed 3.5.3, and let us know if it fixes the issue.

Ok, but I don't use Bungeecord messaging and thus I don't have Bungeecontrol

**Comment by ElBananaa** [comment]
> > > After updating from 10.5.0 to 10.5.4 players cannot write DMs. They receive message that the player is not online.
> > > https://ufile.io/p16i27p8
> > > Minecraft Version: 1.17.1
> > > MySQL: false
> > > BungeeCord: false
> > 
> > 
> > Hey!
> > I believe Kangarko put the wrong BungeControl jar file in the latest update. Switch back to ChatControlRed v10.5.3 and BungeeControlRed 3.5.3, and let us know if it fixes the issue.
> 
> Ok, but I don't use Bungeecord messaging and thus I don't have Bungeecontrol

Annnd, that's right. My bad, I was tired 😅

**Comment by starwarsfreak219** [comment]
This is the same issue that I reported a few days ago. #1240

**Comment by kangarko** [comment]
Thanks, update to the latest version and if you still will face this problem please comment on https://github.com/kangarko/ChatControl-Red/issues/1240
