### ISSUE TITLE
Suggestion: Change to advertisement rule in global.rs

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1253]
As discussed in #1207, the person reported things such as "is, co-ord" and "questions, me" triggering the advertisement filter.
As also shown in this picture.
 
https://imgur.com/2Tz7Soa

----

It seems an error was made after a change to the default advertisement rule in either version 10.5.3 or 10.5.4.
As reported in #1244, the default files for advertising will now match words such as "come" etc

After looking into the issue I found the cause.
In ``gloabl.rs`` in the rule for advertisement, after the ``(\.|dot|\(dot\)|-|;|:|,)`` part of the rule, ``\s`` was removed but ``\s?`` should have been removed instead. As a result, the rule no longer requires a ``(dot)`` or ``dot`` or ``.`` etc for a match to occur, resulting in words like ``come`` getting blocked, because of domains ending in **me**

----

while a fix to this would be to also remove the ``?`` I wanted to propose keeping the ``\s?``

The reason I suggest keeping ``\s?`` is mainly because I have personally seen many people do ``example dot com`` etc to try and bypass the chat filter to advertise on servers, while this change will stop the the issue the person at the top reported from from happening, the downside is it will become easier to bypass. 

For example 
``example .com`` will get blocked, but ``example. com`` will no longer get blocked if "\s?" is removed.

I feel it would be more efficient to change how the filter matches based on what the ending part of the domain is, such as **co** and **me**

----

This is an example of the change I am proposing to the advertisement rule.

``
match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|(?<! )c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|(?<! )m(| +)e|i(| +)o)\b
``

In the example above, I added ``(?<! )`` for the **me** and **co** domains so things such as "is, co-ord" and "questions, me" do not trigger the chat filter for advertisements, while still block things such as ``example dot com`` as ``com``, ``net`` etc are more commonly used domains. Therefore this change will not make it easier for people to advertise on servers.

**Comment by kangarko** [comment]
Thank you very much, pulled this change!
