### ISSUE TITLE
1.16.5: cant delete messages anymore after one or two deletes

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1254]
Hi there again :-)

Some of my moderators have been compaining that they were not able to remove ingame messages anymore, after joining the server and testing this a bit i found out that i could delete a few messages and then i wasnt able to delete ingame chat messages aswell.

just to be clear: im talking about the red "X" that you can mouse click on ingame
![image](https://user-images.githubusercontent.com/10013800/130060796-fca3df58-fb5b-4b0d-93eb-80e45a650db4.png)

I havent found any active tickets on this. so i thought ill make one.

After i wasnt able to remove ingame chat messages anymore i OPed myself, even then i was not able to remove messages.
When switching to another server

more details:
Problem occured on my survival world. After reloading the plugin ingame via command "/chatcontrol reload" i was able to use the inline chat remove function again. i have heard about this issue before but kinda ignored it form my mods because i was busy. and since my servers reboot every night i thought it was just my mods not understanding the feature. but now after having seen it myself i think its a bug.

![image](https://user-images.githubusercontent.com/10013800/130061219-6747aba4-4c57-4128-9767-992e2c19c233.png)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

debug files: [https://ufile.io/dbyheien](https://ufile.io/dbyheien)

**Comment by ElBananaa** [comment]
Hey!
I believe this issue may be related to how the plugin currently uses ProtocolLib.
Hopefully this will get patched for the next update ^^

**Comment by ElBananaa** [comment]
Hey!
Quick update regarding this:
I tried on a local test server under both Paper-1.16.5-b786 and Paper-1.17.1-b196 with a completely fresh install (ChatControlRed v10.5.4, NashornPlus v1.1.0, PAPI v2.10.10, ProtocolLib b#531 (https://ci.dmulloy2.net/job/ProtocolLib/531/), Vault v1.7.3 & Java 16.0.2), and I wasn't able to reproduce your issue.

If you don't mind, could you please try to reproduce the issue with the latest ProtocolLib dev build?
Also, in case you're currently using ChatControlRed v10.5.4, please switch back to v10.5.3 since, the BungeeControl jar file provided with ChatControlRed v10.5.4 isn't the right one.

**Comment by donvdp** [comment]
This issue occured all of the sudden and i have not had this anymore since then. So i am not sure how this

Since i dont know how to reproduce this issue i dont know how downgrading to a previous build will affect the issue.

Just in case i have installed the Dev version of ProtocolLib # 531 and also downgraded all my server to use ChatControlRed v10.5.3. Will i be stuck on v10.5.3 ? or can i upgrade to v10.5.5 or higher when it releases ?
Should i keep bungeecord on "BungeeControl-Red-3.5.3.jar" ?

**Comment by ElBananaa** [comment]
> This issue occured all of the sudden and i have not had this anymore since then. So i am not sure how this
> 
> Since i dont know how to reproduce this issue i dont know how downgrading to a previous build will affect the issue.
> 
> Just in case i have installed the Dev version of ProtocolLib # 531 and also downgraded all my server to use ChatControlRed v10.5.3. Will i be stuck on v10.5.3 ? or can i upgrade to v10.5.5 or higher when it releases ?
> Should i keep bungeecord on "BungeeControl-Red-3.5.3.jar" ?

Sorry to ear that, I thought that switching to the latest dev build may help.
Since Kangarko just released CHC-Red v10.5.5 & BungeeControlRed v3.5.5, you can now update to the latest version.

The BungeeControl jar provided in the previous version was simply the wrong jar from what I understood, which is why I told you to use the previous version ^^
Also, afaik, you should always use the bungeecontrol-red version provided with your chatcontrol-red zip file ^^

**Comment by kangarko** [comment]
Closing in good faith this will be resolved today. Let me know below if you will still need more help and I am happy to do so!

**Comment by kangarko** [comment]
I'll be here more often until Sep 1st, then I am out of office for two weeks so I do hope you can set it up to your goals until then so I can help you!

**Comment by donvdp** [comment]
The problem is still here. sometimes we cannot delete messages when clicking on the [x] icon in the ingame chat.
![image](https://user-images.githubusercontent.com/10013800/131534550-7f4642b3-810a-499d-bc33-fe19175b3ef3.png)
when clicking on it the message stay's put. when checking the database its still in there. when asking ingame players if they still see the message the confirm this.

**Comment by ElBananaa** [comment]
Reopening this since the issue hasn't been fixed.
However, you may not get any updates on this until kangarko gets back from vacations (in approx. 16 days)

**Comment by kangarko** [comment]
Interesting. We do cache and give each message a unique ID, maybe that's changing. I will check this after holidays asap!

**Comment by kangarko** [comment]
I'm back home finally, @donvdp let me know if you're still facing this issue, if yes, just to clarify does this happen on messages on the same server, or on messages from another server on the network?

**Comment by donvdp** [comment]
Yes. I am still experiencing this issue.

It happens in both cases

**Comment by kangarko** [comment]
Thanks for confirming and making it easier for me to test. The debug file had expired, may you please reupload? Just in case I missed something I wanted to reopen it to refresh my memory.

**Comment by kangarko** [comment]
So sorry for the inactivity here, it should have been already patched. Closing, lemme know below if you still see it around in the next version.
