### ISSUE TITLE
1.16.5: formatting with external files

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1255]
Hi there, i have a question with formatting and external files.

i have an admin channel that is linked to discord.
i Tweaked arround with the format that i want to use for sending messages ingame to discord and the console. Now i want to transfer that tweaking to an external file.

in the settings.yml file i did the following:
![image](https://user-images.githubusercontent.com/10013800/130061516-9b21a5ad-48f1-4303-8aaa-1d561a3ad5a9.png)

and created the "admin-chat-console" and "admin-chat-discord" file in the "formats" folder:
![image](https://user-images.githubusercontent.com/10013800/130061770-1993c25d-5fa3-4b50-8880-3ca9a5c3f57f.png)

unfortunatly this does not seem to work, Whenever i type something in the ingame admin chat in discord i see this: 
![image](https://user-images.githubusercontent.com/10013800/130061881-36416a64-f118-4f5b-8b24-1a131416dba5.png)

Is what i am trying to do simple not supported or am i just being a newb and im i not doing it right ? 

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by TheIntolerant** [comment]
Basically you format "minecraft to discord" chat directly in the settings file, unfortunately I do not believe you can use a format to format discord chat. 

This also applies to "Format_Console:" too, for "Format_Spy:" you can either format like below or do what you did for "Format:" and use a format file in the formats folder.

Here is an example,
```yml
Format_Discord: "(AdminChat) {player} **>** {message}"

```

P.s. sorry for saying format so many times lol

**Comment by donvdp** [comment]
ok cool, ill just format it in the settings.yml file and not use external files :-) thanks for your reply !

Format :)
