### ISSUE TITLE
1.17.1 Messages_en.ymal issues

### ISSUE THREAD

**Issue by minimuscle** [kangarko/ChatControl#1256]
When I try to do commands, I get errors like this: 
![image](https://user-images.githubusercontent.com/36906641/130194065-e712b0a2-5bb1-49c0-9a49-8602084c817d.png)

It still works mind you, but it quite ungodly. This is on the latest version 10.5.4 - So ignore the version number there, I have another issue I'll post separately regarding that.

**Comment by ElBananaa** [comment]
> When I try to do commands, I get errors like this:
> ![image](https://user-images.githubusercontent.com/36906641/130194065-e712b0a2-5bb1-49c0-9a49-8602084c817d.png)
> 
> It still works mind you, but it quite ungodly. This is on the latest version 10.5.4 - So ignore the version number there, I have another issue I'll post separately regarding that.

Hey!
What's the java version of your server?

**Comment by minimuscle** [comment]
hmm, I'd assume Java 8 but I don't really know, I run it on a host "ExtraVM", this could certainly be the issue though hey, might have to contact them to see about moving to java 14 or something.

**Comment by ElBananaa** [comment]
> hmm, I'd assume Java 8 but I don't really know, I run it on a host "ExtraVM", this could certainly be the issue though hey, might have to contact them to see about moving to java 14 or something.

Since you're under 1.17, i believe your server runs at least under java 15, simply install NashornPlus and it should fix the issue : https://mineacademy.org/nashorn/

**Comment by kangarko** [comment]
Hey there :)

Have you edited with localization/messages_en.yml file? Looks like a malformed key in Channels.Leave.Success_V2, you can just remove the entire Channels section of that localization file, let the plugin regenerate a new one and the problem should go away.

Do you also have any console message about not being able to run javascripts?

PS: @ElBananaa this can have nothing to do with Java version or Nashorn, it may also be just a localization problem :) But yeah if the server lacks the Nashorn library for whatever reason then we fail to parse JavaScript in localization and output this text

**Comment by ElBananaa** [comment]
> Hey there :)
> 
> Have you edited with localization/messages_en.yml file? Looks like a malformed key in Channels.Leave.Success_V2, you can just remove the entire Channels section of that localization file, let the plugin regenerate a new one and the problem should go away.
> 
> Do you also have any console message about not being able to run javascripts?
> 
> PS: @ElBananaa this can have nothing to do with Java version or Nashorn, it may also be just a localization problem :) But yeah if the server lacks the Nashorn library for whatever reason then we fail to parse JavaScript in localization and output this text

Hey!
@kangarko I'm unable to reproduce this issue on a fresh install under paper 1.17.1, with the default english lang file. This is why I assumed NashornPlus was missing ^^

**Comment by kangarko** [comment]
Use the next release coming up later today and do as Banana suggested, ensure you have NashornPlus installed and there is no console errors or logs coming up, if that still wont help please comment below

**Comment by minimuscle** [comment]
This has been fixed can confirm. Nashorn was missing, latest version of both works fine, only recommendation is on the "tour" in chc to write that it is needed, as I didn't know. But thats on me either way.

**Comment by kangarko** [comment]
Awesome, also the next version will no longer require Nashorn, I found out that Spigot added external libraries support to 1.16.5: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/146a7e4bd764990c56bb326643e92eb69f24d27e
