### ISSUE TITLE
1.17.1 (10.5.4) Chat Prefix Issue

### ISSUE THREAD

**Issue by minimuscle** [kangarko/ChatControl#1257]
![image](https://user-images.githubusercontent.com/36906641/130194326-8b312d0a-4c4c-4812-95a6-5ac40c7281f1.png)
As seen in the above image, I do not have read only mode on (I just joined it at the top) I also do not have discord enabled.

This also applies the VIP tag but I suspect that was a permissions error, as I am the owner, and have "*" as my permissions, so I just negated that one, which was easy to do, but the others are controlled via chatcontrol.

**Comment by TheIntolerant** [comment]
Hey, could you please upload the format file you are using for this chat, so it can be reviewed.

**Comment by minimuscle** [comment]
> Hey, could you please upload the format file you are using for this chat, so it can be reviewed.

[messages_en.yml](https://www.mediafire.com/file/3nizzhcgdsagn8m/messages_en.yml/file)

This was auto generated in 10.5.0 as well as 10.5.4

**Comment by minimuscle** [comment]
This is the chat file, generated in 10.5.4
[chat.yml](https://www.mediafire.com/file/0sekzegge6zqxhv/chat.yml/file)

The file in code:

```yml
# !-------------------------------------------------------------------------------------------------!
#                                  Welcome to formats configuration
# !-------------------------------------------------------------------------------------------------!
#
#   A format renders and customizes a message send to player(s). It can be used across our plugin 
#   in many places, such as in channels, rules, commands etc.
#
#   Remember, you can remove or edit all parts below, and create your own ones! A lot options
#   are optional, that means you do not have to specify them at all.
#
#   Each format consists of parts such as "delete-chat" below. Each part can show different hover
#   events etc. or be hidden if sender/recipient has a certain permission, and more.
#
#   All format options except "Message" are optional. If you don't need those, you can remove it.
#
#   Options for each format part:
#   - Message: A simple string what will be shown in the chat. 
#   - Sender_Permission: What permission must the message sender have for this part to show.
#   - Receiver_Permission: Only show this part to the receivers having this permission.
#   - Sender_Condition: JavaScript condition that must return true for sender (use "player" to get
#                       the Player instance from Spigot) for this part to show.
#   - Receiver_Condition: Similar to Sender_Condition but the script will evaluate against each 
#                         receiver and only show this part to those for which condition is true.
#   - Hover: One line or a list of tooltip to show when hovering over this part with your mouse.
#   - Hover_Item: JavaScript with "player" instance as variable that must return a valid ItemStack
#                 to show when hovering over this part (e.g. "player.getItemInHand()")
#   - Open_Url: A one-line message representing a website to open which clicking on this part. 
#   - Suggest_Command: A one-line message that be suggested as command when clicked on this part.
#   - Run_Command: One command (Minecraft only supports one) that will run upon clicking on part.
#   - Insertion: The text to insert into the chat when this component
#                (and child components) are clicked while pressing the shift key.
#   - Inherit: (Limited) A name of another format from another file to import and use.
#   - Inherit_Part: (Limited) A name of another part from this file to import and use.
#   - Gradient: <from> - <to> (such as RED - GOLD or #123456 - #123456) Gradients for MC 1.16+.
#
#   For help and documentation, visit:
#   https://github.com/kangarko/ChatControl-Red/wiki/formats
#
# !-------------------------------------------------------------------------------------------------!

# -----------------------------------------------------------------------------------------
# The default chat format used by chat formatting or in the "standard" channel.
# -----------------------------------------------------------------------------------------

# The parts of this format.
Parts:

  # Show the [X] button only visible to people having permission on 'Receiver_Permission'
  # that enables you to remove chat messages by clicking on them!
  # PS: They are still saved to log and can be viewed with "/chc log".
  # TIP: Give yourself chatcontrol.bypass.spamkick to prevent being kicked when removing mass messages.
  delete-chat:
    Message: '&8[&4X&8] &f'
    Hover: '&cRemove this message from chat for all players.'
    Run_Command: /{label} internal remove {message_uuid}
    Receiver_Permission: chatcontrol.removemessages

  # Show the [VIP] prefix if sender, not receiver like above, has the 
  # permissions. All players will thus see the message.
  vip-prefix:
    Message: '&8[&6VIP&8] '
    Sender_Permission: chatcontrol.group.vip
  
  # Show the [Read] prefix if the receiver is only reading this channel.
  read-prefix:
    Message: '&8[&bRead&8] '
    Receiver_Condition: '''{player_channel_mode_{channel}}'' == ''read'''
  
  # Show the [Discord] prefix if the sender is from Discord (we use our own
  # special variable for this) and add some interactive elements.
  discord-prefix:
    Message: '&8[&bDiscord | {discordsrv_user_top_role_color_hex}{discordsrv_user_top_role_name}&8] '
    Sender_Condition: '{sender_is_discord}'
    Hover: '&bJoin our Discord at discord.gg/nukYhNt'
    Open_Url: https://discord.gg/nukYhNt
  
  # Show the [Outsider] prefix if the sender is not joined in this channel,
  # and is not coming from discord. This happens for example on "/channel send".
  #outsider-prefix: 
  #  Message: "&8[&cOutsider&8] &f"
  #  Sender_Condition: "!{player_in_channel_{channel}} && !{sender_is_discord}"
  
  # Show the [Spy] prefix only to players who receive this message AND are
  # spying in the given channel, enabling them to stop spying by clicking on prefix.
  spies-prefix:
    Message: ''
    Receiver_Condition: '{player_is_spying_{channel}}'
    Hover: '&dClick to stop spying {channel} channel.'
    Run_Command: /{label_spy} toggle chat {channel}

  # Finally, pull the regular player prefix from your permissions plugin using Vault.
  # The + at the end of the variable automatically inserts a space if player has prefix.
  # E.g. "admin" turns into "admin ". If there's no prefix, you won't end with a trailing space.
  prefix:
    Message: '{player_prefix+}'
    Hover:
    - '&7{player_prefix+}{player_nick} {player_suffix}'
    - '&7Ping&8: &f{ping}ms'
    - '&7Rank&8: &f{player_group}'
    - '&7Posted: &f{timestamp}'
    - ''
    - '&7Click to learn more about ranks.'
      # You can also use PlaceholderAPI variables here
      #- '&7First join: &e{player_first_join_date}'
    Open_Url: https://mineacademy.org/project-orion

  # Display a typical player name to players with the given permission. change {player_name} 
  # to {player_nick} to show nick instead. We'll revert to show normal name if player has no nick.
  # To display a name in rainbow colors, uncomment "Gradient". This requires MC 1.16+
  player-name:
    Message: '{player_nick}'
    #Message: "{player_name}"
    #Gradient: RED - YELLOW
    Hover: '&7Click to message.'
    Suggest_Command: '/tell {player_name} '

  # And finally, show the message the player has typed out, prepending it with player's
  # suffix from your permission plugin. If player has custom '/chc color', we append it
  # after the suffix. Even if you remove the suffix, custom colors will still be appended. 
  message:
    Message: '&7: {player_suffix}{message}'
`

**Comment by ElBananaa** [comment]
> This is the chat file, generated in 10.5.4
> [chat.yml](https://www.mediafire.com/file/0sekzegge6zqxhv/chat.yml/file)
> 
> The file in code:
> 
> ```yaml
> # !-------------------------------------------------------------------------------------------------!
> #                                  Welcome to formats configuration
> # !-------------------------------------------------------------------------------------------------!
> #
> #   A format renders and customizes a message send to player(s). It can be used across our plugin 
> #   in many places, such as in channels, rules, commands etc.
> #
> #   Remember, you can remove or edit all parts below, and create your own ones! A lot options
> #   are optional, that means you do not have to specify them at all.
> #
> #   Each format consists of parts such as "delete-chat" below. Each part can show different hover
> #   events etc. or be hidden if sender/recipient has a certain permission, and more.
> #
> #   All format options except "Message" are optional. If you don't need those, you can remove it.
> #
> #   Options for each format part:
> #   - Message: A simple string what will be shown in the chat. 
> #   - Sender_Permission: What permission must the message sender have for this part to show.
> #   - Receiver_Permission: Only show this part to the receivers having this permission.
> #   - Sender_Condition: JavaScript condition that must return true for sender (use "player" to get
> #                       the Player instance from Spigot) for this part to show.
> #   - Receiver_Condition: Similar to Sender_Condition but the script will evaluate against each 
> #                         receiver and only show this part to those for which condition is true.
> #   - Hover: One line or a list of tooltip to show when hovering over this part with your mouse.
> #   - Hover_Item: JavaScript with "player" instance as variable that must return a valid ItemStack
> #                 to show when hovering over this part (e.g. "player.getItemInHand()")
> #   - Open_Url: A one-line message representing a website to open which clicking on this part. 
> #   - Suggest_Command: A one-line message that be suggested as command when clicked on this part.
> #   - Run_Command: One command (Minecraft only supports one) that will run upon clicking on part.
> #   - Insertion: The text to insert into the chat when this component
> #                (and child components) are clicked while pressing the shift key.
> #   - Inherit: (Limited) A name of another format from another file to import and use.
> #   - Inherit_Part: (Limited) A name of another part from this file to import and use.
> #   - Gradient: <from> - <to> (such as RED - GOLD or #123456 - #123456) Gradients for MC 1.16+.
> #
> #   For help and documentation, visit:
> #   https://github.com/kangarko/ChatControl-Red/wiki/formats
> #
> # !-------------------------------------------------------------------------------------------------!
> 
> # -----------------------------------------------------------------------------------------
> # The default chat format used by chat formatting or in the "standard" channel.
> # -----------------------------------------------------------------------------------------
> 
> # The parts of this format.
> Parts:
> 
>   # Show the [X] button only visible to people having permission on 'Receiver_Permission'
>   # that enables you to remove chat messages by clicking on them!
>   # PS: They are still saved to log and can be viewed with "/chc log".
>   # TIP: Give yourself chatcontrol.bypass.spamkick to prevent being kicked when removing mass messages.
>   delete-chat:
>     Message: '&8[&4X&8] &f'
>     Hover: '&cRemove this message from chat for all players.'
>     Run_Command: /{label} internal remove {message_uuid}
>     Receiver_Permission: chatcontrol.removemessages
> 
>   # Show the [VIP] prefix if sender, not receiver like above, has the 
>   # permissions. All players will thus see the message.
>   vip-prefix:
>     Message: '&8[&6VIP&8] '
>     Sender_Permission: chatcontrol.group.vip
>   
>   # Show the [Read] prefix if the receiver is only reading this channel.
>   read-prefix:
>     Message: '&8[&bRead&8] '
>     Receiver_Condition: '''{player_channel_mode_{channel}}'' == ''read'''
>   
>   # Show the [Discord] prefix if the sender is from Discord (we use our own
>   # special variable for this) and add some interactive elements.
>   discord-prefix:
>     Message: '&8[&bDiscord | {discordsrv_user_top_role_color_hex}{discordsrv_user_top_role_name}&8] '
>     Sender_Condition: '{sender_is_discord}'
>     Hover: '&bJoin our Discord at discord.gg/nukYhNt'
>     Open_Url: https://discord.gg/nukYhNt
>   
>   # Show the [Outsider] prefix if the sender is not joined in this channel,
>   # and is not coming from discord. This happens for example on "/channel send".
>   #outsider-prefix: 
>   #  Message: "&8[&cOutsider&8] &f"
>   #  Sender_Condition: "!{player_in_channel_{channel}} && !{sender_is_discord}"
>   
>   # Show the [Spy] prefix only to players who receive this message AND are
>   # spying in the given channel, enabling them to stop spying by clicking on prefix.
>   spies-prefix:
>     Message: ''
>     Receiver_Condition: '{player_is_spying_{channel}}'
>     Hover: '&dClick to stop spying {channel} channel.'
>     Run_Command: /{label_spy} toggle chat {channel}
> 
>   # Finally, pull the regular player prefix from your permissions plugin using Vault.
>   # The + at the end of the variable automatically inserts a space if player has prefix.
>   # E.g. "admin" turns into "admin ". If there's no prefix, you won't end with a trailing space.
>   prefix:
>     Message: '{player_prefix+}'
>     Hover:
>     - '&7{player_prefix+}{player_nick} {player_suffix}'
>     - '&7Ping&8: &f{ping}ms'
>     - '&7Rank&8: &f{player_group}'
>     - '&7Posted: &f{timestamp}'
>     - ''
>     - '&7Click to learn more about ranks.'
>       # You can also use PlaceholderAPI variables here
>       #- '&7First join: &e{player_first_join_date}'
>     Open_Url: https://mineacademy.org/project-orion
> 
>   # Display a typical player name to players with the given permission. change {player_name} 
>   # to {player_nick} to show nick instead. We'll revert to show normal name if player has no nick.
>   # To display a name in rainbow colors, uncomment "Gradient". This requires MC 1.16+
>   player-name:
>     Message: '{player_nick}'
>     #Message: "{player_name}"
>     #Gradient: RED - YELLOW
>     Hover: '&7Click to message.'
>     Suggest_Command: '/tell {player_name} '
> 
>   # And finally, show the message the player has typed out, prepending it with player's
>   # suffix from your permission plugin. If player has custom '/chc color', we append it
>   # after the suffix. Even if you remove the suffix, custom colors will still be appended. 
>   message:
>     Message: '&7: {player_suffix}{message}'
> `
> ```

Hey!
Could you please make sure NashornPlus (https://bitbucket.org/kangarko/nashornplus/downloads/) v1.1.0 is currently installed on your server?

EDIT: The next version should fix issues with the `{sender_is_discord}` variable, so I removed the 2nd part of my message since this isn't needed. Simply update the plugin to the latest version when it gets released, and it should fix the discord prefix issue.
I'm closing this issue, but feel free to keep commenting and tagging (@ElBananaa) me down below if you need anything else ;D

**Comment by minimuscle** [comment]
This is definitely fixed now to confirm, newest version of CHC and Nashorn and the prefixes gone.
