### ISSUE TITLE
1.17.1: ChatControl's api hook is registering 4 minutes after DiscordSRV being fully enabled

### ISSUE THREAD

**Issue by pupshadow** [kangarko/ChatControl#1258]
Minecraft Version: 1.17.1 (paper)
MySQL: false
BungeeCord: false

Hello **DiscordSRV** asked me to direct this issue to you.

When loading a server up after a restart the ChatControl's api hook for DiscordSRV is taking up to 10 minutes to load at times. I wanted to inform you all of this issue I will post the debug below as well as the log link so you can see what I mean.

Debug zip:  https://ufile.io/4w1a7fr6

Log of issue:  https://pastebin.com/49KAmJ0D

**Comment by kangarko** [comment]
Can you confirm that by removing DiscordSRV this issue is gone?

**Comment by pupshadow** [comment]
Looks like it is not DiscordSRV sorry about that I will run more testing on all the plugins on the server when less people are online and update this issue with a comment.

https://pastebin.com/RakPBwBZ

It possibly could be mcmmo so that's the next one I will try.

**Comment by pupshadow** [comment]
So I Just tested it with only your required plugins to run and it seems that Chat Control just takes that long to load by itself.

log file: https://pastebin.com/xk3pHe4Z
Plugins: https://pastebin.com/aieijS9h

**Comment by kangarko** [comment]
Remove your data.db, for some reason you have a large quantities of invalid UUIDs there, I will recheck this.

**Comment by pupshadow** [comment]
All those uuid are correct those uuid are generated by floodgate a cross platform plug-in for geyser. Geyser is a plug-in that allows bedrock and Java client play together on the same server. Is this an issue for that is happening when having a bunch of client on the server with these plugins?

**Comment by pupshadow** [comment]
> Remove your data.db, for some reason you have a large quantities of invalid UUIDs there, I will recheck this.

All those uuid are correct those uuid are generated by floodgate a cross platform plug-in for geyser. Geyser is a plug-in that allows bedrock and Java clients to play together on the same server. Is this an issue that is happening when having a bunch of client on the server with these plugins?

**Comment by kangarko** [comment]
Interesting, I did not know that. Okay what about todays release, is it loading faster?

**Comment by pupshadow** [comment]
> Interesting, I did not know that. Okay what about todays release, is it loading faster?

Its working great now after the newest update you released yesterday. Sorry about the late reply I was just now able to update the server.
