### ISSUE TITLE
1.16.3 | Cannot spy books

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#126]
When a player writes a book, I cannot see it as a moderator.  It will run a command such as: /chc internal book c0792276-6f35-4779-b965-437cbc22baa6 when I click the spy message, but the book that opens to me just says `* Invalid Book Tag *` and will not display any of the book text.

This is on Paper 1.16.3.

**Comment by broken1arrow** [comment]
If i´m not wrong has this work before. I can confirm it not work (use plain text). 

I use 1.16.4

**Comment by kangarko** [comment]
Thanks, opened a help ticket on forums: https://www.spigotmc.org/threads/opening-book-produces-invalid-tag.473487/

**Comment by broken1arrow** [comment]
Use version 10.1.0 and I get same thing.

**Comment by kangarko** [comment]
Fixed
