### ISSUE TITLE
Chat Translation

### ISSUE THREAD

**Issue by Karrade** [kangarko/ChatControl#126]
I may be wrong here as well but i think a major part of chat control is keeping everything legible. 

So i was wondering about adding a translator, like if you speak english everything people type will be translated to english if you speak spanish everything you see will be in spanish and so for and so on.

here is a link for an api you could use and it is maintained by a decent dev:
http://dev.bukkit.org/bukkit-plugins/chat-translator/

**Comment by kangarko** [comment]
No sorry these translators produce lot of errors and does not serve the main purpose of this plugin.
