### ISSUE TITLE
(Muted Player) Issue

### ISSUE THREAD

**Issue by Thav01** [kangarko/ChatControl#126]
I'm not so sure if this is an Issue with ChatControl, but i don't know how to solve it, and i was hoping that I could possibly get an answer to it.

A Moderator is unable to speak on our Survival server, but from his side it shows normal like this
http://prntscr.com/bpjh6e

But Players do not see his messages. His chat works fine on other servers so i believe its an issue with a plugin in the Survival server.

For me, i have OP, it shows like this http://prntscr.com/bpjhlb
(Muted Slendyy)

I apologize if its not ChatControl related, but if you can, please help me find a solution, thanks.

Regards, Thav01.

**Comment by xknat** [comment]
@Thav01 hey thav01 this is indeed a difrent plugin.
i am able to help you :D

he is soft muted by greefprevention.

the greefprevention overides the essentials /mute
i did the fallowing:
./commands.yml
    |
    --> add these lines:
`  mute:
  - essentials:mute $$1 $2`

than do go over to your greefprevention folder:
./plugins/GriefPreventionData
open bannedWords.txt and empty it and upload it empty back to the server.
open config.yml
              |
              -->   do it like this:
```
SmartBan: false
Mute New Players Using Banned Words: false
```

**Comment by kangarko** [comment]
Hello, I am very sorry but I don't know a solution to your problem. It is not related to CHC. Please try the @xknat's suggestion.
