### ISSUE TITLE
PaperSpigot 1.17.1 (#196): Error on server startup

### ISSUE THREAD

**Issue by starwarsfreak219** [kangarko/ChatControl#1260]
After updating to the latest version, I am getting this error on startup which is disabling the plugin: https://paste.helpch.at/gisewohona.md

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false
Plugin Version: v10.5.5

**Comment by waiching514** [comment]
When I was running on 1.16.5 same happen with u
![image](https://user-images.githubusercontent.com/29138111/130302484-0f7cd528-c33d-4caa-b3ef-93ecb83db7d3.png)

**Comment by kangarko** [comment]
Looks to me like MCMarket did some modifications to the jar file since indeed its broken, although the same build works fine on my PC: https://i.imgur.com/k8qwsGo.png

Will reupload to MCMarket asap today, thank you.

**Comment by starwarsfreak219** [comment]
Issue is fixed on the latest version. Thanks!
