### ISSUE TITLE
1.17: ChatControlRed Not Working

### ISSUE THREAD

**Issue by user0347** [kangarko/ChatControl#1261]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Just purchased ChatControlRed, installed it properly, and every command is issuing the error "Cannot use this command while the plugin is disabled." Not sure what to do, or what info I should provide, as /chc debug doesn't work.

Server is running on java 16 and NashornPlus is installed

**Comment by kangarko** [comment]
Was MCMarket likely corrupting the build because the file on my end worked fine (I always test before submitting). Will resubmit today with latest updates.
