### ISSUE TITLE
1.16.5: Fatal error trying to convert ChatControlRed v10.5.5:org/mineacademy/chatcontrol/lib/model/SpigotUpdater.class

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1262]
/chc debug
[INFO]: Cannot use this command while the plugin is disabled.

All my servers give the same startup error and then chatcontrol disables...
here is my lobby server for1. https://pastebin.com/tGXNRSzY

Contents of the error.log file: https://pastebin.com/UUqgT35i

Papermc: b#876 (latests) 
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by donvdp** [comment]
i have reverted back to 10.5.4 :(

**Comment by kangarko** [comment]
Was MCMarket likely corrupting the build because the file on my end worked fine (I always test before submitting). Will resubmit today with latest updates.
