### ISSUE TITLE
Bungeecord and Discord

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1264]
all channel I had enabled bungee and discord
![image](https://user-images.githubusercontent.com/29138111/130338586-63cf6322-5ee5-4088-8891-4bfbdefefa53.png)

When I sent a message from Discord, It will logg 2times, Because network has 2 servers
![image](https://user-images.githubusercontent.com/29138111/130338545-a5ebb50f-ac2c-43bd-b293-0735631a9e01.png)
![image](https://user-images.githubusercontent.com/29138111/130338551-8676fa23-5dc8-42a5-8a8a-8dc9e2837796.png)

I trying some rule, it blocked to times
![image](https://user-images.githubusercontent.com/29138111/130338556-d95e4edd-6fad-4776-b75b-c987c3f95d9b.png)
![image](https://user-images.githubusercontent.com/29138111/130338558-dbe5165a-7cf4-4e31-83e2-c31186c98684.png)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by donvdp** [comment]
https://github.com/kangarko/ChatControl-Red/wiki/Discord

**Comment by kangarko** [comment]
Please see this: https://github.com/kangarko/ChatControl-Red/wiki/Discord#bungeecord
