### ISSUE TITLE
1.17.1: Error on every command/chat event

### ISSUE THREAD

**Issue by sukinaame** [kangarko/ChatControl#1265]
ufile linked in email
https://pastebin.com/e9Y59ZuU
formatting is also gone form chat

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by TheIntolerant** [comment]
This is caused by a syntax error, which appears to be in your global.rs file

Search for "// # Domain/URL filter." And remove the // part so only the hashtag is at the start of the line and run 
/chc reload, again and your problem should be fixed.

**Comment by kangarko** [comment]
Thanks to gone for helping out!
