### ISSUE TITLE
1.17.1: Discordsrv placeholders

### ISSUE THREAD

**Issue by Korinocho** [kangarko/ChatControl#1266]
There are still no usable placeholders like "%discordsrv_user_top_role_name%" from discordsrv on the plugin?
I want to add them on the discord messages ingame but this is what i get:
![image](https://user-images.githubusercontent.com/21372197/130381870-7e086a92-897d-4a77-ad5b-1347a72554b6.png)
and with "%"
![image](https://user-images.githubusercontent.com/21372197/130383592-2cc619bb-bdf0-4637-95e1-96e0ebc4faa0.png)

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true
Discord: true

**Comment by ElBananaa** [comment]
Hey!
I don't see any issues here.
You're trying to use a luckperms placeholder on a message sent from discord, and, afaik, luckperms doesn't hook with DiscordSRV at all, so it can't show the rank of a user that's not ingame.

**Comment by Korinocho** [comment]
Yhea, thats why im asking if there is still no internal usable placeholder for rank?
BTW the luckperms placeholder was just for demonstration

**Comment by kangarko** [comment]
No sorry we do not offer such placeholders at the moment:/

**Comment by n-aspen** [comment]
I'm trying to use the `%discordsrv_user_top_role_name%` placeholder from DiscordSRV to show the role of the user who sent the message from Discord. I think that's actually what OP meant here as well. DiscordSRV has placeholders using Papi that don't seem to work with ChatControl for some reason. They list them [here](https://docs.discordsrv.com/PAPI-Placeholders/) but I can't get any of them to work when formatting chat messages. 

![image](https://user-images.githubusercontent.com/16448318/142742917-308b8611-9cc7-4d05-b97b-1cd5e3ebd3d4.png)
