### ISSUE TITLE
Permission node for channel join announcements?

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#1267]
I'm looking to prevent certain staff members from announcing that they joined a channel, and I couldn't seem to find any permissions for it in the wiki. Any chance we can get a permission for this sometime in the future? If not, is it possible anywhere to atleast prevent vanished staff from announcing it? Thanks

1. A little bit of extra control never hurt anyone:)

2. It would make moderation a bit less awkward when trying to log in undetected or for keeping tabs of certain channels

**Comment by kangarko** [comment]
Thanks for suggesting, right now the messages can only be hidden by setting the Channels.Join.Success key in localization/messages_X.yml file to "none", but that would apply to all players.

If you want silent channel joining, use the /spy feature instead.
