### ISSUE TITLE
1.17.1: Custom resources not showing

### ISSUE THREAD

**Issue by user0347** [kangarko/ChatControl#1268]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Placeholders for font images from the plugin 'ItemsAdder' don't show properly for player's prefixes at all.

See: https://itemsadder.devs.beer/plugin-usage/using-font_images-emojis-everywhere for more info

![image](https://user-images.githubusercontent.com/75388149/130404518-80dc8fbe-10d3-4511-83f2-bbd312199b79.png)

**Comment by ElBananaa** [comment]
Hey!
To fix this issue, try using the placeholder for your emoji. (https://itemsadder.devs.beer/plugin-usage/placeholderapi).
In my case, I tried with the `:cutie:` emoji, and it worked fine after switching to its placeholder : `{img_cutie}`.
(The screenshot was taken after a server restart, no plugin reload was made).
![image](https://user-images.githubusercontent.com/53318613/130472779-36d9454b-1a15-4ba2-b969-38c7c6e6145e.png)
