### ISSUE TITLE
1.17.1: Nick placeholders

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1269]
What is the variable and/or placeholder for a {receiver} nickname? When I send a /msg, it should show the player's nickname going both ways. So when I send the message, it should show You -> <playernick>, and when I receive a message it should appear as
<playernick> -> You

Also a side note, please on future releases get rid of the weird equation text that appears when someone is joining a channel/leaving or is the only one in the channel etc.

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by donvdp** [comment]
i am using the {player} placeholder

![image](https://user-images.githubusercontent.com/10013800/130421640-4ed0a63b-20eb-4ade-80f6-45262f051f6f.png)

**Comment by ElBananaa** [comment]
> What is the variable and/or placeholder for a {receiver} nickname? When I send a /msg, it should show the player's nickname going both ways. So when I send the message, it should show You -> , and when I receive a message it should appear as
> -> You
> 
> Also a side note, please on future releases get rid of the weird equation text that appears when someone is joining a channel/leaving or is the only one in the channel etc.
> 
> Minecraft Version: 1.17.1
> MySQL: false
> BungeeCord: false

Hey!
I don't understand your issue.
The variable for the receiver is `{receiver}`.

Regarding the "weird equation", could you provide us a screenshot, because we're not aware of a weird equation showing up when you try to join a message. Just in case, since you're under mc 1.17.1, please install NashornPlus (https://mineacademy.org/nashorn/) and let us know if it fixes the issue.

**Comment by HorusApl** [comment]
But {player} would just show their ign

**Comment by ElBananaa** [comment]
Yes, but I didn't mention this placeholder. As I said, it's `{receiver}`, not `{player}` ^^

**Comment by HorusApl** [comment]
I'm basically looking for the {receiver_nick} placeholder. So when I
message someone, it would show You -> <theirnickname>

**Comment by ElBananaa** [comment]
Well, that's what the `{receiver}` variable should do.

**Comment by kangarko** [comment]
Thanks, I will add {receiver_nick} to the next version.

**Comment by ElBananaa** [comment]
Well, it looks like that wasn't the case, my bad for giving wrong informations😅
