### ISSUE TITLE
When Using the packets.txt replace thingy it forgets colours

### ISSUE THREAD

**Issue by ThemInspectors** [kangarko/ChatControl#127]
running Spigot version git-Spigot-a9631d2-67b2424 (MC: 1.10.2)
With ChatControl (free version) v5.3.3
And ProtocolLib v4.1.0-SNAPSHOT-b306
So If I were to put in the Packets.txt file:
`Match (s)'s`
`then replace $1'`
It'd Match an "S" lower or capital and then remove the extra "s" at the end, respecting the lower or capital "S" at the begining.
All above works properly but If I type in " TARDIS's " it removes colours And properly replaces the text from TARDIS's to TARDIS' except with no colours

**Comment by kangarko** [comment]
Hello, please read the https://github.com/kangarko/ChatControl/wiki#known-caveacts, there is an explanation on how the packet filters work in free version. I've rewritten the system in the pro version and the colours tend to be preserved there.
