### ISSUE TITLE
Broken advertising filter?

### ISSUE THREAD

**Issue by johandrex** [kangarko/ChatControl#127]
If a player for example says "youtube.com/channelname" he doesn't get muted. But if he says "hey go to youtube.com/channelname" he does get muted. Please fix this bug. Here's the rule in rules.txt

match [a-zA-Z0-9\-\.]+\s?(\.|dot|no-ip|\(dot\)|-|;|:|,)\s?(com|org|net|cz|nl|co|uk|sk|biz|mobi|xxx|io|eu)\b
id 2
ignore string powercraft|9gag|youtube|www.youtube.com|youtube.com|twitter|www.twitter.com|www.twitter|instagram|www.instagram.com|vine|www.vine.com|www.facebook.com|facebook.|gyazo|www.gyazo.com|imgur|www.imgur.com|www.enjin.com|enjin.com|www.prntscr.com|prntscr|puu.sh|puush.me|twitch|www.twitch.com|minecraft|www.minecraft.com|minecraft.net|www.minecraft.net|mojang|www.mojang.com|minecraftskins|www.minecraftskins.com|optifine|www.optifine.com|www.optifine.net|optifine.net|www.skins.com|skins|www.skins.net|skins.net|google|www.google.com|www.minecraftforge.com|minecraftforge|minecraftforge.net|www.minecraftforge.net|yahoo|www.yahoo.com|skype|www.skype.com|bing|www.bing.com|skype.com|www.skype.com|powercraft.com|www.powercraft.com|store.powercraft.me|minecraftskins.com|www.minecraftskins.com|mcskinsearch.com|www.mcskinsearch.com|store.powercraft.com|needcoolshoes.com|www.needcoolshoes.com|agar.io
strip [\(\[\]\)]
handle as advertisement

**Comment by Karrade** [comment]
If your trying to make sure the player is muted you should take youtube.com out of thr ignore sttings list

**Comment by johandrex** [comment]
No I want them to be able to say it. But if they say "Hello player check out youtube.com" he gets muted but not if he says "youtube.com

**Comment by Karrade** [comment]
Im no pro with regex bit it looks like your checking for whitespace directly before the url maybe try adding something like this to ignore
 " youtube.com"

**Comment by johandrex** [comment]
Not working

**Comment by johandrex** [comment]
Halp!

**Comment by Karrade** [comment]
Like i said im no pro at regex but maybe you could try this until the dev comes to help you

http://www.regexr.com

It should help you create a regex string you want

**Comment by johandrex** [comment]
@kangarko help!

**Comment by johandrex** [comment]
Sorry you've a vacation. Please fix this once you get back ;)

**Comment by MrEminent42** [comment]
Yea I've had that problem too. Try changing it to: 
match [a-zA-Z0-9-.]+(\s?|)(.|dot|no-ip|(dot)|-|;|:|,)\s?(com|org|net|cz|nl|co|uk|sk|biz|mobi|xxx|io|eu)\b
and see if that works.

**Comment by johandrex** [comment]
Not working

**Comment by johandrex** [comment]
When will you be able to look on this?

**Comment by kangarko** [comment]
You have edited advertising filter from the default one. This might be the problem, however, I have cleaned up the ignore section and it seems to be working:

match [a-zA-Z0-9-.]+\s?(.|dot|no-ip|(dot)|-|;|:|,)\s?(com|org|net|cz|nl|co|uk|sk|biz|mobi|xxx|io|eu)\b
id 2
ignore string powercraft.me|9gag.com|youtube.com|twitter.com|instagram.com|vine.com|facebook.com|gyazo.com|imgur.com|enjin.com|prntscr.com|puu.sh|puush.me|twitch.com|minecraft.net|mojang.com|optifine.net|skins.net|google.com|minecraftforge.net|yahoo.com|bing.com|skype.com|minecraftskins.com|needcoolshoes.com|agar.io
strip [\(\[\]\)]
handle as advertisement

**Comment by johandrex** [comment]
Fixed thanks!
