### ISSUE TITLE
We need a lot more variables for spying signs, anvils, and books

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#127]
The amount of variables and the config options for spying signs, anvils, and books is sorely lacking.  We need to have the ability to create a new line in chat with `\r`.  Also, we should have access to the following variables (I am also including ones that are already available, just so we have the full list):

Signs:
- `{server}`
- `{player}`
- `{world}`
- `{x}`
- `{y}`
- `{z}`
- `{line1}`
- `{line2}`
- `{line3}`
- `{line4}`

Anvils:
- `{server}`
- `{player}`
- `{world}`
- `{x}`
- `{y}`
- `{z}`
- `{item_type}`
- `{item_name}`

Books:
- `{server}`
- `{player}`
- `{world}`
- `{x}`
- `{y}`
- `{z}`
- `{name}`
- `{author}`
- `{contents}`

The server, world, x, y, and z variables will allow us to pinpoint exactly where this player was when the sign/book/rename was done, and it would allow us to, for example, add a `/tp x, y, z` command when clicking the spy message.

I understand that books can have a lot of text, so printing the full contents out in the console is not recommended, but we should have the option to log them somewhere.

I told you previously that you could feel free to use the code from a plugin I've been using for years that has all this stuff already working great.  I still think you should look at it and use the code to add it to ChatControl because it's really useful.  It would be nice to have ChatControl be able to do everything this plugin does so I can stop using it and just use CHC.

https://github.com/jamezrin/EventLogger

**Comment by broken1arrow** [comment]
@c0wg0d I made issue for this, i´m happy if you add if it miss something. 

https://github.com/kangarko/ChatControl-Red/issues/117

You can add it as channels (i´m think you not break this), so can you see anvils and signs in console `
like this and add {location} i think this work. I can try i out fast :) 
````
    spy-sign:
      Format: spy-sign
      Format_Console: '[SPY-chat {player}]{location} {sign_lines}'`
````

**Comment by broken1arrow** [comment]
@c0wg0d I made issue for this, i´m happy if you add if it miss something. 

https://github.com/kangarko/ChatControl-Red/issues/117

And placeholders for location/cord is {location} and for signs {sign_lines} 

You are free to change in /plugins/ChatControlRed/formats how i shall look in game :)

But the console logging for anvil and sign, is not a bad idea. 

Use something like this in format perhaps, can be added (if it not get to much settings for channels) 
`Format_Console: '[SPY-chat {player}]{location} {sign_lines}'`

And tips, not use chat.yml he will update it with new settings even after release (working as a template how to set up channels). So recommend use your own :)

**Comment by kangarko** [comment]
Thank you!

**Comment by c0wg0d** [comment]
I know that `{location}` and `{sign_lines}` exist, but they are too limiting, which is why I proposed more variables.  For example, location does not say the server name and doesn't separate the x, y, and z variables so you can use them in a /tp command, for example, and the `{sign_lines}` variables splits the text into 4 separate lines when it would be easier to read if they didn't include line breaks.  Adding finer grain variables allows for more options to people, which is always a good thing.

**Comment by broken1arrow** [comment]
> I know that `{location}` and `{sign_lines}` exist, but they are too limiting, which is why I proposed more variables. For example, location does not say the server name and doesn't separate the x, y, and z variables so you can use them in a /tp command, for example, and the `{sign_lines}` variables splits the text into 4 separate lines when it would be easier to read if they didn't include line breaks. Adding finer grain variables allows for more options to people, which is always a good thing.


I understand what you mean now, you want sign spy to work like previous cc versions (in hover i think current format work, but not soo good in chat)?

When it comes to cord, it is already available with placeholderAPI. Also think you can make your own tp command with these placeholders (cc should still have support for that too). 

Like this /tp %player_name% %x% %y% %z% ,but i don´t know if the placeholder save cords where the player wrote the sign or follows the player. But should work for console and in chat.

and placeholderAPI is very widespread (lots of server use this) and also keep in mind, the more placeholders for the chat you have, the heavier it can be (of course also depends on how heavy each placeholder is).

**Comment by kangarko** [comment]
Thanks, I added all of those
<img width="1680" alt="Screenshot 2020-11-21 at 01 26 22" src="https://user-images.githubusercontent.com/1918426/99862394-da74a400-2b99-11eb-842f-f0026892aeb5.png">

Also, we now log all things that are being spied upon to log.csv that also can go to MySQL and can be viewed with /chc log.

**Comment by c0wg0d** [comment]
Can you please change the anvil so it doesn't append the name and the hover automatically?  I got my format setup with the added item_name and item_type but now it puts the item on the end afterward.

**Comment by kangarko** [comment]
Sure, reopening.

**Comment by kangarko** [comment]
Done, you can now use such format:

![a](https://i.imgur.com/2WIktBb.png)
