### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by Gilthunderx** [kangarko/ChatControl#1271]
Hello how can i get to work the [ i ] and [item] using chatcontrolred. I want to use its cool feature.

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: true

**Comment by ElBananaa** [comment]
> Hello how can i get to work the [ i ] and [item] using chatcontrolred. I want to use its cool feature.
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: true

Hey!
You need to enable our channel feature.
Once this is done, if you're using java 15+, update the plugin to the latest version (v10.6.0-BETA), and it should work.
