### ISSUE TITLE
1.17.1: ItemsAdder Emoji Issues

### ISSUE THREAD

**Issue by user0347** [kangarko/ChatControl#1273]
Minecraft Version: 1.17.1
MySQL: /false
BungeeCord: /false

Any emoji's that are shown in chat get weird formats before and after them; not sure if this is a bug and don't know how to fix:
![image](https://user-images.githubusercontent.com/75388149/130616339-6c973bb1-8d58-4c21-befe-7106626207b9.png)

Also, I submitted a bug report about this before, and you mentioned to use {img_EMOJI-NAME] for their tag, but that still didn't work. I have {player_prefix+) set for the message with ChatControl, and in PEX I have their prefix as :player: for the default rank, but I also tried %img_player%, :player:, {img_player}, and none worked.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1
> MySQL: /false
> BungeeCord: /false
> 
> Any emoji's that are shown in chat get weird formats before and after them; not sure if this is a bug and don't know how to fix:
> ![image](https://user-images.githubusercontent.com/75388149/130616339-6c973bb1-8d58-4c21-befe-7106626207b9.png)
> 
> Also, I submitted a bug report about this before, and you mentioned to use {img_EMOJI-NAME] for their tag, but that still didn't work. I have {player_prefix+) set for the message with ChatControl, and in PEX I have their prefix as :player: for the default rank, but I also tried %img_player%, :player:, {img_player}, and none worked.

Hey,
What I asked you to do worked perfectly fine for me with the latest ItemsAdder version, and the latest chatcontrolred version. Make sure protocollib is also installed and up to date.

Regarding the weird text, it looks like this is caused by a rule.
Please provide us your /chc debug file, so I can run tests with your plugin setup

Also, please provide us your latest.log file when the issue with the emoji happens.

**Comment by ElBananaa** [comment]
Hi,
Since there's no update on this, I'm closing the issue.
If you need anything else, feel free to tag me (@ElBananaa) in the comments down below!

**Comment by user0347** [comment]
@ElBananaa this issue with the emojis in chat showing the [#flpc-i] is still happening.

![image](https://user-images.githubusercontent.com/75388149/135535217-1b3d95b1-8b93-472d-b69f-30795c67a0c8.png)

Debug: [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7262708/debug.zip)

**Comment by ElBananaa** [comment]
> @ElBananaa this issue with the emojis in chat showing the [#flpc-i] is still happening.
> 
> ![image](https://user-images.githubusercontent.com/75388149/135535217-1b3d95b1-8b93-472d-b69f-30795c67a0c8.png)
> 
> Debug: [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7262708/debug.zip)

Hey,
I don't really know what's the cause of the issue.
I tried with both the default plugin's files and your chatcontrol's files, and in both cases, it worked flawlessly.
Even when I enable the rule that contains the `[#flpc-i] & [#flpc-1]` stuff in `rules/chat.rs`, it still works fine for me.

I really have no idea of what's causing the issue. Please remove NashornPlus to see if it helps, who knows (Btw, the library isn't needed anymore for 1.17.X+ servers with java 16 or above, so no need to add it back, no matter if it helps or not)

**Comment by ElBananaa** [comment]
Closing this since tha author didn't answer.
Feel free to tag me down below if the issue persists
