### ISSUE TITLE
1.17.1: Join Messages

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1276]
Using the Prefix section and the rules for join.rs to make the join message show a certain way (I believe it's the default of the plugin.) [+] <nick> which works. But then it also shows the vanilla mc "Horus_Apl has joined the game." Any ideas to correct this? I didn't change the config, just restarted the server and this appeared.

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> Using the Prefix section and the rules for join.rs to make the join message show a certain way (I believe it's the default of the plugin.) [+] which works. But then it also shows the vanilla mc "Horus_Apl has joined the game." Any ideas to correct this? I didn't change the config, just restarted the server and this appeared.
> 
> Minecraft Version: 1.17.1
> MySQL: false
> BungeeCord: false

Hey!
Could you please provide us your /chc debug file and your latest.log? A similar issue has been reported recently, but since it can be caused by many different things, giving us these files would be pretty helpful ^^

**Comment by HorusApl** [comment]
[](url)
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7052227/debug.zip)
[latest (5).log](https://github.com/kangarko/ChatControl-Red/files/7052228/latest.5.log)

**Comment by HorusApl** [comment]
Also, a side note: How can I disable the profanity filter?

**Comment by TheIntolerant** [comment]
> Also, a side note: How can I disable the profanity filter? 

Go into the "global.rs" file in the rules folder and near the bottom of the file you should see a list of rules with "group swear" at the bottom

If you wish to completely disable these rules you can either comment that section out (aka add a hashtag at the front of the line, for the lines starting with "match" and "group"), should you want to use the rules in the future or completely delete that section of the file.

Example, change this
```
# Blocks 'fuck'
match \b(f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
group swear
```
to this
```
# Blocks 'fuck'
#match \b(f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
#group swear
```

**Comment by ElBananaa** [comment]
Hey,
Sorry for the delay.

So, according to your general.txt file, you're not using the latest version of the plugin, but a previous one with Java 16.0.2, but NashornPlus isn't installed on your server.

So I'd suggest doing either the 1st suggestion, or the 2nd one:
- Either update to the latest version, in which case, NashornPlus isn't needed anymore.
- Or stick with your current version of the plugin, but install NashornPlus (https://mineacademy.org/nashorn/).

Once this is done, I noticed that you're also using EssentialsX, so in essentials config file, please set `allow-silent-join-quit` to `false`.

Let me know if it works and if you need anything else!

**Comment by kangarko** [comment]
Assuming it has been fixed, let us know if you still need help below and good luck :)
