### ISSUE TITLE
When the mail having chiese words not working

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1277]
https://pastebin.com/6p8TszeY

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey!
This seems to be pretty weird issue.
Can you confirm that both your issues only happen with chinese characters? Or does the issue also happens with latin characters?

**Comment by waiching514** [comment]
I tested chinese words and latin characters no problem now

**Comment by waiching514** [comment]
but I also have a problem, When player read and delete a mail, they switch to other server the mail will not read and deleted

**Comment by ElBananaa** [comment]
It seems pretty weird.
Could you please provide us your `/chc debug` file?

**Comment by waiching514** [comment]
https://ufile.io/6tv3rvgf

**Comment by ElBananaa** [comment]
Hey,
Thanks for providing us the file.
I was unable to reproduce your issue on my side, on a local server.
I believe your issue may be caused by a wrong database encoding.

Could you please provide us more informations about your database, such as the version and the encoding?
As Kangarko said on a pretty old issue, issues like this one can also happen on older versions of db drivers. (Here's the link of the full message : https://github.com/kangarko/ChatControl-Red/issues/370#issuecomment-751503462)

**Comment by waiching514** [comment]
![image](https://user-images.githubusercontent.com/29138111/131199916-d09ea1d6-34b5-43fd-93eb-d99007d0e23e.png)
![image](https://user-images.githubusercontent.com/29138111/131199926-90ddd475-7c4e-4f72-b323-8d7d30b8ca47.png)

**Comment by kangarko** [comment]
Looks like strings saved to your database do have improper encoding, I advise contacting your hosting regarding using an encoding which supports Chinese. Thanks Banana for the help!

**Comment by waiching514** [comment]
but other plugin work normally

![image](https://user-images.githubusercontent.com/29138111/131434338-5651f601-2886-4a30-bc09-f90c7e0fa054.png)
![image](https://user-images.githubusercontent.com/29138111/131434352-e2be220a-cfe2-4924-8c8c-7d49ad5723b4.png)

only ChanControlRed will not logging chiese word, 
![image](https://user-images.githubusercontent.com/29138111/131434445-ae72b9af-c2c8-4b0d-9b22-6f8e8bd7dc49.png)

**Comment by kangarko** [comment]
I just checked. There were some issues with saving unicode causing player kicks and bad stuff so I actually disabled that temporarily, we can return to this in late September when I am back from holidays.
