### ISSUE TITLE
bcreload bug

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1278]
When using command /bcreload on bungeecord, will make new login player status offline
such as playerB and playerA same server on the network,
playerB login at 7:00
using command /bcreload at 7:05
playerA login at 7:10
playerB using /m playerA, server will showing "playerA" not online
but playerA can using /m with playerB

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> When using command /bcreload on bungeecord, will make new login player status offline
> such as playerB and playerA same server on the network,
> playerB login at 7:00
> using command /bcreload at 7:05
> playerA login at 7:10
> playerB using /m playerA, server will showing "playerA" not online
> but playerA can using /m with playerB
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey,
Sorry for the delay.
Which version of ChatControlRed and BungeeControlRed are you using?
Also, could you try to reproduce this issue on Waterfall? (https://papermc.io/downloads#Waterfall - Waterfall is recommended over Bungeecord since it offers multiple improvements)

**Comment by waiching514** [comment]
10.6.0
3.6.0
It is running on Waterfall

**Comment by kangarko** [comment]
Will temporarily remove this command until problems are solved.
