### ISSUE TITLE
error while loading

### ISSUE THREAD

**Issue by Bronzwar** [kangarko/ChatControl#1279]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

During the download, I get an error

https://paste.helpch.at/ikigorekuf.sql

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> During the download, I get an error
> 
> https://paste.helpch.at/ikigorekuf.sql

Hey!
I noticed you're using a "non official" papermc fork.
Could you please try with spigot/paper to see if the issue also happens?

**Comment by Bronzwar** [comment]
I tested the plugin on a new server using the same paper fork and everything works. Then I launched the plugin on the main server, installing only one plugin on it and the same error appeared. The differences between the server are only flags.
Can you test your plugin with this flags?: 
java -Xms1000M -Xmx27000M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dterminal.jline=false -Dterminal.ansi=true --illegal-access=permit -jar server.jar

**Comment by ElBananaa** [comment]
Hey,
I'm using aikar's flags as well, and I don't have a such issue, so I don't think this is related to the flags.
Which java version are you using on both server?
Also, could you please provide us both your test and main server `/chc debug` files?

**Comment by kangarko** [comment]
I unfortunately am unable to help with this, never had I encoutered such an error nor does it look like it is caused by us. It points to the internal library loading mechanism which is modified by your server fork, or as Banana said, maybe even some startup flags, I am not sure to be honest. Contact your server hosting or try booting up another fork.
