### ISSUE TITLE
/msg is just completely broken?

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#128]
I'm doing /msg [player] [message] with the correct username etc, and it is trying to claim the person isn't online when they blatantly are? [https://i.imgur.com/dUZfGwT.png](https://i.imgur.com/dUZfGwT.png)

Console is also claiming: >.... [07:54:09 INFO]: Player 'aSquish' is not connected through BungeeCord.

When they blatantly are, it is very annoying :/ I'm using the latest version

**Comment by kangarko** [comment]
They have to be connected through BungeeCord if Bungee is enabled

**Comment by DoogiePC** [comment]
They are connected through bungeecord, you shouldn't just close it. It's not possible to join the server without bungeecord

**Comment by kangarko** [comment]
You closed it. Going to investigate.

**Comment by DoogiePC** [comment]
> You closed it. Going to investigate.

msg seems even more broken than I imagined, it is so common for me to message player1 but for some random reason player2 receives the message?

**Comment by kangarko** [comment]
Sorry for the delay. I need more information from you:

1. Upload me your ZIP file by doing /chc debug
2. When that happens you should see "TIP Note: Private message from " tip console log (make sure Show_Tips is on), let me know if that message shows the incorrect player name.

**Comment by DoogiePC** [comment]
https://ufile.io/a0erycr0

it's gonna be very hard to try find that little message, console moves very fast

**Comment by kangarko** [comment]
I apology, but you seem to be using MySQL for logs. Can you please look into your console and find these messages when that happens?

**Comment by kangarko** [comment]
We'll also going to be having another version very soon, please test that ;)

**Comment by broken1arrow** [comment]
> https://ufile.io/a0erycr0
> 
> it's gonna be very hard to try find that little message, console moves very fast

If you use some programs like Notepad++ or Atom and seach true the logs. 

Msg look like this in console [18:56:04] [Server thread/INFO]: [pm] broken_arrow1 ->"other player name": random text

**Comment by kangarko** [comment]
Try next release please, let me know below if still having this issue.
