### ISSUE TITLE
Staff can't do /gmc

### ISSUE THREAD

**Issue by Gigorahk** [kangarko/ChatControl#128]
For some reason staff cannot use their /gmc commands because this plugin seems to be blocking it. I have the proper essentials gamemode permissions but this plugin blocks them :(

**Comment by Gigorahk** [comment]
Had to add permission ( chatcontrol.bypass.rules ) to the group.

**Comment by kangarko** [comment]
You'll also have to review rules/commands.txt and remove the rules you do not want.
