### ISSUE TITLE
Question about javascript

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1281]
Putting a variables on key, is this possible?

```rs
Key: ptp {player_typedname}
Value: |-
    showTpPlot();
    
    function showTpPlot() {
      return "&f[" + "&f{player_typedname} &bPlot Teleport" + "&r]";
    }
Suggest_Command: /plot tp {player_typedname}
```

I dont know how to make new function of {player_typedname}

**Comment by TheIntolerant** [comment]
Just so it's easier for us to help, what are you trying to do?

**Comment by ElBananaa** [comment]
Hey,
As far as I know, no, it's no possible to put a variable in the key part of your variable file.
You can't use spaces there neither.

But what you're trying to do is completely wrong. You can't create a custom command in a variable file.
To do so, please refer to our wiki : https://github.com/kangarko/ChatControl-Red/wiki/Custom-Commands
You can also use bukkit built-in command system: https://www.spigotmc.org/go/commands-yml
Or, you can try to reach the author of your plot plugin, and ask them to add the command you're trying to implement.

Anyways, your usage of the variable system isn't right, so what you wrote won't work ^^

**Comment by kangarko** [comment]
Thanks to Banana for the help!
