### ISSUE TITLE
1.17.1: can use {nick} variavbles in localization?

### ISSUE THREAD

**Issue by mc-eia** [kangarko/ChatControl#1282]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

No action variables except {player}, {player_name} variables.

Is it because my plugin experience is inexperienced and I can't find it?

Or is it not supported? If so, is it possible to apply?

(I'm using Google Translate, so the sentences may be weird.)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1
> MySQL: true
> BungeeCord: true
> 
> No action variables except {player}, {player_name} variables.
> 
> Is it because my plugin experience is inexperienced and I can't find it?
> 
> Or is it not supported? If so, is it possible to apply?
> 
> (I'm using Google Translate, so the sentences may be weird.)

Hey!
Here's the list of our variables : https://github.com/kangarko/ChatControl-Red/wiki/Variables
I don't know if they can all be used in the localization files but it's worth giving it a shot.

**Comment by mc-eia** [comment]
> > Minecraft Version: 1.17.1
> > MySQL: true
> > BungeeCord: true
> > No action variables except {player}, {player_name} variables.
> > Is it because my plugin experience is inexperienced and I can't find it?
> > Or is it not supported? If so, is it possible to apply?
> > (I'm using Google Translate, so the sentences may be weird.)
> 
> Hey!
> Here's the list of our variables : https://github.com/kangarko/ChatControl-Red/wiki/Variables
> I don't know if they can all be used in the localization files but it's worth giving it a shot.

Already tried {player nick} {nick} variable in locale.
It didn't work when I didn't use JavaScript,
and I didn't try it because I didn't know much about JavaScript.

**Comment by ElBananaa** [comment]
> > > Minecraft Version: 1.17.1
> > > MySQL: true
> > > BungeeCord: true
> > > No action variables except {player}, {player_name} variables.
> > > Is it because my plugin experience is inexperienced and I can't find it?
> > > Or is it not supported? If so, is it possible to apply?
> > > (I'm using Google Translate, so the sentences may be weird.)
> > 
> > 
> > Hey!
> > Here's the list of our variables : https://github.com/kangarko/ChatControl-Red/wiki/Variables
> > I don't know if they can all be used in the localization files but it's worth giving it a shot.
> 
> Already tried {player nick} {nick} variable in locale.
> It didn't work when I didn't use JavaScript,
> and I didn't try it because I didn't know much about JavaScript.

What do you mean exactly by "when I didn't use JavaScript"?

**Comment by mc-eia** [comment]
> > > > Minecraft Version: 1.17.1
> > > > MySQL: true
> > > > BungeeCord: true
> > > > No action variables except {player}, {player_name} variables.
> > > > Is it because my plugin experience is inexperienced and I can't find it?
> > > > Or is it not supported? If so, is it possible to apply?
> > > > (I'm using Google Translate, so the sentences may be weird.)
> > > 
> > > 
> > > Hey!
> > > Here's the list of our variables : https://github.com/kangarko/ChatControl-Red/wiki/Variables
> > > I don't know if they can all be used in the localization files but it's worth giving it a shot.
> > 
> > 
> > Already tried {player nick} {nick} variable in locale.
> > It didn't work when I didn't use JavaScript,
> > and I didn't try it because I didn't know much about JavaScript.
> 
> What do you mean exactly by "when I didn't use JavaScript"?

localization/messages_en.yml (line 883)
Not_Online: '&cPlayer {player} &cis not online on this server.'
↓
Not_Online: '&cPlayer {nick} &cis not online on this server.'

**Comment by ElBananaa** [comment]
I see, but you didn't use javascript in here. The only difference is the variable used here.
Anyways, if it worked with `&cPlayer {nick} &cis not online on this server.` I don't really see any problem ^^

**Comment by mc-eia** [comment]
> I see, but you didn't use javascript in here. The only difference is the variable used here.
> Anyways, if it worked with `&cPlayer {nick} &cis not online on this server.` I don't really see any problem ^^

I asked a question because it did not work in the locale file except for the variables {player} and {player_name}

not work {nick} , {player_nick}

If this is not supported, could you please add a feature?

**Comment by ElBananaa** [comment]
> > I see, but you didn't use javascript in here. The only difference is the variable used here.
> > Anyways, if it worked with `&cPlayer {nick} &cis not online on this server.` I don't really see any problem ^^
> 
> I asked a question because it did not work in the locale file except for the variables {player} and {player_name}
> 
> not work {nick} , {player_nick}
> 
> If this is not supported, could you please add a feature?

Alright, I understand this a bit better.
Please wait for @kangarko to see if this is something that can be done 😉

**Comment by mc-eia** [comment]
> > > I see, but you didn't use javascript in here. The only difference is the variable used here.
> > > Anyways, if it worked with `&cPlayer {nick} &cis not online on this server.` I don't really see any problem ^^
> > 
> > 
> > I asked a question because it did not work in the locale file except for the variables {player} and {player_name}
> > not work {nick} , {player_nick}
> > If this is not supported, could you please add a feature?
> 
> Alright, I understand this a bit better.
> Please wait for @kangarko to see if this is something that can be done 😉

oh ok. thx

**Comment by kangarko** [comment]
I apologies, localization mostly only supports {player} when it contains that variable on the given line. We do not parse 1000s of other placeholders there for performance reasons.

**Comment by mc-eia** [comment]
> I apologies, localization mostly only supports {player} when it contains that variable on the given line. We do not parse 1000s of other placeholders there for performance reasons.

can change the nickname through the "/tag" command of the plugin itself.
Is it impossible to register a variable of a nickname that has been changed with this command?

example.
player name = mc_eia
/chc tag nick mc_eia customnick

{player} = mc_eia
{nick} = customnick

message_en.yml line 876
1.
  Not_Online: '&cPlayer {player} &cis not online on this server.'
print -> Player mc_eia is not online on this server.
2.
  Not_Online: '&cPlayer {nick} &cis not online on this server.'
print -> Player customnick is not online on this server.

Is this also impossible?

**Comment by kangarko** [comment]
No sorry, as I said, we are not parsing variables there for performance reasons.
