### ISSUE TITLE
1.17.1: First join message

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1285]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Apparently these settings became unused, but how do I now use the first join message?

![image](https://user-images.githubusercontent.com/5664135/131214110-86b5e717-4b2b-464a-898d-e29c50cf230a.png)

**Comment by kangarko** [comment]
I do not think we have an alternative for this, so I am going to add a new operator "require/ignore firstjoin" to the messages file in the next version.

**Comment by Sikatsu** [comment]
Hmm, thank you. Hope it won't reset everyone that was welcomed?

**Comment by kangarko** [comment]
Not in case you still have Players key with a list of UUIDs in your data.db.

By the way, you will be able to use the "require/ignore playedbefore" across all files, not just join.rs file.

![a](https://i.imgur.com/ofR7pNK.png)

----

**Important**

In case you do not have this list, I added a standalone runnable part into BungeeControl-Red for you to create it from one of your oldest Spigot servers.

1. Open your main world then playerdata folder, you should see a big list of UUID files ending with .dat.
2. Extract this to your desktop into a folder.
3. Place Converter.jar into that folder.
4. Open console, set your working directory to that folder and run the jar.
5. A new data.db file should appear.

![a](https://i.imgur.com/j8WoJdN.png)

**Comment by kangarko** [comment]
[Converter.zip](https://github.com/kangarko/ChatControl-Red/files/7075065/Converter.zip)
Here is the program (you can decompile it if you want and see what it does, it is very simple)

**Comment by Sikatsu** [comment]
It appears they were still in my database and I didn't need the converter(?)

**Comment by kangarko** [comment]
Great then!

**Comment by Sikatsu** [comment]
Thank you for adding this back!
