### ISSUE TITLE
1.17.1: How do I delete a message?

### ISSUE THREAD

**Issue by Woody-Man** [kangarko/ChatControl#1287]
Is there any way to remove this message completely?
It appears when I enter the "!" character itself into the chat.
![image](https://user-images.githubusercontent.com/87870686/131265809-e1d21f04-343a-493f-ac64-7f8f4a514d16.png)
I need it very much

**Comment by Woodpecker123** [comment]
It appears when I enter the "!" character itself into the chat.

**Comment by kangarko** [comment]
Yes, you can remove this block in rules/chat.rs:

![a](https://i.imgur.com/7oeClMP.png)

**Comment by Woody-Man** [comment]
But I need to be able to write to the global chat when I enter "!" in the chat.
But also that there was no such message.

**Comment by Woody-Man** [comment]
Or even change this message, for example, change the command in the message to the symbol"!"

**Comment by kangarko** [comment]
You can change the format in this message in our localization, see the Wiki on Localization.

**Comment by Woody-Man** [comment]
And it's still not impossible to completely remove it?

**Comment by kangarko** [comment]
Should be, set the key in localization settings to "none"
