### ISSUE TITLE
1.17.1: Broadcast Command formatting

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1288]
How do I alter the /chc broadcast formatting? I have searched every config file and there is no way to change it that I can see.

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
You can alter it using localization:

![a](https://i.imgur.com/6GwMycd.png)

See our Wiki regarding Localization usages and tutorial on changing it.
