### ISSUE TITLE
1.16.3 | Formats saving wrongly

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#129]
Before:
![image](https://user-images.githubusercontent.com/62369973/99788516-44596300-2b32-11eb-906b-f5d47c1d7d43.png)

After:
![image](https://user-images.githubusercontent.com/62369973/99787684-1c1d3480-2b31-11eb-84ee-6cca61d20751.png)

The main problem is that it removed all the "\n" things that completely broke the message from how it supposed to look like. It also removed spaces in some messages which were there to centralize the message

Thats how it looks like after a server restart:
![image](https://user-images.githubusercontent.com/62369973/99788009-89c96080-2b31-11eb-8344-170ffab1f07c.png)

Thats how was it supposed to look like:
![image](https://user-images.githubusercontent.com/62369973/99788477-37d50a80-2b32-11eb-916e-2ad67c43e8a0.png)

**Comment by kangarko** [comment]
Do not use \n, but put messages on multiple lines:

```
Message:
- "Hello"
- ""
- "World"
```

**Comment by OfT3N** [comment]
> Do not use \n, but put messages on multiple lines:
> 
> ```
> Message:
> - "Hello"
> - ""
> - "World"
> ```

I can’t cuz for as you can see I have different gradient for every line and for the 9th line, all of the words there are supposed to be buttons, which cannot be realised by your solution

**Comment by kangarko** [comment]
I understand, I apology this cannot be solved with our current system, will have a look for this into the future

**Comment by OfT3N** [comment]
> I understand, I apology this cannot be solved with our current system, will have a look for this into the future

I think thats no problem. I already solved it, but you should define this somewhere in WIKI i guess 

![image](https://user-images.githubusercontent.com/62369973/100272893-efbc4a80-2f6c-11eb-9cce-ca38b7817f53.png)

![image](https://user-images.githubusercontent.com/62369973/100273038-31e58c00-2f6d-11eb-8a3a-f8ebe5066be2.png)
