### ISSUE TITLE
Chat control anti advertisement bypass permission not working

### ISSUE THREAD

**Issue by butterontoast7** [kangarko/ChatControl#129]
Hey I want my staff on my server to be able to post links to forums I put in the - chatcontrol.bypass.ad for all of my staff but it still wont let them post links in chat? Is it a bug or am I just missing something?

**Comment by kangarko** [comment]
What happens if they post a link? Will it get blocked by the filter normally? If the dots are removed from the url, it is not coming from ChatControl. Essentials is known to do that. In such case, try adding your players permission essentials.chat.url and essentials.msg.url for private messages.

**Comment by butterontoast7** [comment]
that fixed the problem! btw im a huge fan of your chat plugin! Keep up the good work! Might donate soon!

**Comment by kangarko** [comment]
Thank you!
