### ISSUE TITLE
1.16.5 : Chatcolor missing glass pane

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1290]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

The /color gui isn't full of red_glass, some slots stay empty

Debug : 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7077616/debug.zip)

<img width="348" alt="Screenshot_5951" src="https://user-images.githubusercontent.com/31826333/131360835-12614baa-0a4c-4102-ae2c-2a0e7dc9d50d.png">

**Comment by kangarko** [comment]
That's what developers call an "Oh awesome, oh crap" moment. We fixed one issue where the glass was always white, so I was so happy I forgot to remove the debug code. Will do so in the next release right now haha!
