### ISSUE TITLE
1.17.1: Database issues

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1292]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Came online today, heard from quite some players and staff members their nickname and chat color got reset after last nights restart. This however did not occur to me and a few others. As suggested before updating I added UUID_Lookup: false to the bottom of the settings.yml file for all servers. Am I doing something wrong?

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7082494/debug.zip)

**Comment by Sikatsu** [comment]
All servers are linked to the same MySQL database, but all servers also have a data.db file, the size of those are the same. On the bungee I also have a data.db file but with a lower file size.

I am not sure if something got corrupt because UUID_Lookup was gone for a while?

**Comment by kangarko** [comment]
Hey! I think it's because of the fact that we hid UUID_Lookup and set it to false on offline servers. Yeah I think it got reset and started to store in either names/uuids (the other way around). I do apology and that was a mistake I corrected in an earlier release that readded this option.

**Comment by Sikatsu** [comment]
So do I have to put it on true or how can I solve this from happening after a restart? ;o

**Comment by kangarko** [comment]
Set it on true if you're having online server or bungeecord.

**Comment by Sikatsu** [comment]
It's a bit confusing because I first had to put UUID_Lookup on false in settings.yml before the update to stop it from resetting again. But apparently that doesn't work correctly on a bungeecord setup then? So if I reset it just once more and put it on true, this issue above should be solved?

**Comment by Sikatsu** [comment]
I set it to true. Again some players lost their nickname and chat color, others didn't..

![image](https://user-images.githubusercontent.com/5664135/131575808-545967eb-625c-4123-add0-86eb352bf9e0.png)

**Comment by kangarko** [comment]
Just to clarify, UUID_Lookup on true saves player date by their UUIDs. On cracked servers, UUIDs are generated for each username uniquely, hence they will change and we recommend keeping the option on false.

If you're on BungeeCord then it likely adjusts the server not to generate UUIDs for each username differently and that's when having this option on true comes handy.

We store userdata in two different ways depending on this option. Players who have their data saved on UUIDs will get reset when you change it to false, and the other way around. I am sorry for the confusion!

**Comment by Sikatsu** [comment]
With UUID_Lookup on true some players still seem to get reset now and then. This does not affect everyone.

Players that get reset do not only lose their nickname, but also lose all their other chatcontrol settings like the chatcolor.

Once you have some time, could you look into this specific issue?

**Comment by Sikatsu** [comment]
Today I have lost my nickname and chat color as well. It's weird, but it seems to happen randomly. Atleast every day, but not everyone is affected every day.

**Comment by ElBananaa** [comment]
> Today I have lost my nickname and chat color as well. It's weird, but it seems to happen randomly. Atleast every day, but now everyone is affected every day.

Hey!
I'm sorry to hear that.
Unfortunately, we can't do anything about it.
I'm reopening the issue, but you'll have to wait for Kangarko to fix this issue.

**Comment by Sikatsu** [comment]
Understandable, if anyone happens to have a bungee setup let me know if this also occurs for you with UUID_Lookup on true, altho this also seemed to happen with it on false before. It's honestly weird as of why it happens and why it doesn't affect EVERYONE at once, it's a surprise every day who is affected. I think the nightly server restart is definitely at play here, but when checking the logs everything boots as usual.

Thanks for your answer though!

**Comment by ElBananaa** [comment]
> Understandable, if anyone happens to have a bungee setup let me know if this also occurs for you with UUID_Lookup on true, altho this also seemed to happen with it on false before. It's honestly weird as of why it happens and why it doesn't affect EVERYONE at once, it's a surprise every day who is affected. I think the nightly server restart is definitely at play here, but when checking the logs everything boots as usual.
> 
> Thanks for your answer though!

Well, a propper server restart shouldn't cause any issues i guess, since all data should be saved correctly on shutdown. However, crashes may be the reason of this issue, but still, I don't think so.

Anyways, the main problem here is that the issue is hard to reproduce on Kangarko's side since he doesn't have a complete network with players online on multiple servers. I guess you guys will both need to run deeper tests on your side to find the cause of the issue and fix it ^^

Thanks to your for your understanding! 😉

**Comment by kangarko** [comment]
I am back, I apologies for the waiting time. Currently looking into this and will use a secondary computer for testing with an arbitrary local network in the next few days asap.

**Comment by Sikatsu** [comment]
That's okay, we're really looking forward into the fix. Still login on the server nearly daily to find out I have been reset again (as well for others)

**Comment by Sikatsu** [comment]
I honestly don't know, but could this be related in anyway? https://pastebin.com/5faF2Sbu

**Comment by kangarko** [comment]
Sure it could, I have made a fix for this error, releasing next version in 1h. Thanks!

**Comment by Sikatsu** [comment]
Unfortunately, today some of us lost their nickname and chat color again. While I thought only staff accounts were affected, today I also got the first report from a regular player who lost her nickname.

**Comment by NoobcoreNetwork** [comment]
I have this issue also,. Well, Everything was working perfect, I updated to Java 16 and 1.17.1 from Java 8/1.16.5 and nicknames do not stick at all, Sometimes just logging out and back in will remove the nickname. was all working before updated. no settings changed.

**Comment by NoobcoreNetwork** [comment]
Sorry to be a pain but is there any news or anything I can do to help with the investigation? My people have paid real money for nicknames and stuff and it just won't stay over a reboot, I have my setting and my DB exported if that helps at all,

thanks :)

**Comment by kangarko** [comment]
I've solved a concurrent modification exception on BungeeCord Red which may or may not be related to this problem. Since I have hard times reproducing it the process of solving takes longer than ideal, I apologies. New release will be available in a few hours.

**Comment by Sikatsu** [comment]
Awesome! I'm not sure if that is the issue though, since it appears to happen on a server restart. Possible to add some debug? Maybe we can see something happening that way?

**Comment by Sikatsu** [comment]
Also are we sure nothing changed between the version before UUID Lookup was removed and once it was added back?

**Comment by kangarko** [comment]
I am happy to announce I have rewritten database saving and the issue should be now gone! Regardless of UUID_Lookup option, we now parse the Nick column properly as well as not save the database during loading for enhanced stability.

**Comment by NoobcoreNetwork** [comment]
Im also happy to announce it seems to all be fixed! all servers reboot and the nicknames now sticking, awesome work Kang! thanks man

**Comment by Sikatsu** [comment]
Sigh, on the latest update this appears to be back. Just by kicking someone of the survival server, who then ended up in the lobby under the same proxy, her nickname and chat color reset.

**Comment by kangarko** [comment]
On it right now.

**Comment by Sikatsu** [comment]
Thank you..

**Comment by kangarko** [comment]
I'll follow up on https://github.com/kangarko/ChatControl-Red/issues/1511

**Comment by kangarko** [comment]
Closing, lets continue on 1511 for simplicity. When we solve your errors I believe this will go away too.
