### ISSUE TITLE
Compatibility with mBedwars

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#1293]
`Party: mBedwars`
Plugin:[https://www.spigotmc.org/resources/%E2%AD%95-marcelys-bedwars-%E2%AD%95-4-0-%E2%AD%90-supports-1-7-1-16-%E2%AD%90-accepts-qiwi-psc-sofort-and-more.13622/]( https://www.spigotmc.org/resources/%E2%AD%95-marcelys-bedwars-%E2%AD%95-4-0-%E2%AD%90-supports-1-7-1-16-%E2%AD%90-accepts-qiwi-psc-sofort-and-more.13622/)

**Comment by kangarko** [comment]
I am sorry my plate is very full in the coming months to be able to add a special integration.

However, you can read Listener Priorities article on our Wiki and try playing with them to see if that fixes your issue!
