### ISSUE TITLE
Suggestion: Change to default message files on BungeeControl

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1295]
I would like to suggest changing the default files in BungeeControl for ``join.rs``, ``switch.rs``, and ``quit.rs`` as shown below.

Quit.rs example
https://pastebin.com/Q8aCvvmA

Switch.rs example
https://pastebin.com/rw94Q17H

Join.rs example
https://pastebin.com/Y2Y3KfrK

---

#### 1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
These changes are based on the join/switch/quit messages prior to the addition of the bungee supported join/switch/leave messages based on permissions etc.

In the examples above I have made examples of how you can create such messages but also have ones that are hidden for staff etc. Using the operators in https://github.com/kangarko/ChatControl-Red/wiki/Messages Which should help people edit such files without taking extra time to seek help if they haven't used chatcontrol before etc.

---

#### 2. What would happen if we won't implement this feature? How's your server being affected?
As this suggestion is purely based on the default files, there would be no major drawbacks however I believe such change would allow people to edit such files at a faster speed (mainly if they haven't done so before) as this would provide a good example of how to have different messages for different groups based on permission nodes, etc.

**Comment by kangarko** [comment]
Love it, thank you very much, added right now!
