### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by BudkaBudka** [kangarko/ChatControl#1296]
How do I change player's username to its nickname when they communicate through discord?

<img width="353" alt="Screenshot 2021-09-01 at 21 42 31" src="https://user-images.githubusercontent.com/88207034/131742190-fa056233-89ea-4631-9b82-4511def4b76e.png">

**Comment by ElBananaa** [comment]
> How do I change player's username to its nickname when they communicate through discord?
> 
> <img alt="Screenshot 2021-09-01 at 21 42 31" width="353" src="https://user-images.githubusercontent.com/88207034/131742190-fa056233-89ea-4631-9b82-4511def4b76e.png">

Hey!
You can't. The name shown ingame is the name of the user who sent the message on discord.

**Comment by BudkaBudka** [comment]
> > How do I change player's username to its nickname when they communicate through discord?
> > <img alt="Screenshot 2021-09-01 at 21 42 31" width="353" src="https://user-images.githubusercontent.com/88207034/131742190-fa056233-89ea-4631-9b82-4511def4b76e.png">
> 
> Hey!
> You can't. The name shown ingame is the name of the user who sent the message on discord.

Is this the beauty of 'customization'? It literally ruins everything. Are you sure there is no way around it?

**Comment by kangarko** [comment]
I am sorry, in 2-3 years that we support DiscordSRV you're the first who've requested this. 

You can of course create your own JavaScript variable where you explicitly return a different username if the given username is what you sent above, but you'd have to do it manually for every username.
