### ISSUE TITLE
chinese word will not logging

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1297]
ChatcontorlRed will not logging any chiese words

[07:45:13 INFO]: [pm] Rz_Dco -> TF_YingCheng: 好
[07:45:14 INFO]: [mysql] Updating MySQL with: INSERT INTO ChatControl_Log VALUES('', '2021-08-26 07:45:13.398', 'private_message', 'Rz_Dco', '[\"TF_YingCheng\"]', '', NULL, NULL, NULL)
![image](https://user-images.githubusercontent.com/29138111/131808416-0d32b113-9909-460f-ad82-c4d30af4a52f.png)

other plugin work normally
![image](https://user-images.githubusercontent.com/29138111/131808474-d4d88b4f-deb7-425a-8826-00ea1c1e92e5.png)
![image](https://user-images.githubusercontent.com/29138111/131808493-8c1e7bd4-ad59-4a1b-93b7-c00845a1b259.png)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Yes you already opened another ticket which I replied to, we'll have a look after holidays (2-3weeks approx, sorry for waiting!)
