### ISSUE TITLE
Discord channel messages from discord

### ISSUE THREAD

**Issue by BudkaBudka** [kangarko/ChatControl#1298]
Hello!

I have created a channel called 'staff'. I connected it to a channel 'staff' in my discord server. When I send messages in-game they are displayed in discord. It works fine MC->Discord. But when I type inside 'staff' channel on discord messages are not send in-game. What's the issue here?

**Comment by kangarko** [comment]
Have you linked the channel as per our Wiki guide? We have updated this guide just recently, it's recommended to recheck it :)

Also set Debug key in settings.yml to ["discord"], restart server (not reload) and post me console messages when someone types in "staff" channel on Discord and nothing is shown on Minecraft. You have to link it with Discord_Channel_Id option for the "staff" channel on ChatControl.

**Comment by kangarko** [comment]
I am on a two-week vacation, assuming the advice above will be helpful I am closing this and will return to you if you comment below when I can!
