### ISSUE TITLE
Add a delay to spam similarity check

### ISSUE THREAD

**Issue by idkw** [kangarko/ChatControl#13]
The anti-spam chat similarity check is rather annoying.
When a player says "hello" in the lobby then plays a game in another server then goes back to lobby 10 minutes later, if he says "hello" again, it gets caught by the anti spam.

Can you add a configurable delay in seconds for the anti spam similarity check. This way it would prevent repeating "hello" in the last 5 seconds for example, but it would still allow to say "hello" twice if the two words are separated by more than 5 seconds.

**Comment by EvilOlaf** [comment]
That's why I disabled the duplicate check at my site by granting the bypass node to everyone.

**Comment by idkw** [comment]
Ok but why do you use ChatControl then if not for anti spam ?

**Comment by kangarko** [comment]
I would rather add some cache cleanup, because the last message it's cached, I can add a repeating task that will wipe the memory. I will work on it when I have some time :)

**Comment by kangarko** [comment]
The premium version received an option to reset player's data on quit. I will add it onto the free version soon, too.

**Comment by kangarko** [comment]
Added in 5.2.0
