### ISSUE TITLE
Spamming characters?

### ISSUE THREAD

**Issue by jb42300** [kangarko/ChatControl#130]
How do i block players for spamming a character x amount of times?

set limit to 5
E.G: "ohhhhhhhhhhhhhhhhhhhhhh" (Make that turn into "ohhhhh")
And also message them saying dont spam characters

**Comment by kangarko** [comment]
Here's an example rule that would suit:

match (.)(?=([a-z])\1{5})
then warn Please do not spam repetitive characters.
then replace

**Comment by jb42300** [comment]
Thank you!
