### ISSUE TITLE
1.16.3 | /msg broken, #128 confirmed

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#130]
I tested it out with 2 mine accounts, both connected from BungeeCord, and when i try to /msg my second acc, it works really strange - one time is works fine, and the next time it says "player is not online on this server"

Console: 
![image](https://user-images.githubusercontent.com/62369973/99790617-702a1800-2b35-11eb-954f-a808599d2eca.png)
(No errors)

In-game screenshot:
![image](https://user-images.githubusercontent.com/62369973/99790659-7ddf9d80-2b35-11eb-8aea-e3978a3d0757.png)

**Comment by Godlycreations** [comment]
I get the same issue, this comes and goes, it does not give out any errors in console. Sometimes we can send the message, then it just randomly stops finding that player. It is also not sending /tell over bungeecord. I am using 1.16.4 BungeeCord and MySql

**Comment by kangarko** [comment]
Going to investigate, can you guys please send you ChatControl Red as ZIP folder?

**Comment by PascalBrassat** [comment]
From what I have gathered on my end, if you want to lock into a chat it will lose the messaging and display the following message; https://i.imgur.com/A9vz0tO.png

but if i just do /msg removidoa Hi it will go through completely fine.

Also i am unsure if it is intentional, but when pming I still have to type out the whole username, and cant just do /msg pab, but have to do /msg pab_jr

**Comment by Godlycreations** [comment]
Updating to CHC 10.1.0 and making the changes in the configs has fixed this issue on my BungeeCord/MySql servers. Messages are being sent and received correctly. Yes, the tab complete for /msg is not working, however, I can use /tell and it does tab complete for me.

**Comment by NerdyBirder** [comment]
We have this issue randomly on my server and also have an issue where messages are being sent to the wrong player even when the username was typed in full. Doesn't happen all the time but happens sometimes.

**Comment by kangarko** [comment]
Let's continue here, please complete steps 1 and 2 outlined at: https://github.com/kangarko/ChatControl-Red/issues/128
