### ISSUE TITLE
New line not working for /chc mute

### ISSUE THREAD

**Issue by thechckn** [kangarko/ChatControl#130]
This is my localization/messages_en.yml file: https://gist.github.com/thechckn/047cb484cc03857600ce#file-emxwoimty-txt-L27-L28

As seen in the lines highlighted, I have a message displayed for /chc mute, if the message is pasted into console and executed as /bc it works perfectly, but ChatControl refuses to recognize the \n symbol. This is how the message looks from ChatControl.
![image](https://cloud.githubusercontent.com/assets/2747816/8147357/c003d128-122b-11e5-97c2-377b26b44d7c.png)

**Comment by kangarko** [comment]
Strange, to me, "\n" doesn't work in console neither. I have added message splitting by "\n" when broadcasting, but at some point in Minecraft it became broken on some systems, I don't know why.

**Comment by kangarko** [comment]
I just discovered bukkit's way to make multiline comment:

      Mute_Broadcast: |-
        This is an example of multi-line.
        Use it if the new line character 
        is not working for you
