### ISSUE TITLE
1.16.5: Unable to send messages/commands to a specific server

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1301]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

I'm unable to test this on proxy setup but I'll try my best to explain the issue.
This issue is seen when using
``/chc announce``  with the ``server:<server_name>`` parameter
or
``/chc forward``

for the ``/chc announce`` command it seems the ``server:<server_name`` parameter does not work at all, while for the ``/chc forward`` command, it seems to only say that ``bungee`` is available.

here is a screenshot of me trying to use ``/chc announce chat`` but with the ``server:<server_name>`` parameter. The command itself works fine if the ``server:<server_name>`` parameter is not used.
![image](https://user-images.githubusercontent.com/48093184/131916256-c646e5e0-1989-4c9d-af8c-736deee389eb.png)

here is a screenshot of ``/chc forward`` only showing bungee despite me being online and other players on different servers.
![image](https://user-images.githubusercontent.com/48093184/131916435-66cbe244-9d73-4eb6-bf7c-a755127ebea2.png)

**Comment by Alexz1008** [comment]
I may be having a similar problem (with spigot paper 1.17.1). It seems only some of my servers are detected. I have 5 total potential targets: Bungee, Towny, Red, Blue, and Green. On Towny, only Bungee and Towny are valid targets. On Red, Bungee, Towny, Red, and Green are targets. In other words, it seems random what servers are valid targets. I tried doing /chc reload on Towny to see if it would update the targets, but it seems to be random (it added Red to the targets but that's it).

**Comment by TheIntolerant** [comment]
> I may be having a similar problem (with spigot paper 1.17.1). It seems only some of my servers are detected. I have 5 total potential targets: Bungee, Towny, Red, Blue, and Green. On Towny, only Bungee and Towny are valid targets. On Red, Bungee, Towny, Red, and Green are targets. In other words, it seems random what servers are valid targets. I tried doing /chc reload on Towny to see if it would update the targets, but it seems to be random (it added Red to the targets but that's it).

So just to add clarification, basically if no one is online the targeted server, it will be unavailable via /chc forward etc.

**Comment by Alexz1008** [comment]
> So just to add clarification, basically if no one is online the targeted server, it will be unavailable via /chc forward etc.

Oh I feel dumb lol, I even read that in the wiki. I just didn't realize it would show as a tab complete option, I thought it'd just give an error. Ok nvm then, I don't have the same issue.

**Comment by TheIntolerant** [comment]
After disabling the cluster feature this issue was nonexistent.

I personally don't use the cluster feature, I was just testing out some things.

I'll keep this issue open in case it's something that needs to be looked into.

**Comment by kangarko** [comment]
Thanks for clarifying, yeah we remove empty servers since we can't send data to them due to how the plugin messaging channel is implemented, so there's no point in announcing messages there anyways.
