### ISSUE TITLE
Player not online when /msg cross server

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1302]
When messaging (with /msg and /r) in game with players I sometimes get a "player not online" notification when sending a message. The player definitely is online. Some players and a few of my admins have noticed the same. I can’t find a rhythm or pattern in it appearing, So I will say it happens "sometimes". I am sorry I cannot be more accurate.

I notice it happens allot when I send a message Cross server (via bungee). Cant say that i have noticed this happening when me and the player are on the same server.

Here is what I see in game:

![image](https://user-images.githubusercontent.com/10013800/132017185-6caa9635-d5e9-4191-a739-c16dabd89b31.png)

debug: https://ufile.io/6e93xy8j
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey!
Did you try to play with the `UUID_Lookup` feature in the settings file?

**Comment by donvdp** [comment]
hi ElBananaa,
I have not touched this setting.

![image](https://user-images.githubusercontent.com/10013800/132234853-222954a1-5bd2-4ada-8473-ac115dfc8d45.png)


Since we are an online server with only real accounts i suppose this setting is correct the way it is.

**Comment by donvdp** [comment]
![](https://cdn.discordapp.com/attachments/884450087768576080/884450278089310319/unknown.png)

another player today reported the problem while they were both on the same server.
So this does not only happen when using /msg cross server.

**Comment by Alexz1008** [comment]
I can also vouch that this issue exists, using latest ChatControl and BungeeControl on latest spigot paper 1.17.1 java 16. The issue happens to me equally cross-server and within the same server, with no errors in the console.

I don't know if this is relevant, but things keep resetting every restart too. Nicknames and spy preferences are reset on restart, even though the mysql is hooked up and working up until restart.

**Comment by ElBananaa** [comment]
Hey,
Sorry for the delay.
Due to health issue, I can't be as present as I wish I could be.

Unfortunately, only Kangarko could help you more on this 😕 and he's on vacation until the 16th, so please be patient, and wait for an answer from him ^^

Also, I'd like to let you all know that, I never had this issue with a single-server setup. So, as a tempfix, I'd suggest simply disabling the bungee integration for now. While this means cross-server nicks tab-completion won't work, at least, it should work flaswlessly for players on the same server.

**Comment by kangarko** [comment]
I'm investigating this right now, thanks for your patience guys!

**Comment by kangarko** [comment]
Let's continue here: https://github.com/kangarko/ChatControl-Red/issues/1292
