### ISSUE TITLE
1.17.1: DiscordSRV not send messages

### ISSUE THREAD

**Issue by Toki-teki** [kangarko/ChatControl#1304]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Hello. My server not send messages discord > Minecraft and Minecraft > discord.
This happened after I updated the plugins to newer versions.
This is my question on DiscordSRV support:
https://support.scarsz.me/transcript/Pmt7e4kAS3KUUOJbedzypw
Debug:
[Uploading debug.zip…]()

**Comment by Toki-teki** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7111721/debug.zip)

**Comment by Toki-teki** [comment]
Thanks, I have already fixed this

**Comment by Skizzles** [comment]
@Toki-teki how did u resolve this issue as I have a similar one?

**Comment by kangarko** [comment]
I recommend you see https://github.com/kangarko/ChatControl-Red/wiki/Discord
