### ISSUE TITLE
1.17.1: First Joins

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1306]
For the option in join.rs: 
# An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server is in 1.13, 1.14, 1.15, 1.16 or 1.17
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
message: 
- &f&lWelcome {player} to &x&f&f&d&5&7&e&lExeosCraft&f&l! Please see &x&f&f&d&5&7&e&l/help&f&l and &x&f&f&d&5&7&e&l/rules&f&l!

How can I make that message appear server-wide? Just set group default? I want both the new player and all online players to see that message.

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by TheIntolerant** [comment]
Hey, the name of the groups do not impact who sees the message, only the operators used within each group, however none of the operators used in your example should impact view-ability of such messages. In your case, I suspect it hasn't been enabled. 

Depending on what message types you want enabled in your settings file, under. ￼"messages:" you should see this and this is where you enable specific message types, in this example i enabled timed, join and quit messages.


![image](https://user-images.githubusercontent.com/48093184/132507774-2da55fa2-1cdf-48bc-8dce-ac533042d185.jpeg)

**Comment by HorusApl** [comment]
I have that enabled, as normal joins appear without a problem.

**Comment by kangarko** [comment]
By default everyone should see this message, we do not prevent anyone from seeing it unless other plugins block it or you have "require perm" operator there.

**Comment by HorusApl** [comment]
I am using the one that comes with the plugin originally, just edited for the actual message. No one sees the message (except for maybe the person joining for the 1st time, which I can't confirm).
The message:
```rs
"# An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server is in 1.13, 1.14, 1.15, 1.16 or 1.17
group default
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
message: 
- &f&lWelcome {player} to &x&f&f&d&5&7&e&lExeosCraft&f&l! Please see &x&f&f&d&5&7&e&l/help&f&l and &x&f&f&d&5&7&e&l/rules&f&l!"
```

**Comment by ElBananaa** [comment]
Hi,
You're having a pretty weird issue. Timed messages should be sent to the whole server, so the whole server should be able to see this message.
Could you please provide us your debug file so we can have a look at it?

**Comment by HorusApl** [comment]
I agree it's weird, and to be clear: TImed messages work 100%. So my auto-broadcast messages are perfectly fine, as well as normal join/quit messages. Only issue is when the original "Welcome" message should display server-wide when a new player joins
[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/7229282/debug.1.zip)
.

**Comment by ElBananaa** [comment]
> I agree it's weird, and to be clear: TImed messages work 100%. So my auto-broadcast messages are perfectly fine, as well as normal join/quit messages. Only issue is when the original "Welcome" message should display server-wide when a new player joins
> [debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/7229282/debug.1.zip)
> .

Yes, sorry, by timed messages, I meant join/quit messages. Thanks for providing us your debug file.
According to your debug file, you're using a pretty old version of the plugin, please update to the very latest version of the plugin, hopefully it will solve the issue.

**Comment by HorusApl** [comment]
I have since updated and the issue is the same.

**Comment by ElBananaa** [comment]
> I have since updated and the issue is the same.

Hey,
Could you please provide us an updated debug file (with the latest version of the plugin)?

**Comment by HorusApl** [comment]
[debug (2).zip](https://github.com/kangarko/ChatControl-Red/files/7404203/debug.2.zip)

**Comment by HorusApl** [comment]
Also, this has happened for about 10 versions now as you can see from the record. I am aware it's 3 versions behind, and have updated since. It isn't a version issue.

**Comment by ElBananaa** [comment]
> Also, this has happened for about 10 versions now as you can see from the record. I am aware it's 3 versions behind, and have updated since. It isn't a version issue.

Hey, thanks, however you don't use the latest version of the plugin with the file you provided.
I know this isn't related to the version since it works perfectly fine for everyone else, but still, we need the updated debug file in order to properly do our job...

**Comment by HorusApl** [comment]
[debug (3).zip](https://github.com/kangarko/ChatControl-Red/files/7406219/debug.3.zip)

**Comment by HorusApl** [comment]
And my current join.rs file:

group default
message:
- join-welcome

# An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server is in 1.13, 1.14, 1.15, 1.16 or 1.17
group default
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
message: 
- &f&lWelcome {player} to &x&f&f&d&5&7&e&lExeosCraft&f&l! Please see &x&f&f&d&5&7&e&l/help&f&l and &x&f&f&d&5&7&e&l/rules&f&l!

**Comment by ElBananaa** [comment]
Alright, thanks.
So your issue is caused by the fact that rules are read from the top of the file, to the bottom, and the plugin only reads the first rule that can be applied to a player, which is, in your case, the 1st rule.
To fix this, simply place your welcome message above your default join message:
<details>
  <summary>Working first join message</summary>

```rs
# An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server is in 1.13, 1.14, 1.15, 1.16 or 1.17
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
message: 
- &f&lWelcome {player} to &x&f&f&d&5&7&e&lExeosCraft&f&l! Please see &x&f&f&d&5&7&e&l/help&f&l and &x&f&f&d&5&7&e&l/rules&f&l!

group default
message:
- &7[&6+&7]&r &f{nick}

# An example of First Join Message for 1.7 to 1.12. Uncomment the lines below if your server is in 1.12, 1.11, 1.10, 1.9, 1.8 or 1.7.
#group firstjoinmessage
#require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_TICK) <= 1
#message: 
#- &7Welcome to the server &c{player} &7!
```
</details>

Edit: I just made a pull request on the default join.rs file to avoid this issue in the future:

<details>
  <summary>New default join.rs file</summary>

```rs
# ---------------------------------------------------------------------------------
# Join messages. Uses the same syntax as files in rules/ folder but operators
# are slightly different. For documentation and a quick tutorial, see:
# https://github.com/kangarko/ChatControl-Red/wiki/messages
#
# Rules in this file are read from top to bottom. Set 'Stop_On_First_Match' 
# key in settings.yml only send the first message we can, to the player (based on
# operator conditions).
# ---------------------------------------------------------------------------------

# Please make sure to keep your first join message at the top of the file, above any other join message to avoid any issues.
# An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server is in 1.13, 1.14, 1.15, 1.16 or 1.17.
#group firstjoinmessage
#require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
#message: 
#- &7Welcome to the server &c{player} &7!

# Please make sure to keep your first join message at the top of the file, above any other join message to avoid any issues.
# An example of First Join Message for 1.7 to 1.12. Uncomment the lines below if your server is in 1.12, 1.11, 1.10, 1.9, 1.8 or 1.7.
#group firstjoinmessage
#require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_TICK) <= 1
#message: 
#- &7Welcome to the server &c{player} &7!

group default
message:
- &7{player} &fhas joined the game
```
</details>
