### ISSUE TITLE
1.16.5: Issue with bungeesynctask

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1307]
Plugin version : 10.6.3
Minecraft Version: 1.16.5 (Airplane)
MySQL: false
BungeeCord: false (my server is under velocity, but bungeecord is FALSE in my config

Some weeks ago I opened an issue because I had a "bungeesynctask" running but I disabled bungeecord in my config (issue https://github.com/kangarko/ChatControl-Red/issues/1227), but now I still got this task 
<img width="313" alt="Screenshot_6123" src="https://user-images.githubusercontent.com/31826333/132530580-d626dffa-e5b1-413d-b698-c813e3d6832d.png">

So, you maybe forgot something ?

My debug : 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7129695/debug.zip)

**Comment by kangarko** [comment]
I don't think 0.18% is a problem in real life that it affects your gameplay or other plugins. We had to readd the task to non-bungee servers since it still adds essential data and removing it broke other features.
