### ISSUE TITLE
Bungeecord > different messages if a player is chatting on another server

### ISSUE THREAD

**Issue by Erestyy** [kangarko/ChatControl#1309]
Hey! i've a question. Im using CCR since 3 days ago, and setted it up. here is my question. If I'm playing as a player on the lobby, and typing in the chat, then i can see that with my another account like normally, but i also get another message like:

<.PLAYER.> {MESSAGE} >>> WITHOUT THE .

How can i fix this?
Anyone that can help me? I also have a screenshot.

https://prnt.sc/1rmhtji

**Comment by ElBananaa** [comment]
> Hey! i've a question. Im using CCR since 3 days ago, and setted it up. here is my question. If I'm playing as a player on the lobby, and typing in the chat, then i can see that with my another account like normally, but i also get another message like:
> 
> <.PLAYER.> {MESSAGE} >>> WITHOUT THE .
> 
> How can i fix this?
> Anyone that can help me? I also have a screenshot.
> 
> https://prnt.sc/1rmhtji

Hey!
It looks like your message is either sent twice, or processed by two different plugins.
Could you please provide us the `/chc debug` file of your lobby server so we can have more informations about your setup and your configs?

**Comment by kangarko** [comment]
Thanks to Banana for answering!
