### ISSUE TITLE
1.8.7 spigot issues

### ISSUE THREAD

**Issue by xXBarchticXx** [kangarko/ChatControl#131]
Pics of issues and rules
http://gyazo.com/c8b4fdfe95e4e828fe803750f069ffbc
http://gyazo.com/f79610270f51bd8a09bfab282370d0d3
http://gyazo.com/a3a877e0bce4b48731375f77f759eb45
http://gyazo.com/9551687c4c9b3a4d3446b27877dc43ab
http://gyazo.com/1b3baa9e81b1542a446885820d307728
http://gyazo.com/16e7803d0f60b653b121845d8fe03834

**Comment by Rida94** [comment]
Im also having issues with 1.8.7 but its working, tho I hate the console being spammed with bugs, hope it will be updated to 1.8.7

**Comment by xXBarchticXx** [comment]
Any info on this?

**Comment by kangarko** [comment]
Cannot replicate. Please make sure your operators are "handle as", not just "handle".
Example:

>match fuck
>handle swear
is wrong, should be:

>match fuck
>handle as swear

**Comment by xXBarchticXx** [comment]
xD thanks, I completely didn't notice that!
