### ISSUE TITLE
How can I turn off the chat?

### ISSUE THREAD

**Issue by ttt0** [kangarko/ChatControl#1312]
I'm going to make an event and I want to close the chat to everyone, I just want the authorities to write something to the chat, how can I do this, is there such a command in the plugin?

**Comment by TheIntolerant** [comment]
The easiest way to do this would be to use the mute command in chatcontrol and mute a channel/server and than the people with the perm **chatcontrol.bypass.mute** will still be able to talk.

**Comment by kangarko** [comment]
Thanks to gone incognito for answering!
