### ISSUE TITLE
CMI chat groups and the Chat.Limit

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#1313]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

When using CMI chat groups, all chat rules apply to those groups similar to public chat. That's fine. However these chat groups may be more loose than rules that apply to public chat.
Private messages fall under the commands regime. So those differ from public chat. In some way, chat groups are also somewhat private but can't be differentiated in settings from public chat.

Eventually I would like to warn players who talk to fast/much in public with the suggestion that they probably would be better off when they create a chat group or talk via /msg. I think this would be possible if I alter the "Checker.period" message into something like: "If you like to talk that much, consider talking private or by making a chat group by executing /chat create groupname"

Example:
Chat.Limit defines the number of chat messages within a certain amount of time period. This may be more loose than public chat. In other words: public chat should be more strict than chat groups where they should be allowed to talk more frequent. If this Chat.Limit can be defined only for both Public chat as Chat group, than the limit should be defined not very strict to annoy the fun in chat groups. This can lead to more frequent public chat which in their turn annoys other people who can't escape public chat. Because you can't turn off the chat (in the MC client) without losing the possibility to execute commands.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1
> MySQL: true
> BungeeCord: true
> 
> When using CMI chat groups, all chat rules apply to those groups similar to public chat. That's fine. However these chat groups may be more loose than rules that apply to public chat.
> Private messages fall under the commands regime. So those differ from public chat. In some way, chat groups are also somewhat private but can't be differentiated in settings from public chat.
> 
> Eventually I would like to warn players who talk to fast/much in public with the suggestion that they probably would be better off when they create a chat group or talk via /msg. I think this would be possible if I alter the "Checker.period" message into something like: "If you like to talk that much, consider talking private or by making a chat group by executing /chat create groupname"
> 
> Example:
> Chat.Limit defines the number of chat messages within a certain amount of time period. This may be more loose than public chat. In other words: public chat should be more strict than chat groups where they should be allowed to talk more frequent. If this Chat.Limit can be defined only for both Public chat as Chat group, than the limit should be defined not very strict to annoy the fun in chat groups. This can lead to more frequent public chat which in their turn annoys other people who can't escape public chat. Because you can't turn off the chat (in the MC client) without losing the possibility to execute commands.

Hey,
I believe none of these 2 plugins are made to work together with both their chat features enabled, so I guess this can be considered as a bug.
I'd ask you to wait for Kangarko (which can take a week or so since he's on vacation right now) to see if there's anything he can do about it.

In the meantime, the only suggestion I can give is trying to play with the listener priority in ChatControl settings file, and (if it's possible), in CMI config file.
You can find more informations about this on our wiki page : https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities (And don't forget to restart your server each time you change the priority) ^^

**Comment by x1p** [comment]
> I'd ask you to wait for Kangarko (which can take a week or so since he's on vacation right now) to see if there's anything he can do about it.

I'm not in any hurry :-)

> 
> In the meantime, the only suggestion I can give is trying to play with the listener priority in ChatControl settings file, and (if it's possible), in CMI config file.

The priority I've set is perfect. I do want CHC to check for Rules and grammar.

To say it the other way around: I would like Chat.Limit (only) to exclude CMI chat groups.

The way I see it is that Chat Groups, actually as well as PlotSquared's Plot Chat, both are nor Public Chat nor Private Chat. If you change Priorities, than you have to accept that it is handled as Chat. It's either "in" or "out". No exceptions are possible to fine-tune it.

Summary of the possible scenario's:
1. Chat_Listener_Priority: HIGH (default) --> Chat groups & Plot chat is not controlled: Players can swear whatever they want. 
2. Chat_Listener_Priority: LOWEST --> Chat groups & Plot chat is controlled in a descent manner: Chat is as strict as public chat.

1 is highly undesirable.

Ideally, players can chat in a descent way, but faster without annoying everyone else
I realize that this is not a straight forward request. So I've already accepted that this may take some consideration whether this is doable/realizable.

**Comment by x1p** [comment]
I don't to subscribe if and how Kangarko should implement this. But perhaps the following could be considered.
CMI chat groups and plot chats always appear in-game/on the console in a certain manner. Perhaps the Chat.Limit can be expanded with a whitelist like other settings.

Console example:
`[14:31:00] [Server thread/INFO]: [Chat] ChatGroupName Player123: Text message blah blah`
`[14:32:00] [Server thread/INFO]: [Plot Spy] [6;-9] Player123: Text message blah blah`

Chat in game example:
`[Chat] ChatGroupName Player123: Text message blah blah`
`[Plot Chat] [6;-9] Player123: Text message blah blah`

Config example:
```yaml
    Limit:
      
      # The period to check. Set to 0 to disable.
      Period: 30 seconds
      
      # How many messages can players send maximum in the period above?
      Max_Messages: 5
      
      Whitelist:
      - '^[Chat]'
      - '^[Plot Chat]'
```

**Comment by kangarko** [comment]
Thanks for suggestion. Technically feasible this may be a problem since we often don't get to see the prefix such as [Chat] from other plugins, and there is not an easy way to check for this in the main chat event we are listening to. Another problem is that adding another set of config options would be extremely confusing, having both Whitelist_Message and Whitelist_Format would double the amount of stuff in the config and make things unnecessarily complex for 99% people who don't use it. For these reasons I am deciding to at least postpone this to a later reconsideration, Thanks.
