### ISSUE TITLE
1.17.1:Emoji's don't seem to work.

### ISSUE THREAD

**Issue by Timtendo12** [kangarko/ChatControl#1314]
Minecraft Version: 1..17.1
MySQL: true
BungeeCord: true

Hi! I have emoji's in my texturepack. It changes chinese characters to a certain part of a texture. It works fine in chat but it seems like chatcontrol's emoji dont work. So :love: doesn't change to the characte i've assigned it to. 

Example:

`
#match :-\(
#then replace ꍃ

#match (:\))|(;\))
#then replace 鄐

#match \:star\:
#then replace 鄔
`
![image](https://user-images.githubusercontent.com/41442518/132957912-918a718c-db31-454a-93bc-1d3c9e987b35.png)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7148343/debug.zip)

I hope I gave you enough information, If not I'll add more info asap.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1..17.1
> MySQL: true
> BungeeCord: true
> 
> Hi! I have emoji's in my texturepack. It changes chinese characters to a certain part of a texture. It works fine in chat but it seems like chatcontrol's emoji dont work. So :love: doesn't change to the characte i've assigned it to.
> 
> Example:
> 
> `
> #match :-(
> #then replace ꍃ
> 
> #match (:))|(;))
> #then replace 鄐
> 
> #match ⭐
> #then replace 鄔
> `
> ![image](https://user-images.githubusercontent.com/41442518/132957912-918a718c-db31-454a-93bc-1d3c9e987b35.png)
> 
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7148343/debug.zip)
> 
> I hope I gave you enough information, If not I'll add more info asap.

Heyn
The emojis aren't working because they're in a comment.
You need to remove the `#` before each line to uncomment them.
