### ISSUE TITLE
Allowing certain URls and ips

### ISSUE THREAD

**Issue by ItzSwagsire** [kangarko/ChatControl#132]
Hello,

I would like to allow my website url and my server ip, but how do i do this with the advertising filter?

Thanks

**Comment by EvilOlaf** [comment]
Add the url and ips you want to whitelist to `ignore string` of your advertisement filter rule.

**Comment by ItzSwagsire** [comment]
EvilOlaf which file is that in?

**Comment by kangarko** [comment]
Open rules/rules.txt and search for 'Domain/URL filter'. There you'll find the information necessary to adjust the filter according to your needs.
