### ISSUE TITLE
1.17.1: Issue hiding server plugins with the regex

### ISSUE THREAD

**Issue by ItWasEnder** [kangarko/ChatControl#1320]
So I am trying to use regex `^Plugins \(([1-9]?[1-9])\): (.*)$` to replace the list on my server, but it does not seem to be triggering. I have checked this with [regexr](https://regexr.com/65n1m) and it seems to be valid but it does not seem to work in game.

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: true

**Comment by TheIntolerant** [comment]
Hey, I have tested this and couldn't reproduce this issue. Please make sure all dependencies are up to date, which includes ProtocolLib for packet rules to work.

**Comment by ItWasEnder** [comment]
> Hey, I have tested this and couldn't reproduce this issue. Please make sure all dependencies are up to date, which includes ProtocolLib for packet rules to work.

Were you using `^Plugins \(([1-9]?[1-9])\): (.*)$` or something else? Also everything seems to be updated to that latest version, so I'm kind of stuck on what to do.

**Comment by TheIntolerant** [comment]
This is the rule I used in ``plugins/ChatControlRed/rules/packet.rs``
```rs
# Replace the /plugins message.
match ^Plugins \(([1-9]?[1-9])\): (.*)$
then replace &fPlugins (4): &aBetter&f, &aLuck&f, &aNext&f, &aTime
dont verbose
```

---

The only things I can think of that you should check is the following inside ``settings.yml`` for chatcontrol-red.

``Integration.ProtocolLib.Listen_For_Packets`` set to ``true``
![image](https://user-images.githubusercontent.com/48093184/133591572-24d59a06-26d5-4579-8c2f-7a45ee4ee389.png)

``Rules.Apply_On`` has ``packet`` in the list.
![image](https://user-images.githubusercontent.com/48093184/133591704-e99f77ed-8875-4e7e-bd1c-a8aeb7ba0da3.png)

**Comment by TheIntolerant** [comment]
Wait nvm I see the issue now, with your RegEx

So because you did ``[1-9]`` it is only searching from the ranges of 1-9 which doesn't seem like an issue till you have ``20`` plugins as ``0`` is not in this range :P

Also instead of doing ``[0-9]?[0-9]`` etc. I would recommend ``[0-9]+`` as ``+`` matches the previous token between one and unlimited times.


So try using this ``^Plugins \(([0-9]+)\): (.*)$`` and that should fix this issue.
