### ISSUE TITLE
Suggestion: Change to default file for packet.rs

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1321]
#### 1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.
In the default file for the packets, there is a rule for replacing the "/plugin" message. As it is right now, chatcontrol will only match the /plugin message if the server only has between 1-9 plugins on it.

This change will mean users with 1, 2, 5, or 9+ plugins on their server, do not need to edit this rule as the "/plugin" message still gets matched.

My suggestion is to edit the rule in the default file mentioned above so it looks something like this:
```rs
# Replace the /plugins message.
match ^Plugins \(([0-9]+)\): (.*)$
then replace &2There are &6$1 &2plugins: &7$2
dont verbose
```
Instead of having the RegEx as ``^Plugins \(([1-9])\): (.*)$``

#### 2. What would happen if we won't implement this feature? How's your server being affected?
By adding ``+`` after ``[0-9]`` chat control will now match the ``/plugin`` message for servers regardless of the amount of plugins it has thus saving time as server admin/owners do not need to edit such RegEx as seen here #1320

**Comment by kangarko** [comment]
Great find, thank you!
