### ISSUE TITLE
1.17.1: Updated to 10.6.3 (Clean Install) Started getting FoException on player join.

### ISSUE THREAD

**Issue by ItWasEnder** [kangarko/ChatControl#1322]
Debug: https://ufile.io/czn9buta
Error.log: https://hastebin.com/ecegoqeyet.properties

Everything was working until I downloaded version `10.6.3` after a player joins the server console is just spammed continuously until the player leaves the server.

_Note: I also realized I had UUID_Lookup enabled so I tried to turn it off but the error still occured_ 

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: true

PS> Should I install chat control on the bungee if I only have 1 server behind it or should I only install chat control on the 1 server?

**Comment by TheIntolerant** [comment]
I personally do not have enough knowledge to help with said error, however, to answer your question.

> PS> Should I install chat control on the bungee if I only have 1 server behind it or should I only install chat control on the 1 server?

Even if you only have one server on the BungeeCord Instance, it is still recommended that you install BungeeControl on BungeeCord/proxy server.

Here is a guide about the set up of BungeeControl 
<https://github.com/kangarko/ChatControl-Red/wiki/BungeeCord>

**Comment by ElBananaa** [comment]
> Debug: https://ufile.io/czn9buta
> Error.log: https://hastebin.com/ecegoqeyet.properties
> 
> Everything was working until I downloaded version `10.6.3` after a player joins the server console is just spammed continuously until the player leaves the server.
> 
> _Note: I also realized I had UUID_Lookup enabled so I tried to turn it off but the error still occured_
> 
> Minecraft Version: 1.17.1
> MySQL: false
> BungeeCord: true
> 
> PS> Should I install chat control on the bungee if I only have 1 server behind it or should I only install chat control on the 1 server?

Hey!
Is this a completely fresh install of the plugin, or did you keep the same database and/or same files?

**Comment by ItWasEnder** [comment]
> > Debug: https://ufile.io/czn9buta
> 
> > Error.log: https://hastebin.com/ecegoqeyet.properties
> 
> > 
> 
> > Everything was working until I downloaded version `10.6.3` after a player joins the server console is just spammed continuously until the player leaves the server.
> 
> > 
> 
> > _Note: I also realized I had UUID_Lookup enabled so I tried to turn it off but the error still occured_
> 
> > 
> 
> > Minecraft Version: 1.17.1
> 
> > MySQL: false
> 
> > BungeeCord: true
> 
> > 
> 
> > PS> Should I install chat control on the bungee if I only have 1 server behind it or should I only install chat control on the 1 server?
> 
> 
> 
> Hey!
> 
> Is this a completely fresh install of the plugin, or did you keep the same database and/or same files?

This was a fresh install yes.

**Comment by sarhatabaot** [comment]
This happens to me as well. 
I fixed this on an instance by deleting the log entries. But on bungee I still get this error: https://pastebin.com/6zvhhGmH

Included just one error, but there is ~40MB of this error.

**Comment by ElBananaa** [comment]
I'm not sure to know the cause of the issue...
If you don't mind, please wait for Kangarko to have a look at the issue ^^

**Comment by kangarko** [comment]
This error is caused by inconsistently updated BungeeCord network. When updating ChatControl Red and BungeeControl Red, shut down entire network, update all servers and restart.

Likely an outdated ChatControl Red on some Spigot server of yours.
