### ISSUE TITLE
Warning spam in console | "PLAYERS_SYNC_NAMES" 

### ISSUE THREAD

**Issue by entrati** [kangarko/ChatControl#1323]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Upon entering the server, counsle gets spammed with warnings from CHCR. This is the error form the error.log: https://pastebin.com/ruhBF87h

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1
> MySQL: true
> BungeeCord: true
> 
> Upon entering the server, counsle gets spammed with warnings from CHCR. This is the error form the error.log: https://pastebin.com/ruhBF87h

Hey,
Did you manage to fix your issue?

**Comment by kangarko** [comment]
It was likely fixed by user after he updated the plugin. This error is caused by inconsistently updated BungeeCord network. When updating ChatControl Red and BungeeControl Red, shut down entire network, update all servers and restart.
