### ISSUE TITLE
Is this currently possible? Checking between diferent lines.

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#1324]
Can you currently make filters account messages distributed between lines? Or is there some effective measure to counter filters being bypassed by dividing your message between lines?

Else it would be nice if regexes could check successive lines, at least by the same player.

**Comment by ElBananaa** [comment]
> Can you currently make filters account messages distributed between lines? Or is there some effective measure to counter filters being bypassed by dividing your message between lines?
> 
> Else it would be nice if regexes could check successive lines, at least by the same player.

Hey!
I believe rules check for each word, no matter the number of words, and no matter if they're split between multiple lines.

**Comment by MithrandirCraft** [comment]
You must be right. I just found out it's not just placing IP's through diferent lines, it's my IP filtering regex in "global.rs" that isn't working for some reason.

I'll update the plugin first, then start investigating.

**Comment by ElBananaa** [comment]
Kangarko made a lot of changes on how the rules system works, and, I think, gone-incognito submitted him a better rule for ip filtering. It should be implemented as a replacement of the previous rule.

Try with these ones (These are the updated rules), and let me know if it helps ^^
```rs
# IP filter. 
match [0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}
name ip
# Remove the specified characters using regex (or replace them with dots) BEFORE the message is checked.
before replace dot|\[|\]|\{|\}|\(|\) with .
before replace [\(\[\]\)]|\s*
group advertisement

# Domain/URL filter.
match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|(?<! )c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|(?<! )m(| +)e|i(| +)o)\b
# If you want to ignore your server, put it at the end of ignore string below like: minecraft.net|youtube.com|yourserver.com
ignore string minecraft.net|youtube.com|imgur.com
# You can also uncomment this operator to allow email addresses. Credit: http://emailregex.com/
#ignore string (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
name url
before replace dot|\[|\]|\{|\}|\(|\) with .
before replace [\(\[\]\)]
group advertisement

# Here is the previous version of the domain filter above which is easier to modify but does not block: t e s t . c o m, etc.
# You can add new domains to be blocked by inserting '|your_domain' after '|me' (e.g. '|me|io' for also blocking '.io' domains)
#match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu|me|io)\b
```

**Comment by MithrandirCraft** [comment]
Epic! That may be useful. Even though I actually already made my own rule which I tested on a regex building website... but this one might be better.

Thanks.

**Comment by ElBananaa** [comment]
> Epic! That may be useful. Even though I actually already made my own rule which I tested on a regex building website... but this one might be better.
> 
> Thanks.

You're welcome!
Let me know if it fixed your issue and if I can close it, or if you need anything else 😃

**Comment by kangarko** [comment]
Right now we only check one message at a time, there's no multi line filtering, as it would 1) cause unnecessary lag, 2) add more complexity (we're already pretty complex) and 3) will cause false catches
