### ISSUE TITLE
1.17.1: Nickname blacklisted characters

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1327]
I don't think it is possible to blacklist certain characters currently, but I am running into an issue.

Players started to set their nickname as %chatcontrolred_nick% for some reason and the result is that when I run a command, their nickname parses as my own nickname.

For example:

You set your nickname as that placeholder and when I run /baltop it parses the players nickname as mine, so it looks as if i'm twice in the baltop.

Test example:

![image](https://user-images.githubusercontent.com/5664135/133971884-acfddbbb-3fdf-4045-958a-933f64472db0.png)

**Comment by kangarko** [comment]
The best advice would be to create a new rule in rules/tag.rs to prevent players from placing variables in their tags:

```
match [({|%)]([^{}]+)[(}|%)]
then warn {prefix_error}You cannot use placeholders in your tag!
then deny
```
