### ISSUE TITLE
Allow Book Reading without Permission Node

### ISSUE THREAD

**Issue by blockswerker** [kangarko/ChatControl#1329]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Hello, is it possible to allow players to read books (specifically using Run_Command in a format .yml configuration) without exposing the entire `chc book` command to the player? I'd like them to be able to read my server rules in book form without allowing players to create books in that manner.

Permissions (https://github.com/kangarko/ChatControl-Red/wiki/Permissions) lists only 'chatcontrol.command.book' as the single permission node for all books - reading and writing.

I love ChatControl-Red, I'm finding new uses for it constantly so please keep up the great work!

**Comment by TheIntolerant** [comment]
You should be able to do this via rules.

If your format file had something like

```
Run_Command: "/rules"
```
and you had a book called, "MyRules", if you go into the ``command.rs`` file in the folder ``rules`` and add something like

```
# This gives a player the book called "MyRules" if they type /rules
match ^\/rules$
then book MyRules
then warn &eHere is a book of all the server rules!
then deny
dont verbose
```
You don't need to use the ``then warn`` operator btw, I just added that as an example.

That way when the player clicks on the text to run ``/rules``, it will get the book while not giving them access to ``/chc book`` so they cannot read or save books you can use in rules, etc, which is what you would be able to do with 
``chatcontrol.command.book`` as you mentioned.
