### ISSUE TITLE
EssentialsX msgtoggle does not cancel sound notify

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#133]
When using EssentialsX `msgtoggle` feature the message actually gets cancelled, but if `Sound_Notify` in `settings.yml` (of CHC) is enabled the sound is still played.

ESS 2.0.1 build 342
CHC 5.3.1 (yes, still on free....)

**Comment by kangarko** [comment]
This is a priority issue. The premium version has the ability to change listener's priorities to make the pipeline work as expected: 1. essentialsX cancels the message (whatever priority lower then chatcontrol's), 2. chatcontrol ignores the cancelled event (either HIGH or HIGHEST priority)
PS: Please update to 5.3.4
