### ISSUE TITLE
1.16.5: Will it ever be possible to use "/chc book" without setting "Mail.Enabled" to true

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1330]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hey,
I am enquiring about the usage of ``/chc book`` and wanted to know if it would ever become possible to use the ``/chc book`` command, without enabling the mail system. Especially if you already use a different mail system and do not wish to use that specific feature in chat control red.

![image](https://user-images.githubusercontent.com/48093184/134156149-99fbd93d-ca27-4f8f-a912-3c2dbb151103.png)

Thanks.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hey,
> I am enquiring about the usage of `/chc book` and wanted to know if it would ever become possible to use the `/chc book` command, without enabling the mail system. Especially if you already use a different mail system and do not wish to use that specific feature in chat control red.
> 
> ![image](https://user-images.githubusercontent.com/48093184/134156149-99fbd93d-ca27-4f8f-a912-3c2dbb151103.png)
> 
> Thanks.

Hey!
Sorry this is absolutely unrelated, but could you please provide me your discord tag. Kangarko and I would both like to get it! Thanks :)

**Comment by gone-incognito** [comment]
@ElBananaa ``TheIntolerant#0001``
If you don't mind deleting this once you've noted the discord username so I can remain mysterious ;)

**Comment by kangarko** [comment]
Technical implementation has a difference between a command and a subcommand, "/mail" is a command whereas "/chc book" is a subcommand internally which makes it incompatible and I would have to copy the same code twice, right now we simple run the /mail new command to create a new book and rely on its logic for simplicity. You can however hide the command from players by changing its label to something else.
