### ISSUE TITLE
Hook into the Parties plugin

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1331]
Hey there, I would love to be able to use the emotes rules I made in my party chat plugin (that runs on the bungee), however, I can't seem to let them parse in our party chat. According to the developer ChatControl has to hook into Parties for this, would that be possible?

https://www.spigotmc.org/resources/parties-an-advanced-parties-manager.3709/

**Comment by kangarko** [comment]
Sorry, not right now, we have other priorities to fix and focus on in the coming months.
