### ISSUE TITLE
1.17.1 About showing which channel other players join

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1336]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: false

Is it supposed to show which channels players are joining to non OP players? I don't want non OP players to see which channels other players are joining because it can be pretty floody and I don't think players should know where others are looking or typing.

It looks like the "ShowTips" option can disable those messages, but I as the server owner want to be able to see those messages even while others can't. It's not much of a big deal though.

Is there a way to do this or no?

**Comment by ElBananaa** [comment]
Hey!
The messages are intended to be seen by everybody! However, if you wish to, you can disable these messages by simply replacing, the message line in `localization/message_en.yml` (or `message_fr.yml` if you use the french lang file) with an empty message.
This is how it would look like for join and leave messages, as example:
**Join.Notification (line 68 on the defaut english file):** `Notification: ""`
**Leave.Notification (line 80 on the defaut english file):** `Notification: ""`

**Comment by kangarko** [comment]
Closing, let us know below if you still need help.
