### ISSUE TITLE
1.17.1: How to auto type in command when click on the chat?

### ISSUE THREAD

**Issue by Lemonray114** [kangarko/ChatControl#1337]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Hi, I wanna to ask how to auto type in certain command when the mouse click on the chat?
For example if i type : 
#(text) /(command)
then when i click on the command again it will help me type out the command.

**Comment by ElBananaa** [comment]
Hey, the plugin doesn't offer a such feature. We do support clickable text in the chat, but we don't offer any feature that automatically makes any message including a command clickable. However, you can make any message from our rules, our timed, death, join, quit and kick systems clickable, as same as any parts of your format files.

To do so, please refer to these links : https://github.com/kangarko/ChatControl-Red/wiki/Formats https://github.com/kangarko/ChatControl-Red/wiki/JSON

**Comment by kangarko** [comment]
Thanks to Banana for answering!
