### ISSUE TITLE
1.17.1: Only display highest suffix or prefix in formats

### ISSUE THREAD

**Issue by 0ofland** [kangarko/ChatControl#1338]
I'm currently trying to use Chat control for the pre- and suffixes. 

This is my current setup in the `formats\chat.yml`:
```
  2-suffix:
    Message: ' &8&l[&42&8&l]&r'
    Sender_Permission: "group.2"
  1-suffix:
    Message: ' &8&l[&41&8&l]&r'
    Sender_Permission: "group.1"
```
My problem is that groups i.e. group.1, group.2 inherit permissions of the previous group, so everyone in group 2 would also technically be in group 1 so for players in group 2 both suffixes would be shown.
Is there a function in chat control for only displaying the highest suffix or prefix?

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> I'm currently trying to use Chat control for the pre- and suffixes.
> 
> This is my current setup in the `formats\chat.yml`:
> 
> ```
>   2-suffix:
>     Message: ' &8&l[&42&8&l]&r'
>     Sender_Permission: "group.2"
>   1-suffix:
>     Message: ' &8&l[&41&8&l]&r'
>     Sender_Permission: "group.1"
> ```
> 
> My problem is that groups i.e. group.1, group.2 inherit permissions of the previous group, so everyone in group 2 would also technically be in group 1 so for players in group 2 both suffixes would be shown.
> Is there a function in chat control for only displaying the highest suffix or prefix?
> 
> Minecraft Version: 1.17.1
> MySQL: true
> BungeeCord: true

Hey!
If your ranks prefix are already defined in your permission plugin (like luckperms with prefixes/suffixes https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta), you could simply use a single part and the `{player_prefix}` and/or `{player_suffix}` placeholders. These will only display the player's main rank prefix/suffix. (Here's a list of all the plugin available placeholders : https://github.com/kangarko/ChatControl-Red/wiki/Variables)
This is how it would look in your format file:
```yaml
  player-suffix:
    Message: ' {player_suffix}'
```

**Comment by 0ofland** [comment]
Yeah, I think I could make a workaround with my old system, I just wanted to know if there was a direct option for that. I figured that I might be able to do it with the JavaScript Variables and the %vault_ranksuffix% placeholder, but I haven't figured out how.

**Comment by ElBananaa** [comment]
> Yeah, I think I could make a workaround with my old system, I just wanted to know if there was a direct option for that. I figured that I might be able to do it with the JavaScript Variables and the %vault_ranksuffix% placeholder, but I haven't figured out how.

Well, you don't need to use JavaScript variables with `%vault_ranksuffix%` since it'll also return the player's main rank suffix. Btw, our `{player_suffix}` variable is based on vault's suffix, and you need to replaces `%%` with `{}` in our plugin.
![image](https://user-images.githubusercontent.com/53318613/134713934-ff2bc388-eb0a-4e73-8563-85dec90277a1.png)

**Comment by 0ofland** [comment]
So how would I create a Sender_Permission that sends the `Message: ' &8&l[&42&8&l]&r'` _if_ `{player_suffix} = "1"`?

**Comment by ElBananaa** [comment]
> So how would I create a Sender_Permission that sends the `Message: ' &8&l[&42&8&l]&r'` _if_ `{player_suffix} = "1"`?

Well, first of all, this will only work if the output of the `{player_suffix}` is `1` for players.
Also, you don't need to use Sender_Permission in this case, but Sender_Condition:

```yaml
  2-suffix:
    Message: ' &8&l[&42&8&l]&r'
    Sender_Condition: '''{player_suffix}'' == ''2'''
  1-suffix:
    Message: ' &8&l[&41&8&l]&r'
    Sender_Condition: '''{player_suffix}'' == ''1'''
```

**Comment by 0ofland** [comment]
That worked perfectly, thank you very much!
