### ISSUE TITLE
1.16.4: partychat multiple messages

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl#134]
![image](https://user-images.githubusercontent.com/66204768/99840524-fe6dc080-2b6c-11eb-962b-ffe9bbf4aec2.png)
This happens with alot of messages in spy (in this case partychat, but also with mail deleting.

**Comment by kangarko** [comment]
Edit your title to include Minecraft version such as 1.16.4 | etc.

Send me your ChatControl as ZIP please.

**Comment by JessePesse123** [comment]
Update: it fixes after a restart, is related to the double join messages asweel. When you reload it breaks again.

**Comment by JessePesse123** [comment]
in latest chatcontrol also double leave messages

**Comment by JessePesse123** [comment]
[ChatControlRed.zip](https://github.com/kangarko/ChatControl-Red/files/5577463/ChatControlRed.zip)

**Comment by kangarko** [comment]
Thanks, investigating right now

**Comment by kangarko** [comment]
I could not reproduce so I assumed it is fixed on the latest version, please wait for its release and comment below if still having issues.

Please note I did not find the party chat in your ZIP and you did not have bungee enabled.
