### ISSUE TITLE
Command to turn off notifications?

### ISSUE THREAD

**Issue by ItzSwagsire** [kangarko/ChatControl#134]
Hi,

Is there a command/permission node to allow my staff to turn off their notifications of the player's original message if they swore, advertised, etc.. in game?
Thanks

**Comment by kangarko** [comment]
Yes,

following permission give the staff ability to view cancelled messages from handlers by default:
chatcontrol.notify.ad
chatcontrol.notify.swear

simply negate those (-chatcontrol.notify.ad, etc..) to take away this ability.
