### ISSUE TITLE
1.16.5 : ignore issue

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1341]
Plugin version : 10.6.4
Minecraft Version: 1.16.5 (Airplane)
MySQL: false
BungeeCord: false (my server is under velocity, but bungeecord is FALSE in my config

My debug (on 10.6.3, config didn't change since this time) : 
[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/7230349/debug.1.zip)

When you /ignore someone, he tells you "XX is now ignored", but he doesn't appear in the /ignore list.

and if you do "/ignore XX" again, it stills say "XX is now ignored", and he is still ignored.
So impossible to un-ignore him

**Comment by TheIntolerant** [comment]
Hey, I couldn't reproduce this issue but I have had similiar issues in the past where a command was getting overwritten by another plugin such as grief prevention's /ignore command.

Please try running ``/ignore`` and the output should look like this if your server is using /ignore from chatcontrol, if not than it is most likely another plugin causing this.
![image](https://user-images.githubusercontent.com/48093184/134793030-0bb9e727-ada8-45e2-ac06-d8c8f8a13979.png)

One way you could fix the above is changing ``Ignore.Command_Aliases`` in your settings.yml file. So the ignore command isn't the same as the one from the other plugin.

**Comment by kangarko** [comment]
Thanks to gone for answering! Closing in good faith that it will help you resolve this, let me know below if otherwise.

**Comment by WarnDa** [comment]
> Hey, I couldn't reproduce this issue but I have had similiar issues in the past where a command was getting overwritten by another plugin such as grief prevention's /ignore command.
> 
> Please try running `/ignore` and the output should look like this if your server is using /ignore from chatcontrol, if not than it is most likely another plugin causing this.
> ![image](https://user-images.githubusercontent.com/48093184/134793030-0bb9e727-ada8-45e2-ac06-d8c8f8a13979.png)
> 
> One way you could fix the above is changing `Ignore.Command_Aliases` in your settings.yml file. So the ignore command isn't the same as the one from the other plugin.

Nope, chatcontrol is actually taking over it, and it always says "you blocked <player>"
![Screenshot_6392](https://user-images.githubusercontent.com/31826333/134824979-fa74a7ff-15ab-41de-9888-a7edd3e60675.png)

That's annoying I can't find the cause of the issue, but I'll manage to find it x)

*Edited by Bananaa : Message was in french, I translated it to english*

**Comment by WarnDa** [comment]
![Screenshot_6393](https://user-images.githubusercontent.com/31826333/134825032-9243081a-72e9-4566-aa34-206b595a735b.png)
There must be something wrong somewhere, and if I copy/paste my plugin's folder on a local test server, it works flawlessly, that's enraging.

*Edited by Bananaa : Message was in french, I translated it to english*

**Comment by ElBananaa** [comment]
> ![Screenshot_6393](https://user-images.githubusercontent.com/31826333/134825032-9243081a-72e9-4566-aa34-206b595a735b.png)
> There must be something wrong somewhere, and if I copy/paste my plugin's folder on a local test server, it works flawlessly, that's enraging.
> 
> _Edited by Bananaa : Message was in french, I translated it to english_

Looks like one of your plugin is causing issues with chatcontrol then.
First of all, make sure to use the very latest version, then try playing around with the listener priority (https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities), who knows, sometimes the easiest and obvious solutions are the right ones ^^

**Comment by WarnDa** [comment]
Putting back the listener priority to high fixed the issue, thanks! :)

(It's pretty weird tho)

*Edited by Bananaa : message was in french, I translated it*
