### ISSUE TITLE
1.16.5: Problem with special characters

### ISSUE THREAD

**Issue by Sakishima** [kangarko/ChatControl#1342]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hello! I have a problem with some russian letters like as "й" and "ё". When I use follow rule for sending to global chat:

match ^(\!)(.*)
then command ch send global $2
dont verbose
then deny

These letters are replaced from "й" to "и" and "ё" to "е". In our language it's a different symbols. How can I resolve this problem? Please help me!

**Comment by TheIntolerant** [comment]
Hey,
You can fix this by going into your settings file and changing ``Rules.Strip_Accent`` To false

**Comment by kangarko** [comment]
Thanks to gone for answering!

**Comment by Sakishima** [comment]
Many thanks! Everything works now!
