### ISSUE TITLE
Suggestion Player Head as image

### ISSUE THREAD

**Issue by Parthurax** [kangarko/ChatControl#1344]
Hi, is it possible to make announcements with the Player Head as image ?

**Comment by TheIntolerant** [comment]
Hey,
You should be able to make announcements with a player head as a image just as long as you have said image, saved in: 
``plugins/ChatControlRed/images``

**Comment by Parthurax** [comment]
i mean that the plugin can get the playerhead by itself.

So i can make announcements with the users head without a downloaded file.

**Comment by ElBananaa** [comment]
Hey,
A such feature has already been requested in the past, you may want to take a look at #723 to see what Kangarko said about it back then ^^

**Comment by Parthurax** [comment]
Now is future 🤯 haha would be a good addition

**Comment by Parthurax** [comment]
Btw what are the conditions for these images.

I tested a bunch of images, one worked :D and was broken :(

**Comment by ElBananaa** [comment]
> Btw what are the conditions for these images.
> 
> I tested a bunch of images, one worked :D and was broken :(

I'm not sure to understand your question.
What do you mean exactly by "worked and was broken"?

I just tried with the latest version on a fresh install with the default creeper-head.png file, and it worked fine for me.

**Comment by kangarko** [comment]
Thanks, however we are not planning on introducing this right now due to time constrains.

**Comment by TheIntolerant** [comment]
> Btw what are the conditions for these images.
> 
> I tested a bunch of images, one worked :D and was broken :(

Just to help, so using the default creeper image you will know you can set the image to different sizes.
``/chc announce image creeper-head.png <6|10|20> <message>``

To get a custom image to display correctly, it's important to know what those numbers mean for the image, basically, even though the creeper image is 128 pixels by 128 pixels, the image shown on the server is reduced to either 6x6 pixels, 10x10 pixels or 20x20 pixels. That is most likely why it "worked" but not really.

Hope this helps 👍
