### ISSUE TITLE
Remove some checks (again)

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1345]
Hello,

Is this possible to disable these check (of interact, enchantement check).
I currently get

> Register_Tools: false

But I also want to disable these other checks (in red).

![Screenshot_6411](https://user-images.githubusercontent.com/31826333/134941693-de338bda-3df7-4f73-94be-2b34e30357dd.png)

My debug : 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7237648/debug.zip)

Spark with + 100 players online :
https://spark.lucko.me/mrgVwJ1z9J
https://spark.lucko.me/jKK2KS8nG8

Sometimes chatcontrol is really heavy :/

**Comment by kangarko** [comment]
Sorry for the delay, I will try to no use this if it's unneeded by your setup in the next version.

**Comment by kangarko** [comment]
Thanks, that will be removed in the next version.
