### ISSUE TITLE
1.15.2: Swear Filter Blocking Wrong Words

### ISSUE THREAD

**Issue by iwentafk** [kangarko/ChatControl#1346]
Minecraft Version: 1.15.2
MySQL: false
BungeeCord: false

Hey there,

So I have a quick question. I'm having issues with the swear filter blocking incorrect words. I have block "ass" by itself but for some reason when you type "assume" it blocks out the first three letters (being the swear I filtered) I have other instances of this, but since this is not a bypass I'm not sure why it blocks the word inside another word. ChatControlPro had a system that didn't let this happen, but it only happens if the word is at the start. So like, if I type "glass" it doesn't trigger the swear, but if the word starts with the swear "assume" it blocks it, I never had this issue with CCP, only with CCR. Any help on this would be gretat.

Thanks!

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.15.2
> MySQL: false
> BungeeCord: false
> 
> Hey there,
> 
> So I have a quick question. I'm having issues with the swear filter blocking incorrect words. I have block "ass" by itself but for some reason when you type "assume" it blocks out the first three letters (being the swear I filtered) I have other instances of this, but since this is not a bypass I'm not sure why it blocks the word inside another word. ChatControlPro had a system that didn't let this happen, but it only happens if the word is at the start. So like, if I type "glass" it doesn't trigger the swear, but if the word starts with the swear "assume" it blocks it, I never had this issue with CCP, only with CCR. Any help on this would be gretat.
> 
> Thanks!

Hey,
The easiest way to "fix" this without breaking your rules/making it harder, is to simply use the `ignore string` variable with your rule.
Here's how it would look like (I ignored 3 words in it, but you can chose to ignore as much as you want ^^)
```rs
# Blocks 'ass'
match \b(a+(\W|\d|_)*s+(\W|\d|_)*s+(\W|\d|_)*)
ignore string assume|assistant|assumed
group swear
```

**Comment by iwentafk** [comment]
I can do that, but can the rules system sensitivity be edited in further versions? It's just a pain to try to ignore every single instance, that's a ton of words and possibilities.

Thanks!

**Comment by ElBananaa** [comment]
> I can do that, but can the rules system sensitivity be edited in further versions? It's just a pain to try to ignore every single instance, that's a ton of words and possibilities.
> 
> Thanks!

Well, you can't adjust "sensitivity". It'll basically either catch something or not.
However, you can just edit the rule to only catch `ass` but it'll also mean that users will be able to bypass the rule easily.
The method I gave you above is the less "painful" one.

Here's a rule that will avoid having to ignore each string:
```yaml
# Blocks 'ass'
match \b(a+(\W|\d|_)*s+(\W|\d|_)*s+(\W|\d|_))
group swear
```

I'm closing this issue as this should solve the issue. Let me know if you need anything else.
