### ISSUE TITLE
Strange Discord SRV Behaviour 

### ISSUE THREAD

**Issue by NoobcoreNetwork** [kangarko/ChatControl#1347]
Hey So, I have tried a few different setups, The first setup, Is discordSRV on only the survival server, Which works when atleast 1 person is on the survival server, but if they go into the creative server (and nobody else is online) we can no longer talk via discordsrv, this is with Forward_From_Bungee: true  on the only server that discordsrv is on.

The other method, Is discordsrv on all servers, and Forward_From_Bungee: true only on survival which yields the below issue

it shows twice if theres people on different servers aka im in lobby and they are in survival, if i go to survival, it will send once (and work correctly) because we are both in survival, 

![javaw_FlGyZEpEjO](https://user-images.githubusercontent.com/62724418/134786541-ed5d8760-703b-4a44-a2ff-edba53170045.png)
![Discord_oTPVPMGlzl](https://user-images.githubusercontent.com/62724418/134786542-aa08d1a4-ee43-447b-8c53-0ca09b8cb767.png)
![Discord_txOOtS5UsL](https://user-images.githubusercontent.com/62724418/134786543-de071e2d-9129-4689-80c2-9eab4f759076.png)
![javaw_Ev5qRnBGyE](https://user-images.githubusercontent.com/62724418/134786544-f1fb0c57-80cb-4633-8c20-3567933380ce.png)

But if there's someone on a third server it still shows twice. Not 3 times. Weird

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

There is a similar closed issue https://github.com/kangarko/ChatControl-Red/issues/1318 But this is a little different, I'm not sure what the ideal setup is anymore, having it on one server doesn't work for me unless 'atleast' one person is on the server discordsrv is on, But then on the other side of things, Having it on every server kinda gives the opposite effect, it works if everyone is on the same server, but doubles up if people move around servers.

Thanks!

**Comment by TheIntolerant** [comment]
I'm having a similar issue but haven't had the time to properly test a few things out.

Just wondering but regarding the bots, do you use the same bot for all your servers? I don't know if this would work like I said, I haven't been able to test this, but if you are only using one bot, could maybe having a separate bot for each server fix this issue?

**Comment by NoobcoreNetwork** [comment]
> I'm having a similar issue but haven't had the time to properly test a few things out.
> 
> Just wondering but regarding the bots, do you use the same bot for all your servers? I don't know if this would work like I said, I haven't been able to test this, but if you are only using one bot, could maybe having a separate bot for each server fix this issue?

I use one bot which isn't advised due to rate limiting, I once tried a bot for each server and it confused the living heck out of chat control so i had to go back to one.

**Comment by UserDerezzed** [comment]
<img width="480" alt="Screen Shot 2021-10-06 at 01 34 10" src="https://user-images.githubusercontent.com/25561419/136168472-03c87690-a14d-4c25-a761-664358aa2c2d.png">
Can confirm that this bug exists

**Comment by kangarko** [comment]
Please check https://github.com/kangarko/ChatControl-Red/wiki/Discord#bungeecord and configure the network according to this, correct me if you already did so. Comment below if you still need any help and I will reopen this.

**Comment by coco0325** [comment]
Same issue here.
With Forward_From_Bungee: false and DiscordSRV on all servers.

**Comment by kangarko** [comment]
The issue is quite old. We will push a new update today, please try on that version and lemme know if the problem persists.

**Comment by coco0325** [comment]
> The issue is quite old. We will push a new update today, please try on that version and lemme know if the problem persists.

Is that released?

**Comment by ElBananaa** [comment]
> > The issue is quite old. We will push a new update today, please try on that version and lemme know if the problem persists.
> 
> Is that released?

Hey, no it's not, it looks like Kangarko didn't have time to finish everything he wanted to, so he didn't push the update.

**Comment by kangarko** [comment]
I am sorry, yes, got delayed with the 1.18 updated. I will try to ship the new compatibility with this bugfix in 1-2d, but prioritize pushing this asap if 1.18 is not feasible within that timeframe.

**Comment by coco0325** [comment]
> I am sorry, yes, got delayed with the 1.18 updated. I will try to ship the new compatibility with this bugfix in 1-2d, but prioritize pushing this asap if 1.18 is not feasible within that timeframe.

The issue still exists in the latest release.

**Comment by kangarko** [comment]
If you have Forward_From_Bungee on false then we do not broadcast this multiple times, the issue could be in your DiscordSRV setup

**Comment by coco0325** [comment]
> If you have Forward_From_Bungee on false then we do not broadcast this multiple times, the issue could be in your DiscordSRV setup

I don't think that's the issue, because I haven't changed DiscordSRV's config since I was using ChatControlPro.

**Comment by kangarko** [comment]
Okay just to confirm you are having duplicated messages from MC to Discord but only one message from Discord to MC on all servers?

Please post me your /chc debug from one of the affected servers.

**Comment by coco0325** [comment]
It's the opposite. I only got duplicated messages from Discord to MC on all servers. I've emailed the debug file to you.

**Comment by kangarko** [comment]
Try setting Integration.Discord.Enabled to false in settings.yml to completely shut off ChatControl's hook to confirm no other plugin is interefering.

Also make sure you've disabled DiscordSRV's chat handling so only ChatControl prints out Discord messages

**Comment by coco0325** [comment]
> Try setting Integration.Discord.Enabled to false in settings.yml to completely shut off ChatControl's hook to confirm no other plugin is interefering.
> 
> Also make sure you've disabled DiscordSRV's chat handling so only ChatControl prints out Discord messages

I disabled DiscordSRV's chat handling and it did solve the duplicating issue. However, the players in game can't see the messages from Discord channels.

**Comment by kangarko** [comment]
Then you'll just need to configure Discord to send messages from its channels into MC into its own dedicated channel, I unfortunately am not sure how to do that but I know there should be a way.
