### ISSUE TITLE
1.17.1：Does not support leaving Chinese in the database, the client crazy output of unknown information

### ISSUE THREAD

**Issue by SheerYin** [kangarko/ChatControl#1348]
Use default settings

Database encoding

![Snipaste_2021-09-28_20-10-38](https://user-images.githubusercontent.com/83099762/135084153-ebcdf068-9fd1-44d2-8952-407577975934.png)
![Snipaste_2021-09-28_20-02-57](https://user-images.githubusercontent.com/83099762/135083765-b4b89255-ab77-4653-8d52-e311f0b574f9.png)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7243814/debug.zip)

I set the configuration, the player uses the pure client to enter and then frantically brushes unknown information

![Snipaste_2021-09-28_20-18-28](https://user-images.githubusercontent.com/83099762/135085189-ade8fb69-4fed-400b-abb6-973e95f36001.png)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7243875/debug.zip)

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey!
Apologize for the delay. Please make sure your database drive is up-to-date.
I also believe the plugin used to have issues with windows setups. Could you please try to reproduce the issue under a linux setup?

**Comment by kangarko** [comment]
You can ignore the Unknown custom packed identifier, it is from Mojang notifying about our sync between bungee servers.

**Comment by kangarko** [comment]
Sorry, I just got a message from Banana. Yes, unfortunately due to technical reasons, we replace all non-standard English letters when saving to database. This also has security implications and prevents crashing data on loading. We will look forward into working this around so that Chinese letters can be saved in the future!
