### ISSUE TITLE
1.16.3 | Other plugins can't handle AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#135]
Every time i write in any chat, i get this error from CMI plugin, and I also saw other reports on this problem but with different plugins 

Error: https://pastebin.com/1jzRmtmB

Other reports (taken from testing discord chat)
![image](https://user-images.githubusercontent.com/62369973/99843338-772b4780-2b82-11eb-861c-9db17409dc0a.png)

**Comment by broken1arrow** [comment]
cmi has is own chat too. I have not try out with cmi, but can check too.

**Comment by kangarko** [comment]
Thanks, will be fixed asap.
