### ISSUE TITLE
Able To Handler Spams And Caps

### ISSUE THREAD

**Issue by justin2001** [kangarko/ChatControl#135]
I have a very important issues. You should add handler for spam and caps. If a player spam and caps, it will handle it due to what command you  define it in the config and use that to punish them. And you should divide spam into two types:

1. Same Message Spammer (Repeater):
Spammer that repeats the same message.

2.Fast Message Spammer (Flooding Chat): Spammer that send a lots of commands and messages in a second.

**Comment by kangarko** [comment]
Hello,

to prevent spamming same messages, configure Anti_Spam.Chat.Similar_Percentage_Block. It works accordingly: If a message is similar (in percent) to the previous one, it will be blocked. By default it will block message that is 80% similar to the previous one.

To block fast message spam (flooding), you can set message delay. Adjust Anti_Spam.Chat.Delay_Between_Messages to fit your needs. 

You can also limit commands, not just messages.

**Comment by justin2001** [comment]
I mean you should add handler for spamming, flooding or capsing. If a player spam, flood or caps, it will handle it due to what command you define it in the config and use that to punish them. E.g. tempban or tempmute spammers, flooders and players who caps.

**Comment by justin2001** [comment]
@kangarko Please do this as quick as possible!

**Comment by kangarko** [comment]
The plugin does check for both spamming, flooding and capsing. Look at the settings.yml file and reread my post above. The only thing you ask for and that is currently missing is executing custom command upon the event, which is to be solved when warn and point system is done.

**Comment by justin2001** [comment]
When will it be out? Im so excited!
