### ISSUE TITLE
Color codes and smileys?

### ISSUE THREAD

**Issue by AndrewRed67** [kangarko/ChatControl#135]
-Missed description lol-
Hey there!
First off, thanks for your previous support! We have found out that if we use a handler like : ) turning into the smiley, it won't use color codes. Even when someone has permission to both, if you type &c:), it would turn out as a white happpy face. Are you able to fix this? If not, it's okay. :)
-Andrew

**Comment by kangarko** [comment]
Hello,

regular expressions strip colors from messages by default, to prevent rules abuse by inserting colors. The premium version contains an option to disable that.
