### ISSUE TITLE
1.17.1: Some kind of memory leak on 10.6.0 BETA and above

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#1350]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

-removed config files for security reasons-

(I would note that other servers that aren't as popular on the network do not seem to crash like this but they all have the exact same configs, it could be the more players join, the worse it gets)

**Comment by DoogiePC** [comment]
Here is a spark profiler https://spark.lucko.me/LZ6mzLNxvm
it is during the server running, i can try get one of when it starts getting worse but i risk it crashing before i can get one.

Here is a timings report https://timings.aikar.co/?id=f2e8b3a76c1641c38d8385b78de853f0

Here is another latest.log https://hastebin.com/hododigeke.sql

**Comment by kangarko** [comment]
@DoogiePC I will further improve our UserRecord class to automatically clean up player data once they disconnect. Right now they are stacked up and sitting there for max performance, but an edge case scenarios such as a hobby server with 500+ players connecting/disconnecting daily may be the cause of this.

**Comment by DoogiePC** [comment]
Yeah the hub server seems to be worst affected, I'd love to test this when you have a build to try.

**Comment by kangarko** [comment]
I reworked out system and made the folowing changes from the old one, which had:

- Two ways to store PlayerCache, this is where tags and other data are stored
- Three ways to store UserRecord, this is where we connect nick-uuid-name

to:

- One way of storing PlayerCache + not saving it when another server sends an update (I tested this and it appears to be working fine, but watch out for players complaining that their chat colors or other data get reset, in this case just report this and I'll do my best to solve asap)
- Two ways of storing UserRecord. I will be looking for removing this cache in the next version completely.

Furthermore, please set your Debug to ["user-record"] and let me know the console message "Storing (...) cached user entries" that should appear on load.

All in all, those should bring memory usage down significantly, so I can't wait to release the new version today!

**Comment by kangarko** [comment]
Closing, if anything, comment below and I'll have a look.

**Comment by ElBananaa** [comment]
Reopening this issue since the latest version didn't fix it.
The author will provide more informations later.

**Comment by DoogiePC** [comment]
@kangarko there appears to be nothing in the startup log matching "cached user entries". Here is the end of the latest.log before it crashed, doesn't seem to have anything useful but i don't know. https://pastebin.com/tpSyJGis

**Comment by kangarko** [comment]
Couple of suggestions I was thinking of: Try disabling our Tab_Complete. Also read up the Performance tab on Wiki, try minimizing the amount of stuff such as rules/formats etc since the more you have the more processing power we have to use for each player.

There's no debug message because there's no map anymore. Are you able to run any profiler such as "spark" on that server ?

**Comment by DoogiePC** [comment]
> Couple of suggestions I was thinking of: Try disabling our Tab_Complete. Also read up the Performance tab on Wiki, try minimizing the amount of stuff such as rules/formats etc since the more you have the more processing power we have to use for each player.
> 
> There's no debug message because there's no map anymore. Are you able to run any profiler such as "spark" on that server ?

Ok but no matter what I look into changing, why was it working perfectly fine before the new .6 BETA version? Something had changed in that version and that's broken it

**Comment by kangarko** [comment]
I need to see those timings or profilers to be able to proceed, I already cut off all of the maps we are storing that may have been the cause of these crashes.

By the way, the latest crash report you have posted seems to be caused by:

Ticking entity: minecraft:goat, entity class: net.citizensnpcs.nms.v1_17_R1.entity.GoatController$EntityGoatNPC

Check to download the latest Paper or Purpur and try also raising a ticket on their end and see what they say. Thank you!

**Comment by kangarko** [comment]
Also, it looks like your database connection may be slow, this is what I found in the report:

java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 35251ms

If we had to wait for 35 seconds for your database to reconnect, this is what's causing the crash. Try disabling MySQL for that server to isolate this issue.

**Comment by DoogiePC** [comment]
> Also, it looks like your database connection may be slow, this is what I found in the report:
> 
> java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 35251ms
> 
> If we had to wait for 35 seconds for your database to reconnect, this is what's causing the crash. Try disabling MySQL for that server to isolate this issue.

disabling mysql disables chatcontrol, its required. it's not the goat, thats just a npc that runs around the spawn, its probably just showing random shit thats getting lagged because theres no ram left because theres a memory leak.

**Comment by kangarko** [comment]
Can you please do a /timings report and a /spark report? https://spark.lucko.me/docs/Command-Usage I am unable to get the same memory usage since I am limited to a few players on my test server so the problem gets sneaked behind.

**Comment by kangarko** [comment]
Hey, just revisited this whole conversation, you already sent enough reports I am sorry for asking like an idiot.

I also revisited the plugin in all places that store data, and found two things:

We were caching player data _without_ removing one piece of data on disconnect. If this bug takes down hub servers, it may be because the data is stacked up and takes more memory the more players reconnect. I have made the cache self-destruct on quit.

I also added a manual option Clear_Cache_On_Disconnect to remove another cache on exit. This cache stores antispam delays 
etc., so players will be able to bypass some checks by mere reconnecting, but you will save tons of memory since these data won't remain loaded until the server is stopped.

I hope these two changes will finally fix your issues!

**Comment by kangarko** [comment]
Closing in good faith these two new changes will fix this, if not please comment below and I will get the notification.

**Comment by ElBananaa** [comment]
Hey!
To add a bit more on this, here are a few spark reports one of our users sent us over the time on some of their issues, and as you can see, there's absolutely no memory leak. Most of these reports (if not all of them) were provided on a server with around 80/100 players online.

https://spark.lucko.me/jKK2KS8nG8
https://spark.lucko.me/mrgVwJ1z9J
https://spark.lucko.me/p3OOmt6FVR
https://spark.lucko.me/iYtkHuV3Dp
https://spark.lucko.me/hMJeN902EZ
https://spark.lucko.me/XTKl9MbbPu
https://user-images.githubusercontent.com/31826333/129277739-6751c503-bd5d-43b4-83fb-133884b67a49.png

**Comment by kangarko** [comment]
Interesting. I still do believe the OP will greatly benefit from our upcoming update. Since we did really stack up the data until the server got restarted which could stack up in RAM for servers with high reconnect rates.

**Comment by DoogiePC** [comment]
> Interesting. I still do believe the OP will greatly benefit from our upcoming update. Since we did really stack up the data until the server got restarted which could stack up in RAM for servers with high reconnect rates.

https://pastebin.com/XHrvDxXS Hub crashed with the new build installed.

The error log is somehow 10GB, not really sure what to do with that.

**Comment by kangarko** [comment]
Wow I am sorry for the crash and hope other files were intact. Remove the error.log file. How large are your MySQL tables from us? 

In case they are too large, we may be downloading too many data over to your hub which may cause this, let me know more info and I will fix it. Apology that it's that cumbersome and taking this long, I acknowledge this is not the first time you're having a long term issue so I want to ensure we get it fixed sooner this time.

**Comment by kangarko** [comment]
@DoogiePC I was thinking about you:

You could lower Clear_Data_If_Inactive from 90 days to 21 days, which will clean your database heavily but players who haven't played in the last three weeks lose their chat colors, prefixes, nicks, joined channels etc. If that is not a problem to you of course :) I will optimize this internally as well.

**Comment by DoogiePC** [comment]
> @DoogiePC I was thinking about you:
> 
> You could lower Clear_Data_If_Inactive from 90 days to 21 days, which will clean your database heavily but players who haven't played in the last three weeks lose their chat colors, prefixes, nicks, joined channels etc. If that is not a problem to you of course :) I will optimize this internally as well.

my db only seems to be around 60MB, ill set it to delete after a day because i use other things to store nicknames prefix's etc.

**Comment by kangarko** [comment]
I am sorry I did not understand - are you deleting the db every day, or you set it to delete it today once to see if it improves the memory leak?

Edit: Oh I see, you meant you will set Clear_Data_If_Inactive to 1 day I suppose. Let me know how it goes!

**Comment by DoogiePC** [comment]
> I am sorry I did not understand - are you deleting the db every day, or you set it to delete it today once to see if it improves the memory leak?
> 
> Edit: Oh I see, you meant you will set Clear_Data_If_Inactive to 1 day I suppose. Let me know how it goes!

It would seeeeem that the hub is still crashing, im just exhausted at this point idk what to do

**Comment by kangarko** [comment]
Disconnect ChatControl on hub from using MySQL... 

Look, I tried numerous optimizations in the plugin and reduced waste for your specific case, there are no other reports of such leaks including big networks using our plugin, all in all I believe it's likely partially caused by another plugin and then chatcontrol just adds the last 20% for the server to be done.

**Comment by DoogiePC** [comment]
> Disconnect ChatControl on hub from using MySQL...
> 
> Look, I tried numerous optimizations in the plugin and reduced waste for your specific case, there are no other reports of such leaks including big networks using our plugin, all in all I believe it's likely partially caused by another plugin and then chatcontrol just adds the last 20% for the server to be done.

I already said, I've tried disconnecting hub from using mysql, but chatcontrol just disables itself because it "requires mysql" on bungeecord

**Comment by kangarko** [comment]
I see, yes, we need MySQL for Bungee to work to sync player data. You can run a test with Bungee disabled for your hub server. Again, I am of that opinion that there could be another plugin draining your memory, I'd advise check your Skript or other plugins that popped up in timings.
