### ISSUE TITLE
support Showitem

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1351]
https://www.spigotmc.org/resources/showitem.10133/

I tried to set Chat_Listener_Priority
And showitem -> listener-priority packet-handler
Tried every one but still can’t support

I think there should be many people who hope to support showitem
![擷取](https://user-images.githubusercontent.com/75075197/135544934-bca17486-02d0-4c1f-9df2-881c8defe1c7.PNG)

**Comment by SheerYin** [comment]
Try to use InteractiveChat, I have been using it for a few months and it seems that there is no problem
Or you use the item display function that comes with CCR

**Comment by ghost** [comment]
I want to use showitem
He is more suitable for my server
Thank you for your suggestion too~

**Comment by ElBananaa** [comment]
Hey,
Sorry for the delay.
Just to be sure: Did you restart your server each time you changed the listener priority?

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
each time you changed the listener priority Restart the server

**Comment by ElBananaa** [comment]
> each time you changed the listener priority Restart the server

Alright,
This is a pretty weird issue.
Unfortunately I have no way to try to reproduce your issue, however one of our users said on discord that both plugins work fine for him, so I'd suggest waiting for Kangarko to see what can be done ^^

**Comment by ghost** [comment]
thank you very much!
By the way, what are the working environments of these  users?
showitem version and chatcontrol red version
I might try it

**Comment by kangarko** [comment]
Unfortunately these two plugins are incompatible, you can either use our [item] feature or use the ItemsAdder plugin, which we support.

**Comment by ghost** [comment]
Why is it incompatible?

**Comment by kangarko** [comment]
No idea sorry, if changing listeners priority wont work when I unfortunately dont have time looking into this specifically

**Comment by ElBananaa** [comment]
Hey,
@kangarko According to Sikatsu, both plugins work perfectly fine together on both latest versions. If you wish to, I could try to reach ShowItem's author to see if he can provide us a version of the plugin for testing purposes, or if we can provide them a version of chatcontrol-red, if they would like to test this on their side (Of course, let me know if it's ok for you ^^)

@SmallFood1026 I don't have more informations about the working environment, but according to some of his other issues, he's running a paper server (1.16.5 or 1.17.1, idk).

Edit: I just reached Phoenix616 (ShowItem's author) on spigot to offer them to either provide them the plugin's jar file to run tests on their end, or to ask if they can provide us a ShowItem jar file to run these tests on our end. I'll keep you both updated here ^^

**Comment by ghost** [comment]
Thank you very much!
Glad to choose this chatcontrol red spigot

**Comment by ElBananaa** [comment]
Hey!
Quick update : I still haven't received an answer from ShoItem's author.
I just sent them another mesage, hoping to have news this time. Otherwise I can't do anything else unfortunately, so you may want to reach them by yourself on their discord server ^^

**Comment by ElBananaa** [comment]
Hey,
@SmallFood1026 Good news: ShowItem's author kindly offered to have a look at this!
First of all, can you please update the plugin to the very latest version available, and make sure this issue still occurs.
If so, please provide us your `/chc debug` output file, your latest.log file and your ShowItem config folder (Of course make sure to remove any sensitive informations).

**Comment by ghost** [comment]
hello! I found the problem
He is not a chatcontrol red and showitem problem
Is caused by my chat rules

match ^(\$)(.*)
then command ch send 廣告交易區 $2
then deny

**Comment by ghost** [comment]
showitem papi >> '$showitem967540166$'
chat rules Let him change 'showitem967540166$'
So it won't show

**Comment by ElBananaa** [comment]
> showitem papi >> '$showitem967540166$' chat rules Let him change 'showitem967540166$' So it won't show

Hey!
Alright, i'm glad to ear that!
