### ISSUE TITLE
[Suggestion] Adding a feature to show player's messages above their head

### ISSUE THREAD

**Issue by Tylwen** [kangarko/ChatControl#1352]
Hello,

I have an idea to submit: be able to display the chat above the players' heads
With prefix, suffix, message, possibility to put PlaceholderAPI.
Have the possibility that it is active all the time or via a command, in the config and leave the choice to the players

This option can be useful for proximity chat without necessarily being in classic chat. The possibility of choosing in the config if you want it to display or not in the chat from a certain distance

I hope I have proposed my idea, I use a translator ^^

Regards,
Tylwen

**Comment by kangarko** [comment]
Thanks, however right now we are already a very complex plugin and I do not want to produce less-quality code so we are keeping features strict to chat-only.
