### ISSUE TITLE
Newcomers question

### ISSUE THREAD

**Issue by Parthurax** [kangarko/ChatControl#1353]
Hi,
do newcomer permission get removed after the defined time ?

**Comment by ElBananaa** [comment]
> Hi, do newcomer permission get removed after the defined time ?

Hey!
Yes, after the defined threshold is reached by the player, anything that applies to the newcomer feature shouldn't apply to them anymore (including permissions). However, keep in mind that the threshold times is the time spent on the server. So if you defined 24 hours there, the player must have 24 hours on the server to not be considered as a newcomer anymore by the plugin ^^

**Comment by Parthurax** [comment]
Thank you for the answer,
it work fine so far, but i noticed that the new players dont have the permissions in luckperms displayed.
The permission works but its just not displayed, maybe a bug ? anyway very strange behavior :D
If everything gets removed after my defined threshold im okay with that, hopefully that wont lead to any issues at some point.

**Comment by ElBananaa** [comment]
Hey,
I'm closing this.
Feel free to tag me in the comments in your need anything else!
