### ISSUE TITLE
1.17.1 How to customize on/off death message?

### ISSUE THREAD

**Issue by Lemonray114** [kangarko/ChatControl#1354]
Minecraft Version: 1.17.7
MySQL: true
BungeeCord: true

Hi, can ChatControl-Red customize player itself to turn on/off showing death message?

**Comment by ElBananaa** [comment]
Hey!
You should be able to turn on/off death messages by using `/chc message toggle death`, however, the command seems to be broken on latest versions of the plugin.
So please wait for @kangarko to have a look at this issue ^^

**Comment by kangarko** [comment]
Will be having a look into this in 1-2 days

**Comment by kangarko** [comment]
It's actually just the "/toggle death" command which works fine. The /chc message toggle command disables the message globally for everyone.

**Comment by ElBananaa** [comment]
Here's a video of the issue I encountered during my tests: https://streamable.com/xshfoq
For some reason none of these commands worked.

As you can see when I type `/toggle death`, the type isn't detected.
When I type `/chc message toggle`, it says that I can use `/chc message toggle death`, but when I type it, it doesn't work neither.

**Comment by kangarko** [comment]
I will fix that invalid help, now we only pull available messages from Messages.Apply_On. Ensure you placed "death" in that key in settings.yml
