### ISSUE TITLE
1.17.1 How to make the bot copy and paste certain word after a symbol?

### ISSUE THREAD

**Issue by Lemonray114** [kangarko/ChatControl#1355]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

How to make auto retype the word in global chat after a specific symbol?
For example if i type "/kit" in global, other players click on the word will auto retype the word in their chat.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1 MySQL: true BungeeCord: true
> 
> How to make auto retype the word in global chat after a specific symbol? For example if i type "/kit" in global, other players click on the word will auto retype the word in their chat.

Hey!
Unfortunately, I don't think this is possible using our chat bot feature. I'm not a 100% sure about it so I'd suggest waiting for Kangarko to make sure about it tho ^^

**Comment by kangarko** [comment]
Not possible right now, unless you can code basic Java and use our API :)
