### ISSUE TITLE
1.17.1 player is not connected through bungeecord

### ISSUE THREAD

**Issue by Lemonray114** [kangarko/ChatControl#1359]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Hi, I cant /channel join after connected to bungeecord, it will come out "player is not connected through bungeecord"

**Comment by kangarko** [comment]
Ensure you have connected through BungeeCord, and use our latest version. If that still won't work, then check for any console errors on Spigot and BungeeCord, post any if you see them, and upload our /chc debug log below. I will reopen this.
