### ISSUE TITLE
Regex question

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [kangarko/ChatControl#136]
Does the messages have to specific?
Currently my regex looks like this:

```
match ^I'm sorry, but you do not have permission to perform this*|^You do not have access to that command.*|^I'm sorry, but you do not have permission to perform this command*|^No permission.*|^You do not have permission for that command*|^You don't have enough permissions to do that*|^You dont have permission to do this!*
```

For instance, if there's a prefix in front of "No permission." like "[CoolPlugin] No permission" (with colors too) will it catch it, if the regex is "No permission." ?
Also, do I need to specify colors in the regex? If so, should I use & or §?

I find this helpfull btw: http://www.regexr.com/

**Comment by kangarko** [comment]
If the regex is just "No permission", then it will match any message that contains "No permission", also "[CoolPlugin] No Permission". You don't need to specify colour, they are removed automatically.

**Comment by TheOnlyRealTGS** [comment]
Okay thank you!
