### ISSUE TITLE
1.17.1: Sound Notify notifies players outside of channel Range

### ISSUE THREAD

**Issue by VitSun2001** [kangarko/ChatControl#1360]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Basically, you can annoy the hell out of people with sound notifications by mentioning them in your local chat. Notification cooldown notifications is not enough to prevent frustration.

**Comment by TheIntolerant** [comment]
Beyond a cooldown, the only other option to limit abuse of sound notifications is to do one of the following:

1) Setting the key ``Sound_Notify.Require_Afk`` to true, inside your ``settings.yml`` file. However, this method "uses Essentials" as stated in the comments for that key.

2) negate the permission node (``chatcontrol.soundnotify``) for your default group and then assign the permission node ``chatcontrol.soundnotify`` to trusted members, such as staff members, etc.

**Comment by ElBananaa** [comment]
This used to be an issue on the first versions of the plugin, with private messages, but was fixed in v10.3.1. (https://www.mc-market.org/resources/18217/update?update=66447)
I guess Kangarko forgot to also fix the issue for the ranged chat. Let's just wait for him to have a look at your issue. ^^

**Comment by TheIntolerant** [comment]
Ohh, my bad for misinterpreting this issue.

**Comment by kangarko** [comment]
Will be looking into this in 1-2 days

**Comment by MADS0LADEN** [comment]
Sound notify also notifies players if their name is contained in words from normal sentences
![image](https://user-images.githubusercontent.com/4103363/136418951-6b1357a9-883e-49a0-84a0-0de0be25d347.png)
Maybe add a setting that requires space around the tag for it to send a sound notification (and change color)

**Comment by kangarko** [comment]
Thank you I fixed everything! New release will be out in a few hours, will appreciate you dropping a review at https://www.trustpilot.com/review/mineacademy.org if you enjoy it!
