### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Bronzwar** [kangarko/ChatControl#1361]
An error occurred when entering a command in the console and in the game chat

Minecraft Version: 1.12.2
MySQL: false
BungeeCord: false

https://paste.helpch.at/ebukaceruy.rb
https://paste.helpch.at/ecuzijawos.md
https://paste.helpch.at/pehipowiye.md
https://paste.helpch.at/oqoyajeput.md
https://paste.helpch.at/osabofozux.cs

**Comment by Bronzwar** [comment]
https://paste.helpch.at/ecuzijawos.md

**Comment by ElBananaa** [comment]
> An error occurred when entering a command in the console and in the game chat
> 
> Minecraft Version: 1.12.2 MySQL: false BungeeCord: false
> 
> https://paste.helpch.at/ebukaceruy.rb https://paste.helpch.at/ecuzijawos.md https://paste.helpch.at/pehipowiye.md https://paste.helpch.at/oqoyajeput.md https://paste.helpch.at/osabofozux.cs

Hey!
I believe these errors occurs because you're using Java 16 with paper 1.12.2 while you shouldn't.
Please downgrade to java either java 8, 11 or 14, and it'll solve the issue. (You can also remove NashornPlus since it's not needed in this version)
