### ISSUE TITLE
/mail send to only users with permission

### ISSUE THREAD

**Issue by 0ofland** [kangarko/ChatControl#1362]
I would like to send update notifications with chat controls mail system. Is there a way to only send a mail to users with a certain permission such as chatcontrol.newsfeed?

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey,
Unfortunately, there is no such feature in the plugin right now.
Please wait for Kangarko to review your suggestion ^^

**Comment by kangarko** [comment]
@0ofland what do you mean exactly? Do you want to limit users who will see "You have a new email" message to only players with "chatcontrol.newsfeed" permission?

**Comment by 0ofland** [comment]
It should only be sent to a user if they have that permission, so only players who would be interested in receiving such a mail should get it.

**Comment by ElBananaa** [comment]
> @0ofland what do you mean exactly? Do you want to limit users who will see "You have a new email" message to only players with "chatcontrol.newsfeed" permission?

I think what they'd like exactly would be a feature like `/email send <permission>` which will only send an email to players with the specified permission. ^^

**Comment by 0ofland** [comment]
Yeah pretty much like that

**Comment by kangarko** [comment]
Thanks for the suggestion, I noted it! Right now my plate is pretty busy but we may return to this in the future.
