### ISSUE TITLE
1.17.1: Nick permissions per server for bungee and mysql

### ISSUE THREAD

**Issue by mav2020** [kangarko/ChatControl#1363]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

I was wondering if I can strip the color or font from a nick on the server's channel if they don't have permission on that particular server, but do on another server. I know I can set up sender conditions to hide the nick if they don't have any nick permission, but I can't figure out a way around the color/font issue.

For example, a player has permissions to color their nick on Server A but not on Server B. When that player moves from A to B, the colored nick is still there. I know if I enable UUID Lookup, then the nick gets removed every time a player changes servers, but that would only work if there is a way to have different nicknames saved per server while still using bungee and mysql (is that possible?).

I hope this is clear enough. Thank you.

**Comment by kangarko** [comment]
Hi there, not right now. Right now we'll propagate the nick as-is across the network. We may change this behavior in the future, thank you for your suggestion.
