### ISSUE TITLE
1.17.1: Player MC Name Change Not Updating - Cannot Change Channels

### ISSUE THREAD

**Issue by InDirectVariant** [kangarko/ChatControl#1364]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Hi team,

We recently started using ChatControl Red and one of our players has changed their Minecraft username. They were in our database with no issue and since changing their name their DB entry has not updated with their new username. As a result they get a "Player <name> is not stored in our database" error and cannot change chat channels.

We attempted deleting their DB entry and having them rejoin so that the plugin re-enters their details but it just regenerated their old information.

Please see debug attached.

Thanks.
[plugins_ChatControlRed_debug.zip](https://github.com/kangarko/ChatControl-Red/files/7290145/plugins_ChatControlRed_debug.zip)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1 MySQL: true BungeeCord: true
> 
> Hi team,
> 
> We recently started using ChatControl Red and one of our players has changed their Minecraft username. They were in our database with no issue and since changing their name their DB entry has not updated with their new username. As a result they get a "Player is not stored in our database" error and cannot change chat channels.
> 
> We attempted deleting their DB entry and having them rejoin so that the plugin re-enters their details but it just regenerated their old information.
> 
> Please see debug attached.
> 
> Thanks. [plugins_ChatControlRed_debug.zip](https://github.com/kangarko/ChatControl-Red/files/7290145/plugins_ChatControlRed_debug.zip)

Hey!
I believe this is a known issue which is pretty similar to #1366.

Please make a backup of your db file, then try to play with the `UUID_Lookup` feature in the settings file to see if it helps? (Also, if your server accepts cracked accounts, you must set it to false. If you only accept premium users, I'd still suggest to set it to false, to, at least see if it helps).

**Comment by InDirectVariant** [comment]
> 
> 
> > Minecraft Version: 1.17.1 MySQL: true BungeeCord: true
> > Hi team,
> > We recently started using ChatControl Red and one of our players has changed their Minecraft username. They were in our database with no issue and since changing their name their DB entry has not updated with their new username. As a result they get a "Player is not stored in our database" error and cannot change chat channels.
> > We attempted deleting their DB entry and having them rejoin so that the plugin re-enters their details but it just regenerated their old information.
> > Please see debug attached.
> > Thanks. [plugins_ChatControlRed_debug.zip](https://github.com/kangarko/ChatControl-Red/files/7290145/plugins_ChatControlRed_debug.zip)
> 
> Hey! I believe this is a known issue which is pretty similar to #1366.
> 
> Please make a backup of your db file, then try to play with the `UUID_Lookup` feature in the settings file to see if it helps? (Also, if your server accepts cracked accounts, you must set it to false. If you only accept premium users, I'd still suggest to set it to false, to, at least see if it helps).

Thanks for the info. I see Matej responded to the other issue.

We'll see what we can do with that setting. We're not a cracked server so that wouldn't be an issue.

Thanks,
Variant

**Comment by kangarko** [comment]
Closing, let's continue on https://github.com/kangarko/ChatControl-Red/issues/1366
