### ISSUE TITLE
1.17.1 | server-name resetting to Unknown Server

### ISSUE THREAD

**Issue by ItWasEnder** [kangarko/ChatControl#1365]
So I stop my server and change the "server-name" in server.properties to "Survival" but when I restart it after that the name will go to "Unknown Server" and then I will start getting errors spammed in the console when a player joins to "set the server-namer in server.poroperties" again.

Host: CreeperHost
Panel Software: CreeperPanel

Log: https://hastebin.com/abeyavenix.properties

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: false

**Comment by ItWasEnder** [comment]
Also, let it be known this was happening with Spigot and Paper-spigot.

**Comment by ElBananaa** [comment]
Hey,
I believe some hosting companies don't allow full edition of files like the server-properties (I know multicraft has a similar feature which requires you to edit the file from the web editor).
Could you try that?
I'm also unable to reproduce the issue on my end on a local test server (fresh install).

**Comment by kangarko** [comment]
Thanks to Banana, check in with your hosting company and let them know you have to edit it for bungeecord integration. Comment below if you will still need help.

**Comment by ItWasEnder** [comment]
> Thanks to Banana, check in with your hosting company and let them know you have to edit it for bungeecord integration. Comment below if you will still need help.

Why isn't this set inside of the plugin config file. Wouldn't that stop this from ever happening?

**Comment by kangarko** [comment]
It used to be set in server.properties for many years. Only recently Mojang seemed to silently remove it without notice. So we just restored it, never had a user complain about it before.

**Comment by ItWasEnder** [comment]
Well in my logic, this might be an edge case with file IO, lots of hosts are moving to their own solutions or building on ptero panel and this issue can become more and more likely. I'm not entirely familiar with how server files are read but it's probably more unlikely a panel is modifying a plugins specific config files over the server.properties file. 

Move over, even if this is an edge case with CreeperPanel only it still affects my perception of ChatControlRed as a product. That's pretty much all I have to say, whether you implement a change is still your decision but this is just how I feel.

Thanks for your time.

**Comment by kangarko** [comment]
Sure, I can move this, along with the other bungee-related toggles, into a separate bungee.yml file. That would actually make more sense for server owners who symlink their settings.yml across bungee network and want some instances not to have bungee enabled, but still receive the sync.
