### ISSUE TITLE
1.17.1: Nick name keeps resetting

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#1366]
Idk what it is or how to disable it but my `/cmi nick` keeps getting disabled every restart. This only started happening after updating chcr from a long time of not updating. Is there a way to disable chcr overriding the nickname every restart?

ChatControl Red 10.6.5.
Minecraft Version: 1.17.1 paper 295.

**Comment by kangarko** [comment]
I am on track of this, seems to happen after the last update, will release a new version in 1-2d

**Comment by kangarko** [comment]
On the next version, if you have Tags.Apply_On not containing nicks, then you should be able to use /cmi nick and it will persist over restarts.
