### ISSUE TITLE
1.12.2: Generating fresh configs on windows corrupts special characters in config files.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1367]
Today I've been experimenting with Red over version of ChatControl 8, very obscure issue on windows. Ive generated fresh configs on MacOSX, Debian and Windows today, on windows all configs with special characters get replaced/corrupted.

here's an example of my emojis in chat.rs (Rip my credit lol)

![Screenshot 2021-10-06 19 39 43](https://user-images.githubusercontent.com/144046/136263510-c6ebac13-3f7a-4529-ae6b-acd7b2ec8927.png)

and in-game:

![2021-10-06_16 38 55](https://user-images.githubusercontent.com/144046/136264061-01303866-10e1-4c0f-bb39-510942983878.png)

Im using a fresh Minecraft server and completely fresh Chat control install with no other plugins minus the required ones.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7296456/debug.zip)

Minecraft Version: 1.12.2
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
It was due to the credits demon hauting the config, I have [added your credits](https://i.imgur.com/mvHzBYI.png) and made them go away in the next version.

**Comment by kangarko** [comment]
@TomLewis did it got solved on the latest version?
