### ISSUE TITLE
1.12.2: /ignore list wipes your ignore list

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1368]
I enabled /ignore, its one of the main reasons I want to move from 8 to Red, as in 8 its broken. Ironically its not working in red either! 

/ignore seems to ignore people, what does not work is being able to list who you have ignored or remove people.
when I /ignore list once I have ignored someone, it just says "you are not ignoring anyone" but it must also wipe who you are ignoring as when I talk from my other testing account you can see them talking again.

I'm currently using the flatfile, but once my testing is complete I will be using MySQL. at present im just testing to make sure everything works.

Sadly there is no console errors.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7296463/debug.zip)
Minecraft Version: 1.12.2
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
I am out of luck trying to reproduce this one.

![a](https://i.imgur.com/b1bOdDK.png)

Assuming the changes made in my build have patched it, I am closing this in good faith that it will start working from today's beta release. Lemme know below if you need anything.

**Comment by TomLewis** [comment]
Whatever you changed seems to have worked!
