### ISSUE TITLE
1.12.2 Adding permissions for autojoin REQUIRES the playter to log out and in-again, /chc reload does not work.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1369]
When experimenting with setting up a global chat channel, I ran into the issue where adding the required permissions and making sure LuckPerms saw the changes (reloaded itself or manual) and even run /chc reload, that it REQUIRED all players to log out and in-again for it to work.

When running /chc reload, this should auto re-check for auto joining channels, this is extremely odd behavior for testing/initial setup and even debugging issues, I personally wouldn't even require it to need a chc reload, adding the correct permissions should be enough.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7296484/debug.zip)

Minecraft Version: 1.12.2
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Odd enough, that was a thing that frustrated some other users. So I solved it by adding a settings.yml toggle to enable autojoin logic to be called upon /chc reload. Just set Channels.Autojoin_On_Reload on, in the next version.

**Comment by TomLewis** [comment]
Fantastic, thanks @kangarko I will give it a try now, I'm basically testing every single feature locally to see how everything works!

Edit: it works! much better!
