### ISSUE TITLE
1.17.1: Discord stopped working

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1372]
After updating to 10.7.1 from 10.6.4 Discord messaging stopped working, messages do not appear and I get this debug error:
`[ChatControlRed] [discord] Failed to find Discord channel from ID 807805085988028416. Message was not sent: [_РазРаб_] **Radiant**: 1`
Which is super weird because this channel ID is not specified anywhere in settings.
Looks like some offset is happening (the actual value in setting.yml is higher than it tries to message).

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by radiant-ai** [comment]
Random small value is subtracted or added to the channel id, some problem with the library parsing big integers?

**Comment by kangarko** [comment]
Thank you very much and I apology for this! A new version will be available in a few hours. 

Btw, you can now remove nashornplus.

**Comment by radiant-ai** [comment]
Thank you!
