### ISSUE TITLE
1.12.2 you can /msg a person you are ignoring, but they can not reply!

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1373]
I think this is just an oversight, if you /ignore someone, they are blocked from chat and sending you messages. But you can send them a /msg still, some players will use this to taunt people because they will not be able to reply and they will be forced to ignore back!
Please remove this temptation from trolls that will ignore people and send them messages to wind them up!

I cant think of any legit reason why someone should be allowed to private message someone they ignore, but maybe have it as a toggle in the settings? Just in-case there is a reason?

Minecraft Version: 1.12.2
MySQL: true/false
BungeeCord: true/false

**Comment by kangarko** [comment]
Great catch! I'll make the Ignore.Bidirectional toggle disallow PMing ignored players. Just set it on true in the next version coming up today.
