### ISSUE TITLE
Do not show options for commands a user does not have permission to use

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1374]
For example, when  user uses /ignore, they should not be told about /ignore <forWhom> <player> as this would be a mod/admin command, and as they do not have permission it should not be shown.

Very very minor detail, no big deal, its just much cleaner to not give them options they can not use, and it will also help with debugging issues too, as we will be able to quickly see what permissions are working for each group from using 1 command.

**Comment by kangarko** [comment]
Very important indeed! I have made that adjustment to the next version:

![a](https://i.imgur.com/x39eOn7.png)

**Comment by kangarko** [comment]
And I also fixed it for many other commands including /channel join and /channel leave!
