### ISSUE TITLE
Change how "/r" work

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1375]
Hello,

So currently when you answer a private msg using "/msg", it will send the /r message to the last player you "/msg", but if someone send you a PM AFTER your last /msg, it will still send your /r to the last player you PM

Exemple to explain clearer : 
- you -> Player A : Hey ! How are you ?
- Player B -> you : Help me please
- You do /r : it will send to "Player A" and not "Player B".

I know this is make like this to avoid errors while doing /r, but an option to automatically send your answer to the last PM you received/send would be nice !

**Comment by kangarko** [comment]
Thanks for suggesting, we may add more options regarding how reply is treated in the next version(s)!

**Comment by c0wg0d** [comment]
I would like this feature as well.  The way it currently works doesn't make much sense to me.

**Comment by kangarko** [comment]
Added a toggle to switch if the sender should override the receiver's /reply or not.
