### ISSUE TITLE
Tiny improvement with nickname message

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1377]
It makes the " go into the same color as the nickname.
![image](https://user-images.githubusercontent.com/5664135/136652823-b40446df-9921-4f67-ade3-c3dda8fd950c.png)

**Comment by ElBananaa** [comment]
> It makes the " go into the same color as the nickname. ![image](https://user-images.githubusercontent.com/5664135/136652823-b40446df-9921-4f67-ade3-c3dda8fd950c.png)

Hey! Which message is that supposed to be exactly?
Is it the `Success_V2` message?

**Comment by Sikatsu** [comment]
The one after you set your nickname, it could very well be Success_V2. Can't currently confirm that though!

**Comment by ElBananaa** [comment]
> The one after you set your nickname, it could very well be Success_V2. Can't currently confirm that though!

Alright, thanks! I believe I found the "issue" but can't do anything unfortunately since I don't have access to the latest version of the plugin, so you'll have to wait for Kangarko ^^

**Comment by kangarko** [comment]
Thank you I will fix that!

**Comment by kangarko** [comment]
No need to reset your localization key, this is an internal fix.
