### ISSUE TITLE
1.17.1: Thanks

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1378]
**I don't have any questions or problems. I just want to thank @kangarko and all his team for all the work they are doing. The ChatControl Red is an amazing plugin that has been managing my server chat for more than a year (I started with ChatControl PRO). Keep it up and never stop doing this amazing work!**

### Thank you!

**Comment by kangarko** [comment]
Thank you so much <3

**Comment by kangarko** [comment]
Also shoutout to @ElBananaa and @gone-incognito, those guys have been amazing in helping everyone out and we would not be where we are today without them, so thanks guys!
