### ISSUE TITLE
1.17.1: Chat and nickname errors

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1379]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

After updating to the latest version last night, I now have the below errors and issues.

Chat error: https://pastebin.com/uLERErT2
Nickname error: https://pastebin.com/4vnvmzt4

**Comment by kangarko** [comment]
I fucked up. I'm sorry. The next release will include a fix.
