### ISSUE TITLE
& symbol is ignored

### ISSUE THREAD

**Issue by xyblues** [kangarko/ChatControl#138]
![image](https://cloud.githubusercontent.com/assets/15712089/17688793/1d6f9d02-63b5-11e6-87d5-89849028e4a2.png)
What should be done to make it not be ignored?
Sorry for my poor English.

**Comment by EvilOlaf** [comment]
AFAIK you could either use && to create a single & or use \ to escape the following character.

**Comment by xyblues** [comment]
Thank you very much！
But why don't you show the number 9
![image](https://cloud.githubusercontent.com/assets/15712089/17693895/d1272662-63d3-11e6-9623-4bba98833aae.png)

**Comment by EvilOlaf** [comment]
Tried `\&9`?

**Comment by xyblues** [comment]
Still not working......
ChatControl is working
ChatControlPro isn't working

**Comment by kangarko** [comment]
Closing. Please post on the Pro page.
