### ISSUE TITLE
1.16.5 : Debug forgot

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1380]
Latest mc-market version

Some debug stayed : 

> [23:12:04 INFO]: [ChatControlRed] Warning: {player}: {message} format's part took 1ms to process message '/boost': {
[23:12:04 INFO]: [ChatControlRed]       'Message' = '{player}: {message}'
[23:12:04 INFO]: [ChatControlRed] }

**Comment by ElBananaa** [comment]
Hey!
This issue has been recently reported again in #1384.
Since the new issue includes more informations, let's continue there ^^
