### ISSUE TITLE
1.17.1: Player not in database error

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1381]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

![image](https://user-images.githubusercontent.com/5664135/136714340-684e94ce-6750-4f20-9301-bd397647a697.png)
It says the player is not in the database, but he definitely is.. happens with other players too since the recent beta update.

**Comment by kangarko** [comment]
What command did the player type to get this? I moved a code block that will simply scan online players if that happens, it should be patched this way in the next version.
