### ISSUE TITLE
Add support for hex format: {#red}

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1382]
CMI's "/colorpicker" command displays all (or at least a lot) of the hex colors. When clicking on colors it pastes the hex code into the chat. CCR supports that, but when shift+left click the colors it pastes the color name, such as: {#rebel}, {#verdungreen}, {#greenhaze}, {#regalblue}, {#navyblue}, {#purple}, {#red}, ETC.
CCR does not support that format, so the player is unable to use the color names.

This can benefit a lot of people because CMI has thousands of downloads. Many of those servers likely also have CCR installed.

**Comment by kangarko** [comment]
Thanks, I may have a look later when I have more time, until then you will need to stick to our standard RGB formula.
