### ISSUE TITLE
Support for registering ChatControl variables as custom placeholders in PlaceholderAPI.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#1383]
RE: https://github.com/PlaceholderAPI/Javascript-Expansion/issues/49

ChatControl-Red 10.7.2

I'm migrating from PlaceholderAPI's Javascript expansion to ChatControl-Red's native variables environment due to the issue ticket above with Java 17. ChatControl-Red's native variables do not seem to have the java incompatibility issue when the Javascript-Expansion for PlaceholderAPI is not installed.

New ``prefix.yml`` in ``/plugins/ChatControlRed/variables``
```yml
Type: format

Key: javascript_prefix

Value: |-
    hasPrefix();
    
    function hasPrefix() {
    var prefix = "{deluxetags_tag}";
      if (prefix == '') {
        return "&8<&7%luckperms_primary_group_name%&8>";
      } else {
           return "%deluxetags_tag%";
       }
    }

Sender_Condition: ''

Sender_Permission: ''

Receiver_Condition: ''

Receiver_Permission: ''
```

Old ``prefix.js`` in ``/plugins/PlaceholderAPI/javascripts``
```js
var prefix = "%deluxetags_tag%";

function hasPrefix()
{
  if (prefix == '')
  {
    return "&8<&7%luckperms_primary_group_name%&8>";
  }
   else {
       return "%deluxetags_tag%";
   }
}

hasPrefix();
```

Replacing all my JavaScript variables to ChatControl-Red works fine and great in-game. However I noticed places that use to register & use PAPI placeholder ``%javascript_name%`` variables now no longer work. Such as on my bridged chat to discord with DiscordSRV.

---

**Would it be possible for ChatControl to register custom PAPI placeholders dynamically for variables created in ChatControl so it can be used elsewhere?**

https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion#with-a-plugin-internal-class
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI#setting-placeholders-in-your-plugin

**Comment by kangarko** [comment]
Thanks, please upload your debug file, I am going to test it and attempt to add the call to PAPI to replace it.

**Comment by mibby** [comment]
I didn't think a debug zip would be necessary since this is more of a feature request to create useable PAPI placeholders.

**Comment by TheIntolerant** [comment]
I was actually thinking how good it would be to have PAPI support for JavaScript variables made with chatcontrol the other day, lol.

Hopefully this could be added!!

**Comment by kangarko** [comment]
Thanks! I have replied on your original thread, the other developer have seemed to fixed it, I tested it out for you. Due to time constrains I will be focusing on other features instead right now since this has been patched on the third party.

**Comment by MrMcyeet** [comment]
Figured id leave this here instead of making a new thread, this would be an awesome feature to have built into ChC Red, the ability to register ChC custom/javascript variables as PlaceholderAPI placeholders.
It seems like it would be a fairly simple addition to make as well

**Comment by kangarko** [comment]
We already support internal placeholder adding, you can check out the org.mineacademy.chatcontrol.fo.model.Variables class, it has some static methods for adding placeholders, but unfortunately at this time I dont have time to document this for non students (we are planning some free tutorials on using our library this year :) )
