### ISSUE TITLE
Add Parties plugin support

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1386]
Hey there, I already asked for this specific's plugin support before for a different issue (emoji rules not working on party plugin), however it also seems if we remove a message using the [X] system it will rebuilt the chat WITHOUT party messages. Is this something can be improved? It would be really nice.

**Comment by ElBananaa** [comment]
> Hey there, I already asked for this specific's plugin support before for a different issue (emoji rules not working on party plugin), however it also seems if we remove a message using the [X] system it will rebuilt the chat WITHOUT party messages. Is this something can be improved? It would be really nice.

Hey!
Which party plugin are you using?
I believe Kangarko is mainly focused on fixing internal issues for now, but giving him the name of the plugin would help so he could potentially add this feature to the roadmap ^^

**Comment by Sikatsu** [comment]
Whoops thought I had the name right in the title, but it's this one:

https://www.spigotmc.org/resources/parties-an-advanced-parties-manager.3709/

**Comment by kangarko** [comment]
I could not reproduce this, so I made you a quick video, maybe you can guide me as to what I am doing wrong:

https://www.loom.com/share/21029b6e56a94800a01c82fa22f80617

**Comment by Sikatsu** [comment]
Hey, the parties plugin is installed on the bungee rather then on the spigot server. I made a video but it's too big to share, let me know if you can reproduce it that way. That's probably also why the emotes in the rules files do not work.

**Comment by kangarko** [comment]
Oh I see! Well I am sorry but frankly having no idea how to fix this, we're not able to see Bungee messages from a Spigot server, so I'd have to be implementing some packet catching service on Bungee and then sending messages down to Bukkit which is an overkill and not something I have time for right now.
