### ISSUE TITLE
1.17.1 Custom Commands in command.rs work but display "Unknown or incomplete command" during entry

### ISSUE THREAD

**Issue by blockswerker** [kangarko/ChatControl#1387]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

I have numerous custom commands for custom help files, etc. which I've created using commands.rs and whitelisted in my CommandWhitelist plugin. If I add a match entry to command.rs is there any way to register that match (e.g match ^\/rules$) as a command?

The commands work when entered BUT display as red text and an error overlay reading "Unknown or incomplete command, see below for error at position 1: /<--HERE]" appears above the chat entry field.

I've tried creating dummy entries in Bukkit's command.yml but otherwise I'm out of ideas for how to get the server to recognize these as legitimate commands during entry. Any ideas?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1 MySQL: false BungeeCord: false
> 
> I have numerous custom commands for custom help files, etc. which I've created using commands.rs and whitelisted in my CommandWhitelist plugin. If I add a match entry to command.rs is there any way to register that match (e.g match ^/rules$) as a command?
> 
> The commands work when entered BUT display as red text and an error overlay reading "Unknown or incomplete command, see below for error at position 1: /<--HERE]" appears above the chat entry field.
> 
> I've tried creating dummy entries in Bukkit's command.yml but otherwise I'm out of ideas for how to get the server to recognize these as legitimate commands during entry. Any ideas?

Hey!
You could either use Bukkit's commands.yml file as you used to, or you could use an external plugin to register our commands such as [MyCommand](https://www.spigotmc.org/resources/mycommand.22272/).
As for registering commands from the commands.rs file, I believe this isn't something either planned or possible to achieve right now, according to #1051.

@gone-incognito made a very complete tutorial in a previous issue (c.f. #594) which explains things a bit further, so I highly suggest to take a look at it as well! :)

**Comment by kangarko** [comment]
Thanks to Banana and gone-incognito for the help and offering potential solutions, I hope these will satisfy you and will be good enough for now.
