### ISSUE TITLE
1.17.1 [ChatControl v10.5.1]: Getting kicked when pasting schematic with World Edit

### ISSUE THREAD

**Issue by itsBeaco** [kangarko/ChatControl#1388]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

On our creative server, when we try to paste a large schematic, we get kicked and I only see messages from ChatControlRed on the console. I've stopped everything else that could affect it such as ViaVersion so this is the last thing. Any ideas how to stop this?

```------------------------------------[ 13.10.2021 16:54:13 ]-----------------------------------
ChatControlRed 10.5.1 encountered a FoException
Running Purpur 1.17.1-R0.1-SNAPSHOT and Java 16.0.2
Plugins: PlaceholderAPI v2.10.10-DEV-132, SilenceMobs v1.10_1.0.4, FarmLimiter v1.5.1, Pl3xMap v1.0.0-BETA-162, AutomaticInventory v2.12.2-eab34e8, CoordinatesHud v1.0, PortalHelper v1.13_1.0.2, MoreMobHeads v1.15_1.0.21, ViaVersion v4.0.1, ViaBackwards v4.0.1, RemoveJoinLeaveMessage v1, LuckPerms v5.3.47, SurvivalInvisiframes v2.1.0, FirstJoinPlus v2.4.1, OpenInv v4.1.8, PlasmoVoice v1.0.5, Sickle v1.8.3, ArmorStandEditor v1.16-24, TAB-BukkitBridge v1.5.2, spark v1.6.1, BuycraftX v12.0.7, Votifier v2.7.2, ProtocolLib v4.7.0, InventoryRollback v2.0-beta, SafeSpectate v1.0, DurabilityAlert v1.5.8, NashornPlus v1.1.0, Vault v1.7.3-b131, ViewDistanceTweaks v1.3.4, Chunky v1.2.86, Parties v3.1.11, PlayerPoints v3.0.3, BungeeGuard v1.2-SNAPSHOT, WorldEdit v7.3.0-SNAPSHOT+5907-0e0b4e7, HeadDatabase v4.14.1, LiteBans v2.7.5, WorldGuard v7.0.6-SNAPSHOT+2149-75774db, EntityDetection v1.2.0 (build #23), AdvancedHelp v1.12.7, GSit v[6.0.2.1], CoreProtect v20.1, Essentials v2.19.1-dev+12-ef8bcc8, TAB v2.9.1, SuperVanish v6.2.6, Pl3xMap-SuperVanish v1.0-SNAPSHOT, EssentialsSpawn v2.19.1-dev+12-ef8bcc8, Harbor v1.6.3, DiscordSRV v1.24.0, Plan v5.4 build 1366, ChatControlRed v10.5.1, OreAnnouncer v2.8.1, OreAnnouncerGUI v1.4.0
----------------------------------------------------------------------------------------------

More Information: 
Messages must be set on Player Message {
	'Type' = 'quit'
}
FoException Report: Messages must be set on Player Message {
	'Type' = 'quit'
}
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage.getNextMessage(PlayerMessage.java:258)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:689)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:559)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:699)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:184)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast(PlayerMessages.java:168)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.listener.PlayerListener.onQuit(PlayerListener.java:326)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor432.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:626)
----------------------------------------------------------------------------------------------


------------------------------------[ 13.10.2021 16:55:20 ]-----------------------------------
ChatControlRed 10.5.1 encountered a FoException
Running Purpur 1.17.1-R0.1-SNAPSHOT and Java 16.0.2
Plugins: PlaceholderAPI v2.10.10-DEV-132, SilenceMobs v1.10_1.0.4, FarmLimiter v1.5.1, Pl3xMap v1.0.0-BETA-162, AutomaticInventory v2.12.2-eab34e8, CoordinatesHud v1.0, PortalHelper v1.13_1.0.2, MoreMobHeads v1.15_1.0.21, ViaVersion v4.0.1, ViaBackwards v4.0.1, RemoveJoinLeaveMessage v1, LuckPerms v5.3.47, SurvivalInvisiframes v2.1.0, FirstJoinPlus v2.4.1, OpenInv v4.1.8, PlasmoVoice v1.0.5, Sickle v1.8.3, ArmorStandEditor v1.16-24, TAB-BukkitBridge v1.5.2, spark v1.6.1, BuycraftX v12.0.7, Votifier v2.7.2, ProtocolLib v4.7.0, InventoryRollback v2.0-beta, SafeSpectate v1.0, DurabilityAlert v1.5.8, NashornPlus v1.1.0, Vault v1.7.3-b131, ViewDistanceTweaks v1.3.4, Chunky v1.2.86, Parties v3.1.11, PlayerPoints v3.0.3, BungeeGuard v1.2-SNAPSHOT, WorldEdit v7.3.0-SNAPSHOT+5907-0e0b4e7, HeadDatabase v4.14.1, LiteBans v2.7.5, WorldGuard v7.0.6-SNAPSHOT+2149-75774db, EntityDetection v1.2.0 (build #23), AdvancedHelp v1.12.7, GSit v[6.0.2.1], CoreProtect v20.1, Essentials v2.19.1-dev+12-ef8bcc8, TAB v2.9.1, SuperVanish v6.2.6, Pl3xMap-SuperVanish v1.0-SNAPSHOT, EssentialsSpawn v2.19.1-dev+12-ef8bcc8, Harbor v1.6.3, DiscordSRV v1.24.0, Plan v5.4 build 1366, ChatControlRed v10.5.1, OreAnnouncer v2.8.1, OreAnnouncerGUI v1.4.0
----------------------------------------------------------------------------------------------

More Information: 
Messages must be set on Player Message {
	'Type' = 'join'
}
FoException Report: Messages must be set on Player Message {
	'Type' = 'join'
}
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage.getNextMessage(PlayerMessage.java:258)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:689)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:559)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:699)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:184)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast(PlayerMessages.java:168)
	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.listener.PlayerListener.lambda$null$1(PlayerListener.java:256)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
----------------------------------------------------------------------------------------------
```

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1 MySQL: true BungeeCord: true
> 
> On our creative server, when we try to paste a large schematic, we get kicked and I only see messages from ChatControlRed on the console. I've stopped everything else that could affect it such as ViaVersion so this is the last thing. Any ideas how to stop this?
> 
> ```
> ChatControlRed 10.5.1 encountered a FoException
> Running Purpur 1.17.1-R0.1-SNAPSHOT and Java 16.0.2
> Plugins: PlaceholderAPI v2.10.10-DEV-132, SilenceMobs v1.10_1.0.4, FarmLimiter v1.5.1, Pl3xMap v1.0.0-BETA-162, AutomaticInventory v2.12.2-eab34e8, CoordinatesHud v1.0, PortalHelper v1.13_1.0.2, MoreMobHeads v1.15_1.0.21, ViaVersion v4.0.1, ViaBackwards v4.0.1, RemoveJoinLeaveMessage v1, LuckPerms v5.3.47, SurvivalInvisiframes v2.1.0, FirstJoinPlus v2.4.1, OpenInv v4.1.8, PlasmoVoice v1.0.5, Sickle v1.8.3, ArmorStandEditor v1.16-24, TAB-BukkitBridge v1.5.2, spark v1.6.1, BuycraftX v12.0.7, Votifier v2.7.2, ProtocolLib v4.7.0, InventoryRollback v2.0-beta, SafeSpectate v1.0, DurabilityAlert v1.5.8, NashornPlus v1.1.0, Vault v1.7.3-b131, ViewDistanceTweaks v1.3.4, Chunky v1.2.86, Parties v3.1.11, PlayerPoints v3.0.3, BungeeGuard v1.2-SNAPSHOT, WorldEdit v7.3.0-SNAPSHOT+5907-0e0b4e7, HeadDatabase v4.14.1, LiteBans v2.7.5, WorldGuard v7.0.6-SNAPSHOT+2149-75774db, EntityDetection v1.2.0 (build #23), AdvancedHelp v1.12.7, GSit v[6.0.2.1], CoreProtect v20.1, Essentials v2.19.1-dev+12-ef8bcc8, TAB v2.9.1, SuperVanish v6.2.6, Pl3xMap-SuperVanish v1.0-SNAPSHOT, EssentialsSpawn v2.19.1-dev+12-ef8bcc8, Harbor v1.6.3, DiscordSRV v1.24.0, Plan v5.4 build 1366, ChatControlRed v10.5.1, OreAnnouncer v2.8.1, OreAnnouncerGUI v1.4.0
> ----------------------------------------------------------------------------------------------
> 
> More Information: 
> Messages must be set on Player Message {
> 	'Type' = 'quit'
> }
> FoException Report: Messages must be set on Player Message {
> 	'Type' = 'quit'
> }
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage.getNextMessage(PlayerMessage.java:258)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:689)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:559)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:699)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:184)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast(PlayerMessages.java:168)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.listener.PlayerListener.onQuit(PlayerListener.java:326)
> 	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor432.execute(Unknown Source)
> 	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
> 	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
> 	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> 	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:626)
> ----------------------------------------------------------------------------------------------
> 
> 
> ------------------------------------[ 13.10.2021 16:55:20 ]-----------------------------------
> ChatControlRed 10.5.1 encountered a FoException
> Running Purpur 1.17.1-R0.1-SNAPSHOT and Java 16.0.2
> Plugins: PlaceholderAPI v2.10.10-DEV-132, SilenceMobs v1.10_1.0.4, FarmLimiter v1.5.1, Pl3xMap v1.0.0-BETA-162, AutomaticInventory v2.12.2-eab34e8, CoordinatesHud v1.0, PortalHelper v1.13_1.0.2, MoreMobHeads v1.15_1.0.21, ViaVersion v4.0.1, ViaBackwards v4.0.1, RemoveJoinLeaveMessage v1, LuckPerms v5.3.47, SurvivalInvisiframes v2.1.0, FirstJoinPlus v2.4.1, OpenInv v4.1.8, PlasmoVoice v1.0.5, Sickle v1.8.3, ArmorStandEditor v1.16-24, TAB-BukkitBridge v1.5.2, spark v1.6.1, BuycraftX v12.0.7, Votifier v2.7.2, ProtocolLib v4.7.0, InventoryRollback v2.0-beta, SafeSpectate v1.0, DurabilityAlert v1.5.8, NashornPlus v1.1.0, Vault v1.7.3-b131, ViewDistanceTweaks v1.3.4, Chunky v1.2.86, Parties v3.1.11, PlayerPoints v3.0.3, BungeeGuard v1.2-SNAPSHOT, WorldEdit v7.3.0-SNAPSHOT+5907-0e0b4e7, HeadDatabase v4.14.1, LiteBans v2.7.5, WorldGuard v7.0.6-SNAPSHOT+2149-75774db, EntityDetection v1.2.0 (build #23), AdvancedHelp v1.12.7, GSit v[6.0.2.1], CoreProtect v20.1, Essentials v2.19.1-dev+12-ef8bcc8, TAB v2.9.1, SuperVanish v6.2.6, Pl3xMap-SuperVanish v1.0-SNAPSHOT, EssentialsSpawn v2.19.1-dev+12-ef8bcc8, Harbor v1.6.3, DiscordSRV v1.24.0, Plan v5.4 build 1366, ChatControlRed v10.5.1, OreAnnouncer v2.8.1, OreAnnouncerGUI v1.4.0
> ----------------------------------------------------------------------------------------------
> 
> More Information: 
> Messages must be set on Player Message {
> 	'Type' = 'join'
> }
> FoException Report: Messages must be set on Player Message {
> 	'Type' = 'join'
> }
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:81)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage.getNextMessage(PlayerMessage.java:258)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:689)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:559)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:699)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast0(PlayerMessages.java:184)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast(PlayerMessages.java:168)
> 	 at ChatControl-Red-10.5.1.jar//org.mineacademy.chatcontrol.listener.PlayerListener.lambda$null$1(PlayerListener.java:256)
> 	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
> 	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
> ----------------------------------------------------------------------------------------------
> ```

Hey,
Please update to the latest version of the plugin currently available (The version you are using is 3 months old) and do the proper changes to the config files, then try again. (You can also remove NashornPlus starting from v10.6.0-BETA since it's not needed anymore since this version)

**Comment by itsBeaco** [comment]
This one is my bad, at some point, I've used the paper.yml on the creative server which has stopped it. But, I wasn't aware of any updates so thank you for that, and thank you for your help. Sorry about that!
