### ISSUE TITLE
Chat control not saving

### ISSUE THREAD

**Issue by BoomScoom** [kangarko/ChatControl#139]
I am trying to change the swear words and stuff in the rules.txt file but when I do and type /chc reload it resets it to the default words. How do I fix this?  Also someone closed this and told me what to do before but it broke the whole plugin.

**Comment by Agazed** [comment]
Use Notepad++

**Comment by BoomScoom** [comment]
I have and it still doesn't save the files.

**Comment by BoomScoom** [comment]
Bumpity bump

**Comment by Agazed** [comment]
Stop your server, edit the files, are start it again.

**Comment by BoomScoom** [comment]
Gives an error when I talk

**Comment by Agazed** [comment]
You arent using the right text encoding I believe.

Are you positive you edited the files with Notepad++?

**Comment by BoomScoom** [comment]
Yes

**Comment by BoomScoom** [comment]
Bump

**Comment by kangarko** [comment]
Make sure you saved the files with UTF-8 encoding:

![Changing Encoding](https://ia.net/content/writer/support/screenshots/notepad__-encoding_normal.png)

While doing this, make sure your server is turned off. Then start it again. Please post any errors if occur.

**Comment by BoomScoom** [comment]
Not working.

**Comment by kangarko** [comment]
What and how is it not working?

**Comment by BoomScoom** [comment]
Well if I changed the swear word to a different swear word and then start the server when ever I talk even if its not the swear word it gives this huge error in the console and it doesn't block the swear word.

**Comment by kangarko** [comment]
Can you post here "this" huge error?

**Comment by BoomScoom** [comment]
http://pastebin.com/DspC0WJh

**Comment by kangarko** [comment]
Have you changed some of the rules? Because the error says some rule is corrupt (the part with the match operator, also regex)

**Comment by BoomScoom** [comment]
Yeah, I've changed the swear words rules to different swear words

**Comment by kangarko** [comment]
Okay, well you have some regular expression error. You can use online regex tester services such as https://regex101.com/ to test your changed swear words and correct the error.

**Comment by BoomScoom** [comment]
I don't know how to use it.

**Comment by kangarko** [comment]
I am sorry, I cannot provide you support for regular expressions since I myself have not enough capabilities in this area. You have to ask on some forum, try bukkit or spigot.
