### ISSUE TITLE
/plot chat   Global chat not working

### ISSUE THREAD

**Issue by NotoriousNemo** [kangarko/ChatControl#139]
Im using the latest version with 1.10, even with 1.9 the /plot chat is broken, and the only way to talk globally is to stand on the road.
When I type /plot chat   it says it toggles plot chat, but it doesnt do anything.

I want the global chat to work on streets and plots, and the /plot chat to work, thank you

**Comment by kangarko** [comment]
How is this affiliated with ChatControl?
It is most likely a priority incompatibility. You may need to disable chat formatter. 

In premium, one can modify formatter's priorities to resolve various third party issues.
