### ISSUE TITLE
1.17.1 {receiver_prefix} variable not working when a private message is sent through BungeeCord

### ISSUE THREAD

**Issue by starwarsfreak219** [kangarko/ChatControl#1391]
Minecraft Version: PaperSpigot 1.17.1
MySQL: true
BungeeCord: true

{receiver_prefix} not working when sending a private message to a user on a different server. It will instead just show {receiver_prefix}. Would it be possible to add bungeecord support for the receiver prefix placeholder?

Here is an image of what is happening, both users are on different servers:
![image](https://user-images.githubusercontent.com/20121232/137601617-410c861d-f2ad-4128-8515-9bc0a51dbf7d.png)

**Comment by ElBananaa** [comment]
Hey!
As stated in the default `format/pm-receiver.yml` file, the `{receiver_prefix}` doesn't work on bungeecord.
This is an intended behavior, which, I believe, can't be fixed for now.
@kangarko correct me if i'm wrong please ^^

**Comment by starwarsfreak219** [comment]
Ah, didn't notice that it said it doesn't work on bungee. :/

I hope there is a plan to add it eventually though. :)

**Comment by kangarko** [comment]
Yes we plan on adding this, but right now, variables are parsed where the player is, so we cannot get the player object on another server.

**Comment by pjindras** [comment]
> Yes we plan on adding this, but right now, variables are parsed where the player is, so we cannot get the player object on another server.

Hello, was this feature update somehow? I would like to be able to use prefixes in /msg etc.

Thanks for the info :)

**Comment by kangarko** [comment]
Not updated since the protocol did not change since
