### ISSUE TITLE
Chat join mysql error

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl#1393]
The following error appears in the console when a player automatically joins a chat in read mode and another chat in write mode when leaving a worldguard region: https://pastebin.com/H9GMnx3g.
The two commands still work, the error spam in the console is a little annoying. No error is returned using version 1.16.5.
Executed commands:
```
ch join eventchat read $player
ch join corpchat write $player
```

error.log: https://pastebin.com/tYfsK49U
debug.zip: [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7367122/debug.zip)
ChatControlRed version 10.7.3
Minecraft Version: 1.17.1 Paper build 336 
MySQL: true
BungeeCord: false
WorldGuard version 7.0.7-SNAPSHOT+2156-9b66513
WorldGuardExtraFlags version 4.1.5-SNAPSHOT

**Comment by kangarko** [comment]
Thanks I will fix that in the next version!
