### ISSUE TITLE
IOException when switching into a channel in read or write mode

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl#1395]
When switching channels to read or write mode, an IO exception occurs:
`[11:54:05 INFO]: [✔] none TheoRetisch1 left reading corpchat channel(s) over limit. [11:54:08 INFO]: BarSerkr issued server command: /ec [11:54:10 INFO]: [ChatControlRed] ChatControlRed 10.7.4 encountered an IOException! Please check your error.log and report this issue with the information in that file. [11:54:10 INFO]: [✔] none TheoRetisch1 left reading eventchat channel(s) over limit.`

I use the following commands:
```
ch join eventchat read $player
ch join corpchat write $player
```
If a player is in corpchat and joins the eventchat in read mode, he loses the possibility to read messages from corpchat until he joins corpchat in write mode again.
The configuration worked until I updated from 1.16.5 to Java16 and 1.17.1. It was possible to be in read mode in corpchat and in read + write mode in eventchat.

debug.zip: [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7372183/debug.zip)
error.log: https://pastebin.com/gkvwaqKn
Minecraft Version: 1.17.1 Paper build 336
MySQL: true
BungeeCord: false

**Comment by kangarko** [comment]
Please test the next release coming up today. Did not faced the error (https://i.imgur.com/hZiG9iB.png), but I rollbacked a change in parsing MySQL database json entries that had caused this.

**Comment by TheoRetisch1** [comment]
The problem also occurred in the latest version. However, the reason was that the delay between the execution of the two commands was too short. Previously, 0.2 seconds was sufficient, but now 1 second is sufficient. Makes no difference to the player, one just has to know. Thank you! #closed

**Comment by kangarko** [comment]
Thanks for letting me know!
