### ISSUE TITLE
1.16.5 : Server freeze

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1397]
Minecraft Version: 1.16.5 Airplane
MySQL: false
Plugin version : 10.7.4
BungeeCord: false (under velocity, but not using mysql bungeecord features)

My server get random freeze every 2-3mn (some ticks lasts 200-300ms, and then goes back to 24ms), so it creates freeze.
I did a spark with all ticks ABOVE 1000ms, and chatcontrolred seems to be heavy : 
https://spark.lucko.me/fqyFFspWG4

Debug : 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7375300/debug.zip)

**Comment by kangarko** [comment]
How many players are online when that happens?

**Comment by WarnDa** [comment]
> How many players are online when that happens?

80 players online
Issue seems RAM cleaning, sometimes it cleans ram every1-2s (instead of 30s before) and ram cleaning can be heavy

**Comment by kangarko** [comment]
What ram cleaning do you use? Are you able to not use this for a day to test it? The thing is, after your ram cleaning, we may force loading of all past players into cache again which may waste resources.

**Comment by WarnDa** [comment]
> What ram cleaning do you use? Are you able to not use this for a day to test it? The thing is, after your ram cleaning, we may force loading of all past players into cache again which may waste resources.

I'm using G1C (with aikar flag, and 18gb ram)


> The thing is, after your ram cleaning, we may force loading of all past players into cache again which may waste resources.

this is why sometimes ram is cleaned twice, and it create freeze

**Comment by kangarko** [comment]
Thanks for sharing. I'll look into optimizing loading past player data. In the meanwhile you could lower Clear_Data_If_Inactive from 90 days to 14 days, which will clean your database heavily but players who haven't played in the last two weeks lose their chat colors, prefixes, nicks, joined channels etc. If that is not a problem to you of course :)

**Comment by WarnDa** [comment]
>  The thing is, after your ram cleaning, we may force loading of all past players into cache again which may waste resources.

If I don't use channels, prefixes, nicks, punishements, etc.
I also need to load every player data ?

I use : 
- colors
- PM
- Protection for flood/spam

Everything else is off, and chat is managed by another plugin. So I got a very very simple use of chatcontrolred, so it should be very light

**Comment by ElBananaa** [comment]
I'm pretty sure using more than 12Gb of ram is not recommended as it can increase a lot the time needed for the garbage collection. So unless you use a moded server, I'd recommend lowering this value to 12Gb (which are moth than enough for a 1.16/1.17 spigot/paper server with 100/150 online players)

**Comment by WarnDa** [comment]
Using old version of chatcontrolered I got no GC issue
<img width="159" alt="Screenshot_6733" src="https://user-images.githubusercontent.com/31826333/138506175-00e109f5-915a-4d2e-90e0-2ad8e297a773.png">

And I got some heavy plugins on ram (anti cheat/questcreator) so I use 8gb ram minimum, so it increase everytime until ram clear itself, so 12gb would be too short. Later I'll reduce it, once vulcan/questcreator devs will work on ram


I'll try again tomorrow with latest release of chatcontrolred but some modifications to config, so we can compare GC

**Comment by kangarko** [comment]
If most of your settings is false, then you could easily set Clear_Data_If_Inactive to 7 days. Players who haven't logged for more than a week will lose their custom chat color preference though. But it should help with cleaning up ram.

If that still doesn't help, remove your data.db entirely, all players will lose their color preference but it should ease up on the plugin since it will reset all data.

**Comment by kangarko** [comment]
For your case, I highly suggest using MySQL. I tested your debug file, it has 1659 players being loaded to memory without adjusting your Clear_Data_If_Inactive option. Yaml is known to be slow with many values, go with MySQL instead.
