### ISSUE TITLE
1.17.1 : Locale de not found

### ISSUE THREAD

**Issue by Grevd** [kangarko/ChatControl#1398]
Minecraft Version: 1.X.Z
MySQL: true
BungeeCord: true

Hello the Locale de is disn't working

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.X.Z MySQL: true BungeeCord: true
> 
> Hello the Locale de is disn't working

Hey!
There's no official deutsch translation for the plugin right now.
Currently, the only available localizations are `en` and `fr`.

**Comment by Grevd** [comment]
Hey, is there anything somewhere that will allow me to do this?

**Comment by ElBananaa** [comment]
> Hey, is there anything somewhere that will allow me to do this?

Well, if you want to, you could make your own localization file by editting the `localization/en.yml` one. In this case, make sure the Locale option in the settings file is set to `Locale: en`
Or, if you wish to, you could send us your localization file so we could add it to the plugin, so everyone could use it (And, of course you'll be credited for it) 😉
