### ISSUE TITLE
1.17.1: Rules replace word with unicode

### ISSUE THREAD

**Issue by maxrio21** [kangarko/ChatControl#1399]
Good morning, I have a question and it is that I have changed the texture of a custom font and that texture I have associated with the unicode character: "\ uE002".

I wonder if it is possible that when a user writes for example "uNi" it will replace that word For this character, I have tried but it writes the text itself, not the unicode character, maybe it is that I have not found the documentation yet about it or it simply cannot be, so just in case I ask.
![Hellu](https://user-images.githubusercontent.com/49069348/138084779-9e41794f-7ef7-46c8-9203-5d5323923a71.PNG)
In this image you can see that in the number 1 I used the tellraw comand to show me the unicode and the number 2 i used the key word to replace it with the new character.

And here you can see what i did in the chat.rs config file:
![Helluu](https://user-images.githubusercontent.com/49069348/138085352-8d8d18a2-1425-494f-ae7c-9d1f30b8e3d2.PNG)

Thank you very much for your attention ^ ^.

**Comment by ElBananaa** [comment]
> Good morning, I have a question and it is that I have changed the texture of a custom font and that texture I have associated with the unicode character: "\ uE002".
> 
> I wonder if it is possible that when a user writes for example "uNi" it will replace that word For this character, I have tried but it writes the text itself, not the unicode character, maybe it is that I have not found the documentation yet about it or it simply cannot be, so just in case I ask. ![Hellu](https://user-images.githubusercontent.com/49069348/138084779-9e41794f-7ef7-46c8-9203-5d5323923a71.PNG) In this image you can see that in the number 1 I used the tellraw comand to show me the unicode and the number 2 i used the key word to replace it with the new character.
> 
> And here you can see what i did in the chat.rs config file: ![Helluu](https://user-images.githubusercontent.com/49069348/138085352-8d8d18a2-1425-494f-ae7c-9d1f30b8e3d2.PNG)
> 
> Thank you very much for your attention ^ ^.

Hey!
I belive the plugin doesn't replace unicode with their actual character, so instead of replacing text with the unicode, replace your text with the special character assigned to the unicode directly.

**Comment by maxrio21** [comment]
WoW it worked perfectly, really thx!
