### ISSUE TITLE
Mention Suggestion

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#1401]
You fixed the mention system so that it doesn't sound notify people when their name is inside a word. That is very awesome and im thankful for the fix!
I have one small suggestion, change or add a setting so that if you end the player's name with "!", "?" or something along the lines.
Right now you need to have a space before "?". 

Thank you!

**Comment by kangarko** [comment]
Takk for at du la merke till det! Skal fikse.

Thanks & fixed!
