### ISSUE TITLE
Chat filter: Ignore string "he's lagging" (global.rs)

### ISSUE THREAD

**Issue by tyuop077** [kangarko/ChatControl#1402]
Default chat filter triggers string "(s)he's lagging" on slag regex as `\b` catches beginning from `'` (so `hes lagging` without `'` would pass) and prevents players from sending that.
```
*--------- Rule match (global/swear) for _Tyuop_ ---------
MATCH: \b(s+(\W|\d|_)*l+(\W|\d|_)*a+(\W|\d|_)*g+(\W|\d|_)*)
CATCH: he's lagging
UPDATE: he'******ing
```
Default `global.rs` on version 10.7.4
> PS. Also default ISSUE_TEMPLATE for bug reports contains a link to issue #515, which has been deleted.

Players also can bypass swear filter by adding any word/letter without space like `so****you` or `youa****le` (both pass).
> In my opinion, it's probably better to keep \b for words, that could be inside other sentences (like "kept watching" for twat) and not keep \b on obviously intentional ones (f**k can't appear anywhere between, so it should trigger).

**Comment by TheIntolerant** [comment]
While I agree with you generally speaking about the usage of 
\b, as someone who has made many edits to get the chat filter to best fit my liking, my only concern would be that such changes such where \b is removed unnecessary could result far more false positives than actually preventing toxic people who are genuinely swearing.

For example a while ago I decided to remove \b from "bitch" to prevent people using that word, how ever phases such as "a bit cheeky" was setting off the chat filter, which is when I made a slight change to the RegEx it self to stop such false positives.

**Comment by tyuop077** [comment]
@gone-incognito I did a lot of testing with many words to come up with letter combinations and where to put \b, but there still can be some sentences, that could be triggered, that's true

**Comment by TheIntolerant** [comment]
To be fair though, it's not a bad idea, I just worry such changes would cause a ton of false positives that's all. 😄

**Comment by kangarko** [comment]
I have fixed the deadline in our issue template, thank you for noticing!

As per the \b feature that stops rule from filtering a word that has space before/after it, this is a touchy topic, also depending on the server's slang and general theme.

For now, I have added "ignore string \blag" to the default settings to at least minimize this!
