### ISSUE TITLE
BungeeControl Variable Addition

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#1404]
Add a placeholder/variable to BungeeControl called something like {unique_players} which returns amount of players stored in data.db, that way it is possible to display which number a newbie joins.

**Comment by kangarko** [comment]
Such variable would be inaccurate, we routinely clear our data.db and given the recent update, not all values are loaded to memory. You can use PlaceholderAPI and one of their expansions should have a variable for Bukkits' offline player count saved on the disk.

**Comment by MADS0LADEN** [comment]
Is that possible from the bungeecord server? :o

**Comment by kangarko** [comment]
No idea honestly :)
