### ISSUE TITLE
Private messages are broken

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl#1405]
Random players who are on the same world cannot send each other msgs. They always get the message `player %player% is not online on this server`. The undelivered message appears normally in the log, there are no errors in the console. With other players without authorisation differences etc., chatting works randomly. If the player switches to a different world than the one his chat partner is in, it works again. The problem also occurs when the `UUID_Lookup` is set to `false`.

This is of course a disaster and leads to numerous complaints o.O

ChatControlRed version 10.7.4
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7403061/debug.zip)
Minecraft Version: 1.17.1 (git-Paper-349)
MySQL: true
BungeeCord: false

**Comment by kangarko** [comment]
Looking into this asap

**Comment by kangarko** [comment]
Sadly I am not able to find this bug: https://i.imgur.com/L9Dnq31.png

The problem seems to occur because the player data has not been loaded.

Set Debug to [data-sync] in the next version. It will spam the console every second with all player data that is loaded. Let me know when that happens and post a screenshot of the log. If my hypothesis is correct, it should NOT have the player name of the recipient that you get "Player is not online" error message for.

**Comment by TheoRetisch1** [comment]
Ok thank you, should I set `UUID_Lookup` to `true` or `false` while testing?

**Comment by ghost** [comment]
I also have this problem
![擷取jpg](https://user-images.githubusercontent.com/75075197/138560890-891bcca1-53b7-4b4a-a684-4d7ffe7189df.jpg)

**Comment by kangarko** [comment]
> Ok thank you, should I set `UUID_Lookup` to `true` or `false` while testing?

Does not matter.



> I also have this problem ![擷取jpg](https://user-images.githubusercontent.com/75075197/138560890-891bcca1-53b7-4b4a-a684-4d7ffe7189df.jpg)

Please also follow instructions I gave above.

**Comment by TheoRetisch1** [comment]
Status update: It's a bit jinxed. The error definitely also occurred very quickly under version 10.7.5. However, since I activated the data-sync debug mode, all players are always synced correctly and the problem no longer occurs. I'll keep monitoring it for now.

**Comment by TheoRetisch1** [comment]
After two days without a report and a solid 200 attempts to reproduce the bug in debug mode, I will turn the debug mode off again tomorrow. If the bug doesn't occur again for two days, the ticket can be closed. I don't get it.

**Comment by kangarko** [comment]
Strange, was probably fixed in the meanwhile. Closing in good faith this has been resolved, comment below if not!
