### ISSUE TITLE
1.17.1: Discord forwarding not working 100%

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#1407]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Discord forwarding does not work when no one is online on the server where DiscordSRV is installed.
It appears to be because the chat is not sent the the servers which have zero players online.

**Comment by kangarko** [comment]
That is a known problem due to how Bukkit sends plugin messages, we literally have to use a Player object to send it through. This is a long term wontfix issue.
