### ISSUE TITLE
Optional Swear Viewing

### ISSUE THREAD

**Issue by null321-jared** [kangarko/ChatControl#1408]
Minecraft Version: 1.8.8, 1.12.2
MySQL: true
BungeeCord: true

I had previously tested out Chat_Ignorer to make it so we can show swears to those that want to see them, and hidden to those that don't.

Is there an alternative way that allows something other than full-on ignoring the message? Something like making it so those that don't want to see the message can see *** or other replacement of the swear, and those that do see the original message?

**Comment by kangarko** [comment]
Chat Ignorer has been partially broken and caused issues with numerous integrations, we do not have an alternative for this at the moment, but you can use https://github.com/kangarko/ChatControl-Red/wiki/Rules#then-deny-silently
