### ISSUE TITLE
sound notifications from mentions

### ISSUE THREAD

**Issue by Miyamoto61** [kangarko/ChatControl#1409]
sound notifications are not engaging after been enabled in settings.yml i have channels set up on my config also changed # prefix and still no joy debug attached 

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true
[debug (2).zip](https://github.com/kangarko/ChatControl-Red/files/7403955/debug.2.zip)

**Comment by ElBananaa** [comment]
Hey,
After running some tests on my end, I was unable to reproduce your issue.
My tests were made under paper 1.17.1 with chc-red 10.7.5: https://streamable.com/qyszbz

UPDATE: It seems to only happen when using a prefix

**Comment by kangarko** [comment]
Thanks, will be fixed.
