### ISSUE TITLE
Commands BLACKLIST

### ISSUE THREAD

**Issue by YepImRobbie** [kangarko/ChatControl#141]
I run a worldedit server and if you can iamgine whitelisting all variants of worldedit commands is impossible.

I want to blacklist reply and message etc so people can msg spam, amongst tpa. But whitelist doesn't let me have this freedom, thanks! :+1:

**Comment by kangarko** [comment]
I would suggest creating a filter for desired purpose, in your case it will be in commands.txt file in rules folder.

The following filter will block "/reply" and "/r" commands to players without permission, sending him "Insufficient permission" message.

match ^/(reply|r)
ignore perm chatcontrol.reply
then warn &cInsufficient permission.
then deny

**Comment by YepImRobbie** [comment]
No, I don't think you understand.

There is an ability to stop command spam.

I have worldedit for everyone, I cannot whitelist EVERY variation.

Instead of a whitelist, I would like a BLACKLIST for command spam.

Therefore I can blacklist tpa and msg and reply instead of WHITELISTING all but them.

**Comment by kangarko** [comment]
Oh, that's not currently possible but I can add it in the next release.
