### ISSUE TITLE
Format Help

### ISSUE THREAD

**Issue by Shane1199** [kangarko/ChatControl#141]
I can't figure out how to format the chat, and I know I am missing something. I believe it is all in chat.yml

I would like the chat to be formatted as shown below from another chat plugin, however only the default format is shown. I am using PermissionsEX, ChatControl Pro 7.0.10, and Spigot 1.7.10. Would you be able to help work me through transferring over to ChatControl?

private_message_formats:
  to_sender:
    format: '&7you &e-> &7%recipient% &7:'
    tooltip:
    - ''
    click_command: '/r '
    chat_color: '&f'
  to_recipient:
    format: '&7%player% &e-> &7you &7:'
    tooltip:
    - ''
    click_command: '/r '
    chat_color: '&f'
  social_spy: '&8[&cSpy&8] &f%player% &e-> &f%recipient%&7:'
formats:
  default:
    priority: 2147483647
    channel: ''
    prefix: '&7[%vault_groupprefix%&7] '
    name_color: '&b'
    name: '%player%'
    suffix: '&7> '
    chat_color: '&f'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '%player%'
    - '&bRank: %vault_group%'
    name_tooltip:
    - ''
    suffix_tooltip:
    - ''
    channel_click_command: ''
    prefix_click_command: /msg %player% '
    name_click_command: '/msg %player% '
    suffix_click_command: ''

**Comment by kangarko** [comment]
Please post on the appropriate page.
