### ISSUE TITLE
sender_or_you variable incorrect

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#141]
The default configuration value for the sender_or_you variable is:

`Value: '''{sender}'' == ''{player}'' ? ''you'' : ''{sender}'''`

The problem here is that `{player}` parses as the person the message is being _sent to_, rather than _the one sending_ the message.  This means it will never be evaluated correctly as "you" and will always be set to the `{sender}`.

**Comment by c0wg0d** [comment]
I'm actually not sure why this variable is needed at all.  Won't it always be "you"?

This doesn't seem to be utilized by the spy command, unless I'm mistaken?

**Comment by kangarko** [comment]
Yep, totally unnecessary, changed this to "you" thanks!
