### ISSUE TITLE
1.17.1: Mention does not take into account to vanish

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#1410]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true
Vanish plugin: PremiumVanish

Mention still fires for vanished recipients 
My action bar shows im vanish, and this player still mentioned my name hence the yellow color
https://i.imgur.com/gBH8tpd.png

**Comment by kangarko** [comment]
Unfortunately, the developer of PremiumVanish would have to give the vanished player the metadata with key "vanished" and value of true, otherwise we cannot recognize it. I recommend asking him. We already support most vanish plugins such as EssentialsX: https://i.imgur.com/8StTFoG.png

**Comment by ElBananaa** [comment]
> Unfortunately, the developer of PremiumVanish would have to give the vanished player the metadata with key "vanished" and value of true, otherwise we cannot recognize it. I recommend asking him. We already support most vanish plugins such as EssentialsX: https://i.imgur.com/8StTFoG.png

@kangarko That's already what they do according to the plugin page.
@MADS0LADEN Which vanish method are you using? Could you try with a different one to see if it helps?

**Comment by MADS0LADEN** [comment]
@ElBananaa I'm using hybrid, aka the default.
I can try the others 😊

**Comment by ElBananaa** [comment]
> @ElBananaa I'm using hybrid, aka the default. I can try the others 😊

If you don't mind trying the others (especially the Bukkit one) and let us know if it changes anything ^^
