### ISSUE TITLE
1.16.5:AutoJoin after reloading or rejoin encounter some bugs 

### ISSUE THREAD

**Issue by TimmyHung** [kangarko/ChatControl#1412]
I have keep my channel mode below before I disconnect form server
![image](https://user-images.githubusercontent.com/58425985/138720296-074d3563-58fa-4a02-8f85-8b8b1da6a6ab.png)

Then I reconnect with permission 'autojoin.admin.read', 'autojoin.global.read' 'autojoin.range.write'

I have set this to false
![image](https://user-images.githubusercontent.com/58425985/138718462-b3dd9b4c-f483-4121-ac8d-e7044b1a350d.png)

Then I connect to the server, see the red box I've draw. It conflicted I think there're some bug in autojoin process.
So Ignore_Autojoin_If_Left is false then why server join me to my saved channel?
![image](https://user-images.githubusercontent.com/58425985/138718267-8b0aed64-bc58-48d7-9a18-db298f4d9409.png)

________________________
Also /chc reload have same bug while autojoin player into channels
![image](https://user-images.githubusercontent.com/58425985/138720468-01037ba0-755f-470b-9e88-4770485c5762.png)

![image](https://user-images.githubusercontent.com/58425985/138720562-9bd2256a-9992-4f3b-a22b-bfce048ef858.png)

**Comment by kangarko** [comment]
If  Ignore_Autojoin_If_Left is false, we will still join players to their saved channels. We will NOT join players to the channels they have explicitly left using /channel leave command.

**Comment by kangarko** [comment]
Next version should also clear up some bugs regarding data sync, let me know if you will experience problems again.
