### ISSUE TITLE
Implementation of new Placeholder.

### ISSUE THREAD

**Issue by LiannOM** [kangarko/ChatControl#1413]
1. People could create custom guis with player counts so users would know if they join channel that only lets say 1 person is in it or 5.

2. It wont be as much customized as i wanted it to be :/

My idea is to implement placeholder that would count online players on specified channel and mode, something like:

{chatcontrolred_player_channelonline_<channel>_mode_<mode>}

Example: {chatcontrolred_player_channelonline_GLOBAL_mode_READ}

Output: Numerical

**Comment by kangarko** [comment]
Thanks for suggestion, however we're not having enough time right now to implement this feature.
