### ISSUE TITLE
Paper 1.8.8: Change chat style without changing color?

### ISSUE THREAD

**Issue by Korinocho** [kangarko/ChatControl#1414]
Can i change my writing style without touching the color?
I mean, I know I can use /chc color red and /chc color red bold, but is there any way to change to underlined (for example) without changing the color (something like /chc color dontchange underlined).

And another question: can I change the first line "Dark Green Color"?
![image](https://user-images.githubusercontent.com/21372197/138738212-2d6e5cf9-ddc1-462f-8869-b2551543d37c.png)

**Comment by kangarko** [comment]
No, but I will add this! In the next version simply type /chatcontrol color default DECORATION and your color will remain.

You cannot translate internal color names at the moment.
