### ISSUE TITLE
player console offline

### ISSUE THREAD

**Issue by Miyamoto61** [kangarko/ChatControl#1416]
hello

Just wanted to report a issue that i've noticed, when a player logs in it runs the player console is not online on this server.
Also on top of that all names in /ch list show as console

Added pics for reference and debug

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true
![Cc1](https://user-images.githubusercontent.com/79632150/138766633-b0497f6d-0bb3-400d-906d-31cfb3056b6a.PNG)
![cc2](https://user-images.githubusercontent.com/79632150/138766634-49776b63-b6dd-494d-ad7f-8adf8091bda1.png)
[debug (3).zip](https://github.com/kangarko/ChatControl-Red/files/7413387/debug.3.zip)

**Comment by kangarko** [comment]
Sorry, this is a technical exception, we can't support the player by the name of "Console" properly at the moment. Most likely other plugins will cause (silent) issues too, I recommend him changing his nickname.
