### ISSUE TITLE
Adding the ability to customize BungeeCord plugin messages using packets.

### ISSUE THREAD

**Issue by MrCrazys** [kangarko/ChatControl#1417]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.) People using ChatControl Red on a BungeeCord network may want to customize some of their BungeeCord plugin messages, as some plugins do not give the option to customize certain or any messages.

2. What would happen if we won't implement this feature? How's your server being affected? My server would not be greatly affected, but I believe it would be helpful for owners of a BungeeCord network.

**Comment by kangarko** [comment]
What messages do you mean exactly?

**Comment by MrCrazys** [comment]
So like, I am running LiteBans for both BungeeCord and Spigot under my server, and whenever you do /litebans, it says LiteBans version 2.7.5 running under BungeeCord, and doing /lbans shows the message LiteBans version 2.7.5 running under Spigot. The good thing with the Spigot message is that I can change it to say Unknown command, and have bypass permissions, whereas with BungeeCord I can't. Don't know if that's possible.

**Comment by kangarko** [comment]
Thanks, I dont think thats possible right now, you can use our ProtocolLib integration to only filter and change Spigot plugin and server messages but not on BungeeCord.

**Comment by MrCrazys** [comment]
Ok
