### ISSUE TITLE
Reloading configuration failed, check console. The error was: Unknown ignore event

### ISSUE THREAD

**Issue by YellowZaki** [kangarko/ChatControl#142]
When I add the config: ignore event CHAT, I get this error when I reload:
Reloading configuration failed, check console. The error was: Unknown ignore event: CHAT Valid: GLOBAL, CHAT, COMMAND, SIGNS.

I have tried with ignore event signs, ignore event SIGN, ignore event chat... But anything works.

I'm using spigot 1.10.2.

**Comment by kangarko** [comment]
Hello,

which file have you edited? Please upload it to pastebin

**Comment by YellowZaki** [comment]
I edited rules.txt.
Here I have uploaded the only part I edited:
http://pastebin.com/hQpM1cPD

**Comment by kangarko** [comment]
Confirmed. I will fix it asap.

**Comment by kangarko** [comment]
Fixed in 5.3.6
