### ISSUE TITLE
Why does the letter replace itself?

### ISSUE THREAD

**Issue by Woody-Man** [kangarko/ChatControl#1420]
Minecraft Version: 1.17.1

Why, when I write to the global chat, the Russian letter "й" changes to "и"?
How to fix it, please help.
I write to the global chat using the "!" symbol before the message.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1
> 
> Why, when I write to the global chat, the Russian letter "й" changes to "и"? How to fix it, please help. I write to the global chat using the "!" symbol before the message.

Hey!
Make sure to set the `Strip_Accent` option to `false` in the settings file of the plugin. It should solve your issue.
