### ISSUE TITLE
1.12.2: Chat_Forwarding from Bungee doesn't appear to work

### ISSUE THREAD

**Issue by LurgenAU** [kangarko/ChatControl#1422]
Minecraft Version: 1.12.2
MySQL: true
BungeeCord: true

I have Global chat working reasonably well between Paper servers, but one of my servers cannot run the plugin so I am attempting to configure Chat_Forwarding on the Bungee proxy. I've set it to "Enabled: true", and specified the name of the server as per my Bungeecord configuration (actually Flamecord, but near enough).

Messages aren't sent or received from this server, and nothing shows up in the console or logs. I attempted to enabled debug for this section, but nothing comes up. I'm also unable to use /tell from there, but that seems to suggest that the proxy isn't intercepting these commands - is that the case?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.12.2 MySQL: true BungeeCord: true
> 
> I have Global chat working reasonably well between Paper servers, but one of my servers cannot run the plugin so I am attempting to configure Chat_Forwarding on the Bungee proxy. I've set it to "Enabled: true", and specified the name of the server as per my Bungeecord configuration (actually Flamecord, but near enough).
> 
> Messages aren't sent or received from this server, and nothing shows up in the console or logs. I attempted to enabled debug for this section, but nothing comes up. I'm also unable to use /tell from there, but that seems to suggest that the proxy isn't intercepting these commands - is that the case?

Hey!
I don't know if flamecord modifies anything from Bungee API, so i'd suggest trying with waterfall to see if it changes anything ^^

**Comment by kangarko** [comment]
Solved over email, we don't support Sponge at the moment but this is something we can look into.
