### ISSUE TITLE
[1.17.1]: PlaceholderAPI relational placeholders are not parsed in chat

### ISSUE THREAD

**Issue by MrMcyeet** [kangarko/ChatControl#1425]
Minecraft Version: 1.17.1
MySQL: False
BungeeCord: False

This feels like a bug, since on the plugin's McM page, it says
![image](https://user-images.githubusercontent.com/68966344/139152494-1955889a-e990-4c84-958a-ebedc8840436.png)
When I tried using one of my relational placeholders in the chat `(I just put that as a prefix to everyones username haha)`, it just stayed `{rel_oraxen_noob_tab}` instead of getting parsed. I'm sure that this is the correct placeholder as we use the same one in our tab list.

In the event that this isnt a bug, and is working as intended, then I think that chat/prefixes/whatever should be parsed for relational placeholders. The two players would be the person receiving the chat, and the person sending the chat.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7429468/debug.zip)

**Comment by kangarko** [comment]
Answered on your other ticket, lets continue there. Thank you :)
