### ISSUE TITLE
[1.17.1]: How do I setup relational placeholders 

### ISSUE THREAD

**Issue by MrMcyeet** [kangarko/ChatControl#1426]
How do we go about setting up relational placeholders for the chat? I looked all throughout the API and the wiki on here, and didn't see anything relating to this. My goal is to make a placeholder that is sent into chat, as a players prefix, and parsed differently based on who is viewing it. In this case, the two parties to be parsed with the placeholder would be the person viewing chat, and the person who sent the chat message.

This is a screenshot of why I thought that something on this topic would be less difficult to find.
![image](https://user-images.githubusercontent.com/68966344/139180910-35b7e526-cc06-4c37-9321-45d16c27e7b2.png)

Minecraft Version: 1.17.1
MySQL: False
BungeeCord: False

**Comment by MrMcyeet** [comment]
Just for some context, I have set up relational placeholders that work in another plugin I use called TAB, so if I need to make an api addon via a seperate java plugin, that is fine, I just didnt see anything in the api relating to relational placeholders

**Comment by kangarko** [comment]
Hey! You can just hook into PlaceholderAPI and use their API to add relational placeholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion#relational-placeholders

We will support it automatically in the plugin, such as in formats/:

![a](https://i.imgur.com/uzxRf0A.png)
