### ISSUE TITLE
Paper 1.17.1: /list not showing in chat

### ISSUE THREAD

**Issue by RetGoatCopper** [kangarko/ChatControl#1427]
When running the /list command, there is no response in chat.  debug.zip link has been sent to the email provided.

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
To add some more informations, I already checked a few things with the author:

- The network is in online mode (which means cracked users are not allowed), however, we still tried with `UUID_Lookup: false` to make sure this isn't related, it didn'thelp.
- The list command is already correctly enabled, and the plugin is up-to-date.
- The plugin seems correctly configured to work with bungee, and there are no errors related to this.
- The tests were made with 2 players on the same server, and none of them was vanished
- The author joined te server from through bungeecord, and not directly.
- We already set debug mode to `bungee`, and according to the output, the command was processed by the plugin, and the plugin did return the list to the right user, without any errors.

**Comment by kangarko** [comment]
Hey! Our current system had some limitations for large networks due to packet size. I have completely rewriten it and made it faster and simpler, in the next version, just open the List section in settings.yml, reconfigure the two new keys and it'll work fine :)
