### ISSUE TITLE
1.8.8 : How to enable formatting

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl#1428]
Minecraft Version: 1.8.8
MySQL: false
BungeeCord: false

How to enable formatting without enabling channels, or is there a way to format the chat without player having to join a channel ? 
![image](https://user-images.githubusercontent.com/34607217/139485028-5e1dd088-902d-40c5-80aa-4aae64816235.png)

**Comment by kangarko** [comment]
No, you need to have channels enabled to use formatting. If you dont like that, here is a tutorial on just having one channel like before: https://github.com/kangarko/ChatControl-Red/wiki/Channels#not-having-channels-and-only-having-1-chat-classic-system
