### ISSUE TITLE
Better Advertise Filter

### ISSUE THREAD

**Issue by justin2001** [kangarko/ChatControl#143]
I felt that the advertise filter is not that sensitive. And it cant block word ip. E.g. us.mineplex.com, play.guildcraft.org. It only blocks numbered ip. And can you make this plugin to detect ip adress and swear word from signs and books? Thanks you!

**Comment by kangarko** [comment]
You can customize the filters to your likings by editing them (they are located in files in folder rules/).

**Comment by justin2001** [comment]
Thanks!
