### ISSUE TITLE
[Question] How to enable features such as Private Messages

### ISSUE THREAD

**Issue by Grevd** [kangarko/ChatControl#1430]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

where can I activate the PM and such?

**Comment by TheIntolerant** [comment]
Inside the file settings.yml

**Comment by ElBananaa** [comment]
Hey,
As gone-incognito said these features can be enabled in the settings file.
I'd suggest reading ou wiki and the files comments as almost everything is explained there.
