### ISSUE TITLE
Missing death message options for stalactites and stalagmites

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl#1431]
Currently it is not possible to add a death messages for death by stalactites and stalagmites. It is only possible to add a death message for `CONTACT` and for `FALLING_BLOCK`. These collective death notifications become more and more confusing from version to version. It would be pretty cool if you could add your own death message for each differentiated vanilla death message. 
This will require separating from and extending the Spigiot API capabilities. I asked them: https://hub.spigotmc.org/jira/browse/SPIGOT-6769. It became clear that the differentiated gateway has to be the plugin, not the Spigiot API: 

> Not everything needs its own cause, you can easily tell if it is a stalactite by checking the block / entity as necessary. ~ mde5

**Comment by kangarko** [comment]
Thanks! I got this to work in the next version:

![a](https://i.imgur.com/gAq5lhl.png)
