### ISSUE TITLE
1.17.1 URL's Shortener 

### ISSUE THREAD

**Issue by LiannOM** [kangarko/ChatControl#1432]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: False

Hey, im trying to make rules with json support. 

What im trying to have:

When message matches regex:  https://stackoverflow.com/a/17773849/16907594

i want to make it replace actual url with [URL] in text that is json (https://pastebin.com/S84ECTpv)

so for example:
 
 if someone sends message without regex it would look like this:
 
 `%rank% %player% %nickname% some random text **www.mineacademy.org** some text blah blah`
 
 and i want it to be 
 
 `%rank% %player% %nickname% some random text **[URL]** some text blah blah`
 
 But only **[URL]** should be clickable and i want it to open url when clicked that player wrote on chat. (www.mineacademy.org in this case) i already tried to do it with rules and formats but didnt worked as i wanted :/
 
 I already spend 4 hours doing research and testing this... help please..
 
 (btw im using formats, my config for now https://pastebin.com/0V6pmRNM )

**Comment by kangarko** [comment]
Hi there! I am afraid this is outside of my expertise, I recommend asking on our Discord instead or eventually Spigot. Thanks and good luck!

**Comment by LiannOM** [comment]
Its not possible using JavaScript?

czw., 4 lis 2021, 14:41 użytkownik Matej Pacan ***@***.***>
napisał:

**Comment by kangarko** [comment]
I am afraid not.
