### ISSUE TITLE
Suggestion: Ability to modify Chat Color Menu gui header?

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#1433]
1. It would be a nice small change that'll allow us to integrate the chat color header with the overall theme of our servers

2. For an exciting feature that let's you change your chat color, the header "menu" in black is kind of bland. It's not a deal breaker though.

Also: Adding name colors would be OP;)

P.S Thanks for all of the awesome work you guys do, I'm always bragging about this plugin to my staff and sometimes players. Keep it up

**Comment by kangarko** [comment]
Yep, got it working for you!

![a](https://i.imgur.com/arsrIZe.png)
