### ISSUE TITLE
Ability to use PAPI placeholders on BungeeControl messages

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#1434]
Im trying to make switch messages silent when players are vanish.
I was trying JavaScript by using the VanishAPI PremiumVanish provides, but it seems like they only provide it on spigot.
If it was possible to use PAPI placeholders it would be no problem to check if players are vanish.

I know this is not easy to implement, but i know your skills Matej! ;)

**Comment by ElBananaa** [comment]
> Im trying to make switch messages silent when players are vanish. I was trying JavaScript by using the VanishAPI PremiumVanish provides, but it seems like they only provide it on spigot. If it was possible to use PAPI placeholders it would be no problem to check if players are vanish.
> 
> I know this is not easy to implement, but i know your skills Matej! ;)

Hey,
Unfortunately, this isn't something on our side, but on PAPI side, as PAPI doesn't support bungeecord, so I don't think Kangarko can do much about it.

**Comment by kangarko** [comment]
As Banana said. If they will support Bungee then we will too :)
