### ISSUE TITLE
Join message channel error

### ISSUE THREAD

**Issue by P-paj** [kangarko/ChatControl#1435]
Can i use channels without this "player console has joined standard" message being shown to everyone every single time someone joins the server?

players find it quite annoying - and i see no config option in the channels section to stop it

![image](https://user-images.githubusercontent.com/51720134/139598858-d823cf79-7807-44ff-b692-42543aa9a325.png)

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: true

**Comment by fyxisShazad** [comment]
I belive it was fixed in latest update:

Fix | Solved channel messages replacing player with Console instead of the player name for some cases.

**Comment by P-paj** [comment]
thanks


> 
> 
> I belive it was fixed in latest update:
> 
> Fix | Solved channel messages replacing player with Console instead of the player name for some cases.

thanks
