### ISSUE TITLE
QUESTION: Velocity Support

### ISSUE THREAD

**Issue by Tarlak333** [kangarko/ChatControl#1437]
Does CCR work on a Velocity Server Network?  If not, can I point multiple servers to the same discord channel as a "pseudo shared" channel?

Thx,

S2GN

**Comment by ElBananaa** [comment]
Hey,
Velocity support is currently WI, there's no ETA for its release tho.
Youes, you should be able to point multiple servers to the same discord channel, you may want to take a look at our dedicated wiki page to learn a bit more about it: https://github.com/kangarko/ChatControl-Red/wiki/Discord

**Comment by Tarlak333** [comment]
Hi, Thx for the info.  I'll test it out soon.
