### ISSUE TITLE
1.17.1: ItemsAdder not work with join/quit message

### ISSUE THREAD

**Issue by EnTIv** [kangarko/ChatControl#1438]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

![image](https://user-images.githubusercontent.com/38716516/139965816-12b434eb-79a7-4fa5-9cd8-157ca87e168d.png)

**Comment by ElBananaa** [comment]
Hey,
Please use the font placeholder in format files: https://itemsadder.devs.beer/plugin-usage/placeholderapi (Don't forget to replace `%%` with `{}`
