### ISSUE TITLE
Suggesting to synchronize CHC Death messages to Discord

### ISSUE THREAD

**Issue by xPaZzyy** [kangarko/ChatControl#1439]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)

It adds the same functionality DiscordSRV already offers but better.

2. What would happen if we won't implement this feature? How's your server being affected?

Missing a lot of good conversations due to deaths not synched to Discord.

So my suggestion is to add Death messages from CHC to DiscordSRV/Discord, so it's visible in the discord channel like by default if you only use DiscordSRV. But then of course way better with the improved death messages from CHC.

Thanks for reading.

**Comment by ElBananaa** [comment]
> 1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
> 
> It adds the same functionality DiscordSRV already offers but better.
> 
> 1. What would happen if we won't implement this feature? How's your server being affected?
> 
> Missing a lot of good conversations due to deaths not synched to Discord.
> 
> So my suggestion is to add Death messages from CHC to DiscordSRV/Discord, so it's visible in the discord channel like by default if you only use DiscordSRV. But then of course way better with the improved death messages from CHC.
> 
> Thanks for reading.

Hey,
This feature is already supported. Please make sure to read our wiki pages : https://github.com/kangarko/ChatControl-Red/wiki/Discord

To do so, you simply need to add `then discord` after each death message like on the wiki https://github.com/kangarko/ChatControl-Red/wiki/Messages#then-discord-channel-message

**Comment by xPaZzyy** [comment]
> > 1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
> > 
> > It adds the same functionality DiscordSRV already offers but better.
> > 
> > 1. What would happen if we won't implement this feature? How's your server being affected?
> > 
> > Missing a lot of good conversations due to deaths not synched to Discord.
> > So my suggestion is to add Death messages from CHC to DiscordSRV/Discord, so it's visible in the discord channel like by default if you only use DiscordSRV. But then of course way better with the improved death messages from CHC.
> > Thanks for reading.
> 
> Hey, This feature is already supported. Please make sure to read our wiki pages : https://github.com/kangarko/ChatControl-Red/wiki/Discord
> 
> To do so, you simply need to add `then discord` after each death message like on the wiki https://github.com/kangarko/ChatControl-Red/wiki/Messages#then-discord-channel-message

We talked about this, look how many messages there are. I'd love to just have it enabled by default

**Comment by ElBananaa** [comment]
> > > 1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
> > > 
> > > It adds the same functionality DiscordSRV already offers but better.
> > > 
> > > 1. What would happen if we won't implement this feature? How's your server being affected?
> > > 
> > > Missing a lot of good conversations due to deaths not synched to Discord.
> > > So my suggestion is to add Death messages from CHC to DiscordSRV/Discord, so it's visible in the discord channel like by default if you only use DiscordSRV. But then of course way better with the improved death messages from CHC.
> > > Thanks for reading.
> > 
> > 
> > Hey, This feature is already supported. Please make sure to read our wiki pages : https://github.com/kangarko/ChatControl-Red/wiki/Discord
> > To do so, you simply need to add `then discord` after each death message like on the wiki https://github.com/kangarko/ChatControl-Red/wiki/Messages#then-discord-channel-message
> 
> We talked about this, look how many messages there are. I'd love to just have it enabled by default

I'm pretty sure a such feature has been requested multiple times, from both authors that knew about the `then discord` operator, or not, but the point is that there's already a feature to allow you to fully customize how death messages are sent to discord. What you want is a step back to the customization.
All you have to do is basically copy/paste messages, which won't take more than what, five minutes, which is why I don't understand the issue with the current system...

ChatControl isn't a drag-and-drop plugin, and I don't think it could ever be one due to the amount of possibilities you have, so yeah, I don't really see the point of your feature request, since there's already a better way (even tho it takes a few minutes to setup) to do what you want. ^^

Anyways, let's wait for Kangarko.

**Comment by kangarko** [comment]
I've added it for you manually. Remove your death.rs file and then replace `#then discord` with `then discord` in the next version using Notepad++ or anything else. I would really appreciate a review if you like this change.

**Comment by xPaZzyy** [comment]
So I have ran into multiple issues doing this.

1: You can only define one message, for a group of 10+ death messages.
2: Defined mythicmobs coloured names are also being displayed to discord ex: "§8§lArgus"
3: Sometimes now message: appears ingame and not on discord 
![image](https://user-images.githubusercontent.com/61637026/140650975-29d34222-d646-491d-9886-0b3ced0e4dec.png)
4: The variable [killer_item] does not work on discord at all while it does work fine in game.
![image](https://user-images.githubusercontent.com/61637026/140650990-b4adad39-18a2-4599-9040-5da03251726c.png)

These are the issue I've ran into so far using the then discord rule.

**Comment by kangarko** [comment]
Thanks! I will add this to our roadmap, we have more important things right now but we can get to it later.
