### ISSUE TITLE
1.16.4: Discord integration issues and frustrations

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl#144]
Hello, the discord integration is very vague. The wiki goes pretty fast about it and doesn't focus on what's most important: the format. Integrating with discorsrv works fine, but then always sends the messages doubke. One format from chatcontrol and one from discordsrv. is discordsrv not compatible with your plugin, like it doesn't see you as a chat plugin? When setting discord format of the channel i'm linking to none, it only sends the format of discordsrv, wich is fine by me. When sending a messages through discord it goes through your normal chat.yml format. This is annoying since there are features there you don't want with discord messages and  otherwise. For example, I want to display a part with their toprole, (configurable in disocrsrv). Or I add Sender_Condition: {sender_is_discord} resulting in whole the format being broken or i don't. PLease explain the way discord integration works in the wiki or here thoroughly.

**Comment by kangarko** [comment]
Thanks for the feedback, I improved it and recorded a video for you: https://github.com/kangarko/ChatControl-Red/wiki/Discord

Next version will have these things covered.
