### ISSUE TITLE
Minecraft 1.17: NoSuchMethodError

### ISSUE THREAD

**Issue by Bloodylegacy2** [kangarko/ChatControl#1440]
I keep getting the following error when loading up my server, it's automatically disabling the plugin. https://pastebin.com/vLnb13KN
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
I cannot reproduce this on a clean Paper install: https://i.imgur.com/IDEOy5f.png

Test without other plugins on the latest Paper version.
