### ISSUE TITLE
1.8.8 : Formatting

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl#1441]
Minecraft Version: 1.8.8
MySQL: false
BungeeCord: false

![image](https://user-images.githubusercontent.com/34607217/140347931-ebd4404b-e0a0-4e82-8d7a-07cf4816327a.png)
https://www.toptal.com/developers/hastebin/icinujamuy.yaml

Im trying to make VIPS or whoever has the group.vip permission, they will have their name and write in chat with the white colour (&F)

But its showing both formatting, i even tried making group.default and negating it, but it did not work.

Thank you!

**Comment by kangarko** [comment]
The tab_tagprefix is duplicating with player_prefix, only use tag_prefix. Use your permissions plugin for managing prefixes per permissions.

**Comment by dabou0** [comment]
![image](https://user-images.githubusercontent.com/34607217/140378985-e71ec99b-8283-4f01-a947-eef7ec3473bd.png)
I think after ichaned it, now server will stop loading when it reachers chatcontrol, not sure if something broke.

https://www.toptal.com/developers/hastebin/midagowuzu.yaml  chat.yml
https://www.toptal.com/developers/hastebin/ejizotuxuk.yaml       latest log

Chatcontrol error.txt = empty

**Comment by kangarko** [comment]
Try on Paper, I have no clue. Try the next ChatControl red.

**Comment by kangarko** [comment]
Try disabling Console Filter.

**Comment by dabou0** [comment]
Console filter was already disabled, i tried  the next ChatControl and still the same thing

**Comment by ElBananaa** [comment]
> Console filter was already disabled, i tried the next ChatControl and still the same thing

Hey!
Did you try with Spigot/Paper?
Also, how much ram did you allocate to your server?

**Comment by dabou0** [comment]
I deleted the ChatControlRed folder and it will work again, so the spigot is not the problem

**Comment by ElBananaa** [comment]
> I deleted the ChatControlRed folder and it will work again, so the spigot is not the problem

Well, actually it doesn't mean the fork you're using isn't a problem. It may still be the reason of your issue, since, as example, it could mean you enabled a feature that needs something in spigot api, but which was removed by your fork... Anyways, glad you fixed your issue.
