### ISSUE TITLE
1.17.1: Tab-Complete Issue

### ISSUE THREAD

**Issue by morgan2233** [kangarko/ChatControl#1445]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

When Tab-Complete is enabled its not removing the BungeeCord tab options even know on the sale page it says under "Insane Bugeecord Support" -> "Tab-complete over your entire network!"

**Comment by morgan2233** [comment]
UPDATE: chatcontrol.bypass.tabcomplete also does not work

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1 MySQL: true BungeeCord: true
> 
> When Tab-Complete is enabled its not removing the BungeeCord tab options even know on the sale page it says under "Insane Bugeecord Support" -> "Tab-complete over your entire network!"

Hey!
You misunderstood the product page and the settings file.
The `Tab_Complete` feature in the settings file is to restrict the commands which can be tab-completed, while the `Tab-complete over your entire network` basically means that you can tab-complete player names over your entire network.
You can find more informations on our dedicated wiki page: https://github.com/kangarko/ChatControl-Red/wiki/BungeeCord

**Comment by morgan2233** [comment]
> > Minecraft Version: 1.17.1 MySQL: true BungeeCord: true
> > When Tab-Complete is enabled its not removing the BungeeCord tab options even know on the sale page it says under "Insane Bugeecord Support" -> "Tab-complete over your entire network!"
> 
> Hey! You misunderstood the product page and the settings file. The `Tab_Complete` feature in the settings file is to restrict the commands which can be tab-completed, while the `Tab-complete over your entire network` basically means that you can tab-complete player names over your entire network. You can find more informations on our dedicated wiki page: https://github.com/kangarko/ChatControl-Red/wiki/BungeeCord

Thank you; is there anyway I can block bungee commands on tab complete?

**Comment by ElBananaa** [comment]
> > > Minecraft Version: 1.17.1 MySQL: true BungeeCord: true
> > > When Tab-Complete is enabled its not removing the BungeeCord tab options even know on the sale page it says under "Insane Bugeecord Support" -> "Tab-complete over your entire network!"
> > 
> > 
> > Hey! You misunderstood the product page and the settings file. The `Tab_Complete` feature in the settings file is to restrict the commands which can be tab-completed, while the `Tab-complete over your entire network` basically means that you can tab-complete player names over your entire network. You can find more informations on our dedicated wiki page: https://github.com/kangarko/ChatControl-Red/wiki/BungeeCord
> 
> Thank you; is there anyway I can block bungee commands on tab complete?

Unfortunately, I don't think CHC-Red currently supports this feature.
You may want to take a look at this plugin, which, I believe, supports this feature (unfortunately, it's a premium resource): https://www.spigotmc.org/resources/%E2%9C%94%EF%B8%8F-plugin-hide-pro-1-8-1-17-spigot-bungee-velocity-suggestion-tabcomplete-command-blocker-%E2%9C%94%EF%B8%8F.77112/

If you're not in a rush, then I'd suggest waiting for Kangarko to review this as a potential suggestion ^^

**Comment by morgan2233** [comment]
> > > > Minecraft Version: 1.17.1 MySQL: true BungeeCord: true
> > > > When Tab-Complete is enabled its not removing the BungeeCord tab options even know on the sale page it says under "Insane Bugeecord Support" -> "Tab-complete over your entire network!"
> > > 
> > > 
> > > Hey! You misunderstood the product page and the settings file. The `Tab_Complete` feature in the settings file is to restrict the commands which can be tab-completed, while the `Tab-complete over your entire network` basically means that you can tab-complete player names over your entire network. You can find more informations on our dedicated wiki page: https://github.com/kangarko/ChatControl-Red/wiki/BungeeCord
> > 
> > 
> > Thank you; is there anyway I can block bungee commands on tab complete?
> 
> Unfortunately, I don't think CHC-Red currently supports this feature. You may want to take a look at this plugin, which, I believe, supports this feature (unfortunately, it's a premium ressource): https://www.spigotmc.org/resources/%E2%9C%94%EF%B8%8F-plugin-hide-pro-1-8-1-17-spigot-bungee-velocity-suggestion-tabcomplete-command-blocker-%E2%9C%94%EF%B8%8F.77112/
> 
> If you're not in a rush, then I'd suggest waiting for Kangarko to review this as a potential suggestion ^^

Ill wait for Kangarko to review; defiantly better if it can be included in this £30 plugin rather than me needing an addition £5 plugin; plus better to have less plugin jars

**Comment by kangarko** [comment]
Thanks for suggesting. I have added a simple tab filter for bungeecord commands, you will be able to specify which subcommands to filter tab completion from such as /server.

**Comment by morgan2233** [comment]
> Thanks for suggesting. I have added a simple tab filter for bungeecord commands, you will be able to specify which subcommands to filter tab completion from such as /server.

How exactly does this work? Like I updated the plugin to latest version and 0 change in what happens and config file. I thought maybe it would handled via Bungeecontrol red but in the update it was just a single jar file not a zip so no update jar for bungeecord (also if your download for first time, BungeeControl-Red wont be included now so where do we get that?)

**Comment by ElBananaa** [comment]
Hey,
Kangarko simply forgot to provide the bungeecontrolred jar. For now, please use the previous version of the plugin as you must use the bungee jar provided with the chc-red jar.
