### ISSUE TITLE
Sending Players Server

### ISSUE THREAD

**Issue by morgan2233** [kangarko/ChatControl#1446]
I would like the addition of a players server placeholder as the current server_name placeholder only shows the name of the current server of the reader and not the sending players.

1. I believe this would benefit others as it would allow better BungeeCord cross talk as it would allow you to show what server the player sending the message is in (this would be of specific benefit for the likes of staff chats and help chats).

2. If this wasn't implemented then nothing dramatic will happen; I will just be a little disappointed that a £30 plugin doesn't have the capability to display what server a user is in.

Edit: I am aware in settings you can set a bungeeprefix but I would like to be able to make custom ones per format rather than a blanket one

**Comment by morgan2233** [comment]
Update: found that {bungee_server_name} is a thing; please add it to your varibles wiki page as its not there

**Comment by kangarko** [comment]
Thanks, will add this to our roadmap. For now you can hardcode ones you want directly in the format file.

**Comment by morgan2233** [comment]
> Thanks, will add this to our roadmap. For now you can hardcode ones you want directly in the format file.

Do you have an example or explanation as I searched the wiki and nothing about the use of Bungee in the format files?

**Comment by kangarko** [comment]
I apologies for a late answer! I made a fix that will properly resolve the {server_name} to the sending player:

![a](https://i.imgur.com/Mn5sQpm.png)
