### ISSUE TITLE
Suggestion: Separate permission nodes for hex colors based on usage like normal color codes.

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1447]
Originally suggested in #1423 but I'll explain everything again :P

---

### **General Info**
So ChatControl has two different permission nodes for normal color codes (&1 &2 &3 &a &b &c etc)
These permissions are: 
 1) ``chatcontrol.color.{color}``
  2) ``chatcontrol.guicolor.{color}``

The first permission is for general color code usage, in the options listed in ``Colors.Apply_On``. 
These options include: chat, me, prefix, nick, suffix, private_message

However, the second permission node is just for the colors people can pick in ``/chc color``

---

### **Actual Suggestion**
Based on the layout for the normal colors shown above, I wanted to suggest this same logic be applied to the permission nodes used for Hex color codes. So there is one permission node for general hex color code usage and another permission node for enabling ur chat color via ``/chc color #<hexcode>``

Currently, there is only one permission node required for hex colors usage regardless if it is for ``/chc color #<hexcode>`` or it is for the options which are enabled in ``Colors.Apply_On`` (such as chat, me, prefix, nick, suffix, private_message)

My suggestion is to have one permission node for general hex color usage in the options in **Colors.Apply_On** (such as chat, me, prefix, nick, suffix, private_message)

Then have another permission node for hex colors for the command ``/chc color #<hexcode>``

Example perms for hex colors:
 1) ``chatcontrol.hexcolor.{color}`` - for general hex color usage (chat, me, prefix, nick, suffix, private_message)
  2) ``chatcontrol.guicolor.hex.{color}`` for chat color usage (``/chc color #<hexcode>``)

---

### 1. How it would benefit others? (Not just you, but 1,000s of other people using the same plugin.)
This would better allow server admins/owners to control where people are allowed to use hex color codes on their server. As well as keep things more consistent, since the normal color codes as explained above already have two different permission nodes depending on its usage.

### 2. What would happen if we won't implement this feature? How's your server being affected?
Admins/owners may decide to not allow usage of hex colors on their server/s if they are unable to find a way to better control where and when people use hex color codes since there is only one permission node for all hex color usage.

**Comment by kangarko** [comment]
What about if we merge hex permissions together with classic color formats so we only have this?

- chatcontrol.color.{color}
- chatcontrol.guicolor.{color}

And you will be able to specify either the classic color name such as "chatcontrol.color.red" or the hex code such as "chatcontrol.color.ccddff"

What do you think?

**Comment by TheIntolerant** [comment]
Yeah that would work too and make things even simpler too!

**Comment by kangarko** [comment]
Done!

**Comment by mav2020** [comment]
How do you give permissions to all regular colors but block the use of hex colors for a certain rank now? Do I have to put in all 16 colors instead of chatcontrol.color.*? Or is there a way to keep that and set hex to false (only for certain ranks)? This is a cosmetic perk that is perfect for keeping with the EULA.

**Comment by TheIntolerant** [comment]
> How do you give permissions to all regular colors but block the use of hex colors for a certain rank now? Do I have to put in all 16 colors instead of chatcontrol.color.*? Or is there a way to keep that and set hex to false (only for certain ranks)? This is a cosmetic perk that is perfect for keeping with the EULA.

That will depend on the permissions plugin you use. The easiest way to do this is to not use any wildcards and just add the permission nodes individually or if you use luckperms you can use this https://luckperms.net/wiki/Advanced-Setup#shorthand-permissions to replace the perm ``chatcontrol.color.*``.

An example could be this:
``/lp group member permission set chatcontrol.color.{red,yellow,gold} true server:vanilla`` etc
to give the group "member" permission for red, yellow and gold on the vanilla server.

Assuming you have shorthand enabled in the config

**Comment by mav2020** [comment]
Ok, so the answer is that I have to now set the permission for all 16 colors. I think there should be a way to set hex permission to false or an easier way to allow classic vs hex colors like it was before. (yes I use LuckPerms) I guess it is only really needed to write once and then can be copied, but I still think this is a commonly used permission that should be easier.

**Comment by DrkMatr1984** [comment]
> > How do you give permissions to all regular colors but block the use of hex colors for a certain rank now? Do I have to put in all 16 colors instead of chatcontrol.color.*? Or is there a way to keep that and set hex to false (only for certain ranks)? This is a cosmetic perk that is perfect for keeping with the EULA.
> 
> That will depend on the permissions plugin you use. The easiest way to do this is to not use any wildcards and just add the permission nodes individually or if you use luckperms you can use this https://luckperms.net/wiki/Advanced-Setup#shorthand-permissions to replace the perm `chatcontrol.color.*`.
> 
> An example could be this: `/lp group member permission set chatcontrol.color.{red,yellow,gold} true server:vanilla` etc to give the group "member" permission for red, yellow and gold on the vanilla server.
> 
> Assuming you have shorthand enabled in the config

Hmm, Now how would I do the opposite and allow access to all Hex Colors without giving players access to the basic 16 colors? I can't possibly type out every hex color code permission individually so the easiest way seems to be to give the chatcontrol.color.* permission. Yes I am aware they could just use hex colors to duplicate the 16 colors.

**Comment by TheIntolerant** [comment]
Going to reopen this issue for further consideration regarding the permissions for colours. While the change is great we have separate hex color permission nodes for chatcolor and general colour usage, this change unfortunately seems to have created a few complications.

**Comment by TheIntolerant** [comment]
@DrkMatr1984 @mav2020 

Would this be better? I'm not 100% sure just throwing ideas out there.

 1) ``chatcontrol.hexcolor.{color}``
 2) ``chatcontrol.hexguicolor.{color}``
 
On the plus side if it was like this, you could assign the permission node ``chatcontrol.color.*`` without giving access to hex colors or ``chatcontrol.hexcolor.*`` without giving access to normal colors? So this would probably be better and easier to manage?

**Comment by DrkMatr1984** [comment]
Yes, exactly what I was thinking. It aligns with a lot of other chat plugins that have separate permissions for both. Also, as I believe was already mentioned, selling both individually in a EULA friendly store just provides extra cosmetics.

**Comment by kangarko** [comment]
Sorry guys but I cannot please everyone, ChatControl is already a huge plugin and I feel it would just become more complicated adding every little feature.

Best thing is that you use your permissions plugin in an elegant way, using its inheritance system. So you can create a permission group "hexcolors" and "lettercolors" for example and make other groups inherit them as needed.

If your permissions plugin supports regex, you can use a regex matcher for hex permissions. If it does not, follow the advice below:

**A) Allow access to all Hex Colors without giving players access to the basic 16 colors:**
Give players `chatcontrol.color.*` and then negative 

```
chatcontrol.color.(black|dark_blue|dark_green|dark_aqua|dark_red|dark_purple|gold|gray|dark_gray|blue|green|aqua|red|light_purple|yellow|white)
chatcontrol.color.(magic|bold|strikethrough|underline|italic|reset)
```

**B) Allow access to all Letter Colors and disallow hex:**
Simply give players negative "-chatcontrol.color.*" permission and then give them the permissions for colors and decoration they can use from above.

**Comment by DrkMatr1984** [comment]
> Sorry guys but I cannot please everyone, ChatControl is already a huge plugin and I feel it would just become more complicated adding every little feature.
> 
> Best thing is that you use your permissions plugin in an elegant way, using its inheritance system. So you can create a permission group "hexcolors" and "lettercolors" for example and make other groups inherit them as needed.
> 
> If your permissions plugin supports regex, you can use a regex matcher for hex permissions. If it does not, follow the advice below:
> 
> **A) Allow access to all Hex Colors without giving players access to the basic 16 colors:** Give players `chatcontrol.color.*` and then negative
> 
> ```
> chatcontrol.color.(black|dark_blue|dark_green|dark_aqua|dark_red|dark_purple|gold|gray|dark_gray|blue|green|aqua|red|light_purple|yellow|white)
> chatcontrol.color.(magic|bold|strikethrough|underline|italic|reset)
> ```
> 
> **B) Allow access to all Letter Colors and disallow hex:** Simply give players negative "-chatcontrol.color.*" permission and then give them the permissions for colors and decoration they can use from above.

You should post this solution to the Wiki. I hadn't thought about just negating the base color perms. Others may not either. Most other Chat Plugins I use have separate permissions built in for both as I had described. It might help people in the future! Thanks :)

**Comment by kangarko** [comment]
Did yesterday, thanks! https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#color-permissions-how-to-disallow-hex-but-allow-letter-colors-or-vice-versa

**Comment by mav2020** [comment]
I was doing this as separate permissions since I wasn't sure how LuckPerms did lists like this. I think most people these days use LuckPerms. The following is the format used and I suggest adding this to the wiki as well (curly brackets and commas):
```
chatcontrol.color.{black,dark_blue,dark_green,dark_aqua,dark_red,dark_purple,gold|gray,dark_gray,blue,green,aqua,red,light_purple,yellow,white}
chatcontrol.color.{magic,bold,strikethrough,underline,italic,reset}
```

**Comment by DrkMatr1984** [comment]
If you negate all the base colors, 
`chatcontrol.color.{black,dark_blue,dark_green,dark_aqua,dark_red,dark_purple,gold|gray,dark_gray,blue,green,aqua,red,light_purple,yellow,white}
chatcontrol.color.{magic,bold,strikethrough,underline,italic,reset}`
but sell them chatcontrol.color.* later when you sell them hex colors, It still allows them to use classic chat colors.

I am trying to allow them to purchase each individual classic color one at a time.
They may also buy all hex colors as one package. 

I want these unavailable until purchased. How to do this with luckperms?

**Comment by kangarko** [comment]
Make sure those negated colors are actually negated and have the right syntax (not sure about the {,,,} one from above if that works for your luckperms version) and that they take over priority.

**Comment by DrkMatr1984** [comment]
I think the problem is with Luckperms:
`Inherited permissions will be overridden by an objects own permissions.
Example: A user is a member of the default group, which grants "some.thing.perm", but the users own permissions has "some.thing.perm" set to false. The inherited permission will be overridden by the users own permissions, and the user will be granted the negative node.`
https://luckperms.net/wiki/Advanced-Setup
So chatcontrol.color.* is overriding the negative values set in the default group. 
Can you point me to an elegant solution using luckperms? I'm selling the individual permissions, not groups, so I'm trying to avoid creating some kind of VIP group or something.

**Comment by TheIntolerant** [comment]
Due to the issue above I personally have chosen to not use chatcontrol's chatcolor gui etc, so I've implemented my own GUI which I can perform additional permission checks on.

While having the perms
``chatcontrol.hexcolor.{color}``
``chatcontrol.hexguicolor.{color}``
Would make managing what chatcolors users can use easier, I personally am not sure how to combat this issue in your case specifically.

**Comment by mav2020** [comment]
> I think the problem is with Luckperms: `Inherited permissions will be overridden by an objects own permissions. Example: A user is a member of the default group, which grants "some.thing.perm", but the users own permissions has "some.thing.perm" set to false. The inherited permission will be overridden by the users own permissions, and the user will be granted the negative node.` https://luckperms.net/wiki/Advanced-Setup So chatcontrol.color.* is overriding the negative values set in the default group. Can you point me to an elegant solution using luckperms? I'm selling the individual permissions, not groups, so I'm trying to avoid creating some kind of VIP group or something.

I don't think you can avoid a group in this case, but it can just be a group called 'hexpermission' or something. The only way I can think to do this would be to have the hex color permission be in a group that gives chatcontrol.color.* while negating the regular colors and fonts. Then the regular colors can be individual permissions set to true. This should accomplish your goal of selling hex and individual colors and fonts separately.

Edit to add: The other way would be to give chatcontrol.color.* along with negating the colors and fonts as individual permissions (not grouped like above). Then have the purchase change the false to a true for the color/font they buy. I think the group way mentioned above is more elegant though.

**Comment by DrkMatr1984** [comment]
The problem with the last solution is negating every single hex color node, which is nearly infinite. It makes it a daunting task to want to sell someone access to all hex colors. 
The problem with adding a group is that certain areas of my server display their group, or menus function differently depending on what group they are currently in. Moving them to new groups will mess all of that up. 
Can groups inherit groups that aren't part of their track? I have only ever messed around with perm groups that are on a single track. However, if say, for example, my Member group is in default track, could I create a new track and name it whatever and have a hex color group in there that can be inherited by an individual user?

**Comment by kangarko** [comment]
Thanks for the feedback, going to revisit this feature to make it more user friendly, @TheIntolerant would love to hear more about your setup so maybe we can push it to ChatControl if you want to!

**Comment by DrkMatr1984** [comment]
> @DrkMatr1984 @mav2020 
> 
> Would this be better? I'm not 100% sure just throwing ideas out there.
> 
>  1) ``chatcontrol.hexcolor.{color}``
>  2) ``chatcontrol.hexguicolor.{color}``
>  
> On the plus side if it was like this, you could assign the permission node ``chatcontrol.color.*`` without giving access to hex colors or ``chatcontrol.hexcolor.*`` without giving access to normal colors? So this would probably be better and easier to manage?

What he suggested here would be perfect. I use venturechat for most of my chat controls, and chatcontrol for managing language, spam, etc. (Admin stuff) Having similar perms to what other chat plugins offer(as suggested) with hex color and regular colors being separate would make it much easier to manage sales and permissions.

**Comment by kangarko** [comment]
Great, I will implement this!

**Comment by DrkMatr1984** [comment]
Thanks! And thanks for being a rock in the MC community for all these years.

**Comment by TheIntolerant** [comment]
Sorry about the delay but I would very much so have a similar issue to what was mentioned above so this solution works well!

**Comment by kangarko** [comment]
@DrkMatr1984 Thank you mister, appreciate it!

@TheIntolerant glad to hear!
