### ISSUE TITLE
Suggestion: Localization - make the prefix of "checker" messages editable.

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1448]
I wish to remove the ``{prefix_error}`` for messages in the localization file under the section called ``Checker:``.
Example shown below:
![image](https://user-images.githubusercontent.com/48093184/140486751-e8801755-460d-4ad2-bdc5-66c77633f60c.png)

1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
This would just mean owners like myself would be able to better edit these messages to their own liking.

2. What would happen if we won't implement this feature? How's your server being affected?
Nothing really, as stated above, it would just be nice if the prefix for these messages was editable so it could either be hidden completely or changed, etc.

**Comment by TheIntolerant** [comment]
Just for clarification, I was hoping for a way to remove the prefix from the messages under "checker" without removing the prefix itself. Since I know you can edit the prefixes themselves and wish to continue using them elsewhere in the plugin.

**Comment by kangarko** [comment]
The best and the most proper way would be to go through each localization file and add {prefix_error}, {prefix_warn}, {prefix_info}, {prefix_success}. Then I would have to check each message in the code and remove the hardcoded prefix. If you have the time to edit the localization, I will find the time to edit the code so we can help each other :)

As a dirty fix I have added it so you can use \@noprefix to force prefix not to be added:

![a](https://i.imgur.com/3xkIOfS.png)
