### ISSUE TITLE
Ability to change the timezone of the plugin.

### ISSUE THREAD

**Issue by MrCrazys** [kangarko/ChatControl#1449]
I would like to have the option to change the timezone of the plugin to match the timezone my players are joining in, as it is very confusing for me when checking through the logs of the plugin, etc. as it is in a different timezone.

**Comment by ElBananaa** [comment]
Hey,
I'm pretty sure the plugin currently uses the timezone of your server. So if your server is hosted in London, it'll use London timezone.

**It is currently already possible to change the timezone if you are using mysql**.

To do so, in your mysql.yml file, add `&serverTimezone=YOURTIMEZONE` at the end of the connector line.
As example, this is how it looks like on my side:
`Line: "jdbc:mysql://{host}/{database}?autoReconnect=true&useSSL=false&serverTimezone=UTC"`

You can find a list of all the available timezones here : https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations
(Unfortunately, I don't know if you need to use the abbreviation, or the UTF offset, and I have no way to try it for now).

**Comment by kangarko** [comment]
We use the timezone of the server currently, but thanks for suggestion and thanks to Banana for the tip!
