### ISSUE TITLE
Hello. I Need help with ChatControl how to bypass?

### ISSUE THREAD

**Issue by marekumas** [kangarko/ChatControl#145]
Hello.
Help Me Please.
I Tried many Permissions..
Dosen't work..
How to do i make so donators can bypass it from
Please Don't Repeat Same Command.
Please help kong

**Comment by EvilOlaf** [comment]
https://github.com/kangarko/ChatControl/blob/master/src/kangarko/chatcontrol/utils/Permissions.java

For commands this would be `chatcontrol.bypass.dupe.commands` as an example.

**Comment by marekumas** [comment]
No Disney work

**Comment by kangarko** [comment]
The permission EvilOlaf wrote is correct. Also check wikipedia for tips on those features.

https://github.com/kangarko/ChatControl/wiki#frequently-asked-questions
