### ISSUE TITLE
1.17.1: Receiver_Nick placeholder not working

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1452]
The recently added placeholder {receiver_nick} doesn't appear to work. Please see attached files and screenshot.

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false
![](https://media.discordapp.net/attachments/711456455772864522/906813078207856672/unknown.png)

Format:
  everything:
    Message: '&7✉ [&fYou &7-> {receiver_nick}&7] &f{message}'
    Hover:
    - '&fPrivate Message'
    - '&3Received: &f{timestamp}'
    - '&3Sender: &f{sender}'
    - ''
    - '&7Click to reply.'
    Suggest_Command: '/r '

**Comment by ElBananaa** [comment]
Hey,
I believe this variable is only compatible with our internal nick system.
Do you use another plugin for nicks?

**Comment by HorusApl** [comment]
Yes, I use EssentialsX which I would assume would be fairly common? Among users who might also have this installed.

**Comment by ElBananaa** [comment]
> Yes, I use EssentialsX which I would assume would be fairly common? Among users who might also have this installed.

Well, this is the reason of your issue I believe.
Afaik, the `{receiver_nick}` variable only works with our nick system.

**Comment by kangarko** [comment]
I will fix that and support CMI/EssentialsX in that placeholder starting next version!
