### ISSUE TITLE
1.17.1: Announcement per Server

### ISSUE THREAD

**Issue by morgan2233** [kangarko/ChatControl#1453]
Is it possible with the /chc announcement command to only send announcements to the server your on instead of the whole network?

If not then assume this is a feature request.

Would also be good to send announcements to server clusters as defined in BungeeControl-Red config

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by TheIntolerant** [comment]
I believe you can if you type something like
``/chc announcement chat server:survival this message is sent to survival``
"this message is sent to survival" would be shown on the survival server.
