### ISSUE TITLE
Player skin in MOTD

### ISSUE THREAD

**Issue by TheIntelloBox** [kangarko/ChatControl#1454]
Hello,

It is possible to do a MOTD that displays an image of the player's skin ? :)

Best regards,
TheIntelloBox

**Comment by ElBananaa** [comment]
Hey,
This has already been suggested multiple times, however and we don't plan adding this feature right now.
(For more informations see #1344)

**Comment by kangarko** [comment]
Starting the next version you will be able to add this via commands: 

![a](https://i.imgur.com/7zBOWwI.png)

**Comment by kangarko** [comment]
This is in the new Motd section of settings.yml
