### ISSUE TITLE
Automatic message

### ISSUE THREAD

**Issue by TheIntelloBox** [kangarko/ChatControl#1455]
Hello,

Have automatic messages been removed from the plugin ? :)

Best regards,
TheIntelloBox

**Comment by ElBananaa** [comment]
Hey,
No, this is still a feature.
You may want to take a look at the `/messages/timed.rs` file.

You also need to enable them in the settings file. To do so, look for the `Messages.Apply_On` part in the `settings.yml` file (near line 510 in the default file), and read the comments.
