### ISSUE TITLE
[Suggestion] /ignore also ignores discord messages from the ignored player

### ISSUE THREAD

**Issue by Tizooo** [kangarko/ChatControl#1459]
hey. i connected discord and minecraft chat together so the messages are sync. would be cool if someone ignores a player he also doesent see his discord messages ingame.

**Comment by ElBananaa** [comment]
> hey. i connected discord and minecraft chat together so the messages are sync. would be cool if someone ignores a player he also doesent see his discord messages ingame.

Hey,
I believe this isn't possible currently since a such feature would require every ingame user to link their ingame account with their discord account. ^^

**Comment by Tizooo** [comment]
oh okay, on my server i made it so its only possible to use discord when they are linked...
