### ISSUE TITLE
1.16.4 - Users being booted out of channels randomly?

### ISSUE THREAD

**Issue by PascalBrassat** [kangarko/ChatControl#146]
This was reported to me a few moments ago, after a certain amount of time in our global/primary channel the user gets booted at one point and it instead gives them this message; https://i.imgur.com/Q6Ct9eq.png telling them to rejoin channels.

I am running the release that you put out last night.

Bug report reported to me;

Unable to see global chat while using nation chat

Please describe in detail the bug or issue.
see title

Evidence:
https://gyazo.com/cb41e8a0e7d5d89b112962ec28583fdf <-- my alt
https://gyazo.com/ddac899a5cbfdedfaef095bbca6a641f <-- me

**Comment by Godlycreations** [comment]
I am seeing this issue as well on 1.16.4 BungeeCord/MySql. Players can be talking and then just randomly need to join the channel again to keep talking.

**Comment by NerdyBirder** [comment]
Yes i have the same issue where i have to rejoin the global channel randomly even though i have the autojoin permission. just inconvenient really

**Comment by kangarko** [comment]
We have a 30 minutes timer that will check if players can stay in a channel:

Enable Show_Tips in settings.yml and let me know if any of you is seeing messages like these:

![a](https://i.imgur.com/kpRIYpQ.png) in the console (the blue ones)

**Comment by PascalBrassat** [comment]
I have done some further testing, it seems this may be a issue with the bungee control? We implemented this plugin on our network last weekend, however due to issues had to disable it again. On my localhost I am unable to reproduce it at the moment.

**Comment by kangarko** [comment]
Got it. Assuming next version solves this given players have the chatcontrol.channel.join.{channel}.{mode} to stay in channel (replace channel and mode appropriately), if not you will see these console messages that we removed them.

**Comment by PascalBrassat** [comment]
This seems to still be an issue, it does seem to boot you after roughly 30 minutes, I did not see anything for tips however in regards to removing a user. Again this seems to be an issue targeted towards bungee servers. It boots you from every channel at this point.

**Comment by kangarko** [comment]
What permissions do people who got booted have?

**Comment by PascalBrassat** [comment]
chatcontrol.channel.join.global.read
chatcontrol.channel.join.global.write
chatcontrol.channel.autojoin.global.read
chatcontrol.channel.leave.global
(Above permissions are copied among a handful of other chats, being, trade, local, nation, internationaltrade, alert, Max amount of read channels was bumped up to deal with the fact that they are in so many)

chatcontrol.channel.autojoin.global.write
chatcontrol.bypass.signduplication
chatcontrol.chat.read
chatcontrol.chat.write
chatcontrol.command.reply
chatcontrol.command.tell
chatcontrol.silence.join
chatcontrol.silence.leave
chatcontrrol.silence.switch

**Comment by NerdyBirder** [comment]
Just tonight with the latest release 10.1.2 i was actively talking in global and it booted me out. I had not gone afk or anything and had my like third message not send and it tell me that "have no channel to write in".

**Comment by broken1arrow** [comment]
I get same problem, not see no msg in console , like that you say.

Get this , but not for the channel i was in (MC-global). This msg i get is 100% normal (work as it should).
[ChatControlRed] TIP Warning: Player bonna_macke had chatcontrol.channel.autojoin.mc-✆hjälp.read but lacked chatcontrol.channel.join.mc-✆hjälp.read so he won't be added to the 'mc-✆hjälp' channel!

I will check perms
I add chatcontrol.channel.mc-globalt.write

I have this
chatcontrol.bypass.channellimit
chatcontrol.channel.autojoin.mc-globalt.read
chatcontrol.channel.autojoin.mc-globalt.write
chatcontrol.channel.autojoin.mc-lokalt.read
chatcontrol.channel.join
chatcontrol.channel.join.mc-globalt.read
chatcontrol.channel.join.mc-globalt.write
chatcontrol.channel.mc-globalt.leave
chatcontrol.channel.mc-globalt.send
chatcontrol.channel.join.mc-lokalt.read
chatcontrol.channel.join.mc-lokalt.write
chatcontrol.channel.mc-lokalt.leave
chatcontrol.channel.mc-lokalt.read
chatcontrol.channel.mc-lokalt.send
chatcontrol.channel.join.mc-✆hjälp.write
chatcontrol.channel.mc-✆hjälp.leave
chatcontrol.channel.mc-✆hjälp.send

Edit.
Even with perm chatcontrol.channel.mc-globalt.write i get disconnected, but only one time and seams to work now.

**Comment by kangarko** [comment]
@broken1arrow you also need to give the player "chatcontrol.channel.join.mc-✆hjälp.read" permission as the message told

**Comment by kangarko** [comment]
I apology for this issue, I had the player cache being removed after 30 minutes automatically to save RAM:

![a](https://i.imgur.com/f4HA6bM.png)

I made it persistent and only be removed when the player leaves the server in the next version.

**Comment by broken1arrow** [comment]
> @broken1arrow you also need to give the player "chatcontrol.channel.join.mc-✆hjälp.read" permission as the message told

Sry i was not clear, is something I know will happen (only mentioned it, at it work on one channel ). But i was in "global" chat and get kick out and not get a msg, like I get on mc-✆hjälp channel (but add chatcontrol.channel.mc-globalt.write and it seam like fix the issue). And remove chatcontrol.channel.autojoin.mc-globalt.read (it was not soo good it get added).

 
>>> I apology for this issue, I had the player cache being removed after 30 minutes automatically to save RAM:
I made it persistent and only be removed when the player leaves the server in the next version

For me it would have been good if you kept this, just to be able to save some ram :) But well make no major difference in the end :)

**Comment by kangarko** [comment]
Great thanks for letting me know. If you have any more issues just write below ;)
