### ISSUE TITLE
Locking Players into PM works a little strange

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1461]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
The behavior is not inherently clear, and other plugins use this type of behavior as standard.
2. What would happen if we won't implement this feature? How's your server being affected?
Any time a player types "/msg <name" and "locks" themselves into a PM channel with the other person, a large percentage are confused on how to get out of the "lock". 

The "lock" of messages when typing "/msg <name>" and it gives "Now conversing with <name>" and all messages typed are only sent to that player is a little quirky, and not obvious to some if a lot of messages are sent in chat. My suggestion would be after you are locked into the PM, allow the unlock to happen with /global instead of just re-typing /msg <name>.

So simply adding an option to type /chat, or /global would be ideal so players can easily exit this PM lock. Currently, typing /global will just say you are in that channel already but you are technically in a PM channel with the other person.

**Comment by HorusApl** [comment]
As well, the /mail send system works a little strangely. I don't believe the system is easy to use for normal players. Instead of giving a book to type with, save the book, and then right click the book to send it, a simple system of /mail send <message> would be good. Or at least a toggle option in the config, for those who prefer the "advanced" book version of /mail of for those who enjoy the simpler option I suggested.

**Comment by kangarko** [comment]
You can create a custom command such as /chat that will invoke "/tell off": https://github.com/kangarko/ChatControl-Red/wiki/Custom-Commands

Regarding books, thanks, however having two systems would be an overkill and prone to bugs.
