### ISSUE TITLE
1.17.1: Help needed to complete startup guide

### ISSUE THREAD

**Issue by Darkside247** [kangarko/ChatControl#1462]
Minecraft Version: 1.17.1 paper 
MySQL: true
BungeeCord: tru
![chc](https://user-images.githubusercontent.com/74486290/141071378-57d31c32-ae07-4ef7-b786-40a2beebe8e8.PNG)
e

**Comment by Darkside247** [comment]
Hey, So i did the tour and confirmed it, and i am still getting this message every time i try to run a command

**Comment by TheIntolerant** [comment]
Hey @Darkside247, so during this setup stage, it will give you a link to the terms and conditions. You must read the terms than you will find a command stated in the terms and conditions that you need to run. Once you do that than the setup process will be complete.

**Comment by kangarko** [comment]
Read the terms properly, there is a command /chc tour SPECIALKEY you will find there to unlock the plugin

**Comment by kangarko** [comment]
Or do you mean you have already typed this command, saved it but it appears again after restart? Send us your /chc debug or ZIP your folder

**Comment by Darkside247** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7516711/debug.zip)

I have done the tour multiple times and entered the command it asked to to. it then tells me that commands have been unlocked but they haven't here is the debug you asked for

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7516711/debug.zip)
> 
> I have done the tour multiple times and entered the command it asked to to. it then tells me that commands have been unlocked but they haven't here is the debug you asked for

Did you find the command given in our terms and did you run it? (https://github.com/kangarko/ChatControl-Red/wiki/Terms)
I tried to reproduce your issue but I was unable to.

**Comment by kangarko** [comment]
Sorry for the delay. That is really strange, anyways I have edited your data.db in the zip, so you can just upload the data.db to your folder from the file below and it should work.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7546206/debug.zip)

**Comment by Qveshn** [comment]
Hi
The same problem. I can not start ChatCotrolRed to use.

ChatControl-Red-10.8.6

Today I upgraded ChatControlPro from spigot to ChatControlRed on MC-market via request on mineacademy.
Then I waited while ChatControlRed on MC-market will be able for download.
Then I downloaded it. zip file 
Then I backup and remove old plugin ChatControlPro and stopped+started server
I did `/chc tour`, `/chc tour migrate` and  `/chc tour confirm`
It sends me to https://github.com/kangarko/ChatControl-Red/wiki/Terms
> You will find the unlock command by reading our Terms.

I have read it but I did not find any "/chc tour SPECIALKEY" and I do not understand where to get that "SPECIALKEY"
I found only:
```
Network unlock
If you have a large network, here's how to complete the tour in the plugin as fast as possible.

Boot one Spigot server and complete the tour. It will write a flag to data.db. Then type /stop and copy and paste this file over your entire network.
```
But there are nothing useful in plugins/ChatcontrolRed/data.db after `/chc tour confirm`:
```
#
# This file stores various data you create via the plugin.
#
#  ** THE FILE IS MACHINE GENERATED. PLEASE DO NOT EDIT **

Metadata:
  Entity: {}
  Block: {}
```
May be I do something wrong?
Should I also add "Tour_Completed: true" to data.db?

**Comment by Darkside247** [comment]
Then you do the tour there is a link to take you to the full terms of service the word you need to enter is in there it's done to make sure you read it

**Comment by Qveshn** [comment]
Finally I figured out what this special word was. 😕 

@TheIntolerant @kangarko 
You should do something with text here:
https://github.com/kangarko/ChatControl-Red/wiki/Terms

The problem is that the commands are not separated from the text by quotation marks or something else.
Not everyone knows English well to guess how and where to separate these parts of the text yourself.

What happened to me:
When I started reading, I first got to the phrase:
> Please use /chc tour command and read our Wiki first before asking questions

I ran the command: `/chc tour command` and found out that this is wrong command.
Then I ran `/chc ?` and found out that the most suitable command is `/chc tour`.
Then I ran `/chc tour` and found out that there are only two commands `/chc tour start` and `/chc tour migrate`
This commands I have already done before.
The last new command from tour (I found) was `/chc tour confirm` and then it sends me back to the terms...
I continued to read terms...
When I met the following command in the text, I could not translate the word after "tour" (only now I realized that it was a special word) and thought that I had to type just the `/chc tour` (as in the first case). But I have already done it. Therefore, I skipped it and continued reading further...
The last sentence I read was:
>Boot one Spigot server and complete the tour. It will write a flag to data.db. Then type /stop and copy and paste this file over your entire network.

And I again typed `/chc tour confirm` and stop and start server. But this did not give the expected results.
Reading these terms has become a charade game. 😟

**Comment by ElBananaa** [comment]
Hey,
I'm glad you found a way to complete the startup guide.
A lot of users had issues with how the system works, so be reassured, you're not the first struggling with it haha.

Anyways, I also do believe this should be reworked. Users don't like how this feature currently works, and I can understand that (And there's no real point a making it that "hard").

I'd suggest completely removing the `/chc tour **SPECIALKEY**` command, instead, users would have to typer `/chc tour confirm` once, then the plugin will return: `By completing the tour, you agree to our terms, and won't violate them. Type the command again to complete the tour.` It would make more sense, and make this feature WAY more easier.

I also think reducing the amount of pages in the tour to ~2 pages, with most of them filled with wiki links & the terms link would make more sense.

**Comment by Qveshn** [comment]
@ElBananaa 

Yes!
Firstly user sees in console: 
```
Before you start using this product, you need to
agree to our Terms of Service and complete a quick
tour with '/chc tour' command.
```
He does not understand what terms it was said, and therefore just runs `/chc tour`. Then `/chc tour start` and sees:
```
...
Thank you for reading. To get started using ChatControl
type '/chc tour confirm'.
```
He types `/chc tour confirm` and sees:
```
[!] By continuing, you indicate that you have fully read
and understood our Terms of Service and have completed
our tour process. Otherwise you will get no support.

https://github.com/kangarko/ChatControl-Red/wiki/Terms

You will find the unlock command by reading our Terms.
```

Look at this phrase again: "You will find the **unlock command** by reading our Terms." 

User opens https://github.com/kangarko/ChatControl-Red/wiki/Terms and finds only one one place with word "**unlock**":
>**Network unlock**
>If you have a large network, here's how to complete the tour in the plugin as fast as possible.
>
>Boot one Spigot server and complete the tour. It will write a flag to data.db. Then type /stop and copy and paste this file over your entire network.

And he does not understand how to complete the tour...
It says: "Boot one Spigot server and complete the tour. It will write a flag to data.db"
He thinks that to complete tour he should type again `/chc tour confirm`, but nothing is written to data.db.

I think the last paragraph "Network unlock" confuses people. They think that this is a way to unlock plugin.
But "... here's how **to complete the tour** in the plugin..."
and "Boot one Spigot server and **complete the tour**..."
puts people into a stupor...
And user again has a question: "So how to complete the tour?"

### Here are my humble suggestions:

1. Plugin message in `/chc tour start/migrate`:
"To get started using ChatControl type '/chc tour confirm'" - this is not true! After that command user will not be able to use ChatControl. It is only starts the procedure for completing the tour.
I think it will be better to write instead it something like: "Read our terms here `...` to understand how to complete the tour and start using ChatControl"

2. Remove command `/chc tour confirm` at all

3. Terms:
"To accept that, type /chc tour specialkey in game" - it is better to replace this phrase with something like
"To accept that and complete the tour, type /chc tour specialkey in game"

4. Terms:
The last paragraph "Network unlock" is useless. Once user finds out how to complete tour (with special key), then he can easy do it on other servers. In any case, he will have to deal with the plugin settings on each server separately.
Moreover, this does not refer to terms. This is more of a hint. I think it should be removed from terms.
It is better to write somewhere in faq that after completing the tour, it will write a flag to data.db and you can copy this file over your network.

Thanks

**Comment by kangarko** [comment]
Going to read this conversation tomorrow, thanks for the feedback guys!

**Comment by kangarko** [comment]
The command is /chc tour mothman, you need to read the terms of service article in full to find it. I've added clarification to the bottom of that article thanks to your feedback.
