### ISSUE TITLE
 Returning the {message} variable to "Hover" in ChatControlRed

### ISSUE THREAD

**Issue by mrstirlic** [kangarko/ChatControl#1463]
1. This will benefit both me and others, because I use the old format of private messages, as in ChatControl Pro, and it is so convenient for me, because after I sent someone on the server a private message, I can safely point to " The message was sent ", and see what message I sent, believe me, it will be useful, not only for me, but for everyone.

2. Well, if you do not add this function (more precisely, if you do not return it), inconveniences may occur, because I do not know the Java programming language, and even more so JavaScript

**Comment by kangarko** [comment]
Thanks, added!
