### ISSUE TITLE
1.17.1: Welcome message of BungeeControlRed not always working

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1464]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

This bug is related to the welcome message of BungeeControlRed.

It is setup as so:

```
group newcomer
ignore playedbefore
message:
- '&x&F&D&E&A&8&3Verwelkom &x&5&F&C&0&8&5{player} &x&F&D&E&A&8&3op de server!'
```
Sometimes (not always!) a new player logs in to the lobby and there is no welcome message showing up.

Example player:
![image](https://user-images.githubusercontent.com/5664135/141107789-205f975b-f356-4264-a77d-146439790fce.png)

There was no in-game welcome message, but he is confirmed to be a new player:
![image](https://user-images.githubusercontent.com/5664135/141107954-b9279a9f-1da9-43f5-8110-f1788b99dc89.png)

![image](https://user-images.githubusercontent.com/5664135/141107877-09b0b98b-e236-4645-9e68-f86ca647b42b.png)

**Comment by kangarko** [comment]
Just to confirm, do you have the welcome message in messages/join.rs of BungeeControl?

Are you saying that BungeeControl join message does not work, but ChatControl Red works?

**Comment by Sikatsu** [comment]
Correct indeed! It's in join.rs of bungeecontrol.

**Comment by kangarko** [comment]
Looking into this, please test the next version.

**Comment by kangarko** [comment]
Closing, lemme know if this is still inconsistent in the next release.

**Comment by Sikatsu** [comment]
This does not seem to be fixed, same information as before.. @kangarko

**Comment by kangarko** [comment]
I have rewritten the mechanism from:

- We would set a cycle of a repeating task asking if Bungee received synced data from Spigot.

To:

- Spigot sends data to Bungee when player is fully loaded and we simply listen to the packet and broadcast.

From my testing it worked flawlessly, please let me know how it goes for you!

**Comment by Sikatsu** [comment]
https://media.discordapp.net/attachments/901843790598381578/916352221552181248/unknown.png

https://media.discordapp.net/attachments/901843790598381578/916352310374985768/unknown.png

This is still not solved, while he did not get his welcome message, he also didn't get ANY join message.

**Comment by kangarko** [comment]
I am out of answers... Please set Debug to [player-message] **in the next version**, it should give reasons to console why/why not the message was broadcasted like this:

```
[07:51:24 INFO]: [BungeeControl-Red] Detected kangarko join to survival, waiting for server data..
[07:51:25 INFO]: [BungeeControl-Red] Broadcast join message for kangarko with variables {server=survival}
```

**Comment by kangarko** [comment]
(In the next version)

**Comment by Sikatsu** [comment]
It happened again, though I have a feeling as of why. This player was kicked on join because he or she has an outdated client, in that case the welcome/join message gets cancelled and on the next join, it will just show the normal join message instead. 

https://pastebin.com/psP1TPRu

https://media.discordapp.net/attachments/901843790598381578/917101255116083210/unknown.png

**Comment by kangarko** [comment]
Oh I see. Thanks so much for letting me know. Yep, in this case the join handle is cancelled before we can catch it I assume. Also apology for the delay, as a solo dev I was also launching my learning portal. Okay, closing this happily, let me know if you will have any more issues!
