### ISSUE TITLE
Autojoin

### ISSUE THREAD

**Issue by TheIntelloBox** [kangarko/ChatControl#1466]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Hello,

I've set these permissions:
- chatcontrol.channel.autojoin.global.write
- chatcontrol.channel.autojoin.global.read
- chatcontrol.channel.join.global.write
- chatcontrol.channel.join.global.read
- chatcontrol.channel.global.join.write

However, people still have an error message saying that they need to write /channel join.

Best regards,
TheIntelloBox.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1 MySQL: true BungeeCord: true
> 
> Hello,
> 
> I've set these permissions:
> 
> * chatcontrol.channel.autojoin.global.write
> * chatcontrol.channel.autojoin.global.read
> * chatcontrol.channel.join.global.write
> * chatcontrol.channel.join.global.read
> * chatcontrol.channel.global.join.write
> 
> However, people still have an error message saying that they need to write /channel join.
> 
> Best regards, TheIntelloBox.

Hey,
The autojoin feature only works if your users don't leave the channel manually. If they joined another channel manually/left these channels manually, they won't be added back to it.
Make sure to give everyone the `chatcontrol.channel.autojoin`, `chatcontrol.chat.read` and `chatcontrol.chat.write` permissions.

I also suggest you take a look at the `Join_Read_Old`, `Ignore_Autojoin_If_Left` and `Autojoin_On_Reload` options in the plugin's settings file.

**Comment by TheIntelloBox** [comment]
Thanks a lot !
