### ISSUE TITLE
1.8.8 : Not able to use chat

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl#1467]
Minecraft Version: 1.8.9
MySQL: false
BungeeCord: false

![image](https://user-images.githubusercontent.com/34607217/141208069-20f5b856-cd15-4249-b95b-d19e2d0a7802.png)
![image](https://user-images.githubusercontent.com/34607217/141208091-5cb601d5-680e-42b7-9da1-7f5d7c83e6f0.png)

im not sure what is happening here, everytime i will type in chat it will kick me

**Comment by dabou0** [comment]
i found out hat if im vanished it will give this error, if im not i can chat normally

**Comment by ElBananaa** [comment]
Hey,
Please provide us your `/chc debug` file.

**Comment by dabou0** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7516541/debug.zip)

**Comment by ElBananaa** [comment]
Thanks.
Please make sure to use Spigot or Paper. We do not support Craftbukkit as said on our wiki page: https://github.com/kangarko/ChatControl-Red/wiki/Compatibility#minecraft-server
You're also using a wrong vault version. As said on Vault's spigot page, the latest versions only work with versions between 1.13 & 1.17. Please use Vault 1.6.7 instead (https://www.spigotmc.org/resources/vault.34315/download?version=240549).
Finally, please update the plugin to v10.7.9.

**Comment by dabou0** [comment]
Welp, i dont use craftbukkit but i use Taco (Imanity Spigot 3)  https://www.mc-market.org/resources/10770/
I will try updating my vault, thank you

**Comment by ElBananaa** [comment]
> Welp, i dont use craftbukkit but i use Taco (Imanity Spigot 3) https://www.mc-market.org/resources/10770/ I will try updating my vault, thank you

Well, it's pretty much the same, we don't support third-party forks like this one, so please give it a try with spigot/paper to see if it happens.

**Comment by dabou0** [comment]
![image](https://user-images.githubusercontent.com/34607217/141221645-a91eb59a-b90b-47da-a11b-2d1d382ab8fc.png)

Same error on paper

Note: I change to vault 1.6.7
and am using CCR v10.7.9.

**Comment by ElBananaa** [comment]
That's weird.
When does this happens exactly?
Are you sending a specific message to "UrGonnaDie"?

**Comment by dabou0** [comment]
im just writting in chat normally, it happens only when im vanished (Super Vanish)

**Comment by dabou0** [comment]
weird, after these error it will start happening the same error from here, https://github.com/kangarko/ChatControl-Red/issues/1441

So i deleted my CCR folder again to fix it.

i disabled also , so now if im vanished it wont give that problem anymore, only bad thing is that i cant use this now.
  Save yourself from accidentally revealing you are online by disabling your ability to send
  direct chat messages. You will need to use "/channel send" instead.
  Prevent_Vanish_Chat: false

**Comment by kangarko** [comment]
Stop your server.

Add utf8 to your startup flags: https://www.spigotmc.org/threads/weird-utf-8-encoding.408238/#post-3629551

Before starting the server, remove messages/messages_en.yml file.
