### ISSUE TITLE
1.17.1: unusual space in between death messages + error message

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#1468]
Not sure what to make of the error message or how to solve this. 2 deaths in a row will generate this error, couldn't seem to find any blanks in the localization file

The death coords are simply a chc warning that triggers with the death message.

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false
Debug: [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7523414/debug.zip)
Error message: https://pastebin.com/47JQqqii
Death.rs: https://pastebin.com/q7Xmf73c

Edit: I also notice the first join example for mc 1.13 or greater, that comes with the join.rs has stopped working (just goes straight to default join message regardless if player is regular or new). Any help with that would be super appreciated:) This is what it looks like in the join.rs file: https://pastebin.com/a204dHZu

![Untitled-2](https://user-images.githubusercontent.com/71758114/141373177-a5f3e961-7c13-40c7-a7df-573fdb3e38b2.jpg)

**Comment by kangarko** [comment]
Thanks, I will fix the Discord error. Regarding the statistic, make sure there is no other error in the console in the next version, and check if other plugins are not interfering.
