### ISSUE TITLE
1.17.1: Invisibility Effect also renders player invisible to chatcontrol 

### ISSUE THREAD

**Issue by SiuanSong** [kangarko/ChatControl#1469]
Minecraft Version: 1.17.1 Purpur # 1427
MySQL: false
BungeeCord: false

When players have the invisibility effect activated, they cannot be PM'd in game nor does a logout message appear in chat.

**Comment by SiuanSong** [comment]
Staff and opped users are able to message them.  


Other players receive this message when attempting to message them.
![Discord_TrvWXjOntS](https://user-images.githubusercontent.com/28202890/141421494-9dfb6d4b-346b-41ff-b278-7155eb30a105.png)

These are the permissions my staff have
```
    - chatcontrol.bypass.reach
    - chatcontrol.command.mail
    - chatcontrol.channel.send.staff
    - chatcontrol.channel.autojoin.staff.read
    - chatcontrol.channel.join.staff.write
    - chatcontrol.channel.join.staff.read
    - chatcontrol.channel.join
    - chatcontrol.autojoin.staff.read
    - chatcontrol.join.staff.write
    - chatcontrol.join.staff.read
    - chatcontrol.join.staff
    - chatcontrol.channel.staff
    - chatcontrol.color.aqua
    - chatcontrol.color.lime
    - chatcontrol.notify.swear
    - chatcontrol.bypass.caps
    - -chatcontrol.color.black
    - chatcontrol.bypass.ignore
    - chatcontrol.bypass.move
    - chatcontrol.bypass.mute
    - chatcontrol.bypass.rules.commands
    - chatcontrol.bypass.time.chat
    - chatcontrol.bypass.time.commands
    - chatcontrol.channel.admin.send
    - chatcontrol.command.adminchat.read
    - chatcontrol.command.adminchat
    - chatcontrol.command.channels.mute
    - chatcontrol.command.channels.spy
    - chatcontrol.command.clear
    - chatcontrol.command.color
    - chatcontrol.command.mute
```



Also totally forgot to upload this...
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7525344/debug.zip)

**Comment by fredagsguf** [comment]
I can confirm this, we are experincing it aswell ^^
Even when users are in spectator mode.

**Comment by kangarko** [comment]
Thank you, will be fixed tonight!
