### ISSUE TITLE
I cannot change any warn messages in chat.txt.

### ISSUE THREAD

**Issue by ElliotPoots** [kangarko/ChatControl#147]
When I change the warn messages in my chat.txt - I get nothing but an error.
I am not making any mistakes - I have even tried using just two simple words, yet still an error. 
Error:
Cannot define an operator when no rule is being created! File: 'chat.txt' Line: '# -------------------------------------------------------------------------------' Previous rule: 'null'

**Comment by kangarko** [comment]
If the previous rule was also "null", ensure you are saving the file in UTF-8 format. You are encouraged to use Notepad++ (on Windows) and save the file in utf-8 (without bom) encoding.
