### ISSUE TITLE
1.16.4 | Players can't see timed messages

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#147]
# **Environment**
### **ChatControl Version**: ChatControlRed-10.1.0

- I was testing the timed messages, and I noticed that there's no permissions for players to see them. You can only see them if you have the permission `chatcontrol.*`

Thanks to Friend_of_God who also tested it, and reported the same issue on his side.

**Comment by Godlycreations** [comment]
That is correct and I am running 1.16.4 BungeeCord/MySql on Java 11

[error.log](https://github.com/kangarko/ChatControl-Red/files/5590108/error.log)

**Comment by kangarko** [comment]
Thank you, I will fix this in the next release.
