### ISSUE TITLE
Cancel sending annoying information to the client log

### ISSUE THREAD

**Issue by SheerYin** [kangarko/ChatControl#1470]
After using the bungee function, CCR will continuously send to the client
Unknown custom packed identifier: plugin:chcred

Makes viewing client log information particularly difficult

Repairing or canceling the sending of the information will make viewing the log more convenient and clear

**Comment by starwarsfreak219** [comment]
I am also getting this same issue. Disabling BungeeCord in the settings.yml does resolve this, but I am hoping this issue will be fixed soon. It not only makes it difficult to read client side logs, but it can also start taking up space for players (as it spams the message around 8 times a second).

**Comment by SheerYin** [comment]
> I am also getting this same issue. Disabling BungeeCord in the settings.yml does resolve this, but I am hoping this issue will be fixed soon. It not only makes it difficult to read client side logs, but it can also start taking up space for players (as it spams the message around 8 times a second).

Turning off the setting of bungee jumping will make it impossible to chat across servers

**Comment by starwarsfreak219** [comment]
> 
> 
> > I am also getting this same issue. Disabling BungeeCord in the settings.yml does resolve this, but I am hoping this issue will be fixed soon. It not only makes it difficult to read client side logs, but it can also start taking up space for players (as it spams the message around 8 times a second).
> 
> Turning off the setting of bungee jumping will make it impossible to chat across servers

Should have responded better. I was stating that for me disabling it does fix it, but it is not a good solution. I would like to be able to send messages across the network for channels. Updating to the most recent version of BungeeControl (He did a reupload yesterday) doesn't resolve it. :/

**Comment by kangarko** [comment]
Impossible right now, the client sends this due to the packet not being recognized.
