### ISSUE TITLE
Still some performances issues

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1472]
Plugin is still taking 1% on my spark (it's a short spark, but on longer spark it's the same)
I got 100 players online, I'm using 1.16.5
MySQL : yes
Bungeecord : false
Plugin version : ChatControl-Red-10.7.9.jar
Debug :
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7532411/debug.zip)

Spark : 
![Screenshot_6998](https://user-images.githubusercontent.com/31826333/141651912-d0d437d2-dc72-4238-b949-57bf92dd9fa4.png)
https://spark.lucko.me/HfocTOlqMB

1% is wayy to much for what it does. I litterally use nothing.

- Also a settings to change delay of permission/group checking would be nice.
I just set 1 permission to my staff so they can bypass rules, except this I don't get any specific permission/group that change things with chatcontrolred.

- I don't use prefix option, I don't use chatcontrolred to manage my chat
- An option to disable vanished player check would also be nice

**Comment by kangarko** [comment]
As far as I can see, we are calling Vault to get the player's information such as group etc., this is not only used in chat but also in variables and other places of the plugin. Then there's a call to LuckPerms which looks like is quite heavy itself. You can try optimize your LuckPerms how you store data there, the database driver, etc.

Your lag does not cause a real lag, it's negligible.
