### ISSUE TITLE
1.17.1: How set up a channel for the Lands plugin?

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1474]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: false

CCR, Lands & dependencies: Latest versions
All permissions are in place.

I'm having trouble setting up a channel for Lands.
I assume how it's supposed to work is that when players chat into the channel, the message is displayed to everyone in the same lands.
Or does the chat only show for the specified land?
It's not really explained.

I already read the wiki.
In the `settings.yml` I set up the channel like:
```
    land:
      Format: landchannel
      Party: lands-land
```

In the landschannel format I have:
```
Parts:
  Player:
    Message: '{player}: '
  Post:
    Message: '{message}'
```

When I send a message there, it can't be seen by anyone except for the sender.

**Comment by kangarko** [comment]
I don't have access to Lands at the moment, @TheIntolerant or @ElBananaa may have a look depending if they have the ability to test this.

**Comment by ghost** [comment]
That would be appreciated.

**Comment by kangarko** [comment]
So sorry that it went quiet. The lands-land party key makes the chat message only go the all players, including sender, within the senders land.

Made you a quick video where I tested this and could not reproduce: [party](https://www.loom.com/share/cd7db64a305245dfa74ac423c880c85f)

**Comment by ghost** [comment]
Oh I see.
I was misunderstanding how the feature was supposed to work.

The reason why the channel wasn't working for me at all is because I was testing it in my spawn world. The Lands plugin provides a way to only enable land claiming in specific worlds. So on my server it is only enabled in the overworld since that is the best world for players to make claims in.
Since land claiming is disabled in my spawn world, the channel didn't work.

The Lands plugin chat works by sending messages to all players who are trusted in the same land, regardless of the area they are standing in (even in worlds where land claiming is disabled.). I originally assumed that's how the CCR channel would work.
Incidentally, would it be possible for you to add an option to make lands channel messages send to the members of the specified land (like private land channels)?

EDIT:
To be more clear, the way that the lands-party key works now is interesting and viable.
I would suggest a key for players who are trusted in the same land claim to chat to each other would be a different key than the current one, so that server owners can use both in different channels.

**Comment by kangarko** [comment]
Great to have that cleared up. Thanks, yes, I can put it to the backburner as suggestion, right now I am extremely busy however, I don't know when I have time to sit down implement this.
