### ISSUE TITLE
Add Velocity Compatibility?

### ISSUE THREAD

**Issue by itsBeaco** [kangarko/ChatControl#1475]
Hey! Let me start off by saying I love this plugin, by far the best out there, I think this suggestion would be great for a lot of servers now that Paper has adopted Velocity.

1. With Paper adopting Velocity, it's only a matter of time until Waterfall stops getting updated and people start to switch to Velocity. I think this would benefit most optimised bungeecord servers

2. We can't use the features offered from the bungeecord aspect of the plugin and therefore makes the bungeecord plugin useless to many of us.

Looking forward to hearing back from you guys!

**Comment by ElBananaa** [comment]
> Hey! Let me start off by saying I love this plugin, by far the best out there, I think this suggestion would be great for a lot of servers now that Paper has adopted Velocity.
> 
> 1. With Paper adopting Velocity, it's only a matter of time until Waterfall stops getting updated and people start to switch to Velocity. I think this would benefit most optimised bungeecord servers
> 2. We can't use the features offered from the bungeecord aspect of the plugin and therefore makes the bungeecord plugin useless to many of us.
> 
> Looking forward to hearing back from you guys!

Hey!
Velocity support is already WIP. There is no date yet, but it'll be announced in the patch note & on discord when it comes out.

**Comment by itsBeaco** [comment]
Awesome! Thank you for getting back to me and letting me know :D

**Comment by ElBananaa** [comment]
> Awesome! Thank you for getting back to me and letting me know :D

Hey,
You're welcome!

To give a bit more informations, as Kangarko said on another issue, he's working with another dev in porting the plugin to Velocity, and the major part is already done, but we're waiting for most known issues to be fixed before releasing the jar file publicly.
Once all the known issues are fixed, VelocityControl will be packed in the main zip file. ^^
(See #1477)
