### ISSUE TITLE
Suggestion: For staff, GUI for canned replies

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1476]
[Wiki canned replies](https://en.wikipedia.org/wiki/Canned_response)
In all support software there is a thing in industry called "canned replies" you get them when you talk to bots for support, for tickets, for auto email replies, its an industry standard.

This would be an amazing tool for staff to create their own Canned response's in-game, like you have /chc color, we would have `/chc canned` that lets them click to send a pre-made reply into chat, but most importantly add a new canned reply, so that they are not reliant on someone editing configs! Everyone that has the staff permission to see these, sees them all, they are shared replies between all staff.
There should be a permission to view them, permission to make a new one, and a permission to send them.

There should also be a shortcut to send them as a command like /chc canned name, so each one should be allowed to set a key word (or a number) when in the GUI creating them.

Once theres a shortcut that can be custom, then we have many options like staff could bind that to an item if they wanted.

Colors and formatting should be allowed.

Would all be stored in the mysql/sqlite database.

**Extend the idea:**

1. You could also extend your /chc announcements with a bunch of pre-made announcements that can be triggered in-game using the same system.
2. You could use the same system to store messages to be shown in /motd using a placeholder with custom formatting
3. You could use this for timed messages too.

**Comment by kangarko** [comment]
Thanks!

For 1., we could just have a canned command. Such as /chc a My Canned Announcement would be executed by typing "/chc canned command %name%". Messages would then run from "/chc canned message %name%". You could of course make custom commands for these lengthy commands such as /c 1 /c 2 /c 3 etc.

2 and 3., I am sorry, I am afraid I do not understand. You mean insert these canned messages into MoTD and timed messages?

**Comment by TomLewis** [comment]
yeah we could have a canned command and show them all in-chat, that's a good middle ground if that's how you prefer to do it.

- So instead of just a static /motd, you could introduce a bulletin board option. So you have your motd file all organised and in it a placeholder say %motd_bb%, and that displays a loop of messages saved to the MOTD BB, which would have the same system as canned replies, except they are public to all players, so messages staff can write for example, /chc motd add &6This is an announcement to be shown in MOTD, Aka saved announcements that can be shown in the MOTD but also via a command. I actually have a custom made script that updates my MOTD for me based on my Forum threads, at present this is the only way I can get staff to post a message to the MOTD. Then they would need a click action, like opening a URL.

- Timed messages, are broadcasts on a timer, at present you have a config file for this `timed.rs`? This ones not so important but the option is there to have this for server owners that would prefer to manage them in-game.

**Comment by kangarko** [comment]
Got it, thank you. Leaving this open for future implementation, at minimum we will add the `/chc canned <message/command> <template>` command. Can't give you an ETA at this point but it will come in a few versions or so.

**Comment by kangarko** [comment]
@[TomLewis](https://github.com/TomLewis) Sorry, being a solo dev is challenging, I am recording a big training program so wont be having time for new features this big for the time being, I pulled it to our long-term roadmap without ETA, thanks for your understanding!

**Comment by TomLewis** [comment]
No problem! AS long as its in the works thats fine!
