### ISSUE TITLE
Velocity Plugin

### ISSUE THREAD

**Issue by AwesomeDude091** [kangarko/ChatControl#1477]
The Idea is that there is a Velocity Bungee Cord Type plugin included in the zip, it would enable usage of ChatControlRed on Velocity Proxies. This addition of Velocity handling would make this plugin usable on a wider variety of network groups. I am mentioning this as Velocity recently merged with Paper (or is still in the process) and it was slightly hinted, that some time in the future Waterfall Support might be dropped. Now I am still using Waterfall, because this (ChatControlRed) is one of the few critical plugins without Velocity (which up until now I was perfectly fine with). However, given the news about a potential drop of the popular Waterfall fork, I think it might be prudent to add Velocity Support.

Thanks for your Time,
AwesomeDude091

**Comment by kangarko** [comment]
Hey! It's pending, I last heard from the developer in charge three weeks ago, I have pinged him. Once it's stable, it will be bundled in the ZIP ;)
