### ISSUE TITLE
1.17.1: Some confusion about the recent update...

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1479]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: false

The recent update notes states: `"Added hex support to chatcontrol.guicolor.{color} - use in the /chc color command and menu."`
When I look into the color menu there are no hex colors. I also don't see any hex colors in the tab complete.
Are hex colors really added to the color menu?

Also in the update notes it states `"All hex colors in permissions **must start with #**."`. In settings.yml it states ```
"1) chatcontrol.color.{color} 
#    - Replace color with color names like "red" or hex like "ccddff" **without #**)."
```
Do permissions actually need the hashtag or not?

**Comment by kangarko** [comment]
I am sorry. The settings.yml header documentation is wrong. Use the hashtag # in your permissions.

Our menu does not support creating custom hex colors yet. You can use the hex color permission to create custom hex colors using /chc color command.
