### ISSUE TITLE
1.16.4 | Return a message instead of breaking the chat when using variables at the wrong place

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#148]
# **Environment**
### **ChatControl Version**: ChatControlRed-10.1.0

- I just noticed the [item] variable completely break the chat when using it with empty hands. I tried to add a check for null/air, but it looks like you can't use `player.getInventory().getItemInMainHand().getType() == Material.AIR` (The material part completely break the plugin). So instead of that, I thought that canceling the message and returning an error message to  player like "You can't use this variable in your situation!" could work, so it will avoid errors like this one.

This is the error when using this code and the [item] variable with an empty hand (https://pastebin.com/e7cFL3LN):
```
    itemDisplayName();
    
    function itemDisplayName() {
        var itemName = player.getInventory().getItemInMainHand().getItemMeta().getDisplayName();

        if (itemName != '') {
            return itemName;
        } else {
            return player.getInventory().getItemInMainHand().getType().name().toLowerCase().replace('_', ' ').replace('_', ' ')
        }
    }
```
And the screenshot of the chat with:
1) Renamed Item
2) Default diamond sword
3) Empty hands
![image](https://user-images.githubusercontent.com/53318613/99887657-588e8480-2c46-11eb-8a04-d286246356ff.png)
_______________________
_______________________
_______________________
This is the error when using this code to check if the item in hand is air (Since null check doesn't change anything) and the [item] variable with an empty hand (https://pastebin.com/JjFkcstC):
```
    itemDisplayName();
    
    function itemDisplayName() {
        var itemName = player.getInventory().getItemInMainHand().getItemMeta().getDisplayName();
        var emptyHand = 'Hand';

        if (player.getInventory().getItemInMainHand().getType() == Material.AIR) {
          return emptyHand;
        }
        if (itemName != '') {
            return itemName;
        } else {
            return player.getInventory().getItemInMainHand().getType().name().toLowerCase().replace('_', ' ').replace('_', ' ')
        }
    }
```
And once again, the screenshot of the chat with:
1) Renamed Item
2) Default diamond sword
3) Empty hands
![image](https://user-images.githubusercontent.com/53318613/99887718-ec605080-2c46-11eb-8d51-f48f83dd8b33.png)

**Comment by kangarko** [comment]
Yeah JavaScript is kinda weird parsing these things, I made a better script:

https://pastebin.com/NPn05PHy

Hopefully by reading it, it will become self-explanatory, if not ask below ;)
