### ISSUE TITLE
Capitalize on links

### ISSUE THREAD

**Issue by NoChanceSD** [kangarko/ChatControl#148]
Any way to disable capitalize on links, for some reasons links like youtube get messed up when you click them in chat and they are capitalized like "Http://.."

**Comment by kangarko** [comment]
ChatControl does have a mechanism that prevents this, unless you have strongly modified the IP-rule. 
I believe it is coming from another plugin.

**Comment by NoChanceSD** [comment]
I tried resetting the rules file and still the same problem, with chatcontrol disabled it worked fine.
For example if i paste https://www.youtube.com/ in chat, i can click it and get in browser https://www.youtube.com/ just like it's supposed to.
However if i paste let's say https://www.youtube.com/watch?v= i get Https://www.youtube.com/watch?v= in chat and when i click it i get in browser http://https//www.youtube.com/watch?v=

**Comment by kangarko** [comment]
Fixed in the next version :)

**Comment by NoChanceSD** [comment]
Cool! Thank you very much,
