### ISSUE TITLE
Ability to format the replaced message when the bot replaces a discord users message

### ISSUE THREAD

**Issue by starwarsfreak219** [kangarko/ChatControl#1480]
If you still believe your feature should be added, you're welcome to suggest it and answer those questions in your description: 

1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
      Formatting the message that the bot replaces could allow for more consistency with the discord chat.

2. What would happen if we won't implement this feature? How's your server being affected?
      Inconsistencies with how the format is usually displayed for players.

3. What is the suggestion?
      When the settings.yml option `Send_Messages_As_Bot` is set to true, it will format messages as `{username}: {message}` when replacing a users message from Discord to Minecraft in the Discord Client. I am unable to change the message to something like `{username} » {message}`, which is how I have the format set up in the config. I am not currently seeing an option to format this, so would it be possible to have the replaced message formatted in a way we want?

Here is a video link to what I am talking about: https://youtu.be/qaUWO52zpmE

Here is my settings.yml: https://paste.helpch.at/axodayenej.php
Here is my chat format: https://paste.helpch.at/osucisexuv.py

**Comment by kangarko** [comment]
Hey!

It is already possible :) Just edit/create the Format_Discord option for your channel in Channels.List in settings.yml. Example:

`Format_Discord: '{player} » {message}'`

**Comment by starwarsfreak219** [comment]
Hey, just looked in my settings.yml and I already have the Format_Discord option set up… :/

What I was asking for was about formatting the message that is replaced by the Discord Bot (where it deletes and re-posts the message on Discord). Is this possible? Discord is still formatting it as {player}: {message}

**Comment by starwarsfreak219** [comment]
Hey @kangarko, I already had that set up in my settings.yml... Is there any way to format the message that is replaced by the discord bot?

**Comment by ElBananaa** [comment]
Reopening the issue.
@kangarko i believe you misunderstood the user's request ^^

**Comment by BearLeonLight** [comment]
For your question, do you want the player to post a message in Discord, after processing it, and then sending it out by the Bot?

**Comment by BearLeonLight** [comment]
This feature is not needed because it has no meaning.
If you need to block certain content and replace it, please use rules to set it up.
One option is to process the message if it comes from Discord.

**Comment by BearLeonLight** [comment]
You can only change the message received by MC, after all Discord has no world, Hover and other content.
Or do you want the embed function?
The message you receive from Discord is through `Format_Discord:'{player} »{message}'` This is basically enough. You may need to describe your purpose and the desired result clearly to help.
Or you can look at DiscordSRV’s ChatChannelHookMessageFormat

**Comment by kangarko** [comment]
Try what Bear has suggested to you (thank you!), otherwise unfortunately I'm too busy right now to implement this.

**Comment by starwarsfreak219** [comment]
What currently happens is that when a player sends a message from Discord to the Minecraft is that the bot replaces the discord message with a duplicate message that the discord user sent. For example, if a discord user sends the message "Hi" in the server-chat channel in discord, that message gets sent to the Minecraft server, but it also gets replaced with a duplicate message from the Discord bot.

Discord User: Hi
[Delete Message]
Discord Bot: {playername}: {message}

In the video I linked I showed the behavior, and how messages are formatted. Messages sent from Discord to Minecraft are formatted, and messages sent from Minecraft to Discord are formatted, but the messages that the discord bot replaces in Discord don't seem to allow any customization for what the format looks like when the message is replaced.

So here is what it currently looks like in terms of formatting:

Minecraft to Discord:
{player_prefix} {player_name} » {message}

Discord to Minecraft:
&9&lDiscord &8┃ &r{player_prefix} {player_name} » {message}

Discord bot replacement:
 {player_name}: {message} <--- This is where I am having the issue, I can't format this.

Honestly not sure how else to explain what I am asking... I just want to format the message that the Discord bot sends out when it replaces the Discord users message with a duplicate message.

@kangarko

**Comment by starwarsfreak219** [comment]
Here is a link to the video again: https://www.youtube.com/watch?v=qaUWO52zpmE

I highlight in Discord at the end of the video what I want to be able to Format.

**Comment by kangarko** [comment]
That is intended. You can set Integration.Discord.Send_Messages_As_Bot to false to remove it, understanding the limits explained in the comments of settings.yml above this key.

**Comment by starwarsfreak219** [comment]
I don't want to remove the bot replacing the message, I am okay with that. What I want to do is format how the message looks when the bot replaces it. It currently shows {name}: {message}, but I would like to have it format as {name} » {message} so it is more consistent on how I have messages set up on Discord for the bot. 

What you originally suggested doing was setting `Format_Discord: '{player} » {message}'`, while this does work for formatting messages from Minecraft to Discord, it doesn't have the adverse effect of formatting the Discord message that is replaced by the discord bot.

**Comment by kangarko** [comment]
Sorry, I finally understand! Fixed. The Format_Discord will now work both ways: https://i.imgur.com/M4FFW6O.png

**Comment by starwarsfreak219** [comment]
Thank you. ☺
