### ISSUE TITLE
1.17.1 PaperMC: Error on startup, brand new install.

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl#1483]
```
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true
```

Brand new install of CCR on a brand new server, all configured, all dependencies installed.
Getting the following error on startup:
https://pastebin.com/sn4hwFpQ

Not sure if it's MySQL related, it should not be. Loading settings class seems to be the issue, however, I'm not sure what I have configured incorrectly to cause this and I can't turn on debugging since the plugin can't start.

Thanks Matej.

**Comment by ElBananaa** [comment]
Hey!
Could you pleade update to the latest version and try again?
If it doesn't work, please provide us your debug file.

**Comment by LeehamElectronics** [comment]
> Hey!
> 
> Could you pleade update to the latest version and try again?
> 
> If it doesn't work, please provide us your debug file.

Thanks for the reply B, I am using the latest version already. I will send a debug file later today.

**Comment by LeehamElectronics** [comment]
Issue was unrelated to CCR, apologies.
