### ISSUE TITLE
1.17.1: Prevent chat messages printing to console?

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1485]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: false

Just wondering if there's a way to prevent chat messages from printing to the console?

**Comment by kangarko** [comment]
Hey!

You can set the Format_Console option to "none" in Channels.List in settings.yml like this:

![a](https://i.imgur.com/KAJXAQd.png)

Sincerely,
Matej

**Comment by mav2020** [comment]
This doesn't work for me.
Have this on Survival Server
`    test:
      Format: chat-test
      Format_Console: none`
but still shows in console on the Survival/non-test server. Don't know now to show the format on here, but it is written in YAML like your example.

**Comment by kangarko** [comment]
Show me your /chc debug ZIP please. You can drag it here into your reply.

**Comment by mav2020** [comment]
> Show me your /chc debug ZIP please. You can drag it here into your reply.

Thanks. Is there a way to get it to you without making it public on here?
Edit: I think I figured it out, the Bungee: true wasn't there and it was coming from the other server. But if I have issues, my question above stands. Thanks for the reply btw.

**Comment by kangarko** [comment]
Just adding that, if you want to send your debug in private, you can use ufile.io and email the link to matej(at)mineacademy.org
