### ISSUE TITLE
1.16.5: Emoji message from discord encoding problem

### ISSUE THREAD

**Issue by TimmyHung** [kangarko/ChatControl#1486]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

So if I send a emoji from discord, for example :smile: emoij without chatcontrol-red it used to shown `:smile:` in game chat, but now it'll show as a weird square box ![image](https://user-images.githubusercontent.com/58425985/142610642-d9ffed2d-b889-49c7-b22d-350a3d67d634.png)

Is there's a way to fix this problem, so I can use rules feature to replace the text with other emoji text from my own custom resource pack

**Comment by TheIntolerant** [comment]
Hey, in settings try setting this ``Integration.Discord.Remove_Emojis`` to ``false``

**Comment by TimmyHung** [comment]
Uh it already set to false so this one might be a bug

**Comment by TheIntolerant** [comment]
Weird, probably need to wait for the dev to check this issue.

**Comment by kangarko** [comment]
Minecraft font does not support all emojis, unfortunately it is unsupported with either your hardware (system encoding, etc.) or software.

**Comment by TimmyHung** [comment]
@kangarko No matter supported or not it not related to the problem I mentioned above. Discord emoji(😄) show as [] in minecraft chat instead of the `:smile:`Although I already set Integration.Discord.Remove_Emojis to false.

(I'm not quite sure if you'll see this reply after issue closed, so if I don't get any reply in future I'll probably open another new one)

**Comment by TheIntolerant** [comment]
We still get notifications regardless if the issue is closed on GitHub, so you should get a reply :p

**Comment by kangarko** [comment]
I am not sure how we would translate the unicode back into a text ":smile:" if that is what you asked for, anyways, I am extremely busy these weeks, cannot be having a look until December. Thanks for your understanding.

**Comment by TimmyHung** [comment]
Nonono I mean without ChatControlRed
If I send an emoji 😄 in Discord, I'll get message `:smile:` display on Minecraft chat.
.
with ChatControlRed installed If I send an emoji 😄 in Discord, I'll get message `[]` display on Minecraft chat.
(I already set Integration.Discord.Remove_Emojis to false)

There might have some bug in the Remove_Emoji feature.

**Comment by kangarko** [comment]
I see thank you! We do have some emojis in our rules file chat.rs: https://i.imgur.com/mMwCaHu.png

Can you try disabling our rules system to see if it fixes the issue? In this case just search for that smiley and remove it.

**Comment by TimmyHung** [comment]
I believe in yaml file mark line with # will not make plugin load the text since it was a comment.
However I've test a while and it still didn't fix the issue (Already restart entire server)
Not only 😄 but every single emojis.
![image](https://user-images.githubusercontent.com/58425985/143594552-00bc987e-3803-4c92-b04d-6cbb10605f7f.png)
![image](https://user-images.githubusercontent.com/58425985/143594621-84fc229b-2fab-4cce-8df1-00d2c1d22675.png)

And here's what it used to be (without chatcontrolRed installed)
![image](https://user-images.githubusercontent.com/58425985/143595125-eacecc04-4133-4b8f-b007-5e7d307114bf.png)
![image](https://user-images.githubusercontent.com/58425985/143595145-55abe9cd-c619-40b5-b011-9d91b8dcb28c.png)

If this issued can be fix then I can use chat.rs to to replace maybe `:pig:` to text emoji ₍ᐢ. ⚇ .ᐢ₎

**Comment by TimmyHung** [comment]
And here's what it used to be (without chatcontrolRed installed)
![image](https://user-images.githubusercontent.com/58425985/143595125-eacecc04-4133-4b8f-b007-5e7d307114bf.png)
![image](https://user-images.githubusercontent.com/58425985/143595145-55abe9cd-c619-40b5-b011-9d91b8dcb28c.png)

**Comment by kangarko** [comment]
Just heard back from DiscordSRV's developer - Minecraft font doesn't support these emojis. However, you can try using this plugin: https://www.spigotmc.org/resources/emojichat.50955/

I will look forward into porting some of its features to ChatControl when I have time, right now my plate is full.

**Comment by TimmyHung** [comment]
It doesn't matter if Minecraft font support these emojis or not. 
All I want is to make ChatControl display messages(emoji text) from discord correctly
Here's what I got now
![image](https://user-images.githubusercontent.com/58425985/144467274-5f1b04ea-1018-48dd-a338-71a2591cb039.png)
And here's what it should be
![image](https://user-images.githubusercontent.com/58425985/144467349-ff236176-2975-4e70-9afb-3753cd949f39.png)

I'm not quite sure if you can understand my problems, since I have bad English to describe things, apologize in advance.

**Comment by kangarko** [comment]
Where is the second picture coming from? Is this using vanilla DiscordSRV?

**Comment by TimmyHung** [comment]
Yes it from vanilla DiscordSRV without ChatControlRed installed

**Comment by kangarko** [comment]
Sorry I cannot help you, cannot reproduce this, I am also getting [] on 1.18: https://i.imgur.com/Z1IuOW8.png

**Comment by ElBananaa** [comment]
> Sorry I cannot help you, cannot reproduce this, I am also getting [] on 1.18: https://i.imgur.com/Z1IuOW8.png

I did run some tests on my end, and I was able to reproduce the same results than the user, with and without chatcontrol.
Here's how the smiley looks like without chatcontrol: 
![image](https://user-images.githubusercontent.com/53318613/144647270-c652b91f-4f16-4deb-b960-67a1534f52c0.png)
And they all get replaced by the weird squares as soon as I install chatcontrol ^^

**Comment by kangarko** [comment]
No idea why I am not getting this. Banana please ask on their Discord how to configure DiscordSRV so emojis are shown like this.

**Comment by ElBananaa** [comment]
That's the full default config folder. (fresh install)
I only provided my bot key, and configured DiscordSRV's `Channels:` part like this: `Channels: {"global": "896859522684047401"}`
(So I basically only changed the discord channel id to one of my test channels).

However, you may also want to take a look at both these settings. In my case, I didn't change them so I don't know what it'll do tho.
```yaml
DiscordChatChannelEmojiBehavior: "name"
DiscordChatChannelEmoteBehavior: "name"
```

EDIT: Setting both values to `"Show"` seems to cause the issue of squared emojis, however, I can confirm that during my testings with chatcontrol-red installed, both values were set to `"name"` which works perfectly fine without chc.

**Comment by TimmyHung** [comment]
So is there any way to fix this issue?It been 5 months, today I use newest CHC version test a while include banana said change it to "show" or "name" but still didn't worked  :/ ("name" is the default setting from DiscordSRV and all the report I reported above are remain default settings,except bot token, channels.)

**Comment by TheIntolerant** [comment]
On the off chance @kangarko doesn't reply, I'll reopen this issue so he definitely sees the messages as there's a chance he just missed the notification for the previous messages in this issue. :P

**Comment by kangarko** [comment]
I am here! Having a look in 24 hours

**Comment by kangarko** [comment]
Can you quickly provide your /chc debug file as you have it right now please?

**Comment by TimmyHung** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8616301/debug.zip)

I also noticed here is a setting called "Remove_Emojis" I should get emoji text replace by [] only when I set it to **true**.
But for some reason it returns an opposite result!
![image](https://user-images.githubusercontent.com/58425985/166584404-bb67b17a-7008-4e6d-9e85-83adf34cb7ee.png)

**Comment by kangarko** [comment]
@TimmyHung sorry for the delay, the next release will remove all emojis completely if the Remove_Emojis option is enabled, otherwise nothing is done to the messages and you may see [] or other odd symbols in game

**Comment by TimmyHung** [comment]
Thanks for the reply, but if nothing is done to the messages come from Discord,for example 🐷,I should see it display as `:pig:` in game right? wdym [] or other odd symbols?

Some picture from the comment above⬇️
![B523BE3A-38F0-446D-BAED-231FA9991A08](https://user-images.githubusercontent.com/58425985/167812380-049c93d1-c2fa-4fc3-b9e7-8fb7d2ca2575.jpeg)

**Comment by kangarko** [comment]
No because your Minecraft receives raw unicode and we don't know how to translate it into :emoji_name:, it will display [] because it can't render it

**Comment by kangarko** [comment]
Maybe discordsrv has its own method for translating unicode into :emoji_name: unfortunately I am super busy with a training program right now to code it over to chatcontrol
