### ISSUE TITLE
1.8.8 : Could  this be improved

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl#1487]
Minecraft Version: 1.8.9
MySQL: false
BungeeCord: false

Not sure if this is an lag issue or bad configuration, but everytime i send the first message it will show this in the console and seems it takes extra time to show in-game compared to other messages like if it was lagging but in a matter of milliseconds.
![image](https://user-images.githubusercontent.com/34607217/142712300-0cb9cfa5-a1b3-4ed6-9784-9ce5e8deddc9.png)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.8.9 MySQL: false BungeeCord: false
> 
> Not sure if this is an lag issue or bad configuration, but everytime i send the first message it will show this in the console and seems it takes extra time to show in-game compared to other messages like if it was lagging but in a matter of milliseconds. ![image](https://user-images.githubusercontent.com/34607217/142712300-0cb9cfa5-a1b3-4ed6-9784-9ce5e8deddc9.png)

Hey,
Please try to the async chat feature in the settings file, as it should improve performances:
- Set `Async:` to `true` (near line 80 in the default file)

**Comment by kangarko** [comment]
Thanks, we will hide it. First message takes some time due to internal initialization, sending more messages wont cause this,.
