### ISSUE TITLE
1.17.1: Unexpected channel switching behavior

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#1488]
Minecraft 1.17.1 (CHC 10.8.0)
MySQL: false
BungeeCord: false

----

I have two rules within `command.rs` that, when run, are intended to switch the active "write" channel for a player, while making one other channel read only, or inaccessible.

```
match ^\/softmute ([a-zA-Z0-9_]{3,16})
then warn &cSoft-muting $1
then console channel join standard read $1|channel join softmute write $1
then deny

match ^\/unsoftmute ([a-zA-Z0-9_]{3,16})
then warn &aUn-soft-muting $1
then console channel leave softmute $1|channel join standard write $1
then deny
```

Expected behavior:
/softmute - Makes the player write into the "softmute" channel, while still allowing them to read the standard channel.
/unsoftmute - Makes the player leave the "softmute" channel, allowing them to write directly into the standard channel.

Observed behavior:
/softmute Works as intended*
/unsoftmute - Moves the player to the standard channel for writing, but still allows the player to read the softmute channel.

I would expect this has something to do with Channels.Join_Read_Old[true/false] setting in `settings.yml`, however toggling this setting does not give the desired result. Either the console reports that the user has left channels over limit, or shows that the player has left the softmute channel, despite the fact they're still reading the channel.

*I've tried modifying the /unsoftmute command to run the `channel leave softmute $1` command twice to counter-act the previous issue. However, in doing so, somehow the result of the first /softmute command changes so that the player is simply set into "read" mode for the standard channel, and isn't allowed to write anywhere.

Example: https://youtu.be/RwJ3XtEub5M

So far, the only "solution" has been to run the command *twice*, as done in the video. This is not an ideal solution, though. I'd like to run the command only once and the player be moved as expected. If I run the commands from commands.rs manually as a player, it seems to work. My rules could be messed up, but I've been struggling on this for days.

**Comment by kangarko** [comment]
Thanks and sorry to hear about this. When I have time I will implement a /channel set command which won't check for these limits and bug out. Keep an eye on changelogs ;)
