### ISSUE TITLE
1.16.3 | <center> thing works wrongly with Russian letters

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#149]
English:
![image](https://user-images.githubusercontent.com/62369973/99899573-7ba74b80-2cbb-11eb-9c7c-50d795543b06.png)

Russian:
![image](https://user-images.githubusercontent.com/62369973/99899582-8e218500-2cbb-11eb-962a-ca878473f6d7.png)

**Comment by kangarko** [comment]
Hi there!

Unfortunately, we're using a library that has English letters hardcoded: https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/ChatUtil.java#L451

With the current system it'll not properly center anything except those letter. I apologies and will be looking into finding an alternative but I don't have enough skills in this area.
