### ISSUE TITLE
1.17.1: ItemsAdder Emoji Bug

### ISSUE THREAD

**Issue by notdeliable** [kangarko/ChatControl#1490]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Hi. I'm trying to use ItemsAdder emojis on chat. But it's a little bit different.
![image](https://user-images.githubusercontent.com/72627840/142765143-10bec314-a1ac-4f41-93d6-b2f2d3e94860.png)
I'm getting the emoji but I'm getting another things. How can I fix it?

![image](https://user-images.githubusercontent.com/72627840/142765172-9d5606a9-6cfd-4e6a-a699-fe58647c561d.png)

**Comment by TheIntolerant** [comment]
would you be able to post ur chat.rs file below? and do you have the channels feature enabled?

**Comment by notdeliable** [comment]
Hi, /plugins/ChatControlRed/rules/chat.rs file: [chatrsfile.txt](https://github.com/kangarko/ChatControl-Red/files/7576700/chatrsfile.txt) It's .rs file, but GitHub not allows .rs extension, so I changed the extension to .txt.

Channels.Enabled is false.
 @TheIntolerant

**Comment by ElBananaa** [comment]
> Hi, /plugins/ChatControlRed/rules/chat.rs file: [chatrsfile.txt](https://github.com/kangarko/ChatControl-Red/files/7576700/chatrsfile.txt) It's .rs file, but GitHub not allows .rs extension, so I changed the extension to .txt.
> 
> Channels.Enabled is false. @TheIntolerant

Hey!
In order for the plugin to work properly, you must enable our channel feature.

**Comment by notdeliable** [comment]
@ElBananaa how can I make players if they join and it's their first join, they'll automatically join to x channel. But if they join and it's their not first join, they'll automatically join to channel which they joined before leaving the game.

**Comment by TheIntolerant** [comment]
For info regarding channels please view https://github.com/kangarko/ChatControl-Red/wiki/Channels

**Comment by ElBananaa** [comment]
As @TheIntolerant please refer to our wiki.
Closing this issue, feel free to comment down below if you need anything else related to it.
