### ISSUE TITLE
1.17.1: How to match sign text only once?

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#1491]
I want to log sign text to a file, but I cannot figure out how to match only once.  Instead, it matches 5 times, once for the full, original sign text (all 4 lines combined) then once for each line.

My rule in sign.ts:

match \S
then write logs/sign.log [SIGN] {player}: {server_name}/{world} @ {x} {y} {z} [TEXT] {original_message}

The log:

[21.11.2021 07:48:16] [SIGN] c0wg0d: lobby/lobby @ -114 63 238 [TEXT] a sign with
[21.11.2021 07:48:16] [SIGN] c0wg0d: lobby/lobby @ -114 63 238 [TEXT] four lines
[21.11.2021 07:48:16] [SIGN] c0wg0d: lobby/lobby @ -114 63 238 [TEXT] this
[21.11.2021 07:48:16] [SIGN] c0wg0d: lobby/lobby @ -114 63 238 [TEXT] like
[21.11.2021 07:48:16] [SIGN] c0wg0d: lobby/lobby @ -114 63 238 [TEXT] a sign withfour lineslikethis

Any help on how to do this would be appeciated.

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by TheIntolerant** [comment]
The only placeholder I know of for signs is ``{sign_lines}`` however I believe this will print each line on the sign as a new line.

@kangarko do you think it would be possible to make something like {sign_message} that works like {sign_lines} but instead sends it as a whole message? For example a sign with
```
hello
friend


```
would print as "hello friend", so adding a space after the first line but as the last two lines are null then no space is added to the end of the line? Just an idea as I have seen a bunch of people asks the same question.

**Comment by kangarko** [comment]
I have added {sign_lines} variable as per TheIntolerant suggestion to the next version! This should log just once:

```
match \S
then write logs/sign.log [SIGN] {player}: {server_name}/{world} @ {x} {y} {z} [TEXT] {sign_lines}
```
