### ISSUE TITLE
Add require sender server <server name> to messages

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#1492]
It would be beneficial if we could get a new require criteria to match a server name.  This would allow you to have a more generic config that can be used across multiple servers via symlinking but still target specific servers for specific actions.

For example, you could have a death.rs file that would only send death messages to Discord from your pvp server.

```
group entity-attack-pvp-generic
require cause ENTITY_ATTACK
require killer PLAYER
require sender server pvp
message:
- &c{player} &7was outmatched by &a{killer}
then discord <discord_channel_id> :skull: {message}

group default
message:
- {original_message}
```

You can already get the world a player is in, so I hope getting the server would not be difficult to add.

**Comment by kangarko** [comment]
Thanks, pulled to roadmap. I am extremely busy right now with our learning platform, having to prioritize other things but it's planned once we have time.
