### ISSUE TITLE
1.17.1: Player cannot write in channel after getting nickname

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#1493]
All players have automatic perms to write in the channel when joining.  If an admin gives a player a nickname, the player can no longer send messages to the channel.

Admin perms:
```
chatcontrol.channel.autojoin.test1.write
chatcontrol.channel.join.test1.write
chatcontrol.command.tag
chatcontrol.command.tag.admin
chatcontrol.command.tag.nick
```

Regular player perms:
```
chatcontrol.channel.autojoin.test1.write
chatcontrol.channel.join.test1.write
```

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by TheIntolerant** [comment]
> If an admin gives a player a nickname, the player can no longer send messages to the channel.

Hey, could you please explain what do you mean by this? What types of messages are they getting when they try to chat?

**Comment by c0wg0d** [comment]
The scenario is:

1. The regular player joins the server.
2. The regular player can type a message, which will correctly write to the test1 channel as expected.
3. An admin does `/chc tag <player> nick <nick>`
4. The regular player can no longer write to the test1 channel, and they get an error "You have no channel to write into. Use '/channel join' to join one."
5. The regular player can quit the server and reconnect, and then they  can type normally, with the nickname applied.

It seems like when the player gets nicknamed, they are kicked out of all channels and are not properly rejoined automatically like they should be.

**Comment by kangarko** [comment]
Investigating, will get back to you in 1-2 days depending on my schedule.

**Comment by kangarko** [comment]
Cannot reproduce so far, are you sure there are no extra commands executed? Please check the console if there is just a single tag command being run for players. Going to reproduce more tomorrow.

**Comment by kangarko** [comment]
Possibly a duplicate, continuing the discussion on https://github.com/kangarko/ChatControl-Red/issues/1292
