### ISSUE TITLE
1.17.1: Newcomer permissions last longer than threshold

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#1494]
Not sure if this is a bug or if it's intended, I have a threshold of 6 minutes with a permission that removes an rtp cooldown for newcomers. Waited about a half hour and my alt was still able to bypass the cooldown. However, when my alt re-joined after the threshold the permission was successfully taken away. Re-joining before the threshold still maintained the permission. So all of that works, it's just that the permission seems to last indefinitely until the player decides to log out.

Minecraft Version: 1.1711
MySQL: false
BungeeCord: false
In case it's needed:  [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7577007/debug.zip)

**Comment by kangarko** [comment]
I am sorry, there is a known issue in regards to the permissions threshold. We will investigate this but right now my plate is extremely full. I advise you use a standalone permissions plugin for this.
