### ISSUE TITLE
1.17.1: Placeholder Translation

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl#1495]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Are channel mode placeholders translatable? For example, I want to translate {0}, {1}, and {2} in "Switch_Success: Switched mode for channel &o{0} &7from {1} to {2}."

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1 MySQL: true BungeeCord: true
> 
> Are channel mode placeholders translatable? For example, I want to translate {0}, {1}, and {2} in "Switch_Success: Switched mode for channel &o{0} &7from {1} to {2}."

Hey,
The `{0}` variable returns the channel name. The `{1}` and `{2}` variables return either `read` or `write`.
Unfortunately, there's no way to translate these variables right now.

**Comment by coco0325** [comment]
Can these variables be translatable in the future version?

**Comment by ElBananaa** [comment]
> 

I don't know.
I believe this question has already been asked and it wasn't in Kangarko's plans.
Anyways, please wait for Kangarko to get back to you about this.

**Comment by kangarko** [comment]
You could use our JavaScript feature to get the result and match it with the English version, then print your localized one:

`mode === "read" ? "myReadLabel" : "differentMode"`

But I am afraid I cannot help you creating JS based translations. We have a video on this in the wiki though. It can get lengthy, so you can use the following syntax instead:

```
Locale_Key: |-
  javascript line one
  javascript line two
  javascript line three
```
