### ISSUE TITLE
1.17.1: Color codes in the global chat

### ISSUE THREAD

**Issue by Woody-Man** [kangarko/ChatControl#1496]
Color codes don't work in global chat(
I'm introducing "!&o hello!" but in the chat, the message is displayed without a color code

**Comment by TheIntolerant** [comment]
Do you have ``chat`` listed in ``Colors.Apply_On`` via settings.yml and the correct permissions set?

Such as:
``chatcontrol.color.{color}``
``chatcontrol.color.italic`` etc?

**Comment by kangarko** [comment]
Please see the last changelog, there were perm changes in the last release. Then check your perm plugin if you assigned those names to your player :)
