### ISSUE TITLE
1.17.1: [item] Not Displayed Correctly On Discord 

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl#1498]
The variable [item] won't be displayed correctly on discord channels.

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey,
I believe this is an intended behaviour. We do not replace variables sent to discord yet.
As said on #1439 Kangarko will think about implementing this feature later.
