### ISSUE TITLE
Support for commands that act like chat

### ISSUE THREAD

**Issue by logicalPolaris** [kangarko/ChatControl#15]
I want to be able to specify the plugin to correct grammar and chat for a certain command.

On my server, I use /ooc (message) to broadcast a message out of character, but with this plugin it doesn't fix caps or grammar.

If this is already implemented, sorry I made this thread.

**Comment by kangarko** [comment]
Such feature is currently not present. I've added it as a suggestion but I have other, more important functions to add so it won't come any soon.

**Comment by logicalPolaris** [comment]
Is there a time that you could predict as of now? I need it to at least work with caps as of now :(

**Comment by kangarko** [comment]
Hey, sorry for the delay, I am very busy lately but I had some time and I am almost done!
Just testing it, and, if all goes well it should be out tonight in the premium version.

**Comment by kangarko** [comment]
Edit: Sorry, it needs some more testing, and the spigot has been down for some hours. Hope it will be up tomorrow.

**Comment by logicalPolaris** [comment]
Thanks for getting back to me. 

I see that you said it will be coming to the premium version.
Is there a way for me to test if the caps prevention works correctly before I pay?

I'll only be using the plugin for the command caps (and maybe grammar if you also included that).

**Comment by kangarko** [comment]
You can try out the free version to test out the anti-caps, but the premium has received a significant improvements.

I have added support to handle certain commands as chat in v6.5.6

**Comment by logicalPolaris** [comment]
Sorry for asking so many questions!

What I was referring to was the functionality of limiting caps on certain commands.
I want to try it out on a command to make sure it works the way I want it to. 
If it doesn't work the way I expect it to, I will have spent 5 EU on a plugin I won't be using.

My question was whether I could test out the command capitalization function before I buy it?

**Comment by kangarko** [comment]
It will downcase the characters in chat, not in the format:

[LOBBY] Donator!CONMAN102: hello
