### ISSUE TITLE
MySQL table creation error

### ISSUE THREAD

**Issue by MrEMan** [kangarko/ChatControl#15]
I'm having an issue creating the tables in the db. ChatControl_Log is created but ChatControl_Mail and ChatControl error.

Error on updating MySQL with: CREATE TABLE IF NOT EXISTS ChatControl (UUID varchar(1024), Name text, Nick text, Data text, LastModified bigint, PRIMARY KEY (UUID));
MySQLSyntaxErrorException Specified key was too long; max key length is 3072 bytes

Error on updating MySQL with: CREATE TABLE IF NOT EXISTS ChatControl_Mail (UUID varchar(1024), Data text, PRIMARY KEY (UUID));
MySQLSyntaxErrorException Specified key was too long; max key length is 3072 bytes

I may have done something wrong when creating the DB

Regards

**Comment by kangarko** [comment]
Thanks, will reduce the varchar from 1024 to 255, wait for next build and comment below if you will still have this issue
