### ISSUE TITLE
Some placeholders are not wotking in Hover part

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#150]
![image](https://user-images.githubusercontent.com/62369973/99899946-e8234a00-2cbd-11eb-8c23-89c62a87055a.png)

**Comment by kangarko** [comment]
Hmm this looks like an incompatibility. I assume you are using PlaceholderAPI, double check the placeholder name, and that there are no errors, but unfortunately we cannot alter how PAPI expansions work.
