### ISSUE TITLE
Support Velocity Proxy as they have merged with Paper Organisation and waterfall will go into legacy.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1500]
I cant find the original post, but the velocity proxy is now under the paper organisation, but you can see from this commit they moved 6 days ago to Paper.
https://github.com/PaperMC/Velocity/commit/2586210ca67f2510eb4f91bf7567643f8a26ee7b

This is because paper are phasing out waterfall and replacing it with velocity. can you please make sure you support velocity asap for the proxy integration.

https://docs.velocitypowered.com/en/latest/developers/command-api.html

I briefly scanned your issue tickets for velocity and it seems you have a third party making a velocity plugin or something? This just needs to be baked in and not run by a third party as this is the future of proxy for Minecraft hosting and not just an alternative proxy to waterfall, do make sure to keep waterfall/bungee support too so its compatible for all parties.

**Comment by kangarko** [comment]
Tagging the responsible person @relavis (assuming you have the same github username as on discord). You can comment below even if it is closed.

We have a working build, with some bugs that, once patched, we can just ship it. Unfortunately my plate is full to learn another programming API right now. I will be monitoring the situation and ship the build once ready.

**Comment by UserDerezzed** [comment]
> This is because paper are phasing out waterfall and replacing it with velocity. can you please make sure you support velocity asap for the proxy integration.

This is untrue, kashike was very clear that Waterfall is not being discontinued:
> we have no current plans to discontinue the Waterfall proxy software in the near future
