### ISSUE TITLE
1.17.1: Max Length of Messages

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl#1501]
Is it possible to limit the max length of messages players can send? 

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Hey! Yes, theoretically, you could just create a chat rule for that and match messages longer than X characters, then block them. You can use google to search for various regexes such as this query:

https://stackoverflow.com/questions/4735164/trying-to-regex-for-strings-longer-than-22-characters


Good luck!
