### ISSUE TITLE
1.17.1 Cant hide help msgs

### ISSUE THREAD

**Issue by MuriloWentz** [kangarko/ChatControl#1503]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Im trying to hide the help msgs that appear after you fail a command, and im not being able to do so..

my main focus is to hide /msg and /ignore, i've tried it like 3/4 months ago but i couldnt, then i went busy with work, now im trying again and i still cant. i tried deleting the messages in localization but didnt work, it regenerates it self.

![Sem título](https://user-images.githubusercontent.com/50129175/143512102-149cee91-26a8-43b8-b686-0d30f4cda38c.png)

**Comment by MuriloWentz** [comment]
i assume that these are the messages i should hide, but i cant, if thats on purpose, could you add an option to hide these messages some other way? like a true/false thing
![Sem título](https://user-images.githubusercontent.com/50129175/143512530-9559ab74-3d14-48a4-85d9-1aec24a8d44c.png)

**Comment by TheIntolerant** [comment]
The most effective way of hiding such messages would be creating a rule inside your ``command.rs`` file.

Examples shown here:
```
# Hides the /msg message sent if command failed
match ^\/(tell|w|m|t|pm|message|msg|whisper|reply|r)$
dont verbose
then deny

# Hides the /ignore message sent if command failed
match ^\/(ignore|ig)$
dont verbose
then deny
```
Just make sure you check what command aliases you have set in the settings.yml file for these commands and edit the above where necessary.

**Comment by MuriloWentz** [comment]
thanks bro!
