### ISSUE TITLE
1.17.1: Single Channel and Auto-Join for First Join

### ISSUE THREAD

**Issue by notdeliable** [kangarko/ChatControl#1506]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Hi. How can I make players if they join and it's their first join, they'll automatically join to x channel. And there will be just one channel. Let me explain it:

[ChatControl RED] kangarko joined and this is first join of kangarko, say welcome to him!
[ChatControl RED] Welcome kangarko! [does some magic stuff] Now you're in x channel.
[kangarko] /channel list
[ChatControl RED] There is no other channel that you can join.
[kangarko] /channel join
[ChatControl RED] As I said there is no other channel so you can't join another channel. I already put you on channel x automatically.

Can I do that?

**Comment by TheIntolerant** [comment]
Have a read of https://github.com/kangarko/ChatControl-Red/wiki/Channels#auto-join for information on how to do this

**Comment by notdeliable** [comment]
> Have a read of https://github.com/kangarko/ChatControl-Red/wiki/Channels#auto-join for information on how to do this

I watched it and I didn't understand this video. As I said on Discord, my English is not good so I can't understand the video.

**Comment by TheIntolerant** [comment]
So basically all you need to do is give people the following permissions
``chatcontrol.channel.autojoin.{channel}.write``
``chatcontrol.channel.join.{channel}.write``

replace ``{channel}`` with the name of your channel. 

Also, some settings you may want to check in your settings.yml file include ``channel.Ignore_Autojoin_If_Left``, you may want to set this to false.
```
  # If you gave player permissions to automatically join a channel on join, and he decided to
  # leave it, should we remember his option and not join him to channel next time he logs in?
  Ignore_Autojoin_If_Left: false
  ```
 
---

if you have extra channles you may want to stop them from leaving this channel?
To do this, negate this permission node ``chatcontrol.channel.leave.{channel}``
example
``/lp group <group> permission set chatcontrol.channel.leave.{channel} false``
``/pex group <group> add -chatcontrol.channel.leave.{channel}``

**Comment by kangarko** [comment]
Thanks to TheIntolerant for helping out, let us know below if you have any more questions.
