### ISSUE TITLE
changable coloured text sugestion 

### ISSUE THREAD

**Issue by VagabondKitten** [kangarko/ChatControl#1507]
Hello im on the the Mod's for the MC.notnot.Pro server. i wish to request a feture. as someone who spends alot of time looking at chat i would like toi beable to distingish the different chattexts with different colours. for example. if Chatspy would apear in redtext for example if i set it to red. so text colour essentelly setable.

**Comment by kangarko** [comment]
Hey, you can already achieve this by yourself. Simply clone your formats/chat.yml file for each channel and assign a different color to it. Spend some time reading this file, it should not be that hard :)
