### ISSUE TITLE
1.16.4 | Different players receive different death message

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#151]
If you have multiple death messages defined in death.rs, it will not send the same message to all players online.  It appears to pick a random one for each player, so there are cases where the same death will show up differently for certain players.

Here's an example you can use for testing:

```
group entity-attack-by-zombie
require cause ENTITY_ATTACK
require killer ZOMBIE
message:
- &e{player} &7found out the hard way that zombies don't like hugs
- &e{player} &7discovered that zombie couldn't be cured at all
- &e{player} &7looked pretty tasty to that zombie
```

**Comment by kangarko** [comment]
Thanks, will be fixed.
