### ISSUE TITLE
1.16.5: How to change the (wirte) (read) messages

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1510]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

How to change the (write) (read) when channels pop out.

**Comment by kangarko** [comment]
In https://github.com/kangarko/ChatControl-Red/wiki/Localization, please see this thank you!

**Comment by ElBananaa** [comment]
> In https://github.com/kangarko/ChatControl-Red/wiki/Localization, please see this thank you!

@kangarko I think they meant how to translate both `read` and `write` words. And that's not a feature rn afaik ^^

**Comment by kangarko** [comment]
Oh I see, nope, this is hardcoded otherwise it would break the system. Thanks!
