### ISSUE TITLE
1.17.1: Chat breaks for everyone when I am online

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1511]
This is the error: https://pastebin.com/nb311s6a

Occurs when I use Sikatsu issued server command: /chc color #f3305b

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by Sikatsu** [comment]
In case this is related, bungeered errors: https://pastebin.com/gNASxuPs

**Comment by Sikatsu** [comment]
Even more errors.. https://pastebin.com/zFJ8nzCs

**Comment by kangarko** [comment]
Please send me your /chc debug, appears you have a syntax error somewhere or our compiler is failing.

**Comment by Sikatsu** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7636250/debug.zip)
@kangarko

**Comment by Sikatsu** [comment]
I am not sure if the errors below it are related, or of a different cause. But I have quite some errors related to ChatControl lately.

**Comment by kangarko** [comment]
Regarding the second error, please ZIP me your BungeeControlRed folder also since it's coming from there, sorry I did not ask earlier. I have made a workaround for the first error and should have patched the third one, looked like a concurrency issue.

**Comment by kangarko** [comment]
I believe this should also solve your database issues.

**Comment by Sikatsu** [comment]
[archive-2021-12-02T171952Z.tar.gz](https://github.com/kangarko/ChatControl-Red/files/7643896/archive-2021-12-02T171952Z.tar.gz)
No worries, here is the BungeeControlRed folder, I really hope the issues will be solved on the next version, especially the database issue we still experience sometimes and the chat breaking.

**Comment by kangarko** [comment]
Going to monitor this in the next few days. I am typically here once per week only due to works on our training portal but I understand, will keep an eye on this.

**Comment by kangarko** [comment]
Pushed another update, please try it. Let me know below if there is anything I should look into!
