### ISSUE TITLE
1.17.1: BungeeControl-Red alternative

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#1512]
Minecraft Version: 1.17.2
MySQL: true
BungeeCord: true

I know that there is currently no Velocity support, but according to Velocity’s announcement, it will now be merged into the Paper project.
What I want to ask is whether I can realize cross-server chat when I do not use BungeeControl-Red, and continue to process it through Redis?
I tried to put your plug-in under Snap (https://github.com/Phoenix616/Snap) to work, but due to the use of some external data, it is difficult to invert compatibility, although cross-server chat can work. (https://github.com/Phoenix616/Snap/issues/21#issuecomment-980731718)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.2 MySQL: true BungeeCord: true
> 
> I know that there is currently no Velocity support, but according to Velocity’s announcement, it will now be merged into the Paper project. What I want to ask is whether I can realize cross-server chat when I do not use BungeeControl-Red, and continue to process it through Redis? I tried to put your plug-in under Snap (https://github.com/Phoenix616/Snap) to work, but due to the use of some external data, it is difficult to invert compatibility, although cross-server chat can work. ([Phoenix616/Snap#21 (comment)](https://github.com/Phoenix616/Snap/issues/21#issuecomment-980731718))

Hey,
You don't need to do a such thing since Velocity support is WIP, there's simply no ETA.
