### ISSUE TITLE
1.17.1: Permission to make groups except OP nonignorable

### ISSUE THREAD

**Issue by dushanbe7** [kangarko/ChatControl#1513]
Hello, can you please help me with this one, if I am OP, players can't use command /ignore on me. How can I do the same for other groups, like moderators, helpers etc. Is there somekind of permission so players can't ignore my moderators? Thank you.

We have been using this plugin for a while now, switched to Red recently, its awesome.

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Hello, can you please help me with this one, if I am OP, players can't use command /ignore on me. How can I do the same for other groups, like moderators, helpers etc. Is there somekind of permission so players can't ignore my moderators? Thank you.
> 
> We have been using this plugin for a while now, switched to Red recently, its awesome.
> 
> Minecraft Version: 1.17.1 MySQL: true BungeeCord: true

Hey,
Make sure to give your mods the permission `chatcontrol.bypass.reach`.
