### ISSUE TITLE
1.17.1: User switchs channel and leaves the other channels

### ISSUE THREAD

**Issue by notdeliable** [kangarko/ChatControl#1514]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Hi. A user switchs his channel and leaves the other channels. But I don't want that. If user switchs his channel, then other channels will become read-mode. Let me explain it:

![image](https://user-images.githubusercontent.com/72627840/144046401-a64c7648-8c66-40da-80ee-c58f4e830127.png)
Can I do that? Tysm.

**Comment by ElBananaa** [comment]
Hey,
As said on discord, please set `Join_Read_Old:` to `true` in the settings file.
