### ISSUE TITLE
Change EssentialsX messages using ChatControlRed

### ISSUE THREAD

**Issue by mikenex10** [kangarko/ChatControl#1516]
Hi there! 
I've recently bought this plugin and I am trying to use it to change some messages from EssentialsX. I know EssentialsX has his own "messages_en_properties" file, but placeholders there work kinda weird to be honest. 

This is my main problem:
When I use /pay <user> <amount>, the message given shows DISPLAYNAME (in this case, "Mod MilanesaBaby >>") and I would like it to show "MilanesaBaby" instead. Is there any way to change that message using ChatControlRed? That would be awesome.

Thank you so much!
![fototo](https://user-images.githubusercontent.com/94531051/144257516-e4bd7d4d-1500-40db-b382-b23480ad7e10.png)

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Not possible to edit EssentialsX placeholder using ChatControl Red, sorry. Even using Javascript variables you'd be out of luck since the variable has already been parsed by Ess.
