### ISSUE TITLE
Tab_Complete function enhancement

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#1518]
I hope to be able to add permission judgments and display different completion menus according to different permissions. (Priority is available), and it can be automatically blocked. You can directly block according to the rules here without going through `command.rs`.
For example, there is a player who has an architect and a player. I want to open WorldEdit to him, but it will not be completed by default. I hope it can be automatically completed using WorldEdit.

1. It can increase the adjustable setting range and provide different displays for different body groups.
2. It is suitable for players who want to see different commands according to different levels.

At present, I have seen that there are plug-ins with official functions, but they need to be paid. I don't want to install more plug-ins, and I hope this plug-in function can be more complete.

**Comment by kangarko** [comment]
Thanks for suggesting, but our tab complete system is take it or leave it right now, my plate is unfortunately too full to add more features to it. We'll of course reconsider this in the future.

**Comment by BearLeonLight** [comment]
> 

okay, I get it.
Thanks for your hard work.
