### ISSUE TITLE
Server Host says people are online when they actually aren't

### ISSUE THREAD

**Issue by TheLastBlockbender** [kangarko/ChatControl#152]
Ever since I added the plugin to the server, the amount of people it says are online stay even after they have left the server, is there a way to fix this in the config? Or is this a bug.

**Comment by kangarko** [comment]
Your issue might be in the console filter preventing certain message from appearing - and that plugin/server modification is reading them to detect the player count. Try disabling the console filter or removing all messages from it.

**Comment by TheLastBlockbender** [comment]
How do you disable the console filter?

**Comment by EvilOlaf** [comment]
Check your `settings.yml` for
```
Console:
  Filter:
    Enabled: false
```

**Comment by TheLastBlockbender** [comment]
Yay! It worked! Thank you so much!
