### ISSUE TITLE
1.16.3 | Hover gradients?

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#152]
Add some way to make a gradient in the hover part of the format

**Comment by kangarko** [comment]
Thanks but that is incompatible with our current system, nor is it something crucial for the plugin to run. People need the basics super stable and solid before adding more flash :)

**Comment by OfT3N** [comment]
> Thanks but that is incompatible with our current system, nor is it something crucial for the plugin to run. People need the basics super stable and solid before adding more flash :)

As i already said in one of the previous issue reports, current gradient system is not really good and that would be really great if you replaced it with the gradient system from such great plugins as CMI, TAB and TrMenu ({#123456>}Text of gradient{#654321<})

**Comment by kangarko** [comment]
That would cost a lot of performance, I can think about it to the future.
