### ISSUE TITLE
1.17.1 | /channel list takes longer to execute

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#1523]
CHC Version: 10.8.2
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Minor, but I've noticed that `/channel list` takes up to 10 seconds to execute on 10.8.2, whereas on 10.7.9, it took only a couple seconds maximum. My `data.db` is only 75KB, so the increase in time is a little odd.

**Comment by ElBananaa** [comment]
> CHC Version: 10.8.2 Minecraft Version: 1.17.1 MySQL: false BungeeCord: false
> 
> Minor, but I've noticed that `/channel list` takes up to 10 seconds to execute on 10.8.2, whereas on 10.7.9, it took only a couple seconds maximum. My `data.db` is only 75KB, so the increase in time is a little odd.

Hey,
I can't reproduce your issue. The list is instantly shown for me.
How many channels do you have?
Could you try to reproduce the issue on a local test server (keep your config file) to see if it also happens?

**Comment by kangarko** [comment]
ZIP us your /chc debug here please.

**Comment by BakiDance** [comment]
Sorry for the delay. I have kept the same configs on a test server, now running 10.8.3, and the issue persists.
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7678032/debug.zip)

**Comment by BakiDance** [comment]
Since the issue persisted on the test server, I decided to delete the `data.db` file and let it repopulate. Now, it's working instantaneously. I'm not sure what the issue was, but it seems related to that file.

I've not made any manual changes to it, though. Nor have many players logged in. I only noticed it slowing down after an update to ChatControl.

**Comment by kangarko** [comment]
Fixed, thanks.
