### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by XGiammyX** [kangarko/ChatControl#1524]
Minecraft Version: 1.X.Z
MySQL: true/false
BungeeCord: true/false

[21:25:20] [Server thread/INFO]: [0;31;1mError: 'java.lang.Class sun.misc.Unsafe.defineAnonymousClass(java.lang.Class, byte[], java.lang.Object[])'[m

**Comment by ElBananaa** [comment]
Hey,
Please update your message to match the format, provide the full error, and also update your issue's title.

**Comment by kangarko** [comment]
Invalid ticket format and not verified purchase, email matej@mineacademy.org with

- Your paypal transaction ID
- "/chc debug" file
- your latest.log file
