### ISSUE TITLE
1.18: Plugin does not start

### ISSUE THREAD

**Issue by dfgsteam** [kangarko/ChatControl#1526]
Minecraft Version: 1.18 PaperMC-25 
MySQL: false
BungeeCord: false

Pluginversion: 10.8.2

Error: [22:28:23 INFO]: Cannot use this command while the plugin is disabled.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.18 PaperMC-25 MySQL: false BungeeCord: false
> 
> Pluginversion: 10.8.2
> 
> Error: [22:28:23 INFO]: Cannot use this command while the plugin is disabled.

Please provide both the `/chc debug` file & the full latest.log file.

**Comment by yourlocalvirgo** [comment]
Hiya, just wondering if there's an update to 1.18 support for ChatControl Red? I tried to update my server a few days ago, but due to chat control not being compatible with 1.18, the plugin actually stopped my server from running at all. Just wondering if there's an ETA!

**Comment by kangarko** [comment]
It's been implemented long time ago. Your ticket is unfortunately invalid, please post us a full console log from start till it says "Done!" when the server starts up, as well as /chc debug below.

Closing to cleanup, but we're reading discussion below normally.
