### ISSUE TITLE
Will not logging chinese word

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1527]
![image](https://user-images.githubusercontent.com/29138111/144689223-629e9c45-287d-420c-9782-569b42eb064e.png)
![image](https://user-images.githubusercontent.com/29138111/144689265-80b27202-efb0-495c-9914-6ceb6e74fe85.png)
![image](https://user-images.githubusercontent.com/29138111/144689280-e155d5d6-a71a-4a5d-8dab-d016ec798d6c.png)

![image](https://user-images.githubusercontent.com/29138111/144689284-366e832f-435d-4f63-a918-c850dfb4a31d.png)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
We had to disable extended unicode for security some time ago, I will look forward into reenabling this with a config option in the future.
