### ISSUE TITLE
1.17.1: Can I override prefixes?

### ISSUE THREAD

**Issue by 10Meisterbaelle** [kangarko/ChatControl#1529]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Is there a way to format your chat by making it so you can override the prefixes I added, like if you have the permission `chatcontrol.group.group1` and `chatcontrol.group.group2`, it will only show the prefix of group2.

**Comment by kangarko** [comment]
Yes, you can create two format parts, one requiring permission1 and the other requiring permission2.

Then use your permissions plugin to give negative -permission1 (a false value in LuckPerms) when players have permissioin2 so only the second prefix will get shown :)
