### ISSUE TITLE
1.16.3 | Message deleting bug

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#153]
Another tester (and a friend of mine) has some statistics from MMOCore displayed in actionbar, and your plugin counts them as a chat message, so when you delete any message from the chat, it spams a lot with the actionbar statistics in the chat
![image](https://user-images.githubusercontent.com/62369973/99994988-d8ddf280-2dca-11eb-9061-5dc7fc2771fc.png)

P.S: I didnt share a plugin with my friend, i just invited him to take part in testing and you gave him the test role :D (Shimaletik#6009)

**Comment by kangarko** [comment]
Sharing with friends is fine! Thanks for reporting.

How can I reproduce this problem? Can you send me mcMMO folder as ZIP?

**Comment by OfT3N** [comment]
> Sharing with friends is fine! Thanks for reporting.
> 
> How can I reproduce this problem? Can you send me mcMMO folder as ZIP?

Sent via email

**Comment by kangarko** [comment]
Thanks, solved.
