### ISSUE TITLE
Custom command ?

### ISSUE THREAD

**Issue by IceSweets** [kangarko/ChatControl#153]
Hello,
I want to ask is it possible to make custom command using commands.txt file in chc ?
Something like:

match 123
then console run op %player%

Thanks !

**Comment by EvilOlaf** [comment]
Yes.
Check examples in `commands.txt` as well as possible actions in the description on top of `rules.txt`.

In your case probably
```
match ^/123$
then console op %player
```

**Comment by kangarko** [comment]
What @EvilOlaf says. It is also possible to use native bukkit.yml file to create aliases and or execute multiple commands at once, check:

http://wiki.bukkit.org/Commands.yml

**Comment by EvilOlaf** [comment]
Yes. What you CAN'T do with CBs' command file though is to add individual permissions to those ;)
