### ISSUE TITLE
Motd

### ISSUE THREAD

**Issue by T4iKoN** [kangarko/ChatControl#1530]
Hey i need help with my Motd.

after i install Chat Control
![image](https://user-images.githubusercontent.com/26348551/144720834-71034de1-c24f-4876-9d48-27c73f995fd0.png)

**Comment by ElBananaa** [comment]
> Hey i need help with my Motd.
> 
> after i install Chat Control ![image](https://user-images.githubusercontent.com/26348551/144720834-71034de1-c24f-4876-9d48-27c73f995fd0.png)

Hey,
Please update your message to follow the bug report format, same with the title.
ChatControlRed doesn't handle the server list motd, but the ingame motd, so I believe your issue is unrelated to the plugin.

**Comment by kangarko** [comment]
You need to use the UTF8 flag to allow your non-English symbols to appear correctly.

1. Remove all non-English symbols.
2. Use this flag when your server starts: https://bukkit.org/threads/startup-script-flag-for-enabling-utf-8.171342/
3. Profit
