### ISSUE TITLE
Before buying the plugin

### ISSUE THREAD

**Issue by typicalsmc** [kangarko/ChatControl#1531]
Hello, before buying the plugin, i need to know that.
Do this plugin need all players connect on the same bungeecord network in order to be function or no?
I want to setup a cross-server chat with multiple bungeecord network.

**Comment by ElBananaa** [comment]
Hey,
I do believe the plugin should work perfectly with with multiple bungee setups as soon as they all connect to the same database.
However, I'd suggest waiting for @kangarko to ensure the plugin will work properly in that case ^^

**Comment by typicalsmc** [comment]
> Hey, I do believe the plugin should work perfectly with with multiple bungee setups as soon as they all connect to the same database. However, I'd suggest waiting for @kangarko to ensure the plugin will work properly in that case ^^

can you give me a time that @kangarko will reply to this issue please? Because we kinda need to switch as soon as possible

**Comment by ElBananaa** [comment]
Unfortunately I can't, but he will most likely answer you before the end of the week.

**Comment by kangarko** [comment]
We support Redis. You can use Redis to connect multiple networks together. Then install BungeeControlRed on all Bungee networks.
