### ISSUE TITLE
1.18: JavaScript Variables throwing error

### ISSUE THREAD

**Issue by nurdism** [kangarko/ChatControl#1532]
Attempting to use the example/default `[item]` variable and it throws an error. 

[Error log](https://gist.github.com/nurdism/c9d4d0fad389bf40846496020196e04b)
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7659889/debug.zip)

Minecraft Version: 1.18.0
MySQL: true
BungeeCord: true

**Comment by codeHusky** [comment]
Also have same issue, been happening since we upgraded to the 1.18 server software

**Comment by kangarko** [comment]
Thanks, will get patched asap.
