### ISSUE TITLE
1.17.1: How do i do cross server messaging ?

### ISSUE THREAD

**Issue by typicalsmc** [kangarko/ChatControl#1533]
So i have moved from VentureChat to ChatControl-Red because it supports Redis so i can do multi bungee.
But now the Cross-server messaging seems doesnt work and im kinda dont understand it ?
Can anyone give me an tutorial please? 

Minecraft Version: Paper version git-Paper-397 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 1a83e90 on ver/1.17.1)
MySQL: true
BungeeCord: true

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7661039/debug.zip)

**Comment by NoobcoreNetwork** [comment]
> So i have moved from VentureChat to ChatControl-Red because it supports Redis so i can do multi bungee. But now the Cross-server messaging seems doesnt work and im kinda dont understand it ? Can anyone give me an tutorial please?
> 
> Minecraft Version: Paper version git-Paper-397 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 1a83e90 on ver/1.17.1) MySQL: true BungeeCord: true
> 
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7661039/debug.zip)

Hey! So it would appear your main chat you want to go across bungee is

```
    global:
      Format: global-chat
      Bungee: true
      Range: '*'
```

Are you also running mysql? I'd recommend it for this kind of setup, You need to make sure you have Bungee-controlRED Installed on your proxy.

If it appears to not be working and you have all that setup then the chances are you are not actually in the 'global channel'

These are the permissions I use for my global channel, Make sure everyone you want to be in that channel by default has them

```
chatcontrol.channel.autojoin.global.write
chatcontrol.channel.join.global.write
```

This should put players who login automatically into the global channel, and let them read/write in said channel

 **I am in no way a helper of chat control, Just helping out and follow my advice if you wish its just what works for me, This can be removed if it's not allowed, just trying to help out!**

**Comment by kangarko** [comment]
Thanks @NoobcoreNetwork for a great answer!

Basically, install BungeeControl Red on your BungeeCord network, and then configure your channels to write the "Bungee: true" key to their config in Channels.List in settings.yml as Noobcore mentioned.
