### ISSUE TITLE
1.8.9: Default 'messages_fr.yml' lacks an Object at 'Channels.Set.Usage'

### ISSUE THREAD

**Issue by haeiven** [kangarko/ChatControl#1534]
Minecraft Version: 1.8.9
MySQL: true
BungeeCord: false

Getting this error since i've updated to 10.8.3: https://paste.soleria.eu/hecakupoyi.apache

**Comment by ElBananaa** [comment]
Hey,
Thanks for reporting this error.

The next update should include an updated version of the french lang file. In the meantime, here's the fixed version https://gist.github.com/ElBananaa/89bc86291ec0696e98d36e9123cfa33d
