### ISSUE TITLE
1.17.1 Changing Plugin Prefix

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#1535]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Is there any way to change the plugin prefix when changing a channel/spy a user? I have already searched the wiki for the whole topic, maybe I missed it several times?

I would be pleased to receive an answer!
~Lorias

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1 MySQL: true BungeeCord: true
> 
> Is there any way to change the plugin prefix when changing a channel/spy a user? I have already searched the wiki for the whole topic, maybe I missed it several times?
> 
> I would be pleased to receive an answer! ~Lorias

Hey,
You can change the plugin's prefix at the end of the settings file.

As for the other parts of the messages, they can be edited in your localization file.
