### ISSUE TITLE
1.17.1: Clear all nicks

### ISSUE THREAD

**Issue by mav2020** [kangarko/ChatControl#1537]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Is there a command to clear nicks for all players? Something like /tag nick * off (or server off, or anything?) I know I can go into MySQL and do something to clear them, but I am would rather avoid that. Thanks.

**Comment by kangarko** [comment]
No, why would you need so? I can add this when I have time. Closing to clean up. Also apology for a late answer.

**Comment by mav2020** [comment]
Nicks, coloring nicks, formatting nicks, etc. are a great cosmetic to give as the ranks get higher. Since there is no way to use different nicks on different servers in a bungee network, when starting a new server with new ranks it would be helpful to clear the existing ones.

**Comment by kangarko** [comment]
Thanks, I can add this when I have time!

**Comment by kangarko** [comment]
I apology, having reviewed the code it's technically challenging to do with the time I have at my disposal this Christmas, I can have a look next year.
