### ISSUE TITLE
1.17.1: Server / Site's sometimes pass the advert filter

### ISSUE THREAD

**Issue by SecretarySami** [kangarko/ChatControl#1538]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

So a while ago i noticed that a player had said "craft.arc.scalacube.site" and our advert filter failed to catch it and still does.
this is our current Ip/Advertising thing and I'm not seeing where the issue is occurring.

https://pastebin.com/yj4LZ0gD

**Comment by mav2020** [comment]
You need to add 'site' to your blocked top-level domain. This regex has it:
`match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o|s(| +)i(| +)t(| +)e)\b`

**Comment by TheIntolerant** [comment]
Edit the ``match`` part under ``# Domain/URL filter.`` to this:

``match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|(?<! )c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|(?<! )m(| +)e|i(| +)o|(?<! )s(| +)i(| +)t(| +)e)\b``


The only difference between this and the above is the fact that this was taken from the rules you provided then edited. As I noticed a few slight changes to that rule

**Comment by TheIntolerant** [comment]
comment below if you still need help :)

**Comment by SecretarySami** [comment]
> match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|(?<! )c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|(?<! )m(| +)e|i(| +)o|(?<! )s(| +)i(| +)t(| +)e)\b

Thank you! works awesome , really appreciate it!
