### ISSUE TITLE
1.17.1: Console prefix [ChatControlRed] causing console duplication issues

### ISSUE THREAD

**Issue by addstar** [kangarko/ChatControl#1539]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Firstly, I'm not entirely sure this is a bug but it is causing a behaviour change that is preventing our custom console from being able to detect duplicate lines properly.

We have a custom console tool that streams the console output from all servers in our bungee network so we can watch everything in real time. Everything was working perfectly with ChatControlRed until recently when we upgraded to 10.8.3 (from 10.6.5). We noticed chat lines were being duplicated because chat logged from other servers are prefixed with `[ChatControlRed]` but local chatisn't, so they don't get detected as duplicate.

I checked the CCR source code and noticed that it will only ever prefix log messages and use `System.out.println()` when `CONSOLE_SENDER` is null. I'm not sure why the console sender would be null? I also noticed the `CONSOLE_SENDER` is initialised as static/final very early on in the server startup, and maybe I'm mistaken but at that point I don't think the server console sender is available.

Obviously one option for our duplication issue is to ask for you to put in a toggle to remove the prefix, but I'm also now concerned that something else isn't right, because of the ConsoleSender issue.

Any thoughts? :)

**Comment by kangarko** [comment]
Hey!

Apologies for writing in late. Can you show an example of that console message?

I forced the console sender to be used at all times, from my testing on 1.17 it works fine. The use was just a remain from an experiment to run Foundation without the Spigot server itself, something we abandoned a long time ago.

Try out the next version please. I am closing this to cleanup, but we'll continue our conversation below.

**Comment by addstar** [comment]
> Can you show an example of that console message?

To demonstrate the issue, below is an example where I said `chat test` in global channel on `Server1`. It logs correctly on the local server but on all other servers it is prefixed with `[ChatControlRed]`. Hope this makes sense?
```
Server1: 2021-12-14 07:10:08 [Async Chat Thread - #624/INFO]: [Donator] <add5tar> chat test
Server2: 2021-12-14 07:10:08 [Server thread/INFO]: [ChatControlRed] [Donator] <add5tar> chat test
Server3: 2021-12-14 07:10:08 [Server thread/INFO]: [ChatControlRed] [Donator] <add5tar> chat test
```

To be clear, it's not just chat, it seems to be any message from CCR:
```
2021-12-13 22:45:11 [Server thread/INFO]: [ChatControlRed] Loading 1 libraries... please wait
2021-12-14 07:03:25 [Server thread/INFO]: [ChatControlRed] TIP: Joining player to his saved channel global in mode write
```


> Try out the next version please. I am closing this to cleanup, but we'll continue our conversation below.

These messages are all while running 10.8.3, I don't see a newer version?

**Comment by kangarko** [comment]
The new version is pending for release later tonight, let me know if it makes any difference.

**Comment by addstar** [comment]
> The new version is pending for release later tonight, let me know if it makes any difference.

We've rolled out the latest update and the `[ChatControlRed]` prefix is still there, but at least it's consistent now. The prefix is now also logged on the local server now, so at least the de-dupe system works :+1: So this solves our issue, thanks!
