### ISSUE TITLE
1.16.3 | /pm command makes the game freeze

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#154]
When you pm sb or reciev pm from somebody, theres a half-a-second game freeze (advancement issue mb)

**Comment by ElBananaa** [comment]
> When you pm sb or reciev pm from somebody, theres a half-a-second game freeze (advancement issue mb)

This is related to the Toast notifications so I don't think there's anything he could do about it...

**Comment by kangarko** [comment]
If you have Toasts enabled, they will drain performance since they must write to disk. Disable to get the lag removed.

**Comment by OfT3N** [comment]
> If you have Toasts enabled, they will drain performance since they must write to disk. Disable to get the lag removed.

Im not sure if it's like that, because i also have CMI and CMI /toast command do not make a single freeze

**Comment by kangarko** [comment]
Not sure how they do it, we tried numerous solutions that lead to data loss, I am not comfortable putting this async just to hide lag at the expense of data corruption.
