### ISSUE TITLE
Rules are not evaluated in the order they're written

### ISSUE THREAD

**Issue by NShadeIV** [kangarko/ChatControl#154]
catch-all rules are broken in that they may be checked **before** more specific (and overlapping) rules.

example:

`match ^\.god`
`then console sudo {player} pex user {player} group add god`
`then deny`

`# don't print ".good" or ".dog" if the above gets mis-typed`
`match ^\.[a-z]`
`then deny`

the rules above seem to be checked in a non-specifiable order.  definitely **not** the order they were written in.  so, the 2nd rule may be checked before the 1st, thereby effectively ignoring the 1st rule

**Comment by kangarko** [comment]
Do you still wish help regarding this issue? The rules are loaded from top to bottom into the plugin. There might be some exceptions but those are not in my control, sadly. This should be avoided by placing them in the same file, e.g. rules.txt for globally applicable rules.
