### ISSUE TITLE
Adding GriefDefender and GriefPrevention hooks for chat channels.

### ISSUE THREAD

**Issue by MrCrazys** [kangarko/ChatControl#1540]
Support for GriefDefender and GriefPrevention would be really useful for chat channels like claim chat, town chat, etc.

**Comment by kangarko** [comment]
@MrCrazys what exactly are you looking for? How would you use it?

**Comment by MrCrazys** [comment]
It'd be a useful addition for party chat, as there is plot chat, towny chat, etc.

**Comment by kangarko** [comment]
Thanks. I reviewed the free one, does not look they have an API for party event, either way I am extremely busy these weeks and I wont be having time to look into this right now, apologies.

**Comment by ShuoYu1026** [comment]
Is there any progress? I need it too
