### ISSUE TITLE
1.17.1: DiscordSRV Webhook and Reserializer support.

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#1541]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

After I enable the Webhook function, I can delete messages in the game, but I cannot delete the messages on Discord synchronously.

In addition, DiscordSRV has the following experimental features. Can you add support or can ChatControl automatically switch when processing Discord<->Minecraft messages?
``
Experiment_MCDiscordReserializer_ToDiscord: true
Experiment_MCDiscordReserializer_ToMinecraft: true
Experiment_MCDiscordReserializer_InBroadcast: true
```

**Comment by kangarko** [comment]
Thank you, I can have a look but I am presently very busy with other stuff, there's no ETA on this unfortunately.
