### ISSUE TITLE
Suggestion: {top_role} placeholder for DiscordSRV integration

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#1542]
DiscordSRV comes with a %toprole% placeholder in its `DiscordToMinecraftChatMessageFormat` field in messages.yml. This way, when someone sends a message in the Discord channel, their highest, visible, role is displayed in-game.

This is very useful to prevent users from impersonating staff, since Discord allows users to change display names easily.
Unfortunately, ChatControl does not provide a way for staff to ensure Discord roles are displayed.

Alternatively, this could be bypassed if it were possible to allow DiscordSRV to format its own messages to chat, instead of CHC taking over in integration. (Similar to how it was in CHC8)

**Comment by kangarko** [comment]
Thanks for suggesting! I am putting this to the backlog due to other priorities but it is something I want to implement asap.

**Comment by kangarko** [comment]
I'll be honest, I had to scrape this for now due to lack of time. However these things then get put to the backburner and I actually have a look at them throughout the year, so I may implement this later. Thank you and sorry!

**Comment by Noxillio** [comment]
Real quick thing in addition to this - absolutely NO placeholders are parsed if a message comes from Discord. Makes no real sense at all and I don't know why it is but even if it's a placeholder that there's very obviously enough information to parse (even %server_tps% for example, when the required PAPI expansion is installed, and it parses everywhere else) it still isn't even attempted to be parsed by CHC. Incredibly frustrating and I feel that maybe there's been some neglect or other oversight in this area. I want to know why it has been done this way, there's no logical reason for it that I can see.

**Comment by kangarko** [comment]
After bending backwards and doing 3 backflips I finally got this to work haha!
