### ISSUE TITLE
Suggestion Regarding Join Messages and texture packs.

### ISSUE THREAD

**Issue by NoobcoreNetwork** [kangarko/ChatControl#1544]
Hey there! As you're probably aware, more and more servers are using custom resource/texture packs,
I'm wondering if it's possible to delay the join messages, until the resource pack has been loaded? I have seen some other plugins do this but I dont want to use another plugin just for join messages when CCR does it perfectly fine!

So like at the moment, when you join on a busy server,

You join > It says you  joined, Then the Pack takes 10-15 seconds load for you so you dont see chat
Everybody says hello,
But you don't see this because you're loading
By time you see the chat the messages are gone now.

But what it could be

You join, It doesnt say you joined yet, The pack loads
Then when youre actually able to talk, it says you joined, and you wont miss any hello messages!

Thanks and i hope this makes sense lol!

**Comment by ElBananaa** [comment]
> Hey there! As you're probably aware, more and more servers are using custom resource/texture packs, I'm wondering if it's possible to delay the join messages, until the resource pack has been loaded? I have seen some other plugins do this but I dont want to use another plugin just for join messages when CCR does it perfectly fine!
> 
> So like at the moment, when you join on a busy server,
> 
> You join > It says you joined, Then the Pack takes 10-15 seconds load for you so you dont see chat Everybody says hello, But you don't see this because you're loading By time you see the chat the messages are gone now.
> 
> But what it could be
> 
> You join, It doesnt say you joined yet, The pack loads Then when youre actually able to talk, it says you joined, and you wont miss any hello messages!
> 
> Thanks and i hope this makes sense lol!

Hey,
I don't know if it is possible to detect when a server ressource-pack is properly & fully loaded on the user end. However, I do believe adding a `delay-join-messages:` option to delay the join motd/welcome message/join message can be pretty useful, especially for server with resourcepacks (which, as you said, are now a pretty big part of mc servers, and it keeps growing).
I'd love to see this feature added! :)

**Comment by NoobcoreNetwork** [comment]
> > Hey there! As you're probably aware, more and more servers are using custom resource/texture packs, I'm wondering if it's possible to delay the join messages, until the resource pack has been loaded? I have seen some other plugins do this but I dont want to use another plugin just for join messages when CCR does it perfectly fine!
> > 
> > So like at the moment, when you join on a busy server,
> > 
> > You join > It says you joined, Then the Pack takes 10-15 seconds load for you so you dont see chat Everybody says hello, But you don't see this because you're loading By time you see the chat the messages are gone now.
> > 
> > But what it could be
> > 
> > You join, It doesnt say you joined yet, The pack loads Then when youre actually able to talk, it says you joined, and you wont miss any hello messages!
> > 
> > Thanks and i hope this makes sense lol!
> 
> Hey,
> I don't know if it is possible to detect when a server ressource-pack is properly & fully loaded on the user end. However, I do believe adding a `delay-join-messages:` option to delay the join motd/welcome message/join message can be pretty useful, especially for server with resourcepacks (which, as you said, are now a pretty big part of mc servers, and it keeps growing).
> I'd love to see this feature added! :)

There's a few methods I can think of.

I know you could 100% add a hook to only fire IF they accept the resource pack. So right now if you join press no on the pack it will send a join and leave which isn't ideal. And there is an event fired by spigot when you accept which could fire the join message.

Or the alternative is waiting until the player first moves. This could also be a double up if bots join their spam join messages won't show (unless they are smart enough to move) but it also poses the question of can a player be pushed and will that activate the join message.

I did some research and I don't think there is a way to determine when the pack is fully loaded. Only when it's accepted or denied.

**Comment by NoobcoreNetwork** [comment]
I wasn't sure about opening a new ticket but I can't for the life of me figure out how to get nick to show on the join messages etc, Im using bungee, maybe that is why?

```
group default
require playedbefore
message:
- &7&l%chatcontrolred_nick% &ehas logged in
```

I have tried
%chatcontrolred_nick%
{chatcontrolred_nick}
%nick%
{nick}

All of which seem to parse correctly in game but it just shows the raw placeholder when you login,

thanks :3

**Comment by ElBananaa** [comment]
> I wasn't sure about opening a new ticket but I can't for the life of me figure out how to get nick to show on the join messages etc, Im using bungee, maybe that is why?
> 
> ```
> group default
> require playedbefore
> message:
> - &7&l%chatcontrolred_nick% &ehas logged in
> ```
> 
> I have tried %chatcontrolred_nick% {chatcontrolred_nick} %nick% {nick}
> 
> All of which seem to parse correctly in game but it just shows the raw placeholder when you login,
> 
> thanks :3

Hey, try `{player_nick}`, however, keep in mind that this placeholder will only work if you use our internal nick system. I'm not 100% sure about that, but using the async join messages could also be the reason for the placeholder to no work properly.
If the issue persists, please open a new issue, as this will allow us to properly track issues.

**Comment by kangarko** [comment]
Thanks to Banana for helping out. Right now we do not check for player movement, this is something I can consider when I have more time but it's not our core focus as the plugin is already overly complex and I am afraid to making it even more difficult to setup,.
