### ISSUE TITLE
1.17.1: ChatControl crashed the server?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1546]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Last night someone typed a message and it seems to have caused a crash related to ChatControl.. though I am not completely sure but I thought to report it.

The error: **LINK REMOVED FOR SAFETY**

**Comment by ElBananaa** [comment]
Hey,
Thanks for reporting this issue, however it is unrelated to us.
As Paper stated on their discord server yesterday, they found and patched a major & severe security issue related to log4j. Issue which has been patched on spigot/paper, but no on purpur's side (they are working on deploying patches for 1.18, 1.17.x & 1.16.5 and will release it once it's ready).

Just to make sure about it, I did run the message the user sent before your server crashed, under both a purpur 1.17.1 b1428 & paper 1.17.1 b399, and the issue only appeared with purpur.

I'd suggest banning any user sending this message & switching to the latest paper build available until purpur releases a fix for this issue.

**Comment by kangarko** [comment]
I'll patch the vulnerability for servers that haven't updated in the next version myself too.

**Comment by ElBananaa** [comment]
Also please take a look at this post published by Mojang which gives your more explanation on how to properly fix this issue on your end (even tho purpur has now released a patch): https://www.minecraft.net/en-us/article/important-message--security-vulnerability-java-edition

**Comment by Sikatsu** [comment]
Thank you, this issue is solved on my server. There was a way of testing whether you solved it properly, kind of already forgot how haha

**Comment by ElBananaa** [comment]
> Thank you, this issue is solved on my server. There was a way of testing whether you solved it properly, kind of already forgot how haha

Well, I'd suggest trying the exact same message the user sent, and wait a lil bit, at some point, the console should stop refreshing, and then after a few minutes, the server will crash. ^^

**Comment by Sikatsu** [comment]
That's indeed also a way!
