### ISSUE TITLE
Adding a /chc parse command

### ISSUE THREAD

**Issue by MrCrazys** [kangarko/ChatControl#1547]
I think a /chc parse command would be useful in order to parse variables, placeholders, and JavaScript variables using a command, and possibly add the option to specify in what message/context it would be used in.

**Comment by ElBananaa** [comment]
> I think a /chc parse command would be useful in order to parse variables, placeholders, and JavaScript variables using a command, and possibly add the option to specify in what message/context it would be used in.

Hey,
We already have a such feature. Please use `/chc info variables` command to get a bit more informations ^^
