### ISSUE TITLE
[Bungeecord] Private Message have problem

### ISSUE THREAD

**Issue by geumu** [kangarko/ChatControl#1548]
**Bukkit**: Catserver 1.12.2
**Bungeecord**: true
**Mysql**: true
**Plugin**: ChatControl-Red-10.8.3
**Explanation**: 'Player {player} is not online on this server.' when using private message. The private message is sent only when you use the 2nd or 3rd command.
It works fine when there are no players, but when there are many players (200), this symptom persists. It is expected that the problem is caused by overloading the database.
**Video**: https://youtu.be/sdwlj3WaPhs
**settings.yml**: https://drive.google.com/file/d/1Z1_K2LRZ7iptljnNAmDCxM0cNg_5Vl1G/view?usp=sharing

**Comment by kangarko** [comment]
I will add a new key "Sync_Period" to settings.yml of BungeeControl and ChatControl, you will need to tweak that value, maybe set it to "10 ticks" on Spigot and leave 1 second on Bungee (which is 20 ticks), or the opposite. Try lower values and it should work, thank you!

**Comment by geumu** [comment]
you are the be

> I will add a new key "Sync_Period" to settings.yml of BungeeControl and ChatControl, you will need to tweak that value, maybe set it to "10 ticks" on Spigot and leave 1 second on Bungee (which is 20 ticks), or the opposite. Try lower values and it should work, thank you!

you are the best
