### ISSUE TITLE
Need Help Please.  [RESOLVED]

### ISSUE THREAD

**Issue by Mutim** [kangarko/ChatControl#155]
**RESOLVED** Thank you!

Hello everyone! I have an issue in getting this to work. I've tried everything, from restarting the server, to using debug, and even uninstalling, and reinstalling. 
This is my startup log. [here](http://pastebin.com/0cRzDQuV)
MC version is: 1.10.2
I THINK the version of CHC is: 271
When I type the command /chc  nothing happens, just blank text. 
If you need any more information, please let me know. This plugin would help my server tremendously.
Thank you in advance!

**Comment by kangarko** [comment]
Please post in the premium section.

I cannot see where the problem is, please use the latest version.
