### ISSUE TITLE
1.16.4 | The mute button shown in the channel list mutes a user named "channel" if the internal "Mute" function isn't enabled

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#155]
# **Environment**
### **ChatControl Version**: ChatControlRed-10.1.0

- Hey! I noticed that when you disable the plugin's internal mute function, if you click on the mute button when using `/chc list`, it tried to mute a player named channel. It would be cool if, even if the mute function is disabled, you could still use the channel mute feature.

**Comment by kangarko** [comment]
Thanks, I will hide these buttons. Unfortunately the system is designed in a way to toggle mute feature all together, not partially. That would lead to other issues.

**Comment by ElBananaa** [comment]
Alright! Thanks for the answer. So I wonder, how will it work for ppl that use channels and a ban management plugin (like litebans)?
What will happen if I use litebans' mute function for each player, or the mutechat?

**Comment by kangarko** [comment]
Then Litebans will take over and prevent people from typing. I will make that to the next version. Thanks for noticing!
