### ISSUE TITLE
Unable to pass nickname from CCR From Bungee>Spigot On Join/Leave Messages

### ISSUE THREAD

**Issue by NoobcoreNetwork** [kangarko/ChatControl#1550]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Hey! So, I sell nicknames on my server, And I noticed that when a player logs in, it shows their normal name, not their nick, So I opened up where the join/leave messages are set inside of join.rs in chat control (On the bungee side)

And my code is 

```
group default
require playedbefore
message:
- &7&l{player_nick} &ehas logged in
```

But whenever a player logs in, anyone, it shows the raw placeholder and not the intended nickname
I have tried many variations including

```
%chatcontrolred_nick%
{chatcontrolred_nick}
%nick%
{nick}
```

But they all seem to have the same result.

![javaw_kmj9GsDWIg](https://user-images.githubusercontent.com/62724418/145652231-ce55e790-3301-4ba7-82d1-3ab8d99ecf61.png)

At first I was thinking maybe its because it's on the proxy side of things but, both being on a mysql database It should be able to fetch the nickname regardless. **(I'm using chat controls nicknaming system)**

Here is my nickname 'josh'
![javaw_SliMFELHWs](https://user-images.githubusercontent.com/62724418/145652404-fe8e2fda-0bf2-4cf5-bd39-a2fa7d3fac71.png)

And here is a papi parse of %chatcontrolred_nick%
![javaw_PAohZa53iL](https://user-images.githubusercontent.com/62724418/145652454-da493bfb-b181-4aeb-b64f-208b18878872.png)

Thanks! let me know if any more detail is required.

**Comment by Sikatsu** [comment]
In general, I think the nicknames are set on the spigot servers. The bungee does not seem to be aware of the nicknames, as I tried to show nicknames in my parties plugin (that runs on the bungee) though that also does not seem to be possible. Perhaps @kangarko has an idea?

**Comment by NoobcoreNetwork** [comment]
> In general, I think the nicknames are set on the spigot servers. The bungee does not seem to be aware of the nicknames, as I tried to show nicknames in my parties plugin (that runs on the bungee) though that also does not seem to be possible. Perhaps @kangarko has an idea?

I mean that doesn't really add up because I can set a nickname on my lobby and it is set on my survival using mysql and a proxy. Maybe bungeecontrol red doesn't connect to the mysql and is merely just a bridge between spigot servers? I'm not sure if bungee red has mysql options in the config as I'm not at my pc.

**Comment by Sikatsu** [comment]
Yeah, that works as I mentioned as well. But the bungee does not seem to know about the nickname. I think this is something kangarko needs to do if he can..

**Comment by kangarko** [comment]
Thanks, we did not support it. I added the following variables (in blue on the left side such as {player_nick} is "player_nick" to the next release:

![a](https://i.imgur.com/odVNhdx.png)

**Comment by Sikatsu** [comment]
Can I also use this in another plugin that runs on the bungee? Likes my parties plugin? @kangarko

**Comment by kangarko** [comment]
What's the name of the plugin? Asaik PlaceholderAPI has no bungee support.

**Comment by Sikatsu** [comment]
The plugin is called Parties. It's installed on the bungee and it would be cool if I can have the nicknames showing in the party chat. PlaceholderAPI indeed doesn't have bungee support..

**Comment by kangarko** [comment]
@Sikatsu this one? https://www.spigotmc.org/resources/party-and-friends-for-bungeecord-supports-1-7-x-to-1-18-x.9531/

**Comment by Sikatsu** [comment]
@kangarko https://www.spigotmc.org/resources/parties-an-advanced-parties-manager.3709/updates

**Comment by kangarko** [comment]
Will follow up with their dev, thanks.

**Comment by Sikatsu** [comment]
Awesome! Thank you :)
