### ISSUE TITLE
1.17.1: Sound error

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1552]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Seem to have new pattern errors in the console: <https://pastebin.com/HGR2xeN2>

**Comment by kangarko** [comment]
Strange, the same exact pattern works on my system: https://i.imgur.com/F3V7kR9.png

Whats more strange is that it passes regex101.com syntax check.

I will have to silence it at the end. Should work for most cases but when it fails, sound notify will fail silently. Needs more investigation but could even be java-related.
