### ISSUE TITLE
1.17.1: ItemsAdder Rainbow Text Bug

### ISSUE THREAD

**Issue by notdeliable** [kangarko/ChatControl#1556]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Hi. There is a bug with ItemsAdder rainbow text bug. Here is the feature: https://itemsadder.devs.beer/plugin-usage/text-effects-1.17+

Here is the bug: 
![image](https://user-images.githubusercontent.com/72627840/145871360-27bbefe8-cc0a-496f-aed0-eecbff2a41f7.png)

**Comment by kangarko** [comment]
Sorry, this is unsupported with ChatControl Red, we only support the basic ItemsAdder version.
