### ISSUE TITLE
Question before purchasing. 

### ISSUE THREAD

**Issue by Dracathio** [kangarko/ChatControl#1559]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

I wanted to know if the purchase on MCMarket is a full year or a life time purchase.
Mainly because we are a Chat Control Pro customer and have been for over 2 years now and I'd like to get the newest features you've created with Chat Control Red and help support the development of the plugin by purchasing it a second time.

Thank you for any answer you can provide.

**Comment by RhinoCD** [comment]
life time purchase! :D

**Comment by TheIntolerant** [comment]
Hey, as RhinoCD stated, you will have lifetime access to ChatControl-red once purchased. 
I will close this issue but if you have any extra questions feel free to comment below. :)

**Comment by kangarko** [comment]
After a some months earlier this year I changed my decision and we have lifetime access and free upgrades for all customers :)
