### ISSUE TITLE
Suggestions for the lang files

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#156]
Hey!

- I started to look inside the lang file to see what could be improved, and I noticed that the write/read modes can't be translate. Translating them for the commands is pretty useless, but it would be cool to be able to translate them in the lang files.

- I also started to work on a translation on my side (I know, changes can still be done to the lang files, but I prefer to start working on it right now), and I noticed that you can't use apostrophes in some parts of the file
E.g. `'(self ? ''You have'' : ''Player has'') + '' no channels to leave.'''`
In this case, I tried using: `''`, `\'`, it didn't work.

- I also noticed that you can't use this format everywhere: `(self ? ''You'' : ''The player'')`, the problem is that in some languages (in my case, french), the verbs aren't the same for each person.
E.g. `Switch_To_Reading: '{person} switched the &o{0} &7channel to reading. Type the command again to leave.'`
In french, if the person is "You", it would be "You have switched". If the person is anything else, it would be: "The player has switched".
It wouldn't be a big deal if this would happen for only one or two lines, but in my case, it happens for something like 50 different lines or even more.

**Comment by kangarko** [comment]
Unfortunately we cannot translate the mode names since they are used internally in the plugin.

Regarding the second problem, can you send me your full line? In those strings where we have JavaScript compiler with ?: in it, it may well be that no inner apostrophes are possible, apologies for that. This is a limitation of Yaml file reader. But you can use the |- to turn this into a multiline string and then use double quotes " instead of ' and so use single quotes as apostrophes.

Regarding the third issue, I will look into it and remove the {person} in favor of JavaScript ?: code that you can translate into any language. Thank you!

**Comment by ElBananaa** [comment]
Hey! Thanks for the answer. Here's the line:
```
Not_Joined: '(self ? ''Vous n\''avez'' : ''{0} n\''a'') + '' pas rejoint ce salon. '' + (channelsPlayerCanLeave.isEmpty() ? '''' + (self ? ''Vous ne pouvez'' : ''Le joueur ne peut'') + '' quitter aucun salon.'' : (self ? ''Vous pouvez'' : ''Le joueur peut'') + '' quitter le(s) salon(s): {1}'')'
```
I used `\''` everywhere I would have to use apostrophes (Ik it's not the right format, this is just an easy way to find the parts I need to edit.

And here's the complete file (I already translated it)
https://pastebin.com/xBTDTFrG

**Comment by kangarko** [comment]
Okay thanks so you got it working like that right?

**Comment by ElBananaa** [comment]
> Okay thanks so you got it working like that right?

It works, but the apostrophe isn't shown, it shows `\''` ingame

**Comment by kangarko** [comment]
Will look into this but it is unlikely getting fixed since the system has its limits. You can use something like that:

````
Not_Joined: |-
  "" + 
  self ? "Vous 'avez'" : "{0}"
````

Something like this...

**Comment by ElBananaa** [comment]
> Will look into this but it is unlikely getting fixed since the system has its limits. You can use something like that:
> 
> ```
> Not_Joined: |-
>   "" + 
>   self ? "Vous 'avez'" : "{0}"
> ```
> 
> Something like this...

Hey! I just tried, I still have the same issue. I can't use apostrophes and the multiline still doesn't allow me to use the self ? variable everywhere.

EDIT: I finally made it work using multiline, this is an error on my end. Let me know when you'll remove the {person} variable :)
