### ISSUE TITLE
1.17.1: Join event error?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1562]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Thanks for all the amazing updates as of late. Sorry to report I found another error on the version from today.

Error: https://pastebin.com/2DDFS26h

**Comment by kangarko** [comment]
Sorry! Seems like the player was not yet synchronized at the time of this. I will make it so no extra variables are replaced when their data are missing. From my testing, the nick variable is working fine after this change: https://i.imgur.com/UEzqY8f.png Not sure what cases this wont workj

**Comment by Sikatsu** [comment]
Unfortunately I still seem to have join errors: https://pastebin.com/cEUx7XtV

**Comment by kangarko** [comment]
Where do you have "hasPermission" in your bungeecontrol red folder? In messages/ somewhere?

**Comment by Sikatsu** [comment]
```
group defaultimmortalpatreon
require sender script player.hasPermission("join.patreon") && player.hasPermission("immortal.default")
message:
- '&x&d&d&d&d&c&c[&x&6&6&f&f&8&8❤&x&d&d&d&d&c&c] &x&8&0&d&0&f&f&l{player}'
```

For this and other join/quit messages.

**Comment by kangarko** [comment]
Can't you use "require sender permission" instead? You can place two operators below each other

**Comment by kangarko** [comment]
Cannot reproduce. Not sure how the sender could have been null so I placed a non-null check to the operator logic for next version

**Comment by kangarko** [comment]
Or you can use 

`require sender script player != null && player.hasPermission("join.patreon") && player.hasPermission("immortal.default")`

**Comment by Sikatsu** [comment]
> Can't you use "require sender permission" instead? You can place two operators below each other

That didn't work, so someone in the discord advised my current approach which works fine other then the error. I could try your second suggestion tho!

**Comment by kangarko** [comment]
How did it not work? Any errors or just plainly did not evaluate the condition?

**Comment by Sikatsu** [comment]
It's been a while since, i'll share the initial discord message:

https://discord.com/channels/360404674219737100/755325303689052200/851769820047212557

**Comment by kangarko** [comment]
Thanks, I see now. Okay use the require sender script for your case with the non-null check.

**Comment by Sikatsu** [comment]
Awesome! Will do and thank you for your time!
