### ISSUE TITLE
1.16.5 : Can't use hexcolor

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1564]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

Hello,
I created a gui to set hex color to players.
So when a player click it execute : 
> '[console] chc color #f2e5d9 reset %player_name%'

but it doesn't apply the hexcolor to the player.
Player get theses permission : 
![image](https://user-images.githubusercontent.com/31826333/146474751-dfadbcaf-f570-41b7-a6de-d3f7466480bc.png)
So according to the wiki the player get the good permissions : 
> chatcontrol.hexcolor.#f2e5d9
> chatcontrol.hexcolor.f2e5d9
> chatcontrol.color.f2e5d9

But it doesn't apply the color I don't know why. What permission should they get to allow them to get hexcolor as color chat.
(not the permission to USE hexcolor, but always write using this hexcolor

**Comment by ElBananaa** [comment]
Hey,
I was completely unable to reproduce your issue on my end with the latest version of the plugin available on mcm.
Seems more like a permission setup issue on your side.
Here are the permissions required for this to work properly.
![image](https://user-images.githubusercontent.com/53318613/146485521-38dd5c9a-a35f-4a86-ba55-306a2fc68881.png)

Closing this, let me know if you need anything else.

**Comment by WarnDa** [comment]
I don't use channel, I use another plugin for chat.
But for all "basic" colors it works, except hexcolor.
And it's not an issue with other plugin, as an OP player I can get hexcolor, and player with permission to use &c &b can use it.

But hexcolor do not work
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7735490/debug.zip)



> Hey, I was completely unable to reproduce your issue on my end with the latest version of the plugin available on mcm. Seems more like a permission setup issue on your side. Here are the permissions required for this to work properly. ![image](https://user-images.githubusercontent.com/53318613/146485521-38dd5c9a-a35f-4a86-ba55-306a2fc68881.png)
> 
> Closing this, let me know if you need anything else.

**Comment by ElBananaa** [comment]
> I don't use channel, I use another plugin for chat. But for all "basic" colors it works, except hexcolor. And it's not an issue with other plugin, as an OP player I can get hexcolor, and player with permission to use &c &b can use it.
> 
> But hexcolor do not work [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7735490/debug.zip)
> 
> > Hey, I was completely unable to reproduce your issue on my end with the latest version of the plugin available on mcm. Seems more like a permission setup issue on your side. Here are the permissions required for this to work properly. ![image](https://user-images.githubusercontent.com/53318613/146485521-38dd5c9a-a35f-4a86-ba55-306a2fc68881.png)
> > Closing this, let me know if you need anything else.

If you don't use our channel system, i believe you can't use our color system neither. @kangarko correct me if i'm wrong ^^

**Comment by WarnDa** [comment]
I can, I used it for basic Colors (using /chc color menu) and it worked well
But manually applying hexcolors to people doesn’t work

**Comment by ElBananaa** [comment]
> I can, I used it for basic Colors (using /chc color menu) and it worked well But manually applying hexcolors to people doesn’t work

Well,
As I said, I was completely unable to reproduce your issue on my side, which makes me think this is either caused by a permission setup issue, or by another plugin conflicting with chatcontrol-red.

Anyways, let's wait for Kangarko to take a look at your issue.

**Comment by kangarko** [comment]
If I understand this correctly, your permissions won't work in the game chat. Since you're not using CCR to format the chat, we can't help you because we do not control this in that case — correct me if I am mistaken!

**Comment by WarnDa** [comment]
> If I understand this correctly, your permissions won't work in the game chat. Since you're not using CCR to format the chat, we can't help you because we do not control this in that case — correct me if I am mistaken!

But for basic minecraft color it works (&c, &b, &e) when using /chc color menu.
So it should work without issue for hexcolor

**Comment by ElBananaa** [comment]
> 

It does because 99,9% of the other plugins use basic color codes, and they all use the same format, while for hex colors, a lot of plugins still don't offer support for them, or simply don't use the same format, which may explain why basic color codes work, but hex ones don't. In this case, as Kangarko said, this would be unrelated to CHC-Red. ^^

**Comment by WarnDa** [comment]
> > 
> 
> It does because 99,9% of the other plugins use basic color codes, and they all use the same format, while for hex colors, a lot of plugins still don't offer support for them, or simply don't use the same format, which may explain why basic color codes work, but hex ones don't. In this case, as Kangarko said, this would be unrelated to CHC-Red. ^^

As OP it works without issue, but for non op it select another coloc (example &b)

Maybe it's not 100% related to chatcontrol but I don't know which plugin could change that

**Comment by ElBananaa** [comment]
> > If I understand this correctly, your permissions won't work in the game chat. Since you're not using CCR to format the chat, we can't help you because we do not control this in that case — correct me if I am mistaken!
> 
> But for basic minecraft color it works (&c, &b, &e) when using /chc color menu. So it should work without issue for hexcolor

Well, i'd take a look at plugins like EssentialsX/CMI, or any other plugin that somehow manages anything related to your chat.

**Comment by WarnDa** [comment]
I'll try with only chatcontrolred

**Comment by ElBananaa** [comment]
Good idea, as I said in my first message, I was unable to reproduce your issue on a fresh install with the right permission setup ^^

**Comment by WarnDa** [comment]
edit : the issue was in deluxechat (sorry for the long issue for nothing)
but at least problem is solved :)

**Comment by ElBananaa** [comment]
No worries haha, at least you found the cause of the issue, so this wasn't for nothing ;)
