### ISSUE TITLE
1.17.1: Ignore Command not functioning

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1565]
Hello, I notice that the /ignore command seems to do nothing at all. At first I thought it was somehow taking  a lower priority to Essentials /ignore command, but it isn't. I removed Essentials and tried /ignore, and it just doesn't recognize this as a valid command. I see the usage for it. 

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false
[debug (5).zip](https://github.com/kangarko/ChatControl-Red/files/7733684/debug.5.zip)

**Comment by kangarko** [comment]
Set Ignore.Enabled to true in your settings.yml to enable this feature :)
