### ISSUE TITLE
Add require server and ignore server on bungeecontrol-red

### ISSUE THREAD

**Issue by sxphirus** [kangarko/ChatControl#1567]
Currently there is no documented feature to send messages to a specific server on bungeecontrol-red and the only choice is per world, per region etc.

Would be nice if we could see a per server requirement especially for unique switch messages or if you want to ignore a specific server with join and leave messages.

I have looked through the documentation on [this](https://github.com/kangarko/ChatControl-Red/wiki/Messages) page and was unable to find anything similar.

**Comment by kangarko** [comment]
Can you give me an example? —Or do you just wish the messages/ folder have the operators "ignore/require server"? This is doable and fairly easily :)

**Comment by sxphirus** [comment]
> Can you give me an example? —Or do you just wish the messages/ folder have the operators "ignore/require server"? This is doable and fairly easily :)

Yep, that is exactly what i mean,
Example below;
Three servers, Red, Blue, Green

```
ignore sender server Green
require receiver server Green
```

Would broadcast messages from Blue and Red servers to only the Green server

**Comment by kangarko** [comment]
Added
