### ISSUE TITLE
[potential bug?] /ch join admin

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#157]
Opped player, fresh install of chc red (10.1.0) running:
mysql.yml -> `Enabled: false`
```
/lp group default permission set chatcontrol.channel.autojoin.standard.write
/chc tour start
/chc tour mothman
/ch join admin
```
yields `[x] Player '{player}' is not stored in our database.` even after player rejoins.

**Comment by kangarko** [comment]
Please see your console messages while having Show_Tips enabled. You also need other permissions for players to be kept in their channels: https://i.imgur.com/JELof34.png
