### ISSUE TITLE
1.18.1: Private message system seems to be buggy

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1570]
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

I was unable to use /reply or even /w xWoffel while the player was online.

![Screenshot_2](https://user-images.githubusercontent.com/5664135/146654920-f704fc82-6df2-4622-894d-e409bc95fd5c.png)

Console log: https://pastebin.com/nhX8yKGR

**Comment by Sikatsu** [comment]
Somehow have a feeling we have to type their full name, correctly including capitals. We can not use nicknames etc. Though I wonder if it also occurs because of the server load, or if this is a new bug on 1.18.1

**Comment by Sikatsu** [comment]
This is a very annoying bug, when a player messages me and I use /r it doesn't go to that player but to the last one I messaged hours ago. Then when I want to message the guy who just messaged me it often doesn't work unless I correctly write the players name. Is this a new bug on 1.18?? It is really annoying :(

**Comment by kangarko** [comment]
@Sikatsu thanks, we can continue here, thanks for emailing me to escalate this

**Comment by kangarko** [comment]
Closing, let's continue over email > let me know if changing Sync_Period solved that issue!
