### ISSUE TITLE
1.17.1: OPs no longer can be notified

### ISSUE THREAD

**Issue by dremovand** [kangarko/ChatControl#1571]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true
ChatControl version: 10.8.4

Hey!
I'm not entirely sure is that a bug or not.
But right after the last update OPs no longer can be notified by regular users or other OPs.

Looks like I'm missing permission or so, but can't figure out what especially I'm looking for.

Thanks! (And sorry, if I've picked the wrong place to ask questions)

**Comment by kangarko** [comment]
Sorry, what do you mean by "not getting notified"? Can you give an example, I cannot get this haha!

**Comment by ElBananaa** [comment]
> Sorry, what do you mean by "not getting notified"? Can you give an example, I cannot get this haha!

I believe they're talking about the `Sound_Notify` feature, however, I did run tests on both my test & my prod server, and I was unable to reproduce the issue.

**Comment by dremovand** [comment]
> Sorry, what do you mean by "not getting notified"? Can you give an example, I cannot get this haha!

Hey @kangarko! @ElBananaa actually explained what I meant :D Sorry for this miscommunication.

And what's interesting, this morning my administration team reported to me that everything works fine now, but I've didn't changed anything in the configuration files or anything that might affect the chat control plugin.

So I'm feeling a little bit awkward right now about starting this conversation :D

Thanks!

**Comment by kangarko** [comment]
Great to hear, let us know below if we need any more help!

**Comment by dremovand** [comment]
Hey! I'm here again :D

So, the problem isn't solved, but now, I've found exactly why it happens.

Any player can't notify the target when the target is in spectator mode.
I've tested it on the latest Paper build (402 for now) and with only the necessary plugins to exclude that this issue is not caused by a third-party plugin.

Here are screenshots when the target is OP, and target without OP:

OP:
![Screen Shot 2021-12-25 at 12 15 31 PM](https://user-images.githubusercontent.com/33837316/147378044-f0c56d3c-cd18-456c-b38e-e26fea5f196a.png)

Not OP:
![Screen Shot 2021-12-25 at 12 16 56 PM](https://user-images.githubusercontent.com/33837316/147378047-2a22db45-7003-483a-94a2-9ac0978c5346.png)

Additional env info:
Minecraft Version: 1.17.1 - Paper build 402

Plugins:
NashornPlus - 1.1.0
ProtocolLib - 4.7.0
Vault  - 1.7.3-b131
LuckPerms - 5.3.89
ChatControlRed -  10.8.4

Thanks!

**Comment by ElBananaa** [comment]
> Hey! I'm here again :D
> 
> So, the problem isn't solved, but now, I've found exactly why it happens.
> 
> Any player can't notify the target when the target is in spectator mode. I've tested it on the latest Paper build (402 for now) and with only the necessary plugins to exclude that this issue is not caused by a third-party plugin.
> 
> Here are screenshots when the target is OP, and target without OP:
> 
> OP: ![Screen Shot 2021-12-25 at 12 15 31 PM](https://user-images.githubusercontent.com/33837316/147378044-f0c56d3c-cd18-456c-b38e-e26fea5f196a.png)
> 
> Not OP: ![Screen Shot 2021-12-25 at 12 16 56 PM](https://user-images.githubusercontent.com/33837316/147378047-2a22db45-7003-483a-94a2-9ac0978c5346.png)
> 
> Additional env info: Minecraft Version: 1.17.1 - Paper build 402
> 
> Plugins: NashornPlus - 1.1.0 ProtocolLib - 4.7.0 Vault - 1.7.3-b131 LuckPerms - 5.3.89 ChatControlRed - 10.8.4
> 
> Thanks!

Hey,
Thanks for reporting this!
Kinda makes sense now: I believe kangarko checks for the spectator status/mode to detect vanished players, which would explain why it happens in this case.
Unfortunately, you'll have to wait since Kangarko (and the most of the team working with him, me included), are taking a break for holidays.
(Also, remove NashornPlus since it isn't needed anymore for 1.17+ servers ^^)

**Comment by kangarko** [comment]
It's intended. We ignore spectating players to prevent them from being discoverable by the radius limit.
