### ISSUE TITLE
1.18: Where can I enable Custom Death Messages?

### ISSUE THREAD

**Issue by AddyPete** [kangarko/ChatControl#1572]
Where can I enable Custom Death Messages? and also where can i edit it

Minecraft Version: 1.18
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> Where can I enable Custom Death Messages? and also where can i edit it
> 
> Minecraft Version: 1.18 MySQL: false BungeeCord: false

Hey,
To enable our death message system, take a look at the settings file. Look for the `Messages.Apply_On` part.
![image](https://user-images.githubusercontent.com/53318613/146692419-a02d4f67-60f1-47fb-ad86-4630f2ab83c8.png)

To edit death messages, take a look at the `messages/death.rs` file. You can find more informations on how to fully edit these messages on our wiki pages:
- https://github.com/kangarko/ChatControl-Red/wiki/Messages
- https://github.com/kangarko/ChatControl-Red/wiki/Rules

I believe the default file also includes a few examples with comments to explain how to do so.
