### ISSUE TITLE
Message Reporting System

### ISSUE THREAD

**Issue by LyrinoxTechnologies** [kangarko/ChatControl#1573]
Hey Kangarko!

Love CCR!

But I was wondering if you guys could add a message report feature? I for one, have a multi-lingual server and sometimes the filter misses when foreign swears are mixed with English text. My players have requested the ability to report a players message(s)

This would be beneficial to everyone using CCR as it would remove the need for a chat reporting plugin as well as make it possible to aggregate all of a player's messages into a log file upon report for future review.

This can be done in a similar way to deleting messages in chat. Simply add a (!) or something to the start of all messages and a player can click the (!) to open a GUI with reasons for reporting the message. IE: Threats, Swearing, Hate Speech etc

**Comment by kangarko** [comment]
Thanks. However we feel that the plugin is already too complicated and it would just open doors to new bugs and slow down the code. 

If you need a report system, use a third party plugin. Or have players use the /mail function — you can create a command alias in command.rs file to run /mail send to all server admins at the same time.
