### ISSUE TITLE
1.18.1: Bungee SQL question

### ISSUE THREAD

**Issue by mav2020** [kangarko/ChatControl#1574]
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

I know that CCR "require a database connection to synchronize data between your network effectively." My question is whether or not all servers need to share the same mysql database? I have assumed so, but on my new test server I am using a separate database and haven't noticed any issues. What is missing by doing separate databases? Thanks.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.18.1 MySQL: true BungeeCord: true
> 
> I know that CCR "require a database connection to synchronize data between your network effectively." My question is whether or not all servers need to share the same mysql database? I have assumed so, but on my new test server I am using a separate database and haven't noticed any issues. What is missing by doing separate databases? Thanks.

Hey,
I'm pretty sure MySQL is only needed if you want to sync chc-red data between your servers.
If you don't want to use this feature (so users won't keep their nicks, tags, mute status, and chat won't be synced, as example), this isn't needed at all ^^

**Comment by mav2020** [comment]
> 
> Hey, I'm pretty sure MySQL is only needed if you want to sync chc-red data between your servers. If you don't want to use this feature (so users won't keep their nicks, tags, mute status, and chat won't be synced, as example), this isn't needed at all ^^

Can you please further explain "chat won't be synced"? This is the part I am unsure of.
Mute might be an issue (recently stopped using Litebans for mutes since CCR is much better at that).
Nicks not being shared is a plus to me.

**Comment by kangarko** [comment]
Not all servers need to share the same mysql database. But then you'll get different player data such as their nicks etc, if you want that then you can have different setups.

Going to see the code just to be sure tmr.

**Comment by mav2020** [comment]
Thank you for checking the code (tomorrow). If it is just their nicks, tags, and mute, then I just need to come up with a mute solution.
From what I can tell, all the chat formats and rules need to be on every server anyway.

**Comment by ElBananaa** [comment]
> > Hey, I'm pretty sure MySQL is only needed if you want to sync chc-red data between your servers. If you don't want to use this feature (so users won't keep their nicks, tags, mute status, and chat won't be synced, as example), this isn't needed at all ^^
> 
> Can you please further explain "chat won't be synced"? This is the part I am unsure of. Mute might be an issue (recently stopped using Litebans for mutes since CCR is much better at that). Nicks not being shared is a plus to me.

By "Chat won't be synced" I meant that you can't communicate with other servers if you don't use the same database.
I'm not 100% sure about that tho, since I believe global chat simply requires plugin messaging.

**Comment by kangarko** [comment]
If you want to have 2 servers on your network use a different database, you must make sure these 2 servers share the same database. Otherwise we will override data from one server to another and vice versa.

When you join a channel, we save it in your database.

You will be able to communicate with other servers using another database as long as channel names as the same, but I cannot guarantee how reliable it will work since I never tested

**Comment by mav2020** [comment]
Thanks.
