### ISSUE TITLE
1.18.1 Ignored Servers not working as expected on BungeeControlRed

### ISSUE THREAD

**Issue by sxphirus** [kangarko/ChatControl#1577]
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

When using this example for switch messages on bungeecontrolred it does not work as expected alongside the server blacklist in the settings.yml

switch.rs
```
group main_message
ignore sender perm chatcontrol.silence.switch
prefix &8[&d>&8]
message:
- &e{player} &fhas switched from &7{from_server} &fto &7{to_server}
group bypass_main_message
require receiver perm chatcontrol.bypass.silence.switch
require sender perm chatcontrol.silence.switch
prefix &8[&d>&8]
message:
- &e{player} &fhas switched from &7{from_server} &fto &7{to_server}
```

settings.yml
```
  Ignored_Servers:
  - 'Hub'
```

When moving from Cloud --> Hub --> Pod

`Cloud --> Hub`
No message is displayed (expected behavior)

`Hub --> Pod`
Message is displayed but shows incorrect server names (shown below)
![image](https://user-images.githubusercontent.com/7299223/147107457-50bef584-02a2-41b2-9dae-ab4129392ffa.png)

**Comment by kangarko** [comment]
Starting the next version, please use the 4 new variables instead of the Ignored_Servers list: https://github.com/kangarko/ChatControl-Red/wiki/Messages#ignore-sender-server-require-sender-server-ignore-receiver-server-require-receiver-server

Thanks!
