### ISSUE TITLE
Nick Gradient Custom

### ISSUE THREAD

**Issue by WinTPo** [kangarko/ChatControl#1578]
Ability to use Hex colors in rules (like a placeholder).  
Nickname does not change to another because the Hex code will be replaced with a color before execution
![image](https://user-images.githubusercontent.com/54418278/147112574-a12548df-ea32-4c47-8487-3a77de31812a.png)

I tried another option for displaying a custom gradient in chat, it didn't help either. Placeholder does not work if there is a placeholder in it
![image](https://user-images.githubusercontent.com/54418278/147112703-afa07633-0aba-41ed-9a82-67b82e27f90d.png)

**Comment by kangarko** [comment]
Thanks for reporting, no we do not support gradients this way right now, this is something I can change when I have time in the future
