### ISSUE TITLE
Chat Control Not Working

### ISSUE THREAD

**Issue by Mutim** [kangarko/ChatControl#158]
Hey! I love this plugin, but it doesn't work properly when configuring the files. I get a "Red Plugin" by typing essentials /pl when I change the Messages.yml. I'll link a pastebin of my file. Maybe you, or someone else can help me out. Do you think it could not working properly with essentials? I really need help on this. I had a bot, and spammer come on and piss everyone off the other day. Really rely on this plugin. Thank you in advance!

http://pastebin.com/GCwx2VgX

**Comment by EvilOlaf** [comment]
Check your console output to see what's wrong.

**Comment by Mutim** [comment]
well, i've obviously done that. There is no output in the console. Just in game. It outputs, "Sorry, I couldn't find player: $player" any help? It was only broken after the update. Please help. Thank you.

**Comment by EvilOlaf** [comment]
If there is something wrong with your configuration it should tell you in console when doing a server restart.  Did you try this?

**Comment by Mutim** [comment]
These are the only errors in console. Libs is out of date, Votifier needs to be removed, SQLite is unimportant, and the ASkyBlock  Pig spawner doesn't work. Other than that, the console shows that everything else should be working. No warnings for ChatControl either. Nothing wrong in the config. I made the config just like the examples. I think I pasted it. It works in an online parser. Everything should be fine. But it's not. I can't customize anything without it messing up. I can plug it in, and it runs. Just when I go to configure it, it messes up. Have you put more thought into it? I'm still trying as well to fix it. Looking on forums, google, nothing's coming up though. =/ Thanks for the responses. ASkyBlock dev isn't even responding after a week. haha.

[12:02:36 ERROR]: [Votifier] Votifier did not initialize properly!
[12:02:37 ERROR]: Error occurred while enabling LibsDisguises v9.1.2 (Is it up to date?)
[12:02:39 ERROR]: WARNING: you seem to not be using the Xerial SQLite driver.  See ORMLite docs on SQLite: http://ormlite.com/docs/sqlite
[12:02:40 ERROR]: WARNING: you seem to not be using the Xerial SQLite driver.  See ORMLite docs on SQLite: http://ormlite.com/docs/sqlite
[12:02:52 ERROR]: [ASkyBlock] Problem parsing shop item from minishop.yml so skipping it: MOB_SPAWNER
[12:02:52 ERROR]: [ASkyBlock] Error is : For input string: "PIG"

**Comment by kangarko** [comment]
Please provide us startup log. Feel free to send it privately via PM at spigot forums.

**Comment by Mutim** [comment]
Hey kangarko. I've sent a conversation request. I'll resolve this one if we can get it working. Thanks!

**Comment by CrazyDutchBoy** [comment]
Have you enabled debugging?

`# Enable if you are having issues, will tell you detailed info in the console.
Debug: false`

**Comment by Mutim** [comment]
I have. What I didn't do though, and i'm kicking myself in the head about it. I needed to use the onlince yaml parser. I found a problem with the custom welcome message where there was no ' after the text. screwed the whole thing up. *facepalm* thank you both for helping with it!

**Comment by Mutim** [comment]
Oh my god. Thank you. i'm kicking myself in the head over this still. I forgot to put a ' at the end of a custom welcome message. *facepalm* using the online yaml parser I found that. (I could have sworn I used it) i guess not. Thank you so much again! Still the best chat control plugin available!

**Comment by kangarko** [comment]
No problem it happens! I have responded in the forums. Feel free to write me if you have any more questions.
