### ISSUE TITLE
Add support for a /softmute command

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#1580]
Since updating to ChatControl Red, softmute commands from plugins such as GriefPrevention no longer work. I am aware that there is a [tutorial](https://github.com/kangarko/ChatControl-Red/wiki/Soft-Mute) on setting up a similar system in ChatControl Red, however this system isn't a perfect replacement for GriefPrevention's softmute.

Ideally, a softmute feature would accomplish _all_ of the following:
- Prevent messages from softmuted individuals from appearing in the standard chat
- Give no indication to the softmuted individual that their message is hidden
- Allow softmuted users to still see the messages of _other_ softmuted individuals
- Allow staff to see softmuted messages, but given indication they are muted
- Allow staff to send a softmuted message, whether by softmuting themselves or by use of a prefix

Theoretically, this should all be possible in the current version of ChatControl Red, but I've been unable to get it to work 

The method on the wiki works fine, but does not allow softmuted users to see messages of other softmuted users. This quickly becomes a problem when you have a group of possible trolls you need softmuted (thus breaking condition 2). I'm sure you could get around this using `then notify` to notify softmuted users, but there would need to be a way for it to preserve [group formats](https://github.com/kangarko/ChatControl-Red/wiki/Formats), and I'm unsure if this is possible in the current version of ChatControl.

After this didn't work, I tried creating a "softmuted" channel. This channel used the same format as my standard chat (preserving group formatting) while allowing softmuted players to see messages from other softmuted individuals. Staff can also spy into this channel, or send messages into this channel using `/ch send`. 

So far so good; it accomplishes everything listed above! 
However, in order for this method to work well, there needs to be a way to move a player--using a command--to the softmute channel in write mode, while keeping them in read mode within the standard channel. Additionally, there needs to be a command to unsoftmute a player, moving them out of the softmute channel _completely_, and allowing them to write into the standard channel again.

This is where this method starts falling apart. Due to #1488 and #1522, you cannot reliably move players this way. I've made `/softmute` and `/unsoftmute` commands that on-paper should move players correctly, but in practice do not. Often players are left without a channel to speak in, or don't have their channels switched at all (despite the command output saying they were). Running the command twice seems to "fix" it most of the time, but I still need to check `/ch list` to make sure.

So far, I only have one channel players can write into (standard); all other channels are for admins. I'm not sure how much worse this issue would become if there were other channels a player could write into (roleplay, or party chat, for example).

----

1. How it would benefit others? 
Having the ability to softmute unvetted/suspicious players is a god-send in moderation. It allows you to keep the chat clean, without making new players feel un-welcomed. If a player spams, says a slur, or breaks some other rule, you don't need to worry about players seeing this.

2. What would happen if we won't implement this feature? How's your server being affected?
I run a server for marginalized communities; due to that, we get a larger-than-average number of trolls. Unfortunately, /softmute is a nearly essential command that makes moderation so much less of a headache. 

----
For reference, I've attached my full ChatControl configuration.

Instead of using commands.rs, I've used the build in commands.yml file. (Purely for the tab-complete. I've not noticed any functional differences.) However, I included the commands.rs file anyway as it contains code for previous softmute attempts.

Any help would be appreciated. I could live without a built-in /softmute system if I were able to get a reliable channel-based one to work.
[CHCSoftmuteSettings.zip](https://github.com/kangarko/ChatControl-Red/files/7765130/CHCSoftmuteSettings.zip)

**Comment by kangarko** [comment]
Thanks!

What if I added chained expressions to /channel set command?

Such as that you can do `/channel set kangarko standard read|softmute write` or something like this. It would solve the #1522 ticket and you could use this reliable in your rules for your command.

**Comment by BakiDance** [comment]
If that works, it would solve the biggest issue I've been having with the plugin. Thank you so much for the quick response, and happy holidays!

**Comment by kangarko** [comment]
Added to next version!
