### ISSUE TITLE
/list formatting

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1583]
Hello ElBananaa & kangarko
Sorry for the mass of questions, I'm finally migrating from 1.12.2 to 1.17!

Looks like there was at one point formatting for list as its in the format folder, but in the main config its very limited in formatting.
The settings based list is very limited, I cant even show how many players are on the server.

Is the reason that its not in the formatting files because of the need to loop through users based on group?

could a simple solution be to use placeholders?

I would like to show player count like 30/100 online.
- Separate staff from players, and show the group they belong to before their list.
- Be able to use placeholders, so I can show crews players are in
- Click events, separate click events for clicking crews to clicking a username

All this would be possible in the formats folder, is it possible to set that up? I tried setting `list.Format` to list, but it just wrote list for each player haha

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Sorry, we had to cut back on the /list feature set and replace support for formats with as single format line. There was always weird data sync issue and large networks got packet overflow, I don't have the resources for this atm. I recommend looking for a bungee-only plugin operating on BungeeCord to show a player list.
