### ISSUE TITLE
From / To server operator 

### ISSUE THREAD

**Issue by sxphirus** [kangarko/ChatControl#1584]
Alongside my previous suggestion, would be cool if it was possible to ignore / require a certain server that the user is moving FROM and the user is moving TO

Example:
3 servers, red, blue, green

```
ignore from blue
require to red
```

Will only send a message if the user is coming from green to red

```
ignore from green
```

Will only send a message if the user is coming from red or blue, and not coming from green.

Thanks! Is useful when the server would like to cancel out switch messages from hub / limbo servers

**Comment by TheIntolerant** [comment]
Hey,

I believe this was recently implemented within BungeeControl.
Please refer to [https://github.com/kangarko/ChatControl-Red/wiki/Messages#ignore-sender-server-require-sender-server-ignore-receiver-server-require-receiver-server](https://github.com/kangarko/ChatControl-Red/wiki/Messages#ignore-sender-server-require-sender-server-ignore-receiver-server-require-receiver-server) for information about this.

**Comment by kangarko** [comment]
I believe also that was already covered, let us know below if I can help you with anything else :)

**Comment by sxphirus** [comment]
There is no way for the variable to respect the server that the user has came from
switch.rs
```
group main_message
ignore sender server Hub
ignore receiver server Hub
message:
- &f巘巆巆&x&c&f&b&3&a&5{player} &x&f&f&f&3&e&dhas moved from &x&c&f&b&3&a&5{from_server} &x&f&f&f&3&e&dto &x&c&f&b&3&a&5{to_server}
```
![image](https://user-images.githubusercontent.com/7299223/147611084-ef9e3745-bd6a-4dd4-81b6-3b307149820d.png)

Servers going from Pod --> Cloud --> Hub --> Pod
Receiving player is on server Pod

**Comment by kangarko** [comment]
I see. We already have edited the current server of player from Pod to Cloud. Not having time for this right now but I can have a look in the future, noted.
