### ISSUE TITLE
An error is displayed on the bungeecord console.

### ISSUE THREAD

**Issue by geumu** [kangarko/ChatControl#1585]
**Bukkit**: Catserver 1.12.2
**Bungeecord**: true
**Mysql**: true
**Plugin**: BungeeControl-Red-3.8.7
**Explanation**: An error is displayed on the bungeecord console.
**Log**: https://drive.google.com/file/d/10rDSzU18R8UjGvZ3G8ks4oxsM6HS6OAV/view?usp=sharing

**Comment by ElBananaa** [comment]
Hey,
According to the error you are using special characters that aren't supported in your config.

Please make sure everything is setup correctly.
Also please send us your bungeecontrol folder so we can have a look (use /chc debug to generate a zip file and automatically remove any credentials from it)

**Comment by kangarko** [comment]
Use https://yaml-online-parser.appspot.com/ to paste content of your configs there to check for syntax errors. If you're using a language other than English, you may need the UTF8 startup flag: https://bukkit.org/threads/startup-script-flag-for-enabling-utf-8.171342/
