### ISSUE TITLE
Gradient text colour

### ISSUE THREAD

**Issue by Rick-Sanchez-C** [kangarko/ChatControl#1586]
I saw your plugin dont do automatic gradient messages, i make a simple function to do that without problems (with 100 character limit), i think can be useful and u only need to implement my function or if u dont want to do that, ¿can u guide me to make an addon for your plugin?

**Comment by kangarko** [comment]
Hey! You can just import ChatControl.jar directly using a build tool such as Maven (use systemPath dependency type). Then just use the ChatControlAPI class or listen to the ChatChannelEvent to modify the message there.
