### ISSUE TITLE
Suggestion: SpongeForge/Fabric/Velocity Compatibility

### ISSUE THREAD

**Issue by LyrinoxTechnologies** [kangarko/ChatControl#1587]
Hey Kangarko!

Once again just gotta say I love you dude! Such awesome plugins!

However, I've recently started work on a modded network and would love to either see a fabric/spongeforge compatibility and perhaps some features added to allow further customization of chat. Like perhaps allowing custom fonts so we could make our own fonts? Or perhaps allowing resource packs to change CCR prefixes and such? Maybe allow prefixes be images rendered in chat?

If it's hard to imagine what I'm referring to, please look into Mineclub. I feel like CCR should be able to do something similar, especially if it's fabric compatible.

But mostly, I just want to use CCR on SpongeForge and Fabric, is there any plans to make them compatible?

**Comment by ElBananaa** [comment]
Hey,
Chatcontrol works fine with plugins using custom fonts/emojis/images. These things are unrelated to chatcontrol, as the changes need to be done in a resourcepack. As example, if you wish to use an image as a prefix, you simply need to make your own ressourcepack, and replace a character with the image, then use this character in the chat.

So basically, the whole "further customizaton" part is fully unrelated to our plugin. To do this, you can either make your own resourcepack manually, or use a plugin such as ItemsAdder, Oraxen, NamePlates, EmojiChat etc...

Here's a reddit thread which gives you more informations about this, and how to do it: https://www.reddit.com/r/admincraft/comments/llrgty/does_anyone_know_how_to_put_a_image_on_the/

**Comment by kangarko** [comment]
Thanks for your feedback and thanks to Banana for answer!

My time is very limited since I'm the only dev of 5 plugins at the moment, I unfortunately don't have enough resources to port it to Sponge or another mod - thank you for your understanding.
