### ISSUE TITLE
ping.yml slight improvement and bug

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#159]
```yaml
# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand"
Key: ping
```
should have something like this instead:
```yaml
# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Oh dear, my ping is [ping]."
Key: ping
```

sidenote, this is abit confusing and I'm pretty sure it's broken:
```yaml
# The value the key will be replaced to.
# This uses JavaScript and must return a boolean value.
Value: player.getHandle().ping
```
ping isn't a boolean, that could explain why [ping], doesn't actually work.

Actually most of the variables have this issue. even [player_is_vanished]

**Comment by kangarko** [comment]
Thanks, I will change those. However, we fetch comments from a singular file for variables so it is not possible to customize those individually.
