### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by LordYarkan** [kangarko/ChatControl#1593]
Hi
1- Can gradients be used in the names? so to speak, from red to yellow and then to green. I mean 3 colors but gradient.

2- How to separate chats by worlds?

**Comment by ElBananaa** [comment]
Hey,

- You can use gradients in formats, so you can tweak the plugin to give specific players/ranks a name with a gradient, however you can't have more than 1 gradient per format, unless you use https://api.extendedclip.com/expansions/gradient/ directly.

- To separate chat by worlds, go in `settings.yml > Channels.List` and play around with the `Range` and `Range_Worlds` settings (You can read explanations about how these 2 operators work in the comments above the config part).

As example, to allow players on the same world to see each other messages no matter the distance, set `Range: '*'`. If you want this to apply to all worlds (so players in the same world, will be able to see each other messages, no matter the distance, and no matter the world), also set `Range_Worlds: '*'`

If you want to allow players in the world `world` and in the `world_nether` world to see each other messages, then set `Range: '*'` and `Range_World: "world, world_nether"`.

**Comment by ElBananaa** [comment]
I'm closing this. Let me know down below if you need anything else! ;)
