### ISSUE TITLE
Request: Allow DiscordSRV embed messages to be shown with discord integration enabled.

### ISSUE THREAD

**Issue by TechRoot** [kangarko/ChatControl#1595]
Morning,

Currently, it is not possible to use 
```
Messages:
 
  # What aspects of messages should be enabled?
  # Options: join, quit, kick, death, timed
  #
  # If you have another plugin handling join/quit etc. messages, remove them from list below.
  # If you want to hide those messages, leave them in Apply_On and empty your messages/ .rs files.
  Apply_On:
  - 'join'
  - 'quit'
  - 'kick'
  - 'death'
  - 'timed'
```
 On a Bungee network and , at same time, allow DiscordSRV to use their default format to announce deaths, joins, advancements and some other texts that this plugin shows on an **embed format**.

We have to chose between custom ingame messages or having our Discord with DiscordSRV embed ones. As, the only way of make both working is to disable DiscordSRV integration, but this also disable global chat forwarding between servers to Discord.

I really do think this would be useful to the entire community, and hope it gets additioned, as if not, BungeeCord networks using ChatControl will not be able to use the entire functionalities of DiscordSRV among with the ChatControl ones.

Thanks.

**Comment by kangarko** [comment]
Thanks, this is something I can have a look for later, unfortunately for at least this whole month I am unable to take on larger feature suggestions.

**Comment by snhnry** [comment]
@TechRoot You can sort of have your cake and eat it too.  Remove the join/leave entries under the Discord messages section in ChatControl, then in the DiscordSRV config set `DiscordChatChannelDiscordToMinecraft: false`  This will disable duping of chat messages while still maintaining the nice, embedded messages from DiscordSRV.  You can do this with multiple servers as well if you are doing Bungee.
