### ISSUE TITLE
1.17.1: Private Messsage on Network Is Broken

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl#1596]
Players can't see private messages from different servers after upgrading ChatcontrolRed from 10.8.5 to 10.8.9.

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by waseric** [comment]
Same issue after upgrading from ChatControlRed 10.8.8 to 10.8.9.

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Reverting to 10.8.8 resolves issue.  It was not necessary to revert BungeeControl-Red from 3.8.9 to prior version (3.8.8)

Note:  We have not yet taken the action to clear ChatControl_Log database as indicated in the 10.8.9 update:
"Solved an error in /chc log anvil when storing anvil rename logs. You will need to clear your ChatControl_Log database for it to take changes."
Unclear if this is related.

**Comment by kangarko** [comment]
Thanks, will be patched tonight!
