### ISSUE TITLE
1.16.5 Log file doesn't support russian letters

### ISSUE THREAD

**Issue by honnisha** [kangarko/ChatControl#1597]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

![Untitled](https://user-images.githubusercontent.com/7021713/147858570-97ecad5a-b006-43eb-b389-24cd6179e8c0.png)

Logs only recognize english letters and numbers.

**Comment by kangarko** [comment]
No sorry it cannot due to a vulnerability which crashed the in game json parser, we're still looking at a solution and will patch this when I find one. If you're a dev I can add you to our source, feel free to help.

**Comment by honnisha** [comment]
Sorry for delay. Do Russian characters а-яА-Я cause an error? I would like to help if I can reproduce this crash

**Comment by kangarko** [comment]
Not per say but because they use a wider unicode letter set. I can investigate later but I am busy right now.
