### ISSUE TITLE
Create channel toggle command that auto tabs without havintg to hack it

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1599]
Ive seen this: https://github.com/kangarko/ChatControl-Red/wiki/Channels
and this https://github.com/kangarko/ChatControl-Red/wiki/Tab-completing-custom-commands

Ive set both up but it just doesn't work, commands.yml just runs the command as its set, chatcontrol isn't taking over.

This should just be part of the plugin, have a section in settings.yml under Channels.List where you have a toggle setting where we set the command we want to toggle that channel, then it  can auto be tab completed by Chat control Red, not require people to "code" their own toggle and not mess with commands.yml, its a very basic feature I think should just come built in.

**Comment by ElBananaa** [comment]
I don't understand why the command should be tab-completed by CMI? Using a library that would allow everyone to tab-complete it, such as Brigadier would make more sense, doesn't it?

**Comment by TomLewis** [comment]
> I don't understand why the command should be tab-completed by CMI? Using a library that would allow everyone to tab-complete it, such as Brigadier would make more sense, doesn't it?

That was suppose to say ChatControl red, just working with multiple plugins today.

**Comment by TheIntolerant** [comment]
Hey, can you post examples of your rules from chatcontrol as well as what you have set in commands.yml

Also can you confirm any possible changes made with Listener Priorities for chatcontrol etc.

So I can test on a fresh setup.

Thanks.

**Comment by TomLewis** [comment]
Its exactly whats in the wiki.

`Chat_Listener_Priority: HIGH` the default again. 

I have banmanager that has to work with priority which I'm yet to check actually works with the priority of chatcontrol, I also have SimpleClans which has chat features that will also need checking work with both banmanager & chatcontrol.

I assume Banmanager needs to be highest? as that deals with mutes across the server, then chatcontrol then simpleclans?

**Comment by kangarko** [comment]
Thanks for suggesting. However I am very careful about taking on feature requests for which I don't have enough skillset, because the plugin's stability stability takes place before expanding our feature set. The wiki article was provided by @TheIntolerant :)

By the way, you could have a look at the recently improved /channel set command you could use in your alias or scripts. If there's anything else we can help you with, just let us know below.
