### ISSUE TITLE
1.16.4 MySQL | Prefix issue with Rule Creator

### ISSUE THREAD

**Issue by memetrollsXD** [kangarko/ChatControl#16]
![image](https://user-images.githubusercontent.com/27217031/98815096-f1dbc080-2426-11eb-81c3-64307de9498f.png)

I'm guessing the {success_error} isn't a (visible) part of the message

**Comment by memetrollsXD** [comment]
![image](https://user-images.githubusercontent.com/27217031/98815813-0076a780-2428-11eb-8073-34cc2bac72b3.png)
This also happens with {prefix_warn}

**Comment by kangarko** [comment]
Thanks will be fixed shortly!
