### ISSUE TITLE
Variables have incorrect colouring added

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#160]
Fresh install of 10.1.0,
https://gyazo.com/f6958d7d1dc69cd25e93ef9414568b83
you can test with:
```
[item]
test [item]
```
the first will send a white item name (which should be Grey (am in default `/ch join standard`)) and the second message yields Grey text.
Paper 1.16.4 version 277

**Comment by kangarko** [comment]
Thanks, will get solved.
