### ISSUE TITLE
Nicknames not working for chat.

### ISSUE THREAD

**Issue by SlothUS** [kangarko/ChatControl#160]
```
        # Default chat format.
        Message_Format: '{pl_prefix}{nick}&f:{pl_suffix} {message}'
```

{nick} does not work for nicknames so I was wondering if anything does.

I'm using Essentials for nicknames at the moment. It would be awesome if you guys could help out with this problem.

**Comment by SlothUS** [comment]
So I disabled interactive chat and it fixed both of my problems. Any way to fix this with interactive chat on?

**Comment by kangarko** [comment]
Please post in the channel for the pro version.
