### ISSUE TITLE
Implement /ignore for Pressing P for clients.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1602]
Theres a built in mute function in Minecraft now, press P to "hide messages" from players, all we need is for this to /ignore them and unignore when toggled, really simple, massive easy way to use ignore then!

**Comment by ElBananaa** [comment]
> Theres a built in mute function in Minecraft now, press P to "hide messages" from players, all we need is for this to /ignore them and unignore when toggled, really simple, massive easy way to use ignore then!

Hey,
Unfortunately, this is not "really simple". The social interaction menu implemented in 1.16+ is entirely client-side, which means that there's absolutely no way for a plugin to interact with it.

Here are a few screenshots taken on paper's discord server explaining this a little bit further:

![image](https://user-images.githubusercontent.com/53318613/147888893-d642450f-41e8-4e40-a5d0-081545b62949.png)
![image](https://user-images.githubusercontent.com/53318613/147888908-089baa22-3030-48c5-a39c-aadd8ab99305.png)
![image](https://user-images.githubusercontent.com/53318613/147888834-64ddcf43-961d-4277-b475-335c10587616.png)

**Comment by kangarko** [comment]
Thanks Banana, I learned something today as well!

**Comment by TomLewis** [comment]
You may not be able to change it, but does it send any data packets to the server? or is it 100% client side.

**Comment by kangarko** [comment]
Honestly haven't had the time to look into this, looks much of this is client side yet (I might be wrong).

**Comment by ElBananaa** [comment]
> You may not be able to change it, but does it send any data packets to the server? or is it 100% client side.

Afaik, this is 100% handled client-side, with absolutely no data sent to the server. I believe they were requests to make it so this could be used/setup server-side but Mojang didn't pay attention to them.

**Comment by TomLewis** [comment]
> Afaik, this is 100% handled client-side, with absolutely no data sent to the server. I believe they were requests to make it so this could be used/setup server-side but Mojang didn't pay attention to them.

Oh man, thats such a bummer! I was thinking of all sorts of awesome ways we could have changed/used this menu! 
Is there a feedback post that I can give a thumbs on the Microsoft feedback website for it?

**Comment by ElBananaa** [comment]
> > Afaik, this is 100% handled client-side, with absolutely no data sent to the server. I believe they were requests to make it so this could be used/setup server-side but Mojang didn't pay attention to them.
> 
> Oh man, thats such a bummer! I was thinking of all sorts of awesome ways we could have changed/used this menu! Is there a feedback post that I can give a thumbs on the Microsoft feedback website for it?

I belive the suggestion was made on the Mojang's bug report blog (since, if I remember correctly, users thought this was a bug at first). I can't find the link back but try to do some research ^^
