### ISSUE TITLE
Please change /reply functionality back to how it was

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1603]
I noticed that /reply now sends a message to the last player you messaged, rather then the last player that messaged you. Can this please be changed back or can you give us the option too?

**Comment by kangarko** [comment]
I'll add a toggle for this in the next version. Next time please avoid duplicating tickets in email/here for clarity thank you.

**Comment by Sikatsu** [comment]
Sorry for that, at first I thought it was a bug when I said it by email, later on I heard it was changed with a reason so I wanted to move it here as a request.
