### ISSUE TITLE
Add an option to disable spy feature + local /cc clear

### ISSUE THREAD

**Issue by nivcoo** [kangarko/ChatControl#1604]
Hello, i already use deluxechat spy can you add an option like Pro edition to disable spy section ? 

Also can you clear only the actrual server when we execute /cc clear (Not all network). Thx

**Comment by kangarko** [comment]
Set Spy.Apply_On to [] to effectivelly disable the spy feature. I will consider local clear command but so far you're the only one requesting it. Thanks!

**Comment by ElBananaa** [comment]
I do think that adding an argument to only clear the chat of a single server (and even a single channel) would be a great idea.

This is something that has been requested multiple time, and with Velocity support coming (I hope soon), this will definitely be something that a lot of users will find useful ^^
