### ISSUE TITLE
1.17.1: showitem and [item] problem.

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#1605]
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

I display items when I use showitem, but Discrod will display $showitem243354955$. In addition, I use the CHC preset [item] to fail to display the name of the ECOEnchants. It will directly control the whiteness. For example, CMI can display many methods I tried. But it cannot be resolved.
![image](https://user-images.githubusercontent.com/52900334/147899843-5186886e-21fe-42f7-b8a1-563082f56af5.png)

**Comment by BearLeonLight** [comment]
Also can you add
https://www.spigotmc.org/resources/interactivechat-discordsrv-addon-show-items-and-invs-on-discord-preview-discord-images-in-game.83917/
support?

**Comment by kangarko** [comment]
I am sorry, that looks incompatible. My plate is full at present to add special third party integrations. You can however, have a look at changing your Formatting priority: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities
