### ISSUE TITLE
1.18.1: Warning_Points.Reset_Task crashing plugin

### ISSUE THREAD

**Issue by DMessor** [kangarko/ChatControl#1607]
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: false

Console Error: https://pastebin.com/t4sgyeDn
Error log file: https://pastebin.com/Wxhagvut
Warning Points section in settings: https://pastebin.com/bmKwkhHr
Unable to use chc debub as plugin is disabled

I've never changed the warning points section until now and it's not even enabled. Previously "Period" was set to "10 minutes" but since the errors have started I changed it to 0 with no luck fixing the isssue.

**Comment by Terminal-Access** [comment]
Duplicate of #1598

Author has replied that the plugins will be updated tonight.

Untill then please use paper build 119.

**Comment by DMessor** [comment]
Thank you!
