### ISSUE TITLE
1.18.1: Plugin fails to load

### ISSUE THREAD

**Issue by Hellcode48** [kangarko/ChatControl#1608]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

ChatControlRed fails to load in latest spigot builds due to file and comment heading changes on spigot's end, only happens in latest 1.18.1 builds (CMI had the same problem: "Fix for introduced issue from spigot side when it comes to file and their comment handling. This only had issue with 1.18.1 and latest builds of it.").

Error: https://pastebin.com/G2UPMAke

**Comment by kangarko** [comment]
Fill be patched in an hour or two, thank you.
