### ISSUE TITLE
Channel autojoin Improvement

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#161]
To avoid confusion as we are moving to the all channel layout, I think it's a good idea to mention in the channels section the permission node to autojoin. Because for instance, servers that never used channels could get confused why people are having issues talking. 

Potential addition(**\*NEW\***):
```yaml
# Which channel should people automatically join?
# A channel name or `none` to use permission nodes.
# To override, use the permission system "chatcontrol.autojoin.{channel}.{read/write}".
Autojoin: 'standard'
```
This would need to be under "Enabled: true".

**Comment by kangarko** [comment]
Thanks, I will not add such option since we already have permissions, but I will add a notice to the channels section.
