### ISSUE TITLE
Adding swears

### ISSUE THREAD

**Issue by Mrufkojad** [kangarko/ChatControl#161]
Hey.
Is there a simple way to add my own swears? I run server in Poland and I need to implement polish swears :)

**Comment by kangarko** [comment]
Hello,

You can simply copy and paste existing filters, changing only the letters. See the following for a quick tutorial:
https://github.com/kangarko/ChatControl/wiki#rules

By the way, the premium version has two commands to do this quickly. One creates them in the game, the other imports massive amounts of rules from a file.

**Comment by Mrufkojad** [comment]
Well, I have list of more than 200 swears, so i would be hard in these 2
cases. But I'll think of it, thanks :)

**Comment by kangarko** [comment]
If you paste them here I will run them in the premium version and generate the rules for you :)

**Comment by Mrufkojad** [comment]
Well, that's really nice offer, but I have to think about it first. I'll
check if free version of your plugin works properly for me and then
probably I'll buy pro version. Thanks for respond.

**Comment by kangarko** [comment]
Hey,

I mean, I will make the rules for you for free so you don't need to buy premium now. I am signing off now, so if you decide you would like them created it will be most likely done by Friday. Thank you for consideration!

Sincerely,
kangarko

**Comment by Mrufkojad** [comment]
Hey, I've got another question. Can your plugin run a command, when a
player breaks rules? I'm searching for a plugin that will mute player for
swearing, pasting URLs and IPs.

**Comment by EvilOlaf** [comment]
Yes, CHC can do that. Check the handlers.yml file.

**Comment by Mrufkojad** [comment]
Okey, I think I'll use your plugin, can you implement polish swears then? I
can give you list, but I'm not sure how it works. For example there is
simple swear "kurwa", but also "kurwie", "kurwe" etc. Can you block then
String "kurw", and all other words will be blocked?

**Comment by EvilOlaf** [comment]
You have to implement those by yourself. Though I can give you a few examples. I use `badword` instead of your example swear.

I hope that is all correct...it is working for me at least :D
```
# Blocks badword, XbadwordX, !!!BaDWoRD!!!
match badword
handle as swear

# Blocks badword, if the word has a separation before BUT NOT after the word. A separation could be a dot, comma, exclamation mark, space, whatever. \b triggers this.
match \bbadword
handle as swear

# Blocks badword, b.a.d.w.o.r.d, xBxAxDxWxOxRxDx, !!!BssssAsssDssssssWssssOgggRasdfasdfD!!! and all combinations you can think about
match (b+(\W|\d|_)*a+(\W|\d|_)*d+(\W|\d|_)*w+(\W|\d|_)*o+(\W|\d|_)*r+(\W|\d|_)*d+(\W|\d|_)*)
handle as swear

# Blocks badword like the example above but handles bedword and its derivates as well (UNTESTED)
match (b+(\W|\d|_)*(a|e)+(\W|\d|_)*d+(\W|\d|_)*w+(\W|\d|_)*o+(\W|\d|_)*r+(\W|\d|_)*d+(\W|\d|_)*)
handle as swear

# Blocks badword, bedword and b4dword non case sensitive but will ignore the rule if "bedwords" has been matched
match b(a|e|4)dword
ignore bedwords
handle as swear
```



From my experience you have to fine adjust your filter over time to defeat false positives which can be easily done with `ignore` or matching regex as well. I recommend to ask your team to watch out carefully about those false positives and report them back to you.
Yes, can be quite annoying to hack all the regex in, but once finished you have a quite decent and reliable running chat filter.

**Comment by Mrufkojad** [comment]
Okey, I'm getting confused. kangarko said:

"If you paste them here I will run them in the premium version and generate
the rules for you :)".

So what now? :D

**Comment by EvilOlaf** [comment]
If @kangarko does this for you, that is great. The information will help you anyways to adjust the filter to your needs :P

**Comment by Mrufkojad** [comment]
That's why I'm asking about the swears, cause my list has about 600 of
them, because of many polish forms. :D

**Comment by kangarko** [comment]
EvilOlaf explained it excellently.

If you wish to also block the derivatives of a word (kurwa, kurwie, ...), then focus on this filter:

> match (k+(\W|\d|_)*u+(\W|\d|_)*r+(\W|\d|_)*w+(\W|\d|_)*(a|ie|e|u)+(\W|\d|_)*)
> handle as swear

This filter looks for characters k u r w (a|ie|e|u)

See the last part: 

> (a|ie|e|u)+(\W|\d|_)*

The letters in parenthesis () determine all the variants of the word kurwa, here: kurwa, kurwie, kurwe, kurwu.

If you want to add another variant, simply put for example |i at the end of the a|ie|e|u part:

> (a|ie|e|u|i)+(\W|\d|_)*

I can import all 600 words for you, but you will need to modify them for all polish cases yourself.

**Comment by kangarko** [comment]
Closing, remind me if any questions.
