### ISSUE TITLE
1.17.1: I have 4 channels and Max_Read_Channels: 5 yet it always kicks me from reading global for "over limit"

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1611]
I haven't setup groups, I have ` Max_Read_Channels: 5`  in settings.yml, I only have 4 channels.
Nobody (I'm OP) can use `/th` which is switch to helpop channel using:
```
# This rule only executes when player is not in the admin channel for reading.
match ^(\/th)
dont verbose
ignore channel helpop write
then command channel join helpop write
then deny

# This rule only executes when player is in the admin channel for writing.
match ^(\/th)
dont verbose
require channel helpop write
then command channel join global write
then deny
```
OR clicking channels in `/ch`
I expect clicking these channels to keep me reading them all and just change what im writing in, not kick me out of reading them.
![2022-01-03_17 43 14](https://user-images.githubusercontent.com/144046/147962190-491f8e5f-1f33-49d5-a8da-d56090105a2a.png)

But if I log out and in again, im reading them all again.

![2022-01-03_17 44 49](https://user-images.githubusercontent.com/144046/147962353-4dfddf45-d7e0-4443-b2c7-16f79aa64c3a.png)

Very strange behavior.

Minecraft Version: 1.17.1
MySQL: true/false
BungeeCord: true/false

**Comment by TomLewis** [comment]
I think I resolved it by setting `Join_Read_Old` what super odd default, this should be on by default, that was so confusing.
Why on earth did it tell me I was over the limit?

**Comment by kangarko** [comment]
Thanks, will set the Join_Read_Old option to true for default installs.
