### ISSUE TITLE
Priority in format

### ISSUE THREAD

**Issue by nivcoo** [kangarko/ChatControl#1615]
Hello, actualy i've https://pics.revolis.fr/2022/01/04/14-10_Wzx5.png and i have to set false the previous permission to not send the other prefix, can you add a priority : if i have permission of rank_2 and rank_1 only the rank_2 message will be send.

**Comment by kangarko** [comment]
That's actually a bug. I will use LinkedHashMap internally which retains top-to-bottom format positions starting next update. You will need to reorder manually upon updating.

**Comment by nivcoo** [comment]
Isn't a bug, i suggest a feature

**Comment by nivcoo** [comment]
I did't speak order but priority

**Comment by kangarko** [comment]
I know, but we are not planning this. We simply make the order from top to bottom.

**Comment by nivcoo** [comment]
You don't understand my feature, isn't an order feature

**Comment by kangarko** [comment]
I am sorry, I misread "if i have permission of rank_2 and rank_1 only the rank_2 message will be send.": You could just use a permission plugin with negative permissions and Sender_Permission option for that format parts for this.

**Comment by nivcoo** [comment]
> I am sorry, I misread "if i have permission of rank_2 and rank_1 only the rank_2 message will be send.": You could just use a permission plugin with negative permissions and Sender_Permission option for that format parts for this.

Yes i did like that, but its more practical without négative permission i think, its Why i suggest that

**Comment by kangarko** [comment]
I see. Use permissions for now, I can have a look later.

**Comment by nivcoo** [comment]
Maybe with option : priority: rank_2 (just for exemple) and if the sender /reveiver can display thé rank_2 so the rank_1 doesnt display
