### ISSUE TITLE
1.18.1: Books not usable

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1617]
Using the /chc book new command then filling out the book to whatever you want and then doing /chc book save <name> does save the book to a .yml file as intended. But when you then do /chc book give <name> and open the book, it just shows *Invalid book tag*. Been an issue for quite a long time, only re-coming to the issue now. Happens on fresh install, making the book function most unusable.

Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Cannot reproduce:

https://i.imgur.com/wuv4pkR.png
https://i.imgur.com/eyuLe29.png

If you are using ViaVersion or any protocolhack, then it will most likely not work properly. Check if you are on the latest CCR and Paper server version.
