### ISSUE TITLE
1.18:1: /r not working

### ISSUE THREAD

**Issue by NyhmsQuest** [kangarko/ChatControl#1618]
![image](https://user-images.githubusercontent.com/3873370/148211782-508d169f-88c1-41b4-b108-c8dc3e1b0e01.png)
Players can't use /r to reply to a message until they have done at least 1 normal /msg player
I feel like you should be able to simply do /r right after recieving a pm from someone and not have to do 1 /msg

Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Cannot reproduce on the next version, please wait for it to update tonight.
