### ISSUE TITLE
DiscordSRV Support / API

### ISSUE THREAD

**Issue by Androkai** [kangarko/ChatControl#162]
I searched for an API and found this one in the description of the pro version:

> API Developers can now take advantage of the following class for working with players' channels: me.kangarko.chatcontrol.api.ChannelAPI
The event 'ChatChannelEvent' allows you to modify the message, format, recipients, or get information regarding the channel or even cancel the message before it's sent out.

Is this available only in the pro version of the plugin? We're getting problems with canceled chat events (which we respect and not send them) for our plugin [DiscordSRV](https://github.com/Scarsz/DiscordSRV/). An official API (for best case in form of a public repository) would be nice.

Greetings

**Comment by kangarko** [comment]
Hello,

yes, the API has been introduced in the premium version in its later releases.
Btw, there is already an open ticked regarding DiscordSRV support:
https://github.com/kangarko/ChatControl-Pro/issues/123

 This stands in the forefront when it comes to the next major release, I will be looking for a solution towards the end of the year. Thank you for your understanding.

**Comment by Androkai** [comment]
Thx for the information and your effort to search for a way to make this possible. The next upcoming release of DiscordSRV (no eta at the moment but possible at christmas) will contain a big rewrite of fundamental parts and provide a much better [API](https://github.com/Scarsz/DiscordSRV/tree/develop/src/main/java/github/scarsz/discordsrv/DiscordSRV/api). Feel free to make use of it.

About your API: Is a bit weird that I need to buy the plugin first to be able to use it ;)

**Comment by kangarko** [comment]
Yes regarding the API, I know, I made it from the ground up in the premium version long time after its initial release, whereas the free version was originally to be remained with only security updates. If I get time to it, I may backport it.

**Comment by SmallSansSerif** [comment]
So does the ChatControl Pro hook or recognition of DiscordSRV allow for filtering of incoming Discord messages? I can't seem to get this working and it bypasses ChatControl Pro currently. I moved the priority up from normal to HIGH but no change there. Please advise @kangarko

**Comment by kangarko** [comment]
Closing. The support will be integrated to ChatControl Pro soon, you can track the progress at

https://github.com/kangarko/ChatControl-Pro/issues/123
