### ISSUE TITLE
1.18.1: Format order automatically reverts

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#1620]
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true
CHC RED Version: 10.9.0

Good evening gentlemen.

After updating to CHC RED 10.9.0, and MC 1.18.1, I encountered some issues with my formats/chat.yml, the format has been disorganized in a way that each format part is in a diferent order. I would bet on this fenomenon also occuring with all other formats.

Attempting to re-order the format parts results in CHC reordering them to it's own preference, hence the chat looks messed up, with player rank prefixes after names (should be before names), incorrect colors being applied, and weird extra spacings (as consequence of unintended reorder).

![imagen](https://user-images.githubusercontent.com/6623704/148230857-61388937-852c-4fc2-b9a6-aac515cd1530.png)

The format reverts to a the same CHC dictated order every time you either start the server or reload the plugin.

**Comment by kangarko** [comment]
Please use this version: https://github.com/kangarko/ChatControl-Red/issues/1619

You will need to reorder again manually after upgrading, but that will be the final time.
