### ISSUE TITLE
1.18.1: Formatting lost when using receiver_permission node

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1621]
READ and understood.

I use a format file for my channel "admin-chat". This formatting is setup in file "admin-chat.yml".

When using the node 'Receiver_Permission' i appear to lose some formatting in the message payload. Let me explain with examples:

**Works**

![image](https://user-images.githubusercontent.com/10013800/148234247-e730c960-0981-49ce-858b-e9bcc72fcb2a.png)

Formatting file: https://pastebin.com/GTgNUKEE

**NOT works**

![image](https://user-images.githubusercontent.com/10013800/148233828-e26ec8f0-2e35-41fd-a5f5-686a43e4b75b.png)

Formatting file: https://pastebin.com/85q1PRUg

Minecraft Version: Papermc 1.18.1 #100
MySQL: true
BungeeCord: true

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7815552/debug.zip)

**Comment by kangarko** [comment]
Do you lose the formating on the same server or across the network? Due to some internal limitations the formating is not lost, but it is not inherited from one component to another over the network. I'll see what I can do.

**Comment by Terminal-Access** [comment]
Just in case this was missed, according to the debug/general.txt this is an older version of CCR and MC Version 1.16.x not sure why its been marked for MC Ver 1.18.1.

Or the debug that's attached is not from the same server.

**general.txt**
```
!-----------------------------------------------------!
 Debug log generated 03.09.2021 16:03:13
!-----------------------------------------------------!
Plugin: ChatControlRed v10.6.2
Server Version: Paper v1_16_R3
```

**Comment by kangarko** [comment]
In that case, @donvdp please use this version: https://github.com/kangarko/ChatControl-Red/issues/1619

**Comment by donvdp** [comment]
Hi there, Great catch on my being outdated !! i didnt know that the newer versions were on a gdrive.

I have just updated all my servers and retested this matter. I am sorry to say that the issues still persists.

**Comment by kangarko** [comment]
I patched this, please try the next version :)

**Comment by donvdp** [comment]
works like a dream now ! sorry for the late reply !
