### ISSUE TITLE
1.17.1 -> 1.18.1 Fully breaking.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1622]
I recently moved from 1.12.2 to 1.17 and re-made configs from scratch on 1.17.1 PurPur, Im trialing 1.18.1 today and ChatControl red fully broke on boot.
I have changed nothing since it was working perfectly fine on 1.17.1

Startup errors https://mclo.gs/lzYJEEp
Error.log
https://gist.github.com/TomLewis/14facebcdb4a98490ed8363cfafb9970

Minecraft 1.18.1
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
We've updated since. Paper/Spigot introduced a breaking change in their config storage. Use: https://github.com/kangarko/ChatControl-Red/issues/1619

**Comment by TomLewis** [comment]
And MCMarket is down, typical!
