### ISSUE TITLE
1.18 Rules question 

### ISSUE THREAD

**Issue by XGiammyX** [kangarko/ChatControl#1623]
Minecraft Version: 1.18
MySQL: true
BungeeCord: true/

I created new rules in the chat server, how do I block words written like this
c0ck and the like, thanks

**Comment by TheIntolerant** [comment]
Hey, To do this just edit the one for "cock" and change this
```rust
# Blocks 'cock'
match \b(c+(\W|\d|_)*o+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
group swear
```
To this
```
# Blocks 'cock'
match \b(c+(\W|\d|_)*(o|0)+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
group swear
```
