### ISSUE TITLE
1.18.1: Ghost message?

### ISSUE THREAD

**Issue by Youseebriandev** [kangarko/ChatControl#1624]
I have said this message one time, But now it comes every 15 minutes back in the chat without a chatformat? I have connected it with Msql and changed the database, Also i have changed the Chat listener to MONITOR. There is no other plugin that formats the chat.

I hope you can help.

![Ghost Message](https://user-images.githubusercontent.com/97226420/148370159-b64a8be7-0100-40e1-8c66-9f0864376d22.jpeg)
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7821162/debug.zip)

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey,
Sorry for the delay.

I've never seen a such issue before. Does this still happens?

**Comment by kangarko** [comment]
It must be coming from another plugin. Odd I know, but the only thing coming to my mind is ViaVersion or ProtocolLib since they mess with packets and all of the odd issues we had reported came from those so far.
