### ISSUE TITLE
Automatic Messages

### ISSUE THREAD

**Issue by TheIntelloBox** [kangarko/ChatControl#1625]
Hello,

Which file is used for Automatic Messages ?

Thanks

**Comment by WolverStones** [comment]
> Hello,
> 
> 
> 
> Which file is used for Automatic Messages ?
> 
> 
> 
> Thanks
> 
> 

Timed.rs more info here: https://github.com/kangarko/ChatControl-Red/wiki/Messages

**Comment by ElBananaa** [comment]
Hey,
Thanks for answering @WolverStones.
I'm closing this issue. Let me know if you need anything else ;)

**Comment by TheIntelloBox** [comment]
Hello, thanks to both of you ! How to make centered automatic messages ?

**Comment by TheIntelloBox** [comment]
Someone wants to come on my server and Discord server to see the bug by yourself ?

**Comment by TheIntolerant** [comment]
> Hello, thanks to both of you ! How to make centered automatic messages ?

Just use ``<center>`` before the message to center it.
