### ISSUE TITLE
Lost Plugin Access

### ISSUE THREAD

**Issue by StormyIceLeopard** [kangarko/ChatControl#1626]
![image](https://user-images.githubusercontent.com/10292779/148469339-15b86bd5-b525-41a2-8d6d-ca6a29b4465d.png)

I been using CC Pro and CC Red for years. What on earth happened? Why did I get my license revoked?

**Comment by ElBananaa** [comment]
> ![image](https://user-images.githubusercontent.com/10292779/148469339-15b86bd5-b525-41a2-8d6d-ca6a29b4465d.png)
> 
> I been using CC Pro and CC Red for years. What on earth happened? Why did I get my license revoked?

Hey!
Your license didn't get revoked, it seems like an issue affecting absolutely everyone one, and every resource. They're already working on it!

Once again, no worries, you didn't lose your license 😉

**Comment by StormyIceLeopard** [comment]
> > ![image](https://user-images.githubusercontent.com/10292779/148469339-15b86bd5-b525-41a2-8d6d-ca6a29b4465d.png)
> > I been using CC Pro and CC Red for years. What on earth happened? Why did I get my license revoked?
> 
> Hey! Your license didn't get revoked, it seems like an issue affecting absolutely everyone one, and every resource. They're already working on it!
> 
> Once again, no worries, you didn't lose your license 😉

![image](https://user-images.githubusercontent.com/10292779/148478293-0878ac71-2a5e-4eae-8445-fe478f88019a.png)
I didn't lose access to anything else I purchased.

**Comment by WolverStones** [comment]
I also no longer have access

License is inactive: Contact seller

**Comment by kangarko** [comment]
@WolverStones please resubmit the upgrade form at mineacademy.org/plugins for the specific plugin. Seems to start occuring after MCMarket has launched their V2, we will just re-add you for free.
