### ISSUE TITLE
Minecraft Version: License issues

### ISSUE THREAD

**Issue by typicalsmc** [kangarko/ChatControl#1627]
![image](https://user-images.githubusercontent.com/53472591/148482214-1b5ec6d7-d352-45be-8af9-7181eb589eb6.png)
Mc-Market update to Xenforo 2 broke my ChatControl-Red license.
Here it says: License deactivated by seller.
I'm pretty sure that i didn't violate any terms and condtions

**Comment by WolverStones** [comment]
#1626

**Comment by ElBananaa** [comment]
As said on Discord by Kangarko : 

```
IMPORTANT LICENSE INFORMATION

MC-Market is back up, seems like some people are starting to lose their license. That was caused by me setting the expiration date to 12 months and the renewal fee to $0, which seems to have not been the case with the new version of Mc-Market.

If you lost your license, simply resubmit the upgrade form at mineacademy.org/chatcontrol-red#upgrade (you can submit it for other plugins there, too) and we'll approve it within 1-3 days maximum.

Thanks
Matej
```

**Comment by kangarko** [comment]
Thanks, please follow the announcement above and just resubmit. Seems to be a problem after MCMarket upgraded.
