### ISSUE TITLE
Notify Error

### ISSUE THREAD

**Issue by xXMrCubezXx** [kangarko/ChatControl#163]
On my server (Paperspigot 1.8.8), we are using non-premium chatcontrol. When someone swears or advertises, It shows as [Swear/ID {ruleID}] {player}: or [AD/ID {ruleID}] {player}:message instead of [Swear/ID Swear] exampleplayer: somebadword.

**Comment by kangarko** [comment]
Hello,

the non-premium version does not support the variables in format {variable}, but rather %variable.
Change them so to: `%player`, `%message`, and so on.
