### ISSUE TITLE
1.18.1 - ChatControl name suggestion using TAB key in /msg

### ISSUE THREAD

**Issue by NovaPixell** [kangarko/ChatControl#1633]
I am preparing my network consisting of 2 Bukkits (with ChatControl in Bungee mode) and Bungee with the BungeeControl plugin.
When users are on a different server, the name itself cannot be seen in the name suggestion using /msg + name.
is there an option or is it a bug?

**Comment by ElBananaa** [comment]
> I am preparing my network consisting of 2 Bukkits (with ChatControl in Bungee mode) and Bungee with the BungeeControl plugin. When users are on a different server, the name itself cannot be seen in the name suggestion using /msg + name. is there an option or is it a bug?

Hey,
I'm pretty sure something's wrong with your setup as, I believe, tab-completion should work across servers when the plugin is properly configured. Is ProtocolLib installed on all your backend servers, and is it up-to-date? Same with BungeeControlRed?
Are you using Bukkit, or Spigot/Paper (or anything else)? We do recommend running the plugin on paper for backend servers, and Waterfall for the proxy.

**Comment by kangarko** [comment]
Tab should work, just make sure to follow what Banana says, and have BungeeCord enabled in settings.yml of the two ChatControl installations.
