### ISSUE TITLE
1.18.1: Sound notify/color

### ISSUE THREAD

**Issue by ACluco1** [kangarko/ChatControl#1634]
Hello, sound notify and sound notify colors doesnt work for me, when i type any nickname (online) into chat, it just does nothing, but it should notify mentioned player and it should change the color of the nickname, but it doesnt..

Any help guys? No errors in console or on startup, not even in error.log ... It was working some time ago, i dont know when it stopped working, i didnt noticed.. Every group has permissions what it has to have

![image](https://user-images.githubusercontent.com/31342467/148806761-3718b5af-a0e7-40d4-a6ef-ae7c690019d1.png)

Minecraft Version: purpur-1.18.1-1498
MySQL: false
BungeeCord: false

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7840518/debug.zip)

**Comment by ElBananaa** [comment]
Hey!
Seems like it's an issue affecting all versions since 10.8.9 (I believe), as this was reported multiple times on discord.
Kangarko will probably fix this in the next versions ^^

**Comment by Malachiel87** [comment]
That happen also with 1.12.2  not working

**Comment by kangarko** [comment]
Thanks, will be patched.
