### ISSUE TITLE
1.17.1: ItemsAdder Text effects not showing correctly In chat and private messages.

### ISSUE THREAD

**Issue by tyepavitt** [kangarko/ChatControl#1635]
The Itemsadder text effects: https://itemsadder.devs.beer/plugin-usage/text-effects-1.17+ don't show correctly in the chat and private messages.

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
I am sorry but thats probably a major incompatibility, we have our own system to send chat messages.
