### ISSUE TITLE
1.18.1: Private message not working with nicknames

### ISSUE THREAD

**Issue by itsBeaco** [kangarko/ChatControl#1637]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

Hey! I hope you're well.

When we direct message people on our server, it says: "Player *name* is not online on this server", they are online and the only thing we can see that is different is their nickname. Any ideas why this is happening? If you need any more information such as my settings.yml, please let me know :)

**Comment by itsBeaco** [comment]
Sorry, I've just seen this is a duplicate issue. I will close and check the older one

**Comment by kangarko** [comment]
Please use the next version :)
