### ISSUE TITLE
1.17+ chat.yml formats resets their order.

### ISSUE THREAD

**Issue by TechRoot** [kangarko/ChatControl#1638]
I try to format the chat messages in a coherent order, meaning suffixes,displaynames,prefixes and such, in a proper way.

But, every time save the yml without yaml parser errors, the file got their parts order reset, meaning displaynames goes prior to prefixes, in example.

I uploaded two files, chatordered.yml.txt, with the order i try to acomplish, and chatresult.yml.txt as the file gets when i start the server.

Minecraft Version: 1.17.0++
MySQL: true
BungeeCord: true
[chatordered.yml.txt](https://github.com/kangarko/ChatControl-Red/files/7849610/chatordered.yml.txt)
[chatresult.yml.txt](https://github.com/kangarko/ChatControl-Red/files/7849618/chatresult.yml.txt)

**Comment by ElBananaa** [comment]
> I try to format the chat messages in a coherent order, meaning suffixes,displaynames,prefixes and such, in a proper way.
> 
> But, every time save the yml without yaml parser errors, the file got their parts order reset, meaning displaynames goes prior to prefixes, in example.
> 
> I uploaded two files, chatordered.yml.txt, with the order i try to acomplish, and chatresult.yml.txt as the file gets when i start the server.
> 
> Minecraft Version: 1.17.0++ MySQL: true BungeeCord: true [chatordered.yml.txt](https://github.com/kangarko/ChatControl-Red/files/7849610/chatordered.yml.txt) [chatresult.yml.txt](https://github.com/kangarko/ChatControl-Red/files/7849618/chatresult.yml.txt)

Hey!
This is a known issue which has been patched in the latest version (which is only available on discord since mcmarket was down when it was pushed). Please join our discord (https://mineacademy.org/discord) and read the announcement channel. The version was published the 5th.

**Comment by kangarko** [comment]
Please use the next version, coming up tonight on MCMarket also, no need for discord this time :)
