### ISSUE TITLE
1.17.1: Latest version of ChatControl overrides my chat format

### ISSUE THREAD

**Issue by SFlakeZ** [kangarko/ChatControl#1639]
Minecraft Version: 1.17.1 (latest paper build)
MySQL: true
BungeeCord: true
ChatControl Red: 10.9.0

It worked for weeks/months without any issues.
I always tried using the latest builds of Chatcontrol / BungeeControl so
it was a small version jump.

Even after regenerating the new chat format file and pasting my old setup step by step
results in a broken / intermixed file.
-> InGame it is completly out of order

There is no error in console / chatcontrol-error log.

config-old.yml (that's the old config from the previous versions)
config-new.yml (newly generated + added my formats)
config-broken.yml (shows exactly how it looks after using it on my server)

[chat-override.zip](https://github.com/kangarko/ChatControl-Red/files/7850285/chat-override.zip)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1 (latest paper build) MySQL: true BungeeCord: true ChatControl Red: 10.9.0
> 
> It worked for weeks/months without any issues. I always tried using the latest builds of Chatcontrol / BungeeControl so it was a small version jump.
> 
> Even after regenerating the new chat format file and pasting my old setup step by step results in a broken / intermixed file. -> InGame it is completly out of order
> 
> There is no error in console / chatcontrol-error log.
> 
> config-old.yml (that's the old config from the previous versions) config-new.yml (newly generated + added my formats) config-broken.yml (shows exactly how it looks after using it on my server)
> 
> [chat-override.zip](https://github.com/kangarko/ChatControl-Red/files/7850285/chat-override.zip)

Hey,
Please use the version in #1619. It'll fix the issue (but you'll need to correctly setup your formats again)

**Comment by kangarko** [comment]
We will update MCMarket tonight :)
