### ISSUE TITLE
Permissions Help

### ISSUE THREAD

**Issue by CloudedKiller** [kangarko/ChatControl#164]
Help needed for adding permissions using PEX
chatcontrol.(any permission i tried to add) does not seem to work, and I would just like some clarification on how to work this out. I have viewed https://github.com/kangarko/ChatControl/blob/master/src/kangarko/chatcontrol/utils/Permissions.java already, and gave me an easy list of permissions to read, which is really helpful, but I am not sure why the permissions aren't working. For example when i try to do /chc help with the permission chatcontrol.commands.list it just replies with "insufficient permission (chatcontrol.commands.list)"
should i paste in some logs?

**Comment by EvilOlaf** [comment]
Probably an issue with your permission management plugin.
In any case please read the contribution guidelines and provide all necessary information to investigate this further.

https://github.com/kangarko/ChatControl/blob/master/CONTRIBUTING.md

**Comment by CloudedKiller** [comment]
2. I downloaded the plugin today, so I will assume that I have the newest version of your plugin.
3. 
24.12 15:27:55 [Server] INFO This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
24.12 15:27:55 [Server] INFO You are 538 version(s) behind 
4. Protocol Lib 4.0.1, Vault v1.5.6-b49, Essentials TeamCity, Multiverse-Core 2.4-b527. Should I list any other plugins versions?

**Comment by kangarko** [comment]
When it comes to commands, you need to give those two permissions explicitly:

    - chatcontrol.commands

and, the specific permission for the command you want to allow:

    - chatcontrol.commands.list

**Comment by kangarko** [comment]
I believe that fixed the issue. Please feel free to comment below if the problem still persists.
