### ISSUE TITLE
1.16.3 | Error while kicking player for spam

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#164]
https://pastebin.com/jTNyU67A

Also when player get kicked, his kick message displays 4 times
![image](https://user-images.githubusercontent.com/62369973/100127489-35571580-2e90-11eb-9a8a-09a950df61b6.png)

**Comment by kangarko** [comment]
Unfortunately that seems like a problem with CMI. Please wait for the next version, and send that version to CMI developers,
