### ISSUE TITLE
1.18: Question regarding [item]

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1640]
How can I add brackets around the [item] variable? I am not quite understanding how it works. So instead of just showing Stone in chat would be [Stone]. As well, is there a way to do this same variable with a [inventory] or [inv]?

Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#how-to-put-brackets-around-the-item-variable-so-it-shows-i-hold-stone :)
