### ISSUE TITLE
1.18.1: "Error: Could not parse CompChatColor" and plugin disables itself on restart

### ISSUE THREAD

**Issue by Jupitour** [kangarko/ChatControl#1642]
The moment I updated to v10.9.3, plugin refuses to start and throws this error: **"Error: Could not parse CompChatColor"** - even when reverting to v10.9.0 it throws the same error.

Since I can't start the plugin up at all to run **/chc debug**, I have attached my **latest.log**, and created a manual **debug.zip**. Hope that suffices!

ChatControlRed v10.9.3
Minecraft Version: 1.18.1
Purpur version git-Purpur-1497 (MC: 1.18.1)
MySQL: false
BungeeCord: false

[latest.log](https://github.com/kangarko/ChatControl-Red/files/7855048/latest.log)
[manual-debug.zip](https://github.com/kangarko/ChatControl-Red/files/7855083/manual-debug.zip)

**Comment by ElBananaa** [comment]
> The moment I updated to v10.9.3, plugin refuses to start and throws this error: **"Error: Could not parse CompChatColor"** - even when reverting to v10.9.0 it throws the same error.
> 
> Since I can't start the plugin up at all to run **/chc debug**, I have attached my **latest.log**, and created a manual **debug.zip**. Hope that suffices!
> 
> ChatControlRed v10.9.3 Minecraft Version: 1.18.1 Purpur version git-Purpur-1497 (MC: 1.18.1) MySQL: false BungeeCord: false
> 
> [latest.log](https://github.com/kangarko/ChatControl-Red/files/7855048/latest.log) [manual-debug.zip](https://github.com/kangarko/ChatControl-Red/files/7855083/manual-debug.zip)

Hey!
There's an issue with your chat.yml file
It seems like your gradient formats got converted to raw hex formats, which are not supported by the plugin.
Please replace `Gradient: §x§9§1§B§0§F§F - §x§F§F§F§F§F§F` with `Gradient: #91B0FF - #FFFFFF`
and `Gradient: §x§B§B§B§B§B§B - §x§F§F§F§F§F§F` with `Gradient: #BBBBBB - #FFFFFF`
It should fix your issue.

Let me know if you need anything else ;)

**Comment by ElBananaa** [comment]
I'm reopening this issue as it seems to actually be a recurring issue with 10.9.3 & latest paper/spigot builds.
Spigot/paper recently did further changes that seem to (once again, thanks spigot...) break yaml files (see https://github.com/PaperMC/Paper/pull/7246)

As example, the gradient part sometimes gets fully deleted from the format files, sometimes the format gets replaced to its raw version (so `Gradient: '#RRGGBB - #RRGGBB'` becomes `Gradient: §x§9§1§B§0§F§F - §x§F§F§F§F§F§F`) or gets replaced to color codes in both the right and the raw format (so `Gradient: YELLOW - RED` becomes `Gradient: &e - &c` or `Gradient: §e - §c`

**Comment by kangarko** [comment]
let's continue here, investigating asap:

https://github.com/kangarko/ChatControl-Red/issues/1650
