### ISSUE TITLE
Suggestion: New operator that works similar to "expires"

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1644]
### Suggestion: Add an operator that works similar to "expires" but this operator is called something like "require afterdate" where a rule or message is only executed if triggered after a specific date and time.

Example: 
```
require afterdate 30 Dec 2021, 15:00
```

----

#### 1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
This would benefit many users who lack knowledge and cannot make their own JavaScript to achieve this.This would also allow people to implement more custom features into their server, as many of the operators already have an opposite counterpart such as ``ignore script`` and ``require script``

As well making it possible to make rules which are only executed if within a specific date, for example users could also use the "expires" operator together with this operator to easily make rules that are only executed between those two dates. Which means less time spent learning how JavaScript works if they wish to do something basic like that.

#### 2. What would happen if we won't implement this feature? How's your server being affected?
While this is achievable with ChatControl, not adding this may result in users spending a heap of time to get this to work or finding another plugin to achieve something similar.

----

This would be an amazing addition to both rules and messages.

**Comment by kangarko** [comment]
I have absolutely no time for this due to recording. However if you write down a simple example such as "require script Date.now() < 000000" where the zeros represent a unix timestamp generated at https://www.unixtimestamp.com/index.php I'll gladly put it to the wiki for the average person ;)

**Comment by TheIntolerant** [comment]
Ohh I didn't know I could do this, I will 100% look into this.
