### ISSUE TITLE
1.12.2: Using java 17 and Nashorn  it just crash chatcontrol

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#1646]
Minecraft Version: 1.12.2
MySQL: true
BungeeCord: false

Error:
![image](https://user-images.githubusercontent.com/3611852/149241392-c9844bbd-0627-42c2-a116-823f68f0ada5.png)

**Comment by braceyourself07** [comment]
I just want to add my +1 for Java 17 support.  

I run a 1.16.5 server (on Java 16) so I'm ok for now, but there is a plugin that we critically rely on that now only supports Java 17 and ChatControl-Red is the only plugin we have that crashes on Java 17.  So we cannot incorporate any more updates until CC Red supports Java 17.  Thanks for the quality work that you do, been a very satisfied customer/user of ChatControl for several years now.

**Comment by ElBananaa** [comment]
Hey,
Chc-red works fine with java 17 for 1.17+ ^^
For versions below, even tho java is supposed to be backward compatible, I believe you guys should stick with java 11/14 for versions below 1.16.5, java 16 for 1.16.5 and java 17 for versions above 1.16.5

**Comment by braceyourself07** [comment]
Oh ok.  You know what, I was going to update CC and test that but I wasn't able to download an updated version and MC Market won't let me buy the $0.01 renewal.  I am working with matej to get it renewed though.  Good to know there is Java 17 support!

**Comment by kangarko** [comment]
@braceyourself07 seems like a bug in MCmarket caused by me lol, just email me and I'll readd you manually

I am too running Java 17 however it request Minecraft 1.17+ to run optimally. For some weird reasons new Java versions don't work well on old Minecraft versions, no clue what to do here, just use Java 8 on old Minecraft version.
