### ISSUE TITLE
1.12.2-1.17.2: Issues on {server_name} placeholder

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#1647]
I am using the following rule on group
then console forward console a &c&l(!) &r&e{player} > {server_name} > Spam: &7{original_message}
it will trow the weird symbol
![image](https://user-images.githubusercontent.com/3611852/149305104-3651c0e2-10ae-4ba4-bbfd-b773d9c972e3.png)

Plus i noticed on 1.18.1 it will show "A minecraft server" instead the server name (i think because the server-name setting was removed)

Minecraft Version: 1.12.2 - 1.17.2
MySQL: true
BungeeCord: false

**Comment by TheIntolerant** [comment]
Please read https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#placeholders to fix this issue.

As I believe the default string used by PlaceholderAPI for the ``{server_name}`` placeholder is "A Minecraft server", which is why this placeholder is the incorrect name. Since PlaceholderAPI will overwrite the way the placeholder is formated by ChatControl.

**Comment by Malachiel87** [comment]
You are right,  that fixed the 2° issue, but i keep to see the strange symbol

**Comment by TheIntolerant** [comment]
Would you mind testing the placeholder via ChatControl and PlaceholderAPI. To see if the placeholder is parsing correctly via those commands.

---

For ChatControl run: ``/chc info variables <your_username> {server_name}``

---

For PlaceholderAPI run: ``/papi parse me %server_name%``

---

**Comment by Malachiel87** [comment]
> Would you mind testing the placeholder via ChatControl and PlaceholderAPI. To see if the placeholder is parsing correctly via those commands.
> 
> For ChatControl run: `/chc info variables <your_username> {server_name}`
> 
> For PlaceholderAPI run: `/papi parse me %server_name%`

That is showed correct to me, but for any weird reason when chatcontrol do it it will add that weird symbol

**Comment by TheIntolerant** [comment]
Unfortunately, this seems like this is outside my scope of knowledge and you may need to wait for the developer of ChatControl to respond to this issue.

---

**In the time being, can you confirm these details:**

The weird symbol didn't show for the placeholderapi command but did for the chatcontrol command?

Are you using bungeecord (or a fork such as waterfall)?

Are you using Velocity?

Is MySQL enabled for ChatControl?

**Comment by Malachiel87** [comment]
yes mysql is true and i am using velocity (not using the chatcontrol on it)  and that only happen on chatcontrol command

**Comment by kangarko** [comment]
No idea, since you're using VelocityControl then we'll have to wait for @relavis to answer this, he's responsible for Velocity development.

**Comment by Malachiel87** [comment]
I am not using chatcontrol on velocity...

**Comment by kangarko** [comment]
Sorry I misread!

Can you please try using Notepad++ and trying to change encoding of your server.properties file so that this weird character is shown? Make sure to backup the original file since some encodings will crash: https://github.com/kangarko/ChatControl-Red/wiki/Use-Right-Encoding

**Comment by Malachiel87** [comment]
i already use notepad++ and use the right encoding (UTF-8) and it still happening

**Comment by kangarko** [comment]
No idea sorry, needs more investigation, will be having a look when I can

But if you are not using velocitycontrol then you could theoretically just hardcode the server name there instead of using placeholder or I am getting it wrong?

**Comment by Malachiel87** [comment]
i use commandforward plugin  for send the command to bungee using chatcontrol

**Comment by kangarko** [comment]
Yeah then you could just write your server name there or not?

**Comment by Malachiel87** [comment]
yeah it work fine  if i do it

**Comment by kangarko** [comment]
Awesome, going to postpone this issue since I am recording right now, just use the name itself for now & thanks!
