### ISSUE TITLE
1.18.1 : java17 i can't use chatcontrol ; ;

### ISSUE THREAD

**Issue by humi0707** [kangarko/ChatControl#1648]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false
![1642086604895](https://user-images.githubusercontent.com/48069005/149355941-f62c77fb-a095-4aab-96a9-784c77f0a5e5.jpg)

**Comment by kangarko** [comment]
Odd, are you using PaperSpigot? Other forks and base CraftBukkit is known to case bugs since they've changed the settings internally in 1.18. Try on Paper at papermc.io. Closing, but let me know if you will still have issues.

**Comment by humi0707** [comment]
i'm using spigot (CraftBukkit version 3397-Spigot-f4ff00f-f3828bb (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT))
i will try on paper later, thanks.
