### ISSUE TITLE
How do i add word in whitelist

### ISSUE THREAD

**Issue by aBo0oDGamer** [kangarko/ChatControl#165]
I want to add new word to the whitelist but wen i add it stil can't show in chat (***) how can i add it?
Note I add it in anti cobs

**Comment by kangarko** [comment]
Which whitelist?

**Comment by aBo0oDGamer** [comment]
Anti caps ***
Sorry for bad English

**Comment by aBo0oDGamer** [comment]
Ohh you are very speed :D
Whitelist in the settings.yml

**Comment by aBo0oDGamer** [comment]
Whitelist in the settings.yml in the anti caps

**Comment by aBo0oDGamer** [comment]
Here i add anal but it dose work 
Sorry for the bad word but the players always write another word but it show (****) so i want to make it in the whitelist 

Anti_Caps:
  Enabled: true
  Warn_Player: true
  
  # Ignore player names. Exclude them from caps percentage and caps in a row check.
  # Enabling is not recommended on a bigger servers (50+ slots) due to iterating over every player (laggy).
  Ignore_Usernames: false
  Min_Message_Length: 5
  Min_Caps_Percentage: 50
  Min_Caps_In_A_Row: 5
  Whitelist:
  - OMG
  - LOL
  - WTF
  - WOW
  - ROFL
  - ANAL

**Comment by kangarko** [comment]
That's whitelist for anti-caps. You are trying to allow a swear word.

To do this, you need to remove the rule that blocks it. Open rules/rules.txt folder, use CTRL + F to search for 'anal', and remove the following rule:

```
# Blocks 'anal'
match \b(a+(\W|\d|_)*n+(\W|\d|_)*a+(\W|\d|_)*l+(\W|\d|_)*)
ignore string analog|an all
handle as swear
```

**Comment by aBo0oDGamer** [comment]
Ok thanks very much i do this but i will check it later but i thing it will work fine 
Thanks very much you are the best author :D
40 m you fix everything thanks
