### ISSUE TITLE
ChatControl Red 10.9.3 is editing my formats, breaking them, then shutting the plugin down before boot.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1650]
I updated to 10.9.3 from 10.9.2, and whatever you did in 10.9.3, its taking all my gradients.

Where my config was 
```
  Bracket_Start:
    Message: 'STAFF&r '
    Gradient: '#55FFFF - #5B86E5'
```

its automatically replacing to
```Gradient: x§7§2§8§9§d§a - §x§9§9§a§a§b§5``` breaking itself, and then telling me there's an error with my formatting! Even if I push my backups, it still does it.

I did enable MySQL if that has anything to do with it, I also disabled the tab complete protection, enabled Anti Caps and enabled the points system.
Not sure how any of those would auto edit my formats for all gradients!

Minecraft Version: PurPur 1.18.1
MySQL: true
BungeeCord: false

**Comment by kangarko** [comment]
Aww, lovely Paper and Spigot breaking things again. Let me have a look into this asap.

**Comment by kangarko** [comment]
Fixed!!! ![a](https://i.imgur.com/Vz3PKB6.png)

Truth to be told, not sure if that was my mistake or on Spigot, since I also did code changes on my end that could result in the color being saved literally not explicitly. Probably my mistake so we can fix it asap!

**Comment by TomLewis** [comment]
Thanks man! I should really add you to my chatcontrol repo so you can always have an upto date set of configs to test with!

**Comment by kangarko** [comment]
Sure, it's matej@matejpacan.com if you're hosting that on GitHub.
