### ISSUE TITLE
Bring back the Private_Message_Match option from BungeeControl Pro

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#1651]
Now that we have finally switched to ChatControl Red and BungeeControl Red, one of the most common complaints I get is that you must use someone's full name when sending them a private message.  I think BungeeControl Red should bring back the option for partial name matching when sending private messages.

This was in the BungeeControl config before:
```
#
# A match need in Private_Messages to "find" a player.
# Set any value from 0.0 to 1.0 (match in percent, equals to 0% to 100%) or 1.0 to disable.
#
Private_Messages_Match: '0.8'
```

**Comment by kangarko** [comment]
Thanks, however it never worked and brought more issues than good. I do not have the time to spend another two months debugging some weird behavior, so I prefer stability over featureset and this feature will be reconsidered at the next major rewrite for now. Thanks!
