### ISSUE TITLE
Add an index in chatcontrol_logs DB

### ISSUE THREAD

**Issue by haeiven** [kangarko/ChatControl#1652]
Hello,

To improve performance, an index should be added in chatcontrol_logs table. Without an index, the MySQL server need to read the whole table each time we need logs, that's not efficient.

**Comment by kangarko** [comment]
Thanks, going to do so in the next update when you regenerate the table. You can add the column manually on the next version to retain old data: https://i.imgur.com/zbe2q21.png

**Comment by kangarko** [comment]
Table will still work even without doing the update manually to preserve backward compatibility
