### ISSUE TITLE
1.18 placeholder issues

### ISSUE THREAD

**Issue by TropTeps** [kangarko/ChatControl#1654]
I cannot put two placeholders in any of the same lines of the format configs.

Example:
Input:
  prefix1:
    Message: ' &e%kingdoms_members%&7/%kingdoms_max_members%'
Output:
    Message: ' &e%kingdoms_members%&7/%kingdoms_max_members%'

I've tested other placeholders as well any other placeholders that are on the line together break - If separated into 2 different sections the placeholders work. I cannot for the life of me find anything that would break this but if I could get any help at all that would be awesome. 

Example
Input:
  prefix1:
    Message: ' &e%kingdoms_members%&7/'
  prefix2:
    Message: '&e'%kingdoms_max_members%'
Output:
    Message: ' 1/10'

Minecraft Version: 1.18
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> I cannot put two placeholders in any of the same lines of the format configs.
> 
> Example: Input: prefix1: Message: ' &e%kingdoms_members%&7/%kingdoms_max_members%' Output: Message: ' &e%kingdoms_members%&7/%kingdoms_max_members%'
> 
> I've tested other placeholders as well any other placeholders that are on the line together break - If separated into 2 different sections the placeholders work. I cannot for the life of me find anything that would break this but if I could get any help at all that would be awesome.
> 
> Example Input: prefix1: Message: ' &e%kingdoms_members%&7/' prefix2: Message: '&e'%kingdoms_max_members%' Output: Message: ' 1/10'
> 
> Minecraft Version: 1.18 MySQL: false BungeeCord: false

Hey, please replace `%%` with `{}`.
