### ISSUE TITLE
Problem with ItemsAdder Emojis

### ISSUE THREAD

**Issue by DarthZeroX** [kangarko/ChatControl#1655]
Hi, I'm using ChatControl Red version 10.9.3 and ItemsAdder plugin version 2.5.4-beta2, and it happens that when I use an emoji from the Itemsadder , like " :sad: " it appears in the chat in that way as shown in the image below.

When using ChatControl Pro, there was no problem.

![Captura](https://user-images.githubusercontent.com/31554523/149645354-f8d37087-8a1d-4cc6-876a-e4b8203091f1.PNG)

**Comment by kangarko** [comment]
Try tweaking https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities, also try testing without ViaVersion or similar if you use that.

**Comment by DarthZeroX** [comment]
> Try tweaking https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities, also try testing without ViaVersion or similar if you use that.

I tried to remove Viaversion first and the error keeps happening. Then try each option in the chat priorities but the error still persists.

**Comment by kangarko** [comment]
I am sorry, this appears incompatible as of now. Looks like it broke a few versions ago, my plate is super busy these days so I will have to postpone it a bit and have a look later, thanks.
