### ISSUE TITLE
1.12.2: Color permission issues with wildcard *

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#1656]
Minecraft Version: 1.12.2
MySQL: true
BungeeCord: false

I have a group vip that have the permission chatcontrol.color.* but since i don't want them use magic  i negated chatcontrol.color.magic, the vip people can still use magic character and any negated permission, it was working fine on chatcontrol pro.
I am using luckperms as permission manager

**Comment by kangarko** [comment]
The name has changed from "magic" to "obfuscated", so it's "chatcontrol.color.obfuscated".

I will update the wiki, thanks!
