### ISSUE TITLE
1.18.1 The rule "ignore comand" is not working

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#1657]
Minecraft Version: 1.12.2
MySQL: true
BungeeCord: false

I noticed from fresh chatcontrol red, all comand inside groups.rs supposed to be ignored by antiswear and antias  like //,/login,/register,/tell,etc... these are keeping to triggering the antiads and antiswear, instead to be ignored, i tried also to add them one by one for each rule on global, same issue....

**Comment by kangarko** [comment]
I cannot reproduce (the first chat message was caught from /test, the second from /login was not): 
![a](https://i.imgur.com/5PUkVpH.png)

Without any bypass permissions. Please provide me an example of your rules file with the "ignore command" operator so I can test...

**Comment by Malachiel87** [comment]
i give you the full debug package with all files
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7883909/debug.zip)

**Comment by kangarko** [comment]
You did not have ignore command in your group.rs, try putting it there: https://i.imgur.com/gHx1vCb.png

**Comment by Malachiel87** [comment]
i removed from here because was not working and i tried to use it on each rule on global.rs

**Comment by kangarko** [comment]
Try the next release, I literally typed /login and it was ignoring it fine. Check your permissions and try on a guest account without perms

**Comment by Malachiel87** [comment]
Tested on 1.10.4 the issue is still here
![image](https://user-images.githubusercontent.com/3611852/149848289-647d3c7b-3ac3-4ccc-aa83-f0017d9d8ebc.png)

**Comment by kangarko** [comment]
Can you try with just one "ignore command"? You have it two times there, maybe that's the bug

**Comment by Malachiel87** [comment]
I manage to fix by restoring the rules and now all working, except for worldedit comands with double slashes that are keeping to flag, any idea why?

**Comment by TheIntolerant** [comment]
after some testing on a fresh install, it seems that while you can use ``ignore command`` on multiple lines. Testing this on the swear filter I can confirm that with this.
```rs
# Ignore WorldEdit
ignore command //
```
It won't block ``//test fuck`` but will block ``// fuck`` so in other words, the ``ignore command`` only checks for the first argument, so if you use ``ignore command //|//test`` etc it would block both "//test fuck" and "// fuck".

**Comment by kangarko** [comment]
Thanks! I will patch this internally to the next version.
