### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by CryLegende** [kangarko/ChatControl#1658]
Hello, I don't know where to contact you so I'm here
Since the Xenforo update of McMarket, I can't download ChatControlRed anymore
![image](https://user-images.githubusercontent.com/25080946/149791824-3721aefa-eea2-46a8-86a5-a4300e9831ff.png)
When I click, I get an error
![image](https://user-images.githubusercontent.com/25080946/149792081-a116f0c4-4a79-4071-84ab-1bc665efa841.png)
Thank you for your help !

**Comment by kangarko** [comment]
What is your MCMarket username?

**Comment by CryLegende** [comment]
Cry_Legende

**Comment by kangarko** [comment]
Thanks, renewed :)
