### ISSUE TITLE
1.16.5: How to use gradients?

### ISSUE THREAD

**Issue by NathanieReborn** [kangarko/ChatControl#1659]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

Hi there! I am currently trying to use color gradients for PEX prefixes. I have read the "chat.yml" file and some other gradient issues on this github, but I don't really understand how does it work at all. 

Mi intention is to get a [STAFF] prefix using yellow-orange gradient, and the plugin I am using to manage groups is PEX. Which would be the steps I should follow?

Thank you so much!

**Comment by kangarko** [comment]
You can use Gradient in your format part, such as this here:

![a](https://i.imgur.com/rONRBxK.png)

You will need to use ChatControl for that not PEX since it does not support it afaik.
