### ISSUE TITLE
/chc output credits

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#166]
A while ago, i started a spigot conversation: http://prntscr.com/vq04v8 with kangarko about making the /chc output customizable. So if a player type /chc it will not show "Running CHC Red". I want to have a simple "no permission" message if a player type /chc it will say: You dont have permission for this command. It would be so nice if you can make the credits configurable.

credits:
   - 'firstline'
   - 'secondline'

It would be so nice if this gets implemented.

**Comment by OfT3N** [comment]
> A while ago, i started a spigot conversation: http://prntscr.com/vq04v8 with kangarko about making the /chc output customizable. So if a player type /chc it will not show "Running CHC Red". I want to have a simple "no permission" message if a player type /chc it will say: You dont have permission for this command. It would be so nice if you can make the credits configurable.
> 
> credits:
> 
> * 'firstline'
> * 'secondline'
> 
> It would be so nice if this gets implemented.

You have "packets.rs" in your /rules/ folder, and there you can change any output from any server message as I guess

**Comment by kangarko** [comment]
Thanks, added tutorial: https://github.com/kangarko/ChatControl-Red/wiki/Localization#customizing-channel-or-chc

**Comment by kangarko** [comment]
So you can just rewrite this to the no permission message

**Comment by DevJoey** [comment]
> 
> 
> So you can just rewrite this to the no permission message

The problem is, it is very buggy with packets because if you use via version, the packets will not work correctly

**Comment by DevJoey** [comment]
> 
> 
> So you can just rewrite this to the no permission message

It would be nice if fully translatable /chc output will be added

**Comment by kangarko** [comment]
Already added, see https://i.imgur.com/eIgfogP.png in Commands section of your localization file.

**Comment by DevJoey** [comment]
> 
> 
> Already added, see https://i.imgur.com/eIgfogP.png in Commands section of your localization file.

Thank you so much for adding this.
