### ISSUE TITLE
License issue.

### ISSUE THREAD

**Issue by iSilviu-debug** [kangarko/ChatControl#1661]
I have a problem with my ChatControl Red license.
In practice, it comes out that I have to renew the license but when I click on it it gives me an error. 
How can I solve? Thank you!
![image](https://user-images.githubusercontent.com/67197594/149890564-48638e00-ee53-4a81-b254-f448ccb477af.png)

![image](https://user-images.githubusercontent.com/67197594/149890613-6c2575d1-cb39-4129-9f71-0af04e6fc5ce.png)

mcmarket account number: 220070

**Comment by TheIntolerant** [comment]
Hey, due to the recent maintenance on mc market some people seemed to lose their license for chatcontrol. To fix this go to <https://mineacademy.org/chatcontrol-red#upgrade> and fill out the form to get this sorted.
