### ISSUE TITLE
1.18.1 When using "then command <command1|command2>" in groups.rs how do I use {message}

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1662]
Can I use {message} when using groups.rs when it comes to issuing commands?
The old chatcontrol pro was much simpler to run multiple commands with options:

Old chat control:
```
  Execute_Commands:
    - 'warn {player} Racist comments.'
    - eco take {player} 25
    - 'kick {player} &cRacism is not acceptable on PirateCraft.\n\nMessage caught: {message}'
    - 'tempmute {player} 24h Racist comments. \n\nMessage caught: {message}'
```

The tempmute is sent to banmanager and logged in our sytem with what they said for easy seeing if it caught a false posative.

But the new system on the Wiki page says it only has `{player}` not the caught `{message}`.
Will {message} work?

It dousnt work well as one big line....
```
group racist
ignore perm chatcontrol.bypass.racist
then command /warn {player} Racist comments.|/eco take {player} 25|/kick {player} &cRacism is not acceptable on PirateCraft.\n\nMessage caught: {message}|/tempmute {player} 24h Racist comments. \n\nMessage caught: {message}
then deny
```

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: false

**Comment by TheIntolerant** [comment]
I believe you meant to use "then console" instead of "then command" as that makes the player run that command whereas the then console operator runs the command via the console.

Also you should be able to use either of these operators on multiple lines without issues, if you didn't want to have a massive line.

**Comment by kangarko** [comment]
I think the message variable should work as of a recent update we did. As @TheIntolerant said, you need to use "then console" to run this from the console.

```
then console /warn {player} Racist comments.
then console /eco take {player} 25
then console /kick {player} &cRacism is not acceptable on PirateCraft.\n\nMessage caught: {message}
then console /tempmute {player} 24h Racist comments. \n\nMessage caught: {message}
```

I understand the old chatcontrol was simpler but it was more limited in the sense it lacked different operators, and people requested more flexibility in their setups.

**Comment by TomLewis** [comment]
Do I have to use the `/` beore all commands?

**Comment by kangarko** [comment]
I don't think so, the plugin should just append it if you don't do it.

**Comment by TomLewis** [comment]
Alright thanks, I was just curious from your exmaple above and I have mixed, some do, some dont, wasnt sure what the best practise was. I will just add them to make sure.
