### ISSUE TITLE
1.18 Sound Notify

### ISSUE THREAD

**Issue by Kyrobi** [kangarko/ChatControl#1664]
Minecraft Version: 1.8.1
MySQL: false
BungeeCord: false

Hello, I'm wondering if I'm using the sound notify right.
I've given the players the `chatcontrol.soundnotify` and have enabled the settings in the settings.yml file.
However, when I do something like `@Kyrobi`, nothing happens

**Comment by kangarko** [comment]
Make sure you are on the most recent version, I recently patched an issue like this. Let me know below if that still happens, and include your /chatcontrol debug ZIP folder if so.

**Comment by Kyrobi** [comment]
Seems like this is still an issue. My debug file: 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7922865/debug.zip)

**Comment by kangarko** [comment]
I apology, but that feature requires channels enabled because it uses channel API to split messages into pieces and inject colors for sound notify inside them.
