### ISSUE TITLE
Suggestion: Ability to reply back to vanished people if they messaged you while in vanish

### ISSUE THREAD

**Issue by Plumzie** [kangarko/ChatControl#1665]
Often mods and admins have to message players while in vanish. They don't wish to show themselves to everybody, but may need to message someone for information on a hacker/issue. The only way to contact the person who messaged you would be via `/r` or `/reply` because `/msg <player>` would be able to be abused to see people vanished at any time they like. Another consideration is if a player messaged a vanished person *before* they went into vanish it wouldn't count and cancel out.

**How it would benefit others?**
It would benefit others as almost every server has vanish and staff that have to use it often. If other don't like it there should most likely be an option to turn it off.

**What would happen if we won't implement this feature?**
If this feature wasn't implemented I'd say that a custom /staffmsg command would have to be created. This is a little bit of a pain because players wouldnt know that they have to use it and overall can be slightly messy.

**Comment by kangarko** [comment]
Thanks! I do recommend creating a /helpop command, we do have examples of this in rules/commands.rs file though. However, if more people request this, I am willing to spend time and implement sort of this system.
