### ISSUE TITLE
Renewed licence on MC-Market impossible

### ISSUE THREAD

**Issue by Tylwen** [kangarko/ChatControl#1666]
![image](https://user-images.githubusercontent.com/26263998/150413468-4210fbb0-7a79-46b8-8ec2-c35267208dc6.png)

**Comment by ElBananaa** [comment]
Hey, this issue appeared since mcmarket deployed XF 2.0. To get your access back, please fill in the upgrade form here then wait for Kangarko to get back to you https://mineacademy.org/chatcontrol-red#upgrade
