### ISSUE TITLE
Plugin is disabled

### ISSUE THREAD

**Issue by Invectix-Dev** [kangarko/ChatControl#1667]
https://pastebin.com/ZmZcz0Lj

**Comment by ElBananaa** [comment]
Hey,
Please stop your server, delete the data.db file, then start the server and complete the tour again.
You can run `/chc tour <secretWord>` (replace `<secretWord>` with the word given in our terms) directly, no need to go through the whole tour again.
Also, next time, please follow the bug report format ;)

@kangarko You may need to take a look at this however, I don't know what's the cause of this issue, but already fixed it by doing what I said above with another user on discord a few hours ago ^^

**Comment by Invectix-Dev** [comment]
This seems to have fixed it. Thank you.
