### ISSUE TITLE
1.18.1 | Cannot use nested Placeholders (Placeholder API)

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#1668]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

This falls somewhere between a feature request and a bug report, but I'll submit it as a bug as it's an unexpected behavior.  

Placeholder API supports placeholder nesting, or placeholders used within other placeholders. For example, `%gradient_message_#f08322_#a40000_{luckperms_suffix}%` would produce a gradient from orange to red, with the text of whatever the player's suffix in Luckperms is set to. At least, this is how it works in most plugins that support PAPI placeholders.

ChatControl, whether due the fact it requires placeholders surrounded by curly brackets or another reason, doesn't appear to support nested placeholders. I've tried various forms of the above code, for example:

`{gradient_message_#f08322_#a40000_{luckperms_suffix}}`
`{gradient_message_#f08322_#a40000_[luckperms_suffix]}`
`{gradient_message_#f08322_#a40000_luckperms_suffix}`
`{gradient_message_#f08322_#a40000_"{luckperms_suffix}"}`

But, I've had no success getting this to work. Though I used the gradient expansion in my examples, this issue is with any nested placeholder and a rather large limitation.

**Comment by kangarko** [comment]
I apology, we do not support this at the moment. It's on the long-term roadmap, something I can have a look into on the next rewrite, however right now I am recording my training programs and my plate is simply but honestly full.
