### ISSUE TITLE
1.18.1: HEX codes. Not showing the right color in-game (darker/dim)

### ISSUE THREAD

**Issue by Tosfoy** [kangarko/ChatControl#1669]
Hello!
I currently have an issue where the hex codes used in the chat formating aren't showing their true colors.
They appear to be darker than normal. I used a color picker to determine if it was just an illusion but I was right, it shows a lot darker than normal. 
For example, the color I chose for the name (#CE3334) shows up as B12D2E (or similar) in-game.

Here's to show it def is a problem with ChatControlRed, as hologramDisplay shows the right color:
https://gyazo.com/406db33b9e10325493652759812fe7f5
Also tab-premium shows the right color (luckperms prefix), it's really just a chat problem. 

The only way to fix this so far is by making the colors a bit brighter than they actually are, but this is a bummer and I wish it wasn't displaying a darker version of the hex code.

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7910254/debug.zip)

**Comment by kangarko** [comment]
No idea, but can you test another chat plugin to see if it really renders it differently than us? Because Holograms are rendered differently using the client. Haven't seen an issue like this so far, I believe it may as well be a client issue.

**Comment by ElBananaa** [comment]
Hey,
I just ran tests on my end with VentureChat, and these are the results. (I used the `#87FF00` color)

**Venture Chat Output**
![image](https://user-images.githubusercontent.com/53318613/150711100-996ee476-e28f-4c68-a7c5-b09278dbf64a.png)

**ChatControl-Red Output**
![image](https://user-images.githubusercontent.com/53318613/150711123-435b4eba-6433-4991-83b3-d0f01c645d85.png)

I then used an expansion to get the hex color from both images, and both colors are matching: `#85FB00` & `#85FB00`.
So yes, it seems more like an "issue" with how the game itself handles colors for the chat and the tablist/entity names(or holograms)/scoreboards.

I highly doubt this is something related to chatcontrol ^^

**Comment by kangarko** [comment]
Interesting. Yeah I use ShareX tool on Windows and comparing using their on-screen color picker the colors also are the same. Closing, likely a client rendering issue (or a feature?).

**Comment by Tosfoy** [comment]
Any ideas what could be causing this?
For example, the color 87FF00 ElBanana used shows as 79DB0D for me

**Comment by Tosfoy** [comment]
FIXED!

It was an issue with Java being out of date.
