### ISSUE TITLE
[PRO VERSION] Bungee Support

### ISSUE THREAD

**Issue by Steev93** [kangarko/ChatControl#167]
Error:

http://pastebin.com/yfiRwmcB

See Config below;

http://pastebin.com/u30zwLRv

**Comment by kangarko** [comment]
Enable bungeecords in settings.yml: BungeeCords.Enabled -> true and install plugin BungeeControlBridge on bungee.

**Comment by Steev93** [comment]
Hey,

I have done that but seem to be getting errors still ?

**Comment by kangarko** [comment]
Ensure the server was stopped and started again after configuration changes.

If an error appears again, it's not the same error, and so please post it :)

**Comment by kangarko** [comment]
Closing, remind me if issues persist.

**Comment by Steev93** [comment]
Sorry for a late reply i locked myself out of my account and then forgot about it. We just disabled it in the end was unsure what was causing the issue
