### ISSUE TITLE
Mohist Compatibility

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#1672]
When i try to run chatcontrol red with mohistmc it crash the server, i would like to find a way to make it compatible
log before crashing: https://pastebin.com/qi2y81V5
crash log: https://haste.mohistmc.com/legabolaza.rb

**Comment by kangarko** [comment]
They are lacking a ton of stuff and libraries, it would take me more time than I have right now and there have been <2 complains about this in the last year or so, sorry I need to focus on higher priorities right now.
