### ISSUE TITLE
1.18.1: Timed message only plays sound for 1 player instead of all players

### ISSUE THREAD

**Issue by Nextinka** [kangarko/ChatControl#1674]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

As the title says, for some reason the sound that triggers in timed.rs does not work for the entire server, but only for 1 player that has joined first. Once you leave the server, the second player will be able to hear the sound without problem. Is this a bug or something wrong on my side?

timed.rs config:
![image](https://user-images.githubusercontent.com/98180136/150573737-c2d5f1e9-f69e-4cfd-8d8d-1ad441b9898e.png)

advert1 config: (other advert configs are identical)
![image](https://user-images.githubusercontent.com/98180136/150573816-bc9ead67-f7f1-460e-9e5c-bacc2996d089.png)

Attaching debug report right here:
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7915594/debug.zip)

**Comment by kangarko** [comment]
Investigating in 24h

**Comment by kangarko** [comment]
Thaniks, fixed!
