### ISSUE TITLE
1.18.1: NICK HEX 

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#1675]
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

NICK does not support HEX, I don't include HEX code when I check it on SQL, I need to change SQL directly to make NICK use HEX

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.18.1 MySQL: true BungeeCord: true
> 
> NICK does not support HEX, I don't include HEX code when I check it on SQL, I need to change SQL directly to make NICK use HEX

Hey,
I'm not sure to understand your issue. You should be able to use hex colors using in the format file directly, don't you?

**Comment by BearLeonLight** [comment]
> > Minecraft Version: 1.18.1 MySQL: true BungeeCord: true
> > NICK does not support HEX, I don't include HEX code when I check it on SQL, I need to change SQL directly to make NICK use HEX
> 
> Hey, I'm not sure to understand your issue. You should be able to use hex colors using in the format file directly, don't you?

But it doesn't work when I use /tag nick, or am I using it wrong?

**Comment by kangarko** [comment]
IT does support HEX, you need to check if you have the right permission, see the documentation of Colors in settings.yml. If that still wont work, let me know exactly what problem you are having below.

**Comment by BearLeonLight** [comment]
> > > Minecraft Version: 1.18.1 MySQL: true BungeeCord: true
> > > NICK does not support HEX, I don't include HEX code when I check it on SQL, I need to change SQL directly to make NICK use HEX
> > 
> > 
> > Hey, I'm not sure to understand your issue. You should be able to use hex colors using in the format file directly, don't you?
> 
> But it doesn't work when I use /tag nick, or am I using it wrong?

I see Markdown which I mainly want, but it doesn't work when I actually use it.
