### ISSUE TITLE
MineDown support 

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#1676]
1. Friendly to those who use SRV

2. It is also more convenient for those who are used to using MineDown

I hope that MineDown support can be added, and MineDown is not processed in the messages that can be sent to Discord->Minecraft, but Discord->Minecraft needs to be processed at the same time, so that both Discord and Minecraft can display the same message in the same way.
[MineDown](https://github.com/Phoenix616/MineDown)

**Comment by ElBananaa** [comment]
Hey!
Wouldn't it be more interesting to use Adventure (which is included in paper since 1.16.5) instead of MineDown? (I don't know much about MineDown, which is why i'm asking ^^)

**Comment by BearLeonLight** [comment]
Adventure? This I don't know what is connected?
MineDown is like the bottom line, strikethrough and other formats of Discord, you can click and link I have put it in.

**Comment by ElBananaa** [comment]
> Adventure? This I don't know what is connected? MineDown is like the bottom line, strikethrough and other formats of Discord, you can click and link I have put it in.

Yeah I know MineDown is basically a chat formatting library that aims to replace spigot's internal library. Adventure is pretty much the same (I believe) but with more features?
Here's their doc https://docs.adventure.kyori.net/minimessage

**Comment by kangarko** [comment]
Thanks for the suggestions guys!

Right now I am recording new training programs, but I can return to this in a few months, I will not be able to take up suggestions this big until then.

**Comment by BearLeonLight** [comment]
> > Adventure? This I don't know what is connected? MineDown is like the bottom line, strikethrough and other formats of Discord, you can click and link I have put it in.
> 
> Yeah I know MineDown is basically a chat formatting library that aims to replace spigot's internal library. Adventure is pretty much the same (I believe) but with more features? Here's their doc https://docs.adventure.kyori.net/minimessage

I see Markdown which I mainly want, but it doesn't work when I actually use it.

**Comment by ElBananaa** [comment]
This is normal, using any of these 2 libraries requires a lot of internal changes ^^
