### ISSUE TITLE
1.18.1: How can I use placeholders in 'match' rule operator?

### ISSUE THREAD

**Issue by Nextinka** [kangarko/ChatControl#1677]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

I am trying to use 'match {player}' in the .rs file, but I'm unable to because the {} brackets already have meaning in regex, and it keeps throwing an error.

**Here's what I'm trying to do, I want to make /tag nick to change your MC username's color, not your actual username.**
![image](https://user-images.githubusercontent.com/98180136/150651959-e1493393-489f-4dfc-b86d-9c0046f2adb6.png)

**Here's the error it throws:**
![image](https://user-images.githubusercontent.com/98180136/150652019-7cbb71d7-a344-4286-bcf3-05e94879bcd2.png)

**Full error log:**
[error.log](https://github.com/kangarko/ChatControl-Red/files/7919088/error.log)

**What have I tried?**
- /{player/} does not return errors, however it breaks the placeholder and returns {player}
- putting it into ""
- putting save key player "{player}" and then putting match player after that, throws errors aswell
- %player%

Is there a way to do this without rules, placeholders, or ignore regex there? Such as enabling something in config I missed or setting proper permissions. If not, I believe it would be a nice feature.

**Comment by kangarko** [comment]
This is unsupported by design, I apology.

However, you can have a look into "require script" which supports placeholders, but I cannot guarantee it will work as you intent. You can try using `require script "{message}" == "{player}"`

**Comment by TheIntolerant** [comment]
For anyone who may be wanting to do something similar, this was solved on discord with the following rule.
```rust
match (.*)
require script "$0" != "{player}"
then warn {prefix_error}You can only change the color of your nickname!
then deny
```
