### ISSUE TITLE
1.18.1: Unable to renew license and upgrade the plugin.

### ISSUE THREAD

**Issue by morfie78** [kangarko/ChatControl#1679]
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

We went to download the latest version of CCR from mc-market and it asked us to renew.  That's fine, we love the plugin and it is totally worth it.  When I clicked "Renew Now", it said that our license couldn't be renewed: https://puu.sh/IERff/637c45b727.jpg

We are unable to upgrade.  Please advise us on what we should do to fix this issue and get the latest version.
Thanks!

**Comment by TheIntolerant** [comment]
Please refer to #1680
