### ISSUE TITLE
BungeeControl join/leave messages

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#168]
A few months ago you told me with the new chat update (then labeled as CHC 9) it would be possible to have different global join/leave messages per group. For example I would like to give my patreons a heart symbol in front of their join and leave messages. Is this still planned?

**Comment by kangarko** [comment]
That is totally possible, you would have to create two rules in messages/join.rs (or other files)

````
group donator
require sender perm chatcontrol.group.donator
bungee
message:
- &8[&c<3&8] &7{player} &fhas joined the game

group default
bungee
message:
- &8[&2+&8] &7{player} &fhas joined the game
````
