### ISSUE TITLE
ERROR ON NEWEST VERSION

### ISSUE THREAD

**Issue by dangerORclose** [kangarko/ChatControl#168]
This error on free version
http://pastebin.com/xUdaXytQ
My server is running CraftBukkit version git-Spigot-7d78b81-e2a288c (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by kangarko** [comment]
Redownload the latest version, and ensure you are NOT using any plugin manager or reloader. When updating plugin, always do a full server stop and then start it again.
