### ISSUE TITLE
CAN'T RENEW LICENSE? READ THIS

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1680]
> #### **IMPORTANT LICENSE INFORMATION**
> 
> MC-Market is back up, seems like some people are starting to lose their license. That was caused by me setting the expiration date to 12 months and the renewal fee to $0, which seems to have not been the case with the new version of Mc-Market.
> 
> If you lost your license, simply resubmit the upgrade form at https://mineacademy.org/chatcontrol-red#upgrade (you can submit it for other plugins there, too) and we'll approve it within 1-3 days maximum.
> 
> Thanks
> Matej

As quoted by @kangarko on discord.

Please keep in mind this was posted some time ago as a result, there currently is no ETA as to when you will get approved but it should happen within a few days in most cases.

**Comment by kangarko** [comment]
Thanks, will be useful for now!
