### ISSUE TITLE
Here you have a gradient addon for your plugin

### ISSUE THREAD

**Issue by Rick-Sanchez-C** [kangarko/ChatControl#1683]
1. Can add auto gradients to their chats and looks cool

![image](https://user-images.githubusercontent.com/87280286/151357015-5443d548-975f-4a01-ab94-fda502da32b9.png)

https://github.com/Rick-Sanchez-C/BetterColor

I did it for the version published in this github, if i could have access to the api of the newest version, i can update it if smth is broken

**Comment by kangarko** [comment]
Thank you! You can request a developer license at mineacademy.org/chatcontrol-red#upgrade
