### ISSUE TITLE
1.8.8 Possible spam/flood with combatlogX

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#1684]
When the player die for combalogx this error flood will be spammed, I think it should be hidden
https://www.toptal.com/developers/hastebin/budagaqupo.yaml

Minecraft Version: 1.8.8
MySQL: true
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey,
It seems like an issue with CombatLogX not providing a kill reason when a player logs in/out during a fight.
This could potentially be fixed using their API, I guess : https://github.com/SirBlobman/CombatLogX/blob/main/api/README.MD#events

I suggest waiting for Kangarko to see what can be done. ;)

**Comment by kangarko** [comment]
I will make the message appear once per 30 minutes only.
