### ISSUE TITLE
[INVALID FORMAT] Add new JSON action for format

### ISSUE THREAD

**Issue by SheerYin** [kangarko/ChatControl#1686]
/tellraw @p [{"text":"1","color":"white","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"clickEvent":{"action":"copy_to_clipboard","value":"123"}}]

"action":"copy_to_clipboard"
Easily copy chats to Windows clipboard

**Comment by ElBananaa** [comment]
@SheerYin Please update the format of your feature request, as requested when creating a new github issue.

**Comment by kangarko** [comment]
No idea what's going on here, as Banana said, reopen the issue following our guideliness.
