### ISSUE TITLE
1.18.1 - Permission bug for hex color codes

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1689]
### **Bug description**
The permission ``chatcontrol.use.color.{apply_on}`` such as ``chatcontrol.use.color.chat``, ``chatcontrol.use.color.nick``, ``chatcontrol.use.color.prefix`` etc only works on normal color codes, NOT hex color codes when negated.

In short:
Regardless if a user has the permission ``chatcontrol.use.color.chat`` etc. negated, they are still able to use hex color codes in any channel. 

```
@Permission(value = "Allow players use & and hex colors. Replace apply_on with Colors.Apply_On sections from settings.yml (by default players can use colors everywhere)", def = true)
public static final String USE = "chatcontrol.use.color.{apply_on}";
```
Affected permission nodes include:
- ``chatcontrol.use.color.chat``
- ``chatcontrol.use.color.me``
- ``chatcontrol.use.color.nick``
- ``chatcontrol.use.color.prefix``
- ``chatcontrol.use.color.private_message``
- ``chatcontrol.use.color.suffix``

---

### **Steps to reproduce**
In this example, I will use the chat.

1) Make sure you can use both normal and hex color codes in chat, by saying something like **&btest1 &#a12892Test2**
2) Negate the permission node ``chatcontrol.use.color.chat``
3) Repeat step 1, to see if the color codes stop working

---

### **Expected behaviour**
All color codes should no longer be able to be used in chat.

---

### **Actual behaviour**
Once the permission node mentioned above has been negated, the regular color codes stop working however the hex color codes continue to work regardless if the user has the correct permission node negated.

---

Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

**Comment by TheIntolerant** [comment]
### **Extra note**
As well as the permission bug, the usage of hex color codes can still occur even for users who wish to have zero usage of ANY color codes and have their settings under the colors section is as follows:
```yml
Colors:
 
  # Where should we let players to use & or RGB color codes?
  # Options: chat, me, prefix, nick, suffix, private_message
  Apply_On: []
```

**Comment by Sikatsu** [comment]
Thanks for testing this, I can confirm this bug!

**Comment by kangarko** [comment]
Damn you're always reporting the top issues, thanks! Having a look asap

**Comment by kangarko** [comment]
Thanks, fixed both issues!
