### ISSUE TITLE
Stop_On_First_Match Let us apply this on each message/.rs NOT Global!

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1691]
```  # Files in messages/ folder are read from top to bottom. A true value means that if you have
  # multiple messages there, we only send the first eligible message to the player (we evaluate
  # this for each player separatedly). A false value means players will see all messages
  # that are eligible for them. 
  Stop_On_First_Match: false
```

After spending about 30 mins trying to figure out why my grouped timed.rs are just only displaying the first set of messages thinking I have done something wrong, I came across `Stop_On_First_Match` which when I disabled fixed my multiple grouped messages in timed.rs start working! BUT with the caviet that it is now displaying ALL the death messages, kick messages, quick messages... this is bonkers. 

Please make Stop_On_First_Match a list like this;

```
  Stop_On_First_Match:
  - 'death'
  - 'join'
  - 'quit'
  - 'kick'
```

So I can remove `timed` from it! This would work well if we could actually set it what to do!

**Comment by TheIntolerant** [comment]
I suggested the same thing in #709 but we'll see what matej says again :P

**Comment by TomLewis** [comment]
@TheIntolerant ha! Brilliant, so its not just me then! They need to fix it, as the timed.js just does not work as it should with this setting.

**Comment by kangarko** [comment]
I see. Now that multiple people are requesting this, I should ship this to the next release!

**Comment by TomLewis** [comment]
Thanks man
