### ISSUE TITLE
timed.rs what permission to not show a group?

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1692]
I have a group of timed messages that I show to everyone, but when people are a certain rank I wish to not show these to them, what permissions do I give that group? Do I use one of these?

`ignore sender perm <permission> and ignore receiver perm <permission>`

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: false

**Comment by kangarko** [comment]
Use "ignore receiver". That will hide the message from appearing to people who have the given permission.

Using "ignore sender" won't make sense here, it's used on death messages to make the message not send, when the sender (the player who died) has the given permission.

**Comment by TomLewis** [comment]
Right so for the message group, use `ignore receiver perm missives.contributor` and give a permission `missives.contributor` to the Luckperms group with that permission I set there?

**Comment by kangarko** [comment]
Sorry for the delay, you were correct. It won't show to people having said permission.
