### ISSUE TITLE
Default colors for /chc announce chat

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1693]
When I use /chc announce chat (I have a alias for /an) there is no color to the text its black. Forcing me to use a color before it.
Is there an easy way to edit the default color the text will be in chatcontrol or do I need to edit this into my alias?

**Comment by TheIntolerant** [comment]
You can change this color in the local file, under ``Commands.Announce.Chat_Body_Line_Color``

**Comment by kangarko** [comment]
Thanks to Ezra for the easy tip, just edit the localization file and you'll be good to go :)

**Comment by TomLewis** [comment]
Brilliant thanks, nice and simple!

Maybe it's worth having a default of &e so it's not black text as default?

**Comment by kangarko** [comment]
<img width="276" alt="Screenshot 2022-02-02 at 13 22 36" src="https://user-images.githubusercontent.com/1918426/152152893-6521ebd6-8f3a-4514-83e9-9274ef06c54a.png">
Do you mean this config key? We're already prepending &f before so it should be white, can you send an example screenshot? Thanks

**Comment by TomLewis** [comment]
No look below it where it says `Chat_Body_Line_Color` the default color is `GRAY`, defaults should be white or yellow so the messages can be seen in chat, Not sure why GRAY was picked you cant read it! let alone a big popup annoucement! 
I changed mine to yellow.

**Comment by kangarko** [comment]
Thank you, I have corrected that on default installs.

**Comment by DeusNinja** [comment]
Would it be possible for hex support for the announcer? I seem to be breaking my announcer when I try.

**Comment by kangarko** [comment]
Thanks for the suggestion, will put this down for the future!
