### ISSUE TITLE
Add N word to global regex

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1695]
Im terrible at regex.

We have an N word filter(s)

```
# Blocks 'nigger' or 'niggar' and 'n i g g a r s' and 'n i g g e r s'
#OLD match (?:^|[^a-z])(n|N)\s*(i|I|1)\s*((g|G)\s*){2,}(?:e|a|E|A)*\s*(r|R)*(?:\s*(s|S)\s*)?(?:[^a-z]|$)
match (n)\s*(i)\s*((g)\s*){2,}(?:e|a)*\s*(r)*(?:\s*([a-z])\s*)
group racist

# Blocks 'nibber' or 'nibbar' or plural of any plus with spaces
match (?:^|[^a-z])((n|N)\s*((i|I|1)\s*){1,}((b|B)\s*){1,}(?:e|a)r*s*?)|(n\s*i\s*(b\s*){2,}(?:e|a)\s*r\s*s*)(?:[^a-z]|$)
group racist
```

Problem is we just got a false posative, for `an iggl` from a player saying `/c oh here is an igglo`.
https://regex101.com/r/KZ3sJW/1

This should be a word(s) that is included in the global list as its incredibly offensive.

So can you help me write a better regex for these words? then I can trial it for false posatives. 

You can see that I have an `#OLD match` which works better, but its 314 steps and 1.0ms! So its not fast.

**Comment by kangarko** [comment]
If you wish to block nigger then you can use the following filter, it's simply copied and edited from the other default filters in our global.rs file:

```
# Blocks 'nigger' or 'niggar'
match \b(n+(\W|\d|_)*i+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*(e|a)+(\W|\d|_)*r+(\W|\d|_)*)
group swear
```

I don't recommend matching spaces or weird abbreviations since this will cause too many false catches.

**Comment by TomLewis** [comment]
If you use the same structured regex for all your key words, why not just dynamically create this regex based on a word list? this would make it 10x easier for normal users of the pugin to just use either regex or write words into a list that you dynamically change to this secific regex.

**Comment by kangarko** [comment]
Thanks, you can use /chc rule add to dynamically create rules like that and we automatically insert them into the rs file :)

**Comment by TomLewis** [comment]
Oh wow I didnt know this! Save so much time! I hate regex.
