### ISSUE TITLE
1.16.5: Incompatibility with ItemsAdder

### ISSUE THREAD

**Issue by NathanieReborn** [kangarko/ChatControl#1696]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hi there! I have recently installed ItemsAdder and I am trying to use its Emoji function. If I put ": smile :" (all togheter), for example, a smiling emoji is shown in my chat msg. But when I try to do ": smile :", some weird code appears in the message. It is related to ChatControlRed since if I disable ChatControlRed, the problem is solved. Any suggestion? I would like to use both of them!
![with](https://user-images.githubusercontent.com/97909834/152082095-4ece61de-72cb-4487-89f9-4c39afc4c3a1.png)
![without](https://user-images.githubusercontent.com/97909834/152082096-36c936df-06c9-4c15-945d-b8182ab013a5.png)

**Comment by kangarko** [comment]
On it

**Comment by kangarko** [comment]
<img width="404" alt="Screenshot 2022-02-02 at 07 06 11" src="https://user-images.githubusercontent.com/1918426/152101799-b7b70599-23b7-4a0a-800c-2696776d51bf.png">
Cannot reproduce. Send me your /chc debug and check if you have the right itemsadder perms when using chatcontrol-

**Comment by NathanieReborn** [comment]
I am using * permission so, in theory, that is not the problem. An interesting fact is that if I don't let any space between words and the emoji, it works properly. But If i let space, it does not work. I attached you an example of this.
Also, here you have my /chc debug.
![junto](https://user-images.githubusercontent.com/97909834/152152347-4fb8b44b-e44d-4c88-9809-9cbf668e047c.png)
![separado](https://user-images.githubusercontent.com/97909834/152152356-24fe43c6-85ce-49f4-a16d-8617575699c0.png)
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7986287/debug.zip)

**Comment by ElBananaa** [comment]
Hey,
Can you please try to set `Rules.Strip_Colors` to `false` in the settings file. Does it change anything?

**Comment by NathanieReborn** [comment]
I have just tried but unfortunately, nothing changes! D:

**Comment by kangarko** [comment]
Thanks, I've fixed that!

**Comment by DarthZeroX** [comment]
The same error keeps happening to me, even with the latest version. When I send an emoticon with /msg or with the mcmmo admin chat ( /ac ) that strange symbol does not appear. I use ChatControlRed with the DeluxeChat formats, I don't know if it has anything to do with it.

**Comment by kangarko** [comment]
Sorry, the release was delayed, ensure you're on 10.9.8.

**Comment by DarthZeroX** [comment]
I'm on version 10.9.9, but it keeps happening

**Comment by kangarko** [comment]
So sorry for the delay, the fix I pushed earlier was broken, apologies so much and see the next version coming up toda!
