### ISSUE TITLE
1.18.1:MySQL question

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#1698]
I have multiple servers, can I use the same database for all of them?

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> I have multiple servers, can I use the same database for all of them?
> 
> Minecraft Version: 1.18.1 MySQL: true BungeeCord: true

Hey,
Yes you can, but this mean it will sync all chat data between servers, however it won't allow you to send a pm to a user on another server, unless you setup bungeecontrolred on the proxy.

I'm closing this but feel free to let me know if you need anything else down below.

**Comment by FinlayHDev** [comment]
I have bungeecontrolred so even without them being on the same database you can still send pm to other servers right?

Also what are the benifits of having MySQL?

**Comment by ElBananaa** [comment]
> I have bungeecontrolred so even without them being on the same database you can still send pm to other servers right?
> 
> Also what are the benifits of having MySQL?

I believe you need to setup a mysql database if you want to take advantage of cross-server features.

A MySQL database is basically better when the db size is pretty high and stores a lot of data as it will be quicker than a file database. It also makes the database more readable.
