### ISSUE TITLE
where does one find the source code for this project?

### ISSUE THREAD

**Issue by gsand** [kangarko/ChatControl#17]
That is all, thanks!

**Comment by EvilOlaf** [comment]
https://github.com/kangarko/ChatControl
There you go :grin:

**Comment by gsand** [comment]
@EvilOlaf Your link does not contain the source code.

**Comment by EvilOlaf** [comment]
Touché. Never looked at the source so I never noticed that there's no source in this repository :grin:

**Comment by kangarko** [comment]
I decided to remove the actual source for a while, it had w.i.p features that were added to the premium version afterwards. I plan to release it again, besides the you can decompile the free version.
