### ISSUE TITLE
1.16.5: Anti spam regex don't apply over 24 repeats

### ISSUE THREAD

**Issue by CzarnyWujek** [kangarko/ChatControl#1700]
Minecraft Version: 1.15.2-1.17.1
MySQL: true
BungeeCord: true

Any anti spam regex based on positive lookahead like:
(.)(?=\1{3})
(..)(?=\1\1\1+)
works only for 24 repeats (of single character or group of chars). It seems to omit any char over 24.
ie
aaaaaaaa - trim to: aaa
aaaaaaaaaaaaaaaaaaaaaaaa - trim to aaa
abababababababababababababababababababababababab - trim to ababab
but
aaaaaaaaaaaaaaaaaaaaaaaaa - trim to aaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaa - trim to aaaaaa
abababababababababababababababababababababababababab - trim to ababababab

observed in ChatControl-Red-10.4.5 and still to actual version

**Comment by kangarko** [comment]
Thanks, I believe this is a performance and a safety cap to prevent crashing servers on malformed or too demanding regex. I'll have a look what I can do when I have time.
