### ISSUE TITLE
Add Support for InteractiveChat DiscordSRV Addon

### ISSUE THREAD

**Issue by NyhmsQuest** [kangarko/ChatControl#1701]
https://www.spigotmc.org/resources/interactivechat-show-items-inventory-in-chat-custom-chat-keywords-bungee-velocity-support.75870/
This plugin already works with ChatControlRed
Howver it's DiscordSRV addon doesn't work with ChatControlRed and I think if it's made compatible it would be really nice way to show items or inventories from the game to Discord.

https://www.spigotmc.org/resources/interactivechat-discordsrv-addon-show-items-and-invs-on-discord-preview-discord-images-in-game.83917/
That's the addon I'm talking about.

**Comment by kangarko** [comment]
Thanks for the suggestion, unfortunately right now I am too busy with other projects to be looking into this asap.
