### ISSUE TITLE
Would love the feature for the plugin to control ignored players in discord if possible.

### ISSUE THREAD

**Issue by pupshadow** [kangarko/ChatControl#1702]
Description: 

Hello so my idea would work off the already used ignore feature from the plugin but it would go further. What I mean by this is if person a ignores person b in Minecraft chat and that ignore makes sure the person a that ignored the person b messages are non existent for them. But if you have discord connected to the server person a can see person b messages since ignore doesn't work n discord messages. I would love to see an implementation of something that would ignore the discord messages from person b for person a.

Questions:

1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)

This would benefit all types of servers that use game chat and discord chat on their server because then if you do have ignored players the player that's ignored by however many people can still access discord if they so choose and still be able to talk to their friends from discord to Minecraft.

2. What would happen if we won't implement this feature? How's your server being affected?

For my server I truly don't know how I would fix it I have already looked into making discord into a new channel in minecraft but then the java and bedrock players using it would have to switch channels and it would take more time for bedrock players to have to keep switching from global chat to discord chat which this is not ideal or smooth for some players... I think I would have to find a different method for discord to integrate with minecraft instead of using your plugin to make it happen I think. I would not get rid of your plugin because it works fairly well but it does have its downfalls but I'm willing to live with what issues are there.

**Comment by kangarko** [comment]
Thanks for your suggestion, however my plate is extremely full at the moment so I may return to this in the future when doing a major update!
