### ISSUE TITLE
Minecraft Version: 1.16.5 Prefix in chat help

### ISSUE THREAD

**Issue by Thorbjo** [kangarko/ChatControl#1703]
```

  prison_placeholders:
    Message: '&r{prison_rank_tag_prestiges+}&r{prison_rank_tag_default+}'

```
I also tried
``` 
  prison_placeholders:
    Message: '&r{prison_rank_tag_prestiges}&r{prison_rank_tag_default}'

```
None of this placehoders works in the chatcontroll red but it works fine in essentials chat 
   i have tryed also to do 

/papi parse me %prison_rank_tag_prestiges%
/papi parse me %prison_rank_tag_default%

And it works fine the placeholder but it dont show up the prison rank or prestiges
![Unavngivethelp](https://user-images.githubusercontent.com/71459845/152396627-11d92bbd-eba8-4516-a0c1-7be2503f978d.png)

**Comment by kangarko** [comment]
Looks like for some reason they are replacing it in their own way, which makes it incompatible (I can be wrong).

What you can do is try setting up Listener Priority in our plugin to different values to see if any value fixes this:

https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities
