### ISSUE TITLE
Duplicate DiscordSRV messages sent by servers connected by Bungee

### ISSUE THREAD

**Issue by n-aspen** [kangarko/ChatControl#1704]
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

I have 2 servers connect by a waterfall server with BungeeControl-Red and I'm trying to get DiscordSRV to work correctly. I know that there needs to be a player on the server for DiscordSRV to send messages to Discord, so I have DiscordSRV on both servers because my player base isn't currently active enough to ensure that there is a player on the other server. 

The issue is that when there are players on both server I have duplicate Discord messages in-game even though I have `Forward_From_Bungee` disabled on both servers. I know that the duplicate Discord message is being received from the other server because I changed the formatting for the message to make sure.

**Comment by kangarko** [comment]
Can you please upload your /chc debug?

**Comment by n-aspen** [comment]
Here's the [debug zip](https://ufile.io/em15m72j) from one of the paper servers. They're configured identically other than a few minor formatting changes.

**Comment by kangarko** [comment]
Thanks, I will fix that to the next release.

TIP: Remove NashornPlus, no longer needed with us.

**Comment by n-aspen** [comment]
Awesome! Thanks <3 
And I had no idea, lol. Thanks for letting me know <3
