### ISSUE TITLE
1.18.1: Player is not connected through BungeeCord.

### ISSUE THREAD

**Issue by Noxillio** [kangarko/ChatControl#1706]
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8005718/debug.zip)

Issue only occurs on one server of our network, which includes three backend servers and the proxy. The **`settings.yml`** files are all identical, and CHC is updated on all backend servers - BCR is also up to date.

**Comment by TheIntolerant** [comment]
Not sure how helpful this will be but once I experienced this, it was caused by BungeeControl not loading up correctly due to an error or I had made in the configuration files.

Can you confirm that chatcontrol and BungeeControl are loading up correctly on server startup?

**Comment by kangarko** [comment]
Very odd, we've completely rewritten the system multiple times now and so far you're the first person noticing. Ensure you're really connected through BungeeCord on that server, as well as that there's no errors in the console, but I am sure you already did...

In the next version try setting Debug to [bungee-sync] for the Spigot server where this is occurring. It should print which players it think it found on BungeeCord, which must contain all players. Missing players will render as "offline" as you are getting, please double check this and report what you see in the console below.
