### ISSUE TITLE
1.18 discord sync message repeat

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1707]
Minecraft Version: 1.18
MySQL: true
BungeeCord: true

Just like the picture, when sending a message on discord, the server will send the message repeatedly.

[image](https://cdn.discordapp.com/attachments/767301984679624735/939435190458146886/unknown.png)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8007647/debug.zip)

**Comment by kangarko** [comment]
Set Integration.Discord.Forward_From_Bungee to false in settings.yml 

Also please see this: https://github.com/kangarko/ChatControl-Red/wiki/Discord#bungeecord
