### ISSUE TITLE
1.18.1: How do I disallow players from using 'decorations' in /chc color?

### ISSUE THREAD

**Issue by Nextinka** [kangarko/ChatControl#1708]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

The title says it all, I have no idea how to disallow players from using bold, strikethrough, italic, obfuscated, and more in the /chc color command. So far I have tried setting permissions such as chatcontrol.command.color.bold to false or even chatcontrol.command.color.decorations to false, again.

Is it even possible to somehow restrict this feature? I just want players to change their color using color codes (only using the first argument), but not all these special things that make the chat ugly-looking. Thanks.

Would it also be possible to change the success message once you change your chatcolor? So the 'aqua' string will actually be in aqua color.
![image](https://user-images.githubusercontent.com/98180136/152640107-50d3258d-b846-45f8-aca6-6072b8431cad.png)

**Comment by TheIntolerant** [comment]
To prevent people from using decorations, just negate the following permissions
```
chatcontrol.color.strikethrough
chatcontrol.color.underline
chatcontrol.color.obfuscated
chatcontrol.color.bold
```
Use the command ``/chc permissions`` to find the permissions that the plugin uses.

**Comment by Nextinka** [comment]
Those permissions you suggested already are negated/not allowed, yet it still allows you to change the color to bold, underline or anything else from the second argument.

**Comment by kangarko** [comment]
It's the chatcontrol.guicolor.{colorName} permission not just "color":

![Screenshot 2022-02-08 at 18 05 33](https://user-images.githubusercontent.com/1918426/153038258-310368fd-901d-44ac-b1cf-424568e579cf.png)

:)

**Comment by Nextinka** [comment]
Thanks a lot!

**Comment by TheIntolerant** [comment]
Oops my bad
