### ISSUE TITLE
/bcreload Command on VelocityControl

### ISSUE THREAD

**Issue by angwdev** [kangarko/ChatControl#1709]
/bcreload, Reloads BungeeControl settings.yml and player messages. But appears that VelocityControl currently does not have this feature, so there is no option to reload changes like message without restarting the whole proxy. (/vcreload or /vc reload)

**Comment by kangarko** [comment]
@james090500

**Comment by james090500** [comment]
This should be fairly simple. I will test when home, pushed some code in the meantime.

**Comment by angwdev** [comment]
Ping me when is done, to test it.

**Comment by james090500** [comment]
> Ping me when is done, to test it.

@arima0k  Can you try this?

https://github.com/kangarko/VelocityControl/releases/tag/3.9.3-beta.2

**Comment by angwdev** [comment]
> > Ping me when is done, to test it.
> 
> @arima0k Can you try this?
> 
> https://github.com/kangarko/VelocityControl/releases/tag/3.9.3-beta.2

Yes, will try.

**Comment by angwdev** [comment]
Looks like the plugin can't read the config. (even removing the previous config and letting regenerate newones) 

```
org.yaml.snakeyaml.constructor.ConstructorException: Can't construct a java object for tag:yaml.org,2002:org.mineacademy.velocitycontrol.settings.Settings$SettingsFile; exception=Class not found: org.mineacademy.velocitycontrol.settings.Settings$SettingsFile
 in 'reader', line 16, column 1:
    Server_Aliases: 
    ^
```
(if I take out `Server_Aliases:`)
```
org.yaml.snakeyaml.constructor.ConstructorException: Can't construct a java object for tag:yaml.org,2002:org.mineacademy.velocitycontrol.settings.Settings$SettingsFile; exception=Class not found: org.mineacademy.velocitycontrol.settings.Settings$SettingsFile
 in 'reader', line 20, column 1:
    Messages:
    ^
```

**Comment by james090500** [comment]
Is this when doing `/vcreload` or when starting the plugin with a deleted `settings.yml` file?

**Comment by angwdev** [comment]
When starting the server.

**Comment by james090500** [comment]
I see, this fixes it - https://github.com/kangarko/VelocityControl/releases/tag/3.9.3-beta.3

**Comment by angwdev** [comment]
works ` &a[VelocityControl] Reloaded`

**Comment by james090500** [comment]
Does the reloading work ok? eg; disabling Apply_Ons or changing a setting?

**Comment by angwdev** [comment]
yes, it reloads the config.
