### ISSUE TITLE
MySQL database issue (suggestion?)

### ISSUE THREAD

**Issue by altruiis** [kangarko/ChatControl#171]
The plugin has an issue connecting to our sql databases with the error "Public Key Retrieval is not allowed." Other plugins have lines in their config where you can add flags to allow stuff like that. (e.g. LiteBans has a Flags: 'allowPublicKeyRetrieval=true' line in their config). Without this setting, the plugin won't connect to the database and we can't use it. Maybe just add a line to the MySQL.yml file for stuff like that?

**Comment by kangarko** [comment]
Thanks, I add ability to change this.
