### ISSUE TITLE
Player Introduction into Channels

### ISSUE THREAD

**Issue by VimaMT** [kangarko/ChatControl#1710]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

I have two parts to this. First, two questions:

- Do we currently have any way of letting other players know when someone new joins their channel?

- Do we currently have any way of sending an introductory statement to the new player, letting them know what the channel rules are, when they join a new channel?

Second, a request for a low-priority enhancement:

If we do not have those capabilities mentioned above, can we please consider adding them sometime in the future?

**Comment by VimaMT** [comment]
We can strike one of those questions off the list. I do get notification when a player joins my channel.

**Comment by kangarko** [comment]
Thanks! Yep, you've noticed the first one, good! :)

Not really anything for the second one, however you can check out our Motd.Format_Motd_First_Time section in settings.yml and send a special message to the player there!

Or you could go advanced and create a rule in rules/command.rs file which will listen to the channel join command, assuming the player played less than 10 minutes using the operator below and then hinting them the message:

`require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 10`

Matej
