### ISSUE TITLE
Lockette/Blocklocker compatibility

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#1711]
Sign spy shows lockette/blocklocker signs. Is it possible to add an option to exclude the message from chat if the text on the first line matches a certain phrases via ignorecase (e.g.  `[texthere], [private], [Timer:2], [everyone]` etc).

1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
It would prevent unnecessary sign spam as these aren't really important.

2. What would happen if we won't implement this feature? How's your server being affected?
Nothing really just a minor inconvenience and makes it a tad bit more annoying to view legitimate sign messages.

**Comment by kangarko** [comment]
Thanks, but the only way would be to exclude sign messages starting with [ and ending with ] on their first line, from being logged. Which could lead to players bypassing this. I feel this would be an overkill and lead to bypasses, denied.
