### ISSUE TITLE
1.16.5: Translation Bug

### ISSUE THREAD

**Issue by Alucardz997** [kangarko/ChatControl#1712]
Hi there,

I've encountered a bug with the localization file.
To be more specific, the description of the /toggle command does not take the description into account.
I've translated the description in the localization file, but the "default" is still displayed in-game (after several server restarts).

`Toggle:
    Usage: <type> [group]
    Description: '&6- &fTrimite un mesaj privat.'`

In-Game I get the default "Toggle seeing parts of the plugin.".

**Comment by Alucardz997** [comment]
Update: Found multiple occurences of translations in the localization file not applying upon restart.

This part should get an overhaul generally speaking - it's inconsistent and only partially working.
What I mean by inconsistent is that the structure of the localization is different even between command tooltips.
Example: PM vs REPLY - different in terms of structure in the localization file and cannot be translated in a way that allow for consistency. (help messages to look more or less the same across multiple commands)

**Comment by kangarko** [comment]
Thank you I will have a look in the next version!
