### ISSUE TITLE
1.18 - Quick help

### ISSUE THREAD

**Issue by MuriloWentz** [kangarko/ChatControl#1714]
hey im getting this error in console, how can i stop it?

[ChatControlRed] Warning: JSON Message to SnoopKevinn was too large, removing interactive elements to avoid kick. Sending plain:

**Comment by kangarko** [comment]
Reduce the amount of parts in your format(s) in format/ or anywhere where it could be oversized (see the plain message). Or set Strip_Oversized_Json to false in settings.yml
