### ISSUE TITLE
Channel join/leave message

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#1718]
I searched the wiki a bit and unfortunately didn't find anything about this, or maybe I read over it several times. 
I'm quite new with the plugin and I can't find a permission or config setting to get rid of the "Player XY has joined 'XY' channel". Do you know what to do? 

Minecraft 1.17.1
MySQL: false
BungeeCord: false
chc version: 10.9.8

![grafik](https://user-images.githubusercontent.com/62625225/153652046-a7cc0e3a-db8e-4f90-bf92-c1ad5f4ea5b9.png)

**Comment by kangarko** [comment]
You just want to hide these annoying messages? Set them to "none" using your localization file ;)

More info here: https://github.com/kangarko/ChatControl-Red/wiki/Localization
