### ISSUE TITLE
1.18.1: /mail issues

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#1719]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: true

`/mail send online`  does not send mail at all (or, if it does, it only sends to one player online). `/mail send all` however does work.

In addition, mail forwarding to multiple players separated by | does not seem to work. Forwarding to single players, does work.

**Comment by kangarko** [comment]
Thanks, I'll fix that to the next release coming up tonight!
