### ISSUE TITLE
1.18.1 | Discord -> Minecraft formatting no longer works after update

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#1720]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: true

Discord -> Minecraft chat formatting is broken. Formatting worked in the previous version (unfortunately I don't have the version number), but broke on update.

![image](https://user-images.githubusercontent.com/43658058/153701953-799f7326-5a67-417b-ac6c-d77450fd1ab5.png)

**Comment by kangarko** [comment]
Could you please upload your ChatControl zip folder as instructed? Use /chc debug so I can have a look

**Comment by BakiDance** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8054223/debug.zip)

**Comment by kangarko** [comment]
Sorry for the delay! It was not broken, actually right now it started to work as expected. You had Discord_Format set to {message} only and that is the message you are seeing in white. remove that key:

![a](https://i.imgur.com/zsorxsz.png)

And then it started to work properly:

![a](https://i.imgur.com/qfFHt4Z.png)

**Comment by BakiDance** [comment]
Just delete that key? Unfortunately, it isn't working right, still. After deleting the key, discord messages appear duplicated in chat, with the message content appearing both before AND after the Discord tag. 

![image](https://user-images.githubusercontent.com/43658058/154792524-1e6d6cf6-4146-4111-9905-8b4a8e067ea5.png)

Furthermore, messages sent from Minecraft to the Discord channel appear with the user's username proceeding the message, which is also new since the start of this ticket. 
![image](https://user-images.githubusercontent.com/43658058/154792592-bf5d583f-2c41-48c6-b7db-b921c068f306.png)

**Comment by kangarko** [comment]
What format would you like to use on Discord>Minecraft messages?

**Comment by BakiDance** [comment]
Ah, I was able to fix this by changing Channels>Format_Discord. There must have been a regression in my config, so this isn't a bug. 
I'm still affected by the first issue in my reply, though. I'm not sure why messages are appearing twice, considering if I add back the List>Standard>Format_Discord key, as they originally were, the message only appears once (but without the appropriate format, like in the first image.)

I'll try updating to 10.9.10 tonight and I'll report back if it changes anything.

**Comment by BakiDance** [comment]
I can create another thread if necessary, but I'll put it here first since it may be related to the DiscordSRV issues here. Apparently, most players aren't able to use the DiscordSRV->Minecraft function; their messages simply just don't go through. Additionally, I see this exception when someone tries, and it fails.

```
>.... [17:05:49 WARN]: [ChatControlRed] Task #10504359 for ChatControlRed v10.9.9 generated an exception
java.lang.NullPointerException: Cannot invoke "org.mineacademy.chatcontrol.PlayerCache.getPlayerName()" because "cache" is null
at org.mineacademy.chatcontrol.model.Discord.lambda$onMessageReceived$0(Discord.java:125) ~[ChatControl-Red-10.9.9.jar:?]
at org.mineacademy.chatcontrol.PlayerCache.lambda$pollIfExists0$7(PlayerCache.java:1121) ~[ChatControl-Red-10.9.9.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-187]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-187]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
I'm able to send messages, so I'm unsure what exactly is preventing everyone else.

**Comment by sarhatabaot** [comment]
I can second this. Messages go through but the player name doesn't show up.
If the player is not on the server when they speak the player name won't show up in the message.
![javaw_gupmWXcHAq](https://user-images.githubusercontent.com/4803946/155057352-77e7b4eb-001d-42c6-8249-ba771f7792e2.png)
If the player is online their player name shows up.
![javaw_qytYAcfeUK](https://user-images.githubusercontent.com/4803946/155057355-0a470050-3657-4bc1-b444-d458dfb5dd4e.png)

EDIT:
In console the message shows up properly, with the playername.

By modifying my format I was able to fix this on my end, i.e. playername now shows up. 
This seems to be an issue with `{player_nick}`.

By adding this to my format:
```yaml
  player-nick:
    Message: '{player_nick}'
    Sender_Condition: '{sender_is_player}'
    Suggest_Command: '/tell {player_name} '
  player-name:
    Message: '{player_name}'
    Sender_Condition: '{sender_is_discord}'
```

**Comment by kangarko** [comment]
Thanks, will be investigating in 48 hours.

**Comment by kangarko** [comment]
Apologies for the delay, I am rewriting our settings structure https://github.com/kangarko/Foundation/commits/6.0 so I am unable to move on with plugins until it is done since it introduces some breaking changes to CCR

**Comment by kangarko** [comment]
Should be solved in the next version! The player_nick variable will now work properly from discord to the game: ![a](https://i.imgur.com/r2kSfp7.png)

**Comment by BakiDance** [comment]
Will the next update include a fix for the issue I described in my previous reply? 

> Just delete that key? Unfortunately, it isn't working right, still. After deleting the key, discord messages appear duplicated in chat, with the message content appearing both before AND after the Discord tag.
> 
> ![image](https://user-images.githubusercontent.com/43658058/154792524-1e6d6cf6-4146-4111-9905-8b4a8e067ea5.png)

This is still affecting my server, and has been for 11 days.

**Comment by HorusApl** [comment]
Still a problem on 10.10.2, and using 1.18.2

**Comment by kangarko** [comment]
Please try using the next release which patched some possibly related issues to this.
