### ISSUE TITLE
1.18.1 | /chc reload does not reload messages_en.yml

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#1721]
Minecraft Version: 118.1
MySQL: false
BungeeCord: true

`/chc reload` does not reload messages in the messages_end.yml file. Instead, a server restart is required in order to update plugin messages.

**Comment by kangarko** [comment]
Thanks. Just found out that all of our software has this bug. Will have more time next week, this needs a deeper investigation. Stay tuned with our changelogs to see once this is patched!
