### ISSUE TITLE
Lost license on mc-market

### ISSUE THREAD

**Issue by MrFireSword** [kangarko/ChatControl#1724]
Minecraft Version: 1.X.Z
MySQL: true/false
BungeeCord: true/false

![image](https://user-images.githubusercontent.com/62079225/153748584-c43a96ac-62e9-4d34-acfc-aa8a500b86c7.png)

Hello
Why am i asked to pay again for a plugin i already paid for and there wasn't any license agreements.

**Comment by MrFireSword** [comment]
![image](https://user-images.githubusercontent.com/62079225/153748652-b7efce06-bd61-4a43-9a25-fe088dac91db.png)

**Comment by MrFireSword** [comment]
I really loved the plugin and now i wanna get back into server making 
i need to renew the purchase, I don't understand why :(

**Comment by TheIntolerant** [comment]
Please read #1680 for information regarding this type of issue, if you have any further questions just ask below.

**Comment by kangarko** [comment]
I've put the renewal price to $0.97, it was not intended this will be expired, I apology. Anyone needing renewal can either pay the symbolic $1 or reach out to get it renewed for free.
