### ISSUE TITLE
1.8.8 A special heart character will be not able to be formatted and it will crash chatcontrol

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#1726]
Error https://pastebin.com/wtruq8cc
The character is "🎔" (might be U+1F394)
I use rule for blocking symbols but somesone of my staff tell me that character is unknow on java language, so dunno what to do

Minecraft Version: 1.8.8
MySQL: true
BungeeCord: false

**Comment by kangarko** [comment]
Interesting, will investigate.

**Comment by kangarko** [comment]
I will block this internally. I cannot even type this character to the chat, I recommend you block this unicode by using the filter:

```
# Prevent special, unicode characters. Those are misused to bypass filters.
# Please keep in mind that non-English languages use them, so only uncomment this on English servers.
match [^\u0000-\u007F]+
then warn {prefix_error}Unicode characters are prohibited.
then deny
```
