### ISSUE TITLE
/r issue (Bungeecord)

### ISSUE THREAD

**Issue by PascalBrassat** [kangarko/ChatControl#173]
Server version: 1.16.4
Plugin version: newest (release from today)

When getting a message from someone on a different server, and then doing /r for them it will not work and instead go to whomever the last person to pm you on your server was.

ex.

Pab is on server one
Doug is server two
Karin is server one

Doug messages pab,
Karin messages pab 10 minutes later
Pab does /r (message), the message goes to doug and not karin.

Also, https://github.com/kangarko/ChatControl-Red/issues/146 was closed, however issue is not solved at this time it seems.

**Comment by kangarko** [comment]
Check settings.yml -> Private_Messages.Reply_Change_Threshold that this is set to a low amount. We prevent /r from being changed during this period. Set this to 5 seconds and retest please. 

Next release will have that option removed for now until we fix this problem.
