### ISSUE TITLE
1.18.1: Messages from Discord are never sent to server if playername not found

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1730]
I set my Discord name to `Radiant`. Messages are sent to server with no problem because I use same nickname on server.
I set my Discord name to `Radiand`. Messages are never sent to server.

I tried to use `{name]` `{username}` `{player_name}` `{player_nick}` in formats, all without any success.

CCR: 10.9.9
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Thanks, fixed!
