### ISSUE TITLE
1.18.1: Error parsing rule: Player Message

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1732]
Error on quit (also happens on join): https://pastebin.com/4gUHbDD1

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

![image](https://user-images.githubusercontent.com/5664135/153931472-51abfc22-fbbd-4188-a183-558000f63028.png)

**Comment by kangarko** [comment]
This is caused by some of your rule on BungeeControl, mind posting that folder as a ZIP please?

**Comment by kangarko** [comment]
Closing to clean up, please use the next release and post the ZIP below as instructed in case it happens again, thank you!

**Comment by Sikatsu** [comment]
I did not receive an email of your first message. It still happens, must be because of the change we made last time regarding patreon join/quit messages. Will do!

**Comment by Sikatsu** [comment]
[archive-2022-02-21T184059Z.tar.gz](https://github.com/kangarko/ChatControl-Red/files/8111515/archive-2022-02-21T184059Z.tar.gz)

@kangarko

**Comment by kangarko** [comment]
@Sikatsu does it still happen even with you putting the non-null check "**player != null** && player.hasPermission("XX")" to the file?

**Comment by Sikatsu** [comment]
Isn't that what I currently have?

require sender script player != null && player.hasPermission("join.patreon") && player.hasPermission("immortal.pink")

I do believe the error stopped since 22 februari, by checking the error.log from bungeecontrol.

**Comment by kangarko** [comment]
Thanks. Let me know if that reoccurs again. Will be updating all plugins shortly.
