### ISSUE TITLE
[all] Chatcontrol don't reload locale file when using /chc reload

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#1733]
Hi, i noticed when you edit something on locale file and you do /chc reload, it don't load the file with the new changes, and i have to restart the server for see changes, is normal or a bug?

Minecraft Version: 1.12.2
MySQL: true
BungeeCord: false

**Comment by kangarko** [comment]
Thanks, that's right and that's a deeper issue, we'll be having a complete config overhaul to address this in the future.

**Comment by kangarko** [comment]
I need extra time, will rewrite this internally, too many issues recently with Paper/Spigot breaking changes on 1.18. Can take some time since I am a solo developer but I will get it done!
