### ISSUE TITLE
Death Message + RGB [item] 

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1735]
```
group playerdeath
require killer player
require killer item *_SWORD|*_AXE
message:
- &c{player} was slain by {killer} using &8[&r[item]&8]
```
ChatControl RED 10.9.9
This is what happens when someone is using too much RGB in itemname.

![image](https://user-images.githubusercontent.com/87967222/154304588-3d8ea1bc-2261-43ee-9e9a-d2165063a1cd.png)

**Comment by kangarko** [comment]
This is a security feature. You can turn it off by setting Strip_Oversized_Json to false in settings.yml at your own risk
