### ISSUE TITLE
Broken regex

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1738]
ChatControl RED 10.9.9

```
# Restrict one same character to max. three repeats
# example: aaaaaaaaaa to aaa
match (.)(?=\1\1\1+)
then replace
```
Im using this rule in chat and it seems to break after exceeding a certain character limit.

![image](https://user-images.githubusercontent.com/87967222/154496600-a86a330b-eab3-4ba5-8a5f-65d3f7c623bf.png)

**Comment by TheIntolerant** [comment]
Hey, someone recently reported the same issue, please read this #1700

**Comment by Teslicek** [comment]
How do I replace repeating characters then? If the feature doesn't work for 24+ repeats?

**Comment by kangarko** [comment]
I have increased the security limit from 20 to 100, should fix this issue :)
