### ISSUE TITLE
[1.18.1] Problem with {killer} placeholder in death.rs

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1739]
ChatControl RED 10.9.9

I'm trying to customize death messages, but there is a problem with {killer} placeholder.
I am using "require killer ENDER_CRYSTAL|PRIMED_TNT" rule.

If a player is killed by a tnt explosion, {killer} displays the name of the user who ignited the tnt.
If a player is killed by an end_crystal explosion, {killer} displays "End Crystal" instead of the player who made the end_crystal explode.

Would it be possible to fix that and make {killer} placeholder display the name of the player who made the end_crystal explode?

**Comment by kangarko** [comment]
Pardón, ale je komplikované preniesť údaje z kryštálu na hráča a opačne, preto teraz vraciam len názov kryštálu., Neviem o žiadnom jednoduchom spôsobe ako ten údaj zistiť ktorý by fungoval aj naprieč inými pluginmi a bol kompatibilný.

-Matej
