### ISSUE TITLE
[Request] Offline viewable permission file

### ISSUE THREAD

**Issue by CypherPhyre** [kangarko/ChatControl#174]
I would like to make a request for an "offline viewable" permission file as part of the .jar download. I understand that maintaining a separate list on GitHub is far from ideal. However, making the current permissions viewable inside the .jar would make it easier for owners and devs to make permission adjustments without needing to be online. The default permissions are already listed in the plugin.yml after all.

CypherPhyre#6126 Tester: 1.16-mysql

**Comment by kangarko** [comment]
Sure, I dumped the class here: https://github.com/kangarko/ChatControl-Red/wiki/Permissions#chatcontrol-red-permissions-dump
