### ISSUE TITLE
I have a problem/bug? I dont know

### ISSUE THREAD

**Issue by iTzAndreZGameZ** [kangarko/ChatControl#174]
**Hi, I have a problem.**
I hosted my server in "serverminer" and that page has a "graph" or "list" of users in which you can see the connected users, the problem is that since I put the plugin (very good by the way) it acts as a FakeSlots, 

it tells me that there are 200 users but in reality there are only 50, 

is there any way to disable it or do something with it? Does not generate lag and in the "multiplayer" menu of the minecraft client you see the real people, as I say, it is only in that graph which I find strange (spigot server 1.8.3). Thanks for your attention

**Comment by kangarko** [comment]
See the wikipedia:

https://github.com/kangarko/ChatControl/wiki#frequently-asked-questions
