### ISSUE TITLE
[item] question

### ISSUE THREAD

**Issue by AgentPieCZ** [kangarko/ChatControl#1740]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

Hi, i trying to figure out how use [item] variable, whats default in files, is there something i need to change to make it works? bcs now it doesnt work.

**Comment by kangarko** [comment]
You need to have Channels.Enabled on true to enable our formatting, then you should be able to type [item] into the chat to see it working. Make sure you have variables/item.yml file there, if not then delete the entire variables/ folder and backup your changes to let it regenerate

**Comment by AgentPieCZ** [comment]
Made it works ( took little more time than i wanted but...), thanks for info !
