### ISSUE TITLE
1.18.1: DiscordSRV Issue

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#1743]
I disabled the DiscordSRV integration but these ids are still coming through, I think their from ChatControlRed
![image](https://user-images.githubusercontent.com/73852683/154716890-ff5ed71f-7e95-45a5-bc98-3206ccef22a0.png)

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

**Comment by FinlayHDev** [comment]
Nvm.

**Comment by kangarko** [comment]
Do you still need help?
