### ISSUE TITLE
commands blocker

### ISSUE THREAD

**Issue by ttt0** [kangarko/ChatControl#1745]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord:false

How can I turn off "/pl, /plugins" style commands I don't want players to see it

**Comment by kangarko** [comment]
Give players negative bukkit.command.version and bukkit.command.plugins permissions, see https://bukkit.fandom.com/wiki/CraftBukkit_Commands

This can and should be done without ChatControl

**Comment by ttt0** [comment]
i installed an old paper version and my problem was fixed
