### ISSUE TITLE
[1.18.1] ChatControlRed-Hikari localization file reset

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1746]
ChatControl-Red 10.9.10-HikariCP

Seems like after switching from 10.9.9 to 10.9.10-HikariCP, my localization file got reset/broken.

When I change my nick with 10.9.9 (custom localization file):
![image](https://user-images.githubusercontent.com/87967222/154799517-b637ef72-3eed-4635-b820-d2b1de77905d.png)

Changing nick after updating to 10.9.10-HikariCP (same localization file as on 10.9.9):
![image](https://user-images.githubusercontent.com/87967222/154799535-ab9a6ad0-0985-487b-8255-77c28a26cd9d.png)

(Also, you could fix the colors after you change your name)

**Comment by ElBananaa** [comment]
@kangarko I believe this is unrelated to the changes made to how the database work, right?

**Comment by kangarko** [comment]
@ElBananaa I don't think so

Please reset the given key in your localization file and it will work properly, you just need to manually append the color after the nickname:

![a](https://i.imgur.com/mdzYnkM.png)
