### ISSUE TITLE
1.18.1: Mail is send to multiple people

### ISSUE THREAD

**Issue by DerSeegler** [kangarko/ChatControl#1747]
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: false

When a player sends a mail via /mail new and then /mail send name it is send to more than just the given player. Yesterday I tested thsi with three people online and always everyboday received the mails. Today I updated all plugins to make sure and tested it again with only 2 people online and the another player sending a mail to an offline player. And both the sending and the receiving player got the mail, but I didn't receive it as the day before. I want to test some more, once I have more people to test available, but maybe you can already pinpoint the problem based on this.

**Comment by DerSeegler** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8102286/debug.zip)

**Comment by BakiDance** [comment]
I also experienced something similar. I deleted the message, unfortunately, so I don't have data to add.

**Comment by kangarko** [comment]
Thanks, please wait for the next version, and then if it happens again, please set Debug key to [mail] and let me know your console input when that happens.

**Comment by kangarko** [comment]
Should be fixed in the next version.
