### ISSUE TITLE
When I die, there is no chat message

### ISSUE THREAD

**Issue by ttt0** [kangarko/ChatControl#1749]
Minecraft Version: 1.18.1
MySQL: true/false
BungeeCord: true/false

When I die, there is no chat message. What should I do? I set it via "deaths.rs" but it still does not go.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.18.1 MySQL: true/false BungeeCord: true/false
> 
> When I die, there is no chat message. What should I do? I set it via "deaths.rs" but it still does not go.

Hey,
Please make sure you enabled death messages in your settings file? To do so, make sure the `Messages.Apply_On` part of the settings file contains `- 'death'` like the screenshot.
![image](https://user-images.githubusercontent.com/53318613/155050822-b5ef87f9-66a2-4c0d-a01d-3b4fa4dab561.png)

**Comment by kangarko** [comment]
Thanks to Banana for help. Closing, let us know below if you still need help!
