### ISSUE TITLE
1.16.4 | IllegalStateException when try /chc log all before:1h

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#175]
Try this command /chc log all before:1h and I dont know if it old data in database causes this. I can remove it and try :)

But seams like is book log get error.

https://pastebin.com/uENE4Xmd

error log
https://pastebin.com/7TtvdJk1

**Comment by kangarko** [comment]
Please post me your log.csv file

Does it happen with new books? I believe this bug was created in old version and new version cannot read this.

**Comment by broken1arrow** [comment]
> Please post me your log.csv file
> 
> Does it happen with new books? I believe this bug was created in old version and new version cannot read this.

I think i managed to read new book. This is my log, is not important to save it either, so I can remove it and let it do new.
[log.zip](https://github.com/kangarko/ChatControl-Red/files/5608190/log.zip)

**Comment by kangarko** [comment]
Interesting, so these two logs have completely different format... 

![a](https://i.imgur.com/jYsMvFy.png)

Books must have the {""} format with Content etc. and not just plain text. Try using the next release, remove this log and let me know if you see these again in your log. Thank you.

**Comment by broken1arrow** [comment]
> Interesting, so these two logs have completely different format...
> 
> ![a](https://camo.githubusercontent.com/c2ef7dfc95ffdc057df1beabcd69907d59e3f8da6a7cf47908edcbbe82abeab0/68747470733a2f2f692e696d6775722e636f6d2f6a59734d7646792e706e67)
> 
> Books must have the {""} format with Content etc. and not just plain text. Try using the next release, remove this log and let me know if you see these again in your log. Thank you.

Working fine now :) only thing it cant handle if you use åäö (not big deal for me )

**Comment by kangarko** [comment]
How is this broken? Just tested without problems:

![bu66kWMSHI](https://user-images.githubusercontent.com/1918426/100588675-7026d680-32f2-11eb-8386-223e3287f695.gif)
![a](https://i.imgur.com/PxNnmqg.gif)

**Comment by kangarko** [comment]
We already discussed this, on some systems the special characters are broken, nothing I can do about it. It should work on a Linux server :)

**Comment by broken1arrow** [comment]
@kangarko

And now I will use Linux instead of windows (I will be clear what is I try on). And see if this work.
