### ISSUE TITLE
The lag problem is serious.

### ISSUE THREAD

**Issue by geumu** [kangarko/ChatControl#1750]
Minecraft Version: 1.12.2
MySQL: true
BungeeCord: true

I am currently running a bungeecord server with 600 concurrent users.
Currently, there is a lot of load in the chat controller and related protocols. Is there any way to solve this problem?

**Spark Report**: https://spark.lucko.me/mTSjochDbX

**Comment by ElBananaa** [comment]
Hey,
Which version of the plugin are you using?
Did you enable all async features in the settings file?

**Comment by kangarko** [comment]
Thanks! Please check to follow ElBanana's advice and see this: https://github.com/kangarko/ChatControl-Red/wiki/Performance

Let me know if you still need help or continue to see this lag.
