### ISSUE TITLE
Hide the channel join message from players?

### ISSUE THREAD

**Issue by Alucardz997** [kangarko/ChatControl#1751]
Hi there!

I was hoping that you could help me understand what it takes to hide the channel join message for regular players. (or all players hopefully) The message I'm talking about can be seen in the below screenshot.
![2022-02-21_21 45 09](https://user-images.githubusercontent.com/98710721/155017881-37a7da0d-131c-4eb7-a6b6-accb1d4df1a9.png)

Thank you!

**Comment by ElBananaa** [comment]
Hey,
Please look for the `Notification:` part in your localization file, and set it to `Notification: ''`, then restart the server.

**Comment by kangarko** [comment]
Thanks to Banana for answering while I was gone!
