### ISSUE TITLE
Optimize PlayerListener.onJoin() and PlayerListener.onQuit()

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1752]
ChatControl-RED 10.9.9

Hello, I'm running a server on 1.18.1 with about 100+ concurrent players and ChatControl is using the most usage from all the plugins. (Tested with multiple timings and spark reports.) I'm not exactly sure which events are happening on join/quit, but I'm pretty sure there's a way to improve it, because right now its pretty much disaster with many players. 

(Can provide a spark/timings report if necessary, but not publically. Txslx#0001)

![image](https://user-images.githubusercontent.com/87967222/155021799-7abb1ca1-2128-407d-b6b2-023ba973596a.png)

**Comment by TomLewis** [comment]
Do you have an onjoin message thats dispalying a placeholder?

**Comment by Teslicek** [comment]
Im not using join messages from chatcontrol.

**Comment by kangarko** [comment]
Please upload your /chc debug output file for me to try to reproduce. @TomLewis how's the performance on your end I may ask?

**Comment by Teslicek** [comment]
@kangarko [debug.zip](https://github.com/kangarko/ChatControl-Red/files/8149003/debug.zip)

**Comment by kangarko** [comment]
Thanks, investigating shortly.

**Comment by kangarko** [comment]
Should be improved upon next version. If you still experience this, please send a full spark report over to matej@mineacademy.org
