### ISSUE TITLE
1.18.1: Previously sent /mail causes random exceptions

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#1753]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: true

I have no idea what happened, or how to replicate this. However, /mail that was previously sent is now displaying as a JSONParseException exception on server load and after, randomly. It seems to be limited to just a few specific mails, but I'm unsure why. They were just regular messages.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8112331/debug.zip)
[error.log](https://github.com/kangarko/ChatControl-Red/files/8112332/error.log)

**Comment by kangarko** [comment]
Thanks, can you please send your data.db file?

**Comment by BakiDance** [comment]
It's included in the debug.zip file attached. Github will not let me send it here directly.

**Comment by kangarko** [comment]
Thanks, will investigate soon.

**Comment by kangarko** [comment]
Fixed. Please remove the quotes " in your email message stored somewhere ( I can't send it in data.db, did you remove that file since?)

Example message causing issues, just remove the two " ":

if you get this message, say "banya" in chat!

We will automatically strip these letters starting the next version.

**Comment by BakiDance** [comment]
So if I'm understanding this correctly, mail messages cannot contain double quotes? I'm glad that's getting fixed, and thank you, but that's a tad disappointing. I had not removed my data.db file. Should I?

**Comment by kangarko** [comment]
Correctly, we'll automatically remove invalid letters causing these errors from your mail/books starting the next version.

You can just ZIP me your entire ChatControl folder and send privately over matej@matejpacan.com and I'll clean it up for you :)
