### ISSUE TITLE
1.17.1: BungeeControlRed Initialization Issue

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl#1754]
After upgraded to 3.9.10
https://pastebin.com/KhzwD8aU

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by sarhatabaot** [comment]
There is a problem with your yaml file. Have you tried putting it in http://www.yamllint.com/ ?

**Comment by coco0325** [comment]
> There is a problem with your yaml file. Have you tried putting it in http://www.yamllint.com/ ?

It's valid. The issue still exists even using the default files.

**Comment by kangarko** [comment]
Looks like a file system issue of that sort. Please try completely resetting the file, or even your entire folder. Use Notepad++ to save the files. If still having this bug, let me know below what language your system uses.
