### ISSUE TITLE
Command to display timed messages in specific group. "chc message list timed <group>"

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1755]
`chc message list timed` seems to list timed groups.
`chc message list timed general` Gives me an invalid argument when trying to display messages from that group.

I want to have a link in my /motd that says something like "Click to see annoucements", so when a player clicks it loads the timed messages in a specific group, so then I only have to write the messages once, and they can quickly read all important messages that are saved in a specific timed group.

How would I do this? It seems nearly all systems are in place (kind of) its so close.

**Comment by TomLewis** [comment]
I feel like this is a bug, it even auto tabs the group name, it just does not work.

**Comment by kangarko** [comment]
Thanks, going to reproduce on Monday, had some important settings rewrites to finish https://github.com/kangarko/Foundation/commits/6.0 that will improve performance and solve reloading localization file not reflected in the game.

**Comment by kangarko** [comment]
Thanks, I have made it functional for you!

**Comment by TomLewis** [comment]
Super thanks!

**Comment by kangarko** [comment]
Sorry for the release still not being out, settings system needed a deeper testing. Will aim to push it out tomorrow.
