### ISSUE TITLE
1.18.1: /ignore feature no longer exists.

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl#1756]
settings.yml has this feature enabled and it once functioned on some level... now there is no version of this command that can be run, every attempt will result in "Invalid argument, run /chc ? for help" which is beyond irritating since the help text doesn't even mention the /ignore command nor its syntax, but the syntax IS: /ignore [player] ... doing so toggles ignore either on or off.  Toggling it "on" would be like setting the "/toggle chat" and pm and mail and death and join and mail and me and quit ALL at the same time... but actually working, and working on only the one player you're targeting.

As always, this absolutely MUST also ignore all actions taken by other plugins such as essentials.

Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> settings.yml has this feature enabled and it once functioned on some level... now there is no version of this command that can be run, every attempt will result in "Invalid argument, run /chc ? for help" which is beyond irritating since the help text doesn't even mention the /ignore command nor its syntax, but the syntax IS: /ignore [player] ... doing so toggles ignore either on or off. Toggling it "on" would be like setting the "/toggle chat" and pm and mail and death and join and mail and me and quit ALL at the same time... but actually working, and working on only the one player you're targeting.
> 
> As always, this absolutely MUST also ignore all actions taken by other plugins such as essentials.
> 
> Minecraft Version: 1.18.1 MySQL: false BungeeCord: false

Hey,
Could you please provide us your `/chc debug` file?
It seems to be working just fine for me on my side.

**Comment by mrcoffee1026** [comment]
Here you go:
https://ufile.io/jpmhkgwg
Thanks!

**Comment by ElBananaa** [comment]
Hey, thanks!
I don't see anything wrong here. It simply seems like another plugin is overriding the ignore command.
Could you please try to reproduce the issue on a fresh install with only chatcontrol and its dependencies installed?

**Comment by kangarko** [comment]
Closing as invalid, please complete steps that Banana has suggested or feel free to comment below if you need more help/have questions from us.

**Comment by mrcoffee1026** [comment]
removing all plugins but this one doesn't really tell me anything.  However, try changing the alias:  I've tried changing the alias from "ignore" to "cignore" in case there was some interferance with another plugin.  Doing this does not work, /ignore is hardcoded to be the alias and cannot be changed.  Your config says "do not remove the first alias", my assumption by reading that was that the plugin needs at least one alias, not that "ignore" is hardcoded as the only alias that can work.  Making this small change has no effect when trying /ignore I get a "invalid argument. Run /chc ? for help" which - if run - supplies no information for ignore as if this was never a chc feature.  At the very least, this should alert you to language modifications that need to be made to clear up the confusion.  Perhaps you could provide the full command to your plugin that might be able to access the ignore command as a way of bypassing whatever might be trying to overpower the /ignore alias (/chc:ignore for example -- that isn't it, but it should be something with a similar format).  Used to be that I could /chatcontrol: or /channel: a variety of commands but that is no longer the case so I lack the proper approach here.

**Comment by mrcoffee1026** [comment]
When attempting this, I tried changing both the first AND the second alias which I used to have set to "ign" changing that one to "cign" made it FUNCTIONAL.  I was then able to use CMI's aliaseditor to create an alias for /ignore which resolved to /cign ... which made /ignore work again.  I mean the help text all says to use "/cign", but it's fine since that works too.  That doesn't explain why "/ignore" doesn't work or why it printed /chc help information any time we attempted it before, but this is a workaround to that issue if it comes up again.  I still advise the language updates.

**Comment by ElBananaa** [comment]
> removing all plugins but this one doesn't really tell me anything. However, try changing the alias: I've tried changing the alias from "ignore" to "cignore" in case there was some interferance with another plugin. Doing this does not work, /ignore is hardcoded to be the alias and cannot be changed. Your config says "do not remove the first alias", my assumption by reading that was that the plugin needs at least one alias, not that "ignore" is hardcoded as the only alias that can work. Making this small change has no effect when trying /ignore I get a "invalid argument. Run /chc ? for help" which - if run - supplies no information for ignore as if this was never a chc feature. At the very least, this should alert you to language modifications that need to be made to clear up the confusion. Perhaps you could provide the full command to your plugin that might be able to access the ignore command as a way of bypassing whatever might be trying to overpower the /ignore alias (/chc:ignore for example -- that isn't it, but it should be something with a similar format). Used to be that I could /chatcontrol: or /channel: a variety of commands but that is no longer the case so I lack the proper approach here.

You did understand us right: "Do not remove the first alias" means that the plugin needs one alias (no matter what it is). I use a completely different alias for most commands, and it works perfectly fine for me.
I didn't try with the ignore command specifically tho, but I still believe that there's something wrong with your setup here as I was unable to reproduce your issue.
Also keep in mind that combining 2 chat plugins isn't the best thing to do. Which may also explain your issue if you use both our chat system and CMI's one.

We ask you to try to reproduce the issue on a clean setup to make sure this is caused by another plugin (or by ours, depending on the results), and not directly by one of your configs. So yes, running tests on a clean setup tells us a lot more than what you think.

**Comment by mrcoffee1026** [comment]
This old nonsense in commands.yml (leftover fix for ChatControlPro):
```
   ignore:
  - chc ignore $1-
  unignore:
  - chc ignore $1-


```
Caused the issue.  Removing this fixed it.
