### ISSUE TITLE
1.18.1: Repeated characters added to anti-spam section of config?

### ISSUE THREAD

**Issue by DeusNinja** [kangarko/ChatControl#1757]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

Is it possible to have the anti-spam function replace repeating characters to a configured maximum?
For example taking "hiiiiiiii" and replacing it to "hii" as 2 being maximum repeating characters?

**Comment by DeusNinja** [comment]
match (.)(?=([a-z])\1{2})
then replace

This is what I've tried to use, but it's catching whole messages instead of individual words, causing usernames to be altered in /msg.

Additionally that regex only matches a single character, so if the word has multiple character spams in it, only the first repeating character is filtered, and the rest are ignored.

**Comment by kangarko** [comment]
Thanks! I can think about it but most people just use regular expressions, adding this as standalone feature would just add another layer of complexity, I feel it's sufficient as rules (with caveacts).
