### ISSUE TITLE
1.18.1: Cracked by kangarko 

### ISSUE THREAD

**Issue by mybvbbles** [kangarko/ChatControl#1758]
https://ufile.io/lye19507

A discord server for a plugin is refusing support because of a line that showed up in my logs that came from ChatControl when booting up.  ([09:02:45] [Server thread/INFO]: Loaded! Cracked by kangarko (MineAcademy.org) #joke)

Is this line intentional from kangarko or am I actually using a cracked plugin?

Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> https://ufile.io/lye19507
> 
> A discord server for a plugin is refusing support because of a line that showed up in my logs that came from ChatControl when booting up. ([09:02:45] [Server thread/INFO]: Loaded! Cracked by kangarko (MineAcademy.org) #joke)
> 
> Is this line intentional from kangarko or am I actually using a cracked plugin?
> 
> Minecraft Version: 1.18.1 MySQL: false BungeeCord: false

Hey,
As said in the line itself, this is simply a joke. If you downloaded the plugin from an official source, then you're using an official version :)

**Comment by mybvbbles** [comment]
Also another issue I am having with ChatControlRed is that im getting spammed in console whenever someone types a message
![chatspam](https://user-images.githubusercontent.com/89573765/156044696-2b29f689-b68b-4caf-ad00-b7d212ebb4f5.PNG)

**Comment by mybvbbles** [comment]
how do i fix this from spamming my console?

**Comment by TheIntolerant** [comment]
This issue has already been patched in an update, please make sure you are using the latest version of chatcontrol.

**Comment by kangarko** [comment]
We are working with BlackSpigot to waste their best men's time to crack our plugins: https://i.imgur.com/qIEZoE5.png

Enough jokes.

Just update to the most recent version and those spammy messages should go away.

**Comment by DarrylSSY** [comment]
> We are working with BlackSpigot to waste their best men's time to crack our plugins: https://i.imgur.com/qIEZoE5.png
> 
> Enough jokes.
> 
> Just update to the most recent version and those spammy messages should go away.

Damn the blackspigot owner really sounds like an asshole here
