### ISSUE TITLE
[move->PRO] Provide support for sending bungee messages server locally

### ISSUE THREAD

**Issue by pedroo21** [kangarko/ChatControl#176]
Hello,

I'm guessing currently for sending ChatControl bungee messages (such as ach, global), it makes use of bungeecord plugin only.
My problem is that I wanted to send a "/chc ach" message, but instead of being a player, I wanted to send it through a plugin or the server console.

What happens is, I get an error:
`java.lang.IllegalArgumentException: Cannot send a bungee message from an empty server`

This is because the console is not connected to the network.
I think this could be fixed and it would be extremely helpful for launching those commands not only as a player.

Regards.

**Comment by kangarko** [comment]
You posted in the wrong section.

The present API only allow to send messages upstream via a player instance (correct me if I am wrong?), that's why we need a player to delegate.

**Comment by pedroo21** [comment]
I'm not currently using the API for this.
The idea would be to use the staff chat through the console, in such way as me inside a plugin, could send a message like:
`Bukkit...dispatchCommand("chc ach hello from console");`

It's not that I don't want to use the API, but other plugins only support commands, and it would be really useful for me to use chatcontrol global chat or staff chat like that. In this case, the "player" sending the message would be tagged as console.

**Comment by kangarko** [comment]
You can send admin chat commands via "/chc ach" command from the console as well.
The problem starts when the server is empty, as there is nobody from whom I can send the message. I see now that there is an alternative way of doing this which would allow it in this case, I will test it out and let you know!

**Comment by pedroo21** [comment]
Just tested, and with people in the server it works fine! I know bungee limitations don't allow messages to be sent across empty servers, so if you can't figure it out, this solution should work just fine for me!

However, I'm not sure if the exception being thrown multiple times causes any problem, if you could check that and let me know.

Thanks!
Regards.

**Comment by kangarko** [comment]
No problem, if there's a way I will ship it in the next release. Closing for now, feel free to comment below if any questions.
