### ISSUE TITLE
Blocks "alt" as a swear word

### ISSUE THREAD

**Issue by VimaMT** [kangarko/ChatControl#1760]
Minecraft Version: Paper 1.18.1 (latest build)
MySQL: false
BungeeCord: false

I am having some difficulty finding the rule that is blocking the word "alt" and turning it into "***".

Suggestions, please?

**Comment by ElBananaa** [comment]
> Minecraft Version: Paper 1.18.1 (latest build) MySQL: false BungeeCord: false
> 
> I am having some difficulty finding the rule that is blocking the word "alt" and turning it into "***".
> 
> Suggestions, please?

Hey,
There's no such rule in the plugin, however I believe this rule may be the one triggering a detection on "alt":
```
# Blocks 'twat'
match \b(t+(\W|\d|_)*w+(\W|\d|_)*a+(\W|\d|_)*t+(\W|\d|_)*)
group swear
```
I'd suggest either removing it, or simply add `ignore string \balt` under `match \b(t+(\W|\d|_)*w+(\W|\d|_)*a+(\W|\d|_)*t+(\W|\d|_)*)`.

Let me know if it changes anything :)

**Comment by kangarko** [comment]
Thanks to Banana! Closing, let us know if you need more help below.
