### ISSUE TITLE
[10.9.10] Variables in log files don't work

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1762]
```
group swear
then warn &cSwearing is not allowed here!
then notify chatcontrol.rules.swear &8[&7Swear&8] &c{player} wrote:&7 {original_message}
then write logs/swear/{rule_name}.log [{rule_name}] {player}: {original_message}
then deny
```
I want to sort logs from swear messages in order to fix possible falses, but variable {rule_name} doesn't do anything in the log file. It only works in the message.

**Comment by TheIntolerant** [comment]
You must assign a name to the rule for **{rule_name}** to work.
As shown [here](https://github.com/kangarko/ChatControl-Red/wiki/Rules#name-rule-name) and below.

---

``name <rule name>``
Give a rule a name that you can later use in alert messages or in groups with the ``{rule_name} ``variable. Example:
```
name ip
```

**Comment by Teslicek** [comment]
That is not the problem here.

I have a line in group config:
`then write logs/swear/{rule_name}.log [{rule_name}] {player}: {original_message}`

The problem is that {rule_name} variable DOES NOT return the name (of the matched rule) in this section of the message:
`then write logs/swear/{rule_name}.log`

But IT DOES return the rule name in this section:
`[{rule_name}] {player}: {original_message}`

So in this example, if someone swears and the rule has `name hello`, a file called `{rule_name}.log` is created, but IT DOES have format `[hello] {player}: {original_message}`. Thats the problem, because I want `hello.log` file to be created, not `{rule_name}.log`.

**Comment by TheIntolerant** [comment]
Ohh, I see. In that case matej will probably need to have a look into this once he is available.

**Comment by kangarko** [comment]
Thanks, will be fixed :)
