### ISSUE TITLE
Suggestion: New operator "ignore usernames"

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1763]
### Description:
This operator already exists on ChatControlPro and should function the same (or similar to) as stated there.
```
(Rule will ignore the names of the players online. Can degrade performance when having over 100 players.)
ignore usernames
```

---

### 1. How it would benefit others? (Not just you, but 1,000s of other people using the same plugin.)
I have seen a few people comment either on discord or Github mentioning that they were having trouble with specific rules since it was matching player usernames etc. by adding this, people would be able to create anti-spam rules etc which do not edit the usernames of persons online, etc

----

### 2. What would happen if we won't implement this feature? How's your server being affected?
Nothing major would happen if this wasn't implemented, it would just be an inconvenience.

**Comment by kangarko** [comment]
Thanks for suggesting, but that's easier said than done, we had some odd bugs with replacements and other operators when "ignore usernames" was used. I could not find a solution that was stable and allowed other operators to work 100%, hence there's no plans on reintroducing it back.

**Comment by TheIntolerant** [comment]
Ahh, fair enough!
