### ISSUE TITLE
ChatControl RED Config Help

### ISSUE THREAD

**Issue by uk49** [kangarko/ChatControl#1764]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Is there any way of requesting someone to configure chat control for me? I am struggling massively with the permissions and setting up certain features, and some other stuff as-well. I can detail what is needed if anyone responds.

**I can pay people** as-well, I just need this done asap!

**Comment by TheIntolerant** [comment]
Would you be able to list the things you are struggling with?

**Comment by uk49** [comment]
> 

Mainly permissions - I have set up 'roleplay' style chats, with certain block radius's (and one main server wide chat) - I've given myself the permission listed in the chat config, and the autojoin permission, but the chat is still saying 'you have no permission for this'

**Comment by ElBananaa** [comment]
> > 
> 
> Mainly permissions - I have set up 'roleplay' style chats, with certain block radius's (and one main server wide chat) - I've given myself the permission listed in the chat config, and the autojoin permission, but the chat is still saying 'you have no permission for this'

Hey,
Let's say I'd like to automatically join the channel named `pvp` in write mode, and the channel named `minigames` in read mode, these are the permissions I would need:

- `chatcontrol.channel.join.pvp.write`
- `chatcontrol.channel.autojoin.pvp.write`
- `chatcontrol.channel.join.minigames.read`
- `chatcontrol.channel.autojoin.minigames.read`

Also make sure players have the permissions `chatcontrol.chat.read` and `chatcontrol.chat.write` so they can read chat messages and write in the chat.

**Comment by kangarko** [comment]
Thanks to Banana and Intolerant for prompt answering :) I can help you for free too, no need to pay, but since you have not replied since I assume it has been solved, so I am closing this.

If not, please also read https://github.com/kangarko/ChatControl-Red/wiki/Channels and comment below, we will get back to you.
