### ISSUE TITLE
ChatControl Red on DeluxeMenus GUI

### ISSUE THREAD

**Issue by twseer67875** [kangarko/ChatControl#1765]
If I click Item with DeluxeMenus GUI, the following error will appear, this error may be caused by the API change of 1.18.2

Minecraft Version: Paper 1.18.2 #Build224
MySQL: true
BungeeCord: true
ProtocolLib Version: 4.8.0-SNAPSHOT-b540
DeluxeMenus Version: 1.13.4-Release

error-log:
https://pastebin.com/KR3aSF03

**Comment by HarvelsX** [comment]
Unfortunately, this is caused by migration to 1.18.2 and can only be corrected by updating the plugin developer, or independently change the NMS.

**Comment by kangarko** [comment]
Thanks, we will introduce 1.18.2 support in 96 hours.
