### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ttt0** [kangarko/ChatControl#1766]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

logs: https://paste.gg/p/anonymous/77c972e38f4446aba00e0b69893bb6fa
error.logs: https://paste.gg/p/anonymous/b4e0b45ded26416c83c286677d7aeb14

**Comment by ElBananaa** [comment]
Hey,
It appears your database log table is somehow wrongly formatted. I'd suggest making a backup of the database and cleaning it, so the plugin could regenerate every table properly.

**Comment by celciusjj** [comment]
Same issue, i clean the database and remove it to generate a new db but the still issue

**Comment by celciusjj** [comment]
just delete the log.csv

**Comment by ElBananaa** [comment]
Hey,
Is your issue fixed?

**Comment by kangarko** [comment]
Remove your log.csv, closing.
