### ISSUE TITLE
1.17.1: Possibility in Rules / Javascript

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl#1767]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Hi wanna say, love the plugin has been an absolute godsend, I was  wondering if it's possible to make a rule

Where no matter the channel if something is surrounded by quotation marks "EXAMPLE" it will change the colour of that message within the quotation marks.

I essentially want no matter the channel if something is within quotation marks it changes that text inside of it to white and then goes back to the default chat colour when outside of the quotation marks.

**Comment by TheIntolerant** [comment]
Hey, try adding this to ur chat.rs file
```
# If something is surrounded by quotation marks, this will change the colour of that message to white.
match ("[^"]+")
then replace [#flpc-i]&f$0[#flpc-1]
dont verbose
```

**Comment by Ash10744** [comment]
Thanks it worked!!

**Comment by TheIntolerant** [comment]
No problem :)
