### ISSUE TITLE
1.18.1: Placeholder chat issue

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#1768]
Placeholders aren't working in chat.
<img width="393" alt="Screenshot 2022-03-07 at 17 04 19" src="https://user-images.githubusercontent.com/73852683/157087197-6f42a785-b959-40fe-aca5-e40b7a1f63f2.png">
Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

**Comment by TheIntolerant** [comment]
Are you using PlaceholderAPI?

If you are, have you tried "/papi parse me <placeholder>"
To see if it is a chatcontrol issue or PlaceholderAPI?

**Comment by ElBananaa** [comment]
> Placeholders aren't working in chat. <img alt="Screenshot 2022-03-07 at 17 04 19" width="393" src="https://user-images.githubusercontent.com/73852683/157087197-6f42a785-b959-40fe-aca5-e40b7a1f63f2.png"> Minecraft Version: 1.18.1 MySQL: true BungeeCord: true

Hey,
Please use {} instead of %% for your placeholders.
This should work.
