### ISSUE TITLE
1.18.2: NMS Support error

### ISSUE THREAD

**Issue by FastJoe0** [kangarko/ChatControl#1769]
On 1.18.1 everything worked. After update to 1.18.2 I have such errors in the console:
https://pastebin.com/VY5HVibF

Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

**Comment by ttt0** [comment]
I am also getting the same error.

**Comment by angwdev** [comment]
1.18.2 still not supported.

**Comment by HarvelsX** [comment]
Waiting for NBT API update in plugin dependencies

**Comment by kangarko** [comment]
Thanks, I updated NBT-API right now, we will push our plugins asap in the following 96 hours or even sooner.
