### ISSUE TITLE
How to add messages to deny in packets.txt ignoring formatting

### ISSUE THREAD

**Issue by kyledagrim** [kangarko/ChatControl#177]
Hey,
love the plugin :D
just wondering, how would I block a message such as this  with formatting (or anything starting with [Sudo]) in packets.txt ?
![command](https://cloud.githubusercontent.com/assets/25331186/22264376/9d71c500-e26f-11e6-9005-ef6bf24e3e45.png)
I tried this:
match ^[Sudo] Sucessfully ran command
then deny

and many other variations that didn't seem to work
PS: I have read this and found nothing that can help me with this:
https://github.com/kangarko/ChatControl/wiki

**Comment by kyledagrim** [comment]
please, need help on this

**Comment by kangarko** [comment]
Hey, please see the last message at
https://github.com/kangarko/ChatControl/wiki#known-caveats
