### ISSUE TITLE
High resource usage in timings

### ISSUE THREAD

**Issue by MilkAndCereal121** [kangarko/ChatControl#1770]
why does the plugin lag so much?
![image](https://user-images.githubusercontent.com/97564298/157149017-50bd06ea-e871-4853-9fca-6410a4358f3b.png)

**Comment by ElBananaa** [comment]
> why does the plugin lag so much? ![image](https://user-images.githubusercontent.com/97564298/157149017-50bd06ea-e871-4853-9fca-6410a4358f3b.png)

Hey, please follow the format, we can't do anything with a single screenshot of your timings report...

Provide us:
- the timings link
- a spark report link
- the debug file (`/chc debug`)
- informations about the environment (mysql? version?)

**Comment by kangarko** [comment]
Invalid format. Please read this: https://github.com/kangarko/ChatControl-Red/wiki/Performance If the advice there won't help, please reopen a new ticket with the information Banana requested.
