### ISSUE TITLE
Cannotm download resource from McMarket?

### ISSUE THREAD

**Issue by Alucardz997** [kangarko/ChatControl#1771]
![image](https://user-images.githubusercontent.com/98710721/157512609-874d3fe0-84d8-4148-9a52-bf67d08d4fc5.png)

I'm getting this c*** and if I choose to renew I'm getting an error message stating that the license cannot be renewed. 
I'm pretty much locked out of my our purchased resource. The McMarket support said that I shall be contacting the author.

**Comment by kangarko** [comment]
What's your MCMarket username?

**Comment by kangarko** [comment]
Nevermind, I found you. Unlocked :)
