### ISSUE TITLE
Timings report without MySQL

### ISSUE THREAD

**Issue by MilkAndCereal121** [kangarko/ChatControl#1772]
why does the chatcontrol red lag the most?
also it's not connected to MySQL? does this might be the issue?
https://timings.aikar.co/?id=8b75124515f74037badcade23c181c83#plugins

**Comment by kangarko** [comment]
Could you please upload your /chc debug ? I need to see your data file.

**Comment by MilkAndCereal121** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8228155/debug.zip)

**Comment by kangarko** [comment]
Rename your log.csv to log_backup.csv and replace data.db with these data.db, I have cleaned empty sections with only name-uuid-last active time and no other information about each player for you:
[data.zip](https://github.com/kangarko/ChatControl-Red/files/8230390/data.zip)

The next version will do the cleanup automatically.
