### ISSUE TITLE
1.18.1: Can CCR take over the functions of mcMMO Party Chat and Towny Chat Mechanics?

### ISSUE THREAD

**Issue by Dracathio** [kangarko/ChatControl#1773]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

So I'm wanting to know if CCR can take over the functions of Towny Chat {fully} and the Functions of mcMMO Party Chat {fully}

If so, how would setting that up go, because I know when it comes to Towny Chat you have Alliance Chat, Town Chat, Nation Chat, and General Chat... and with mcMMO Parties you got well just the party chat for the party you're in as well as Party Ally Chat {but we don't use that on Athandra}

So I'd like to know if CCR can function the same way both of those methods of chat function and I'd like to know how we can set that up on Athandra, to kinda make things easier on my Dev as I work on all the other plugin configs.

**Comment by kangarko** [comment]
Partially, you can use the "Party" feature of a channel to make it only exchange messages for players in the same party, town, or a nation. See our Channels page on the wiki. There's no settings more advanced than that at this point, as we'd like to keep our already complex settings as easy as possible, for more complex setups you'd be best off getting a custom small plugin developed hooking into Towny and mcMMO directly.
