### ISSUE TITLE
1.18.2 (join/leave messages, MYSQL)

### ISSUE THREAD

**Issue by Suinalk** [kangarko/ChatControl#1775]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: false
Server Software: Purpur

Join/Leave messages not working, uses default.
Another problem is that I need to delete the tables after every PC restart or else it will disable itself. Had to delete tables 3 times now.
(problems didn't occur on older version of ChatControlRed)

Fixes tried for join leave message problem:
New clean server with clean new files
Same problem with latest version of paper as well.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.18.2 MySQL: true BungeeCord: false Server Software: Purpur
> 
> Join/Leave messages not working, uses default. Another problem is that I need to delete the tables after every PC restart or else it will disable itself. Had to delete tables 3 times now. (problems didn't occur on older version of ChatControlRed)
> 
> Fixes tried for join leave message problem: New clean server with clean new files Same problem with latest version of paper as well.

Hey, please provide us your `/chc debug` file.
Make sure the plugin is up-to-date (same with its dependencies).

**Comment by kangarko** [comment]
Also please provide the error when the plugin disables itself and you have to delete the mysql tables.

**Comment by Suinalk** [comment]
MYSQL seems fine now? Idk, could be hardware problem. Join/leave message is not changing though.
Just try latest version paper and latest version of "ChatControlRed"

**Comment by kangarko** [comment]
Great, closing in good faith it has been resolved, comment below if you need more help.

**Comment by Suinalk** [comment]
Join messages still not appearing though!!

**Comment by ElBananaa** [comment]
> Join messages still not appearing though!!

Please do what I asked here: https://github.com/kangarko/ChatControl-Red/issues/1775#issuecomment-1064716678
