### ISSUE TITLE
1.18.2: Possibility to 100% customize command usage messages?

### ISSUE THREAD

**Issue by Nextinka** [kangarko/ChatControl#1776]
Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

Is it possible to edit the messages in localization.yml file completely? It seems as most of them are hard-coded, especially the command usage messages, and I can't change some parts or to get rid of empty lines when changing the corresponding parts to ''

For example, I'm trying to edit this message that shows up whenever you type /msg. It would show Usages there, and I got rid of that. But the blank line is still present, and the ----------------- lines on COMMAND USAGE aswell.
![image](https://user-images.githubusercontent.com/98180136/157889731-bc58ac3d-81ce-418c-9619-56542d609864.png)

Is there a workaround or something? Thanks for any tips and answers.

**Comment by kangarko** [comment]
Right now, you can only completely take over the /channel header help message: https://i.imgur.com/lq7yGay.png and the main header in /chatcontrol (https://i.imgur.com/Os5sBut.png < the section is "Commands"). At present we do not allow changing the red ----- lines
