### ISSUE TITLE
Support Gradient in chat

### ISSUE THREAD

**Issue by D3BoxOfficiel** [kangarko/ChatControl#1777]
Hi, I would like chatcontrol red to be able to support gradients in the chat (currently impossible or as title/tags as on the screen

![image](https://user-images.githubusercontent.com/38442389/157950348-5da636ac-bbf2-4f40-9002-7c3c15751281.png)

**Comment by kangarko** [comment]
Thanks for the suggestion, added to our roadmap :)

**Comment by MattDeWeerd** [comment]
@kangarko Are there still any plans for this to be implemented?

**Comment by kangarko** [comment]
Yes, but we would have to drop <1.7.10 support and it needs like 10-20 development hours, I did not find the time for it yet, I am sorry.
