### ISSUE TITLE
1.18.2: Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#1778]
[[]]

Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

All plugin dependencies up to date.

https://paste.helpch.at/goyitajane.md

Sending Debug Log to support@mineacademy.org

**Comment by kangarko** [comment]
Please use 10.10.1

**Comment by 00Hrtz** [comment]
Can not locate 10.10.1 on McMarket, seem to be missing and the new .2 update you pushed on Google Drive seems to be empty?

**Comment by 00Hrtz** [comment]
I finally managed to download 10.10.2,  I've sent you an email to confirm an alternate email address i used as i won't be using my registered email address you may have on file.

**Comment by kangarko** [comment]
Thanks, we'll update MCMarket today or tomorrow with a new version again, the old did not get upload until recently.
