### ISSUE TITLE
Switch to using normal data.db file when failed to connect to MySQL

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1779]
Right now, when ChatControl fails to connect to MySQL database, it disables itself and can't be used anymore, unless restarted.

That's why my suggestion is, that when ChatControl fails to connect to MySQL database, it will get data from data.db file instead of disabling itself.

**Comment by kangarko** [comment]
Thanks, but the data is not kept in sync, would lead to users wondering why they have lost data. I think the focus should be on fixing your connection rather than falling gracefully with bad consequences.
