### ISSUE TITLE
10.10.1 - Format discord

### ISSUE THREAD

**Issue by SinonCute** [kangarko/ChatControl#1782]
Format chat from discord to server is not working properly
![image](https://user-images.githubusercontent.com/81401485/158026265-0988a719-c9bb-418f-9f78-fdeac20eb796.png)

When a user on discord sends a message to the channel, it will be deleted and sent back by the bot, but it will be formatted not bold, but instead **

some discordsrv placeholders cannot be used in channel in game

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by TheIntolerant** [comment]
Could you please provide your /chc debug, file

**Comment by kangarko** [comment]
Closing, debug file not provided in time, please open a new issue.
