### ISSUE TITLE
[10.10.2] Death messages off by one space

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1785]
After updating to latest version of ChatControl, there seems to be an issue with Death messages.

My rule:
```
group crystaldeath
require killer ENDER_CRYSTAL|PRIMED_TNT
message:
- #FF0000[☠] {player} blew up
```
How the message looks like:
![image](https://user-images.githubusercontent.com/87967222/158059682-b36e2dc6-9969-437e-a99f-b95efed62552.png)

As you can see, the messages are off by one space.

**Comment by TheIntolerant** [comment]
Could you please provide your /chc debug, file

**Comment by Teslicek** [comment]
[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/8239590/debug.1.zip)

**Comment by itsBeaco** [comment]
This happens with both death messages and join/leave messages

**Comment by kangarko** [comment]
Thanks, recorded and patched in the next release.

**Comment by itsBeaco** [comment]
Thank you!
