### ISSUE TITLE
1.17.1: Players are not being put in read mode upon joining another channel

### ISSUE THREAD

**Issue by superhize** [kangarko/ChatControl#1786]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Option `Join_Read_Old` is set to true in settings.yml
Permission they have: https://luckperms.net/treeview/fhrr9iaXmm or https://pastebin.com/QKW5jR5y

Everything was working fine untill i update to 10.10.2

Debug:
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8240147/debug.zip)

**Comment by james090500** [comment]
Related to #1784 I believe

**Comment by kangarko** [comment]
Thanks, this will be fixed as a part of #1784 hotfix, apology for the delay.
