### ISSUE TITLE
[10.10.2] PlayerListener.onQuit() causing MSPT spikes

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1787]
I noticed that sometimes I have more than 200ms gap between tick intervals. 
(I cleared data.db file, so it's not big.)

Something like this:
![image](https://user-images.githubusercontent.com/87967222/158207255-04e08709-4b03-495e-9352-43d46abb509c.png)

So I used `/spark profiler --only-ticks-over 150` and stopped it after 10 minutes.
(Can provide spark report, but not publically.)

To my surprise, this is what I've found out:
![image](https://user-images.githubusercontent.com/87967222/158208067-6139d015-65cb-41df-8131-639ce14cec69.png)

**Comment by ElBananaa** [comment]
@kangarko
Here are informations @Teslicek provided me on discord:
Server version: 1.18.2
Tested with both MySQL enabled (MariaDB 10.3.3) and disabled, the issue happens in both cases.
Playercount: ~150/200

The issue appears when a player joins the server too, as you can see on this screenshot.
![image](https://user-images.githubusercontent.com/53318613/158233125-23b92a4f-e1fa-489d-ae8c-1ebfcbd01ff2.png)

We also noticed that, for an unknown reason, every time a user changes his chatcolor the cpu usage has a huge spike (up to 4 times the normal usage), and the plugin can take up to ~10/15s to change the player's color ingame.

**Comment by kangarko** [comment]
Please send me your /chc debug, I need to see your data.db specifically, seems like it's too large

**Comment by Teslicek** [comment]
As I previously said. I generated a new, clean data.db file.

[debug (3).zip](https://github.com/kangarko/ChatControl-Red/files/8253962/debug.3.zip)

**Comment by kangarko** [comment]
Thanks, I recommend enabling MySQL and reseting data.db once again. We will look into another disk storage, as right now we are still using a YAML system which can cause spikes if the file crosses a certain size, for you it seems this has been the case.
