### ISSUE TITLE
Question: Exception for switch messages

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1788]
Hi there, i have a question.

Chatcontrol handles the player join and player quit messages. This works awesome !

Now i want to be able to make an exception. When players go from the "survival:  server to the "quest" server i dont want a quit message displayed. And when players return from the "quest" server to the "survival" world i also do not want to show a join message. 

This would be the only exception. In every other situation i want the quit message to display. is this possible ?

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Hi there, i have a question.
> 
> Chatcontrol handles the player join and player quit messages. This works awesome !
> 
> Now i want to be able to make an exception. When players go from the "survival: server to the "quest" server i dont want a quit message displayed. And when players return from the "quest" server to the "survival" world i also do not want to show a join message.
> 
> This would be the only exception. In every other situation i want the quit message to display. is this possible ?
> 
> Minecraft Version: 1.18.1 MySQL: true BungeeCord: true

Hey,
This should already be possible using the `<ignore/require> <sender/receiver> server` operators: https://github.com/kangarko/ChatControl-Red/wiki/Messages#ignore-sender-server-require-sender-server-ignore-receiver-server-require-receiver-server.

**Comment by kangarko** [comment]
Thanks Banana for answering, let me know below if you still need help.

**Comment by donvdp** [comment]
thanks for your suggestion, but i have tried this. I tried to modifying the quit.rs file with the following examples

![image](https://user-images.githubusercontent.com/10013800/160928220-e18b0c2a-373d-4e26-937f-8374afb9668f.png)

But this results in a reload error

![image](https://user-images.githubusercontent.com/10013800/160928276-12fddd6c-4175-41c0-b4b3-dd44265726cc.png)

i have tried (trail by error) all 4 combinations as described on the wiki, but they all reload in the above mentioned error.

![image](https://user-images.githubusercontent.com/10013800/160928388-caba91a0-d2f5-4203-9c5c-660ad76cbb53.png)

------------

i also tried this:
![image](https://user-images.githubusercontent.com/10013800/160928767-f2741649-6315-4bfc-9675-3b0130934600.png)
also with all 4 variants... they will reload succesfully, but nothing changes ingame. Quit messages are still shown

is it broken or am i simply being a newb and doing it wrong hahahaha

**Comment by ElBananaa** [comment]
This is pretty weird.
Could you try to place the `ignore` part under the quit message?

**Comment by donvdp** [comment]
i did, and that also does not work. the ignore part gets printed in the chat.

**Comment by ElBananaa** [comment]
Hmm that's really weird.
Reopening this issue, please wait for @kangarko (due to personal issues, this may take a while ^^)

**Comment by kangarko** [comment]
[BungeeControl-Red-3.10.4.jar.zip](https://github.com/kangarko/ChatControl-Red/files/8402798/BungeeControl-Red-3.10.4.jar.zip)

Can you please try this version? reloaded fine for me, no errors, the functionality is there, improved it to support multiple operators like you tried :)

**Comment by donvdp** [comment]
Still getting errors

> [01:18:34 INFO]: ChatControlRed 10.10.4 encountered a FoException! Please check your error.log and report this issue with the information in that file.
> [01:18:34 WARN]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Unrecognized operator 'ignore sender server quests' found in Player Message {
> [01:18:34 WARN]:        'Type' = 'join'
> [01:18:34 WARN]: }
> [01:18:34 WARN]:        at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:90)
> [01:18:34 WARN]:        at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.operator.Operator.onOperatorParse(Operator.java:522)

I might just as well be messing up, since the wiki isnt exactly a practical guide i need to basicly guess what to do. I am using the part of the wiki that @ElBananaa tolled me to use, so i know i am using the correct variabled, but where to write them i am not 100% clear. I will try to make clear below. What would be the correct way of writing the config file ?

Without the ignore part i have this working: 

> group default
> message:
> - &2[&a+&2] &a{player}

When trying to incorporate the ignore message i make this:

> group default
> ignore sender server quests
> message:
> - &2[&a+&2] &a{player}

This is the 'join.rs' config on my survival server. I am trying to ignore the join message from a player when he/she joined the survival server when they are comming from the quest server, but only from the quest server. any other server should create a join message.

**Comment by donvdp** [comment]
Seeing as this ticket is already closed i think its not getting much attention anymore. i wil create a new ticket
