### ISSUE TITLE
1.16.4 |  Question how fix I sound on PM?

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#179]
know previously there was info about thist this, but can not find info how you can add sound (but may be really wrong).

Tested with rules and it was only the sender who got the sound not the recipient (tested around with different settings).

**Comment by NerdyBirder** [comment]
this is a feature that I would love to add as well. I want to use a sound when someone receives a PM instead of toasts.

**Comment by kangarko** [comment]
Thanks, I will add this feature!
