### ISSUE TITLE
1.18.2: Discord username not showing up in message from discord and Discord messages sent from players not on the game isn't sending 

### ISSUE THREAD

**Issue by pupshadow** [kangarko/ChatControl#1790]
Minecraft Version: Paper version git-Paper-250 (MC: 1.18.2)
MySQL: false
BungeeCord: false

**Issues at hand:** 

1: Discord usernames from users that have not logged into Minecraft for today don't have a username in chat when messaging from discord, but ones that have logged in today have username in chat if they message with discord. 

The chat from Minecraft to discord is not an issue. Only from discord to Minecraft from players not logging in to the server the same day.

This issue started back on update: I don't remember but its been a bit now I didn't report it because it wasn't showing any errors in console until now.

2: I just found out that my pasbin error is a different issue this issue makes it so players not in game at that the same time cant chat from discord.

**PasteBin Error**

https://pastebin.com/EEqYbxwj

This error was after I messaged in discord as well.

**Debug File**

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8254572/debug.zip)

If any other data is needed please don't hesitate to ask for it.

**Comment by pupshadow** [comment]
here is some pictures to help with the issue:
![discord chat](https://user-images.githubusercontent.com/35120956/158411923-147c28eb-6c09-4edd-98cb-b0dad9280b76.jpg)
![error from minecraft](https://user-images.githubusercontent.com/35120956/158411942-56e7417a-2e8e-4dea-85b0-b4adb34b3e34.jpg)

I had a player message in chat for me since I joined already today.

also found this issue:
![discord chat 2](https://user-images.githubusercontent.com/35120956/158412448-0b5e8a15-47e3-47fa-92f4-d95e99a735bb.jpg)
![error from minecraft 2](https://user-images.githubusercontent.com/35120956/158412463-1cbb9bbf-45b2-4e0f-8794-d878e673c57b.jpg)


that player usually talks in discord chat daily.

**Comment by TheIntolerant** [comment]
It seems this is being caused by the issue noted #1720 in regards to the placeholder ``{player_nick}``

**Comment by pupshadow** [comment]
Thanks for this information I'm happy that I wasn't the only one having this issue I thought I was because the only think that was on here was about my issue first. How about the not letting people message issue since that is another issue with it?

**Comment by TheIntolerant** [comment]
I personally cannot help with that specific issue, so you will need to wait for matej or someone else who knows what's wrong to assist you further.

**Comment by kangarko** [comment]
Thanks, I've patched the null pointer exception issue, please comment below if you need more help in the next version.

**Comment by pupshadow** [comment]
> Thanks, I've patched the null pointer exception issue, please comment below if you need more help in the next version.

Will do ill let you know if the other issue is still around or not.

**Comment by pupshadow** [comment]
Have an issue with the discord part still and now that plugin regular use as well.

This happened when I was trying to talk or even use a command in game for the plugin.

`WARN01:36:12
[ChatControlRed]: Plugin ChatControlRed v10.10.3 generated an exception while executing task 27712
Console
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map.get(Object)" is null
at org.mineacademy.chatcontrol.ServerCache.getDiskCaches(ServerCache.java:427) ~[ChatControl-Red-10.10.3.jar:?]
at org.mineacademy.chatcontrol.PlayerCache.lambda$pollAll$12(PlayerCache.java:1118) ~[ChatControl-Red-10.10.3.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-265]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-265]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-265]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by kangarko** [comment]
Thanks, will patch asap today.

**Comment by pupshadow** [comment]
Players can now send chat messages from discord when not on the game thank you for the help with that issue.  They however cant see players names still when the player chatting is not in the game still.

**Comment by kangarko** [comment]
<img width="448" alt="Screenshot 2022-04-02 at 17 37 54" src="https://user-images.githubusercontent.com/1918426/161390440-c0e010b7-f485-4005-86f3-bc85d38994b6.png">
So sorry for the delay! I have tested chatting from Discord from username "kangarko" while not being in the game. In the game I see my chat from the username "couverbo" and he sees my Discord name properly.

Can you please explain what you mean by this bug or I am missing something?
