### ISSUE TITLE
1.18.2: Changing chat color, prefixes or suffixes removes them from the channel?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1791]
I am not really sure what is going wrong. Whenever a certain group changes their chat color, they no longer have access to the channel.

![image](https://user-images.githubusercontent.com/5664135/158482042-d51c6a65-a94f-4705-b56f-e68b8d20bc09.png)

This is the setup I am using, to allow players to change their chat color and prefix:

https://pastebin.com/8m4P52AM / https://pastebin.com/6F4F7C5Q

Is it something I am doing wrong?

Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

**Comment by TheIntolerant** [comment]
Possibly related to database issue as seen in #1784

**Comment by ElBananaa** [comment]
Hey,
As TheIntolerant said, this is related to the issue tagged above. I'm closing this issue, let's continue there @Sikatsu.

**Comment by kangarko** [comment]
Thanks, this will be fixed as a part of #1784 hotfix, apology for the delay.
