### ISSUE TITLE
1.18.2: Broadcast message toggle resets on join

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1792]
Whenever you join the server, it resets your toggle for broadcast messages. So if you had it off, it will be enabled again on join,

Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/8257603/debug.1.zip)

**Comment by kangarko** [comment]
Thanks, this will be fixed as a part of #1784 hotfix, apology for the delay.
