### ISSUE TITLE
1.18.1: Making timed.rs messages URLS clickable. 

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1794]
In my timed.rs, I have URLS, players can not click on them. How do I fix this?

```
  - &r
    &9⚑ &e&lMarch 2022 Build of the month Competition! &r
    &r
    &7 &a✓ &7Enter Build Of the Month competition now!
    &7 
    &7 &a✓ &7Submit any unsubmitted build from any time period!
    &7 
    &7 &a✓ &7Info:&9 https://bit.ly/march22botm
    &7 
    &7 &a✓ &7Entry Form:&9 https://bit.ly/botmcomp
    &r
```

![This is an image](https://cdn.discordapp.com/attachments/901427669021909012/953590630603440208/2022-03-16_10.45.11.png)

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: false

**Comment by TheIntolerant** [comment]
Hey, it took me a bit to work this out myself when I was doing this a few weeks ago but if you add " &r" after the actual link you should be able to click on it.

So it looks something like this "https://example.com &r"

**Comment by kangarko** [comment]
Thanks @TheIntolerant for finding out about this, could you please update our Frequent Questions wiki page?

Tom let us know if you still need help below!

**Comment by TomLewis** [comment]
> Hey, it took me a bit to work this out myself when I was doing this a few weeks ago but if you add " &r" after the actual link you should be able to click on it.
> 
> So it looks something like this "https://example.com &r"

Brilliant! Thanks for telling me this! I was getting so confused why some of my links were working and others were not! I will update all my links now, thank you again!

**Comment by TheIntolerant** [comment]
> Thanks @TheIntolerant for finding out about this, could you please update our Frequent Questions wiki page?

Sure!

**Comment by kangarko** [comment]
}> > Thanks @TheIntolerant for finding out about this, could you please update our Frequent Questions wiki page?
> 
> Sure!

Thank you much, just wanted to say that I appreciate it!
