### ISSUE TITLE
1.18.2: Messages from Discord kick player from channel.

### ISSUE THREAD

**Issue by MrLogano** [kangarko/ChatControl#1795]
I'm seeing a new bug with version **10.10.2** that is causing players to be kicked from a channel when receiving a message from Discord.

There is no issue with chat between Discord and Minecraft, however, each message sent from Discord kicks players from the relevant channel. I have 3 discord channels linked to different channels, and each one is showing the exact same issue.

No error messages come up in the console, and I have tried debugging both ChatControl and DiscordSRV to narrow down the cause without success. I reverted to version **10.9.10** and the bug is not present there. 

**To Replicate:**
- Join a channel connected to Discord,
- Send message in the Discord channel,
- Player is kicked, or has the channel set to read mode.

Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Thanks, this will be fixed as a part of #1784 hotfix, apology for the delay.
