### ISSUE TITLE
1.18: Errors muting players: encoded string too long

### ISSUE THREAD

**Issue by addstar** [kangarko/ChatControl#1798]
When muting players, we are getting this error: https://www.toptal.com/developers/hastebin/aduxebiyed.properties

It doesn't always have this error, after we restart bungee+server, it seems to be fine for a short time and then does this error. It's making it very difficult to moderate since the mute doesn't always work. We have to run the mute on the server the player is on, but if they logout/login the mute is gone.

Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true
ChatControlRed version: 10.10.2
BungeeControlRed: 3.10.2

**Comment by kangarko** [comment]
Thanks, this will be fixed as a part of #1784 hotfix, apology for the delay.
