### ISSUE TITLE
1.18.2: Extra space in various messages

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1799]
Hello, I'd like to start with saying I am aware of the + icon to remove trailing spaces, how to use formats etc, As of 10.10.2, it seems any message that is not apart of a format (messages that don't lead to a format file) have an extra space included at the beginning. I know I can solve this by using a format, but this happens in a fresh install of 10.10.2 and with something like Death messages it is just not feasible to make a format for every possible death.

Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

**Comment by HorusApl** [comment]
![image](https://user-images.githubusercontent.com/64336395/159154105-0692a64d-9cf1-4ae5-9ef0-3c98187b34f8.png)

**Comment by HorusApl** [comment]
Occurs both on my test server which has completely blank configs, and my main server with my customized stuff after the latest update.

**Comment by kangarko** [comment]
Should be patched in the next release, thanks for reporting.
