### ISSUE TITLE
Change Worldguard flags message 

### ISSUE THREAD

**Issue by ByReturn** [kangarko/ChatControl#18]
Hello here sorry to bother you, I would change enfeite messages with flags worldguard chatcontrol someone told me it was possible with ChatControl but do not want to tell me because it was too long will you please tell me how? thank you in advance

**Comment by kangarko** [comment]
It is possible using packet rules. It has been discussed plenty of times on spigot forum, and reading provided examples should enable you to figure out yourself.

**Comment by ByReturn** [comment]
I'm french so I do not understand everything that is said in the same plugin help page, it faudrai explain me laugh because in agouter example in some of the packets was not walking

**Comment by kangarko** [comment]
Hey,

it is possible to create a packet rule which will hide the message. Open rules folder in ChatControl folder and then open "packets.txt" and create a rule. An example of a rule:

#match The message you want to block.
#then deny

So if you want to hide "You cannot do this there", message, simply write:

#match You cannot do this there
#then deny
