### ISSUE TITLE
1.16.4 | Death messages are not sent to Discord

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#180]
MySQL: Yes
BungeeCord: Yes

If you have Messages.Apply_On: [death] set, those messages are not sent to Discord.  If you don't allow ChatControl to control the death messages, they show up.

I thought maybe we could just add 'then discord channel message' into death.rs, but that gets very messy if you have multiple events and multiple messages configured.  Can the plugin just send the death message to Discord the same way it is shown to players?

**Comment by JessePesse123** [comment]
Hello, i tried the method from discord
: it sends every message 4 times, and [item] isn't working 
![image](https://user-images.githubusercontent.com/66204768/100525093-13c29a80-31be-11eb-9f51-4bc5e32feae8.png)

**Comment by JessePesse123** [comment]
![image](https://user-images.githubusercontent.com/66204768/100525094-18874e80-31be-11eb-8f1e-df93377e0135.png)

**Comment by kangarko** [comment]
Thanks, fixed this and added native support.
