### ISSUE TITLE
Cannot edit Config 1.5.2

### ISSUE THREAD

**Issue by ByNetsky** [kangarko/ChatControl#180]
Always when I it on de imagine disabled the plugin..
and when I put it back on en, it goes to normal.

14.02 21:44:13 [Server] INFO Enabling ChatControl v5.4.2
14.02 21:44:13 [Server] INFO Hooked into: Essentials
14.02 21:44:13 [Server] INFO Hooked into: Multiverse-Core (World Alias)
14.02 21:44:13 [Server] INFO Hooked into: ProtocolLib (Packet Features)
14.02 21:44:13 [Server] INFO Hooked into: Vault
14.02 21:44:13 [Server] SEVERE Cannot load configuration from stream
14.02 21:44:13 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: unacceptable character '���' (0xFFFD) special characters are not allowed
14.02 21:44:13 [Server] INFO in "<string>", position 157
14.02 21:44:13 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
14.02 21:44:13 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:138)
14.02 21:44:13 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:202)
14.02 21:44:13 [Server] INFO at kangarko.chatcontrol.utils.CompatProvider.loadConfiguration(CompatProvider.java:70)
14.02 21:44:13 [Server] INFO at kangarko.chatcontrol.config.Localization.load(Localization.java:31)
14.02 21:44:13 [Server] INFO at kangarko.chatcontrol.config.ConfHelper.loadAll(ConfHelper.java:55)
14.02 21:44:13 [Server] INFO at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:79)
14.02 21:44:13 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
14.02 21:44:13 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384)
14.02 21:44:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
14.02 21:44:13 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugin(CraftServer.java:303)
14.02 21:44:13 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.CraftServer.enablePlugins(CraftServer.java:285)
14.02 21:44:13 [Server] INFO at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:479)
14.02 21:44:13 [Server] INFO at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:445)
14.02 21:44:13 [Server] INFO at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:385)
14.02 21:44:13 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
14.02 21:44:13 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:588)
14.02 21:44:13 [Server] INFO at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
14.02 21:44:13 [Server] INFO Caused by: unacceptable character '���' (0xFFFD) special characters are not allowed
14.02 21:44:13 [Server] INFO in "<string>", position 157
14.02 21:44:13 [Server] INFO at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70)
14.02 21:44:13 [Server] INFO at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50)
14.02 21:44:13 [Server] INFO at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
14.02 21:44:13 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
14.02 21:44:13 [Server] INFO ... 17 more
14.02 21:44:13 [Server] SEVERE java.lang.reflect.InvocationTargetException
14.02 21:44:13 [Server] SEVERE at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14.02 21:44:13 [Server] SEVERE at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
14.02 21:44:13 [Server] SEVERE at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14.02 21:44:13 [Server] SEVERE at java.lang.reflect.Method.invoke(Method.java:606)
14.02 21:44:13 [Server] SEVERE at kangarko.chatcontrol.config.ConfHelper.invokeMethods(ConfHelper.java:84)
14.02 21:44:13 [Server] SEVERE at kangarko.chatcontrol.config.ConfHelper.loadValues(ConfHelper.java:62)
14.02 21:44:13 [Server] SEVERE at kangarko.chatcontrol.config.Localization.load(Localization.java:36)
14.02 21:44:13 [Server] SEVERE at kangarko.chatcontrol.config.ConfHelper.loadAll(ConfHelper.java:55)
14.02 21:44:13 [Server] SEVERE at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:79)
14.02 21:44:13 [Server] SEVERE at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
14.02 21:44:13 [Server] SEVERE at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384)
14.02 21:44:13 [Server] SEVERE at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
14.02 21:44:13 [Server] SEVERE at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugin(CraftServer.java:303)
14.02 21:44:13 [Server] SEVERE at org.bukkit.craftbukkit.v1_5_R3.CraftServer.enablePlugins(CraftServer.java:285)
14.02 21:44:13 [Server] SEVERE at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:479)
14.02 21:44:13 [Server] SEVERE at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:445)
14.02 21:44:13 [Server] SEVERE at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:385)
14.02 21:44:13 [Server] SEVERE at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
14.02 21:44:13 [Server] SEVERE at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:588)
14.02 21:44:13 [Server] SEVERE at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
14.02 21:44:13 [Server] SEVERE Caused by: java.lang.NoSuchMethodError: java.lang.Class.getTypeName()Ljava/lang/String;
14.02 21:44:13 [Server] SEVERE at kangarko.chatcontrol.config.ConfHelper.validate(ConfHelper.java:281)
14.02 21:44:13 [Server] SEVERE at kangarko.chatcontrol.config.ConfHelper.addDefault(ConfHelper.java:291)
14.02 21:44:13 [Server] SEVERE at kangarko.chatcontrol.config.ConfHelper.getString(ConfHelper.java:146)
14.02 21:44:13 [Server] SEVERE at kangarko.chatcontrol.config.Localization.init(Localization.java:109)
14.02 21:44:13 [Server] SEVERE ... 20 more
14.02 21:44:13 [Server] INFO !----------------------------------------------!
14.02 21:44:13 [Server] INFO Error loading ChatControl, plugin is disabled!
14.02 21:44:13 [Server] INFO Running on 1.5.2-R1.1-SNAPSHOT (v1_5_R3) and Java 1.7.0_111
14.02 21:44:13 [Server] INFO !----------------------------------------------!
14.02 21:44:13 [Server] INFO Error: Unable to get the error message, search above.
14.02 21:44:13 [Server] INFO !----------------------------------------------!
14.02 21:44:13 [Server] INFO Disabling ChatControl v5.4.2

**Comment by kangarko** [comment]
There's something wrong with your settings.yml most likely, post it here and ensure you have saved the file in the proper encoding (UTF-8 with Bom using Notepad++ is recommended)

**Comment by ByNetsky** [comment]
Okay Thanks,

**Comment by kangarko** [comment]
Closing, assuming it's fixed.
