### ISSUE TITLE
1.18.2: Player variable not working in console log

### ISSUE THREAD

**Issue by angwdev** [kangarko/ChatControl#1800]
@james090500

This is my join.rs config (I have the same in quit and switch)
```
message:
- &e{player} &fjoined servername network &7({server})
then log {player} joined {server}
```
but he console shows
`[VelocityControl] {player} joined lobby`
If I use {player_name} it does it right.

quit.rs: If I use `then log {player} left {server}` it shows `[VelocityControl] {player} left servername`. If I use {player_name} rather than {player}, doesn't shows nothing and same for switch.rs.

Minecraft Version: 1.18.2
MySQL: true

**Comment by james090500** [comment]
Can you try this?
[VelocityControl-3.9.3.zip](https://github.com/kangarko/ChatControl-Red/files/8311510/VelocityControl-3.9.3.zip)

**Comment by angwdev** [comment]
@james090500 
Tryed:
Now I used `then log &a{player} joined {server}` it shows `&aplayername joined lobby`, no colors.
Switch doesn't show and quit the same as join.

**Comment by angwdev** [comment]
Ok, latest chc update, now switch works.

**Comment by kangarko** [comment]
Glad to hear, closing!
