### ISSUE TITLE
Minecraft Version: 1.180Issue Title

### ISSUE THREAD

**Issue by Arthuuurr** [kangarko/ChatControl#1802]
Hello!
Some time ago you gave one of my staff a regex, I've been testing it and it doesn't block several dns. I don't know anything about Regex, could you help me solve the problem? I pass you the piece of Regex configuration attached to a photo with what I wrote in the chat.

```# Domain/URL filter.
match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|(?<! )c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|(?<! )m(| +)e|i(| +)o)\b
# If you want to ignore your server, put it at the end of ignore string below like: minecraft.net|youtube.com|yourserver.com
ignore string minecraft.net|youtube.com|imgur.com
# You can also uncomment this operator to allow email addresses. Credit: http://emailregex.com/
#ignore string (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
name url
before replace dot|\[|\]|\{|\}|\(|\) with .
before replace [\(\[\]\)]
ignore command /email
group advertisement```

**Comment by Arthuuurr** [comment]
![image](https://user-images.githubusercontent.com/90864573/159176518-dd137f06-455b-40ae-9c97-24c7a563ac02.png)

**Comment by kangarko** [comment]
Unfortunately I do not provide regex support as this is an international language that can be learned outside of ChatControl, plus my knowledge is limited here. I assume the "ga" and "tk" domains are not getting caught, so you could replace the end of match:

`|i(| +)o)\b`

with:

`|i(| +)o)|tk|ga|link\b`

as a provisionary solution, you will need to do this for all other domains.
