### ISSUE TITLE
1.18.2 Bungeecontrol error

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1807]
I've had this error for a while now, think we discussed it earlier. Might be related to my setup. The error seems harmless, but is yet annoying.

Error: https://pastebin.com/k4LVj7yD

Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

[bungee error.zip](https://github.com/kangarko/ChatControl-Red/files/8318656/bungee.error.zip)

**Comment by kangarko** [comment]
Can you try rewriting your conditions from:

require sender script player != null && player.hasPermission("join.patreon") && player.hasPermission("immortal.default")

to

require sender script player == null ? false : player.hasPermission("join.patreon") && player.hasPermission("immortal.default")

To see if the compiler stops throwing error if the player is undefined.

Quit messages seem not to have the player instance properly defined, you can try using Waterfall not Bungee to see if that helps if you're not already using it.

**Comment by Sikatsu** [comment]
Will try! Also I am already using waterfall ^^

**Comment by kangarko** [comment]
Closing, let me know below how the testing did go!
