### ISSUE TITLE
1.18.2: ClassNotFoundException!

### ISSUE THREAD

**Issue by GeleVla** [kangarko/ChatControl#1808]
I got the following error regarding ClassNotFoundException!
The error happens when a player drops a item from inventory.

Console log: https://bin.bloom.host/ewexojarey
error.log: https://bin.bloom.host/ejucafofar

Minecraft Version: 1.18.1 Purpur 1597
MySQL: false
BungeeCord: false
Velocity: true

**Comment by GeleVla** [comment]
It happens when dropping a item.

**Comment by ElBananaa** [comment]
> I got the following error regarding ClassNotFoundException! The error happens when a player drops a item from inventory.
> 
> Console log: https://bin.bloom.host/ewexojarey error.log: https://bin.bloom.host/ejucafofar
> 
> Minecraft Version: 1.18.1 Purpur 1597 MySQL: false BungeeCord: false Velocity: true

Hey,
You are using an oudated version of the plugin.
Please update to the latest version and let us know if that changes anything.

**Comment by kangarko** [comment]
Update as Banana said :)

**Comment by GeleVla** [comment]
The latest version of the plugin seems to have fixed it! Didn't know I was using an outdated version ;)
