### ISSUE TITLE
Title suggest (announce)

### ISSUE THREAD

**Issue by D3BoxOfficiel** [kangarko/ChatControl#1809]
Added the possibility to specify a player at the end and not mention the whole server + gradient support in the announcements

/chc announce title {javascript_vote}|{tab_placeholder_condition:votedispo}

**Comment by kangarko** [comment]
Thanks for your suggestion! While I am not looking to implement it right now for time constrains reasons, I will take note on this and if multiple people request this, we'll prioritize this!
