### ISSUE TITLE
Suggestion | Ability to toggle chat variables for message gradient

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#181]
Currently, "Gradient" cannot be applied to {message} part because of parsing chat variables, but I think that some people (like me) would like to be able to use gradient on player message but without any variables in chat, so that would be great if possible :)

**Comment by kangarko** [comment]
Thank you, however with the current system there's a limitation like this since the message is split word by word. It would be too complicated and drain performance. I can look into this in the future though.
