### ISSUE TITLE
Suggest bossbar

### ISSUE THREAD

**Issue by D3BoxOfficiel** [kangarko/ChatControl#1811]
Make it possible to add the time of the bossbar if there is already an existing boss (possibility to add or not)

**Comment by kangarko** [comment]
Sorry I don't understand your suggestion?

**Comment by D3BoxOfficiel** [comment]
Make it possible to add the time, if we execute the command several times

/chc announce bossbar message time:5

/chc announce bossbar message time:5

5+5 = 10s bossbar

**Comment by ElBananaa** [comment]
I personally don't understand why would anyone need that, instead of running `chc announce bossbar message time:10` directly.

Also, what about those who would like to be able to send 2 different bossbars with 2 different styles/colors/messages/durations?

**Comment by kangarko** [comment]
Thanks, denied, simply not having enough time and energy for this right now.
