### ISSUE TITLE
Add {uncolored_message} variable

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1812]
There is a variable `{player}`, which doesn't include player's nick color and `{player_nick}`, which does.

I would like to create the same thing, but with `{message}` variables.

My suggestion is to add a variable `{uncolored_message}`, which doesn't include player's chat color in a message.

Variable `{message}` includes player's chat color by default and using `&f{message}` or `&r{message}` doesn't work.

**Comment by TheIntolerant** [comment]
Hey, when making a suggestion please include these two questions.

1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)

2. What would happen if we won't implement this feature? How's your server being affected?


This helps the developer better understand the use cases of such suggestions and why it should be implemented etc

Thanks

**Comment by Teslicek** [comment]
1. Not sure how others would use it, but I really need it. I'm doing a hiderank feature for donator ranks, which would basically make them appear as normal players in chat. But right now its not possible due to chatcolor, since once a player uses chatcolor, its automatically colored in {message} and I cant get rid of it. Player's uncolored name is a not a problem, since there is a variable for that.

2. It would be a pity for me and for others, who would like to take advantage of advanced features from ChatControl.

**Comment by ElBananaa** [comment]
I believe this can be achieved without any new variable. Simply pur `&r{message}` in your format file and it should send a white message with no chat decorations

**Comment by Teslicek** [comment]
That's the problem, it doesn't. It's somehow encoded in the {message} variable.

**Comment by kangarko** [comment]
Thanks, looking into options what we can do here

**Comment by kangarko** [comment]
Sorry, we can't support that at this moment, there's only one message renderer and this system would require us to send different placeholders for different players, which would further reduce performance of the plugin.

**Comment by TheIntolerant** [comment]
Since this isn't getting added directly to chat control. 

Have you (@Teslicek) tried making this hiderank feature give said users the negated permission nodes for chatcolor OR just switching their chat color to white when they toggle this hiderank feature?

As this should solve your issue mentioned here?

**Comment by Teslicek** [comment]
Well, that's exactly what I did. Once they have hiderank, their chatcolor is set to default, but the problem is, that once they unhide their rank, the chatcolor stays default and not the one they had.

**Comment by kangarko** [comment]
Maybe you can get a developer to add a simple small plugin for your very case? We do have an extensive API, your dev can just hook into PlayerCache and set the chat color back there.
