### ISSUE TITLE
1.18.2: Discord usernames issue when players not in game for ingame chat

### ISSUE THREAD

**Issue by pupshadow** [kangarko/ChatControl#1814]
Minecraft Version: Paper version git-Paper-265
MySQL: false
BungeeCord: false

**Issue at hand:**
Discord usernames still not showing up when players talk from the discord into the Minecraft server when they are not on the server.
It works when they are in the server however.

The first picture is when I was not on the server but chatting from discord.
![test out of game](https://user-images.githubusercontent.com/35120956/159588907-d791b792-cb7f-4f8e-b0f3-1e33318a4faf.jpg)
![Test for in the game](https://user-images.githubusercontent.com/35120956/159588927-e2de4b73-4254-4fc5-9b48-0d842bce7151.jpg)
The second one is a test for when I was in the game and chatting from discord.

**Files requested to be given with issues:**
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8328297/debug.zip)

**Comment by kangarko** [comment]
I have added a fallback mechanism to the next release, please try out that one.
