### ISSUE TITLE
Add COPY_TO_CLIPBOARD option to Format

### ISSUE THREAD

**Issue by SheerYin** [kangarko/ChatControl#1815]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
Allows you to copy text sent from other players to the clipboard

2.What would happen if we won't implement this feature? How's your server being affected?
For me, this function can better communicate for players, and it is best to implement it if necessary.

**Comment by TheIntolerant** [comment]
While the "copy to clipboard" is not currently a feature, I believe there is already a similar feature as of Version **10.9.3**, due to a request seen here #1609

This now allows you to add this to your format file as seen in that suggestion, to more or less copy a message.
```
Suggest_Command: '{message}'
```

**Comment by SheerYin** [comment]
> While the "copy to clipboard" is not currently a feature, I believe there is already a similar feature as of Version **10.9.3**, due to a request seen here #1609
> 
> This now allows you to add this to your format file as seen in that suggestion, to more or less copy a message.
> 
> ```
> Suggest_Command: '{message}'
> ```

because i want to copy from windows clipboard
Suggest_Command obviously can't do it

**Comment by TheIntolerant** [comment]
The only reason I mentioned it as it would be possible to select the less this way and than press control + c (or command + c if a mac user etc) to copy the message.

I do however see the potential use cases for such a feature for example if you allow multiple languages on your server, this would make the process of copying such messages and pasting into google translate (or another program) faster!

I guess we will just have to wait for now to see how the developer feels about this suggestion. Just thought I would provide a possible alternative even if it would be more time consuming in comparison to this suggested feature.

**Comment by TheIntolerant** [comment]
That being said it would be cool to see this implemented as translating other player messages on our server who don't speak English has always been a struggle!

**Comment by SheerYin** [comment]
> That being said it would be cool to see this implemented as translating other player messages on our server who don't speak English has always been a struggle!

Fully endorses

**Comment by kangarko** [comment]
Thanks, added!
