### ISSUE TITLE
Ignoring ChatControl's warning JSON messages not working

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1817]
10.10.4

Somehow ChatControl is unable to ignore warning JSON messages.

Console filter settings:
```
Messages:
  - '[ChatControlRed] Warning: JSON Message'
```

![image](https://user-images.githubusercontent.com/87967222/159718231-f0343d6c-03dc-4960-bf70-2e50a9f26540.png)

**Comment by kangarko** [comment]
Try setting Strip_Oversized_Json to false in settings.yml, otherwise for security reasons it's not possible to hide this warning message.
