### ISSUE TITLE
MySQL | ChatControl_Log Receiver column format

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#182]
In the ChatControl_Log table, there are two columns that save player names.  Sender and Receiver.  The Sender column has just the name, but the Receiver column has the name surrounded with square brackets and double quotes, like `["c0wg0d"]`.  Can these be removed so it's just the name?  This will help with manual SQL query lookups and data manipulation outside of the plugin.

**Comment by kangarko** [comment]
The Receiver column is dynamic and will have different data depending on the log type. It will not be the same all the time.
