### ISSUE TITLE
Command help

### ISSUE THREAD

**Issue by Johandrex** [kangarko/ChatControl#182]
Hey, I am having issues with the matching command. I'm unable make the matching command stop at a specific point not affecting any commands that have more than the /warp word. I'm probably doing something wrong, but unable to find out what the correct regex is.

match ^/warp
match ^/warp^
match ^/(warp)\b
match ^/warp\b
then replace /warp list

**Comment by kangarko** [comment]
You cannot have multiple match operators like this. A rule only accepts **one** match operator. I believe this is what you are looking for:

match ^/warp$
