### ISSUE TITLE
1.18.2 : InventoryCreativeEvent

### ISSUE THREAD

**Issue by iGamer2003** [kangarko/ChatControl#1820]
Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

Our server is constantly kicking back the error "Could not pass InventoryCreativeEvent to ChatControlRed"  I have copied and pasted a full version of the error from the console in the Pastebin link below.  Also, I looked through prior issues and noticed this was a bug before so I figured I would file it as such here.  Thanks for any help!

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8346622/debug.zip)

PasteBin of Console: https://pastebin.com/VWxvKGQ0

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.18.2 MySQL: false BungeeCord: false
> 
> Our server is constantly kicking back the error "Could not pass InventoryCreativeEvent to ChatControlRed" I have copied and pasted a full version of the error from the console in the Pastebin link below. Also, I looked through prior issues and noticed this was a bug before so I figured I would file it as such here. Thanks for any help!
> 
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/8346622/debug.zip)
> 
> PasteBin of Console: https://pastebin.com/VWxvKGQ0

Hey,
You are using an outdated version of the plugin.
Please update to the latest version available, it'll fix the issue.
