### ISSUE TITLE
[10.10.4] Exceeding PID limit + Out Of Memory Errors

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1822]
Pufferfish #56 (1.18.2)
ChatControl 10.10.4

After many, many crashes and random errors, I've reset my server (not Minecraft), reinstalled pterodactyl and so on. Before the reset, I had PID limit set to unlimited (because of some stuff). But after the reset, I didn't change PID limit.

---
**1.) Exceeding PID Limit** (using ChatControl database/file)
The server was normally running, around 150 players on, ChatControl connected to a database, and suddenly, the server started lagging intensively and I started getting random errors in console, something about cores/threads failing, I tried switching to using data.db file (using chc reload). Still no help and after a while, the server crashed and pterodactyl popped up a window saying to increase the PID limit. 

And that's what I did. The only way I fixed this is by setting PID limit to unlimited, but I've read somewhere, that it's not normal for a server to exceed PID limit. (Keep in mind that I've never had errors like this without ChatControl.)

---
**2.) Random Out Of Memory Errors - Java Heap Space** (only using ChatControl database)
After using ChatControl database, I've started getting totally random Out Of Memory/Java Heap Space errors. Doesn't matter if its 50 people on the server or 200, the result is still the same. These errors are totally unpredictable and can happen at any time. The problem is, that the server doesn't even crash, it basically "freezes", making all players unable to join the server and the only way to fix that is to either click Restart button (and wait like 5m for the server to restart), or to just kill it.

Before someone says, that I dont have enough RAM, that's not true. I'm using 24GB for my server which was enough even for 250 people (without ChatControl), I've also tried using even 32GB, but this didn't help it at all, still the same error. 

[debug (4).zip](https://github.com/kangarko/ChatControl-Red/files/8355633/debug.4.zip)

**Comment by ElBananaa** [comment]
Hey,
As we already discussed multiple times about this on discord (privately and publicly), please also provide here an updated crash-report log, and a spark profiler report (If you'd like to keep these privately, please also let us know here and send them to matej@mineacademy.org).

**Comment by kangarko** [comment]
Following via email, we need to optimize data.db. Looking into alternative drivers asap.
