### ISSUE TITLE
[WRONG FORMAT] Unknown error

### ISSUE THREAD

**Issue by Chumb3x** [kangarko/ChatControl#1825]
[ChatControlRed] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControlRed
28.03 15:37:11 [Server] INFO java.lang.UnsupportedOperationException: The method getUniqueId is not supported for temporary players.
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.delegate(TemporaryPlayerFactory.java:166) ~[?:?]
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler.getUniqueId(Unknown Source) ~[?:?]
28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.PlayerCache.from(PlayerCache.java:988) ~[?:?]
28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.<init>(Operator.java:705) ~[?:?]
28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.operator.RuleOperator$RuleOperatorCheck.<init>(RuleOperator.java:320) ~[?:?]
28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.<init>(Rule.java:228) ~[?:?]
28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:180) ~[?:?]
28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.model.Packets$1.onMessage(Packets.java:227) ~[?:?]
28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.lib.model.PacketListener$SimpleChatAdapter.onPacketSending(PacketListener.java:246) ~[?:?]
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
28.03 15:37:11 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:311) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
28.03 15:37:11 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:267) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
28.03 15:37:11 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:243) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
28.03 15:37:11 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1903) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
28.03 15:37:11 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1876) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
28.03 15:37:11 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer$1.sendMessage(CraftPlayer.java:2410) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
28.03 15:37:11 [Server] INFO at com.github.sirblobman.api.nms.PlayerHandler_1_16_R3.sendActionBar(PlayerHandler_1_16_R3.java:20) ~[?:?]
28.03 15:37:11 [Server] INFO at com.SirBlobman.combatlogx.expansion.notifier.manager.ActionBarManager.updateActionBar(ActionBarManager.java:59) ~[?:?]
28.03 15:37:11 [Server] INFO at com.SirBlobman.combatlogx.expansion.notifier.listener.ListenerNotifier.onTimerChange(ListenerNotifier.java:40) ~[?:?]
28.03 15:37:11 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor465.execute(Unknown Source) ~[?:?]
28.03 15:37:11 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
28.03 15:37:11 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
28.03 15:37:11 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
28.03 15:37:11 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
28.03 15:37:11 [Server] INFO at com.SirBlobman.combatlogx.manager.CombatManager.lambda$run$0(CombatManager.java:217) ~[?:?]
28.03 15:37:11 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
28.03 15:37:11 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
28.03 15:37:11 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
28.03 15:37:11 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
28.03 15:37:11 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
28.03 15:37:11 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
28.03 15:37:11 [Server] Craft Scheduler Thread - 168/ERROR Parameters: 
28.03 15:37:11 [Server] INFO net.minecraft.server.v1_16_R3.PacketPlayOutChat@d887b6e[
28.03 15:37:11 [Server] INFO a=<null>
28.03 15:37:11 [Server] INFO components={TextComponent{text=Combat , BaseComponent(color=?6, font=null, bold=true, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=? , BaseComponent(color=?7, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=|||||||||, BaseComponent(color=?a, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=|||||| , BaseComponent(color=?c, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=9 seconds., BaseComponent(color=?f, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}}
28.03 15:37:11 [Server] INFO b=GAME_INFO
28.03 15:37:11 [Server] INFO c=00000000-0000-0000-0000-000000000000
28.03 15:37:11 [Server] INFO ]
28.03 15:37:12 [Server] Server thread/INFO ?f?a?a?lMember ?7?7 ?8| ?7?7Zdendy225?7 ?8| ?f?f_QWander_ why

**Comment by ElBananaa** [comment]
> [ChatControlRed] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControlRed 28.03 15:37:11 [Server] INFO java.lang.UnsupportedOperationException: The method getUniqueId is not supported for temporary players. 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.delegate(TemporaryPlayerFactory.java:166) ~[?:?] 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler.getUniqueId(Unknown Source) ~[?:?] 28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.PlayerCache.from(PlayerCache.java:988) ~[?:?] 28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.(Operator.java:705) ~[?:?] 28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.operator.RuleOperator$RuleOperatorCheck.(RuleOperator.java:320) ~[?:?] 28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.(Rule.java:228) ~[?:?] 28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:180) ~[?:?] 28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.model.Packets$1.onMessage(Packets.java:227) ~[?:?] 28.03 15:37:11 [Server] INFO at org.mineacademy.chatcontrol.lib.model.PacketListener$SimpleChatAdapter.onPacketSending(PacketListener.java:246) ~[?:?] 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?] 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?] 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?] 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?] 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?] 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?] 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?] 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?] 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?] 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?] 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?] 28.03 15:37:11 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?] 28.03 15:37:11 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:311) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"] 28.03 15:37:11 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:267) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"] 28.03 15:37:11 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:243) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"] 28.03 15:37:11 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1903) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"] 28.03 15:37:11 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1876) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"] 28.03 15:37:11 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer$1.sendMessage(CraftPlayer.java:2410) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"] 28.03 15:37:11 [Server] INFO at com.github.sirblobman.api.nms.PlayerHandler_1_16_R3.sendActionBar(PlayerHandler_1_16_R3.java:20) ~[?:?] 28.03 15:37:11 [Server] INFO at com.SirBlobman.combatlogx.expansion.notifier.manager.ActionBarManager.updateActionBar(ActionBarManager.java:59) ~[?:?] 28.03 15:37:11 [Server] INFO at com.SirBlobman.combatlogx.expansion.notifier.listener.ListenerNotifier.onTimerChange(ListenerNotifier.java:40) ~[?:?] 28.03 15:37:11 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor465.execute(Unknown Source) ~[?:?] 28.03 15:37:11 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"] 28.03 15:37:11 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"] 28.03 15:37:11 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"] 28.03 15:37:11 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"] 28.03 15:37:11 [Server] INFO at com.SirBlobman.combatlogx.manager.CombatManager.lambda$run$0(CombatManager.java:217) ~[?:?] 28.03 15:37:11 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"] 28.03 15:37:11 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"] 28.03 15:37:11 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"] 28.03 15:37:11 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?] 28.03 15:37:11 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?] 28.03 15:37:11 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?] 28.03 15:37:11 [Server] Craft Scheduler Thread - 168/ERROR Parameters: 28.03 15:37:11 [Server] INFO net.minecraft.server.v1_16_R3.PacketPlayOutChat@d887b6e[ 28.03 15:37:11 [Server] INFO a= 28.03 15:37:11 [Server] INFO components={TextComponent{text=Combat , BaseComponent(color=?6, font=null, bold=true, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=? , BaseComponent(color=?7, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=|||||||||, BaseComponent(color=?a, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=|||||| , BaseComponent(color=?c, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=9 seconds., BaseComponent(color=?f, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}} 28.03 15:37:11 [Server] INFO b=GAME_INFO 28.03 15:37:11 [Server] INFO c=00000000-0000-0000-0000-000000000000 28.03 15:37:11 [Server] INFO ] 28.03 15:37:12 [Server] Server thread/INFO ?f?a?a?lMember ?7?7 ?8| ?7?7Zdendy225?7 ?8| ?f?f_QWander_ why

Hey, please provide us your debug file.
Newt time, also follow the issue format.

**Comment by ElBananaa** [comment]
Also please provide us more infos about the issue: when does it happens exactly?

**Comment by Chumb3x** [comment]
I fixed it
