### ISSUE TITLE
1.18.1 Did Chatcontrol just crash the server?

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1829]
https://gist.github.com/TomLewis/7b061185788d00401235441c344fb066

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: false

**Comment by kangarko** [comment]
Can you screenshot this:

![a](https://i.imgur.com/DrtPujs.png)

I need to see the table sizes you have, so I can try creating dummy data up to your size and reproduce. Thanks.

**Comment by kangarko** [comment]
Not the ChatControl_Log table that I accidentally highlighted, but all three ChatControl_ tables

**Comment by kangarko** [comment]
Closing due to cleanup, please see the next version coming out tonight/tomorrow and let me know below if you still need help.

**Comment by TomLewis** [comment]
Sorry I have been extremely sick for the last 6 days. Do you still need me to send you anything? 

I just logged onto my server and it crashed within 5 mins, same error.

**Comment by TomLewis** [comment]
I cant even download 10.10.4 as mc-market says;

The server just crashed again, after being up for about 3-5 mins.

```
An Error Occurred
Sorry, this file is no longer available. Please initiate the download request again.
```

**Comment by TomLewis** [comment]
![Screenshot 2022-04-04 16 04 31](https://user-images.githubusercontent.com/144046/161573654-224f91cb-e7f6-4227-8c50-7acd393813ab.png)

![Screenshot 2022-04-04 16 06 36](https://user-images.githubusercontent.com/144046/161573964-1898bc1b-93e5-4da0-bc2c-e3149bf538fd.png)


Sidenote, how on earth is that `chatcontrol` table 3.9 GB!?? that's nuts, its only got 13,026 rows.

**Comment by TomLewis** [comment]
This Data column in "Chatcontrol" is definitely not storing data correctly per player.
its storing "Tour_Completed" for multiple people? for some reason its got my username/UUID stored PER player? A lot of these users have entire arrays of ALL the channels..
![Screenshot 2022-04-04 16 09 45](https://user-images.githubusercontent.com/144046/161574688-61dcf623-3a70-4ea6-a312-98bd83a62b98.png)

Heres a random normal user I picked, not staff, just a normal user, its storing an insane amount of information PER player/row.
https://gist.github.com/TomLewis/b9b68975456a64de3d2e9d4990afafd1

**Comment by TomLewis** [comment]
A comment from a moderator:
`I swear every time we talk in game chat from discord the server dies`

So maybe there is an issue with the Discord integration on top?

**Comment by ElBananaa** [comment]
> A comment from a moderator: `I swear every time we talk in game chat from discord the server dies`
> 
> So maybe there is an issue with the Discord integration on top?

We had issues with data storing in previous versions. I'd suggest completely cleaning-up the database as it looks like the plugin didn't manage to properly update the tables.

You can also configure a short period for the log table cleanup (i'd suggest keeping 7 days of logs or less, especially with a high amount of players)

**Comment by TomLewis** [comment]
> We had issues with data storing in previous versions.

Is this referencing the 3.9GB of data I just reported? https://github.com/kangarko/ChatControl-Red/issues/1829#issuecomment-1087686074

I need to know what version this is fixed in, there was an update today but nothing was mentioned about fixing server crashes.

**Comment by ElBananaa** [comment]
> > We had issues with data storing in previous versions.
> 
> Is this referencing the 3.9GB of data I just reported? [#1829 (comment)](https://github.com/kangarko/ChatControl-Red/issues/1829#issuecomment-1087686074)
> 
> I need to know what version this is fixed in, there was an update today but nothing was mentioned about fixing server crashes.

I can't remember which version fixed this, but this is one of the previous versions. 10.10.4 already includes the fixes.

**Comment by TomLewis** [comment]
Alright, I have nuked the tables and updated to the latest version on survival and bungee. Lets hope this works.

**Comment by ElBananaa** [comment]
> Alright, I have nuked the tables and updated to the latest version on survival and bungee. Lets hope this works.

Great, keeps us updated!
Also try to lower the value of the `Clear_Data_If_Inactive` part to something like 10-15 days.
Same with `Log.Clean_After` which I recommend setting to `7 days` or even lower if you have an important playerbase.
You may also want to take a look at the `Clear_Cache_On_Disconnect` option.

**Comment by TomLewis** [comment]
> Great, keeps us updated!
> Also try to lower the value of the `Clear_Data_If_Inactive` part to something like 10-15 days.
> Same with `Log.Clean_After` which I recommend setting to `7 days` or even lower if you have an important playerbase.
> You may also want to take a look at the `Clear_Cache_On_Disconnect` option.

I just looked into these settings, and the comments in the config even say that the server may lag when the table gets too big, this just means that the plugin is poorly written. At no point should having a large database impact performance, unless its been written badly, like importing an entire database.

I just checked my chatcontrol table after I wiped it and its been running a day, and it looks like its no longer saving all data in that column, which is good.

**Comment by kangarko** [comment]
@TomLewis sorry for the trouble, you had an unfortunate version with my bug that caused the database to save the entire database for each player, hence the excessive size.

As Banana said, just remove ChatControl table completely. We've optimized our saving further since this bug has been patched.

Let me know if you will have anything else  and I am happy to help!
