### ISSUE TITLE
chat.txt error

### ISSUE THREAD

**Issue by Demonkid1112** [kangarko/ChatControl#183]
So I just updated to the latest version of the plugin, and when ever I went into the chat.txt file saved it then restarted my server or attempt to do /chc reload, I get an error saying Line: '(someweird symbol)# ------ 'basic grammar corrections' that weird symbol I know from command blocks means an enter, so I think whats going on is your file is reading the enters you input into the file.

**Comment by kangarko** [comment]
Make sure you saved your files in the proper encoding. Plugin saves files in UTF-8 format. WordPad or Notepad on Windows breaks them. Notepad++ is strongly recommended. Use UTF-8 (without BOM), not ANSI.

**Comment by kangarko** [comment]
Closing. Let me know if you still have issues.
