### ISSUE TITLE
Slow Chat Command

### ISSUE THREAD

**Issue by SiuanSong** [kangarko/ChatControl#1830]
**Suggestion:** Introduce a /slowchat command that limits how many seconds a player must wait in between sending their messages.

Sometimes chat can run really fast, especially on my server where players are particularly chatty and enjoy engaging with others. There are times where you send a message and your message is almost immediately pushed out of the chat box by other players' messages.

I know there is a delay feature in the settings file, but I really only need this feature at peak periods of the day, and having to edit the file and reload the plugin is clunky, especially when we usually only need to temporarily enable that for a few minutes.  I am also not particularly keen on setting up radius chat, as I feel that can alienate players.

A command to enable a feature like this would go a long way on servers like mine with a community focus, but I understand if it's not a priority.

**Comment by ElBananaa** [comment]
I really like the idea of a slowchat command.

While the plugin already comes with an integrated slow chat feature, it isn't really convenient for users who don't want to constantly use this feature, as they **must** go the the config file(s) and configure the feature accordingly, then reload the plugin each time they want to enable/disable it.

I think a such feature would really benefit small, medium and large-sized servers/network. The plugin wouldn't need to check for the message similarity and all these features, which also makes this feature way more lightweight than the current one.

In addition to the current suggestion, I have a few more ideas:

- The command could include multiple options such as the `-g` argument which would make the command run on the whole network.
- The `-s:<server>` argument would make the command run on a specific server.
- The slowmode could be applied to specific channels or to all the channels availables, by either runing, as example: `/chc slowmode all` for all channels or `/chc slowmode channel1|channel2|channel3` for specific channels.
- You could also chose to apply the slowmode only to public chat, and/or to private messages using the `-pm` argument for private messages only, or `-cpm` for both the chat and private messages.
- Users will have to specify the delay between each message in the slowmode command.
- And of course, adding a bypass permission (which could be useful for staff members, but could also be used as an additional feature for servers with ranks, as example)

**Comment by kangarko** [comment]
Thank you! While I am unfortunately unable to add this right now, I'm putting this to my private notes and we'll be looking over this in the next major feature update in the future.
