### ISSUE TITLE
Suggestion: Change function of the delay operator (review of #1629)

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1831]
As mentioned in the title this is essentially a duplicate of the suggestion #1629

Containing a few added notes of some potential use cases explaining why this suggestion would be beneficial.

---

### How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
This will benefit server owners as they will have more fine-grain control over custom command rules.

### What would happen if we won't implement this feature? How's your server being affected?
While in the above suggestion, a potential solution was to use a third party application to create custom commands and add cooldowns, this problem isn't easy to resolve when using attempting to use the "delay" operator as a per person delay for rules regarding chat, signs, books or packets etc.

In my case I have a few packet rules to limit the rate at which some plugins send messages to players such as "you cannot do that here" which can quickly spam a players chat. So I have implemented a packet rule using "delay" to make such messages no so spammy and annoying for people (not realising this was being applied globally).

Is this something that could be looked into again? Alternatively if it is easier to implement (while less ideal) you could have a potential additional delay operator (such as "playerdelay") but obviously make it so it only affects each user instead of it being a global delay.

**Comment by ElBananaa** [comment]
I think this would be a pretty useful integration (And it seems like a few other users would like the plugin to implement a such feature).
However, imo, creating a new operator would actually be a better idea as this would completely change the behavior of the plugin for all the users already using this operator.

I do believe making a new `playerdelay` or `cooldown` operator would more convenient.

**Comment by TheIntolerant** [comment]
> I think this would be a pretty useful integration (And it seems like a few other users would like the plugin to implement a such feature).
> 
> However, imo, creating a new operator would actually be a better idea as this would completely change the behavior of the plugin for all the users already using this operator.
> 
> 
> 
> I do believe making a new `playerdelay` or `cooldown` operator would more convenient.

Actually now I think about it, a new operator would probably be better, that way it wouldn't break other peoples setup who use the delay operator!

**Comment by kangarko** [comment]
Thanks, will reconsider, leaving open for future implementation.

**Comment by kangarko** [comment]
Added "player delay" operator! @TheIntolerant can you please update our Wiki in Rules? As well as maybe clarify the difference between "delay" and "player delay" for newcomers so that they won't get confused :) Thanks!

**Comment by TheIntolerant** [comment]
Done, hopefully this is clear enough 
![image](https://user-images.githubusercontent.com/48093184/161441045-295c2d3f-3a5a-4c3d-bb89-279e8c58b3ed.png)

**Comment by kangarko** [comment]
Yes thank you!
