### ISSUE TITLE
Rules.rs

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#1832]
Have a nice evening!

I have a question where I do not know quite further and do not really have the JavaScript experience I sit a few days longer. The wiki could help me a little, but unfortunately not in the points.

We a text based Minecraft server. Our users write many and long messages. The issue is that at times it is annoying that they have to write so many in a row. We had the idea that you can "cache" messages. How would this work?

Our thoughts: The user writes his text and appends an extension character to the end, like ">". The message is not sent to the chat, but saved (here you could use a placeholder like "is_typing" or something like that). If the next message doesn't have a ">" again, the message will be appended to the first one and both will be sent together. If it has the character again, then the messages are appended to each other and so you can create longer chains. It should be possible to set the maximum number of messages that can be appended to each other.

Is this possible with ChatControl or do we have to take a detour via a Denizen script? About it it is possible, but an unsightly and messy detour that I do not want to go ^^'' 

Sorry if this question seems stupid, but in our field several servers use this technique and it would be important for us to implement it as well.

1.18.2 Paper-272 
Velocity-Network
Java 17
CHC Version 10.10.4

edit: 
a placeholder that looks what was toggled would be handy. So something along the lines of {chatcontrolred_toggle_join} and as return value then true or false for the state activated or deactivated. the same for the other toggle states of a player (quit, announcements, etc.) ^^'' 
That would be a suggestion from my side ^^''

**Comment by kangarko** [comment]
Thank you very much! For now you can try googling a Spigot plugin that's already existing, for now we won't add this due to time constrains but I can reconsider this in the future.
