### ISSUE TITLE
Add the option to use the {player_suffix} in the /list command format in the settings.yml

### ISSUE THREAD

**Issue by MrCrazys** [kangarko/ChatControl#1833]
I believe that adding the option to use the {player_suffix} variable in the /list command format would be beneficial to many server owners. On my own server, certain ranks such as Builder don't give you a Builder prefix, but instead give you a suffix, so that in case they are an Administrator, the Administrator rank can still be shown along with the Builder suffix. Without this option, builders' suffixes will not be shown in /list. I also believe this would be useful for certain server owners that have ranks that can give you a custom suffix.

**Comment by kangarko** [comment]
Thanks, added!
