### ISSUE TITLE
1.16.4 |  ERROR Couldn't dispatch custom payload

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#184]
I don't now this, but has never see this before. So suspect it is something get trigged in your plugin (sry if i´m wrong). 

https://pastebin.com/FYLbiLw4

**Comment by AngellitoX** [comment]
Hello there, doesn't look like ChatControl is causing it, but could be. Would you mind trying to isolate and give some steps to reproduce the issue?

I would also recommend trying this on a testserver and see the result.

**Comment by broken1arrow** [comment]
> Hello there, doesn't look like ChatControl is causing it, but could be. Would you mind trying to isolate and give some steps to reproduce the issue?
> 
> I would also recommend trying this on a testserver and see the result.

Yes of course, that what I did for several weeks :) wanted to get a little bigger test group to find more bugs. Unfortunately, that error did not reveal what plugin was the problem. Know that player is running with fastclicker and triggers "client sends too many packets" (so he may have some more junk causing this).

And I did not get any major problems when I ran with all the plugins on the test server. But let's see if I can somehow get the problem started.

**Comment by broken1arrow** [comment]
> Hello there, doesn't look like ChatControl is causing it, but could be. Would you mind trying to isolate and give some steps to reproduce the issue?
> 
> I would also recommend trying this on a testserver and see the result.

Do not know if I wrote it clearly but ran it on test server, even with the plugin I run on the real one.

CC 8 has such major drawbacks that I do not know where to start. Saw today red also has so you can remove, points for each player (have in that case missed it in CC 8 if it would work). Dc does not work at all in CC 8, spy works half-heartedly.

And then you actually get a bigger base that can actually test the plugin properly. For example, it happened yesterday that the sent message as a wisper, does not know the cause (received errors). but restart solved that error.

**Comment by kangarko** [comment]
Hey! Thanks for reporting, but this is not coming from ChatControl Red. I'll continue keeping an eye on this though.
