### ISSUE TITLE
1.18.2: Discord usernames issue when players not in game for ingame chat

### ISSUE THREAD

**Issue by pupshadow** [kangarko/ChatControl#1840]
Minecraft Version: Paper version git-Paper-275
MySQL: false
BungeeCord: false

Issue at hand:
Discord usernames still not showing up when players talk from the discord into the Minecraft server when they are not on the server.
It works when they are in the server however.

The first picture is when I was not on the server but chatting from discord.
![not in game](https://user-images.githubusercontent.com/35120956/161828802-301ae4aa-3617-46ae-9da4-c144c193f01b.jpg)

The second one is a test for when I was in the game and chatting from discord.
![in game](https://user-images.githubusercontent.com/35120956/161828820-0201a845-51c0-475b-a8d1-cb0fca5ccbaa.jpg)

Files requested to be given with issues:
https://ufile.io/is1rvvbn

**Comment by ElBananaa** [comment]
Hey,
When the issue happens, does anything shows-up in your server logs?

**Comment by pupshadow** [comment]
> Hey, When the issue happens, does anything shows-up in your server logs?

No errors show up but it does show that its sending my name to the server. here is what is says when I wasn't in the server its the same as when I was in the server as well..

This was when I was not in the server.
![not in server log](https://user-images.githubusercontent.com/35120956/161835027-7544e47e-001c-41ce-b07f-e6e7f0934dc8.jpg)

This was when I was in the server.
![in server log](https://user-images.githubusercontent.com/35120956/161835067-c7aa88ce-26d0-4130-8901-81b16e8809b7.jpg)

Both of these was when I messaged from discord into the game.

**Comment by pupshadow** [comment]
I was also testing and making the setting default in the formats to see if it was on my end but it wasn't.

**Comment by pupshadow** [comment]
The format file I'm using is the global-chat.yml one for that chat channel that the discord and other players can chat in.

**Comment by kangarko** [comment]
Thanks, investigating. Is this online or offline server?

**Comment by pupshadow** [comment]
> Thanks, investigating. Is this online or offline server?

online server

**Comment by TheIntolerant** [comment]
Just out of curiosity what placeholder do you use for peoples name?

In your format file? Correct me if I'm wrong but I assume it's either {nick} or {player_nick}?

I only ask as I have a strong feeling this issue is related to the usage of those specific placeholders.

**Comment by pupshadow** [comment]
> Just out of curiosity what placeholder do you use for peoples name?
> 
> In your format file? Correct me if I'm wrong but I assume it's either {nick} or {player_nick}?
> 
> I only ask as I have a strong feeling this issue is related to the usage of those specific placeholders.

For the discord chat itself it’s the default {player} for regular in game chat it’s {player_nick} since it’s easier to see the nicknames in chat there and discord would not be able to know the player nickname as easily. But let me check what the default is for that.

**Comment by pupshadow** [comment]
Apparently I think as a collective we may have found out the issue. So I use {player_nick} for my ingame chat format option and I use {player} for my discord option however I changed my ingame chat option to {player} to see if that fixed the issue and apparently the discord chat was using my ingame game chat option instead of my discord message option so it was making the discord name not show up since it was trying to do my ingame chat option instead of the discord format.     Is there a way to make it so that my discord will use its options instead of my regular chat option?

**Comment by ElBananaa** [comment]
I'm not sure to understand what your meant by "chat option". Could you please elaborate a bit? Are you talking about the format?
You'd like to format the chat differently if the message comes from discord, is that right?

**Comment by pupshadow** [comment]
> I'm not sure to understand what your meant by "chat option". Could you please elaborate a bit? Are you talking about the format? You'd like to format the chat differently if the message comes from discord, is that right?

When I said options I mean in the format file. Its an option in my mind because you can make it be any variable you want "Meaning I have many options" for formatting my messages. 

I will make a modified format document show what I had to change to get it to work again.

Ill share my one I  was using  and the one that fixed the issue.

**Comment by pupshadow** [comment]
https://ufile.io/jxkze7su Here is the format file and I explained what happened in a comment.

**Comment by kangarko** [comment]
Thanks, glad it got fixed. The next version will properly show player_nick variable and replace it with pure name if it comes from Discord and player is offline.
<img width="440" alt="Screenshot 2022-04-07 at 12 57 18" src="https://user-images.githubusercontent.com/1918426/162184191-6456df91-d0e1-4f6d-b38f-965dc785a75d.png">

<img width="595" alt="Screenshot 2022-04-07 at 12 56 36" src="https://user-images.githubusercontent.com/1918426/162184216-21707ab4-f607-48dd-b949-f12bc6aff738.png">

**Comment by TimmyHung** [comment]
Hello there I'm using last version of CHC-Red. I have encounter same issued as above, {player_nick} not shown in minecraft chat when I'm not in the server.

Edited: {player} work fine without problems.

**Comment by kangarko** [comment]
I am so sorry, I will patch this and even work nicknames work when the player is offline.

**Comment by ScrapMetalGolem** [comment]
I see this is an older issue, so if I should make a separate thread please let me know and I will. However, I have the same result as above, but for a different reason, so I thought it might be appropriate to post here.

I am using CMI meta placeholders for nickname and chatcolor. (e.g. %cmi_user_meta_nickname%) This works splendidly in Minecraft, and works from Discord->Minecraft as long as the user is in the game. However, when the user is not in game, the result is no username is sent.

I'm not sure if I should talk to the discordsrv devs, CMI devs, or here, but at any rate I'm hoping for a solution that allows our discord bot to somehow send that placeholder in the message when the player is not in game.

Thanks for any consideration!

**Comment by kangarko** [comment]
It won't work when the user is not in the game because we lack the Player instance to input into CMI to get the placeholders. Even PlaceholderAPI asks for the player instance to retrieve them, so by nature it won't work.

**Comment by ScrapMetalGolem** [comment]
Unfortunate; I mostly expected that, but was hoping there was a solution. Will continue looking for a workaround, thanks.
