### ISSUE TITLE
Better Command AntiSpam

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1841]
**1.) Make commands listed in Whitelist_Delay ignore any active command delay.**
Right now, commands in Whitelist_Delay don't activate a cooldown, but if there is an active one from previous command, they don't get executed.

**2.) Make command antispam ignore cancelled commands.**
ChatControl does not ignore if the console cancelled the command or not. This results in ChatControl resonating with BoosCooldowns (and most likely more plugins), which uses warmups. For example if there is a warmup of 3 seconds for /spawn and the player executes it, the first /spawn is cancelled another one is activated once the warmup timer ends. The issue here is that both /spawn commands activate the command delay, not only the second one.

---
I need both of those features to fix a bug that is on my server. I have a command delay set to 1 second. If a player uses /spawn and quickly another command, for example /msg, the second /spawn (after the warmup ends) is blocked by antispam.

I tried adding /spawn to command whitelist, but it doesn't matter, because if the /msg was executed one second before the second /spawn, the /spawn is affected by antispam anyway. (And I can't add /msg to whitelist, because I don't want players to spam it.)

**Comment by kangarko** [comment]
Thanks, I can put this into my dashboard but unfortunately my plate is very full at the moment. You can try changing Listener_Priority to see if your cooldown plugin will be able to cancel our message beforehand.
