### ISSUE TITLE
1.18.2: Exception caused when talking via Discord

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1842]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

Debug file emailed to [support@mineacademy.org](mailto:support@mineacademy.org)

This [exception](https://pastebin.com/hzuyh1Qd) is caused if you have a format such as [this](https://pastebin.com/ndL7u3GB) because of the luckperm placeholders used in ``Sender_Condition``. However, if I use a simple format such as [this](https://pastebin.com/dzEGaupw), I no longer get the exception.

This format however works **100%** in-game with zero issues!! I don't believe it is because I have set up the conditions incorrectly??

NOTE: You need to change the part of the config for PlaceholderAPI in order for this format to work.
```yml
boolean:
  'true': 'true'
  'false': 'false'
```

---

**Extra Note**
While I have only done a quick test this is something worth noting!!!

What I found interesting was that, while [this](https://pastebin.com/ndL7u3GB) works 100% as intended if you are in-game but breaks if talking via discord (thus no message is sent), however if you use pretty much the same setup like [this](https://pastebin.com/ndL7u3GB) but change it to [this](https://pastebin.com/W5V1p0fL), talking via discord seems to work.

---

I assume in this part of the exception ``'false && '`` just means discord isn't handling the placeholders in the condition as intended?

Since these conditions don't work when talking via discord
```
Sender_Condition: '{sender_is_player} && {luckperms_has_groups_on_track_staff}'
Sender_Condition: '{sender_is_player} && !{luckperms_has_groups_on_track_staff}'
```
But these conditions work when talking via discord
```
Sender_Condition: '{sender_is_player}'
Sender_Condition: '{sender_is_player} && "{luckperms_has_groups_on_track_staff}" == "true"'
Sender_Condition: '{sender_is_player} && "{luckperms_has_groups_on_track_staff}" == "false"'
```

Based off the quick test I did.

**Comment by TheIntolerant** [comment]
P.s. Sorry if I miss any information, it's late and I wanted to make sure I report the bug asap before I get too busy lol

I only did some quick test but hopefully it's enough information to look into it further

**Comment by ElBananaa** [comment]
What happens if you try `'''{sender_is_player}'' == ''true'' && ''{luckperms_has_groups_on_track_staff}'' == 'true'''`

**Comment by TheIntolerant** [comment]
> What happens if you try `'''{sender_is_player}'' == ''true'' && ''{luckperms_has_groups_on_track_staff}'' == 'true'''`

Yeah that works fine!


This is weird because I get the exception if I were to do this in my format files:
```
Sender_Condition: '{sender_is_player} && {luckperms_has_groups_on_track_staff}'
Sender_Condition: '{sender_is_player} && !{luckperms_has_groups_on_track_staff}'
```

However, chat works normally via discord with these in the format files:
```
Sender_Condition: '{sender_is_player} && "{luckperms_has_groups_on_track_staff}" == "false"'
Sender_Condition: '{sender_is_player} && "{luckperms_has_groups_on_track_staff}" == "true"'
Sender_Condition: '"{sender_is_player}" == "true" && "{luckperms_has_groups_on_track_staff}" == "true"'
Sender_Condition: '"{sender_is_player}" == "true" && "{luckperms_has_groups_on_track_staff}" == "false"'
```
And so forth

Which doesn't make much sense lol, especially since all the examples above work fine if only using chat in-game, it's when it comes to discord that it breaks

**Comment by kangarko** [comment]
You'd have to use the fully explicit '== "false"' operator. This is caused due to javascript returning an empty string when the sender is discord because the variable cannot be parsed at all, whereas if the sender is player, then we properly parse the variable and return false.

**Comment by TheIntolerant** [comment]
Ahh okay, thank you for the heads up!
