### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1843]
Player cannot leave all channel, after upgrade 10.10.5 from 10.9.5
![image](https://user-images.githubusercontent.com/29138111/162112029-b85ea9e4-602f-40ef-be5e-c1dd017bb644.png)

https://youtu.be/V1EXJT2OcDI

Minecraft Version: 1.16.5
MySQL: true (mariadb)
BungeeCord: true

**Comment by kangarko** [comment]
Update to 10.10.5.

**Comment by kangarko** [comment]
If still that is a problem then please submit your /chc debug as a ZIP file
