### ISSUE TITLE
1.18.2: Whisper Disabled in 10.10.5 until Completing Tour

### ISSUE THREAD

**Issue by blockswerker** [kangarko/ChatControl#1845]
Minecraft Version: 1.18.2 Paper #282
MySQL: false
BungeeCord: false

I'm trying to diagnose an issue where no whispers (msg, tell, whisper, w etc.) are being received by players. The console shows "xxxxxx issued server command: /msg xxxxxxx" but the whisper is never received. This was working until I updated from 10.10.2 to 10.10.5.

Any help would be appreciated.

**Comment by blockswerker** [comment]
It turns out CHC decided that I need to re-do `/chc tour` before it would work. After I completed the tour then whispers started working again. Is it a bug that CHC requires admins to re-do the tour after updating?

**Comment by kangarko** [comment]
We disable most of our features until the tour is completed because you need to agree to our Terms of service to be able to use our software ;)

**Comment by blockswerker** [comment]
With all respect for your hard work Kangarko I don't think you understand. I already completed the tour and accepted the terms when I installed the plugin the first time. The plugin arbitrarily decided that I needed to do it again when I updated the plugin and it didn't tell me at the time - it just stopped working.

**Comment by kangarko** [comment]
I apology, then I will need to investigate this asap. We'll be rolling out a new version in a few days, hopefully that stopped happening after the second time for you, please correct me if I am wrong.
