### ISSUE TITLE
"Billing"

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#1847]
Hey, as context, just wanted to say I paid for this resource twice (CHC, and now CHCRed), and have had to configure either one or the other version like 3 or 4 times from scratch due to continuous development changes.

Now I'm being asked to "Renew now for $9.97" on MCMARKET.
My username there is MithradirCraft, and I bought this resource some time around a year ago.

On the CHCRed site it says the license lasts 50 years (If this is not the case, maybe it should be changed).

I understand you may want to recharge your persisting customers, and that this is (probably) a full time business for you, but I believe I haven't given this plugin such use for the price, and wish to express that I won't go through with the aditional charges, eventually moving to alternative chat systems, since I don't use this plugin so heavily.

Take that as constructive marketing feedback, not as a threat, I don't feel I've amortized the last 30$ I paid for last year yet, nor was I aware that this was a subscription.

**Comment by ElBananaa** [comment]
> Hey, as context, just wanted to say I paid for this resource twice (CHC, and now CHCRed), and have had to configure either one or the other version like 3 or 4 times from scratch due to continuous development changes.
> 
> Now I'm being asked to "Renew now for $9.97" on MCMARKET. My username there is MithradirCraft, and I bought this resource some time around a year ago.
> 
> On the CHCRed site it says the license lasts 50 years (If this is not the case, maybe it should be changed).
> 
> I understand you may want to recharge your persisting customers, and that this is (probably) a full time business for you, but I believe I haven't given this plugin such use for the price, and wish to express that I won't go through with the aditional charges, eventually moving to alternative chat systems, since I don't use this plugin so heavily.
> 
> Take that as constructive marketing feedback, not as a threat, I don't feel I've amortized the last 30$ I paid for last year yet, nor was I aware that this was a subscription.

Hey,
We don't want to "recharge our persisting customers". What you're experiencing is an issue that's been introduced for some random resources by mcmarket when they updated their forums, a few months ago.

You also could've asked for a completely free upgrade when switching from chatcontrol-pro to chatcontrol-red. The plugin **isn't a subscription that you need to renew each year. It's a one-time purchase.**

Please read https://github.com/kangarko/ChatControl-Red/issues/1680 and follow what's written there to **get your licence back for free**.

**Comment by MithrandirCraft** [comment]
Great thanks for letting me know this, I knew something wasn't right.

**Comment by kangarko** [comment]
Sorry for the trouble, I made the mistake in 2020 of charging existing customers to upgrade to Red, now we offer all Pro customers a free upgrade. 

Due to MCMarket technical change when they rolled 2.0, I had to set an upgrade price, but in reality we do really upgrade for free, you can do this over mineacademy.org/chatcontrol-red#upgrade > form > chatcontrol red > mcmarket > license expired ;)

I understand the inconvenience and would love to offer you one of our premium plugins for free as an apology (lifetime access), since I have your MCMarket username just let me know what plugins you'd like to check out and I'll add you!
