### ISSUE TITLE
1.18.2: Unable to send custom png on chat

### ISSUE THREAD

**Issue by angwdev** [kangarko/ChatControl#1848]
`java.lang.StringIndexOutOfBoundsException: begin 2, end 1, length 1`
Minecraft Version: git-Paper-282 (MC: 1.18.2)
MySQL: true
BungeeCord: true
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8477397/debug.zip)
https://pastebin.com/ndXKX0CD

**Comment by ElBananaa** [comment]
Hey,
Sorry for the delay, I completely forgot to take a look at your issue.
I did run tests on my end, and I'm able to reproduce your issue too.

I also noticed everything works fine with the default image provided by the plugin.
Please wait for Kangarko to have a look at this issue ;)

**Comment by TheIntolerant** [comment]
Hello, not sure if this is worth adding but it seems this is only caused when an image is used with a transparent background.

I used the same image but without it having a transparent background and it worked.
![image](https://user-images.githubusercontent.com/48093184/163704672-43b2533d-6e44-4349-b8e1-eeeba2ff0414.png)

Will leave this open still in case there is anything Kangarko can do something to fix this. :P

**Comment by TheIntolerant** [comment]
I must admit it would be super cool if Kangarko can make it possible to use images that have transparent backgrounds!!

**Comment by kangarko** [comment]
Thanks, unfortunately this is a limitation of the image parser, and I am not skilled enough to customize that library since I am typically not dealing with parsing images. You can for now just fill the transparent pixels with black color or any other closest-fit color.

**Comment by angwdev** [comment]
ok, thnak you

**Comment by ElBananaa** [comment]
Fixed in https://github.com/kangarko/Foundation/pull/154
