### ISSUE TITLE
Block certain messages

### ISSUE THREAD

**Issue by msmanui** [kangarko/ChatControl#1849]
Hello!

If someone spam something like: "BestTownSurvival.Com"

How can i use the match tool? Like if it the phrase match "Best + Town + Survival"  Consider i dont want to match the whole phrase like (BestTownSurvival.Com) just certain words inside the phrase

**Comment by TheIntolerant** [comment]
Chatcontrol uses regular expressions (RegEx) to find (or "match") a sequence of characters to which it than can do something with depending on the operators listed below.
For information regarding operators read through this part of the wiki - [Rules](https://github.com/kangarko/ChatControl-Red/wiki/Rules )

For example this replaces “example123” with “*****”

```
match (example123)
then replace *****
```

To test your RegEX you can use [RegEx101](https://regex101.com)

Just make sure to select these flags

![image](https://user-images.githubusercontent.com/48093184/163432321-de033c99-0054-411b-9466-18c27e5dfb3a.jpeg)

**Comment by TheIntolerant** [comment]
Something like the following would match “BestTownSurvival” etc as demonstrated in the screenshot below.

```
match (b+e+s+t+( |)t+o+w+n+( |)s+u+r+v+i+v+a+l+)
```
![image](https://user-images.githubusercontent.com/48093184/163432821-613f7b98-a524-4098-b129-cc6431192421.jpeg)

**Comment by msmanui** [comment]
> (b+e+s+t+( |)t+o+w+n+( |)s+u+r+v+i+v+a+l+)

best in the town survival, you can bypass like this for example, how to prevent that?

**Comment by TheIntolerant** [comment]
Have you tried to do this yourself first? If you haven't I strongly suggest you do, as this will help you patch such things faster.

Anyway, inserting this into the section mentioned above would prevent that ``( in the )?`` Obviously you can add the ``+`` if you want to prevent "iiiinnnnn ttthhheee" etc

**Comment by kangarko** [comment]
Closing since I feel this has been answered, you can find more info about rules on our Wiki, and regarding regular expressions (match XX where XX is a regular expression) on the internet since this is a universal language. If you need more help then I suggest asking out on our discord!

**Comment by kangarko** [comment]
Closing since I feel this has been answered, you can find more info about rules on our Wiki, and regarding regular expressions (match XX where XX is a regular expression) on the internet since this is a universal language. If you need more help then I suggest asking out on our discord!

**Comment by kangarko** [comment]
Closing since I feel this has been answered, you can find more info about rules on our Wiki, and regarding regular expressions (match XX where XX is a regular expression) on the internet since this is a universal language. If you need more help then I suggest asking out on our discord!
