### ISSUE TITLE
1.16.4 | Find cause of range settings not work problem.

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#185]
Okay redo my text, Is vanish as do you also see local chat, as you would within 150 range of the player.

https://luckperms.net/verbose/lLxovVRrrO

**Comment by kangarko** [comment]
Sorry what is exactly the issue?

**Comment by broken1arrow** [comment]
> Sorry what is exactly the issue?

When you use vanish (in this case use it from cmi), I can see players range chat even if i´m not in range of any player (Is work as i should if i turn of vanish). Is not big issue.

**Comment by kangarko** [comment]
Thanks I fixed that!
