### ISSUE TITLE
Centering message in motd? (question)

### ISSUE THREAD

**Issue by AndGK** [kangarko/ChatControl#185]
Is there any way of centering a message in MOTD? Because if you use the {player} handle and manually set up spaces, it always would shift due to players length of the name. If there are no way of doing so, would be a great idea of featuring this in next updates :)

**Comment by kangarko** [comment]
There is no native way yet, but I take this as a suggestion.

**Comment by kangarko** [comment]
Closing and moving to the pro channel.
