### ISSUE TITLE
Potential collaboration with the dev of InteractiveChat?

### ISSUE THREAD

**Issue by itsBeaco** [kangarko/ChatControl#1850]
Hi there!

I'd just like to suggest the possibility of a collaboration between you guys and the dev of the plugin, InteractiveChat 

<https://www.spigotmc.org/resources/interactivechat-show-items-inventory-in-chat-custom-chat-keywords-bungee-velocity-support.75870/>

Currently, as far as I can tell, and as claimed by the Dev, InteractiveChat is incompatible with CCR. I personally, and I think others would too, would like the opportunity to use the plugin on our servers. At the moment, the dev is unable to look into making it compatible with CCR due to it being a premium plugin.

I'm not sure how willing you would be, or if you currently have the resources, but just thought I'd make the suggestion as it could only make the plugins better 😄 

Happy to hear your thoughts on this and looking forward to hearing back from you. Thank you in advance!

**Comment by kangarko** [comment]
Hey! Any developer is welcome to get free access to ChatControl Red and hook into it, they can simply request this using our mineacademy.org/chatcontrol-red#upgrade form ;)

**Comment by itsBeaco** [comment]
That's awesome, I've reached out to the developer to let them know 😄 

Thank you!

**Comment by itsBeaco** [comment]
Somehow I've become the middle man 😆 but, I reached out to the developer and they were kind enough to look into it and this is part of their response. Any suggestions with this? or, is it something that could possibly be added?

Thank you again!

![image](https://user-images.githubusercontent.com/77558094/164546073-e198fef1-76b0-4ca0-b590-2ceb296caeb1.png)

**Comment by kangarko** [comment]
Thanks. Yep unfortunately we have a ton of custom handling to make sure we support hover/click events as well as javascript variables, side effect is incompatibility with a few other plugins. Because I am quite busy these weeks and you're the only one ever asking for interactivechat specifically I won't be making a major change in the plugin, I am sorry. But you can just disable our channels and discord integration completely and use your solution instead.

**Comment by itsBeaco** [comment]
I completely understand, it's not an issue. I'd rather have the channels and things. I appreciate your time and willingness to allow others to look at the code and add what they can. Thank you for getting back to me and I hope you doing well. CCR is an amazing plugin nonetheless, keep up the good work!
