### ISSUE TITLE
1.18.2: 10.10.3 Trailing Space Bug still present in 10.10.5

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1851]
Seems like quite a few trailing space issues (little blank space before messages) Doesn't happen everywhere or as often, but still present in many areas. Edited the lang of the announce command to display what I wanted, and it gives an extra space before the actual message that's being announced. 

Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey,
In which messages are these spaces present exactly?

**Comment by HorusApl** [comment]
The /chc broadcast or the chc announce commands both seem to do it. In the Lang, I edited the layout of this to be just the placeholder {lines} so that you only see the broadcast and not the massive wall of text that is standard. Death messages do it as well last I checked too.

**Comment by TheIntolerant** [comment]
Could you provide your debug file, to get it simply type "/chc dug" thanks. If you wish to provide this privately you can email it to

support@mineacademy.org

Just keep in support may be slightly delayed in getting a response if you choose to email it privately depending on how busy matej is.
Also make sure you include information about this issue such as link to this issue report.

**Comment by HorusApl** [comment]
[debug (6).zip](https://github.com/kangarko/ChatControl-Red/files/8501197/debug.6.zip)

**Comment by kangarko** [comment]
Thanks, I believe this will be resolved in the next release.
