### ISSUE TITLE
Issue with /ignore & /ignore list commands

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#1852]
hello
you can **/ignore player**
but you can't unignore the player
or i didn't find any command for it

**Comment by ElBananaa** [comment]
> hello you can **/ignore player** but you can't unignore the player or i didn't find any command for it

Hey,
To remove a player from the ignored players list, simple type the ignore command again.

**Comment by FakEEE14** [comment]
here take look when you /ignore player twice
![image](https://user-images.githubusercontent.com/68513641/163683526-90c0cb52-ae01-4449-85c1-120600c28340.png)

**Comment by ElBananaa** [comment]
> here take look when you /ignore player twice ![image](https://user-images.githubusercontent.com/68513641/163683526-90c0cb52-ae01-4449-85c1-120600c28340.png)

This is a known issue someone already reported to me privately. I already sent a message to @kangarko about it.
I'm reopening this issue so we can keep you updated about the updates.

**Comment by FakEEE14** [comment]
take another look list is bugged too
![image](https://user-images.githubusercontent.com/68513641/163683796-70618cc7-669a-41d5-9d98-f166f5f65d26.png)
i lareday ignore someone but there is no one on my ignore list

**Comment by ElBananaa** [comment]
Yes, we're already aware of this too. Can you please provide us more informations about your environment? (Server Version? Do you use MySQL? And your `/chc debug` file)

**Comment by FakEEE14** [comment]
i oppen this for question
can you change it to bug report ?
**paper 1.18.2 builde 283
bungeecord: true
mysql: true**
[general.txt](https://github.com/kangarko/ChatControl-Red/files/8500328/general.txt)

**Comment by TheIntolerant** [comment]
> i oppen this for question
> 
> can you change it to bug report ?
> 
> **paper 1.18.2 builde 283
> 
> bungeecord: true
> 
> mysql: true**
> 
> [general.txt](https://github.com/kangarko/ChatControl-Red/files/8500328/general.txt)
> 
>  

This isn't necessary, as all other issue types such as bug reports (except the issues for VelocityControl), do not automatically assign a label to the issue on creation.

**Comment by TomLewis** [comment]
I came here to report /ignore is yet again broken! I cant remember a time where ignore wanst broken!
You also can not unignore people that are ignored, its fully broken, you cant ignore someone one, you cant unignore either.

PurPur 1.18.2, MySQL.

Its going to be MySQL again. 

Edit: I was right, its not touching the Data Column for ChatControl table for users.

**Comment by kangarko** [comment]
@TomLewis probably only works during my testing haha

Anyways, found something that may have been the cause and I fixed it!

Details:
https://www.loom.com/share/debb716d6ec24da4bcb22f21dcd3c25c

**Comment by TomLewis** [comment]
> @TomLewis probably only works during my testing haha
> 
> Anyways, found something that may have been the cause and I fixed it!
> 
> Details:
> https://www.loom.com/share/debb716d6ec24da4bcb22f21dcd3c25c

First time I've had a developer reply with a video, voiceover and camera shot! Quality reply!

It seems to be working now. I'll give it a few more days of users testing, if you don't hear back from me then it should all be fine.

Thanks for the video demo, wasn't expecting that!

**Comment by kangarko** [comment]
@TomLewis thank you!
