### ISSUE TITLE
1.18.2: Can't send a mail to an offline player

### ISSUE THREAD

**Issue by dremovand** [kangarko/ChatControl#1853]
Minecraft Version: 1.18.2 (Paper build 278)
ChatControlRed Version: 10.10.5.
MySQL: false
BungeeCord: false
Plugins: MiniMOTD v2.0.6, LuckPerms v5.4.16, ExplainMe v1.0, PlaceholderAPI v2.11.1, Vault v1.7.3-b131, InvSeePlusPlus v0.11.8-SNAPSHOT, ProtocolLib v4.8.0, WorldEdit v7.2.10+1742f98, ViewDistanceTweaks v1.5.0, PremiumVanish v2.7.13, TCPShield v2.5.6, ChatControlRed v10.10.5, TAB v3.1.1, HeadDatabase v4.16.0, LiteBans v2.8.13, WorldGuard v7.0.7+216b061, CoreProtect v21.2, Spartan vBuild 457, GSit v1.0.7, CoreProtectTNT v2

Hey!

Issue description is minuscule, just can't send a mail to an offline player.
As an example, I've used a player named "borobushee", I've also checked that in the db we have a record for that player.
Results of `/chc debug` - [debug.zip](https://github.com/kangarko/ChatControl-Red/files/8499985/debug.zip)

Thanks!

**Comment by kangarko** [comment]
Thanks for your patience and waiting, I can confirm this works on the next release :)
