### ISSUE TITLE
1.18.2: vanish got broken

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1854]
Hello, updated CCR from `10.10.4` to `10.10.5`. Now players can see join messages and can tab complete and send PMs to vanished player. I use vanish from the CMI.

Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Thanks, should be fixed in the next update.

**Comment by kangarko** [comment]
If not, please let me know how you vanish these players (on another server and then you expect it to pickup using bungeecord?)
