### ISSUE TITLE
Question: Exception for switch messages

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1855]
the 'try this' sollution did not succees im sorry to say :(
this new questions is a followup from ticket #1788 

Still getting errors

> [01:18:34 INFO]: ChatControlRed 10.10.4 encountered a FoException! Please check your error.log and report this issue with the information in that file.
> [01:18:34 WARN]: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Unrecognized operator 'ignore sender server quests' found in Player Message {
> [01:18:34 WARN]:        'Type' = 'join'
> [01:18:34 WARN]: }
> [01:18:34 WARN]:        at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.lib.Valid.checkBoolean(Valid.java:90)
> [01:18:34 WARN]:        at ChatControl-Red-10.10.4.jar//org.mineacademy.chatcontrol.operator.Operator.onOperatorParse(Operator.java:522)

I might just as well be messing up, since the wiki isnt exactly a practical guide i need to basicly guess what to do. I am using the part of the wiki that @ElBananaa tolled me to use, so i know i am using the correct variabled, but where to write them i am not 100% clear. I will try to make clear below. What would be the correct way of writing the config file ?

Without the ignore part i have this working: 

> group default
> message:
> - &2[&a+&2] &a{player}

When trying to incorporate the ignore message i make this:

> group default
> ignore sender server quests
> message:
> - &2[&a+&2] &a{player}

This is the 'join.rs' config on my survival server. I am trying to ignore the join message from a player when he/she joined the survival server when they are comming from the quest server, but only from the quest server. any other server should create a join message.

**Comment by TheIntolerant** [comment]
> ```rust
> group default
> ignore sender server quests
> message:
> - &2[&a+&2] &a{player}
> ```
> 
> This is the 'join.rs' config on my survival server. I am trying to ignore the join message from a player when he/she joined the survival server when they are comming from the quest server, but only from the quest server. any other server should create a join message.
> 
> 

When you say "This is the 'join.rs' config on my survival server", are you saying that this is what is inside of your join.rs file in chatcontrol on your survival server?

If that is the case, the [wiki](https://github.com/kangarko/ChatControl-Red/wiki/Messages#ignore-sender-server-require-sender-server-ignore-receiver-server-require-receiver-server) states that "ignore server" etc. is a BungeeCord condition, therefore it cannot be used on your backend servers (the servers that actually run chatcontrol).

Which is why you would get this error

**Comment by kangarko** [comment]
Correct, you can only use "ignore server" on BungeeCord. It doesn't make sense to use it on Spigot since you simply would not put the rule on the server you prefer it not to have.

**Comment by kangarko** [comment]
I have a feeling that I might have misunderstood you, please comment below if you meant something else !
