### ISSUE TITLE
Optimize it

### ISSUE THREAD

**Issue by Chumb3x** [kangarko/ChatControl#1857]
Optimize the plugin because it laggs the server. 
![image](https://user-images.githubusercontent.com/79834154/164324624-b54e1f28-fda3-4689-9f72-2e16953970db.png)

**Comment by ElBananaa** [comment]
Hey,
You're using an outdated version, please update to the latest one.
Also, did you enable the async features? They can be found in the settings file.
They should look like that
![image](https://user-images.githubusercontent.com/53318613/164334048-e42eb895-608d-4eb6-a1a7-51126dde7418.png)
![image](https://user-images.githubusercontent.com/53318613/164334064-283cbf07-9b3f-4808-adce-bdec6775de28.png)

**Comment by Chumb3x** [comment]
What does Async do?

**Comment by ElBananaa** [comment]
Async means that the plugin will manage some things off the main thread, which should result in way better performances.

Closing this assuming this should solve the issue.
Let us know down below if you need anything else.
