### ISSUE TITLE
Chat randomly breaks for some players sometimes

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#186]
https://pastebin.com/jTbAYHPL

Chat randomly breaks for some players sometimes

**Comment by kangarko** [comment]
Cannot reproduce, how did you get this error please?

**Comment by DoogiePC** [comment]
I really can't say, its a random player just chatting randomly and it breaks randomly

**Comment by kangarko** [comment]
Please test the next version.
