### ISSUE TITLE
Optimize it

### ISSUE THREAD

**Issue by Chumb3x** [kangarko/ChatControl#1860]
You have to optimize it. I have async enabled and it still uses most of the cpu. 
![image](https://user-images.githubusercontent.com/79834154/164889727-a4a8923c-3ae9-4482-9b67-bdc1328627c9.png)

**Comment by ElBananaa** [comment]
Please provide us information about your environment (server version? Mysql enabled?), your `/chc debug` file and the link of the spark report.

We've also already asked you multiple times to follow the bug report format in both the issue message and the title, so please do so.

**Comment by Chumb3x** [comment]
1.16.5 paper. no Mysql.  . Please message me when you review the timings because I have to remove the link since there are all my plugins ...
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8546969/debug.zip)

**Comment by ElBananaa** [comment]
Please install Spark and run a spark report then provide us the link

**Comment by Chumb3x** [comment]
https://spark.lucko.me/ucG4PQ0zEK

**Comment by ElBananaa** [comment]
> https://spark.lucko.me/ucG4PQ0zEK

- You provided a spark heap summary. Please provide us a spark profiler report instead.
- According to the heap summary, you don't use Aikar's flags. We suggest using them.
Airplane made a simple and useful tool on their website to generate the right flags based on the memory allocated to your server: https://blog.airplane.gg/aikar-flags/
- I noticed you are using Java 16, I'd suggest switching to java 17 as this is the latest stable LTS version.
- It appears both your db file and your log file are pretty "heavy". I'd also suggest switching to a MySQL database.
- Decrease the value of the `Clean_After:` setting in your settings file to something like `Clean_After: 10 days`
- Decrease the value of the `Clear_Data_If_Inactive:` setting in your settings file to something like `Clear_Data_If_Inactive: 30 days`

**Comment by kangarko** [comment]
Thanks to banana for the tips, I recommend switching over to MySQL since all queries are run async as opposed to non-mysql where you can't turn it async, so it'll always show up on spark.
