### ISSUE TITLE
1.18.2 Mysql crashing server

### ISSUE THREAD

**Issue by OhhGeeCluster** [kangarko/ChatControl#1863]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

I have been getting server crashes due to this error: https://pastebin.com/xHuW1GwE

`Error on querying MySQL with: SELECT * FROM ChatControl`
then
`Error getting user record from MySQL. Returning incomplete data...`

**Comment by kangarko** [comment]
Update the plugin, remove all ChatControl tables and check if your connection is correctly setup. Use MySQL or MariaDB
