### ISSUE TITLE
1.18.2: All console colours broken after Paper build 244

### ISSUE THREAD

**Issue by addstar** [kangarko/ChatControl#1864]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

Last month Paper merged [this PR](https://github.com/PaperMC/Paper/pull/7560) which "broke" console colours for any plugin using the unsupported section sign (`§`). It replaces them all with `0x7F` to show when a plugin is using unsupport colour handling. It affects many other plugins too but any plugin using the proper colour methods are fine:

![image](https://user-images.githubusercontent.com/1924905/165071376-cc7d2a68-2d4d-4934-89dd-e9c27cb15836.png)
![image](https://user-images.githubusercontent.com/1924905/165071822-5c866169-9274-4d92-99ad-2fae9d9259d4.png)

From the Paper discord:
> using the § char as a legacy color code symbol in a logger is unsupported, and plugins should use alternative methods for showing colors to the console.

Is this something you're aware of and/or in the process of fixing? Thanks!

**Comment by kangarko** [comment]
This is ridiculous, let's wait how the situation will pin out, looks like they are intentionally breaking tons of plugins right now. I am sorry, I am busy recording a new training program than wasting my time having to backport an odd fix for some kids thinking they can force everyone using their stupid adventure library

**Comment by addstar** [comment]
> This is ridiculous, let's wait how the situation will pin out, looks like they are intentionally breaking tons of plugins right now. I am sorry, I am busy recording a new training program than wasting my time having to backport an odd fix for some kids thinking they can force everyone using their stupid adventure library

I'm fine with deprecating functionality (when there's a suitable replacement) but I agree this seems ridiculous to force this without a way to override it. So many of our plugins now have broken colours in console, so we either stay "stuck" at build 243 and lose all the fixes in the past ~70 builds, or we just deal with bad unreadable console chat/output... 

They seem to be pretty insistent that they are not changing, I plan to look into what is needed to be updated. I don't think you _must_ use Adventure, you just can't use the "legacy" symbol for colours. Not sure how ChatControl is doing logging but surely the `ChatColor` class is still fine to use...

**Comment by addstar** [comment]
Did some reading up on the change... so yes, `ChatColor` is considered "legacy" and it's use is unsupported. Seems like Adventure API is the only supported way from what I can tell. Paper are saying MiniMessage is the direct replacement: https://docs.adventure.kyori.net/minimessage/

It would have been nice if they announced a cut off date in advance so people could be prepared, rather than just suddenly break most plugins and force devs to quickly update! :angry:

We rely heavily on console and chat colours, so this is a huge pain.. for now we're stuck at build 243 until we work out a solution :pensive:

**Comment by Machine-Maker** [comment]
Just to chime in, you can still use ChatColor and legacy text when you send a message to the ConsoleCommandSender. Like `Bukkit.getConsoleSender().sendMessage(ChatColor.RED + “this is red”);`. Just not to a logger, since loggers are support to log data, not parse unsupported pairs of characters.

**Comment by MiniDigger** [comment]
machine-maker you got this wrong, we are just kids that don't know what we are doing, you can't make sensible suggestions to improve others people's projects, that's not how this works!

**Comment by addstar** [comment]
> Just to chime in, you can still use ChatColor and legacy text when you send a message to the ConsoleCommandSender. Like `Bukkit.getConsoleSender().sendMessage(ChatColor.RED + “this is red”);`. Just not to a logger, since loggers are support to log data, not parse unsupported pairs of characters.

@Machine-Maker :100: Thank you for your suggestion! :grinning: Your comments pointed me to look at our log4j config because we had plugins using `Bukkit.getConsoleSender()` with `ChatColor` not working... So I dug deeper and turns out our (old) log4j config has been wrong/out of date for a long time and the changes in build 244 just triggered the colour issue. My apologies, I falsely assumed Paper had broken ConsoleSender colours :man_facepalming: 

This is no longer an issue for us, I had misunderstood the problem. ChatControl uses ConsoleSender and is working as expected with the default log4j config from paper :partying_face: Colours of all our other plugins are working fine too.

**Comment by kangarko** [comment]
> machine-maker you got this wrong, we are just kids that don't know what we are doing, you can't make sensible suggestions to improve others people's projects, that's not how this works!

Are you kidding? I am always open to discussion, Paper just locked their issue completely. Look again before posting troll comments you fool.

**Comment by kangarko** [comment]
@addstar glad this has been resolved (for now), let's hope either Paper stops making ridiculous API breaks or someone makes a decent fork again ;)

**Comment by electronicboy** [comment]
The logger handling section symbols was never an API contract but a side effect of how craftbukkit implemented the way that the command sender dealt with this stuff, this feature was moved over to the terminal console appended but, such logic was aimed to be replaced by an alternative replacement which can handle modern text features, and in part because the deprecated formats support is intended to be removed from TCA given stuff is moving forward, i.e. RGB; the inclination to maintain behavior which was deprecated 7 years ago was minimal but was somewhat open for discussion until people started blindly badgering us

You didn't invoke any form of discussion, you just came in making blind demands that we revert some change with 0 consideration towards existing discussions we've had about this in public, or the reason why said changes where made, that said, OP here confirmed that this was not an issue with paper but their own setup.

I do ask that people on both sides of this aim to maintain a level of respect for one another.

**Comment by ElBananaa** [comment]
Come on, let's not start another useless childish fight here.
Kangarko made a mistake, he shouldn't have been aggressive towards anyone here, neither he should've instantly put the blame on you.
You guys shouldn't come here to provocate neither (some of you didn't).

We all know you guys can't stand each others, that's fine. Paper/spigot communities don't like kangarko or his work, that's fine, let's just not pour more fuel on the fire.

If you guys want to discuss, just reach each others privately. If some of you want to trashtalk kangarko, keep it on your discord servers/DMs.

The issue has been solved, that's the only thing that matters.
Thanks @electronicboy for the heads-up.

Now let's stop it there.
Have a nice day yall.

**Comment by kangarko** [comment]
@electronicboy thanks for clarifying, I was not aware of previous talks on this subject so I am sorry for drawing quick conclusions, and I appreciate your explanation. I am glad it got resolved by the user.
