### ISSUE TITLE
1.18.2: How to delete one message instead of multiple message when i used in several server?

### ISSUE THREAD

**Issue by Lemonray114** [kangarko/ChatControl#1865]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

I used ChatControl-Red in several server but linked,
when i delete one message, it will repeat the job for other server,
it makes other message also deleted that not I wanted to,
How to settings so i can just delete one specific message ?

**Comment by kangarko** [comment]
Sorry but if you link your servers together then we will remove the message from all servers, that is a feature.

**Comment by Lemonray114** [comment]
But the thing is it not only delete the message from all server, it delete the message that i want to delete, and other 4 different message ,so that when i delete the message A, message B, C and D will deleted also

**Comment by kangarko** [comment]
You're saying that if I type "Hello" on 1 server it will also delete other messages such as "Goodbye" on other servers? Sorry maybe I am misunderstanding here?
