### ISSUE TITLE
1.18.2: Localization config does not capitalise the first letter

### ISSUE THREAD

**Issue by Nextinka** [kangarko/ChatControl#1866]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: false

Whenever I'm modifying the localization config and adding color codes before the messages, it won't capitalise the first letter of the sentence.
![image](https://user-images.githubusercontent.com/98180136/165353207-05a7e99a-2c6a-442b-b1f6-10a2a54f00c0.png)

Output:
![image](https://user-images.githubusercontent.com/98180136/165353561-c1f2dfca-5095-4a88-b0e2-6c59ae06675e.png)

Happens on the latest CHC version (10.11.0)

**Comment by kangarko** [comment]
What command exactly are you typing? "/chatcontrol color #55ffff" ? 

Please send me your localization file.

**Comment by Nextinka** [comment]
[messages_en.zip](https://github.com/kangarko/ChatControl-Red/files/8574059/messages_en.zip)
Command: **/chc c #55FFFF**

**Comment by ElBananaa** [comment]
Hey,
I can confirm i'm also able to reproduce this issue, even with the default lang file. As soon as you add a color code before the message, it lowercase the 1st letter.

**Comment by kangarko** [comment]
Thanks will get fixado§
