### ISSUE TITLE
1.18.2: Colorblind Mode/Colorless

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1867]
Is there any way to have a player specific way to strip excess colors/placeholders etc from chat? A command or permission to give a player to have the chat reverted to a more default state. I saw through sender and receiver condition that such a thing may be doable, just unsure how to execute this.

Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
You should be able to create a rule in rules/chat.rs that will remove colors from the player's message, you can just ask out about this on our Discord ;)
