### ISSUE TITLE
Default fake message

### ISSUE THREAD

**Issue by dartasen** [kangarko/ChatControl#187]
Hi, I'm french and I use custom localization.yml file. All translated messages work but fake message doesn't.
My localization_fr.yml : [http://prnt.sc/eli6ir](config)
Fake message in game : [http://prntscr.com/eli9nm](screen)

Version : 7.2.5

**Comment by kangarko** [comment]
Hey, please make your localization file works otherwise. What's your **Messages.Join** and **Messages.Quit** in settings.yml ?

**Comment by dartasen** [comment]
I have'nt any **Messages.Join** and **Messages.Quit** in my settings.yml...

**Comment by kangarko** [comment]
ChatControl does have them. If you are using the pro version, close this ticket and reopen new [here](https://github.com/kangarko/ChatControl-Pro/issues).
PS: There is no such version as 2.7.5

**Comment by kangarko** [comment]
Closing, assuming it's fixed. Please let me know if you have any more questions.
