### ISSUE TITLE
1.16.4 | MOTD kicks players from the server

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#187]
When i try to join the server instead of getting MOTD i just get kicked from bungee
![image](https://user-images.githubusercontent.com/62369973/100548059-4da5a680-327b-11eb-808f-38ab68cda4f3.png)

MOTD:
[motd.zip](https://github.com/kangarko/ChatControl-Red/files/5612484/motd.zip)

**Comment by kangarko** [comment]
Hey,

I am very sorry but I could not fix this, when I split the packet it got distorted: https://i.imgur.com/qP2TS6S.png

The problem is in artificial limit imposed by BungeeCord. You need to make your format shorter for it to send.
