### ISSUE TITLE
1.18.2: How to delete one message instead of multiple message when i used in several server?

### ISSUE THREAD

**Issue by Lemonray114** [kangarko/ChatControl#1870]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

I used ChatControl-Red in several server but linked,
when i delete one message, it will repeat the job for other server,
it makes other message also deleted that not I wanted to,
it delete the message that i want to delete, and other 4 different message ,
so that when i delete the message A, message B, C and D will deleted also
How to settings so i can just delete one specific message ?

**Comment by kangarko** [comment]
Let's continue your discussion on your older issue, do not open duplicate issues as we reply to all of them.

Please try using the latest dev build of ProtocolLib for these servers. Try without ViaVersion if you use that.

**Comment by ElBananaa** [comment]
@kangarko Latest ProtocolLib devbuilds completely break the whole message deletion feature as said here https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#i-am-unable-to-remove-individual-chat-messages-with-latest-protocollib-dev-builds

**Comment by kangarko** [comment]
Sorry, you are right Nathan, please use ProtocolLib 4.8.0
