### ISSUE TITLE
Option to toggle Sound Notify (if enabled) using /toggle

### ISSUE THREAD

**Issue by MrCrazys** [kangarko/ChatControl#1871]
I believe that the ability to toggle sound notify using /toggle would be extremely useful for staff members and popular players such as YouTubers or Twitch streamers, mainly because large networks with lots of players may have multiple players repeating someone's name in the chat. For the recipient, this can become extremely annoying if they are for example watching a video, listening to music, etc. In order to prevent it, said player would have to take extremely inconvenient measures, such as disabling said sound, negating permissions from themself (if they can, of course), and possibly disabling their chat entirely. Without this setting, it is very hard to combat this problem. I believe that many servers, especially larger networks, would greatly benefit from this addition.

**Comment by ElBananaa** [comment]
> I believe that the ability to toggle sound notify using /toggle would be extremely useful for staff members and popular players such as YouTubers or Twitch streamers, mainly because large networks with lots of players may have multiple players repeating someone's name in the chat. For the recipient, this can become extremely annoying if they are for example watching a video, listening to music, etc. In order to prevent it, said player would have to take extremely inconvenient measures, such as disabling said sound, negating permissions from themself (if they can, of course), and possibly disabling their chat entirely. Without this setting, it is very hard to combat this problem. I believe that many servers, especially larger networks, would greatly benefit from this addition.

Hey,
Thanks for your suggestion.
Added in https://github.com/kangarko/ChatControl-Red-Src/pull/25

**Comment by kangarko** [comment]
Thanks to Banana for handling this, great job!
