### ISSUE TITLE
removing messge by internal command don't work

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#1873]
this part from formats don't work ```
  delete-chat: 
    Message: "&8[&4X&8] &f"
    Hover: "&cRemove this message from chat for all players."
    Run_Command: "/{label} internal remove {message_uuid}"
    Receiver_Permission: chatcontrol.removemessages```
![image](https://user-images.githubusercontent.com/68513641/166116919-750290b0-82f2-4eb7-9410-87725fad2936.png)
and this do nothing

Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> this part from formats don't work ` delete-chat: Message: "&8[&4X&8] &f" Hover: "&cRemove this message from chat for all players." Run_Command: "/{label} internal remove {message_uuid}" Receiver_Permission: chatcontrol.removemessages` ![image](https://user-images.githubusercontent.com/68513641/166116919-750290b0-82f2-4eb7-9410-87725fad2936.png) and this do nothing
> 
> Minecraft Version: 1.18.2 MySQL: true BungeeCord: true

Please provide us your debug file.

**Comment by FakEEE14** [comment]
i think the only thing that needed is in the debug is this
[general.txt](https://github.com/kangarko/ChatControl-Red/files/8598181/general.txt)
everything other (books,firmats,images,localization,messages,rules,vatuables)folders and settings.yml are fresh, no erorr.log and intresting thing is mysql and bungee is enabled bug in the text says false and null

**Comment by ElBananaa** [comment]
Please read and follow what's said here: https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#i-am-unable-to-remove-individual-chat-messages-with-latest-protocollib-dev-builds
This will solve your issue.

**Comment by FakEEE14** [comment]
yeah thats true, protocollib build 548 is works
