### ISSUE TITLE
1.18.2: Raw message or optional color apply

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1874]
Is there a way to get raw player message without color applied through the `/chc color` that I can use in formats? The problem is: I don't want to apply colors set by players to all channels, only specific ones, but every `{message}` string gets colorized in all channels.

Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Dupe of #1812

**Comment by kangarko** [comment]
I see, I can have a look into this and prioritize it

**Comment by kangarko** [comment]
Solved using the new {chat_color} variable :)

**Comment by radiant-ai** [comment]
You rock!
