### ISSUE TITLE
1.17.1: chc announce multiline support

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#1876]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true/
I use `/chc announce chat 1test /n 2test`,
`/chc announce chat 1test \n 2test`
Neither can wrap the bulletin content.
Be sure to hit more than display will wrap.

![image](https://user-images.githubusercontent.com/52900334/166263935-8511209c-b94a-4fd0-b3eb-b5dacc861660.png)

**Comment by ElBananaa** [comment]
Hey, this is already possible using `/chc announce chat Line1|Line2|Line3|Line4` etc..
