### ISSUE TITLE
1.18.2: Admin Chat Passthrough (Bungee)

### ISSUE THREAD

**Issue by ItWasEnder** [kangarko/ChatControl#1877]
Hello! I was playing around with chc-red and I was wondering how I can passthrough admin chat to other admins on the network but not pass through any other chats. I used to do this with the original ChatControl but have no idea how to accomplish this again. Any help would be greatly appreciated.

Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true?

**Comment by kangarko** [comment]
Hi there!

Thanks for your question. You can simply create "admin" channel and then write Bungee: true option to its settings: https://github.com/kangarko/ChatControl-Red/wiki/Channels

![a](https://i.imgur.com/nxswmaM.png)

Make sure to enable Integrations.BungeeCord and install BungeeControl on Bungee also

**Comment by TheIntolerant** [comment]
Just to reiterate the importance, please make sure to read https://github.com/kangarko/ChatControl-Red/wiki/Channels as this will help speed up the process of making channels and help with the permission setup etc
