### ISSUE TITLE
Not capitalizing or putting a period and im owner of my server but works for all other staff

### ISSUE THREAD

**Issue by MinecraftMarcus1** [kangarko/ChatControl#188]
I would like to know how do I set it so the plugin lets my staff like moderators access to commands like gamemode creative and commands like that? I also have an issue with it not capitalizing or punctuating my own chat and im the owner of the server

**Comment by kangarko** [comment]
Hey,

please review rules/command.txt file for default rules that also involve gamemode.

as a server owner you have bypass permission. You need to give yourself negative permission:

"-chatcontrol.bypass.punctuate"
"-chatcontrol.bypass.capitalize"
