### ISSUE TITLE
1.18.2: Changing "/ch j global" to just "/ch global" 

### ISSUE THREAD

**Issue by DawnguardAlpha** [kangarko/ChatControl#1881]
I am looking for a way to edit/shorten the command for joining/switching your channel to just /ch [channel] as opposed to including "j" for join. It seems other servers have the ability to do this, I'm just not sure where to begin.

Thanks.

Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Why not just to /global? You can create any command you'd like using our guide: https://github.com/kangarko/ChatControl-Red/wiki/Custom-Commands
