### ISSUE TITLE
Join/quit and death messages logged by default.

### ISSUE THREAD

**Issue by angwdev** [kangarko/ChatControl#1882]
Join an quit .rs messages and death messages doesn't log by default, doing this can be beneficial for newcomers. Logging is a extremely important feature for unforeseen events. And is a must security feature.

**Comment by ElBananaa** [comment]
Hey,
You can use the `then log` operator (https://github.com/kangarko/ChatControl-Red/wiki/Rules#then-log) under each rule to log specific messages to the console.
You can also use the `then write` operator (https://github.com/kangarko/ChatControl-Red/wiki/Rules#then-write) to log messages to external files.

**Comment by angwdev** [comment]
I mean by default. In first install. But all these messages are disabled by default anyway.

**Comment by kangarko** [comment]
Thanks, I understand your concerns but we prefer not to do it by default, you can always use "then log" operator.
