### ISSUE TITLE
Chat Control functions.

### ISSUE THREAD

**Issue by LordYarkan** [kangarko/ChatControl#1883]
Hi
1- How can I block Unicode Symbols in the rules of Anvil.rs .. etc?
2- How to use Chatcontrol without using Channel?
I await your response, thank you.

ChatControl-Red-10.10.4
Minecraft Version: paper-1.16.5-788
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Hi!

Please see chat.rs rule for blocking unicode, you can just copy the filter from there into your anvil.rs file.

Regarding not using channels, see https://github.com/kangarko/ChatControl-Red/wiki/Channels#not-having-channels-and-only-having-1-chat-classic-system

**Comment by LordYarkan** [comment]
Another question, I just limited the names of the weapons that are used in the anvil and a problem occurs. 
Anvil.rs
match .{20,}
This happens to BEDROCK players my server has Geyser. In java there is no problem it works fine when using the anvil.
The BEDROCK player tells me that he deletes the name of the weapon on the anvil so he can enchant them.

**Comment by kangarko** [comment]
Sorry but it doesn't look like an issue on our end, you need to adjust your filter so that item names are not empty/null otherwise it won't work due to vanilla limitations.
