### ISSUE TITLE
1.8.8: SQL injection from chat message

### ISSUE THREAD

**Issue by W0lfyZRex** [kangarko/ChatControl#1884]
When someone types an apostrophe in any chat message/private message, an error gets thrown saying that the sql syntax is incorrect because the apostrophe ended up closing the string, messing things up.

Note: this didn't happen until I updated the plugin because of another issue involving inventory clicks.

[Debug File](https://github.com/kangarko/ChatControl-Red/files/8653718/debug.zip)

![image](https://user-images.githubusercontent.com/66094336/167460736-14751865-fa77-4e9b-8c7a-ed61f40500ad.png)

Minecraft Version: 1.8.8
MySQL: true (MariaDB)
BungeeCord: true

**Comment by W0lfyZRex** [comment]
Oh, just noticed it's a duplicate of #1879, I'll close this then.

**Comment by kangarko** [comment]
Investigating, thank you.
