### ISSUE TITLE
Allows Player to send PM to someone who turned off their PM

### ISSUE THREAD

**Issue by nivcoo** [kangarko/ChatControl#1886]
Hello, my suggestion is to be able to reply someone when he started the conversation and when he toggle off his PM. Example :

I do /toggle PM.

No one can PM me.

But if i do /msg Player, this player can /r ou /msg me because i've started the conversation first.

**Comment by kangarko** [comment]
Hey!

Thanks but that's intended.

**Comment by ElBananaa** [comment]
Hey,
I'll try to work on implementing a toggle for this feature (like the bi-directional ignore toggle) but can't make any promises.
This may take a while tho since this isn't a priority at all for us and as I don't have that much free time.

Keep an eye on update logs.

**Comment by kangarko** [comment]
@ElBananaa I appreciate it, but that's not needed right now and will just add code bloat. Let's keep it simple, we already have a large enough codebase

**Comment by ElBananaa** [comment]
Alright, gotcha.
