### ISSUE TITLE
1.18.2: BungeeControl-Red - join/switch messages don't work but quit does?

### ISSUE THREAD

**Issue by c11network** [kangarko/ChatControl#1887]
Minecraft Version: 1.18.2
MySQL: false (for now)
BungeeCord: true

Issue:
I have enabled join, quit, and switch messages but only quit messages display.

Steps to try and resolve the issue:
1. Made sure everything was up-to-date and deleted BungeeControl-Red plugins folder so that it could regenerate.
2. Searched through the issues and found this post replacing the messages in join|quit|switch.rs:https://github.com/kangarko/ChatControl-Red/issues/1520
3. Enabled [player-message] debug option after above didn't work to resolve things.  Found in: https://github.com/kangarko/ChatControl-Red/issues/1464

The quit message does show the message but the rest (which I just copied and pasted then changed the action to so that there could be no formatting issue)  does not work and I don't understand what I'm doing wrong.

Full proxy latest.log + BungeeControl-Red settings & messages:
https://pastebin.com/3kdsEjLG

**Comment by kangarko** [comment]
I have made it to postpone the join message by 1 tick which seems to do the trick, let me know if you still face these issues in the next release.

**Comment by c11network** [comment]
Hey there, still having the issue after updating.
[BungeeControl-Red.zip](https://github.com/kangarko/ChatControl-Red/files/8693662/BungeeControl-Red.zip)

**Comment by kangarko** [comment]
let's continue on https://github.com/kangarko/ChatControl-Red/issues/1890

**Comment by c11network** [comment]
Sorry for reopening/continuing on this issue but I didn't know if the issue mentioned above was fixed after the update.
I have updated to the latest and still same results.
Nothing has been changed in the configs just plugin jars updated.
Is there any other debug flags I can give it to see what all is being processed/triggered?
