### ISSUE TITLE
Paper 1.18.2: Why do suddenly purchased resources require a subscription to use??

### ISSUE THREAD

**Issue by twseer67875** [kangarko/ChatControl#1895]
![image](https://user-images.githubusercontent.com/70073452/168549267-c46a2bf6-6980-4a61-a64b-c9b280989fcf.png)

![image](https://user-images.githubusercontent.com/70073452/168549344-ee1ad2ec-d156-4880-9543-9a48729abb2b.png)

![image](https://user-images.githubusercontent.com/70073452/168549591-c19a7ebf-87c7-4c1f-9581-8e558c38492b.png)

Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey,
Please read #1680 and follow what's written there. This is an issue that appeared when mcmarket updated their forums.
Simply follow what's said in the specified issue and wait for kangarko to give you back access to the plugin. (This may take a few days)

**You don't need to pay anything else, you bought the plugin once, you own it for life.**
