### ISSUE TITLE
1.12.2: Issue with MySQL Database with versions 10.11.0 and later on 1.12.2

### ISSUE THREAD

**Issue by starwarsfreak219** [kangarko/ChatControl#1897]
Minecraft Version: 1.12.2 (PaperMC #1620)
MySQL: true
BungeeCord: false

Hello, so I recently been having an issue getting ChatControl-Red to the latest version on my Minecraft Server. Unfortunately it appears to completely disable the plugin when MySQL is enabled. Here is what is shown in the error.log: https://paste.helpch.at/kodacupawa.sql

I tried resetting it to a default version (renaming the old ChatControlRed folder to something else and then starting the server). Seems to have worked fine without MySQL, I set up MySQL how I have had it set up in the previous configuration (which worked with older versions), got the same issue. Here is what it shows in the console as well: https://paste.helpch.at/xexanijodo.sql (NOTE: I changed the IP address to x.x.x.x in the paste just to keep that information confidential).

Thanks in advance! ☺

**Comment by ElBananaa** [comment]
Hey,
I am completely unable to reproduce your issue under both java 8 & java 18 (Paper 1.12.2 b1620).
When using java 8, the plugin downloads the required libraries (thanks to the legacy-libraries feature) and database connection is properly established.
When using java 16, as the plugin can't use the legacy-libraries feature, it is unable to download the mysql driver, so instead it'll use the one provided in spigot, and still, database connection is properly established.

Java 18: https://paste.gg/p/anonymous/d7320763e1b54ab7a4e986a9c3d2eaa9
Java 8: https://paste.gg/p/anonymous/551c8b3e58dc4a12ac9f88ae7ea0b243

Please try to use Java 8, and let us know if it changes anything

**Comment by starwarsfreak219** [comment]
Unfortunately, I cannot use Java 8 as certain plugins will not work with Java 8 (DeluxeMenus being the main issue). Is there anything that would cause this issue? It didn't start happening until the 10.11.0 update...

**Comment by starwarsfreak219** [comment]
Currently using Java 11.

**Comment by ElBananaa** [comment]
Honestly I don't see any reason why this would happen except an issue with java 11.
I will run tests with java 11 too to see if i'm able to reproduce your issue and i'll keep you updated.
@kangarko Got any other idea about what's happening here?

**Comment by ElBananaa** [comment]
Getting back on this, I just finished running tests with java 11, and still, i'm completely unable to reproduce your issue, so there's definitely something wrong, however seems like it's something on your end. 

- First of all, try to download the latest version again to see if that helps (i'm pretty sure i've already seen similar issues which were fixed like that).

- If it doesn't work, please try to reproduce your issue on a test server with only chatcontrol and its dependencies installed?
If it works fine, then simply add your plugins one by one to make sure it's not caused by another plugin somehow conflicting with chatcontrol.

**Comment by kangarko** [comment]
I will include a fix to resort back to the legacy MySQL driver in case Hikari is used. Or worst case you will need to stop using MySQL if you can't downgrade to Java 8, but I will try to resolve your issue as much as I can. Let me know the outcome in the next release.

**Comment by ElBananaa** [comment]
@kangarko I did run a few tests on my end, and it appears the `legacy-libraries` feature actually works above Java 8 (Tested on Java 11, 14 and 8), so another solution would be to actually make it work from Java 8 to Java 14, as this will allow users to benefit from updated drivers.
The only problem (which isn't really one), is that the first time you'll use the plugin, it'll show an `Illegal Reflective Access` warning.

**Comment by kangarko** [comment]
It cannot work because we have a code exception for Java 9+: https://i.imgur.com/cr7wxzn.png

The reason being is that they have removed the method we use to load that library on that java version(s)

**Comment by ElBananaa** [comment]
> It cannot work because we have a code exception for Java 9+: https://i.imgur.com/cr7wxzn.png
> 
> The reason being is that they have removed the method we use to load that library on that java version(s)

I know, what I'm telling you is that I did run tests on my end, as I raised the version requirement up to java 14, and it worked perfectly fine.

**Comment by ElBananaa** [comment]
@kangarko Here's the full log: https://paste.gg/p/anonymous/3d75bd7945654efdb3b1cba1cb4546d1
(Using Java 11)

**Comment by kangarko** [comment]
Interesting thank you!

**Comment by kangarko** [comment]
Sorry for the delay @starwarsfreak219, it should be resolved in the next release.

**Comment by starwarsfreak219** [comment]
Hmm, still seem to be getting an issue with the recent release (10.11.5)... Here is what is shown in the console log for CHC-RED: https://paste.helpch.at/gujisowiki.md

**Comment by kangarko** [comment]
It no longer looks like a problem with our driver, rather it simply says your credentials were invalid or something else is blocking the connection, check in with your hosting please.

**Comment by starwarsfreak219** [comment]
Just tested it again (I had to reset my panel due to an issue with an update to it). Looks like it is working as expected now. Thanks! ☺
