### ISSUE TITLE
Do not send empty chat messages

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1898]
Rather than denying whole messages with matched words in it (swears, etc), I strip the them. But this also has a little side effect.
If the only thing the user types is the matched word, the word gets stripped, resulting the message to be basically null.
But the problem is, that the messages is sent anyways and it looks like this:
![image](https://user-images.githubusercontent.com/87967222/169307250-130ad48d-eab9-47a1-8e46-017b2ce05f13.png)
![image](https://user-images.githubusercontent.com/87967222/169308145-0a53e262-04f6-4c99-9448-fa9af0e6cf72.png)

That's why I suggest that if the message is null, chatcontrol will ignore it, rather than sending it without any text.

**Comment by kangarko** [comment]
Thanks, I will fix that.
