### ISSUE TITLE
1.8.8 | Server on windows working incorrectly

### ISSUE THREAD

**Issue by tomet123** [kangarko/ChatControl#19]
Java:
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

Plugin version: 10.0.1

OS: Windows 10 Pro 2004

Some texts are broken.

[latest.log](https://github.com/kangarko/ChatControl-Red/files/5524192/latest.log)

**Comment by kangarko** [comment]
Woah that's a big error

How to reproduce please? If unsure you can just ZIP me your whole server with all jars and I'll remove it soonest I see it

**Comment by tomet123** [comment]
I dont know how i create this error. I prepare clean server on windows same as on my linux workstation where working fine. Here is complete server - https://drive.google.com/file/d/1BA0aHi-6KREHBiX_fTEfRAHeWbs-dRCs/view?usp=sharing . There is not any sensitive data only clean server.

**Comment by kangarko** [comment]
Thank you I'll fix that in a few hours!
