### ISSUE TITLE
ChatControl filters apply to OP players?

### ISSUE THREAD

**Issue by adopted3** [kangarko/ChatControl#19]
Hello,

How can I make the ChatControl rules/filters also affect players who are OP'd?

Is there a certain permission I need to remove from them?

Thanks!

**Comment by adopted3** [comment]
I revoked the chatcontrol.bypass.rules permission from the group the OP's belong to, and I even set the default to "false" in permissions.yml, but it didn't help. Maybe permissions don't apply to OP players, although I think the "default: false" instead of "default: op" should do the trick?

**Comment by kangarko** [comment]
I have set **Op_Has_Permissions** to false in **settings.yml** and rules were applied to operators, too.

Make sure they don't have any * permission, for example from PermissionsEx.

**Comment by adopted3** [comment]
Thank you, that fixed it. :-)
