### ISSUE TITLE
Suggestion: Tab-complete blocking by group

### ISSUE THREAD

**Issue by CypherPhyre** [kangarko/ChatControl#190]
I would like to suggest an enhancement to the tab-complete blocking. Add a file section that can be linked to groups via permission
"chatcontrol.tabcomplete.group.<group>". This would allow owners/devs to set up what commands they want tab completed by groups instead of having only 1 black/whitelist or general bypass. This can replace the need for plugin/command hiding plugins needed after 1.13.

CypherPhyre#6126 Tester: 1.16-mysql

**Comment by kangarko** [comment]
Thank you for your suggestion!

**Comment by CypherPhyre** [comment]
Would you consider adding this or is it off the table? I personally am looking to replace the plugin (pl-hide) I am currently using for this. I understand it is not a top-priority item. I just feel that it would be beneficial since you already have the key components "groups" and "tab-complete white/blacklist" built-in.

**Comment by kangarko** [comment]
Not right now, I am a one-man dev for all 5 plugins so my time is pretty limited, however, you can temporary give chatcontrol.bypass.tabcomplete permissions to trusted players and let them tab complete everything.
