### ISSUE TITLE
1.18.2: CCR ignores canceled chat events

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1901]
```
        @EventHandler(priority = EventPriority.LOWEST)
	public void onPlayerChat(AsyncChatEvent e) {
		var player = e.getPlayer();
		var plainSerializer = PlainTextComponentSerializer.plainText();
		var message = plainSerializer.serialize(e.message());
		if (message.charAt(0) == ';') {
			e.setCancelled(true);
			Bukkit.getScheduler().callSyncMethod(plugin, () -> player.performCommand("clan chat "+message.substring(1)));
		}
	}
```
Suppose I have this event listener. In both LOWEST and HIGHEST listener priorities any messages starting with `;` are still formatted and displayed in Chat Control Red while should be canceled. This results into messages displayed both in CCR and my old clans plugin.

Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey,
Did you try to play with ChatControl's listener priority?
Also, may I ask you why didn't you use `if (message.startsWith(";")) {` instead of `if (message.charAt(0) == ';') {`?

**Comment by radiant-ai** [comment]
> Hey, Did you try to play with ChatControl's listener priority? Also, may I ask you why didn't you use `if (message.startsWith(";")) {` instead of `if (message.charAt(0) == ';') {`?

This is a legacy plugin that I wrote when I was not that good at Java. The problem here is probably that chatcontrol has no idea about this event as it is quite new, I switched to it because the previous one was deprecated. And can playing with priorities really change anything if I already tried to play with them in my plugin?

**Comment by ElBananaa** [comment]
> > Hey, Did you try to play with ChatControl's listener priority? Also, may I ask you why didn't you use `if (message.startsWith(";")) {` instead of `if (message.charAt(0) == ';') {`?
> 
> This is a legacy plugin that I wrote when I was not that good at Java. The problem here is probably that chatcontrol has no idea about this event as it is quite new, I switched to it because the previous one was deprecated. And can playing with priorities really change anything if I already tried to play with them in my plugin?

I'd still suggest to give it a shot, who knows, hopefully it can help a bit.

As for the event you call it doesn't look specifically recent, but it's an event that can only be found in paper. Could you try to reproduce your issue with spigot's `AsyncPlayerChatEvent` to see if it changes anything?

**Comment by radiant-ai** [comment]
I cannot use the older event because it uses legacy formatting and I shift
to the Adventure Api. Though the older event is canceled properly. I think
CCR can fix this by calling the Papers new event in the older one in code
and see if it is cancelled, and if it is cancelled, cancel the older one.

For now I fixed the issue with specifiing the rule in chat.rs to cancel
messages starting with `;`. And in future I may shift my plugin fully to
support CCR Api party system.

For now it is more like a heads up that this event is likely not properly
handled by the CCR.

**Comment by ElBananaa** [comment]
Well, the issue is that if we rely on paper's event, spigot users will encounter issues. And Chatcontrol/Foundation do not support Adventure at all (at least for now) unfortunately, even tho, imo this would definitely be a huge improvement.

Let's just wait for Kangarko to see if there's any other solutions I guess ^^

**Comment by radiant-ai** [comment]
You won't rely on paper event, you just create papers event in older
listener and call it, then you wait for result and if it is cancelled, that
means that there is a plugin using paper chat event :)

This is very similar to like many plugins can integrate into any protection
plugins:
create block break event and call it on behalf of player, if it is
cancelled, this means that there is some protection going on at the
location.

**Comment by kangarko** [comment]
I have no idea about AsyncChatEvent and we do not listen to that. Since Minecraft 1.3.2 there's AsyncPlayerChatEvent which you should listen to instead of we'll ignore it properly in case you adjust our priorities to come after yours.

**Comment by radiant-ai** [comment]
But the even you suggest is deprecated

**Comment by kangarko** [comment]
AsyncPlayerChatEvent is not deprecated if you use Spigot or Paper, I am not supporting anything else for time reasons at the moment.

**Comment by radiant-ai** [comment]
https://jd.papermc.io/paper/1.18/org/bukkit/event/player/AsyncPlayerChatEvent.html

**Comment by ElBananaa** [comment]
@radiant-ai AsyncPlayerChatEvent event is only deprecated on paper since they use their own event, AsyncChatEvent. The problem is AsyncChatEvent is only supported by paper and its forks (which means replacing spigot's event with paper's one will break the plugin for all users using spigot), and AsyncChatEvent requires us to support Adventure, which is not the case for now. While I do agree supporting adventure would be a huge plus for the plugin, it would also require an important rewrite of most parts of the plugin and the library kangarko uses.

Here's spigot's javadocs for the event. As you can see it is not deprecated https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/AsyncPlayerChatEvent.html
