### ISSUE TITLE
1.18.2: How does {player_afk} work on BungeeControl?

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1902]
Hello, so the variable ``{player_afk}`` is a BungeeControl Red Variable, and therefore I was hoping to use it to hide switch messages (from non-staff) if a player is kicked for AFK (using EssentialsX) from say the survival server and sent to the hub server. However, everything I have tried doesn't seem to work.

The variable seems to always return "false" even if a user gets kicked for being AFK by EssentialX.

Here is a simplified example I tried to test ``{player_afk}`` but it still didn't seem to work.
```rust
group afk_kick
require sender script "{player_afk}" == "true"
require receiver perm message.see.afkkick
prefix &8[&d>&8]
message:
- &e{player} &fgot AFK kicked &8(&7{from_server} &fto &7{to_server}&8)


group main_message
require sender script "{player_afk}" == "false"
prefix &8[&d>&8]
message:
- &e{player} &fhas switched from &7{from_server} &fto &7{to_server}
```

It seems like ``{player_afk}`` isn't working for EssentialsX?

What ends up happening with the above setup, is that the ``group main_message`` is always sent even when EssentialsX kicks a user for being afk. So any extra infomation on how ``{player_afk}`` works would be great! Thanks

Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Thanks and sorry for the delay, the messages are stored in a cache and we wait for the server to confirm the response, during which time the afk status gets changed. So I simply saved variables from the current server from where player is switching and it should work. Not sure what implications this will have for vanish status etc., in case the user aims to disable vanish on the second server, we will still report it as true now

**Comment by TheIntolerant** [comment]
It seems its still broken in the latest version sadly.

**Comment by kangarko** [comment]
I am sorry, this is also something I will take after June 21st

**Comment by kangarko** [comment]
I unfortunately don't have time time I wished I had to implement this, I have to postpone it until further notice, I apologies.
