### ISSUE TITLE
1.18.2: Localization bug with variables

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1903]
**Note** Tested on a fresh install.

It seems some variables aren't parsed correctly depending on what caused part of the local to be displayed. In my case triggering the anti-spam via chatcontrol rule causes this to happen.

The rule used here is ``/adminchat <message>`` and part of the local file that was edited was ``Checker.Similarity`` to include ``&8{chat_line_smooth}`` in the message.

The debug file with these changes has been provided below.

---

### Steps to reproduce using the debug file below.
1) talk in chat normally with the same message 2 times to trigger the anti-spam. You will see the normal output here.
![image](https://user-images.githubusercontent.com/48093184/169697842-923e60bc-b7e0-4e70-b96c-6fda1d9b02c6.png)

2) Talk in the admin channel via chatcontrol rules ``/adminchat <message>`` with the same message 2 times to trigger the anti-spam. Here you will see the variables used aren't parsed correctly.
![image](https://user-images.githubusercontent.com/48093184/169697973-f70e8248-a486-4ff8-9673-cd5335bd0949.png)

---

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8749539/debug.zip)

Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Thanks, the command was not replacing inbuilt variables so my fix also resolved many other localization keys. Fixed.
