### ISSUE TITLE
1.18.2 Problem with parameter localization in the message

### ISSUE THREAD

**Issue by Sakishima** [kangarko/ChatControl#1904]
Hello!
I have a problem with the translation param in messages.yml file. The "mute" section has a "Mute_Success" param with the following text: "The {type}", where "{type}" can be the word server/channel/player. But how can I translate this word "{type}"? All params in the message.yml file don't have a translation of this "{type}".
Help me please.

Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey,
You cannot translate the `{type}` variable yet.
I just changed this https://github.com/kangarko/ChatControl-Red-Src/pull/31

The changes will hopefully be available in the next release.
