### ISSUE TITLE
1.18.2: Links are no longer clickable

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1905]
## Bug Information

It seems in one of the recent updates of chatcontrol, plain url links in chat, formats etc can no longer be clicked, however this worked in prevoius versions of the plugin.

This was tested with Zero plugins and i tested each time I added these plugins "Vault", "luckperms" and "ProtocolLib" all of which worked and I was able to click on links in chat, till adding ChatControl-Red onto the server.

Zero changes were made to the configs of any of the plugins mentioned (including chatcontrol) in my testing, thus I assumed providing a debug file wasn't needed.

### Extra notes

This seems to be related to chatcontrol-red itself and not any dependancy as I tested clicking on links sent in chat etc after installing each plugin, it was only till I installed chatcontrol-red it stopped working.

It should also be noted, this effect can be seen regardless if the channel feature is enabled etc
(As I have the issue on my own network which uses channels etc)

Even if you have the default config unchanged from install, clicking links sent in chat becomes impossible.

---

### Steps to reproduce:

1) Say "http://www.google.com" in chat without chatcontrol-red installed, you should be able to click on the link

2) Repeat step 1 but install chatcontrol-red onto the server and the link will no longer be clickable.

---

### Server Environment Information
```
Plugin: ChatControlRed v10.11.4
Server Version: Paper v1_18_R2
Java: 17.0.1 (Oracle Corporation/Private Build)
OS: Linux 5.13.0-21-generic
Online mode: true
Players Online: 1
Plugins: LuckPerms v5.4.25, Vault v1.7.3-b131, ProtocolLib v4.8.0, ChatControlRed v10.11.4
BungeeCord: null
MySQL: false
```
```
Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false
```

**Comment by ElBananaa** [comment]
This may be related to the changes I made in a previous version (10.11.1 I believe).
I'll have a look at it later today (if kangarko doesn't  before I do ^^)

**Comment by kangarko** [comment]
@ElBananaa which commit did you make for this change?

**Comment by ElBananaa** [comment]
> @ElBananaa which commit did you make for this change?

I'm not sure, but I believe this issue is related to this PR: https://github.com/kangarko/Foundation/pull/152

**Comment by ElBananaa** [comment]
Fixed in https://github.com/kangarko/Foundation/pull/159

https://streamable.com/55nd20

**Comment by TheIntolerant** [comment]
> Fixed in https://github.com/kangarko/Foundation/pull/159
> 
> 
> 
> https://streamable.com/55nd20

Seeing the change you've made, I have a feeling that could potentially also fix this issue #1816 which was just about how ".online" domains don't work etc.

**Comment by ElBananaa** [comment]
> > Fixed in [kangarko/Foundation#159](https://github.com/kangarko/Foundation/pull/159)
> > https://streamable.com/55nd20
> 
> Seeing the change you've made, I have a feeling that could potentially also fix this issue #1816 which was just about how ".online" domains don't etc.

It actually does fix this issue too, you are right! Thanks for pointing this out.

**Comment by kangarko** [comment]
Closing, thanks so much @ElBananaa for having a look and fixing it!

**Comment by dandyjay** [comment]
wow thanks so much!
