### ISSUE TITLE
1.18.2: MySQL Syntax Error

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#1907]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: false

Updating to the latest version of chat control gives me a SQL syntax error. I am unsure  how to fix this error. **Debug file** found in Email to support@mineacademy.org with same title as this issue.

MySQL Error
https://pastebin.com/ESfwf8X0

**Comment by ElBananaa** [comment]
Hey,
Your error says you are using Chatcontrol 10.11.1.
Latest version available is 10.11.4. Please update to this version.

**Comment by TZ122** [comment]
Hey, i've updated versions  but still running into the same issue ver. 10.11.4 from McMarket

**Comment by ElBananaa** [comment]
> Hey, i've updated versions but still running into the same issue ver. 10.11.4 from McMarket

Can you please provide us the updated error?

**Comment by kangarko** [comment]
You have ' character which we failed to properly escape in our databases in old versions. I recommend you either drop the table completely, losing log history, or find all occurrences of ' and replace them with ''

I apology for the inconvenience.
