### ISSUE TITLE
Suggestion: "ignore channel" operator should also apply when a message is also sent via /ch send <channel>, not just when someone talks normally.

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1908]
### 1. How it would benefit others? (Not just you, but 1,000s of other people using the same plugin.)
This would make it easier for admin/owners to create bypasses for specific rules sent via a specific channel which people can only talk in that channel via command. Such as ``/adminchat <message>``.

I personally prefer to use a third-party plugin to create custom commands, as I am able to manage tab completion etc with the one plugin. For example, with my admin channel, I created ``/adminchat <message>``
which makes them use ``/ch send admin <message>`` similar to how commands.yml works. The problem with this is there is no easy way of allowing ``/ch send admin`` to bypass specific rules like my advertisement rules etc. in my admin channel. While I could use ``ignore command`` this can only be done on the main label of the command meaning you can only do ``ignore command /ch|/channel`` which unfortunately means regular players could use /ch send <whatever channel> to bypass the rules.

Since the plugin allows ``/ch send`` as another way of talking to a specific channel, it would make sense to make it so if someone talks into the channel listed in "ignore channel <channel>, via ``/ch send <channel``, so that the specific rules do not apply to that user. Plus this would make creating bypasses for specific rules in specific channels much easier!

---
### 2. What would happen if we won't implement this feature? How's your server being affected?
Currently, it is possible to make specific rules bypass channels but in order for it to only apply to the specific channel, you need to create a rule for the channel when using an alias (such as /adminchat), which unfortunately means accent markers, color codes, etc are stripped from the messages sent in the channel (since chat control removes those things via rules), which could be an important context for the conversation people are having.

This is why this should be added, especially when people would prefer to use ``commands.yml`` or a third-party plugin to create command aliases since they do not want accent markers, color codes, etc getting stripped from a message sent via chat control rule for important channels.

**Comment by TheIntolerant** [comment]
If this suggestion is considered, I might add that this change should also be applied to the operator ``require channel``

Thanks.

**Comment by kangarko** [comment]
Thanks. I am however launching a new training program so I am extremely short on time so I cannot do this at the moment, however I have pulled two of your other suggestions/bug reports ;)

**Comment by TheIntolerant** [comment]
Do you think this would be something that could be added in a later date?

**Comment by kangarko** [comment]
Sure! I can have a look after June 21st when I am back home from holidays :)

**Comment by TheIntolerant** [comment]
Thank you!!

**Comment by kangarko** [comment]
Thanks, I have fixed inconsistencies with "ignore channel" and it should now be applied even for /ch send!

**Comment by TheIntolerant** [comment]
Amazing!! Thank you so much!

**Comment by TheIntolerant** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9078285/debug.zip)
Seems to still block it via /channel send

Tested on a fresh server with minimal plugins, running paper 1.18.2
The only things I changed were part of the swear group to include ``ignore channel admin`` and enabled the channels.

I tested by typing ``/channel send admin fuck`` and despite having ``ignore channel admin`` it still blocks it

**Comment by kangarko** [comment]
I am so sorry, looking at it in 24h

**Comment by kangarko** [comment]
Sorry for half-assed fix, I did not check when I am joined in another channel than the what "ignore channel" is.

Fixed and tested, should be all good now!

![a](https://i.imgur.com/AXQipjL.png)

**Comment by TheIntolerant** [comment]
Thank you! Happy to confirm it is working on my end too.
