### ISSUE TITLE
Format messages with pages

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/ChatControl#1910]
The suggestion that I have is having the possibility to make pages inside the messages that are sent by CHC
So at the bottom of the messages, I get this;
`------------------------------- << - >> -------------------------------`

The ` << ` will then send you a page back and the ` >> ` will send you a page forward.
But not only this would be great but also a possibility to have hover text on that part as well.

This could help other by making a full-on custom help page where you can make a full help page with the pages.

**Comment by ElBananaa** [comment]
To add on this suggestion: This is something that could also be extremely useful for the motd feature in the roadmap!

**Comment by Greazi-Times** [comment]
To add to the part of the hover message.
The possibility of adding hover Tex tot other part of the formats would be great as well.

Not just 1 line total but just a part.

**Comment by kangarko** [comment]
Thank you, I understand your request (hopefully haha) and have pulled it to our road map!

**Comment by Greazi-Times** [comment]
Quick question of there is any time frame when this update will might happen?

**Comment by ElBananaa** [comment]
> Quick question of there is any time frame when this update will might happen?

Unfortunately, no, there is not. I believe Kangarko is currently busy with courses, and other personal things so he's keeping new feature additions to a minimum unless these features are either highly requested, or pretty important overall.
