### ISSUE TITLE
1.18.2: Bungee quit messages not working and throwing an error

### ISSUE THREAD

**Issue by addstar** [kangarko/ChatControl#1911]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

After upgrading to 10.11.4 (from 10.11.0), quit messages are no longer working and this error is in the Bungee logs: https://www.toptal.com/developers/hastebin/iyuyibucoy.properties

Join messages and all other chat/channel related things are working fine.

We did see the message doubling/tripling issue for a short time after upgrading (like in #1890) but after restarting proxy+all servers again it seemed to go away.

**Comment by kangarko** [comment]
Thanks and apology for both bugs, they should be patched in the next version.

**Comment by addstar** [comment]
Thanks @kangarko! Can confirm the problem has been fixed with version 10.11.5 :+1:
