### ISSUE TITLE
[BUG] Unexpected null last damage spam

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1913]
I'm getting spammed by this message.
```[01:02:44] [Craft Scheduler Thread - 154 - ChatControlRed/INFO]: [ChatControlRed] Unexpected null last damage cause for RobotVictorMan, messages not broadcasted. This message appears once per 30 minutes.```
(The name is always different, but the message is the same.)
I have no idea what is causing it, but it has appeared 208 times in console for the past 13 hours and I have no idea what to do to fix it.

**Comment by ElBananaa** [comment]
> I'm getting spammed by this message. `[01:02:44] [Craft Scheduler Thread - 154 - ChatControlRed/INFO]: [ChatControlRed] Unexpected null last damage cause for RobotVictorMan, messages not broadcasted. This message appears once per 30 minutes.` (The name is always different, but the message is the same.) I have no idea what is causing it, but it has appeared 208 times in console for the past 13 hours and I have no idea what to do to fix it.

Hey,
This isn't a bug, as the message itself says, this message is sent when a player is killed with no apparent reason.
This can be caused by a lot of different reasons, but most likely by plugins like combat loggers not properly defining a death cause when a player leaves the server in combat.

**Comment by kangarko** [comment]
Thanks, I have reduced the spam to once per 24 hours, and added additional explainer to the message as per Banana's suggestions
