### ISSUE TITLE
[BUG] Cannot match & in color codes

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1916]
It is impossible to match & character in color codes in rules.

For example, matching `&` in `&g` works, but in `&l` doesnt.

**Comment by ElBananaa** [comment]
> It is impossible to match & character in color codes in rules.
> 
> For example, matching `&` in `&g` works, but in `&l` doesnt.

I'm not sure to fully understand your issue. Can you send us the rule that's not working?

**Comment by Teslicek** [comment]
> I'm not sure to fully understand your issue. Can you send us the rule that's not working?

For example in anvil.rs, lets try to match that if the user types `&` in anvil, it will not let the user to rename the item.
```
match &
then warn &cYou cannot use & character in anvil!
then deny
```
So for this test, I tried to rename item A to `&lTEST` and item B to `&gTEST`.
The result from this test was, that I was able to rename item A, but not item B, because & character in item B is not in a color code.

The problem is that it shouldn't allow me to even use any type of &, even if it's a color code.

**Comment by ElBananaa** [comment]
> match &

Try
`match &[a-zA-Z-0-9]` this should solve your issue.

**Comment by Teslicek** [comment]
Nope, didnt work, as I already said, it doesn't affect anything related to a color code.

**Comment by ElBananaa** [comment]
Interesting, it appears setting `Rules.Strip_Colors: false` solves the issue.
Looks like colors should already be stripped when using `Rules.Strip_Colors: true` but they're not for a reason I ignore.

I'll try to have a look at it in the next few days.


@kangarko Correct me if I'm wrong

**Comment by kangarko** [comment]
You need to have Rules.Strip_Colors set to false for this to work otherwise we stripe them before the matcher.
