### ISSUE TITLE
[10.11.5] Broken hex chatcolor

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1918]
10.11.4:
![image](https://user-images.githubusercontent.com/87967222/170835761-9eab5079-f23b-498a-b575-a26349bd5afe.png)
10.11.5:
![image](https://user-images.githubusercontent.com/87967222/170835780-5e4e02c5-f312-49ff-8461-7540f058d914.png)

After updating to the latest version of ChatControl, the hex is not shown anymore when changing chatcolor.

```Success_Color: '&8[&a&l!&8] &7Set {0} chat color to&7: &f{1}'```

And also, the "s" is still not capitalized, would appreciate if there was any way to do it, because right now its impossible through localization and also the "." is not even in my localization file. (Yes, I'm aware that some weird message merging is applied here).

**Comment by ElBananaa** [comment]
I'm going to have a look at the color issue asap.
As for the 2nd issue, I believe Kangarko said there isn't much he can do rn. @kangarko

**Comment by ElBananaa** [comment]
Alright,
This has been fixed in https://github.com/kangarko/Foundation/pull/160.
I'm closing this issue as it appears kangarko already answered you in #1909.

@kangarko Got anything to add?

**Comment by kangarko** [comment]
Thanks! The merge will remain as this is one of the workaround solutions we found, I am open minded to a better fix. Or worst case, we just create two localization keys instead of one. That will be after my arrival from holidays after June 21st, please remind me.
