### ISSUE TITLE
Tab complete for @ SoundNotify configuration

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#1919]
Hey, so one major pain is having to write the full name of a player after @ (or whatever configured tag) in order to mention them with the SoundNotify config feature. 

This reduces the frequency with which this great feature is used by players, it would be hugely useful if player names started showing up after typing @, being completable by some initials and pressing tab, just like commands.

Has this feature been added yet? If it has, I'd like to know the new config, If not, I'd like to suggest it. Thanks!

**Comment by ElBananaa** [comment]
Hey! Unfortunately, no this isn't a feature, so, unless you choose to use the Sound_Notify feature without a prefix, you can't tabcomplete names. I believe this is a limitation of how the current system works.

**Comment by MuriloWentz** [comment]
i would tabcomplete the name, then use the left-arrow key to go back and add the @

**Comment by MithrandirCraft** [comment]
Without having looked at this in much detail, I would say this could be coded. Am I mistaken?

**Comment by kangarko** [comment]
Thanks! I haven't looked code-wise if that can be accomplished, probably in some hacky ways by inserting all player names with @ before them which would lead to other issues. I don't have time for this right now, I may return to this after my holidays end at June 21st.
