### ISSUE TITLE
Smileys

### ISSUE THREAD

**Issue by FrankHeijden** [kangarko/ChatControl#192]
Heya,
is there a way to disable those automatic-smileys in the chat? I dont knwo where to find it in the config.

-Frank

**Comment by kangarko** [comment]
Hello,

you can remove rules you do not wish to use, in this case those are found in rules/chat.txt

**Comment by FrankHeijden** [comment]
I have also got a question about herochat compatibilty, because i cant access herochats ingame commands anymore with chatcontrol enabled. Maybe a feature request to hook in with herochat's channels?

**Comment by kangarko** [comment]
Hey, please see this Wikipedia article and try to change the Listener priority:
https://github.com/kangarko/ChatControl/wiki/Pro-Information#common-pro-issues

**Comment by FrankHeijden** [comment]
changed it, but now getting error:

27.03 21:26:25 [Server] WARN ... 21 more
27.03 21:26:25 [Server] WARN at nul.final...\\...........aux.lpT6$throw$protected.init(SourceFile:252)
27.03 21:26:25 [Server] WARN at nul.final...\\...........aux.lpT6.class(SourceFile:28)
27.03 21:26:25 [Server] WARN at nul.final...\\...........aux.AUX.LpT2(SourceFile:202)
27.03 21:26:25 [Server] WARN at nul.final...\\...........aux.AUX.protected(SourceFile:179)
27.03 21:26:25 [Server] WARN at nul.final...\\...........aux.AUX.protected(SourceFile:340)
27.03 21:26:25 [Server] WARN at nul.final...\\...........aux.AUX.protected(SourceFile:348)
27.03 21:26:25 [Server] WARN Caused by: java.lang.RuntimeException: Malformed configuration! Key 'Anti_Spam.Commands.Delay_Between_Commands' in settings.yml must be Integer but got Double: '0.5'
27.03 21:26:25 [Server] WARN at java.lang.Thread.run(Unknown Source)
27.03 21:26:25 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603)
27.03 21:26:25 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276)
27.03 21:26:25 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336)
27.03 21:26:25 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398)
27.03 21:26:25 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437)
27.03 21:26:25 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328)
27.03 21:26:25 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378)
27.03 21:26:25 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
27.03 21:26:25 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
27.03 21:26:25 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
27.03 21:26:25 [Server] WARN at nul.final...\\...........aux.Aux.onEnable(SourceFile:61)
27.03 21:26:25 [Server] WARN at nul.final...\\...........aux.AUX.protected(SourceFile:56)
27.03 21:26:25 [Server] WARN at nul.final...\\...........aux.lpT6.protected(SourceFile:54)
27.03 21:26:25 [Server] WARN at nul.final...\\...........aux.AUX.cOm2(SourceFile:93)
27.03 21:26:25 [Server] WARN at nul.final...\\...........aux.AUX.super(SourceFile:108)
27.03 21:26:25 [Server] WARN at nul.final...\\...........aux.AUX.protected(SourceFile:128)
27.03 21:26:25 [Server] WARN at java.lang.reflect.Method.invoke(Unknown Source)
27.03 21:26:25 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
27.03 21:26:25 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
27.03 21:26:25 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
27.03 21:26:25 [Server] WARN java.lang.reflect.InvocationTargetException
27.03 21:26:24 [Server] INFO Connecting to MySQL database...
27.03 21:26:24 [Server] INFO Configuration loads..
27.03 21:26:24 [Server] INFO \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
27.03 21:26:24 [Server] INFO | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
27.03 21:26:24 [Server] INFO | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
27.03 21:26:24 [Server] INFO | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
27.03 21:26:24 [Server] INFO / ____| |         | |  / ____|          | |           | |
27.03 21:26:24 [Server] INFO _____ _           _    _____            _             _  +
27.03 21:26:24 [Server] INFO [ChatControl] Enabling ChatControl v7.2.9

**Comment by kangarko** [comment]
This error is not related to it at all. The value in your settings.yml at Anti_Spam.Commands.Delay_Between_Commands must be a whole number: 1, 2, 3, ... not a double like 0.5

**Comment by FrankHeijden** [comment]
Oh, didn't know that. I have now set it to 1.
