### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#1920]
Minecraft Version: 1.18.2
MySQL: true
velocity: true 

I use EcoEnchants and MMOITEM to make equipment and give magic.
But when I use [item], I can't format and display the enchantment, it won't display the enchantment of EcoEnchants, only the original version, but I can display it through the chat function of cmi, I don't know how to change it. CHC and CMI chat format processing cannot be enabled at the same time.

**Comment by kangarko** [comment]
Sorry, this is simply unsupported since we only reach out to vanilla minecraft for that information, and not to any external plugins.

**Comment by BearLeonLight** [comment]
> Sorry, this is simply unsupported since we only reach out to vanilla minecraft for that information, and not to any external plugins.

Is there no way to call `CMI` API to display?

**Comment by kangarko** [comment]
I recommend then using CMI to format your chat, I am sorry I don't have enough time to create a custom integration right now.
