### ISSUE TITLE
1.16.5: apostrophe uses config in variables

### ISSUE THREAD

**Issue by SinonCute** [kangarko/ChatControl#1922]
![image](https://user-images.githubusercontent.com/81401485/170895951-d2ee58ce-e749-4c77-9ca4-d25f4cf3e6e6.png)

the apostrophe using configuration in variables does not work correctly, it fails when the return data of variables contains a '

Minecraft Version: 10.11.5
MySQL: tfalse
BungeeCord: false

**Comment by TheIntolerant** [comment]
Have you tried this 
```
"'siro_dot" != "'"
```

**Comment by SinonCute** [comment]
siro_dot' is a data return of a variable

**Comment by TheIntolerant** [comment]
> siro_dot' is a data return of a variable

My apologies, I should of explained myself better, anyhow, did using double quotation marks the variable work? What is your setup for this?

**Comment by kangarko** [comment]
You can use 'siro_dot\'' or double quotes and it should load normally, thank you.

**Comment by SinonCute** [comment]
![image](https://user-images.githubusercontent.com/81401485/171555621-77cf29c7-a2d0-4059-8e3c-0cc961bcd8ec.png)
it still doesn't work please check because this is a very serious error, my log database has been corrupted because of this

**Comment by TheIntolerant** [comment]
> ![image](https://user-images.githubusercontent.com/81401485/171555621-77cf29c7-a2d0-4059-8e3c-0cc961bcd8ec.png)
> 
> it still doesn't work please check because this is a very serious error, my log database has been corrupted because of this

If you are checking that the placeholder does not equal `'` than your condition needs to be as follows
```yml
Sender_condition: "{townyadvanced_towny_postfix}" != "'"
```
