### ISSUE TITLE
1.18.2 Whats this? "Still executing, drink water and DO NOT SHUTDOWN YOUR SERVER"

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#1923]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

Question: what is this? I'm all in for funny messages, but it's not very informative. What exactly is "still executing"?

other sentences:
[ChatControlRed] Still executing, call your friend and DO NOT SHUTDOWN YOUR SERVER.
or
[ChatControlRed] Still executing, keep calm and DO NOT SHUTDOWN YOUR SERVER.
or
[ChatControlRed] Still executing, watch the show and DO NOT SHUTDOWN YOUR SERVER.

**Comment by ElBananaa** [comment]
Hey,
These messages are usually shown when your database is taking some time to gather/send information.
This may be related to #1888.

**Comment by x1p** [comment]
Thank you. Nice to know that it has something to do with databases.

Btw: it started with CHC version 10.11.5

**Comment by kangarko** [comment]
I have edited the message to be more informative, thank you.
