### ISSUE TITLE
Finer control over spy with permission nodes

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#1924]
ChatControlRed offers a _bunch_ of permission nodes that allow you to finely control how chat features operate across ranks on your server. This is obviously good when setting up channels and the like, but I was surprised at how relatively limited the spy permissions were.

Issue #529 brings up the same general concerns, but I would like to add that I do agree with the statement "Spying is a dangerous privilege that should only be granted to staff you trust". However, _for_ that reason, I'm asking for more granular control over the spy system. 

In my pursuit of creating a CHC /softmute command (similar to GriefPrevention's), I've opened a few other issues (#1488 #1580 1522). I finally have the replacement softmute system how I want it (thanks for the help!); Currently, it works by silently moving a player to a special softmute channel with the same formatting as the regular chat channel. So, while softmuted, a player can still read the main chat, but they write into the special softmute channel where only they, and other softmuted players and staff, can read their messages. To anyone except staff, this is undetectable; softmuted players don't have a way to check that they're softmuted, and regular players just don't receive their messages. This is incredibly useful for moderation because it gives staff a chance to determine if a player is trolling without risking an argument or unsavory chat messages being sent in the main chat.

The reason I'm asking for more control over the spy system is because, currently, the only way for staff to read messages sent in the softmute channel (still important for moderation) is by spying into it. Having staff members read into the channel automatically works, technically, but because softmuted messages appear as regular chat in the channel, it's hard to tell who is actually softmuted that way.

![image](https://user-images.githubusercontent.com/43658058/171046765-26a322b1-7b82-40ac-9edc-6c2686dd2c2f.png)
Otherwise (without spying), formatting appears as it normally would, which makes determining softmute status tricky. 
![image](https://user-images.githubusercontent.com/43658058/171046854-b5eb3346-5160-4a1f-9daf-b3015e5c7647.png)

Because the spy permissions are so limited, the only way in which the softmute command could work for all staff is by allowing all staff to spy on _everything_. This is not ideal. I would have liked to allow lower ranking staff (Mod/Helpers) to spy ONLY into the softmute channels (or only spy into channels, failing that), and then allow Admins to spy everything. However, this cannot be done, and so the only other option is to make softmute available only to admins. 

I'm not comfortable with either option, but since we use the softmute channel so regularly, I've had to give full spy permissions to all staff. I don't like this solution, but I also can't risk removing this moderation tool for the staff who rely on it most. I know my situation is a bit unusual, but I doubt I'm the only user who would benefit from more granular spy permissions. Even something like `chatcontrol.command.spy.channels.{channel_name}` mentioned in #529 would be a huge improvement for me. Spy is a dangerous privilege, and for that reason I think additional permissions would help mitigate the issue of giving _full_ spy access to _all_ staff in cases like this.

**Comment by kangarko** [comment]
Thanks, I am closing this and will reopen after June 21st when I am home from holidays.

**Comment by kangarko** [comment]
I am sorry, came from holidays but I am incredibly busy, won't be having time to add this in the near future.

**Comment by BakiDance** [comment]
Understandable, but I hope this will be added in the future. In the meantime, all my support staff have full spy access.
