### ISSUE TITLE
1.8.8: NashornPlus issues with Java 17

### ISSUE THREAD

**Issue by HappyAreaBean** [kangarko/ChatControl#1925]
Minecraft Version: 1.8.8
MySQL: true
BungeeCord: true

I noticed that #1670 has some discussion on this issue, but unfortunately is not the same error as I got.

Error: https://pastes.dev/aLDtmxbY18

**Comment by ElBananaa** [comment]
Hey,
Minecraft 1.8.8 isn't made for java 17, which is most likely the cause of your issue. Did you try with java 8/11 instead?

**Comment by kangarko** [comment]
Sorry such old Minecraft is unsupported with Java 17, use Java 8.
