### ISSUE TITLE
Chat color resetting after rejoinging

### ISSUE THREAD

**Issue by iiMilan** [kangarko/ChatControl#1926]
Hi, 

I'm having an issue where players with the permissions to have white chat color. The color reset after rejoinen. But the Italic style stays after rejoining. I can't seem to find any perm or setting to resolve this issue.

I'm using the latest version of ChatControlRed. (1.18.2) Any fixes?

**Comment by kangarko** [comment]
If the players have the right permission then they should remain. Otherwise check console and look for "TIP Alert: Removing chat" (...) message so you know it was lost, in this case you need to give players the right permission: https://i.imgur.com/fRoVLxM.png
