### ISSUE TITLE
Question | Is it possible to change the display of the messages in /chc log?

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#193]
I know you can change certain aspects of these messages in messages_en.yml, but can you change, for example, the timestamp format or the hover text?  For example, I would like to change what it shows for anvils so I can see the name given to the item without hovering my mouse over the item type.

**Comment by kangarko** [comment]
You can edit Timestamp in settings.yml at the bottom, unfortunately with the just in time compiler editing that exact style becomes problematic. We do have a lot to customize for /chc log, and I look forward adding more in the future!

**Comment by c0wg0d** [comment]
Any update on this?  /chc log still isn't using the timestamp format from settings.yml.

**Comment by kangarko** [comment]
Sorry no this is not using the timestamp from settings right now, I may reopen this later
