### ISSUE TITLE
FactionUUID Coloration Not Working?

### ISSUE THREAD

**Issue by Kashalls** [kangarko/ChatControl#193]
I am attempting to set the faction ally color to the name, however only the name shows but there is no color to the tag. Is this a bug?

**Comment by Kashalls** [comment]
https://i.gyazo.com/61a971713a43c92bda6616a50a1934ad.png

**Comment by kangarko** [comment]
Do you mean the relative color to the player that sees the message? This is not currently possible, but it is on the to-do list.

**Comment by Kashalls** [comment]
Oh nevermind then. Do you have an ETA? Or a workaround?

**Comment by kangarko** [comment]
On pro, probably within two weeks. If you are experienced in Javascript you may create a custom variable there right now. In free, I am sorry, but the standard {faction} variable will remain. I may add support for PlaceholderAPI within the same time frame.

**Comment by Kashalls** [comment]
I am kind of good with JavaScript but I wouldn't know where to start and
yes I am running pro

**Comment by kangarko** [comment]
Allright. Here is a snippet of a Java code that I begun to make for ChatControl. It is working and it fetches the relative color of the other player (but at this stage I can't tell you how it implement to a variable sorry):
https://pastebin.com/Lu5gcZX8


> ** Mon, 03 Apr 2017 09:06:28 -0700 - "kangarko/ChatControl" <chatcontrol@noreply.github.com>, "kangarko/ChatControl" <reply@reply.github.com> **
>
> I am kind of good with JavaScript but I wouldn't know where to start and
> yes I am running pro
>

**Comment by Kashalls** [comment]
Yeah, we can't figure out how to use the code. We honestly tried though.

**Comment by kangarko** [comment]
I just tried to make it, and realized that it requires two variables, the player that executes the messages, and the other player from which it is evaluated. Unfortunately it is not possible to gain access to the latter variable. I am sorry. This feature is already on the to-do list, and I'll be aiming to add it within the scope of the next two weeks.
