### ISSUE TITLE
Issue with Symbol prefix next to nickname.

### ISSUE THREAD

**Issue by Tosfoy** [kangarko/ChatControl#1931]
Hello! I have an issue with the symbol prefix next to a nickname, it shows on both nicknames and actual names.
![92212f6fb2e26f8496ae2638760c6e28](https://user-images.githubusercontent.com/58991099/171927541-431033a0-743a-4400-8533-70aa3f2bad99.png)

For example, Copycatcloudy does not have a nickname, but PickleRick does, yet it shows ~ next to both.

To add more, i'm using essentials, the nickname ~ feature does not work so i'm relying on chatcontrol for a fix, here's my chat format for names in chat
![eb0295acfff5ede058a6c79b5d18d85d](https://user-images.githubusercontent.com/58991099/171930481-a5418bcc-b1df-42b2-bcf7-4b27c66109e6.png)

![image](https://user-images.githubusercontent.com/58991099/171930874-097c2a79-2ea1-41a0-8b88-3658a3a0fc1b.png)

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey, actually you are not using Chatcontrol's nickname feature, so this is most likely and "issue" on essentials' side.
*(As you can see, `Apply_On:` is empty, which means our nick system isn't enabled)*

**Comment by ElBananaa** [comment]
I assume this has been solved since you didn't answer.
I'm closing this issue.
If you need anything else related to it, feel free to comment down below.
