### ISSUE TITLE
nick don't change displayname immediately

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#1932]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

https://user-images.githubusercontent.com/68513641/172016843-7f563c70-8754-4583-a32e-78e53d05d720.mp4

simple video that explains that player displayname don't change when you use nick
and you need to relog for the change to apply
Tag.Change_Displayname: true

**Comment by ElBananaa** [comment]
Hey, i'm unable to reproduce your issue on my side. Could you please try the version provided in #1888 and let us know if it changes anything?

**Comment by FakEEE14** [comment]
yep i tryed both version that provided there and still same result
you need to relog

**Comment by ElBananaa** [comment]
> yep i tryed both version that provided there and still same result you need to relog

Please set your debug key to `mysql` in chatcontrol's config file. Then reload the plugin, and try to change your nick. 
Once this is done, you should see something like that in your logs:
`[ChatControlRed] [mysql] Updating database with: INSERT INTO ChatControl (UUID, Name, Nick, Data, LastModified) VALUES ('df650855-f238-313a-b9c8-b63e9ed17920', 'ElBananaa', 'Test1', '{"Channels":{"standard":"write","admin":"read","global":"read","ranged":"read"}}', '1654436072181') ON DUPLICATE KEY UPDATE UUID=VALUES(UUID), Name=VALUES(Name), Nick=VALUES(Nick), Data=VALUES(Data), LastModified=VALUES(LastModified);`

Then, take a look at your database, and make sure your nick is properly saved in the `Nick` column of your `Chatcontrol` table, like the screenshot.
![image](https://user-images.githubusercontent.com/53318613/172053416-6bdbc0e5-8087-4ecb-86eb-6f90d4aec981.png)

**Comment by FakEEE14** [comment]
i don't have a database problem here, the placeholder %player_displayname% don't change and you need to relog to replace it with the nick name

**Comment by TheIntolerant** [comment]
> i don't have a database problem here, the placeholder %player_displayname% don't change and you need to relog to replace it with the nick name

Have you tried to debug it as mentioned above though?

**Comment by FakEEE14** [comment]
yes i did the data saves okay
[21:29:44]: FakEE7 issued server command: /tag nick off
```[21:29:44]: [ChatControlRed] [mysql] Updating database with: INSERT INTO ChatControl (UUID, Name, Nick, Data, LastModified) VALUES ('52a21e9d-7cd4-3238-b764-7c55c7cd9148', 'FakEE7', NULL, '{"Chat_Color":"dark_aqua","Channels":{"survivals":"write","helpop":"read","standard":"write","admin":"read","global":"read","staff":"read","rank":"read","helpme":"read"},"Spying_Sectors":["mail","book","private_message","anvil","chat","command","sign"],"Spying_Channels":["standard","towny","ranged","helpop","admin","rank","global","staff","survivals"]}', '1654444784390') ON DUPLICATE KEY UPDATE UUID=VALUES(UUID), Name=VALUES(Name), Nick=VALUES(Nick), Data=VALUES(Data), LastModified=VALUES(LastModified);```
[21:29:48]: FakEE7 issued server command: /tag nick test
```[21:29:48]: [ChatControlRed] [mysql] Updating database with: INSERT INTO ChatControl (UUID, Name, Nick, Data, LastModified) VALUES ('52a21e9d-7cd4-3238-b764-7c55c7cd9148', 'FakEE7', 'test', '{"Chat_Color":"dark_aqua","Channels":{"survivals":"write","helpop":"read","standard":"write","admin":"read","global":"read","staff":"read","rank":"read","helpme":"read"},"Spying_Sectors":["mail","book","private_message","anvil","chat","command","sign"],"Spying_Channels":["standard","towny","ranged","helpop","admin","rank","global","staff","survivals"]}', '1654444788890') ON DUPLICATE KEY UPDATE UUID=VALUES(UUID), Name=VALUES(Name), Nick=VALUES(Nick), Data=VALUES(Data), LastModified=VALUES(LastModified);```

**Comment by ElBananaa** [comment]
> i don't have a database problem here, the placeholder %player_displayname% don't change and you need to relog to replace it with the nick name

Well as I said it works fine, which is why I think this is a database issue.
Anyways, I have no idea about what's going on here.

**Comment by FakEEE14** [comment]
%player_displayname% don't changes and you need to relog to changes take effect

**Comment by ElBananaa** [comment]
> %player_displayname% don't changes and you need to relog to changes take effect

I understood that, the problem is, as I said, that I can't reproduce your issue.

Just make sure the Papi Player Expansion is up to date, if it's not, update it, if it is, then wait for Kangarko to have a look at it when he comes back from vacations.

**Comment by FakEEE14** [comment]
i'm sure it's update

**Comment by ElBananaa** [comment]
Hey,
Sorry for the delay @FakEEE14
Please send me a DM on discord, i'll provide you a dev build which should hopefully fix this issue.

**Comment by FakEEE14** [comment]
hi , can i have your discord id please

**Comment by ElBananaa** [comment]
Bananaa#1471

**Comment by kangarko** [comment]
I assume your problem was solved over Discord, please comment below if you are still facing this issue.

**Comment by ElBananaa** [comment]
> I assume your problem was solved over Discord, please comment below if you are still facing this issue.

The issue was fixed in one of the builds I sent to the user (based on the 1.19 pull request https://github.com/kangarko/ChatControl-Red-Src/pull/32)

**Comment by FakEEE14** [comment]
this was fixed until the new update. now is broken again :D
