### ISSUE TITLE
[Suggestion] Add a variable to know if the taget player is ignored

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#1933]
hi
this can help build a universal ignore player for rules like
adding a variable like {target_ignored} that return true or false, this way you can set a rules for ignored player
like:
require script {target_ignored}
to be true for a rule deny it

**Comment by kangarko** [comment]
Thanks however we have not received any other suggestion like this and prefer to keep our plugin lean, if multiple people request this then we will add it.
