### ISSUE TITLE
1.18.2: ch send does not support bungee

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#1935]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true (Velocity)

When I use `ch send`, it will only show on the DC and the server where the command is entered, but other servers will not show it, including `ch sendas`

My English is not good, use GOOGLE to translate

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.18.2 MySQL: true BungeeCord: true (Velocity)
> 
> When I use `ch send`, it will only show on the DC and the server where the command is entered, but other servers will not show it, including `ch sendas`
> 
> My English is not good, use GOOGLE to translate

Hey,
I believe this is an intended behavior. The only way to use `/ch send` to work on bungee is to use the same channels on all your servers.
Please wait for kangarko to review this when he comes back from vacations, just in case

**Comment by kangarko** [comment]
We do support bungee when doing /ch send, but as ElBananaa said the channel must support bungee and you must be joined to it to see the message.
