### ISSUE TITLE
1.18.2: TrMenu Placeholders didnt work in CHC

### ISSUE THREAD

**Issue by wafumoon** [kangarko/ChatControl#1937]
Minecraft Version: 1.18.2
MySQL: false
BungeeCord: i have Velocity

for some reason placeholders from TrMenu not working in CHC formats. In other plugins it works well
i think its because {} instead of %%

there is no errors.

**Comment by ElBananaa** [comment]
Hey,
TrMenu is deprecated, and it has been deprecated for more than a year now, so we most likely won't add support for it.
I'm leaving this open so Kangarko can review it when he comes back.

**Comment by wafumoon** [comment]
it is not
![image](https://user-images.githubusercontent.com/52106020/172670064-db67b42f-1e6c-42fc-a0ff-432a72c8fccb.png)
![image](https://user-images.githubusercontent.com/52106020/172670133-2a8cc1bd-82f6-42cb-88d0-a7a97fc82263.png)

**Comment by ElBananaa** [comment]
It is actually: https://i.imgur.com/62fKKor.png

They didn't publish any official release nor dev builds since 2020.
Anyways, as I said, please wait for Kangarko to review your request ^^

**Comment by 157946a** [comment]
> It is actually: https://i.imgur.com/62fKKor.png
> 
> They didn't publish any official release nor dev builds since 2020. Anyways, as I said, please wait for Kangarko to review your request ^^

You are wrong, score2 has been maintaining TrMenu, and it has not been updated, but it is not updated in TrMenu's own warehouse. It did stop for a while a year ago, but after two months, score2 took over the maintenance, the original author because I had to stop changing due to academic reasons.

**Comment by 157946a** [comment]
> 它实际上是：[https ://i.imgur.com/62fKKor.png](https://i.imgur.com/62fKKor.png)
> 
> 自 2020 年以来，他们没有发布任何官方版本或开发版本。 无论如何，正如我所说，请等待 Kangarko 审核您的请求^^

The official version has already been released on Actions. I don't know why Score2 was not released on Release.
https://github.com/InsinuateProjects/TrMenu/actions/runs/1541731638

**Comment by ElBananaa** [comment]
Alright, sorry for the delay,
Which placeholders are you trying to use exactly?
Also, did you try to replace `%%` with `{}` when using TrMenu's placeholders in chatcontrol?

**Comment by 157946a** [comment]
> Alright, sorry for the delay, Which placeholders are you trying to use exactly? Also, did you try to replace `%%` with `{}` when using TrMenu's placeholders in chatcontrol?

The reason why {} does not take effect is because TrMenu has a variable that it provides for its own use, for example, {data:key}, I think this may be in conflict with yours, and you need to create a papi variable

**Comment by ElBananaa** [comment]
Alright, I'll let you handle this with @kangarko when het gets back from vacations (in ~2 weeks)

**Comment by 157946a** [comment]
> Alright, I'll let you handle this with @kangarko when het gets back from vacations (in ~2 weeks)

OK

**Comment by kangarko** [comment]
Thanks, unfortunately I have no idea why it does not work. You can try checking if PlaceholderAPI has an expansion for TrMenu, if yes, download it, if no, then you can try adjusting our formatter priorities: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities. Unfortunately I am too busy right now to be able to add custom integration.

**Comment by 157946a** [comment]
> Thanks, unfortunately I have no idea why it does not work. You can try checking if PlaceholderAPI has an expansion for TrMenu, if yes, download it, if no, then you can try adjusting our formatter priorities: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities. Unfortunately I am too busy right now to be able to add custom integration.

Let me tell you a message, the variables of TrMenu are provided by the plug-in and do not need to be downloaded, and papi reload can still exist, so only the latter can be used.

**Comment by kangarko** [comment]
If they are provided by TrMenu itself and changing our priorities as per my link above does not work, then unfortunately it's incompatible.

**Comment by 157946a** [comment]
> If they are provided by TrMenu itself and changing our priorities as per my link above does not work, then unfortunately it's incompatible.

Let's see how he chooses. If the priority does not take effect, I suggest you use the papi variable to display it. After all, some plug-ins in taboolib will indeed grab the priority with other plug-ins, causing some functions to fail.

**Comment by kangarko** [comment]
We already support all PAPI variables automatically, if PAPI supports your plugin then it should be working. I am sorry for the inconveniences.

**Comment by 157946a** [comment]
> We already support all PAPI variables automatically, if PAPI supports your plugin then it should be working. I am sorry for the inconveniences.

You may need to set it to %player_name%, of course, he also has to try to modify the priority first to see if it can be used normally
