### ISSUE TITLE
Minecraft & Discord emoji

### ISSUE THREAD

**Issue by Rawxdealz** [kangarko/ChatControl#1938]
I have a problem with some emoji that dont work in minecraft but do in discord.
For login and logout messages i want to use these as a prefix 🔴  and 🟢. But they do not work in minecraft. I can use an other simular emoji in minecraft with a color code. Is it possible to make discord use an other emoji then minecraft as a prefix?

**Comment by ElBananaa** [comment]
Hey,
Apologize for the delay.
Could you elaborate a bit more about this, because i'm not sure to fully understand the issue right now? (If you could take screenshots or record a video to show what the issue is exactly, I wouldn't say no ^^

**Comment by Rawxdealz** [comment]
![image](https://user-images.githubusercontent.com/42896942/173138675-b6994898-0413-435d-9e1d-49b1379abb4d.png)
That is this emoji in discord:
![image](https://user-images.githubusercontent.com/42896942/173138765-20474be1-5940-4f88-9042-dca842d65280.png)
But it does not work in minecraft.
Is it possible to make discord have other emojis as a prefix then minecraft?
![image](https://user-images.githubusercontent.com/42896942/173139480-195fd745-1df4-4376-9c46-bcd695185313.png)

**Comment by Rawxdealz** [comment]
Or another way to achieve that?

**Comment by ElBananaa** [comment]
Alright, sorry for the delay,
So yeah, this is possible, but you'll have to tweak each message manually.
Basically, instead of defining the prefix in chatcontrol's main config file, you'll define it in the join/quit/death.rs files.

Here's an example with join messages: (replace `896859522684047401` with your join channel id)
```rs
group default
message:
- &a⬤ &7{player} &ejoined the game!
then discord 896859522684047401 🟢 {player} joined the server!
```

Same with quit messages: (replace `896859522684047401` with your quit channel id)
```
group default
message:
- &c⬤ &7{player} &eleft the game!
then discord 896859522684047401 🔴 {player} left the server!
```

Also, when using this method, make sure to remove both the `join:` and `quit:` parts under `Discord:` to avoid messages being duplicated. And same, remove `join:` and `quit:` under the `Prefix:` part.

Let me know if this is what you've been looking for!

**Comment by Rawxdealz** [comment]
I tried that before, and both messages came into discord. Also i am having alot of custom messages, is this also possible with that?

> group default
> message:
> - &a⚪ &7{player} &fhas joined the game
> then discord 945209773018718309 🟢 &7{player} &fhas joined the game
> - &a⚪ &7{player} &fhas joined the party
> then discord 945209773018718309 🟢 &7{player} &fhas joined the party

?

**Comment by Rawxdealz** [comment]
```group default
message:
- &a⚪ &7{player} &fhas joined the game
then discord 945209773018718309 🟢 &7{player} &fhas joined the game
- &a⚪ &7{player} &fhas joined the party
then discord 945209773018718309 🟢 &7{player} &fhas joined the party```

**Comment by Rawxdealz** [comment]
```group default
message:
- &a⚪ &7{player} &fhas joined the game
then discord 945209773018718309 🟢 &7{player} &fhas joined the game
- &a⚪ &7{player} &fhas joined the party
then discord 945209773018718309 🟢 &7{player} &fhas joined the party```

**Comment by Rawxdealz** [comment]
Lol dont know how to type like that in here.
![image](https://user-images.githubusercontent.com/42896942/173147823-6f7a9315-6d41-4153-8c4b-820b3412384d.png)

**Comment by ElBananaa** [comment]
The `join.rs` file should only be used to display messages of players joining the server, same with the `quit.rs` file. It should only be used to display messages of players leaving the servers.

As for party join messages, these are most likely handled by your party plugin, so you should customize these messages in there.

**Comment by Rawxdealz** [comment]
The join the party is a join message. It works but not when i am having more then 1 message under group default.

**Comment by ElBananaa** [comment]
Alright, I see, so basically you want multiple join message to be ran randomly when a player joins the server.
This is possible, however, it won't work with the `then discord` operator.
This means that you can only have one discord join/quit message, but as many ingame join/quit messages as you want, like that:
```
message:
- &a⚪ &7{player} &fhas joined the game
- &a⚪ &7{player} &fhas joined the party
then discord 945209773018718309 🟢 &7{player} &fhas joined the game```

**Comment by Rawxdealz** [comment]
Ok. Thank you for your time. Now it is up to me to know what i want, emoji or multiple messages,...
Thanks

**Comment by ElBananaa** [comment]
> Ok. Thank you for your time. Now it is up to me to know what i want, emoji or multiple messages,... Thanks

Feel free to open a suggestion to add a such feature! We are always open to new ideas to improve the plugin! :)
