### ISSUE TITLE
1.18.2: Wrong Labels in Help Usages

### ISSUE THREAD

**Issue by hatemabsi** [kangarko/ChatControl#1939]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

In the help messages, for example when running /msg 
the usage uses {label} which returns "chc" instead of "msg"

![image](https://user-images.githubusercontent.com/84775981/173025890-0ed20501-01b8-4358-b8c7-8515fa93ce7b.png)
![image](https://user-images.githubusercontent.com/84775981/173025958-1e065370-a27b-4004-a784-237d3561ae8b.png)

**Comment by ElBananaa** [comment]
Hey,
Thanks for reporting. Fixed in https://github.com/ElBananaa/Foundation/commit/3427c8ba4f5d56284157ef5da8655e1a65b30495
Next update should include this patch (I will most likely push a dev build on our discord this week-end for 1.19 early compatibility, which should also include this fix)
