### ISSUE TITLE
msg is just broken, really badly

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#194]
>.... [21:01:28 INFO]: [ChatControlRed] TIP Note: Received packet DB_UPDATE from creative3
>.... [21:01:28 INFO]: [ChatControlRed] TIP Note: Received packet DB_UPDATE from creative3
>.... [21:01:28 INFO]: [ChatControlRed] TIP Note: Received packet DB_UPDATE from creative3
>.... [21:01:28 INFO]: [ChatControlRed] TIP Note: Received packet DB_UPDATE from creative3
>.... [21:01:28 INFO]: [ChatControlRed] TIP Note: Received packet DB_UPDATE from creative3
>.... [21:01:28 INFO]: [ChatControlRed] TIP Note: Private message from michaelmode to acousthicc (is online ? false)
>.... [21:01:28 INFO]: [pm] michaelmode -> acousthicc: no, servers with big openings like that usually have way more
>.... [21:01:28 INFO]: [ChatControlRed] TIP Note: Received packet DB_UPDATE from creative4
>.... [21:01:29 INFO]: Enabled all spying for MrEPIC403.

I messaged acousthicc that message, but it shows that Michaelmode sent it in console and in-game. Why is it doing that?

**Comment by Sikatsu** [comment]
Is this one the latest version?

**Comment by DoogiePC** [comment]
> Is this one the latest version?

yes

**Comment by kangarko** [comment]
If that was after cca 30 minutes of you being connected, please test the new version.

**Comment by kangarko** [comment]
Closing, the very latest version should not have this issue.
