### ISSUE TITLE
1.18.2: User-Log Spam message

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#1940]
Hello, I have a question. 
The user logs are currently spammed with an error, which makes it a little more difficult for users to read if they want to read something again. 
Is there anything known in this direction or is something still needed for further diagnostics? 

Here is an excerpt from the player logs, the message is a regular spam ^^'' I also have no idea so far what it could be
https://paste.md-5.net/ehuzuqigep.css

Minecraft Version: 1.18.2
MySQL: true/
BungeeCord: true [Velocity]

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8912998/debug.zip)

**Comment by ElBananaa** [comment]
Hey,
This message appears because the client can't read the packets sent by the plugin.
Unfortunately we have no idea about how to fix this so far.

**Comment by Lorias-Jak** [comment]
This is very inconvenient, because the logs grow super fast within minutes, so that users with low memory will have problems playing with us in the long run, in addition to not being able to view the logs.
Maybe it has something to do with the velocity bridge, can I help you by sending more files? It is at least in the sense of many if the problem is solved and I am open to many things ^^''

**Comment by ElBananaa** [comment]
> This is very inconvenient, because the logs grow super fast within minutes, so that users with low memory will have problems playing with us in the long run, in addition to not being able to view the logs. Maybe it has something to do with the velocity bridge, can I help you by sending more files? It is at least in the sense of many if the problem is solved and I am open to many things ^^''

No need to, but thanks!
I already sent a message to Kangarko with something that should hopefully help finally patching this issue. However, as he's on vacations until the 21st, you'll have to wait a bit ^^
As for client logs themself, I believe the client will automatically delete them when they reach a certain size :)

**Comment by Lorias-Jak** [comment]
I have noticed that he is on vacation, I can also wait two, three, weeks. But I can at least offer everything that could help you :D 

Thank you for the help, I remain curious! :)

**Comment by kangarko** [comment]
It's a known issue, because the client does not recognize our packet. We have to send it twice per second to keep information from Spigot synced on Bungee. I am open to better solutions but I am afraid I have none at the moment, sorry.

**Comment by Lorias-Jak** [comment]
I will ask the Dev of my confidence whether he has a good idea.

**Comment by ElBananaa** [comment]
Hey, we may have found a way to fix this. Please keep an eye on #1951 to follow Kangarko's progress on this issue.
