### ISSUE TITLE
1.18.2: Gradient and Nick Colors

### ISSUE THREAD

**Issue by SpectreVoid** [kangarko/ChatControl#1943]
In the wiki it states that I should use:

Make the entire part in gradient colors. (Requires Minecraft 1.16+)

Syntax: -

Examples: "RED - GOLD" or "#123456 - #123456"

But the issue is that I don't know where to put it, when I tried in-game to do /tag nick <color> <nick> that doesn't work and the nick turns out white plain writing. And I don't understand how I can do gradient in chat either. I tried /chc color "color - color" that doesn't work. So I'm not sure if I understand how the gradient works or if it's only limited to adding in the config files? appreciate the help :) great plugin! 

Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey,
As the gradient part can be found in the format wiki pages, the Gradient feature only works in your format files.
There should be an example on how to use this feature in the default formats/chat.yml file.
