### ISSUE TITLE
1.18.2: Possible to have multiple click events? [QUESTION]

### ISSUE THREAD

**Issue by VouchMe123** [kangarko/ChatControl#1947]
Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

Question: Anyway to put multiple RUN_COMMAND or SUGGEST_COMMAND? Like Left-Click to suggest one command, Right-Click to suggest another. But under the same variable. 

![image_2022-06-25_001044776](https://user-images.githubusercontent.com/108157852/175721571-3371e017-4a5f-45ad-8642-c9b59e0eb0ba.png)

I would love it to have it like this:

![image_2022-06-25_001255471](https://user-images.githubusercontent.com/108157852/175721686-9e2ddc37-e207-4352-87e4-b5667024d4b7.png)

**Comment by kangarko** [comment]
No sorry, this is a limit imposed by Minecraft, only one is possible.
