### ISSUE TITLE
1.19: How to setup BungeeCord chat without channels?

### ISSUE THREAD

**Issue by Andore97** [kangarko/ChatControl#1948]
Minecraft Version: 1.19
MySQL: true
BungeeCord: true
latest plugins

**Comment by ElBananaa** [comment]
Hey,
You can't setup a Bungeecord chat without our channels system enabled.
This is a voluntary limitation of the plugin as our chat system is require for most features to fully work. (The message remove feature, the purge command, the channel/player mute commands, the variable system, etc...)

**Comment by Andore97** [comment]
hmm then a need to make an bungee channel with autojoin right?

In the settings i found this:

  # - Bungee: true/false option. **This overrides Integration.BungeeCord from below**, so you can
  #           disable BungeeCord message synchronization for some channels.
which integration is mean with that?

**Comment by ElBananaa** [comment]
> hmm then a need to make an bungee channel with autojoin right?
> 
> In the settings i found this:
> 
> # - Bungee: true/false option. **This overrides Integration.BungeeCord from below**, so you can
> # disable BungeeCord message synchronization for some channels.
> which integration is mean with that?

That's right. You can take a look at our wiki page, as it explains pretty much everything about it: https://github.com/kangarko/ChatControl-Red/wiki/Channels#auto-join

As for the bungee integration, well this means that setting `Bungee: true` or `Bungee: false` will overwrite settings under the `Integration.BungeeCord` part.

**Comment by Andore97** [comment]
for understanding, when its override the option that you must have enabled for usage then why its even there? you must have it enabled for bungeecord chatting.

**Comment by ElBananaa** [comment]
Alright, to make it simple:
When using the `Integration.BungeeCord` part and without having `Bungee: true` or `Bungee: false` under each channel, BungeeCord message synchronization will work on all channels.
When using the `Integration.BungeeCord` part with some of the channels using `Bungee: false` and some other channels using `Bungee: true`, BungeeCord message synchronization will only be enabled for channels with `Bungee: true`.

That's the point of having 2 config options for this.

**Comment by Andore97** [comment]
alright thanks
