### ISSUE TITLE
1.16.4 | Problem with the rules system

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#195]
# **Environment**
### **ChatControl Version**: ChatControlRed-10.1.2

- Hey! I noticed a weird issue with the actual rules system. It looks like using a rule to block the /pl command also block every command starting with /pl (E.G.: /playsound, /playerskull, /playerweather)...

My server is in online mode, I don't use MySQL or BungeeCord.

This is my rule in the command.rs
```
match ^\/(bukkit:*|pl|plugin|plugins|ver|version|ifo|news|eabout|gc|lag|mem|memory|about|icanhasbukkit)
then warn &8&l» &eNice try m8!
then deny
```

And here's the console log:
```
29.11 22:48:12 [Server] INFO ElBananaa issued server command: /playerweather
29.11 22:48:12 [Server] INFO *--------- Rule match (command) for ElBananaa ---------
29.11 22:48:12 [Server] INFO MATCH: ^/(bukkit:*|pl|plugin|plugins|ver|version|ifo|news|eabout|gc|lag|mem|memory|about|icanhasbukkit)
29.11 22:48:12 [Server] INFO CATCH: /playerweather
29.11 22:48:12 [Server] INFO Original message cancelled.
```

I know that I can use the `ignore command` variable, but it wasn't necessary in the previous versions. Is it now?

**Comment by kangarko** [comment]
Do not use such rules to block commands, instead, give negative permissions for these commands such as "-bukkit.command.plugins" (or a false permission if using LuckPerms), that will prevent all forms of accessing this command.

https://bukkit.gamepedia.com/CraftBukkit_Commands
https://essinfo.xeya.me/permissions.html
