### ISSUE TITLE
commands.txt not supporting ANSI

### ISSUE THREAD

**Issue by TheWranger** [kangarko/ChatControl#195]
I converted the commands.txt rules file to ANSI encoding so I could use \n to make new lines, but upon doing so, the server is now unable to read the file and is giving me errors on startup.
https://pastebin.com/P2ZGBDRq

**Comment by kangarko** [comment]
Hey,

every system is different in general I recommend using utf-8 encoding (see the wikipedia to the free version on saving it using Notepad++). You can enforce \n by setting **Enforce_New_Line** to **true** in settings.yml
