### ISSUE TITLE
Unknown packed identifier: chatcontrol

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl#1951]
Solution: Use BungeeCord as main channel and ChatControl as subchannel for bungee sending to remove client log spam

**Comment by Valaron-Jakob** [comment]
I hope its not a problem asking in a closed issue, but how would one do this with Velocity instead of BungeeCord?

**Comment by ElBananaa** [comment]
> I hope its not a problem asking in a closed issue, but how would one do this with Velocity instead of BungeeCord?

Velocity supports the Bungeecord plugin messaging channel natively : https://docs.papermc.io/velocity/faq#does-velocity-support-plugins-developed-for-bungeecord-or-waterfall

**Comment by ElBananaa** [comment]
@kangarko Are there any news about this? I believe someone recently asked updates on discord.
I wish I could help, but I still can't manage to setup a working bungeecord server locally.

Here's a link to spigot's wiki about this, it doesn't look that hard/long to fix https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/

**Comment by kangarko** [comment]
Not hard but I am trying to avoid breaking changes for students of my trainings otherwise it wont work for them, that is what makes it hard. I will keep you updated once progress is made, no ETA.
