### ISSUE TITLE
1.18.2 [item] does not show hover over lore for items with gradients.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1952]
Any item that has a gradient and is used in chat with [item] does not have working hover over for its lore.

Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Technical limitation for now, I am sorry my plate is extremely full these weeks so I am unable to resolve this. A note to self: Probably an ugly solution where we force the hover for every letter of different gradient color.
