### ISSUE TITLE
1.18.2  Access to my custom plugin

### ISSUE THREAD

**Issue by Floxiik** [kangarko/ChatControl#1955]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true
Redis: true

Hi, i got this warn in console 
![image](https://user-images.githubusercontent.com/52674139/176438309-6fef4041-a444-4864-b432-13a4fd0c8f81.png)
I don't even use ChatControl API, i think it is chc side.

**Comment by kangarko** [comment]
We do not use your API, you can open our JAR > plugin.yml and add your plugin to softdepend to hide this warning for whatever reason it came from.
