### ISSUE TITLE
server-name not configured

### ISSUE THREAD

**Issue by dinobossytnew** [kangarko/ChatControl#1956]
Hello kanguro-san, I need your help in something the error that I am going to leave marked in a mcpaste you will see that it asks me to change the server-name but there is a big problem there is no such thing in settings.yml and according to the config that passes me in the link of mineacademy.org/server.properties it places it like this but in settings there is no server-name only if you use bunge.

I leave you the files apart from the error.log of your plugin and the log of my server.

link error log ccred: https://pastebin.com/pEqzjRkF
link log full:  https://pastebin.com/npvAeNtF

Note: You were told that no path type was found to edit this.

Minecraft Version: 1.19
MySQL: false
SoftWare: Purpur
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey, please read the error message properly : `Detected getServerName call, please configure your 'server-name' in server.properties according to mineacademy.org/server-properties`
It tells you ton configure the `server-name` key in the `server.properties` file, according to https://mineacademy.org/server-properties

**Comment by dinobossytnew** [comment]
I don't understand what you mean if my server-name is set.

**Comment by dinobossytnew** [comment]
@ElBananaa

**Comment by kangarko** [comment]
Simply read what it says: Please configure your 'server-name' in server.properties according to mineacademy.org/server-properties
