### ISSUE TITLE
server-name not configured 

### ISSUE THREAD

**Issue by dinobossytnew** [kangarko/ChatControl#1957]
#1956
I don't understand if it is placed on my purpur server here is the file.

https://pastebin.com/qF063Nq9

**Comment by TheIntolerant** [comment]
Basically you need to edit your server properties and add the key "server-name" along with a name

For example you could add a new line in server.properties file that looks like this
```
server-name=survival
```

For more information visit
https://mineacademy.org/server-properties

**Comment by ElBananaa** [comment]
TheIntolerant said everything that has to be said. Looks like you actually already added the `server-name=Survival` line in your `server.properties` file, so everything should work perfectly fine.

I'm closing this, if you need anything else, simply comment down below, no need to open a 3rd issue for the same problem.

**Comment by dinobossytnew** [comment]
ok now i have another problem the /chc tour confirm 
it thanks me etc etc but it doesn't work well.

I try to use some chatcontrol function and it still doesn't work, it asks me for the tour again.

**Comment by TheIntolerant** [comment]
You need to read the [Terms](https://github.com/kangarko/ChatControl-Red/wiki/terms) and you will find the command to unlock the plugin.

**Comment by dinobossytnew** [comment]
I read them, the command is /chc tour confirm but once I execute this command, I execute /chc color and it asks me again for the terms as if the path is not confirmed.

**Comment by kangarko** [comment]
/chc tour mothman is the command, not /chc tour confirm
