### ISSUE TITLE
Minecraft Version: 1.19 Issue Title 

### ISSUE THREAD

**Issue by mmcmullen9420** [kangarko/ChatControl#1958]
Minecraft Version: 1.19
MySQL: false
BungeeCord: true
[latest.log](https://github.com/kangarko/ChatControl-Red/files/9014377/latest.log)
will not load Chatcontrol Red we are using bungee.. and we actually bought the plugin twice once from spigot once on MCmarket we like the plugin but it simply does not load. if there is a dependency issue please let us know. we self host Thanks -Mike

**Comment by ElBananaa** [comment]
Hey,
Your logs are clearly telling you what's wrong : `[ChatControlRed]  You are running an old and unsupported version of ProtocolLib, please update it.`
ProtocolLib 4.8.0 doesn't support MC 1.19, you must use the latest dev build.

**Comment by mmcmullen9420** [comment]
> Hey, Your logs are clearly telling you what's wrong : `[ChatControlRed] You are running an old and unsupported version of ProtocolLib, please update it.` ProtocolLib 4.8.0 doesn't support MC 1.19, you must use the latest dev build.

4.8.0 is the latest build

**Comment by ElBananaa** [comment]
4.8.0 is the latest stable version, not the latest dev build. ProtocolLib 4.8.0 doesn't work on 1.19. Their spigot page provides you a link to their dev builds.
