### ISSUE TITLE
How to use the ChatControl Pro's classic chat format with admin chat and ! in Red

### ISSUE THREAD

**Issue by mrstirlic** [kangarko/ChatControl#196]
Good afternoon, Matej Pacan, I have the following question on how to format a chat without using channels, if this is not possible then please add the usual chat formatting without any commands like in ChatControl Pro v8 for example global local and admin chat without changing your new formatting system chat in ChatContorolRed v10 because not everyone on my server wants to register the command / ch join {channel} when entering the server to write something to the chat, because with the channels there is the following problem when you write what to the chat using for example the sign "!" this message does not appear for the global channel in the server console. I hope you can help me solve this problem while this plugin is in the beta stage.

![image](https://user-images.githubusercontent.com/62768099/100601835-c6544380-330b-11eb-9e0f-064513a865a3.png)
![image](https://user-images.githubusercontent.com/62768099/100601899-de2bc780-330b-11eb-9901-16601326216e.png)

**Comment by OfT3N** [comment]
> Good afternoon, Matej Pacan, I have the following question on how to format a chat without using channels, if this is not possible then please add the usual chat formatting without any commands like in ChatControl Pro v8 for example global local and admin chat without changing your new formatting system chat in ChatContorolRed v10 because not everyone on my server wants to register the command / ch join {channel} when entering the server to write something to the chat, because with the channels there is the following problem when you write what to the chat using for example the sign "!" this message does not appear for the global channel in the server console. I hope you can help me solve this problem while this plugin is in the beta stage.
> 
> ![image](https://user-images.githubusercontent.com/62768099/100601835-c6544380-330b-11eb-9e0f-064513a865a3.png)
> ![image](https://user-images.githubusercontent.com/62768099/100601899-de2bc780-330b-11eb-9901-16601326216e.png)

Take a look into /rules/chat.rs
You can send !text to global #text to other chat, and &text for another. You do not have to use any /ch join, just set the autojoin permission for players

**Comment by OfT3N** [comment]
And i noticed that ur Ukrainian, so if you speak Russian, you can PM me in Discord (`_OfTeN_#6829`) and ill tell you how it works if you didnt get it

**Comment by kangarko** [comment]
Thanks for suggesting this. You can achieve this in CHC10 too but it needs a few more steps. I can record a video tutorial in a few days.

**Comment by mrstirlic** [comment]
Good. I'll wait.

**Comment by mrstirlic** [comment]
> And i noticed that ur Ukrainian, so if you speak Russian, you can PM me in Discord (_OfTeN_#1337) and ill tell you how it works if you didnt get it


I can’t write to you, you have a nickname in discord like or a different hashtag 
![image](https://user-images.githubusercontent.com/62768099/100773481-9be8b000-3409-11eb-8fd0-9fb6ee043fed.png)

**Comment by OfT3N** [comment]
> > And i noticed that ur Ukrainian, so if you speak Russian, you can PM me in Discord (_OfTeN_#1337) and ill tell you how it works if you didnt get it
> 
> I can’t write to you, you have a nickname in discord like or a different hashtag
> ![image](https://user-images.githubusercontent.com/62768099/100773481-9be8b000-3409-11eb-8fd0-9fb6ee043fed.png)

My nitro has just expired today :D `_OfTeN_#6829`

**Comment by kangarko** [comment]
I don't accept PMs since I can't manage all of this on so many places. For public issues, use GitHub. For private issues, email support@mineacademy.org

Unfortunately I won't be able to take on this video task this weekend but it's on my list ;)

**Comment by OfT3N** [comment]
> I don't accept PMs since I can't manage all of this on so many places. For public issues, use GitHub. For private issues, email [support@mineacademy.org](mailto:support@mineacademy.org)
> 
> Unfortunately I won't be able to take on this video task this weekend but it's on my list ;)

He didn't mean to PM you, he PMd me and we solved his question as I understood

**Comment by kangarko** [comment]
Recorded a video on using channels in a way like we did previously with chat formatting: https://www.youtube.com/watch?v=EKziLXSjwhY
