### ISSUE TITLE
1.18.2: Tag Nickname Success Message

### ISSUE THREAD

**Issue by hatemabsi** [kangarko/ChatControl#1960]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

Hello, I set up the tag nickname through the rules however I noticed the success message is like this 
![image](https://user-images.githubusercontent.com/84775981/176622350-46ff6ef7-f896-4349-b3ea-8f923ef9a331.png)
and I can't find a place to actually change this specific message.

Is that something that could be done?

**Comment by kangarko** [comment]
You can change it in Commands.Tag.Success_V2 key in localization/messages_en.yml file.
