### ISSUE TITLE
1.18.2: (Posible issue) Can't click chat hyperlinks

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#1963]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

Hey, so for some reason, every server I set up and has at least EssentialsX or World Guard (two only plugins confirmed to cause this issue so far) set up on it, I can't click (at least some of) the hyperlinks written in chat. This should be vanilla permitted behaviour.

I know this is posibly not an issue related to CHCRed (and right now I'm thinking I should probably test CHCRed on my localhost test server, on it's own, to see if the issue can also be reproduced with your plugin), but I still wanted to ask about it, since CHCRed can/is supposed to control the entirety of the chat's behaviour right? And I can't click on links, so I was wondering if maybe there is some way I can enforce hyperlinking from server chat links, either with some more specific formatting, or maybe rules...

For my tests I'm using clean installations of Paper and the mentioned confirmed plugins, on their own, and only with any required dependencies for them. It's a really baffling problem.

In the case of EssentialsX, I tried installing EssentialsXChat and it fixes this issue (this was suggested by some of the essX staff), but the issue is far to being related to a single plugin... actually, it seems any plugin that is in some shape or form controlling chat can cause the problem. You may wonder why I consider WG to touch chat, and that is because it has some chat features where you can toggle flags through it.

Also, and very importantly: 
- This issue can be reproduced by every player I've asked, on my main server.
- My client is properly configured and allows for clicking hyperlinks in options. 
- Nobody who tested the issue has any mods installed and their installation of minecraft was either completely or very close to clean.
- All servers this was tested on where Paper 1.18.2's last release.

**Comment by TheIntolerant** [comment]
For context, where exactly are these links?
A chat message sent by player? Format file? Or something else?

Also to confirm that it isn't an EssentialX issue, is the link displayed in its entirely like this "google.com" and not like "google com"

**Comment by kangarko** [comment]
Please try following this tip: https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#ad-filter-doesnt-work-all-dots-are-removed-example-wwwgooglecom-becomes-www-google-com

We are not blocking links detection feature, if you put a URL to the chat then your client should make it clickable automatically.
