### ISSUE TITLE
Link for BungeeControl-Red is not working

### ISSUE THREAD

**Issue by YrChen1001** [kangarko/ChatControl#1964]
How I get BungeeControl-Red, that link page is not work.

**Comment by TheIntolerant** [comment]
It may be unavailable until it is approved by staff on mc-market for the next few days. Right now, it seems it is still unavailable as you can see it is not listed  as a resource by kangarko [shown here](https://www.mc-market.org/resources/authors/91814/).

**Comment by YrChen1001** [comment]
oh , can that send it here ? because I need use that.

**Comment by kangarko** [comment]
We're still waiting for approval, I am going to try sending staff a message to expedite the process. Download it from here:

[BungeeControl-Red-3.12.0.jar.zip](https://github.com/kangarko/ChatControl-Red/files/9033161/BungeeControl-Red-3.12.0.jar.zip)
