### ISSUE TITLE
AutoJoin channels

### ISSUE THREAD

**Issue by AgentPieCZ** [kangarko/ChatControl#1966]
Hi, i want to setup "premium channels" well , i made them , only problem i have is, i can¨t figure how to make person ( Default player ) who buys Vip move  autojoin to Vip Channel and after Vip expires, it will move him back to default.
------------------------------------
Now it works like... it will move person, but wont join him back to read from all 3 channels (default, legendadefault, admindefault)
... tried to make it work like for 4 hours, without succes

Minecraft Version: 1.19
MySQL: false
BungeeCord: false

---Config options
  Max_Read_Channels: 3
  Join_Read_Old: true
  Ignore_Autojoin_If_Left: false
  Autojoin_On_Reload: true

 -- Using luckperms
  - My permissions in luckperms
![Bez názvu](https://user-images.githubusercontent.com/86957086/177014215-1832d960-2567-4eb4-8e42-44ad4051a3e1.png)

**Comment by kangarko** [comment]
We unfortunately don't have a timer that would move the person back after 4 hours.

What you can do is either install a third party plugin from which you would run the command to move the player such as /channel set, or use timed permissions and then kick the player out of the game, rejoining will cause him to lose the ineligible channel automatically.

Sorry for the inconvenience.
