### ISSUE TITLE
1.19: How do you enable the chat filter?

### ISSUE THREAD

**Issue by cyberpxl** [kangarko/ChatControl#1968]
Minecraft Version: 1.19
BungeeCord: false

How do you enable the chat filter? I've looked everywhere and I can't find a single thing about it anywhere. Is there a way to enable this, or do you have to use rules to make it yourself?

**Comment by ElBananaa** [comment]
Hey,
What do you mean exactly by "Chat Filter"? If you are talking about swear/ads filtering, you need to have a look at the files in the `rules/` folder.

Note that you also need to enable the rules system. (The comments in the settings file explain absolutely everything)
![image](https://user-images.githubusercontent.com/53318613/177836374-df1988e4-5587-4d1a-bbe5-853b5889406a.png)

Finally, I suggest you take a look at our wiki to understand how each feature works, what are their limitations, etc. https://github.com/kangarko/ChatControl-Red/wiki


I'm closing this, but feel free to keep commenting down below if you need anything else.

**Comment by TheIntolerant** [comment]
To add to what was said above, basically the "chat filter" on chatcontrol may also be referred as "chat rules".

To configure these rules, open the rules folder in chatcontrol and look for ``chat.rs``

If you see "group swear" under a rule, that group is configured in the ``groups.rs`` file

For more information go to https://github.com/kangarko/ChatControl-Red/wiki/Rules

**Comment by cyberpxl** [comment]
Thanks
