### ISSUE TITLE
1.19: CMI Hex Colour Gradients Don't Work When Channels Are Enabled

### ISSUE THREAD

**Issue by MrCrazys** [kangarko/ChatControl#1969]
Minecraft Version: 1.19
MySQL: true
BungeeCord: true
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9061189/debug.zip)

When using CMI's hex colours, for example `{#red>}This is a gradient!{#orange<}`, and channels are enabled, it doesn't seem to send the colours, it just shows the raw message without the colours being translated. However, using just `{#red}Hello!` works fine while channels are enabled.

**Comment by kangarko** [comment]
I apology but when enabling our own formatting system, we handle colors in our own way which at this moment has no support for in-chat gradients.
