### ISSUE TITLE
pet name foramatter support

### ISSUE THREAD

**Issue by BabelSolea** [kangarko/ChatControl#197]
hello add pls supporting mypet premium to prevent "SurpriseMotherfucker" pet names =)

https://www.spigotmc.org/resources/mypet-premium.17566/

and add pls feature to prevent nametags with that) to vanilla mobs in anvil changes.

sry for bad english :3

**Comment by kangarko** [comment]
Hey, thank you for your suggestion. Unfortunately I did not purchase that plugin so I cannot hook into it. Also ChatControl already has the feature of catching swearings in anvil.
