### ISSUE TITLE
Is it possible to add something like DiscordSRV event listening priority?

### ISSUE THREAD

**Issue by twseer67875** [kangarko/ChatControl#1972]
Since ChatControl is called ChatControl, I hope to open more restrictions such as DiscordSRV hooks or provide DiscordSRV listening priority, because I found that ChatControl seems to want to control all chat content, which will cause unnecessary trouble when other plugins try to intervene. And the problem, I hope that the option can be opened to let the user decide whether to leave the ChatControl option, after all, these things should be left to the user to decide, not the plugin itself or the plugin author

**Comment by kangarko** [comment]
Thanks, while I do not completely understand your question, I am afraid this is technically hard to implement without nasty workarounds. We are a chat plugin, we format chat and we offer discordsrv feature which you can disable. Having it enabled we take control to format and manage it.

**Comment by twseer67875** [comment]
@kangarko I mean is it possible to turn on the option to modify DiscordSRV ListenerPriority ?
Since I checked that org.mineacademy.chatcontrol.lib.model.DiscordListener is currently hardcoded, is there an option to adjust it, is it possible to use other plugins to interfere with the message content without affecting the events monitored by ChatControl and DiscordSRV?

**Comment by twseer67875** [comment]
At present, it is found that the ListenerPriority of ChatControl to DiscordSRV is HIGHEST, I hope it can be modified

**Comment by kangarko** [comment]
Not technically feasible to rework the entire class to make the priority customizable, you are so far the first who requests it. For your special case I recommend disabling discord integration in chatcontrol and using a third party or your own solution, I apology.

**Comment by twseer67875** [comment]
> Not technically feasible to rework the entire class to make the priority customizable, you are so far the first who requests it. For your special case I recommend disabling discord integration in chatcontrol and using a third party or your own solution, I apology.

Well, this is really frustrating because it means I have to develop a dedicated patch for this myself to deal with this, or can you just change the ListenerPriority to HIGH to leave room for other adjustments later?🥲

**Comment by kangarko** [comment]
That sounds doable ;)

Just to make sure, do you mean this class? https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/model/DiscordListener.java#L480

This is where we have those discord listeners.

**Comment by kangarko** [comment]
Done!

**Comment by twseer67875** [comment]
> Done!

Wow, thank you so much, this modification has greatly reduced the development workload of the Discord patch I developed myself, thanks 🥰

**Comment by kangarko** [comment]
If you appreciated you can drop us a review at [MCMarket](https://www.mc-market.org/resources/18217/reviews), someone tried to attack our community there recently which is a shame.
