### ISSUE TITLE
Cannot finish tour

### ISSUE THREAD

**Issue by mfcc168** [kangarko/ChatControl#1974]
![image](https://user-images.githubusercontent.com/88373848/177955324-bd79cfd4-b726-4fea-b7c1-043a93839e42.png)
even though I finished the tour, it still pops up this message
Minecraft Version: 1.12.2
MySQL: false
BungeeCord: true

**Comment by mfcc168** [comment]
![image](https://user-images.githubusercontent.com/88373848/177955959-1a49190a-c538-42aa-801e-c43b3c6f6439.png)
the /chc tour confirm just does not work

**Comment by ElBananaa** [comment]
`You will find the unlock command by reading our terms`
The plugin tells you exactly what to do. Read tthe terms on the link provided to find the required command.
