### ISSUE TITLE
1.12.2: emoji doesn't work on discord integration

### ISSUE THREAD

**Issue by mfcc168** [kangarko/ChatControl#1976]
![image](https://user-images.githubusercontent.com/88373848/178089524-56ba139d-2d18-46a2-9f43-66836be47208.png)
It only shows the emoji code but does not convert it to emoji
Minecraft Version: 1.12.2
MySQL: false
BungeeCord: true

**Comment by mfcc168** [comment]
And how can I format the style of message that is sent to the discord?
for now it is just name: message

**Comment by kangarko** [comment]
I am sorry, we do not provide this ability.

You can however, format the style of message sent to Discord in Channels.List in settings.yml, there is Discord_Format I believe (see the comments above the List key).
