### ISSUE TITLE
Problem 1.19

### ISSUE THREAD

**Issue by BrayaanPS** [kangarko/ChatControl#1977]
Minecraft: 1.19
ChatControlRed: 10.12.3
ProtocolLib: 5.0.0 Snapshot
MySQL: false
BungeeCord: false

Problem:
1. Messages are not displayed when I use the {chat_color} variable 
![image](https://user-images.githubusercontent.com/30274810/178107290-8dc0fe86-8154-4540-a4e9-2893b1979aac.png)
2. When trying to delete a message with the [X] it does not let you delete it

**Comment by ElBananaa** [comment]
Hey,
I'm unable to reproduce the first issue.
Could you please provide us your `/chc debug` file?

As for the second issue, this is a known issue (I believe, @kangarko?) with ProtocolLib latest devbuilds. For an unknown reason, using the latest ProtocolLib dev build works perfectly fine on 1.18.2, but starting 1.19, the X remove feature and the purge command do not work anymore.

**Comment by BrayaanPS** [comment]
Hi, sorry for the delay, here it is.
https://ufile.io/9m4426oc

**Comment by ElBananaa** [comment]
> Hi, sorry for the delay, here it is. https://ufile.io/9m4426oc

No worries, thanks!
You forgot to add the `{message}` placeholder after the `{chat_color}` placeholders in your `formats/chat.yml` file, which seems to be the cause of your issue.
This is how your `message:` part should look like at the end of your chat.yml file:
```yaml
  message:
    Message: '&8: &7{chat_color}{message}'
    Hover:
    - '&7Enviado: &e{timestamp}'
 ```

**Comment by BrayaanPS** [comment]
Oh, that was it, thank you very much!
