### ISSUE TITLE
1.16.4 | little /motd issue

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#198]
When i do just /motd, it says, that im offline, but if i do /motd _OfTeN_ - works fine
![image](https://user-images.githubusercontent.com/62369973/100650309-cb89b080-3354-11eb-8167-ed1294610eac.png)

Minecraft version: 1.16.4
Mysql: false
BungeeCord: true (but i guess false because i do not use MySQL)
debug:
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5624503/debug.zip)

**Comment by kangarko** [comment]
You did not follow the new issue template: https://github.com/kangarko/ChatControl-Red/issues/2

**Comment by OfT3N** [comment]
> You did not follow the new issue template: #2

Edited

**Comment by kangarko** [comment]
Thanks that will likely be fixed in the next version

**Comment by kangarko** [comment]
![a](https://i.imgur.com/850P3ce.gif)
