### ISSUE TITLE
1.19: can't send death messages to discord with then discord

### ISSUE THREAD

**Issue by nickstaub** [kangarko/ChatControl#1982]
I am trying to use then discord to send death messages to discord. I started by using the channel name from in discord but it said in the error to use the id. I updated it to use the channel id and now gives this error "JSON requires Map to be translated into keys that are String only, found Long: 914660425285656577 with value test"
emailing debug file and relevant errors from error log.

Minecraft Version: 1.19.0
MySQL: true
BungeeCord: false
Velocity: true

**Comment by kangarko** [comment]
Thanks, going to have a look in 24h

**Comment by mcer10081** [comment]
i also have this same problem but i'm using bungeecord

**Comment by kangarko** [comment]
Sorry for the delay.

Problem fixed: ![a](https://i.imgur.com/9vL2Qgn.png)
