### ISSUE TITLE
1.19: Error in console

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1985]
Minecraft Version: 1.19
MySQL: true
BungeeCord: true

Ever since I upgraded to purpur 1.19, I am receiving these errors in console: <https://pastebin.com/rSsa9XZs>
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9091817/debug.zip)

**Comment by kangarko** [comment]
Investigating right now

**Comment by kangarko** [comment]
Does it please happen on Paper?

**Comment by Sikatsu** [comment]
Due to my health issues i'm not able to test that at this time. I just made sure to report it

**Comment by kangarko** [comment]
Sorry I am late.

I've upgraded our JSON library and testing your setup, I haven't found any issues so far:

![2022-07-18-18 02-043](https://user-images.githubusercontent.com/1918426/179553689-d5bb04d7-e51c-498a-8a6d-8e277a86f70a.jpg)

The new version will include the fix.
