### ISSUE TITLE
1.19 Lands can't connect to MySQL database when ChatControl-Red is installed

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1987]
I'm using the land claiming plugin called Lands. After installing ChatControl-Red the Lands plugin can't connect to the MySQL database anymore and is therefore disabled. When I remove this plugin, this issue goes away and there is no database problems.

This issue still exist using the latest version 10.12.4

Minecraft Version: 1.19
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Please try the new version that I am going to release tonight.

If that still won't help, please drop me your error stack log below.
