### ISSUE TITLE
[1.19] [10.12.3] Memory Leak (Database)

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1988]
I don't know what changes were made in ChatControl 10.12.3's database code, but they are causing the server to gradually fill all the RAM, causing old gc and then server crash.

Even though I couldn't find anything in heapdump, I tested this over 5 times (with 200 players) and each time I tried switching from using data.db file to using a database. In the end, it always caused old gc/crashed the server while using a database. Sometimes the server didn't even last more than an hour. When using data.db, the server was lagging a bit more, but it didn't cause old gc/crash the server.

This behaviour did not happen when using 10.12.1 in 1.18.2.

**Comment by Michael-A-Sloan** [comment]
I can confirm this as well I have been watching this same issues like this.

**Comment by kangarko** [comment]
Without any heat dumps or logs I cannot investigate, please provide relevant data so I can have a look. Thank you.

**Comment by Teslicek** [comment]
As I already explained, heapdump doesnt show anything, because stuff like databases are not shown there. What I'd like you to do is review the database code changes you've made since 10.12.1, because the issue was not happening there.

**Comment by kangarko** [comment]
I have reverted changes made to closing database connection forcefully, try the next release and let me know if there were any improvements.

**Comment by Teslicek** [comment]
I can confirm that the memory leak has been fixed in the 10.12.6 version.

**Comment by kangarko** [comment]
Awesome!
