### ISSUE TITLE
Similar messages - way to disable check after specific time?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#199]
Hi, can I somehow disable similar messages check for ex. 2 minutes? So if player wanna write:
"I'm selling XP bottles".
and the check will be set to be allowed for 2 minutes, then after 2 minutes he can repeat this message, if it's under 2 minutes it will be normally blocked. I just wanna some timer, if it's possible.

**Comment by kangarko** [comment]
Not currently, that would be a bit overcomplicated with our current system, but I can take this as a suggestion for the future!
