### ISSUE TITLE
1.19 Infinity tour

### ISSUE THREAD

**Issue by Dionis1902** [kangarko/ChatControl#1992]
In minecraft 1.19 i have infinity tour
![image](https://user-images.githubusercontent.com/63014993/179354938-6d33ecda-f332-4fcc-b085-7994ce5b3abb.png)
After reload i try use /msg but he say i need complete tour

**Comment by ElBananaa** [comment]
Hey, simply type `/chc tour` ingame and read what's written in the chat. Everything's explained there.

If you need anything else, feel free to keep commenting down below.
Closing this issue.

**Comment by Dionis1902** [comment]
yes i tried it
/chc tour
/chc tour start
/chc tour confirm

and after that it wants again /chc tour

**Comment by Dionis1902** [comment]
ok i fix it

**Comment by Dionis1902** [comment]
thx
