### ISSUE TITLE
1.19: Adding sound to Bungee join messages - any ways around it?

### ISSUE THREAD

**Issue by PsychoLynx** [kangarko/ChatControl#1993]
Minecraft Version: 1.19
MySQL: false
BungeeCord: true

Hi there!

I am trying to replicate a series of join messages for our network in Chatcontrol. They have previously included a small 'pop' sound (ENTITY_ITEM_PICKUP) whenever a player joins to better alert players that a new person has joined. However, I appear to be somewhat stuck and despite my best efforts I can't figure this out by myself

**What I want:**
When a player joins the network, a JSON formatted join message gets sent to every player in every server in the network along with a 'pop' sound.

**What is the problem**
I have made a JSON join message using the alertraw-command, which successfully shows across every server in the network. However, I cannot for the life of me get the sound to go with it. I have tried:

- "then sound" as (did not work on Bungee join messages)
- PlaceholderAPI playsound-placeholder (similarly didn't work in Bungee join message)
- then bungeeconsole-command to run a separate command to make the pop (I could not get bungeeconsole to run any commands on other servers, just the proxy)
- Chatcontrol packet rules to detect when a join message was sent (they were unable to detect the join messages)

I was able to use "then sound" and "then command" to play sounds in join messages not originating from bungee, but I want Bungee to handle all my join/leave messages.

Please find the debug.zip below.
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9126279/debug.zip)

Any help would be very much appreciated! I feel getting the bungeeconsole command to actually run the commands would be the easiest solution, but I will happily take less hacky solutions as well.

Kind regards,
PsychoLynx

**Comment by kangarko** [comment]
Thanks, we simply do not support this because there is not easy support in BungeeCord to play sounds as their developer rejected the feature years ago: https://github.com/SpigotMC/BungeeCord/pull/1292

So when you use "then sound" on Spigot, it will only be heard by players on the same server but not on the whole network. Same with PlaceholderAPI.
