### ISSUE TITLE
1.19: Bungee join messages showing for muted players when they're not supposed to

### ISSUE THREAD

**Issue by PsychoLynx** [kangarko/ChatControl#1994]
Minecraft Version: 1.19
MySQL: false
BungeeCord: true

Long story short, I used Chatcontrol to mute a test account of mine, but this had no effect on their bungeecord join messages showing up. The mute function has been enabled and  Hide_Join_Messages: true. I could get around this if I could check whether the player is muted using a placeholder, but I am not sure if one exists or could be made.

Any help would be welcome! The debug folder has been posted in my other issue here: #1993

Kind regards,
PsychoLynx

**Comment by BearLeonLight** [comment]
Permissions can be used to judge requests, at least that's what I currently do.

**Comment by BearLeonLight** [comment]
```
group admin
require sender perm chatcontrol.group.admin
ignore sender perm hatcontrol.silentjoin
bungee
message:
- &7{player_prefix+}{nick}{player_suffix} &f加入伺服器

group default
bungee
ignore sender perm hatcontrol.silentjoin
message:
- &7{player_prefix+}{nick}{player_suffix} &fjoin server

group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
bungee
message: 
- &7Welcome to the server &c{player} &7!
```

**Comment by PsychoLynx** [comment]
> 

Thank you, but I don't think this is helpful in this case unless you suggest I give/take a permission from a person every time they are muted/unmuted. Hence why I was asking about the "Is_muted" placeholder.

**Comment by kangarko** [comment]
Unfortunately the BungeeCord network does not see if the player is muted. We do not transmit this data over to Bungee and thus cannot regulate player-related messages on BungeeControl according to that.

**Comment by kangarko** [comment]
This is something I can consider as a future suggestion to improve.

**Comment by BearLeonLight** [comment]
> 

Can PAPI support be extended? On Bungee, something like TAB provides a link that we can use to make judgments.

**Comment by kangarko** [comment]
Thanks, yes, in the future when I have time I can pass this data from Spigot to BungeeCord and ignore muted players.
