### ISSUE TITLE
[Suggestion] Ability to change from chat to actionbar messages

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1998]
I'd like ChatControl to add a setting, where you can select, which messages are gonna be sent via actionbar instead of chat. 
For example: `actionbar-message: ["chat", "death", "join"]` 
This would make it a easier to notify players about doing something wrong and would also make the chat cleaner.

I know that you can use actionbar messages in rules, but you cannot use actionbar for messages, such as "typing too fast". My chat is already flooded with the amount of players I have, so I'd like to make it a little bit more minimalistic and cleaner.

**Comment by kangarko** [comment]
Thanks, added to roadmap.

**Comment by ElBananaa** [comment]
Hey,
I was thinking about starting working on this.
@kangarko I was wondering, what would be the best way to implement this feature in your opinion?

- Should we create a new file like `message-type.yml` in which players will be able to chose to either send bossbar messages, actionbar messages or chat messages? It would look like this:
```yaml
Channels.Disabled: chat
Channels.Disabled_World: bossbar
Channels.No_Channels: actionbar
```

- Another solution would be to do what @Teslicek describred, directly in the settings file. 
- Or, we could also make it so users would have to type `|bossbar|`, `|chat|` or `|actionbar|` at the beginning of their messages in the localization file directly.

I personally think doing this in a separate file is the best way to implement this feature as it won't only be easier for us, but also a bit more user-friendly, and it allows us to easily select which messages can be sent as bossbar/actionbar messages.

**Comment by kangarko** [comment]
I think it's just more complexity to an already complex plugin, lets keep things simple and in chat for now
