### ISSUE TITLE
Allow changing colors-only in tags, not the text

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1999]
```
match (.*)
require script '$0' != '{player}'
then warn §8[§c§l!§8] §cYou can only change the colors of the username!
then deny
```

This is the rule I was using in `tag.rs` for /tag nick, when I had `Strip_Colors: true`. It allowed users to only change colors of their name, not the actual text. For example, if my name is "Txslx", it would allow me to change tag to "&aTx&bslx", but not to "&aTes&blicek" (because Teslicek is not my name, its "Txslx").

This rule was working perfectly, but right now I'm using `Strip_Colors: false` (so that I can also match color codes in rules) and I have no idea how to make this rule work now.

Normally, adding `before replace &#[a-f0-9]{6}|&[a-f0-9k-or]` to rules works, but with `tag.rs` rule, it doesn't.

So I'm asking, is there a way to make this rule work, that will only allow users to change the colors, not the text of the tag, when option `Strip_Colors:` is set to `false`?

**Comment by kangarko** [comment]
I am sorry for the delay. You need to use the § operator directly which is the color letter that & is translated to, and then it will work normally even under Strip_Colors set to false.

`before replace &#[a-f0-9]{6}|§[a-f0-9k-or]`

![a](https://i.imgur.com/jjur6fR.png)

**Comment by Teslicek** [comment]
And what about HEX colors?

**Comment by Nextinka** [comment]
I have tested the HEX colors, and they do not work.

The output is: &#084cfbb&#175bfbi&#266afbr&#357afcd&#4489fcf&#5398fcl&#62a7fco&#71b6fcp&#80c5fc.&#8fd5fdc&#9ee4fdo&#adf3fdm

**Comment by Teslicek** [comment]
I was able to resolve this issue by using `before replace §x(§[a-f0-9]){6}|§[a-f0-9k-or]`, since `&#RGBRGB` and `#RGBRGB` are translated into `§x§R§G§B§R§G§B`.
