### ISSUE TITLE
How to disable chat log?

### ISSUE THREAD

**Issue by 50ouncebrew** [kangarko/ChatControl#20]
Just wondering how can i disable it doesnt keep showing the chat log? in the logs folder, when i delete it a new one comes

**Comment by EvilOlaf** [comment]
Stop the server.
Delete `chat.log`
`ln -s /dev/null chat.log`
Done.

:grimacing:

**Comment by kangarko** [comment]
Saving chat communication to "plugins/ChatControl/log/chat.txt" file is possible to turn off via settings.yml

Open settings.yml and set **Writer.Write_Chat_Communication** to **false**.

**Comment by 50ouncebrew** [comment]
thanks
