### ISSUE TITLE
Disconect Message Error with Last Authme Devbuild

### ISSUE THREAD

**Issue by DisTrugator** [kangarko/ChatControl#200]
There is the error that appear in console when a player disconect from my server 

> 14.04 21:29:18 [Server] ERROR Could not pass event PlayerQuitEvent to ChatControl v5.4.3 14.04 21:29:18 [Server] INFO org.bukkit.event.EventException 14.04 21:29:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-54ec0b8-1ac133e] 14.04 21:29:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-54ec0b8-1ac133e] 14.04 21:29:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-54ec0b8-1ac133e] 14.04 21:29:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-54ec0b8-1ac133e] 14.04 21:29:18 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerList.disconnect(PlayerList.java:379) [spigot.jar:git-Spigot-54ec0b8-1ac133e] 14.04 21:29:18 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1063) [spigot.jar:git-Spigot-54ec0b8-1ac133e] 14.04 21:29:18 [Server] INFO at net.minecraft.server.v1_11_R1.NetworkManager.handleDisconnection(NetworkManager.java:318) [spigot.jar:git-Spigot-54ec0b8-1ac133e] 14.04 21:29:18 [Server] INFO at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:174) [spigot.jar:git-Spigot-54ec0b8-1ac133e] 14.04 21:29:18 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot.jar:git-Spigot-54ec0b8-1ac133e] 14.04 21:29:18 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-54ec0b8-1ac133e] 14.04 21:29:18 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-54ec0b8-1ac133e] 14.04 21:29:18 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-54ec0b8-1ac133e] 14.04 21:29:18 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71] 14.04 21:29:18 [Server] INFO Caused by: java.lang.NoClassDefFoundError: fr/xephi/authme/api/API 14.04 21:29:18 [Server] INFO at kangarko.chatcontrol.hooks.AuthMeHook.isLogged(HookManager.java:239) ~[?:?] 14.04 21:29:18 [Server] INFO at kangarko.chatcontrol.hooks.HookManager.isLogged(HookManager.java:144) ~[?:?] 14.04 21:29:18 [Server] INFO at kangarko.chatcontrol.listener.PlayerListener.onQuit(PlayerListener.java:95) ~[?:?] 14.04 21:29:18 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71] 14.04 21:29:18 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_71] 14.04 21:29:18 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71] 14.04 21:29:18 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71] 14.04 21:29:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-54ec0b8-1ac133e] 14.04 21:29:18 [Server] INFO ... 12 more

**Comment by kangarko** [comment]
Hey, thank you for reporting. I have fixed it. A new release will be available tonight.
