### ISSUE TITLE
[BUG] tag.rs is using rules from command.rs

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2000]
This is a weird issue, but I will describe it anyway.

Since `/tag nick` is also a command, rules in `tag.rs` also use rules from `command.rs`. This is not necessarily a bad thing, but there is a bug that happened to us.

We use `@import global` in `command.rs` and user "Nextinka" tried to change his username using `/tag nick &#fb24bfN&#fb22b7e&#fc20aex&#fc1ea6t&#fc1b9di&#fc1995n&#fd178ck&#fd1584a`, but there is a part, which contains `d178ck`, which is caught by `global.rs` filter.

How I suggest to resolve this issue is that `tag.rs` rules will not follow `commands.rs`'s `@import global` rule, so that users can set, if they want `@import global` in `tag.rs` or not.

**Comment by kangarko** [comment]
Ty, fixed
