### ISSUE TITLE
1.18.2: After clearing the chat, use the removal information function

### ISSUE THREAD

**Issue by SheerYin** [kangarko/ChatControl#2002]
After using "/CCR CLEAR", the chat box is indeed emptied
But if you use "/{label} internal remove {message_uuid}"
The removal message will return again

Hope work: After using "CCR CLEAR"
Remove information will not restore the information of "CCR CLEAR"

Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Do not use the internal command, as it says, it's for internal purposes only. The /chc clear works as intended.
