### ISSUE TITLE
1.18.2: Small issue with mute command

### ISSUE THREAD

**Issue by Sakishima** [kangarko/ChatControl#2003]
Hello. I have an unexpected problem with the /mute command.  If you run "/mute player" without any other parameters, then the TPS drops to 8 on the server. Please check this.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9151806/debug.zip)
ChatControl-Red: 10.11.5
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Do you use mysql or not?

**Comment by kangarko** [comment]
Please also include your /chc debug file as per instructions when making a ticket

**Comment by ElBananaa** [comment]
Hey,
You are using an outdated version, please update to the latest version and let us know if the issue happens again.

**Comment by kangarko** [comment]
Let us know below if you still have that problem after updating to the version that I will release later today.
