### ISSUE TITLE
1.19: Preview Chat feature

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#2006]
Hi, i enabled the new minecraft 1.19 preview chat feature but it seems to not work with ChatControlRed, is it not possible, is it something that will be made compatible in the future?  I've checked CCR's config but couldn't find anything relevant to it.

Minecraft Version: 1.19
MySQL: false
BungeeCord: false

**Comment by TheIntolerant** [comment]
After testing on both spigot and paper, I can confirm both server software do not have support for chat preview. This was tested on a server with zero plugins. For now Preview Chat is only available on the vanilla server software.

**Comment by kangarko** [comment]
Thanks, I do not have interest in implementing this. I believe it also requires messages to be cryptographically signed and thus being able to be reported to Microsoft which we will never support.

**Comment by 00Hrtz** [comment]
> Thanks, I do not have interest in implementing this. I believe it also requires messages to be cryptographically signed and thus being able to be reported to Microsoft which we will never support.

ok, thank you.

**Comment by ElBananaa** [comment]
@kangarko Alright, so multiple users asked for this feature to be added on discord. So I did dig a bit further, and it appears this feature now seems to work fine on paper/spigot without chatcontrol, however it is completely broken when chatcontrol is enabled.

It also appears that this feature **does not require messages to be signed**. If I got it right, you only need to play with packets.
As this is something i'm not really used to, i'd rather let you have a look by yourself just to make sure about that.

Here's an opensource plugin made by another developer that show you what to do: https://github.com/LOOHP/ChatPreview
As far as I know, you'd only have to play with the CHAT_PREVIEW packet (https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/PacketType.java#L369) and the SET_DISPLAY_CHAT_PREVIEW packet (https://github.com/dmulloy2/ProtocolLib/blob/2092b8f48e1ffa2ed689eaa5eb25717afa01550e/src/main/java/com/comphenix/protocol/PacketType.java#L183) to see if the feature is enabled (The feature can be toggled in the server.properties file).
(BTW you should update ProtocolLib to the latest version available as I believe Foundation is using an old version that doesn't contains changes made to the SYSTEM_CHAT packet.

I also must say that, at first I thought this wasn't a really necessary addition, however this feature can be used to easily proofread your messages before sending them (you can even see your chat format before sending the message).

This can also be used as a last chance for users that are about to be rude in chat, as example.

**Comment by kangarko** [comment]
Thank you, I am going to re-consider this in a few weeks, right now I my plate is full with finishing recording of our training program (that I started in February but still needs some content haha)

Actually we will work on implementing NoEncryption first before chat preview, I believe that is more important
