### ISSUE TITLE
Message syntax lacks "killer_prefix" and "killer_nick" for PvP death messages.

### ISSUE THREAD

**Issue by dandyjay** [kangarko/ChatControl#2007]
In death.rs on PvP death messages there are killer variables, like in the death message:

`group entity-attack-by-pvp-diamond-sword`
`require cause ENTITY_ATTACK`
`require killer PLAYER`
`require killer item DIAMOND_SWORD`
`#then discord`
`message:`
`-&c{player_prefix}&f {nick} &7was distracted by {killer}&7's shiny [killer_item]!`

I've added prefixes and nicknames to these messages to make the more in-line with how my chat actually looks, but it only works on the player who died. I think it would be beneficial to access variables from the killer player with variables like "killer_prefix", "killer_nick", or any other "player_..." variables.

For example, here is how it looks with PvE deaths: 
![image](https://user-images.githubusercontent.com/62490812/180584808-051e9ae5-42b3-4a6e-9f81-83c3084bd07f.png)
It's pretty similar to how regular chat looks, only difference being the level and class of the player.

Here's how it looks with PvP deaths:
![image](https://user-images.githubusercontent.com/62490812/180584848-6555a75a-a1b0-424b-b18a-203e5efb9fd4.png)
The second player looks out of place compared to the player who died. 

This is not urgent by any means, but I think it would be a nice improvement.

**Comment by kangarko** [comment]
Thank you for your suggestion.

Currently we only evaluate all variables against the player who died. Plus there are a few special killer-related variables. I can take this as a future suggestion and somehow create an easy prefix or a switch somewhere for this.
