### ISSUE TITLE
1.18.2: java.lang.IllegalArgumentException: Invalid UUID string

### ISSUE THREAD

**Issue by Neeonn** [kangarko/ChatControl#2009]
Minecraft Version: 1.18.2 (git-Pufferfish-72)
MySQL: false
BungeeCord: true (Velocity)

Debug: [debug.zip](https://github.com/kangarko/ChatControl-Red/files/9173669/debug.zip)

**Comment by kangarko** [comment]
Thanks, I apology for the delay, you appear to have an outdated data.db. I will add a mechanism to ignore this, you can consider deleting that file anyways since those player data by their names wont be loaded anyways.
