### ISSUE TITLE
[Question] Channels not working

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#201]
A couple of versions back I didn't have this issue, so I am not sure if I missed anything.

```
Minecraft Version: 1.16.4 Tuinity
MySQL: true
BungeeCord: true
```

On server join I automatically join in ''read'' mode, but I actually don't join anything. When I manually join the channel it says it works, but I can't for the life of me get it to work so I can actually use the chat. Am I missing something?

![image](https://user-images.githubusercontent.com/5664135/100743516-accefc80-33dc-11eb-98ac-eabaffbe577e.png)

**Comment by Sikatsu** [comment]
![image](https://user-images.githubusercontent.com/5664135/100749050-6c737c80-33e4-11eb-9466-3c75ae976551.png)

Now that 2 players are in this global channel, the chat seems to work. After a relog when I start typing again it says I have no channel to write into. Then I have to leave the channel, join it again and wait for another player to connect so this message shows up:

`[14:48:34 INFO]: [ChatControlRed] TIP Note: Received packet DB_UPDATE from Lobby`

Once that message shows up, it works, until I relog.. so on and on..

You'd say it's related to permissions, but I did take a look on the wiki and assigned these:

![image](https://user-images.githubusercontent.com/5664135/100758602-f9700300-33ef-11eb-83f0-8d09252f6a29.png)

It also says that I have no channel to write into (even tho in /ch list it says I am in write mode), yet can't join a write channel either, since I'm in one even tho I am not:

![image](https://user-images.githubusercontent.com/5664135/100758674-0ee52d00-33f0-11eb-9485-46a36eb946f3.png)

**Comment by Sikatsu** [comment]
I did do a migration, but I will rollback to CHC 8 for now since I have zero clue on this. I double checked my permissions and configurations as well for migration.log.. I even tried setting debug to channels and it didn't tell me anything extra regarding this matter.

**Comment by NerdyBirder** [comment]
I am also having a similar issue. When i try to join a channel it says that I have joined it but then when it try to talk it says that I don't have a channel to talk in. 

I did finally get to talk in my global channel after about 2 minutes of waiting but then as soon as i tried to join another channel it kicked me from all my channels again and said i didn't have any channel to write into. I can send messages with the /chc send global command but can not actually join the channels to talk in them without a command. 

I had to go to 10.1.3 in order to get my chat to work at all.

**Comment by broken1arrow** [comment]
> I did do a migration, but I will rollback to CHC 8 for now since I have zero clue on this. I double checked my permissions and configurations as well for migration.log.. I even tried setting debug to channels and it didn't tell me anything extra regarding this matter.

Ha you add this perm chatcontrol.channel.global.write and chatcontrol.channel.global.read?

**Comment by Sikatsu** [comment]
Yeah, same for me. I would just like to have 2 channels, one for admin chat and one for global bungee chat. They should be automatically in that global channel and should never have to use the channel commands at all. Can't seem to get that to work though.

@broken1arrow Correct, I have tried both permissions as well for wildcard. I tested with and without operator as well.

**Comment by Godlycreations** [comment]
I also had to return to 10.1.3 in order for players to chat. It does kick them out at times, but at least they can get back in to chat and talk across the network as well. I am running 1.16.4 bungeecord/mysql and have 5 active channels for different groups of players.

**Comment by Sikatsu** [comment]
So maybe it's related to 10.1.4?

**Comment by DoogiePC** [comment]
This issue happens to me from 10.1.4
channels work on 10.1.3

**Comment by kangarko** [comment]
Apologies for this, I've been out of home again, pushing next release tonight — let me know if that helped! (I've tested this without being able to reproduce this now)

**Comment by Sikatsu** [comment]
This seems to have been solved.
