### ISSUE TITLE
Remove permission from op

### ISSUE THREAD

**Issue by TheMrMicky** [kangarko/ChatControl#201]
Hello,

I use ChatControl in my server and it's works great but I have a problem: I can't give only some permissions to op or remove some permission to op.

For example if I don't wan t op have access to /chc reload, I negate the permision "chatcontrol.commands.reload" in my permission plugin but op still have access to /chc reload.

So I try to disable "Op_Has_Permissions" in config and only give the permission for the commands I need, for test I give me the permission "chatcontrol.commands.list" , but I still can't access to /chc list.

Can you please fix this ? Because actually op players can't have only some permissions

Sorry for my english, i'm french

Thanks

**Comment by kangarko** [comment]
Hey, I have spot an issue in the system, thank you for reminding me. Will fix soon.

**Comment by kangarko** [comment]
Fixed, closing.
