### ISSUE TITLE
1.19: ChatControl-Red breaks url links from working.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#2010]
Minecraft Version: 1.19
MySQL: false
BungeeCord: false

Purpur dev 1732
ChatControl-Red 10.12.7
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9175807/debug.zip)

With no plugins, go in-game and type ```google.com```. I can click on the link in chat and minecraft opens it fine. 

Add ChatControl-Red 10.12.7 and start server. Type ``google.com`` and I'm unable to click on it to open the url. Tested as OP with unmodified default configs. This also happens on my main environment which _is_ heavily modified. The urls also do not work in timed message announcements.

Likewise, if I add EssentialsX while using ChatControl-Red, short links sent through Essential's private messages and MOTD work fine. 

Possibly broke in this update? (10.11.5)
https://www.mc-market.org/resources/18217/updates?page=2#resource-update-84960

> Fix | Solved links not working in chat properly again thanks to ElBananaa.

**Comment by mibby** [comment]
@kangarko Doing some testing, last working build seems to be ChatControl-Red 10.11.6. Breaks every build afterwards.

**Comment by mibby** [comment]
Caused by the regex looking for https when normally it is not required since vanilla minecraft appends http:// to normal shortened links without it? Bringing back vanilla behavior would be nice so I don't have to verbosely append https:// to every message.

https://github.com/kangarko/Foundation/pull/159/commits/4d038629b4729fc139152d3a6c366bce2ac689ba

**Comment by kangarko** [comment]
Thanks I will fix that!
