### ISSUE TITLE
1.17.1: Database Update Issue

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl#2014]
The database batch update process is never complete.
https://pastebin.com/Qgc5GhQf

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey,
Please make sure to update to the latest version available, this issue should've been solved already.
If the issue keeps happening please provide us your `/chc debug` file after updating the plugin.

**Comment by coco0325** [comment]
It is the latest version of ChatControl Red.
How to provide the debug log privately?

**Comment by ElBananaa** [comment]
Send it to support@mineacademy.org with the link to the github issue

**Comment by kangarko** [comment]
Thanks, should be fixed in the next version.
