### ISSUE TITLE
1.19: Colours are not applied to chat

### ISSUE THREAD

**Issue by MrLogano** [kangarko/ChatControl#2017]
ChatControl-Red Version: 10.12.7
Minecraft Version: 1.19
MySQL: true
BungeeCord: true (Velocity)
All plugins up to date

**Issue:**
When changing colours with the /chc color command, messages do not update to show the correct colour.

I haven't changed anything other than updating plugins to 1.19, and it no longer works.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9184608/debug.zip)

**Comment by Teslicek** [comment]
Hello, you forgot to use variable `{chat_color}` in your chat.yml format.

In newer version of ChatControl, `{message}` and `{chat_color}` are two separate variables.

**Comment by MrLogano** [comment]
> Hello, you forgot to use variable `{chat_color}` in your chat.yml format.
> 
> In newer version of ChatControl, `{message}` and `{chat_color}` are two separate variables.

Ah that makes sense, thanks for clearing that up.
