### ISSUE TITLE
[10.12.7] Rare fail to connect to channel

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2019]
There is a small bug that has been happening for a long time. It is pretty rare, but it still happens.

When I autoconnect players to one channel, sometimes ChatControl fails to connect the user to the channel, which results in:
![image](https://user-images.githubusercontent.com/87967222/180978374-722d6711-15a0-4338-a047-154f4f10ab92.png)

As I already said, this is very rare, but it is still an issue even in this version of ChatControl.

**Comment by kangarko** [comment]
Sorry for the delay. Set Show_Tips to true in settings.yml, wait until it happens again and post below the console output when that happens, it should say the highlighted logTip messages: ![a](https://i.imgur.com/gpJtwwl.png)
