### ISSUE TITLE
Essentials Nicks and ChatControl

### ISSUE THREAD

**Issue by KKosyfarinis** [kangarko/ChatControl#202]
For some reason Essentials' nicks and ChatControl don't work together.
Here's the ChatC config:

` 
 Formatter:
   
 Enabled: true

 Message_Format: '&r%pl_prefix&r{deluxetags_tag}&r %player &8>>&7%pl_suffix %message'
`

I have the latest version of vault, essentials (essentials2.x-snapshot) as well as the latest version of ChatControl.

Also using {ISLAND_LEVEL} from ASkyblock simply displays {ISLAND_LEVEL} and not the island level of a player.

Thanks in advance!

**Comment by Jason0162** [comment]
Hello KKosyfarinis,

Use %displayname instead of %player

&r%pl_prefix&r{deluxetags_tag}&r %displayname &8>>&7%pl_suffix %message

**Comment by kangarko** [comment]
Thanks to Jason for answering.

Also, if {deluxetags_tag} does not work, use %deluxetags_tag%
