### ISSUE TITLE
1.19: Placeholders in gradients (formats)

### ISSUE THREAD

**Issue by Kanin** [kangarko/ChatControl#2022]
Minecraft Version: 1.19
MySQL: true
BungeeCord: true

How might I go about using PlaceholderAPI placeholders in the "Gradient" section of formats? Nothing I've tried thus far works, thanks!

**Comment by kangarko** [comment]
Sorry but that is entirely unsupported, you need to use the Gradient: #ccccc - #44444 for example or whatever else on the entire format part, and you put your PAPI variables into the Message section instead.

**Comment by Kanin** [comment]
> Sorry but that is entirely unsupported, you need to use the Gradient: #ccccc - #44444 for example or whatever else on the entire format part, and you put your PAPI variables into the Message section instead.

So I have %color_name% and %color_name_end%, that return a hex code, how do I put these in the message section to apply a gradient to my name?

**Comment by kangarko** [comment]
Oh I see, well that won't work for now. I am afraid for the performance drain to parse placeholders in gradients where 99% users won't use it, I may add this in the future in case multiple people ask for it.

**Comment by kangarko** [comment]
Adding a toggle option to settings.yml is not ideal either, as we have over 1000+ lines and it's becoming messy.
