### ISSUE TITLE
ChatControl-Red

### ISSUE THREAD

**Issue by Denas1** [kangarko/ChatControl#2024]
why doesn't it support in itemsadder chat?

**Comment by TheIntolerant** [comment]
Please provide more context regarding what issue you are currently experiencing regardingcapability with this plugin

**Comment by ElBananaa** [comment]
Chatcontrol completely overwrites the default chat system so you can take advantage of features like the message removal feature, the channel system, etc...

**Comment by kangarko** [comment]
We do offer support to some extend though: https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/chatcontrol-red
