### ISSUE TITLE
[Suggestion] Check for more permissions in Sender_Permission

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2025]
I'd like ChatControl to check, if the player has any of the permissions suggested in `Sender_Permission`. The permissions would be separated with `|` symbol.

```Sender_Permission: permission.1|permission.2|permission.3```

In this example, ChatControl would send the format/message, if the user has any of the above permissions. Right now, using `|` doesnt work and ChatControl checks for the one `permission.1|permission.2|permission.3` permission, which of course doesn't exist.

**Comment by ElBananaa** [comment]
This can already be achieve using `Sender_Condition` and `||` which is used in java as a OR operator.

**Comment by Teslicek** [comment]
I know that this is possible with using Sender_Condition, however then it looks very bloated. This would be much simpler and easier solution.

**Comment by kangarko** [comment]
Thanks! I can consider that if more people ask for them, however that seems unnecessary right now since you have a special case which you can solve as Banana suggested.
