### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#2026]
I have found a no longer correct statement in the wiki, which should be corrected. Under "Compatibility" it still says that the Bungeecord addon is in the ZIP file. This is no longer true. I would also list Velocity there, since Chatcontrol also supports Velocity and that is certainly important for some to know. 

Accordingly, also a link where you can download the Bungeecord and Velocity extension.

Kind regards
Lorias

![grafik](https://user-images.githubusercontent.com/62625225/181920757-35c6d93f-afda-4d97-a1a4-6f594ce644f2.png)

**Comment by TheIntolerant** [comment]
Fixed
