### ISSUE TITLE
1.19: Book spying

### ISSUE THREAD

**Issue by LilShadow19** [kangarko/ChatControl#2027]
When my mods /spy books and it says click to open. It says they dont have permission to do it and unknown command. What would the command be?

Minecraft Version: 1.19
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
I can't reproduce: https://i.imgur.com/YaiZ3Zc.png and https://i.imgur.com/d8oY0ER.png

The book spying command invokes "/chc internal book X" command, make sure you configured your permission plugin to allow commands without any permission by default. That command can be called by anyone having a secret key which is the X generated by the spy message.

Matej
