### ISSUE TITLE
1.19: When we /ignore it says over and over again you are now ignore [player] but its not ignoring them 

### ISSUE THREAD

**Issue by LilShadow19** [kangarko/ChatControl#2028]
### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

Our Message Files: https://paste.gg/p/anonymous/490041bf7b2d4534acb7a289487f882d
Our Config Files: https://paste.gg/p/anonymous/fd44f811dcdf480093ea88ddec9694f5

### Information about the issue/bug

https://imgur.com/a/o2qOXEm

**Comment by kangarko** [comment]
We do not have the /unignore command at all. It's some of your other plugin causing conflict, disable ignore feature in the other plugin. I just tested without any other plugin that has /ignore and it works fine with your settings: https://i.imgur.com/Xce0vyl.png

Perhaps you need to disable it in Essentials ?

**Comment by ElBananaa** [comment]
Same thing here, I did try to reproduce the `/ignore` command issue with both mysql enabled and disabled, and I couldn't reproduce it.

As for essentials, you don't need to change anything, chatcontrol automatically overrides their ignore command when enabled.
