### ISSUE TITLE
Chat rules

### ISSUE THREAD

**Issue by BrayaanPS** [kangarko/ChatControl#2029]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

No

### Question

Hello, is it possible to use the chat rules without using the channels?

**Comment by TheIntolerant** [comment]
I can confirm, you should be able to use most rule features without channels being enabled.

**Comment by BrayaanPS** [comment]
and use the chat format without the use of channel?

**Comment by TheIntolerant** [comment]
> and use the chat format without the use of channel?

Unlike Chatcontrol-Pro, in chatcontrol-red you must use channels to format chat.

**Comment by kangarko** [comment]
You do not need to use channels, you can have one channel which you then use as the standard chat.

We even have a tutorial for that:

https://github.com/kangarko/ChatControl-Red/wiki/Channels#not-having-channels-and-only-having-1-chat-classic-system
