### ISSUE TITLE
Bow and Arrow issue

### ISSUE THREAD

**Issue by aldun** [kangarko/ChatControl#203]
Latest update 10.1.4 stops players and mobs from being able to fire arrows.. I know this sounds strange but I just tested on my server and as soon as I downgraded to 10.1.2 the issue went away.

**Comment by broken1arrow** [comment]
You need give more info, read https://github.com/kangarko/ChatControl-Red/issues/2 .

But i can confirm on 1.16.2 with  10.1.4, 10.1.3 work fine.

Edit
Try on 1.16.4 , only recommended plugins and same issue, no mysql or bungee.

**Comment by aldun** [comment]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

After upgrading to 10.1.4 players and mobs are not able to fire arrows, I have not tested with 10.1.3 but after reverting back to 10.1.2 the issue is no longer present.

**Comment by OfT3N** [comment]
Same here. 
1.16.4
Mysql and bungee - false

I cannot shoot any arrows from bows and crossbows, and i cant break blocks with crossbow

**Comment by kangarko** [comment]
Oh I know where this is coming from! I was recording a video for a student and forgot to remove that code before the release, but I already removed it from the source code. Sorry guys!

**Comment by OfT3N** [comment]
> Oh I know where this is coming from! I was recording a video for a student and forgot to remove that code before the release, but I already removed it from the source code. Sorry guys!

yeah, i see the {chatcontrolred_receiver_in_channel_<channel>} placeholder, but i still would love to have {chatcontrolred_receiver_mode_<channel>} to get if the user writing or reading this channel
