### ISSUE TITLE
1.8.8 & 1.18.2: Use Channels across Network

### ISSUE THREAD

**Issue by Neeonn** [kangarko/ChatControl#2030]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

I've installed VelocityControl, conntected every server's ChatControl-Red with MySQL and want to use some channels on all servers. Following the BungeeCord guide didn't help me.
I can't explain it so I won't really try. I'm providing some screenshots:

![image](https://user-images.githubusercontent.com/24417584/182145893-065b1fb2-3f6d-4892-8f62-8a139a8ab8c2.png)
![image](https://user-images.githubusercontent.com/24417584/182145903-c0075555-21e1-4c7b-b151-2d7b07e9b87e.png)

From Hub: [debug(1).zip](https://github.com/kangarko/ChatControl-Red/files/9233799/debug.1.zip) 
From Football: [debug(2).zip](https://github.com/kangarko/ChatControl-Red/files/9233806/debug.2.zip)

I don't know if this is an issue or just a misconfiguration so I'm asking it here.

**Comment by ElBananaa** [comment]
I'm sorry but what's the issue here exactly?
I might be missing something but everything seems fine to me. ^^

**Comment by Neeonn** [comment]
Hello, when players send messages to the staff channel from the football server, players on hub don't see it but rather because I added all bots in that staff channel on discord, the bot message gets sent instead.

**Comment by kangarko** [comment]
**You also need to set Integration.BungeeCord.Enabled to true for all of your debug files, the file did not have it enabled.**

If it then persistsn, it could be a plugin incompatibility, does it work when you remove DiscordSRV just to test?

**Comment by Neeonn** [comment]
When I set `Integration.BungeeCord.Enabled` I can see messages from every channel, I don't want that.
I also get duplicate message on hub because of the multiple bots.

Edit: Okay, I see that there is an `Bungee` option per-channel. Thank you!

**Comment by Neeonn** [comment]
![image](https://user-images.githubusercontent.com/24417584/182436451-05a93c81-d03a-4837-a57b-915e2cc79e37.png)
The only issue now is that I'm seeing doubled messages.

**Comment by kangarko** [comment]
Read this and tweak your discord srv to prevent dupes: https://github.com/kangarko/ChatControl-Red/wiki/Discord#bungeecord

**Comment by Neeonn** [comment]
I've managed to connect said channels but I can't see messages from Discord and via-versa from any channel. I've added every channel name & id in DiscordSRV's config on the only server that has it and `Integration.BungeeCord.Enabled` set to true.

**Comment by kangarko** [comment]
Have you followed our Discord integration guide? If yes and you still have that problem simply set Debug key in settings.yml to [discord] and let me know the console messages when you write on Discord but it won't appear in the game.

**Comment by Neeonn** [comment]
Please explain to me what I have to do.
I only left DiscordSRV on my Factions server. I enabled `Integration.BungeeCord.Enabled` there. I want the `staff` and `helpop` channels to be global.
I have ChatControl-Red on my other servers with Bungee and Discord enabled.

**Comment by kangarko** [comment]
Enable Integration.BungeeCord.Enabled on all servers. You also need to create "Discord_Channel_Id" option and write it for both "staff" and "helpop" channels for all servers pointing to your Discord server's channel IDs:

<img width="646" alt="Screenshot 2022-08-04 at 05 32 43" src="https://user-images.githubusercontent.com/1918426/182757253-548a8020-900f-4235-8ea3-19dcb2dac230.png">

Then only have DiscordSRV on Factions server and configure it there. 

If you still have issues then let me know what the problem is, set Debug key in settings.yml to [discord] and post me your console messages and I will help you :)

**Comment by Neeonn** [comment]
```
[10:43:29 INFO]: [ChatControlRed] [discord] Received Discord message from channel '⚽︲football-chat' which isn't linked in ChatControl. It can be linked by adding 'Discord_Channel_Id: 964446670387564584' to Channel.List in our settings.yml. Message: a
```
It's linked, but in another server's config.
Keep in mind I'm using velocity.

**Comment by Neeonn** [comment]
```
Channels: {"fac-standard": "871495151518904340", "fut-standard": "964446670387564584", "staff": "549237230431109132", "hoster": "964446670387564584", "referee": "964446670387564584", "commentator": "964446670387564584", "fcfa": "967491357998481468", "nkp": "967562363312169040", "ifk": "997484464223563831"}
```
Those are all the channels from both servers, I have DiscordSRV only installed on factions and forwarding enabled.
Everything works only on factions.

**Comment by kangarko** [comment]
> ```
> [10:43:29 INFO]: [ChatControlRed] [discord] Received Discord message from channel '⚽︲football-chat' which isn't linked in ChatControl. It can be linked by adding 'Discord_Channel_Id: 964446670387564584' to Channel.List in our settings.yml. Message: a
> ```
> 
> It's linked, but in another server's config. Keep in mind I'm using velocity.

You need to link it at your current server's config for it to work.
