### ISSUE TITLE
Awesome Concept never seen in any recent chat plugins! Channel tabs!

### ISSUE THREAD

**Issue by NoobcoreNetwork** [kangarko/ChatControl#2031]
### Summary

![Discord_uu2gzTwWr6](https://user-images.githubusercontent.com/62724418/182188362-c6947458-7cc4-48b0-b697-415b6cc071bc.png)

So I was browsing seeing what some other servers that use resource packs do, and I seen this awesome concept.

The buttons on the (latest) line of chat are clickable icons (You could make them just text without a resource pack) and clicking on them takes you into the different channels, (Plus they are ALWAYS the most recent message regardless of chatting and system messages etc, Imagine if chat control had something like this? How cool of a feature/selling point would that be! It's definitely an awesome feature that would be something none of the other big chat plugins have. I was going to go about doing lots of plugin trickery, resending the entire chat + the buttons every time a message was sent but then I thought hey, This would be amazing to have baked into chat control! If you dont have the perm for the channel show a different image or say `locked` or something like staff chat, Imagine popping into staff chat with the click of a button? and keeping player trades in one place, Would be epic!

Anyway sorry for my rant! <3

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Nothing would happen if it wasnt implemented, But it would be an amazing unique feature for a chat plugin to have, The only ones that exist (like the screenshot) are custom edge case scenarios

**Comment by kangarko** [comment]
Thanks so much! I'd have to put this into my roadmap, however it looks like they are either using Resource Packs or a client mod which we prefer to to force upon users.

**Comment by ElBananaa** [comment]
> Thanks so much! I'd have to put this into my roadmap, however it looks like they are either using Resource Packs or a client mod which we prefer to to force upon users.

@kangarko They're already aware about this, I think the suggestion here is to take advantage of the chat page system already available in chatcontrol and foundation (like the /chc tour) and to adapt it to the channel system so users could switch channel simply by clicking on buttons at the bottom of the chat.

Here's an example of plugins that offers a similar feature : https://dev.bukkit.org/projects/tabchannels

![7c9cf49f748da3963963de5159e4b568ca8f890c](https://user-images.githubusercontent.com/53318613/182404067-17ab2930-aad5-43bc-8cc2-5ed412d6aefb.gif)

**Comment by NoobcoreNetwork** [comment]
Yeah so no client mods or resource packs needed :) Just where the above image says the tab/channel names like admin/global etc, Let the user choose what content to put there, If its text, or a character image from a resource pack :) then it works for everyone

**Comment by kangarko** [comment]
Thanks for the headsup! Sure, that looks epic, I am saying that I will consider it upon new major update but these months we're busy finishing our training program instead.

**Comment by NoobcoreNetwork** [comment]
Hey! I'm still searching for a solution to do this. The main issue is, If I do find one I would have to drop chatcontrol red as what ever plugin I get made would have to handle everything inside of it's own chat. Is there any chance this can be put onto an update? I really do think this would make chat control REALLY stand out and I think almost everybody would use such a cool feature.

**Comment by ElBananaa** [comment]
Agreed with @NoobcoreNetwork. That would still be one step further to make the plugin more intuitive for players. This could also replace the current `/ch` and `/ch list` commands, and finally, this could also give players even more control when it comes to their chat when this is combined with a resourcepack, as the text for each channel could be replaced with custom buttons, as example.

Implementing this would also make it easier to implement #1910.

**Comment by kangarko** [comment]
I am open to it, but due to lack of time it is not a priority atm, but if anyone is willing to take over this I would be happy to make the source available.

**Comment by Dusreza** [comment]
This feature would make a fantastic addition to the plugin, as it would greatly enhance its overall functionality and provide users with a valuable new tool to streamline their workflow!

**Comment by Neeonn** [comment]
Would love to see this feature added!
