### ISSUE TITLE
Can I get a lifetime update whenever there is an update if I buy it once?

### ISSUE THREAD

**Issue by Angsimosaurus** [kangarko/ChatControl#2033]
Can I get a lifetime update whenever there is an update if I buy it once?

 Like spigotmc or polymart.

 Place of purchase : https://builtbybit.com

**Comment by kangarko** [comment]
We currently only give lifetime licenses :)

**Comment by kangarko** [comment]
50 years or whatever is there is considered a lifetime. I am going to send you a paper check in 2072 by a post pigeon if it expires
