### ISSUE TITLE
1.19: High CPU usage when updating from 10.12.7

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2034]
### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

Same settings, just changed .jar

10.12.7:
![image](https://user-images.githubusercontent.com/87967222/182408121-b14b00e8-ceba-4f30-bb7f-b47158f1f605.png)

10.12.8:
![image](https://user-images.githubusercontent.com/87967222/182408149-0bc5a67a-b020-4b2f-b649-8730a4ad4053.png)

**Comment by kangarko** [comment]
Please post me the full link to your spark report, or email it in private if you prefer.

We updated ProtocolLib integration to support [X] feature since it was broken under 1.19, it may be that

**Comment by kangarko** [comment]
Sent you an email. Thanks!
