### ISSUE TITLE
1.19: ChatControlRed 10.12.7

### ISSUE THREAD

**Issue by TechRoot** [kangarko/ChatControl#2035]
### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/0d93821cf0404619acd968f92de30398

### Information about the issue/bug

Nothing relatable. Just randomply appear.

**Comment by kangarko** [comment]
Thanks, I will make it print what message caused this in the next version, you can resend the error if it appears
