### ISSUE TITLE
1.19: then replace stopped working in packet.rs

### ISSUE THREAD

**Issue by SleazLee** [kangarko/ChatControl#2036]
### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

NA

### "/chc debug" output (strongly recommended)

Email -- SleazLee's Debug

### Information about the issue/bug

When Verbose is on the server logs the match, catch, & replace event to the console but no messages were ever replaced for the client.

**Comment by TheIntolerant** [comment]
Unable to reproduce using default settings,
![image](https://user-images.githubusercontent.com/48093184/182562926-8cf0ffd3-c050-48aa-a54b-fc97088e41dd.png)

What rule inside ``packet.rs`` isn't working?
Also for 1.19, make sure you are using the dev builds of [ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) and it should work.


**server setup**
```
Plugin: ChatControlRed v10.12.8
Server Version: Paper v1_18_R2
Java: 17.0.3 (Oracle Corporation/Private Build)
OS: Linux 5.13.0-21-generic
Online mode: true
Players Online: 1
Plugins: Tester v1.0.3, ViaVersion v4.4.1, ViaBackwards v4.4.1, ProtocolLib v5.0.0-SNAPSHOT-b587, LuckPerms v5.4.36, Vault v1.7.3-b131, ChatControlRed v10.12.8
BungeeCord: null
MySQL: false
```

**Comment by kangarko** [comment]
It was a bug indeed because of the new protocollib handling of 1.19 system chat packet.

That being said, fixed :)

**Comment by SleazLee** [comment]
So you're saying "It was a bug" does that mean it's no longer a bug in 1.19.1?

**Comment by TheIntolerant** [comment]
If you use version ``10.12.10`` of ChatControlRed, then this bug should be fixed.

**Comment by SleazLee** [comment]
Whoa, Awesome! That was a quick update, I didn't even see it :D Thank you guys so much!!

**Comment by kangarko** [comment]
Was a bug, no longer a bug haha
