### ISSUE TITLE
1.19.1: 'This message is not secure' warning

### ISSUE THREAD

**Issue by jnijland** [kangarko/ChatControl#2037]
### Are you using MySQL?

No

### Are you using BungeeCord?

Yes

### Information about the issue/bug

When somebody sends a chat message, a exclamation mark is put behind the chat with a warning that the message is not secure. It shows up behind every message and it looks awful. What can I do to fix this exclamation mark? 

![image](https://user-images.githubusercontent.com/9889834/182691008-e0388a84-954a-4ea9-bba0-3cdce1b56a69.png)

**Comment by ElBananaa** [comment]
This is unrelated to ChatControlRed as it appears you are using the vanilla chat with EssentialsX or a similar plugin.
This format gets removed when using the channel system, as the plugin has its own chat system taking over the vanilla one.

**Comment by kangarko** [comment]
Thanks, ignore it. I have added more info here:

https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#119-chat-reporting--this-message-is-not-secure

Oh and the (!) should disappear when you use our Channel feature in chatcontrol.
