### ISSUE TITLE
Chat returning to it's original colour after using a colour code. [suggestion]

### ISSUE THREAD

**Issue by toxinyx** [kangarko/ChatControl#2038]
### Summary

This might be a weird thing to ask, though my players have brought it up in discussions before. They'd like the ability to be able to use chat **formats** such as bold, italic, underline, etc, in their messages when they want to emphasise certain words (NOT the entire message). This would be fine to allow if all of my chat channels were the default &f - but they aren't. We have a yellow chat channel too.

I don't want to give players access to _colouring_ their messages as I'd like to keep chat as clean and readable as possible - so giving them access to &e isn't possible. 

It's probably a long shot, but is it in any way possible to add code so that the chat autocorrect back to it's original colour when doing &r (the reset colour code?) so that instead of the yellow chat going to white, it goes back to yellow?

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

If you decided not to implement it because it's too difficult or not even possible, it's really isn't a big deal and not a problem at all. Just a nifty little feature I thought I'd ask about just in case it IS possible. :)

**Comment by kangarko** [comment]
We have a secret feature for that already as an experiment, you can try this:

`&fHello [#flpc-i]&cworld[#flpc-1] this message should be back in white.`

**Comment by kangarko** [comment]
There's a rule about this feature in chat.rs also:

```
# -----------------------------------------------------------------------------------------------
# Special filter to colorize any commands appearing in the chat. This will turn "Type /help"
# into "Type &c/help" and then intelligently revert back to whatever color the message had
# previously.
#
# PLEASE NOTE that the [#flpc-X] variables are the only two special ones you can use without
# any modifications. If you have Strip_Colors on true in Rules in settings.yml, using any other
# color in the message will get it removed because the match removes colors as per this setting.
# -----------------------------------------------------------------------------------------------

match (,|\s)\/(\w+)
then replace [#flpc-i]&c$1/$2[#flpc-1]
```

**Comment by toxinyx** [comment]
OOhh okay!! 
Is the [#flpc-i]&cworld[#flpc-1] temporary? As in, would there possibly be a way to change what you have to type (e.g to make it simpler to type) when it's no longer a secret/experimental feature or would this be the final product?

It works fantastically so either way is fine - i just like knowing things and having answers :)) fantastic as always!!

**Comment by TheIntolerant** [comment]
I'm not sure exactly what you asking exactly but to give an example of a way this could be used on your server, if you add this to your ``chat.rs`` file
```
match !(.+)!
then replace [#flpc-i]&e$1[#flpc-1]
```

Then if someone were to say this in chat ``This part is normal !this part is highlighted! but this part is normal again``
Which will make the message look like this
![image](https://user-images.githubusercontent.com/48093184/183109462-69a71a9f-6880-49c2-9c4f-1fa796d59dc3.png)


Meaning any part of a users text which is surrounded by ``!`` as shown here ``!this part is highlighted!`` will have the colour changed.

**Comment by toxinyx** [comment]
> I'm not sure exactly what you asking exactly but to give an example of a way this could be used on your server, if you add this to your `chat.rs` file
> 
> ```
> match !(.+)!
> then replace [#flpc-i]&e$1[#flpc-1]
> ```
> 
> Then if someone were to say this in chat `This part is normal !this part is highlighted! but this part is normal again` Which will make the message look like this ![image](https://user-images.githubusercontent.com/48093184/183109462-69a71a9f-6880-49c2-9c4f-1fa796d59dc3.png)
> 
> Meaning any part of a users text which is surrounded by `!` as shown here `!this part is highlighted!` will have the colour changed.

thats exactly what i meant, apologies. never been very good at explaining things and im not exactly a wiz at the rules part of the plugin haha. ty though!
