### ISSUE TITLE
1.19.1: Chat Reporting

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2039]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Is the 1.19.1 player chat reporting feature already non-working or usable in 1.19.1? I see a closed issue for it previously, but no message definitively stating if it would work/not work.

**Comment by kangarko** [comment]
Thanks for the headsup, I have added a clear explanation here now:

https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#119-is-chat-reporting-enabled-i-am-worried-about-my-private-chat-leaking-to-microoft
