### ISSUE TITLE
Packets.yml is no longer working.

### ISSUE THREAD

**Issue by MSWS** [kangarko/ChatControl#204]
For some reason when I ported all my server files over to a new server, the ChatControl packet.txt didn't work. Nothing is being put into place such as blocking messages such as the world guard denial message. Please fix or tell me how to fix it!!! (Everything else however works). I've made sure that ChatControl and ProtocolLib are both up-to-date.

**Comment by kangarko** [comment]
Hey,

please make sure there are no errors in the console. Have you made any changes to the packet.txt file since the migration?

Also make sure Packets.Enabled is still enabled.

Lastly, you can just upload me your startup log to pastebin.com

**Comment by kangarko** [comment]
Assuming it's fixed, please remind me if any questions.

**Comment by MSWS** [comment]
Ah yes, apologies for not updating it. Turns out it was something with the version of the server. Had to update it to 1.8.8, not sure if this was intentional or not?

**Comment by kangarko** [comment]
I don't know, ChatControl does work with older versions as well, but ProtocolLib is pretty strict, there you have to match exactly the correct version for the respective server version.
