### ISSUE TITLE
Change to [#flpc-i] [#flpc-1] to allow multiple rule usage

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2040]
## Summary

Adding the possibility to use multiple rules that use [#flpc-i] [#flpc-1] to add colours.

For example, if I have this in ``chat.rs``, the colour is only added to one of the emotes when multiple emotes are used in a single message. It would be amazing if this wasn't the case and that all emotes would have the colour as set via the rules if multiple emotes are used in a single message instead of just once
```
match :\(
then replace [#flpc-i]&b☹[#flpc-1]

match \:star\:
then replace [#flpc-i]&6★[#flpc-1]

match \:derp\:
then replace [#flpc-i]&a(◑‿◐)[#flpc-1]
```

### Examples
Using the emotes shown above, if I were to say something like this in chat.
``test :derp: test :star: test :(``
``test :star: test :derp: test :(``
``test :( test :star: test :derp:``
This is the results
![image](https://user-images.githubusercontent.com/48093184/182772057-a99c96f0-df38-42c0-884c-4c7eee37df19.png)

It would be nice if all the emotes had their colours respectively, regardless if one or multiple emotes were used in a single message.

As shown here, it is fine if only one emote is used (using the chat.rs rules above)
![image](https://user-images.githubusercontent.com/48093184/182772637-7c1e16f5-83a9-43db-89e2-2a3adc2a9568.png) 
However the moment more than one of these types of rules is triggered in a single message, the colour is only applied to the last rule affected as shown above.

---

## What would happen if we didn't implement this feature? Why not having this feature is a problem?

Nothing major would happen if this wasn't added, just the inconvenience of some specific rules not function as intended.

**Comment by kangarko** [comment]
Thanks, going to have a look when I have time :) Should be technically possible

**Comment by kangarko** [comment]
It actually works, you must however set Stripe_Colors to false in settings.yml for this feature to work properly when manually used:

<img width="1215" alt="Screenshot 2022-08-08 at 19 01 22" src="https://user-images.githubusercontent.com/1918426/183473105-94ca5886-d0ad-4601-8d31-325908c361f5.png">

**Comment by TheIntolerant** [comment]
Ahh, okay!

Just wondering, about this setting
```yml
  # Remove colors from checked messages? Prevents bypasing filters by using colors: fu&cck.
  # [WARNING] This will remove all custom colors in the message in case it is filtered!
  # TURNING THIS OFF will break packet rules and make players able to bypass rules by using colors.
  # LEAVING THIS ON will break "then replace" if the replaced message contains colors.
  Strip_Colors: true
```
As I use packet rules, what affect does it have on packet rules? As in, would I still be able to use packet rules with this disabled or will packet rules become completely broken and non-functional?

**Comment by kangarko** [comment]
Go test it, I can't remember I am sorry. But as long as you match the colors of the message you want to catch using packet rules, then it should work even if disabled.
