### ISSUE TITLE
1.19 and 1.19.1: /msg no longer functions correctly.

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl#2042]
### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

N/A

### "/chc debug" output (strongly recommended)

N/A

### Information about the issue/bug

When you have ViaBackwards installed it adds /msg settings that seem to override CHC:
# 1.19.1 chat type formats.
chat-types-1_19_1:
  chat.type.text: <%s> %s
  chat.type.announcement: '[%s] %s'
  commands.message.display.incoming: '%s whispers to you: %s'
  commands.message.display.outgoing: 'You whisper to %s: %s'
  chat.type.team.text: '%s <%s> %s'
  chat.type.team.sent: -> %s <%s> %s
  chat.type.emote: '* %s %s'
  
This plugin causes /msg to not function cross server and overrides /msg when both are on the same server. This also makes /r no longer work.

![image](https://user-images.githubusercontent.com/30563757/182847267-cf786359-3918-4b93-b059-3322130b5622.png)
![image](https://user-images.githubusercontent.com/30563757/182847391-75ed4da9-2293-4a80-9ae4-13dea5787936.png)

**Comment by malonnnn** [comment]
Edit: rewriting this comment for clarity

I am also having trouble with /msg, but do not use ViaBackwards nor Bungee

/msg will kick both the sender and the receiver

The error received when being kicked:
[https://i.imgur.com/cxOlCHy.png](https://i.imgur.com/cxOlCHy.png)

edit #99:
i've at least narrowed it down to /minecraft:msg is triggering the crash for me, so its upstream somewhere in paper/spigot

**Comment by kangarko** [comment]
Sorry about this, testing in 24 hours

**Comment by TheIntolerant** [comment]
I tested this on 1.19.2 and was unable to reproduce this bug

```
!-----------------------------------------------------!
 Debug log generated 08.08.2022 16:48:06
!-----------------------------------------------------!
Plugin: ChatControlRed v10.12.11
Server Version: Paper v1_19_R1
Java: 17.0.3 (Oracle Corporation/Private Build)
OS: Linux 5.13.0-21-generic
Online mode: true
Players Online: 0
Plugins: Tester v1.0.3, ViaVersion v4.4.1, ViaBackwards v4.4.1, ProtocolLib v5.0.0-SNAPSHOT-b587, LuckPerms v5.4.41, Vault v1.7.3-b131, ChatControlRed v10.12.11
BungeeCord: null
MySQL: false
```
Here's a [debug.zip](https://github.com/kangarko/ChatControl-Red/files/9283636/debug.zip) file, all settings were the default except the following:
``Channels.Enabled`` and ``Private_Messages.Enabled``, it was using chatcontrol as expected when I used the
 command ``/msg``
 
 
Edit: Even after testing on 1.19.1 and using different versions of ViaVersion and ViaBackwards I could still not reproduce this bug

**Comment by malonnnn** [comment]
It may be related to paper? This commit was recently pushed:  
https://github.com/PaperMC/Paper/pull/8262

But I can't test it yet, too many players on for me to install and reboot at the moment

**Comment by kangarko** [comment]
Update to 1.19.2, most likely just caused by ViaVersion/Backwards as some other protocol kicks that we experienced.

I recommend you disable our Private_Message feature for now until these plugins resolve the kicks. The image above you posted from running the command by the way, shows that you already have it disabled, in which case the problem is unrelated to ChatControl

**Comment by Skizzles** [comment]
I do not have it disabled, Viaversion/backwards is overriding the chat messages. I do not experience a kick and my issue is separate from the other user. I am running 1.19.2 as well, ViaVersion and backwards are overriding CHC.
________________________________

**Comment by kangarko** [comment]
This is for clients connecting on 1.19.2?

**Comment by Skizzles** [comment]
> This is for clients connecting on 1.19.2?

Tested with 1.19/1.19.1/1.19.2, have not tested on anything before that but could.

**Comment by Skizzles** [comment]
Also happens with 1.18 clients

**Comment by kangarko** [comment]
I am extremely sorry, I was able to reproduce this bug by connecting a 1.12 client to a 1.19.2 server running Via plugins, unfortunately I was not able to resolve it. Could you shout a message to Via developers to add a toggle to disable handling of /tell and /reply completely? As last resort they could at least add a registration of this command to their plugin.yml inside ViaVersion.jar so that you could remove it manually (after each updating, annoying but works).
