### ISSUE TITLE
1.19 / Big error JSON serialization

### ISSUE THREAD

**Issue by TechRoot** [kangarko/ChatControl#2043]
### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.md-5.net/fuzimixetu.pl

### "/chc debug" output (strongly recommended)

[error.log](https://github.com/kangarko/ChatControl-Red/files/9262593/error.log)

chc debug breaks console.

### Information about the issue/bug

No information other than error. Got a few subservers with almost the same configuration, none of them showed this issue.

**Comment by TheIntolerant** [comment]
The JSONParseException seen here has been patched in one of the newer versions of the plugin, please update chatcontrol and this issue should be fixed.

**Comment by ElBananaa** [comment]
As TheIntolerant said, this issue has been fixed in 10.12.8. Simply update to the latest version.

**Comment by kangarko** [comment]
Let us know below if you spot it on the current release :)
