### ISSUE TITLE
1.19.1: Typing before moving kicks every players

### ISSUE THREAD

**Issue by james090500** [kangarko/ChatControl#2045]
### Are you using MySQL?

Yes

### Are you using BungeeCord?

No (Using Velocity)

### Information about the issue/bug

If you pop a message in chat and the "please move before typing into chat" thing comes up everyone gets kicked but the person typing.

**Comment by james090500** [comment]
https://www.minecraft.net/en-us/article/minecraft-1-19-2-release-candidate-1 should fix this possibly

**Comment by ElBananaa** [comment]
@james090500 This should've already been fixed by paper (and its forks) ^^
