### ISSUE TITLE
Stop rules from matching accents in words

### ISSUE THREAD

**Issue by zombwie** [kangarko/ChatControl#2047]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

my server is in a nother languge and checks false flag how do i stop that?

\b(f+(\W|\d|_)*a+(\W|\d|_)*e+(\W|\d|_)*n+(\W|\d|_)*)

that the string to block "Faen"

but it also blocks "få en"

**Comment by TheIntolerant** [comment]
In your ``settings.yml`` file, set ``Rules.Strip_Accents`` to ``false``.
![image](https://user-images.githubusercontent.com/48093184/183254789-bc844668-0e40-4fc2-a971-791ba6126c23.png)
