### ISSUE TITLE
1.19.1:  -server.properties MOTD-  modified after install

### ISSUE THREAD

**Issue by Nutmegan** [kangarko/ChatControl#2049]
### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9276958/debug.zip)

### Information about the issue/bug

After installation of ChatControlRed the server MOTD is modified. Attached is an image comparing my live server (no ChatControlRed) with my (cloned) local development server (with ChatControlRed installed/verified).
<img width="482" alt="Screen Shot 2022-08-06 at 4 23 39 PM" src="https://user-images.githubusercontent.com/9382508/183296617-bac216b7-9326-4cfd-9f54-25ae2e849453.png">

Comparison of server.properties  motd
Original
motd=\u00A72\u00A7l\u227E \u227E\u00A7a\u00DFriar\u20A2aft\u00A72\u00A7l\u227F \u227F\u00A7r\n             \u26CF\u00A77Lets Play Together\u26CF

Modified
motd=\u00C2\u00A72\u00C2\u00A7l\u00E2\u0089\u00BE \u00E2\u0089\u00BE\u00C2\u00A7a\u00C3\u009Friar\u00E2\u0082\u00A2aft\u00C2\u00A72\u00C2\u00A7l\u00E2\u0089\u00BF \u00E2\u0089\u00BF\u00C2\u00A7r\n             \u00E2\u009B\u008F\u00C2\u00A77Lets Play Together\u00E2\u009B\u008F

**Comment by Nutmegan** [comment]
This issue is a low priority for me, but I felt it was important to report because the behavior seems odd and potentially problematic for others. I'll likely just update to a new motd and avoid using any utf characters.

**Comment by Nutmegan** [comment]
Updated from version 10.12.8 --> 10.12.11   Same issue

**Comment by kangarko** [comment]
Thanks for reporting, going to test this asap

**Comment by ElBananaa** [comment]
Hey,
After running tests, I am completely unable to reproduce the issue on my own local test server.
(Running on paper 1.19.2 b117, CHC 10.12.11 & Java 18.0.2 - Windows 10)

**Comment by kangarko** [comment]
I may be that server-name key from that file was missing, in which case we attempt to add it there and save the file back

**Comment by Nutmegan** [comment]
Yes... I see this
server-name=Undefined - see mineacademy.org/server-properties to configure
So if I populate that the file won't be resaved?

EDIT: Is this a new/old option in the server.properties  file? It's not in my original file.

**Comment by TheIntolerant** [comment]
Yes, it is a new option in the server.properties

**Comment by kangarko** [comment]
Thanks, fixed!
@Nutmegan see mineacademy.org/server-properties on tutorial on what to put there

**Comment by Nutmegan** [comment]
That worked great. Thanks for the background information, I really prefer to know "why" something is not working or has to be changed. That was very helpful and I'll be sure to have our developer read your note as well.
