### ISSUE TITLE
Suggestion | List of placeholders

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#205]
Can you please make a list of plugin placeholders that can be used in other plugins (%chancontrolred_???%). For example i would like to have a placeholder like %chatcontrolred_player_is_joined_{channel}% to get true of false wether the player has joined any channel, or %chancontrolred_mode_{channel}% to get the mode (read/write/none) that the player has for this channel

**Comment by kangarko** [comment]
Can you try doing {chatcontrol_X} where X is the placeholder you'd normally use in ChatControl? I believe that should work, haven't yet tested.

**Comment by OfT3N** [comment]
> Can you try doing {chatcontrol_X} where X is the placeholder you'd normally use in ChatControl? I believe that should work, haven't yet tested.

I tried and i have only found that %chatcontrolred_channel% returns the channel what i am currently writing at

**Comment by kangarko** [comment]
I think these are the all we have right now:

```
{chatcontrolred_label_channel}
{chatcontrolred_label_ignore}
{chatcontrolred_label_mail}
{chatcontrolred_label_me}
{chatcontrolred_label_mute}
{chatcontrolred_label_motd}
{chatcontrolred_label_tag}
{chatcontrolred_label_reply}
{chatcontrolred_label_spy}
{chatcontrolred_label_tell}
{chatcontrolred_label_toggle}
{chatcontrolred_receiver_is_spying_<channel>}
{chatcontrolred_receiver_in_channel_<channel>}
{chatcontrolred_channel}
{chatcontrolred_nick}
{chatcontrolred_prefix_tag}
{chatcontrolred_suffix_tag}
{chatcontrolred_player_newcomer}
{chatcontrolred_data_<data>}
```

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Red/wiki/Variables#placeholderapi-compatible-variables

**Comment by OfT3N** [comment]
> https://github.com/kangarko/ChatControl-Red/wiki/Variables#placeholderapi-compatible-variables

I see the {chatcontrolred_receiver_in_channel_"channel"} placeholder, but I still would love to have {chatcontrolred_receiver_mode_in_channel_"channel"} or sth to get if the player writing or reading this channel

**Comment by kangarko** [comment]
Thanks, added:

`{chatcontrolred_receiver_channel_mode_<channel>}`
