### ISSUE TITLE
1.19: Emojis not being translated correctly

### ISSUE THREAD

**Issue by dollannn** [kangarko/ChatControl#2051]
### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

I have a luckperms prefix as :admin: which should display the admin icon from betterranks for itemsadder.
It works flawlessly while in chat and when directly applying it to a format as a part of the format as just :admin:
But the issue arises when I'm having the plugin translate the emoji on the fly and it does not seem to ever do that, I believe this should be seen as a bug? Anyways I'm just looking for help, I might have done something wrong. I just need this to be resolved in some way or another, all solutions are welcome!

Luckperms prefix: https://i.imgur.com/GDGWdOo.png https://i.imgur.com/15vCaIs.png

chat format: https://i.imgur.com/9ATIMjo.png

Chat: https://i.imgur.com/6JOKCA4.png

**Comment by kangarko** [comment]
What do you mean "it does not work when translating the emoji on the fly"? Thanks

**Comment by dollannn** [comment]
Om the fly means it is translating the :admin: into the admin image in real-time. It means that it is translating every message as they come in and not just adding the prefix :admin: into the format as a static part of the message. Hope this clears it up for you 😅

**Comment by TheIntolerant** [comment]
Can I suggest that this is changed
https://imgur.com/GDGWdOo

So the prefix is only ``:admin:`` instead of ``:admin: &6`` and see if that works?
You should be able to add a space after the prefix if you use ChatControls channel system instead of doing it directly in the prefix.

**Comment by dollannn** [comment]
That does not solve it

**Comment by emmanuelvlad** [comment]
I have the same issue, wondering if there is a way to re-parse a placeholder

ex:
`{luckperms_prefix}` (returning: %img_admin%) will parse the returned value to correctly display the image

**Comment by kangarko** [comment]
Thanks, I will add support for replacing variables inside variables to the next version.

**Comment by emmanuelvlad** [comment]
Just tested the latest release, it works but I need to wrap the returned value with curly braces instead of `%`.
`%` is being used everywhere else, so if I change the group's prefix with `{` `}` around it will break the other plugins using `%`

**Comment by emmanuelvlad** [comment]
Just tested the latest release, it works but I need to wrap the returned value with curly braces instead of `%`.
`%` is being used everywhere else, so if I change the group's prefix with `{` `}` around it will break the other plugins using `%`
@kangarko

**Comment by ElBananaa** [comment]
This is something that have been reported at multiple times, and I personally agree with you.
Most plugins that were using {} variables/placeholders replaced them with %%, even MVDW did it with his plugins.

This is a choice that is not only weird, but also not user-friendly at all as we've all always been used to %% placeholders.

I think finally using %% in placeholders would be a great thing.

**Comment by kangarko** [comment]
I can reopen this and include an option to double parse, if you want this. It will reduce performance but you can enable it at your own choice.

**Comment by dollannn** [comment]
Yes I'm willing to sacrifice performance for emojis

**Comment by ElBananaa** [comment]
@kangarko I think the best thing to do here is to add the double-parsing option as you said, and then get rid of it in a future version, so users have the time to switch to `%%` placeholders before completely removing brackets placeholders from the plugin.

**Comment by kangarko** [comment]
No thanks, I prefer {syntax} over %syntax%, we had like this for years, I see no reason why I should do it just because others do it.

**Comment by ElBananaa** [comment]
Well, the main reasons are that this has become a sort of "convention" on the mc plugin community and players are now all used to percent placeholders so this is definitely more user-friendly and more intuitive than brackets ones (the proof is that we've had many players opening issues because their % placeholders didn't work.)

But anyways, that's your choice ^^

**Comment by LordYarkan** [comment]
Hello, in how many days will ChatControlRed be available for 1.19.2?

**Comment by ElBananaa** [comment]
Since chatcontrol 10.13.0 1.19.2 should be fully supported, however a few previous versions should also work fine.

**Comment by LordYarkan** [comment]
> Since chatcontrol 10.13.0 1.19.2 should be fully supported, however a few previous versions should also work fine.

Ok I will try to configure it from 0 as I got a lot of errors.

**Comment by ElBananaa** [comment]
> > Since chatcontrol 10.13.0 1.19.2 should be fully supported, however a few previous versions should also work fine.
> 
> Ok I will try to configure it from 0 as I got a lot of errors.

Stop your server, delete the error.log file in chatcontrol's folder, and then start the server. Once the file is generated, please send it here. I'll have a look at it

**Comment by LordYarkan** [comment]
> 

Done, resetting the configuration fixed it. if I find a fault I'll let you know.

**Comment by kangarko** [comment]
Done, a new update will be available in an hour.

We will now properly support both %syntax% and {syntax} variables ;)
