### ISSUE TITLE
1.19.2: Bug when "Strip_Colors" is disabled

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2052]
### Are you using the latest version of the plugin available?

The plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

## Steps to reproduce Bug
1) Open the settings file
2) Set ``Rules.Strip_Colors`` to ``false``
3) Open ``/rules/packet.rs``
4) Add ``before replace (&|§)([a-f0-9k-or]|#[a-f0-9]{6})`` to the rule that replaces the /plugins message. So it looks like this
```
# Replace the /plugins message.
match ^Plugins \(([0-9]+)\): (.*)$
before replace (&|§)([a-f0-9k-or]|#[a-f0-9]{6})
then replace &2There are &6$1 &2plugins: &7$2
dont verbose
```
6) Run the command ``/chc reload``
7) Run the command ``/plugins``

---

## Expected behaviour
When the command ``/plugins`` is used, it should change the message and look like this:
![image](https://user-images.githubusercontent.com/48093184/183712443-2e1f0965-0800-4be7-8745-0f8c7d14f60e.png)

---

## Actual behaviour
When the command ``/plugins`` is used, the operator ``then replace`` seems to mess up the message.

If you look here, you can see it randomly adds this part to the message
![image](https://user-images.githubusercontent.com/48093184/183714887-89fa009d-ccbd-434e-8d3b-2498ba913491.png)

---

## Extra Notes
This was tested on a fresh install, so all files were the default files.

---

## Information about Server Setup
```
Plugin: ChatControlRed v10.12.11
Server Version: Paper v1_19_R1
Java: 17.0.3 (Oracle Corporation/Private Build)
OS: Linux 5.13.0-21-generic
Online mode: true
Players Online: 1
Plugins: Tester v1.0.3, ViaVersion v4.4.1, ViaBackwards v4.4.1, ProtocolLib v5.0.0-SNAPSHOT-b588, LuckPerms v5.4.41, Vault v1.7.3-b131, Essentials v2.19.5-dev+41-ee7c1b1, EssentialsSpawn v2.19.5-dev+41-ee7c1b1, ChatControlRed v10.12.11
BungeeCord: null
MySQL: false
```

**Comment by TheIntolerant** [comment]
This weird behaviour can be seen in other examples in the ``packet.rs`` rules, not sure if it affects other rule types but it seems ``then replace`` is kind of broken when "Strip_Colors" is disabled

**Comment by kangarko** [comment]
Will be having a look in 1-2 days.

**Comment by kangarko** [comment]
Thanks, fixed!
