### ISSUE TITLE
1.18.2 /chc color menu stopped working at some point

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2053]
### Are you using the latest version of the plugin available?

The plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

Im not sure when this happened, but `/chc color menu` was reported to not be working when selecting a color, the colors are just not shown in chat, but manually writing them in-game work still for staff.
was something changed that requires me to update my formats? or permissions? or is it just broken.

**Comment by TheIntolerant** [comment]
Have you made the changes mentioned here https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#why-are-my-chat-colours-not-getting-applied-to-chat

**Comment by kangarko** [comment]
Assuming you just need to append our variable as shown by above :) Closing, but let me know if you did that and it still won't work.

**Comment by TomLewis** [comment]
Fantastic! Thank you, I knew I had read this somewhere and didn't implement it at the time.
This is a MUCH better way of doing it as we can pick where we want this shown!

This is also the groundwork for expansion! That GUI could be dynamic for multiple things with custom placeholders.

Imagine if we had:
```
{chat_color_1}{chat_decoration_1}
{chat_color_2}{chat_decoration_2}
{chat_color_3}{chat_decoration_3}
{chat_color_4}{chat_decoration_4}
```

1. player picked color in GUI for overhead names (Using tab & CHC placeholder)
2. player picked color in GUI for badge next to their name
3. player picked color in GUI for their own username

Something like `/chc color menu 1` or in the GUI have 1-9 for 9 placeholders and clicking goes between each one. we could customize what each ones called in the languages config.

This could easily be expanded to include "preset" gradients into the GUI too for a username.

The groundwork is there!

**Comment by TomLewis** [comment]
![2022-08-10_12 00 23](https://user-images.githubusercontent.com/144046/183885536-882a7227-1481-4e20-84e1-9709af25d3dd.png)

Looks like somebody forgot about console messages when implementing this!

**Comment by kangarko** [comment]
> Fantastic! Thank you, I knew I had read this somewhere and didn't implement it at the time. This is a MUCH better way of doing it as we can pick where we want this shown!
> 
> This is also the groundwork for expansion! That GUI could be dynamic for multiple things with custom placeholders.
> 
> Imagine if we had:
> 
> ```
> {chat_color_1}{chat_decoration_1}
> {chat_color_2}{chat_decoration_2}
> {chat_color_3}{chat_decoration_3}
> {chat_color_4}{chat_decoration_4}
> ```
> 
> 1. player picked color in GUI for overhead names (Using tab & CHC placeholder)
> 2. player picked color in GUI for badge next to their name
> 3. player picked color in GUI for their own username
> 
> Something like `/chc color menu 1` or in the GUI have 1-9 for 9 placeholders and clicking goes between each one. we could customize what each ones called in the languages config.
> 
> This could easily be expanded to include "preset" gradients into the GUI too for a username.
> 
> The groundwork is there!

Thanks! Sounds like a good idea, time is a factor here as always, at this moment it's pretty limited for me so I have to postpone it to our future roadmap. But thanks and I do value your feedback!



> ![2022-08-10_12 00 23](https://user-images.githubusercontent.com/144046/183885536-882a7227-1481-4e20-84e1-9709af25d3dd.png)
> 
> Looks like somebody forgot about console messages when implementing this!

Will fix this, apologies!
