### ISSUE TITLE
JSON Message was too large!

### ISSUE THREAD

**Issue by ProAlexYTB** [kangarko/ChatControl#2054]
### Are you using the latest version of the plugin available?

The plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://pastebin.com/5XSZA7Fj

### "/chc debug" output (strongly recommended)

I send a email proalexytb@gmail.com

### Information about the issue/bug

When someone send a message he spam it in the console.

**Comment by kangarko** [comment]
Set Strip_Oversized_Json to false in settings.yml, should work on your 1.18
