### ISSUE TITLE
1.19: Books STILL Unusable.

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2057]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

As originally referenced in #1617 , this has been an issue forever. This happens both on a production 1.19 server with plugins and other things installed, as well as a completely fresh test server with a fresh install of ChatControlRed, Vault and Luckperms and absolutely nothing else. Tested on both barebones Paper and Purpur, same problem.

When you do /chc book new, you get a book and then fill out/sign it and then run /chc book save <name>. It saves properly, and then you do /chc book give <bookname> <playername> and it will give you the book. But when you right click to open the actual book, it will say invalid book tag in the book instead of what you typed. If you do the /chc book open <bookname> command, then it works for some reason. But getting the physical book is unusable.

**Comment by kangarko** [comment]
Thank you and apology for the long-standing problem, I have found the cause and confirmed it is fixed!
