### ISSUE TITLE
Double parsing placeholders from PlaceholderAPI

### ISSUE THREAD

**Issue by cbinteract** [kangarko/ChatControl#2059]
### Summary

If I use the placeholders %math_0_{prestige}*3% or %ezcolors_color_msg_{player_name}%' in my ChatControlRed formatting, they don't work, due to the formatting with the {} brackets in ChatControlRed.
Ex: 
 player-name:
    Message: '{ezcolors_color_msg_{player_name}}'
This just outputs the player name surrounded by {ezcolors_color_msg_}, when I'd like it to output the placeholder output, which would be the colorized player name.

If I could have a way of formatting and using these placeholders that'd be awesome!

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Because I think these placeholders are useful and permitted in every other plugin that supports PlaceholderAPI. This is the only plugin I've had that doesn't support them due to the {} formatting of placeholders. :(

**Comment by kangarko** [comment]
Thank you for your suggestion. Right now we don't support placeholder priority, i.e. placeholders inside placeholders won't work like this, but I can reconsider adding this in the future when I have more time.
