### ISSUE TITLE
[PRO VERSION] Prefix with color AND formatting code error

### ISSUE THREAD

**Issue by BabelSolea** [kangarko/ChatControl#206]
when i put in permissions prefix like &0-9 a-f or &r - that working true

when i put prefix with formatting like &k &l &m &n - that working true

but when i put prefix like &e&l &2&k ... etc

that change ONLY last part of chat-code:

put &e&l >>> show &l
put &2&k >>> show &k

what i did wrong or that is bug?
if that bug - please fix that (my little donate-option cry with that bug)

**Comment by kangarko** [comment]
Hello,

where do you put the prefix? To your group in your permission plugin, e.g. PermissionsEx?

**Comment by BabelSolea** [comment]
PermissionsEx
tried:
/pex user USER prefix &e&k
/pex user USER prefix &k&e

personally prefix, not group prefix.

**Comment by kangarko** [comment]
I see. Please make sure your players have 'chatcontrol.chat.format.bold' and 'chatcontrol.chat.format.magic' permissions.

Or just give them 'chatcontrol.chat.format.*' to enable all colors.

If you have essentials, also make sure they've got 'essentials.chat.format' and 'essentials.chat.color' if you want to allow them to type the colors in chat.

**Comment by BabelSolea** [comment]
i dont wanna give players permissions to that chat formats.

any way i with OP and all perms can enter &e&k in chat but cant do same in prefix.

i need possible to give players &color&format prefixes only.

(dont wanna give to players permissions to formatting chat messages to dont get unreadable eyes pain chat flow)

**Comment by kangarko** [comment]
Hey, I found it!

In interactive chat, only the last color is transfered. So, I recommend you type the {player} placeholder right after the {pl_prefix} in your chat format in chat.yml. Make sure to remove the part where the {player} is, so it is not displayed twice.

![img](https://i.imgur.com/S7yplZJ.png)

**Comment by BabelSolea** [comment]
yeah few mins i upload my files

**Comment by BabelSolea** [comment]
[https://cloud.mail.ru/public/BoKi/YZDccj2R3](url)
[https://cloud.mail.ru/public/12NC/oJYUofNqM](url)
there chat.yml and settings.yml
ChatControlPro v7.3.2 spigot 1.11.2

**Comment by kangarko** [comment]
Hey,

In interactive chat, only the last color is transfered. So, I recommend you type the {player} placeholder right after the {pl_prefix} in your chat format in chat.yml. Make sure to remove the part where the {player} is, so it is not displayed twice.

Just insert the {player} placeholder right after the prefix placeholder in one part.
![img](https://i.imgur.com/S7yplZJ.png)

**Comment by BabelSolea** [comment]
ok i will do like ure said =)

**Comment by kangarko** [comment]
Closing. Feel free to comment below if you have any more questions.
