### ISSUE TITLE
1.19.2: Chatting causes everyone to be kicked with validation failure message.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#2060]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

Emailed.

### Information about the issue/bug

ChatControl-Red v10.12.11
Paper dev 125 & Purpur dev 1759 (Spigot 1.19.2)

Possibly caused by chat changes in https://github.com/PaperMC/Paper/commit/954b3fb7d5215acba1c736ba88174a9de3642ce4 (https://github.com/PaperMC/Paper/issues/8275#issuecomment-1212573823)

Whenever someone chats publicly, all players are kicked from the server with ``Chat message validation failure``. Removing ChatControl-Red, players can chat fine without kicks. Using EssentialsX-Chat, players can chat fine without kicks.

**Edit: See for more info. https://github.com/PaperMC/Paper/issues/8275#issuecomment-1213611642 Possibly just a conflict with AntiPopup when connecting behind a proxy.**

**Comment by andy01745** [comment]
I have tested this. You will need to go over every plugin you have installed. Cause when I removed all my plugins. This problem went away. I updated them like these for example.
![image](https://user-images.githubusercontent.com/84942293/184497035-8262bf9c-8007-4302-a072-413ad829cfbd.png)

As you can see here the issue has gone. 

![image](https://user-images.githubusercontent.com/84942293/184497132-fd7c92f3-8df9-42b5-b98f-7362d2d1dc67.png)

**Comment by kangarko** [comment]
Thanks, investigating. 1.19.2 addressed a problem like this, but I assume you are on the latest Paper anyways.

**Comment by kangarko** [comment]
It's caused by AntiPopup, I just reproduced it. Unfortunately I don't have a solution for that at the moment. On the good note, spying and chat reporting is disabled when using ChatControl since we send all messages as system chat.
