### ISSUE TITLE
READ ME FIRST | Version 10.13.0 Released Aug 13 At 19:10 CET

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#2061]
**This version contains an important issues that seems to break every command containing 2 or more arguments, like `/chc tag`.**

A fix was released on our official discord server. In order to download it, please follow these steps:

- Join https://discord.gg/SAYYKRvjQZ
- Verify your purchase on https://app.mineacademy.org/discord-verify
- See the pinned messages in the #chatcontrol channel once verified

**Comment by kangarko** [comment]
I am sorry, going to investigate asap.

**Comment by ElBananaa** [comment]
@kangarko I already fixed it in https://github.com/kangarko/ChatControl-Red-Src/pull/40

**Comment by kangarko** [comment]
Sounds good thanks :) Will upload tonight in a few hours!
