### ISSUE TITLE
1.19.2: Please

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#2062]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I've spent the last 16 hours trying to figure out what was causing the problem with not being able to run commands on my server after updating CCR and Paper, only to find i have to use a website that's broken to verify on a discord server that i never even knew existed until today because i was given the impression all support was provided over github.

Your verification site is broken because it refuses to accept that my Discord is already successfully connected to my buitbybit account, the same account i purchased CCR on. 

I'm disappointed i've had to go through all this and waste so much time having to get verified on Discord when i should just be able to download the update on builtbybit.

Please please can someone answer my email which i've sent to support and verify me on Discord so i can get this command issue fixed once and for all, i've had a long 4 days of troubleshooting broken plugins causing my server to be shutdown and i'm emotionally drained and have run out of patience.

**Comment by 00Hrtz** [comment]
Also it's not just breaking commands by removing the spaces, it's also removing the spaces from whatever you type, example:

`Hi how are you` ends up `Hihowareyou` and `/gamemode creative` ends up `gamemodecreative`

**Comment by ElBananaa** [comment]
Hey,
The reason the update is not publicly available is that I don't have access to Kangarko's BBB account to publish updates.
Please add me on discord `Bananaa#1471` I will send you the update privately until Kangarko finally approves you.

In the meantime, I'd simply suggest reverting to the previous version.

**Comment by 00Hrtz** [comment]
thank you, i can provide you evidence.
