### ISSUE TITLE
If I don't use auto mode, can't use private messages?

### ISSUE THREAD

**Issue by mc-eia** [kangarko/ChatControl#2063]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

bukkit settings.yml line489
Auto_Mode: false

when set like this 

When this is set, a message like this appears even if the contents are included in Private Messages.
(ex. /msg user test)

'The conversation mode is disabled! Set Private_Messages.Auto_Mode to true in settings.yml to enable.'

If I use it as an example, the message "test" should arrive to the user, but I get an error message.

So if you don't use auto mode then private messages aren't available at all?

**Comment by ElBananaa** [comment]
Hey,
Thank you for reporting this.
This should be fixed in the next update.
