### ISSUE TITLE
.network domains not recognized as an URL

### ISSUE THREAD

**Issue by Johandrex** [kangarko/ChatControl#2065]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

Yes

### Information about the issue/bug

Using version 10.13.1. The problem is that .network isn't recognized as an domain name when posting URL's in the rules folder. The players are unable to click on the links.

Example command-rule:
match ^/(hi)
then replace optifine.net optifine.com optifine.network

The first two links are clickable, the third isn't

**Comment by kangarko** [comment]
Thanks, solved by Banana!
