### ISSUE TITLE
Upgrade from 12.11 to 13.0

### ISSUE THREAD

**Issue by ProAlexYTB** [kangarko/ChatControl#2066]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hello, when i'm on version 12.11 and i execute a command who need permission is ok, but when i upgrade to 13.0 he told me to same command the unknown command, what can i do?

**Comment by ElBananaa** [comment]
Hey,
Please read #2061
