### ISSUE TITLE
1.19.2 Big Party Chat problem

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#2067]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hi, I have a massive problem. I've been looking for a party plugin to work with a party channel using ChatControlRed only, the problem is as follows.

"Party"

This option will make channel messages only go to players in the same party of a third party plugin. You can combine this option with Range.

Available parties are:

    factions-faction: Factions, FactionsUUID or FactionsX players in the same faction. **not looking for land claim plugin and or  out of date.**
    plotsquared-plot: PlotSquared players in the same plot. **not a party plugin**
    towny-town: Towny players in the same town. **not looking for land claim plugin**
    towny-nation: Towny players in the same nation. **not looking for land claim plugin**
    towny-ally: Towny players in the same ally. **not looking for land claim plugin**
    mcmmo-party: mcMMO players in the same party. **incompatible with my anti cheat plugin which i have no interest in dumping**
    lands-land: Lands players in the same land. **not looking for land claim plugin**

The only Party plugin that i can find that's somewhat good is `Parties` but your Wiki states it doesn't support party chat.

So i'm stuck without a compatible party plugin that ChatControlReds compatible with.

**Comment by 00Hrtz** [comment]
Nevermind, i've decided to explore Towny.

**Comment by 00Hrtz** [comment]
OK so i've checked out Towny and it doesn't allow for party member only channels with CCR so Towny is useless to me. Is there no way you can make a party plugin like `Parties` compatible with a party chat channel. Noticed a few other people have asked for this in the past.   https://www.spigotmc.org/resources/parties-an-advanced-parties-manager.3709/

**Comment by kangarko** [comment]
Thanks for your suggestion, I can consider it when I have more time. Right now we only support listed party plugins in the wiki as you noted
