### ISSUE TITLE
1.18.2, ChatControl Red 10.13.0 breaks ALL commands even in console and breaks ALL spaces when talking in chat.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2068]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

I cant, you broke using all commands.

### Information about the issue/bug

Updated from ChatControl-Red-10.12.9 to ChatControl Red 10.13.0

1. ALL spaces are removed when people type in chat.
2. ALL commands have been fully broken, even in console.

Cant run any debugging as I literally could not do anything, not even as OP, so I backdated to 10.12.9.

![2022-08-15_11 41 03](https://user-images.githubusercontent.com/144046/184622755-0a776eb8-8df1-4314-b9a1-2b655aa8865a.png)

**Comment by ElBananaa** [comment]
See #2061 for a fix

**Comment by TomLewis** [comment]
Was this pushed to a later update? So all I would do now is update the plugin?

**Comment by ElBananaa** [comment]
This was merged in 10.13.1.
Simply read the update logs, they tell you what changes were made.
