### ISSUE TITLE
1.19.2. plugin version: 10.13.0 breakes commands for other plugins

### ISSUE THREAD

**Issue by ArcaneLegend1** [kangarko/ChatControl#2069]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

when you put in a command like /lp editor it would remove the space and give back an error saying /lpeditor with an arrow it only started when i updated the plugin and when i removed it and moved back a version it stoped

**Comment by kangarko** [comment]
Will be fixed in 30min

**Comment by kangarko** [comment]
Or 60min depending how fast I implement one more feature for todays release :)

**Comment by ArcaneLegend1** [comment]
brill you are the best and fast reply thank you
