### ISSUE TITLE
I bought the plugin and I can't activate it

### ISSUE THREAD

**Issue by FITFC** [kangarko/ChatControl#2070]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

I bought the plugin I already used the "chc tour confirm" I read the terms, but I didn't understand how to activate this plugin, I don't know if it's a bug or if I'm having trouble understanding (I'm not Anglophone and I don't have this language as official in my country)

**Comment by TheIntolerant** [comment]
If you go to https://github.com/kangarko/ChatControl-Red/wiki/Terms you will find the command.
![image](https://user-images.githubusercontent.com/48093184/184958508-551e3932-aaef-4388-bdb6-1b60d566b461.png)

**Comment by TheIntolerant** [comment]
If you have any more issues just comment below :)
