### ISSUE TITLE
1.19: Create special permissions for timed.rs

### ISSUE THREAD

**Issue by FITFC** [kangarko/ChatControl#2071]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

No

### Question

Hello, I use timed.rs to send an automatic message every x minutes, I would like to know if it is possible to create a rule/group to hide this broadcast for certain players

**Comment by TheIntolerant** [comment]
Yes this is possible and can be done a few ways depending on preference, for more info go to the wiki [here](https://github.com/kangarko/ChatControl-Red/wiki/Messages)

Here are two examples one using ``require receiver script`` and ``require receiver perm``
```
group staff_message1
delay 1500 seconds
require receiver script "{luckperms_has_groups_on_track_staff}" == "yes"
message:
- this message is only shown to users who are on the track "staff" in luckperms



group staff_message2
delay 1500 seconds
require receiver perm random.perm.example
message:
- this message is only shown to users who have the permission random.perm.example
```

**Comment by kangarko** [comment]
Thanks to TheIntolerant for helping out, let us know below if you still need help!
