### ISSUE TITLE
lag and crash

### ISSUE THREAD

**Issue by xcoolerboy** [kangarko/ChatControl#2072]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://timings.aikar.co/dev/?id=77380e6c214c4678b32c86b44c2fa422

### Information about the issue/bug

hey i have question why chat control should lag and crash my server?
everyday my spigot server getting huge lag and after that  crash i dont know for what reason but i was able to get timings before it get crash
https://timings.aikar.co/dev/?id=77380e6c214c4678b32c86b44c2fa422

**Comment by ElBananaa** [comment]
Hey,
Please update the plugin and make sure to enable async features in the settings file.

If you have an important playerbaseand/or use the plugin on multiple servers, you should consider switching to a mysql database. Finally, please provide us a spark report, the timings reports are not very useful here.

**Comment by kangarko** [comment]
Please update your plugin. If it still happens, please include your /chc debug as I need to look at what settings you are having.
