### ISSUE TITLE
Mention support nicknames starting with a special character

### ISSUE THREAD

**Issue by emmanuelvlad** [kangarko/ChatControl#2073]
### Summary

Allow special characters to be parsed in mentions.

Ex:
I have a Bedrock player named: `.PlayerUsername`

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

You cannot mention Bedrock players (if using Geyser with the default prefix `.`)

**Comment by kangarko** [comment]
Thanks, does not this work already? You will probably need to disable Prefix in Sound_Notify so that we can fully parse the username because probably the plugin thinks that the dot is a prefix

**Comment by emmanuelvlad** [comment]
I have `Require_Prefix: ''`

**Comment by emmanuelvlad** [comment]
And it doesn't work 😅 @kangarko

**Comment by kangarko** [comment]
Thanks, I found and fixed the bug!
