### ISSUE TITLE
BentoBox support for Party

### ISSUE THREAD

**Issue by emmanuelvlad** [kangarko/ChatControl#2075]
### Summary

BentoBox Island members support for `Party` option

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

BentoBox is a very popular plugin for many gamemodes (such as SkyBlock, OneBlock...), would be nice to have this compatibility

**Comment by kangarko** [comment]
Thank you, I did it! Description under the Party option is here: https://github.com/kangarko/ChatControl-Red/wiki/Channels

If you appreciated my support please drop a quick review when you can :)
