### ISSUE TITLE
Changes to item.yml file

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2076]
### Summary

Added some minor changes to ``item.yml`` to make it easier to customise by adding brackets or removing them etc

Also includes the fix shown in #1921

Changes to this file are shown in the pastebin link below
https://pastebin.com/40zvL020

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Nothing really, the only issue would be people having a harder time customising it to their own needs.

**Comment by TheIntolerant** [comment]
Okay so I didn't test this and broke something, so imma close this as I am a bit busy now and will reopen later when fixed lol

**Comment by kangarko** [comment]
Thank you so much :))
