### ISSUE TITLE
1.8.8 & 1.18.2: Discord Integration

### ISSUE THREAD

**Issue by Neeonn** [kangarko/ChatControl#2077]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### "/chc debug" output (strongly recommended)

[football-debug.zip](https://github.com/kangarko/ChatControl-Red/files/9394427/debug.3.zip)
[hub-debug.zip](https://github.com/kangarko/ChatControl-Red/files/9394429/debug.4.zip)

### Information about the issue/bug

I've installed DiscordSRV and setup everything related to discord on my hub server (1.18.2). If I want to see messages from the football server in staff chat on discord (fut-staff/hub-staff/fac-staff channels) at least one player has to be on the hub server. If there is no one on the hub, I can only see messages from those channels in game.

**Comment by kangarko** [comment]
Yeah unfortunately the way BungeeCord communication works requires at least one player on the server. BungeeCord then broadcasts the message to your main server which has Discord and that broadcasts it elsewhere. There are plans how to workaround this issue.
