### ISSUE TITLE
[1.18.2] ChatControl Red does not start.

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#2078]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/9c3c0d6b6bf54c0ea817ab13b2215bf2

### Information about the issue/bug

I tried to start ChatControl Red on [Arclight](https://github.com/IzzelAliz/Arclight) server but it does not start. Tried to open an issue on their github but they said its plugin related not Arclight.

**Comment by ElBananaa** [comment]
Hey,
Chatcontrol is a spigot plugin and it is only desgined to work with spigot's api and some of it's forks (like paper or purpur).

We do not support other server softwares yet and I don't think this is something planned as they are too many different ones that are barely used.

**Comment by ghost** [comment]
Hey! Thanks for the response. Arclight is based on spigot so i don't know whats the real problem. :( Any chance to solve this? :/ Thanks in advance!

**Comment by ElBananaa** [comment]
I have honestly no idea.
I'd suggest you try to download chatcontrol's latest version again, just to make sure the jar file isn't corrupted, if the issue persists, please wait for @kangarko to have a look at it.

**Comment by ghost** [comment]
Thank you very much! The jar is ok because I tested it on paper and it worked. I'll wait for @kangarko.

**Comment by kangarko** [comment]
It looks like a corrupted jar, I redownloaded it from BuiltByBit just to be sure but it works on my end on 1.19 paper.

Try redownload, if it still does not work then it's incompatible with your fork unfortunately, looks like the fork is scanning the jar in some way making it incompatible :/

**Comment by ghost** [comment]
> It looks like a corrupted jar, I redownloaded it from BuiltByBit just to be sure but it works on my end on 1.19 paper.
> 
> 
> 
> Try redownload, if it still does not work then it's incompatible with your fork unfortunately, looks like the fork is scanning the jar in some way making it incompatible :/
> 
> 
> 
> 

Thanks for the response! I try to contact the Arclight dev about this.
