### ISSUE TITLE
Banmanager is not a soft depend

### ISSUE THREAD

**Issue by jaboy** [kangarko/ChatControl#208]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Hello

Having banmanager installed, when the first player joins the server, the follow warning will be shown in the console:

```
[12:04:37] [Server thread/INFO]: weboy[/x.x.x.x:17282] logged in with entity id 174 at ([Plots]-762.8506461074118, 65.0, -3053.791924393714)
[12:04:37] [Server thread/WARN]: [ChatControlRed] Loaded class me.confuser.banmanager.common.api.BmAPI from BanManager v7.2.2 which is not a depend, softdepend or loadbefore of this plugin.

```

**Comment by broken1arrow** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true
> 
> Hello
> 
> Having banmanager installed, when the first player joins the server, the follow warning will be shown in the console:
> 
> ```
> [12:04:37] [Server thread/INFO]: weboy[/x.x.x.x:17282] logged in with entity id 174 at ([Plots]-762.8506461074118, 65.0, -3053.791924393714)
> [12:04:37] [Server thread/WARN]: [ChatControlRed] Loaded class me.confuser.banmanager.common.api.BmAPI from BanManager v7.2.2 which is not a depend, softdepend or loadbefore of this plugin.
> ```

Gets this from many different plugins and not specifically red. If I'm not wrong, there's no major error.

**Comment by jaboy** [comment]
If it was not "wrong" then it would not be shown 🤔 

The plugin will still work and will be able to access banmanagers api without having ban manager marked as a softdepend, but considering that this plugin is going to be premium on spigot in a while, it would not look very professional that the author didn't add (literally) 1 word to the plugin.yml inside the jar to mark it properly.

**Comment by broken1arrow** [comment]
> If it was not "wrong" then it would not be shown 
> 
> The plugin will still work and will be able to access banmanagers api without having ban manager marked as a softdepend, but considering that this plugin is going to be premium on spigot in a while, it would not look very professional that the author didn't add (literally) 1 word to the plugin.yml inside the jar to mark it properly.

I it soo easy he will fix it :) 

I get this from red (but I don´t see it as big issue so long it work :) )
02.12 18:43:47 [Server] WARN [ChatControlRed] Loaded class me.angeschossen.lands.api.integration.LandsIntegration from Lands v4.12.1 which is not a depend, softdepend or loadbefore of this plugin.

Have tons of other similar on my server,have read it somewhere that there is nothing to care about (can be on paper on DC when someone asked about this).  
02.12 18:43:28 [Server] WARN [mcMMOHorse] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend, softdepend or loadbefore of this plugin.

02.12 18:43:26 [Server] WARN [ChestSort] Loaded class me.clip.placeholderapi.expansion.PlaceholderExpansion from PlaceholderAPI v2.10.9 which is not a depend, softdepend or loadbefore of this plugin.

02.12 18:43:39 [Server] WARN [mcMMO] Loaded class us.myles.ViaVersion.api.protocol.ProtocolRegistry from ViaVersion v3.2.0 which is not a depend, softdepend or loadbefore of this plugin.

02.12 18:43:49 [Server] WARN [PlaceholderAPI] Loaded class com.gmail.nossr50.mcMMO from mcMMO v2.1.154 which is not a depend, softdepend or loadbefore of this plugin.

02.12 18:43:26 [Server] WARN [ChestSort] Loaded class me.clip.placeholderapi.expansion.PlaceholderExpansion from PlaceholderAPI v2.10.9 which is not a depend, softdepend or loadbefore of this plugin.

**Comment by kangarko** [comment]
Spigot is getting annoying with these messages nowadays :) I will hide this
