### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#2080]
### Summary

It would be great to have an public api as an maven repository

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

In general, it is difficult for servers or projects with multiple developers to work properly on a project if they all need to have the jar downloaded and imported as a library. Maven helps here. They can all work with the same version and don't need to have the plugin on their local machines. It would suffice here if only the api was accessible with the appropriate javadocs to write extensions specifically for your own server. 
There are features that are too specific and are not accepted, such an extension would already make a difference for projects. 
On the other hand, for plugin developers who want to hook into the plugin for programming, this would also be very helpful.

**Comment by kangarko** [comment]
Thank you, a public API is definitely something we can consider adding. Unfortunately I can't give you an ETA right now. However, you can email matej(at)mineacademy.org and I'll add you to buyers list so you can access the full JAR (with the disadvantages as you mentioned).

**Comment by Lorias-Jak** [comment]
Hey there, its been a while since I asked for an open api accessable through Maven / Gradle. 

I know, no ETA and you have much to do with the Chatcontroll 11 update. 
I'm just curious if this is still on your list or not

**Comment by kangarko** [comment]
Great suggestion! Well right now we ship the plugin completely unobfuscated, everything is accessible plus there is an entire api package. If you are a developer and have a plugin published at a popular site, let me know your plugin URl and your builtbybit user ID and I give you free access to chatcontrol

I can look into taking out stuff into api package and publishing to maven tho, but I've been really short pressed on time with all the work plus given these plugins are a hobby thing now, life changed a lot after 11 years

**Comment by Lorias-Jak** [comment]
I'm currently working on 2 Plugins. One of them is my own. The other one is a bigger one, but I'm only helping there if I have enough time.

* [LoriTime](https://modrinth.com/plugin/loritime), my own one
* [BetonQuest](https://www.spigotmc.org/resources/betonquest-all-your-adventure-supplies-versatile-quests-in-depth-conversations.2117/), where I'm helping out if there is any time left during the week.

BBB: aegorin.290210

In case you're interessted in a few details. 
* I'm coding since 2021. Learned most of the stuff by my self. Had help from Wolf2323 from a certain point (Core-Dev of BetonQuest). 
* LoriTime is the first own plugin that i uploaded. At the moment I'm doing some code-quality stuff that isnt pushed yet (pmd, spotbugs, java docs). 
* Currently saving some money to take your nms course ;) 

If you have any questions, feel free to ask :)

**Comment by kangarko** [comment]
Cool! It says you already own a license for ChatControl and Velocity, so you should be able to download the jar and use it as a systemPath dependency (if using Maven, not sure how with Gradle). You will then be able to access all methods and classes inside of the plugin. Can you confirm it works for you?

**Comment by Lorias-Jak** [comment]
Sory for the late response! Got sick and was not able to test it. Yeah its working pretty good, thank you!
