### ISSUE TITLE
1.19.2: Server kick "Chat message validation failure" when using "/chc rule create"

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2081]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

#### To reproduce this issue:

1) Type ``/chc rule create``
2) Type ``test`` (this can be anything)
3) Type ``global`` (This can be "chat" or "sign" it doesn't matter)
4) Type ``no`` (you can type "yes" too for the same result)
5) Type ``exit``
6) Move around in-game
7) Type something in chat.
8) You should then be kicked with the message saying "Chat message validation failure".

**Comment by TheIntolerant** [comment]
Note: this was first reported by a user on discord so I don't have a ton of info about this specific issue. This was also tested on a fresh install of the plugin

One potentially useful bit of information is that, if you follow all these steps again but skip ``6`` and don't move at all throughout the whole process, it seems to not kick people oddly enough.

**Comment by kangarko** [comment]
Sorry I am unable to reproduce: https://i.imgur.com/DELd0vo.png

The next version will include a new option at Channels.Prevent_Spying, try leaving it on false to see if the problem goes away. If ViaVersion is installed it may be the cause of it, then the key needs to stay disabled in that case.

**Comment by LeehamElectronics** [comment]
Also getting this issue on my network.

**Comment by LeehamElectronics** [comment]
I fixed this by installing [AntiPopup](https://www.spigotmc.org/resources/%E2%9C%A8-antipopup-no-chat-reports-and-popup-%E2%9C%A8.103782/) and [NoEncryption](https://www.spigotmc.org/resources/noencryption.102902/).
