### ISSUE TITLE
[1.19.2] [10.13.4] Option Channel.Prevent_Chat is missing/not working in settings.yml

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2084]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[settings.zip](https://github.com/kangarko/ChatControl-Red/files/9444642/settings.zip)

### Information about the issue/bug

Already explained in the title. There is no `Channel` setting in settings.yml, only `Channels`. And even after inserting `Prevent_Chat: true/false` manually under `Channels` section, it did not fix the issue.

**Comment by TheIntolerant** [comment]
I believe this is a typo
![image](https://user-images.githubusercontent.com/48093184/187211805-35c1213d-4a53-4c23-8cc1-25deca2bf60a.png)

Try looking for this setting instead
![image](https://user-images.githubusercontent.com/48093184/187212077-e3e23233-9fd3-463f-a932-c732929b1967.png)

**Comment by Teslicek** [comment]
Alright, after setting the `Prevent_Spying` to `true`, it resolved the issue. Thanks.

**Comment by kangarko** [comment]
Sorry, was just a typo, it's Prevent_Spying :)
