### ISSUE TITLE
Hook with Advanced Vanish

### ISSUE THREAD

**Issue by RhinoCD** [kangarko/ChatControl#2085]
### Summary

Please hook with this plug-in here and prevent players from messaging those in vanish:
https://www.spigotmc.org/resources/advancedvanish.86036/

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Without this feature, players are able to message all staff in vanish, and it even tab completes the staff members name even though they are vanished.

**Comment by ElBananaa** [comment]
Hey,
I did try to work on implementing support for this plugin, however it seems like maven can't resolve the dependency.
I don't know if that's an issue on maven, jitpack or the plugin itself tho.

Do you know if they have another repository available?

**Comment by RhinoCD** [comment]
iv linked this to an issue I opened over at advanced vanish, hope you could work with them or vise versa to get this resolved! ❤️

**Comment by ElBananaa** [comment]
> iv linked this to an issue I opened over at advanced vanish, hope you could work with them or vise versa to get this resolved! ❤️

Alright thanks!
I'm not the author tho, @kangarko is ^^

BTW, you can close this issue, i'll answer on the previous one you opened on their github

**Comment by RhinoCD** [comment]
ah i’m quite dumb, alright thank you!

**Comment by ElBananaa** [comment]
@RhinoCD I was talking about the issue you opened on their github, not this one xD

**Comment by RhinoCD** [comment]
ohhh 😅😂

**Comment by quantiom** [comment]
> Hey, I did try to work on implementing support for this plugin, however it seems like maven can't resolve the dependency. I don't know if that's an issue on maven, jitpack or the plugin itself tho.
> 
> Do you know if they have another repository available?

I updated the repository, you can find it here https://github.com/quantiom/AdvancedVanish#maven

**Comment by ElBananaa** [comment]
Alright @RhinoCD could you please add me on discord `Bananaa#1471` I'll provide you a test build there.

**Comment by RhinoCD** [comment]
alright I dmed you :D

**Comment by kangarko** [comment]
Thanks, will get added to the next version thanks to Banana!
