### ISSUE TITLE
1.19.2:Hover message does not show up with custom variables

### ISSUE THREAD

**Issue by MatinHQ** [kangarko/ChatControl#2086]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

No error

### "/chc debug" output (strongly recommended)

emailed to [support@mineacademy.org](mailto:support@mineacademy.org) 

### Information about the issue/bug

The title clearly says the issue I just created a custom variable called {server_handle} and it works fine however when I hover my mouse over it doesn't show the hover message and also nothing happens when I click on it

/chc info variables Matin_Dark {server_handle}
![image](https://user-images.githubusercontent.com/22664859/187469228-269f4c95-f649-4b21-991f-dfc297b3f538.png)

**Comment by ElBananaa** [comment]
Hey,
Could you please provide us the variable file here?

**Comment by MatinHQ** [comment]
```
Type: FORMAT
Key: "server_handle"
Value: |-
  getServerName();

  function getServerName() {
    var thisServer = capFirst('{server_name}');
    return thisServer;
  }

  function capFirst(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  }
Hover_Item: '&bClick for transfer'
Hover: 'test'
Run_Command: '/admin{server_name}'
Sender_Condition: ""
Receiver_Condition: ""
Sender_Permission: ""
Receiver_Permission: ""

```

**Comment by MatinDark** [comment]
Here you are

**Comment by MatinHQ** [comment]
Here you are https://ufile.io/0ze3jegk

**Comment by ElBananaa** [comment]
Thank you!
I'll try to have a look at this in a few hours, will keep you updated here.

**Comment by MatinHQ** [comment]
Any news?

**Comment by ElBananaa** [comment]
Hey, yeah, sorry for the delay,
So, it appears the `Hover:` part works fine if the `Hover_Item:` part is empty, which, I believe, is intended.
So if you wish to have a custom hover part with multiple lines, this is how it should look in your file:
```yaml
Hover_Item: ""
Hover: ["Test12345", "Test1213123", "banana"]
Open_Url: ""
Suggest_Command: "/say test1"
Run_Command: "/say test"
Sender_Condition: ""
Receiver_Condition: ""
Sender_Permission: ""
Receiver_Permission: ""
```

As for the `Suggest_Command:` and `Suggest_Command:` features, they appear to both be broken. I'll try to have a look at this in the next few days, but @kangarko may be more helpful than me here.

**Comment by kangarko** [comment]
The Hover_Item must be a valid ItemStack, in our case a way to get the ItemStack by calling JavaScript such as "player.getItemInHand()".  The Hover part will work on its own but cannot be combined with Hover_Item.

**Comment by MatinHQ** [comment]
> The Hover_Item must be a valid ItemStack, in our case a way to get the ItemStack by calling JavaScript such as "player.getItemInHand()". The Hover part will work on its own but cannot be combined with Hover_Item.

I changed my variable file to this below and still, nothing happens when I hover my mouse over it
```
Type: FORMAT
Key: "server_handle"
Value: |-
  getServerName();

  function getServerName() {
    var thisServer = capFirst('{server_name}');
    return thisServer;
  }

  function capFirst(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  }
Hover_Item: ''
Hover: ["&bClick for transfer"]
Run_Command: '/admin{server_name}'
Sender_Condition: ""
Receiver_Condition: ""
Sender_Permission: ""
Receiver_Permission: ""
```

**Comment by kangarko** [comment]
@MatinDark oh I am sorry, just tested and you were right, we do not parse the hover/click interactive events for FORMAT type variables when in formatting/ folder or parsed in a game command, this is something more complex that I would need to handle on the next major update, sorry for the confusion here!

**Comment by ElBananaa** [comment]
@kangarko I was able to reproduce the same thing with the `MESSAGE` type during my tests, so it seems to be fully broken

**Comment by kangarko** [comment]
Works for me on my end with MESSAGE variable type when used in chat: https://i.imgur.com/mwhiSgj.png

Keep in mind that other places are not supported, we have a special handling for chat.

**Comment by ElBananaa** [comment]
I edited my item.yml variable for the tests, and it didn't work in my case: https://paste.gg/p/anonymous/d48702fbb2ea426892397ccc43a44063

**Comment by kangarko** [comment]
Oh I missed that completely, thank you! Going to have a look tmr!

**Comment by kangarko** [comment]
@ElBananaa it works when i removed InteractiveChat plugin from earlier. Now it works:

![a](https://i.imgur.com/ZBNqeCv.png)

**Comment by ElBananaa** [comment]
> @ElBananaa it works when i removed InteractiveChat plugin from earlier. Now it works:
> 
> ![a](https://camo.githubusercontent.com/722ae447016aa6833258ed446e7b43c07067abb1da7818ff0caa9f6604731bf5/68747470733a2f2f692e696d6775722e636f6d2f5a424e716543762e706e67)

Same thing with the click action/suggestion?

**Comment by kangarko** [comment]
Yep, looks like InteractiveChat breaks up, I did not have time to debug with their different chat listener priorities but changing those may fix the issue.

**Comment by ElBananaa** [comment]
> Yep, looks like InteractiveChat breaks up, I did not have time to debug with their different chat listener priorities but changing those may fix the issue.

I think you misunderstood me : I was also able to reproduce the `click action/suggestion` without InteractiveChat installed on the server ^^

**Comment by kangarko** [comment]
Hmm that's strange, can you please send the full server in case you run it on your computer ZIPPed and uploaded to ufile.io? Just to save us time I will boot the exact config you have -- or did you just change the variable yml file?

**Comment by ElBananaa** [comment]
> Hmm that's strange, can you please send the full server in case you run it on your computer ZIPPed and uploaded to ufile.io? Just to save us time I will boot the exact config you have -- or did you just change the variable yml file?

I simply replaced the variable file with the one I provided above
