### ISSUE TITLE
[1.18.2] DiscordSRV - Webhook format

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#2087]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hi!

Is it possible to display prefixes to discord? I use webhook and i want to display the prefix at the bot's name.

I made a picture if its not clear. [imgur](https://imgur.com/WOCptnG)

Thanks in advance!

Ben.

**Comment by kangarko** [comment]
Hmm not possible with webhooks I suppose. Without webhooks you can customize Discord message format easily.

**Comment by ghost** [comment]
> 

Just asked because if I only use discordsrv it displays my prefix.

**Comment by kangarko** [comment]
Can you post an image of that please just so I get the idea, maybe I am missing something.

**Comment by ghost** [comment]
Sure! The prefix is from Luck Perms and there i use it with essentials chat. I try to achieve this but with CCR. [imgur](https://imgur.com/MP4P6sz)

**Comment by kangarko** [comment]
Thanks, I will add a Format_Discord_Webhook_Name channel option in the next version that will make it possible show that prefix there :)

**Comment by ghost** [comment]
> Thanks, I will add a Format_Discord_Webhook_Name channel option in the next version that will make it possible show that prefix there :)

Thats cool! Thanks for the hard work :)
