### ISSUE TITLE
Ranged chat "Channel_Range_Notification" can be cheated as an alternative to /near

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2088]
### Summary

How can I disable the `Channel_Range_Notification: '''{prefix_warn}There is no one in '' + (hasRange ? ''range'' : ''channel'') + '' you can chat to.'''`
Players within seconds of adding a ranged chat are already using it as a way to spam to see if someone is near them without /near.
Because of this message.

If the message can be disabled it solves it, alternatively add a permission so people that have /near (Staff) can still see this message.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

People are abusing ranged chat because it acts the same as /near by telling you if nobody is near you.

**Comment by ElBananaa** [comment]
Try to set `Channel_Range_Notification: none` or `Channel_Range_Notification: ""`, it should solve the issue.

**Comment by kangarko** [comment]
Thanks to Banana for a workaround, yes you can simply disable that message this way.

I will add a new settings option to the Channels section so you can even customize how often the message shows:

![a](https://i.imgur.com/VZokEPA.png)

**Comment by TomLewis** [comment]
Thank you again @ElBananaa and @kangarko Amazing work as usual! Top speed! players wont be so happy they cant cheat this once I update it! hahaha 

If you ever want to see if something can be cheated within 10 mins, put it on piratecraft, they will find a way.

**Comment by ElBananaa** [comment]
Haha, the more players you have, the more ppl abusing these bugs you'll have unfortunately.

A fun fix for this would also be to show the /list command output for players trying to abuse this feature :D
