### ISSUE TITLE
1.19.2: Can't join Towny Channel

### ISSUE THREAD

**Issue by DarrylSSY** [kangarko/ChatControl#2089]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://gist.github.com/DarrylSSY/dc0c6cc311f767004393792268ec0827

### "/chc debug" output (strongly recommended)
https://ufile.io/lxtf610w

### Information about the issue/bug

I have configured my Towny channel in settings.yml to be     
```
town:
      Format: '&8[{#1e90ff}TC&8] {#1e90ff}{player}&7: {#1e90ff}{message}'
      Party: "towny-town"
```

However, when I switch to the town channel, ChatControlRed thinks it's a bentobox channel and gives me error because I don't have any plugins from bentobox

**Comment by kangarko** [comment]
Thanks will be fixed today!
