### ISSUE TITLE
Wrong names in comments in settings.yml

### ISSUE THREAD

**Issue by jaboy** [kangarko/ChatControl#209]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Hello

I noted that some names in the comments where incorrect in the settings.yml.

Line 676 ( by command alias for mail)
says:   # The commands that manually show the motd to the player.
Suggested:   # What commands will invoke the mail feature.

Line 694 ( by command alias for Tag)
says:   # The commands that manually show the motd to the player.
Suggested:   # What commands will invoke the tag feature.

Line 713 ( by command alias for Toggle)
says:   # The commands that manually show the motd to the player.
Suggested:   # What commands will invoke the toggle feature.

Line 733 ( by command alias for Toggle)
says:   # The commands that manually show the motd to the player.
Suggested:   # What commands will invoke the spy feature.

Sorry for being pedantic :)

**Comment by kangarko** [comment]
Thank you very much!
