### ISSUE TITLE
Finally adding support for InteractiveChat Discord Addon

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2091]
### Summary

Hi, many people already requested support for this plugin. https://github.com/kangarko/ChatControl-Red/issues?q=is%3Aissue+interactivechatis%3Aclosed+ It has been delayed for a long time. Do you think that it can be finally added?

<chat=a4e11efc-7feb-4e2a-acb5-4b642438f6a7:[item]:> This is what we get. 

If I disable chatcontrolred Discord integration, how can then I enable sending messages into my standard chat? From some reason it doesn't work. So we don't have any option to have working sending from Discord to Minecraft VS InteractiveChat Discord Addon. We have to choose.

I'm also available for Discord cooperation and as many people sent you into threads, author will cooperate with you as well.  So, please, this is not single request, look how many people requested it and there's more of them! Just join Discord of that plugin and you'll see that more people asked there.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Then we have two options:
- Disable CHC Red Discord integration, but then from some reason Discord --> Minecraft wouldn't work, is there way to fix it or not btw?
- Disable this plugin... but it adds so nice images on Discord of inventories, ender chests, items, etc! It's really useful!

Btw you can contact me on Discord if needed Renzotom#6586 I can help as well. I was beta tester of CHC Red and made here bunch of issue reports for a long time as you can see under mine name so I'll be glad if this can be finally added

Even if you should add some bandage it can be better than nothing. But here LOOHP can may cooperate with you, he's the author of the InteractiveChatDiscordSRVAddon plugin, so would be nice if there could be found some solution.

**Comment by LOOHP** [comment]
If CCRed can fire discordsrv events like how it would normally without discordsrv then InteractiveChatDiscordSRVAddon would most likely work perfectly.

**Comment by TheIntolerant** [comment]
A few of the technical limitations were mentioned here #1850

Would be cool if supported was added, as I recall it was suggested by a number of users on github.

**Comment by LOOHP** [comment]
Surely there is a way to fire some event for discord messages. You can't have hover and click events in discord messages anyway.

**Comment by kangarko** [comment]
I would be happy to get some help from @LOOHP so we can make this work :)

Here are the Discord events that we listen on: https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/model/DiscordListener.java#L478

We cancel both GameChatMessagePreProcessEvent and DiscordGuildMessagePreProcessEvent. I am thinking if you could listen to your events on NORMAL priority so your edits come before we can cancel them, or do you have a suggestion for a better way?

@bobhenl I know it has been suggested before, I am mostly a solo dev for these plugins and this is my hobby so my time is pretty limited, sorry, will do my best to get it working this month ;)

**Comment by LOOHP** [comment]
Hello @kangarko, can you explain a little bit on the steps for a message to send from the in-game chat box all the way to the discord with CHR?

**Comment by kangarko** [comment]
Sure, I invited you to see our source code. 

We listen to AsyncPlayerChatEvent and then send the message in our own way using TextComponent. We then remove all recipients from said event without canceling it for compatibility reasons (ChatListener class).

Then in the Channel class we invoke sendBungeeAndDiscord which opens the  org.mineacademy.chatcontrol.model.Discord model class (sendChannelMessage method) and invokes either webhook or TextChannel's (discordsrv's class) sendMessage() method.

Hope that helps)

**Comment by LOOHP** [comment]
Thanks for the clarification. I can see the reason why there is a compatibility issue.

DiscordSRV's `GameChatMessagePreProcessEvent` is always cancelled and ignored so no changes that InteractiveChat and its addon in the said event would be reflected.
I believe these two are the best solutions to this problem.
- ChatControl fires the `GameChatMessagePreProcessEvent` and `GameChatMessagePostProcessEvent` from discordsrv manuelly
- ChatControl fires its own event that would allow plugins to modify discord messages before they are sent to discord, which then I can listen to them.

***

For clarification, here's the flow of what happens on InteractiveChat and the addon.

InteractiveChat (IC) listens to `GameChatMessagePreProcessEvent` to remove a tag that it adds to chat messages which identifies the sender during `AsyncPlayerChatEvent`. 
The listener priority can be changed in the config for compatibility reasons, that's why there is no compatibility issue with ChatControl in-game.

InteractiveChatDiscordSRVAddon (ICD) reads the `GameChatMessagePreProcessEvent` and if it finds that a message needs to be modified, it will add a tag to the message. For example, `<ICD=1>`.
Then during `DiscordGuildMessageSentEvent` (for regular messages) or JDA's `MessageReceivedEvent` (for webhooks), ICD will look for these tags within the discord message content and then edit the message to include embeds and remove the tag from the message content.

**Comment by kangarko** [comment]
Sounds good thanks! I have made it not cancel GameChatMessagePreProcessEvent event and fire it manually when we send a channel message.

Can you please give this demo version a quick test if it works properly now?

[ChatControl-Red-10.13.7.zip](https://github.com/kangarko/ChatControl-Red/files/9487700/ChatControl-Red-10.13.7.zip)

**Comment by LOOHP** [comment]
I've just tested and there seems to be a slight issue. Can you fire `GameChatMessagePreProcessEvent` before applying all the discord message formatting and escaping? As it is a "Pre" process event. Thanks!

**Comment by bobhenl** [comment]
Also I'd like to note with the build you've sent inventories almost work, just messages are doubled from some reason:
![image](https://user-images.githubusercontent.com/18662086/188947753-7038956b-1679-427c-97fb-691780fa42c1.png)

+

![image](https://user-images.githubusercontent.com/18662086/188947789-ca185029-1fc1-4bc2-b2a6-bf0ad8db2a9c.png)

**Comment by TheIntolerant** [comment]
> Also I'd like to note with the build you've sent inventories almost work, just messages are doubled from some reason

The doubling of messages, is this limited to just discord? or is it also sending the message twice in-game too?

**Comment by bobhenl** [comment]
Discord I think

**Comment by kangarko** [comment]
> I've just tested and there seems to be a slight issue. Can you fire `GameChatMessagePreProcessEvent` before applying all the discord message formatting and escaping? As it is a "Pre" process event. Thanks!

Sure, please test the next build: 
[ChatControl-Red-10.13.8.zip](https://github.com/kangarko/ChatControl-Red/files/9539766/ChatControl-Red-10.13.8.zip)

**Comment by LOOHP** [comment]
Working great! Thanks.

**Comment by bobhenl** [comment]
![image](https://user-images.githubusercontent.com/18662086/189969764-e8e5238a-358c-4cf2-bee9-30f060c6c53c.png)
@kangarko messages are still doubling even on new build, can you please look into it?

**Comment by bobhenl** [comment]
![image](https://user-images.githubusercontent.com/18662086/190524350-ea31e054-07ed-4f5a-829a-810f0971ab7c.png)

@kangarko messages are still doubled
![image](https://user-images.githubusercontent.com/18662086/190524388-a1418aa2-b57b-4b9f-92fd-6ec84a917003.png)

**Comment by kangarko** [comment]
@bobhenl try setting DiscordChatChannelMinecraftToDiscord to false in your discord config.yml
