### ISSUE TITLE
[1.18.2] Tab completion with possible commands?

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#2092]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hey!

Is it possible to make tab completions which shows the possible commands? Like this: [imgur](https://imgur.com/C7PTZNv)

Thanks in advance!

**Comment by TheIntolerant** [comment]
Unfortunately this is not possible with chatcontrol.

However, you should be able to achieve this using a third party plugin that is designed to make custom commands, as it should include the ability to manipulate tab-competition functionality with the commands you create.

**Comment by ghost** [comment]
> Unfortunately this is not possible with chatcontrol.
> 
> However, you should be able to achieve this using a third party plugin that is designed to make custom commands, as it should include the ability to manipulate tab-competition functionality with the commands you create.

Can you recommend me any plugin for this? I found a guide to custom commands here but that mentioned plugin is down now.

**Comment by ElBananaa** [comment]
> > Unfortunately this is not possible with chatcontrol.
> > However, you should be able to achieve this using a third party plugin that is designed to make custom commands, as it should include the ability to manipulate tab-competition functionality with the commands you create.
> 
> Can you recommend me any plugin for this? I found a guide to custom commands here but that mentioned plugin is down now.

I just updated the page.
You could have a look at plugins like https://www.spigotmc.org/resources/customcommands-new-1-19-tab-completion-in-game-configs-edition.14363/ or https://www.spigotmc.org/resources/%E2%9C%94%EF%B8%8F-plugin-hide-pro-customize-players-tabcompletion-spigot-bungee-velocity-%E2%9C%94%EF%B8%8F.77112/

**Comment by kangarko** [comment]
Thanks Banana and TheIntolerant :) I think this question has been answered, comment below if you need more help.
