### ISSUE TITLE
1.18.2: multiple placeholders do not work in the same input

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/ChatControl#2093]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9461163/debug.zip)

### Information about the issue/bug

When I put a placeholder inside the `/chc announce` doesn't matter what option it doesn't parse the placeholders when there are 2 or more placeholders. It does work when you just put in 1 placeholder.

On the other side when a placeholder contains another placeholder it doesn't parse the second placeholder at all.

Currently running 1.18.2 but soon updating to 1.19.2

**Comment by kangarko** [comment]
@Greazi-Times I am very sorry, but I cannot reproduce: https://i.imgur.com/LlAXYOF.png

What command did you type exactly?

**Comment by ElBananaa** [comment]
@kangarko He tried with `%%` placeholders, and these are the placeholders he used (he gave them on discord a few days ago): `%player_name% %cmi_stats_kills%`

**Comment by kangarko** [comment]
I tried some other placeholders I had from PlaceholderAPI assuming the %cmi one came from there too, and it works fine on the latest version: https://i.imgur.com/ySACUko.png 

I will push it tonight or tmr morning, may you please retest :)

**Comment by Greazi-Times** [comment]
> I tried some other placeholders I had from PlaceholderAPI assuming the %cmi one came from there too, and it works fine on the latest version: https://i.imgur.com/ySACUko.png 
> 
> 
> 
> I will push it tonight or tmr morning, may you please retest :)

Yes of course I will test it out the moment I can.
