### ISSUE TITLE
1.19.2: Error when /say in the console

### ISSUE THREAD

**Issue by angwdev** [kangarko/ChatControl#2094]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://ptero.co/raw/sozuvyxipu

### Information about the issue/bug

Error appear when a player is online.

**Comment by kangarko** [comment]
Disable Channels.Prevent_Spying in settings.yml since it appears to be broken on your server version or combination of plugins
