### ISSUE TITLE
Request for party channel support for Party and Friends

### ISSUE THREAD

**Issue by Michael-A-Sloan** [kangarko/ChatControl#2095]
### Summary

I would love to see support for Party and Friends like how mcmmo party is in the Channels. I would love to be able to talk to my party members in a specified channel instead of having to type /p like the party and friends chat wants me to.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Nothing this is just a request. It would help with the flow of chat in my server.

**Comment by kangarko** [comment]
There are multiple plugins by that name, please send a link to Spigot or other site where I can download it.

**Comment by ElBananaa** [comment]
They are most likely talking about this plugin : https://www.spigotmc.org/resources/party-and-friends-extended-for-spigot-supports-1-7-1-19.11633/

**Comment by kangarko** [comment]
Thanks! Going to put this to my roadmap, not having time to implement this asap.
