### ISSUE TITLE
Unhandled Crash Causing Server Wide MYSQL lockdown

### ISSUE THREAD

**Issue by NoobcoreNetwork** [kangarko/ChatControl#2096]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/0014d42a56924c8583fe836f955492d4

### Information about the issue/bug

Hey! So i'm attempting to setup regex rules for anvils to stop people putting stupid characters in.

```
@import global

# Prevent renaming items with names longer than the amount of matching letters, here 20.
# Note: Colors & are counted as 2 characters currently.
match /^[\w-_.]{0,15}$/
then deny
```
This was the code i used in anvil.rs and upon reloading the plugin, the server locks up for 5 seconds, spits out the above error, and actually locks up most of the other databases on my server including the main backend/multicraft.

as seen here,

![AvastBrowser_f5TgcG7yqF](https://user-images.githubusercontent.com/62724418/188033865-d8bdf5f9-0ae9-45a9-b39a-d9435f4a573d.png)

I'm aware the regex is probably wrong, which is why it's happening, but this seems like an unhandled type of crash and I have never seen a plugin capable of affecting stuff on a linux/dedi level, So thought it was worth opening a ticket!

ty! (I can fix it easily by running /reload, as soon as the server reboots, whatever hold chc had on the mysql driver, seems to be let go)

**Comment by TheIntolerant** [comment]
This is unrelated to the crash but I strongly recommend removing unrelated comments 

Example
```
# Prevent renaming items with names longer than the amount of matching letters, here 20.
# Note: Colors & are counted as 2 characters currently.
match /^[\w-_.]{0,15}$/
then deny
```
Should probably be replaced with this
```
# Blocks usage of stupid characters via anvils
match /^[\w-_.]{0,15}$/
then deny
```
That just makes it easier to work out what each rule is trying to do, so you don't forget later on


Also with the Regex assuming you are okay with symbols like .,:;+=!&%$€£(){}[]\/ 
I would use ``match [^\w\s\-.,:;+=!&%$€£(){}\[\]\\\/]`` instead

**Comment by kangarko** [comment]
Thanks, I have fixed this really stupid mistake of mine and we push a new release tonight.
