### ISSUE TITLE
[1.19.2] [10.13.6] Prevent_Spying breaking DiscordSRV mc->dc messages

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2097]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

Prevent_Spying is a very good thing, since it prevents random kicks from the server due to chat validation failure.

But there is a little problem with it, it breaks DiscordSRV's mc->dc messages. They are not being sent at all. Dc->mc messages work normally.

**Comment by kangarko** [comment]
I cannot reproduce, please test the next version and use the latest dev build of DiscordSRV.

I tested both Webhook option false and true and both worked fine: https://i.imgur.com/otmwVUh.png

**Comment by Teslicek** [comment]
I am not using DiscordSRV hook.

**Comment by kangarko** [comment]
If you have DiscordSRV integration in ChatControl disabled, then I recommend contacting DiscordSRV's or your other Discord plugin support instead, this might be some weird incompatibility I am unaware of sorry.

**Comment by kangarko** [comment]
How's the timings of ChatControl btw? We've fixed an important problem when reloading the plugin that caused memory leaks, hope it's doing alright for you now :)

**Comment by Teslicek** [comment]
Performance hasn't changed. It's still great. I am more worried about the DiscordSRV mc->dc relay. I cannot turn Prevent_Spying off, because otherwise players will get randomly kicked due to "chat validation failure", but when it is on, DiscordSRV mc->dc chat messages do not work, even though Server started/stopped relays normally. Would it be possible to install Freedom Chat plugin alongside ChatControl?

**Comment by Teslicek** [comment]
Another update:

I managed to get Discord mc->dc messages work again, but it was a workaround. Yes, CHC is at fault here. I installed FreedomChat plugin (https://modrinth.com/plugin/freedomchat) and set `Prevent_Spying: false`.

After that, even though I still have [Not Secure] in each message in console, players are not getting kicked for "Chat validation failure" and discord mc->dc messages work normally.

Would it be possible to fix the [Not Secure] somehow else?

**Comment by Teslicek** [comment]
BTW, this is what sometimes happens even with `Prevent_Spying: true`, not just screwing up DiscordSRV's relay.
After this happens, it kicks almost everyone out for Chat Validation Failure.

![image](https://user-images.githubusercontent.com/87967222/188281284-67b93180-4ad3-43ad-8f16-76633eb1c5c8.png)

**Comment by ElBananaa** [comment]
@Teslicek Which version of protocolLib are you using? (The exact build verision)
Are you using chc 10.13.6?
Is ViaVersion installed?
Could you please make sure you are using the latest paper version available (or pupur if using purpur)?

I'm unable to reproduce this issue on my end with everything up to date btw

**Comment by Teslicek** [comment]
Yes, CHC 10.13.6, ProtocolLib b600, ViaVersion b649. I am using Pufferfish+ b25 (no purpur), but it has paper patches.

**Comment by ElBananaa** [comment]
> Yes, CHC 10.13.6, ProtocolLib b600, ViaVersion b649. I am using Pufferfish+ b25 (no purpur), but it has paper patches.

Alright then your issue above could be a compatibility issue with ViaVersion. As said in the settings file, you should avoid using this feature when ViaVersion is installed.

**Comment by Teslicek** [comment]
The problem is, if I dont have the feature toggled, everyone is kicked for Chat Validation Failure or something like that. The only thing that solves it is FreedomChat. Maybe I could try FreedomChat + Prevent_Spying: true later, but im not sure if they wont be incompatible together.

**Comment by ElBananaa** [comment]
That's pretty weird as this shouldn't happen since all messages are sent as system messages when our channels feature is enabled, which means that the server should not even try validate messages at all.

I wish I could do more but I do think you'll have to wait for Kangarko for this.
I'm reopening this so he doesn't forget to have another look at your issues :)

**Comment by kangarko** [comment]
> BTW, this is what sometimes happens even with `Prevent_Spying: true`, not just screwing up DiscordSRV's relay. After this happens, it kicks almost everyone out for Chat Validation Failure.
> 
> ![image](https://user-images.githubusercontent.com/87967222/188281284-67b93180-4ad3-43ad-8f16-76633eb1c5c8.png)

I will add a way for the entire error to show in the next version, please send it back to me below when it happens.
