### ISSUE TITLE
New renewal system ? Scam me .

### ISSUE THREAD

**Issue by TheJavaProgrammer3301** [kangarko/ChatControl#2098]
After purchasing this many year ago , I went to BuiltByBit to redownload the latest version , when I see renew for 1 dollar . I do not remember this being implemented. I purchase it, and AFTER CHARGING MY ACCOUNT I just get error "Please enter a number that is no more than 4294967295." so I try again , thinking it didn't charge account , and same error . I have lost 2 dollar . Please fix , I want to use ChatControl Red and want dollar refund .

**Comment by ElBananaa** [comment]
**We must've talked about it pretty much half a hundred times in the last few months : We are not scamming anyone**. This is an issue that appeared when mcmarket updated their forums, and you don't have to pay anything to renew your license. Simply follow what's said here : https://github.com/kangarko/ChatControl-Red/issues/1680

As for getting your money back, send an email to support@mineacademy.org.

If the upgrade button somehow doesn't work for you, simply send this request to support@mineacademy.org with your builtbybit account link.

**Comment by kangarko** [comment]
Sorry to hear, but this looked like the renewal price was too low and there was a bug in BuiltByBit. I have contacted their support on your behalf.

I have also issued you a new manual license from BuiltByBit so you should now be able to download it and issued you the glorious $0.99 refund.

**Comment by TheJavaProgrammer3301** [comment]
Thank you very much - I apologize for the rushed manner, it was 4 AM for me and I was very tired. Have a nice day!
