### ISSUE TITLE
Missing Italian localization?

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2099]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Bug/Question

I notice in version **10.13.4** it stated.

**New | Added Italian localization thanks to [BugabuseMe](https://builtbybit.com/members/bugabuseme.191293/)!**

However it seems it was never added to the actual jar file nor was it added [here](https://github.com/kangarko/ChatControl-Red/tree/master/localization), was this a mistake? 

This also needs to be updated
![image](https://user-images.githubusercontent.com/48093184/188277955-eaa8a86b-195d-4b05-9333-c9f4e45b9ffc.png)
To include ``tw (Traditional Chinese)`` as well Italian

**Comment by ElBananaa** [comment]
I opened a PR to fix this, thanks for reporting!
![image](https://user-images.githubusercontent.com/53318613/188290433-75ec01d9-990d-477e-9032-ebe899db0407.png)

**Comment by kangarko** [comment]
Thank you I will update it, sorry for the missing file!
