### ISSUE TITLE
Players cant do faces in chat

### ISSUE THREAD

**Issue by MatrixKhan** [kangarko/ChatControl#21]
so when players try and do for example :) or <3 etc it wont let them it says special characters are not allowed how can i fix this?

**Comment by kangarko** [comment]
It seems like another rule is preventing it. Have you edited the rules? If so, try to go through the files and find the suspicious one. If you fail then you can send me the rule files via PM at spigot forums, and I will try to do it in my free time.

**Comment by kangarko** [comment]
Resolved via PM.
