### ISSUE TITLE
Cannot define an operator when no rule is being created!  File chat.txt

### ISSUE THREAD

**Issue by Sidious82** [kangarko/ChatControl#210]
i am trying to edit the chat.txt file (which it clearly says i can safely edit) to remove the emoji function of this plugin, however every time i make ANY change to the chat.txt file it renders the entire plugin useless.  Must delete the .txt file and let the configuration regenerate a new one for the plugin to work again

**Comment by kangarko** [comment]
Hey,

If the error says that previous rule was 'null', ensure you are saving the file in UTF-8 format. See https://github.com/kangarko/ChatControl-Pro/wiki/Common-Issues#check-your-encoding

**Comment by Sidious82** [comment]
i am able to make edits just fine to the rules.txt (e.g. adding additional blacklisted words) but if i make any alterations whatsoever to the rules.txt the entire plugin crashes.

**Comment by Sidious82** [comment]
resolution:  must use notepad++ when editing chat.txt file, and must use "#" to disable features.  i think you could spell this out a little clearer for us "regular folk"

**Comment by kangarko** [comment]
Thank you for advising, I will update the wikipedia.
