### ISSUE TITLE
question | set delay on motd and join msg.

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#210]
As it is now, motd comes last and join above and some plugin message handles under motd from time to time.

As you could in cc8 set, can you do it in red or do you have to add support?

Look like this now
![motd](https://user-images.githubusercontent.com/16368286/100899696-65bb3700-34c2-11eb-9b97-4b916a04e844.png)

**Comment by kangarko** [comment]
We removed it to simply our config. It was not used by many and some people were confused.

How do you use this? Do you want this order?

1. All other plugin messages.
2. Join message
3. Motd

Matej

**Comment by broken1arrow** [comment]
> We removed it to simply our config. It was not used by many and some people were confused.
> 
> How do you use this? Do you want this order?
> 
> 1. All other plugin messages.
> 2. Join message
> 3. Motd
> 
> Matej

Oright, I understand :) 
Like this (so players see/spot their join msg easy).
1. All other plugin messages.
2. Motd
3. Join message

**Comment by kangarko** [comment]
Thanks, done
