### ISSUE TITLE
[1.19.2] [10.13.6] Lag spikes caused by Database.lambda$loadCache$5()

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2100]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

After updating to 1.19.2 (from 1.19) and latest ChatControl, I started having occasional lag spikes caused by `Database.lambda$loadCache$5()`. 

![image](https://user-images.githubusercontent.com/87967222/188278088-57361252-dfed-40f4-b0d0-dfcbf9d0bf7c.png)

I do not know what changes have been made since 10.12.11 (which was perfect btw), but this is causing relatively high MSPT spikes.

**Comment by kangarko** [comment]
I am sorry, I cant see the lag spikes, but one thing we did change was that we removed async config save since that caused more issues than good, all file operations are synced on the main thread which may cause a blocking operation for a split second. Should not cause any real lag in game tho.
