### ISSUE TITLE
1.19.2: MCMMO Chat Spy

### ISSUE THREAD

**Issue by LilShadow19** [kangarko/ChatControl#2102]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Is there a way to disable MCMMO chat spy w/ chat control red like through the spy menu and if so what channel is it called?

**Comment by kangarko** [comment]
Try setting Spy.Format_Party_Chat to "" in our settings.yml but I dont think that it can be disabled in ChatControl, rather, disable that feature in mcmmo.
