### ISSUE TITLE
1.19: Unhandled exception listening to AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by iUndef** [kangarko/ChatControl#2105]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://gist.github.com/iUndef/d582b64d12eda81e994d5a20b6df7804

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9502553/debug.zip)

### Information about the issue/bug

When a user sends a message in the general public chat, the above error occurs and the message is sent without our standard prefix. However if a user sends a message in a channel, or sends to the public chat via a command (/g [message] in our case) the message goes through with no issue. In the below screenshot the first message was sent to the public chat the standard way of pressing 't' and sending a chat message, the second was sent by typing "/g test" and includes the expected prefix and formatting, the third was sent to a private channel, and the last two lines are a /msg that were also delivered in the expected format.
![image](https://user-images.githubusercontent.com/104413998/188784949-a8f4aa09-4be1-4ef7-8317-dc5bf5cf45f4.png)

**Comment by kangarko** [comment]
Your Sender_Condition is failing somewhere, the script cannot be called async (all chat is async). Since you have tons of usages of it (https://i.imgur.com/qOyIZCG.png) I will make the next version print a more informative message to help you locate where you have that condition.
