### ISSUE TITLE
1.19.2 - Issue Displaying Custom Enchants In Chat Using [item] Variable

### ISSUE THREAD

**Issue by ManicTrav** [kangarko/ChatControl#2106]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

no error in console

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9506285/debug.zip)

### Information about the issue/bug

Items do not show custom enchants when players link items in chat using the [item] function. Only vanilla enchants are displayed. I'm using ecoenchants as my custom enchant plugin. All item attributes are listed in the console when I use the cmd /chc info item (player name). Here is an example console output when using the /chc info item cmd:

https://pastebin.com/nCFLuHFy

All custom attributes/enchants are listed here but not when players hover over the items in chat. Its missing the custom enchants.

![Same Item Displayed Correctly In Inventory](https://user-images.githubusercontent.com/112690163/188883734-e2d2baab-d204-40a8-84e3-7b68cdfcbde4.png)

![Hover Item In Chat](https://user-images.githubusercontent.com/112690163/188883590-14ef452a-fe5d-48a0-8726-c37d299b6e6d.png)

**Comment by kangarko** [comment]
Thanks, this is because custom enchants are unsupported in Minecraft so your other plugin must be showing them as lore. Not sure why the lore is broken but we simply render the item as Minecraft server instructs your client to do, likely it is incompatible. You can try using the plugin InteractiveChat to see if they render it properly.
