### ISSUE TITLE
Proxy/Spigot QOL feature suggestion

### ISSUE THREAD

**Issue by NoobcoreNetwork** [kangarko/ChatControl#2107]
### Summary

Hey! So I have a little bit of an issue on my server, It's more of an inconvenience, I run a custom resource pack and when a user joins, it instantly fires the join rule from the proxy side, (which would be the same on the spigot side I assume also) The pack can take 15-20 seconds to load for some users, and longer for others, Now when they are in the pack loading screen, Everybody is saying hello to them, but they don't see this welcoming because they are loading, And by the time they have loaded into the game the messages are gone.

I have checked and the event is ready to be hooked
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerResourcePackStatusEvent.html
ACCEPTED, DECLINED, FAILED_DOWNLOAD, SUCCESSFULLY_LOADED

SUCCESSFULLY_LOADED being the one that would need to be hooked for the join messages + first time join messages to be delayed until the user is actually in the game.

LMK if you need more info ty!

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Honestly nothing, But i feel like it's an issue for everyone running CHC and a custom resource pack, unless they disable chc's messages and make a custom plugin to deal with it.

**Comment by kangarko** [comment]
Thanks, added under Messages.Delay_Until_Resource_Pack_Loaded

**Comment by TheIntolerant** [comment]
Will this work for such messages sent via BungeeControl-Red too?
If not, that would be a good addition!

**Comment by kangarko** [comment]
We notify bungeecord about this so it should yes :)

**Comment by NoobcoreNetwork** [comment]
Hey! So i have tested this out and it would seem that the event is firing on ACCEPTED and not SUCCESSFULLY_LOADED, The difference being as soon as you press accept it says you joined the server, but it might take you 15-20 seconds to load the pack

**Comment by ElBananaa** [comment]
Hey,
@NoobcoreNetwork Well it appears we do fire the event when the status is `SUCCESSFULLY_LOADED`:
![image](https://user-images.githubusercontent.com/53318613/193667779-604538cd-f091-42cc-95aa-1cbe7373df07.png)

I also ran tests and it seems to work pretty fine for me (except the message appears to be sent twice)

**Comment by NoobcoreNetwork** [comment]
I just realised im sending my messages out from the proxy

and i have put
If you have a custom resource pack you can delay showing join messages until player accept 
and downloads it. We will not show anything on decline/failed download.
  Delay_Until_Resource_Pack_Loaded: true
  
  on the frontend survival lol

**Comment by NoobcoreNetwork** [comment]
Wait. I just pasted that into the config of bungeecord and I don't think thats how it works is it? lol

**Comment by ElBananaa** [comment]
This setting isn't in BungeeCord, it must be enabled in your spigot/paper server.

**Comment by NoobcoreNetwork** [comment]
> 
Ah yeah seems to not work this way for me hmm, Could you test with the messages being on the proxy side? :)

**Comment by TheIntolerant** [comment]
I asked:
> Will this work for such messages sent via BungeeControl-Red too?

Which Matej replied saying:
> We notify bungeecord about this so it should yes :)

---
So I assume it works for BungeeControl messages? You just need to enable this option on the backend servers. Unless you are saying it's still not working even after enabling in your chatcontrol settings?

**Comment by kangarko** [comment]
Going to follow this up in 24h

**Comment by NoobcoreNetwork** [comment]
Yeah i have it enabled in spigot and it doesn't seem to delay the bungeecord messages at all

**Comment by kangarko** [comment]
Thanks, Elbanana is working on a fix, I just requested a minor change but it should be finished quickly :)

**Comment by NoobcoreNetwork** [comment]
Thanks seems to be working now for me! :D

**Comment by NoobcoreNetwork** [comment]
![javaw_ZnHruXHvd9](https://user-images.githubusercontent.com/62724418/205455849-cff665b9-66e1-48be-95de-3f4d6ddf4249.png)


Hello again! 

```
  # If you want to display join message after other plugins, you can send it
  # a bit later such as 1 tick later than the other messages. 
  # **YOU CANNOT OVERRIDE THIS WITH THE "DELAY" OPERATOR**
  Defer_Join_Message_By: 1 tick
  
  # If you have a custom resource pack you can delay showing join messages until player accept 
  # and downloads it. We will not show anything on decline/failed download.
  Delay_Until_Resource_Pack_Loaded: true
  
  # The SHORTEST delay when sending timed messages. You CANNOT use "delay" operator lower than this
  # in your messages/timed.rs file. When no delay operator is used, we use Timed_Delay as default. 
  Timed_Delay: 10 seconds
  ```
  
  
  So, Im having an issue when players don't manage to fully load the pack, either backing out or having a connection issue, it is still firing the leave message before it even got to the part of firing the join message, It's very strange for people to see X player left the server, when they never actually logged in lol!
  
  Thanks!

**Comment by TheIntolerant** [comment]
To be fair, it would probably be worth making this apply to all messages, so messages such as the quit messages don't fire before the join message gets a chance to be fired.

**Comment by ElBananaa** [comment]
Hey,
I quickly worked on something that should hopefully fix this, however I don't have the time to test this.
@NoobcoreNetwork If you want, when you have a minute, just @ me on our discord in the chatcontrol channel and i'll send you the build so you can give it a shot.

**Comment by NoobcoreNetwork** [comment]
> Hey, I quickly worked on something that should hopefully fix this, however I don't have the time to test this. @NoobcoreNetwork If you want, when you have a minute, just @ me on our discord in the chatcontrol channel and i'll send you the build so you can give it a shot.

Hey hey! I did message ya on discord but there is no join messages being fired at all now

**Comment by kangarko** [comment]
@ElBananaa thanks so much, please make a pull request when this is ready! :)

**Comment by ElBananaa** [comment]
@kangarko Alright, so after running tests, I should have fixed the issue for spigot servers, however, servers using BungeeControl's quit message system still receive the quit message. We did try a few things yesterday with @NoobcoreNetwork but none of them ended up working. Can take a look at this on your side too?

EDIT: Spent multiple hours trying to find the best way to fix this on the proxy side, but couldn't, so I wouldn't say no to some help.
