### ISSUE TITLE
1.19.2: Chat Dont Push Messages

### ISSUE THREAD

**Issue by editon96** [kangarko/ChatControl#2108]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### "/chc debug" output (strongly recommended)

Debug File 1: https://ufile.io/73fja0io
Debug File 2: https://ufile.io/s9nvj3ju
Debug File 3: https://ufile.io/qxsqfx4z

Why tree? because its an network and that are tree Servers.
Only from Velocity Control I dont get any Debug.

### Information about the issue/bug

I want that an join leave masseage msg and chat over that network work also the forwrding with Discord SRV..

But yet it dont work messages only on the server were write it.
In 1.18.2 it all worked but now not. I only update all.

**Comment by kangarko** [comment]
@james090500

**Comment by kangarko** [comment]
closing since our developer is inactive, @james090500 let me know when you come back

**Comment by james090500** [comment]
Sorry I currently have covid but let me try get some more information.

You're saying that with discord forwarding enabled, only messages from the current server are forwarded not the entire network?

Can you list your servers and which servers have discord srv on?

**Comment by kangarko** [comment]
Get well and thanks for replying! Hope you are getting notifications about closed tickets :)

**Comment by editon96** [comment]
I see it yeah.
I have only disord srv on one server and the pushing from one server to the others.

I dont now why but I cant send any massage from one ingame Server to a nother. It didnt work.

And I dont now why...

**Comment by editon96** [comment]
I fogot to answer ...

How I can enable the network wide chat that dont work?

**Comment by kangarko** [comment]
Due to Bukkit limits you can't send message from/to an empty server, check if there were players.

Network wide chat you can enable by setting Bungee: true in your channel settings and enabling bungeecord integration, read BungeeCord on our wiki.
