### ISSUE TITLE
1.16.4 | Warning: The following entries in settings.yml are unused and were moved into settings.yml

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#211]
MySQL: Yes
Bungee: Yes

Are old/deprecated settings supposed to be sent to a backup file?  I get the following warning when updating from 10.1.2 to 10.1.4:

Warning: The following entries in settings.yml are unused and were moved into settings.yml: [Messages.Timed_Suffix, Messages.Timed_Prefix]

Should that say "are unused and were removed"?  The language used there is confusing.

**Comment by broken1arrow** [comment]
> MySQL: Yes
> Bungee: Yes
> 
> Are old/deprecated settings supposed to be sent to a backup file? I get the following warning when updating from 10.1.2 to 10.1.4:
> 
> Warning: The following entries in settings.yml are unused and were moved into settings.yml: [Messages.Timed_Suffix, Messages.Timed_Prefix]
> 
> Should that say "are unused and were removed"? The language used there is confusing.

and it create new folder unused with the removed settings.

**Comment by kangarko** [comment]
This is intended, we no longer use these two keys so they became unused. I'll try to change the wording so it's less confusing next time.
