### ISSUE TITLE
1.19.2 - Request for report feature

### ISSUE THREAD

**Issue by rRampelnik** [kangarko/ChatControl#2110]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

No

### Question

**Zdravím, ahoj.**

Nepřidal byste nový příkaz?
Možnost reportu, nahlášení hráče nebo bugů či problému.
_/report player_  pro nahlášení hráče přímo ve hře.
Poté něco jako _/report problem_, pro nahlášení poblémů, bugů a podstatných věcí.
S podporou aktuální verze minecraft (java), k dnešnímu dni 1.19.2.

Využití napříč možnostmi, hlavně nahlášení problémů v nepřítomnosti člena Staff.

Jistě existují podobné pluginy ([například](https://www.spigotmc.org/resources/player-report-%C2%BB-1-7-1-17-1-%E2%80%A2-gui-for-reports-%E2%80%A2-api.22371)), pracujeme na vlastním serveru a již máme zakoupený Chat Control Red.
Zakoupili jsme si ho pro důvěru a spolehlivost.

**Děkuji** za zpětnou vazbu.
Rampelník

**Comment by kangarko** [comment]
ďakujem, nateraz nie neplánujeme to. Máme funkciu /mail čo umožní hráčom jednoducho poslať mail správcom, aj keď sú offline. Plus na väčšie report funkcie nemáme priestor/čas, na to sú separátne pluginy.
