### ISSUE TITLE
color and design removed after disconnect

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#2111]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

just set a color
then disconnect and connect (reconnect)
the color or design are gone

**Comment by TheIntolerant** [comment]
Assuming this is regarding ``/chc color``, please make sure you have the correct permission nodes assigned. If you don't have the proper permission node, upon rejoining the server, that chat colour will get stripped from the user.

---

For Hex colours ``&#1b4d3e``, ``&#fe4480``, etc.
```
chatcontrol.hexguicolor.{color}
chatcontrol.hexguicolor.1b4d3e
chatcontrol.hexguicolor.fe4480
```

For Legacy colours ``&2``, ``&6`` etc.
```
chatcontrol.guicolor.{color}
chatcontrol.guicolor.dark_green
chatcontrol.guicolor.gold
```

**Comment by FakEEE14** [comment]
thanks sir

**Comment by FakEEE14** [comment]
thanks sir
solved
