### ISSUE TITLE
1.18.2 Did chatcontrol.command.announce.chat perms change? Staff all lost the ability!

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2113]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Suddenly all staff lost the ability to send annoucements? was this changed in an update? Chat/title anything.

**Comment by TheIntolerant** [comment]
There hasn't been a permission change, after running this command
```
/lp verbose on chatcontrol. me
```
to check, only this perm ``chatcontrol.command.announce.chat`` showed up.

**Comment by kangarko** [comment]
Check permissions as the intolerant said and feel free to return back if you have any more questions

**Comment by TomLewis** [comment]
![Screenshot 2022-09-17 17 37 32](https://user-images.githubusercontent.com/144046/190867269-f5cdc046-c19a-4614-817d-c1c721ad5c84.png)

Its not me. The permissions haven't changed on my server, only chatcontrol has updated, and this permission check in luckperms is showing a placeholder instead of the actual permission read `{type}`.

But its bypassed by OP.

**Comment by ElBananaa** [comment]
Hey, could you please add me on discord: `Bananaa#1471`? I'll provide you a jar file which hopefully should fix this. I believe I introduced this issue when implementing support for toast styles in the `/chc announce` command.

**Comment by TomLewis** [comment]
Sent!

**Comment by kangarko** [comment]
Will be fixed in todays release! Thanks to @ElBananaa for a prompt help!
