### ISSUE TITLE
Paper 1.19.2 #142: Question about Command Interception

### ISSUE THREAD

**Issue by VimaMT** [kangarko/ChatControl#2114]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Question:  Do you intercept commands as well as chat messages?

I've noticed lately that the WorldGuard /locate command is overriding my Minecraft /locate command. I just took this issue to the WorldGuard developers because it should not be occurring. I'm running PaperMC 1.19.2 and one of the latest snapshots of WorldGuard.

Is there any way that ChatControl can be changing priorities on Minecraft commands?

I had to ask.  :-)

**Comment by ElBananaa** [comment]
Hey,
Afaik, chatcontrol doesn't need to add a such feature as you can easily fix this using bukkit's commands.yml file (which is in your server's root folder).

This is how the default file looks like:
```yaml
aliases:
  icanhasbukkit:
  - version $1-
```

Add this part below, and it should fix your issue:
```yaml
  locate:
  - minecraft:locate $1-
```

**Comment by kangarko** [comment]
Thanks to Banana!

Also, there is always the "hardcore" approach where you open the WorldGuard.jar file, then open plugin.yml file, find the "locate"  command and remove it or change its name/aliases.
