### ISSUE TITLE
Discord Specific Rules

### ISSUE THREAD

**Issue by alderwyn** [kangarko/ChatControl#2115]
### Summary

I would like to suggest a new operator which works similarly to "then replace" however, it only replaces the matches part of the message on discord, instead of it being replaced globally like "then replace" currently does.

For example, say I have a rule like this:
match 
then discord replace 💯

So "" is replaced with "💯" but ONLY on discord and it remains unchanged in-game.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

If this feature weren't implemented rules would be limited to global meaning less customization and restrictions on creativity for server owners that want a more customised chat for their users in-game and in their Discord server. In my example I would be using this feature to replace emojis that you can see in-game with their Discord equivalents. I appreciate your attention to my improvement request.

**Comment by kangarko** [comment]
Thanks for your suggestion, however our rules are already quite complex and extensive and I dont want to drag the performance down further due to features that are requested by 1-2 people out of all customers. I hope you understand
