### ISSUE TITLE
I cannot buy Chat control on builtbybit

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/ChatControl#2116]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

Yes

### Information about the issue/bug

When I click on purchase I receive the error: Oops! We ran into some problems.
Please enter a number that is no more than 4294967295.

Could you sell it to me via another method please contact me @ yvanlincroyable@gmail.com

Thank you

PS: I have opened a ticket on their plateform also

**Comment by CtrlAiDel** [comment]
Hello there,

Thank you for reaching out to us.

This is an issue with how the author has set up the resource. Please attempt reaching out to the author for further support.

If there’s anything else that we can do for you, please let me know and I would be more than happy to assist. Otherwise, I'll go ahead and close this ticket for you.

Regards,
Vierdant

**Comment by ElBananaa** [comment]
Hey,
Did you previously buy ChatControlPro, or ChatControlRed, or is it the first time you attempt to buy the plugin?

**Comment by CtrlAiDel** [comment]
First time. Looking to buy ChatControlRed

**Comment by CtrlAiDel** [comment]
Do you have any discord server?

**Comment by ElBananaa** [comment]
Alright, yes, we do have a discord server : https://discord.gg/SAYYKRvjQZ
If you wish, you can buy the plugin on our website directly : https://app.mineacademy.org/offer/2451

If you'd rather buy it on BuiltByBit directly, please send an email to support@mineacademy.org to explain your issue. Don't forget to provide your builtbybit profile link. Kangarko will most likely answer you in the next few days.

**Comment by CtrlAiDel** [comment]
Thank you!
@ElBananaa
