### ISSUE TITLE
Variables in "then notify" rules

### ISSUE THREAD

**Issue by Neeonn** [kangarko/ChatControl#2118]
### Summary

Add an option to notify players for which certain variables return true; example:
```then notify {player_is_spying_command} spy-command```

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Currently there is no way to spy on custom commands.

**Comment by ElBananaa** [comment]
This would be a pretty useful feature.
In addition to this, TheIntolerant also suggested that when using a format file with the `then notify` operator, we only send the notification if the receivers of the message don't see an empty message. This would work as a workaround for the feature suggested above, however, I don't really know what's the best way to achieve this

**Comment by TheIntolerant** [comment]
Just to provide more clarification on this issue and why this suggestion was made!!

Basically, we were trying to make it so custom commands (created within chat control) could be spied on similarly to regular commands that are spied on using the spy feature in the settings.

For example, say I had a custom command ``/test``

Using this [command rule](https://pastebin.com/m12cEAZy) and this [format file](https://pastebin.com/8kVFFxZk) (called ``spy-command.yml``), I could essentially make it function the same as the normal spy for commands which are actually registered by plugins, etc.

This worked but once the user turned off spying for commands, this resulted in them getting sent a blank line in chat when someone ran the command "/test" as they didn't meet any of the conditions listed in that format file so a blank message was sent.

**Comment by kangarko** [comment]
@ElBananaa you could potentially implement a new operator "process command" which would call Spy#broadcastCommand and Log#logCommand methods like in CommandListener

**Comment by ElBananaa** [comment]
> @ElBananaa you could potentially implement a new operator "process command" which would call Spy#broadcastCommand and Log#logCommand methods like in CommandListener

I didn't think about directly "hooking" a new operator to the current spy system, but that's a great idea! I'll try to have a look at this tonight when I get home :)

**Comment by ElBananaa** [comment]
Alright, @kangarko added in https://github.com/kangarko/ChatControl-Red-Src/pull/45
