### ISSUE TITLE
settings.yml Private_Messages Reverse msgtoggle, default to OFF and opt in to accept MSG

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2119]
### Summary

10 years of running a minecraft server and I only just thought of this, people currently can /msg any player at any point, unless they toggle their messages off. If its the other way around, where its always off when they log in and they can use /msgtoggle to turn it on, that would be beneficial to many players.

This could automatically be toggled on when they msg someone.

When im online as staff, I always have /msgtoggle to disable my messages, but I know how to set this! new players wont at the start and have to learn, and by then they could have been bombarded by people with messages with god knows what.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Nothing much, more spam to people.

**Comment by ElBananaa** [comment]
I don't think that disabling private messages by default is a great idea, but I'll work on a config option to automatically disable private messages by default, this way server owners will have the choice.

**Comment by ElBananaa** [comment]
Alright, I just made a PR for this feature. Let's wait for Kangarko to either approve or deny it now ^^

**Comment by TomLewis** [comment]
Thanks, sorry I wasn't around to test!

**Comment by ElBananaa** [comment]
> Thanks, sorry I wasn't around to test!

No worries! I test the changes myself so I don't have to wait to make adjustments. ;)

**Comment by kangarko** [comment]
I believe this was implemented by @ElBananaa !
