### ISSUE TITLE
1.12.2 | [ProtocolLib] [PacketFilterManager] [ChatControlRed] Unsupported client packet in current Minecraft version

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#212]
Bungee: Yes
MySQL: Yes

I am getting the following warning with CC Red 10.1.4 on Paper 1.12.2:

[ProtocolLib] [PacketFilterManager] [ChatControlRed] Unsupported client packet in current Minecraft version: B_EDIT[PLAY, CLIENT, 12, classNames: [net.minecraft.server.v1_12_R1.PacketPlayInBEdit] (unregistered)]

**Comment by kangarko** [comment]
Thanks. This feature won't work on MC <1.13 anyways, so I just hid the message.
