### ISSUE TITLE
MyPet Support

### ISSUE THREAD

**Issue by PinoyLifeCraft** [kangarko/ChatControl#212]
Hello there @kangarko,

Can you add MyPet Premium Support? 🙏 
I get error when the pet killed the player 🙁 

Best Regards,
Me 😜

**Comment by kangarko** [comment]
Hey,

please post me the error.

**Comment by PinoyLifeCraft** [comment]
Hello there @kangarko ,

Here's the error 
https://pastebin.com/asgE0XWF

**Comment by kangarko** [comment]
Hey,

the error you have posted links to classes that does not exist in the current ChatControl version. Please test against the following release and report the error:

https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro.10258/update?update=161174

**Comment by kangarko** [comment]
If you still have the issue, please make a new issue on the Pro issue tracker (this one is for the free version) and include the stack trace from the latest version.
