### ISSUE TITLE
Ability to use images in files.

### ISSUE THREAD

**Issue by SuperPyroManiac** [kangarko/ChatControl#2122]
### Summary

The ability to use images in files would be fantastic. Would allow more unique messages, broadcasts, etc.
One example would be to use your server logo in an MOTD.

![image](https://user-images.githubusercontent.com/1407314/190920065-cbf351f7-feae-4daf-a7dc-d36a1d94a052.png)

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

You have a cool image to text converter that is wasted only on an announcement command.

**Comment by kangarko** [comment]
Thank you, I will put this to the roadmap, no ETA right now
