### ISSUE TITLE
Fix [Not Secure] without Prevent_Spying

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2125]
### Summary

Since Prevent_Spying breaks DiscordSRV's mc->dc messages, I cannot use it.

I'm pretty sure there is a way to fix the [Not Secure] without the Prevent_Spying feature.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Nothing, except that all messages in console are white, which makes it really hard to read compared to before (1.19).

**Comment by ElBananaa** [comment]
I honestly doubt it's currently possible for us to get rid of the [not secure] part without the `Prevent_Spying` feature (unless spigot, or one of it's forks make changes directly related to this? idk).

**Comment by kangarko** [comment]
Yeah we need to cancel chat event and then log the message manually to the console without said prefix. 

This message can easily be removed by editing the server (PaperSpigot can easily add a toggle) but they can not care less to do it.
