### ISSUE TITLE
Allow formating of the help messages in the localization files. 

### ISSUE THREAD

**Issue by ManicTrav** [kangarko/ChatControl#2127]
### Summary

There is no way, that I can find, to easily edit the "help" messages. I am limited to editing the verbiage and colors of the messages using the localizations files. Anyway to add the line formatting, spacing, formatting, ect to the messages_en.yml? I really dont need 10 lines of chat for this simple tip. Thanks in advance. 

Allowing customization of the formatting via the localization files would be great, but taking it an extra step further and adding a rule or cmd to open the tips/help menus in a gui or book would be amazing!!

![Screenshot (284)](https://user-images.githubusercontent.com/112690163/192090126-fad31e48-639d-4205-b6d9-d8b3b8826f9e.png)

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Just an ugly chat...lol

**Comment by TheIntolerant** [comment]
Just to add to this, I believe a few other people have asked for something similar in the past and it would be nice to edit the local file so you could make such messages, more minimalistic!!

For example, regarding the output for ``/reply``, I believe it would benefit the plugin to allow users to change such command help suggestions so server owners/admin can make it more minimalistic like this:
![image](https://user-images.githubusercontent.com/48093184/192093104-50425833-fc58-4017-b2f5-684bcc437adf.png)


For example: in #411 the changes made there allowed users to change the Chat Announcement, from [this](https://imgur.com/a/y1mRnh0) to [this](https://imgur.com/a/eL6Z4qm)!

Anyway, if this were added, that would be amazing!

**Comment by kangarko** [comment]
Thanks, I added "Commands.Simple_Help_Design" to localization key to turn this design on

**Comment by ManicTrav** [comment]
Simple_Help_Design: true did not function for me. help menus are still formated in the original styling.

**Comment by TheIntolerant** [comment]
Can confirm, I also have this issue. Nothing changed, even when I tested it with a fresh install and on a test server. The ``false`` or ``true`` value seemed to make no difference in ``Simple_Help_Design:``


I noticed this was implemented on your other plugins too and so I tested it on chatcontrol and boss but had the same issue. I only had these [plugins](https://user-images.githubusercontent.com/48093184/192548954-7298d0e3-9af1-4d48-a483-8bb66eb647ce.png) installed on a test server when I first tested it.

**Comment by ElBananaa** [comment]
This appears to work fine for me.
![image](https://user-images.githubusercontent.com/53318613/192583486-b8ae8d6f-01a0-475c-bfb9-60a0f9c5bec8.png)

![image](https://user-images.githubusercontent.com/53318613/192583579-9f75cb45-b346-41e3-b50c-3459f374b75a.png)

**Comment by kangarko** [comment]
I probably forgot to compile foundation before our plugins, apology and will push an update to them all soon!

**Comment by TheIntolerant** [comment]
The latest update fixes this! Thanks!
