### ISSUE TITLE
1.17.1 Spigot: ChatControlRed Crashes and does not work when player joins

### ISSUE THREAD

**Issue by Tensapsn** [kangarko/ChatControl#2128]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/cd271f9dc5034612bde8cbe095ca346f

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9639128/debug.zip)

### Information about the issue/bug

Whenever player count reaches 10+/75 The chatcontrolred plugin randomly crashes and does not work we are unable to reload kicking that player sometimes work but sometimes does not, restarting the server fixes it but however this is an issue that i am not able to fix and could not find out the reason why this keeps happening. Please help me with this bug thank you.

**Comment by ElBananaa** [comment]
You are not using the latest version available and this is not a VelocityControl error.
It also appears your data.db file is corrupted.

Update the plugin, delete your data.db file, then start your server, and complete the tour again. It will solve your issue.

**Comment by Tensapsn** [comment]
Thank you, im sorry for this inconvinience
