### ISSUE TITLE
1.8.8: Database batch update is still processing

### ISSUE THREAD

**Issue by Neeonn** [kangarko/ChatControl#2129]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Error log (if applicable)

https://gist.github.com/Neeonn/05a171368f23a496c8c68c10ebd4b905

### "/chc debug" output (strongly recommended)

[debug(5).zip](https://github.com/kangarko/ChatControl-Red/files/9639550/debug.5.zip)

### Information about the issue/bug

I've been seeing this but disregarding, it doesn't always happen when using tag or other chc commands, it happens every once in a while too.
[latest.log](https://termbin.com/strd)

**Comment by kangarko** [comment]
Just ignore it, not sure why it takes longer to update the database but as you see the message shows only once, that means we updated it successful at the end.

**Comment by ElBananaa** [comment]
@kangarko This happened more than 200 times in less than 15 hours for this user, and it pretty much almost always happened for a single query

**Comment by kangarko** [comment]
Wow did not know that; but I still believe that something is causing the database to be slow.

@Neeonn how big is your database how many entries for each of the three tables that we create? You can just backup and remove it to see if by reseting it it solves the issue. If it does not then it is caused by a slow connection to your db server or high latency

**Comment by NoobcoreNetwork** [comment]
Hello! Same issue here with me

[18:30:42] [Timer-81/INFO]: [ChatControlRed] Database batch update is still processing, drink water and DO NOT SHUTDOWN YOUR SERVER. (Total size: 1 queries)
[14:23:00] [Timer-21/INFO]: [ChatControlRed] Database batch update is still processing, drink water and DO NOT SHUTDOWN YOUR SERVER. (Total size: 1 queries)
[14:34:13] [Timer-50/INFO]: [ChatControlRed] Database batch update is still processing, check your db and DO NOT SHUTDOWN YOUR SERVER. (Total size: 1 queries)
[18:30:42] [Timer-81/INFO]: [ChatControlRed] Database batch update is still processing, drink water and DO NOT SHUTDOWN YOUR SERVER. (Total size: 1 queries)

I'm on a mysql DB which isn't that big at all, It happens ALOT and sometimes not at all

**Comment by ElBananaa** [comment]
Reopening as this appears to be a recurring issue, even for users with small databases that are hosted on the same machine than their mc servers.

**Comment by kangarko** [comment]
I apology for my absence, I will get to this in 24 hours.

**Comment by kangarko** [comment]
Sorry for the delay, I was really out of luck reproducing it so I made all of these messages save into sql-batch.log with additional information.

Please use the next update coming up tonight, and upload the newly created sql-batch.log file once you see these messages again.

**Comment by StarozytnySky** [comment]
With latest version ChatControlRed 10.14.5 still appear information about `Database batch update is still processing`
File with sql-batch: [sql-batch.log](https://github.com/kangarko/ChatControl-Red/files/9847206/sql-batch.log)

**Comment by kangarko** [comment]
Thank you, investigating in 1-2 days

**Comment by kangarko** [comment]
I will fix that in todays release coming up later today.
