### ISSUE TITLE
1.16.4 | motd limit hover?

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#213]
mysql: no
Bunge: no

try on Windows and Linux

I don´t know if it consciously, for performance / minecraft limit. But can not put more than 6 hover in motd (it turn off all hover text).

**Comment by jaboy** [comment]
Have you attempted the steps as shown in "common issues" ? 

_**My format does not display hover/click/suggest command and other interactive elements!**
If you format is over 32,000 letters we need to remove those to avoid player from being kicked out. Set "Debug" key in settings.yml to "[component]" to see if there is a console message "Message to X was too large, removing interactive elements to avoid kick." when that happens. Try making your format smaller/less text. Unfortunately this is a hard limit of Spigot._

The 32000 limit might seem like a lot, but it is really not, as all the "behind the scenes" stuff like adding color codes and chat effects all count towards that limit, and they take a huge amount of characters.

**Comment by broken1arrow** [comment]
> Have you attempted the steps as shown in "common issues" ?
> 
> _**My format does not display hover/click/suggest command and other interactive elements!** If you format is over 32,000 letters we need to remove those to avoid player from being kicked out. Set "Debug" key in settings.yml to "[component]" to see if there is a console message "Message to X was too large, removing interactive elements to avoid kick." when that happens. Try making your format smaller/less text. Unfortunately this is a hard limit of Spigot._
> 
> The 32000 limit might seem like a lot, but it is really not, as all the "behind the scenes" stuff like adding color codes and chat effects all count towards that limit, and they take a huge amount of characters.

Thanks, forgot to mention another problem as well, can also not move already existing hover (stops working then too).

So do not really know what causes it. May update with more info when I test.

I upload a image because atom not support this symbols, so when I move one hover the motd get to large (copy paste it and remove it on the old place). I think Gradient: take lots of space too. 
![motd](https://user-images.githubusercontent.com/16368286/100976303-9ab99f00-353f-11eb-985e-810dd9d32403.PNG)

This setup not work (move hover up one step too "välkommen:" , should be in "nyheter:")
https://pastebin.com/Ssdw1iLx

But this do (same amount of text, is under "nyheter:" I move hover in the paste above).
https://pastebin.com/TDdqdF4z

**Comment by kangarko** [comment]
Unfortunately for us, Minecraft builds even the simplest message to the most complicated component. Where you see:

FirstPart:
  Message: Hey
  Hover: Another
SecondPart:
  Message: There
  Hover: Text

is already something like {"text": "", extra: {text: "hey", hover: ["another"]} etc etc}

You can visit https://minecraftjson.com/ to build your format there and see the JSON behind the scenes. We're making the json even łonger because we have to account for the previous color to avoiding it being reset back so that's why the put the colors back each time.

**Comment by broken1arrow** [comment]
> Unfortunately for us, Minecraft builds even the simplest message to the most complicated component. Where you see:
> 
> FirstPart:
> Message: Hey
> Hover: Another
> SecondPart:
> Message: There
> Hover: Text
> 
> is already something like {"text": "", extra: {text: "hey", hover: ["another"]} etc etc}
> 
> You can visit https://minecraftjson.com/ to build your format there and see the JSON behind the scenes. We're making the json even łonger because we have to account for the previous color to avoiding it being reset back so that's why the put the colors back each time.

I understand, but is strange it work on one place in the file but not on an other (with less text). But ether way I think i push this to the limit almost :)
