### ISSUE TITLE
Add Discord message send to switch.rs in BungeeControlRed

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl#2130]
### Summary

When players leave or join the network, or switch from server to server, I want to send a message to a discord channel. I have DiscordSRV installed on my lobby server with all other servers forwarding to it. Everything works as expected, but when attempting to use `then discord 34345etc` inside switch.rs or any BungeeControl file, it does not send a message to the Discord channel.
DiscordSRV messages work fine for everything else though.

I'm guessing BungeeControl does not have this feature, it would be great if it could be added. Perhaps it can forward its Discord messages to the lobby server too since DiscordSRV can't be installed on the proxy.

Here is my [switch.rs](https://pastebin.com/N8fy2D6f) file.

Cheers.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

It's impossible to send messages to Discord for player leave/join events when using a network Bungee setup as DiscordSRV is only installed on one server, and players can disconnect from the network while being on any server within the network. It's also not possible to tell when players switch servers.

**Comment by kangarko** [comment]
Thanks, we aim right now to further simplify the plugin not add more features so I will just hold this for the time being.

**Comment by LeehamElectronics** [comment]
> Thanks, we aim right now to further simplify the plugin not add more features so I will just hold this for the time being.

So there's no way around this that you can think of? Just need a Discord message, or even a web hook  sent when someone switches servers.

**Comment by kangarko** [comment]
No I am sorry, we completely do not support Discord on BungeeControl Red due to lack of infrastructure, I'd have to build a new setup for it for which I have no time at the moment, unfortunately.
