### ISSUE TITLE
All mc versions (happened in 1.16.5 and 1.19.2 for sure). /spy list  <- command malfunction

### ISSUE THREAD

**Issue by KKYH246** [kangarko/ChatControl#2131]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

no visible errors in console

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9640952/debug.zip)

### Information about the issue/bug

After doing /spy list, at least all nicknames reset. im not sure if anything else in the database for chatcontrol is affected. but nicknames, for sure.

and the output for /spy list is definitely incorrect.

![2022-09-25_22 16 22](https://user-images.githubusercontent.com/51881532/192148344-4a9dea2a-7aee-41d7-8a95-a25e886796c8.png)
^ Output right after /spy list in chat.

**Comment by kangarko** [comment]
Please provide enough data, how many players were actually spying? I see that no were reported which is true if no players were spying

**Comment by KKYH246** [comment]
There were 2 people spying on all channels

**Comment by ElBananaa** [comment]
> Please provide enough data, how many players were actually spying? I see that no were reported which is true if no players were spying

I was also able to reproduce this with no one spying. 
Unfortunately I didn't have the time to try to identify the source of the issue.

**Comment by KKYH246** [comment]
The more critical problem to why i created this issue is not because of the spy list cmd not displaying anything even when there are ppl with spy(all channels, signs etc, everything) turned on. <i mean, its still an issue, but its not too big>


Im more concerned about the cmd resetting nicknames(in my case, that was visually obvious ig). idk about other user properties tho, those that belong to chc. (This applies to me using mysql, and even when using a test server with that plugin only, + default settings. None of the config files touched except enabling chat channels)

**Comment by ElBananaa** [comment]
I wasn't able to reproduce the whole nickname reset issue on my side tho.
I'll have a look at this when I get home, later tonight.

**Comment by ElBananaa** [comment]
Alright, I tried to reproduce the nick getting removed, and i'm completely unable to, as shown on this video https://streamable.com/e635cz
