### ISSUE TITLE
1.19.2: out-of-order chat: 't'

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#2132]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Error log (if applicable)

https://gist.github.com/BearLeonLight/cc4a9b3a0b182da14c98563e9131b7db

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9646922/debug.zip)

### Information about the issue/bug

I use 1.19.2 client and server. When I enter `/chc reload`, `/ch join` and other commands in the game, I chat and kick out again, and the error message that the time is out of sync will be displayed.

**Comment by kangarko** [comment]
We do not have this message, seems like a Paper/vanilla bug, mind reporting it there instead?

**Comment by BearLeonLight** [comment]
> We do not have this message, seems like a Paper/vanilla bug, mind reporting it there instead?

I don't know how to report it, and it works fine after I re-adjust the proxy settings.
 
`force-key-authentication=false -> true `
Cooperate with NoEncryption-1.19.2-3.1 to complete the function of closing chat report.

**Comment by TheIntolerant** [comment]
I feel this specific issue is more likely to be related to paper/spigot than vanilla, anyhow, to make a vanilla bug report, you need to head to [Mojang's Official Issue Tracker.](https://bugs.mojang.com/browse/WEB-6118?jql=)

To make a report to Paper, head to their [GitHub page.](https://github.com/PaperMC/Paper/issues)
To mention this issue in another repo on github, just type ``kangarko/ChatControl-Red#2132``

Just so you know for future reference :)

**Comment by kangarko** [comment]
Thanks! 

Yeah just disable auth and use NoEncryption instead, at last your chat wont get reported.

**Comment by BearLeonLight** [comment]
> Thanks!
> 
> Yeah just disable auth and use NoEncryption instead, at last your chat wont get reported.

Sorry I ran into the same problem recently, before `No Encryption` would reverse the connection and get other error messages. Upside-down players cannot enter the server.
I'm not sure which plugin is causing it, I don't have anything going on without any plugins.
I didn't have this problem before entering ch in the game to switch channels, but after entering it, an error occurred.
````
[00:34:44 INFO]: [survival] BearLeon: t
[00:34:46 INFO]: BearLeon issued server command: /ch join survive
[00:34:46 WARN]: BearLeon sent out-of-order chat: 't': 1665246889 > 1665246886
[00:34:46 INFO]: BearLeon lost connection: Out-of-order chat packet received. Did your system time change?
````

**Comment by kangarko** [comment]
Your system time clock may be unsynchronized, the fix depends on your operating system.
