### ISSUE TITLE
1.19.2: Random console error on chat, and Prevent_Spying: True breaks discord functions

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2133]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/50578042d34243bbb0b384dca9e6c491

### Information about the issue/bug

Seems any chat message brings up the error. As well, updated to latest version and enabled the Prevent_Spying to true and it no longer sent messages to the designated discord channel. Switched it to false and reloaded, and messages once again fixed.

**Comment by kangarko** [comment]
Thanks got to fix!
