### ISSUE TITLE
Join & Leave -> TPS improvement?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2134]
### Summary

Hi, I just like to ask if there wouldn't be possibility to improve join & leave events?

I've tried to set join & quit messages async but it didn't help, anything else what can I try? Can be MOTD a thing as well?

https://timings.aikar.co/dev/?id=40a7014f722542e388b2703127d118c7

![image](https://user-images.githubusercontent.com/18662086/192404181-d81de27d-7b6e-4b13-91bb-02632323d531.png)

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

These red numbers will persist

**Comment by ElBananaa** [comment]
Please provide the link to a recent spark profiler report.
As for these "lags", they somehow are to be expected (I guess we could try to improve them but you don't expect anything crazy) with the feature it includes. We do load a lot of different things when players join the server, and we also save a lot of other things when they leave the server.

**Comment by kangarko** [comment]
Please see and read https://github.com/kangarko/ChatControl-Red/wiki/Performance
