### ISSUE TITLE
Better BentoBox support

### ISSUE THREAD

**Issue by emmanuelvlad** [kangarko/ChatControl#2135]
### Summary

Some features are missing or incomplete such as not being able to send messages when the player is not on any island or the `bentobox-island-visitor` not working when being on others people island.

### Expected behaviour

**When not being on an island:** Sends to player's own island  
**When standing in not own island (non-member):**
 | If channel is `bentobox-island-visitor`: read/write messages from the current standing island
 | If channel is `bentobox-island-coop`: check for permissions, then read/write messages from the current standing island
 | If channel is `bentobox-island-trusted`: check for permissions, then read/write messages from the current standing island
 | If it's anything else then read/write from the player's island

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Same as stated in #2075, a very popular plugin coupled with ChatControl-Red will be amazing

**Comment by kangarko** [comment]
What should happen if player is not on any island then?

We do only take the three variables you mentioned from the current standing island already through bentobox API: https://i.imgur.com/H8yY3uu.png -> https://i.imgur.com/nzoaO7z.png

**Comment by TheIntolerant** [comment]
I think they are saying if they are not on an island, the message should get sent to their own island.

**Comment by kangarko** [comment]
Thank you I will solve it, actually ranks other than visitors were broken so I fixed that as well!
