### ISSUE TITLE
1.19.2: no join,quit,death messages sent to Discord

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#2137]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/931f0a3dc5ba45719982656a932724e9

### Information about the issue/bug

After CCR update the error started to happen and no join,quit,death messages are sent to Discord. Error happens on each of these event.

**Comment by TheIntolerant** [comment]
This is potentially linked to #2123

**Comment by kangarko** [comment]
Fixed!
