### ISSUE TITLE
Auto AI Moderation System/Catching or Flagging messages on the fly

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#2139]
### Summary

This would probably be more of an end goal project but an auto-ai moderation system, that doesn't just follow the select rules that are preset. The biggest/only viable competitor for chat filtration and chat moderation plugin to this one has a similar feature, where they have preset rules and on top of that have a completely recoded AI where it auto detects people trying to bypass it and automatically flags messages that may or may not be malicious, including having an option to easily add it to the rules. I'm not gonna state the name of the plugin but I think if something like this gets implemented in the long run then it would greatly boost sales in terms of leading the market because this plugin is absolutely amazing and already excels in most things the other plugin has. 

The main help for this feature would be catching spam and other sorts of messages or flagging it on the fly so that it would lift alot of weight off the moderators shoulders especially when there is none on.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Not having this feature would just mean there will be a more human interaction needed with moderating the chat alongside this plugin, and the rising competitors product looking better in comparison.

**Comment by kangarko** [comment]
Thank you, that looks like an idea for a completely separate plugin. I am open minded to having a look once I have a little bit more time to develop plugins again later this year.
