### ISSUE TITLE
1.16.4 | Timed messages delay works wrongly

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#214]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

I do not know how to properly explain this, but if i have a group of 3 different timed messages with delay of 3 seconds, players will only get the first of them, and the other 2 will never appear

![image](https://user-images.githubusercontent.com/62369973/100924047-248e4b80-34f1-11eb-8241-06e575c6b402.png)
![image](https://user-images.githubusercontent.com/62369973/100923955-09234080-34f1-11eb-849c-332fb6f74d7b.png)

But if i put for example 2 seconds - everything works properly

![image](https://user-images.githubusercontent.com/62369973/100924072-2f48e080-34f1-11eb-9284-b0a9fbfa2be9.png)
![image](https://user-images.githubusercontent.com/62369973/100924116-3f60c000-34f1-11eb-9acc-c9d044a860e2.png)

**Comment by OfT3N** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5635366/debug.zip)
Debug

**Comment by OfT3N** [comment]
UPD: One of a million messages can be different tho :D Maybe changing the current message of the list must be with the same delay as in "delay", or for every message you should take the next message of the list?

![image](https://user-images.githubusercontent.com/62369973/101013452-5943e680-3575-11eb-9b4d-c4821936ff8a.png)

**Comment by kangarko** [comment]
It's intended since we evaluate the last elapsed time and will show the first message all the time since they all have the same delay.

Yes, 1/10000 times it happens because of some micro time difference.

Use different delays for these messages.

**Comment by kangarko** [comment]
Or use multiple messages for one group.
