### ISSUE TITLE
Unable to use Variables from ASkyblock

### ISSUE THREAD

**Issue by KKosyfarinis** [kangarko/ChatControl#214]
Hello,
I am unable to use variables from ASkyblock for some reason. This is my current setup: 

`    Message_Format: '- {ISLAND_LEVEL} - &r%pl_prefix&r{deluxetags_tag}&r&7%displayname &8>>&7%pl_suffix %message'
`

And this is what is displayed in the chat:
{ISLAND_LEVEL} [MyRank] MyName >> My-Message

I have tried using %ISLAND_LEVEL% and this is what is displayed in the chat:
<MyName> My-Message
And console gives me this: 

>17.05 13:27:05 [Server] ERROR Could not pass event AsyncPlayerChatEvent to ChatControl v5.4.4
17.05 13:27:05 [Server] INFO org.bukkit.event.EventException
17.05 13:27:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
17.05 13:27:05 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
17.05 13:27:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
17.05 13:27:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
17.05 13:27:05 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1276) [spigot-1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
17.05 13:27:05 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1214) [spigot-1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
17.05 13:27:05 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
17.05 13:27:05 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
17.05 13:27:05 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
17.05 13:27:05 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
17.05 13:27:05 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
17.05 13:27:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
17.05 13:27:05 [Server] INFO Caused by: java.util.UnknownFormatConversionException: Conversion = ' '
17.05 13:27:05 [Server] INFO at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:100) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
17.05 13:27:05 [Server] INFO at kangarko.chatcontrol.ChatFormatter.onChatFormat(ChatFormatter.java:54) ~[?:?]
17.05 13:27:05 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
17.05 13:27:05 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
17.05 13:27:05 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
17.05 13:27:05 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
17.05 13:27:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-fbb47e8]

I have also tried using  %askyblock_island_world% from PlaceholderAPI as well as {askyblock_island_world}, but nothing seems to be working. Is there a way I could fix this?
Thanks in advance!

**Comment by kangarko** [comment]
Hey,

I've seen you're running ChatControl free. Unfortunately there was no support for PlaceholderAPI in the free version, but I decided to backport it from the premium version for you. A new update should be available tonight.
