### ISSUE TITLE
[Suggestion] Make ChatColor's localization respect Uppercase/Lowercase letters

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2140]
### Summary

My localization message:
```
Color: 
  Success_Color: '&8[&e&l!&8]&7 Set {0} chat color to&7: &f{1}'
```
Output:
![image](https://user-images.githubusercontent.com/87967222/193411534-3b2f5fa5-1aa6-4156-b514-042ea960aadf.png)

When I move `&7` closer to `Set`:
```
Color: 
  Success_Color: '&8[&e&l!&8] &7Set {0} chat color to&7: &f{1}'
```
![image](https://user-images.githubusercontent.com/87967222/193411704-82044748-f131-4e83-89b1-1aa4854167ae.png)

**THE PROBLEM**
1.) As you can clearly see, ChatControl's chat color localization is a little broken. It doesn't respect if any letter is uppercase or lowercase. It just tries to force the first character to be uppercase and every other character to be lowercase.
2.) Another problem here is that it also automatically added a dot at the end of the message, which is not even defined in the localization, making it unable to remove.

I know that Kangarko made this feature that it would be able to change both color and text formatting at the same time, but the localization is pretty hard to understand here and is also missing the options to change it properly, making it hard to work with. Right now, i cannot choose if I want some words to have uppercase letters or not, because CHC just forced it to be like that.

That is why suggestion is to split the chatcolor messages into more sections, where I can edit each one of them. For example one section would be when I changed only color and not the text formatting and another section would apply when I changed both the color and the text formatting at the same time.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Honestly nothing, it just makes ChatControl hard to work with and is missing configuration/localization options.

**Comment by kangarko** [comment]
Thanks, I'll end up with creating multiple keys at the end since our intelligent merging system may produce these unwanted results.

**Comment by kangarko** [comment]
In the next version there will be these new locale keys you can customize 100%
