### ISSUE TITLE
Mention technical limitation in comments for the "Forward_From_Bungee" setting.

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2142]
### Summary

The technical limitation mentioned in issue #1819, is not widely known therefore it would be ideal to have this documented in the config comments above ``IntegrationDiscord.Forward_From_Bungee``, stating the technical limitation of enabling ``Forward_From_Bungee``.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

People could potentially waste their own time trying to figure out why discord messages aren't being received all the time, not realizing that this specific feature if enabled, requires at least one player online for discord messages to be received.

**Comment by kangarko** [comment]
Thanks, I gave you access to our source, not sure why you did not have it previously but right now you should be able to create a simple one liner pull request for this one :) Thanks!
