### ISSUE TITLE
1.18.2: "then discord" rule operator fails to send to discord, logs stack trace to console (offlineSender is null)

### ISSUE THREAD

**Issue by waseric** [kangarko/ChatControl#2143]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/b35148cf97e84dffa22ccab09a1e0a45

### "/chc debug" output (strongly recommended)

from command.rs:
```yaml
# -----------------------------------------------------------------------------------------------
# Private Message logging
# -----------------------------------------------------------------------------------------------

match ^\/m\s|^\/message\s|^\/msg\s|^\/pm\s|^\/r\s|^\/reply\s|^\/t\s|^\/tell\s|^\/w\s|^\/whisper\s
then discord numericchannelid [PM] {player}@{server_name}: {original_message}
then write logs/messages.log [PM] {player}@{server_name}: {original_message}
dont verbose
```

from anvil.rs:
```yaml
match \S
then discord numericchannelid [ANVIL] {player}: {server_name}/{world} @ {x} {y} {z} [ITEM] {original_message}
then write logs/anvil.log [ANVIL] {player}: {server_name}/{world} @ {x} {y} {z} [ITEM] {original_message}
dont verbose
```

### Information about the issue/bug

This is really a continuation of #2123 
While the point of exception has changed, all other symptoms are identical, including the workaround by rollingback to 10.13.7.

When using "then discord" operator in a rule to log messages to discord channel, a warning and stack trace are made on the console, indicating that offlineSender is null.  The message is not sent to the discord channel, but subsequent operators (e.g. "then write <file> ...") do succeed.

This behavior was first observed in 10.13.9, is present in 10.13.10, and is being worked around by a rollback to 10.13.7.
The stack trace has changed with 10.14.1.

Channels with associated Discord_Channel_Id are NOT affected -- messages to a channel continued to go to discord just fine.

**Comment by waseric** [comment]
Since #2123 is Closed.  I did add this information there, but wasn't sure updates would be picked up on a Closed issue.  If 2123 is reopened, current issue (2143) could be closed as a duplicate.

**Comment by TheIntolerant** [comment]
Dupe of #2123

**Comment by kangarko** [comment]
Fixed!
