### ISSUE TITLE
Minor improvement to default "death.rs" file.

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2144]
### Summary

This [file](https://pastebin.com/sA9TvJqf) has some minor changes to it. Those changes being
``#then discord`` replaced with ``#then discord <Discord_Channel_Id> {original_message}``

This makes it faster for server Owner's/Admin to set up the ``then discord`` operator in the death.rs file.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Just means people can enable the discord messages faster especially if they weren't aware of the syntax being ``then discord <channel> <message>``. Which in the past, I have seen a few people ask why it wasn't working which was because they didn't know you needed to include the discord channel ID plus a message with that specific operator for it to work.

**Comment by kangarko** [comment]
What the channel ID should default to if none is specified?

**Comment by TheIntolerant** [comment]
Hmm, I'm not sure. I was just trying to think of a way to make it so people weren't confused with this operator when it wasn't working because they forgot to include the discord channel id and a message

**Comment by ElBananaa** [comment]
I'll have a look to add a better error message for this tomorrow. This is probably the best thing to do

**Comment by TheIntolerant** [comment]
Maybe instead of ``#then discord <Discord_Channel_Id> {original_message}``
It should be ``#then discord <Put_Discord_Channel_Id_Here> {original_message}``

Just because the error message seems to be pretty clear about the issue but that would help prevent the error from happening in the first place since the ``then discord`` part of the death.rs file is commented out by default.

I found the error on discord when someone asked about it https://pastebin.com/j9bFfvWg

**Comment by kangarko** [comment]
Thanks, I will improve on that message today.
