### ISSUE TITLE
Civs Support

### ISSUE THREAD

**Issue by Fenix012585** [kangarko/ChatControl#2145]
### Summary

Hello,
I am hoping you could add support for the Civs plugin. It is a lot like towny or factions and has chat channels for each civilization, nation, etc... It would be great to be able to recreate these channels with chr.

Paid Version - https://mythiccraft.io/index.php?resources/civs-premium.399/
or
Free Version - https://mythiccraft.io/index.php?resources/civs.398/

Thank you for the consideration!

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Any one using this plugin for their server would miss out on the channel features.

The world would not stop or anything, but my server and players would be missing the incredible features of chat control or the special chat channels built in to the civs plugin. Either way it's a huge bummer for us.

**Comment by kangarko** [comment]
Thank you, right now however we are busy and quite small dev team to add infinite integrations, I recommend asking PlaceholderAPI team because we already support that plugin so that they can only make an extension for PlaceholderAPI and any other plugin would support Cive automatically.

**Comment by Fenix012585** [comment]
Thank you so much for the very quick response. If they dill accept it, How can I link chr to the different chat channels? I've never used placeholder api for anything like that before. I've only used it for statistics so far.

Thank you

**Comment by kangarko** [comment]
I see, hmm in that case the other developer would need to use our API and listen to our ChatChannelEvent to properly redirect it based on Civs
