### ISSUE TITLE
Channels Chat per Servers Group

### ISSUE THREAD

**Issue by Floxiik** [kangarko/ChatControl#2148]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Hello, I have 6 servers linked on velocity via BungeeRedis, and I would like to know if it is possible to link 3 servers on the same chat channel and the 3 others on another channel? If so what is the process?

**Comment by kangarko** [comment]
Should be doable, create channels with unique names for the three servers that should share them.
