### ISSUE TITLE
Update to the new ChatControl message sending format

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl#2149]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Information about the issue/bug

@james090500 please update VelocityControl for changes upstream, basically we now send all bungee messages through "BungeeCord" channel and write the channel name as the first argument into the byte array as UTF. Thank you!

**Comment by ElBananaa** [comment]
@kangarko Just had a quick look at the changes you made, but I believe your forgot to add a sub-channel there.
Here's a link to their doc which I believe explains this a bit more in the code examples provided: https://www.spigotmc.org/wiki/sending-a-custom-plugin-message-from-bungeecord/

I also believe Velocity needs you to specify a sub-channel too to send/receive plugin messages (see https://jd.papermc.io/velocity/1.1.0/com/velocitypowered/api/proxy/messages/MinecraftChannelIdentifier.html):

I'm almost certain this is mandatory for BungeeCord, as for Velocity, @james090500 correct me if i'm wrong ^^

**Comment by TheIntolerant** [comment]
Would that explain the error reported here #2151, as I updated and now getting spammed with a ton of errors in the console as soon as someone joined a server (the error is seen on both the proxy server and backend servers)

*im using bungeecord*

**Comment by ElBananaa** [comment]
> Would that explain the error reported here #2151, as I updated and now getting spammed with a ton of errors in the console as soon as someone joined a server (the error is seen on both the proxy server and backend servers)
> 
> _im using bungeecord_

Yeah, I guess it would explain the error reported there. However, I may actually be wrong, as it appears the log message simply says the plugin isn't receiving plugin messages in the right order: `Expected UUID, got PlayerCountWithoutVanished`, and kangarko actually appears to use a sub-channel for messages.

**Comment by TomLewis** [comment]
I will await the velocity update before I can update chatcontrol red!

**Comment by james090500** [comment]
@kangarko Can I get access to CHC Red repo so I can see the changes?

**Comment by kangarko** [comment]
@james090500 sure, sorry about that, was not aware you did not have access. Sorry for the delay also.

**Comment by kangarko** [comment]
@james090500 I fixed a bug in Foundation which we use, see https://github.com/kangarko/Foundation/commit/4bd1753f314109150805c796968cfca781dfd97d before you implement :)

**Comment by kangarko** [comment]
Closing in favor of https://github.com/kangarko/ChatControl-Red/issues/2187
