### ISSUE TITLE
1.19.2: How do I escape characters?

### ISSUE THREAD

**Issue by Kyrobi** [kangarko/ChatControl#2150]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I'm trying to make an auto response system. However, I can't figure out how to escape the $ character.

This is my setup:

![image](https://user-images.githubusercontent.com/20980266/194676036-26606cb6-8818-4491-9718-ddc43bddeb42.png)

Outcome:
![image](https://user-images.githubusercontent.com/20980266/194676041-9aca02bf-2f78-4bf2-93dc-62b1e976573e.png)

**Comment by ElBananaa** [comment]
Hey, use a backslash to escape utf8 characters. So it would look like `\$60,000`

**Comment by Kyrobi** [comment]
Doesn't seem to work.

![image](https://user-images.githubusercontent.com/20980266/194676517-2653497e-d0f6-4601-9758-232ddbb62750.png)

![image](https://user-images.githubusercontent.com/20980266/194676525-106db2ae-183f-44d1-9719-1434a4541456.png)

**Comment by ElBananaa** [comment]
Hmmm alright, that's pretty weird, as it appears to be working fine for me, even without escpaing the $ in the rules file.
![image](https://user-images.githubusercontent.com/53318613/194677200-afe943a5-f3b0-489b-808e-a9f9b455b1a1.png)
![image](https://user-images.githubusercontent.com/53318613/194677204-a516f4e4-179a-40dc-aa8e-61f3a54b979d.png).

Make sure your file is saved in utf8. If it still doesn't work, either try to also escape the `/` before `/warp market` (so `\/warp market)` too.
You can also try to to reproduce the issue on a local test server to see if it works there.

**Comment by Kyrobi** [comment]
Yes, I made sure to save the file in UTF-8. Is there a setting in settings that I have to change or something? I'm testing it on a test server and it still doesn't escape it correctly

![image](https://user-images.githubusercontent.com/20980266/194678311-de5991a6-a136-42b5-a5df-ee3aa217803e.png)

**Comment by TheIntolerant** [comment]
> Hmmm alright, that's pretty weird, as it appears to be working fine for me, even without escpaing the $ in the rules file. ![image](https://user-images.githubusercontent.com/53318613/194677200-afe943a5-f3b0-489b-808e-a9f9b455b1a1.png) ![image](https://user-images.githubusercontent.com/53318613/194677204-a516f4e4-179a-40dc-aa8e-61f3a54b979d.png).
> 
> Make sure your file is saved in utf8. If it still doesn't work, either try to also escape the `/` before `/warp market` (so `\/warp market)` too. You can also try to to reproduce the issue on a local test server to see if it works there.

I believe the reason this works is that there is no 6th capture group in that Regex, so it cannot replace ``$6`` with anything

I'd imagine if you did
``match ^\/(a)(b)(c)(d)(e)(f)`` it would replace ``$6`` with the ``f`` since that is the 6th capture group

**Comment by TheIntolerant** [comment]
I believe the only fix would be to make non-capture groups in the RegEx you are using.

Example of non-capture group
![image](https://user-images.githubusercontent.com/48093184/194685166-328fc676-52fc-43b2-90aa-6fdda59a85c8.png)

And a capture group
![image](https://user-images.githubusercontent.com/48093184/194685189-d9ad7bfa-3790-4f00-9cdf-fce1561e76cd.png)

---

**How Do I make a non-capture group in my Regex?**
Just add ``?:`` inside the brackets, like this
![image](https://user-images.githubusercontent.com/48093184/194685238-1f3aa7d8-c7d2-4be7-bb0b-70fae0f5f68b.png)

**Comment by Kyrobi** [comment]
Okay, this is what I ended up doing
![image](https://user-images.githubusercontent.com/20980266/194691170-8a2f4ca2-033f-4489-ba29-2c6e5d51e851.png)

Thanks for the help!

**Comment by TheIntolerant** [comment]
Glad you got it working! And no problem

**Comment by TheIntolerant** [comment]
Just thought of another workaround, you could also fix this if you need those capture groups, by changing the message slightly, where it looks the same but you insert a colour code after the ``$`` to prevent it from getting replaced.

So instead of
``then warn &a1. Buying it at /warp market for $60,000``
You type it like this
``then warn &a1. Buying it at /warp market for $&a60,000``

It will look exactly the same but because you inserted a colour code in between ``$6``, it prevents it from getting replaced with the 6th capture group in your RegEx.
