### ISSUE TITLE
1.18.2 / Waterfall 1.19 / BungeeControlRed 3.12.1 / ChatControlRed v10.14.3: IllegalArgumentException: Expected UUID spamming console, chat not working.

### ISSUE THREAD

**Issue by waseric** [kangarko/ChatControl#2151]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/58120a32220240e6852137fefc0f3ac5

### Information about the issue/bug

Both server and bungee(waterfall) console being spammed with stack traces following upgrade of both ChatControlRed (10.13.7 -> 10.14.3) and BungeeControlRed (3.12.0 -> 3.12.1)

BungeeControlRed 3.12.1 console:
https://paste.gg/p/anonymous/1ba2adae8e10491981bd6419856f5af7

Worked around by reverting to CCR 10.13.7 and BCR 3.12.0.

No other configuration elements changed.  Will provide more diagnostic data upon request.

**Comment by TheIntolerant** [comment]
Also have this same error, believe this is caused by the changes found here #2146

**Comment by ElBananaa** [comment]
Could you elaborate a bit more on when this happens? I believe kangarko said that this worked fine for him when using commands such as /list, /ignore and even when chatting.

**Comment by waseric** [comment]
This is approximately when the user connects to the server.  

At the timing of these traces, there are a few things going on...  These come after a nightly restart.  All servers are starting (using updated versions of plugins).  Bungee server has just finished startup.  Other servers in the network are still coming up.  server1 in these traces is already up.  It is configured in bungee as a fallback server.  

```
Expected UUID, got PlayerCountWithoutVanished for packet null from server null
Expected UUID, got lobby for packet null from server null
Expected UUID, got server1, server2, server3, server4, server5, server6, server7, server8, server9, server10, server11, server12, server13, server14, server15, server16, server17, server18, server19 for packet null from server null
```
(lobby is same as server1 -- I missed that in my data sanitization efforts.

Best uneducated guess is that BCR is attempting to process traffic from other plugins.
We do have a number of plugins which use bungee channels to talk amongst the servers...  any one of them might be generating these...
BungeeTabListPlus is the one I can share in a public forum.  It has plugins both on the waterfall and paper side.
The player count / server name / list of bungee servers parameters we see in these examples would all make sense in context of btlp.

Happy to share full plugin list privately.

**Comment by ElBananaa** [comment]
> This is approximately when the user connects to the server.
> 
> At the timing of these traces, there are a few things going on... These come after a nightly restart. All servers are starting (using updated versions of plugins). Bungee server has just finished startup. Other servers in the network are still coming up. server1 in these traces is already up. It is configured in bungee as a fallback server.
> 
> ```
> Expected UUID, got PlayerCountWithoutVanished for packet null from server null
> Expected UUID, got lobby for packet null from server null
> Expected UUID, got server1, server2, server3, server4, server5, server6, server7, server8, server9, server10, server11, server12, server13, server14, server15, server16, server17, server18, server19 for packet null from server null
> ```
> 
> (lobby is same as server1 -- I missed that in my data sanitization efforts.
> 
> Best uneducated guess is that BCR is attempting to process traffic from other plugins. We do have a number of plugins which use bungee channels to talk amongst the servers... any one of them might be generating these... BungeeTabListPlus is the one I can share in a public forum. It has plugins both on the waterfall and paper side. The player count / server name / list of bungee servers parameters we see in these examples would all make sense in context of btlp.
> 
> Happy to share full plugin list privately.

Alright, thanks, I don't need we need anything more. I simply needed more informations about this, but yeah, this most likely happens because the plugin is basically trying to process any plugin message sent on the BungeeCord channel, as it appears @Kangarko forgot to also use a sub-channel dedicated to chc for these messages.

**Comment by NoobcoreNetwork** [comment]
https://pastebin.com/faKHCcRG

Hey yeah. just updated to latest, 1.5mb of log files in 3 mins gonna have to pull back to the older build

**Comment by x1p** [comment]
> https://pastebin.com/faKHCcRG
> 
> Hey yeah. just updated to latest, 1.5mb of log files in 3 mins gonna have to pull back to the older build

My bungee log is 300 mb. Ruined my day for sure.

**Comment by ElBananaa** [comment]
> > https://pastebin.com/faKHCcRG
> > Hey yeah. just updated to latest, 1.5mb of log files in 3 mins gonna have to pull back to the older build
> 
> My bungee log is 300 mb. Ruined my day for sure.

Kangarko should have a look at this soon, so just be patient.
For now, the temp fix is as simple as you simply have to drag & drop previous version for both bungeecontrol & chatcontrol-red, that's it. This shouldn't take a day, it shouldn't even take more than 2 minutes to achieve ;)

**Comment by x1p** [comment]
Oh I am very patient. I just reverted to the last working plugins.
I was just referring to the log file that grows rapidly in these kinds of situations.
I'm sure it will be resolved soon enough.

**Comment by ElBananaa** [comment]
Unfortunately, yes, and I can't assist Kangarko on this as I have no way to test any changes I would make ^^
(+ I only have a very small experience with plugin messaging)

Anyways, Kangarko will most likely have a look at this on monday or tuesday, as he usually is busy/away during weekends

**Comment by celciusjj** [comment]
Same issue here!

and come back to previous version and spam this message
![image](https://user-images.githubusercontent.com/37490999/195475677-6b0e7e99-1adf-4404-8be5-cbf29dcf92e7.png)

**Comment by celciusjj** [comment]
@ElBananaa some way to solve solve spam problem ?

**Comment by ElBananaa** [comment]
> @ElBananaa some way to solve solve spam problem ?

For now, I suggest your revert both ChatControl & BungeeControl to the previous version publicly available.
Here's the full post I sent on our discord about this.
![image](https://user-images.githubusercontent.com/53318613/196058637-93575db6-6514-4093-8a5b-2d72cd0ddf1c.png)

As for an ETA for a fix, well, I can't give any. @kangarko seems to be busy with other stuff.

**Comment by celciusjj** [comment]
> Same issue here!
> 
> and come back to previous version and spam this message ![image](https://user-images.githubusercontent.com/37490999/195475677-6b0e7e99-1adf-4404-8be5-cbf29dcf92e7.png)

@ElBananaa nono, i come back to previous versión in both plugin and now i have this spam message
@compile chat message 
do you know the solution for it?

**Comment by ElBananaa** [comment]
Afaik this isn't a chc-red message @celciusjj, as I have never seen this previously + there's no such log message in chatcontrol. So i guess this comes from another plugin.

**Comment by TheIntolerant** [comment]
For 10.14.2 in the change log on builtbybit, it says 

> Note: There is a developer leftover message ``@Compile chat message`` in the console, ignore this. It will get removed in the next release.

If the spam is super annoying, you could downgrade to 10.14.1 but please make sure to read the change log provided under the "updates" tab for the plugin page, so you are aware of any changes made

**Comment by ElBananaa** [comment]
> For 10.14.2 in the change log on builtbybit, it says
> 
> > Note: There is a developer leftover message `@Compile chat message` in the console, ignore this. It will get removed in the next release.
> 
> If the spam is super annoying, you could downgrade to 10.14.1 but please make sure to read the change log provided under the "updates" tab for the plugin page, so you are aware of any changes made

I didn't even notice this, well, thanks for letting me know :)

**Comment by kangarko** [comment]
I will make a public statement about this, in short, I disappeared for 12 days without announcement due to personal regards (not that this is an excuse), and this issue has been related to us in fact reading data from other plugins. Will be fixed urgently within a few hours.
