### ISSUE TITLE
Bungee spy on channels

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/ChatControl#2152]
### Summary

The idea that I have and some others as well either in discord or here in the posts is the possibility to be able to spy on specific channels throughout bungee.
Being able to see what gets said on the server where staff isn't would be great as when you don't have staff you will be able to see what other people say as well as in a way (The way how people talk) you can see what they are doing and what happens on the server without being there.

Banana already made a version for me to test out and it works great being able to enable and disable it for specific channels works great.

Here are some GitHub request that has a similar request or intention and if I ask around in discord there are many people who would like the same.
#1549 #1924 and #1199

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

I have a small staff team that can't be online on all servers, I don't want to enable bungee chat as it is confusing for normal players to see chat across servers.
By seeing chat messages you can see what is happening on your server and you can see where you need to go and where to help.

**Comment by mcer10081** [comment]
this would be very useful

**Comment by kangarko** [comment]
I apology for my absence, I will get to this in 24 hours

**Comment by kangarko** [comment]
Added! (see the changelog and drop a review if you enjoyed it :))
