### ISSUE TITLE
1.19.2: out-of-order chat: 't'

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#2153]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Error log (if applicable)

https://gist.github.com/BearLeonLight/c7272e5ca00528f34ee4076ab6dd1832

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9739825/debug.zip)

### Information about the issue/bug

kangarko/ChatControl-Red#2132
Continuing, I also have this problem when using very few plugins.
`10.14.3`, `10.14.2`, `10.14.1`
The error is also generated with only 5 plugins
`[00:59:41 INFO]: Plugins (7): ChatControlRed, LuckPerms, PlaceholderAPI, PluginManager, ProtocolLib, TAB-Bridge, Vault`
I also removed all plugins on velocity

**Comment by BearLeonLight** [comment]
To add again, in the end there are only two plugins left with the same problem.
`[01:04:54 INFO]: Plugins (2): ChatControlRed, LuckPerms`
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9739846/debug.zip)

**Comment by BearLeonLight** [comment]
PaperMC/Velocity#876
Said to be caused by paid plugins.

**Comment by ElBananaa** [comment]
After searching your issue on google for 5 minutes, it appears that all users who had this issue fixed it by syncing their system clock:
https://www.reddit.com/r/minehut/comments/va9wp0/server_keeps_kicking_out_members_i_need_a_fix_for/
https://www.spigotmc.org/threads/sent-out-of-order-chat.570272/

Also make sure both Velocity and papermc are up to date.

**Comment by BearLeonLight** [comment]
> 

Yes, I am using the latest version. My time zone synchronization is WIN11, and I am using automatic synchronization. The source is the default.

**Comment by BearLeonLight** [comment]
In addition, I haven't encountered this problem since I installed ViaVersion, and I don't know why, it's amazing.
I had errors with only that CHC state, but after including ViaVersion it was fine.

**Comment by kangarko** [comment]
If they come back again, disable our protocollib integration by setting Integration.Protocol_Lib.Listen_For_Packets to false in settings.yml, as that might have been the cause. I will need to do some more testing, was not able to reproduce yet.
