### ISSUE TITLE
1.19.2 vanish bug?

### ISSUE THREAD

**Issue by NoHoPeLess** [kangarko/ChatControl#2154]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/ef30fc534cdc4455b868e5fba3001565

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9740340/debug.zip)

### Information about the issue/bug

Hello, i have an strange error on join, what is this?

**Comment by ElBananaa** [comment]
Hey, this is an issue related to the latest chc-red & bungeecontrol-red versions. Revert to the previous version of both plugins for the moment. I'm closing this, so we can continue on #2151
