### ISSUE TITLE
1.19.2: Duplicate Discord messages

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2157]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

N/A

### Information about the issue/bug

No console output or other changes, simply updated to get rid of that null pointer exception brought on by the 14.0 version. Now updated to newest .3 and all messages sent to the discord channel are duplicated.

**Comment by Kielczi** [comment]
@HorusApl did you fix this problem cause i have the same on my "standard" channel?

**Comment by kangarko** [comment]
Read our Wiki about Discord, we have some advice there
