### ISSUE TITLE
Bungecord problems integration

### ISSUE THREAD

**Issue by celciusjj** [kangarko/ChatControl#2158]
the chc debug
https://easyupload.io/dzmlbh

(Ufile.io had problems for me)

### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

Hello,

I have problems configuring chatcontrolred with bungecord.

I followed all the steps, configure mysql, enable bungeecord in configuration, put the bungecordred plugin, put server-name in server properties and they don't end up appearing when I use the chc forward command

I will leave images of everything, so you can see how I have configured it

![image](https://user-images.githubusercontent.com/37490999/194983653-390e2b45-c026-45f6-aa30-31d5837132d4.png)
here you can see how the other available servers do not appear

in settings.yml
`
  BungeeCord:
    Enabled: true
    Prefix: '&8[&dBungee/{bungee_server_name}] '
`

In bunge config, i remove the ips for security
`  dungeons:
    address: XXX
    motd: '&1Just another Waterfall - Forced Host'
    restricted: false
  provincia:
    address: XXX
    motd: '&1Just another Waterfall - Forced Host'
    restricted: false`

server name in server properties, obviously also put the dungeons on the other server
`
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
server-name=provincia
prevent-proxy-connections=false
hide-online-players=false
`

I checked and the database if it has the information, but it doesn't want to read the bungecord, I think.

So, i send this message for bungee, and never come
![image](https://user-images.githubusercontent.com/37490999/194993664-d5f3293e-6502-46bc-b336-f7802dd1cad1.png)

I would also like to know if it is possible to make all messages global, that a player writes something in "province" and they can read it in "dungeons".

Thank you

**Comment by ElBananaa** [comment]
Hey, the latest version of both chc-red and bungeecontrol appears to be broken. Please try to revert to the previous version for both plugins to dee if it helps.

As for doing what you want with messages, yes this is possible. Simply make sure all channels are synced across your network, and simply make your players join these channels in read mode.

**Comment by celciusjj** [comment]
Excuse me, I had 2 previous versions of chatcontrol and that was the problem, now I updated everything and it works.
