### ISSUE TITLE
Error report keep sending while running server

### ISSUE THREAD

**Issue by Lemonray114** [kangarko/ChatControl#2159]
I have some error while turn on server, not sure what cause the problem, 
here's the report
https://paste.gg/p/anonymous/004d12e993ba437e8d942b7bfd982b42   ChatControl-Red-10.14.3
https://paste.gg/p/anonymous/e0a4223781914b75ba0e589c3ee2ce30   BungeeControl-Red-3.12.1 

plugin version:
ChatControl-Red-10.14.3   
BungeeControl-Red-3.12.1

**Comment by ElBananaa** [comment]
Dupe of #2151
Follow what we said there
