### ISSUE TITLE
Mute and Spam Bypassing

### ISSUE THREAD

**Issue by kevblue264** [kangarko/ChatControl#216]
This is an amazing plugin, but I am currently experiencing some troubles with guests being able to bypass the chat mute feature and the chat spam and time delay feature, I did negate the permission node, but it seems to still not be working :(

**Comment by kangarko** [comment]
Hey,

apologies for the delay. The permissions that allow bypassing are not given by default, so they should not be allowed to bypass it if you did not change any ChatControl's bypass-related permissions. Make sure you did not give your guest permissions with '*', as this will override the subpermissions (chatcontrol.* allows all bypasses).

Which permission plugin are you using btw?

**Comment by kangarko** [comment]
I am closing this as per the 8-day no reply policy. I hope it's been all fixed, please write below if you're still experiencing issues.
