### ISSUE TITLE
[Question] Bungee join/quit messages

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#216]
So I added the ''bungee'' syntax, but now those messages also show up on server switch. Could I make it so they only show up on network join instead?

**Comment by NerdyBirder** [comment]
There is a setting in the settings.yml for BungeeControl-Red to allow/disallow messages when players switch bungeecord instances. Just remove the message to not have that announcement.

**Comment by Sikatsu** [comment]
This doesn't have to do with bungeecontrol though, but with the new .rs files from chatcontrolred ^^

**Comment by kangarko** [comment]
Sorry this is not possible right now because we don't "see" players switching. The Bukkit server thinks they've just joined. I'll keep an eye on a potential solution though.

**Comment by Sikatsu** [comment]
Hmm if we can't deny server switch then I guess the bungeecontrol option is better, altho I can't make it with groups through there. Hopefully in the future this can be improved :)

**Comment by kangarko** [comment]
Yep, for now I recommend using BungeeControl, thanks for your input!
