### ISSUE TITLE
1.19.2: Hex Colors in Chat | Parse Update [Req]

### ISSUE THREAD

**Issue by KhaozFrost** [kangarko/ChatControl#2161]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Most Plugins use the full minimessage system; I was wondering if you could also include support for using
<code> more specifically the <> being able to be also used here.
CMI nick parses both regardless but other plugins don't typically parse the hex code alone so wondering if you could just allow both options. 
![image](https://user-images.githubusercontent.com/15788954/196303580-d27be1af-318d-4fc4-a419-6037b7fbbf38.png)

**Comment by kangarko** [comment]
Thanks, right now we just use our own format system in formats or the \# directly in chat, but I will consider this later as this is coming up again and again lately.
