### ISSUE TITLE
1.19.2: "Expected UUID, got..." error with BungeeControlRed with latest ChatControlRed

### ISSUE THREAD

**Issue by addstar** [kangarko/ChatControl#2164]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/d39a2ac922604eb49f10cb38be0cbd0e

### Information about the issue/bug

Same as the issue you found in #2149 but needs to be fixed for BungeeChatControl.

We just updated to ChatControlRed 10.14.4 + BungeeControlRed 3.12.1 and I noticed the ChatControlRed fix for the "Expected UUID" error here https://github.com/kangarko/Foundation/commit/4bd1753f314109150805c796968cfca781dfd97d.

But I think the same fix needs to be made in [here](https://github.com/kangarko/BungeeFoundation/blob/master/src/main/java/org/mineacademy/bfo/bungee/BungeeListener.java#L184) in BungeeControlRed.

**Comment by Tazler89** [comment]
Having same problem here. please help.

**Comment by kangarko** [comment]
Thanks, solved!

**Comment by Tazler89** [comment]
when will update be ? to fix this ?, can't see any new release.

**Comment by kangarko** [comment]
In about 60 mins :)

**Comment by Tazler89** [comment]
seems to all be working great, amazing, thanks for getting that sorted 👯
