### ISSUE TITLE
1.19.2 : strange log

### ISSUE THREAD

**Issue by NoHoPeLess** [kangarko/ChatControl#2166]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/e080223084524caf8e44d691c8131f93

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9842825/debug.zip)

i think i cant do /chc debug because its seems the error/bug is on the bungeecord...

### Information about the issue/bug

I just wanted to report the error.
The error fills my log to extreme size...

greetz noho

**Comment by TheIntolerant** [comment]
Please update ChatControlRed to ``10.14.5``
Also update BungeeControlRed to ``3.12.2``

**Comment by NoHoPeLess** [comment]
@TheIntolerant it solved it, thanks <3
