### ISSUE TITLE
1.18.2: Entity deaths spam chat if theres a lot of entities 

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2167]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

Ignore the XP dupe, thats another bug.

For some reason when using many [cannons ](https://dev.bukkit.org/projects/cannons) that shoot many projectiles to kill a player, ChatControl spams the living crap out of chat, is it trying to detect entities around a player? and then listing all entities that killed them?

https://www.youtube.com/watch?v=kC6tzDiPEEI

**Comment by ElBananaa** [comment]
We don't run any weird checks when parsing death messages.
Iirc, we do use spigot's api to check for the last damage done to the player before they died to show the death cause, so I guess this happens either because one of your plugin is canceling the death event multiple times, as example.

Maybe this comes from your cannon plugin doing very tricky things? Or maybe the factions plugin, because in the video you provided we can clearly see that the player is somehow not losing life but still taking damages a dozen of times before instantly dying.

**Comment by TomLewis** [comment]
>  because in the video you provided we can clearly see that the player is somehow not losing life but still taking damages a dozen of times before instantly dying.

That's something I also missed, very weird.

Damange done to the player could be a trigger, as these cannons are sending many multilpes of projectiles to the player, as what they are doing is setting multiple cannons off at once, using redstone to mass-shoot projectiles, so if a single shot kills it dousnt do this in chat, only for a mass redstone chain of cannons firing.

**Comment by ElBananaa** [comment]
> > because in the video you provided we can clearly see that the player is somehow not losing life but still taking damages a dozen of times before instantly dying.
> 
> That's something I also missed, very weird.
> 
> Damange done to the player could be a trigger, as these cannons are sending many multilpes of projectiles to the player, as what they are doing is setting multiple cannons off at once, using redstone to mass-shoot projectiles, so if a single shot kills it dousnt do this in chat, only for a mass redstone chain of cannons firing.

Well I don't know how your cannons plugin works, but yeah, this is something that's definitely not caused by chatcontrol, as death messages are only sent when the PlayerDeathEvent event is triggered. So nothing's wrong on our end.

**Comment by kangarko** [comment]
At the end of the day I could add a simple de-duplicator, going to have a look into this tomorrow or on Monday.

**Comment by ElBananaa** [comment]
> At the end of the day I could add a simple de-duplicator, going to have a look into this tomorrow or on Monday.

Well, I doubt this will solve the true problem. I guess the best thing to do would be to identify the exact cause of the issue, and since Chatcontrol only looks for the PlayerDeath event, it would be like applying a dressing to treat a hemorrhage ^^

**Comment by kangarko** [comment]
Banana is right, this appears to be a problem in how your third party plugin handles deaths. Try setting Debug to ["operator"] and see if this message gets spammed in the console:

![a](https://i.imgur.com/497fYlF.png)

If yes, then it means you need to prevent player from dying not by setting his health back in the PlayerDeathEvent, but rather cancelling EntityDamage-related events. By fixing your death event it will also fix issues with other plugins you may not see now.

Matej

**Comment by TomLewis** [comment]
Any idea how I can figure out which plugin is causing the change to my death event? 
Could be literally anything, PvPManger, CMI, Essentials, Recount, SimpleClans, GriefPrevention, maybe the cannons plugin itself is changing the death event when cannons are fired? 

Im assuming, its something I will have to get fixed by whichever plugin is doing it at developer level?

**Comment by kangarko** [comment]
Hmm great question. How is it that the player should die instantly after getting hit as you shown on the video above? Start there. 

Probably I would look into plugins modifying that behavior, modifying damage, or the cannon plugin.
