### ISSUE TITLE
1.18.2: Waterfall BungeecontrolRed error

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#2168]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://gist.github.com/MithrandirCraft/c277e6aa4bbfbe20dc2e45d8ff5366dc

### Information about the issue/bug

It's an error that regularly spams on the waterfall console.

**Comment by ElBananaa** [comment]
Dupe of #2151.
Update chatcontrol-red and BungeeControlRed.
