### ISSUE TITLE
[Issue] Mutechat not giving feedback

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#217]
Performing /mutechat doesn't seem to give any feedback in the chat.

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

**Comment by broken1arrow** [comment]
> Performing /mutechat doesn't seem to give any feedback in the chat.
> 
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true

 Minecraft Version: 1.16.4
 MySQL: false
 BungeeCord: false
version cc: 10.1.5

work for me in 
![mute](https://user-images.githubusercontent.com/16368286/101136965-5ea13f80-360e-11eb-891e-7eeda3759d84.png)

**Comment by Sikatsu** [comment]
This is /mutechat <player> I think, could you try /mutechat to mute the whole chat?

**Comment by broken1arrow** [comment]
> This is /mutechat I think, could you try /mutechat to mute the whole chat?


/ mutechat does not exist for me is it another plugin?

Tested / mute server and / mute channel "channel name" works fine

**Comment by Sikatsu** [comment]
You're right, this is from LiteBans and related to another issue I had. Whoops! Thanks for testing.
