### ISSUE TITLE
Way to send the /msg from Discord

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2170]
### Summary

Hello, could it be possible to somehow send /msg via Discord? So like by some rules or some feature that can catch /msg and then sent it in-game?

Like if I type: /msg playername <text> on Discord it would send the text into the game to the player msg.

Although I'm not really sure how to receive response them, if it would be possible somehow. Or may only way to send it without receiving responses.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

It can be useful for players if they would like to communicate privately from Discord with some other players in-game.

**Comment by kangarko** [comment]
Thanks, sure, that is doable but not in my current time I have for development. I would suggest you look into getting a developer to create a small addon for this. If they used Foundation it would be quite simple: ![a](https://i.imgur.com/vmG8LT3.png)
