### ISSUE TITLE
Partial Plugin Reloads

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2171]
### Summary

Running /chc reload has quite a massive performance hit and even with just a small handful of players on, will instantly drop TPS and noticeably so. With more players on, reloading the plugin is a good 3-5 second freeze of the entire server. So if I want to quickly add a timed broadcast, change the motd, edit a single variable, or other small change then I best not be doing it during peak hours or players will feel it. 

I'd like to suggest partial plugin reloads. Example: "/chc reload Books" or "/chc reload motd" or "/chc reload formats" and then move the main reload to "/chc reload all"

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Just makes the plugin easier to edit without wrecking players experience, as currently most server owners would have to wait until after peak times to even think of editing this plugin.

**Comment by kangarko** [comment]
Due to reload safety we have to reload mysql on the main thread, this takes some time. At present there is no plan to split the reload command, but rather I am interested in experimenting running mysql reload async and reducing reloading time, thanks for your feedback.
