### ISSUE TITLE
Velocity-Purpur 1.19.2: Connection to MySQL Database

### ISSUE THREAD

**Issue by scarlettcloud** [kangarko/ChatControl#2172]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/94786f5ac41b40d9bb15eb5f11dd1bd0

### "/chc debug" output (strongly recommended)

Plugin is disabled because of the lack of connection, cannot run /chc debug

### Information about the issue/bug

I'm not entirely sure what started the issue or whether it's related to my database v. chatcontrol (I think database) but I'll try to give a step by step of what I did leading up to this.

Be me, running velocity network, trying to set up a fourth server for hardcore.

Also me, it would be cool to use custom rank tags and icons in chat! I'm going to use items adder. Okay great, that works awesome for the tablist, but I really want them to show up in chat as well!

Also me, "eh the instructions for this texture pack don't say how to do this for ChatControl, let's try what I do for my existing tags"

And (where I think) the FU was: If I just go into luckperms and set the prefix for the admin group to prefix.:admin_tag::admin_nameplate: it should be fiiiine right?? 

Run /chc reload, db connection lost and chatcontrol disabled. Okay, no sweat, maybe that's an operator that breaks the tables??? no idea. 

Being me in this scenario means you don't understand mysql at all (still don't) but I know that chatcontrol will make my tables again if I just delete and reset the database? Cool, do that. Nope, no cigar. 

Console output says that I should run FLUSH HOSTS, okay great, don't have permissions to run that in my database. 

I'm in the process of asking to Bisect (my host) to run this command but they're re-running through all the troubleshooting steps that I've run. I'm at a loss at this point. I have no idea if it's at all related to the colon operator in a prefix or what but none of my servers' chatcontrols (except the Hub server that the database is on) will connect to it. 

I'm 99% sure that I've just done something stupid to cause this but the console says to send you guys my error log so here you go.

**Comment by scarlettcloud** [comment]
ISSUE PART TWO: THE SWEET SWEET RESOLUTION!!!!! Updating this just in case someone runs into this issue ever again.

Here's what to watch out for in your console:

[26.10 12:58:07] [Server] [INFO] !-----------------------------------------------------!
[26.10 12:58:07] [Server] [INFO] Failed to connect to database
[26.10 12:58:07] [Server] [INFO] URL: {redacted}
[26.10 12:58:07] [Server] [INFO] Error: Report: Could not make new instance of public com.zaxxer.hikari.HikariDataSource(com.zaxxer.hikari.HikariConfig) with params: com.zaxxer.hikari.HikariConfig@7579629b
[26.10 12:58:07] [Server] [INFO] Plugin is now disabled.
[26.10 12:58:07] [Server] [INFO] !-----------------------------------------------------!

Specifically, if the error tells you to run flush hosts on your mysql database, do it. 

After 5 hours of back and forth with my host not believing me that this was the problem, it indeed, fixed the problem. :D listen to the almighty console. 

to the chat control devs who might see this i love you i love the plugin hope you enjoyed this epic saga.

**Comment by kangarko** [comment]
Thanks for sharing!

Summary: If you get **Could not make new instance of public com.zaxxer.hikari.HikariDataSource(com.zaxxer.hikari.HikariConfig) with params: com.zaxxer.hikari.HikariConfig@7579629b**

**Fix**: Run "flush hosts" SQL command on your mysql database.
