### ISSUE TITLE
How can configure correctly the formats? 

### ISSUE THREAD

**Issue by gabriel262m** [kangarko/ChatControl#2173]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I recently start to use chat control red, i cant make the formats works, it show some like the essentials default format, but i dont have essentials chat installed, i follow the guide in wiki, my config looks like this 
Parts:
  Prefix:
    Message: '&8[&6VIP&8] '
  PlayerName:
    Message: '{player_name} '
  Message:
    Message: '{message} '

![Sin título](https://user-images.githubusercontent.com/48396708/199895548-5dbb12aa-7a5f-4e71-be2d-e4f0ebdbac2d.png)

settings: 
  List:
    standard:
      Format: prueba
      Format_Spy: '@noprefix chat'

**Comment by TheIntolerant** [comment]
This is most likely because you haven't enabled the "channels" in your settings. Please check that this has been enabled.
![image](https://user-images.githubusercontent.com/48093184/200140348-1e5c4417-6893-4bc0-b729-6feb792c036b.jpeg)

**Comment by kangarko** [comment]
Closing, lemme know if you need more help
