### ISSUE TITLE
1.19.2: require killer script condition doesn't work

### ISSUE THREAD

**Issue by Chiruso** [kangarko/ChatControl#2175]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

I tried to use the **require killer script** condition to create personalizated kill messages
I have this variable:
```
Type: FORMAT
Key: "spooky_activated"
Value: |-
  isSpookyActivated();
    function isSpookyActivated() {
      var usermeta = "{luckperms_meta_mensajes.personalizados}";
      var message = "spooky";

      if (usermeta == message) {
        return true;
      }
      else {
        return false;
      }
    }
Sender_Condition: ""
Receiver_Condition: ""
Sender_Permission: ""
Receiver_Permission: ""
```
and this death message:
```
group spooky
require cause ENTITY_ATTACK
require killer PLAYER
require killer script {spooky_activated}
message:
- &c☠ &c{killer} &6asustó a &c{player}
- &c☠ &e{killer} &faterrorizó a &c{player}
- &c☠ &e{killer} &fhorrorizó hasta la muerte a &c{player}
```
But the message is only sent when the VICTIM has the **mensajes.personalizados** key with the **spooky** value setted.
What I need is that the message is sent when the KILLER has that meta key

**Comment by kangarko** [comment]
Thanks, going to fix in the next version for tonight!
