### ISSUE TITLE
1.19.2: Send Announcement as a command on first join.

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#2176]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hi, i've looked at motd first join and i can see that you can send a message with a click command but that's not what i want.

I want to send players on first join, an image message as you show under super cool messages.

I have the command and message setup ready but i can not see a way to send it to a player on first join?

**Comment by 00Hrtz** [comment]
I've tried with parts: message: and all i get is 
![2022-11-06](https://user-images.githubusercontent.com/66942713/200154443-541a836d-8e70-4c69-b95b-427f30834783.png)

**Comment by 00Hrtz** [comment]
I've set it to run in console in the settings yml under motd but the problem there is i don't really want it run on console, i tried to run as player but it kept saying i needed to give players the announce permission which i also dont really want to do?

**Comment by TheIntolerant** [comment]
Dupe of #2122

**Comment by TheIntolerant** [comment]
Currently, the usage of the "image" feature is limited to the announcement command (which shows the image to everyone). So adding images via MOTD etc is not possible.

**Comment by 00Hrtz** [comment]
> Currently, the usage of the "image" feature is limited to the announcement command (which shows the image to everyone). So adding images via MOTD etc is not possible.

I'm not looking to use images inside formats, i want to run the image from settings yml via the motd player command without having to give all players the announce command permission so this is not a duplicate.

**Comment by TheIntolerant** [comment]
I understand, but regardless of how this is achieved it would still have the same outcome.

**Comment by 00Hrtz** [comment]
> I understand, but regardless of how this is achieved it would still have the same outcome.

No it wouldn't,  /chc image can already be used under motd in settings yml via command console or player. the issue is to use command player, you have to give all players the announce permission which i do not want to do. I want to run the /chc image command via player without the need to give the permission. I'm currently running it via command console under motd.  So my question for the Developer is, can he allow it so that a permission is not needed to run under command player.

**Comment by TheIntolerant** [comment]
It would be easier to code it to support a ``player:`` parameter in the command itself. Similar to the ``server:`` parameter which can be used to send such messages to a specific server.

Assuming you are trying to send the message to that player only, which is why you don't want to run it via console?

**Comment by 00Hrtz** [comment]
yeah, just want to basically send the /chc image message to each player on firstjoin and or join. but not via console or the need for a perm. At the moment it works under settings.yml >motd >command >player but it requires all players to have the announce permission. 

bypassing having to create a format or use console. It's pretty much already possible aside requring the announce permission.

**Comment by TheIntolerant** [comment]
Ah okay, well hopefully this isn't too time-consuming to add, as it *should* be easier than adding support for images via formats!

Just have to wait for the developer to see what he can do.

**Comment by kangarko** [comment]
Thanks, I take this as a suggestion. My time is very limited these weeks but if TheIntolerant or ElBanana want to make the code changes I'd be welcome.

**Comment by ElBananaa** [comment]
Well, as kangarko said on #2178 I won't work on any new feature unless at least 40 or 50 people ask for it, so I don't waste the small amount of free time I have working on features that won't be added, sorry.

**Comment by 00Hrtz** [comment]
> Well, as kangarko said on #2178 I won't work on any new feature unless at least 40 or 50 people ask for it, so I don't waste the small amount of free time I have working on features that won't be added, sorry.

It's not even a new feature, the features already added, the request was to allow the use of motd>player command without the need for each player who receives the message to need a permission but, thanks for not reading, understanding and your lack of consideration of the actual request (not a new feature request at all), totally appreciated. 

Also thanks for closing before the others decide if they would consider doing it.

**Comment by ElBananaa** [comment]
> > Well, as kangarko said on #2178 I won't work on any new feature unless at least 40 or 50 people ask for it, so I don't waste the small amount of free time I have working on features that won't be added, sorry.
> 
> It's not even a new feature, the features already added, the request was to allow the use of motd>player command without the need for each player who receives the message to need a permission but, thanks for not reading, understanding and your lack of consideration of the actual request (not a new feature request at all), totally appreciated.
> 
> Also thanks for closing before the others decide if they would consider doing it.

- I did read your message, and I perfectly understand it. As TheIntolerant said, "It would be easier to code it to support a `player:` parameter in the command itself", that's a fact, and this would be a new feature for the announcement command, that's a fact too.
- As for consideration of the actual request, a true lack of consideration would've been to close this issue directly without even answering you.
- I did not close your issue.

If you somehow are upset with us denying this, then read the issue I mentioned above (because you clearly didn't read it, otherwise you wouldn't have said half of the things you said in your message). Kangarko explained there why we are denying this feature request.

**Comment by kangarko** [comment]
I am going to run a survey about this to see how many people need this, and of course will add this if we have many requests. Thanks for understanding.
