### ISSUE TITLE
1.17.1 - Issue with chat, when a variable is used.

### ISSUE THREAD

**Issue by RandomUser4510** [kangarko/ChatControl#2177]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

No

### Question

How to disable "variables"? 
There is a variable that is the [item] that is in conflict with my plugin that I already have for THAT!!! 
HOW DO I REMOVE???
![Screenshot_1](https://user-images.githubusercontent.com/106982801/200188525-f9452c50-2746-4dde-8dbf-9105b197bb3f.png)

**Comment by TheIntolerant** [comment]
Just remove the file found here ``/plugins/ChatControlRed/variables/item.yml``

**Comment by RandomUser4510** [comment]
I keep having the problem...
But if I remove the chatcontrol plguin my plugin works

**Comment by RandomUser4510** [comment]
Everytime I do [i] , I get that mensage...

**Comment by RandomUser4510** [comment]
Everytime I do [i] , I get that mensage...
![Screenshot_1](https://user-images.githubusercontent.com/106982801/200188932-430c3a7b-841e-4abb-82ac-15f4a99547f5.png)

**Comment by TheIntolerant** [comment]
In that case I would suggest providing your debug file ``/chc debug``, so this can be looked into.
If you want to keep your settings private Upload the ZIP file to [ufile.io](https://ufile.io/) then email the link to [support@mineacademy.org](mailto:support@mineacademy.org)

**Comment by RandomUser4510** [comment]
I also have this problem, where the chat cooldown is not working properly...

To me looks like this:  (Screenshot 1)
![Screenshot_1](https://user-images.githubusercontent.com/106982801/200204708-128a9422-e0e9-41da-926e-f802e7db35c7.png)

For other people look like this: (Screenshot 2)
![Screenshot_2](https://user-images.githubusercontent.com/106982801/200204732-69fc0495-789d-445f-b8f2-7885868f9f67.png)

**Comment by kangarko** [comment]
Follow instructions from TheIntolerant and then we can help you
