### ISSUE TITLE
Adding support for fadein, fadeout and stay on then title

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#2178]
### Summary

Currently we are able to use 'then title' within different areas of the CHCR plugin but not customize the amount of time / fade in / fade out that the title stays on screen for. I think it would be awesome to have this customizability so we can produce things like "then title Welcome to my server! fadein: 2 stay: 10 fadeout: 2"

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Not implementing this feature leaves less customizability for the 'then title' feature. Currently there is no way to control how long the title is on screen for and a player may miss the message!

**Comment by kangarko** [comment]
Thanks, right now definitely not a priority, we're trying to keep things simple

**Comment by ElBananaa** [comment]
Alright @kangarko I just made a PR to implement this feature in chatcontrol-red. I tested it myself and it works flawlessly, so feel free to merge.

**Note: this remains simple as players don't need to specify any values, and it'll still work**

**Comment by kangarko** [comment]
As I said in the pull request, I really want to keep the vision of chatcontrol that of a simple plugin, no reason to add million features because 1 person asks for it

I am going to start deleting features that were added from 1 person requesting them from now on since it's going to kill us in the long term

**Comment by kangarko** [comment]
For the sake of transparency here is what I said on the private commit:

<img width="918" alt="Screenshot 2022-11-11 at 14 51 27" src="https://user-images.githubusercontent.com/1918426/201365048-32eccf5e-ece1-44b2-88aa-0ef70ff3f7f3.png">

**Comment by TZ122** [comment]
Can I assume we will not see this in ChatControlRed then? We are able to use fadein fadeout and stay in the /chc annonce command already seems odd to me that we cannot use it in other places in the plugin.

If im understanding correctly previously implemented features will be removed from the plugin overtime as well? Makes me extremely hesitant to upgrade in that case would hate to use old versions of software but I do see where you guys are coming from. 

Thanks

**Comment by ElBananaa** [comment]
> Can I assume we will not see this in ChatControl then? We are able to use fadein fadeout and stay in the /chc annonce command already seems odd to me that we cannot use it in other places in the plugin.
> 
> If im understanding correctly previously implemented features will be removed from the plugin overtime as well? Makes me extremely hesitant to upgrade in that case would hate to use old versions of software but I do see where you guys are coming from.
> 
> Thanks

You can get a free upgrade to chatcontrolred if you are a previous owner of ChatControlPro, simply send an email to support@mineacademy.org with a proof of ownership like the paypal invoice and your builtbybit profile link

**Comment by TZ122** [comment]
> > Can I assume we will not see this in ChatControl then? We are able to use fadein fadeout and stay in the /chc annonce command already seems odd to me that we cannot use it in other places in the plugin.
> > If im understanding correctly previously implemented features will be removed from the plugin overtime as well? Makes me extremely hesitant to upgrade in that case would hate to use old versions of software but I do see where you guys are coming from.
> > Thanks
> 
> You can get a free upgrade to chatcontrolred if you are a previous owner of ChatControlPro, simply send an email to [support@mineacademy.org](mailto:support@mineacademy.org) with a proof of ownership like the paypal invoice and your builtbybit profile link

Sorry I think were at a misunderstanding -  I own Chatcontrolred was just confused by the above replies, it seemed that it was implemented then rejected just want to confirm if it will be added or not so i know whether or not to search for a separate plugin for my title message to control the fading in or out.

**Comment by kangarko** [comment]
I rejected it but then ElBanana already did all the work and it was basically a push-button decision so I wanted to acknowledge his work and given the minority of this feature I decided to pull it. It will come to the next release about tonight :)
