### ISSUE TITLE
1.19.2: Console Spam "generated an exception while executing task 152"

### ISSUE THREAD

**Issue by Sqbri** [kangarko/ChatControl#2179]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/3cac44c937ca46728419d3dab6ce34f6

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9962143/debug.zip)

### Information about the issue/bug

N/A, nothing has been changed in the config files yet, this happened right after installing & restarting my server, there is no error that pops up when starting up the server

**Comment by kangarko** [comment]
You closed the ticket, I assume it got fixed. Lemme know if otherwise.
