### ISSUE TITLE
[Issue] Can't leave party spy and spy duplicates

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#218]
We can't seem to leave the mcmmo party spy channels. And it shows messages of our own party chat. 

We actually use the built-in party spy from mcmmo, so I wonder if we can just toggle mcmmo spying off?

![image](https://user-images.githubusercontent.com/5664135/101085243-785f6a00-35af-11eb-90fa-3f82b9073978.png)

![image](https://user-images.githubusercontent.com/5664135/101085258-7bf2f100-35af-11eb-8826-1c51d5921487.png)

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

**Comment by Sikatsu** [comment]
After a while it even triples the messages..

![image](https://user-images.githubusercontent.com/5664135/101091264-3981e200-35b8-11eb-8972-80e668723c22.png)

And then also quatriple a bit later..

![image](https://user-images.githubusercontent.com/5664135/101092021-47843280-35b9-11eb-921b-9b6a986124c4.png)

**Comment by broken1arrow** [comment]
Has not try party (not use mcmmo party). But no problem on normal channels to turn off spy.

Has you check /spy menu if mcmmo show up?

And i think you only need one plugin some spy on the chat (you will probably get  such errors you got here) :)

**Comment by Sikatsu** [comment]
McMMO doesn't show up there, I wish I could just disable it. I am using mcmmo's party spy (and even if I turn it off, this happens)

**Comment by broken1arrow** [comment]
> McMMO doesn't show up there, I wish I could just disable it. I am using mcmmo's party spy (and even if I turn it off, this happens)

ask suport on mcmmo too, for me is one chat good enough :) only chat i try is for a plugin call lands (only too see if it works now when red has  support).

Has you set up this?

```
    mcmmo:
      Format: '[&blands&f] {pl_suffix}{player}&f:&b {message}'
      Format_Console: '&bland-&f{player}:&b {message}'
      Party: mcmmo-party
```

**Comment by Sikatsu** [comment]
Hmm no I haven't, that's why I don't understand why ChatControl is spying on mcmmo actually. Can I turn it off if I add that?

**Comment by broken1arrow** [comment]
> Hmm no I haven't, that's why I don't understand why ChatControl is spying on mcmmo actually. Can I turn it off if I add that?

i think soo.

**Comment by Sikatsu** [comment]
For now I disabled spying on ''chat'' since I don't actually need that at all, but maybe @kangarko can add an option to turn off mcmmo spy in general ^^

**Comment by kangarko** [comment]
The recommended way is to create a channel with Party set on mcmmo-party. I will however fix the duplication. How to reproduce the duplicated messages? What commands were run when the duplication started?

**Comment by Sikatsu** [comment]
Ah, yeah it currently seems to make a channel for every mcmmo party. I however dont need mcmmo spy and could not seem to turn it off. The duplication happens kver time and gets worse and worse. I couldn't find a reason as for why it happened.

**Comment by kangarko** [comment]
I can add a toggle for mcmmo spy. Will investigate the duplication.

**Comment by Sikatsu** [comment]
Thanks! If I can be of any more help let me know.

**Comment by kangarko** [comment]
Added Format_Party_Chat option to settings in Spy section. Setting this to "none" should prevent message from appearing
