### ISSUE TITLE
Watchdog Timeout from network connection

### ISSUE THREAD

**Issue by Qballl** [kangarko/ChatControl#218]
On a sever that I am co-owner on and uses chatcontrol because of me is now crashing duw to a network connection taking too long in the main thread. From my understanding of spigot coding connections of any sort should be asynchronous. Please fix this. Link to time out https://pastebin.com/p0jyRKdu used pastebin cause I making this on my phone

**Comment by mixaxdd** [comment]
Have a some problem
https://timings.spigotmc.org/?url=hifikuqiko

**Comment by kangarko** [comment]
Hey,

I apologies for the delay. Please see https://github.com/kangarko/ChatControl/issues/217

Notice I made the connection asynchronous in the next release. I have tested it, but please let me know if issues arise/persist.
