### ISSUE TITLE
1.19: Integration.BungeeCord.Prefix

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#2181]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

How is Integration.BungeeCord.Prefix in settings.yml supposed to work? The comment above the line says "The optional prefix before all messages so that you know where they are coming from."

My interpenetration of this is that all messages sent from the server are prefixed with the value set, so that you know which server the message originated from. However, in practice it appears to be the opposite: Messages are prefixed with the value BY the server the message appears on.

For instance, I have two servers (creative and survival) that share a chat through CHC. If I want messages sent FROM creative to appear with a "[Creative] " prefix, I have to set __survival's__ Prefix tag with that value, and vice-versa for creative.

This seems backwards, though, because the comment implies that the server sending out the message is the one prefixing it. It also doesn't appear expandable like this because if I add a third server (Skyblock, for example) there is no way for the Survival server to determine if a message is coming in from there or from Creative, if the Prefix for Survival is set as "[Creative] ".

I might be misunderstanding the purpose of the prefix system altogether. I'm just not sure if this is intentional behavior or a bug.

**Comment by kangarko** [comment]
Sorry for the delay; I unfortunately can't reproduce. Try hardcoding the prefix into Integration.BungeeCord.Prefix section of settings.yml for the two servers, it did worked for me — also make sure you have the latest BungeeControl

<img width="808" alt="Screenshot 2022-11-15 at 18 41 21" src="https://user-images.githubusercontent.com/1918426/201999973-f6937b9b-5c14-4b75-8bd6-aebbe87433a2.png">
<img width="903" alt="Screenshot 2022-11-15 at 18 41 26" src="https://user-images.githubusercontent.com/1918426/201999980-fa9facbb-be8e-4bc5-98e8-7f8e7bed106e.png">

Let me know below if you need more help.

**Comment by BakiDance** [comment]
I should be running the latest version (BungeeControl-Red-3.12.2). This must be a bug then... I recorded a couple videos of what I'm experiencing. 

https://youtu.be/yd2AosiGH_I
https://youtu.be/5iyvHl3NGQI

In both videos, the creative config and client are on the right, and the survival config and client are on the left. This is verifiable by watching the changes occur as I reload both individually, but also at the start of one of the videos I have the "Grammar" rules applied to Creative, but not Survival.

When I add my own values to BungeeCord.Prefix, similarly to how you've done, they still apply to the wrong servers.

It seems that I SHOULD be able to set the Prefix for my creative config to '[Creative]', and it would show up in the Survival chat with that prefix, but that is not my experience. Instead, messages from creative are appearing in survival with the prefix defined in the survival config, and vice versa.

**Comment by kangarko** [comment]
Could you please upload /chc debug from these two servers just so I can test it?

**Comment by BakiDance** [comment]
[survival_debug.zip](https://github.com/kangarko/ChatControl-Red/files/10043959/survival_debug.zip)
[creative_debug.zip](https://github.com/kangarko/ChatControl-Red/files/10043960/creative_debug.zip)

**Comment by kangarko** [comment]
Sorry for the delay. I am missing something or are the BungeeCord prefixes opposite? I opened survival_debug.zip to find the (C) prefix, assuming it was for Creative server and (S) I saw in creative settings. Place that in the Creative server's settings.yml instead. Sorry if I missed something, just let me know below!

**Comment by BakiDance** [comment]
That's exactly why I opened this issue. The prefixes ARE opposite and they *need* to be or else they will display the wrong info. Based on what you've described with your images, I'm assuming what I'm experiencing is a bug.

If I make Creative use (C), and Survival use (S), for the prefix setting, the chat will display the wrong prefix for each, making messages coming from Survival look like they're coming from Creative; the prefixes aren't applied correctly, so I had to switch them. Of course, this means if I add a third server eventually, there is no way to make the prefixes look "correct" (how I have it now is a hack to get around the issue).

Thank you for your help so far, by the way. I hope what I'm describing makes sense (even if the issue doesn't, lol).

**Comment by kangarko** [comment]
Try the next version please, keep the prefixes in the right order i.e. creative has C and survival has S. I have no idea why they are flipped but things work properly on my latest built that has some bungee changes so hopefully that will get solved automatically as well. Let me know how it goes! (Update both CCR and BungeControl, they will be out in 1-2 hours)

**Comment by BakiDance** [comment]
I swapped my prefixes so that they're in the correct order (creative has C and survival has S), and updated ChatControl across all my servers (v.10.14.9) and my proxy (v3.12.3). The issue still persists. Messages coming from survival are mislabeled with (C), and messages coming from creative are mislabeled with (S).

If required I can screenshare on Discord at some point. I am in the Mineacedemy Discord server.

**Comment by kangarko** [comment]
@ElBananaa are you able to help please? I am unavailable for the required time due to family reasons

**Comment by ElBananaa** [comment]
@kangarko Will try to have a look asap, but this will most likely be in a few days as i'm currently busy with work all day ^^

**Comment by kangarko** [comment]
@ElBananaa okay thank you :)

**Comment by ElBananaa** [comment]
Hey, so I did actually manage to run some tests last night, and it appears the prefix are shown in the right order as long as you use the `{bungee_server_name}` operator in the `Bungeecord.Prefix` section of your server. However, if you decide to hardcode a custom prefix directly there without using this operator, the prefix gets reverted.

I can't do anything much about this for now. I'll see if I find the time to take a deeper look at it at the end of the month or early next year during my vacations.

**Comment by BakiDance** [comment]
Sounds good, thank you. I would like to use a hardcoded prefix just to keep chat clean. I do hope this is something that can be fixed.

**Comment by ElBananaa** [comment]
Well, you should still be able to hardcode the prefix in your bungeecontrol settings file.
This is how it looks like on my side:
```yaml
Server_Aliases: 
  test1: "Test Server 1"
  test2: "Test Server 2"
```

then use the `{bungee_server_name}` operator in each `Bungeecord.Prefix` part of your chatcontrol config file.

**Comment by kangarko** [comment]
@BakiDance try the advice from @ElBananaa :) looks like the reversal is by design since the hardcoded variable will always be of the sending server not the receiving one
