### ISSUE TITLE
1.19.2: Deleting messages not working on ProtocolLib (5.0.0)

### ISSUE THREAD

**Issue by Sqbri** [kangarko/ChatControl#2182]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

No errors

### "/chc debug" output (strongly recommended)

[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/9980877/debug.1.zip)

### Information about the issue/bug

When trying to delete a message sent in chat, it spams the chat with stuff from other plugins and some other weird stuff
Example: https://gyazo.com/8cdd71ba5979aaed75d2ac6884c2e79f

**Comment by kangarko** [comment]
This is an incompatibility with the custom health/icon plugin, unfortunately we were not able to find a solution for the time being :(

**Comment by Sqbri** [comment]
I have contacted the developers of mmocore which is the plugin that broke it, they are interested in fixing the issue but they have asked me to give them the jar file to be able to work on it, do I have your permission?

**Comment by kangarko** [comment]
Sure :)
