### ISSUE TITLE
1.19.2 Database connection problems

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#2183]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://pastebin.com/h72RHEWu

### Information about the issue/bug

I did `chc reload` to make a change in rules effective.
Chatcontrol gave an long and extensive error basically saying it could not connect to the database.
After that it kept nagging about:
`[20:57:34] [HikariPool-3 connection adder/WARN]: [org.mariadb.jdbc.message.server.ErrorPacket] Error: 1040-08004: Too many connections`

The database has no connection limit

**Comment by kangarko** [comment]
Going to test myself in 24h

**Comment by x1p** [comment]
I tried to reproduce it on my test server but haven't been able to. I guess 20+ players + dynmap + logblock have put some strain on it too but that's just a wild guess.
I do have a feeling that putting the database string to `jdbc:mysql://` is somehow more stable. With `jdbc:mariadb://` I sometimes get a message saying
`[com.zaxxer.hikari.util.DriverDataSource] Registered driver with driverClassName=org.mariadb.jdbc.Driver was not found, trying direct instantiation.`

**Comment by kangarko** [comment]
Can you try this on your test server > run "SHOW PROCESSLIST;" SQL command on your database and then notice in the table if connections are being duplicated without being closed on each /chc restart?

**Comment by x1p** [comment]
Indeed it grows and grows every reload
With 1 test server: it starts with about 13 and increases by 10 every reload.
I guess that is multiplied by the number of servers that use the same database on the production bungee-network.

**Comment by kangarko** [comment]
That's bad. It means I didn't code it to close connections. Which means more reloads = more db load. This is urgent, going to prioritize first thing tomorrow.

**Comment by kangarko** [comment]
Sorry it's taking this long, I am not forgetting and working on this

**Comment by kangarko** [comment]
Should be fixed now!
