### ISSUE TITLE
player tag nick change event

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#2184]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

hi what is this event called and fired ?

**Comment by kangarko** [comment]
Hi, I am sorry we don't have such event. Would you be interested in having one? How would you like to use it?

**Comment by FakEEE14** [comment]
hi
i want to set a cooldown on a nick command but when the nick acutally changes and don't get cooldown when it's says it's in use

**Comment by kangarko** [comment]
You can just catch the nick command using PlayerCommandPreProcessEvent
