### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by celciusjj** [kangarko/ChatControl#2186]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://pastebin.com/Ys3vnQRJ

### "/chc debug" output (strongly recommended)

https://ufile.io/grm8yjy2

### Information about the issue/bug

I have a multiserver, i change the server from one to another, that are connected to the same mysql.
when player joins the console make multiples spams and does not load  my server.
![image](https://user-images.githubusercontent.com/37490999/202581712-af6584b3-88d0-4293-a210-1d5d1de173e8.png)

**Comment by TheIntolerant** [comment]
Please update to ``10.14.8`` and let us know if you are still having this issue

**Comment by kangarko** [comment]
Update chatcontrol

**Comment by kangarko** [comment]
@TheIntolerant have you noticed less people opening issues since we added "Are you using latest version" question? This guy clearly ignored it and I am afraid most people just mindless tick it so it's kinda pointless to have, unless you've noticed a dip.

**Comment by ElBananaa** [comment]
> @TheIntolerant have you noticed less people opening issues since we added "Are you using latest version" question? This guy clearly ignored it and I am afraid most people just mindless tick it so it's kinda pointless to have, unless you've noticed a dip.

You should replace the checkbox with a `Plugin version:` part in which users would have to include the output of the `/chc` command. If the plugin is up-to-date, we will answer the issue, if it's not (and the user didn't explain why they didn't update) we'll simply close the issue and ignore it.

**Comment by TheIntolerant** [comment]
Made a pull request which includes the suggested change by banana
