### ISSUE TITLE
1.16.5: not working on velocity for the latest version

### ISSUE THREAD

**Issue by NebulusFR** [kangarko/ChatControl#2187]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Error log (if applicable)

No error

### Information about the issue/bug

Hello, i can't use a version above: ChatControl-Red-10.13.10
Not working with Velocity
Plugin say i'm not connect on the bungeecord

**Comment by kangarko** [comment]
@james090500 can you please have a look?

**Comment by NebulusFR** [comment]
With channels

**Comment by DJIronic** [comment]
So, is there any ETA on the velocity control? It is linked on the plugin page, so we thought it was maintained the same as the plugin.

**Comment by NebulusFR** [comment]
I didn't understand. When will the problem be fixed? I can't update my Chatcontrol version without this patch

**Comment by ElBananaa** [comment]
Sorry if I wasn't clear enough.

Unfortunately, there is no eta for an actual fix to this issue as the velocity version is basically not handled by Kangarko.

However, if you guys are willing to run tests, I could provide you a VelocityControl test version. If you are interested, DM me on discord: Bananaa#1471

**Comment by NebulusFR** [comment]
No problem. When will he be back? I added you on Discord, thanks for the answers

**Comment by ElBananaa** [comment]
> No problem. When will he be back? I added you on Discord, thanks for the answers

I personally have no idea, seems like we've all been unable to reach him lately unfortunately.
@kangarko

**Comment by NebulusFR** [comment]
I see

**Comment by james090500** [comment]
@ElBananaa  if you can submit a PR i'll happily merge it if it works. I haven't been able to test my changes at all recently

**Comment by DJIronic** [comment]
I also sent you a request @ElBananaa . As we are also stuck on an older version. And to be honest, it was a not great experience to purchase a plugin and then spent 5+ hours debugging whats going on and finding the velocity addon just does not work with the latest version.

Also, please change wording on the plugin site, as it seems like the velocity connector is just another part of your plugin and everybody expects that your plugin works with your addon...as it really should for 30 USD puchase :)

**Comment by ElBananaa** [comment]
> @ElBananaa if you can submit a PR i'll happily merge it if it works. I haven't been able to test my changes at all recently

@james090500 I'm also busy right now, so, as I said to NebulusFR on discord, it'll take a few days until I have enough free time to work on something. So feel free to make changes, and i'll see if I find some free time to test your changes ^^

@DJIronic It's not up to me to make changes on the BuiltByBit page (I don't have accesses there anyways), but I don't really know what needs to be changed to the wording.

You should have a look about this with @kangarko directly (or you can email him: matej@mineacademy.org)

**Comment by kangarko** [comment]
I apology for the inconvenience.

Just to clear up > My coding skills cover the Bukkit API and Bungee which means I can ship immediate updates to ChatControl [Red] and BungeeControl. 

But not to VelocityControl, that's simply out of my skill hence I found a volunteer James who can maintain it in his spare time. I should probably add a note about this somewhere to set the expectation.

**Comment by kangarko** [comment]
@james090500 can you please set an expectation when you will be available? You're the only maintainer of VelocityControl for the time being, I'd need to find someone else if you're no longer available :/

**Comment by editon96** [comment]
Then PLS @kangarko make you Bungeecontroll RUN in **Snap** its an Plugin for Velocity that let run Bungeecord Plugins under Velocity.

**Comment by kangarko** [comment]
I dont have time for maintaining Velocity it's always been volunteer driven

**Comment by TomLewis** [comment]
So does this mean i cant update ChatControl if im using velocity? 
We cant use Waterfall as there are very simple methods to crash it/time everyone out.

**Comment by james090500** [comment]
I have been ill recently but will look at this hopefully over the next few days. The issue is I can't test the plugin because I need an alt. 

If anyone is able to test keep an eye on my posts in the discord server.

**Comment by Lorias-Jak** [comment]
How can i join the Discord? I have an alt and we have an velocity network. I would help, if im at home when the test is needed

edit: found it

**Comment by james090500** [comment]
Update: We run into a small hurdle, speaking with @kangarko on next steps

**Comment by kangarko** [comment]
Sorry that it took me so long to get back, was out of office. Working on this asap right now.

**Comment by kangarko** [comment]
Discussing options with James right now

**Comment by ElBananaa** [comment]
@kangarko It would be nice to add a contributor channel to discord, and give all the contributors and the mod team access to it, so we could all get in touch with each others faster and also helping in such issues, whether by making suggestions to solve an issue or even to simply try potential changes ^^

**Comment by DJIronic** [comment]
Hello, so is there any progress on this?

**Comment by editon96** [comment]
Obversly not that is why I change temporally to a other Chat Plugin and hope they get it. And make it possible to update Velocity Controll when Chatcontrol is updated.

But the only thing you can do are hopping or learning how to make that on you own...
@DJIronic

**Comment by james090500** [comment]
We know the issue, I've been speaking with @kangarko about what we both need to do.

It's a bit of a long winded fix but it is being worked on.

**Comment by DJIronic** [comment]
OK, is there any ETA? Its crazy to still be on an older version, not having features we purchased the plugin for..

**Comment by james090500** [comment]
As with everything it takes time. 

A rushed project is not a good project.

**Comment by TomLewis** [comment]
Velocity support should be added to the BungeeControl Red plugin, most plugins bundle it all together in one jar and not separate them, so that all development is kept updated together.
Especially since that everyone recommends Velocity over bungee as a proxy nowadays.

**Comment by ElBananaa** [comment]
> Velocity support should be added to the BungeeControl Red plugin, most plugins bundle it all together in one jar and not separate them, so that all development is kept updated together. Especially since that everyone recommends Velocity over bungee as a proxy nowadays.

The problem is not the plugins being in separate jar files, because currently there's no interest at all at using a single jar file for both plugins.
The thing is, as kangarko said, he doesn't have the time to read all velocity docs and learn how to use their api.

As for velocity being recommanded over bungee, yeah that's true, but still, velocity's api lacks a lot of features, and velocity pretty much has no plugin support compared to bungee...

That being said to avoid any issues, kangarko should definitely add a big disclaimer on the plugin page, warning users about velocity being partially supported and being maintained by another developer.

**Comment by kangarko** [comment]
Sorry my current knowledge of Velocity API is close to zero plus my time is spread out on non Minecraft related projects. I maintain Bungee and Spigot part, and a volunteer does Velocity. 

Having said that I made the requested changes to ChatControl and BungeeC and Velocity should get updated shortly :)

**Comment by kangarko** [comment]
@james090500 please let us know when you update it! (The channel to listen to we now broadcast at is plugin:chcred)

**Comment by ElBananaa** [comment]
@kangarko Getting back to using the `plugin:chcred` channel won't also bring back the `unknown custom packed identifier` issue? Or did you simply mean that you use `plugin:chcred` as a subchannel and `BungeeCord` as the main channel for plugin messaging?

**Comment by james090500** [comment]
> @kangarko Getting back to using the `plugin:chcred` channel won't also bring back the `unknown custom packed identifier` issue? Or did you simply mean that you use `plugin:chcred` as a subchannel and `BungeeCord` as the main channel for plugin messaging?

This error was due to something different.

**Comment by ElBananaa** [comment]
> > @kangarko Getting back to using the `plugin:chcred` channel won't also bring back the `unknown custom packed identifier` issue? Or did you simply mean that you use `plugin:chcred` as a subchannel and `BungeeCord` as the main channel for plugin messaging?
> 
> This error was due to something different.

Are you sure about this, because using the wrong channel for plugin messaging was clearly identified as the cause of the `unknown custom packed identifier` error spam in client logs, not only by Kangarko, but also by other devs that faced the same issue. The plugin also stopped spamming this error as soon as Kangarko switched to the BungeeCord channel.

**Comment by james090500** [comment]
You aren't meant to use the bungeecord channel for anything but bungee. A custom channel is more than fine. This issue is due to packets being sent to the target player instead of target server.

**Comment by ElBananaa** [comment]
> You aren't meant to use the bungeecord channel for anything but bungee. A custom channel is more than fine. This issue is due to packets being sent to the target player instead of target server.

Seems weird, I'm pretty sure velocity has a config option (which, I believe, is set to true by default) to support messages coming from the BungeeCord channel, but I guess I either misunderstood this, or I did see it somewhere else x). Anyways, in the end I really think spigot docs about plugin messaging are confusing, and the fact that Velocity seems to handle things completely differently is not helpful.

**Comment by james090500** [comment]
Said config options turns on BungeeControl channel handing so you can do this: https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/

Anyway I am slightly wrong, the errors are actually due to packet handing issues. I am investigating

**Comment by ElBananaa** [comment]
> Said config options turns on BungeeControl channel handing so you can do this: https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/
> 
> Anyway I am slightly wrong, the errors are actually due to packet handing issues. I am investigating

Yeah I kinda understood that too, I still think spigot's documentation about plugin messaging is not intuitive at all but hey, at least someone finally managed to get this right!

Anyways, thanks for looking into it, i'll go to sleep less dumb tonight :)

**Comment by james090500** [comment]
Hi everyone,

VelocityControl 3.11.0 is out which supports the latest ChatControl Red release! (10.16.0)

https://github.com/kangarko/VelocityControl/releases/tag/3.11.0

This issue has actually been a blessing in disguised as it's allowed me and @kangarko to have a real good look on how we are sending messages between servers. These changes will make updates easier!

@ElBananaa This line, was the "custom packed" issue. Packets were getting forwarded to the client:
https://github.com/kangarko/VelocityControl/blob/main/src/main/java/org/mineacademy/velocitycontrol/listener/VelocityControlListener.java#L124-L125

**Comment by ElBananaa** [comment]
Awesome! I guess @Kangarko should also make the changes to BungeeControl if that's not already done ^^

**Comment by kangarko** [comment]
James advised me to use Server#sendPluginMessage. I have tested it and it appears to work, but the message spam log is back.

@james090500 can we keep the communication here for simplicity? I have replied both on Discord and here thanks!

![2022-12-18-08 12-157](https://user-images.githubusercontent.com/1918426/208286076-7a42894d-198a-4123-a5cf-7cb8f5c89081.png)

**Comment by james090500** [comment]
Hi @kangarko please review this PR - https://github.com/kangarko/BungeeFoundation/pull/6

This should fix the unknown custom packed for the BungeeCord plugin

**Comment by kangarko** [comment]
Amazing work, thank you!

**Comment by NebulusFR** [comment]
Thanks!
