### ISSUE TITLE
1.19 Some variables not working in chat

### ISSUE THREAD

**Issue by GreenFlameblade** [kangarko/ChatControl#2189]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

When I use the {player_server} variable/placeholder inside my  chat format, it displays as literally {player_server}. What am I doing wrong? Other variables work just fine, and I have the bungee extension installed on my Waterfall server.
![2022-11-18_17 43 07](https://user-images.githubusercontent.com/118574096/202815311-d3284b5f-071f-4a9f-b346-85b3b4d8926a.png)

**Comment by TheIntolerant** [comment]
If I recall correctly, these specific [variables](https://github.com/kangarko/ChatControl-Red/wiki/Variables#bungeecontrol-red-variables) cannot be used on your backend servers, they can only be used on the proxy server (aka your waterfall server). 

These types of variables can only be used in messages sent directly via BungeeeControl-Red, for example, in the join/switch/quit messages on BungeeControl-Red.

**Comment by GreenFlameblade** [comment]
Okay, thanks. Knowing that, I managed to get the result I wanted by using world names instead of server names.

I have another small question. I made a chat channel named 'help', but whenever I try joining it, it just brings up the help menu. I was going to remove the help permission, but I couldn't find any. How do I set up a channel named 'help' so that I can join it by typing "/ch j help"?

**Comment by TheIntolerant** [comment]
> I have another small question. I made a chat channel named 'help', but whenever I try joining it, it just brings up the help menu. I was going to remove the help permission, but I couldn't find any. How do I set up a channel named 'help' so that I can join it by typing "/ch j help"?

Hey, so I would assume this going to be a case where you are unable to use that specific word. My suggestion would be to use a synonym for the word "help" such as "assistance", "support", "advice" or
"guidance", otherwise you could use "help-chat" as the channel name etc. Hope that helps

**Comment by kangarko** [comment]
I am sorry, TheIntolerant is right, you can't really use /ch j help since it is a reserved keyword. Just use an alternative channel name such as "helpop" or "support".
