### ISSUE TITLE
[Issue] Lava deathmessages don't work

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#219]
I imported my deathmessages:

```
group lava
require cause LAVA
message: 
- &3{player} &7heeft een bad genomen in een meer van lava
- &3{player} &7probeerde een lava lamp te maken met echte lava
- &3{player} &7probeerde te zwemmen in lava
- &3{player} &7is een inventaris vol spullen verloren in lava
- &3{player}'s &7laatste woorden waren 'Heet, Heet, Heet' in de &Clava

```

![image](https://user-images.githubusercontent.com/5664135/101086334-fff9a880-35b0-11eb-8328-c3b2fbbf47e1.png)

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

**Comment by broken1arrow** [comment]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false
version cc: 10.1.5

Get no msg ingame for lava (is import from cc 8). try other death and these work (will check older versions).

```
group lava
require cause LAVA
message: 
- &e{player} &7trodde det gick bada i lava
- &e{player} &7trodde det gick ta upp lava med händerna
- &e{player} &7man ska inte mina rakt ner
- &e{player} &7var törstig och tog fel
- &e{player} &7dansade i lavan
- &e{player}&7försökte ta diamanterna och föll i lava

```

**Comment by Sikatsu** [comment]
These work or do not work for you? Not sure if it's related to the '' in the last deathmessage

**Comment by broken1arrow** [comment]
> These work or do not work for you? Not sure if it's related to the '' in the last deathmessage

not work at all ingame (get no msg player get kill in lava), other death msg work (but have not test all)

**Comment by ElBananaa** [comment]
Hey!

I just checked on spigot, and the LAVA cause exists for the death reasons. (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html)

Even tho, I also have the same issue, and I noticed an error in the console. I don't know if it happens with some other death messages, but I guess since it looks like the plugins tried to check if the death if caused by a lava block. https://pastebin.com/s58YD61f

And yeah, some messages are working perfectly fine.

**Comment by kangarko** [comment]
Works fine as long as you have the LAVA cause on top of the file and it doesn't get handled by anything else. Just move it right to the top:

![a](https://i.imgur.com/zeRa3JL.png)

**Comment by Sikatsu** [comment]
Alright that seems to work, but why does it only work if it's on top of the file? It makes more sense to be near the ''Drowning'' death messages, and I assume people in the future won't always place this on top of the file and run into the same issue?

**Comment by kangarko** [comment]
Not sure, if we match any condition above it, we apply that instead.

**Comment by Sikatsu** [comment]
Hmm odd since drowning and such works, I mean it works for me now but might still be a question that will be asked in the future!

**Comment by kangarko** [comment]
I updated the wiki article thank you!

**Comment by broken1arrow** [comment]
> Works fine as long as you have the LAVA cause on top of the file and it doesn't get handled by anything else. Just move it right to the top:
> 
> ![a](https://camo.githubusercontent.com/b2dd67c1a52ad5a539a98b63cd306d06a03df684dbc21bd1bfde3fa6a5f83742/68747470733a2f2f692e696d6775722e636f6d2f7a655261334a4c2e706e67)

If it need bee on top you have to update the cc 8 to cc 10 migration.

**Comment by broken1arrow** [comment]
and i generate new files.

And "group lava" is on line 347.

**Comment by broken1arrow** [comment]
It seams work with latest version (I has only test with no bungee and mysql).
