### ISSUE TITLE
can't put &r in chat formatting and suffix before player name

### ISSUE THREAD

**Issue by chillerkraft** [kangarko/ChatControl#219]
this doesnt work
    # Default chat message format.
    # The prefix has to include the 'pl_' because without it the plugin's prefix name will be given instead.
    Message_Format: '%pl_prefix%player:%pl_suffix %&rmessage'
and this doesnt work
    # Default chat message format.
    # The prefix has to include the 'pl_' because without it the plugin's prefix name will be given instead.
    Message_Format: '%pl_prefix%%pl_suffix %player: message'
but this does
    # Default chat message format.
    # The prefix has to include the 'pl_' because without it the plugin's prefix name will be given instead.
    Message_Format: '%pl_prefix%player:%pl_suffix&r %message'
and so does this
    # Default chat message format.
    # The prefix has to include the 'pl_' because without it the plugin's prefix name will be given instead.
    Message_Format: '%pl_prefix&r%player%pl_suffix&r: %message'

**Comment by kangarko** [comment]
1) The '%message' is a placeholder. If you put anything between the % and the rest, it will break. You may only put color codes after (%message&r) or before it (&r%message)

2) I don't see why you are putting % after the %pl_prefix. The variable only requires one '%' mark.

3) and 4) Yes those are correct and they'll work as expected.

If you want to reset the color before player's name, this will work:

%pl_prefix&r%player:%pl_suffix %message

**Comment by chillerkraft** [comment]
o okay i thought the variables were like %pl_prefix% etc

i stopped using chatcontrol chat formatting because chatcolor plugin wasnt able to successfully change the color of players names.. do you know what i need to do? im using essentialsx aswell. now using essentialsxchat

**Comment by kangarko** [comment]
Hey,

I understand the confusion, that's why the system has been changed in ChatControl pro to a more unified form "{variable_name}" instead of "%variable_name".

If you decide to try ChatControl again in the future you can test replacing %player variable with %nick or %displayname to see if the colors of player names will be changed.

**Comment by chillerkraft** [comment]
thankyou so much! ill try those variables now. i couldnt find them anywhere in the wiki
