### ISSUE TITLE
1.19.2 - compile chat message in console

### ISSUE THREAD

**Issue by DJIronic** [kangarko/ChatControl#2191]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.brcb.eu/futibujutu.less

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10051305/debug.zip)

### Information about the issue/bug

The console is flooded by the message reported. This issue happens only on MC servers, not the plugin on Velocity working as a link.

**Comment by ElBananaa** [comment]
This is a known issue that has already been fixed on most recent versions. We're waiting for the maintainer of VelocityControl to update it so you can also use the latest chatcontrol version with velocitycontrol (which is not possible yet).

See #2187 for updates about this.
