### ISSUE TITLE
Adding /command registration for tab completion

### ISSUE THREAD

**Issue by DJIronic** [kangarko/ChatControl#2192]
### Summary

Hello,

it would be great to add your own TAB completing for custom commands or aliases.

The plugin linked in documentation does not exist anymore and using commands.yml is not a great option as you need to restart all servers and it's an issue to keep this list of commands synced across the network (well, its another config file to keep synced on sym-linked).

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Server owners needs to keep another plugin on the server, or manually manage all the tab commants in a separate config wit no option to simply register all aliases/custom commands.

**Comment by TheIntolerant** [comment]
Keeping this open for the dev to have a look at, however, I updated the wiki for [Tab-completion](https://github.com/kangarko/ChatControl-Red/wiki/Tab-completing-custom-commands) so it didn't include any links to outdated plugins.

**Comment by kangarko** [comment]
Thanks, but that's pretty complex for the time I have left right now, I have to politely deny for the time being.
