### ISSUE TITLE
Configurable chat delay (cooldown) for groups/with permissions

### ISSUE THREAD

**Issue by DJIronic** [kangarko/ChatControl#2193]
### Summary

Please add the option to change the deafault chat delay for groups. Not only if the group bypasses it, but also add levels, so one group cana have the default timer, another one shorter or longer and then some other bypass it.

I know there is a permissions `chatcontrol.bypass.delay`, but I also suggest adding permission like `chatcontrol.delay.<time_in seconds>` (for example `chatcontrol.delay.15`).

This feature can enable servers to let higher ranks chat more often, or have group for users already punished for chat misuse forced to think twice about every message they type.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

The plugin lacks a needed feature that cannot be added without doing stupid things like combining plugins with custom delays and making a minecraft unoptimized mess.

**Comment by ElBananaa** [comment]
This is already a feature. See https://github.com/kangarko/ChatControl-Red/wiki/Groups and the `Groups:` part of the settings.yml file.
