### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by PuranaGamer** [kangarko/ChatControl#2194]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Its unfortunate to renew after paying $30 please make it one time payment

my builtbybit id is https://builtbybit.com/members/pg-bhai.282360/

**Comment by ElBananaa** [comment]
See #1680.
Also email support@mineacademy.org with your BuiltByBit profile link and the paypal transaction id for the plugin.

**Comment by kangarko** [comment]
Upgrade is free :) I have cleared up my mails today, let me know if you have any other questions!
