### ISSUE TITLE
Check for username changes

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2195]
### Summary

Hello, I do not allow my players to change the text of their username, only the color. However, there is a "bug", that happens when a user changes their username. 

Lets say my username is `Steve` and I use `/nick &bSteve` to color my name. Then I change my Minecraft username to `Alex`. The next time I join the server, my name is still `Steve` (well, basically `&bSteve`, but you get the idea).

Thats why I propose to add a new setting that would compare player's Minecraft username with nickname from data.db/database. In case there is any difference (even between capitalization), it would reset the nickname from the player.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Nothing really, but right now when a user changes their username and has a nickname from the previous names, it gets really confusing, because the tab-completion and some chat messages are off-sync (due to some using player's username and some using player's nickname). -> By using my suggestion, that would fix the issue.

**Comment by kangarko** [comment]
Thank you. 

If you change the username at Mojang's than it's intended for the nick to remain same. I don't see a pressing reason to add this feature on already a cluttered codebase, I hope you understand.
