### ISSUE TITLE
1.19.2: Warning when someone uses /say

### ISSUE THREAD

**Issue by Omarlatif** [kangarko/ChatControl#2196]
### "/version ChatControlRed" - plugin version

10.14.8

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://pastebin.com/J19bXVGH

### Information about the issue/bug

When someone types /say; the chat message is Unverified and lets out these warnings in console.

**Comment by kangarko** [comment]
I have fixed the console error but you will need to disable Prevent_Spying, unfortunately for the kick there's no fix. Use alternative /say plugin or our own broadcast feature
