### ISSUE TITLE
1.18.2: DeluxeTags compatibility with PAPI

### ISSUE THREAD

**Issue by ClemenDev34** [kangarko/ChatControl#2197]
### "/version ChatControlRed" - plugin version

10.13.4

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/da449a33496f4757b21e6bb79268b555

### Information about the issue/bug

Hello !
I use DeluxeTags for my tags but when I try to include their in chat.yml that make a bug and tags don't work ?
![image](https://user-images.githubusercontent.com/54217887/204090439-7ab1aa3a-cbb4-48c1-aa8a-4a6323d5a004.png)
![image](https://user-images.githubusercontent.com/54217887/204090455-24cbfaf4-cc3e-49e8-aeaf-b421b52e3973.png)

**Comment by kangarko** [comment]
Something is causing deluxetag to connect to the internet or a slow database, you need to fix your tag this is not an issue on our end.
