### ISSUE TITLE
1.19.2: Death messages not hooking into MythicMobs

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#2199]
### "/version ChatControlRed" - plugin version

10.14.9

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://pastebin.com/jxm6rJmk

### Information about the issue/bug

Using the mythic mobs boss name returns the above error when killed by the boss. Unsure if I am setting this up incorrectly.

How to recreate: 
1. Set the following in Chatcontrol red config (made sure in MythicMobs there is a boss named BuffAxo)

```
#RequireSupport MythicMobs or Boss plugin and send a special death message.
group boss
require boss BuffAxo
message:
- &f[&6RIP&f] &c{player}&c has died by a Boss {boss_name}
```
2. Spawn the boss and let the boss kill the player, error appears.

**Comment by kangarko** [comment]
Should be fixed in the next version: https://i.imgur.com/VqpmDw6.png

Use MythicMobs 5.2.0
