### ISSUE TITLE
1.16.4 | Wrong quit message generated

### ISSUE THREAD

**Issue by Qw4rtz** [kangarko/ChatControl#22]
The plugin has generated this line in messages/quit.rs
`- &8[&2+&8] &7{player} &fhas quit the game`
While it should be
`- &8[&4-&8] &7{player} &fhas quit the game`

**Comment by ElBananaa** [comment]
I also noticed that the {player} placeholder returns your nickname. I tried the plugin on a test server with a friend, and the placeholder shows his name, even tho I'm the one who joined/left the server

**Comment by kangarko** [comment]
I will fix that default message. @ElBananaa please wait until the next version, if the placeholder still returns nick, create new ticket with steps on how to reproduce
