### ISSUE TITLE
Players can still swear using /me

### ISSUE THREAD

**Issue by adopted3** [kangarko/ChatControl#22]
I'm not sure what I've done wrong. All the settings look correct.

**Comment by kangarko** [comment]
Cannot replicate. Both /minecraft:me and /me from Essentials works and swears are either blocked or replaced.

**Comment by adopted3** [comment]
I think it's because in settings.yml I had:
Rules:
  Check_Commands: false

I will test after the next restart.

Thanks. :)

**Comment by kangarko** [comment]
Oh yeah, it will work now ;)
