### ISSUE TITLE
random no repeat on timed messages still repeating even tho true

### ISSUE THREAD

**Issue by chillerkraft** [kangarko/ChatControl#220]
the messages are supposed to stop after sending once, but the messages are sending over and over again
am i wrong about this feature? or is it not working?

`  # Automatic message broadcaster.
  Timed:
    Enabled: true
    Random_Order: true
    
    # If random order is enabled, the messages will be put in a cache and not repeat until the cache is empty,
    # then it will be filled again and so on.
    Random_No_Repeat: true`

**Comment by kangarko** [comment]
The timed messages are supposed to be repeated infinitely, but when Random_No_Repeat is true, they will be saved in a list and from that list we pick one random message each time until the list is empty, and finally fill it again and start over (so you won't see the same message that very often).

**Comment by chillerkraft** [comment]
o okay. thanks! all good
