### ISSUE TITLE
1.19.2: Death messages not formatting item names correctly

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#2200]
### "/version ChatControlRed" - plugin version

10.14.9

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

Hello, please see the image attached (link). My death messages are not formatting hex item names correctly. 

How to reproduce:

1. Set death messages to enabled
2. Have a player kill another player with hex color item name
3. Result https://cdn.discordapp.com/attachments/755325303689052200/1046893785315037244/image.png

Here is the item name
 &#adf3fd&lH&#a3e9fd&la&#99defd&ld&#8fd4fd&le&#85c9fd&ls &#7abffd&lB&#70b4fd&ll&#66aafd&le&#5c9ffd&ls&#6ca5f6&ls&#7baaef&le&#8bb0e7&ld
  &#9ab6e0&lB&#aabbd9&ll&#b9c1d2&la&#c9c6ca&ld&#d8ccc3&le

Some also use console formatting ex. §x§3§f§d§6§f§2§lM§x§4§3§b§c§e§9§ly§x§4§6§a§2§e§0§ls§x§4§a§8§8§d§8§lt§x§4§e§6§e§c§f§li§x§5§1§5§4§c§6§lq§x§5§5§3§a§b§d§lu§x§5§9§2§1§b§5§le

and also do not format correctly

**Comment by kangarko** [comment]
I just tested with plain Bukkit API. It looks like there's a limit on the size of the item's name and Bukkit gives us a cutoff version: https://i.imgur.com/THyFsGV.png
 
Sorry about that, I literally call the official Bukkit method to get the name, I don't think there's any other.

**Comment by TZ122** [comment]
> I just tested with plain Bukkit API. It looks like there's a limit on the size of the item's name and Bukkit gives us a cutoff version: https://i.imgur.com/THyFsGV.png
> 
> Sorry about that, I literally call the official Bukkit method to get the name, I don't think there's any other.

Sorry, hate to reply to a closed issue here. The item names dont seem to cut off when I test this on latest version. They only do not format when the item-name is in console or legacy format. 

Example console format: §x§0§8§4§c§f§bt§x§1§3§5§7§f§be§x§1§e§6§2§f§bs§x§2§9§6§d§f§bt§x§3§4§7§9§f§cl§x§3§f§8§4§f§ce§x§4§a§8§f§f§cg§x§5§5§9§a§f§ca§x§6§0§a§5§f§cc§x§6§b§b§0§f§cy§x§7§6§b§b§f§cf§x§8§1§c§6§f§co§x§8§c§d§2§f§dr§x§9§7§d§d§f§dm§x§a§2§e§8§f§da§x§a§d§f§3§f§dt


Example legacy format
&x&0&8&4&c&f&bt&x&1&3&5&7&f&be&x&1&e&6&2&f&bs&x&2&9&6&d&f&bt&x&3&4&7&9&f&cl&x&3&f&8&4&f&ce&x&4&a&8&f&f&cg&x&5&5&9&a&f&ca&x&6&0&a&5&f&cc&x&6&b&b&0&f&cy&x&7&6&b&b&f&cf&x&8&1&c&6&f&co&x&8&c&d&2&f&dr&x&9&7&d&d&f&dm&x&a&2&e&8&f&da&x&a&d&f&3&f&dt

**Comment by TZ122** [comment]
> I just tested with plain Bukkit API. It looks like there's a limit on the size of the item's name and Bukkit gives us a cutoff version: https://i.imgur.com/THyFsGV.png
> 
> Sorry about that, I literally call the official Bukkit method to get the name, I don't think there's any other.

I can also open up another issue if additional information is needed ^^

**Comment by kangarko** [comment]
That's the size limit, nothing I can do at the moment.
