### ISSUE TITLE
error death msg purpur 1.18.2

### ISSUE THREAD

**Issue by xuandattnvn1995** [kangarko/ChatControl#2202]
### "/version ChatControlRed" - plugin version

10.14.9

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://gist.github.com/xuandattnvn1995/f91bf15b8e4489ef998a8d6b4c4be64b

### "/chc debug" output (strongly recommended)

https://ufile.io/58t86esf

### Information about the issue/bug

After every server reload, this error randomly appears
sometimes there is no error.

**Comment by TheIntolerant** [comment]
Potentially related to #2199

**Comment by kangarko** [comment]
Yep, lets continue at https://github.com/kangarko/ChatControl-Red/issues/2199
