### ISSUE TITLE
1.19.2: Action bar spam when click on remove msg of player

### ISSUE THREAD

**Issue by SpyraMMO** [kangarko/ChatControl#2203]
### "/version ChatControlRed" - plugin version

10.14.9

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

https://imgur.com/ZiSUbxR

**Comment by ElBananaa** [comment]
Please provide us your `/chc debug` file.

**Comment by kangarko** [comment]
Lets continue when user provides debug log
