### ISSUE TITLE
Help setting up a permission toggle for swear rules

### ISSUE THREAD

**Issue by Tazler89** [kangarko/ChatControl#2206]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hello, i am trying to have an age rule but can't seem to find a way to do it, could you please show me how i can do this

So i would like to have anyone over the age of 16 have a perm, using the ignore if they have this perm the words are not blocked, but for everyone else without this perm all bad words are blocked.

the problem i have is it blocks the bad words for anyone without this perm when sending, but it seems to show the players with the perm the replacement i.e **** and when someone with the perm sends a bad word it don't block it for the people that don't have the perm they still see the bad word

what i would like is a way so that
sender without perm, bad word gets blocked
receiver without perm bad word gets blocked 
receiver with perm bad word don't get blocked

sender with perm bad word don't get blocked
receiver without perm bad word gets blocked
receiver with perm bad word don't get blocked

**Comment by ElBananaa** [comment]
@TheIntolerant Can you please have a look at this? I believe you already answered multiples times to users requesting assistance to setup something similar ^^

**Comment by Tazler89** [comment]
i did check old posts but could not find anything that gave me the answer to this. it seems to look at the sender for the ignore event when it should be looking at the person reading it if its something they are allowed to see, so when its ignoring its ignoring the viewer not the Typer

**Comment by TheIntolerant** [comment]
Unfortunately as the plugin is currently, I don't believe this would be possible. At least I cannot think of any ways of doing this, at this point in time.

**Comment by Tazler89** [comment]
so its filter for everyone or for no one as any message from someone ignored can still be seen unfiltered by everyone else.

**Comment by kangarko** [comment]
We don't support that right now.

You need to simply give people above 16 the permission to swear using "chatcontrol.bypass.swear" or whatever you configured (by default in groups.rs) but then if they will swear everyone is going to see it.

**Comment by ElBananaa** [comment]
@kangarko Actually, isn't it possible to use the `{original_message}` variable in a format file instead of the `{message}` one for players with a specific permission? (I think this variable can already be found in the groups.rs rule file) This way, players that are 16+ with this perm will be able to see the uncensored message while others will see the censored message.

I don't have the time to test this, which is why i'm asking ^^

**Comment by Tazler89** [comment]
if i knew where to change this i would give this a try, i did try doing this with require perm then replace full message with the original but it errored out and did not like it, but this was in the groups file, it would not accept the {original_message} part being in the replace part

**Comment by kangarko** [comment]
I can't remember right now exactly, when you have time try testing it and let me know, thanks :)

**Comment by Tazler89** [comment]
> I can't remember right now exactly, when you have time try testing it and let me know, thanks :)

i tested this and no it don't work, the format file don't seem to be able to understand the code
```
  Message:
    Receiver_Permission: chat.swear.off
    Message: ': &e{original_message}'
    Hover: '&7Posted: &f{timestamp}'
  Message2:
    Receiver_Permission: chat.swear.on
    Message: ': &e{message}'
    Hover: '&7Posted: &f{timestamp}'
    
```
it works but shows {original_message} in the chat

![image](https://user-images.githubusercontent.com/51469267/206669037-f52bd4e5-1623-46de-9ddd-c3e779ade338.png)
i have both perms so it shows both message parts

**Comment by Tazler89** [comment]
been messing around doing some more tests got very close, found a way to get the rule to send message to formats by using notify, making the above code work, problem being if there is no bad word the {original_message} don't activate and it just posts the holder

**Comment by Tazler89** [comment]
Found a way to do it was a lot of work but it seems to work, had to do cross over formats and stuff and make lots groups as in a rule you can't assign the match to more then 1 group

Rules, 1 match per group, 1 group per channel
# Blocks 'bugger'
match \b(b+(\W|\d|_)*u+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)
group help
match \b(b+(\W|\d|_)*u+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)
group mcb
match \b(b+(\W|\d|_)*u+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)
group world
match \b(b+(\W|\d|_)*u+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)
group closeby

each group for each channel and then 1 format to go along side each format for the channels
by using notify it makes the original holder activate, without it being done this way and making formats to go alongside the original holder don't activate so you must have normal format files for when the rule is not active
group help
require channel Help write
then notify chat.swear.on MCBHelpS
then replace BadWordNo
then deny

group mcb
require channel MCB write
then notify chat.swear.on MCBChatS
then replace BadWordNo
then deny

group world
require channel World write
then notify chat.swear.on MCBChatWS
then replace BadWordNo
then deny

group closeby
require channel CloseBy write
then notify chat.swear.on MCBChatLS
then replace BadWordNo
then deny

and finally, the format to define if the word is blanked out or not blanked out depending on if the receiver has the perm
Parts:
  Worlds:
    Message: '&f[&r{server_name}&f]'
    Hover: This is the Server the sender is currently in.
  Channel:
    Message: '&f[&e{channel}&f]'
    Hover:
    - 'This is the Channel the player is talking in.'
    - 'Click to Join Channel'
    Run_Command: /ch join {channel} write
  Prefix:
    Message: '&f[&r{player_prefix}&f]'
    Hover: Server Rank of the player.
  Name:
    Message: '{player_name}'
    Hover:
    - '{player_first_join_date}'
    - '&7Click to message.'
    Suggest_Command: '/tell {player_name} '
  Message:
    Receiver_Permission: chat.swear.off
    Message: ': &e{original_message}'
    Hover: '&7Posted: &f{timestamp}'
  Message2:
    Receiver_Permission: chat.swear.On
    Message: ': &e{message}'
    Hover: '&7Posted: &f{timestamp}'

**Comment by Tazler89** [comment]
i have attempted to use java script and condition but nothing can tell when  {original_message} has text in it or not, all i need is a way for it to know when a rule has been activated or not, when not showing normal message when true it can show  {original_message}, this is the only thing hold me back now, it just needs to know when a rule is activated

**Comment by Tazler89** [comment]
managed to get my another plugin dev to help me and after 3+ days of trying to make this happen he done it in 20 mins, woot woot, alot of messing and fiddle bits fine tuning but its there, you guys don't make it easy :D, inherit don't seem to like to be used more than once, so can't do perm inherit diff perm inherit, so had to make a big massive list, also only being able to do 1 perm per section was abit grrr, hope all this stuff gets improved over time to make the formats more flexible

**Comment by TheIntolerant** [comment]
> managed to get my another plugin dev to help me and after 3+ days of trying to make this happen he done it in 20 mins, woot woot, alot of messing and fiddle bits fine tuning but its there, you guys don't make it easy :D, inherit don't seem to like to be used more than once, so can't do perm inherit diff perm inherit, so had to make a big massive list, also only being able to do 1 perm per section was abit grrr, hope all this stuff gets improved over time to make the formats more flexible 

Glad to hear, do you mind sharing how you achieved this?

**Comment by Tazler89** [comment]
in group using the Notify system, this outputs a unfiltered message "then notify Perm Format" then you mirror the format you use for normal channels, but using 

Message:
    Message: ': &e{original_message}'
    Hover: '&7Posted: &f{timestamp}'
    
you need a perm for filter and a perm for none filter, then you need to change some stuff in your normal format file so to hide it from the none filter perm otherwise they would get double. But you also need to make it show when nothing is being filtered that is the hard part.

Message:
    Receiver_Permission: none filter perm
    Receiver_Condition: '!"{message}" .contains("what ever you use for the filter replacment")'
    Message: ': &e{message}'
    Hover: '&7Posted: &f{timestamp}'

this checks the player has the no filter perm and checks if they normal message has a filtered word in it.
you must do this for EVERY panel you have if you don't the player not being filtered will get double panels displaying

Message2:
    Receiver_Permission: filter perm
    Message: ': &e{message}'
    Hover: '&7Posted: &f{timestamp}'

then you need to add another for the player who can see the filtered message

to make this work you need to have all of your formats for every channel in 1 format file, this cannot work over multiple channel formats unless your going to make a rule for each channel

this thing was hell to do and a lot of tweaking using channel conditions to get it to work on every channel and still display each part in its own format to each channel lol

hope this helps others not have to spend as much time on this as i did
