### ISSUE TITLE
Optimise PlayerListener.onJoin()

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#2207]
### Summary

I got issue with my mspt, the 95%ile and the max tick is heavy, so I did a spark with only tick over 70ms
![image](https://user-images.githubusercontent.com/31826333/205501837-ef9b35f5-1163-4f8c-9c21-e5126cad69c3.png)
![image](https://user-images.githubusercontent.com/31826333/205501846-b72699ab-a635-4431-ac78-68d668901337.png)

Spark : https://spark.lucko.me/StKcrDQ5aH
### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Why is some informations stored into yaml and not a real dabatase, it could optimise the plugin even more for this event

Config : 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10148971/debug.zip)

**Comment by WarnDa** [comment]
Edit : I was not using mysql, using mysql it seems better :)

**Comment by kangarko** [comment]
Large databases work best with MySQL, just use that instead :)
