### ISSUE TITLE
Bedrock Compatibility, Mail

### ISSUE THREAD

**Issue by Tazler89** [kangarko/ChatControl#2208]
### Summary

Hi i am slowly trying to config the plugin, i and making a fully bedrock friendly server, but your mailing system using the books can't be used by bedrock users.

the inbox is chat click bedrock users can't do this, and when a bedrock user opens the book and types something it will not sign and save the book to be sent, so bedrock users at this time cannot send or receive mail, could you please do something with this or make it have other options, GUI menu or all text command based mailing as with this i would then be able to make a GUI using the commands

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

No bedrock users could ue any of the mailing system and i will now have to disable it and find another system what is a massive shame as i not like the plugin and hope it could be fully supporting for its users

**Comment by kangarko** [comment]
Sorry that seems like a hard incompatibility at the moment. We could do a chat-only alternative for bedrock but I dont have time for this right now.

**Comment by Tazler89** [comment]
do you have any sort of time frame on this, a text or GUI one would be great as it would over come this problem, its really holding me back so need to find a new plugin that works or know this is something that can be resolved

**Comment by kangarko** [comment]
I remember Essentials plugin has text Mail feature. I am sorry as of right now my time is limited and I have to set a boundary not to implement any major features taking days to do as a result.
