### ISSUE TITLE
1.19.2: link a Minecraft channel with two different discord server's channel

### ISSUE THREAD

**Issue by MusicTW** [kangarko/ChatControl#2209]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

![image](https://user-images.githubusercontent.com/52475422/206233774-e483749c-a22b-4637-a193-0b3f0097e626.png)
I want to let my server can link two different discord server channel, how can I do
I just try to do like:
Discord_Channel_Id: 815096744580612156,1891325181868186183
But, it can't work
I already invite the bot to the other discord server

**Comment by kangarko** [comment]
One ChatControl channel can only be linked to one Discord channel, this is by design. You need a third party plugin for that, sorry.

**Comment by MusicTW** [comment]
or add a new feature, maybe?

**Comment by kangarko** [comment]
I don't see a big need for this, in years you are the only one asking for this -- I do recommend looking into DiscordSRV plugin whether it can accomplish your need or appointing a small developer to listen to our ChatChannelEvent and redistributing it from there

**Comment by MusicTW** [comment]
So, if I wanna use chat rules with this plugin, I must try to develop a small addon about these two plugins?
And we have a discord bot that can connect two server chat channel together now, why not Minecraft link with discord can have same feature, too
![Screenshot_20221209-102903_Discord](https://user-images.githubusercontent.com/52475422/206610548-20202fd9-01d1-4c03-b009-26ec6e4f1674.jpg)
![Screenshot_20221209-102912_Discord](https://user-images.githubusercontent.com/52475422/206610557-b0ba46a9-8df8-41cd-b190-f26aa3c04367.jpg)

**Comment by kangarko** [comment]
For chat rules you can send a Discord message to any channel and even multiple channels, see https://github.com/kangarko/ChatControl-Red/wiki/Discord#6-optional-send-discord-messages-from-rules

So theoretically you could use that "then discord" operator in rules/chat.rs to forward your messages to multiple Discord channels. You can use the rule multiple times over multiple lines :)

**Comment by MusicTW** [comment]
match (.*)
require channel Discord
require script {sender_is_player}
then discord 1050081226008035360 {player} » {message}

match (.*)
require channel Discord
require script {sender_is_player}
then discord 815096744580612146 {player} » {message}

ok, I wrote something like above,
and now it works that Minecraft's chat going into discord server channels
and another question is coming
that is how these two discord channels throwback messages back
just create the others two channel for those messages and throw the messages back to the current channel?

**Comment by MusicTW** [comment]
match (.*)
require channel Discord
require script {sender_is_player}
then discord 1050081226008035360 {player} » {message}

match (.*)
require channel Discord
require script {sender_is_player}
then discord 815096744580612146 {player} » {message}

ok, I wrote something like above,
and now it works that Minecraft's chat going into discord server channels
and another question is coming
that is how these two discord channels throwback messages back

**Comment by MusicTW** [comment]
I just tried the way that I thought above my review.
It pretty cool.
that works.
I mean, almost works perfectly.
only one fault here, that is the discord channels can't fit together
