### ISSUE TITLE
[Issue] Toggle permissions don't seem to work

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#221]
Gave the player access to the following permissions:

![image](https://user-images.githubusercontent.com/5664135/101089170-199cef00-35b5-11eb-9a2c-6b4a885c0754.png)

In-game it results in when I try to toggle either:

![image](https://user-images.githubusercontent.com/5664135/101089191-20c3fd00-35b5-11eb-9a19-209221dcaf92.png)

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Alright, I just tried on my test server, and I have the same issue. Using `chatcontrol.command.toggle.{type}` works tho (Yeah, use the permission I wrote, don't replace the type).

**Comment by Sikatsu** [comment]
But if you do that, you will allow to toggle every setting I think?

**Comment by kangarko** [comment]
Thank you, I will fix that!

**Comment by Sikatsu** [comment]
Awesome!
