### ISSUE TITLE
Add dynamic image of player head in MOTD

### ISSUE THREAD

**Issue by NightshadePixelmon** [kangarko/ChatControl#2210]
### Summary

I honestly thought this feature already existed when I purchased the plugin (yea, I know.. I should have tried free before purchase so this is completely my fault I suppose) but other chat plugins offer the ability to have the player head to the left of the MOTD similar to how this is displayed in fancy messages (why I thought this plugin could do it) https://camo.githubusercontent.com/e7ac06532e66d5960de8e9d48f4158ec5157ced7fd6f18a08bb7a55f99e8ea65/68747470733a2f2f692e696d6775722e636f6d2f505176536d4e6a2e706e67

In your marketing, ChatControl Red also marrys up the MOTD with the image command adding a bit to why I figured this plugin could in fact already accomplish this. 
![image](https://user-images.githubusercontent.com/34421890/206243901-c7a08032-6c5f-41e5-b1b9-88f1cff8954f.png)

The request would be for this plugin to also be able to dynamically place the player head to the left of the motd. Here is an example of this being used in not only another chat plugin but an essentials plugin with a chat module on the side: https://www.zrips.net/cmi/custom-text/

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

This allows for a more personalized experience for the player. It is a feature that more cheaper and less specialized plugins already have.

**Comment by kangarko** [comment]
Sorry for the confusion, I have added this feature! You can use images placed in the images/ folder, user avatars or download any image from the net by tweaking your format file like this in the next version:

![b](https://i.imgur.com/i0FHo6J.png)

![a](https://i.imgur.com/SuHB3JS.png)

**Comment by NightshadePixelmon** [comment]
That looks sexy. Thank you!
