### ISSUE TITLE
Add placeholders for the players states of /toggle settings

### ISSUE THREAD

**Issue by NoobcoreNetwork** [kangarko/ChatControl#2212]
### Summary

Hey! So I'm looking to make a form of, Toggle GUI on my server for players to be able to toggle off different parts of chatcontrol features, Aka, /toggle pm, /toggle soundnotifications etc, Of course, I can make the GUI make the player run those commands when they click it, but I'd like to be a little more advanced, 

![chrome_PRivO218K5](https://user-images.githubusercontent.com/62724418/206810027-c5a95b28-f120-4115-98fe-dcd980fa2b3f.png)

I'd like my menu to have a toggle switch image but in order for the GUI to know if it should show the 'on' or 'off' position, there needs to be placeholders that i can use in a condition based on the current condition of the players toggle setting

Aka {toggled_<part>}

So like, {toggled_pm} and {toggled_soundnotify}
So i can check this and let the GUI understand which image/state of the toggle is currently selected!

Also, I run a clean server and users can only run commands that I let them, If I'm making a custom menu for this, I don't want to allow them to type /toggle in the chat, So I will block the command using a command whitelist plugin, So I'm also suggesting that we can be allowed to run /toggle pm %USERNAME% from the console, So I don't have to allow the user to have access to the command directly, and the GUI can handle it all, I tried this as a test but the command has to be run as a player, due to the this.checkConsole() statement in the toggle code

Of course, this is all just a suggestion, But I think these features might come in handy for people anyway in general, It would also allow admins to be able to toggle other players' states if they might need too! 

Thanks! Let me know if this didn't make any sense, I'm not too great at explaining things lol.

 

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Nothing, Just a nice feature to have!

**Comment by kangarko** [comment]
Thanks, honestly that seems like a great idea and all but right now my time is pretty scarce and as I said other places, I am looking to rather remove things from ChatControl to keep it lean and minimalstic as possible. That would fit as a great installable addon what you are suggesting :) If you have a dev or anyone who codes I can grant him a dev license so he can use our APIs.
