### ISSUE TITLE
Minecraft 1.16.5 :  Sound notification doesn`t work

### ISSUE THREAD

**Issue by maxxxmine** [kangarko/ChatControl#2213]
### "/version ChatControlRed" - plugin version

10.15.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

No error logs occur

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10212867/debug.zip)

### Information about the issue/bug

The issue appears when trying to use @[player] feature, as noone recieves notifications nor does the player nick change. tried it in every type of chat - global, ranged, standart. Removed every other plugin that might interfere (towny, rpg chat, Vulcan). Tried both as OP, player, owner(luckperms, basicaly). Checked settings.yml multiple times and went as far as to delete it and let the plugin regenerate it. Nothing seems to work. Even made an experiment, where i used partial phrase for "true" - "tr" and plugin just inored it, no errors whatsoever, still not working. And more than that, some features, which had Enabled: false, still seemed to work just fine? (For example, /me). 
![Screenshot_2](https://user-images.githubusercontent.com/119621688/207184347-f73db7ed-d22d-4474-97da-c8a135763a58.png)
![Screenshot_3](https://user-images.githubusercontent.com/119621688/207184359-9e83b847-ccbe-4cfd-9155-5c5e6f23b0fd.png)
![Screenshot_4](https://user-images.githubusercontent.com/119621688/207184366-8a71e21a-c209-4a15-b9b2-105d1dc74721.png)

After some more experiments, it seems like the plugin is ignoring the settings.yml whatsover. UTF-8 Encoding, warning message occurs
![Screenshot_5](https://user-images.githubusercontent.com/119621688/207187113-4508c51b-ecec-4be5-81d8-d87e2b1982a5.png)

**Comment by maxxxmine** [comment]
Update: Tried completely clean install, no other plugins except Vault, PAPI and Essentials. Still nothing seems to work for me :(

**Comment by ElBananaa** [comment]
Alright, after running a quick testing session, I'm able to reproduce all the issues reported above.
I don't know what's the cause of all these issues, but something's definitely wrong here as most features appear to be partially broken.

@kangarko This definitely needs to be handled quickly as we're facing issues such as not being able to enable/disable features without a server restart, features being disabled that somehow are still working (such as the `/me` command, however, when it's disabled, it appears to be fully broken, the color isn't applied, kinda like the command is working with the default minecraft chat system and not chatcontrol's channel system) etc...

**Comment by kangarko** [comment]
Strange, on it tomorrow.

**Comment by kangarko** [comment]
Okay couple of notes: the /me command still works even if you disable it at us because Minecraft provides one on its own still. 

I could reproduce sound notify being broken, going to try to fix tonigh.

**Comment by kangarko** [comment]
<img width="524" alt="Screenshot 2022-12-18 at 12 54 07" src="https://user-images.githubusercontent.com/1918426/208297005-0369d970-86b3-4ab4-a5da-ffb9f65c350f.png">
Hey! The latest version should have the problem solved :)
Anyways when you're editing settings.yml try doing it when the server is stopped if you experience issues while it is running.
