### ISSUE TITLE
Better clarification in regards to Velocity support

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2214]
### Summary

Currently, users who download ChatControl-Red wishing to use it under a Velocity Server may be unaware of the level of support that VelocityControl receives compared to "BungeeControl". It is likely many users are under the impression that Matej is actively maintaining this plugin

---

It should clearly state that ``VelocityControl is maintained by a third-party developer`` where there is mention of VelocityControl.

---

### Places that need better clarification, include:
- https://builtbybit.com/resources/18217/ 
![image](https://user-images.githubusercontent.com/48093184/207647688-797d66ea-280d-4500-a484-39a6d4ae115e.png)
- https://github.com/kangarko/VelocityControl/blob/main/README.md
- https://github.com/kangarko/ChatControl-Red/wiki/Compatibility#velocity

---

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

If this is not implemented, many users may be misled into thinking that Matej is actively maintaining this plugin, VelocityControl. When it is actually being maintained by a third-party developer

**Comment by kangarko** [comment]
Thank you, I added it! Let me know if you have any comments on that :)

**Comment by TheIntolerant** [comment]
Perfect!
