### ISSUE TITLE
1.19.2: Error appears in the console, related to "death" from "Messages.Apply_On"

### ISSUE THREAD

**Issue by TheMrLhuixx** [kangarko/ChatControl#2215]
### "/version ChatControlRed" - plugin version

10.15.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://gist.github.com/TheMrLhuixx/71ca3275f5d7cee7ec73440cc4776a9e

### Information about the issue/bug

The error shows up on console when I kill a player or he's die from a mob, but when I remove "death" from "Messages.Apply_On" or when I kill the player with /kill, the error doesn't show up.

Edit: I also want to add, that I delete the ChatcontrolRed folder, so that it starts with clean files from 0, and when I set "death" to "Messages.Apply_On", the error still appears when I kill a player.

**Comment by kangarko** [comment]
Testing asap. Looks like MythicMobs integration is failing

**Comment by kangarko** [comment]
Should be fixed in yesterday's release for this MythicMobs version:

https://www.mythiccraft.io/downloads/mythicmobs/free/MythicMobs-5.2.0.jar
