### ISSUE TITLE
1.19.2: Custom Variable Spacing

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2216]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I use some custom variables to display things based on PAPI placeholders. The variable is basically if player has X permission, display X. The variables work, but my question is how can I make them use the + trailing space fixer or is there a way to automatically adjust for if there is an empty line?

Chat format:
  player-name:
    Message: '&r#C6C1FB{player_nick}&r'
    #Message: "{player_name}"
    #Gradient: RED - YELLOW
    Hover:
    - ''
    - '{topvoter}'
    - '{nitro}'
    - '{toppt}'
    - '{topmcmmo}'
    - '{topdamage}'
    - '{topmobs}'
    - '{topmined}'
    - ''

Currently, if a player has all of these variables then it displays fine. But if any of them are missing, then the line stays and just appears blank which looks pretty terrible. Is there any workaround/solution to this that I am missing?

**Comment by kangarko** [comment]
I guess that's by design, I will look into alternatives but at the moment there is none. 

One thing you could do is wrap the variable using our javascript, see examples in the variables/ folder. So if the player has none, you show "None" instead of blank space
