### ISSUE TITLE
1.19.2: Chat channels can be read when user not authenticated

### ISSUE THREAD

**Issue by DarrylSSY** [kangarko/ChatControl#2218]
### "/version ChatControlRed" - plugin version

10.15.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10241635/debug.zip)

### Information about the issue/bug

I have enabled hideChat: true in Authme Reloaded config, however, it seems that even after that, unauthenticated users can still see the chat. This is an issue because users are able to see the staff channel when they use a staff account that has autojoin read on staff channel. Are there any way to solve this?

**Comment by kangarko** [comment]
Hey! Looks like incompatibility with AuthMe.

My time is really scarce to deal with third parties, but we have a simple ChatChannelEvent so you can try asking their authors nicely to listen to it and cancel it when the user is not logged in. If they need assistance just email matej@mineacademy.org and I will also grant them developer free license.
