### ISSUE TITLE
1.19.3: Console Error

### ISSUE THREAD

**Issue by NyhmsQuest** [kangarko/ChatControl#2219]
### "/version ChatControlRed" - plugin version

10.15.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://mclo.gs/DEpDrUe

### Information about the issue/bug

Updated my server to 1.19.3 and the console spews out error everytime someone connects

**Comment by ElBananaa** [comment]
The plugin doesn't support 1.19.3 yet and there's no eta for its support.
Keep an eye on this page to see when 1.19.3 is officially supported: https://builtbybit.com/resources/chatcontrol-red-format-filter-chat.18217/reviews

**Comment by kangarko** [comment]
Updating right now, estimated time it takes about 24 hours :)

**Comment by NyhmsQuest** [comment]
I still get this in console after the update

**Comment by NyhmsQuest** [comment]
https://mclo.gs/qJYEp3g

**Comment by ElBananaa** [comment]
@NyhmsQuest Can you please make sure you are using the latest ProtocolLib devbuild available? You can get it here: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by NyhmsQuest** [comment]
I am using the latest version of ProtocolLib

**Comment by kangarko** [comment]
Thanks, that was related to our Prevent_Spying feature. Due to so many problems with it I will have to just remove it from the next version. Disable it.
