### ISSUE TITLE
chatcontrol reload caused problems

### ISSUE THREAD

**Issue by chillerkraft** [kangarko/ChatControl#222]
https://pastebin.com/361pZ895
all i changed was taking out the two chat rules for smiles :) and :-)

**Comment by chillerkraft** [comment]
it broke the plugin
i need to rebuild the config after reinstalling, i guess. idk what else to do

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding

**Comment by chillerkraft** [comment]
i guess i just had to delete the chat rules file because i edited it using notepad

**Comment by chillerkraft** [comment]
https://i.gyazo.com/bd5eb9cd6fdce727ec328e248ff99179.png
i dont have option for utf8 without BOM..

**Comment by kangarko** [comment]
Just use UTF-8-BOM, it should work.

**Comment by chillerkraft** [comment]
please help.. when i edit the chat.txt in rules, with notepad++, it makes smileys not happen anymore on my server
here's the file https://pastebin.com/AQDL0gEj

**Comment by chillerkraft** [comment]
o okay

**Comment by kangarko** [comment]
Try either UTF-8 (Click convert to UTF-8) or UTF-8-BOM (do it on a stopped server because the file is manipulated on the stop/reload :))

**Comment by chillerkraft** [comment]
that did not work...

**Comment by chillerkraft** [comment]
o just got ur msg now sorry

**Comment by kangarko** [comment]
NP. Did you find a combination that works? :)

**Comment by chillerkraft** [comment]
sorry i took a little break the extended into an hour, ill try stopping the server to edit
thanks again for epic support

**Comment by chillerkraft** [comment]
none of that worked

**Comment by kangarko** [comment]
I got it fully working on the latest Notepad++
![img](https://i.imgur.com/ndW28Hm.png)

I don't know what your system is, it it's odd because I never get this issue reported when saved under UTF-8...x encoding.

**Comment by chillerkraft** [comment]
can you please create and send me a file like the one i pastebinned that i can upload onto my server and use?

**Comment by kangarko** [comment]
Hey, the picture shows default rules/chat.txt file. Just remove the file, restart the server and it will be created again.

**Comment by chillerkraft** [comment]
also, if im using a plugin that adds a prefix to my name in chat, how do i allow that prefix to show in chat? im gonna try using %pl_prefix

**Comment by chillerkraft** [comment]
no no i want one like this https://pastebin.com/AQDL0gEj
i cant make one like that remember, and i dont want it default im so sick of the default :) and :-)

**Comment by kangarko** [comment]
Use {pl_prefix} instead.

**Comment by kangarko** [comment]
I have saved the one for you and it loaded just fine on my server. File: https://expirebox.com/download/57347cadf984cf6c92b1b6ed137d0122.html

**Comment by chillerkraft** [comment]
i stopped my server and put the new chat file on my server.. it doesn't work still :(
along with {pl_prefix} 

![](https://i.gyazo.com/15e03ab5d7055d8c3c1516d8e684eca6.png)

**Comment by kangarko** [comment]
Something does work because I see the [Member] prefix. Where is that coming from? It seems like ChatControl does not manage your chat. Do you have any other plugin that edits chat like EssentialsChat or DeluxeChat? If so, please disable their chat formatting features first.

**Comment by chillerkraft** [comment]
the [Member] prefix, that's my display name. i honestly can't remember what plugin makes that its either essentialsx (not using essentialsxchat) or luckperms (or at least the prefix/suffix i set in the perms, thats being put into the display name)
im pretty sure %pl_prefix will just show [Member].. yea i'll try disabling that and seeing if it replaces it with dragonslayer prefix. thankyou

**Comment by chillerkraft** [comment]
i removed the prefix from luckperms, and i put %pl_plugin in chatformatting, i was supposed to have the prefix but it was just showing my name and chat. no prefixes. i should probably be talking to mr dragonslayer dev about this.. idk...
about the chat file not working on my system, im going to try editing that file from my multicraft panel

**Comment by chillerkraft** [comment]
Status: Saved on 2017-06-20 17:49:02 using mode FTP_ASCII
File: /plugins/ChatControl/rules/chat.txt

that didnt work either
could you please send me a jar, where i can reinstall the plugin completely with it set default the way i want, so through further updates it will keep the same chat rules file there, that works?

**Comment by kangarko** [comment]
It's not %pl_plugin, it's %pl_**prefix**. If you used that and it still does not work, then it's not ChatControl's fault because we only reach out for the prefix from Vault, which reaches out from it from your permission plugin. I don't know if Luckperms are supported by Vault, you can check their page or Vault's page on bukkitdev.

I can't send you another jar because that would be exactly the same as the one on SpigotMC. I don't know why it doesn't work, I would suggest you rename ChatControl folder completely and let a new be regenerated. Then, try once again with the various encodings in Notepad++. I hope it'll work :)

Multicraft may cause issues especially if you wish to use smileys. I would recommend you only use Notepad++ to edit the ChatControl's files.

**Comment by chillerkraft** [comment]
no no i want a jar that's already edited the way i showed u above in the pastebin
because ive already tryed all the encoding stuff and it is not working for me

im pretty sure i put %pl_prefix but i'll try again. yes luckperms supports vault

**Comment by chillerkraft** [comment]
well. i figured out the prefix problem. chatcolor+ was breaking it. i have to have changedisplayname false for essentials, and dragonslayer puts the prefix in displayname.

now i'd just really appreciate it and be 100% good if you could make me a jar with these changes to the chat rules files, https://pastebin.com/AQDL0gEj
i basically just put the big smile for the main smiles, and got rid of all the other smileys except the heart and star.
altho it would be really nice to get this working, i can't now but i will look into solving this issue in the future. for now, if you could make me that jar, golden. thanks.

**Comment by chillerkraft** [comment]
okay so. it turns out the smileys just aren't working for mee.
i think it's because i turned off the rule permission for me or something, imma look into it

**Comment by chillerkraft** [comment]
chatcontrol.bypass.rules
i need this perm to allow me to go /gm 1 and stuff
but it stops me from doing smileys

**Comment by kangarko** [comment]
The _chatcontrol.bypass.rules_ permission will disable rules for the person having it, meaning all the rules.

You can remove the rules for /gm 1 in rules/commands.txt and remove yourself that permission afterwards.

**Comment by chillerkraft** [comment]
k thanks (:
