### ISSUE TITLE
Paper 1.19.2: {sender} {receiver} nicknames

### ISSUE THREAD

**Issue by hatemabsi** [kangarko/ChatControl#2220]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

I am using a nickname plugin and I managed to integrate it everywhere as it uses its own placeholder for nickname which is %haonick_name% and I was wondering if there is a way I can integrate it into the pm-sender and pm-receiver message. So that when someone sends a message to me they see my nickname in chat and when I send them a message they see the message from my nickname.

**Comment by kangarko** [comment]
I am sorry, due to the design we only send limited amount of data to the sender/receive stream in private messages. We should support {nick} but I suppose your HaoNick plugin need to integrate into ChatControl for that first.
