### ISSUE TITLE
1.19.2 Bungee log spam: Cancel event from plugin::chcred

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#2222]
### "/version ChatControlRed" - plugin version

BungeeControl Red 3.13.2

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

Too large

### "/chc debug" output (strongly recommended)

Bungeecord spams
`Cancel event from plugin::chcred`

Spamming 120 lines of crap PER SECOND !

Log file is exploding!

I understand that changing plugin channels can be challenging. But wouldn't it be a good idea to have BC accept both before turning the old channel off? Would have prevented this I assume.

### Information about the issue/bug

-

**Comment by james090500** [comment]
Hi,

Sorry you have this issue!

Please try this fixed build : https://cdn.discordapp.com/attachments/755325303689052200/1054498993771651142/BungeeControl-Red-3.13.3.jar

@kangarko will release it on BuiltByBit soon.

**Comment by x1p** [comment]
Yeah. I tested it and it works. (Yes I'm that guy.)
I'll test tomorrow on the production server. (Solved I guess)

**Comment by kangarko** [comment]
Thanks for James for a prompt fix, I have made a updated built official as well :)
