### ISSUE TITLE
1.18.2: How I can line break in discord format ?

### ISSUE THREAD

**Issue by ClemenDev34** [kangarko/ChatControl#2223]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

No

### Question

Hi, 
I want to line break in my advertissement ad but the `\n` and the `<br>` don't work !

**Comment by TheIntolerant** [comment]
Have you tried using ``then discord`` twice?
Example
```
then discord first line message
then discord second line message
```

**Comment by ClemenDev34** [comment]
Yes but that make only one message

**Comment by james090500** [comment]
If you want to split it into 2 messages, I dont think you can do that.

**Comment by ClemenDev34** [comment]
It's for do something like :
```
**New Report**
-> User
-> Message
-> Time
```

**Comment by kangarko** [comment]
I have fixed this in the next version! Simply use:

```
then discord 781507830896132127 ***
then discord 781507830896132127 This is an announcement
then discord 781507830896132127 ***
```

Replace 781507830896132127 with your channel name.
