### ISSUE TITLE
1.19.3: Messages are not being forwarded by DiscordSRV to Discord.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#2225]
### "/version ChatControlRed" - plugin version

ChatControlRed version 10.16.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10275618/debug.zip)

### Information about the issue/bug

ChatControlRed for 1.19.3 seems to have broken DiscordSRV chat forwarding. If I remove/disable ChatControl and restart my server, chatting publicly _does_ forward the public message from ``In-game -> Discord`` (via DiscordSRV) fine. If I re-enable ChatControl, public messages are not forwarded. 

I do not enable the native integration because ChatControl breaks Emoji handling from incoming ``Discord -> In-game`` messages with the plugin EmojiChat. (Discord Emojis are no longer translated and become [] brackets.)
```
  # Integration with DiscordSRV. 
  Discord:
    
    # Enable all integration with DiscordSRV?
    # This is enabled by default because Discord in reality won't work unless you connect it
    # in Channels.List above or use it in operators, so you have one less option to find & enable. 
    Enabled: false
```

I tried disabling AntiPopup to see if that was conflicting and it made no difference. Enabling ChatControl's integration _does_ forward messages but again, ends up breaking relayed discord messages with it no longer showing Emojis from EmojiChat. ChatControl / DiscordSRV forwarding use to function fine with the setting off & wasn't needed enabled before in 1.19.2 and earlier. 

Could this perhaps be fixed so chat message forwarding for public global chat functions again and is handled entirely by DiscordSRV?

ChatControlRed 10.16.1
DiscordSRV 1.26.1-SNAPSHOT-cd74152
ProtocolLib dev 608 (https://ci.dmulloy2.net/job/ProtocolLib/)
AntiPopup 5.2 (https://github.com/KaspianDev/AntiPopup/tree/5-2)
EmojiChat 2.0.2 (https://github.com/Vap0r1ze/EmojiChat)

**Comment by james090500** [comment]
Have you made sure to put the channel id in settings.yml?

![image](https://user-images.githubusercontent.com/20372645/209846617-41447a59-a582-4b55-9fef-db16cf6e4a84.png)

**Comment by mibby** [comment]
> Have you made sure to put the channel id in settings.yml?

The ID is only necessary if you have the ChatControl-Red discord integration enabled. I do not enable it because it breaks EmojiChat emoji handling and wasn't needed to be enabled if you let DiscordSRV handle forwarding both ways.

As mentioned above, enabling the native discord integration (with channel ID) does work and forwards messages again, but this breaks EmojiChat and wasn't needed before in 1.19.2 builds.

**Comment by kangarko** [comment]
Sorry for the delay, just to confirm you still experience the bug even with Integration.Discord.Enabled on false? That should kill switch all of our handling

**Comment by mibby** [comment]
> just to confirm you still experience the bug even with Integration.Discord.Enabled on false?

Yes, unfortunately. With ChatControl's handling all disabling, when ChatControl is enabled, public messages are not being picked up by DiscordSRV anymore for forwarding. I only utilize one channel people are auto-assigned to for a single public global unified chat. This use to work under 1.19.2. :(

Removing ChatControl, public messages are picked up and forwarded fine by DiscordSRV.

**Comment by kangarko** [comment]
Can you try editing Listener_Priority in our settings.yml and trying LOWEST and HIGHEST priorities? Since we cancel chat event, maybe after editing it we will come after DiscordSRV so it will have a chance to forward it.

**Comment by mibby** [comment]
> LOWEST and HIGHEST priorities

I already had ``Chat_Listener_Priority`` set to ``HIGHEST`` when I opened this ticket so that doesn't seem to work. Testing ``LOWEST`` doesn't seem to forward the message either. Changing it back to ``HIGHEST`` afterwards, still nothing.

**Comment by kangarko** [comment]
I wished that I could fix EmojiChat but at least I fixed the integration, it had to do with us removing [Not Secure] misleading console prefix in a way which canceled the chat event and broke Discord. Fixed in the next build!
