### ISSUE TITLE
More gradient colors

### ISSUE THREAD

**Issue by glorying16** [kangarko/ChatControl#2227]
### Summary

I would love to be able to add more complex color gradients by using more than just two colors. Like red - blue- yellow - purple etc. Adding as many as needed for the look youre going for.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Having more complex gradients means more eye catching/interesting messages. It would help make formats and messages less likely to be missed in a fast paced chat. Having this ability native would make it much easier, and more seamless than breaking apart messages in format files, which is currently the only way.

**Comment by kangarko** [comment]
Thanks, I am keeping eye on these suggestions and will consider this at the next major rewrite (no ETA)
