### ISSUE TITLE
Colors and separators in the bossbar (Alternative Messages)

### ISSUE THREAD

**Issue by zS0bye** [kangarko/ChatControl#2228]
### Summary

Hi, I wanted to ask if it was possible to implement a function for the <bossbar> variable, to set the color and the segments. 

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Because you can't customize the bossbar in any way, you can only edit the message and that's it. Aesthetically it's ugly because it's the default pink one, it would be cool if you could change it.

**Comment by kangarko** [comment]
<img width="783" alt="Screenshot 2022-12-29 at 19 37 30" src="https://user-images.githubusercontent.com/1918426/209995054-1368777e-c30c-4f59-9b90-babf56167762.png">

You can already use that in the parameters of the /chc announce command, but it requires a modern MC version. Example:

/chc announce bossbar color:GREEN style:SEGMENTED_20 time:10 hey there

**Comment by zS0bye** [comment]
That was not what I meant, I know there is this command. But I need to send a broadcast as soon as the server starts, with messages in the bossbar. To do this, I use alternative messages, but I can't customize them.

Example:
![Immagine 2022-12-29 213503](https://user-images.githubusercontent.com/52009682/210008629-0411a3c2-6b68-4eb6-8874-44176accfd5d.png)

**Comment by kangarko** [comment]
Oh I see thank you, looks like right now we don't support any more customization in these messages. When I have more time I can look into this (no ETA)

**Comment by zS0bye** [comment]
> Oh I see thank you, looks like right now we don't support any more customization in these messages. When I have more time I can look into this (no ETA)

Thank you very much, I will wait for this update <3
