### ISSUE TITLE
1.19.3 purpur: Bungeecord server link

### ISSUE THREAD

**Issue by AlphaBlock4k** [kangarko/ChatControl#2229]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hay I have a problem, namely the ChatControll can not write about all servers it worked before, but not anymore I have made MySQL several times Bungeecord is active in all Settings.yml channle is active server.properties server-name is also correct I've tried to reinstall it several times, I also have the latest version 10.16.1 for spigot and bungeecontroll 3.13.3, so I don't know what's going on and I don't have any erros

**Comment by james090500** [comment]
Hi,

In your channels section in settings.yml, under "List" and the channel name, is Bungee: true?

![image](https://user-images.githubusercontent.com/20372645/209139469-29149cc9-26f6-4f5c-b2ff-1fd488ce653f.png)

**Comment by AlphaBlock4k** [comment]
yes I tried it with the setting without this setting

**Comment by james090500** [comment]
Are you seeing messages to any servers? 

Please note: You need to have a player on a server for a message to be sent to it.

**Comment by AlphaBlock4k** [comment]
yes I have players to test, and no see no message on the other servers with /chc forward I can check if the servers are connected but they are not all

**Comment by AlphaBlock4k** [comment]
Here is my BungeeControll settings.yml : https://pastebin.com/7EH7cNAF
an here ChatControll settings.yml :https://www.file-upload.net/download-15063809/settings.yml.html

**Comment by james090500** [comment]
Do you see chat message in console of any servers?

Are players definitely in the same channels?

**Comment by AlphaBlock4k** [comment]
I have 1 bungee 3 under server, in the console I only see the message that was sent from this server and not in the other consoles, all are in the same standard channel

**Comment by AlphaBlock4k** [comment]
https://gyazo.com/b002a93195a29a1d9bc233d86ff79d04
https://gyazo.com/beb71f410fbe88267e3f682fef0ce5c3
https://gyazo.com/8986730c850f6c6a1a03939ea04f32ec

**Comment by AlphaBlock4k** [comment]
[debugCB.zip](https://github.com/kangarko/ChatControl-Red/files/10290992/debugCB.zip)
[debugFARM.zip](https://github.com/kangarko/ChatControl-Red/files/10290993/debugFARM.zip)
[debugOB.zip](https://github.com/kangarko/ChatControl-Red/files/10290994/debugOB.zip)

**Comment by AlphaBlock4k** [comment]
Hello Somebody here ? ?

**Comment by james090500** [comment]
Sorry for delayed reply. What Minecraft Server version are you running? 

Are there any logs in BungeeCord saying the plugin has loaded successfully?>

**Comment by AlphaBlock4k** [comment]
Which Minecraft version I have on it is in the title but I'll say it again purpu 1.19.3 I even changed the version and I'm back to 1.19.2 purpu where it worked before but it doesn't work there either

**Comment by AlphaBlock4k** [comment]
[debugCB.zip](https://github.com/kangarko/ChatControl-Red/files/10296534/debugCB.zip)
[debugFarm.zip](https://github.com/kangarko/ChatControl-Red/files/10296536/debugFarm.zip)
[debugOB.zip](https://github.com/kangarko/ChatControl-Red/files/10296537/debugOB.zip)
This is the current information, I have now set the server to 1.19.2

**Comment by AlphaBlock4k** [comment]
please do not forget my report . I've already tried it on other bungeecord servers and I got the same error that the server doesn't work across the board

**Comment by james090500** [comment]
No one has forgotten we are celebrating Christmas.

Can you send the bungee logs when it's started please.

**Comment by AlphaBlock4k** [comment]
sorry forgot, merry christmas
here are the bungee start logs
[latest.log](https://github.com/kangarko/ChatControl-Red/files/10311641/latest.log)

**Comment by james090500** [comment]
Hi,

CB and Farm seem to both be using ChatControlRed v10.15.1, please update.

**Comment by AlphaBlock4k** [comment]
both already have the 10.16.1 version on it so I updated them

**Comment by james090500** [comment]
The debug logs argue different.

**Comment by AlphaBlock4k** [comment]
[debugCB.zip](https://github.com/kangarko/ChatControl-Red/files/10315968/debugCB.zip)
[debugfarm.zip](https://github.com/kangarko/ChatControl-Red/files/10315976/debugfarm.zip)

this can be good, i tested a lot, several versions, different settings older version new version no matter what i do it doesn't work

**Comment by AlphaBlock4k** [comment]
there are the most recent settings

**Comment by james090500** [comment]
Can you send your bungeecord-red config, can you also enable debug mode for "bungee" in two servers and send a message from both and provider the console log.

Please make sure you have a player on each server.

**Comment by AlphaBlock4k** [comment]
https://gyazo.com/5472b9c1699de1328ba96e75e0dfcd2f

**Comment by AlphaBlock4k** [comment]
[settings.zip](https://github.com/kangarko/ChatControl-Red/files/10316139/settings.zip)
I don't know why but now it works. but / chc forward is not displayed correctly, I don't understand anything anymore

**Comment by james090500** [comment]
After updating plugins the entire network usually needs a reboot. What's happening with CHC forward?

**Comment by AlphaBlock4k** [comment]
with the command /chc forward only the servers are displayed where players are on it?

**Comment by james090500** [comment]
Most likely correct. You can't forward to a server with no players on it.

**Comment by AlphaBlock4k** [comment]
Okay for some reason it's working again now.  I thank you for the help. We wish you happy holidays and a good start into the new year. <3
