### ISSUE TITLE
[Issue] Can't remove rule files

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#223]
I tried to remove some rule files I don't need, but on a server restart they will just generate again.

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

**Comment by OfT3N** [comment]
> I tried to remove some rule files I don't need, but on a server restart they will just generate again.
> 
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true

Just comment everything inside them

**Comment by broken1arrow** [comment]
> I tried to remove some rule files I don't need, but on a server restart they will just generate again.
> 
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true

do not know why you want to delete this (really useful). eg set up a bot for frequently asked questions players have :)

there are quite large reasons why this can not be removed, it is to increase usability. Is not quite easy to get acquainted with this and even more difficult if the  rule files are not generated.

**Comment by Sikatsu** [comment]
Rules were being enforced that I don't need so I thought to remove the ones I do not need, but # works as a workaround ^^

**Comment by kangarko** [comment]
Keep the file but keep it empty. You cannot remove the native files, it is like removing settings.yml
