### ISSUE TITLE
1.19.2: Sending multiple channel join messages

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#2230]
### "/version ChatControlRed" - plugin version

10.16.1

### Are you using MySQL?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10288477/debug.zip)

### Information about the issue/bug

I'm on the Velocity network. After the latest update to VelocityControl 3.11.0 and the latest chatcontrol version, I have multiple channel join messages in chat when I use /ch j <channel>. 

Is this bug already known or is something else needed?

![grafik](https://user-images.githubusercontent.com/62625225/209177940-1ddc2cca-67a7-4ed3-9826-afee6c95d4ec.png)

**Comment by james090500** [comment]
Does it print the exact same number of lines each time you run it?

Also how many servers do you have behind velocity?

**Comment by Lorias-Jak** [comment]
The amount is different on each server.

But on the specific server every time the same amount. So on my build server it's 2 messages, on my main-server it's 7 messages.


In the whole network we have 5 servers, 3 of them have ChatControl and 2 run without ChatControl.

**Comment by james090500** [comment]
Is it dependant on the amount of players in the server? 

Sorry for questions just trying to diagnose and it's hard with only 1 alt!

**Comment by Lorias-Jak** [comment]
Yes, it depends on how many users are on the server. 
It sends it as often as there are many players on the server

12 players on the server = 12 messages for me

And you do not need to apologize for asking

**Comment by james090500** [comment]
Does this do the same if you do /chc leave?

Also, I assume its only the player running the command that get the message?

**Comment by Lorias-Jak** [comment]
yes and yes

**Comment by james090500** [comment]
I have a idea whats causing it, I will try debug this on bungee and velocity to make sure it's on Velocity affected.

**Comment by james090500** [comment]
@kangarko Unfortunately this happens on Bungee and Velocity so I think an issue within CHC Bukkit. Can you see if you can resolve. Seems to only happen with channel changes (which I think is DB_UPDATE?) and prints the success message * player count to only the sender.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/20372645/209236287-00b7a971-e166-49bf-87e8-74be8d6806b5.png">

**Comment by kangarko** [comment]
Sorry for my absence in this regard, I was moving countries plus holiday season took a lot of my time. Investigating right now.

**Comment by sxphirus** [comment]
Just for further context on #2233, I am using the `join.rs` on BungeeControl which is what is duplicating.
```yml
group main_message
message:
- &x&5&c&b&c&1&c{player}
```
![image](https://user-images.githubusercontent.com/7299223/209988993-d4824204-6174-4b96-bc04-8f4cdc22fd97.png)

**Comment by kangarko** [comment]
Jesus I finally fixed that. Sorry it took so long. A new release will come out tonight finally.

**Comment by kangarko** [comment]
@ElBananaa this is important: Remember the bungee changes we did to fix "unknown packed identifier" bug? Apparently they created this issue so I had to revert them, see https://github.com/kangarko/Foundation/commit/5694c8342bd047b9a7256a335417c215ae7deacb

**Comment by james090500** [comment]
That should be fine btw @kangarko I think that wont cause any issues. They main patch in Bungee/Velocity Control should allow you to undo those foundation changes.

**Comment by kangarko** [comment]
Thanks, James do you need to edit VelocityBungee or will it stay the same?

**Comment by james090500** [comment]
@kangarko  VelocityControl should be fine, but to be honest, I dont think your changes with bring back "Unknown packed identifier"

This should still stop it - https://github.com/kangarko/BungeeFoundation/blob/master/src/main/java/org/mineacademy/bfo/bungee/BungeeListener.java#L190

**Comment by kangarko** [comment]
Aha I see thank you!
