### ISSUE TITLE
1.19.2: Minecraft prefix overwrite discord prefix

### ISSUE THREAD

**Issue by Kielczi** [kangarko/ChatControl#2231]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hi!

I would like to add additional prefix like {alonso_tag_chat), but unfortunately this perfix also added on discord. How can i remove this prefix in discord message?
![prefix1](https://user-images.githubusercontent.com/38833122/209324010-6abc02f7-35fe-4053-bb4d-b06245a502a9.png)
![prefix2](https://user-images.githubusercontent.com/38833122/209324127-9e235645-4333-4c5b-89ee-2765807eb34c.png)

**Comment by james090500** [comment]
Hi,

You can use a sender condition eg;

``Sender_Condition: '{sender_is_player}'``

Or

``Sender_Condition: '{sender_is_discord}'``

**Comment by Kielczi** [comment]
Yeah it's working, thanks ^^
