### ISSUE TITLE
Make rules not apply on player names

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2232]
### Summary

There are a lot of issues with the rules regarding player names.

For example, there is a default rule in chat.rs that shortens repeating characters into max 3 in a row, however this rule also works, if someone is called "DDDDDDDDDDDDDDDD" and someone tries to say their name in chat. It says "DDD".

Another example might be global.rs filter. This is a lot trickier, because it works everywhere and I do not know any reason to fix it. If someone's name ends with, let's say "xyzNIG" and then someone tries to type "/msg xyzNIG game", you can already tell what will happen. 

Even worse scenarios are when there is a swear in a player's names that is immediatelly caught by global.rs rule, because the player can do nothing about it. They cannot type their name in chat, cannot message them, and since the name blacklist in settings does not support regex, it is not possible to filter lots of names (or their variations).

**That is why I propose that all online player names will be excluded from any rules.**

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Welp, nothing, but then you get the issues shown above.

**Comment by kangarko** [comment]
> For example, there is a default rule in chat.rs that shortens repeating characters into max 3 in a row, however this rule also works, if someone is called "DDDDDDDDDDDDDDDD" and someone tries to say their name in chat. It says "DDD".

Yeah that's the limit of the system, I can't ignore player names since those are the what it is filtered. 


...

I recommend not inheriting any other rules inside player names rules and using a separate set of rules for that file. If we would exclude player names than players would not be able to type &ckangarko and add colors to their names which you said you were using, isn't it?

**Comment by Teslicek** [comment]
Okay, thanks for the feedback.

Yes, you are right, I use the rule you mentioned.
