### ISSUE TITLE
1.19.2 BungeeControl sending duplicate join messages

### ISSUE THREAD

**Issue by sxphirus** [kangarko/ChatControl#2233]
### "/version ChatControlRed" - plugin version

10.16.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

BungeeControl is occasionally sending duplicate join messages in-game. The amount of duplicate messages also varies, from 1 to 10 or even more! We are running 1.19.2 Paper servers with the latest builds of CHC and BungeeControl, our users are playing on versions. from 1.19->1.19.3 but from what I can tell that doesn't change the amount of messages being sent.

This doesn't happen consistently, I am running Waterfall-510 and BungeeControl 3.13.3.

I'm not sure if this is related to #2230 so am opening this anyway, other users are also experiencing the same oddities in the CHC Discord.

**Comment by james090500** [comment]
Is it dependant on the players in proxy/server? Eg 4 messages if 4 players on

**Comment by sxphirus** [comment]
> Is it dependant on the players in proxy/server? Eg 4 messages if 4 players on

No there is no correlation to how many people are on.

For example when we had 20 players earlier across the network 6 messages sent on one occasion

Now we have about 40 and 1 or 2 are sending, and sometimes 6 or even 8

**Comment by kangarko** [comment]
Let's continue at https://github.com/kangarko/ChatControl-Red/issues/2230
