### ISSUE TITLE
1.19.2 | Not secure icon after all text

### ISSUE THREAD

**Issue by NetworkingPanda** [kangarko/ChatControl#2234]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

After every message, I have a (!) not secure message when hover, how do I disable that

**Comment by james090500** [comment]
You need to set ``enforce-secure-profile`` to false in server.properties of all servers.

You may need to turn off ``force-key-authentication`` in velocity but I'm not sure so test with it on first.

**Comment by kangarko** [comment]
When you are using ChatControl's channel system we do not send this Not Secure icon. I recommend you get AntiPopup or something like that.
