### ISSUE TITLE
1.8.8: Suggestion - tab completion should only show players on first argument for private messages.

### ISSUE THREAD

**Issue by notedo** [kangarko/ChatControl#2235]
### "/version ChatControlRed" - plugin version

10.16.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

![2022-12-26_22 18 13](https://user-images.githubusercontent.com/110790224/209584142-7b079280-578d-441d-9d78-d66932acdb62.png)

### Information about the issue/bug

Hi, when you have private messages enabled and you send a message to a player it double tab the player name, can you fix it? It should only tab the player's name once.

**Comment by kangarko** [comment]
Thanks I have fixed this!
