### ISSUE TITLE
1.8.8 but it doesnt work in all versions: Chat Format VIP bug

### ISSUE THREAD

**Issue by notedo** [kangarko/ChatControl#2236]
### "/version ChatControlRed" - plugin version

10.16.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

You cant make VIP custom chat formatting, the only thing you can do is add a prefix to the VIP group

https://mclo.gs/0ImDD6m

See here, the "vip-message" should replace the default "message", right now when a user has the VIP group permission, it just adds the vip-message options as prefix, making it impossible to add middle parts, like vip placeholder between the nickname and the message or make a default color for vip chat message.

**Comment by notedo** [comment]
I'm using global chat

**Comment by notedo** [comment]
it should only send vip-message, while right now it uses vip-message as a prefix of player-message

**Comment by ElBananaa** [comment]
Please take a look at this page, as it appears you simply didn't understand how the format files work: https://github.com/kangarko/ChatControl-Red/wiki/Formats.

**Comment by broken1arrow** [comment]
I try help him, he has set message placeholder two times. But I not really know what he want for the vip and normal player shall have, so I have to guess little. 

Is more or less solved now, I added JavaScript for negative perms (could not find in the wiki if you could use !).

**Comment by notedo** [comment]
@ElBananaa you're not understanding what I'm asking.
I'll use DeluxeChat config as an example:
https://mclo.gs/cfoDeBJ

Now, with the Priority and Permission options DeluxeChat choose the format to use for the player. It has a global chat system but VIP players (with permissions and priority) have VIP format in the global chat.

With CHC, using only 1 channel (the global chat one) you cant have different chat formats without using weird JavaScript conditions. As shown on the formats guide you can only set prefixes based on permission: 
![formats](https://user-images.githubusercontent.com/110790224/209722886-fcfd0f80-41d2-4205-825c-3bcc382f3f4f.PNG)

So if you want to add an extra placeholder between player's name and the message only for VIP players you cant.

You should add a simple priority system like in DeluxeChat, it avoids us to use complicate JavaScript functions and makes it easy for regular users to set it up, this can help you achieving your goal of making a "frustration-free" system.

**Comment by ElBananaa** [comment]
So, as I said, you clearly didn't understand how the whole format file/system works.
You can configure each part of the format file to work with permission, not only prefixes. As I said, read the wiki page I provided above, because it explains everything.

There's nothing on this page that says "You can only set prefixes based on permissions".

**Comment by broken1arrow** [comment]
> So, as I said, you clearly didn't understand how the whole format file/system works. You can configure each part of the format file to work with permission, not only prefixes. As I said, read the wiki page I provided above, because it explains everything.

The problem was he not wanted some parts get send when you are vip. I could not find in the wiki mention about negative perms (so I help him make some JavaScript booleans instead to make it work as he wanted).

**Comment by notedo** [comment]
exactly, as broken said, The problem is that I didnt want some parts get send when you are vip and also add default chat color to VIP groups. As deluxechat does, it only uses the VIP format, which can be COMPLETELY different from the default one (based on priority and permission)

**Comment by ElBananaa** [comment]
Well yeah, this is still achievable, simply use the `Sender_Permission` part. For the default group, use a permission like group.default under each default part, and for the vip group, use a permission like group.vip under each vip part, that's it. This may not be "as simple" as deluxechat, but still, this can 100% be done with the plugin.

**Comment by notedo** [comment]
how does the plugin choose which part to use in a specific position?
![68747470733a2f2f692e696d6775722e636f6d2f6f393079626a562e706e67](https://user-images.githubusercontent.com/110790224/209724903-f6ab4b58-7a46-40e5-a714-2d71fb019e1c.png)
how is it choosing where to put prefix, playername and message?

**Comment by broken1arrow** [comment]
> Well yeah, this is still achievable, simply use the `Sender_Permission` part. For the default group, use a permission like group.default under each default part, and for the vip group, use a permission like group.vip under each vip part, that's it. This may not be "as simple" as deluxechat, but still, this can 100% be done with the plugin.

Or allowed permission like this "!boolean" as deluxemenu do.

**Comment by broken1arrow** [comment]
> how does the plugin choose which part to use in a specific position? ![68747470733a2f2f692e696d6775722e636f6d2f6f393079626a562e706e67](https://user-images.githubusercontent.com/110790224/209724903-f6ab4b58-7a46-40e5-a714-2d71fb019e1c.png) how is it choosing where to put prefix, playername and message?

Has i say on discord it start reading from the top to bottom (it always do this in any file) and if not the conditions or permission requirements return true, then it Jump to next one.

**Comment by broken1arrow** [comment]
> Well yeah, this is still achievable, simply use the `Sender_Permission` part. For the default group, use a permission like group.default under each default part, and for the vip group, use a permission like group.vip under each vip part, that's it. This may not be "as simple" as deluxechat, but still, this can 100% be done with the plugin.

Also then you has to remove old perm when they get the new one or they get it double.

**Comment by ElBananaa** [comment]
> > Well yeah, this is still achievable, simply use the `Sender_Permission` part. For the default group, use a permission like group.default under each default part, and for the vip group, use a permission like group.vip under each vip part, that's it. This may not be "as simple" as deluxechat, but still, this can 100% be done with the plugin.
> 
> Also then you has to remove old perm when they get the new one or they get it double.

Deny the permission group.default for the vip rank, and you're done. As said above: this may not be as easy as deluxechat, but saying this can't be done would not be true.

**Comment by TheIntolerant** [comment]
Also, the parts are read from top to bottom and if there are special conditions they are applied if the user meets said conditions (from top to bottom).

For example, if I wanted to make two prefixes using chat control this is how I would do it.
```yml
Parts: 

  delete-chat: 
    Message: "&8[&4X&8] &f"
    Hover: "&cRemove this message from chat for all players."
    Run_Command: "/{label} internal remove {message_uuid}"
    Receiver_Permission: chatcontrol.removemessages

  discord-prefix: 
    Message: "&8[&9Discord&8] &f"
    Sender_Condition: "{sender_is_discord}"

  staff_rank: 
    Message: "&8[&4Staff&8] "
    Sender_Permission: chatcontrol.group.staff
 
  vip_rank: 
    Message: "&8[&6VIP&8] "
    Sender_Permission: chatcontrol.group.vip

  player-name: 
    Message: "{nick}"

  message_part: 
    Message: "&7: {player_suffix}{chat_color}{chat_decoration}{message}"
```

**Comment by TheIntolerant** [comment]
Here is a simple example of you could have your ranks up. In this example, rank prefixes were made via LuckPerms https://pastebin.com/n4FP7KR8

**Comment by notedo** [comment]
the best solution was the one that @ElBananaa proposed. With permission and negative permissions this can easily be achieved, thank you a lot guys!

**Comment by kangarko** [comment]
Thanks guys for walking in and helping out! :)
