### ISSUE TITLE
1.8.8 but it doesnt work in all versions: PM AUTOMODE BUG

### ISSUE THREAD

**Issue by notedo** [kangarko/ChatControl#2237]
### "/version ChatControlRed" - plugin version

10.16.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

```yml
   # If you type /tell <player> we toggle automode for you, so chat messages will go to their inbox.
   # You won't need to type /r or /tell <player> to send a message to this player.
   Auto_Mode: false
```

if I disable this option I cant use private messages
I just want to disable conversation when you do "/tell player"
but I still want "/tell player text"

![2022-12-27_00 17 22](https://user-images.githubusercontent.com/110790224/209588017-a35d3b37-1a26-48c5-a9a9-1d2b1649a6dd.png)

See the image, after I set Auto_Mode: false I cant even do "/tell player text" while it should let me do that but it should disable "/tell player" (that starts the conversation with "auto-reply")

**Comment by james090500** [comment]
Can you run /msg (player) test?

**Comment by zPopCorn10** [comment]
That’s the command I run, I got that error

**Comment by james090500** [comment]
In the issue description you say you're using /tell and in the picture it's /w

**Comment by zPopCorn10** [comment]
Yeah sorry it’s /tell

**Comment by kangarko** [comment]
Please provide us your /chc debug as instructed

**Comment by zPopCorn10** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10329478/debug.zip)

Tested on 1.18.2 (also in 1.8.8)

**Comment by notedo** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10329502/debug.zip)

Tested on 1.18.2 (also in 1.8.8 but this is the debug from 1.18.2)

**Comment by kangarko** [comment]
Thanks I have found and fixed the bug! New release will come out in 1-2 days
