### ISSUE TITLE
1.19.3 | Anti Popup

### ISSUE THREAD

**Issue by zS0bye** [kangarko/ChatControl#2239]
### Summary

Hi, I wonder if it would be possible to integrate an Anti Popup system to remove, for example, the notification that is in the image below.

![photo_2022-12-28_19-20-38](https://user-images.githubusercontent.com/52009682/209855722-2cd534ea-e6b4-47cc-9cce-394a2925fb27.jpg)

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Because it would be useless to have additional plugins just to remove this notification. Already basic ChatControl removes the chat warning, but unfortunately this popup remains on the join, so if it were removed it would be a very good addition.

**Comment by kangarko** [comment]
We already did try and it's beyond my scope of time I have and skills, we ended up removing this support and I recommend you get AntiPopup or another plugin for just that

**Comment by zS0bye** [comment]
Yes, but AntiPopup currently doesn't even support 1.19.3, and what's more, it would be an additional plugin that, in my opinion, could also be avoided.

**Comment by kangarko** [comment]
I understand the argument to avoid additional plugins, but I am not confident having features which I can't provide a guarantee on stability for. I still recommend using a third party plugin, sorry to hear it was not yet updated. Perhaps try another.

**Comment by zS0bye** [comment]
> I understand the argument to avoid additional plugins, but I am not confident having features which I can't provide a guarantee on stability for. I still recommend using a third party plugin, sorry to hear it was not yet updated. Perhaps try another.

Yes apparently the dev version was on their discord.  Anyway I understand and thanks anyway for the support ;)
