### ISSUE TITLE
Timed Messages new line

### ISSUE THREAD

**Issue by NoChanceSD** [kangarko/ChatControl#224]
In timed messages \n doesn't seem to work, also %health is not working, don't know about the other placeholders.
I don't really mind the %health issue but \n is pretty important.

**Comment by kangarko** [comment]
Hey, try setting **Enforce_New_Line** to true in settings.yml.

If that does not help, use the following format:

```
Messages:
  - |-
     This message will be shown
     on &ctwo lines.
  - Normal one line message.
```
