### ISSUE TITLE
[Issue] Toggle chat doesn't seem to function

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#224]
I toggled the chat but I can still see messages in the global chat.

![image](https://user-images.githubusercontent.com/5664135/101092187-8adea100-35b9-11eb-93d4-f4c90fa455be.png)

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

**Comment by broken1arrow** [comment]
> I toggled the chat but I can still see messages in the global chat.
> 
> ![image](https://user-images.githubusercontent.com/5664135/101092187-8adea100-35b9-11eb-93d4-f4c90fa455be.png)
> 
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true


 MySQL: false
 BungeeCord: false

I has no option to turn of chat in /toggle, will check if it a error on my side. I think i solve the problem I will test :)


I work fine for me, I get only spy msg when ignore the chat and if I turn off spy it work fine no msg.

**Comment by Sikatsu** [comment]
That's odd, not sure why that doesn't work for me then. Maybe because I have wildcard in my permissions or operator?

**Comment by broken1arrow** [comment]
> That's odd, not sure why that doesn't work for me then. Maybe because I have wildcard in my permissions or operator?

I think op bypass this. I will check. No not even if other player is op, you can see it (I not use wildcard).

**Comment by ElBananaa** [comment]
I didn't try with the latest version, and I can't rn, but I tried it in the previous version, and it was working perfectly fine. Make sure you are not operator, or don't have any admin perm.

**Comment by Sikatsu** [comment]
Correct, it works! Will close this issue, thanks for confirming.
