### ISSUE TITLE
1.19.2 - "then discord" operator bug

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2241]
### "/version ChatControlRed" - plugin version

10.16.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://pastebin.com/GTKZAwXb

### "/chc debug" output (strongly recommended)

n/a

### Information about the issue/bug

Use the ``then discord`` operator in a rule and you should get this error.
I will see if I can reproduce this on a test server and then provide a more detailed step-by-step process of how to reproduce this bug.

**Comment by kangarko** [comment]
Thanks, will be fixed asap.
