### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by AlphaBlock4k** [kangarko/ChatControl#2242]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

How can I turn off the default join message?
https://pastebin.com/zMDV7kkV
[debugfarm.zip](https://github.com/kangarko/ChatControl-Red/files/10321409/debugfarm.zip)
[debugcb.zip](https://github.com/kangarko/ChatControl-Red/files/10321435/debugcb.zip)
![87e9d539bc710125200c55a3c84b43bf](https://user-images.githubusercontent.com/56409408/210003848-6f3edbc3-1ac5-444d-82ed-fc4376db95f4.png)

**Comment by AlphaBlock4k** [comment]
and if I change the server, the join message does not come, only the switch
![e8ddb21a469fdba44d0e742e52c15fcf](https://user-images.githubusercontent.com/56409408/210004009-96a1f6b4-8d07-4176-bce9-bd1b178c7555.png)
 message

**Comment by kangarko** [comment]
Empty your messages/ .rs files to hide them. 

Use the next version that I will release in a few hours, that will fix the bug. thanks
