### ISSUE TITLE
1.19.2: What does {label} run as?

### ISSUE THREAD

**Issue by Vulm** [kangarko/ChatControl#2243]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

In Format what does {label} actually run as?

I have a command whitelist and I need to add the root of the command to the list so that staff can actually utilize the feature.

**Comment by Vulm** [comment]
nvm, runs as chc....

**Comment by kangarko** [comment]
It will use whatever you have first in Command_Aliases in settings.yml
