### ISSUE TITLE
Help messages

### ISSUE THREAD

**Issue by zS0bye** [kangarko/ChatControl#2247]
### "/version ChatControlRed" - plugin version

10.16.2

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

Hi, I noticed that on the languages, if I deactivated "Simple_Help_Design", when the server restarts it is as if it were active, I have to do /chc reload to fix it. Would it be possible to make sure that this doesn't happen on reboot?

Then I wanted to ask if it was possible to better customize the help bar above, because I wanted to remove it. (Below there will be a sample photo)
![Immagine 2023-01-04 012931](https://user-images.githubusercontent.com/52009682/210463341-46780778-158f-42c7-a2d7-76e5561370cc.png)

**Comment by kangarko** [comment]
Sorry I can't reproduce the first problem with Simple_Help_Design.

I set that option to false, restart, and it works. Try editing the file when the server is stopped.

Not right now sorry it's not possible to remove the ------, that's why we added Simple_Help_Design option.
