### ISSUE TITLE
Suggestion: Command to spy on a specific person.

### ISSUE THREAD

**Issue by SheerYin** [kangarko/ChatControl#2248]
### Summary

Monitor all operations of a player, command, anvil, book, etc.
new command: /chc spyplayer <playerName>

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

The current spy command can only spy on all players, when I want to spy on all operations of a certain player, it will be overwhelmed by other player information

**Comment by kangarko** [comment]
Thank you that's a beautiful addition! Going to pull it to our roadmap and add when I have time (no ETA)

**Comment by kangarko** [comment]
Closing, this will be up on the roadmap.
