### ISSUE TITLE
Missing hex in new chatcolor format

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2249]
### "/version ChatControlRed" - plugin version

10.16.3

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

This explains everything.

![image](https://user-images.githubusercontent.com/87967222/211086229-92588e32-f6c6-4cf6-a653-fb8ab922652d.png)

The first message is when using `/chc c #00ffff` and second one is `/chc c aqua`.

**Comment by kangarko** [comment]
Thanks will be fixed!
