### ISSUE TITLE
PlayerJoinEvent Errors

### ISSUE THREAD

**Issue by BurntValentine** [kangarko/ChatControl#225]
Getting a lot of errors on player join (new player joins) from ChatControl
Errors: https://hastebin.com/igiqesedoh.vbs

Server Version: Spigot 1.12 (latest/up to date)
ChatControl Version: 5.5.1

**Comment by kangarko** [comment]
Thank you for the report. I unfortunately don't have the source code now that I am on holidays. I will come back to it after 14th of July.

Please consider using %player instead of %nick variable temporarly.

**Comment by BurntValentine** [comment]
I currently don't have anything actively set up to use the %nick variable, it just gives this error on join of new players (doesn't seem to do it with players who have been on the server previously, new players obviously not having any nicknames set so I assume thats the cause of the error? idk)

No worries - It's only a minor annoyance with the console errors, it doesn't appear to be effecting anything I use CC for currently at the very least!

**Comment by kangarko** [comment]
Hey, please test out the latest version just released.

**Comment by BurntValentine** [comment]
That has done the trick - no more spam! Thank you :)

**Comment by kangarko** [comment]
No problem, glad it helped!
