### ISSUE TITLE
Missing colors in console format

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2250]
### "/version ChatControlRed" - plugin version

10.16.3

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

I'm glad that Kangarko managed to get rid of [Not Secure] message in console, but there are still missing all the colors that used to be there before Minecraft 1.19 came out.

`Format_Console: '&n{player_prefix}&r {player} #959595» &r{message}'`

![image](https://user-images.githubusercontent.com/87967222/211087923-7fcaefef-b1b7-4695-8742-78d99ef8d631.png)

As you can see, the colors are completely missing (player prefix is not white and `#959595` is also not white).

**Comment by kangarko** [comment]
Thanks. Try the next version, in my environment I don't see console chat colors anyways. Unfortunately that is the price for not seeing the Not Secure prefix since we have to use alternative ways of sending log messages.

**Comment by Teslicek** [comment]
Hello, this has not been fixed even in CHC 10.16.5.

CHAT CONSOLE FORMAT
`Format_Console: '&n{player_prefix}&r {player} #959595» &r{message}'`

MSG CONSOLE FORMAT
`Format_Console: '&#808080[&#FFFF00MSG&#808080] &f{sender} &#808080-> &f{receiver}: &f{message}'`

![image](https://user-images.githubusercontent.com/87967222/212089737-5ae51ea6-df90-45a0-b478-f2e701ed6a92.png)

As you can see, the colors work when MSG CONSOLE FORMAT is used, but not when CHAT CONSOLE FORMAT is used. 
(Both it settings.yml)

**Comment by kangarko** [comment]
Sorry, where is the MSG CONSOLE FORMAT and where is the CHAT CONSOLE FORMAT used? The message is the private message format? Send me your debug or just these formats and main settings.yml please

**Comment by Teslicek** [comment]
CHAT CONSOLE FORMAT
```Channels.Format_Console: '&n{player_prefix}&r {player} #959595» &r{message}'```

MSG CONSOLE FORMAT
```Private_Messages.Format_Console: '&#808080[&#FFFF00MSG&#808080] &f{sender} &#808080-> &f{receiver}: &f{message}'```

[settings.zip](https://github.com/kangarko/ChatControl-Red/files/10404840/settings.zip)

**Comment by kangarko** [comment]
Try setting Channels.Remove_Insecure_Chat_Tag to false in the next version, if that does not help then I ran out of ideas unfortunately.

**Comment by Teslicek** [comment]
Unfortunately, not even the 10.16.7 has solved the issue.

`Remove_Insecure_Chat_Tag: true`
![image](https://user-images.githubusercontent.com/87967222/213285703-2bf6bf5e-8028-454e-a77e-8bf3332a404c.png)

`Remove_Insecure_Chat_Tag: false`
![image](https://user-images.githubusercontent.com/87967222/213285806-d1d4871d-5e27-4afe-89a7-8bd982a721e0.png)

I just dont get why MSG messages have color in console properly, but CHAT messages do not.

(You can see my settings in my earlier messages).

**Comment by kangarko** [comment]
Oh I see now, because we let Bukkit send the console message in Channels but we use our custom method in Private Messages.

Fixing this is not easy, I cannot set the Bukkit's format to nothing (does not work), so I have to cancel the entire chat event for the message not to be shown. Which causes problems with other plugins hence we rollbacked that change. Sorry looks like a wontfix for now.
