### ISSUE TITLE
1.19.2: Database Log-Table clear

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#2252]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Good evening to you,

I wanted to ask if there is a way to quickly and easily delete the logs from the database up to a certain point in time or completely without deleting the database table each time.

![grafik](https://user-images.githubusercontent.com/62625225/211173223-de23e68a-e7e1-4a67-a230-243ed773a8ca.png)

**Comment by kangarko** [comment]
Hey! Probably just running a SQL:

https://www.google.com/search?hl=all&q=sql+remove+before+date
