### ISSUE TITLE
Change "Rules.Strip_Colors" setting, so the setting is more flexiable. 

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2253]
### Summary

The specific setting ``Rules.Strip_Colors`` should be changed to something like this
```yml
  # Remove colors from checked messages? Prevents bypasing filters by using colors: fu&cck.
  # [WARNING] This will remove all custom colors in the message in case it is filtered!
  # TURNING THIS OFF will break packet rules and make players able to bypass rules by using colors.
  # LEAVING THIS ON will break "then replace" if the replaced message contains colors.
  Strip_Colors: [anvil, book, chat, command, global, packet, sign, tag]
```
The reason is it should help solve the issues mentioned #756 #2040 #2052 (just to name a few)
As you could make it so rules within the ``global`` section get color codes stripped but other places like ``chat``, ``tag`` or ``packet`` don't have their color codes stripped, which means rules which contain color codes such as chat emojis, or packets won't break as you could disable it for those sections but prevent swear rules in the global section from being bypassed via chat color codes.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

By adding this, server administrators could pick which specific sections have the color codes stripped instead of being forced to have all rules or no rules strip color codes.

This would also save time, as admin could disable it for a specific section but keep color code stripping enabled for the global rules. so that server administrators do not need to add a ton of extra steps just so they can disable the stripping of color codes in one specific section like the issue mentioned #756 and #2040.

Overall, this change would make this feature a lot more flexible. Similar to how the ``Stop_On_First_Match:`` setting was changed to this
```yml
Stop_On_First_Match: [join, quit, kick, death, timed]
```
So that "timed" messages could be better utilized!

If this was added, this would also allow people to better control how nicknames are used on their network, or add custom commands via command.rs without worrying about losing color codes in the custom commands server admins make etc.

**Comment by kangarko** [comment]
@TheIntolerant or @ElBananaa would either of you guys had the time to implement this please? Should not be too technical since we already have Apply_On sections in settings.yml with the same logic you need to use

**Comment by ElBananaa** [comment]
I will try to have a look whenever I manage to get some free time.

**Comment by kangarko** [comment]
@TheIntolerant or perhaps I could just add "dont strip colors" operator so that individual rules could be exempted from this?

**Comment by TheIntolerant** [comment]
Honestly that'd work too!

**Comment by kangarko** [comment]
Added! https://github.com/kangarko/ChatControl-Red/wiki/Rules#strip-colors
