### ISSUE TITLE
1.19.3: Join message appears 2 times

### ISSUE THREAD

**Issue by ACluco1** [kangarko/ChatControl#2254]
### "/version ChatControlRed" - plugin version

10.16.3

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10372416/debug.zip)

### Information about the issue/bug

when player joins to the server, it actually shows join message, but when he also log in with /login pass command, it shows that same join message again, so it appears 2 times, one time per join and second time per login. It should appear only one time, on join or login, which could be even in settings file, when it should appear.

**Comment by kangarko** [comment]
Thanks, going to be fixed in the next version!
