### ISSUE TITLE
Add blacklist to sign spy

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#2255]
### Summary

We have CraftBook plugin installed and people can use the pipe system which requires people to place signs where line 2 is "[Pipe]" and it gets quite spammy, so it would be nice to have some sort of filter/blacklist of certain words/lines that's very common.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Our staff will continue to be spammed :(

**Comment by kangarko** [comment]
Cool! In the next version you should be able to create a rule in rules/sign.rs to prevent this from being spied/logged

```
match \[Pipe\]
then warn Your text is not spied.
dont spy
dont log
```

-Matej

**Comment by kangarko** [comment]
Actually it's \[Pipe\]
