### ISSUE TITLE
[/msg toggle] to make players unable to message you

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2256]
### Summary

Explained in headline.

Lots of plugins do have this feature, EssentialsX also (I replaced its messaging system by the one CHC provides), but I am still missing this one feature and get lots of requests from players to implement it. Would it be possible?

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Nothing much, but I cannot 100% overwrite EssX's messaging system unless CHC has it.

**Comment by ElBananaa** [comment]
I am pretty sure this is already a feature, look at our toggle part in the settings file.
The command should be something like `/toggle privatemessages` or `/toggle pm`
