### ISSUE TITLE
1.16.5: Multiple Receiver Permissions?

### ISSUE THREAD

**Issue by Jsnbrown1989** [kangarko/ChatControl#2258]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I am looking to have a button to only show if two permissions are true. I'm clueless on javascript and I doubt `receiver-permission: "permission.1 && permission.2"` would work. What should I do to account for two separate permissions?

**Comment by kangarko** [comment]
Something like this probably?

`Receiver_Script: "player.hasPermission("permission.1") && player.hasPermission("permission.2")"`

**Comment by Jsnbrown1989** [comment]
The above had YAML issues if you intended that to be inserted into the format yml. 
I removed the " and replaced it with ' so that the line is as follows: 
Receiver_Script: 'player.hasPermission("permission.1") && player.hasPermission("permission.2")'

And its showing as valid yaml however now I am getting the following error in the console:

`[13.01 17:11:13] [Server] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:639]: Caused by: org.mineacademy.chatcontrol.lib.exception.FoException: Report: Found unrecognized format keys, please remove those: {Receiver_Script=player.hasPermission("chatcontrol.message.staffmode") && player.hasPermission("bm.command.ban")}`

**Comment by kangarko** [comment]
I am so sorry, I mean "Receiver_Condition" not Received_Script, sorry!
