### ISSUE TITLE
1.18.2: About ItemsAdder, Luckperms and ChatControl-Red

### ISSUE THREAD

**Issue by anhvuquang0512** [kangarko/ChatControl#2259]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

tôi have a problem with ItemsAdder and Luckperms and ChatControl-Red 
![image](https://user-images.githubusercontent.com/112370921/212232839-e63d8ec5-4d24-4482-8d5e-8bc6a1f04a98.png)
I have added each permission like that to each rank, all is different in permission.***
![image](https://user-images.githubusercontent.com/112370921/212233007-5ce71838-ebf0-4df2-a461-dbdbb0651b16.png)
I also adjusted chat.yml like this to match the prefix of each rank
![image](https://user-images.githubusercontent.com/112370921/212233143-530c281a-f8ac-4be6-b215-2e63f4da0c1e.png)
but when i chat it shows like this

so i have a question: is there any way to help me adjust so that each rank has a prefix (I mean separate them for each rank )

**Comment by TheIntolerant** [comment]
So basically, this is working as intended, as you have all the permissions in your format for those parts so, all the parts are applied to you as you have all the permissions.

To fix this you just need to negate the permissions from the below ranks. So with luckperms you would set ``permission.default`` to ``false`` for the "hero" (assuming that is the name of the group) etc.

**Comment by TheIntolerant** [comment]
Assuming this fixed the issue, I will close this. If not comment below. :)
