### ISSUE TITLE
[Issue] Error on updating MySQL

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#226]
I keep getting this error now and then: https://pastebin.com/27wujtNL

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

**Comment by broken1arrow** [comment]
> I keep getting this error now and then: https://pastebin.com/27wujtNL
> 
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true

I think you have same problem as this post https://github.com/kangarko/ChatControl-Red/issues/206.
