### ISSUE TITLE
Unable To Enable ChatControl Pro

### ISSUE THREAD

**Issue by KensonPlays** [kangarko/ChatControl#226]
This keeps popping up in my console:
`05.07 23:26:20 [Server] INFO Disabling ChatControl v7.4.9
05.07 23:26:20 [Server] INFO ChatControl *-----------------------------------------------*
05.07 23:26:20 [Server] INFO ChatControl  Plugin is now disabled.
05.07 23:26:20 [Server] INFO ChatControl  Run /vault-info and check what is missing.
05.07 23:26:20 [Server] INFO ChatControl  prefix and suffix, that is compatible with Vault.
05.07 23:26:20 [Server] INFO ChatControl  Chat formatter requires a plugin for player's
05.07 23:26:20 [Server] INFO ChatControl *-----------------------------------------------*`

I want to have my server up and running by next Monday, and this is the only plugin that isn't fully working. It shows up as red, and I've gone through all the YML files in the plugin root directory through multiple YAML parsers, and they all say the YML is valid.

Unsure of what is going on.

**Comment by kangarko** [comment]
Please post in the correct section.

There should not be a problem in your files. Please run /vault-info command and post me the output.

**Comment by kangarko** [comment]
If it appears again, please open a new issue in that aforementioned link with the output of your /vault-info command.
