### ISSUE TITLE
1.19.2 Mute/Unmute event

### ISSUE THREAD

**Issue by Sakishima** [kangarko/ChatControl#2260]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hello.
I have a question, does ChatControl Red have an event on mute? Is there any way to use the mute/unmute event to output to discordsrv?
If there is an event, how can I use it, what parameters does it have?

**Comment by kangarko** [comment]
We did not but I implemented it for you. Here is the event: https://pastebin.com/SWd0jV8a

Will come in the next version tonight.

**Comment by kangarko** [comment]
Give me a review if you appreciated it!
