### ISSUE TITLE
Paper 1.19.2: Nickname Compatibility (HexNicks)

### ISSUE THREAD

**Issue by hatemabsi** [kangarko/ChatControl#2261]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

I am trying to integrate the nickname plugin "HexNick" into ChatControl messaging. The {receiver_nick} takes the name perfectly and everything else works smoothly. Except 1 feature.

When I try to /msg (the player's nickname), it says the player does not exist, so I was wondering if there is a way to make it so the player can message another player through their nickname. (Maybe if we can even make it so the nickname is the one that shows when you try to "tab" rather than their real name.

**Comment by kangarko** [comment]
You can contact the author of HexNicks to call ChatControlAPI#getPlayerCache().setTag(Tag.Type.NICK, "yourNick") to hook into our plugin and then it should work.

**Comment by Majekdor** [comment]
Hi. Developer of HexNicks here. Where could I find the Maven artifact information so I can hook into the plugin?

Thanks!

**Comment by kangarko** [comment]
Sorry we don't have that at the moment. Email me at matej@mineacademy.org with your BuiltByBit username or ID and I will add you a license for the plugin so you get the full jar and hook into it.

**Comment by Majekdor** [comment]
That's a shame. With HexNicks' workflow (and most Java projects for that matter), adding a jar dependency just isn't worth the hassle.

**Comment by kangarko** [comment]
I could potentially drop the files on here and you just used JitPack to hook into this repo via Maven. There's no ETA but I ping you when we add it.
