### ISSUE TITLE
1.19.2: Discord Reply Format

### ISSUE THREAD

**Issue by jack444410** [kangarko/ChatControl#2262]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

CCR version: 10.16.3

We are trying to implement the placeholder {reply} to our server.
And we noticed that there's some bug in it.

Seem the {reply} placeholder inherit the value  `DiscordToMinecraftMessageReplyFormat: ` from DiscordSRV's message.yml.

![image](https://user-images.githubusercontent.com/72694726/212465684-0c58941e-91f4-4e67-9765-5581856a1344.png)
![image](https://user-images.githubusercontent.com/72694726/212465688-2689ee1b-cadd-449d-b1f9-054c2cbaaf2b.png)

in game, the placeholder isnt showing the message correctly but showing the new message.

related values in message.yml:
```
DiscordToMinecraftChatMessageFormat: "%reply%&6【%toprolecolor%%toprole%&6】&7☍ &r%name% » %message%"
DiscordToMinecraftChatMessageFormatNoRole: "&6【%toprolecolor%%toprole%&6】&7☍ &r%name% » %message%"
DiscordToMinecraftAllRolesSeparator: " | "
DiscordToMinecraftMessageReplyFormat: " &8(回覆自訊息)   &7┌── %name% » %message%\n"
```

by the way, how can I make the reply message and player message in two different line?
eg
![image](https://user-images.githubusercontent.com/72694726/212465784-43387180-460d-4fd6-ba59-82fcd53f03de.png)

**Comment by kangarko** [comment]
I am sorry this is entirely unsupported, I can think about adding this to our roadmap when I have more time.
