### ISSUE TITLE
Discord srv channel is not receiving CHC normal chat message

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/ChatControl#2263]
### "/version ChatControlRed" - plugin version

10.16.2

### Are you using MySQL?

No

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

https://ufile.io/0a1sq2oe

Discord srv plugin and CHC has a problem together. When chatting from the server, the channel is not receiving the message. 

The channel is link properly since when I chat in it, it does shows in game. 

Please help thank you! :) 

### Information about the issue/bug

1 Run discord srv (last version)
2 Setup a global chat channel
3 Setup a console channel
4 Reboot server
5 Try to type from Discord to the game, it works
6 Try to type from the Game to Discord, chat are not appearing

**Comment by TheIntolerant** [comment]
I believe this was solved after they made some changes to the DiscordSRV config. If not, comment below and I'll re-open this issue.

Edit: going to reopen this, as I believe there was some minor miscommunication

**Comment by TheIntolerant** [comment]
After setting up a fresh server I am unable to reproduce this issue.
Below I will provide the steps I followed to setup the server.

For context, [this is the discord server setup.](https://ibb.co/Jck4Xq0)

---

1. Follow the steps on the [Discord Spigot page](https://www.spigotmc.org/resources/18494/)

> This involved changing the ``channels`` config setting
> I changed it from this https://pastebin.com/u6yDq4ze
> 
> To this, https://pastebin.com/N9t96xFZ
> 
> This was because I didn't want the "Server has started" messages etc to show up in my discord-minecraft channel, so I made the "mc-log" channel, the first channel listed in my DiscordSRV config.

2. In DiscordSRV config, set ``DiscordChatChannelMinecraftToDiscord`` to ``false`` (Requested by ChatControl to prevent Dupe messages)

3. In CHC Settings, set ``Channels.Enabled`` to ``true``

4. In CHC Settings, Under the desired channel add ``Discord_Channel_Id:`` with the Discord channel ID.

**Comment by TheIntolerant** [comment]
Also please update ChatControlRed

**Comment by kangarko** [comment]
Closing, let us know if you have more questions below and thanks to Ezra for helping out!

**Comment by CtrlAiDel** [comment]
Thanks for the support, I managed to do it! :)

**Comment by CtrlAiDel** [comment]
Hi, finally after two day of setup, i have almost everything setup, but I think I have a problem that I don't know how to fix related to this.
 
 I've got two options, and both of them are failing me

First one is having "DiscordChatChannelMinecraftToDiscord: true" set to true because I want my Minecraft message to get through discord. But when I chat between my different server MC on bungee, the bot is spamming back the message although we already received it.

(I'd like the bot only to send the message when it's from discord directly, and not from a server (it's kind of a loop)

The other option is to set DiscordChatChannelMinecraftToDiscord: false to false like the support team told me, but when I do that, I am not receiving the message from the game to discord and that's an option I want.

 Thanks for your support

**Comment by CtrlAiDel** [comment]
![1235345345345](https://user-images.githubusercontent.com/40178706/213616395-f07eaccd-dfe4-43c9-bb29-bad286907f3c.png)

**Comment by TheIntolerant** [comment]
I looked through the debug file you provided above and it seems you haven't configured the discord part for any of your channels.

please have another read through [https://github.com/kangarko/ChatControl-Red/wiki/Discord](https://github.com/kangarko/ChatControl-Red/wiki/Discord) in case you missed any steps by accident.
