### ISSUE TITLE
1.18.2 - plugin problem

### ISSUE THREAD

**Issue by Kaktus207** [kangarko/ChatControl#2264]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I have a problem with the plugin, namely deleting chat messages stopped working, it worked before but recently stopped.
plugin version 10.16.5

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10437614/debug.zip)

**Comment by TheIntolerant** [comment]
Could you type ``/ver ProtocolLib`` and confirm that you are using either this build or later (if a new build is released)

![image](https://user-images.githubusercontent.com/48093184/212967523-daae0ea9-e506-4422-8a9a-6bb2fa185fda.png)

**Comment by kangarko** [comment]
Use this ProtocolLib:

https://github.com/dmulloy2/ProtocolLib/releases/download/4.8.0/ProtocolLib.jar

**Comment by Kaktus207** [comment]
I have it but it doesn't work

**Comment by kangarko** [comment]
Something that you changed broke it. I see ViaVersion, try removing it for ONE restart instance to see if that helps. Also try deleting other chat or packet interfering plugins perhaps you have updated those.
