### ISSUE TITLE
1.19.3: Text from Discord is showing a text event in the game but without the text.

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/ChatControl#2265]
### "/version ChatControlRed" - plugin version

10.16.6

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://ufile.io/2q9reokx https://ufile.io/kjxd7ies  https://ufile.io/pgtbadci

### Information about the issue/bug

1. Install Discord SRV and CHC on multiples server.
2. Create bots. for each of the server and invite them to the discord
3. I couldn't tell you my exact specific setupfor why there is a mistake sorry
4. Now I have the chat from the Game to discord that works, but to opposite doesn't
5. When I type in discord then only thing that shows up is [x] My name in gray. without any text In the console it shows:
[ChatControlRed] [standard] my name + text

![issue 744](https://user-images.githubusercontent.com/40178706/213838123-3cf8bf6f-9b78-4927-ae5c-3d70afb0d88a.png)

**Comment by CtrlAiDel** [comment]
Can 4 differents bots, be on the same channel without duplicating messages? It's not the problem at the moment, but earlier it was.. It might had been the good config but just impossible to do?

**Comment by CtrlAiDel** [comment]
im tired of working on this, I created 4 channel for each bot ... that's enough

**Comment by kangarko** [comment]
To avoid duplication of messages if you have DiscordSRV on multiple servers in a BungeeCord network, see this link please:

https://github.com/kangarko/ChatControl-Red/wiki/Discord#bungeecord
