### ISSUE TITLE
1.19.2: Big lag - something about DB

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2266]
### "/version ChatControlRed" - plugin version

10.16.5

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://pastebin.com/7tqEAZrA sql-error.log: https://pastebin.com/hWWgEci4

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10471340/debug.zip)

### Information about the issue/bug

There was big lag, around 2s or more, not sure what happened, but you'll see more in the log.

Also, not sure if Chatcontrol isn't a little bit laggy. I have these regular TPS drops, some plugin is probably saving its data every minute. Can't it be Chatcontrol? It figures in the sparks that I create, can you check it, please?

Some weird spark with 3000 ms from CHatcontrol, may related to the issue above. https://spark.lucko.me/li8Cqgf7Zg

Classic spark  longer: https://spark.lucko.me/hzd4ZDdjrk
Shorter: https://spark.lucko.me/0STYnRlnDw

**Comment by bobhenl** [comment]
Just a note, received this from FAWE as well after this error: https://pastebin.com/E4CjSqsc

**Comment by kangarko** [comment]
@bobhenl please see this advice: https://stackoverflow.com/a/10959780

You need to change the collation of your table to support storing 4-bytes-long unicode

**Comment by kangarko** [comment]
I think also fastasyncworldedit may be causing some issues there, resolve that first before concluding it's ChatControl, thanks.
