### ISSUE TITLE
Link in chat

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [kangarko/ChatControl#2268]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hello, every time I send any link to chat, it cannot be opened. There is a default "/msg playername".
Is it possible to somehow enable to always be able to open also the sent link? What can I do for that? Thank you

![image](https://user-images.githubusercontent.com/68572049/214273839-6b067075-fa43-4dcf-87a7-05968b716ca8.png)

**Comment by kangarko** [comment]
Try seeing these advices: https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#the-url-in-my-messages-are-not-clickable and https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#ad-filter-doesnt-work-all-dots-are-removed-example-wwwgooglecom-becomes-www-google-com

**Comment by Sh3r1ffCZ** [comment]
I tried "https://www.youtube.com/watch?v=d1YBv2mWll0 &r" and still couldn't click on the link.
I use LuckPerms on my server. I really don't know what it could be, but when I click on the link, it automatically says "/msg playername", but it won't open the link.

**Comment by kangarko** [comment]
Post me your /chc debug please

**Comment by Sh3r1ffCZ** [comment]
Here
https://ufile.io/tb1yhbgd

**Comment by ElBananaa** [comment]
You issue probably comes from this part of your chat.yml format file:
```yml
  message:
    Message: '&7 ►&f {chat_color}{chat_decoration}{message} '
    Suggest_Command: '/msg {player_name} '
```

Remove the `Suggest_Command:` part, and you should then be able to click links again.

**Comment by Sh3r1ffCZ** [comment]
Ok, ill try. Thanks
