### ISSUE TITLE
Dynamic chat range for ranged chat (Idea from CMI)

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2269]
### Summary

CMI added this today.

> Added new option to have dynamic chat range which will change depending on amount of players you have currently online. This will allow to enable global chat when you have small amount of players and lower char range on peak times automatically.

This is brilliant, I use ranged chat via ChatControl, seems like a simple/great addition that should be added into ChatControl!

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Nothing? Its a feature not a problem github text box!

**Comment by kangarko** [comment]
Sounds good, how would you configure that? Shall I add a function such as:

Dynamic_Range_Formula: "{players_amount} / 2"
Max_Players_For_Global_Chat: 50

So if there's 50 or less players, global chat will be used. Otherwise let's say there's 100 players we will show the ranged chat in 50-blocks radius? (100/2)

Is that how you need it to work?

**Comment by TomLewis** [comment]
Personally I use range as its own channel, and have a seperate global channel currently, but I like the idea of Global channel when its quiet and ranged when its super busy, say 50+, or allow maths in the `Max_Players_For_Global_Chat` too? So then its not fixed (Brains half asleep today) haha

It would be nice if there could be an option for a ranged channel too, so ignoring global, to dynamically change the range based on players online just for that channel.

Cant belive I didnt think of this feature! its so simple!

**Comment by TheIntolerant** [comment]
Is this what you mean, it could be either a fixed value or a percentage. 

So if you have a setting like this

1) ``Max_Players_For_Global_Chat: 50``
If there are 50+ people online, it changes to a ranged chat

2) ``Max_Players_For_Global_Chat: 50%``
If there are 50% or more people online (based on the "max-players" in your server.properties), it changes to a ranged chat

**Comment by TheIntolerant** [comment]
Personally, I think the ``Dynamic_Range_Formula:`` could be a bit weird, with the current example.

For example with the ``"{players_amount} / 2"`` as the formula.
100 peoples = 50 range (100/2)
80 people = 40 range (80/2)

but surely you would want it to be a bigger range if there are fewer people online.

---

The idea could 100% work, just be careful with the maths. :P

It might be enough to just have the "Max_Players_For_Global_Chat:" setting.

**Comment by kangarko** [comment]
I love the idea with the percentage!

I think we could just add the following simple Channel key to the config:

`Dynamic_Range_Player_Threshold: 60%`

or

`Dynamic_Range_Player_Threshold: 60`

So for that given channel we would enable Ranged mode if there's over 60% of server's max players connected (or 60 players literally if no percentage is used).

@TomLewis you would still keep your global channel as always-global and only have that option for the ranged one, would that work?

**Comment by TomLewis** [comment]
> The idea could 100% work, just be careful with the maths. :P

haha yeah, thats what im not sure about! may need some trial and error!

> you would still keep your global channel as always-global and only have that option for the ranged one, would that work?

Yeah I would still keep Global (For now) as thats what players are used to, but it may be very handy to have an overall like CMI does for specific worlds/events/other types of servers.

This will require some testing with numbers, I dont have a good idea in my head for the correct defaults! (I wonder how much world size matters in this respect)

**Comment by kangarko** [comment]
Added https://github.com/kangarko/ChatControl-Red/wiki/Channels#min_players_for_range !
