### ISSUE TITLE
[Issue] Error with DiscordSRV

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#227]
This error shows up once in a while within the console: https://pastebin.com/WaMZ9fiL

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

**Comment by broken1arrow** [comment]
> This error shows up once in a while within the console: https://pastebin.com/WaMZ9fiL
> 
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true

I not use latest on this server and get this (10.0.3), I think DC lost connection for a second. So ether i get lucky or that version handel it better.

Can be for he use MySQL and BungeeCord and i not.
```
04.12 10:55:18 [Server] ERROR [DiscordSRV] [JDA] There was an I/O error while executing a REST request: timeout
04.12 10:55:18 [Server] ERROR [DiscordSRV] Failed to send message to channel TC:consol(618718095220932650): 503: N/A
```

**Comment by kangarko** [comment]
Thanks, this is a problem with DiscordSRV. I will make this only visible when the Debug option is on [discord] in settings.yml
