### ISSUE TITLE
1.18.2: Is velocity updated so I can update chatcontrol red?

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2270]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Can I update Chatcontrol red now? Im using 10.13.10 and couldnt update as I use Velocity which isnt properly supported and there was an issue with it being updated, which got me stuck being able to update ChatControl Red!

What is the process with Velocity now? Can I update both? Will there be future breaking changes that will prevent me using ChatControl because of Velocity support? 

Sadly there are too many seucity and performance issues with Waterfall to move back to it.

**Comment by kangarko** [comment]
Yep James has done an update a few weeks ago: https://github.com/kangarko/VelocityControl/releases/tag/3.11.0

@james090500 just to confirm can you please run a quick check on today's version?
