### ISSUE TITLE
1.19.3: Custom Variable Trailing Space

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2272]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

How can I use the trailing space inside a custom variable? The custom variable I have works and shows up in chat using the { } but I can't seem to make it work with the + operator to append a space before/after.

**Comment by HorusApl** [comment]
Specifically, I need this variable in my chat.yml format to be usable with the + operator:
  cstag-meta:
    Message: '{cstag+}'
    Sender_Condition: '''%deluxetags_tag%'' == '''''
    Hover:
    - '&7Testing!'
I can make it work as an individual variable {cstag}, but as soon as I add the + it breaks the variable.

**Comment by kangarko** [comment]
Hey, as a workaround you would need to create a javascript placeholder in variables/ and then just add the space using the ternary operator in javascript. You can see the player-is-vanished.yml file for example.
