### ISSUE TITLE
1.19.3: Player randomly loses formatting, accompanied by NPE

### ISSUE THREAD

**Issue by malonnnn** [kangarko/ChatControl#2273]
### "/version ChatControlRed" - plugin version

10.16.8

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/c1d0b51fcdd04ce9929b8cb328c5c761

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10530322/debug.zip)

### Information about the issue/bug

I'm not certain how to reproduce it, it happened randomly.

Suddenly, without warning, a player lost all chat formatting, accompanied by an NPE in the console, and subsequent messages were just fine.

**Comment by kangarko** [comment]
Your view condition for some chat format component is failing. I have adjusted the error to be more informative and point out where you need to fix it.
