### ISSUE TITLE
1.19.3: ChatControlRed using high amount of server resources

### ISSUE THREAD

**Issue by Yertled** [kangarko/ChatControl#2274]
### "/version ChatControlRed" - plugin version

10.16.8

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10530930/debug.zip)

### Information about the issue/bug

With 64 players online, we hit lower TPS than average. We might hover around 15 TPS with that amount of players, but now we were at 10 TPS for a long time.
After checking Spark profiler, it shows ChatControlRed using 13%, which is VERY HIGH!
https://spark.lucko.me/h8wlxIVC3C

In general, ChatControlRed has been at the top of the usage chart, being the most demanding plugin on our server.
Is there any optimization changes we can fix to help lower the lag the plugin causes?
Thank you in advance.

I took a screenshot of the exact spot where I see the percentage.
![image](https://user-images.githubusercontent.com/12172847/215357146-1b40503b-5220-456f-97be-64b60fca3e8c.png)

**Comment by kangarko** [comment]
Hey and thanks for reporting.

I can see that the Tab_Complete section of your settings.yml has a long list of regular expressions. We are compiling them each time. The solution would be for me to pre-compile the expression at the plugin start/reload, you can test this improvement in the next version and report. 

Also keep in mind that simply by the laws of nature, the more regex you throw in that whitelist, the more CPU cycles it takes to evaluate, so the less you have in your settings the smaller the impact. You can read more about performance [here](https://github.com/kangarko/ChatControl-Red/wiki/Performance).

**Comment by Yertled** [comment]
Thank you for the quick response @kangarko .
Is there any other method of only showing certain commands to players? We would like to only show commands players can actually run and use. Is ChatControlRed maybe not the best place to do so?
Also, I will test the update once it comes out.

**Comment by kangarko** [comment]
Cool let me know below!

**Comment by kangarko** [comment]
Please use 10.16.10
