### ISSUE TITLE
1.19.3: Death messages sending multiple death for same person even though Stop_On_First_match in Conf is set

### ISSUE THREAD

**Issue by Michael-A-Sloan** [kangarko/ChatControl#2275]
### "/version ChatControlRed" - plugin version

10.16.8

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10538035/debug.zip)

### Information about the issue/bug

Found that the death messages send 2 to 3 times even with the config setting for Stop_On_First_Match set properly.

<img width="848" alt="image" src="https://user-images.githubusercontent.com/89812914/215544878-8e3cb4e4-b947-4687-9a32-16b7a4ae84ac.png">

**Comment by kangarko** [comment]
Might be a bug with PerWorldPlugins how the death event is fired, try removing it for one testing round. In that case unfortunately I am unable to fix it since I have no control over that plugin.
