### ISSUE TITLE
1.19.3: Player does not connect through Bungee

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#2276]
### "/version ChatControlRed" - plugin version

10.16.8

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10538367/debug.zip)

### Information about the issue/bug

I'm in the server and I'm also in the channel.
But if I want to switch to another channel or change the status of the current channel, it will show that I am not connected through Bungee.

]This server is running BungeeCord version git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:f8e0bcc:1675 by md_5

BungeeControl-Red 3.12.2

This server is running Paper version git-Paper-386 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)
You are running the latest version
Previous version: git-Paper-383 (MC: 1.19.3)

**Comment by TheIntolerant** [comment]
This should be fixed by updating to ``BungeeControl-Red v3.13.4``
Version 3.13.4 is required for ChatControl 10.16.2 and up

Let me know by commenting below if this doesn't fix your issue and I'll re-open this.
