### ISSUE TITLE
1.19.3: Failed to connect to mysql database ("Could not make new instance of public com.zaxxer.hikari.HikariDataSource(com.zaxxer.hikari.HikariConfig)")

### ISSUE THREAD

**Issue by scarlettcloud** [kangarko/ChatControl#2277]
### "/version ChatControlRed" - plugin version

10.16.8

### Are you using MySQL?

Yes

### Error log (if applicable)

https://pastebin.com/wGTnqYUi

### "/chc debug" output (strongly recommended)

Plugin disabled after failure to connect so I can't run the debug - here's the console output as well [https://pastebin.com/k9wh6fsV](https://pastebin.com/k9wh6fsV)

### Information about the issue/bug

So I've had this issue intermittently for a while; usually running flush hosts on the mysql database works, but with the update to 10.16.8 that hasn't seemed to fix anything. I run a Velocity proxy with between 3-6 backend servers connected and using chatcontrol/mysql at all times. The failure to connect happens on every server with ChatControl, this log and output is from my lobby/hub server specifically but it's the same issue for each.

If relevant - the proxy is 1.19.3 velocity, hub is 1.19.3 purpur.

**Comment by scarlettcloud** [comment]
Adding this as it's the same issue I reported here - https://github.com/kangarko/ChatControl-Red/issues/2172

Flush hosts is no longer working for me

**Comment by scarlettcloud** [comment]
Sorry for more comments; wondering if it's the same issue as identified here for bungeecord and just needs to be updated for Velocity? https://github.com/kangarko/ChatControl-Red/issues/2183

**Comment by scarlettcloud** [comment]
So I think I fixed it by editing the connector string - I added &allowPublicKeyRetrieval=true
(Full string: jdbc:mysql://{host}/{database}?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8) This has fixed 2/6 servers so far (still updating them all). 

I have no idea what a public key is or why it needs one but it does fix it. I will leave that to the gods to ponder. 

StackExchange says that "allowPublicKeyRetrieval=True could allow a malicious proxy to perform a MITM attack to get the plaintext password" which sounds bad but I genuinely have zero mysql or database knowledge and I don't think any of the six players on my server know how to perform an MITM attack so ¯\_(ツ)_/¯ . I'm going to close this but wanted to give that update just in case it's still something you guys need to know about, or for the future server admin furiously googling for a solution to this problem.

**Comment by ElBananaa** [comment]
@kangarko @james090500 You guys may want to review this ^^

**Comment by kangarko** [comment]
I am going to add a toggle to disable HikariCP so you can use the old Java pool instead

**Comment by scarlettcloud** [comment]
Thank you! Happy to test anything you need, too. The public key retrieval string has worked on all servers except the one that's still on 1.19.2, but the console log there looks like a genuine too many connections so I'm running flush hosts again.

**Comment by ElBananaa** [comment]
HikariCP shouldn't cause too many connections as its whole point is to decrease the amount of connections by pooling them (which also provides a significant perf gain). Seems more like we're somehow doing something wrong somewhere. (In which case that's probably on me since I initially made the changes for HikariCP). The weird thing is, I never experienced a such issue.

As for the original issue, I honestly think that allowing users to toggle HikariCP is more of a workaround than an actual fix to the issue. I'd gladly have a look at it, unfortunately I don't have the time to even try to "debug" things a bit... :/

**Comment by ElBananaa** [comment]
@scarlettcloud Instead of using `&allowPublicKeyRetrieval=true`, could you please try to remove this argument from one of your server, and change `autoReconnect=true` to `autoReconnect=false` on the same server to see if it helps

**Comment by scarlettcloud** [comment]
Sure! Let me check quickly on one of the ones that the `&allowPublicKeyRetrieval=true` fixed

**Comment by scarlettcloud** [comment]
So it connected fine without the publickey string, and with `autoreconnect=false` on one of the 1.19.3 servers, I did get this in the console as it connected: 

```
[31.01 12:27:56] [Server] [INFO] [com.zaxxer.hikari.pool.HikariPool] HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@12782e97
[31.01 12:27:56] [Server] [ERROR] [STDERR] [com.mysql.jdbc.Driver] Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

```

**Comment by ElBananaa** [comment]
This is weird, the plugin should only rely on the old driver class for legacy minecraft/java versions. Could you please provide us the full log from where the warning above comes from?

**Comment by kangarko** [comment]
Thanks for sharing, the Hikari option will be added to the next release as last resort option alongside the tips you shared here to resolve issues..

**Comment by scarlettcloud** [comment]
@ElBananaa I'm not seeing a corresponding error.log for that driver output; just the one from failure to connect. Here's my whole error.log file https://pastebin.com/g6PCKB3z

**Comment by ElBananaa** [comment]
> @ElBananaa I'm not seeing a corresponding error.log for that driver output; just the one from failure to connect. Here's my whole error.log file https://pastebin.com/g6PCKB3z

I was referring to the latest.log x)

**Comment by scarlettcloud** [comment]
Ahh okay here you go! https://pastebin.com/4e1LiGSd 

Hopefully it hasn't been too long and it has everything

**Comment by kangarko** [comment]
It says "Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it."

**Comment by scarlettcloud** [comment]
Ugh sorry, try this one: https://paste.gg/p/anonymous/adb3f801166f41de9391a9f52296744a

I think I swear in chat and so pastebin made me set it to private

**Comment by ElBananaa** [comment]
> Ugh sorry, try this one: https://paste.gg/p/anonymous/adb3f801166f41de9391a9f52296744a
> 
> I think I swear in chat and so pastebin made me set it to private

Alright, so this isn't a ChatControlRed issue, but as DiscordSRV one. As you can see on the code below, the error is prefixed with `DiscordSRV`.
```
[11:27:56] [Server thread/INFO]: [com.zaxxer.hikari.pool.HikariPool] HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@12782e97
[11:27:56] [DiscordSRV - Initialization/ERROR]: [STDERR] [com.mysql.jdbc.Driver] Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
```

**Comment by ElBananaa** [comment]
Anyways, @kangarko I just made a PR in which I updated chatcontrol dependencies and turned off autoReconnect by default as it appears this is what's recommended by MySQL, it can lead to many issues (This one included apparently) and it actually is not required when HikariCP is used. That's the best I can do for now.

@scarlettcloud Can you please confirm that setting this option to false did fix the issue for one or multiple servers?

**Comment by scarlettcloud** [comment]
It did fix them! I removed the public key string as well and they all seem fine now. And oh good catch I missed that! Thank you again, seriously, for all the help!
