### ISSUE TITLE
1.19.3: Cannot change nick

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2279]
### "/version ChatControlRed" - plugin version

10.16.8

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10553784/debug.zip)

### Information about the issue/bug

I have one player who cannot change their nick under any circumstance. I have tried to sudo them, changing myself from console/OP privileges, having them change it, nada. No matter what we try, this one player cannot change their nick. When they change the command, it goes through and it changes in my TAB plugin, DiscordSRV plugin, and others but will not change in chat. All other players can freely change their nick without issue.

**Comment by kangarko** [comment]
What is the name of the player? What exactly is he changing the nick to?

**Comment by kangarko** [comment]
Closing due to inactivty, comment below when you come back.

**Comment by HorusApl** [comment]
Their full ign is SavannahsSimp, and they can't change their nick to anything. Even tried just the word "test" and no dice.

**Comment by kangarko** [comment]
I am sorry I cannot reproduce:

![a](https://i.imgur.com/hjL9yMe.png)

 Does it say that the nick was edited for the player?

**Comment by HorusApl** [comment]
Yes it does say it was edited properly, and it shows up everywhere except for in-chat.

**Comment by kangarko** [comment]
I have made some changes to the code but still was not able to reproduce your problem on my machine, as seen above.

Try only testing with ChatControl without any other tag or chat -related plugins, if not then unfortunately it's a third party issue and I am unable to move forward.

**Comment by HorusApl** [comment]
Alright I fixed it but not by removing any plugins of any kind. I use Essentials for my nicknames, which ChatControl picks up on. If I change {player_nick} in my chat.yml format to %essentials_nicknname%, their nick works fine. I checked my rules to make sure "Simp" wasn't being triggered somehow, but this does appear to be a ChatControl issue.
