### ISSUE TITLE
1.19.2: Console colours no longer working

### ISSUE THREAD

**Issue by addstar** [kangarko/ChatControl#2281]
### "/version ChatControlRed" - plugin version

10.16.10

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/addstarmc/b62b870b59d6442aabe73663fdd0b1a6

### Information about the issue/bug

Hi,
We've just updated to 10.16.10 and console chat colour are no longer working. The colours work fine in game, with the exception of some messages generated from our own plugin using the ChatControlRed API.

I believe this was due to the Vault changes from #2246, it's attempting to check perms for `CONSOLE` player (which I don't think is possible with vault). I'm wondering if it's possible to just put in a bypass to _never_ check perms for console? Or have a way to disable the Vault check for those of us using LuckPerms? Thanks :slightly_smiling_face:

**Comment by addstar** [comment]
Actually, we rolled back to our previous version (10.14.9, haven't updated for a while) and still have no console colours :thinking: Although the Console/Vault error is gone.

Might be something else causing it, we're doing some more testing..

**Comment by kangarko** [comment]
That's a smart observation! I will add an if-condition for console to allow all colors and send you the test build soon.

**Comment by kangarko** [comment]
Should be resolved in 10.16.11!
