### ISSUE TITLE
Gradients

### ISSUE THREAD

**Issue by Candousek** [kangarko/ChatControl#2282]
### Summary

Hello, is there any way to use gradients, if so how? If there is not, I would love it to be added in the next version. Thanks loves

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

I would be sad.

**Comment by kangarko** [comment]
Hey Candousek!

There is a way to use gradients in formats/ folder by using the Gradient key, please see the Format page of Wikipedia for examples.

**Comment by DeusNinja** [comment]
May you please elaborate on how this is done? I'm confused by how you mean "gradient key".

**Comment by DeusNinja** [comment]
For anyone else that comes across this in the future: https://github.com/kangarko/ChatControl-Red/issues/1659
