### ISSUE TITLE
Paper 1.17.1 : FoException Report: Unable to deserialize class java.lang.String from json

### ISSUE THREAD

**Issue by Smedve** [kangarko/ChatControl#2283]
### "/version ChatControlRed" - plugin version

10.16.10

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/774a522750024416b21e0f0758d07d5f

### "/chc debug" output (strongly recommended)

https://ufile.io/zbwwqg6q

### Information about the issue/bug

toast message not send other server

**Comment by kangarko** [comment]
Update your BungeeControl Red.

**Comment by Smedve** [comment]
my bungeecontrolred version 3.13.5
but not working :/

**Comment by ElBananaa** [comment]
Reopening for further investigation.
@kangarko

**Comment by kangarko** [comment]
Please provide steps to reproduce. What command did you type? When does it appear?

**Comment by kangarko** [comment]
I see it is coming from /chc announce but there is many combinations of this command, please provide the exact one you typed since I am not able to reproduce it myself.

**Comment by Smedve** [comment]
chc announce toast text

(Ha jól láttam cégadat szerint magyar székhelyű, esetleg magyarul is lehetne írni? 😅)

**Comment by kangarko** [comment]
Try the next release that I will push out in 1 hour.

Sajnos nem beszélek magyarul!

**Comment by Smedve** [comment]
@kangarko 

https://ufile.io/ijj1hpwy
https://paste.gg/p/anonymous/b729c7e9f3ba4e9c9d9fd736b46cd9e9
https://paste.gg/p/anonymous/07b81027a3474c4f810f5ea9eb0a1aad

**Comment by kangarko** [comment]
Fixed!
