### ISSUE TITLE
1.19.3: Can't get redis to work with VelocityControl

### ISSUE THREAD

**Issue by Folas1337** [kangarko/ChatControl#2284]
### "/version ChatControlRed" - plugin version

10.16.10

### Are you using MySQL?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10608929/debug.zip)

### Information about the issue/bug

I can't get chat to work across two proxies, it does however work over the same proxy on two different backend servers.

I have reset ChatControl entirely and it's the only plugin running on the backend servers at all to eliminate any other source that could be causing this issue.

- The only settings I have enabled is "Integration.BungeeCord: true" and "Channels.Enabled: true", I have also set up MySQL accordingly.
- I have installed RedisBungee https://github.com/ProxioDev/RedisBungee and it's currently in use by another plugin, so that makes sure that RedisBungee is set up properly
- I have made sure both backend servers have their appropriate name set in server.properties under the key server-name, they are called "test1" and "test2", the same way they are called in both proxies' velocity.toml
- I have installed VelocityControl on both proxies and set up the Server_Aliases as follows:
```yaml
Server_Aliases: 
  test1: "test1"
  test2: "test2"
```

I hope so far that was all good and fine, now here is the problem. If I log in with user1 and user2 on the same proxy and connect to test1 and test2, messaging across both backend servers works fine, all messages go both ways __but__ if I now connect user2 to proxy2 and backend server test2, it won't forward any messages at all.

The weirdest thing is that I have also been debugging this issue on the redis server by using redis-cli monitor, which shows the other plugin's messages but not ChatControl's - this also makes me wonder how the messages get to the other server in the first place as I have "bungee-plugin-message-channel: false" in both velocity.toml

If there is anything else I can provide or do, please let me know cause I'm at a loss regarding this situation and I couldn't find any other information but what I've provided and done.

**Comment by Folas1337** [comment]
I have now also reduced the plugins on the velocity proxies to a minimum, leaving only luckperms, redisbungee and velocitycontrol but to no avail :(

Edit 1:
RedisBungee version 0.10.1
VelocityControl 3.11.1-SNAPSHOT (I also tried 3.11.0 with no success)

Edit 2:
Oh yeah one more thing, when user1 and user2 are both on proxy1 and connected to test1 only the first user to join can change channels, the other one will be told `Player 'user2' is not connected through BungeeCord` and I have no idea why that's happening at all... I can however use "/ch send global <msg>" to get around this limitation. All quite strange to me.

**Comment by BearLeonLight** [comment]
Are you using multiple Velocities?
Velocity Control should not currently support RedisBungee.
Because when you have multiple Velocities, he cannot pass messages through more than two Velocities at the same time.
Will invert the individual delivery message channels.

The suggestion is that you only install Velocity on the backend (server), and use haproxy on the external master (ProxyServer or Proxy VPS) to send traffic (connection) to the backend (server) Velocity.
(My English is not good and I use GOOGLE translation

**Comment by ElBananaa** [comment]
@james090500 @kangarko Could you guys please have a look whenever you have some free time.

Also, as a side note, it appears to be only happening with VelocityControl. Multiple users reported this to be working perfectly fine on BungeeControl.

**Comment by Folas1337** [comment]
> Are you using multiple Velocities? Velocity Control should not currently support RedisBungee. Because when you have multiple Velocities, he cannot pass messages through more than two Velocities at the same time. Will invert the individual delivery message channels.
> 
> The suggestion is that you only install Velocity on the backend (server), and use haproxy on the external master (ProxyServer or Proxy VPS) to send traffic (connection) to the backend (server) Velocity. (My English is not good and I use GOOGLE translation

I am using multiple velocity proxies but as @ElBananaa said, it works on BungeeControl, I'm not sure if VelocityControl even has support for RedisBungee but from what I read it sounded like it would.
I guess we'll wait for James to chime in on this and let us all in on their wisdom.

**Comment by kangarko** [comment]
My scope of expertise is outside of Redis and the integration is not done by myself. The best I can do is to share the source code responsible for packet distribution in BungeeControl Red which you should install on all of your BungeeCord instances (or VelocityControl for that sake) and I will be happy to assist if you or one of your developers is able to debug this:

https://bitbucket.org/kangarko/bungeecontrol-red/src/master/src/main/java/org/mineacademy/bungeecontrol/model/Redis.java

**Comment by kangarko** [comment]
Let's continue the conversation here

**Comment by Folas1337** [comment]
What if I don't have a developer who's able to debug this and it's just me as the owner/user of my plugins?

Also wouldn't @james090500 have to "simply" (not sure how simple this really is) implement that into VelocityControl?

**Comment by kangarko** [comment]
Gonna wait for James to reply if he has a suggestion on next steps in this matter.
