### ISSUE TITLE
Chat Tags - (Improved version of Deluxe Tags)

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2285]
### Summary

I would like to have the ability for players to select/pick Chat/Tab/Tag tags (via a placeholder)
I can only find two existing solutions and they have issues:

- deluxetags, https://www.spigotmc.org/resources/deluxetags.4390/
    - Abandoned in terms of adding required features or bug fixing.
    - ~~No RGB support~~ Hex may be working? Even tho its not in changelogs or features list, seems to show?
    - No Gradient support
    - No MySQL
    - No preview tags permission
    - No sorting at all, you have to manually put in a number for each tag to order.
- ImmortalTags https://www.spigotmc.org/resources/%E2%AD%90-50-off-sale-%E2%AD%90-immortaltags-%E2%AD%90-the-ultimate-chat-tags-plugin-%E2%AD%90-1-8-1-18-%E2%AD%90.79698/
    - Not the best reviews
    - Rarely if ever updated and no 1.19 support.
    - Their website immortalplugins.com is taken over by a domain squatter, so also Abandoned.

It seems there's a big gap in the market for an updated Chat Tags plugin.
Personally I would use the placeholder to use above players heads with the plugin "Tab" and when hovering over messages in chat.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Use deluxetags most likely and work around its missing features.

**Comment by kangarko** [comment]
We do have the /tag command adding prefix, suffix and nicks feature. Would you specifically like players to be able to set one custom tag?

You can create a makeshift tag feature if you place this to your rules/chat.rs

```
# Or you can create advanced bots saving and showing data (data is saved permanently)
# See https://github.com/kangarko/ChatControl-Red/wiki/Rules for a tutorial
match ^(\@bot name)$
ignore key name
then warn &8[&dBot&8] &7Please enter your name.
then deny

match ^(\@bot name)$
require key name
then warn &8[&dBot&8] &7Your name is: {data_name}
then deny

match ^(\@bot name) null$
strip colors false
save key name
then warn &8[&dBot&8] &7Removed your name.
then deny

match ^(\@bot name)(.*)
strip colors false
save key name "$2".trim()
then warn &8[&dBot&8] &7Saved your name as: {data_name}.
then deny
```

And then this to formats/chat.yml or wherever you want to show it:

```
custom-prefix:
    Message: '&8[&f{data_name}&8] '
    Sender_Condition: '"{data_name}".length !== 0'
```

You need the next version to show the tag! HEX should be supported. With some effort you will be able to expand on this to your likings. Hope that helps! (The data_ variables are automatically stored in mysql and flatfile)

![a](https://i.imgur.com/Frvccqv.png)

**Comment by TomLewis** [comment]
You can select tags from a GUI like in deluxetags? Am I blind I cant see the docs page! haha

I dont want players to be able to create tags, I want there to be a big selectable GUI list, that can click and be able to show it in "tab" plugin via placeholder

**Comment by kangarko** [comment]
I see, hmm we don't have that. 

I could look into creating another premium plugin for fine, it's been a while since I did, but at present my schedule is full for at least a week. Lets say I take DeluxeTags as base to create it - what features are you using in it? I dont need to code those you are not using

**Comment by kangarko** [comment]
I am not promising to create a separate plugin I am just gathering ideas since I planned to release new plugin this year anyways

**Comment by TomLewis** [comment]
I think thats whats needed someone to improve on Deluxe Tags, I just cant believe its not a regularly updated Tags plugin out there! Unless they are bunled into other chat plugins.

its all needed apart from things like format_chat, legacy_hex and DeluxeChat support. No need to add in legacy support, DeluxeChat or formatting chat! Everything else is standard and needed.

The key thing missing from DT is the preview tags permission, If we have 500+ tags in game for players to customise whats shown above their heads, they need to actually be able to see whats avabile and how to get them (via description) could even have its own click behavior for preview tags. Very odd this wasnt ever implemented origonally. 

It is a very simple plugin, just missing a few core basics otherwise it does work fine.

**Comment by kangarko** [comment]
Cool, I am bookmarking this. Gonna rethink this in a week or two when I have more time.

**Comment by TheIntolerant** [comment]
While it may not be possible to create an inventory type GUI, you could make a chat GUI using chatcontrol and the ``{data_<key>}`` placeholder.

It won't necessarily be an easy process compared to a dedicated plugin but definitely possible.

Also with the data placeholder, as that had PlaceholderAPI support ``{chatcontrolred_data_<key>}``, you can use this placeholder to get the same data but in other plugins, so you could use a third party plugin to make an inventory GUI, while chatcontrol does the rest via rules.

**Comment by TomLewis** [comment]
If one universal GUI system could be created and re-used then you could also implement this:
https://github.com/kangarko/ChatControl-Red/issues/1476

You could also then give options to put things like the /ignore list into a GUI for players and /l for cross server network player lists with custom click actions for the online players.

I know its not strictly "chat" but then we get to use resource packs to make these menus look awesome.

**Comment by kangarko** [comment]
I can create the Tag plugin you were talking about initially. 

These requests seem like a bigger project for ChatControl Red alltogether, I only have time for one. I think the Tag plugin could work out, I can send you more info once I begin working on it.

**Comment by TomLewis** [comment]
Bonus points, allow placeholder(s) as placeholder tags, so a player can unlock a placeholder to show above their head, then that opens up a ton of interesting options. PlaceholderAPI support for other placeholders!
