### ISSUE TITLE
"Party And Friends" plugin dependency issue

### ISSUE THREAD

**Issue by Simonsator** [kangarko/ChatControl#2287]
### "/version ChatControlRed" - plugin version

3.13.6

### Are you using MySQL?

No

### Are you using BungeeCord?

Yes

### Information about the issue/bug

I am the developer of Party And Friends. You added an integration for it into BungeeControl Red. The problem is that you forgot to add a softdepend for Party And Friends, which can cause your plugin to load before Party And Friends, which makes it, so the integration is not initialized correctly.

**Comment by kangarko** [comment]
Thank you, I will place "PartyAndFriends" to plugin.yml and bungee.yml of our plugins.
