### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by Smedve** [kangarko/ChatControl#2289]
### "/version ChatControlRed" - plugin version

10.16.12

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/de51cd898ab1405faf08a019da31c886

### "/chc debug" output (strongly recommended)

https://ufile.io/p8lzmir5

### Information about the issue/bug

Hi!
It produces an error in the log. Also with a new configuration folder.

**Comment by ElBananaa** [comment]
Dupe of #2288. Let's continue there

**Comment by kangarko** [comment]
Fixed asap, explanation will come in the changelog
