### ISSUE TITLE
[Feature] Edit Text

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#229]
## Context ##
So I was thinking about the whole being able to delete messages and how we could expend it into something even bigger and better.

I have 2 ideas for significant improvement:
The first was #81 
The second is `Edit`. 

## What is Edit? ##
Edit is a feature similar to delete whereby it gives a staff member (or if we want to take this further, player with their own messages), the ability to edit a message.

## How it works: ##
Upon clicking the component that says edit, the player will be prompted to retype the text to change it. **Note: It is important to give the player a clickable text component to print the message into the players active chatbox for editing**. When the player types the message, it will replace the previous message in the cache and resend the player all the messages in the same way delete currently does.

Another banger of an idea by yaboi. 

Sidenote, can we please reeopen #81 and keep this one open but instead mark them as "Following Release" or something so we can keep track of them easier.

**Comment by ElBananaa** [comment]
The idea is pretty cool, but I think it'll represent a lot of work for a feature that will cause a lot of troubles, and won't really be used. I mean, I personnally don't really see the point of editing a player message. If the player says something wrong, just removes their message and rewrite it.

It would add a unique feature to the plugin features list (which is already huge, and way bigger than any other chat plugin), but yeah, once again, I think it's more like a gadget feature.

**Comment by LogGits** [comment]
The idea being that this would be a feature coming after the release. In terms of edit, take discord for example. How often do you delete your own message and repost vs edit. This on a per player level would be a gamechanger and a headliner feature.

My idea for staff usage would be to help moderate. Deleting is a very binary approach allowing for 2 options, to delete and to not delete. Having the option "To modify" allows for endless possibilities. E.g. if i don't like what a player said and it doesn't necessarily go against any rules, I could just update their text.

**Comment by ElBananaa** [comment]
> The idea being that this would be a feature coming after the release. In terms of edit, take discord for example. How often do you delete your own message and repost vs edit. This on a per player level would be a gamechanger and a headliner feature.
> 
> My idea for staff usage would be to help moderate. Deleting is a very binary approach allowing for 2 options, to delete and to not delete. Having the option "To modify" allows for endless possibilities. E.g. if i don't like what a player said and it doesn't necessarily go against any rules, I could just update their text.

Yeah but the fact is that discord messages can be seen 1 year after, minecraft messages can't. On discord, you can't edit users messages, and there's a reason behind. You can't edit a player message because you don't like what they say. If it respect your rules, but you'd like the players to change it, you'll have to ask. It'll also cause legal problems. In some countries, this is considered as identity theft (And I'm completely serious about this). So, yeah, giving players the ability to edit their own messages can be a pretty cool feature, but it could also be a huge performance drop. But giving the abilty to edit other players messages is a really bad idea in my opinion.

**Comment by kangarko** [comment]
Thank you very much, however we've never designed the entire system to enable editing messages. So that's a great suggestion for ChatControl 11 but right now as things are I am not going to spend another 1 month rewrite the core, sorry.

**Comment by LogGits** [comment]
@ElBananaa, the performance hit by this feature would be negligible in the most uptodate version because async tings. 

> Yeah but the fact is that discord messages can be seen 1 year after, minecraft messages can't.

Player types, "Hey sam, hows it going" in public chat thinking it is private... accidentally leaking their friends name. With my edit feature they can quickly solve that problem. Why does a message have to be a year old to be editable? xDD

> It'll also cause legal problems. In some countries, this is considered as identity theft (And I'm completely serious about this)

I'd like to know more about this, can you please link me some more information. If this is actually the case, the feature would be fine with just giving the enduser the option to edit their own messages.

> Thank you very much, however we've never designed the entire system to enable editing messages. So that's a great suggestion for ChatControl 11 but right now as things are I am not going to spend another 1 month rewrite the core, sorry. @kangarko 

Im not saying we have it instantly added, i mean we should keep these open with a future feature tag so we don't lose track of them. I don't see it being added as a CR 11 feature because it's not big enough for that. This would consist of minor edits to the existing delete function (instead of deleting, simply replacing/overriding the existing text in the map) and an AsyncPlayerChatEvent listener to catch what the player wants to replace the text with (you'd need "cancel" to cancel the player from editing the text aswell). This along with #81 would be 10.X.0 updates as i'd consider them small changes that make big differences. At most an extra config value to enable/disable or set cooldowns on message editing.
