### ISSUE TITLE
Spy Feature

### ISSUE THREAD

**Issue by UrgeWine** [kangarko/ChatControl#229]
Hello,

I have a small simple feature that would have been cool. On my server, my admins have the spy permission, but I would like them not to be able to spy on my commands. It would be really cool if there could be a "chatcontrol.chat.spy.exempt" permission to make the spy feature not work on the player with that permission.

Thanks :)
-UrgeWine

**Comment by kangarko** [comment]
Are you talking about ChatControl Pro?

In that case, please use the proper issue channel.

Nevertheless, I have implemented the **chatcontrol.bypass.spy** it to the new version 7.4.14
