### ISSUE TITLE
1.19.2: Doesn´t work with DiscordSRV

### ISSUE THREAD

**Issue by TallonsCZ** [kangarko/ChatControl#2290]
### "/version ChatControlRed" - plugin version

10.16.12

### Are you using MySQL?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/e094f1288c754b83b64ca3f60e3e4a0d

### "/chc debug" output (strongly recommended)

I send it on email.

### Information about the issue/bug

A couple of days ago, the ChatControlRed plugin started crashing together with DiscordSRV, where before everything worked normally and the next day it didn't.

**Comment by kangarko** [comment]
Can you try disabling GrimAC for one round to see if that removes the error?

**Comment by kangarko** [comment]
Because I literally call just Discord's own config at that error line, I am unfortunately not sure how to work this around
![2023-02-09-11 10-256](https://user-images.githubusercontent.com/1918426/217782752-fefd68ff-bffb-4242-9b08-ba1029a186c3.png)

**Comment by TallonsCZ** [comment]
Yeah, when i disabled GrimAC its remove error.

**Comment by kangarko** [comment]
Then unfortunately it's your Anticheat's plugin's fault, I have no clue how to work this around.
