### ISSUE TITLE
1.19.2: Console chat colours for local server chat not working

### ISSUE THREAD

**Issue by addstar** [kangarko/ChatControl#2291]
### "/version ChatControlRed" - plugin version

10.16.14

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

Hello,

This issue is a continuation of #2281. Thank you for your console perms fix, that did solve the issue of the error spam :+1: but unfortunately it did not fix the console colours for player chat on the local server.

To clarify the issue, we this format for our global chat:
```
Format_Console: '{player_chat_prefix} &7<{player_suffix}{player_nick}&7> &f{message}'
```
When a player talks on the local server, the console log _on the local server_ only shows the uncoloured version of their chat (including chat colours and format colours). But when a player talks on a remote server, the received chat does show chat colour in console.

- Using 10.14.9 _with_ `Prevent_Spying: true` console colours work for local players.
- Using 10.14.9 _with_ `Prevent_Spying: false` console colours do NOT work for local players.
- Recent versions do not have the `Prevent_Spying:` option and I'm unable to get console colours working for local players.

Note: Colours in game work perfectly fine for all chat, including cross-server chat. This is only an issue with console colours.

I hope that makes sense? Happy to clarify any information :slightly_smiling_face:

**Comment by Teslicek** [comment]
I have had this problem since the start of 1.19 and it hasn't been resolved since.
Even though Kangarko tried to fix it a few times, it did not work at all.

**Comment by addstar** [comment]
> I have had this problem since the start of 1.19 and it hasn't been resolved since. Even though Kangarko tried to fix it a few times, it did not work at all.

Yeah, from my testing it's definitely a compatibility issue with newer server versions. We have a 1.17 server which runs the same version (10.16.14) and console colours work fine. But on 1.19, the same config and CCR version has no console colours for local chat (but remote server chat shows colours)

**Comment by kangarko** [comment]
I see. I will make "Alternative_Console_Sending" option in settings.yml > Channels to the next release to patch this problem as it was patched when the Prevent_Spying option was there. Shame on Paper for not supporting colors in their native way of showing commands.

**Comment by ElBananaa** [comment]
I believe that's not something on paper but on Bukkit. They basically introduced colors in the console in a way they shouldn't have been (bad practice) and it simply recently got removed or changed iirc. Paper already talked about it in one of their github issues.

**Comment by kangarko** [comment]
What is a bad practice? Using § for legacy colors? I am still using Spigot API for my plugins plus I need 1.8.8 compatibility, there is no alternative atm. I still disagree with Paper removing such fundamental features

**Comment by addstar** [comment]
> I see. I will make "Alternative_Console_Sending" option in settings.yml > Channels to the next release to patch this problem as it was patched when the Prevent_Spying option was there. Shame on Paper for not supporting colors in their native way of showing commands.

Thanks! :grinning: we'll test it out and let you know if there's any issues

**Comment by addstar** [comment]
@kangarko FYI version `10.16.15` has solved our issues and we have colours back again :tada: thanks again for the fix!
