### ISSUE TITLE
1.19.3 chc forward

### ISSUE THREAD

**Issue by Smedve** [kangarko/ChatControl#2292]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hi!
How to work /chc forward and/or /chc announce <type> server:Vadon <text>? I set server name, prefix and bunge config but doesn't work. 
https://kepkuldes.com/image/xTWWbF

**Comment by kangarko** [comment]
Do you still need help? Sorry for the delay
