### ISSUE TITLE
1.19: {chatcontrolred_player_is_spying_<mode>}	 does not work

### ISSUE THREAD

**Issue by LilShadow19** [kangarko/ChatControl#2294]
### "/version ChatControlRed" - plugin version

10.16.15

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

I am trying to make my own spy menu and i need it to say if the player is currently spying. But the variable for that is not working.
![image](https://user-images.githubusercontent.com/108494329/219973646-1d880170-042d-471e-b5b0-02623a24cdd8.png)

**Comment by ElBananaa** [comment]
Remove the `<>` and it should work.

**Comment by kangarko** [comment]
You need to replace <command> with a spying type, which you will find under Variables in our Wiki when you search for "chatcontrolred_player_is_spying_<mode>"

**Comment by LilShadow19** [comment]
![image](https://user-images.githubusercontent.com/108494329/228090188-d5c6db68-25b4-410e-b9bb-5511a7e831ea.png)
sorry for such a late reply, but it has still yet to load in

**Comment by kangarko** [comment]
Please ZIP me your /chc debug and let me know where I can find this variable.
