### ISSUE TITLE
CHC `messages` join and quit form Bungee

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#2296]
### Summary

I use Bungee as a proxy. I hope that CHC `messages` join and quit can have a new condition to refer to other Bungee. If he switches from other Bungee networks, this line of messages will not be displayed, so that I can let He cooperates with SRV and is only displayed once, not every time he switches servers, he will show joining and leaving.

Function:
1. A message will be displayed when he joins or exits the server (split), but it will not be displayed when switching the stream.
Supplement: When joining or exiting a server (split), a message will be displayed, which can be seen in other streams.

2. BungeeControl-Red supports {nick}, which displays the player's nickname from CHC's database.

3. In addition, I see that some plug-ins such as Tab can support Bungee and Velocity at the same time. Will there be such support in the future? The same framework runs on Bungee and Velocity.
Like https://github.com/NEZNAMY/TAB

Translate with GOOGLE

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

If both SRV and
The message on BungeeControl-Red, Wanjia will continue to see repeated messages in the game and on Discord when switching the diversion.
like
Player <Player> has left the server (server)
Player <Player> Switch Server (BungeeControl-Red)
The player <Player> joins the server (server)

If I go through BungeeControl-Red, there will be no messages on Discord.

BungeeControl-Red can't display nicknames and no PAPI can be used.

**Comment by kangarko** [comment]
Thanks for the suggestion.

You can completely disable join/leave messages on your Spigot servers, and only use messages on BungeeControl Red.

You will need to install DiscordSRV only on one of your networks for this feature to work properly and without duplication.

Let me know if I understood you correctly.
