### ISSUE TITLE
1.19.3: java.sql.BatchUpdateException

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#2298]
### "/version ChatControlRed" - plugin version

10.16.15

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/7526940daa2b497894e18c0c8022258d/files/d62102743a2249459fbc95c9414c8993/raw

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10806123/debug.zip)
The MariaDB Server version: 10.3.34-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04

### Information about the issue/bug

When i run `/ch list` it prints errors in the console

**Comment by kangarko** [comment]
Thanks, will be patched tonight"
