### ISSUE TITLE
1.19.3: "then replace" kicks everyone

### ISSUE THREAD

**Issue by Yertled** [kangarko/ChatControl#2299]
### "/version ChatControlRed" - plugin version

10.16.15

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://mclo.gs/fZYBL0p

### "/chc debug" output (strongly recommended)

https://ufile.io/uell9zhc

### Information about the issue/bug

I tried to use the example config to replace bad words with other words.

So when I had:
match f*ck
group swear
then replace frick

After I applied this setting, and someone said the F word, the whole server got kicked for "Chat message validation failure"

**Comment by kangarko** [comment]
Sorry for the delay, revieweing in 24 hours

**Comment by kangarko** [comment]
Hey!

I can't reproduce with your debug files: 
![a](https://i.imgur.com/m7qA9Vq.png)

But what it looks to me is that if you keep the default rule from groups.rs which blocks "fuck", then you cannot match the same word and replace it to something else like you did above. You will be fucked. You need to remove the fuck match from line 65 in global.rs if you want to match it from groups.rs as well. Apologizes for swearing.

Hope that helps! :)
