### ISSUE TITLE
Does this has cooldown messages per group?

### ISSUE THREAD

**Issue by CharlieClewer** [kangarko/ChatControl#23]
I would like to set donators without cooldown between messages and normal users with a cooldown of 3 seconds per message. Is that possible? with this plugin?

**Comment by gsand** [comment]
All you have to do is look at the settings.yml file and read the section where it deals with *just* that: https://github.com/kangarko/ChatControl/blob/master/settings.yml#L304-L320

**Comment by kangarko** [comment]
@gsand thank you for navigating him. I am closing it as it perfectly fits your need.
