### ISSUE TITLE
[Issue] Chat mention color stays

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#230]
When you mention a player, the color persists also after the player name.

![unknown-14](https://user-images.githubusercontent.com/5664135/101209220-b1611280-3673-11eb-9b1f-e70df5d87453.png)

Minecraft: 1.16.4
Bungee: true
MySQL: true

**Comment by ElBananaa** [comment]
I just tried, I have the same issue.

**Comment by kangarko** [comment]
Fixed
