### ISSUE TITLE
1.16.5: mail forward will sending all player

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#2303]
### "/version ChatControlRed" - plugin version

10.12.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/7a0758b038e04e878a78b1774d404d14

### "/chc debug" output (strongly recommended)

https://ufile.io/z3b17q7m

### Information about the issue/bug

 When I mail forward a B player before and I send a new mail to A player, B player will still recived

**Comment by kangarko** [comment]
Upgrade your ChatControl.
