### ISSUE TITLE
1.16.5: placeholderapi {server_name} displaying unicode

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#2304]
### "/version ChatControlRed" - plugin version

10.16.15

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

It will displaying unicode like this \u6D3B\u52D5\u7A7A\u5CF6, I using this placeholder other place display normal

**Comment by kangarko** [comment]
Check that your server-name in server.properties file does not contain unicode, it only supports English.
