### ISSUE TITLE
1.18.2 Couldn't pass PluginMessageEvent to velocitycontrol java.lang.IllegalArgumentException: Expected UUID, got plugin:chcred for packet null from server null

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2305]
### "/version ChatControlRed" - plugin version

3.11.2 Velocity Control and ChatControl Red 10.17.0

### Are you using MySQL?

Yes

### Error log (if applicable)

https://gist.github.com/TomLewis/c348ac5f68ebb968a145292f92aad10f

### Information about the issue/bug

I tried to update to VelocityControl 3.11.2 and ChatControl Red 10.17.0, but VelocityControl  is throwing these empty errors and anything that uses BungeeChat is now broken between servers.

Velocity shows the error message for `Nashorn library` but my shared host for proxy is using Java 17.
![Screenshot 2023-03-05 13 01 41](https://user-images.githubusercontent.com/144046/222962963-1ca45e07-b707-48e3-b636-0934172b2c57.png)

The Paper server(s) are also throwing error messages when someone tries to use anything bungee related too.
https://gist.github.com/TomLewis/fe6ae9b4b04505ebd215253d1dd8e15d

What is going on?

Velocity 2.3.1.

**Comment by kangarko** [comment]
@james090500

**Comment by kangarko** [comment]
Looks like VelocityControl needs to update the order in which it reads data, James you can have a look at the BungeeListener class in BungeeFoundation for the new order. We now place the channel name there before the UUID which wasnt there previously, hence the error.

**Comment by james090500** [comment]
@TomLewis Please test this?
https://github.com/kangarko/VelocityControl/releases/tag/3.11.3

**Comment by TomLewis** [comment]
I cant test on Prod again. Has this been tested before released? I would have to setup a local network to test.

**Comment by james090500** [comment]
Tested on my local environment and on my mc server and I see no issues currently.

**Comment by TomLewis** [comment]
Awesome, If I get some time ill try and test it by re-creating my environment locally, its all just time!

**Comment by kangarko** [comment]
Sounds good, closing. If you guys need to chat just do so below.
