### ISSUE TITLE
1.19.3: Channels no longer recognize chat prompt commands

### ISSUE THREAD

**Issue by sandwally** [kangarko/ChatControl#2306]
### "/version ChatControlRed" - plugin version

10.17.0

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

With quickshop and cmi you are prompted to type a value in chat, the value is shown in a chat channel and the plugin registers it also.
Before it never sent those chat commands to the chat.

It started with Paper 405 and same problem up to 442.
Tried with a default chatcontrol red folder, enabled channels and the problem start happening.
Changed the listener from lowest and up to highest with no change and removed item variable.

**Comment by kangarko** [comment]
Disable paper plugins feature. Looks like a problem caused by their new implementation.

**Comment by Sikatsu** [comment]
How to disable paper plugins feature?

**Comment by kangarko** [comment]
I am sorry, I have no idea. They need to provide clearer instructions and a PSA when releasing such a major mechanism change since apparently it does break a lot of plugins.
