### ISSUE TITLE
1.19.2 Multiple permissions in Messages

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#2307]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

I am currently running join.rs and quit.rs on the Velocity proxy. 

Is there a possibility to ask for multiple permissions from the sender and / or receiver? Because if I try to make "require sender perm xxx" twice in a row, then comes an error in the console. I have tried every syntax I know to see if I can figure out if this works or not. So far without success. 
"require sender script" or "require receiver script" don't work either, because it doesn't get the uuid of the player. Otherwise I could have queried the permission about it.

Do you have a tip for me if this works and if so how? Because it would actually be the simpler variant for me to solve the whole thing over the proxy, instead of over the subserver

I have smth in mind like: "require sender perm aegorin.chat && aegorin.join.vip"

**Comment by kangarko** [comment]
Hey, I believe this is best solved in your permission plugin if you use the inheritance feature and inherit a singular permission in multiple groups. I believe in keeping the plugin simple and you are the first one requesting this, I do think there is a more proper solution in your permission plugin.

Regarding the script operator, did you try calling "player.getUniqueId()"?

@james090500 can you look into the script operator not being able to resolve UUID in case sender is a player?

**Comment by Lorias-Jak** [comment]
JavaSriptExecutor class
![grafik](https://user-images.githubusercontent.com/62625225/230609026-74e5192a-6ba7-4fb6-a659-c5abcef86b35.png)

PlayerMessage abstract class
![grafik](https://user-images.githubusercontent.com/62625225/230609037-b249f7cd-a741-4137-93e4-7d63f2f19692.png)

I had a little look in the public sourcecode of vc. Generally it can't find the sender and reciever at all, because they are not passed to the JavaScriptExecutor.run() method at all, but always just null. Can't try to fix it though, as I don't know enough about gradle and accordingly can't compile it to test any changes. Wanted to have it noted once, so that it stands somewhere and does not go down after all.

Maybe it is also intentional that js does not work. But it would be a pity for the missing function.

**Comment by kangarko** [comment]
I will just ping my friend responsible for the development of VelocityControl.

@james090500 could you have a look into what the OP suggested? thanks
