### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2308]
### "/version ChatControlRed" - plugin version

10.17.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10944886/debug.zip)

### Information about the issue/bug

Hi, by some of the latest updates, you've introduced a bug to the CMI plugin. When the user edit holograms there using /cmi hologram (click on the specific name (or + to create a new one), and then write the text into the line, the message is sent into the chat as well instead of being canceled. When I disabled the ChatControlPlugin & tried to start the server without it, it worked. Could you please try to look into this issue?

I've also reported to the CMI, but discovered its issue with the CHatControlRed. https://github.com/Zrips/CMI/issues/7664

**Comment by kangarko** [comment]
Can you try Paper build 404 please? They seemed to have changed some plugin logic and then these events started happening.

**Comment by Yertled** [comment]
> Can you try Paper build 404 please? They seemed to have changed some plugin logic and then these events started happening.

We have the same issue with every plugin basically. And we figured out it was CHC sending the messages without cancelling them. I know it happened because of Paper update, but are you looking into fixing this issue from your end? :)
We love CHC

**Comment by kangarko** [comment]
We changed nothing in our code. The plugin worked for years on end until Paper came with this update. I have absolutely no idea what I need to fix and I want to keep it compatible with 1.8.8 plus Spigot, so I am awaiting for paper to give assistance at https://github.com/PaperMC/Paper/issues/8911#issuecomment-1464834688

You can ping them there and/or on discord to help them expedite the process since this is a high priority issue.

**Comment by kangarko** [comment]
Actually Paper just released a new build, can you please test on their latest one?

**Comment by Yertled** [comment]
> Actually Paper just released a new build, can you please test on their latest one?

Paper build 448 don't fix any issues regarding that.

![image](https://user-images.githubusercontent.com/12172847/224942723-b9f3b911-3073-4cee-8080-c9697a4049b0.png)

It sends the message with CHC on the server, but if I remove CHC, it's blocked.

**Comment by kangarko** [comment]
Thanks. What about build 404, does that work?

**Comment by Yertled** [comment]
> Thanks. What about build 404, does that work?

![image](https://user-images.githubusercontent.com/12172847/224945022-6f42cd9a-e024-403d-b87b-bbe55b2bc05e.png)

Build 404 works perfectly, but I don't think we can downgrade on our main SMP (We use latest PurpurMC)
I'm scared of breaking stuff

**Comment by kangarko** [comment]
No plugins should break between those Paper builds. I can't say if there were any data structure changes in the chunk storage, so I can't guarantee that downgrading will work with your map sadl.y

You can push Paper team to prioritize this issue and reply to that above ticket. We do fire "event.setCancelled(true)" like it's supposed to do, I am awaiting instructions from them on what to change.

**Comment by Sikatsu** [comment]
Is there any fix so far? We can't update to 1.19.4, as then the chat inputs will break once more..

**Comment by kangarko** [comment]
Let's continue at the Paper's issue n. 8911 please. Thanks.
