### ISSUE TITLE
1.19.3:Null Pointer Exception

### ISSUE THREAD

**Issue by malonnnn** [kangarko/ChatControl#2309]
### "/version ChatControlRed" - plugin version

10.17.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://gist.github.com/malonnnn/5feae5e227a4493c20e489103f025fa1

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/10951596/debug.zip)

### Information about the issue/bug

It appears to involve some javascript that I've never touched, so I think it's system JS

```
!-----------------------------------------------------!
Failed to parse JavaScript view condition for component!
The javascript code must return a valid true/false boolean value.
Code: '{player_channel_mode_standard}' == 'read'
Error: {
'Text' = '[Read] '
'View_Condition' = ''{player_channel_mode_standard}' == 'read''
}
!-----------------------------------------------------!
```

sadly not reproducible.

**Comment by kangarko** [comment]
I apology, this is a problem in a problem caused in the plugin. I will solve the invalid error handling so the new error it will produce , if it will, will point me to the actual problem. Just report below on the next version once it happens again, thanks.
