### ISSUE TITLE
[Issue] JSON errors

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#231]
I am having issues with plugins like ShowItem and AuctionHouse that language lines which contain JSON don't show up within the chat.

Error.log output: https://pastebin.com/Wke77cmS

Minecraft: 1.16.4 Tuinity
MySQL: true
Bungee: true

**Comment by kangarko** [comment]
Thanks, I'll silence these errors however any JSON plugin is incompatible since we already modified the chat beforehand. Even if yo change chat priorities so they come first, these plugins are incompatible since they don't edit the message in a way we can catch later.

**Comment by Sikatsu** [comment]
Wait so I can't use ShowItem properly? With chatcontrol 8 this worked fine though. The ShowItem developer said it was related to the bungee-chat api, and that the adventure text library would be a better solution.

Anything I can do to make these compatible? Since ShowItem offers more features then chatcontrol's [item]

**Comment by kangarko** [comment]
Interesting. Try the next version and play with the chat formatter priority.

We do not require nor use our BungeeChatAPI library on 1.16.4, we use the native one. You can also try Paper instead of your fork.
