### ISSUE TITLE
1.19.3: Random "crash" with loads of people typing

### ISSUE THREAD

**Issue by Yertled** [kangarko/ChatControl#2310]
### "/version ChatControlRed" - plugin version

ChatControlRed version 10.17.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://mclo.gs/J5FpOk6

### "/chc debug" output (strongly recommended)

https://ufile.io/15uc5hst

### Information about the issue/bug

60 players online, spamming chat. It made this crash and made one player type with vanilla message.
Like:
<player>: <message> instead of our format

**Comment by kangarko** [comment]
I apology, I am going to improve the error message since right now it does not tell me sufficient information. Please report the new error in case it happens again on the next version below.
