### ISSUE TITLE
problem with disconnecting players randomly

### ISSUE THREAD

**Issue by xcoolerboy** [kangarko/ChatControl#2311]
BungeeControl Red - Cross-Network Chat 3.14.0

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://pastebin.com/ssscrW3u

### Information about the issue/bug

hello there soo i have problem with chatcontrol bungee and that got kicked randomly from server even if i dont add chatcontrol red on spigot i got this error too and im sure that this is chat control bungee problem cause after i add the plugin i got this problem and when i remove it i dont have problem

**Comment by xcoolerboy** [comment]
now i notice that the bungeechat control make my players ping go high i dont know why and kick them and players will go to lobby randomly i enable the debug but i cannot understand it it huge log

**Comment by xcoolerboy** [comment]
i cannot paste the debug on pastebin because this You have exceeded the maximum size of 512 kilobytes per Paste.
but here is the debug 
[log.txt](https://github.com/kangarko/ChatControl-Red/files/10990015/log.txt)

**Comment by kangarko** [comment]
Hey! Try this build of BungeeCord to see if that error is fixed:

[BungeeControl-Red-3.14.0.zip](https://github.com/kangarko/ChatControl-Red/files/10993955/BungeeControl-Red-3.14.0.zip)

The logging feature will generate lag and slow down the plugin, I have received your log and found nothing unusual, you can now set Debug key in settings.yml back to [] for maximum performance. :)

**Comment by xcoolerboy** [comment]
hey kangarko my players getting kicked to lobby when i use bungeecontrol can you help me find out what is happening at 200 players or more they getting kicked to lobby

**Comment by xcoolerboy** [comment]
i saw another guy have same problem https://github.com/kangarko/ChatControl-Red/issues/964

**Comment by xcoolerboy** [comment]
i can send you full log but can you make this issue private? i dont want people get my bungee info

**Comment by kangarko** [comment]
Yes please you can send the error log and debug file over matej@mineacademy.org in private

**Comment by xcoolerboy** [comment]
done
