### ISSUE TITLE
1.19.3: Chat event ignores event.setCancelled(true)

### ISSUE THREAD

**Issue by Nextinka** [kangarko/ChatControl#2313]
### "/version ChatControlRed" - plugin version

10.17.3

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

This isn't really a problem of the plugin itself, it's a problem that CHC causes to other plugins. We have a ClanChat plugin that works on "AsyncPlayerChatEvent" and it works fine on the latest paper build as long as the ChatControl-Red plugin is disabled. It completely ignores the "event.setCancelled(true)" function, which is in our code, and it worked in older versions of the CHC. However, after using the new version with the latest build, it duplicates the message, so there is one message in both the clan chat and the normal chat.

![image](https://user-images.githubusercontent.com/98180136/225977737-6708f663-0d88-4035-a3a6-b79b8a43770a.png)

As you can see in the screenshot above, we can not cancel the CHC messages from the event.

Have you switched to a custom event or removed isCancelled() function or anything like that? I'll be glad if you can tell me why it's not working like it used to.

Here is the code that handles the clan chat messages:

```
@EventHandler
    public void onClanMessage(AsyncPlayerChatEvent event) {
        Player player = event.getPlayer();
        ClanUser clanUser = ClanChatPlugin.getInstance().getManager().getClanUser(player.getUniqueId());

        if (clanUser != null && clanUser.isInClan() && clanUser.isChatEnabled()) {
            event.setCancelled(true);

            String playerName;
            String badge;

            if(player.hasPermission("group.hiderank")) {
                playerName = PlaceholderAPI.setPlaceholders(player, "%luckperms_meta_name%") + player.getName();
                badge = " ";
            } else {
                playerName = PlaceholderAPI.setPlaceholders(player, "%chatcontrolred_nick%&r");
                badge = PlaceholderAPI.setPlaceholders(player, " %badge_badge%&r ");
            }

            String prefix = PlaceholderAPI.setPlaceholders(player, "%luckperms_prefix%&r");
            String playerColor = PlaceholderAPI.setPlaceholders(player, "%luckperms_meta_name%");

            String message = Config.clanChatFormat()
                    .replace("{player}", prefix + badge + playerName + playerColor + " »")
                    .replace("{pd}", player.getDisplayName())
                    .replace("{clan}", clanUser.getCurrentClan().getName())
                    .replace("{message}", event.getMessage());

            clanUser.getCurrentClan().allAction(user -> {
                if (user.isOnline()) user.bukkit().sendMessage(Util.bungeeColourise(message));
            });

            String consoleOutput = Config.consoleLoggingFormat()
                    .replace("{player}", player.getName())
                    .replace("{pd}", player.getDisplayName())
                    .replace("{clan}", clanUser.getCurrentClan().getName())
                    .replace("{message}", event.getMessage());

            Bukkit.getConsoleSender().sendMessage(Util.bungeeColourise(consoleOutput));
        }
    }
```

**Comment by kangarko** [comment]
Hi there!

It seems to be broken since Paper build 404 (please post this also to: https://github.com/PaperMC/Paper/issues/8911). We have not changed a single line of code in that class since - we listen to AsyncPlayerChatEvent and optionally, cancel the event:

![a](https://i.imgur.com/pjVfqR3.png)

Try setting Channels.Alternative_Console_Sending to false if it was on true to make the event not cancel on our end.

**Comment by Nextinka** [comment]
Hello, thanks for letting me know that it's the build's problem! I have been suspicious about it as everything worked fine on older builds of Paper.

**Comment by kangarko** [comment]
Let's continue on the Paper ticket.
