### ISSUE TITLE
1.19.3:  Nashorn Startup message on Velocity

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#2314]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Since the last VelocityControl update I have the following error message from VC in the console. If I install NashornPlus on the proxy, the plugin does not load, if I install it on the Bukkit server, then the error message from the proxy also comes. Am I understanding something wrong? 

![grafik](https://user-images.githubusercontent.com/62625225/226012333-e5d2a5c9-808e-4cdd-8983-d36f0b3c70a4.png)

![grafik](https://user-images.githubusercontent.com/62625225/226014899-d4de2c3e-aea3-47d2-855e-e407dbb969c2.png)

**Comment by kangarko** [comment]
NashornPlus is not a Velocity plugin, it should work without it. @james090500 can you please have a look?

**Comment by ElBananaa** [comment]
@Lorias-Jak 
Please make sure both VelocityControl & Chatcontrol-red are up-to-date on your server(s) and proxy.
Also, make sure to update Velocity itself.

Finally, once everything above is done, please provide environment information (server versions, proxy version, java version etc...)

**Comment by Xikser** [comment]
I have the same issue

![obraz](https://user-images.githubusercontent.com/51416960/229354986-9c362ef1-7abb-4b2d-ae51-60c697433354.png)


java version openjdk version "17.0.6" 2023-01-17
paper spigot 1.19.3
velocity 3.2.0 

VelocityControl-3.11.3-SNAPSHOT
ChatControl-Red-10.17.7

**Comment by Lorias-Jak** [comment]
> @Lorias-Jak Please make sure both VelocityControl & Chatcontrol-red are up-to-date on your server(s) and proxy. Also, make sure to update Velocity itself.
> 
> Finally, once everything above is done, please provide environment information (server versions, proxy version, java version etc...)

Im sry for not answering for a long time. 
- VelocityControl 3.11.3
- Velocity version 247
- ChatControlRed 10.07.7
- Paper 1.19.3-448

Cant update to 1.19.4

**Comment by ElBananaa** [comment]
@james090500 Would you have some free time to take a look at this, please?

**Comment by Yertled** [comment]
I am having the same startup errors on Velocity. I have 1.19.4 server too.

**Comment by kangarko** [comment]
@james090500 any update please?

**Comment by james090500** [comment]
I'm very sorry for the delay everyone I'm struggling to get some time on my PC. As a side note, the plugin will still function without nashhorn so the error can be ignored.

If something actually doesn't work please let me know in the meantime. I'll try work on this soon!

**Comment by kangarko** [comment]
@james090500 any news?

**Comment by james090500** [comment]
Technically, this isn't an issue, but this will remove the warning

https://github.com/kangarko/VelocityControl/releases/tag/3.11.4
