### ISSUE TITLE
Dont move my commented out files!

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2315]
### Summary

Ive just reloaded the plugin and seen this message:
`Warning: The following entries in motd-archive.yml are unused and were moved into plugins/ChatControlRed/unused/motd-archive.yml:`

The file I created as an archive for my old messages, has been moved automatically.
Why is this an issue?
This breaks my workflow, I keep an archive for a reason, so I can re-use things later, but whats frustrating with this, is that all my files are on github, so when I pull to the server, its then going to mess with my files and move them all around, this is going to be a complete mess with those people that use Git to mange their files (as people should be)

Now I have to spend ages trying to figure out what the hell has been done to my structure, what is the point of this?

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Stop making life harder

**Comment by kangarko** [comment]
I apology, we use this library and are already communicating with the author regarding a problem: https://github.com/tchristofferson/Config-Updater/issues/24

I'll look into this after that first thing is solved.

**Comment by TomLewis** [comment]
![Screenshot 2023-04-05 12 12 00](https://user-images.githubusercontent.com/144046/230064326-8bc7321e-d00a-4a7f-b334-c52c3342c783.png)

Visual example of normal comments being removed from files that store reference information that is re-used.
Seems to only be with plugins that use this Config-Updater framework.

**Comment by kangarko** [comment]
Yes this is coming from the config-updater library that we use. Unfortunately I don't have time to rework it but we are communicating with the author regarding one other issue and I can ask about this later.

**Comment by kangarko** [comment]
But my intention is to force-update comments such as when we edit our documentation then I want the user to see the new one (i.e. a new channel option is added)

**Comment by TomLewis** [comment]
Ah, that makes sense. Sounds like a complex problem to solve.
I wouldn't know how to go about that without resetting the files entirely! 

I could always create a reference file/template file.
Or, you could have a "notes" comment section at the top/bottom of each file that gets left there, that the user can store notes in. 
Or what if we double comment out comments? So they could be ignored as the plugin recognizes that these are our comments and to not remove them? so like;

```
## -----------------------------------------------------------------------------------------
## These are my personal notes
## please do not auto remove them plugin!
## -----------------------------------------------------------------------------------------
```


A few ways I use comments in files:

1. Re-usable messages/templates that are only displayed at certain times, like events, or sales.
2. Reference to things I use often, so I don't need to go look up the docs on it, and the ability to work faster 
3. Linking to documentation pages in the files I'm working on, for speedy getting to the doc pages
4. Notes for other staff that have access to the repo/also update it

**Comment by kangarko** [comment]
Thank you, this is out of my scope atm but I have pinged the developer of that library whether he can help us move forward. Great suggestions btw!
