### ISSUE TITLE
1.19.3: Custom command using {receiver_nick}

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2316]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I am trying to essentially replicate how the /msg works but with different commands, and I need the {receiver_nick} placeholder to work but it doesn't appear too in the format I am using.

I have a custom command rule that when typing "/wb Player123" it would show the person executing the command something like "You say wb to Player123" amd then the recepient of the command would see "Horus says wb!". It seems the logic works fine for /msg but I can't seem to understand how to make it work for my use case.

**Comment by kangarko** [comment]
Can you show me the format which you have made so far?

**Comment by HorusApl** [comment]
Parts:
  everything:
    Message: '#85b4de✉ &7{receiver_nick} &7to You → #85b4de{message}'

And here's the rule:
match ^\/wb (.*)
then warn wb
then deny

So doing /wb doesn't parse {receiver_nick} and doesn't send it to the other player. I'm sure this is my issue, just unsure how to fix it.

**Comment by kangarko** [comment]
Sorry, using receiver is only supported in private messages. It is a special variable that does not exist at rules level.
