### ISSUE TITLE
1.12 & 1.19.4: Bungeecord console errors ~

### ISSUE THREAD

**Issue by SpectreVoid** [kangarko/ChatControl#2317]
### "/version ChatControlRed" - plugin version

10.16.2 and BungeeControl-Red-3.14.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/86583c02537f4aa097487830351daac0

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11049317/debug.zip)

### Information about the issue/bug

I am using the latest waterfall, 2x lobbies on 1.12, and skyblock on 1.19.4. 

and this issue happens on all servers I have bungeecord enabled on, and not on the ones I don't have it enabled.

Not exactly sure the database connection is fine but I get this error:` [09:48:01 ERROR]: [com.zaxxer.hikari.HikariConfig] Failed to load driver class com.mysql.cj.jdbc.Driver from HikariConfig class classloader org.bukkit.plugin.java.PluginClassLoader@c44e3fa`
on server start.

**Comment by ElBananaa** [comment]
Your chatcontrol & bungeecontrolred plugins are most likely outdated. Update both plugins to the latest version and try again.

**Comment by SpectreVoid** [comment]
> Your chatcontrol & bungeecontrolred plugins are most likely outdated. Update both plugins to the latest version and try again.

All verions are the latest. Like downloaded today late. Reinstalled and the versions i used when submitting was latest on bungee and 2 version back spigot. Still same issues as previous versions.

**Comment by kangarko** [comment]
The error says you are on 10.16.2. The latest is 10.17.5.
