### ISSUE TITLE
Plugin support question

### ISSUE THREAD

**Issue by ItzRonaldMLG** [kangarko/ChatControl#2318]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hello,
I'm considering buying this plugin, but have 1* question.
Im using another plugin for the nickname and colored chat because of there features (UltraColor).
It has placeholders to display the nickname and colored chat & name.
Question: Will those placeholders work in the config file and messages on Bungeecord?
                Do i even need to use the placeholder or will this plugin pull the names out of Vault plugin?

Thank you for your time.

**Comment by kangarko** [comment]
Hey!

I unfortunately don't thinkt that you could use UltraColor's variables in our BungeeControl messages, we don't support that unless PlaceholderAPI would support this.

You can use PlaceholderAPI in case your other plugin hooks into it and then use its placeholders.

Matej

**Comment by ItzRonaldMLG** [comment]
Thank you for your fast response.
Would Placeholders work for players who are on another server or work for offline players?
And how do i get it in the plugin messages, it is using like {Receiver} & {Sender} too, can i modify this outputs aswell?

**Comment by kangarko** [comment]
They should work for players on another server because we compile the message on their server so all placeholders are ready.

Due to this, the receiver and sender is limited and can only be used in a few places, such as player messages. You can choice between {receiver} or {receiver_nick} and so on.
