### ISSUE TITLE
1.19.4: QuickShop chat messages appearing in global/discord

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2319]
### "/version ChatControlRed" - plugin version

10.17.6

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/11071270/debug.1.zip)

### Information about the issue/bug

With Quickshop when you buy an item, it has you type in the amount to buy in chat. Pre-1.19.4, the typed numbers wouldn't appear in the global channel and would just disappear. They're also now duplicating in global. I implemented a temporary solution of just:

match ^[0-9]*$
then deny

But it still sends it to discord and I can't see any rule method to prevent it from doing that. I'd prefer not to need to use regex to not send Quickshop chat messages and for it not to go to discord, as it was pre-1.19.4.

**Comment by HorusApl** [comment]
As well, I also use Quickshop which when you buy an item, it has you type in the amount to buy in chat. Pre-1.19.4, the typed numbers wouldn't appear in the global channel and would just disappear. They're also now duplicating in global.

**Comment by HorusApl** [comment]
I fixed the mcmmo party chat issue by making it it's own channel instead, but I cannot think or enable a solution to the Quickshop problem.

**Comment by kangarko** [comment]
This broke on Paper build 404, please report under their issue https://github.com/kangarko/ChatControl-Red/issues/2319
