### ISSUE TITLE
[Issue] Respond with ''/r ?'' no longer works

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#232]
When you use "/r ?" it shows the /r help output, on ChatControl 8 it would just sent the message with a question mark.

Minecraft: 1.16.4 Tuinity
MySQL: true
Bunege: true

**Comment by ElBananaa** [comment]
Yeah, looks like this is a little mistake.

**Comment by kangarko** [comment]
Thanks, fixed!
