### ISSUE TITLE
Purpur 1.19.4 CMI Interactive Commands do not function while using ChatControl on Bungee Network

### ISSUE THREAD

**Issue by VimaMT** [kangarko/ChatControl#2321]
### "/version ChatControlRed" - plugin version

10.17.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11093365/debug.zip)

### Information about the issue/bug

See this link to an issue on CMI:  https://github.com/Zrips/CMI/issues/7664

It is still applicable.

**Comment by VimaMT** [comment]
I am not sure this is a ChatControl issue now. I totally disabled ChatControl throughout my network, and I tried to create CMI holograms again. The message we see in the screenshot comes from CMILib.
![2023-03-28_16 52 27](https://user-images.githubusercontent.com/46653361/228375515-3486cd65-2d3d-4063-8be5-d3d37d43f4e9.png)

**Comment by ElBananaa** [comment]
Hey,
If the issue persists without chatcontrol, why did you report this here? It clearly means this isn't something on our end in this case

**Comment by VimaMT** [comment]
I did not try it without ChatControl until after I had already reported it. And I reported it here because I first fond an issue on Zrips' github that tied the two of them together. If you know how to close this ticket, please do so.
