### ISSUE TITLE
Purpur 1.19.3 | "Player is not online on this server"

### ISSUE THREAD

**Issue by Truongvv10** [kangarko/ChatControl#2322]
### "/version ChatControlRed" - plugin version

10.17.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/a4b9c232c5834f2283164a4270312b53

### "/chc debug" output (strongly recommended)

[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/11102151/debug.1.zip)

### Information about the issue/bug

I can /msg some players but other players I can't. It sais that the player isn't online while they are right in front of me.

- I did, I made database on my bungee and connected it
- Enabled sql in settings.yml
- and changed my server.properties to have the same name as my bungee settings

**Comment by BlueFyreMatt** [comment]
I'm also getting this error on 10.17.7 on Purpur 1.19.2 on a Geyser standalone server with Floodgate enabled (AKA not bungee/velocity) Some players are able to message eachother, others are not. Will update if I find any further information that could be relevant.

**Comment by kangarko** [comment]
@BlueFyreMatt I don't know how Floodgate works but right now we only support BungeeCord/Waterfall and Velocity.  That probably explains why "some" players are found while others don't, perhaps only Java players are found. Are you using any of that @Truongvv10 ?

**Comment by ttc111** [comment]
I also have this issue where I can't message a player who is right in front of me and the system says the player is offline. Some players are affected while others are not.

I'm using the following versions:

paper ChatControl-Red-10.17.7
waterfall BungeeControl-Red-3.14.2.jar
This issue did not occur when I was using the following versions:

ChatControl-Red-10.17.5
BungeeControl-Red-3.14.1

**Comment by FITFC** [comment]
I'm having this same problem on 1.19.4 with Purpur, only I don't use Waterfall or Bunge... it's a simple survival server...

ChatControl-Red 10.17.7
git-Purpur-1949 (MC: 1.19.4)
LuckyPerms v5.4.69
EssentialsX versão: 2.19.7

**Comment by Truongvv10** [comment]
> @BlueFyreMatt I don't know how Floodgate works but right now we only support BungeeCord/Waterfall and Velocity. That probably explains why "some" players are found while others don't, perhaps only Java players are found. Are you using any of that @Truongvv10 ?

I don't use floodgate at all. Here's the list of plugins I use but I don't think any of them would collide with chatcontrol red.
![image](https://user-images.githubusercontent.com/67742370/229295698-16479f24-c2ce-4d17-a8ec-5a90614e7bf7.png)

**Comment by BlueFyreMatt** [comment]
> 

I've cross referenced a list of bedrock players to java players and had them test messaging both java and bedrock players with the same issues still occurring (random players being listed as "offline") so I don't think its Floodgate. I've also checked to see if its a versioning issue with viaversion and players on all versions are experiencing problems messaging both players on their version and players on different versions. I do have a dev server setup where I can open it up to say 20 players to test if its a CHC issue with this version (10.17.7) or not if you'd like?

**Comment by Lorias-Jak** [comment]
Same Issue with:
- paper 1.19.3-448
- Velocity 3.2.0-247
- ChatControlRed 10.17.7
- VelocityControl 3.11.3

**Comment by Truongvv10** [comment]
@BlueFyreMatt it seems like people that only have lowercase letters can be messaged. If you have an uppercase in your name, they can't be messaged

**Comment by BlueFyreMatt** [comment]
> it seems like people that only have lowercase letters can be messaged. If you have an uppercase in your name, they can't be messaged

I can confirm this as the issue. Have replicated on my end too, any users with capital letters are shown as being offline, whilst users with lowercase, numbers or punctuation within their names can all recieve messages without issue. See image for an example 
![image](https://user-images.githubusercontent.com/74265327/229645319-99e30e66-652e-42e4-855b-26353e128ba0.png)

**Comment by ElBananaa** [comment]
Can you guys please DM Bananaa#1471 on discord? I'll provide you a test version with a potential fix there.

**Comment by ElBananaa** [comment]
@kangarko Please review https://github.com/kangarko/ChatControl-Red-Src/pull/71 for a fix

**Comment by BlueFyreMatt** [comment]
> Can you guys please DM Bananaa#1471 on discord? I'll provide you a test version with a potential fix there.

Attempted to drop you a friend request yesterday as your DMs are closed. Discord is BlueFyreMatt#3460

**Comment by BlueFyreMatt** [comment]
> Can you guys please DM Bananaa#1471 on discord? I'll provide you a test version with a potential fix there.

@ElBananaa Just checking in, do you still need people to test this for you? I'm more than happy to do so-

**Comment by kangarko** [comment]
I believe that was fixed in [10.17.8](https://builtbybit.com/resources/chatcontrol-red-format-filter-chat.18217/update/97659/)

**Comment by ElBananaa** [comment]
> > Can you guys please DM Bananaa#1471 on discord? I'll provide you a test version with a potential fix there.
> 
> @ElBananaa Just checking in, do you still need people to test this for you? I'm more than happy to do so-

As kangarko said, latest release should include a patch. Sorry for not answering, i missed your previous message ^^
