### ISSUE TITLE
1.19.4: Channel List not showing players

### ISSUE THREAD

**Issue by Michael-A-Sloan** [kangarko/ChatControl#2323]
### "/version ChatControlRed" - plugin version

10.17.7

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11115189/debug.zip)

### Information about the issue/bug

When running /ch list 

the issue occurs where it doesn't list players in the channels at all.

**Comment by Michael-A-Sloan** [comment]
<img width="289" alt="image" src="https://user-images.githubusercontent.com/89812914/228940207-821dfd0d-2226-44d2-b730-aa2f3b3727c9.png">

**Comment by kangarko** [comment]
Have you waited until the database has loaded and then tried running the command again? If your mysql is located on a different host or your internet connection has a high ping then it can take a few seconds after joining the game.

**Comment by Michael-A-Sloan** [comment]
Nothing ever loaded sadly that's why I made this issue. All data is  in the default area on the machine from when your plug-in set it up.

**Comment by Truongvv10** [comment]
People that only have lowercase letters in their name can be messaged for some reason @kangarko

**Comment by ElBananaa** [comment]
Hey, sorry for the delay.
Could you please try to use a MySQL database to see if this helps with your issue?

Let's keep infos about the lowercase name issue in #2322

**Comment by kangarko** [comment]
I apology for delays, I was out for holidays. Going to review at last on Monday.

**Comment by kangarko** [comment]
I will sit down and release a fix by tonight, thanks @ElBananaa
