### ISSUE TITLE
1.16.5: Packet.rs require perm doesn't work. Need help configuring.

### ISSUE THREAD

**Issue by F1reP0wer12345** [kangarko/ChatControl#2324]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I have a minigame server with two plugins. One plugin which, on command, toggles player permssions to change my language. ChatControl's Packets.rs file handles the tranlations. Most plugins are in english. I speak dutch and english. My goal is to make a server with with "packets" in english and dutch. When I type /lang english, the first plugin will set chatcontrol.rule.EN to true and chatcontrol.rule.NL to false using -chatcontrol.rule.NL. When I type /lang dutch the first plugin will set chatcontrol.rule.NL to true and chatcontrol.rule.EN to false. Everything works fine when packets only need to be changed if my language is indeed dutch. The problem occurs when I need to change both the output in english and dutch. Example of my packets.rs:
This part works:
```
match You can not leave the arena borders!
require perm chatcontrol.rule.NL
then replace &cJe kunt niet buiten de arena gaan!
dont verbose

match You are outside the arena borders!
require perm chatcontrol.rule.NL
then replace &cJe bent buiten de arena!
dont verbose

match Congratulations! you have won the game!
require perm chatcontrol.rule.NL
then replace &a&lGefeliciteerd! &6Je hebt gewonnen!
dont verbose
```
This part does not:
```
match You teleported to world 'LuckyLobby'\!
require perm chatcontrol.rule.EN
then replace You teleported to the LuckyIslands lobby!
dont verbose

match You teleported to world 'world'\!
require perm chatcontrol.rule.EN
then replace You teleported to the Hub!
dont verbose

match You teleported to world 'LuckyLobby'\!
require perm chatcontrol.rule.NL
then replace Je bent in de LuckyIslands lobby terecht gekomen!
dont verbose

match You teleported to world 'world'\!
require perm chatcontrol.rule.NL
then replace Je bent in de Hub terecht gekomen!
dont verbose
```
As of now, the above consistently give me english results. No matter the permssions. I've tried many things, but maybe one of you can show me how it should look?
I've tried `ignore perm chatcontrol.rule.NL` instead of `require perm chatcontrol.rule.EN`
I've tried `require perm -chatcontrol.rule.NL` instead of `require perm chatcontrol.rule.EN`
I can't think of anything else. If you can help that would be great! Thanks in advance!

**Comment by kangarko** [comment]
Some messages are client-rendered and we can't catch them. Try to find out if that message is compiled on the client by removing all other messages from packet.rs, only keeping that one that doesn't work, removing "require perm" operator and just keeping "match" and "then replace" and see if it starts working.

**Comment by F1reP0wer12345** [comment]
I probably should've mentioned that I have used the rules one by one without the require perm option. This does work. I just don't know why it doesn't work with two different `require perm` options. Maybe I'm just doing it wrong? What I want to accomplish is, if they have perm `chatcontrol.rule.EN` then translate it to one thing. If they have perm `chatcontrol.rule.EN`, then translate it to something else.

**Comment by ElBananaa** [comment]
> I probably should've mentioned that I have used the rules one by one without the require perm option. This does work. I just don't know why it doesn't work with two different `require perm` options. Maybe I'm just doing it wrong? What I want to accomplish is, if they have perm `chatcontrol.rule.EN` then translate it to one thing. If they have perm `chatcontrol.rule.EN`, then translate it to something else.

Could you please try to add a backslash before each `'`?
Who knows, this may hopefully be as simple as that ^^

**Comment by F1reP0wer12345** [comment]
> Could you please try to add a backslash before each `'`?

The default packet.rs file has the following rule:
`match ^I'm sorry, but you do not have permission to perform this.*|^You do not have access to that command.`
So i didn't think it was necessary to a backslash. I will try to see if it makes any difference. I also have other rules containing a `'`. I also figured out that some of my rules just ignore the `require perm` option completely. This one for instance:
```
match >> Wins/Losses: (.*)/(.*)
require perm chatcontrol.rule.NL
then replace &9>> &cOverwinningen/Nederlagen: &6$1/$2
dont verbose
```
Could it be that permissions can't contain capitalized letters? I didn't try that yet, but will do so soon.

**Comment by kangarko** [comment]
@ElBananaa

**Comment by ElBananaa** [comment]
@kangarko Alright, so Greazi#9999 and TehZombiJesus#0001 apparently played with chc, and found out this only happens on 1.19 with newer versions of ProtocolLib. Switching back to 1.18.2 and and older build of ProtocolLib released before they added 1.19 support fixed the issues. So, as they also noticed, this has most likely something to do with the whole chat reporting/preview system added in 1.19.

**Comment by F1reP0wer12345** [comment]
This could very well be the case. Thanks for looking into it. I will try to downgrade my protocolLib to before the 1.19 support update. I will report back if it works for me too.

**Comment by ElBananaa** [comment]
> This could very well be the case. Thanks for looking into it. I will try to downgrade my protocolLib to before the 1.19 support update. I will report back if it works for me too.

This should work as a tempfix (once again, all credits goes to Greazi#9999 and TehZombiJesus#0001 on discord for having a deeper look into it.

@kangarko Could you please take a look at this, I didn't really follow the changes made in ProtocolLib recently and I don't have enough time to look into this right now

**Comment by F1reP0wer12345** [comment]
It doesn't seem to work.. I've been using 4.8.0 the entire time (not the dev builds), and even downgraded to 4.7.0. Still doesn't change. By the way, i wasn't sure if i said this in the post above, but my server is using 1.16.5, and this has always been the case. I honestly didn't really consider upgrading, because of the hassle that came with chat reporting. I can try 4.6.0, but I don't think it will change much.

**Comment by kangarko** [comment]
<img width="1051" alt="Screenshot 2023-04-12 at 18 53 19" src="https://user-images.githubusercontent.com/1918426/231528014-933aeca1-3ba6-4eac-a540-37a0db57e94b.png">
Confirmed, paper broke again due to library changes.

Afaik there is no easy way to set the final adventure field and setting its content by calling the content() method does not work for me, I will have to contact their support and wait for answer until now.

**Comment by kangarko** [comment]
Lets follow at https://github.com/KyoriPowered/adventure/issues/901
