### ISSUE TITLE
Placeholder expansion

### ISSUE THREAD

**Issue by ItzRonaldMLG** [kangarko/ChatControl#2325]
### Summary

Hello,
Is it possible to pull the toggle status from PlaceholderAPI? There is only one for the channel at the moment.
I would like to see other toggle status too so i can integrate it in my server menu with other plugins.
Like this status: 
%player_toggle_<type>% Type is: announcement, chat, join, list, mail, me, pm, quit, soundnotify & timed.
Especially the chat and pm, i would like to remember the player at join that they toggeled the chat and pms.
Als like i said, to make an interface to control everything in 1 GUI.

Another one that might be useful fore some users:
Receive {player_nick} data: %NicknamePlugin% also in the use for pm receivers and so on.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

More possibilities for use in other plugins.

**Comment by kangarko** [comment]
I do recommend hooking into our API by writing a plugin if you want GUI.  Due to time constrains I am at present unable to implement this as a new variable, I apology.

**Comment by ItzRonaldMLG** [comment]
Not even a true/false value? I cant code so otherwise it wont happen sadly.
With true/false i could make it already :)

Still thank you for your hard work.

**Comment by kangarko** [comment]
You were right, that one I could implement it was quite simple. Done!

<img width="587" alt="Screenshot 2023-04-09 at 14 11 29" src="https://user-images.githubusercontent.com/1918426/230771907-32949214-8ed3-451d-8152-966de19935f0.png">

Usage:
`{chatcontrolred_is_ignoring_<mode>} - Returns "true" or "false" if the player is ignoring the given mode via /toggle command. Modes available: mail, announcement, me, pm, chat, soundnotify.`

**Comment by ItzRonaldMLG** [comment]
Thank you so much! You are the best! :D
Will be in the next update i imagine or already in the dev version?

**Comment by kangarko** [comment]
It will come in 24-48 hours, I am on Easter holidays so need to sit down a bit more
