### ISSUE TITLE
Easy channel switch

### ISSUE THREAD

**Issue by ItzRonaldMLG** [kangarko/ChatControl#2326]
### Summary

1. I was wondering if i can add a button behind the Your channels: ''(read/write)'' to switch to read mode.
    At the moment it seems you need to type a command or leave and join the channel.
2. Can i change/disable the channel join message per channel?

Example:
- standard (write)   [✎]    (You are already in this one)
- helpop (read)    [switch]
- global (read)    [switch]
- staffchat (read)    [switch]

Or maybe even another click event (change write/read) on the message and an button in front to leave?
Or just the 2 click events on the name the leave and on the status message the click event to change your write channel?

Example:
- standard (write)    (ofcourse you have no permission to leave this one.)
- "[X]" helpop (read)
- "[X]" global (read)
- "[X]" staffchat (read)

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

More player friendly interface for Channel changes

**Comment by ElBananaa** [comment]
Hey,

- When you type `/ch list` you should be able to click on the channel name to join it, or on the mode written on the right side to switch between read/write mode.

- You can disable every single message. Simply find them in your localization file: `plugins/ChatControlRed/localization/messages_en.yml for the english file` then replace the matching string with `none` (look at the highlighted line in the screenshots below for an example).


**BEFORE**
![image](https://user-images.githubusercontent.com/53318613/229881339-53cb2881-33d5-4aa1-bcd2-55c1c547097d.png)


**AFTER**
![image](https://user-images.githubusercontent.com/53318613/229881558-b039b047-8c57-4dac-aea4-245d462f4584.png)

**Comment by ItzRonaldMLG** [comment]
I know about the command and the ''none'' message.
Its just a improvement for usability for the players to do it with clicking on a message.

I would like to only disable the join message for the standard chat but not for all other chats, otherwise you will get spammed by players connecting to the standard channel again.
But it is helpful in channels like: Help, staff and parties.

**Comment by ElBananaa** [comment]
You can already click on a chat message to either join/leave a channel, and even switch between write & read modes.
Staff members with the right permission can even mute a channel by clicking on a text in the chat when this feature is enabled, like the below screen shows. (The screen was taken from another issue, but it clearly shows the `Leave` and `Mute` buttons.

![image](https://user-images.githubusercontent.com/53318613/230144199-3ae8ca55-4720-416d-aafd-806eb62e64aa.png)


If you are talking about a feature like [TabChannels](https://dev.bukkit.org/projects/tabchannels) (see the screenshot below), then I believe it's already been suggested a few times but kangarko denied it since not enough people asked for a such feature and he didn't have enough time to work on it (@kangarko correct me if i'm wrong).
![jTbYVfB](https://user-images.githubusercontent.com/53318613/230145678-7579651e-c487-4212-bbcd-66d01ac454e2.gif)

**Comment by ItzRonaldMLG** [comment]
The first screenshot  is exactly what i ment.
But for normal players and a button to switch to read on a channel.
But i dont get that message, i get this with / channels.
https://i.imgur.com/8Hv7f2q.png

**Comment by kangarko** [comment]
Thanks, I will review your conversation on Monday after holidays and see what I have time for.

**Comment by kangarko** [comment]
Done, I have improved the design!

![a](https://i.imgur.com/sZ36kst.png)

**Comment by ItzRonaldMLG** [comment]
Looks verry nice! But xD
I cant seem to join the channels once i left them, i have to manually join them with a command.
Also something strange, i cant seem to switch to write once i changed my write channel to something else.
I tried multiple things and even reset the messages file, i dont really understand why i cant rejoin and change the mode.

It is like there is a permission missing.
With OP everything works. but i have the permissions:
chatcontrol.channel.join.standard.write
chatcontrol.channel.join.standard.read
chatcontrol.channel.leave.standard

**Comment by kangarko** [comment]
What message do you get when you click a channel you have left and it does not join it?

**Comment by ItzRonaldMLG** [comment]
When i hover over the channels, the only thing i can do is leave the channel and not join or change the mode.
If you are in multiple channels you still cant change to write without clicking on the leave button, but thats not what you ment to do (leaving) you just wanted to message the other chat.
Also, sometimes it changes to write mode and sometimes it will leave you directly.
there is no error if you try to click on it and no hover message.

**Comment by kangarko** [comment]
Check if you have both join and leave permissions for the channel you want to switch to. I cannot reproduce this unfortunately.

**Comment by kangarko** [comment]
@ItzRonaldMLG I was thinking of this: you need to retype /ch again after clicking the channel names for it to update:

![a](https://i.imgur.com/skSdZOB.png)

Are you doing this or do you want me to resend the channel message after you click the names?

**Comment by ItzRonaldMLG** [comment]
I am aware of that yes. I tested for 2 hours with all permissions.
Even deleted all files and the MySQL data pool & data.db

chatcontrol.channel.join.admin.write
chatcontrol.channel.join.admin.read
chatcontrol.channel.join.standard.write
chatcontrol.channel.join.standard.read

Even added this (was not expected to fix with this):

chatcontrol.chat.write
chatcontrol.chat.read
chatcontrol.channel.join
chatcontrol.channel.leave
chatcontrol.channel.leave.others
chatcontrol.channel.send.admin
chatcontrol.channel.send.standard
chatcontrol.command.info
chatcontrol.command.script
chatcontrol.command.rule
chatcontrol.bypass.spamkick

None of those permission fixed the problem, but if i have OP or chatcontrol.* it does work.
Are you sure you didnt add another permission to use this, none of the normal permissions work..?
Its still only the join and mode switch that wont show and wont execute in this /channel menu

**Comment by ElBananaa** [comment]
I managed to reproduce @ItzRonaldMLG's issue too on my end.
@kangarko seems like you forgot to replace the `{mode}` part in the permission check, so in order to get this working for regular players, they must have a permission like `chatcontrol.channel.join.standard.{mode}` instead of `chatcontrol.channel.join.standard.write`.

@ItzRonaldMLG I have a version that should fix this. If you wanna give it a shot on your end, dm me on discord: Bananaa#1471

**Comment by kangarko** [comment]
Thanks, gonna shoot this to the official release in 1h

**Comment by ItzRonaldMLG** [comment]
It seems to work now, Thank you!

**Comment by ItzRonaldMLG** [comment]
Sorry for the late reaction, i was gone for a day.
Thank you for solving this mystery.
