### ISSUE TITLE
Manually broadcast timed message to server/yourself 

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2327]
### Summary

Can I output timed messages via command?

`/chc message list timed` just lists their delay and type as a group, not the actual messages. These could be click to display that group, directly in chat.

Even better if there is a way to display based on ID/name of the timed message.

- Primarily for testing/making sure a format works and is displayed properly, timed messages you have to just sit and wait for to test they are displaying as you expect.

![2023-04-05_11 45 08](https://user-images.githubusercontent.com/144046/230058616-79374475-d348-4d44-b239-d113fb598506.png)

Secondly, have a command that allows me to use the annoucement to use a pre-made message from timed, or alternativly, have another file in "messages" folder for pre-saved announcements that can use formatting. 

We have a lot of manually fired announcements in-game that need to be written each time staff do something, it would be great to use just `/chc announce chatsaved <saved message>` 

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Keep struggling to test.

**Comment by TheIntolerant** [comment]
Regarding your first issue/question if you type ``/chc message info timed <group>``
You should see the actual timed messages

**Comment by TomLewis** [comment]
> Regarding your first issue/question if you type `/chc message info timed <group>` You should see the actual timed messages

I do not, I just get this;

![2023-04-06_23 08 14](https://user-images.githubusercontent.com/144046/230502798-5635e566-0aa9-41e6-aa58-7f32aadadfc7.png)

**Comment by TheIntolerant** [comment]
My bad, the command you did was correct but you need to include the group
So ``/chc message list timed <group>``

**Comment by kangarko** [comment]
Thanks to @TheIntolerant for handling this! let us know if you need more help.

**Comment by TomLewis** [comment]
Any chance for the manual broadcasting of timed messages?

**Comment by kangarko** [comment]
Added!

/chc message run timed GROUPNAME

**Comment by TomLewis** [comment]
Fantastic thanks! does it need a message ID/name?

**Comment by kangarko** [comment]
It needs the "group id" which you defined in the .rs file, i.e.

```
group xmas
message:
- blablah
```

Then you gonna call "/chc message run timed xmas"
