### ISSUE TITLE
1.19.2: Port to Fabric? 

### ISSUE THREAD

**Issue by KhaozFrost** [kangarko/ChatControl#2331]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I was wondering if you had plans on porting ccr to fabric? 
If so what would the cost of the project cost as I would like to hire for this project.

**Comment by kangarko** [comment]
I have very little time for this right now, I am sorry.

I'd love to help, and if you can refer to a great developer I am happy to give them source access so they can maintain a fork on their own.

**Comment by FawksX** [comment]
I may be willing to port this sometime in the future

**Comment by kangarko** [comment]
Cool! Send me an email (matej@mineacademy.org), you will sign a simple NDA not to distribute ChatControl Red Bukkit and you can use its source for the port anyhow you like.
