### ISSUE TITLE
Placeholders in join/leave channel message

### ISSUE THREAD

**Issue by ItzRonaldMLG** [kangarko/ChatControl#2332]
### "/version ChatControlRed" - plugin version

10.17.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

(Still trying to get nicknames from other plugins)
It seems you can use Placeholders in the join/leave message from the channels feature.
https://i.imgur.com/Y3lr7iU.png
I tried to use %ucolor_nickname% first and it didnt work.
Then i thought it couldnt get the name because it wouldnt execute as the player, but this one also doesnt work.

I tried this one too with the variables feature, but is doesnt seem to change anyway.
https://pastebin.com/cXXKaTcg

### Information about the issue/bug

Use placeholders in (i assume) the messages_en.yml (aswell buildin and PlaceholderAPI placeholders)

**Comment by kangarko** [comment]
What do you mean by "I tried this one too with the variables feature, but is doesnt seem to change anyway."? 

Does it work i.e. it gets replaced?

**Comment by ItzRonaldMLG** [comment]
If i use the in variable created variable it will give ''{ucolor_nickname}'' and not the playername.
https://i.imgur.com/qVdjDbo.png

**Comment by ElBananaa** [comment]
Please try to reproduce the issue using `/papi parse yourName %placeholder%` (to ensure the placeholder actually works with placeholderapi) then send us a screenshot of the command output.

Make sure the `%ucolor_nickname%` works properly using the command above (and use the placeholder with %%).

**Comment by ItzRonaldMLG** [comment]
the placeholder does output correctly.
https://i.imgur.com/47lBBUq.png

**Comment by kangarko** [comment]
Unfortunately these messages wont support PlaceholderAPI because of offline and Bungee support, we can't guarantee there will be a Player from which we can replace the variables.

I could add this but you will end up seeing %variable% placeholers for offline/bungee players breaking it.
