### ISSUE TITLE
Minecraft 1.19.3: ChatControl incorrectly shows PlaceholderAPI placeholder

### ISSUE THREAD

**Issue by MinecraftAdmin** [kangarko/ChatControl#2336]
### "/version ChatControlRed" - plugin version

10.18.0

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

debug.zip emailed to [support@mineacademy.org](mailto:support@mineacademy.org)
Subject: `debug.zip - Github: MinecraftAdmin`

### Information about the issue/bug

ChatControl incorrectly shows PlaceholderAPI placeholder

Output for placeholder using PlaceholderAPI `/papi parse me %ezcolors_color_msg_testing 123%`:
![image](https://user-images.githubusercontent.com/1650123/231939170-c9a85764-e47e-4e6a-8fde-07b8736d5824.png)

Output for placeholder using ChatControlRed:
![image](https://user-images.githubusercontent.com/1650123/231939261-2964c569-5e86-45df-9e7b-45996f45a250.png)

Chat setting:
![image](https://user-images.githubusercontent.com/1650123/231939343-4b6995dc-31a6-47c7-8fed-2533e0270aab.png)

**Comment by kangarko** [comment]
I don't think we support placeholders in placeholders that way at this moment. I can have a look into this when I have more time.
