### ISSUE TITLE
1.19.4: Delete Messages broken

### ISSUE THREAD

**Issue by TehZombiJesus** [kangarko/ChatControl#2337]
### "/version ChatControlRed" - plugin version

10.18.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11234487/debug.zip)

### Information about the issue/bug

As you can see in this GIF after trying to delete messages, it keeps adding more messages or completely removes all of them.
@ElBananaa has also tested and confirmed this issue [here](https://discord.com/channels/360404674219737100/755325303689052200/1096437039072809081).

![qgKpOtzm3b](https://user-images.githubusercontent.com/81379135/232089657-7a1d97bc-4fe5-41a0-8fa5-0c2008666683.gif)

**Comment by kangarko** [comment]
Thanks, was caused by https://github.com/kangarko/Foundation/commit/8374209e590ce25a10888a861d046ecd7c6cc83c, going to reverse in 1h
