### ISSUE TITLE
1.19.4: Can't figure out correct priority on server

### ISSUE THREAD

**Issue by devJordanOfficial** [kangarko/ChatControl#2340]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello, I can't seem to figure out the correct listener priority in order to stop messages from sending when other plugins ask for a prompt via chat.

The plugin I am primarily testing this with is called [Player Warps](https://www.spigotmc.org/resources/⭐-player-warps-⭐-➢-let-your-players-set-warps-1-7-1-19.66692/). I have a sizeable amount of plugins on my server, so I took this plugin as well as ChatControl over to a private server in order to make restarting faster. It seemed to work on "HIGHEST" priority. So I took this value back over to my main server and tried it again with no success this time.

I decided to bite the bullet and try every listener priority, and none of them worked. The following was the same result after trying all priorities.
![image](https://user-images.githubusercontent.com/94763582/232906654-57ab2534-afb8-4f7e-9ab0-5ec8cca1fc32.png)

**Comment by kangarko** [comment]
Can you review https://github.com/PaperMC/Paper/issues/8911 and let me know if this is the same issue? It should have been fixed by Paper

**Comment by devJordanOfficial** [comment]
This was in fact the issue, thank you for your response!

**Comment by kangarko** [comment]
What did you do to fix it btw? So that I can inform our other users as well, thanks.

**Comment by devJordanOfficial** [comment]
> What did you do to fix it btw? So that I can inform our other users as well, thanks.

Absolutely; The plugin I found that was being the most difficult with this issue is called PlayerWarps, other plugins seemed to work on more listener priorities after I updated Paper to the latest build version.

To get ChatControl working with PlayerWarps specifically I set the listener priority to MONITOR

**Comment by kangarko** [comment]
Thanks!
