### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by ZzSitas** [kangarko/ChatControl#2343]
### "/version ChatControlRed" - plugin version

latest

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[message.txt](https://github.com/kangarko/ChatControl-Red/files/11302171/message.txt)

### Information about the issue/bug

I am not sure why i get that error

**Comment by ZzSitas** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11302475/debug.zip)

i got the files from debug

**Comment by kangarko** [comment]
Thanks, going to fix tonight.
