### ISSUE TITLE
1.19.3 Purpur - Problem with SuperiorSkyblock2 chat

### ISSUE THREAD

**Issue by Chrqmated** [kangarko/ChatControl#2347]
### "/version ChatControlRed" - plugin version

10.16.14

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

No need on this situation

### Information about the issue/bug

On the SuperiorSkyblock2 plugin, there is an island chat system to talk between island members. But with Chat Control Red, when they talk on their island chat the message is sent on the island chat but also in the normal chat. This is a relatively important bug and since my server is open, I would like to solve it very quickly. I can pay for a quick patch.

**Comment by airdropped** [comment]
I would also like to have an integration for SuperiorSkyblock2. Somewhat similar to BentoBox I would assume.
When players have island chat enabled, it would put them in a "Party Channel" for island chat. Like towny 😄

**Comment by kangarko** [comment]
Thanks! I am really busy atm but if @ElBananaa would be able to help with adding this API hook then you can donate to him instead. Nathan let me know what you think please?

**Comment by ElBananaa** [comment]
I am working from 7am to 5pm pretty much every day, so I unfortunately don't really have the time nor the motivation to work on this right now (I think you'll understand that I don't really want to do more work, after work ^^)

**Comment by kangarko** [comment]
That's long working hours but I am happy you have a job! Okay I completely understand, going to put this on my backburner.
