### ISSUE TITLE
1.18.2: Help with a chat.rs rule

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl#2348]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

I am looking for a way if a user puts two "))" brackets at the end of their message it will send their message to another channel if I could have some support with that that'd be amazing 

I have tried figuring it out but nothing I have tried worked if I could get the rule for that'd be amazing! Thank you in advance!

**Comment by kangarko** [comment]
Hey!

How about a simple rule like this (replace admin with your channel):

```
match \)\)$
ignore channel admin
then command /ch send admin {message}
then deny

```

**Comment by Ash10744** [comment]
Hey tried this with the above rule and it didn't seem to work here is what I did:
```
match \)\)$
ignore channel local
then command /ch send local {message}
then deny
```

![image](https://user-images.githubusercontent.com/16086663/236057465-f893451b-ec79-4f58-a5e6-9c9c3ad04a27.png)

It doesn't change the message to the local channel when I do it.

**Comment by kangarko** [comment]
Oh I am sorry, try something like this:

```
match (.*)(\)\))$
ignore channel local
then command /ch send local $0
then deny
```

Try replacing $0 with $1 if the 0 does not work

**Comment by Ash10744** [comment]
I am so sorry for bringing this back up again I have totally forgotten about it since, but the actual rule still isn't working.

    
match (.*)(\)\))$
ignore channel Local
then command /ch send Local $1
then deny

Here is my rules config for further help the channel is Called "Local" and its still not working

https://mcpaste.io/cd4f2f8a43a1b859

**Comment by kangarko** [comment]
You have "then command /ch send Local $1", I have $0, try changing that to $0

**Comment by Ash10744** [comment]
Yeah despite being on the latest version and trying this it still doesnt seem to work its really weird?
![image](https://github.com/kangarko/ChatControl-Red/assets/16086663/cbaaed5e-6f3a-44f6-8875-bcef1f10ef6d)

**Comment by Ash10744** [comment]
Even with your edit you made

**Comment by kangarko** [comment]
I made this adjustment:
````
match (.*)(\)\))$
ignore channel admin
then command /ch send admin $1
then deny
````

Now it works properly, it even removes the )) at the end of the message when it is sent to your other channel. Replace admin with your channel name.
<img width="299" alt="Screenshot 2023-07-28 at 11 38 13" src="https://github.com/kangarko/ChatControl-Red/assets/1918426/0fa733b7-0ac2-4ab5-b66d-8fb1c5b5b32f">

**Comment by Ash10744** [comment]
So I have again tried with your changes updated the plugin could there be a config option that is stopping this? It's really weird?

The default "!" works but this one doesn't.

![image](https://github.com/kangarko/ChatControl-Red/assets/16086663/48c9566a-6ad0-4b33-aea0-295d2a1e8eef)

```
# -----------------------------------------------------------------------------------------------
# Forwarding messages to other channels.
# -----------------------------------------------------------------------------------------------

# Send messages starting with "!" to global channel
match ^(\!)(.*)
then command channel send standard $2
then deny
dont verbose	

match (.*)(\)\))$
ignore channel Local
then command /ch send Local $1
then deny
```

Sorry to keep bringing this up but I just can't seem to figure out what might be causing this?

**Comment by kangarko** [comment]
Are you testing on an OP account? Can you test on an user one? Maybe you have rules bypass permission

**Comment by Ash10744** [comment]
What would that permission be I don't have the OP system so I can disable that perm if I do have it? But wouldn't that prevent other rules also? Considering the other ones work?

**Comment by kangarko** [comment]
Yes. So sorry, I had to leave office, will be getting back on you in 2-3 days max.

**Comment by kangarko** [comment]
Sorry, I'm back. Correct, if the first rule works but the other doesn't then it would not make sense.

Can you try this?

```
match (.*)(\)\))$
ignore channel Local
then warn Should redirect the message!
then command channel send standard Local $1
then deny
```

Are you getting "Should redirect the message!" in the game chat when you type a message ending with )) ?

Also, is there any other chat formatting plugin being used?

**Comment by Ash10744** [comment]
That didn't work which is super odd, I only have CMI? But the chat module is off?  So not sure what it could be?

**Comment by Ash10744** [comment]
Here is a list of my plugins
```
[15:40:39 INFO]: ------------=[ Plugins ]=-------------
[15:40:39 INFO]:  Plugins (85): AdvancedCrates, AreaShop, BannerMaker, BigDoors, BlockParticles, BlockRegen, BungeeGuard, BungeeTabListPlus, BuycraftX, CMI, CMILib, ChatControlRed, ChestProtect, Citizens, ClearLag, CoreProtect, Craftconomy3, CustomFishing, DeluxeMenus, Denizen, DiceFurniture, DiscordSRV, FastAsyncVoxelSniper, FastAsyncWorldEdit, FurnitureLib, HeadDatabase, ImageOnMap, Interactions, ItemEdit, ItemJoin, ItemsAdder, ItemsAdder-WorldEdit, Jobs, LagAssist, Lands, LibsDisguises, LightAPI, LoneLibs, LuckPerms, MCPets, MVdWPlaceholderAPI, Magic, MineableGems, MoarBows, ModelEngine, MorePlayerModels2, Multiverse-Core, Multiverse-Inventories, MythicLib, MythicMobs, OpenAudioMc, OpenRP, PhatLoots, PlaceholderAPI, Plan, PlayerVaults, PlugMan, PocketGames, ProtectionLib, ProtocolLib, RPGInventory, ServerUtils, Shopkeepers, TAB, TimeManager, TokenManager, UltimateAutoRestart, UltraCustomizer, Vault, Vehicles, VenturaCalendar, VenturaUtilities, ViaBackwards, ViaVersion, VoidGen, Votifier, WDLCompanion, Webizen, WhitelistByTime, WorldBorder, WorldGuard, dtlTraders, spark, squaremap and squaremarker
[15:40:39 INFO]: -------------------------------------------------
```

**Comment by kangarko** [comment]
So sorry I really can't reproduce.

![a](https://i.imgur.com/glCFF0x.png)

![b](https://i.imgur.com/l2AA2kB.png)

These are the rules:

```
match ^(\!)(.*)
ignore channel standard
then command /ch send standard $2
then warn (Redirected your message to standard)
then deny

match (.*)(\)\))$
ignore channel global
then command /ch send global $1
then warn (Redirected your message to global)
then deny
```

Try them, just edit the "global" to your "local" and let me know if you are seeing the warn message in the chat like I do. If not, post me your entire /chc debug file so I can try running on your exact setup.

I apology that this takes so long.

**Comment by Ash10744** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/12313178/debug.zip)


Here ya are <3 Hopefully, this helps and the one you just did I will test now

**Comment by Ash10744** [comment]
Alright it still didn't work.
I have no idea why, sorry this is being a big pain in the ass.
![image](https://github.com/kangarko/ChatControl-Red/assets/16086663/682cc302-b5df-4ca1-99ea-b42f3c3e3dc3)

**Comment by Ash10744** [comment]
Could my bungeecord be effecting this could it be my network channel?

**Comment by kangarko** [comment]
Can you please try only using ChatControl and no other plugins on a test server?
