### ISSUE TITLE
1.19.3 Accented characters gets unaccented.

### ISSUE THREAD

**Issue by download042** [kangarko/ChatControl#2349]
### "/version ChatControlRed" - plugin version

v10.18.4

### Are you using MySQL?

No

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11398207/debug.zip)
![image](https://user-images.githubusercontent.com/13710574/236229946-f625de62-e05a-415a-827c-fbb38f07a13e.png)

### Information about the issue/bug

I have a chat rule in chat.rs:

match :D
require perm chc.chatemoji.1 
then replace &r&f馣{chat_color}{chat_decoration}
dont verbose

Replaces ":D" text to "馣" (resource pack font smile icon, see screenshot)
This rule somehow makes the accented characters unaccented. 
Any idea how to fix? Am i making something wrong?

**Comment by kangarko** [comment]
Set the Rules.Strip_Accents to false to fix this.
