### ISSUE TITLE
Cannot define an operator when no rule is created issues

### ISSUE THREAD

**Issue by AhRoon** [kangarko/ChatControl#235]
Hello, when I edit the rules.txt, It happens when I launches the server.
And this time, I have set the Encoding to UTF-8, It still happenes.

Log: https://pastebin.com/08T9ZKSg

rules.txt: https://pastebin.com/1FXbjEgy

Can you look into the file what is happening?
Thanks.

**Comment by kangarko** [comment]
Hello & welcome to Issues Tracker!

The file seems OK. I cannot see the encoding when you upload the content of the file elsewhere. I recommend you use Notepad++ and go through various encodings: ANSI, UTF-8, UTF-8-BOM and the others as well.

If you are using Multicraft or you edit the file in other program then Notepad++ or another one where you set the encoding, it will be reset.

**Comment by kangarko** [comment]
I assume it's fixed, because this is in 99% of cases caused by a wrong encoding. Please let me know if you have any issues.
