### ISSUE TITLE
1.19.4 | Chat not forwarding through bungee / bungeecontrolred

### ISSUE THREAD

**Issue by TheTechnologyStudio** [kangarko/ChatControl#2350]
### "/version ChatControlRed" - plugin version

10.17.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

None

### "/chc debug" output (strongly recommended)

[debug_geopol.zip](https://github.com/kangarko/ChatControl-Red/files/11420782/debug_geopol.zip)
[debug_lobby.zip](https://github.com/kangarko/ChatControl-Red/files/11420790/debug_lobby.zip)

BungeeControlRed - Config: https://hastebin.com/share/wikafusope.yaml
Bungee Config File - Config: https://www.toptal.com/developers/hastebin

Server names are specified in the server. Properties files

### Information about the issue/bug

Global / admin / vip chats not being forwarded over bungeecord but works fine locally just not sending over bungee. 

Any help would be awesome, Let me know if any more questions.

**Comment by kangarko** [comment]
I see you set the Debug key to "bungee", what did the console say when you type a message? Also make sure you are connecting through bungeecord not directly to the server then we cannot forward it

**Comment by ElBananaa** [comment]
Update chatcontrol and bungeecontrol. You are using outdated versions.

**Comment by kangarko** [comment]
oh I missed that, good catch thanks! Closing, let us know if it got resolved by updating
