### ISSUE TITLE
MC1.8: Multiple Join Messages

### ISSUE THREAD

**Issue by Nolan6464** [kangarko/ChatControl#2351]
### "/version ChatControlRed" - plugin version

10.18.5

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

I got the BungeeCord join/leave messages working. But there seems to be the default? Minecraft join message, where is shows "PLAYER joined/left the game" in yellow along with the configured messages in Bungeecord. I found a old Github issue which seem to be very similar to this, they could not find the issue with it. Do you have any ideas why it might be displaying it?

**Comment by kangarko** [comment]
You need to enable Messages in Spigot/Bukkit and then leave your join.rs or quit.rs files empty on that Spigot/Bukkit server to not send anything.

**Comment by Nolan6464** [comment]
I remove the insides of join.rs and quit.rs on my spigot side, but it still displays. Picture of the chat: https://justpaste.it/8f8r0

**Comment by Nolan6464** [comment]
Here is a debug of my CHC folder: 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11445432/debug.zip)
