### ISSUE TITLE
MC1.8:Messages Editing

### ISSUE THREAD

**Issue by Nolan6464** [kangarko/ChatControl#2353]
### "/version ChatControlRed" - plugin version

10.18.5

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

N/A

### Information about the issue/bug

![image](https://github.com/kangarko/ChatControl-Red/assets/133073085/00d6e687-3a8b-4306-96c6-a71c619d7626)
I cannot edit the format of this message. The messages config lists this section has:
`  Reply:
    Dosage: <message>
    Prescription: '&fReply to the last person who msg you.'
    Alone: '&cCould not find anyone to reply to!'`

**Comment by Nolan6464** [comment]
![image](https://github.com/kangarko/ChatControl-Red/assets/133073085/edb16030-3601-4f40-8b3e-4b669a1edcd3)
I changed the setting of "Simple_Help_Design" and now when running commands the help menu is unstable. The order of messages it sends is random. In the example above I ran the command " /msg " twice and it sent the help commands in different format orders. It does this for some reason.

**Comment by Nolan6464** [comment]
Here is another example, the order of text it sends in not right. It sometimes sends "Usage:" first, other times "Description" first.
![image](https://github.com/kangarko/ChatControl-Red/assets/133073085/6f4222f4-cbde-430d-88d0-7fec994b91a0)

**Comment by Nolan6464** [comment]
Another example, like why is the description on the bottom and usages in the middle??
![image](https://github.com/kangarko/ChatControl-Red/assets/133073085/265877f6-5ee5-4e2d-8bf6-06b9f9e307ad)

**Comment by kangarko** [comment]
<img width="668" alt="Screenshot 2023-05-18 at 19 04 16" src="https://github.com/kangarko/ChatControl-Red/assets/1918426/598f9f27-eb1a-424f-a6eb-6172699385ed">
You have to restart the server not /chc reload for some messages to get updated.

Not sure why the out-of-order issue happens, I assume your 1.8 fork is trying some async stuff messing up our logic.
