### ISSUE TITLE
1.19.4 Paper/Purpur with Velocity 3.2.0 - Snapshot Build #254

### ISSUE THREAD

**Issue by RHydrix** [kangarko/ChatControl#2354]
### "/version ChatControlRed" - plugin version

10.18.5

### Are you using MySQL?

Yes

### Error log (if applicable)

https://gist.github.com/Waffl3Development/a51fc3207acfaf330806773c1fce33b4#file-error-txt

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11473736/debug.zip)

Not sure if anything will be seen in the main files as it seems to be specifically with Velocity

### Information about the issue/bug

Velocity Server with VelocityControl and Purpur server with chat control red with Mariadb server and after joining the server it just spams the velocity console

**Comment by james090500** [comment]
Hi,

The error log is unaccessible.

**Comment by Lorias-Jak** [comment]
![grafik](https://github.com/kangarko/ChatControl-Red/assets/62625225/03d02a6d-6c19-4d70-b42d-3c5a39768ca5)

I think its this one, i tried to use VelocityControl v3.11.4. It spams the message. I downgraded back to 3.11.3


If the picture is not good readable here the spam part of vc
https://paste.md-5.net/yokiyafepa.bash

**Comment by james090500** [comment]
Just to confirm, it only spams with new version not old one?

**Comment by RHydrix** [comment]
Yeah it's that error, I updated my GitHub name thing and forgot it would break that link https://gist.github.com/RHydrix/a51fc3207acfaf330806773c1fce33b4 there's the updated link although probably not needed anymore

**Comment by Lorias-Jak** [comment]
> Just to confirm, it only spams with new version not old one?

Yes, only on new version, not on old one

**Comment by james090500** [comment]
Seems something from the CHC side is sending null data. 

Is this purpur?

Can you test with a single purpur and velocity instance with just chatcontrol and velcoity control? 

If so turn on debugging and send logs from both. Not at PC at the moment so can't test to much sorry!

**Comment by RHydrix** [comment]
I am also not at my PC at the moment but I will once I get home from work 
     
     
      
     
    
    
     
     
       -- 
      Sent from Canary 
      
      
       
      
     
    
    
    
     
     
       On Monday, May 15, 2023 at 11:07 AM, James Harrison ***@***.***> wrote: 
       
      
      
       
      Seems something from the CHC side is sending null data. 
      Is this purpur? 
      Can you test with a single purpur and velocity instance with just chatcontrol and velcoity control? 
      If so turn on debugging and send logs from both. Not at PC at the moment so can't test to much sorry! 
      —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 
      ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/kangarko/ChatControl-Red/issues/2354#issuecomment-1548045901","url": "https://github.com/kangarko/ChatControl-Red/issues/2354#issuecomment-1548045901","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

**Comment by Neeonn** [comment]
Getting the same error. Reported on Discord but got no response.
Velocity 3.2.0-SNAPSHOT (git-7f776abf-b252)

```
[21:54:05] [Velocity Task Scheduler - #549/ERROR] [com.velocitypowered.proxy.scheduler.VelocityScheduler.VelocityTask]: Exception in task org.mineacademy.velocitycontrol.listener.VelocityControlListener$$Lambda$2621/0x0000000801c2b0a8@6d682958 by plugin VelocityControl
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "object" is null
	at org.mineacademy.velocitycontrol.listener.OutgoingMessage.compileData(OutgoingMessage.java:87) ~[?:?]
	at org.mineacademy.velocitycontrol.listener.OutgoingMessage.send(OutgoingMessage.java:57) ~[?:?]
	at org.mineacademy.velocitycontrol.VelocityControl.broadcastPacket(VelocityControl.java:151) ~[?:?]
	at org.mineacademy.velocitycontrol.SyncedCache.updateForOnlinePlayers(SyncedCache.java:245) ~[?:?]
	at org.mineacademy.velocitycontrol.listener.VelocityControlListener.lambda$scheduleSyncTask$1(VelocityControlListener.java:74) ~[?:?]
	at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:242) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by RHydrix** [comment]
alright I have a velocity server with only velocity control and a purpur server with chat control red same error as before 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11483596/debug.zip)

there also doesn't appear to be anything in the purpur logs HOWEVER i did notice this little bit at the top of the velocity log 
https://gist.github.com/RHydrix/4498174649890d7c9e3577d1390a6a11
On line 12 Velocity async event executor throws an error saying it "Couldn't pass ServerConnectEvent to Velocitycontrol" and after that it begins spamming the error seen above

**Comment by RHydrix** [comment]
[2023-05-16-4.log](https://github.com/kangarko/ChatControl-Red/files/11483705/2023-05-16-4.log)
also here is the log from the purpur server nothing really interesting here

**Comment by kangarko** [comment]
@james090500 you have access to ChatControl's source code right? Can you please help me debug and locate what is sending the null data? Thanks

**Comment by Callial** [comment]
> @james090500 you have access to ChatControl's source code right? Can you please help me debug and locate what is sending the null data? Thanks

So I am not sure if this is helpful to you or not, but I made a small fork of velocity control to fix a few of the errors I had seen pop up (Just adding some null catches since it seemed to be working fine I just didn't want to see the errors), the line of code that was causing the error in this issue, was when the channel name was added to the queue here https://github.com/kangarko/VelocityControl/blob/main/src/main/java/org/mineacademy/velocitycontrol/listener/OutgoingMessage.java#L27 when I added this line of code right before it, Just to make it so the channel name had a value even if it was null. The error no longer spammed console as it could properly be caught with the if else tree that is listed as the erroring function.

```
if (this.getChannelName() == null) {
     this.setChannelName("Null");
}
```

I also made a few other minor formatting tweaks(I just hate squiggly lines under my code so if the behavior is the same I will use the IDE's recommendations) And I think I added one or two other null catches but I can't remember, you can see all the differences here, I only bothered looking at files that threw errors. https://github.com/kangarko/VelocityControl/compare/main...Callial:VelocityControl:main Hopefully that helps, my version seems to be working just fine for me now, but as I changed some other formatting things without fully knowing how the code base was set up I won't be submitting a merge request unless asked. (Sorry if this was a jumbled mess, I am extremely ill right now)

**Comment by james090500** [comment]
Feel free to submit a pr! Will try take a look soon

**Comment by Callial** [comment]
> Feel free to submit a pr! Will try take a look soon

Submitted, don't think I broke anything but let me know :)

**Comment by kangarko** [comment]
Answered on https://github.com/kangarko/VelocityControl/pull/6

I think you need to update the scheme rather than hiding the error, I havent seen a case where the channel is null, to me it rather seems like an issue of message order not being updated after we changed upstream
