### ISSUE TITLE
1.18.2: Bungee Question

### ISSUE THREAD

**Issue by MrSkidder** [kangarko/ChatControl#2355]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Heyy,

So i have a few questions. 
1. when i try to join a channel its return: Player '<playername>' is not connected trough BungeeCord. Why is that?
2. So there is this anti swear rule, and i wonder how can i set it up to see the swear alert on every server on the network, not just on that server where is the player swearing.

I tried everything, please help me. Thanks in advance

**Comment by TheIntolerant** [comment]
Make sure you have [BungeeControl-Red](https://builtbybit.com/resources/24248/) on your bungee server.

**Comment by MrSkidder** [comment]
Its inside bungeecord plugins folder and not working,
The plugin is fully working but the features arent
