### ISSUE TITLE
1.19.4 how do I set default chat color to white?

### ISSUE THREAD

**Issue by chrydin** [kangarko/ChatControl#2356]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I put in luck perms so player join the standard channel automatically, but their chat color is grey, is there a way to make it default to white?

Thanks

**Comment by kangarko** [comment]
Yes you need to edit the formats/chat.yml assuming that's your channel format, place &f before the {message} variable to make the message show up white.
