### ISSUE TITLE
URL Hover

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2357]
### Summary

If a user types a certain URL in chat, such as `https://youtube.com/test`, it would be shown in chat as [URL], which players would be able to hover and click on. It would certainly make the chat look a lot cleaner.

(Of course, I would still have global rules in place to prevent grabify & other links.)

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Well, nothing really, but I would like to allow players to share some videos & channels from youtube, twitch, tiktok, etc. By having this feature, even if the chat were to be spammed, it would look good. If the feature is not going to be implemented, I do not think I will add this change, as it is not good to have links in chat. It does not look nice at all.

**Comment by kangarko** [comment]
This could be really nice and is something I look forward to next time I rewrite the rules engine. As of right now there's no ETA.
