### ISSUE TITLE
Faster rules & ignoring usernames of online players

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2358]
### Summary

```
[21.03.2023 15:37:56] Liavps11: /msg LTFC untrustworthy person
[22.03.2023 23:59:02] Lost_Dogo: /msg miloranjer k come spawn
[18.05.2023 10:08:23] XXLshadowclassic: /msg CSNIG gimme your sword ill enchant it
+ other 100 messages...
```
Usernames from various players are mixed in the rules, making them falsely matching certain messages.

That is why I got a very interesting idea, where it would be possible to modify how the matched messages in rules are handled, possibly improving performance.

I am not quite sure, how the `before replace` is handled during the rules right now, but what if the order of matching messages would be this:
1. Try to catch a message via the `match`, without looking at `before replace`
2. If the message is matched, only then we are going to try to apply the `before replace` to the message and match again
3. While we're applying the `before replace`, we can also get all online players and ignore them

By using this logic, if using 100+ rules, we would not need to apply `before replace` from each rule, but only for the matched one. This change also allows us to ignore all online players' usernames from the one matched message, instead of applying it to all the rules.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Falses when usernames from online players are mixed in the rules, as well as slow performance when using hundreds of rules at once.

**Comment by kangarko** [comment]
The rationale behind "before replace" is that of it will help to make the "match" more effective by replacing certain content in the message before it was matched. It goes first in the code:

![a](https://i.imgur.com/P784VSC.png)

I unfortunately cannot satisfy all users, we had more users request it being this way than the other way. I hope you understand.
