### ISSUE TITLE
if Disallowed_Usernames -> Then command

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2359]
### Summary

Self-explanatory.

If regex from settings.yml `Anti_Bot.Disallowed_Usernames` is found, execute a command (configurable).
When using proxy, this is not enough to stop players from trying to connect to the server, that is why I need to ban them.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Nothing, but currently the option is not very useful. Sometimes the player with a bad name ends up in a proxy joining loop.

**Comment by kangarko** [comment]
Prepac za oneskorenie, bol som mimo domov. Dostanem sa k vsetkemu koncom tyzdna.

**Comment by kangarko** [comment]
Added!
