### ISSUE TITLE
1.19.3 Adminchat not sending cross servers

### ISSUE THREAD

**Issue by dahbawz** [kangarko/ChatControl#2360]
### "/version ChatControlRed" - plugin version

ChatControl-Red-10.17.6.jar

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11535833/debug.zip)

### Information about the issue/bug

Since we've updated, we can write messages in the adminchat, but other stafmembers can't read them. This only happens on one of our servers within our bungee network. It also only started after we updated chatcontrol. We didn't change any of the files.

**Comment by kangarko** [comment]
What do you mean they "can't"? What happens when they write? Are they joined in read/write mode?

**Comment by kangarko** [comment]
How are they writing there, using /chc send or directly in the game chat,

**Comment by TheIntolerant** [comment]
I believe I helped this person the other day on discord, from what I can tell this issue was caused by having a older version of BungeeControl installed which didn't support the chatcontrol version being used, thus messages weren't sent via the proxy server.

So this *should* be working now.

**Comment by kangarko** [comment]
@TheIntolerant you are a life saver :)

**Comment by dahbawz** [comment]
Yes it was me on discord! Thanks again for the help. all is resolved now!
