### ISSUE TITLE
1.17-1.19.4: Mute Command Doesnt Mute

### ISSUE THREAD

**Issue by NeverGrowUp** [kangarko/ChatControl#2361]
### "/version ChatControlRed" - plugin version

10.18.6

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11554365/debug.zip)
Debug output from Purpur 1.19.2-1758.
Can provide other builds, or Paper version if required.

### Information about the issue/bug

Using the command `/mute player <playername> 15m`, does not mute the player. (player is online). Notification that player is muted appears in chat (messages_en.yml>Mute:Mute_Success), but player can still chat. No errors appear in console or error.log

Has been an issue on our live bungee server for a while, and initially thought it was our configs not updating through the various updates. 
Created fresh local server with minimal plugins (CCR, LuckPerms, ProtocolLib, and Vault), and have pinpointed that it did work on build 10.16.5, and started failing at 10.16.6. (each time letting CCR create new configs)

Only change made to settings.yml between 10.16.5 and 10.16.6 was addition of `Channels.Filter_Insecure_Chat`. Toggled this setting, which didnt fix mute. (wasnt expecting it to anyway)
10.16.6 was also the build where MuteEvent API was introduced.
Player does not have chatcontrol.bypass.mute perm.

**Comment by kangarko** [comment]
Thanks, you're right, that bug came after the introduction of MuteEvent. I fixed it now.
