### ISSUE TITLE
MC:BUNGEECORD ( ChatControlBungee addon join.rs, and quit.rs messages)

### ISSUE THREAD

**Issue by NolanDesu** [kangarko/ChatControl#2362]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

I have 4 servers, and when a player joins it goes like this.
- They connect to the Proxy, which sends them to the "Limbo" where they register, and then to the "Hub" where they can then go to the Bedwars, Survival, Skywars, etc server from there.

What I want is for the join message to not be sent when they join the Limbo server, but when they join the Hub server. Because they might not join the Hub, they may just stay in Limbo (might just enter and leave before logging in or registering). 
I tried using the " Ignored_Servers " by adding the Limbo server, and messing around with the " require sender server ", or "ignore sender server", etc but that disables the join message entirely. I thought that maybe the plugin only registers the "join.rs" file ONCE when they join the proxy, even if they are sent to a ignore server. 

Anyway, what would I be able to do to achieve this?

FYI > Since the LIMBO server is just a limbo, it doesn't have any plugins, it is a standalone server

**Comment by kangarko** [comment]
I am sorry but for this custom setup you'd likely need a small custom plugin developed that would hook into our API. I can roughly assist you but I am unable to develop this for you.
