### ISSUE TITLE
1.19.4: Mentioning someone on chat doesn't  change color of mentioned user, Also when typing prefix for example @ it doesn't recommend online users on tab complete

### ISSUE THREAD

**Issue by MatinHQ** [kangarko/ChatControl#2365]
### "/version ChatControlRed" - plugin version

10.18.6

### Are you using MySQL?

Yes

### "/chc debug" output (strongly recommended)

Emailed to support

### Information about the issue/bug

Mentioning someone on chat doesn't  change color of mentioned user, Also when typing prefix for example @ it doesn't recommend online users on tab complete (however the mention sound will be played)

![image](https://github.com/kangarko/ChatControl-Red/assets/22664859/ca480572-9cb9-41b0-8280-f821b4a759f8)
![image](https://github.com/kangarko/ChatControl-Red/assets/22664859/af366da9-f395-4c59-a158-89c1713e6a21)

**Comment by Neeonn** [comment]
I have the same issue. 10.18.5 Providing debug:
[debug(6).zip](https://github.com/kangarko/ChatControl-Red/files/11585418/debug.6.zip)

**Comment by kangarko** [comment]
Thanks. Will fix. Note that tab completion when you have a prefix such as @ is not supported atm

**Comment by MatinHQ** [comment]
> Thanks. Will fix. Note that tab completion when you have a prefix such as @ is not supported atm

Most of similar plugins supports that, can you add that please?

**Comment by kangarko** [comment]
Not sure how to do it, I already tried couple of times but 1.13+ had some breaking changes: https://www.spigotmc.org/threads/how-to-change-the-tab-completer-for-chat-messages.352203/#post-3257206, https://www.spigotmc.org/threads/tab-completions-in-chat.467146/
