### ISSUE TITLE
1.8.8: Unparsed Variable

### ISSUE THREAD

**Issue by Neeonn** [kangarko/ChatControl#2366]
### "/version ChatControlRed" - plugin version

10.18.5

### Are you using MySQL?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/d69896860a8344478348c8f6dc726c6c

### "/chc debug" output (strongly recommended)

[debug(6).zip](https://github.com/kangarko/ChatControl-Red/files/11584815/debug.6.zip)

### Information about the issue/bug

I tried using `{player_is_flying}` variable in my `rules/commands.rs` rule:
```match ^\/test$
require script {player_is_flying}
then warn {prefix_success}works
then deny
```
After executing `/test` command, an error shows up in console (same one found in `error.log`).

**Comment by kangarko** [comment]
Where you get the variable from? I cannot see it in your custom variables:

<img width="810" alt="Screenshot 2023-05-31 at 18 04 45" src="https://github.com/kangarko/ChatControl-Red/assets/1918426/2ba9f53f-1851-453e-b9a3-396afbf3abf9">

can you try this instead?

`require script '{player_vanished}' == 'true'`

**Comment by Neeonn** [comment]
From https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders `%player_is_flying%`.
I tried adding a custom variable in chatcontrol (copied player-is-vanished and made player-flying) and it still produces the same error.

**Comment by Neeonn** [comment]
My bad, was supposed to surround in ''...

**Comment by kangarko** [comment]
Yes, sorry for the confusion!
