### ISSUE TITLE
1.19.3 - Error on latest ItemsAdder update

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#2367]
### "/version ChatControlRed" - plugin version

10.18.6

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://pastebin.com/WAt6tEFJ

### Information about the issue/bug

Plugin do not load when using latest itemsadder jar (3.4.1d)

**Comment by kangarko** [comment]
I am sorry I don't know how Pufferfish+ works, but I tried on PaperSpigot 1.19.4 using 3.4.1d of ItemsAdder and it loaded without issues.

If the error happens in the game later after the server has loaded let me know, otherwise you'd need to test with Paper
