### ISSUE TITLE
1.16.4 | /motd sometimes says the player is offline

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#237]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

/motd command still sometimes says that player is not online, tried from both console and from the game

![image](https://user-images.githubusercontent.com/62369973/101282099-1471b700-37e4-11eb-9f28-148b33e272f6.png)
![image](https://user-images.githubusercontent.com/62369973/101282117-22bfd300-37e4-11eb-81e5-97d326aac29d.png)

debug:
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5648847/debug.zip)

**Comment by kangarko** [comment]
Can you please try the next release please? I made some edits to the cache map, could not reproduce your issue.

**Comment by OfT3N** [comment]
> Can you please try the next release please? I made some edits to the cache map, could not reproduce your issue.

You mean 10.1.6 or wait for the next?

**Comment by kangarko** [comment]
Please wait for 10.1.7

**Comment by kangarko** [comment]
It has been released, if you will still have this odd bug please comment below and I add some special debug messages. Pretty hard to find out why this is happening.
