### ISSUE TITLE
/Nick command from essentials doesn't change the nickname in chat.

### ISSUE THREAD

**Issue by Ganeb** [kangarko/ChatControl#237]
Hello, i installed ChatControl and was very happy because of the customising, but stumbled upon a little problem, when trying to change nickname appearance with /nick, nothing in chat changes, here's my chat formatting line:
 Message_Format: '{factions_relcolor}§l{factions_roleprefix}§r{factions_relcolor}{factions_name|rp}%pl_suffix%pl_prefix %player {deluxetags_tag} &9&l> &7%message'
Am i missing something? Is there a something to replace %player that shows everything like it used with EssentialsChat [DISPLAYNAME] please help, it's kinda bugging me..

**Comment by kangarko** [comment]
Hello,

please use %nick variable instead of %player.
