### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by zombwie** [kangarko/ChatControl#2370]
### "/version ChatControlRed" - plugin version

v10.18.6

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://pastebin.com/Yu9urR2A

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11592160/debug.zip)

### Information about the issue/bug

when i coppyed and pasted it from a difernet server on my network i get this error this error is not on my other servers

**Comment by kangarko** [comment]
Make sure that chatcontrol and bungeecontrol red are on the latest versions everywhere. Something is outdated.
