### ISSUE TITLE
Folia support

### ISSUE THREAD

**Issue by mani1232** [kangarko/ChatControl#2371]
### Summary

Add support for Folia regionscheduler (im can help with test)

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Folia is a new core that allows you to keep a large number of players on the server without cutting back on the gameplay.

**Comment by kangarko** [comment]
I heard about it, and I am open to someone taking over this project as my plate is currently very full.

**Comment by mani1232** [comment]
> I heard about it, and I am open to someone taking over this project as my plate is currently very full.

I can help you with this.

**Comment by kangarko** [comment]
What's your experience with Folia projects?

**Comment by mani1232** [comment]
> What's your experience with Folia projects?

Im forked all eco plugins and add folia support https://github.com/mani1232/eco  (https://github.com/Auxilor)
im forked auction, protocollib, DecentHolograms, triton and Fancy plugins to add\help folia support

**Comment by kangarko** [comment]
Please email me your first and last name at matej@mineacademy.org and I'll send you a small NDA, then I will give you access to ChatControl Red source code so you can add support thanks :)

**Comment by mani1232** [comment]
> Please email me your first and last name at [matej@mineacademy.org](mailto:matej@mineacademy.org) and I'll send you a small NDA, then I will give you access to ChatControl Red source code so you can add support thanks :)

ok, im send, if need my discord: mani123#4406
