### ISSUE TITLE
1.19.4: Discord to Ingame Not Working

### ISSUE THREAD

**Issue by NyhmsQuest** [kangarko/ChatControl#2374]
### "/version ChatControlRed" - plugin version

10.18.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/ec8607c0e6b04853b3165d3cc549d1a5

### Information about the issue/bug

With the latest version ChatControl-Red-10.18.7 the Discord to Ingame isn't working but the Ingame to Discord is working.

**Comment by kangarko** [comment]
Sorry, I broke it. Going to fix in 1h
