### ISSUE TITLE
1.19.4: /tell across bungee network

### ISSUE THREAD

**Issue by fishermedders** [kangarko/ChatControl#2376]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

The title pretty much sums it up. I would like to know if it is possible to use /tell or /msg across a bungeecord network. I have looked at the wiki and can't find an answer, is this possible with chatcontrolred out of the box? I have standard chat working across servers, but can't figure this one out.

Thanks in advance,
Fisher

**Comment by kangarko** [comment]
Yes absolutely. Just install the BungeeControl Red plugin and the PMs should automatically sync across all connected servers.
