### ISSUE TITLE
1.19.4: Logs aren't logging messages

### ISSUE THREAD

**Issue by bzigus** [kangarko/ChatControl#2377]
### "/version ChatControlRed" - plugin version

10.18.6

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

https://ufile.io/uaeyd032

### Information about the issue/bug

The server only logs messages to the /chc log when send through discord, and not through the actual ingame chat. I have sent a couple pictures showing what I mean.
![Screenshot 2023-06-12 at 1 56 50 PM](https://github.com/kangarko/ChatControl-Red/assets/22013942/71004f11-22cf-4cf1-9f98-947b4751ff45)
![Screenshot 2023-06-12 at 1 57 34 PM](https://github.com/kangarko/ChatControl-Red/assets/22013942/1daa4466-0c23-456e-8b8e-103bdc848dfc)
The first picture is a messages sent through ingame and the second through discord. Only the discord message is logged.

This is the command I used. "/chc log chat".

Let me know if you need any more information, i'd be happy to give it. Thanks

**Comment by kangarko** [comment]
Is there anything in the console about the player having a bypass permission and his message thus being exempted from the log? Note that this message only appears once the first time the player chats.

**Comment by bzigus** [comment]
Yes there is. Thank you for the help. Should of noticed that.
