### ISSUE TITLE
1.20: Plugin not working (NoSuchMethodError - SnakeYAML)

### ISSUE THREAD

**Issue by Xect0r** [kangarko/ChatControl#2378]
### "/version ChatControlRed" - plugin version

10.18.8

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/ec92359761d54253912005af3f5a8ae7

### Information about the issue/bug

Running Purpur 1.20 (Stable Release)

Seems to be similar to the issue on #2375?

**Comment by kangarko** [comment]
We're not compatible with 1.20 due to md_5 breaking changes, we're investigating it

**Comment by NeverGrowUp** [comment]
Would have thought this issue would remain open until it is resolved as "fixed" or "not fixing"

**Comment by kangarko** [comment]
Just got it fixed. I expect all plugins to be updated in a few hours.
