### ISSUE TITLE
Minecraft Version: 1.19.4: On join console error spam

### ISSUE THREAD

**Issue by Afgewezen** [kangarko/ChatControl#2379]
### "/version ChatControlRed" - plugin version

3.11.4

### Are you using MySQL?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/e5de179ac0e64fb7b68094e9e5a9dbb5

### Information about the issue/bug

Error spam on join in velocity. also its making the file "velocitycontrol\users.json" in folder plugins. I dont think this should happen.

**Comment by kangarko** [comment]
@james090500

**Comment by james090500** [comment]
Can you tell me about your environment, is it windows, Linux, etc?

**Comment by Afgewezen** [comment]
Its running on pterodactyl. Installed on Ubuntu 22.04

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CtrlAiDel** [comment]
Just to let you know I took out all my plugins except for floodgate velocity, geyser velocity, and velocity control 3.11.4-snapshot.

I still have error spam in console, I thought i would share this info

**Comment by james090500** [comment]
Please try this:

https://github.com/kangarko/VelocityControl/suites/13676890370/artifacts/755734150

**Comment by CtrlAiDel** [comment]
It worked. I have no error in console anymore. 

I'd like to thank you again for you awesome plugin, and for your support :) !

**Comment by Afgewezen** [comment]
Maybe good to Know. As I reported before. Velocitycontrol is creating a file in the plugins folder called velocitycontrol\users.json
I think this is a typo in the plugin that it should be velocitycontrol/users.json so it will be in the folder. If this is not a mistake. Tell me :)

**Comment by kangarko** [comment]
@james090500 please put this out as a Release :)

**Comment by james090500** [comment]
@Afgewezen This is fixed now - https://github.com/kangarko/VelocityControl/releases/tag/3.11.5
