### ISSUE TITLE
ChatControl new localization - messages_hu.yml

### ISSUE THREAD

**Issue by montlikadani** [kangarko/ChatControl#238]
Welcome!
**I would like to add a new language to the plugin. Language name: Hungarian (hu) - messages_hu.yml.** If you've accepted me to add a language then tell me where to write it down.

**Comment by kangarko** [comment]
Hello and thank you for your interest!

Here is the English language file: https://pastebin.com/iqSuLSaw

Feel free to translate everything inside (except for the %xyz variables) and send it back. Thank you!

**Comment by montlikadani** [comment]
kangaroo
Translation is successful.
Download: http://www.mediafire.com/file/hnpwdcxch1mkyrp/messages_hu.yml
Pastebin: https://pastebin.com/1EqcLKVH

**Comment by kangarko** [comment]
Thank you very much! I will include it into a new update tonight.
