### ISSUE TITLE
VelocityControl is spamming in the console

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/ChatControl#2380]
### "/version ChatControlRed" - plugin version

10.19.0

### Are you using MySQL?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/858c3e1503594ec8beab5a861777d415/files/7b1e16e5bd9f411fae4cb612baf1b3e7/raw

### "/chc debug" output (strongly recommended)

I am receiving this error in loop in the velocity console! 

Have a good day!

### Information about the issue/bug

I run CHC on paper server.

My proxy is Velocity.

and I  am receiving this error in loop

**Comment by CtrlAiDel** [comment]
@kangarko I don't know If i have to tag you.. Sorry if I don't have too! Don't want to spam you. :)

**Comment by kangarko** [comment]
In the stack trace I cannot find "MineAcademy" or "ChatControl", these errors are from a different plugin.

**Comment by CtrlAiDel** [comment]
Isn't that a reference to it? sorry i'm still a new "developper" 

[12:29:25 ERROR]: Exception in task org.mineacademy.velocitycontrol.listener.VelocityControlListener$$Lambda$1747/0x00000008016b4878@339128e6 by plugin VelocityControl
java.lang.NullPointerException: null

It says VelocityControl

**Comment by kangarko** [comment]
Oh I see, sorry I missed that. @james090500 can you please have a look? We recently updated to 1.20 there were no protocol changes but I recommend you look into it

**Comment by CtrlAiDel** [comment]
Thank you guys for the great plugins ... :) i'll stay updated

**Comment by kangarko** [comment]
I don't know what I am doing wrong but in the above stack trace I cannot find "velocitycontrol" anywhere

**Comment by kangarko** [comment]
Do you see it in your link? https://paste.gg/p/anonymous/858c3e1503594ec8beab5a861777d415/files/7b1e16e5bd9f411fae4cb612baf1b3e7/raw

**Comment by CtrlAiDel** [comment]
This is coming from my Velocity Server and it spam it back to back.

**Comment by CtrlAiDel** [comment]
[latest.zip](https://github.com/kangarko/ChatControl-Red/files/11772388/latest.zip)

This is the .latest.log from my velocity server would that do ? 

How would you like me to share it to you?

**Comment by CtrlAiDel** [comment]
Sorry for the .zip ...didn't accept .log

**Comment by james090500** [comment]
Looks like SimpleBan to me

**Comment by james090500** [comment]
Actually this is related to #2379 

I will investigate

**Comment by CtrlAiDel** [comment]
I turned off simple ban, and my console was fine at first, but my logs are looking like that right now. Still spamming something
[latest.zip](https://github.com/kangarko/ChatControl-Red/files/11772483/latest.zip)

thanks for your plugin and your support!
