### ISSUE TITLE
Message sent in double in the last v. of Velocitycontrol & CHC

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/ChatControl#2381]
### "/version ChatControlRed" - plugin version

10.19.0

### Are you using MySQL?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/c591f471cb804f87ac3677f8cdc6cbfa

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11770777/debug.zip)

### Information about the issue/bug

1 Run    VelocityControl-3.11.4-SNAPSHOT.jar
2 Run chat red control 10.19.0 on multiple servers on paper servers 
( This server is running Paper version git-Paper-18 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 2e363c7)

Try to chat between servers.

![image](https://github.com/kangarko/ChatControl-Red/assets/40178706/e218fec3-9e15-44bb-b9f4-c98dfa2d038b)

I tried with all my servers and this is happening with all my servers.

Thank you for your support.

**Comment by CtrlAiDel** [comment]
@kangarko I don't know If i have to tag you.. Sorry if I don't have too! Don't want to spam you. :)

**Comment by kangarko** [comment]
I answered here, you need to fix your other plugins first > https://github.com/kangarko/ChatControl-Red/issues/2380

**Comment by CtrlAiDel** [comment]
Ok, just to give more information. In #2380 you seem to attribute "both problems" to one plugin. I turned off simple ban temporarily. 

I have tried back the chat without this plugin, and the chat is still doubled. 

I will give more info in the issue #2380

**Comment by CtrlAiDel** [comment]
Just to let you know I took out all my plugins except for floodgate velocity, geyser velocity, and velocity control 3.11.4-snapshot.

I still have double messages sent by my game and CHC :S sorry for the trouble.

**Comment by CtrlAiDel** [comment]
I had this filled out in VelocityControl

  # List of what servers do not have ChatControl and need chat forwarded to them?
  To_Servers:
#    - "TempCity"
#    - "Creative"
#    - "Hardcore"
(i commented them)

My problem is fixed :) ! Thank you for the great plugins...now the console error ----­­>  #2379
