### ISSUE TITLE
1.20.1 Waterfall start error

### ISSUE THREAD

**Issue by ItzRonaldMLG** [kangarko/ChatControl#2382]
### "/version ChatControlRed" - plugin version

10.19.0

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/5a2494fb85b445a497d3a96f41636d66

### Information about the issue/bug

There is an error on startup.

Latest Waterfall (waterfall-1.20-536).
Old config from 1.19.4 server is being used.

**Comment by kangarko** [comment]
ChatControlRed is a Bukkit plugin, install BungeeControl Red on your Waterfall only.
