### ISSUE TITLE
when somebody joins, send a welcome message with the possibility to click on it and send the command /welcome "%username%" 

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/ChatControl#2383]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Quick question; 

About this join.rs settings: 

An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server runs MC 1.13 or greater.
Please make sure to keep your first join message at the top of the file, above any other join message to avoid any issues.
#group firstjoinmessage
#require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
#message: 
#- &7Welcome to the server &c{player}&7!

Could anyone tell me how I could program the command /welcome "%player_username%" when people would click on it.

Like on that picture 
![20230616_131417](https://github.com/kangarko/ChatControl-Red/assets/40178706/a793df47-7107-47a8-9a0a-40a1ce53beff)

Is it really in that join.rs file?  Thank you again. I might be planning to get into your java course soon!

Have a good day!

**Comment by kangarko** [comment]
Thanks, you can just refer to a format in the message, such as "chat" found in formats/chat.yml (create your own format)

```
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
message:
- chat
```

**Comment by CtrlAiDel** [comment]
I need to add something like this in chat.yml at the bottom?

  group firstjoinmessage:
  require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
    Message: '/Welcome: click here to say hello to {player} and win 100$!'
    Hover: '&cClick here to welcome new player!.'
    Run_Command: /welcome {player}
    
    Would that work in your opinion please?

**Comment by kangarko** [comment]
You do not need to add the "Require_Sender_Script" in your format. Simply create a new format such as motd.yml and reference it in your rule.

**Comment by CtrlAiDel** [comment]
"I have that in chat.yml

```
  welcome-first:
    Message: '/Welcome {player_nick} to be rewarded 100$!'
    #Message: "{player_name}"
    #Gradient: CYAN - WHITE
    Hover: '&7Click here for your reward!'
    Suggest_Command: '/welcome {player_name} '
```

and I have took out the # in there in the join.rs.

```
# An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server runs MC 1.13 or greater.
# Please make sure to keep your first join message at the top of the file, above any other join message to avoid any issues.
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
message: 
- &7Welcome xxx &c{player}&7!
```

Could you tell me how to integrate what I've done into the chat.yml into the join.rs?


Am I on the good path or not at all? Thank you!"

**Comment by kangarko** [comment]
Please use the appropriate formatting when pasting here (```).

I already told you not to use chat.yml format since this is the default chat format when anyone chats, you need to duplicate the file and place your format there - you can learn how to create formats in our Wiki or by looking at examples. And I told you above how to send the format using rules when the player joins for the first time.

**Comment by Izocel** [comment]
Hello @kangarko i'm helping @KvasirQc i'm developper i've read some of the wikis but can't seem to find why those don't work in @KvasirQc configuration, waht could be the cause where should the group 'firstjoinmessage' be referenced ?
in join.rs
```yaml
# An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server runs MC 1.13 or greater.
# Please make sure to keep your first join message at the top of the file, above any other join message to avoid any issues.
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
message:
- motd
```

```yaml
# An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server runs MC 1.13 or greater.
# Please make sure to keep your first join message at the top of the file, above any other join message to avoid any issues.
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
message:
- &7Hello world
``` 

none of these solution show a message when a players join

**Comment by Izocel** [comment]
I think i've found it the feature motd: in `setting.yaml` was set to `false`...
But the motd is private only right ? Anyway way to make it public ?

**Comment by CtrlAiDel** [comment]
I was able to load my format/onfirstjoin.yml in motd... but i'm not able to do the same in the join.rs
that would be really appreciated

i've asked help to my friend developper and even with him we weren't able to do so
I was able to load the onfirstjoin, in the settings at the line 860 :

What message is sent when the player joins for the first time.
Format_Motd_First_Time: onfirstjoin

But the message was only sent to the player joining off course, when I want it to be send to everyone, except for the player joining (if possible)

I'll just repeat what I am trying to accomplish.
I want this to happen:

Parts:
everything:
Message: Welcome {player_nick}, click on his nickname and press Enter to be rewarded 100$!
Hover: '&7Click here for your reward!'
Suggest_Command: /welcome {player_name}

Me and my developper friend worked on this for hours, could you tell us a little bit more ?

**Comment by kangarko** [comment]
> I think i've found it the feature motd: in `setting.yaml` was set to `false`... But the motd is private only right ? Anyway way to make it public ?

Yes it's private in the sense that it only sends to the player but not others. No, for public broadcasts you need to use the join message.



> Hello @kangarko i'm helping @KvasirQc i'm developper i've read some of the wikis but can't seem to find why those don't work in @KvasirQc configuration, waht could be the cause where should the group 'firstjoinmessage' be referenced ? in join.rs
> 
> ```yaml
> # An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server runs MC 1.13 or greater.
> # Please make sure to keep your first join message at the top of the file, above any other join message to avoid any issues.
> group firstjoinmessage
> require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
> message:
> - motd
> ```
> 
> ```yaml
> # An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server runs MC 1.13 or greater.
> # Please make sure to keep your first join message at the top of the file, above any other join message to avoid any issues.
> group firstjoinmessage
> require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
> message:
> - &7Hello world
> ```
> 
> none of these solution show a message when a players join

What do you mean that it "doesn't work"? What message is shown? Did you test on a fresh account? Post me your join.rs file uploaded to pastebin.com

**Comment by CtrlAiDel** [comment]
We tried to add some XXXX in the firstjoin so we could spot the message but we couldn't, we didnt received the first join (of course we deleted all player data to be sure to receive the message)

https://pastebin.com/fySrJfba

**Comment by kangarko** [comment]
I apology, Bukkit name was misleading, it actually is TICKS not MINUTES so you need to reset the data again, and increase the value to like 100 (that means that the player spent less than 5 seconds on the server, because 20 ticks = 1 second, so 100 ticks is 5 seconds):

require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 100

Bukkit confused both of us, I am sorry.

**Comment by CtrlAiDel** [comment]
Thank you for your feedback I appreciate!

**Comment by KvasirQc** [comment]
Does that make a sense?

# An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server runs MC 1.13 or greater.
# Please make sure to keep your first join message at the top of the file, above any other join message to avoid any issues.
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
Message: '/Welcome: click here to say hello to {player}, get rewarded 100$ and a scroll with quests!'
Hover: '&cClick here to welcome new player!.'
Run_Command: /welcome


+ i got this in my settings:

  # Should we hide join messages?
  Hide_Join_Messages: false

  # Should we hide quit messages?
  Hide_Quit_Messages: false
  
  
At the moment we don't see the message. 
Would that be because we are not in the firstjoinmessage group? Should it be sent to global/default or I have to create that channel and make everyone Read it? 

thanks

**Comment by CtrlAiDel** [comment]
```
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 100
Message: 
  - &7Click here to say hello to {player}, get a cash reward and a scroll with quests!
Hover: '&cClick here to welcome new player!'
Run_Command: /welcome
```


I have this at the moment, but it's still not loading
My settings has block join message to false.

Now i am wondering if my player must be in the  firstjoinmessage  group has reader to be able to see the join message or it's automatic? 

Thank you

**Comment by kangarko** [comment]
Sorry but it's a bit confusing, THe Run_Command key is not supported in the rules file. Did you check console for loading errors?

> My settings has block join message to false.
What do you mean? Please post your /chc debug folder here
