### ISSUE TITLE
First join message not editing in join.rs

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/ChatControl#2384]
### "/version ChatControlRed" - plugin version

10.19.0

### Are you using MySQL?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/5aee7198f94b4a23b750f57f18f5b86d

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/11777643/debug.zip)

### Information about the issue/bug

1) Modifiyng join.rs

``` yaml
# An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server runs MC 1.13 or greater.
# Please make sure to keep your first join message at the top of the file, above any other join message to avoid any issues.
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
message: 
- &7Welcome to the server &c{player}, dear newbie!&7!
```

2)  Restart the server
3)  We are not seeing the modification done to the server.

I am still trying to implement #2383 

Thank you, sorry for the problem,

**Comment by kangarko** [comment]
I answered there on the other ticket instead. Also note that this does not look like Velocity issue to me, since you are editing these files on Bukkit

**Comment by KvasirQc** [comment]
I was able to load my   format/onfirstjoin.yml   in motd... but i'm not able to do the same in the join.rs
that would be really appreciated, i've asked help to my friend developper and even with him we  weren't able to do so
I was able to load the onfirstjoin, in the settings at the line 860 :

  # What message is sent when the player joins for the first time.
  Format_Motd_First_Time: onfirstjoin

But the message was only sent to the player joining off course, when I want it to be send to everyone, except for the player joining (if possible)


I'll just repeat what I am trying to accomplish.
I want this to happen:

Parts:
  everything:
    Message: Welcome {player_nick}, click on his nickname and press Enter to be rewarded 100$!
    Hover: '&7Click here for your reward!'
    Suggest_Command: /welcome {player_name}


Me and my developper friend worked on this for hours, could you tell us a little bit more ?
