### ISSUE TITLE
1.20.1: Strange Error in Console

### ISSUE THREAD

**Issue by NyhmsQuest** [kangarko/ChatControl#2385]
### "/version ChatControlRed" - plugin version

10.19.0

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://mclo.gs/pIXs49J

### Information about the issue/bug

I noticed a strange error message in console, I don't know what caused it.
https://mclo.gs/VyBgPJA

**Comment by kangarko** [comment]
That is indeed strange, please test in the next version.
