### ISSUE TITLE
1.19.4: /chc log all group:swear throws a error

### ISSUE THREAD

**Issue by MatinHQ** [kangarko/ChatControl#2387]
### "/version ChatControlRed" - plugin version

10.19.0

### Are you using MySQL?

Yes

### Error log (if applicable)

https://paste.ubuntu.com/p/zjjBh3rb9b/

### "/chc debug" output (strongly recommended)

I will mail it

### Information about the issue/bug

When I run `/chc log all group:swear` it will throw that error

**Comment by kangarko** [comment]
Thanks, will be fixed.
