### ISSUE TITLE
1.20.1: No command? /chc inspect

### ISSUE THREAD

**Issue by SheerYin** [kangarko/ChatControl#2388]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

There is no command /chc inspect, and the Hover of variables cannot use the js function

Hover: |-
  function lore() {
    if (player.getItemInHand().getItemMeta().hasLore()) {
      return player.getItemInHand().getItemMeta().getLore();
    } else {
      return "";
    }
  }
  lore();

Or what should I do if I want to use js in Hover?

**Comment by kangarko** [comment]
Hey! The inspect command was removed due to safety concerns. JavaScript could theoretically be used but it's only supported on Hover_Item
