### ISSUE TITLE
1.16.4 | Some permissions do not appear at TAB-complete (LuckPerms)

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#239]
Version: 1.16.4

MySQL/Bungee: False/True

Scince LuckPerms is 98% used permission plugin, i think that would be nice if ALL of the plugin permissions will appear on tab-complete wjhen trying to give them

For example, there is no "leave" permision there
![image](https://user-images.githubusercontent.com/62369973/101289480-c83b6c80-380d-11eb-8f57-908c9edd09a8.png)

Im not sure if debug is needed there, but let me know if it is

**Comment by kangarko** [comment]
We create these permissions dynamically, meaning these are not registered for LuckPerms to see. Thanks for the suggestion though.

**Comment by OfT3N** [comment]
> We create these permissions dynamically, meaning these are not registered for LuckPerms to see. Thanks for the suggestion though.

As far as i know, LuckPerms can register those permissions, for example in the menu plugin if i just put a custom permission into the menu condition, LuckPerms starts tab-completing this without any reloads

![image](https://user-images.githubusercontent.com/62369973/101344547-b05bfb00-3896-11eb-8a4a-8510d40d1c5e.png)
![image](https://user-images.githubusercontent.com/62369973/101344561-b81b9f80-3896-11eb-881f-831b0a0b192e.png)

**Comment by kangarko** [comment]
I have no idea how to integrate those, I am sorry. I will focus on fixing important bugs and can have a look at this in the future.

**Comment by OfT3N** [comment]
> I have no idea how to integrate those, I am sorry. I will focus on fixing important bugs and can have a look at this in the future.

Ok. Thank you anyway :D

**Comment by 00Hrtz** [comment]
> 
> 
> Version: 1.16.4
> 
> MySQL/Bungee: False/True
> 
> Scince LuckPerms is 98% used permission plugin, i think that would be nice if ALL of the plugin permissions will appear on tab-complete wjhen trying to give them
> 
> For example, there is no "leave" permision there
> ![image](https://user-images.githubusercontent.com/62369973/101289480-c83b6c80-380d-11eb-8f57-908c9edd09a8.png)
> 
> Im not sure if debug is needed there, but let me know if it is

Would it be possible if you could help me please, i see you're using luckperms too and im having problems with my default players saying they have no access to channels. any chance i can see your default group's permissions list please?
