### ISSUE TITLE
1.8.9 - Interactive Chat & ChatControl Red Conflict/Issue

### ISSUE THREAD

**Issue by deathmaul2** [kangarko/ChatControl#2390]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hi,

I want to use Interactive Chat plugin on my server along side ChatControl Red.  

Interactive Chat Plugin link: https://www.spigotmc.org/resources/interactivechat-show-items-inventory-in-chat-custom-chat-keywords-bungee-velocity-support.75870/

When I try to use its features such at [item] or [inv] it's unable to parse the placeholders and looks like this: 

https://i.imgur.com/BPZ5eK5.png

Is this a ChatControl Red conflict or does the plugin developer of Interactive Chat need to support something within ChatControl Red? Any help would be appreciated Thank you.

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities and try adjusting things on our end. It it wont work out then it is unfortunately incompatible
