### ISSUE TITLE
1.20.1: Death Messages & Plugin Messages Are Not Showing Up

### ISSUE THREAD

**Issue by mrericwong** [kangarko/ChatControl#2391]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello, I am new to the ChatControl Red plugin. I recently found that there is a channel system in the plugin, which allows players to join channels like standard and global. I'd like to know how do I make a default channel for everyone to chat without typing commands to join a channel? Secondly, my players are using the standard channel right now. However, death messages & plugin messages (such as the Essentials AFK announcement) aren't showing up. 

Thank you for your help in advance.

**Comment by CtrlAiDel** [comment]
This is for the first question. I'll leave the second question to the professionnal!

In your permissions plugin, to your default user, add these strings:

chatcontrol.channel.autojoin.global.write
chatcontrol.channel.autojoin.standard.write
chatcontrol.channel.join.global.write
chatcontrol.channel.join.standard.write
chatcontrol.channel.join
chatcontrol.channel.leave

These permissions will help your users to autojoin these channel, to type /ch join and /join leave  

Hope that I've helped :)!

**Comment by CtrlAiDel** [comment]
I have a couple more strings I could give you, for CHC, but since they were not related, I did not send them all!

**Comment by mrericwong** [comment]
Hey! Thank you for your response! I'll try adding them later today and see if they work!

**Comment by kangarko** [comment]
Thanks to @KvasirQc for helping out!

In regards to the first question here's an extra video on how to autojoin people to one channel: https://github.com/kangarko/ChatControl-Red/wiki/Channels#not-having-channels-and-only-having-1-chat-classic-system

Death messages (I don't know what you meant by plugin messages?) need to be enabled under the Messages section of settings.yml first before showing up, and uncommented from your messages/death.rs file. If unsure just send me your /chc debug

**Comment by kangarko** [comment]
Let me know below if you have more questions :)

**Comment by mrericwong** [comment]
Hey kangarko, thank you for your response. I will check the video out later today when I get home. Regarding the plugin messages, what I meant was messages like the AFK announcement of Essentials (i.e. xxx is now AFK.) were not showing up. Any idea why it isn’t showing?

**Comment by kangarko** [comment]
Nope, we have no control over these.
