### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by devanshk4** [kangarko/ChatControl#2392]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

how can i block commands in chat control red??

**Comment by devanshk4** [comment]
also i have 1 more issue that in motd file using 
Image_Url: https://mc-heads.net/avatar/{player_uuid} 
or
Image head 
both options doesnt show the actual skin instead shows steve skin head

**Comment by kangarko** [comment]
To block commands in ChatControl, see rules/command.rs file for examples.

For the other issue please upload your whole MoTD part of settings to pastebin so I can see it

**Comment by devanshk4** [comment]
![image](https://github.com/kangarko/ChatControl-Red/assets/91319354/6f71ec04-5884-4789-a41f-a594036caf23)
![image](https://github.com/kangarko/ChatControl-Red/assets/91319354/a5809473-bd21-4396-9f41-628f690ef144)

**Comment by kangarko** [comment]
If you are using a cracked server, try using {player_name} instead:

`Image_Url: https://mc-heads.net/avatar/{player_name}`
