### ISSUE TITLE
1.19.4: Option to toggle off Bungee for private messaging

### ISSUE THREAD

**Issue by wellnesscookie** [kangarko/ChatControl#2393]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

I am using latest versions of BungeeControlRed and ChatControlRed.

I turned on:  Integration.BungeeCord.Enabled, so I could make Admin chat across all of our servers, but I want to turn Bungee OFF **for all other channels** (and private msg). The problem is that, I can explicitly say Bungee:false for my 'standard' channel, which I have, but how can I explicitly say Bungee: false for private messaging, as they do not show up as channels at all? I don't want to use the feature for Bungee-cross /msg, but I want to use your messaging system as is.

Does that makes sense? (Private_Messages section in settings.yml does not have Bungee:true/false option)

**Comment by kangarko** [comment]
Sure, I can add a toggle for Bungee mode for PMs in the next version.

**Comment by kangarko** [comment]
Will be pushed tonight!
