### ISSUE TITLE
Ignore username for caps check

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#2394]
### Summary

I got some players with fully caps username, and it automatically lower their username, but it creates an incompatibility with interactivechat, which display <ic^**username**> instead of just the username
![image](https://github.com/kangarko/ChatControl-Red/assets/31826333/39401c70-2195-40fa-81d5-0aca374efc51)
And interativechat dev told me he can't really fix this, because it creates other issue.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

My chat can be ugly because of this

**Comment by kangarko** [comment]
Hey, we already ignore usernames but we can't ignore them with the ic prefix. You can try reading about Listener Priorities on our wiki and adjusting our priority to see if some will fix the issue but there's no guarantee, I am sorry

**Comment by WarnDa** [comment]
If I change priority it creates issue with interactivechat or superior, already tried..
But thanks

**Comment by kangarko** [comment]
You need to pick one chat plugin for your chat formatting, either use channels from our plugin or use interactivechat, not both.

**Comment by WarnDa** [comment]
Interactivechat is just to add some interaction (like showing inventory, parsing placeholders, etc.) it's not a formatting chat plugin.
But yeah I'll stick with this issue until interactivechat dev manage on how to fix priorities on each events :/

**Comment by kangarko** [comment]
Due to how Bukkit works - we have to cancel the chat event and send it via our own, unique way - I am afraid that it wont work, because both plugins need to cancel the event and send it via their own ways making it conflict
