### ISSUE TITLE
1.20.1: Console Error Spam when a player is online

### ISSUE THREAD

**Issue by Tosfoy** [kangarko/ChatControl#2396]
### "/version ChatControlRed" - plugin version

10.19.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/9bfe425b2c2748aab0f772e05a2c1dbf

### Information about the issue/bug

Use latest paper 1.20.1 build, install chatcontrolred, launch server

**Comment by kangarko** [comment]
Update BungeeControl Red to 3.15.0 because the packet sequence has changed.

**Comment by Tosfoy** [comment]
We don’t use bungeecontrol red, that’s the problem. Do we really need to use it?

**Comment by kangarko** [comment]
Well the error says that ChatControl is attempting to read a packet sent by BungeeControl Red from somewhere and that BungeeControl Red version is outdated because it is using legacy order.

**Comment by Tosfoy** [comment]
That’s weird, I’ll try installing bungeecontrol and disable it’s features as we don’t need it, hopefully this fixes it.
