### ISSUE TITLE
folia

### ISSUE THREAD

**Issue by ewof** [kangarko/ChatControl#2397]
### Summary

folia support

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

unusable on servers with >200 players

**Comment by ewof** [comment]
u can see my github ive added folia support to a couple plugins and am open to adding it to chatcontrol-red
i saw the other issue but it's been like a month

**Comment by kangarko** [comment]
Thank you. @mani1232 is already working on a fork with Folia support, mani1232 would you be able to add ewof to your repository so he can sync it with the latest ChatControl changes?

**Comment by mani1232** [comment]
![image](https://github.com/kangarko/ChatControl-Red/assets/70480001/4271cd58-3ce3-4e43-8806-6ff7dafb7e23)
It works fine

**Comment by ewof** [comment]
can u send the jar? or put it on builtbybit?

**Comment by mani1232** [comment]
> can u send the jar? or put it on builtbybit?

Are you on the MineAcademy.org discord server?

**Comment by ewof** [comment]
yea my disc is ewofer but i havent verified yet 1 sec
