### ISSUE TITLE
Addition to the forwand function

### ISSUE THREAD

**Issue by Shaarper** [kangarko/ChatControl#2398]
### Summary

Hello, I would like to ask more about the forwand function.
In the past this function was available on behalf of the console, but now you have made it only on behalf of the player. 
So, why is that? (It says it's because of some kind of vulnerability, but which one?)
We need to use this particular command for our server on behalf of the console.
That's why we propose to make an extra function to enable and disable forwand from the console.
For example, if forwand-console: false is in config, then this command is used only on player's behalf. And if true, it can be used from the console as well. Thank you

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

we will look for other solutions

**Comment by kangarko** [comment]
We made it for security reasons such that malformed clients would not be able to execute console-level commands. As of right now there's no workaround
