### ISSUE TITLE
Paper 1.19.4: Whitelist delayed commands dont work

### ISSUE THREAD

**Issue by gazdyy** [kangarko/ChatControl#2399]
### "/version ChatControlRed" - plugin version

10.19.2

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Whitelist_Delay:
    - '/cmi spawn'
    - '/spawn'

**Comment by gazdyy** [comment]
![image](https://github.com/kangarko/ChatControl-Red/assets/60019769/a3216495-020b-4394-bd85-40ea05da8b34)

**Comment by gazdyy** [comment]
If I use for example "/tell" from your plugin, it works for me, but CMI spawn doesn't work, I don't understand....

**Comment by gazdyy** [comment]
Commands from other plugins (except CMI) work, but commands from CMI do not

**Comment by gazdyy** [comment]
Why don't commands with more words work? If I add the "/cmi" command to the whitelist, all commands will be ignored, so the bypass delay for the /spawn command will work for me, but I want to use only "/cmi spawn", the same happens if I want to use the bypass to turn off the global chat (from your plugin ) "/toggle chat" will not work

**Comment by kangarko** [comment]
Ahoj, prepáč, nerozumiem otázke.

Keď zadáš /spawn a /cmi spawn do whitelistu, tak tá kontrola bude vypnutá na /spawn a /spawn .... (hocičo), rovnako ako na cmi.

Ty chceš aby to vyplo kontrolu iba na /cmi spawn a nie na napríklad /cmi tp, atď?

**Comment by gazdyy** [comment]
Ano, keď zadám do whitelistu /spawn alebo /cmi spawn, tak stále vyžaduje cooldown... ak zadám do whitelistu len /cmi tak zruší cooldown pre všetky cmi príkazy, ale ja potrebujem aby nefungoval cooldown len na /cmi spawn, čo sa týka iných príkazov je tam ten istý problém, ak zadám príkaz ktorý ma medzeru, príklad "cmi spawn" alebo "toggle chat" tak whitelist ignoruje medzery

**Comment by kangarko** [comment]
Vdaka. Zmenim system a dam tam regex tak ako ma Whitelist_Delay v Chat. V dalsej verzii tam napis toto:

```
Whitelist_Delay:
- '/cmi spawn$'
- '/spawn$'
```

Zablokuje to vyhradne "/cmi spawn" a "/spawn", nie "/spawn adasdasdas" atd. Dal som tam dokumentaciu v komentari, mozes pozriet.
