### ISSUE TITLE
Cannot define an operator when no rule is being created

### ISSUE THREAD

**Issue by NoDi522** [kangarko/ChatControl#24]
Hello. Today i edited my ChatControl rules.txt and chat.txt files and when i reloaded my server i got an error message: "Cannot define an operator when no rule is being created".
Here are the links of my chat.txt and rules.txt:

Error in log = http://pastebin.com/WesBva36

Rules.txt = http://pastebin.com/aEr1YZd2

Chat.txt = http://pastebin.com/1ux87qBN

If you need any other file please comment as soon as possible :)

**Comment by kangarko** [comment]
Cannot replicate. You can send me the rest. If you would like to keep them private, please send me them via PM at Spigot forums (please do not forget to link to this conversation).

**Comment by NoDi522** [comment]
Hello thanks for reply. What exactly do you need:

handlers.yml:
http://pastebin.com/USqsjncX

settings.yml:
http://pastebin.com/9FJ8xAM5

**Comment by kangarko** [comment]
Can you please send me the rest of the rule files?

**Comment by NoDi522** [comment]
Commands.txt:
http://pastebin.com/dz8EMSiv

packets.txt:
http://pastebin.com/DEuryvj3

sign.txt
http://pastebin.com/KFVcKNZ8

**Comment by NoDi522** [comment]
I tried reseting server because i read one post and you said that error can be caused by much reloading so i restarted many times,and yes im using Notepad ++...

**Comment by NoDi522** [comment]
And just to know i wrote this swear part like you on tutorial where you explained how to block swearing and adverts.

**Comment by kangarko** [comment]
Closing.
Please post if you still have any issues.
