### ISSUE TITLE
1.16.4 | Confusing permissions

### ISSUE THREAD

**Issue by Qw4rtz** [kangarko/ChatControl#24]
/chc perms gives `chatcontrol.command.tell` permission node, but the given node doesn't work, it's actually `chatcontrolred.command.tell` that work.
The "No permission" message however gives the working node (`chatcontrolred.command.tell`).

Also, `chatcontrolred.command.tell` does not give access to /w or /pm, which are just aliases of /tell.

Suggestion 1: Either change all `chatcontrol.` nodes into `chatcontrolred.` or the opposite, `chatcontrolred.` changed into `chatcontrol.` nodes.

Suggestion 2: When using /w, /whisper, /pm and the other aliases, check for `chatcontrolred.command.tell` or `chatcontrolred.command.` the first alias.

**Comment by kangarko** [comment]
Thank you, I will change these remnants to "chatcontrol.X". I will also make the same permission apply for all command aliases.
