### ISSUE TITLE
1.20.1: High timings

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#2402]
### "/version ChatControlRed" - plugin version

10.19.2

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/12003151/debug.zip)

### Information about the issue/bug

I have this spark profile [https://spark.lucko.me/J9GuObaZKD](https://spark.lucko.me/J9GuObaZKD)

It shows some issues with tabcomplete and vanished players

**Comment by kangarko** [comment]
Thanks, do players use colors in their nicks? If not I can just add a toggle for the check to not replace colors since that appears to be draining it

**Comment by MADS0LADEN** [comment]
Yes most of the players have colors in nicks

**Comment by kangarko** [comment]
Thanks for reporting. I have made some optimizations to reduce this. Please report how the next version is performing.
