### ISSUE TITLE
1.19.4: multiplayer.disconnect.unsigned_chat

### ISSUE THREAD

**Issue by ClemenDev34** [kangarko/ChatControl#2407]
### "/version ChatControlRed" - plugin version

10.18.8

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

Since I put ChatControlRed my playre are disconnected when they type in chat whith this error : multiplayer.disconnect.unsigned_chat

**Comment by kangarko** [comment]
I apology I completely overlooked your message. This is unrelated to ChatControl, has to do something with your AntiPopup plugin, consult it with the other dev instead.
