### ISSUE TITLE
Books: JSON or MiniMessage support

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2408]
### Summary

I am trying to create custom books, which will have the ability to open links upon click as well as having some hover messages.
I was trying to use JSON or MiniMessage, but none of it works. I currently have no idea how to do it.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Well, I will probably need a custom plugin for it. But given ChatControl-Red's functionalities, it should be possible to do it.

**Comment by kangarko** [comment]
In the next version :)

![a](https://i.imgur.com/IjN8wtp.png)

You might will need to edit the file manually.

**Comment by Teslicek** [comment]
Unfortunately, there is a little bug. When using colors in hover text, it breaks.

**When using colors in hover text**
```
Pages: 
  - '<click:open_url:https://google.com><hover:show_text:"<#abcdef>Hover text"><#81C2FF><bold>[CLICK HERE]'
```
![image](https://github.com/kangarko/ChatControl-Red/assets/87967222/673d149c-d83b-4566-949f-ec42f26c1576)

**Without colors in hover text**
```
Pages: 
  - '<click:open_url:https://google.com><hover:show_text:"Hover text"><#81C2FF><bold>[CLICK HERE]'
```
![image](https://github.com/kangarko/ChatControl-Red/assets/87967222/cad5ab26-3489-42c0-af93-e9b4dc74a937)

**Comment by kangarko** [comment]
I don't know why, we are simply using MiniMessage API. Perhaps books do not support colored hovers? I might be wrong. Try without the \<\>

**Comment by Teslicek** [comment]
I think the problem lies in ChatControl's native color support. I think it is parsing the #81C2FF color before MiniMessage has the chance to detect it.

**Comment by kangarko** [comment]
Thanks, going to investigate when I get home on Monday

**Comment by Teslicek** [comment]
Bump, since Kangarko probably forgot.

The issue happens with any color in hover text, whether its hex, such as <#abcdef> or just normal <yellow\>.

Books do support colored (even hex) hover messages. It is just a little bug that happens with Chatcontrol's minimessage hover support. When no colors are present in the hover message, it works normally.

**Comment by kangarko** [comment]
You are correct, let me put a note about this and investigate
