### ISSUE TITLE
1.20.1: Variable Format Error {sender_is_discord}

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#2409]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hey, I’m trying to create a variable to display in-game tags however as expected it will not parse from discord as sender. I am receiving an error when adding the sender condition ‘is not discord’. How can I resolve this? Help is much appreciated.

Variable Format
https://pastebin.com/xs78X0NA

Error
https://pastebin.com/k19TdGX1

**Comment by kangarko** [comment]
Thanks, in the next version we should parse "is sender discord" before your JS variables.

**Comment by TZ122** [comment]
> Thanks, in the next version we should parse "is sender discord" before your JS variables.

Hey I still seem to be receiving the same error while using the newest jar.

Here is my setup
Error: https://pastebin.com/ap5mvYnt
Variable: https://pastebin.com/dEw7m3bQ

**Comment by TZ122** [comment]
> Thanks, in the next version we should parse "is sender discord" before your JS variables.

Hey I am now receiving this error when using is sender discord. 'java.lang.RuntimeException: Script execution failed for '!{sender_is_discord}'

Here is the error:
https://pastebin.com/3VGmGXWC

**Comment by kangarko** [comment]
Sorry for this, next version should fix this for all.
