### ISSUE TITLE
[Issue] Toggle worked only once

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#241]
I was able to do /toggle announcement once to ignore them, but undoing asks for the permission.

![image](https://user-images.githubusercontent.com/5664135/101290404-56a9f100-3802-11eb-8119-c69a68425342.png)

Now just using /toggle without arguments says I need the chatcontrol.command.toggle.announcement permission too.. 

I only want the players to toggle chat, pm, death and timed which they have the permission for.

So they do not have the announcement toggle, yet it worked once and is now stuck on it.

Minecraft 1.16.4 Tuinity
Bungee: true
MySQL: true

**Comment by kangarko** [comment]
Thanks, fixed.
