### ISSUE TITLE
1.19.4: /chc color menu don't work

### ISSUE THREAD

**Issue by dulee004** [kangarko/ChatControl#2410]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hello,
I have set player permissions for it. When the player types the command and selects what they want, it doesn't work, it doesn't apply in the chat.

I sent chc debug on mail

**Comment by kangarko** [comment]
Hey!

Make sure to put {chat_color} and {chat_decoration} to your format file, i.e. here is an example from formats/chat.yml:

![a](https://i.imgur.com/LrUKQCt.png)

**Comment by kangarko** [comment]
I see your debug file via email, you need to place these two variables here:

![a](https://i.imgur.com/m5Kvf1v.png)
