### ISSUE TITLE
Velocity: error in console "Couldn't pass PlayerChatEvent to velocitycontrol"

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/ChatControl#2411]
### "/version ChatControlRed" - plugin version

10.19.6

### Are you using MySQL?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/98b9da3bdb1d474ab0ea4fef583523a5

### "/chc debug" output (strongly recommended)

Hi, my CHC is updated, and my velocity control is too.   (VelocityControl-3.11.5-SNAPSHOT.jar)

I am wondering what this error is, please! 

Thank you for your support.

### Information about the issue/bug

I don't really what is producing the error in my console, So i can't tell you the exact steps sorry. I can only add that i am on 

Paper:    paper-1.20.1-96
Velocity: 3.2.0-SNAPSHOT

**Comment by james090500** [comment]
Something wrong with your velocitycontrol config I think. Either fix it or try delete and regenerate it.

**Comment by CtrlAiDel** [comment]
Thank you ill look into it.

**Comment by kangarko** [comment]
Closing, assuming fixed. Thanks James for a prompt reply. If you need more help simply reply below.

**Comment by CtrlAiDel** [comment]
It seems fixed indeed thank you.
