### ISSUE TITLE
1.20.1: One of my server is not showing prefix and color. Dunno why&?

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/ChatControl#2414]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

sorry text is short im injured right now to the right shoulder,

Hi everyone, i have problem with prefixes on one of my server, all the others sub server are working. CHC is up to date(ChatControl-Red-10.19.7.jar). Velocity control is updated too.

This is my ch list on my problematic server.  (second picture), the third picture is the ch list on a server that it is working:

this is from my settings.yml:

  List:
    standard:
      Format: chat
      Format_Spy: '@noprefix chat'
    admin:
      Format: admin-chat
      Format_Console: '[A-chat {player}] {message}'
    global:
      Format: chat
      Format_Spy: '@noprefix chat'
      Discord_Channel_Id: '1066182758357008445'
    es:
      Format: chat
      Format_Spy: '@noprefix chat'
    fr:
      Format: chat
      Format_Spy: '@noprefix chat'

I've got a second question, im acutally watching Matej video; and I am wondering how could I implemant the welcome screen with the face of my user please : )?!
Image # 4

PS: I've also tried to put 100% of my files plugin from my working server, to the non working server. Rebooted and it didn't worked.

I also tried to check permissions by permissions, I really don't get it :S  Sorry
These are the permissions in group default; on the non working server

This prefix is also in the permisssions of default prefix.0.&a&lPlayer &7&l- &3 and it works on every other server that i have. weird cant find why really,  

and I added the result in chat once more in the last picture: 
![1](https://github.com/kangarko/ChatControl-Red/assets/40178706/8e7ffe5a-c95e-46c0-ac65-fefe7c850f90)
![2](https://github.com/kangarko/ChatControl-Red/assets/40178706/85f8ad6d-36da-4639-8f48-bbbf2fcd6fa0)
![3](https://github.com/kangarko/ChatControl-Red/assets/40178706/98699066-9091-47ae-9281-bd6b15aa3e7d)
![4seconq](https://github.com/kangarko/ChatControl-Red/assets/40178706/7717a561-b5d4-428b-927f-ff3408aa86a4)
![5](https://github.com/kangarko/ChatControl-Red/assets/40178706/1f885ecf-99f1-4e02-a9b0-98e4dec86de0)
![6](https://github.com/kangarko/ChatControl-Red/assets/40178706/827de0c6-7043-4046-ba19-6bf349191f86)
![7](https://github.com/kangarko/ChatControl-Red/assets/40178706/8f7aa705-d6a6-4c22-847d-e210f43e0755)
![8](https://github.com/kangarko/ChatControl-Red/assets/40178706/6034ec02-7b34-4ab0-b9ee-5c0160e8da98)

**Comment by kangarko** [comment]
I am sorry, I am getting lost there.

**1. The prefix not showing**
Which prefix? Can you please upload your /chc debug from that server and from one other server that is working to compare? Something must be different...

2. The player head in format
You can use the Image_x keys in your chat format to display the head.

```yaml
# The parts of this format.
Parts:

  # Shows the head of the specified player before their messages
  player-head:
    Message: ""
    Hover: "{player}"
    Image_Head: "{player}"
    Image_Height: 10
    Image_Type: "LIGHT_SHADE"
```

**Comment by CtrlAiDel** [comment]
[debugworking main lobby.zip](https://github.com/kangarko/ChatControl-Red/files/12221734/debugworking.main.lobby.zip)
[debug hardcore not working.zip](https://github.com/kangarko/ChatControl-Red/files/12221735/debug.hardcore.not.working.zip)

I will check about the player head afterward. Since im injured, thank you for your support, sorry for the trouble

**Comment by CtrlAiDel** [comment]
![image](https://github.com/kangarko/ChatControl-Red/assets/40178706/3d549174-ffbf-441d-ba19-eb17756e8a92)
prefix is looking like that on other server :) Thanks

**Comment by kangarko** [comment]
Yes. So sorry, I had to leave office, will be getting back on you in 2-3 days max.
