### ISSUE TITLE
1.19.2: DiscordSRV Setup

### ISSUE THREAD

**Issue by MayDayRains** [kangarko/ChatControl#2415]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Heyo! I have configured my chat control with discordSRV so that only the selected channels would actually go through to discord, but now my discord channel wont send messages to in game, I was wondering if there was any settings in the settings/config that I would be able to check? or if anyone else has any ideas on how to fix this?

**Comment by kangarko** [comment]
I don't understand the question. When you configure ChatControl to have the Discord Channel ID at the selected channels, you will have two-way sync, meaning MC > Discord and Discord > MC.

Are you saying that Discord > MC does not work? Set your Debug key in settings.yml to "[discord]", restart and let me know the output when Discord message is written.

**Comment by MayDayRains** [comment]
Its Discord > MC that isn't working - I did what you said here are the latest logs - My apologies I normally don't work on dev side of things for our server c: 
[latest.log](https://github.com/kangarko/ChatControl-Red/files/12221515/latest.log)

**Comment by kangarko** [comment]
I am sorry the log is too large I cant find the specific message.

Only send me the debug when you type something on discord and it does not go through.

Also please attach your /chc debug so I can test this.

**Comment by MayDayRains** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/12222542/debug.zip)

This is what you are referring to correct?

**Comment by kangarko** [comment]
Yes. So sorry, I had to leave office, will be getting back on you in 2-3 days max.

**Comment by kangarko** [comment]
Okay, your file looks correct. Can you please open DiscordSRV/config.yml and set Debug key there to "[MINECRAFT_TO_DISCORD, DISCORD_TO_MINECRAFT]"? Thanks.

And btw, make sure you have DiscordChatChannelDiscordToMinecraft set to true in the same file.

Now, let me check your console. When you type a message in Discord and it does not go to Minecraft, let me know what you see in the console.

Here is how it looks like for me when everything is correctly setup:

![a](https://i.imgur.com/7dSHJZE.png)

**Comment by MayDayRains** [comment]
Thank you so much we got it fixed! You are the best! <3

**Comment by kangarko** [comment]
Happy to hear! Just let me know if you have anything else I can assist you with.
