### ISSUE TITLE
1.20.1 : \n or new line in chat format

### ISSUE THREAD

**Issue by Pattanawaris** [kangarko/ChatControl#2417]
### "/version ChatControlRed" - plugin version

10.19.9

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

-

### "/chc debug" output (strongly recommended)

-

### Information about the issue/bug

I use \n to try to config 2 line chat format but its seem to not working. is there a way to config a multiline chat format?

**Comment by kangarko** [comment]
Do not use \n, use '' on multiple lines:

![a](https://i.imgur.com/mm4xV5A.png)
