### ISSUE TITLE
Gradient support and per group message color

### ISSUE THREAD

**Issue by Pattanawaris** [kangarko/ChatControl#2418]
### Summary

please add feature to make a gradient text and per group chat color by permission just like prefix.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

its would be very cool if Chatcontrol have those features.

**Comment by kangarko** [comment]
We support gradients in formats, but not in the chat itself at the moment. Thanks for the suggestion!

Per-group chat color you can configure by duplicating format parts, see formats/chat.yml, and using Sender_Permission
