### ISSUE TITLE
1.20: /mute Not Working

### ISSUE THREAD

**Issue by gavnlmao** [kangarko/ChatControl#2419]
### "/version ChatControlRed" - plugin version

10.19.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

Muting a channel or server does not mute it.

To replicate:
/mute channel <channel> 15m
then /mute channel <channel> off
You get this error:
![image](https://github.com/kangarko/ChatControl-Red/assets/137229576/8e5cf715-2189-455c-8877-433fd90026fe)

The same thing happens for /mute server, but /mute player works.

**Comment by kangarko** [comment]
Thanks, fixed.
