### ISSUE TITLE
Relational Placeholders

### ISSUE THREAD

**Issue by MarkehMe** [kangarko/ChatControl#242]
Hello,

Can you support relational placeholders from PlaceholderAPI?

**Comment by MarkehMe** [comment]
Heres the update about it:

https://www.spigotmc.org/resources/placeholderapi.6245/update?update=167267

**Comment by kangarko** [comment]
Hello,

thank you for noticing and suggestion! However, this has been mentioned multiple times and it is on the roadmap already: https://github.com/kangarko/ChatControl-Pro/issues/267

Please note that ChatControl free is no longer receiving such updates. The roadmap is for the premium version.

**Comment by MarkehMe** [comment]
Cool! No worries. Was asking for someone using one of my plugins, was not aware there were seperate repos 👍
