### ISSUE TITLE
[Issue] Anti-Bot check not working correctly

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#242]
If you are AFK / Inactive for a couple of minutes and you start typing again it will say ''[X] Please move before typing in chat'', I assume this should only be on login like it was with ChatControl 8.

Minecraft 1.16.4 Tuinity
Bungee: true
MySQL: true

**Comment by kangarko** [comment]
Thanks, this problem occurred after 30-minutes and was fixed in the last release.

**Comment by Sikatsu** [comment]
> Thanks, this problem occurred after 30-minutes and was fixed in the last release.

This isn't fixed on today's release, it still occurs.

**Comment by kangarko** [comment]
Please post me your /chc debug file.

**Comment by Sikatsu** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5672771/debug.zip)

**Comment by kangarko** [comment]
let's continue here: https://github.com/kangarko/ChatControl-Red/issues/250
