### ISSUE TITLE
1.20.1 : Multiline chat format generate blank line output.

### ISSUE THREAD

**Issue by Pattanawaris** [kangarko/ChatControl#2420]
### "/version ChatControlRed" - plugin version

10.19.9

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

I'm using multiline chat format and when I add any text in front off {message} variable in chat.yml its seem that chat output come with blank line but if I move the text to come after {message} variable it works  just fine
<img width="664" alt="image" src="https://github.com/kangarko/ChatControl-Red/assets/22558449/77489b7c-e2a2-45d6-ba6d-8588ab1ec603">
<img width="676" alt="image" src="https://github.com/kangarko/ChatControl-Red/assets/22558449/5be2e6cf-1b85-4f08-8281-d26239579792">

<img width="303" alt="image" src="https://github.com/kangarko/ChatControl-Red/assets/22558449/9ba6d6d9-6934-47f4-8742-f4ffbc1de143">

**Comment by Pattanawaris** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/12281747/debug.zip)

Here's debug

More info: I've tried to solve this by myself by move - '' (multiline format)from line1 of message parts to line 2 player suffix parts instead (message part are now normal single line but player name and suffix are in multiline format instead and it came out that blank line are generated at first line in chat output instead of middle line and I Think maybe  its always generate blank line above part that are multiline and have text infront of variable)

Another issue I found is if I use negative-space unicode Hover feature will not working but I'm not sure if this is fixable.

**Comment by kangarko** [comment]
I am sorry, this seems like an internal limit for now. I'll try to tackle this on the next rewrite.
