### ISSUE TITLE
1.20.1 Variable on Format_Discord

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#2421]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello, 

I am trying to use a variable in Format_Discord which adds "Discord" in front of the players name (formatting on Discord chat end not minecraft chat). I have {tagdiscord} in Format_Discord but it parses as false when I send a message on discord. How can I have this return "Discord"?

Thanks!

Type: FORMAT

Key: "tagdiscord"

Value: |-
  getWord(); 

  function getWord() {     
      return "[ᴅɪsᴄᴏʀᴅ]";
  }

Sender_Condition: '{sender_is_discord}'

**Comment by kangarko** [comment]
Can you try using a format file in formats/ folder and then using Sender_Condition for the format part instead of the variable?

**Comment by TZ122** [comment]
Does Format_Discord support formats?   "# The default format only shown on Discord unless overriden below. Does not support formats."

I added the format to Format_Discord: '**{discordtagformat} {player}**: {message}'  however now it outputs like this "{discordtagformat} TZ122: test!" on discord

discordtagformat file:
Parts:
  message:
    Message: 'Discord'
    Sender_Condition: '{sender_is_discord}'

**Comment by kangarko** [comment]
Thanks, you're right. I'll fix that tonight.

Yes sorry for the wrong instruction, correct, Format_Discord does not support formats folder.

This will work in the next version:

![a](https://i.imgur.com/EIplrzM.png)
