### ISSUE TITLE
1.18.2: Open_Url does not support dynamic urls like adding {player}

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2422]
### "/version ChatControlRed" - plugin version

10.18.2

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

I know im outdated by a bit, but ive read the changelogs and cant see this fixed.

Trying to change when clicking a players name to open 
`Open_Url: 'https://piratemc.com/pirate/{player}'`
But for some reason Open_Url does not allow these placeholders, and does nothing, if I remove {player} the click event happens, which is annoying as I want it to click to open the players profile that I created unique for my server.

**Comment by kangarko** [comment]
Sorry for the annoyance, indeed I missed that. Fixed :) Going to push the new update in a few hours.

**Comment by kangarko** [comment]
Sorry for the annoyance, indeed I missed that. Fixed :) Going to push the new update in a few hours.
