### ISSUE TITLE
Please support the mention as a player's display name.

### ISSUE THREAD

**Issue by paiow** [kangarko/ChatControl#2424]
### Summary

Hello

Could you please add a function so that the mention system can be used as a display name?

Also, could you tell me how to get a list of players that the player ignored through API?

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

I can't use the player mention function on my server.
In my server, I use the nickname system with player's display name instead of player name.

I hope you support.

**Comment by kangarko** [comment]
Sure, I will! In the next version just listen to PlayerPreMentionEvent and use setNick to put your custom nick there.

As for the API, you can call PlayerCache.from(yourPlayer).isIgnoringPlayer(uniqueId) or SyncedCache.fromName(playerName).isIgnoringPlayer(uniqueId) if you are using Bungee.

**Comment by paiow** [comment]
Thank you!! Thank you for supporting the player's display name for the mention.

If I don't use bungee, should I call this PlayerCache.from(yourPlayer).isIgnoringPlayer(uniqueId)?

**Comment by kangarko** [comment]
> If I don't use bungee, should I call this PlayerCache.from(yourPlayer).isIgnoringPlayer(uniqueId)?
Yes

If you appreciated my support please drop a quick review, motivates me a ton :)
