### ISSUE TITLE
1.20.1 ChC and CMI formatting conflict

### ISSUE THREAD

**Issue by GreenFlameblade** [kangarko/ChatControl#2425]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

I am using Chat Control Red and CMI combined. It's working mostly well together, but I've encountered a few formatting conflicts. A problem I'm having is using CMI gradients in chat. For example, I write {#ffffff>}Message{#111111<} to create a gradient message, but it comes out as >}Message<}
![image](https://github.com/kangarko/ChatControl-Red/assets/118574096/c2791f25-22f2-488e-8ee2-2dfeed88da7c)
Nicknaming still works with CMI gradients since I'm using CMI nicknames
![image](https://github.com/kangarko/ChatControl-Red/assets/118574096/0af35e88-1617-41c5-b8d4-f5a00608b5d7)

So, I have two questions:

Is there a way to disable Chat Control Red's color formatting so that CMI can handle it? 

Or is there a way to get Chat Control Red to recognize this format?  {#hex>}Message{#hex<}

**Comment by kangarko** [comment]
Thank you for reporting. You can try changing https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities.

However if that wont work, then it's incompatible.  I am afraid the color replacing is quite deeply embedded in the plugin it's technically unfeasible to add a toggle. 

I have plans for adding chat gradients though :)

**Comment by GreenFlameblade** [comment]
Thank you. I experimented, and got it to function properly by setting listener priority to MONITOR and the CMI chat settings to
![image](https://github.com/kangarko/ChatControl-Red/assets/118574096/6b794d42-5ba0-4190-a4c3-51df6954d8f8)



![image](https://github.com/kangarko/ChatControl-Red/assets/118574096/a73dc196-1ad9-4c32-91ff-b8df5706976b)
Thank you again :-)

**Comment by kangarko** [comment]
Please post a quick review it really helps me to get going if you appreciated my support :)
