### ISSUE TITLE
1.18.2 How do i allow a bypass for adverting on one command?

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2426]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

My admins have use of //snap list and //snap use, the worldedit snapshot system for worlds.
https://worldedit.enginehub.org/en/latest/usage/snapshots/

But this is flagged as advertising, ideally I would like to have a whitelist to allow that command to just bypass the adverting system without giving full bypass for all adverting, what would be the best way to do this?

Using verbose I found out the global bypass is `chatcontrol.bypass.ad` which I can use for now.

Im assuming this comes under the IP filter.

And im assuming I have to edit my global.rs and add a "ignore event" somehow for a command?
Or is there a main config option for whitelist of commands?

for some reason my IP filter is this large of a regex
```
# IP filter. 
match [0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}
name ip
ignore event signs
# Remove the specified characters using regex (or replace them with dots) BEFORE the message is checked.
before replace dot|\[|\]|\{|\}|\(|\) with .
before replace [\(\[\]\)]|\s*
before replace ((\{|\[|\(|<){1,2}(dot|.)?(>|\)|\]|\}){1,2}) with .
group advertisement
```

**Comment by kangarko** [comment]
Have you tried the "ignore command" operator?

![a](https://i.imgur.com/90gL3hU.png)

**Comment by TomLewis** [comment]
Ah this is what I need then! Why couldn't my brain see that in the docs, I did check! I will try this, thanks.

**Comment by kangarko** [comment]
Prob because they are clunky. I wished to have the time to make the plugin simpler. Let me know if that works and if you have more questions!

**Comment by TomLewis** [comment]
ok that worked, but I saw that I can also add a bypass for channels, I tried to add a bypass for my admin channel but it still flags for IP/website advertising.
Its a read channel, that you have to use /ho to message into if this helps.


edit; I tried adding
`ignore channel admin read`
But this ended up being a FULL bypass to any channel, I just want them to be able to use URLS and IPs in the admin channel only.

**Comment by kangarko** [comment]
Try "ignore channel admin write" instead.

**Comment by TomLewis** [comment]
Sadly not

**Comment by kangarko** [comment]
How do you have it? I can't reproduce having placed the ignore operator in groups.rs >

![a](https://i.imgur.com/EUioAEU.png)

**Comment by TomLewis** [comment]
```
# IP filter. 
match [0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}
name ip
ignore event signs
ignore command /snap|/snapshot|/restore
ignore channel admin write
# Remove the specified characters using regex (or replace them with dots) BEFORE the message is checked.
before replace dot|\[|\]|\{|\}|\(|\) with .
before replace [\(\[\]\)]|\s*
before replace ((\{|\[|\(|<){1,2}(dot|.)?(>|\)|\]|\}){1,2}) with .
group advertisement
```

**Comment by kangarko** [comment]
Place the ignore channel to the group itself please.
