### ISSUE TITLE
1.12.2: Plugin does not work as it's expected

### ISSUE THREAD

**Issue by MatinHQ** [kangarko/ChatControl#2427]
### "/version ChatControlRed" - plugin version

10.20.2

### Are you using MySQL?

Yes

### "/chc debug" output (strongly recommended)

I will mail it

### Information about the issue/bug

When players chat in the server nothing appears, I checked console there is no error also player chats are visible on console but nothing will send in game

Also other commands like /chc does not have any output when I run them in the game but in console is just fine

![image](https://github.com/kangarko/ChatControl-Red/assets/22664859/00baff19-e565-4c9f-af92-178636a93125)
![image](https://github.com/kangarko/ChatControl-Red/assets/22664859/83ef1c51-6f7d-49f5-950b-5a4c7a1d91ad)

**Comment by james090500** [comment]
Are you sure your chat isn't turned off or set to secure only?

I think its

ESC > Options > Chat Settings

**Comment by MatinHQ** [comment]
No it's off

**Comment by james090500** [comment]
Then you'll need to turn your chat on.

**Comment by MatinHQ** [comment]
How can enabling only secure chat help me solve this issue I don't want to see only secure chats

**Comment by kangarko** [comment]
There is no secure chat option on Minecraft 1.12, James. Actually we do not support secure chat (for 1.19+) so that needs to be OFF.

I tested this on 1.12 with these chat settings:

![a](https://i.imgur.com/Avt1fhc.png)

And was able to see the chat normally (tested via Bungee)

![a](https://i.imgur.com/OYv8gfD.jpeg)

Can you try connecting directly to the server without Velocity to see if that works? I am unable to test Velocity at the moment. But if that will work then it's likely you have a plugin at Velocity that's blocking our chat.

**Comment by MatinHQ** [comment]
Unfortunately, we can't directly connect to servers via port, due some network limitation applied for security reasons

**Comment by kangarko** [comment]
@james090500 I can partially reproduce when switching channels, I do not see a "x joined y channel message", nothing.

To reproduce:
1. Type /ch
2. Click on the up arrow to start writing in the another channel.
3. You should get a chat message but nothing is printed to chat:

This is what you should get in chat (using default setup):
![b](https://i.imgur.com/x72TOTf.png)

Instead nothing happens when via Velocity:

![a](https://i.imgur.com/WY7EjBm.png)

**Comment by james090500** [comment]
Must be a typo on my behalf. I meant make sure CHAT is on and SECURE CHAT is off

**Comment by MatinHQ** [comment]
Any news on this?

**Comment by MatinHQ** [comment]
Also I have another gamemode which is 1.18.2 and it has same issue

![image](https://github.com/kangarko/ChatControl-Red/assets/22664859/09355cb7-4245-4d5a-9a28-0869476df94d)

**Comment by kangarko** [comment]
@james090500 any ETA on fixing this please?

**Comment by MatinHQ** [comment]
Can you guys please, put this issue on priority whole purpose of chat control is controlling chat, but if plugin makes the chat no longer works there is no reason to be used

**Comment by james090500** [comment]
I have been away from home. I know the notification message isn't working properly but this does not stop chat working.

This sounds either like a config or environment bug at the moment.

What versions are you running and can you try on a test environment with a blank config then with your config

**Comment by MatinHQ** [comment]
> I have been away from home. I know the notification message isn't working properly but this does not stop chat working.
> 
> This sounds either like a config or environment bug at the moment.
> 
> What versions are you running and can you try on a test environment with a blank config then with your config

I already sended full config files to support email and I had no issue so far, I have been using chat control for 8 month or so and nothing changed except regex for detecting swears

**Comment by kangarko** [comment]
@james090500 did you try my reproduction steps? I found a simple way to find the bug, thanks.

**Comment by james090500** [comment]
I am aware of the bug. But this is more of a visual issue. It does not effec the actual joining or messages etc.

The issue with the OP not being able to send messages is something completely different but I can't replicate.

**Comment by TheWylot** [comment]
Hey, i have same issue currently

**Comment by james090500** [comment]
> Hey, i have same issue currently

The issue of no player messages appearing in chat?

Send your config.

**Comment by TheWylot** [comment]
`Channels:
  Enabled: true
  Ignore_Worlds:
  - pvp
  Command_Aliases:
  - channel
  - ch
  Max_Read_Channels: 3
  Join_Read_Old: true
  Ignore_Autojoin_If_Left: true
  Autojoin_On_Reload: false
  Format_Console: '[{channel}] {player}: {message}'
  Format_Discord: '**{player}**: {message}'
  Antispam_Broadcast_Threshold: 1 second
  Ranged_Channel_No_Near_Player_Delay: 3 seconds
  Save_To_Database: true
  Alternative_Console_Sending: true
  List:
    towny:
      Format: chat
      Format_Spy: '@noprefix chat'
      Bungee: true
    admin:
      Format: admin-chat
      Format_Console: '[A-chat {player}] {message}'
      Bungee: true
Anti_Spam:
  Similarity_Ignore_Accents: true
  Chat:
    Delay: 3 seconds
    Similarity: 0%
    Similarity_Past_Messages: 2
    Similarity_Time: 10 seconds
    Whitelist_Delay: []
    Whitelist_Similarity:
    - ^hello \w+$
    - ^hey \w+$
    - ^hi \w+$
    Limit:
      Period: 0 seconds
      Max_Messages: 4
    Parrot:
      Enabled: false
      Delay: 1 second
      Similarity: 85%
      Whitelist:
      - ^(hello|hey|hi)( \w+|)(!|)$
  Commands:
    Delay: 3 seconds
    Similarity: 0%
    Similarity_Past_Commands: 1
    Similarity_Time: 10 seconds
    Whitelist_Delay: []
    Whitelist_Similarity:
    - /tag
    - /nick
    Limit:
      Period: 0 seconds
      Max_Commands: 4
Anti_Caps:
  Enabled: true
  Enabled_In_Commands:
  - - '*'
  Min_Message_Length: 5
  Min_Caps_Percentage: 50
  Min_Caps_In_A_Row: 5
  Whitelist:
  - OMG
  - LOL
  - WTF
  - WOW
  - ROFL
Anti_Bot:
  Block_Chat_Until_Moved: false
  Block_Commands_Until_Moved: []
  Block_Same_Text_Signs: false
  Disallowed_Usernames:
    List:
    - Notch
    Commands: []
  Cooldown:
    Rejoin: 0 seconds
    Chat_After_Login: 0 seconds
    Command_After_Login: 0 seconds
  Join_Flood:
    Enabled: false
    Join_Threshold: 5 seconds
    Min_Players: 3
    Commands:
    - /kick {player} You've been kicked because your '{message}' message matched what {player_amount} player(s) wrote in {threshold}.
Tab_Complete:
  Enabled: false
  Use_Nicknames: true
  Prevent_If_Below_Length: 0
  Whitelist:
  - '@blacklist'
  - (/ver|/version)\b
  - (/pl|/plugins)\b
  - /hiddenCommand
Grammar:
  Insert_Dot_Message_Length: 0
  Capitalize_Message_Length: 0
Rules:
  Apply_On:
  - chat
  - command
  - packet
  - sign
  - book
  - anvil
  - tag
  Verbose: true
  Strip_Colors: true
  Strip_Accents: true
  Case_Insensitive: true
  Unicode: true
  Regex_Timeout_Ms: 500
Private_Messages:
  Enabled: true
  Bungee: true
  Toasts: false
  Sound: ENTITY_CHICKEN_EGG 1F 1.5F
  Auto_Mode: true
  Disabled_By_Default: false
  Auto_Mode_Leave_Threshold: 5 minutes
  Tell_Aliases:
  - tell
  - w
  - m
  - t
  - pm
  - message
  - msg
  - whisper
  Reply_Aliases:
  - reply
  - r
  Sender_Overrides_Receivers_Reply: true
  Format_Sender: pm-sender
  Format_Receiver: pm-receiver
  Format_Toast: '&7PM from &6{sender}:|&f{message}'
  Format_Console: '[pm] {sender} -> {receiver}: {message}'
Messages:
  Apply_On: []
  Stop_On_First_Match:
  - join
  - quit
  - kick
  - death
  - timed
  Prefix: {}
  Discord: {}
  Defer_Join_Message_By: 1 tick
  Delay_Until_Resource_Pack_Loaded: false
  Timed_Delay: 10 seconds
  Async: []
Colors:
  Apply_On:
  - chat
  - me
  - prefix
  - nick
  - suffix
  - private_message
Sound_Notify:
  Enabled: true
  Cooldown: 10 seconds
  Require_Afk: false
  Require_Prefix: '@'
  Sound: ENTITY_CHICKEN_EGG 1F 1.5F
  Color: '&a'
Me:
  Enabled: false
  Command_Aliases:
  - me
  Format: '&7* &o{player_name} {message}'
List:
  Enabled: false
  Command_Aliases:
  - list
  - ls
  - l
  Format: ' &7{count}. &f{player_name}'
  Format_Hover:
  - '&7Server: &f{player_server}'
  - '&7Nick: &f{player_nick}'
  - '&7Vanished: &f{player_is_vanished}'
  - '&7Channels: &f{player_channels}'
  Sort_By: group
Ignore:
  Enabled: true
  Bidirectional: false
  Command_Aliases:
  - ignore
  - ig
  Hide_Chat: true
  Stop_Private_Messages: true
Mute:
  Enabled: false
  Broadcast: true
  Command_Aliases:
  - mute
  Prevent_Commands:
  - /tell
  - /w
  - /m
  - /t
  - /pm
  - /message
  - /msg
  - /whisper
  - /mail
  - /reply
  - /r
  - /me
  Prevent_Writing_Books: true
  Prevent_Placing_Signs: true
  Prevent_Anvil_Renaming: true
  Hide_Join_Messages: true
  Hide_Quit_Messages: true
  Hide_Death_Messages: true
  Soft_Hide: false
Motd:
  Enabled: false
  Async: false
  Delay: 3 ticks
  Command_Aliases:
  - motd
  - news
  Format_Motd: motd
  Format_Motd_First_Time: motd
  Format_Motd_Newcomer: motd
  Sound: ENTITY_FIREWORK_LAUNCH 1F 0.1F
  Commands:
    Console: []
    Player: []
Announcer:
  Chat_Sound: ENTITY_ARROW_HIT_PLAYER 1.0F 0.1F
Mail:
  Enabled: false
  Command_Aliases:
  - mail
  - email
  - post
  - gmail
Tag:
  Apply_On:
  - nick
  Command_Aliases:
  - tag
  - settag
  Backward_Compatible: false
  Max_Nick_Length: 20
  Nick_Prefix: ''
  Nick_Disable_Impersonation: true
  Change_Displayname: true
Real_Name:
  Command_Aliases:
  - realname
  - realn
  - rn
Tab_List:
  Enabled: false
  Format: '{player_prefix+}{player_nick}'
Toggle:
  Apply_On:
  - chat
  - mail
  - announcement
  - me
  - pm
  - soundnotify
  Command_Aliases:
  - toggle
  - tg
Spy:
  Apply_On:
  - chat
  - command
  - private_message
  - mail
  - sign
  - book
  - anvil
  Prefix: '&8[&5Spy&8] '
  Command_Aliases:
  - spy
  Format_Chat: '@noprefix spy'
  Format_Party_Chat: '@noprefix spy-party'
  Format_Command: '&7{player}: &f{message}'
  Format_Private_Message: '&7{sender} &8-> &7{receiver}: &f{message}'
  Format_Mail: spy-mail
  Format_Sign: spy-sign
  Format_Book: spy-book
  Format_Anvil: spy-anvil
  Commands:
  - '@blacklist'
  - /register
  - /reg
  - /login
  - /l
Groups:
  admin:
    Message_Delay: 0 seconds
Warning_Points:
  Enabled: false
  Reset_Task:
    Period: 10 minutes
    Remove:
      global: 2
      spam: 1
      fastmessages: 1
  Triggers:
    Chat_Delay: fastmessages 3 - {remaining_time}
    Chat_Similarity: spam 4 * ({similarity_percentage_double} / 2)
    Chat_Limit: fastmessages 2
    Command_Delay: fastmessages 3 - {remaining_time}
    Command_Similarity: spam 4 * ({similarity_percentage_double} / 2)
    Command_Limit: fastmessages 3
    Caps: spam 4 * ({caps_percentage_double} / 2)
  Sets:
    global:
      '3':
      - warn &7You must obey the &2rules &7else you will be &4punished&7.
      '10':
      - warn &c**** &lHey &c{player} ****
      - warn &7-> &cThis is your &6final &cwarning!
      '30':
      - kick {player} &cKicked for breaking the rules
    swear:
      '3':
      - warn &cYou have received first warning for swearing.
      '6':
      - warn &cPlease do not swear, otherwise an action will be taken!
      '8':
      - kick {player} &cInappropriate language (last warning)
    spam:
      '6':
      - warn &cPlease do not act like a spammer.
      '10':
      - warn &cPlease do not spam, otherwise you will be banned.
      '12':
      - kick {player} &cSpamming the chat (last warning)
    fastmessages:
      '8':
      - warn &cPlease slow down chat messages.
      '12':
      - warn &cSlow down chat, otherwise you will be banned.
      '16':
      - kick {player} &cSlow down chat (last warning)
Newcomer:
  Threshold: 0 minutes
  Worlds:
  - '*'
  Permissions:
  - chatcontrol.group.newcomer
  - chatcontrol.spy.autoenable - false
  Warning_Points_Multiplier: 2.0
  Restrict_Seeing_Chat: false
  Restrict_Chat:
    Enabled: false
    Whitelist: []
  Restrict_Commands:
    Enabled: false
    Whitelist:
    - /login
    - /l
    - /register
    - /reg
    - /helpop
    - /help
    - /?
Log:
  Apply_On:
  - chat
  - command
  - private_message
  - mail
  - sign
  - book
  - anvil
  Clean_After: 60 days
  Command_List:
  - /tell
  - /w
  - /m
  - /t
  - /pm
  - /message
  - /msg
  - /whisper
  - /mail
  - /reply
  - /r
  - /me
  - /tag
  - /nick
Console_Filter:
  Enabled: false
  Messages:
  - Reached end of stream for
  - Connection reset
Integration:
  AuthMe:
    Delay_Join_Message_Until_Logged: false
    Hide_Quit_Message_If_Not_Logged: true
  BungeeCord:
    Enabled: true
    Prefix: ''
  Discord:
    Enabled: false
    Filter_Chat: true
    Remove_Emojis: true
    Webhook: false
    Send_Messages_As_Bot: true
    Forward_From_Bungee: false
  ProtocolLib:
    Listen_For_Packets: true
    Book_Anti_Crash: true
  TownyChat:
    Spy_Channels_Whitelist:
    - '@blacklist'
Show_Tips: true
Register_Tools: false
Strip_Oversized_Json: true
Timestamp_Format: dd.MM.yyyy HH:mm:ss
Chat_Listener_Priority: HIGH
Command_Aliases:
- chc
- chatcontrol
Locale: en
Prefix: ''
UUID_Lookup: false
Clear_Data_If_Inactive: 60 days
Clear_Cache_On_Disconnect: false
Log_Lag_Over_Milis: 100
Debug: []
Version: 32`

**Comment by TheWylot** [comment]
as github doesnt accept yml files. i will send it using txt format
[config.txt](https://github.com/kangarko/ChatControl-Red/files/12570722/config.txt)

**Comment by james090500** [comment]
We will need the full config to replicate. And please say the full issue you're facing.

**Comment by james090500** [comment]
Closing due to lack of response.

**Comment by MatinHQ** [comment]
Lack of response?

**Comment by MatinHQ** [comment]
Did you try ask me anything? I send you all required files explained you everything i could also kangarako gave you a repro and you say about lack of response?

**Comment by TheWylot** [comment]
> Did you try ask me anything? I send you all required files explained you everything i could also kangarako gave you a repro and you say about lack of response?

even when i sent the config file. they just asked it again.

**Comment by kangarko** [comment]
@james090500

**Comment by james090500** [comment]
@kangarko if they've emailed the configs to you please send them on discord to me.

@MatinHQ you never replied to my message asking you to test in a separate environment with brand new configs.

Basically

1. Spin up a new server, install CHC does /chc output in chat?

2. If it does, try with your existing config on a brand new server, does /chc output anything.

If it does, another plugin on your existing server is causing chc to stop working. 

To add, the bug with notifications that says "you joined a Chanel" is visual, I am trying to look into it but even if it doesn't say "you joined the channel" you still join it.

The bigger issue you described is /chc not working and chat not displaying.

**Comment by TheWylot** [comment]
> as github doesnt accept yml files. i will send it using txt format
> [config.txt](https://github.com/kangarko/ChatControl-Red/files/12570722/config.txt)
> 

@james090500 just click on config.txt here (then reformat it to yml.)

**Comment by james090500** [comment]
> > as github doesnt accept yml files. i will send it using txt format
> > [config.txt](https://github.com/kangarko/ChatControl-Red/files/12570722/config.txt)
> > 
> 
> @james090500 just click on config.txt here (then reformat it to yml.)

We don't need 1 yml. We need the entire config folder
