### ISSUE TITLE
Spigot 1.20: Issue with chatbots

### ISSUE THREAD

**Issue by lukesiddons5** [kangarko/ChatControl#2428]
### "/version ChatControlRed" - plugin version

10.19.4

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/12373931/debug.zip)

### Information about the issue/bug

The chatbots are not working at all.

**Comment by kangarko** [comment]
What do you mean by "The chatbots are not working at all."? Provide example and steps to reproduce below.

**Comment by lukesiddons5** [comment]
sorry for the poor description of the issue. The chat rules are seem to be completely disabled if I type one of the rules it just doesn't work. For example chat bots just seem to not work. Im also sorry if this does not give you enough information its difficult for me to explain

**Comment by kangarko** [comment]
It says you need to agree with the terms of the plugin first:

![a](https://i.imgur.com/5zPbe00.png)

Type /chc tour mothman

Then it worked for me when I was non-OP:

![a](https://i.imgur.com/YtvWRXM.png)

**Comment by kangarko** [comment]
Hope that helps!
