### ISSUE TITLE
1.20.1: then log not saving color formats

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2432]
### "/version ChatControlRed" - plugin version

10.20.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

Sometimes, when my players use /nick or /itemname, they get flagged for something in swear filter, but when I check the log files, there is only text, such as `/itemname Hello`. After further testing, I realized that since it only happens in /itemname and /nick commands, players are using colors, but the colors are not saved in the {original_message} variable. I would like the `then log` rule to also log colors, since it is a part of {original_message}.

**Comment by kangarko** [comment]
Thanks, due to technical limitation this needs more work. I'll have to put it to later due to lack of time for now.
