### ISSUE TITLE
1.20.1: Sound_Notify

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [kangarko/ChatControl#2433]
### "/version ChatControlRed" - plugin version

10.20.2

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

Hello, I'm experiencing the problem that when I tag someone in chat, sometimes it doesn't tag the player that day. It's a small chance, but about 20% for sure. Thank you

I'm attaching photos and settings

Sound_Notify:

  Enabled: true

  Cooldown: 0 seconds

  Require_Afk: false

  Require_Prefix: ''
  
  Sound: ENTITY_CHICKEN_EGG 1F 1.5F

  Color: '&a'

![Snímek obrazovky 2023-08-20 202256](https://github.com/kangarko/ChatControl-Red/assets/68572049/3292702d-c7d7-4628-86bd-9e1c8e0d308c)
![2](https://github.com/kangarko/ChatControl-Red/assets/68572049/29150782-4ff0-4636-9166-6c4e4d817b9c)
![3](https://github.com/kangarko/ChatControl-Red/assets/68572049/c3ce816f-a7b3-487d-9bda-9755719e71ba)

**Comment by kangarko** [comment]
Pridal som do pluginu debug, prosím nastav Debug kľúč v settings.yml na [sound-notify] a napíš mi presne, keď to nepôjde, že čo píše v konzole.

Ale niečo som tam opravil, malo by to už ísť.

**Comment by Sh3r1ffCZ** [comment]
Již to funguje, děkuji :3

V konzoli to píše jen:
[17:50:32 INFO]: [sound-notify] Attempting to find sound notify tags in BeneG_'s message 'Sh3r1ffCZ'
[17:50:32 INFO]: [sound-notify] Ignoring BeneG_ due to equals to sender OR vanished OR afk
[17:50:32 INFO]: [sound-notify] Found Sh3r1ffCZ using '\b(Sh3r1ffCZ)($| |\.|\,|\?|\!|\:)'? true
[17:50:32 INFO]: BeneG_: Sh3r1ffCZ

**Comment by kangarko** [comment]
Found znamena ze to naslo, a teda funguje :)
