### ISSUE TITLE
1.20.1: Javascript gone wrong after update

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2434]
### "/version ChatControlRed" - plugin version

10.20.2

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://pastebin.com/SF9fgBsC

### Information about the issue/bug

Updated from 10.20.1 to 10.20.2 and my chat javascript is screwed and displays an error after each message.

**Comment by kangarko** [comment]
Sorry for this, please post your /chc debug so I can investigate asap.

**Comment by kangarko** [comment]
Fixed
