### ISSUE TITLE
1.19.4: Kicking all Java players

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2435]
### "/version ChatControlRed" - plugin version

10.19.1 (but by changelogs it seems it wasn't fixed yet)

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/855c735e7e1041d29cfc4a603c8321ab

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/12402135/debug.zip)

### Information about the issue/bug

When someone on bedrock (via geyser) types a chat over or exactly 259 characters it causes this error

**Comment by kangarko** [comment]
Thanks, should be fixed in the next version.
