### ISSUE TITLE
{player_nick} cannot display Essentials' nick

### ISSUE THREAD

**Issue by gary81013** [kangarko/ChatControl#2436]
### "/version ChatControlRed" - plugin version

10.21.0

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

{player_nick} cannot display Essentials' nick

**Comment by kangarko** [comment]
Set this option to true please:

![a](https://i.imgur.com/cbmSBrr.png)

**Comment by gary81013** [comment]
Thanks
