### ISSUE TITLE
[item] 

### ISSUE THREAD

**Issue by noaskers** [kangarko/ChatControl#2438]
### "/version ChatControlRed" - plugin version

10.19.1

### Are you using MySQL?

No

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

Not really a debug

### Information about the issue/bug

Idk realy now if this bug but you can put [item] multiple times in chat so people can just bypass the spam

**Comment by noaskers** [comment]
![image](https://github.com/kangarko/ChatControl-Red/assets/90572779/6817d8ab-3d1d-4b8e-ad83-2c62c0bfb8c5)
Tried this tried alot but can't find a way to justs limit it to 1 per message and to also disable unicode in it 

![image](https://github.com/kangarko/ChatControl-Red/assets/90572779/c711b0e8-3c1c-4d09-b0f8-10970d87d765)

**Comment by kangarko** [comment]
You can place this filter to chat.rs:

```
match (\[item\])\s*(?:\1\s*)+
then warn &cCannot use the item variable more then once per message.
then deny
```
