### ISSUE TITLE
ChatControl /Kicked For Spamming Commads 

### ISSUE THREAD

**Issue by Foxgamer201** [kangarko/ChatControl#244]
Look i Have tryed and tryed nothin but can you help me 

 
![ec](https://user-images.githubusercontent.com/31118621/29441932-aa01ccc4-839c-11e7-90d9-929396908a99.png)
 i have Mycmd i made it open a ederchest 

Then This heppens.....

![screenshot_1](https://user-images.githubusercontent.com/31118621/29441944-bef0b780-839c-11e7-80a4-1fc1da0f46de.png)

![screenshot_2](https://user-images.githubusercontent.com/31118621/29441959-d058f71c-839c-11e7-900d-9b55b959a6db.png)

**Comment by kangarko** [comment]
Hey,

this is not caused by ChatControl, I am sorry. ChatControl by default does not have this messages. See if you have for example NoCheatPlus+ configured as such.
