### ISSUE TITLE
[Issue] Nick already in use

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#244]
When I use `/tag nick &cLib` and then decide I want a different color code like `&eLib`, it says the nickname is already in use. If it's my own nickname, this should definitely overwrite. I even did `/tag nick &eLibe` and then tried `/tag nick &eLib` but it still said it's in use.

Minecraft 1.16.4
Bungee: true
MySQL: true

**Comment by kangarko** [comment]
Thanks, fixed!

**Comment by Sikatsu** [comment]
@kangarko This does not seem to be fixed on 10.1.17:

When using /tag nick &eLib and then /tag nick &cLib it still says the name is in use, even tho I wanna overwrite the nick color for myself. Which I think should work?

![image](https://user-images.githubusercontent.com/5664135/101361324-1fd5e880-389f-11eb-9a73-4a5a6f071fd9.png)

**Comment by kangarko** [comment]
Are you on the latest ver?  Cannot reproduce. My non-nicked name is "kangarko" and I tried all three combinations:

![a](https://i.imgur.com/qJm4Ifk.gif)

Btw there is an issue on the latest version that will get patched tonight so you can try that instead.

**Comment by Sikatsu** [comment]
Yeah, on the latest version of course. Actually odd that it doesn't work for me then.
What was the issue you found?

**Comment by kangarko** [comment]
No issue, but I changed the code 2 versions ago. Okay so what is your non-nicked name you were trying to change?

**Comment by Sikatsu** [comment]
I had &cLib, but didn't have the &c color code permission so it resulted in just Lib. Then when I did &eLib (had the permission for yellow) it said the name is already in use. So I did &eLibe and then &eLib but it said Lib was still in use.. not sure if related to color codes, but that's what I tested.

**Comment by kangarko** [comment]
Still cannot reproduce even if lacking color perms:

![a](https://i.imgur.com/fj1T7X3.gif)

Please tell me the following:

1. What is your non-nicked name? The one you are connected to the server with, not your nick.
2. The exact sequence in which these are executed

**Comment by Sikatsu** [comment]
The non-nicked name is Libertatia. Is this perhaps related to a permission so they can overwrite their nickname?
The exact steps I listed in the message above

**Comment by Sikatsu** [comment]
![image](https://user-images.githubusercontent.com/5664135/101787328-409c7900-3aff-11eb-9198-135ef8e51194.png)

When I logged in my nick was set as &cLibe, I changed it to &cLib, now performing &cLibe says the nickname is already in use.
After a server restart it seems Libe is back available, but I still can't change the color code of Lib..

Have you been testing this with mysql?

![image](https://user-images.githubusercontent.com/5664135/101787510-75a8cb80-3aff-11eb-8443-92101ffd2336.png)

**Comment by kangarko** [comment]
Thank you, I finally found this problem and made the checking mechanism not take into account capitalization or colors.
