### ISSUE TITLE
1.8.9 : Join Event lag spike

### ISSUE THREAD

**Issue by ZeroTwoO2** [kangarko/ChatControl#2440]
### "/version ChatControlRed" - plugin version

10.20.1

### Are you using MySQL?

Yes

### Error log (if applicable)

There is no error log

### "/chc debug" output (strongly recommended)

https://ufile.io/58nyutz1 - **_BEDWARS ARENA_**
https://ufile.io/bl8a8npa - **_BEDWARS LOBBY_**

### Information about the issue/bug

When players are joining, there are lag spikes. I've read some stacktraces, and it shows that ChatControlRed could be the issue.

**Comment by kangarko** [comment]
Please update to 10.21.1.

Plus, you only provided debug.zip which is not enough, I need to see all of the stack traces and spark profiler with the lag spikes themselves to identify and fix them.
