### ISSUE TITLE
1.20.1: Book Color Codes

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2442]
### "/version ChatControlRed" - plugin version

10.21.0

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/12446638/debug.1.zip)

### Information about the issue/bug

Going to keep this separate from my other issue to make things easier. After updating from 10.19.0 to 10.21.0, all color codes that I use in my Books folder created by ChatControl don't function. Neither the hex codes or regular Minecraft ones like &a or &l.
![image](https://github.com/kangarko/ChatControl-Red/assets/64336395/030b1b2c-9175-4333-8a80-88860dbc16ca)

**Comment by kangarko** [comment]
Correct. Sorry for the confusion. We have adopted a new MiniMessage format. I have added a toggle so you can disable this in the new version:

![a](https://i.imgur.com/N1v6b2F.png)
