### ISSUE TITLE
1.20: graidant usage in chat

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#2443]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

hi, just a fast question
i can use rgb in chat with &#RRGGBB but how use a gradiant in my chat ?

**Comment by kangarko** [comment]
Hey!

Yes as a format part, but not for players. This is something we'd like to add in the future.
