### ISSUE TITLE
1.20.1: Itemsadder custom sounds support?

### ISSUE THREAD

**Issue by goldenartur** [kangarko/ChatControl#2444]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

I have a question if u have itemsadder sounds support. I want to replace the default sounds with my own custom ones, is there a easy way to do it?

**Comment by kangarko** [comment]
We support ItemsAdder items, not sure about sounds to be honest. I have never dealt with it, you can ask his author instead.
