### ISSUE TITLE
Shift+Click formatting options 

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2446]
### Summary

Hi All!

It would be great to implement shift+clicking options, normal click runs command, shift+click opens URL for example.]

Im not entirely sure if Minecraft allows Shift+click event in chat, Its definitally part of GUIs, so this may just not be possible.

This would allow admin/mod based tasks on for example clicking a username in chat, normal click is normal behavior, shift+click lets you run the mod task, we really dont like a cluttered chat, so adding in more prefixes or suffixes are not the behavior we want, clean as possible.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Would have to make chat uglier with a character in line with the rest of each message, or have a GUI open using another plugin and require an extra click to get to the mod menu.

**Comment by kangarko** [comment]
Can you please check if that is possible on the client? Have seen any other plugin do it? If not someone could just make a client mod connecting to our APIs, unfortunately thats not something I have time for at the moment.

**Comment by TomLewis** [comment]
Dont think its possible after some googling :(
lame

**Comment by kangarko** [comment]
Oh that's a pity! Sorry about it!
