### ISSUE TITLE
Faction chat parties (Add ally,truce,enemy, faction mod)

### ISSUE THREAD

**Issue by goldenartur** [kangarko/ChatControl#2447]
### Summary

ChatControl has factions party where u can speak with only your faction, but it would be nice, if the same could be done with Ally, Truce, Enemy, or faction mod chat which are all also in the factions plugins implemented. Imo im dumb at coding but if you already have factions only chat implemented then it should be the same process with other ones that excist in faction plugins?

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Right now only the Faction chat works, but all faction servers also have truce, ally etc chats so its a bit annoying and unneccessary to convert one chat but not being able to convert others. If it's been done with faction chat then it shouldnt be any different for other factions related chats.

**Comment by kangarko** [comment]
Thanks, I'll have a look in 24h

**Comment by kangarko** [comment]
Which factions plugin you are using?

**Comment by goldenartur** [comment]
im using saberfactions

**Comment by kangarko** [comment]
Leaving open for future implementation, right now no ETA.

**Comment by MotikaCraft-TheJoshua** [comment]
I think this should be separate plugin. Not related to CHCRed, just my opinion.

**Comment by kangarko** [comment]
Possibly, chatcontrol's getting clunky and I am interested in deleting stuff rather than adding because it already has a learning curve for beginners

**Comment by kangarko** [comment]
Sorry this wont get added due to lack of time tbh, if anyone is willing to aid with development just contact me

**Comment by MotikaCraft-TheJoshua** [comment]
> Sorry this wont get added due to lack of time tbh, if anyone is willing to aid with development just contact me

if anyone need factionchat plugin recoded (1.8-1.12) from James (well known FactionChat plugin from bukkit) contact me, i can provide you jar, i can also publish it on github, i just use it for my own server and it has full support for FactionsUUID & SaberFactions, fixed everything

I really think this is out of scope for CHC.
