### ISSUE TITLE
1.20.1: Unhandled exception listening to AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by houtblok** [kangarko/ChatControl#2448]
### "/version ChatControlRed" - plugin version

10.21.4

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://gist.github.com/houtblok/53556b6253aa70746b3fa395cbd5d0a6

### Information about the issue/bug

1. Update the plugin to the latest version (ChatControl Red + BungeeControl).
2. Send a chat message in the server.

**Comment by kangarko** [comment]
Thanks, will fix.
