### ISSUE TITLE
CounterStrike Chat Support

### ISSUE THREAD

**Issue by PinoyLifeCraft** [kangarko/ChatControl#245]
Hello there @kangarko ,

I am using [CounterStike](https://www.spigotmc.org/resources/counterstrike-minigame.16641/) plugin on my server and when the game start and I chat two chat will exist ....Chatcontrol which is making the chat globa where my enemy can hear it. and the CSGO plugin chat which per team chat only.

And my reguest is to add support for that plugin xD . which is to disable the chatcontrol chat format when the game is started.

Note: [CounterStike](https://www.spigotmc.org/resources/counterstrike-minigame.16641/) is the same with Cops and Crims from Hypixel.
![21146217_475149512857022_1709438288_o](https://user-images.githubusercontent.com/13610530/29740961-d8e8f1d0-8a17-11e7-82d1-e97a7fdbf80f.png)

**Comment by kangarko** [comment]
Hey,

please try changing the priority of the Formatter to HIGHEST or MONITOR as per this article:

https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities

Sincerely,
kangarko

**Comment by kangarko** [comment]
I see your issue at https://github.com/kangarko/ChatControl-Pro/issues/330

Please do not double post.
