### ISSUE TITLE
1.20.1 | Bedrock Users Image Head Error

### ISSUE THREAD

**Issue by DeOpping** [kangarko/ChatControl#2450]
### "/version ChatControlRed" - plugin version

10.21.4

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/70d8d662fda2434cac629cac5d46490c

### Information about the issue/bug

Hello, this bug occurs I assume because the Image_Head can't get the skin for Bedrock users.
This is not a problem, I've made it so the Image_Head MOTD only shows when a Java player joins, using two MOTD parts.

However, it still attempts to send the Java MOTD to the Bedrock player (it just doesn't because the Receiver Condition).
This makes the error still occur.

Perhaps it is possible to add a check in the plugin that if the Image Head is not found, don't add an Image Head or replace it with a default one?

**Comment by kangarko** [comment]
Great catch! I have added a fallback option to settings.yml

![a](https://i.imgur.com/r6BPPKJ.png)

If you appreciate my support since 2015 consider dropping a review at BBB :)
