### ISSUE TITLE
1.20.1 First Join Message

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#2452]
### "/version ChatControlRed" - plugin version

10.21.6

### Are you using MySQL?

Yes

### Information about the issue/bug

Every time the server restarts, every player that joins gets the „first time joined“ message. Happened after I updated VelocityControl and ChatControl.

**Comment by james090500** [comment]
Can you send your velocitycontrol folder please,

Do you see any errors on velocity start up?

**Comment by Lorias-Jak** [comment]
[velocitycontrol.zip](https://github.com/kangarko/ChatControl-Red/files/12579429/velocitycontrol.zip)

Sorry for the delay, had nen long day and come only now to it.

As a short info. The existing users.yml is one that I took from the backup. After the conversion, this was almost completely empty. I should still have a backup of it, if you need it as well. 
I have first downgraded back to the 3.11.5, now it works again as before.

**Comment by kangarko** [comment]
Just to be sure you are talking about messages file on Velocity not on ChatControl on Bukkit right?

**Comment by Lorias-Jak** [comment]
Yes, only the one from velocity. The subserver join messages from chatcontrol are disabled.

**Comment by kangarko** [comment]
Apologizes for delays. I unfortunately don't code for Velocity, hope that my colleague will get back to you and resolve this

@james090500 can you prioritize this please?

**Comment by james090500** [comment]
@kangarko @Lorias-Jak Sorry, I didn't see this!

I think this is fixed now. Was a bug do to it writing empty data before reading it...

https://github.com/kangarko/VelocityControl/releases/tag/3.11.7

**Comment by kangarko** [comment]
Closing, let us know below if you got any more comments. Thanks for your patience.
