### ISSUE TITLE
1.20.1 clan name

### ISSUE THREAD

**Issue by Tunikaso** [kangarko/ChatControl#2454]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello, I would like the clan format that I created to appear when a user creates a team. But I can't do it. The clan plugin I use is Ultimate Clans V6. What I want is when a user does not have a team, nothing appears, and when they have a team, the name of the team appears. I have managed to insert the variable so that it comes out. But I can't find the option that activates that when a player creates a team from that plugin. I hope for a solution please

**Comment by kangarko** [comment]
Hey there!

You would have to make a custom javascript variable, I recommend duplicating variables/player-is-vanished.yml file and returning the clan variable if it is not empty, let me know if you need help with this.

**Comment by Tunikaso** [comment]
I do not know how to do it. It is very difficult.

**Comment by Tunikaso** [comment]
![what](https://github.com/kangarko/ChatControl-Red/assets/144724085/177ff4e1-d89b-493b-b49d-530a4eda471e)
I also keep getting that error.

**Comment by Tunikaso** [comment]
My server is not on a network, nor do I use BungeeCord. How do I remove that notice? It's annoying

**Comment by kangarko** [comment]
This is also required on a local instance, please set it as per instructions in the error message.
