### ISSUE TITLE
Chat similarity % block after configurable amount of repetitions

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#2455]
### Summary

Please add the setting "CheckAfterTimes: #" in the Chat > Similarity section of settings.yml

Adding this feature will allow to drastically reduce the frequency with which the repeated message block appears. Which is a lot, and has kinda become a classic meme in many servers.

I believe one of the main reasons for blocking repeated message spam would be stopping spam such as:
Hello
Hello (repetition blocked)
Hello (repetition blocked)

or

get rekt noobs
get rekt noobs (repetition blocked)
get rekt noobs (repetition blocked)

Having the first repetition blocked so easily is a bit too harsh depending on the similarity %. You may argue changing the percentage is a good solution for this, making the message strictly 100%, however then players would (as expected) add or reduce a couple letter or two just to avoid the repetition block.

A % such as 60, and blocking after 3 repetitions would allow valid messages while blocking serious ill intended spam.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Players may feel frustrated by this chat limitation appearing so easy.
Players will write excess lines just to get out of this block.

**Comment by kangarko** [comment]
Thanks, I'll be sitting with this some time next week.

**Comment by MithrandirCraft** [comment]
> Thanks, I'll be sitting with this some time next week.

Thank YOU.

**Comment by kangarko** [comment]
<img width="797" alt="Screenshot 2023-09-29 at 11 23 22" src="https://github.com/kangarko/ChatControl-Red/assets/1918426/65d21481-c711-4499-808e-6e9704727766">
Done - hopefully I understood it right and please let me know if there are any issues since it got quite complex with all the other conditions, thanks!
