### ISSUE TITLE
1.20.1: Numeric Rules

### ISSUE THREAD

**Issue by Pattanawaris** [kangarko/ChatControl#2456]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I read rules wiki for 2-3 times and still cant figured out that is there away  I can create rule to replace a specific range of number eg. 
player said  "selling [Item] for $5000" I try to rule to make to plugin replace the text to "selling [Item] for &b$5,000"
and if number is greather than 1000000 will replaced to &61,000,000 or even "$1m" to "&6$1,000,000" am not sure if it able to do? or you have any idea with this please?

**Comment by TheIntolerant** [comment]
Could you post an example of the rule below, thanks

**Comment by kangarko** [comment]
I think you can ask ChatGPT to create a regular expression based on your condition and then append our flpc variables as per this example rule before, and after that to properly add the old color back after it.

```
# -----------------------------------------------------------------------------------------------
# Special filter to colorize any commands appearing in the chat. This will turn "Type /help"
# into "Type &c/help" and then intelligently revert back to whatever color the message had
# previously.
#
# PLEASE NOTE that the [#flpc-X] variables are the only two special ones you can use without
# any modifications. If you have Strip_Colors on true in Rules in settings.yml, using any other
# color in the message will get it removed because the match removes colors as per this setting.
# -----------------------------------------------------------------------------------------------

match (,|\s)\/(\w+)
then replace [#flpc-i]&c$1/$2[#flpc-1]
```
