### ISSUE TITLE
Message_Delay

### ISSUE THREAD

**Issue by ttc111** [kangarko/ChatControl#2457]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

I've set Message_Delay to 10 minutes, but when players switch from server1 to server2, they can immediately send another message. How can I make Message_Delay apply to all sub-servers?

    ace:
      Message_Delay: 10 minute
      Format: acechat
      Bungee: true

**Comment by kangarko** [comment]
This information is not synchronized at this moment, I can add this to our roadmap for the future. Thank you.
