### ISSUE TITLE
1.20.1: Unable to show img link which sent from Discord

### ISSUE THREAD

**Issue by Hatsuharu33227** [kangarko/ChatControl#2458]
### "/version ChatControlRed" - plugin version

10.21.8

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

Private and sent to support@mineacademy.org

### Information about the issue/bug

I installed "DiscordSRV" "InteractiveChat" and "InteractiveChatDiscordSrvAddon" on my paper server, after the settings all done, the "Preview Images from Discord on Maps" function is working fine (fyi: 
![image](https://github.com/kangarko/ChatControl-Red/assets/141670946/35354002-1249-4fcb-9d0f-583c57b786e5)
). 

But after installed the "ChatControlRed" and settings the "Listener Priorities" on both these 4 plugins, then the "Preview Images from Discord on Maps" function was unable to show on minecraft chat. Both plugins are updated to latest version for testing. 

Please help to solve this issues, thanks.

**Comment by Hatsuharu33227** [comment]
Update: After testing another chat plugin like "Chatty", and the "Preview Images from Discord on Maps" function is working fine. Seem like only "ChatControlRed" have this issue.

**Comment by kangarko** [comment]
Yep, we're incompatible I am sorry. If maps can be opened by a command then you can just program a custom variable using ChatControl (see variables/ folder) that, when clicked, will open the map. That's how we do it for most things.

**Comment by Hatsuharu33227** [comment]
May I have an example for that? Since i dont know how to create variable for discord link, thanks.

**Comment by kangarko** [comment]
You will find examples in variables/ folder. Just run the command below the Run_Command key. You will need to check if there is such a command at DiscordSRV side.

**Comment by Hatsuharu33227** [comment]
But that is not a command, only trigged from Discord when someone send pic on Discord-MC chat channel.
FYI: https://www.spigotmc.org/resources/interactivechat-discordsrv-addon-show-items-and-invs-on-discord-preview-discord-images-in-game.83917/

**Comment by kangarko** [comment]
I am sorry, it appears to be incompatible at the moment. I'll investigate more when I have time but that most likely won't be fixed due to the scope of work required
