### ISSUE TITLE
1.20.1: Replacing /tpa text to include JSON/Click events

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2459]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Trying to replace the /tpa and /tpahere messages from EssentialsX so that it can be clickable to accept the request. From searching the discord, issues and Wiki, the closest I got is: 

match ^(\/tpa) (.*)$
then console tellraw "$2" {"text":"/tpa","clickEvent":{"action":"run_command","value":"/tpa"},"hoverEvent":{"action":"show_text","contents":["Teleport to them"]}}

Which still doesn't work the way I wanted. I tried using a format but this also doesn't seem to work. What am I doing wrong?

**Comment by kangarko** [comment]
I don't think your logic is correct here, isn't the other player obliged to type /tpaccept? Is the /tpaccept what you are trying to make clickable then this would work:

```
match ^(/tpa) (.*)$
then console tellraw "$2" {"text":"New pending /tpa.","clickEvent":{"action":"run_command","value":"/tpaccept"},"hoverEvent":{"action":"show_text","contents":["Click to teleport to him."]}}
then warn &6Request sent!
then deny
```

**Comment by HorusApl** [comment]
Alright this does seem to work, but only works with one direction. Is there a way to have an "Accept" and "Deny" button side-by-side on one line? Of course I can re-send the command, but that isn't great looking.

**Comment by HorusApl** [comment]
Like is there any way of sending a variable/format in this manner or any other way to accomplish the side by side buttons?

**Comment by HorusApl** [comment]
![image](https://github.com/kangarko/ChatControl-Red/assets/64336395/01afb5bb-3886-4fd7-a65c-dbf3a76230ed)
 Like so

**Comment by kangarko** [comment]
I unfortunately can't provide support with third party plugins. I am not familiar that much with their logic.

**Comment by HorusApl** [comment]
Wasn't asking for support with another plugin, was providing context with a picture to show what I was trying to do. Regardless, I figured that part out just by doing a longer tellraw command. My new question, is there any way to have the $2 parse their display name/nick name? Atm it only does exactly what you've typed, but the tellraw command only works with full IGNs and not nicks. So it sends the teleport request via Essentials, but my buttons aren't sent due to this.

**Comment by kangarko** [comment]
If I understand you correctly, are you trying to catch the $2 which catches the nick, and then convert the nick into a full IGN?
