### ISSUE TITLE
ChatControl (Free Version) Rules.txt Problem on /chc reload

### ISSUE THREAD

**Issue by ItzSomebody** [kangarko/ChatControl#246]
Version: 5.5.6
Spigot 1.8.8

Rules.txt (https://pastebin.com/raw/3uKKuxt7)

Stacktrace: (https://pastebin.com/raw/LUPkQ1SL)

**Comment by kangarko** [comment]
If this is fixed by restarting the server, then your file system is incompatible with the reload function. This is a rare case, but it cannot be excluded.

**Comment by kangarko** [comment]
I am closing this in faith this has been solved / understood. Feel free to comment below if any questions and I will answer them quickly :)

**Comment by ItzSomebody** [comment]
Oh ok, good to know :D

**Comment by ItzSomebody** [comment]
And and by the way, no. It is not fixed with a restart.

Ubuntu 16.04

**Comment by kangarko** [comment]
In linux, you can try using [Atom](https://atom.io/) to save it in UTF-8 format.

If it still doesn't work try saving the rules files in other format like ANSI (but you'll loose your smiles from chat.txt).

Make sure you don't use Multicraft editor or any other inbuilt editor that does not respect encodings.

Other than that, are you having this problem on your localhost testing server or on your online server?

**Comment by ItzSomebody** [comment]
It was on our online servers. Really strange, but I will try Atom and different encoding formats
