### ISSUE TITLE
[Issue] Incompatibility with ShowItem

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#246]
We discussed this in another issue and I was wondering if the incompatibility with the ShowItem plugin could be solved somehow.

New error: https://pastebin.com/LQ08FvSP

Old error: https://pastebin.com/Q4Hi236D

ChatControl error (It's silent since last release): https://pastebin.com/Wke77cmS

Comment from ShowItem developer:

`It's the main reason I moved to the adventure text library in ShowItem, unfortunately as long as other plugins like ChatControl touch the messages again the error might still happen. If you can then I suggest disabling any dynamic protocol message rewriting which chat control might have. Their error is even proof of that: it shows that they correctly get the message that was modified by me, they simply fail to properly parse it`

**Comment by kangarko** [comment]
We use the native md_5's library to parse data, I am not responsible for this library to fail unfortunately. So I'd suggest you ask that developer to silently hide the error when it happens. Or disable packet processing on ChatControl.

**Comment by kangarko** [comment]
Can you ask the developer on what priority he is listening his packet adapter on? I can try changing mine to LOWEST so it comes before ShowItem plugin

**Comment by Sikatsu** [comment]
I will ask the ShowItem developer and report back once he replied. Thanks!

**Comment by klugemonkey** [comment]
Why does ShowItem try to serialize the components that are sent already in the chat packet?  I'm not following why this is necessary, but also seems like gson is failing on the second go of serialization.  I don't think this is a component loop issue with the original components.  Would not be surprised if there are still issues in gson given all the problems of late with the latest versions after md_5 updated the gson version in Spigot around 1.16 release.  Gson seems like one of those APIs that you can break if you don't implement the code properly.  Also, please note, gson is good for serialization, and good for deserialization, but its not as good if you are trying to retain the same content by serializing and deserializing and serializing again, expecting to get the same output as input.
