### ISSUE TITLE
1.20.1: CHC Crashing / Hangs server

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#2460]
### "/version ChatControlRed" - plugin version

10.21.6

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://pastebin.com/5EfkZXmq

### Information about the issue/bug

On the past four version or so of chatcontrol red I have received this error message that hangs and crashes my server. Im not to sure how to replicate it as it seems to happen at random times.

**Comment by kangarko** [comment]
Thank you, will be fixed by tonight!

**Comment by TZ122** [comment]
> Thank you, will be fixed by tonight!

Hey, I saw the update on builtbybit. I should mention that looking back at the log (must've missed this in my pastebin) I did have a player join then the crash proceeded. Just thought I would mention this seeing as the change-log had mentioned player quit. (I have joins on async as well not sure if this could've had something to do with it too)

**Comment by kangarko** [comment]
Thanks. I removed a synchronize block on the whole logic so the fix would apply for all kinds of player messages: join, quit, kick, death. Let me know if you spot anything!

**Comment by kangarko** [comment]
Thanks. I removed a synchronize block on the whole logic so the fix would apply for all kinds of player messages: join, quit, kick, death. Let me know if you spot anything!
