### ISSUE TITLE
1.20.2: Cannot use another language file

### ISSUE THREAD

**Issue by VozikCZE** [kangarko/ChatControl#2461]
### "/version ChatControlRed" - plugin version

10.21.9

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/3deec7a066c140de99667dedcb6c46bd

### Information about the issue/bug

I copied messages_en.yml and I changed name of it to messages_cz.yml, but plugin won't load it. 
![image](https://github.com/kangarko/ChatControl-Red/assets/48393384/df50adf9-39f9-429c-82a0-e9a49a233b59)

**Comment by kangarko** [comment]
Nechaj tam starý názov a upravuj messages_en.yml
