### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by chrydin** [kangarko/ChatControl#2462]
### "/version ChatControlRed" - plugin version

10.21.9

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

Updated bunch of plugins, then it stripped off the chatcontrol display from chats when players talk

### Information about the issue/bug

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/12797779/debug.zip)

[error.log](https://github.com/kangarko/ChatControl-Red/files/12797782/error.log)

**Comment by kangarko** [comment]
Did you reload or used plugman? Try on a clean server start

**Comment by chrydin** [comment]
ah i noticed it doesnt work together with citizenAPI for some reason, deleted citizen and alls ogod

**Comment by kangarko** [comment]
Must have been an outdated version then. We do not interfere with Citizens in any way in ChatControl.

**Comment by chrydin** [comment]
nah happened after i updated both plugins :(

**Comment by kangarko** [comment]
Sorry for the delay, still having issues? If yes try the latest Citizens from https://ci.citizensnpcs.co/job/citizens2/ and do a clean restart not /reloading

**Comment by chrydin** [comment]
Yeah tried wiping both files of those two no dice

**Comment by kangarko** [comment]
I'll silence the error in the next version since discord sender is never citizens NPC
