### ISSUE TITLE
1.20.1: Newest version /chc announce chat does not print in chat

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#2464]
### "/version ChatControlRed" - plugin version

10.21.10

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Hey, 
Since updating to the most recent version of chat control using the announce chat feature does not seem to work.

How to replicate:
Run the command '/chc announce chat test'. This does not print anything in chat however it does show in console.

This command worked on the previous version.

**Comment by kangarko** [comment]
Should be fixed on the next version
