### ISSUE TITLE
1.20.1: Missing Channel Change/Switching messages

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2465]
### "/version ChatControlRed" - plugin version

10.21.10b

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/12837135/debug.zip)

### Information about the issue/bug

The normal message sent to the player upon channel change/channel entry is not appearing on newest version, but it is still present in my localization file as always has been. I am fairly sure this is effecting other locale/plugin messages as I received no message in-chat upon make the debug zip

Relevant section from locale:
    Switch_Success: Switched mode for channel &o{0} &7from {1} to {2}.
    Success: Joined &o{0} &7channel in {1} mode.

**Comment by TZ122** [comment]
I am also having this issue in addition to #2464 on latest version

**Comment by Teslicek** [comment]
I agree. The newest update (10.21.10) screwed it up. There are no message inputs in certain messages, such as /message, /chc message, etc.

**Comment by HorusApl** [comment]
It seems my radius local chat is also not working/showing up for anyone.

**Comment by kangarko** [comment]
Sorry, was due to a faulty pull request in Foundation: https://github.com/kangarko/Foundation/pull/244#issuecomment-1760708199

We have reversed this change asap.
