### ISSUE TITLE
1.20.1: SocialSpy not spying every cmd

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#2466]
### "/version ChatControlRed" - plugin version

10.21.10

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

I sent an email

### Information about the issue/bug

If our staff have cmd spy on only a small percentage of the cmds are sent to the staff and the only places i have dont spy in rules are on signs.

some of the cmds we like to watch players use are /b or /back

**Comment by kangarko** [comment]
Should be fixed on the next version
