### ISSUE TITLE
1.20.1 - /chc color menu and /spy menu is not working

### ISSUE THREAD

**Issue by MeHaVr** [kangarko/ChatControl#2468]
### "/version ChatControlRed" - plugin version

1.20.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

I sent an email

### Information about the issue/bug

When I do /chc color menu or /spy menu there is nothing and in the console it just says "[16:35:20 INFO]: Name issued server command: /spy menu".

**Comment by kangarko** [comment]
Should be fixed in the next version.
