### ISSUE TITLE
ig list

### ISSUE THREAD

**Issue by ttc111** [kangarko/ChatControl#2470]
### Summary

Is there any consideration for adding a check feature to /ignore? For instance, if I enter /ignore list or /ig list, it could display a list or menu showing who I have ignored. This would be very helpful for players, especially on large servers.
When players block too many people, they tend to forget who they have blocked. Having a list would make their experience much better.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

n

**Comment by kangarko** [comment]
There is /ignore list already, that will list players that you ignore.
