### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by chrydin** [kangarko/ChatControl#2471]
### "/version ChatControlRed" - plugin version

10.21.10

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Last version with Citizen does not work, I fresh installed both plugins and citizens disables chatcontrol's chat UI completely, other chatcontrol features worked such as pm and channels

Please look into this, 1.20.1/1.20.2

**Comment by kangarko** [comment]
Cant reproduce on the next version, please test with the next update tonight

![a](https://i.imgur.com/X7TXdfk.png)
