### ISSUE TITLE
1.20.1 - remove message not working

### ISSUE THREAD

**Issue by MeHaVr** [kangarko/ChatControl#2472]
### "/version ChatControlRed" - plugin version

10.21.10b

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

no error log

### Information about the issue/bug

**Remove message not working**

The chat.yml file defines delete-char with:

    Run_Command: /{label} internal remove {message_uuid}

and issues this command:

     /chc internal remove 844db6ef-6a7c-439f-b446-ed6e5dfe9e00

However, it does not delete any message. No errors anywhere.

**Comment by kangarko** [comment]
You need to have ProtocolLib latest development build for that feature
