### ISSUE TITLE
Velocity 1.20.2 is working?

### ISSUE THREAD

**Issue by celciusjj** [kangarko/ChatControl#2473]
### "/version ChatControlRed" - plugin version

10.21.11

### Are you using MySQL?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/12907972/debug.zip)

### Information about the issue/bug

I was working in bungecord with waterfall, and i can communicate between servers, in the chat, not now with velocity

**Comment by celciusjj** [comment]
really interests me is that the messages are shared between servers

![image](https://github.com/kangarko/ChatControl-Red/assets/37490999/d55287b2-7190-4ec4-b86b-edccc32341a0)
Just appear the only one server bunge

**Comment by celciusjj** [comment]
Another info more, before works with bungecontrol-red but i change to velocity

settings.yml in every spigot server
https://pastebin.com/E207Gr5k

in velocity 

https://pastebin.com/Nh72nXRh

**Comment by kangarko** [comment]
@james090500 please have a look

**Comment by celciusjj** [comment]
Some update @james090500 @kangarko ?

**Comment by james090500** [comment]
Sorry, I've been trying to find some time to look into 1.20.2. 

I assume you can access all on server on 1.20.1? Did this work previously or are you using 1.20.2 straight away?

**Comment by celciusjj** [comment]
I just test in new versions of velocity,  Now I can't test in 1.20.1, because it corrupts all my maps when downgrading. Do you look the config, and some other things? Maybe I'm the one doing something wrong.

Really i dont know if is just a problem with 1.20.2, but with bungecontrol red works the chat forwarding

@james090500

**Comment by james090500** [comment]
Can you try just velocity 1.20.1 with via version keep paper on 1.20.2

**Comment by celciusjj** [comment]
Ok i will try

**Comment by celciusjj** [comment]
![image](https://github.com/kangarko/ChatControl-Red/assets/37490999/f26a80e6-6e4d-4216-8ee7-0a3cfa4700ed)
I was testing and works, lol, even in 1.20.2, the chat forwarding

**Comment by james090500** [comment]
> ![image](https://github.com/kangarko/ChatControl-Red/assets/37490999/f26a80e6-6e4d-4216-8ee7-0a3cfa4700ed)
> I was testing and works, lol, even in 1.20.2, the chat forwarding

Ok so... What's changed?

**Comment by celciusjj** [comment]
> > ![image](https://github.com/kangarko/ChatControl-Red/assets/37490999/f26a80e6-6e4d-4216-8ee7-0a3cfa4700ed)
> > I was testing and works, lol, even in 1.20.2, the chat forwarding
> 
> Ok so... What's changed?

Really, i dont know

I've made a lot of changes since opening the issue, changing the speed version several times, but the latest one seems to work.

**Comment by kangarko** [comment]
Fixed, closing. Let us know below if you should have any other questions.
