### ISSUE TITLE
I need help for the chat format.

### ISSUE THREAD

**Issue by Tunikaso** [kangarko/ChatControl#2475]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I need help. I want when someone creates a clan to add the placeholder next to the rank. It is this %uclans_tag_formated% and when someone activates a tag too, it is this %deluxetags_tag%. Right now I have it like this because I don't know how to create the condition. I've been trying for hours and I have no idea. If no one can help me I will have to look for another plugin.Having it the way I have it, not having a clan, you see a space in front of the rank and it looks very ugly.
![format](https://github.com/kangarko/ChatControl-Red/assets/144724085/7bd786d9-e5cf-41b7-9b3c-8f93bdf96dea)
![cc](https://github.com/kangarko/ChatControl-Red/assets/144724085/4cd61ad6-7361-4bd0-bbb9-05ab5ae0f450)

**Comment by kangarko** [comment]
Have you tried using the + variable to only add the space when it's set?

{uclans_tag_formated+}

**Comment by Tunikaso** [comment]
Thank you very much, it already works with what you have told me. I apreciate it!

**Comment by kangarko** [comment]
You're welcome :) Consider giving a review if you like my plugin!
