### ISSUE TITLE
1.20.1 Blocking of townys /t command

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#2477]
### "/version ChatControlRed" - plugin version

10.21.12

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/13060438/debug.zip)

### Information about the issue/bug

ChatControl registers an /tell alias named /t. This interferes with Towny's /t command, which is more common on our server. Only the team is allowed to use /tell or /msg. 

I tried to disable the /t alias, but when chatcontrol is on the server, towny still does not recognize the /t command. I have to take the plugin out completely first for towny to work again. Happens also only since I have now made a major version jump of ChatControl, was previously on version 10.21.3

**Comment by kangarko** [comment]
Thanks, should be fixed in https://builtbybit.com/resources/chatcontrol-red-format-filter-chat.18217/updates

**Comment by Lorias-Jak** [comment]
Thank you very much ^^
