### ISSUE TITLE
Configurable /ignore list

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2479]
### Summary

![image](https://github.com/kangarko/ChatControl-Red/assets/87967222/22686220-8aa8-44e0-9842-03e866a3c504)

Those lines are non-editable and are ugly. Even with maximum chat scaling, it takes 2 lines. And I'm not even talking about the rest of the menu...

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

.

**Comment by kangarko** [comment]
Thanks, will do in 1h.

**Comment by kangarko** [comment]
Also I fixed the padding overflowing issue on the default setting.
