### ISSUE TITLE
[Issue] Toggle timed doesn't work

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#248]
When using /toggle timed it asks for a group. When I give up the group it throws an error: https://pastebin.com/DAq49htr

Minecraft 1.16.4 Tuinity
Bungee: true
MySQL: true

**Comment by ElBananaa** [comment]
> When using /toggle timed it asks for a group. When I give up the group it throws an error: https://pastebin.com/DAq49htr
> 
> Minecraft 1.16.4 Tuinity
> Bungee: true
> MySQL: true

I have the same issue. The line is in the file, but it looks like kangarko made a typo mistake:
`Report: Default 'messages_en.yml' lacks an Object at 'Commands.Toogle.Toggled_Group'`
But it should be `'Commands.Toggle.Toggled_Group'`

**Comment by kangarko** [comment]
OMG that's a typo!
