### ISSUE TITLE
1.20.2: Velocity join messages not displaying

### ISSUE THREAD

**Issue by Geitenijs** [kangarko/ChatControl#2481]
### "/version ChatControlRed" - plugin version

10.22.0

### Are you using MySQL?

Yes

### Information about the issue/bug

I'm running a completely stock Velocity setup (b294) with the latest version of VelocityControl (3.11.7). No changes were made to the messages folder/files

config file: https://pastebin.com/Gdpebytq

screen: https://imgur.com/a/zIOE0nz

Leave messages work just fine, but join messages don't show up at all. No permissions are configured either, so that's not the issue.
Not sure about switch messages, as I currently only have 1 server running under Velocity.

**Comment by james090500** [comment]
Can you please send the join.rs file in messages

**Comment by Geitenijs** [comment]
It's stock. not edited in any way. https://pastebin.com/J4m291ef

**Comment by james090500** [comment]
Is there a users.json file in the VelocityControl folder? Does a reboot fix it?

**Comment by Geitenijs** [comment]
@james090500 yes there is, I've already deleted it to create a fresh setup, but to no avail. And a reboot doesn't fix it, obviously.

It almost seems like Velocity has changed their API in a way that VelocityControl doesn't pickup the join events anymore.

**Comment by james090500** [comment]
I will look into this tonight

**Comment by Geitenijs** [comment]
@james090500 Have you been able to check this yet?

**Comment by james090500** [comment]
I am seeing similar issues on my server but struggling to see why its only working for some users and not others. I am looking into it

**Comment by james090500** [comment]
@Geitenijs  Can you turn on Debug mode and send a velocity log on attempted join?

**Comment by james090500** [comment]
@Geitenijs Ok this is a simple issue.
![image](https://github.com/kangarko/ChatControl-Red/assets/20372645/8ee3e6a2-7501-4b63-914d-4cf831cc34f8)

Please check you have "Bungeecord" as "True" in ChatControl settings.yml line 1350

![image](https://github.com/kangarko/ChatControl-Red/assets/20372645/9e5b5ddb-56d6-4c67-83ca-8b0fb71211c8)

**Comment by Geitenijs** [comment]
This works! Thanks for your help :)
