### ISSUE TITLE
1.20.2: Creating a CHC rule to help prevent staff vanish chat

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#2482]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

No

### Question

Hey, 

Im looking for assistance in creating a rule that when: 

If a player is returning {premiumvanish_isvanished} = yes and chatcontrolred channel = local
How can I then require all of the players messages (not commands) to require "/" after it in order to send to that channel?

Thanks for any help!

**Comment by kangarko** [comment]
Hey! Good question, I will add it to our wiki.

You need to be using the next upcoming version since I made it easier. Here is the rule:

Just replace essentials with your other vanish plugin and change channel name:

```
match ^.*
require script {essentials_vanished}
require channel standard
then warn {prefix_error}&7You are vanished!
then warn {prefix_error}&7Your message must start with &6/&7 to talk in chat.
then deny
dont verbose
```

**Comment by TZ122** [comment]
> Hey! Good question, I will add it to our wiki.
> 
> You need to be using the next upcoming version since I made it easier. Here is the rule:
> 
> Just replace essentials with your other vanish plugin and change channel name:
> 
> ```
> match ^.*
> require script {essentials_vanished}
> require channel standard
> then warn {prefix_error}&7You are vanished!
> then warn {prefix_error}&7Your message must start with &6/&7 to talk in chat.
> then deny
> dont verbose
> ```

Thank you for adding this!
I tried this out on the latest version. The conditions work great however adding "/" before the message does not push it to chat (I receive the 'then warn' messages instead). Here is my rule unsure why this is not working: https://pastebin.com/ZWKDGHGY

I would love to have this rule only apply towards chat (not commands) and for the "/" to be present after the message. (So it doesnt conflict with commands) 
For example: Hello World/ (If vanished and channel is matching). Is this possible?

**Comment by kangarko** [comment]
Sorry for the delay! Did you put it to chat.rs file? It should only be in this file not to get filtered by other means.

**Comment by TZ122** [comment]
> Sorry for the delay! Did you put it to chat.rs file? It should only be in this file not to get filtered by other means.

Hey yes it is in chat.rs however does not seem to let the chat through (the conditions are correct). Please let me know if I can provide anything to help further.

**Comment by kangarko** [comment]
Oooh if I understand correctly you want to force players type / before when they are vanished to make them chat? I just looked at it and this will effectively act as a command, thus they wont be able to run any commands when vanished. 

Instead, what I ended up doing is enforcing players to prepend a dot "." before their messages to chat in local. Place both rules in the order below to chat.rs **in the next version**.

```
match ^\.(.*)
dont verbose
require script {essentials_vanished}
require channel local
then rewrite $1
then abort

match ^.*
dont verbose
require script {essentials_vanished}
require channel local
then warn &7You are vanished!
then warn &7Your message must start with &6&l.&7 to talk in chat.
then deny
```

Let me know if that helps and you understand these two rules above! **_The abort operator will start to work in the next version_**.

PS: Please use require script "{premiumvanish_isvanished}" and not require script "{premiumvanish_isvanished}" == "Yes" because the "Yes" is unnecessary and case sensitive (must be yes not Yes)

**Comment by TZ122** [comment]
Hey almost! PremiumVanish plugin uses "/" after the message to send it to chat (but it has no CHC channel integration - not sure how who doesn't use CHCR these days!)

I changed the above rule to match that and it works perfect! Thanks for making such an incredibly flexible plugin :)

match ^(.*)\/$
dont verbose
require script {premiumvanish_isvanished}
require channel local
then rewrite $1
then abort

**Comment by kangarko** [comment]
Oh sorry for the oversight, I see that the / should be at the end of the message, cool! Happy we got it resolved finally :)
