### ISSUE TITLE
1.20.1: CHC throws error when wants to give a book

### ISSUE THREAD

**Issue by MatinHQ** [kangarko/ChatControl#2483]
### "/version ChatControlRed" - plugin version

10.22.0

### Are you using MySQL?

Yes

### Error log (if applicable)

there are only few lines which will be posted at information section

### "/chc debug" output (strongly recommended)

I will mail it

### Information about the issue/bug

Error on console
```
[16:07:03 INFO]: [ChatControlRed] !-----------------------------------------------------!
[16:07:03 INFO]: [ChatControlRed]  Failed to execute command /chc book give Lobby_Help
[16:07:03 INFO]: [ChatControlRed] !-----------------------------------------------------!
```

**Comment by kangarko** [comment]
Your error.log says:

"Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information.
	§4§l§nWelcome To Lobby§r
server lobby avalin serveri hast ke shoma bad az login varedesh mishin, shoma mitonid ba estefade az §5§lCOMPASS§r gamemode mored nazaretoon ro entekhab konid, hamchenin mitonid az §5§lNPC §r haye vasat lobby estefade konid"


So you need to replace all & and § occurrences as per the error or set Books.MiniMessage_Format to false in settings.yml
