### ISSUE TITLE
1.20.2: Boss TM player boss death message

### ISSUE THREAD

**Issue by Navalke** [kangarko/ChatControl#2484]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hi Matej! 

I'm using your Boss plugin and Chat Control Red together. As you know there is a death message feature in CCR and when you kill a player it sends a message to chat. I love this feature but when I create a Player NPC Boss for my dungeon, every time a player kills this boss, the plugin perceive this boss as a player and sends a death message. I got a lot of bosses in my dungeon so it makes chat so messy. Can I disable this?

**Comment by kangarko** [comment]
Sure mate, I'll implement diz to the next release!

```
group citizens-npc
require npc
then abort
```
