### ISSUE TITLE
How to Nickname or Displayname Mention

### ISSUE THREAD

**Issue by paiow** [kangarko/ChatControl#2486]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Besides the player's name
The player's nickname (Essentials/CMI) or
Is there a way to mention it by Displayname?

**Comment by kangarko** [comment]
How is the displayname different from a player's name or a nick? I thought it's the same as nick.

**Comment by paiow** [comment]
Yes, PlayerName and DisplayName are different.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#setDisplayName(java.lang.String)

PlayerName
can't be set
can be get

DisplayName
can be set
can be get

**Comment by paiow** [comment]
Can you update the functionality of DisplayName or Nickname Mention?

**Comment by kangarko** [comment]
Cool! I will add to the next version. For now it will only work locally without bungee.
