### ISSUE TITLE
bypass advertising for specific command?

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2488]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Sorry on mobile doing this. Most likely a silly question, but is there a way to bypass advertising for domains for a specific command? 

Our case is /accesstrust group.to

This is a griefprevention command to give access to a simple clans group, but it think's it's a .to website!

**Comment by TomLewis** [comment]
wait I already know this, its just
https://github.com/kangarko/ChatControl-Red/wiki/Rules#ignore-command-command

isnt it, let me test this

**Comment by kangarko** [comment]
Yes you can ignore a certain command there. Let me know!
