### ISSUE TITLE
Suggestion: Ability to reject sound notify mention

### ISSUE THREAD

**Issue by paiow** [kangarko/ChatControl#2489]
### Summary

/chc mentiontoggle on
the state of being able to receive a mention

/chc mentiontoggle off
the condition of not receiving a mention

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Some players may not want a mention.

**Comment by kangarko** [comment]
Not now, and I am unfortunately crazy busy these weeks but I can keep this open for a future implementation.

**Comment by paiow** [comment]
When will you develop a toggle to reject mentions?

I am waiting for this feature.
I would like you to also provide a related Developer API or a PlaceHolder API that can check the status.

**Comment by kangarko** [comment]
Sorry, not sure how I missed your issue but it got implemented:

![a](https://i.imgur.com/hXnNGqH.png)

Add soundnotify to Toggle.Apply_On in settings.yml and then let players use /toggle soundnotify
