### ISSUE TITLE
1.20.1: Got an error report from console

### ISSUE THREAD

**Issue by Hatsuharu33227** [kangarko/ChatControl#2490]
### "/version ChatControlRed" - plugin version

10.22.2

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

When I say sth in sync discord chat and the error will popup from console.

[02:46:53 ERROR]: ChatControlRed 10.22.2 encountered a ScriptException! Please check your error.log and report this issue with the information in that file. Running Paper 1.20.1-R0.1-SNAPSHOT and Java 17.0.6

**Comment by kangarko** [comment]
Sorry but the error log sucks. My fault. I'll improve it in the next release so you know exactly what went wrong and can either fix it or repost it.

**Comment by kangarko** [comment]
I would replace the Value in ping.yml variable with just 

Value: "player.getPing()"

Should fix it.
