### ISSUE TITLE
Offline message

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#2491]
### Summary

If you send a /msg to someone offline, don't cancel it but rather send it to him once he connect, like essentials did with the /mail

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Player often ask to send messages to their offline friend (so they can see the message once they connect)

**Comment by kangarko** [comment]
Yes we already have a /chc mail, I dont plan on adding this to /msg because we already do this in the mail.
