### ISSUE TITLE
1.19.3 : Load issue

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#2492]
### "/version ChatControlRed" - plugin version

10.21.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

I had an issue into my database on server load, and plugin failed to start because of : 
Failed to connect to database

So I fixed my database, and tried to do "/chc reload" to enable the plugin again and connect it to the database, but it told me "you can't do that while plugin is disabled"

So it forced me to restart the server just for this, but a reload to reconnect to the database would have fix the issue

**Comment by kangarko** [comment]
Post me the console log, pretty sure there is an error.

**Comment by WarnDa** [comment]
https://pastebin.com/U4GK9bek
here are the logs with chatcontrol.
Once the plugin restarted, it connected to mysql but the /msg wasn't working and telling plugin is disabled.
I can send the full logs in private on discord : **warnd**

**Comment by kangarko** [comment]
It says "This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff."

**Comment by WarnDa** [comment]
> It says "This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff."

https://pastebin.com/W9C8ptuH
I tried to plugman it to fix it, didn't work
But this happened because my mysql was off when server boot, and then I fixed my mysql worked again and I had to restart the server to fix chatcontrolred

**Comment by kangarko** [comment]
It says Connection refused. Check your credentials. Or try setting Hikari to false in mysql.yml.

**Comment by WarnDa** [comment]
But ?? 
I just told you that my mysql went down, and when the mysql is off while starting the plugin, it fails to load and you must restart server to fix it, I just ask you to make /chc reload trying to load the plugin again and connect to mysql ???

**Comment by kangarko** [comment]
I understand, however the plugin is meant to be used with or without MySQL. If your MySQL goes down, naturally there is an error. This is meant to notify server owners of a critical issue.
