### ISSUE TITLE
MINEDOWN Formatting Support 

### ISSUE THREAD

**Issue by NoxNap** [kangarko/ChatControl#2495]
### Summary

Support MINEDOWN Formatting. 
You can view more information on it [here](https://github.com/Phoenix616/MineDown). 
I need it because I use Velocitab and the hex works fine in tab (i.e. &#<colorHex>&MyText) but leaves the &MyText in chat instead of just MyText. 
I would use another tab plugin but I really can't find any other plugin alternatives for Velocity. 

I hope we can see this in a future release of ChatControlRed because as of now I can't use hex in my ranks without having an &{username} in chat or #{hex}{username} tab.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

As mentioned above, if you didn't implement this feature plugins that depend on MINEDOWN (or MINIMESSAGE works too) then plugins such as Velocitab won't work for hex, and server owners would have to decide between using hex or a new chat manager that supports minedown or minimessage.

**Comment by kangarko** [comment]
We already [use our own parser](https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/model/SimpleComponent.java) which at this point would make it technically unfeasable. I'd have to rewrite it from scratch for which I have no time right now. But I understand that this library could be technically superior with more control so I can consider that in the next major rewrite (V11). No ETA for this yet.
