### ISSUE TITLE
ChatControlRed 10.22.5 encountered a FoException

### ISSUE THREAD

**Issue by chrydin** [kangarko/ChatControl#2498]
### "/version ChatControlRed" - plugin version

10.22.5

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/47ca37e965e94c31915353bad85f4d92

### "/chc debug" output (strongly recommended)

plugin disabled cant use

### Information about the issue/bug

pls note the paste.gg link everything on there

**Comment by kangarko** [comment]
Remove log.csv file and it will be fixed. It has a corrupted header.
