### ISSUE TITLE
Command to enable/disable chat spy 

### ISSUE THREAD

**Issue by afroman84** [kangarko/ChatControl#25]
This would be useful for moderators, having a command to enable and disable the ability to read all the ranged chat. It technically disables and enables the permission chatcontrol.chat.spy for the user.
Syntax suggest: /chc spy and /chc spy username for enabling and disabling to others.
New permission suggest: chatcontrol.chat.spy.toggle and chatcontrol.chat.spy.toggle.others

Thanks for reading.

**Comment by kangarko** [comment]
Can consider adding it, but most probably to the premium version.

**Comment by Okane84** [comment]
Thank you. Ot: The premium version chat formatter is still without the %displayname for the nicknames?

**Comment by kangarko** [comment]
No, it has both %displayname for displayname and %nick for Essentials's nick, but you can create your own variables.

**Comment by kangarko** [comment]
Closing. Covered by Chat Channels in premium version.
