### ISSUE TITLE
1.16 bungee | BungeeChatAPI-2.0.0 Error Enabling Plugin

### ISSUE THREAD

**Issue by astirling** [kangarko/ChatControl#25]
I'm getting the error below when starting my Bungeecord server with the latest release (10.0.1)

https://pastebin.com/qhe0B7Kc

**Comment by kangarko** [comment]
Do not BungeeChatAPI to your BungeeCord. I have included it in the file by a mistake, apology. Next version will include the correct "BungeeControl Red" plugin.
