### ISSUE TITLE
[Issue] Players are being kicked out of channels

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#250]
My players keep getting this message now and then:

![image](https://user-images.githubusercontent.com/5664135/101398275-1b74f400-38ce-11eb-8c53-f5511593a70f.png)

And this after being inactive for a moment:

![image](https://user-images.githubusercontent.com/5664135/101398292-23349880-38ce-11eb-94d7-18a24e33848b.png)

This is on todays release .17 and using Bungee / MySQL.

**Comment by kangarko** [comment]
After how long do players start to see the "please move before typing" message?

**Comment by Sikatsu** [comment]
Not entirely sure and not every player seems to have this. So far I have had 2 players that reported this.
Seems to be around an hour between their reports though back when I made this github issue.

**Comment by kangarko** [comment]
Will look into this asap.

Attaching a copy of your debug:
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5673590/debug.zip)

**Comment by kangarko** [comment]
Apology for a big delay this time. Did it stop happening on the last version or is this still a problem?

**Comment by Sikatsu** [comment]
I have completely reset the ChatControl database and I haven't heard much issues about this anymore.

There were still a few cases though where people didn't have a channel to write into, a relog would always fix this for them though.

So that still means there is an issue somewhere, but a relog fixes it and it barely happens too.

**Comment by kangarko** [comment]
Thanks for waiting and letting me know! There's a correction for people unable to use the autojoin permission in the next release too :)
