### ISSUE TITLE
Allow certain links to be posted in chat

### ISSUE THREAD

**Issue by mingemuffler** [kangarko/ChatControl#250]
Hey, either I cant find it or it may not be there but I wondered if theres a section where I can post certain links to bypass the IP/link ban?
Cheers

**Comment by kangarko** [comment]
Yes,

please open rules/rules.txt and read about how to add exceptions to the domain or IP address filters.

**Comment by mingemuffler** [comment]
Sorry to be a bother, but I kiiiind of understand what it explains but not really, what setting would I add and where in the settings to allow www.flow-craft.com to be posted?

**Comment by kangarko** [comment]
In that file, find this line:

ignore string minecraft:|youtube.com|imgur.com

and add |flow-craft.com to it like so:

ignore string minecraft:|youtube.com|imgur.com|flow-craft.com
