### ISSUE TITLE
Sound_Notify Tab Completion

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2501]
### Summary

`Sound_Notify.Require_Prefix: '@'`

Make it so after the prefix, the user will get the tab completion of online players. 

Right now, the feature is basically useless, as it is very tidious to type something like @ShXd0s6s2d4 in order to ping them.

If such a feature were a thing, you would just type `@Sh(tab)` and could easily complete that name without a hassle.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

.

**Comment by kangarko** [comment]
Chat completions are handled client side as of the modern MC and thus editing it is not supported, sorry.
