### ISSUE TITLE
Chat message sending/Command execution cooldowns actually queue instead of stopped

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [kangarko/ChatControl#2502]
### Summary

So basically we set time between 2 commands or 2 chat messages
Player types: "Hello there"
and somehow he also types after 0.5 seconds "What's up?"

This will result into "Please wait x before sending another message" or if it is command execution, it will result into "Please wait x before executing another command"

Now what this optional setting could do is to actually not fully prevent chat message from being sent/command from being executed, but to DELAY it until cooldown is over

Let's assume delay between chat messages and commands are both set to 2 seconds
1. So i join server and type "Hello everyone"
2. After 0.5 seconds i already tried to send "How is everyone?"
3. Server says to me "Please wait x before sending another message" followed with "Sending message..." message
4. After 1.5 seconds (because delay is set to 2 seconds, i tried to send message after 0.5 seconds, so 2-0.5 = 1.5), the chat message (or if it is command execution, same approach), is finally sent as it was queued.

* Potential things i am unsure about as i am not (good) developer is that this might require faking PlayerChatEvent because this would probably act like sudoing player after rest of the delay has expired so this would be possible (i don't know how else this could be done)

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

I personally think this is something unique and this feature, no matter if it is bad for performance (i assume not?) or if it is small or whatever... i am sure no CHAT MANAGEMENT PLUGIN has feature like this, and this in my opinion is not something that will bulk up the plugin itself, this could be optional, but i don't know.

**Comment by kangarko** [comment]
Thank you, that is frankly not the vision behind chatcontrol right now since I try to keep it clean and we already have tons of setup. This rather looks like a separate plugin idea, not sure if I have time for this right now. Thanks for your understanding.
