### ISSUE TITLE
Block phrase with a word, but don't block if it a single word

### ISSUE THREAD

**Issue by StKillReal** [kangarko/ChatControl#2503]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

How to block message only if it contains a phrase with the word, but not a single word?
I want to create warn message for players who sending buy/sell messages in global chat without blocking ability to send a single "buy" word in the chat.

**The case for example:**
- Player1: [GlobalChat] I'm selling/buying bunch of glowstone (player can't send it to global chat and see warn)
- Player1: [AuctionChat] I'm selling/buying bunch of glowstone (all good)
- Player2: [GlobalChat] buy/sell (this message shouldn't be blocked)
_I speak other language and this dialogue looks better on my native lang ;)_
![image](https://github.com/kangarko/ChatControl-Red/assets/60330193/a16890e4-40d7-447a-8c92-9ea3c671f11f)

**Comment by kangarko** [comment]
Hey!

That regular expression should be fairly doable. I asked chatgpt:

![a](https://i.imgur.com/elMjCHZ.png)

This is what it said:

`(?i)\bbuy(ing)?\b.*\b\w+\b|\b\w+\b.*\bbuy(ing)?\b|\bsell(ing)?\b.*\b\w+\b|\b\w+\b.*\bsell(ing)?\b`

After placing it to https://regex101.com/ and testing it appears to be working :)

Matej
