### ISSUE TITLE
1.20.X: Chat clear when server switch (Global Server Chat) 

### ISSUE THREAD

**Issue by R3miiTV** [kangarko/ChatControl#2504]
### "/version ChatControlRed" - plugin version

10.22.6

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

Hey, I'm using ChatControl with its cross server Feature. 
It's working fine but when people switch servers the previous chat is getting cleared / is gone.

**Comment by kangarko** [comment]
That is a client-side issue, the client clears the chat and I am afraid we can't stop that. You would need to google some Forge/Fabric mods for that.
