### ISSUE TITLE
1.20.2: Remove message will not work if Rules.Apply_On does not have "packet" inside

### ISSUE THREAD

**Issue by nhanledev** [kangarko/ChatControl#2505]
### "/version ChatControlRed" - plugin version

10.23.0

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

I was having problem with messages can not be delete by the admins.
As I inspecting the setting, I figure out that if I remove **packet** from **Rules.Apply_On** (because I just don't use that .rs file, it will cause the problem that message can not be deleted
![image](https://github.com/kangarko/ChatControl-Red/assets/28459250/e9cde8a7-e6a1-4655-a1e2-3c3d3c0a226c)

I don't know if this is a bug or is an intended feature :) If this is a false report, please let it slide :)

**Comment by kangarko** [comment]
Thanks for spotting. Fixed.
