### ISSUE TITLE
Add a cache for placeholders

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#2506]
### Summary

I'm using javascript and placeholders before player name in chat (and in hover) but currently each time a player speak, it refreshs all the placeholder (and the javascript), which uses a LOT of ram (it's ~0.1gb every message).
So I would like to add a cache to theses placeholder, so it can be refreshed every X seconds and not each messages.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

It would use way too much ram for nothing, and I would need to change my chat plugin

**Comment by kangarko** [comment]
Can you show me where you are having those? We already cache them every 0.5 seconds

**Comment by WarnDa** [comment]
> Can you show me where you are having those? We already cache them every 0.5 seconds

I used a real time memory checking to track the ram used by server (with TAB and a placeholder that refresh every tick and a placeholder that return current memory usage, and I was testing some javascript itself and also in chat)
And I want to cache them for 20-30s, not only 0.5s :/

**Comment by kangarko** [comment]
Can you give me an example where do you use that variable? Do you keep it in a separate file in variables?

**Comment by WarnDa** [comment]
For example in global_chat.yml :

`Message: '&f%javascript_donateur%&f%javascript_staff_joueur%&f%javascript_grade% %javascript_couleurpseudo%{player_name} &8❯`
and in the hover I got 8 placeholders (to display players stats)

**Comment by kangarko** [comment]
I am sorry but that would be for a custom plugin. Can you code? You can just call our HookManager.addVariable()  and add the variable there, making hashmap in your own java code with the timestamp and last memory value. That would be the easiest thing. I do have free MC coding tutorials on youtube I think you can get started very easily.

**Comment by WarnDa** [comment]
But it would be easier if you just add an option to keep placeholders parsed from chat messages in cache.
I will need to change chat plugin just because of that, make a custom plugin will be mainly the same issue, chatcontrol will need to check each time the placeholder

**Comment by WarnDa** [comment]
It’s something that impact every server that uses placeholders in chat

**Comment by kangarko** [comment]
Yes I understand, we already have 0.5s cache for all placeholders. Anything more will cause technical glitches as far as it goes. I can have another look and perhaps add a setting option for this after holiday. But I strongly believe that these customized variables should have a special 30-sec cache on your end

**Comment by WarnDa** [comment]
> Yes I understand, we already have 0.5s cache for all placeholders. Anything more will cause technical glitches as far as it goes. I can have another look and perhaps add a setting option for this after holiday. But I strongly believe that these customized variables should have a special 30-sec cache on your end

But if you add an option in config to change this, customer can change the value if needed as 0.5s is really low. 
Will wait after holidays then.

**Comment by kangarko** [comment]
I reviewed the code and seems like not everything is cached through that. If I have the time I can sit with it after holidays, thanks.

**Comment by WarnDa** [comment]
> I reviewed the code and seems like not everything is cached through that. If I have the time I can sit with it after holidays, thanks.

Okay, keep me updated ! :)

**Comment by kangarko** [comment]
I haven't found any major performance increase and re-enabled the micro cache we had temporarily disabled. Let me know if you have any major drops, simply send a spark report.

**Comment by WarnDa** [comment]
> I haven't found any major performance increase and re-enabled the micro cache we had temporarily disabled. Let me know if you have any major drops, simply send a spark report.

Bug, the issue with refreshing too much placeholders isn't SPARK, it's the memory usage (because placeholders are parsed async, aren't showed in spark), and this uses a lot of ram.. :/

**Comment by kangarko** [comment]
Provide me a memory report then, with and without ChatControl. I am interested in seeing the data

**Comment by WarnDa** [comment]
Can't remove chatcontrol for the test, as it's too hard to monitor

But will manage to find another fix, thanks for the help
