### ISSUE TITLE
InteractiveChat Not Working With ChatControl

### ISSUE THREAD

**Issue by Kaludii** [kangarko/ChatControl#2507]
### "/version ChatControlRed" - plugin version

10.23.0

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Hello, interactivechat plugin is pretty glitchy and often doesn't work in chat when using chatcontrol. When someone uses a chat placeholder, it'll show in discord because we use interactivechatdiscordsrv for placeholders to be sent in discord, but it won't show directly in-game, it'll just show the placeholder but no information. Is there a way for interactivechat to work 100% of the time instead of it being glitchy? It's a big part of our server.
Images:
https://media.discordapp.net/attachments/755325303689052200/1185860836212875345/image.png?ex=659125f7&is=657eb0f7&hm=cb148999803468c25f49836df6c543ec6449c9232ff33948c25a709bfe372d7f&=&format=webp&quality=lossless
https://media.discordapp.net/attachments/755325303689052200/1185860836514877470/image.png?ex=659125f7&is=657eb0f7&hm=df5b200b84c04a3a35b805bd7fd3d56cb4e8b2ee210498b96f78772418b4b9f7&=&format=webp&quality=lossless

**Comment by Kaludii** [comment]
Additionally, I do see the Chat Listener priority in settings and saw the wiki, it is currently set to `HIGH` by default. The chat placeholders from InteractiveChat do work, but sometimes, in this case which priority may be the best?

**Comment by Kaludii** [comment]
Last thing, the priorities for InteractiveChat by default are all `HIGH` as well.
  EventPriorities:
    # Defaults to HIGH
    Commands: HIGH
    # Defaults to HIGH
    Chat: HIGH
    # Defaults to HIGH
    Preview: HIGH

**Comment by kangarko** [comment]
Unfortunately these two are inherently incompatible since they fight for the same features. You either use chatcontrol or them, not both, not the same chat formatting features, I am afraid. Sorry about this, if you want a refund just email me.
