### ISSUE TITLE
Possible to use discordsrv's webhook messages for in-game chat, but respond using chatcontrolred from discord to in-game?

### ISSUE THREAD

**Issue by Kaludii** [kangarko/ChatControl#2508]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello, as stated in the title, is it possible to use discordsrv's webhook messages, meaning don't disable DiscordSRV's `DiscordChatChannelMinecraftToDiscord` and instead disable chatcontrolred's discord messages from being seen, and still being able to send messages from discord to in-game. We prefer the webhook format discordsrv provides, because it shows each player's nickname instead of username, their skin head image, and we have had also added each player's rank and prefix to the discordsrv messages. Please let me know if this is possible, thanks!

DiscordSRV webhook format:
https://ibb.co/zJtG0kH

**Comment by JerichoTorrent** [comment]
Yep, did exactly this. Add the following to your chat channels in the list in settings.yml
`Format_discord: none`
Upon reloading ChatControl Red will tell you that messages will be duplicated but they won’t. You can now enable the DiscordSRV messages. By doing this you are essentially sending messages from Minecraft to discord twice, but only formatting them once, so they only appear once.

**Comment by Kaludii** [comment]
> none

This is exactly what I was looking for, thank you so much!!
