### ISSUE TITLE
prefix and name have the same color

### ISSUE THREAD

**Issue by tariqmg** [kangarko/ChatControl#251]
Hello i need help with my chat plugin , well my problem is the chat display the message as : 
- (prefix name : message) all in the same color . But the color is only assigned for the prefix thank you 7
- Here is the img of the issue :https://ibb.co/fmfFuF

**Comment by kangarko** [comment]
Hey, what's your settings.yml ?

**Comment by kangarko** [comment]
Assuming fixed, please remind me if not.
