### ISSUE TITLE
1.20.2: File localization encoding problem

### ISSUE THREAD

**Issue by youguo** [kangarko/ChatControl#2511]
### "/version ChatControlRed" - plugin version

10.23.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

I'm sorry to raise this question.

All my plugins are working on GB2312. If I use "-Dfile.encoding=UTF-8" this param, all of my plugins (and all different servers) need to be recompiled, which is a absolutely big project....

Every time I start my server the file will be broken. I just hope you can provide a options to choose encoding or any other effective way. 

Thank you very much!!!!

**Comment by kangarko** [comment]
Hey! Are you able to open the ChatControl .jar and drag all the files manually to your plugins/ChatControlRed folder and then open them in like Notepad++ and change the encoding from there?

**Comment by youguo** [comment]
> Hey! Are you able to open the ChatControl .jar and drag all the files manually to your plugins/ChatControlRed folder and then open them in like Notepad++ and change the encoding from there?

#### Hello! 

#### I hava tried this.
#### But it seems that the plugin will manual broken my file (It can show text correctly only once) 

#### Every time I start my server or reload chatcontrol, message file will be broken.


#### Like this:

### From
![Screenshot 2023-12-30 120029](https://github.com/kangarko/ChatControl-Red/assets/60578211/02b0d1c4-ba0f-4aad-b3e2-a407e3ca0a12)

### To
![Screenshot 2023-12-30 120123](https://github.com/kangarko/ChatControl-Red/assets/60578211/1397585a-6a15-498e-9ad2-0f5baefec48f)

**Comment by kangarko** [comment]
Unfortunately, I don't think we're compatible. The plugin (and the server afaik) is made with UTF-8 encoding. That's something I won't be able to fix, sorry. If you need a refund just email me.
