### ISSUE TITLE
1.20.2: Random JavaScript errors

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2512]
### "/version ChatControlRed" - plugin version

10.22.6

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/3b2e00cf568649f8ade13b601b1f160a

### Information about the issue/bug

see error above

**Comment by kangarko** [comment]
Please use 10.23.1 and repost if that happens.
