### ISSUE TITLE
1.20.4: A question about bungee join/leave/switch messages

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/ChatControl#2514]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hello, I was wondering if it was possible for join/leave/switch messages to only be shown to players on the same server as the one performing the action? For example, if player X switches from server A to B, I would like the switch message to only be shown on server A, and the join message to only be shown on server B. It is fine if the switch message shows on both servers, but what I don't want is for either switch or join message to be shown on a server C also connected to the network.

The join message part is easy - CHC Red can handle them individually on the backend servers. But for the switch and leave messages, there needs to be a condition that requires the sender server to be equal to the receiver server, which has me stumped.

Thanks in advance for your help!

**Comment by kangarko** [comment]
I see, I don't think so for now, sorry. You can configure join/leave messages on Spigot part in ChatControl and they will stay on the server. Messages you configure in BungeeControl upstream and broadcasted network-wide.
