### ISSUE TITLE
1.20.2: Startup error after update

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2515]
### "/version ChatControlRed" - plugin version

10.23.2

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/c2becbb31c12436c9666e724e3813da0

### Information about the issue/bug

.

**Comment by Neeonn** [comment]
Same issue. Formats in question for me are `spy-pm.yml` and `spy-command.yml`. I update the files and restart the server but it keeps removing the line after restart.
This is why:
```[18:56:15 INFO]: Warning: The following entries in spy-command.yml are unused and were moved into plugins/ChatControlRed/unused/spy-command.yml: [New_Line_Per_Part]
[18:56:15 INFO]: Warning: The following entries in spy-pm.yml are unused and were moved into plugins/ChatControlRed/unused/spy-pm.yml: [New_Line_Per_Part]
[18:56:15 INFO]: Warning: The following entries in admin-say.yml are unused and were moved into plugins/ChatControlRed/unused/admin-say.yml: [New_Line_Per_Part]
```

**Comment by StKillReal** [comment]
![image](https://github.com/kangarko/ChatControl-Red/assets/60330193/e15376d5-3703-4f47-bb85-3aaff5864495)
Seems the same. I have downgraded plugin version to make it work again

**Comment by kangarko** [comment]
I apology for the screwup, fixed. A new release will be out in a few hours asap.
