### ISSUE TITLE
1.8.8: @noprefix Localization

### ISSUE THREAD

**Issue by Neeonn** [kangarko/ChatControl#2516]
### "/version ChatControlRed" - plugin version

10.22.5

### Are you using MySQL?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/13788569/debug.zip)

### Information about the issue/bug

Try using `@noprefix` for `Mute.Mute_Success_Plain`.

**Comment by kangarko** [comment]
Thanks, will be fixed.
