### ISSUE TITLE
How to create local and [!] global chat

### ISSUE THREAD

**Issue by xskylite** [kangarko/ChatControl#2517]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

How to create local and global chat
local: 
player local message: hi I player (100 blocks range)
player global message: !hi I plauer (infiniti blocks)

**Comment by StKillReal** [comment]
# Send messages starting with "!" to global channel
match ^(\!)(.*)
then command channel send global $2
then deny
dont verbose

Add this to rules>chat.rs

**Comment by xskylite** [comment]
> # Send messages starting with "!" to global channel
> match ^(!)(.*) then command channel send global $2 then deny dont verbose
> 
> Add this to rules>chat.rs

that is, I need to add this to the rules and create an auto join channel range? (and also how to change the range format) ?

Edit: and why is there 2$ there?

**Comment by kangarko** [comment]
Thanks to StKillReal :) Closing now, you fill find more rule examples in rules/chat.rs that will help you. Comment below if you need more help.
