### ISSUE TITLE
"New_Line_Per_Part" defaulting to "true" when updating to 10.23.2

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2519]
### "/version ChatControlRed" - plugin version

10.23.2

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

I haven't updated ChatControl yet but noticed a few users report this on discord and decided I might as well report the bug.
---
![image](https://github.com/kangarko/ChatControl-Red/assets/48093184/59bc07c6-8710-4aa0-8518-057cf2c1574e)
![image](https://github.com/kangarko/ChatControl-Red/assets/48093184/77f8c033-fbbd-49c5-a36b-f749e3c8e040)
---
![image](https://github.com/kangarko/ChatControl-Red/assets/48093184/27eaddd7-1952-4a9d-8c30-6199e9108476)

**Comment by kangarko** [comment]
Thank you, apology for the screwup. Fixed asap.
