### ISSUE TITLE
[Issue] Message deletion also deletes other plugin messages

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#252]
When I ban/kick someone and I delete a players message, it also deletes the LiteBans messages. Attaching a video zipped below!

[bug.zip](https://github.com/kangarko/ChatControl-Red/files/5668196/bug.zip)

**Comment by kangarko** [comment]
Will get back to this once I have time

**Comment by kangarko** [comment]
Okay so, the way chat deletion works is as follows:

1. We listen to absolutely every message and store it in chat history, per player.
2. When a message is removed, we resend 100 last messages to the player with the removed message exempted, using their chat history.

Unfortunately this is likely an incompatibility in that LiteBans is sending the message in a way we can't register. We use ProtocolLib to catch messages. The only time we did not put them into the history log was when they were over 50k lines. I removed that limitation in the next version. If the issue will still occur, unfortunately I can't fix this right now. Please correct me if I am wrong.

**Comment by Sikatsu** [comment]
Thanks for your clarification!
