### ISSUE TITLE
Player Disconnect Console Error

### ISSUE THREAD

**Issue by doitliketyler** [kangarko/ChatControl#252]
Hey. Just reporting a console error Im getting when a player leaves a server.

https://pastebin.com/AyRCwA2r

Im on Paper Spigot 1.12.1 and running the latest version of CC. Thoughts?

**Comment by kangarko** [comment]
Hey,

I am rewriting ChatControl. Please wait 1-3 days for the new version that brings many major changes.

**Comment by doitliketyler** [comment]
Will do. Thank you.

**Comment by kangarko** [comment]
Hey,

Thank you for contacting me. I am sorry you have issues and I hope we can get this solved quickly :) I am right now rewriting ChatControl. Please wait 1-3 days for the new version that brings many major changes and also this fix.

**Comment by kangarko** [comment]
Houps, I double-posted :)
