### ISSUE TITLE
1.20.2:  Many MySQL connections opened but not closed (causes "too many connections" error)

### ISSUE THREAD

**Issue by benhogervorst** [kangarko/ChatControl#2521]
### "/version ChatControlRed" - plugin version

10.23.0

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://gist.github.com/benhogervorst/b1c894a5a3332efabc9e3663433e7d53

### Information about the issue/bug

I have a BungeeCord server (build 1779) with 5 connected paper spigot servers (1.20.2 build 318).  All servers connect to a self-hosted MySQL database and each has multiple plugins accessing its own database or a shared network-wide database (for things like permissions and playtime counting).  

I started getting errors from most MySQL-connected plugins on most of the servers about the MySQL server denying new connections because of "too many connections".  The default limit is somewhere around 150 I think, and I only have 3-5 connections per server, so this limit should not be met (and never has been before this).

I logged into the MySQL console and ran "SHOW FULL PROCESSLIST;" with all servers stopped (aka connections closed).  I saw just a couple of processes.  Once I started BungeeCord, I saw a couple more added, as I'd expect.  Once I started a paper spigot server, I saw an immediate stream of new connections from ChatControl to it's database.  The new connections didn't stop and just filled up the whole table until the MySQL server started rejecting them.

Screenshot below only shows the last 50 or so connections:
![image](https://github.com/kangarko/ChatControl-Red/assets/11810635/faabe34f-bf24-4ad8-b2c3-3e197aa3d06e)

**Comment by benhogervorst** [comment]
Updated to 10.23.3 (newest that I see).  Does not seem to have fixed anything.

**Comment by benhogervorst** [comment]
On line 39 of mysql.yml, I changed autoReconnect=true to false.  It now reads as follows:
`Line: jdbc:mysql://{host}/{database}?autoReconnect=false&useSSL=false`

This seems to have stopped the creation of new connections, but there are still a good 10 connections created to the database for each server now, which is still weird.   Will continue to test and see how this works.

**Comment by kangarko** [comment]
Hey!

Apologized for the late answer. I believe in certain settins, hikari can cause this. However we do obey its default limit of 10 connections per server. Set Hikari to false in mysql.yml and it should only make 1 connection. I tested with rejoining and /chc reload with Hikari disabled:

![a](https://i.imgur.com/E8xV6XZ.png)

Matej

**Comment by benhogervorst** [comment]
Cool, no problem.  My fix has worked so far but I'll give that a try as a more proper fix.  That explains why I was seeing 10 connections being opened at the same time.  Thanks.

Ben

**Comment by kangarko** [comment]
Thank you, I have improved the docs of mysql.yml :)
