### ISSUE TITLE
1.20.2: Internal exception after while

### ISSUE THREAD

**Issue by PSYCHEER** [kangarko/ChatControl#2522]
### "/version ChatControlRed" - plugin version

ChatControlRed version 10.23.3

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

No log error

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/13801329/debug.zip)

### Information about the issue/bug

When server start up all is operating normal, but after ca.10min when I want to delete message it give me kick with strange error
![image](https://github.com/kangarko/ChatControl-Red/assets/42911029/5d2e8386-9b6b-4517-ab4c-f7e4b8a0a4df)
Interesting is, sometimes it kick all players with this error after message deletion and sometimes only other players...

**Comment by PSYCHEER** [comment]
Okay, I tried to change priority from NORMAL to HIGH but
![image](https://github.com/kangarko/ChatControl-Red/assets/42911029/02771e7f-ed33-41d8-b8d6-de527841b8f6)
these messages are deleted but for me are still visible...

**Comment by PSYCHEER** [comment]
Okay, after like 20 minutes it's working as it should...

**Comment by kangarko** [comment]
Please update to the latest dev build of ProtocolLib from: https://ci.dmulloy2.net/job/ProtocolLib/
