### ISSUE TITLE
Request To Improve Gradient Text

### ISSUE THREAD

**Issue by Kaludii** [kangarko/ChatControl#2523]
### Summary

Hello, I've noticed that there is a visible difference between using gradient from gradient generator websites, and using the built-in `Gradient` for the format. The first message below along with the screenshot provided was generated with an online gradient text generator, and the second one is how it looks when using the built-in gradient, as you can see, the built-in text gradient is not as vibrant as the online generator, it would be nice to improve the current text gradient, if possible.

```   Message: '&#D700FFK&#AC30FFa&#8160FFl&#568FFFu&#2BBFFFd&#00EFFFi'```

```
    Message: '%essentials_nickname%&r'
    Gradient: '#D700FF - #00EFFF'
```

![image](https://github.com/kangarko/ChatControl-Red/assets/63890666/2f269982-c553-4b27-97f2-187fe4af2693)

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

The current gradient colors are not in line with what the gradient should be.

**Comment by kangarko** [comment]
Hey!

Thanks. Our gradient method is open source here: https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/ChatUtil.java#L568

Suggestions are welcome.
