### ISSUE TITLE
Prevent chat format codes counting towards max nick length limit

### ISSUE THREAD

**Issue by BlueFyreMatt** [kangarko/ChatControl#2525]
### Summary

Exclude formatting codes from the max nickname length.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Currently, players are limited to a max character length, which becomes highly restrictive when applying hex codes to a nickname. This means we must either increase the nickname length to allow for this, or leave it low which prevents the nickname from exceeding 4-5 characters after formatting has applied.

**Comment by kangarko** [comment]
Hey, you can adjust the max nick length in Tag.Max_Nick_Length in settings.yml where colors are not counted.
