### ISSUE TITLE
1.20.4 Discord -> server messages not sent

### ISSUE THREAD

**Issue by Yoloman0013** [kangarko/ChatControl#2526]
### "/version ChatControlRed" - plugin version

10.23.2

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://pastebin.com/e84maA3Y

### "/chc debug" output (strongly recommended)

https://ufile.io/a09yusq3

### Information about the issue/bug

Messages sent from discord wont appear inside server

**Comment by kangarko** [comment]
Thanks, looking into this asap.

**Comment by StKillReal** [comment]
Have the same issue, but reverse. Messages from Minecraft doesn't appear in discord after updating discordsrv to the latest version

**Comment by kangarko** [comment]
Thanks, Discord has broken the integration with us, I will fix it tonight.

**Comment by kangarko** [comment]
Guys, by the way, make sure to have

`Sender_Condition: '{sender_is_player}'`

in your ping.yml file or wherever the error occurs. You need to ignore this variable since it cannot work for players on Discord.
