### ISSUE TITLE
1.20.4: discordsrv incompatibility

### ISSUE THREAD

**Issue by Sylensky** [kangarko/ChatControl#2527]
### "/version ChatControlRed" - plugin version

10.23.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://pastebin.com/pdcY5z32

### Information about the issue/bug

With discordsrv 1.27.0 they introduced some changes that affect chat forwarding, see [here](https://www.spigotmc.org/resources/discordsrv.18494/update?update=528521)

**Comment by kangarko** [comment]
Thanks, gonna update asap.

**Comment by kangarko** [comment]
Will be out tonight, sorry for the delay.
