### ISSUE TITLE
Suggestion: Discord ignore

### ISSUE THREAD

**Issue by Pantera07** [kangarko/ChatControl#2530]
### Summary

Players cannot ignore Discord users.
I suggest adding a command to ignore messages sent from Discord.

Also, if the DiscordSRV setting is `DiscordChatChannelRequireLinkedAccount: true`, it would be nice if I could check for linked accounts and ignore Discord messages from players I ignore.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Players can't ignore Discord spam.

**Comment by kangarko** [comment]
Discord users are not reachable Bukkit players, they might not have an instance yet. Therefore is technically more complex to ignore them. Right now we do not plan on adding this but I might consider in the future at the next recode.

**Comment by Pantera07** [comment]
Is it also difficult to add a command to ignore all messages sent from Discord to Minecraft?

**Comment by Pantera07** [comment]
https://github.com/kangarko/ChatControl-Red/issues/2535

**Comment by Pantera07** [comment]
> Is it also difficult to add a command to ignore all messages sent from Discord to Minecraft?

@kangarko

**Comment by kangarko** [comment]
I'll look into this in a few days

**Comment by kangarko** [comment]
Sorry, really I don't have the time nor capacity to add this feature right now.
