### ISSUE TITLE
Suggestion: Fix PM Auto Mode InteractiveChat Incompatibility

### ISSUE THREAD

**Issue by Pantera07** [kangarko/ChatControl#2531]
### Summary

PM Auto Mode does not support sending placeholders for InteractiveChat.
Because it is sent as below.

`[inv] hello` →
`/tell Mad_Daniel <chat=f6dc4708-1af2-4dd4-aa92-252af3891a8f:[inv]:> hello`

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

PM Auto Mode does not support sending placeholders for InteractiveChat.

**Comment by kangarko** [comment]
This is I believe a known incompatibility. The only way would be to use the new paper chat event which would break on Spigot and older MC versions, but I might add it later.
