### ISSUE TITLE
1.20.4: No Casesensitive Regex

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#2532]
### "/version ChatControlRed" - plugin version

10.23.3

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/13864864/debug.zip)

### Information about the issue/bug

We're filtering for a vanish command. The command is case sensitive, it only reacts to lowercase commands. I think my expression in the rules file `command.rs` should be the right one. 

`match ^\/(v|vanish)$`

Chatcontrol reacts to `/V` and `/v` - Normally it should only react to the lowercase `/v`
In the following picture you're able to see, that the `/V` command does not exist, but chatcontrol sends the message.
Maybe i do something wrong?

<img width="392" alt="image" src="https://github.com/kangarko/ChatControl-Red/assets/62625225/6d0d3a59-a81b-41c3-8b23-2a453c1b039b">

**Comment by kangarko** [comment]
Set Rules.Case_Insensitive to false in settings.yml to disable this feature.
