### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by gary81013** [kangarko/ChatControl#2533]
### "/version ChatControlRed" - plugin version

10.23.4

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://pastebin.com/j9NvJ4Wi

### Information about the issue/bug

Chat messages cannot be connected to discord
ChatControl-Red-10.23.4

**Comment by kangarko** [comment]
Update your DiscordSRV to the latest version.
