### ISSUE TITLE
1.20.4 Bug Lines

### ISSUE THREAD

**Issue by xskylite** [kangarko/ChatControl#2534]
### "/version ChatControlRed" - plugin version

10.23.2

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/13867776/debug.1.zip)

### Information about the issue/bug

Lines Bug 
![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/ab249bac-bf2f-4475-8cc2-7298d5655ab0)

**Comment by kangarko** [comment]
Set New_Line_Per_Part to false for files inside formats/
