### ISSUE TITLE
1.20.2: Read and Write permission

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [kangarko/ChatControl#2536]
### "/version ChatControlRed" - plugin version

ChatControl-Red-10.23.4

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

I sent a private email

### Information about the issue/bug

chatcontrol.chat.read: See chat messages.
chatcontrol.chat.write: Write chat messages.

Hello, the problem concerns these 2 rights. I have something like a "tutorial" on the server and I need before it ends that the player can't see any messages in the chat and likewise can't post in the chat. I tried disabling these rights, I found on WIKI, but neither on me nor on a newbie without rights.. unfortunately these rights did not work

Is there any way to disable writing and reading messages in public chat? Thank you very much for your support

**Comment by kangarko** [comment]
Hey,

Unfortunately [I can't reproduce](https://i.imgur.com/SMQwFYG.png). If you give the player the two permissions you mentioned, he will be unable to engage in ChatControl chat, meaning he won't be able to send or receive messages through any ChatControl channels.

That is for our own plugin only. We dont filter messages from other plugins or the server and the player will still receive them.

**Comment by Sh3r1ffCZ** [comment]
> chatcontrol.chat.read: See chat messages.
> chatcontrol.chat.write: Write chat messages.

The problem is that the player has these permissions disabled. However, the player can still post in the chat. We don't use anything other than the chatcontrol plugin to edit the chat. That's the only reason I'm contacting you with the error. I can also send screenshots that the player permission has:
**chatcontrol.chat.read false
chatcontrol.chat.write false**
and still can see the chat and can write.
