### ISSUE TITLE
1.20.1: Adding [JSON] before announcement does not make it JSON format

### ISSUE THREAD

**Issue by Kaludii** [kangarko/ChatControl#2537]
### "/version ChatControlRed" - plugin version

10.23.3

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

On the wiki it says `You can send a chat message, title, boss bar, action bar, toast or even json, and in-game it shows that JSON can be added by adding [JSON] before the announcement, but it does not make it json format for the chat announcement as it states.

![image](https://github.com/kangarko/ChatControl-Red/assets/63890666/b0b7d358-f85b-4232-8127-2c1d4e77c7eb)

**Comment by kangarko** [comment]
Hey! Apologizes, that is one unsupported because of the formatting that is above/below (! ANNOUNCEMENT !) so it's parsed as text.
