### ISSUE TITLE
1.20.4 Velocity - Error Message in Velocity Control

### ISSUE THREAD

**Issue by MasterGabeMOD** [kangarko/ChatControl#2538]
### "/version ChatControlRed" - plugin version

VelocityControl-3.11.8-SNAPSHOT

### Are you using MySQL?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/29dd2f46afe647d38b6dc1dd906b3239

### Information about the issue/bug

Running Velocity build #320.

**Comment by kangarko** [comment]
@james090500

**Comment by james090500** [comment]
You're using a snapshot build from a half baked commit. Use a full release on the side bar.
