### ISSUE TITLE
Minecraft Version: 1.20.4

### ISSUE THREAD

**Issue by danieliustt** [kangarko/ChatControl#2539]
### "/version ChatControlRed" - plugin version

10.23.5

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/c1d2729ca2744df783a2125e0d6c69a9

### Information about the issue/bug

Crashing the server
For example: /msg username /msg username {player_name} {message} 
Private messages

Private_Messages:
  
  # Should we enable this feature?
  Enabled: true

**Comment by danieliustt** [comment]
Problem with placeholder parsing, namely with {message}. You just need to write to somone with mentioned command and server is down.

**Comment by kangarko** [comment]
Thank you, I have fixed that.
