### ISSUE TITLE
1.20.1: Bungee message was oversized issue

### ISSUE THREAD

**Issue by kamber5** [kangarko/ChatControl#2540]
### "/version ChatControlRed" - plugin version

10.23.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://hastebin.com/share/faweburako.markdown

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/13954740/debug.zip)

This is a haste from our Hub Server

### Information about the issue/bug

I dont have steps for reproducing, it just keeps spamming the Bungee Console.
We are using latest version of Flamecord.

**Comment by kangarko** [comment]
Sorry for the delay. How many players were online?

Please use BungeeControl 3.16.1 from later today and let me know what it will say, I have made the messages more accurate.

**Comment by kamber5** [comment]
Currently at 197 players and it is spamming the issue.

I shall update it and check if the issue continues tomorrow.

![image](https://github.com/kangarko/ChatControl-Red/assets/35629701/af5a9b84-816c-4531-9507-07daf1bcd9d7)
![image](https://github.com/kangarko/ChatControl-Red/assets/35629701/d1caef77-5e08-4faf-a5bd-b9e243ad9cd6)

**Comment by kangarko** [comment]
Please do update. I have improved the log message in a way where it will tell me where it is coming from.

**Comment by kamber5** [comment]
Today it was happening again, here is the message from the logs.
Bungee-Control version: 3.16.1.

`[20:52:44] [BungeeControl-Red Pool Thread #0/INFO]: [BungeeControl-Red] [outgoing-broadcastExcept] Outgoing bungee message was oversized, not sending. Max length: 32766 bytes, got 37163 bytes.`

It also seems that the problem only happens for a certain period of time, it does not happen through the whole day. I would send the log, but it has every players IP address.

**Comment by kangarko** [comment]
It would naturally happen when you have the most players online and their total sum of information exceeds the allowed packet size.

Here is a dev build, please do test it and let me know the new console message. It will have the same outgoing-broadcastExcept prefix but this time also tell me exactly which packet type it is and which info is being sent (it will be huge), allowing to track it down properly and possibly fix it. Apologizes for the inconvenience.

[BungeeControl-Red-3.16.1.zip](https://github.com/kangarko/ChatControl-Red/files/14058424/BungeeControl-Red-3.16.1.zip)

Thanks for your time.
Matej

**Comment by kamber5** [comment]
Added the new .jar for tomorrow morning after bungee restarts.

I will update as soon as I see the error.

**Comment by kangarko** [comment]
Thank you.

**Comment by kamber5** [comment]
Here is a paste link of the error message with the new .jar

**Comment by kangarko** [comment]
Thanks, I've deleted your link for privacy. Investigating on Monday.

**Comment by kangarko** [comment]
I will have to rework the network sync not to use plugin messaging packets but rather mysql or sockets.

Are you hosting your mysql on the server virtual machine? I.e. is the connection pretty much instant?

**Comment by kamber5** [comment]
Yes, its preety much instant, we are hosting sql on one of our machines. There are multiple server connecting from other machines also, but they are all in the same data center so there is no delay there.

**Comment by kangarko** [comment]
Hello,

Unfortunately rewriting how ChatControl communicates would require about 5-7 days of work, We have over dozens of plugin messages that would need to be written and read over the db and with all the testing and such it is not a small task, I 'd love to do it but I can't at the moment. I can just refund you or exchange for another plugin of yours. I am very sorry for the continued inconvenience.
