### ISSUE TITLE
1.20.1 Folia: Error loading plugin

### ISSUE THREAD

**Issue by iLemon** [kangarko/ChatControl#2542]
### "/version ChatControlRed" - plugin version

10.23.5

### Error log (if applicable)
https://pastes.dev/iE1vydmmRC

### Information about the issue/bug
Startup log: https://pastes.dev/E9967jBHvP

Server is running a fork of Folia 1.20.1.

**Comment by kangarko** [comment]
not found: 'iE1vydmmRC'
  maybe the paste expired?
