### ISSUE TITLE
Added Redis support.

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#2543]
### Summary

I hope that chat can be synchronized through Redis.

This way I can synchronize multiple agents without installing agent components.

Data is synchronously transmitted to some other economic components through Redis, without SQL. All communications between servers are handled through Redis.

Currently, Velocity support is not friendly, and some placeholders or functions on the agent cannot be used.
Use Redis to handle these problems, and place the processing on the server instead of the proxy.

1. For example, when I send announcements, I no longer use a proxy but directly send them to all servers (or designated servers) through Redis.
2. You can also use Redis to handle player joining and exiting. If I want the player joining information to be displayed on Discord, the player will join and exit once as long as he switches the stream.

The player's joining and leaving messages can be transmitted through Redis. Players can make short-term records when leaving the server. If they join other servers at this time, the server switching message will be triggered (currently only provided by the agent), and the joining will not be triggered. message.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

This is another alternative to SQL and synchronizes chat without installing a plug-in.

And it can solve the functions that are provided on the agent but not on the server. (Server switching message)

Does not rely on communication capabilities on the agent.

**Comment by kangarko** [comment]
Hello,

Thanks for suggesting. We do support Redis in BungeeControl, I don't know about VelocityControl but you'd have to ask @james090500 , our Velocity-fork maintainer of that issue.

**Comment by BearLeonLight** [comment]
> Hello,
> 
> Thanks for suggesting. We do support Redis in BungeeControl, I don't know about VelocityControl but you'd have to ask @james090500 , our Velocity-fork maintainer of that issue.

I hope to support it on the PaperMC backend so that cross-server chat can be done without going through a proxy.

In this way, even if the server has no players, I can still forward DiscordSRV, commands, etc.

**Comment by kangarko** [comment]
Oh I see. Thanks for the suggestion. For now theres no plans, I really dont have time for this plus the Redis integration was done by someone else since I dont frankly posses the skills for Redis. Happy to give source code access in case you know someone knowledgeable and trustworthy.
