### ISSUE TITLE
Using Command to run another Command

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#2545]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hi, I'm trying to get the `/info` command to run `/player_info` command but don't see where i'm going wrong?

#match ^\/info$
#require perm command.info &cInsufficient permission ({permission}).
#then warn &cDescription: Opens Info Menu.
#then warn &cUsage: /player_info
#then deny

match ^\/info (.*)
#require perm command.info &cInsufficient permission ({permission}).
then command player_info $1
then deny

`/player_info` simply opens a deluxemenus custom gui

Update:

match ^\/info$
then replace /player_info

it's catching the command and running the second command, it's just not opening the menu. If you run /player_info in chat the command is registered white and opens the menu.

[16:41]
[11:38:20 INFO]: Sir_Craftypants issued server command: /info
[11:38:20 INFO]: *--------- Rule match (command) for Sir_Craftypants ---------
[11:38:20 INFO]: MATCH: ^\/info$
[11:38:20 INFO]: CATCH: /info
[11:38:20 INFO]: UPDATE: /player_info

**Comment by 00Hrtz** [comment]
Tried

match ^\/info$
#require perm command.info &cInsufficient permission ({permission}).
then command player_info
then deny

and 

match ^\/info$
#require perm command.info &cInsufficient permission ({permission}).
then command /player_info
then deny

and get

[12:20:26 INFO]: Sir_Craftypants issued server command: /info
[12:20:26 INFO]: *--------- Rule match (command) for Sir_Craftypants ---------
[12:20:26 INFO]: MATCH: ^\/info$
[12:20:26 INFO]: CATCH: /info
[12:20:26 INFO]: Original message cancelled.

Menu's still not opening.

**Comment by 00Hrtz** [comment]
OK, i've found an alternative way to deal with `/info` but, i still need to know how to run the command so it opens a gui.

**Comment by kangarko** [comment]
Hello,

I dont have that plugin, but I tested with Boss and I was able to [open the menu](https://i.imgur.com/vqBFSWZ.png) normally using:

```
match ^/info$
then command /boss menu
then deny
```

As long as the player has the permission to run that command, it should work. If it does not then it looks like an issue with DeluxeMenus.

**Comment by SirCraftypants** [comment]
My mistake, i forgot to remove the \ on match.
