### ISSUE TITLE
1.18:2: Multiverse Chat crossing

### ISSUE THREAD

**Issue by RuuDarling** [kangarko/ChatControl#2546]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hi, I was wondering if there was a way to make global chats be visible between worlds? Like if I chat in one world, another world would be able to see it as well?

I've tried looking but I'm not sure if I'm just blind when reading the information. I am use multiverse core if that's any help.

Cheers in advance

**Comment by kangarko** [comment]
Hey,

Sure, it's possible. Read the docs in settings.yml in the Channels.List section, namely you gonna need to write Range option and set it to *, then configure Range_Worlds
