### ISSUE TITLE
[ChatControlRed]  Error executing JavaScript in a variable!Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by danieliustt** [kangarko/ChatControl#2547]
### "/version ChatControlRed" - plugin version

10.23.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/30f5786bae214e83bfca1d7e07f25145

### Information about the issue/bug

Errors

**Comment by kangarko** [comment]
You need to open ping.yml and change

return player.getHandle().ping;

to 

return player ? player.getHandle().ping : "";
