### ISSUE TITLE
1.20.1: Using Paper's AsyncChatEvent and/or AsyncChatDecorateEvent

### ISSUE THREAD

**Issue by NoxNap** [kangarko/ChatControl#2548]
### "/version ChatControlRed" - plugin version

10.23.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

hi, I'm using UltraStaffChatPlus for my Staff Chat. It allows for togglable messages however that does not work without using SignedVelocity. Here's where my issue arises that matters for ChatControlRed. 

CHC uses  `org.bukkit.event.player.AsyncPlayerChatEvent` instead of `io.papermc.paper.event.player.AsyncChatEvent`
I saw someone having the same issue with a different Chat Formatter say
> Developers could temporarily wrap their legacy functions to use paper AsyncChatEvent using something like
 > 
> String msg = LegacyComponentSerializer.legacySection().serialize(e.message();
> 
> // your old stuff
> 
> e.message(LegacyComponentSerializer.legacy('&').deserialize(msg));
> 
> But in the end it comes down to legacy code that needs to be rewritten

When I was talking with USCP Support to figure out why the toggled messages were not working, we ended up with it being out of their scope and the best option would be to go to ChatControl support and see if it's possible to use  Paper's AsyncChatEvent and/or AsyncChatDecorateEvent to resolve the issue. 

please let me know whether it's possible to have CHC use paper AsyncChatEvents; 

thanks.

**Comment by kangarko** [comment]
Thanks, using the modern listener is a high priority however not right now since I rather just cut off legacy MC versions than having two duplicate systems. The code is already very big. No ETA at the moment but this is something I look forward to doing.
