### ISSUE TITLE
1.20.4: Chatmessages dissapear on Serverswitch within a network

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#2549]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Hello everyone! 

I've updated and noticed that every time I change servers within my network, my chat is deleted. Is it possible to integrate a cache that sends incoming messages back to the player when the server is changed? This doesn't have to be a large cache over a long period of time, but it would be a shame if a message arrived when the Enter key for the server change was pressed and then suddenly disappeared without having been read. The same applies to internal channels that we have created for communication.

**Comment by joshwenke** [comment]
We are experiencing this issue as well... but  @Lorias-Jak are you sure that this isn't a spigot/paper issue? We had this issue on a newer 1.20.x version before switching to ChatControl Red. Would be interested to hear what you find.

**Comment by Lorias-Jak** [comment]
I think it will be default minecraft behavior, not a bug on the part of spigot / paper or velocity / bungee. 

Maybe you could ask paper if they know more @joshwenke?

**Comment by nhanledev** [comment]
AFAIK this is a bug since minecraft 1.20.4 as it clears all previous chat messages on server switch. I also have this issue too. I tested on the same server with 1.20.1 client and 1.20.4 client. 1.20.1 client does not have this issue.

**Comment by joshwenke** [comment]
Thanks for checking nhanledev. I see the bug report here:
https://bugs.mojang.com/browse/MC-267983

**Comment by kangarko** [comment]
I am sorry to see it's a bug out of my hands. Closing this, let's hope Mojang will get it fixed soon.

**Comment by Seeroh** [comment]
This isn't a bug, but rather a "Feature" of 1.20.2. Is there a way you can fix this, @kangarko?

**Comment by kangarko** [comment]
No unfortunately not an easy way to fix. Lets hope Mojang takes user feedback seriously.
