### ISSUE TITLE
Suggestion: H2 or SQLite database support

### ISSUE THREAD

**Issue by Pantera07** [kangarko/ChatControl#2550]
### Summary

Currently ChatControl Red has significant performance degradation when MySQL is not enabled. For servers where MySQL is not available, changing YamlConfig to H2 or SQLite instead can significantly improve performance.
https://github.com/kangarko/ChatControl-Red/wiki/Performance#non-mysql-users-high-cpu-drain-when-on-player-quit

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Servers without MySQL enabled will experience significant performance degradation when players leave or log in.

**Comment by kangarko** [comment]
I had an user configure his mysql.yml > "Line" key for flatfile/H2 storage, I unfortunately don't remember the structure but it should be doable. I strongly recommend MySQL/MariaDB when having higher workloads.

**Comment by Pantera07** [comment]
> I had an user configure his mysql.yml > "Line" key for flatfile/H2 storage, I unfortunately don't remember the structure but it should be doable. I strongly recommend MySQL/MariaDB when having higher workloads.

How can I set it up?
Will this be added in the next update?

**Comment by kangarko** [comment]
Try asking in our Discord community. I don't remember what he put into the Line key, but it _should_ be possible even now. No sorry I don't plan on adding h2 or litestorage specifically.
