### ISSUE TITLE
Please give us another option to specify servers other than server-name

### ISSUE THREAD

**Issue by joshwenke** [kangarko/ChatControl#2551]
### Summary

For every other Bungee plugin out there, they provide a config.yml option to set the server's name. You can tell the plugin what the name of your servers are via a normal configuration file. ChatControl makes you edit your server.properties.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

ChatControl's implementation of requiring edits to the server.properties is unsustainable for us.

1. Players often are confused by this in your Discord server, and it was not intuitive at all when setting up the plugin.
2. Randomly and without warning, the server.properties file will clear out the server-name value. Whether this is a Spigot/Paper/Bukkit bug, I am unsure, but server-name is NOT a vanilla value, and I am constantly fighting with my server to keep this value in there.
3. For networks that dynamically spin up servers on the fly, issue number 2 mentioned above is a big pain.
4. When the server-name value is not set, the plugin spams the log every 1 second, filling up drive space fast.

We love the plugin otherwise, but this inconvenience and inconsistency with the recognized standard of Bungee plugins (a .yml config value) is frustrating and will lower our 5 star review down to 3 or 4. Please fix this!

**Comment by joshwenke** [comment]
Here is an example of our current workaround for when server.properties removes the server-name variable. It is super messy and very frustrating.

<img width="1541" alt="image" src="https://github.com/kangarko/ChatControl-Red/assets/1607041/a41aad3e-ef34-486a-b15c-bf904742abbd">

**Comment by kangarko** [comment]
Thank you for sharing.

I propose we add a new file called bungee.yml. I was advised not to place this option in settings.yml for networks wanting to symlink their settings between multiple servers would end up in a server name duplicates. What do you think?

**Comment by joshwenke** [comment]
This is a great idea! Many other plugins have a dedicated bungee config file, and this allows us to pull our standard settings.yml from a single location in Git, and the server configs from their own respective locations. When the servers are dynamically generated, this will make it easy from a server management perspective.

**Comment by kangarko** [comment]
Done!
