### ISSUE TITLE
1.20.2: Unable to parse JavaScript when use msg via ShopGUI+ plugins

### ISSUE THREAD

**Issue by Corey-Stowe** [kangarko/ChatControl#2552]
### "/version ChatControlRed" - plugin version

10.23.6

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/de562aa0b9084d688c64f6cabc241f6a

### Information about the issue/bug

This issue occurs when a player purchases an item using ShopGUI+. After making a purchase, the command to send a message (/msg) to the player is initiated, but unfortunately, the message does not appear for the player.

![image](https://github.com/kangarko/ChatControl-Red/assets/55090875/764ab874-ba70-48bc-adae-a7a80a3e4994)

**Comment by kangarko** [comment]
Open variables/ping.yml and change Value to

````
Value: |-

  // Returns the ping of the player who sent a message with this variable
  getPing();
  
  
  function getPing() {
    
    // Try to call player.getPing() method directly if available 
    try {
        return player.getPing();
    
    // On old Minecraft use the NMS getHandle() and ping field.
    // You can access NMS here directly like this without worrying about imports.
    } catch (exception) {
        return player.getHandle().ping
    }
  }
````
