### ISSUE TITLE
1.12.2: Can I have in console colored chat too

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [kangarko/ChatControl#2553]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hello there,
is it possible to mirror almost exact same (or very similar) chat from ingame to chat logs in console (realtime console logging) to keep formatting (both colors and formatting itself) and to potentially not show [<channelname>] because i only am using 1 channel and autojoin all users to write and read (with those 2 permissions for `autojoin` and `join` + `write` and `read`)

I hope i clarified my questions correctly, i actually need this for 1.8+ servers to work if possible and not only 1.12.2 what i stated in title, i only did because there was that note for wrong and correct title and current server i am working on is paper 1.12.2

Thank you in advance! See images to see what i meant

ingame log
![image](https://github.com/kangarko/ChatControl-Red/assets/56804505/b73c6313-7cb6-4f80-8016-5e4574604be7)

console log
![image](https://github.com/kangarko/ChatControl-Red/assets/56804505/13d29cd9-78ef-44f3-a4e8-7351b3afb6b1)

**Comment by kangarko** [comment]
Unfortunately it's problematic, hence we had to add a separate formatter for the console. I recommend you configure a separate console format as close as possible to your main format. Some systems might allow for colors, you can just try using them with the & letter.

**Comment by MotikaCraft-TheJoshua** [comment]
> Unfortunately it's problematic, hence we had to add a separate formatter for the console. I recommend you configure a separate console format as close as possible to your main format. Some systems might allow for colors, you can just try using them with the & letter.

Thanks
Can you please explain how to make format to send to console only? and how to replace current format in console?

**Comment by kangarko** [comment]
Yes, please see Channels.List comments. You can use Format_Console option, such as here:

![a](https://i.imgur.com/pfLiGMS.png)

**Comment by MotikaCraft-TheJoshua** [comment]
Can i also state format name from file? Just like it is for `List.standard.Format: chat`
So can i set `Format_Console: my-format`, assuming that `my-format` format exists?

**Comment by kangarko** [comment]
The "Format" option supports this, but not the ones for discord/console
