### ISSUE TITLE
LiteBans mute bypass

### ISSUE THREAD

**Issue by xskylite** [kangarko/ChatControl#2555]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/9b301a06-7684-4b6b-8492-771828124466)
I will help /channel send global "message" you can bypass mute
![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/17c1aff7-4809-445d-90f0-a76eee719fbe)
![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/e70b44b1-bb25-4488-9874-ba4401a1c405)

**Comment by kangarko** [comment]
We should support LiteBans when installed with the latest ChatControl on Spigot. Not sure about Velocity, unfortunately if that does not work then you would need to use our own mute system instead which is fully compatible.

**Comment by 10Meisterbaelle** [comment]
Block the command /channel in Litebans, that should fix it
