### ISSUE TITLE
1.20.4: server-name bug

### ISSUE THREAD

**Issue by Pantera07** [kangarko/ChatControl#2556]
### "/version ChatControlRed" - plugin version

10.23.8

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/6c2976be3b0c44ce89606c4853ccc694

### Information about the issue/bug

This happens after updating from 10.23.7 to 10.23.8

**Comment by karlarturlokk** [comment]
same problem

**Comment by DerSeegler** [comment]
Same here. Seems it has to do with my server not having Bungeecord. And I have set the name in the server.properties, but MC removes it again on every server start. This is with the new version 10.23.8. It is not a problem with 10.23.7.

**Comment by kangarko** [comment]
Thanks, apologizes for the confusion.

All that was needed to do is set a server name in bungee.yml file, but I understand it might be useless since you are not using bungee so I have hid this (outdated) error.

Matej
