### ISSUE TITLE
1.12.2: GrantX can't cancel chat message on grant

### ISSUE THREAD

**Issue by 10Meisterbaelle** [kangarko/ChatControl#2557]
### "/version ChatControlRed" - plugin version

10.23.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14113856/debug.zip)

### Information about the issue/bug

When using the plugin [GrantX](https://demeng.dev/project/grantx/), if I type in a reason in for a grant or try editing the grant menu, it will send the chat message in chat even though it is supposed to cancel it. I don't know if you are able to fix this since it is a paid plugin.

**Comment by kangarko** [comment]
Hello,

You can try https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

If that won't work, then unfortunately it's incompatible.

**Comment by 10Meisterbaelle** [comment]
Setting it to HIGHEST fixes it, thanks!
