### ISSUE TITLE
1.20.4: Only 2 server show on chc alert or broadcast

### ISSUE THREAD

**Issue by sl0wl0r1s** [kangarko/ChatControl#2558]
### "/version ChatControlRed" - plugin version

10.0.23.8

### Are you using MySQL?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14117566/debug.zip)

### Information about the issue/bug

Good evening,
I installed chatcontrol red on all the backend servers of my network and I installed the velocity version in my velocity.
when I try to make a broadcast, in the list of servers it only shows me 2, which alternate, sometimes kitpvp and lifesteal, other times lobby and lifesteal, in short it's random, but it doesn't show me all 4 servers
 making it impossible to broadcast on all servers (lobby, kitpvp, creative and lifesteal).
I connected all the servers to the same database and it still doesn't solve the problem.

![Screenshot 2024-01-31 224040](https://github.com/kangarko/ChatControl-Red/assets/116310867/ee7cadbd-b0fc-42f3-b310-c85d81ff64a7)

**Comment by kangarko** [comment]
Sorry for the delay, investigating in 24h

**Comment by sl0wl0r1s** [comment]
> Sorry for the delay, investigating in 24h

Ty

**Comment by kangarko** [comment]
@james090500 this seems to be an issue with VelocityControl, can you please have a look? Should be fixed when VelocityControl does not clear the serverlist every time it receives the sync packet

This is how we do it on Spigot, we add new servers and rmv disconnected afterwards:

![a](https://i.imgur.com/fI0pKOs.png)

**Comment by sl0wl0r1s** [comment]
> @james090500 this seems to be an issue with VelocityControl, can you please have a look? Should be fixed when VelocityControl does not clear the serverlist every time it receives the sync packet
> 
> 
> 
> This is how we do it on Spigot, we add new servers and rmv disconnected afterwards:
> 
> 
> 
> ![a](https://i.imgur.com/fI0pKOs.png)

So what do I have to do?

**Comment by kangarko** [comment]
I pinged James, he's the developer for VelocityControl.  I unfortunately can't develop for Velocity so we'll have to wait for him.

**Comment by james090500** [comment]
I'll try fix this soon, I want to rewrite the entire velocity control at one point because it's a bit messy

**Comment by sl0wl0r1s** [comment]
> I'll try fix this soon, I want to rewrite the entire velocity control at one point because it's a bit messy 

Ty

**Comment by kangarko** [comment]
Thank you!

**Comment by kangarko** [comment]
@james090500 how is this going please?

**Comment by kangarko** [comment]
@james090500 can you update us on this please?

**Comment by PSYCHEER** [comment]
How its going? CHC now utilize the new modern paper chat event as say update log and good to see some update to get it properly working😄 and there's said I should update bungeecontrol but for velocity is this plugin unsuable so we need VelocityControl😄

**Comment by kangarko** [comment]
I am rewriting velocity plugin from the ground up. Please try this alpha version from the link below. It should update your old velocity config automatically if you rename the plugin folder to "VelocityControl".

[VelocityControl-1.0.0.zip](https://github.com/kangarko/ChatControl-Red/files/15013485/VelocityControl-1.0.0.zip)

**Comment by kangarko** [comment]
Closing since I strongly believe most issues have been resolved. Lets keep talking below should anything comes up.

**Comment by PSYCHEER** [comment]
Yeah it works! Thanks! Seeya on Discord later, I have there a one specific question :D

**Comment by kangarko** [comment]
Thanks! I typically dont answer on discord in a timely manner so I prefer if we kept chatting here or via email

**Comment by PSYCHEER** [comment]
> Thanks! I typically dont answer on discord in a timely manner so I prefer if we kept chatting here or via email

Tak máš email odo mňa❤️
