### ISSUE TITLE
Suggestion: Bossbar time

### ISSUE THREAD

**Issue by Zalaee** [kangarko/ChatControl#2559]
### Summary

Bossbar broadcast has a time option, i'd like to suggest a placeholder, preferably with papi support, that would output the time countdown in digits such as %time_left%.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Having this placeholder would allow making more interactive bossbar messages.

**Comment by kangarko** [comment]
Thanks! Right now no, but when I see multiple people ask for this I am happy to consider.
