### ISSUE TITLE
Permissions for specific the rules' txts

### ISSUE THREAD

**Issue by NotAHackedCookie** [kangarko/ChatControl#256]
Is there any permission to bypass a specific rules' txt?

**Comment by malonnnn** [comment]
https://github.com/kangarko/ChatControl/blob/master/rules/rules.txt

Line 9 explains it. Add this to the rule you want to bypass

ignore perm <permission>

**Comment by NotAHackedCookie** [comment]
yeah but I will have to give the permission to bypass all the rules txt

**Comment by malonnnn** [comment]
First you ask for a "specific rules txt" and now you're saying "all the rules txt"

Can you be more specific please

**Comment by NotAHackedCookie** [comment]
when I add ignore perm <permission> in a txt then I need to add the permission to bypass all the txt rules and the ignored permission. I want to only add the ignored permission and not the permission for all the rules

**Comment by kangarko** [comment]
Hey!

The permission "chatcontrol.bypass.rules" will make you ignore absolute all rules.

**Comment by kangarko** [comment]
Assuming fixed, closing.
