### ISSUE TITLE
Questions before purchasing a plugin

### ISSUE THREAD

**Issue by JedynyTakiPsiak** [kangarko/ChatControl#2560]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Haj o/
I know that after about an hour of intensive research on wiki, discord, etc. I MAY find the answers, but if there is a "question" label, I will use it.
I would like to ask a few questions about the "ChatControl Red" plugin because I am considering purchasing it :>
1. Is it possible to communicate between servers (via bungeecord), so that e.g. the administration or players can communicate with each other? Additionally, is there still a record of all logs on some mariadb site (as promoted)?
2. I couldn't find it (maybe I'm blind now xd) are there any forms of announcements etc.? I love using <center> and some automatic announcement every 10 minutes. Additionally, if it were the case (which many plugins do not have), each rank would be a different notification (no, the permission rule).
3. I saw a change in the video about mentions (@adasdas), will across bungee also work? or at least on individual servers?
4. if we have "mail" or another plugin via the API (I'm a little green in this, but I can handle it), to send a "letter" to a player, and the player got just this "mail", e.g. as "the mode got an update" v3.1.7 see what's new"?
5. Is there any mini "mail prioritization" system, e.g. to make a letter from an admin higher or highlighted differently in the entire list? It would add a lot of charm :>
6. and if we already have this "mail", when the player enters the server there is a chance (or it is already built-in) that the player will receive notifications in the form of not only chat messages but also an inscription as title/bossbar/sound (if there is any important message from admin/server)

**Comment by kangarko** [comment]
Hello,

1. Yes, thru chat channels. Yes, there is a record in /chc log.
2. Yes, thru /chc announce.
3. Yes, mentions work across bungee.
4. Not sure what you mean but you can use our /mail command or your plugin's one and disable our feature not to interfere.
5. No sorry.
6. No sorry, that would require a custom solution.
