### ISSUE TITLE
1.20.1: Linking Discord Account in DiscordSRV changes DiscordToMinecraftChat format.

### ISSUE THREAD

**Issue by RealisticCarrot** [kangarko/ChatControl#2562]
### "/version ChatControlRed" - plugin version

10.23.5

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

N/A

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14150620/debug.zip)

### Information about the issue/bug

Hello, my discord to Minecraft chat works fine if I don't link my discord account to discordSRV in /discordsrv link. But after I link it to discordSRV, it messes up the discord to Minecraft chat format. I will attach an image of me typing "test" from Discord to Minecraft before the link and after the link.

![image](https://github.com/kangarko/ChatControl-Red/assets/69768653/e5500b1c-a7e4-4108-8fab-e2ec82b6546b)

From the image, after the link, my in-game prefix and username with a colon suddenly pop up even though it is not part of my Discord to Minecraft chat format.

**Comment by kangarko** [comment]
Sorry for the delay, investigating in 24h

**Comment by RealisticCarrot** [comment]
> Sorry for the delay, investigating in 24h

Here is my config folder if you need to check my formatting, 
[Chatcontronconfig.zip](https://github.com/kangarko/ChatControl-Red/files/14174249/Chatcontronconfig.zip)

**Comment by kangarko** [comment]
Sorry, just noticed you were on outdated version, please try on 10.24.0 and let me know if it persists.

**Comment by RealisticCarrot** [comment]
> Sorry, just noticed you were on outdated version, please try on 10.24.0 and let me know if it persists.

I have updated to the latest version, but the issue persists. The discord to Minecraft format is still messed up when I verified my account on discordSRV.
![image](https://github.com/kangarko/ChatControl-Red/assets/69768653/31462305-cfca-435c-af1e-4dbc91bc3963)

**Comment by kangarko** [comment]
How did you setup your bot so it can receive private messages! I am not that good at this and my bot wont let me send him a message, so I cannot test it unfortunately:

![a](https://i.imgur.com/heuebXm.png)

**Comment by RealisticCarrot** [comment]
Hello, I followed this wiki to set up my discordSRV bot.
https://docs.discordsrv.com/master/installation/initial-setup/

Your server has to be online for the bot to be online. Also make sure you have your own bot token and discord channel ID.
![image](https://github.com/kangarko/ChatControl-Red/assets/69768653/070f0a2c-11f1-48a2-8e9c-1690f46335f1)

**Comment by kangarko** [comment]
Thanks, have you tried asking on discordsrv's discord whether they have a config option to disable that duplicate message?

**Comment by RealisticCarrot** [comment]
> Thanks, have you tried asking on discordsrv's discord whether they have a config option to disable that duplicate message?

I have opened a ticket but they said it was not caused by their plugin because the duplicated message bug did not happen when you are an unverified user. Your prefix and in-game name only suddenly shows after you verify your discord.

**Comment by kangarko** [comment]
Can you try setting Debug key in settings.yml to [discord] and then sending me the console log for A) unverified and B) verified user when they type from Discord?

**Comment by RealisticCarrot** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14228897/debug.zip)
[latest.log](https://github.com/kangarko/ChatControl-Red/files/14228898/latest.log)

**Comment by kangarko** [comment]
Apologizes for the delay. Can you try setting DiscordChatChannelDiscordToMinecraft to false in config.yml of DiscordSRV?

**Comment by RealisticCarrot** [comment]
> Apologizes for the delay. Can you try setting DiscordChatChannelDiscordToMinecraft to false in config.yml of DiscordSRV?

Hello. After I set that to false, anything sent to the Discord chat does not show up in Minecraft Server Chat.

**Comment by kangarko** [comment]
Ok I finally got the bot to work, unfortunately cant reproduce your issue:

![a](https://i.imgur.com/XketRP3.png)

For the record, here is my config.yml of Discord except bot token, try using that instead (make sure to link your own channels there): https://pastebin.com/BcnjtSrp

I suspect it's either some third party plugin or discord's config.yml issue right now, I am sorry I was unable to help.

**Comment by RealisticCarrot** [comment]
> Ok I finally got the bot to work, unfortunately cant reproduce your issue:
> 
> ![a](https://camo.githubusercontent.com/d2512eadc6fa3fcec314a7b4c1dff5d801e6620c1167b2e4d2820d210f994621/68747470733a2f2f692e696d6775722e636f6d2f586b65745250332e706e67)
> 
> For the record, here is my config.yml of Discord except bot token, try using that instead (make sure to link your own channels there): https://pastebin.com/BcnjtSrp
> 
> I suspect it's either some third party plugin or discord's config.yml issue right now, I am sorry I was unable to help.

Hello. The bug appears when you message from Discord to Minecraft before the link and after the link. You will notice that your prefix changes. Send a message on discord before you link your discord account and send a message on discord after you link your discord account:
![image](https://github.com/kangarko/ChatControl-Red/assets/69768653/5d8dcaea-2253-46cb-8043-b22e372d986c)

**Comment by kangarko** [comment]
Try to add the follow key-value pair to the format part that does show after linking but shouldn't:

`Sender_Condition: '{sender_is_discord}'`

If that does not help - How can I get your prefixes to show? Can you refer to the exact format parts which are on your picture?

**Comment by RealisticCarrot** [comment]
> Try to add the follow key-value pair to the format part that does show after linking but shouldn't:
> 
> 
> 
> `Sender_Condition: '{sender_is_discord}'`
> 
> 
> 
> If that does not help - How can I get your prefixes to show? Can you refer to the exact format parts which are on your picture?

In my formats/chat.yml, I have this part defined specifically for discord prefix:
![image](https://github.com/kangarko/ChatControl-Red/assets/69768653/8d521212-5f6a-4524-8262-aa2dcdfab46f)

"&f[&bDiscord &f| &a{top_role}&f] {name} »" should be the correct prefix for when users sent from the discord channel. 

But after user links their discord account using /link in game, their prefix is no longer "&f[&bDiscord &f| &a{top_role}&f] {name} »". 

It becomes mixed with all the prefixes defined in chat.yml for the player. It becomes "&8[&4X&8] &f :emerald:&e[&eLvl %mmocore_level% %mmocore_class%&e] &f[&bDiscord &f| &a{top_role}&f] {name} »&a{player_name}&7:" 

Which is not normal because "&8[&4X&8] &f :emerald:&e[&eLvl %mmocore_level% %mmocore_class%&e] &a{player_name}&7:" prefix is only for the players that send messages in Minecraft server chat.

If there is a sender condition that checks if the sender is in the Minecraft server (Sender_Condition: '{sender_is_MinecraftServer}') then chatcontrol can possibly ignore using the prefixes that are not supposed to be used if the sender is in discord. 

---------------------------------------

To make it clear:

Correct Discord Prefix: &f[&bDiscord &f| &a{top_role}&f] {name} »

Incorrect Discord Prefix: &8[&4X&8] &f :emerald:&e[&eLvl %mmocore_level% %mmocore_class%&e] &f[&bDiscord &f| &a{top_role}&f] {name} »&a{player_name}&7:

Before a user links their discord account, it is using the correct discord prefix.

After a user links their discord account, it is using the incorrect discord prefix.

This is for when the player messages on the discord channel to be displayed in the Minecraft server. So it's discordtoMinecraft.

**Comment by RealisticCarrot** [comment]
Nvm {sender_is_player} fixes this issue. Thanks for your help.
