### ISSUE TITLE
1.20.4: Players are not detected in other servers - Velocity

### ISSUE THREAD

**Issue by zestian56** [kangarko/ChatControl#2563]
### "/version ChatControlRed" - plugin version

10.23.9

### Are you using MySQL?

Yes

### "/chc debug" output (strongly recommended)

https://ufile.io/5giayiyr

### Information about the issue/bug

/msg , /tell commands are not working cross server, autocompletes only the users in the server, but not on other servers.
If you msg a user from other server it says the user is disconnected

This is happening since this version.
On ChatControl-Red-10.22.6 it works correctly

**Comment by kangarko** [comment]
Would you still need help? Mind sharing with others how you resolved it? Thanks.
