### ISSUE TITLE
Minecraft Version: 1.20.4

### ISSUE THREAD

**Issue by xskylite** [kangarko/ChatControl#2564]
### "/version ChatControlRed" - plugin version

10.23.2

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Don't work colors &a  #FF000 
Colors don't work due to line format
![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/1d5f7418-fdea-4a5d-966a-25b90839e128)

colors don't work in line format

**Comment by xskylite** [comment]
![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/442404ef-0848-46f2-8d85-d2c827f515c1)
and please add title message on mentions

![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/81f52987-4f8c-47ea-ae41-76706d09f2da)

**Comment by kangarko** [comment]
Sorry, looks like a technical limitation. I unfortunately dont have time to fix this right now but will keep an eye on it.
