### ISSUE TITLE
1.20.2 when /msg other players, it says that they are not online

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#2565]
### "/version ChatControlRed" - plugin version

10.23.8

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14176203/debug.zip)

### Information about the issue/bug

Send a message to an online player (via /msg), and it will say that he is not online

**Comment by kangarko** [comment]
![image](https://github.com/kangarko/ChatControl-Red/assets/1918426/91a0f3c5-f01c-448a-af80-9e6f44390b2e)

I apology, I can't reproduce on your install and no other plugins. Try on a stock server with ChatControl only. Looks like a plugin or a server conflict. (I tested without bungee)
