### ISSUE TITLE
Add user-written comments to not disappear in any yml file of CHCRED

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [kangarko/ChatControl#2566]
### Summary

Title says it all, i really want to have empty rows in some of my formats yml files aswell as comments too... tho they get deleted/removed fully when i reload plugin/restart server, i really want to make it more concise to understand for myself, thank you

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Simply not removing user written comments...

**Comment by kangarko** [comment]
We replace users' comments with our own ones to provide always-accurate documentation. It's a feature. You can keep your custom notes in files found in rules/ and messages/ folders.

**Comment by MotikaCraft-TheJoshua** [comment]
> We replace users' comments with our own ones to provide always-accurate documentation. It's a feature. You can keep your custom notes in files found in rules/ and messages/ folders.

I really think there should be way for us to have personal notes, that is basic thing... please think about it again

- I install CHCRED
- It generates default configs
- I head to `formats` folder
- I copy `chat.yml` or `global-chat.yml` to new file called `my-main-format.yml`, so i have now exact same content inside of it, and i am keeping the original (DEFAULT) yml file there only for "archiving" - only for documentation purposes; i from now on only use `my-main-format.yml` file for modifications.

This way I really would like to set my personal notes where i want, to have empty spaces where i want and i am not needing a documentation inside of files in form of comments, **because i am keeping original (default) files with present documentation/explanations UNTOUCHED**, this is crazy when you have a lot of it just so you know how you formatted something and if you have 2 parts to work with IF and IFNOT for specific group or user groups...

Please please think about this, this is so basic and SO NEEDED... please don't say "this is not priority", this is BASIC thing, please think about it..... i've been struggling with this also in CHCPRO, i really don't want to switch your plugins for anything else, this is so basic flexibility thing, at least add option in main config like
```yml
do-not-replace-user-comments-in-files:
- `formats/<filename>.yml`
```
I really need this, for years

**Comment by kangarko** [comment]
It is not that it is not a priority, it is intentional. We have a comment updater system written specifically for this purpose. I have thousands of users and we found through out the years that the majority prefers having up to date documentation right in the files. Thanks for your understanding. You can always have .txt files in plugin folder with your own notes.

**Comment by MotikaCraft-TheJoshua** [comment]
> It is not that it is not a priority, it is intentional. We have a comment updater system written specifically for this purpose. I have thousands of users and we found through out the years that the majority prefers having up to date documentation right in the files. Thanks for your understanding. You can always have .txt files in plugin folder with your own notes.

With all respect, why cannot you add what I mentioned? OPTIONAL thing? Why can't you make not all files but only default files to work with comments, so when i create "my-own-formatting.yml" it will not apply comments

I don't need notes man, i need notes right above part of formatting, to write what i use it for, i have pretty complex system and i need spacings (empty lines), why cannot you make this, optional thing, this is not strict, let it by default regenerate official comments but please let us have freedom of commenting, why you have to do this?

**Comment by MotikaCraft-TheJoshua** [comment]
@kangarko i sometimes create part of format, and i need to comment it, i just need to temporarily disable it - comment it out, and reload plugin and test some with some other part, i sometimes need to switch

And don't tell me "then just leave your notepad open", i can't control that, i can leave it open, maybe my PC shuts down from electricity shutdown, maybe my PC crashes / BSOD happens, i don't understand what is the problem here really, why you entirely disabled thing that is widely used everywhere and always, removing it and replacing with your own, how is that 100% flexible for work, i sometimes need to make really a lot of parts and it is really frustrating, why can't there be an option to whitelist what files not to apply documentation comments, please...

**Comment by MotikaCraft-TheJoshua** [comment]
It slows me down by so much, i cannot be creative 247, some of us are not artsy and are black-white brained, when i get some idea of how to format chat (or either TABlist or scoreboard), when i set it up i really don't want it to be gone because if it is gone i will lose 2 hours to create something new/unique, my brain is just stupid for creativity, or when i disable it and want to use other one, and i disable it by commenting it because it speeds me up time, you always talk in your videos about speeding up time and now you give say this:


> It is not that it is not a priority, it is intentional. We have a comment updater system written specifically for this purpose. I have thousands of users and we found through out the years that the majority prefers having up to date documentation right in the files. Thanks for your understanding. You can always have .txt files in plugin folder with your own notes.

It is a bit contradictory to talk always in your videos about speeding up process of testing things, and then make your 10 year old plugin with no flexibility for years, i have been using CHCPRO for a long time and never wanted to switch from it, if you need for verification please tell me because i don't know what else could be problem here to MAKE IT OPTIONAL(?) why does that hurt performance of plugin? Please...

**Comment by kangarko** [comment]
Thanks for the feedback. However the decision has been made from a large body of customers who'd prefer to have up to date comments. I am happy accepting contributions to the [class responsible for saving comments](https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/settings/YamlComments.java) because it does support "ignored sections" where auto-update does not happen, but without comments. I do not have time for this at the moment and I cannot please everyone, every time there is a change someone is displeased, please understand and respect that.
