### ISSUE TITLE
"handling player data causing main thread blocking"

### ISSUE THREAD

**Issue by alfoons** [kangarko/ChatControl#2568]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

"chatcontrolred seems to be saving and writing from file on the main server-thread.
while saving and writing to file itself might not be be a bad way to handle player data, doing it on the main thread causes momentary lag spikes due to file writing/reading being a blocking task.
could you guys publish an update to make that async (offthread)?"

**Comment by kangarko** [comment]
Use mysql to minimize disk writes please.
