### ISSUE TITLE
One of the most needed features that all plugin have, but CHC does not.

### ISSUE THREAD

**Issue by nezoxclipss** [kangarko/ChatControl#2569]
### Summary

I'm writing about a feature with global and local chat. At the moment, the players are not very developed, so it is very difficult for them to use and move between chats. It’s very cool that CHC has everything you need, except for 1 feature - it’s impossible to get into the global/local chat using a special character or without it.
For example, all servers have global messages with !message and local ones without anything. In my opinion, this is the most important feature that every chat plugin should have. 

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

A lot of my friends didn’t buy the plugin because this feature wasn’t in it. It is needed on almost every server.

**Comment by kangarko** [comment]
Sorry for not mentioning it clearly enough.

https://github.com/kangarko/ChatControl-Red/wiki/Channels#use-special-character-like--to-send-message-to-globalrange

Guess you need to tell all of your friends now.
