### ISSUE TITLE
[Request] Hexcode formatting

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#257]
My players are used to {#hexcode} since that is the hexcode many plugins use like CMI, HyperDrive etc.
I would like to ask if it's possible to make {#hexcode} work along side the current one so it's not becoming confusing for players.

**Comment by kangarko** [comment]
Doesn't it work already? We should have a compatibility for that on some places.

Regarding the other places, I left it out intentionally since parsing regular expressions twice would effectively half the plugin's performance for these parts of chat.

**Comment by Sikatsu** [comment]
Ah, I tried using it in combination with /nick, that doesn't work however.

**Comment by ElBananaa** [comment]
Hey! I just tried, and it looks like the {#hexcode} format can't be used in chat.
For the nick thing, it looks like the colors aren't used. So basically, if I use: `/nick #4287f5Test` it'll say something like `Nick changed for Test` but the colors aren't shown.

**Comment by kangarko** [comment]
Okay so I looked at the code and right now the best we can do, is just to support #syntax, not both. It would decrease performance by 2x since we'd have to scan the message twice. If our syntax does not work somewhere please comment below and I'll fix this.

**Comment by Sikatsu** [comment]
Ah, sad. Would be easier for players if it was all the same formatting haha.
