### ISSUE TITLE
1.20.4: Denizen chat events doesnt work

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#2570]
### "/version ChatControlRed" - plugin version

10.24.2

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14224934/debug.zip)

### Information about the issue/bug

I cant use the "on player chat" and "after player chat" event from denizen. It simply doesnt get called, even if i change the listener priority. Tested it on my Server within my Velocity network. And with a minimal Setup. I send the chcr data of the minimal setup, its just a basic paper Server with no proxy.

And the Denizen script. I had to zip it to upload it here.
[chat-test-script.zip](https://github.com/kangarko/ChatControl-Red/files/14224955/chat-test-script.zip)

Is there anything to do about it?

**Comment by Lorias-Jak** [comment]
Edit, i tried the "ignorecancelled:true" method too. But it doesnt work as well
![image](https://github.com/kangarko/ChatControl-Red/assets/62625225/8d6d0a5b-e20c-487b-b962-ca2034b984a9)

**Comment by Lorias-Jak** [comment]
Edit: I think i got it running to fire the event. The next problem is, that i cant cancel the event from denizen. ChatControl still reacts and does it's thing, when i try to cancel the event
![image](https://github.com/kangarko/ChatControl-Red/assets/62625225/944edc88-f204-4b59-a6ba-510064470284)
![image](https://github.com/kangarko/ChatControl-Red/assets/62625225/2e46f48e-8d87-442b-b79c-7f5425c34544)

**Comment by kangarko** [comment]
Unfortunately we cancel the chat event making it incompatible by default.

However, you can try changing the listener priority from LOWEST to HIGHEST or even MONITOR to see if one of them fixes it: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

**Comment by Lorias-Jak** [comment]
Nah it sadly doesnt help for canceling the chat event via denizen. We cant work with Chat-Interceptors like this. An important feature for us

**Comment by kangarko** [comment]
We support the legacy chat event which does not let us send messages in the interactive click/hover format, hence we need to cancel it and send it in our own unique way.

Most people found solutions by changing the event priorities as I described above, have you tried that?
