### ISSUE TITLE
1.20.4: DisguiseAPI Not working

### ISSUE THREAD

**Issue by zestian56** [kangarko/ChatControl#2571]
### "/version ChatControlRed" - plugin version

10.23.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

When chaning a username nick, with Hynick that uses DisguiseAPI.

The user cant chat, since it says its not joined to a channel:
![image](https://github.com/kangarko/ChatControl-Red/assets/29008143/15fdf181-aaae-4a3b-be61-e76f1820842c)

If i remove the nick it works back again.

**Comment by kangarko** [comment]
I am sorry, this is incompatible. We support Essentials and CMI nicks as well as our own system for tags.

**Comment by zestian56** [comment]
@kangarko Is there a workaround that i can use? I really want to implement a nick system, but right now chatcontrol and essentials nick doesnt fullfill my needs

**Comment by kangarko** [comment]
Unfortunately, at this time not. We can just refund you if you email us.
