### ISSUE TITLE
Suggestion: Add %sender% (representing sender's username/player_name) variable for global use

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [kangarko/ChatControl#2573]
### Summary

I need this variable to be used inside of formats "Receiver_Condition", i found out that there is no adequate placeholder and i really need this one

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Simply this will add +1 placeholder to the list which can be very useful

**Comment by kangarko** [comment]
Sorry for the delay, sure, I can have a look on Monday.

**Comment by MotikaCraft-TheJoshua** [comment]
Thank you so much!

**Comment by kangarko** [comment]
Added: {sender} to supported variables and format keys.

**Comment by MotikaCraft-TheJoshua** [comment]
> Added: {sender} to supported variables and format keys.

Nice, thank you very much

I tried to find an edit button on github wiki but i couldn't, probably i am not able to edit it or PR edits (i don't remember how does it work)
Aswell this {sender} and there are some other placeholders that are natively there from CHCRED but not mentioned anywhere on wiki/Variables so wanted to ask you to add it for future usage (when you can of course)

More specifically, i don't see (i'll check again later but i already checked 3 times) anywhere mentioned that + can be inside of placeholder but at the beginning so like `{+placeholder}`

**Comment by kangarko** [comment]
Thanks! I've added these to the wiki: https://github.com/kangarko/ChatControl-Red/wiki/Variables#the--plus-letter-and-trailing-space-removal
