### ISSUE TITLE
1.20.4: Velocity integration broken

### ISSUE THREAD

**Issue by Geitenijs** [kangarko/ChatControl#2576]
### "/version ChatControlRed" - plugin version

10.24.2

### Are you using MySQL?

Yes

### Information about the issue/bug

Hi there, I just updated to CHC 10.24.2 and to my surprise the integration with VelocityControl is no longer working.
I suppose it has to do with the BungeeCord changes introduced in earlier CHC versions, but unfortunately there's no update for VelocityControl yet.
Is this something I can fix myself or should I wait for a new release of VC?

**Comment by zestian56** [comment]
@Geitenijs I had the same issue, what happened to me is that on newest chat control there is a new file called bungee.yml. You need to enable it in there

**Comment by Geitenijs** [comment]
@zestian56 Right, I see. Thanks for your help!

**Comment by kangarko** [comment]
@james090500 can you please account for the new update and add a notification instead of the error? Thanks.
