### ISSUE TITLE
1.20.4: ChatControl event priority not working as expected

### ISSUE THREAD

**Issue by zestian56** [kangarko/ChatControl#2577]
### "/version ChatControlRed" - plugin version

10.23.9

### Are you using MySQL?

No

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

https://ufile.io/xndvu050

### Information about the issue/bug

Hello, currently im creating a plugin and i need to disable the chatEvent. However im unable to do that (the issue is on chat control)

i have already  added the LOWEST priority 
![image](https://github.com/kangarko/ChatControl-Red/assets/29008143/aaa724a4-6a52-40bc-a9ff-1b3ef567bb93)

and i have tested from HIGH to MONITOR, and none of them seems to cancel the event... if i do this without chatcontrol it works correctly
![image](https://github.com/kangarko/ChatControl-Red/assets/29008143/1577b133-67f4-4590-8fe7-d136515d05c3)

**Comment by kangarko** [comment]
Hello, please switch it. Have your plugin listen on LOWEST so it cancels the event first and leave ChatControl at NORMAL.
