### ISSUE TITLE
Not work integrate DiscordSRV and bungee mode 1.20.4

### ISSUE THREAD

**Issue by xskylite** [kangarko/ChatControl#2578]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/04cf28e0-5949-4b59-b0d3-bdd9b7dcc3fd)
![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/a35f112b-79c4-4c3a-bb3b-a1d891fa73dc)

After migration my integration stopped working
ChatControl Version: 10.24.1

Velocity:
![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/0b456293-f9d9-4ab7-a30d-a0df5233bb59)
![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/fbd0f588-0e10-49f2-a91a-aceed59aac31)
![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/00b78328-dc77-4eee-8d7c-a92f846c86b9)
![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/026f082c-f0db-408e-bbfe-11a48fa0362d)
there is no lobby 1 server.

**Comment by xskylite** [comment]
before migration
![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/98a341bf-94ab-429f-9fdb-14a0a5827c14)
![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/e7516271-e999-4202-902a-ab8d17eafaa9)

**Comment by xSviatoslaw** [comment]
Sorry everything is already working the problem with velocity itself went away, but the problem with DiscordSRV after I updated it to the latest version.

**Comment by xskylite** [comment]
Sorry everything is already working the problem with velocity itself went away, but the problem with DiscordSRV after I updated it to the latest version.

**Comment by kangarko** [comment]
Happy to hear it got resolved, let me know if there is anything else I can help you with.
