### ISSUE TITLE
[PRO] "Regex capturing groups" works very bad.

### ISSUE THREAD

**Issue by Hdadaw** [kangarko/ChatControl#258]
I'm using ChatControl Pro
I need to display the balance information in the "actionbar".
I wrote the rule in "packets.txt":

```
match ^\[Money\] Balance\:(.*)
then replace &6Balance:&e$1
then actionbar &6Balance:&e$1
```

But I get this result:
![javaw_2017-09-25_10-59-38](https://user-images.githubusercontent.com/32250813/30790933-b2f51e2c-a1e1-11e7-9e0a-b5e9c180bada.png)
And the output of the captured group does not work if i change "then replace" to "then rewrite".

Please, fix it.

UPD: It turns out that the use of captured groups in player and server commands also does not work.

**Comment by kangarko** [comment]
Hello,

I am very sorry to inform you that this functionality was not covered by the time that engine was written.

I have added it to ChatControl Pro over the years, but since how much has changed it will not be backported. Thank you for your understanding.

**Comment by kangarko** [comment]
Please try

`match ^(\[Money\] Balance\:)(.*)`

and then perhaps $0 or $2 even, just to test it out. I am pretty confident it should work.

**Comment by Hdadaw** [comment]
Oh, it really works, thanks for the help!
And I think it would be useful to add to the rules file that it is necessary to take in the group the first part of the regular expression.

**Comment by kangarko** [comment]
Added, thanks!
