### ISSUE TITLE
[Issue] Nickname colors

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#258]
When you use a color / hexcolor in your nickname which you don't have permission for, the plugin sets your nickname to gray rather then white.

Minecraft: 1.16.4
Bungee: true
MySQL: true

**Comment by kangarko** [comment]
Thanks, however this is not a high priority bug so I am closing this and will return later as I have more time.

**Comment by Sikatsu** [comment]
Understandable, except that players can now all get the gray nickname that I don't want them to use/have..

**Comment by Sikatsu** [comment]
And once it does get fixed, how do I set it all back to white for them?
