### ISSUE TITLE
Editing a message

### ISSUE THREAD

**Issue by nezoxclipss** [kangarko/ChatControl#2580]
### Summary

Hello, I want to write about adding such a feature to ChatControl Red as editing chat messages.  Quite often a useful thing.  Here's what I suggest for it: 1. Editing the message after sending.  2. Possibility of adding it as a button.  3. The admin can edit any message in the chat.  4. Editing a personal message.  5. Selection in the config: 5.1: When you click on the edit button, the message that you wrote before will immediately appear.  5.2: When you click on the edit button, you will have to write a message from scratch.  That's all I want to add.  It would also be cool to add chat secrecy, that is, so that only personal/server messages are sent to the chat if desired.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

It is just super cool.

**Comment by kangarko** [comment]
Thank you. However at this time, I dont have the capacity for this. I will put it to the backburner for considering at the next major rewrite.
