### ISSUE TITLE
Minecraft Version: 1.20.4 | How to crash the server

### ISSUE THREAD

**Issue by danieliustt** [kangarko/ChatControl#2582]
### "/version ChatControlRed" - plugin version

10.24.4

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/69b7609e7c404f03b902409a23ea0987

### Information about the issue/bug

Problem: /msg name "bay"

**Comment by kangarko** [comment]
Hey! Thanks for reporting but that would need to go the Paper or even Mojang's bug tracker. I cannot find chatcontrol on the stack trace and looks like the loop is in the NBT
