### ISSUE TITLE
Receiver and sender group variables

### ISSUE THREAD

**Issue by envizar** [kangarko/ChatControl#2583]
### Summary

add `{receiver_group}` and `{sender_group}` variables

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

This feature adds more customization to pm formatting

**Comment by kangarko** [comment]
What is the "group" - is it the permissions group from like LuckPerms?

**Comment by envizar** [comment]
Yes, it's like `{player_group}`, but usable in `formats/pm-sender.yml` and `formats/pm-receiver.yml`

**Comment by envizar** [comment]
Is it possible to get sender's prefix/suffix/group using javascript?

**Comment by envizar** [comment]
@kangarko will you add `{receiver_group}` and `{sender_group}`? It's small feature, but it will be very useful

**Comment by kangarko** [comment]
Probably not using JS since we dont pass the sender object there. It's a small feature but not requested by anyone except you and there are some technicalities to add it, I am happy to add it once more people support this idea.
