### ISSUE TITLE
when I type this in chat it should show but it doesn't

### ISSUE THREAD

**Issue by Dsngxddd** [kangarko/ChatControl#2584]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

when I type this in chat it should show but it doesn't 
[Uploading archive-2024-02-24T162652Z.tar.gz…]()

**Comment by Dsngxddd** [comment]
> ### Are you using MySQL?
> Yes
> 
> ### Are you using BungeeCord/Velocity?
> Yes - BungeeCord
> 
> ### Question
> when I type this in chat it should show but it doesn't Uploading archive-2024-02-24T162652Z.tar.gz…


![image](https://github.com/kangarko/ChatControl-Red/assets/113624264/425db937-5faf-43aa-9723-288d1785d87c)

**Comment by kangarko** [comment]
This is not a placeholder that we have... You can try installing PlaceholderAPI and using the {variable_syntax} from it instead.
