### ISSUE TITLE
1.20.1: BetterTeams Team Chat isn't working

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2586]
### "/version ChatControlRed" - plugin version

10.24

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Hello, BetterTeams plugin chat isn't working. When you create team using /team create, and then /team chat, it should send the message with special format into the team chat so no one else than from your team cannot see it. But unfortunately, it doesn't change the format, and everyone see it.

There are also prefixes since the latest version for ? ! which should work too, but they do not work.

I asked the dev on Discord, and they told me to come to you with the source code of all the /team chat functionality https://github.com/booksaw/BetterTeams/blob/master/src/main/java/com/booksaw/betterTeams/events/ChatManagement.java#L34
![image](https://github.com/kangarko/ChatControl-Red/assets/18662086/0005f0c7-404b-4f5b-a915-77c5a229c68e)
As you see, the format wasn't changed & it was sent to everyone
![image](https://github.com/kangarko/ChatControl-Red/assets/18662086/412c11d8-95ff-4792-a797-474be73dcb19)

This doesn't wok neither.

Both work without the chatcontrolred

https://www.spigotmc.org/resources/better-teams.17129/

**Comment by kangarko** [comment]
Try all priorities from LOWEST to MONITOR as described here to see if any will get the job done: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities
