### ISSUE TITLE
Tested on 1.8.8 and 1.20.4: <center> tag visible in /chc tour list

### ISSUE THREAD

**Issue by 10Meisterbaelle** [kangarko/ChatControl#2588]
### "/version ChatControlRed" - plugin version

10.24.5

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

Occurs on a freshly installed instance; if it can't be reproduced I'll send it.

### Information about the issue/bug

On command /chc tour list:
![screenshot](https://github.com/kangarko/ChatControl-Red/assets/45918080/ba39df33-6242-4da8-948c-c5d91ef808e6)
This issue also occurs in other places with /chc tour.

**Comment by kangarko** [comment]
Good catch!

Thanks, fixed <3
