### ISSUE TITLE
All versions: Luckperms enable-ops: false overrides rules for /op

### ISSUE THREAD

**Issue by 10Meisterbaelle** [kangarko/ChatControl#2589]
### "/version ChatControlRed" - plugin version

10.24.5

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

If enable-ops is set to false, LuckPerms overrides the /op message, which won't be overridden again by any rules. I don't know if there is an easy way to fix this, but I will report it regardless.

**Comment by kangarko** [comment]
Unfortunately no easy way to fix, it's caused by LP's behavior.
