### ISSUE TITLE
1.20.4: How do I block tab-completion of commands in Bungeecord?

### ISSUE THREAD

**Issue by 10Meisterbaelle** [kangarko/ChatControl#2590]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

How do I block tab-completion of commands in Bungeecord? I can only seem to find the option to filter arguments, but no option to filter the commands themselves.

**Comment by kangarko** [comment]
We unfortunately don't have that option for bungee.

**Comment by 10Meisterbaelle** [comment]
Ok, I'll submit it as a feature request then
