### ISSUE TITLE
/chatbypass as a "sudo" for admins without bypass permission for continued false positive detection 

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2591]
### Summary

Requesting /chatbypass that goes before whatever you are doing in chat to temp run whatever you are trying to run by bypasses all rules.

I prefer admins and mods to not bypass chat rules so that they can pick up false positives, as they seem to be the only people that report them and we have close communication.

This comes from an odd one, we had a player log in with the username "IDotnet", admin greeted them and got blocked because Thier username matches the regex for domain names!

We wouldn't have been warned about this issue if they had a bypass permission so most likely wouldn't have come up, this would have prevented players being able to interact with the player!

So comes the idea of a quick bypass command so that mods and admins can quickly bypass if required, say if they needed to ban, but it keeps the false positives coming in for us to adjust rules!

Also I have no idea what the best course of action is for someone with a username like this...

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Create some crappy command that temp adds the bypass permissions for a set time to run the commands they need that auto expire.

**Comment by TomLewis** [comment]
To fix player names not being filtered, just include online usernames into the word whitelist.

**Comment by kangarko** [comment]
Thanks, unfortunately this is an odd case I have no extra time for, and therefore won't be implementing this.
