### ISSUE TITLE
Option to entirely disable chat reporting feature

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2592]
### Summary

This has been bothering me for a while now. Ever since 1.19+, ChatControl never had a proper way to disable the chat reporting feature, even though claiming to have the control over the entire chat.

To disable the chat reporting feature (and popup), I have been using FreedomChat alongside ChatControl.

That is why I propose to include the FreedomChat's way of disabling the chat into ChatControl's settings (for 1.19+ servers).

FreedomChat, as opposed to AntiPopup, is just a few lines of code, making it easy to implement into ChatControl and has zero known incompatibilities.

The setting would be called `DisableChatReporting: true/false` and if `true`, would act as if you had FreedomChat installed with config options `rewrite-chat` (removes chat reporting) and `claim-secure-chat-enforced` (removes popup) enabled.

https://github.com/ocelotpotpie/FreedomChat

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Nothing, would have to always use more chat plugins instead of just one.

**Comment by kangarko** [comment]
Please keep using FreedomChat, I don't have time maintaining that extra functionality.
