### ISSUE TITLE
1.8: Chat Cooldown doesn't work if < 20 ticks

### ISSUE THREAD

**Issue by lulu2002** [kangarko/ChatControl#2593]
### "/version ChatControlRed" - plugin version

10.24.5

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Just like the title says, easy to reproduce, but if there's more information I should provide (like that doesn't happened in your testing) please let me know!

1 second for chat delay is too long for my server, I would like to make it to 10 ticks.

**Comment by kangarko** [comment]
This is limited to 1 second due to performance savings and we are not planning to reduce this delay for the time being.
