### ISSUE TITLE
I get error when I click [X] to delete the message

### ISSUE THREAD

**Issue by Kyle20192005** [kangarko/ChatControl#2594]
### "/version ChatControlRed" - plugin version

10.24.6

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/5ec575ad9ed94e9297b3fbce68e1bd43

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14462468/debug.zip)

### Information about the issue/bug

produce some solutions

**Comment by kangarko** [comment]
Do not reload and check that you are on a compatible ProtocolLib version.
