### ISSUE TITLE
1.20.4: Not working VelocityControl plugin

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2595]
### "/version ChatControlRed" - plugin version

10.24.6

### Are you using MySQL?

Yes

### Information about the issue/bug

https://paste.gg/p/anonymous/b68ee691b8b248839e5f53314274b000 Hello, seems that the plugin cannot be even loaded on the newest velocity version

**Comment by kangarko** [comment]
@james090500 can you please have a look asap?

**Comment by kangarko** [comment]
@james090500

**Comment by AminGHG** [comment]
@james090500

**Comment by kangarko** [comment]
Fixed on 3.11.7:

https://github.com/kangarko/VelocityControl/releases/tag/3.11.7

![a](https://i.imgur.com/ceBkySE.png)

**Comment by bobhenl** [comment]
Strange, I had 3.11.7 as you can see on the paste https://paste.gg/p/anonymous/b68ee691b8b248839e5f53314274b000 @kangarko

**Comment by kangarko** [comment]
And your velocity version? Try redownloading again in case the jar got corrupted. I literally just downloaded it from Releases
