### ISSUE TITLE
1.20.4 Paper #436 Tablist not updating

### ISSUE THREAD

**Issue by Denial234** [kangarko/ChatControl#2596]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

When i enabled the tab list function in settings.yml i didn't think much off it since it seemed to work with the fact that i changed nick using /tag nick and the tab list updated just fine. But as soon as i updated my prefix and suffix through my Permissions plugin the tab list didn't seem to want to change the prefix or suffix in the tab. It only changed once i rejoined the server. Is this a bug or am i doing something wrong?

Keep in mind that i only use /tag nick for nicknames and have only enabled ApplyOn for nick since i'm not changing my prefix or suffix using that feature but instead use PlaceholderAPI for my suffix and {player_prefix+} for my prefix.

My format:   
  Format: '{player_prefix+}&f{player_nick}%supremetags_tag%'

Only the nick through /tag nick seem to want to change the {player_nick} on the tab list but won't update when i change the other two placeholders by assigning the player to a different group with a different prefix or tag with another suffix.

**Comment by kangarko** [comment]
Hello, looks like that other permission plugin is incompatible. I would recommend getting a separate tab plugin in your case unfortunately.
