### ISSUE TITLE
Add support for: Ultra Permissions by TechsCode

### ISSUE THREAD

**Issue by Denial234** [kangarko/ChatControl#2597]
### Summary

I heard the permissions plugin that i use wasn't supported for the tab list to update with my prefixes that i setup on the server. It would be absolutely if support was added for it ^^ Love this plugin, this is the only thing thats needed for it to be an 11/10 haha

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Ultra Permissions is a premium permissions plugin and it has over 5,000 purchases on SpigotMC. I'd say it's very popular and a lot of people have paid for it. Unfortunately it's not as popular in terms of plugins that support it and i don't know why. But it would be absolutely amazing if support was added ^^

**Comment by kangarko** [comment]
Thanks for the suggestion. I recommend you talk to their authors and suggest adding a variable to PlaceholderAPI since we already support that instead.
