### ISSUE TITLE
1.20.4: Is it possible to set chat color per group?

### ISSUE THREAD

**Issue by Denial234** [kangarko/ChatControl#2598]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I know its possible to set a chat color per player using /chc color but is it or could it be possible to add a way of setting a chat color for a specific group as their default color? Or just set the default color on join for everyone / new players?

**Comment by kangarko** [comment]
You can install Vault and PlaceholderAPI and place the variable indicating a group's color from PlaceholderAPI to your format part before the {message} variable. That way PlaceholderAPI will pull up the color from your permissions plugin automatically.
