### ISSUE TITLE
1.20.4: Is there a way to limit [item] in chat with a permission?

### ISSUE THREAD

**Issue by Denial234** [kangarko/ChatControl#2599]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Is it possible to only allow people with a specific permission to use [item] in chat?

**Comment by Hatsuharu33227** [comment]
You can try to add Sender_Permission: 'something.you.want' in item.yml

**Comment by Denial234** [comment]
> ###

That actually works ^^ but instead of returning the message as [item] in chat, it just leaves the message blank.

**Comment by kangarko** [comment]
That is a technical limitation, I will try to work this around in the next major release.
