### ISSUE TITLE
[1.8.8] InventoryCreativeEvent Mail error

### ISSUE THREAD

**Issue by haeiven** [kangarko/ChatControl#26]
No idea why it happened... I was just in my creative inventory, i didn't used any command related to mails before.

https://paste.soleria.eu/vibisujuro.pl

**Comment by ElBananaa** [comment]
I have the same issue under Paper 1.16.4, Java 14, CHC 10.0.1

**Comment by kangarko** [comment]
Thank you I will fix that in a few hours!
