### ISSUE TITLE
Swearwords beginning with a color code

### ISSUE THREAD

**Issue by adopted3** [kangarko/ChatControl#26]
Hi!

This isn't a bug, but more of a question...

All the default/sample swears begin with \b, which is good, but prevents swears that a player prefixed with a color code, such as &cShit.

I'm sure I can fix this by going through and changing every `\b` prefix to `\b(\&.)?` correct?

Or, is there a simpler way around this? I'm just not sure why the default swears only had `\b`.

Thanks!

**Comment by kangarko** [comment]
Hey,

you just got a brilliant idea! I just tested replacing \b with `\b(\&.)?` but unfortunately it did not work. I am not that good at regex, so it would be greatly appreciated if you would find a solution. PS: For testing, I recommend using https://regex101.com,

**Comment by kangarko** [comment]
Tested now, filters do also work when a colour is specified in front of them.
