### ISSUE TITLE
Plugin not compatible with BetterNick.

### ISSUE THREAD

**Issue by LoYungSum** [kangarko/ChatControl#260]
I have this plugin called BetterNick, it does the same thing with EssentialsNick, but it has more features, such as API, custom prefix, custom suffix, etc. Link to the plugin: https://www.spigotmc.org/resources/better-nick-api-1-8-3-1-12-2.39633/

A proof: https://imgur.com/a/dfZTH  (I still have the [Admin] tag)

**Comment by malonnnn** [comment]
where is the [Admin] tag coming from?

**Comment by LoYungSum** [comment]
Come from PEX, admin group with [Admin] tag

**Comment by kangarko** [comment]
How it is not compatible?

**Comment by LoYungSum** [comment]
After I nick, I want to change the prefix to the BetterNick's prefix (after you nick, betternick will you give you a prefix in the config.yml)

**Comment by kangarko** [comment]
From the image you've posted, I see that your nick has been displayed correctly.

I don't understand your question, sorry.

**Comment by LoYungSum** [comment]
k

**Comment by kangarko** [comment]
Closing this in faith that this has been resolved.
