### ISSUE TITLE
Suggestion: Add %receiver% variable for global/javascript

### ISSUE THREAD

**Issue by Hatsuharu33227** [kangarko/ChatControl#2600]
### Summary

I need this variable to check if player afk with reason then printout like "{receiver} is afking since {my_js_here}" when someone pm t hat player.

P.S EssentialsX's afk

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

That is hard to run my javascript for checking {receiver} by adding customer variabe in messages_en.yml.

`hasAFKReason();
function hasAFKReason() {
return "is afking since %essentials_afk_reason%"
}
`

**Comment by kangarko** [comment]
This is unsupported due to technical reasons right now unfortunately.
