### ISSUE TITLE
1.20.4: {player_group} isn't working in messages/quit.rs

### ISSUE THREAD

**Issue by envizar** [kangarko/ChatControl#2602]
### "/version ChatControlRed" - plugin version

10.24.6

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

`{player_group}` isn't working in `messages/quit.rs`
![изображение](https://github.com/kangarko/ChatControl-Red/assets/87126318/22c211c2-ab23-46ac-9cae-bdb90e456a16)
![изображение](https://github.com/kangarko/ChatControl-Red/assets/87126318/08749959-5c08-4da7-bf2e-7858a0c4e7ec)

**Comment by envizar** [comment]
`{player_prefix}` and `{player_suffix}` also don't work

**Comment by kangarko** [comment]
At the time when the player quits, bukkit fires the event with limited player instance since he already disconnected and thus these variables which require an online player won't work.

**Comment by envizar** [comment]
> At the time when the player quits, bukkit fires the event with limited player instance since he already disconnected and thus these variables which require an online player won't work.

You can just request data from luckperms, it works even for offline players

**Comment by kangarko** [comment]
I believe we already do, check if you are NOT having async option for leave messages in settings.yml > Messages.Async
