### ISSUE TITLE
1.20.4 PlayerName to Discord

### ISSUE THREAD

**Issue by Hatsuharu33227** [kangarko/ChatControl#2603]
### "/version ChatControlRed" - plugin version

10.24.6

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

I am using the default settings for the format
`Format_Discord: '**{player}**: {message}`
The problem is when a player named "_Player_" chat in game -> discord, that will be -> **_Player_**: test <- show on discord chat.
How can I remove the italics for player name? Thanks.

**Comment by kangarko** [comment]
No idea, I recommend get rid of these weird discord names like Player since it's generally incompatible

**Comment by Hatsuharu33227** [comment]
Not discord's name, is Minecraft's player name. Some of them named "_SomeName_"

**Comment by kangarko** [comment]
I'll investigate in 1-2 days.

**Comment by kangarko** [comment]
Apologizes very much for delay, I accidentally hit "Mark as read". Going thru this asap.

**Comment by kangarko** [comment]
Should not happen on the latest version:

![a](https://i.imgur.com/0nrjEgE.png)

If still it does then try disabling Send_Messages_As_Bot or Webhook options in settings.yml for discord
