### ISSUE TITLE
Block tab-completion of commands in Bungeecord

### ISSUE THREAD

**Issue by 10Meisterbaelle** [kangarko/ChatControl#2604]
### Summary

This feature should allow you to block the tab-completion of Bungeecord commands in BungeeControl-Red in (this should also be added for Velocity and VelocityControl-Red) in a similar fashion to Spigot commands inside the BungeeControl-Red (or VelocityControl-Red) config file.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

On Spigot, you have the ability to hide commands from tab completion, but after doing that, certain commands in Bungeecord can still be tab completed, which stops the tab completion suggestions from looking clean.

**Comment by kangarko** [comment]
@james090500 would you have time for something like this please?

**Comment by kangarko** [comment]
Closing, our dev is very busy on networking part and we already handle this on spigot. You can just configure this on each bukkit server and use a third party plugin for network level filtering.
