### ISSUE TITLE
10.24.6: Chat Colors

### ISSUE THREAD

**Issue by bogdanW11** [kangarko/ChatControl#2605]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

So, I dont know how to toggle off the players chat colors, I have tried from settings.yml but I dont understand how.

![1d](https://github.com/kangarko/ChatControl-Red/assets/132227015/e32fc949-93bb-4dfe-9890-f0ba3a0425d5)
![Screenshot 2024-03-12 163809](https://github.com/kangarko/ChatControl-Red/assets/132227015/7f48b041-a9d8-497c-b986-1a2173f4af15)

**Comment by kangarko** [comment]
Hey! Sorry for a late reply. To turn off players colors in chat, leave Colors.Apply_On to an array list of values excluding "chat".

Your second screenshot is correct.

**Comment by kangarko** [comment]
If it still does not work then it's coming from another plugin
