### ISSUE TITLE
Error on Death: 1.20.4

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2606]
### "/version ChatControlRed" - plugin version

10.24.6

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/5062bd08c45549059caac51a61d6e270

### Information about the issue/bug

Seems to happen randomly on certain player death, this particular one was due to a baby drowned killing a player.

**Comment by kangarko** [comment]
Remove "death" from a list of async messages. This is a wontfix issue for async.
