### ISSUE TITLE
1.20.1: Placeholders for /toggle settings?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2608]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello, is there some PAPI placeholder for various toggle settings, when we want to display it under our settings menu? Like it will show the state "true" "false" when it's parsed? Something like %chatcontrolred_togglechat% etc.

**Comment by kangarko** [comment]
Yes, please look for "is_ignoring_" in https://github.com/kangarko/ChatControl-Red/wiki/Variables
