### ISSUE TITLE
1.20.4: Can I put join/quit on async thread with this setup?

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#2609]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

No

### Question

Hello!

I saw in the CHCR settings file that putting messages on async thread is experimental and may break things. I am curious if I should see any issues if I enable this setting with my join/quit files attached. Thanks!

join file
https://pastebin.com/gn9f97fP

quit file
https://pastebin.com/NJ3YphRH

**Comment by kangarko** [comment]
Got to test it man, I can't give any guarantees. Generally it's not recommended as sync sending is well optimized.
