### ISSUE TITLE
[Issue] Nickname colors

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#261]
When you use a color of hexcode you do not have access too, your nickname shows white. In party chat it shows up with the colors that you have no permission too:

![unknown-16](https://user-images.githubusercontent.com/5664135/101913582-730faa00-3bc3-11eb-9794-46941c27b44b.png)

Minecraft 1.16.4 bungee mysql

**Comment by Sikatsu** [comment]
After I found more information, this is actually related to #266 and I will close this one.

**Comment by kangarko** [comment]
Sorry I cannot reproduce: https://i.imgur.com/6x0iWuL.gif
I've set my nickname containing two colors, one of which I lacked the permission for, and the name was returned to gray as per the format

We can't control party chat so we can't fix that.

**Comment by Sikatsu** [comment]
That's scary, we both replied at the same time. This is actually related to McMMO's party chat. 

Nossr said: 

`You should contact them about it, mcMMO tries to get nicknames via the built-in getDisplayName() (Part of Bukkit) and has done so for 9+ years.`

It's not related to this issue though, since it seemed party chat still used CMI's nickname system. See #266

**Comment by kangarko** [comment]
Haha funny. I will add that call.
