### ISSUE TITLE
Implement UltimateFactions V2 for faction chatmode

### ISSUE THREAD

**Issue by Psykoo92** [kangarko/ChatControl#2611]
### Summary

Hi, it would be nice (and convenient for many people) if you implemented support for the faction chat mode of the Ultimate Faction V2 plugin.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

unfortunately I can't use chatcontrol red Pro on my faction server (and like me, certainly on many others)

**Comment by kangarko** [comment]
Hello,

Sure, unfortunately the plugin is a premium plugin without accessible developer API. If their developers add a API for us to get the players in the same faction as the sender player, then I'll add the party mode.
