### ISSUE TITLE
1.20.4: Is chatcontrolred_is_ignoring_soundnotify still working?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2612]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello, it's written on the wiki, but it doesn't seem to replace placeholder. How it can be even toggled? It's not under toggle command, only using permission, or?

**Comment by kangarko** [comment]
![Screenshot 2024-03-23 at 08 41 52](https://github.com/kangarko/ChatControl-Red/assets/1918426/b6e4fbd9-dfe3-4271-b3b0-197e7c9a6509)
I can't reproduce, works fine. Check you're on the latest chatcontrol. Where are you using it?

**Comment by bobhenl** [comment]
![image](https://github.com/kangarko/ChatControl-Red/assets/18662086/c1c420ab-53c8-4cb1-9a1d-7448af9c7647)
shouldn't I enable it somehow or so?

Don't I miss some files or so?

And yeah I'm on 10.24.6 the last one when posted

**Comment by bobhenl** [comment]
Just ping so you can see it @kangarko

**Comment by kangarko** [comment]
Check that no errors are in the console. Check that sound notify feature is enabled. Check that Renzotom is a real player on the same server.
