### ISSUE TITLE
Minecraft Version: 1.19.4 [08:37:34 INFO]: Error: Too many connections, ( i saw https://github.com/kangarko/ChatControl-Red/issues/2521 )

### ISSUE THREAD

**Issue by AminGHG** [kangarko/ChatControl#2615]
### "/version ChatControlRed" - plugin version

10.24.5

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

The plugin is not starting.

### Information about the issue/bug

I tried everything you guys said to try, im running a network with a global chat and with 4 backend servers. The Database worked yesterday but now it dosent work anymore. After i we fix this i have a other question, if you use global chat, there is a servername option and how can i make it that when you chat on survival (example) that it also shows that you are in survival, becuase normally it dosent show when your on that server.
Please help.
- Amin
-

**Comment by kangarko** [comment]
1. Please share me the "Line" key from mysql.yml.
2. Please confirm you have Hikari set to false in mysql.yml
3. Please send a screenshot of the SQL's command SHOW FULL PROCESSLIST output when that happens.

To answer your other question, I recommend you hardcode the [survival] prefix to your chat format. That way it will show on all servers.

**Comment by AminGHG** [comment]
I cant access the console of the db


```
# -----------------------------------------------------------------------------------------------------
# An alternative file that holds sensitive database information.
#
# **IMPORTANT** We only support utf8mb4_unicode_520_ci collation (database encoding) because we need
# need to store messages in 4 bytes (mb4) due to unicode/emojis/non-English letter support.
# 
# Check if your database has that charset. Check with your hosting provider. Or try removing all
# old ChatControl tables and the plugin will recreate the database with the right encoding.
# Using MySQL 5.7 or 8.0 is recommended, there may be issues with MariaDB due to this encoding.
# -----------------------------------------------------------------------------------------------------

# Use an external database to store logs, mails and user data (channels, nicks, etc.)?
# If false, then we store these date into your data.db file.
Enabled: true

# Enable HikariCP connection pool?
#
# NOTE: If having too many open connections (https://github.com/kangarko/ChatControl-Red/issues/2521)
# Try adding &allowPublicKeyRetrieval=true (or false) at the end of "Line" key, and changing autoReconnect
# from true to false. Test various combinations or eventually set this key to false as last-resort solution.
Hikari: false

# The host and the port to connect to
Host: 

# The database name
Database: 

# The username
User: 

# The password
Password: 

# ADVANCED: The full connector line, do not modify unless you know what you are doing.
# If facing issues try appending &useUnicode=yes&characterEncoding=UTF-8 at the end.
#
# Use 'jdbc:mysql://' if you are running a mysql database.
# Use 'jdbc:mariadb://' if you are running a mariadb database.
Line: jdbc:mysql://{host}/{database}?autoReconnect=false&useSSL=false&allowPublicKeyRetrieval=false
```


I just wanted that there is a little prefix in front of the name like :

S | Owner Amin: wsp

**Comment by AminGHG** [comment]
i tried using this

```
# -----------------------------------------------------------------------------------------------------
# A file that holds bungee-cord related settings. Kept separate from settings.yml so you can symlink
# settings.yml and have unique server name per server configured here. 
# -----------------------------------------------------------------------------------------------------

# Hook to BungeeCord?
#
# [IMPORTANT] Install BungeeControl Red: https://www.mc-market.org/resources/24248 first.
# [IMPORTANT] Please write the 'server-name' key to your server.properties according 
#             to https://mineacademy.org/server-properties
Enabled: true

# The optional prefix before all messages so that you know where they are coming from.
Prefix: '#ffa500&l{bungee_server_name} &8| '

# [IMPORTANT] Set a unique name for this server. 
# If having issues, try removing colors and special characters.
Server_Name: S

# Enable the ability of ChatControl on Spigot to forward console commands?
#
# At this point we are investigating a potential vulnerability so we recommend enabling this only
# for private servers with trusted clients.
Enable_Forward_Command: false
```

**Comment by AminGHG** [comment]
and also there are 2 spaces for some reason

![image](https://github.com/kangarko/ChatControl-Red/assets/164731452/83259217-a760-41cf-abec-130d1f2fc8a4)

**Comment by kangarko** [comment]
Can you clarify what did you mean with "The Database worked yesterday but now it dosent work anymore"? Your configuration seems normal and should not cause the excessive connections issue.

When it comes to the two spaces in your nickname, check your format parts inside that chat format used on the picture. If you are using spaces after the player prefix and inside of it, remove one. Example: "{player_prefix+} {player_name}" should be "{player_prefix+}{player_name}"

**Comment by AminGHG** [comment]
i just wanted 3 things:

that there are just 1 space

that database is working again

that it shows the server infornt of ur name like: S | Owner Amin: wsp

**Comment by kangarko** [comment]
Awesome, I assume that it got solved. Closing. If you have any more questions, comment below.
