### ISSUE TITLE
1.19.4: Permission problem

### ISSUE THREAD

**Issue by gazdyy** [kangarko/ChatControl#2616]
### "/version ChatControlRed" - plugin version

10.19.4

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Prečo je teraz 1 permission pre bypass chat delay aj command delay? Predtým mal každý delay svoju permissiu. Bolo to dobré pretože sa to dalo lepšie rozdeliť medzi VIP groups

**Comment by kangarko** [comment]
Ahoj, netuším. Ale rozdelil som ti to naspäť tak ako to bolo predtým.

**Comment by gazdyy** [comment]
ďakujem pekne
