### ISSUE TITLE
1.20.4: Executing command on multiple commands repeated?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2618]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello, is it possible to execute some command (like in rules then command) when player repeats one command like XX times? For example if they'll do:
/home
/home
/home
3 times in a row, I'd like to execute some command

it's just a protection for me cause I saw that sometimes there are some dangerous commands that lead to dupe or so and I'd like to be notified in these situations

**Comment by kangarko** [comment]
Hey! Yes but with custom coding required. I recommend you get someone to write a plugin for that as it will work better.
