### ISSUE TITLE
1.19.4: GlobalChat prefix

### ISSUE THREAD

**Issue by AminGHG** [kangarko/ChatControl#2619]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

How can i make a globalchat where there is the server name infornt of ur message like: S (survival) | Owner Amin: wsp (ik how to do that but i dont see the letter in the server your in)

**Comment by kangarko** [comment]
Hey,

It's quite simple, you just edit the formats/chat.yml to add the (survival) prefix manually. Then enable bungeecord mode and delete bungee prefix. Then the prefix will show on all servers.
