### ISSUE TITLE
How to allow some players to see swearings

### ISSUE THREAD

**Issue by TheIronMinerLv** [kangarko/ChatControl#262]
Hi!

I would like to create a command that would "toggle" full visibility of blocked swearings. Like if you swear, for you the message shows as normal (nothing changed, not even a "warning"), but for other players - that hasn't used the command, for them the swear words will be "censored", but for the ones who will have used it - they will see the message without censoring.

How could I do that? Thanks.

**Comment by kangarko** [comment]
Hey,

in the pro version, there is a feature named Chat Ignorers (more info [here](https://github.com/kangarko/ChatControl-Pro/wiki/Chat-Ignorers)). Unfortunately this is not available in the free version.

**Comment by TheIronMinerLv** [comment]
I have that pro version and that is not what I want.

**Comment by kangarko** [comment]
Then please post at the Issues Channels for the pro version.
