### ISSUE TITLE
[Question] Discord Formatting & Webhooks

### ISSUE THREAD

**Issue by rumplepusscat** [kangarko/ChatControl#262]
Minecraft Version: 1.16.3
MySQL: true
BungeeCord: true

============================

Hi there,

Is there any way to still make use of DiscordSRV's 'experimental' webhook delivery with ChatControl Red? (i.e. It shows up as the player's head when sending a message?) I've been using this for years now alongside ChatControl (pre CHC-Red however), and it would be a shame to have to lose this useful feature completely.

Additionally, I'm presuming there is no way to bypass ChatControl Red deleting/re-sending messages sent via Discord? I'm sure this is something I will have to become used to, but right now I'm finding it frustrating not being able to have messages sent via Discord stay 'true' to Discord (i.e. you can still see Discord nicknames, role colours, be able to click on a user & PM etc.).

As I said, this will probably unfortunately have to be something I get used to (this is still by far the best chat plugin out there!!), but if there is something that can be done to work around this, I would be incredibly grateful.

Many thanks,

Rumple

**Comment by kangarko** [comment]
Thanks for your feedback. I totally understand, so I will add the new Send_Messages_As_Bot option into the Integration section in the next release. Keep in mind however, that disabling this, will also break rules and [X] features on discord. More explanations in the comments above that key.

**Comment by rumplepusscat** [comment]
That's amazing - thank you very much! I understand this will break some features, so will find workarounds or cut my losses! 👍 

Thank you so much for taking on feedback - I've known many a dev to not do this in the slightest!!

Best wishes,

Rumple

**Comment by kangarko** [comment]
Thanks so much! I will push an update tonight/tmr. If you appreciated this, you can drop a quick review on our brand new MCM page: https://www.mc-market.org/resources/18217/
