### ISSUE TITLE
1.19.4: Message Bug

### ISSUE THREAD

**Issue by gazdyy** [kangarko/ChatControl#2621]
### "/version ChatControlRed" - plugin version

10.25.0

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

![image](https://github.com/kangarko/ChatControl-Red/assets/60019769/b787f340-c70f-4678-8dc7-8d80c32dec33)

### Information about the issue/bug

Prečo sa mi zobrazuje 2x (!)? v messages_en mám jasne napisané
Enable: '&8&l(!) &7Nyní ignoruješ hráče &f{1}&7.
prefix pluginu tiež nie je (!)

**Comment by gazdyy** [comment]
taktiež sa plugin prefix z settings.yml zobrazuje v niektorých správach v messages_en bez toho aby som používal {plugin_prefix}, čiže v podstate není možnosť ho odstrániť zo správ ak ho nechcem používať

**Comment by kangarko** [comment]
Ahoj, vidim ze si zavrel otazku tak ju povazujem za vyriesenu.
