### ISSUE TITLE
Add Official Velocity Support

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2624]
## Summary

As stated in the repo for [VelocityControl](https://github.com/kangarko/VelocityControl): 
``VelocityControl is maintained by a third-party developer in his spare time. I, Matej, actively develop ChatControl Red and BungeeControl Red only.``

In other words, there is no "official support" as of yet, as quoted ``maintained by a third-party developer``

## What would happen if we didn't implement this feature? Why not having this feature is a problem?

As of 27th of March, 2024 waterfall (a fork of BungeeCord) reached its end of life and therefore no longer be updated. Making it more likely for people to switch to Velocity, instead of using a slower proxy software.

ChatControl is great in terms of what it can do etc. However, this fact alone would not be enough to make people want to switch back to slower proxy software (BungeeCord) compared to Velocity.

To support this you can view a [survey](https://www.spigotmc.org/threads/what-is-the-best-proxy.444261/)(Posted on Spigot Forums @ Jun 9, 2020) 
| **Proxy Software**  | **Total Votes** |
| ------------- | ------------- |
| BungeeCord | 11.9% |
| Waterfall | 23.8% |
| Travertine | 1.9% |
| Aegis | 5.8% |
| Flamecord | 12.6% |
| Velocity | 39.1% |
| Other | 4.8% |

Even if we acknowledge that this survey still shows that people are mostly using BungeeCord. It should be noted that 44.1% of these users are using a BungeeCord fork, of which most used waterfall directly or were using a fork of waterfall. Suggesting that people are seeking to use the software on their proxy servers that use less resources but also run faster, as Velocity outperforms BungeeCord, as another 39.1% already use velocity it would be wise to learn about the Velocity software so that we can get official support.

Otherwise, you risk losing out on a group of potential customers, not due to issues with the plugin but compatibility issues which could easily be resolved.

**Comment by kangarko** [comment]
I'm learning this new skillset but my time is limited. I'm planning on teaching Velocity in the next iteration of my courses so by that time I should have the enough capability to write an official velocity plugin.

**Comment by kangarko** [comment]
Thanks !
