### ISSUE TITLE
1.20.1: I can't use Image_head: Herobrine (in motd.yml from fomat folder)

### ISSUE THREAD

**Issue by PrinceNotAvailable** [kangarko/ChatControl#2625]
### "/version ChatControlRed" - plugin version

10.25.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/7f16edcb5be84027a1bdc8f84f25e049

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14838622/debug.zip)

### Information about the issue/bug

i was trying to set my motd for my server but when i tried to use the Image_Head: "Herobrine" its not working error came . i tried fixing it myself but i was not able to .. else everything is fine but herobrine head is not loading :( .

**Comment by kangarko** [comment]
You sure you put the image head like this ?

![a](https://i.imgur.com/dWf48zu.png)

**Comment by PrinceNotAvailable** [comment]
![Screenshot 2024-04-02 215728](https://github.com/kangarko/ChatControl-Red/assets/96819509/19253b8f-4088-4da9-9f0a-49edddb91e3a)

i mean in the chat.yml file syntax is - Image_Head: "Herobrine" 
you can see this in the small screenshot i provided . 

if its not gonna work its ok i have a feeling that there's something wrong with my main server because everything worked fine in my local server ... its fine .. 

also i don't think  Image_Head: "{player}" gonna work for cracked servers.

**Comment by kangarko** [comment]
Looks like minotar which we used is down. I have switched to https://mc-heads.net/. In the next version, you will be able to specify your own API endpoint to fetch player head skins under the Image_Head_Endpoint key in settings.yml
