### ISSUE TITLE
1.20.1: Velocity Join/Leave/Switch Messages Nonexistent

### ISSUE THREAD

**Issue by OyotOnyenwe** [kangarko/ChatControl#2626]
### "/version ChatControlRed" - plugin version

10.24.6

### Are you using MySQL?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14845706/debug.zip)

VelocityControl Config:
[velocitycontrol.zip](https://github.com/kangarko/ChatControl-Red/files/14845834/velocitycontrol.zip)

### Information about the issue/bug

I've been trying to get VelocityControl to work since I switched to Velocity. I purchased ChatControl Red specifically to have access to VelocityControl. I previously used BungeeControl with ChatControl Free and had the desired behavior. I simply want a message that says "X joined the server" "X joined from otherServer" or "X left the server". I have configured the .rs files for velocitycontrol, but simply nothing appears when any player joins or quits the server. At one point I had only quit messages appearing, then those disappeared too. I don't know what changed to cause that.

**Comment by kangarko** [comment]
@james090500 mind having a look asap please?

**Comment by Timoti11** [comment]
@kangarko This problem is also on BungeeControlRed - I used it for a year in conjunction with ChatControlRed - I had to put separately plugins like `BungeeJoinMessages` or `vmessage`.
Here is my thread on this issue: https://github.com/kangarko/ChatControl-Red/issues/2403

**Comment by james090500** [comment]
Are they completely non existent or just temperamental?

**Comment by Timoti11** [comment]
> Are they completely non existent or just temperamental?

It's not working. Sometimes after restart `quit`-message can work, but no other, and later it's finaly no message alerts

**Comment by kangarko** [comment]
Gotcha. I'll look into the protocol but looks like the packets are not being properly sent sometimes which is hard to debug. Will have a deeper look when I have time. @james090500 appreciated it you could had the time to debug chatcontrol too perhaps I made an error there and proxy is ok

**Comment by james090500** [comment]
> Gotcha. I'll look into the protocol but looks like the packets are not being properly sent sometimes which is hard to debug. Will have a deeper look when I have time. @james090500 appreciated it you could had the time to debug chatcontrol too perhaps I made an error there and proxy is ok

I wonder if it's caused by this @kangarko. I can't build and test right now but it lines up with the issues...

https://github.com/kangarko/ChatControl-Red-Src/commit/6c96e6b89abccd156359f4a787f50b2f9fcaee83#diff-17e33337e2804023492b18b97abcaa759560317f90e3cee53be40c2676c07904

**Comment by kangarko** [comment]
Which section of the commit? The synchronized lock?

**Comment by james090500** [comment]
> Which section of the commit? The synchronized lock? 

In player listener. It's sending the packet as player, if the connection isn't fully established it may fail

**Comment by kangarko** [comment]
> > Which section of the commit? The synchronized lock?
> 
> In player listener. It's sending the packet as player, if the connection isn't fully established it may fail

Even before that commit we would still use the first available random player on the server since thats how bungee works if I am not mistaken.

@Timoti11 can you please try these two dev builds? you'd need to replace both chatcontrol and bungeecontrol using these builds: 

[Archive.zip](https://github.com/kangarko/ChatControl-Red/files/14936130/Archive.zip)

**Comment by james090500** [comment]
Bungee/Velocity should be smart enough to use a player that's fully connected. 

I'll try the dev build also and work on some more debugging my side

**Comment by kangarko** [comment]
Thanks. I removed synchronized/volatile blocks in the dev build. No other changes.

**Comment by kangarko** [comment]
@OyotOnyenwe can you please try the devbuild from above comment in case you're still having this issue?

**Comment by OyotOnyenwe** [comment]
I can't, because my issue was on VelocityControl and not BungeeControl. (I don't have a bungee proxy, only velocity)

**Comment by kangarko** [comment]
@james090500 can you please adjust velocitycontrol to the changes from bungee? Remove the synchronize blocks and replace volatile with final whereever possible

**Comment by kangarko** [comment]
@OyotOnyenwe can you try this alpha build of my version of velocity along with the next release of chatcontrol please? Thanks.

[VelocityControl-1.0.0.zip](https://github.com/kangarko/ChatControl-Red/files/15013892/VelocityControl-1.0.0.zip)

@james090500  see discord

Closing as I am taking over Velocity development now and believe this got fixed. Comment below if any issues.

**Comment by OyotOnyenwe** [comment]
Unfortunately the issue is still occurring. I have updated ChatControl to 10.25.6 on all my servers and installed the velocitycontrol build on the proxy. I double checked the bungee.yml for all of them, and updated the config for the new velocitycontrol plugin. Still absolutely nothing in the way of join, switch, or leave messages.

**Comment by kangarko** [comment]
1. Just to confirm you used the ZIP file of velocity from above?
2. Please use the v10.25.7 of ChatControl Red.
3. If that problem still continues then set your Debug key in settings.yml of VelocityControl to [player-message] and post me the console log when join message should happen but it does not. Check it's enabled in settings.yml under Messages.Apply_On

**Comment by OyotOnyenwe** [comment]
1. Yes, I'm using the new VelocityControl-1.0.0.jar and removed the old one.
2. Updated to 10.25.7 ChatControl Red.
3. Unfortunately the problem is still occurring. Attached is the console output.
![image](https://github.com/kangarko/ChatControl-Red/assets/71685036/162dd58b-c759-4174-9048-75c6795d10e0)
Also, here is the Apply_On in velocitycontrol settings.yml:
![image](https://github.com/kangarko/ChatControl-Red/assets/71685036/288b6f59-fef5-43bb-a8a7-4b3c1244f593)

**Comment by kangarko** [comment]
Is chatcontrol installed on all spigot/paper servers with bungeecord enabled?

**Comment by OyotOnyenwe** [comment]
Yes, ChatControl is on all the servers and Bungee is enabled in the ChatControl config for each one. They all have the correct server-name field from server.properties, velocity config, VelocityControl config, and ChatControl config.

**Comment by kangarko** [comment]
Oh I apology, I missed that you said you had mysql off. You need to enable mysql in the mysql.yml file for network sync to work properly.

**Comment by OyotOnyenwe** [comment]
I don't want to use any of the other features like chatting across networks. I only wanted to have the join/leave/switch messages from VelocityControl and use ChatControl for moderation on each individual server. Is MySQL necessary for just that one feature?

**Comment by kangarko** [comment]
Should be fixed on my velocity build, closing. Let me know if you got any questions below.

**Comment by kangarko** [comment]
I am sorry but mysql is indeed required for fundamental data sync and its technically linked to sending other player data too required for player messages such as their statuses or variables.
