### ISSUE TITLE
1.20.4: Can we show that player doesn't have perm for specific color?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2628]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello, if the player wants to use colors in chat like &cMESSAGE, can we send him a message that he doesn't have permission for it somehow? Maybe using rules? But wouldn't it be so difficult for the server performance?

**Comment by kangarko** [comment]
Sorry we don't have these conditions natively, but perhaps you can create a rule in rules/chat.rs that will match all messages and send a message if player does not have the perm

```
match .*
ignore perm i.must.not.have.this.perm
then warn You don't have the permission!
```

**Comment by bobhenl** [comment]
but wait, this matches all messages, how I distinguish if they use & character there?

**Comment by kangarko** [comment]
Oh sorry, that's correct. Can't you use this?

`match (.*)\&c(.*)`
