### ISSUE TITLE
use placeholder in soundnotify setting

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#2629]
### Summary

hi
make it possible to use placeholders in this places:

Sound_Notify:
  Color: '&%color_code%'

or

Groups:
  test:
    Sound_Notify_Color: '%color_code%'

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

have alot of groups for only tag colors, this make it have one group for all of them

**Comment by kangarko** [comment]
Sorry this is unsupported due to technical reasons for now.
