### ISSUE TITLE
Chat.txt edit 

### ISSUE THREAD

**Issue by ItzJustAverage** [kangarko/ChatControl#263]
When ever i try to edit the "chat.txt" file i get an error 

https://pastebin.com/NxgQhntW

**Comment by malonnnn** [comment]
Could you please post your chat.txt file?

**Comment by ItzJustAverage** [comment]
it happens even when I change one letter so it won't help. ill give it anyway

https://pastebin.com/TvQKjPFL

**Comment by malonnnn** [comment]
Is the chat.txt you posted the broken one, or the working one?

**Comment by ItzJustAverage** [comment]
Broken one

**Comment by ItzJustAverage** [comment]
the only one that works is the default one

**Comment by kangarko** [comment]
> Cannot define an operator when no rule is being created (previous operator is null)

This error is always indicating that the file could not be read due to wrong encoding. Please read the bottom of https://github.com/kangarko/ChatControl/wiki
