### ISSUE TITLE
1.20.4 : Latest update issue

### ISSUE THREAD

**Issue by v4rl1** [kangarko/ChatControl#2632]
### "/version ChatControlRed" - plugin version

10.25.2

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/1d8ddd05286f416ab919c2d05c92fd07

### "/chc debug" output (strongly recommended)

https://ufile.io/p9jlhf4a

### Information about the issue/bug

Issue seems to happen at random occurrences since the latest update. I couldn't reproduce to see what triggers it.

**Comment by kangarko** [comment]
Please retest on v10.25.3 and let me know if that happens still.

**Comment by v4rl1** [comment]
It still does it : https://paste.gg/p/anonymous/5ed54df888da4b96a514e63888e3664b

**Comment by kangarko** [comment]
Thanks, will be fixed in the next version.
