### ISSUE TITLE
1.20.4/1.8.8: PlaceholderAPI placeholders are completely ignored when messages are sent from console

### ISSUE THREAD

**Issue by 10Meisterbaelle** [kangarko/ChatControl#2633]
### "/version ChatControlRed" - plugin version

10.25.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

When console sends a message to a channel (using channel send), PlaceholderAPI placeholders are ignored entirely.
![Demonstration Image](https://github.com/kangarko/ChatControl-Red/assets/45918080/d9d06d64-684f-40a7-88b9-1f1bbcad32f1)
Expected behaviour: It should return as empty.

**Comment by kangarko** [comment]
Unsupported, please use a separate console format instead: https://github.com/kangarko/ChatControl-Red/wiki/Channels#format_console

**Comment by 10Meisterbaelle** [comment]
@kangarko 
> Unsupported, please use a separate console format instead: https://github.com/kangarko/ChatControl-Red/wiki/Channels#format_console

Doesn't this only change how it looks inside the console? I wanna change how the console looks to other players when it sends a message.

**Comment by kangarko** [comment]
Oh I see. Then you would need to write the following condition to your format file into individual parts:

`Sender_Condition: '{sender_is_console}'`

Keep it as is if you only want a format part to show IF the sender is console. Otherwise if you want to hide it from console use:

`Sender_Condition: '!{sender_is_console}'`

**Comment by kangarko** [comment]
You can read up on variables you can use here: https://github.com/kangarko/ChatControl-Red/wiki/Variables
