### ISSUE TITLE
1.20.4: Tablist feature does not update prefix or suffix until you rejoin.

### ISSUE THREAD

**Issue by Denial234** [kangarko/ChatControl#2635]
### "/version ChatControlRed" - plugin version

10.25.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

https://ufile.io/r1s2l64p

### Information about the issue/bug

Tablist feature does not update when you change prefix & suffix until you rejoin. I feel like this has nothing to do with the permissions plugin i'm using because the tablist works fine when i'm not using chat control red to manage my tablist. It works totally fine when i use TAB and updates as soon as i change group and give myself a new suffix using supremetags. Although as soon as i switch plugin to Chatcontrol RED to handle my tablist i have to rejoin every time i want the tablist to update the changes i've made.
Every other plugin works except for this plugin when it comes to the tablist.
It doesn't matter what placeholder i use, nothing updates until you rejoin. Except for the username when i change nick using /chc tag

**Comment by kangarko** [comment]
Thanks, I made the code update tablist on all tag changes, not just nick tags. The next update should do the trick :)

**Comment by Denial234** [comment]
The tablist update unfortunately did not change anything. The problem still exists.

**Comment by kangarko** [comment]
I am sorry. Please use the next version from tonight, in settings.yml > Debug set the key to [tab-list] and see the console messages each time the tablist should get updated to check what is happening and what the tablist is set to. Report back to me please.

![a](https://i.imgur.com/fM5dDvK.png)

**Comment by Denial234** [comment]
17.04 15:48:46 [Multicraft] Graned ran command Message of the Day
17.04 15:48:47 [Server] INFO Graned
17.04 15:48:52 [Server] INFO Graned issued server command: /uperms
17.04 15:48:52 [Server] INFO Note: Not sending Graned's command to spying players because he had 'chatcontrol.bypass.spy.command' permission. Player messages with such permission are not spied on. To disable that, negate this permission (a false value if using LuckPerms). This message only shows once per 3 hours.
17.04 15:49:01 [Server] INFO Graned issued server command: /tags
17.04 15:49:16 [Server] INFO Listing Online Player(s)                        
17.04 15:49:16 [Server] INFO 1. MEMBER Graned
17.04 15:49:28 [Disconnect] User Graned has disconnected, reason: Disconnected
17.04 15:49:28 [Server] INFO Removing sell holding instance for user: Graned
17.04 15:49:29 [Server] INFO Graned
17.04 15:49:31 [Server] INFO UUID of player Graned is 6f63b55e-97c4-4dd6-8fb1-057c65c148f6
17.04 15:49:31 [Server] INFO Updating profile player reference for: Graned
17.04 15:49:31 [Server] INFO Updating tab list name of Graned to MEMBER Graned Elite
17.04 15:49:31 [Server] INFO TIP: Joining player to his saved channel standard in mode write
17.04 15:49:31 [Server] INFO TIP Alert: Supposed to add Graned to channel 'admin' which is not installed on this server, skipping
17.04 15:49:31 [Server] INFO TIP: Player Graned is already in channel 'standard' in mode read, not adding.



Plugins: UltraPermissions (SpigotMC) & SupremeTags (SpigotMC)

Tab_List:

  # Change the tablist for players?
  Enabled: true
  
  # The format of the tab list
  Format: '%uperms_prefix%&r {player_nick}%supremetags_tag%'

**Comment by Denial234** [comment]
I was STAFF when i joined, i used /uperms and changed prefix to MEMBER and then rejoined.

**Comment by Denial234** [comment]
I also changed tags using /tags from Ice to Elite

**Comment by Denial234** [comment]
17.04 15:48:45 [Server] INFO UUID of player Graned is 6f63b55e-97c4-4dd6-8fb1-057c65c148f6
17.04 15:48:46 [Server] INFO Updating profile player reference for: Graned
17.04 15:48:46 [Server] INFO Updating tab list name of Graned to STAFF Graned ʜᴇʀᴏ
17.04 15:48:46 [Server] INFO TIP: Joining player to his saved channel standard in mode write
17.04 15:48:46 [Server] INFO TIP Alert: Supposed to add Graned to channel 'admin' which is not installed on this server, skipping
17.04 15:48:46 [Server] INFO TIP: Player Graned is already in channel 'standard' in mode read, not adding.
17.04 15:48:46 [Server] INFO TIP: Automatically enabling spy mode for Graned because they had 'chatcontrol.spy.autoenable' permission. To stop automatically enabling spy mode for players, give them negative 'chatcontrol.spy.autoenable' permission (a value of false when using LuckPerms). This message only shows once per 3 hours.
17.04 15:48:46 [Connect] User Graned, IP 
17.04 15:48:46 [Multicraft] Graned ran command Message of the Day
17.04 15:48:47 [Server] INFO Graned
17.04 15:48:52 [Server] INFO Graned issued server command: /uperms
17.04 15:48:52 [Server] INFO Note: Not sending Graned's command to spying players because he had 'chatcontrol.bypass.spy.command' permission. Player messages with such permission are not spied on. To disable that, negate this permission (a false value if using LuckPerms). This message only shows once per 3 hours.
17.04 15:49:01 [Server] INFO Graned issued server command: /tags
17.04 15:49:16 [Server] INFO Listing Online Player(s)                        
17.04 15:49:16 [Server] INFO 1. MEMBER Graned
17.04 15:49:28 [Disconnect] User Graned has disconnected, reason: Disconnected
17.04 15:49:28 [Server] INFO Removing sell holding instance for user: Graned
17.04 15:49:29 [Server] INFO Graned
17.04 15:49:31 [Server] INFO UUID of player Graned is 6f63b55e-97c4-4dd6-8fb1-057c65c148f6
17.04 15:49:31 [Server] INFO Updating profile player reference for: Graned
17.04 15:49:31 [Server] INFO Updating tab list name of Graned to MEMBER Graned Elite
17.04 15:49:31 [Server] INFO TIP: Joining player to his saved channel standard in mode write
17.04 15:49:31 [Server] INFO TIP Alert: Supposed to add Graned to channel 'admin' which is not installed on this server, skipping
17.04 15:49:31 [Server] INFO TIP: Player Graned is already in channel 'standard' in mode read, not adding.


  # The format of the tab list
  Format: '%uperms_prefix%&r {player_nick}%supremetags_tag%'

**Comment by Denial234** [comment]
I used /uperms to change my prefix from STAFF to MEMBER
And used /tags to change tag from HERO to Elite

It updates as soon as i disconnect and join back.

**Comment by kangarko** [comment]
When you use /uperms we do not get the notification that the tag got updated. ChatControl can only update tags when it receives an event of that such as when you run the /tag command.

**Comment by Denial234** [comment]
Why is it that when i use TAB it works fine? I'm not a developer so i don't really know this type of stuff. But is it not possible to automatically update the tablist when a placeholder gets changed? Those placeholders are from PlaceholderAPI

**Comment by Denial234** [comment]
All and all i just want to be able to have a colored name in the tablist. This is why i wanted to use chatcontrol red to manage the tablist. Is is possible to maybe add a placeholder for chatcontrol red that you can put in TAB that gets the nick format for the name and display it in the tablist? Just like how you can get a prefix color from a placeholder.

**Comment by Denial234** [comment]
Something like %chatcontrol_nick% that i can use in TAB so that the chatcontrol nick is displayed in the TAB plugin's tablist? And when i have the nick disabled it just displays the name as normal.

**Comment by Denial234** [comment]
All and all i just want to be able to have a colored name in the tablist using chatcontrol red's nickname function. This is why i wanted to use chatcontrol red to manage the tablist. Is is possible to maybe add a placeholder for chatcontrol red that you can put in TAB that gets the nick format for the name and display it in the tablist? Just like how you can get a prefix color from a placeholder.

Something like %chatcontrol_nick% that i can use in TAB so that the chatcontrol nick is displayed in the TAB plugin's tablist? And when i have the nick disabled it just displays the name as normal.

**Comment by kangarko** [comment]
We already have that, doesnt it work already? {chatcontrol_nick} or {player_nick} I believe

**Comment by Denial234** [comment]
But that doesn't work if i put it into TAB's config. That's a placeholder that is specifically made for ChatControl RED settings.yml
Is there a PlaceholderAPI placeholder for ChatControl RED that lets me get the nick from ChatControl RED and use it in TAB's config so that i can use TAB's tablist that seems to work as i want it to when i change my placeholders so that i can get the nickname from ChatControl RED and use it in TAB?

**Comment by Denial234** [comment]
But that doesn't work if i put it into TAB's config. That's a placeholder that is specifically made for ChatControl RED settings.yml
Is there a PlaceholderAPI placeholder for ChatControl RED that lets me get the nick from ChatControl RED and use it in TAB's config so that i can use TAB's tablist that seems to work as i want it to when i change my placeholders so that i can get the nickname from ChatControl RED and use it in TAB?

**Comment by Denial234** [comment]
%uperms_prefix% & %supremetags_tag% are both placeholders that works using PlaceholderAPI this is why i can use them in that TAB plugin. It would be amazing if there was a placeholder for ChatControl RED that allowed me to use the nick from ChatControl RED in the TAB plugin as well.

**Comment by kangarko** [comment]
The %chatcontrolred_nick% variable we have goes right into PlaceholderAPI so if TAB suppors PAPI, you could use that. However the tab is only refreshed when you run /tag command from ChatControl as I explained above.

**Comment by Denial234** [comment]
That solved the issue! Thank you.

**Comment by Denial234** [comment]
Sorry for the hassle.. 

Is there a wiki of all the possible placeholders that ChatControl RED has?

**Comment by kangarko** [comment]
Yes of course, please see https://github.com/kangarko/ChatControl-Red/wiki/Variables

**Comment by Denial234** [comment]
Thank you so much!

**Comment by kangarko** [comment]
You're welcome!
