### ISSUE TITLE
1.20.4 : priority issue

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#2637]
### "/version ChatControlRed" - plugin version

10.24.6

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14898362/debug.zip)

### Information about the issue/bug

Since some months (at least 2 months) the priority system is getting issue.

Before I was using `Chat_Listener_Priority: LOWEST` without issue, didn't update any plugin except chatcontrolred, and now I'm getting tons of issues with every plugin that use chat :
- playerwarps
- superiorskyblock
- interactivechat
- displayshops

Before I had litterally no issue. I tried changing to each possible value (from lowest to monitor) none of them work properly without creating issue.

**The issue seems to occur since I updated from 1.19 to 1.20 (same on 1.20.1 server)**, because I had to update chatcontrol when I updated my server version, and after this, the issue happened

**Comment by WarnDa** [comment]
Every plugin that need to CANCEL a chat event can't. (tested ALL priority)
Each time the message is still send. This didn't happen before on 1.19

**Comment by kangarko** [comment]
Can you try switching value of Channels.Alternative_Console_Sending in settings.yml?

**Comment by WarnDa** [comment]
> Can you try switching value of Channels.Alternative_Console_Sending in settings.yml?

It's the same behavior, but some plugin messages are canceled but they shouldn't (like superior ones), tried on all priority

**Comment by kangarko** [comment]
Can you please give me step-by-step instructions on how to reproduce using one of the above (free) plugins? I assume you're on stock Paper not Purpur etc.

**Comment by kangarko** [comment]
I see you're on UniverseSpigot. Can you please try using Paper - just to be 100% sure that the fork is not the one causing this? I don't have the time capacity to test on all forks, thanks for your understanding.

**Comment by WarnDa** [comment]
I could reproduce the issue and find more informations !
It's something from the config, as with default chatcontrol I don't get any issue, but with the config on the /chc debug I got issue
- The debug : [debug.zip](https://github.com/kangarko/ChatControl-Red/files/14950296/debug.zip)


For this test I had to use a premium plugin (easier for me) add me on discord : **warnd** I'll give it to you
Plugin used : https://www.spigotmc.org/resources/%E2%AD%90-player-warps-%E2%AD%90-%E2%9E%A2-let-your-players-set-warps-1-7-1-20-4.115286/
Dependency : https://www.spigotmc.org/resources/vault.34315/
- Use paper/Chatcontrol
- Use my config of chatcontrol
- Create a pwarp `/pwarp set test`
- Open the `/pwarp` and click on a sponsor slot
![image](https://github.com/kangarko/ChatControl-Red/assets/31826333/894ae96f-bc83-4c8a-bc62-98abbe5a6bb9)
- Type `test` in chat
![image](https://github.com/kangarko/ChatControl-Red/assets/31826333/36426062-5b70-4564-b7c9-ebfc2516f7c8)
The message should be deleted but it's not.

- With default config of chatcontrol it works : 
![image](https://github.com/kangarko/ChatControl-Red/assets/31826333/c75b923c-7863-498e-a299-419b48eadf8a)
- To remove a pwarp and test again `/pwarp remove test`
- Tested `Alternative_Console_Sending: true` also, and all priority

Edit : If I set "channel" to `Enabled: false` the issue is fixed, so it comes from channels (a bit logical lol)

**Comment by kangarko** [comment]
The message always shows up for me. Even when chatcontrol is uninstalled:

![Screenshot 2024-04-12 at 13 42 40](https://github.com/kangarko/ChatControl-Red/assets/1918426/b094a0b6-6139-4fb6-827c-4bd8f3585d3b)

Sorry I believe either these plugins are not canceling chat event properly or there is some other bug out of chatcontrol's scope. In us, simply by changing the priority to HIGHEST or MONITOR majority of issues are fixed.

Or, 1.20 changed something in the event pipeline - had I been you I would ask that in paper discord just to be sure. Praying they didnt since that would be unfixable on our end.

**Comment by kangarko** [comment]
Feel free to continue talking below

**Comment by WarnDa** [comment]
> The message always shows up for me. Even when chatcontrol is uninstalled:
> 
> ![Screenshot 2024-04-12 at 13 42 40](https://private-user-images.githubusercontent.com/1918426/321969937-b094a0b6-6139-4fb6-827c-4bd8f3585d3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjI2MDAsIm5iZiI6MTcxMjkyMjMwMCwicGF0aCI6Ii8xOTE4NDI2LzMyMTk2OTkzNy1iMDk0YTBiNi02MTM5LTRmYjYtODI3Yy00YmQ4ZjM1ODVkM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMTE0NTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTEzNDc2MDZkYWNkMGM2MGIyNzI0YWY3NjBiNjEyMDk0OTFiMzY5MTZmMDUwYTczMTdmMjBhN2JhMDFlNDNlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.U1F2kjFWZB8bTmWXOX1QLUc4Vvg3w1cSv-DXkMEIgeY)
> 
> Sorry I believe either these plugins are not canceling chat event properly or there is some other bug out of chatcontrol's scope. In us, simply by changing the priority to HIGHEST or MONITOR majority of issues are fixed.
> 
> Or, 1.20 changed something in the event pipeline - had I been you I would ask that in paper discord just to be sure. Praying they didnt since that would be unfixable on our end.

Because you tested the free version, that has issue, on the premium version I was able to correctly reproduce the issue.

Here is with HIGHEST priority : 
![image](https://github.com/kangarko/ChatControl-Red/assets/31826333/4615f9a3-6f5a-4e01-b317-8649013ff8b0)
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14958320/debug.zip)


And MONITOR : 
![image](https://github.com/kangarko/ChatControl-Red/assets/31826333/c18b9cd8-662e-4472-b660-af6fe6d3798e)
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14958337/debug.zip)

And if I remove chatcontrol channels, no issue.

**Comment by kangarko** [comment]
I am not able to test with premium plugins. Is any one of those four above available as a free one?

**Comment by kangarko** [comment]
Or contact me privately at matej@mineacademy.org and we can move forward with this faster.
