### ISSUE TITLE
Modification to Wiki page

### ISSUE THREAD

**Issue by BlueFyreMatt** [kangarko/ChatControl#2638]
### Summary

In the past 6 months, a variable was changed so servers that run Velocity should be entering "then bungeeconsole velocity" instead of "then bungeeconsole bungee" if they want a rule to execute on the proxy, the change wasn't reflected in the change logs as a breaking change so this is a simple suggestion to update the wiki to reflect that change here:

https://github.com/kangarko/ChatControl-Red/wiki/Rules#then-bungeeconsole-server-command1command2

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

.

**Comment by kangarko** [comment]
Thank you. Great notice, added!
