### ISSUE TITLE
1.20.4: chat event [item] loses its format after update

### ISSUE THREAD

**Issue by smscentras** [kangarko/ChatControl#2639]
### "/version ChatControlRed" - plugin version

10.25.3

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/09e9105d2cd841a99425ee66ac68c7be

### "/chc debug" output (strongly recommended)

omg

### Information about the issue/bug

[item] not working

**Comment by kangarko** [comment]
Thanks, will be fixed in the next version.
