### ISSUE TITLE
1.16.4 | rules on sign, only replace first line. 

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#264]
I try out rules on sign and it only replace first line (was other issues in older versions i miss report).

But this is new bug. It seams like it run hole xxx in first line (sry for bad worlds i use).

![2020-12-11_22 54 03](https://user-images.githubusercontent.com/16368286/101958527-ce618c80-3c03-11eb-8d14-873c0b90aa30.png)

https://pastebin.com/hEzidRRH

**Comment by Qw4rtz** [comment]
I want to add that if you write only one word per line it also replace the first line only, with multiple censored words (**** **** **** ****)

**Comment by kangarko** [comment]
Thanks, fixed.
