### ISSUE TITLE
packets.txt can't change command messages?

### ISSUE THREAD

**Issue by TheCrazyBoi** [kangarko/ChatControl#264]
I am customizing messages sent by a plugin and when I try to modify a message which starts with a **/**, I am not able to modify it. 

Example: I am trying to change a command sent from the Factions plugin (MassiveCore) and I can modify everything exempt the messages that starts with a **/**. This is what I try in the packets.txt:
packets.txt - With regex
`match \/f sethome\,sethome \[faction\=you\]`
`then rewrite &c/f sethome`

packets.txt - Without regex
`match /sethome,sethome [faction=you]`
`then rewrite &c/f sethome`

Any solutions for this?

**Comment by kangarko** [comment]
Why are you having the "," and sethome twice? The rules accept the command explicitly as it is:

match ^/sethome \[faction\=you\]

should work.

**Comment by TheCrazyBoi** [comment]
No, this doesn't work...

What I want to do is hiding this message from appearing in the chat:
`/f sethome,sethome [faction=you]` This is the exact message sent from the Factions plugin (MassiveCore).

I am using the following regex to remove the message from chat:
`match ^/f sethome`
`then deny`

And this does NOT work... The message still appears in the chat.

**Comment by ItzSomebody** [comment]
^/f sethome*

**Comment by ItzSomebody** [comment]
Do you have protocollib installed?

**Comment by TheCrazyBoi** [comment]
Yes, ProtocolLib is installed.

**Comment by TheCrazyBoi** [comment]
As it seems to me, I am not able to modify any messages that starts with a **Slash (/)** due to client-side chat or something... 

Am I correct or is there other ways to modify messages that starts with a slash?

**Comment by kangarko** [comment]
I see, from my understanding, this is handled in such way that ChatControl doesn't see the message. I personally never tested catching literal chat messages starting with a slash. Unfortunately, if this won't work for any of them, my hands are tied because I rely on ProtocolLib for this.

Last chance, try just catching parts of the message:

```
match sethome\,sethome
then deny
```

**Comment by malonnnn** [comment]
@TheCrazyBoi 

I can recommend other plugins that can fairly easily edit chat/commands before chatcontrol picks up on it, but that's the only solution I'm aware of for your particular problem

**Comment by kangarko** [comment]
Closing in faith that this has been solved or workarounded
