### ISSUE TITLE
1.20.4: French language text file issue

### ISSUE THREAD

**Issue by v4rl1** [kangarko/ChatControl#2640]
### "/version ChatControlRed" - plugin version

10.25.4

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/bb214e2078bc46f7a9b29ccb38b5b185

### "/chc debug" output (strongly recommended)

https://ufile.io/j6iqyl6b

### Information about the issue/bug

Had the issue when trying to use the command `/tag nick off`

**Comment by kangarko** [comment]
Thanks, will fix in the next version.
