### ISSUE TITLE
Minecraft Version 1.20.1 : Cant load pluggin

### ISSUE THREAD

**Issue by Master-Athreas** [kangarko/ChatControl#2641]
### "/version ChatControlRed" - plugin version

10.25.5

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://pastebin.com/cgRXCnT5

### Information about the issue/bug

cant load this chat pluggin in my server.

**Comment by Master-Athreas** [comment]
its fabric server

**Comment by Master-Athreas** [comment]
Paypal Transaction ID:
[58702967TE9709926]

SpigotMC username: Athreas

**Comment by kangarko** [comment]
I cannot see ChatControl in the log you provided when I search for the keyword "ChatControl"

**Comment by Master-Athreas** [comment]
It doesn’t log it. Like if it where not compatible idk.

On 11 Apr 2024, at 12:08, Matej ***@***.***> wrote:

﻿

I cannot see ChatControl in the log you provided when I search for the keyword "ChatControl"

**Comment by kangarko** [comment]
Your server software is incompatible. You need Paper or a software supporting Bukkit/Spigot/Paper plugins.
