### ISSUE TITLE
1.19.4: How to get uncensored public and private messages for logging

### ISSUE THREAD

**Issue by virustotalop** [kangarko/ChatControl#2642]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hello I'm having an issue getting logging working using a custom logging system for a client that I have. The issue is that with all the events I have tried thus far the message is still censored. I have tried using PreRuleMatchEvent and PlayerMessageEvent and neither once seems to fire. I've also tried using the SpyEvent, ChatChannelEvent and PrePrivateMessageEvent and all I'm getting is censored messages. I'm running ChatControlRed on the backend servers. Any advice on how to get around this? Thank you for the help.

**Comment by kangarko** [comment]
you closed it so i assume it's fixed
