### ISSUE TITLE
1.20.4 : Error on join and multi-server msg dont work

### ISSUE THREAD

**Issue by FrancescoJacovo** [kangarko/ChatControl#2644]
### "/version ChatControlRed" - plugin version

10.25.5 and 3.11.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://gist.github.com/FrancescoJacovo/1e9a55a765d01dc6008faccd92475a36

### "/chc debug" output (strongly recommended)

file sent via wetransfer on that mail

### Information about the issue/bug

For the msg it doesn't give an error, it comes out only on join but idk if broke something.

**Comment by kangarko** [comment]
Thanks, fixed in: https://github.com/kangarko/VelocityControl/commit/075da38c0e45534587d15a790ff61049acd29f00

Waiting for @james090500 to push release or you can just compile it yourself.  Thanks.
