### ISSUE TITLE
1.18.2: Crashing of 1.20+ Users

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl#2645]
### "/version ChatControlRed" - plugin version

10.25.5

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14968515/debug.zip)

### Information about the issue/bug

So Upon a 1.20.1 user joining my server and writing in one of my channels "roleplay" to be specific they are getting this error and getting kicked from my network:

![image](https://github.com/kangarko/ChatControl-Red/assets/16086663/aa10a3d1-c094-475f-a282-ca324b9d5092)

**Comment by Ash10744** [comment]
I also use viaversion + viabackwards for my network so this could be the cause but as its related to chat I thought I'd start here.

**Comment by kangarko** [comment]
Disable protocollib in the Integration part of settings.yml

**Comment by Ash10744** [comment]
Sorry hoping you'll see this asap but its still continuing with this error after I disabled protocollib
![image](https://github.com/kangarko/ChatControl-Red/assets/16086663/7a1ea347-777e-4a3e-bf74-4d6b883c5a0b)
[debug(1).zip](https://github.com/kangarko/ChatControl-Red/files/14981961/debug.1.zip)

**Comment by Ash10744** [comment]
It kicks the users from the server they can speak in my Network channel but not my Roleplay channels its really weird

**Comment by Ash10744** [comment]
I also recently updated my server to 1.20.4 and this issue is still persistant

**Comment by Ash10744** [comment]
So I recently found out this only happens to 1.20.1 users

**Comment by kangarko** [comment]
Definitely a viaversion or protocollib issue then. Check if they are on latest versions. I strongly recommend limiting your server to the latest subversion such as 1.20.4 since we are unable to solve issues on unsupported old subversions due to time constrains and the complexity.
