### ISSUE TITLE
BungeeControl Red not working properly 

### ISSUE THREAD

**Issue by xOnlyFadi** [kangarko/ChatControl#2646]
### "/version ChatControlRed" - plugin version

10.25.3

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[Bungee.zip](https://github.com/kangarko/ChatControl-Red/files/14968675/Bungee.zip)
[Lobby debug.zip](https://github.com/kangarko/ChatControl-Red/files/14968670/debug.zip)

### Information about the issue/bug

Hi im confused how `BungeeControl Red` works on bungee because I did all steps in the wiki sometimes Im getting the network switch message im not getting player joined the network im just getting quit most of the time im using XCord Custom Bungeecord fork

**Comment by xOnlyFadi** [comment]
@kangarko is this problem happening with a lot of people?

**Comment by kangarko** [comment]
Yes, we are making a new version out by tonight, thanks. Please test it and let us know below if you continue seeing this issue.

**Comment by xOnlyFadi** [comment]
I just saw the updated version on BBB Im getting quit messages and sometimes switch messages but not join messages here is my configs

join.rs
```
group default
prefix &8[&a+&8]
message:
- &e{player} &fjoined the network &7({server})
 ````

switch.rs
```
group default
prefix &8[&d>&8]
message:
- &e{player} &fhas switched from &7{from_server} &fto &7{to_server}
```

**Comment by kangarko** [comment]
Make sure the database is not loading data still. I will adjust the console warning message about slow databases regarding this.

In the next versions, set Debug to [player-message] in settings.yml for bungeecontrol red, you should see whats going on in the bungee console like this: https://i.imgur.com/j7A0jlm.png

**Comment by xOnlyFadi** [comment]
`[player-message] Detected xOnlyFadi join to auth-1, waiting for server data..`
does chr have to be installed even in the auth lobby?

**Comment by kangarko** [comment]
Correct. ChatControl needs to be on all spigot/paper servers from which you want the messages to show.
