### ISSUE TITLE
1.8, 1.12, 1.17, 1.20: Receivers still get empty messages when display conditions

### ISSUE THREAD

**Issue by gre3x** [kangarko/ChatControl#2647]
### "/version ChatControlRed" - plugin version

10.25.4

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

None

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/14968765/debug.zip)

### Information about the issue/bug

After updating to version 10.25.4 from 10.24.5, these features no longer work:
- Improve | No longer sends empty messages to chat if your chat format is empty depending on your display conditions.
- Improve | Better detection at not sending empty messages, now evaluating whether the message is empty per-receiver's format conditions.

Note that this did NOT happen in version 10.24.5

![image](https://github.com/kangarko/ChatControl-Red/assets/123699236/c0d739d0-e98a-49e0-b553-8127ca3fb5a4)

**Comment by gre3x** [comment]
@kangarko are you able to take a look at this soon? This is feature regression and breaks my current chat setup

**Comment by kangarko** [comment]
Please test the next version available in a few hours and if that issue continues let me know exactly which format is that again please

**Comment by kangarko** [comment]
Just comment below instead of opening a duplicate ticket

**Comment by kangarko** [comment]
Reproducing now...

**Comment by gre3x** [comment]
Thank you for looking into this!

Specifically, the format that has stopped working for filtering out the messages is global-chat.yml in my configs (see debug.zip).
The is not supposed to not send a message to the player if all parts of the message are filtered out by the `Receiver_Condition`. In 10.24.5, that has stopped working.

Below is the full filter that does work as a condition, but still sends the empty message (even though it is not supposed to send an empty message according to the above change logs). And it used to not send an empty message in version 10.24.5:
```
    Receiver_Condition: '''{advanciuschat_canview_{sender}}'' == ''true'''
```

Note that this did NOT happen in version 10.24.5

**Comment by gre3x** [comment]
Btw `advanciuschat_canview_{sender}` is just a placeholder api placeholder that returns "true" or "false" based on if that player has a certain toggle

**Comment by kangarko** [comment]
I cannot reproduce this issue. Try the next version where you set Debug key in settings.yml to [component] and it should print what it sees before sending to each player to the console:

![a](https://i.imgur.com/PKSqjYi.png)

Also note that console will always receive the full message because no conditions are evaluated against it.

**Comment by gre3x** [comment]
These are the debug messages:
```
18.04 19:23:06 [Server] Server thread/[INFO] [component] Sending Clans_MC message: §f§f
18.04 19:23:06 [Server] Server thread/[INFO] [ChatControlRed] [global] SiiRGEOO: cya everyone :D
18.04 19:23:09 [Server] Server thread/[INFO] [component] Sending Clans_MC message: §f§f
18.04 19:23:09 [Server] Server thread/[INFO] [ChatControlRed] [global] Zekobot2000: 30 fps rn
18.04 19:23:12 [Server] Server thread/[INFO] [component] Sending Clans_MC message: §f§f
```

**Comment by gre3x** [comment]
Not sure how those are coming up since there is nothing in the config like that. And again, everything is being filtered by the Receiver_Condition. 

Seems like you just need to strip the color codes before checking if the message is empty or not @kangarko 

Very odd that this started happening only in the new version... I'm guessing something changed to add those §f§f or the color codes stopped getting stripped

**Comment by kangarko** [comment]
We already strip it: 

![a](https://i.imgur.com/FkI07Yq.png)

But I placed the strip into the debug method here, please try this dev build with the new debug message and let me know what the console says now:

See the build below.

**Comment by kangarko** [comment]
Actually try this build:

[ChatControl-Red-10.25.8.zip](https://github.com/kangarko/ChatControl-Red/files/15030239/ChatControl-Red-10.25.8.zip)

**Comment by gre3x** [comment]
Using that attached version it is empty in console, but it is not filtered haha... very strange! Possibly it is something to do with it being a message from a seperate server in the BungeeCord network?

```
4 21:13:44 [Server] Server thread/[INFO] [component] [ignore empty=false] Sending Clans_MC message: ''
18.04 21:13:44 [Server] Server thread/[INFO] [ChatControlRed] [global] baebiekay: gg
18.04 21:13:44 [Server] Server thread/[INFO] [component] [ignore empty=false] Sending Clans_MC message: ''
18.04 21:13:44 [Server] Server thread/[INFO] [ChatControlRed] [global] KhaleesiKayy414: gg
18.04 21:13:46 [Server] Server thread/[INFO] [component] [ignore empty=false] Sending Clans_MC message: ''
18.04 21:13:46 [Server] Server thread/[INFO] [ChatControlRed] [global] Midnight60163: gg
18.04 21:13:46 [Server] Server thread/[INFO] [component] [ignore empty=false] Sending Clans_MC message: ''
```

And still see the empty messages on the player's screen:
![image](https://github.com/kangarko/ChatControl-Red/assets/123699236/7a0b2c44-b566-452f-9c0c-4f2d3e1a23b3)

**Comment by kangarko** [comment]
Yes, I missed the fact it came from another server. Does the bug happen with local messages or network messages as well?

You see the "ignore empty" being false flag which needs to be true for the ignore to happen, perhaps it's false from network messages. I'll investigate.

**Comment by gre3x** [comment]
@kangarko I just tested it and it happens with local and network messages. Some messages do somehow seem to be filtered though? It is very odd (these logs are from the users `MC_Legend` and `Clans_MC` on the same server with some other players on other bungee servers sending messages too:

```
21.04 01:20:23 [Server] Async Chat Thread - #26/[INFO] [global] MC_Legend: tt
21.04 01:20:25 [Server] Server thread/[INFO] [component] [ignore empty=false] Sending Clans_MC message: ''
21.04 01:20:25 [Server] Server thread/[INFO] [component] [ignore empty=false] Sending MC_Legend message: ''
21.04 01:20:25 [Server] Server thread/[INFO] [ChatControlRed] [global] Prototyzer: scutes will probably be 1 or 2 ingots
21.04 01:20:26 [Server] Server thread/[INFO] [component] [ignore empty=false] Sending Clans_MC message: ''
21.04 01:20:26 [Server] Server thread/[INFO] [component] [ignore empty=false] Sending MC_Legend message: ''
21.04 01:20:26 [Server] Server thread/[INFO] [ChatControlRed] [global] S4mmYT_: §dttttt
21.04 01:20:26 [Server] Server thread/[INFO] [component] [ignore empty=false] Sending Clans_MC message: ''
21.04 01:20:26 [Server] Server thread/[INFO] [component] [ignore empty=false] Sending MC_Legend message: ''
21.04 01:20:26 [Server] Server thread/[INFO] [ChatControlRed] [global] tgg99: tt?
21.04 01:20:26 [Server] Async Chat Thread - #26/[INFO] [component] [ignore empty=true] Sending Clans_MC message: ''
21.04 01:20:26 [Server] Async Chat Thread - #26/[INFO] [component] Message is empty, skipping.
21.04 01:20:26 [Server] Async Chat Thread - #26/[INFO] [component] [ignore empty=true] Sending MC_Legend message: ''
21.04 01:20:26 [Server] Async Chat Thread - #26/[INFO] [component] Message is empty, skipping.
21.04 01:20:26 [Server] Async Chat Thread - #26/[INFO] [global] MC_Legend: t
21.04 01:20:28 [Server] Server thread/[INFO] [component] [ignore empty=false] Sending Clans_MC message: ''
21.04 01:20:28 [Server] Server thread/[INFO] [component] [ignore empty=false] Sending MC_Legend message: ''
```

**Comment by kangarko** [comment]
[ChatControl-Red-10.25.8.zip](https://github.com/kangarko/ChatControl-Red/files/15053010/ChatControl-Red-10.25.8.zip)
Try this devbuild please. It has ignoreFalse on true from bungee messages.

**Comment by gre3x** [comment]
Yes that dev build worked thank you! @kangarko

**Comment by gre3x** [comment]
Will that change be part of the next version released?

**Comment by kangarko** [comment]
Yes of course!

**Comment by gre3x** [comment]
Great thank you! When will that new version be available @kangarko?

**Comment by kangarko** [comment]
Sorry I got sick. Hopefully tonight.
