### ISSUE TITLE
1.20.4: Random prefix in times.rs only select the first 2 options.

### ISSUE THREAD

**Issue by Denial234** [kangarko/ChatControl#2649]
### "/version ChatControlRed" - plugin version

10.25.5

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

When using the random prefix in times.rs it only sends out and randomized the first 2 options.
group json-sample
delay 600 seconds
prefix [JSON]
random
message: 
- "Message 1"
- "Message 2"
- "Message 3"
- "Message 4"

It will only send out message 1 & 2 randomly but never send out message 3 & 4

**Comment by kangarko** [comment]
I am geting json malformed error with your example: https://i.imgur.com/5ALaWlt.png

After removing the "prefix [JSON]" line it works fine: https://i.imgur.com/ZRgQMqg.png

Also make sure you update to tonights version please.

**Comment by Denial234** [comment]
It was an example. I use json fomat in the texts. Here is my normal one. 


group json-sample
delay 600 seconds
prefix [JSON]
random
message: 
- ["",{"text":"\n"},{"text":"Server tip #1","bold":true,"color":"gold"},{"text":"\n"},{"text":"Did you know that you can withdraw cash & XP into items?\nBy using","color":"gray"},{"text":" "},{"text":"/withdraw <amount>","color":"yellow","clickEvent":{"action":"suggest_command","value":"/withdraw "},"hoverEvent":{"action":"show_text","contents":["",{"text":"IMPORTANT TO KNOW","bold":"true","color":"red"},{"text":"\n"},{"text":"Performing this command will withdraw\nyour desired amount of ","color":"gray"},{"text":"cash","color":"yellow"},{"text":" and\nturn it into a bank note.","color":"gray"},{"text":"\n\n"},{"text":"Click to copy the command!","color":"yellow"}]}},{"text":" &","color":"gray"},{"text":" "},{"text":"/xpbottle <amount>","color":"light_purple","clickEvent":{"action":"suggest_command","value":"/xpbottle "},"hoverEvent":{"action":"show_text","contents":["",{"text":"IMPORTANT TO KNOW","bold":"true","color":"red"},{"text":"\n"},{"text":"Performing this command will withdraw\nyour desired amount of ","color":"gray"},{"text":"xp","color":"light_purple"},{"text":" and\nturn it into an xp bottle.","color":"gray"},{"text":"\n\n"},{"text":"Click to copy the command!","color":"yellow"}]}},{"text":"\n "}]
- ["",{"text":"\n"},{"text":"Server tip #2","bold":true,"color":"gold"},{"text":"\n"},{"text":"View your current stats & skills by using\nthe commands ","color":"gray"},{"text":"/stats","color":"yellow","clickEvent":{"action":"suggest_command","value":"/stats"},"hoverEvent":{"action":"show_text","contents":["",{"text":"Click to copy command!","color":"yellow"}]}},{"text":" & ","color":"gray"},{"text":"/skills","color":"yellow","clickEvent":{"action":"suggest_command","value":"/skills"},"hoverEvent":{"action":"show_text","contents":["",{"text":"Click to copy command!","color":"yellow"}]}},{"text":" and learn\nmore about your current levels & abilities.","color":"gray"},{"text":"\n "}]
- ["",{"text":"\n"},{"text":"Server tip #3","bold":true,"color":"gold"},{"text":"\n"},{"text":"Collect blocks & items and sell them to gain some\nextra cash by using either ","color":"gray"},{"text":"/sell all","color":"yellow","clickEvent":{"action":"suggest_command","value":"/sell all"},"hoverEvent":{"action":"show_text","contents":["",{"text":"IMPORTANT TO KNOW","bold":"true","color":"red"},{"text":"\n"},{"text":"Performing this command will sell all\nyour sellable items in your inventory.","color":"#B2ACA2"},{"text":"\n\n"},{"text":"Click to copy command!","color":"yellow"}]}},{"text":" or ","color":"gray"},{"text":"/sell hand","color":"yellow","clickEvent":{"action":"suggest_command","value":"/sell hand"},"hoverEvent":{"action":"show_text","contents":["",{"text":"IMPORTANT TO KNOW","bold":"true","color":"red"},{"text":"\n"},{"text":"Performing this command will sell the\ncurrent item you're holding in your hand.","color":"#B2ACA2"},{"text":"\n\n"},{"text":"Only works if the item is sellable.","color":"dark_gray"},{"text":"\n\n"},{"text":"Click to copy command!","color":"yellow"}]}},{"text":"\n "}]
- ["",{"text":"\n"},{"text":"Server tip #4","bold":true,"color":"gold"},{"text":"\n"},{"text":"You can toggle these tips on & off\nby typing ","color":"gray"},{"text":"/toggle timed","color":"yellow","clickEvent":{"action":"suggest_command","value":"/toggle timed"},"hoverEvent":{"action":"show_text","contents":["",{"text":"IMPORTANT TO KNOW","bold":"true","color":"red"},{"text":"\n"},{"text":"Turning these tips off could lead to\nyou not properly being informed on\nall the features we have to offer.","color":"gray"},{"text":"\n\n"},{"text":"You can toggle them back on by\nusing the same command again.","color":"dark_gray"},{"text":"\n\n"},{"text":"Click to copy command!","color":"yellow"}]}},{"text":" in chat.","color":"gray"},{"text":"\n "}]

**Comment by Denial234** [comment]
The problem wasn't the json format as i only sent an example. My actual timed.rs was setup just fine. Maybe i just got really unlucky when it came to the randomness of the messages and recieved message 1 & 2 multiple times in a row.

**Comment by Denial234** [comment]
My bad

**Comment by kangarko** [comment]
No worries!
