### ISSUE TITLE
[bug] Using {nick} in formatting for v7.5.10 creates NullPointerException

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl#265]
Finally spent the time upgrading my configs to the latest and greatest so I could get on 7.5.10, Turns out you can no longer use {nick} after a TON of trial and error trying to figure out why the formatter wasn't working!

https://pastebin.com/9fVM3Qwa

**Comment by kangarko** [comment]
This is Issues Channel for the free version, please post to the correct section.

Btw, error has been resolved.

**Comment by FrozenBeard** [comment]
I just used the link from the Pro versions page to post this, your page links here.
Thanks for fixing it.

**Comment by kangarko** [comment]
Where is the invalid link please, so I can fix it?

**Comment by FrozenBeard** [comment]
In the TOS, it says for the Pro version it states;
**§7 I only give support on this forum and GitHub. Be aware of fraud attempts.**
So I Clicked that Github link as it was in the Terms.

**Comment by kangarko** [comment]
Thank you, fixed!
