### ISSUE TITLE
1.20.4: Tablist still doesn't update prefix & suffix upon change.

### ISSUE THREAD

**Issue by Denial234** [kangarko/ChatControl#2650]
### "/version ChatControlRed" - plugin version

10.25.5

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

**After tablist update, still does not update the placeholders until after you rejoin the server:**

Tablist feature does not update when you change prefix & suffix until you rejoin. I feel like this has nothing to do with the permissions plugin i'm using because the tablist works fine when i'm not using chat control red to manage my tablist. It works totally fine when i use TAB and updates as soon as i change group and give myself a new suffix using supremetags. Although as soon as i switch plugin to Chatcontrol RED to handle my tablist i have to rejoin every time i want the tablist to update the changes i've made.
Every other plugin works except for this plugin when it comes to the tablist.
It doesn't matter what placeholder i use, nothing updates until you rejoin. Except for the username when i change nick using /chc tag

**Comment by kangarko** [comment]
I am sorry, lets continue at your previous ticket I just answered.
