### ISSUE TITLE
Chat Pings

### ISSUE THREAD

**Issue by real-vgi** [kangarko/ChatControl#2652]
### Summary

Ping players like you do in Discord.

@everyone - Requires permission: chatcontrol.ping.everyone
Will ping everyone from all channels.

@here - Will ping everyone inside the channel the message is sent to. - Requires permission: chatcontrol.ping.here

@player - Pings certain player

@<luckperms_group> - Pings all people from a luckperms group. Ex: Mod, Helper, Ping4Help, Etc.) 
Requires permission node: chatcontrol.ping.group.<luckperms_group>

Note: There should be a buffer between pings so people do not abuse this feature.
 

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Most Chat plugins nowadays have a Pings feature, where you can @<player> just like you would do in Discord.
I was personally surpised that one of the best chat plugins, if not the best chat plugin doesn't have a pings feature yet.

**Comment by kangarko** [comment]
Thanks, we already have a sound notify feature which works similarly. You can find it in settings.yml
