### ISSUE TITLE
1.20.2: Disable ChatControl formatting in TownyChat channels

### ISSUE THREAD

**Issue by real-vgi** [kangarko/ChatControl#2653]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

No

### Question

I would like to localize ChatControlRed so it only formats its own channels and leaves TownyChat's TC, NC and AC alone.

**Comment by kangarko** [comment]
Use the latest version and play around with listener priority (see Wiki on how to do that). Perhaps one of the options will make the plugin not format TC channels. If that wont work then it unfortunately is incompatible - in which case you can make a towny chat channel in chatcontrol using our Party option and configure formatting in our plugin instead.

**Comment by real-vgi** [comment]
It is uncompatible. How would making a channel work?
TownyChat works by creating a channel for each town that is only accessible by the members of that town.

**Comment by kangarko** [comment]
Right, you can make a similar channel in chatcontrol in settings.yml > Channels > List. And write the [Party option](https://github.com/kangarko/ChatControl-Red/wiki/Channels#party) there set to "towny-town". It will make a channel where only players of the same town can chat.
