### ISSUE TITLE
1.20.4: rules/command.rs redirecting a command remains red in chat but works.

### ISSUE THREAD

**Issue by Denial234** [kangarko/ChatControl#2655]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I had a question regarding the way you can redirect a command into a custom command in command.rs.

If i wanted to redirect the command /heal to /healing (example)
Is there a way for the command to not be red marked when you type it in the game and also allow to auto complete to the custom command?

When i type in /heal, since thats the actual command, it auto completes and also turned white as a normal command should when i typed it in completely. But when i type in /healing, it is red. As if it isn't an actual command that you can type in.
Is this something that is fixable or is it just the way minecraft works?

**Comment by Denial234** [comment]
The command /healing still works but its red.

**Comment by kangarko** [comment]
I am afraid not, tab completions are done differently since 1.13 and we dont inject them as a command for technical reasons. Try using commands.yml in root server folder for command aliases instead.

**Comment by Denial234** [comment]
Oh i see. That's alright. Thank you for responding ^^
