### ISSUE TITLE
1.20.4: Formát chatu

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [kangarko/ChatControl#2656]
### "/version ChatControlRed" - plugin version

ChatControl-Red-10.25.8.jar

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

Posláno na email

### Information about the issue/bug

Dobrý den, 

 do verze "ChatControl-Red-10.25.5.jar" nebyl žádný problém, každopádně jakákoliv novější aktualizace mi ukazuje duplikační formát v chatu. Lze to vidět na přiloženém obrázku.
  Stejně tak v settings mám zakázán discord a má zpráva se pošle automaticky i na discord. Zkoušel jsem i nejnovější aktualizaci "ChatControl-Red-10.25.8.jar", bohužel problém stále přetrvává. 
Děkuji
![Snímek obrazovky 2024-04-18 230529](https://github.com/kangarko/ChatControl-Red/assets/68572049/c5a2a2c1-aa87-4f8b-9238-67df5fe329d2)

**Comment by kangarko** [comment]
Dobry den,

Skusali ste [zmenit listener prioritu](https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities)?

A tiez skontrolujte, ci Multiverse-Core ma vypnute formatovanie chatu. Je treba zistit odkial prichadza ten stary [LobbyNormal] chat a vypnut to. 

Mame novy listener pre chat ktory vyuziva moderny event od Paper. Preto mohlo dojst k tomu ze ten druhy chat sa zobrazuje pred nami. Pokial nic nezafunguje viem do configu pridat nastavenie o zapnute stareho eventu

**Comment by Sh3r1ffCZ** [comment]
> Dobry den,
> 
> Skusali ste [zmenit listener prioritu](https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities)?
> 
> A tiez skontrolujte, ci Multiverse-Core ma vypnute formatovanie chatu. Je treba zistit odkial prichadza ten stary [LobbyNormal] chat a vypnut to.
> 
> Mame novy listener pre chat ktory vyuziva moderny event od Paper. Preto mohlo dojst k tomu ze ten druhy chat sa zobrazuje pred nami. Pokial nic nezafunguje viem do configu pridat nastavenie o zapnute stareho eventu


Zkoušel jsem teď v multiverse vypnout vše, co je spojené s chatem.
Do ChatControl jsem dal:
 Chat_Listener_Priority: HIGHEST
Přes DiscordSRV jsem našel problém, jak vypnout odesílání zpráv na Discord.

Každopádně  problém ovšem stále přetrvával a zjistil jsem, že to dělá config v CMI chat.yml 
 "ClickHoverMessages: true"
Chat od CMI mám celý vyplý, používám jen jejich MSG a tohle má zajistit jen to, že lze na zprávu od MSG kliknout a aby naskočil příkaz /msg nick. Je škoda, že i když mám Chat_Listener_Priority: HIGHEST, tak to bohužel stále lze vidět v chatu. Myslíte, že by byla možnost, že byste přidal do configu zapnutí starého eventu? Omlouvám se za problémy, ale chtěl bych mé nastavení serveru zachovat

**Comment by Sh3r1ffCZ** [comment]
Což tedy v CMI mám kompletně vyplý chat format, jen ten clickhover je zaplý:

Chat:
Will try to modify chat to display it in defined format
  ModifyChatFormat: false
  When set to true, regular and private messages (excludes clean messages) will have additional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: true

**Comment by kangarko** [comment]
Prosim otestujte tento build. V settings.yml je nutne nastavit Modern_Chat_Listener na false aby sa spraval, tak ako v starej verzii.

[ChatControl-Red-10.25.8.zip](https://github.com/kangarko/ChatControl-Red/files/15049225/ChatControl-Red-10.25.8.zip)

**Comment by Sh3r1ffCZ** [comment]
> Prosim otestujte tento build. V settings.yml je nutne nastavit Modern_Chat_Listener na false aby sa spraval, tak ako v starej verzii.
> 
> [ChatControl-Red-10.25.8.zip](https://github.com/kangarko/ChatControl-Red/files/15049225/ChatControl-Red-10.25.8.zip)

Nastavil jsem Modern_Chat_Listener: false, ale bohužel stále vidím 2 zprávy v chatu

**Comment by kangarko** [comment]
S Modern_Chat_Listener na false je stale nutne vyskusat rozne listener priorities, skus LOWEST, NORMAL, HIGHEST a aj MONITOR

**Comment by Sh3r1ffCZ** [comment]
> LOWEST

Nastavil jsem:
Chat_Listener_Priority: LOWEST
Modern_Chat_Listener: false

A vše OK, jak má být. Děkuji za pomoc, myslím, že by teď mělo být vše v pořádku

**Comment by Sh3r1ffCZ** [comment]
Omlouvám se, že otravuji, ale bude s tím asi více problémů :D 
Nelze teď zobrazit předmět v chatu přes showitem, pomocí "%item%"
Stejně tak mi teď nejde PartyChat-4.2.1 😄 

Prozatím asi nechám ChatControl-Red-10.25.5.jar a vyčkám na starém paperu, než tak nějak na vše budou pluginy připravené

**Comment by kangarko** [comment]
Nevieme podporit kazdy plugin, pretoze vela developerov si nastavuju priority podla seba a my vieme zmenit len tu nasu. Obavam sa ze tie ine pluginy su nekompatibiline. Mozes sa pohrat s nasou prioritou, kedze je tam celkovo 6 priorit plus stary/novy rezim cize 6*2 = 12 moznosti, a mozno jedna z nich zafunguje.

Ak nie tak pouzi [item] placeholder z naseho pluginu.

**Comment by Sh3r1ffCZ** [comment]
> Nevieme podporit kazdy plugin, pretoze vela developerov si nastavuju priority podla seba a my vieme zmenit len tu nasu. Obavam sa ze tie ine pluginy su nekompatibiline. Mozes sa pohrat s nasou prioritou, kedze je tam celkovo 6 priorit plus stary/novy rezim cize 6*2 = 12 moznosti, a mozno jedna z nich zafunguje.
> 
> Ak nie tak pouzi [item] placeholder z naseho pluginu.

To samozřejmě naprosto chápu a s vaší prací jsem naprosto spokojený. Už jak jsem napsal, tak jsem věděl, že se mi tu pomoci dostane.

Chat zatím i na nejnovější verzi funguje zcela parádně a těch 12 možností ještě vyzkouším a věřím, že i výzvy v chatu od tryme nebo partychat bude fungovat také. 
Děkuji ještě jednou za pomoc

**Comment by kangarko** [comment]
Za malo, vdacne :)
