### ISSUE TITLE
Ability to freeze chat

### ISSUE THREAD

**Issue by lilynet336** [kangarko/ChatControl#2657]
### Summary

I suggest adding the ability to freeze chat, with a configurable list of channels to freeze, that freeze upon a command in game such as `/freezechat` or `/freeze`. This way, if something is going really wrong in the chat, or an event is being held, one can prevent players from spamming all at once. If there's a way to do this with a rule that I haven't thought of, please let me know.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Per the first use case outlined above, not having this feature could make it hard to deal with mass amounts of players behaving poorly in the chat. 
Per the second, it is technically possible by making the default channel(s) restricted by permission so that players don't have any writable channels. But this isn't the easiest solution either and requires editing the config file on every server in the network.

**Comment by kangarko** [comment]
Hello,

We already implement the /mute function. You can mute the chat, server or a player using this command.

**Comment by lilynet336** [comment]
That’s my fault for not reading the documentation. I figured that command would be player-only. I’m sorry.

**Comment by kangarko** [comment]
I think it also can be executed from the console.

**Comment by lilynet336** [comment]
I mean like only having the ability to mute a single player at a time, sorry

**Comment by lilynet336** [comment]
But that’s also good to know, thank you

**Comment by kangarko** [comment]
Yes its possible to mute a single player at a time through the /mute command as I explained above
