### ISSUE TITLE
1.20.4: Chat formatting not applied to channels in all backend servers

### ISSUE THREAD

**Issue by Gingied** [kangarko/ChatControl#2658]
### "/chc debug" output (strongly recommended)

Debug is from my survival server: [debug.zip](https://github.com/kangarko/ChatControl-Red/files/15050350/debug.zip)

### Information about the issue/bug

I have 3 backend servers running; creative, survival, and a lobby. All 3 have the same chatcontrolred config settings, but with unique (matching server.properties) server names in bungee.yml. Despite this, chat is only formatted in the lobby server, join/leave/switch messages send inconsistently, and chat is passed from the lobby server to the survival and creative, but not from the survival or creative to the others. 

Velocity 3.3.0-376
Purpur 1.20.4-2172

**Comment by Gingied** [comment]
Multiple restarts and an update to one server that was not on the exact same purpur build fixed this, my bad

**Comment by Gingied** [comment]
Uh... apologies, This issue is back after more restarts. As described above, all of my servers have the same ChatControlRed config save for bungee.yml. I have one global chat channel, which is autojoined by default and has "Bungee: 'true'" in the channel config section of the settings. The only server in which the global chat formatting and passthrough is working is the lobby. 

I can use /list to show network players in all of the backend servers, and join, leave, and switch messages are formatted correctly when they appear in all servers, it's just my main chat channel which is not formatted on servers other than my lobby. If there's more information needed for debugging I'll do my best to provide it.

**Comment by kangarko** [comment]
Please update velocitycontrol/ccr to the new versions that will be released tonight and let me know if it will continue to happen.

**Comment by Gingied** [comment]
Still having this issue unfortunately :/

**Comment by kangarko** [comment]
Sorry for the wait, I did not get the chance to push the update.

In the next version please set Debug to [player-message] in both velocity and chatcontrol. When the join/quit message should happen but does not, send me your console logs please.

**Comment by kangarko** [comment]
The update should come out tonight.

**Comment by kangarko** [comment]
Closing, let me know if you have any more questions below

**Comment by Gingied** [comment]
After installing the update, I regenerated all my configs and pasted my MYSQL/bungee stuff back in, and it seems to be working. I did attempt to paste the plugin folder from a working server to the others multiple times, but it didn't hook up quite right until i regenerated them. Thanks for the fix!

**Comment by kangarko** [comment]
You're welcome!
