### ISSUE TITLE
1.20.1/1.20.4: Join msg not reliable

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#2659]
### "/version ChatControlRed" - plugin version

10.25.8

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

I've sent an email

### Information about the issue/bug

This video show that when players that have not joined in a long time doesn't have any join msgs.
[https://youtu.be/jIrqu2IPmYQ](https://youtu.be/jIrqu2IPmYQ)

The video is a little old but the same issue is currently still happening.

**Comment by kangarko** [comment]
Please update velocitycontrol/ccr to the new versions that will be released tonight and let me know if it will continue to happen.

If yes, set Debug to [player-message] in settings.yml in velocitycontrol and crr and send me the console logs when the message is not appearing.

Wait for the next version please

**Comment by MADS0LADEN** [comment]
im using bungeecontrol

**Comment by kangarko** [comment]
Sorry I got sick, could not make a new release. Same applies for BungeeControl, the new update will come out tonight.
