### ISSUE TITLE
[Question] Nicknames and mcmmo

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#266]
For some reason McMMO still uses CMI's nickname system, despite it being disabled.. how can I let ChatControl take over display names in third party plugins? 

If I reset all CMI's nicknames, then it just shows the minecraft playername. 
Is it because ChatControl doesn't have compatibility to hook into mcmmo that way?

**Comment by kangarko** [comment]
Thanks, I will expand the API calls to call all three methods so it should be covered.

<img width="962" alt="Screen Shot 2020-12-15 at 13 16 16" src="https://user-images.githubusercontent.com/1918426/102213905-bde93480-3ed7-11eb-9a3d-e504aba4c283.png">
