### ISSUE TITLE
1.20.4 : Server Prefix working opposite to expectation

### ISSUE THREAD

**Issue by markie1611** [kangarko/ChatControl#2661]
### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/15098590/debug.zip)

### Information about the issue/bug

Hello, I recently set my Chatcontrol up on a velocity network for the first time and I think I've misunderstood a behaviour. In  Bungee.yml there's the code 
```
# The optional prefix before all messages so that you know where they are coming from.
Prefix: '[G]'
```

Which to me means any message sent from this server will have the [G] in front.
but the behavior is that all messages I receive from players on others servers all have [G] while I'm in this server, making it impossible to distinguish which server sent it. 
I've probably set something up wrong, but any help would be great.

**Comment by Gingied** [comment]
Second this. I am seeing the same behavior using 1.0.1-BETA, where all received messages have the server's configured prefix, but sent messages do not.

**Comment by kangarko** [comment]
Thanks guys, fixed. A new release will appear tonight.
