### ISSUE TITLE
1.19.4: CCR Messes with Enchant Registry (Token Enchant)

### ISSUE THREAD

**Issue by VyperzDev** [kangarko/ChatControl#2662]
### "/version ChatControlRed" - plugin version

10.25.8

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.helpch.at/cuzogipenu.md

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/15119471/debug.zip)

### Information about the issue/bug

install Token Enchant(worldguard depend) & ChatControlRed on the server. 

https://polymart.org/resource/tokenenchant-1-7-10-1-20-x.155

**Comment by kangarko** [comment]
Thanks. Should be fixed. I tested it with ExcellentEnchants 4.0.4
