### ISSUE TITLE
1.20.4: Translate problem!

### ISSUE THREAD

**Issue by smscentras** [kangarko/ChatControl#2663]
### "/version ChatControlRed" - plugin version

10.25.8

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Can't translate one line in "/ignore":
**Toggle seeing messages/PMs from players.**

**Comment by kangarko** [comment]
Should be fixed in the new version tonight. Edit Commands.Ignore.Description in your locale file: https://i.imgur.com/5r6YlFg.png
