### ISSUE TITLE
Not compile

### ISSUE THREAD

**Issue by BAD7777** [kangarko/ChatControl#2665]
### Information about the issue/bug

 mvn compile
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.mineacademy:VelocityControl:jar:1.0.2
[WARNING] 'dependencies.dependency.version' for org.mineacademy:VelocityFoundation:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 20, column 13
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------< org.mineacademy:VelocityControl >-------------------
[INFO] Building VelocityControl 1.0.2
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.velocitypowered:velocity-api:jar:3.3.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.146 s
[INFO] Finished at: 2024-04-28T12:28:56+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project VelocityControl: Could not resolve dependencies for project org.mineacademy:VelocityControl:jar:1.0.2: Failed to collect dependencies at org.mineacademy:VelocityFoundation:jar:LATEST: Failed to read artifact descriptor for org.mineacademy:VelocityFoundation:jar:LATEST: Failed to resolve version for org.mineacademy:VelocityFoundation:jar:LATEST: Could not find metadata org.mineacademy:VelocityFoundation/maven-metadata.xml in local (C:\Users\BAD7777\.m2\repository) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by BAD7777** [comment]
What is the version of the dependency?

**Comment by kangarko** [comment]
I dont provide support for self compilation. But a tip - download VelocityControl to your disk and compile it first.
