### ISSUE TITLE
ChatControl Command Issues

### ISSUE THREAD

**Issue by DarkSlayer995** [kangarko/ChatControl#2666]
### "/version ChatControlRed" - plugin version

10.25.9

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

N/A

### "/chc debug" output (strongly recommended)

Hey, I have a problem with the Plugin when using the command /chc help 1 or /chc help I get kicked with an Error (See Screenshot) the weird thing is /chc help 2 is working without any problems I have No errors in Console. Is there a way to fix this?

![image](https://github.com/kangarko/ChatControl-Red/assets/78599947/acdec92c-c2c1-49ab-89b8-647ca95106c9)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/15142663/debug.zip)

### Information about the issue/bug

N/A

**Comment by DarkSlayer995** [comment]
Our Plugins ^^ 

![image](https://github.com/kangarko/ChatControl-Red/assets/78599947/c220e2f1-ba74-4701-a7c1-c96e26d351d0)

**Comment by kangarko** [comment]
Set Strip_Oversized_Json to true in settings
