### ISSUE TITLE
1.20.5: ChatControl fails to load

### ISSUE THREAD

**Issue by TheClowner** [kangarko/ChatControl#2667]
### "/version ChatControlRed" - plugin version

10.25.9

### Are you using MySQL?

No

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://pastebin.com/dHiBHvYs

### Information about the issue/bug

The plugin doesn't load using the latest build of Paper 1.20.5, despite the changelog for 10.25.9 claiming to add support for 1.20.5. 

This was a fresh install of the plugin, so the settings.yml file is the default.

**Comment by kangarko** [comment]
Because you did not pray before upgrading your server

**Comment by kangarko** [comment]
I am just kidding. The next version should fix load issues on Paper
