### ISSUE TITLE
1.20.4: How to disable clickable links

### ISSUE THREAD

**Issue by Pantera07** [kangarko/ChatControl#2668]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

No

### Question

How to disable clickable links?

I want to disable clickable on all links or on links I don't allow.

**Comment by kangarko** [comment]
We dont have a toggle for this yet. You can install Essentials and give players negative essentials.chat.url

**Comment by Pantera07** [comment]
@kangarko
Latest vanilla Minecraft servers don't make chat urls clickable by default.
This only happens when using ChatControl-Red.

**Comment by Pantera07** [comment]
This plugin is not open source, so the method below is currently the best I can do.
```
match ([a-zA-Z0-9]+(\.[a-zA-Z0-9]+)+)
before replace (([a-zA-Z]./)*(whitelist\.domain)) with (whitelist,domain)
then replace $1΄
```

**Comment by Pantera07** [comment]
or
formats
```
  message:
    Message: '&7: {player_suffix}{chat_color}{chat_decoration}{message}'
    Open_Url: ' '
```

**Comment by kangarko** [comment]
I'll add the option in Channels.Make_Links_Clickable in settings.yml you can turn off to stop making links clickable.

**Comment by Pantera07** [comment]
Thanks!
