### ISSUE TITLE
[Issue] Nickname system

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#267]
It seems that tab-complete listens to nicknames rather then minecraft names. If my name is Sikatsu, and I change my nickname to Shane, people can no longer use /w Sikatsu since it will say that player is not in the database for some reason. /msg Shane works fine however.

Minecraft 1.16.4, Bungee and MySQL.

**Comment by kangarko** [comment]
Yes, we have an entire tab-completion system for nicknames. Is the /w command from Essentials or ChatControl?

**Comment by Sikatsu** [comment]
ChatControl, I do not have essentials. I understand tab-completion works for nicknames, but why does it make normal minecraft names no longer work?

**Comment by kangarko** [comment]
This seems no longer to be an issue on the upcoming release 👍 

![nick](https://user-images.githubusercontent.com/1918426/102524419-4236e580-4099-11eb-9214-a932f8e6b900.gif)
