### ISSUE TITLE
Minecraft Version: Purpur 1.20.4 build 2176 - Broken parsing & private messages

### ISSUE THREAD

**Issue by BlindMag** [kangarko/ChatControl#2670]
### Error log (if applicable)

https://gist.github.com/Kirrasio/6957959d70ae89911da81e0fe8ca3d72

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/15179839/debug.zip)

### Information about the issue/bug

Chatcontrol red is not parsing the on hover placeholders correctly and private messages are not going through. 
When fully updated on our main server the error I sent spams the server console.

We are running velocity control red 
CHC v10.25.10
Purpur 1.20.4 build 2176
Velocity 3.3.0
Velocity Control 1.0.2

**Comment by kangarko** [comment]
Wait for the next release out tonight.

If it still happens, provide me the exact steps to reproduce this issue below please.
