### ISSUE TITLE
Unhandled make people spam as much as they want.

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#2671]
### "/version ChatControlRed" - plugin version

10.25.8

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/bf3055a889a8419c846cd3bcb3c909fc

### Information about the issue/bug

someone was spamming "space"  like empty message.
![image](https://github.com/kangarko/ChatControl-Red/assets/48274082/351a604f-6dea-4d45-b8a4-2962cd48c918)

**Comment by kangarko** [comment]
Update to this devbuild:

[ChatControl-Red-10.26.0.jar.zip](https://github.com/kangarko/ChatControl-Red/files/15212101/ChatControl-Red-10.26.0.jar.zip)
