### ISSUE TITLE
1.20.4: Velocity Cross-Network Chat No Longer Works

### ISSUE THREAD

**Issue by JerichoTorrent** [kangarko/ChatControl#2672]
### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/15211162/debug.zip)

### Information about the issue/bug

So, as referenced in a previous issue I created back in late 2023-ish, I had managed to get cross-network chat working beautifully. I made absolutely sure not to touch anything that could mess with this, as I wasn't entirely sure how I did it. After updating ChatControl Red 10.25.10, and buying the premium VelocityControl (latest version), cross-network chat broke. I saw that some things had changed but went through the wiki extensively to make sure I did everything right:
- double checked my database connections (working)
- made sure server names were correct in bungee.yml, as well as velocity.toml and server.properties (though I think that's deprecated now?)
- bungee is set to true and server names are all consistent
So, being that I made no changes on my end before it broke, and have exhausted all documentation to figure it out, is there anything I need to still change to get this to work? I am seeing join, quit, switch messages show up (somewhat). But /pm is not tab-completing and nobody in my global channel on any backend server is seeing messages from other backends. FYI, the debug file is from one of my backend servers (lifesteal). Help.

**Comment by JerichoTorrent** [comment]
Edit: I'm actually on CCR 10.26.0

**Comment by NeverGrowUp** [comment]
Can confirm we are getting the same issue. Previously on V10.25.10 and cross server chat was fine (with the exception of this https://github.com/kangarko/ChatControl-Red/issues/2670)

But now no cross server chat with V10.26.0 and VelocityControl v1.0.3

**Comment by kangarko** [comment]
You now need to disable bungee-plugin-message-channel = false in velocity.toml 

https://github.com/PaperMC/Velocity/issues/1312

Next VelocityControl will implement the other bungeecord messages so your other plugins wont break.

**Comment by JerichoTorrent** [comment]
> You now need to disable bungee-plugin-message-channel = false in velocity.toml

That breaks server switching commands, voting, and a plethora of other features velocity-side. Not really an option, sorry to say.

**Comment by celciusjj** [comment]
@JerichoTorrent I am agree with u, with no pay for a plugin with poor compability with the other plugins.

**Comment by celciusjj** [comment]
@kangarko will be solved in next update?

**Comment by kangarko** [comment]
As of latest VelocityControl, we will handle other plugin compatibility automatically. Can you please retest?

**Comment by JerichoTorrent** [comment]
> As of latest VelocityControl, we will handle other plugin compatibility automatically. Can you please retest?

Can confirm it now works! Thank you for the prompt fix.
