### ISSUE TITLE
1.20.4 Question about velocity

### ISSUE THREAD

**Issue by celciusjj** [kangarko/ChatControl#2673]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Why is the reason to disable

`bungee-plugin-message-channel = false`

breaks some plugins that used this.

Thanks for answer

**Comment by kangarko** [comment]
You can just install BungeeQuack. 

The reason is that the BungeeCord plugin message channel is taken over by Velocity and you won't see our messages after that.

**Comment by kangarko** [comment]
https://github.com/PaperMC/Velocity/issues/1312

**Comment by celciusjj** [comment]
@kangarko The result is the same, i test with bungeBark and bungeQuarck.

Putting false in the flag breaks all plugins for chatcontrol, that use this channel, generating a big compatibility problem with chatcontrol and other plugins!

also we pay for velocity control, but thats not works since its compatibility with other plugins is zero, before it worked better and we did not pay for it

**Comment by kangarko** [comment]
As of latest VelocityControl, we will handle other plugin compatibility automatically. Can you please retest?

**Comment by celciusjj** [comment]
Looks well, i will more test!
