### ISSUE TITLE
Suggestion: Discord ignore support

### ISSUE THREAD

**Issue by Pantera07** [kangarko/ChatControl#2674]
### Summary

Players cannot ignore Discord users.
I suggest adding a command to ignore messages sent from Discord.

Previous issue was not completed. I can wait until you have time to add this. https://github.com/kangarko/ChatControl-Red/issues/2530

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Players can't ignore Discord spam.

**Comment by kangarko** [comment]
Added

**Comment by kangarko** [comment]
Took me some time, I'd appreciate if you could drop a review at https://www.trustpilot.com/review/mineacademy.org :)

**Comment by Pantera07** [comment]
Thanks!
