### ISSUE TITLE
1.20.4 - Warp Forwarding Via PluginChannel

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#2677]
### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/15275186/debug.zip)

### Information about the issue/bug

On Velocity you say 
```
VelocityControl has detected a communication issue:
Set 'bungee-plugin-message-channel' to false in
in velocity.toml. We need this to broadcast
on BungeeCord channel.
Notice: We will handle BungeeCord channel for
other plugins so they will continue to function.
```

The Problem is, that the Plugin HuskHomes works with these channels and the Serverwide homes and warps stops working, when setting `bungee-plugin-message-channel` to `false`. Something, we cant stop to work with.

When changing channels with `/ch j <channelname>` we dont get a message anymore, when setting the above setting to true, we dont have serverwide message channels

Any Idea on how to solve this? 

Edit: 
Java 17

Velocity-3.3.0-390
VelocityControl-1.0.5

Paper-1.20.4-496
ChatControlRed-10.26.2

**Comment by kangarko** [comment]
" We will handle BungeeCord channel for
other plugins so they will continue to function."

Did you actually try disabling that option and you are talking from experience or assumptions? Bc we handle the lack of that channel

**Comment by Lorias-Jak** [comment]
I actually tried to disable that option. After that, the home / warp plugin stopped working.

I'm using this as home / warp plugin- https://modrinth.com/plugin/huskhomes

**Comment by kangarko** [comment]
Thanks for confirming, I'll test and fix that in 1-3 days

**Comment by kangarko** [comment]
I've tested with the following sample code:

```java
			final ByteArrayDataOutput out = ByteStreams.newDataOutput();
			out.writeUTF("Connect");
			out.writeUTF("flat");

			getPlayer().sendPluginMessage(SimplePlugin.getInstance(), "BungeeCord", out.toByteArray());
```

Without VelocityControl when bungee-plugin-message-channel is false it was not working, but with VelocityControl it started to work. That means we do relay that channel normally.

I can try reproducing with your mentioned plugin, please provide the steps to reproduce i.e. how to get to that feature that doesnt work?

**Comment by Lorias-Jak** [comment]
I provided you the config we use. You need to setup a database and put in your credentials, as well as you need redis.
We have a velocity proxy setup. It's an easy proxy to subserver network. No multi-proxy setup.

Proxy
  |
  | --- aegorin_reb
  | --- aegorin_farm
  | --- bauteam

* Download HuskHomes (use version 4.6.2): https://modrinth.com/plugin/huskhomes/versions?c=release&l=paper
* Here is the setup guide in case you need it: https://william278.net/docs/huskhomes/setup
* And our config from one of our servers: [huskhomes-config.zip](https://github.com/kangarko/ChatControl-Red/files/15340737/huskhomes-config.zip)

**Comment by kangarko** [comment]
Thanks. Just to confirm, then I need to set a warp on another server and try to teleport to it from a different server? And that no longer functions?

**Comment by Lorias-Jak** [comment]
Exactly. Just set two warps, one on each server and try to warp between these.

**Comment by kangarko** [comment]
Thanks. Sorry I didnt get to it yet :/ We've been having a product launch and now company holiday. Will take as first priority upon returning May 26th.

**Comment by Lorias-Jak** [comment]
Unfortunate, but understandable. Pleasant vacation

**Comment by kangarko** [comment]
Can you please try this build and tell me if it works? Works on my end but I noticed you used redis and I am unable to test on redis. Keep bungee-plugin-message-channel on false in velocity.toml.

[VelocityControl-1.0.6.zip](https://github.com/kangarko/ChatControl-Red/files/15458267/VelocityControl-1.0.6.zip)

**Comment by Lorias-Jak** [comment]
I'tll take some time to test, as i dont have the time today and tomorrow. I'll try my best to do it asap

**Comment by kangarko** [comment]
No worries! I did test the build, made two warps, and it was working before chatcontrol was installed with the velocity option on true and after with it being false, I just wanted to make sure you have the same result. Closing, assuming done, just reply below if anything.

**Comment by Lorias-Jak** [comment]
It's working now, thank you!

**Comment by Lorias-Jak** [comment]
Just a short question, will there be an official release of this with the sink forward spam in console removed? Or deactivatable? Currently were getting something between 30-50 (i didnt wanted to count all of them) messages per second. This doesnt help us in case of issues thrown by other plugins ^^'' 


![image](https://github.com/kangarko/ChatControl-Red/assets/62625225/437acb08-b41a-4d75-bc0b-1d4ea430ddf4)

**Comment by kangarko** [comment]
Is this from Velocity? I can't find this message anywhere: https://i.imgur.com/e2O6tYJ.png Did you use the latest official build from builtbybit?

**Comment by Lorias-Jak** [comment]
> Can you please try this build and tell me if it works? Works on my end but I noticed you used redis and I am unable to test on redis. Keep bungee-plugin-message-channel on false in velocity.toml.
> 
> [VelocityControl-1.0.6.zip](https://github.com/kangarko/ChatControl-Red/files/15458267/VelocityControl-1.0.6.zip)

I still use this velocity version here, as there was no update on bbb of VelocityControl ^^''

**Comment by kangarko** [comment]
Thanks, just found out i somehow forgot to push release, will do today, so sorry.
