### ISSUE TITLE
1.19.4: "&x" shows up in message when player uses HexCodes in chat

### ISSUE THREAD

**Issue by VyperzDev** [kangarko/ChatControl#2678]
### "/version ChatControlRed" - plugin version

10.26.2

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Type in chat" {HexCode}{Message}" #222222Hello  

the output: &x{ColoredMessage}

![image](https://github.com/kangarko/ChatControl-Red/assets/21981168/311a9257-ee7b-43ae-ac4a-3e6aa48b6e3e)

**Comment by kangarko** [comment]
Try on the default settings. I can't reproduce on 1.19.4. It's either your configuration or a third party plugin:

![a](https://i.imgur.com/gelqt4M.png)

**Comment by FaultyFunctions** [comment]
I know this is closed but for anyone else that stumbles upon this, for me it was the plugin `Interactive Chat` that was conflicting.
I fixed it by setting `TranslateAltColorCode: '&'` to `TranslateAltColorCode: ''` in the config.yml.

I believe Chat Control Red does everything that Interactive Chat can do so there really is no point in keeping Interactive Chat. Chat Control Red is way more flexible with chat replacement functionality like `[pos]` -> `x: 3 y: 5 z: 14`. Though Interactive Chat is easier to set them up.

**Comment by VyperzDev** [comment]
My issue was with CMI replacing the color codes in chat.

**Comment by kangarko** [comment]
> I know this is closed but for anyone else that stumbles upon this, for me it was the plugin `Interactive Chat` that was conflicting. I fixed it by setting `TranslateAltColorCode: '&'` to `TranslateAltColorCode: ''` in the config.yml.
> 
> I believe Chat Control Red does everything that Interactive Chat can do so there really is no point in keeping Interactive Chat. Chat Control Red is more way flexible with chat replacement functionality like `[pos]` -> `x: 3 y: 5 z: 14`. Though Interactive Chat is easier to set them up.

Just curious what was easier to setup in InteractiveChat than in ChatControl. Thanks!
