### ISSUE TITLE
Help with chat.txt and others

### ISSUE THREAD

**Issue by CraftingBro** [kangarko/ChatControl#268]
Hi, I made this issue because I'm unsure on how to remove any of the text without the error "cannot define operator when no rule is being created" in the chat.txt file. The other files work fine, but if I try to delete anything or a section in chat.txt it errors. Please help!
![image](https://user-images.githubusercontent.com/12457072/31387901-0aae93ee-adc4-11e7-92d3-56a22635421f.png)

**Comment by malonnnn** [comment]
Please paste the broken version of chat.txt

**Comment by kangarko** [comment]
Hey,

this error indicates that you have saved your file in the wrong encoding. You can find that issue as the last question in the [FAQ](https://github.com/kangarko/ChatControl/wiki#frequently-asked-questions) Wikipedia section. [Here](https://github.com/kangarko/ChatControl-pro/wiki/Use-Right-Encoding) is a more information on how to fix it.

@malonnnn if the user gets this error please navigate him to [this](https://github.com/kangarko/ChatControl-pro/wiki/Use-Right-Encoding) link. Thank you.
