### ISSUE TITLE
1.16.4 | Last plugin version terminated JSON

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#268]
Version: 1.16.4
Mysql/Bungee: false

I have tested my timed messages formats on 10.1.7 version and they worked well, but on 10.1.8 just removes all the JSON from them saying that this is for avoiding kick. Fix that pls

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5688503/debug.zip)

**Comment by OfT3N** [comment]
It also killed my MOTD

**Comment by OfT3N** [comment]
Which worked aswell

**Comment by Sikatsu** [comment]
I think this might also be why some of my groups no longer have a hover, in the previous version it still worked according to players.

**Comment by kangarko** [comment]
We had to implement this to avoid being kicked out. It did kick out players on some Minecraft versions, especially 1.8.8. When I have time I can pinpoint exactly what MC version does kick players and then only disable such long JSONs there. If you wish to help me, you can test MC 1.8.8 through 1.15.x on the previous version and let me know when the kicking starts to happen.

**Comment by Sikatsu** [comment]
Is there no documentation on this somewhere? I mean, with ChatControl 8 these kicks never occured for me on any minecraft version. I've been using ChatControl since 2015 ^^

**Comment by kangarko** [comment]
I am not sure, but we've expanded our feature set, making the JSON larger. It seems that, legacy MC versions can't handle such long JSON any longer. The Pro version has shorter JSON so it won't cross the 30k chars for it to kick.

**Comment by Sikatsu** [comment]
Hmm I see, hope it can be solved as some of the higher donation ranks seem to be affected and I show player stats in the hovers haha :)

**Comment by OfT3N** [comment]
> I am not sure, but we've expanded our feature set, making the JSON larger. It seems that, legacy MC versions can't handle such long JSON any longer. The Pro version has shorter JSON so it won't cross the 30k chars for it to kick.

Ive got REALLY little messages stopped working aswell, so i think that this must be fixed somehow :(

**Comment by kangarko** [comment]
Thanks, unlocked long JSONs for MC 1.9+ at your own risk.
