### ISSUE TITLE
1.18.2 Send Spy to Discord Channel?

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2680]
### Summary

Not sure if this is already possible but it would be handy to send the spy information into a discord channel for admins to be able to easily search.

The reason behind this is because I started using InteractiveChat & its discord addon that shows these items in Discord, and it would be great to catch people trying to scam people if its logged to discord.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Not be able to moderate this behavior

**Comment by kangarko** [comment]
Hmm I believe while this is technically not very feasible, you can use our rules system and use "then discord" operator instead.
