### ISSUE TITLE
Get server name using BungeeCord channel

### ISSUE THREAD

**Issue by SheerYin** [kangarko/ChatControl#2681]
### Summary

Setting the server.properties server-name manually for each server is always cumbersome, and using a BungeeCord plugin message, sent when a player joins and waiting for BungeeCord to return the ServerName seems like a better option?

```kotlin
fun getServerName(player: Player) {
        val byteArrayOutputStream = ByteArrayOutputStream()
        DataOutputStream(byteArrayOutputStream).use { output ->
            output.writeUTF("GetServer")
        }
        player.sendPluginMessage(this, pluginChannel, byteArrayOutputStream.toByteArray())
    }
```

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

More convenient, that's all

**Comment by kangarko** [comment]
I apology, the documentation was outdated. You can now just set this in bungee.yml of ChatControl. We need you to set this manually the way our protocol communication works to ensure it's always the right value.
