### ISSUE TITLE
1.20: Vulnerability?

### ISSUE THREAD

**Issue by joshwenke** [kangarko/ChatControl#2682]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hello, we are looking at using the forward command, but it has mentioned a potential vulnerability for several months. Can you share more details on this?

![image](https://github.com/kangarko/ChatControl-Red/assets/1607041/19beaeb8-2548-4f5d-a96a-9b6fd0a3e7a2)

**Comment by kangarko** [comment]
Details here: https://github.com/kangarko/ChatControl-Red/issues/2664

I believe it's safe now but I did not get around to make a custom hacked client to test this. We switched to broadcast on BungeeCord channel which afaik is ignored when not coming from server connection and we do an extra check to ignore players.
