### ISSUE TITLE
1.20.4: Hovering not working with ItsMyConfig variables

### ISSUE THREAD

**Issue by Manu585** [kangarko/ChatControl#2683]
### "/version ChatControlRed" - plugin version

10.25.10

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/15351260/debug.zip)

### Information about the issue/bug

So I am using a plugin called ItsMyConfig and it basically lets you set variables to use in other configs, and I think that when using it in /formats (or anywhere really) that it breaks the hovering.
![config](https://github.com/kangarko/ChatControl-Red/assets/72874613/ef946892-8324-4838-a212-354853c1601b)
![ingame](https://github.com/kangarko/ChatControl-Red/assets/72874613/ad698552-f68a-4592-add3-495eb3762dae)

**Comment by kangarko** [comment]
Unfortunately not possible with our system of displaying hover texts :/
