### ISSUE TITLE
1.20.1: Cannot access logs via in-game command starting on version 10.26.0 and higher

### ISSUE THREAD

**Issue by gre3x** [kangarko/ChatControl#2687]
### "/version ChatControlRed" - plugin version

10.26.3

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

There are no errors in console

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/15410504/debug.zip)

### Information about the issue/bug

Attempting to use any kind of `/chc log` command just says "Compiling database information..." and then a few seconds later says "No logs for were found"
![image](https://github.com/kangarko/ChatControl-Red/assets/123699236/7658e5d6-5850-4b3e-85a3-dd8ef196dd4a)

There are no errors in console (even with every debugging option enabled).

I manually checked the MySQL database, and I can see that there are logs in the database.

**NOTE:** This did not happen before v10.26.0 and when downgrading to v10.25.9, the logs command works fine and shows the latest logs. 

My guess is that this commit as part of v10.26.0 has caused some issue, but I am not sure what it is since there are no console logs: https://github.com/kangarko/ChatControl-Red-Src/commit/d4a7d847a01d2e0782548971c7fb2d40cfa1caea

**Comment by gre3x** [comment]
I honestly tried to compile ChatControlRed locally, but I kept running into issues lol so I'm making this issue so that you can hopefully take a look :)

**Comment by kangarko** [comment]
Hey, I cannot reproduce on the latest build:

![a](https://i.imgur.com/FA1mCsL.png)

I remember fixing this recently, not sure why it did not push to release. Will make a new release tonight, thanks.
