### ISSUE TITLE
1.20.4: [item] Resetting color code

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2688]
### "/version ChatControlRed" - plugin version

10.26.3

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug (2).zip](https://github.com/kangarko/ChatControl-Red/files/15413910/debug.2.zip)

### Information about the issue/bug

When using [item], if I have a color code appiled to my chat via the color menu or other means, [item] will remove the color code and default it to white. Not sure if this is a bug or a question as I am getting different results on 2 different test servers where one works and one doesn't, and it also doesn't work on my main server.
![image](https://github.com/kangarko/ChatControl-Red/assets/64336395/68c2a98a-fd8e-47ee-bf06-3da49b01c307)

**Comment by kangarko** [comment]
We do our best-effort matching to cache the previous color. Sometimes this does not work for certain format part configuration, unfortunately this is due to lacking support in the text component class. Try adding the color in the same format part where the [item] can be placed (that would be {message} to see if that helps, and work yourself from there

**Comment by HorusApl** [comment]
Doesn't seem like anything I do can change what CCR is cacheing for its color. I ran into the same issue when making my colorblind chat (which is now working). I do think this should be fixed at some point, as other similar plugins that link items to chat can do this with CCR installed.

**Comment by kangarko** [comment]
Sorry for delay, I was sick. Gonna be looking into this tomorrow

**Comment by HorusApl** [comment]
Just want to bump this to see if any fix is possible/planned.

**Comment by kangarko** [comment]
Sorry for delay. I found it broke on 1.20.x but still works on older versions. Unfortunately I don't have the amount of hours available to write our own parser and adventure does not have support for what we need.
