### ISSUE TITLE
Download / Beginner Creator

### ISSUE THREAD

**Issue by ZYMEEEE** [kangarko/ChatControl#2689]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Hi, I've recently bought VelocityControl. However I don't seem to find a way to download / acces the plugin. I haven't been in this business for a long time so perhaps this may be an incredibly stupid question, but. Where can I download the purchased plugin?

Sincerely, Me.

**Comment by kangarko** [comment]
Hey and thanks for purchasing!

Do you see a button to download it at https://builtbybit.com/resources/velocitycontrol-cross-network-chat.43226/ like this?

![2024-05-27-15 18-995](https://github.com/kangarko/ChatControl-Red/assets/1918426/a21f7f92-4f1b-46d2-96d0-f815743ac343)

If not, let me know your BBB username below - if you paid through tebex - or email me from purchase email address - if you paid through mineacademy - and I'll check that for you.
