### ISSUE TITLE
1.16.4 Bungeecord, Username Change issue.

### ISSUE THREAD

**Issue by PascalBrassat** [kangarko/ChatControl#269]
Plugin is currently on production server;

When a user changes their username and then connects to the server it notifies them that they are not stored in the database and leaves them in whatever channel they were last in. Unable to look into further as the user had left the server for the night.

**Comment by PascalBrassat** [comment]
One other issue we seem to be having is new players when joining arent placed in any channel and are forced to do  /channel join (XXX) in order to join, Permisisons I have setup for new players are as follows;

chatcontrol.channel.join.global.read
chatcontrol.channel.join.global.write
chatcontrol.channel..autojoin.global.write
chatcontrol.channel.autojoin.global.read
chatcontrol.channel.leave.global
chatcontrol.channel.send

EDIT:
Solution we have found to work,
Restart the server and then it works fine for them, unsure if you are able to fix this but would definitely be appreciated as we only restart every few days.

**Comment by Sikatsu** [comment]
Might wanna make a seperate issue for that, but I have a similar issue where players don't have write access in a channel until they relog.

**Comment by kangarko** [comment]
Thanks, should be fixed in the next release.

Also, I added so that we now "upgrade" players having saved a channel in read mode to write mode, if they have autojoin permissions for write mode.

**Comment by kangarko** [comment]
Also give players chatcontrol.channel.join permission.
