### ISSUE TITLE
Remove permissions from users with OP

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2690]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Good afternoon,

It's a pleasure to be able to write you my question, I'm testing the integration of chat groups and channels. The problem I have encountered is that since the user I am testing with has op, he receives everything I do or configure.

I was wondering if there is any way to ensure that the user who has op does not have all the permissions and only uses the permissions of the groups to which I give them.

I know that one answer could be that I remove the OP, but the fact that I have to constantly remove the OP makes the task difficult for me.

If this is the only option, there is no problem and I will continue like this.

Thank you very much for the plugin, I am delighted with it!

**Comment by Z3r0xh** [comment]
I want to add that we mostly use the user with OP privileges for tasks (specifically 2 users). These are shown in all formats when viewing them in chat, so perhaps an option to remove all permissions from the base OPs could be good.

**Comment by kangarko** [comment]
You need to use the Sender_Permission directive in your format parts and give them the permission from the directive as negative (i.e. a false value when using luckperms)
