### ISSUE TITLE
keep autojoin when disconnecting

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2691]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hi, I've been trying to configure this for a few hours and reading the wiki. I have deleted all permissions just to try to find a way to do it correctly.

I'll tell you, I'm trying to make each server have a defined autojoin (lobby, survival, skywars, etc.).

When I only have the autojoin and join permission it works fine, but I also want to give them permissions so that they can enter other channels and can read or write them in a general way (that's why they don't have a selected server, they apply to the entire network).

The problem is that when disconnecting, what I expect is that when I reconnect it maintains the autojoin channel first, but it continues to maintain the last one with which I disconnected in this way:

I'm probably giving the permissions wrong... I also set the Ignore_Autojoin_If_Left option to false but I still can't get it.

If you help me with this it will really help me.

All the best!

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/e0fe0b79-9d5d-4e7a-b3f8-db35aa25ea34)

**Comment by kangarko** [comment]
Hey,

Try setting Channels.Ignore_Autojoin_If_Left to false in settings.yml.  If you gave player permissions to automatically join a channel on join, and he decided to leave it, this option will remember his setting and not join him to channel next time he logs in.

**Comment by Z3r0xh** [comment]
> Hey,
> 
> Try setting Channels.Ignore_Autojoin_If_Left to false in settings.yml. If you gave player permissions to automatically join a channel on join, and he decided to leave it, this option will remember his setting and not join him to channel next time he logs in.

I understand that, but I don't quite understand the permissions structure so that you always connect to the same channel when you enter but also have access to move to others.

Could you help me see what the permissions would be like in a structure like this?

For example, we have the lobby as an autojoin channel, but I also want them to be able to connect and write in the survival and helpop channel, but when connecting they are always redirected to the lobby channel

I have the option of false as I mentioned
![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/818a2373-0000-4404-aa12-c918b32a163b)

but when entering the lobby, it keeps the channel in which I disconnected saved, without paying attention to the autojoin permission

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/eae7b246-111b-4338-b120-2d4348b004e3)
