### ISSUE TITLE
1.20.4: How to block special fonts?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2693]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello, some people bypass the swear & discrimination limit by using the special font:
![image](https://github.com/kangarko/ChatControl-Red/assets/18662086/5a6bcae3-57de-491b-a103-dbd6d59116e9)
Can I somehow block it? If so, how please?

I already have set this:
```
  # Evaluate the "match" operator in rules/ as well as other regexes in settings.yml (i.e. in Whitelist)
  # using the unicode flag? Enable this if your server is in a non-English language.
  # NB: When testing on regex101.com make sure you toggle "unicode" flag
  Unicode: false
  
```

But may it would be to completely block this type of custom fonts in the chat?

**Comment by kangarko** [comment]
You can uncomment this rule in rules/chat.rs

# Prevent special, unicode characters. Those are misused to bypass filters.
# Please keep in mind that non-English languages use them, so only uncomment this on English servers.
# [WARNING] You must set Rules.Unicode to true in settings.yml for this to work.
#match [^\u0000-\u007F]+
#then warn {prefix_error}Unicode characters are prohibited.
#then deny

If that does not work you need to adjust the "match" according to the correct regular expression. Reg. exprs. are a global language you can find a lot of stuff online or just ask chatgpt
