### ISSUE TITLE
Why is the player's channel saved?

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2694]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

I am giving the permissions to the default group as follows:
![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/86bee94c-6d20-461c-8197-3ce2a1f38464)

The thing that I have set to false is that if a player joins, the channels they had are not saved and they follow the autojoin ones, the thing is that all the time the same channel that the user saves is set and I can't do it.

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/6c7d70b2-79be-42ad-8323-b3179e7a5887)

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/b0d89686-a380-4cea-9923-885397eda8f8)

I would like to make lobby the default channel and helpop only join if they want

Can you give me a help? Thank you so much!

**Comment by Z3r0xh** [comment]
When you tell me how I can solve it, don't close the ticket in case I need to ask you something else.

Thank you so much!

**Comment by Z3r0xh** [comment]
I have been testing in 1.8 and 1.20.4, in 1.8 this option of returning to the autojoin channel if they have more channels that they can access does not work well.

In 1.20 it does work well. I have used the same permissions syntax for both

**Comment by kangarko** [comment]
Sorry for delay, I was sick. Gonna be investigating tomorrow.

**Comment by kangarko** [comment]
It is stored on mysql. Can you check the ChatControl table after the console message states that it autojoined the player whether the row with the player name got updated his data?

**Comment by kangarko** [comment]
Lets continue discussion here or on your other ticket. Feel free to ask your other question here or on the other ticket.

**Comment by Z3r0xh** [comment]
Okay, as soon as I'm home I'll connect to the databases,

Meanwhile I found that with this option in 1.8 they made it return them to their default home channels every time they logged in.

How should the Ignore_Autojoin_If_Left option be if I always want them to be in the autojoin channels when they enter?

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/ee60577b-9de9-4268-9d9c-168a8e609569)

**Comment by kangarko** [comment]
If you always want players to join to their autojoin, set Ignore_Autojoin_If_Left to false

**Comment by Z3r0xh** [comment]
> Está almacenado en mysql. ¿Puedes comprobar la tabla ChatControl después de que el mensaje de la consola indique que se unió automáticamente al jugador y si la fila con el nombre del jugador actualizó sus datos?

Sorry for the delay, I've been away from home and didn't have access to most of the things.

I just checked by checking the database.

And as you can see it stays in the helpop channel for some reason

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/c516c6cd-1c99-4bf7-99f2-96adbcd17b83)

**Comment by kangarko** [comment]
Just to make sure I am understanding it 100% - I see that the player typed /channel join but did not leave the channel. That is intended. ChatControl will save the joined channel and then rejoin the player upon his return. I am missing something?

**Comment by Z3r0xh** [comment]
> Solo para asegurarme de que lo entiendo al 100%, veo que el jugador escribió /channel join pero no abandonó el canal. Eso es lo que se pretende. ChatControl guardará el canal al que se unió y luego se volverá a unir al jugador cuando regrese. ¿Me falta algo?

The problem is not when joining, what I want is that when they enter the server they always join the same channel, in this case it is lobby and that they only have the autojoin for writing in the lobby and for reading in UnnameCraft.

The helpop can join, but once it disconnects it does not have to join again

**Comment by Z3r0xh** [comment]
> Just to make sure I am understanding it 100% - I see that the player typed /channel join but did not leave the channel. That is intended. ChatControl will save the joined channel and then rejoin the player upon his return. I am missing something?

The problem is not when joining, what I want is that when they enter the server they always join the same channel, in this case it is lobby and that they only have the autojoin for writing in the lobby and for reading in UnnameCraft.

The helpop can join, but once it disconnects it does not have to join again

**Comment by kangarko** [comment]
Sorry for the delay.

This is by feature design.

If the player leaves the autojoin channel and manually joins the second one, we will join him to the second channel once he relogs.

**Comment by Z3r0xh** [comment]
> Sorry for the delay.
> 
> This is by feature design.
> 
> If the player leaves the autojoin channel and manually joins the second one, we will join him to the second channel once he relogs.

But in principle, setting the ignore-auto-join-if-left option to false, wouldn't it have to make it join the autojoin channel whenever it reconnects?

**Comment by kangarko** [comment]
No because saved channels take priority over that option.

**Comment by Z3r0xh** [comment]
> No because saved channels take priority over that option.

In 1.20.6 it worked like this and the users are always reconnected to the same autojoin channel that they have in write, but in 1.8 this does not happen.

I'm trying to find a solution so that they always enter with autojoin

**Comment by kangarko** [comment]
No idea, we do not have separate logic for the two versions. Check your permissions setup
