### ISSUE TITLE
1.20.2: Ignore Issue

### ISSUE THREAD

**Issue by efekurbann** [kangarko/ChatControl#2695]
### "/version ChatControlRed" - plugin version

10.25.4

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Lets say, I gave my players permission to ignore each other. (/ignore command)
And I gave them the following permissions:
chatcontrol.command.ignore
chatcontrol.command.ignore.list

The issue is that, they can force other players to ignore each other by simply using `/ignore <player> <otherPlayer>`
Yes. I am 100% sure they do not have `chatcontrol.command.ignore.others` permission.

**Comment by kangarko** [comment]
Sorry for delay, I was sick. Gonna be looking into this tomorrow.

**Comment by kangarko** [comment]
They must have the ignore.others permission because it is literally hardcoded in the code:

![b](https://i.imgur.com/ZSvyJYq.png)

![a](https://i.imgur.com/oh3gE2o.png)

Do a verbose/debug with luckperms or your other permission plugin. or try giving them the ignore.others on false explicitely.
