### ISSUE TITLE
deleting messages works badly in 1.8

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2696]
### "/version ChatControlRed" - plugin version

10.26.4

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

https://ufile.io/9ka42c66

### Information about the issue/bug

When you are on a 1.8 server and you delete a message, several are deleted at the same time, as if you deleted 10 lines at once.

It then becomes impossible to delete a single message from a player.

**Comment by kangarko** [comment]
Unfortunately ViaVersion does not work 100% with protocollib which we rely on to get the chat context, sorry sadly nothing I can do especially for that 1.8.8 version
