### ISSUE TITLE
autojoin not working in 1.8

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2697]
### "/version ChatControlRed" - plugin version

10.26.4

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

https://ufile.io/9ka42c66

### Information about the issue/bug

The problem is with the autojoin function in 1.8, it is not respected.

When I have the Ignore_Autojoin_If_Left option set to false, this is not respected and continues saving the channels with which the user disconnected:

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/9bc1d415-e0f1-4810-b653-4db6ab53dfe8)

From what I see, this has only happened to me in 1.8, since I have followed the same permissions structure in 1.20.4 and it works fine, I understand that it is an error.

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/f116e42d-8d0f-4f10-a1ef-330291eb2f0a)

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/dcfa1c61-7a35-406d-870b-a6e52412b6e9)

The thing is that when users disconnect with other selected channels, they do not return to the autojoin write channel.

I have tried leaving only the autojoin of the lobby channel in writing mode and it doesn't work either.

**Comment by Z3r0xh** [comment]
While testing, I realize that this also affects the other spigots of the network, causing their autojoins to not work.

**Comment by kangarko** [comment]
Sorry for delay, I was sick. Gonna be looking into this tomorrow

**Comment by kangarko** [comment]
So I read your ticket, and I am sorry if I am misunderstanding, but you have the "Ignore_Autojoin_If_Left" on false and then it supposed not to return players back to the autojoin write channel. You need to enable that key for players to autojoin back.

**Comment by kangarko** [comment]
I can also see that the "helpop" channel is not in your autojoin permissions. So from your log chatcontrol returned the channel  because it was stored in the mysql database.

**Comment by kangarko** [comment]
Let me know if you have any further clarifications below.
