### ISSUE TITLE
1.20.4 Discord Formatting setup

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2698]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Is there any better way of formatting how messages appear when chatting from Discord to Minecraft? I can change Minecraft to Discord easy enough without problems, but it seems the reverse is overly complex or I am not understanding something with it. https://mclo.gs/qKgLRBP Is there any better way of doing this? It's quite messy and doing a ton of lookups.

**Comment by kangarko** [comment]
Yes you can just type the discord>mc chat format directly using the Format_Discord key in your channels list:

![a](https://i.imgur.com/W7EDVnQ.png)

**Comment by HorusApl** [comment]
The Format_Discord option only applies when typing from Minecraft to Discord, which is the easy part to configure. I have yet to find a way to make the Discord to Minecraft option use any other format then my standard chat.yml without using that crazy implementation I listed above.

**Comment by kangarko** [comment]
I'll make the Format_Discord key for channels be used for both Discord>Minecraft and Minecraft>Discord messages.

**Comment by HorusApl** [comment]
Getting this error: https://mclo.gs/wFI4did on some of my pre-setup rules due to the new "blocked command" thing added in one of the recent updates. I see nowhere to change what commands are or are not blocked, and I have many rules that rely on /lp commands.

**Comment by HorusApl** [comment]
As well, I think it may be best to have the Format_Discord be 2 separate items. Currently, the image below is what is shown for users who haven't linked their accounts with DiscordSRV. If I edit any part of the Format_Discord to allow one to have a symbol/some other change, it will of course take place on both parts. I have found a solution for my specific use case: https://mclo.gs/L0EL6is

But I imagine this would not be suitable for everyone. 

Also, the Format_Discord seems to not work via linking to a format file like other Format_* types do.
![image](https://github.com/kangarko/ChatControl-Red/assets/64336395/7ad374c2-6249-4620-b8bc-b3e94d843dc5)

**Comment by kangarko** [comment]
> Getting this error: https://mclo.gs/wFI4did on some of my pre-setup rules due to the new "blocked command" thing added in one of the recent updates. I see nowhere to change what commands are or are not blocked, and I have many rules that rely on /lp commands.

Sorry about that, I will relax the blocker

**Comment by kangarko** [comment]
> As well, I think it may be best to have the Format_Discord be 2 separate items. Currently, the image below is what is shown for users who haven't linked their accounts with DiscordSRV. If I edit any part of the Format_Discord to allow one to have a symbol/some other change, it will of course take place on both parts. I have found a solution for my specific use case: https://mclo.gs/L0EL6is
> 
> But I imagine this would not be suitable for everyone.
> 
> Also, the Format_Discord seems to not work via linking to a format file like other Format_* types do. ![image](https://private-user-images.githubusercontent.com/64336395/337568786-7ad374c2-6249-4620-b8bc-b3e94d843dc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTkyNDIsIm5iZiI6MTcxNzc1ODk0MiwicGF0aCI6Ii82NDMzNjM5NS8zMzc1Njg3ODYtN2FkMzc0YzItNjI0OS00NjIwLWI4YmMtYjNlOTRkODQzZGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDExMTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZWFhNjMxN2Y1ZTJkMTUwYWUzYTZiMjczN2NiOGJkYzNkMjU3NTlhZDlhMjkzZDUyOWI4NzJkNDVlOGJiYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yWB1fghUyxe8CJpisbVjPZwcMoSWDx6ZCaMtC9s5Ih0)

Thanks, I'll make that consideration, however right now there is no ETA
