### ISSUE TITLE
1.16.4 | Failed to parse JSON for Server Name

### ISSUE THREAD

**Issue by Pukejoy** [kangarko/ChatControl#27]
OS: Windows 10 Pro
If you haven't set a server name in server.properties you get errors like this one - https://paste.soleria.eu/qugimalupo.bash
I don't know if it's an error, but I think it's a little annoying...

**Comment by ElBananaa** [comment]
> OS: Windows 10 Pro
> If you haven't set a server name in server.properties you get errors like this one - https://paste.soleria.eu/qugimalupo.bash
> I don't know if it's an error, but I think it's a little annoying...

In your server.properties, look for `server-name=Undefined - see mineacademy.org/server-properties to configure` and replace it with a name with no spaces.
E.g. `server-name=TestServer`

**Comment by Pukejoy** [comment]
Yes, I did it, but I think is kind of annoying to give you an error by default.

**Comment by broken1arrow** [comment]
Yes and the wiki not help soo much and error not stop it keep going. I think a new installed plugin shall not give lots of errors. 

suggestion i like from Bananaa on DC
That's a pretty good thing, I mean, it makes more sense to define it there, but it's a bit confusing tho, they should change it to server-name=Undefined by default, and the plugin would detect it. If it's undefined, it would send a message in the console and to operators that says "Please change your server name in the server.properties (Don't use spaces)"

**Comment by Pukejoy** [comment]
Agreed

**Comment by kangarko** [comment]
Thank you, I will fix that. Also made the error throw up in a clearer way so you know what went wrong.
