### ISSUE TITLE
Spam Kick

### ISSUE THREAD

**Issue by xJus** [kangarko/ChatControl#27]
Disable Spam Kick

Allow customization of:
>>
>>
>> Please slow down chat blah blah
>>
>>

thx

**Comment by kangarko** [comment]
>Disable Spam Kick
Do you mean "disconnected.spam" message?

>Allow customization of
Possible via localization. Read spigot page on how to do it.

**Comment by xJus** [comment]
Yes

**Comment by kangarko** [comment]
At the moment it is not possible. Since this is simple to implement, I'll take a look at it.

**Comment by kangarko** [comment]
Implemented to both versions.
