### ISSUE TITLE
1.16.4: Suggestion about Channels

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl#270]
When providing channel alternatives to things like adminchat there are alot of possibilities. I do however want to create /ac toggle command or something using aliases. Therefore it would be handy if There was a /ch switch channel1 channel2 command wich swhitches between the two. So if you're in channel 2, you join channel1 and otherwise.

**Comment by JessePesse123** [comment]
Other Suggestion: being able to specify a mode in `require channel`

**Comment by kangarko** [comment]
Thank you for your suggestion! Leaving open for implementation.

**Comment by kangarko** [comment]
Added require channel mode option.
