### ISSUE TITLE
ChatControl and ProtocolLib

### ISSUE THREAD

**Issue by chillslash** [kangarko/ChatControl#270]
I got an error when I added ProtocolLib
I have the latest update of both plugins
Minecraft 1.8
Java 8

https://pastebin.com/PVbGwG1K

**Comment by kangarko** [comment]
Hello, I am sorry for a late reply. I have a strong believe that this is caused by an incorrect version of ProtocolLib - you need to be using an older ProtocolLib for your MC version.
