### ISSUE TITLE
1.20.x: Send MOTD Async || Player heads not displaying right

### ISSUE THREAD

**Issue by Manu585** [kangarko/ChatControl#2700]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

No

### Question

It states in the console, that I should enable Async running, but I don't know how to.
![image](https://github.com/kangarko/ChatControl-Red/assets/72874613/cf71d3d3-be5f-4ba7-bafb-78b6c8342383)

And the player head is not displaying the right way.
![image](https://github.com/kangarko/ChatControl-Red/assets/72874613/4c5d1c0a-66fc-403a-86b3-21066f5a5484)

motd.yml:
`
New_Line_Per_Part: false
Parts:
  
  everything:
    Message:
    - '&8*--------------------------------------------------*'
    - '&fWelcome back &6{player} &fenjoy your time here!'
    - ''
    - '&6Version: &f{server_version}'
    - ''
    - '&6&lInfo:'
    - '&7- &fServer still undergoing development!'
    - ''
    - '&6Changelog:'
    - '&7- &fNerfed &eEarthKick'
    - ''
    - '&8*--------------------------------------------------*'
    Image_Head: '{player}'
`

**Comment by kangarko** [comment]
The long ---- lines never worked properly with the image, remove them.

We disabled async option due to some other problems, it's fine it's just 190ms should not cause any real noticeable lag.
