### ISSUE TITLE
1.20.1: What Advancement ID does CCH use?

### ISSUE THREAD

**Issue by FaultyFunctions** [kangarko/ChatControl#2701]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello! I am using a client side fabric mod called [Advancement Plaques](https://modrinth.com/resourcepack/embellished-stone-advancements-plaques). Basically it makes toasts into a bigger deal with sound effects, however I still want to use PM toasts from Chat Control Red but I don't want it to activate the Advancement Plaques mod and make a huge noise and deal every PM.

The mod gives 3 options for adding an advancement to its blacklist. Here is this config file:
![image](https://github.com/kangarko/ChatControl-Red/assets/6508045/b57aee19-2225-4dae-b280-bcfae1e5b68c)

Would I be able to add anything to that blacklist to ignore advancement toasts made by Chat Control Red? Let me know, thanks!

**Comment by kangarko** [comment]
We use bukkit's toast system whereby we put in the bukkit's Material class into it. See what we are doing here, I unfortunately wont be able to assist further: https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/remain/Remain.java#L2306
