### ISSUE TITLE
Need help with a console message I'm getting

### ISSUE THREAD

**Issue by Thefonzie** [kangarko/ChatControl#2702]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

[20:50:47 INFO]: [ChatControlRed 10.26.2] AdventureChatListener listening to AsyncChatEvent at HIGH priority took 187.63 ms

If there are a lot of people chatting at the same time the server tends to start lagging quite a bit.

**Comment by kangarko** [comment]
Hey, please see this guide on performance optimization and try to trim your formats and/or variables: https://github.com/kangarko/ChatControl-Red/wiki/Performance
