### ISSUE TITLE
Do not show channels on the console

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2704]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hi,

I have a question,

I currently have 6 channels connected to the network, 3 of them are 2 modes and the lobby.

The thing is that when I type anything in one of the modes, that message appears in the console of another mode. Is there any way for it not to appear, for example, if I speak in survival mode it appears in the lobby console?

Thank you very much for your attention!

**Comment by kangarko** [comment]
Set Format_Console to "none" in channels list in settings.yml for these channels.

**Comment by Z3r0xh** [comment]
> Set Format_Console to "none" in channels list in settings.yml for these channels.

I have it set to "none", but they continue to be sent to the other consoles.

My question is more about the echo of the messages from each mode not reaching the other modes via console.

For example... I write in the survivla mode and if there is someone in the lobby he does not read it because it is on another channel, but it does appear on the console.

Then I have also tried adding the cancel_event but it doesn't work either and they continue to appear in the other consoles.

**Comment by kangarko** [comment]
Are you saying the other consoles print an empty message or they print the full message?

**Comment by Z3r0xh** [comment]
> Are you saying the other consoles print an empty message or they print the full message?

I have set a format for each channel as shown on the console, even everything is fine.

The problem is that the different consoles show the message. I'll add a couple of images.

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/8dca37bd-ebc3-4146-a79b-3f549e2f3993)

For example, I speak in the "survival" channel and what I send in it is also shown in the "lobby", I understand that it is because they are connected to each other (bungee = true).

So I wonder if I can deny the message that comes from a channel such as the lobby from being displayed in the survival console?

This is the format that I follow within survival, ensuring that the other channels do not show the messages that come from other modalities, but it seems that they continue to be shown

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/dfb1b90b-9639-4ce9-9e59-bee30c202719)

lobby format:
![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/a6041b9b-8b2d-46b8-8b9b-01475ee8741d)

In the end what I am trying to do is that only the survival channel is shown in the survival console and the same with the other chat channels of each modality

**Comment by kangarko** [comment]
That is not supported by design since you have the Bungee key on true. You need to disconnect the channel for it not to pop in the console.

**Comment by Z3r0xh** [comment]
> That is not supported by design since you have the Bungee key on true. You need to disconnect the channel for it not to pop in the console.

But if you perform this action, they are not sent to the other modalities, right?

Couldn't you create some dont_send_to_anothers_consoles style option?

**Comment by kangarko** [comment]
No sorry this is out of alignment of the core values of the plugin

**Comment by Z3r0xh** [comment]
> No sorry this is out of alignment of the core values of the plugin

okay, no problem. The channels are mixed, but with some plugin I can eliminate them from what is seen in the console
