### ISSUE TITLE
ChatControl Red: Adding Player Prefix To Death Messages

### ISSUE THREAD

**Issue by mrericwong** [kangarko/ChatControl#2705]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hi,

I have just purchased the "Witty Death Message Pack," I would like to add player prefix in front of their name, is it possible?

Thanks

**Comment by kangarko** [comment]
Sure, you can use the {player_prefix} variable, does it work? Let me know below.

**Comment by mrericwong** [comment]
It worked, thanks!
