### ISSUE TITLE
Witty Death Messages: Missing Death Message For Falling Onto Stalagmites

### ISSUE THREAD

**Issue by mrericwong** [kangarko/ChatControl#2706]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello,

I found out the there isn't a message for falling onto a pointed dripstone (stalagmites). Currently, the message would be "xxx 7tried to hug a cactus" or something like that.

Eric

**Comment by kangarko** [comment]
Thanks, if you have created this feel free to send it over otherwise I'll look into it :)

**Comment by mrericwong** [comment]
I'm afraid I'm not good enough to create funny death messages, please push an update to the resources once the bug is fixed. Thanks!
