### ISSUE TITLE
Is CHC compatible with Folia please?

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/ChatControl#2707]
### "/version ChatControlRed" - plugin version

10.26.4

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/2fde83d9e316469883636440250e9271

### Information about the issue/bug

Hello!

I tried to run the latest version of CHC on version 1.20.6 on the latest version of Folia, but I received this error. 

I read somewhere that CHC was compatible. Am I mistaken? Thanks!

**Comment by CtrlAiDel** [comment]
[03:59:19 INFO]: !-----------------------------------------------------!
[03:59:19 INFO]:  Error loading ChatControlRed v10.26.4, plugin is disabled!
[03:59:19 INFO]:  Running on 1.20.6-R0.1-SNAPSHOT & Java 21.0.1
[03:59:19 INFO]: !-----------------------------------------------------!
[03:59:19 INFO]:  Unable to setup reflection!
[03:59:19 INFO]:  Your server is either too old or
[03:59:19 INFO]:  the plugin broke on the new version :(
[03:59:19 INFO]:  Error: Unable to get the error message, search above.
[03:59:19 INFO]: !-----------------------------------------------------!

**Comment by kangarko** [comment]
I compiled folia using https://github.com/Slackadays/FoliaToGo and it worked fine.

Please post me the full startup log below if still experiencing issues.

**Comment by CtrlAiDel** [comment]
Have you tried with folia 1.20.4 or folia 1.20.6? Cause at the moment I had tried with 1.20.6 and in there (https://nightly.link/Slackadays/FoliaToGo/workflows/folia/main/FoliaToGo)  I cannot find folia 1.20.6.

So you might have tried on 1.20.4 and I did so on 1.20.6?

@kangarko  ( i tagged you because i don't know if you'll see this post since the issue is closed )

**Comment by kangarko** [comment]
Sorry I dont have time to compile, can you ZIP me the folia jar and upload here? I'll remove it after

**Comment by CtrlAiDel** [comment]
I couldn't find any other method... i tried zip zip with different name in here without success.. tried to dm you on discord ... 

Anyway :) here's a google drive link with the .zip
https://drive.google.com/file/d/1FLQuiZ_UrcgmeFYfYfcgC2fbUha3dwCs/view?usp=sharing

Thank you for your time

**Comment by kangarko** [comment]
Thanks! I closed office for the day, so I will be looking over Sunday or Monday morning thank you :)

**Comment by BearLeonLight** [comment]
[error.log](https://github.com/user-attachments/files/15764192/error.log)

**Comment by kangarko** [comment]
Sorry for the misunderstanding. I meant please send Folia 1.20.6. I dont have time to compile it right now and the mirror only caches 1.20.4

**Comment by CtrlAiDel** [comment]
Folia 1.20.6 is what i sent via google drive

**Comment by kangarko** [comment]
Are you sure? The link https://drive.google.com/file/d/1FLQuiZ_UrcgmeFYfYfcgC2fbUha3dwCs/view contains a 2mb chatcontrol jar file

![a](https://i.imgur.com/sltola1.png)

**Comment by CtrlAiDel** [comment]
Lol my mistake i am gonna check this tonight or today if i have the time

**Comment by CtrlAiDel** [comment]
This should work please confirm

https://drive.google.com/file/d/16PIT_IQZAcw4-Fqb_RVHSkB0z123NbLs/view?usp=drivesdk

Thank you have a nice day

**Comment by CtrlAiDel** [comment]
Hi can I please have a follow whenever you can @kangarko

**Comment by kangarko** [comment]
I am out tomorrow but I will be sitting down on Monday. I requested access to your link and removed it.
