### ISSUE TITLE
Paper, 1.20.4: Where do I purchase this plugin?

### ISSUE THREAD

**Issue by CodingWithAnxiety** [kangarko/ChatControl#2708]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Hello, devs & maintainers!

I'm a server owner interested in using this plugin. However, I'm confused on where to buy it-

I was lead to [here](https://mineacademy.org/chatcontrol), however it seems... Odd? 
I also saw I can buy from [here](https://builtbybit.com/resources/chatcontrol-red-format-filter-chat.18217/), where the velocity plugin is *also* hosted. 

I want to know where the preferred place to purchase is.

Thank you!

**Comment by CtrlAiDel** [comment]
Both places are legit... I could not recommand you which one to use since I have forgoten, but I do have an account on both website .... and I do download the file from the second website. But I think you HAVE to go through their official website (maybe)

Good luck, this plugin is something else to configure ;) ! ^^

**Comment by CodingWithAnxiety** [comment]
Something else to configure? Can you give me some more detes on that?

**Comment by kangarko** [comment]
We sell on MineAcademy (my website) or BuiltByBit.

But we only distribute on BuiltByBit which means if you purchase through MineAcademy you will get access on BuiltByBit after your purchase (automatically).

I recommend you purchase through MineAcademy so we can contact you in case something happens with your/our BuiltByBit account (i.e. ban) you continue having access.

**Comment by CodingWithAnxiety** [comment]
Ah, I already bought from BuiltByBit. If I have any issues, will a copy of my license key / receipt still work as "proof of purchase?"

**Comment by kangarko** [comment]
Yes of course! Thank you!
