### ISSUE TITLE
1.20.6: Variables: player#getItemInHand not working

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [kangarko/ChatControl#2709]
### "/version ChatControlRed" - plugin version

10.27.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/9ec904a0de114b279cfa984af225cfe8

### Information about the issue/bug

When you try to use [item] error appears and vanilla chat message is sent instead of CHC

**Comment by kangarko** [comment]
Thanks, will be fixed in the next upgrade.
