### ISSUE TITLE
I don't know what's wrong with my chat control plugin :'(

### ISSUE THREAD

**Issue by ma241075** [kangarko/ChatControl#271]
I'm updated to the latest version as of today, I've replaced the .jar file constantly and I've tried searching everywhere for assistance. My chat Control plugin gives off numerous lines of errors and compatibility issue claims. It spams my console on every reload, restart or when I execute a command associated with the server. Sometimes it generates errors even when I don't do anything, while I'm AFK. Please help me. Take a look at this hastebin I've pasted for you :/

https://hastebin.com/zoyakacunu.vbs

**Comment by kangarko** [comment]
Hello,

I am sorry you have issues. I have looked at them and the errors are coming from ProtocolLib. Please update that plugin to the correct version for your Minecraft server.

Blessings,

kangarko

**Comment by ma241075** [comment]
Kangarko, how do I know what version of ProtocolLib to use? I looked everywhere for a guide, please help me :(

**Comment by ma241075** [comment]
ProtocolLib is meant to support all versions of Minecraft no matter the plugin version :/

**Comment by kangarko** [comment]
Try the following versions:
* https://www.spigotmc.org/resources/protocollib.1997/update?update=168097, or (use only one at the time)
* http://ci.dmulloy2.net/job/ProtocolLib/373/
