### ISSUE TITLE
[Issue] DiscordSRV Placeholders Not Working

### ISSUE THREAD

**Issue by rumplepusscat** [kangarko/ChatControl#271]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

=================

Hi there,

As mentioned on Discord, I'm having some issues with certain DiscordSRV placeholders, namely `%discordsrv_user_top_role_color_code%` for processing text from Discord -> MC. The text simply displays the placeholder itself, with using both `{}` and `%%` variants.

Configs/logs etc. available if this is useful!

Many thanks in advance,

Rumple

**Comment by kangarko** [comment]
Unfortunately these are unsupported on ChatControl Red. I will take this as a suggestion for the future.

**Comment by rumplepusscat** [comment]
That's a shame, but understandable if it is the case.

Is this the same for all/some DiscordSRV placeholders?

Thanks,

Rumple

**Comment by kangarko** [comment]
i will check this out for you. If DiscordSRV has a method for replacing variables we will call it. Will return back shortly.

**Comment by kangarko** [comment]
Unfortunately it doesn't. Maybe I can return for this in the future.
