### ISSUE TITLE
1.20.4: Allowing viewing swears for some players?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2711]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Hello, is it possible to allow this part:
```
group swear

ignore perm chatcontrol.bypass.swear

then replace @prolong *
```

to be executed only if the VIEWER has some specific permission? Like that he players can decide on their own (they could set it in the custom GUI or so), if they want to view the unreplaced or replaced message? So this way we could allow seeing swearings for some players

**Comment by kangarko** [comment]
Sorry, technically impossible.

**Comment by kangarko** [comment]
And would drain the plugins performance so much having to run javascripts for each player separatedly

**Comment by bobhenl** [comment]
@kangarko, but there exists some relational placeholders; wouldn't it have a similar effect? I use them in the chat to show the prefix depending if player has or doesn't have the resource pack (he sees the custom rank icon or normal prefix), I guess it could work similarly?

**Comment by kangarko** [comment]
This is handled at the component level, not at the rule level. Completely different technically unfortunately
