### ISSUE TITLE
1.20.4: Chat does not appear in console

### ISSUE THREAD

**Issue by AntZaro** [kangarko/ChatControl#2712]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

I'm technically using velocity and I have it set up with chatcontrol to do join/quit/switch messages, but this question concerns the server chatcontrolred is on. 

I'm not using chatcontolred to format my chat or do channels or pms or anything. I'm using EssentialsXChat. We have pretty simple formatting that is just a default format and then a few ranks that have color chat. The issue I'm having is that when ChatControlRed is installed, I do not see any in-game chat in console. Nothing people are saying gets logged. 

When I delete CCR from the plugins folder, chat appears in console and the logs as normal. So I know this plugin is causing the problem. I've been scouring the CCR config to see what setting could be causing this, but I can't for the life of me find anything. I don't understand why this would be happening given I'm not using CCR for chat formatting, only for things like death messages, swear filters, etc. Please tell me I'm not crazy and there is a setting for this!

**Comment by kangarko** [comment]
Please send /chc debug since the console is shown for me when I disabled channels.

**Comment by AntZaro** [comment]
Yes, here is the zip file from running the command. 
[debug.zip](https://github.com/user-attachments/files/15798071/debug.zip)

**Comment by kangarko** [comment]
So sorry for the delay. I will fix that. The cause was that we remove the [Not Secure] spam and replace with our own console log but not when channels are off. I will just log the console manually in the chat event if channels are disabled.
