### ISSUE TITLE
error with pm

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2713]
### "/version ChatControlRed" - plugin version

10.27.1

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

https://ufile.io/qf6hge6s

### Information about the issue/bug

Even if you check the pm formats in the folders folder, they appear vanilla
![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/6a63af9d-9b8e-414d-acd9-50258b42c539)
![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/45934a11-c94b-45b0-9583-e0b3b671b573)

**Comment by kangarko** [comment]
I downloaded your /chc debug and opened the last error log, but it seems there is another problem when the plugin starts with WorldGuard. You need to check your entire startup log and fix all other plugin issues first.

**Comment by Z3r0xh** [comment]
> I downloaded your /chc debug and opened the last error log, but it seems there is another problem when the plugin starts with WorldGuard. You need to check your entire startup log and fix all other plugin issues first.

Right now in the log file I don't have any warnings, the worldguard problem does not appear (it was a problem when starting wg with fawe).

Currently I don't have any errors, but the /pm is still displayed in vanilla format

**Comment by Z3r0xh** [comment]
> I downloaded your /chc debug and opened the last error log, but it seems there is another problem when the plugin starts with WorldGuard. You need to check your entire startup log and fix all other plugin issues first.

okay, I found a way to fix it through /chc reload

Anyway, I think it's a problem when the plugin starts next to that module.

**Comment by kangarko** [comment]
Unfortunately it looks like a plugin incompatibility then

**Comment by Z3r0xh** [comment]
> Unfortunately it looks like a plugin incompatibility then

I tried only with chatcontrolred, protocollib and essentials and still had the same problem

**Comment by kangarko** [comment]
Provide me the full startup log with these three plugins then please. And make sure essentials is not overtaking our /pm or /tell command.

**Comment by Z3r0xh** [comment]
> Provide me the full startup log with these three plugins then please. And make sure essentials is not overtaking our /pm or /tell command.

https://mclo.gs/uM50p9A

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/b43248a1-616a-49e8-9c1d-10d70cc88872)

**Comment by kangarko** [comment]
Does it work automatically when you only have ChatControl plugin installed?

**Comment by Z3r0xh** [comment]
> Does it work automatically when you only have ChatControl plugin installed?

If I only have chatcontrolred, yes, it is a problem with essential. I don't understand it either because within the list I have all the essentials commands related to the msg disabled

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/d03345c8-90de-47c8-a79c-2725fa303894)

**Comment by kangarko** [comment]
Essentials is taking over the command. Open its plugin.yml and remove the command from "command" section.
