### ISSUE TITLE
Paper 1.20.4 |:| Specific wiki page on color formatting?

### ISSUE THREAD

**Issue by CodingWithAnxiety** [kangarko/ChatControl#2714]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Hi!

I'm interested in finding out how I can use color (gradients, etc...) in formatting and what standard we use? I know CCRed can be formatted with hex, but I can't find any specific guides on how the coloring is handled- any guidance to the correct part of the wiki would be greatly appreciated!

**Comment by CodingWithAnxiety** [comment]
```
Parts:
  owner-tag:
    Message: '[Owner] '
    Gradient: #fab2ff - #123456
```

When I run the server with this, however, the gradient section is removed from the config and nothing happens- however, using;

    Gradient: RED - BLUE

Works fine. Any advice?

**Comment by CodingWithAnxiety** [comment]
Figured that one out- but what would I do if I want to make something specifically a gradient? Instead of the entire owner tag, what about just the owner part of it?

**Comment by kangarko** [comment]
Put '' around it like this: '#000000 - #000000'. It works on my end:

![a](https://i.imgur.com/cIg91IX.png)
