### ISSUE TITLE
1.20.4: Issue Doesnt work with Component 

### ISSUE THREAD

**Issue by Maxlego08** [kangarko/ChatControl#2716]
### "/version ChatControlRed" - plugin version

   10.27.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

The plugin is not compatible with the Kyori Adventure Component, it will not take into account the format and colors of the text correctly.

```java
    @EventHandler(priority = EventPriority.LOWEST)
    public void onChat(AsyncChatEvent event) {

        Player player = event.getPlayer();
        String message = PlainTextComponentSerializer.plainText().serialize(event.originalMessage());

        TagResolver.Builder builder = TagResolver.builder();
        for (ChatDisplay chatDisplay : this.chatDisplays) {
            message = chatDisplay.display(this.adventureComponent, builder, player, message);
        }

        event.message(adventureComponent.getComponent(player, message, builder.build()));
    }
```

![image](https://github.com/kangarko/ChatControl-Red/assets/32517160/2e340f2c-804d-4b2a-94ef-d379f53e1c24)

**Comment by kangarko** [comment]
Unfortunately isnt. We have a wide range of compatibility down to 1.7.10 and I have no time nor resources to add more complexities for the latest thing.

**Comment by Maxlego08** [comment]
> Unfortunately isnt. We have a wide range of compatibility down to 1.7.10 and I have no time nor resources to add more complexities for the latest thing.

Still, it’s a shame to continue to support a version as old as 1.7.10, it represents a few dozen servers in the world, while the majority of servers are in the latest version of minecraft. I advise you to change this quickly.

**Comment by WarnDa** [comment]
So we can't even do custom integration using adventure which is now used almost everywhere even by paper

**Comment by kangarko** [comment]
You can do custom integration with our SimpleComponent class or listen to ChatChannelEvent

**Comment by kangarko** [comment]
For context, even Adventure supports 1.7.10+. The issue is we have developed the entire core off of our own framework since Adventure did not exist back then. To rewrite the core requires more time than I have at my disposal unfortunately.
