### ISSUE TITLE
1.20.6: [item] chat message doesnt work

### ISSUE THREAD

**Issue by QuestalNetwork** [kangarko/ChatControl#2717]
### "/version ChatControlRed" - plugin version

10.27.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/0e4a266d09cb4dad872e2557e71c0a42

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/user-attachments/files/15764280/debug.zip)

### Information about the issue/bug

If someone types [item] in chat it won't show the item name. It buggs and it show a vanilla minecraft chat with the message [item]

**Comment by kangarko** [comment]
Thanks, will be patched in the next version.
