### ISSUE TITLE
Per-user toggle for private message sound

### ISSUE THREAD

**Issue by Jyguy** [kangarko/ChatControl#2718]
### Summary

Some players prefer a sound played when a private message is received, while others do not want it. A command or another way to toggle the notification sound per-user would resolve this issue.

Alternatively, adding an API event for when a private message is _successfully_ sent (currently, `PrePrivateMessageEvent` is called before any checks are made) would allow developers to hook into the API and add it themselves.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Players who do not want the private message receive sound would not be able to toggle it off for themselves.

**Comment by kangarko** [comment]
I will adjust the PrePrivateMessageEvent such that it will contain the setSound() method so you can disable it for players who do not want it using API.
