### ISSUE TITLE
Character duplication disabling

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [kangarko/ChatControl#272]
Hi! Is it possible to change the amount of letters to be flagged as duplication? Or disable that? Or disable that for player usernames? Or disable that by permission? I couldn't find info about this on wiki :/

**Comment by kangarko** [comment]
Hey, see Anti_Spam.Chat section in settings.yml, and to disable that, set the marked option below to 0:

![a](https://i.imgur.com/Sc27coq.png)

**Comment by Kryniowesegryderiusz** [comment]
Okey, but I'm talking about letters similatity, not whole message. (Ex. Heeeeeeey) Cuz it takes affect to nicknames on my server, when somebody has three letters in row in nick.

**Comment by Kryniowesegryderiusz** [comment]
Also is it not possible to change language of message, which occures (Your message contains too many duplicated characters.), so I have to do it by packets section XD

**Comment by kangarko** [comment]
Hey, yes, you can create a rule for cutting heeeeey to hey and similar. Open rules/chat.txt and uncomment the following:

```
# Example of limiting repeating characters to four repeats maximum.
#match (.)(?=([a-z])\1{3})
#then replace
```

You can insert `ignore usernames `operator there to prevent it being applied on usernames, and change the {3} to another number for more/less strict.

Yes, create localization/ folder in ChatControl folder and messages_en.yml file (empty file) inside of that folder. Restart the server and it will be filled with messages.

**Comment by Kryniowesegryderiusz** [comment]
I know that i can create that rule, but i asked how can I disable characters similarity check in your config.
And there is not locale for "Your message contains too many duplicated characters." message.

**Comment by Kryniowesegryderiusz** [comment]
And Ignore_Duplicate_Characters: true in spam section doesn't work

**Comment by kangarko** [comment]
The highlighted message in in the localization file:

![a](https://i.imgur.com/GgS33GA.png)

To disable similarity check, set Anti_Spam.Chat.Similar_Percentage_Block to 0

**Comment by Kryniowesegryderiusz** [comment]
You are still talking about message similarity and I'm asking for the **character** similarity check. Message that you have hilighted says "Please do not repear the same (or similar) message". I'm asking for "Your message contains too many duplicated characters" one. So could you answer my questions? To remind they are following:
1) How to disable the CHARACTER (LETTER) similarity check
2) How to change amount of acceptable letters in row in CHARACTER similarity check.

**Comment by kangarko** [comment]
I understand, sorry for the initial misunderstanding! ChatControl does not have such feature unless enabled explicitly in rules/chat.txt file, but there is no such message:

![a](https://i.imgur.com/otgtphw.png)

**Comment by Kryniowesegryderiusz** [comment]
Oh my god. I'm so sorry. I forgot that I haven't unload plugin that I was testing before i found ChatControl and this feature was from another plugin. I'm so sorry for wasting your time. I was pretty sure that is a feature of ChatControl.

**Comment by kangarko** [comment]
No worries, can happen.
