### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by Ezkrossz** [kangarko/ChatControl#2720]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

![image](https://github.com/kangarko/ChatControl-Red/assets/169351817/40cbbaf6-ea6f-4b2e-9bea-59f7c0554581)

I don't have a license yet.

**Comment by kangarko** [comment]
Not a chatcontrol bug. We dont even have such a message.
