### ISSUE TITLE
Expirovaná license - ChatControlRed

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2721]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Zdravím, měl předtím zakoupený ChatControl Pro a license mi transfernula na ChatControlRed, ale před nějakou dobou mi to expirovalo, nevěděl jsem, zda se jedná o záměr, ale cena za prodloužení je za plnou cenu. Četl jsem https://github.com/kangarko/ChatControl-Red/issues/1680, ale link na obnovení už nefunguje. Bylo by možné prosím licenci prodloužit? Předem díky! https://builtbybit.com/members/renzotom.40038/

**Comment by kangarko** [comment]
Licencia predĺžená :)
