### ISSUE TITLE
Multi proxy support

### ISSUE THREAD

**Issue by funnycubeguy** [kangarko/ChatControl#2722]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Does this support multi proxy like 2 velocity proxies and it will sync across all?

**Comment by kangarko** [comment]
We do support Redis, yes.

**Comment by funnycubeguy** [comment]
> We do support Redis, yes.

I bought both the velocity plugin and chatcontrol plugin but I don't see any option for redis?

**Comment by funnycubeguy** [comment]
> We do support Redis, yes.

Oh if you're talking about redisbungee is there anything else I have to do? I set up the chat it works on velocity with 1 proxy and 2 servers like the instructions say, but it does not work with redisbungee and 2 veloxity proxies. I followed the regular network setup

**Comment by kangarko** [comment]
I just saw it's not supported in VelocityControl so I am adding it right now

**Comment by kangarko** [comment]
I can't test right now since I don't have a Redis instance. Please try this version:

[VelocityControl-1.0.7.zip](https://github.com/user-attachments/files/15898212/VelocityControl-1.0.7.zip)
