### ISSUE TITLE
Improve gradients

### ISSUE THREAD

**Issue by funnycubeguy** [kangarko/ChatControl#2724]
### Summary

Can you add some more gradient compatibility with formats? Multiple gradients instead of just 2 like Gradient: '#D95632 - #DB6E46 - #ffc07c - #4CFF00' 

Can you also add something like minedown so we can easily add gradients without doing things like &#D95632☄ &#DA5F39S&#DA633Dk&#DA6741y &#DE7347L&#E57E49e&#EB884Bg&#F2924Ce&#F89D4En&#FFA750d'.

For example: `<gradient:#A279D7:#d46c76:#ffc07c>test</gradient>` in the hover format.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Less customization somewhat of a deal breaker since ranks can't have nice gradients like other chat plugins. Thank you!

**Comment by kangarko** [comment]
Thank you, yes that and minimessage compatibility is planned. I am researching options right now: https://github.com/PaperMC/Paper/discussions/10917#discussioncomment-9826966

No ETA, because it would need to rewrite our core.
