### ISSUE TITLE
Problem with /chc colors menu

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2726]
### "/version ChatControlRed" - plugin version

ChatControlRed version 10.27.3

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://mclo.gs/A3KDjIM

### "/chc debug" output (strongly recommended)

https://ufile.io/9bxczpm8

### Information about the issue/bug

When you go into the menu to choose colors it doesn't react and you can move the elements.

As you see I can move the items and leave them in other slots

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/34ad813f-e701-4f65-a42e-250cd412a3f5)

**Comment by Z3r0xh** [comment]
The same thing also happens in the spy menus
https://mclo.gs/Ut5iaXA

**Comment by BAD7777** [comment]
My players just get free wool because of this problem! Fix it urgently!

**Comment by kangarko** [comment]
Sorry guys, will update and provide context what happened asap tonight.

**Comment by Z3r0xh** [comment]
> Sorry guys, will update and provide context what happened asap tonight.

the problem persists

https://mclo.gs/H5g7WfI

**Comment by kangarko** [comment]
Sorry to hear, I will fix this adjacent error tonight.
