### ISSUE TITLE
1.20.4: Velocity is not starting

### ISSUE THREAD

**Issue by martijnpu** [kangarko/ChatControl#2727]
### Error log (if applicable)

https://paste.gg/p/anonymous/a1ed1bb619244af986b97bb5dba7dc66

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/user-attachments/files/15932437/debug.zip)

### Information about the issue/bug

When updating from VelocityControl 1.0.6 to 1.0.8 this error appears in the console and the plugin will not be loaded.

![image](https://github.com/kangarko/ChatControl-Red/assets/38832167/391261fc-db2d-4450-aa67-dcfb920b067f)

**Comment by kangarko** [comment]
Redownload from builtybit, it loads fine on my end: https://i.imgur.com/jvm9oiq.png
