### ISSUE TITLE
problem with chat prioritiesMinecraft Version: Your Question Title

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2728]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hello, I am using both chatcontrolred and ultimateclans, the performance is good in both.

The problem or my doubt is with the /clan chat priorities.

If the user types /clan chat and then writes what he wants to send, it is sent fine, but if he only enters /clan chat then the messages he writes afterwards are not sent. I understand that it is a problem of priorities, I have been reading the wiki but I don't quite understand how it works.

If you can explain to me how to fix it or how it works a little more with examples it would be helpful.

I leave you as you listen to the priorities of both your plugin and ultimateclans:

I have left your plugin as it was so as not to break it
![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/5d62b5e6-67b5-4c13-9df4-44f3d2932f21)

ultimateclans /clan chat:

![image](https://github.com/kangarko/ChatControl-Red/assets/138524212/c894677e-e55e-4951-8258-d87f8dea321c)

thank you very much for your help!

**Comment by kangarko** [comment]
Hello,

Please see https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities#important-regarding-paper-119

**Comment by Z3r0xh** [comment]
> Hello,
> 
> Please see https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities#important-regarding-paper-119

I'm trying, but I can't get it. I don't understand very well, I have set high in ccr and lowest in uclans and nothing, the /clan chat is not shown

**Comment by kangarko** [comment]
There are 12 combinations with modern chat on true/false and the 6 priorities for each, if none of them work then unfortunately it's incompatible
