### ISSUE TITLE
1.20.4: HEX Color not parsed correctly with relationals placeholders

### ISSUE THREAD

**Issue by Willi4mDev** [kangarko/ChatControl#2729]
### "/version ChatControlRed" - plugin version

10.26.3

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/user-attachments/files/16022005/debug.zip)

### Information about the issue/bug

Hi, i have a plugin with relationnals placeholder for relations colors.

Here the code:
![image](https://github.com/kangarko/ChatControl-Red/assets/138307082/a52f6bfb-e29e-4c4e-b5c4-735af9b65be1)

Here the debug: 
`relation_color_simple_hex`
`Player One: Willi4m`
`Player Two: Willi4m`
`Relation: self`
`Relation Color: <#6CD07D>`
`Simple Hex: #6CD07D`

The format:
![image](https://github.com/kangarko/ChatControl-Red/assets/138307082/36f4e5b4-8f2f-42c2-9b44-1a2cc1896df5)

And the result:
![image](https://github.com/kangarko/ChatControl-Red/assets/138307082/27dcb9d1-c32b-47ac-b1dd-f59bb87dd3fb)

So the returned color should be green (#6CD07D), but show a pink color, and for every hex color that show only a legacy color with the last HEX of the color code, "D" for #6CD07D, that pink, for #E0E0E0 that will take "0" and show black color.

I tried with legacy hex colors like §x§6§C§D§0§7§D or &x&6&c&d&0&7&d and i got the same result.

**Comment by kangarko** [comment]
Probably lost somewhere in the adventure to legacy chat translation, unfortunately it's an incompatibility.

**Comment by kangarko** [comment]
Can you try toggling modern chat listener? It's in settings.yml

**Comment by Willi4mDev** [comment]
I toggled modern chat listener to false and the problem persist :/

**Comment by kangarko** [comment]
I'm extremely sorry, it appears to be broken on 1.20+. I will pour more time into this when I find it, thanks.
