### ISSUE TITLE
DiscordSRV sending multiple lines of same message

### ISSUE THREAD

**Issue by NerdyBirder** [kangarko/ChatControl#273]
Version: 10.1.8, server is bungeecord with lots of instances, 1.16.4

I set up discord integration but when i try to chat in my global channel in discord it sends the message through each active bungeecord instance in the channel which results in the message repeating 3 or 4 times depending on how many instances are running at any given time. Minecraft to discord chat is working perfectly fine. zipped chatcontrolred and discordSRV folders attached for reference

[ChatControlRed.zip](https://github.com/kangarko/ChatControl-Red/files/5704254/ChatControlRed.zip)
[DiscordSRV.zip](https://github.com/kangarko/ChatControl-Red/files/5704262/DiscordSRV.zip)

![image](https://user-images.githubusercontent.com/32281657/102383293-5e535d80-3f99-11eb-8914-afc6fa969d96.png)
In this screenshot i am in the lobby, OC1 and OC3 are other bungeecord instances

**Comment by kangarko** [comment]
Yeah it's a feature to make your message more visible.

Just kidding, fixed.
