### ISSUE TITLE
/ccr command permission

### ISSUE THREAD

**Issue by Cookie12345678** [kangarko/ChatControl#273]
Maybe I'm not sure how to work with this plugin. But I don't want people in specific groups (non-staff) to be able to use the /ccr (clear chat) command. How do I fix this?

**Comment by kangarko** [comment]
You can create a rule such as:

```
match ^/(ccr)
ignore perm clear.chat
then warn &cNo permission for this command.
then deny
```

place it in rules/chat.txt
