### ISSUE TITLE
1.20.4: PrePrivateMessageEvent#setSound does not work

### ISSUE THREAD

**Issue by Jyguy** [kangarko/ChatControl#2733]
### "/version ChatControlRed" - plugin version

10.27.5

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

The setSound method that was added in 10.27.3 to the API does not do anything. Regardless of if it's set to true or false, the sound for the receiver plays.

**Comment by kangarko** [comment]
thx, will be fixed
