### ISSUE TITLE
Better ChatBubbles support

### ISSUE THREAD

**Issue by d0ddn** [kangarko/ChatControl#2734]
### Summary

I want you to help the plugin
Better ChatBubbles add support for your plugin

Can you answer the developer about this?
https://github.com/max1mde/ChatBubbles-API/issues/1

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Your excellent chat plugin does not edit messages in Bubbles and I would not like to send them to some channels, for example admin chats

" this is a symbol for sending a message directly to the admin channel
![2024-07-01_13 59 57](https://github.com/kangarko/ChatControl-Red/assets/118112731/9d42413c-cb2d-411a-b19d-5402fe830992)

**Comment by kangarko** [comment]
Try if any of these priority changes will help, otherwise it's unfortunately incompatible:

https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities
