### ISSUE TITLE
1.20.6: How to format discord messages inside admin chat?

### ISSUE THREAD

**Issue by gandra123** [kangarko/ChatControl#2735]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I want to format messages that are sent between minecraft and discord.

I configured everything according to your guide but messages sent from disord do not appear in the game.

**Comment by kangarko** [comment]
You can set a different format using Format_Discord key for that channel. You did not provide /chc debug, I cannot check if you linked your Discord_Channel_Id properly.

Also to debug whats going on set the key Debug to [discord] in settings.yml and restart the server, then see the console when you type in mc.
