### ISSUE TITLE
Request to add new features to Rules

### ISSUE THREAD

**Issue by geumu** [kangarko/ChatControl#2737]
### Summary

When a rule is delayed, a function is needed to tell how much delay remains.

delay 6 seconds
**delay reason {delay} seconds left!**

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Users don't know why the rule doesn't work, so they think it's a bug and generate a report.

**Comment by TheIntolerant** [comment]
![image](https://github.com/kangarko/ChatControl-Red/assets/48093184/d1e4ec4f-6235-47ff-bb05-6e3bad358a31)
Leaving this for reference, never got a chance to test this! But this is basically what I asked for a while back!

If you are able to @kangarko could you give an example of this placeholder being used? As I didn't understand how to use the placeholder!

**Comment by kangarko** [comment]
Spot on. It's already there tho, but I missed documenting it. Fixed now:

![a](https://i.imgur.com/yqRq3gT.png) from Wiki > Rules

**Comment by kangarko** [comment]
I will improve the reliability of this in the next version since I spotted some glitches testing it

**Comment by TheIntolerant** [comment]
Thank you!!

Random question, did Protect have the same feature? As I cannot tell via [Protect's wiki](https://github.com/kangarko/protect/wiki/Rules#delay)

Also hope it was okay that I added `<time> [message]` in the wiki for chatcontrol
![image](https://github.com/kangarko/ChatControl-Red/assets/48093184/59f6b0d3-6653-4535-aaad-4b0eaa71788d)

**Comment by kangarko** [comment]
Thank you! Yes, in Protect it should work the same, I updated its Wiki now to include the time and message parameters
