### ISSUE TITLE
[Question] about Formatting and Gradients

### ISSUE THREAD

**Issue by saschahi** [kangarko/ChatControl#274]
Is there a way (yet) to let players use gradients for themselves? 
for example in /tag nick or /chc color
or would I have to pre-fab them all in the formatting files and then permission-juggle them around if I'd wish to implement this?

I could see that hex codes by themselves work just fine, but don't understand the whole new gradient thing yet xD

- Saschahi

**Comment by kangarko** [comment]
No sorry, due to technical implementation we can only add gradients in the config. Thanks for the tip though!
