### ISSUE TITLE
1.21: Redis integration issues in VelocityControl 1.0.8

### ISSUE THREAD

**Issue by addstar** [kangarko/ChatControl#2741]
### Information about the issue/bug

We use a RedisBungee fork for Velocity on a single Velocity instance (for non-standard reasons) but as of VelocityControl 1.0.8, if RedisBungee is detected it _always_ uses it for communications (which we don't want right now).

There's two issues here:
1. I'd like the option to disable Redis integration, even if RedisBungee is detected.
2. The Redis integration doesn't seem to work. Chat seems to break entirely with the Redis integration. Looking at the code, it seems like VC _only_ sends messages to other proxies via Redis and not to local backend servers via plugin messages. Is this intended? How do local backend servers receive messages in this scenario?

It's possible my setup is different to expected or not compatible somehow, but currently we are unable to use VC 1.0.8 until at least the first issue is fixed.

Hope this description makes sense? Not sure what other logs/info I can provide?

**Comment by kangarko** [comment]
Hello,

1. Added!
2. Fixed!

Please test on the next version.

Matej

**Comment by addstar** [comment]
Awesome, thank you for the fast response and fix! :100:
