### ISSUE TITLE
1.21 - discord messages doesn't apply format

### ISSUE THREAD

**Issue by StKillReal** [kangarko/ChatControl#2742]
### "/version ChatControlRed" - plugin version

10.27.5

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

No

### Information about the issue/bug

All worked fine on 1.20.4, but after upating to 1.21 discord messages are broken and looks like a text without prefix, nickname and colors - just a simple white text...
```
  discord-prefix:
    Message: '&9| &f{player} &9>>> &f{message}'
    Sender_Condition: '{sender_is_discord}'
```
![image](https://github.com/kangarko/ChatControl-Red/assets/60330193/8ddc0d00-f150-429a-93f3-e58bf7e8c60e)

**Comment by kangarko** [comment]
Please send me your /chc debug and tell me which channel it is.

**Comment by StKillReal** [comment]
> Please send me your /chc debug and tell me which channel it is.

global-chat
[debug.zip](https://github.com/user-attachments/files/16108312/debug.zip)

**Comment by kangarko** [comment]
We recently started using Format_Discord on discord too. Remove that option from settings.yml > Channels.List:global and the format will now be used.
