### ISSUE TITLE
1.20.4: Toggling private messages while in conversation soft-mutes the other party

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/ChatControl#2747]
### "/version ChatControlRed" - plugin version

10.26.4

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/user-attachments/files/16115504/debug.zip)

### Information about the issue/bug

To reproduce:
- Have player A and player B start messaging each other in conversation, by player A starting the conversation using `/msg B`.
- Player B uses `/msgtoggle`, turning off private messages.
- Player A can no longer send any messages without seeing "B has toggled off private messages".
- Player A is only allowed to speak again if B turns on private messages, or A starts a conversation with a third user.

I know my plugin version is slightly outdated, but I have not seen anything in the recent changelogs related to this.

**Comment by kangarko** [comment]
Is /msgtoggle coming from ChatControl? If not then it's incompatible

**Comment by Leomelonseeds** [comment]
It is a ChatControl command yes. It works perfectly fine if you're not currently in a private conversation.

EDIT: I believe I set `/msgtoggle` as an alias for `/toggle pm`

**Comment by kangarko** [comment]
I mean the player A can no longer send messages to the player B as long as B is muted. A needs to use /msg someoneElse to get out of the softmute. That is by design. How would you like it to work then?

**Comment by Leomelonseeds** [comment]
Ah, I should have reported that A using `/msg B` a second time to cancel their conversation with B also results in the "B has toggled off private messages" message, when it should exit out of the conversation.

**Comment by kangarko** [comment]
This is by design, and changing it is a low priority feature for me right now due to the other work this month. Thanks for reporting tho.
