### ISSUE TITLE
Could we participate in the beta?

### ISSUE THREAD

**Issue by m171717** [kangarko/ChatControl#275]
Good day,
We've been using ChatControl Pro for years and are interested in partaking in the ChatControl Red beta, how would we go about doing so? My apologies if this is the wrong section, we cannot find any other contact method.

**Comment by kangarko** [comment]
Thanks so much! We've already finished our private beta, and the full plugin will be released in 1-2 days. Learn more at mineacademy.org/chatcontrol-red
