### ISSUE TITLE
1.0.9: BungeeMessageChannel error

### ISSUE THREAD

**Issue by hallo1142** [kangarko/ChatControl#2750]
### "/chc debug" output (strongly recommended)

Has been sent via mail.

### Information about the issue/bug

We're having issues with the bungee message channel using the [ConnectOther](https://docs.papermc.io/paper/dev/plugin-messaging#plugin-message-types) type. When using that type and sending it via the BungeeCord channel, it will be treated as Connect type and the current player will be send instead of the specified player. We also tried the bungeecord:main which should be used since 1.13 and this channel does not get handled at all from the plugin.

**Comment by kangarko** [comment]
Assumed you use VelocityControl, I fixed that, thanks.

**Comment by hallo1142** [comment]
Thank you for the quick fix 😄
