### ISSUE TITLE
1.20.1: Questions about luckperms prefixes on bungeecord

### ISSUE THREAD

**Issue by xOnlyFadi** [kangarko/ChatControl#2751]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hello kangarko, I have a question about bungeecord version of chatcontrol red is there a way to get luck perms prefixes that works with bungeecontrol red to get prefixes?

**Comment by kangarko** [comment]
Yes, but you need to make the prefixes be recognized by PlaceholderAPI on your spigot server. ChatControl will then pick up on them.

**Comment by xOnlyFadi** [comment]
> Yes, but you need to make the prefixes be recognized by PlaceholderAPI on your spigot server. ChatControl will then pick up on them.

How do I make to recognize the placeholder for chatcontrol ?

**Comment by kangarko** [comment]
Install PlaceholderAPI and its luckperm expansion pack

**Comment by xOnlyFadi** [comment]
tried this but the join message with luckperms prefix did not work I used a different method, download the bungeecontrol-red from bitbucket and imported the luckperms library and made a custom function that calls the prefix is that okay with you this way?
```java
	public String getPlayerPrefix() {
		LuckPerms api = LuckPermsProvider.get();

		User user = api.getUserManager().getUser(this.uniqueId);
		String prefix = user.getCachedData().getMetaData().getPrefix();

		return prefix;

	}
```

**Comment by kangarko** [comment]
That is okay!

**Comment by xOnlyFadi** [comment]
thank you and have a nice day 😄
