### ISSUE TITLE
Hide quit message for unauthenticated players

### ISSUE THREAD

**Issue by gandra123** [kangarko/ChatControl#2753]
### Summary

As the title says, make it possible to hide quit messages for players that are not logged in.

CCR already has support for authme but only for join messages.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

Welp it would be cool to have that, this way the chat gets spammed.

**Comment by kangarko** [comment]
Please resubmit your request in a month, we're rewriting chatcontrol to adventure. It will get dropped out anyways during this time but we might be open to adding this later :)
