### ISSUE TITLE
1.20.6: A bug with sending emails

### ISSUE THREAD

**Issue by BAD7777** [kangarko/ChatControl#2757]
### "/version ChatControlRed" - plugin version

ChatControlRed version 10.27.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

Three different emails were sent to three different people. However, from the screenshot, it is evident that the second email was received by both the second and first person, and the third email was received by all three. I am not sure if this is a mistake in the text or if, in reality, some people received additional emails meant for others.

Look, each email was addressed to a single individual. However, it shows that the second email had 2 recipients, and the third one had 3 recipients. When hovering over the email (here I hovered over the second one), it shows that the recipients are 777 and Nikitushka. The only thing I don't know is whether this is just a text bug or if previous emails are actually being sent to new recipients.

To rephrase the last part, I don't know if 777 and Nikitushka received the email with the subject "check," but they are listed as recipients when hovering over it, even though this email was sent to a single other person.

![image](https://github.com/user-attachments/assets/f6dc7b8c-a5b8-4c97-985b-18a8484b469c)

**Comment by kangarko** [comment]
Thanks, will be addressed end of the week due to company holidays.

**Comment by kangarko** [comment]
Should be fixed in the next version.
