### ISSUE TITLE
1.16.5: In rules, player delay <time> [message] is not linked to velocity.

### ISSUE THREAD

**Issue by geumu** [kangarko/ChatControl#2758]
### "/chc debug" output (strongly recommended)

https://ufile.io/wpr8tdh5

### Information about the issue/bug

**Explanation**: In rules, 'player delay <time> [message]' is not linked to velocity.

After applying 'player delay <time> [message]' on server1, if you return to server2, 'player delay <time> [message]' has been initialized, so you can chat while ignoring the delay.

**Video**: https://youtu.be/JqrJ6oXgDts

**Comment by kangarko** [comment]
Thanks, will be addressed end of the week due to company holidays

**Comment by kangarko** [comment]
I dug into this, but for technical complexities this will remain unsupported for now. I'll add this to our roadmap.

**Comment by geumu** [comment]
Will it take a month or so to be added?

**Comment by kangarko** [comment]
No ETA for now due to the fact we are rewriting a bunch of other things
