### ISSUE TITLE
[Feature Request/Question] - Advertising (youtuber/streamer)

### ISSUE THREAD

**Issue by arturek1666** [kangarko/ChatControl#276]
I wasn't aware if in pro you could do that but would love to see that feature in chatcontrol red.

I have some streamers and youtubers on the server and I would love them to be able to advertise only their channels or streams only, would love to see permission chatcontrolred.bypass.add.(url address) chatcontrolred.bypass.add.https://www.youtube.com/user/PewDiePie, if not permission somthing that will allow them to advertise but also not allow them to spam ;) basicly something chat friendly for youtubers/streamers ;)

**Comment by kangarko** [comment]
I thought you wanted to advertise ChatControl haha!

Yes, that's totally possible, you can either open rules/groups.rs and see what permission we have to bypass ad filter, or open rules/global.rs and add their channel url to the exceptions list. Both are documented.
