### ISSUE TITLE
Number abbreviation problem

### ISSUE THREAD

**Issue by xBeratE** [kangarko/ChatControl#2760]
### "/version ChatControlRed" - plugin version

10.27.7

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

https://prnt.sc/KW_vc3DfUR_Q  A different plugin is zAuctionHouse, players sell their items with a command and while selling, some of the amount they enter repeats the numbers like 100000 and chatcontrol changes it to 100. This needs to be fixed urgently

**Comment by xBeratE** [comment]
Line  9544: [08:32:09] [Server thread/INFO]: Sachiiikoo issued server command: /ah sell 130000
Line  9547: [08:32:09] [Server thread/INFO]: CATCH: /ah sell 130000
Line  9548: [08:32:09] [Server thread/INFO]: UPDATE: /ah sell 1300

**Comment by kangarko** [comment]
You need to adjust your regular expression matching to ignore numbers. You can just ask chatgpt on how to do that. I am unsure which rule this is regarding to because you did not provide /chc debug
