### ISSUE TITLE
excessive consumption by chatcontrol

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2761]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

They tell me that a large part of my tps drops originate from the chat plugin, could you check it?

Since I like the chat plugin and I would like to be able to continue using it

https://spark.lucko.me/CKcREydL83

![image](https://github.com/user-attachments/assets/f5ee1c37-82b6-4f08-85b8-930430b13883)

**Comment by kangarko** [comment]
I'm sorry you've received misleading support from their side. Specifically using decoding Adventure message in the chat packet causes the major slowdown. While we can't improve server internals, your best bet is indeed turning off our packet listener by setting Integration.ProtocolLib.Listen_For_Packets to false in settings.yml
