### ISSUE TITLE
Newbie - Dont join global chat until they talk in global chat

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2762]
### Summary

Brand new spawns get overwhelmed when they first join, go join a bunch of servers and be overwhelmed by in-game chat, if there's anything important you needed to read, its gone in seconds with a busy server!

But there cant be any learning curve to getting out of this newbie jail, it needs to automatically join them to reading global as soon as they write in chat (not command, text).

- Alert the player they are new, and that global chat has been temporarily disabled for 2-5 mins, at which point it will auto join them, and that all they need to do is speak in chat to join global.
- Tell them if they want to join global without talking, use /channel and click on the arrow to join global, this way it also teaches them about /channel and how to manage their chat channels, 2 birds this one!
- If they talk in chat they are joined to read global
- only if they are tagged in a chat message will this bypass and be sent to them, for example "Welcome Username" would be sent to them, because this is a good way to show new players that there are active real people playing, and they new people are welcome to chat.
- admins can toggle them into global easily

Imagine trying to read tutorials and NPC information that's sent to you in chat, and all you have is a flood of messages getting in your way.

We have seconds to secure a new player, if they are irritated about learning the server in the first few mins, they will never come back.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

- Make the default luckperms rank not have global read
- Move the first rank up, that you are put into with 2 mins gameplay
- Have a command + npc + hologram that explains this situation to the player
- Could also have exit the region set the rank, but it would need to do a check first to not screw up existing players, leave the spawn area, get ranked up.

**Comment by JerichoTorrent** [comment]
I do like this suggestion a lot. However, as a stopgap, you can join them to the local channel first, and add in your message of the day that they can join the global channel with `/ch join global`

**Comment by kangarko** [comment]
Thanks for suggesting. I recommend getting a custom plugin written that hooks into ChatControlAPI class and switches channels for the newbies according to your needs. I am currently busy writing chatai plugin as well as rewriting chatcontrol to adventure.
