### ISSUE TITLE
1.20.6 -> 1.20.4: Duplicate messages and broken network-wide private messages

### ISSUE THREAD

**Issue by JerichoTorrent** [kangarko/ChatControl#2764]
### Information about the issue/bug

So, I've bug fixed and narrowed down the issues with my dual proxy setup with redis down to just 2 final bugs. When all players are on proxy 1, everything functions as intended. Global channel works, as does cross-server PMs. No duplicated messages. When a player from proxy2 joins, any messages sent in the global channel are duplicated for those in the same backend server as the sender, but not duplicated if on the other servers. For context players are auto-joined to the global channel in write, and the local channel and ranged in read. This is what it looks like: 
![Screenshot 2024-07-25 164135](https://github.com/user-attachments/assets/d4f43ec0-a778-4658-947f-a87fce1c5180)
Furthermore, when a player from proxy2 is online, users cannot send PMs cross-server. It says "player is not online" even if they're both on the same backend server.
![Screenshot 2024-07-25 165038](https://github.com/user-attachments/assets/a9256699-5da8-45b2-99b9-f0cb94bcfa74)
My theory is that somehow that players being present on separate proxy servers causes messages to appear as if they were sent from global and local chat channels, since the [{server}] prefix is only shown in the second message. As for why cross-server PMs aren't sent, I have no idea. Thanks for any attention you pay to this issue. It's always a pleasure being a user of this great plugin!

**Comment by kangarko** [comment]
Thank you for reporting! I'm presently doing a major rewrite, can you please hold this on for the next week and re-test on the upcoming ChatControl 11. Appreciated that!

**Comment by JerichoTorrent** [comment]
Sounds great, I look forward to it!

**Comment by kangarko** [comment]
Just to share the progress, we moved the needle on the plugin a lot and it should be fixed in the 11th release. Still no ETA, I'd be happy if it's out this week.

**Comment by JerichoTorrent** [comment]
Thanks for the update! Very excited to see how this comes along.

**Comment by kangarko** [comment]
Unfortunately still working on this, it's very uncommon that issues take over 5 days to fix let alone 30, and I am doing my best to get it out in a stable format asap. You can track our rework progress of the library we use at https://github.com/kangarko/Foundation/commits/v7/, the chatcontrol repo is private. ETA 1-2 more weeks.

**Comment by kangarko** [comment]
Should be completely solved in ChatControl 11. ETA 1 more week. Thanks for your patience.
