### ISSUE TITLE
1.21: Sign formatting removes newlines

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#2765]
### "/version ChatControlRed" - plugin version

10.27.7

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

I will send a mail

### Information about the issue/bug

The formatting replaces the newlines on signs

https://github.com/user-attachments/assets/d54b8aec-c4b7-4f9f-a392-0442025f54d6

**Comment by kangarko** [comment]
We need to join the lines otherwise players can easily bypass our rules by splitting words on multiple lines. So we parse all four lines together. There is no easy way to split them back after rules parsing afaik
