### ISSUE TITLE
1.21: Chat issues

### ISSUE THREAD

**Issue by Rexmen1** [kangarko/ChatControl#2766]
### "/version ChatControlRed" - plugin version

10.27.7

### Are you using MySQL?

No

### Are you using BungeeCord?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/user-attachments/files/16402068/debug.zip)

### Information about the issue/bug

So chat is not preventing swear words, or not replacing emoji etc in chat... it does show that it worked in console but in chat not...
im using cmi as my chat plugin, and it worked fine until 1.20 im using same settings since 2-3 years never had issue until recently...

[02:58:20 INFO]: *--------- Rule match (chat) for rexmen --------- 
[02:58:20 INFO]: MATCH: \:star\:
[02:58:20 INFO]: CATCH: :star:
[02:58:20 INFO]: UPDATE: ★
[02:58:20 INFO]: <rexmen> ★
[02:58:20 INFO]: xMissZeldax issued server command: /es withdraw REDSTONE:0
[02:58:22 INFO]: <rexmen> nope

![image](https://github.com/user-attachments/assets/45fd30a4-8abd-4db0-9e26-6bd7a0b9b526)

**Comment by Rexmen1** [comment]
I think neither chatcontrol or cmi is working correctly here? as it does show that cmi is working correct chat in public chat but in console something else is taking priority

**Comment by kangarko** [comment]
Probably CMI taking over the chat format. Can you adjust your listener priorities please? https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities 

Also try toggling Modern Chat Listener option in settings.yml

**Comment by Rexmen1** [comment]
Nope nothing works... Can u please not the close the ticket before its really fixed? do i need to reopen this ticket now? or commenting here will make u see it..? If not reply i guess need to reopen it then..

**Comment by Rexmen1** [comment]
Chat_Listener_Priority: HIGHEST

# -------------------------------------------------------------------------------------------------
# 1.19+: Use Paper chat event? This event is fired AFTER the old chat event. We provide this toggle
# for compatibility. See https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities
# -------------------------------------------------------------------------------------------------
Modern_Chat_Listener: false

**Comment by Rexmen1** [comment]
was able to fix it... ty

**Comment by kangarko** [comment]
You're welcome!
