### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by mecray** [kangarko/ChatControl#277]
Hello. 

Recently, there has been this error constantly spamming in the console. All other functions of the plugin seem to me working fine -
`28.12 17:00:31 [Server] ERROR Could not pass event AsyncPlayerChatEvent to ChatControl v5.6.1
28.12 17:00:31 [Server] INFO java.util.UnknownFormatConversionException: Conversion = '§'
28.12 17:00:31 [Server] INFO at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:100) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
28.12 17:00:31 [Server] INFO at kangarko.chatcontrol.ChatFormatter.onChatFormat(ChatFormatter.java:64) ~[?:?]
28.12 17:00:31 [Server] INFO at kangarko.chatcontrol.ChatFormatter.execute(ChatFormatter.java:42) ~[?:?]
28.12 17:00:31 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
28.12 17:00:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
28.12 17:00:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
28.12 17:00:31 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1319) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
28.12 17:00:31 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1257) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
28.12 17:00:31 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
28.12 17:00:31 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
28.12 17:00:31 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
28.12 17:00:31 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
28.12 17:00:31 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
28.12 17:00:31 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]`

**Comment by kangarko** [comment]
This error is most likely caused by wrong format option in Chat.Formatter.Message_Format. Make sure you have quotes "" around the message and that it does not contain an invalid %variable or an additional & that is not translated.

![a](https://i.imgur.com/8iMyUAw.png)
