### ISSUE TITLE
Party and Friends party chat support.

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#277]
Hi, 

I currently use Party and Friends Extended for Spigot  https://www.spigotmc.org/resources/party-and-friends-extended-for-spigot-supports-1-7-1-16-4.11633/

They also have a Bungeecord Party and Friends.

Please could you add party chat support for these?

**Comment by kangarko** [comment]
Thanks for your suggestion! However, the plugin is very small, only 404 downloads, and my time is pretty limited so I am focusing on adding more popular plugin support.

However, ChatControl is not obfuscated, if you have a developer they can just hook into our APIs and add support that way.

**Comment by SirCraftypants** [comment]
They have 2 versions and their Bungeecord version has  41 thousand downloads? Seeing as they are both pretty much the same plugin by the same developer, i'm told there's hardly any different aside ones for #Bungee and the other for Non Bungee.

**Comment by 00Hrtz** [comment]
> 
> 
> Thanks for your suggestion! However, the plugin is very small, only 404 downloads, and my time is pretty limited so I am focusing on adding more popular plugin support.
> 
> However, ChatControl is not obfuscated, if you have a developer they can just hook into our APIs and add support that way.

They have 2 versions and their Bungeecord version has 41 thousand downloads? Seeing as they are both pretty much the same plugin by the same developer, i'm told there's hardly any different aside ones for #Bungee and the other for Non Bungee.

**Comment by 00Hrtz** [comment]
Only requesting that it be supported for the party channel so players can use CCR party channel through Party and Friends for Spigot and Bungee.

**Comment by kangarko** [comment]
This plugin is premium and we don't have access to spigotmc any more, you can still send the jar over to matej@mineacademy.org - if you already did, I will get back to it shortly,.
