### ISSUE TITLE
Version: Universe Spigot 1.20.4

### ISSUE THREAD

**Issue by 411Kk** [kangarko/ChatControl#2772]
### Are you using MySQL?

No

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.7

### Optional: Error log

https://spark.lucko.me/thumb/kqSL8M1NWe.png

### Steps to reproduce

 causing 170ms+ spikes every time someone joins because of chatcontrolred https://github.com/user-attachments/assets/30fb81cf-cc72-4f64-ba77-0efeaf1b64d0

**Comment by kangarko** [comment]
Please provide the full spark report and /chc debug file.

**Comment by 411Kk** [comment]
> Please provide the full spark report and /chc debug file.

https://spark.lucko.me/kqSL8M1NWe

**Comment by 411Kk** [comment]
Any updates?

**Comment by 411Kk** [comment]
Hey, this is causing major lag for my server, can someone please look into this or recommend me another chat plugin to switch to?

**Comment by kangarko** [comment]
Your spark report says "Unable to load the data. Perhaps it expired? Are you using a recent version?"

**Comment by kangarko** [comment]
Closed due to inactivity, comment below when you come back.

**Comment by 411Kk** [comment]
> Closed due to inactivity, comment below when you come back.

Im here, yes, I am using the latest version of Chat control.

**Comment by kangarko** [comment]
Try on the next version I will release tonight

**Comment by 411Kk** [comment]
> Try on the next version I will release tonight

Sure will, sorry for the late reply, I don't check this often haha

**Comment by 411Kk** [comment]
> Try on the next version I will release tonight

https://spark.lucko.me/LycPsRotAG Hey, this issue has not
![image](https://github.com/user-attachments/assets/d1f1bc3d-db90-47fa-8c19-bbc536eb0563)
been fixed. Now gives 270ms tick spikes. Please fix this.

**Comment by 411Kk** [comment]
No worries, I'll just move to chatsentinel

**Comment by kangarko** [comment]
It's related to using a flatfile which is inherently slow. You are recommended using MySQL for ChatControl. I will switch to SQLite in ChatControl 11 instead of yaml files for increased performance.
