### ISSUE TITLE
tps lose

### ISSUE THREAD

**Issue by juinwei7** [kangarko/ChatControl#2773]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

10.27.7

### Steps to reproduce

I encountered a problem. When using it with discordsrv, it seems that I can't completely take over discord to send messages.
Sometimes it is sent by discordsrv, sometimes it is sent by ChatControl Red
This situation seems to cause my TPS to drop packets instantly
The packet drop is very short-lived, but has a huge impact

Looking at the report, it seems to be related to PlayerCache

**Comment by juinwei7** [comment]
I just tested it and it seems that there will be a problem when the discord user name is in Chinese, but there will be no problem in English. Could you please help me take a look!

**Comment by kangarko** [comment]
Where can I please look at the report? Please provide a spark report.

**Comment by juinwei7** [comment]
Later, I tried to send a message to minecarft from discordsrc, and tps was adjusted directly. Currently, it only happens when the discord user name is Chinese.

https://timings.aikar.co/dev/?id=4242ae5893eb436db7d49b4e3b14c8e6

**Comment by kangarko** [comment]
Unfortunately paper legacy timings do not provide sufficient info, can you please run a spark report instead?

**Comment by juinwei7** [comment]
https://spark.lucko.me/KmLOg2kxub

Not sure if this is it

**Comment by kangarko** [comment]
Should be solved in ChatControl 11. No ETA yet, but it's coming next week. Thanks.
