### ISSUE TITLE
Paper 1.21-111: Player Suffixes 

### ISSUE THREAD

**Issue by ChiefWarPig** [kangarko/ChatControl#2774]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

I use eternal tags to manage player tags as a suffix on a permission per tag basis. The suffix placeholder does not show the tag as it is not one set in side of ChatControl Red. Following advice on your discord I have swapped your suffix variable for the %eternaltags_tag_formatted% placeholder. The issue this is now causing is if the player doesn't have a tag equipped in eternal tags it now places "None" as the suffix. Can someone explain how this works and how to correct it so if no tags are equiped the suffix is ignored instead of displaying "none" between the players name and their message. 
Based on the information I have received so far I presume this will require a new rule to be created but this raises a new issue. 
I have looked at the wiki at the rules section as this is what you support team in discord advise dictates how the chat plugin uses this. In the commands section there is a rule command that states this is used to import new rules but no syntaxs or usage examples are given so it is unclear how this command should be used. When you follow the link in the command section to look at rules there is a long and comprehensivly produced page telling me how to create a new rule but it doesn not tell me how to import the created rules or where to put the input your rules generator outputs, neither can I locate in any of the files the plugin has generated where rules should be added. The only mention with regards to importing rules I can find in the rule section is the following "You can add multiple operators if you wish, but you cannot create your own files" so my question here is if I need a new rule how do I import it where do I setit? I am having the same issue with the rules with adding words to the chat filter, Where do they get entered once I have the generator output? 
Any help you can provide on this would be greatly received.

**Comment by ChiefWarPig** [comment]
Just to update I have had some help from the Discord Group but the suffix now shows as "none" but instead no containing the colour gradients/formats the players nickname contains.

**Comment by kangarko** [comment]
Can you try something like this? Put this as a part in your format file:

```
  tag-prefix:
    Message: '&8[&b{eternaltags_tag_formatted}&8] '
    Sender_Condition: '''{eternaltags_tag_formatted}'' != ''None'''
```

**Comment by ChiefWarPig** [comment]
Hi, Thank you for the response this seems to add an empty set of square brackets at the end of the message if there is no tag applied and a Tag inbetween square brackets at the end of the message if one is applied. Wierdly I have removed the code you have given me today and now it is working as expected/wanted without. Not sure what the reason would be for an inconsistancy like that? 
I appreciate the time and help this is by far the most difficult plugin I have encountered to setup as a new server owner although I am sure once I can get my head around it the plugin will be amazing with the ability to customise it so much. 
I can't seem to locate in the documents and I am hoping you can advise where do I need to paste in new chat rules for the swear filter? Do I need to use the /chc rule command or do I just paste the new rule into wherever it is meant to go? I am struggling frollowing this process through on the wiki it seems slightly confusing/conflicting so if you are able to clarify that for me I would really appreciate it?

**Comment by kangarko** [comment]
Sorry to hear it's a difficult plugin, I'm trying to accomodate advanced users request that's why we have this level of extensive customization options.

Happy to hear it got fixed.

You need to paste your new chat rules at the bottom of any rs file, for example rules/global.rs to make them apply everywhere.

**Comment by ChiefWarPig** [comment]
Ok brilliant thank you. No need to apologise the customisation options is what prompted me to purchase it. Hopefully with a little bit of trial and error and the wiki I will be in a position to utilise some of the more advanced features. 
Thank you for the time and response. :)
