### ISSUE TITLE
Paper 1.21: Chatcontrol issues with ChatColor plugin

### ISSUE THREAD

**Issue by AaronBDesign** [kangarko/ChatControl#2775]
### Are you using MySQL?

No

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.7

### Steps to reproduce

Use both ChatControlRed and [ChatColor](https://www.spigotmc.org/resources/chatcolor.22692/) - &f appears before chat for non-op players. Also RGB chat colours get broken. Was fine before 1.21

&f is the default colour from ChatColor
The broken chat colour is because it's a hex colour

<img width="149" alt="image" src="https://github.com/user-attachments/assets/9926fd40-315e-4e21-87aa-1c1294b6e769">
<img width="70" alt="Screenshot 2024-08-04 164239" src="https://github.com/user-attachments/assets/f672c290-8d3f-49c8-9fd1-89dc1367f468">

**Comment by kangarko** [comment]
It's a plugin incompatibility. Please this adjusting our listener priority: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities If that wont help, unfortunately it's incompatible.

**Comment by AaronBDesign** [comment]
So I have tried the different listener priorities and they didn't work but I don't think it's an incompatible plugin as this only occured after updating to 1.21. Also as it's fine when the player is opped.

I'm not sure about the RGB colours but at least for the &f at least surely this should be made invisible?

**Comment by kangarko** [comment]
The rgb color compatibility should be solved in ChatControl 11. No ETA yet, but it's coming next week. Thanks.
