### ISSUE TITLE
10.27.3: Issues with color parsing in placeholders / 3rd side commands

### ISSUE THREAD

**Issue by pjindras** [kangarko/ChatControl#2776]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### Question

Hello, I have serious issues with parsing colors properly from placeholders in other than chc commands and in 3rd side commands, it doesnt parce the colour properly

![image](https://github.com/user-attachments/assets/dd08e193-70eb-48c9-89b7-2d37f2764204)

**Comment by kangarko** [comment]
Please try https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

If that won't help, it's incompatible. I'm working on ChatControl 11 that should bring better compatibility with modern RGB colors.
