### ISSUE TITLE
ChatControlRed bypassess litebans mutes.

### ISSUE THREAD

**Issue by MassiveLag** [kangarko/ChatControl#2778]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.7

### Optional: "/chc debug" file

ChatControlRed works awesome! But currently we are having issues that it is bypassing litebans mutes. Is this a bug or what do i do?

### Steps to reproduce

I have checked the chatcontrol red config, i dont see anywhere an options to enable litebans check or whatever.

**Comment by MassiveLag** [comment]
I have mute system turned it to false. So it should check for litebans mutes. No?

When a muted player say something. It says "[Event cancelled by litebans]"

**Comment by kangarko** [comment]
Can you send a screenshot of that message [Event cancelled by litebans] please?

**Comment by kangarko** [comment]
Also try adjusting your https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

**Comment by kangarko** [comment]
Closed due to inactivity, comment below when you come back.
