### ISSUE TITLE
Default CCR throwing Warns/Errors on reload/restart.

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#278]
Minecraft Version: 1.16.4
MySQL:false
BungeeCord: false

Ok, i just installed ChatControl Red and added some more Swear words, nothing else. 

I ran /chc reload and it threw this Warn   https://paste.helpch.at/ovohakebuy.md

in settings.yml

So i removed the @ and replaced with / and tried reloading and it through another error similar to the above error.

Now I'm about to remove everything that was there by default, so i can reload, hopefully without an error.

**Comment by 00Hrtz** [comment]
OK so i removed everything from the whitelist specified above and attempted to reload again and now have this warn

https://paste.helpch.at/hopihozuxo.md

**Comment by 00Hrtz** [comment]
OK not errors but warns rendering it unusable from purchase, i cant reload and i've not even configured anything apart from the profanity list.

**Comment by 00Hrtz** [comment]
My Server is now down and time is money, please fix asap.

**Comment by 00Hrtz** [comment]
OK now i'm getting an error on Restart  https://paste.helpch.at/ijazimifit.rb

So now i can't chc reload or even restart, the plugins completely disabled and i haven't even done anything.

**Comment by 00Hrtz** [comment]
Why always me sigh.

**Comment by 00Hrtz** [comment]
I updated to 10.1.8 and it's still throwing the error.

**Comment by 00Hrtz** [comment]
OK So i decided to delete the settings.yml file and restart my server, everything is back to normal, extremely strange because i never did anything to the file at all.

I'm now going to attempt to make some changes and hopefully i won't get a re-occurrence of the above error or warms.

**Comment by kangarko** [comment]
Your files contained syntax errors, please use https://yaml-online-parser.appspot.com/ before putting this live and fix this. You should have also created a local test server before pushing any new plugin to production. Thanks.
