### ISSUE TITLE
Prefix issue

### ISSUE THREAD

**Issue by mkrtes** [kangarko/ChatControl#278]
Hi! Help me pls.. I use ChatControl plugin with LP. Why I can't see prefix in chat?  I should note that if I assign a group globally, then the prefix is visible. 
![default](https://user-images.githubusercontent.com/7057658/35179300-ce6a69e6-fda8-11e7-8c95-e5c65eff18d8.png)
![default](https://user-images.githubusercontent.com/7057658/35179305-ddd9e21c-fda8-11e7-9973-39398e3113cf.png)

**Comment by kangarko** [comment]
Hey,

please install the Vault plugin and use the variable %pl_prefix in ChatControl's formatter in settings.yml.
