### ISSUE TITLE
Minecraft 1.21 | CCR 10.27.7 - [item] crashes <1.21 clients

### ISSUE THREAD

**Issue by JerichoTorrent** [kangarko/ChatControl#2780]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.7

### Steps to reproduce

![Screenshot 2024-08-05 183827](https://github.com/user-attachments/assets/4d57d252-913e-42a3-9ca8-9dbdcc43328f)
Sorry to keep making issues lol. I know you're working on ChatControl 11; no rush on that, but just wanted to make you aware of another issue that cropped up. I recently updated two of my backend servers to 1.21. I use ViaVersion & ViaBackwards to support older clients. Long story short, myself and another user on a 1.20.6 client get kicked from the network anytime someone uses [item]. This does NOT effect users on 1.21.
The above screenshot shows the client error. Players on earlier versions of MC do get kicked from the whole network, and no errors are logged in console.
I am on the latest CI build of ViaVersion & ViaBackwards, which is recommended unless you have a specific use case not to.

**Comment by JerichoTorrent** [comment]
UPDATE:
This only happens when a player uses [item] when holding a new 1.21 item, like the new music disk. In fact, it doesn't happen with a mace. It only seems to be the music disk causing this, strangely. I'm going through the list to see if I can narrow it down.

**Comment by JerichoTorrent** [comment]
Confirmed, only the new music disks. I would say this is a really low priority issue. Only address it if you're a perfectionist lol.

**Comment by kangarko** [comment]
Please report this to ViaVersion, since we only pass through the native itemstack nbt tag it looks like ViaVersion needs to accommodate older versions in how the hover event data is displayed.
