### ISSUE TITLE
Variable Placeholder Issue

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#2781]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.27.7

### Optional: Error log

No need

### Optional: "/chc debug" file

I wanted these variables (placeholder) use on any resources. But %% not working.
https://github.com/kangarko/ChatControl-Red/wiki/Variables

### Steps to reproduce

Is this possible to use variables to use as placeholder? For example, I wanted to use {player_nick} on NEZNAMY`s tab plugin. But {player_nick} placeholder not working and I used %player_nick% and still no use. I read this wiki but not working it seems.

https://github.com/kangarko/ChatControl-Red/wiki/Variables

**Comment by kangarko** [comment]
We only support {placeholder_syntax} not %%
