### ISSUE TITLE
1.21: Performance issues

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2782]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.27.7

### Optional: "/chc debug" file

[debug (1).zip](https://github.com/user-attachments/files/16535569/debug.1.zip)

### Steps to reproduce

Unsure, just looks for tips on performance improvements. ChatControl Red is taking a massive amount of tick time whenever a player joins, but as far as I know I don't have that much interacting with them joining. Attached my debug file in-case a variable I have or some such like that is messing with me and I'm not sure.

**Comment by HorusApl** [comment]
Forgot to attach the spark report* https://spark.lucko.me/0LMlYPPbuy It seems almost entirely based on a player joining.

**Comment by kangarko** [comment]
Please use mysql to lift the file operations off of the main thread, especially now that you are having a large dataset in the file.
