### ISSUE TITLE
Comments made in ``chat.yml`` aren't saved.

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2783]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.27.7

### Steps to reproduce

1. Install plugin
2. Add a few comments to the file ``chat.yml``
3. Restart/reload the server
4. Open ``chat.yml`` the comments added to the file are now gone

**Comment by S2GN** [comment]
Are you using MySQL?
Yes

Are you using a proxy?
Velocity

"/version ChatControlRed" - plugin version
10.27.7

Optional: Error log
No response

Optional: "/chc debug" file
No response

Steps to reproduce
Install plugin
Add a few comments to the file chat.yml
Restart/reload the server
Open chat.yml the comments added to the file are now gone

**Comment by kangarko** [comment]
Custom comments are not supported for files that have their equivalent in the jar file.
