### ISSUE TITLE
git-Purpur-1171 (MC: 1.16.5): Player cache load and remove consumes too much.

### ISSUE THREAD

**Issue by SentorCraft** [kangarko/ChatControl#2784]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.26.4

### Steps to reproduce

![resim_2024-08-10_210802573](https://github.com/user-attachments/assets/29fefd8a-e9c8-4816-9eec-9ad7359fa302)
Nothing to reproduce. Just start the server and let the plugin work.

I will share more information like chc debug when i update to the latest version.

**Comment by kangarko** [comment]
Please use mysql for your setup, it will be vastly more efficient.
