### ISSUE TITLE
1.20.1-1.20.4: Key 'player' is already in the map

### ISSUE THREAD

**Issue by kamber5** [kangarko/ChatControl#2785]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

10.27.7

### Optional: Error log

https://pastebin.com/eWf7TCsK

### Steps to reproduce

Updated only to latest versions.
Bungee Control Red is on 10.27.7

**Comment by kangarko** [comment]
Should not happen in the next version, thanks.
