### ISSUE TITLE
1.21.1: NBTCompound.getString bug

### ISSUE THREAD

**Issue by Pantera07** [kangarko/ChatControl#2786]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.27.7

### Optional: Error log

https://mclo.gs/g1iyPXg

### Steps to reproduce

Click or drop an item on 1.21.1 Paper server.

**Comment by kangarko** [comment]
Will be updating to support 1.21.1 shortly.
