### ISSUE TITLE
Update Minecraft 1.21.1

### ISSUE THREAD

**Issue by BAD7777** [kangarko/ChatControl#2787]
### Summary

Update MineCraft 1.21.1

**Comment by kangarko** [comment]
I know, we are waiting for some other changes, coming in a few days.

**Comment by BAD7777** [comment]
Alright, we'll wait, but you mentioned that there would be an update last week, and there’s still nothing.

"Could not initialize class org.mineacademy.chatcontrol.lib.remain.nbt.NBTReflectionUtil"

**Comment by Pantera07** [comment]
https://github.com/kangarko/ChatControl-Red/issues/2786
