### ISSUE TITLE
It throws me out when using a command or writing with version 1.21.

### ISSUE THREAD

**Issue by Tunikaso** [kangarko/ChatControl#2788]
### Are you using MySQL?

No

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

Last Version

### Steps to reproduce

Hello, I have this error when I log in with version 1.21 to the server. If I write or use a command it throws me out and says this. They tell me it has to do with the chat plugin. Any solution? A messy chat packet has been received. Has there been any change in the time on your device?
![Uploading image.png…]()

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Red/issues/2787
