### ISSUE TITLE
Version: TitleChatControl Red 10.27.8

### ISSUE THREAD

**Issue by ChiefWarPig** [kangarko/ChatControl#2789]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.27.8

### Optional: "/chc debug" file

[debug.zip](https://github.com/user-attachments/files/16600279/debug.zip)

### Steps to reproduce

I had the following message in console. Updated the settings.yml as per the message and now the red X does not work for removing chat ingame. It removes messages on discord via the discord link but doesn't remove them in game. I have updated to the latest version released today and still not working. Any help you can provide is gratefully received. :)

**Comment by ChiefWarPig** [comment]
Console Message for reference. 

![Screenshot 2024-08-13 134112](https://github.com/user-attachments/assets/e42f83cd-1af7-4f42-9ed5-e6268a891bca)

**Comment by kangarko** [comment]
You need to enable protocollib integration back to use the [X] feature. Should be working fine with ViaVersion now, the message is there for the part of our userbase having some custom settings/interference where the only solution is knock it off at our end

**Comment by ChiefWarPig** [comment]
Ahhh ok my bad. I think looking into it a bit further the player is using Litematic mod so maybe interfering with ViaVersion. Thank you for the quick response. May a ask a question re chat formatting whilst I am here if that is ok?

**Comment by kangarko** [comment]
Sorry for the late response, just ask out or use discord for community support, but you can just ask here
