### ISSUE TITLE
1.20.1-1.20.4: PM not working, Player not online but he is

### ISSUE THREAD

**Issue by kamber5** [kangarko/ChatControl#2790]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

ChatControlRed version 10.27.7

### Optional: "/chc debug" file

You can use old debug file that i sent from office@serb-craft.com

### Steps to reproduce

- /msg a player that is on the server with you
- Player is online with me on server but it says that he is not online at all
- The problem is not with all players, some you can msg and some you cant

Maybe its connected with Bungee issue from last ticket. https://prnt.sc/oo9vcOw3Fm4S

https://github.com/kangarko/ChatControl-Red/issues/2785

**Comment by kangarko** [comment]
Should already have been fixed in the current release, sorry for forgetting to answer here! Let us know below if you got any other questions or issues.
