### ISSUE TITLE
Version: Purpur(2176) 1.20.4-R0.1-SNAPSHOT- File not found!

### ISSUE THREAD

**Issue by smscentras** [kangarko/ChatControl#2791]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.27.8

### Optional: "/chc debug" file

[ChatControlRed]  File not found: https://repo1.maven.org/maven2/com/alessiodp/libby/maven/resolver/libby-maven-resolver/1.0.1/libby-maven-resolver-1.0.1.jar

### Steps to reproduce

Start server.

**Comment by kangarko** [comment]
Should have already been solved in the current build. Thanks!
