### ISSUE TITLE
1.21: Null channel?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2794]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.8

### Optional: Error log

https://pastebin.com/nHyapCts

### Steps to reproduce

Hello, I don't know how to reproduce, but hopefully you'll have some idea what's going on there
![image](https://github.com/user-attachments/assets/633f3436-f298-4fd9-86e5-7ad6fc39cf60)
I have only these channels

**Comment by kangarko** [comment]
Should be fixed in today's version.
