### ISSUE TITLE
Could not pass event

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#2795]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.27.7

### Optional: Error log

https://pastebin.com/XgjAP6ZC

### Optional: "/chc debug" file

Server Version: 1.21.1 (Paper)

### Steps to reproduce

Its just spamming on my console.

**Comment by kangarko** [comment]
Please stay on 1.21 or update ChatControl (if the new version does not work you need to stay on 1.21 for the time being - we are actively rewriting the plugin and will ship a big update end of week or early next one)

**Comment by ghost** [comment]
Chatcontrol 10.27.8 is not working on 1.21. but 10.27.7 does. Okay I ll wait for the update while being spammed on console :)

**Comment by kangarko** [comment]
Gotcha. Still busy rewriting, will push it out as soon as I can.
