### ISSUE TITLE
1.16.5: Lag Problem

### ISSUE THREAD

**Issue by geumu** [kangarko/ChatControl#2796]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.7

### Steps to reproduce

Image: https://imgur.com/a/xiuJAQI

There seems to be some lag. I sent the spark report and debug file to your email.

**Comment by kangarko** [comment]
That's coming from the console command sender which is using your native OS kernel driver, unfortunately out of ChatControl's control.

**Comment by geumu** [comment]
> That's coming from the console command sender which is using your native OS kernel driver, unfortunately out of ChatControl's control.

Is there a way to disable logs in the console?

**Comment by kangarko** [comment]
That's not an issue with chatcontrol, every plugin calling logger will cause the server to lag unless you fix the root issue
