### ISSUE TITLE
1.16.5: An error is displayed in the console and the plugin cannot be used.

### ISSUE THREAD

**Issue by geumu** [kangarko/ChatControl#2797]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.8

### Optional: Error log

https://pastebin.com/dPj88eDL

### Optional: "/chc debug" file

Materials were sent by email.

### Steps to reproduce

An error is displayed in the console and the plugin cannot be used.

**Comment by kangarko** [comment]
Super strange, can you try deleting libraries/ folder from your root server folder while server is stopped and restarting?

**Comment by geumu** [comment]
**Explanation**: I installed the new Arclight and received the latest libraries. If you run the server with only one ChatControlRed, the console error below is displayed.
**Log**: https://pastebin.com/Zfry6tYi

**Comment by geumu** [comment]
Is there a way to disable logs in the console?

**Comment by kangarko** [comment]
Gotcha. Apologies for the issue, it's been long-since fixed on our end but we cant push the update yet due to some underlying work on our library. Will be pushing it out asap.
