### ISSUE TITLE
1.21: IllegalStateException

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2798]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.8

### Optional: Error log

https://pastebin.com/Aetekj2R

### Steps to reproduce

Hello, unfortunately I don't know, maybe the server was crashing

**Comment by bobhenl** [comment]
Wait there's a bit more, prob associated with rules?
https://hastebin.com/share/bizoruqaxe.makefile -> whole crash report
https://pastebin.com/prZEQCqN -> whole error.yml log part

**Comment by kangarko** [comment]
Please rollback to the previous version.
