### ISSUE TITLE
Version: 1.21 | Trying to hide Admin chat to normal ranks

### ISSUE THREAD

**Issue by brandonlea** [kangarko/ChatControl#2799]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### Question

Hello, I wanna hide Admin channel from normal rank and show it for my staff but when I do /ch it shows in the list even though it don't have permissions to join how can I fix this thank you.

Also how can I disable it saying You have joined x channel, You have left x channel as everyone can see it thank you.

![image](https://github.com/user-attachments/assets/ecf78e70-4858-4142-a0a6-88b61596842e)
![image](https://github.com/user-attachments/assets/03bf8da0-1817-4966-ac69-2b79bd768469)
![image](https://github.com/user-attachments/assets/737a9e08-40de-413c-92b4-842390c3a100)

**Comment by kangarko** [comment]
Make sure players dont have the chatcontrol.channel.join.admin.* nor chatcontrol.channel.leave.admin.* nor send permission.

To hide the two messages edit their key in localization/messages_en.yml by setting it to "none"
