### ISSUE TITLE
Essentials chat and chat control

### ISSUE THREAD

**Issue by AndGK** [kangarko/ChatControl#28]
So I set up essentials chat, with group prefixes, and etc. After installing chat control it's does not work even when this turned off:

Chat:
  Formatter:
    Enabled: false

please help!

**Comment by EvilOlaf** [comment]
You may use only one chat management plugin at the same time. Either EssentialsChat or ChatControl.

**Comment by kangarko** [comment]
False. You can use as many as you like as long as their functions are not overlapping/conflicting with each another.

In your case, just make sure the ´Chat.Formatter.Enabled´ is really set to ´false´, then it should no longer conflict with EssentialsChat.
Does it work when ChatControl is not present?

**Comment by AndGK** [comment]
> In your case, just make sure the ´Chat.Formatter.Enabled´ is really set to ´false´, then it should no longer conflict with EssentialsChat.

Where can I find this?

> Does it work when ChatControl is not present?

Yes it does.

**Comment by kangarko** [comment]
You're welcome, no problem!
