### ISSUE TITLE
Do not find permissions fochatcontrol

### ISSUE THREAD

**Issue by Cobzer** [kangarko/ChatControl#280]
Hello! I dont find any permissions for chatcontrol, and I got groupmanager, bt no groups can use it, if you dont have OP on the server. And I have tried to lookup, but do not find, Can you please help me out =)

Looking for those perms:

/Chc clear - and perms for bypass "Clearing" for staff
/chc fake join/leave

**Comment by kangarko** [comment]
Hey,

permissions are here: https://github.com/kangarko/ChatControl/blob/master/src/kangarko/chatcontrol/utils/Permissions.java

For clear: chatcontrol.commands.clear

For fake join and leave: chatcontrol.commands.fake
