### ISSUE TITLE
Added Naughty Words to the Naughty Word List

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#280]
I've added many naughties and put it in somewhat alphabetical order.

# Blocks 'anal'
match \b(a+(\W|\d|_)*n+(\W|\d|_)*a+(\W|\d|_)*l+(\W|\d|_)*)
ignore string analog|an all
group swear

# Blocks 'anus'
match \b(a+(\W|\d|_)*n+(\W|\d|_)*u+(\W|\d|_)*s+(\W|\d|_)*) 
group swear

# Blocks 'arse'
match \b(a+(\W|\d|_)*r+(\W|\d|_)*s+(\W|\d|_)*e+(\W|\d|_)*)
group swear

# Blocks 'arsehole'
match \b(a+(\W|\d|_)*r+(\W|\d|_)*s+(\W|\d|_)*e+(\W|\d|_)*h+(\W|\d|_)*o+(\W|\d|_)*l+(\W|\d|_)*e+(\W|\d|_)*)
group swear

# Blocks 'ass'
match \b(a+(\W|\d|_)*s+(\W|\d|_)*s+(\W|\d|_)*)
group swear

# Blocks 'ashole'
match \b(a+(\W|\d|_)*s+(\W|\d|_)*h+(\W|\d|_)*o+(\W|\d|_)*l+(\W|\d|_)*e+(\W|\d|_)*)
group swear

# Blocks 'ashol'
match \b(a+(\W|\d|_)*s+(\W|\d|_)*h+(\W|\d|_)*o+(\W|\d|_)*l+(\W|\d|_)*)
group swear

# Blocks 'asshole'
match \b(a+(\W|\d|_)*s+(\W|\d|_)*s+(\W|\d|_)*h+(\W|\d|_)*o+(\W|\d|_)*l+(\W|\d|_)*e+(\W|\d|_)*)
group swear

# Blocks 'bastard'
match \b(b+(\W|\d|_)*a+(\W|\d|_)*s+(\W|\d|_)*t+(\W|\d|_)*a+(\W|\d|_)*r+(\W|\d|_)*d+(\W|\d|_)*)
group swear

# Blocks 'bitch'
match \b(b+(\W|\d|_)*i+(\W|\d|_)*t+(\W|\d|_)*c+(\W|\d|_)*h+(\W|\d|_)*)
group swear

# Blocks 'bltch'
match \b(b+(\W|\d|_)*l+(\W|\d|_)*t+(\W|\d|_)*c+(\W|\d|_)*h+(\W|\d|_)*)
group swear

# Blocks 'b1tch'
match \b(b+(\W|\d|_)*1+(\W|\d|_)*t+(\W|\d|_)*c+(\W|\d|_)*h+(\W|\d|_)*)
group swear

# Blocks 'boner'
match \b(b+(\W|\d|_)*o+(\W|\d|_)*n+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)
group swear

# Blocks 'chinkie'
match \b(c+(\W|\d|_)*h+(\W|\d|_)*i+(\W|\d|_)*n+(\W|\d|_)*k+(\W|\d|_)*i+(\W|\d|_)*e+(\W|\d|_)*)
group swear

# Blocks 'chinky'
match \b(c+(\W|\d|_)*h+(\W|\d|_)*i+(\W|\d|_)*n+(\W|\d|_)*k+(\W|\d|_)*y+(\W|\d|_)*)
group swear

# Blocks 'cock'
match \b(c+(\W|\d|_)*o+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
group swear

# Blocks 'c0ck'
match \b(c+(\W|\d|_)*0+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
group swear

# Blocks 'cum'
match \b(c+(\W|\d|_)*u+(\W|\d|_)*m+(\W|\d|_)*) 
group swear

# Blocks 'cunt'
match \b(c+(\W|\d|_)*u+(\W|\d|_)*n+(\W|\d|_)*t+(\W|\d|_)*)
group swear

# Blocks 'cunty'
match \b(c+(\W|\d|_)*u+(\W|\d|_)*n+(\W|\d|_)*t+(\W|\d|_)*y+(\W|\d|_)*)
group swear

# Blocks 'cvnt'
match \b(c+(\W|\d|_)*v+(\W|\d|_)*n+(\W|\d|_)*t+(\W|\d|_)*)
group swear

# Blocks 'dafuq'
match \b(d+(\W|\d|_)*a+(\W|\d|_)*f+(\W|\d|_)*u+(\W|\d|_)*q+(\W|\d|_)*) 
group swear

# Blocks 'darkie'
match \b(d+(\W|\d|_)*a+(\W|\d|_)*r+(\W|\d|_)*k+(\W|\d|_)*i+(\W|\d|_)*e+(\W|\d|_)*)
group swear

# Blocks 'darkey'
match \b(d+(\W|\d|_)*a+(\W|\d|_)*r+(\W|\d|_)*k+(\W|\d|_)*e+(\W|\d|_)*y+(\W|\d|_)*)
group swear

# Blocks 'darky'
match \b(d+(\W|\d|_)*a+(\W|\d|_)*r+(\W|\d|_)*k+(\W|\d|_)*y+(\W|\d|_)*)
group swear

# Blocks 'dick'
match \b(d+(\W|\d|_)*i+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
group swear

# Blocks 'dickhead'
match \b(d+(\W|\d|_)*i+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*h+(\W|\d|_)*e+(\W|\d|_)*a+(\W|\d|_)*d+(\W|\d|_)*)
group swear

# Blocks 'dildo'
match \b(d+(\W|\d|_)*i+(\W|\d|_)*l+(\W|\d|_)*d+(\W|\d|_)*o+(\W|\d|_)*) 
group swear

# Blocks 'douche'
match \b(d+(\W|\d|_)*o+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*h+(\W|\d|_)*e+(\W|\d|_)*)
group swear

# Blocks 'fag'
match \b(f+(\W|\d|_)*a+(\W|\d|_)*g+(\W|\d|_)*) 
group swear

# Blocks 'faggot'
match \b(f+(\W|\d|_)*a+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*o+(\W|\d|_)*t+(\W|\d|_)*) 
group swear

# Blocks 'fcuk'
match \b(f+(\W|\d|_)*c+(\W|\d|_)*u+(\W|\d|_)*k+(\W|\d|_)*)
group swear

# Blocks 'ffs'
match \b(f+(\W|\d|_)*f+(\W|\d|_)*s+(\W|\d|_)*) 
group swear

# Blocks 'fuck'
match \b(f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
group swear

# Blocks 'gay'
match \b(g+(\W|\d|_)*a+(\W|\d|_)*y+(\W|\d|_)*)
group swear

# Blocks 'heil'
match \b(h+(\W|\d|_)*e+(\W|\d|_)*i+(\W|\d|_)*l+(\W|\d|_)*)
group swear

# Blocks 'homo'
#match \b(h+(\W|\d|_)*o+(\W|\d|_)*m+(\W|\d|_)*o+(\W|\d|_)*)
#group swear

# Blocks 'homosexual'
match \b(h+(\W|\d|_)*o+(\W|\d|_)*m+(\W|\d|_)*o+(\W|\d|_)*s+(\W|\d|_)*e+(\W|\d|_)*x+(\W|\d|_)*u+(\W|\d|_)*a+(\W|\d|_)*l+(\W|\d|_)*)
group swear

# Blocks 'horny'
match \b(h+(\W|\d|_)*o+(\W|\d|_)*r+(\W|\d|_)*n+(\W|\d|_)*y+(\W|\d|_)*)
group swear

# Blocks 'hentai'
match \b(h+(\W|\d|_)*e+(\W|\d|_)*n+(\W|\d|_)*t+(\W|\d|_)*a+(\W|\d|_)*i+(\W|\d|_)*)
group swear

# Blocks 'intercourse'
match \b(i+(\W|\d|_)*n+(\W|\d|_)*t+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*c+(\W|\d|_)*o+(\W|\d|_)*u+(\W|\d|_)*r+(\W|\d|_)*s+(\W|\d|_)*e+(\W|\d|_)*)
group swear

# Blocks 'jerk'
match \b(j+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*k+(\W|\d|_)*)
group swear

# Blocks 'kkk'
match \b(k+(\W|\d|_)*k+(\W|\d|_)*k+(\W|\d|_)*)
group swear

# Blocks 'lesbian'
match \b(l+(\W|\d|_)*e+(\W|\d|_)*s+(\W|\d|_)*b+(\W|\d|_)*i+(\W|\d|_)*a+(\W|\d|_)*n+(\W|\d|_)*)
group swear

# Blocks 'milf'
match \b(m+(\W|\d|_)*i+(\W|\d|_)*l+(\W|\d|_)*f+(\W|\d|_)*) 
group swear

# Blocks 'niger'
match \b(n+(\W|\d|_)*i+(\W|\d|_)*g+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)
group swear

# Blocks 'niga'
match \b(n+(\W|\d|_)*i+(\W|\d|_)*g+(\W|\d|_)*a+(\W|\d|_)*)
group swear

# Blocks 'nigga'
match \b(n+(\W|\d|_)*i+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*a+(\W|\d|_)*)
group swear

# Blocks 'ni99a'
match \b(n+(\W|\d|_)*i+(\W|\d|_)*9+(\W|\d|_)*9+(\W|\d|_)*a+(\W|\d|_)*)
group swear

# Blocks 'nigger'
match \b(n+(\W|\d|_)*i+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)
group swear

# Blocks 'ni99er'
match \b(n+(\W|\d|_)*i+(\W|\d|_)*9+(\W|\d|_)*9+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)
group swear

# Blocks 'packy'
match \b(p+(\W|\d|_)*a+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*y+(\W|\d|_)*)
group swear

# Blocks 'pedo'
match \b(p+(\W|\d|_)*e+(\W|\d|_)*d+(\W|\d|_)*o+(\W|\d|_)*) 
group swear

# Blocks 'penis'
match \b(p+(\W|\d|_)*e+(\W|\d|_)*n+(\W|\d|_)*i+(\W|\d|_)*s+(\W|\d|_)*)
group swear

# Blocks 'piss'
match \b(p+(\W|\d|_)*i+(\W|\d|_)*s+(\W|\d|_)*s+(\W|\d|_)*)
group swear

# Blocks 'prick'
match \b(p+(\W|\d|_)*r+(\W|\d|_)*i+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
group swear

# Blocks 'prostitute'
match \b(p+(\W|\d|_)*r+(\W|\d|_)*o+(\W|\d|_)*s+(\W|\d|_)*t+(\W|\d|_)*i+(\W|\d|_)*t+(\W|\d|_)*u+(\W|\d|_)*t+(\W|\d|_)*e+(\W|\d|_)*) 
group swear

# Blocks 'pussy'
match \b(p+(\W|\d|_)*u+(\W|\d|_)*s+(\W|\d|_)*s+(\W|\d|_)*y+(\W|\d|_)*)
group swear

# Blocks 'queer'
match \b(q+(\W|\d|_)*u+(\W|\d|_)*e+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)
group swear

# Blocks 'rape'
match \b(r+(\W|\d|_)*a+(\W|\d|_)*p+(\W|\d|_)*e+(\W|\d|_)*)
group swear

# Blocks 'rapist'
match \b(r+(\W|\d|_)*a+(\W|\d|_)*p+(\W|\d|_)*i+(\W|\d|_)*s+(\W|\d|_)*t+(\W|\d|_)*)
group swear

# Blocks 'retard'
match \b(r+(\W|\d|_)*e+(\W|\d|_)*t+(\W|\d|_)*a+(\W|\d|_)*r+(\W|\d|_)*d+(\W|\d|_)*) 
group swear

# Blocks 'r3tard'
match \b(r+(\W|\d|_)*3+(\W|\d|_)*t+(\W|\d|_)*a+(\W|\d|_)*r+(\W|\d|_)*d+(\W|\d|_)*) 
group swear

# Blocks 'reetard'
match \b(r+(\W|\d|_)*e+(\W|\d|_)*e+(\W|\d|_)*t+(\W|\d|_)*a+(\W|\d|_)*r+(\W|\d|_)*d+(\W|\d|_)*) 
group swear

# Blocks 'sex'
match \b(s+(\W|\d|_)*e+(\W|\d|_)*x+(\W|\d|_)*)
group swear

# Blocks 'shit'
match \b(s+(\W|\d|_)*h+(\W|\d|_)*i+(\W|\d|_)*t+(\W|\d|_)*)
group swear

# Blocks 'slut'
match \b(s+(\W|\d|_)*l+(\W|\d|_)*u+(\W|\d|_)*t+(\W|\d|_)*)
group swear

# Blocks 'slag'
match \b(s+(\W|\d|_)*l+(\W|\d|_)*a+(\W|\d|_)*g+(\W|\d|_)*)
group swear

# Blocks 'sperm'
match \b(s+(\W|\d|_)*p+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*m+(\W|\d|_)*) 
group swear

# Blocks 'spunk'
match \b(s+(\W|\d|_)*p+(\W|\d|_)*u+(\W|\d|_)*n+(\W|\d|_)*k+(\W|\d|_)*) 
group swear

# Blocks 'tard'
match \b(t+(\W|\d|_)*a+(\W|\d|_)*r+(\W|\d|_)*d+(\W|\d|_)*)
ignore string title
group swear

# Blocks 'testicle'
match \b(t+(\W|\d|_)*e+(\W|\d|_)*s+(\W|\d|_)*t+(\W|\d|_)*i+(\W|\d|_)*c+(\W|\d|_)*l+(\W|\d|_)*e+(\W|\d|_)*) 
group swear

# Blocks 'titt'
match \b(t+(\W|\d|_)*i+(\W|\d|_)*t+(\W|\d|_)*(t|s)+(\W|\d|_)*)
ignore string title
group swear

# Blocks 'tosser'
match \b(t+(\W|\d|_)*o+(\W|\d|_)*s+(\W|\d|_)*s+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)
group swear

# Blocks 'twat'
match \b(t+(\W|\d|_)*w+(\W|\d|_)*a+(\W|\d|_)*t+(\W|\d|_)*)
group swear

# Blocks 'vagina'
match \b(v+(\W|\d|_)*a+(\W|\d|_)*g+(\W|\d|_)*i+(\W|\d|_)*n+(\W|\d|_)*a+(\W|\d|_)*)
group swear

# Blocks 'wanker'
match \b(w+(\W|\d|_)*a+(\W|\d|_)*n+(\W|\d|_)*k+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)
group swear

# Blocks 'whalecum'
match \b(w+(\W|\d|_)*h+(\W|\d|_)*a+(\W|\d|_)*l+(\W|\d|_)*e+(\W|\d|_)*c+(\W|\d|_)*u+(\W|\d|_)*m+(\W|\d|_)*)
group swear

# Blocks 'whitey'
match \b(w+(\W|\d|_)*h+(\W|\d|_)*i+(\W|\d|_)*t+(\W|\d|_)*e+(\W|\d|_)*y+(\W|\d|_)*)
group swear

# Blocks 'whore'
match \b(w+(\W|\d|_)*h+(\W|\d|_)*o+(\W|\d|_)*r+(\W|\d|_)*e+(\W|\d|_)*)
group swear

# Blocks 'wtf'
match \b(w+(\W|\d|_)*t+(\W|\d|_)*f+(\W|\d|_)*) 
group swear

**Comment by 00Hrtz** [comment]
I was reluctant to paste this but as you've requested i do so here, here it is.

**Comment by kangarko** [comment]
Thanks so much!
