### ISSUE TITLE
1.21.1: Death messages not being transferred from another server to Discord

### ISSUE THREAD

**Issue by BAD7777** [kangarko/ChatControl#2800]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

ChatControlRed version 10.27.8

### Steps to reproduce

Death messages are not being transferred to Discord from one of the servers. On one server where DiscordSRV is installed, the messages are successfully sent to the designated Discord channel. However, on another server, the messages are not being sent at all, despite identical configurations.

**Comment by kangarko** [comment]
Wontfix for now, low priority bug until ChatControl 11 is out. Thanks for your understanding.
