### ISSUE TITLE
Version: 1.20.1

### ISSUE THREAD

**Issue by naberlo** [kangarko/ChatControl#2801]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### Question

Hello i'm using velocity and paper server but the plugin is only at my paper server. When I try to join a channel i get an error. "Player <playername> is not connected trough BungeeCord."

**Comment by kangarko** [comment]
Please follow our installation guide here: https://github.com/kangarko/ChatControl-Red/wiki/Installation
