### ISSUE TITLE
1.21 + ChatControl = No Skins

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2806]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.27.8

### Steps to reproduce

Download any 1.21 build and use currently the latest CHC version. Also use another plugin that is depending on CHC.

The temporary fix to this issue is to either remove CHC or the plugin relying on CHC (we use it for clan chat).

The issue works like this:
1. Join with PlayerA
2. Join with PlayerB
3. Result: PlayerA can see skin of PlayerB, but PlayerB cannot see skin of PlayerA.

![image](https://github.com/user-attachments/assets/b408801d-7355-4471-af27-3aafe505e393)

![image](https://github.com/user-attachments/assets/44523e51-41be-4b03-b8f5-1bb9392d0161)

**Comment by Teslicek** [comment]
Update:

Might be actually fully caused by our own plugin. Will investigate.

**Comment by Teslicek** [comment]
99% caused by our own plugin. It was just a coincidence it relied on ChatControl.

**Comment by kangarko** [comment]
Odd indeed. Thanks for investigating. Also today's new chatcontrol will support 1.21.1 fully.
