### ISSUE TITLE
1.21.1: Is not working with latest protocollib

### ISSUE THREAD

**Issue by pjindras** [kangarko/ChatControl#2807]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.8

### Optional: Error log

https://paste.gg/p/anonymous/af1bf486bd0446428568b8947dc2e329

### Steps to reproduce

IDK its totaly broken after update. Sometimes it cannot start, /msg is broken for some players etc.

**Comment by pjindras** [comment]
mc 1.21.1

**Comment by kangarko** [comment]
Thanks, will be fixed in the next version.
