### ISSUE TITLE
New IA in development causing troubles for CCR

### ISSUE THREAD

**Issue by PSYCHEER** [kangarko/ChatControl#2809]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.7

### Optional: Error log

https://pastebin.com/mhc3fAML

### Steps to reproduce

Lone is working on new version of IA and seems then the IA class in replicateutil will be obsolete as it will be released

Pls fix

**Comment by kangarko** [comment]
Thanks, beautiful, will be updating shortly.

**Comment by nhanledev** [comment]
any update on this?

**Comment by kangarko** [comment]
No ETA yet, will be shipped in ChatControl 11. Lets track progress at https://github.com/PluginBugs/Issues-ItemsAdder/issues/3801#issuecomment-2336794776
