### ISSUE TITLE
Server thread 7.29% - is consuming a lot! (Purpur: latest MC: 1.21.1)

### ISSUE THREAD

**Issue by GG-MD** [kangarko/ChatControl#2810]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.27.8

### Optional: "/chc debug" file

```
chc debug:
https://ufile.io/pl1rm7ct

I want to continue to use your plugin, because I consider it a leader, but such a load I have never seen before, as online such a number of did not have with your plugin, please do something about it, otherwise we will have to leave you (which we do not want).
Spark profiler: https://spark.lucko.me/pQvB7REcL9
```

### Steps to reproduce

unknown, just players socializing, playing, new players coming in AND so on.

**Comment by GG-MD** [comment]
Please help us, tell us what to do? @kangarko

**Comment by GG-MD** [comment]
And another report!....
https://spark.lucko.me/74yFmQL99F

**Comment by kangarko** [comment]
You have a lot of traffic and using a file storage, which is inherently slow. 

Pleas sSwitch to MySQL with HikariCP enabled. In the next major ChatControl update I will make these changes as default since we've got a lot of reports of file storage being slow, but that is inherit to its nature. 

Thanks for the report!

**Comment by broken1arrow** [comment]
> You have a lot of traffic and using a file storage, which is inherently slow.
> 
> Pleas sSwitch to MySQL with HikariCP enabled. In the next major ChatControl update I will make these changes as default since we've got a lot of reports of file storage being slow, but that is inherit to its nature.
> 
> Thanks for the report!

I don't remember if you offer SQLite support or not, but if you shall do the change to force on SQL. I strongly recommend you set SQLite as standard (you can use HikariCP with that option) or even using H2 database as it have almost same feature set as MySQL and claims to be faster than SQLite. It is not a big difference how to use either SQLite or H2 database.

**Comment by GG-MD** [comment]
> You have a lot of traffic and using a file storage, which is inherently slow. 
> 
> 
> 
> Pleas sSwitch to MySQL with HikariCP enabled. In the next major ChatControl update I will make these changes as default since we've got a lot of reports of file storage being slow, but that is inherit to its nature. 
> 
> 
> 
> Thanks for the report!

**You're telling me to use MySQL. 
you do realize that if I change the storage type, nothing will practically change, because you didn't make an async thread for it!?**
@kangarko @broken1arrow

**Comment by broken1arrow** [comment]
> > You have a lot of traffic and using a file storage, which is inherently slow.
> > Pleas sSwitch to MySQL with HikariCP enabled. In the next major ChatControl update I will make these changes as default since we've got a lot of reports of file storage being slow, but that is inherit to its nature.
> > Thanks for the report!
> 
> **You're telling me to use MySQL. you do realize that if I change the storage type, nothing will practically change, because you didn't make an async thread for it!?** @kangarko @broken1arrow

The MySQL saving should be async if he have not miss something.

**Comment by kangarko** [comment]
Today, using a database driver such as MySQL is done async in ChatControl. Using file storage is done sync. 

If you start using mysql.yml, you will experience a performance improvement.

In the upcoming ChatControl 11, I will get rid of the data.db (which is a yaml underneath) and use a database driver by default, either SQLite or H2, anything your OS supports. This will make the plugin high performance by design, and all necessary calls will be made async. ETA is 1-3 weeks.

**Comment by GG-MD** [comment]
> Today, using a database driver such as MySQL is done async in ChatControl. Using file storage is done sync.
> 
> If you start using mysql.yml, you will experience a performance improvement.
> 
> In the upcoming ChatControl 11, I will get rid of the data.db (which is a yaml underneath) and use a database driver by default, either SQLite or H2, anything your OS supports. This will make the plugin high performance by design, and all necessary calls will be made async. ETA is 1-3 weeks.

I didn't notice it worked in the async stream for fuck's sake!
Read it : https://github.com/kangarko/ChatControl-Red/issues/2814

**Comment by broken1arrow** [comment]
> > Today, using a database driver such as MySQL is done async in ChatControl. Using file storage is done sync.
> > If you start using mysql.yml, you will experience a performance improvement.
> > In the upcoming ChatControl 11, I will get rid of the data.db (which is a yaml underneath) and use a database driver by default, either SQLite or H2, anything your OS supports. This will make the plugin high performance by design, and all necessary calls will be made async. ETA is 1-3 weeks.
> 
> I didn't notice it worked in the async stream for fuck's sake! Read it : #2814

It doesn't seem like it's same issue. 

Remember when you fix biggest performance problem, can a underlaying issue be visible. 

What I mean is your biggest performance drain hide your second issue. 

Fix performance issues is not like push a button, as number of players, server performance, operating system and other plugins using your API. 

Just the shear number of setting that some take more resources than others.

**Comment by kangarko** [comment]
Answered on the other ticket.
