### ISSUE TITLE
Regex generation to use ``[\W\d_]`` instead of ``(\W|\d|_)``

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2812]
# Summary

## This suggestion is regarding 
- https://app.mineacademy.org/chatcontrol-rules-generator
- In-game command ``/chc rule create``

With the suggestion that the Regular Expressions made via these methods use ``[\W\d_]`` instead of ``(\W|\d|_)`` 

It does the same thing but requires fewer steps, therefore less processing power is needed!
By replacing ``(\W|\d|_)`` to ``[\W\d_]`` you can improve performance!

---
## See below for an example of the increase in performance!

**BEFORE CHANGES**
![image](https://github.com/user-attachments/assets/5cb58cd1-1c81-4799-af98-9c8eae5692f0)

**AFTER CHANGES**
![image](https://github.com/user-attachments/assets/36807114-62c7-4875-bb24-f85a565ffd19)

**Comment by TheIntolerant** [comment]
For more context! This simple change can decrease the number of steps needed to be completed by around 50-60% which I believe everyone would appreciate!

**Comment by kangarko** [comment]
AMAZING discovery and I will be more than happy to implement this!
