### ISSUE TITLE
10.27.9: MSG commands are not loaded correctly

### ISSUE THREAD

**Issue by pjindras** [kangarko/ChatControl#2813]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.9

### Optional: Error log

no error in console

### Steps to reproduce

I use minecraft 1.21.1 and when I start server, chatcontrol /msg commands are not working and in game are used vanilla commands.
After using /chc reload plugin reloads without error and than the chatcontrol commands /msg etc. works fine.

There must be some problem just in server start, it loads vanilla minecraft commands instead of those.

**Comment by pjindras** [comment]
@kangarko problém stále přetrvává, po restartu to prostě neloadne ty /msg /whisper commandy a musím udělat /chc reload abych je mohl použít

**Comment by kangarko** [comment]
Ahoj, skús novú verziu ktorý vydám dnes večer. Ak to stále nepôjde, prosím, nahraj mi svoj /chc debug zip

**Comment by pjindras** [comment]
> Ahoj, skús novú verziu ktorý vydám dnes večer. Ak to stále nepôjde, prosím, nahraj mi svoj /chc debug zip

Stále ten stejný problém, posílám debug
[debug.zip](https://github.com/user-attachments/files/16975898/debug.zip)

**Comment by kangarko** [comment]
1. Skús pridať nejaký custom alias do Private_Messages.Tell_Aliases v settings.yml napr /sprava a pozri sa, či ten funguje hneď po reštarte. Tiež prosím nepoužívaj /reload alebo plugmanx na chatcontrol pretože tie môžu robiť tieto veci. 

2. Over že nemáš nič v commands.yml v hlavnej zložke servera, žiaden príkaz ktorý je už v Tell_Aliases.

3. Tiež, pozerám že tam máš dosť pluginov, vieš vytvoriť kópiu serveru kde bude iba ChatControl? Aby sme zistili či to nie je nejakým iným pluginom, a potom odporúčam vypínať jeden po jednom až dokým nenájdeš ten ktorý to spôsobuje, a tak sa vieš opýtať jeho vývojara ako ho prestaviť. 

Pointa je, 99% som si istý že je to nejakým iným pluginom. My už máme výnimku pre Towny, ak sa ti podarí zistiť o aký plugin sa jedná vieš ho buď upraviť manuálne editovaním jeho plugin.yml v jar súbore, alebo viem pridať ďalšiu výnimku.

**Comment by pjindras** [comment]
> 1. Skús pridať nejaký custom alias do Private_Messages.Tell_Aliases v settings.yml napr /sprava a pozri sa, či ten funguje hneď po reštarte. Tiež prosím nepoužívaj /reload alebo plugmanx na chatcontrol pretože tie môžu robiť tieto veci.
> 2. Over že nemáš nič v commands.yml v hlavnej zložke servera, žiaden príkaz ktorý je už v Tell_Aliases.
> 3. Tiež, pozerám že tam máš dosť pluginov, vieš vytvoriť kópiu serveru kde bude iba ChatControl? Aby sme zistili či to nie je nejakým iným pluginom, a potom odporúčam vypínať jeden po jednom až dokým nenájdeš ten ktorý to spôsobuje, a tak sa vieš opýtať jeho vývojara ako ho prestaviť.
> 
> Pointa je, 99% som si istý že je to nejakým iným pluginom. My už máme výnimku pre Towny, ak sa ti podarí zistiť o aký plugin sa jedná vieš ho buď upraviť manuálne editovaním jeho plugin.yml v jar súbore, alebo viem pridať ďalšiu výnimku.

V command.yml nemám nic.
```

  Tell_Aliases:
  - 'tell'
  - 'w'
  - 'm'
  - 't'
  - 'message'
  - 'msg'
  - 'whisper'
  - 'pm'
  
  # The reply command aliases.
  # EDIT AS YOU WISH BUT THERE MUST BE AT LEAST ONE ALIAS
  Reply_Aliases:
  - 'reply'
  - 'r'
```

/m apod. co je v těchto aliasech ale ne v MC ani essentials apod. jde vpořádku, jak jsi psal (s tím /sprava)

Teoreticky mě napadá essentials nebo interactive chat, něco takového.

Můžeme to tedy zkusit otestovat cca plugin po pluginu jestli zjistíme, čím to je, ale děje se nám to na všech serverech i s méně pluginy. Vyzkoušíme a dám pak vědět.

**Comment by pjindras** [comment]
> 1. Skús pridať nejaký custom alias do Private_Messages.Tell_Aliases v settings.yml napr /sprava a pozri sa, či ten funguje hneď po reštarte. Tiež prosím nepoužívaj /reload alebo plugmanx na chatcontrol pretože tie môžu robiť tieto veci.
> 2. Over že nemáš nič v commands.yml v hlavnej zložke servera, žiaden príkaz ktorý je už v Tell_Aliases.
> 3. Tiež, pozerám že tam máš dosť pluginov, vieš vytvoriť kópiu serveru kde bude iba ChatControl? Aby sme zistili či to nie je nejakým iným pluginom, a potom odporúčam vypínať jeden po jednom až dokým nenájdeš ten ktorý to spôsobuje, a tak sa vieš opýtať jeho vývojara ako ho prestaviť.
> 
> Pointa je, 99% som si istý že je to nejakým iným pluginom. My už máme výnimku pre Towny, ak sa ti podarí zistiť o aký plugin sa jedná vieš ho buď upraviť manuálne editovaním jeho plugin.yml v jar súbore, alebo viem pridať ďalšiu výnimku.

Tak je tam konflikt s Essentials X na 1.21.1

Verze, kterou používáme: 2.20.1 release
posílám rovnou i config. https://pastebin.com/aXKaA15K

Všechny ty commandy jsou tam vypnuté (v disabled commands, ale je možné, že na 1.21.1 je to broken nebo nějak jinak, dřív to šlo normálně a nic se neměnilo).

**Comment by kangarko** [comment]
Skus ich vymazat s disabled commands. Ak to nepomoze, otvor EssentialsX.jar, najdi tie prikazy v sekcii commands a vymaz celu sekciu. V ChatControl 11 by to uz nemalo robit.
