### ISSUE TITLE
main server thread overloaded CMI [v. latest]

### ISSUE THREAD

**Issue by GG-MD** [kangarko/ChatControl#2814]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.27.9

### Optional: Error log

-

### Steps to reproduce

You recommended to me here that I use MySQL, earlier ([issue](https://github.com/kangarko/ChatControl-Red/issues/2810#issuecomment-2320130020)). But that didn't help either, hikari cp true, using mariadb. The main problem is that you claim to be the best coding training studio. As my coder who we have been working with for many years says:
> “any requests to any storage should be done from async thread. Changing the storage from files to MySql, but leaving the logic in the async stream, will not change the situation, or will change very little”

profiler: https://spark.lucko.me/gC6Z9dp6ux
`(/spark profiler start --only-ticks-over 135)`

_How long do we have to wait for the fixes? 
If it takes longer than 7 days, I will then leave your plugin immediately, please let me know._

<img width="919" alt="image" src="https://github.com/user-attachments/assets/64664c58-0a71-4779-9a0c-6a0bae93f10f">

**Comment by GG-MD** [comment]
**It's a shit plugin. I don't recommend it to anyone. Your performance will suffer forever, the coder is crooked.** Assessment I left everywhere, acquaintances will also leave, good luck.
<img width="1131" alt="image" src="https://github.com/user-attachments/assets/7a8d472b-ae30-4839-b46f-f0ec47505294">

new spark profiler: https://spark.lucko.me/C5JJXj8RxB

**Comment by broken1arrow** [comment]
> ### Are you using MySQL?
> 
> Yes
> ### Are you using a proxy?
> 
> No
> ### "/version ChatControlRed" - plugin version
> 
> 10.27.9
> ### Optional: Error log
> 
> 
> ### Optional: "/chc debug" file
> 
> _No response_
> ### Steps to reproduce
> 
> You recommended to me here that I use MySQL, earlier ([issue](https://github.com/kangarko/ChatControl-Red/issues/2810#issuecomment-2320130020)). But that didn't help either, hikari cp true, using mariadb. The main problem is that you claim to be the best coding training studio. As my coder who we have been working with for many years says:
> 
> > “any requests to any storage should be done from async thread. Changing the storage from files to MySql, but leaving the logic in the async stream, will not change the situation, or will change very little”
> 
> profiler: https://spark.lucko.me/gC6Z9dp6ux `(/spark profiler start --only-ticks-over 135)`
> 



I see, the commit from your developer clear up what you mean. I can't say exactly how he built the system around the send message, but either way when you fix the issue with the database, you did now revealed more clearly another issue (can't say if it is linked to the database or not), but it shows it is costly to send messages. 

What for placeholders and text do you send with every message to player? Do you using JavaScript?

> “any requests to any storage should be done from async thread. Changing the storage from files to MySql, but leaving the logic in the async stream, will not change the situation, or will change very little”

**Comment by GG-MD** [comment]
> I see, the commit from your developer clear up what you mean. I can't say exactly how he built the system around the send message, but either way when you fix the issue with the database, you did now revealed more clearly another issue (can't say if it is linked to the database or not), but it shows it is costly to send messages.
What for placeholders and text do you send with every message to player? Do you using JavaScript?

You really can't tell from the reports?! Even I understand a lot of things already.
Think better if you're the developer of this shit.

Tip:
<img width="894" alt="image" src="https://github.com/user-attachments/assets/f76cb3cc-36ef-415a-9fbb-98c616337623">

**Comment by broken1arrow** [comment]
> > I see, the commit from your developer clear up what you mean. I can't say exactly how he built the system around the send message, but either way when you fix the issue with the database, you did now revealed more clearly another issue (can't say if it is linked to the database or not), but it shows it is costly to send messages.
> > What for placeholders and text do you send with every message to player? Do you using JavaScript?
> 
> You really can't tell from the reports?! Even I understand a lot of things already. Think better if you're the developer of this shit.
> 
>

I'm not the developer, I just trying to understand your situation. 

If I am to interpret, the problem laying in when message is sent to server. High chance when translate the raw message and all placeholders is translated to a value + JavaScript (if you use placeholders with just JavaScript) and also hex colors specially gradients is costly. 

As I not the developer of this plugin, I don't know exact how he handle each part and keep in mind some placeholders can't be set async.

**Comment by GG-MD** [comment]
> > > I see, the commit from your developer clear up what you mean. I can't say exactly how he built the system around the send message, but either way when you fix the issue with the database, you did now revealed more clearly another issue (can't say if it is linked to the database or not), but it shows it is costly to send messages.
> > > What for placeholders and text do you send with every message to player? Do you using JavaScript?
> > 
> > 
> > You really can't tell from the reports?! Even I understand a lot of things already. Think better if you're the developer of this shit.
> 
> I'm not the developer, I just trying to understand your situation.
> 
> If I am to interpret, the problem laying in when message is sent to server. High chance when translate the raw message and all placeholders is translated to a value + JavaScript (if you use placeholders with just JavaScript) and also hex colors specially gradients is costly.
> 
> As I not the developer of this plugin, I don't know exact how he handle each part and keep in mind some placeholders can't be set async.

```
/channel send global
 message by player, using the symbol ! 
```

zip archive plugin.
https://file.io/tcaB5oJD702b

**Comment by CodingWithAnxiety** [comment]
> > I see, the commit from your developer clear up what you mean. I can't say exactly how he built the system around the send message, but either way when you fix the issue with the database, you did now revealed more clearly another issue (can't say if it is linked to the database or not), but it shows it is costly to send messages.
> > What for placeholders and text do you send with every message to player? Do you using JavaScript?
> 
> You really can't tell from the reports?! Even I understand a lot of things already. Think better if you're the developer of this shit.
> 
> Tip: <img alt="image" width="894" src="https://private-user-images.githubusercontent.com/178586019/364497850-f76cb3cc-36ef-415a-9fbb-98c616337623.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MzYwODUsIm5iZiI6MTcyNTczNTc4NSwicGF0aCI6Ii8xNzg1ODYwMTkvMzY0NDk3ODUwLWY3NmNiM2NjLTM2ZWYtNDE1YS05ZmJiLTk4YzYxNjMzNzYyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QxOTAzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTVlMDE3Yzk3NzJlYzZlM2NkZWIyMjUwZjJkZWNmZjhjMDAzMWVmZTRlY2E4ZmY5ZDk2ZDNhMjQ1MzU2NTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2OY1B5XgbIh3scaqbGpsv7jxxyjUZXK06okAzRTJvx8">

I've used CCRED for some time, and I've never had the performance issues you speak of.

On that note, can you _please_ be civil, especially on the github page? I understand your frustration-- seriously, I do, but also-- there's legitimately no reason to be hostile on here, especially to another person simply trying to understand your situation.

**Comment by kangarko** [comment]
If it is a shit plugin then stop using it immediately.

Our database queries are async by default, and they do not show up in the new spark report.

The spart report from your initial message points to some delay in how ProtocolLib decodes the message. The easiest fix is to set Integration.ProtocolLib.Listen_For_Packets to false in settings.yml. You will lose access to the [X] feature and packet rules, all other things will remain.

In the upcoming ChatControl 11 we'll speed up the packet manipulation thanks to native Adventure support. However I can't speak for ProtocolLib, we got other reports too complaining of its performance, I might need to switch to PacketEvents or have it disabled by default.

**Comment by CodingWithAnxiety** [comment]
> If it is a shit plugin then stop using it immediately.
> 
> Our database queries are async by default, and they do not show up in the new spark report.
> 
> The spart report from your initial message points to some delay in how ProtocolLib decodes the message. The easiest fix is to set Integration.ProtocolLib.Listen_For_Packets to false in settings.yml. You will lose access to the [X] feature and packet rules, all other things will remain.
> 
> In the upcoming ChatControl 11 we'll speed up the packet manipulation thanks to native Adventure support. However I can't speak for ProtocolLib, we got other reports too complaining of its performance, I might need to switch to PacketEvents or have it disabled by default.

I think disabled by default would be a sane default. Protocollib is something that I think only more advanced users will use. I'd like to stay, generally speaking, protocol lip integration does decrease the performance of certain events in a lot of chat programs-- this isn't a CC-red issue

**Comment by GG-MD** [comment]
> If it is a shit plugin then stop using it immediately.
> 
> Our database queries are async by default, and they do not show up in the new spark report.
> 
> The spart report from your initial message points to some delay in how ProtocolLib decodes the message. The easiest fix is to set Integration.ProtocolLib.Listen_For_Packets to false in settings.yml. You will lose access to the [X] feature and packet rules, all other things will remain.
> 
> In the upcoming ChatControl 11 we'll speed up the packet manipulation thanks to native Adventure support. However I can't speak for ProtocolLib, we got other reports too complaining of its performance, I might need to switch to PacketEvents or have it disabled by default.

I'm glad your response is adequate, I'll check it out, thank you so much for your patience. Yes I support disabling the default, because not everyone is as clear as me for example, because my English is bad.

**Comment by kangarko** [comment]
No worries, let us know how it goes and if you see anything else on the spark report, please post it, I am happy to help.
