### ISSUE TITLE
10.27.9: Forcefully leaving staff channel each reconnect

### ISSUE THREAD

**Issue by Yertled** [kangarko/ChatControl#2815]
### Are you using MySQL?

No

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

VelocityControl-1.1.0.jar

### Optional: "/chc debug" file

[debug.zip](https://github.com/user-attachments/files/16829612/debug.zip)

### Steps to reproduce

The issue is that I was stupid and tried to create a toggle for our "staffchat" channel. It has worked flawlessly for ages, and I am the only person who has issues.
I can join the channel by doing `/ch join staffchat read` for example, or use the `/ch set` command, but the second I disconnect from the server, and re-connect, I am no longer in staffchat as read.
I have tried using LuckPerms to set the permissions I need on both myself as a user and in a group, which neither of them works for me.
This is the permission I have:
chatcontrol.channel.autojoin.staffchat.read

How can I either delete my player profile from CHC, or how can I fix this issue?

I saw this in the wiki:
"IMPORTANT: If players decide to leave the channel you joined them into, we save their preference and won't automatically join them next time their login. To prevent this, take away the chatcontrol.channel.leave.{channel} permission for the said channel, so they won't be able to leave it."

But why does it save my preference for leaving a channel, when I am also trying to join it back? How do I delete that preference from my player?

**Comment by TheIntolerant** [comment]
![image](https://github.com/user-attachments/assets/421b9e85-9ca0-4f21-a098-eda8f0383720)
Check ``settings.yml`` and near the top around line 55 you should see these two options, it sounds like you just need to adjust these options to your own needs.

You will probably only need to change ``Ignore_Autojoin_If_Left`` to ``false``

**Comment by TheIntolerant** [comment]
Also to allow us to better understand this issue, can you please provide the permission nodes used for the channels. Thanks

**Comment by kangarko** [comment]
Thanks to Ezra for answering, should you need more assistance comment below please.
