### ISSUE TITLE
Send private messages on discord

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2816]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### Question

Hi, sorry to bother you with this stupid question.

I'm trying to create a log of private messages that are sent to discord.
I have 2 questions.
I have the problem that it looks bad on discord, since it shows the entire message and visually it doesn't look quite right, although this is secondary.

The problem comes when users directly use the private chat function without using the command, that is, they just put /msg and enter a private conversation.

Is there a way to always send private messages to discord?

Could this feature be added?

![image](https://github.com/user-attachments/assets/0c2bd2b1-967b-4b3a-b8e4-70196a74e6e9)

Currently it looks like this:
![image](https://github.com/user-attachments/assets/fbe64e3c-7412-411f-b3a2-4103a735e1f8)

But I wish it could look like this:
![image](https://github.com/user-attachments/assets/af4d795d-0fe9-4a51-8c46-967d01519fdd)

**Comment by kangarko** [comment]
Thanks, currently not possible to easily spy /tell in automode, I will rework this for ChatControl 11.

**Comment by Z3r0xh** [comment]
> Thanks, currently not possible to easily spy /tell in automode, I will rework this for ChatControl 11.

Thank you very much! I appreciate your work!

**Comment by kangarko** [comment]
Thank you!!
