### ISSUE TITLE
1.21.1: ChatControlRed 10.27.7

### ISSUE THREAD

**Issue by fredagsguf** [kangarko/ChatControl#2818]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.7 (newest is obviously not stable)

### Optional: Error log

https://pastebin.com/ra4mCKJN

### Optional: "/chc debug" file

[debug.zip](https://github.com/user-attachments/files/16884690/debug.zip)

### Steps to reproduce

Unsure, as I'm i do not understand the error.

I was on 1.21 previously, when updating to 1.21.1 this started happeningen.
Btw in case you wondering license wise, it is licensed to another admin (we manage the server together)

**Comment by kangarko** [comment]
Solved on the latest version, thank you!
