### ISSUE TITLE
purpur 1.21

### ISSUE THREAD

**Issue by AlphaBlock4k** [kangarko/ChatControl#2819]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

10.27.8

### Steps to reproduce

Hey, the time stamp is no longer displayed for me. Does anyone know what could be the problem?
![image-3](https://github.com/user-attachments/assets/bd9392db-1fa8-41d4-85be-ecacbf919508)

**Comment by AlphaBlock4k** [comment]
?

**Comment by kangarko** [comment]
Hey! Good catch, please use {date}, {date_month} or {date_short} now.
