### ISSUE TITLE
Vanish support

### ISSUE THREAD

**Issue by TheBrianiac** [kangarko/ChatControl#282]
When I use /vanish fakequit, it sends a fake quit message. With ChatControl installed, when I quit again, it sends a second quit message. ChatControl should not broadcast a quit message when I'm vanished.

I believe VanishNoPacket sets the quit message in the PlayerQuitEvent, and ChatControl should be doing this too. Just make ChatControl's event run on a lower priority, optionally with a config option.

Thanks.

**Comment by kangarko** [comment]
Hey, I added a basic support for this :)
