### ISSUE TITLE
nah

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#2820]
nah

**Comment by Wasabules** [comment]
I have the same issue

**Comment by MiguVT** [comment]
Me too, pls fix

**Comment by MiguVT** [comment]
@kangarko Its a big issue, too much people use ItemsAdder, pls can you release a update fixing it?, ItemsAdder changed how their api works

**Comment by goldenartur** [comment]
+1

**Comment by kangarko** [comment]
Will be fixed on the next update tonight already, thanks everyone for your patience!
