### ISSUE TITLE
Server overoaded

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2821]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

version 10.27.9

### Optional: Error log

https://mclo.gs/KMD4DGB

### Optional: "/chc debug" file

https://ufile.io/tg790ilk

### Steps to reproduce

Through users taliking on discord the server crashes

**Comment by kangarko** [comment]
This is a configuration problem, not a ChatControl problem. Some of your variables, not sure if it's {alonsotags_tag_chat} or others, take too long. Try removing that variable or {top_role} and see if it helps, keep removing until you find the problematic one.
