### ISSUE TITLE
1.21.1: Crash error

### ISSUE THREAD

**Issue by Pantera07** [kangarko/ChatControl#2822]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.28.0

### Optional: Error log

https://mclo.gs/sQ6amQN

### Steps to reproduce

I don't know how to reproduce it, but it happened after this Paper upstream update: https://github.com/PaperMC/paper/commit/61fe23cd08c313128e175b417ed567e61ba9d248

**Comment by kangarko** [comment]
Set Integration.ProtocolLib.Listen_For_Packets to false for now. Doesnt look like it's caused by a commit which merely deprecates things. Looks like a server issue though, have you tried asking on paper discord?

Thanks
Matej
