### ISSUE TITLE
Version: Discord diffrent format

### ISSUE THREAD

**Issue by noaskers** [kangarko/ChatControl#2825]
### Are you using MySQL?

No

### Are you using a proxy?

Yes - Velocity

### Question

About the proxy chc is not conntect to the proxy.

I was wondering if its possible to make it so if a messages comes from discord

To give it a diffrent format like:

[Discord] {name}: {message}

**Comment by noaskers** [comment]
Right now it takes the formation of the normal chat format but it needs to be clear that it comes from discord

**Comment by JerichoTorrent** [comment]
This is already a feature. In ChatControlRed/formats you can specify the message format if the sender is in Discord, there is an example provided in chat.rs already. You can change it to your liking.

**Comment by noaskers** [comment]
Can u send the code I can't seem to find it?

**Comment by TheIntolerant** [comment]
The current setting is due to change as a result of complaints regarding the formatting of discord messages via in-game VS on the discord server.

See #2804 for more information

**Comment by noaskers** [comment]
No I want to make it so when a message comes from discord it gets send in the chat like this;

[Discord] {Name}: {message}

**Comment by noaskers** [comment]
How can i achieve that?

**Comment by kangarko** [comment]
Lets continue at the other ticket. The bottom line, you will be able to use the two new discord format in the next version, it will be very easy and I will document it. Thank you for your patience :)
