### ISSUE TITLE
Paper v1.21.1-76: Multi-command conflict

### ISSUE THREAD

**Issue by NoxNap** [kangarko/ChatControl#2826]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.27.7

### Optional: "/chc debug" file

[debug.zip](https://github.com/user-attachments/files/17008379/debug.zip)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/6f2f9a5a-4d11-4118-94bb-a4ba698d88f1)
per screenshot i'm doing this in death.rs
```yml
group default
then command mh popup * death-message 100 {player} | {killer}
```
but since CHCR determines multiple commands by `|` it believes it should be a new command, I need to use `|` for MythicHUD arguments. I tried putting the command in quotes but that did not work.

Proposed solution is to make it so that if something like 
```yml
group default
then command "mh popup * death-message 100 {player} | {killer}"
```
was done it would consider that all part of command1. If I then added `| command2` to the end of that, it would be considered command2 or if I wanted to I could do `| "command2"`
essentially making it so that when `|` is within quotes, it is not considered the stopping point for command1.

Hopefully this can be added between the large update but if not, I'll still be sad, but understanding.

**Comment by kangarko** [comment]
Have you tried escaping it with a backslash \? Like this:

`then command mh popup * death-message 100 {player} \| {killer}`

That should do!
Matej
