### ISSUE TITLE
1.21.1: Not seeing first time join messages for new players

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2828]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.27.8

### Optional: "/chc debug" file

[debug (3).zip](https://github.com/user-attachments/files/17024502/debug.3.zip)

### Steps to reproduce

I am sure it's a setting somewhere, but I cannot seem to find it. It was working at one point, but isn't currently so hoping for some guidance.

**Comment by JerichoTorrent** [comment]
First of all you're a couple versions behind on ChatControlRed. Also, the first join message can be seen in ChatControlRed/messages/join.rs
Here's mine for example:
group firstjoinmessage
```
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 100
message: 
- &7Welcome to &cTorrent Network &#F5C445{player}&7! Read &a/guide &7to get started. [&#F5C445%server_unique_joins%]
```

**Comment by HorusApl** [comment]
I already have that exact thing set in ths join.rs

**Comment by JerichoTorrent** [comment]
Care to share what your join.rs file looks like?

**Comment by HorusApl** [comment]
I linked my debug.zip for all of my files which should have anything needed

**Comment by kangarko** [comment]
The name is misleading, it records ticks despite saying minutes. Try increasing the number:

```
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 100
message: 
- &7Welcome to the server &c{player}&7!
```
