### ISSUE TITLE
Version: Laters v10.28.0

### ISSUE THREAD

**Issue by danieliustt** [kangarko/ChatControl#2829]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

v10.28.0

### Optional: "/chc debug" file

TPS DROPS
![image](https://github.com/user-attachments/assets/c3fb9fc5-a5a7-46dd-9896-a3b4dfd3a166)

### Steps to reproduce

https://github.com/user-attachments/assets/c3fb9fc5-a5a7-46dd-9896-a3b4dfd3a166

**Comment by danieliustt** [comment]
Server ver. 1.20.4

**Comment by kangarko** [comment]
Please provide a spark report, Spigot timings is very inaccurate, that is why it is pending removal in Paper. Thank you.

**Comment by danieliustt** [comment]
![image](https://github.com/user-attachments/assets/5605982f-1678-4633-9942-8818d02b5828)

**Comment by kangarko** [comment]
This is still not a spark report url, I am sorry.

**Comment by danieliustt** [comment]
![image](https://github.com/user-attachments/assets/3bdef0a2-7490-48d3-8377-324ead4a2fa5)

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/ChatControl-Red/issues/2834

**Comment by kangarko** [comment]
Closing, lets continue on there.
