### ISSUE TITLE
Spy System Crashing my Server

### ISSUE THREAD

**Issue by Chopnex** [kangarko/ChatControl#2832]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.28.0

### Optional: Error log

https://mclo.gs/UQYetFm

### Optional: "/chc debug" file

[debug.zip](https://github.com/user-attachments/files/17089705/debug.zip)

### Steps to reproduce

Don't know, haven't changed much except for mysql and bungee forward settings to velocity. Im still using CMI as the primary plugin for formatting plugins at the moment. Don't know if this could have anything to do with the amount of text/data that is being processed by the plugin.

**Comment by kangarko** [comment]
Hey! Apologizes for the trouble. We're extremely close to pushing ChatControl 11 out now, if it happened once I recommend waiting until the new release. If it is happening daily let me know and I try to patch the 10.

**Comment by Chopnex** [comment]
Happened twice within minutes but helped when I removed tracking of everything but one thing.

**Comment by kangarko** [comment]
Got it. Please re-post on ChatControl 11 since the structure of the code changed completely if it happens again. Thank you.
