### ISSUE TITLE
Toast doesn't work correctly

### ISSUE THREAD

**Issue by d0ddn** [kangarko/ChatControl#2833]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.28.0

### Optional: "/chc debug" file

![image](https://github.com/user-attachments/assets/9d5e3ed0-527f-417e-8215-c64e6ee9a53e)
`then toast AMETHYST_SHARD CHALLENGE 1`

### Steps to reproduce

match ^\/command\b
require perm permission.1
then toast AMETHYST_SHARD CHALLENGE 1
then deny

**Comment by kangarko** [comment]
Apologizes, I will be reviewing this on Monday.

**Comment by kangarko** [comment]
Thanks, I will fix the wrong icon in chatcontrol 11, this is not a major bug for the old chatcontrol 10.x
