### ISSUE TITLE
Incorrect formatting from discord

### ISSUE THREAD

**Issue by Sakishima** [kangarko/ChatControl#2835]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.28.0

### Optional: "/chc debug" file

When sending a discord message, the game uses a channel formatting (Format_Discord) from the main configuration file. But for the game chat, I have tuned formatting for each channel in a special file (Formats folder, Discord-Prefix field), but it is ignored.
Tell me how to return formatting so that it works as on previous versions?

### Steps to reproduce

Send a message from Discord. The game chat is improper formatting.

**Comment by kangarko** [comment]
Game to discord is a bit strange in ChatControl 10, we'll add two separate keys for the new ChatControl 11. ETA 1-2 weeks.
