### ISSUE TITLE
Elevate rules/packet.rs functionality to work also on Bungeecord output messages if BungeeControl is installed (and option inside of it enabled)

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [kangarko/ChatControl#2836]
### Summary

This could be useful to remove some hardcoded messages from some bigger plugins... like SkinsRestorer (every single usage message is not translatable) but the list goes on, smaller plugins are more prone to this

I guess this would require Protocolize, or maybe even nothing? i am not sure how this could be handled.

**So this would simply do everything which is configured inside of CHCRED on the server on which the player is**
So let's say player is on hub, and he tries to execute `/skin set` command, the packet.rs will check rules for that output message (if enabled in BungeeControl) and will do the job accordingly like it does for backend message
And if the player executes this same command on some other server where CHCRED is installed but packet.rs does not have this rewrite rule for `/skin set` output, of course nothing will happen

I actually think this could be done maybe without even using BungeeControl for this specific potential feature (except for toggle switch as option in its config but that can also be implemented into CHCRED if there is no need for BungeeControl to be involved into this feature being elevated to proxy) because of next:
- i have autobroadcast plugin on bungee, which sends messages to proxiedplayers online
- when someone chat inside of the server, admins can click X to remove messages which is CHCRED feature (CHCRED is of course installed on backend not bungee, BungeeControl is on proxy but i think this doesn't matter)
- when admin click the X at player's message, not only that message gets removed but every bungee sent message in the chat gets fully removed from the chat, it is nowhere found in whole chat
- having this is mind, just wanted to mention, maybe it's VERY wrong because for this feature functionality is handled very differently (e.g. whole chat is cleared and re-sent)...
- Really doesn't matter, thanks for reading

Thank you for reading again!

**Comment by kangarko** [comment]
We will be unfortunately getting rid of packet rules due to how poorly this packet is implemented and changed across Minecraft versions, not to mention the performance issues it causes.

**Comment by kangarko** [comment]
The [X] feature will remain, but there is no plan on adding proxy support as of right now due to time constrains. I might revisit this later, thank you.

**Comment by MotikaCraft-TheJoshua** [comment]
> We will be unfortunately getting rid of packet rules due to how poorly this packet is implemented and changed across Minecraft versions, not to mention the performance issues it causes.

Ok good to know not to rely my server onto this feature then and to find some alternative... very sad though, especially because it works good on every version i tested (any server/client version combination, i have a lot of test servers)

Will you keep it maybe because of Folia? it will be able to absorb any issues related to this because it's multithreaded(?)

I'd also like to better understand what do you meanby "due to how poorly this packet is implemented":
- implemneted into your plugin?
- implemented into spigot/paper API?



> The [X] feature will remain, but there is no plan on adding proxy support as of right now due to time constrains. I might revisit this later, thank you.

You might revisit this later - for bungee?

**Comment by kangarko** [comment]
Yes, we might revisit the need for packet rules later. Generally speaking using packet rules is a hacky way that should be done using chat or command rules instead. All of the other packet features will stay, I am just talking about rules/packet.rs file being removed.
