### ISSUE TITLE
Possible chat color bug

### ISSUE THREAD

**Issue by sennby** [kangarko/ChatControl#2837]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.28

### Steps to reproduce

![image](https://github.com/user-attachments/assets/1900b208-20ea-47b1-856f-2ac8ef801526)
I use ezcolors and chatcontrolred. Since 1.21 chat colors have been messed up. I just updated ezcolors to 1.21.1 version.
Possible issue with chatcontrolred?

Maybe its a config thing i can fix? But this worked up until 1.21.1 and now it shwos the color codes.

**Comment by sennby** [comment]
If i do /chatcolor select a color, it shows the color code infront of it.
If i plugman disable ezcolors then enable it, it works properly for whoever already chose colors, if someone were to choose a color again, it shows the &a or whatever color code chose infront.
disable plugman they will work (it remembers ur color code)

**Comment by kangarko** [comment]
I unfortunately can't support PlugMan at all because how it is implemented. I think the EZColors might be incompatible with our color menu, either use ChatControl or that plugin for color management.

**Comment by sennby** [comment]
I dont care about plugman compatibility -- i have to plugman disable the plugin (ezcolors) because it doesnt work with chatcontrolred is all.
It worked before on 1.20.4, now since 1.21.1 it doesnt work. It used to work just fine, so something in the update broke it.
ezcolors provides a shop/gui for chat colors that players already have purchased and used. if im forced to move if anything it will be have to be me moving off of CCR as that wont affect my players...

ezcolors applies its colors and it works after plugman disabling it.

so when i start my server if someone has already selected or selects a color. it shows the color code infront and it also usees the color correctly in chat. When i plugman disable it, the color remains, and the color code removes, so it looks like its working but u cant change ur color bc the ezcolors is disabled.
@kangarko 
I dont use CCR colors at all to my knowledge.

**Comment by kangarko** [comment]
Yes I will make sure we improve the compatibility in the next version. Until then you can try adjusting the listener priorities as per our Wiki article.

**Comment by sennby** [comment]
> Yes I will make sure we improve the compatibility in the next version. Until then you can try adjusting the listener priorities as per our Wiki article.

Sadly no changes to priorities worked. Im  just going to disable the plugin on a schedule til the update. Appreciate you atleast doing it.

**Comment by kangarko** [comment]
Thanks for your patience!

**Comment by kangarko** [comment]
Yes of course I care, but I am a solo dev for five plugins plug managing real life so it's just not physically possible to do instantly

**Comment by sennby** [comment]
I dont know if the last update was supposed to fix it but it did not for me.

**Comment by kangarko** [comment]
No sorry, I aim to improve compatibility in ChatControl 11.x not the 10th branch, due to the amount of work needed :)
