### ISSUE TITLE
Distribute Thai translation for Thai people.

### ISSUE THREAD

**Issue by v4r1n** [kangarko/ChatControl#2838]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.28.0

### Optional: Error log

https://pastebin.com/tfsTth3Y

### Optional: "/chc debug" file

I have made the localization for Thai language so that Thai people can use Locale: th for chatcoltrol red plugin.

### Steps to reproduce

-

**Comment by kangarko** [comment]
Thank you, please repost it when chatcontrol 11 is ready because there will be breaking translation changes.
