### ISSUE TITLE
Error - 24/7 Spamming Console

### ISSUE THREAD

**Issue by DeadMaster121** [kangarko/ChatControl#284]
[Thu, 22. Feb 2018 17:30:06 CET INFO] arthurMTB13 issued server command: /sell
[Thu, 22. Feb 2018 17:30:06 CET WARN] java.util.regex.PatternSyntaxException: Unknown inline modifier near index 70
(?:[a-z0-9!#$%'*+/=?^_`{|}~-]+(?:.[a-z0-9!#$%'+/=?^_`{|}~-]+)|"(?[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\[\x01-\x09\x0b\x0c\x0e-\x7f])")@(?:(?:[a-z0-9](?:[a-z0-9-][a-z0-9])?.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\[\x01-\x09\x0b\x0c\x0e-\x7f])+)]|ultranetwork.me|mc.ultranetwork.me|ultranetwork.gamename.net|ultranetwork.mc-srv|ultranetwork.mcalias|forums.ultranetwork.me|store.ultranetwok.me|ultranetwork|skyblock.ultranetwork.me)
                                                                      ^
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at java.util.regex.Pattern.error(Pattern.java:1957)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at java.util.regex.Pattern.group0(Pattern.java:2896)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at java.util.regex.Pattern.sequence(Pattern.java:2053)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at java.util.regex.Pattern.expr(Pattern.java:1998)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at java.util.regex.Pattern.group0(Pattern.java:2823)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at java.util.regex.Pattern.sequence(Pattern.java:2053)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at java.util.regex.Pattern.expr(Pattern.java:1998)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at java.util.regex.Patternpile(Pattern.java:1698)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at java.util.regex.Pattern.<init>(Pattern.java:1351)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at java.util.regex.Patternpile(Pattern.java:1054)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at kangarko.chatcontrol.utils.Common.getMatcher(Common.java:342)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at kangarko.chatcontrol.utils.Common.regExMatch(Common.java:353)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at kangarko.chatcontrol.rules.Rule.matches(Rule.java:168)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at kangarko.chatcontrol.rules.ChatCeaser.iterateStandardRules(ChatCeaser.java:276)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at kangarko.chatcontrol.rules.ChatCeaser.parseRules(ChatCeaser.java:238)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at kangarko.chatcontrol.listener.CommandListener.onPlayerCommand(CommandListener.java:93)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at sun.reflect.GeneratedMethodAccessor185.invoke(Unknown Source)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at java.lang.reflect.Method.invoke(Method.java:498)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[Thu, 22. Feb 2018 17:30:06 CET WARN]     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)

This error is spamming my console non-stop, not just command literally any command that gets executed.

I've removed this part from my rules and yet it still causes spam.

ChatControl Version - 5.6.3
Spigot version - 1.8.8

**Comment by kangarko** [comment]
You have a syntax error in your rules.txt file somewhere. The error points out to the IP or domain rule. Use regex101.com for testing please, or remove that rule completely and restart the server.
