### ISSUE TITLE
10.27.9: Replace or hide specific characters when sending messages to discord

### ISSUE THREAD

**Issue by NekrosBurek** [kangarko/ChatControl#2840]
### Are you using MySQL?

No

### Are you using a proxy?

Yes - Velocity

### Question

I've been using ChatControl as a main sender of messages from Minecraft to Discord, and while using IA or Oraxen i have custom emoji's when user is sending that chat in discord is replacing that with the of course the symbol behind the emoji
Is it possible before message is sent to discord to modify it or have those emojis removed/replaced

Thanks in advance

**Comment by kangarko** [comment]
I understand, but that is such a specific requirement that I see two possible solutions:

1. I can add a global toggle into settings.yml to remove emojis in mc>discord messages
2. You will need to make a small plugin hooking into JDA to do the sending yourself

**Comment by kangarko** [comment]
Closing. Let me know below if you still need help.
