### ISSUE TITLE
Bedrock /mail commands

### ISSUE THREAD

**Issue by ChiefWarPig** [kangarko/ChatControl#2841]
### Summary

Bedrock players can not use the options of clicking on chat messages to open and view /mail so it would be great to have commands like /mail read <mail title> etc so that the mail system has better compatability on cross play servers. I can not find any commands in the ingame help or the wiki that would allow bedrock players to manage their mails effectively.

**Comment by kangarko** [comment]
The way the system works currently is that each email has a long unique ID. I do not have the capacity to do a big rewrite at this moment, the best you can do is use an alternative mail plugin or have a developer hook into ours and make a custom solution for bedrock, I apology for the inconvenience.
