### ISSUE TITLE
10.28.0: Ignore perm nefunguje

### ISSUE THREAD

**Issue by pjindras** [kangarko/ChatControl#2842]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.28.0

### Optional: "/chc debug" file

[_tady_](https://ufile.io/vxec2ei3)

### Steps to reproduce

Mám pravidlo např.
```
match (?i)h\s*i\s*t+\s*l\s*e\s*r
ignore perm at.chatcontrol.bypass
then warn  {plugin_prefix}Nenadávej v chatu.
then notify chatcontrol.notify.rulesalert &8[Zkouší nadávat] &7{player} &b(&fhitler&b) &7: &f{original_message}
then deny
```

kdokoli má permisi at.chatcontrol.bypass -> stejně ho to zachytí

**Comment by kangarko** [comment]
Ahoj,

Mne to funguje na tvojich settings: ![a](https://i.imgur.com/IvFRpn1.png)

Vyzera to na konflkt s inym pluginom. Vid sekcia listener priority vo Wiki, pripadne skopiruj server na desktop a otestuj iba s chatcontrol-om.
