### ISSUE TITLE
1.21.1: "Player" is not stored in our database

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2843]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

Recently moved to MySQL storage due to server/log size needing it. It seems any players stored on the old .db that is currently on someone's ignore list, still shows on their ignore list. I never deleted my old .db file, should I delete it? If it's still used for toggles or other things, is there a different way to remove it?

**Comment by kangarko** [comment]
You can delete it. Make sure to have done a clean restart, no plugman, and join through your proxy with velocitycontrol or bungeecontrol plugins installed on proxy.

**Comment by kangarko** [comment]
Closing. Let me know below if you still need help.
