### ISSUE TITLE
Version: Paper 1.21.1

### ISSUE THREAD

**Issue by sa1f22** [kangarko/ChatControl#2844]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.28.1

### Steps to reproduce

I cant hover over anything, nothing pops up when  i hover. [item] does not work. Am i missing something?

**Comment by kangarko** [comment]
Let me get back to you in 24 hours

**Comment by kangarko** [comment]
Can you please send me your /chc debug?

**Comment by kangarko** [comment]
Closing due to inactive, please comment below when you come back
