### ISSUE TITLE
Version: Paper 1.21 Title: Chats sent automatically being with &f

### ISSUE THREAD

**Issue by SynthCraft** [kangarko/ChatControl#2846]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.28.1

### Optional: "/chc debug" file

[debug.zip](https://github.com/user-attachments/files/17464236/debug.zip)

### Steps to reproduce

When sending a chat, every message begins with &f - this is displayed chat as "Axynth: &ftest" whilst it should be "Axynth: test" I am not using channels to format the chat.

**Comment by SynthCraft** [comment]
Issue fixed.

**Comment by kangarko** [comment]
It's a deeper issue, which we aim to address in ChatControl 11. Thank you!
