### ISSUE TITLE
Add an option to not depend on DiscordSRV plugin and instead to boot up CHCRED own bot with token, or if token not provided then use webhook

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [kangarko/ChatControl#2848]
### Summary

This could potentially have a lot of options such as current options but without depending on DiscordSRV but also an option to send webhook with exact same name like "MC Chat" (to manually create it for a given channel and then provide URL in chcred to use it)

**Comment by kangarko** [comment]
Absolutely, this will come with ChatControl 11! :)

**Comment by MotikaCraft-TheJoshua** [comment]
Thanks @kangarko 
Please let's relate to https://github.com/kangarko/ChatControl-Red/issues/2847

for v11:
1. Eliminating and making DIscordSRV (v1 and v3 ASCENSION) support optional which if disabled will require input of bot's token, so CHCRED has its own bot (this will be required to be able to send DISCORD -> MINECRAFT messages)
2. Keeping the existing functionalities which currently rely on DiscordSRV such as sending MINECRAFT -> DISCORD messages either as bot or as webhook which is adapted to each user's ingame head avatar & their message (of course with preconfigured format and channel ID)
3. Allow either text channels or voice channels, both will function (this is something DiscordSRV (v3) Ascension has as feature) because this would make having channels much easier where you can literally create your network's subserver channel, a SINGLE CHANNEL which can be used for voice chatting but also for syncing ingame and discord chat both ways (if enabled in config)!

I think these features are key for the basic Discord support which fits into CHC so good -> chat! :)

**Comment by kangarko** [comment]
Will add, except for voice support, I unfortunately don't have time for everything.

**Comment by MotikaCraft-TheJoshua** [comment]
> Will add, except for voice support, I unfortunately don't have time for everything.

I am not sure if you understand me correctly about voice channels...

![image](https://github.com/user-attachments/assets/00f26797-8ee0-49bf-8d65-fd7fac25e999)

![image](https://github.com/user-attachments/assets/548a51a2-3a5c-40c5-95b8-467df186ba9d)

I mean this, voice channels' text chat, not voice chat, we are only talking about text-based chat, because we can also write text messages inside of voice channels

I am saying this because it would make life so much easier if we could create 1 channel for each of our sub-servers on our network, and use them for native voice chat PLUS for chatcontrol to sync **text chat inside of those voice channels** from mc to discord and from discord to mc, just like it does for regular text channels

**Comment by kangarko** [comment]
gotcha, yes that should be possible in the next 11 version

**Comment by MotikaCraft-TheJoshua** [comment]
> gotcha, yes that should be possible in the next 11 version

Very happy to hear this! :)


> Thanks @kangarko Please let's relate to #2847
> 
> for v11:
> 
> 1. Eliminating and making DIscordSRV (v1 and v3 ASCENSION) support optional which if disabled will require input of bot's token, so CHCRED has its own bot (this will be required to be able to send DISCORD -> MINECRAFT messages)
> 2. Keeping the existing functionalities which currently rely on DiscordSRV such as sending MINECRAFT -> DISCORD messages either as bot or as webhook which is adapted to each user's ingame head avatar & their message (of course with preconfigured format and channel ID)
> 3. Allow either text channels or voice channels, both will function (this is something DiscordSRV (v3) Ascension has as feature) because this would make having channels much easier where you can literally create your network's subserver channel, a SINGLE CHANNEL which can be used for voice chatting but also for syncing ingame and discord chat both ways (if enabled in config)!
> 
> I think these features are key for the basic Discord support which fits into CHC so good -> chat! :)

I just want to add to this because some bots/mc plugins that host a bot does not provide this:

Activity status or whatever it is called (maybe activity presence) can either be "playing"/"listening" and other... where it will display "hardcoded" text of "Listening... <whatever you wrote>":
![image](https://github.com/user-attachments/assets/8247cd66-2e10-4f6c-af57-c8251545cfee)

A lot ago, discord added Custom Discord Status/Presence which does not require you to have activity name such as "playing" or "listening", but you can directly input text which will be displayed as status of the bot, exactly like you write it, for example "Hello there good people!"; example:

![image](https://github.com/user-attachments/assets/0f3286a9-07d7-4f3d-adc3-d01bf4a496ed)

![image](https://github.com/user-attachments/assets/0abcfc9b-4905-4c7d-ab93-d8c6670cd670)

So i wanted to also suggest that v11 should have this feature too — that Custom Discord Status/Presence — without the need of adding upfront "listening"/"playing"/"streaming"...

**Comment by kangarko** [comment]
Thanks for suggesting. Please wait until the new generation is out and feel free to re-suggest later. We will see how much time we will have for extra features.

**Comment by MotikaCraft-TheJoshua** [comment]
> Thanks for suggesting. Please wait until the new generation is out and feel free to re-suggest later. We will see how much time we will have for extra features.

I think everything mentioned here are the most basic things that discord bot related to chat should have
Of course if something is not added initially, i will for sure create GH issue to make it come to CHCRED v11, i truly believe CHCRED should take care of chat as it's much better for conditions etc...
Thanks for listening

**Comment by kangarko** [comment]
Sounds good, thank you for suggestion!
