### ISSUE TITLE
Chat Control Pro suddenly stopping working today, what happening?

### ISSUE THREAD

**Issue by netherstar** [kangarko/ChatControl#2849]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

I'm using Chat Control Pro normally on Server 1.12.2, and i'm fine with it, but today, Chat Control Pro on all of my servers stopped working, with this message print below print, can you tell me what happen? are my server hacked? or you make something to force old Chat Control Pro customer to upgrade to Chat Control Red?

[05:04:46 INFO]: <0> An error occured: pamF2YS5pby5GaWxlTm90Rm91bmRFeGNlcHRpb246IGh0dHA6Ly9rYW5nYXJrby5jb20vYXV0aC9wdXJpZnlfNC5waHA=
[05:04:46 INFO]: [ChatControl] Disabling ChatControl v7.9.31
[05:04:46 INFO]: Plugin might not shut down property. Got NullPointerException: null

**Comment by kangarko** [comment]
Yes you were force migrated and since you are late, we'll charge late-migration fees. It's gotta be $50...

**Comment by kangarko** [comment]
I am obviously kidding 😄 You are of course keep using our software without migrating and I have made the necessary changes to make it bootable again after SpigotMC deleted our page. Please grab the new build from https://github.com/kangarko/ChatControl-Pro/releases/tag/8.12.0
