### ISSUE TITLE
Messages: Custom...

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl#285]
In the death messages setting the "Custom" option appears limited to a single message... does not follow formatting as the rest of the messages where you can put multiple options.  

Format for Every other message:
```
  Dragon_Breath:
    Message:
      - '&7The Enderdragon has annihilated &e{player}'
      - '&e{player} &7couldn''t tame a NightFury'

```
Format for Custom:
```
  Custom:
    Message: '&e{player}&7''s life force was mysteriously extinguished'
```

I'm assuming this is an oversight of this single "custom" option and that it's not intentional that multiple messages entered in the usual yml (prefixed with dash and correct spacing for each) is not supposed to all display as a single message with those dashes and ' marks displayed along with them... and also that it should have been possible to enter more than one message using the format provided for every other death type.  If I'm wrong about these 2 assumptions, then never mind.  Thanks much!

**Comment by kangarko** [comment]
Hello,

I am happy to say that I made ChatControl so flexible it that it automatically detects whether a message is a single-liner or a multiline. We also support "|-" on both lists and single lines for multilined message in the game chat. Just retype it to a list format and it'll work. Cheers!

**Comment by mrcoffee1026** [comment]
works perfect now, thanks
