### ISSUE TITLE
Formatting Features Not Working

### ISSUE THREAD

**Issue by Hydoxl** [kangarko/ChatControl#2851]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.28.1

### Optional: "/chc debug" file

https://ufile.io/yzhqxds8

### Steps to reproduce

Hello,

I recently purchased the Chat Control Red plugin and followed the Getting Started tour, which worked fine. However, after completing the tour, I've noticed that the default formatting features, such as removing messages, are not functioning as expected.

**Details:**
- I have the correct permissions, specifically `op` and `chatcontrol.removemessages`.
- I've tried changing the server version and software (both Purpur and Paper), but the issue persists.
- I have the latest version of ProtocolLib installed (v5.3.0).
- I've checked the console for any errors, but there are none.
- I also attempted to use group formatting with the `chatcontrol.group.vip` permission, but that did not work either.

**Screenshots:**

1. **Not Working Formatting:**
   ![image](https://github.com/user-attachments/assets/6c3e3509-a7c0-48ea-b2cb-ea4878af513c)

2. **Set Up Permissions:**
   ![image](https://github.com/user-attachments/assets/174ef7ee-6ee7-41cf-93b3-df523f81367e)

3. **Server Plugin List:**
   ![image](https://github.com/user-attachments/assets/ec559425-53ed-47dd-a3b2-48ea0af76588)

**Questions:**
- Is there something I might have missed in the plugin setup?
- What could be causing these formatting issues?

Any assistance would be appreciated!

Thank you!

**Comment by kangarko** [comment]
Investigating in 24 hours

**Comment by kangarko** [comment]
Hello,

I see your file, the [X] feature requires Channels to be enabled. Simply set Channels.Enabled to true in settings.yml and the default formats/chat.yml already has the feature implemented so it will work under the standard channel, which you can edit.
