### ISSUE TITLE
Cannot invoke "java.lang.invoke.MethodHandle.type()" because "target" is null

### ISSUE THREAD

**Issue by v4r1n** [kangarko/ChatControl#2852]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

ChatControl-Red-10.28.1

### Optional: Error log

https://paste.helpch.at/qivizetori.md

### Optional: "/chc debug" file

**Describe the bug**
The VelocityControl plugin is failing to load when the Velocity proxy is running on Java 21. The error occurs during plugin initialization, where a NullPointerException is thrown because the target is null in the MethodHandle.type() call. This results in the plugin being disabled.

**Expected Behavior**
The VelocityControl plugin should load and function correctly without throwing any exceptions, regardless of the Java version used.

**Actual Behavior**
The plugin fails to initialize and is disabled due to a NullPointerException during the initialization of the JavaScriptExecutor class. The error stack trace indicates that the issue is related to method handling in Java.

**Plugin List**
Velocity Proxy Plugins: _VelocityControl v1.1.0_, _LuckPerms v5.4.145_

**Velocity Version**
Velocity Version: _3.4.0-SNAPSHOT (git-08a42b37-b449) Running on Java 21.0.4_

**Additional Information**
This error may be related to a compatibility issue with Java 21. The issue may be fixed by updating the version of VelocityControl - Cross-Network Chat to support it without any problems.

### Steps to reproduce

**Steps to Reproduce**
1. Set up a Velocity proxy server running Java 21.
2. Install the VelocityControl plugin (v1.1.0).
3. Start the server and observe the console output.
4. The error appears in the logs, and the plugin is disabled.

**Comment by v4r1n** [comment]
The conflict issue is caused by velocity-b447 (Update several dependencies). More info at https://github.com/PaperMC/velocity/commit/f2d6e143ae872f7da83d69a97acca0412923c7f6

**Comment by kangarko** [comment]
Investigating in 24 hours

**Comment by ImBas** [comment]
Experiencing the same issue here.

**Comment by kangarko** [comment]
Almost fixed, need 18 hours more and will push a new release, thanks yall for your patience

**Comment by kangarko** [comment]
Fixed. I will push the update out by tonight.
