### ISSUE TITLE
Could not pass event IventoryClickEvent to ChatControlRed

### ISSUE THREAD

**Issue by Jerlag01** [kangarko/ChatControl#2853]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.28.1

### Optional: Error log

https://pastebin.com/xi3suUA3

### Optional: "/chc debug" file

[debug.zip](https://github.com/user-attachments/files/17565045/debug.zip)

### Steps to reproduce

not that i know of, random error occured while runnig the server

**Comment by kangarko** [comment]
Probably because you reloaded or some other unknown error, but it should not happen often. Let me know if it happens on v11

**Comment by Jerlag01** [comment]
> Probably because you reloaded or some other unknown error, but it should not happen often. Let me know if it happens on v11

Any ETA on v11? cuz I just restarted the entire server and it's still spamming the console

**Comment by kangarko** [comment]
Post me the full error stack trace from server start to the end of it please

**Comment by Jerlag01** [comment]
> Post me the full error stack trace from server start to the end of it please

https://pastebin.com/uSZ0mNaJ

**Comment by kangarko** [comment]
Fixed

**Comment by Jerlag01** [comment]
> Fixed

thanks for the quick fix, really appreciate it

**Comment by kangarko** [comment]
You're welcome!
