### ISSUE TITLE
Paper 1.21.1 Multi Proxy relay and multi filters

### ISSUE THREAD

**Issue by PlayGlowCraft** [kangarko/ChatControl#2854]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### Question

I know you have ChatControl 11 coming soon. I just wanted to ask if these are possible now or maybe in the future.

First Issue: I run 2 proxies. 1 for Regular Connections and 1 linked to Minehut. Is there a way to sync messages between both proxies? At the moment. If im connected to the Main Proxy. I cannot see any messages/joins/quits/switches from the Minehut proxy and vice versa.
Do all the servers need to share the same database. I ask because I have both backend servers setup with seperate databases to keep chat and nicknames seperate on each server.

2nd Issue: I am trying to make it so the following happens.

2 groups of Players Regular and Verified
The main chat filter filters global chat. 
The secondary group and or filter will allow a few adult words (this is for 18+ players to be seperate from younger players)

The idea is that if your age verified when you type one of these allowed swear words it will forward the message to the verified channel. instead of Main Chat.

Things i tried 

I set the word directly so if it was type it would do command ch send  verified $2 then when typing the world it came back with the error of me not typing the command correctly. However when i type to the verified channel directly without a swear word it works. 
I set the word to a secondary group swear2 then in the groups.gs folder set it so it would command ch send verified $2 and got the same error.

I know you have ChatControl 11 coming and i want to thank you for an awesome plugin.

**Comment by kangarko** [comment]
Thank you!

We do support Redis, but I do not believe we support Minehut. Messages are currently relayed over 1 velocity/bungee network with the exception of Redis.

And I am open to contributions, if you or anyone else is willing to take onto editing our [VelocityControl](https://bitbucket.org/kangarko/velocitycontrol/src/master/) or BungeeControl plugins I am happy to give them source access! 

When the comes to your second questions, you can ignore filtering certain swear words in certain channels by adding the "ignore channel {name}" operator under the specific filters in your .rs files. That way you can create adult-only chats.

Hope that helped or let me know below if you got any more questions!

**Comment by PlayGlowCraft** [comment]
Sorry to bother you again. I currently have select words setup like this
# Blocks 'damn'
match \b((?i)d+(\W|\d|_)*a+(\W|\d|_)*m+(\W|\d|_)*n+(\W|\d|_)*)
ignore channel verified
group swear

Is there a way to make it so when they type the sentence with the word.  It auto sends it to the verified channel instead of having to manually join the channel to write?

I gave myself autojoin I currently have 3 channels Standard/staff and verified

**Comment by kangarko** [comment]
I believe so, can you review the examples in rules/chat.rs or commands.rs? We got some that will show you how to do message forwarding, I am out of my office atm but you should find them easily
