### ISSUE TITLE
VelocityControl 1.1.0: error when enabling plugin

### ISSUE THREAD

**Issue by Geitenijs** [kangarko/ChatControl#2855]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.28.1

### Optional: Error log

https://pastebin.com/qEDMf2gi

### Steps to reproduce

Update to Velocity #449 and VelocityControl won't enable anymore.

**Comment by kangarko** [comment]
Fixed already, new build coming out today, thanks!
