### ISSUE TITLE
Do I need buy VelocityControl to?

### ISSUE THREAD

**Issue by Domplanto** [kangarko/ChatControl#2856]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### Question

I already bought Chat Control Red and I have a Velocity network, do I now also need to buy VelocityControl if I already bought Chat Control Red?

**Comment by kangarko** [comment]
See:

![a](https://i.imgur.com/dtOiw5t.png)
https://builtbybit.com/resources/velocitycontrol-cross-network-chat.43226/
