### ISSUE TITLE
Suggestion: ChatControl-Red to show full name of custom items with [item] command

### ISSUE THREAD

**Issue by v4r1n** [kangarko/ChatControl#2857]
I would like the chatcontrol-red plugin to support displaying the full name from the oraxen plugin when typing `[item]` in the chat box.

**Screenshot**:
ChatControl-Red-10.28.2
![image](https://github.com/user-attachments/assets/0abe8344-4e17-4739-92de-2493f87e630f)

InteractiveChat-4.2.13.0
![image](https://github.com/user-attachments/assets/27354cd8-eaee-4e15-a78c-5923945634d4)

**Comment by kangarko** [comment]
What is your configuration to display that in InteractiveChat?

**Comment by v4r1n** [comment]
> การกําหนดค่าของคุณในการแสดงใน InteractiveChat คืออะไร

Configure item display with the `[item]` command of the Chat Plugin (InteractiveChat)
**Config**:
https://paste.helpch.at/vikufinepi.yaml
I copied only the part that is shown with the `[item]` command.

More details about this plugin if you want more information https://www.spigotmc.org/resources/interactivechat-show-items-inventory-in-chat-custom-chat-keywords-bungee-velocity-support.75870/

**Comment by kangarko** [comment]
Thanks, not a priority now. But I am leaving this open for ChatControl 11.

**Comment by kangarko** [comment]
I am very sorry, due to time constrains this had to be dropped for now. I will consider this in the future, I hope you understand. Thank you.
