### ISSUE TITLE
Suggestions to support custom colors via config.yml file and support gradient colors in chat

### ISSUE THREAD

**Issue by v4r1n** [kangarko/ChatControl#2858]
You can create your own guardian color and decorate the gui window. Currently, chatcontrol-red only shows hex and vanilla colors, and cannot decorate the window or add colors to the gui page. I have to write it separately in an external plugin to call it, such as the deluxe menu plugin.

Sample image:
![image](https://github.com/user-attachments/assets/cb4cf166-00ec-401f-8cf2-4b56a486b07a)

**Comment by kangarko** [comment]
If I have time I will add the ability to add your own hex colors to the GUI in ChatControl 11, thanks for suggesting.
