### ISSUE TITLE
[Request] A /realname command

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#286]
Most nickname plugins, like Essentials or CMI offer a /realname command so you can see the minecraft name of a player who has set a nickname. For example /realname Shane would tell the player Sikatsu. Hope ChatControl can implement this as well, or make it hook into Essentials / CMI's /realname command.

**Comment by 00Hrtz** [comment]
I agree

**Comment by kangarko** [comment]
Thanks, sure will add shortly

**Comment by kangarko** [comment]
Added
