### ISSUE TITLE
Velocity 1.1.1: NoClassDefFoundError

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#2861]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.28.0

### Optional: Error log

https://pastebin.com/a4msc5V7

### Steps to reproduce

It removed the join/leave/switch msgs

the error is from error.log

**Comment by MADS0LADEN** [comment]
Maybe v 1.1.1 will fix - i will try (i thought we were on 1.1.1)

**Comment by kangarko** [comment]
Solved on v1.1.1
