### ISSUE TITLE
1.21.1: Origin Placeholder

### ISSUE THREAD

**Issue by BuilderDan** [kangarko/ChatControl#2862]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.28.2

### Optional: "/chc debug" file

[debug.zip](https://github.com/user-attachments/files/17694824/debug.zip)

### Steps to reproduce

Load server in 1.21.1 with https://modrinth.com/plugin/origins-reborn/versions and Chat Control Red
Add format in chat.yml for Origins using the origins placeholder

  origin:
    Message: '%origin%'
    Hover:
    - '&7{origin}'
    - '&7Disc'
    - ''
    - '&7Click to learn more about Origins.'
    Open_Url: https://mineacademy.org/project-orion
    
    %% or {} either doesn't work.
    Reload
    Try chatting to see if it displays.

**Comment by kangarko** [comment]
Hello,

Thanks for posting. I am extremely sorry, this appears to be incompatible. Please try our advice on Wiki regarding changing the [listener priority](https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities). Do other placeholder work?

**Comment by BuilderDan** [comment]
From what I tested, yes, I did a placeholder from coinsengine and it displayed

**Comment by kangarko** [comment]
Hmm I see.  Try adjusting listener priorities. If they won't help, then unfortunately that other placeholder is incompatible. I am sorry for that!

**Comment by BuilderDan** [comment]
Unfortunately, the listeners did not work. Is incompatibility on your end or the Origin plugin? As in, how do I get compat?

**Comment by kangarko** [comment]
Ask the developer of Origin to add a hook for PlaceholderAPI. We will then support it nativelly.

**Comment by BuilderDan** [comment]
Update from the dev of the Origins Reborn Plugin:
Second statement is true, I've used it in other chat plugins, currently using a Skript for chat instead of CHC
![image](https://github.com/user-attachments/assets/c944f63b-eeba-467d-b5f4-e6f52532f407)

**Comment by kangarko** [comment]
Gotcha, thanks for that. I will test it asap when I get time.

**Comment by kangarko** [comment]
Just to set expectation I am leaving office for the weekend and will be testing this on Monday :)

**Comment by kangarko** [comment]
Apologizes, had to delay this 1-2 more days. Thanks for your patience.

**Comment by kangarko** [comment]
Super late, sorry I caught a disease. Turns out you need to explicitly prefix the plugin's identifier, so using: {origin_origin} will work fine!

**Comment by BuilderDan** [comment]
Worked, thank you, feel better!

**Comment by kangarko** [comment]
Thanks! Consider giving a review if you enjoy the plugin <3
