### ISSUE TITLE
Paper 1.20.1: Can I use Language Keys in formats?

### ISSUE THREAD

**Issue by BijuuKrunos** [kangarko/ChatControl#2863]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### Question

I want to use language keys in formats and want to ask if that is possible.
I am speaking about ressourcepack language keys like for example:

langkey: hb.item.attr.depth_striker
en_us.json from Ressourcepack:   "hb.item.attr.depth_striker": "§cDepth Striker",

I could not find a way to do that please help :)

**Comment by kangarko** [comment]
Unfortunately this is unsupported for now, I apology. I will put this into our roadmap for consideration. ChatControl 11 will support minimessage so you can use it there :)
