### ISSUE TITLE
1.20.4: Can ChatControl-Red display player head skins in the chat?

### ISSUE THREAD

**Issue by M0DSTERX** [kangarko/ChatControl#2864]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### Question

Hi, I would like to know if ChatControl-Red supports displaying player head skins in the chat. Is there any way to display the player head along with their message in the chat, similar to how some other plugins show player heads in chat?

  **Thank you in advance for the help!**

**Comment by BearLeonLight** [comment]
MC to DC?
see 
https://docs.discordsrv.com/config#experiment_webhookchatmessage
https://docs.discordsrv.com/config#AvatarUrl

**Comment by M0DSTERX** [comment]
Thank you for the suggestion!

 However, my main goal is to display the player's head skin directly in the Minecraft chat itself, not on Discord. I’m aiming for a way to visually show the player's head icon alongside their chat messages within Minecraft. Is there a way to achieve this within Minecraft chat, possibly with a plugin like ChatControl-Red ? or any other recommendations

**Comment by BearLeonLight** [comment]
Have you seen any server or plug-in implementation? I have not researched or searched for it.

It seems that a texture pack (resource pack) is required to display the image on the text.

**Comment by M0DSTERX** [comment]
Thanks for your response!

There are plugins that can do this without the need for a resource pack. It's great, but it just lacks a placeholder. Would it be possible to use ChatControl-Red along with Oraxen to display the player’s head in the chat?

**Comment by BearLeonLight** [comment]
Oraxen This also requires the use of resource packages. The prefix and suffix or Tag parts can be displayed by using PAPI in CHC.

**Comment by BearLeonLight** [comment]
I just looked through it and I only saw those that require resource packs. Are there any that don’t require resource packs?
I would like to know, as far as I know, displaying special text (pictures) needs to be achieved through resource packages.
If you know of any that can be used without resource packs, please reply to me. I would also like to know about them.

**Comment by M0DSTERX** [comment]
Thank you for the information!

I’m currently using the [ChatHeadFont](https://github.com/OGminso/ChatHeadFont) plugin alongside [EssentialsXChat](https://www.spigotmc.org/resources/essentialsx.9089/), which allows me to display player heads in chat without requiring a resource pack.

As for Oraxen, it seems to require a resource pack to display custom icons like player heads in chat. Thank you again for clarifying!

**Comment by kangarko** [comment]
Hey and first of all thanks for helping out!

We support the player head skin rendered as chat letters:

![a](https://i.imgur.com/TtsNfgg.png)

To achieve this, see https://github.com/kangarko/ChatControl-Red/wiki/Formats#image_head

**Comment by BearLeonLight** [comment]
> Thank you for the information!
> 
> I’m currently using the [ChatHeadFont](https://github.com/OGminso/ChatHeadFont) plugin alongside [EssentialsXChat](https://www.spigotmc.org/resources/essentialsx.9089/), which allows me to display player heads in chat without requiring a resource pack.
> 
> As for Oraxen, it seems to require a resource pack to display custom icons like player heads in chat. Thank you again for clarifying!

![{0FEB80D2-CFF4-4684-855D-640EDEC0584B}](https://github.com/user-attachments/assets/5083738e-1bd7-40c9-9e89-539180df5799)

![{A3F27381-213B-4798-9D5C-86520954413D}](https://github.com/user-attachments/assets/e39bccb9-b5bc-4372-86e0-99e00402997e)
The same is done through the resource package to customize the format (text and pictures)
