### ISSUE TITLE
Plugin does not properly shut down

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [kangarko/ChatControl#2867]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

10.28.3

### Optional: Error log

https://mclo.gs/9QC3Sdb

### Steps to reproduce

1. Start up server
2. Shut down server
3. See message, happens almost always on any server version (from 1.8.8 up to 1.21.1)

**Comment by MotikaCraft-TheJoshua** [comment]
i apologize, i don't know what happened with title

**Comment by kangarko** [comment]
Thanks, fixed! A new release will be out in 1-2 days.
