### ISSUE TITLE
Question: Spy in books

### ISSUE THREAD

**Issue by Sakishima** [kangarko/ChatControl#2868]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### Question

Hello.
There was a problem with a spy to books. When clicking on the message, open the book, nothing happens. I use a plugin to hide commands. But I don’t understand which command needs to be allowed to open books in the spy mode.

**Comment by kangarko** [comment]
What server version are you using?

**Comment by Sakishima** [comment]
I am using server version: 1.21.1

**Comment by kangarko** [comment]
I apologize, I was sick and still recovering, I'll be dealing with this on Saturday/Sunday, thanks for your patience.

**Comment by kangarko** [comment]
I am sorry, I can't reproduce.

Is clicking in the chat message right at when the book is signed broken? Works for me:

![a](https://i.imgur.com/SzWxBCo.png)

Also using /chc logs works fine:

![a](https://i.imgur.com/RT4eejN.png)

Tested on This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce

This must be a third party incompatibility. All I can say is that you need to allow all /chc and /chatcontrol commands to not be blocked, esp. the /chc internal or /chatcontrol internal

**Comment by Sakishima** [comment]
These commands ( /chatcontrol commands, /chc internal, /chatcontrol internal) helped solve the problem. Thank you very much.
