### ISSUE TITLE
Need help with wildcards

### ISSUE THREAD

**Issue by VulpusMaximus** [kangarko/ChatControl#287]
I can't find any documentation related to the wildcards used in the configs, maybe I'm just looking under the wrong name, but could you possibly link me to the correct page or explain them? By wildcards, I mean everything like \w, _, *, etc.

**Comment by VulpusMaximus** [comment]
The only thing I can find is at the top part of https://github.com/kangarko/ChatControl-Pro/wiki/Rules which explains what \b does

**Comment by kangarko** [comment]
Hello,

ChatControl both free and premium have not really consistent configuration. It depends where you want to use it.

If by wildcart you mean regular expressions, then they are supported in: Anti_Bot.Disallowed_Nicknames and Anti_Spam.Regex_In_Whitelists.

All files in rules/ folder support regex, however only the "match" and "ignore string" support full regexes in the free version.
