### ISSUE TITLE
Cluster System Does Not Work

### ISSUE THREAD

**Issue by SentorCraft** [kangarko/ChatControl#2870]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.28.1

### Steps to reproduce

Enable clusters on VelocityControl settings.
I have Redis server and enabled redis_integration.
Chat sync across servers does not work as intended.
All cross server messaging functions do not work.

**Comment by SentorCraft** [comment]
I think the problem is because of reload command.

**Comment by kangarko** [comment]
Does it work without reloading?

**Comment by kangarko** [comment]
Closing due to ghosted, comment below when you come back
