### ISSUE TITLE
Paper 1.21.1: bungee-plugin-message-channel handle not working after update

### ISSUE THREAD

**Issue by RikMichiel** [kangarko/ChatControl#2871]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### Question

I've set up ChatControl and VelocityControl. Everything is working as expected, however there's a bit in the setup instructions for VelocityControl that says to disable bungee-plugin-message-channel, but that VelocityControl will handle it instead. I use other plugin (HuskHomes) which won't work if bungee-plugin-message-channel is disabled. VelocityControl doesn't handle it automatically. The commands in the plugin just don't work cross-server anymore. How to fix this?

**Comment by kangarko** [comment]
I could not reproduce on my snapshot build, can you please wait 1-2 days before we release it to the public? Thanks for understanding. If it still happens there please provide steps to reproduce in the comment below.

**Comment by RikMichiel** [comment]
Hello, I have installed the latest version of VelocityControl (1.2.1-BETA) and the problem persists. Can you take a look at this?

**Comment by kangarko** [comment]
Apologizes, the issue turned out a bit more complicated. I will resolve it in the v11, please rollback for now.
