### ISSUE TITLE
chatcontrol.bypass.reach permission

### ISSUE THREAD

**Issue by audicu707** [kangarko/ChatControl#2872]
### Summary

chatcontrol.bypass.reach permission allows to do two irrelevant things. it would be better if the vanish and ignore part can be managed with two different permissions. for example i don't want my helpers to be ignored by the players but when i give them that permission they can send messages to the vanished players.

**Comment by kangarko** [comment]
Hello!

Thanks, good point. I will split it into chatcontrol.bypass.reach and chatcontrol.bypass.vanish in the upcoming ChatControl 11.
