### ISSUE TITLE
Paper 1.21.1: Command issue after server version update

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#2873]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

Hi, while on 1.20 my commands were working fine but, now that i've updated to 1.21.1 i'm getting this warning

https://paste.helpch.at/ayihiziguz.csharp

ChatControlRed v10.28.4

Any advice?

**Comment by kangarko** [comment]
I have honestly no idea about how commands.yml works as this is a spigot command, please ask on their discord, or, alternativelly use our rules/commands.rs to achieve the same.

**Comment by 00Hrtz** [comment]
> I have honestly no idea about how commands.yml works as this is a spigot command, please ask on their discord, or, alternativelly use our rules/commands.rs to achieve the same.

So i don't have to place the commands in the command.yml for commands i've created in chatcontrolred?

**Comment by kangarko** [comment]
Correct. Placing your commands from rules/ is completely unneeded.
