### ISSUE TITLE
Velocity network starts, but ChatControlRed on a specific server needs a reload for the cross-server messaging to work properly.

### ISSUE THREAD

**Issue by MisterMakey** [kangarko/ChatControl#2874]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### Question

Hello everyone. We have a strange issue that we have been able to solve temporarily.

We have a Velocity network with a total of 9 servers. Each night, we restart them. Since not all of them run on the same rack, we restart them in two steps: 5 servers at 4:00 AM and 4 servers at 4:30 AM.

Interestingly, there is currently one server that has a problem where ChatControlRed doesn't seem to handle the /msg function correctly. This means that /msg on this server only works for players who are also on this server and not for players on other servers. Interestingly, /tell works just fine.

If I reload the plugin, the problem is immediately solved, and the cross-server /msg feature is recognized right away.

This problem only occurs on this single server.

All servers have the same configuration settings and parameters. 

Do you have any idea why this might be happening and what we can do to fix it?"

**Comment by kangarko** [comment]
Thank you for finding and sharing the alternative solution for now. At this point, I am rewriting the plugin so my capacity to patch bugs (unless critical) for v10 is limited. Please re-test on v11 once it's out and tag me below should it continue to happen, thank you!
