### ISSUE TITLE
Version: Mohist 1.12.2

### ISSUE THREAD

**Issue by JIMER228** [kangarko/ChatControl#2875]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

latest versio

### Optional: Error log

none

### Optional: "/chc debug" file

Hello. I ran into a problem that plugin does not perform any functionality on the server, although it works, there are no errors in the console and there are no error.log files. The bottom line is, I'm in formats/that.the yml in the prefix section did this like this -
`  prefix:
    Message: '{%luckperms_prefix%}'
    Hover:
    - '&7{%luckperms_prefix%}{player_name} {player_suffix}'
    - '&7Ping&8: &f{ping}ms'
    - '&7Rank&8: &f{player_group}'
    - '&7Posted: &f{timestamp}'
    - ''
    - '&7Click to learn more about ranks.'`
   

### Steps to reproduce

An example of why the plugin does not work:

after I took away my "OP" rights, when sending messages to the chat, I was not given any warnings, etc., it didn't matter to everyone. 

The prefix is not displayed at all, whatever I did, I spent 4 hours solving the problem and it did not work.

**Comment by JIMER228** [comment]
I tried to write %luckperms_prefix% without "%" the same way.

**Comment by kangarko** [comment]
Can you try the {syntax} ?

**Comment by kangarko** [comment]
Also report is invalid. Latest is not a version, and no /chc debug is provided.

**Comment by kangarko** [comment]
Please also send me your full startup log and the /chc debug zip

**Comment by kangarko** [comment]
Closing: Invalid and inactive
