### ISSUE TITLE
Problems with chat and some emojis

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2877]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

ChatControlRed version 10.28.4

### Optional: Error log

no errors in console

### Optional: "/chc debug" file

https://ufile.io/qaty98ti

### Steps to reproduce

Good evening!
I have a problem with the chat... When I execute some commands and messages appear in the chat, they are displayed on the entire screen:

![image](https://github.com/user-attachments/assets/a47af568-c8f9-473f-abbd-fac582b1fbb4)

I think it's a problem related to itemsadder and its new version and it's affecting the chat

This is the emoji that is causing me problems: ☄
Some other emojis give these errors.

This is a template where these emojis are displayed. I have thought about removing them but I see that other plugins also use this type of emojis.:

kick_entry: " #b6d9d8ℹ #f5f5dc&lɪᴅ #b6d9d8$idRandom\n    #d9fd88♦ #f5f5dcᴛɪᴘᴏ\
  \ #d9fd88ᴇxᴘᴜʟꜱɪóɴ\n    #ff5348☄ #f5f5dcɪɴꜰʀᴀᴄᴛᴏʀ #ff5348$player\n    #a9c8ff🪓\
  \ #f5f5dcᴇxᴘᴜʟꜱᴀᴅᴏ ᴘᴏʀ #a9c8ff$executor\n    #ffd439⌚ #f5f5dcғᴇᴄʜᴀ #ffd439$dateStart\
  \ #6d6d6d(#f5f5dcʜᴀᴄᴇ $timeSince#6d6d6d)\n    #c19a6b✎ #f5f5dcʀᴀᴢóɴ #c19a6b$reason\n\
  \  "

**Comment by kangarko** [comment]
Unfortunately that is outside of the scope of this plugin. Try on vanilla client and report to itemsadder please.

**Comment by Z3r0xh** [comment]
> Unfortunately that is outside of the scope of this plugin. Try on vanilla client and report to itemsadder please.

I reported it to them and they don't have the problem, it's only with chat components.

**Comment by kangarko** [comment]
We do not cause the glyphs to render like this, I have honestly no idea what is causing this and have never had a report regarding this.

Try on stock client, no mods. And try on just ChatControl and ItemsAdder, no other plugins. If it does not happen without ItemsAdder than it's not our issue, I apology for not being able to resolve it.
