### ISSUE TITLE
ChatFormatter and chatcontrolred collisions

### ISSUE THREAD

**Issue by CitralFlo** [kangarko/ChatControl#2878]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

Hello, I'm a dev from EternalCode community and we  have got an report from one of your clients that there is some issue between chatcontrolred and our plugin chatformatter. Is there a way to resolve collision that occurs between these two plugins.

Our plugins main focus is to format chat messages that include placeholders, ranks, text formatting.
Chatcontrolred is used to censor/detect swear words and channels.
Using both plugins at the same time causes to not send formatted messages
Trying to lower the priority of your formatting does not resolve the issue and messages are not formatted at all.

# Question:
Is there a way to turn off formatting for normal chat messages? Probably without breaking censorship.
Or to integrate in some way those two plugins? We are open to resolving issue from our side

**Comment by kangarko** [comment]
I am always a fan of breaking censorship!

Now, in regards to that, you can just have Channels.Enabled to false in settings.yml, effectivelly not using the formatter, and then adjust https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities (in chatcontrol 10 there is an extra toggle saying to use modern chat, should be near the listener key). 

It's not possible to disentangle channels and rules because they are in one listener, so effectivelly you cannot "pre-format" the chat before we finally format it at the moment.

A solution would be to hook into our API's event ChatChannelEvent and do your formatting there. In the upcoming v11 there will be also an additional way of replacing placeholders, here is a sample code:

```java
package org.mineacademy.chatcontrol.api;

import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.mineacademy.fo.model.SimpleComponent;
import org.mineacademy.fo.model.SimpleExpansion;
import org.mineacademy.fo.model.Variables;
import org.mineacademy.fo.platform.FoundationPlayer;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;

/**
 * This class is automatically registered if your plugin uses Foundation,
 * if not then call {@link Variables#addExpansion(SimpleExpansion)} in your onEnable()
 * manually.
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class SampleCustomPlaceholders extends SimpleExpansion {

	@Getter
	private static final SimpleExpansion instance = new SampleCustomPlaceholders();

	@Override
	protected SimpleComponent onReplace(FoundationPlayer audience, String identifier) {

		// You can get the Bukkit sender and Players from the audience object
		final CommandSender sender = audience.getSender();
		final Player player = audience.isPlayer() ? audience.getPlayer() : null;

		// use {my_variable} or {chatcontrol_my_variable} if using PlaceholderAPI in your messages
		if ("my_variable".equals(identifier))
			return SimpleComponent.fromMini("<red>My &evariable");

		else if ("my_section_variable".equals(identifier))
			return SimpleComponent.fromSection("§cMy variable");

		else if ("my_adventure_variable".equals(identifier))
			return SimpleComponent.fromAdventure(Component.text("My variable").color(NamedTextColor.RED));

		else if ("my_plaintext_variable".equals(identifier))
			return SimpleComponent.fromPlain("My variable");

		return null;
	}
}
```

**Comment by perlsol** [comment]
This however is no good if we are using channels with chatcontrol, chatcontrol does not work with towny chat so are forced to use chatcontrol channels, this causes the knock on effect to the issue of breaking chat formatter plugin.
if you can just allow remormatting via other plugins after chc has done it's thing then priorities can work as intended

**Comment by kangarko** [comment]
Sure, that would be a priority for v11, but we do not plan on having two separate event listeners. Let me know if you need more adjustments on the upcoming v11
