### ISSUE TITLE
Version: Title Issue with Velocity Control

### ISSUE THREAD

**Issue by PlayGlowCraft** [kangarko/ChatControl#2879]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### Question

Im not sure if this is a bug. I updated to the lastest velocity control and suddenly im getting this. 
![Screenshot 2024-11-29 093607](https://github.com/user-attachments/assets/f8093f85-096a-4871-8c7c-84118f5c3ed7)

**Comment by kangarko** [comment]
Sorry, can you please explain and also send the requested /chc debug alongside velocity configs so I can try reproducing?

All I can see is the strange letter after TM but this can be normal esp. on legacy Minecraft versions which cannot process some new characters if you use them

**Comment by PlayGlowCraft** [comment]
sorry. I will try to explain better. There are no errors. I have the bungee setup for the cross server chatting. It was working fine till i updated to the latest velocity control Now when anyone types instead of the message going to the other server it produces the bungee message twice on each server  example if im on the earth server as the picture above shows. it should just show the message without the Green E and then on the other servers show the message with the green E. Now it shows the regular message on earth and then also shows the message with the green E on earth as well.
[debug.zip](https://github.com/user-attachments/files/17967614/debug.zip)

**Comment by PlayGlowCraft** [comment]
Its not doing it on 1.1.1 which was the version i was using previously

**Comment by kangarko** [comment]
Investigating, should be handled in 1-2 days. Please stay on the old version for now.

**Comment by kangarko** [comment]
Please roll back to 1.1.1 for now, the issue will be completely address in the upcoming 2.0.0 rewrite.

**Comment by PlayGlowCraft** [comment]
will stay put for now thanks :)
