### ISSUE TITLE
Can't escape | in rules

### ISSUE THREAD

**Issue by RuiNtD** [kangarko/ChatControl#288]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

Hello. There needs to be a way to escape | symbols in rules files, such as:
`then command chc announce image warning.png 8 \|\|\|Server restarting\|in 1 minute!`

**Comment by ElBananaa** [comment]
Hey! Could you try using `❘` instead of `|`? :)

**Comment by RuiNtD** [comment]
I need to use | for the formatting with `/chc announce image`, which replaces `|`s with new lines.

**Comment by kangarko** [comment]
Thanks, will be added!
