### ISSUE TITLE
Config Wrong

### ISSUE THREAD

**Issue by Inspectiver** [kangarko/ChatControl#288]
So ChatControl is not working, I think it is because I have messed up the config, and I think it is in the Broadcaster section. I have tried re-freshing the config but after I have edited it it stoips working again, so I must be doing something wrong. I have tried putting ' and ' after every broadcast incase but I didn't think that was the problem. I think their may be something else wrong as well as the broadcaster section. Anyone know what is happening?
https://pastebin.com/LT10anQs

**Comment by kangarko** [comment]
You have to put quotes around all broadcastes, it seems you missed this:

![a](https://i.imgur.com/zGsqhPB.png)

Next time please use https://yaml-online-parser.appspot.com/ to check configurations.

**Comment by Inspectiver** [comment]
That does not fix it, I tried

**Comment by kangarko** [comment]
Post me the error.
