### ISSUE TITLE
Paper-1.21-130. Setting Global and Local chat

### ISSUE THREAD

**Issue by TheReizi** [kangarko/ChatControl#2881]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

I don't understand how I can set up global and local chat so that if there is an ! (exclamation mark) at the beginning of a message, it will be sent to global chat

**Comment by kangarko** [comment]
Hello,

Sure, first create the two channels in Channels.List in settings.yml. Then place this rule to rules/chat.rs:


````
# Uncomment to forward any message starting with ! to bungee channel
match ^[!](.+)
then command ch send global $1
strip colors false
strip accents false
dont verbose
then deny
````
