### ISSUE TITLE
Paper 1.21.1: bungee-plugin-message-channel handle not working after VelocityControl update

### ISSUE THREAD

**Issue by RikMichiel** [kangarko/ChatControl#2882]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

v10.28.4

### Optional: "/chc debug" file

I've set up ChatControl and VelocityControl. Everything is working as expected, however there's a bit in the setup instructions for VelocityControl that says to disable bungee-plugin-message-channel, but that VelocityControl will handle it instead. I use other plugin (HuskHomes) which won't work if bungee-plugin-message-channel is disabled. VelocityControl doesn't handle it automatically. The commands in the plugin just don't work cross-server anymore. 

I've sent you an issue about this before, but it was marked as closed while the issue still persists. That's why I've made a new one

I've also contacted the developer of HuskHomes, who says that bungee-plugin-message-channel has to be enabled. So VelocityControl should fix this according to the wiki.

How to fix this?

### Steps to reproduce

- Setup a velocity network with at least 2 backend paper servers
- Install VelocityControl on velocity proxy 
- Install ChatControlRed and HuskHomes on every backend server
- Set bungee-plugin-message-channel to false in velocity.toml
- Try to teleport between servers using /huskhomes:tp (name), while bungee-plugin-message-channel is set to false

**Comment by RikMichiel** [comment]
I'm using VelocityControl v1.2.1-BETA now btw

**Comment by kangarko** [comment]
Please rollback to 1.1.1 for now, as per the changelog: https://builtbybit.com/resources/velocitycontrol-cross-network-chat.43226/updates

The new builds are in preparation but require more time and will require the new ChatControl as well, but the 1.1.1 is perfectly stable. I apology for the inconvenience.

**Comment by RikMichiel** [comment]
Hello Kangarko,

I have updated VelocityControl to version 2.0.4-BETA and ChatControl to version 11.0.4-BETA

The issue still persists. Whenever I try /tpa (name) the command won't work cross-server because I set bungee-plugin-message-channel to false. I'm still using HuskHomes plugin. The plugin works fine with bungee-plugin-message-channel set to true.

Can you fix this please?

**Comment by kangarko** [comment]
Please try using the next version I will put out today and let me know how it goes.

**Comment by RikMichiel** [comment]
Updated to VelocityControl v2.1.4 and ChatControl v11.1.4 and it works! thank you!
