### ISSUE TITLE
Use more than two hex colours in chat formatting

### ISSUE THREAD

**Issue by therealaqz** [kangarko/ChatControl#2883]
### Summary

Hey there. I recently saw a player's rank from another server look like this:
![SkyGodLook](https://github.com/user-attachments/assets/38d2500d-a485-4500-b808-4aab4162cdde)

I tried doing it in the ChatControl chat.yml formats file:

**Before: (Only using two HEX colors in gradient)**
```
  player-name-skygod:
    Message: '{player_displayname}'
    Gradient: '#F4342E - #5555FF'
```

**After: (More than two HEX colors with gradient, with Errors)**
```
  player-name-skygod:
    Message: '&l{player_displayname}'
    Gradient: '#F4342E - #FF982E - #08F944 - #13FFDC - #5555FF'
```

From the error message, it seems I can only use two hex colors. I would greatly appreciate the ability to use multiple hex colors, ideally six or more. Thank you!

If this is just a formatting issue that I did myself, I'd appreciate any suggestions or help. 

Thank you

**Comment by kangarko** [comment]
This limitation will be resolved in v11 where you can just use minimessage gradient tag ;)
