### ISSUE TITLE
Tracking messages count per timeframe?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2885]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

Hello, is there possibility to track messages by specific user within specific timeframe? Is there placeholder?

I'd like to reward users every 10m for example if they send around 100 messages or so. Can it be done somehow?

**Comment by kangarko** [comment]
Theoretically yes but that is out of scope for this plugin, I recommend you code your own plugin since it's not that hard to count.

**Comment by bobhenl** [comment]
Oh :/ I thought if some placeholder cannot be added with total messages or messages per specific timeframe, but yeah own plugin could solve it too.

**Comment by kangarko** [comment]
For now not a priority, with the amount of work with v11 every new feature like this means the release will get further postponed (it's been postponed since August already)
