### ISSUE TITLE
Nick issue

### ISSUE THREAD

**Issue by therealaqz** [kangarko/ChatControl#2886]
### Summary

Hey there. 

I have an issue where once I do /nickname off, it turns off my nickname successfully but once I rejoin the server it automatically reverts back to my previous nickname despite it having been turned off.

I've contacted the EssentialsX team but no success so far, is this an issue with ChatControl? 

`%essentials_nickname%` 
I used this placeholder in the ChatControlRed format config

**Comment by kangarko** [comment]
Mind posting `/chc debug` please?

**Comment by VouchWasHere** [comment]
Sure! Here you go:

[debug.zip](https://github.com/user-attachments/files/18031714/debug.zip)

**Comment by therealaqz** [comment]
Hey there, I've sent the debug file to support@mineacademy.org via dropbox.

**Comment by kangarko** [comment]
Try setting Tag.Backward_Compatible to true in settings.yml, that should resolve it and let me know how it goes below!

**Comment by therealaqz** [comment]
Hey there! I did `Backward_Compatible: true` and it still re-applies my nickname after turning it off and then re-joining.

I also disabled EssentialsX and re-joined but it did the same thing.

**Update:**

Found out someone on my server added in HexNicks which was the issue. I removed it and it successfully managed to resolve the issue. Thanks for your help and assistance Matej!

**Comment by kangarko** [comment]
No problem, thanks for keeping me posted and thanks for sharing the solution!
