### ISSUE TITLE
Issues with VelocityControl

### ISSUE THREAD

**Issue by Kaludii** [kangarko/ChatControl#2887]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.28.4

### Steps to reproduce

Hello, I'd like to report critical issues with VelocityControl's network-wide chat functionality. Our server environment uses MariaDB database with a Velocity proxy, and we are running the latest version of ChatControl Red (10.28.4) along with the latest velocity version.

The primary issue is a severe connection pool overload. Despite trying various connection limit settings (100, 150, 200), the server consistently hits the MariaDB connection limits, which results in players being kicked from the server and us losing access to the pterodactyl panel. This occurs even with minimal player load, we experienced these issues with as few as 2 players on the network.
This seems related to GitHub issue #2521 which documents MySQL connections not being properly closed.

We have attempted several solutions without success. These included adjusting the MariaDB connection limits multiple times, adding `&allowPublicKeyRetrieval=true` to the connection string, setting autoReconnect to false, and maintaining HikariCP enabled to prevent worse performance degradation. None of these attempts resolved the underlying issue.

Additionally, there is a separate bug where the `{server_name}` placeholder is not functioning correctly when players join or leave the server network. It only works properly during server transfers.

To reproduce these issues:
Simply enable network-wide chat with multiple backend servers connected to the same database, we are using 5 backend servers. Add even a single additional player to the network, and you'll observe database connections rapidly increasing until hitting the connection limit, regardless of what that limit is set to. Note that both the database and the servers are hosted on our dedicated machine.

Config:
```
# Use an external database to store logs, mails and user data (channels, nicks, etc.)?
# If false, then we store these date into your data.db file.
Enabled: true

# Enable HikariCP connection pool?
#
# NOTE: If having too many open connections (https://github.com/kangarko/ChatControl-Red/issues/2521)
# Try adding &allowPublicKeyRetrieval=true (or false) at the end of "Line" key, and changing autoReconnect
# from true to false. Test various combinations or eventually set this key to false as last-resort solution.
Hikari: true

# ADVANCED: The full connector line, do not modify unless you know what you are doing.
# If facing issues try appending &useUnicode=yes&characterEncoding=UTF-8 at the end.
#
# Use 'jdbc:mysql://' if you are running a mysql database.
# Use 'jdbc:mariadb://' if you are running a mariadb database.
Line: jdbc:mysql://{host}/{database}?autoReconnect=false&useSSL=false&allowPublicKeyRetrieval=true
```

![image](https://github.com/user-attachments/assets/43943c0c-2f47-4563-8df8-cd75de0eef10)

![image](https://github.com/user-attachments/assets/9a085108-ba26-452b-8c5d-f00d3241641e)

**Comment by kangarko** [comment]
Hey and thank you for reporting.

The issue lays in that Hikari creates about 10 connections using its connection pool by default, For now I advise you to set Hikari to false in the file above to use another MariaDB driver which only opens 1 connection each time.

Regarding the placeholder issue, have you tried using {server} instead of {server_name}? I am in the process of rewriting the plugin and will consolidate the variables then.
