### ISSUE TITLE
Version: MSG 

### ISSUE THREAD

**Issue by AlphaBlock4k** [kangarko/ChatControl#2888]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

10.28.2

### ZIP of "/chc debug"

https://ufile.io/bvrolgzy

### Steps to reproduce

After I updated chatcontrolred I can no longer write an MSG that says the player is not online, I switched back to the old version and everything works. Has anything changed that ?

**Comment by kangarko** [comment]
You can continue using the latest ChatControl Red but make sure to keep VelocityControl on 1.1.1. I am currently working on this, thanks.

**Comment by AlphaBlock4k** [comment]
@kangarko 
Hey, sorry for answering so late,
But you already know that I don't use velocity control, right? 
I have bungecontrollred?
what is the solution there

**Comment by kangarko** [comment]
No problem. Stay on the old version until ChatControl 11 is out, then update both BungeeControl and ChatControl and let me know if you will still observe the issue.
