### ISSUE TITLE
/{label} internal remove {message_uuid}

### ISSUE THREAD

**Issue by hammad-alhassan** [kangarko/ChatControl#289]
hi can you add anything in the beginning of the command for example `/dltmsg {label} internal remove {message_uuid}` so that i can add this command to whitelist and be able to use it cause in my network am blacklisting all the commands and whitelisting the commands that players can use but i cant add /{label} to whitelist

**Comment by hammad-alhassan** [comment]
sorry for inconvenience in wiki variables
 
{label} | Return our main command label.
which is `chc`

**Comment by BenjaminHoegh** [comment]
do that command work for you?
