### ISSUE TITLE
Paper 1.21.3: Question Regarding PlaceholderAPI For VelocityControl

### ISSUE THREAD

**Issue by Kaludii** [kangarko/ChatControl#2892]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### Question

Hello, we have a few backend servers and use VelocityControl for network-wide chat, however, when users join/leave, is there a way to have the placeholder that works in one server shown to the network? For example, in the image below, this is my staff rank and nickname, I'd like it to be shown to the network, but in the other servers it just shows the placeholder with no information.

![image](https://github.com/user-attachments/assets/190c1558-0fed-4211-80c5-dc13e3c8136a)

**Comment by kangarko** [comment]
If v11, this will be fixed. Such as you will be able to use {player_nick} in your proxy join messages on VelocityControl and this will get replaced by the nick consistently over all servers.

**Comment by Kaludii** [comment]
> If v11, this will be fixed. Such as you will be able to use {player_nick} in your proxy join messages on VelocityControl and this will get replaced by the nick consistently over all servers.

Hey there, we updated to the latest v11.1.0 version, however, the luckperms placeholder just shows the raw text, and the {player_nick} still shows my username. My nick across all our backends is "Kaludi". We are on Paper 1.21.1 and use EssentialsX on the backends for the nickname.

```
# group helper
# require sender perm staffchat.join
# message: 
# - &8[&a✔&8] {luckperms_prefix_element_highest_on_track_staff} &7{player_nick} has joined the server.
```

![image](https://github.com/user-attachments/assets/4cadd535-f0bd-4b77-a77f-3177af45a643)

**Comment by kangarko** [comment]
Is this message set on Velocity or Bukkit? Afaik only Bukkit  supports these extended variables. Also what is the problem with the nick, sorry I don't see it?

If this is on Bukkit, please check with /papi parse me %luckperms_prefix_element_highest_on_track_staff% that it works fine. Also check with /chc info variable yourname {luckperms_prefix_element_highest_on_track_staff} and let me know the outcomes

**Comment by Kaludii** [comment]
The message is set on Velocity, but we were able to resolve the prefixes by adding each group to its own specific prefix.

In regards to nick, even though I have a nickname set to "Kaludi" from essentialsx, it still shows my username "Kaludii" (two i's), even though I am using the {player_nick} placeholder. Is it possible to show my nickname that is set on essentialsx network-wide? In the documentation it mentions that the nick variable is taken from player's Bukkit server, and I have the same nickname in all of our backend servers.

Console:
```
papi parse Kaludii %essentials_nickname%
[14:31:39 INFO]: Kaludi
chc info variable Kaludii {essentials_nickname}
[14:31:42 INFO]: Result (took 0ms): Kaludi
chc info variable Kaludii {player_nick}
[14:31:44 INFO]: Result (took 0ms): Kaludii
chc info variable Kaludii {player_has_nick}
[14:39:29 INFO]: Result (took 3ms): true
```

**Comment by kangarko** [comment]
Thanks, I'll get to you on the network-wide essentials prefix in 24 hours

**Comment by kangarko** [comment]
Do you have Tag.Backward_Compatible on true in settings.yml?

**Comment by Kaludii** [comment]
Oh, I did not have it enabled, setting it to true resolved it, thank you!
