### ISSUE TITLE
1.21.4: What is PAPI placeholder for chatcolor & decoration?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2894]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

Hello, on this page https://github.com/kangarko/ChatControl-Red/wiki/Variables I don't see PAPI placeholder for:
{chat_color}{chat_decoration}

what it is, please?

**Comment by kangarko** [comment]
In ChatControl v11 it will be %chatcontrol_player_chat_color% in PlaceholderAPI .

Simply add the chatcontrol prefix in front. Keep in mind you must use the {} syntax in chatcontrol and %% in papi
