### ISSUE TITLE
Paper 1.21.3: Channel Visibility Issue

### ISSUE THREAD

**Issue by etztrefis** [kangarko/ChatControl#2895]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

10.28.5

### ZIP of "/chc debug"

The issue occurs when a player joins a server and sends a message in chat. The message is sent to the Standard Channel, but players on other servers can also see messages from the Standard Channel of a different server.

I expect the Standard Channel to function as a local chat that is visible only to players on the same server. Messages sent to a Global Channel should be the only ones visible to all players across the proxy network.

I had the expected behavior on a 1.21.1 server with ChatControl version 10.21.14. However, I am not sure what has changed with the new updates, as this issue did not exist in the earlier setup.
[debug.zip](https://github.com/user-attachments/files/18129542/debug.zip)

### Steps to reproduce

1. Set up a BungeeCord network: Include at least two backend servers running Paper.
2. Install BungeeControl: Add the BungeeControl plugin to the BungeeCord proxy server.
3. Install ChatControl Red: Add the ChatControl Red plugin to each backend Paper server.
4. Join the server: Connect to the BungeeCord proxy.
5. Send a message in chat: Type and send any message to observe the behavior.

**Comment by kangarko** [comment]
Can you set the Bungee key to false in the standard channel? This will make it not broadcast over proxy. By default it's enabled.
