### ISSUE TITLE
1.21.4: Stuck in old version?

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#2896]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### Question

VCR 3.11.7, CHC 10.23.3

I don't want to leave a negative review just to question this, and I can't find any links to the discord support server, so I opened here (this project is infamously badly linked, you should at least post a clear discord link somewhere). 

Today I paid for velocity control red, even though it can likely be built manually, mainly to support this long standing plugin, and since I've been using it for most of it's lifetime, but also because I need to update it.

I am currently stuck with a version of chatcontrol red that potentially kicks players when they talk (I can't really confirm this but it's an old version so it's likely to be the main cause since it handles chat).

But can't update on velocity and paper, because the latest recommended version of velocity control red doesn't support latest velocity, correct?

Which means I'd be forced to downgrade Velocity to a version below mc 1.21.4. This would mean denying access to bedrock users, and latest Java version users.

And the velocity control red download that did support latest velocity is no longer available. AFAIK with a flag I could have still loaded the plugin.

I just want some info on this whole situation and potential workarounds since paying for the product for like the 3rd or so time I at least expected it to work.

**Comment by kangarko** [comment]
Hello!

I am sorry you are having issues.

The link to our discord is mineacademy.org/discord, it's also posted as a button image at the Overview page, did you miss it?

![2024-12-16-00 38-736](https://github.com/user-attachments/assets/b5c93342-0485-4c72-a686-0a3b1e3524a2)

I already made a fix inside Velocity which [Paper devs rejected](https://github.com/PaperMC/Velocity/issues/1462). 

Please use the startup argument "-Dlog4j2.julLoggerAdapter=org.apache.logging.log4j.jul.CoreLoggerAdapter" for now or rollback to an older Velocity build until this get resolved. 

All VelocityControl and other Velocity plugins using the Nashorn library are affected. Hopefully Paper will push the fix or the new log4j library which has the bug will release its new major version soon and they will do it.
