### ISSUE TITLE
Version: 10.28.5 / BungeeCord: 3.18.0-BETA

### ISSUE THREAD

**Issue by Robin-Arnhardt** [kangarko/ChatControl#2897]
### Are you using MySQL?

No

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

10.28.5

### Optional: Error log

https://prnt.sc/uBvSB1pfbduR | https://prnt.sc/IVQL3ZAYTJPF

Spigot Version: https://prnt.sc/DWeRn2ru6iPl | Bungee Version: https://prnt.sc/xDqaAaKG9oy3

### ZIP of "/chc debug"

Hello, since i installed ChatControl Red on Spigot and BungeeCord player cant join the server and i get this error messages.

Hopefully you can fix it. Bungee is in all configs included bungee.yml activated

Regards!

### Steps to reproduce

Edit the config and enabled all bungee options

If i deinstalled the Plugin, my server works fine. If i installed the Plugin JUST on Spigot Server, it works to

**Comment by kangarko** [comment]
Can you rollback to pre-BETA versions of BungeeControl?

**Comment by kangarko** [comment]
Let me know if it's fixed there

**Comment by Robin-Arnhardt** [comment]
Now i use Paper and get this error, i use the version before the BETA Version: https://prnt.sc/_9P_qAbXoOG9 ...

**Comment by kangarko** [comment]
Use ChatControl v10.28.5.

**Comment by kangarko** [comment]
Just downgrade BungeeControl but keep ChatControl the latest.

**Comment by kangarko** [comment]
Solved on ccr 11
