### ISSUE TITLE
/mail Error

### ISSUE THREAD

**Issue by Robin-Arnhardt** [kangarko/ChatControl#2898]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.28.5

### Optional: Error log

https://prnt.sc/w0qpzqikTARE | https://pastebin.com/1PMdBg0H

### ZIP of "/chc debug"

Hello, i get error if i type the /mail inbox command and wanna open the Mail (https://prnt.sc/56grI-6nOePc) after i click on this hover, i get the error (mail open)

I also get this error on /mail autor view: https://pastebin.com/bKSN2dZu

### Steps to reproduce

Show error logs

**Comment by kangarko** [comment]
You're on CraftBukkit? Please use Paper.
