### ISSUE TITLE
1.16.4 BungeeCord - Player not connected through BungeeCord and commands failing

### ISSUE THREAD

**Issue by Godlycreations** [kangarko/ChatControl#29]
Test group: 1.16.4 BungeeCord with MySql

I have done a clean install of CHC red on two of my servers and created a new proxy server for testing purposes. I have configured only the MySql database as well as enabled bungeecord. I am put into ranged chat by default and can talk, It gives the following when entered into the chat:

[ranged] {Admin} Friend_Of_God: test
<Friend_Of_God> test

Not sure why it is doubling everything that is said, but this is the basic out of box install, I have not attempted to adjust the channels yet.

When I attempt to change to any other channel using /ch j admin, /ch j global, or /ch j standard, I get a message in chat that states that I am not connected through BungeeCord

When I attempt to use the command /ch list, it tells me that the command failed and to check console and report the error.

I get the same error when I use the commands /ch s admin, /ch s global, and /ch s standard, the only difference is that it will send the message to each of those channels in chat as it is supposed to before showing the error of the command failing.

These errors occur on both of the servers that are connected to the proxy, I am attaching both error logs to this issue report. If there is anything else that you need from me, please let me know. I will keep these two servers and proxy set up for any additional testing that you need. Thank you for all the hard work you are putting into this plugin, I am excited to see it all come together.

In your service,
FoG

[Elyon-error.log](https://github.com/kangarko/ChatControl-Red/files/5526671/Elyon-error.log)
[Endless-error.log](https://github.com/kangarko/ChatControl-Red/files/5526672/Endless-error.log)
[proxy_log.txt](https://github.com/kangarko/ChatControl-Red/files/5526706/proxy_log.txt)

**Comment by kangarko** [comment]
Thank you. I apology for the mess of including BungeeChatAPI not BungeeControl Red in the ZIP. Will fix that to the next release. Remove BungeeChatAPI and BungeeControl 2.x.x from BungeeCord, and only place the new BungeeControl Red there from next release's zip file.
