### ISSUE TITLE
Faction Compatibility - Question

### ISSUE THREAD

**Issue by HelloIsaac** [kangarko/ChatControl#29]
Hi, quick question: what (if there is one) is the variable to add a faction name (from the Factions plugin) into the chat? I'm trying to get:

"[Faction] [Prefix] Display Name: Message"

And have everything except the [Faction] tag in place with ChatControl, but can't find any documentation on how to add the faction information.

Thanks!

**Comment by kangarko** [comment]
Hey! I guess you have found it: it's %faction
Not sure if the free version has it, but it is included by default in premium.

**Comment by HelloIsaac** [comment]
Thanks a lot for your help :) I did find it! Love the plugin, and definitely upgrading to support your development once my server launches.
