### ISSUE TITLE
[ISSUE] Chat duplication

### ISSUE THREAD

**Issue by ScottGB** [kangarko/ChatControl#290]
Minecraft Version: 1.16.4 (paper-331)
MySQL: true
BungeeCord: true

For some reason if I type a message on my admin account from the Creative server, the message will be duplicated as follows on other servers. The issue doesn't persist so long as I'm on any other part of the network or if I remove my admin rank.
https://i.imgur.com/2TxB6Ak.png

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5713404/debug.zip)

Permissions:
As admin:
'*' (which includes all chc)

As regular:
chatcontrol.channel.autojoin.standard.write
chatcontrol.channel.join.standard.write

**Comment by kangarko** [comment]
I see you have ViaVersion and CMI, try removing these plugins or any other plugin who's managing chat and see if you can isolate this issue purely to ChatControl please.

Thank you.

**Comment by ScottGB** [comment]
Hi. Sorry, but it was a CMI issue. Resolved with an update.
