### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fred112f** [kangarko/ChatControl#290]
Is there any way to obtain private message sender's displayname and receiver's displayname?

**Comment by fred112f** [comment]
Is there is a way to send messages with prefixes like @sc (staff chat) that broadcast to the staff_chat channel that are sent instantly?(without the player needing to join and quit the channel, just sending one message that doesnt have to do with what channel you are in,(doesnt add you to the channel), you only need the permission for it)

**Comment by kangarko** [comment]
Hello,

sorry no there is no way for private message's to have display name.

For the second questions, I assume you have the Pro version: You can create an alias /sc that will send a message to the channel Staff Chat, see Command Aliases (https://github.com/kangarko/ChatControl-Pro/wiki/Shortening-Commands)
