### ISSUE TITLE
Paper 1.21.1: Parsing PAPI Placeholder in MOTD msg

### ISSUE THREAD

**Issue by NoxNap** [kangarko/ChatControl#2900]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.0.0-BETA

### Optional: Error log

https://mclo.gs/C2bHvH0

### ZIP of "/chc debug"

[debug-1.zip](https://github.com/user-attachments/files/18204668/debug-1.zip)

### Steps to reproduce

- Bug report created in reference to this https://discord.com/channels/360404674219737100/755325303689052200/1319448149169012786
`[01:02:16 INFO]: This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)`

Summary: In CHC v11 my MOTD message broke; it had `- '<#ce5631>{nexo_chatline} Welcome back, &f%utils_parse:2_katsu_player_{player_name}_small% {player_name}'` but it was not parsing `%utils_parse:2_katsu_player_{player_name}_small%` correctly. I assumed it was the usage of `%` so switched it, but no dice in any combination of setups. I then tried just parsing the placeholder and nothing else (`{katsu_player_MyUser_small%`), it disconnected me from the server.
- [disconnect-2024-12-19_19.16.07-client.txt](https://github.com/user-attachments/files/18204656/disconnect-2024-12-19_19.16.07-client.txt)
- ![image](https://github.com/user-attachments/assets/22c361a9-316a-4e11-86cb-f634ecb715a1)
None of this was happening on CHC v10.28.5 — it parses correctly when testing through PAPI; No disconnection.
- ![image](https://github.com/user-attachments/assets/e1a0c37e-ec49-4c68-9dcc-310d5fdfa83b)
Given Error log is from trying what `The Intolerant` said which was using `{utils_parse:2_katsu_player_%player_name%_small}` to parse, didn't solve anything though so I assume just invalid formatting (can't use `%` inside of `{` or whatever)

Lemme know if there's anything else I can provide.

**Comment by kangarko** [comment]
Thanks, investigating. Can you please send me your old backup folder via matej(at)mineacademy.org too? I'll also test if it got migrated properly.

**Comment by kangarko** [comment]
Please try the next version and re-migrate your folder if possible, let me know how it goes, thanks! (It will come out in about 1h)

**Comment by NoxNap** [comment]
Hey, I'm still having the same problems. Not sure what info you'd like as it really is just same exact info initially mentioned. I did re-migrate my folder (renamed the backup folder to ChatControlRed and deleted ChatControl folder).

**Comment by kangarko** [comment]
I will introduce the ability to double-parse variables in the next release, let me know how it goes!

**Comment by NoxNap** [comment]
Hey, still having the disconnection problem as of 11.0.4-B -- whenever this `{utils_parse:2_katsu_player_{player_name}_small}` is done and CHC is reloaded if I do /motd it will disconnect me from the server until I remove that line. I have Support_Variables_In_Variables: true and as far as I can tell it's all the exact same as above mentioned problem.

Edit: added console log for what happens after adding the placeholder to MOTD; the problem persists only when trying to use that placeholder in ChatControl, can use papi parse and see it fine, can use it in holograms, etc..
- https://bin.birdflop.com/zejuzumidi.csharp

**Comment by NoxNap** [comment]
Reported on ViaVersion discord too; one of their 'helpful' role members (not sure if they're official support or not) mentioned
> it i[s] probably chatcontrol sending bad packets, so either chatcontrol has to change them, or viaversion has to make a part of code to understand them correctly, but for the last it has to be open source (https://discord.com/channels/316206679014244363/316208160232701955/1323475350503686184)


see here for beginning context n info if interested: https://discord.com/channels/316206679014244363/316208160232701955/1323463276796969054 (assuming you are in the ViaVersion discord). If I need to open a new bug report let me know but this seems pretty much same as original post as it's still disconnect problems when using the placeholder originally mentioned.
cc @kangarko

**Comment by kangarko** [comment]
Unfortunately that issue looks like it's either from ViaVersion or adventure-platform which we use to send messages, We do not send any chat packets. I don't have time scrolling through that discord link but you can send me the relevant information from it if it still happens.

Also make sure to set ProtocolLib.Enabled to false in settings.yml and see if the issue was resolved.

**Comment by NoxNap** [comment]
Tried on v11.0.4-B with the ProtocolLib.Enabled=false and that did not fix it. BUT in CHC v11.0.6-B the problem is fixed (without having to disable ProtocolLib). Not exactly sure what fixed it... but hey, at least it's working!
![image](https://github.com/user-attachments/assets/2eae9aae-11c2-452e-82af-f71ffed65d29)

**Comment by kangarko** [comment]
We fixed it :)
