### ISSUE TITLE
Paper-1.21.1: Error in console

### ISSUE THREAD

**Issue by TheReizi** [kangarko/ChatControl#2901]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.28.5

### Optional: Error log

https://pastebin.com/g7T9Upxc#4RVwgV2q

### ZIP of "/chc debug"

> chc debug
[04:31:44 INFO]: Cannot use this command while the plugin is disabled.

### Steps to reproduce

Everything was fine, it was functioning normally, but after today's launch this error appeared

**Comment by kangarko** [comment]
Hello,

I haven't changed anything in 10.28.4, but the error says that your log.csv file has wrong structure on line 1. You can simply remove that line. If the error continues you would need to remove and reset that file completely.
