### ISSUE TITLE
require $2

### ISSUE THREAD

**Issue by d0ddn** [kangarko/ChatControl#2902]
### Summary

I want to send messages to a specific player after a specific event
```
match ^/(.*)
require variable {player_name} $2
then toast AMETHYST_SHARD CHALLENGE You did it!
then deny
```

**Comment by kangarko** [comment]
The $2 in require variable is the wrong usage. For performance reasons we do not parse the required value. It will always be matched against the literal $2 so it will be false. Find another design that suits you.
