### ISSUE TITLE
Purpur 1.21.4 - {player_nick} not working with Essentials

### ISSUE THREAD

**Issue by MarkThePanda** [kangarko/ChatControl#2903]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

2.0.0

### ZIP of "/chc debug"

[debug (1).zip](https://github.com/user-attachments/files/18208926/debug.1.zip)

### Steps to reproduce

{player_nick} is being used in global-chat, chat, motd, and other locations. Backward compatible is enabled. ChatControl is not recognizing Essentials nicknames and is only returning player name.

**Comment by BAD7777** [comment]
I support this. I want a colored nickname (plugin hexnicks), but it shows an error.
https://mclo.gs/HLt9XX4

**Comment by kangarko** [comment]
Confirmed, fixed: https://github.com/kangarko/Foundation/commit/0d4395f568155754346cb825d83ff47e0aff2fe3
