### ISSUE TITLE
img holders items adder not working Version: 1.21.1

### ISSUE THREAD

**Issue by LixaSl** [kangarko/ChatControl#2904]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11

### Steps to reproduce

Display of prefixes does not work - pictures of items adder
![image](https://github.com/user-attachments/assets/c96313d6-4d0b-4d88-a30e-1af7c46ae1f1) - luck perms prefix

![image](https://github.com/user-attachments/assets/dd6f1ebd-4098-47bf-bd38-f56eeedda7e8) - chat config prefix

![image](https://github.com/user-attachments/assets/0b1b2d0e-aed2-465a-8237-29d059969947) - Tab works great as all other plugins

![image](https://github.com/user-attachments/assets/12c6ce89-926e-43e4-ad5c-d32c39b62066) - But, not a chat

**Comment by Energobro** [comment]
can confirm ye

**Comment by kangarko** [comment]
Need 48 hours to investigate

**Comment by kangarko** [comment]
I will readd this in todays update.

**Comment by kangarko** [comment]
@LixaSl please try on the next version that I will release today

If it will continue to happen, what plugin are you using for img_offset variable? Are you using PlaceholderAPI? If yes which extensions do you have installed?

**Comment by LixaSl** [comment]
> @LixaSl please try on the next version that I will release today
> 
> If it will continue to happen, what plugin are you using for img_offset variable? Are you using PlaceholderAPI? If yes which extensions do you have installed?

im use Items Adder for prefixes
your plugin just doesn't work papi in papi, that is, it displays folders but does not format the context

ChatControl 11.1.0
![image](https://github.com/user-attachments/assets/5c8762e6-f3fb-4c80-a8bd-22f235b8efa9)

**Comment by LixaSl** [comment]
I sent you a link to a video with a bug by email

> @LixaSl please try on the next version that I will release today
> 
> If it will continue to happen, what plugin are you using for img_offset variable? Are you using PlaceholderAPI? If yes which extensions do you have installed?

**Comment by kangarko** [comment]
Thanks, will investigate in 24 hours

**Comment by kangarko** [comment]
Finally got it done, sorry, took longer than expected.

Set Performance.Support_Full_PlaceholderAPI_Syntax to true in the next version.

Also I recommend getting rid of the offset. You will also need to use the mini syntax for hex. This is what I am using:

`%img_admin%<#7634ff> ` (note the space at the end)

![a](https://i.imgur.com/6mOXVD1.png)
