### ISSUE TITLE
1.20.6 RGB Chat Color Bug

### ISSUE THREAD

**Issue by Zsomi** [kangarko/ChatControl#2905]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.0.0-BETA

### Optional: Error log

No Error.

### ZIP of "/chc debug"

https://ufile.io/dy5nxcce

### Steps to reproduce

Using default config files, formats etc.
In the future if you set the ch color menu to level you will get the same bug.

1. Upload the plugin to plugins directory
2. Restart the server
3. Type any text in chat.
4. See Bug

![{797174CF-A439-4778-83DC-77C026332152}](https://github.com/user-attachments/assets/fc27285b-c64e-4bd6-9f8a-e38e41856d2f)

**Comment by kangarko** [comment]
Thanks, I will add a migrator for %variables% and &# color codes.
