### ISSUE TITLE
[Version: Pufferfish 1.21.3]  Hex color parsed from plugin hooked with PAPI not displaying corretly. + Chat not being displayed if 'evertthing:' parts not existed.

### ISSUE THREAD

**Issue by Pattanawaris** [kangarko/ChatControl#2906]
### Are you using MySQL?

No

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

11.0.0BETA

### Optional: Error log

No errors just display issue.

### ZIP of "/chc debug"

Debug files and addtional pic sent via email with a title of [CHC11 Github. #2096-Pattanawaris]

### Steps to reproduce

since it's just display issue no need to reproduce or you may want to try my config in debug that has been sent to you.

**Comment by Pattanawaris** [comment]
update: email sent.
I missed typo ticket id from 2906(correct one) to 2096 in email title.

**Comment by kangarko** [comment]
Thanks, lets continue here if you find anything else on the next version.

**Comment by Pattanawaris** [comment]
in 11.0.1 parsed hex still not displaying correctly but others in this ticket/email has been solved.

**Comment by Pattanawaris** [comment]
Okie, I updated to latest 11.0.3 BETA Hex parsed from PAPI still not working correctly. but others issue from ticket/email has been solved.

**Comment by kangarko** [comment]
Can you please remind me of steps to reproducing the hex issue?

**Comment by kangarko** [comment]
Nevermind, I wlll add back support for old hex formatting.

**Comment by Pattanawaris** [comment]
Sorry for late reply, Thank you <3

**Comment by Pattanawaris** [comment]
Hi, seems like issue still remain in latest version as my assumption that the plugin use ancient legacy method like '&a&7&e&k...' to display hex.

**Comment by kangarko** [comment]
Should be addressed today, if not please comment below with steps to reproduce and an example of where it is broken.
