### ISSUE TITLE
Korean characters in regex splits into two

### ISSUE THREAD

**Issue by kdhkr** [kangarko/ChatControl#291]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

![image](https://user-images.githubusercontent.com/55907150/102571769-ae632900-412d-11eb-8704-ab67164724cd.png)
If I set a regex rule using Korean, it somehow splits them and does not function properly.

**Regex Used:** `match (시|싀|쉬|슈|씨|쒸|씌|쓔|쑤|시이|싀이|쉬이|씨이|쒸이|씌이|찌이|스|쓰|쯔|스으|쓰으|쯔으|수우|쑤우|십|싑|쉽|슙|씹|쓉|씝|쓥|씁|싶|싚|슆|슾|앂|씦|쓒|씊|쑾|ㅅ|ㅆ|ㅅㅣ|ㅅ이|ㅆ이|c|c이|Ⓒ|Ⓒ이|씨이이|시이이|쓰으으|스으으)[^가-힣]*(바|파|발|팔|빠|빨|불|벌|벨|밸|빠|ㅂ|ㅃ|ㅍ)|(병|뱡|뱅|뱡|빙|븅|븽|뷰웅|비잉|볭|뱽|뼝|뺑|쁑|삥|삉|뺭|뼈엉|쀼웅|ㅂ)[^가-힣]*(신|싄|슨|씬|씐|진|즨|ㅅ|딱|시인|시나)|(새|섀|세|셰|쌔|쎄|썌|쎼)[^가-힣]`

`[^가-힣]` should select all korean characters, but since it is somehow splitted into two, it gives me an error that the regex is incorrect.
![image](https://user-images.githubusercontent.com/55907150/102571939-2e898e80-412e-11eb-96ff-c41253753f49.png)

**Comment by kangarko** [comment]
Looks like the regex is corrects. Unfortunately I dont have enough regex experience, I wrote the plugin in Java, however the error seems related to your file encoding. Please see https://github.com/kangarko/ChatControl-Red/wiki/Use-Right-Encoding to try fixing this by using the steps in the article.

PS: To diagnose regex errors specifically, you can use regex101.com

<img width="739" alt="Screenshot 2020-12-22 at 00 19 00" src="https://user-images.githubusercontent.com/1918426/102831139-52c5c380-43eb-11eb-976a-a9a280458e3c.png">
