### ISSUE TITLE
Paper 1.21.1: Plugin is being disabled.

### ISSUE THREAD

**Issue by developedbyalex** [kangarko/ChatControl#2912]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.0.3-BETA

### Optional: Error log

https://paste.byalex.gg/view/Mavs6WN5ul

### Steps to reproduce

Just added the new ChatControl plugin from BBB into the server. Restarted.

**Comment by developedbyalex** [comment]
Update: It seemed it couldn't parse the placeholder for [HexNicks](https://www.spigotmc.org/resources/hexnicks-easy-nicknames-with-gradients.83554/) yet HexChat uses MiniMessage?

**Comment by developedbyalex** [comment]
Also shaders from this [McModels ](https://mcmodels.net/products/9679/very-cool-text-effects)link aren't being displayed in chat (they are being displayed else where)

**Comment by kangarko** [comment]
HexNick looks like a very poorly designed plugin, I recently discovered it shades Adventure library without relocation which is a biggy: https://github.com/kangarko/ChatControl-Red/wiki/JAR-hell

Plus, we pass the null sender as permitted in PlaceholderAPI: https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/src/main/java/me/clip/placeholderapi/PlaceholderHook.java#L35

Looks like they don't handle such cases. This is something they need to fix.
