### ISSUE TITLE
1.21.4 TAB: Error Placeholder

### ISSUE THREAD

**Issue by SaKePlqa** [kangarko/ChatControl#2913]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.0.3-BETA

### Optional: Error log

https://pastebin.com/M0xDbdDN
https://pastebin.com/RLfs9nhB

### ZIP of "/chc debug"

https://ufile.io/dwjknrkv

### Steps to reproduce

Hello, the problem occurs when I add tab to the variable in the plugin file, it's more about the error with: tabsuffix: "%chatcontrol_player_newcomer% %luckperms-suffix%"
added variable:
Groups.yml
_DEFAULT_:
  tabprefix: "%luckperms-prefix%"
  tagprefix: "%luckperms-prefix%"
  customtabname: "%player%"
tabsuffix: "%chatcontrol_player_newcomer% %luckperms-suffix%"
  tagsuffix: "%luckperms-suffix%"
Config.yml:
placeholder-output-replacements:
  '%chatcontrol_player_newcomer%':
    'true': '&a🍁'
    'false': ''

**Comment by SaKePlqa** [comment]
https://pastebin.com/RLfs9nhB

**Comment by kangarko** [comment]
Thanks, will be fixed. Keep in mind at that point in time when TAB calls our placeholders  the database is not yet loaded. We will return empty at the first call and then return the right variable as soon as the db is loaded. Let me know if it will work properly.

**Comment by SaKePlqa** [comment]
Hello again, now the problem appears: sometimes the error is shown in the console, sometimes not
![image](https://github.com/user-attachments/assets/bd93f949-32a1-4a6c-957e-c0803dd8567b)

**Comment by kangarko** [comment]
This will be addressed in todays release, thanks.
