### ISSUE TITLE
1.21.1: Priorities change?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2918]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

Hello, when I'm using the 11.0.3 CHC version, I cannot use [item] from InteractiveChat, but it worked on CHatcontrol RED latest version.

Did priorities change somehow or is it different bug? I have HIGHEST in chatcontrol and NORMAL in interactivechat, and it worked before

Like I cannot do [item] etc.

**Comment by kangarko** [comment]
Can you try appending -MODERN to the chat priority settings.yml key? Like HIGHEST-MODERN instead of just HIGHEST ?

Thanks

**Comment by bobhenl** [comment]
No even when I have:
```yml
Chat_Listener_Priority: HIGHEST-MODERN
```
it still doesn't work, but as mentioned, on CHCRed the HIGHEST worked, not sure if priorities changed somehow & I should try to lower it, but hopefully it won¨t break the other things as the HIGHEST was already tested and the best for me -> to support interactivechat, faction chats, etc. in the past

**Comment by bobhenl** [comment]
No even when I have:
```yml
Chat_Listener_Priority: HIGHEST-MODERN
```
it still doesn't work, but as mentioned, on CHCRed the HIGHEST worked, not sure if priorities changed somehow & I should try to lower it, but hopefully it won¨t break the other things as the HIGHEST was already tested and the best for me -> to support interactivechat, faction chats, etc. in the past

@kangarko

**Comment by kangarko** [comment]
The next version should bring back compatibility with ItemsAdder. You can use NORMAL-MODERN priority again and ignore the console warning if it will work, if not, try LOWEST

**Comment by bobhenl** [comment]
Yeah but here the interactikvechat plugin isn’t working, but yeah let’s see after new version


EDIT: IT's working now, thanks!
