### ISSUE TITLE
1.21.3: Player nicknames not displaying colors

### ISSUE THREAD

**Issue by BAD7777** [kangarko/ChatControl#2919]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

ChatControl version 11.0.3-BETA

### Optional: Error log

https://mclo.gs/kBNAc9E

### Steps to reproduce

In the previous version of ChatControl (10.28.4), player nicknames displayed colors correctly using the following format:

```yaml
player-name:
  Message: '{display_name}'
```

However, after updating to version 11.0.3-BETA, colored player nicknames no longer work with any placeholder format, including `{display_name}`, `{player_name}`, and `{player_nick}`.

**Behavior:**
- In version 10.28.4, colored nicknames were displayed correctly.
- In version 11.0.3-BETA, nicknames are no longer displayed with any color formatting.
- The only placeholder that works for displaying colored nicknames is `{hexnicks_nick_mm}`, but it causes the following error when reloading the plugin:

```
[CHAT] [i] Reloading plugin's data, please wait..
[CHAT] [✕] Oops, reloading failed! See the console for more information. Error: Cannot invoke "org.bukkit.OfflinePlayer.getUniqueId()" because "player" is null
```

**Full console error log:**
[[Console Error Log](https://mclo.gs/kBNAc9E)]

**Error Details:**
```
[00:09:34 INFO]: Tuzik issued server command: /chc reload
[00:09:34 INFO]: [ChatControl] -------------------------------------------------------------------------------------------
[00:09:34 INFO]: [ChatControl] Error initializing format chat
[00:09:34 INFO]: [ChatControl] -------------------------------------------------------------------------------------------
[00:09:34 INFO]: java.lang.NullPointerException: Cannot invoke "org.bukkit.OfflinePlayer.getUniqueId()" because "player" is null
...
```

**Tested Placeholders:**
- `{hexnicks_nick}` - Returns the player's nickname with legacy formatting.
- `{hexnicks_nick_raw}` - Returns the player's nickname with no formatting at all.
- `{hexnicks_nick_hex}` - Returns the player's nickname with hex formatting (used by DeluxeChat and derivatives).
- `{hexnicks_nick_mm}` - Returns the player's nickname with MiniMessage formatting (works, but causes the error mentioned above).

**Expected Behavior:**
Player nicknames should display with colors as expected using placeholders like `{display_name}` and `{player_name}`, without causing errors when reloading the plugin.

**Steps to Reproduce:**
1. Use the ChatControl plugin version 11.0.3-BETA and HexNicks.
2. Set up a player name placeholder (e.g., `{display_name}`) in the configuration.
3. Reload the plugin using `/chc reload`.
4. Observe that player nicknames are no longer displayed with color, and the plugin fails to reload with a NullPointerException error.

**Additional Information:**
- This issue does not occur in version 10.28.4, where player names display colors correctly.
- Using `{hexnicks_nick_mm}` can temporarily solve the problem but causes a runtime error in the console.

![image](https://github.com/user-attachments/assets/d6bd1942-f4eb-4f9c-a685-5502d52a425d)

**Comment by bobhenl** [comment]
looks like the old # hex format isn't supported and that makes a lot of problems, there are actually prob 3 issues regarding it

**Comment by kangarko** [comment]
Unfortunately I decompiled HexNick and found it was poorly written in that they shade the Adventure library without relocation leading to bootup issues and potentially other issues too. I recommend you switch over to our own tag system. 

https://github.com/kangarko/ChatControl-Red/wiki/JAR-hell

Having said that, in the next update I will theoretically add a fix where the old syntax will start to work again.

**Comment by Majekdor** [comment]
The version of HexNicks you decompiled is nearing on 3 years old. New versions of HexNicks aren't posted to Spigot (which is literally stated right at the top of the Spigot page) since they only support Paper. You can find the latest version of HexNicks [here](https://modrinth.com/plugin/hexnicks). The latest version hasn't been updated in over a year (I don't have as much time anymore for MC plugins as I'd like) but is much more stable (fairly consistent usage across [a few hundred servers](https://bstats.org/plugin/bukkit/HexNicks/8764)).

Now had you bothered to look into the actual error even a little bit (I mean really, the version of HexNicks he's using shows up in the logs), you'll see that my PlaceholderAPI hook is being passed a null `OfflinePlayer`. This is likely due to something with running on a proxy server, but I don't know as I don't work with proxy servers or claim that HexNicks supports them. Nor can I investigate what has changed between versions of ChatControlRed since it's not open source.

**Comment by BAD7777** [comment]
> Unfortunately I decompiled HexNick and found it was poorly written in that they shade the Adventure library without relocation leading to bootup issues and potentially other issues too. I recommend you switch over to our own tag system.
> 
> https://github.com/kangarko/ChatControl-Red/wiki/JAR-hell
> 
> Having said that, in the next update I will theoretically add a fix where the old syntax will start to work again.

![image](https://github.com/user-attachments/assets/54e98f1d-973c-4ba7-8c78-9b9bd1bd4f2e)

**Comment by BAD7777** [comment]
After updating to ChatControl version 11.0.5-BETA and using `%hexnicks_nick_hex%`, everything works fine, and the colored nickname feature is functional. However, upon starting the plugin, I encounter the following error:  

```
[12:40:43 INFO]: [ChatControl] Enabling ChatControl v11.0.5-BETA
[12:40:43 INFO]: [ChatControl]  ____ _  _ ____ ___ ____ ____ _  _ ___ ____ ____ _     
[12:40:43 INFO]: [ChatControl]  |    |__| |__|  |  |    |  | |\ |  |  |__/ |  | |    
[12:40:43 INFO]: [ChatControl]  |___ |  | |  |  |  |___ |__| | \|  |  |  \ |__| |___
[12:40:46 INFO]: [ChatControl] -------------------------------------------------------------------------------------------
[12:40:46 INFO]: [ChatControl]  Faulty extension class dev.majek.hexnicks.hook.PapiHook
[12:40:46 INFO]: [ChatControl]  failed to replace 'nick_hex'
[12:40:46 INFO]: [ChatControl]  
[12:40:46 INFO]: [ChatControl]  Alert their developers to account for null
[12:40:46 INFO]: [ChatControl]  offline player as specified in PlaceholderAPI
[12:40:46 INFO]: [ChatControl]  standards. Printing the error below and
[12:40:46 INFO]: [ChatControl]  returning empty value.
[12:40:46 INFO]: [ChatControl] -------------------------------------------------------------------------------------------
```

More details here: [https://mclo.gs/xyLzKr7](https://mclo.gs/xyLzKr7)

**Comment by kangarko** [comment]
> The version of HexNicks you decompiled is nearing on 3 years old. New versions of HexNicks aren't posted to Spigot (which is literally stated right at the top of the Spigot page) since they only support Paper. You can find the latest version of HexNicks [here](https://modrinth.com/plugin/hexnicks). The latest version hasn't been updated in over a year (I don't have as much time anymore for MC plugins as I'd like) but is much more stable (fairly consistent usage across [a few hundred servers](https://bstats.org/plugin/bukkit/HexNicks/8764)).
> 
> Now had you bothered to look into the actual error even a little bit (I mean really, the version of HexNicks he's using shows up in the logs), you'll see that my PlaceholderAPI hook is being passed a null `OfflinePlayer`. This is likely due to something with running on a proxy server, but I don't know as I don't work with proxy servers or claim that HexNicks supports them. Nor can I investigate what has changed between versions of ChatControlRed since it's not open source.

Thanks for providing context. I did indeed used the outdated version on Spigot, sorry for not seeing there was a newer version available.

@BAD7777 regarding the new bug @Majekdor can you please account for null OfflinePlayer in your PlaceholderAPI extension? The way the plugin is programmed accounts for null scenarios which we fire for console, discord or dynmap senders. This is something in the extension that needs to be fixed.

**Comment by kangarko** [comment]
Looks like there was a comment that got deleted? Let me know if you need my input on anything.

**Comment by BAD7777** [comment]
> Looks like there was a comment that got deleted? Let me know if you need my input on anything.

Hello, I was the one who wrote the previous message. The plugin no longer shows an error message when starting or when a player connects. However, when I use `/chc reload`, I get the following error:
![image](https://github.com/user-attachments/assets/fa6a6bfe-8656-42bf-91b3-11bdbcee881b)

The issue is essentially resolved, but when reloading the plugin with the command, I still get this error. So, does this mean you’ve fixed everything? Is that correct?

**Comment by kangarko** [comment]
For a complete fix, they need to fix it. On /chc reload we check every format and every placeholder for errors, this error is not coming from our plugin.

**Comment by Majekdor** [comment]
@BAD7777 I'll have a fix out for HexNicks this weekend.
