### ISSUE TITLE
InteractiveChat Support

### ISSUE THREAD

**Issue by Hellcode48** [kangarko/ChatControl#292]
I use InteractiveChat (https://www.spigotmc.org/resources/interactivechat-supports-bungeecord-custom-keywords-items-inventories-in-chat-rgb-fonts.75870/) for my [item] variables. It works fine in chat but in discord it doesn't work (I have the discord addon for the plugin as well)

**Comment by kangarko** [comment]
Hey, that plugin conflicts with our own [item] variable so thus is unfortunately uncompatible.
