### ISSUE TITLE
1.21.3: Colors from LuckPerms not displayed in {player_suffix}

### ISSUE THREAD

**Issue by BAD7777** [kangarko/ChatControl#2920]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

ChatControl version 11.0.3-BETA

### Steps to reproduce

**Issue Description:**  
In version 10.28.4, colors defined in LuckPerms for `{player_suffix}` are correctly displayed in chat messages. However, after updating to version 11.0.3-BETA, colors are no longer passed through, and `{player_suffix}` is displayed as plain text without formatting.

In the changelog for version 11.0.1, the following improvement is mentioned:  
> **Improve** | Added %placeholder% to {placeholder} syntax migrator as well as one for &#123456 hex design placeholders and one for more legacy variables. Those will run always even if you already migrated your folder.  

Despite this, the issue with color transmission remains unresolved.

---

**Channel Configuration:**  
```yaml
# Show the [Read] prefix if the receiver is only reading this channel.
read-prefix:
  Message: '&7L | &r{player_suffix}'
```

---

**How it Displays:**  
![image](https://github.com/user-attachments/assets/ac6bb192-54d5-4c10-9ab1-10782115b074)

---

**Steps to Reproduce:**  
1. Install LuckPerms and configure suffixes with colors.  
2. Install ChatControl version 11.0.3-BETA.  
3. Set up the channel with the above configuration.  
4. Join the server and send a message in the chat.

---

**Expected Behavior:**  
Colors defined in LuckPerms for `{player_suffix}` should be displayed correctly in the chat.
![image](https://github.com/user-attachments/assets/53dee782-5a56-47b9-be67-b720d0c364ff)

**Actual Behavior:**  
`{player_suffix}` is displayed without colors, as plain text.
![image](https://github.com/user-attachments/assets/ac6bb192-54d5-4c10-9ab1-10782115b074)
---

**Notes:**  
- This configuration worked correctly in version 10.28.4.  
- The issue may be related to placeholder migration introduced in newer versions.  
- LuckPerms version: 5.4.150.

**Comment by kangarko** [comment]
Thanks, this issue lays in the difference on how we search for a hex string. Since ChatControl 11, hex needs to be wrapped in <> and be a valid MiniMessage like this:

`<#FFFFFF>My prefix`

Since I don't want you to waste your time updating all prefixes, I will add an option that will parse and convert hex variables from them in the next version
