### ISSUE TITLE
FlamePaper 1.8.8 (2.0.4): Discord to Minecraft Vault Severe Error

### ISSUE THREAD

**Issue by Neeonn** [kangarko/ChatControl#2927]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

11.0.3-BETA

### Optional: Error log

https://pastebin.com/cuB1kdV9

### ZIP of "/chc debug"

[debug.zip](https://github.com/user-attachments/files/18222225/debug.zip)

### Steps to reproduce

Use my config, send a message to the Discord channel and check console.

**Comment by kangarko** [comment]
This is just a warning, you can ignore it. We cant read perms for discord players. I will silence it to the next version.
