### ISSUE TITLE
Proxy 、 Server_Name Confing

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#2929]
### Summary

Can't Proxy and Server_Name be a separate file like before?
In this way, when I synchronize files or modify files on multiple servers, I don't need to make adjustments to individual servers.

After separation, it will look like the old version, making it easier to synchronize settings on multiple distribution servers.

**Comment by kangarko** [comment]
Thanks, will revert that and place it to the separate file again.
