### ISSUE TITLE
Custom Permission messages

### ISSUE THREAD

**Issue by Jast3r** [kangarko/ChatControl#293]
Ive tried to find the location of the "No permission" messages. I noticed that they were different than the default commands. Thats why i wanted to customise it so you dont get any permission message when you do a command. Not sure if this is possible. I could not find anything resembeling this feature in the files nor online.

Version of ChatControl 7.8.6

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/ChatControl-pro/wiki/Localization
