### ISSUE TITLE
Paper 1.21.1: luckperms prefix placeholder not working on VelocityControl v2.0.4-BETA

### ISSUE THREAD

**Issue by RikMichiel** [kangarko/ChatControl#2935]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

11.0.4-BETA

### ZIP of "/chc debug"

![image](https://github.com/user-attachments/assets/acf12aee-3457-48d7-bf95-fd5aa01dcdba)
When adding the following to VelocityControl, the placeholder for luckperms_prefix does not work. I have PlaceholderAPI installed on all backend servers and I have PAPIProxyBridge installed on proxy, where VelocityControl is also located.

Code:
group donator
require sender perm chatcontrol.join
message: 
- {luckperms_prefix} {player} &7joined the server!

### Steps to reproduce

- Install VelocityControl v2.0.4-BETA with ChatControl v11.0.4 on Velocity Network.
- Add the code below to join.rs in VelocityControl messages
- join server with chatcontrol.join permission

Code:
group donator
require sender perm chatcontrol.join
message: 
- {luckperms_prefix} {player} &7joined the server!

**Comment by RikMichiel** [comment]
[VelocityControl.zip](https://github.com/user-attachments/files/18247052/VelocityControl.zip)

**Comment by BearLeonLight** [comment]
{player_prefix} works on my side,
Velocitycontrol itself does not support PAPI, nor does it support PAPIProxyBridge.
You can ask kangarko if it can add PAPIProxyBridge support.

**Comment by RikMichiel** [comment]
> {player_prefix} works on my side, Velocitycontrol itself does not support PAPI, nor does it support PAPIProxyBridge. You can ask kangarko if it can add PAPIProxyBridge support.

This works but the {player_prefix} placeholder does not work with HEX color codes. So the color code is displayed in chat now.
![f11c09dabda41c2614ef962e6464f65f](https://github.com/user-attachments/assets/36ebbd3f-e060-458d-b235-d1dd7a8b8c86)

**Comment by kangarko** [comment]
Should be corrected in today's version. Also make sure you have the old syntax enabled in settings.yml under Performance
