### ISSUE TITLE
Delay universal condition does not seem to function with login messages.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#294]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

Migrating from ChatControl 8 to Red 10.1.9.

With ChatControl 8, I delayed login messages by 5 ticks to give enough time for player displayname colors to load their group prefix so their name didn't display all gray.

ChatControl 8
```
Join_Message:
  Enabled: true
  Ignore_Vanished: false
  Delay_Ticks: 5
  Message: Login
  ```
  
However with ChatControl Red, delay does not seem to work. The login message breaks and does not display anything.

join.rs
```
group default
message: 
- &8[&2+&8] {player_displayname} &fhas &2joined &fthe server.
delay 1 seconds
```

I've tried moving the delay above and below the ``message:`` section but it doesn't do anything. Login messages do not work when a delay is set.

This is what it looks like when it isn't delayed. There was only color at the very top because everyone logged in at the same time causing enough of a backup to delay long enough to get their color. When players normally join (such as myself at the top and someone who relogged at the bottom), their color could not be obtained in time,

![link](https://i.imgur.com/B5J2jZA.png)

---

Similarly, is it possible to specify a delay time in ticks instead of seconds?

**Comment by kangarko** [comment]
Thanks, will readd that option shortly

**Comment by kangarko** [comment]
Added

**Comment by mibby** [comment]
Confirmed fixed and working as intended, thanks. The default 1 tick defer seems to fix the problem; players are properly showing their displayname color again on login.
