### ISSUE TITLE
Some tips are still being shown despite show_tips setting turned off.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#295]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

ChatControl Red 10.1.9

Noticed some tips still being shown despite tips being turned off. Specifically found this by typing ``/chc announce``.

![link](https://i.imgur.com/HpclZi4.png)

```
# -------------------------------------------------------------------------------------------------
# Show important informational messages such as what channels players is joining into, etc. ?
#
# DO NOT disable this unless you have been using ChatControl Red for a few weeks otherwise you
# will miss out and then waste time reading our Wiki and opening tickets where things could easily
# be explained simply by reading the console.
#
# If you want to disable "*--------- Rule match" messages, set Rules.Verbose to false.
#
# False also remove links to Wiki and Issue Tracker from the console when the plugin starts.
# -------------------------------------------------------------------------------------------------
Show_Tips: false
```

**Comment by mibby** [comment]
> Show important informational messages such as what channels players is joining into

I assume Tips is suppose to disable this too? 
![link](https://i.imgur.com/Kxq3iHs.png)

I did not use channels in ChatControl 8 and now that I'm forced into it for formatting, I would very much like to be able to disable the ``has joined '<channel>' channel.`` message for everyone.

**Comment by Sikatsu** [comment]
Show_Tips is related to the tip messages in the console, not the tips underneath commands.

You can disable ''Player Okarim has joined standard channel'' by setting notifcation in the language file to none.

**Comment by mibby** [comment]
Hm, I see. Wording is a little confusing, but thanks. I'll just remove the tip messages from the localization and strip the channel notification message. I assume it doesn't actually have to be set to ``none`` and can just be empty? 

i.e.

```
  Join:
    Notification: ''
```

**Comment by Sikatsu** [comment]
Both should work!

**Comment by kangarko** [comment]
Yes, the tip config is only console-related messages. To remove them from game, simply edit your localization file.
