### ISSUE TITLE
Packet question

### ISSUE THREAD

**Issue by SirMittens** [kangarko/ChatControl#295]
Hey,
 quick question if you don't mind. I have been trying to disable a mythicdrops chat message
This one in particular http://prntscr.com/jebqub
This is an example of my Packet file http://prntscr.com/jebqoi

I have tried quite a few things adding/removing color codes, checking spaces and messing with the message itself. nothing seems to work the message seems to pop up any ideas?

**Comment by kangarko** [comment]
Hello,

I'd like not to disappoint you, but ChatControl free has rules engine that don't work properly on messages with colors, see https://github.com/kangarko/ChatControl/wiki#known-caveats By the way, your rule includes the &a color which is unnecessary anyways. 

The engine in the Pro version is capable of matching colored messages.
