### ISSUE TITLE
TAB Completeion block

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#296]
hi
can you add an option that block blacklisted tabs ?
like essentials that are essentials and need when essentials it's in black list or didn't add it to whitelist player can use the command,
this is able to add to prevent them to use it (like block /essentials command)

**Comment by kangarko** [comment]
Hey,

This is already in the plugin, please see and read the section of settings.yml called Tab_Complete

**Comment by FakEEE14** [comment]
i want to block the commands from using not from auto completeing
like if i add /placeholderapi in blacklist section just auto complete will be blocked and if you right it player can see the detail of the plugin

**Comment by ElBananaa** [comment]
> i want to block the commands from using not from auto completeing
> like if i add /placeholderapi in blacklist section just auto complete will be blocked and if you right it player can see the detail of the plugin

Hey!
Happy New Year!
This isn't a tab-completion block, but a plugin-command block. You can already do this using the rules. However, keep in mind that this is a chat plugin, not a plugin-command blocker plugin.

Anyways, Kangarko will probably tell you if he wants to add this feature or not.

**Comment by kangarko** [comment]
Thanks, we're however not planning to expand our features this direction right now.
