### ISSUE TITLE
A few mention notification bugs

### ISSUE THREAD

**Issue by ShawnPR1** [kangarko/ChatControl#297]
1) A player gets a sound when they send a message containing their own name. Yes, I know, who would even do such a thing? But it still happens and doesn't make a lot of sense.
2) Sending a player's name in chat while the ranged chat is on will still play a sound to them even though they aren't in the same world to receive the message (or in the same range for that matter).

The second point is the most important. Playing the sound to a player when their name is typed in a global message would make sense, but they can't even see the message in the above scenario and still hear the sound.

**Comment by kangarko** [comment]
Hello,

ChatControl free is no longer receiving minor updates, but I consider 2. as a bug and will return to it to fix it shortly. Thanks for reporting.
