### ISSUE TITLE
Player Name Colours Placeholder

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#298]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

Ok You closed my last support request so i need to start a new one.

We've gone over the nickname and chat color options but my problem still isn't solved.

My problem is that i want to change the actual names of players color, i have downloaded a plugin to do this but the Dev of the other plugin says i have to use one of his placeholders and place it somewhere in to Chat Control Reds settings to work.

The placeholder is:   %omeganames_namecolour%

Where do i place this to change my players actual names, to be clear, not nicknames or chat color. Actual players names.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: false
> BungeeCord: false
> 
> Ok You closed my last support request so i need to start a new one.
> 
> We've gone over the nickname and chat color options but my problem still isn't solved.
> 
> My problem is that i want to change the actual names of players color, i have downloaded a plugin to do this but the Dev of the other plugin says i have to use one of his placeholders and place it somewhere in to Chat Control Reds settings to work.
> 
> The placeholder is: %omeganames_namecolour%
> 
> Where do i place this to change my players actual names, to be clear, not nicknames or chat color. Actual players names.

Hey! I'm not sure to really understand your question. But afaik, it should be in the formats (formats/chat.yml for default chat as example), and replace `{player_name}` with `%omeganames_namecolour%`. I'm not sure if the pluggin actually support placeholders with percents, so if it doesn't work, consider giving a try to `{placeholderapi_omeganames_namecolour}`.

**Comment by 00Hrtz** [comment]
I've tried everything possible, nothing works, please can you add Placeholder API support.

**Comment by ElBananaa** [comment]
> I've tried everything possible, nothing works, please can you add Placeholder API support.

Hey! So I just tried, you need to use `{omeganames_namecolour}`, and place it before the `{player_nick}` placeholder.

Here's an example with a part of my chat format:
```
  player-name-admin:
    Message: '{omeganames_namecolour}{player_nick} '
    Sender_Permission: group.admin
    Hover:
    - '&cClick to send a message.'
    Suggest_Command: '/tell {player_name} '
```
It works perfectly fine like that.

**Comment by 00Hrtz** [comment]
> 
> 
> > I've tried everything possible, nothing works, please can you add Placeholder API support.
> 
> Hey! So I just tried, you need to use `{omeganames_namecolour}`, and place it before the `{player_nick}` placeholder.
> 
> Here's an example with a part of my chat format:
> 
> ```
>   player-name-admin:
>     Message: '{omeganames_namecolour}{player_nick} '
>     Sender_Permission: group.admin
>     Hover:
>     - '&cClick to send a message.'
>     Suggest_Command: '/tell {player_name} '
> ```
> 
> It works perfectly fine like that.

That's to change the nick, if i use the same as you but change player_nick to player_name, it does not change the players name. I'm trying to change the players name, not the players nickname.

in fact i dislike the whole idea of nicknames, im not using nicknames in my server.

**Comment by ElBananaa** [comment]
> > > I've tried everything possible, nothing works, please can you add Placeholder API support.
> > 
> > 
> > Hey! So I just tried, you need to use `{omeganames_namecolour}`, and place it before the `{player_nick}` placeholder.
> > Here's an example with a part of my chat format:
> > ```
> >   player-name-admin:
> >     Message: '{omeganames_namecolour}{player_nick} '
> >     Sender_Permission: group.admin
> >     Hover:
> >     - '&cClick to send a message.'
> >     Suggest_Command: '/tell {player_name} '
> > ```
> > 
> > 
> > It works perfectly fine like that.
> 
> That's to change the nick, if i use the same as you but change player_nick to player_name, it does not change the players name. I'm trying to change the players name, not the players nickname.
> 
> in fact i dislike the whole idea of nicknames, im not using nicknames in my server.

The plugin doesn't replace the player name, it only changes the colour.

**Comment by 00Hrtz** [comment]
> 
> 
> > > > I've tried everything possible, nothing works, please can you add Placeholder API support.
> > > 
> > > 
> > > Hey! So I just tried, you need to use `{omeganames_namecolour}`, and place it before the `{player_nick}` placeholder.
> > > Here's an example with a part of my chat format:
> > > ```
> > >   player-name-admin:
> > >     Message: '{omeganames_namecolour}{player_nick} '
> > >     Sender_Permission: group.admin
> > >     Hover:
> > >     - '&cClick to send a message.'
> > >     Suggest_Command: '/tell {player_name} '
> > > ```
> > > 
> > > 
> > > It works perfectly fine like that.
> > 
> > 
> > That's to change the nick, if i use the same as you but change player_nick to player_name, it does not change the players name. I'm trying to change the players name, not the players nickname.
> > in fact i dislike the whole idea of nicknames, im not using nicknames in my server.
> 
> The plugin doesn't replace the player name, it only changes the colour.

You misunderstand, I'm not trying to replace the player name, i have a plugin called Omeganames, it changes a Players real MC name's color. it has a placeholder which you see i'm trying to use. So I'm trying to change the color of a players name, not nickname.

**Comment by ElBananaa** [comment]
> > > > > I've tried everything possible, nothing works, please can you add Placeholder API support.
> > > > 
> > > > 
> > > > Hey! So I just tried, you need to use `{omeganames_namecolour}`, and place it before the `{player_nick}` placeholder.
> > > > Here's an example with a part of my chat format:
> > > > ```
> > > >   player-name-admin:
> > > >     Message: '{omeganames_namecolour}{player_nick} '
> > > >     Sender_Permission: group.admin
> > > >     Hover:
> > > >     - '&cClick to send a message.'
> > > >     Suggest_Command: '/tell {player_name} '
> > > > ```
> > > > 
> > > > 
> > > > It works perfectly fine like that.
> > > 
> > > 
> > > That's to change the nick, if i use the same as you but change player_nick to player_name, it does not change the players name. I'm trying to change the players name, not the players nickname.
> > > in fact i dislike the whole idea of nicknames, im not using nicknames in my server.
> > 
> > 
> > The plugin doesn't replace the player name, it only changes the colour.
> 
> You misunderstand, I'm not trying to replace the player name, i have a plugin called Omeganames, it changes a Players real MC name's color. it has a placeholder which you see i'm trying to use. So I'm trying to change the color of a players name, not nickname.

That's litterally what you said: `I'm trying to change the players name, not the players nickname.`
Anyways, just replace the `{player_nick}` placeholder with `{player}` and place `{omeganames_namecolour}` before, it'll work.

**Comment by SirCraftypants** [comment]
Yeah i was getting frustrated because i keep saying i'm trying to change the players name color from the start.

  player-name:
    Message: '{omeganames_namecolour}{player_name} '
    #Message: "{player_name}"
    #Gradient: RED - YELLOW

**Doesn't work**

  player-name:
    Message: '{omeganames_namecolour}{player} '
    #Message: "{player_name}"
    #Gradient: RED - YELLOW

**Isn't working**

**Comment by 00Hrtz** [comment]
> 
> 
> > > > > > I've tried everything possible, nothing works, please can you add Placeholder API support.
> > > > > 
> > > > > 
> > > > > Hey! So I just tried, you need to use `{omeganames_namecolour}`, and place it before the `{player_nick}` placeholder.
> > > > > Here's an example with a part of my chat format:
> > > > > ```
> > > > >   player-name-admin:
> > > > >     Message: '{omeganames_namecolour}{player_nick} '
> > > > >     Sender_Permission: group.admin
> > > > >     Hover:
> > > > >     - '&cClick to send a message.'
> > > > >     Suggest_Command: '/tell {player_name} '
> > > > > ```
> > > > > 
> > > > > 
> > > > > It works perfectly fine like that.
> > > > 
> > > > 
> > > > That's to change the nick, if i use the same as you but change player_nick to player_name, it does not change the players name. I'm trying to change the players name, not the players nickname.
> > > > in fact i dislike the whole idea of nicknames, im not using nicknames in my server.
> > > 
> > > 
> > > The plugin doesn't replace the player name, it only changes the colour.
> > 
> > 
> > You misunderstand, I'm not trying to replace the player name, i have a plugin called Omeganames, it changes a Players real MC name's color. it has a placeholder which you see i'm trying to use. So I'm trying to change the color of a players name, not nickname.
> 
> That's litterally what you said: `I'm trying to change the players name, not the players nickname.`
> Anyways, just replace the `{player_nick}` placeholder with `{player}` and place `{omeganames_namecolour}` before, it'll work.

Yeah i was getting frustrated because i keep saying i'm trying to change the players name color from the start.

player-name:
Message: '{omeganames_namecolour}{player_name} '
#Message: "{player_name}"
#Gradient: RED - YELLOW

Doesn't work

player-name:
Message: '{omeganames_namecolour}{player} '
#Message: "{player_name}"
#Gradient: RED - YELLOW

Isn't working

**Comment by ElBananaa** [comment]
That's weird, it should work, I mean, I tried both on my server, and both methods worked. Could you send me a screenshot of how it should be vs how it actually looks?

**Comment by 00Hrtz** [comment]
default player name color on my server is light_grey

I did what you instructed, reloaded with chc reload, then i set my omega color to green, it confirmed in chat that the color was successfully chosen, i then typed in chat and my name was still light_grey.

I'm admin, opped.

I have essentialsx installed but never used it for chat.

I can't show you what it supposed to look like as it won't do what it should. 
![2020-12-19 (1)](https://user-images.githubusercontent.com/66942713/102698836-40575880-4238-11eb-8fdb-f0cea210659d.png)

**Comment by ElBananaa** [comment]
Alright, could you upload your format file too please?

**Comment by 00Hrtz** [comment]
> 
> 
> Alright, could you upload your format file too please?

https://hastebin.com/idirajereg.yaml

**Comment by ElBananaa** [comment]
Thanks. Alright, try to remove the `Gradient: red - yellow` line under the `player-name:` part and tell me if it changes anything. Also, it looks like you are not editting the right format file. Since I see [lobby] before you name, I guess you have a bungeecord setup, it means you have to edit the bungee format file (It should be named something like `bungee-chat.yml` or `global-chat.yml`.

This is how the default bungeechat format file looks:
```
# -----------------------------------------------------------------------------------------
# The default chat format used in the global channel.
# -----------------------------------------------------------------------------------------

# The parts of this format.
Parts: 
  
  # See the chat.yml format file for a tutorial on how this works.
  everything: 
    Message: "&8[&3{channel}&8] &f{player_name}&7: &f{message}"
```
And this is how it should look if you want the custom color to be used:
```
# -----------------------------------------------------------------------------------------
# The default chat format used in the global channel.
# -----------------------------------------------------------------------------------------

# The parts of this format.
Parts: 
  
  # See the chat.yml format file for a tutorial on how this works.
  everything: 
    Message: "&8[&3{channel}&8] {omeganames_namecolour}{player_name}&7: &f{message}"
```

**Comment by 00Hrtz** [comment]
so im supposed to be putting the namespace in to the settings.yml?

I've been putting it in the chat.yml.

no i don't have bungee, i use multiverse and all my worlds have separate per world chats.

**Comment by ElBananaa** [comment]
> so im supposed to be putting the namespace in to the settings.yml?
> 
> I've been putting it in the chat.yml.
> 
> no i don't have bungee, i use multiverse and all my worlds have separate per world chats.

No, you shouldn't touch the settings file. There's something weird in your format file: as we can see on your screenshot, the world (I guess) named lobby is shown before you name, but there's nothing related to the world in the config file... Let's do something easier: place your actual plugin folder in a zip and upload it here, it'll be easier.

**Comment by 00Hrtz** [comment]
in multiverse core, each world can have an alias and Lobby is my World named Lobby with my Lobby in it.

**Comment by 00Hrtz** [comment]
that's impossible, i have over 60 plugins so the file size will be huge and i'm not allowed to distribute my premium plugins.

**Comment by ElBananaa** [comment]
> that's impossible, i have over 60 plugins so the file size will be huge and i'm not allowed to distribute my premium plugins.

I misexplained myself, I meant: Zip chatcontrol folder xD

**Comment by 00Hrtz** [comment]
> 
> 
> > that's impossible, i have over 60 plugins so the file size will be huge and i'm not allowed to distribute my premium plugins.
> 
> I misexplained myself, I meant: Zip chatcontrol folder x

so we're on same page, im not bungeecord, my setup is multiverse with per world chat and each world has an alias, that is wat the lobby prefix is.
[ChatControlRed.zip](https://github.com/kangarko/ChatControl-Red/files/5720141/ChatControlRed.zip)

**Comment by ElBananaa** [comment]
> > > that's impossible, i have over 60 plugins so the file size will be huge and i'm not allowed to distribute my premium plugins.
> > 
> > 
> > I misexplained myself, I meant: Zip chatcontrol folder x
> 
> so we're on same page, im not bungeecord, my setup is multiverse with per world chat and each world has an alias, that is wat the lobby prefix is.
> [ChatControlRed.zip](https://github.com/kangarko/ChatControl-Red/files/5720141/ChatControlRed.zip)

Yep, we're on same page. I need one more thing: Could you remove the actual error.log (inside the chatcontrol plugin folder), then restart the server, and send it again (if it still gets generated).

**Comment by 00Hrtz** [comment]
> 
> 
> > > > that's impossible, i have over 60 plugins so the file size will be huge and i'm not allowed to distribute my premium plugins.
> > > 
> > > 
> > > I misexplained myself, I meant: Zip chatcontrol folder x
> > 
> > 
> > so we're on same page, im not bungeecord, my setup is multiverse with per world chat and each world has an alias, that is wat the lobby prefix is.
> > [ChatControlRed.zip](https://github.com/kangarko/ChatControl-Red/files/5720141/ChatControlRed.zip)
> 
> Yep, we're on same page. I need one more thing: Could you remove the actual error.log (inside the chatcontrol plugin folder), then restart the server, and send it again (if it still gets generated).

No Error Log after restart.

**Comment by ElBananaa** [comment]
Ok, so, try to replace your actual chat.yml format file with this one: https://hastebin.com/ipijunileq.yaml
Also use `/chc color` ingame, and make sure you don't have any color defined using this feature.

**Comment by 00Hrtz** [comment]
OK here's what i've done.

I did what you said to do.

Then i reset my omega names color to yellow.

Then i joined   Standard Channel and tested, my name was light_gray    (Standard is my per world channels)
Then i joined   Global Channel and tested, my name was white
Then i joined   Range Channel and tested, my name was white.

**Comment by 00Hrtz** [comment]
i think i should be putting the placeholder in to the channel formats in setting.yml?

**Comment by ElBananaa** [comment]
> i think i should be putting the namespace in to the channel formats in setting.yml

You could give it a try. Tbho I don't know what's wrong actually. For sure this is something related to one of your configs (Maybe caused by another plugin), but I don't know which one.

**Comment by 00Hrtz** [comment]
> 
> 
> > i think i should be putting the namespace in to the channel formats in setting.yml
> 
> You could give it a try. Tbho I don't know what's wrong actually. For sure this is something related to one of your configs (Maybe caused by another plugin), but I don't know which one.

didn't work in settings.yml so set back to default. i then added the placeholder to global chat and the name coloring is now working in global channel but not in standard chat channel.

**Comment by ElBananaa** [comment]
> > > i think i should be putting the namespace in to the channel formats in setting.yml
> > 
> > 
> > You could give it a try. Tbho I don't know what's wrong actually. For sure this is something related to one of your configs (Maybe caused by another plugin), but I don't know which one.
> 
> didn't work in settings.yml so set back to default. i then added the placeholder to global chat and the name coloring is now working in global channel but not in standard chat channel.

Well, that's definitely related to something else, and this isn't directly related to chatcontrol-red I guess. As I said, it works perfectly fine for me. Make sure there's no colors defined after the prefix for your groups.

**Comment by 00Hrtz** [comment]
> 
> 
> > > > i think i should be putting the namespace in to the channel formats in setting.yml
> > > 
> > > 
> > > You could give it a try. Tbho I don't know what's wrong actually. For sure this is something related to one of your configs (Maybe caused by another plugin), but I don't know which one.
> > 
> > 
> > didn't work in settings.yml so set back to default. i then added the placeholder to global chat and the name coloring is now working in global channel but not in standard chat channel.
> 
> Well, that's definitely related to something else, and this isn't directly related to chatcontrol-red I guess. As I said, it works perfectly fine for me. Make sure there's no colors defined after the prefix for your groups.


**I use multiverse core to give my worlds their own chat channels, they come under standard channel in ChatControlRed, here is my Multiverse Config.**    https://paste.helpch.at/yuhoxaviyi.shell


That's all i have that affects Chat as Essentialsx player name setting is disabled and i don't have any chat plugin accept for cc red

**Comment by 00Hrtz** [comment]
> 
> 
> > > > i think i should be putting the namespace in to the channel formats in setting.yml
> > > 
> > > 
> > > You could give it a try. Tbho I don't know what's wrong actually. For sure this is something related to one of your configs (Maybe caused by another plugin), but I don't know which one.
> > 
> > 
> > didn't work in settings.yml so set back to default. i then added the placeholder to global chat and the name coloring is now working in global channel but not in standard chat channel.
> 
> Well, that's definitely related to something else, and this isn't directly related to chatcontrol-red I guess. As I said, it works perfectly fine for me. Make sure there's no colors defined after the prefix for your groups.

OK, i uninstalled and then reinstalled ChatControl Red and now all my world channels are gone and only ChatControls channels remain.  On the plus side now all the channels show player name color change.

Now my problem is all my per world channels are gone, all the worlds prefixes are gone with them and now my rank prefix are not showing. I use Ultra Permissions so the placeholder for it is   {uperms_rank}

**Comment by 00Hrtz** [comment]
reluctantly given up and ditched my premium ultra permissions.

**Comment by 00Hrtz** [comment]
BOOOOOOOOM! 

After changing from Ultra Permissions to Luckperms I've figured out how to set chat channels in settings.yml

Example:
      Format: '&f[{world}&f] &7{pl_prefix+}&f{omeganames_namecolour}{player_name}&b:{pl_suffix} &f{message}'

By using Omeganames Plugin I have managed to set it so that you can change a Players Name Color within ChatControlRed

By using the placeholder {world} I can set Mutliverse Core up so that each World has it's own Alias name and that Alias name will appear by using {world}.


Plugins:

ChatControlRed
Multiverse Core
Luckperms
Omeganames
