### ISSUE TITLE
Channels not auto-joining after first login / first time initialization (creating new) player ChatControl data.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#299]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

ChatControl Red 10.1.9

When players login for the first time (new ChatControl data being initialized for the first time), they do not auto-join their appropriate login auto-join channels despite having permission to do so.

```
- chatcontrol.channel.autojoin.standard.write
- chatcontrol.channel.join.standard.write
- chatcontrol.channel.join
```

First login with a fresh MySQL database and no data.db file in ChatControl folder. I tried to chat after login.

Since it didn't work, I relogged to force ChatControl to reload my now created data. 

It seems you have to relog to be able to chat / auto-join on first join / new data creation. Can this be fixed? I don't want players having to relog after joining to be able to chat / auto-join channels.

**Edit note:** I had permissions to auto-join & join two different channels on login; staff-chat & standard. Just thought I'd note it in case it's an issue with joining multiple channels on first login.

**Edit 2:** After monitoring for a while, new members joining only 1 channel _seem_ to be fine on first login. So it either decided to break for me as the very first person to login with a new database or it breaks when you join multiple channels at once.

**Edit 3:** Seem to be having some non-staff members who join for the first time since ChatControl Red was installed, they aren't able to chat until they relog again. So initial data creation with autojoin channels isn't allowing people to autojoin to chat. Forces them to relog to chat - please fix. :(

**Comment by Hellcode48** [comment]
I get the same issue, at least when it comes to the players having to join the channel (also the autojoin seems to have to happen on every login when it should only happen once)

**Comment by Sikatsu** [comment]
I have heard of similiar issues on my server, glad to see I am not the only one ^^

**Comment by SirCraftypants** [comment]
my test team and my alt can't even see or join any channels despite having the perms added to the default group in luckperms.

**Comment by kangarko** [comment]
What messages appear in the console when the player joins? There should be messages why/why not we joined the player into each installed channel or not.

**Comment by kangarko** [comment]
Update to next version. If still happens, post console messages when players join.
