### ISSUE TITLE
[SOLVED] chat controle - rules.txt/chc reload - problem

### ISSUE THREAD

**Issue by Retracker** [kangarko/ChatControl#3]
this is my rules file
http://pastebin.com/yKjWM5nu

this is my console log thing error
http://pastebin.com/16r1LULK

i cant /chc reload the plugin, i dont know why...

**Comment by kangarko** [comment]
Can you try shutting down the server and starting it again?

**Comment by Retracker** [comment]
@kangarko i tried now but now the plugin is disabled 
screenshot:
http://imagebin.ca/v/2Ad7tZksIrez

**Comment by Retracker** [comment]
nvm i found the problem it was at here:
http://imagebin.ca/v/2AdBzim8KD6C

i left a match without any word in it. thanks for your help anyways.

**Comment by kangarko** [comment]
Oh yes, I missed it when I was checking the file. 
I am closing this, if you have any more questions feel free to post them here.
