### ISSUE TITLE
AntiFlood option

### ISSUE THREAD

**Issue by david160596** [kangarko/ChatControl#30]
The plugin is perfect, but I would like if you could add a AntiFlood option to replace for example "hiiiiiiiiiiiiiiiiiiiiiiiiiiiii" to "hi"

Have a good day :D

**Comment by kangarko** [comment]
Such functionality can be achieved using rules.

Example:

match (.)(?=\1\4+)
then replace

**Comment by david160596** [comment]
I put in the "rules" file:
match (.)(?=\1\4+)
id 5
then replace

but my users can still make flood, I hope you can help me.
