### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by Golvore** [kangarko/ChatControl#300]
I write it here because I did not find another support tool.

How can I create Towny channels? Do I need to install TownyChat or not?

I can translate the color menu "/ chatcontrol color"?

**Comment by kangarko** [comment]
When having ChatControl pro, use https://github.com/kangarko/ChatControl-pro/issues to post issues.

Please see https://github.com/kangarko/ChatControl-Pro/wiki/Channels.

You cannot translate that menu at this time, apologies for that.
