### ISSUE TITLE
Unable to make use of DiscordSRV's @ mentions with Red's integration.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#301]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

ChatControl Red 10.1.9
DiscordSRV v1.21.1-SNAPSHOT

ChatControl Red's DiscordSRV integration does not seem to support @'ing players by their discord name via in-game chat. For example, you can't @mibby in public chat or a channel message like admin chat to receive a discord ping from the bridged bot.

ChatControl Pro (v8) with all discord integration turned off & DiscordSRV, you _are_ able to mention players.

DiscordSRV Config.yml
```
DisableMentionFiltering: false

DiscordChatChannelTranslateMentions: true
```

**Comment by kangarko** [comment]
I've added this, please see https://github.com/kangarko/ChatControl-Red/wiki/Discord#important-if-you-want-rules-and-filtering-for-your-discord-the--mentions-or-your-other-discord-plugin-may-not-work

**Comment by mibby** [comment]
I've already disabled ``Send_Messages_As_Bot``. Yet I'm still not able to use @ to ping groups (such as @Staff) or specific members from within in-game chat.

```
  Discord:
  
    # Discord does not let us edit messages, so we must remove the original message and resend
    # it as the bot. You will see your message disappear and reappear in a second or less. 
    # true = messages are sent as bot (username icons not visible)
    # false = we do not edit your discord messages (warning: this breaks antispam, rules and 
    #         removing messages on discord)
    Send_Messages_As_Bot: false
```

The issue is not with discord writing but in-game writing being forwarded to discord. This is not an issue with DiscordSRV handling integration on ChatControl 8.

**Comment by kangarko** [comment]
Thanks for bringing this up. We made the new system apparently break this feature since we've added support for message editing and rewriting both ways so that rendered these incompatible. This is something I can definitely look into for the future.

**Comment by mibby** [comment]
Sure, thanks for looking into it. Can you just re-open this ticket instead of creating a new one?

**Comment by kangarko** [comment]
So that looks something DiscordSRV is handling not ChatControl. For the time being we've added a switch to kill our Discord integration completely so you can use DiscordSRV's one for that feature.

**Comment by kangarko** [comment]
It's in Integration.Discord

**Comment by mibby** [comment]
Thanks. I disabled ChatControl's integration for now but it would be nice to fully support DiscordSRV's functionality to @ ping discord roles / players from within in-game.
