### ISSUE TITLE
ChatControl Formatting

### ISSUE THREAD

**Issue by itsyagirlpayton** [kangarko/ChatControl#301]
Hi there,

I've been desperately trying to figure out how to use ChatControl formatter. I've enabled it, made sure we have vault installed and set the priority to high. It still seems like something is either overriding it or the formatting does not work.
Example: http://prntscr.com/juqdy8
Current format: [%pl_prefix%player]:%pl_suffix %message

Furthermore, I've been trying to find a way to integrate LuckPerm's chat color setting into messages. Was unable to do this with essentials chat, and was wondering if it was possible with chatcontrol. Thanks.

**Comment by kangarko** [comment]
Hello and welcome to the issues channel!

In ChatControl Pro, we use another syntax, so %pl_prefix becomes {pl_prefix} and so on.

If you use {pl_prefix}, that should integrate LuckPerm's color through Vault automatically.

Any errors in the console? Also try to completely restart the server when toggling formatting.

What other plugins are installed on your server?

**Comment by kangarko** [comment]
If you still need help, comment below.
