### ISSUE TITLE
Discord integration incompatible with EmojiChat emote translating - not sending message emote to discord.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#302]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

ChatControl Red v10.1.9
DiscordSRV v1.21.1-SNAPSHOT
EmojiChat v1.8.3

ChatControl Red's discord integration seems to be incompatible with EmojiChat and not translating Emojis sent in-game upstream to the connected discord channel.

My guess is ChatControl Red is sending the raw unicode / chinese characters to its own discord hook before it's mapped to an emote by EmojiChat? This issue does not exist with ChatControl Pro (v8) with discord integration off & letting chat be forwarded entirely by DiscordSRV. It's properly displayed on discord & in-game with the the old version / discordSRV.

I have tried adjusting the chat listener to both ``Chat_Listener_Priority: HIGH`` & ``Chat_Listener_Priority: MONITOR``. Neither fix the issue.

Old reference: https://github.com/kangarko/ChatControl-Pro/issues/1498

**Edit:** Here is how it looks on ChatControl Pro (v8) with discord integration handled entirely by DiscordSRV only.

**Comment by kangarko** [comment]
Try setting Integration.Discord.Send_Messages_As_Bot in settings.yml to false. Unfortunately if that doesn't help then it's incompatible for now.

**Comment by mibby** [comment]
That setting was already turned off when tested. Besides, that should only delete/rewrite messages on discord sent to in-game, not in-game sent upstream to discord, no? In both screnshots, the Emoji was used in-game and forwarded upstream to the discord channel.

```
  Discord:
  
    # Discord does not let us edit messages, so we must remove the original message and resend
    # it as the bot. You will see your message disappear and reappear in a second or less. 
    # true = messages are sent as bot (username icons not visible)
    # false = we do not edit your discord messages (warning: this breaks antispam, rules and 
    #         removing messages on discord)
    Send_Messages_As_Bot: false
```

Discord integration in Red just doesn't register the emoji alias in ChatControl, whereas DiscordSRV handling integration with ChatControl 8 does. Perhaps it's an issue with registering chat some ticks before EmojiChat handles it? Not sure why DiscordSRV doesn't have the issue.

Disabling ChatControl Red's discord integration means messages deleted in-game wouldn't delete from the bridged chat. So if it could be fixed, I'd really appreciate it. :(

**Comment by kangarko** [comment]
Thank you! I have other priorities right now such as fixing /reply command, sorry but I can't change this right now, feel free to resuggest this in the future.

**Comment by mibby** [comment]
Sure, no problem. Can this ticket just be reopened? Emojis properly display both directions (discord -> ingame; ingame -> discord) when discord integration is disabled in ChatControl Red. If you could look to see how DiscordSRV natively parses emojis for Red's own integration, it would be much appreciated. I'm forced to keep Red's discord integration disabled for emojis to work, which makes it so I can't use the new remove message button feature of Red. :(

Could it be as simple as just waiting a tick for EmojiChat?

This is with Discord integration enabled on Red. First emoji was used in-game, second/third emoji came from discord channel.


This is with Discord integration disabled on Red, chat forwarding handled entirely by DiscordSRV.


Latest testing with ChatControl Red 10.1.12

**Comment by ElBananaa** [comment]
> Sure, no problem. Can this ticket just be reopened? Emojis properly display both directions (discord -> ingame; ingame -> discord) when discord integration is disabled in ChatControl Red. If you could look to see how DiscordSRV natively parses emojis for Red's own integration, it would be much appreciated. I'm forced to keep Red's discord integration disabled for emojis to work, which makes it so I can't use the new remove message button feature of Red. :(
> 
> Could it be as simple as just waiting a tick for EmojiChat?
> 
> This is with Discord integration enabled on Red. First emoji was used in-game, second/third emoji came from discord channel.
> ![link4](https://camo.githubusercontent.com/4052e6113f11b0373d1205c1b2798e6eeb945f731ea1238411fd146a6d812c7a/68747470733a2f2f692e696d6775722e636f6d2f615466656f6d512e706e67)
> 
> This is with Discord integration disabled on Red, chat forwarding handled entirely by DiscordSRV.
> ![link5](https://camo.githubusercontent.com/df240e156751e4c0122eef74bfea2cda9a23a7e1040534ed2e9caeffbebe14a0/68747470733a2f2f692e696d6775722e636f6d2f4b33724232714a2e706e67)
> 
> Latest testing with ChatControl Red 10.1.12

Hey! As Kangarko said above, in order to keep clean and understandable tracks of issues/suggestions, you should simply consider opening a new ticket in a few weeks.

**Comment by kangarko** [comment]
I am not certain where things break, but given the fact we entirely cancel chat event and send it in our own, unique way (due to channels), I see no easy out. You'll need to stick with DiscordSRV integration to keep emojis for the time being.

**Comment by mibby** [comment]
Would it be outside the feature scope of ChatControl to implement its own emoji handling with a resource pack that has font unicode pngs? Assuming compatibility with ChatControl's discord integration can't be fixed to work with EmojiChat.

**Comment by kangarko** [comment]
Not right now, but I can put this to the backburner.
