### ISSUE TITLE
Chatting in a channel with commands before talking publicly does not use your display_name color.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#303]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

ChatControl Red v10.1.9

If you try talking in a channel with the command ``/ch send <channel> message`` before you talk globally normally (just writing, no commands), ChatControl does not get the player's displayname colors.

1) Login
2) ``/ch send staff-chat test``
3) See name as gray.
4) Talk publicly, your name is the correct prefix color.
5) ``/ch send staff-chat test``
6) See name correct color.

Formatting for staff-chat;
```
Parts:
  everything:
    Message: '&4[Staff] &7%display_name%&f: {message}'
```

Relogging breaks it every time if you try to channel chat via command before talking publicly.

**Testing note:** I added the following aliases to commands.yml (bukkit configuration) so players can talk in staff chat with ``/ac`` more easily.

```
  ac:
  - ch send staff-chat $1-
  sc:
  - ch send staff-chat $1-
```

**Comment by kangarko** [comment]
That is unfortunately a fault of your plugin loading displaynames, such as Essentials or CMI. Please contact their authors since they need to load it on player join, and not on player chatting.

**Comment by mibby** [comment]
Are you sure this is the fault of the plugin loading displaynames? Display names are properly shown on login (ChatControl Red's join.rs) and another plugin I use (TitleManager) is able to grab the display name when players login for the title bar welcome announcement. This is all before players chat. Since the display name is properly grabbed, I assume it is loaded fine on player join. It also displays the display name colors / name fine in my tab menu before players write a message.

The issue only occurs when using ChatControl Red's channel send command to send a message. If you send a message before talking publicly, it doesn't ever use the displayname. Once you talk publicly (normal chat, no commands), the display name is used in channel send commands.

Latest testing with ChatControl Red 10.1.12

**Comment by kangarko** [comment]
How are you setting the display name to have a color?

**Comment by mibby** [comment]
Display name colors are set by the player's primary group prefix in LuckPerms. Otherwise using Essential's nick command for coloring and setting specialized display name.

**Comment by kangarko** [comment]
Will look into this together with your other ticket

**Comment by kangarko** [comment]
@mibby https://www.loom.com/share/e98a4389400a4f508b5668a2b8cac8bc

**Comment by mibby** [comment]
I'm having a hard time reproducing this issue as of Red 10.2.1 & EssentialsX dev 1102. I'm going to assume whatever may have been causing the problem was fixed or lessened with the nick support added. If I come across this again, I'll debug with logs and let you know!
