### ISSUE TITLE
Color codes all over the line

### ISSUE THREAD

**Issue by DeCarvalho83** [kangarko/ChatControl#304]
The little problem is
i have luckperms set meta prefix to &4[&cAdmin&4]
and i have luckperms set meta usercolor-code green

what happen is that chatcontrol is getting the las color code &4 before ] and setting for the entire line
chatcontrol config.yml
Message_Format: '%pl_prefix%player:%pl_suffix %message'

![image](https://user-images.githubusercontent.com/13871000/41888199-9059acae-78da-11e8-82a9-e5c9e78e4708.png)
![image](https://user-images.githubusercontent.com/13871000/41888220-beabd000-78da-11e8-941e-3460ba099539.png)
i cant use &r after ] cuz it will remove any color codes that i have given by another plugin.

**Comment by kangarko** [comment]
ChatControl uses Vault to get the player's username. Sorry,  it seems that LuckPerms don't hook into Vault that way. I recommend suggesting LuckPerm's developer to report prefixes to Vault.
