### ISSUE TITLE
Thermos/1.7.10 support

### ISSUE THREAD

**Issue by marekvac** [kangarko/ChatControl#305]
Minecraft Version: Thermos-1.7.10-R0.1 / Spigot 1.7.10
MySQL: false - not setup yet
BungeeCord: false - not setup yet

Hi,
on our server we had issues with the plugin. 

On first load on Thermos server, plugin crashes on entities that isn't on <1.8 version:
`Error parsing rule operator from line (100): require killer ENDERMITE
File: plugins/ChatControlRed/messages/death.rs` 
[error.log](https://pastebin.com/PnvAdSpx) - pastebin
That I've fixed removing all lines with 1.8+ entities from this file.

Then plugin loaded. And on first join on server, plugin fired next error with join.
`Error parsing rule: Player Message {
	'Type' = 'join'
}`
[error.log](https://pastebin.com/HPC5zMcc) - pastebin

And after I joined, it doesn't work any of chc commands. (Commands works from console, before I joined)
`Failed to execute command /chc 
ReflectionException Could not find class: net.minecraft.server.v1_7_R4.IChatBaseComponent`
[error.log](https://pastebin.com/PbQzMHtY) - pastebin
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5717735/debug.zip)

after I wrote a message it started huge spam in console. In error.log doesn't appear any error.
[console error](https://pastebin.com/tLD9Bkf2) - pastebin

I know you don't like thermos and you don't want to support it. But the same errors is happening on vanilla Spigot 1.7.10, so I think if you will fix it on Spigot, you can also fix it on Thermos. 
We really need Chc, because on 1.7.10 is not any good chat plugin that supports bungeecord. 

I also attach debug.zip from Thermos server.

**Comment by marekvac** [comment]
`Class.forName` uses a wrong class loader on Thermos by default, you need to specify it explicitly like `Class.forName("class.name", true, MyPlugin.class.getClassLoader());`

**Comment by kangarko** [comment]
Please test the next version. If still having issues, ZIP me your whole server without worlds, upload to google drive/dropbox and send over matej@mineacademy.org with the subject ChatControl Red: Issue 305: Cauldron.

**Comment by kangarko** [comment]
Where did I say I don't like Thermos? We're fine supporting it and we even support old versions down to 1.2.5

**Comment by marekvac** [comment]
> Where did I say I don't like Thermos? We're fine supporting it and we even support old versions down to 1.2.5

Ok, then in that case it's great. We had similar issues with ChatControl Pro and you didn't have support for that. It's good to know that some plugin developers also support theese forge+bukkit/spigot servers.

**Comment by kangarko** [comment]
Sure!
