### ISSUE TITLE
Problems with the &m modifier

### ISSUE THREAD

**Issue by josemoncab** [kangarko/ChatControl#306]
### Specs
**Minecraft Version**: 1.16.4
**Server Software**: Paper#332
**ChatControl Version**: 10.1.9
**Bungecord**: false
**MySQL**: false

### Description
Hi, when i start customize my chat format I found an issue.

All the problems come out when you try to use the `&m` modified in any part in hover message (I see on this case).

First. the `&r` stop working if has other modified afther him like `&6` or `&l` (Example on the final letter)
If i only use `&r` works as espected (Example in my nickname)
![image](https://user-images.githubusercontent.com/34101063/102658601-28b89b00-4178-11eb-94df-969f0cf8742b.png)
```
    Hover:
    - '&8&m----&r {player_name} &8----&r&6a'
    - '&8&m----&r {player_name} &8----&r&6&la'
```

Second, the `&m` format still even if you don't have in multiple places. In this case, I only have the `&m` in the first segment (gray) but not in the gold one, but still have the modifier
![image](https://user-images.githubusercontent.com/34101063/102659302-784b9680-4179-11eb-9658-d151f59d1a8b.png)
```
Hover:
    - '&8&m----&r {player_name} &6----'
    - '&8&m----&r {player_name} &6----'
```

### Debug Zip:
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5717947/debug.zip)

_If you need more info or tests, you can contact me with dm in discord (goku_727#7397)_

**Comment by kangarko** [comment]
Thanks, will be fixed.
