### ISSUE TITLE
PremiumVanish problem

### ISSUE THREAD

**Issue by Hellcode48** [kangarko/ChatControl#307]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

The join and leave messages don't show when a player goes in and out of vanish

**Comment by TheIntolerant** [comment]
Please make sure you follow the template described here <https://github.com/kangarko/ChatControl-Red/issues/2>
By doing this, you can speed up the process of getting issues resolved significantly.

**Template:**
```
Minecraft Version: 1.X.Z
MySQL: true/false
BungeeCord: true/false

Remove this and type your issue description here with steps to reproduce: 1-2-3.
```
If you have ANY problem, run "/chc debug" and upload your ZIP file to this window directly when creating new issues.
If having a permissions problem, post ALL permissions that the affected player is having.

**Comment by kangarko** [comment]
Thanks, yes, we ignore vanished players. I will solve quit messages still being sent for vanished players in the next version.
