### ISSUE TITLE
ignore event signs is not working

### ISSUE THREAD

**Issue by Magnum97** [kangarko/ChatControl#309]
I want to prevent people from spamming repeated characters ie. aaahhhhhhhhhhhhh! But I want to exempt signs. With the config below it is still triggering on signs.
This is from from rules.txt:

match (.)\1{4,}
ignore event signs
handle as letter_spam

**Comment by kangarko** [comment]
Replace "ignore event signs" with "ignore event sign" without the plural s.

If it still does not work, set "Debug" to "[rules]" in settings.yml and post me your ChatControl startup output from console, and the output when you break the rule on sign.

**Comment by kangarko** [comment]
Confirmed, fixed.
