### ISSUE TITLE
The death.rs file doesn't change when I translated it.

### ISSUE THREAD

**Issue by MdoubleM** [kangarko/ChatControl#310]
I have translated the death.rs to Spanish and in my server it doesn't change, it's still in English. I have restarted my server and everything. What can I do?

https://pastebin.com/jDCsireH

**Comment by WolverStones** [comment]
Maybe this can help you https://github.com/kangarko/ChatControl-Red/wiki/Rules#chinese--cyrillic--accented-language

**Comment by MdoubleM** [comment]
No, it doesn't help my problem. I still don't know why my Spanish translation doesn't replace the English translation.

https://pastebin.com/jDCsireH

**Comment by ElBananaa** [comment]
> No, it doesn't help my problem. I still don't know why my Spanish translation doesn't replace the English translation.
> 
> https://pastebin.com/jDCsireH

Hey! I think more infos would be useful (Server version (Paper? Spigot?... 1.16? 1.12?...), plugin version, protocolLib version, logs...
Also, does it shows default minecraft death messages? If so, make sure in the settings file, Under the `Messages:` part, under `Apply_On:` there's: `death`
(Here my setup as example)
```
# -------------------------------------------------------------------------------------------------
# Represents settings for player messages such as join, quit, death and timed messages
# -------------------------------------------------------------------------------------------------
Messages:
 
  # What aspects of messages should be enabled?
  # Options: join, quit, kick, death, timed
  #
  # If you have another plugin handling join/quit etc. messages, remove them from list below.
  # If you want to hide those messages, leave them in Apply_On and empty your messages/ .rs files.
  Apply_On:
  - 'join'
  - 'quit'
  - 'kick'
  - 'death'
  - 'timed'
```

I just tried on my test server with CHCRed 10.1.9, paper 332 (1.16.4), it works perfectly fine.

**Comment by MdoubleM** [comment]
Hi, I'm using the latest paper version and my server is in the 1.16.4. The plugin is in the latest version also.
I have that config like this.
# -------------------------------------------------------------------------------------------------
# Represents settings for player messages such as join, quit, death and timed messages
# -------------------------------------------------------------------------------------------------
Messages:
 
  # What aspects of messages should be enabled?
  # Options: join, quit, kick, death, timed
  #
  # If you have another plugin handling join/quit etc. messages, remove them from list below.
  # If you want to hide those messages, leave them in Apply_On and empty your messages/ .rs files.
  Apply_On:
  - 'death'
 
And the deaths that are shown in the server are the default death messages of the Chatcontrol plugin

**Comment by ElBananaa** [comment]
> Hi, I'm using the latest paper version and my server is in the 1.16.4. The plugin is in the latest version also.
> I have that config like this.
> 
> # -------------------------------------------------------------------------------------------------
> # Represents settings for player messages such as join, quit, death and timed messages
> # -------------------------------------------------------------------------------------------------
> Messages:
> 
> # What aspects of messages should be enabled?
> # Options: join, quit, kick, death, timed
> # If you have another plugin handling join/quit etc. messages, remove them from list below.
> # If you want to hide those messages, leave them in Apply_On and empty your messages/ .rs files.
> Apply_On:
> 
> * 'death'
> 
> And the deaths that are shown in the server are the default death messages of the Chatcontrol plugin

That's weird, I cannot reproduce this issue, even on a local test server. Are you sure you editted the right server/file? Could you send your plugin folder here?

**Comment by WolverStones** [comment]
You can use the /chc debug command to upload files and upload a zip for example https://ufile.io sensitive data like mysql information etc. has been removed from the plugin if you use this command.

**Comment by MdoubleM** [comment]
In which folder is the debug.zip that generates when I use the /chc debug? I can't find it

**Comment by WolverStones** [comment]
> In which folder is the debug.zip that generates when I use the /chc debug? I can't find it

If created correctly, it should be located in the _**plugins/ChatControlRed**_  folder

**Comment by MdoubleM** [comment]
Well I use the /chc debug and it appears the message: Succesfully copied 48 file(s) to debug.zip. But then it doesn't appear in the chatcontrolred folder

**Comment by MdoubleM** [comment]
Okay I have it.

https://ufile.io/cfah7m15

**Comment by ElBananaa** [comment]
> Okay I have it.
> 
> https://ufile.io/cfah7m15

Hey! With the debug file you provided, it looks like the death.rs file is the default one. It means that you didn't save the changes made to the file.

**Comment by MdoubleM** [comment]
Thank you, I finally solved it
