### ISSUE TITLE
ChatControl bypass EssentialsX's chat formatting

### ISSUE THREAD

**Issue by LemonLight** [kangarko/ChatControl#311]
Hi !

I have an issue with ChatControl. When I disable ChatControl's formatting, it looks that it still is ChatControl that format the chat... The EssentialsXChat's configuration is not take in consideration. 

Did I forget parameters ?

Here's my configs : 
* EssentialsX Chat :
```yaml
group-formats:
    default: '&b[Member] {DISPLAYNAME} &3&l» &7{MESSAGE}'
```
* ChatControl :
```yaml
Formatter:
    Enabled: false
Packets:
    Deserialize_Json: false
```

And I get : 
```<LemonLight29> Hello World```
instead of : 
``` [Member] LemonLight29 » Hello World ```

NB : When I uninstall ChatControl, the chat formatting works perfectly.
NB2 : I am using LuckPerms permission plugin

Thanks in advance :)

**Comment by kangarko** [comment]
Hello,

when you set Formatter.Enabled to false in ChatControl, the chat is left unformatted by us, we only apply antispam and rules. Can you also try removing LuckPerms for 1 testing round?

**Comment by LemonLight** [comment]
Of course ! I uninstalled LuckPerms but it still does not work.. :/
It still stays as the default chat formatting : ```<LemonLight29> Hello World```

**Comment by LemonLight** [comment]
Of course ! I am using 1.13, here the /version command's result : This server is running CraftBukkit version git-Spigot-2b0e71c-c0df4b8 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[ChatControl.zip](https://github.com/kangarko/ChatControl/files/2290298/ChatControl.zip)

**Comment by kangarko** [comment]
Thanks!

I detected that this is a priority mismatch, fix by setting this option to LOWEST in our settings.yml:

![a](https://i.imgur.com/11O0PXM.png)
