### ISSUE TITLE
Overriding TownyChat

### ISSUE THREAD

**Issue by punkrocker250** [kangarko/ChatControl#312]
Im trying to get TownyChat to handle the titles and chat formatting, but whenever I had chatcontrol on the server, it refuses to allow townychat to do the formatting.

It also doesn't allow the towny channels. It forces its own channels.

**Comment by kangarko** [comment]
Try adjusting Formatter priority (https://github.com/kangarko/ChatControl-pro/wiki/Listener-Priorities) from LOWEST to HIGH and even MONITOR. If that does not work than it is incompatible.
