### ISSUE TITLE
Network Unreachable

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#313]
What the hell is this? xD
https://hastebin.com/kelebecelo.md
I'm willing to bet it's some sort of experimental anti-stealing method you came up with, since it happened as I changed host. <u<
Can you please fix this for me? I just can't use the plugin and it works fine on my other host.

PD: yes, AutoSaveWorld loves critisizing plugins that mess around on main server thread.

**Comment by kangarko** [comment]
Wrong section, this is for the free version.

Anyways, this has been solved. I apologies for the inconvenience.
