### ISSUE TITLE
Strange Channel changing behaviour

### ISSUE THREAD

**Issue by saschahi** [kangarko/ChatControl#315]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

some... strange behaviours that I found while switching around channels.

- If you're in no channel at all, then join a channel in write mode, and then another channel in read mode, you get kicked out of the first channel (where you're in write mode in) without any message. You can then rejoin the first channel in write mode and it works without a problem.

oh and:

for some reason it doesn't do that always
imgur 1 https://imgur.com/a/hidvRC4
imgur 2 https://imgur.com/a/m61oAUu
and a time it somehow actually worked https://imgur.com/a/oPfV6hc

debug.zip
https://ufile.io/h799yxpk

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: false
> BungeeCord: false
> 
> some... strange behaviours that I found while switching around channels.
> 
> * If you're in no channel at all, then join a channel in write mode, and then another channel in read mode, you get kicked out of the first channel (where you're in write mode in) without any message. You can then rejoin the first channel in write mode and it works without a problem.
> 
> oh and:
> 
> for some reason it doesn't do that always
> imgur 1 https://imgur.com/a/hidvRC4
> imgur 2 https://imgur.com/a/m61oAUu
> and a time it somehow actually worked https://imgur.com/a/oPfV6hc
> 
> debug.zip
> https://ufile.io/h799yxpk

Hey! What's the value for `Max_Read_Channels:` in your settings file?

**Comment by saschahi** [comment]
```
Groups:
  staff:
    Message_Delay: 0 seconds
    Max_Read_Channels: 10
    Rejoin_Cooldown: 0
  player:
    Max_Read_Channels: 2
```
was tested with the staff permission (there are only 3 channels, and one is staffchannel)

oh but I left

```
Channels: 
  ...
  Max_Read_Channels: 1
  ...
```
because it said it overwrites in groups

**Comment by ElBananaa** [comment]
Try changing the 2nd one to 2, and see if it fixes the issue. ;)

**Comment by saschahi** [comment]
nope. still kicks me out (most of the time) when joining the second channel

**Comment by ElBananaa** [comment]
> nope. still kicks me out (most of the time) when joining the second channel

That's weird. Anyways, I just noticed you are still using ChatControlRed v10.1.5, please update to the latest version (v10.1.9) and try again.

**Comment by saschahi** [comment]
still happens

**Comment by kangarko** [comment]
Should be fixed in the next release.
