### ISSUE TITLE
Party and Friends Compatibility

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#316]
Hi, you declined and closed my last request for you to make Chat Control Red compatible with Party and Friends because the Spigot version only has around 400 downloads.

But what you failed to check was the other version link i sent you, the Bungeecord version has 41,036  here: https://www.spigotmc.org/resources/party-and-friends-for-bungeecord.9531/

So please can you make CCR compatible with Party and Friends.

**Comment by kangarko** [comment]
Thanks, but the plugin seems premium and I don't have access to SpigotMC anymore. You can send the jar over to matej@mineacademy.org and link to your old issue please where you outlined what you needed us to implement.
