### ISSUE TITLE
[Feature Request] PlaceholderAPI (or similar) support

### ISSUE THREAD

**Issue by saschahi** [kangarko/ChatControl#317]
It'd be nice if you could have placeholders for:

- Chatcontrol_Channel_Joined_write_*channelname* as boolean
- Chatcontrol_Channel_Joined_read_*channelname* as boolean
- Chatcontrol_number_of_chanels_joined as int

would make making custom GUIs a lot easier.
if nothing of that sort is planned just close this issue

**Comment by ElBananaa** [comment]
> It'd be nice if you could have placeholders for:
> 
> * Chatcontrol_Channel_Joined_write__channelname_ as boolean
> * Chatcontrol_Channel_Joined_read__channelname_ as boolean
> * Chatcontrol_number_of_chanels_joined as int
> 
> would make making custom GUIs a lot easier.
> if nothing of that sort is planned just close this issue

Hey! For the 2 first placeholders, there's something like that: 
`{chatcontrolred_player_in_channel_<channel>}` returns true or false if the player is in the given channel

For the others, I'm no sure. Here's the list of placeholders: https://github.com/kangarko/ChatControl-Red/wiki/Variables

**Comment by saschahi** [comment]
oooh nice :D I didn't see that ^^ thx. exactly what I needed
