### ISSUE TITLE
Boss Red?

### ISSUE THREAD

**Issue by Ergenta** [kangarko/ChatControl#318]
I realize my question doesn't reference this plugin but since you dropped all support and deleted everything from spigot, this is the only place I could ask.

Is there a "Boss Red" version found mcmarket like there is "Chatcontrol Red"? Perhaps you're still working on that 4.0 version you said was coming 2yrs ago and I stuck around for.

**Comment by ElBananaa** [comment]
> I realize my question doesn't reference this plugin but since you dropped all support and deleted everything from spigot, this is the only place I could ask.
> 
> Is there a "Boss Red" version found mcmarket like there is "Chatcontrol Red"? Perhaps you're still working on that 4.0 version you said was coming 2yrs ago and I stuck around for.

Hey! I can't talk for Kangarko, but afaik, he announced that for now, he will only focus on ChatControl Pro/Red and Project Orion since he doesn't have time to work on many plugins/projects like he used to.

**Comment by kangarko** [comment]
Nope. We're not having the time capacity to rewrite Boss 3 right now. I would love to introduce Boss 4, if it would be an upgrade, then it's going to be free, but in case of a rewrite, I think it's fair to republish it. However as I can see it I am a single-man developer right now and that's more than I can do in my timeframes.

**Comment by kangarko** [comment]
However, I want to make clear that I will continue updating Boss 3 and even add some of the top requested features. We love Boss and it will not get abandoned.
