### ISSUE TITLE
Staff Leave message

### ISSUE THREAD

**Issue by slvlr** [kangarko/ChatControl#319]
When a staff member disconnects from the server by default (Vanish no packet) no leave message is sent to the server. 

Since installing chat control it has been saying for oped players "Staff - playername"  when they disconnect.
https://gyazo.com/0b2946e17ce6b7e05b0edcc5dd6be355

What is the permission node that I can use to negate this from happening?
or is there a config option?

**Comment by kangarko** [comment]
Unfortunately, the free version does not have a permission for this. It only should hide the message if the player is vanished.

The pro version has chatcontrol.messages.join permissions and further customizations.
