### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kennethbgoodin** [kangarko/ChatControl#320]
In ChatControl.class you have a Map of String to PlayerCache. Is there a reason entries are never removed i.e. after the player's disconnected and a certain amount of time has passed? Atm it's causing a slow leak.

**Comment by kangarko** [comment]
Usually servers are being restarted at least once a day, so that is generally not a problem.

I have reworked the Reset_Cache_On_Quit option to remove player's cache on their exit, but keep in mind this will wipe their antispam so they will be able to bypass chat delay when the log in again.
