### ISSUE TITLE
DiscordSRV Send_As_Bot broken?

### ISSUE THREAD

**Issue by m171717** [kangarko/ChatControl#320]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Hello,
We use the experimental option of DiscordSRV, which allows us to send avatar images and names in Discord chat. Our players much prefer this, and I see no way of enabling this in ChatControl-Red with the exception of   Send_Messages_As_Bot: false

However, this setting doesn't change anything it seems beyond not editing Discord->Minecraft messages.

Is there anyway to use the experimental avatar web hook again?

**Comment by kangarko** [comment]
Thanks, next version will fix Integration.Discord.Send_Messages_As_Bot, just make sure it's on false.

<img width="300" alt="Screenshot 2020-12-22 at 18 55 48" src="https://user-images.githubusercontent.com/1918426/102918509-527b0600-4487-11eb-850a-c9d7d67a3e89.png">

**Comment by kangarko** [comment]
Below is messages after changing Send_Messages_As_Bot to false.
