### ISSUE TITLE
Formatting Problem

### ISSUE THREAD

**Issue by CoutovyLp** [kangarko/ChatControl#321]
Hi. I have a problem with formatting. I am doing prefixes and it´s not working. 
Minecraft version: 1.16.4
Bungee: False
MySQL: False

Errror: https://pastebin.com/ijfYWTYk

chat.yml: https://pastebin.com/BVKBpbyz

Thank you <3

**Comment by ElBananaa** [comment]
> Hi. I have a problem with formatting. I am doing prefixes and it´s not working.
> Minecraft version: 1.16.4
> Bungee: False
> MySQL: False
> 
> Errror: https://pastebin.com/ijfYWTYk
> 
> chat.yml: https://pastebin.com/BVKBpbyz
> 
> Thank you <3

Hey! There's a problem with the indentations of your file and with the multiline setup. You need to use a `-` before each line when using multiline in formats. Try with this file, it should fix your issue: https://pastebin.com/wmDuapm2

**Comment by braceyourself07** [comment]
> Hey! There's a problem with the indentations of your file and with the multiline setup. You need to use a `-` before each line when using multiline in formats. Try with this file, it should fix your issue: https://pastebin.com/wmDuapm2


This ^  and you also may want to google "YML validator" and copy/paste your YML files into it to make sure your syntax is correct.  Good way to problem solve syntax issues.

**Comment by CoutovyLp** [comment]
Oh god. I am such and idiot. Thank you very much <3

**Comment by CoutovyLp** [comment]
I have one more problem.. :/ I don´t know why.. But prefixes etc. not working

Screenshot + yml: 
https://pastebin.com/Dg7a7RPH

https://ctrlv.cz/QbJf

No errors in console.. I can´t find anywhere that I can enable Chat Formatting

**Comment by ElBananaa** [comment]
Hey! If it fixed your issue, don't forget to close it ;D

**Comment by kangarko** [comment]
No worries <3 Next time use https://yaml-online-parser.appspot.com/ to check your file.
