### ISSUE TITLE
Total and Utter Nightmare.

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#322]
First i couldn't get a placeholder to work
then I got it to work after a reinstall but my per world channels were disabled in the process
spend half the day trying to get a name placeholder to work
next I try my uperms rank placeholder and that works but it's not showing it's color.
and to top that off i'm now having to do the bloody tour every 5 minutes.

Spent the entire day on this and now have a splitting migraine, 18 hours and 47 minutes to be exact and got absolutely nowhere..

**Comment by SirCraftypants** [comment]
Bit annoyed to be honest, never had so much issue with a plugin before. I get that it's new and being fixed but none of my place holders are working, i've found that few of my plugins are compatible and it seems to be devoted more to Bungeecord users which i am not and the Dev seems to be selective in what he is willing to support. So what do i do, change half my plugins to be able to use this. already wasted almost 19 hours on it so far and i'll have to reset up at least 8 plugins all over again minimum. If i knew i was potentially buying a plugin that wasn't even officially released until after i bought it i wouldn't have been so quick to buy so soon.  Extremely frustrated doesn't even come close, not even a per world chat enable setting.

**Comment by kangarko** [comment]
Hey, sorry for your frustrations, I'm move than happy to help if you mention specifically what placeholder was problematic, and you ZIP your folder as per our issue guideliness so I can help with the rest.
