### ISSUE TITLE
Wither rose deathmessage

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl#323]
A death due to the effect of a wither rose is not traced back to it, instead a death message from the wither is called. It would make some nice new death messages possible, if one could differentiate here.
I tried this one:
```
group witherrose
require block WITHER_ROSE
require block POTTED_WITHER_ROSE
bungee
message: 
- &e{player} &7geriet in eine Venusfliegenfalle
```
Nevertheless, the following event is triggered:
```
group wither
require cause WITHER
bungee
message: 
- &e{player} &7ist verwelkt
- &e{player} &7hat die Milch verschüttet
```

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5720718/debug.zip)
ChatControl 10.1.9
Tuinity-"8056d13" (MC: 1.16.4)

PS: Big thumbs up for the successful recode!

**Comment by ElBananaa** [comment]
Hey!

Try with these options, and tell me if it works:
```
group witherrose
require block WITHER_ROSE
bungee
message: 
- &e{player} &7geriet in eine Venusfliegenfalle
```

```
group witherrosepot
require block POTTED_WITHER_ROSE
bungee
message: 
- &e{player} &7geriet in eine Venusfliegenfalle
```

```
group witherskeleton
require cause ENTITY_ATTACK
require killer WITHER_SKELETON
bungee
message: 
- &e{player} &7ist verwelkt
- &e{player} &7hat die Milch verschüttet
```

```
group wither
require cause WITHER
bungee
message: 
- &e{player} &7ist verwelkt
- &e{player} &7hat die Milch verschüttet
```

**Comment by TheoRetisch1** [comment]
Thank you for your help! I was wrong about potted witherroses: They don't deal damage to the player. Anyway I tried your advice and it didn't work :/.
The witherskeleton group is triggered when a player is killed by the witherskeleton with a sword. However, if you die from the effect of the witherskeleton, the wither group is triggered. The witherrose group cannot be triggered at all, the effect of the witherrose always triggers the wither group. 
Conclusion: At the moment, no differentiation between the causers of the wither status effects is possible, it always triggers the group wither. It would be brilliant if a differantion would become possible 👍

**Comment by ElBananaa** [comment]
> Thank you for your help! I was wrong about potted witherroses: They don't deal damage to the player. Anyway I tried your advice and it didn't work :/.
> The witherskeleton group is triggered when a player is killed by the witherskeleton with a sword. However, if you die from the effect of the witherskeleton, the wither group is triggered. The witherrose group cannot be triggered at all, the effect of the witherrose always triggers the wither group.
> Conclusion: At the moment, no differentiation between the causers of the wither status effects is possible, it always triggers the group wither. It would be brilliant if a differantion would become possible 👍

Alright, then try:
```
group wither
require cause ENTITY_ATTACK
require killer WITHER
bungee
message: 
- &e{player} &7ist verwelkt
- &e{player} &7hat die Milch verschüttet
```

```
group witherskeleton
require cause ENTITY_ATTACK
require killer WITHER_SKELETON
bungee
message: 
- &e{player} &7ist verwelkt
- &e{player} &7hat die Milch verschüttet
```

```
group witherrose
require block WITHER_ROSE
require cause WITHER
bungee
message: 
- &e{player} &7geriet in eine Venusfliegenfalle
```

**Comment by TheoRetisch1** [comment]
I tried it, but now the death message groups are not triggered at all, instead the default group is addressed :/
```
group default
bungee
message: 
- &e{player} &7has messed with higher powers
- &e{player} &7died unhappily
- &e{player} &7is a bit smarter now
- &e{player} &7misses his inventory
- &e{player} &7is no longer salvageable. The doctor came too late.
```

**Comment by ElBananaa** [comment]
> I tried it, but now the death message groups are not triggered at all, instead the default group is addressed :/
> 
> ```
> group default
> bungee
> message: 
> - &e{player} &7has messed with higher powers
> - &e{player} &7died unhappily
> - &e{player} &7is a bit smarter now
> - &e{player} &7misses his inventory
> - &e{player} &7is no longer salvageable. The doctor came too late.
> ```

Hmmm, that's really weird, I'm sorry, but I don't think I could help you more with this ^^

**Comment by TheoRetisch1** [comment]
Thank you for your help ElBananaa :)

**Comment by kangarko** [comment]
Will check this out tomorrow :)

**Comment by kangarko** [comment]
I reviewed the system and this is something requiring a larger code update that I simply don't have time time for, now. We'll try to return to this in a few months in favor of prioritizing more important issues. Thank you for your understanding.

**Comment by TheoRetisch1** [comment]
Ok thanks for considering! I already tried a year ago, back then it was stated most likely with the recode (https://github.com/kangarko/ChatControl-Pro/issues/1686). I will try again in three months if this is ok. Have a nice christmas!
