### ISSUE TITLE
Custom deathmessage for lingering damage potions and damage potions

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl#324]
I want to define custom deathmessages for lingering damage potions and for dying because of trinking damage potions, but I can't figure out how.

I tried this one for harming potions:

```
group damage-potion
require block POTION
bungee
message: 
- &7Ist die Potion zu stark, bist du zu schwach, &e{player}
- &e{player} &7verwechselte die Flaschen
- &e{player} &7war durstig
```
But instead this one get's triggered:

```
group entity-attack-by-pvp-diamond-sword
require cause ENTITY_ATTACK
require killer PLAYER
require killer item DIAMOND_SWORD
bungee
message: 
- &c{player} &7fiel dem Schwert von &a{killer} &7zum Opfer
- &c{player} &7überlegt es sich demnächst zweimal mit wem man spielen kann
- &c{player} &7wurde von &a{killer} &7in dünne Scheibchen geschnitten
```

I tried this one for lingering damage potions:
```
group damage-potion
require block LINGERING_POTION
bungee
message: 
- &e{player} &7erfuhr die verzögerte Rache des Drachens
- &e{player} &7spielte zu lange mit den Blasen
- &e{player} &7verärgerte (wieder) einen Alchemisten
```
But instead this one get's triggered:
```
group entity-attack
require cause ENTITY_ATTACK
bungee
message: 
- &e{player} &7dachte, &a{killer} &7mag Umarmungen
```
Could you please give me a hint? I just searched for potions in the Wiki documentation and found them under blocks.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5720751/debug.zip)
ChatControlRed 10.1.9
Tuinity-"8056d13" (MC: 1.16.4)

**Comment by ElBananaa** [comment]
Hey! Regarding death reasons, I don't think you could actually use a different message for each potion.
You should consider using: `require cause magic` (you can find the different causes here) https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html

**Comment by TheoRetisch1** [comment]
Thanks for your answer! I know the MAGIC variable. I also never wanted to specify the potion type. But the variables POTION and LINGERING_POTION can be found here: https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/remain/CompMaterial.java

So one should be able to use 
`require block POTION`
or `require killer item POTION`
together with `require cause magic`, but it just doesn't work. I would consider this to be a bug?

**Comment by ElBananaa** [comment]
> Thanks for your answer! I know the MAGIC variable. I also never wanted to specify the potion type. But the variables POTION and LINGERING_POTION can be found here: https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/remain/CompMaterial.java
> 
> So one should be able to use
> `require block POTION`
> or `require killer item POTION`
> together with `require cause magic`, but it just doesn't work. I would consider this to be a bug?

Hmm, tbho I have no idea, so yeah, you should leave this ticket open

**Comment by TheoRetisch1** [comment]
I reseted and rebuilt my death.rs for better debugging. I found out that it is definitely an `ENTITY ATTACK` and the cause `MAGIC` is indeed triggered. However, it still does not differentiate down to `POTION`. I have also not been able to get `LINGERING_POTION` to work.

**Comment by kangarko** [comment]
I reviewed the system and this is something requiring a larger code update that I simply don't have time time for, now. We'll try to return to this in a few months in favor of prioritizing more important issues. Thank you for your understanding.

**Comment by TheoRetisch1** [comment]
Ok thanks for considering. I have tried before in 2018, it was even in the roadmap back then (https://github.com/kangarko/ChatControl-Pro/issues/801). I will try again in three months if this is ok :)
