### ISSUE TITLE
Askyblock placeholder error

### ISSUE THREAD

**Issue by bladbl** [kangarko/ChatControl#324]
Hello! I have a little problem.
`Global_Message_Format: '&7[Всем]&7 %askyblock_level% &f%pl_prefix%player%pl_suffix  &a➠&7 %message '` -Work
`Global_Message_Format: '&7[Всем]&7 &f%pl_prefix%player%pl_suffix %askyblock_level%  &a➠&7 %message '` -Does not work

**Comment by kangarko** [comment]
Hey, I am afraid this is a problem with the ASkyblock plugin itself. Try changing the formatter listener priority as outlined here: https://github.com/kangarko/ChatControl-pro/wiki/Listener-Priorities
