### ISSUE TITLE
Luckperms permission issue

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#325]
Minecraft Version: 1.16.4 Paper
MySQL: false
BungeeCord: false

OK so after finding out my premium Ultra Permissions was one of a few plugins that are not compatible with ChatControl Red I was left with 2 choices. 1. get rid of ChatControl Red, cut my losses and settle for a lesser Chat solution or 2. get rid of a few Premium Plugins and start using some compatible alternatives.

After hours if struggling to come to terms with losing a few premium plugins i decided to give ChatControl Red a chance.

So Ultra Permissions is gone and Luckperms is installed, one of 4 premium plugins to hit the losses pile.

NOW TO THE PROBLEM.

I've setup Luckperms and assigned Chatcontrol permissions to the default group, my alt is successfully joined to the default group but ChatControl says in chat that he's lacking the permission to use /ch.

**Comment by ElBananaa** [comment]
Hey! About the compatibility issues, you should consider opening an issue to know if Kangarko can do anything about it.
Related to the channel permission, make sure the default group has the following permissions: https://github.com/kangarko/ChatControl-Red/wiki/Channels#auto-join

**Comment by 00Hrtz** [comment]
> 
> 
> Hey! About the compatibility issues, you should consider opening an issue to know if Kangarko can do anything about it.
> Related to the channel permission, make sure the default group has the following permissions: https://github.com/kangarko/ChatControl-Red/wiki/Channels#auto-join

I've given my alt all of these 

lp group default permission set chatcontrol.channel.autojoin.standard.write true.
lp group default permission set chatcontrol.channel.autojoin.global.write true.
lp group default permission set chatcontrol.channel.join.global.write true.
lp group default permission set chatcontrol.channel.join.standard.write true.
lp group default permission set chatcontrol.channel.leave.global true.
lp group default permission set chatcontrol.channel.leave.standardtrue.

lp group default permission set chatcontrol.command.mail true.
lp group default permission set chatcontrol.command.tell true.
lp group default permission set chatcontrol.command.reply true.
lp group default permission set chatcontrol.chat.write true.
lp group default permission set chatcontrol.chat.read true.
lp group default permission set chatcontrol.channel.join true.


ChatControl still says i haven't got the permission.

It's also saying no channels exist for my alt but, everything is working fine for my opped account.

**Comment by 00Hrtz** [comment]
Now it keeps saying in chat that i don't have permission: chatcontrol.channel.join

but i do as you can see above.

One of your test team must have used Luckperms and figured it out?

**Comment by 00Hrtz** [comment]
Please can someone help, i've spent 2 entire days on this now, had to change my permissions plugin only to find out unless someones opped, they cant see or use any channels because the permissions don't work in luckperms. Why am i the only one reporting this when there are clearly other luckperm users here. i've contacted them all but none have replied. Going to have a mental breakdown at some point.

**Comment by NerdyBirder** [comment]
We use luckperms on our server but we use a bungeecord network so ours is set up a bit differently. Also we migrated to Chatcontrol Red from the Pro plugin so didn't have to give all the permissions fresh like you had to.

But i would look for these things to see if they are enabled:
- check the newcomer settings in the settings.yml to see what they are set to
- check to make sure that you don't have any permissions in the permissions.yml which might conflict with chatcontrol's use of your luckperms setup
- be sure that your default group does have the permissions that you added by doing /lp group default check <permission> just to be sure things saved because it could be something wrong with luckperms saving the perms too.
- check to make sure that your default group has these permissions in addition to the ones you listed chatcontrol.chat.write and chatcontrol.channel.send.<channelname>

Hope this helps!

**Comment by 00Hrtz** [comment]
> 
> 
> We use luckperms on our server but we use a bungeecord network so ours is set up a bit differently. Also we migrated to Chatcontrol Red from the Pro plugin so didn't have to give all the permissions fresh like you had to.
> 
> But i would look for these things to see if they are enabled:
> 
>     * check the newcomer settings in the settings.yml to see what they are set to
> 
>     * check to make sure that you don't have any permissions in the permissions.yml which might conflict with chatcontrol's use of your luckperms setup
> 
>     * be sure that your default group does have the permissions that you added by doing /lp group default check  just to be sure things saved because it could be something wrong with luckperms saving the perms too.
> 
>     * check to make sure that your default group has these permissions in addition to the ones you listed chatcontrol.chat.write and chatcontrol.channel.send.
> 
> 
> Hope this helps!

newcomer is disabled

Permissions.yml? where's that located, i've looked in luckperms and chatcontrolred.

/lp group default    says they are all set to undefined global

**These are the perms i've set**

lp group default permission set chatcontrol.channel.join.global.write true.
lp group default permission set chatcontrol.channel.join.standard.write true.
lp group default permission set chatcontrol.channel.join.ranged.write true.

lp group default permission set chatcontrol.channel.join.global.read true.
lp group default permission set chatcontrol.channel.join.standard.read true.
lp group default permission set chatcontrol.channel.join.ranged.read true.

lp group default permission set chatcontrol.channel.send.global true.
lp group default permission set chatcontrol.channel.send.standard true.

lp group default permission set chatcontrol.chat.write true.
lp group default permission set chatcontrol.chat.read true.


**Still saying i haven't got permission chatcontrol.channel.join   on my alt who's confirmed to be in default group and when i run /ch on my alt is shows no channels**

**My opped account has full access to all the channels**

**Comment by 00Hrtz** [comment]
> 
> 
> We use luckperms on our server but we use a bungeecord network so ours is set up a bit differently. Also we migrated to Chatcontrol Red from the Pro plugin so didn't have to give all the permissions fresh like you had to.
> 
> But i would look for these things to see if they are enabled:
> 
>     * check the newcomer settings in the settings.yml to see what they are set to
> 
>     * check to make sure that you don't have any permissions in the permissions.yml which might conflict with chatcontrol's use of your luckperms setup
> 
>     * be sure that your default group does have the permissions that you added by doing /lp group default check  just to be sure things saved because it could be something wrong with luckperms saving the perms too.
> 
>     * check to make sure that your default group has these permissions in addition to the ones you listed chatcontrol.chat.write and chatcontrol.channel.send.
> 
> 
> Hope this helps!

Please can you show me a copy of your default groups permissions list?
