### ISSUE TITLE
Block illegal characters in a book and prevent dupe glitch

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#325]
Hey,

I was wondering if there is a way with ChatControl to block illegal characters in books?

Is it possible to prevent this dupe glitch with the use of ChatControl? And if so how?

https://www.youtube.com/watch?v=sd8SM8YWP9U&feature=youtu.be

Thanks in advance.

**Comment by ArtelGG** [comment]
I personally use this in `rules.txt`:

>>>```
# Blocks special characters.
match [^\u0000-\u007F]+
ignore string \p{Sc}
then deny
then warn &cSpecial characters are not allowed.
```
Works wonders. Perhaps you could make it less strict, then apply it to books. You could also just disable the crafting of book and quills.

**Comment by Sikatsu** [comment]
Thanks for your answer. Do you know if this works for the dupe glitch aswell?

Hmm, disabling that kind of breaks a gameplay feature. Rather just block the characters. ^^

**Comment by ArtelGG** [comment]
No idea, I just disabled book & quills and signed books.
Use https://regex101.com/ and follow the pastebin link from the description of that video you linked and do some testing.

**Comment by Sikatsu** [comment]
I do not see any pastebin link in that description. Do you perhaps mean another video about the same issue?

**Comment by ArtelGG** [comment]
https://pastebin.com/kREVWL4b

**Comment by kangarko** [comment]
Thank you @ArtelGG for the answer!

PS: In ChatControl Pro, you can place that rule in rules/books.txt file so it will only be run when signing a book.

**Comment by Sikatsu** [comment]
Yup, that's what I did and it's solved for me! Thanks @ArtelGG
