### ISSUE TITLE
Chat Formatting not works for me

### ISSUE THREAD

**Issue by CoutovyLp** [kangarko/ChatControl#326]
Minecraft Version: 1.16.4
Bungee: False
MySQL: False

Hello. I have one more problem.. The problem is, that Chat formatting is not working.

Screenshot + yml:
https://pastebin.com/Dg7a7RPH

https://ctrlv.cz/QbJf

No errors in console

Thanks for your reply

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> Bungee: False
> MySQL: False
> 
> Hello. I have one more problem.. The problem is, that Chat formatting is not working.
> 
> Screenshot + yml:
> https://pastebin.com/Dg7a7RPH
> 
> https://ctrlv.cz/QbJf
> 
> No errors in console
> 
> Thanks for your reply

Hey! Could you provide the zipped plugin's folder (Chatcontrol plugin folder) and the latest.log please?

**Comment by CoutovyLp** [comment]
> > Minecraft Version: 1.16.4
> > Bungee: False
> > MySQL: False
> > Hello. I have one more problem.. The problem is, that Chat formatting is not working.
> > Screenshot + yml:
> > https://pastebin.com/Dg7a7RPH
> > https://ctrlv.cz/QbJf
> > No errors in console
> > Thanks for your reply
> 
> Hey! Could you provide the zipped plugin's folder (Chatcontrol plugin folder) and the latest.log please?

Of course! Here it is: https://mega.nz/file/HddwlRIS#5mnhqtO5kuQUPQRcrzcAljHr6hJW_KfFeRtYk2JAQgM

**Comment by ElBananaa** [comment]
> > > Minecraft Version: 1.16.4
> > > Bungee: False
> > > MySQL: False
> > > Hello. I have one more problem.. The problem is, that Chat formatting is not working.
> > > Screenshot + yml:
> > > https://pastebin.com/Dg7a7RPH
> > > https://ctrlv.cz/QbJf
> > > No errors in console
> > > Thanks for your reply
> > 
> > 
> > Hey! Could you provide the zipped plugin's folder (Chatcontrol plugin folder) and the latest.log please?
> 
> Of course! Here it is: https://mega.nz/file/HddwlRIS#5mnhqtO5kuQUPQRcrzcAljHr6hJW_KfFeRtYk2JAQgM

Thanks! Btw, you can also use `/chc debug` ingame to automatically upload a copy of you files with all the informations needed. The file can be found under `/plugins/ChatControlRed/debug.zip` :)

**Comment by CoutovyLp** [comment]
> > > > Minecraft Version: 1.16.4
> > > > Bungee: False
> > > > MySQL: False
> > > > Hello. I have one more problem.. The problem is, that Chat formatting is not working.
> > > > Screenshot + yml:
> > > > https://pastebin.com/Dg7a7RPH
> > > > https://ctrlv.cz/QbJf
> > > > No errors in console
> > > > Thanks for your reply
> > > 
> > > 
> > > Hey! Could you provide the zipped plugin's folder (Chatcontrol plugin folder) and the latest.log please?
> > 
> > 
> > Of course! Here it is: https://mega.nz/file/HddwlRIS#5mnhqtO5kuQUPQRcrzcAljHr6hJW_KfFeRtYk2JAQgM
> 
> Thanks! Btw, you can also use `/chc debug` ingame to automatically upload a copy of you files with all the informations needed. The file can be found under `/plugins/ChatControlRed/debug.zip` :)

I know :D I realized it then I just did this :D

**Comment by ElBananaa** [comment]
Alright, you're not using the right version of protocolLib. Download this one https://ci.dmulloy2.net/job/ProtocolLib/lastBuild/artifact/target/ProtocolLib.jar and try again.

**Comment by CoutovyLp** [comment]
> Alright, you're not using the right version of protocolLib. Download this one https://ci.dmulloy2.net/job/ProtocolLib/lastBuild/artifact/target/ProtocolLib.jar and try again.

Still not working :(

**Comment by CoutovyLp** [comment]
> Alright, you're not using the right version of protocolLib. Download this one https://ci.dmulloy2.net/job/ProtocolLib/lastBuild/artifact/target/ProtocolLib.jar and try again.

Is the chat.yml right? Is there some mistake or something? :/

**Comment by ElBananaa** [comment]
> > Alright, you're not using the right version of protocolLib. Download this one https://ci.dmulloy2.net/job/ProtocolLib/lastBuild/artifact/target/ProtocolLib.jar and try again.
> 
> Is the chat.yml right? Is there some mistake or something? :/

It looks fine to me. That's really weird. Could you try to install the plugin on a local server (with only Vault, protocolLib, luckperms and ChatControlRed) with your actual config folder and tell me if it fixes this issue.

**Comment by CoutovyLp** [comment]
> > > Alright, you're not using the right version of protocolLib. Download this one https://ci.dmulloy2.net/job/ProtocolLib/lastBuild/artifact/target/ProtocolLib.jar and try again.
> > 
> > 
> > Is the chat.yml right? Is there some mistake or something? :/
> 
> It looks fine to me. That's really weird. Could you try to install the plugin on a local server (with only Vault, protocolLib, luckperms and ChatControlRed) with your actual config folder and tell me if it fixes this issue.

Ok. I´ll try

**Comment by CoutovyLp** [comment]
> > > Alright, you're not using the right version of protocolLib. Download this one https://ci.dmulloy2.net/job/ProtocolLib/lastBuild/artifact/target/ProtocolLib.jar and try again.
> > 
> > 
> > Is the chat.yml right? Is there some mistake or something? :/
> 
> It looks fine to me. That's really weird. Could you try to install the plugin on a local server (with only Vault, protocolLib, luckperms and ChatControlRed) with your actual config folder and tell me if it fixes this issue.

Ok. I tried it.. But still not working.. :/

**Comment by ElBananaa** [comment]
Alright, so you messed-up somewhere in your config files. Which files did you edit?

**Comment by CoutovyLp** [comment]
> Alright, so you messed-up somewhere in your config files. Which files did you edit?

Just chat.yml :D

**Comment by CoutovyLp** [comment]
> Alright, so you messed-up somewhere in your config files. Which files did you edit?

Have I to enable it somewhere in settings or something? Because i didn´t find anything..

**Comment by ElBananaa** [comment]
> > Alright, so you messed-up somewhere in your config files. Which files did you edit?
> 
> Have I to enable it somewhere in settings or something? Because i didn´t find anything..

It is enabled by default. Try with this file: https://hastebin.com/siveguvuzo.sql

**Comment by CoutovyLp** [comment]
> > > Alright, so you messed-up somewhere in your config files. Which files did you edit?
> > 
> > 
> > Have I to enable it somewhere in settings or something? Because i didn´t find anything..
> 
> It is enabled by default. Try with this file: https://hastebin.com/siveguvuzo.sql

I´ve tried.. But still not working :(

**Comment by ElBananaa** [comment]
Ohh wait I'm dumb, you need to enable the channels system. At the top of the file, set:
```
Channels:
  
  # Should we format the chat and apply channels?
  Enabled:``` to `true`
```
And follow this video to setup the plugin correctly: https://www.youtube.com/watch?v=EKziLXSjwhY

**Comment by CoutovyLp** [comment]
Ok. Now I have this :D

![image](https://user-images.githubusercontent.com/42292648/102721167-71e42880-42f9-11eb-92f1-5a84dfd2d293.png)

**Comment by ElBananaa** [comment]
> Ok. Now I have this :D
> 
> ![image](https://user-images.githubusercontent.com/42292648/102721167-71e42880-42f9-11eb-92f1-5a84dfd2d293.png)

Follow the video and the wiki to setup the plugin correctly, and you're done. :)

**Comment by CoutovyLp** [comment]
> > Ok. Now I have this :D
> > ![image](https://user-images.githubusercontent.com/42292648/102721167-71e42880-42f9-11eb-92f1-5a84dfd2d293.png)
> 
> Follow the video and the wiki to setup the plugin correctly, and you're done. :)

Ok. Thank you very much <3

**Comment by CoutovyLp** [comment]
> > Ok. Now I have this :D
> > ![image](https://user-images.githubusercontent.com/42292648/102721167-71e42880-42f9-11eb-92f1-5a84dfd2d293.png)
> 
> Follow the video and the wiki to setup the plugin correctly, and you're done. :)

Can you help me with one more thing? :D 
{player_prefix}/{player_prefix+}/{player_suffix} ----> What I have to replace for that placeholders? It´s gets the prefix and suffix from LuckPerms

**Comment by ElBananaa** [comment]
> > > Ok. Now I have this :D
> > > ![image](https://user-images.githubusercontent.com/42292648/102721167-71e42880-42f9-11eb-92f1-5a84dfd2d293.png)
> > 
> > 
> > Follow the video and the wiki to setup the plugin correctly, and you're done. :)
> 
> Can you help me with one more thing? :D
> {player_prefix}/{player_prefix+}/{player_suffix} ----> What I have to replace for that placeholders? It´s gets the prefix and suffix from LuckPerms

Sure! What are you trying to do exactly? I don't really understand

**Comment by CoutovyLp** [comment]
> > > > Ok. Now I have this :D
> > > > ![image](https://user-images.githubusercontent.com/42292648/102721167-71e42880-42f9-11eb-92f1-5a84dfd2d293.png)
> > > 
> > > 
> > > Follow the video and the wiki to setup the plugin correctly, and you're done. :)
> > 
> > 
> > Can you help me with one more thing? :D
> > {player_prefix}/{player_prefix+}/{player_suffix} ----> What I have to replace for that placeholders? It´s gets the prefix and suffix from LuckPerms
> 
> Sure! What are you trying to do exactly? I don't really understand

Nothing. I solved it. :D But thanks <3

**Comment by ElBananaa** [comment]
> > > > > Ok. Now I have this :D
> > > > > ![image](https://user-images.githubusercontent.com/42292648/102721167-71e42880-42f9-11eb-92f1-5a84dfd2d293.png)
> > > > 
> > > > 
> > > > Follow the video and the wiki to setup the plugin correctly, and you're done. :)
> > > 
> > > 
> > > Can you help me with one more thing? :D
> > > {player_prefix}/{player_prefix+}/{player_suffix} ----> What I have to replace for that placeholders? It´s gets the prefix and suffix from LuckPerms
> > 
> > 
> > Sure! What are you trying to do exactly? I don't really understand
> 
> Nothing. I solved it. :D But thanks <3

Great, good to know :)
Don't forget to close the issue ;)
