### ISSUE TITLE
Please add a toggle for replace

### ISSUE THREAD

**Issue by Xsm0deus** [kangarko/ChatControl#328]
Hi, on our servers we give each Admin the * permission, unfortunately that makes our chat does not replace with emojis. If you could add a toggle to force emojis without using permissions that would be great :)

**Comment by kangarko** [comment]
Hello,

you can give admins "-chatcontrol.bypass.rules.*" negative permission to enforce rules on them, and then give them chatcontrol.bypass.swear and chatcontrol.bypass.ad to prevent ad and swear filters from being applied on them while emojis will continue to work.

Hope that helps,
Have a wonderful day!

**Comment by Xsm0deus** [comment]
Doesn't work, each admin has * permission

**Comment by kangarko** [comment]
Give admins negative -chatcontrol.bypass.rules.* permission, it must start with - if you have PermissionsEx or be false if you have Luckperms.
