### ISSUE TITLE
/reply sometimes returns the send message

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl#328]
`/reply ` randomly sends messages not only to the receiver, but also again in direct reply back to the sender. So the sender not only sends his message, but also receives his message back immediately as a reply. As mentioned, this phenomenon occurs randomly with some players. No such problems have been observed with /msg.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5721225/debug.zip)
ChatControlRed 10.1.9
Tuinity-"8056d13" - MC: 1.16.4

**Comment by Sikatsu** [comment]
Related to #222

**Comment by kangarko** [comment]
Investigating right now, please follow up on 222.
