### ISSUE TITLE
/t registers for chatcontrol, which makes it unable to register for towny

### ISSUE THREAD

**Issue by Managering** [kangarko/ChatControl#329]
/t is a much used command for towny.

/t is loaded and unloaded by chatcontrol on our network.
Towny is unable to register the command as chatcontrol already did so.

I've removed chatcontrol and rebooted, to confirm that indeed it's chatcontrol causing the issue.

How do I make sure chatcontrol does not load /t?

**Comment by ElBananaa** [comment]
> /t is a much used command for towny.
> 
> /t is loaded and unloaded by chatcontrol on our network.
> Towny is unable to register the command as chatcontrol already did so.
> 
> I've removed chatcontrol and rebooted, to confirm that indeed it's chatcontrol causing the issue.
> 
> How do I make sure chatcontrol does not load /t?

Hey! In the settings file, search for this part: `Tell_Aliases:`
And simply remove
`  - 't'`

Before: 
```
  Tell_Aliases:
  - 'tell'
  - 'w'
  - 'm'
  - 't'
  - 'pm'
  - 'message'
  - 'msg'
  - 'whisper'
 ```
After:
```
  Tell_Aliases:
  - 'tell'
  - 'w'
  - 'm'
  - 'pm'
  - 'message'
  - 'msg'
  - 'whisper'
```

**Comment by Managering** [comment]
I already have my settings as:

  # EDIT AS YOU WISH BUT DO NOT REMOVE THE FIRST ALIAS
  Tell_Aliases:
  - 'tell'
  - 'msg'
  - 'whisper'
  - 'pm'
  - 'privatemessage'
  - 'm'
  - 'w'
  
  This does not resolve the issue.
  I believe it is because chatcontrol still registers it somehow.

**Comment by ElBananaa** [comment]
> I already have my settings as:
> 
> # EDIT AS YOU WISH BUT DO NOT REMOVE THE FIRST ALIAS
> Tell_Aliases:
> 
> * 'tell'
> * 'msg'
> * 'whisper'
> * 'pm'
> * 'privatemessage'
> * 'm'
> * 'w'
> 
> This does not resolve the issue.
> I believe it is because chatcontrol still registers it somehow.

Alright, then in your commands.yml file (In the root directory of your server) add this line under aliases:
```
aliases:
  t:
  - towny:t $1-
```
Tell me if it fixes your issue.

**Comment by Managering** [comment]
Nope.

Command not found.

All was fine before updating to CHC Red. It worked with CHC Pro

**Comment by ElBananaa** [comment]
> Nope.
> 
> Command not found.
> 
> All was fine before updating to CHC Red. It worked with CHC Pro

What's is the /t for with towny?

**Comment by Managering** [comment]
It's an abbreviated command for /Town. /town works fine.

**Comment by ElBananaa** [comment]
> It's an abbreviated command for /Town. /town works fine.

I think you should take a look at this issue with Kangarko ^^

**Comment by Managering** [comment]
I'm here for that. Thanks for trying.

Do I wait for him now?

**Comment by kangarko** [comment]
I'm here, will have a look tomorrow soon :)

**Comment by kangarko** [comment]
1. Remove the "t" alias from Private_Messages.Tell_Aliases in settings.yml
2. Place the following command alias in commands.yml in your root server folder:

![a](https://i.imgur.com/PuNbrBh.png)

**Comment by MinecraftAdmin** [comment]
This breaks tab-completion functionality for the Towny `/t` command, which at many times requires elaborate player names, town names, flag settings and more to be typed in. 

I would appreciate a method of retaining tab-completion on the Towny `/t` command while using ChatControl red, aliases just don't cut it at the moment.

**Comment by kangarko** [comment]
I'm afraid that's not possible since we have to unregister that alias which breaks auto completion.

**Comment by m171717** [comment]
This is unacceptable. Most, if not all Towny players use `/t` as their primary command. You're making it harder on Towny server owners justify purchasing this plugin, as this is a **major** tradeoff.

**Comment by Managering** [comment]
We need a way to make chatcontrol not load in /t as a command, or set it on a very low priority...
We've been struggling with this ever since I reported it.

**Comment by kangarko** [comment]
I've added a workaround for this!

**Comment by MinecraftAdmin** [comment]
> I've added a workaround for this!

Legendary. Thank you, it works!
