### ISSUE TITLE
Players can't  execute two times the same command

### ISSUE THREAD

**Issue by DofyAdmin** [kangarko/ChatControl#329]
Hello,
I recently installed your plugin on my server for other reasons than "anti-commands spam or tchat spam" so in the configuration file I put "0" everywhere to desactivate the options but despite those modifications players can't execute a command two times even after 10s the error message still appears ! 
And so I had to uninstall your plugin because it wasn't possible to keep it on my server.

Server version: 1.12.2
Plugin version: Last released 

ps: sorry if there is some mistakes, I'm not english ^_^

**Comment by DofyAdmin** [comment]
I tried to add the permissions "chatcontrol.bypass.time.chat" and "chatcontrol.bypass.time.commands"
But it doesn't work.

**Comment by kangarko** [comment]
@DofyAdmin Hey and apology for late response.

May I see your settings.yml file?

**Comment by DofyAdmin** [comment]
[settings.zip](https://github.com/kangarko/ChatControl/files/3040949/settings.zip)
Here is the settings file

**Comment by DofyAdmin** [comment]
But it's very strange because even with the bypass permissions players received the warning messages : /

**Comment by DofyAdmin** [comment]
My players start to be very angry : ccc

**Comment by kangarko** [comment]
Hello,

you still have the Similar_Percentage_Block option enabled. Set it to 100 to disable.
