### ISSUE TITLE
Can't edit Chat file

### ISSUE THREAD

**Issue by MysticParadox** [kangarko/ChatControl#33]
Every time I try to edit the 'Chat.txt' file and then reload plugin, it chooses to make me have to delete & refresh the file.  I've tried using someone else's chat.txt file that works perfectly fine for them but it just doesn't want to work for me.

**Comment by kangarko** [comment]
Can you post the console output? (Shutdown the server, place the edited chat.txt in the rules folder and start the server again)

**Comment by MysticParadox** [comment]
http://pastebin.com/2GrTtmfJ
This is what I get each time.

**Comment by kangarko** [comment]
The error actually shouldn´t ever happen, because the plugin ignores lines with '#'. However, on certain encodings this is misread and might lead to issues. Try using Notepad++ and save the file in UTF-8 encoding, or as ANSI.

**Comment by MysticParadox** [comment]
So I changed it to ANSI and then saw a stray '#' with nothing after that
and it seems to work fine now.

**Comment by kangarko** [comment]
Closing as it is fixed.
