### ISSUE TITLE
Startup Message mistake

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#33]
Hey!

Just noticed you made a mistake in the link, it should be:

https://github.com/kangarko/ChatControl-Red/wiki (It doesn't work with the caps)

```12.11 15:05:27 [Server] INFO ____ _ _ ____ ___ ____ ____ _ _ ___ ____ ____ _
12.11 15:05:27 [Server] INFO | |__| |__| | | | | |\ | | |__/ | | |
12.11 15:05:27 [Server] INFO |___ | | | | | |___ |__| | \| | | \ |__| |___
12.11 15:05:27 [Server] INFO Tutorial:
12.11 15:05:27 [Server] INFO https://github.com/kangarko/ChatControl-Red/Wiki ```

**Comment by tjrgg** [comment]
Also, can the tutorial/help messages be disabled? I personally don't want to see it in my console every time I reload the plugin or startup the server and I don't see an obvious way to disable them.

**Comment by kangarko** [comment]
Thank you. I will add Silent_Startup option that will hide those.
