### ISSUE TITLE
[Suggestions]

### ISSUE THREAD

**Issue by EOT3000** [kangarko/ChatControl#330]
1. When checking commands, only check args, not command itself. One of my players wrote /f claim, and it got censored because I made it block f space c.
2. Add an api method "getCensored", which takes in a string, and returns the censored string.
3. If in rules, there is an "i", search for "1", "|" and "l", because that's how people bypass it (e.g, I want to block people saying testing, they say test1ng), o with "0", g with "9" and e with "3".
4. Before censoring, do rawstring.replaceAll(" ", ""); because that's another way to bypass it. If I want to block hello, people will write "h e l l o", and it will bypass.

**Comment by kangarko** [comment]
Hello,

ChatControl free is not taking in suggestions, sorry about that.

For the rules system, you can implement some of your ideas using the regular expressions language.

**Comment by EOT3000** [comment]
Ok, thanks for the reply though
