### ISSUE TITLE
Are there any pre-translated messages?

### ISSUE THREAD

**Issue by Spaex** [kangarko/ChatControl#330]
Hay,

are there already pre translated messages.yml? Because on the linked wiki page (settings.yml) it says there are but as I change the localization: en to localization: de for example they are not getting downloaded. Or don't they exist and I have to translate everything by myself?

Greetings Spaex

**Comment by ElBananaa** [comment]
> Hay,
> 
> are there already pre translated messages.yml? Because on the linked wiki page (settings.yml) it says there are but as I change the localization: en to localization: de for example they are not getting downloaded. Or don't they exist and I have to translate everything by myself?
> 
> Greetings Spaex

Hey! Actually, there's no official translation available (except the default one). However, Ik that some ppl are already working on translations (Including me for the french one, which is done at 99%). I don't know if anyone has done a deutsh/german translation tho.

**Comment by kangarko** [comment]
We currently don't have localization messages other than English but you are free to make your own ones and send to us :)
