### ISSUE TITLE
Problem with the command /msg in spamming, fastmessaging and caps

### ISSUE THREAD

**Issue by MdoubleM** [kangarko/ChatControl#331]
I have enabled the warning points sections and in the general chat works fine for the groups of spam, fastmessage, global, and swear. Also the anti-caps works fine. But then, when a player use the /msg command, it only works for the swear group that censor the words, but they are still able to write in caps, do spam and do fastmessaging. I have the CMI plugin in my server and I think that plugin controls the msg command but I don't know. There also some errors that appear in the console.

[error.log](https://github.com/kangarko/ChatControl-Red/files/5721989/error.log)

**Comment by MdoubleM** [comment]
I have this settings.

https://ufile.io/qof7cz52

**Comment by kangarko** [comment]
This is a problem with CMI, please contact their support team. Thank you and Merry Christmas :)
