### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by J-SHarper** [kangarko/ChatControl#332]
This plugin is incredible! Are there plans for it to support [Velocity](https://velocitypowered.com/)? The current bungee implementation does not work with Velocity.

**Comment by kangarko** [comment]
Thanks! Sure we're discussing about it, but right now our plans are to build our own marketplace so we don 't have the time for this in the near future. Sorry about that!

**Comment by james-d-elliott** [comment]
I'd love to see this as well. Seems like there are at least 8 people on GitHub who've asked for this feature. Maybe it could be on the Roadmap?

**Comment by kangarko** [comment]
Right now I am short on time but rest assured this will get done once I am available OR if there's a capable developer I can send him the source code of bungeecontrol.
