### ISSUE TITLE
Ad-bypass

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#333]
Minecraft Version: 1.8.9
MySQL: true
BungeeCord: false
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5723529/debug.zip)

People are able bypassing the filter by inserting a whitelisted domain inside the chat
![image](https://user-images.githubusercontent.com/3611852/102763505-0b531f00-437a-11eb-8768-05a4d3cfdc95.png)

**Comment by steveb05** [comment]
The message is not blocked since by default chatcontrol red does not have the extension .it in the rules. You can fix this by going to globa.rs and adding .it in the Domain/URL filter on line 26.

**Comment by kangarko** [comment]
Unfortunately that's a good catch we can't limit, because we rely on the regular expressions to catch the message. You can for now, remove these domains and create a custom command like /website X or /google X for them instead.
