### ISSUE TITLE
Hover Click Commands

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#337]
So I've formated my channels under list in the settings.yml to get my omeganames name color plugin to work like below because it wouldn't work in the channel ymls.

    global:
      Format: '&f[&9Global&f] &7{pl_prefix+}&f{omeganames_namecolour}{player_name}&b:{pl_suffix} &f{message}'

Now i need to find out how to add a hover click command to these channels, one for the prefix and one for the players name, how do i do that?

**Comment by kangarko** [comment]
Hey!

Instead of putting the format directly in the Format key, create your format in formats/ folder such as omeganames.yml and then type:

```
global:
  Format: omeganames
```

Instead. In that format file, you will be able to add the hover event, see other format files how it's done or you can check out our wiki.
