### ISSUE TITLE
Unicode Prohibited?

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#338]
Hi,

Please anyone explain why Unicode is set to prohibited, interested to know if there's a reason or is it just set that way as default.

Is there a way to un-prohibit chat?

I've looked through the Wiki but can't find anything in commands or permissions.

**Comment by OfT3N** [comment]
> Hi,
> 
> 
> 
> Please anyone explain why Unicode is set to prohibited, interested to know if there's a reason or is it just set that way as default.
> 
> 
> 
> Is there a way to un-prohibit chat?
> 
> 
> 
> I've looked through the Wiki but can't find anything in commands or permissions.

Hey there! Take a look at one of the first rules of your rules/chat.rs file - there you can remove the UTF restriction easily

**Comment by 00Hrtz** [comment]
> 
> 
> > Hi,
> > Please anyone explain why Unicode is set to prohibited, interested to know if there's a reason or is it just set that way as default.
> > Is there a way to un-prohibit chat?
> > I've looked through the Wiki but can't find anything in commands or permissions.
> 
> Hey there! Take a look at one of the first rules of your rules/chat.rs file - there you can remove the UTF restriction easily

thank you
