### ISSUE TITLE
[Issue] Incompatiblity with CMI?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#339]
CMI uses the [playerDisplayName] placeholder to show nicknames in their messages. It however fails to sometimes retrieve the nickname of a player. For me and other players as well (not everyone), it shows our minecraft name rather then nickname.

Related to https://github.com/Zrips/CMI/issues/4780

Minecraft 1.16.4, Bungee and MySQL.

**Comment by kangarko** [comment]
Asked Zrips directly, thanks.
