### ISSUE TITLE
1.16.4 MySQL | Help command not updated

### ISSUE THREAD

**Issue by memetrollsXD** [kangarko/ChatControl#34]
![image](https://user-images.githubusercontent.com/27217031/98962543-05f6ef00-2507-11eb-8236-a88b617cf49e.png)

This isn't too big of an issue, but the -bungee switch doesn't appear on the help tag, but it does on the autotab.

**Comment by kangarko** [comment]
Thanks, I will remove those auto-completions. We have removed this during development. If bungee is on, it will clear the network natively.
