### ISSUE TITLE
PlotSquared PlotChat (party chat) does not work.

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#341]
Minecraft Version: 1.12.2
MySQL: false
BungeeCord: false

When a player types into plot chat, noone can read what he types even though they stand on the same plot. Do I need to specify chat range perhaps?

**Comment by kangarko** [comment]
Can you please post me your channel from settings.yml keys?

**Comment by nikitushu2** [comment]
List:
    staffchat:
      Format: admin-chat
      Format_Spy: none
    publicchat:
      Format: global-chat
      Format_Spy: none
    plotchat:
      Format: chat
      Party: plotsquared-plot
      Format_Spy: none

When other player types and when I am (as an op) in the same plot, I can see their messages only through spy feature and I dont know how to turn the spy off. I added format_spy set to none, but spying continues. Non-op players do not have spying enabled somehow and they cant see what others are typing into plotchat.

**Comment by kangarko** [comment]
What plotsquare version are you using please? You can turn off spy with /spy off command.

**Comment by nikitushu2** [comment]
PlotSquared-Bukkit-3.815.jar

**Comment by kangarko** [comment]
Thanks, will have a look in a few days :)

**Comment by Malachiel87** [comment]
is working for me, use monitor priority on chatcontrol if is the same issue i think

**Comment by nikitushu2** [comment]
> 
> 
> is working for me, use monitor priority on chatcontrol if is the same issue i think

Setting priority to `MONITOR` did not fix the issue either. I noticed that when I, as an op, type into PlotChat, players can see what I type. But when non-op players type something, they do not see messages from each other. 

Maybe the issue is in permissions? My players have the following perms: `chatcontrol.channel.send.plotchat`, `chatcontrol.channel.leave.plotchat`, `chatcontrol.channel.leave.plotchat`, `chatcontrol.channel.join.plotchat.write` and `chatcontrol.channel.autojoin.plotchat.write`.

**Comment by ElBananaa** [comment]
> > is working for me, use monitor priority on chatcontrol if is the same issue i think
> 
> Setting priority to `MONITOR` did not fix the issue either. I noticed that when I, as an op, type into PlotChat, players can see what I type. But when non-op players type something, they do not see messages from each other.
> 
> Maybe the issue is in permissions? My players have the following perms: `chatcontrol.channel.send.plotchat`, `chatcontrol.channel.leave.plotchat`, `chatcontrol.channel.leave.plotchat`, `chatcontrol.channel.join.plotchat.write` and `chatcontrol.channel.autojoin.plotchat.write`.

Hey! Merry Christmas!
Could you try to give your players the following permission and tell us if it fixed your issue.

- chatcontrol.chat.read

If you are using LuckPerms, you could try to use their verbose function to see if any permission is missing.
It would also be great if you could provide your `/chc debug` file.

**Comment by nikitushu2** [comment]
> 
> 
> > > is working for me, use monitor priority on chatcontrol if is the same issue i think
> > 
> > 
> > Setting priority to `MONITOR` did not fix the issue either. I noticed that when I, as an op, type into PlotChat, players can see what I type. But when non-op players type something, they do not see messages from each other.
> > Maybe the issue is in permissions? My players have the following perms: `chatcontrol.channel.send.plotchat`, `chatcontrol.channel.leave.plotchat`, `chatcontrol.channel.leave.plotchat`, `chatcontrol.channel.join.plotchat.write` and `chatcontrol.channel.autojoin.plotchat.write`.
> 
> Hey! Merry Christmas!
> Could you try to give your players the following permission and tell us if it fixed your issue.
> 
>     * chatcontrol.chat.read
> 
> 
> If you are using LuckPerms, you could try to use their verbose function to see if any permission is missing.
> It would also be great if you could provide your `/chc debug` file.

Hey again, I added that perm but the issue persists. Non-op players can not see each other in the plotchat.

I sent the debug.zip file to  support@mineacademy.org with the message GITHUB PLOTSQUARED.

**Comment by ElBananaa** [comment]
> > > > is working for me, use monitor priority on chatcontrol if is the same issue i think
> > > 
> > > 
> > > Setting priority to `MONITOR` did not fix the issue either. I noticed that when I, as an op, type into PlotChat, players can see what I type. But when non-op players type something, they do not see messages from each other.
> > > Maybe the issue is in permissions? My players have the following perms: `chatcontrol.channel.send.plotchat`, `chatcontrol.channel.leave.plotchat`, `chatcontrol.channel.leave.plotchat`, `chatcontrol.channel.join.plotchat.write` and `chatcontrol.channel.autojoin.plotchat.write`.
> > 
> > 
> > Hey! Merry Christmas!
> > Could you try to give your players the following permission and tell us if it fixed your issue.
> > ```
> > * chatcontrol.chat.read
> > ```
> > 
> > 
> > If you are using LuckPerms, you could try to use their verbose function to see if any permission is missing.
> > It would also be great if you could provide your `/chc debug` file.
> 
> Hey again, I added that perm but the issue persists. Non-op players can not see each other in the plotchat.

Hey,

If you have luckperms, could you use `/lp verbose on chatcontrol`, then ask to a player who doesn't have the permission to type one message in the plotsquared chat.

Regarding the debug file, you can upload it here, any sensitive information is automatically removed from the file when you generate it.

Also, as I said, try to play arround with the formatter priority (don't forget to restart the server each time you change the priority), and let me know if it fixes the issue with a specific priority.

**Comment by nikitushu2** [comment]
Here are the verbose results: 
[https://ibb.co/XbmgWkY](https://ibb.co/XbmgWkY)
[https://ibb.co/bdppVYt](https://ibb.co/bdppVYt)
[https://ibb.co/xMbxH02](https://ibb.co/xMbxH02)

> 
> 
> > > > > is working for me, use monitor priority on chatcontrol if is the same issue i think
> > > > 
> > > > 
> > > > Setting priority to `MONITOR` did not fix the issue either. I noticed that when I, as an op, type into PlotChat, players can see what I type. But when non-op players type something, they do not see messages from each other.
> > > > Maybe the issue is in permissions? My players have the following perms: `chatcontrol.channel.send.plotchat`, `chatcontrol.channel.leave.plotchat`, `chatcontrol.channel.leave.plotchat`, `chatcontrol.channel.join.plotchat.write` and `chatcontrol.channel.autojoin.plotchat.write`.
> > > 
> > > 
> > > Hey! Merry Christmas!
> > > Could you try to give your players the following permission and tell us if it fixed your issue.
> > > ```
> > > * chatcontrol.chat.read
> > > ```
> > > 
> > > 
> > > If you are using LuckPerms, you could try to use their verbose function to see if any permission is missing.
> > > It would also be great if you could provide your `/chc debug` file.
> > 
> > 
> > Hey again, I added that perm but the issue persists. Non-op players can not see each other in the plotchat.
> 
> Hey,
> 
> If you have luckperms, could you use `/lp verbose on chatcontrol`, then ask to a player who doesn't have the permission to type one message in the plotsquared chat.
> 
> Regarding the debug file, you can upload it here, any sensitive information is automatically removed from the file when you generate it.
> 
> Also, as I said, try to play arround with the formatter priority (don't forget to restart the server each time you change the priority), and let me know if it fixes the issue with a specific priority.

**Comment by nikitushu2** [comment]
I can not find the button to upload a file here, and all the "share the zip file" services offer sharing only via email.

**Comment by nikitushu2** [comment]
I tried out all 6 priorities, none fixed the issue. Leaving it on MONITOR right now.

**Comment by ElBananaa** [comment]
> I can not find the button to upload a file here, and all the "share the zip file" services offer sharing only via email.

As said in the outpust message of `/chc debug`, use https://ufile.io/ to upload the zip file.

**Comment by nikitushu2** [comment]
> 
> 
> > I can not find the button to upload a file here, and all the "share the zip file" services offer sharing only via email.
> 
> As said in the outpust message of `/chc debug`, use https://ufile.io/ to upload the zip file.

[https://ufile.io/emt6qd2o](https://ufile.io/emt6qd2o)

**Comment by ElBananaa** [comment]
Alright, thanks!

So first of all, I can see that you're using a pretty old version of PlotSquared, it might be the reason.
Also, you're not using the latest version of chatcontrol-red. Your actual version is v10.1.8, but the v10.1.11 is out.
We need you to update your plugins (PlotSquared (to v3.821) and ChatControl-Red (to v10.1.11) in order to help you properly.

If it still doesn't work, since you have LuckPerms, use `/lp verbose on chatcontrol` and make sure that your players don't have any missing permissions.

**Comment by nikitushu2** [comment]
> 
> 
> Alright, thanks!
> 
> So first of all, I can see that you're using a pretty old version of PlotSquared, it might be the reason.
> Also, you're not using the latest version of chatcontrol-red. Your actual version is v10.1.8, but the v10.1.11 is out.
> We need you to update your plugins (PlotSquared (to v3.821) and ChatControl-Red (to v10.1.11) in order to help you properly.
> 
> If it still doesn't work, since you have LuckPerms, use `/lp verbose on chatcontrol` and make sure that your players don't have any missing permissions.

Where do I get  ChatControl-Red (v10.1.11)? I bought it on mcmarket but the link is unavailable there.

**Comment by ElBananaa** [comment]
> > Alright, thanks!
> > So first of all, I can see that you're using a pretty old version of PlotSquared, it might be the reason.
> > Also, you're not using the latest version of chatcontrol-red. Your actual version is v10.1.8, but the v10.1.11 is out.
> > We need you to update your plugins (PlotSquared (to v3.821) and ChatControl-Red (to v10.1.11) in order to help you properly.
> > If it still doesn't work, since you have LuckPerms, use `/lp verbose on chatcontrol` and make sure that your players don't have any missing permissions.
> 
> Where do I get ChatControl-Red (v10.1.11)? I bought it on mcmarket but the link is unavailable there.

You should be able to download it from McMarket: https://www.mc-market.org/resources/18217/
I just tried to download it, and I have no issues.

**Comment by nikitushu2** [comment]
> 
> 
> > > Alright, thanks!
> > > So first of all, I can see that you're using a pretty old version of PlotSquared, it might be the reason.
> > > Also, you're not using the latest version of chatcontrol-red. Your actual version is v10.1.8, but the v10.1.11 is out.
> > > We need you to update your plugins (PlotSquared (to v3.821) and ChatControl-Red (to v10.1.11) in order to help you properly.
> > > If it still doesn't work, since you have LuckPerms, use `/lp verbose on chatcontrol` and make sure that your players don't have any missing permissions.
> > 
> > 
> > Where do I get ChatControl-Red (v10.1.11)? I bought it on mcmarket but the link is unavailable there.
> 
> You should be able to download it from McMarket: https://www.mc-market.org/resources/18217/
> I just tried to download it, and I have no issues.

Thx, I downloaded it. I also updated the PlotSquared but the issue persists.

**Comment by ElBananaa** [comment]
> > > > Alright, thanks!
> > > > So first of all, I can see that you're using a pretty old version of PlotSquared, it might be the reason.
> > > > Also, you're not using the latest version of chatcontrol-red. Your actual version is v10.1.8, but the v10.1.11 is out.
> > > > We need you to update your plugins (PlotSquared (to v3.821) and ChatControl-Red (to v10.1.11) in order to help you properly.
> > > > If it still doesn't work, since you have LuckPerms, use `/lp verbose on chatcontrol` and make sure that your players don't have any missing permissions.
> > > 
> > > 
> > > Where do I get ChatControl-Red (v10.1.11)? I bought it on mcmarket but the link is unavailable there.
> > 
> > 
> > You should be able to download it from McMarket: https://www.mc-market.org/resources/18217/
> > I just tried to download it, and I have no issues.
> 
> Thx, I downloaded it. I also updated the PlotSquared but the issue persists.

Alright, then as I said, use `/lp verbose on chatcontrol`, then ask a player to write in the plot chat, and see if they don't have any missing permission.

If it still doesn't work, I guess it's related to you pretty old version of PlotSquared.
If so, you should wait for Kangarko, and see what he can do.

**Comment by nikitushu2** [comment]
Hey, my plugin got suddenly disabled. I cannot test the /lp verbose. I restarted the server and reinstalled the chatcontrolred jar file but when i type any command, it says that "Cannot use this command while the plugin is disabled."

**Comment by ElBananaa** [comment]
> Hey, my plugin got suddenly disabled. I cannot test the /lp verbose. I restarted the server and reinstalled the chatcontrolred jar file but when i type any command, it says that "Cannot use this command while the plugin is disabled."

Hey!

Could you send us your latest.log file please?

**Comment by nikitushu2** [comment]
> 
> 
> > Hey, my plugin got suddenly disabled. I cannot test the /lp verbose. I restarted the server and reinstalled the chatcontrolred jar file but when i type any command, it says that "Cannot use this command while the plugin is disabled."
> 
> Hey!
> 
> Could you send us your latest.log file please?

[https://ufile.io/ibha4he9](https://ufile.io/ibha4he9)

**Comment by Malachiel87** [comment]
i noticed the same stuff, it affect the 1.8.8 servers because death file contain newer stuff, just delete the file messages/death.rs and restart

**Comment by ElBananaa** [comment]
> i noticed the same stuff, it affect the 1.8.8 servers because death file contain newer stuff, just delete the file messages/death.rs and restart

Thanks for helping! I'll wait for his answer and see it it fixes his issue.

**Comment by nikitushu2** [comment]
Thanks, the plugin got enabled again.

Regarding the plotsquared issue, are we waiting for kangarko?

**Comment by nikitushu2** [comment]
> 
> 
> > i noticed the same stuff, it affect the 1.8.8 servers because death file contain newer stuff, just delete the file messages/death.rs and restart
> 
> Thanks for helping! I'll wait for his answer and see it it fixes his issue.

Hey, I just found out that while I'm on roads (not on plots), plot chat is still enabled (still not working). I.e even when I am not on plots, I am still kept in the plotchat. Does it mean that somehow plotchat from chatcontrol does not "stick" with the plots? Maybe that's the cause of my issue?

**Comment by Malachiel87** [comment]
btw how you used chatcontrol instead plot chat?

**Comment by nikitushu2** [comment]
> 
> 
> btw how you used chatcontrol instead plot chat?

I created a new channel and assigned it `Party: plotsquared-plot`. All the possible permissions were also given to the players.

**Comment by kangarko** [comment]
Hey, I've reviewed the code and since there's API changes from PlotSquared 3 to PlotSquared 5, for the time being we only support PlotSquared 5 the paid version. They support 1.12.2 though so it should work fine.

**Comment by nikitushu2** [comment]
> 
> 
> Hey, I've reviewed the code and since there's API changes from PlotSquared 3 to PlotSquared 5, for the time being we only support PlotSquared 5 the paid version. They support 1.12.2 though so it should work fine.

Spigot page says that the earliest version they support is 1.13. Do you have any information source of where it says that it supports 1.12? Because I'm afraid I might buy their plugin and waste my money due to incompatibility.

**Comment by ElBananaa** [comment]
> > Hey, I've reviewed the code and since there's API changes from PlotSquared 3 to PlotSquared 5, for the time being we only support PlotSquared 5 the paid version. They support 1.12.2 though so it should work fine.
> 
> Spigot page says that the earliest version they support is 1.13. Do you have any information source of where it says that it supports 1.12? Because I'm afraid I might buy their plugin and waste my money due to incompatibility.

Hey!

I believe this is either a mistake from kangarko, or a mistake from PlotSquared developper. As I can see on their page, the latest dev-build for plotsquare 1.12.2 is the v3.821.

**Comment by nikitushu2** [comment]
> 
> 
> > > Hey, I've reviewed the code and since there's API changes from PlotSquared 3 to PlotSquared 5, for the time being we only support PlotSquared 5 the paid version. They support 1.12.2 though so it should work fine.
> > 
> > 
> > Spigot page says that the earliest version they support is 1.13. Do you have any information source of where it says that it supports 1.12? Because I'm afraid I might buy their plugin and waste my money due to incompatibility.
> 
> Hey!
> 
> I believe this is either a mistake from kangarko, or a mistake from PlotSquared developper. As I can see on their page, the latest dev-build for plotsquare 1.12.2 is the v3.821.

Yeah, unfortunately they authors say (in spigot discussion page of plotsquared v5) that 1.12 is not compatible with plotscuared v5. and so does chatcontrolred's plotsquared party feature :(

**Comment by kangarko** [comment]
Damn that's bad, please email the last 1.12 compatible plotsquared to matej@mineacademy.org and I can try adding support for it.

**Comment by ElBananaa** [comment]
> Damn that's bad, please email the last 1.12 compatible plotsquared to [matej@mineacademy.org](mailto:matej@mineacademy.org) and I can try adding support for it.

@kangarko The latest compatible version for 1.12.2 is publicly available under this link: https://ci.athion.net/job/PlotSquared-v3/lastSuccessfulBuild/artifact/target/

**Comment by kangarko** [comment]
Thanks, will be added

**Comment by nikitushu2** [comment]
> 
> 
> Damn that's bad, please email the last 1.12 compatible plotsquared to [matej@mineacademy.org](mailto:matej@mineacademy.org) and I can try adding support for it.

I've sent the email. Thanks for engagement! Any approximate dates of when the support will be released?

**Comment by ElBananaa** [comment]
> > Damn that's bad, please email the last 1.12 compatible plotsquared to [matej@mineacademy.org](mailto:matej@mineacademy.org) and I can try adding support for it.
> 
> I've sent the email. Thanks for engagement! Any approximate dates of when the support will be released?

Hey! The latest version of the plugin that was just released on McMarket should now support PlotSquare v3.

**Comment by nikitushu2** [comment]
It works! Thanks
