### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#342]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

After a day of installing and setting up ChatControlRed, my Server unexpectedly crashed upon logging in this morning. I got this warn and then the the Server kicked me, I checked my Console and this warn was spamming https://paste.helpch.at/eteyaziyax.css

So i stopped my Server, then tried to restart the Server and got this https://paste.helpch.at/ezikinaqet.cs

So i accessed my Server using FileZilla and noticed that every single file on my Server has .gz on the end of their file names.

Server will not start up.

I hadn't installed any other plugin that uses sql since like 5 months ago at least.

I've contacted my Host to try to fix this issue.

The last thing i did before logging off last night was un-deny unicode.

**Comment by 00Hrtz** [comment]
Was my Hosts fault, they just admitted it. Nothing to see here, not caused by ChatControlRed.

**Comment by kangarko** [comment]
Thanks for letting me know, got scared a bit haha!

**Comment by 00Hrtz** [comment]
Yes sorry, as your plugin was just installed it was one suspect but i found out what the cause was in the end.

.gz is Gzip compression format which Hosts use to move your server files from one Server to another, my host said it was their mistake, case closed. If anyone else has this issue it's their Host.

**Comment by ElBananaa** [comment]
> Yes sorry, as your plugin was just installed it was one suspect but i found out what the cause was in the end.
> 
> .gz is Gzip compression format which Hosts use to move your server files from one Server to another, my host said it was their mistake, case closed. If anyone else has this issue it's their Host.

Hey! Thanks for letting us know about it.
