### ISSUE TITLE
[Issue] Please move before you type

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#344]
Players often have the issue where ChatControl once again asks the player to move before they can type. This happens randomly and not only when you login on the server.

Minecraft 1.16.4, Bungee and MySQL.

**Comment by 00Hrtz** [comment]
I'm non Bungee, doesn't do it for us so likely a Bungee related issue, is that when they're switching servers or even when on the same server and not switching.

**Comment by Sikatsu** [comment]
Even when on the same server and not switching, might be a bungee issue. Only heard a couple of players experiencing this.

**Comment by kangarko** [comment]
Thanks, likely caused when player moves to his login location. Will fix.
