### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Rexmen1** [kangarko/ChatControl#345]
Chat control red:- Can u make it so we can add space for announcement messages... I want to put messages in the center and using <center> does nothing so was trying to do &7     Test for 4 extra spaces but that doesn't work either...

https://gyazo.com/ca6e158f017423a739fef4b8997885e5

**Comment by kangarko** [comment]
You can add spaces with "&r &r &r &r &r &r"

**Comment by Rexmen1** [comment]
But that doesn't really help oh well... 
https://gyazo.com/08e07b8fc9fd06910ac6b2cfa1ddd027
https://gyazo.com/ebd503f72895673979f369055488d9f9
With that many characters, we can't do a good announcement message...

**Comment by Rexmen1** [comment]
and where do even use < center> it doesn't work with /chc announce
it doesn't work with timed commands either

https://gyazo.com/280608c53846eda0fe1b0037b8869dc9
https://gyazo.com/53114265e26108a69d681e27860b56a3

**Comment by kangarko** [comment]
I understand, I am very sorry that this is frustrating however Minecraft doesn't let us use more than one space in the chat, which affects the announcement command.

Regarding the < center> issue, I will fix that today!

**Comment by Rexmen1** [comment]
it works fine with many other plugins...
CMI allows adding as many spaces but it's fine.... Not a huge issue I guess...

**Comment by Rexmen1** [comment]
OK thanks...
