### ISSUE TITLE
Deathmessages - item asterisk differentiation doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl#347]
The variable `require killer item *_SWORD` from the default config simply triggers all items and does not differentiate against swords. If it is at the top it will be triggered no matter which item is used to kill. The same is true for all constructs of this kind, like `require killer item *_AXE`.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5731630/debug.zip)
ChatControlRed version 10.1.9
Tuinity-"8056d13" (MC: 1.16.4)

**Comment by kangarko** [comment]
Thanks, solved.
