### ISSUE TITLE
Question: Tablist

### ISSUE THREAD

**Issue by Spaex** [kangarko/ChatControl#348]
ChatControl Red replaced EssentialsChat and many other plugins for me and so far I love the opportunities this plugins gives but there's one thing I'm missing or simply don't find.

Is it already possible to also format the Tablist name of the user? Like in EssentialsChat so I have for example "&4Admin: Max: " in Chat and "&4Admin: Max" on the tablist?

**Comment by kangarko** [comment]
Awesomely, Merry Christmas and I've added this feature to the next release! Drop a 5* <3 if you enjoy this:)
