### ISSUE TITLE
Unknown character in private messages

### ISSUE THREAD

**Issue by ImSapphire** [kangarko/ChatControl#349]
Whenever I send or receive a message, there are 3 weird characters before everything else. I can't find any way to change the message displayed here.
![image](https://user-images.githubusercontent.com/48931512/102945012-25782480-4482-11eb-9f5c-8a3ed65a5104.png)
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

Steps to reproduce:
1. Use /pm, /tell, /msg or any other aliases to message someone.
2. Observe output.

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues#my-emoticons--are-just-showing-as---unicodes--special-characters-not-working
