### ISSUE TITLE
Problem with custom color in chat.

### ISSUE THREAD

**Issue by Kielczi** [kangarko/ChatControl#350]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

Hi!

I don't know why, but when i try using different color like #792aad(/chc color #792aad), only first word has this color, the rest of the sentence is white.
![color](https://user-images.githubusercontent.com/38833122/102949633-08b30f80-44c9-11eb-8443-6e1cfbd23008.PNG)

Debug: https://ufile.io/ys0hw248

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: false
> BungeeCord: false
> 
> Hi!
> 
> I don't know why, but when i try using different color like #792aad(/chc color #792aad), only first word has this color, the rest of the sentence is white.
> ![color](https://user-images.githubusercontent.com/38833122/102949633-08b30f80-44c9-11eb-8443-6e1cfbd23008.PNG)
> 
> Debug: https://ufile.io/ys0hw248

Hey! Your ProtocolLib version is outdated, update to the v4.6.0-Snapshot and try again (You can download it here: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)

**Comment by Kielczi** [comment]
Nah, today i found that this plugin https://www.spigotmc.org/resources/interactivechat-supports-bungeecord-custom-keywords-items-inventories-in-chat-rgb-fonts.75870/ doing this. I know that chc red has some "interactive-chat" features, but i downloaded this only for showing inventory on discord using [inv]. I tried to find an option in config to stop doing this but there isn't. Weird beacuse normal minecraft colors like gold/purple/aqua work well only hexadecimal colors do not work correctly.

**Comment by kangarko** [comment]
Sorry but that plugin is incompatible.
