### ISSUE TITLE
/channel ? kicks when executed

### ISSUE THREAD

**Issue by Managering** [kangarko/ChatControl#351]
Hi,

Using /channel ? Kicks players off of the server when using the command.

That's all.

Please have a look at it :)

**Comment by kangarko** [comment]
<img width="671" alt="Screenshot 2020-12-23 at 15 04 02" src="https://user-images.githubusercontent.com/1918426/103002927-1a7bcd80-4530-11eb-9d7e-f7a2693b6787.png">
It works for me. Please follow the issue template (READ ME) and open a new ticket.
