### ISSUE TITLE
Customization for help on /channel and /spy 

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#353]
It would be nice if the help menu (this: https://prnt.sc/w8i45e) not the /chc help menu gets customizable. Customizing the header etc. To make it fits to my servers design.

**Comment by kangarko** [comment]
<img width="1145" alt="Screenshot 2020-12-23 at 15 12 48" src="https://user-images.githubusercontent.com/1918426/103003588-54999f00-4531-11eb-9cc4-269a31d620fc.png">
Thanks! RIght now the code makes is super difficult but I took a note for the future.

**Comment by DevJoey** [comment]
Thank you. it would be nice if you simple make a multi line message, which gets sendet. make an option. optional-help: true and then i can define an own help by simple multi line messages. here i have written an example https://pastebin.com/61B4f3BX

you can simple leave your current help system as it is. you can simple implement a option so i can write my own help which gets printed instead of the normal help.

The /chc help must not be customizable, because it is only visible to admins but for /tag /spy /channel and all other helps for subcommands which can be seen by an user would a own help option verry useful and will make the plugin 100% customizable for any servers needs.
