### ISSUE TITLE
Customizing /tag list 

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#354]
It would be nice, if more would get customizable. Here the tag list output. i would customize that more. https://prnt.sc/w8iegq

Example;

tag-list-output:
- '[Servername] You have the folowing tags:'
- 'Prefix is set to %prefix_tag%'
- 'Nick is set to %nick_tag%' 
A multiline message would be nice please see this example i written because i cannot use yaml syntax in github: https://pastebin.com/9pkwLefG

With this format, serverowners can easy customize it to everything they need. Because of the multiline i can easy add/remove lines and edit a line as my wish. with the currently implemented system, i can not make chc fits my server.

**Comment by kangarko** [comment]
Thanks for your suggestion! As with these things, we build this on the fly so it's a bit tricky to get customized, but I can have a look when I have more time 👍

**Comment by DevJoey** [comment]
Yea with the build on the fly it is a simple solution. leave your current system and add an optional-help: true option so i can define my own help message instead of the original one with simple multi lines. is 20 lines of code. simple check for the option and if this is enabled simple send my own defined message

**Comment by kangarko** [comment]
<img width="627" alt="Screenshot 2020-12-24 at 08 37 32" src="https://user-images.githubusercontent.com/1918426/103071142-498f4f00-45c3-11eb-84c4-f26aa37225e6.png">
It's not so simple, as I mentioned I'll have a look in the future
