### ISSUE TITLE
Color menu not working

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#355]
Iam using an 1.16 server and have OP and can click on any color in the menu. it dont do anything. No errors in console, it simple does nothing

**Comment by ElBananaa** [comment]
Hey! It works fine for me. Could you please provide your debug file using `/chc debug`?

**Comment by DevJoey** [comment]
Yea https://ufile.io/xx7ctdzz

**Comment by 00Hrtz** [comment]
not saying anything in chat when you click a color?

**Comment by ElBananaa** [comment]
> Yea https://ufile.io/xx7ctdzz

Alright, your settings file looks fine to me. try replacing your formats/chat.yml with this https://hastebin.com/wefutasosa.yaml and tell me if it fixes your issue.

**Comment by DevJoey** [comment]
No it dont work. the menu does not even give me any feedback. no enchanted items nothing. normally if i click the item will be get an enchant.

**Comment by kangarko** [comment]
This must be another plugin then, try testing on a local server on your computer without any other plugins. Lemme know below if still having issues after that 👍

**Comment by DevJoey** [comment]
it is an issue with another plugin. i think another plugin is cancelling the event on a lower priority. i have found out, that you ignore the evnt if it is cancelled. so, please remove the if(event.isCanncelled()) return; or the EventHandler ignore canncelled annotation.

**Comment by DevJoey** [comment]
I have only self made plugins on my server except of CHC also i have fixed this issue by my self by fixing the events priority. but to prevent other plugins failure you can remove the ignore cancelled if you want.

**Comment by kangarko** [comment]
I am not going to listen and process canceled events, this is potentially dangerous and can lead to other problems. You have to fix your plugin.
