### ISSUE TITLE
msg not showing from discord to game

### ISSUE THREAD

**Issue by Rexmen1** [kangarko/ChatControl#356]
[ChatControlRed] Received Discord message to non-linked ChatControl channel '💬-survival-chat' id 726122767187050557, Message: test

Messages are not showing from discord to game
but shows from game to discord

**Comment by kangarko** [comment]
Have you followed our Discord wiki guide? You need to link the channel, remove all emojis and use plain text "survival-chat" only as per the guide.

**Comment by Rexmen1** [comment]
Sorry to tell you to think but Red is not good compared to Pro with all these new limitations not really any good features... 
I think I'm gonna go back to old chatcontrol... If there gonna be limits for things which is not added yet.. Like its doable that emoji can work with old pluign but not new...

Thank you for your time... <3

**Comment by kangarko** [comment]
What limitations exactly? Emojis work fine as long as you use the proper encoding, this is also outlined in our wiki...

**Comment by Rexmen1** [comment]
Before with old chatcontrol i can use the discord chat without enabling the channels but I guess the plugin is changed and can't use other features without using the channels....

**Comment by ElBananaa** [comment]
> Before with old chatcontrol i can use the discord chat without enabling the channels but I guess the plugin is changed and can't use other features without using the channels....

Hey!
Actually, with the new version, you need to enable the channels in order to make everything work perfectly.
However, it doesn't really change anything except the fact that you need to have at least one channel if you enable this feature.

**Comment by kangarko** [comment]
I will make some corrections so that Discord is not modified when channels are not enabled. I will also add a specific option to disable Discord integration.

**Comment by Rexmen1** [comment]
Ok great ur awesome... THANKKSSSSSSSSSSSSSS
