### ISSUE TITLE
Suggestion : log files per day

### ISSUE THREAD

**Issue by dartasen** [kangarko/ChatControl#36]
It would be cool to separate log files per day rather than one large file.

**Comment by EvilOlaf** [comment]
+1 for logrotate ^^

**Comment by Steev93** [comment]
+ Following

**Comment by rErEaT** [comment]
+1, would be nice

**Comment by DeusNinja** [comment]
If this is added as an improvement, could it please be an optional thing? Such as being able to set it to split between day, week, month, year, or not at all? I quite enjoy being able to search my entire chat log from the beginning of time using less -R on my linux OS. Where as if they were daily files, I'd have to run a grep search through all of my log files then pipeline them into my less command..

**Comment by kangarko** [comment]
Of course, I would let the users to decide whether they want to split files at all, if so, how frequently.

**Comment by kangarko** [comment]
Addressed at https://github.com/kangarko/ChatControl-Pro/issues/64
