### ISSUE TITLE
[Issue] Language line became white

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#360]
The line ''Your chat color set to'' used to be gray, it's now white on the last release.

![image](https://user-images.githubusercontent.com/5664135/103037873-30f44a00-456d-11eb-964b-57ec89c3d8c8.png)

When I add &7 in front of the {0}, it makes the first letter lose a capital. It will say ''je'' rather then ''Je''

Minecraft 1.16.4, Bungee and MySQL.

**Comment by kangarko** [comment]
What key in localization is this please?

**Comment by Sikatsu** [comment]
All the keys with "{0) color set to" "{0} decoration set to", I can check the language file in a few hours if the key is needed ^^

**Comment by kangarko** [comment]
Will fix in 1-2 days :)

**Comment by kangarko** [comment]
Just pushed a new update, got to go right now haha!

**Comment by Sikatsu** [comment]
No worries, not a high priority! The key is Color.Succes_Color, not sure right now if all of them that start with {} are affected

**Comment by ElBananaa** [comment]
Hey! I just tried on my own server, and the text shown before the color is grey. But, I noticed that when I use the default color list (like `/chc color dark_aqua`, `/chc color gold`), the text is completely grey, the color isn't applied to its name.
So basically, this is how it looks in my chat
![image](https://user-images.githubusercontent.com/53318613/103099616-82edac00-460f-11eb-98e9-4f04d0fa158c.png)

**Comment by Sikatsu** [comment]
Hmm, in my case I removed the success symbol, might be related?

**Comment by ElBananaa** [comment]
I have no idea tbho. You could give it a try ;)

**Comment by kangarko** [comment]
Oh I found it. It's intentional. We build the message on the fly, assuming no color will be used. I apology. Cannot simply add a workaround since they it's gonna be putting " and " between these messages...

**Comment by Sikatsu** [comment]
I understand, but you can also not fix it that if I add &7 in front of the {0} it will still have a capital letter?

**Comment by kangarko** [comment]
We effectively split the first letter and make it capitalized so putting &7 will try to capitalize & and break it.
