### ISSUE TITLE
[Issue] Hover in /chc help looks broken

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#362]
![image](https://user-images.githubusercontent.com/5664135/103038741-816ca700-456f-11eb-99da-a9433da47d15.png)

Picture explains enough I think haha. Happens on all hovers in the plugin.

Minecraft 1.16.4, Bungee and MySQL.

**Comment by kangarko** [comment]
Oh

**Comment by Sikatsu** [comment]
I noticed this part in the hover having some color issues I think:

![image](https://user-images.githubusercontent.com/5664135/103086891-21fdae00-45e6-11eb-9491-bcb1e2200e55.png)

![image](https://user-images.githubusercontent.com/5664135/103086921-3cd02280-45e6-11eb-9052-52167def5ff0.png)

**Comment by Sikatsu** [comment]
After Usage the command seems to miss in this hover:
![image](https://user-images.githubusercontent.com/5664135/103087018-86207200-45e6-11eb-83ee-15e401c469bb.png)

**Comment by kangarko** [comment]
Thanks! Will fix the two issues above, the last I am still investigating, not a big deal
