### ISSUE TITLE
Discord using discord usernames instead of nicknames

### ISSUE THREAD

**Issue by altruiis** [kangarko/ChatControl#363]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

When using discord for a channel, the message in minecraft shows as their actual discord username, instead of whatever nickname they have set in the discord server. Instead, there should be an option to use their nickname on discord. I know this is an option on DiscordSRV by default, but using chatcontrol it forces their regular discord username. Thanks!

**Comment by kangarko** [comment]
Thanks, will be added!

**Comment by JPlayer3** [comment]
I also got a new Red setting and got here.

Regarding messages to Discord, the Pro specifications or the way messages are displayed was very attractive.

The Red message isn't bad, but it doesn't look good.

Technically you should be able to edit even a webhock message.

Or I want you to be able to use the webhock specifications in the settings.
