### ISSUE TITLE
Timed message don't work with this setup

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#365]
Minecraft Version: 1.16.3
MySQL: true
BungeeCord: true
With this setup and plotsquared world the timed messages don't work, any idea why? i using monitor priority and plotsquared  (is the only difference of other servers where timed message work fine)
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5738974/debug.zip)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.3
> MySQL: true
> BungeeCord: true
> With this setup and plotsquared world the timed messages don't work, any idea why? i using monitor priority and plotsquared (is the only difference of other servers where timed message work fine)
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5738974/debug.zip)

Hey! Merry christmas! Could you please update to the latest version of the plugin and let us know if it fixes your issue.

**Comment by Malachiel87** [comment]
nope broadcast don't work

**Comment by ElBananaa** [comment]
Hey! Could you try to play arround with the different Chat_Listener_Priority (you need to restart the server each time you change the priority), and let me know if it works with a specific priority. As said here: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities, using a different priority for plugins like PlotSquared could fix your issue.

**Comment by james090500** [comment]
I dont think it's a plotsquared issue because I have the same problem. I can't get timed messages to send at all, but I can get them to send to discord.
[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/5744673/debug.1.zip)

**Comment by kangarko** [comment]
Does it work without PlotSquared installed? I've copy pasted your debug @Malachiel87 and it works just fine, the only thing I did was to set "delay" to "1 second" in timed.rs as well as settings.yml to test it faster. You can try lowering the delay to the same to see if messages start popping out.

<img width="640" alt="Screenshot 2020-12-30 at 12 23 11" src="https://user-images.githubusercontent.com/1918426/103348270-cc1f7f00-4a99-11eb-80ed-1f8fed1bff6f.png">

Please try doing the same @james090500 
<img width="504" alt="Screenshot 2020-12-30 at 12 24 40" src="https://user-images.githubusercontent.com/1918426/103348380-1d2f7300-4a9a-11eb-9e09-33a6798f031a.png">

**Comment by Malachiel87** [comment]
Yeah only with plotsquared don't work

Il mer 30 dic 2020, 12:25 Matej Pacan <notifications@github.com> ha scritto:

**Comment by kangarko** [comment]
Please ask PlotSquare developers about it, it doesn't look like something we can control on our end. Apology I was not able to help.

**Comment by james090500** [comment]
I'm going to have to re-open this as i dont use plot squared but still have the problem sadly.

**Comment by ElBananaa** [comment]
> I'm going to have to re-open this as i dont use plot squared but still have the problem sadly.

Hey!

Please open a new issue instead. It looks like both issue are related in some ways, but since they can be both caused by different reasons, I think it's better to separate them.

**Comment by james090500** [comment]
Will get it all sorted tomorrow!

**Comment by Malachiel87** [comment]
i noticed at hub if if i write something using /say, i can't see any message come out if chatcontrolred is installed, on console it work
