### ISSUE TITLE
1.16.4: Error.log

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#366]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

My error log keeps filling up and is already around 8mb in a few days. Not sure what the error means, as everything seems to work in-game?

[error.log](https://github.com/kangarko/ChatControl-Red/files/5739488/error.log)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true
> 
> My error log keeps filling up and is already around 8mb in a few days. Not sure what the error means, as everything seems to work in-game?
> 
> [error.log](https://github.com/kangarko/ChatControl-Red/files/5739488/error.log)

Hey! Merry christmas! It looks like this is related to #231.
Please update to the latest version of ChatControl-Red then, as said there, try to play with the chat formatter priority.
Make sure to remove the error.log file before.

**Comment by Sikatsu** [comment]
Hmm I did play with the chat formatter without success, I am also on the latest release that was released today (.11)

Merry christmas to you too! <3

**Comment by ElBananaa** [comment]
> Hmm I did play with the chat formatter without success, I am also on the latest release that was released today (.11)
> 
> Merry christmas to you too! <3

Thanks! Could you please remove the error.log file, then wait a bit, and upload the debug.zip file when the error log is generated?

**Comment by kangarko** [comment]
Thanks, should be silenced to the next version
