### ISSUE TITLE
Updating default comments inside the settings file

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#368]
1. That's the default file, so it will be useful for any new users.

2. It won't affect my server since I'm aware of this, but once again, new users can be easily confused.

I also noticed, while I was looking into the default lang file, that even with the latest version, you didn't replace the update url.

```
# -------------------------------------------------------------------------------------------------
# Messages related to updating the plugin
# -------------------------------------------------------------------------------------------------
Update:  
  Available:
    - '&2A new version of &3ChatControl&2 is available.'
    - '&2Current version: &f{current}&2; New version: &f{new}'
    - '&2URL: &7https://spigotmc.org/resources/{resource_id}/'
```

And I guess that you didn't change the plugin update notification system to work with mcmarket, so it would be cool to make it compatible too.

**Comment by kangarko** [comment]
Thanks, I removed that key for now.
