### ISSUE TITLE
1.16.4 msg broken Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#369]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

/msg is still broken, it seems common in /reply most of all but it just makes the wrong player send the message
![image](https://user-images.githubusercontent.com/29175381/103104845-a9b4de00-4621-11eb-9c97-ef14fab23743.png)
![image](https://user-images.githubusercontent.com/29175381/103104846-acafce80-4621-11eb-88ba-c1f34bf70256.png)

he had to do /r twice for it to send properly as him

**Comment by ElBananaa** [comment]
Hey! Merry christmas!
Thanks. Since this is related to #222 I'll close this issue and quote it there.
