### ISSUE TITLE
1.16.4 | Wrong quit/join message

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#37]
Hey!

# **Environment**
### **ChatControl-Red Version**: ChatControl-Red-10.0.2b

Alright, as said on this post https://github.com/kangarko/ChatControl-Red/issues/22 if I still have the issue listed below, I should open a ticket, so there I am. The problem is that my friend (MRTYGER) joined the server, and here's the message shown 
![image](https://user-images.githubusercontent.com/53318613/98970480-460e9f80-2510-11eb-959f-20074e89e816.png)

It shows my name. If I disconnects, he sees his name. I didn't change anything in the formatting options.

**Comment by kangarko** [comment]
Thank you so much for your patience and actually testing and reposting this. I will fix that right now.
