### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by Yive** [kangarko/ChatControl#37]
![bug 1](http://i.yive.me/0DK1w59)
![bug 2](http://i.yive.me/cGY5jv0)
Is there a way to fix this?

config:
http://i.yive.me/Pqe8rn4

**Comment by kangarko** [comment]
@Yive is the bug still present, or can I close this issue? The thing is that much of the plugin has changed in 5.x so the possibility that it was fixed is high

**Comment by Yive** [comment]
@kangarko I'm not sure since I quit minecraft.

**Comment by kangarko** [comment]
Oh, ok then I am closing this issue, feel free to create a new if any issues occur in case you use the plugin again.
