### ISSUE TITLE
1.16.4:  MySQL db error on updating from 10.1.9 --> 10.1.10/10.1.11

### ISSUE THREAD

**Issue by CypherPhyre** [kangarko/ChatControl#370]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

ChatControlRed disables on boot due to MySQL db error. There is no error when MySQL.enabled is false only when it is set to true. There is no issue in 10.1.9

[error.log](https://github.com/kangarko/ChatControl-Red/files/5740424/error.log)

**Comment by ElBananaa** [comment]
Hey! Merry Christmas!
Thanks for reaching us.

Could you make sure the following tables were created in the database:
- ChatControl
- ChatControl_Log
- ChatControl_Mail.

If so, simply run these commands: 
- `ALTER TABLE ChatControl CONVERT TO CHARACTER SET utf8mb4_unicode_ci;`
- `ALTER TABLE ChatControl_Log CONVERT TO CHARACTER SET utf8mb4_unicode_ci;`
- `ALTER TABLE ChatControl_Mail CONVERT TO CHARACTER SET utf8mb4_unicode_ci;`

Let me know if it fixed the issue.

**Comment by CypherPhyre** [comment]
I have tested with those tables and got the same error.
I removed the tables and now they will not auto create on boot. Same error.

The plugin is trying to create the tables as utf8mb4_unicode_520_ci.
That set is not an option for my db.

Reverting back to 10.1.9 works fine.

**Comment by ElBananaa** [comment]
> I have tested with those tables and got the same error.
> I removed the tables and now they will not auto create on boot. Same error.
> 
> The plugin is trying to create the tables as utf8mb4_unicode_520_ci.
> That set is not an option for my db.
> 
> Reverting back to 10.1.9 works fine.

That's pretty weird.
If changing the encoding to utf8mb4_unicode_ci didn't work, and/or if the tables aren't generated, try to create the 3 tables manually using utf8 (or change the encoding to utf8).

Simply remove the error.log file, then try to create the tables/change their encoding to utf8, and then, if it doesn't fix the issue, send us your `/chc debug` file.

**Comment by CypherPhyre** [comment]
Debug file: https://ufile.io/mdeepdba
Error Log: [error.log](https://github.com/kangarko/ChatControl-Red/files/5740656/error.log)

The tables will not auto-create in 10.1.11 due to forcing utf8mb4_unicode_520_ci which is not an option for my db.
Reverting to 10.1.9: Tables create as utf8_unicode_ci.
Manually editing to utf8mb4_unicode_ci still gives an error on reboot due to the wrong table.

**Comment by ElBananaa** [comment]
Alright. I marked this issue as high priority. Kangarko will probably have a look soon. However, it could take a few days for you to get an answer. If the previous version works fine, you should consider using it until then.

**Comment by kangarko** [comment]
You need to update your MySQL provider driver. We switched to support unicode using 4 bits length because the previous system only supported 3 bits.

Some characters such as smiley or Chinese are stored in 4 bits so they would crash the 3-bit database leading to more problems. Most hosting providers have now widely adopted the utf8mb4_unicode_520_ci encoding.
