### ISSUE TITLE
Option to completely disable discord touching

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#371]
Add a option to have the plugin completely not touch anything discordsrv related. Its such garbage way of handeling this atm.

**Comment by ElBananaa** [comment]
Hey! Merry Christmas!
Could you please give more details.
Also, please follow the actual suggestion format.

**Comment by ghost** [comment]
Currently when trying to setup the discord hook, it doesnt allow you to see messages from discord in game. Even with nothing configured in the settings.yml.

Simply put i purely want to use chatcontrol for easy moderation, i dont need to format anything.

**Comment by ElBananaa** [comment]
If I'm not wrong, you should be able to see both messages from the game on discord, and messages from discord ingame.
Make sure you followed the [steps listed on the wiki](https://github.com/kangarko/ChatControl-Red/wiki/Discord) to setup the discord chat relay correcly.

I'm pretty sure that Kangarko would've loved to make the plugin installation as easy as "drop the plugin in your plugin folder, and you're ready to go", but this is sadly impossible. The plugin has too many features to be as simple.

**Comment by broken1arrow** [comment]
> Currently when trying to setup the discord hook, it doesnt allow you to see messages from discord in game. Even with nothing configured in the settings.yml.
> 
> Simply put i purely want to use chatcontrol for easy moderation, i dont need to format anything.

Yep, can be other errors, as it can takes all channels and sends to discord.

If you need help setting it up, in that case tell what is hard too fix, otherwise type with global in discord config.yml (so it should take from global chat / normal chat). but there is some risk it can also bring your other channels with (have not tested this in red).

**Comment by ElBananaa** [comment]
> > Currently when trying to setup the discord hook, it doesnt allow you to see messages from discord in game. Even with nothing configured in the settings.yml.
> > Simply put i purely want to use chatcontrol for easy moderation, i dont need to format anything.
> 
> Yep, can be other errors, as it can takes all channels and sends to discord.
> 
> If you need help setting it up, in that case tell what is hard too fix, otherwise type with global in discord config.yml (so it should take from global chat / normal chat). but there is some risk it can also bring your other channels with (have not tested this in red).

That's pretty weird. Could you please provide your `/chc debug` file? I'll investigate the issue.

**Comment by broken1arrow** [comment]
> > > Currently when trying to setup the discord hook, it doesnt allow you to see messages from discord in game. Even with nothing configured in the settings.yml.
> > > Simply put i purely want to use chatcontrol for easy moderation, i dont need to format anything.
> > 
> > 
> > Yep, can be other errors, as it can takes all channels and sends to discord.
> > If you need help setting it up, in that case tell what is hard too fix, otherwise type with global in discord config.yml (so it should take from global chat / normal chat). but there is some risk it can also bring your other channels with (have not tested this in red).
> 
> That's pretty weird. Could you please provide your `/chc debug` file? I'll investigate the issue.

Test this in cc 8.8, new function in discordsrv, where you can put it on global (in case you do not have a chat plugin or one that does not support discordsrv).

But do not know how well it would work in red (so nothing I would recommend, but if TS wants a quick fix this is a solution).

**Comment by kangarko** [comment]
Thanks, will add this option to the next version.
