### ISSUE TITLE
1.16.4 | chc remove some symbols if you not use English. 

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#372]
If you typ "hej hur är det :)" when chc see ":)" it apply a emoji/Smileys (for it match a rule) and players see this "hej hur ar det :)" use Linux and it has support for this language (no issue with other plugins if they use åäö and it store it correctly in database).

And this is for every time the plugin shall change any thing in a text, because of player use some words some match a rule i have set. Only one placeholder some do it correctly is {original_message} . 

See if it can be solved or try to get around it.

CHC version: 10.01.11 (has bee like this from the beginning)
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

one example

`25.12 14:17:53 [Server] INFO Bigkaninen issued server command: /g hej på dig
25.12 14:17:53 [Server] INFO [ChatControlRed 10.1.11] Command /channel send mc-globalt hej pa dig took 8.56 ms`

**Comment by ElBananaa** [comment]
> If you typ "hej hur är det :)" when chc see ":)" it apply a emoji/Smileys (for it match a rule) and players see this "hej hur ar det :)" use Linux and it has support for this language (no issue with other plugins if they use åäö and it store it correctly in database).
> 
> And this is for every time the plugin shall change any thing in a text, because of player use some words some match a rule i have set. Only one placeholder some do it correctly is {original_message} .
> 
> See if it can be solved or try to get around it.
> 
> CHC version: 10.01.11 (has bee like this from the beginning)
> Minecraft Version: 1.16.4
> MySQL: false
> BungeeCord: false
> 
> one example
> 
> `25.12 14:17:53 [Server] INFO Bigkaninen issued server command: /g hej på dig 25.12 14:17:53 [Server] INFO [ChatControlRed 10.1.11] Command /channel send mc-globalt hej pa dig took 8.56 ms`

Hey! Merry Christmas! I don't really understand everything. For the first part, Kangarko is aware that there's some issues under windows with some characters, but for now, this isn't a priority. But what's the other problem? Could you please provide your `/chc debug` file, screenshots and/or vidéos?

**Comment by broken1arrow** [comment]
> > If you typ "hej hur är det :)" when chc see ":)" it apply a emoji/Smileys (for it match a rule) and players see this "hej hur ar det :)" use Linux and it has support for this language (no issue with other plugins if they use åäö and it store it correctly in database).
> > And this is for every time the plugin shall change any thing in a text, because of player use some words some match a rule i have set. Only one placeholder some do it correctly is {original_message} .
> > See if it can be solved or try to get around it.
> > CHC version: 10.01.11 (has bee like this from the beginning)
> > Minecraft Version: 1.16.4
> > MySQL: false
> > BungeeCord: false
> > one example
> > `25.12 14:17:53 [Server] INFO Bigkaninen issued server command: /g hej på dig 25.12 14:17:53 [Server] INFO [ChatControlRed 10.1.11] Command /channel send mc-globalt hej pa dig took 8.56 ms`
> 
> Hey! Merry Christmas! I don't really understand everything. For the first part, Kangarko is aware that there's some issues under windows with some characters, but for now, this isn't a priority. But what's the other problem? Could you please provide your `/chc debug` file, screenshots and/or vidéos?

It is when the plugin shall alter a msg, and if I not miss it is under linux not windows.

**Comment by ElBananaa** [comment]
> > > If you typ "hej hur är det :)" when chc see ":)" it apply a emoji/Smileys (for it match a rule) and players see this "hej hur ar det :)" use Linux and it has support for this language (no issue with other plugins if they use åäö and it store it correctly in database).
> > > And this is for every time the plugin shall change any thing in a text, because of player use some words some match a rule i have set. Only one placeholder some do it correctly is {original_message} .
> > > See if it can be solved or try to get around it.
> > > CHC version: 10.01.11 (has bee like this from the beginning)
> > > Minecraft Version: 1.16.4
> > > MySQL: false
> > > BungeeCord: false
> > > one example
> > > `25.12 14:17:53 [Server] INFO Bigkaninen issued server command: /g hej på dig 25.12 14:17:53 [Server] INFO [ChatControlRed 10.1.11] Command /channel send mc-globalt hej pa dig took 8.56 ms`
> > 
> > 
> > Hey! Merry Christmas! I don't really understand everything. For the first part, Kangarko is aware that there's some issues under windows with some characters, but for now, this isn't a priority. But what's the other problem? Could you please provide your `/chc debug` file, screenshots and/or vidéos?
> 
> It is when the plugin shall alter a msg, and if I not miss it is under linux not windows.

Alright! Could you please provide the `/chc debug` file please?

**Comment by broken1arrow** [comment]
> > > > If you typ "hej hur är det :)" when chc see ":)" it apply a emoji/Smileys (for it match a rule) and players see this "hej hur ar det :)" use Linux and it has support for this language (no issue with other plugins if they use åäö and it store it correctly in database).
> > > > And this is for every time the plugin shall change any thing in a text, because of player use some words some match a rule i have set. Only one placeholder some do it correctly is {original_message} .
> > > > See if it can be solved or try to get around it.
> > > > CHC version: 10.01.11 (has bee like this from the beginning)
> > > > Minecraft Version: 1.16.4
> > > > MySQL: false
> > > > BungeeCord: false
> > > > one example
> > > > `25.12 14:17:53 [Server] INFO Bigkaninen issued server command: /g hej på dig 25.12 14:17:53 [Server] INFO [ChatControlRed 10.1.11] Command /channel send mc-globalt hej pa dig took 8.56 ms`
> > > 
> > > 
> > > Hey! Merry Christmas! I don't really understand everything. For the first part, Kangarko is aware that there's some issues under windows with some characters, but for now, this isn't a priority. But what's the other problem? Could you please provide your `/chc debug` file, screenshots and/or vidéos?
> > 
> > 
> > It is when the plugin shall alter a msg, and if I not miss it is under linux not windows.
> 
> Alright! Could you please provide the `/chc debug` file please?

here is it

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742352/debug.zip)

**Comment by ElBananaa** [comment]
> > > > > If you typ "hej hur är det :)" when chc see ":)" it apply a emoji/Smileys (for it match a rule) and players see this "hej hur ar det :)" use Linux and it has support for this language (no issue with other plugins if they use åäö and it store it correctly in database).
> > > > > And this is for every time the plugin shall change any thing in a text, because of player use some words some match a rule i have set. Only one placeholder some do it correctly is {original_message} .
> > > > > See if it can be solved or try to get around it.
> > > > > CHC version: 10.01.11 (has bee like this from the beginning)
> > > > > Minecraft Version: 1.16.4
> > > > > MySQL: false
> > > > > BungeeCord: false
> > > > > one example
> > > > > `25.12 14:17:53 [Server] INFO Bigkaninen issued server command: /g hej på dig 25.12 14:17:53 [Server] INFO [ChatControlRed 10.1.11] Command /channel send mc-globalt hej pa dig took 8.56 ms`
> > > > 
> > > > 
> > > > Hey! Merry Christmas! I don't really understand everything. For the first part, Kangarko is aware that there's some issues under windows with some characters, but for now, this isn't a priority. But what's the other problem? Could you please provide your `/chc debug` file, screenshots and/or vidéos?
> > > 
> > > 
> > > It is when the plugin shall alter a msg, and if I not miss it is under linux not windows.
> > 
> > 
> > Alright! Could you please provide the `/chc debug` file please?
> 
> here is it
> 
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742352/debug.zip)

Thanks!
Alright, so, to fix this, in your settings file, set: `Strip_Accents` to `false`.
I tested it on my server, and it fixed the issue.

I'm closing this issue, feel free to keep sending messages here if it doesn't work, and I'll reopen it then.

**Comment by broken1arrow** [comment]
> > > > > > If you typ "hej hur är det :)" when chc see ":)" it apply a emoji/Smileys (for it match a rule) and players see this "hej hur ar det :)" use Linux and it has support for this language (no issue with other plugins if they use åäö and it store it correctly in database).
> > > > > > And this is for every time the plugin shall change any thing in a text, because of player use some words some match a rule i have set. Only one placeholder some do it correctly is {original_message} .
> > > > > > See if it can be solved or try to get around it.
> > > > > > CHC version: 10.01.11 (has bee like this from the beginning)
> > > > > > Minecraft Version: 1.16.4
> > > > > > MySQL: false
> > > > > > BungeeCord: false
> > > > > > one example
> > > > > > `25.12 14:17:53 [Server] INFO Bigkaninen issued server command: /g hej på dig 25.12 14:17:53 [Server] INFO [ChatControlRed 10.1.11] Command /channel send mc-globalt hej pa dig took 8.56 ms`
> > > > > 
> > > > > 
> > > > > Hey! Merry Christmas! I don't really understand everything. For the first part, Kangarko is aware that there's some issues under windows with some characters, but for now, this isn't a priority. But what's the other problem? Could you please provide your `/chc debug` file, screenshots and/or vidéos?
> > > > 
> > > > 
> > > > It is when the plugin shall alter a msg, and if I not miss it is under linux not windows.
> > > 
> > > 
> > > Alright! Could you please provide the `/chc debug` file please?
> > 
> > 
> > here is it
> > [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742352/debug.zip)
> 
> Thanks!
> Alright, so, to fix this, in your settings file, set: `Strip_Accents` to `false`.
> I tested it on my server, and it fixed the issue.
> 
> I'm closing this issue, feel free to keep sending messages here if it doesn't work, and I'll reopen it then.

If I turn of, I get this problem.

```
26.12 17:38:17 [Server] INFO *--------- Rule match (chat) for LelleYT ---------
26.12 17:38:17 [Server] INFO MATCH: [^\u0000-\u007F]+
26.12 17:38:17 [Server] INFO CATCH: ska titta på ett bygge jag ska göra
26.12 17:38:17 [Server] INFO Original message cancelled.
```

**Comment by ElBananaa** [comment]
> > > > > > > If you typ "hej hur är det :)" when chc see ":)" it apply a emoji/Smileys (for it match a rule) and players see this "hej hur ar det :)" use Linux and it has support for this language (no issue with other plugins if they use åäö and it store it correctly in database).
> > > > > > > And this is for every time the plugin shall change any thing in a text, because of player use some words some match a rule i have set. Only one placeholder some do it correctly is {original_message} .
> > > > > > > See if it can be solved or try to get around it.
> > > > > > > CHC version: 10.01.11 (has bee like this from the beginning)
> > > > > > > Minecraft Version: 1.16.4
> > > > > > > MySQL: false
> > > > > > > BungeeCord: false
> > > > > > > one example
> > > > > > > `25.12 14:17:53 [Server] INFO Bigkaninen issued server command: /g hej på dig 25.12 14:17:53 [Server] INFO [ChatControlRed 10.1.11] Command /channel send mc-globalt hej pa dig took 8.56 ms`
> > > > > > 
> > > > > > 
> > > > > > Hey! Merry Christmas! I don't really understand everything. For the first part, Kangarko is aware that there's some issues under windows with some characters, but for now, this isn't a priority. But what's the other problem? Could you please provide your `/chc debug` file, screenshots and/or vidéos?
> > > > > 
> > > > > 
> > > > > It is when the plugin shall alter a msg, and if I not miss it is under linux not windows.
> > > > 
> > > > 
> > > > Alright! Could you please provide the `/chc debug` file please?
> > > 
> > > 
> > > here is it
> > > [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742352/debug.zip)
> > 
> > 
> > Thanks!
> > Alright, so, to fix this, in your settings file, set: `Strip_Accents` to `false`.
> > I tested it on my server, and it fixed the issue.
> > I'm closing this issue, feel free to keep sending messages here if it doesn't work, and I'll reopen it then.
> 
> If I turn of, I get this problem.
> 
> ```
> 26.12 17:38:17 [Server] INFO *--------- Rule match (chat) for LelleYT ---------
> 26.12 17:38:17 [Server] INFO MATCH: [^\u0000-\u007F]+
> 26.12 17:38:17 [Server] INFO CATCH: ska titta på ett bygge jag ska göra
> 26.12 17:38:17 [Server] INFO Original message cancelled.
> ```

Hey!

In your `rules/chat.rs` file, comment or remove this part:
```
# Prevent special, unicode characters. Those are misused to bypass filters.
# Please keep in mind that non-English languages use them, so only uncomment this on English servers.
match [^\u0000-\u007F]+
then warn {prefix_error}Unicode characters are prohibited.
then deny
```
It should fix your issue.

**Comment by broken1arrow** [comment]
> > > > > > > > If you typ "hej hur är det :)" when chc see ":)" it apply a emoji/Smileys (for it match a rule) and players see this "hej hur ar det :)" use Linux and it has support for this language (no issue with other plugins if they use åäö and it store it correctly in database).
> > > > > > > > And this is for every time the plugin shall change any thing in a text, because of player use some words some match a rule i have set. Only one placeholder some do it correctly is {original_message} .
> > > > > > > > See if it can be solved or try to get around it.
> > > > > > > > CHC version: 10.01.11 (has bee like this from the beginning)
> > > > > > > > Minecraft Version: 1.16.4
> > > > > > > > MySQL: false
> > > > > > > > BungeeCord: false
> > > > > > > > one example
> > > > > > > > `25.12 14:17:53 [Server] INFO Bigkaninen issued server command: /g hej på dig 25.12 14:17:53 [Server] INFO [ChatControlRed 10.1.11] Command /channel send mc-globalt hej pa dig took 8.56 ms`
> > > > > > > 
> > > > > > > 
> > > > > > > Hey! Merry Christmas! I don't really understand everything. For the first part, Kangarko is aware that there's some issues under windows with some characters, but for now, this isn't a priority. But what's the other problem? Could you please provide your `/chc debug` file, screenshots and/or vidéos?
> > > > > > 
> > > > > > 
> > > > > > It is when the plugin shall alter a msg, and if I not miss it is under linux not windows.
> > > > > 
> > > > > 
> > > > > Alright! Could you please provide the `/chc debug` file please?
> > > > 
> > > > 
> > > > here is it
> > > > [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742352/debug.zip)
> > > 
> > > 
> > > Thanks!
> > > Alright, so, to fix this, in your settings file, set: `Strip_Accents` to `false`.
> > > I tested it on my server, and it fixed the issue.
> > > I'm closing this issue, feel free to keep sending messages here if it doesn't work, and I'll reopen it then.
> > 
> > 
> > If I turn of, I get this problem.
> > ```
> > 26.12 17:38:17 [Server] INFO *--------- Rule match (chat) for LelleYT ---------
> > 26.12 17:38:17 [Server] INFO MATCH: [^\u0000-\u007F]+
> > 26.12 17:38:17 [Server] INFO CATCH: ska titta på ett bygge jag ska göra
> > 26.12 17:38:17 [Server] INFO Original message cancelled.
> > ```
> 
> Hey!
> 
> In your `rules/chat.rs` file, comment or remove this part:
> 
> ```
> # Prevent special, unicode characters. Those are misused to bypass filters.
> # Please keep in mind that non-English languages use them, so only uncomment this on English servers.
> match [^\u0000-\u007F]+
> then warn {prefix_error}Unicode characters are prohibited.
> then deny
> ```
> 
> It should fix your issue.

thanks will test it, I think it was an other rule some was the issue for some symbols.

**Comment by kangarko** [comment]
Thanks so much to Banana for helping <3
