### ISSUE TITLE
Ignore command

### ISSUE THREAD

**Issue by Kielczi** [kangarko/ChatControl#374]
Hi!
In chatcontrol pro there was a command ./ignore and permission for this chatcontrol.command.ignore. In chatcontrol red there isn't or it is different permission. If not, can you add this comamnd to your plugin?

**Comment by ElBananaa** [comment]
> Hi!
> In chatcontrol pro there was a command ./ignore and permission for this chatcontrol.command.ignore. In chatcontrol red there isn't or it is different permission. If not, can you add this comamnd to your plugin?

Hey! Merry Christmas!
There is a ignore command in ChatControl Red. The permission is the same one: `chatcontrol.command.ignore`
You can take a look at the permission list here: https://github.com/kangarko/ChatControl-Red/wiki/Permissions, or by using `/chc perms` ingame. You can also find the command list here: https://github.com/kangarko/ChatControl-Red/wiki/Commands

Please let me know if you need anything else, or if I can close this ticket. ;)

**Comment by Kielczi** [comment]
> > Hi!
> > In chatcontrol pro there was a command ./ignore and permission for this chatcontrol.command.ignore. In chatcontrol red there isn't or it is different permission. If not, can you add this comamnd to your plugin?
> 
> Hey! Merry Christmas!
> There is a ignore command in ChatControl Red. The permission is the same one: `chatcontrol.command.ignore`
> You can take a look at the permission list here: https://github.com/kangarko/ChatControl-Red/wiki/Permissions, or by using `/chc perms` ingame. You can also find the command list here: https://github.com/kangarko/ChatControl-Red/wiki/Commands
> 
> Please let me know if you need anything else, or if I can close this ticket. ;)

Oh , there was an option in config to enable this future. Thanks!

**Comment by ElBananaa** [comment]
> > > Hi!
> > > In chatcontrol pro there was a command ./ignore and permission for this chatcontrol.command.ignore. In chatcontrol red there isn't or it is different permission. If not, can you add this comamnd to your plugin?
> > 
> > 
> > Hey! Merry Christmas!
> > There is a ignore command in ChatControl Red. The permission is the same one: `chatcontrol.command.ignore`
> > You can take a look at the permission list here: https://github.com/kangarko/ChatControl-Red/wiki/Permissions, or by using `/chc perms` ingame. You can also find the command list here: https://github.com/kangarko/ChatControl-Red/wiki/Commands
> > Please let me know if you need anything else, or if I can close this ticket. ;)
> 
> Oh , there was an option in config to enable this future. Thanks!

You're welcome!
Have a great day.

Closing this issue. If you need anything else, just open a new one :D
