### ISSUE TITLE
1.7.10: ChatControl doesn't sync via BungeeCord

### ISSUE THREAD

**Issue by marekvac** [kangarko/ChatControl#377]
Minecraft Version: Thermos 1.7.10
MySQL: true
BungeeCord: true

After I did settings on chatcontrol, enabled bungeecord support on both servers. Installed bungeecontrol red on bungeecord. And messages doesn't send to other server. I turn on the bungee debug, Thermos servers sends packets, bungeecord receives them, it says packets are sending to other server, but the other server does not receive them. Also doesn't works private messages - it says the player isn't online.

Bungeecord is Waterfall Travertine, fork for 1.7

Bungeecord console output:
`[23:28:07 INFO]: [BungeeControl-Red] Incoming packet CHANNEL from event`
`[23:28:07 INFO]: [BungeeControl-Red]    Forwarded to 'event2'`
`[23:28:07 INFO]: [BungeeControl-Red]    Did not send to 'event', the server equals sender`
`[23:28:49 INFO]: [BungeeControl-Red] Incoming packet CHANNEL from event`
`[23:28:49 INFO]: [BungeeControl-Red]    Forwarded to 'event2'`
`[23:28:49 INFO]: [BungeeControl-Red]    Did not send to 'event', the server equals sender`

Debug from thermos server:
`[ChatControlRed] [bungee] Server 'event' sent bungee message [plugin:chcred, CHANNEL]: admin, MarcusCZ, 3bf67b57-aaba-3e4b-8efa-e2f192ec6c11, aa, {Current_Component={Text=, Inherit_Formatting={"extra":[{"color":"white","text":"aa"}],"text":""}}, Past_Components=[{Text=, Hover_Event={Action=SHOW_TEXT, Value={"extra":[{"extra":["8f2ef38f-e07a-407a-a2f3-28c25d561770"],"text":""}],"text":""}}}, {Text=}, {Text=[admin] MarcusCZ: }, {Text=aa, Inherit_Formatting={"extra":[{"color":"white","text":""}],"text":""}}]}, [admin] MarcusCZ: aa, true, true, true,`
`[23:55:48 INFO]: [ChatControlRed] [channel] Sending message to admin took 4ms`
`[23:55:48 INFO]: [admin] MarcusCZ: aa`

Attaching debug.zip from one of thermos server, config.yml from bungeecord, settings.yml from bungeecontrol

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742504/debug.zip)
[bungeecord-config.zip](https://github.com/kangarko/ChatControl-Red/files/5742513/bungeecord-config.zip)

**Comment by marekvac** [comment]
Bungeecord messages (player joined/left network) works.

**Comment by ElBananaa** [comment]
Hey! Merry Christmas! (A bit late)

1) - First of all, make sure that you followed the steps listed on the wiki page (https://github.com/kangarko/ChatControl-Red/wiki/BungeeCord).

2) - Update your BungeeChatAPI (You are using v1.0.1, but v2.0.0 is available, use this version.)

3) - If it doesn't work, since you are using Travertine, switch to BungeeCord and try to reproduce this issue.

Let me know if anything works, or not.

**Comment by marekvac** [comment]
I followed all steps from wiki.

BungeeChatAPI I have 2.0.0, but in plugin.yml file is version 1.0.1 - that should @kangarko fix.

First I switched to [HexaCord ](https://github.com/HexagonMC/BungeeCord/releases )- same problem here, but I must disable support for protocollib in settings.yml because I got kicked from server after I wrote a message. Then I switched to [BungeeCord](https://ci.md-5.net/job/BungeeCord/1119/) and an error occurred right after the first run - settings.yml file of BungeeControl was empty and plugin was unable to load.

[Full log from bungeecord](https://pastebin.com/Lujerakv)

**Comment by ElBananaa** [comment]
> I followed all steps from wiki.
> 
> BungeeChatAPI I have 2.0.0, but in plugin.yml file is version 1.0.1 - that should @kangarko fix.
> 
> First I switched to [HexaCord ](https://github.com/HexagonMC/BungeeCord/releases)- same problem here, but I must disable support for protocollib in settings.yml because I got kicked from server after I wrote a message. Then I switched to [BungeeCord](https://ci.md-5.net/job/BungeeCord/1119/) and an error occurred right after the first run - settings.yml file of BungeeControl was empty and plugin was unable to load.
> 
> [Full log from bungeecord](https://pastebin.com/Lujerakv)

Alright, thanks!

It looks like the file needs you to provide the server alias manually. So try to fill it manually, and let me know if it fixed the issue.

**Comment by marekvac** [comment]
>Alright, thanks!
>
>It looks like the file needs you to provide the server alias manually. So try to fill it manually, and let me know if it fixed the issue.

I tried it, but after the next server start the file was empty again.

**Comment by ElBananaa** [comment]
> > Alright, thanks!
> > It looks like the file needs you to provide the server alias manually. So try to fill it manually, and let me know if it fixed the issue.
> 
> I tried it, but after the next server start the file was empty again.

Alright, you should consider reverting to Travertine then.
Could you also provide your `/chc debug` file?

**Comment by marekvac** [comment]
Here is it.

I also tried remove all other plugins, but it did not help.
In /chc forward I see only the server I am currently connected to and bungee.

[debug_server1.zip](https://github.com/kangarko/ChatControl-Red/files/5744670/debug_server1.zip)
[debug_server2.zip](https://github.com/kangarko/ChatControl-Red/files/5744671/debug_server2.zip)

**Comment by ElBananaa** [comment]
> Here is it.
> 
> I also tried remove all other plugins, but it did not help.
> In /chc forward I see only the server I am currently connected to and bungee.
> 
> [debug_server1.zip](https://github.com/kangarko/ChatControl-Red/files/5744670/debug_server1.zip)
> [debug_server2.zip](https://github.com/kangarko/ChatControl-Red/files/5744671/debug_server2.zip)

Thanks!

Well, I guess it's somehow related to your version, since as we can see on your debug outputs above, the message are actually forwarded. Your should wait for @kangarko to take a look at this issue.

**Comment by kangarko** [comment]
Sorry, for some versions on 1.7 and older, BungeeCord won't work. If this is a problem and you just bought the plugin, email matej@mineacademy.org for a refund.
