### ISSUE TITLE
1.16.4: output a net.md_5.bungee.api.chat.TextComponent in a channel with API

### ISSUE THREAD

**Issue by loewenjunges** [kangarko/ChatControl#379]
Hi, 
is it possible to output a net.md_5.bungee.api.chat.TextComponent in a channel with the API? So that you can create your own hover and click events.
Unfortunately I could not find anything in this regard

**Comment by kangarko** [comment]
Sorry this is not possible, we don't use md5's library but instead have our own one that's compiled on the fly.
