### ISSUE TITLE
Compat break with new /r behavior of EssentialsX

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#38]
Cross-post as this could also affect newer versions of ChatControl.

https://github.com/drtshock/Essentials/issues/260

tl;dr EssentialsX recently replaced the behavior of handling /r messages. This allows to not have issues with interfering players whispering you and so your /r message gets to the wrong receiver.

**Comment by kangarko** [comment]
I just have added support to the EssentialsX:
https://www.spigotmc.org/resources/chatcontrol.271/update?update=52890

I don't even have the source of 4th generation anymore, so please upgrade or stay at the original essentials.

**Comment by drtshock** [comment]
Thanks for adding support :)
