### ISSUE TITLE
1.16.3: How i block permission to write special format?

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#380]
which is the correct permission to block italic, bold ecc?
I tried to use like chatcontrol.color.magic and is not working.
People have chatcontrol.color.* setted to true and chatcontrol.color.magic setted to false
I am using luckperms

**Comment by ElBananaa** [comment]
Hey!
Afaik, there's no such permission in ChatControl-Red.

**Comment by Malachiel87** [comment]
so what i have to do for give them colors but no formatting  stuff?

**Comment by ElBananaa** [comment]
> so what i have to do for give them colors but no formatting stuff?

Alright, I was wrong, there are permissions for that, here's the list:

- `chatcontrol.color.bold`
- `chatcontrol.color.obfuscated`
- `chatcontrol.color.strikethrough`
- `chatcontrol.color.underline`
- `chatcontrol.color.italic`

Closing this issue.

**Comment by Malachiel87** [comment]
you should add these on wiki :)
