### ISSUE TITLE
Message placeholder striped of player set chat color ?

### ISSUE THREAD

**Issue by pustinek** [kangarko/ChatControl#381]
When creating a format for a specific channel, when using the placeholder `{message}` it appends his set chat color. I'm wondering if there is a placeholder/way that doesn't add said chat color to the message ?

**Comment by ElBananaa** [comment]
Hey!

Did you try to place a `&r` before the message placeholder?

**Comment by pustinek** [comment]
Doesn't work 😞
Would be nice to have a raw message format that way, we can easily set the default color of the message

**Comment by kangarko** [comment]
Sorry this is not possible, you will rather need to disable /chc color command entirely and possibly find a third party plugin then inject its color as a variable to the format
