### ISSUE TITLE
1.16.3: Can't use color codes on chatcontrol /nick alias

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#382]
Minecraft Version: 1.16.3
MySQL: true
BungeeCord: true
Debug: [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5743520/debug.zip)

Using /nick alias color are stripped
using /tag nick name colors work fine

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.3
> MySQL: true
> BungeeCord: true
> Debug: [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5743520/debug.zip)
> 
> Using /nick alias color are stripped
> using /tag nick name colors work fine

Hey!
In your `settings.yml` file, under the `Rules:` part, set `Strip_Colors` to `false`
Let me know if it fixed your issue.

**Comment by Malachiel87** [comment]
now is blocked as unicode character

**Comment by Malachiel87** [comment]
nvm fixed :)

**Comment by ElBananaa** [comment]
> now is blocked as unicode character



> nvm fixed :)

Great!
I am closing this issue, feel free to open a new one if you need anything else!
Have a nice day! :)
