### ISSUE TITLE
Add separate permission for use color/format on tag

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#383]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
All people

2. What would happen if we won't implement this feature? How's your server being affected?
It help

I would like to see the permission splited in chatcontrol.color.* and chatcontrol.tag.color.*, for example i wanna allow bold nick but i don't wanna allow it on chat, it would have more sense and more control :)

**Comment by ElBananaa** [comment]
> 1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
>    All people
> 2. What would happen if we won't implement this feature? How's your server being affected?
>    It help
> 
> I would like to see the permission splited in chatcontrol.color.* and chatcontrol.tag.color.*, for example i wanna allow bold nick but i don't wanna allow it on chat, it would have more sense and more control :)

Hey!
This is already possible, but partially:


Allow players use & and hex colors. Replace apply_on with Colors.Apply_On sections from settings.yml (by default players can use colors everywhere
- `chatcontrol.use.color.{apply_on}`
(You can replace {apply_on} with: `chat`, me, `prefix`, `nick`, `suffix`, `private_message`

You also need to edit this part in your `settings.yml` file:

```
Colors:
 
  # Where should we let players to use & or RGB color codes?
  # Options: chat, me, prefix, nick, suffix, private_message
  Apply_On:
```

**Comment by Malachiel87** [comment]
i already know that but you can't  use it separately instead

**Comment by ElBananaa** [comment]
> i already know that but you can't use it separately instead

For now, afaik, you can't. I'll leave this suggestion open so Kangarko could take a look at it.

**Comment by kangarko** [comment]
Thanks! Right now I am dealing with other, more important issues but I can reconsider in the future.
