### ISSUE TITLE
MOTD should be per network join

### ISSUE THREAD

**Issue by james090500** [kangarko/ChatControl#384]
There should be an option to have MOTD in Bungee Control instead of individual servers. At the moment we have it enabled in just the hub however it causes problems:

- Join Network - Gets MOTD
- Goes to creative - No MOTD
- Goes back to hub - Gets MOTD

**Comment by Sikatsu** [comment]
I'd love to see this as well!

**Comment by kangarko** [comment]
Thanks! Something for the future :)
