### ISSUE TITLE
Get discord role and color when user sends message

### ISSUE THREAD

**Issue by james090500** [kangarko/ChatControl#386]
When a user sends a message from discord we should be somehow able to get their role and color so we can format their rank properly.

**Comment by Spaex** [comment]
Would be awesome missing that so much from the original DiscordSRV. Because Placeholders like %discordsrv_user_top_role_name% and %discordsrv_user_top_role_color_code% don't work for me when putting it into the discord-prefix.

**Comment by ElBananaa** [comment]
> Would be awesome missing that so much from the original DiscordSRV. Because Placeholders like %discordsrv_user_top_role_name% and %discordsrv_user_top_role_color_code% don't work for me when putting it into the discord-prefix.

Hey!

In order to use placeholders with the plugin, you must replace `%` with `{}`.
However, I don't know if this is something that could be done if you enable the `Send_Messages_As_Bot:` feature.
Anyways, Kangarko would clearly give you a better answer than mine, so please wait for his answer. :)

Have a nice day!

**Comment by Spaex** [comment]
> 
> 
> > Would be awesome missing that so much from the original DiscordSRV. Because Placeholders like %discordsrv_user_top_role_name% and %discordsrv_user_top_role_color_code% don't work for me when putting it into the discord-prefix.
> 
> Hey!
> 
> In order to use placeholders with the plugin, you must replace `%` with `{}`.
> However, I don't know if this is something that could be done if you enable the `Send_Messages_As_Bot:` feature.
> Anyways, Kangarko would clearly give you a better answer than mine, so please wait for his answer. :)
> 
> Have a nice day!

Thanks for the advice but sadly the placeholders won't work even with {} also turning `Send_Messages_As_Bot:` to false or true doesn't make them work.

**Comment by kangarko** [comment]
Thanks, right now the system is not built for this, however I can add this to our future suggestions list.
