### ISSUE TITLE
1.16.4: Disable formatting on minecraft to discord chat and vice versa

### ISSUE THREAD

**Issue by james090500** [kangarko/ChatControl#387]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Invalid characters/emojis should be removed from Discord to Minecraft chat:
![image](https://user-images.githubusercontent.com/20372645/103161847-1970c780-47e0-11eb-8f1e-90858bb72613.png)

And players with underscores should be escaped so their names aren't slanted
![image](https://user-images.githubusercontent.com/20372645/103161853-2a213d80-47e0-11eb-89ed-471667a8a193.png)

We also need to be able to control of players can type in bold, italics etc in discord from minecraft and vice versa

**Comment by kangarko** [comment]
The latest version doesn't have such problem. If I am wrong, post the exact username from Discord that is causing issues in Minecraft.

**Comment by kangarko** [comment]
There is going to be an new release tonight, so please use that.
