### ISSUE TITLE
{server_name} variable always returns with “A Minecraft server” and other issues with messages.yml

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#388]
Chat Control Red is everything I’ve ever wanted in a chat management plugin, my only complaint is that there seems to be less freedom when configuring the localization section, than there was with CCP. 

Aside from the {server_name} variable not working (tested in global-chat.yml, I triple checked and the server is in fact named), I’m also getting a “none” at the end of the message for certain configurations in the messages.yml. For example, when a player successfully joins a channel I simply want it to say “channel: global_chat” but instead it’s returning with “channel: global_chatnone”. 

Speaking of none, when following the instructions at the top of the messages.yml, replacing a message with none doesn’t seem to hide it, it just returns with “none”

Thanks for the awesome work you do:)

**Comment by pustinek** [comment]
To answer your first issue with the `{server_name}` placeholder. I believe it's a placeholder used by PlaceHolderAPI plugin. Where you have to download it via `/papi ecloud download Server` command and then change it under the PlaceHolderAPI config.yml file. At least that is what worked for me.

**Comment by james090500** [comment]
There seem to be 2 server_name variables. ChatControl has it's own one which if you use in certain places returns the ``server-name`` value under ``server.properties``. Then theres is a PAPI ``server-name`` as pustinek said. However, that returns the ``motd`` value under ``server.properties``

**Comment by Squeej** [comment]
Ah yup, it was s placeholder thing this whole time. Thanks for the help fellas, closing this issue
