### ISSUE TITLE
[Bungee] Spam on bungee console about messages

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#389]
Minecraft Version: Waterfall
MySQL: true
BungeeCord: true

Is anoying to get spammed with this :) https://gist.github.com/Malachiel87/9fd3bd485152ec49d4e109ea87939e15
I think it should be moved to debug or removed

**Comment by james090500** [comment]
This is due to having debug BungeeControl-Red set to something. I think ``packets``?

If you set it to ``Debug: []`` and restart bungee it will stop this

**Comment by Malachiel87** [comment]
yeah was default to packets, i removed it, waiting next bungee restart
