### ISSUE TITLE
Essentials Nickname

### ISSUE THREAD

**Issue by RhysDam** [kangarko/ChatControl#39]
I see you have added %nick which is great, however if nick is blank or not set then the persons name is blank.

Could you make it so if the users %nick is blank it defaults to their minecraft username?

**Comment by kangarko** [comment]
Can you test against the latest version? It has been recently added :)

**Comment by kangarko** [comment]
Implemented in 5.2.6.

**Comment by RhysDam** [comment]
Thanks!
