### ISSUE TITLE
Error ChatControl

### ISSUE THREAD

**Issue by chrisbruijnes** [kangarko/ChatControl#39]
Hey there!

Since a short time I get an error message the whole time.
Error: http://pastebin.com/3eWHdfqT

It says something to-do with the customsigns plugin. That plugins sets a command on a sign. Well, I have checked all the signs and clicked on it but I dont get an error so I have no idea what it could be.

Please, I hope there is any way to fix this.

**Comment by kangarko** [comment]
I think by 99% that it was fixed, correct me if I am wrong.
