### ISSUE TITLE
Chat extension to Discord

### ISSUE THREAD

**Issue by JPlayer3** [kangarko/ChatControl#391]
https://www.spigotmc.org/resources/interactivechat-discordsrv-addon-show-inventories-items-on-discord-translate-ic-placeholders.83917/

This is an add-on for a chat plugin.
Can I add such a feature to ChatControl-Red?

**Comment by ElBananaa** [comment]
> https://www.spigotmc.org/resources/interactivechat-discordsrv-addon-show-inventories-items-on-discord-translate-ic-placeholders.83917/
> 
> This is an add-on for a chat plugin.
> Can I add such a feature to ChatControl-Red?

Hey!
You should take a look at the [developper API](https://github.com/kangarko/ChatControl-Red/wiki/API). I think that you could actually do something like that. However, I'm not sure, you'll have to wait for an answer from Kangarko.

**Comment by JPlayer3** [comment]
I'm not asking if I can create an add-on plugin.

Seeing that it was released as an add-on for chat plugins, I wondered if ChatControl could implement such a feature as well.

**Comment by ElBananaa** [comment]
As said in the actual plugin roadmap:
`Due to a tiny team we are at present not open for features. There is no ETA. All features are consideration only.`

So I guess you'll have to wait for these features to eventually be added in the plugin.

**Comment by kangarko** [comment]
That looks awesome! Unfortunately I am pretty busy for the time being, but I can look into this sometime in the future :)
