### ISSUE TITLE
1.8.8: killer_item variable don't work

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#395]
Minecraft Version: 1.8.8 also 1.16.4
MySQL: true/
BungeeCord: true/
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5745327/debug.zip)

![image](https://user-images.githubusercontent.com/3611852/103180607-7c716580-4897-11eb-87b5-9c6738818b0f.png)

As you can see killer variable don't work, i  tested in all minecraft version and never worked

**Comment by james090500** [comment]
I had this issue. I replaced all {killer_item} references with [killer_item]

Here's an example death.rs https://paste.gg/p/anonymous/f809d9f10ef144aca42fe817d840f621

Here's an example of my killer-item.yml in variables. https://paste.gg/p/anonymous/8066467b0d9943eb8bc6190a66a48481

Which fixed the issue.

**Comment by kangarko** [comment]
Thanks to James for helping out!
