### ISSUE TITLE
1.16.4 Error: Unhandled exception listening to AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#396]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true
Logs: https://gist.github.com/Malachiel87/70dd25297f622f5485c873448523925d
![image](https://user-images.githubusercontent.com/3611852/103180732-d3c40580-4898-11eb-86d4-ddeab86ae390.png)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5745330/debug.zip)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true
> Logs: https://gist.github.com/Malachiel87/70dd25297f622f5485c873448523925d
> ![image](https://user-images.githubusercontent.com/3611852/103180732-d3c40580-4898-11eb-86d4-ddeab86ae390.png)
> 
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5745330/debug.zip)

Hey!
Your version of ProtocolLib is outdated. Same for ChatControlRed, please update both plugins.

**Comment by Malachiel87** [comment]
i upgraded both, i let you know if that come out again

**Comment by Malachiel87** [comment]
I upgraded and player reported again the "no formated" text on server 1.16.4 vanilla
There is the new [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5747574/debug.zip)
Error log: https://gist.github.com/Malachiel87/65b18cdd687eb788551cf0f09fae6b87
Screenshot:
![image](https://user-images.githubusercontent.com/3611852/103220073-a40c1080-491f-11eb-8666-9ca17843de43.png)

**Comment by ElBananaa** [comment]
> I upgraded and player reported again the "no formated" text on server 1.16.4 vanilla
> There is the new [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5747574/debug.zip)
> Error log: https://gist.github.com/Malachiel87/65b18cdd687eb788551cf0f09fae6b87
> Screenshot:
> ![image](https://user-images.githubusercontent.com/3611852/103220073-a40c1080-491f-11eb-8666-9ca17843de43.png)

Hey!

Could you explain us in which circumstances this happens? Is it a random error? Does it lasts, or it only happens for a message, then the format works again?

Also, make sure your are using the latest paper version (Paper-350).

Have a nice day! :)

**Comment by kangarko** [comment]
Somewhere you have Receiver_Condition that returns null. It must return either true or false. Next version will properly show this error cause.
