### ISSUE TITLE
1.8.x/1.16.xPrivate messages and reply messages don't work correct

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#397]
Minecraft Version: 1.8.x/1.16.x
MySQL: true
BungeeCord: true
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5745338/debug.zip)
People are complaining  that  sometimes using msg, the receiver will don't see the message, and in other case using /reply  will go to a wrong person

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.8.x/1.16.x
> MySQL: true
> BungeeCord: true
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5745338/debug.zip)
> People are complaining that sometimes using msg, the receiver will don't see the message, and in other case using /reply will go to a wrong person

Hey! This is related to #222.
I'm closing this issue, and quoting it there.
