### ISSUE TITLE
1.16.4: Error PAPI

### ISSUE THREAD

**Issue by Tylwen** [kangarko/ChatControl#398]
Hello, I have this problem since I installed a file. All PAPI variables no longer load in the chat.
I only have this problem with ChatControlRed. Featherboard is not affected as well as other plugins.

Here are the errors:
https://pastebin.com/b6MD7djP

Here is what I installed (I need this for TrMenu):
https://github.com/TrMenu/TrMenu/blob/v2/doc/INSTALL_GUIDE.md

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

**Comment by Tylwen** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5745410/debug.zip)

**Comment by ElBananaa** [comment]
> Hello, I have this problem since I installed a file. All PAPI variables no longer load in the chat.
> I only have this problem with ChatControlRed. Featherboard is not affected as well as other plugins.
> 
> Here are the errors:
> https://pastebin.com/b6MD7djP
> 
> Here is what I installed (I need this for TrMenu):
> https://github.com/TrMenu/TrMenu/blob/v2/doc/INSTALL_GUIDE.md
> 
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true

Hey!
It looks like this is something related to both plugins.
You should wait for an answer from both Arasple and Kangarko.
I also noticed some of your plugins (like protocolLib) aren't update. You should consider updating them in order to avoid bugs with ChatControl.

**Comment by Tylwen** [comment]
I have ProtocolLib 4.5.1

**Comment by ElBananaa** [comment]
> I have ProtocolLib 4.5.1

Yes, I know, and here's what's said on the plugin page: 
![image](https://user-images.githubusercontent.com/53318613/103184023-2bbd3500-48b6-11eb-9635-93600596d907.png)
So consider updating to the latest dev build (https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)

Have a nice day! :)

**Comment by kangarko** [comment]
This is a problem with the autorestart expansion, you'll need to contact their plugin author.
