### ISSUE TITLE
1.16.4: Global message disable

### ISSUE THREAD

**Issue by WolverStones** [kangarko/ChatControl#399]
Hello, how can disable global message sync?

https://imgur.com/gallery/gRRvPYW

**Comment by Tylwen** [comment]
List:
    standard:
      Format: chat
      Format_Spy: '@noprefix chat'
      Discord: true
      Bungee: false
    admin:
      Format: admin-chat
      Format_Console: '[A-chat {player}] {message}'
      Bungee: true
      Discord: true
    global:
      Format: global-chat
      Bungee: true
    ranged:
      Format: '&6[ranged] &7{pl_prefix+}{player}:{pl_suffix} {message}'
      Range: 100
      Bungee: false
    towny:
      Format: chat
      Party: towny-town
      Bungee: false
    helpop:
      Format: helpop
      Discord: true
      Bungee: false

**Comment by Tylwen** [comment]
Put Bungee: true/false everywhere

**Comment by WolverStones** [comment]
Thank you
