### ISSUE TITLE
[Solved] how to block advertisement 

### ISSUE THREAD

**Issue by Retracker** [kangarko/ChatControl#4]
can someone give me a match that will block any link like play.server.com or block www.youtube.com or block facebook.com or block server.com/forum. i dont know how to make the match for advertising, i only know how to make it for swearing not for advertising. 

this is the default match that comes with the rules.txt
match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu|me)\b
id 2
before strip [\(\[\]\)]
then warn &cadvertising is not allowed.
then replace www.thezortex.com

but this one only blocks links like a.com or b.com not youtube.com or www.youtube.com or webpages.
please help, thanks.

**Comment by kangarko** [comment]
The filter you provided does block any domain. I just tested:

>match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu|me)\b
>then warn &cPlease do not advertise.
>then deny

**Comment by Retracker** [comment]
i rechecked it works but theres a few problems now when a player says "came" it will be registered as a advertisment and deny it also how can i leave to not block my website domain but block all the other domains?

**Comment by Retracker** [comment]
nvm i fixed the "Came" thing,  i just need to know how to make it so it wont block my website domain address

**Comment by Retracker** [comment]
bump ;/

**Comment by kangarko** [comment]
Please read the header of rules/rules.txt file. It contains all the available operators and how to use them.

To ignore certain domains use "ignore string" operator. An example:
>match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu|me)\b
>ignore string yourdomain.com|anotherdomain.org
>before strip [\(\[\]\)]
>handle as advertisement

**Comment by Retracker** [comment]
@kangarko k thanks but now when someones types in my website domain it shows up as
www thezortex com not www.thezortex.com the "." (dot) gets removed is it cause of:
match [a-zA-Z0-9-.]+\s?(.|dot|(dot)|-|;|:|,)\s?(com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu|me)\b???
thank you.

**Comment by Retracker** [comment]
also i  only added ignore string yourdomain.com|anotherdomain.org
not before strip [([])]
do i need to add before strip [([])]??

**Comment by kangarko** [comment]
>When url is entered in chat, all the dots are replaced by spaces (e.g. www.google.com -> www google >com)
>This change is not coming from ChatControl. Essentials is known to do that, try adding your players >permission essentials.chat.url and essentials.msg.url for private messages.

>do i need to add before strip [([])]??
no it does not matter

**Comment by Retracker** [comment]
@kangarko omg thank youu sooo much!!! Youre the only author that ever has helped me with a plugin problem!!! Thanks a bunch!! I very very appreciate it!! Cya

**Comment by kangarko** [comment]
Oh thanks :)

**Comment by justin2001** [comment]
@kangarko Please unignore me in spigot. ;)
