### ISSUE TITLE
1.8.8 | Encountering a MalformedJsonException

### ISSUE THREAD

**Issue by Ultimating** [kangarko/ChatControl#4]
When I join the server, the console spams MalformedJsonExceptions until I leave the server. I've attached the error.log and I have made sure I'm using the 1.8.8 paper build provided by PaperMC (even though the file says I'm using CraftBukkit). What could be causing this?

[error.log](https://github.com/kangarko/ChatControl-Red/files/5520929/error.log)

**Comment by kangarko** [comment]
Please configure your 'server-name' in server.properties according to mineacademy.org/server-properties
