### ISSUE TITLE
1.16.4 | Player has been kicked from the game when removing messages

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#40]
# **Environment**
### **ChatControl-Red Version**: ChatControl-Red-10.0.2b

Alright, so basically, my friend tried to spam the chat, and then I removed his messages, but at some point, it prints a weird message. Also, my friend sees his nickname in the chat instead of mine, even tho I ran the command. This is related to https://github.com/kangarko/ChatControl-Red/issues/37
There's no errors in the console.

Here's a video of the issue: 
https://streamable.com/6p4se6

**Comment by kangarko** [comment]
Thank you. I will fix that, I haven't seen any "weird" message except the fact that when he got kicked, it showed the wrong nick. That will be patched. Let me know if there's anything else :)

**Comment by kangarko** [comment]
So you're saying your friend got kicked when you were removing messages? What kick message did he see?

**Comment by ElBananaa** [comment]
Well, it says that he got kicked, but he wasn't actually kicked from the server

**Comment by kangarko** [comment]
Interesting, please test 10.0.3 it is out in a few mins

**Comment by ElBananaa** [comment]
Alright, so, the issue with the name placeholder is fixed, but it still shows the kick message when I do the exact same thing.
Everyone can see this message, and I have all perms.

**Comment by kangarko** [comment]
Can you please ZIP me your entire ChatControl folder? I have yet been not been able to reproduce this.

**Comment by ElBananaa** [comment]
There you go
[ChatControlRed.zip](https://github.com/kangarko/ChatControl-Red/files/5547216/ChatControlRed.zip)
I also made a cleaner video of the issue: https://streamable.com/gb06c2

**Comment by kangarko** [comment]
Thanks, I fixed that.
