### ISSUE TITLE
1.16.4: Disabling specific rule sections in specific channels?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#400]
Hi, I wanna ask if it's possible to disable for ex. swearing section of rules (and how to "create" it, when it's whole in global?) in specific channels. So if I wanna make "night chat channel" without rules applying, if I don't wanna rules in vip or admin chat etc.

**Comment by TheIntolerant** [comment]
Yeah, that is possible, using one of the operators seen in [GitHub Wiki - Rules](https://github.com/kangarko/ChatControl-Red/wiki/Rules)

``ignore channel <channel names> [channel mode]``
Only applied from chatting – when sender sent the message from a certain chat channel, ignore the rule. Use | to separate multiple channels. You can also specify the mode the sender must be in to ignore.

**Example:**
```
ignore channel admin
ignore channel admin|anarchy
```

**How do I do this??**

To allow people, for example, to swear in a specific channel,
Firstly, go into **groups.rs** file inside the rules folder. 
Secondly, under ``group swear`` just add ``ignore channel <channel_name>``, save the file, and type ``/chc reload`` and that should allow people to bypass that specific rule group in that channel.

**Comment by ElBananaa** [comment]
Hey!
Thanks to @iTz-MrAnonymous for answering you.

I'm closing this issue, feel free to open a new one if you need anything else!
Have a great day! :)
