### ISSUE TITLE
Allow to use names on the nick of the same player that invoking it

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#401]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
Allow the player to use his nick in different colors

2. What would happen if we won't implement this feature? How's your server being affected?
Player have to choose other names

Actually using a real player in the nickname will be prevented. yeah is a nice feature, but what about if the nick contain your name, it should be allowed :)

**Comment by kangarko** [comment]
<img width="404" alt="Screenshot 2020-12-30 at 18 31 57" src="https://user-images.githubusercontent.com/1918426/103370528-533a1a80-4acd-11eb-8a1f-85466a4a306f.png">
Will be working on then next version
