### ISSUE TITLE
Block unicode characters on nick

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#403]
I would ask if is possible to block the unicode characters on nick like on chat

**Comment by ElBananaa** [comment]
Hey!

Simply paste this code in your `rules/commands.rs` it should prevent the usage of unicode in commands.
```
match [^\u0000-\u007F]+
then warn Unicode is prohibited
then deny
```

**Comment by Malachiel87** [comment]
I can't sti use any kind of unicode here after pasting jt

**Comment by ElBananaa** [comment]
> I can't sti use any kind of unicode here after pasting jt

Wait, are you trying to block unicode, or allow it?

**Comment by Malachiel87** [comment]
I want BLOCK it on the nick/tag command

Il lun 28 dic 2020, 18:21 Nathan <notifications@github.com> ha scritto:

**Comment by ElBananaa** [comment]
> > I can't sti use any kind of unicode here after pasting jt
> 
> Wait, are you trying to block unicode, or allow it?

Weird. I just tried to use it with the /nick & /tag commands, and it actually blocks the commands. Same with any other command. Make sure you correctly pasted this code in your file, and try to restart your server. Also make sure your plugins are up-to-date.

**Comment by Malachiel87** [comment]
ok it worked, i have to put that unicode font before the nick rule.... btw i wanna allow only normal allow normal characters like authme one regex [a-zA-Z0-9_]*'

**Comment by ElBananaa** [comment]
> ok it worked, i have to put that unicode font before the nick rule.... btw i wanna allow only normal allow normal characters like authme one regex [a-zA-Z0-9_]*'

Hey!

Could you explain in details what you would like to do?

**Comment by Malachiel87** [comment]
i wanna allow alphabetical names, numbers, '_' like the minecract name and colors codes

**Comment by ElBananaa** [comment]
Hmm, I don't think I could help you with that unfortunately.
You should wait for Kangarko.

**Comment by kangarko** [comment]
You can place the rule mentioned above to rules/tag.rs file and it will block it:

```
match [^\u0000-\u007F]+
then warn Unicode is prohibited
then deny
```

<img width="438" alt="Screenshot 2020-12-30 at 18 54 30" src="https://user-images.githubusercontent.com/1918426/103371710-774b2b00-4ad0-11eb-828e-f6ec51379305.png">

**Comment by Malachiel87** [comment]
That code still allow some symbols and dots or accented letter, I want just allow normal alphabet letters and numbers and _ like Minecraft names rules

**Comment by kangarko** [comment]
Try this:

match [^a-zA-Z0-9äöüÄÖÜ_]+

**Comment by Malachiel87** [comment]
where i have to put that?

**Comment by ElBananaa** [comment]
> Try this:
> 
> match [^a-zA-Z0-9äöüÄÖÜ_]+

I'm not sure, but I think you should create a new rule in your tag.rs file. Under this part:
```
match [^\u0000-\u007F]+
then warn Unicode is prohibited
then deny
``` 
add
```
match [^a-zA-Z0-9äöüÄÖÜ_]+
then warn Special characters are prohibited
then deny
