### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#407]
.

**Comment by elijahskingdom** [comment]
Oh. I'm dumb. Just thought of this while I was out. Might be due to multiple groups in quit.rs? Whereas there should only be one default and just have all the the groups inherit default via luckperms?..

**Comment by ElBananaa** [comment]
> Oh. I'm dumb. Just thought of this while I was out. Might be due to multiple groups in quit.rs? Whereas there should only be one default and just have all the the groups inherit default via luckperms?..

Hey!

The groups in rules files should only be defined in the groups.rs file, not in luckperms.
The group system is used to create messages/rules groups that can be toggled.

If you need more help with this system, I need you to provide us the `/chc debug` file.

**Comment by elijahskingdom** [comment]
I wasn't talking about the groups.rs i was talking about the join/quit.rs. my custom javascript prefix works on the login but not quit.rs. It's still not working and i believe there's no fancy setup for quit.rs either, correct?

(sorry i closed this assuming i knew the solution but i didn't woops..)

**Comment by elijahskingdom** [comment]
here's the debug.zip though in case that helps:
