### ISSUE TITLE
1.16.4: Item Variable Possibility

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl#408]
Hiya is it possible with the item variable to:

1. Make it show the display name of the item (so when another plugin renames them it'll show that display name in chat.

2. Add several keys for the 1 variable.

**Comment by ElBananaa** [comment]
> Hiya is it possible with the item variable to:
> 
> 1. Make it show the display name of the item (so when another plugin renames them it'll show that display name in chat.
> 2. Add several keys for the 1 variable.

Hey!

You should already by able to show the item name when using the item variable.
For the several key, I don't think this is something possible now.

**Comment by Ash10744** [comment]
It shows the item name but not the Display name...


SO when someone renames the item in an anvil etc it dont show that name just the item name.

**Comment by ElBananaa** [comment]
> It shows the item name but not the Display name...
> 
> SO when someone renames the item in an anvil etc it dont show that name just the item name.

Could you send me your actual item script?

**Comment by Ash10744** [comment]
Mhm!
https://mcpaste.io/7bddb98a90e3bbd6

**Comment by ElBananaa** [comment]
> Mhm!
> https://mcpaste.io/7bddb98a90e3bbd6

Your script it outdated. Use this one instead: https://hastebin.com/ahohobawax.php
It'll show the display name if the item has one, it'll change the first letter of each word with a capital, and you can change the color shown in the chat here: `var textColor = '#42f595';`

**Comment by kangarko** [comment]
Hey Ash! There's a lot of possibilities so you can show multiple things under just one Key variable. You can of course just show the item name, here's an example of how we do things for the killer's item: https://pastebin.com/2vsQUH01

**Comment by Ash10744** [comment]
Alright! Thank you but is it possible to have multiple keys or nope?

**Comment by kangarko** [comment]
No, only a single Key.
