### ISSUE TITLE
1.16.4: Multi Channel Connection to DiscordSRV

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl#409]
Hiya having this issue where when I add multiple channels to connect to discordsrv In the CHATCONTROL config.

On reload it removes them all bar one.

BEFORE RELOAD:
![image](https://i.imgur.com/2REqBru.png)
![image](https://i.imgur.com/RQcQpBS.png)

After Reload:
![image](https://user-images.githubusercontent.com/16086663/103248438-7f855800-4962-11eb-8d08-0cea317b1f2f.png)

**Comment by ElBananaa** [comment]
Hey!
Try using only lowercased letters and don't use any special symbols like `-`.
It the error persists, please send us the `/chc debug` output file.

**Comment by Ash10744** [comment]
Yeah, the issue is still persistent. My channels are formatted with the dashes '-'

and I tried it with lowercase

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5749221/debug.zip)

**Comment by Ash10744** [comment]
The dashes work up to 3 channels then more than 3 channels removes them all. So the formatting is perfect it just seems to be limited on ChatControls side.

**Comment by ElBananaa** [comment]
> The dashes work up to 3 channels then more than 3 channels removes them all. So the formatting is perfect it just seems to be limited on ChatControls side.

Alright, thanks for the informations.
Kangarko will probably have a look at your issue in the next few days.

**Comment by kangarko** [comment]
You can only have connected one channel with one ChatControl Channel.

This is also a limitation of YAML files, you cannot have two keys of the same value:

apple: green
apple: red

will not work. The keys "apple" must be different.

**Comment by Ash10744** [comment]
Is there no work around to get all my channels into discordsrv then? 

I preferbly want all my channels logged in a single channel get me?

**Comment by ElBananaa** [comment]
Hey!

You should be able to do that in DiscordSRV main file: `DiscordConsoleChannelId: ""`

**Comment by Ash10744** [comment]
The console has all the errors etc not just the chat?

I use one channel for console logs and then the other for chat only

**Comment by ElBananaa** [comment]
> The console has all the errors etc not just the chat?
> 
> I use one channel for console logs and then the other for chat only

What I gave you above is for console logs.
Simply make 2 channels: one for the chat, one for the logs.

**Comment by Ash10744** [comment]
I dont think you're quite understanding what I'm saying. 

I have several channels in chatcontrol that need to be in the chat channel of discord not just one channel from chat control.

**Comment by ElBananaa** [comment]
> I dont think you're quite understanding what I'm saying.
> 
> I have several channels in chatcontrol that need to be in the chat channel of discord not just one channel from chat control.

Alright, yeah I misunderstood.
As Kangarko said, this is not possible for now.

**Comment by Ash10744** [comment]
Do you think it could be implemented? Cause I cannot be the only person who'd need this 👍

**Comment by kangarko** [comment]
Not right now, but you can disable our discord integration in Integration.Discord section of settings.yml and use DiscordSRV's one or any other
