### ISSUE TITLE
Whitelist domains/ip

### ISSUE THREAD

**Issue by Disorbs** [kangarko/ChatControl#41]
its not working this is how i have it down and i reloaded (/chc reload)
but when players or me type google.com it comes out like "google com" youtube com"

match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu)\b

ignore string google.com|yahoo.com|imgur.com|gyazo.com|youtube.com|youtu.be|minecraft.net

id 2

strip [\(\[\]\)]

handle as advertisement

**Comment by kangarko** [comment]
>**When url is entered in chat, all the dots are replaced by spaces (e.g. www.google.com -> www google >com)**
>This change is not coming from ChatControl. Essentials is known to do that, try adding your players >permission essentials.chat.url and essentials.msg.url for private messages.
