### ISSUE TITLE
Minecraft 1.16.4 - Questions regarding permissions nodes and localization

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#411]
First Question) Using the localization English file, it seems I can no longer reduce the overall size that ``/chc announce chat <message>`` takes up of chat, for example, in ChatControlPro, I was able to reduce the size to something like this 
https://imgur.com/a/AthhPja
``&6[Announcer] &a<message>``

For referance in ChatControlPro, I was able to do this by changing the default and making it look something like this:
```yml
Announcer:
  Message: '&6[Announcer]&r &e{message}'
```
**If this is still possible, how would I do it?** If not is it something that can be added?

----------------------------------------------------------------------

Second & Third Question) This is in regards to ``/toggle`` and ``/ignore``, after doing ``/chc perms`` and ``/lp tree`` to check permission nodes for ChatControlRed, it seems there are no bypass permissions for those commands, to give to staff on my server. Should people try to ``/ignore`` them or do ``/toggle chat`` or ``/toggle pm``, staff can still contact the player in-game even if they have chat toggled off or private messaging toggled off or tried to /ignore a staff member.

**If I am wrong and there are actually bypass permissions for these commands, can someone confirm what those permission nodes are? Thanks**

**Comment by ElBananaa** [comment]
Hey!

Regarding your first question, you should aready be able to edit the announce format under the announce part in the localizations.

Regarding your 2nd and third question, give your staff the permissions `chatcontrol.bypass.mute` to bypass chat/channel mute, and `chatcontrol.bypass.reach` to "send messages and private messages to players who ignore you, or have PMs disabled".
You can see the full list of perms here: https://github.com/kangarko/ChatControl-Red/wiki/Permissions.

**Comment by kangarko** [comment]
Closing, comment below if you still need help :)

**Comment by TheIntolerant** [comment]
Thanks for helping with the permissions issue, regarding the localizations issue I was having it seems I can only edit the "header".
As seen here, https://imgur.com/a/lbD8jyj


As it seems I cannot edit the Footer, or add a prefix to the chat announcement message. 
I personally would prefer if it was like this ``&6[Announcer] &a<message>``

Basically, if I had the ability to edit the footer of the announcement message in chat and possibly add a ``prefix``? to the announcement message. So that I could do something like...

**Example of what I am talking about**
I want to be able to do something like this?
```yml
Header: []
Footer: []
Announcement_prefix: `&6[Announcer]&r '
```
But as it stands right now, it seems I can only edit the Header.

By adding the ability to edit the footer and add a prefix to the announcement, I could change it so that my announcement messages followed this format, ``&6[Announcer] &a<message>``, that would be amazing.

Also thank you for taking the time to help me out!

**Comment by kangarko** [comment]
Done :)

Do this in the next version and you can rate the plugin [here](https://www.mc-market.org/resources/18217/) if you appreciated this!

<img width="839" alt="Screenshot 2020-12-31 at 08 25 48" src="https://user-images.githubusercontent.com/1918426/103399537-cbdabe80-4b41-11eb-8a7c-d14a8dd1cbe0.png">
