### ISSUE TITLE
Minecraft Version: There is no format for discord to game

### ISSUE THREAD

**Issue by Rexmen1** [kangarko/ChatControl#413]
So i was able to use discord chat and channels to work it out but now I'm having another issue where the format I'm using gets broken from discord to game. [suffix | prefix | name > msg] https://gyazo.com/3709fcbf0290c5208f3d8103b3455023
But works fine from game to discord.  [suffix | prefix | name > msg] https://gyazo.com/1374d35d3ab022f31dee01367779cb04

Its not working because there is no way I know so far or there is no option in plugin found in hours of finding to edit format for discord to game... There is formats for game to discord but no other way around....

Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

**Comment by Rexmen1** [comment]
https://hastebin.com/kewasaceli.php   [global-chat.yml]
https://hastebin.com/esapizifeh.yaml [setting.yml]

**Comment by Rexmen1** [comment]
Also tried all possible options dff like many many time
seted 
Format_Console: none 
Format_Console: "none"

in channels too and above everywhere
tried diff formats by adding new format file and all but still same
Format_Console: discord
Format_Console: "discord"

**Comment by james090500** [comment]
Format_Console formats the messages that appear in the minecraft console.

If you want to format discord -> Minecraft you need to use the "Format" option under the channel. In your case this is "admin-chat", "global-chat" and "help".

The easiest way is to use sender conditions. See line 43 of the "global-chat.yml" you sent ``Sender_Condition: '{sender_is_discord}'``. You can then add ``Sender_Condition: '{sender_is_player}'`` to the tags you DONT want to appear on discord and forma tthem appropiately.

**Comment by ElBananaa** [comment]
Hey!

Thanks @james090500 for answering him!

I think james said everything that had to be said.
Let me know if it helped you, or if you need anything else!

**Comment by kangarko** [comment]
Closing, let us know below if you need more help :)
