### ISSUE TITLE
1.16.4: AutoJoin not working

### ISSUE THREAD

**Issue by CoutovyLp** [kangarko/ChatControl#417]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

Hello. I have problem with autojoin.. I set up: 
chatcontrol.channel.autojoin.standard.read
chatcontrol.channel.autojoin.standard
chatcontrol.channel.autojoin.standard.write

but it´s not joining them to the channel.

**Comment by Yamamot00** [comment]
The autojoin permission is only saying to enter the X player automatically to that channel.
You also need to put the permission: chatcontrol.channel.join.standard.write so the plugin can understand that you have permission to join and have permission to autoJoin the channel.
The .write variable can Read and Write and the .read can only read the messages.

**Comment by ElBananaa** [comment]
Hey!

Thanks @Yamamot00 for answering him!
You said everything that had to be said. 

I'm closing this issue, feel free to open a new one if you need anything else!
