### ISSUE TITLE
1.16.4: Local chat broken.

### ISSUE THREAD

**Issue by m171717** [kangarko/ChatControl#419]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Hi, not sure the issue here. Local chat is completely broken here, either says nobody is in range or we can see other servers local chat. Any solution would be much appreciated. Attached our debug.zip as well.
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5752422/debug.zip)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true
> 
> Hi, not sure the issue here. Local chat is completely broken here, either says nobody is in range or we can see other servers local chat. Any solution would be much appreciated. Attached our debug.zip as well.
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5752422/debug.zip)

Hey!

Please update ChatControl and ProtocolLib and let us know if it fixes your issue.

**Comment by kangarko** [comment]
Closing, if you will face it again after updating comment below and tag ElBananaa :)
