### ISSUE TITLE
1.16: Unable to specify message group in command.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#424]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

ChatControl Red 10.1.12

Trying to use the command ``/chc message info timed global`` to get info on the global group but ChatControl outputs "Invalid argument. Run ``/chc ?`` for help." Checking the help documentation, it says to type ``/chc message <list/toggle/info/reload> <type> [group]``. 

No matter which way I try to type it, I'm not able to specify the ``global`` group in the message info / toggle / list command.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: false
> 
> ChatControl Red 10.1.12
> 
> Trying to use the command `/chc message info timed global` to get info on the global group but ChatControl outputs "Invalid argument. Run `/chc ?` for help." Checking the help documentation, it says to type `/chc message <list/toggle/info/reload> <type> [group]`.
> 
> No matter which way I try to type it, I'm not able to specify the `global` group in the message info / toggle / list command.

Hey!

There's no global group by default in the plugin.
All your groups are defined inside the `/plugins/ChatControlRed/rules/groups.rs` files.

**Comment by ElBananaa** [comment]
I'm closing this issue. Feel free to comment down below if your issue persits, or open a new ticket if you need anything else.
