### ISSUE TITLE
1.16.4: use jasonTexts in the api

### ISSUE THREAD

**Issue by loewenjunges** [kangarko/ChatControl#425]
Hi,
because using "net.md_5.bungee.api.chat.TextComponent" with ChatControlRed api is not possible.
Is it possible to use jasonTexts in the api?

e.g. Channel.findChannel(channel).sendMessage(e.getSender(), "{'text': 'This is a test', 'color': 'aqua'}");

You can specify only one string as the message.

**Comment by kangarko** [comment]
Hey! Not directly, you'd have to get online players in the channel using Channel#getOnlinePlayers() and then use player#spigot().sendMessage() for each of those via Spigot
