### ISSUE TITLE
1.16.4 Prefix_ explained

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#426]
I was busy editing the groups.rs file and I stumbled upon a variable that I couldn't find explained.

{warn_prefix}

What I found striking was the order. All others start with `prefix_` and this one from the groups.rs file is exactly the other way around. Is this a mistake or intentional?

**Comment by ElBananaa** [comment]
> I was busy editing the groups.rs file and I stumbled upon a variable that I couldn't find explained.
> 
> {warn_prefix}
> 
> What I found striking was the order. All others start with `prefix_` and this one from the groups.rs file is exactly the other way around. Is this a mistake or intentional?

Hey!

Yes, this is intentional. Actually, you can use `{warn_prefix}` and `{prefix_warn}`. Same for `{info_prefix}`, `{success_prefix}`, `{error_prefix}`, `{question_prefix}` and `{announce_prefix}`. These prefixes can be defined in your localization file, under the `Prefix:` part.
