### ISSUE TITLE
1.12.2: How to have different default message colors based on permissions/groups

### ISSUE THREAD

**Issue by Chappy202** [kangarko/ChatControl#429]
Good day,

How can I implement different default message colors based on permissions or groups?

For example, I want my normal players to chat in "white" by default. while all staff members type in "yellow"

**Comment by ElBananaa** [comment]
Hey!

You can do that using the format files.
Simply add a `Sender_Permission:` check under your message part,
Here's an example:
```
  message-default:
    Message: '&8&l» &r{message}'
    Sender_Permission: group.default
```
```
  message-staff:
    Message: '&8&l» &e{message}'
    Sender_Permission: group.staff
```
Then give your players the `group.default` permission, and give your staff the `group.staff` permission. (Don't forget to deny the `group.default` permission for staff groups, or their message will be shown twice.)

You can also do this using the `Sender_Condition:` feature, but it requires some knowledges in javascript.
For more informations about the different conditions that you can use, take a look at the wiki page: https://github.com/kangarko/ChatControl-Red/wiki/formats
