### ISSUE TITLE
chatcontrol.bypass.dupe.command node does not work

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#43]
I recently started experimenting with CHC v5 and discovered that if a player has the node `chatcontrol.bypass.dupe.command` he still gets the notification that he is not allowed to run the same command multiple times.

Side note: `chatcontrol.bypass.dupe.chat` seem to work as expected.

v5.2.6

**Comment by kangarko** [comment]
Hey, thanks for reporting.

It seems like you forget the plural -s at the end. It should be 'chatcontrol.bypass.dupe.command**s**'. Can you test against this? It works for me.

**Comment by EvilOlaf** [comment]
Works for me to. My fault. Thanks for the reply.

**Comment by kangarko** [comment]
Congratulations for updating to v5 by the way! :+1:

**Comment by EvilOlaf** [comment]
Well I did not to that yet. I just put the latest v5 into on my testing environment and I am now trying to convert the configs from v4 to v5.
Probably takes a while till I finished this and used it in production as my mood for doing this is disgustful low ^^

**Comment by kangarko** [comment]
Good luck then :) If anything comes up feel free to ask.
