### ISSUE TITLE
1.16.4: Join message sent on join (with delayJoinMessage: true in AuthMe)

### ISSUE THREAD

**Issue by tomhula** [kangarko/ChatControl#430]
Minecraft Version: 1.16.4
Plugin version: 10.1.12
MySQL: true
BungeeCord: false

I have set _delayJoinMessage_ in Authme to _true_ and _Chat_Listener_Priority_ to _HIGH_ in ChatControlRed.

Steps to reproduce:
1. Set _delayJoinMessage_ to _true_ in Authme.
2. Set _Chat_Listener_Priority_ to _HIGH_ in ChatControlRed.
3. Join to the server and the join message is sent even before login.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> Plugin version: 10.1.12
> MySQL: true
> BungeeCord: false
> 
> I have set _delayJoinMessage_ in Authme to _true_ and _Chat_Listener_Priority_ to _HIGH_ in ChatControlRed.
> 
> Steps to reproduce:
> 
> 1. Set _delayJoinMessage_ to _true_ in Authme.
> 2. Set _Chat_Listener_Priority_ to _HIGH_ in ChatControlRed.
> 3. Join to the server and the join message is sent even before login.

Hey!
Please try to play arround with the different `Chat_Listener_Priority` and let us know if using of them fixes the issue.

**Comment by kangarko** [comment]
Right now this is unsupported, this is something we can consider adding in the future
