### ISSUE TITLE
White color on menu (/chc color menu)

### ISSUE THREAD

**Issue by Reeferx7** [kangarko/ChatControl#433]
Hello, i think you forgot to add white color on menu, is possible to added on next update?

![iD3kFhC](https://user-images.githubusercontent.com/8740881/103379276-d2d7e180-4aed-11eb-82cf-9742b5aba25f.png)

thanks

**Comment by ElBananaa** [comment]
> Hello, i think you forgot to add white color on menu, is possible to added on next update?
> 
> ![iD3kFhC](https://user-images.githubusercontent.com/8740881/103379276-d2d7e180-4aed-11eb-82cf-9742b5aba25f.png)
> 
> thanks

Hey! I just tried to see if I have the same issue, and I don't.
Make sure you are using the latest version.
![image](https://user-images.githubusercontent.com/53318613/103379930-9ef9bd80-4ae7-11eb-9793-f99383cff7bf.png)

**Comment by Reeferx7** [comment]
yes i see the last update after this post sorry,
