### ISSUE TITLE
Adding of a permission tree for deleting messages

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#434]
### **1.** How it would benefit others?

*Basically, it would allow us to configure different permission levels for the remove message feature.
It's pretty useful since it'll avoid staff members to remove messages from members with the same group or a higher group than theirs.  You can't instantly completely trust an user, but in order to trust him, you need to give him responsabilities. Having to choose between giving full remove rights, or not giving anything at all isn't the best thing.* 
 

### **2.** What would happen if we won't implement this feature? How's your server being affected?

*My server wouldn't really be affected by the changes now since I don't have a lot of staff members, and I trust my actual staff team, but I can understand that this would become something pretty important for newcomers in a server staff team.*

**Comment by kangarko** [comment]
Thank you! Our current system is not designed to tag messages into player groups for now, but when I am doing larger code edits I can keep this in mind.
