### ISSUE TITLE
1.16.4: Console spam after update to 10.1.13

### ISSUE THREAD

**Issue by altruiis** [kangarko/ChatControl#435]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Step 1. Update from CHC 10.1.11 to 10.1.13
Step 2. Join the server
Step 3. The console will spam a warning only when a player is online. If the server is empty, it stops.

Here is the error: https://pastebin.com/hWxYKMeP

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true
> 
> Step 1. Update from CHC 10.1.11 to 10.1.13
> Step 2. Join the server
> Step 3. The console will spam a warning only when a player is online. If the server is empty, it stops.
> 
> Here is the error: https://pastebin.com/hWxYKMeP

Hey!
Please provide your debug file using `/chc debug`

**Comment by altruiis** [comment]
> 
> 
> > Minecraft Version: 1.16.4
> > MySQL: true
> > BungeeCord: true
> > Step 1. Update from CHC 10.1.11 to 10.1.13
> > Step 2. Join the server
> > Step 3. The console will spam a warning only when a player is online. If the server is empty, it stops.
> > Here is the error: https://pastebin.com/hWxYKMeP
> 
> Hey!
> Please provide your debug file using `/chc debug`

https://ufile.io/ydfj941z

**Comment by ElBananaa** [comment]
Thanks!

Please update your dependencies and your paper version. Also make sure that ChatControl is up-to-date on every server, and same for BungeeControl.

**Comment by kangarko** [comment]
Yeah just stop your whole network, update to 10.1.14 everywhere then start again.
