### ISSUE TITLE
1.16.4 Books filtering before signing

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#436]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true
CHC Version: 10.1.12

When a player writes a swear in a writable_book (book and quill), chh does see the swear but refuses to replace or deny the swear.
What does work (only once when writen):
- then warn
- then points

What does not work:
- then replace
- then deny

That means a player will receive a warning, points and thus a mute when writing. Since the word is not replaced, the player has no clue what he did wrong.
When the book is finalized by signing, the player receives yet another point for swearing.
When the group executes `then replace`, the word is replaced and the book can be signed.
However; when the group executes `then deny`, the signing is prevented. The swear word is not replaced, so it's still in the book.
This means, that the player won't sign the book. He is not forced to finalize it. He can now unsigned book with the swear in it. Once writen, it's not replaced nor denied.

The advantage may be that he is able to correct himself without rewriting the whole story.
The down side is that he can use the book with swears in it as long as he won't sign it.

**Comment by ElBananaa** [comment]
Hey!
As said on the wiki page, you can use `then deny` on book, but this will only prevent players from signing them.
About the `then replace` option, I don't know if this is possible.
You'll have to wait for Kangarko to get an answer about that.

**Comment by kangarko** [comment]
Hey, yes that is the intended sequence of the operators. You have to chose either using replace or denying the swears. What I recommend you simply replace all swears instead.

**Comment by x1p** [comment]
Unfortunately, that doesn't work either.
I have special book rules which do `then replace`
The console says it's replaced, but the text is still in the book.
So basically, there is not much difference between replace and deny.

The text will be replaced when signed, yes. But this is too late.
Nothing will stop players using unsigned books.

I tested version 8.9.x on this, and this works the same. I just haven't tested this scenario before.
So I guess I just have to coop with this.

Btw: some words are just too offensive to replace and let them know exactly what is filtered and what is not.

**Comment by kangarko** [comment]
@x1p shoot a quick video for you: https://www.loom.com/share/132b5b612cb54322af239391975efc00
