### ISSUE TITLE
1.16.4: Please stop asking for tos compliance, it's completely unnecesary

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#438]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

```
[23:51:55] [Server thread/INFO]: !-----------------------------------------------------!
[23:51:55] [Server thread/INFO]:  Welcome to ChatControl!
[23:51:55] [Server thread/INFO]:   
[23:51:55] [Server thread/INFO]:  Before you start using this product, you need to
[23:51:55] [Server thread/INFO]:  agree to our Terms of Service and complete a quick
[23:51:55] [Server thread/INFO]:  tour with '/chc tour' command.
[23:51:55] [Server thread/INFO]:   
[23:51:55] [Server thread/INFO]:  We recommend you complete this process before
[23:51:55] [Server thread/INFO]:  making any changes to your configuration.
[23:51:55] [Server thread/INFO]: !-----------------------------------------------------!
```

No matter how many times I verify with the command ```/chc tour mothman```, it keeps asking me to do the tour and verify.

It's asumed that when you purchase a product, there's going to be TOS, and you accept them wether you agree or not, the entire system shouldn't even be necesary.

Edit: Although it's well possible that I'm only getting this again and again due to https://github.com/kangarko/ChatControl-Red/issues/437

**Comment by ElBananaa** [comment]
Hey! It looks like this is something related to your setup.
Make sure to run `/chc tour start` then `/chc tour confirm` and then the latest command.

**Comment by MithrandirCraft** [comment]
> 
> 
> Hey! It looks like this is something related to your setup.
> Make sure to run `/chc tour start` then `/chc tour confirm` and then the latest command.

CHC says I already completed the tour. It will ask me to do it again next restart though.

:l

On the other hand, the plugin seems to be "working fine" (edit: more like working as configured) nevertheless, so I guess it's not that bad.

**Comment by ElBananaa** [comment]
> > Hey! It looks like this is something related to your setup.
> > Make sure to run `/chc tour start` then `/chc tour confirm` and then the latest command.
> 
> CHC says I already completed the tour. It will ask me to do it again next time though.
> 
> :l
> 
> On the other hand, the plugin seems to be "working fine" (edit: more like working as configured) nevertheless, so I guess it's not that bad.

Well, the real problem is that I cannot reproduce your issue.
Please provide your `/chc debug` output file.

**Comment by MithrandirCraft** [comment]
Will do. I'm out of time right now, I spent the entire day configuring CC :'D

**Comment by kangarko** [comment]
You don't have to execute any other command, you can just boot the server and type "chc tour mothman" from the console right away @ElBananaa. It will write it to data.db. Then type /stop and next time you start the server it will load this and not ask again. You can just copy and paste this data.db over your entire network.

**Comment by MithrandirCraft** [comment]
Here it is.

https://ufile.io/xg9qbm8u
