### ISSUE TITLE
1.16.4: Captcha?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#439]
Hi, how does please captcha command work? I can't see it.

```
		@Permission("Answer or regenerate captcha.")
		public static final String CAPTCHA = "chatcontrol.command.captcha";
```

**Comment by ElBananaa** [comment]
> Hi, how does please captcha command work? I can't see it.
> 
> ```
> 		@Permission("Answer or regenerate captcha.")
> 		public static final String CAPTCHA = "chatcontrol.command.captcha";
> ```

Hey!
This feature isn't implemented yet. So you are not able to use it now.
https://github.com/kangarko/ChatControl-Red/issues/1
