### ISSUE TITLE
ChatControl not working. No Debug info showing in console

### ISSUE THREAD

**Issue by Chris4418** [kangarko/ChatControl#44]
Im having an issue with Chat Control. i run 2 servers, one creative and the other Factions. The plugin is working flawlessly in Creative but on Factions its another story, the plugin does not work and is showing red when i use the command /pl. i went to the config file and enabled the Debug so i could get information from the console to see what my problem is exactly but there is no errors showing up. everything seems to be normal. I tried to copy the config over from Creative and paste it into my factions  but then same thing is occurring. Only thing i changed after copying and pasting was the broadcast messages.

**Comment by EvilOlaf** [comment]
If the plugin (or any other plugin ^^) does not load on startup there has to be any console output that shows why. If you are unsure about that you should paste a full startup log to pastebin or hastebin and put the link here.

**Comment by Chris4418** [comment]
http://pastebin.com/CVTkTXWr

here is the link. i managed to get most of the logs in but some. this should still help. from what i see, there is no info on the issue with the plugin. Essentials is outdated yes. but its the exact same on the Creative server but Chat Control still works.

**Comment by kangarko** [comment]
The log does not even shows ChatControl loading. Try installing the .jar again and post the full log till it says Done!. If you would like to keep  it private you can message me at spigot (don't forget to link to this page).

**Comment by Chris4418** [comment]
i tried reinstalling the plugin and its still coming up with the same problem. i removed any plugins that could be clashing with it as well but that doesn't seem to be the issue. the logs are the same as what i posted earlier as well.

**Comment by kangarko** [comment]
The log is not complete and it does not contain any mention of ChatControl. You need to post the log from "Loading libraries, please wait..." and "Starting minecraft server version..." till it says "Done!..."

**Comment by Chris4418** [comment]
I am unable to copy the whole log but from seeing it during boot up there is nothing about chat control at all. I will try find the boot logs when I can and I will post them

**Comment by kangarko** [comment]
Does the plugin appear on /plugins?

If you are unable to copy the whole log during startup, then you can copy the start part from the ´latest.log´ file inside ´logs´ folder.

**Comment by Chris4418** [comment]
Yeah it appears in /plugins but in res

**Comment by kangarko** [comment]
You mean red colored? Then there has to be a console message about it. Look up in the log files.

**Comment by EvilOlaf** [comment]
The log pasted above does not show CHC loading because it is not a full startup log. That's just a small cut.

**Comment by Chris4418** [comment]
I will look

**Comment by Chris4418** [comment]
I have found something. Will post it soon via  a link to pastebin

**Comment by Chris4418** [comment]
http://pastebin.com/Jjx2BR43

here are the logs. they werent showing up in the console though. i even played close attention to the start up files but i have found them in the logs.txt file

**Comment by kangarko** [comment]
You have a syntax error. Copy your settings.yml file content into http://yaml-online-parser.appspot.com/ and fix it accordingly.

**Comment by Chris4418** [comment]
i have just done that. came up clean, still showing an issue
i wll check every yml file and see if any others are causing this to happen
(sorry for late reply)

**Comment by Chris4418** [comment]
Update: http://yaml-online-parser.appspot.com/

is this any help. i got the command.yml from both my Factions and Creative server, both showing the same error. Yet the plugin in creative is working fine. i checked and fixed the settings.yml for Factions and that hasnt resolved the issue

**Comment by kangarko** [comment]
The link provided don't show the actual file. Please upload the file with errors to pastebin and I can try to fix it for you.

**Comment by Chris4418** [comment]
sorry for late reply again. i have been very busy over the Christmas and new year break but here are all the yml files. incase

handlers.yml: http://pastebin.com/snruQ4sa
settings.yml: http://pastebin.com/hXmw7QdA
chat.txt;        http://pastebin.com/fs2jsnGn
commands.txt: http://pastebin.com/FjxXM7MG
packets.txt;  http://pastebin.com/MscuDt6D
rules.txt: http://pastebin.com/3t85nkUp
signs.txt;   http://pastebin.com/944HVRn0

**Comment by Chris4418** [comment]
i should just be able to delete it and have it regenerate a new one?

**Comment by Chris4418** [comment]
this is the error i get when i post the commands.txt file into the Online YAML Parser

ERROR:

mapping values are not allowed here
  in "<unicode string>", line 11, column 71:
     ... ert &8[&7ID %ruleID&8] &7%player: &f%message

**Comment by kangarko** [comment]
Can you try putting the whole line in brackets ' '? Example: '[&7ID %ruleID] %player'

**Comment by Chris4418** [comment]
That section  is in brackets. The error that it was giving  me was for the colon at the end of "player" everytime i do put it back, gives me that error

**Comment by kangarko** [comment]
Can you post me the file?

**Comment by Chris4418** [comment]
http://pastebin.com/ge127NgH (commands.txt)

**Comment by kangarko** [comment]
Remove the last line 'match ^/(heal)' from that file, since that rule lacks additional operators.

**Comment by Chris4418** [comment]
Removed  the line, still showing an error when i logon to server.

**Comment by kangarko** [comment]
Can you post me the error?

**Comment by Chris4418** [comment]
i can try find the error in the logs. i will post an update if i can find it

**Comment by allemartinw** [comment]
I having the same error. I have "ChatControl v5.2.7". I cant write /chc. It dosent show up any help.

**Comment by kangarko** [comment]
I can't do anything unless I see some error message.
_Cleaned the thread_

**Comment by allemartinw** [comment]
Ohh, when i type /pl the "ChatControl" is red. Help?

**Comment by Chris4418** [comment]
Where would i find the logs forr the plugi?. Couldn't  find any in the main logs at all

**Comment by kangarko** [comment]
The logs are usually found in the logs/latest.log file in the main server folder.
If the plugin renders red in /plugins, post me the startup log please.

**Comment by Chris4418** [comment]
http://pastebin.com/p3QRAJwx its saying something about Advertising in Handlers and something abuot the Rules. even though i have checked over them and all seems fine. even used the YMAL Parser,

**Comment by Chris4418** [comment]
http://pastebin.com/U1yNwGtk

says something about Advertisements in Handlers and something about Rules, i have checked them on YAML Parser, Handlers comes up with the error about the Colon, Rules comes up clean.

**Comment by kangarko** [comment]
Because you must not uncomment the first lines in the handlers.yml file. They are only examples. The actual lines are at the bottom
See https://github.com/kangarko/ChatControl/commit/647b5551ce16da57bd5b4ea6cd54a42903489b39

**Comment by Chris4418** [comment]
thanks. that helped.

**Comment by kangarko** [comment]
Closing. Anyone having startup issue please make a new issue, and include the error log.
