### ISSUE TITLE
1.8.8 / 1.16.4 :  Sample in /chc color menu not working correctly

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#44]
It seems the sample doesn't work correctly in /chc color menu. Tested on both versions:

![image](https://user-images.githubusercontent.com/5664135/98982876-54fd4e00-2520-11eb-8f35-c0a912903ff7.png)
![image](https://user-images.githubusercontent.com/5664135/98982980-765e3a00-2520-11eb-93d1-9e67d0a5e4a6.png)

**Comment by kangarko** [comment]
Thank you I will fix that!
