### ISSUE TITLE
1.16.4 /chc inspect file <wrong_file>

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#440]
Minecraft Version: 1.64.4
MySQL: true
BungeeCord: true

Hi, I tried use /chc inspect file 
![image](https://user-images.githubusercontent.com/18662086/103388227-21927500-4b08-11eb-8221-f22c70aebd50.png)and used it for .core file and then my server crashed. I think that you maybe could add some preventation or some way to stop server crash if someone try to inspect wrong file. https://pastebin.com/VnMq4zcf https://pastebin.com/QB8qJ25V error logs

**Comment by kangarko** [comment]
We don't understand what files crash the server or not, you should only give this command to people you trust since it can also execute java methods.
