### ISSUE TITLE
1.16.4: Then replace doesn't work?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#442]
Minecraft Version: 1.64.4
MySQL: true
BungeeCord: true

Hi, is it possible that "then replace" doesn't work?
![image](https://user-images.githubusercontent.com/18662086/103389157-6967cb00-4b0d-11eb-8f68-c5fde6ff9cfc.png)
```
#kokot
match (k+(\W|\d|_)*o+(\W|\d|_)*k+(\W|\d|_)*o+(\W|\d|_)*t+(\W|\d|_)*)
name swear
group swear
then replace srdíčko
then sound <AMBIENT_CAVE>
```

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.64.4
> MySQL: true
> BungeeCord: true
> 
> Hi, is it possible that "then replace" doesn't work?
> ![image](https://user-images.githubusercontent.com/18662086/103389157-6967cb00-4b0d-11eb-8f68-c5fde6ff9cfc.png)
> 
> ```
> #kokot
> match (k+(\W|\d|_)*o+(\W|\d|_)*k+(\W|\d|_)*o+(\W|\d|_)*t+(\W|\d|_)*)
> name swear
> group swear
> then replace srdíčko
> then sound <AMBIENT_CAVE>
> ```

Hey!
We can't provide any support with the "informations" you provided.
Please provide your debug file.
Also, as I can see, your screen is pretty useless. You show us the word "kurva" in it, while the section from your rules checks for the word "kokot".
Also, you should consider changing the name to a different one. I'm pretty sure each name must be unique.

**Comment by bobhenl** [comment]
Here's word "kokot".
![image](https://user-images.githubusercontent.com/18662086/103389870-b9e12780-4b11-11eb-888f-beaecba666c5.png)
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5756209/debug.zip)

And about name I answered in second thread.

**Comment by ElBananaa** [comment]
Thank you.
It looks like your format is completely broken. Make sure your rules are working correctly. Also make sure there's no errors either in the plugin's error.log file, or in the console.

**Comment by bobhenl** [comment]
![image](https://user-images.githubusercontent.com/18662086/103390182-4809dd80-4b13-11eb-9deb-a20ffd146206.png)

Weird is that as admin it's normally replaced... but when I type it as player it isn't. Same word typed into chat.

**Comment by bobhenl** [comment]
[error.log](https://github.com/kangarko/ChatControl-Red/files/5756230/error.log)
Error

**Comment by kangarko** [comment]
The rule contains "then replace" but the part of the message has already been replaced because the rule also uses the "swear" group which did replace it previously. 

Either remove "then replace" from the rule or remove "then replace @prolong *" from the "swear" group in groups.rs.
