### ISSUE TITLE
1.16.4 /chc rule toggle swear doesn't work?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#443]
Minecraft Version: 1.64.4
MySQL: true
BungeeCord: true

Hi, I think that chc rule toggle swear doesn't work, look on my example:
![image](https://user-images.githubusercontent.com/18662086/103389215-d8ddba80-4b0d-11eb-95d1-1a4a73531583.png)

```
#deb
match (d+(\W|\d|_)*e+(\W|\d|_)*b+(\W|\d|_)*(i|o)+(\W|\d|_)*)
name swear
group swear
then sound <AMBIENT_CAVE>
```

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.64.4
> MySQL: true
> BungeeCord: true
> 
> Hi, I think that chc rule toggle swear doesn't work, look on my example:
> ![image](https://user-images.githubusercontent.com/18662086/103389215-d8ddba80-4b0d-11eb-95d1-1a4a73531583.png)
> 
> ```
> #deb
> match (d+(\W|\d|_)*e+(\W|\d|_)*b+(\W|\d|_)*(i|o)+(\W|\d|_)*)
> name swear
> group swear
> then sound <AMBIENT_CAVE>
> ```

Please provide us your debug file.
Use a unique name for each rule,
Make sure you don't have any bypass permission.

**Comment by bobhenl** [comment]
but what if I wanna enable whole group, not just name? Whole group swear.
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5756208/debug.zip)

I wanna make night chat after 22pm, so I wanna execute command automatically that will enable all swearings.

**Comment by ElBananaa** [comment]
> but what if I wanna enable whole group, not just name? Whole group swear.
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5756208/debug.zip)
> 
> I wanna make night chat after 22pm, so I wanna execute command automatically that will enable all swearings.

Thanks.
You can use the same group, but not the same name.
Also, as I said, make sure to test it without any bypass permission. Since you could spy the swear, it means you have a bypass permission.

**Comment by bobhenl** [comment]
but I spied it as me, I had there "Tester" warez account to test it and this account doesn't have special permissions.  So it isn't due to permissions.

About name, I used it due to `/chc rule toggle  ` cmd supports only names, not groups :/  How can I make then this?

> I wanna make night chat after 22pm, so I wanna execute command automatically that will enable all swearings.

**Comment by kangarko** [comment]
Thanks for your suggestion, right now only individual rules are supported. I can have a look into expanding this for groups in the future but right now we don't have time for this, sorry.

You can just create that automatic command for all rules and give them a unique name.
