### ISSUE TITLE
Channel specific permission to use color or ability to disable color chat in a channel

### ISSUE THREAD

**Issue by NerdyBirder** [kangarko/ChatControl#444]
Being able to set up permissions to use colors in a channel would be a nice way to clean up our chat. Right now on my server we have about 4 channels that are used constantly but when someone has the /chc color menu setup it is hard to pick out one channel from the global chat. If we could disable color in the channels other than our global it would make it soooo much easier to see one channel from another. 

I can tell my members to not use color in those channels or to use the channel's chat color code in front of their chat but that is really cumbersome and hard to remember.

**Comment by kangarko** [comment]
Thanks, you can actually just create rules for that:

match &[0-9a-fk-orA-FK-OR]+
require channel standard
then replace
then warn No colors in standard channel!

That will block all & colors in the standard channel. You can just customize the regex to your needs. Here's a regex for HEX:

match #((?:[0-9a-fA-F]{3}){1,2})

**Comment by NerdyBirder** [comment]
I wasn't able to get this to work when someone had the gui color enabled. It blocked my color codes when i used the code before my message because i don't have a color setup through the gui but when my staff tried to use a color code before their message while having the light blue color from the gui color menu it just blocked the green color code but still sent the message in light blue

**Comment by kangarko** [comment]
I understand, well I am so sorry I was not able to help. Seems like it's doable right now, I'll leave a note in the todo list when I have time.

**Comment by NerdyBirder** [comment]
awesome thank you for looking into adding this feature! it will really help me in my server if you can figure out a way to block color in certain channels :)
