### ISSUE TITLE
1.16.4: Forwarding message to only specific servers?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#447]
Hi, when we can forward message across whole bungee using this:
![image](https://user-images.githubusercontent.com/18662086/103420193-68c74700-4b96-11eb-9e0d-b79dcc5e3822.png)

Could we also forward specific messages to just specific servers, so for ex. to just survival somehow?

**Comment by ElBananaa** [comment]
> Hi, when we can forward message across whole bungee using this:
> ![image](https://user-images.githubusercontent.com/18662086/103420193-68c74700-4b96-11eb-9e0d-b79dcc5e3822.png)
> 
> Could we also forward specific messages to just specific servers, so for ex. to just survival somehow?

Hey!
I don't think this is possible for now, but why would you need this feature? Simply created a timed message on that server without the bungee variable.

**Comment by bobhenl** [comment]
I wanted to forward 1 message that is same on two servers to another server too, bust just to the one.

**Comment by ElBananaa** [comment]
> I wanted to forward 1 message that is same on two servers to another server too, bust just to the one.

Well, simply copy that message inside the other server timed.rs file. :)

**Comment by bobhenl** [comment]
Yeah I know I can do this 😅 just wanted to do it like with "bungee" option that I can have message just on one server and get it forwarded to another, so I don't need to edit it on multiple servers if I decide to change message.

**Comment by ElBananaa** [comment]
That would be a great feature, however, as I said, afaik, this isn't possible for now.

**Comment by kangarko** [comment]
<img width="630" alt="Screenshot 2021-01-04 at 18 25 54" src="https://user-images.githubusercontent.com/1918426/103561777-4bf28280-4eba-11eb-898a-84deb6955036.png">

You can use the /chc forward command to send messages only to a certain server

**Comment by bobhenl** [comment]
But I wanna send messages kangarko, not commands. Messages from timed messages file. And not across all servers on bungee, but only to specific ones.

**Comment by kangarko** [comment]
Sorry I'm afraid that's not possible right now, I can put this onto our todo list but there's no plan adding this at the moment.
