### ISSUE TITLE
1.16.4: Disabling channel join quit messages

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#449]
Where/How do I disable channel join and quit messages?

**Comment by ElBananaa** [comment]
> Where/How do I disable channel join and quit messages?

Hey!
Happy new year!

You should be able to disable the join/quit messages from each channel by editting these lines in your localization file:
`Notification: '&8[&2+&8] &7Player {player} has joined ''{channel}'' channel.'` to `Notification: 'none'`
and `Notification: '&8[&4-&8] &7Player {player} has left ''{channel}'' channel.'` to `Notification: 'none'`
