### ISSUE TITLE
Dynamic JSON adds to chat formatter

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#45]
I am currently experimenting with alternative ranks for players and was worried about if there is a chance for adding hover texts to the chat formatter.

This hover text should be dynamic and should adapt itself to the prefix that was given from a permission plugin through vault.
So for example if a player has the rank `Moderator` there should be a mouse hover text like `Be aware,  he will bite you`. Other prefixes bring other hover texts or JSON stuff in general with them.
Surely this JSON stuff has to be predefined somewhere and be selected at purpose as it cannot come from vault too.

I saw that CHC premium offers support for JSON and I am wondering if something like this would be possible too.

Thanks for reading.

**Comment by kangarko** [comment]
There is no native support for json usage. In premium, you can start the message with [JSON] to indicate that it should be handled as that type. Somewhere it is possible to workaround this by sending the player '/tellraw' command, but this is not possible in chat formatter, sorry.
