### ISSUE TITLE
Nick support on plotsquared chat

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#451]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
Using plugin like nicky, it was working on plotsquared 5 plot chat. Chatcontrol doesn't

2. What would happen if we won't implement this feature? How's your server being affected?
I would like chatcontrol nick working on plot chat on plotsquared 5, it will make the roleplayer happy again

**Comment by ElBananaa** [comment]
Hey!
This as already been suggested/reported: #359.
Closing this suggestion an quoting it there.
