### ISSUE TITLE
1.16.4: Info in console bungeecord

### ISSUE THREAD

**Issue by StarozytnySky** [kangarko/ChatControl#452]
When i install BungeeControl-Red in console i have message https://pastebin.com/Hj258Bd0.
Is there a way to turn it off?

**Comment by ElBananaa** [comment]
> When i install BungeeControl-Red in console i have message https://pastebin.com/Hj258Bd0.
> Is there a way to turn it off?

Hey!
You should be able to turn these informations off by remove the `Packet` word in your BungeeControl debug part.
It should look like: `Debug: []` after.
