### ISSUE TITLE
1.16.4 Writer logs/chat.log

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#453]
CHC 8.x had the writer function which could log all chat messages into /logs/chat.log. This includes all chat from plotsquared's plot chat. This makes following conversations a lot easier. Because the normal server log also contains commands.

CHC 10 does not seem to log all chats. It only seems to store in these 2 cases:
- filtered chats (in the mysql database)
- when filtered via the rule `then log` in a separate log.

Am I missing a setting or is this intentional?
Is the chat.log coming back in near future?

**Comment by ElBananaa** [comment]
> CHC 8.x had the writer function which could log all chat messages into /logs/chat.log. This includes all chat from plotsquared's plot chat. This makes following conversations a lot easier. Because the normal server log also contains commands.
> 
> CHC 10 does not seem to log all chats. It only seems to store in these 2 cases:
> 
> * filtered chats (in the mysql database)
> * when filtered via the rule `then log` in a separate log.
> 
> Am I missing a setting or is this intentional?
> Is the chat.log coming back in near future?

Hey!
Happy New Year!
The new logging system allows you to check the logs ingame using the command: `/chc log chat`.
This feature can be configured in your settings file under the `Log:` part.

Regarding the `then log` rule, it was replaced by `then write`.
Then log is now used to log a message in the console, and then write is used to write a message in the desired file(s).

For more informations regarding the rules, take a look at this wiki page: https://github.com/kangarko/ChatControl-Red/wiki/Rules

For more informations regarding the new logging system, take a look at this wiki page: https://github.com/kangarko/ChatControl-Red/wiki/Logs

**Comment by x1p** [comment]
> Regarding the then log rule, it was replaced by then write

Ah yes, I'm still used to the v 8.x terminology. You'll get the point though.

> This feature can be configured in your settings file under the Log: part.

This requires channels to be enabled! Default chat via another plugin does not seem to work, sadly.
So this bypasses CMI, Essentials, Plotsquared... and even default minecraft.

**Comment by kangarko** [comment]
You can actually create a rule

match .*
dont verbose
then log XXX

that will match all messages and log them into a file
