### ISSUE TITLE
1.16.4: Randomizing timed messages?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#454]
Hi, is it possible to randomize timed messages somehow like it was in Chc8?
```
  # Display styles.
  # 0 - From first to the last message from the list.
  # 1 - Randomly picks up from the list.
  # 2 - Random, but messages won't repeat until every message has been broadcasted.
  #
  Mode: 2
```
Something similar? Now only the first mode is activated, but can we change it?
https://pastebin.com/KbbFWwgY
It spammed me the first group - winter almost all time from some reason. Another question is, how it really works? Will it pick from all groups? Or will it pick all from first, then it will continue to second group, then to third, or is it executing all groups in same time?

**Comment by ElBananaa** [comment]
> Hi, is it possible to randomize timed messages somehow like it was in Chc8?
> 
> ```
>   # Display styles.
>   # 0 - From first to the last message from the list.
>   # 1 - Randomly picks up from the list.
>   # 2 - Random, but messages won't repeat until every message has been broadcasted.
>   #
>   Mode: 2
> ```
> 
> Something similar? Now only the first mode is activated, but can we change it?
> https://pastebin.com/KbbFWwgY
> It spammed me the first group - winter almost all time from some reason. Another question is, how it really works? Will it pick from all groups? Or will it pick all from first, then it will continue to second group, then to third, or is it executing all groups in same time?

Hey!
Happy New Year!

According to the wiki, the messages should already be selected randomly. (https://github.com/kangarko/ChatControl-Red/wiki/Messages)

If it actually doesn't, let me know, and I'll leave this issue open so Kangarko could take a look at it.

**Comment by bobhenl** [comment]
I though that on wiki is:

> We read the file from top to bottom. Each group can have certain conditions when to show a certain message. Such as different messages for VIP players, etc. (but so much more!) The program reads all groups from top to bottom and if the first group's conditions don't allow it to show, it moves down to the next one, and so on, until it finds the first group where it can show, and then it stops.

But I don't really understand it, it seems that group winter is appearing almost instantly, and another ones goes really from top to bottom, but not sure, ideally I wanna mix it

**Comment by bobhenl** [comment]
And I think something is broken here... it shows only message about snow (so winter one) on my server, nothing else.
![image](https://user-images.githubusercontent.com/18662086/103446284-31cc6080-4c7e-11eb-80a8-5effa6276c50.png)

![image](https://user-images.githubusercontent.com/18662086/103446285-3264f700-4c7e-11eb-9edd-20c39592a229.png)

Is there any mistake? https://pastebin.com/KbbFWwgY

**Comment by kangarko** [comment]
Ahoj,

I recommend using "delay" for these groups, so that you use

group winter
delay 5 seconds
 
group project
delay 10 seconds

etc. That way the plugin will ignore the first group and move into the next one once it goes through the file to send these messages. If you have multiple messages in "message" operator their order is random.

**Comment by bobhenl** [comment]
Ok, thanks. Check my other issues please, I responded to them now, even these you closed.

**Comment by bobhenl** [comment]
Just a little question about it, why it will ignore the first group when there's delay 5 and the second is 10? The first will be triggered twice, or?

**Comment by ElBananaa** [comment]
> Just a little question about it, why it will ignore the first group when there's delay 5 and the second is 10? The first will be triggered twice, or?

When he says that the plugin will ignore the first group, it means that once the message of the first group is sent, it'll ignore the first group and send the message of the second group. Once the message of the 2nd group is sent, it'll ignore the 2 firsts groups and send the message of the 3rd group...

When all the groups messages are sent, it'll repeat this cycle.

**Comment by ElBananaa** [comment]
> > Just a little question about it, why it will ignore the first group when there's delay 5 and the second is 10? The first will be triggered twice, or?
> 
> When he says that the plugin will ignore the first group, it means that once the message of the first group is sent, it'll ignore the first group and send the message of the second group. Once the message of the 2nd group is sent, it'll ignore the 2 firsts groups and send the message of the 3rd group...

When all the groups messages are sent, it'll repeat this cycle.

**Comment by bobhenl** [comment]
I was testing it a little bit and it's behavior is a little bit weird.

With delays (small values there, in settings Timed_Delay: 1 seconds + here is file of timed messages https://pastebin.com/Kiid2Emf), and now from some reason it doesn't wait to all other groups be send, but it sends multiply group "Premium 2"
![image](https://user-images.githubusercontent.com/18662086/105460416-068cce00-5c8c-11eb-8c49-387a3d986159.png)


With deleted delays it shows just the first group
![image](https://user-images.githubusercontent.com/18662086/105460712-80bd5280-5c8c-11eb-9a8c-a070b20713dc.png)


And if I wanna really randomizing them, so every group will have same chance on being sent, how to do it? Even same delay doesn't help (still sending the first one).

**Comment by bobhenl** [comment]
I think that main problem is that when group contains just one message, then other groups won't be displayed... cause the first one is still executed forever after. This is probably how it shouldn't work?

**Comment by kangarko** [comment]
Is this still going on for the latest version? Messages are iterating for me correctly.

<img width="644" alt="Screenshot 2021-02-02 at 18 24 21" src="https://user-images.githubusercontent.com/1918426/106638186-e3afc300-6583-11eb-8add-c8c7561a195f.png">

**Comment by bobhenl** [comment]
And about this one, isn't this problem?

>  think that main problem is that when group contains just one message, then other groups won't be displayed... cause the first one is still executed forever after. This is probably how it shouldn't work?

**Comment by kangarko** [comment]
When the group contains just one message and NO operators, then yes, no other groups will be shown. 

This is because we only show a message from the first _valid_ group, by valid I mean the first group that has operators enabling us to send it. You can disable this now in Messages section of settings.yml
