### ISSUE TITLE
1.16.4: Rule creator wizar finish output messages broke

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#455]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

1. Create a new rule using /chc rule create
2. See that: https://prnt.sc/we6hti

**Comment by ElBananaa** [comment]
Hey!
Happy New Year.

Thanks for reporting this issue!
I'll leave it open so Kangarko could take a look at it.

**Comment by kangarko** [comment]
Thanks, just replace it with {prefix_success}
