### ISSUE TITLE
Make /spy and /nick /realname can be deactivated

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#458]
Many features of chc can be deactivated. It would be nice if this gets also be able for /spy /nick and /realnem so the plugin dont register this commands to my server. currently i have to block the commands /nick /spy /realname to hide it completely. It would be nice if thats gets imprved. the next thing is, it would be nice if i can disable auto spy without having to revoke the permission. this makes my permission setup very ugly,

**Comment by ElBananaa** [comment]
> Many features of chc can be deactivated. It would be nice if this gets also be able for /spy /nick and /realnem so the plugin dont register this commands to my server. currently i have to block the commands /nick /spy /realname to hide it completely. It would be nice if thats gets imprved. the next thing is, it would be nice if i can disable auto spy without having to revoke the permission. this makes my permission setup very ugly,

Hey!

You should be able to disable the /nick and /realname commands in your settings file, under the `Tag:` part.
Also remove the command alias for `/nick` in your `/plugins/ChatControlRed/rules/command.rs` file. This should be located under the `# Command aliases.` comment.

Regarding the spy feature, you can configure/disable it under the `Spy:` part in the settings file.
Regarding the permission, I think someone already asked about it (I'm not sure tho). The fact is that your permissions aren't meant to be shown to everybody. This makes the auto-spy system more flexible.
Also, I don't think the fact that it makes your permissions ugly is reason good enough to make a such change to this system. However, this is only my own opinion.

I'll leave this issue open so Kangarko could take a look at it and give you a proper answer.

**Comment by DevJoey** [comment]
Nope i cannot disable it. and i cannot remove all aliases because it will throw error. it must me an enable: false key there is no

**Comment by broken1arrow** [comment]
> > Many features of chc can be deactivated. It would be nice if this gets also be able for /spy /nick and /realnem so the plugin dont register this commands to my server. currently i have to block the commands /nick /spy /realname to hide it completely. It would be nice if thats gets imprved. the next thing is, it would be nice if i can disable auto spy without having to revoke the permission. this makes my permission setup very ugly,
> 
> Hey!
> 
> You should be able to disable the /nick and /realname commands in your settings file, under the `Tag:` part.
> Also remove the command alias for `/nick` in your `/plugins/ChatControlRed/rules/command.rs` file. This should be located under the `# Command aliases.` comment.
> 
> Regarding the spy feature, you can configure/disable it under the `Spy:` part in the settings file.
> Regarding the permission, I think someone already asked about it (I'm not sure tho). The fact is that your permissions aren't meant to be shown to everybody. This makes the auto-spy system more flexible.
> Also, I don't think the fact that it makes your permissions ugly is reason good enough to make a such change to this system. However, this is only my own opinion.
> 
> I'll leave this issue open so Kangarko could take a look at it and give you a proper answer.

Is it this you mean banana? https://github.com/kangarko/ChatControl-Red/issues/402#issuecomment-752989150

**Comment by ElBananaa** [comment]
> > > Many features of chc can be deactivated. It would be nice if this gets also be able for /spy /nick and /realnem so the plugin dont register this commands to my server. currently i have to block the commands /nick /spy /realname to hide it completely. It would be nice if thats gets imprved. the next thing is, it would be nice if i can disable auto spy without having to revoke the permission. this makes my permission setup very ugly,
> > 
> > 
> > Hey!
> > You should be able to disable the /nick and /realname commands in your settings file, under the `Tag:` part.
> > Also remove the command alias for `/nick` in your `/plugins/ChatControlRed/rules/command.rs` file. This should be located under the `# Command aliases.` comment.
> > Regarding the spy feature, you can configure/disable it under the `Spy:` part in the settings file.
> > Regarding the permission, I think someone already asked about it (I'm not sure tho). The fact is that your permissions aren't meant to be shown to everybody. This makes the auto-spy system more flexible.
> > Also, I don't think the fact that it makes your permissions ugly is reason good enough to make a such change to this system. However, this is only my own opinion.
> > I'll leave this issue open so Kangarko could take a look at it and give you a proper answer.
> 
> Is it this you mean banana? [#402 (comment)](https://github.com/kangarko/ChatControl-Red/issues/402#issuecomment-752989150)

Not exactly, and that's what he means neither I guess. That's why I'll leave this ticket open so Kangarko could take a look.

**Comment by kangarko** [comment]
To disable Spy command registering, set Spy.Apply_On to [] in settings.yml. To disable Real Name command, remove "nick" from Tag.Apply_On. And finally to disable /nick just look up that command in command.rs somewhere and remove the rule.
