### ISSUE TITLE
1.16.4: API Setting removing checking nick/prefix/suffix 

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#459]
I have a simple question. I will make a cool plugin where the user can choose a cool prefix in a gui. executing a command is simple unprefessional. so here is my question. is there an API for setting a nick/prefix/suffix? it would be nice if this would be exists. so i can simple hook in chc

**Comment by kangarko** [comment]
Hey, you can use PlayerCache#findPlayer and then the setTag() method in ChatControl
