### ISSUE TITLE
MySQL information duplicate

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#46]
It seems the MySQL information is in both the mysql.yml file as well for settings.yml, not sure if intended, thought to give a headsup ^^

**Comment by kangarko** [comment]
It's intended. some people asked for this since they share their settings.yml with others and wanted to keep mysql logins out. there's an option in mysql section of settings.yml to not use that file, then you can remove it

**Comment by Sikatsu** [comment]
Makes sense, thanks!
