### ISSUE TITLE
1.16.4 Replying on emails works too good :P 

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl#461]
Hey, when you once click reply to an email all the mails from that point (also with /mail new) go to the same player, whatever you do. So for example I get a mail from Apple saying 'Hello' I click reply, that works fine. Then I want to send a mail to Pear , I type /mail new, sign it but then it sends it to Apple.

**Comment by ElBananaa** [comment]
Hey!
Happy New Year!

Thanks for letting us know about this issue. Next time, please follow the bug-report format.

**Comment by kangarko** [comment]
Thanks will be fixed, funny bug haha!
