### ISSUE TITLE
@mentions dont work accross servers. (Bungee)

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl#463]
Minecraft Version: 1.16.4 PaperMC
MySQL: true
BungeeCord: true

Pastebin not needed, simple issue...

Latest release of CHR from MC Market.
![image](https://user-images.githubusercontent.com/51737378/103448451-126d1c00-4cee-11eb-8e31-b32da20007cb.png)
Sound notifications work fine on local server, but they dont work from one sever to another via Bungee

EDIT: It's not the sounds that are not working, the system simply does not register and detect username mentions when sent / received through a bungee channel.

**Comment by kangarko** [comment]
Thanks, yeah this is still a limitation of sound notify, I can look into adding this system in the future.

**Comment by LeehamElectronics** [comment]
> 
> 
> Thanks, yeah this is still a limitation of sound notify, I can look into adding this system in the future.

Sorry it's not the sounds, it just does not work in general, if you look in the chat, my username does not get highlighted in green as it should, the system just does not register when going through a bungee channel. Perhaps when the program is checking for username mentions it ignores messages received from bungee channels?

**Comment by kangarko** [comment]
Thanks, next version will add a beta support for sound notify through BungeeCord and for nicknames.
