### ISSUE TITLE
1.16.4| death for pvp not work as i should. Give wrong message 

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#464]
And now when pvp you get # Require the player to by killed by a hand (own i fix check debug). even if you has a item in hand. Work in older versions.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5759940/debug.zip)

Os: Linux java 11
CHC: 10.1.1.14
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

Edit fixed `[killer_item] not work, only [item] `

**Comment by james090500** [comment]
You dont have a killer_item variable in your variable folder.

Create a file called "killer-item.yml" in your "variables" folder and paste this inside of it.

https://paste.gg/p/anonymous/c9ebb54b84b643cc8b5f147c1b8b4e2c

Reload CHC and it should work.

**Comment by broken1arrow** [comment]
> You dont have a killer_item variable in your variable folder.
> 
> Create a file called "killer-item.yml" in your "variables" folder and paste this inside of it.
> 
> https://paste.gg/p/anonymous/c9ebb54b84b643cc8b5f147c1b8b4e2c
> 
> Reload CHC and it should work.

Oo, miss see i need fix that part. Thanks.

**Comment by ElBananaa** [comment]
> > You dont have a killer_item variable in your variable folder.
> > Create a file called "killer-item.yml" in your "variables" folder and paste this inside of it.
> > https://paste.gg/p/anonymous/c9ebb54b84b643cc8b5f147c1b8b4e2c
> > Reload CHC and it should work.
> 
> Oo, miss see i need fix that part. Thanks.

Hey!
Happy New Year!

As it seems this is something wrong on your side, I'm closing this issue. Feel free to keep sending messages down below if you still need help.

**Comment by broken1arrow** [comment]
> > > You dont have a killer_item variable in your variable folder.
> > > Create a file called "killer-item.yml" in your "variables" folder and paste this inside of it.
> > > https://paste.gg/p/anonymous/c9ebb54b84b643cc8b5f147c1b8b4e2c
> > > Reload CHC and it should work.
> > 
> > 
> > Oo, miss see i need fix that part. Thanks.
> 
> Hey!
> Happy New Year!
> 
> As it seems this is something wrong on your side, I'm closing this issue. Feel free to keep sending messages down below if you still need help.

Yes , i change title and fix my first post. 

Is in this version, it use wrong msg, I have one when players use hand to kill players and for use weapon (it not use others only one msg no mater if player has sword/axe or not). I not remember if it was 12 i use before update to 14, and my settings work in that version.

**Comment by kangarko** [comment]
Sorry but do you still have a problem? I don't quite understand if yes, please describe what's the current issue below.

**Comment by broken1arrow** [comment]
> Sorry but do you still have a problem? I don't quite understand if yes, please describe what's the current issue below.

Something has change i latest version. 

So if I use this in the file, it ignore all other pvp death in the death massage now.

```
# Require the player to by killed by a hand.
group playerhand
require cause ENTITY_ATTACK
require killer player
message:
- &c{killer}&7 tog rak höger på&a {player}
```

**Comment by kangarko** [comment]
Yeah that will execute for all player vs player kills, if you have any more specific conditions then you need to put them above this.

**Comment by broken1arrow** [comment]
> Yeah that will execute for all player vs player kills, if you have any more specific conditions then you need to put them above this.

Soo how I set hand/fist variable?

**Comment by kangarko** [comment]
Perhaps you can have a look into our wiki, such as using "require killer item" condition

**Comment by broken1arrow** [comment]
> Perhaps you can have a look into our wiki, such as using "require killer item" condition



> Perhaps you can have a look into our wiki, such as using "require killer item" condition

Soo have use multiply ignore killer item , will see if that work with out breaking the plugin (i know i some vanilla events for catch this, but i think not spigot has support for this) :)
