### ISSUE TITLE
Anti Bot feature does not work.

### ISSUE THREAD

**Issue by SwagaNout297** [kangarko/ChatControl#47]
Hi,
I experienced alot of bot attacks since I made my server and decided to find a perfect plugin that suits my needs especially on chat formatting. So when I added the plugin I tested most of the features except and I saw that its good but when a Bot Attack occured on the server, multiple random accounts joined without ChatControl stopping them with its Anti Bot feature.
What could cause the problem?

**Comment by kangarko** [comment]
ChatControl is not mainly developed to stop bot attacts. It's only feature to *lower* bot attacks is the login delay feature which will prevent the same player rejoining quickly, but it won't prevent series of different account attacking the server. 

Personally, I found a combination of NoCheatPlus along with a plugin developed specially for that purpose, like AntiJoinBot, a suitable solution.
