### ISSUE TITLE
tablist and tag weight support

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#470]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)

this is to add priority support to prefix and nicks
luck perms has his weight system that can help this to use priority the tab list
weight.<weight>   or   prefix.<weight>.<name>

2. What would happen if we won't implement this feature? How's your server being affected?

this can effect servers that there is no more need for a nick, tablist and tag plugin and it's can handle pretty much all of them

**Comment by FakEEE14** [comment]
and chatcontrol don't have a placeholder for nicknames to use it on tablist plugin or nametag plugins so /nick on chatcontrol change all of the others it's going to be great

**Comment by ElBananaa** [comment]
> and chatcontrol don't have a placeholder for nicknames to use it on tablist plugin or nametag plugins so /nick on chatcontrol change all of the others it's going to be great

Hey!
Happy New Year!

ChatControl does have a placeholder that can be used on tablist/nametag plugins: `{chatcontrolred_nick}`.
You can find the plugin placeholders here: https://github.com/kangarko/ChatControl-Red/wiki/Variables

**Comment by FakEEE14** [comment]
but it's going to be great to add this priority by weight

**Comment by kangarko** [comment]
Thanks, interesting idea, however there's no plans adding this right now due to other things.
