### ISSUE TITLE
1.16.4: Local chat, town chat etc. being send over bungee, while Bungee: false is used.

### ISSUE THREAD

**Issue by Managering** [kangarko/ChatControl#471]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

    local:
      Format: '&e[L] &8({luckperms_prefix}{luckperms_suffix}&8) {player_displayname}&e:&f {message}'
      Range: '100'
      Bungee: false
      
   When talking in local chat, the server you're on is ranged to 100 blocks.
   However anyone on another server gets to see my chat via Bungee.
   
   It'd seem like the Bungee: false is not really doing anything there.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true
> 
> ```
> local:
>   Format: '&e[L] &8({luckperms_prefix}{luckperms_suffix}&8) {player_displayname}&e:&f {message}'
>   Range: '100'
>   Bungee: false
> ```
> 
> When talking in local chat, the server you're on is ranged to 100 blocks.
> However anyone on another server gets to see my chat via Bungee.
> 
> It'd seem like the Bungee: false is not really doing anything there.

Hey!
Happy New Year!

Could you try to completely remove the `Bungee:` part from this chat?
Let us know if it fixes the issue.
If it doesn't, please send us your `/chc debug` file.

**Comment by Managering** [comment]
Hi,

I tried both already. 

I made a debug file but can't find where it was saved. Could you give me a hint?

**Comment by ElBananaa** [comment]
> Hi,
> 
> I tried both already.
> 
> I made a debug file but can't find where it was saved. Could you give me a hint?

Alright,
The debug file should be inside your ChatControl folder. The file is named `debug.zip`

**Comment by Managering** [comment]
https://ufile.io/1cq2intb

**Comment by ElBananaa** [comment]
> https://ufile.io/1cq2intb

Did you enable the Chat Relay in BungeeControl config file?

**Comment by Managering** [comment]
Chat_Forwarding:
  
  # Enable this feature?
  Enabled: false
  
  Nope

**Comment by ElBananaa** [comment]
> Chat_Forwarding:
> 
> # Enable this feature?
> Enabled: false
> 
> Nope

Alright, well, that's pretty weird. Unfortunately I won't be able to test it since I have issues running a local bungeecord server.
You'll have to wait for Kangarko to take a look at this issue.
It should be done until Monday/Tuesday.

**Comment by kangarko** [comment]
Thanks, will make sure we don't send or receive messages if that channel has Bungee on false. Keep that option.
