### ISSUE TITLE
1.16.4: Unable to make chat go across the network

### ISSUE THREAD

**Issue by OliverP98** [kangarko/ChatControl#473]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Our issue at the moment is trying to get the chats across bungee, they have been configured on one server and the files transferred to ensure that all servers in the network are using the game configurations. So far we keep getting the following issue:
![image](https://user-images.githubusercontent.com/42102786/103462857-1ca80e00-4d20-11eb-8412-712cba066974.png)
This happens which I attempt to do /ch and then click on one of the channels to move to. This is also effecting /msg and get the following issue:
![image](https://user-images.githubusercontent.com/42102786/103462877-4103ea80-4d20-11eb-8e59-c0ee97da7e86.png)
I am in fact on the server, I would be so gracious for any help in trying to resolve these issues

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true
> 
> Our issue at the moment is trying to get the chats across bungee, they have been configured on one server and the files transferred to ensure that all servers in the network are using the game configurations. So far we keep getting the following issue:
> ![image](https://user-images.githubusercontent.com/42102786/103462857-1ca80e00-4d20-11eb-8412-712cba066974.png)
> This happens which I attempt to do /ch and then click on one of the channels to move to. This is also effecting /msg and get the following issue:
> ![image](https://user-images.githubusercontent.com/42102786/103462877-4103ea80-4d20-11eb-8e59-c0ee97da7e86.png)
> I am in fact on the server, I would be so gracious for any help in trying to resolve these issues

Hey!
Happy New Year!

Please provide us your `/chc debug` file, and your bungeecontrol config file.

**Comment by OliverP98** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5760612/debug.zip)
[settings.zip](https://github.com/kangarko/ChatControl-Red/files/5760614/settings.zip)

These are the files.

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5760612/debug.zip)
> [settings.zip](https://github.com/kangarko/ChatControl-Red/files/5760614/settings.zip)
> 
> These are the files.

Thanks.
Alright, please update your plugins/dependencies/server softwares.
ChatControl is outdated, same for ProtocolLib, and I guess it's the same for BungeeControl.

**Comment by OliverP98** [comment]
Thank you for the push to update the plugins, I was working with ChatControl Pro and upgraded to Red not too long ago. I left the old BungeeControl jar in my proxy while I should have updated it to the red version. Doing this has fixed the problem with my lack of reading ability.
