### ISSUE TITLE
1.16.4: PvPManager Incompatibility

### ISSUE THREAD

**Issue by JasmineWMCM** [kangarko/ChatControl#475]
https://ufile.io/7gsk9i0y

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

1- Load this up up with a clean version of PvPManager (Latest) & ChatControlRed (Latest).
2- /chc tour completion
3- /pvp doesn't work. (Dev says it's on your side)
4- Rest of PvPManagers commands are not working on the enable and disable pvp module

**Comment by ElBananaa** [comment]
> https://ufile.io/7gsk9i0y
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: false
> 
> 1- Load this up up with a clean version of PvPManager (Latest) & ChatControlRed (Latest).
> 2- /chc tour completion
> 3- /pvp doesn't work. (Dev says it's on your side)
> 4- Rest of PvPManagers commands are not working on the enable and disable pvp module

Hey!
Happy New Year!
You're not using the latest version of ChatControl, so please update it, and test again
Once this is done, if it still doesn't work, provide us a new `/chc debug` file, the server latest.log, and also provide us a link to the thread related to this issue from their discord/github/spigot page, or at least, a copy of the discussion you had with him.

**Comment by JasmineWMCM** [comment]
https://github.com/NoChanceSD/PvPManager-Issues/issues/135 <-- the link of the convo

https://ufile.io/aupun0ev <--- the new debug

**Comment by kangarko** [comment]
What do you mean "you can't use this command" — what happens when you run this in the game?

**Comment by JasmineWMCM** [comment]
It acts as if the command doesn't even exist at all. It's so strange. I think it must be something to do with ProtocalLib and how it handles stuff like this. I don't really know. It just sends the unknown command (custom, I edited this in spigot.yml). When I remove ChatControl Red it's perfectly fine.

**Comment by kangarko** [comment]
Seems like we unregister /toggle and register our own command. Try going through our settings.yml and for each section like Toggle, Spy, Tag, Me etc. try setting Enabled to false to stop it from working. Also try setting Apply_On keys to [] all where applicable. You'll find where it causes incompatibility and unfortunately you won't be able to use that section
