### ISSUE TITLE
1.16.4: Please Reopen

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#476]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

Can this pls be reopended. https://github.com/kangarko/ChatControl-Red/issues/457 Still no answer and i still have that problem. I have tested it on a complete fresh server with no plugin and all plugins uptodate but still not replacing the placeholder. Please do not close kangarko must throw a look of that bug.

**Comment by ElBananaa** [comment]
Hey!

Sorry, I completely forgot to answer you.
I'm closing this issue and reopening the other one.
