### ISSUE TITLE
1.16.4: Unable to hide certain chat messages

### ISSUE THREAD

**Issue by aerulion** [kangarko/ChatControl#477]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false
ChatControlRed Version: 10.1.14

Hello there,
i'm trying to hide the message which is sent when a user switches an channel, but when setting

Channels:
--Join:
----Switch_success: none

to 'none', the message just says none ingame:

![oNZtr2p](https://user-images.githubusercontent.com/43320714/103482204-cc908080-4ddf-11eb-8737-00c487c5b834.png)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: false
> ChatControlRed Version: 10.1.14
> 
> Hello there,
> i'm trying to hide the message which is sent when a user switches an channel, but when setting
> 
> Channels:
> --Join:
> ----Switch_success: none
> 
> to 'none', the message just says none ingame:
> 
> ![oNZtr2p](https://user-images.githubusercontent.com/43320714/103482204-cc908080-4ddf-11eb-8737-00c487c5b834.png)

Hey!
Happy New Year!

I believe someone already reported this issue, unfortunately I can't find the issue.
I'll leave this issue open so Kangarko could take a look at it and answer you.

**Comment by Sikatsu** [comment]
Yeah, I encountered the same issue with the automatic spy message on join.

**Comment by kangarko** [comment]
Thanks I will fix that!
