### ISSUE TITLE
1.12.2 How to delete these lines?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#478]
I've searched through the whole file in localization folder but could not find out how to remove these lines in the chat: [https://ibb.co/wW4KRBN](https://ibb.co/wW4KRBN)

**Comment by ElBananaa** [comment]
Hey!
Happy New Year!

If i'm not wrong, you can find these lines in the localization file. Simply search for the placeholders `{chat_line}` and remove them.
I'm closing this issue, let me know down below if you need anything else.

**Comment by nikitushu2** [comment]
I put '' in all the variables containing that placeholder, and i also tried setting them to 'none' but the lines still appear.

**Comment by ElBananaa** [comment]
> I put '' in all the variables containing that placeholder, and i also tried setting them to 'none' but the lines still appear.

Alright, I'll reopen this and let Kangarko have a look at it.

**Comment by kangarko** [comment]
What line again? That link is broken.

**Comment by ElBananaa** [comment]
> What line again? That link is broken.

He is trying to remove the header lines shown in each commands like these ones:
![image](https://user-images.githubusercontent.com/53318613/103668021-f039ff00-4f76-11eb-88e8-04c5ce9bc6ba.png)

**Comment by nikitushu2** [comment]
> 
> 
> > What line again? That link is broken.
> 
> He is trying to remove the header lines shown in each commands like these ones:
> ![image](https://user-images.githubusercontent.com/53318613/103668021-f039ff00-4f76-11eb-88e8-04c5ce9bc6ba.png)

Yes, that line

**Comment by kangarko** [comment]
I am sorry, right now this is not changeable because it's hardcoded in the code. At last I'll make the color customizable in Commands.Header_Color key in the next version.
