### ISSUE TITLE
1.16.4 | Rule Match sending several messages

### ISSUE THREAD

**Issue by Pukejoy** [kangarko/ChatControl#48]
I'm not sure If this is a bug, but when two or more Rules are applied to one message you get "Swearing is prohibited on this server" several times.
![image](https://user-images.githubusercontent.com/51823459/98985186-de664d80-252b-11eb-9559-fd58cce90d2e.png)

Maybe it will be better when several Rules are applied to send only one message to the player.

**Comment by kangarko** [comment]
Thanks will do!
