### ISSUE TITLE
Staff warning on player join

### ISSUE THREAD

**Issue by Steev93** [kangarko/ChatControl#48]
Requesting a player support option, so there can be like...

if they join if will alert staff or those will the command they are on a watch list, so like you can either also add comments onto them also as a Premium feature, or just like /chc watch <name> /chc unwatch <name> and the same with List, but you get alerted when they join

**Comment by kangarko** [comment]
Free version is not receiving feature updates, however I am leaving this open as a future suggestion or to the premium version.

**Comment by EvilOlaf** [comment]
I think this is comparable to the notes feature of BanManager.
A player can get a note X added by staff. When the player joins their a warning pops up that this particular player has note X. Also with the `notes` command all notes of players currently online are listed.

**Comment by Steev93** [comment]
What Evil said, and i have the Paid version, so i was hoping this for the paid not the free "Hence why i said Premium" i do believe this would be a good feature, like BanManager or AdminNotes

**Comment by kangarko** [comment]
Allright, thanks for your suggestion I will see what I can do.

**Comment by rErEaT** [comment]
hmmm not bad!

**Comment by kangarko** [comment]
I think this feature is supplied by many other plugins already, and adding it to ChatControl would only bias it with unnecessary features to most people.

However, it is possible to create a warning by hacking it inside the variable. Here is an example:

```
define {playerOrWarn}
script:
    var message = "&cBeware! &7Player &6{player} &7has joined the server!";
    var permission = "chatcontrol.alertjoin";
    var list = ["examplePlayer", "kangarko", "anotherPlayer"];

    if (contains(list, player.getName())) {
        var allPlayers = Java.type("org.bukkit.Bukkit").getOnlinePlayers();
        
        for (i = 0; i < allPlayers.size(); i++)            
            if (allPlayers[i].hasPermission(permission))
                allPlayers[i].sendMessage(message.replace("{player}", player.getName()).replaceAll("&", "§"));
    }
    
    player.getName();
    
    function contains(a, obj) {
        for (var i = 0; i < a.length; i++) {
            if (a[i] === obj) {
                return true;
            }
        }
        return false;
    }
```

The **message** variable in the code is the actual message. Change to whatever.
The **permission** is the permission for staff to receive the message. Also can be changed to whatever.
The **list** contains player who the staff will be warned about when they join. By default its examplePlayer, kangarko and anotherPlayer. It should be easily for you to figure out how to remove or add another players.

Just place the code in global/variables.txt file and then use the variable {playerOrWarn} normally in the join message in settings.yml.
