### ISSUE TITLE
1.16.4: Making swear rule check (or all rules) work only in specific commands?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#480]
Hi, how could please I limit group swear to only be whitelisted (to check) normally chat + JUST specific commands, not all of them? So just pm, tell, msg, r, mail, etc. + signs etc. normally, but I mainly wanna allow it in all commands and disable just in mentioned, cause there are some problems with it for me.

**Comment by broken1arrow** [comment]
> Hi, how could please I limit group swear to only be whitelisted (to check) normally chat + JUST specific commands, not all of them? So just pm, tell, msg, r, mail, etc. + signs etc. normally, but I mainly wanna allow it in all commands and disable just in mentioned, cause there are some problems with it for me.

I have not try it, but if i´m not wrong you can has only swear rule on a specific channel (limit for commands i don´t know is a way too limit).

**Comment by kangarko** [comment]
You can use "ignore command /brush|/auction|/auc|/register|/reg|/login|l" or "ignore channel swearchannel" operators in group.rs or the rules rs files.

**Comment by kangarko** [comment]
There's no way to not check all but specific commands right now, sorry.

**Comment by bobhenl** [comment]
and maybe way to ignore player names? Cause sometimes happens that someone has "wrong" nickname (mostly mistake in rules that has to be allowed) and then it can't be used in commands

**Comment by kangarko** [comment]
Thanks for your suggestion however we re not planning on adding this right now
