### ISSUE TITLE
1.15.2: Chat Formatting Rule

### ISSUE THREAD

**Issue by Cat956** [kangarko/ChatControl#481]
I have been trying to write a rule that will format a player's message (depending on their channel) so that the a substring between quotations is coloured differently than the rest of the message.

For example, https://i.imgur.com/GoWWe7F.png

I have written the regex that will return the substring, however I cannot find a way to preserve the original message while adding the colour codes. Is there a way to do this? Here is my current rule:

match (["'])(?:(?=(\\?))\2.)*?\1
require channel local
then replace &6{message?}&e

**Comment by kangarko** [comment]
Hey, you may want to try disabling Rules.Stripe_Colors in settings.yml to make rules not remove colors. Keep in mind however, players will be able to use colors to bypass other filters.

**Comment by Cat956** [comment]
Hi,

Sorry if I was a little unclear. The rule as it works now does replace the regex string with the colour codes, and I would like the rule to format chat as in the example above automatically. Players will not use colour codes themselves to create this effect.

My issue in creating the rule is that I can't seem to find a way to preserve the original regex. For instance, if a message is:

This is "a chat message"

The regex will return "a chat message". I need the rule to replace this with &6"a chat message"&e, however because of the replace command the substring "a chat message" is lost completely and I can't seem to find a way to retain it. Variables do not seem to work inside of the replace command.

**Comment by kangarko** [comment]
Sorry I am unable to help, I'm not proficient enough in regex. However you can't use {message?}, instead, use $0, $1 etc. to get the parts of the regex filter that have been matched. That way you can perhaps create two filters, one for the first quote, one for the final quote and use "then replace &6{0}" or similar in them respectivelly.

**Comment by Cat956** [comment]
The $0 worked to preserve the returned regex, the only issue was that the rule runs again and can recursively generate an endless string if the replaced text is also captured by the regex. I solved this by adding a more elaborate expression.
