### ISSUE TITLE
{player_channel_mode_{channel}} values

### ISSUE THREAD

**Issue by freeg-bee** [kangarko/ChatControl#482]
Whats full values list of {player_channel_mode_{channel}} variable?

**Comment by ElBananaa** [comment]
> Whats full values list of {player_channel_mode_{channel}} variable?

Hey!
Happy New Year.
For sure, this should output two values: Either `write` or `read`. Maybe a third value `not-joined`, but I'm not sure about this one tho.

**Comment by kangarko** [comment]
There's none, you simply place that right into your format and we automatically replace this variable with the current mode in the current player's channel.
