### ISSUE TITLE
1.16.4: How can I disable spy when player stop having permission for it?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#483]
Hi, I have one question. When someone join spying of specific channel, but then is from ex. degraded, kicked from team or it was just test, shouldn't he stop spying if he doesn't has permission anymore on it? At least if he doesn't have auto join spy permission? Cause it was regular player and still could spy messeages.

**Comment by kangarko** [comment]
Thanks I will make it so that we check for perm each time we send spy messages
