### ISSUE TITLE
1.15.2: MySQLSyntaxErrorException

### ISSUE THREAD

**Issue by Ultimating** [kangarko/ChatControl#484]
I've noticed that sometimes for one of my staff members when they chat into the "standard" chat channel, the console gives a MySQLSyntaxErrorException. I have the MySQL database on the BungeeCord proxy, I'm using BungeeControl Red version 3.1.14, Chat Control Red version 10.1.14 on the paper server this is happening on, and the database is using MariaDB version 10.3.21. I've attached the debug zip file and the error.log provided. What could be causing this?

**Minecraft Version:** 1.15.2
**MySQL:** true
**BungeeCord:** true

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5766959/debug.zip)
[error.log](https://pastebin.com/KJpSt4n4)

**Comment by UserDerezzed** [comment]
Same issue on 1.12.2 Paper. It's an issue with using apostrophes (')

**Comment by kangarko** [comment]
Thanks will get patched!
