### ISSUE TITLE
Mail system improvements

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#49]
1) It would be nice if you can sent a mail to all players that have been online on the server (mostly used for staff-purposes)

2) Misses a space between ''1recipients''
![image](https://user-images.githubusercontent.com/5664135/98986214-e40c6500-2524-11eb-9826-615fa3a1d39d.png)

3) I assume it misses color formatting ''click with mouse to discard''
![image](https://user-images.githubusercontent.com/5664135/98986329-0c945f00-2525-11eb-9c83-d0f469837209.png)

4) After sending a mail, you can not use the same draft to send it to another player even though the book stays in your inventory.
![image](https://user-images.githubusercontent.com/5664135/98986525-52512780-2525-11eb-861d-78171ca6c86a.png)

**Comment by kangarko** [comment]
Thanks, fixed all except 4) - this is a wontfix if you signed the book and then got it again.

**Comment by Sikatsu** [comment]
How do you mean exactly? I signed the book but what if I decide after sending the mail that I want to send it to someone else as well? I have to re-write the book (mail)?

Thanks though!

**Comment by Sikatsu** [comment]
And the book is required currently, could it be an option to make a config so you can send mails without the book system?

/mail Sikatsu <message>
