### ISSUE TITLE
Enable rangedmode for OP's

### ISSUE THREAD

**Issue by AmandoVledder** [kangarko/ChatControl#49]
Is it possible to enable rangedmode for ops?

**Comment by kangarko** [comment]
Ranged mode is enabled for everyone. OPs can have the permission (chatcontrol.chat.overrideranged) to speak in the whole world, and to the entire server when message starts with ! and have chatcontrol.chat.global permission.

**Comment by AmandoVledder** [comment]
Even without the permission ops can speak to the whole world

**Comment by kangarko** [comment]
Okay, do you want the ops to not be able to speak to the whole world?

**Comment by AmandoVledder** [comment]
Yes

**Comment by kangarko** [comment]
Enable ranged chat and give everyone **chatcontrol.chat.overrideranged** permission and **-chatcontrol.chat.overrideranged** permission to OPs.
