### ISSUE TITLE
1.16.4: chatcontrol.command.message

### ISSUE THREAD

**Issue by freeg-bee** [kangarko/ChatControl#490]
What is chatcontrol.command.message permission grant?

**Comment by ElBananaa** [comment]
Hey!
According to the wiki, this permission is used to `Manage player messages.`
You can see that using `/chc permissions` ingame, on on the wiki page: https://github.com/kangarko/ChatControl-Red/wiki/Permissions

I'm closing this issue. If you need more precisions feel free to comment down below, or if you need anything else, open a new issue. :)
