### ISSUE TITLE
[1.16.4] Duplicated Text

### ISSUE THREAD

**Issue by elkoyofficial** [kangarko/ChatControl#491]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

https://gyazo.com/651df70086479a872d5238829bb2b93d - Chat duplication. It's very random.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: false
> BungeeCord: false
> 
> https://gyazo.com/651df70086479a872d5238829bb2b93d - Chat duplication. It's very random.

Hey!

Please provide us your `/chc debug`

**Comment by elkoyofficial** [comment]
https://ufile.io/y7nn7caf

**Comment by ElBananaa** [comment]
Hey!

The plugin and its dependencies aren't up-to-date. As said on the issue report format, we only provide support for the latest release.
Please update the plugin and its dependencies.

**Comment by kangarko** [comment]
Also seems like it's caused by some other plugin, check your chat plugins
