### ISSUE TITLE
1.12.2 Helpop warn message does not change

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#492]
Minecraft Version: 1.12.2
MySQL: false
BungeeCord: false

Helpop warn message does not change even though I set a proper rule.

[https://ibb.co/y4HnTjm](https://ibb.co/y4HnTjm)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.12.2
> MySQL: false
> BungeeCord: false
> 
> Helpop warn message does not change even though I set a proper rule.
> 
> https://ibb.co/y4HnTjm

Hey!

Please provide us your `/chc debug`

**Comment by nikitushu2** [comment]
[https://ufile.io/jxr57rmq](https://ufile.io/jxr57rmq )

**Comment by ElBananaa** [comment]
Alright.
From what I can see, neither your dependencies nor your plugins are up-to-date. Please update to the latest version.
I also noticed that you didn't change anything to the command.rs file:
```
# Catch "/helpop" command and send usage.
match ^\/helpop$
dont verbose
then warn &cDescription: Send a message to online staff members.
then warn &cUsage: /helpop <message>
then deny
```
This is the part in your file, and as you can see, it's different than the one you provided with your screenshot.

I'm closing this issue, feel free to keep sending messages here if you need anything else.

**Comment by nikitushu2** [comment]
Hi, thanks for your answer. I noticed that I can put the "catch" function of a command both in chat.rs and command.rs. What's the difference between them?

I don't know I can't make it work, even though I put catching of helpop in both directories. Strangely enough catching "!" and other symbols works fine, only helpop does not for some reason.

**Comment by nikitushu2** [comment]
Ok, it works now. I accidently blocked the command by command blocker. But I still would like to know the difference between chat and command rs

**Comment by nikitushu2** [comment]
Oh, nvm. Helpop does not work, it was helpop of another plugin. Sorry :)

**Comment by nikitushu2** [comment]
I fixed it! I forgot to put \ before /helpop.
