### ISSUE TITLE
[1.16.4] Timed messages are not displayed

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#494]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

I have timed messages configured in group default, but i cannot see them at all

![image](https://user-images.githubusercontent.com/62369973/103867659-cc8eca00-50d8-11eb-8ab6-08c401e208ed.png)

![image](https://user-images.githubusercontent.com/62369973/103867694-d7e1f580-50d8-11eb-8fce-126e44033041.png)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5780319/debug.zip)

**Comment by ElBananaa** [comment]
Hey!

We don't provide support for outdated versions of the plugin.
Please update ChatControl, ProtocolLib and your server softwares (bungee/waterfall/spigot/paper or whatever your use), try again, and post a new `/chc debug` file if it still doesn't work.

**Comment by kangarko** [comment]
Right see if the latest version of ChatControl prints any Tips in the console regarding this. Also check your Timed_Delay setting in Messages section.

**Comment by OfT3N** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5792625/debug.zip)


> Right see if the latest version of ChatControl prints any Tips in the console regarding this. Also check your Timed_Delay setting in Messages section.

**Comment by OfT3N** [comment]
Still does not work

**Comment by OfT3N** [comment]
And i see no tips

**Comment by kangarko** [comment]
<img width="682" alt="Screenshot 2021-01-12 at 10 02 13" src="https://user-images.githubusercontent.com/1918426/104292527-42ba7480-54bd-11eb-8f16-b2cf27fa6f4d.png">
Works fine for me, tried via bungee. Try removing all other plugins to see if something else is blocking it

Also your debug file has bungeecord disabled, is this the latest file right?
