### ISSUE TITLE
1.16.4: DiscordSRV

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#495]
I'm trying to show the in-game player name rather then discord nickname in-game.

![image](https://user-images.githubusercontent.com/5664135/103883646-c9e2a380-50dd-11eb-8838-fe9d45ab241d.png)

{player} and {player_name} both pull the discord nickname, however, since I'm linked with DiscordSRV, I was hoping it would be possible to show the in-game name instead.

If I set my nickname on discord to &4Sika, it will also get colored in-game. Can't quite figure out how to solve this though..

**Comment by ElBananaa** [comment]
Hey!

For the first part, I guess this could be done using DiscordSRV placeholder: `{discordsrv_user_game_name}`.
For the second part, I have no clues, please wait for an answer from Kangarko.

**Comment by Sikatsu** [comment]
Ah, that works within the chatcontrol configuration too?
It kinda would solved the second matter too.

**Comment by ElBananaa** [comment]
> Ah, that works within the chatcontrol configuration too?
> It kinda would solved the second matter too.

Well, you could give it a try I guess.

**Comment by Sikatsu** [comment]
It doesn't, sadly:

![image](https://user-images.githubusercontent.com/5664135/103925199-72612980-5117-11eb-99f2-a6d18645e7c7.png)

**Comment by Yamamot00** [comment]
I used another plugin from discord the name is DBVerifier, he links the In game name to Discord name

**Comment by kangarko** [comment]
Thanks, I'll leave this open and look into making the PAPI variable work.

**Comment by Sikatsu** [comment]
Thank you

**Comment by kangarko** [comment]
While I was not able to get placeholder replacing to work, I made the following change:

We now use the linked Minecraft name in player messages coming from Discord. If players haven't linked their name, we simply use their Discord username.

**Comment by Sikatsu** [comment]
Thanks! That should work.
