### ISSUE TITLE
[1.16.4] Wrong formatting when using mentions

### ISSUE THREAD

**Issue by OfT3N** [kangarko/ChatControl#496]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Message text is supposed to be white and it is, but if you mention a player as the first word of your message, it takes color from previous format part (&8)
![image](https://user-images.githubusercontent.com/62369973/103890392-0b347c80-50f9-11eb-89e6-fa3b986b8176.png)

**Comment by ElBananaa** [comment]
Hey!

I'm using the plugin on my production server, and I don't have the same issue. I guess it's something related to you.
Please update your plugins, their dependencies and your server softwares.
Also please provide your `/chc debug` once this is done.

**Comment by kangarko** [comment]
This is a special case because we were not able to grab the previous formatting if this is the first word. It's a long-standing issue I am not seeing an easy fix for this right now.
