### ISSUE TITLE
Leave + Join Variable

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl#497]
Maybe a placeholder for the custom leave and join message specific to the user.

So I can implement the leave and join messages into other plugins without hafting to retype the message and it'll change automatically depending on the user.

For example I can make it show their leave and join message on discordsrv 👍 

I am not sure if this is possible in the javascript variable if so please let me know <3

**Comment by kangarko** [comment]
Hey, not quire sure what you mean but you can create your own variables in variables/ folder and then use them for players who join/leave and then use "then discord" to send this message over to Discord.
