### ISSUE TITLE
1.8.8 | Not reloadable after config fail

### ISSUE THREAD

**Issue by tomet123** [kangarko/ChatControl#5]
After some invalid changes in config, plugin crash and not reloadable anymore. Will be good to check if config valid and than reload.

**Comment by kangarko** [comment]
What exactly are these changes and what exactly is this error?

**Comment by tomet123** [comment]
For example if user changing config value to invalid - for example "Channels.Enabled: truex". Server show valid error. In this example: 
"Oups, reloading failed! See the console for more information. Error: Report: Malformed configuration! Key 'Channels.Enabled' in settings.yml must be Boolean but got String: 'truex'." 
After user fix this misclick there is no ability to another reload - server must be restarted.

**Comment by kangarko** [comment]
We can only prevent syntax errors from happening. This is a valid syntax and it reads as a String not a Boolean, which is checked deeper in the plugin.
