### ISSUE TITLE
Handler ignore command

### ISSUE THREAD

**Issue by Mikgreg** [kangarko/ChatControl#50]
Hi, in handlers.yml I can only see an option to ignore certain commands. Is there a way to make a certain handler ignore all commands?

**Comment by Mikgreg** [comment]
Here's another issue too. Errors get thrown when the /r command is run
http://i.imgur.com/zr2Xr63.png

**Comment by kangarko** [comment]
>Hi, in handlers.yml I can only see an option to ignore certain commands. Is there a way to make a certain handler ignore all commands?
No because you put the rule in the appropriate place, not the handler. If you want only chat to be checked, move the rule from rules.txt to chat.txt file.

>Here's another issue too. Errors get thrown when the /r command is run
Are you using Essentials or EssentialsX? Which version and what bukkit version are you running?

**Comment by Mikgreg** [comment]
Ok thank you, will try it out in chat.txt
--
I'm running EssentialsX version 2.0.1-b235 on PaperSpigot version http://i.imgur.com/FutKjrh.png

**Comment by kangarko** [comment]
I cannot reproduce. Using %nick variable everything works correctly. 

Ensure you are on latest both ChatControl and EssentialsX dev builds.

**Comment by Mikgreg** [comment]
Are we testing the correct issue? Where does the %nick variable come into /r causing an error?

**Comment by kangarko** [comment]
Oh, I see :) Sorry. But I just tested the /reply also where the code is used, and did not get any errors. What version of ChatControl are you running?

**Comment by Mikgreg** [comment]
v5.0.6

**Comment by kangarko** [comment]
The latest version is 5.2.7. Please update.
