### ISSUE TITLE
Autojoin is broke

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#50]
I will use CHC as a normal global chat. So i removed all channels and only leave the "standart" and give chatcontrol.channel.join.standard.write and chatcontrol.channel.autojoin.standard.write than, i rejoined and write some stuff and the plugin say: "Youre not i a channel"

**Comment by DevJoey** [comment]
I have found the problem. it is, because i have left the cahnnel manuelly. but can you please ass an option to force the player to the channel, even if he left it manually

**Comment by Qw4rtz** [comment]
> I have found the problem. it is, because i have left the cahnnel manuelly. but can you please ass an option to force the player to the channel, even if he left it manually

You can prevent your players from leaving the channel by denying them the permission `chatcontrol.channel.leave.{channel}`.
With luckperms the command would be `/lp group [group name] permission set chatcontrol.channel.leave.{channel} false`

**Comment by kangarko** [comment]
Thanks for answering!

**Comment by kangarko** [comment]
Added Ignore_Autojoin_If_Left to next version to disable that option
