### ISSUE TITLE
[Suggestion] Usernames should not be counted in Anti_Caps feature

### ISSUE THREAD

**Issue by Theepwner** [kangarko/ChatControl#50]
Hello, I am really wanting to use the Anti_Caps feature with ChatControl, but when players type usernames that are all in caps, it will force it to lowercase.  I am suggesting a feature where you can specify if names currently online will be counted in the caps limit.

So for example, if you have it so 5 caps in a row will force it to lowercase.  But having a username that is currently online in the chat message, it will not count.
So lets say a player's name is BOB_BUILDER.  Saying "Hi BOB_BUILDER" will not force "BOB_BUILDER" into "bob_builder".

Now lets say a player says "OMG BOB_BUILDER YOU ARE TERRIBLE", it should convert to "omg BOB_BUILDER you are terrible".

I hope you consider this suggestion :)

**Comment by kangarko** [comment]
Implemented ;)
However as I mentioned it might cause lag on bigger servers.
