### ISSUE TITLE
1.8.8: MySQL syntax error

### ISSUE THREAD

**Issue by haeiven** [kangarko/ChatControl#500]
Minecraft Version: 1.8.8
MySQL: true/
BungeeCord: false

There's an error in the mysql syntax when pasting logs into the database: https://paste.soleria.eu/ariwetaqoq.sql

It seems caused by quotes.

Best regards,

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.8.8
> MySQL: true/
> BungeeCord: false
> 
> There's an error in the mysql syntax when pasting logs into the database: https://paste.soleria.eu/ariwetaqoq.sql
> 
> It seems caused by quotes.
> 
> Best regards,

Hey!
This is a known issue which was fixed in the latest version.
Please update your plugin, it should fix the issue.
