### ISSUE TITLE
1.16.4: Hiding deathmessages not working

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#501]
Minecraft Version: 116.4
MySQL: true
BungeeCord: true

Unless my setup is wrong (attached debug folder), I added all deathmessages under the same group, but when toggling, the deathmessages still show up.

![image](https://user-images.githubusercontent.com/5664135/103939888-ccb8b500-512c-11eb-9e94-ee802b7b9ce5.png)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5783754/debug.zip)

**Comment by kangarko** [comment]
Congratulations for the 116th Minecraft, unfortunately the system's designed only to support 1 message group. Right now we're not planning doing recodes in this regards.

**Comment by Sikatsu** [comment]
Seems i'm far ahead indeed lol.

I'm not asking for a recode, and I am not sure what you mean. I can make a group per death message, but then they'd have to toggle off every individual death message.

Can you tell me how I make it so theres just one toggle to disable the deathmessages? Or is it not possible to disable all deathmessages at once?

**Comment by Sikatsu** [comment]
Getting reports that if you disable the deathmessage, players no longer see YOUR deathmessages..

Did you check my deathmessages configuration?

**Comment by kangarko** [comment]
I will make it so you can ignore all message types and also will fix the inverted logic. thanks.
