### ISSUE TITLE
Placeholder {rule_name} not getting replaced

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#502]
When using the operator ``name <rule name>`` for a rule, the placeholder {rule_name} does not get replaced

Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

To test this again, I used the default configuration and made very few changes.

1) add ``name <name>`` to a rule, here is an example below
```
# Blocks 'shit'
match \b(s+(\W|\d|_)*h+(\W|\d|_)*i+(\W|\d|_)*t+(\W|\d|_)*)
name s word
group swear
```

2) Add the ``{rule_name}`` to the group that the rule belongs to that you edited above, in this case, the ``swear`` group.
```
group swear
ignore perm chatcontrol.bypass.swear
ignore command /brush|/auction|/auc|/register|/reg|/login|l
ignore command //
then warn {warn_prefix} Swearing is prohibited on this server.
then notify chatcontrol.notify.swear &8[&7Swear/ID {rule_name}&8] &7{player}: &f{original_message}
then log {player} triggered the swear filter, ID {rule_name} > {original_message}
then replace @prolong *
```
3) swear in chat ;)

**NOTES**
I added ``{rule_name}`` to, ``then notify`` and ``then log``, to see if I trigger the rule listed above, if ``{rule_name}`` would return a result at all, even for rules without a name, it didn't return with a value like ``UNSET`` like it use to on ChatControlPro, it simply remained the same and the placeholder did not change at all.

Also if this is able to be fixed, would someone be able to confirm if it will behave similar to ChatControlPro, where if the placeholder is used in say ``then notify chatcontrol.notify.swear &8[&7Swear/ID {rule_name}&8] &7{player}: &f{original_message}`` but the rule triggered does not have a ``name``, would it return a value ``UNSET``.

**Comment by kangarko** [comment]
Thanks, will get fixed in the next version.
