### ISSUE TITLE
1.16.4: Nickname issue (in use)

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#504]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Players name was &9Kolfikdrie, he tried to change the colors but again it said the nickname is already in use.

Player feels that the issue is related to capitals. His minecraft name is "Kolfikdrie", and he only wanted to add a color to it and name himself "KolFikDrie", this however was not possible.

![unknown-11](https://user-images.githubusercontent.com/5664135/104068471-47ed9a00-5205-11eb-8116-fd2293d6e116.png)

**Comment by kangarko** [comment]
I will make this case insensitive
