### ISSUE TITLE
1.16.4: Name color bug with 3.1.17?

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#506]
I went ahead and updated my 3.1.15 to .17, and right away noticed everyones names were yellow **with** a space in front of their names (chat only, not tablist). Triple checked my formats and everything's done correctly on my end, I was able to fix the issue by rolling back to 3.1.15. I didn't see anything in the changelogs that could've impacted name colors in chat so I'm unsure if this is a legit bug or just something I should've tweaked with the new update.

If it helps at all, this is exactly what the player name variable looks like in all of my formats: '&f{player_name}: '

Mysql: true
Bungeecord: true
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5800263/debug.zip)

**Comment by ElBananaa** [comment]
> I went ahead and updated my 3.1.15 to .17, and right away noticed everyones names were yellow **with** a space in front of their names (chat only, not tablist). Triple checked my formats and everything's done correctly on my end, I was able to fix the issue by rolling back to 3.1.15. I didn't see anything in the changelogs that could've impacted name colors in chat so I'm unsure if this is a legit bug or just something I should've tweaked with the new update.
> 
> If it helps at all, this is exactly what the player name variable looks like in all of my formats: '&f{player_name}: '

Hey!
Please follow the bug report format, it's here, and there's a reason. :)
Soo please provide your `/chc debug` and infos about your environment (MySQL? Bungee setup?...)

**Comment by Squeej** [comment]
Yeah I just saw the license removal post and updated the post with mysql and bungee info, I’ll provide debug docs later tonight

**Comment by Squeej** [comment]
Okay I went ahead and uploaded the debug zip using 3.1.17 to the original post. Apologies for incorrectly posting the issue

The issue happens with all of my servers, but I have noticed overtime bungee chat will stop working for my hardcore server (3.1.15), so I chose the hardcore debug zip, I was wondering if you guys can take a look at that also instead of opening a separate issue for it. Thanks for everything you guys do:)

**Comment by kangarko** [comment]
<img width="464" alt="Screenshot 2021-01-12 at 10 14 01" src="https://user-images.githubusercontent.com/1918426/104293961-ebb59f00-54be-11eb-9df3-4a7e56c4ef86.png">
Sorry how can I reproduce this? Tested hardcore_chat.

Let's fix this issue first before moving on thank you.

**Comment by Squeej** [comment]
Gotcha, yeah that’s strange, on my end it shows in chat like <‘@e {player}’>

I’ll take a snapshot tonight and do some more testing to see if maybe it’s a plugin conflict with the namecolor plugin or something, then update/close this thread if I find anything.

**Comment by Squeej** [comment]
Okay so I did some testing, doesn't appear to be a plugin conflict, seems to work great in my test server with the same plugins. Not sure what's going on, only difference in between the test and main server is that the main server uses java 11/ubuntu and the test server uses java 8/windows

EDIT: Tested with 3.1.16 and there's no issues, so its something that changed with the 3.1.17 update

![CHC TEST](https://user-images.githubusercontent.com/71758114/104446732-bc9b3e00-554f-11eb-8856-3b07c5951c29.jpg)

**Comment by kangarko** [comment]
I cannot reproduce still, has to be caused by something else most likely. Not sure why upgrading would render this issue visible. Are you certain you've sent me the exact config from the main server? Why I am getting [HC] tag before and you're not?

**Comment by Squeej** [comment]
I figured it out! It was conflicting with an afk plugin I was using, which would change a players name color on afk. It likely had to do with it's bungee feature since I wasn't able to reproduce the issue in my test server without bungee. Closing this issue, thanks for looking into it!

**Comment by ElBananaa** [comment]
> I figured it out! It was conflicting with an afk plugin I was using, which would change a players name color on afk. It likely had to do with it's bungee feature since I wasn't able to reproduce the issue in my test server without bungee. Closing this issue, thanks for looking into it!

Hey!
Thanks for letting us know. Could you please give us the name of the plugin, so we can list this as a "known issue" just in case.
