### ISSUE TITLE
Bug - "then warn" not sending message if exactly the same as another "then warn" in that specific rule

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#507]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Example
If I got into ``chat.rs`` and type this
```
match ^how (do|can|to)(| I| you) (set|create|place)(| a) home
then warn &r
then warn &fTry typing /sethome
then warn &r&b
then deny
```
It will print out
```

Try typing /sethome

```
BUT if I write this,
```
match ^how (do|can|to)(| I| you) (set|create|place)(| a) home
then warn &r
then warn &fTry typing /sethome
then warn &r
then deny
```
It sends the user this message
```

Try typing /sethome
```

**NOTE** the same thing happens if I were to type
```
match ^how (do|can|to)(| I| you) (set|create|place)(| a) home
then warn {chat_line}
then warn &fTry typing /sethome
then warn {chat_line}
then deny
```
As in the second ``then warn {chat_line}`` doesn't get printed but if I do ``then warn &r{chat_line}`` etc it does, because it isn't "technically" the same.

Any chance this could be fixed? that would be amazing! :D

**Comment by kangarko** [comment]
Thanks will be magically fixed!
