### ISSUE TITLE
Please Make formats folder allow to have sub folders. | allow to able to import more rules

### ISSUE THREAD

**Issue by king-glitch** [kangarko/ChatControl#508]
1. 
**Formats**

I suggest to make formats folder allow to have sub folders, because of chat rules on `then warn <format>`. What if I want to make chat format on every rules, that would be very complecated, It would really help other developers too (I believe). I will help others able to organize folder structure. 

**Rules*

Please also implement rules folder to able to create more rules and import from different files.
ex. I create bot.rs I want to import it from chat.rs for chat message event.

instead of writing 1000 lines of code. can be suppurate to different files.

This would be very very helpful to another developers too.

2. It wouldn't affect the server.

**Comment by kangarko** [comment]
Thanks, however that would require some major system upgrade we're not planning right now
