### ISSUE TITLE
1.16.4: Error when clicking to delete messages with the command /spy on

### ISSUE THREAD

**Issue by MdoubleM** [kangarko/ChatControl#509]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

Hi, when I use the command ''/spy on'' and someone writes something, I click to delete the message and then appear this error:
https://pastebin.com/pqs7JsY2

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: false
> BungeeCord: false
> 
> Hi, when I use the command ''/spy on'' and someone writes something, I click to delete the message and then appear this error:
> https://pastebin.com/pqs7JsY2

Hey!
Please provide your `/chc debug` file.

**Comment by MdoubleM** [comment]
Here it is: https://ufile.io/b4pumgp6

**Comment by ElBananaa** [comment]
Thanks.
As I can see, ProtocolLib is outdated. Please update to the [latest ](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)version
Let us know if it fixes your issue.

**Comment by MdoubleM** [comment]
I'm still having the same error in the console with the ProtocolLib updated

**Comment by kangarko** [comment]
The settings you've provided have Channels disabled. When I enable them, and toggle /spy on then click on X there's no error. Try without any other plugins and ensure you've sent me the actual latest zip with those settings that break it.

**Comment by MdoubleM** [comment]
I enabled the Channels but then the people can't talk in general chat and I have to give them more permissions that I don't want to. I prefer them to talk in a general chat and not in channels. Also I was still having the error, but no problem. If I have to enable the channels to make this feature of deleting messages with a click then I don't want to. Thank you for your time and sorry for bothering you. I'll close the issue

**Comment by ElBananaa** [comment]
> I enabled the Channels but then the people can't talk in general chat and I have to give them more permissions that I don't want to. I prefer them to talk in a general chat and not in channels. Also I was still having the error, but no problem. If I have to enable the channels to make this feature of deleting messages with a click then I don't want to. Thank you for your time and sorry for bothering you. I'll close the issue

Hey,

It is currently possible to make a general chat with the channel feature enabled. You don't need to have thousands of channels. In my case the feature is enabled, and I only have two channels: an adminchat, and a general chat. For the permissions, you only need to add something like 4 permissions for each channel, that's nothing. Kangarko even made a video to explain how to setup channels, and it's pretty easy actually: https://www.youtube.com/watch?v=EKziLXSjwhY

But feel free to do whatever you want.
