### ISSUE TITLE
1.16.4 : Hexcodes in /chc color

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#51]
Despite testing for 1.8.8, I quickly tested hexcodes as well on 1.16.4 since that was one of my main issues on ChatControl 8.

![image](https://user-images.githubusercontent.com/5664135/98987433-72cdb180-2526-11eb-8ae1-a19ece4c29cd.png)

Missing value after /chc color: ''/chc color - Set chat color to HEX''
Missing value in front of the dot: ''Set your chat color to .''
Double space between ''Sikatsu has chat color.''

Other then that, hexcodes seem to be implemented well! 👍 

I couldn't find the permission to allow for certain hexcodes only though, which was accepted months ago for a request ^^

**Comment by ElBananaa** [comment]
Same issue for me.

**Comment by kangarko** [comment]
Thanks, added all, sorry about missing the hex perm!

It's now: "chatcontrol.hexcolor.CODE" such as chatcontrol.hexcolor.ccaadd from the next version.

**Comment by Sikatsu** [comment]
Awesome, no worries! Is it also possible to only allow certain hex in the nickname, but no hexcodes at all in the chat itself? @kangarko
