### ISSUE TITLE
drop chat event and lose it's format

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#510]
this is error in error.log

------------------------------------[ 10.01.2021 18:03:22 ]-----------------------------------
ChatControlRed 10.1.17 encountered a ConcurrentModificationException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 11.0.9
----------------------------------------------------------------------------------------------
More Information: 
Unhandled exception listening to AsyncPlayerChatEvent
ConcurrentModificationException (Unknown cause)
	 at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
	 at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1521)
	 at org.mineacademy.chatcontrol.model.Channel.compileSoundNotify(Channel.java:587)
	 at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:487)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:153)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:31)
	 at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)

**Comment by ElBananaa** [comment]
> this is error in error.log
> 
> ## ------------------------------------[ 10.01.2021 18:03:22 ]-----------------------------------
> ChatControlRed 10.1.17 encountered a ConcurrentModificationException
> Running Paper 1.16.4-R0.1-SNAPSHOT and Java 11.0.9
> More Information:
> Unhandled exception listening to AsyncPlayerChatEvent
> ConcurrentModificationException (Unknown cause)
> at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
> at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1521)
> at org.mineacademy.chatcontrol.model.Channel.compileSoundNotify(Channel.java:587)
> at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:487)
> at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:153)
> at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:31)
> at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
> at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)

Hey!
Please follow the bug-report format. It's here, and there's a reason. :)
I can't do anything to help you with the error you provided, and I don't think Kangarko could do anything too.
We need informations.

Please provide us informations about your environment: Server Version, java version, mysql setup? Bungee setup?
Make sure your plugins, server softwares and dependencies are up-to-date.
And also provide us your `/chc debug`.

**Comment by FakEEE14** [comment]
sorry about this

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true
all dependencies are latest

**Comment by ElBananaa** [comment]
> sorry about this
> 
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true
> all dependencies are latest

Thanks!
Could you also provide your `/chc debug` please?
Sensitive informations are automatically removed.

**Comment by kangarko** [comment]
Thanks Ill fix that
