### ISSUE TITLE
Ignore command contain spaces // dealing with CMI aliasses

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#511]
### Background ###

As perhaps known, CMI's aliasses works like this:
`/msg player123 I want to swear blah blah blah`
results actually in 2 commands;
1. The player execute: /msg player123 I want to swear blah blah blah
2. System executes: /cmi msg player123 I want to swear blah blah blah
This counts for all CMI commands.

If you wanted to filter private messages, you had to:
- mark `/cmi msg` as chat.
or:
- ignore commands like `/cmi tpa`
to work as normally without filtering. Because the `handle_as_chat` couldn't handle spaces, the only option was to ignore all commands you wanted to exclude. This `ignore commands` allowed spaces. This resulted in a handlers file to look like this:

```yaml
swear:
  Ignore_Commands:
    - // # WorldEdit
    - /cmi tpa
    - /tpa
```
### Problem ###
Nowadays with ChatControl Red, you can't do this:
```yaml
group swear
ignore command /cmi tpa
ignore command /tpa
```
nor can you mark `/cmi msg` as chat.

### Suggestion ###
I would like to see spaces to be accepted in `ignore command` or `/cmi msg` to be handled as chat.

Use case:
- players need to perform certain commands, containing player names, at all times. Regardless of names containing potential inappropriate names. E.g. pay, tpa, msg etc

**Comment by TheIntolerant** [comment]
This should work as a temp fix ``ignore string ^\/cmi tpa``

**Comment by x1p** [comment]
Thnx. That could be a workaround in individual cases. Of course not in all (~1000) rules.

**Comment by kangarko** [comment]
Closing

**Comment by x1p** [comment]
To my humble opinion, it's not a good idea to permanently equip 1000 rules with long `ignore string` lines
