### ISSUE TITLE
1.16.4: Format_Spy Reverting to default spy.yml

### ISSUE THREAD

**Issue by Plum1111** [kangarko/ChatControl#512]
No matter what I try, Format_Spy doesn't work. I've tried using `@noprefix` to see if that made a difference but it did not. I've tried using another spy file, it didn't work either. I've put the spy file I'm trying to use as the default spy file and it worked flawlessly but I would like it to be channel specific. I've tried naming the format `spy5` like someone suggested (even though I don't think it matters too much) and it still did not work.
I have come to the conclusion it is a bug because there's not much else I can try. It works for other people but not me for some reason which is still unknown.

Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

How to reproduce (however it might not be so easy because it works for other people):
1. Make a spy file with the exact contents of spy.yml and then make a small noticable change to see if it worked
2. Use that file in settings.yml under 'Format_Spy'
3. Spy on someone's message and see if it worked or not

This was originally a question but it seems to be a bug. Previous version: 
<details><summary>1.16.4: How do you use 'Format_Spy' ?</summary>
I made a spy.yml copy called local-spy.yml for my local channel (with a color code touchup) and then used Format_Spy. It didn't work and simply shows the default spy.yml no matter what I do. Am I doing something wrong? https://i.imgur.com/qUKAbo0.png
</details>

**Comment by ElBananaa** [comment]
> I made a spy.yml copy called local-spy.yml for my local channel (with a color code touchup) and then used Format_Spy. It didn't work and simply shows the default spy.yml no matter what I do. Am I doing something wrong?
> ![local spy](https://camo.githubusercontent.com/65472914013c07ae4d686e2eafbeced3ddb2a36fce5429a10cbf120f44230e9f/68747470733a2f2f692e696d6775722e636f6d2f71554b41626f302e706e67)

Hey!
Please follow the bug report format!

Try adding `'` before and after your format spy, so it should look like: `Format_Spy: 'local-spy'`.

**Comment by Plum1111** [comment]
This wasn't a bug report, it was a question. But it may be a bug at this point

**Comment by Plum1111** [comment]
@ElBananaa

**Comment by kangarko** [comment]
Alright that'll be fixed in the next version
Thanks for reporting!
