### ISSUE TITLE
1.16.4: Sometimes player logout default message is shown

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#514]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Player logged out normally, but somehow it sometimes also shows the default minecraft logout message to players.

![image](https://user-images.githubusercontent.com/5664135/104183255-fe25cf00-5411-11eb-9ded-7ec1f3b09193.png)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true
> 
> Player logged out normally, but somehow it sometimes also shows the default minecraft logout message to players.
> 
> ![image](https://user-images.githubusercontent.com/5664135/104183255-fe25cf00-5411-11eb-9ded-7ec1f3b09193.png)

Hey,
Please provide your `/chc debug` file.

**Comment by Sikatsu** [comment]
Hey, uploaded below!

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5797720/debug.zip)

**Comment by kangarko** [comment]
Thanks next version should have this repaired
