### ISSUE TITLE
1.16.4 Error

### ISSUE THREAD

**Issue by ttt0** [kangarko/ChatControl#517]
https://hastebin.com/volixifani.sql

I am getting such an error I could not find how to solve it

**Comment by ElBananaa** [comment]
Hey!
Please follow the issue-report format and open a new ticket using the right format.

**Comment by kangarko** [comment]
Check your quit messages, remove your messages/quit.rs if unsure to let the plugin regenerate a new one

If still having issues open a new ticket and **follow the issue template**
