### ISSUE TITLE
1.16.4: Unable to connect due to MySQL error

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#518]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false
MySQL database: External Mariadb Cluster (Shared hosting)

1. Empty test server
2. Let CHC run
3. Shut down server
4. Edit msql parameters
5. Start server
6. See error

Error message:
https://pastebin.com/rj2WYNwR

I can't get mysql working.
I noticed the hint to install a mysql driver. I placed several mysql jars in the CHC folder, just like Litebans works, but this didn't work.
It won't create the tables. In the past weeks, it was only once or twice successful. Afterwards failed again. So it's not only the creation that fails.
I'm puzzled why only this plugins is so difficult to connect. I've setup many many plugins in the past years without any trouble.
I'm open for all advice.

**Comment by kangarko** [comment]
The line seems to have an error:

jdbc:mysql://censored.hostname.net:3306/s10000_databasename?autoReconnect=true&useUnicode=yesharacterEncoding=UTF-8&useSSL=false

Change to

jdbc:mysql://censored.hostname.net:3306/s10000_databasename?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false

**Comment by kangarko** [comment]
That's a really odd error, I am also getting it like 1/100 cases when I start my test server. Haven't found the cause _yet_. Hmm maybe using MySQL instead of MariaDB? Heard from someone else having a different issue with encoding that switching solved his problem

**Comment by x1p** [comment]
My mysql file looks exactly like the default.
`Line: jdbc:mysql://{host}/{database}?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false`
Why would I mess with that?

How can I use MySQL instead of MariaDB? The hosting manages that since it's a shared hosting. I will ask them, but I'm afraid they'll answer that it's arbitrary. Mariadb is very common.

Edit:
`&&ccharacterEncoding` seems to result in an error where the line is correct:
`?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false`
The result is the same; it won't connect due to `No suitable driver found for jdbc:mysql://` etc. etc.

**Comment by kangarko** [comment]
Try these lines:

`Line: jdbc:mysql://{host}/{database}?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false`

`Line: jdbc:mysql://{host}/{database}?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=true`

`Line: jdbc:mysql://{host}/{database}?autoReconnect=true&useSSL=false`

`Line: jdbc:mysql://{host}/{database}`

**Comment by x1p** [comment]
Tried every combination but no luck
`No suitable driver found for jdbc:mysql://` etc. etc.

Tried a random free online database. No luck.

**Comment by kangarko** [comment]
Sorry for a late response, I followed this https://javarevisited.blogspot.com/2016/09/javasqlsqlexception-no-suitable-driver-mysql-jdbc-localhost.html and added Class.forName to load the driver, not sure why it's working 90% of times without this. Anyways please test the new version coming up in 48h or less.
