### ISSUE TITLE
Very tiny customisation possebillitys

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#52]
I will Completely customize the /ch command it looks ugly for me and dont match my server design. I cannot completely customize that http://prntscr.com/vi7hsx i will make this as my server design.
Please implement it as the following
channel-info:
    - '------------------------------------------------------------------'
    - 'Channles'
    - ''
    - 'Youre in channel: %channels%'
    - '------------------------------------------------------------------'

So how its is, i cannot make it looks as my server design!

**Comment by DevJoey** [comment]
I will simple have &2Proxy&7Socke &8x &zYou are in channel: %channels% and not this big ugly header message

**Comment by ElBananaa** [comment]
> I will simple have &2Proxy&7Socke &8x &zYou are in channel: %channels% and not this big ugly header message

I think that the actual format looks pretty basic (and that's a good thing), not ugly. You have to edit the format yourself to make it look the way you want :)

**Comment by DevJoey** [comment]
No it has nothing todo with formats. Type /ch and see the message. i will able complete customize that.

**Comment by ElBananaa** [comment]
Oh, my bad, thought you were talking about the formats xD

**Comment by DevJoey** [comment]
All good.

**Comment by kangarko** [comment]
I'll add this to the next version.

**Comment by DevJoey** [comment]
Thank you. It would be nice if all messages get this format. So i can edit every line as my like

It would be so nice if this gets added.

**Comment by kangarko** [comment]
Not sure if it was you whom I promised this to, but we'll add this. Yes one of the most frustrating things about third party plugins is the lack of custom design, we aim to fix that

**Comment by kangarko** [comment]
Added, look for Alternative_Header. There are two, one for /channel, the other one for /chatcontrol.
