### ISSUE TITLE
1.16.4: Timed messages error

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#521]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Todays release gives an error with timed messages, nor do they show up.

Error: https://pastebin.com/XWf5Lyrz

Debug: 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5801215/debug.zip)

**Comment by LogGits** [comment]
Also having this issue

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true
> 
> Todays release gives an error with timed messages, nor do they show up.
> 
> Error: https://pastebin.com/XWf5Lyrz
> 
> Debug:
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5801215/debug.zip)

Hey!
Thanks for reporting this.
However, according to you debug file, you are using chc v10.1.13. Are your sure that you are using the latest version?
If so, please provide us the right debug file.

**Comment by Sikatsu** [comment]
Might have copied the wrong one, updated:

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5803665/debug.zip)

**Comment by ElBananaa** [comment]
Alright, thanks! I just tried, and I can confirm I have the same issue.
Just wait for kangarko to fix this.

**Comment by kangarko** [comment]
It's always so strange because on my own setup that's 90% similar to the default one I barely get these issues and then I must look like an idiot for not testing this haha

Anyways I actually uncovered another issue with "delay" and fixed both for a quick today's release. Enjoy!
