### ISSUE TITLE
CMI hex compatibility

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#522]
CMI displayname hex compatibility improvements. CMI uses the format of {#abc123} format for hex colours. When applying the cmi nickname can you add the `{` and `}` before and after the hex code. This will make all cmi displaynames and tablist features compatible

**Comment by Sikatsu** [comment]
Would like the same, I have requested this but it was denied sadly.

**Comment by kangarko** [comment]
Please vote: https://forms.gle/gCNcn7ZR7X6pyF3u8
