### ISSUE TITLE
1.16.4: Death Message API

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#523]
So in the previous version chc8 i was using DeathMessageEvent to cancel death messages that were spammy. It was removed in chc-red. Is there a way to actually prevent the death message via the api rn?

i tried:
```java
    @EventHandler (priority = EventPriority.LOWEST)
    public void onDeathCHC (PlayerDeathEvent event) {
        event.setDeathMessage(null);
    }
```
and even with highest priority and it still seems to send the chc death message. Could we make it so either if event.getDeathMessage() returns null we prevent chc death message or re-add the old api DeathMessageEvent?

The plugin is lookin good so far :)

**Comment by ElBananaa** [comment]
> So in the previous version chc8 i was using DeathMessageEvent to cancel death messages that were spammy. It was removed in chc-red. Is there a way to actually prevent the death message via the api rn?
> 
> i tried:
> 
> ```java
>     @EventHandler (priority = EventPriority.LOWEST)
>     public void onDeathCHC (PlayerDeathEvent event) {
>         event.setDeathMessage(null);
>     }
> ```
> 
> and even with highest priority and it still seems to send the chc death message. Could we make it so either if event.getDeathMessage() returns null we prevent chc death message or re-add the old api DeathMessageEvent?
> 
> The plugin is lookin good so far :)

Hey!
Why would you use the API to do that? In your messages/death.rs, remove every rules, and add
```
# Doesn't show any death message
group death-messages
message: 
- none
```
It should disable every death message.

**Comment by LogGits** [comment]
Nah i want to keep death messages just cancell them in some occassion e.g. to prevent death msg spam

**Comment by kangarko** [comment]
Thanks will add new API event for that.
