### ISSUE TITLE
Ability to toggle Discord functionality per channel

### ISSUE THREAD

**Issue by m171717** [kangarko/ChatControl#525]
Hi, I have a fairly simple request: Allow toggle Discord to be toggled per channel as opposed to altogether. This is a feature that was in Pro, but is lacking in Discord. We want to use the experimental web hook avatars, but haven't been able to since switching to Red.

We need this feature because otherwise all chat from all channels is synced to Discord (such as Town chat, Nation chat, etc). 

Best regards,
Michael.

**Comment by broken1arrow** [comment]
Is, for get some functions to work. Was not easy to get it work at all, see if he can fixit in the future (was not so fun bugs when all channels linked to discord and you cant turn if off).

**Comment by kangarko** [comment]
Hey,

You can write "Discord: false" key for each channel to disable Discord functionality there.
