### ISSUE TITLE
1.16.4: Wrong placeholder in /r error message

### ISSUE THREAD

**Issue by tomhula** [kangarko/ChatControl#527]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: alse

When you type command **/r {mesage}** and the player it should message to is not online anymore, it says **Player {message} is not online on this server.** instead of **Player <player> is not online on this server.**

So if I was messaging with player Notch and then he left and I then typed **/r hello**. It would say **Player hello is not online on this server.** instead of **Player Notch is not online on this server.**

**Comment by kangarko** [comment]
Thanks, will be fixed.
