### ISSUE TITLE
Question - Can we make it so we have more control with the spy permission nodes?

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#529]
Basically, I was wondering if it would be possible to do the following with regards to the spy permission nodes

**Pick if staff can bypass a specific part of /spy?**
``chatcontrol.bypass.spy.{type}`` 
*For examples*
``chatcontrol.bypass.spy.channels.{channel_name}``, ``chatcontrol.bypass.spy.signs``, ``chatcontrol.bypass.spy.privatemessagaes``  etc

**Pick what parts of /spy, staff can access?**
``chatcontrol.command.spy.{type}`` 
*For examples*
``chatcontrol.command.spy.channels.{channel_name}``, ``chatcontrol.command.spy.signs``, ``chatcontrol.command.spy.privatemessagaes`` etc.

**Pick what part of /spy, staff have enabled automatically?**
``chatcontrol.spy.autoenable.{type}`` 
*For examples*
``chatcontrol.spy.autoenable.channels``, ``chatcontrol.spy.autoenable.signs``, ``chatcontrol.spy.autoenable.privatemessagaes`` etc

**How will it benefit the community?**
By adding these extra permission nodes, this would allow server administrators, to better control how their staff use /spy and instead of just grant their staff to everything within /spy. For example, by making it possible to do ``chatcontrol.spy.autoenable.{type}``, server admins, can keep the ability to spy on commands without having it enabled automatically, yet, make sure other features such as private messages remain so spying for private messages is enabled automatically. Regarding ``chatcontrol.command.spy.{type}``, this could enable admins to say let their helpers spy on specific channels etc while making sure only Mod+ can spy on other things like private messages.

**Comment by kangarko** [comment]
Spying is a dangerous privilege that should only be granted to staff you trust, we see no need to changing the current system — you either trust the staff member fully to give him full rights to /spy or you don't.

**Comment by iTz-MrAnonymous** [comment]
Would it still be possible to do

chatcontrol.spy.autoenable.{type}?
To avoid having spy auto enabled all the time for things like commands?
