### ISSUE TITLE
Command Cooldowns and Factionschat

### ISSUE THREAD

**Issue by Goldentoenail** [kangarko/ChatControl#53]
Players using regular commands which may be repeated are being refused.

Can the Command Spam section be reworked using a cooldown instead of requiring an intermediate command from a player. So that normal players are not annoyed by the problem.

Using Factions and Factionchat
The swear filter works in /fc p (the default Public channel) but not in any other /fc <channel>
I'm not sure if this is under your control or Factionchat.

**Comment by kangarko** [comment]
You can add commands that you want allow to be repeated after each other in **Anti_Spam.Commands.Whitelist_Similarity** or repeated quickly in **Anti_Spam.Commands.Whitelist_Delay**.

>The swear filter works in /fc p (the default Public channel) but not in any other /fc 

Unfortunately FactionsChat is having a higher priority that is overlapping with ChatControl. Priority of ChatControl's events is configurable in the pro version.

**Comment by kangarko** [comment]
Considering it's fixed, please correct me if I am wrong.
