### ISSUE TITLE
1.16.4: Anvil Spy not enough exp

### ISSUE THREAD

**Issue by Plum1111** [kangarko/ChatControl#531]
Anvil spy triggers even when you don't have enough exp to complete the rename. E.g. It costs 1 exp and I have 0 but I happen to click the finished item. This can be spam clicked repeatedly and spam the moderator's chat.

Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
That seems to get called in Bukkit, can try looking into it but likely there's no way for us to check that easily
