### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#532]
Hi!
A few questions
I'm wandering how to mute the chat in the server
If I can clear chat not just on the whole network

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Hi!
> A few questions
> I'm wandering how to mute the chat in the server
> If I can clear chat not just on the whole network
> 
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true

Hey!
In order to use the mute feature, you need to enable it in your settings.yml:
```
Mute:

  # Should we enable this feature?
  Enabled: true
```
Once this is done, reload the plugin and simly use `/mute` to get infos about the command. You can currently mute a channel, a player or the whole server.
Regarding the chat thing, I'm not sure that a network clean feature is actually available in the plugin. You should wait for an answer from kangarko.

**Comment by TheIntolerant** [comment]
```
/chc clear
Clear the game chat. You can specify the parameters -a for anonymous clearance (hides who cleared it) 
-s to avoid announcing anything. BungeeCord is supported. You can also give a clear reason.
```
- Stated in -> [Wiki - Commands](https://github.com/kangarko/ChatControl-Red/wiki/Commands)

Also when I've used this command on a bungee network it's cleared chat of other servers.

**Comment by ElBananaa** [comment]
> ```
> /chc clear
> Clear the game chat. You can specify the parameters -a for anonymous clearance (hides who cleared it) 
> -s to avoid announcing anything. BungeeCord is supported. You can also give a clear reason.
> ```
> 
> * Stated in -> [Wiki - Commands](https://github.com/kangarko/ChatControl-Red/wiki/Commands)
> 
> Also when I've used this command on a bungee network it's cleared chat of other servers.

Hey!
Thanks, I wasn't sure about it.
You'll have to wait for Kangarko to see what can be done, but I guess he could add something like `/chc clear -n` in order to clear the entire chat network.

**Comment by kangarko** [comment]
Hey, we automatically clean the network if BungeeCord integration is enabled.
