### ISSUE TITLE
WIKI: Something i  discussed on discord regarding discordsrv

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#533]
Know that they are not always good at support and are really bad at giving answers (usually get answers in riddles if you get an answer).

The problem is that in the spigot it says that you should enter the discord channel name and ID (which in my opinion is quite funny, is like writing the channel name twice).

The funny thing is that in config.yml it is the opposite of their wiki on spigot, I not find their log when they add this 
feature, where they actually posted support for minecraft's own global channel in case you do not have a chat plugin (in that case you need to enter minecraft channel name that is global not from discord). It was not so long time ago they add that support. 

And also they are apparently known for not being able to decide how things should be and change things back and forth :)

```
# Channel links from game to Discord
# syntax is Channels: {"in-game channel name from Minecraft": "numerical channel ID from Discord", "another in-game channel name from Minecraft": "another numerical channel ID from Discord"}
```

**Comment by kangarko** [comment]
Thanks for letting me know! I will keep an eye on this and when it gets stabilized feel free to ping me and I will update our wiki.

**Comment by broken1arrow** [comment]
> Thanks for letting me know! I will keep an eye on this and when it gets stabilized feel free to ping me and I will update our wiki.

Hi, yea they have this mistake for a long time now. Do not know if it will even be fixed (has try to speak with dem but is like talk to a wall).

Know other things they changed and then changed back (like where they should have their placeholders).

Seams like my first text is not 100% correct, spigot page not say any thing about channels linking (if i not miss something).

I find this on there wiki https://config.discordsrv.com/config/Channels,

**Comment by kangarko** [comment]
Yeah isn't this the same way as we describe on our wiki already? 
<img width="1018" alt="Screenshot 2021-01-26 at 10 42 46" src="https://user-images.githubusercontent.com/1918426/105828290-407b0e80-5fc3-11eb-870f-cd986dd00020.png">

**Comment by broken1arrow** [comment]
> Yeah isn't this the same way as we describe on our wiki already?
> <img alt="Screenshot 2021-01-26 at 10 42 46" width="1018" src="https://user-images.githubusercontent.com/1918426/105828290-407b0e80-5fc3-11eb-870f-cd986dd00020.png">

I think on this "Use the exact channel names as you have on Discord" or misunderstand I this?

**Comment by kangarko** [comment]
It should work when you use the same channel names
