### ISSUE TITLE
1.16.4: Tag alias

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#534]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Hey, I have a plugin called ''Tag'', that of course has ''Tag'' as command. Since CHC also uses /tag, I was hoping if I made a custom alias for tag:tag that it would work for the other plugin, but CHC also listens to tag:tag.

Anyone knows any solution?

**Comment by rybuilder23** [comment]
Je gebruikt ook cmi toch nog?

maak via cmi /cmi aliaseditor
/tag aan en kopel hem via /tags

zou goed is je probleem moeten oplossen.

[English]

I thougth that you used CMI Also
Create wih cmi /cmi aliaseditor
the alias en connect hem with /tags

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true
> 
> Hey, I have a plugin called ''Tag'', that of course has ''Tag'' as command. Since CHC also uses /tag, I was hoping if I made a custom alias for tag:tag that it would work for the other plugin, but CHC also listens to tag:tag.
> 
> Anyone knows any solution?

Hey!

Under the `Tag:` part in the plugin settings, try to replace:
```
  Command_Aliases:
  - 'tag'
```
with:
```
  Command_Aliases:
  - 'chctag'
```
Let me know if it fixed your issue.

**Comment by Sikatsu** [comment]
Thanks, I found a workaround that works!
