### ISSUE TITLE
1.16.4: Null pointer &  Startup Bungee Error

### ISSUE THREAD

**Issue by xNocSx** [kangarko/ChatControl#537]
**Minecraft Version:** 1.16.4 - Paper or Tuinity
**MySQL:** true
**BungeeCord:** true

So, few things that might come in hand:
- We have 2 Machine (A Dedicated and a KVM);
- We have some Minecraft server Running in both;
- We are having this Error below only when MC Servers on the Dedicated Machine (We have MySQL DB on the KVM);
![photo_2021-01-06_11-05-41](https://user-images.githubusercontent.com/29774601/104812813-27c16a80-5805-11eb-9ff2-f195614f8c6b.jpg)

Debug of the related server:
[SkyBlock_debug.zip](https://github.com/kangarko/ChatControl-Red/files/5824422/debug.zip)

With the Survival sometimes it says that **the player is offline** when you try to /msg him or when you try to change channel it says something like **The user xNocSx is not connected through Bungeecord**
[https://pastebin.com/MKafgPj8](https://pastebin.com/MKafgPj8)
[Survival_debug.zip](https://github.com/kangarko/ChatControl-Red/files/5824414/debug.zip)

Last but not least, this is the startup bungeecord error.
We are currently using flamecord.
[https://pastebin.com/ch8tBfhZ](https://pastebin.com/ch8tBfhZ)

_Thank you in advance for the help! :)_

**Comment by kangarko** [comment]
Regarding that error, I see "co.ryred.spongepls" in it that means you are using some custom fork of Bungee (flamecord) which we cannot support sorry about right now. We only guarantee support on paper and bungeecord
