### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by DavidForge** [kangarko/ChatControl#538]
Hi, I'm thinking of buying your plugin and I had some suggestions to add to it.
I dont know if the plugin already have some of that features, i think that not but well, i suggest anyway.

Add mentions of @everyone and @here with a permission that allows not to receive them in order to make an option that they do not reach them.

Also add @staff mentions that only reach those who have permission.

The last suggestion is to add the function that this plugin has: https://www.spigotmc.org/resources/chatreplay.28982/

I really do not see it necessary nor do I know if it is a very good idea but I give you the suggestion so that you value it.

Thanks for reading and have a good day ^^

**Comment by ElBananaa** [comment]
> Hi, I'm thinking of buying your plugin and I had some suggestions to add to it.
> I dont know if the plugin already have some of that features, i think that not but well, i suggest anyway.
> 
> Add mentions of @everyone and @here with a permission that allows not to receive them in order to make an option that they do not reach them.
> 
> Also add @staff mentions that only reach those who have permission.
> 
> The last suggestion is to add the function that this plugin has: https://www.spigotmc.org/resources/chatreplay.28982/
> 
> I really do not see it necessary nor do I know if it is a very good idea but I give you the suggestion so that you value it.
> 
> Thanks for reading and have a good day ^^

Hey!
Thanks for submitting your suggestions, I'm pretty sure Kangarko will like them!
Next time, please use the suggestion template :)

Keep in mind that for now, Kangarko's goal is to stabilize the plugin as much as possible, and to fix as many issues as possible, so if your suggestion is accepted, I might still take a while before it actually gets added.

However, the @everyone, @here and @staff feature seems a little blurry, could you explain it a bit further? From what I understand, you'd like chatcontrol to manage discord features, but I don't know if this is something that would really be interesting since the plugin would need to manage things like discord ranks in order to implement this kind of features, and I don't know if this is something that Kangarko would like.

Regarding your second suggestion, I must admit that it looks pretty cool, and it could be really useful to have a text printed in your chat like `[Click here to see the last 20 messages sent before your connection]`, but it looks like a pretty heavy task tho.

**Comment by DavidForge** [comment]
Hello!
Thanks for your reply!

Try using the suggestion template, sorry if you don't use it very well.

I understand Kangarko's current goal, it's okay if you're slow to add these suggestions.

With the suggestion of @everyone, @here and @staff the plugin would check by putting someone that who has a permission to send them the notifications.

As in discord yes.

Regarding the chat history, I understand that it can be heavy, I thought the same but just in case I wanted to suggest it.

And do you think the suggestion to receive ads based on having x permissions is added to the plugin?

**Comment by ElBananaa** [comment]
> Hello!
> Thanks for your reply!
> 
> Try using the suggestion template, sorry if you don't use it very well.
> 
> I understand Kangarko's current goal, it's okay if you're slow to add these suggestions.
> 
> With the suggestion of @everyone, @here and @staff the plugin would check by putting someone that who has a permission to send them the notifications.
> 
> As in discord yes.
> 
> Regarding the chat history, I understand that it can be heavy, I thought the same but just in case I wanted to suggest it.
> 
> And do you think the suggestion to receive ads based on having x permissions is added to the plugin?

What do you mean by "receive ads based on having x permissions"? The plugin doesn't send any ads in the chat.
Anyways, feel free to open a new suggestion if you'd like to suggest another feature. :)

**Comment by kangarko** [comment]
Thanks for your suggestion! It's not our priority to keep adding more "flashy" features like mentions etc., but rather I want to make sure the plugin is 100% stable and high performant. We already have 10X more core features than any other competitor plugin so I have to reject this right now.

**Comment by DavidForge** [comment]
> > Hello!
> > Thanks for your reply!
> > Try using the suggestion template, sorry if you don't use it very well.
> > I understand Kangarko's current goal, it's okay if you're slow to add these suggestions.
> > With the suggestion of @everyone, @here and @staff the plugin would check by putting someone that who has a permission to send them the notifications.
> > As in discord yes.
> > Regarding the chat history, I understand that it can be heavy, I thought the same but just in case I wanted to suggest it.
> > And do you think the suggestion to receive ads based on having x permissions is added to the plugin?
> 
> What do you mean by "receive ads based on having x permissions"? The plugin doesn't send any ads in the chat.
> Anyways, feel free to open a new suggestion if you'd like to suggest another feature. :)


I want to say with the broadcast command, that for you see the broadcast you need a permission that the person that do the broadcast put in the command.

**Comment by DavidForge** [comment]
> Thanks for your suggestion! It's not our priority to keep adding more "flashy" features like mentions etc., but rather I want to make sure the plugin is 100% stable and high performant. We already have 10X more core features than any other competitor plugin so I have to reject this right now.

Ok, i understand is fine, thanks anyway ^^
