### ISSUE TITLE
How do I use this plugin with essentials nicknames? and How do I use it with factions?

### ISSUE THREAD

**Issue by Qballl** [kangarko/ChatControl#54]
As the title suggest I just want to know how to use it with both of those plugins. Like what variable do, I need to have in my config? Please help.

**Comment by kangarko** [comment]
To use it with Essentials, simply use %nick variable across the files, e.g. in chat formatter in settings.yml.

Same with Factions: there is a %faction variable.

**Comment by Qballl** [comment]
Is there a way to make it to where the %faction shows has a way of indicating a rank in the faction and if a faction's status towards yours such as ally netural or enemy

**Comment by kangarko** [comment]
No sorry, the %faction variable only shows the player faction. There is no %pl_faction variable by the way.

**Comment by Qballl** [comment]
Well when I use %pl_faction it does distiguish ranks in facs and faction status

**Comment by kangarko** [comment]
The %pl_faction is not from ChatControl. 
And in case you haven't noticed yet, the free version is no longer receiving feature updates.
