### ISSUE TITLE
1.16.4 still use chatcontrolred

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#54]
chatcontrolred

chatcontrolred.command

chatcontrolred.command.reload

chatcontrolred.command.permissions

chatcontrolred.command.message

chatcontrolred.command.debug

version 10.0.3

![2020-11-12_22 03 26](https://user-images.githubusercontent.com/16368286/98996424-1fae2b80-2533-11eb-9215-5cc0a8821438.png)

**Comment by kangarko** [comment]
Thanks, I will those. Can you please check for "chatcontrolred" and "chatcontrolred.command" only ? I could not find where those would pop up.

**Comment by broken1arrow** [comment]
> Thanks, I will those. Can you please check for "chatcontrolred" and "chatcontrolred.command" only ? I could not find where those would pop up.

I get it in luckperms editor (as suggestion). But I can check it better if is only, old cache.

**Comment by kangarko** [comment]
Let me know if you find anything more. Thank you.
