### ISSUE TITLE
Formating placeholder question

### ISSUE THREAD

**Issue by Yamamot00** [kangarko/ChatControl#540]
I'm trying to setup a new prefix on one of my channel formats that will show the user Clan prefix if he has a clan or else to be blank.
The format that i tried to make inside the channel is this.
`  Simplesclan:`
    `Message: '&7[{simpleclans_tag_label}&7]&f '`
   ` Sender_Condition: '{player_simpleclans_in_clan}'`
    `Hover:`
   ` - '&7.{simpleclans_clan_name}.'`
But even so the format is not working the way that i want.
the placeholders are correct: "{simpleclans_tag_label}shows tag" "{player_simpleclans_in_clan}return yes/no if clan" "{simpleclans_clan_name}show name when hover"

is there something that I'm missing? i tried going thought the wiki but the only possible way that this could be used was using the Js Variables and i have no clue on how i could do that

**Comment by ElBananaa** [comment]
> I'm trying to setup a new prefix on one of my channel formats that will show the user Clan prefix if he has a clan or else to be blank.
> The format that i tried to make inside the channel is this.
> ` Simplesclan:`
> `Message: '&7[{simpleclans_tag_label}&7]&f '`
> ` Sender_Condition: '{player_simpleclans_in_clan}'`
> `Hover:`
> ` - '&7.{simpleclans_clan_name}.'`
> But even so the format is not working the way that i want.
> the placeholders are correct: "{simpleclans_tag_label}shows tag" "{player_simpleclans_in_clan}return yes/no if clan" "{simpleclans_clan_name}show name when hover"
> 
> is there something that I'm missing? i tried going thought the wiki but the only possible way that this could be used was using the Js Variables and i have no clue on how i could do that

Hey!
The `Sender_Condition` and `Receiver_Condition` both need the variable to return a boolean (either true or false).
If the placeholder doesn't allow it, you can actually create a custom variable for that using chatcontrol.


**Go into `/plugins/ChatControlRed/variables`, create a file named `player-in-clan.yml` and paste this inside:** 
<details>
<summary>Code:</summary>

```Javascript
# -------------------------------------------------------------------------------------------------
# ChatControl supports dynamic, high performance variables you create! They can be used across
# the plugin, for example in formatting your chat or death messages. Currently, the folder
# variables/ stores all custom variables in each separate yml file.
#
# Variables can not only be used to display information, but because you can write your own full
# code in JavaScript to display them, they can also do whatever you would wish for your
# players/server, such as sneaking in code to send sounds or spawn monsters.
#
# Coding this variable requires a little bit of JavaScript knowledge, see the link below.
#
# For documentation and help, please see this link:
# https://github.com/kangarko/ChatControl-Red/wiki/JavaScript-Variables
# -------------------------------------------------------------------------------------------------

# Where should this variable be used?
#
# FORMAT = used in your formats with {syntax}, players cannot use it
# MESSAGE = players can use it with [syntax] in their chat messages
Type: format

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand"
Key: player_in_clan

# The value the key will be replaced to.
# This uses JavaScript and must return a boolean value.
Value: |-
    displayName();
    
    function displayName() {
      var isInClan = "{player_simpleclans_in_clan}";
    
      if (isInClan == "yes") {
        return true;
      } else {
        return false;
      }
    }

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: ''

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

# See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
# and only show the message to those receivers for which the condition returns true.
Receiver_Condition: ''

# What permission must the message receiver have in order for this variable to display to them?
Receiver_Permission: ''
```
</details>

Once this is done, in your format, simply replace: `Sender_Condition: '{player_simpleclans_in_clan}'` with `Sender_Condition: '{player_in_clan}'`

**Comment by Yamamot00** [comment]
hello. i'm getting some errors when i try to type in chat with this code, i fixed the {player_simpleclans_in_clan} part and changed to {simpleclans_in_clan} so the placeholder can inderstand the command but even so i get the error that "true is not defined"

https://pastebin.com/ektQYRMD

what i'm trying to do is to show the Clan tag when a user has a clan
