### ISSUE TITLE
1.8.8: /tell description lang error

### ISSUE THREAD

**Issue by Syndr4** [kangarko/ChatControl#543]
Minecraft Version: 1.8.8 and 1.16.4

I found this error, I know it is not important but maybe it should be fixed.

In the messages if you translate the description of "tell" it will only work for /tell, it will not work for /msg, /t, /w, etc

My traslate: https://i.imgur.com/lejJ1Lm.png

The error: https://imgur.com/a/r9G0RVN

**Comment by ElBananaa** [comment]
Hey!

Thanks for reporting this. :)
That's not a big deal, but details like this are always a bit important!
I'll leave this ticket open so Kangarko could take a look at it.

**Comment by kangarko** [comment]
I cannot reproduce, this is solved by clean restart of the server
