### ISSUE TITLE
1.16.4: Chat Clear Bypass Permission Bug

### ISSUE THREAD

**Issue by Spaex** [kangarko/ChatControl#544]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

When I give myself the permission chatcontrol.bypass.clear and use /chc clear my chat also gets cleared even due to my bypass permission. Tried it several times. Also did attached a screenshot which shows a permission check with Luckperms for that permission.

![2021-01-18_00 26 09](https://user-images.githubusercontent.com/46825907/104859252-3bafbe00-5924-11eb-9ea3-454d9071c4a3.png)

**Comment by ElBananaa** [comment]
Hey!

Thanks for reporting this issue! :)
I tried, and I have the same issue.
It looks like the `chatcontrol.bypass.clear` permission isn't even recognized by luckperms, like the permission isn't actually implemented in the plugin.
I'll leave this ticket open so Kangarko could take a look at it.

**Comment by kangarko** [comment]
@ElBananaa  It is irrelevant what perms are registered to LucksPerms since we don't register them in plugin.yml so LP may miss them anyways

For that issue, I will fix that thanks!
