### ISSUE TITLE
Adding a few placeholders & a first-time global join message

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#545]
Hey!
Basically, I noticed that the plugin actually includes a newcomer system and we have the ability to show players a different message when they first-join a server, but you can't send a different first-time join message. So I thought it would be cool to be able to change the first-time join message.
Related to this, I thought adding 2 placeholders: `{last_login}` to show the player's last login date, and `{last_login_time_elapsed}` to show the time elapsed between the player last login and the moment he logged-back-in would be nice.

**1. How it would benefit others?**
Well, adding a first-join message file to configure a different message than the one used in the `join.rs` file seems pretty basic and pretty important for a chat plugin. I mean, it's something quite important and pretty basic tho. So I'd say it would benefit everyone because it's a pretty basic feature that will litterally be interesting for any server.

Regarding the 2 placeholders, since the plugin has a newcomer feature, I guess it wouldn't be that hard to implement these placeholders. These are rather gadget features if i'm honest, but it would allow us to display more infos to players and who knows, it could be useful for future features.

**2. What would happen if we won't implement this feature? How's your server being affected?**

Regarding the firt-join message, I must admit that it's a bit annoying that the plugin doesn't actually have a such feature.
Regarding the placeholders, these are more gadget features. I'd say that it would be a pretty cool thing to add to the plugin, but it's litterally 1000 times less important than the first-join message thing.

**Comment by kangarko** [comment]
Added!


{last_active} | Return the last active player date using Timestamp_Format from settings.yml.
-- | --
{last_active_elapsed_seconds} | Return the time in seconds since player's last join.

**Comment by ElBananaa** [comment]
> Added!
> 
> {last_active}	Return the last active player date using Timestamp_Format from settings.yml.
> {last_active_elapsed_seconds}	Return the time in seconds since player's last join.

Hey, thanks!
What about the global first join message thing? Do you think it can be added?

**Comment by kangarko** [comment]
Replied there :)

**Comment by kangarko** [comment]
Lemme know if I missed something or missed a part of your suggestion?

**Comment by ElBananaa** [comment]
> Lemme know if I missed something or missed a part of your suggestion?

Hey!
I guess everything's there.
I'll have to run some tests in order to make sure everything works as intended tho.
I'll let you know if it does, or not.

**Comment by ElBananaa** [comment]
Hey! Alright, yeah it answered to my questions.

I have a few suggestions to improve these placeholders:

- Every time a player logs-in/out, it would be cool to update the placeholders, so if a players joins the server 10 times between each reboot, it'll show the good date. (Because actually, the placeholder are updated if there's a restart, so if you don't restart a server for a week, it'll show the wrong date).

- It would also be cool to add `{last_active_elapsed_format}` so it would automatically convert 60 seconds to 1h, 24h to 1 day, 7 days to 1 week, 30 days to 1 month, 365 days to 1 year etc..

- Finally, it would be awesome if, instead of giving a random date with the {last_active} placeholder, if it's the first time the player join, the placeholder would return "none".

**Comment by kangarko** [comment]
I unfortunately cannot update the placeholder since it's stored directly on Bukkits side, I'd have to invent our own unique system for that which is pain in the ass :/

For the other tips, I do really appreciate them however can you have a look into PlaceholderAPI? I'd not like to reinvent the wheel especially if that plugin has 10,000+ placeholders, AND you can combine PlaceholderAPI with our scripting system to customize it even more. Thanks so much :)

**Comment by ElBananaa** [comment]
> I unfortunately cannot update the placeholder since it's stored directly on Bukkits side, I'd have to invent our own unique system for that which is pain in the ass :/
> 
> For the other tips, I do really appreciate them however can you have a look into PlaceholderAPI? I'd not like to reinvent the wheel especially if that plugin has 10,000+ placeholders, AND you can combine PlaceholderAPI with our scripting system to customize it even more. Thanks so much :)

Alright, I understand. I'll see if I can find an alernative. However, I don't think there's anything I could do in order to create a placeholder like `{last_active_elapsed_format}`, as same as for the `{last_active}` placeholder, I don't think I could actually change it's default output (Which is a random date, something like 01.01.1970)

**Comment by kangarko** [comment]
I've made the change that instead of 1970's date it will print "none" :)

Also, I added this variable that will print this in a format like you suggested! 

<img width="573" alt="Screenshot 2021-02-04 at 11 24 48" src="https://user-images.githubusercontent.com/1918426/106879583-9d6d7780-66db-11eb-8932-5a10dd649d7e.png">

**Comment by ElBananaa** [comment]
> I've made the change that instead of 1970's date it will print "none" :)
> 
> Also, I added this variable that will print this in a format like you suggested!
> 
> <img alt="Screenshot 2021-02-04 at 11 24 48" width="573" src="https://user-images.githubusercontent.com/1918426/106879583-9d6d7780-66db-11eb-8932-5a10dd649d7e.png">

Alright, thanks!
I'm still searching for an alternative way to update the `{last_active}` placeholder everytime a players logs in and out, I'll let you know if I find anything related to that.

**Comment by ElBananaa** [comment]
Hey!

So after taking a look at what could be done, I found out that you can actually use 2 methods to get the player last played date:
You could either use the `getLastPlayed` method from the class `org.bukkit.entity.Player`, or you could use the `getLastPlayed` method from the class `org.bukkit.OfflinePlayer`. According to a few people, this should be done asynchronously, but if I'm no wrong, running async tasks with bukkit isn't the best idea. According to [this post](https://www.spigotmc.org/threads/best-way-to-retrieve-offlineplayer.423588/) this can be done synchronously tho.

Anyways, using this method should actually update the `{last_active}`, `{last_active_elapsed}` and `{last_active_elapsed_seconds}` without needing a server restart.

I must admit that it sounds weird to me tho, since, I guess, you'd actually have to store the last played date using the playerQuitEvent then retrieve this date when you log back in.

If you want more infos, you could take a look at https://github.com/AlessioDP/LastLoginAPI in order to know how he actually does it. Ofc, it it takes too much time, don't bother you with that. Howerver, I'd be happy to try a few things on my side if you can't or don't want to invest more time in this feature. ;)

EDIT: It also looks like the {last_active} placeholder still parses a date instead of "none" even tho i'm using the latest version of the plugin. (I also completely resetted the db)
![image](https://user-images.githubusercontent.com/53318613/107123073-d6ece100-689b-11eb-81ff-983efd835c19.png)

**Comment by kangarko** [comment]
Thanks, I fixed the 1970 date problem as well as used the getLastPlayed method which seems to update after each rejoin. However when a new player joins for the first time it will still say:

![a](https://i.imgur.com/O0nCeTb.png)

**Comment by ElBananaa** [comment]
> Thanks, I fixed the 1970 date problem as well as used the getLastPlayed method which seems to update after each rejoin. However when a new player joins for the first time it will still say:
> 
> ![a](https://camo.githubusercontent.com/5dc0cc890c08827012ca6b5efc290f4489ed48dc7150595d4c0e8d69b91a7cf1/68747470733a2f2f692e696d6775722e636f6d2f4f306e436554622e706e67)

Hey!
Thanks. That's not really a problem regarding the date since we can replace none with anything we want using the internal variable system easily now, but tbho, I think it makes more sense to show "none" the first time rather than a random date. :)
