### ISSUE TITLE
/chc fake - reintroduction

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#546]
> 1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)

Would reintroduce the `/chc fake <join/leave/kick> <username>` command that was included in chc8.

> 2. What would happen if we won't implement this feature? How's your server being affected?

Nothing really, i'd just make it via alternative methods. It'd just be convenient if it was re-added into the chat plugin it was originally in instead of needing to have a seperate plugin just for that single command.

Loving CHC Red, keep up the great work Kangarko :)

**Comment by ElBananaa** [comment]
Hey!

You can actually create a custom command in the plugin in order to do that.
https://github.com/kangarko/ChatControl-Red/wiki/Custom-Commands

**Comment by kangarko** [comment]
Yeah you can just create a custom command or use /chc announce -raw :)

**Comment by LogGits** [comment]
@kangarko
> [X]: No such type: '-raw'. Available: chat, image, title, actionbar, bossbar, toast

**Comment by kangarko** [comment]
Sorry, wrong syntax. Use:

/chc a chat type:raw Hey!
