### ISSUE TITLE
1.16.4: Random error

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#547]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

This random error sometimes breaks the chat formatting: https://pastebin.com/u7GMU45Q

Error.log: https://pastebin.com/DpQG7jTJ

**Comment by kangarko** [comment]
Seems like this is popping when the player discontinues just when pinging him, will attempt to fix that

**Comment by Sikatsu** [comment]
I'm not sure if it's related to pinging actually, it broke in a message that the player didn't tag anyone I believe.

[error (1).log](https://github.com/kangarko/ChatControl-Red/files/5844181/error.1.log)

**Comment by kangarko** [comment]
He does not have to ping someone successfully, we still iterate for every online player in that function to find the ping. Assuming that got fixed, but lemme know if you still see this popping out.

**Comment by Sikatsu** [comment]
It's not fixed though, see the error.log above or this pastebin: https://pastebin.com/rFSRMGWr

Could this be reopened?

**Comment by kangarko** [comment]
Try the next version please :)
