### ISSUE TITLE
1.16.4: Minecraft name change causing issues

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#548]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Player changed name from xAzureMoon to Liddooo, but in every message from ChatControl it will still say xAzureMoon.
It also resets her nickname on every login.

![image](https://user-images.githubusercontent.com/5664135/105014407-b241de00-5a40-11eb-95a4-49d751eb1233.png)

Debug: 
[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/5834917/debug.1.zip)

**Comment by kangarko** [comment]
For now just edit his name in on MySQL, I will investigate thank you.

**Comment by kangarko** [comment]
Look for his UUID then change Name column

**Comment by Sikatsu** [comment]
Yeah but I have a few players with this, gonna be hard having to change that manually each time haha

**Comment by kangarko** [comment]
It's pretty tricky to catch up — would you be so kind doing a small test? Edit Name column for your name to something else, then join the game and see if the issue will pop up for you.

**Comment by Sikatsu** [comment]
![image](https://user-images.githubusercontent.com/5664135/105212965-61b8a680-5b4e-11eb-9454-e980cd65c42a.png)

Sikatsu > Sikatsu2
On join it sets back to Sikatsu it seems.

![image](https://user-images.githubusercontent.com/5664135/105212990-67ae8780-5b4e-11eb-8b09-fd76372d0ae7.png)

**Comment by Sikatsu** [comment]
The name changed for the player now, so it must've been a server restart, or multiple relogs for ChatControl to update?

**Comment by Sikatsu** [comment]
Still happens for every player that changes his name through mojang. It will eventually update, but as of how it looks right now it requires a server restart to do so.

**Comment by x1p** [comment]
Chatcontrol's nick overrules CMI's nick every time player joins

**Comment by Sikatsu** [comment]
That's unrelated to this issue

**Comment by Sikatsu** [comment]
Could this be reopened?

**Comment by kangarko** [comment]
I did some rewrite and while I was not able to test this it appear to properly migrate nicknames this time. There will be a console message each time a player changes his Mojang's username, so it's easier for you to catch this and see immediately if his data was properly migrated. Let me know if the next version fixes this (finally!).

<img width="642" alt="Screenshot 2021-01-27 at 13 40 21" src="https://user-images.githubusercontent.com/1918426/105993061-2ebe6780-60a6-11eb-9216-ce033989d2bb.png">

**Comment by kangarko** [comment]
Closing in good faith this has been resolved, just comment below — I see everything :)
