### ISSUE TITLE
1.16.4: Console Commands 

### ISSUE THREAD

**Issue by Rexmen1** [kangarko/ChatControl#549]
So after started using the chatcontrolred all chat with staff/players are not coming to console and some other things either.. Is any way to fix it?
Can't see player to players message in console... How do I fix it

Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

**Comment by Rexmen1** [comment]
Can't see player to players message in console... How do I fix it

**Comment by TheIntolerant** [comment]
When reporting such issues please type ``/chc debug`` and upload the ``debug.zip`` here.

**Comment by ElBananaa** [comment]
> So after started using the chatcontrolred all chat with staff/players are not coming to console and some other things either.. Is any way to fix it?
> Can't see player to players message in console... How do I fix it
> 
> Minecraft Version: 1.16.4
> MySQL: false
> BungeeCord: false

> When reporting such issues please type `/chc debug` and upload the `debug.zip` here.

@iTz-MrAnonymous Thanks for answering him.

@Rexmen1 As said above, please provide your `/chc debug` output file.

**Comment by Rexmen1** [comment]
https://ufile.io/qmigtp3s

**Comment by kangarko** [comment]
Your another staff chat plugin conflicts with ours. See https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities and try experimenting with our priority system to find one that works
