### ISSUE TITLE
Multiple Formats in one file

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#55]
I will have multiple formats for the auto messager. but creating a new format-file for every message will be a mess. it would be nice, if i can define multiple formats in one single file. I know that i can use json but multiple formats in one file will be nice.

This format for rules and else.
formatfilename/formatname

File:
Formats:
    format_one:
       Parts:
    format_two:
       Parts:
      
so i can sipmple use

myfile/format_one to get the first format.

**Comment by kangarko** [comment]
I understand, but I cannot please everyone. We had formats in a single file for years. People decided otherwise. I cannot have both systems because it would end up badly, it would be overcomplicated and hard to maintain.
