### ISSUE TITLE
Enhance @playername

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#55]
I have a suggestion for a new feature. This can be integrated into the premium version.

`@playername` can highlight a player by playing a sound.
This can be enhanced in two ways I think.

Firstly it would be nice if the highlighted player sees the particular chat message or his name only in a different color or other ways to format a text.

Next `@playername` used at the beginning of a message could start a private conversation with `playername`. Using `@playername` in the middle of a message will not enable this mode

So I enter in chat:
`@player1 hello`

All further messages I type into the chat will automatically be declared as private wisp/msg to this particular player, so no more typing /r is needed. Simply typing `@` into the chat will quit the private conversation.

If one of those or both already exist please never mind. Was not sure as I could not find proper information at the plugin description and due to lack of property :P I could not test this by myself yet.

Thanks for reading.

Olaf

**Comment by Sikatsu** [comment]
I love these ideas, I hope @kangarko will be able to work on such system.

**Comment by kangarko** [comment]
I can see what's in my scope of skills. If all goes well I think I could add both high-lightning and that private conversation starting, but it would require Essentials to hook into.

**Comment by EvilOlaf** [comment]
At least for me that won't be an issue.

**Comment by Sikatsu** [comment]
I guess most use essentials.

**Comment by xknat** [comment]
i am using essentialsx (just saying :P )

**Comment by ImranDoet** [comment]
Or you could add an player to an arraylist when the message is like @imrandoet and customize the recipients to only people in that arraylist. and if it is @ then remove the player.

**Comment by Tsuser1** [comment]
I would love to see this feature in ChatControlPro

**Comment by kangarko** [comment]
Coming 8. February 2018 at its 2nd year's anniversary to celebrate fast support and implementation!

**Comment by VulpusMaximus** [comment]
Is it implemented yet?

**Comment by kangarko** [comment]
It has been delayed to 2021, sorry for that!

**Comment by kangarko** [comment]
Just kidding. I moved countries recently, moved from university to work etc., lots of stuff going on. However I am always keeping an eye on open issues in case I have an evening or two, so definitely it comes sooner that that!

**Comment by kangarko** [comment]
Bim bom ... implemented!

**Comment by EvilOlaf** [comment]
Nice job. However I am no longer into Minecraft server related stuff. Thank you anyways.
