### ISSUE TITLE
1.16.4: SQL ERROR

### ISSUE THREAD

**Issue by Syndr4** [kangarko/ChatControl#550]
Hi, I finished my ChatControlRed configuration and was about to put it on my productive server but it won't let me put the database, I tried changing the database and it still won't let me, any solution?
MySQL Version: 10.1.47-MariaDB-0ubuntu0.18.04.1
Error: https://pastebin.com/6Fn0Km6m

**Comment by ElBananaa** [comment]
> Hi, i have a problem to setup my sql in the ChatControlRed, this is my error, any solution?
> 
> https://pastebin.com/6Fn0Km6m

Hey!
Please follow the issue report format and update your current message in order to get support. Let us know once this is done.

**Comment by Syndr4** [comment]
@ElBananaa ready

**Comment by ElBananaa** [comment]
> @ElBananaa ready

Thanks,
We also need your `/chc debug` output file. Also include a copy of your database (remove any sensitive information)

**Comment by kangarko** [comment]
Update your MySQL Driver, see here: https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes the first answer
