### ISSUE TITLE
1.16.5: Announcement in locale file

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#553]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I just wanna ask how does this line works:

`    Type: '(bungee ? ''NETWORK '' : '''') + ''ANNOUNCEMENT'''`

Cause I though that word "Network" is only added when it's global announcement via bungeecord, so when specifying server:bungee, but even when I type just /ann (my alias) chat test, it's send with word NETWORK too from some reason.

![image](https://user-images.githubusercontent.com/18662086/105110325-a7c62980-5abe-11eb-9851-decaf678518a.png)

![image](https://user-images.githubusercontent.com/18662086/105110317-a4cb3900-5abe-11eb-9500-d04b85e442ea.png)

**Comment by kangarko** [comment]
Right now it'll always say Network if Bungee is enabled

**Comment by bobhenl** [comment]
and is it send to all servers or just to the one where it's executed from? When I don't specify server:bungee

**Comment by kangarko** [comment]
It's sent to all servers on the network where announcements are enabled

**Comment by bobhenl** [comment]
Wait and shouldn't it be rather on the one when I don't specify server:bungee? Couldn't we change this behaviour?

**Comment by kangarko** [comment]
Right now we can't but I'll be putting this down as a future suggestion
