### ISSUE TITLE
1.16.4: Command rule doesn't pick up color codes

### ISSUE THREAD

**Issue by Plum1111** [kangarko/ChatControl#554]
When I use something like '&6' to make it gold it works when im typing in the channel normally but when I use the command rule it just sends the message and the color code disappears as though it was never there. In this example I use '/g <message\>'.

```
# Catch "/g" command and join channel
match ^\/g$
dont verbose
then command channel join global write
then deny

#---- this is the one with the problem:
# Catch "/g <message>" and redirect to the global channel.
match ^(\/g) (.*)
dont verbose
then command channel send global $2
then deny
```

Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

**Comment by Plum1111** [comment]
also, it works just fine using /channel send <message\> just not the one using the rule

**Comment by kangarko** [comment]
This is intended, see Strip_Colors in settings.yml to disable this. Keep in mind disabling this will make players able to type ads/swears with colors in them and the filter wont catch up on this

**Comment by Plum1111** [comment]
@kangarko is there a way to disable it per rule?

**Comment by ElBananaa** [comment]
> @kangarko is there a way to disable it per rule?

Hey! If i'm not wrong, you could use: `before strip <regex>` in your rule in order to keep special characters, but I don't think there's anything possible for colors yet.

**Comment by Plum1111** [comment]
@ElBananaa Yeah I did ask about colors and not special characters
