### ISSUE TITLE
[item] like CMI

### ISSUE THREAD

**Issue by Syndr4** [kangarko/ChatControl#555]
Hello, I have this suggestion
it would be nice if the [item] system is similar to the CMI.
Like this https://i.imgur.com/7xwNNJ1.png

(If this can be added without the need for an update how could it be done?)

**Comment by Plum1111** [comment]
First of all, I don't think cmi has [item] (if it is I cant find it anywhere). And second, it's already included on install of the plugin in the variables folder in item.yml of which you can completely edit to however you want it to look.

**Comment by kangarko** [comment]
We already have this ...
