### ISSUE TITLE
Way to send placeholder in msg, to chat etc.

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#558]
Hi, could you please add way that players with specific permissions could send placeholder to msg or to whole chat? So if they will type for ex. {vault_group} in chat, vault group will be printed (probably differently for players, so good will be if parseother placeholder will work here (https://github.com/kangarko/ChatControl-Red/issues/460).

Similar feature is already in CMI at least in msg, toasts etc. 

- Now placeholders will not be translated when sending private messages. This only applies to the message itself
- Now toast command will support placeholders as long as you send it to one player and not using ALL variable. This is due to limitations of how toast works in general and we cant show dynamic text by using simple methods.
Can't find exact node when they mentioned they've added it, but it was added before.

2.
If you won't implement it, server won't be affected but this is good feature and it maybe could lead that someone will use CMI rather than chatcontrol.

**Comment by Plum1111** [comment]
Just make your own variable in the variables folder on chat control

**Comment by kangarko** [comment]
Hey, you can create your own chat variable for that, see item.yml in variables/ folder. Just duplicate that file, rename it and change Key and Value to something like that.

**OBS: Probably rename the file and Key to something else like vault_my_group so it doesn't collide**

<img width="838" alt="Screenshot 2021-01-26 at 10 38 04" src="https://user-images.githubusercontent.com/1918426/105827708-9ac79f80-5fc2-11eb-8765-dc13163e3a4e.png">

**Comment by bobhenl** [comment]
I didn't though especially this placeholder, but also bunch of others. I don't predict which placeholders should be recreated to the variables by me, but I would prefer way to send any placeholder we would like. Like we can in CMI, but ok, isn't especially needed.

**Comment by kangarko** [comment]
Not sure if you still need my help, if yes comment below
