### ISSUE TITLE
Way to change hex format

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#559]
Hi, could you please add way to change hex format that is detected in chat? So instead of #color it could detect (#color) with () too. Would be useful due to CMI /colorpicker handle, where are () included when you click on specific colors.

**Comment by bobhenl** [comment]
See this thread please https://github.com/Zrips/CMI/issues/4936#issuecomment-764539302

**Comment by ElBananaa** [comment]
> See this thread please [Zrips/CMI#4936 (comment)](https://github.com/Zrips/CMI/issues/4936#issuecomment-764539302)

Hey!
Kangarko already made a poll regarding this on discord in order to know which one he should use.
We don't know which one of the two formats won for now tho, so just be patient ^^

**Comment by kangarko** [comment]
Done, thanks
