### ISSUE TITLE
? on whitelist for commands does not work

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#56]
For my help system I use the `/?` command very often. 
Unfortunately adding `- ?` to the `Whitelist_Similarity:` section does not except `/?` from this check.

**Comment by kangarko** [comment]
The question mark is a special character in the YAML parser. Please use https://yaml-online-parser.appspot.com/ to check how the program sees your input.

I believe prefixing ? with '\' should fix it.

Example:
```
Whitelist:
  - \?
```

**Comment by EvilOlaf** [comment]
Unfortunately `\?` does not work for me.

**Comment by kangarko** [comment]
What about:

```
Whitelist:
  - '?'
```

**Comment by EvilOlaf** [comment]
Oh yes. `'?'` works perfect. Thank you!
