### ISSUE TITLE
1.16.4: How do you display the discord nickname in discord? [discord -> mc]

### ISSUE THREAD

**Issue by Plum1111** [kangarko/ChatControl#560]
When sending a message on discord and it is replaced and then put into the discord channel by the bot, it uses the discord username rather than the discord nickname. How do I make it show the discord nickname like it does ingame?

e.g. My discord username might be YellowMan but my discord nickname might be RedMan21954. In the discord chat it sends it as YellowMan but in game it shows RedMan21954 (which is the desirable outcome).

Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> When sending a message on discord and it is replaced and then put into the discord channel by the bot, it uses the discord username rather than the discord nickname. How do I make it show the discord nickname like it does ingame?
> 
> e.g. My discord username might be YellowMan but my discord nickname might be RedMan21954. In the discord chat it sends it as YellowMan but in game it shows RedMan21954 (which is the desirable outcome).
> 
> Minecraft Version: 1.16.4
> MySQL: false
> BungeeCord: false

Hey!
I don't think this is actually possible with the plugin. This is what Kangarko said in #495:

> While I was not able to get placeholder replacing to work, I made the following change:
> 
> We now use the linked Minecraft name in player messages coming from Discord. If players haven't linked their name, we simply use their Discord username.

**Comment by Plum1111** [comment]
I tried to really be precise in saying that it works **ingame** but not when it replaces it on **discord** and wondering if it's possible to make them the same

**Comment by kangarko** [comment]
Sorry not right now, can consider this to the future :)
