### ISSUE TITLE
MCmarket

### ISSUE THREAD

**Issue by dinobossytnew** [kangarko/ChatControl#561]
brother, I get that the license lasts 1 year before it said unlimited, it got me, could you help me?

**Comment by ElBananaa** [comment]
> brother, I get that the license lasts 1 year before it said unlimited, it got me, could you help me?

Hey! This is normal.
Kangarko plans to move to his own platform for the plugins, and the transfer will be done within one year.

**Comment by dinobossytnew** [comment]
> > hermano, entiendo que la licencia dura 1 año antes de que dijera ilimitada, me entendió, ¿podrían ayudarme?
> 
> ¡Oye! Esto es normal.
> Kangarko planea mudarse a su propia plataforma para los complementos, y la transferencia se realizará dentro de un año.

ok thaks brother ;)
