### ISSUE TITLE
Parrot function

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#562]
CHC v.8 had a very nice "Parrot" function. In hacked clients this is also known as "Annoy"
CHC v.10 doesn't have this. I would like to suggest to bring back this awesome function.

What it does?
This annoy/parrot function repeats everything a selected player says within a fraction of a second.

Why?
This function is not blocked by any other existing function as the 2 similar messages are from different players sending this message.
The only way this can be stopped is by intervention of a staff member.
This function can come in handy too when a slow bot attack is happening. As all bot-players talk (almost) the same sentences commanded by the attacker.

**Comment by ElBananaa** [comment]
> CHC v.8 had a very nice "Parrot" function. In hacked clients this is also known as "Annoy"
> CHC v.10 doesn't have this. I would like to suggest to bring back this awesome function.
> 
> What it does?
> This annoy/parrot function repeats everything a selected player says within a fraction of a second.
> 
> Why?
> This function is not blocked by any other existing function as the 2 similar messages are from different players sending this message.
> The only way this can be stopped is by intervention of a staff member.
> This function can come in handy too when a slow bot attack is happening. As all bot-players talk (almost) the same sentences commanded by the attacker.

Hey!
This feature is already in ChatControl-Red.
In your settings.yml, search for `Similarity:` under the `Anti_Spam:` part.
You can also configure auto commands for this feature under the `Warning_Points:` part.

**Comment by x1p** [comment]
Afaik that works only if you repeat yourself

The "annoy" is different. Are you familiar with the "parrot" function of CHC v.8?

**Comment by ElBananaa** [comment]
> Afaik that works only if you repeat yourself
> 
> The "annoy" is different. Are you familiar with the "parrot" function of CHC v.8?

I am yes, I guess that if it was removed, it's because this function isn't worth the potential resources loss.
Anyways, Kangarko will give you a better answer.

**Comment by kangarko** [comment]
Thanks, for now we decided to remove it since the usage was extremely low, if there's need asked for multiple times I can add this in my spare time again
