### ISSUE TITLE
1.16.5: Two first join messages

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#565]
Minecraft Version: 1.64.5
MySQL: true
BungeeCord: true

Hi, why this code please doesn't work? I wanted to put there require self to send special message, but it seems that this script in two messages doesn't work :/
```
group first_join
require sender script !player.hasPlayedBefore()
message: 
- &8&l[&5&l>&8&l] &7{pl_prefix+} &e&l{player} &7se připojil poprvé!

group test
delay 1 second
require sender script !player.hasPlayedBefore()
message: 
- &8&l[&5&l>&8&l] &7adasdasdasd
```

WHen using just one of codes it works great, but I need two of them :/. I wanna put `require self` to one message.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.64.5
> MySQL: true
> BungeeCord: true
> 
> Hi, why this code please doesn't work? I wanted to put there require self to send special message, but it seems that this script in two messages doesn't work :/
> 
> ```
> group first_join
> require sender script !player.hasPlayedBefore()
> message: 
> - &8&l[&5&l>&8&l] &7{pl_prefix+} &e&l{player} &7se připojil poprvé!
> 
> group test
> delay 1 second
> require sender script !player.hasPlayedBefore()
> message: 
> - &8&l[&5&l>&8&l] &7adasdasdasd
> ```
> 
> WHen using just one of codes it works great, but I need two of them :/. I wanna put `require self` to one message.

Hey!
I'm not sure to understand what you're trying to do.
You say that you want to use `require self`, but you don't use it in the example below.

Also, please provide us your `/chc debug` file.

**Comment by bobhenl** [comment]
Yeah I didn't write here require self, but it could be for ex. here:
```
group test
require self
delay 1 second
require sender script !player.hasPlayedBefore()
message: 
- &8&l[&5&l>&8&l] &7adasdasdasd
```

and not sure if debug is needed, cause if I use JUST ONE message with `require sender script !player.hasPlayedBefore()` it works, but it doesn't work when two of them are used. May you could try it too.

**Comment by ElBananaa** [comment]
Thanks for make things a bit clearer.
I tried on my test server, and I could reproduce the issue.
For an unknown reason, the 2nd message isn't sent.
```
group test
require self
delay 1 second
require sender script !player.hasPlayedBefore()
message: 
- &8&l[&5&l>&8&l] &7adasdasdasd

group firstjoinmessage
require self
delay 1 second
require sender script !player.hasPlayedBefore()
message: 
- &8&l[&5&l>&8&l] &esdsdsfdsfdfdsfdfdsf
```

Also, for some reason, I noticed that even if I use `delay 1 second` the message is only sent every 10 seconds.
You should wait for Kangarko to fix this (in case this is an actual issue).
I posted a suggestion a few days ago to add a proper welcome message system, you should also consider taking a look at it: #545

**Comment by bobhenl** [comment]
How exactly does these newly added placeholders work?
{last_active}
and 
{last_login_time_elapsed}

Some example?

**Comment by ElBananaa** [comment]
> How exactly does these newly added placeholders work?
> {last_active}
> and
> {last_login_time_elapsed}
> 
> Some example?

Hey!
Well, there's nothing to really explain.
{last_active} shows your last active date
{last_login_time_elapsed} shows the time elasped between your latest connection and your actual connection, in seconds.

**Comment by bobhenl** [comment]
And when player didn't connect (so connected first time), and I'll use last_active, could it solve my issue somehow? What it will return if he didn't play on server yet? And how to use these placeholders in messages?
```
group test
require self
delay 1 second
require sender script !player.hasPlayedBefore()
message: 
- &8&l[&5&l>&8&l] &7adasdasdasd

group firstjoinmessage
require self
delay 1 second
require sender script !player.hasPlayedBefore()
message: 
- &8&l[&5&l>&8&l] &esdsdsfdsfdfdsfdfdsf
```

**Comment by ElBananaa** [comment]
> And when player didn't connect (so connected first time), and I'll use last_active, could it solve my issue somehow? What it will return if he didn't play on server yet? And how to use these placeholders in messages?
> 
> ```
> group test
> require self
> delay 1 second
> require sender script !player.hasPlayedBefore()
> message: 
> - &8&l[&5&l>&8&l] &7adasdasdasd
> 
> group firstjoinmessage
> require self
> delay 1 second
> require sender script !player.hasPlayedBefore()
> message: 
> - &8&l[&5&l>&8&l] &esdsdsfdsfdfdsfdfdsf
> ```

The placeholders won't return anything if the place didn't join the server at least one time.
Using these placeholders won't solve your issue, they are just used to give more informations to players.
As I said, {last_active} shows a date, and {last_login_time_elapsed} shows the time elapsed between 2 player connection in seconds.

**Comment by kangarko** [comment]
The messages are read from top to bottom, all players only will see the first message they are eligible for.

Next versions will bring Stop_On_First_Match key that can be set to false to disable this.

Also the "delay" does not send the message later here, it will prevent message being sent multiple times in the period of X seconds, for example if delay is set to 15 seconds it means if the player reconnects within 15 seconds the message won't be shown.
