### ISSUE TITLE
1.16.5: Disallow * in rules? Like W*nker

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#569]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, how could I please disallow players do w*nker, wan*er etc.?
```
#wanker
match (w+(\W|\d|_)*(a|á)+(\W|\d|_)*(n|ň)+(\W|\d|_)*k+(\W|\d|_)*(e|ě|é)+(\W|\d|_)*(r|ř)+(\W|\d|_)*)
group swear
ignore perm chatcontrol.bypass.swear
then replace @prolong *
then sound <AMBIENT_CAVE>

```

**Comment by kangarko** [comment]
You can use the backslash \ before the * as the letter such as instead:

w+(\W|\d|_)*

you use

(w|\*)+(\W|\d|_)*

You can also test this via regex101.com before dropping in the game and they will explain how this works.
