### ISSUE TITLE
1.16.4 | tab complete only work if you are op

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#57]
Commands work but you have to use ? for get the commands if you not are op.

**Comment by kangarko** [comment]
Interesting, have you tried to find what permission will enable tab-completion?

**Comment by broken1arrow** [comment]
> Interesting, have you tried to find what permission will enable tab-completion?

no, but I can see if I find any.

It is chatcontrol.bypass.tabcomplete , but I think is strange setup of perm. You should do like this chatcontrol.tabcomplete (bypass are more if you should force you to pass rules or perms).

**Comment by kangarko** [comment]
Can you give me an example of a command where this is broken?

**Comment by broken1arrow** [comment]
> Can you give me an example of a command where this is broken?

What i mean are the name on the perm is for me little confusing.

**Comment by kangarko** [comment]
Set Tab_Complete.Minimum_Length to 0. This is a feature.

**Comment by broken1arrow** [comment]
right I get what i should do, is set on zero when i update and get new settings file.
