### ISSUE TITLE
[PREMIUM] Incompatible plugins? Important!

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#57]
Since i'm using ChatControl I have some issues with some plugins.

_What plugins are you having issues with?_
- PetBlocks, BattlePets and PremiumVanish.

_Whats the problem you encounter?_
PetBlocks and BattlePets both have a rename option in the GUI. If you click on that option in the chat it will say ''Please enter the name of your pet:'' when you do so, it will give the pet the correct name, but will also send the message in the chat. This makes the chat messy if everyone is renaming their pets and it will also be send in the chat.

For PremiumVanish, it  should block being able to send a message when you are in vanish. Unfortunatly it just sends the message to everyone in the server and doesn't get blocked anymore. The developer of PremiumVanish tried to fix this using a chat priority event system. But even while I gave it the highest priority event, it wasn't working.

This all, for sure, didn't happen while using DeluxeChat.

I'm using ChatControl Pro with EssentialsX.

**Comment by kangarko** [comment]
_I cannot test premium plugins as I don't own them._

With the *pet plugins, it seems like a priority issue. Try setting the Listener_Priority to following:
```
Listener_Priority:
  Formatter: HIGHEST
  Checker: NORMAL
```

For the PremiumVanish, try playing with the Formatter priority above, try following values and see if one of them works: LOWEST, LOW, NORMAL, HIGH and HIGHEST

**Comment by Sikatsu** [comment]
I do understand you can't test it because of that, but we are able to test it together.

I tried setting is to highest, but it still isn't working. I'm really sure it all worked fine using DeluxeChat.

**Comment by Sikatsu** [comment]
It doesn't work with mcmmo either, tried everything using that listerner priority.

Also as I said I already tried chat priorities from PremiumVanish, which didn't work either..

If non of it can be fixed, I'll probably be switching back to DeluxeChat, because these issues are worse then not being able to send a private message to an essentials nickname.

**Comment by kangarko** [comment]
I've changed some logic in sending message, can you try the latest version released a couple of minutes ago?

**Comment by Sikatsu** [comment]
Sure, I will test it. I can't reload the plugin using Plugman right? Only a server restart will work?

**Comment by Sikatsu** [comment]
I ordered a quick test server, gonna set it up real quick and let you know.

**Comment by Sikatsu** [comment]
I tested your new update.

Using interactive chat:
- AdminChat, PartyChat, PetBlocks, BattlePets, PremiumVanish are broken with the issues above.

Without using interactive chat:
- Everything above, is working normally.

However, Multicraft seems to break using my current ChatControl files. When I completely reset the ChatControl files, multicraft works again.

**Comment by Sikatsu** [comment]
This has been fixed.
