### ISSUE TITLE
Improved pings/nicknames

### ISSUE THREAD

**Issue by james090500** [kangarko/ChatControl#570]
Users now and again set their nicknames to a single character and everyime someone types in chat if a single character is in the sentence they get pinged. 

Maybe only ping users if there is a space in the message? 

For example, a staff member is referencing "James_OverKill" but it pings me (James)

![image](https://user-images.githubusercontent.com/20372645/105616100-37741c80-5dcc-11eb-91f4-0b83d6db8805.png)

**Comment by kangarko** [comment]
Thanks will get patched
