### ISSUE TITLE
Suggestion Slowchat

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#571]
There are situations where chat explodes.
Wouldn't it be nice if we could turn on/off slowchat when needed?

I would like to suggest:
- a (toggle) command like `/chc slowchat`
- which changes the Anti_Spam.Chat.Delay value instantly to a pre-defined value, e.g. 60 sec.
- broadcast a message like: "Slowchat has been turned on"

**Comment by kangarko** [comment]
Thanks for your suggestion however due to time constrains I decided not to implement this right now.
