### ISSUE TITLE
1.16.5: Admin chat is visible on dynmap °_ °

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#574]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I've just noticed that admin chat is visible on dynmap... When I switch to admin chat channel, then players can see it from dynmap... Hopefully it could be fixed.

**Comment by kangarko** [comment]
I don't know how this can be fixed? Was this problem also happening on ChatControl Pro?

**Comment by bobhenl** [comment]
I didn't use dynmap before. But the problem is probably that it doesn't detect channels, maybe you can add integration there

**Comment by bobhenl** [comment]
As I heard, admin chat works in MCMMO even when you type /a -> enables admin chat, like in ChatControlPro switches chat, and then type text, it doesn't appear on dynmap. So it probably could be solved somehow. May you could inspire there.

**Comment by kangarko** [comment]
Will add "Cancel_Event" true/false option. Set to true if you want this channel to be hidden from DynMap or other plugins.

**Comment by bobhenl** [comment]
Hopefully other channels could be hidden too?

**Comment by kangarko** [comment]
Yes use Cancel_Event for each channel you want this to have
