### ISSUE TITLE
1.16.3: How to join only read channels?

### ISSUE THREAD

**Issue by Toki-teki** [kangarko/ChatControl#576]
Minecraft Version: 1.16.3
MySQL: true
BungeeCord: true

I have channels:
local, global, news

I gave the players naggings:
chatcontrol.channel.join
chatcontrol.channel.join.local.write
chatcontrol.channel.join.global.write
chatcontrol.channel.autojoin.local.write
chatcontrol.channel.autojoin.global.write
chatcontrol.channel.leave(all)
chatcontrol.channel.autojoin.news.read
chatcontrol.channel.join.news.read

Problem on screenshot: no say all channels
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5863123/debug.zip)

![image](https://user-images.githubusercontent.com/74260160/105642770-e54efc00-5e9c-11eb-84bc-5d7d53e5b24b.png)

**Comment by ElBananaa** [comment]
Hey!
You can only join one channel in writing mode, you need to join the others in read mode.
Also, there's only 2 channels: hub and news, so these permissions are useless:
```
chatcontrol.channel.join.local.write
chatcontrol.channel.join.global.write
chatcontrol.channel.autojoin.local.write
chatcontrol.channel.autojoin.global.write
```
Follow the wiki to setup your permissions correctly. https://github.com/kangarko/ChatControl-Red/wiki/Permissions

**Comment by Toki-teki** [comment]
I have bungeecord.
"global" and "local" channels are used on other servers

I do not understand why the player does not see the "news" channel in the channel list

**Comment by ElBananaa** [comment]
> I have bungeecord.
> "global" and "local" channels are used on other servers
> 
> I do not understand why the player does not see the "news" channel in the channel list

Hey! I don't think you can join channels that are not on your server. As I said, check your permission setup and follow the link I gave you.

**Comment by Toki-teki** [comment]
I think you misunderstood.

I want players to be able to connect to the "news" channel, but not be able to post there. But this channel is not in the channel list


I have already configured all the necessary permissions for this

**Comment by ElBananaa** [comment]
> I think you misunderstood.
> 
> I want players to be able to connect to the "news" channel, but not be able to post there. But this channel is not in the channel list
> 
> I have already configured all the necessary permissions for this

`chatcontrol.channel.join.news.read`,
`chatcontrol.channel.autojoin.news.read` and it'll work.
If it doesn't, reset your database and it'll work.

**Comment by Toki-teki** [comment]
my perms list:
![image](https://user-images.githubusercontent.com/74260160/105757641-46d79f00-5f5f-11eb-88a9-b95ad1f96d8f.png)
not work

**Comment by Toki-teki** [comment]
I understood.
If the player has permission to the "read" channel, then he will not see this channel in the /ch.
Only "write" is displayed in the /ch.
Right?

**Comment by ElBananaa** [comment]
> I understood.
> If the player has permission to the "read" channel, then he will not see this channel in the /ch.
> Only "write" is displayed in the /ch.
> Right?

No, afaik, read channels should also be displayed there.
The fact is, as I said, your perms are broken.
You are giving write perms to multiple channels even tho this isn't possible, you can't have more than 1 write-channel at once.
Since everything is working perfectly on my side, I can only guess you did something wrong with your setup.
![image](https://user-images.githubusercontent.com/53318613/105775767-a0dc6280-5f67-11eb-9a25-439b27dec9c7.png)
