### ISSUE TITLE
1.16.4: Toggle chat bungee support

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#578]
Currently when you toggle the chat, this only works per-server. Since my chat is global on the whole network, I would love it if I can disable the chat of all servers together aka bungee compatible.

**Comment by kangarko** [comment]
Sorry what do you mean? What command is that?

**Comment by Sikatsu** [comment]
The /toggle chat command from ChatControl? It works per-server, but if you have a bungee chat it doesn't disable the whole bungee chat.

![image](https://user-images.githubusercontent.com/5664135/106004936-02114c80-60b4-11eb-865e-5f9f751a0b88.png)

**Comment by kangarko** [comment]
Thanks, fixed
