### ISSUE TITLE
1.16.4 BungeeCord and MySql - Created my own channels and they are giving out errors

### ISSUE THREAD

**Issue by Godlycreations** [kangarko/ChatControl#58]
I created 4 of my own channels and followed the formats listed on the wiki. Which appear to be the same as when I used the format.yml in CHC 8, just separate ymls for each channel type. I also adjusted some of the settings in the settings.yml. Chat was working fine using the default channels that you provided, but when I made my own, it started giving out errors. I am attaching the settings.yml and the four channel formats with my error logs. I have set both servers up with these same configs, so you only need one set of configs to know what both servers are using. I changed the yml file extensions to txt only to attach them to this issue report. If you need additional information, please let me know. Thanks for all the hard work on this, I am loving what I am seeing so far!

[elyon-error.log](https://github.com/kangarko/ChatControl-Red/files/5539592/elyon-error.log)
[es-error.log](https://github.com/kangarko/ChatControl-Red/files/5539593/es-error.log)
[admin.txt](https://github.com/kangarko/ChatControl-Red/files/5539596/admin.txt)
[global.txt](https://github.com/kangarko/ChatControl-Red/files/5539597/global.txt)
[guest.txt](https://github.com/kangarko/ChatControl-Red/files/5539598/guest.txt)
[lost.txt](https://github.com/kangarko/ChatControl-Red/files/5539599/lost.txt)
[settings.txt](https://github.com/kangarko/ChatControl-Red/files/5541096/settings.txt)

**Comment by ElBananaa** [comment]
Made some tests (Paper 1.16.4, No mysql/no bungeecord) and it looks like this is something related to the database. I had the same issue. Removing the data.db file and letting the plugin generating a new one with the new channels fixed the problem for me)

**Comment by Godlycreations** [comment]
It worked for me too, I cleared the db and everything came back to life! Thanks bananaa
