### ISSUE TITLE
Cooldown per permission

### ISSUE THREAD

**Issue by Intensearmadillo** [kangarko/ChatControl#58]
If a player is in a extremely high rank, or a player is a donator to the server, they are less likely to spam the chat, where as a new, untrusted player (or just someone joining to troll the chat) is one of the major problems. I'd appreciate it if you could add chat cooldown per permission for loyal members of servers.
Thanks!

**Comment by kangarko** [comment]
I don't think it is possible, in case you want to have dynamic permissions like chatcontrol.delay.5 for five second delay, etc.
http://bukkit.org/threads/setting-variable-permission-values.101235/
looping through many numbers is not a good solution
correct me if I am wrong

**Comment by MylesIsCool** [comment]
Would it be more suitable that you could make permissions in the config which would then provide donor ranks such as:

permissions:
 chatcontrol.donator:
   - spam: 6

And that allows dynamic creation of permissions to fit a server owners needs.

**Comment by Intensearmadillo** [comment]
This guy knows what he's talking about! <3

**Comment by kangarko** [comment]
I saw that in other plugins, so it's possible. It will probably be implemented within a few next versions, please provide my some examples of what you want to be configurable.

**Comment by Intensearmadillo** [comment]
cooldowns:
   //bla bla
   loyalty-cooldowns: false
      groups:
         - A : defaultCooldown
         - Staff : reducedCooldown

Listens to groups, or, some sort of permission setup. Thanks a lot, many server owners will love this tweak.

**Comment by kangarko** [comment]
But cooldowns for what? And also expect it to be little bit simplier, like @MylesIsCool said, e.g.

custom-permissions:
  vip:
    chat-delay: 2
    command-delay 1
  moderator:
    chat-delay: 1
    command-delay: 1
  admin:
    chat-delay: 0
    #command-delay: 1 // If you don't specify it will be taken from global one.

**Comment by Intensearmadillo** [comment]
That works. Perhaps have a toggle for custom permissions, default to false, for people who do not wish to use them. That looks really good to me, though.

**Comment by Intensearmadillo** [comment]
Any more information on Permission Cool downs?
Thanks alot!

**Comment by kangarko** [comment]
Not yet I am currently busy, and as I previously stated on the spigot forum I will rather focus on fixing bugs and improving of current features, I don't have time for everything.

**Comment by Intensearmadillo** [comment]
Okay thanks, I was only inquiring. Keep up the good work sir!

**Comment by kangarko** [comment]
Sorry for the delay, it should be working for message and command delay. Check out v5.1.0.

**Comment by Intensearmadillo** [comment]
Fantastic. Thanks a bunch. I know everyones going to love this idea

**Comment by kangarko** [comment]
@MylesIsCool and @Intensearmadillo maybe you also appreciate custom join/kick/leave messages per different groups :)
