### ISSUE TITLE
ChatControl breaks multicraft chat?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#58]
Since I'm using ChatControl Pro, my chat in Multicraft is only showing connected and disconnected messages like shown in the image: http://prntscr.com/a2wk3o

I contacted the multicraft team, unfortunatly they advised me to check the plugins, once again it seems to work with DeluxeChat, so this is probably related to ChatControl.

**Comment by kangarko** [comment]
The console filter seems to be incompatible with Multicraft. You can disable it by setting **Console.Filter.Enabled** to false in settings.yml

**Comment by Sikatsu** [comment]
Hmm I saw that # tag saying about multicraft thought it wasn't about the chat, thanks for that!

**Comment by Sikatsu** [comment]
@kangarko Well it's still not working after disabling that option as you see: http://prntscr.com/a3kwc4
Restarted the server to make sure.

**Comment by kangarko** [comment]
Does this also happen without ChatControl?

**Comment by Sikatsu** [comment]
It didn't happen using DeluxeChat or EssentialsChat, yes.

**Comment by kangarko** [comment]
But have you tried removing ChatControl and seeing if it still happens?

**Comment by Sikatsu** [comment]
Is there a possibility for you to come online at my test server?
