### ISSUE TITLE
1.16.5: Weird regex match

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#580]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I have a weird regex match...

`match (?:(?!dycky)d+(\W|\d|_)*(i|y|í|ý|ï|ÿ)+(\W|\d|_)*(c|č)+(\W|\d|_)*k(?<!pandick|lidick))|(?:(?!dy k|)(d|ď)+(\W|\d|_)*(y|i|ý|í|ï|ÿ)+(\W|\d|_)*k+(\W|\d|_)*)|(p+(\W|\d|_)*(y|ý|i|í|ÿ|ï)+(\W|\d|_)*j+(\W|\d|_)*)`
matches word 'přijd' as group 12 that's explained as:
![image](https://user-images.githubusercontent.com/18662086/105760886-aaa79b00-5f52-11eb-92a6-2d827166a01e.png)

> 12th Capturing Group (\W|\d|_)*
> * Quantifier — Matches between zero and unlimited times, as many times as possible, giving back as needed (greedy)
> A repeated capturing group will only capture the last iteration. Put a capturing group around the repeated group to capture all iterations or use a non-capturing group instead if you're not interested in the data
> 1st Alternative \W
> \W matches any non-word character (equal to [^a-zA-Z0-9_])
> 2nd Alternative \d
> \d matches a digit (equal to [0-9])
> 3rd Alternative _

But the weird is, that it matches only "ž, š,ř etc...", this means that these characters aren't non-word characters or? How can I fix it?

I need usage of word "Přijde"

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, I have a weird regex match...
> 
> `match (?:(?!dycky)d+(\W|\d|_)*(i|y|í|ý|ï|ÿ)+(\W|\d|_)*(c|č)+(\W|\d|_)*k(?<!pandick|lidick))|(?:(?!dy k|)(d|ď)+(\W|\d|_)*(y|i|ý|í|ï|ÿ)+(\W|\d|_)*k+(\W|\d|_)*)|(p+(\W|\d|_)*(y|ý|i|í|ÿ|ï)+(\W|\d|_)*j+(\W|\d|_)*)`
> matches word 'přijd' as group 12 that's explained as:
> ![image](https://user-images.githubusercontent.com/18662086/105760886-aaa79b00-5f52-11eb-92a6-2d827166a01e.png)
> 
> > 12th Capturing Group (\W|\d|_)*
> > 
> > * Quantifier — Matches between zero and unlimited times, as many times as possible, giving back as needed (greedy)
> >   A repeated capturing group will only capture the last iteration. Put a capturing group around the repeated group to capture all iterations or use a non-capturing group instead if you're not interested in the data
> >   1st Alternative \W
> >   \W matches any non-word character (equal to [^a-zA-Z0-9_])
> >   2nd Alternative \d
> >   \d matches a digit (equal to [0-9])
> >   3rd Alternative _
> 
> But the weird is, that it matches only "ž, š,ř etc...", this means that these characters aren't non-word characters or? How can I fix it?
> 
> I need usage of word "Přijde"

Hey!
In your rule, add the following line if you enabled `Strip_Accents:` in the settings file:
`ignore string prijde`
if it's set to false, instead use:
`ignore string přijde`

it should fix the issue.

**Comment by bobhenl** [comment]
Yes, but why it's matched? every characters like ěščřž etc are matched :/

**Comment by kangarko** [comment]
Probably because they are non-standard ascii letters but Czech letters instead...

**Comment by bobhenl** [comment]
Oh, I thought it will be something with it, but I thought it's supported by ASCII. Couldn't we add somehow this character as supported or add them to ASCII?

**Comment by kangarko** [comment]
That's out of my control unfortunately... you could replace \W with [^a-zA-Z0-9_ěščřž] maybe?
