### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by cades66** [kangarko/ChatControl#581]
Minecraft Version: 1.16.5
MySQL: true - Error when trying to use it
BungeeCord: true

https://paste.gg/p/anonymous/f3d15866396c4deea0199f6b295e6ca2

The above link is the full error I am recieving. I am not able to attach a debug zip as it says the plugin is disabled. I have entered the correct MySQL info but it is throwing up errors.

**Comment by cades66** [comment]
[error.log](https://github.com/kangarko/ChatControl-Red/files/5870173/error.log)
Here's my error.log file.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true - Error when trying to use it
> BungeeCord: true
> 
> https://paste.gg/p/anonymous/f3d15866396c4deea0199f6b295e6ca2
> 
> The above link is the full error I am recieving. I am not able to attach a debug zip as it says the plugin is disabled. I have entered the correct MySQL info but it is throwing up errors.

Hey,
This is a known issue, you need to update your mysql driver. To proceed, follow the steps given in the first answer here: https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes
If you can't update your mysql driver for some reasons, contact your hosting provider, and ask them to do it.

I'm closing this issue, once again, feel free to comment down below if the issue persists, or open a new ticket if you need anything else.
