### ISSUE TITLE
1.16.5: message toggle bug

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#583]
So interestingly i noticed my timed messages aren't working (seperate issue) but when i went to try and toggle them off/on it only "disabled":

https://gyazo.com/b6f9f8e822420ba4dcfbc2d289902309

paper 1.16.5 build 444 - Chc Red 10.1.21

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
So sorry for a late reply this time, I could not reproduce your issue having just one message group "default". Please attach your zip.

<img width="488" alt="Screenshot 2021-02-04 at 10 15 02" src="https://user-images.githubusercontent.com/1918426/106870837-dacd0780-66d1-11eb-9635-8ccaef2d872b.png">

**Comment by LogGits** [comment]
Fairly confident this is resolved with #590 and I'm too afraid to test incase it perma disables timed.rs again haha
