### ISSUE TITLE
1.16.5: How to add other servers to Chc forward?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#584]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

![image](https://user-images.githubusercontent.com/18662086/105856707-d0cc4a00-5fe9-11eb-9784-abd02d1b6c56.png)
Hi, on every server I see just bungee and it's server, why I don't see there other servers? How to forward then to another servers than bungee?
![image](https://user-images.githubusercontent.com/18662086/105856775-dfb2fc80-5fe9-11eb-88b0-82f230ee811c.png)
![image](https://user-images.githubusercontent.com/18662086/105856803-e6da0a80-5fe9-11eb-950f-6d4588894884.png)
![image](https://user-images.githubusercontent.com/18662086/105857856-fc036900-5fea-11eb-9c99-a38a8799d0f3.png)

Isn't it a bug? I didn't find any information how to enable it, neither in settings of chatcontrolred and neither in bungeecontrol... servers are using same mysql and are on same bungee network.
And I have set server-name in server.properties.

**Comment by TheIntolerant** [comment]
As stated when you run ``/chc forward`` 
**NOTE: You cannot send commands to empty servers.**

Meaning a player must on the specific server for you to send a command to that server via ``/chc forword``.

![1513513513516513f5131](https://user-images.githubusercontent.com/48093184/105946607-ae0a6600-60bb-11eb-8b84-58884a0972d1.JPG)

**Comment by ElBananaa** [comment]
Hey!

Thanks to @iTz-MrAnonymous for answering you.
I'm closing this issue, feel free to keep sending messages here if you need anything else, or open a new ticket if it's unrelated to this one.

**Comment by bobhenl** [comment]
And is it possible to send command from proxy too via bungeecontrol? Cause chc forward or chc bungeecontrol forward doesn't work.

**Comment by kangarko** [comment]
No sorry, right now you can't forward from BungeeControl
