### ISSUE TITLE
1.16.5: Code body locale formatting bug?

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#585]
regarding:
```yaml
Chat_Body: |-
      &7 ------------------ {type} ------------------ 
      &f{lines}
```
I want to get the message without the formatting, {lines} seems to apply this appearance: `&7%message%`. As a result, I'm not able to achieve the white text which should be displayed in the above formatting

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Sorry what key is this?

**Comment by LogGits** [comment]
I dont have access to my comp rn but it's the `/chc announce chat` message formatting inside the locale en file

**Comment by LogGits** [comment]
UPDATE: 
**localization>messages_en.yml**
Key: `Commands.Announce.Chat_Body`

**Comment by kangarko** [comment]
<img width="286" alt="Screenshot 2021-01-30 at 16 13 52" src="https://user-images.githubusercontent.com/1918426/106359954-29ffea80-6316-11eb-9ff5-b69deb2f43f8.png">
Will add a new key to configure that color
