### ISSUE TITLE
1.16.5: How do you make chat colors permanent?

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#586]
I believe this should be possible but for some reason I can’t get chat colors to stick when a player relogs. Anyone know if there’s a setting or permission for this?

This is a question, but for good measure I uploaded the debug.zip in case it's a bug
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5874484/debug.zip)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> I believe this should be possible but for some reason I can’t get chat colors to stick when a player relogs. Anyone know if there’s a setting or permission for this?
> 
> This is a question, but for good measure I uploaded the debug.zip in case it's a bug
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5874484/debug.zip)
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
Could you explain a bit further your issue please.
What do you mean by "chat colors"? The message colors? The player chat color selected in `/chc color menu`? Or something else?

**Comment by Squeej** [comment]
My apologies, yes when players use /chc color menu, basically anything that's chosen in the gui only appears to last while the player is logged in and then resets after a while

edit: Tested it a bit further and it seems to be intermittent, could possibly be a bug

**Comment by kangarko** [comment]
Please specify when exactly will the colors stop applying? Just tested /chc reload and restart and they are persistent.

**Comment by Squeej** [comment]
Looks like it's fine, a player kept reporting it but I was only able to replicate the issue once. If I can find a reason or cause that's not user error I'll update with the info. Closing this issue

**Comment by Squeej** [comment]
Looks like it was just an issue with group manager, haven't heard any reports since switching to luckperms

**Comment by ElBananaa** [comment]
> Looks like it was just an issue with group manager, haven't heard any reports since switching to luckperms

Hey!
Alright, thanks for letting us know! Feel free to open a new issue if you need anything else or if this issue happens again.
