### ISSUE TITLE
Minecraft names in tab-complete for private messages

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#589]
I'd like it if instead of nicknames, the minecraft names would show up in the tab-complete of the private message system.
As currently when you private message eachother, it shows the minecraft name rather then nicknames, but the tab-complete shows the nicknames. Players would prefer if it showed the minecraft name in both places.

**Comment by kangarko** [comment]
Thanks however the whole system is built to prefer nicknames if they are used. Right now theres no plans on doing such a rewrite.
