### ISSUE TITLE
[PREMIUM] Issues with mcmmo's AdminChat and PartyChat!

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#59]
It doesn't only break the AdminChat from mcmmo, it also breaks the PartyChat.

http://prntscr.com/a0nasg

The AdminChat has been fixed with the switch you made and using MyCommand, but the PartyChat really needs to work aswell. I have a couple of parties on my server, so my players are really annoyed by this currently. Hope there will be a fix for this.

These are 3 (The other 2 issues I created on github too) pretty annoying issues I have using ChatControl. While DeluxeChat didn't deliver the option to send pm's to essentials nicknames, it was stable. Looking forward that my issues will be solved. :)

**Comment by EvilOlaf** [comment]
I am also using mcMMO and planning to use CHC. MyCommand as well. Can you tell me more about the adminchat issue and how you could fix it?

Cheers
Olaf

**Comment by Sikatsu** [comment]
McMMO delivers the option /ac to enable the adminchat and /ac <message> if you only want to send one single message to the adminchat. Unfortunatly, the /ac to enable the adminchat will break using ChatControl.

ChatControl does have it's own adminchat, but didn't had the option to enable it by default like McMMO has. So, Kongarko added the command /chc ach switch to enable the adminchat by default.

Now, I didn't like the adminchat format from ChatControl, but you can change the format exactly to how it looks with the adminchat from mcmmo using the following in your settings.yml:

`  Admin_Chat:
    Parts:
      Bracket_Start:
        Message: "&b["
      Player:
        Message: "&c%nick"
      Bracket_End:
        Message: "&b] &b"
      Message:
        Message: "%message"`

Then using MyCommand I made an alias for the /chc ach switch command. The alias I used is /a.

So now you have /a to enable the adminchat and /ac <message> to just send a single message to the adminchat. The only difference there is, is that /ac won't enable the adminchat by default, but /a will.

Hope I was clear enough. :)

There is no fix for the partychat tho, so hope the developer will be able to fix this soon.

**Comment by kangarko** [comment]
As #57 is relating to the same problem, please continue the discussion on one place. Try adjusting the priority like I advised there.
