### ISSUE TITLE
1.16.5: {player} in join.rs and quit.rs

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#591]
Noticed that in join.rs (and I'm assuming quit.rs) {player} is set as the receiver in this case:
```r
group default
ignore receiver perm test.staff
message: 
- '&f{player} has joined the server.'

group staff
require receiver perm test.staff
message:
- '[JSON] {"text": "&cX &f{player} has joined the server.","hoverEvent": {"action": "show_text","value": {"text": "&click to do da ting"}}}'
```
It appears that for players with `test.staff` they receive the second one as expected, however, `{player}` placeholder is changing to the receivers name instead of the player who joined. This is only for the second one and not the first, meaning the first one has the joining players name and the second has the receivers name for some reason.

CHC Red 10.1.21
Minecraft Version: 1.16.5 paper 444
MySQL: false
BungeeCord: false

**Comment by TheIntolerant** [comment]
I could be incorrect but I believe with what you are trying to do you should be using 
```
require sender perm <permission>
ignore sender perm <permission>
```
instead, as I believe you are trying to send a message based on what permission the "sender" has aka the person joining the server, and not based on what permission the receiver has aka the person already on the server.

**Comment by kangarko** [comment]
Thanks, will be fixed
