### ISSUE TITLE
Added support [Bungee Velocity]

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#592]
BBFor me, Velocity performance is better than BungeeCord, but Velocity does not support any Bukkit and other related codes, so I cannot install BungeeControl-Red on it. At present, some plugins start to support Velocity, and I hope that ChatControl Red can also support it.

**Comment by kangarko** [comment]
Thanks, we had multiple people request it already, I am not in a position where I have enough time and resources to add this in right now but it's definitely on the table...

**Comment by BearLeonLight** [comment]
Thanks for your hard work, just come back if you have time, I can continue to use other agents first.

**Comment by kangarko** [comment]
Thanks — If you know a trusted developer I can share sources for BungeeControl Red and he can port this :)

**Comment by cades66** [comment]
> 
> 
> Thanks — If you know a trusted developer I can share sources for BungeeControl Red and he can port this :)

On a newly opened ticket, a developer is willing to port over BungeeControl Red to Velocity. See https://github.com/kangarko/ChatControl-Red/issues/724
