### ISSUE TITLE
1.16.5: All commands are disabled while muted in CMI or mute expires

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#598]
Players cannot perform any commands while being muted with CMI. After mute EXPIRES, they still cannot perform any commands. I cannot fix this in any way for a player, he is effectively banned.

![image](https://user-images.githubusercontent.com/43506080/106124187-6cf86d00-6120-11eb-8470-4aef63eb5e18.png)

Why does CC even listens to any commands other than /ch and /tell?????

CMI version: 8.8.0.5
CCR version: 10.1.21

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by radiant-ai** [comment]
After investigation: when the mute expires, CC does not remove the mute from the player. /chc reload is required to fix this.
ALL commands are muted when player is muted. So there are actually two issues.

**Comment by radiant-ai** [comment]
Is it going to be fixed? I cannot upgrade from the Pro version to Red because of this.

**Comment by kangarko** [comment]
Thank you, apologies for the delay. Fixed both.
