### ISSUE TITLE
OpenInv conflicts with default Chatcontrol config

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#6]
When trying to use `/openinv` the default rule for `/op` will block that.
If there is a wildcard behind `op` it should be removed.

ChatControl 5.1.7
OpenInv 2.3.3
Spigot 1.8.8

**Comment by kangarko** [comment]
Go to plugins/ChatControl/rules/commands.txt and edit or remove the default rule.

```
match ^/op
ignore perm chatcontrol.bypass.rules
id /op
then warn &bYes, we are giving away OPs. Seriously, what did you expect?!
then notify chatcontrol.notify.rulesalert &8[&7ID %ruleID&8] &7%player: &f%message
then deny
then log
```

**Comment by EvilOlaf** [comment]
I am aware of this. My thinking was to alter the default settings to listen explicitly to /op with argument  only and not /op* with argument ;)

**Comment by EvilOlaf** [comment]
Meaning the default setting with is shipped with chatcontrol at installation.

**Comment by kangarko** [comment]
Oh I understand now. I will edit it appropriately. I am sorry I didn't know you are aware, there's been to many cases of users complaining about the default settings (apparently they didn't even take a look at the files)

**Comment by kangarko** [comment]
The predefined examples are terrible, I gotta do something with them. I made them up in a hurry and that's like it persisted since the.

**Comment by EvilOlaf** [comment]
There may be question from my side somewhen in the future related to configuration... But could not find some mood to upgrade to v5 yet :P

**Comment by kangarko** [comment]
Feel free to ask :) So you are still on 4.x.x ? There is already v6 out. I cannot remember much about the 4th generation besides some weird bugs with permissions.

**Comment by EvilOlaf** [comment]
As from my side I just noted the the chat clear bypass permission does not work as expected, but not sure if this one wasn't introduced in v5.

Yes i am still on 4.5.7. Works well on newest spigot release. As written above there is some lack of mood to rewrite the configuration with the update as it will be marked as incompatible an not being used.

**Comment by kangarko** [comment]
The permissions acted weirdly back in v4. This is fixed in 5.0.0 and upwards. If you want, I can take a look at your configuration and do a migrate to 5.1.7, shouldn't be so hard.

**Comment by EvilOlaf** [comment]
Thank you for the offer. I appreciate it. 

Ya probably it isn't that hard. Just the thing is you have to get into a new syntax... Maybe some day but not now :D

**Comment by kangarko** [comment]
What now syntax? The settings.yml looks almost the same. The only new thing are the rules, which are very similar to PwnFilter's (it inspired me to create rules after I saw it's been one year without updates). 
But if you will update one day, feel free to PM me if you have any questions. Good luck.

**Comment by EvilOlaf** [comment]
Never used PwnFilter ;)

Just for the bottom line: Thank you for your great work with ChatControl :).

**Comment by kangarko** [comment]
Thank you, appreciated :)
