### ISSUE TITLE
Players can bypass swear filter by using CAPS

### ISSUE THREAD

**Issue by DiamondKing099** [kangarko/ChatControl#60]
I'm not sure if this is an issue with my files or what. If players try to swear in lower case it blocks the words. If they try to swear in CAPS it goes undetected by CHC. I've tried adding /regex/i and ?i to the end of the match string, to no avail.

Any ideas?

**Comment by kangarko** [comment]
Hey,
can you post exactly which words are not blocked by using caps? And also the regular expression.
Thanks ;)

**Comment by DiamondKing099** [comment]
Every curse word in my filter can be bypassed by using caps. 
rules.txt: http://pastebin.com/X5TrR2cm
I have already tried adding both /regex/i and ?i, neither work.

**Comment by kangarko** [comment]
I have tested them, every is working fine. Do you have Rules.Check_Chat to true? And check if you don't have the bypass permission.

**Comment by DiamondKing099** [comment]
Yes, it is set to true. The bypass permission has nothing to do with it. Lowercase swears are blocked while the same swears in CAPS go by freely.

**Comment by kangarko** [comment]
Finally managed to fix, sorry for the delay ;)
