### ISSUE TITLE
1.8.8 Paper | Vault not showing as hooked in /chc tour hooks

### ISSUE THREAD

**Issue by draakkin** [kangarko/ChatControl#60]
![image](https://user-images.githubusercontent.com/56176412/99139293-ae8f7680-260d-11eb-90ac-52579f722e21.png)

**Comment by ElBananaa** [comment]
Looks like this is a version-related issue, I don't have this issue under paper 1.16.4

**Comment by kangarko** [comment]
Fixed. I mistakenly called if economy is hooked, not vault.
