### ISSUE TITLE
Private message and socialspy format

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#60]
We have already been speaking about this in a private conversation, but it might be better to post this on github.

I'd like to have an option to change the private message and socialspy formats like some other Chat plugins offer.

Currently:
Sikaru -> me
me -> Sikaru

What I'd like to see:
Me -> [Rank] Sikaru
[Rank] Sikaru -> me

With being able to change the colors and practically everything.

Also socialspy is hard to read currently.
I'd like to see:
[Socialspy] sender -> reciever

My previous formats within an other plugin looked like this: http://prntscr.com/a2wqiy

**Comment by kangarko** [comment]
When chat channels are implemented, such feature will be added as well.

**Comment by Sikatsu** [comment]
Shouldn't you mark it as planned instead of closing it?

**Comment by kangarko** [comment]
It has been mentioned several times elsewhere and I am well aware of it.

**Comment by Sikatsu** [comment]
Alright :P
