### ISSUE TITLE
Configurable [item] variable for chat fully customizable with permission

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#600]
If players trading in chat it would be nice, if they are able to show thier item. so it would be nice if you add an [item] variable.

How it works:
If i write [item] in chat a hover item (Item in my hand) gets send with the message. So players can hover over it and see Lore, Enchantments, Displayname, Item Type

How implement:
It would be nice, if this feature is fully configurable.
- Configurable design with variables like %type%, %enchants% %lore% %name% etc
- Configurable variable, so i can change [item] to any i want

Config example for it:
https://pastebin.com/2Xh57iT0

Example:
If i write Hello, i sell my [item] for 500$ [item] gets replaced with the Items name and players can hover over it and see this (Screenshot) https://prnt.sc/xrurg2

**Comment by ElBananaa** [comment]
> If players trading in chat it would be nice, if they are able to show thier item. so it would be nice if you add an [item] variable.
> 
> How it works:
> If i write [item] in chat a hover item (Item in my hand) gets send with the message. So players can hover over it and see Lore, Enchantments, Displayname, Item Type
> 
> How implement:
> It would be nice, if this feature is fully configurable.
> 
> * Configurable design with variables like %type%, %enchants% %lore% %name% etc
> * Configurable variable, so i can change [item] to any i want
> 
> Config example for it:
> https://pastebin.com/2Xh57iT0
> 
> Example:
> If i write Hello, i sell my [item] for 500$ [item] gets replaced with the Items name and players can hover over it and see this (Screenshot) https://prnt.sc/xrurg2

Hey!
There's already an [item] variable. Check `/plugins/ChatControlRed/variables`
