### ISSUE TITLE
1.16.5: Problem after connecting to MySQL

### ISSUE THREAD

**Issue by Kielczi** [kangarko/ChatControl#601]
Hi! Today i tried to add bungee channel to my survival server. I did everything like wiki said(bungeecord: true, connecting MYSQL). When i restart server, i have some errors and whole plugin doesn't work.
![chc](https://user-images.githubusercontent.com/38833122/106222417-cb385500-61df-11eb-860e-201006ace65e.PNG)
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5891152/debug.zip)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Hi! Today i tried to add bungee channel to my survival server. I did everything like wiki said(bungeecord: true, connecting MYSQL). When i restart server, i have some errors and whole plugin doesn't work.
> ![chc](https://user-images.githubusercontent.com/38833122/106222417-cb385500-61df-11eb-860e-201006ace65e.PNG)
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5891152/debug.zip)
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
This is a known issue with the latest version of the plugin. Revert to the previous version until Kangarko fixes the issue.

**Comment by kangarko** [comment]
Closed, explanation here: https://github.com/kangarko/ChatControl-Red/issues/596
