### ISSUE TITLE
Minecraft Version 1.16.5: Errors in console with PlayerCommandPreprocessEvent

### ISSUE THREAD

**Issue by MdoubleM** [kangarko/ChatControl#602]
ChatcontrolRed version: 10.2.0
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

I'm having some errors in console when players leave the server, join the server, and with some commands. Not always happen but randomly the console give those errors. Here is the debug and the error files

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5894141/debug.zip)
[error.log](https://github.com/kangarko/ChatControl-Red/files/5894144/error.log)

**Comment by ElBananaa** [comment]
Hey!
This is a known issue with the latest version.
Please revert to the previous version of the plugin until Kangarko release a patch for this.

**Comment by kangarko** [comment]
Closed, explanation here: Closed, explanation here: https://github.com/kangarko/ChatControl-Red/issues/596
