### ISSUE TITLE
1.16.5: Error file - malformed json

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#603]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I have this code in my error log: https://pastebin.com/1nBZQ8Yt.
DO you think it could be fixed? I have spammed error log there by this, I wanted to upload whole file on pastebin but it was so big. Just for one day.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, I have this code in my error log: https://pastebin.com/1nBZQ8Yt.
> DO you think it could be fixed? I have spammed error log there by this, I wanted to upload whole file on pastebin but it was so big. Just for one day.

Hey!
Your issue is due to an issue in one of the files: `IllegalArgumentException Could not parse ChatColor #1FFFFFFF`
As you can see above, the color you use has 8 characters, but hex colors only need 6.
Replacing `#1FFFFFFF` with `#1FFFFF` and it should fix your issue.

**Comment by kangarko** [comment]
Interesting, post me /chc debug and I have a look how can I intelligently print a warning message instead of just letting you down

**Comment by bobhenl** [comment]
Here, but I'm sorry I've deleted error file already cause it was so large and I was try to test if it was solved (asked on DiscordSRV support for help).
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5898553/debug.zip)

**Comment by ElBananaa** [comment]
> Here, but I'm sorry I've deleted error file already cause it was so large and I was try to test if it was solved (asked on DiscordSRV support for help).
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5898553/debug.zip)

Hey!
Thanks for posting your debug file.

Do you still need help with your issue, or did you finally found a way to solve it?

**Comment by bobhenl** [comment]
Seems fixed, if it will occur again, I will let you know.

**Comment by bobhenl** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5912465/debug.zip)
It's still happening :/

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5912465/debug.zip)
> It's still happening :/

Hey!
Same issue, your hex color is too long, there's 8 characters, but hex colors should only have 6 of them.
Fix your files.

**Comment by bobhenl** [comment]
And in which files should I find it?

**Comment by ElBananaa** [comment]
> And in which files should I find it?

I don't know, I didn't edit your files. You must know where you used hex colors, if you don't, then look throught each file one by one.

**Comment by bobhenl** [comment]
All I have is just this, and it's probably in this sentence, but idk what's wrong there. (messages.yml from DIscordSRV)
`DiscordToMinecraftChatMessageFormat: "[&bDiscord &r| %toprolecolor%%toprole%&r] %name% » %message%"`

Cause if you look at it, it'S where Discord is aqua, then rolecolor, player name, then » and text

```
Malformed JSON when sending message to tapped6 with JSON: {"extra":[{"text":"["},{"color":"aqua","text":"Discord "},{"extra":[{"color":"#1FFFFFFF","text":"NEOVIP"}],"text":"| "},{"text":"] Ciiba » ci"}],"text":""}
IllegalArgumentException Could not parse ChatColor #1FFFFFFF
```

**Comment by ElBananaa** [comment]
> All I have is just this, and it's probably in this sentence, but idk what's wrong there. (messages.yml from DIscordSRV)
> `DiscordToMinecraftChatMessageFormat: "[&bDiscord &r| %toprolecolor%%toprole%&r] %name% » %message%"`
> 
> Cause if you look at it, it'S where Discord is aqua, then rolecolor, player name, then » and text
> 
> ```
> Malformed JSON when sending message to tapped6 with JSON: {"extra":[{"text":"["},{"color":"aqua","text":"Discord "},{"extra":[{"color":"#1FFFFFFF","text":"NEOVIP"}],"text":"| "},{"text":"] Ciiba » ci"}],"text":""}
> IllegalArgumentException Could not parse ChatColor #1FFFFFFF
> ```

Hey, this might be due to the `%toprolecolor%` placeholder. Try removing it and see if it fixes the issue.

**Comment by kangarko** [comment]
Bob do you have the full error message? Because as far as I checked we don't even throw such an error on our side, only these two messages:

<img width="841" alt="Screenshot 2021-02-04 at 14 20 26" src="https://user-images.githubusercontent.com/1918426/106898166-2395b800-66f4-11eb-905f-4a40a07520c6.png">

**Comment by bobhenl** [comment]
as mentioned here is error log https://pastebin.com/1nBZQ8Yt

**Comment by kangarko** [comment]
Assuming this is caused by some third party plugin message, I will hide this error

**Comment by bobhenl** [comment]
it seems it's from DiscordSRV as mentioned, but support there think there isn't anything wrong about it


> All I have is just this, and it's probably in this sentence, but idk what's wrong there. (messages.yml from DIscordSRV)
> `DiscordToMinecraftChatMessageFormat: "[&bDiscord &r| %toprolecolor%%toprole%&r] %name% » %message%"`
> 
> Cause if you look at it, it'S where Discord is aqua, then rolecolor, player name, then » and text
> 
> ```
> Malformed JSON when sending message to tapped6 with JSON: {"extra":[{"text":"["},{"color":"aqua","text":"Discord "},{"extra":[{"color":"#1FFFFFFF","text":"NEOVIP"}],"text":"| "},{"text":"] Ciiba » ci"}],"text":""}
> IllegalArgumentException Could not parse ChatColor #1FFFFFFF
> ```

But as Banana suggested me I tried to remove color.

**Comment by kangarko** [comment]
Great, next version is out please try that one!
