### ISSUE TITLE
1.16.4 When I connect it to mysql it doesnt work and throws errors at me

### ISSUE THREAD

**Issue by 6008417** [kangarko/ChatControl#605]
[error (1).log](https://github.com/kangarko/ChatControl-Red/files/5896120/error.1.log)

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false
[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/5896112/debug.1.zip)

**Comment by 6008417** [comment]
https://pastebin.com/f2mA5FKj

**Comment by ElBananaa** [comment]
> [error (1).log](https://github.com/kangarko/ChatControl-Red/files/5896120/error.1.log)
> 
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: false
> [debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/5896112/debug.1.zip)

Hey!
This is a known issue, use the previous version of the plugin.
Also consider updating your java 11 since it'll be required in the future, and won't break anything, it'll only improve your server performances.
