### ISSUE TITLE
1.16.5 Is it possible to use regex group variables (e.g. $1, $2) in require script rule lines?

### ISSUE THREAD

**Issue by Plum1111** [kangarko/ChatControl#606]
1.16.5 Is it possible to use regex group variables (e.g. $1, $2) in **require script** rule lines?

Currently I'm able to get the rule to show the arguments just fine in this debug rule verifying the regex is correct:
```
match ^\/punish[ ]*([\S]*)[ ]*(.*)$
then warn &eplayer: &f$1&e|&ereason: &f$2
then deny
```

But when I use 'require script' with the regex groups it doesn't work:
```
match ^\/punish[ ]*([\S]*)[ ]*(.*)$
require script $1 == "hi"
then warn the first argument said 'hi'
then deny
```

If this isn't possible, is there a better way of checking argument values? I'm hoping there's a way of doing this otherwise I guess this is a suggestion.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Have you tried this?

require script "$1" == "hi"

It's a string so it needs to be surrounded by brackets in javascript

**Comment by Plum1111** [comment]
I tried doing that and it didn't work

**Comment by kangarko** [comment]
Fixed. I also added so you can use print() to print stuff to console to see how it works:

```
match ^\/punish[ ]*([\S]*)[ ]*(.*)$
require script print("test: '$0 $1 $2'"); '$1' == 'hi'
then warn the first argument said 'hi'
then deny
```
