### ISSUE TITLE
1.16.5: NullPointerException with some players, causes formatting to stop

### ISSUE THREAD

**Issue by sarhatabaot** [kangarko/ChatControl#607]
NullPointerException with some players, causes formatting to stop.
Also causes a very large error.log file (95MB)

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

https://pastebin.com/eMDsXS87

**Comment by ElBananaa** [comment]
> NullPointerException with some players, causes formatting to stop.
> Also causes a very large error.log file (95MB)
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> https://pastebin.com/eMDsXS87

Hey, this doesn't give us any infos.
Please upload your `/chc debug` output file. (If the file is too heavy, stop the server, and keep only 50 lines in your debug file, then upload the zip here.

**Comment by sarhatabaot** [comment]
I can confirm this only happen with new players. 
https://ufile.io/agvxb824

**Comment by ElBananaa** [comment]
Thanks.
We just released 10.2.3, please update to this version, it should fix the issue.
https://www.mc-market.org/resources/18217/
