### ISSUE TITLE
Add a setting or permission to disable/override "The nick cannot impersonate a real player name."

### ISSUE THREAD

**Issue by sarhatabaot** [kangarko/ChatControl#608]
Add a setting or permission to disable/override "The nick cannot impersonate a real player name." 
Some of my players want to customize their nickname to show only a part of their name but are prevented from doing so.

**Comment by ScottGB** [comment]
Or a toggle in config to completely disable!

**Comment by kangarko** [comment]
Can you give me an example of where it blocks the part of the name? Also check if you're on the latest version

**Comment by ScottGB** [comment]
I am on the latest version,

It blocks my admin from giving himself the nickname "Fred" due to impersonation. We got hacked a while ago where someone tried to spoof our UUIDS too, meaning I can't use "Scott" anymore, and I can't find anywhere in the database (or just in general) where it references that name.

**Comment by kangarko** [comment]
Weird, because we allow players to use partial matches. For example if there's a player "kangarko" then a player "test" can type "/tag nick kangark" to get "kangark" nickname but he cannot type "/tag nick kangarko".

**Comment by kangarko** [comment]
Never heard of spoofing UUIDs but I recommend you rollback to the version before the hack if possible or just reset the involved part of the server, can't really assist here since I don't know sorry.

**Comment by ScottGB** [comment]
We can't rollback now since it's far too late, but even if we could, a bungee network with so many plugins would not be easy to roll back. I think giving us more choice by letting us disable the impersonation thing outright would be a popular thing.

**Comment by kangarko** [comment]
Sure, I'll add Tag.Nick_Disable_Impersonation option to settings.yml
