### ISSUE TITLE
1.16.4: Huge bug unknown reason

### ISSUE THREAD

**Issue by Shimaletik2** [kangarko/ChatControl#609]
I don't know why a very strange bug happens this way.

https://pastebin.com/UqRS2b5R

Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> I don't know why a very strange bug happens this way.
> 
> https://pastebin.com/UqRS2b5R
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5898498/debug.zip)
> 
> Minecraft Version: 1.16.4
> MySQL: false
> BungeeCord: false

Hey!
This is a known bug, a patch should be released soon.
Please use the previous plugin version until then.

**Comment by ElBananaa** [comment]
Alright, Kangarko just released 10.2.1.
It should fix your issue, so please update to this version.
https://www.mc-market.org/resources/18217/
