### ISSUE TITLE
Chat Control Not Loading

### ISSUE THREAD

**Issue by NytronMC** [kangarko/ChatControl#61]
19.02 09:34:20 [Server] INFO Disabling ChatControl v5.2.7 19.02 09:34:20 [Server] INFO !----------------------------------------------! 19.02 09:34:20 [Server] INFO Error: Unable to get the error message, search above. 19.02 09:34:20 [Server] INFO !----------------------------------------------! 19.02 09:34:20 [Server] INFO Running on 1.8.8-R0.1-SNAPSHOT (v1_8_R3) and Java 1.7.0_72 19.02 09:34:20 [Server] INFO Error loading ChatControl, plugin is disabled! 19.02 09:34:20 [Server] INFO !----------------------------------------------!
[ChatControl.zip](https://github.com/kangarko/ChatControl/files/138233/ChatControl.zip)

**Comment by kangarko** [comment]
Hey,

I need to see the error above this, since this tells me nothing. Also please use pastebin for uploading stack traces.

**Comment by NytronMC** [comment]
Here's everything with "chatcontrol" in it.
http://pastebin.com/xkffxtTx

**Comment by kangarko** [comment]
Error is "Caused by: java.lang.IllegalArgumentException: Malformed config value, expected integer at: Anti_Spam.Commands.Delay_Between_Commands"

**Comment by NytronMC** [comment]
Fixed that but now have this:
http://pastebin.com/gRAwMkA9
Plugin is still disabled.

**Comment by EvilOlaf** [comment]
`20.02 08:39:12 [Server] WARN Caused by: java.lang.IllegalArgumentException: Command_Delay has to be Integer! (got 0.5)`
`int` != `float`
Use integer only.

**Comment by kangarko** [comment]
Like EvilOlaf said, use whole numbers from 0 to 100.

**Comment by NytronMC** [comment]
Missed setting the default group setting to 1.  Fixed it on one but not the other.  Thanks for the help!
