### ISSUE TITLE
1.16.5: Chat unformatted and errors in console

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#613]
Hey, randomly my chc red breaks. The chat is unformatted and i get wierd errors in console. I cant say more about it but i have all logs and debug. The next thing is, i get errors if i place down a sign,

Chat after chc is broken: https://prnt.sc/xx3li9

Error with chat: https://pastebin.com/AFsCJmjU
Error with signs: https://pastebin.com/rJ9yVE48
Debug: https://workupload.com/file/FJhKR6zKRPb

Minecraft Version: 1.16.5
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5899733/debug.zip)

MySQL: alse
BungeeCord: false

**Comment by DevJoey** [comment]
And an error on join: https://pastebin.com/XLdamj0c

**Comment by DevJoey** [comment]
I have see, there is a new version out. I have updated to see if the error still occurs

**Comment by ElBananaa** [comment]
> I have see, there is a new version out. I have updated to see if the error still occurs

Hey!
The latest version of the plugin should fix your issue.
Please let me know if it does or not.
