### ISSUE TITLE
1.16.5: Using arguments in rules (commands.rs)?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#614]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, is it possible to use arguments in commands.rs file? I wanted to make that when player gets mute then I will give him also group muted, but it seems that arguments aren't counted and anything after command is not counter as well.

My command:
```
# This rule only executes when player is in the admin channel for writing.
match ^(\/mute)
dont verbose
then command say test $1-
```

output of this command:
![image](https://user-images.githubusercontent.com/18662086/106395636-9c022d80-6403-11eb-943c-e876f3896614.png)

Could I do it somehow please?

**Comment by DevJoey** [comment]
Use correct regex 
it must be
match ^(\/mute\s(\w+))
dont verbose
then command say test $1-

**Comment by DevJoey** [comment]
You can also use this

match ^/mute\s(\w+)
dont verbose
then command say test $1-

After mute, it must be a space. So i put \s in here. The next is any word charakter between one and unlimited times, so i put \w+ in here. i put \w+ in a group, because you want to use it with $1, so your first arg will be put in group 1

**Comment by bobhenl** [comment]
We're almost there! Thanks @DevJoey , but now how to continue and make second argument?

With your example:
```
match ^/mute\s(\w+)
dont verbose
then command say test $1-
```
I can use then `Lp user $1 parent addtemp muted $2`

so when i'll use` /mute DevJoey 5h`, this command will be added to it to add muted group to player (for discord srv sync) -> `lp user DevJoeye parent addtemp muted 5h`.

How to make second argument now?

**Comment by DevJoey** [comment]
simple continue 

match ^/mute\s(\w+)\s(\w+)\s(\w+)
dont verbose
then command say test $1 $2 $3

**Comment by DevJoey** [comment]
\s = Whitespace
\w+ = Any letter in any quantity, from one to unlimited
() simbolizy a group which you can access using $1 $2 and so on

**Comment by ElBananaa** [comment]
Hey!

Thanks for helping @DevJoey!

I'm closing this issue, feel free to keep commenting down below if you need anything else related to this question, or open a new issue if that's something different. :)
