### ISSUE TITLE
Better configuration

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#615]
I would configure the message "You can only sent 4 messages in 5 seconds" but i cant configure it. secounds is not translatable and i have to colorize the whole 4 messages but i want to colorize it more. 

i would it so "&cYou can only send &7{preriod} &cMessages in &7{time} &cseconds"
But i cant colorize the numbers because they are part of the {time} and {period} can you plese make 2 extra messages for each. Iam forced to colorize the whole number and the type

Example:
Period_Message: 'Yo can only send %period% messages in %time% seconds'
Period_Commands: 'Yo can only send %period% commands in %time% seconds'

CHC Red is very uncustomizable and it would be nice if they are more possebillitys.

Here: https://prnt.sc/xxmds2
And here i have translated Seconds in german, but it is not applied to the message https://prnt.sc/xxmptl

**Comment by ElBananaa** [comment]
> I would configure the message "You can only sent 4 messages in 5 seconds" but i cant configure it. secounds is not translatable and i have to colorize the whole 4 messages but i want to colorize it more.
> 
> i would it so "&cYou can only send &7{preriod} &cMessages in &7{time} &cseconds"
> But i cant colorize the numbers because they are part of the {time} and {period} can you plese make 2 extra messages for each. Iam forced to colorize the whole number and the type
> 
> Example:
> Period_Message: 'Yo can only send %period% messages in %time% seconds'
> Period_Commands: 'Yo can only send %period% commands in %time% seconds'
> 
> CHC Red is very uncustomizable and it would be nice if they are more possebillitys.
> 
> Here: https://prnt.sc/xxmds2
> And here i have translated Seconds in german, but it is not applied to the message https://prnt.sc/xxmptl

Hey!
Afaik, CHC-Red has more customizable features than CHC-Pro.
To edit the message you're talking, in the localization file, search for the `Delay:` part.

Regarding the translation for `seconds`, please provide your `/chc debug` file.

**Comment by DevJoey** [comment]
I dont mean the Delay message, i mean the Period message

This message here: Period: You can only send {type} in {period}. i have only have the type variable, but type conains the number and the type. But i want to colorize the number with an other color than Type. But because type is a combination of number and type i cant. and on the time placeholder the same. Time contains the number and seconds but i want extra variables. One for the actual number and another for the rest. 

Like so: 

Period: &cYou can only send &7{period} &c{type} in &7{time} &c{timeform}.
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5904246/debug.zip)

**Comment by ElBananaa** [comment]
> I dont mean the Delay message, i mean the Period message
> 
> This message here: Period: You can only send {type} in {period}. i have only have the type variable, but type conains the number and the type. But i want to colorize the number with an other color than Type. But because type is a combination of number and type i cant. and on the time placeholder the same. Time contains the number and seconds but i want extra variables. One for the actual number and another for the rest.
> 
> Like so:
> 
> Period: &cYou can only send &7{period} &c{type} in &7{time} &c{timeform}.
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5904246/debug.zip)

Hey!

Alright, my bad, I musunderstood. Tbho, i'm not sure to fully understand, but anyways, please wait for Kangarko so you can get a "proper" answer.

**Comment by kangarko** [comment]
Great I will change this
