### ISSUE TITLE
Channels has stopped working and also saying players are offline when they are in-game

### ISSUE THREAD

**Issue by itsBeaco** [kangarko/ChatControl#616]
------------------------------------[ 31.01.2021 22:07:43 ]-----------------------------------
ChatControlRed 10.2.0 encountered a NullPointerException
Running Tuinity 1.16.5-R0.1-SNAPSHOT and Java 11.0.8
Plugins: LuckPerms v5.2.14, ColoredSigns v4.1.0, FirstJoinPlus v2.4.1, OpenInv v4.1.5, SAML v2.0.0, PlaceholderAPI v2.10.9, NoEndermanGrief v1.14.0.1, Sickle v1.8.3, ClearLag v3.1.6, spark v1.4.1, SilenceMobs v1.10_1.0.3, Votifier v2.7.1, InventoryRollback v1.4.0, SafeSpectate v1.0, CoordinatesHud v1.0, PortalHelper v1.13_1.0.2, LimitPillagers v2.14.0, MoreMobHeads v1.14_1.0.17.D3, DurabilityAlert v1.5.0, Vault v1.7.3-b131, ColoredAnvils v1.08, dynmap v3.1-beta6-438, WorldEdit v7.2.1+299386a, EntityTrackerFixer v1.3.3, Essentials v2.18.2.0, WorldBorder v1.9.10 (beta), WorldGuard v7.0.4+f7ff984, DeluxeChat v1.16.2, VotingPlugin v6.0.4, TAB v2.8.8, SuperVanish v6.2.0, CoreProtect v19.4, StackMob v5.3.6, Chunky v1.1.16, DiscordSRV v1.21.3, OreAnnouncer v2.7.2, ChatControlRed v10.2.0, OreAnnouncerGUI v1.3.0
----------------------------------------------------------------------------------------------

More Information: 
Unhandled exception listening to AsyncPlayerChatEvent
NullPointerException (Unknown cause)
	 at org.mineacademy.chatcontrol.model.UserMap.save(UserMap.java:181)
	 at org.mineacademy.chatcontrol.PlayerCache.from(PlayerCache.java:1064)
	 at org.mineacademy.chatcontrol.model.Channel.getOnlinePlayers(Channel.java:379)
	 at org.mineacademy.chatcontrol.model.Channel.compileReceivers(Channel.java:688)
	 at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:434)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:157)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:31)
	 at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
----------------------------------------------------------------------------------------------

**Comment by ElBananaa** [comment]
> ## ------------------------------------[ 31.01.2021 22:07:43 ]-----------------------------------
> ChatControlRed 10.2.0 encountered a NullPointerException
> Running Tuinity 1.16.5-R0.1-SNAPSHOT and Java 11.0.8
> Plugins: LuckPerms v5.2.14, ColoredSigns v4.1.0, FirstJoinPlus v2.4.1, OpenInv v4.1.5, SAML v2.0.0, PlaceholderAPI v2.10.9, NoEndermanGrief v1.14.0.1, Sickle v1.8.3, ClearLag v3.1.6, spark v1.4.1, SilenceMobs v1.10_1.0.3, Votifier v2.7.1, InventoryRollback v1.4.0, SafeSpectate v1.0, CoordinatesHud v1.0, PortalHelper v1.13_1.0.2, LimitPillagers v2.14.0, MoreMobHeads v1.14_1.0.17.D3, DurabilityAlert v1.5.0, Vault v1.7.3-b131, ColoredAnvils v1.08, dynmap v3.1-beta6-438, WorldEdit v7.2.1+299386a, EntityTrackerFixer v1.3.3, Essentials v2.18.2.0, WorldBorder v1.9.10 (beta), WorldGuard v7.0.4+f7ff984, DeluxeChat v1.16.2, VotingPlugin v6.0.4, TAB v2.8.8, SuperVanish v6.2.0, CoreProtect v19.4, StackMob v5.3.6, Chunky v1.1.16, DiscordSRV v1.21.3, OreAnnouncer v2.7.2, ChatControlRed v10.2.0, OreAnnouncerGUI v1.3.0
> ## More Information:
> Unhandled exception listening to AsyncPlayerChatEvent
> NullPointerException (Unknown cause)
> at org.mineacademy.chatcontrol.model.UserMap.save(UserMap.java:181)
> at org.mineacademy.chatcontrol.PlayerCache.from(PlayerCache.java:1064)
> at org.mineacademy.chatcontrol.model.Channel.getOnlinePlayers(Channel.java:379)
> at org.mineacademy.chatcontrol.model.Channel.compileReceivers(Channel.java:688)
> at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:434)
> at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:157)
> at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:31)
> at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
> at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)

Hey!
Please follow the bug-report format, and use '```' to paste the code.
Saying "hello" would also be great.
Finally, update to the latest version of the plugin.
