### ISSUE TITLE
Way to delay MOTD & chat after join

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#617]
Hi, could you please add way to delay MOTD? For ex. if we wanna title and subtitle after joining, then it looks a little bit ugly when there's big pop up of chat message. Or may even better would be way to delay chat messages after joining, both could be pretty nice. Chat would be even nicer that when player will join, he could read title, subtitle, then he could read motd and then the messages from players start spamming. But way to delay them would be very nice. I also delayed my board to don't mix up with title, so delaying text will be cool also.

**Comment by kangarko** [comment]
I've added delay to motd. Sorry delaying chat messages is not feasible right now.
