### ISSUE TITLE
1.16.5: [item] spam prevention

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#618]
Curious if there is a way to prevent [item] from being used to many times in a single message or certain amount of time.
e.g:
```yaml
player: [item][item][item][item]
```
(wanting to restrict this to 1 per sentence) and;
```yaml
player: [item]
player: [item]
player: [item]
player: [item]
```

(whereby first time sending the message within 30s would result in translation and the second+ time sending within 30s = the literal string `[item]` instead of the translated placeholder) - this could apply to the previous one aswell.

Is this possible to do currently, if not, can we look into adding some settings inside variables to support these.

Thanks in advance, CHC red is amazing so far!

**Comment by ElBananaa** [comment]
Hey!

As far as I know, there's no way to configure this for each variable.
However, you can enable the `Anti_Spam.Chat.Delay` feature in the settings, then edit the `Whitelist_Similarity` part like this:
```
    Whitelist_Similarity:
    - '@blacklist'
    - '^[item]'
```
So it'll turn the whitelist into a blacklist and should allow the variable to be sent only 1 time every x second.

**Comment by kangarko** [comment]
Not right now, we can take a look in the future :)
