### ISSUE TITLE
Timed messages not working at all

### ISSUE THREAD

**Issue by DiamondKing099** [kangarko/ChatControl#62]
The times messages aren't working. I have looked through the configs and added the broadcaster view permission.
Here is my settings.yml: http://pastebin.com/dm9ygc9x

**Comment by kangarko** [comment]
The broadcaster permission is not needed and is enabled by default.

Apart from your config, I don't see your issue. Can you try regenerating it?

**Comment by kangarko** [comment]
@DiamondKing099 is the issue still present?
