### ISSUE TITLE
1.16.3: how to translate?

### ISSUE THREAD

**Issue by Toki-teki** [kangarko/ChatControl#620]
how to translate variable: {receiver_or_you} ?
I need translate "you"

**Comment by Plum1111** [comment]
Go into the variables folder and then edit the corresponding variable

**Comment by Toki-teki** [comment]
thank u for help

**Comment by ElBananaa** [comment]
Hey!

Thanks Plum111 for answering Toki-teki.
I'm closing this issue, feel free to open a new one if you need anything else.
