### ISSUE TITLE
[Req] Group Anti-Spam Similarity Option

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#621]
Ability to change the similarity percentage for antispam in groups.

> 1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)

Would allow server owners to change the similarity % for any group.

> 2. What would happen if we won't implement this feature? How's your server being affected?

Nothing really it's just a really convenient feature to have.

**Comment by kangarko** [comment]
Thanks added!
