### ISSUE TITLE
1.16.5: With a combo of certain prefixes + suffixes everyone gets kicked off the server

### ISSUE THREAD

**Issue by sarhatabaot** [kangarko/ChatControl#622]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

With a combo of certain prefixes + suffixes, when that player send a message everyone gets kicked off the server.
[debug.zip](https://ufile.io/d6x80oe0)
Specifically this prefix + suffix. Tested on a different account as well. https://puu.sh/HcXRB/0ad372464f.png

Edit: Upon further testing, this doesn't happen if I remove the magic formatting i.e. &k.

**Comment by kangarko** [comment]
Please copy and paste this prefix to this chat here so I can try reproducing

**Comment by kangarko** [comment]
Also what's the kick message? Any console errors?

**Comment by kangarko** [comment]
<img width="273" alt="Screenshot 2021-02-04 at 15 04 35" src="https://user-images.githubusercontent.com/1918426/106903468-4fb43780-66fa-11eb-962b-0a0e14f4185f.png">
Tested some unicode with magic, works fine for me

**Comment by sarhatabaot** [comment]
No errors in the console.
![error](https://puu.sh/HdBhl/650d0165aa.png)
The Prefix: `#1d66ee↞#5677f1=#e37d05&k&l|#568fff♪#e37d05&k&l|&r#1d66ee&lL#5677f1&li#7789f4&lm#929cf6&le#aaaff8&ll#c1c2fa&li#d6d6fc&lg#ebeafe&lh#ffffff&lt#e37d05&k&l|&r#568fff♪#e37d05&k&l|&r#5677f1=#5677f1↠&r`
The Suffix: `&8&l{&b&lT&f&l\.&b&lI&f&l\.&8&l}&r`

It says the server went down but it hasn't gone down.

**Comment by kangarko** [comment]
Remove \ from the suffix. I fixed some mechanism breaking this.

Should work now with your exact prefix and suffix, I tested 1.16.5 over Bungee on the same server:

![a](https://i.imgur.com/Ihfc6Ys.png)

**Comment by sarhatabaot** [comment]
Great, thanks!
