### ISSUE TITLE
Discord integration improvements

### ISSUE THREAD

**Issue by ScottGB** [kangarko/ChatControl#623]
Hi, I have just set up Discord integration for my network, however, I noticed that bungee configured channels dont send all messages, only messages from the server with discordsrv. It would be nice if all messaages could be sent to discord if set to bungee: true!

Secondly, it would be nice to have a new rule parameter for Discord. Such as "discord_replace". As I have custom font icons on my server, it means they don't translate to discord properly. Example:
```
match \:pog\:
require perm emoji.pogchamp &cUnlock this emoji in a crate.
then replace 
then discord_replace :pogchamp:
```

Thanks

**Comment by kangarko** [comment]
Thank you, however right now there's a requirement to have DiscordSRV on that server. Thank you for your suggestions tho!
