### ISSUE TITLE
[Req] Timed.rs dynamic delay.

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#624]
A way to change the timed.rs delay depending on how many players are online.

> 1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)

Will allow server owners to adjust the speed of the timed message depending on how many people are online. When many people are on lots of people chat and that's why a server owner may want to adjust the speed of a timed.rs delay.

> 2. What would happen if we won't implement this feature? How's your server being affected?

Nothing really i just really would like it so announcements are seen more when lots of players are online.

This could be achieved by having a regular delay option and a `max-delay` option whereby if max-delay isn't specified it defaults to `delay`'s speed. This means the more people that are on, the closer it gets to max eventually reaching it. 

A `reverse` arg could also be used in the case a server owner wants to make the delay go from max -> default in speed when player count goes up.

**If this cannot be added, could you provide me an example of how i could adjust the timed objects delay arg via the api.**

Thanks in advance :)

**Comment by kangarko** [comment]
Thanks, but there's no feasible way to achieve this. We run the scheduler on the interval set in the config. Theoretically I could run this on 1 second and then only run logic as needed but that would grow the plugin unnecesarily complex and we'd soon have similar issues internally as with ChatControl Pro
