### ISSUE TITLE
1.16.5: Disallowed nicknames error file?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#625]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi guys, on one of my 3 servers (don't know why just here) I'm getting this error log due to my disallowed nicknames section in settings.yml. Don't know why it takes so much time, when there isn't any regex in it.
```
  Disallowed_Usernames:
  - 'Notch'
  - 'kurva'
  - 'debil'
  - 'blbec'
  - 'idiot'
  - 'dement'
  - 'kund'
  - 'štětk'
  - 'děvk'
  - 'stetk'
  - 'devk'
  - 'pizda'
  - 'pussy'
  - 'fuck'
  - 'kurv'
  - 'kurev'
  - 'horny'
  - 'nadržen'
  - 'aroused'
  - 'hentai'
  - 'porn'
  - 'slut'
  - 'slag'
  - 'boob'
  - 'vagin'
  - 'penis'
  - 'péro'
  - 'pero'
  - 'pele'
  - 'dick'
  - 'cock'
  - 'bugger'
  - 'bastard'
  - 'cunt'
  - 'nigga'
  - 'nigger'
  - 'jerk'
  - 'vyhoni'
  - 'anal'
  - 'anál'
  - 'wanker'
  - 'tosser'
  - 'shit'
  - 'hovn'
  - 'srá'
  - 'sra'
  - 'rape'
  - 'rapist'
  - 'whore'
  - 'bitch'
  - 'asshole'
  - 'twat'
  - 'titt'
  - 'piss'
  - 'sex'
  - 'gay'
  - 'lesb'
  - 'homo'
  - 'teplouš'
  - 'intercourse'
  - 'cum'
  - 'sperm'
  - 'spunk'
  - 'testicle'
  - 'milf'
  - 'retard'
  - 'anus'
  - 'dafuq'
  - 'prick'
  - 'wtf'
  - 'douche'
  - 'prostitut'
  - 'ffs'
  - 'pedo'
  - 'deb'
  - 'blb'
  - 'kkt'
  - 'zmrd'
  - 'svině'
  - 'dement'
  - 'imbecil'
  - 'chcát'
  - 'chcal'
  - 'chčít'
  - 'kokot'
  - 'kretén'
  - 'pič'
  - 'jeb'
  - 'mrd'
  - 'buz'
  - 'čurák'
  - 'čurak'
  - 'kripl'
  - 'krypl'
  - 'prdel'
  - 'čubk'
  - 'idiot'
  - 'posrán'
  - 'cigán'
  - 'cikán'
  - 'cigoš'
  - 'cikoš'
```

Here is error file: https://pastebin.com/jsgxAtq1

The weird is that this section is same on another 2 servers and there aren't any errors. Any idea what to do with it?

May I could try do this: 
```
Sometimes, all you need doing is increasing timeout
limit in your settings.yml
```
but as mentioned it's weird that it takes so long when it isn't regex :/

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi guys, on one of my 3 servers (don't know why just here) I'm getting this error log due to my disallowed nicknames section in settings.yml. Don't know why it takes so much time, when there isn't any regex in it.
> 
> ```
>   Disallowed_Usernames:
>   - 'Notch'
>   - 'kurva'
>   - 'debil'
>   - 'blbec'
>   - 'idiot'
>   - 'dement'
>   - 'kund'
>   - 'štětk'
>   - 'děvk'
>   - 'stetk'
>   - 'devk'
>   - 'pizda'
>   - 'pussy'
>   - 'fuck'
>   - 'kurv'
>   - 'kurev'
>   - 'horny'
>   - 'nadržen'
>   - 'aroused'
>   - 'hentai'
>   - 'porn'
>   - 'slut'
>   - 'slag'
>   - 'boob'
>   - 'vagin'
>   - 'penis'
>   - 'péro'
>   - 'pero'
>   - 'pele'
>   - 'dick'
>   - 'cock'
>   - 'bugger'
>   - 'bastard'
>   - 'cunt'
>   - 'nigga'
>   - 'nigger'
>   - 'jerk'
>   - 'vyhoni'
>   - 'anal'
>   - 'anál'
>   - 'wanker'
>   - 'tosser'
>   - 'shit'
>   - 'hovn'
>   - 'srá'
>   - 'sra'
>   - 'rape'
>   - 'rapist'
>   - 'whore'
>   - 'bitch'
>   - 'asshole'
>   - 'twat'
>   - 'titt'
>   - 'piss'
>   - 'sex'
>   - 'gay'
>   - 'lesb'
>   - 'homo'
>   - 'teplouš'
>   - 'intercourse'
>   - 'cum'
>   - 'sperm'
>   - 'spunk'
>   - 'testicle'
>   - 'milf'
>   - 'retard'
>   - 'anus'
>   - 'dafuq'
>   - 'prick'
>   - 'wtf'
>   - 'douche'
>   - 'prostitut'
>   - 'ffs'
>   - 'pedo'
>   - 'deb'
>   - 'blb'
>   - 'kkt'
>   - 'zmrd'
>   - 'svině'
>   - 'dement'
>   - 'imbecil'
>   - 'chcát'
>   - 'chcal'
>   - 'chčít'
>   - 'kokot'
>   - 'kretén'
>   - 'pič'
>   - 'jeb'
>   - 'mrd'
>   - 'buz'
>   - 'čurák'
>   - 'čurak'
>   - 'kripl'
>   - 'krypl'
>   - 'prdel'
>   - 'čubk'
>   - 'idiot'
>   - 'posrán'
>   - 'cigán'
>   - 'cikán'
>   - 'cigoš'
>   - 'cikoš'
> ```
> 
> Here is error file: https://pastebin.com/jsgxAtq1
> 
> The weird is that this section is same on another 2 servers and there aren't any errors. Any idea what to do with it?
> 
> May I could try do this:
> 
> ```
> Sometimes, all you need doing is increasing timeout
> limit in your settings.yml
> ```
> 
> but as mentioned it's weird that it takes so long when it isn't regex :/

Hey!
This might be due to the accents and special characters such as: `á`,`š` etc.
You could try to increase the timeout limit, or try to remove the special characters.
Let us know if anything helps.

**Comment by kangarko** [comment]
Post your debug please, if this happened once then it's not a problem, could as well be an unrelated lag, or does it always happen?

**Comment by bobhenl** [comment]
I saw it happened multiple times, regularly on the server, but I've tried as ElBanana suggested me to remove diacritics from it, so we will see. For now I will close it and if it happens again, I will reopen.

**Comment by bobhenl** [comment]
Mhm on Survival server I have got similar error, but now when the rule was matched. The problem here was as mentioned similar with time limit and due to maybe so big regex code, but I'm not sure. Do you think that using *  in regex to filter chat isn't good?
https://pastebin.com/Wx4L1fNF

Maybe players still can use another chars to workaround it like !, -, $ and so much more... SO IDK if it isn't necessary difficult to performance.

**Comment by kangarko** [comment]
<img width="819" alt="Screenshot 2021-02-04 at 15 41 26" src="https://user-images.githubusercontent.com/1918426/106908282-74f77480-66ff-11eb-981d-abfb0bdc54ae.png">
Yeah some regexes are pretty hungry, this doesn't seem like it but you can try testing it for multiple messages at regex101.com, just ensure you tick on these flags
