### ISSUE TITLE
1.16.5: [Item] lore issues

### ISSUE THREAD

**Issue by MrLarkyy** [kangarko/ChatControl#626]
Hey! I just use plugin EcoEnchants. When I use [item], it doesn't show up enchants from the plugin. I already tried to use more [item] plugins, but still the same issue. When I disable formatting from CHC RED, it works... So something is wrong in CHC RED.

I use CHC RED v10.1.21

Debug: 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5917425/debug.zip)

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Sorry this is incompatibility with your plugin.
