### ISSUE TITLE
Minecraft Version:1.16.5 Private Messaging Format for sender doesn't work

### ISSUE THREAD

**Issue by Krakenazo** [kangarko/ChatControl#627]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hello, 

I have this formatting configured:

    Message: '&6[yo -> {luckperms_prefix}{receiver}&6] &f{message}'
  
However, when you send a PM, the prefix that appears is that of the sender, not the receiver.

Best Regards.
Thanks.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hello,
> 
> I have this formatting configured:
> 
> ```
> Message: '&6[yo -> {luckperms_prefix}{receiver}&6] &f{message}'
> ```
> 
> However, when you send a PM, the prefix that appears is that of the sender, not the receiver.
> 
> Best Regards.
> Thanks.

Hey!
Please upload your `/chc debug` file.

**Comment by Krakenazo** [comment]
Hello, 

Here you are:
https://ufile.io/u0y4dev9

Thanks.

**Comment by kangarko** [comment]
I apology, right now we parse the variables on the sending server due to BungeeCord support that means they are parsed for the sender (with the exception being the player name). We may change this in the future :)
