### ISSUE TITLE
[improvements] /chc permissions

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#629]
Improvements
---
1) Ability to click to Suggest_Text permission nodes in `/chc permissions` (whereby it pops up in that chatbox).
2) Ability to search phrases in `/chc permissions <phrase>` (e.g. `/chc permissions bypass` to look for all bypass permissions) - this would also find matches in the descriptions of the permission nodes (similar to `/cmi checkperm <phrase>`)

Other
---
> 1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)

Would make the usage of `/chc permissions` significantly more useful.
> 2. What would happen if we won't implement this feature? How's your server being affected?

Nothing really, it's just annoying having to manually type the permission node and search through pages losing chat instead of being able to search with the command.

**Comment by kangarko** [comment]
Added the phrase argument!
