### ISSUE TITLE
1.16.5: Cannot use my own Ignore system

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#633]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hey, i have written my own ignore system, because i dont like the one from chc itself. now i have a problem. if i ignore a player, i still see his messages in chat. I have set my AsynChatEvent to lowest priority but it dont work. If i remove chc all works fine. So the problem is from chatcontrol. My server is completely written by me, except of chc and now this. It woulbe be nice if you can fix this, because i can no longer use chc. On previous versions all works fine. Chc pro all is good. 

Here the code i use

public void onChat(AsyncPlayerChatEvent event) {
		Player player = event.getPlayer();
		event.getRecipients().removeIf(rec -> rec != player && isIgnored(rec, player));
	}

On vanilla and with my own chat system system all works fine. With Chc all brokes. Please fix Thanks

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5928498/debug.zip)

**Comment by ElBananaa** [comment]
Hey!

I don't think I could help you with that. However, did you try to take a look at the plugin api? If I'm not wrong, ChatControl uses it's own chat component, so it might be the reason of your issue.

**Comment by DevJoey** [comment]
But CHC uses a normal ChatEvent and my ignore system simple removes the receiver if the sender is ignored by the receiver.

**Comment by DevJoey** [comment]
I think i must ChannelChatEvent instead right?

**Comment by ElBananaa** [comment]
> I think i must ChannelChatEvent instead right?

You could give it a try, it looks like you can get the message recipients and cancel the message from there.

**Comment by DevJoey** [comment]
I have this, but it dont work. The channel chat event get not even be called. 

@EventHandler
	public void onChat(ChatChannelEvent event) {
		System.out.println("Hello from channel event");
		System.out.println(event.getSender().getName());
		Player player = (Player) event.getSender();
		event.getRecipients().removeIf(rec -> rec != player && isIgnored(rec, player));
	}

The "Hello from channel event" gets not called. i think chc is not calling events. I have no possebilitys to fix this problem, because of malfunctions of chc, my servers system is completey broke due to chc.

**Comment by DevJoey** [comment]
Ok, channel chat event works perfectly

**Comment by ElBananaa** [comment]
> Ok, channel chat event works perfectly

Great!
I'm closing this ticket. Feel free to open a new one if you need anything else! :)
