### ISSUE TITLE
1.16.5: Default Rank Breaks Chat

### ISSUE THREAD

**Issue by RedZephon** [kangarko/ChatControl#634]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

When an user with the default rank on my server logs in, it breaks the chat and returns it to vanilla style.
![image](https://user-images.githubusercontent.com/16528824/106957994-9a7b8280-66ed-11eb-9d74-d152192880bd.png)
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5928637/debug.zip)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> When an user with the default rank on my server logs in, it breaks the chat and returns it to vanilla style.
> ![image](https://user-images.githubusercontent.com/16528824/106957994-9a7b8280-66ed-11eb-9d74-d152192880bd.png)
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5928637/debug.zip)

Hey!
This is a known issue which was fixed in v10.2.1. Kangarko also just released v10.2.2, so please update to the latest version and it'll fix your issue.
