### ISSUE TITLE
Game to Discord -> colors + pings

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#635]
Hi, when I had disabled Discord Integration, then there were working colors when you sent message from Discord to game. When I do it with integration, it doesn't work.  Then also when I ping someone ingame to deliver on Discord and ping there someone on Discord (so ping from game - user on Discord), it also doesn't help, without integration it works.

SO, I would ask to add color support (withh hex too) from Discord to Minecraft (may you could use discordsrv format somehow, I also wanted use feature DiscordChatChannelRoleAliases but it seems that I can't now... And then pings from game to Discord.

**Comment by kangarko** [comment]
Sorry this is not on the table right now, because I want to focus on stability and performance for the time being not discord integration, however this may get improved in the future.

**Comment by bobhenl** [comment]
Couldn't be added at least support for colors? Or couldn't we make own rule for it somehow?

**Comment by kangarko** [comment]
I don't think there's "at least" support. We either completely rewrite it, and that would bring all of the other features too. I am willing to rewrite it in the future when I have more time.
