### ISSUE TITLE
An option to have the plugins "tags" work like DeluxeTags with preset tags?

### ISSUE THREAD

**Issue by AZFire1** [kangarko/ChatControl#637]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.) I'd love if there was an option in the plugin to have tags function like DeluxeTags tags. If it had a GUI to pick tags (and have tag descriptions) that would be even better, but it could just as easily be some chat messages where you can go through pages and still have hover tooltip descriptions. I think this would be great to have in the biggest chat management plugin and would allow people to just remove one more plugin and use it all with ChatControl Red.

2. What would happen if we won't implement this feature? How's your server being affected? If you don't implement it, nothing bad would happen, people would likely continue using DeluxeTags.

Here is what deluxetags is https://www.spigotmc.org/resources/deluxetags.4390/

**Comment by sarhatabaot** [comment]
You can install DeluxeTags and use it along-side ChatControl. This is what I do. 
I created a variable using the wiki, I think it's still there somewhere. Then just set your formatting to use the variable instead of the normal prefix.
```yaml
Value: |-
    getTagOrPrefix(); // call the function below that returns the tag or prefix
    
    function getTagOrPrefix() {
        // replace with the tag
        var tag = "{deluxetags_tag}";
       
        // if the tag is empty, return prefix, else return the tag.
        return tag == "" ? "{pl_prefix}" : "&f["+tag+"&f]";
    }
```

**Comment by kangarko** [comment]
Thanks to sarhatabaot for suggesting a great solution right now!
