### ISSUE TITLE
1.12.2: Giving group `*` or `chatcontrol.*` gives user all group prefixes

### ISSUE THREAD

**Issue by VyperzDev** [kangarko/ChatControl#638]
Minecraft Version: 1.12.2
MySQL: true
BungeeCord: false

https://gyazo.com/3e5f15e9fb8c85983488e9d0937845dc

Groups should be based on specific permissions only so owners can use luckperms in-game and have all chat control perms without having to add each and every one manually.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.12.2
> MySQL: true
> BungeeCord: false
> 
> https://gyazo.com/3e5f15e9fb8c85983488e9d0937845dc
> 
> Groups should be based on specific permissions only so owners can use luckperms in-game and have all chat control perms without having to add each and every one manually.

Hey!
It makes sense that giving user `chatcontrol.*` will give them **every** permissions. As for now, I suggest you take 2 minutes of your time to give/remove the right permissions to the specified users, at least until Kangarko takes a look at your suggestion and gives you a final answer.

**Comment by kangarko** [comment]
That's an intended behaviour, some people use it like that. You need to give negative (false) permissions for the groups you want to hide.
