### ISSUE TITLE
Replace WorldGuard messages

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#64]
As WorldGuard does not provide any language files to customise phrases (they're hardcoded) I tried to use CHC to replace/translate some of these messages.

The phrase I tried to replace is `Hey! Sorry, but you can't break that block here.` The `Hey!` is in red, the rest is in grey.

I tried various stuff like
`match ...\nHey!\n....\nSorry, but you can.t (break|place) that block here.`
or
`match ^.+ Sorry, but you can.t (break|place) that block here.`
but no love here.

I guess the problem is that CHC splits the message up in four to check each for itself:

```
[21:10:44] [Server thread/INFO]: [ChatControl Debug] Checking Packet rules against: red
[21:10:44] [Server thread/INFO]: [ChatControl Debug] Checking Packet rules against: Hey!
[21:10:44] [Server thread/INFO]: [ChatControl Debug] Checking Packet rules against: gray
[21:10:44] [Server thread/INFO]: [ChatControl Debug] Checking Packet rules against:  Sorry, but you can't break that block here.
```

I don't want to create an extra rule to filter any "hey!" messages to get rid of it.

Any ideas?

CHC 5.2.7

Thanks for reading.

**Comment by kangarko** [comment]
Hey! Sorry, but you can't change that message here ;)

I appreciate you've enabled the debug. As you can see, the message is a JSON component which cannot be read in one piece, and therefore it has to be decomposed into multiple pieces and every of them is evaluated separately. I know, the system is limiting, and I was struggling with finding a solution for about a half year, and when I found it, the pro version was (unfortunately) already released. 

I see this feature is "very minor", compared to the others like bungee support, chat channels, that are in the PRO version. I can add it down to the free, too :) (in a few days)

**Comment by EvilOlaf** [comment]
Thanks for the reply.

So do I understand correctly that the pro version currently can handle messages like the one issued above?

**Comment by kangarko** [comment]
Yes. The pro version is utilising a library added in 1.7.10 which allows to decompose and compose JSON messages and makes things like you mentioned possible.

**Comment by EvilOlaf** [comment]
Ah okey. I consider making a donation for the work (to say buying the pro version) when I finally switched to v5 in production and check if everything runs smoothly.

Anyway someone else might be also interested in a backport ;)

**Comment by kangarko** [comment]
Thank you very much! I am glad you've switched from that ancient 4.x branch :+1:

**Comment by EvilOlaf** [comment]
It may be ancient now but it runs still very smooth and reliable ;)

**Comment by kangarko** [comment]
I understand perfectly. I was also running a few plugins on their older, but reliable and well tested versions for some time on my server :D

**Comment by EvilOlaf** [comment]
Works nice with the new version.
`[18:48:16 INFO]: [ChatControl Debug] Checking Packet rules against: Hey! Sorry, but you can't break that block here.`

**Comment by kangarko** [comment]
Good to know! Thanks for reporting
