### ISSUE TITLE
1.16.5 Party option plotsquared-plot does not switch me to global chat when standing on roads

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#640]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

I have global and local (party: plotsquared-plot) chat channels. I must be automatically switched to global chat when standing between plots but it does not happen (I keep being in the plot chat). What to do?

**Comment by kangarko** [comment]
We don't automatically change channels under any circumstances unless you use our API in your own way or call the /channel join command manually.

**Comment by nikitushu2** [comment]
Isn't it the default behaviour of the plotsquared-plot function? Because when you stand on the roads between plots, it is not considered as standing on the plots. So, by definition plot chat must be disabled somehow. Or am I getting something wrong?

**Comment by ElBananaa** [comment]
> Isn't it the default behaviour of the plotsquared-plot function? Because when you stand on the roads between plots, it is not considered as standing on the plots. So, by definition plot chat must be disabled somehow. Or am I getting something wrong?

Hey! As Kangarko said, the plugin doesn't automatically switch channels. The plotsquared-plot function is just an integration for plotsquared in the channels system, that's all.

**Comment by kangarko** [comment]
We're not listening for this. However ChatControl Red has an API so you can consult this with them or get a dev to make a simple extension.
