### ISSUE TITLE
Option to configure the duration of actionbar messages

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#643]
As said in the title, it would be cool to add an option to configure the duration of the actionbar announcements, like the bossbar or the title announcements. I'm pretty sure I've already seen some plugins doing it, so I guess it's possible.

**1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**
It would add an option that could be pretty useful for a lot of users since actionbar messages are really (too) fast.

2. What would happen if we won't implement this feature? How's your server being affected?
Nothing. I just feel like this would be a cool feature to add to the actual system. That could be really useful for a lot of different things related (or not) to ChatControl-Red.

**Comment by kangarko** [comment]
Thanks, but there's no native support for this (https://i.imgur.com/ITroPrS.png) and I feel like this would get too complex for a chat plugin

**Comment by ElBananaa** [comment]
> Thanks, but there's no native support for this (https://i.imgur.com/ITroPrS.png) and I feel like this would get too complex for a chat plugin

Hey, thanks for the answer!
I wasn't sure about the native support, that's why I made this suggestion. So yeah, after a few checks, it looks like the only way to actually do this is would be to loop the actionbar every 2 seconds. Seems pretty useless tbho. However, I'll keep an eye on MiniMessage (the new library that'll be used by paper when mojang release 1.17) since i'm pretty sure i've seen something about implementing this feature natively. Anyways, if this ever happens, and if you decide to use it with CHC-Red in the future, I'll consider opening a new suggestion.
