### ISSUE TITLE
1.16.5: Player issued server commands not showing up in the console due to Tell_Aliases and Reply_Aliases

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#645]
Debug.zip file -> https://ufile.io/1s1l3063

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

So in short some commands are not showing up in the console when a player runs the command. One of the commands that seem to be affected is /warp, I've tested this issue on a server with as few plugins as possible but doesn't seem to help, I've also reset all the rules I created in case it was some weird rule causing this issue but nothing seems to work. When I try to run /abc etc that shows up in the console but not /warp.

At this point, I am pretty confused as to what is causing it, so any help is welcome! :D

**Comment by TheIntolerant** [comment]
Okay so after getting super annoyed, I managed to work out the cause, it seems it has something to do with...
```
  Tell_Aliases:
  - 'tell'
  - 'w'
  - 'm'
  - 't'
  - 'pm'
  - 'message'
  - 'msg'
  - 'whisper'
  ```
  Under ``Private_Messages:``
  
  the same seems to apply to
  ```
  Reply_Aliases:
  - 'reply'
  - 'r'
  ```
As ``/region``, etc do not show up in the console when a player runs such commands.

This is why such commands like ``/warp``, ``/region``, ``/marry`` etc do not show up in the console when a user runs such commands, but once I removed the aliases, they showed up in the console as normal.

In case I am not clear enough there aren't any messages like
``(username) issued server command: /warp food`` etc, printed to the console, due to the aliases.

**Comment by kangarko** [comment]
Thanks, will get solved.
