### ISSUE TITLE
1.16.5: Rule to highlight commands

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#646]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I've created this rule but I have few problems:
```
# Limiting repeating characters to four repeats maximum.
match /(\w+)
then replace &c/$1&r
```

![image](https://user-images.githubusercontent.com/18662086/107147894-c185be80-6950-11eb-87d3-463d4db8e0e1.png)
When I write something ...... /command and then next command /command, only the first one is red.

Also, when I tried something .... /command1 ..... something .... &c/command2, color didn't work for the first one.

Any solution how to solve it?

And could I somehow enable this rule also in commands, BUT not at the beginning  (cause then commands probably won't work), I mean just for /r something .... something .... /command -> so it will be with &c, but I don't wanna to be &c/r there...

**Comment by kangarko** [comment]
Thanks, will get fixed
