### ISSUE TITLE
Improve timed.rs 

### ISSUE THREAD

**Issue by arturek1666** [kangarko/ChatControl#647]
I would love to see the timed.rs been improved and allow the messages from timed.rs to show in action bar or boss bar or title, depending on how owner want's to configure it.
**1.** This feature will allow to give owners option to have auto messages not just in chat but in action bar, boss bar, or title. Let's say it not everyone pays attention to chat xD
**2.** Nothing would have to find another way to do it.

**Comment by ElBananaa** [comment]
> I would love to see the timed.rs been improved and allow the messages from timed.rs to show in action bar or boss bar or title, depending on how owner want's to configure it.
> **1.** This feature will allow to give owners option to have auto messages not just in chat but in action bar, boss bar, or title. Let's say it not everyone pays attention to chat xD
> **2.** Nothing would have to find another way to do it.

Hey!
This is already possible: https://github.com/kangarko/ChatControl-Red/wiki/Messages#then-actionbar-message
https://github.com/kangarko/ChatControl-Red/wiki/Messages#then-bossbar-color-style-seconds-to-show-message
https://github.com/kangarko/ChatControl-Red/wiki/Messages#then-title-titlesubtitle

**Comment by arturek1666** [comment]
How exactly?, as when i try it failed bad?

**Comment by ElBananaa** [comment]
> How exactly?, as when i try it failed bad?

Please send me your `/chc debug` file

**Comment by arturek1666** [comment]
I don't want this:
![image](https://user-images.githubusercontent.com/1558228/107154830-e8ea8480-696c-11eb-9aab-d9dc24403d8a.png)
I want this:
![image](https://user-images.githubusercontent.com/1558228/107154835-f0119280-696c-11eb-9abf-e4498e110b94.png)
To display in bossbar with is not posible i try different ways.

**Comment by arturek1666** [comment]
What i wanted was make the message: (list) to show in bossbar or title etc
with the "then" dosn't do it

**Comment by arturek1666** [comment]
Thats my debug:
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5939662/debug.zip)

**Comment by ElBananaa** [comment]
> What i wanted was make the message: (list) to show in bossbar or title etc
> with the "then" dosn't do it

Alright, try with `<actionbar>` or `<title>` or `<bossbar>`at the beginning of your message.
So it'll look like:
```
message:
- <title>Test message
```
Let me know if it works.

**Comment by arturek1666** [comment]
OMG  works thanks very much :), would love to see that in wiki :)
Sorry if it felt like i was writing aggressive I was just loosing my mind ;(

**Comment by ElBananaa** [comment]
> OMG works thanks very much :), would love to see that in wiki :)

Actually, this is in the wiki: https://github.com/kangarko/ChatControl-Red/wiki/Alternative-Messages ^^

> Sorry if it felt like i was writing aggressive I was just loosing my mind ;(

No worries haha, I didn't felt like you were aggressive, but only annoyed.
Anyways, I'm closing this ticket, feel free to open a new one if you need anything else! :)

**Comment by arturek1666** [comment]
In that case sorry ;(, if i was annoying my bad :(

**Comment by ElBananaa** [comment]
> In that case sorry ;(, if i was annoying my bad :(

That's not what I meant, I meant that I felt like you were annoyed :)
Anyways, as I said, no worries, no need to apologies haha
