### ISSUE TITLE
1.16.5 | Issue with the Cases in the localization file

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#648]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hey! I recently noticed when trying the anti-caps feature, that the Cases are sent twice. So basically, let's say I send `I AM A BANANAA` ingame, it'll send me: `"Please avoid excessive capitalization in your message. messages."`
My server is under paper 1.16.5, the plugin is up-to-date, as same as its dependencies, and I'm using the default plugin configurations.

**Comment by kangarko** [comment]
Thanks!
