### ISSUE TITLE
1.16.5: (AuthMe) join message problems

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#650]
There is the issue with AuthMe join messages.

I have in settings:
```Messages:
 Apply_On:
  - 'join'
  - 'quit'
  - 'death'
```
Join message rule:
```
group default
message:
- &7[&a+&7] {player}
```
This option in AuthMe is set:
```
delayJoinMessage: true
```

**I expect:**
Message `[+] player` is written when player logins.

**I get:**
Message `[+] player` is written when player connects.

**Some notes:**
After extensive testing, there is no combination of `delayJoinMessage` and ChatControl settings that help to work around this problem.

-----------------------------------------------------------
Minecraft Version: 1.16.5
ChatControl: 10.2.2
Authme: AuthMeReloaded v5.6.0-SNAPSHOT (build: 2440)
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Thanks, added an option in our plugin for that. Using authme's option breaks it for some reason, don't use that and wait for our next version ;)

**Comment by radiant-ai** [comment]
Thanks!
