### ISSUE TITLE
Make prefix for "then log" and messages sent from other servers via BungeeControl customizable/hideable in the console

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#651]
**1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**
It would allow server owners/admin shorten messages in the console, so messages don't have to be longer than necessary.
_________________________________________________
**2. What would happen if we won't implement this feature? How's your server being affected?**
If this isn't implemented it means that a log of messages sent from other servers or when "then log" is used in rules, those messages will continue to be longer than necessary which could be reduced if the prefix for "then log" or messages sent via BungeeControl was customizable/hideable
_________________________________________________

For reference, I am talking about the prefix ``[ChatControlRed]`` that you see in the console when using ``then log`` or a message is sent via BungeeControl.

**Comment by kangarko** [comment]
Thanks however our system can't be changed in this way right now, I may return to this later.
