### ISSUE TITLE
1.16.5: Chat format disappeared for one player when using sound notify

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#652]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

![image](https://user-images.githubusercontent.com/18662086/107231445-9c608100-6a20-11eb-9e65-f1a785b7861e.png)

```
[15:14:43 INFO]: [ChatControlRed] ChatControlRed 10.2.2 encountered a ConcurrentModificationException! Please check your error.log and report this issue with the information in that file.
[15:14:43 INFO]: java.util.ConcurrentModificationException
[15:14:43 INFO]: at org.mineacademy.chatcontrol.model.Channel.compileSoundNotify(Channel.java:606)
[15:14:43 INFO]: at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:493)
[15:14:43 INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:157)
[15:14:43 INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:31)
[15:14:43 INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
[15:14:43 INFO]: [ChatControlRed] !-----------------------------------------------------!
[15:14:43 INFO]: [ChatControlRed]  Unhandled exception listening to AsyncPlayerChatEvent
[15:14:43 INFO]: [ChatControlRed] !-----------------------------------------------------!
[15:14:43 INFO]:  <aliezz321> topimat 
[15:14:45 INFO]: [ChatControlRed 10.2.2] ChatListener listening to AsyncPlayerChatEvent at HIGH priority took 223.93 ms

```

**Comment by TheIntolerant** [comment]
Can you do ``/chc debug`` and upload your debug.zip file, so contributors can help you with your issue faster :)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> ![image](https://user-images.githubusercontent.com/18662086/107231445-9c608100-6a20-11eb-9e65-f1a785b7861e.png)
> 
> ```
> [15:14:43 INFO]: [ChatControlRed] ChatControlRed 10.2.2 encountered a ConcurrentModificationException! Please check your error.log and report this issue with the information in that file.
> [15:14:43 INFO]: java.util.ConcurrentModificationException
> [15:14:43 INFO]: at org.mineacademy.chatcontrol.model.Channel.compileSoundNotify(Channel.java:606)
> [15:14:43 INFO]: at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:493)
> [15:14:43 INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:157)
> [15:14:43 INFO]: at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:31)
> [15:14:43 INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
> [15:14:43 INFO]: [ChatControlRed] !-----------------------------------------------------!
> [15:14:43 INFO]: [ChatControlRed]  Unhandled exception listening to AsyncPlayerChatEvent
> [15:14:43 INFO]: [ChatControlRed] !-----------------------------------------------------!
> [15:14:43 INFO]:  <aliezz321> topimat 
> [15:14:45 INFO]: [ChatControlRed 10.2.2] ChatListener listening to AsyncPlayerChatEvent at HIGH priority took 223.93 ms
> ```

Hey!

Please provide us your `/chc debug` file. Also make sure that you used a correct soung name/format. Sounds can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html and you can find informations about how to setup this feature correctly here: https://github.com/kangarko/ChatControl-Red/wiki/Sound-Notify

**Comment by bobhenl** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5944909/debug.zip)


It happened just once, otherwise it worked. Check my debug please

Also on second server I had this error:
```
More Information: 
Failed to execute scheduled task: java.util.ConcurrentModificationException
ConcurrentModificationException (Unknown cause)
	 at java.base/java.util.ArrayDeque.nonNullElementAt(ArrayDeque.java:270)
	 at java.base/java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:700)
	 at org.mineacademy.chatcontrol.model.Packets.lambda$removeMessage$0(Packets.java:399)
	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	 at java.base/java.lang.Thread.run(Thread.java:832)
----------------------------------------------------------------------------------------------

```

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5944909/debug.zip)
> 
> It happened just once, otherwise it worked. Check my debug please
> 
> Also on second server I had this error:
> 
> ```
> More Information: 
> Failed to execute scheduled task: java.util.ConcurrentModificationException
> ConcurrentModificationException (Unknown cause)
> 	 at java.base/java.util.ArrayDeque.nonNullElementAt(ArrayDeque.java:270)
> 	 at java.base/java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:700)
> 	 at org.mineacademy.chatcontrol.model.Packets.lambda$removeMessage$0(Packets.java:399)
> 	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
> 	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
> 	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
> 	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> 	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> 	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> 	 at java.base/java.lang.Thread.run(Thread.java:832)
> ----------------------------------------------------------------------------------------------
> ```

I don't see any error file in you debug file.

I also tried to reproduce the issue on my side, and I couldn't (I tried with paper). Keep in mind that ChatControl doesn't support forks like Purpur or Yatopia, so please try with Paper or Spigot and let me know if it fixes your issue.

**Comment by BloodshotPico** [comment]
Is there any chance in there being support for Yatopia at all? Kind of want that multi-threaded worldgen. Just curious.

**Comment by ElBananaa** [comment]
> Is there any chance in there being support for Yatopia at all? Kind of want that multi-threaded worldgen. Just curious.

Hey!
No support for Yatopia doesn't mean that the plugin won't work under it, but it means that the plugin could not work or have issues related to Yatopia that Kangarko won't solve (for now).
I'm personnally using the plugin with Purpur and everything works perfectly fine, I never had any issues related to purpur.

As for now, afaik, Kangarko doesn't plan to support Yatopia or any other server softwares than the ones listed on the wiki, because he knows he won't have time to fix potential bugs caused by these plugins. However, that doesn't mean ChatControl-Red will never support Yatopia.

**Comment by BloodshotPico** [comment]
Well to be fair Yatopia preach that if Paper breaks a plugin then so do they, meaning that they shouldn't break plugins that work on Paper. However thanks for the info.

**Comment by ElBananaa** [comment]
> Well to be fair Yatopia preach that if Paper breaks a plugin then so do they, meaning that they shouldn't break plugins that work on Paper. However thanks for the info.

Tbho, I don't know much about Yatopia. But I know that some plugins (especially plugins using reflections, but not only) must make some adaptations in order to work properly with Yatopia.

**Comment by BloodshotPico** [comment]
I'm very cautious of even trying Yatopia since I've heard thing might not work so steering clear for now at least until I update and or setup the stuff I want.

**Comment by kangarko** [comment]
Thanks, should be fixed. Regarding support for other forks, that's way more than enough for my plate right now but I can do my best if there's an easy fix, just open a new ticket if you face any issue. Any complex issues won't be fixed, however.
