### ISSUE TITLE
1.16.5: rules - original string placeholder?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#653]
Hi, how can I send original string to admin channel in rules please? Is it possible? When I deny the rule and wanna the original string be sent to admin channel? I only saw there's rewrite option, but it doesn't offer anything with channels and it isn't placeholder.

` channel send admin ORIGINAL STRING?`

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by TheIntolerant** [comment]
Can you please send the whole section for that specific rule you are talking about? Just so it's easier to answer your question. :)

For example, say I wanted to make ``#<message>`` for admin chat but was having issues, I'd send this
```
# Send messages starting with "#" to admin chat
match ^(#)(.*)
then command channel send admin $2
then deny
dont verbose
```

As we don't know the layout of the rule you are talking about, it is hard to help :)

**Comment by bobhenl** [comment]
```
match harry potter
then console cmi ctellraw {player} <T>&c&lRádce &f» &eHledáš &fHarryho Pottera&e? Najdeš ho na &c/warp magie&e! Pro tipy &fnajeď &emyší.</T><H>&eZákladní informace o magii:\n&e- &7Hůlku máš již v &einventáři\n&e- &7Kouzla přepínáš pomocí &ečísel &7nad tabem a písmeny qw atd... NEBO &eklikem v inventáři\n&e- &7Kouzelné body vidíš v &eXP baru&7 a získáváš je &ezabíjením stvoření\n&e- &7Kouzla vylepšuješ klikem na &eoltář očarování &7(enchant table)\n&e- &7Mozkomory a jiné příšery zabiješ &ekouzly\n&e- &7Další úrovně (student aj.) získáš &enaučením &7se více kouzel v oltáři očarování\n&e- &7Modifikační balíček (resourcepack) získáš pomocí &c/resourcepack&7 - manuální instalace, rychlejší načítání serveru, případně jen &c/getrp\n\n&eVíce informací na &c/warp magie&e.\n\n&cKlikni pro teleport.</H><SC>/warp magie</SC>
then console channel send admin Hráči {player} zodpovězena otázka o Harrym Potterovi.
then deny silently
```

Used for auto bot, when someone speak about harry potter question and I want to print whole string (chat message) into admin chat if quesiton would be another to let our team answer him individually

**Comment by kangarko** [comment]
I believe {original_message} should show what the player has typed.

**Comment by bobhenl** [comment]
@kangarko doesn't work:
then console channel send admin {original_message}

Anything is sent there...
And it has created infinite loop in console
![image](https://user-images.githubusercontent.com/18662086/107545221-5693ec00-6bcb-11eb-8365-3fb92a70193d.png)

**Comment by kangarko** [comment]
I will fix the duplication, next version should work fine.

**Comment by bobhenl** [comment]
@kangarko  now the problem is that it matches console too 😅

```
match harry potter
then console cmi ctellraw {player} <T>&c&lRádce &f» &eHledáš &fHarryho Pottera&e? Najdeš ho na &c/warp magie&e! Pro tipy &fnajeď &emyší.</T><H>&eZákladní informace o magii:\n&e- &7Hůlku máš již v &einventáři\n&e- &7Kouzla přepínáš pomocí &ečísel &7nad tabem a písmeny qw atd... NEBO &eklikem v inventáři\n&e- &7Kouzelné body vidíš v &eXP baru&7 a získáváš je &ezabíjením stvoření\n&e- &7Kouzla vylepšuješ klikem na &eoltář očarování &7(enchant table)\n&e- &7Mozkomory a jiné příšery zabiješ &ekouzly\n&e- &7Další úrovně (student aj.) získáš &enaučením &7se více kouzel v oltáři očarování\n&e- &7Modifikační balíček (resourcepack) získáš pomocí &c/resourcepack&7 - manuální instalace, rychlejší načítání serveru, případně jen &c/getrp\n\n&eVíce informací na &c/warp magie&e.\n\n&cKlikni pro teleport.</H><SC>/warp magie</SC>
then console channel send admin {original_message} 
then deny
```

```
[11:55:48 INFO]: *--------- Rule match (chat) for Renzotom ---------
[11:55:48 INFO]: MATCH: harry potter
[11:55:48 INFO]: CATCH: Kde je harry potter
[11:55:48 INFO]: Original message cancelled.
[11:55:48 INFO]: *--------- Rule match (chat) for CONSOLE ---------
[11:55:48 INFO]: MATCH: harry potter
[11:55:48 INFO]: CATCH: Kde je harry potter
[11:55:48 INFO]: Original message cancelled.
```

So it isn't sent to admin channel then

And `ignore channel admin` didn't help me
ignore command /channel neither

Only ignore string worked to workaround it, but I think this should be fixed as well

**Comment by kangarko** [comment]
There isn't an easy workaround for this right now, apologies. May relook into this in the future when we're rewriting our system.
