### ISSUE TITLE
1.16.5 Tags allowing spaces with ""

### ISSUE THREAD

**Issue by cades66** [kangarko/ChatControl#654]
Hi, I think this would be an amazing feature to allow users to add tags with spaces in them, specifically in a format such as " &cprefix". This prevents the prefix from mashing against other objects such as a LuckPerms prefix or a suffix, and makes it a lot cleaner.

Everyone could benefit from this as it makes tags appealable to members.
See the image below to see what I mean, of it mashing up against the text.
![image](https://user-images.githubusercontent.com/57970060/107305538-c9288e80-6a48-11eb-9670-d5f0200a8918.png)
What it should look like if we encased it with "", allowing spaces inside of the quotes.
![image](https://user-images.githubusercontent.com/57970060/107305632-f412e280-6a48-11eb-96f6-bfbc4f0d74f5.png)

**Comment by kangarko** [comment]
Can you give me an example of running the /tag command with this feature on?

**Comment by cades66** [comment]
Sure! When I try to use quotes to allow spaces, CHC includes the quotes in the tag like so: 
![image](https://user-images.githubusercontent.com/57970060/107542356-b9ff2900-6b8d-11eb-9538-9d0c91438bd8.png)

Instead of including the quotes, ignore them and have those quotes allow players to use spaces.

**Comment by kangarko** [comment]
Sure I will add this!
