### ISSUE TITLE
Internal remove (X) causes TPS drops

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#656]
Hi, I want to report that when I click on message to delete from chat when there's more than 30 players etc, then it causes a little bit TPS drops.
```
  # Show the [X] button only visible to people having permission on 'Receiver_Permission'
  # that enables you to remove chat messages by clicking on them!
  # PS: They are still saved to log and can be viewed with "/chc log".
  # TIP: Give yourself chatcontrol.bypass.spamkick to prevent being kicked when removing mass messages.
    Run_Command: /{label} internal remove {message_uuid}
```
Talking about this one, do you think that it could be improved somehow? Or any idea how I personally could improve it? For ex to clear it slower?
![image](https://user-images.githubusercontent.com/18662086/107358112-47317780-6ad3-11eb-9a37-00c3af5703bf.png)
![image](https://user-images.githubusercontent.com/18662086/107358145-50224900-6ad3-11eb-9708-bd7137b2696e.png)

Then it went back to 20

https://timings.aikar.co/?id=6dcecedba6534f87998424bce4dd5d9d#plugins
you could try find here

**Comment by kangarko** [comment]
Yeah we have to send thousands of packets to redraw the entire chat history for all online users, this can take some hits.
