### ISSUE TITLE
1.16.5 MySQL not generating in config?

### ISSUE THREAD

**Issue by BloodshotPico** [kangarko/ChatControl#658]
Minecraft Version: 1.16.5
MySQL: N/A
BungeeCord: true

So I've literally looked through the config file for a bit now and I'm using Atom, and using the serach function to find out where the MySQL piece about the plugin is within the settings.yml and I can not for the life of me find it. All I get is two obscure areas about this. This is a clean install since RED is now a thing apparently. And like discussion wasn't allowed so I can't ask other users there, which personally I find a little silly. But just needing a little help with this. :)

Lines 1245-1250

1.  -
2.  List of section names that will print informative messages about their features.
3.  If you have issues, try enabling either of these sections to self-diagnose:
4.  [mysql, points, bungee, channel, operator, rules, discord, component]
5.  -
6. Debug: []

And

Lines 1064-1068

1.  -
2.  Save game events to see what happened while you were offline.
3.  If you have MySQL enabled, these logs will go directly to your database.
4.  -
5. Log:

Settings.yml file
https://pastebin.com/wv6gsq3T

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: N/A
> BungeeCord: true
> 
> So I've literally looked through the config file for a bit now and I'm using Atom, and using the serach function to find out where the MySQL piece about the plugin is within the settings.yml and I can not for the life of me find it. All I get is two obscure areas about this. This is a clean install since RED is now a thing apparently. And like discussion wasn't allowed so I can't ask other users there, which personally I find a little silly. But just needing a little help with this. :)
> 
> Lines 1245-1250
> 
> 1. 
> 2. List of section names that will print informative messages about their features.
> 3. If you have issues, try enabling either of these sections to self-diagnose:
> 4. [mysql, points, bungee, channel, operator, rules, discord, component]
> 5. 
> 6. Debug: []
> 
> And
> 
> Lines 1064-1068
> 
> 1. 
> 2. Save game events to see what happened while you were offline.
> 3. If you have MySQL enabled, these logs will go directly to your database.
> 4. 
> 5. Log:
> 
> Settings.yml file
> https://pastebin.com/wv6gsq3T

Hey!
Thanks for reaching us!

You can find the file related to MySQL setup under the plugin root directory: `/plugins/ChatControlRed/mysql.yml`.
Regarding the discussion thing, you can open a ticket or comment under this ticket if you would like to have any information regarding the plugin, I'd be happy to answer you. :)

**Comment by BloodshotPico** [comment]
The tour is giving out false information then on the last page I believe? It says something about looking in the Settings.yml for make sure MySQL etc is hooked up properly. Or there is no where pointing towards the yml you just sent. But again thanks for the info. :)

**Comment by ElBananaa** [comment]
Thanks for reporting this issue! @kangarko

**Comment by kangarko** [comment]
Thanks, fixed.
