### ISSUE TITLE
1.16.5: Range and world chat doesnt work

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#659]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

The range option for chat channels doesn't work, I set it to a number and everyone on the server can see it. Also if I set it to range: "*" so anyone in the world can see it, it still shows it to everyone on the server and not just the world.

**Comment by kangarko** [comment]
Please ensure you don't have any bypass permissions and test on a plain account without any permissions

**Comment by DoogiePC** [comment]
Hm works now.

Wasn't aware there was a range bypass permission?

**Comment by ElBananaa** [comment]
Hey!
There is: `chatcontrol.bypass.range.world`
You can find all the permissions at this page: chatcontrol.bypass.range.world

I'm closing this issue, feel free to open a new one if you need anything else! :)
