### ISSUE TITLE
1.16.4 | Hex colors aren't shown in the item variable

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#66]
# **Environment**
### **ChatControl Version**: ChatControlRed-10.0.4

Hey! I just noticed a small thing while playing with the variables: the default color codes (&a, &b &c...) are shown when using the [item] variable, but it doesn't work with the hex colors. There's no errors, the text is just white.

**Comment by kangarko** [comment]
Sorry I cannot reproduce, what did you do exactly?

<img width="1003" alt="Screenshot 2020-11-16 at 13 57 38" src="https://user-images.githubusercontent.com/1918426/99255111-b587d600-2813-11eb-9e0d-f64161ccdc17.png">

**Comment by ElBananaa** [comment]
> Sorry I cannot reproduce, what did you do exactly?
> 
> <img alt="Screenshot 2020-11-16 at 13 57 38" width="1003" src="https://user-images.githubusercontent.com/1918426/99255111-b587d600-2813-11eb-9e0d-f64161ccdc17.png">

Hey! Sorry, I misexplained myself. I didn't change the color in the file, but I renamed the item using hex colors.

**Comment by kangarko** [comment]
Apology, this is unsupported by the nature of showing items.
