### ISSUE TITLE
Permission nodes broken

### ISSUE THREAD

**Issue by Her-Craving** [kangarko/ChatControl#66]
Any permission node relating to a command is broken and doesn't work whatsoever.

**Comment by kangarko** [comment]
They works, make sure you have your permission plugin set up correctly and check for misspelling.

**Comment by Her-Craving** [comment]
I know what I'm doing with permission nodes. These nodes DO NOT allow me to use the commands in game. I am not opped, I have permissions inheriting correctly.

the chatcontrol.commands.* node and chatcontrol.* doesn't work either. Not sure if many star nodes broke in 1.8 or what.

    - chatcontrol.bypass.*
    - chatcontrol.commands.clear
    - chatcontrol.commands.clear.anonymous
    - chatcontrol.commands.clear.console
    - chatcontrol.commands.clear.silent
    - chatcontrol.commands.fake
    - chatcontrol.commands.list
    - chatcontrol.commands.mute
    - chatcontrol.commands.mute.anonymous
    - chatcontrol.commands.mute.silent
    - chatcontrol.commands.reload

**Comment by kangarko** [comment]
What permission plugin are you using? They work for me on PEX.

**Comment by Her-Craving** [comment]
Groupmanager. I'm on spigot for 1.8
