### ISSUE TITLE
Bi-directional ignore

### ISSUE THREAD

**Issue by Wertik** [kangarko/ChatControl#661]
Suggestion: Add an option to make ignore bi-directional -- ignored player wouldn't see messages sent by the player who ignores him.

1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
We're seeking this feature mostly because of some conflicts between players, hence I believe we're not the only server that would use this.

2. What would happen if we won't implement this feature? How's your server being affected?
We'd probably have to develop something of our own instead, which would meddle around the already well-populated chat listeners -- we want to avoid this as much as we can.

**Comment by LogGits** [comment]
Honestly thought it already worked like this. Great idea and I'd also like to see this feature added 👍

**Comment by bublif** [comment]
Great idea! Add it please! <3

**Comment by ElBananaa** [comment]
Hey!

I was just looking at the files, and noticed this option in the settings: `Hide_Chat:`.
It should be what you guys are looking for. So please try to enable this feature, and let me know if it actually works.

**Comment by kangarko** [comment]
Willbeadded
