### ISSUE TITLE
1.16.5: Colour codes/Swear Filter

### ISSUE THREAD

**Issue by elkoyofficial** [kangarko/ChatControl#662]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Colour codes in chat and swear filter is not working.
My Debug zip file; https://ufile.io/1f5jc67u

**Comment by ElBananaa** [comment]
Hey!

Increasing the `Regex_Timeout_Ms:` to `100` or `150` (if it still doesn't work with 100) in the plugin settings.yml should fix your issue.
I'm closing this, but feel free to keep commenting down below if the issue persists, or open a new issue if you need anything else that's not related to this issue! :)
