### ISSUE TITLE
1.16.5: The server equals sender – connecting problem

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#663]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I discovered the problem with Reconnect plugin (https://www.spigotmc.org/threads/bungee-automatic-reconnect-bungee-reconnect.465646/) that sometimes can't connect players on specific servers cause the servers "are restarting" by it. I've asked dev of this plugin about it and got this response:

> looks to be BungeeControl-Red.
>
> "Did not send to 'Survival', the server equals sender"
> Perhaps that plugin gets confused when Reconnect connects the player to the same server and then kicks them back to hub.
>
> Seems to be what's up.
> I'll see what I can do about it but because it depends on ChatControlPro (and that is a paid plugin) I can't make any promises.

But, if it's problem that player can't be send due to the server is equals to sender, it is probably turn to fix from you kangarko.
As I mentioned it happens only sometimes and I don't know when exactly, but here's my log when it happened, so you can check (debug is enabled there).

This is from yesterday
[2021-02-09-2.log.gz](https://github.com/kangarko/ChatControl-Red/files/5962300/2021-02-09-2.log.gz)

This is from today
[2021-02-10-2.log.gz](https://github.com/kangarko/ChatControl-Red/files/5962298/2021-02-10-2.log.gz)

Cause it happens everyday and I'm loosing players due to it, I have to disable Bungeecord integration until you fix this issue, if it's really issue by your side.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, I discovered the problem with Reconnect plugin (https://www.spigotmc.org/threads/bungee-automatic-reconnect-bungee-reconnect.465646/) that sometimes can't connect players on specific servers cause the servers "are restarting" by it. I've asked dev of this plugin about it and got this response:
> 
> > looks to be BungeeControl-Red.
> > "Did not send to 'Survival', the server equals sender"
> > Perhaps that plugin gets confused when Reconnect connects the player to the same server and then kicks them back to hub.
> > Seems to be what's up.
> > I'll see what I can do about it but because it depends on ChatControlPro (and that is a paid plugin) I can't make any promises.
> 
> But, if it's problem that player can't be send due to the server is equals to sender, it is probably turn to fix from you kangarko.
> As I mentioned it happens only sometimes and I don't know when exactly, but here's my log when it happened, so you can check (debug is enabled there).
> 
> This is from yesterday
> [2021-02-09-2.log.gz](https://github.com/kangarko/ChatControl-Red/files/5962300/2021-02-09-2.log.gz)
> 
> This is from today
> [2021-02-10-2.log.gz](https://github.com/kangarko/ChatControl-Red/files/5962298/2021-02-10-2.log.gz)
> 
> Cause it happens everyday and I'm loosing players due to it, I have to disable Bungeecord integration until you fix this issue, if it's really issue by your side.

Hey!
Thanks for reporting this issue, and apologies about it.

I think it would be better to see with the developer of the plugin if he could come on github or send an email to Kangarko at the address: matej@mineacademy.org about this problem in order to facilitate communication between them.

**Comment by kangarko** [comment]
I am pretty sure this is unrelated to BungeeControl Red, we don't even handle reconnecting players
