### ISSUE TITLE
1.16.5: name showing {player_nick} instead of discord username

### ISSUE THREAD

**Issue by ImSapphire** [kangarko/ChatControl#665]
Minecraft Version: 1.16.5
MySQL: false (i think)
BungeeCord: false
![javaw_G9dcpieyFe](https://user-images.githubusercontent.com/48931512/107595328-f5274980-6bd9-11eb-8c23-591078ceab3d.png)
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5962767/debug.zip)
I'm having an issue where players who talk in any Discord channels linked to Minecraft show the username as {player_nick} instead of their Discord username and I can't find where to change the message.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false (i think)
> BungeeCord: false
> ![javaw_G9dcpieyFe](https://user-images.githubusercontent.com/48931512/107595328-f5274980-6bd9-11eb-8c23-591078ceab3d.png)
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5962767/debug.zip)
> I'm having an issue where players who talk in any Discord channels linked to Minecraft show the username as {player_nick} instead of their Discord username and I can't find where to change the message.

Hey!
I don't thing anyone reported this issue before. Anyways, please make sure all your plugins and dependencies (like protocolLib) are up-to-date. Also please try with the latest version of DiscordSRV available **on spigot**, and not the devbuild. Does it changes anything?

Also, you can change the actual format in `ChatControlRed/formats/chat.yml`. You could try to replace `{player_nick}` with `{player}` and see if this works.

**Comment by ImSapphire** [comment]
> > Minecraft Version: 1.16.5
> > MySQL: false (i think)
> > BungeeCord: false
> > ![javaw_G9dcpieyFe](https://user-images.githubusercontent.com/48931512/107595328-f5274980-6bd9-11eb-8c23-591078ceab3d.png)
> > [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5962767/debug.zip)
> > I'm having an issue where players who talk in any Discord channels linked to Minecraft show the username as {player_nick} instead of their Discord username and I can't find where to change the message.
> 
> Hey!
> I don't thing anyone reported this issue before. Anyways, please make sure all your plugins and dependencies (like protocolLib) are up-to-date. Also please try with the latest version of DiscordSRV available **on spigot**, and not the devbuild. Does it changes anything?
> 
> Also, you can change the actual format in `ChatControlRed/formats/chat.yml`. You could try to replace `{player_nick}` with `{player}` and see if this works.

I can't see an option to change what the player username is, I only see the prefix and sender condition.
![image](https://user-images.githubusercontent.com/48931512/107596903-d4152780-6bde-11eb-95d8-cf0fc9a60236.png)

**Comment by ImSapphire** [comment]
I also updated all of my plugins and PaperMC to the latest version 1-3 days ago.

**Comment by ElBananaa** [comment]
> > > Minecraft Version: 1.16.5
> > > MySQL: false (i think)
> > > BungeeCord: false
> > > ![javaw_G9dcpieyFe](https://user-images.githubusercontent.com/48931512/107595328-f5274980-6bd9-11eb-8c23-591078ceab3d.png)
> > > [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5962767/debug.zip)
> > > I'm having an issue where players who talk in any Discord channels linked to Minecraft show the username as {player_nick} instead of their Discord username and I can't find where to change the message.
> > 
> > 
> > Hey!
> > I don't thing anyone reported this issue before. Anyways, please make sure all your plugins and dependencies (like protocolLib) are up-to-date. Also please try with the latest version of DiscordSRV available **on spigot**, and not the devbuild. Does it changes anything?
> > Also, you can change the actual format in `ChatControlRed/formats/chat.yml`. You could try to replace `{player_nick}` with `{player}` and see if this works.
> 
> I can't see an option to change what the player username is, I only see the prefix and sender condition.
> ![image](https://user-images.githubusercontent.com/48931512/107596903-d4152780-6bde-11eb-95d8-cf0fc9a60236.png)

This is the right file, but not the right part:
```
  player-name:
    Message: '{player_nick}&f{+player_suffix}'
    Hover:
    - '&7Click to message this player.'
    Suggest_Command: '/tell {player_name} '
```

**Comment by ImSapphire** [comment]
Changing {player_nick} to {player} still shows the placeholder instead of the username. As far as I know this worked before I upgraded all of the plugins on my server.

**Comment by ElBananaa** [comment]
> Changing {player_nick} to {player} still shows the placeholder instead of the username. As far as I know this worked before I upgraded all of the plugins on my server.

Hey!
Sorry for the delays.

As yous aid, you updated your plugins 3 days ago, the problem is that I can still see that a lot of your plugins are outdated.
I also recommend updating to Java 11 (This won't break any of your plugins).

Finally, please provide an update version of your `/chc debug` file.

**Comment by kangarko** [comment]
You can't use player-related variables when showing a message from Discord. You can use the Discord_Format option for your channel and use a completely separate formatting where you only use the "{player_name}" (or just "{player}")
