### ISSUE TITLE
1.16.5: Channel Autojoin

### ISSUE THREAD

**Issue by CoutovyLp** [kangarko/ChatControl#666]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hello. I have problem with autojoin.
I set permission "chatcontrol.channel.autojoin.standard.write" and it´s not autojoin them in standard. They must to write it by themself
Where is problem?

**Comment by Yamamot00** [comment]
You need to have "chatcontrol.channel.join.standard.write" too.
It seems chatcontrol use the "join" to be able to join if you want and "autojoin" to join in the channel automatically with that it becomes easily to create a only Vip channel automatically and be able to leave the channel if the player desires.

I also use "autojoin.global.read" and "join.global.read" for my users be able to only see the messages but to write in the Global channel i use the "channel.send.global" and "channel.send" for the user to be able to only send messages in global with the specific command

**Comment by CoutovyLp** [comment]
Ooooh.. Ok, thanks

**Comment by ElBananaa** [comment]
Hey!
Thanks to @Yamamot00 for answering your question.
I'm closing this issue, feel free to open a new one if you need anything else! :)
