### ISSUE TITLE
1.16.5: Timed.rs prefix not shown if message is json

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#667]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

If i use a json message in timed.rs, the prefix it not shown. This is only if the message is '[JSON]'

Debug: 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5966410/debug.zip)

**Comment by kangarko** [comment]
Yeah we're using it as-is if we detect JSON. You'd have to manually input your prefix that way
