### ISSUE TITLE
SUGGESTION: Implementing mcmmo alliance feature into partychat

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl#668]
Hello , with mcmmo partys can be allies with eachother and then type in eachothers partychat, would yo perhaps implement this feature in the channel option aswell? This would make it really useful. Thanks!

**Comment by ElBananaa** [comment]
> Hello , with mcmmo partys can be allies with eachother and then type in eachothers partychat, would yo perhaps implement this feature in the channel option aswell? This would make it really useful. Thanks!

Hey! Thanks for your suggestion.
Please update your post using the suggestion format.

**Comment by kangarko** [comment]
Thank you for your suggestion, however I decided not to implement this right now due to other priorities.
