### ISSUE TITLE
1.16.5: Colour codes and swear filter not working

### ISSUE THREAD

**Issue by elkoyofficial** [kangarko/ChatControl#669]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Re-opening this issue. I changed that ms thing to 100 and tried 150, they both do not work. This shows up in console when someone swears;
[01:30:27 INFO]: [ChatControlRed] !-----------------------------------------------------!
[01:30:27 INFO]: [ChatControlRed]  A regular expression took too long to process, and was
[01:30:27 INFO]: [ChatControlRed]  stopped to prevent freezing your server.
[01:30:27 INFO]:   
[01:30:27 INFO]: [ChatControlRed]  Limit 150ms
[01:30:27 INFO]: [ChatControlRed]  Expression: '\b(s+(\W|\d|_)*l+(\W|\d|_)*u+(\W|\d|_)*t+(\W|\d|_)*)'
[01:30:27 INFO]: [ChatControlRed]  Evaluated message: 'yeah you tell me to chill you little slut'
[01:30:27 INFO]:   
[01:30:27 INFO]: [ChatControlRed]  IF YOU CREATED THAT RULE YOURSELF, we unfortunately
[01:30:27 INFO]: [ChatControlRed]  can't provide support for custom expressions.
[01:30:27 INFO]:   
[01:30:27 INFO]: [ChatControlRed]  Sometimes, all you need doing is increasing timeout
[01:30:27 INFO]: [ChatControlRed]  limit in your settings.yml
[01:30:27 INFO]:   
[01:30:27 INFO]: [ChatControlRed]  Use services like regex101.com to test and fix it.
[01:30:27 INFO]: [ChatControlRed]  Put the expression without '' and the message there.
[01:30:27 INFO]: [ChatControlRed]  Ensure to turn flags 'insensitive' and 'unicode' on
[01:30:27 INFO]: [ChatControlRed]  on there when testing: https://i.imgur.com/PRR5Rfn.png
[01:30:27 INFO]: [ChatControlRed] !-----------------------------------------------------!

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Re-opening this issue. I changed that ms thing to 100 and tried 150, they both do not work. This shows up in console when someone swears;
> [01:30:27 INFO]: [ChatControlRed] !-----------------------------------------------------!
> [01:30:27 INFO]: [ChatControlRed] A regular expression took too long to process, and was
> [01:30:27 INFO]: [ChatControlRed] stopped to prevent freezing your server.
> [01:30:27 INFO]:
> [01:30:27 INFO]: [ChatControlRed] Limit 150ms
> [01:30:27 INFO]: [ChatControlRed] Expression: '\b(s+(\W|\d|_)*l+(\W|\d|_)_u+(\W|\d|_)*t+(\W|\d|_)_)'
> [01:30:27 INFO]: [ChatControlRed] Evaluated message: 'yeah you tell me to chill you little slut'
> [01:30:27 INFO]:
> [01:30:27 INFO]: [ChatControlRed] IF YOU CREATED THAT RULE YOURSELF, we unfortunately
> [01:30:27 INFO]: [ChatControlRed] can't provide support for custom expressions.
> [01:30:27 INFO]:
> [01:30:27 INFO]: [ChatControlRed] Sometimes, all you need doing is increasing timeout
> [01:30:27 INFO]: [ChatControlRed] limit in your settings.yml
> [01:30:27 INFO]:
> [01:30:27 INFO]: [ChatControlRed] Use services like regex101.com to test and fix it.
> [01:30:27 INFO]: [ChatControlRed] Put the expression without '' and the message there.
> [01:30:27 INFO]: [ChatControlRed] Ensure to turn flags 'insensitive' and 'unicode' on
> [01:30:27 INFO]: [ChatControlRed] on there when testing: https://i.imgur.com/PRR5Rfn.png
> [01:30:27 INFO]: [ChatControlRed] !-----------------------------------------------------!

Hey! The issue is the same, than your first message. As said in the "error" message the expression took too long to process so the plugin stopped the process so it won't freeze your server. Unfortunately we can't do much about it. You can, if you wish, keep increasing the limit until it works, but it also means that an expression could freeze your server. An alternative would be to optimize and upgrade your server/vps/dedicated server.

**Comment by elkoyofficial** [comment]
I've increased the limit to 400 and that has fixed the filter. I am still having trouble with colour codes in chat. The chc color command works fine with colours, but if you try with &etest in-game, it will not work.

**Comment by elkoyofficial** [comment]
Forgot to include server specs:
AMD Ryzen 7 3800X - 8 c / 16 t - 3.9 GHz / 4.5 GHz - 32G RAM

**Comment by ElBananaa** [comment]
> Forgot to include server specs:
> AMD Ryzen 7 3800X - 8 c / 16 t - 3.9 GHz / 4.5 GHz - 32G RAM

I don't know what are the conditions fwhen you are testing this, but if there's only a few players online this shouldn't happen then.

**Comment by elkoyofficial** [comment]
Okay so I've downloaded a new version on another server and the colour codes work. I then moved my current folder over to the other server and it broke the colours. Maybe a new .jar update broke something and I need to redo the entire thing again?

**Comment by ElBananaa** [comment]
> Okay so I've downloaded a new version on another server and the colour codes work. I then moved my current folder over to the other server and it broke the colours. Maybe a new .jar update broke something and I need to redo the entire thing again?

Hey! This might actually be caused by another plugin. Could you please provide us your `/chc debug` file from the server with the issue. Also make sure your plugins, server software(s) and dependencies are all up-to-date.

**Comment by elkoyofficial** [comment]
[debug(2).zip](https://github.com/kangarko/ChatControl-Red/files/5978252/debug.2.zip)

**Comment by ElBananaa** [comment]
> [debug(2).zip](https://github.com/kangarko/ChatControl-Red/files/5978252/debug.2.zip)

Thanks.

It's pretty weird, I don't know what can cause this issue. I only see two options: either, it's due to a pretty high amount of players (but I guess this shouldn't happen) or by another plugin. Unfortunately, you'll have to wait for kangarko.

**Comment by elkoyofficial** [comment]
Yeah, it's definitely weird. We have 30+ on all day long with peaks of up to 70.

**Comment by kangarko** [comment]
Thanks for reporting, just keep it at the higher value for now, please email me your ChatControl Red ZIP over to matej@mineacademy.org and I'll test this
