### ISSUE TITLE
1.16.4 MySQL | Center tag doesn't exactly center the text.

### ISSUE THREAD

**Issue by viasnake** [kangarko/ChatControl#67]
Maybe the string using `<center>` is not exactly centered.
A clear way to check this is announcement command.

![image](https://user-images.githubusercontent.com/6961187/99160210-fc000680-2727-11eb-8f6f-b7b407fb7949.png)

Environment
--------------
Java: Java 14
Server software: git-paper-267
Version: ChatControl-Red-10.0.4

**Comment by kangarko** [comment]
Unfortunately this is the case of the free library extension we are using, anyone is encouraged to make a pull request to fix that: https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/ChatUtil.java

I tried before but it breaks other centerings such as on /chc ? pagination etc.
