### ISSUE TITLE
Need little improvements in anti-ad

### ISSUE THREAD

**Issue by Sprunkas** [kangarko/ChatControl#67]
Hello,

when someone is advertising like this:
m c . server . c o m
it bypasses and can send this message to server.

**Comment by kangarko** [comment]
This is like the filters are, the more stronger you make it the more false catches will be raised. They have been optimized to catch most of the domains while keeping the false positives rate low.

I can give you an example of stronger domain filter but it may cause unwanted catches:

`match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?((c+(\W|\d|_)*o+(\W|\d|_)*m+(\W|\d|_)*)|(o+(\W|\d|_)*r+(\W|\d|_)*g+(\W|\d|_)*)|(n+(\W|\d|_)*e+(\W|\d|_)*t+(\W|\d|_)*)|cz|co|uk|sk|biz|mobi|xxx|eu|me|io)\b`

Place this as a replacement for the match operator in rules/rules.txt in the domain/url filter.
