### ISSUE TITLE
1.16.5: Announcer

### ISSUE THREAD

**Issue by CoutovyLp** [kangarko/ChatControl#670]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hello. I have question. At old ChatControl was in /chc announce the {dynamicLine}. I tried that in this new version. (RED)
Is possible to get text in the second line?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Hello. I have question. At old ChatControl was in /chc announce the {dynamicLine}. I tried that in this new version. (RED)
> Is possible to get text in the second line?

Hey!
The announce format can be changed under the `Chat_Body:` part in your localization file.
The `{dynamicLine}` variable was replaced with `{lines}`.
