### ISSUE TITLE
1.16.5: Exclude some accents strips in Russian

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#671]
When `Strip_Accents: true`:

Some letters in Russian are not considered as accents and should not be stripped. Stripping them makes some messages look weird for the users. In ChatControl Pro they were handled properly.

`й` - `и`
`ё` - `е`

Please add them to exclusions, thanks.

P.S. There are no accents in Russian at all, but for the simplicity sake just exclude 2 symbols ;)

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey!

Unfortunately, these characters are actually considered as accents in some languages. However, adding a file to customize which characters are considered as accents would be a cool idea to avoid such issues, and give users more flexibility.

**Comment by radiant-ai** [comment]
I think this issue is not really relevant to Russian, because it does not have accents as I said. So disabling accent stripping in setting does not affect chat filtering. So I will close this issue.
