### ISSUE TITLE
1.16.5: ChatControl breaks /pvp command

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#672]
When ChatControl Red is installed `/pvp` command of PvPManager plugin stops working and does not even appear to exist.

Tested using default CCR config.

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> When ChatControl Red is installed `/pvp` command of PvPManager plugin stops working and does not even appear to exist.
> 
> Tested using default CCR config.
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false

Hi,

Please provide us your `/chc debug`. Also make sure your plugins, your server software and your dependencies are all up-to-date.
Also, please give us more context. Does it return a message? Do you get any errors in your console/logs?

**Comment by radiant-ai** [comment]
> > When ChatControl Red is installed `/pvp` command of PvPManager plugin stops working and does not even appear to exist.
> > Tested using default CCR config.
> > Minecraft Version: 1.16.5
> > MySQL: false
> > BungeeCord: false
> 
> Hi,
> 
> Please provide us your `/chc debug`. Also make sure your plugins, your server software and your dependencies are all up-to-date.
> Also, please give us more context. Does it return a message? Do you get any errors in your console/logs?

As I noted before I ran 100% default config (I just deleted my CCR folder). But I've just retested everything and here is the debug: https://ufile.io/7lt23wm1
I don't have any errors in console, server just says that `/pvp` command does not exist.

**Comment by kangarko** [comment]
Thanks, /pvp command had /toggle in its aliases so I added an exception so that we won't deregister this
