### ISSUE TITLE
Json messages

### ISSUE THREAD

**Issue by Danielpeter-99** [kangarko/ChatControl#674]
It would be nice to have json support for localized files.

For example, I wanted to have the no one can hear you for ranged channels message clickable, it would generate the command to talk in the global chat automatically.

**Comment by ElBananaa** [comment]
Hey! You can use json in your localization : https://github.com/kangarko/ChatControl-Red/wiki/JSON

**Comment by Danielpeter-99** [comment]
I have tried but keep getting issues. My fault most likely, cant format well enough.
`  Channel_Range_Notification: '[JSON] ["",{"text":"{prefix_warn}","clickEvent":{"action":"suggest_command","value":"/g Oi pessoal!"}},{"text":"Ninguém te escuta! Para falar com todos, digite:","color":"gold","clickEvent":{"action":"suggest_command","value":"/g Oi pessoal!"}},{"text":"\n","clickEvent":{"action":"suggest_command","value":"/g Oi pessoal!"}},{"text":"/g <mensagem> ou clique nessa mensagem!","color":"yellow","clickEvent":{"action":"suggest_command","value":"/g Oi pessoal!"}}]'
`
Error:
`More Information: 
ChatControlRed does not support the localization: messages_pt.yml (For custom locale, set the Locale to 'en' and edit your English file instead)
FoException Report: ChatControlRed does not support the localization: messages_pt.yml (For custom locale, set the Locale to 'en' and edit your English file instead)
	 at org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60)
	 at org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadLocalization(YamlConfig.java:212)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.createLocalizationFile(YamlStaticConfig.java:250)
	 at org.mineacademy.chatcontrol.lib.settings.SimpleLocalization.load(SimpleLocalization.java:81)
	 at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:92)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.reload(SimplePlugin.java:771)
	 at org.mineacademy.chatcontrol.lib.command.ReloadCommand.onCommand(ReloadCommand.java:53)
	 at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:375)
	 at org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
	 at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:375)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)`

**Comment by ElBananaa** [comment]
> I have tried but keep getting issues. My fault most likely, cant format well enough.
> ` Channel_Range_Notification: '[JSON] ["",{"text":"{prefix_warn}","clickEvent":{"action":"suggest_command","value":"/g Oi pessoal!"}},{"text":"Ninguém te escuta! Para falar com todos, digite:","color":"gold","clickEvent":{"action":"suggest_command","value":"/g Oi pessoal!"}},{"text":"\n","clickEvent":{"action":"suggest_command","value":"/g Oi pessoal!"}},{"text":"/g <mensagem> ou clique nessa mensagem!","color":"yellow","clickEvent":{"action":"suggest_command","value":"/g Oi pessoal!"}}]'`
> Error:
> `More Information: ChatControlRed does not support the localization: messages_pt.yml (For custom locale, set the Locale to 'en' and edit your English file instead) FoException Report: ChatControlRed does not support the localization: messages_pt.yml (For custom locale, set the Locale to 'en' and edit your English file instead) at org.mineacademy.chatcontrol.lib.Valid.checkNotNull(Valid.java:60) at org.mineacademy.chatcontrol.lib.settings.YamlConfig.loadLocalization(YamlConfig.java:212) at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.createLocalizationFile(YamlStaticConfig.java:250) at org.mineacademy.chatcontrol.lib.settings.SimpleLocalization.load(SimpleLocalization.java:81) at org.mineacademy.chatcontrol.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:92) at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.reload(SimplePlugin.java:771) at org.mineacademy.chatcontrol.lib.command.ReloadCommand.onCommand(ReloadCommand.java:53) at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:375) at org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374) at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:375) at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)`

Hey!

You need to edit the file `messages_en.yml` and use the english lang in the file.

**Comment by Danielpeter-99** [comment]
I do that actually, I sent the wrong error Im sorry.

`------------------------------------[ 13.02.2021 14:26:47 ]-----------------------------------
ChatControlRed 10.2.3 encountered a NullPointerException
Running Tuinity 1.16.5-R0.1-SNAPSHOT and Java 1.8.0_275
Plugins: AntiCooldown v3.4, PlaceholderAPI v2.10.10-DEV-111, PlugMan v2.1.7, Admin360-Reloaded v8.0.0, OldCombatMechanics v1.9.0, DeluxeTags v1.8.1, TopTags v1.0.1, GSit v[2.14.1.0], NBTAPI v2.7.1, NoSpawnVillagers v1.0, SupremeTPA v3.0, CheaperPhysicsEvent v1.0-SNAPSHOT (build 2), VillagerOptimiser v1.1.5, PacketListenerApi v3.7.8-SNAPSHOT, BetterSpawners v1.2.7, GlowAPI v1.4.14-SNAPSHOT, BuycraftX v12.0.6, MapManager v1.7.10-SNAPSHOT, Votifier v2.7.2, AdvancedPortals v0.5.10, Vouchers v1.8.17-RELEASE, VoidGenerator v1.7.0, LimitPillagers v2.14.0, LangUtils v2.4.x, AdvancedAFK v1.3.2, AnimatedFrames v4.12.1-SNAPSHOT, ViaVersion v3.2.1, ViaBackwards v3.2.1-SNAPSHOT, LuckPerms v5.2.76, AnimatedScoreboard v0.2.3, ProtocolLib v4.6.0-SNAPSHOT-b483, LibsDisguises v10.0.24, ChatBrawl v1.7.3, Vault v1.7.3-b131, TokenManager v3.2.5, HolographicDisplays v2.4.6, SkinsRestorer v13.8.8, WitherAC v0.23.1, MyCommand v5.6.9, LagAssist v2.23.3, WorldEdit v7.2.2+fc3c499, PinataParty v2.16.3, HeadDatabase v4.13.4, Multiverse-Core v4.2.2-b812, TrMenu v2.08, SimpleClans v2.14.6, Citizens v2.0.27-SNAPSHOT (build 2186), PlayerAuctions v1.2.3, DeluxeMenus v1.13.3-Release, Lottery v1.4.3, CrazyCrates v1.10.1-SNAPSHOT-Build#95, VoidTeleport v2.3.6, HolographicExtension v1.10.9, LeaderHeadsRevamped v4.0.6, WorldGuard v7.0.4+f7ff984, Insights v5.9.3, MythicMobs v4.11.0-BETA-79e173ec, CoreProtect v19.4, SilkSpawners v7.0.0, EconomyShopGUI v3.0.2, mcMMO v2.1.132, FarmLimiter v1.5.1, Quests v3.9.5-b130, MarriageMaster v2.2.13-Release, IllegalStack v2.2.1a, ChestShop v3.11 (build 213), Shopkeepers v2.12.0, GriefPrevention v16.17.1-2b69191, TradePlus v3.77, GriefPreventionFlags v5.10.0, Wild v2.22-e6c1382, GPAccruals v1.1, PlayerWarps v6.4.0, Essentials v2.19.0-dev+70-34fdcf8, Elevator v3.11.0, DragonSlayer v0.10.3.1_Jeppa, AdvancedAchievements v6.2.0, TAB v2.8.10, SuperVanish v6.2.0, CombatLogX v10.3.7.1, EssentialsSpawn v2.19.0-dev+70-34fdcf8, WorldGuardExtraFlags v4.1.5-SNAPSHOT, MyPet v3.11, FlightControl v4.7.20-BETA, Jobs v4.17.0, DiscordSRV v1.21.1, AuthMe v5.6.0-SNAPSHOT-b2425, Duels v3.4.1, LiteBans v2.6, ChatControlRed v10.2.3
----------------------------------------------------------------------------------------------

More Information: 
Unhandled exception listening to AsyncPlayerChatEvent
NullPointerException (Unknown cause)
	 at org.mineacademy.chatcontrol.settings.Lang.ofScript(Lang.java:185)
	 at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:478)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:157)
	 at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:31)
	 at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
----------------------------------------------------------------------------------------------`

**Comment by ElBananaa** [comment]
> I do that actually, I sent the wrong error Im sorry.
> 
> ## `------------------------------------[ 13.02.2021 14:26:47 ]-----------------------------------
> ChatControlRed 10.2.3 encountered a NullPointerException
> Running Tuinity 1.16.5-R0.1-SNAPSHOT and Java 1.8.0_275
> Plugins: AntiCooldown v3.4, PlaceholderAPI v2.10.10-DEV-111, PlugMan v2.1.7, Admin360-Reloaded v8.0.0, OldCombatMechanics v1.9.0, DeluxeTags v1.8.1, TopTags v1.0.1, GSit v[2.14.1.0], NBTAPI v2.7.1, NoSpawnVillagers v1.0, SupremeTPA v3.0, CheaperPhysicsEvent v1.0-SNAPSHOT (build 2), VillagerOptimiser v1.1.5, PacketListenerApi v3.7.8-SNAPSHOT, BetterSpawners v1.2.7, GlowAPI v1.4.14-SNAPSHOT, BuycraftX v12.0.6, MapManager v1.7.10-SNAPSHOT, Votifier v2.7.2, AdvancedPortals v0.5.10, Vouchers v1.8.17-RELEASE, VoidGenerator v1.7.0, LimitPillagers v2.14.0, LangUtils v2.4.x, AdvancedAFK v1.3.2, AnimatedFrames v4.12.1-SNAPSHOT, ViaVersion v3.2.1, ViaBackwards v3.2.1-SNAPSHOT, LuckPerms v5.2.76, AnimatedScoreboard v0.2.3, ProtocolLib v4.6.0-SNAPSHOT-b483, LibsDisguises v10.0.24, ChatBrawl v1.7.3, Vault v1.7.3-b131, TokenManager v3.2.5, HolographicDisplays v2.4.6, SkinsRestorer v13.8.8, WitherAC v0.23.1, MyCommand v5.6.9, LagAssist v2.23.3, WorldEdit v7.2.2+fc3c499, PinataParty v2.16.3, HeadDatabase v4.13.4, Multiverse-Core v4.2.2-b812, TrMenu v2.08, SimpleClans v2.14.6, Citizens v2.0.27-SNAPSHOT (build 2186), PlayerAuctions v1.2.3, DeluxeMenus v1.13.3-Release, Lottery v1.4.3, CrazyCrates v1.10.1-SNAPSHOT-Build#95, VoidTeleport v2.3.6, HolographicExtension v1.10.9, LeaderHeadsRevamped v4.0.6, WorldGuard v7.0.4+f7ff984, Insights v5.9.3, MythicMobs v4.11.0-BETA-79e173ec, CoreProtect v19.4, SilkSpawners v7.0.0, EconomyShopGUI v3.0.2, mcMMO v2.1.132, FarmLimiter v1.5.1, Quests v3.9.5-b130, MarriageMaster v2.2.13-Release, IllegalStack v2.2.1a, ChestShop v3.11 (build 213), Shopkeepers v2.12.0, GriefPrevention v16.17.1-2b69191, TradePlus v3.77, GriefPreventionFlags v5.10.0, Wild v2.22-e6c1382, GPAccruals v1.1, PlayerWarps v6.4.0, Essentials v2.19.0-dev+70-34fdcf8, Elevator v3.11.0, DragonSlayer v0.10.3.1_Jeppa, AdvancedAchievements v6.2.0, TAB v2.8.10, SuperVanish v6.2.0, CombatLogX v10.3.7.1, EssentialsSpawn v2.19.0-dev+70-34fdcf8, WorldGuardExtraFlags v4.1.5-SNAPSHOT, MyPet v3.11, FlightControl v4.7.20-BETA, Jobs v4.17.0, DiscordSRV v1.21.1, AuthMe v5.6.0-SNAPSHOT-b2425, Duels v3.4.1, LiteBans v2.6, ChatControlRed v10.2.3
> More Information:
> Unhandled exception listening to AsyncPlayerChatEvent
> NullPointerException (Unknown cause)
> at org.mineacademy.chatcontrol.settings.Lang.ofScript(Lang.java:185)
> at org.mineacademy.chatcontrol.model.Channel.sendMessage(Channel.java:478)
> at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:157)
> at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:31)
> at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
> at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
> ----------------------------------------------------------------------------------------------`

please send us your `/chc debug` file.

**Comment by kangarko** [comment]
Just send us your debug log please

**Comment by ElBananaa** [comment]
@Danielpeter-99 Hey! Is there anything new? Can we close this?

**Comment by kangarko** [comment]
Closing but I'm waiting for you to comment below so we can get back and help ;)
