### ISSUE TITLE
/Unignore

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#675]
Simple one, a `/unignore` that isnt a /ignore alias but instead an ignore removal.

### 1. How it would benefit others?
I've noticed players on my server getting confused with the /ignore not knowing how to unignore players (yes even though there is more then enough info in /ignore help page)

"I cant see a /unignore in tabcomplete how do i unignore {insertplayername}"

### 2. What would happen if we won't implement this feature? How's your server being affected?

Nothing really, just confusion for them I guess.

**Comment by kangarko** [comment]
Thanks but no thanks, you can just use our rules to add your own help system with navigation on using /ignore twice to stop ignoring.

**Comment by LogGits** [comment]
No worries, i've made an alias that messages the player a tip saying "Ignore works as a toggle use it to unignore X"
