### ISSUE TITLE
1.16.5: Bad Optimization or error?

### ISSUE THREAD

**Issue by Syndr4** [kangarko/ChatControl#676]
Minecraft Version: 1.16.4
MySql: false
BungeeCord: false

I do not know if this will be an error or a bad optimization of the plugin but I am about to remove ChatControlRed from how bad it works on my server,  is impossible that with 40 players A CHAT PLUGIN uses 36% ...
I need a solution please
https://i.imgur.com/5RFL7wz.png

**Comment by arturek1666** [comment]
I mean it's worse for my server 50-60 players;
![image](https://user-images.githubusercontent.com/1558228/107863201-21490180-6e4a-11eb-8369-dccbb2a0c2e0.png)
looks like you are not the only one

**Comment by arturek1666** [comment]
Do you have any error in console, as I do but i use custom paperspigot so it might be different story.

**Comment by arturek1666** [comment]
My log:
https://gist.github.com/arturek1666/f9d9a02ac724791a644298e686cf968d

**Comment by Syndr4** [comment]
No, I don't have any errors, the plugin just uses a lot to be a chat system.

**Comment by arturek1666** [comment]
Do you use beta?

**Comment by arturek1666** [comment]
If you do change to that previous one, as with that one i have no error :) and performance are good

**Comment by radiant-ai** [comment]
> Minecraft Version: 1.16.4
> MySql: false
> BungeeCord: false
> 
> I do not know if this will be an error or a bad optimization of the plugin but I am about to remove ChatControlRed from how bad it works on my server, is impossible that with 40 players A CHAT PLUGIN uses 36% ...
> I need a solution please
> https://i.imgur.com/5RFL7wz.png

You need to read the timings properly, only a couple of your ticks have taken too long to process. Click `All` button to display average tick times and I am 100% sure ChatControl won't even appear in there.

**Comment by arturek1666** [comment]
even if when chatcontrolred is installed my players a annoying me with the game lags it freezes, after plugin is gone no issue what so ever.  Chatcontrol Pro had non of that issues, it really fills like a down grade xD

**Comment by arturek1666** [comment]
even all is too long for me anyway:
It uses more resource then an anticheat I currently use xD
![image](https://user-images.githubusercontent.com/1558228/107865139-8b1dd700-6e5b-11eb-8c28-c7a11e957ed9.png)
It need some good performance improvements anyway ;)
It's a fresh plugin so issues like that too be expected, compared to chatcontrol pro, the chatcontrol red is still a child that has to grow ;), Now it's just a waiting game ;)

**Comment by kangarko** [comment]
Post us your debug log guys...

**Comment by Syndr4** [comment]
My debug log:
https://ufile.io/4y9gdlky

**Comment by kangarko** [comment]
I just spent the last couple of hours moving parts of the save mechanism async, please use the next version and report anything that comes up
