### ISSUE TITLE
RGB incompatibility with luckperms prefix

### ISSUE THREAD

**Issue by Danielpeter-99** [kangarko/ChatControl#678]
When setting a luckperms prefix, chat will ignore & and use #, coming out with a glitched prefix.
It looks fine on our TAB, only chat is glitching.
![image](https://user-images.githubusercontent.com/70642181/107869483-90c7ec80-6e5c-11eb-8873-d9dae5af865b.png)

**Comment by ElBananaa** [comment]
Hey!
I don't have a such issue with the plugin and luckperms. You don't need to use `&#` in order to use rgb colors. It works with `#rrggbb`.

Here's an example of one of my prefixes: `prefix.90.&7[#00d7ebManager&7]&e`
