### ISSUE TITLE
Reload command broken

### ISSUE THREAD

**Issue by Her-Craving** [kangarko/ChatControl#68]
The reload command does nothing. The plugin does not reload and the entire server must be reloaded for anything to update.

**Comment by kangarko** [comment]
What do you mean by anything? It works just fine for me.

Reloading will reload the files in rules/ folder, settings.yml and localization.

**Comment by kangarko** [comment]
Reloading works except for enabling/disabling/changing:
- console filter
- any dependency - essentials, authme, protocollib, vault etc.
- timed messages (it will only reload them from settings.yml)
- updater

(as of v5.0.3 - might be changed later)

**Comment by Her-Craving** [comment]
Settings aren't changing for me in the config file when i /chatcontrol reload

**Comment by kangarko** [comment]
Then do a server restart. Reloading only the plugin or server with /reload is known to cause issues on certain configurations and does not always provide reliable results.

**Comment by Her-Craving** [comment]
Can you not just fix the /chatcontrol reload command to reload the config file? I am using spigot for 1.8

**Comment by kangarko** [comment]
The thing is, that the command is working for me. It was made so it reloads the config and rules and the things above. I am also using spigot 1.8 and it just works, I can't help you remotely.
