### ISSUE TITLE
PlaceholderAPI broken.

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#68]
When I add this in my chat.yml:

        Hover_Event:
          Action: SHOW_TEXT
          Values:
          - '&8*-----* &f{player} &8*-----*'
          - '&bSpeelt sinds: &7{player_first_join_date}'
          - '&bTotale speeltijd: &7{statistic_time_played}'
          - '&bTotale votes: &7{voteroulette_votes_lifetime}'
          - '&bAantal keer dood: &7{statistic_deaths}'
          - '&bSaldo: &7{vaulteco_balance_fixed}'

The placeholders are not working and shoot these errors:

27.02 21:29:03 [Server] WARN java.lang.NullPointerException
27.02 21:29:03 [Server] WARN at me.clip.placeholderapi.placeholders.PlayerPlaceholders.onPlaceholderRequest(PlayerPlaceholders.java:116)
27.02 21:29:03 [Server] WARN at me.clip.placeholderapi.PlaceholderAPI.setBracketPlaceholders(PlaceholderAPI.java:323)
27.02 21:29:03 [Server] WARN at me.kangarko.chatcontrol.com7.const(SourceFile:554)
27.02 21:29:03 [Server] WARN at me.kangarko.chatcontrol.coM6.const(SourceFile:204)
27.02 21:29:03 [Server] WARN at me.kangarko.chatcontrol.coM5.const(SourceFile:150)
27.02 21:29:03 [Server] WARN at me.kangarko.chatcontrol.coM5.const(SourceFile:136)
27.02 21:29:03 [Server] WARN at me.kangarko.chatcontrol.coM5.const(SourceFile:129)
27.02 21:29:03 [Server] WARN at me.kangarko.chatcontrol.prn.native(SourceFile:304)
27.02 21:29:03 [Server] WARN at me.kangarko.chatcontrol.NUL.const(SourceFile:345)
27.02 21:29:03 [Server] WARN at me.kangarko.chatcontrol.PrN.const(SourceFile:48)
27.02 21:29:03 [Server] WARN at me.kangarko.chatcontrol.aux.const(SourceFile:82)
27.02 21:29:03 [Server] WARN at me.kangarko.chatcontrol.aux.execute(SourceFile:45)
27.02 21:29:03 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
27.02 21:29:03 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
27.02 21:29:03 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
27.02 21:29:03 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084)
27.02 21:29:03 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022)
27.02 21:29:03 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
27.02 21:29:03 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
27.02 21:29:03 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
27.02 21:29:03 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
27.02 21:29:03 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
27.02 21:29:03 [Server] WARN at java.lang.Thread.run(Thread.java:745)
27.02 21:29:03 [Server] INFO [ChatControl] *----------------------------------------------*
27.02 21:29:03 [Server] INFO [ChatControl]  PlaceholderAPI failed to replace variables!

27.02 21:50:18 [Server] ERROR Could not pass event AsyncPlayerChatEvent to ChatControl v6.7.2-BETA
27.02 21:50:18 [Server] INFO java.lang.NullPointerException
27.02 21:50:18 [Server] INFO at me.clip.placeholderapi.placeholders.PlayerPlaceholders.onPlaceholderRequest(PlayerPlaceholders.java:116) ~[?:?]
27.02 21:50:18 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:390) ~[?:?]
27.02 21:50:18 [Server] INFO at me.kangarko.chatcontrol.coM6.const(SourceFile:519) ~[?:?]
27.02 21:50:18 [Server] INFO at me.kangarko.chatcontrol.com6.const(SourceFile:199) ~[?:?]
27.02 21:50:18 [Server] INFO at me.kangarko.chatcontrol.com5.const(SourceFile:150) ~[?:?]
27.02 21:50:18 [Server] INFO at me.kangarko.chatcontrol.com5.const(SourceFile:136) ~[?:?]
27.02 21:50:18 [Server] INFO at me.kangarko.chatcontrol.com5.const(SourceFile:129) ~[?:?]
27.02 21:50:18 [Server] INFO at me.kangarko.chatcontrol.NUL.native(SourceFile:300) ~[?:?]
27.02 21:50:18 [Server] INFO at me.kangarko.chatcontrol.nUL.const(SourceFile:341) ~[?:?]
27.02 21:50:18 [Server] INFO at me.kangarko.chatcontrol.PRn.const(SourceFile:44) ~[?:?]
27.02 21:50:18 [Server] INFO at me.kangarko.chatcontrol.aux.const(SourceFile:81) ~[?:?]
27.02 21:50:18 [Server] INFO at me.kangarko.chatcontrol.aux.execute(SourceFile:44) ~[?:?]
27.02 21:50:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
27.02 21:50:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
27.02 21:50:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
27.02 21:50:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
27.02 21:50:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
27.02 21:50:18 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
27.02 21:50:18 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
27.02 21:50:18 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
27.02 21:50:18 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
27.02 21:50:18 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
27.02 21:50:18 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
27.02 21:50:18 [Server] INFO [Legend] TheDutchPenguin: nooo ;-;
27.02 21:50:20 [Server] ERROR Could not pass event AsyncPlayerChatEvent to ChatControl v6.7.2-BETA
27.02 21:50:20 [Server] INFO java.lang.NullPointerException
27.02 21:50:20 [Server] INFO at me.clip.placeholderapi.placeholders.PlayerPlaceholders.onPlaceholderRequest(PlayerPlaceholders.java:116) ~[?:?]
27.02 21:50:20 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:390) ~[?:?]
27.02 21:50:20 [Server] INFO at me.kangarko.chatcontrol.coM6.const(SourceFile:519) ~[?:?]
27.02 21:50:20 [Server] INFO at me.kangarko.chatcontrol.com6.const(SourceFile:199) ~[?:?]
27.02 21:50:20 [Server] INFO at me.kangarko.chatcontrol.com5.const(SourceFile:150) ~[?:?]
27.02 21:50:20 [Server] INFO at me.kangarko.chatcontrol.com5.const(SourceFile:136) ~[?:?]
27.02 21:50:20 [Server] INFO at me.kangarko.chatcontrol.com5.const(SourceFile:129) ~[?:?]
27.02 21:50:20 [Server] INFO at me.kangarko.chatcontrol.NUL.native(SourceFile:300) ~[?:?]
27.02 21:50:20 [Server] INFO at me.kangarko.chatcontrol.nUL.const(SourceFile:341) ~[?:?]
27.02 21:50:20 [Server] INFO at me.kangarko.chatcontrol.PRn.const(SourceFile:44) ~[?:?]
27.02 21:50:20 [Server] INFO at me.kangarko.chatcontrol.aux.const(SourceFile:81) ~[?:?]
27.02 21:50:20 [Server] INFO at me.kangarko.chatcontrol.aux.execute(SourceFile:44) ~[?:?]
27.02 21:50:20 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
27.02 21:50:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
27.02 21:50:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
27.02 21:50:20 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
27.02 21:50:20 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
27.02 21:50:20 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
27.02 21:50:20 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
27.02 21:50:20 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
27.02 21:50:20 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
27.02 21:50:20 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
27.02 21:50:20 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by Sikatsu** [comment]
After checking further, I noticed it breaks when using this placeholder:

{player_first_join_date}

When I remove that one, everything works again.

**Comment by extendedclip** [comment]
This is my fault... Will be fixed in PlaceholderAPI 2.0.8. Update is being pushed shortly after I test to confirm this issue is fixed.

**Comment by Sikatsu** [comment]
Thanks!

**Comment by kangarko** [comment]
Resolved by the developer of PlaceholderAPI.
