### ISSUE TITLE
1.16.4 MySQL | The permissions list is a mixture of links.

### ISSUE THREAD

**Issue by viasnake** [kangarko/ChatControl#68]
Some of the permissions listed in `/chc permissions` are links.
Clicking on them will take you to the URL of the permissions.

![image](https://user-images.githubusercontent.com/6961187/99160305-4635b780-2729-11eb-9d12-3309caa8e54d.png)
![image](https://user-images.githubusercontent.com/6961187/99160309-4c2b9880-2729-11eb-94d2-0aca9d4c5fa3.png)

Environment
--------------
Java: Java 14
Server software: git-paper-267
Version: ChatControl-Red-10.0.4

**Comment by kangarko** [comment]
Thanks, will be fixed.
