### ISSUE TITLE
In the messages folder, add a "sleep.rs" to change sleep messages

### ISSUE THREAD

**Issue by itsBeaco** [kangarko/ChatControl#680]
<!---
Notice: Some of the best ideas and features we added were thanks to your suggestions. However, as an extremely small team we're focusing on stability and performance of our software first before adding new features. As such, we're currently very limited to taking in new features.

If you still believe your feature should be added, you're welcome to suggest it and answer those questions in your description: 

1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
Just like the fun quit, join and death messages people could add personalised sleep messages. I've had people on my server request it and I think it could be a fun feature as well. 

2. What would happen if we won't implement this feature? How's your server being affected?
I'd just have to find another way to implement it, since there is already quit, join, death, timed and kick messages I think it would only be an extra benefit to user and your plugin :)

I think it would be awesome to have a "sleep.rs" files alongside the current messages that are included with the plugin :)

Thank you!
Connor

**Comment by ElBananaa** [comment]
Hey!
Please follow the suggestion format.
I'm closing this suggestion, feel free to open a new one using the format or @ me here when you update you post so I can reopen it.
