### ISSUE TITLE
1.16.5: "ignore channel" not working as I epexted?

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#684]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

I wanted to disable ``group advertisement`` and ``group swear`` when  ``/ch send admin`` is used, however when I used 
``ignore channel admin`` in ``groups.rs`` it wouldn't prevent swearing in the main chat or on signs etc. Is this normal behavior?

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5984418/debug.2.zip)

**Comment by kangarko** [comment]
Just to understand this, you are saying that if you use "ignore channel admin" it will break the rule and made it not work for the main chat as well as signs etc?

**Comment by TheIntolerant** [comment]
Yes basically, also for reference I have the perms setup to autojoin "standard" channel in write mode and "admin" channel in read mode.

**Comment by kangarko** [comment]
Thanks, will get patched
