### ISSUE TITLE
/list - not working

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#687]
My **/list** won't work, nothing shows in spigot console except me executing the command

**bungee console:**
16.02 12:52:08 [Server] INFO Incoming packet LIST_PLAYERS_RESPONSE from Main
16.02 12:52:08 [Server] INFO Response collected from Main

but no message to me on the server

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Check if you are connected through BungeeCord. Also if you have installed only one and the latest jar of BungeeControl **Red**. Lastly check any other plugins if they cause any issues, try only with ChatControl Red and nothing else.

![a](https://i.imgur.com/eMsCQiM.png)
