### ISSUE TITLE
chat games

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#689]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
it's great to have a built in chat game that work this nicely
2. What would happen if we won't implement this feature? How's your server being affected?
people love small thing and if there was an option like this under this big development and updates is going to be greate
Thank you. Please remove this text and write your actual suggestion below.
-->
add game chat like this https://github.com/DragonHunt3r/ChatGames to be setup and used as it should

**Comment by ElBananaa** [comment]
Hey!
Thanks for suggestion.

Tbho, I don't know if this is something that will be done, and if so, I guess it'll wait since our priority is to stabilize the plugin as much as possible. However, also keep in mind that chatcontrol is a chat management plugin. ^^

**Comment by Squeej** [comment]
I like this idea but, it seems like it would distract players from the actual game, and result in unwanted chat spam for those who aren't interested in the concept.

**Comment by kangarko** [comment]
Thanks for suggesting this.

However, we are a chat plugin with a very tiny development team, and I am afraid this would take away from our core focus and cause more bugs left unfixed. So I have to politely reject this.
