### ISSUE TITLE
Timed broadcast above action bar

### ISSUE THREAD

**Issue by mormoon** [kangarko/ChatControl#69]
Would it be possible to add a feature to make the timed broadcast appear above the actionbar, like this example? http://www.spigotmc.org/threads/solved-hook-into-action-bars-text-area.43087/

**Comment by kangarko** [comment]
Currently not but I am leaving it open for the possible implementation in the future. Keep in mind although I am focussing on server in general this is still mainly a chat plugin.

**Comment by kangarko** [comment]
Sorry, I am busy with other features and this one has little to do with chat. ChatControl is open source so maybe you can ask some developer to fetch timed messages from it to the action bar.
