### ISSUE TITLE
1.16.5: 'Then warn' operator not working for death messages

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#691]
Below is a link to the error log as well as the debug zip. I'm trying to send death coordinates with the warn operator while also displaying the original death message, but it's not working. Using version 10.2.2

https://pastebin.com/C3MxtjU3

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5993478/debug.zip)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey! As said in your error log, the "then warn" operator doesn't work in death messages. Idk if this is intended or not, so I'll leave this ticket open. Just wait for Kangarko's answer ;)

**Comment by Squeej** [comment]
That's what I assumed at first and almost made a suggestion for it, but then I saw this in the wiki under 'messages' and figured it's suppose to be a working feature:

**then warn < message >**
Optional message to send to the sender (such as the player who died, etc.). Use | to define multiple messages, one of which will be selected randomly. Use the {player} variable to get the player and other variables normally.

To send multiline warn messages, you can use multiple "then warn" operators multiple times on new lines.

**Comment by kangarko** [comment]
Sure, I will make the operator "then warn" work for messages as well. Got it working:

![a](https://i.imgur.com/OjcxQtM.png)
