### ISSUE TITLE
Question: What is shared through bungeecord across all servers

### ISSUE THREAD

**Issue by Westloch** [kangarko/ChatControl#692]
~~How do you enable/use the remove message function? i do not see it in settings.yml~~ <--figured it out

Also what else is shared when using bungeecord, besides chat? forexample: nick names, join messages, leave messages, death messages, etc 

read the wiki and it just says bungee is supported but not exactly what is supported

plugin version: 10.2.3

**Comment by TheIntolerant** [comment]
Nicknames are stored in the MySQL database so they are the same across all servers.
As for join messages, you can choose to either use

https://github.com/kangarko/ChatControl-Red/wiki/messages#bungee
for messages in chatcontrol itself

or 

the join network/switch server/leave network, message system in BungeeControl (required on the bungee server) for bungeecord to work for ChatControl. (Also you do not need to pay extra for BungeeControl)

**Comment by ElBananaa** [comment]
Hey!

I think @gone-incognito said everything (BTW, thanks for answering :D).
Would you like to know something else, or can I close this?

**Comment by Westloch** [comment]
when using chatcontrol on muliple servers (on a bungee network) do all the files need to be exactly the same or do you configure one and just enable mysql on all?

**Comment by ElBananaa** [comment]
> when using chatcontrol on muliple servers (on a bungee network) do all the files need to be exactly the same or do you configure one and just enable mysql on all?

Well, if you wish to have the exact same features on each server, you'll have to use the same files on each server. But it isn't required. The only thing needed to link servers is the mysql database. So each server needs an unique name, and linked to the same database.

**Comment by Westloch** [comment]
Do the names for each server need to be added to any of the chatcontrol file?

**Comment by TheIntolerant** [comment]
https://mineacademy.org/server-properties
Yeah, it's added to the server.properties file

**Comment by Westloch** [comment]
great, thanks for the fast replies!

**Comment by ElBananaa** [comment]
> great, thanks for the fast replies!

Thanks again @gone-incognito for answering!
I'm closing this issue, feel free to open a new one if you need anything else, or keep commenting down below, I'd be more than happy to help! :D

**Comment by kangarko** [comment]
Thanks to Banana for helping out!

You can have different setups on different Spigot servers. If you have Integration.BungeeCord on true and use the same MySQL database, then you should however have "channel" names the same if you want channels and channel-related features to work properly.

Also if you use Discord then you should have linked all channels you want to use on the whole network for every server.
