### ISSUE TITLE
Custom chat commands using javascript?

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#693]
Would it be possible to add support for implementing custom chat commands that hook into javascript files? For example, I would like to add a ``/random`` command that outputs a specific formatted message line in chat with a random number between 1 and 99999 -- publicly broadcasting the message to everyone in the chat channel (global chat or private channels).

**Comment by kangarko** [comment]
Hey!

Sure, just create a variable outputting that number and then create a command rule for that:

![a](https://i.imgur.com/TVgeu2I.png)

**Comment by mibby** [comment]
Is it possible to tie the command syntax back to the variable with a specific value? For example, ``/random 2`` would roll a number between 1-2. ``/random 9999`` would roll a number between 1-9999. Whole numbers only, defining what the maximum range is, and broadcasting to everyone.

**Comment by kangarko** [comment]
Not by any simple means, you'd be better off creating your own Java plugin instead.
