### ISSUE TITLE
1.16: Part Plotsquared 5 not working

### ISSUE THREAD

**Issue by FETXU** [kangarko/ChatControl#694]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

We have a Plotsquared 5 installed, and if we try using the following in the channels config it does not run chat inside the plot.

It could be that CC is made to work with the old P2 4 version.

Any chance we could get some confirmation on what P2 this is supposed to work on? 

Cheers :)

    PLOT:
      Format: chat-plot
      Party: plotsquared-plot
      Discord: true

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> We have a Plotsquared 5 installed, and if we try using the following in the channels config it does not run chat inside the plot.
> 
> It could be that CC is made to work with the old P2 4 version.
> 
> Any chance we could get some confirmation on what P2 this is supposed to work on?
> 
> Cheers :)
> 
> ```
> PLOT:
>   Format: chat-plot
>   Party: plotsquared-plot
>   Discord: true
> ```

Hey!
The plugin doesn't automatically change your chat channel.
However, it does work with Plotsquared v3, and v5 (Idk for v4, but I guess it should work too). (See #341)

**Comment by FETXU** [comment]
So what exactly is, and how do we use the party chat property? There is a specific PlotSquared party property you can set in config?

**Comment by ElBananaa** [comment]
> So what exactly is, and how do we use the party chat property? There is a specific PlotSquared party property you can set in config?

Well, basically, this feature means that every player talking in the channel `PLOT` will automatically be talking in his plotchat. As said on #640, the plugin doesn't automatically change your channel. However, this can be achieved using the API.

**Comment by FETXU** [comment]
So it is automatic? 

My question here is:
How do I make Plots work Chat Control? 

I have set up plotsquared. 
Plot chat works in plot squared using /plot chat.
I have plotsquared-plot set in party property.

I enter my chat control plot channel, but I am not in the plot channel.

**Comment by ElBananaa** [comment]
> So it is automatic?
> 
> My question here is:
> How do I make Plots work Chat Control?
> 
> I have set up plotsquared.
> Plot chat works in plot squared using /plot chat.
> I have plotsquared-plot set in party property.
> 
> I enter my chat control plot channel, but I am not in the plot channel.

Regarding your first question, as I already said 2 times, no, it's not automatic. However, the API can be used to make it automatic, but there's no such function in the plugin itself.

Regarding the second part, I misexplained myself. Here's what's explained in the config file:
```
  # - Party: Makes the channel players only reach other players in the same party. This can work
  #          together with Range, but does not require that option. 
  #          Available values: factions-faction, plotsquared-plot, towny-town, towny-nation,
  #          mcmmo-party and lands-land
  #          Warning: The Party option does not work over BungeeCord!
```
Basically, players won't be in the `/plot chat`, but into a channel that works like plot chat.

**Comment by FETXU** [comment]
Thank you, and sorry for the double question. I misunderstood you.. twice :| Apologies.

Do you have a link to the API docs? I will find a dev to help us out :)

**Comment by kangarko** [comment]
We don't currently have an API docs because the plugin's code is not obfuscated, just download and decompile ChatControl's jar ;)

**Comment by nikitushu2** [comment]
> 
> 
> > So it is automatic?
> > My question here is:
> > How do I make Plots work Chat Control?
> > I have set up plotsquared.
> > Plot chat works in plot squared using /plot chat.
> > I have plotsquared-plot set in party property.
> > I enter my chat control plot channel, but I am not in the plot channel.
> 
> Regarding your first question, as I already said 2 times, no, it's not automatic. However, the API can be used to make it automatic, but there's no such function in the plugin itself.
> 
> Regarding the second part, I misexplained myself. Here's what's explained in the config file:
> 
> ```
>   # - Party: Makes the channel players only reach other players in the same party. This can work
>   #          together with Range, but does not require that option. 
>   #          Available values: factions-faction, plotsquared-plot, towny-town, towny-nation,
>   #          mcmmo-party and lands-land
>   #          Warning: The Party option does not work over BungeeCord!
> ```
> 
> Basically, players won't be in the `/plot chat`, but into a channel that works like plot chat.

Does it mean that when you stand on roads (i.e between plots) then all the people who are on roads will see each others messages and they won't see the messages of those who are on plots?

**Comment by nikitushu2** [comment]
I am sorry but I am misunderstanding something.

There are plots. There are roads between them. The roads are not considered as plots. By these definitions, plotsquared-plot party chat must not work on roads (because it must work on plots only). But on roads, the plotsquared-plot party chat is not disabled nor it gets switched (you explained that I need an API for this). 

But isn't it a bug then that on roads plotsquared-party chat still keeps working?

**Comment by kangarko** [comment]
We do not automatically change the chat mode.

If people stand on roads, then maybe it will get the players also standing on roads. I am not sure, because we only call PlotSquared to ask for players in the same plot.

So if PlotSquared is not considering a road to be a plot, then they will still be able to talk but no one will hear them.
