### ISSUE TITLE
1.16.4: Toggle send cryptic msg if you not has perms for a special type

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#695]
If you not have perm for special type like chat,death (if you has for example only perms for toggle or toggle.me).

You get this error.

![perms](https://user-images.githubusercontent.com/16368286/108319860-4fb83b00-71c2-11eb-86d3-cbe0a7616b2e.png)

I dont know if this is normal (if it is (ignore this part).
And when I run /toggle list and push on * "click to stop ignoring" it run /toggle "your type. Is it something I need set up (is similar problem on other I try too)? 
![2021-02-18_08 25 04](https://user-images.githubusercontent.com/16368286/108320735-7cb91d80-71c3-11eb-82bc-cc629ded8c04.png)

Minecraft Version: 1.16.4
chatcontrol red: 10.2.4
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Hi!

That is correct, we show invalid message when the user lacks permissions for that toggle type.

I am afraid we don't support '*' in the argument. When I clicked on all links in /toggle list it worked fine, please let me know if I misunderstood your message!

![a](https://i.imgur.com/EqiKYcB.png)

**Comment by broken1arrow** [comment]
> Hi!
> 
> That is correct, we show invalid message when the user lacks permissions for that toggle type.
> 
> I am afraid we don't support '*' in the argument. When I clicked on all links in /toggle list it worked fine, please let me know if I misunderstood your message!
> 
> ![a](https://camo.githubusercontent.com/29a81e04c41a5b3e2c05306f7b75837e901d4e109dfa9ea9fa05e69157cf5bd2/68747470733a2f2f692e696d6775722e636f6d2f4571694b5963422e706e67)

Was a valid command /toggle death i get that if i has no perms it should say you has no perms, as it do if i not has toggle perm.

Was some debugging for know what is wrong, when is not working. I have to use lp verbose for see what was wrong.

Other one is what chc set default for remove toggle when use /toggle list and push in chat. So I need edit it in translation?

**Comment by kangarko** [comment]
Just edit the translation for now. I can have a look into adding no-permissions message for partial parts that you lack permission for later.
