### ISSUE TITLE
Bungee custom player join/leave messages

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#697]
Now that ChatControl Red has been released, I was hoping you could add this suggestion. When I first suggested this for ChatControl Pro, it was mentioned the new ChatControl would have such a feature, while it does, it's not bungee compatible at the moment.

An option to give certain ranks a custom player join/leave message.

**Comment by ElBananaa** [comment]
> Now that ChatControl Red has been released, I was hoping you could add this suggestion. When I first suggested this for ChatControl Pro, it was mentioned the new ChatControl would have such a feature, while it does, it's not bungee compatible at the moment.
> 
> An option to give certain ranks a custom player join/leave message.

Hey!
Can't you already achieve this with the actual system in your join.rs/quit.rs?

**Comment by Sikatsu** [comment]
I tried, it works but it also shows the messages on a server switch. I would like it to be a network-wide thing ^^

**Comment by Sikatsu** [comment]
Else it will become very spammy in the chat as well

**Comment by TheIntolerant** [comment]
Just to add clarification, since the join.rs and quit.rs aren’t able to tell the difference between switching servers or disconnecting from the bungee network, therefore you’d see a doubling up of messages (message of them leaving and joining a different server). So I assume this is something that’d need to be implemented in BungeeControl itself.

**Comment by kangarko** [comment]
Thanks, yes there are plans to level-up messages to the bungee level in the future, I'll keep you posted however right now there's no ETA for this.

**Comment by Sikatsu** [comment]
Hm, this has been said before back in the ChatControl Pro times. I would really like to have this feature to work with. All I basically need is an option to disable the messages from showing on a server switch.

This way I can add custom messages to Patreons, or even make them vote perks.

Please let me know if it's possible anytime soon, it's the only thing I'd really like.

**Comment by kangarko** [comment]
Thanks, we're getting a developer help with Redis integration and I can ask her to handle this feature also if possible.
