### ISSUE TITLE
1.16.5: death.rs problem

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#698]
So I had death.rs set to do the original minecraft message, which worked and then I updated for the first time in a while and its just a blank space when a death message happens now

**Death.rs:**
https://pastebin.com/nH423kN4

Minecraft Version: 1.16.5
MySQL: true - not using for the messages
BungeeCord: true - not using bungee for the messages

**Comment by ElBananaa** [comment]
> So I had death.rs set to do the original minecraft message, which worked and then I updated for the first time in a while and its just a blank space when a death message happens now
> 
> **Death.rs:**
> https://pastebin.com/nH423kN4
> 
> Minecraft Version: 1.16.5
> MySQL: true - not using for the messages
> BungeeCord: true - not using bungee for the messages

Hey. Your death.rs seems to be empty. Try ti remove it and restart your server. It should regenerate it properly
