### ISSUE TITLE
Multiple before replace

### ISSUE THREAD

**Issue by MineTheCube** [kangarko/ChatControl#7]
Hi,

In a rule, I wanted to replace any accent by the corresponding letter, so I typed:
```
before replace (é|è|ê) with e
before replace (â|à) with a
```

But when I reload, it says "replace before already set".. Is there any way to add multiple "before replace" ?

**Comment by kangarko** [comment]
Hey,

no this is not possible. In premium version, accents are replaced internally without the need to add this operator. You can do a workaround and include the accents in the regex itself, like
>match f(u|ú)ck
>handle as swear

**Comment by MineTheCube** [comment]
The regex contains about 200 chars.. So replacing every accented vowels by matching vowel would be really innefficient.. :/

Is it possible to add this in free version ?

**Comment by kangarko** [comment]
I might try but no promises, and I have some features in premium that take priority first.
