### ISSUE TITLE
1.16.4 BungeeCord/MySql - Nick not following player from one server to the next and is not long enough

### ISSUE THREAD

**Issue by Godlycreations** [kangarko/ChatControl#70]
If you set a nickname on one server, then move to another server, the nickname does not follow the player to the next server, meaning that you have to set a new nickname on each server. We also need an option that allows us to change the max length of the nickname. Right now we are restricted to only 10 characters, so if I wanted to do &e&lF&6&lo&e&lG to make a bold, colored FoG, I cannot do it. Many of our players love setting highly colored nicks and so having the option to set our own max length would be great.

**Comment by kangarko** [comment]
Thanks I will fix that!

Regarding the length, remove rules/tag.rs and let the new file be regenerated in the new version. We now have this rule natively in settings.yml in Tag section to exclude colors
