### ISSUE TITLE
1.16.5: Join clear (empty) chat?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#700]
Minecraft Version: 1.16,5
MySQL: true
BungeeCord: true

Hi, is it possible to join with clear (empty) chat when using bungeecord? Cause when players are on lobby, there could be some messages that I don't wanna display when they join another servers. So something like clearing chat after player join, but just for him?

**Comment by kangarko** [comment]
No sorry, but you can work this around by sending empty messages to players on join.
