### ISSUE TITLE
1.16.5: World Chat

### ISSUE THREAD

**Issue by darrennrena** [kangarko/ChatControl#701]
I used to own CCP and want to get CCR i just need to know can i group worlds by adding them in some way to a group (or as you say might work MV Alias's) so world, the end and nether would be survival and that survival group would get messages in that world and not from say bedwars, skyblock etc

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false
I use Multiverse

**Comment by ElBananaa** [comment]
> I used to own CCP and want to get CCR i just need to know can i group worlds by adding them in some way to a group (or as you say might work MV Alias's) so world, the end and nether would be survival and that survival group would get messages in that world and not from say bedwars, skyblock etc
> 
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: false
> I use Multiverse

Hey!
I'm not sure to completely understand what you would like to do, bu yes, you can send message to specific world(s)/server(s). You can take a look at the conditions you could use there: https://github.com/kangarko/ChatControl-Red/wiki/Messages.
In your case, this might be what you're looking for: https://github.com/kangarko/ChatControl-Red/wiki/Messages#require-sender-world-world-name-and-require-receiver-world-world-name

**Comment by darrennrena** [comment]
I want to group my worlds so my main world, hub and nether are grouped as "Survival" and they can only send and see messages in that group, Bedwars Hub and bedwars games would also be grouped and they would only see and send messages in chat to the bedwars group. As with sky block and so on. i dont use multi servers i run one with multiverse.

**Comment by ElBananaa** [comment]
> I want to group my worlds so my main world, hub and nether are grouped as "Survival" and they can only send and see messages in that group, Bedwars Hub and bedwars games would also be grouped and they would only see and send messages in chat to the bedwars group. As with sky block and so on. i dont use multi servers i run one with multiverse.

Well, as said above, you can use the `require receiver world` condition in order to do that. I don't think you can directly create groups like you'd like to. However, what you want to do is pretty easy to setup. Here's an example of timed messages (`plugins/ChatControlRed/messages/timed.rs`) that'll only be sent to players in the worlds named `hub`, `survival` and `test1`:

(Quick note: The `group default-messages` used at the top isn't what you're looking for, this is only used to toggle the messages.)
```
group default-messages
delay 10 seconds
require receiver world hub|survival|test1
message:
- a simple test message
- a very cool message
```

**Comment by darrennrena** [comment]
Sooooo theres no solution really for my issue? for a 30 ish plugin?

**Comment by ElBananaa** [comment]
> Sooooo theres no solution really for my issue? for a 30 ish plugin?

Hey!
The price of the plugin doesn't mean the plugin will have any feature that actually exists.
However, there's a solution, and I gave it to you 2 times. The solution doesn't work like you imagined it, but it works, so it's a solution. :)

Anyways, if you wish to, you can make open a suggestion, we're more than happy with any suggestion that could improve the plugin and benefits its users! :D

**Comment by kangarko** [comment]
Banana I think Darrennrena was talking about chat channels not messages.

To achieve this, simply create a chat channel with the range option set on "*" and specify a list of worlds you want to connect using the example of me doing it below:

![a](https://i.imgur.com/YlmrLSm.png)

Let me know below if I understand you properly and you still need any more help!
