### ISSUE TITLE
TryMe support (disable similarity when TryMe is enabled)

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#702]
Hi, cause in TryMe plugin https://www.spigotmc.org/resources/tryme.3330/updates is hang man mode and so many other modes that work the way that you type in chat worlds or letters, then the similarity check is a little bit problem, cause it doesn't allow players to guess multiple times similar worlds. I think about disabling similarity for now, but couldn't you try to make a hook that will always disable similarity when the question from TryMe is sent? And may also chat message cooldown, but this could be as option.

**Comment by kangarko** [comment]
Thanks! However that's something they should add, we have an API and don't obfuscate our code.
