### ISSUE TITLE
Updated DiscordSRV hook

### ISSUE THREAD

**Issue by Vankka** [kangarko/ChatControl#703]
Hello,

I've recently received a report of Minecraft -> Discord chat not working with DiscordSRV's snapshots, while ChatControl is the main chat plugin used. I believe this is caused by https://github.com/DiscordSRV/DiscordSRV/commit/3f3d97b6013017fbd56d7529e2e88183e332c78e which limited Minecraft -> Discord chat forwarding to a channel called `global` *unless* a ChatHook is registered, in which case the message would be forwarded to it for forwarding instead. 

[ChatHooks](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/hooks/chat/ChatHook.java) can be added via `DiscordSRV.getPlugin().getPluginHooks().add(...)` and have been around since v1.19.0 (March 2020)

Feel free to ask any questions, I'll do my best to answer them as soon as possible

Thanks,
Vankka, DiscordSRV Developer

**Comment by kangarko** [comment]
Hey! Thanks for the heads up, I will update! 

Just to be clear, what is the recommended way of implementing this? Assuming this needs to be placed and called in onEnable... also what about supporting /reload or /chatcontrol reload ?

![a](https://i.imgur.com/4PBhyW7.png)

**Comment by Vankka** [comment]
Placing it in `onEnable` is fine, but the time you add it at doesn't matter. If you store the PluginHook in a variable you can remove it from the pluginHooks when you disable, `DiscordSRV.getPlugin().getPluginHooks().remove(...);`. When something is added or removed from the plugin hooks list, DiscordSRV will adjust to using that automatically - even without a reload.

**Comment by kangarko** [comment]
Thank you! https://github.com/kangarko/Foundation/commit/36d677eb9c05dc99533dbb2582ad7ed3cfea4db7
