### ISSUE TITLE
1.16.5: Trying to figure out what plugin is effecting rukes.

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl#704]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hiya, I am trying to figure out what plugin isn't allowing me to interact with the rules if you could let me know that would be amazing I have enclosed my debug.zip in hopes it will help.
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6011122/debug.zip)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hiya, I am trying to figure out what plugin isn't allowing me to interact with the rules if you could let me know that would be amazing I have enclosed my debug.zip in hopes it will help.
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6011122/debug.zip)

Hey! I don't know which plugins doesn't let you interact with the rules, but you could try changing the `Chat_Listener_Priority:` in your settings.yml to see if it changes anything (Don't forget to restart the server when you change it). Also make sure there's no other chatplugin on your server, and make sure that your plugins, your server softwares and your dependencies are up-to-date.

**Comment by kangarko** [comment]
Thanks Banana! 

Test different Chat_Listener priorities as per our Wiki. If that doesn't work then simply use plain ChatControl and no other plugin and install other plugins one by one to see which is blocking it.
