### ISSUE TITLE
1.16.5: Players able to send messages while muted

### ISSUE THREAD

**Issue by altruiis** [kangarko/ChatControl#706]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

(Using LiteBans)
Players who are muted are still able to send messages using /ch send <channel> <message> or /ch sendas <player><channel> <message>. They cannot chat normally, but using those commands they are able to chat. It should be able to hook into LiteBans to detect if they're muted and then prevent those commands from sending messages.

**Comment by TheIntolerant** [comment]
This isn't a chatcontrol issue as you are using litebans to mute people however to fix the issue.
Just add ``/ch`` and ``/channel`` or any other aliases you have for channels/chat commands you have in use. In the “command blacklist” part the config of Litebans under “mutes”

As shown here at line 99
[LiteBans Config](https://gitlab.com/ruany/LiteBans/blob/master/config.yml)

**Comment by ElBananaa** [comment]
Hey!

@gone-incognito Thanks for answering.
I'm closing this issue, feel free to open a new one if you need anything else! :)
