### ISSUE TITLE
1.16.5: Command for toggling admin chat stopped working

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#707]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, this command stopped working from some reason, players can't turn back into normal mode. I think it was due to some of the latest updates.

![image](https://user-images.githubusercontent.com/18662086/108578568-5a3e1600-7323-11eb-848d-8253affda259.png)

```
# This rule only executes when player is not in the admin channel for reading.
match ^(\/ach)
dont verbose
ignore channel admin write
then command channel join admin write
then deny

# This rule only executes when player is in the admin channel for writing.
match ^(\/ach)
dont verbose
require channel admin write
then command channel join standard write
then deny
```

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, this command stopped working from some reason, players can't turn back into normal mode. I think it was due to some of the latest updates.
> 
> ![image](https://user-images.githubusercontent.com/18662086/108578568-5a3e1600-7323-11eb-848d-8253affda259.png)
> 
> ```
> # This rule only executes when player is not in the admin channel for reading.
> match ^(\/ach)
> dont verbose
> ignore channel admin write
> then command channel join admin write
> then deny
> 
> # This rule only executes when player is in the admin channel for writing.
> match ^(\/ach)
> dont verbose
> require channel admin write
> then command channel join standard write
> then deny
> ```

Hey! Try removing the backslash, I'm not sure about it, but I think it isn't necessary anymore.

**Comment by JessePesse123** [comment]
Hey Banana! I'm having the same issues and i didn't implement the backslash

**Comment by JessePesse123** [comment]
Don't mInd the language :):

```
match ^/act
require channel standard write
dont verbose
then command channel join admin write
then warn &aStaffchat gejoined! &fAlles wat je zegt komt nu in de staffchat.
then deny

match ^/act
require channel admin write
dont verbose
then command channel join standard write
then warn &cStaffchat Verlaten! &fAlles wat je zegt komt nu in de gewone chat.
then deny
```

**Comment by bobhenl** [comment]
It has been broken in one of the newest updates...

**Comment by TheIntolerant** [comment]
I’d assume this is due to

**Solved a vulnerability when using "ignore channel" in rules/groups allowing players to bypass the given rule/group anywhere else by simply writing to the ignored channel, such as on books or signs.**

In the latest update.

**Comment by ElBananaa** [comment]
Alright, I just tried it on my prod server with the latest version, and it seems to be working perfectly.
That's exactly what I used:

```
# This rule only executes when player is not in the admin channel for reading.
name adminchat
match ^(\/ach)
dont verbose
ignore channel staffchat write
then command channel join staffchat write
then deny

# This rule only executes when player is in the admin channel for writing.
name adminchat
match ^(\/ach)
dont verbose
require channel staffchat write
then command channel join general write
then deny
```

**Comment by bobhenl** [comment]
Eh, no? :D 
![image](https://user-images.githubusercontent.com/18662086/108613202-149b4f00-73f0-11eb-989c-cb95db7153c5.png)

**Comment by ElBananaa** [comment]
> Eh, no? :D
> ![image](https://user-images.githubusercontent.com/18662086/108613202-149b4f00-73f0-11eb-989c-cb95db7153c5.png)

Are you using ChatControl-Red 10.2.5? Could you please provide us your debug file?
Also try removing the `name adminchat` from both parts and let me know if it fixes the issue.

**Comment by JessePesse123** [comment]
Well Banana that doesn't work all the time, e.g. we also use the same method with /p  and if you would say matchc (\/p) then /pv would also be matched

**Comment by JessePesse123** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6018096/debug.zip)

**Comment by JessePesse123** [comment]
match /p$ doesnt work

**Comment by bobhenl** [comment]
> Alright, I just tried it on my prod server with the latest version, and it seems to be working perfectly.
> That's exactly what I used:
> 
> ```
> # This rule only executes when player is not in the admin channel for reading.
> name adminchat
> match ^(\/ach)
> dont verbose
> ignore channel staffchat write
> then command channel join staffchat write
> then deny
> 
> # This rule only executes when player is in the admin channel for writing.
> name adminchat
> match ^(\/ach)
> dont verbose
> require channel staffchat write
> then command channel join general write
> then deny
> ```

Just btw your command is exact like mine but I have another name for "staffchat -> admin" and name adminchat couldn't work twice probably

**Comment by ElBananaa** [comment]
> > Alright, I just tried it on my prod server with the latest version, and it seems to be working perfectly.
> > That's exactly what I used:
> > ```
> > # This rule only executes when player is not in the admin channel for reading.
> > name adminchat
> > match ^(\/ach)
> > dont verbose
> > ignore channel staffchat write
> > then command channel join staffchat write
> > then deny
> > 
> > # This rule only executes when player is in the admin channel for writing.
> > name adminchat
> > match ^(\/ach)
> > dont verbose
> > require channel staffchat write
> > then command channel join general write
> > then deny
> > ```
> 
> Just btw your command is exact like mine but I have another name for "staffchat -> admin" and name adminchat couldn't work twice probably

Hey!
Yeah, you must adapt it to your server.
Unfortunately, I don't think I could help more with this, I'm not used/good enough with regex :/
You'll have to wait for kangarko.

**Comment by TheIntolerant** [comment]
> Eh, no? :D
> ![image](https://user-images.githubusercontent.com/18662086/108613202-149b4f00-73f0-11eb-989c-cb95db7153c5.png)

That just means that there is no rule for ``name <rule_name>`` to be applied too, as ``name`` needs to be used after ``match`` not before.



> Well Banana that doesn't work all the time, e.g. we also use the same method with /p and if you would say matchc (/p) then /pv would also be matched

You can used
``match (/p)$``
``match /p$``
``match /(p)$`` etc
they should all work the same just as long as you use ``$`` at the end, so chat control knows that is the end of the string.

-----------------------------------------------
I also tried the /ach command and couldn't manage to get it to work using the default config for cc
I think ``ignore channel`` and ``require channel`` aren't working correctly.

I tested with
```
match ^(\/test)
require channel standard write
then warn send this message if writing in standard channel
then deny
```
AND
```
match ^(\/test2)
ignore channel standard write
then warn send this message if not writing in standard channel
then deny
```
neither of the rules above worked as they should after I typed ``/ch join standard write``, and than typing ``/ch join admin write``. This leaves me to assume it is something to do with the changes to ``ignore channel`` on the latest version.

**Comment by kangarko** [comment]
Apologies, looks like the operator change broke this, investigating right now.

**Comment by kangarko** [comment]
Alright so the last update changed this in the correct way, because by logic we only check "channels" in chat.rs file since this is where rules are checked from messages.

There is no channel associated when player is typing a command, when he is signing a book etc.

I understand how this can actually cause issues specifically for commands, so I added an exception henceforth.
