### ISSUE TITLE
1.16.5 | Plugin disabled on load after a server restart

### ISSUE THREAD

**Issue by sarhatabaot** [kangarko/ChatControl#708]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

https://pastebin.com/UkrZU418
Cannot run chc debug since plugin is disabled on load.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> https://pastebin.com/UkrZU418
> Cannot run chc debug since plugin is disabled on load.

Hey!
For some reason, an entry in your log doesn't match the format for the logs, which breaks the plugin. Stop your server, remove the log file in the plugin directory, and start it again, it should fix the issue.
