### ISSUE TITLE
1.16.5: Is it possible to set `` Stop_On_First_Match: false`` for timed messages but not for all other message types?

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#709]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

I just wanted to know if it was possible to set this ``Stop_On_First_Match: false`` for ``timed.rs`` but leave ``death.rs``, ``join.rs``, ``quit.rs`` etc as ``Stop_On_First_Match: true``? If not is this something that could be added in the future?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> I just wanted to know if it was possible to set this `Stop_On_First_Match: false` for `timed.rs` but leave `death.rs`, `join.rs`, `quit.rs` etc as `Stop_On_First_Match: true`? If not is this something that could be added in the future?

Hey!
As far as I know, this isn't possible as for now. However, I'll leave this ticket open so Kangarko could take a look at your suggestion.

**Comment by kangarko** [comment]
Sorry we're not planning to split our config that much. It will become too complicated like last time in Pro and people won't understand it. Rather it's less options and there's always the option for you to use our API to develop your own hook.
