### ISSUE TITLE
1.16.4 BungeeCord/MySql - Error with CHC communicating with SaberFactions plugin.

### ISSUE THREAD

**Issue by Godlycreations** [kangarko/ChatControl#71]
My factions server uses Saber Factions and was not having any issues with the CHC plugin until this update. Now it is giving the errors found in the errors.log attached below. In game it appears to be working just fine. If you need additional information, please let me know.

[error.log](https://github.com/kangarko/ChatControl-Red/files/5541722/error.log)

**Comment by kangarko** [comment]
Thank, you can increase Regex_Timeout_Ms in settings.yml to 50 or even 100. We had it on 100 for years, I now put it on 10 to see how plugin performs. Seems like some rules are taking a bit longer on your server.
