### ISSUE TITLE
Support PlaceholderAPI

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl#71]
Please add support for PlaceholderAPI :dancers:

**Comment by EvilOlaf** [comment]
Ask and you shall receive it: https://www.spigotmc.org/resources/chatcontrol-pro-sale-70-update-500-downloads.10258/

**Comment by rErEaT** [comment]
what about free version? :S

**Comment by EvilOlaf** [comment]
The free version will not receive any greater feature updates, mostly bug  and security fixes only.

**Comment by rErEaT** [comment]
sure

**Comment by EvilOlaf** [comment]
This is the way @kangarko chose to maintain his plugins. But I can almost guarantee that the pro version is worth its money ;)

**Comment by rErEaT** [comment]
I dont have paypal to buy that :/

**Comment by kangarko** [comment]
I shall consider it, but the variable system that version use is a bit confusing in its internals, so no warranties :)
