### ISSUE TITLE
1.16.5: Can't switch between channels after nick change

### ISSUE THREAD

**Issue by darosleal** [kangarko/ChatControl#710]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, when i try to change between channels after nick change, no message appears, and nothing happens.
![image](https://user-images.githubusercontent.com/57519648/108609922-265d0200-73b0-11eb-8a0a-e72d461279b0.png)
And in the database my nickname is repeated twice, but with a different UUID. I tried to delete my duplicate UUID, but the problem still persist.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, when i try to change between channels after nick change, no message appears, and nothing happens.
> ![image](https://user-images.githubusercontent.com/57519648/108609922-265d0200-73b0-11eb-8a0a-e72d461279b0.png)
> And in the database my nickname is repeated twice, but with a different UUID. I tried to delete my duplicate UUID, but the problem still persist.

Hey!
For some reason, none of the 2 UUIDs shown here is actually [yours](https://fr.namemc.com/profile/Thrashjoking.3).
Is your server in offline mode? That might be the reason of the issue.
I don't have a such issue on my own server which is in online mode.

**Comment by darosleal** [comment]
Yes, it is in offline mode, but with a semi-premium login system that changes the UUIDs to avoid UUID collisions.  
https://github.com/Jakubson/JPremiumCleared/wiki#fixed-unique-ids

**Comment by darosleal** [comment]
I updated ChatControl Red to the latest version, and now when I try to switch channel I get that I am not connected through BungeeCord

**Comment by ElBananaa** [comment]
> I updated ChatControl Red to the latest version, and now when I try to switch channel I get that I am not connected through BungeeCord

Alright, which mode are you using with your plugin? I don't know much about how the plugin deals with non-premium accounts, but you should give it a try with the `REAL` mode. Keep in mind that however, the changes might not work since you already changed your name.
If you use the `REAL` mode, stop your server, remove one of the two entries with your nick from the database, and update your UUID using the real one: https://namemc.com/profile/Thrashjoking.3 `e3d33464-41bd-4e20-aaa4-7970d72975ef`.

**Comment by darosleal** [comment]
Now i'm using my real UUID (e3d33464-41bd-4e20-aaa4-7970d72975ef) and I still can't change channels...
![image](https://user-images.githubusercontent.com/57519648/108691473-4e488480-74da-11eb-84e8-9bd962590396.png)

**Comment by kangarko** [comment]
Are you talking about switching nicks in /tag nick or switching Mojang username (https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames) ?

**Comment by darosleal** [comment]
Mojang username

**Comment by darosleal** [comment]
A user just changed their mojang username and this problem did not happen to them, so right now I don't really know when this bug occurs

**Comment by ElBananaa** [comment]
> A user just changed their mojang username and this problem did not happen to them, so right now I don't really know when this bug occurs

That's pretty weird tbho. Could you try to stop your network and remove any entries with your name from the plugin database? Does it changes anything?

**Comment by ElBananaa** [comment]
> A user just changed their mojang username and this problem did not happen to them, so right now I don't really know when this bug occurs

Hey! Since you closed this issue, I guess it is solved? If so, could you please explain how did you do? It'll help us in case someone else runs the same issue

**Comment by darosleal** [comment]
I closed it because I switched to ChatControl Pro, I could never solve the problem in Red.

**Comment by ElBananaa** [comment]
> I closed it because I switched to ChatControl Pro, I could never solve the problem in Red.

Hey!
Alright, that's up to you.
However, Kangarko will probably take a look at this issue once he gets back. I'll let you know if there's anything new then.
