### ISSUE TITLE
Suggestion: Parse Receiver Prefix for PM

### ISSUE THREAD

**Issue by darosleal** [kangarko/ChatControl#711]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
The private messages would look better, and you could easily distinguish the rank of the person who is speaking to you (Admin, Helper)

2. What would happen if we won't implement this feature? How's your server being affected?
Users are complaining that the new format without prefix is confusing and ugly, because we had the previous format for 3 years with Player Prefix in ChatControl Pro

**Comment by gone-incognito** [comment]
Not sure if this helps so I'll keep it short, inside ``ChatControlRed > formats`` you should find a file called ``pm-receiver.yml`` and ``pm-sender.yml`` 

That is where you should be able to change the formatting for pm's similar to ChatControlPro. If you get confused just refer to https://github.com/kangarko/ChatControl-Red/wiki/Formats

**Comment by ElBananaa** [comment]
Thanks for your suggestion!
Related to #690

**Comment by kangarko** [comment]
We cannot please everyone.

People were complaining that the variables were parsed for the receiver, now you are (the only one) complaining about the opposite. 

I added {receiver_prefix} variable you can use IN LIMITED CONTEXT without guarantee, it should work
