### ISSUE TITLE
1.12.2: change command help format

### ISSUE THREAD

**Issue by NoobiousMcNoob** [kangarko/ChatControl#712]
How to I change the usage format of the command?
For example, if I type /reply it gives this usage page:
--------------Usage--------------
Description:
Reply to the last player who messaged you

/reply <message>.
How do I customize this?

Minecraft Version: 1.12.2
MySQL: false
BungeeCord: true

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Red/wiki/Localization
