### ISSUE TITLE
1.16.5: Hex color codes not supported when use on Luckperms prefix

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl#713]
I tested with {luckperms_prefix}, {player_prefix}, {player_prefix+} and still not works perfectly.

<img width="453" alt="Screenshot 2021-02-21 142158" src="https://user-images.githubusercontent.com/8324198/108626457-93c06f80-7450-11eb-82ea-043461c1789d.png">

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> I tested with {luckperms_prefix}, {player_prefix}, {player_prefix+} and still not works perfectly.
> 
> <img alt="Screenshot 2021-02-21 142158" width="453" src="https://user-images.githubusercontent.com/8324198/108626457-93c06f80-7450-11eb-82ea-043461c1789d.png">
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false

Hey.
You don't need to use `&` in your prefix. Simply use `#RRGGBB`

**Comment by andris155** [comment]
Thanks!
