### ISSUE TITLE
1.16.5: Rules not work in mcMMO party chat and PlotSquared chat

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl#719]
The all ChatControl rules not work in  in mcMMO party chat and PlotSquared chat.
<img width="446" alt="Screenshot 2021-02-22 153619" src="https://user-images.githubusercontent.com/8324198/108722700-bbccd300-7523-11eb-9ad9-c048be8a8e2b.png">

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
This chat is not seen by ChatControl Red, unfortunately. As last resort we've added the option to change how to see the chat in the events pipeline, you can read and tweak this as per the following article:

https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

**Comment by andris155** [comment]
Thanks!
