### ISSUE TITLE
Caps bypasses replace system

### ISSUE THREAD

**Issue by johandrex** [kangarko/ChatControl#72]
Okay, I've tested it out. It does handle it as swear then and does the message but it doesn't replace it.

Regex:
http://gyazo.com/a72834a88851eea59b423fd6542759cb

Proof it just works:
http://gyazo.com/a2899a44c1f503fa24d6cda2fb519016

So, with the capital it works, without it doesn't.

// Written by Chris_GSPvP

**Comment by kangarko** [comment]
Please follow #76
