### ISSUE TITLE
1.16.4 MySQL | book variable is not working.

### ISSUE THREAD

**Issue by viasnake** [kangarko/ChatControl#72]
Books opened with the `/chc book open` command do not support variables.

![image](https://user-images.githubusercontent.com/6961187/99161018-eba05980-2730-11eb-9886-bab71da2e598.png)

Environment
--------------
Java: Java 14
Server software: git-paper-267
Version: ChatControl-Red-10.0.4
MySQL version: 8.0.22 MySQL Community Server - GPL

**Comment by kangarko** [comment]
Thanks will be fixed!
