### ISSUE TITLE
1.16.5: Incompatibility with Paper-1.16.5 #473+

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#720]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

Hey!
Paper recently officially implemented Adventure (https://github.com/KyoriPowered/adventure) in replacement of Bungee chat component. The issue is that, since this version, the remove/purge features don't work anymore. There's absolutely no errors in the console, but clicking on the remove button doesn't work anymore, and using the `/chc purge <player>` neither.
However, we can still click on other things in the chat, and it works properly. Same with the chat clear.

**Comment by Ekmot276** [comment]
WARNING: You are not using Paper!

Third party forks such as Tuinity are known to alter
our plugin's behavior. If you have any problems, test
using Paper only otherwise you will get NO SUPPORT.

Have you tested this on latest spigot?

**Comment by ElBananaa** [comment]
> WARNING: You are not using Paper!
> 
> Third party forks such as Tuinity are known to alter
> our plugin's behavior. If you have any problems, test
> using Paper only otherwise you will get NO SUPPORT.
> 
> Have you tested this on latest spigot?

**Server Version: Paper v1_16_R3**
I didn't try under spigot, but I can almost guarantee that this is related to the latest paper update. It works properly with versions prior to paper 473

**Comment by ghost** [comment]
But you're using normal Paper?

**Comment by ElBananaa** [comment]
> But you're using normal Paper?

I do. I usually run Purpur, and it works perfectly with it. However, in order to make sure this isn't related to purpur, this was also tested under Paper.

**Comment by kangarko** [comment]
Thanks, however right now I don't have enough understanding of this new system nor the resources needed to implement a new one from our side. I will keep this in the backlog, thank you!
