### ISSUE TITLE
1.16.5: BungeeCord breaks Mails

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#721]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Okay... It looks like BungeeCord kinda breaks the mailing system.
When you have a Bungee-Setup and send a mail to "all" and you delete the message on one client its been removed from the inbox - which works fine, but if you reload the plugin or restart the server after the mail will show up again in the clients inbox.

I did some magic (yea im sorry for that i know im not supposed to, but I deleted all "Mails:" from the data.db and restarted the server.

After rejoining and using /mail inbox the mail was back, but the mail itself wasnt saved as a file in data.db UNTIL i tried to delete the mail on 1 client, after which the data.db was filled again with all mails.

The overall issue im having is, that im not able to delete any past mails, because they are always coming back, even if I just switch to a different server under the bungee-network. Idk how the plugin handles the mails, but there might be an file/mysql conflict, im not sure.

debug.zip
https://ufile.io/a01nxi2w

**Comment by kangarko** [comment]
Thanks, fixed this. Essentially we simply forgot to call db update after a mail has been removed so that is why it got loaded again on reload.
