### ISSUE TITLE
Image Message - player head?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#723]
Hi, I wanna suggest way to use skin player names in image messages. So you could for ex. display head of Notch or specific player who receives the message, mainly this... if it would be possible.

**Comment by ElBananaa** [comment]
> Hi, I wanna suggest way to use skin player names in image messages. So you could for ex. display head of Notch or specific player who receives the message, mainly this... if it would be possible.

Hey!
This seems to be a pretty heavy task for the plugins while it aims at performances.
Actually, it would require to fetch each player skin using mojang's/crafatar api, then replace the image for each player with his own head.

However, I'll let Kangarko give you an answer once he get back. :)

**Comment by kangarko** [comment]
Thanks but not for now, I feel this is too complex to keep our focus right now (we already have crazy amount of features). Just download images you want to use frequently to the images folder.

**Comment by ghost** [comment]
Maby you could just allow to pull the image frrom a webhost and use a server like Crafatar, this feature actually might be pretty cool to have:

https://crafatar.com/

**Comment by kangarko** [comment]
Thanks I may consider this in the future but not right now.
