### ISSUE TITLE
[Improvement] Velocity Support

### ISSUE THREAD

**Issue by ArgonGaming** [kangarko/ChatControl#724]
_Notice: Some of the best ideas and features we added were thanks to your suggestions. However, as an extremely small team we're focusing on stability and performance of our software first before adding new features. As such, we're currently very limited to taking in new features._

_If you still believe your feature should be added, you're welcome to suggest it and answer those questions in your description:_ 

**1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**

> Many people would benefit from this compatibility due to the sheer amount of server owners using this newly optimized method of networking. Velocity acts as a better performing Bungeecord.

[Read more here](https://velocitypowered.com/wiki/users/what-does-velocity-do-for-me/)

This is highly worth looking into, as this plugin could affect the entire market of "Velocity plugins". It would undoubtedly be the best chat plugin that is compatible with Velocity, and in turn grow it's player base.

**2. What would happen if we won't implement this feature? How's your server being affected?**

It is affecting for those who use Velocity because it would mean having to use other plugins / methods to achieve only less than half the features ChatControl red allows for. That is why this plugin is a perfect candidate to introduce to Velocity.

**Comment by ArgonGaming** [comment]
**In addition:** A developer is willing to help with porting the entire plugin! 

You can contact Juliafromthegamers@outlook.com

OR 

stormfront#5479 on discord

She will require the open source, and she has already stated it may be a difficult task due to the inclusion of the licensing system, and verifications, but it can be done and is well worth it.

**Comment by radiant-ai** [comment]
Yeah, Velocity-based server count grows every day. And the latest Velocity versions support plugin messaging, so it won't require any changes in code for Spigot/Paper servers. Personally I am in a process of switching to Velocity right now and I am sure a lot of users would appreciate and consider CCR as their chat plugin when it has Velocity support.

**Comment by ghost** [comment]
Velocity-Support would be amazing 👍

**Comment by cades66** [comment]
It would, I vouch. Velocity is the future of proxies on these networks.

**Comment by kangarko** [comment]
Thanks guys, however I literally have 0 experience with Velocity and does not have the time and resources feasible to learn/implement this.

So I made BungeeControl Red open source:

https://bitbucket.org/kangarko/bungeecontrol-red/src/master/

Anyone can take this project over and I'll be more than happy to collaborate to bring this to Velocity asap.

If someone thinks he is capable enough please send a working prototype over matej@mineacademy.org and I will create a repo for you.

**Comment by kangarko** [comment]
I emailed Julia, thanks Argon.
