### ISSUE TITLE
I cant use deluxe tags with chatcontrolred

### ISSUE THREAD

**Issue by TenReeez** [kangarko/ChatControl#725]
Minecraft Version: 1.13.2 and 1.16.5
MySQL: true
BungeeCord: true

Hey I cant use deluxetags with chatcontrolred.

Ive been using chatcontrolfree, but for the life of me i cant work out how to add tags. for the paid version. AM I doing something wrong etc? 
Its really an awesome plugin, but players prefer their tags over chatcontrolreds bells and whistles.. 📦 
ANy ideas on a fix anyone?

Thanking you.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.13.2 and 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hey I cant use deluxetags with chatcontrolred.
> 
> Ive been using chatcontrolfree, but for the life of me i cant work out how to add tags. for the paid version. AM I doing something wrong etc?
> Its really an awesome plugin, but players prefer their tags over chatcontrolreds bells and whistles.. 📦
> ANy ideas on a fix anyone?
> 
> Thanking you.

Hey!
It works perfectly fine for me.
Please provide your `/chc debug` file so I could take a look at you files, and see if there's anything wrong.

**Comment by TenReeez** [comment]
What would be the format? Ive tried:     Message_Format: '{pl_prefix}{player}:{pl_suffix} {message}' 
Come to think of it, I wouldnt have a clue how to add deluxe tags to a players name in chat. ANy help would be appreciated. I have gone through all 28 pages here on the Github looking :/

**Comment by TenReeez** [comment]
I have worked it out. Thankyou for helping ElBananaa :)
