### ISSUE TITLE
1.16.5: Ignoring command section on Discord?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#728]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, how could please I ignore command section on Discord? there isn't anything like     Sender_Condition: '!{sender_is_discord}' in rules that I could add to these "command rules"... and what about if I wanna ignore whole commands section?

So, and if I would just block specific command, which rule to use there to ignore discord?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, how could please I ignore command section on Discord? there isn't anything like Sender_Condition: '!{sender_is_discord}' in rules that I could add to these "command rules"... and what about if I wanna ignore whole commands section?
> 
> So, and if I would just block specific command, which rule to use there to ignore discord?

Hey!
In rules, you can user: `require script {sender_is_player}` to do this. `{sender_is_player}` will only return true if a players does the action, not the console nor a user from discord.
