### ISSUE TITLE
Toggle all messages back to default for players who lost the permission

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#729]
As the title says, it would be great to turn on/off some hidden messages for those players who lost the `toggle` permission node. Right now when a player gets demoted/promoted and their permissions update, those players may no longer be able to turn some messages back on.

For example staff on my server can turn off death and join/leave messages, but when they get demoted, they no longer able to turn on the messages back.

I think this improvement is a good small detail needed for a lot of servers who allow to turn off/on messages for some player groups.

Alternatively, the permission node can also be split into e.g `toggle.death.on` and `toggle.death.off` and the command be changed into `/toggle <on|off> <message type>`

**Comment by kangarko** [comment]
Thanks, will put this to the backnode for future implementation like we did with "/chc purge"

**Comment by kangarko** [comment]
Added on/off permissions!
