### ISSUE TITLE
1.16.5: chat.rs "!" command issue

### ISSUE THREAD

**Issue by C0ffeL0Ve** [kangarko/ChatControl#731]
Using the ChatcontrolRed 10.2.5
I activated the ! and also made a /g and /global command for my players to be able to send Messages to global without needing to enter the channel itself but to only be able to send global message using the ! or /g or /global command.

My issue it this: 
When the code pastes the $2 string that i think that refers to the text i can't insert COLORS on the message.
For example when i write "/g &6Hello world" the actual text only show "Hello world" without the color
Is there some way to fix this? or this is intended. Here is my code (nothing changed by the default value)

`# Send messages starting with "!" to global channel`
`match ^(\!)(.*)`
`then command channel send global $2`
`then deny`
`dont verbose`

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Hey, set Rules.Strip_Colors to false in settings.yml to avoid this (please read the comments above this key to understand the implications and how it works)
