### ISSUE TITLE
1.16.5: {player_prefix+} on Discord?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#732]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, it's good that when you type from discord to game it shows your linked name from game... but why it doesn't show your prefix when I'm using {player_prefix+} there? What to use as variable (placeholder) then to show prefix when someone types from Discord to game? Couldn't you make this supported also in this case?

**Comment by kangarko** [comment]
We don't support any placeholders on Discord as they require the Player instance which must be a real online player who is typing on a Spigot server. You can probably use PlaceholderAPI if they support some of this but no guarantee.

**Comment by bobhenl** [comment]
Mhm tried from this page but it didn't work :/ https://github.com/DiscordSRV/DiscordSRV/wiki/PAPI-Placeholders

**Comment by kangarko** [comment]
Sorry for a late reply, unfortunately right now they are unsupported as it seems, but we made it possible to completely disable our Discord integration so you can use the one from DiscordSRV instead.

**Comment by bobhenl** [comment]
Mhm ok, but hopefully one day it will come. I can't switch, when i've tried it it didn't work from some reason. Messages weren't sent from Discord to game. Happening on one of the latests snapshots, you've implemented this https://github.com/kangarko/ChatControl-Red/issues/703, but it doesn't work without integration enabled.

About using integration, I rather use your now cause it uses nicknames from game + has hover message, way to share admin chat & helpop channels too etc. So I prefer your integration. The only thing that's missing is this, pinging @mentions, colors from Discord to game and way to disable emojis :D

**Comment by NoobcoreNetwork** [comment]
Ah this might explain why i cannot get the players nickname tag to send to discord right?
