### ISSUE TITLE
1.16.5: Disabling emojis from Discord?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#733]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, could I somehow make rule to disable emojis from Discord or something like that?
![image](https://user-images.githubusercontent.com/18662086/109043846-09873e00-76d2-11eb-9923-b6168ad6ca5c.png)

![image](https://user-images.githubusercontent.com/18662086/109043851-0ab86b00-76d2-11eb-86fe-f8d23c2fad42.png)

**Comment by kangarko** [comment]
Hmm you could just uncomment this rule in chat.rs:

```
# Prevent special, unicode characters. Those are misused to bypass filters.
# Please keep in mind that non-English languages use them, so only uncomment this on English servers.
#match [^\u0000-\u007F]+
#then replace
```

**Comment by bobhenl** [comment]
Hm, but I still wanna allow diacritics from Discord, so any other idea?

+ any idea how to prevent this? There are 2 bots from 2 servers in one channel and this is happening when I've tried search for some combinations, I've tried:
```
([^a-zA-Z0-9_ěščřžúůôĺľäýíáéďťň]|\d|_)*
(\:\w+\:|\<[\/\\]?3|[\(\)\\\D|\*\$][\-\^]?[\:\;\=]|[\:\;\=B8][\-\^]?[3DOPp\@\$\*\\\)\(\/\|])(?=\s|[\!\.\?]|$)
\\b[A-Z\\s!@#$%^&*()\\_-+={}[\\]:;\"'<>?,./]+\\b
(\u00a9|\u00ae|[\u2000-\u3300]|\ud83c[\ud000-\udfff]|\ud83d[\ud000-\udfff]|\ud83e[\ud000-\udfff])
```

But nothing worked as expected
![image](https://user-images.githubusercontent.com/18662086/109172932-93dbaa80-7783-11eb-9ccb-db81e0f3b2ed.png)

**Comment by kangarko** [comment]
Sorry I misunderstood, what were the two messages that you typed that got caught? 

You can also use "ignore string" as it accepts a regex too.

**Comment by bobhenl** [comment]
About similarity, it happened when I used some emoji from Discord in message with mentioned examples.

And what ignore string do you suggest me to ignore just emojis and not diacritics? Like mentioned above, I've tried few examples but they didn't work as I wanted.
![image](https://user-images.githubusercontent.com/18662086/109835511-8cb11280-7c43-11eb-8f1a-0176be37e25e.png)
Wanna ignore just these cause they can't be transformed there

**Comment by kangarko** [comment]
I will completely remove Emoji from the next version by default.
