### ISSUE TITLE
1.16.5: server:xxx doesn't work for image type

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#734]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I wanna report that image type is missing value server:xxx.
![image](https://user-images.githubusercontent.com/18662086/109075249-2a16be80-76f9-11eb-9476-52e42659467c.png)

**Comment by kangarko** [comment]
Unfortunately the image parser is above the code for parameters, this is the only exception due to different nature of parameters for the image, sorry about that: https://i.imgur.com/xmhoV6n.png
