### ISSUE TITLE
1.16.5: Remaining space doesn't work?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#735]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, i'm not really sure if remaining space works as it should...
![image](https://user-images.githubusercontent.com/18662086/109075850-fe480880-76f9-11eb-87c5-bcb9fe5917c0.png)
This is showing empty lines when there's so much characters, shouldn't it show less lines if it has more rows? Shouldn't be lines fulfilled until the end of the chat visibility without pressing T?

**After scrolling up**
![image](https://user-images.githubusercontent.com/18662086/109075881-09029d80-76fa-11eb-86fa-1e44d381a94e.png)
This is the whole one.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, i'm not really sure if remaining space works as it should...
> ![image](https://user-images.githubusercontent.com/18662086/109075850-fe480880-76f9-11eb-87c5-bcb9fe5917c0.png)
> This is showing empty lines when there's so much characters, shouldn't it show less lines if it has more rows? Shouldn't be lines fulfilled until the end of the chat visibility without pressing T?
> 
> **After scrolling up**
> ![image](https://user-images.githubusercontent.com/18662086/109075881-09029d80-76fa-11eb-86fa-1e44d381a94e.png)
> This is the whole one.

Hey!
No, this isn't possible since the text size in the chat depends on the chat window size. So it you have a little chat windows, only a few words can full it. There's no way to get your chat size, so unfortunately I guess Kangarko can't do anything about that.

**Comment by bobhenl** [comment]
Oh, and how is then remaining space counted?

**Comment by kangarko** [comment]
Unfortunately this only works if you use the "|" operator in the message. Otherwise we cannot calculate/estimate how many lines there are as Banana explained. (Or I am unable of writing such code :P)
