### ISSUE TITLE
1.16.5: Using RGB in rules (packet.rs)?

### ISSUE THREAD

**Issue by EnTIv** [kangarko/ChatControl#736]
I want to use RGB in the rule file, but it doesn't work.

```
match ^I'm sorry, but you do not have permission to perform this.*|^You do not have access to that command.
then deny
then console tellraw '{player}' {"text": "#f15bb5[!] no permission"}
dont verbose
```

I noticed that I was able to use format `then warn NoPermission`
I have a lot of messages that need to be replaced.
I don't want to make a format file for every message.
So can I just send some of the messages, such as 

packet.rs:
```
then warn essentials.fly
then warn essentials.home
then warn essentials.gamemode
```

essentials.yml(format)
```
Parts:
  fly:
    Message: 'you fly'
  home:
    Message: 'home'

```

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: true

**Comment by kangarko** [comment]
What about using the hex in "then warn" directly?

"then warn #f15bb5[!] no permission"

**Comment by EnTIv** [comment]
I also want to use hover and run_ command.

**Comment by EnTIv** [comment]
> What about using the hex in "then warn" directly?
> 
> "then warn #f15bb5[!] no permission"

Because I want to use hover and run_ command.

**Comment by ElBananaa** [comment]
> > What about using the hex in "then warn" directly?
> > "then warn #f15bb5[!] no permission"
> 
> Because I want to use hover and run_ command.

Hey!
Your issue is due to wrong usage of json text. In order to use hex colors in JSON, you must do it like that:
`/tellraw @p {"text":"Test message 0101","color":"#FF5900","clickEvent":{"action":"run_command","value":"/say test"},"hoverEvent":{"action":"show_text","contents":[]}}`.

You can use websites like this one: https://minecraftjson.com/ to generator JSON messages.

**Comment by EnTIv** [comment]
> > > What about using the hex in "then warn" directly?
> > > "then warn #f15bb5[!] no permission"
> > 
> > 
> > Because I want to use hover and run_ command.
> 
> Hey!
> Your issue is due to wrong usage of json text. In order to use hex colors in JSON, you must do it like that:
> `/tellraw @p {"text":"Test message 0101","color":"#FF5900","clickEvent":{"action":"run_command","value":"/say test"},"hoverEvent":{"action":"show_text","contents":[]}}`.
> 
> You can use websites like this one: https://minecraftjson.com/ to generator JSON messages.

![image](https://user-images.githubusercontent.com/38716516/111729178-7775ee00-88a9-11eb-85a3-963837284c6f.png)
It still doesn't seem to work....

**Comment by kangarko** [comment]
Interesting, sorry I am unable to help because I'm not familiar with the JSON format in tellraw, you can just use "then warn format" and change the format to a format's name from formats.yml to send a message that way

**Comment by EnTIv** [comment]
> Interesting, sorry I am unable to help because I'm not familiar with the JSON format in tellraw, you can just use "then warn format" and change the format to a format's name from formats.yml to send a message that way

If the command is sent from the console, it works, but if it is sent from ChatControlRed, it doesn't work

**Comment by kangarko** [comment]
Interesting, will investigate but I still highly recommend sending interactive text using formats not a tell raw feature

**Comment by EnTIv** [comment]
I need to create more than 100 format files, which is a bit inconvenient...

**Comment by kangarko** [comment]
Solved, please in the next version prepend all hex codes with \ like this: https://i.imgur.com/fILgMuE.png And it will work.
