### ISSUE TITLE
1.16.5: {original_message} does not work in death.rs

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#737]
Yeah so I tried everything on my end, spits out a blank space every time someone dies

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6040774/debug.zip)

https://pastebin.com/0JRVViK1

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
What do you mean / what message?

![a](https://i.imgur.com/zfbir5A.png)

This is what I see.... both players get " (survival)" because the original message is empty. To fix that use {original_message+} instead and remove the space after it.

**Comment by Squeej** [comment]
Tried that, still nothing. Is original message suppose to be a placeholder for the the vanilla minecraft death message? I'm trying to make it so it announces the vanilla death message over bungee, with the server name at the end included

**Comment by kangarko** [comment]
Sorry that was actually a bug I detected and fixed!
