### ISSUE TITLE
1.16.5: Regex to match command /eventrewardXXXX A B C D doesn't work

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#739]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi guys, I want to ask why this regex doesn't work in ChatControl.
```
#Match when someone type /eventodmenalehci <event_name> <player1|X> <player2|X> <player3|X>, /eventodmenastredni <...> ..., /eventodmenatezsi <...> .....
match ^(\/eventodmena.*)
dont verbose
then write logs/eventy.log {timestamp_short}: Hráč {player} vykonal {original_message}
```

By regex page it should be ok
![image](https://user-images.githubusercontent.com/18662086/109315111-76bddf00-784a-11eb-9fa3-5a51716b628e.png)
So what's wrong there please? It isn't added to the log :/ Only when I type /eventodmena, but nothing else

#This one isn't logged any way
![image](https://user-images.githubusercontent.com/18662086/109315180-89d0af00-784a-11eb-826a-05efbd91043e.png)

#Here were logged only /event, when I had in match just /event, and only /eventodmena, but it doesn't log /eventodmenalehci etc...
![image](https://user-images.githubusercontent.com/18662086/109315186-8d643600-784a-11eb-95b9-e40f577335c9.png)

+ Why I have double date there please?

**Comment by TheIntolerant** [comment]
I tested on ``ChatControlRed 10.2.7`` and it seems to work fine, if you haven't updated yet, make sure you do, as, for a double date in your logs, please note you do not need to add `` {timestamp_short}`` with ``then write``

Instead, try this,
```rs
# Match when someone type /eventodmenalehci <event_name> <player1|X> <player2|X> <player3|X>, /eventodmenastredni <...> ..., /eventodmenatezsi <...> .....
match ^(\/eventodmena.*)
dont verbose
then write logs/eventy.log Hráč {player} vykonal {original_message}
```

If you are still having issues please type ``/chc debug`` and upload your debug.zip file

**Comment by bobhenl** [comment]
Oh yes it works, may it's due to I just used reload.

And don't you know how to start logging ONLY if the first part eventodmenalehci/eventodmenastredni... is fullfiled + then at least 2 arguments?

**Comment by ElBananaa** [comment]
Hey!
Thanks @gone-incognito for answering.

@bobhenl I'm not used to regex at all, but you could give a try to something like `match ^(\/eventodmena.*) (.*) (.*)`
Once again, I'm probably wrong about this since I don't know much about regex, but giving it a try only costs a few seconds ^^

**Comment by bobhenl** [comment]
![image](https://user-images.githubusercontent.com/18662086/109373327-65a6b980-78ae-11eb-8f9b-e137e06fdfbe.png)
No :/ May you could try let it open if someone has an idea how to do it.

**Comment by ElBananaa** [comment]
> ![image](https://user-images.githubusercontent.com/18662086/109373327-65a6b980-78ae-11eb-8f9b-e137e06fdfbe.png)
> No :/ May you could try let it open if someone has an idea how to do it.

Sure, since I wasn't sure about my answer, I woudn't have closed your issue anyways :)

**Comment by TheIntolerant** [comment]
The only other thing I can think of is the location that you put it in ``commands.rs``. Remember chatcontrol checks from top to button, so if my commands.rs file looked something like this

```
# run command when user runs /eventodmena etc
match ^(\/eventodmena.*)
then command <command>
then deny

#Match when someone type /eventodmenalehci <event_name> <player1|X> <player2|X> <player3|X>, /eventodmenastredni <...> ..., /eventodmenatezsi <...> .....
match ^(\/eventodmena.*)
dont verbose
then write logs/eventy.log {timestamp_short}: Hráč {player} vykonal {original_message}
```

The second rule where it logs to ``eventy.log`` would never get executed due to the ``then deny`` part of the rule above

In other words, try adding
```
#Match when someone type /eventodmenalehci <event_name> <player1|X> <player2|X> <player3|X>, /eventodmenastredni <...> ..., /eventodmenatezsi <...> .....
match ^(\/eventodmena.*)
dont verbose
then write logs/eventy.log {timestamp_short}: Hráč {player} vykonal {original_message}
```
To the top of the ``commands.rs`` file

**Also**
Did you want to also match ``/eventrewardXXXX .....`` or ``/eventreward ......``?

If so you can use this in that rule instead.
``match ^\/(eventodmena|eventrewardXXXX)(.*)``
OR
``match ^\/(eventodmena|eventreward)(.*)``

![53483438435](https://user-images.githubusercontent.com/48093184/109374311-8d2a7000-7908-11eb-95ff-7a25274e6d68.JPG)

**Comment by TheIntolerant** [comment]
If none of that worked than I suggest looking at the rules part of ``settings.yml``
As shown here https://pastebin.com/2xt3SSfh

**Comment by bobhenl** [comment]
Wait you probably missunderstood me.

I meant that I want to match just:

/eventodmenaLEHCI Event <player>
/eventodmenaSTREDNI event <player> <player>

Only if there are at least 2 arguments, so only if they specify just the first player. THe XXX is just example, XXXX = lehci, stredni, tezsi

**Comment by kangarko** [comment]
To match just those two commands, use:

```
match ^(\/eventodmena(lehci|stredni)) .*
dont verbose
then write logs/eventy.log {timestamp_short}: Hráč {player} vykonal {original_message}
```

Or something like that - this will only match IF there are 2 one-word arguments exactly:

![a](https://i.imgur.com/rjnG0rT.png)

**Comment by bobhenl** [comment]
Ok, thanks.
