### ISSUE TITLE
1.16.4 - /chc mute does not exist

### ISSUE THREAD

**Issue by Qw4rtz** [kangarko/ChatControl#74]
The command `/chc mute` is mentioned in settings.yml (as a comment, line 545) while it doesn't actually exist (it returns "Invalid argument", it isn't a suggested command and it does not appear in /chc help).

**Comment by Qw4rtz** [comment]
Also, using the mute button in /ch list uses /mute, no matter if the command was changed in settings.yml, maybe it could use this /chc mute instead, if implemented?

**Comment by kangarko** [comment]
Thanks, it was changed to just "/mute".
