### ISSUE TITLE
1.16.5: Disable death messages

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#742]
Hi, I want to know how I would disable the death messages which the plugin sends so then I have complete vanilla, I know about putting it to original in death.rs but want to completely disable it.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Hi, I want to know how I would disable the death messages which the plugin sends so then I have complete vanilla, I know about putting it to original in death.rs but want to completely disable it.
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
To do so, simply go in `/plugins/ChatControlRed/settings.yml`, search for the `Messages:` part, then `Apply_On:`, and remove `- 'death'` from there.
This is how it looks like in your file:
```
Messages:
 
  # What aspects of messages should be enabled?
  # Options: join, quit, kick, death, timed
  #
  # If you have another plugin handling join/quit etc. messages, remove them from list below.
  # If you want to hide those messages, leave them in Apply_On and empty your messages/ .rs files.
  Apply_On:
  - 'join'
  - 'quit'
  - 'kick'
  - 'death'
  - 'timed'
```
