### ISSUE TITLE
Messages for Sleep

### ISSUE THREAD

**Issue by itsBeaco** [kangarko/ChatControl#743]
**Hey, I'm making the suggestion as you already have a these types of things in game so I'm hoping it wouldn't be too much extra work to add this as well, fingers crossed, but I'm no coder. Just like the custom death, joins, kick, quit and times message, could you please add one for when players sleep? for example "[name] is counting sheep"** 

1. Would be a fun addition to the game, the same way we have custom messages for death, join, kick and more
2. Would either have to look for a plugin to do this or leave it, would be a nice feature that could benefit you as well as other server owners

**Comment by ElBananaa** [comment]
> **Hey, I'm making the suggestion as you already have a these types of things in game so I'm hoping it wouldn't be too much extra work to add this as well, fingers crossed, but I'm no coder. Just like the custom death, joins, kick, quit and times message, could you please add one for when players sleep? for example "[name] is counting sheep"**
> 
> 1. Would be a fun addition to the game, the same way we have custom messages for death, join, kick and more
> 2. Would either have to look for a plugin to do this or leave it, would be a nice feature that could benefit you as well as other server owners

Hey!
I think you can use the rules packet system to replace the actual sleeping message with a custom one. I'm not a hundred percent sure about that, but give it a try.

So in your `rules/packet.rs`, do something like:
```
# Rewrite sleeping message
match ^{player} is now sleeping
then rewrite {player} is counting sheeps
```

**Comment by itsBeaco** [comment]
Oh thank you for that, I'll give that a try. By any chance do you know if that would let me do multiple options? Appreciate your help!

**Comment by ElBananaa** [comment]
> Oh thank you for that, I'll give that a try. By any chance do you know if that would let me do multiple options? Appreciate your help!

I don't know if you can show multiple (random or not) messages tho. Anyways, keep in mind that this is probably a temporary solution. Kangarko will let you know if he wants to implement this feature into the plugin, or not.

**Comment by kangarko** [comment]
You can use 

then rewrite ONE
then rewrite TWO

or then rewrite ONE|TWO

and the plugin will pick one from the two options randomly :)
