### ISSUE TITLE
1.16.5: /list

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#745]
I have a bungee network and when I do /list on my survival and skyblock it will list the whole network but not on my hub, it just shows players on the hub and not the others,
though if I do the command a few times it will work and then stop again

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> I have a bungee network and when I do /list on my survival and skyblock it will list the whole network but not on my hub, it just shows players on the hub and not the others,
> though if I do the command a few times it will work and then stop again
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
This is a weird behavior. Just in case, could you give us more informations about your environment? I don't know if this is necessary, but I guess it could be somehow helpful for Kangarko.

**Comment by kangarko** [comment]
Cannot reproduce, please return to this and provide steps to reproduce this problem along with your debug log from "hub" server and "survival" so I can try reproducing.
