### ISSUE TITLE
1.16.5: {killer_item} placeholder nonexistent?

### ISSUE THREAD

**Issue by cades66** [kangarko/ChatControl#748]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I'm using the default death.rs but it appears your placeholder for {killer_item} is fully broken on default. Is there a PAPI placeholder I need, or something else? There are no errors, it just looks like the placeholder doesn't work.
![javaw_NaIzl5WuA3](https://user-images.githubusercontent.com/57970060/109405820-042c2c80-793a-11eb-95f7-1677bd20a288.png)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, I'm using the default death.rs but it appears your placeholder for {killer_item} is fully broken on default. Is there a PAPI placeholder I need, or something else? There are no errors, it just looks like the placeholder doesn't work.
> ![javaw_NaIzl5WuA3](https://user-images.githubusercontent.com/57970060/109405820-042c2c80-793a-11eb-95f7-1677bd20a288.png)

Hey!
Try replace it with `[killer_item]`. Let me know if it fixes the issue.

**Comment by cades66** [comment]
It worked! Thanks so much - I'd recommend forcing the plugin to update these / change the auto-gen'd files to fix this or at least make a post about it, other than that, thanks!
