### ISSUE TITLE
Require/ignore newcomer conditions for messages

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#749]
1. It would make it extremely simple to configure first join messages, as well as death messages that could suggest to the community that a newcomer needs help

2. It's certainly not high priority but would add an interesting dynamic to messages. I'm mostly just concerned about first join messages though, that's definitely something I'd like to have working some day. Maybe a seperate first-join.rs?

_I would also like to suggest, without opening another ticket, the ability to change a players name color with a simple command, such as /chc name color (player) (color)_

**Comment by ElBananaa** [comment]
> 1. It would make it extremely simple to configure first join messages, as well as death messages that could suggest to the community that a newcomer needs help
> 2. It's certainly not high priority but would add an interesting dynamic to messages. I'm mostly just concerned about first join messages though, that's definitely something I'd like to have working some day. Maybe a seperate first-join.rs?
> 
> _I would also like to suggest, without opening another ticket, the ability to change a players name color with a simple command, such as /chc name color (player) (color)_

Hey! Sending first joinessages is currently possible using conditions. Adding a join.rs would make it easier, but you can already do yhis without this file

**Comment by Squeej** [comment]
Oh awesome! Do you know what conditions I would use for first-joins and normal joins? I wasn't able to figure it out with any of the conditions listed on the wiki

**Comment by ElBananaa** [comment]
> Oh awesome! Do you know what conditions I would use for first-joins and normal joins? I wasn't able to figure it out with any of the conditions listed on the wiki

Hey!
In `messages/join.rs`, add this line, then edit the message with whatever you want.

`require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 30` means that the script will only execute if the player played for 5 ticks or less on your server (0.25 second).

Make sure to paste this part at the top of your file, so it doesn't get overwritten by other parts.

```yaml
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 5
message: 
- welcome-message
```

**Comment by Squeej** [comment]
Thank you for this!!
