### ISSUE TITLE
1.16.5: Messages sent from Discord do not have {channel}?

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#750]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Is it possible to get the {channel} for messages sent from Discord?

I have a channel_prefix variable I setup, but messages coming from Discord do not have the {channel} variable filled.  I'm trying to format messages from Discord to be exactly the same as messages in game.

My channel_prefix.yml:

```
Type: format
Key: channel_prefix
Value: |-
    channelPrefix();
    
    function channelPrefix() {
        var channel = '{channel}';
        
        if(channel === 'test1') {
            return '&7[&a1&7]&f';
        }
        else if(channel === 'test2') {
            return '&7[&e2&7]&f';
        }
        else if(channel === 'testa') {
            return '&c[M]&f';
        }
        else {
            return '';
        }
    }
```

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Is it possible to get the {channel} for messages sent from Discord?
> 
> I have a channel_prefix variable I setup, but messages coming from Discord do not have the {channel} variable filled. I'm trying to format messages from Discord to be exactly the same as messages in game.
> 
> My channel_prefix.yml:
> 
> ```
> Type: format
> Key: channel_prefix
> Value: |-
>     channelPrefix();
>     
>     function channelPrefix() {
>         var channel = '{channel}';
>         
>         if(channel === 'test1') {
>             return '&7[&a1&7]&f';
>         }
>         else if(channel === 'test2') {
>             return '&7[&e2&7]&f';
>         }
>         else if(channel === 'testa') {
>             return '&c[M]&f';
>         }
>         else {
>             return '';
>         }
>     }
> ```

Hey! I think your variable is wrong. Use '==' instead of '==='

**Comment by c0wg0d** [comment]
No, the JavaScript works on the Paper side, just not from Discord.

**Comment by ElBananaa** [comment]
> No, the JavaScript works on the Paper side, just not from Discord.

Oh, I just noticed there's no `{channel}` placeholder in the plugin. And I think the plugin can't get retrieve any informations from discord, but I'm not sure.

**Comment by kangarko** [comment]
{channel} should work but it is not gonna work in custom variables since they need a Player instance which is only working on Minecraft not from Discord.
