### ISSUE TITLE
1.16.5: Swearing problem

### ISSUE THREAD

**Issue by Toki-teki** [kangarko/ChatControl#752]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hello.
I have a rule with a configuration like this.

```yaml
# Blocks 'сука'
match \b(с+(\W|\d|_)*у+(\W|\d|_)*к+(\W|\d|_)*а+(\W|\d|_)*)
group swear

# Blocks 'slut'
match \b(s+(\W|\d|_)*l+(\W|\d|_)*u+(\W|\d|_)*t+(\W|\d|_)*)
group swear
```

"slut" good work.
but "сука"...
try to write this sentence: "я на сук залез и аметист."
![2021-02-28_21 53 28](https://user-images.githubusercontent.com/74260160/109429909-7e7ab080-7a0f-11eb-9d7d-61d8918c141b.png)

The plugin sees a match across the entire post
я на СУК залез и Аметист.

It will block most of the message, although it doesn't need to.

**Comment by ElBananaa** [comment]
Hey!
Replace your `сука` rule with:
```yaml
# Blocks 'сука'
match \b(с+(\W|\d|_)*у+(\W|\d|_)*к+(\W|\d|_)*а+(\W|\d|_))
group swear
```
It should fix the issue
