### ISSUE TITLE
Chat protection from PremiumVanish bypassed?

### ISSUE THREAD

**Issue by Westloch** [kangarko/ChatControl#753]
Minecraft Version: 1.16.2
MySQL: true
BungeeCord: true
chatcontrolred version:10.2.7

When using premium vanish, the message protection that premium vanish has is bypassed by chatcontrolred. 

Within the premium vanish config i set: 

```
# The priority for cancelling chat messages
AsyncPlayerChatEventPriority: HIGHEST
```

but still is bypassed by chatcontrolred, not sure if theres some sort of premium vanish comparability that im missing? 
I disabled chatcontrolred and premium vanish worked as normal

https://user-images.githubusercontent.com/62856212/109436098-773dad80-79e3-11eb-855d-2ef179855a9e.mp4

**Comment by ElBananaa** [comment]
Hey. I'm using both plugins on my server and I don't have a such issue. The formatter priority is set to HIGH, try with it.
So basically, set `AsyncPlayerChatEventPriority` to `HIGH` in PremiumVanish config. Then set `Chat_Listener_Priority` to `HIGH` in chatcontrol-red config file.
