### ISSUE TITLE
Server-name displays "A Minecraft Server"

### ISSUE THREAD

**Issue by Westloch** [kangarko/ChatControl#754]
Minecraft Version: 1.16.2
MySQL: true
BungeeCord: true
ChatControlRed version: 10.2.7

Using the placeholder {server_name}, In-game it displays "A minecraft server" instead of the actual server name

Inside server.properties i set the same server name used in the proxy config.yml

i also tried downloading and using papi %server_name% and it returned the same "A minecraft server"

not sure if its a bug or could i be doing something wrong?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.2
> MySQL: true
> BungeeCord: true
> ChatControlRed version: 10.2.7
> 
> Using the placeholder {server_name}, In-game it displays "A minecraft server" instead of the actual server name
> 
> Inside server.properties i set the same server name used in the proxy config.yml
> 
> i also tried downloading and using papi %server_name% and it returned the same "A minecraft server"
> 
> not sure if its a bug or could i be doing something wrong?

Hey!
I just tried it, and yeah, I can confirm, for some reasons, this doesn't parse the right value. It's probably a mistake from Kangarko.
I'll leave this open so he could take a look at it and fix it in the next update.

**Comment by kangarko** [comment]
Let's continue on the other ticket. For me it works using BungeeCord: https://i.imgur.com/HAg9vrM.png so let's investigate

**Comment by Squeej** [comment]
I had this problem too, you can totally use papi's %server_name% placeholder however you need to edit the server name in papi's configuration file because that's where it pulls the placeholder from, not your server.properties
