### ISSUE TITLE
How to mute chat while still allowing advanced ban to use /mute?

### ISSUE THREAD

**Issue by Westloch** [kangarko/ChatControl#755]
Minecraft Version: 1.16.2
MySQL: true
BungeeCord: true
ChatControlRed version: 10.2.7

anyway to use the **/mute channel** function, while still allowing advanced ban to use **/mute**? Currently i do /mute and its being used by advancedban, unless theres another command to mute chat that im missing?

**Comment by TheIntolerant** [comment]
In ``ChatControlRed > Rules > commands.rs`` add the following

```
# Makes "/mute channel" run via chatcontrol
match ^\/(mute(?::mute)? channel)(?: )?(.*)?
then command mute:mute channel $2
dont verbose
then deny


# Makes "/mute player" run as /mute via advanced ban
# to prevent users getting muted via chatcontrol
match ^\/(mute(?::mute)? player)(?: )?(.*)?
then command advancedban:mute $2
dont verbose
then deny


# Makes "/mute" run via advanced ban plugin
match ^\/(mute(?::mute)?)(?: )?(.*)?
then command advancedban:mute $2
dont verbose
then deny
```

**NOTE**
This will also prevent the usage of ``/mute server`` if you still wanted to allow staff/yourself to use that command add the following instead

```
# Makes "/mute channel" run via chatcontrol
match ^\/(mute(?::mute)? channel)(?: )?(.*)?
then command mute:mute channel $2
dont verbose
then deny

# Makes "/mute server" run via chatcontrol
match ^\/(mute(?::mute)? server)(?: )?(.*)?
then command mute:mute server $2
dont verbose
then deny

# Makes "/mute player" run as /mute via advanced ban
# to prevent users getting muted via chatcontrol
match ^\/(mute(?::mute)? player)(?: )?(.*)?
then command advancedban:mute $2
dont verbose
then deny

# Makes "/mute" run via advanced ban plugin
match ^\/(mute(?::mute)?)(?: )?(.*)?
then command advancedban:mute $2
dont verbose
then deny
```

**Comment by TheIntolerant** [comment]
Also, make sure to add those rules listed how I have it because chatcontrol checks the rules from top to bottom.
So if you add
```
# Makes "/mute" run via advanced ban plugin
match ^\/(mute(?::mute)?)(?: )?(.*)?
then command advancedban:mute $2
dont verbose
then deny
```
at the top, ``/mute channel`` etc wouldn't work, that is why I have: 
``match ^\/(mute(?::mute)? channel)(?: )?(.*)?`` etc above,
this rule ``match ^\/(mute(?::mute)?)(?: )?(.*)?``

**Comment by kangarko** [comment]
Thanks to gone-incognito for the help!
