### ISSUE TITLE
/nick doesnt recognize color codes

### ISSUE THREAD

**Issue by Westloch** [kangarko/ChatControl#756]
Minecraft Version: 1.16.2
MySQL: true
BungeeCord: true
ChatControlRed version: 10.2.7

When using the /nick command provided in the **command.rs** file (to shorten the nick name command **/tag nick <nickname>**) it seems that color codes arent recognized.

When a player uses the command /nick <nickname> with color codes, the nickname is applied but the color codes are completely ignored

When a player does /tag nick <nickname> with color codes, the nickname is applied with the color codes as normal

Commands.rs:
```
# -----------------------------------------------------------------------------------------------
# Create a /nick command that executes a longer /tag nick command.
# -----------------------------------------------------------------------------------------------

# Create a simple alias for /tag nick to just type /nick instead, using two rules.
# This rule only sends the usage message, and the rule below actually forwards the command.
match ^\/nick$
require perm chatcontrol.custom.nick &cInsufficient permission ({permission}).
then warn &cDescription: Sets your own nickname.
then warn &cUsage: /nick <nick>
then deny

# An example used for /nick command alias with the help of group matching (see the $2), it will
# replace what players type in /nick - that is pulled from the (.*) part
match ^\/nick (.*)
require perm chatcontrol.custom.nick &cInsufficient permission ({permission}).
then command tag nick $1
then deny
```

![Screenshot___02-28-2021___361 724088 994](https://user-images.githubusercontent.com/62856212/109455466-4d54ad00-7a1c-11eb-9c10-4c6abe0c9b6d.png)

![Screenshot___02-28-2021___362 147577 425](https://user-images.githubusercontent.com/62856212/109455469-4fb70700-7a1c-11eb-91dd-ee45fd77ebbb.png)

**Comment by TheIntolerant** [comment]
This isn't a bug due to ``Strip_Colors: true``, under ``Rules:`` in your ``settings.yml`` file
As shown here [Rules section of settings.yml](https://pastebin.com/V8BbdN4g)

So due to ``Strip_Colors: true`` when you make a custsom command (such as /nick) via a chatcontrol rule, it will remove the color codes, while you can change this to  ``Strip_Colors: false`` this to stop that from happening, I strongly suggest you make an alias in ``commands.yml`` instead, so you do not need to worry about people using color codes to bypass rules you create such as swear words etc.

To do this, open up ``commands.yml`` and add the following:
```
command-block-overrides: []
ignore-vanilla-permissions: false
aliases:
  nick:
  - "tag nick $1-"
```
If you have this
```
aliases:
  icanhasbukkit:
  - "version $1-"
```
 and you want to keep that :P just add it underneath, so it looks something like this:
```
command-block-overrides: []
ignore-vanilla-permissions: false
aliases:
  icanhasbukkit:
  - "version $1-"
  nick:
  - "tag nick $1-"
```

**Comment by TheIntolerant** [comment]
Also if you do decide to create an alias via ``commands.yml``. Make sure to change the nick part of your ``commands.rs`` file. So chatcontrol does not override ``/nick``

You can keep this part
```
# Create a simple alias for /tag nick to just type /nick instead, using two rules.
# This rule only sends the usage message, and the rule below actually forwards the command.
match ^\/nick$
require perm chatcontrol.custom.nick &cInsufficient permission ({permission}).
then warn &cDescription: Sets your own nickname.
then warn &cUsage: /nick <nick>
then deny
```
However, for this part, you should either add a hashtag to the front of each line or completely remove this section.
```
# An example used for /nick command alias with the help of group matching (see the $2), it will
# replace what players type in /nick - that is pulled from the (.*) part
match ^\/nick (.*)
require perm chatcontrol.custom.nick &cInsufficient permission ({permission}).
then command tag nick $1
then deny
```

**Comment by ElBananaa** [comment]
Hey!
Thanks @gone-incognito for answering!
As stated above, you can use both methods to fix your problem.

I'm closing this issue, but feel free to open a new one if you need anything else.
