### ISSUE TITLE
Paper1.16.5: If I can translate the [item] item name?

### ISSUE THREAD

**Issue by MusicTW** [kangarko/ChatControl#757]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false
![image](https://user-images.githubusercontent.com/52475422/109456498-effc4280-7a93-11eb-867b-2db14aede74a.png)
Like translate "air" to  Chinese "空氣"

**Comment by ElBananaa** [comment]
Hey!
Replace your item variable with this, then replace `Name given to the air` with whatever you want.
```yaml
Type: message

Key: item

Value: |-
    displayName();
    
    function displayName() {
      var item = player.getItemInHand();
      var textColor = '#42f595';
    
      var air = Java.type("org.bukkit.Material").AIR;
       
      if (item.getType() == air) {
        return textColor + "Name given to the air";
      }
    
      var metadata = item.getItemMeta();
      
      if (metadata != null && metadata.hasDisplayName())
        return textColor + metadata.getDisplayName();
    
      var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
      var name = item.getType().name().toLowerCase().replace('_', ' ').replace('_', ' ');
    
      return textColor + wordUtils.capitalize(name);
    }

Sender_Condition: ''

Sender_Permission: ''

Receiver_Condition: ''

Receiver_Permission: ''

Hover: []

Hover_Item: player.getInventory().getItemInMainHand()

Open_Url: ''

Suggest_Command: ''

Run_Command: ''
```

**Comment by MusicTW** [comment]
So, if i want to translate all items to Chinese, I need to type this again and again?

**Comment by ElBananaa** [comment]
> So, if i want to translate all items to Chinese, I need to type this again and again?

Well, yes. As far as I know, this is the only way to do so. This is a limitation of the game, so Kangarko can't really change anything about it. He could also use packets to get your client language then translate the item names based on it, but it seems pretty difficult for something like that, which is almost useless tbho.
