### ISSUE TITLE
AsyncPlayerChatEvent bug

### ISSUE THREAD

**Issue by Kamo452** [kangarko/ChatControl#758]
All chat messages are delivered very slowly

[Mon, 1. Mar 2021 11:35:56 CET INFO] [ChatControlRed 10.2.7] ChatListener listening to AsyncPlayerChatEvent at HIGHEST priority took 766.77 ms

TPS on server is good (20.0)

**Comment by ElBananaa** [comment]
Hey. Please update your issue to match the bug-report format. Also provide us your chc debug file.

**Comment by kangarko** [comment]
If this is happening only the first time or after reloading, it's fine.

If it's happening frequently check your variables and rules. Simplest way to do so is renaming rules/ folder so the plugin will generate a new one with a clean setup. If the problem goes away you know you have either too many rules or regexes taking way long, in which case you need to use regex101.com with unicode and insensitive flags on to solve this on your own.

Or simply remove all variables from the chat format being used to see if any of those causes the delay.

**Comment by kangarko** [comment]
Also if other plugins have the same issues it may be poor hardware or other server setup issue on your end.
