### ISSUE TITLE
1.16.5: Message shows key and UUID

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#759]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

I think the image says enough, it's being shown on /t off

![image](https://user-images.githubusercontent.com/5664135/109514879-c4cf1e80-7aa6-11eb-8786-c733b0b21506.png)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> I think the image says enough, it's being shown on /t off
> 
> ![image](https://user-images.githubusercontent.com/5664135/109514879-c4cf1e80-7aa6-11eb-8786-c733b0b21506.png)

Hey!
Thanks for reporting this bug. I tried on my server, and I can confirm, I have the same issue when using `/t <player>` then `/t off`.
I'll leave this open so Kangarko could take a look at it and probably fix it in the next update. :)

**Comment by kangarko** [comment]
Thanks, will get patched
