### ISSUE TITLE
People can swear if they use CAPS

### ISSUE THREAD

**Issue by zigaliro** [kangarko/ChatControl#76]
Hey!
When players don`t use caps, when they swear it works normally the chat doesn`t appear. But when they use CAPS they can swear without  ******** appearing. 

Example: When they say "fuck you" it normaly does "**** you" but when they say "FUCK YOU" it does "FUCK YOU" the *****  doesn`t appear.

**Comment by kangarko** [comment]
A fix is planning with a high priority. 
Sorry for the inconveniences.

**Comment by kangarko** [comment]
Fixed, just forgot to close the ticket.
