### ISSUE TITLE
Hexcode permission for nicknames

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#76]
Hey, you recently added a permission to allow for only specific hexcodes within the chat and /chc color. But I'd like to do the same with the nickname system, so they can only use the hexcodes that we officially use in our ranks rather then them being able to use ANY hexcode. This was my original suggestion a few months ago ^^

**Comment by kangarko** [comment]
That i working already, see what permissions you need to give below.. Apology for changes. Only those colors, for which player has permissions for, will be allowed to be used in nicks.

<img width="1101" alt="Screenshot 2020-11-16 at 15 28 08" src="https://user-images.githubusercontent.com/1918426/99264113-5aa8ab80-2820-11eb-8dfb-a59874e66d00.png">

**Comment by kangarko** [comment]
If it doesn't work, use the next release :)

**Comment by Sikatsu** [comment]
Awesome! And then I can only allow it in nicknames and not within chc color or chat I hope?

**Comment by Qw4rtz** [comment]
> Awesome! And then I can only allow it in nicknames and not within chc color or chat I hope?

Maybe there could be permissions like `chatcontrol.hexcolor.cc4455.channel.{channel}` and `chatcontrol.hexcolor.cc4455.tag.{type}` ? Kind of interested tbh 😁

**Comment by kangarko** [comment]
Hmm that would be overkill for now, let's keep things simple especially during beta.

But I added this (coming in 10.0.6):

<img width="773" alt="Screenshot 2020-11-16 at 17 56 36" src="https://user-images.githubusercontent.com/1918426/99283287-17a50300-2835-11eb-8bb7-4cb93fe48254.png">

**Comment by Sikatsu** [comment]
That somewhat works, but if I wanted to allow one specific rank to use a hexcode in /chc color and nicknames and all the other ranks just in nicknames that would still be limited.

I could force a hexcode chat color using permissions I think like I do now as a workaround?

**Comment by kangarko** [comment]
Yes you can just wait for the next version, remove all from that list except for "nicks" and give you rank those color perms you need.
