### ISSUE TITLE
1.16.5: TownyChats implementation

### ISSUE THREAD

**Issue by Larsthesheep** [kangarko/ChatControl#760]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hello team - over the last few days I've been trying to get ChatControlRed to work with Towny. During this I've had some strange issues and I'm at the end of my knowledge and energy trying to get it to work. I've tried a multitude of approaches which I'll list down below but beware that those might be very long.

One of the source questions I have is as follows: Do you require TownyChat.jar or not. Without this it seems like the permissions don't get registered well in a manner that blocks people from using these chats when they're not in a town or nation.

<details>
  <summary>Lossy channels for Nation and Town</summary>

  ```
    general:
      Format: chat
      Format_Spy: '@noprefix chat'
      Discord: true
    ranged:
      Format: '&6[ranged] &7{pl_prefix+}{player}:{pl_suffix} {message}'
      Range: 100
      Bungee: false
    towny:
      Format: towny-chat
      Party: towny-town
    nation:
      Format: nation-chat
      Party: towny-nation
  ```
These are the formats:
<details>
  <summary>towny-chat</summary>

  ```Parts:
    spies-prefix:
      Message: '&8[&5TC Spy&8] &f'
      Receiver_Condition: '{player_is_spying_{channel}}'
      Hover: '&dClick to stop spying {channel} channel.'
      Run_Command: /{label_spy} toggle chat {channel}
    prefix:
      Message: '[TC]{townyadvanced_nation_tag}{townyadvanced_town_tag} '
      Sender_Condition: '{sender_is_player}'
    player-name:
      Message: '{player_nick}'
      Hover: '&7Click to message.'
      Suggest_Command: '/tell {player_name} '
    message:
      Message: '&f: {player_suffix}{message}'
```
</details>
<details>
  <summary>nation-chat</summary>

  ```Parts:
  spies-prefix:
    Message: '&8[&5NC Spy&8] &f'
    Receiver_Condition: '{player_is_spying_{channel}}'
    Hover: '&dClick to stop spying {channel} channel.'
    Run_Command: /{label_spy} toggle chat {channel}
  prefix:
    Message: '[NC]{townyadvanced_nation_tag}{townyadvanced_town_tag} '
    Sender_Condition: '{sender_is_player}'
  player-name:
    Message: '{player_nick}'
    Hover: '&7Click to message.'
    Suggest_Command: '/tell {player_name} '
  message:
    Message: '&f: {player_suffix}{message}'
```
</details>

In addition to these channels I added the following rules in global.rs:
```
match ^(/tc) (.*)
dont verbose
then command channel send towny $2
then deny
```
```
match ^(/nc) (.*)
dont verbose
then command channel send nation $2
then deny
```
</details>

This setup somewhat worked but had permission errors with TownyAdvanced with players being able to use chat without being in a town and such. To create a way to check if a player was actually in a town I tried to create the following variable:
```
Type: FORMAT
Key: player_has_town
Value: |-
    getTagOrPrefix();
    
    function getTagOrPrefix() { 
        var town = "{townyadvanced_town}";
        if(town == "")
          return false;
        else 
          return true;  
    }
Sender_Condition: ''
Sender_Permission: ''
Receiver_Condition: ''
Receiver_Permission: ''
```

Testing these using the provided commands returned true and false at the right moments (when in a town and when not). But while using this in practice the following error pops up when using these as a `require script {player_has_town}` in the rule giving in example one (attached as error.log).
[error.log](https://github.com/kangarko/ChatControl-Red/files/6062821/error.log)

At this point I have no clue on how to properly support Towny in my chat anymore, could anyone please point me to the right direction?

Lars

**Comment by Larsthesheep** [comment]
To clarify my ideal situation would be as follows:
- One general chat
- One local chat (range of 100 or so)
- /tc and /nc to talk in Town or Nation chat respectively that's only accessible when you're in a town or/and nation.

If possible I only need the fix to the javascript variable that's crashing it. With that variable all issues that were created got fixed.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Hello team - over the last few days I've been trying to get ChatControlRed to work with Towny. During this I've had some strange issues and I'm at the end of my knowledge and energy trying to get it to work. I've tried a multitude of approaches which I'll list down below but beware that those might be very long.
> 
> One of the source questions I have is as follows: Do you require TownyChat.jar or not. Without this it seems like the permissions don't get registered well in a manner that blocks people from using these chats when they're not in a town or nation.
> 
> Lossy channels for Nation and Town
> This setup somewhat worked but had permission errors with TownyAdvanced with players being able to use chat without being in a town and such. To create a way to check if a player was actually in a town I tried to create the following variable:
> 
> ```
> Type: FORMAT
> Key: player_has_town
> Value: |-
>     getTagOrPrefix();
>     
>     function getTagOrPrefix() { 
>         var town = "{townyadvanced_town}";
>         if(town == "")
>           return false;
>         else 
>           return true;  
>     }
> Sender_Condition: ''
> Sender_Permission: ''
> Receiver_Condition: ''
> Receiver_Permission: ''
> ```
> 
> Testing these using the provided commands returned true and false at the right moments (when in a town and when not). But while using this in practice the following error pops up when using these as a `require script {player_has_town}` in the rule giving in example one (attached as error.log).
> [error.log](https://github.com/kangarko/ChatControl-Red/files/6062821/error.log)
> 
> At this point I have no clue on how to properly support Towny in my chat anymore, could anyone please point me to the right direction?
> 
> Lars

Hey! The issue you had is due to spigot chat formatting placing colors before the booleans.
To fix this, replace your script with this one:
```yaml
Type: FORMAT
Key: player_has_town
Value: |-
    getTagOrPrefix();
    
    function getTagOrPrefix() { 
        var town = "{townyadvanced_town}";
        if(town == "") {
          return "No";
        }
         return "Yes";  
    }
Sender_Condition: ''
Sender_Permission: ''
Receiver_Condition: ''
Receiver_Permission: ''
```
Then for your condition, use `require script {player_has_town} == "Yes"`

**Comment by Larsthesheep** [comment]
> 
> 
> > Minecraft Version: 1.16.5
> > MySQL: false
> > BungeeCord: false
> > Hello team - over the last few days I've been trying to get ChatControlRed to work with Towny. During this I've had some strange issues and I'm at the end of my knowledge and energy trying to get it to work. I've tried a multitude of approaches which I'll list down below but beware that those might be very long.
> > One of the source questions I have is as follows: Do you require TownyChat.jar or not. Without this it seems like the permissions don't get registered well in a manner that blocks people from using these chats when they're not in a town or nation.
> > Lossy channels for Nation and Town
> > This setup somewhat worked but had permission errors with TownyAdvanced with players being able to use chat without being in a town and such. To create a way to check if a player was actually in a town I tried to create the following variable:
> > ```
> > Type: FORMAT
> > Key: player_has_town
> > Value: |-
> >     getTagOrPrefix();
> >     
> >     function getTagOrPrefix() { 
> >         var town = "{townyadvanced_town}";
> >         if(town == "")
> >           return false;
> >         else 
> >           return true;  
> >     }
> > Sender_Condition: ''
> > Sender_Permission: ''
> > Receiver_Condition: ''
> > Receiver_Permission: ''
> > ```
> > 
> > 
> > Testing these using the provided commands returned true and false at the right moments (when in a town and when not). But while using this in practice the following error pops up when using these as a `require script {player_has_town}` in the rule giving in example one (attached as error.log).
> > [error.log](https://github.com/kangarko/ChatControl-Red/files/6062821/error.log)
> > At this point I have no clue on how to properly support Towny in my chat anymore, could anyone please point me to the right direction?
> > Lars
> 
> Hey! The issue you had is due to spigot chat formatting placing colors before the booleans.
> To fix this, replace your script with this one:
> 
> ```yaml
> Type: FORMAT
> Key: player_has_town
> Value: |-
>     getTagOrPrefix();
>     
>     function getTagOrPrefix() { 
>         var town = "{townyadvanced_town}";
>         if(town == "") {
>           return "No";
>         }
>          return "Yes";  
>     }
> Sender_Condition: ''
> Sender_Permission: ''
> Receiver_Condition: ''
> Receiver_Permission: ''
> ```
> 
> Then for your condition, use `require script {player_has_town} == "Yes"`

Thanks for the response, I've tried this and the following error occurred:
```
[19:20:43 INFO]: [ChatControlRed] !-----------------------------------------------------!
[19:20:43 INFO]: [ChatControlRed]  Error parsing rule: Rule {
[19:20:43 INFO]: [ChatControlRed]       'Player Commands' = '[channel send towny $2]'
[19:20:43 INFO]: [ChatControlRed]       'Cancel Message' = 'true'
[19:20:43 INFO]: [ChatControlRed]       'Ignore Verbose' = 'true'
[19:20:43 INFO]: [ChatControlRed]       'Require Script' = '{player_has_town} == "Yes"'
[19:20:43 INFO]: [ChatControlRed]       'Type' = 'global'
[19:20:43 INFO]: [ChatControlRed]       'Match' = '^(/tc) (.*)'
[19:20:43 INFO]: [ChatControlRed] }
[19:20:43 INFO]: [ChatControlRed] !-----------------------------------------------------!
[19:20:43 INFO]: [ChatControlRed] ChatControlRed 10.2.7 encountered a ParserException! Please check your error.log and report this issue with the information in that file.
[19:20:43 INFO]: [ChatControlRed] ChatControlRed 10.2.7 encountered a ParserException! Please check your error.log and report this issue with the information in that file.
[19:20:43 INFO]: jdk.nashorn.internal.runtime.ParserException: <eval>:1:0 Expected an operand but found error
[19:20:43 INFO]: Yes == "Yes"
[19:20:43 INFO]: ^
[19:20:43 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:132)
[19:20:43 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:88)
[19:20:43 INFO]: at org.mineacademy.chatcontrol.operator.RuleOperator$RuleOperatorCheck.canFilter(RuleOperator.java:348)
[19:20:43 INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.canFilter(Rule.java:311)
[19:20:43 INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:245)
[19:20:43 INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:162)
[19:20:43 INFO]: at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:675)
[19:20:43 INFO]: at org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:154)
[19:20:43 INFO]: at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:284)
[19:20:43 INFO]: at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:109)
[19:20:43 INFO]: at org.mineacademy.chatcontrol.model.Checker.filterCommand(Checker.java:123)
[19:20:43 INFO]: at org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:59)
[19:20:43 INFO]: at org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:23)
[19:20:43 INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
[19:20:43 INFO]: [ChatControlRed] !-----------------------------------------------------!
[19:20:43 INFO]: [ChatControlRed]  Unhandled exception listening to PlayerCommandPreprocessEvent
[19:20:43 INFO]: [ChatControlRed] !-----------------------------------------------------!
```

This is what the error.log states:
```
------------------------------------[ 01.03.2021 19:20:43 ]-----------------------------------
ChatControlRed 10.2.7 encountered a ParserException
Running Paper 1.16.5-R0.1-SNAPSHOT and Java 11.0.9.1
Plugins: custom-ore-generator v2020.11.13, PlaceholderAPI v2.10.9, Playtimes v1.3.10, SilkySpawnies v1.0, ConditionalTextPlaceholders v1.3.6, ViaVersion v3.2.1, ViaBackwards v3.2.0, ChatColor v1.3, LuckPerms v5.2.115, Scoreboard-revision vR3 1.4.2 RELEASE, ProtocolLib v4.6.0, DamageIndicator v1.1.4, Vault v1.7.3-b131, MyCommand v5.6.9, dynmap v3.1-beta7-449, WorldEdit v7.2.3+5680-135941e, Essentials v2.18.2.0, CommandPanels v3.15.2.4, HolographicDisplays v2.4.6, Multiverse-Core v4.2.2-b812, AsyncWorldEdit v3.8.2, TAB v2.8.10, PlayerVaults v4.1.16, Prism v2.1.7-6, EssentialsSpawn v2.18.2.0, WorldBorder v2.1.0, WorldGuard v7.0.4+f7ff984, Citizens v2.0.27-SNAPSHOT (build 2269), MythicMobs v4.11.0-BETA-79e173ec, Quests v2.14.1, GSit v[4.9.0.1], mcMMO v2.1.174, SuperVanish v6.2.0, WorldGuardExtraFlags v4.1.5-SNAPSHOT, MarriageMaster v2.2.13-Release, Towny v0.96.7.0, IllegalStack v2.2.2a, CrateReloaded 2.0.23 by dinosaur, CitizensCMD v2.5.1, DiscordSRV v1.21.3, Dynmap-Towny v0.84, BetterRTP v3.0.5, ChatControlRed v10.2.7, Rankup v3.11.3, TheNewEconomy v0.1.1.12
----------------------------------------------------------------------------------------------

More Information: 
Unhandled exception listening to PlayerCommandPreprocessEvent
ParserException <eval>:1:0 Expected an operand but found error
§f§fYes == "Yes"
^
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:297)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:282)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.unaryExpression(Parser.java:4462)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expression(Parser.java:4620)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.conditionalExpression(Parser.java:4772)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.assignmentExpression(Parser.java:4711)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expression(Parser.java:4589)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expression(Parser.java:4585)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1854)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.statement(Parser.java:1155)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:909)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.program(Parser.java:844)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:325)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:285)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compile(Context.java:1500)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1467)
	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:750)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:542)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:531)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	 at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	 at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:132)
	 at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:88)
	 at org.mineacademy.chatcontrol.operator.RuleOperator$RuleOperatorCheck.canFilter(RuleOperator.java:348)
	 at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.canFilter(Rule.java:311)
	 at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:245)
	 at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:162)
	 at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:675)
	 at org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:154)
	 at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:284)
	 at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:109)
	 at org.mineacademy.chatcontrol.model.Checker.filterCommand(Checker.java:123)
	 at org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:59)
	 at org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:23)
	 at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
----------------------------------------------------------------------------------------------
```

Seems like Spigot is still adding colour formatting, is there any alternative?

**Update:**
I've made a temporary fix using the ConditionalTextPlaceholders plugin as such:
```
town-in:
  placeholder: '%towny_town%'
  rules:
    - "empty;false"
    - "!empty;true"
    
nation-in:
  placeholder: '%towny_nation%'
  rules:
    - "empty;false"
    - "!empty;true"
```

Using `require script {custom_town-in}` actually works this way.

I hope there's an actual plugin-based solution for this as this is a bit of a hacky way of having it setup.

**Comment by ElBananaa** [comment]
> > > Minecraft Version: 1.16.5
> > > MySQL: false
> > > BungeeCord: false
> > > Hello team - over the last few days I've been trying to get ChatControlRed to work with Towny. During this I've had some strange issues and I'm at the end of my knowledge and energy trying to get it to work. I've tried a multitude of approaches which I'll list down below but beware that those might be very long.
> > > One of the source questions I have is as follows: Do you require TownyChat.jar or not. Without this it seems like the permissions don't get registered well in a manner that blocks people from using these chats when they're not in a town or nation.
> > > Lossy channels for Nation and Town
> > > This setup somewhat worked but had permission errors with TownyAdvanced with players being able to use chat without being in a town and such. To create a way to check if a player was actually in a town I tried to create the following variable:
> > > ```
> > > Type: FORMAT
> > > Key: player_has_town
> > > Value: |-
> > >     getTagOrPrefix();
> > >     
> > >     function getTagOrPrefix() { 
> > >         var town = "{townyadvanced_town}";
> > >         if(town == "")
> > >           return false;
> > >         else 
> > >           return true;  
> > >     }
> > > Sender_Condition: ''
> > > Sender_Permission: ''
> > > Receiver_Condition: ''
> > > Receiver_Permission: ''
> > > ```
> > > 
> > > 
> > > Testing these using the provided commands returned true and false at the right moments (when in a town and when not). But while using this in practice the following error pops up when using these as a `require script {player_has_town}` in the rule giving in example one (attached as error.log).
> > > [error.log](https://github.com/kangarko/ChatControl-Red/files/6062821/error.log)
> > > At this point I have no clue on how to properly support Towny in my chat anymore, could anyone please point me to the right direction?
> > > Lars
> > 
> > 
> > Hey! The issue you had is due to spigot chat formatting placing colors before the booleans.
> > To fix this, replace your script with this one:
> > ```yaml
> > Type: FORMAT
> > Key: player_has_town
> > Value: |-
> >     getTagOrPrefix();
> >     
> >     function getTagOrPrefix() { 
> >         var town = "{townyadvanced_town}";
> >         if(town == "") {
> >           return "No";
> >         }
> >          return "Yes";  
> >     }
> > Sender_Condition: ''
> > Sender_Permission: ''
> > Receiver_Condition: ''
> > Receiver_Permission: ''
> > ```
> > 
> > 
> > Then for your condition, use `require script {player_has_town} == "Yes"`
> 
> Thanks for the response, I've tried this and the following error occurred:
> 
> ```
> [19:20:43 INFO]: [ChatControlRed] !-----------------------------------------------------!
> [19:20:43 INFO]: [ChatControlRed]  Error parsing rule: Rule {
> [19:20:43 INFO]: [ChatControlRed]       'Player Commands' = '[channel send towny $2]'
> [19:20:43 INFO]: [ChatControlRed]       'Cancel Message' = 'true'
> [19:20:43 INFO]: [ChatControlRed]       'Ignore Verbose' = 'true'
> [19:20:43 INFO]: [ChatControlRed]       'Require Script' = '{player_has_town} == "Yes"'
> [19:20:43 INFO]: [ChatControlRed]       'Type' = 'global'
> [19:20:43 INFO]: [ChatControlRed]       'Match' = '^(/tc) (.*)'
> [19:20:43 INFO]: [ChatControlRed] }
> [19:20:43 INFO]: [ChatControlRed] !-----------------------------------------------------!
> [19:20:43 INFO]: [ChatControlRed] ChatControlRed 10.2.7 encountered a ParserException! Please check your error.log and report this issue with the information in that file.
> [19:20:43 INFO]: [ChatControlRed] ChatControlRed 10.2.7 encountered a ParserException! Please check your error.log and report this issue with the information in that file.
> [19:20:43 INFO]: jdk.nashorn.internal.runtime.ParserException: <eval>:1:0 Expected an operand but found error
> [19:20:43 INFO]: Yes == "Yes"
> [19:20:43 INFO]: ^
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:132)
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:88)
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.operator.RuleOperator$RuleOperatorCheck.canFilter(RuleOperator.java:348)
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.canFilter(Rule.java:311)
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:245)
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:162)
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:675)
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:154)
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:284)
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:109)
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.model.Checker.filterCommand(Checker.java:123)
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:59)
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:23)
> [19:20:43 INFO]: at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
> [19:20:43 INFO]: [ChatControlRed] !-----------------------------------------------------!
> [19:20:43 INFO]: [ChatControlRed]  Unhandled exception listening to PlayerCommandPreprocessEvent
> [19:20:43 INFO]: [ChatControlRed] !-----------------------------------------------------!
> ```
> 
> This is what the error.log states:
> 
> ```
> ------------------------------------[ 01.03.2021 19:20:43 ]-----------------------------------
> ChatControlRed 10.2.7 encountered a ParserException
> Running Paper 1.16.5-R0.1-SNAPSHOT and Java 11.0.9.1
> Plugins: custom-ore-generator v2020.11.13, PlaceholderAPI v2.10.9, Playtimes v1.3.10, SilkySpawnies v1.0, ConditionalTextPlaceholders v1.3.6, ViaVersion v3.2.1, ViaBackwards v3.2.0, ChatColor v1.3, LuckPerms v5.2.115, Scoreboard-revision vR3 1.4.2 RELEASE, ProtocolLib v4.6.0, DamageIndicator v1.1.4, Vault v1.7.3-b131, MyCommand v5.6.9, dynmap v3.1-beta7-449, WorldEdit v7.2.3+5680-135941e, Essentials v2.18.2.0, CommandPanels v3.15.2.4, HolographicDisplays v2.4.6, Multiverse-Core v4.2.2-b812, AsyncWorldEdit v3.8.2, TAB v2.8.10, PlayerVaults v4.1.16, Prism v2.1.7-6, EssentialsSpawn v2.18.2.0, WorldBorder v2.1.0, WorldGuard v7.0.4+f7ff984, Citizens v2.0.27-SNAPSHOT (build 2269), MythicMobs v4.11.0-BETA-79e173ec, Quests v2.14.1, GSit v[4.9.0.1], mcMMO v2.1.174, SuperVanish v6.2.0, WorldGuardExtraFlags v4.1.5-SNAPSHOT, MarriageMaster v2.2.13-Release, Towny v0.96.7.0, IllegalStack v2.2.2a, CrateReloaded 2.0.23 by dinosaur, CitizensCMD v2.5.1, DiscordSRV v1.21.3, Dynmap-Towny v0.84, BetterRTP v3.0.5, ChatControlRed v10.2.7, Rankup v3.11.3, TheNewEconomy v0.1.1.12
> ----------------------------------------------------------------------------------------------
> 
> More Information: 
> Unhandled exception listening to PlayerCommandPreprocessEvent
> ParserException <eval>:1:0 Expected an operand but found error
> §f§fYes == "Yes"
> ^
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:297)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:282)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.unaryExpression(Parser.java:4462)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expression(Parser.java:4620)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.conditionalExpression(Parser.java:4772)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.assignmentExpression(Parser.java:4711)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expression(Parser.java:4589)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expression(Parser.java:4585)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1854)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.statement(Parser.java:1155)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:909)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.program(Parser.java:844)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:325)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:285)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compile(Context.java:1500)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1467)
> 	 at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:750)
> 	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:542)
> 	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:531)
> 	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
> 	 at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
> 	 at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
> 	 at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:132)
> 	 at org.mineacademy.chatcontrol.lib.model.JavaScriptExecutor.run(JavaScriptExecutor.java:88)
> 	 at org.mineacademy.chatcontrol.operator.RuleOperator$RuleOperatorCheck.canFilter(RuleOperator.java:348)
> 	 at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.canFilter(Rule.java:311)
> 	 at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:245)
> 	 at org.mineacademy.chatcontrol.operator.Rule$RuleCheck.filter(Rule.java:162)
> 	 at org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:675)
> 	 at org.mineacademy.chatcontrol.operator.Rule.filter(Rule.java:154)
> 	 at org.mineacademy.chatcontrol.model.Checker.filter(Checker.java:284)
> 	 at org.mineacademy.chatcontrol.model.Checker.<init>(Checker.java:109)
> 	 at org.mineacademy.chatcontrol.model.Checker.filterCommand(Checker.java:123)
> 	 at org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:59)
> 	 at org.mineacademy.chatcontrol.listener.CommandListener.execute(CommandListener.java:23)
> 	 at org.mineacademy.chatcontrol.lib.event.SimpleListener.execute(SimpleListener.java:89)
> 	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
> 	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> 	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
> ----------------------------------------------------------------------------------------------
> ```
> 
> Seems like Spigot is still adding colour formatting, is there any alternative?
> 
> **Update:**
> I've made a temporary fix using the ConditionalTextPlaceholders plugin as such:
> 
> ```
> town-in:
>   placeholder: '%towny_town%'
>   rules:
>     - "empty;false"
>     - "!empty;true"
>     
> nation-in:
>   placeholder: '%towny_nation%'
>   rules:
>     - "empty;false"
>     - "!empty;true"
> ```
> 
> Using `require script {custom_town-in}` actually works this way.
> 
> I hope there's an actual plugin-based solution for this as this is a bit of a hacky way of having it setup.

Alright, simply try with `{player_has_town} == Yes` then

**Comment by Larsthesheep** [comment]
That still gives the same error as the §f§f gets added to the variable.

**Comment by ElBananaa** [comment]
> That still gives the same error as the §f§f gets added to the variable.

Weird. Well, I don't have any other suggestion, sorry. I'll leave it open, Kangarko should be able to take a look at it tomorrow or wednesday. :)

**Comment by kangarko** [comment]
Thanks finally solved that issue by a workaround in Foundation.
