### ISSUE TITLE
1.16.5: Bug with deleting messages

### ISSUE THREAD

**Issue by Spaex** [kangarko/ChatControl#761]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

When I try to delete a Chat Message via the red X nothing happens InGame.
On the first click it only gets deleted on Discord (no Console Errors) und the second try to click the red X in front of the message it gives me the Console Error:
[18:47:07 INFO]: [ChatControlRed] TIP Alert: Could not remove Discord message in channel 'chat' id 816003560750710818, it was probably deleted otherwise or this is a bug.

But the Chat Message stays in the InGame Chat no matter how often I click on X. Also included the error.log

[error.log](https://github.com/kangarko/ChatControl-Red/files/6063443/error.log)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> When I try to delete a Chat Message via the red X nothing happens InGame.
> On the first click it only gets deleted on Discord (no Console Errors) und the second try to click the red X in front of the message it gives me the Console Error:
> [18:47:07 INFO]: [ChatControlRed] TIP Alert: Could not remove Discord message in channel 'chat' id 816003560750710818, it was probably deleted otherwise or this is a bug.
> 
> But the Chat Message stays in the InGame Chat no matter how often I click on X. Also included the error.log
> 
> [error.log](https://github.com/kangarko/ChatControl-Red/files/6063443/error.log)

Hey! This is a known issue with the latest versions of paper (since they included Adventure). Kangarko is aware of it. Just be patient, we'll let you know when this get fixed.

**Comment by kangarko** [comment]
Follow up on: https://github.com/dmulloy2/ProtocolLib/issues/1110
