### ISSUE TITLE
1.16.5: Any chat with a period give a help message

### ISSUE THREAD

**Issue by Magnum97** [kangarko/ChatControl#762]
Minecraft Version: ~~1.16.4 Paper Build 416~~ 1.16.5 Paper Build 416
MySQL: false
BungeeCord: true

When I send a message that has any . (period) in it, CHC tells me to use `/ch send` command. This happens with channels enabled and without. It happens both when I am OP and non-OP. 

My [debug.zip link](https://ufile.io/0pah158d)

![image](https://user-images.githubusercontent.com/39318657/109624556-3634be80-7af3-11eb-9a25-8767a8697d0f.png)

**Comment by ElBananaa** [comment]
> Minecraft Version: ~1.16.4 Paper Build 416~ 1.16.5 Paper Build 416
> MySQL: false
> BungeeCord: true
> 
> When I send a message that has any . (period) in it, CHC tells me to use `/ch send` command. This happens with channels enabled and without. It happens both when I am OP and non-OP.
> 
> My [debug.zip link](https://ufile.io/0pah158d)
> 
> ![image](https://user-images.githubusercontent.com/39318657/109624556-3634be80-7af3-11eb-9a25-8767a8697d0f.png)

Hey!
I don't have a a such issue with the latest version of the plugin using the default configuration on a complete fresh install.
Your version of the plugin is outdated, please make sure all your plugins are up-to-date, and same for your dependencies, then try again.

EDIT: It also looks like some of your rules are currently causing issues like the one you actually have:
```yaml
Expression: '[a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o)\b'
Evaluated message: '/rg bypass'
```

**Comment by Magnum97** [comment]
Hmm- I checked version and updated CHC before I did another test. I have done very little with the config but I will try a fresh install. 
> EDIT: It also looks like some of your rules are currently causing issues like the one you actually have:
Can you elaborate? I don't seem to have the worldguard rule you show - are you suggesting I add it? I checked global.rs and command.rs 
Thank you for the help.

**Comment by ElBananaa** [comment]
> Hmm- I checked version and updated CHC before I did another test. I have done very little with the config but I will try a fresh install.
> 
> > EDIT: It also looks like some of your rules are currently causing issues like the one you actually have:
> > Can you elaborate? I don't seem to have the worldguard rule you show - are you suggesting I add it? I checked global.rs and command.rs
> > Thank you for the help.

The rule I shown is in your error.log file. It matched the worldguard command due to the regex above.

**Comment by kangarko** [comment]
It's one of your rules as Banana pointed out, please go ahead and disable or edit it out :)
