### ISSUE TITLE
1.16.5: Commands are blocked

### ISSUE THREAD

**Issue by Magnum97** [kangarko/ChatControl#763]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Any luck perms command I issue with a period in it is blocked with a Channels disabled message making it very difficult to setup permissions. ^_^  I don't know if this is related to #762 but it since it deals with commands I made another issue.

My [debug.zip](https://ufile.io/0pah158d)

![image](https://user-images.githubusercontent.com/39318657/109625453-36818980-7af4-11eb-984f-fce50fc41fac.png)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Any luck perms command I issue with a period in it is blocked with a Channels disabled message making it very difficult to setup permissions. ^_^ I don't know if this is related to #762 but it since it deals with commands I made another issue.
> 
> My [debug.zip](https://ufile.io/0pah158d)
> 
> ![image](https://user-images.githubusercontent.com/39318657/109625453-36818980-7af4-11eb-984f-fce50fc41fac.png)

Hey!
Like your other ticket, I tried on a fresh install with the latest version, and I couldn't reproduce your issue. Please update your plugins and their dependencies, then try again.

**Comment by kangarko** [comment]
Use a clean setup and restart without reloading or PlugMan.
