### ISSUE TITLE
1.16.5:  Double chat

### ISSUE THREAD

**Issue by SSwanny** [kangarko/ChatControl#765]
Minecraft Version: 1..16.5
MySQL: false
BungeeCord: true (But not on the bungee server) 

Just did a restart and getting double chat. Looked through the configs and found nothing. Looked at past issues and none seem to relate to my issue. 
I do not have any other chat plugins in my server aside from Mcmmo
![image](https://user-images.githubusercontent.com/79940737/109710908-e215f280-7b63-11eb-9a55-025244ed0038.png)

if I do /ch s global {message} it doesnt duplicate

**Comment by ElBananaa** [comment]
> Minecraft Version: 1..16.5
> MySQL: false
> BungeeCord: true (But not on the bungee server)
> 
> Just did a restart and getting double chat. Looked through the configs and found nothing. Looked at past issues and none seem to relate to my issue.
> I do not have any other chat plugins in my server aside from Mcmmo
> ![image](https://user-images.githubusercontent.com/79940737/109710908-e215f280-7b63-11eb-9a55-025244ed0038.png)
> 
> if I do /ch s global {message} it doesnt duplicate

Hey! Please provide us your `/chc debug` file

**Comment by ghost** [comment]
This is happened to me after updating to Paper 507, a chat events for better Adventure support update. Downgrading the build version might fix the thing. Well IDK if it's related to that, but the double chat thing happened to my lobby server after I update my paper version.

**Comment by ghost** [comment]
Might be this issue which has been fixed in latest paper builds:
https://github.com/PaperMC/Paper/issues/5292

**Comment by SSwanny** [comment]
I just deleted everything and redid it all and fixed itself.
