### ISSUE TITLE
Chat from ranged channels is dumped to default bukkit chat if all other players leave range

### ISSUE THREAD

**Issue by snhnry** [kangarko/ChatControl#77]
Version: 6.7.5

Error log: http://pastebin.com/S4KLQ8g7

If a player is in a ranged channel and attempts to chat while no other players are in the defined range, the chat is sent straight to bukkit default chat. An error is also sent to console.  As soon as another player in the same channel re-enters the channel range, it resumes operating normally.

**Comment by kangarko** [comment]
My bad, fixed in the latest version!
