### ISSUE TITLE
1.16.5: How do I use the "parseother" placeholder from PlaceholderAPI with "require script"

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#770]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

Hey,
I wanted to block a command based on the returned value of [parseother placeholder](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#parseother)

here is a rule I was using to try and get it working, I would enter my own username in the command ``/test`` to see if it would work but everything I did, didn't work. Could it be because PlaceholderAPI needs you to use brackets inside the placeholder for it to work? Or is my setup just wrong?
```
match ^\/(test) (.*)
require script '{parseother_{$2}_{player_online}}' == 'yes'
then warn &aIt worked! 
then deny
```
But I couldn't get it to work.

**Info about this placeholder from PlaceholderAPI**
```
Let's you parse any placeholder for another player.
You can use placeholders in place of username.
Make sure to include the {} brackets, as it won't work without them.

%parseother_{username}_{placeholder_without_percent_signs}%
```

**Comment by kangarko** [comment]
Unfortunately we don't support double parsing of variables in that operator.
