### ISSUE TITLE
1.13.2 Chatcontrolred

### ISSUE THREAD

**Issue by TenReeez** [kangarko/ChatControl#774]
Minecraft Version: 1.13.2
MySQL: true
BungeeCord: true

Hey. Direct to the point: Does anyone involved with this plugin or knowledge of, such as ElBananna, or plugin dev ( wouldnt expect it)  do commission work to set this up properly?

 I have had nothing but issues with this plugin. While I am sure i am 99% responsible for such issues, And the dev has dumbed himself down as much as he can to spell it out to a laymen as myself, I am in need of support for it. I have had crash after crash etc. When I have asked for help it has been a minimal response. ( totally understanding that this is not a job, but a side project from the author and contributers ) however that wont help me.  I have managed to sort out every other plugin i use, but alas not this one.

I am still within my 30 day money back guarantee as stipulated by author, I do not want to do this as i see how well this plugin is thought out, but i might have to and move on.

So cry over, is there someone that will help set this up, talk me through it, im happy to PAY for hourly help, and i understand that if i pay for help in setting this up, it does not grant me the right to pester the person helping me after this is set up and working normal.

Please and thank you :)

**Comment by ElBananaa** [comment]
Hey!
We'd be more than happy to help you **without any payment**. You paid for the plugin, that's enough. Neither Kangarko nor I will make you pay to provide you support.

So let's just start by the beginning: what are the issues you're encountering with the plugin?

**Comment by TenReeez** [comment]
Hey Bananaa. Thankyou for your reply. I will speak with you after i sleep. Thank you for your offer of support. And you atleast deserve a couple of coffee's once this is over :)

**Comment by TheIntolerant** [comment]
Also happy to help if needed, though I don’t think my assistance will be required. 😝

**Comment by kangarko** [comment]
Wow that's really kind of you guys ;)

Please do let me know any "roadblocks" or anything stupid or confusing in the plugin and I'll try to make it better/easier to understand so that maybe you can do most of the work yourself quickly ;)
