### ISSUE TITLE
1.16.4: Expected human readable error

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#775]
I basically updated chatcontrol and now it won't load because of some config: https://gist.github.com/MithrandirCraft/5dedd4db6687db4565582c033e0fc793

I already set it to 1 second, but it seems like it still doesn't want to load. How can I fix the config?

Minecraft Version: 1.16.4 b416
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> I basically updated chatcontrol and now it won't load because of some config: https://gist.github.com/MithrandirCraft/5dedd4db6687db4565582c033e0fc793
> 
> I already set it to 1 second, but it seems like it still doesn't want to load. How can I fix the config?
> 
> Minecraft Version: 1.16.4 b416
> MySQL: true
> BungeeCord: true

Hey! If it doesn't want to load, it means that you didn't correctly update this value everywhere. Make sure there's human readable time in every file.

**Comment by MithrandirCraft** [comment]
> Hey! If it doesn't want to load, it means that you didn't correctly update this value everywhere. Make sure there's human readable time in every file.

The error refers to 

    Anti_Spam:
      Chat:
        Delay: 1

As you can see, it's already set to 1 second delay, but the error will still complain, saying "1" isn't human readable.

There are no other mentioned instances of conflicting values in the same or diferent files. And even if there where, I don't see what the issue is with setting a floating point value (even though it doesn't seem to care if it's float or not) in a config that was originally working fine.

In order to further check that there are "human readable values" in all of the plugin's files though, I'd first need to know what qualifies as "human readable", and what doesnt.

**Comment by ElBananaa** [comment]
> > Hey! If it doesn't want to load, it means that you didn't correctly update this value everywhere. Make sure there's human readable time in every file.
> 
> The error refers to
> 
> ```
> Anti_Spam:
>   Chat:
>     Delay: 1
> ```
> 
> As you can see, it's already set to 1 second delay, but the error will still complain, saying "1" isn't human readable.
> 
> There are no other mentioned instances of conflicting values in the same or diferent files. And even if there where, I don't see what the issue is with setting a floating point value (even though it doesn't seem to care if it's float or not) in a config that was originally working fine.
> 
> In order to further check that there are "human readable values" in all of the plugin's files though, I'd first need to know what qualifies as "human readable", and what doesnt.

The issue is due to the fact that you must write `Delay: 1 second`. `Delay: 1` isn't considered as human readable.

**Comment by kangarko** [comment]
Thanks Banana!

Yeah basically the plugin doesn't know what type of time is this - is it in seconds? In minutes? etc. You need to specify this ;)
