### ISSUE TITLE
1.16.5 How to read other channels while being in another channel?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#776]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: true

I have plot squared plot chat and public chat. I want my players to stay in the plot chat, send messages to global chat by putting "!" before messages (which I accomplished), and let them read the global chat while being in plot chat.

I can't get how to do that. If a player in the plot chat, he can't see the messages from the global chat. He has to join the global chat to see the messages. But I want him to be able to read the global chat while staying in plot chat.

Any suggestions?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: true
> 
> I have plot squared plot chat and public chat. I want my players to stay in the plot chat, send messages to global chat by putting "!" before messages (which I accomplished), and let them read the global chat while being in plot chat.
> 
> I can't get how to do that. If a player in the plot chat, he can't see the messages from the global chat. He has to join the global chat to see the messages. But I want him to be able to read the global chat while staying in plot chat.
> 
> Any suggestions?

Hey!
Simply give your users the autjoin permissions for the global chat in read mode.
`chatcontrol.channel.autojoin.<YourChannel>.read` `chatcontrol.channel.join.<YourChannel>.read` and it should fix the issue (at least for new users). If it doesn't fix it for old users, just ask them to manually join the global channel in read mode.

**Comment by nikitushu2** [comment]
Yeah, it worked for new users only.

I am, as an old user, trying to join the global chat in read mode but then I can't chat in local chat.

Is there any way to join several channels, one into read and the other one into write mode?

**Comment by ElBananaa** [comment]
> Yeah, it worked for new users only.
> 
> I am, as an old user, trying to join the global chat in read mode but then I can't chat in local chat.
> 
> Is there any way to join several channels, one into read and the other one into write mode?

This could be caused by multiple things. First, make sure the max read channel option is igh enough in the main config file.

Also make sure that you join the global chat using `/ch join global read` and join the local chat using `/ch join local write`

**Comment by nikitushu2** [comment]
Thanks, it worked.
