### ISSUE TITLE
1.16.5: CCR bad performance comparing to PRO

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#778]
![image](https://user-images.githubusercontent.com/43506080/110235355-379c2780-7ef5-11eb-8abd-020c95f509f2.png)

ChatControl Red uses more tick time than anticheat and the only thing it is supposed to do is to process chat messages that are all ASYNC events. I don't have any filters enabled on my server, nor I use any heavy regex except for `!message` for global chat. I am a little worried about those who use filters or host on shared hosts or don't have good CPUs. ChatControl Pro did not have so huge huge performance issues with the same functionality, but CCR is far far behind it.

I suggest to fix the performance.

**Comment by ghost** [comment]
![ccrp](https://user-images.githubusercontent.com/57458634/110237631-47d7f500-7f3d-11eb-8ae1-7c349b20727d.PNG)

How many players do you have on your server, when you took that timings report?

**Comment by radiant-ai** [comment]
> ![ccrp](https://user-images.githubusercontent.com/57458634/110237631-47d7f500-7f3d-11eb-8ae1-7c349b20727d.PNG)
> 
> How many players do you have on your server, when you took that timings report?

Around 40. You have `count(3)` btw, everybody was sitting in silence at the time of report capture?

**Comment by radiant-ai** [comment]
Some more data over 2 hours, this is the lag tab and CCR is the only plugin on my server that causes ticks to reach past 100% of allowed tick window.

![image](https://user-images.githubusercontent.com/43506080/110374697-97d6ba80-8016-11eb-95e8-f1e6caab4fa7.png)

During the 2 hours CCR caused at least 242 cases of 200 ms lag. This is very critical, suppose a player bridging over lava pool. This player may fall down because of this 200 milliseconds lag and this happened over 200+ times in 2 hours.

Overall as you can see CCR is responsible for 40% of all laggy ticks on my server.

![image](https://user-images.githubusercontent.com/43506080/110375115-23504b80-8017-11eb-964b-fd65dae2f512.png)

Compare its performance to the performance of a very badly optimized CrazyAuctions plugin which does IO operations on the main thread.

**Comment by kangarko** [comment]
Thanks, let's continue at https://github.com/kangarko/ChatControl-Red/issues/782
