### ISSUE TITLE
1.16.5: Forward channel bug

### ISSUE THREAD

**Issue by Toki-teki** [kangarko/ChatControl#779]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

I have a problem with forwarding messages.
For example, I write "test !Err"
The global channel displays: err

If I write "Wow!" Then a message will be displayed that I cannot send an empty message

My rules:

match (\!)(.*)
then command ch send global $2
dont verbose
then deny

match (\=)(.*)
then command ch send moder $2
dont verbose
then deny

**Comment by Toki-teki** [comment]
I can even write "/ tell player This is! Best bug"
And the "best bug" will be displayed

**Comment by Toki-teki** [comment]
I can even write "/tell player This is! Best bug"
And the "best bug" will be displayed

**Comment by Toki-teki** [comment]
I found a solution. It was necessary to add "^" at the beginning.
This symbol was not present by default.

**Comment by ElBananaa** [comment]
> I found a solution. It was necessary to add "^" at the beginning.
> This symbol was not present by default.

Hey!
Yes, you must use `^` before. Here's an example of my staffchat rule:
```yaml
# Send messages starting with "$" to staffchat
match ^(\$)(.*)
require perm chatcontrol.channel.autojoin.staffchat.read
then command ch send staffchat $2
then deny
dont verbose
```
I'm closing this issue, feel free to open a new one if you need anything else! :)
