### ISSUE TITLE
matching order of defined rules

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#78]
Following scenario:
In my `chat.txt` I create a rule to drop any useless asking for staff, like this:

```
match ^(mod|chatmod|admin|team|teamie) (da|anwesend|online|on).?$
then warn Stelle deine Frage einfach im Chat!
then deny
```

In the same file a few lines below I have two rules that remove spamming question and exclamation marks:
```
match (!)\1+
then replace !

match (\?)\1+
then replace ?
```

Then a user was asking for staff in a way that in theory matches both rules:
```
[14:44:42] [Async Chat Thread - #62/INFO]: *--------- ChatControl rule match on aPlayer --------- ID UNSET
[14:44:42] [Async Chat Thread - #62/INFO]: MATCH: (\?)\1+
[14:44:42] [Async Chat Thread - #62/INFO]: CATCH: admin online???
[14:44:42] [Async Chat Thread - #62/INFO]: FINAL: admin online?
```

Is there a way to control the matching order for rules? For this example I would prefer to match the first rule first.

CHC 5.2.8

**Comment by kangarko** [comment]
Rules should be matched from top to bottom.

**Comment by EvilOlaf** [comment]
Oh well, found the issue. The first rule did not match as there were multiple questions marks....
