### ISSUE TITLE
Whitelisted Delay Not Registering

### ISSUE THREAD

**Issue by TheMattVid** [kangarko/ChatControl#78]
I have the command "tpaccept" listed under the whitelist delay section, but it is still restricting people from using it consecutively. Perhaps it's because it is the exact same command. It gives players the error "Please do not repeat the same message (or similar) command. How do I get around this?

**Comment by TheMattVid** [comment]
I'd just like to add that the commands whitelist does not seem to be working for any commands. In all circumstances, players are prevented from typing the same command back-to-back and there does not seem to be any way to prevent this. In addition to this, it would be convenient if the plugin had a true/false option for this feature so we can turn this feature off and allow all commands to be repeated.

**Comment by kangarko** [comment]
Can you post your config? Make sure you did not include the "/" in the commands.

This works for me:
    Whitelist_Similarity:
    - tell
    - pm
    - spawn
    - home
    Whitelist_Delay:
    - spawn
    - home


And if you want to disable similarity block, set Similar_Percentage_Block to 0.

**Comment by TheMattVid** [comment]
Sorry about this late response. I think I actually switched the delay and similarity by accident. All is fixed.
