### ISSUE TITLE
1.16.5: Auto announce

### ISSUE THREAD

**Issue by Toki-teki** [kangarko/ChatControl#781]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

How to create auto announces?
can wiki link

**Comment by ElBananaa** [comment]
Hey!
You can find infos about timed messages in `messages/timed.rs`. You can find examples in the default files.
Also take a look at this page: https://github.com/kangarko/ChatControl-Red/wiki/Messages#timed-messages-conditions

**Comment by Toki-teki** [comment]
thank u
