### ISSUE TITLE
Vanish Improvement with /t

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#784]
When you use /t on a vanished player (camerahoofd was online in vanish), players can start a conversation.
They can not start one with me, because I am actually offline.
![image](https://user-images.githubusercontent.com/5664135/110476566-66c3bc00-80e2-11eb-8c63-3b8b9b9045c6.png)

Think this can use some improvement!

**Comment by kangarko** [comment]
Thanks will get added!
