### ISSUE TITLE
Stuck in private message on join

### ISSUE THREAD

**Issue by itsBeaco** [kangarko/ChatControl#786]
Hey, a few players on my server are joining the game and automatically being put into private messages with, who I assume, was the last player there spoke too. Is there a setting that would cause this to happen? or maybe a extra permission I shouldn't have added?

Kind regards,
Connor

**Comment by ElBananaa** [comment]
> Hey, a few players on my server are joining the game and automatically being put into private messages with, who I assume, was the last player there spoke too. Is there a setting that would cause this to happen? or maybe a extra permission I shouldn't have added?
> 
> Kind regards,
> Connor

Hey!
I believe this is due to the fact that they used `/tell <player>` without writing any message, which enters them in concersation mode with this player.
Tell them to use `/tell` to disable this mode.
If it still hapens, I'll take a look at your issue later today when I come back from the university. ^^

**Comment by TheIntolerant** [comment]
Just to add to this, on servers like Hypixel, if you do not speak for 5 minutes or more, the user automatically leaves conversation mode. Is this that could be added to prevent such cases like the one mentioned above?

**Comment by ElBananaa** [comment]
> Just to add to this, on servers like Hypixel, if you do not speak for 5 minutes or more, the user automatically leaves conversation mode. Is this that could be added to prevent such cases like the one mentioned above?

Well, that would definitely be a great idea, thanks for the suggestion! I'll leave this open so Kangarko could take a look at it.

**Comment by Larsthesheep** [comment]
> 
> 
> > Hey, a few players on my server are joining the game and automatically being put into private messages with, who I assume, was the last player there spoke too. Is there a setting that would cause this to happen? or maybe a extra permission I shouldn't have added?
> > Kind regards,
> > Connor
> 
> Hey!
> I believe this is due to the fact that they used `/tell <player>` without writing any message, which enters them in concersation mode with this player.
> Tell them to use `/tell` to disable this mode.
> If it still hapens, I'll take a look at your issue later today when I come back from the university. ^^

Even after disabling this mode, trying both `/tell` and `/tell off` it still auto-joins me into this talk. 
![afbeelding](https://user-images.githubusercontent.com/34158984/110852067-2b77e780-82b2-11eb-8361-a84dcca641e1.png)

**Comment by kangarko** [comment]
Thanks, I removed automode from data.db/mysql saving and made it forget itself after a given time limit
