### ISSUE TITLE
1.16.5 Endles errors FoException: Report: Unknown action named

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#787]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false
CHC 10.2.9

For every new version, I always start a test server with CHC and let CHC make it's folder with default config files.
From 10.2.8 and higher, this goes completely wrong resulting in endless errors.
I first thought I might be doing something wrong.

But since the errors still happen with 10.2.9, hereby a report of the errors.
Maybe someone knows the origin of these errors.

The server starts fine, as always.
As soon as a player joins: errors! https://pastebin.com/raw/eF1zJrUk
You can restart the server, doesn't matter. As soon as the first player joins,... 

CHC 10.2.7 runs fine

**Comment by kangarko** [comment]
Please update your BungeeControl Red also.

**Comment by kangarko** [comment]
*BungeeControl Red I mean
