### ISSUE TITLE
1.16.5: How can I disable chatcontrol death messages on a server?

### ISSUE THREAD

**Issue by AlfreDGR** [kangarko/ChatControl#789]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ghost** [comment]
Check "ChatControlRed/messages/death.rs"

**Comment by AlfreDGR** [comment]
I can't find anything to disable all death messages within that file.

**Comment by ghost** [comment]
The file is filled with rules to override all different death messages, you can edit or remove messages you don't want to change from this config or just delete the entire file, maby you should try to understand how ccr works in general, i think this was covered in the tutorial?

**Comment by TheIntolerant** [comment]
You can disable any of the message types in 
``settings.yml`` -> ``Messages:`` -> ``Apply_On:``

It should look something like this
```
Messages: 
 
  # What aspects of messages should be enabled?
  # Options: join, quit, kick, death, timed
  #
  # If you have another plugin handling join/quit etc. messages, remove them from list below.
  # If you want to hide those messages, leave them in Apply_On and empty your messages/ .rs files.
  Apply_On: [join, quit, kick, death, timed]
```
So you end up with ``Apply_On: [join, quit, kick, timed]`` etc

**Comment by ElBananaa** [comment]
Hey!
Thanks to everyone for answering. I'm closing this issue, feel free to open a new one if you need anything else.
