### ISSUE TITLE
The private message spy is showing people's UUID's instead of player names.

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#79]
[https://i.imgur.com/jYhcewZ.png](https://i.imgur.com/jYhcewZ.png)
The private message spy is showing people's UUID's instead of player names.

My format config is set to:
    Message: "&c[PM] &f[{sender}] -> [{receiver}]: &7{message}"

**Comment by kangarko** [comment]
Thanks, will be fixed
