### ISSUE TITLE
Group Chat Format

### ISSUE THREAD

**Issue by NytronMC** [kangarko/ChatControl#79]
I was wondering if there was any way to set specific chat colors for certain groups.

Example
Defaults: &7
Owner: &e
![2016-03-06_14 41 12](https://cloud.githubusercontent.com/assets/17339983/13557627/80be0a10-e3a9-11e5-8180-ff41763f0e8d.png)

**Comment by kangarko** [comment]
Hey, such feature is handled by a permission plugin, for example PermissionsEx.
