### ISSUE TITLE
1.16.5: Some promlems with global chat

### ISSUE THREAD

**Issue by div2005** [kangarko/ChatControl#790]
**First:** 
There is a problem with some letters in the global chat. I would like to know if one of me has this and what could be a problem

(GlobalChat) I send: `!ё й ї` >> Result: `е и і`
![image](https://user-images.githubusercontent.com/46396764/110785975-a1615c00-827c-11eb-944c-b0d25ff49935.png)

(LocalChat) I send: `ё й ї` >> Result: ё й ї
![image](https://user-images.githubusercontent.com/46396764/110786228-ee453280-827c-11eb-81b2-ac14864863fc.png)

But when i'm using global chat with command, it works perfectly:
(GlobalChat) I send: `/channel send Global ё й ї` >> Result: `е и і`
![image](https://user-images.githubusercontent.com/46396764/110786439-2fd5dd80-827d-11eb-9e15-f45a4442fb62.png)

**Second:**
For global chat doesn't work "Format_Console" setting
```
Global:
      Format_Console: '[G] {player}: {message}'
      Format: global-chat
      Discord: false
```
![image](https://user-images.githubusercontent.com/46396764/110786692-7c211d80-827d-11eb-9500-43872e85a19e.png)

ChatControlRed & Paper (JesusSpigot) versions: latest 
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by TheIntolerant** [comment]
Please type ``/chc debug`` and upload your debug file here.

**Comment by div2005** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6123309/debug.zip)

**Comment by TheIntolerant** [comment]
Okay so I see you use ``!<message>`` to talk in global chat. 
To fix this in ``settings.yml`` under ``rules:`` change ``Strip_Accents: true`` to ``Strip_Accents: false``

As for the issue with Format_Console, it most likely will be up to the  plugin dev to fix that.

**Notes For Dev**
It seems the issue with ``Format_Console:`` is a bug, as it is only displayed when someone types in that channel while in "write" mode. So when you use ``/channel send <channel_name>`` to talk or a chat control rule, for example:
```
# Send messages starting with "!" to global channel
match ^(\!)(.*)
then command channel send global $2
then deny
dont verbose
```
No message is sent to the console (unless it is a command then the only message you will see, is something like "{user} executed command: /command" etc)

**Comment by kangarko** [comment]
Thanks to gone-incognito for the help!

**Comment by kangarko** [comment]
Looking into the format console issue

**Comment by kangarko** [comment]
Thanks, solved
