### ISSUE TITLE
1.16.5: Tab completer problem

### ISSUE THREAD

**Issue by Toki-teki** [kangarko/ChatControl#791]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hello.
Tab completion does not work for me with some commands. I'll mark the ones that don't work.
What could be the reason?

https://pastebin.com/RvPRQvuF

[settings.zip](https://github.com/kangarko/ChatControl-Red/files/6130651/settings.zip)

**Comment by Toki-teki** [comment]
Not completed commands: /fly, /craft and /chop

**Comment by kangarko** [comment]
Likely because they are monitored/managed by some other (tab controlling) plugin, however I am not 100% sure, will let you know if I find something
