### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by Smedve** [kangarko/ChatControl#792]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hello!

Today I've updated the plugin, and it spams the console with the error below.
It only happens when a player is online.

![kép](https://user-images.githubusercontent.com/37949493/110960752-5e23ed80-834f-11eb-8f91-dfbd2057cf8d.png)

**Comment by kangarko** [comment]
Update BungeeControl Red and restart the network, do not reload.

**Comment by kangarko** [comment]
Or try the BungeeControl Red from the next version
