### ISSUE TITLE
1.16.5: Few error logs & messages to check

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#793]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi I decided that if something weird occurs in my error messages that I will regularly report it. Cause my error messages are still being existing, there's something wrong.

https://pastebin.com/pmgKy6Cc -> especially look at DiscordSRV one
+ about my regex problems, I would be glad if you would suggest me something to improve it: 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6133649/debug.zip)

Second server - just DIscord ones: https://pastebin.com/ZguH6iUT

**Comment by bobhenl** [comment]
```
More Information: 
Failed to execute scheduled task: java.util.ConcurrentModificationException
ConcurrentModificationException (Unknown cause)
	 at java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:648)
	 at org.mineacademy.chatcontrol.model.Packets.lambda$removeMessage$0(Packets.java:392)
	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	 at java.lang.Thread.run(Thread.java:748)
----------------------------------------------------------------------------------------------

```

**Comment by kangarko** [comment]
Regarding regex problems, I believe I have identified the cause, as a temporary resort I switched off this check for those cases where it may come up. Next version will be free of this problem. Also the Concurrency issue will get patched.

**Comment by bobhenl** [comment]
And just btw regardless to this Spark https://spark.lucko.me/60I0727oXJ?hl=9949,14865,42,23,37697 where's chatcontrol mentioned too, sometimes it seems that when regex got caught it caused tps drops, see here https://pastebin.com/82m88YP8, may you find there other causes too like quitplayer etc in this cut log

**Comment by bobhenl** [comment]
Jen btw myslíš, že by pomohlo přidat to \b na začátek těch regexů sprostých slov ohledně výkonu, či to o moc velká změna nebude? Ale možná by se nedělo toto a zase helpery na hlídání máme případně.

**Comment by kangarko** [comment]
Je to mierna zmena, ale treba rátať s tým že každý regex sa kontroluje pre každú správu pre každého hráča. Takže 50 pravidiel znamená 50x vykonaná kontrola len na jednu správu. Čiže zráta sa to.

**Comment by bobhenl** [comment]
Mhm, tak pokud myslíš, že ty mé problémy souvisí i s tím regexem, tak ho asi mohu trošku protřídit. Záleží teda, zda by to mohlo nějak výrazněji přispět https://github.com/kangarko/ChatControl-Red/issues/782 a vyřešit se tím nějaké to červené číslo, případně na kolik ideálně regexů (těch pravidel tedy) to nechat. Možná na wiki můžeš uvést nějaké doporučené číslo, pod kterým to držet. Případně možná bych to mohl dát jen pro chat, i když je škoda, že to nelze dát jen pro chat + určitý příkaz stále, že bych to dal jen pro msg.

**Comment by kangarko** [comment]
Neviem odporúčané číslo pretože všetko závisí od používania a hardvéru.

Server kde je 5 hráčov so slabým hardvérom pôjde rýchlejšie ako s 180timi hráčmi s výkonným hardvérom. Proste to by som si musel vymyslieť, takéto testy sme nerobili, vyskúšaj nechaj bežať na 5 dní a meraj výkon s pár kombináciami. Veľa šťastia :)
