### ISSUE TITLE
1.16.5 : Is it possible to make it so that muted players can't talk from discord?

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl#794]
Minecraft Version: 116.5
MySQL: true/**false**
BungeeCord: true/**false**

Hey! I was wondering if you can prevent muted players from chatting from discord! thanks :)

**Comment by kangarko** [comment]
If you mute them through ChatControl Red then they won't be able to talk, please correct me if I am wrong (haven't tested right now).

**Comment by JessePesse123** [comment]
We always mute through ChatControl Red and  they're still able to talk :)

**Comment by kangarko** [comment]
Thanks for noticing, I will fix that
