### ISSUE TITLE
Placeholder Support for Gradients (Channel Formats)

### ISSUE THREAD

**Issue by NiNjAiKoToBa** [kangarko/ChatControl#798]
If you still believe your feature should be added, you're welcome to suggest it and answer those questions in your description: 

1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
Being able to use placeholders, more specifically luckperms metadata to program gradients would bring gradiented usernames and the alike to servers just like when we were first able to colorise usernames and nicknames. This would be a great cosmetic addition and would bring another step CCR above most other chat plugins which also do not yet support this.

2. What would happen if we won't implement this feature? How's your server being affected?
Without this feature, implimenting group based gradients is infeasible. We have one working for our developers but can not reasonable roll this out on a custom basis for our players due to it requiring hardcoded groups and a lot of permission overrides to properly function.

Hello!
 
I’ve noticed there seems to be one small feature missing from CCR that if possible I’d like to request.
 
When trying to setup gradients for channel components, I noticed that you cant actually feed placeholders into the gradient config. Trying to do so causes an error.
 
I’m trying to setup dynamic gradients using placeholders configured by user group from luckperms. Slightly advanced, but I was hoping to see the ability for the gradient feature in channel formats to be able to parse placeholders so I can achieve this.

![image](https://user-images.githubusercontent.com/5144099/111186800-46e13c00-85ab-11eb-86d6-0aceb3c0e08e.png)
Instead of hardcoding the values, we could pull them from permissions, using {luckperms_meta_thex1} for example, and be able to retrieve the code, just like we can for non gradient color usage elsewhere. instead of having to hardcode for each user group/permission.
![image](https://user-images.githubusercontent.com/5144099/111187002-7bed8e80-85ab-11eb-89ca-897a317f2d5a.png)

Thanks for your time and consideration!

**Comment by kangarko** [comment]
Thank you, I will note this into the future!
