### ISSUE TITLE
Then warn/kick <random|random>

### ISSUE THREAD

**Issue by MineTheCube** [kangarko/ChatControl#8]
Hi again,

We can replace or rewrite with a random message, that's fine, but when we warn or kick player with a random message (separated with "|"), it sends "random|random" literally, instead of sending random one.

Please, could you fix this bug ?

**Comment by kangarko** [comment]
Random selecting is currently only supported in replace or rewrite. I can take a look if it is possible to add in warn or kick, too.

**Comment by MineTheCube** [comment]
Oh it would be great, as I thought it was a bug :)

**Comment by kangarko** [comment]
So I reviewed the code and added randomly picking one message to "kick" operator. The warn operator already supports | to split messages over to multiple lines, but not to pickup random.

**Comment by MineTheCube** [comment]
I just downloaded 5.1.8, and:

`then warn first|second|third` send me `first|second|third`
![](http://i.imgur.com/voMZQNc.png)

`then kick first|second|third` kick me with `|` replaced with new lines
![](http://i.imgur.com/05hSVvD.png)

I suggest you to use `|` as random separator, and `\n` as new line separator in every operator that support messages (replace, rewrite, console, warn, kick, notify)

**Comment by kangarko** [comment]
The thing is, \n does not work on some systems. I don't know why is that, but this is the default line separator on windows/unix so I can't fix that.

Operator **then warn** has | functionality as random separator only in premium version. When I have time, I can take a try to add it here too.

**Comment by MineTheCube** [comment]
I was talking about using `\n` literally in file, like:
![](http://i.imgur.com/DdLAzIR.png)
But this is a suggestion, as I only need the random feature (`|`) for `then warn` operator.

**Comment by kangarko** [comment]
Yeah the \n does not need any implementation from my side since it's default line separator on most systems. The thing is that it appears not to be working since about 1.8, so I had to find out another way.
You can try if it works for you.
