### ISSUE TITLE
Display name on join message not formated right

### ISSUE THREAD

**Issue by hockeymikey** [kangarko/ChatControl#8]
http://i.imgur.com/AEJYbYB.png

As you can see from the picture your display name is not correctly formatted when you join the server.

My config is here: http://pastebin.com/Q9DMhFz9
I am using EssentialsChat for the chat.

Also the join message is sent to the player joining when it shouldn't only to other players.
http://i.imgur.com/FlzMhli.png
Example of it in the link.  You can clearly see I am being sent my own join message.

**Comment by DiamondKing099** [comment]
%prefix still only shows [ChatControl]

**Comment by kangarko** [comment]
Oh, really? My bad. It is overlapping the %prefix you specify in localization. I will try to fix it but most likely it will require a prefix name change.

**Comment by kangarko** [comment]
So I finally managed to, hopefully, fix the issue, use %pl_prefix and %pl_suffix in the chat formatter.
@hockeymikey and @DiamondKing099 please test against version 5.0.5

**Comment by hockeymikey** [comment]
I've switched to bungee so I'm using a bungee plugin for join/quit messages now.  Sorry but I probably won't have time to test.

**Comment by kangarko** [comment]
I have tested them, works fine when  using new variables.
