### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by iorunner** [kangarko/ChatControl#80]
Every time anyone tries to chat, it throws this exception:
http://pastebin.com/We8HFDts

and prefixes and suffixes no longer show up.

Here's a look at my server startup activities, which includes a list of plugins at the bottom:

http://pastebin.com/iPwKcTAW

**Comment by iorunner** [comment]
and here is the config file:  http://pastebin.com/TERNZ0CR

**Comment by kangarko** [comment]
Make sure you are on the latest version and notice that %prefix and %suffix has changed to %pl_prefix and %pl_suffix
