### ISSUE TITLE
Paper 1.16.5 | Issue with ignored players and the Sound_Notify feature

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#800]
Minecraft Version: Paper 1.16.5
MySQL: true
BungeeCord: false

Hey!
So I just noticed that ignored players can still tag players when the Sound_Notify feature is enabled. Enabling/Disabling the bi-directional ignore feature doesn't change anything. The issue here is that it means that even if a player is ignored by another player, they can still tag each other.

I also noticed that there's no bypass permission for the Sound_Notify delay. I think it would be pretty useful to add this, since as a staff member, you sometimes need to tag a player a few times in a short time range.

Finally, I think it would be also nice to send a message to ignored players if they specify the name of a player who ignored them in the chat, telling them that this specific player ignored them, so they're aware of it.

**Comment by kangarko** [comment]
Implemented it all thank you!
