### ISSUE TITLE
1.16.5: CCR Interaction with other plugins

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#801]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

I did several tests on this and its 100% CCR:

It looks like ccr is interacting with different plugins in a pretty weird way. I discovered that ccr is looping tasks from different plugins, for example mcmmo. I discovered getting many debug messages from that plugin even if debug was disabled, so i asked the author (nossr50) about this.

First of all, here is a log where you ccan see the issue, i tested on paper and spigot to be sure its not related to a custom fork or something:
https://pastebin.com/W54xnqve

You will find something like this:
[08:13:43] [Server thread/INFO]: [mcMMO] [Debug] Saving Parties... (0)
[08:14:43] [Server thread/INFO]: [mcMMO] [Debug] Saving Parties... (0)
[08:15:43] [Server thread/INFO]: [mcMMO] [Debug] Saving Parties... (0)

I asked nossr50 what to do about this and what is actually happening and he replied that the plugin might be somehow looping the mcmmo tasks (and maby also other plugins) which may result in high disc usage or issues with plugins breaking.

![nossr50-1](https://user-images.githubusercontent.com/57458634/111430722-0f81a500-86fb-11eb-9ea1-622973fa7e05.PNG)
![nossr50-2](https://user-images.githubusercontent.com/57458634/111430733-13152c00-86fb-11eb-962e-708bb0128056.PNG)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6154470/debug.zip)
(default config)

Plugin list:
- ChatControl-Red-10.3.0
- mcMMO-2.1.181
- ProtocolLib-Build498
- Vault-1.7.3

**Comment by ElBananaa** [comment]
Hey!
Did you fix this issue? Was it related to chatcontrol-red?

**Comment by kangarko** [comment]
I have no idea how we could cause other plugins to loop, I can look into this but you're so far the first ever to report such and if that would the case then this would come years ago.
