### ISSUE TITLE
/chc forward allowing even when server is empty

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#803]
Hi please, I want to forward one cmd from Lobby (or proxy, but proxy doesn't support forward command) even when Lobby server is empty.

I want to execute command:
```
  'chc forward Survival collaborationredirect confirm id%',
  'chc forward Svanilla collaborationredirect confirm id%'
```

It's custom plugin working as daily reward when people visit website. But I can forward it ONLY from Lobby or Proxy, cause Survival & Semi are on different machine and aren't on Pterodactyl. SO I need to forward it even when server is empty if it could be possible. May you could add there something like `-e` or new option to config to allow it? I really need it, cause Dispatcher plugin https://www.spigotmc.org/resources/old-dispatcher.9854/ stopped working and there isn't any other way to do it for me than via Chatcontrol, but now I can't do it cause people aren't on Lobby 24/7... so when someone will ask for daily reward he doesn't have to get it. Kdyžtak to popíšu v češtině, ale je to opravdu potřeba.

**Comment by kangarko** [comment]
Hey!

Apology, you cannot forward to empty servers by design of the BungeeCord API because there is no player instance to refer from. I recommend asking your custom plugin developer to store rewards on MySQL and make other servers periodically check for them even if they are empty instead.

**Comment by bobhenl** [comment]
And what about chc forward command on bungee?

**Comment by kangarko** [comment]
Right now the command does not exist on Bungee and it is executed from Bukkit.
