### ISSUE TITLE
Add required servers conditional for rules

### ISSUE THREAD

**Issue by DavidForge** [kangarko/ChatControl#805]
Hi, I have a suggestion of add required servers conditional for rules.

It would work in such a way that the player needs to be on the server for the conditional to be met.

1. The servers could in this way put that some rules or even commands can only be executed if the player is on certain servers.

Especially I see it useful to create / lobby type commands and take the player to the lobby, right now to do it without taking him to the lobby you need to make a list of worlds, and in large networks it is quite uncomfortable.

2. I could do the / lobby and other commands with the chatcontrol network, as explained above.

**Comment by kangarko** [comment]
Thanks, pulled to a future roadmap but not planned right now

**Comment by DavidForge** [comment]
Ok perfect, thanks you ^^
