### ISSUE TITLE
1.16.5: Can't disconnect from the channel

### ISSUE THREAD

**Issue by Toki-teki** [kangarko/ChatControl#806]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

I am trying to leave the channel. But in response he writes: The player is offline.
But I know for sure that the player is on the server, because it's me.

**Comment by kangarko** [comment]
Are you connecting through BungeeCord? Does this also happens after a restart?

**Comment by Toki-teki** [comment]
Yes and yes

**Comment by Toki-teki** [comment]
i use this plugin on bungee. Maybe this problem?
https://www.spigotmc.org/resources/%E2%96%A0-jpremium-%E2%96%A0-authorization-plugin-%E2%96%A0-automatic-login-premium-%E2%96%A0-cracked-sessions-%E2%96%A0-password-recovery-%E2%96%A0.27766/

**Comment by ElBananaa** [comment]
> i use this plugin on bungee. Maybe this problem?
> https://www.spigotmc.org/resources/%E2%96%A0-jpremium-%E2%96%A0-authorization-plugin-%E2%96%A0-automatic-login-premium-%E2%96%A0-cracked-sessions-%E2%96%A0-password-recovery-%E2%96%A0.27766/

Hey!
If i'm not wrong, plugins like this one are doing manipulations with players UUIDs in order to allow premium logins without having to type any password. You could try to remove JPremium, and see if the issues persists if you don't mind.

**Comment by kangarko** [comment]
Thanks to Banana for catching up on this, closing since this is a third party plugin incompatibility. Let me know below if I am wrong.
