### ISSUE TITLE
1.16.5: How to disable death notifications in a worldguard region?

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl#808]
How can I disable death notifications in a worldguard region? I tried the following setting at the top of death.rs.
```
group silent_in_region_test
require sender region test
message: 
- none
```
The effect is simply that no deathmessage is displayed anywhere anymore. I have also played around with `ignore sender region` and `require killer region`, also without success. With other parameters, like worlds, the syntax works, but with regions nothing works. How do you do it correctly? I would be very happy if you could point me in the right direction!

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6173437/debug.zip)
Minecraft Version: Paper 1.16.5 - build 551
ChatControlRed version 10.3.0
WorldGuard version 7.0.5-SNAPSHOT+2100-aeea455
MySQL: true
BungeeCord: false

**Comment by ElBananaa** [comment]
> How can I disable death notifications in a worldguard region? I tried the following setting at the top of death.rs.
> 
> ```
> group silent_in_region_test
> require sender region test
> message: 
> - none
> ```
> 
> The effect is simply that no deathmessage is displayed anywhere anymore. I have also played around with `ignore sender region` and `require killer region`, also without success. With other parameters, like worlds, the syntax works, but with regions nothing works. How do you do it correctly? I would be very happy if you could point me in the right direction!
> 
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6173437/debug.zip)
> Minecraft Version: Paper 1.16.5 - build 551
> ChatControlRed version 10.3.0
> WorldGuard version 7.0.5-SNAPSHOT+2100-aeea455
> MySQL: true
> BungeeCord: false

Hey!
The `require region` features isn't for worldguard but for chatcontrol region feature. 
You can find more infos about it on the wiki (https://github.com/kangarko/ChatControl-Red/wiki/Commands#chc-region) or by typing `/chc region` ingame.

**Comment by TheoRetisch1** [comment]
Thank you it worked 👍
