### ISSUE TITLE
Prevent ChatControl handling Discord -> MC messages

### ISSUE THREAD

**Issue by Curtis73** [kangarko/ChatControl#809]
Would it be possible to prevent ChatControl from handling Discord -> MC messages, and let DiscordSRV handle them instead?

I'm happy with how ChatControl handles MC -> Discord messages, but I'd rather DiscordSRV handles & formats the Discord -> MC messages, and broadcasts them to all players on the server.

**Comment by ElBananaa** [comment]
> Would it be possible to prevent ChatControl from handling Discord -> MC messages, and let DiscordSRV handle them instead?
> 
> I'm happy with how ChatControl handles MC -> Discord messages, but I'd rather DiscordSRV handles & formats the Discord -> MC messages, and broadcasts them to all players on the server.

Hey!
This is currently not possible, but you can completely disable ChatControl integration in order to do this with DiscordSRV directly. However, as I don't know if this was already suggested, I'll leave this open so Kangarko could take a look at it.

**Comment by kangarko** [comment]
Thanks to Banana for answering, right you can completely disable our Discord hook in the Integration section of settings.yml and then use a third party plugin such as DiscordSRV to format.

**Comment by Curtis73** [comment]
Hey, thanks for your replies!

I've tried disabling the Discord hook entirely, but that becomes problematic when you have multiple in-game channels, as all the messages are sent into a singular Discord channel where they blend together, which is really confusing for everyone on Discord.

Because of this, a way to enable ChatControl's handling of MC -> Discord messages, so I can control what messages go into what Discord channels, but a way to Disable ChatControl's handling of Discord -> MC messages, so they're broadcast to all players using DiscordSRV's format would be ideal.
Of course, I understand if that's not possible for whatever reason

Thank you!

**Comment by kangarko** [comment]
Thanks, not possible right now but I can put this onto our future roadmap
