### ISSUE TITLE
Suggestion: /chc purge <player> to remove all player messages

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#81]
So i requested the "insertion" addition (btw thanks for adding) and was thinking it could be really interesting to have it function as a "remove all messages from this player in chat" option. Whereby holding shift and clicking the [X] would achieve this. This improvement would make it extremely simple to essentially remove the problem players messages for everyone on the servers. 

iirc insertion essentially runs a suggest_command clickaction so you can use that as a verification. i.e the staff member would need to click the X and then press enter to confirm the action.

If this is already a thing, mybad i just got access to Red.

**Comment by kangarko** [comment]
Thanks, however I have no idea how to do it. Maybe I can add a command `/chc removemessages <player>` instead?

**Comment by LogGits** [comment]
Yeah youd need to have a dedicated command for it, e.g. `/chc purge [player]`.

**Comment by kangarko** [comment]
I looked at the current system, and decided to delay adding this suggestion till we're at least out of beta. Feel free to resuggest in a month or two, thank you.

**Comment by LogGits** [comment]
Can we relook into this, im also curious could I achieve feature this via the chc api?

**Comment by kangarko** [comment]
Reopening, problem is the system doesn't store that information, bigger rewrite is needed so it's gonna take a while, while I am limited on time

**Comment by kangarko** [comment]
Finally implemented, took longer due to other work but I am happy we have it now!
