### ISSUE TITLE
Strange Character Appears Before Intended Symbol

### ISSUE THREAD

**Issue by EnslavedDave** [kangarko/ChatControl#81]
When using » in the chat format, a different character appears as well as the intended character.

This can be seen here: http://gyazo.com/d1b5afda58890b3c8f16b0d261e0e09e

**Comment by EnslavedDave** [comment]
Config can be found here:
http://pastebin.com/2Cpmb4yq

**Comment by kangarko** [comment]
What CB/java/operating system are you running? Make sure unicode characters (UTF-8) are saved properly. I have tested them on Notepad++, wordpad/notepad on windows is broken.
