### ISSUE TITLE
1.16.5: then notify <permission> <message or format> -> Can we use command instead of message too?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#810]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, is it possible to use in combination with:
`then notify <permission> <message or format>`
command instead of <message or format>? Or wouldn't it be possible please? I wanna make that when someone writes word "helper" and so on... then it will display actiobar /title to users with this permission. If it's not already possible, could you please add this way to execute command only for people with the given permission? Like helper.notify

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, is it possible to use in combination with:
> `then notify <permission> <message or format>`
> command instead of ? Or wouldn't it be possible please? I wanna make that when someone writes word "helper" and so on... then it will display actiobar /title to users with this permission. If it's not already possible, could you please add this way to execute command only for people with the given permission? Like helper.notify

Hey!
I'm not sure to completely understand you, but I think what you want is already possible using `then actionbar <message>` (https://github.com/kangarko/ChatControl-Red/wiki/Rules#then-actionbar-message) and `then title <title|subtitle>` (https://github.com/kangarko/ChatControl-Red/wiki/Rules#then-title-titlesubtitle).

**Comment by kangarko** [comment]
You can use the two operators as Banana explained. Right now the "then notify" operator only shows on chat.

**Comment by bobhenl** [comment]
But wait, I need to combine it with permission. I want to send this actionbar/title only to those who have this permission.

**Comment by bobhenl** [comment]
@ElBananaa ?

**Comment by ElBananaa** [comment]
> @ElBananaa ?

Hey!
Sorry for the delay, I completely forgot to answer you.
Unfortunately, I don't think what you want to do is currently possible with the plugin.
I'll leave your issue open so Kangarko could take a look at it.

**Comment by kangarko** [comment]
We do not support a conditional actionbar/title operator right now, you'd have to stick with a bare message for now.

**Comment by bobhenl** [comment]
The problem is that bar message isn't so visible... Couldn't you at least add a way to execute a command, so it could be then notify <permission> <message, format OR command>?

**Comment by kangarko** [comment]
I think for your needs it's just gonna be easiest if you have a small developer make a custom integration for CCR
