### ISSUE TITLE
1.16.5. Ignoring channel in rules does not apply for message forwarding

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#812]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

Here what I got in rules:
```

# -----------------------------------------------------------------------------------------------
# Forwarding messages to other channels.
# -----------------------------------------------------------------------------------------------

# Send messages starting with "!" to global channel
match ^(\!)(.*)
then command channel send global $2
then deny
dont verbose

# -----------------------------------------------------------------------------------------------
# Anti spam.
# -----------------------------------------------------------------------------------------------

# Limiting repeating characters to four repeats maximum.
match (.)(?=([a-z])\1{3})
ignore channel local
then replace
```

My channels are global and local. People send messages to global through the use of "!" before messages (so messages are reforwarded from the local channel).

The problem is that the above rule ignores both local and global channel. (I want apply rules only to global channel, ignoring the local one). My assumption is that because the plugin does not detect message forwarding to a channel same as being in that channel. 

How to fix this?

**Comment by TheIntolerant** [comment]
I could be wrong but I believe it needs to be ``ignore channel local write``, I'm not 100% sure how ``ignore channel`` works though.

**Comment by ElBananaa** [comment]
Hey!

@gone-incognito It works with both ways. You can specify the channel mode, but it's not a obligation.

@nikitushu2 Please upload us your `/chc debug` file, i'll run some tests on my end.

**Comment by nikitushu2** [comment]
> 
> 
> Hey!
> 
> @gone-incognito It works with both ways. You can specify the channel mode, but it's not a obligation.
> 
> @nikitushu2 Please upload us your `/chc debug` file, i'll run some tests on my end.

[https://ufile.io/ic960obs](https://ufile.io/ic960obs)

**Comment by ElBananaa** [comment]
> > Hey!
> > @gone-incognito It works with both ways. You can specify the channel mode, but it's not a obligation.
> > @nikitushu2 Please upload us your `/chc debug` file, i'll run some tests on my end.
> 
> https://ufile.io/ic960obs

Thanks.

It seems like you're using a really old version of the plugin. Please update to the latest version and try again. If it still doesn't work, since I don't really know if the order of the rules count, try to place the antispam rule above the global channel rule

**Comment by TheIntolerant** [comment]
Sorry I read this wrong, just to add clarification to what was said above, basically chatcontrol rules are processed from top to bottom. This is especially important to note when you have rules you wish to interact with each other.

In your case, an anti spam rule and a channel forwarding rule.
Another thing to note, due to one of the having the "then deny" operator, this effectively cancels the message and thus, any rules below it will not process the rule as it has been cancelled.


So by making the rules layout like this...

```
# -----------------------------------------------------------------------------------------------
# Anti spam.
# -----------------------------------------------------------------------------------------------

# Limiting repeating characters to four repeats maximum.
match (.)(?=([a-z])\1{3})
ignore channel local
then replace



# -----------------------------------------------------------------------------------------------
# Forwarding messages to other channels.
# -----------------------------------------------------------------------------------------------

# Send messages starting with "!" to global channel
match ^(\!)(.*)
then command channel send global $2
then deny
dont verbose
```

That will fix your problem, as the anti spam rule processes the message before it gets canceled by the channel forwarding rule.

Hope that makes sense as to why this is happening and hopefully prevents you from having the issue again in the future.

**Comment by kangarko** [comment]
Thanks to gone-incognito for giving a helping hand on this one!
