### ISSUE TITLE
1.16.5 bungee/dc chat prefix

### ISSUE THREAD

**Issue by lalalalajciyiy** [kangarko/ChatControl#813]
Hello,

I just want to ask you, if its possible to remove those [Bungee/Onefun] prefixes here https://prnt.sc/10qxjih ?
Thanks for help,
Lukas

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Hello,
> 
> I just want to ask you, if its possible to remove those [Bungee/Onefun] prefixes here https://prnt.sc/10qxjih ?
> Thanks for help,
> Lukas
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
Yes, it is possible.
To do so, go in ChatControl-Red settings file and under the `BungeeCord:` part, look for: 
`Prefix: '&8[&dBungee/{bungee_server_name}] '` then replace it with `Prefix: ''`
