### ISSUE TITLE
1.16.5: Database is loading data?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#814]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, this message is appearing quite often for me after rejoin:
![image](https://user-images.githubusercontent.com/18662086/111880965-a0cc7200-89ae-11eb-87b2-e1aacd5f259e.png)
And then the message is delayed sometimes when players join. 
also login message got doubled for this reason...

This message appears after every command I try to execute.
and tps are green...
![image](https://user-images.githubusercontent.com/18662086/111881008-d4a79780-89ae-11eb-9013-b2a738224cb9.png)

But I've god message that login servers are down, so isn't something wrong with Minecraft (Mojang) accounts itselves? Maybe when checking my name or?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, this message is appearing quite often for me after rejoin:
> ![image](https://user-images.githubusercontent.com/18662086/111880965-a0cc7200-89ae-11eb-87b2-e1aacd5f259e.png)
> And then the message is delayed sometimes when players join.
> also login message got doubled for this reason...
> 
> This message appears after every command I try to execute.
> and tps are green...
> ![image](https://user-images.githubusercontent.com/18662086/111881008-d4a79780-89ae-11eb-9013-b2a738224cb9.png)
> 
> But I've god message that login servers are down, so isn't something wrong with Minecraft (Mojang) accounts itselves? Maybe when checking my name or?

Hey! I don't have a such issue with the plugin.
Are your databases and your game servers hosted on the same dedicated server? If not, you could try to do so. Also make sure your database driver is up-to-date, as it can increase speed (You should consider using MariaDB over MySQL since it's faster, and way more optimized).

**Comment by bobhenl** [comment]
Yeah it's on same machine. I use MariaDB. And yes, they're up to date. But it doesn't happen everytime I join, just "sometimes", but a quite often maybe. Maybe few times a day?  Don't know, I can try to count, I think for me I notice it maybe <5-10, but IDK how other players. If there is something to fix, at least to don't prevent command usage, cause I can't execute any commands when database is currently... or some other solution.

**Comment by ElBananaa** [comment]
> Yeah it's on same machine. I use MariaDB. And yes, they're up to date. But it doesn't happen everytime I join, just "sometimes", but a quite often maybe. Maybe few times a day? Don't know, I can try to count, I think for me I notice it maybe <5-10, but IDK how other players. If there is something to fix, at least to don't prevent command usage, cause I can't execute any commands when database is currently... or some other solution.

Hey!
In the settings file, if you've enabled the log system, try to reduce the `Clean_After:` option to something like 10 days.

**Comment by bobhenl** [comment]
I had there 7 days, but I've changed to 10, do you think this was the problem? :/

**Comment by ElBananaa** [comment]
> I had there 7 days, but I've changed to 10, do you think this was the problem? :/

To be honest, I have no idea. This isn't normal, and if it takes so much time to load, it probably means that something's wrong. However, you're the first one to report this issue afaik.
You should wait for Kangarko to see this with him ^^

**Comment by kangarko** [comment]
Hey,

The only reason this shows up is that we're waiting for the MySQL database's response. 

Any time the database is called, such as in some commands or when you join the game, we start a connection to your database to pull data. Until these data is received and processed we block some actions from the plugin and show this message instead to prevent data corruption.

So it's either your database taking too long to respond sometimes or you have a large amount of data that take time to process. 

How big is your database and ChatControl tables?

**Comment by bobhenl** [comment]
![image](https://user-images.githubusercontent.com/18662086/112176516-73730480-8bf8-11eb-9f37-bc502c6caf6a.png)

Is this enough?

And couldn't you at least allow executing commands or something?

**Comment by ElBananaa** [comment]
> ![image](https://user-images.githubusercontent.com/18662086/112176516-73730480-8bf8-11eb-9f37-bc502c6caf6a.png)
> 
> Is this enough?
> 
> And couldn't you at least allow executing commands or something?

That's probably something on your end.
I don't have a such issue with a 1,6Gb database.
I'm using MariaDB-1:10.5.9 on debian buster, the server database is hosted on the same dedicated server, and I'm using adminer (It's not really useful)

**Comment by ghost** [comment]
maby you database is overloaded in some way? are you hosting several databases on the same mysql instance? (i've seen something like this on mcmmo, but i dont now if this actually has anything to do with this)

        # This setting is the max simultaneous mysql connections allowed at a time, needs to be
        # high enough to support multiple player logins in quick succession
        MaxConnections:
            Misc: 30
            Load: 30
            Save: 30
        # This setting is the max size of the pool of cached connections that we hold available
        # at any given time
        MaxPoolSize:
            Misc: 10
            Load: 20
            Save: 20

**Comment by kangarko** [comment]
To my understanding this is caused by your database taking too long to respond for our query. Other plugins should also have the same problem however they are not blocking anything in the game because they have a different nature. 

Try renaming the ChatControl database to something else, this will wipe your 4000+ players' data but it will reset the overhead so it should load faster.

**Comment by bobhenl** [comment]
But btw any errors in the console from other plugins due to the database, so I'm not really sure if other plugins have a problem too.

Just a note: May when players have default channel, may it's not needed to save into database. Or other values if they're not set and they're empty like {}. Why have there all players even if they didn't change anything?

Maybe the option to exclude data that didn't change? To save just data with some changes and not default values?

**Comment by kangarko** [comment]
Other plugins do not report the database taking too long, not sure if I know of a plugin that does it.

We need to store all channels to properly maintain cross-server sync, not all networks are created equal.

**Comment by bobhenl** [comment]
Mhm still happening :/ Maybe option to still allow executing commands or something? Or something to speed it up

**Comment by kangarko** [comment]
This would cause more harm than good because it would effectively enable players to violate rules, PM players they ignore etc. etc. since we have no information about them at that point.

**Comment by kangarko** [comment]
I will be looking into an alternative solution but my time is limited... we need to fix the offline/online problem where users are reported as online first. Your problem is not an issue in itself because your database is simply not returning queries in time, but I can have a look later — until then consult your hosting or try another mysql hosting just to test this.
