### ISSUE TITLE
1.16.5: Disable messages about join to channel 

### ISSUE THREAD

**Issue by div2005** [kangarko/ChatControl#816]
Hi, is it possible to disable or hide this messages? It sends when player joining after restart to the server (autoenable permissions are set for him).
```
[+] Player nickName has joined 'Global' channel.
[+] Player nickName has joined 'Local' channel.
```

**Comment by ElBananaa** [comment]
> Hi, is it possible to disable or hide this messages? It sends when player joining after restart to the server (autoenable permissions are set for him).
> 
> ```
> [+] Player nickName has joined 'Global' channel.
> [+] Player nickName has joined 'Local' channel.
> ```

Hey!
You can disable this message by chaging `Notification: '&8[&2+&8] &7Player {player} has joined ''{channel}'' channel.'` to
`Notification: ''` in your localization file.

**Comment by div2005** [comment]
It won't send empty message?

**Comment by ElBananaa** [comment]
> It won't send empty message?

it shouldn't. If the message is empty, it won't send anything.
If it send an empty message, try with `Notification: 'none'`

**Comment by div2005** [comment]
ok, i'll try this, thanks

**Comment by div2005** [comment]
It works
