### ISSUE TITLE
1.16.5: Bungeed Chat Issue

### ISSUE THREAD

**Issue by Revanrose6** [kangarko/ChatControl#817]
Minecraft Version: 1.16.5
MySQL: True
BungeeCord: True

One of my players has reported being unable to change chat channels and is receiving this response. He can talk in the channel he is already in:
https://cdn.discordapp.com/attachments/696934996329365506/822951027422527509/2021-03-20_17.53.01_2.png

We just updated to the newest chat control red plugin. No one else has reported an issue and there doesn't seem to be anything showing up in the console on the bungee side or the server's side.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6176497/debug.zip)

**Comment by kangarko** [comment]
Did the player change his username with Mojang?

**Comment by Revanrose6** [comment]
No he did not

**Comment by Revanrose6** [comment]
The server and entire server network have restarted multiple times since it started and they are still unable to change channels.

**Comment by kangarko** [comment]
Is your server on cracked mode or online?

**Comment by Revanrose6** [comment]
Online and bungeed

**Comment by kangarko** [comment]
I believe this will be fixed, if not comment on https://github.com/kangarko/ChatControl-Red/issues/309
