### ISSUE TITLE
1.16.4: How to make per world group chat?

### ISSUE THREAD

**Issue by Manfruity** [kangarko/ChatControl#818]
I cant seem to figure out how to setup per world group chat any help will be appreciated.

Minecraft Version: 1.16.4
MySQL: true/false
BungeeCord: false

**Comment by ElBananaa** [comment]
> I cant seem to figure out how to setup per world group chat any help will be appreciated.
> 
> Minecraft Version: 1.16.4
> MySQL: true/false
> BungeeCord: false

Hey!
Please provide us your `/chc debug` output file so we can see what you tried until now.

**Comment by kangarko** [comment]
Very simply, create a channel you want to use for that in Channels section of settings.yml, then set the Range option there to "*".

You can also connect multiple worlds with the Range_Worlds option as shown below:

![a](https://i.imgur.com/rpLWfdl.png)

More info in the wiki.
