### ISSUE TITLE
1.16.5. How to get the variable for my prefix to use it in tablist?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#819]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

My channel's prefix is defined in formats/chat.yml:
![image](https://user-images.githubusercontent.com/32280863/111910615-c8811000-8a6a-11eb-80f6-0dd5f552c59d.png)

What variable do I put into tablist format (in the settings.yml) so that the prefix gets displayed in the tablist providing a player has a certain permission?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: false
> 
> My channel's prefix is defined in formats/chat.yml:
> ![image](https://user-images.githubusercontent.com/32280863/111910615-c8811000-8a6a-11eb-80f6-0dd5f552c59d.png)
> 
> What variable do I put into tablist format (in the settings.yml) so that the prefix gets displayed in the tablist providing a player has a certain permission?

Hey!
Unfortunately, as far as I know, you can't do what you're trying to do. I might be wrong, but I think the plugin doesn't have any feature for that.
I'll leave your issue so Kangarko could take a look at it anyways.

**Comment by nikitushu2** [comment]
Yeah, if it is not possible then I'd like to suggest adding this feature as it's quite useful.

**Comment by kangarko** [comment]
Thanks for your suggestion.

Right now we only alter tab when you create yourself a custom prefix, nick or suffix and have Tag.Change_Displayname on true but we do not alter tab based on a format's part.
