### ISSUE TITLE
ChatControl Task

### ISSUE THREAD

**Issue by Fallenclocks** [kangarko/ChatControl#82]
Every once and a while I receive this error in console: http://pastebin.com/t2uPGMvh

I am not sure what is causing this. Here is an image of my plugins: http://gyazo.com/67fb273346b54212735d47dd64bc9b49

I am thinking that it is due to me having an announcer plugin along side chatcontrol; although, I have disabled the auto messages on chatcontrol.

**Comment by kangarko** [comment]
The auto msgs are still enabled in chatcontrol, make sure you have Messages.Timed.Enabled to false
