### ISSUE TITLE
Customizations

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#82]
Hey, the /ch channels message is nice customizable, but i have some more improvements

1. Make the help for each command individual editable like here: https://hastebin.com/itutohocem.sql
And that for every command. so i can customize all the help messages individual.

2.
Make channel mode translatable. on channel list there is channelname (write)
Make it so: https://hastebin.com/itutohocem.sql

**Comment by kangarko** [comment]
Sorry, but this is not possible, because these messages are built on-the-fly and will change on every update. Then you 'd have to change your localization files manually on each update and people would have outdated information.

**Comment by DevJoey** [comment]
can yo then please make the help header customizable? If a player types /ch j this ugly help menu will pop up, which looks not like my server design.

**Comment by kangarko** [comment]
I understand, but all help files are made on the fly so we can't build the from localization files. Can you post a screen of your server style? I see what I can do

**Comment by DevJoey** [comment]
I dont mean the help for chatcontrol. i mean the help for commands player can use. /ch help 

Screen of my server: http://prntscr.com/vll6ut

**Comment by kangarko** [comment]
Yeah I understand. Well you can just create a rule in rules/command.rs that will match /channel help and print custom help messages for your players then.
