### ISSUE TITLE
1.16.5 Some error when coppied folder on another part on bungee 

### ISSUE THREAD

**Issue by lalalalajciyiy** [kangarko/ChatControl#820]
Hello,
Can you help me whats wrong here? I just coppied folder of chatcontrolred and pasted it on another part on my bungee and got this error..

https://pastebin.com/KsRbXi29

https://pastebin.com/yx3PLAW5

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Thanks,
Lukas

**Comment by ElBananaa** [comment]
> Hello,
> Can you help me whats wrong here? I just coppied folder of chatcontrolred and pasted it on another part on my bungee and got this error..
> 
> https://pastebin.com/KsRbXi29
> 
> https://pastebin.com/yx3PLAW5
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Thanks,
> Lukas

Hey!
Copying folder without runing checks after isn't the best idea. First of all, make sure the plugin version is the same on both servers (And if it ain't, make sure to update your plugins/dependencies). Once this is done, also make sure both servers have a different and right `server-name` key in your `server.properties` (Which means no spaces, only english characters, no accents, and no symbols).

If the issue perists after that, please upload your `/chc debug` output file.

**Comment by kangarko** [comment]
It says "Unknown action named: PLAYERS_SYNC" meaning your BungeeControl Red is outdated, because such packet has since been changed. @ElBananaa if this happens they just need to update BungeeControl Red :)
