### ISSUE TITLE
1.16.5: Making discord users appear identical via SRV integration

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#823]
---
name: Question
about: Ask a question about the plugin.
title: '1.16.5: Making discord users appear identical via SRV integration'
labels: 
assignees: ''

@@ -12,6 +12,12 @@ Please READ this: https://github.com/kangarko/ChatControl-Red/issues/515
BEFORE submitting this issue otherwise no support will be given.
-->

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hi there, I cannot use the standard DiscordSRV variables throught the chatcontrol red integration, and was hoping to make discord users appear identical to ingame users.
Is there any way to use the native % based variables or achieve an identical message format?

Thanks,
Jamie

(I think I may have submitted this in the incorrect place before as I'm unfamiliar with this submission system)

**Comment by ElBananaa** [comment]
> name: Question
> about: Ask a question about the plugin.
> title: '1.16.5: Making discord users appear identical via SRV integration'
> labels:
> assignees: ''
> 
> @@ -12,6 +12,12 @@ Please READ this: #515
> BEFORE submitting this issue otherwise no support will be given.
> -->
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Hi there, I cannot use the standard DiscordSRV variables throught the chatcontrol red integration, and was hoping to make discord users appear identical to ingame users.
> Is there any way to use the native % based variables or achieve an identical message format?
> 
> Thanks,
> Jamie
> 
> (I think I may have submitted this in the incorrect place before as I'm unfamiliar with this submission system)

Hey!
I'm not sure to completely understand what you mean. If you're talking about placeholders, this is normal. As far as I know, there's no way for us to completely support DiscordSRV variables since they're internal. If you with to use these variables, I think you'll have to use DiscordSRV chat formatting. I'm not completely sure about this tho, so I'll leave your issue open so Kangarko could take a look at it. :)

**Comment by ghost** [comment]
Thank you very much, hopefully there's a way of sorting this :)

**Comment by kangarko** [comment]
Hey!

We support Discord username linking so if you use that feature in DiscordSRV and on Discord then you should see identical player names. If not then you'll have to stick with the %player% variable that shows the playername on Discord which may or may not be equal to his Minecraft username.
