### ISSUE TITLE
1.16.5: Javascript variable generating color codes? 

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl#826]
Minecraft Version: 1.16.5
MySQL: true/**false**
BungeeCord: true/**false**

**What I want to create:** 
I want to make a command only accessible to claimowners, therefore I created a variable {isClaimOwner} which is supposed to return a boolean that I can use as a condition in rules.

**What is the problem:**
I'm getting errors when using the variable. 'expected an operand but...' (see later)

**My Variable config:**

```
Type: FORMAT

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand"
Key: isClaimOwner

# The value the key will be replaced to.
# This uses JavaScript and must return a boolean value.
Value: |-
    isClaimOwner();  
    function isClaimOwner() {
        var claimOwner = "{griefprevention_currentclaim_ownername}";
        var playerName = "{player_name}";
        if (claimOwner == playerName) {
        return true;
        }
        return false;
    }
```

**My rule in which I use the variable:¨**
```
match (^/claimexplosion)
dont verbose
ignore script {isClaimOwner}
then warn &cEnkel de Claimowner kan Explosies aan/uit zetten
then deny
```
**The error:**

[VariableError.txt](https://github.com/kangarko/ChatControl-Red/files/6188240/VariableError.txt)

**Comment by TheIntolerant** [comment]
I believe this has been sorted.

**Comment by kangarko** [comment]
Thanks, assuming this got sorted on Discord, but let me know below if you still need assistance.
