### ISSUE TITLE
1.16.5: item2chat compatibility

### ISSUE THREAD

**Issue by Syndr4** [kangarko/ChatControl#828]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hi, i have a problem with CCR and Item2Chat.
When i put the prefix from the Item2Chat the message dont send in the chat, any solution for that?
I speaked with the item2chat dev and he say that: https://i.imgur.com/jH96cCm.png

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Hi, i have a problem with CCR and Item2Chat.
> When i put the prefix from the Item2Chat the message dont send in the chat, any solution for that?
> I speaked with the item2chat dev and he say that: https://i.imgur.com/jH96cCm.png

Hey!
You could try to play around with the `Chat_Listener_Priority` in your `settings.yml` file.
However, keep in mind that chatcontrol already has a variable system and a premade item variable that probably works the same than Item2Chat.

**Comment by Syndr4** [comment]
I've tried lowering the priority and it still doesn't work :(

**Comment by kangarko** [comment]
Sorry, these kinds of plugins are and will always be incompatible because we handle chat in our own way.
