### ISSUE TITLE
1.16.5: Setting group regex using # sign doesn't properly set the group param $2

### ISSUE THREAD

**Issue by myiume** [kangarko/ChatControl#829]
I'm trying to add the following command alias as a rule:

match (\/hexcolor) (.*)
dont verbose
then command chc color $2
then deny

but the param is not properly being sent if it contains a # at the beginning.

Could you help me figure out how to properly set this?

Thanks.

Minecraft Version: 1.16.5
MySQL: true/
BungeeCord: true/

**Comment by kangarko** [comment]
Unfortunately the system has been designed to replace & and hex colors in "then command" operator, we're not planning to do a rewrite right now.
