### ISSUE TITLE
Emoji ItemsAdder in channel broken

### ISSUE THREAD

**Issue by Tylwen** [kangarko/ChatControl#830]
Hello,
ItemsAdder emojis (image) does not work in channels.

When I deactivate the channels, they work again.

Possible to fix this problem?

I am using ChatControlRed 10.3.1 and ItemsAdder 2.2.5.
Minecraft Paper 1.16.5 - 565

**Comment by ElBananaa** [comment]
> Hello,
> ItemsAdder emojis (image) does not work in channels.
> 
> When I deactivate the channels, they work again.
> 
> Possible to fix this problem?
> 
> I am using ChatControlRed 10.3.1 and ItemsAdder 2.2.5.
> Minecraft Paper 1.16.5 - 565

Hey!
This is due to the fact that ItemsAdder is trying to send the emojis on the default chat system, which is overwritten by chatcontrol-red. You should probably ask the ItemsAdder dev to add support for ChatControl-red.

**Comment by Tylwen** [comment]
LoneDev — Aujourd’hui à 12:33
probably chatcontrol is intercepting packets of chat and messing with them.. if i can't see the source of the plugin i can't do much

Tylwen — Aujourd’hui à 13:17
https://github.com/kangarko/ChatControl-Red/wiki/API
It's not sufficient ? @LoneDev

LoneDev — Aujourd’hui à 14:47
since their api is not free I can't do much.
ItemsAdder API is free to use https://itemsadder.plugin.ga/developers/java-api they just have to call this method to apply emojis on the message.
FontImageWrapper.replaceFontImages(player, message)

If they support PlaceholderAPI they have no excuse to avoid supporting also my placeholders

**Comment by ElBananaa** [comment]
> LoneDev — Aujourd’hui à 12:33
> probably chatcontrol is intercepting packets of chat and messing with them.. if i can't see the source of the plugin i can't do much
> 
> Tylwen — Aujourd’hui à 13:17
> https://github.com/kangarko/ChatControl-Red/wiki/API
> It's not sufficient ? @lonedev
> 
> LoneDev — Aujourd’hui à 14:47
> since their api is not free I can't do much.
> ItemsAdder API is free to use https://itemsadder.plugin.ga/developers/java-api they just have to call this method to apply emojis on the message.
> FontImageWrapper.replaceFontImages(player, message)
> 
> If they support PlaceholderAPI they have no excuse to avoid supporting also my placeholders

Hey!
Thanks for the infos!
I guess you'll have to wait for Kangarko to take a look at your issue.
If ItemsAdder developper wants to get access to ChatControl-Red source code, he should send an email to support@mineacademy.org

**Comment by kangarko** [comment]
Thanks, yeah if they reach out to our email address I will add them however we're not planning on adding support for their system right now.

**Comment by Tylwen** [comment]
I'd prefer if they integrate itemsadder emojis replacement directly into their code, it's just one method:
FontImageWrapper.replaceFontImages(player, message).
API is freely available here as maven package: https://itemsadder.plugin.ga/developers/java-api
