### ISSUE TITLE
1.16.5: Operator 'then deny silently' not functioning correctly in ChatControlRed-Operated PMs

### ISSUE THREAD

**Issue by SmashbrosThe3rd** [kangarko/ChatControl#831]
Minecraft Version: 1.16.5
MySQL: True
BungeeCord: True

Hello. I work with ChatControlRed on the server I'm staff on and I'm encountering an issue regarding one of the operators not functioning correctly through PMs operated by ChatControlRed. The operator in mind is 'then deny silently'. Below is the console message provided when my advertisement filter is triggered in a PM to a user:

```
[23:05:36 INFO]: SmashbrosThe3rd issued server command: /r (user) Hi! Don't forget to watch videos at http://www.youtube.com/
[23:05:36 INFO]: *--------- Rule match (global/2) for SmashbrosThe3rd ---------
[23:05:36 INFO]: MATCH: [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o)\b
[23:05:36 INFO]: CATCH: /r (user) Hi! Don't forget to watch videos at http://www.youtube.com/
[23:05:36 INFO]: Original message cancelled silently.
[23:05:36 INFO]: [pm] SmashbrosThe3rd -> (user): (user) Hi! Don't forget to watch videos at http://www.youtube.com/
[23:05:36 INFO]: [ChatControlRed 10.3.1] Command /r (user) Hi! Don't forget to watch videos at http://www.youtube.com/ took 21.6 ms
```

The plugin states it cancelled the message but it still sends the PM with the URL in my testing (through the /msg & /r commands). It functions this way in Private Messages but it also works in other servers connected through a BungeeCord network through MultiChat if published in regular game chat, though I'm assuming this cannot be solved because of the way the ChatControlRed plugin functions and how MultiChat sees the message sent only to the sender in console and proceeds to send it to everyone on the other MC servers.

I am hoping that this issue is solvable through the PM system your plugin provides but I understand if it cannot be solved because /msg & /tell are built-in commands in Minecraft. (Maybe this could be solved using a custom messaging command instead...?)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: True
> BungeeCord: True
> 
> Hello. I work with ChatControlRed on the server I'm staff on and I'm encountering an issue regarding one of the operators not functioning correctly through PMs operated by ChatControlRed. The operator in mind is 'then deny silently'. Below is the console message provided when my advertisement filter is triggered in a PM to a user:
> 
> ```
> [23:05:36 INFO]: SmashbrosThe3rd issued server command: /r (user) Hi! Don't forget to watch videos at http://www.youtube.com/
> [23:05:36 INFO]: *--------- Rule match (global/2) for SmashbrosThe3rd ---------
> [23:05:36 INFO]: MATCH: [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o)\b
> [23:05:36 INFO]: CATCH: /r (user) Hi! Don't forget to watch videos at http://www.youtube.com/
> [23:05:36 INFO]: Original message cancelled silently.
> [23:05:36 INFO]: [pm] SmashbrosThe3rd -> (user): (user) Hi! Don't forget to watch videos at http://www.youtube.com/
> [23:05:36 INFO]: [ChatControlRed 10.3.1] Command /r (user) Hi! Don't forget to watch videos at http://www.youtube.com/ took 21.6 ms
> ```
> 
> The plugin states it cancelled the message but it still sends the PM with the URL in my testing (through the /msg & /r commands). It functions this way in Private Messages but it also works in other servers connected through a BungeeCord network through MultiMC if published in regular game chat, though I'm assuming this cannot be solved because of the way the ChatControlRed plugin functions and how MultiMC sees the message sent only to the sender in console and proceeds to send it to everyone on the other MC servers.
> 
> I am hoping that this issue is solvable through the PM system your plugin provides but I understand if it cannot be solved because /msg & /tell are built-in commands in Minecraft. (Maybe this could be solved using a custom messaging command instead...?)

Hey!
Thanks for reporting this issue.
I don't know if this is something intended, however I can tell you that ChatControl already has its own chat system, which also means it has its own private message system too. If you enabled the channel feature and the plugin pm feature in the config, then it probably means it's a bug.

I'll leave your issue open so Kangarko could take a look at it in the upcoming days.

**Comment by kangarko** [comment]
Hey!

Commands are built-in in a way that doesn't really make it possible for us to "fake" that the command has been executed and return the result without actually running the command.

Thus we only support the silent denial operator in the chat.
