### ISSUE TITLE
1.16.5 denzien chat triggers

### ISSUE THREAD

**Issue by SirAltF4** [kangarko/ChatControl#833]
im currently using CC pro and want to get CC red but I want to confirm this will work as its not working in CC pro, 
when trying to talk to npcs in Citizens using a denzien chat trigger when you don't have channels enabled it works fine and deltes the message but when I have a channel at first it was registering the chat for the npc but also sending it in chat, but now the npc isn't even detecting the chat and its only sending in chat, wondering what sort of support you have for denzien

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> im currently using CC pro and want to get CC red but I want to confirm this will work as its not working in CC pro,
> when trying to talk to npcs in Citizens using a denzien chat trigger when you don't have channels enabled it works fine and deltes the message but when I have a channel at first it was registering the chat for the npc but also sending it in chat, but now the npc isn't even detecting the chat and its only sending in chat, wondering what sort of support you have for denzien
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false

Hey!
As far as I know, the plugin doesn't support denizen now. You should probably ask Denizen developpers to implement support for ChatControl-red. Keep in mind that the channel features completely overwrite the default chat system, which means messages need to be sent on the channel when the feature is used.

**Comment by kangarko** [comment]
As banana explained, this is not supported because of how we override chat sending.
