### ISSUE TITLE
1.16.5: /channel join admin

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#834]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, something weird is happening for me this day.
![image](https://user-images.githubusercontent.com/18662086/112556078-bcc67e00-8dc9-11eb-97b5-7672c84f4dde.png)
When I use this command, the message above appears, but the message is still sent. 

But... when I want to use the whole channel, it doesn't join me there....
![image](https://user-images.githubusercontent.com/18662086/112556125-d10a7b00-8dc9-11eb-8c9e-3cff23a8d296.png)

Logs from proxy:
[logybungee.zip](https://github.com/kangarko/ChatControl-Red/files/6208385/logybungee.zip), should be in the latest here probably:
![image](https://user-images.githubusercontent.com/18662086/112556268-23e43280-8dca-11eb-89fb-2f7367820ce6.png)

on Survival isn't anything weird in log

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, something weird is happening for me this day.
> ![image](https://user-images.githubusercontent.com/18662086/112556078-bcc67e00-8dc9-11eb-97b5-7672c84f4dde.png)
> When I use this command, the message above appears, but the message is still sent.
> 
> But... when I want to use the whole channel, it doesn't join me there....
> ![image](https://user-images.githubusercontent.com/18662086/112556125-d10a7b00-8dc9-11eb-8c9e-3cff23a8d296.png)
> 
> Logs from proxy:
> [logybungee.zip](https://github.com/kangarko/ChatControl-Red/files/6208385/logybungee.zip), should be in the latest here probably:
> ![image](https://user-images.githubusercontent.com/18662086/112556268-23e43280-8dca-11eb-89fb-2f7367820ce6.png)
> 
> on Survival isn't anything weird in log

Hey!
Have you changed your username throught mojang recently?

**Comment by bobhenl** [comment]
No I have not, may there were Mojang servers down?

**Comment by ElBananaa** [comment]
> No I have not, may there were Mojang servers down?

Hey!
No, we're encountering this kind of issues with players changing their names throught mojang.
I guess you'll have to wait for Kangarko to take a look at your issue.

**Comment by kangarko** [comment]
Please set Debug to "bungee" on the next version and report the new "Checking if XXX" message when that happens again.

**Comment by kangarko** [comment]
I believe this will be fixed in the next release, if not comment on https://github.com/kangarko/ChatControl-Red/issues/309
