### ISSUE TITLE
1.16.5: Error?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#836]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I've got this error today in the console: https://pastebin.com/40WywyPW, probably on player join

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, I've got this error today in the console: https://pastebin.com/40WywyPW, probably on player join

Hey!
Thanks for reporting this issue!
It looks like this is an issue caused by a wrong usage of protocolLib in the PlayerCache class. I'm not sure tho, Kangarko will surely give you a better answer.

**Comment by kangarko** [comment]
Thanks, will get patched.
