### ISSUE TITLE
1.16.5: Bungee Join_message not displaying/Server not receiving Discord messages

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#837]
Not sure if debug includes bungee info, but here's what the config looks like: https://pastebin.com/GHDJYGLH
For some reason leave messages work great, but join messages aren't displaying in chat

I also have an issue with one of my servers not receiving messages sent in discord. I'm not getting any startup errors for chc or discordsrv, but I do get this console error when receiving a message from discord: https://pastebin.com/P3k5Fybg 

I suspect this one may be a user error but everything seems to be properly configured, hoping someone can make sense of the error log posted above

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6213570/debug.zip)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Regarding join messages not showing up, I am not sure if maybe BungeeTabListPlus is intefering here or perhaps PremiumVanish is blocking join messages in attempt to hide vanished players? Try with just ChatControl Red installed.

The Discord NPE will be fixed.

**Comment by ElBananaa** [comment]
> Regarding join messages not showing up, I am not sure if maybe BungeeTabListPlus is intefering here or perhaps PremiumVanish is blocking join messages in attempt to hide vanished players? Try with just ChatControl Red installed.
> 
> The Discord NPE will be fixed.

Just as a quick tip: I'm using PremiumVanish with CCR and it works flawlessly (i'm on a single server tho). And I'm using default priorities in both plugins.
