### ISSUE TITLE
1.16.5: unicode breaks filter due to ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#838]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Exception when a player uses arabic unicode.

Console:
https://pastebin.com/raw/tQZYL0mU
Error.log
https://pastebin.com/raw/S4bYYHNi

Something similar happens when emoticons are trying to be used like `:tableflip:`

After many errors, chat is no longer controlled and filtered!

Important to replicate this, is this rule:
```
match [^\u0000-\u007F]+
then replace
```
The `then replace` is important. When `then deny` it can't be reproduced.

**Comment by kangarko** [comment]
Thanks, solved!
