### ISSUE TITLE
1.16.5: "Unknown custom packet identifier: plugin:chcred" client log spam

### ISSUE THREAD

**Issue by ZeNinja864** [kangarko/ChatControl#839]
I followed through with the installation instructions for the BungeeCord installation of ChatControlRed on the GitHub wiki for my Waterfall proxy and servers and noticed upon connection to any servers behind the BungeeCord proxy, the client log was spammed with the text of:
`[Render thread/WARN]: Unknown custom packed identifier: plugin:chcred`

When I noticed this spam in my client log, I asked my other friend who was also logged in to the same server as me behind the BungeeCord proxy was instead getting the error of:
`[Render thread/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Unknown custom packet identifier: plugin:chcred`

These errors were displayed in our client logs upon us simply logging into the server and I decided to come to the issues section to see if there were any similar threads. I had a look at issues #346 and #415 and attempted some of the solutions proposed in those issue threads to see if items such as a plugin were causing the issue due to a conflict and raising Paper's packet incoming-packet-spam-threshold to 3000 from the default 300 would fix the issue but nothing stopped the error from occurring; I also removed all plugins from the server except for ChatControlRed, LuckPerms, and Vault and we still received the errors in our client logs. We do have a BungeeCord setup, as mentioned, and the only plugin on the proxy itself is the `BungeeControl-Red-3.3.1.jar`.

One thing I did notice about this error is that similar to #415, a fresh install of ChatControlRed both on the servers and Waterfall proxy did not cause the error to print to chat logs but, once the BungeeCord integration was enabled in the settings.yml config, the issues started printing to our client logs.

For this issue, I generated two debug.zip archives, the first one being after the fresh install with no errors being put to the client and the second one after the BungeeCord integration was enabled in the settings.yml.

Fresh install: https://drive.google.com/file/d/1Z2hUFXCdK_P9hYEvKULV7ntKaZepLFXT/view?usp=sharing
Bungee enabled: https://drive.google.com/file/d/1IWXh2FXeDDC2etwsvA2MtAEVASsF2jop/view?usp=sharing

Chatcontrol-red: 10.3.1
Minecraft Version: Paper 1.16.5 Build 570
MySQL: true
BungeeCord: true (Waterfall Build 403)

**Comment by kangarko** [comment]
Thank you, we send packet communication back and forth every 10 ticks to keep track of players connected through out the network. As long as you are not facing any actual malfunction in the game you can safely ignore this.
