### ISSUE TITLE
Enhancement: Add console action to packet.txt

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#84]
I recently discovered a situation where the use of `then console` at matching a specific packet would be quite useful.

Therefore I suggest to allow the use of `then console` at the packets.txt

If this is a part of the pro version already, never mind ;)

**Comment by kangarko** [comment]
I see, but it could lead to a race condition(s) where the console would send message to the player, which would again be caught by CHC and again in a circle, leading to a server froze. 

It will be added tonight.
Handle with care :)

**Comment by EvilOlaf** [comment]
Are other rules not also probably affected for leading into a race condition?
