### ISSUE TITLE
Custom deathmessage for lingering damage potions, damage potions and wither rose deathmessage

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl#840]
It would be fantastic if one could add death notifications for lingering damage potions, damage potions and wither rose deathmessage. The implementation of deep differentiation options would make the death notification system even more awesome.
I made the suggestion three months ago in ticket #323 and #324. At that time it was rejected because some major code changes are needed and a re-evaluation in a few months was promised. Has the time come for a major improvement of the death notification system or should we wait?

ChatControlRed 10.3.1
Minecraft Version: 1.16.5 Paper build 564
MySQL: true
BungeeCord: false

**Comment by kangarko** [comment]
Thanks for proposing this again, I'll pull this to our roadmap, no ETA at the moment

**Comment by TheoRetisch1** [comment]
Since the feature request is no longer in the routemap: Is this now possible 👍 and if so how?

**Comment by kangarko** [comment]
No, it was scrapped, the API does not support this (we literally see entity attack with no active potions on potion death: https://i.imgur.com/XzGNYvu.png) and I do not have time to code some complex workaround for this unfortunately.
