### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#842]
Hey, in the config there is an option to change the message, that gets sended, if a player use /chc (Alternative Header), it would be nice, if there a 2 messages. one, that gets sendet if the player has no chc.command.chc and the other if the player has the permission.

So i can send a simple no perms message on /chc if the player do not have perms and an other message if the player can use the /chc command.

**Comment by kangarko** [comment]
Thanks for your suggestion! However for that you can just create a custom rule in command.rs file
