### ISSUE TITLE
1.16.5: How do I disable the chat rules for specified worlds?

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#843]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hi there,

I'm trying to disable the swearing/URL filtering element of chat rules for specified worlds, how would I go about doing this please?

Thank you in advance!

**Comment by TheIntolerant** [comment]
Go into the ``groups.rs`` file in ``/rules`` and add ``ignore world <world name>``, to the group you wish to be ignored for that world. 

Example: 
``ignore world world_nether``

If I wanted to add say ``world_nether`` and ``world_the_end`` I would type this:
``ignore world world_nether|world_the_end``

EDIT:
If you haven't already, I highly recommend reading through, https://github.com/kangarko/ChatControl-Red/wiki/rules, to learn more about the operators that you can use in chat control rules.

**Comment by ElBananaa** [comment]
Hey!

@gone-incognito Thanks for answering them!
@Gadget135 Everything was said above. I'm closing this issue, but feel free to keep commenting down below or open a new one if you need anything else.
