### ISSUE TITLE
1.16.5: How do I disable the message which combines "Join: Leave_Reading & Success"

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#844]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

Hi there,

I'm trying to disable the channel join messages by setting the variables to none, however when setting two of the many variables (Leave_Reading and Success under the Join: category in messages_en.yml) it simply displays "nonenone".

I've tried to see if there is anywhere which calls and combines these into one message however cannot find where this is.

Thank you in advance

**Comment by TheIntolerant** [comment]
Hey there, I assume you have set them to ``none``, As the ``Success: `` & ``Leave_Reading:`` are displayed in one message, this would explain why it says ``nonenone``. 

To fix this, just set Leave_Reading & Success to ``''`` instead, of ``none``

**Comment by ElBananaa** [comment]
Hey!
Everything was said by @gone-incognito.
Closing this issue.
