### ISSUE TITLE
1.16.5: Disabling chat cooldown for specified worlds

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#846]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hi there,

How would I go about disabling the command cooldown for a specified world? Although I'd preferably only remove the cooldown for specific commands please.

Thank you in advance, also the support provided here has been unparalelled!

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Hi there,
> 
> How would I go about disabling the command cooldown for a specified world? Although I'd preferably only remove the cooldown for specific commands please.
> 
> Thank you in advance, also the support provided here has been unparalelled!

Hey!
As far as I know, this isn't possible right now.
I'll leave this ticket open, so Kangarko could take a look at it, and decides if he wants to potentially add this to the roadmap.

**Comment by TheIntolerant** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Hi there,
> 
> How would I go about disabling the command cooldown for a specified world? Although I'd preferably only remove the cooldown for specific commands please.
> 
> Thank you in advance, also the support provided here has been unparalelled!

Are you talking about the command delay or similarity checks? Anyway, I believe in your ``settings.yml`` file, under
```
    # Commands the player can type bypassing the Delay above. We check the command label
    # so if you put "/tell" there, "/tell ANYTHING" will be matched.
    #
    # Whitelist_Delay:
    #   - /spawn
    #   - /hello
    Whitelist_Delay: []
  ```
  OR
  ```
    # Commands the player can type bypassing the Similarity above. We check the command label
    # so if you put "/tell" there, "/tell ANYTHING" will be matched.
    #
    # Whitelist_Similarity:
    #   - /tell
    #   - /pm
    #   - /t
    #   - /w
    #   - /r
    Whitelist_Similarity: []
```
That should be what you are looking for. 
Similarity = prevents people from running the same command repeatedly.
Delay = How many seconds must the player wait between each command.

Another thing to know, you can turn these whitelist into a blacklist by adding ``'@blacklist'`` at the top of the list, for example, I don't care if people run most commands  repeatedly, but don't want specific commands being spammed like /tpa, so I did
```
Whitelist_Similarity:
    - '@blacklist'
    - '/tpahere'
    - '/tpa'
```
etc.

**Still, want to disable such checks in a specific world?** This is where ``Groups:`` in your settings file would come in. The group name can be anything, so in your case, the ``Groups:`` might look like this.
```
Groups:
  NoCommandCooldown:
    Command_Similarity: 0
    Command_Delay: 0 seconds
  staff:
    Max_Read_Channels: 5
    Message_Delay: 0 seconds
    Rejoin_Cooldown: 5 seconds
    Command_Similarity: 0
    Message_Similarity: 0
```
The permission for these groups is ``chatcontrol.group.<section>``, so I would then apply the permission node ``chatcontrol.group.NoCommandCooldown`` to the specific world I want such checks disabled in.

**Comment by ghost** [comment]
Thank you :)

**Comment by kangarko** [comment]
Thanks to @gone-incognito for all the help!

Also, for the simplest solution without creating any group, just give players "chatcontrol.bypass.delay" and/or "chatcontrol.bypass.similarity" permissions only on the given worlds, that will also do the trick!
