### ISSUE TITLE
1.16.5: Per World welcome messages (motd?)

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#847]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hi there,

I'm trying to do per world join and leave messages, although this area is especially scare for some reason. I've found a plugin which will achieve this, although it has extremely limited customisability and will still execute join/leave when players are vanished (and will even display join/leave when a player is being instantly teleported from their previous multiverse world).

I was hoping there'd be a way to achieve this in chat control red, potentially via the MOTD function? Any help with this is really appreciated.

Thank you

**Comment by ghost** [comment]
I'm now using the channel join messages as per world join/leave messages, however I cannot figure out how to show leave messages as the player is still "in" the channel when leaving. How would I go about doing it?

**Comment by ElBananaa** [comment]
> I'm now using the channel join messages as per world join/leave messages, however I cannot figure out how to show leave messages as the player is still "in" the channel when leaving. How would I go about doing it?

Hey!
Yes, this should be possible under `ChatControlRed/messages/join.rs` and `ChatControlRed/messages/quit.rs` with the `require world <worldname>` variable.
You can find infos about the different variables that can be used with the plugin on our wiki page: https://github.com/kangarko/ChatControl-Red/wiki/Rules#require-world-world-name

Here's an example with a join message :
```
group survival-join-message
require world survival
message:
- &6[&a+&6] &d{player}
```

You can combine this with a simple variable to check if the player is vanished, and if so, don't it won't send the message.

**Comment by ghost** [comment]
Would you happen to know how I'd combine this with a vanished variable please? I'm a noob when it comes to that side of things haha

**Comment by ElBananaa** [comment]
> Would you happen to know how I'd combine this with a vanished variable please? I'm a noob when it comes to that side of things haha

What's your vanish plugin?

**Comment by ghost** [comment]
SuperVanish

**Comment by kangarko** [comment]
We automatically not show these messages when the player is vanished.

Or you could just use the "ignore sender script" operator somewhere else to achieve the same.

```
group survival-join-message
ignore sender script {player_vanished}
require sender world survival
message:
- &6[&a+&6] &d{player}

```
