### ISSUE TITLE
Removing prefixes for single messages

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#85]
Every message in messages file, does start with a [X] or else, can this be configurable like %prefix_error% for each messages? i want some messages with other prefixes.

And to the closed issue for the help customization, it would be nice if it is a file called help-override, so i can override the original help with a custom one, for each command. so if the messages changes with an update, my override is still used and i can update it, if i want

**Comment by DevJoey** [comment]
And it would be nice, if i can create custom prefixes in the Prefix: section under messages

**Comment by kangarko** [comment]
Yes you can just set Prefix.Error to "" this will disable the [X] prefix etc.

You can customize your prefixes in that section too:

<img width="307" alt="Screenshot 2020-11-17 at 10 12 32" src="https://user-images.githubusercontent.com/1918426/99369994-6c8c5c00-28bd-11eb-9197-0914f2dfc48c.png">

**Comment by DevJoey** [comment]
if i add an own prefix to tha section, it will be removed on restart

**Comment by kangarko** [comment]
No they should remain changed, please use the next incoming version
