### ISSUE TITLE
Plugin cant be removed

### ISSUE THREAD

**Issue by ShankTank** [kangarko/ChatControl#85]
I removed the plugin from the ftp completely shut down my server started it back up but your fancy plugin decided to stick around and still do stuff I dont want it to do

**Comment by kangarko** [comment]
Make sure you don't have the plugin in update directory, which is a directory handled by Bukkit. When ChatControl downloads a new version, it is placed there and moved to plugins folder upon server restart.

**Comment by ShankTank** [comment]
No still dosent work I have deleted the chat control jar folder and the updater folder but still it on my server

**Comment by kangarko** [comment]
Shut down the server first. Make sure it is completely shut down.
Then do a deep search and remove every track of chatcontrol.

Personally, I never had any issue like that, what I can tell is that either you didn't removed it properly and/or there was some other mistake taken, or, it is also possible, that someone is trolling you. Did you saw any other uncommon behaviour apart from that?

If you are using bungee, do you have some synchronisation enabled that automatically install one certain plugin over your servers? I have 0% experience running bungee so if that is the case I can't help you.

**Comment by ShankTank** [comment]
Never mind its was no cheat plus is causing it but didnt block spam until i added your plugin thanks for the help

**Comment by kangarko** [comment]
So the problem is solved? I still don't understand how NCP would not allowed this plugin to be removed.
