### ISSUE TITLE
1.16.5: Bungeecord Questions

### ISSUE THREAD

**Issue by ZNChano** [kangarko/ChatControl#851]
I have just purchased ChatControl Red and I am wondering what features it offers for bungeecord as I did not see much info on that in the store page. 
Also, do I need to add chatcontrol red to the proxy, hub, and skyblock (for example)? or just the hub and skyblock?
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> I have just purchased ChatControl Red and I am wondering what features it offers for bungeecord as I did not see much info on that in the store page.
> Also, do I need to add chatcontrol red to the proxy, hub, and skyblock (for example)? or just the hub and skyblock?
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
You can find bungee features under this link: https://github.com/kangarko/ChatControl-Red/wiki/BungeeCord
Regarding the installation, put ChatControl-Red jar file on each server, and put BungeeControl-Red jar file on the proxy.

**Comment by ElBananaa** [comment]
> I have just purchased ChatControl Red and I am wondering what features it offers for bungeecord as I did not see much info on that in the store page.
> Also, do I need to add chatcontrol red to the proxy, hub, and skyblock (for example)? or just the hub and skyblock?
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
Do you need anything else?
May I close this issue?
