### ISSUE TITLE
1.16.5: I can not enter the chat in read mode

### ISSUE THREAD

**Issue by Toki-teki** [kangarko/ChatControl#852]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hello. I gave access to all players for chatcontrol.channel.join.bungee.read
But the channel is not displayed in the list
![2021-03-30_21 43 28](https://user-images.githubusercontent.com/74260160/113040042-008dfe80-91a1-11eb-973f-cee65ef5c7ad.png)

**Comment by Toki-teki** [comment]
How to fix it?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hello. I gave access to all players for chatcontrol.channel.join.bungee.read
> But the channel is not displayed in the list
> ![2021-03-30_21 43 28](https://user-images.githubusercontent.com/74260160/113040042-008dfe80-91a1-11eb-973f-cee65ef5c7ad.png)

Hey!
Are you sure that the channel currently exists?
Could you please provide us your `/chc debug` output file?

I can't remember if there's a `chatcontrol.channel.join` permission, however, you can give it a try.

**Comment by Toki-teki** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6238366/debug.zip)

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6238366/debug.zip)

Thanks!

From what I see, you're using an outdated version of chatcontrolred. Please update to the latest version and try again.

**Comment by Toki-teki** [comment]
![2021-04-01_20 41 46](https://user-images.githubusercontent.com/74260160/113333137-bf295a80-932a-11eb-9c35-201a470eafde.png)
no. Bungee channel is not available
[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/6245414/debug.1.zip)

**Comment by ElBananaa** [comment]
Alright, try giving yourself these permissions: `chatcontrol.channel.join.bungee.read` `chatcontrol.channel.autojoin.bungee.read`.
Also, from what I can see on your screenshot, you were in this channel, then left it, why?

Finally, I think that there used to be an issue with UltraPermissions not registering correctly the permissions (I'm not sure tho).
Would be cool if you could try with another perm plugin such as LuckPerms, because I can't reproduce this on my end.

**Comment by Toki-teki** [comment]
![2021-04-02_19 19 02](https://user-images.githubusercontent.com/74260160/113433688-5dc7c100-93e8-11eb-978f-5d116fb220ec.png)
![2021-04-02_19 19 13](https://user-images.githubusercontent.com/74260160/113433695-5ef8ee00-93e8-11eb-99c7-6128ca6d4356.png)
Default group have this permissions.
It's not UPerms problem. 
LuckPerms had the same problem

**Comment by Toki-teki** [comment]
--- Also, from what I can see on your screenshot, you were in this channel, then left it, why?
I did this to demonstrate that the desired channel does not appear in the list of available ones. But it is possible to enter the channel using the command "/channel join bungee". But I don't want players to have to memorize extra commands.

I think I might have to create a separate format for displaying channels. Can I turn off the /ch command to create it myself? In the Rules file

**Comment by ElBananaa** [comment]
> --- Also, from what I can see on your screenshot, you were in this channel, then left it, why?
> I did this to demonstrate that the desired channel does not appear in the list of available ones. But it is possible to enter the channel using the command "/channel join bungee". But I don't want players to have to memorize extra commands.
> 
> I think I might have to create a separate format for displaying channels. Can I turn off the /ch command to create it myself? In the Rules file

This shouldn't be necessary. I think it's an issue from the plugin. Weird thing is that it doesn't happen on my side. I guess i'm missing something, but I don't really know what tho.

**Comment by Toki-teki** [comment]
Another question. Where can I change the format of posts in Discord?

**Comment by Toki-teki** [comment]
![image](https://user-images.githubusercontent.com/74260160/113443875-755c7500-93fb-11eb-84e6-dfa01bf83499.png)
i need to add placeholders on discord

**Comment by ElBananaa** [comment]
> --- Also, from what I can see on your screenshot, you were in this channel, then left it, why?
> I did this to demonstrate that the desired channel does not appear in the list of available ones. But it is possible to enter the channel using the command "/channel join bungee". But I don't want players to have to memorize extra commands.
> 
> I think I might have to create a separate format for displaying channels. Can I turn off the /ch command to create it myself? In the Rules file

Hey!
Soo, quick update, I just noticed what could be the cause of your issue.
Could you try increasing `Max_Read_Channels:` to `4` in chc-red settings file? Then try again.

**Comment by Toki-teki** [comment]
![2021-04-03_08 51 57](https://user-images.githubusercontent.com/74260160/113469894-de72d580-9459-11eb-8a69-5dc42f68d407.png)
Not work 🤔

**Comment by Toki-teki** [comment]
![2021-04-03_09 02 40](https://user-images.githubusercontent.com/74260160/113470067-5f7e9c80-945b-11eb-834c-419640d34add.png)
/ch list

**Comment by Toki-teki** [comment]
If the player has access to chatcontrol.channel.join.bungee.write then everything is displayed correctly. But I only want to read
![2021-04-03_09 16 47](https://user-images.githubusercontent.com/74260160/113470325-79b97a00-945d-11eb-83f1-195d9e770def.png)

**Comment by Toki-teki** [comment]
Can I do this?
My way doesn't work

match ^(\!)(.*)
then command ch send global $2
dont verbose
then deny

match ^(\!!)(.*)
then command ch send bungee $2
dont verbose
then deny

**Comment by Toki-teki** [comment]
Interesting. I swapped and it works the way I wanted


match ^(\!!)(.*)
then command ch send bungee $2
dont verbose
then deny

match ^(\!)(.*)
then command ch send global $2
dont verbose
then deny

**Comment by ElBananaa** [comment]
> Interesting. I swapped and it works the way I wanted
> 
> match ^(!!)(.*)
> then command ch send bungee $2
> dont verbose
> then deny
> 
> match ^(!)(.*)
> then command ch send global $2
> dont verbose
> then deny

Hey!
This is due to the fact that the plugin reads the rules files from the top, to the bottom, so top rules have priority over bottom rules.

Regarding the channel issue, that's really weird. Since I can't reproduce this under a single server, I guess it's somehow related to Bungee. Let's wait for Kangarko so he could take a look at your issue. :)

**Comment by Toki-teki** [comment]
ok

**Comment by kangarko** [comment]
Do operators or people with "*" permission see this bungee channel? Have you installed it on every server on your network?

**Comment by Toki-teki** [comment]
yes, the operators see.
yes, installed on all servers

**Comment by Toki-teki** [comment]
the settings are the same on all servers

**Comment by kangarko** [comment]
So sorry for a late answer! Please try giving your players these permissions:

- chatcontrol.channel.join.bungee.*
- chatcontrol.channel.join.bungee
- chatcontrol.channel.join

**Comment by Toki-teki** [comment]
chatcontrol.channel.join.bungee.* 

I do not need the player to be able to enter this channel with the "write" mod. Therefore, this permission is not suitable

my permissions list:

- chatcontrol.channel.join
- chatcontrol.channel.join.bungee
- chatcontrol.channel.autojoin.bungee.read
- chatcontrol.channel.join.bungee.read
- chatcontrol.channel.autojoin.bungee.read
- chatcontrol.channel.leave.bungee
- chatcontrol.channel.leave

**Comment by kangarko** [comment]
So sorry I completely missed that, the system only showed channels you had WRITE permission for, not READ. This will get patched.
