### ISSUE TITLE
1.16.5 - Set up staff chat (admin channel) to be readable in other channel?

### ISSUE THREAD

**Issue by cades66** [kangarko/ChatControl#854]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hiya, I have a super simple question. It's quite inconveniencing for my mods to have to be told to /ch join admin every time I need to tell them something - I was wondering if it's possible for my staff to be in the main chat (in this case, global channel) yet ALSO see the admin channel. Everyone has the permission chatcontrol.channel.autojoin.global.write, so they can all talk in the global chat.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hiya, I have a super simple question. It's quite inconveniencing for my mods to have to be told to /ch join admin every time I need to tell them something - I was wondering if it's possible for my staff to be in the main chat (in this case, global channel) yet ALSO see the admin channel. Everyone has the permission chatcontrol.channel.autojoin.global.write, so they can all talk in the global chat.

Hey!
Yes, this is currently possible, simply give them the permission `chatcontrol.channel.autojoin.global.write` and `chatcontrol.channel.autojoin.staffchat.read` (Don't forget to replace `staffchat` with the right channel.
Once this is done, place this inside your `rules/chat.rs` : 
```
 Send messages starting with "$" to staff channel
match ^(\$)(.*) # <-- Replace the $ with anything you want
then command channel send staffchat $2 <-- Replace the `staffchat` with your current staff channel (Don't touch the `$2`)
then deny
dont verbose
```
(Once again, don't forget to replace `staffchat` with your current staff chat name. You cal also replace the $ with another symbol)

**Comment by cades66** [comment]
It seems that this still isn't working @ElBananaa - I cannot get my moderator to see the admin channel, however the $ thingy works.

https://media.foxedin.xyz/ss/firefox_sIcgcY6YA0.png
https://media.foxedin.xyz/ss/sublime_text_qfMW00Cane.png

^ Please right click and open in new tab, cloudflare is mad otherwise.

**Comment by ElBananaa** [comment]
> It seems that this still isn't working @ElBananaa - I cannot get my moderator to see the admin channel, however the $ thingy works.
> 
> https://media.foxedin.xyz/ss/firefox_sIcgcY6YA0.png
> https://media.foxedin.xyz/ss/sublime_text_qfMW00Cane.png
> 
> ^ Please right click and open in new tab, cloudflare is mad otherwise.

Hey!
They must manually join the channel in read mode. It'll fix your issue
