### ISSUE TITLE
1.16: Custom command -> format response

### ISSUE THREAD

**Issue by tomhula** [kangarko/ChatControl#856]
Minecraft Version: 1.16

Hello, is it somehow possible, that if you type custom command, it would answer you with a format?

example:

`/rules`
would send you a format called "Rules".

thanks in advance.

**Comment by ElBananaa** [comment]
Hey!
From what I know, and what's written on the wiki, you can use `then notify <permission> <message or format>` (More informations about this on the wiki page: https://github.com/kangarko/ChatControl-Red/wiki/Rules#then-notify-permission-message-or-format) under your command rule. However, this will send the message to every user with the specified permission.

You could also give a try to `then warn <message or format>`, however, I don't know if it'll work.

**Comment by tomhula** [comment]
Ok, exactly what I was looking for, thanks :)

**Comment by TheIntolerant** [comment]
I can confirm ``then warn <message or format>`` will work to use a format.

If you wish to use something ``then notify <permission> <message or format>`` but don't want the message to be sent to all people with that perm, you can always add the following ``require perm <permission> [message]`` then add ``then warn <message or format>``
So the rules looks something like
```
match ^\/rules\b
require perm server.rules
then warn Rules
```
If you find you are getting conflicts with a plugin that uses /rules, just add ``then deny`` to the rule, to prevent any conflicts. Also in that example, I made the permission node ``server.rules`` for /rules.

Also you can do 
```
match ^\/rules\b
require perm server.rules
then warn &6Server Rules:
then warn &e1) Do not spam
then warn &e2) Do not swear
...
```
etc

Butttt. you can probably make it look nicer using formats :P
So just "then warn (format name)"

**Comment by tomhula** [comment]
Ok, thanks, I'll try it.
