### ISSUE TITLE
The delete queue issue

### ISSUE THREAD

**Issue by fredagsguf** [kangarko/ChatControl#857]
The delete queue issue, is still there even though it says its fixed..

![image](https://user-images.githubusercontent.com/46964809/113220137-f3494080-9282-11eb-968a-6dec238d4302.png)

![image](https://user-images.githubusercontent.com/46964809/113220180-05c37a00-9283-11eb-9e99-4e20783fab24.png)

![image](https://user-images.githubusercontent.com/46964809/113220208-14119600-9283-11eb-931d-c2a298aeef94.png)

![image](https://user-images.githubusercontent.com/46964809/113220062-dad92600-9282-11eb-9a78-658306dbd423.png)

Not sure what i should provide, i'm on latest ChatControl and Protocollib :)

**Comment by ElBananaa** [comment]
> The delete queue issue, is still there even though it says its fixed..
> 
> ![image](https://user-images.githubusercontent.com/46964809/113220137-f3494080-9282-11eb-968a-6dec238d4302.png)
> 
> ![image](https://user-images.githubusercontent.com/46964809/113220180-05c37a00-9283-11eb-9e99-4e20783fab24.png)
> 
> ![image](https://user-images.githubusercontent.com/46964809/113220208-14119600-9283-11eb-931d-c2a298aeef94.png)
> 
> ![image](https://user-images.githubusercontent.com/46964809/113220062-dad92600-9282-11eb-9a78-658306dbd423.png)
> 
> Not sure what i should provide, i'm on latest ChatControl and Protocollib :)

Hey!

Do you still need help? Did you finally solve your issue? If so, could you please tell us what was wrong?

**Comment by fredagsguf** [comment]
> > The delete queue issue, is still there even though it says its fixed..
> > ![image](https://user-images.githubusercontent.com/46964809/113220137-f3494080-9282-11eb-968a-6dec238d4302.png)
> > ![image](https://user-images.githubusercontent.com/46964809/113220180-05c37a00-9283-11eb-9e99-4e20783fab24.png)
> > ![image](https://user-images.githubusercontent.com/46964809/113220208-14119600-9283-11eb-931d-c2a298aeef94.png)
> > ![image](https://user-images.githubusercontent.com/46964809/113220062-dad92600-9282-11eb-9a78-658306dbd423.png)
> > Not sure what i should provide, i'm on latest ChatControl and Protocollib :)
> 
> Hey!
> 
> Do you still need help? Did you finally solve your issue? If so, could you please tell us what was wrong?

I saw that i could get my license revoked for improper documentation so i just closed it because i couldn't be bothered to..
but yes i still have the issue, where if you delete one message another from the deleted queue comes back.

**Comment by ElBananaa** [comment]
> > > The delete queue issue, is still there even though it says its fixed..
> > > ![image](https://user-images.githubusercontent.com/46964809/113220137-f3494080-9282-11eb-968a-6dec238d4302.png)
> > > ![image](https://user-images.githubusercontent.com/46964809/113220180-05c37a00-9283-11eb-9e99-4e20783fab24.png)
> > > ![image](https://user-images.githubusercontent.com/46964809/113220208-14119600-9283-11eb-931d-c2a298aeef94.png)
> > > ![image](https://user-images.githubusercontent.com/46964809/113220062-dad92600-9282-11eb-9a78-658306dbd423.png)
> > > Not sure what i should provide, i'm on latest ChatControl and Protocollib :)
> > 
> > 
> > Hey!
> > Do you still need help? Did you finally solve your issue? If so, could you please tell us what was wrong?
> 
> I saw that i could get my license revoked for improper documentation so i just closed it because i couldn't be bothered to..
> but yes i still have the issue, where if you delete one message another from the deleted queue comes back.

Are you sure that the plugin, protocolLib and the server software are up to date? I couldn't reproduce the issue on my end, everything works perfectly fine. So please provide us your debug file.

(And regarding your license, instead of closing the issue, just update it. But yeah, we can't provide you any support since we don't have any informations about your environment)

**Comment by fredagsguf** [comment]
> > > > The delete queue issue, is still there even though it says its fixed..
> > > > ![image](https://user-images.githubusercontent.com/46964809/113220137-f3494080-9282-11eb-968a-6dec238d4302.png)
> > > > ![image](https://user-images.githubusercontent.com/46964809/113220180-05c37a00-9283-11eb-9e99-4e20783fab24.png)
> > > > ![image](https://user-images.githubusercontent.com/46964809/113220208-14119600-9283-11eb-931d-c2a298aeef94.png)
> > > > ![image](https://user-images.githubusercontent.com/46964809/113220062-dad92600-9282-11eb-9a78-658306dbd423.png)
> > > > Not sure what i should provide, i'm on latest ChatControl and Protocollib :)
> > > 
> > > 
> > > Hey!
> > > Do you still need help? Did you finally solve your issue? If so, could you please tell us what was wrong?
> > 
> > 
> > I saw that i could get my license revoked for improper documentation so i just closed it because i couldn't be bothered to..
> > but yes i still have the issue, where if you delete one message another from the deleted queue comes back.
> 
> Are you sure that the plugin, protocolLib and the server software are up to date? I couldn't reproduce the issue on my end, everything works perfectly fine. So please provide us your debug file.
> 
> (And regarding your license, instead of closing the issue, just update it. But yeah, we can't provide you any support since we don't have any informations about your environment)

I'm using a fork of paper called purpur which also forks tuinity - so thats probably that causing it.. and i won't be trying on paper as thats not a viable solution for other things.

**Comment by ElBananaa** [comment]
> > > > > The delete queue issue, is still there even though it says its fixed..
> > > > > ![image](https://user-images.githubusercontent.com/46964809/113220137-f3494080-9282-11eb-968a-6dec238d4302.png)
> > > > > ![image](https://user-images.githubusercontent.com/46964809/113220180-05c37a00-9283-11eb-9e99-4e20783fab24.png)
> > > > > ![image](https://user-images.githubusercontent.com/46964809/113220208-14119600-9283-11eb-931d-c2a298aeef94.png)
> > > > > ![image](https://user-images.githubusercontent.com/46964809/113220062-dad92600-9282-11eb-9a78-658306dbd423.png)
> > > > > Not sure what i should provide, i'm on latest ChatControl and Protocollib :)
> > > > 
> > > > 
> > > > Hey!
> > > > Do you still need help? Did you finally solve your issue? If so, could you please tell us what was wrong?
> > > 
> > > 
> > > I saw that i could get my license revoked for improper documentation so i just closed it because i couldn't be bothered to..
> > > but yes i still have the issue, where if you delete one message another from the deleted queue comes back.
> > 
> > 
> > Are you sure that the plugin, protocolLib and the server software are up to date? I couldn't reproduce the issue on my end, everything works perfectly fine. So please provide us your debug file.
> > (And regarding your license, instead of closing the issue, just update it. But yeah, we can't provide you any support since we don't have any informations about your environment)
> 
> I'm using a fork of paper called purpur which also forks tuinity - so thats probably that causing it.. and i won't be trying on paper as thats not a viable solution for other things.

I'm also using purpur on my server (the update they released 4 hours ago), and it works perfectly too.

**Comment by fredagsguf** [comment]
> > > > > > The delete queue issue, is still there even though it says its fixed..
> > > > > > ![image](https://user-images.githubusercontent.com/46964809/113220137-f3494080-9282-11eb-968a-6dec238d4302.png)
> > > > > > ![image](https://user-images.githubusercontent.com/46964809/113220180-05c37a00-9283-11eb-9e99-4e20783fab24.png)
> > > > > > ![image](https://user-images.githubusercontent.com/46964809/113220208-14119600-9283-11eb-931d-c2a298aeef94.png)
> > > > > > ![image](https://user-images.githubusercontent.com/46964809/113220062-dad92600-9282-11eb-9a78-658306dbd423.png)
> > > > > > Not sure what i should provide, i'm on latest ChatControl and Protocollib :)
> > > > > 
> > > > > 
> > > > > Hey!
> > > > > Do you still need help? Did you finally solve your issue? If so, could you please tell us what was wrong?
> > > > 
> > > > 
> > > > I saw that i could get my license revoked for improper documentation so i just closed it because i couldn't be bothered to..
> > > > but yes i still have the issue, where if you delete one message another from the deleted queue comes back.
> > > 
> > > 
> > > Are you sure that the plugin, protocolLib and the server software are up to date? I couldn't reproduce the issue on my end, everything works perfectly fine. So please provide us your debug file.
> > > (And regarding your license, instead of closing the issue, just update it. But yeah, we can't provide you any support since we don't have any informations about your environment)
> > 
> > 
> > I'm using a fork of paper called purpur which also forks tuinity - so thats probably that causing it.. and i won't be trying on paper as thats not a viable solution for other things.
> 
> I'm also using purpur on my server (the update they released 4 hours ago), and it works perfectly too.

heres my files, not sure if you can see anything from that:
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6240377/debug.zip)


And plugin list:
![image](https://user-images.githubusercontent.com/46964809/113231289-32838b80-929b-11eb-9fac-6b489724cdbf.png)

**Comment by ElBananaa** [comment]
> > > > > > > The delete queue issue, is still there even though it says its fixed..
> > > > > > > ![image](https://user-images.githubusercontent.com/46964809/113220137-f3494080-9282-11eb-968a-6dec238d4302.png)
> > > > > > > ![image](https://user-images.githubusercontent.com/46964809/113220180-05c37a00-9283-11eb-9e99-4e20783fab24.png)
> > > > > > > ![image](https://user-images.githubusercontent.com/46964809/113220208-14119600-9283-11eb-931d-c2a298aeef94.png)
> > > > > > > ![image](https://user-images.githubusercontent.com/46964809/113220062-dad92600-9282-11eb-9a78-658306dbd423.png)
> > > > > > > Not sure what i should provide, i'm on latest ChatControl and Protocollib :)
> > > > > > 
> > > > > > 
> > > > > > Hey!
> > > > > > Do you still need help? Did you finally solve your issue? If so, could you please tell us what was wrong?
> > > > > 
> > > > > 
> > > > > I saw that i could get my license revoked for improper documentation so i just closed it because i couldn't be bothered to..
> > > > > but yes i still have the issue, where if you delete one message another from the deleted queue comes back.
> > > > 
> > > > 
> > > > Are you sure that the plugin, protocolLib and the server software are up to date? I couldn't reproduce the issue on my end, everything works perfectly fine. So please provide us your debug file.
> > > > (And regarding your license, instead of closing the issue, just update it. But yeah, we can't provide you any support since we don't have any informations about your environment)
> > > 
> > > 
> > > I'm using a fork of paper called purpur which also forks tuinity - so thats probably that causing it.. and i won't be trying on paper as thats not a viable solution for other things.
> > 
> > 
> > I'm also using purpur on my server (the update they released 4 hours ago), and it works perfectly too.
> 
> heres my files, not sure if you can see anything from that:
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6240377/debug.zip)
> 
> And plugin list:
> ![image](https://user-images.githubusercontent.com/46964809/113231289-32838b80-929b-11eb-9fac-6b489724cdbf.png)

Thanks!
Well, you're not using the latest version of the plugin in which this issue was fixed, that why you're still experiencing it. Update to v10.3.3 (You're currently using 10.3.2 according to the debug file)

**Comment by fredagsguf** [comment]
Thats really wierd, i downloaded it today? but thanks i'll try the new version!

**Comment by fredagsguf** [comment]
That worked, i swear i downloaded the plugin today - but i apperently was using an old version somehow.

**Comment by ElBananaa** [comment]
> That worked, i swear i downloaded the plugin today - but i apperently was using an old version somehow.

That's not a big deal haha. At least it works now. Have a nice day :)

**Comment by kangarko** [comment]
Glad that was solved happy for you ;)

For everyone reading - always update the whole network including ChatControl Red and BungeeControl Red and RESTART, reloading can cause odd things to happen.
