### ISSUE TITLE
1.16.5 - packet.rs bug, not working for /plugins or /version

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#858]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true
Paper build 487

In the past, this has worked fine, yet now no longer works unless it is dealing with packets from another plugin etc
Just so I am clear, I am talking about /ver and /plugins

These default rules no longer work
```
# Troll users accessing /version command
# You can use the $ + group number as a variable that will be replaced by the matching group
match (git-Paper-)(.*)(Implementing API version .*)
then replace JesusSpigot-$2 (Implementing API version 1.17-R0.1-SNAPSHOT)
dont verbose

# Replace the /plugins message.
match ^Plugins \(([1-9])\): (.*)$
then replace &2There are &6$1 &2plugins: &7$2
dont verbose
```

however when I tested
```
# Hide unknown command message.
match ^Unknown command.*
then deny
dont verbose
```
It worked fine, could this be due to Paper 1.16.5 build 473, now including Adventure? As I noticed some changes to paper's /ver, since it now has hover test etc? I assume such changes also impacted /plugins? since the packet rules for /plugins also no longer work.

Just to be clear, it seems packet.rs is working fine for the most part until you try to use on paper commands like /version or /plugins

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> Paper build 487
> 
> In the past, this has worked fine, yet now no longer works unless it is dealing with packets from another plugin etc
> Just so I am clear, I am talking about /ver and /plugins
> 
> These default rules no longer work
> 
> ```
> # Troll users accessing /version command
> # You can use the $ + group number as a variable that will be replaced by the matching group
> match (git-Paper-)(.*)(Implementing API version .*)
> then replace JesusSpigot-$2 (Implementing API version 1.17-R0.1-SNAPSHOT)
> dont verbose
> 
> # Replace the /plugins message.
> match ^Plugins \(([1-9])\): (.*)$
> then replace &2There are &6$1 &2plugins: &7$2
> dont verbose
> ```
> 
> however when I tested
> 
> ```
> # Hide unknown command message.
> match ^Unknown command.*
> then deny
> dont verbose
> ```
> 
> It worked fine, could this be due to Paper 1.16.5 build 473, now including Adventure? As I noticed some changes to paper's /ver, since it now has hover test etc? I assume such changes also impacted /plugins? since the packet rules for /plugins also no longer work.
> 
> Just to be clear, it seems packet.rs is working fine for the most part until you try to use on paper commands like /version or /plugins

Hey!
I just tried with CHC-Red 10.3.3 and latest ProtocolLib dev build under paper 1.16.5 build 576, and I can confirm that the first rules doesn't work. However, the plugins rules works properly. Same thing with the unknown command rule.

I also tried to simply replace the rule with the code down below, and wrote `Paper` in the chat, then I had this error: https://paste.gg/p/anonymous/23d4af0e758644c485814170d1c1b956
```
# Troll users accessing /version command
# You can use the $ + group number as a variable that will be replaced by the matching group
match Paper
then replace JesusSpigot-$2 (Implementing API version 1.17-R0.1-SNAPSHOT)
dont verbose
```

**Comment by kangarko** [comment]
This is due to the Adventure library in Paper. I already reached out to ProtocolLib developer for assistance, at present I am unable to move forward with this.

**Comment by DeusNinja** [comment]
Any change this was taken care of? I'm currently still experiencing packet.rs not functioning on current builds as of this comment.

**Comment by ElBananaa** [comment]
> Any change this was taken care of? I'm currently still experiencing packet.rs not functioning on current builds as of this comment.

This is most likely unrelated as this issue was patched a few months ago already. Please open a new issue following the format and provide your `/chc debug` file there.
