### ISSUE TITLE
Premium Vanish support

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/ChatControl#859]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
     All users that use premium vanish has the option to disable message they do this in a way on putting a " / " on the back of a message. I think it would be great to use this feature instaid of needing to use a command to prevent chat.

2. What would happen if we won't implement this feature? How's your server being affected?
My server isn't really affected only I would like to see this option possible because use a command or a " / " on the end of a message is a big difference.

I want to suggest as I said a premium vanish support that allows you to set a / behind the message so you don't need to use a command to send a message. I think Premium vanish has done a great job with this and I would like to see this feature available

**Comment by ElBananaa** [comment]
> 1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
>    All users that use premium vanish has the option to disable message they do this in a way on putting a " / " on the back of a message. I think it would be great to use this feature instaid of needing to use a command to prevent chat.
> 2. What would happen if we won't implement this feature? How's your server being affected?
>    My server isn't really affected only I would like to see this option possible because use a command or a " / " on the end of a message is a big difference.
> 
> I want to suggest as I said a premium vanish support that allows you to set a / behind the message so you don't need to use a command to send a message. I think Premium vanish has done a great job with this and I would like to see this feature available

Hey!
I'm using PremiumVanish flawlessly on my server. Could you please provide us your `/chc debug` output file and your PV config file so we could take a look at them?

**Comment by Greazi-Times** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6244372/debug.zip)
https://paste.helpch.at/zuruhagudi.coffeescript

The .zip contains the debug files and the link contains the config from premium vanish

I have not updated to the newest version yet I need to wait until some other things are finished.

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6244372/debug.zip)
> https://paste.helpch.at/zuruhagudi.coffeescript
> 
> The .zip contains the debug files and the link contains the config from premium vanish
> 
> I have not updated to the newest version yet I need to wait until some other things are finished.

Alright, thanks.
Try changing `Prevent_Vanish_Chat:` to `false` in ChatControlRed config file, it should fix your issue with PremiumVanish.

**Comment by Greazi-Times** [comment]
> > [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6244372/debug.zip)
> 
> > https://paste.helpch.at/zuruhagudi.coffeescript
> 
> > 
> 
> > The .zip contains the debug files and the link contains the config from premium vanish
> 
> > 
> 
> > I have not updated to the newest version yet I need to wait until some other things are finished.
> 
> 
> 
> Alright, thanks.
> 
> Try changing `Prevent_Vanish_Chat:` to `false` in ChatControlRed config file, it should fix your issue with PremiumVanish.

In chat control red I assume. 
Because so had that option disabled and when I am vanished And I send a message it still sends the message without even the / behind the message

**Comment by ElBananaa** [comment]
Alright, so, quick update: I just tried on my prod server with the latest version of chatcontrol, and I can confirm that this is somehow broken. However, to fix this, in PremiumVanish config file, set `AsyncPlayerChatEventPriority:` to `HIGHEST`, then restart your server, and it'll fix the issue.

EDIT: Reloading PremiumVanish seems to break the system, even with the priority set to `HIGHEST`. So I guess we'll have to wait for Kangarko to see if there's anything he could do about it. :)

**Comment by Greazi-Times** [comment]
I have set the option to highest than it stil doesn't work. When I set the option to moderate it works. but it doesn't let me use color codes.

**Comment by kangarko** [comment]
Try keeping the default AsyncPlayerChatEventPriority for PremiumVanish and changing ours, see if that helps: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

**Comment by Greazi-Times** [comment]
> Try keeping the default AsyncPlayerChatEventPriority for PremiumVanish and changing ours, see if that helps: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

I have set it to almost any value and no luck so far.

**Comment by kangarko** [comment]
Thanks, but since ChatControl handles chat in its own way, I am afraid this is a minor compatibility clash we're not gonna address by adding our own duplicate system for it.

**Comment by Greazi-Times** [comment]
> Thanks, but since ChatControl handles chat in its own way, I am afraid this is a minor compatibility clash we're not gonna address by adding our own duplicate system for it.

I understand that part but I hav tried everything default and it still doesn't work even though ElBanna says he has PremiumVanish 2 and it works fine for him. So I have no idea what may cause this problem.

**Comment by ElBananaa** [comment]
> > Try keeping the default AsyncPlayerChatEventPriority for PremiumVanish and changing ours, see if that helps: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities
> 
> I have set it to almost any value and no luck so far.

Hey!
Did you try to restart the server after changing the priority?
If it still doesn't work, then this means this is caused by something else. As I said, it works perfectly fine for me.

**Comment by Greazi-Times** [comment]
> > > Try keeping the default AsyncPlayerChatEventPriority for PremiumVanish and changing ours, see if that helps: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities
> 
> > 
> 
> > I have set it to almost any value and no luck so far.
> 
> 
> 
> Hey!
> 
> Did you try to restart the server after changing the priority?
> 
> If it still doesn't work, then this means this is caused by something else. As I said, it works perfectly fine for me.

Yes I have restarted my server after I changed the value

**Comment by Greazi-Times** [comment]
I have reset chat control red and it works now I think of a bug somewhere on my server
