### ISSUE TITLE
Hover/clickable Names in chat

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#860]
Is it possible to have clickable/hover player names in chat and then have it link when you click the name to something a command which for instance gives you a GUI about the player (The GUI wouldn't be done through this plugin though)

If this isn't a feature it would be really cool if it could get added.

Thanks

Minecraft Version: 1.16.X
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Is it possible to have clickable/hover player names in chat and then have it link when you click the name to something a command which for instance gives you a GUI about the player (The GUI wouldn't be done through this plugin though)
> 
> If this isn't a feature it would be really cool if it could get added.
> 
> Thanks
> 
> Minecraft Version: 1.16.X
> MySQL: true
> BungeeCord: true

Hey!
You can currently do this with the plugin using the format system.
Take a look at the wiki page to do so : https://github.com/kangarko/ChatControl-Red/wiki/Formats
