### ISSUE TITLE
server-name

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#861]
hi
why changing server-name: in server.properties don't have effect on papi %server-name% place holder but effect on ChatControl-red server name
paper said to me that this option was removed long time ago

want to know how to use this placeholder  that chatcontrol offers?

Minecraft Version: 10.3.3
MySQL: true
BungeeCord: true

**Comment by TheIntolerant** [comment]
Have a read of this #769 that should fix your issue (assuming you are using PlaceholderAPI)

**Comment by TheIntolerant** [comment]
As stated there, it seems PlaceholderAPI overrides that placeholder, used by chatcontrol

**Comment by FakEEE14** [comment]
thanks i found it
