### ISSUE TITLE
1.16.5 Does chc log warns and kicks?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#862]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Does chc log warns and kicks issued by chc?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Does chc log warns and kicks issued by chc?

Hey!
You can log commands, however, as far as I know, there's no way to only log kick/warns commands.
You could write a rule to automatically log the kick/warn commands ran by an user.

**Comment by kangarko** [comment]
Just write a custom rule to log any command you wish.
