### ISSUE TITLE
1.16.5 : Is it possible to read two or more channel at one time? 

### ISSUE THREAD

**Issue by enkacang** [kangarko/ChatControl#863]
Is it possible to read two or more channels at one time?

I want to create a channel where people that chat in ranged can see global chat.

**Comment by ElBananaa** [comment]
> Is it possible to read two or more channels at one time?
> 
> I want to create a channel where people that chat in ranged can see global chat.

Hey!
Yeah, you can read multiple channels at the same time, but you can write in only one channel at time. However, you could create chat rules to automatically send a message to a specific channel if your message starts with a specific prefix. There's an example rule for that in `/rules/chat.rs`.

**Comment by enkacang** [comment]
``` Yeah, you can read multiple channels at the same time, ```

How can I achieve this?

**Comment by ElBananaa** [comment]
> `Yeah, you can read multiple channels at the same time,`
> 
> How can I achieve this?

Simply give yourself the following permissions: `chatcontrol.channel.autojoin.channel1.read`, `chatcontrol.channel.autojoin.channel2.read`, `chatcontrol.channel.autojoin.channel3.read`, `chatcontrol.channel.join.channel1.read`, `chatcontrol.channel.join.channel2.read`, `chatcontrol.channel.join.channel3.read`, etc...

Ofc, don't forget to replace `channel1`, `channel2` and `channel3` with your current channel names.
