### ISSUE TITLE
1.12.2 ProtocolLib incompatibility

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#866]
Minecraft Version: 1.12.2
MySQL: false
BungeeCord: false

I have installed Protocollib on my server, and when I type "/" or any command starting with "/" and then press enter, then it replies that the server went down and I get disconnected (even though the server hasn't gone down!). I was wondering what was the issue and decided to turn on/off each plugin on my server. It appeared that when both ChatControlRed and Protocollib are both active, then this issue happens. There are no errors in the console. The issue happens with any version of Protocollib.

I attach the file generated after /chc debug command (of course with deactivated Protocollib, otherwise I wouldn't even be able to run the debug command).

[https://ufile.io/nirhv5rd](https://ufile.io/nirhv5rd)

**Comment by ElBananaa** [comment]
Hey!
Which version of ProtocolLib did you try?
This is probably a version-related issue, but we would still need this information.
Also, please provide us the full latest.log when this happens, just in case.

**Comment by nikitushu2** [comment]
Here is the ProtocolLib I use: [https://ufile.io/pou6sio1](https://ufile.io/pou6sio1)
Here is the latest.log after I have reproduced the issue: [https://ufile.io/s6y0lf57](https://ufile.io/s6y0lf57)

**Comment by ElBananaa** [comment]
> Here is the ProtocolLib I use: https://ufile.io/pou6sio1
> Here is the latest.log after I have reproduced the issue: https://ufile.io/s6y0lf57

Hey!
Alright. Your ProtocolLib version is outdated, please update to v4.6.0 then try again.

**Comment by nikitushu2** [comment]
Same issue.

Chc's debug: [https://ufile.io/ttrgkq2g](https://ufile.io/ttrgkq2g)
latest.log: [https://ufile.io/bwo2ewcl](https://ufile.io/bwo2ewcl)

**Comment by ElBananaa** [comment]
> Same issue.
> 
> Chc's debug: https://ufile.io/ttrgkq2g
> latest.log: https://ufile.io/bwo2ewcl

Alright, try the following : `set Integration.ProtocolLib.Listen_For_Packets and Tab_Complete.Enabled both to false in settings.yml.` then try restarting the server, and let us know if it fixes the issue.
Also, make sure to update all of your plugins/dependencies. From what I can see in your logs, a lot of your plugins are outdated.

**Comment by nikitushu2** [comment]
The issue persists. (sorry didnt notice the last line, I'll write back when I update the plugins)

**Comment by nikitushu2** [comment]
I have updated all the possible plugins, the issue persists.

**Comment by nikitushu2** [comment]
Curiously enough, if I replicate the issue joining from 1.12.2, my client crashes:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000045df814, pid=13676, tid=10584
#
# JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# J 7992 C2 buy.a(Lvg;Lbxy;F)V (1453 bytes) @ 0x00000000045df814 [0x00000000045de660+0x11b4]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp

**Comment by nikitushu2** [comment]
I am very sorry for taking your time! The issue persists even when chc is disabled. I go to protocllib support
