### ISSUE TITLE
1.12.2 How to unmute a player?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#867]
Minecraft Version: 1.12.2
MySQL: false
BungeeCord: false

How to unmute a muted player?

Also, how to turn off the public announcement that Console has muted someone? Or how to make this announcement visible only to the offender?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.12.2
> MySQL: false
> BungeeCord: false
> 
> How to unmute a muted player?
> 
> Also, how to turn off the public announcement that Console has muted someone? Or how to make this announcement visible only to the offender?

Hey!
Simply use `/mute <player> off`
