### ISSUE TITLE
1.12.2 How to create a rule that logs mutes?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#868]
Minecraft Version: 1.12.2
MySQL: false
BungeeCord: false

I know that I should add "then log" after the mute line but the Warning Points section has actions executed on reaching particular points, and each action is in one line. 

```
    swear:
      3:
      - 'warn &cYou have received first warning for swearing.'
      6:
      - 'warn &cPlease do not swear, otherwise an action will be taken!'
      8:
      - 'mute player {player} 1h &cInappropriate language (last warning)'
```

Should I put "then log" there? And how do I put it as a second line so it does not break anything?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.12.2
> MySQL: false
> BungeeCord: false
> 
> I know that I should add "then log" after the mute line but the Warning Points section has actions executed on reaching particular points, and each action is in one line.
> 
> ```
>     swear:
>       3:
>       - 'warn &cYou have received first warning for swearing.'
>       6:
>       - 'warn &cPlease do not swear, otherwise an action will be taken!'
>       8:
>       - 'mute player {player} 1h &cInappropriate language (last warning)'
> ```
> 
> Should I put "then log" there? And how do I put it as a second line so it does not break anything?

Hey!
I don't think you can currently use rules operators in this part. So I don't think you can currently log mutes executed from the plugin.

**Comment by kangarko** [comment]
Sorry that would not be possible right now, however you could write a trick:

```
      3:
      - 'warn &cYou have received first warning for swearing.'
      - 'logmute 3'
```

This non-existent command I believe you can catch by creating a command rule, see command.rs for examples, then simply use 'then log' and 'then deny' operators to silence any information that the command has been executed.
