### ISSUE TITLE
Suggestion: give option in /chc book commands

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl#869]
The book saving and opening of this plugin is a great feature, but what would really make it useful is the option to create an item of a book you saved. Of course placeholders wouldn't work but maybe you find a solution for that. 

1. How would it benefit others? You can make awesome book using chatcontrol, if you could give them to new players for example on first join, or a special library, you could make cool things with the book as items. This is much more dynamic then for the player to always type /chc book open (name)

2. If you won't implement the feature the world will end in 5 days, just kidding. My server will have ugly books instead of nice ones. 

Btw: The suggestion format makes no sense, especially question 2. I get you have a fixed format for bugs, it spares you time, but with suggestion the only real requirement would be to explain it thoroughly

**Comment by ElBananaa** [comment]
> The book saving and opening of this plugin is a great feature, but what would really make it useful is the option to create an item of a book you saved. Of course placeholders wouldn't work but maybe you find a solution for that.

Hey!
Please update your suggestion to follow the suggestion format or open a new one.
I'm closing your suggestion, and I'll reopen it if you update the format.

If you decide to update your post, please tag me in a new comment.

**Comment by JessePesse123** [comment]
@ElBananaa

**Comment by kangarko** [comment]
Thanks added :) @ElBananaa if reasonable they might slightly use an adjusted version of the issue template, here is fine :)
