### ISSUE TITLE
Question about whitelisting urls and more

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [kangarko/ChatControl#87]
I saw you prefferred the message here, so here we go:
I'm trying to block these annoying Minechat messages:
![image](https://cloud.githubusercontent.com/assets/3297866/6651191/1b8458a6-ca38-11e4-8c59-f201ea115bab.png)

```
# -------- Prevent annoyances
match I'm chatting on my . using Minecraft Connect! Check it out, it's free|connected with an . using MineChat|Connected from Hyperchat .
then rewrite I can't get enough of this server.
```
But people can still write it (see screenshot). What am I doing wrong? (PS: A lot of people would probably appreciate if you added this as a standard filter because it's a common message)

I'm also trying to whitelist some ips, I just tested with google.com and it's blocked. Config:
```
# IP filter. Notice the operator strip which removes specified characters BEFORE the message is checked.
match \b[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}\b
ignore string google|bit.ly|mcsimplegaming.com|minecraft.net|mojang.com|reddit.com
id 1
strip [\(\[\]\)]
then warn &cPlease read the server rules! /rules
then deny
handle as advertisement
```
I can write bit.ly but not mcsimplegaming.com

**Comment by kangarko** [comment]
This is unknown operator and will cause the parser to fail: strip [\(\[\]\)]

To the first issue: It is perhaps a message from another plugin, than you have to write the rule in packets.txt and deny it with appropiate operator (read the header)

To the second issue: There is something wrong with your regex perhaps, I am not that good at them but you might try to add \ before the bit.ly so it is bit\.ly since the dot is parsed as a literal when it has \ before

**Comment by TheOnlyRealTGS** [comment]
> First issue
No this is caused by android/ios apps allowing you to chat on MC servers so it's not that

> Second issue
So 
```
google|\bit.ly|\mcsimplegaming.com|\minecraft.net|\mojang.com|\reddit.com
```
Would do the trick or?

I'll play more around and return back

**Comment by TheOnlyRealTGS** [comment]
Okay, second one is solved. Solution
```
ignore string google|bit.ly|mcsimplegaming.com|minecraft.net|mojang.com|reddit.com|youtube.com
```

I moved it to the domain filter and it works perfectly, it was in the IP filter (makes senses)

**Comment by kangarko** [comment]
Yes if you want to hide a message from another plugin you have to make a rule in packets.txt

**Comment by TheOnlyRealTGS** [comment]
I'll try that

**Comment by TheOnlyRealTGS** [comment]
Wait, that's pointless - all the other chat stuff works fine, it must be my syntax that is wrong

**Comment by TheOnlyRealTGS** [comment]
I edited it to
```
match using Minecraft Connect! Check it out, it's free|using MineChat|Connected from Hyperchat
```
