### ISSUE TITLE
1.16.5 : Last Question Of The Day - Aliases 👍 

### ISSUE THREAD

**Issue by enkacang** [kangarko/ChatControl#871]
Thanks for the helpfulness... How about aliases?

I want to create simple /g {arg} for /channel send [channel] [msg]

**Comment by TheIntolerant** [comment]
There should be an example of how to do this in the ``command.rs`` file on ``/rules``

```
# -----------------------------------------------------------------------------------------------
# Create a /helpop command that sends messages to a channel.
# -----------------------------------------------------------------------------------------------

# Catch "/helpop" command and send usage.
#match ^\/helpop$
#dont verbose
#then warn &cDescription: Send a message to online staff members.
#then warn &cUsage: /helpop <message>
#then deny

# Catch "/helpop <message>" and redirect to the helpop channel.
#match ^(\/helpop) (.*)
#dont verbose
#then command channel send helpop $2
#then deny
```
To enable you just remove the hashtag at the start for the operators, such as ``then deny`` ``then command`` ``dont verbose`` and ``match``, if you keep the hashtags the plugin interprets it has a comment, comments are helpful for explaining part of the code.


Anyway, all you need to make ``/g {arg}`` run say ``/channel send global [msg]``, add the following into the ``command.rs`` file in ``/rules``
```
# Catch "/g" command and send usage.
match ^\/g$
dont verbose
then warn &cDescription: Send a message to global chat.
then warn &cUsage: /g <message>
then deny

# Catch "/g <message>" and redirect to the global channel.
match ^(\/g) (.*)
dont verbose
then command channel send global $2
then deny
```

-------------------------------
**Short explanation as to how this works**

The hardest part with making chatcontrol rules is getting the regular expression right (the part that goes after ``match``) and understanding things like ``^`` = start of the string and ``$`` = end of the string. Also understanding how the capture groups work, in the above example the second capture group is used ``$2``

So if I look at ``match ^(\/g) (.*)``, ``$0`` would return with ``/g <msg>`` whatever your message is but ``$1`` would return with just ``/g`` whereas ``$2`` returns with the ``message`` part of that command. That is why ``$2`` is used in ``then command channel send global $2``
