### ISSUE TITLE
Thanks to whoever came up with all these death messages

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#873]
Sorry if this is off-topic but the death messages are so funny!

**Comment by ElBananaa** [comment]
Hey,
Please don't open issues if that's not for a question, a suggestion or a bug-report regarding the plugin. :)

**Comment by kangarko** [comment]
Thanks man <3

**Comment by kangarko** [comment]
I am not gonna take credit for this, I believe a guy sent me his debug file years ago and so I just asked him if we could ship this with the default config and he said yes!
