### ISSUE TITLE
Tab prefix for muted players and muted player response

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#875]
**1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**

People trying to message a muted player will understand that the player can't respond by receiving a reply something like: the player is muted for 1h, he cannot respond.

Regarding tab prefix, it'd be just a nice feature for those who doesn't want to include my above mentioned feature. So that if you message a player and he doesn't respond, just check the tab and you will see that he is muted.

**2. What would happen if we won't implement this feature? How's your server being affected?**

My server would lack a very convenient feature, though not the critical one.

**Comment by kangarko** [comment]
Thank you! We're not planning to add this right now but I've put this to the backburner
