### ISSUE TITLE
1.16.5 How to synchronize /msg messages with Discord?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#876]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

I managed to synchronize chat channels but I don't know what rule and where I should create to synchronize all the messages sent by /pm, /tell or /msg into Discord.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> I managed to synchronize chat channels but I don't know what rule and where I should create to synchronize all the messages sent by /pm, /tell or /msg into Discord.

Hey!
What do you mean by synchronizing messages sent by pm with discord? Are you trying to send spied messages to discord?
If you're trying to send a private message from the server, to a discord user, then, I don't think this is currently possible with the plugin.

**Comment by nikitushu2** [comment]
I mean that I want all the messages sent by players (yeah, spying) be redirected to discord. I did same with chat, whatever they write into chat, automatically gets sent to discord. How do I do same with private messages?

**Comment by kangarko** [comment]
You can just create a chat.rs rule that will use the "then discord" operator and catch all private message commands.
