### ISSUE TITLE
1.16.5 Anti-spam rule does NOT ignore the channel

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#877]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

```
# -----------------------------------------------------------------------------------------------
# Anti spam.
# -----------------------------------------------------------------------------------------------

# Limiting repeating characters to four repeats maximum.
match (.)(?=([a-z])\1{3})
ignore channel local
then replace

```

What's wrong with my configured anti-spam section? My players are still punished for spamming into local channel.

**Comment by TheIntolerant** [comment]
Have you tried 
**ignore channel local write**

**Comment by nikitushu2** [comment]
I tried it but the issue persists.

**Comment by kangarko** [comment]
In the next version put ["rules"] into Debug key in settings.yml and report the console messages when you type that message while in the local channel

**Comment by kangarko** [comment]
<img width="627" alt="Screenshot 2021-04-13 at 09 17 40" src="https://user-images.githubusercontent.com/1918426/114512186-1be51900-9c39-11eb-88eb-fc82245159c8.png">
Works perfectly fine for me, follow up on the instructions above if you still have this problem and post below

**Comment by TheIntolerant** [comment]
I have a feeling they have a rule that uses ``then deny`` that is preventing the anti-spam rule from being processed.

@kangarko It might be worth changing the default config for ``chat.rs`` so that
```
# -----------------------------------------------------------------------------------------------
# Anti spam.
# -----------------------------------------------------------------------------------------------

# Limiting repeating characters to four repeats maximum.
#match (.)(?=([a-z])\1{3})
#then replace

# Prevent special, unicode characters. Those are misused to bypass filters.
# Please keep in mind that non-English languages use them, so only uncomment this on English servers.
#match [^\u0000-\u007F]+
#then warn {prefix_error}Unicode characters are prohibited.
#then deny
```
is at the top of the file, since I have a strong feeling that they are using one of these rules
```
# -----------------------------------------------------------------------------------------------
# Forwarding messages to other channels.
# -----------------------------------------------------------------------------------------------

# Send messages starting with "!" to global channel
#match ^(\!)(.*)
#then command channel send global $2
#then deny
#dont verbose
```
and because that is at the top of the chat.rs file, the anti-spam rule does not process the message before it is forwarded to another channel.

**Comment by TheIntolerant** [comment]
> ```
> 
> # -----------------------------------------------------------------------------------------------
> 
> # Anti spam.
> 
> # -----------------------------------------------------------------------------------------------
> 
> 
> 
> # Limiting repeating characters to four repeats maximum.
> 
> match (.)(?=([a-z])\1{3})
> 
> ignore channel local
> 
> then replace
> 
> 
> 
> ```
> 
> 
> 
> What's wrong with my configured anti-spam section? My players are still punished for spamming into local channel.


@nikitushu2 try copying that and moving it to the top of the file, as chatcontrol processes each rule from top to bottom and the reason it might not be working could simply be due to it being blocked by another chatcontrol rule that uses "then deny" etc.

**Comment by kangarko** [comment]
Thanks, moved. Users need to migrate this manually to see the effect.
