### ISSUE TITLE
1.16.5: Discord chat adds chat uuid

### ISSUE THREAD

**Issue by simon44556** [kangarko/ChatControl#878]
Minecraft Version: 1.16,5
MySQL: false
BungeeCord: false

When I setup the chatcontrol to forward my chat to discord I get a random uuid attached to the message.
This sometimes happens after I reload the plugin or sometimes after the server starts here is an image example
https://prnt.sc/1144try

Is it possible that some other plugin is adding this?
Also is it possible that when I enabled Webhook this started happening?

The other request I have is it possible to change the displayname the webhook uses to a realname of the player?

I am also providing the debug zip.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6255089/debug.zip)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16,5
> MySQL: false
> BungeeCord: false
> 
> When I setup the chatcontrol to forward my chat to discord I get a random uuid attached to the message.
> This sometimes happens after I reload the plugin or sometimes after the server starts here is an image example
> https://prnt.sc/1144try
> 
> Is it possible that some other plugin is adding this?
> Also is it possible that when I enabled Webhook this started happening?
> 
> The other request I have is it possible to change the displayname the webhook uses to a realname of the player?
> 
> I am also providing the debug zip.
> 
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6255089/debug.zip)

Hey!
Thanks for reporting this issue!
This might be caused by chatcontrol, since the remove message feature uses the message uid.
Kangarko will probably have a look at it tomorrow! :)

**Comment by kangarko** [comment]
Looks like another plugin, please try disabling/enabling webhooks etc. Or completely disable our Discord integration to see if the problem persists when letting DiscordSRV format chat. Or try just with DiscordSRV and ChatControl Red

**Comment by simon44556** [comment]
Thank you for the reply. 
After more testing I figured out the interactive chat was adding that to the message. I need to disable that plugin anyways and enable the features in Chatcontrol.
