### ISSUE TITLE
1.12.2 What do I lose if I disable listen_for_packets?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#879]
Minecraft Version: 1.12.2
MySQL: false
BungeeCord: false

Does chc lose critical features if I disable listen_for_packets in the protollib's section?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.12.2
> MySQL: false
> BungeeCord: false
> 
> Does chc lose critical features if I disable listen_for_packets in the protollib's section?

Hey!
Well according to the wiki, disabling this features means that you won't be able to use packet rules (see rules/packet.txt) and won't be able to prevent tab complete on older MC versions.

https://github.com/kangarko/ChatControl-Red/wiki/Compatibility#optional-plugin-dependencies

**Comment by kangarko** [comment]
Thanks Banana!

**Comment by kangarko** [comment]
And you also lose the [X] chat message removal feature.
