### ISSUE TITLE
Console filter problem

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [kangarko/ChatControl#88]
This is so useful btw.
This is my config:
```
Console:
  Filter:
    # Filter console messages specified below?
    Enabled: true

    # Remove certain messages from the server console.
    # Does not need to be whole message, just a part of the message you want to block.
    Filter_Console_Messages:
    - Reached end of stream for
    - Connection reset
    - lost connection
    - CommandBlock at
    - issued server command: /menu
    - issued server command: /icc
    - issued server command: /hg vote
    - issued server command: /realname
    - issued server command: /whowas
    - CONSOLE issued server command: /fly
```
I did /chatcontrol reload, and yet this shows; Does it need a restart or is it a bug?
![image](https://cloud.githubusercontent.com/assets/3297866/6656146/60e5a954-cb1e-11e4-98a3-ad1a0e4c45fe.png)

**Comment by kangarko** [comment]
Of course it NEEDS to be restarted. It is stated multiple times across the spigotmc where the plugin is posted and in the reload message itself.

**Comment by TheOnlyRealTGS** [comment]
> Of course it NEEDS to be restarted
Okay, it seems to work with the commadblock message, but I'll restart and see if the issue still persists.
