### ISSUE TITLE
Channel party "plotsquared-plot" results in no format at all

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#88]
Doesn't seem to work at all, I set my local channel to plotsquared-plot [https://i.gyazo.com/e0b9827c66e6dcf96062632640ef7ea9.png](https://i.gyazo.com/e0b9827c66e6dcf96062632640ef7ea9.png)

but it doesn't seem to work, it just has no chat formatting and everyone on the server can see my chat message.
[https://i.gyazo.com/416534c53b2210a97023611423cd5886.png](https://i.gyazo.com/416534c53b2210a97023611423cd5886.png)

If I change it to ranged mode or something, the formatting works again:
[https://i.gyazo.com/6e6f2ce7060c452f75b125a488b246ed.png](https://i.gyazo.com/6e6f2ce7060c452f75b125a488b246ed.png)

(Also I think having words like gay and lesbian blocked by default is wrong, they aren't offensive at all or swear words or inappropriate, maybe change that.)

**Comment by kangarko** [comment]
Thanks, any errors in the console when that happens?

**Comment by kangarko** [comment]
Also what PlotSquared version do you use?

**Comment by DoogiePC** [comment]
https://pastebin.com/q6gvVq7y

Also im running the latest plotsquared v5

**Comment by kangarko** [comment]
Thanks, I will fix that.

**Comment by 00Hrtz** [comment]
> 
> 
> Doesn't seem to work at all, I set my local channel to plotsquared-plot https://i.gyazo.com/e0b9827c66e6dcf96062632640ef7ea9.png
> 
> but it doesn't seem to work, it just has no chat formatting and everyone on the server can see my chat message.
> https://i.gyazo.com/416534c53b2210a97023611423cd5886.png
> 
> If I change it to ranged mode or something, the formatting works again:
> https://i.gyazo.com/6e6f2ce7060c452f75b125a488b246ed.png
> 
> (Also I think having words like gay and lesbian blocked by default is wrong, they aren't offensive at all or swear words or inappropriate, maybe change that.)

I was looking for some info and came across this issue, noticed your last comment about the terms gay and lesbian not being bad.

The words are not bad no but the way in which people use them is bad so it's extremely appropriate to flag them as offensive and take them out of the equation altogether. No one should feel the need to use those terms on a gaming server anyway and it just invites people to use those terms in hostile ways. I have updated the swear filter recently so you should see more filtered words in a future update by kangarko.
