### ISSUE TITLE
1.16.5: Multiple Channels, how to send to one Discord channel?

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl#880]
For whatever reason my Channels are not being sent to the Discord channel correctly. In ChatControlPro all we had to do was enable Discord on each channel and add the channel name to DiscordSRV and this worked perfectly.

For whatever reason now I can only get Local chat to send to Discord when I am trying to send Local and Global chats.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Debug: https://ufile.io/ij82iz7c

**Comment by kangarko** [comment]
You haven't connected your global and local channels in the Connected_Channels key (just search for this in settings.yml)

Please watch the video here and complete the steps to get our hook working again ;)

https://github.com/kangarko/ChatControl-Red/wiki/Discord

**Comment by Skizzles** [comment]
@kangarko I see, how would I send both global and local to a single discord channel? (This was possible on ChatControlPro)

**Comment by kangarko** [comment]
In the next version you will be able to set the Discord key in Channels settings to your channel name and it should work :)
