### ISSUE TITLE
PaperMC 1.16.5 | High ms for ChatListener listening

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl#885]
Minecraft Version: PaperMC 1.16.5
MySQL: true
BungeeCord: true

```
[18:51:33] [Async Chat Thread - #0/INFO]: [ChatControlRed 10.3.3] ChatListener listening to AsyncPlayerChatEvent at HIGH priority took 1387.67 ms
[18:51:33] [Async Chat Thread - #0/INFO]: [standard] AmazedMender16: d
[18:51:35] [Async Chat Thread - #0/INFO]: [ChatControlRed 10.3.3] ChatListener listening to AsyncPlayerChatEvent at HIGH priority took 916.24 ms
[18:51:35] [Async Chat Thread - #0/INFO]: [standard] AmazedMender16: d
```

We're seeing high MS for ChatListener listening, this results in chat messages being send late/showing up late.

Debug.zip was privately shared with Matej via email, not uploading it publicly.

**Comment by ElBananaa** [comment]
> Minecraft Version: PaperMC 1.16.5
> MySQL: true
> BungeeCord: true
> 
> ```
> [18:51:33] [Async Chat Thread - #0/INFO]: [ChatControlRed 10.3.3] ChatListener listening to AsyncPlayerChatEvent at HIGH priority took 1387.67 ms
> [18:51:33] [Async Chat Thread - #0/INFO]: [standard] AmazedMender16: d
> [18:51:35] [Async Chat Thread - #0/INFO]: [ChatControlRed 10.3.3] ChatListener listening to AsyncPlayerChatEvent at HIGH priority took 916.24 ms
> [18:51:35] [Async Chat Thread - #0/INFO]: [standard] AmazedMender16: d
> ```
> 
> We're seeing high MS for ChatListener listening, this results in chat messages being send late/showing up late.
> 
> Debug.zip was privately shared with Matej via email, not uploading it publicly.

Hey,
Please wait for Kangarko then. I can't provide you any support if I don't have any informations.

**Comment by kangarko** [comment]
Thanks, registered your email, getting back to you in 1-2 days max

**Comment by kangarko** [comment]
Lets continue here https://github.com/kangarko/ChatControl-Red/issues/885

**Comment by AmazedMender16** [comment]
@kangarko we're already on #885

**Comment by kangarko** [comment]
Sorry I meant https://github.com/kangarko/ChatControl-Red/issues/309

**Comment by AmazedMender16** [comment]
@kangarko still seeing this high ms on 10.3.6
```
[ChatControlRed 10.3.6] ChatListener listening to AsyncPlayerChatEvent at HIGH priority took 1705.32 ms
[standard] AmazedMender16: d
```
Setting UUID_Lookup to false made a slight difference ( from 1700 to 500/600 ): https://github.com/kangarko/ChatControl-Red/issues/309#issuecomment-818819206
Can we improve this even further?

**Comment by kangarko** [comment]
The UUID_Lookup option changes how data is loaded when the player joins, it's not called when the player chats, not sure if that wasn't a fluke or is this consistent? Data is already loaded when chatting so there's no way this could change timings.

I've also written an article regarding optimizing performance, please check it out and try adjusting the options there : https://github.com/kangarko/ChatControl-Red/wiki/Performance

Mind doing a spark profiler for me please?

Also regarding your formats/variables.. not sure if I mentioned it but yes there's a ton of serialization going on right now, we need to get rid of md_5 library ... Paper already did that.. but it's a complex thing and I also want keep support Spigot not just Paper.
