### ISSUE TITLE
Problem with Timings

### ISSUE THREAD

**Issue by ttt0** [kangarko/ChatControl#886]
https://timings.pl3x.net/?id=b213a6c67640471a926fc9f69f2ab23d

Timings chatcontrol red red Do you have suggestions what can I do?
Will it cause any problems?

**Comment by ElBananaa** [comment]
Hey!
A lot of performance improvements were made in the latest version, could you confirm you are using these versions?
Recently, Kangarko implemented a config option to run some parts of the plugin async, it's in the plugin settings.yml file: `Async:`

However, keep in mind that this is an experimental feature that could break some operators like `require region` or custom variables who interact with data, worlds and chuncks. (You can find more informations above this part by reading the comment.
You should give it a shot, and see if it helps with performances a bit. :)

**Comment by kangarko** [comment]
From your Purpur timings I see you're using version 10.1.14 from December 2020. Please upgrade to 10.3.4 and use the Async option as Banana suggested, thank you.
