### ISSUE TITLE
1.16.5 : CHAT

### ISSUE THREAD

**Issue by msmanui** [kangarko/ChatControl#887]
Hello.

I want to use the chat by distance but using DeluxeChat prefixes and all that. Its possible? I mean, want DeluxeChat to manage the /tell, /pm, /r, etc... but only buy ChatControl Red for the chat by distance.

**Comment by ElBananaa** [comment]
> Hello.
> 
> I want to use the chat by distance but using DeluxeChat prefixes and all that. Its possible? I mean, want DeluxeChat to manage the /tell, /pm, /r, etc... but only buy ChatControl Red for the chat by distance.

Hey!
No this isn't possible, you can't use 2 different chat plugins, this will cause issues on both sides. You have to either use DeluxeChat or ChatControl-Red.

**Comment by WarnDa** [comment]
Hello,

I use deluxechat for chat and chatcontrol-pro (I'm upgrading to chatcontrol red, I just bought it) for private message since two years, I never got any issue :)
(on paper 1.12 and paper 1.16)

**Comment by WarnDa** [comment]
(Okay I tried chatcontrolred and channel feature block deluxechat, so you'll have to use chatcontrol red only)

**Comment by ElBananaa** [comment]
> Hello,
> 
> I use deluxechat for chat and chatcontrol-pro (I'm upgrading to chatcontrol red, I just bought it) for private message since two years, I never got any issue :)
> (on paper 1.12 and paper 1.16)

Well, you should never use 2 different plugins that have the same utility, 99,9% of the time, this will cause important issues.
Anyways, I'm closing this issue since ChatControl-Red isn't made to work with another chat plugin.
