### ISSUE TITLE
Does ChatControl Red and have Geyser support?

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#888]
I'm just wandering if ChatControl Red has Geyser support or not before I set it up?
Thanks

**Comment by ElBananaa** [comment]
Hey!
I didn't know plugins needed to support Geyser.
Anyways, if so, well, I don't think the plugin currently uses Geyser.
I'll leave this open so Kangarko could take a look at it and decide if that's something that can eventually get added.

**Comment by kangarko** [comment]
I have no idea sorry
