### ISSUE TITLE
Capitals in Rule Exceptions

### ISSUE THREAD

**Issue by TheMattVid** [kangarko/ChatControl#89]
Awhile ago, there was the problem where capitalization allowed people to bypass rules. That has been fixed.

The new problem now is that capitalization does not allow exceptions.

For example, if I have the word "crap", it is blocked.
Crap becomes *****
CRAP becomes *****

But if I allow the word "skyscraper" and someone tries to type it, here's what happens.
skyscraper stays as skyscraper
SKYSCRAPER becomes *****

**Comment by kangarko** [comment]
Thanks for reporting, will look into it.

**Comment by kangarko** [comment]
You have to adjust the matcher so it won't match skycraper, either using \b at the beginning:

match \bcrap

or adding an ignore operator:

match crap
ignore string skyscraper
