### ISSUE TITLE
1.16.5: How can I disable chatcontrol rules on discord

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#891]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

As far as I believe this is not possible (so this possibly should be a suggestion) but anyhow, I was just wondering if it is possible to disable rules on discord?

**background info￼** since I have a chat that links the chat of 6 public servers. On discord I set it up so the channels function the same way, in that I have 1 discord channel that shows the chat as you would see it if you were in game, however when a rule is triggered, such as a swear, because the single discord channel is linked to one channel across multiple servers, the swear filter is triggered 6 times in my case because I have chat linked up across 6 servers. I personally am happy to disable the rules completely as I only allow staff to chat via discord However I can imagine the issue I have addressed above could be problematic for other server owners.

**Comment by kangarko** [comment]
Thank you, I'll add the "ignore discord" operator to ignore certain rules from Discord. Thanks for sharing your setup though.

**Comment by wearenoobsuk** [comment]
Adding onto this without opening a new issue, I hope that's ok! I had this issue, And adding ignore discord works great, as it was running my litebans warning command like 8 times (on all servers lol) issuing 8 warnings to the discord name, Meaning you could change your discord name and get anyone banned by swearing.

But the issue now is, Anybody can swear through discord, I need some form of separate modification of messages coming through discord?  Any help on this would be massively appreciated. 

**group instantwarn
ignore perm chatcontrol.bypass.swear
ignore discord
then console warn {player} Please do not swear here, we are family friendly 
then notify chatcontrol.notify.swear &8[&7Swear&8] &7{player}: &f{original_message}
then discord monitor **Swear** By {player} = {message}
then deny**

I'm unsure if theres a way to do this currently? That I'm not seeing? I know about the if sender is discord, but that only seems to apply to the initial format .yml  files, Which seem unaffected by the Rule catches. 

Been scratching my head over this, I do actually have a discord bot that removes the swear from discord, But discordsrv/CCRED sends it to minecraft right before the bot grabs it, So it's unfortunately not a solution,

Any light on this would be awesome, Thankyou
