### ISSUE TITLE
Question, Does anyone have the plugin messages translated into Spanish?

### ISSUE THREAD

**Issue by DavidForge** [kangarko/ChatControl#892]
Hi, I hope I can ask this here.

I just want to know if by any chance someone has the plugin messages translated into Spanish.

**Comment by ElBananaa** [comment]
> Hi, I hope I can ask this here.
> 
> I just want to know if by any chance someone has the plugin messages translated into Spanish.

Hey!
Of course, you can ask questions here!
Unfortunately, there's no Spanish translation yet, but feel free to make one and send it to Kangarko! :)
Would you like to know anything else, or may I close this issue?

**Comment by DavidForge** [comment]
Oh, ok, thanks ^^
