### ISSUE TITLE
Mute/temp muted players should not have their death messages/login/logout messages shown to public but to staff only.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#893]
I have some custom death messages that show a players sword name when they kill someone, some players have found out they can name a sword to bypass a tempmute/mute from banmanager by naming a sword and killing their friend over and over.
Alternatively muted/tempmuted players from banmanager will log in and out to spam the chat.

Please can you make these messages muted from chat too in your death messages/login & out messages formatted by chatcontrol.

I use BanManager if it requires an API call.

**Comment by LogGits** [comment]
Side question that is somewhat relates, does CHC mute these messages (death, join/leave, chat) if the player was muted using and litebans?

**Comment by kangarko** [comment]
I will add a new Soft_Hide option to hide death/join/quit messages only from players who lack chatcontrol.bypass.mute perm :)

So just turn this on and give yourself that permission and you'll continue receiving these messages while others won't.
