### ISSUE TITLE
1.16.5: CHC is preventing my plugins sign change event to set colored text

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl#896]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

I have written my own chestshop plugin which uses a sign change event to colorize the text. All works fine, but if i install chc red nothing is working anymore and the text is replaced with nothing.

Without CHC red: https://prnt.sc/11bzhtc
With CHC Red: https://prnt.sc/11bzg6o

I have tested it multiple times and it is definently a chc red issue. CHC Red is breaking my whole well working chestshop system
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6303653/debug.zip)
.

**Comment by DevJoey** [comment]
This is because the new paper version using a own chatcomponent API. And i think chc is using some wierd packet stuff that is not compatible.

**Comment by kangarko** [comment]
Have you tried changing your listener priority to LOWEST or HIGHEST or even MONITOR?

**Comment by DevJoey** [comment]
> 
> 
> Have you tried changing your listener priority to LOWEST or HIGHEST or even MONITOR?

Changing to hight has fixed it. Thank you to much
