### ISSUE TITLE
Ignore permission – way to set how much players can player ignore

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#897]
Hi, I want to suggest improvement to ignore permission. TO allow us set there how much players can player ignore, so for ex. chatcontrol.command.ignore.5, 3 etc...

**Comment by kangarko** [comment]
Do you mean a limit for how many players can be ignored? Sorry this is not the core focus of our plugin, we already have branched into different areas and I feel this is too much to handle and too many potential bugs to be left undiscovered/unfixed by a single developer (myself).

**Comment by ElBananaa** [comment]
Hey!
I'll give my opinion as a server owner: I'm not sure to understand the point of this feature. Why would you limit the max amount of players you can ignore? Basically, it means that if you have the right to ignore 5 players max, and let's say there's 7 players bothering you, you can only ignore 5 of them.
