### ISSUE TITLE
1.12.2: When you use the auto-complete feature, you are disconnected from the server and The plugin doesn't work with an error message.

### ISSUE THREAD

**Issue by voicestory776** [kangarko/ChatControl#898]
Minecraft Version: 1.12.2
MySQL: true
BungeeCord: true

1. When you press the tab shortcut, the message "The server you are preoccupied with, you have been connected to a fallback server" appears and disconnects. 
Nothing is output to the bukkit
※ Removing ProtocolLi.jar solves the problem, but I must use this plugin

2. The plugin is disabled when an error is output
```
------------------------------------[ 14.04.2021 02:05:30 ]-----------------------------------
ChatControlRed 10.3.5 encountered a NoSuchMethodError
Running Paper 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_271
Plugins: LuckPerms v5.2.77, Vault v1.7.3-b131, ProtocolLib v4.6.0, ChatControlRed v10.3.5
----------------------------------------------------------------------------------------------
NoSuchMethodError org.yaml.snakeyaml.LoaderOptions.setMaxAliasesForCollections(I)V
	 at org.mineacademy.chatcontrol.lib.settings.SimpleYaml.saveToString(SimpleYaml.java:67)
	 at org.mineacademy.chatcontrol.lib.settings.ConfigInstance.saveDo(YamlConfig.java:2145)
	 at org.mineacademy.chatcontrol.lib.settings.ConfigInstance.lambda$save0$0(YamlConfig.java:2117)
	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	 at java.lang.Thread.run(Unknown Source)
----------------------------------------------------------------------------------------------

------------------------------------[ 14.04.2021 02:16:00 ]-----------------------------------
ChatControlRed 10.3.5 encountered a NoSuchMethodError
Running Paper 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_271
Plugins: LuckPerms v5.2.77, Vault v1.7.3-b131, ProtocolLib v4.6.0, ChatControlRed v10.3.5
----------------------------------------------------------------------------------------------

More Information: 
Failed to execute command /chc debug 
NoSuchMethodError org.yaml.snakeyaml.LoaderOptions.setMaxAliasesForCollections(I)V
	 at org.mineacademy.chatcontrol.lib.settings.SimpleYaml.saveToString(SimpleYaml.java:67)
	 at org.mineacademy.chatcontrol.lib.settings.SimpleYaml.saveToString(SimpleYaml.java:58)
	 at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68)
	 at org.mineacademy.chatcontrol.lib.command.DebugCommand.copyFilesToDebug(DebugCommand.java:93)
	 at org.mineacademy.chatcontrol.lib.command.DebugCommand.onCommand(DebugCommand.java:43)
	 at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:390)
	 at org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
	 at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:390)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
----------------------------------------------------------------------------------------------
```

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.12.2
> MySQL: true
> BungeeCord: true
> 
> 1. When you press the tab shortcut, the message "The server you are preoccupied with, you have been connected to a fallback server" appears and disconnects.
>    Nothing is output to the bukkit
>    ※ Removing ProtocolLi.jar solves the problem, but I must use this plugin
> 2. The plugin is disabled when an error is output
> 
> ```
> ------------------------------------[ 14.04.2021 02:05:30 ]-----------------------------------
> ChatControlRed 10.3.5 encountered a NoSuchMethodError
> Running Paper 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_271
> Plugins: LuckPerms v5.2.77, Vault v1.7.3-b131, ProtocolLib v4.6.0, ChatControlRed v10.3.5
> ----------------------------------------------------------------------------------------------
> NoSuchMethodError org.yaml.snakeyaml.LoaderOptions.setMaxAliasesForCollections(I)V
> 	 at org.mineacademy.chatcontrol.lib.settings.SimpleYaml.saveToString(SimpleYaml.java:67)
> 	 at org.mineacademy.chatcontrol.lib.settings.ConfigInstance.saveDo(YamlConfig.java:2145)
> 	 at org.mineacademy.chatcontrol.lib.settings.ConfigInstance.lambda$save0$0(YamlConfig.java:2117)
> 	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
> 	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
> 	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
> 	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> 	 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	 at java.lang.Thread.run(Unknown Source)
> ----------------------------------------------------------------------------------------------
> 
> ------------------------------------[ 14.04.2021 02:16:00 ]-----------------------------------
> ChatControlRed 10.3.5 encountered a NoSuchMethodError
> Running Paper 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_271
> Plugins: LuckPerms v5.2.77, Vault v1.7.3-b131, ProtocolLib v4.6.0, ChatControlRed v10.3.5
> ----------------------------------------------------------------------------------------------
> 
> More Information: 
> Failed to execute command /chc debug 
> NoSuchMethodError org.yaml.snakeyaml.LoaderOptions.setMaxAliasesForCollections(I)V
> 	 at org.mineacademy.chatcontrol.lib.settings.SimpleYaml.saveToString(SimpleYaml.java:67)
> 	 at org.mineacademy.chatcontrol.lib.settings.SimpleYaml.saveToString(SimpleYaml.java:58)
> 	 at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68)
> 	 at org.mineacademy.chatcontrol.lib.command.DebugCommand.copyFilesToDebug(DebugCommand.java:93)
> 	 at org.mineacademy.chatcontrol.lib.command.DebugCommand.onCommand(DebugCommand.java:43)
> 	 at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:390)
> 	 at org.mineacademy.chatcontrol.lib.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
> 	 at org.mineacademy.chatcontrol.lib.command.SimpleCommand.execute(SimpleCommand.java:390)
> 	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
> 	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
> ----------------------------------------------------------------------------------------------
> ```

Hey!
Sorry for the delay, I completely forgot to answer you. Could you please update ProtocolLib to the latest dev build, then try again. If the issue persists, then try to set `Listen_For_Packets` to `false` in the settings file.
Finally, would you mind providing us your debug output file?
If you wish to keep your configurations private, please send it to matej@mineacademy.org with the link to your issue, then wait for Kangarko. ;)

**Comment by kangarko** [comment]
@ElBananaa thanks for all the help, unfortunately I forgot to double check if the LoaderOptions class exists on MC 1.12 and older probably, solving today
