### ISSUE TITLE
Minecraft Version: 1.16.5 problem with JSON messages

### ISSUE THREAD

**Issue by Rongel92** [kangarko/ChatControl#899]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hi I've been using this plugin for a while now and ever since I did the last update 10.3.5 all the JSON msgs are not working
they are showing up but the click event doesn't work anymore also the hover event any idea what's wrong?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Hi I've been using this plugin for a while now and ever since I did the last update 10.3.5 all the JSON msgs are not working
> they are showing up but the click event doesn't work anymore also the hover event any idea what's wrong?

Hey!
I don't have a such issue. Could you please provide your `/chc debug` file? I'll try with it on my end.

**Comment by Rongel92** [comment]
correction it is working when i do it thru the format files but it doesn't work when I just type a tellraw json msg into the chat
the colors and text format works but the click event and hover doesn't

**Comment by Rongel92** [comment]
here is the debug.zip
https://ufile.io/vr7aa4w1

**Comment by Rongel92** [comment]
another question that i had is it possible to block the worldguard "Hey! Sorry, You cant change that here." message from showing up when players interact with my custom items?
its showing up in the chat everytime even tho its allowed in the region so I thought maybe I can block it thru the chat

**Comment by ElBananaa** [comment]
> another question that i had is it possible to block the worldguard "Hey! Sorry, You cant change that here." message from showing up when players interact with my custom items?
> its showing up in the chat everytime even tho its allowed in the region so I thought maybe I can block it thru the chat

Hey!
I'll try with your configs later today if I have some free time.
Regarding worldguard message, you can either silent it using chatcontrol packet rules, or by removing it in WorldGuard settings.
To do so, go in `WorldGuard/config.yml`, and under the `build-permission-nodes:` part, add this : `deny-message: ''`.
So this is how it should look like : 
```yaml
build-permission-nodes:
    enable: false
    deny-message: ''
````

**Comment by Ronglito** [comment]
i tried to change the deny msg but it still showing up it a different msg built into worldguard but how can I silent it with chat control any chance u can give me an explanation?

**Comment by ElBananaa** [comment]
Hey!
Since there's no answer from you, I'm considering this issue as solved, so I'm closing it. Feel free to keep commenting down below if you need anything else.

**Comment by Rongel92** [comment]
i was waiting for an answer from you :D
the msg i took care of I made the packet rule which worked so thanks
but the json msgs not working when im using tellraw

**Comment by ElBananaa** [comment]
> i was waiting for an answer from you :D
> the msg i took care of I made the packet rule which worked so thanks
> but the json msgs not working when im using tellraw

Oh yeah right, completely forgot that. In which file is your tellraw?

**Comment by Rongel92** [comment]
its not in a file i use it as a command so if u click on an npc for example it will send a tellraw command with a click and hover events that usually work but now stopped

**Comment by ElBananaa** [comment]
> its not in a file i use it as a command so if u click on an npc for example it will send a tellraw command with a click and hover events that usually work but now stopped

Please send me the command you used.

**Comment by Rongel92** [comment]
i figured it out it was a mistake in the command..
thanks for the help :)
