### ISSUE TITLE
Caps bypass rules/filters

### ISSUE THREAD

**Issue by iMaarten** [kangarko/ChatControl#901]
You can bypass any rules/filters by using capitals at random places within the words.

Minecraft Version: 1.8.8-1.16.5
MySQL: true
BungeeCord: false

**Comment by TheIntolerant** [comment]
In your settings file, under ``Rules:`` is ``Case_Insensitive:`` set to ``true``?

**Comment by ElBananaa** [comment]
Hey!
Since you didn't reply in 3 days, I'm closing this issue. Feel free to keep commenting down below if the issue persists.
