### ISSUE TITLE
ChatControlRed + ItemsAdder

### ISSUE THREAD

**Issue by Tylwen** [kangarko/ChatControl#902]
https://github.com/kangarko/ChatControl-Red/issues/853

**Comment by LoneDev6** [comment]
Hello @Tylwen , if you want you can create a ticket on my support server and then add me as friend, then send me a copy of ChatControlRed so that I can do some tests.
https://support.plugin.ga/

Thanks

**Comment by LoneDev6** [comment]
contacted via private message

**Comment by kangarko** [comment]
Thanks!
