### ISSUE TITLE
1.12.2  Received packet 

### ISSUE THREAD

**Issue by nicklly** [kangarko/ChatControl#905]
There was a problem with the plugin receiving the data packet, which caused the problem with the picture below  

![QQ截图20210417091910](https://user-images.githubusercontent.com/17716585/115097638-fc622f00-9f5d-11eb-9dda-2476ff5bccee.png)

debug file: [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6328474/debug.zip)
Plugins Version: 10.1.8
Minecraft Version: 1.12.2
MySQL: true
BungeeCord: true/

**Comment by nicklly** [comment]
when the player is sending message, The plugin will send the package twice, resulting in the same chat message appearing twice

**Comment by ElBananaa** [comment]
> when the player is sending message, The plugin will send the package twice, resulting in the same chat message appearing twice

Hey!
Please update to the latest version of the plugin then try again. The version you're using it completely outdated.

**Comment by kangarko** [comment]
Update please
