### ISSUE TITLE
1.16.5: Lag reason

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#907]
Hello, I've found the reason for lag ticks. The issue is that ChatControl does file writes (I guess) on the main thread and this takes too long. Some ticks reach 200 ms.

Here are two profilers results with ticks over 100 ms. There you can see that logging is responsible for all the lag:
https://spark.lucko.me/SOBls23IEu
https://spark.lucko.me/XTpVFzBBSW

I disabled the logging by setting logged commands and channels lists to `[]` in config. Now I get this:
https://spark.lucko.me/fAM3ZrdU6t

As you can see, there is no more lag. I hope this will help you a bit and you can make it async. (though it can be very dangerous for servers with only 1-3 cores available as they may not keep up and get overflown. You may possibly have to investigate the reason for so long writes. Also I would recommend to cache messages to write and write them in batches on a separate thread.)

Thank you

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by LogGits** [comment]
Just tried this and things seem to be faster even `/chc reload` (after removing the log csv aswell). Cheers :)

**Comment by kangarko** [comment]
Thanks, remade logging and now all I/O is done async in bulk each second. Thank you <3 Lemme know if timings have improved starting the next version!
