### ISSUE TITLE
"/chc forward" can't find other server

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#908]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true
Plugin Version: 10.3.5

![未命名](https://user-images.githubusercontent.com/55199486/115133483-2c333480-a03b-11eb-87f1-7f44f981e33f.png)

Command "/chc forward" can't find other server.

server.properties
![image](https://user-images.githubusercontent.com/55199486/115133585-022e4200-a03c-11eb-9170-dfc2b8ff8e7b.png)

Bungeecord - config
![image](https://user-images.githubusercontent.com/55199486/115133597-238f2e00-a03c-11eb-8a7c-b87253d4a945.png)

**I tried to use English but it still doesn't work.**

**Comment by TheIntolerant** [comment]
That command only works if someone is already on that specific server, so the reason you aren't seeing it, is simply because no one is online on that server.

**Comment by kangarko** [comment]
Check if someone's online on that server. ChatControl Red sees the existence of other network's servers based on the first online player on each server, otherwise we simply have no idea that server exists.
