### ISSUE TITLE
1.16.4 Plugin exception

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#91]
On a clean installation after logging in on the server I seem to get this error: https://pastebin.com/BsuQAFh3

**Comment by kangarko** [comment]
Looks like you have BungeeControl 2.x somewhere, ensure you have the new 3.x generation and removed the old one

**Comment by Sikatsu** [comment]
Ah, the test server is linked under the same proxy. I'm testing ChatControl Red without bungee though, but it still appears to communicate with BungeeControl 2.x then?

**Comment by kangarko** [comment]
Yes when it connects to any BungeeCord it will use the same channel as 8th generation used, so you have to swap all ChatControls and all BungeeControls accordingly
