### ISSUE TITLE
Auction advertising

### ISSUE THREAD

**Issue by Shmeeb** [kangarko/ChatControl#91]
I am unable to figure out how to allow people to bypass the anti-advertising when they are doing certain commands, like auctioning.

This is from my rules.txt:
![image](https://cloud.githubusercontent.com/assets/2238074/6661898/2af7d788-cb71-11e4-8bbe-5b5494b9b4f6.png)

When I do the command it shows this in console:
![image](https://cloud.githubusercontent.com/assets/2238074/6661901/445b6532-cb71-11e4-835c-0bdbd73b6eea.png)

This is the command I do:
![image](https://cloud.githubusercontent.com/assets/2238074/6661905/4e8d786a-cb71-11e4-9605-fbd9556d2a96.png)

**Comment by deswryn21** [comment]
On the settings.yml try adding auc under "Enabled_In_Commands". That should work in theory.

**Comment by kangarko** [comment]
Open handlers.yml, scroll down to the advertisement filter and add the command in the Ignored_In_Commands list.
