### ISSUE TITLE
Suggestion: Bungee supported join/leave messages (without switch) based on permissions

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl#910]
bungee supported join/leave messages (without switch) based on permissions @Sikatsu

**Comment by kangarko** [comment]
I didn't use the template format, gonna remove my license now :facepalm:

**Comment by Sikatsu** [comment]
Any news on this, though?

**Comment by kangarko** [comment]
Sorry for the delay, it got deprioritized due to other works, should get back on track within a few days.

**Comment by kangarko** [comment]
Sorry to turn this down, the entire system would need a port to BungeeCord which is something I don't have resources for right now.

**Comment by kangarko** [comment]
Noted, going to revisit this next week, maybe there's a feasible option that doesn't involve rewriting the whole setup.

**Comment by Sikatsu** [comment]
Thank you ♥️

**Comment by kangarko** [comment]
Alright I am getting the draft done, let's just review the points together to ensure I understand everything perfectly:

- Player joins the network > we broadcast his join message from Bukkit = done already
- Player quits the network > broadcast from Bukkit = done already
- Player switches from A to B on the network
  - do NOT broadcast join or quit message from Bukkit
  - broadcast switch message from Bungee = done already

- Also, @BearLeonLight and Sikatsu would you like to have a switch message (switch.rs file on Bukkit) to take advantage of the enhanced messaging system on ChatControl instead of BungeeControl?

So essentially we'd only stop join/quit messages from appearing when the player switches the network?

**Comment by Sikatsu** [comment]
I personally don't need server switch messages, only join/leave network messages that I can customize with the use of permissions per group/player.

**Comment by kangarko** [comment]
Okay I was thinking of implementing it this way:

1. Player joins or quits from Bukkit.
2. Bukkit prepares the message for all recipients on Bukkit as per conditions.
3. In the meanwhile, BungeeCord sends a packet that the player left/joined to Bukkit. We do this to prevent showing join/quit messages on switching servers.
4. Show the message normally on Bukkit and then broadcast over the network.

It looks doable, still much easier than porting the rule parser system to bungee. 

To have the same join/quit network messages, you'd have to retain the same messages/ configuration on all Bukkit servers. Is this acceptable?

**Comment by Sikatsu** [comment]
That's not a problem for me, as long as I can link the messages with a permission to a specific group or player. ^^

**Comment by kangarko** [comment]
You will link the permission for the sender right? You won't be able to link it to receivers on the network, as we already will generate a finished message that'll be sent from there... (Only receivers on the sending server get their conditions checked.)

**Comment by Sikatsu** [comment]
To a group, so for example when a Patreon joins it will say [+] [<3] Sikatsu, but for others it will say the normal [+] Sikatsu since they don't have that permission.

**Comment by kangarko** [comment]
Here it gets complicated.. . we need to compile sender's information on the sending server because there's no "instance" of the sender on the network (such as that variables wouldn't work) and that's tied with the receivers. 

Okay at least I can make the loop compile the network message from the what is built for a receiver other than the sender.

**Comment by Sikatsu** [comment]
Wait, not sure if you understood me right.
For example player A bought Patreon, within his group Patreon is a permission that gives him the custom join/leave message [+] [<3] PlayerA, EVERYONE sees that. Player B who has not bought Patreon and is a regular player, just has the normal message [+] PlayerB.

**Comment by NoobcoreNetwork** [comment]
> Wait, not sure if you understood me right.
> For example player A bought Patreon, within his group Patreon is a permission that gives him the custom join/leave message [+] [<3] PlayerA, EVERYONE sees that. Player B who has not bought Patreon and is a regular player, just has the normal message [+] PlayerB.

Basically you want custom join/leave messages based on what group/permission they have.
I'd like this also. For switch messages if possible :p

**Comment by BearLeonLight** [comment]
> * Player switches from A to B on the network
>   
>   * do NOT broadcast join or quit message from Bukkit
>   * broadcast switch message from Bungee = done already

> So essentially we'd only stop join/quit messages from appearing when the player switches the network?

This is the function I want, but I also want the message to be displayed on Discord.

**Comment by BearLeonLight** [comment]
> Wait, not sure if you understood me right.
> For example player A bought Patreon, within his group Patreon is a permission that gives him the custom join/leave message [+] [<3] PlayerA, EVERYONE sees that. Player B who has not bought Patreon and is a regular player, just has the normal message [+] PlayerB.

This is because you should change the rules, and then add or leave the message, the authorized person displays the set message, but does not have the authority to display another?
![image](https://user-images.githubusercontent.com/52900334/116846577-23d22080-ac1b-11eb-8d24-397a0beaa37a.png)

**Comment by kangarko** [comment]
Got it. Porting the entire .RS system (in a limited form) to BungeeControl. Will let you know the progress! Yes including the switch messages.

**Comment by kangarko** [comment]
<img width="1168" alt="Screenshot 2021-05-07 at 20 41 32" src="https://user-images.githubusercontent.com/1918426/117494458-a2f58a80-af74-11eb-8e0f-4a9c48a122fb.png">
Very happy to announce that the port is successfully working.. haven't tested everything, tons of operators missing but you'll get the permissions and even javascript conditions to the extent possible. Tomorrow I can't work and Sunday I have to catch up on something else, but next week I can drop the bomb!

**Comment by kangarko** [comment]
Yeah and NO discord support yet. We'd have to pick a Spigot server where we send the packet about it... may add a config.yml option which server you want to use since DiscordSRV lacks BungeeCord support

**Comment by kangarko** [comment]
Status update: This is being worked on, slightly delayed, I put a note to continue working on this on Friday. Will try to push this prioritized!

**Comment by kangarko** [comment]
I released it!! Unfinished, please read the changelog and let me know @Sikatsu if you can get your patreon permission-based messages to work. Keep in mind we use the BungeeCord "hasPermission" check, so likely you'll need LuckPerms there too.

**Comment by Sikatsu** [comment]
I can also only seem to get the default group to work, luckperms is installed however. And what if you have multiple groups for example?

**Comment by Sikatsu** [comment]
Disregard my messages, after testing around with it I got it exactly how I wanted it! Thank you very much ^^

**Comment by Sikatsu** [comment]
I am trying to hide the join/leave messages from staff members using abort, while it seems to work I do get this error: https://pastebin.com/tW862kky

Am I doing it wrong?

**Comment by kangarko** [comment]
Please post me your RS file.

**Comment by Sikatsu** [comment]
I have actually solved it by setting the default join message permission to false for staff. Could be an idea to add support for vanish perhaps ^^

**Comment by kangarko** [comment]
Thanks, managed to add that in into the next version!

**Comment by Sikatsu** [comment]
@kangarko It seems the .rs files don't listen to the setting ''Ignored servers'', how do I disable the join/leave messages in certain servers? Like the test server we have linked.

**Comment by Sikatsu** [comment]
Other then that, I seem to have this error: https://pastebin.com/ESQwgV8w

**Comment by kangarko** [comment]
Thanks, feature added and bug fixed :)

**Comment by Sikatsu** [comment]
Hmm, I just updated (didn't see the update was released already) but there is another error: https://pastebin.com/0RSQfiDH

**Comment by kangarko** [comment]
Thanks, that will be patched.

**Comment by kangarko** [comment]
Alright the last version contains the following operators on Bungee. The green ones are commented out and they won't work since we don't have the player instance nor access to this information. I'm closing this, if something is urgently needed to be implemented let me know below.

<img width="580" alt="Screenshot 2021-05-30 at 20 15 44" src="https://user-images.githubusercontent.com/1918426/120115422-db5b4380-c183-11eb-8c40-7c7f79cb93b7.png">

<img width="630" alt="Screenshot 2021-05-30 at 20 15 34" src="https://user-images.githubusercontent.com/1918426/120115428-df876100-c183-11eb-8a77-cbab77629329.png">

**Comment by Sikatsu** [comment]
Is it possible to require two permissions that it will show a different join/quit message then if you have one?

Group A
Require sender perm join.patreon|join.immortal

Group B
Require sender perm join.patreon

Group C
Require sender perm join.immortal

So in case the player has both it will use group A, else it will use B or C depending on their permissions.

**Comment by kangarko** [comment]
I am sorry, the preferred way is to setup your permissions plugin differently than require two permissions.

**Comment by Sikatsu** [comment]
I'm not sure how I would do that and get the result I want. Because both permissions are in two different groups. But using script it worked as advised on the discord server ^^

**Comment by kangarko** [comment]
Then just go with a script for now :)
