### ISSUE TITLE
paper 590 : permission

### ISSUE THREAD

**Issue by Krejzu** [kangarko/ChatControl#912]
What is the permission to join automatically a channel on read and write?

**Comment by ElBananaa** [comment]
> What is the permission to join automatically a channel on read and write?

Hey!
To automatically join a channel in read/write mode, you must give the player this permission : `chatcontrol.channel.autojoin.{channel}.{mode}`.

So let's say I want my players to join the `global` channel in read mode, and the `general` channel in write mode, i'll give them : 
`chatcontrol.channel.autojoin.global.read` and `chatcontrol.channel.autojoin.general.write`.
They must also have this permission in order for the autojoin feature to work properly : `chatcontrol.channel.join.{channel}.{mode}`.

You can find more infos about this on the wiki : https://github.com/kangarko/ChatControl-Red/wiki/Channels#auto-join
