### ISSUE TITLE
Improvement to Private Chat Channels

### ISSUE THREAD

**Issue by Revanrose6** [kangarko/ChatControl#913]
The following 2 Impovements I think would help improve the usage of the plugin:

1. Ability to create channels ingame via commands

Would allow for more streamlining of channel creation. ie: If I want a player to be able to have their own private channel for their friends/group, this would allow my staff to create a channel in game that does not require config editing. I think for any server this can be helpful.

2. Ability to set passwords to channels

Harkening back to private channels for a group. Currently, in order to access a channel you need the right permissions, without setting up a custom command to allow a player who 'owns' the channel to give or take that permission away, this would allow that player to only give out the password to those whom they want. Any server that uses a Guild System or just wants people to be able to decide who is in their conversation would very likely appreciate this.

Thank you for taking the time to read this.

**Comment by kangarko** [comment]
Thanks so much! Pulled to roadmap, no ETA yet.
