### ISSUE TITLE
1.16.5: DecoderException

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl#914]
https://i.imgur.com/SO3dtOT.png

User receives a disconnect when sending a large chat message.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Looks like his message combined with your format caused this, mind sending me your formats/ and variables/ (if needed) folder please?

**Comment by Skizzles** [comment]
[Files.zip](https://github.com/kangarko/ChatControl-Red/files/6351402/Files.zip)

**Comment by kangarko** [comment]
Thanks, I'm on it, will review and patch by Monday at max.

**Comment by Skizzles** [comment]
Thanks

**Comment by kangarko** [comment]
I apology, missed the deadline and forgot to return to you, I'll be sitting down with this in 24h

**Comment by Skizzles** [comment]
All good, let me know.

**Comment by kangarko** [comment]
Unfortunately I can't reproduce this, would you be able to send me the message that caused it? You can try sending your full debug just in case i missed something but I've tried the chat.yml formatting for the standard channel without issues.

If you're having ViaVersion on, try removing it temporarily to see if it goes away.

<img width="1556" alt="Screenshot 2021-04-30 at 11 09 03" src="https://user-images.githubusercontent.com/1918426/116674081-7d7ce580-a9a4-11eb-8813-41bf1d0120f4.png">

**Comment by kangarko** [comment]
Alright so I artificially bumped the format size and started to see the kicks (albeit with a different kick reason). Added a safety mechanism to remove all interactive elements if that happens.
