### ISSUE TITLE
1.16.5: DiscordSRV Glitch Over Bungee Channel

### ISSUE THREAD

**Issue by xivamnain** [kangarko/ChatControl#917]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hello, I have a problem with DiscordSRV with channel using Bungee, So first of all my configuration, its 2 Discord Bots 1 for each server "Hub Bot" and "Survival Bot" I have 3 servers in total including bungee, Hub , Survival and bungee itself, I am using ChatControlRed on both my Hub and Survival server and also BungeeChatControlRed on my Bungee server, I have 2 channels on each server, 1st channel is Main in Hub and second Staff, Also in survival same channels Main and Staff, My Discord has 3 channels, 2 Main channels 1 for hub and one for survival named Hub and Survival of course and the other channel is for staff members and is connected to Staff channel, So now that i have made myself pretty clear lets talk about the problem, So i have bungee set to true on my staff channel because i want my staff to talk across servers and also i have discord set to true so that it would be possible to talk from discord to staff channel, the problem is that because there are 2 bots on the discord and if for example you message from hub or survival but for example lets pretend the message is from hub so "/channel send Staff Hello this is from hub" Now this message does go to survival because of bungee but the problem is because the staff channel is connected to discord srv in both servers Hub and Survival, when the message goes to discord the "Survival Bot" thinks that the message was typed on discord and deletes it and pastes it again and so the Hub Bot thinks the same thing and a loop goes on of infinite messages, I know it may sound dumb or maybe i am not being much clear but i can show you on discord and my server for far far better explanation of what i mean. I don't know how this can be solved but in the meantime i have made 2 seperate channels under catagory staff, Hub and Survival for each server so the bots don't kill each other. But it would be very nice to have just one discord channel connected to entire bungee staff channel. Thanks

**Comment by xivamnain** [comment]
My Discord is Shivamzter#0,0,0,1 just in case if need more explanation just ping me i'll show you.

**Comment by TheIntolerant** [comment]
Hey, I am not 100% on this issue but as someone who has a bungee setup and also using DiscordSRV, my only suggestion is, have you tried using one single bot, for both (Hub and Survival) servers?

**Comment by xivamnain** [comment]
> Hey, I am not 100% on this issue but as someone who has a bungee setup and also using DiscordSRV, my only suggestion is, have you tried using one single bot, for both (Hub and Survival) servers?

Hello, i have tried using one bot and that will solve the issue indeed but i cannot really use a single bot because i want to sync discord roles with my shop/store items

**Comment by TheIntolerant** [comment]
Ahh I see, I guess only the plugin dev will be able to help with this in that case. :)

**Comment by xivamnain** [comment]
Can this issue get some attention is been 8 days

**Comment by kangarko** [comment]
Sorry! I'll be going through your case in 24h.

**Comment by kangarko** [comment]
Sorry I'm unable to help with this, there's no support for multiple bots, neither I have experience to make this work with multiple bots at the moment.

**Comment by xivamnain** [comment]
@kangarko hey, I understand that there's no support for multiple bots but the issue can be fixed in my opinion if there would be something to define some discord users in config so the users messages won't be filtered or removed/readded by chatcontrolred, think about it, If not possible than it is alright i have no problem using 2 channels for each server but would've been nice to use just one. thanks
