### ISSUE TITLE
Upgrade the channel list "/ch"

### ISSUE THREAD

**Issue by Toki-teki** [kangarko/ChatControl#918]
1.  It will be easier for players to use the channel list

Add the ability to connect to a channel in read mode without using commands.
1. / ch
2. Just click on the desired channel.

If the player has permission chatcontrol.channel.join.<channel>.read, then connect to the channel. Instead of writing that there is no access to chatcontrol.channel.join.<channel>.write
![2021-04-21_19 18 22](https://user-images.githubusercontent.com/74260160/115587443-610ee800-a2d6-11eb-90be-0bce85997bd6.png)

**Comment by kangarko** [comment]
Thanks, sorry for a late reply, this will get added!
