### ISSUE TITLE
Minecraft Version: 1.16 Silent autojoin

### ISSUE THREAD

**Issue by socksprox** [kangarko/ChatControl#919]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false, but using it

**Comment by socksprox** [comment]
How can i make my users autjoining silently the standard channel?

**Comment by ElBananaa** [comment]
> How can i make my users autjoining silently the standard channel?

Hey!
You can silent the channel join message, but this will apply to all channels.
To do so, in you localization file, under the `Join:` part, search for `Notification: "&8[&2+&8] &7Player {player} has joined '{channel}' channel."` and replace it with: `Notification: ""`.
