### ISSUE TITLE
Simpleclans Tag Integration

### ISSUE THREAD

**Issue by HeroWaar** [kangarko/ChatControl#92]
Hi,

First, thanks for the amazing plugin...
Now let's go to the issue, using SimpleClans 2.5.3 the clan tag should be showing after the local/global or with the player prefix but it appears before everything, can you make another var for the clan tag?

Look the example here: http://i.imgur.com/6Be9om4.png

I'll try to contact the SimpleClans manager too, but it would be great if you can do like this.

Once again, amazing plugin thanks!
(Sorry for my poor english)
Regards,
HeroWaar

**Comment by kangarko** [comment]
Hey, thanks to @phaed420 you can now use %clan to display your clan name.
Details at https://github.com/kangarko/ChatControl/commit/d054963fbc330b48d3acd7ef4071cb7915fc66db

**Comment by HeroWaar** [comment]
I don't that much experience so...

How I can implement that in my version? Or will u upload a new version of it?

Thanks

**Comment by kangarko** [comment]
If you can't compile it by yourself you'll have to wait for the next version. I cannot give any ETA since I don't have my workspace yet.

**Comment by HeroWaar** [comment]
Can you send me any tutorial?

Thanks
