### ISSUE TITLE
leaving channels

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#92]
For some reason if I leave myself logged in and then come back in a few minutes, I'm not in the channels I was in anymore? I have no idea why as I haven't been running any command and console doesn't seem to show anything. All I can see in console is this: [https://pastebin.com/uaiWKjPC](https://pastebin.com/uaiWKjPC)

**Comment by DoogiePC** [comment]
And another big issue, it seems local chat (plotsquared-plot) chats seem to be visible for everyone on the bungee server except the server its on. So if I have creative1 and have a plot chat, it works fine on just there, only people on the plot can see it. But if I go to creative-2, everyone on creative-2 can see anyone plot chats from creative-1.

**Comment by kangarko** [comment]
For the first issue, open join.rs and look for `message:` key that is empty. Remove that key.
 
Regarding the other issue, I will add "Bungee" option for channels so you can disable that channel from sending over BungeeCord

**Comment by DoogiePC** [comment]
I'm just curious to understand, how come having message: in join.js is causing it to randomly kick players out of channels while they're online?

**Comment by DoogiePC** [comment]
> For the first issue, open join.rs and look for `message:` key that is empty. Remove that key.
> 
> Regarding the other issue, I will add "Bungee" option for channels so you can disable that channel from sending over BungeeCord

I think that error message wasn't to do with my issue then. It would appear at random points, everyone online the server gets kicked out the channel they're in? Nothing shows in console or anything? Is there anything in the plugin that kicks players out of the channel if I use /ch join to force join them to a channel even if they don't have permission for that channel?
