### ISSUE TITLE
1.16.5: I want do a bypass in discord for delay in messages and more with discordsrv link.

### ISSUE THREAD

**Issue by DavidForge** [kangarko/ChatControl#920]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hello, I have communicated some mc channels of the chatcontrolred with some of discord with the discordsrv but I want the delay and others to not take effect when speaking, which I cannot do, I have not found in the settings.yml or in the wiki the shape.

Is there any way to do it?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hello, I have communicated some mc channels of the chatcontrolred with some of discord with the discordsrv but I want the delay and others to not take effect when speaking, which I cannot do, I have not found in the settings.yml or in the wiki the shape.
> 
> Is there any way to do it?

Hey!
I'm not sure to fully understand what you're trying to do. If there's a delay on discord, you might have to edit the settings of your discord, and that would be completely unrelated to ChatControl-Red.

**Comment by TheIntolerant** [comment]
I believe they might be talking about the "chat delay" feature of ChatControlRed under "Anti-Spam", which I have actually mentioned in #922

**Comment by ElBananaa** [comment]
Alright, yeah, got it. Well, i'll leave this issue open so Kangarko could review it. :)

**Comment by DavidForge** [comment]
Sorry I dont talk english so good.
And yes, I am talking of #922.

I say because I want to disable that by example: 
![test1](https://user-images.githubusercontent.com/37558093/115965165-ffde5300-a527-11eb-91fb-c9db05f0e1af.png)

In settings.yml only are for disable in x channel the delay of the chat, and is not a full fix anyway.

**Comment by kangarko** [comment]
Will have a look for possible options here in 24h

**Comment by TheIntolerant** [comment]
I think there there needs to be an option in the settings file, as permissions isn't currently a viable ￼solution without there being support for [discord linking](https://github.com/DiscordSRV/DiscordSRV/wiki/linking) even than I'm not 100% if that would work

**Comment by kangarko** [comment]
In the next version you'll be able to disable filtering messages from Discord using the Integration.Discord.Filter_Chat option.

**Comment by DavidForge** [comment]
Ok thanks so much ^^

**Comment by DavidForge** [comment]
I have forgot say that work perfect, thanks :)
