### ISSUE TITLE
1.16.5: ":" convert to [#flpc-i]:[#flpc-1]

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl#921]
If I write the ":" the Chatcontrol convert to this: [#flpc-i]:[#flpc-1].
This bug only have in ChatControl Red 10.3.6. 10.3.5 version no convert the ":"

![115711557-f44a2b00-a373-11eb-8198-9c0cfee238fb](https://user-images.githubusercontent.com/8324198/115890887-bd4c4600-a455-11eb-87b1-a7c4f9524f3c.png)

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by TheIntolerant** [comment]
Hey,
I assume you are using a rule similar to this
```
match (,|\s)\/(\w+)
then replace [#flpc-i]&c$1/$2[#flpc-1]
```
If so, could you paste it below, so we can assist? To help work out what could be causing this issue, thanks

**Comment by andris155** [comment]
The ChatControl Red do this with full default settings.

**Comment by kangarko** [comment]
Thanks, that's accidentally caused by the last version's change to add support for ItemsAdder, will correct this by Monday max, you can just stay on the older version for now.

**Comment by kangarko** [comment]
Shipped into the next version.
