### ISSUE TITLE
Discord bypass for Anti-Caps + Anti-Spam features

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#922]
**Description**
As it stands currently, there is no way to disable the following features of ChatControlRed for messages sent from discord. The features include the anti-caps feature, as well as these features under the anti-Spam section of ChatControlRed, the similarity check, limiting of messages, and message delays.

-----------------------------------

**1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**
It would allow many server administrators better control how ChatControlRed and Discord interact with each other.

-----------------------------------

**2. What would happen if we won't implement this feature? How's your server being affected?**
A different plugin may have to be sourced or people would be forced to disable the integration for ChatControlRed and DiscordSRV if they needed to have such things disabled for messages sent from discord.

**Comment by BearLeonLight** [comment]
try https://github.com/kangarko/ChatControl-Red/wiki/Rules#ignore-discord

**Comment by TheIntolerant** [comment]
The parts I have mentioned above aren't controlled by chatcontrol rules. They are solely controlled within the settings file, so therefore I cannot use that operator to create a bypass.

**Comment by kangarko** [comment]
Do you mean bypassing them via permission or disabling them via the settings.yml file?

**Comment by kangarko** [comment]
I think I understand now, let's continue at https://github.com/kangarko/ChatControl-Red/issues/920

**Comment by kangarko** [comment]
Thanks,  added Integration.Discord.Filter_Chat toggle for all of this.
