### ISSUE TITLE
Bungee Messages [join, quit]

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#924]
1. The beneficiaries are those who use Bungee.

2.
    I hope to change the (additional option) the join and exit messages between Bungee and Server, because both messages will be displayed when I switch servers.
For example, I will always see messages about him entering and leaving the server on the DC, but I don’t want to send join and leave messages to other players or on the DC every time he switches the server. I just want to The message set in [BungeeControl-Red/settings.yml] is displayed in Mimeacrft (currently in this state).
Then, the message set on the server is not displayed, only when he joins, enters, exits, and kicks out [Bungee] for the first time.

The conclusion is to manage the first join, enter, exit, and kick out through [BungeeControl] (Discord support).
Because I use a Discord channel for multiple servers, he will have this problem.

**Comment by BearLeonLight** [comment]
![image](https://user-images.githubusercontent.com/52900334/115945637-2fbd3480-a4ef-11eb-8acd-1ee504548301.png)
Move Server

**Comment by ElBananaa** [comment]
> ![image](https://user-images.githubusercontent.com/52900334/115945637-2fbd3480-a4ef-11eb-8acd-1ee504548301.png)
> Move Server

Hey!
I believe what you're looking for was added to the roadmap recentely (Check #910)

**Comment by kangarko** [comment]
Let's continue at #910
