### ISSUE TITLE
1.16.5: Messages no longer randomly selected.

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#925]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Thihs was tested on a fresh install. With regards to how ``then warn`` works, as stated [here](https://github.com/kangarko/ChatControl-Red/wiki/rules#then-warn-message) it says you can use ``|`` to define multiple messages, one of which will be selected randomly. Instead, it just adds a new line. I do not know if this was an intended change and the wiki just has outdated info but I thought I would report it anyway.

Example 1, in chat.rs
```
match test
then warn text 1|text 2|text 3
then deny
```
Instead of randomly selecting  text 1, text 2 or text 3, it would return as followed
**text 1**
**text 2**
**text 3**

I believe this is also related but in ``/chatcontrol-red/messages``, I only tested ``timed.rs`` but it seems while it says it will randomly select a message from ``messages:``, it does not, it just prints the messages from top to bottom.

Example 2, in timed.rs
```
group global
delay 1 second
message:
- Hey, {player}, did you know that we are running ChatControl?
- Check out &ahttps://mineacademy.org/plugins
- text 3
- text 4
```
Instead of randomly selecting a message, each message would simply get shown from top to bottom.

**Comment by kangarko** [comment]
Thanks, will check that out in 24h

**Comment by kangarko** [comment]
Thanks, corrected. You can now use

```
match test
then warn text 1|text 2|text 3
then warn one|two|three
then deny
```

To get both warn lines but each line will pick up one random word, cool.
