### ISSUE TITLE
1.16.5: {bungee_server_name} not using Server_Aliases from BungeeControl

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl#926]
Hi,
My problem is that when sending messages cross server, I want to have a prefix that specifies what server the message came from. However, the current method:
`    Prefix: '&8[&d{bungee_server_name}] '`
Does not look very nice as its the raw server name contained in `server.prop`

Rather, I would like to be able to use the Server name alias that is configured in BungeeControlRed here:
```
Server_Aliases:
  lobby: Lobby
  creative: Creative Server
```

This would make the chat look MUCH better. Alternativly, you could allow us to use placeholders in the prefix such as this:
![image](https://user-images.githubusercontent.com/51737378/115988526-89ac2000-a5fd-11eb-9a56-2c2a9b83a3f4.png)

However, placeholders don't seem to work...

Thanks!

**Comment by LeehamElectronics** [comment]
I also tried the following:
![image](https://user-images.githubusercontent.com/51737378/115988806-ac8b0400-a5fe-11eb-9688-aadbff48b136.png)

Which resulted in:
![image](https://user-images.githubusercontent.com/51737378/115988813-b9a7f300-a5fe-11eb-8836-d8d18fd6750b.png)

I refered to this in the wiki:
![image](https://user-images.githubusercontent.com/51737378/115988833-cb899600-a5fe-11eb-8739-3a2d357c2df3.png)

**Comment by ElBananaa** [comment]
> I also tried the following:
> ![image](https://user-images.githubusercontent.com/51737378/115988806-ac8b0400-a5fe-11eb-9688-aadbff48b136.png)
> 
> Which resulted in:
> ![image](https://user-images.githubusercontent.com/51737378/115988813-b9a7f300-a5fe-11eb-8836-d8d18fd6750b.png)
> 
> I refered to this in the wiki:
> ![image](https://user-images.githubusercontent.com/51737378/115988833-cb899600-a5fe-11eb-8739-3a2d357c2df3.png)

Hey!
For some reasons I couldn't reproduce this issue on my side with the latest version.
![image](https://user-images.githubusercontent.com/53318613/116587183-8628d980-a91a-11eb-9fa7-405305642fe8.png)
Is PlaceholderAPI installed? If so, make sur to download the `Server` expansion, then restart the server and try again

**Comment by kangarko** [comment]
Sorry for the delay, going to reproduce myself in 1-2 days.

**Comment by kangarko** [comment]
Correct, this is not used. I'm going to make this change in a few days.

**Comment by LeehamElectronics** [comment]
> > I also tried the following:
> > ![image](https://user-images.githubusercontent.com/51737378/115988806-ac8b0400-a5fe-11eb-9688-aadbff48b136.png)
> > Which resulted in:
> > ![image](https://user-images.githubusercontent.com/51737378/115988813-b9a7f300-a5fe-11eb-8836-d8d18fd6750b.png)
> > I refered to this in the wiki:
> > ![image](https://user-images.githubusercontent.com/51737378/115988833-cb899600-a5fe-11eb-8739-3a2d357c2df3.png)
> 
> Hey!
> For some reasons I couldn't reproduce this issue on my side with the latest version.
> ![image](https://user-images.githubusercontent.com/53318613/116587183-8628d980-a91a-11eb-9fa7-405305642fe8.png)
> Is PlaceholderAPI installed? If so, make sur to download the `Server` expansion, then restart the server and try again

Hey B,
Yeh I tried that too, did not work for me...

**Comment by kangarko** [comment]
Can't you just use the server name from server.properties file?

**Comment by kangarko** [comment]
Alright I made {bungee_server_name} properly take server alias from bungeecontrol's settings. This is done through sending a packet from bungee to spigot when a player joins... so you may only use it after he joined, such as when chatting.
