### ISSUE TITLE
1.16.5: Caps protection not always working

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#927]
When you typ OMG (small word with caps), the word after that is allowed in caps as well. Seems like the caps protection doesn't always work correctly.

![image](https://user-images.githubusercontent.com/5664135/116008652-f59a8280-a615-11eb-9d9b-ca3587459b25.png)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6372954/debug.zip)

**Comment by TheIntolerant** [comment]
I can confirm on a fresh install, even after changing ``Anti_Caps.Min_Message_Length`` and ``Anti_caps.Min_Caps_In_A_Row`` to ``1``.
I could still say this in chat (even though I would be warned about using too many caps)

``OMG BANAAN OMG BANAAN OMG BANAAN OMG BANAAN OMG BANAAN OMG BANAAN OMG BANAAN OMG BANAAN OMG BANAAN OMG BANAAN OMG BANAAN OMG BANAAN``

But the weird thing is I couldn't say this

``THIS IS A TEST`` 
without the caps being removed.

**EDIT**
As stated above, it seems any whitelisted words will allow the next word to also bypass the anti caps. 
So typing  ``LOL THIS LOL IS LOL A LOL TEST`` wouldn't be changed, the user would only get a warning.

**Comment by kangarko** [comment]
Great find! Will do a deep dive tomorrow and attempt to remake the filter.

**Comment by kangarko** [comment]
Patched.
