### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by arttwart** [kangarko/ChatControl#928]
**1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**
Velocity is a modern Minecraft proxy server better than Bungee Cord and all of its forks. It can handle players that two Bungee Cord instances can't handle. There is no such plugins to use on Velocity, so everyone consider using Bungee Cord and its forks. If everyone would support Velocity, there could be every alternative plugins for Velocity.

**2. What would happen if we won't implement this feature? How's your server being affected?**
Unfortunately I will not be able to use Chat Control Red. I don't want any other chat plugins, because Chat Control Red has every feature with best functions. It's an essential for a server.

Add support for Velocity proxy server: https://velocitypowered.com/

**Comment by ElBananaa** [comment]
> **1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**
> Velocity is a modern Minecraft proxy server better than Bungee Cord and all of its forks. It can handle players that two Bungee Cord instances can't handle. There is no such plugins to use on Velocity, so everyone consider using Bungee Cord and its forks. If everyone would support Velocity, there could be every alternative plugins for Velocity.
> 
> **2. What would happen if we won't implement this feature? How's your server being affected?**
> Unfortunately I will not be able to use Chat Control Red. I don't want any other chat plugins, because Chat Control Red has every feature with best functions. It's an essential for a server.
> 
> Add support for Velocity proxy server: https://velocitypowered.com/

Hey!
This feature has already been requested many time. Velocity support is currently WIP, so we can't provide you any infos about it neither any ETA unfortunately. :)

**Comment by kangarko** [comment]
Hey! I am communicating with the developer who reached out to me regarding this a few weeks ago, it's taking longer than expected. Sorry about that! I am thinking of this, I know how important/requested it is so rest assured I'll be either following with her or worst case make a new post to see if we can get another volunteer to help (financial reward included)
