### ISSUE TITLE
1.16.5: "$0" stops working if "then replace" is also used in a rule.

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#929]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hey, so I was testing something and found that ``$0`` stopped working in specific situations, after testing on a fresh server, I found that if you use the operator ``then replace`` you couldn't use $0 in operators such as ``then warn`` etc

This was the first thing I tested in ``chat.rs``

```
match (123)
then replace [#flpc-i]&7&o(Blocked)[#flpc-1]
then warn &cThis is a test &7$0
dont verbose
```

At first, I thought it was ``[#flpc-i]`` ``[#flpc-1]`` but even if I did...
``then replace (Blocked)`` instead of ``then replace [#flpc-i]&7&o(Blocked)[#flpc-1]`` I was still having the same issue, where $0 wasn't getting replaced.

It wasn't still I removed the ``then replace``
```
match (123)
then warn &cThis is a test &7$0
dont verbose
```

-----------------------------------------------

I was making a chat rule that uses the ``then replace`` operator alongside a ``then warn`` operator which that had ``$0`` in it, if this bug could be fixed that would be amazing, thank you!!

**Comment by kangarko** [comment]
Sorry for the delay, going to have a look in 1-4 days.

**Comment by kangarko** [comment]
Hey, just reviewed this, looks like a limitation of our current system. When I'm rewriting the parser I'll keep that in mind but for now I'll have to close this as "wontfix".
