### ISSUE TITLE
1.16.4 Migration not working

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#93]
The migration got stuck on a book.txt, and I think because of that the other migration settings didn't work either. I checked the migration.log and compared it to settings.yml, but the settings seem to be default still. I attached settings.yml, migration.log and error.log in the zip below. ^^

[CHC.zip](https://github.com/kangarko/ChatControl-Red/files/5555480/CHC.zip)

**Comment by kangarko** [comment]
Can you please send me your book.txt? Regarding the packet error, ensure you have BungeeControl 3.X from releases page and removed all else.

**Comment by Sikatsu** [comment]
I don't have a book.txt, does it require all folders to be there for the migration?

![image](https://user-images.githubusercontent.com/5664135/99520480-71bbda80-2993-11eb-8654-77d8d7223f6c.png)

**Comment by kangarko** [comment]
You should have this in rules/ folder of old ChatControl or doesn't you?

**Comment by Sikatsu** [comment]
Yeah but I didn't copy that folder since I didn't need to migrate it. I only copied the stuff that I needed to migrate ^^

**Comment by kangarko** [comment]
Thanks, I will fix that
