### ISSUE TITLE
1.16.5: Chatcolour gui custom colour formats

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#931]
Is it possible to setup custom formats for chatcolours?
e.g. I want to do some sort of rainbow gradient with custom item model in the GUI with a perm like `chatcolor.guicolor.rainbow` or have special gradients for events, etc. Is this possible with the current setup?

**Comment by TheIntolerant** [comment]
I am not sure about the gradient in ``/chc color`` but if it is possible to use such commands, you cannot use chatcontrol to use it, if it is not already in the GUI for ``/chc color``

I personally use another plugin to create a custom GUI with the base command ``/chatcolor`` and run the commands ``/chc color <color> reset {player}`` etc in the console.

**Comment by kangarko** [comment]
Thanks, not right now but I'll take that as a suggestion! We only support gradients that are hardcoded in your formats.
