### ISSUE TITLE
Discord Format / Rules Issue

### ISSUE THREAD

**Issue by NoobcoreNetwork** [kangarko/ChatControl#933]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true
Fully upto date on all plugins. 

Adding onto this closed issue, https://github.com/kangarko/ChatControl-Red/issues/911 I hope that's ok! I had this issue, And adding ignore discord works great, as it was running my litebans warning command like 8 times (on all servers issuing 8 warnings to the discord name, Meaning you could change your discord name and get anyone banned by swearing.

But the issue now is, Anybody can swear through discord, I need some form of separate modification of messages coming through discord? Any help on this would be massively appreciated.

group instantwarn
ignore perm chatcontrol.bypass.swear
ignore discord
then console warn {player} Please do not swear here, we are family friendly
then notify chatcontrol.notify.swear &8[&7Swear&8] &7{player}: &f{original_message}
then discord monitor Swear By {player} = {message}
then deny <<< **I only need this part on messages sent from discord to minecraft**

I'm unsure if theres a way to do this currently? That I'm not seeing? I know about the if sender is discord, but that only seems to apply to the initial format .yml files, Which seem unaffected by the Rule catches.

Been scratching my head over this, I do actually have a discord bot that removes the swear from discord, But discordsrv/CCRED sends it to minecraft right before the bot grabs it, So it's unfortunately not a solution,

Any light on this would be awesome, Thankyou

**Comment by TheIntolerant** [comment]
I'm not 100% sure if this will work but it should.

To prevent swearing but not get spammed with warnings, I suggest you only add this group to the ``group.rs`` file of **one** of your servers.

So obviously keep
```
group instantwarn
ignore perm chatcontrol.bypass.swear
ignore discord
then console warn {player} Please do not swear here, we are family friendly
then notify chatcontrol.notify.swear &8[&7Swear&8] &7{player}: &f{original_message}
then discord monitor Swear By {player} = {message}
then deny
```
but also add **but only add it to one server** to prevent multiple warnings.
```
group instantwarn discord
ignore perm chatcontrol.bypass.swear
require script {sender_is_discord}
then notify chatcontrol.notify.swear &8[&7Swear&8] &7{player}: &f{original_message}
then discord monitor Swear By {player} = {message}
then deny
```
the ``require script {sender_is_discord}`` should make it so this group is only applied to messages sent from discord
the downside is since you can only define a group once per rule, you would need to copy all of the swear rules in ``global.rs`` and add them again but change ``group instantwarn`` to ``group instantwarn discord`` for my suggestion to work thankfully you only need to do that one of the servers.

**Comment by NoobcoreNetwork** [comment]
That's very clever! This sounds like it would work it was the require script {sender_is_discord} I didn't know could be implemented that way  I'll give it a shot tomorrow and report back thankyou very much!

**Comment by TheIntolerant** [comment]
I forgot to add this but you might want to add ``then warn`` for the discord group, since I removed ``then console warn {player} Please do not swear here, we are family friendly``
so it looks something like
```
group instantwarn discord
ignore perm chatcontrol.bypass.swear
require script {sender_is_discord}
then warn {player} Please do not swear here, we are family friendly
then notify chatcontrol.notify.swear &8[&7Swear&8] &7{player}: &f{original_message}
then discord monitor Swear By {player} = {message}
then deny
```
then warn, basically just sends a message saying "(username) Please do not swear here, we are family friendly"

**Comment by NoobcoreNetwork** [comment]
I closed an issue and thought I fixed it but it basically related to this one. 

![Screenshot_20210428-092343_Discord](https://user-images.githubusercontent.com/62724418/116371658-900be900-a803-11eb-89ce-8b42dec34af0.jpg)
 
Its 'sending' the discord message multiple times at random. It only appears on minecraft once through.

Its not a 'rule' so I don't think I can only put it on one server. Any ideas?

**Comment by wearenoobsuk** [comment]
![javaw_nfE3xo4FhS](https://user-images.githubusercontent.com/62724418/116375220-fcd4b280-a806-11eb-8ff7-c87705a1918d.png)

unfortunately the original solution looks like its not possible to have 2 of the same things defined with different warnings

**Comment by NoobcoreNetwork** [comment]
Also, If I only put the rule on one server. It lets the discord message (the swear) go through on the other servers

**Comment by NoobcoreNetwork** [comment]
![javaw_rBICP1zlTP](https://user-images.githubusercontent.com/62724418/116385556-cd2aa800-a810-11eb-9b57-a7a0b80b76a7.png)


This is my PVP server after emptying the rules and global folder, in hopes that the rules on global folder in my main lobby server will still apply. But the word 'douche' is on the list in lobby and it lets you say it in PVP. So it would seem that, It's not applying over bungeecord but only on a per server basis. So putting anything on a singular server will just mean the other servers will lack the functionality.

Again. Unless i'm doing something wrong.

**Comment by TheIntolerant** [comment]
> I closed an issue and thought I fixed it but it basically related to this one.
> 
> ![Screenshot_20210428-092343_Discord](https://user-images.githubusercontent.com/62724418/116371658-900be900-a803-11eb-89ce-8b42dec34af0.jpg)
> 
> Its 'sending' the discord message multiple times at random. It only appears on minecraft once through.
> 
> Its not a 'rule' so I don't think I can only put it on one server. Any ideas?

I'm not on how to fix this.



> ![javaw_rBICP1zlTP](https://user-images.githubusercontent.com/62724418/116385556-cd2aa800-a810-11eb-9b57-a7a0b80b76a7.png)
> 
> This is my PVP server after emptying the rules and global folder, in hopes that the rules on global folder in my main lobby server will still apply. But the word 'douche' is on the list in lobby and it lets you say it in PVP. So it would seem that, It's not applying over bungeecord but only on a per server basis. So putting anything on a singular server will just mean the other servers will lack the functionality.
> 
> Again. Unless i'm doing something wrong.

I haven't tried it myself but since it is only blocking it on one server, I assume that means the group shown above would need to be added on multiple servers, you will get multiple messages saying not to swear unless you only have the ``then warn`` operator in one of the groups instead of all 8.

So that one server has 
```
group instantwarn discord
ignore perm chatcontrol.bypass.swear
require script {sender_is_discord}
then warn {player} Please do not swear here, we are family friendly
then notify chatcontrol.notify.swear &8[&7Swear&8] &7{player}: &f{original_message}
then discord monitor Swear By {player} = {message}
then deny
```
and all the other servers have
```
group instantwarn discord
ignore perm chatcontrol.bypass.swear
require script {sender_is_discord}
then notify chatcontrol.notify.swear &8[&7Swear&8] &7{player}: &f{original_message}
then discord monitor Swear By {player} = {message}
then deny
```
so that the ``{player} Please do not swear here, we are family friendly`` message, isn't repeated 8 times

**Comment by NoobcoreNetwork** [comment]
That seems to all be working, and as for the tripling up of messages, I seemed to have fixed this by changing use bot to send messages to false. And because im still using the 

group instantwarn discord
ignore perm chatcontrol.bypass.swear
require script {sender_is_discord}
then notify chatcontrol.notify.swear &8[&7Swear&8] &7{player}: &f{original_message}
then discord monitor Swear By {player} = {message}
then deny

I can still apply rules :D

Will do a real test over today and see how i get on

**Comment by NoobcoreNetwork** [comment]
So might have found a slight issue. Discordsrv kinda requires you to have a bot and bot token per server. So you don't hit rate limits And I'm running 8 servers. So basically. I tried it with 2 of my 2 servers for a test with 2 different tokens/bots and the exact same working config from my current setup. Only the first bot would work. The second new bot wouldn't push messages to minecraft from discord. However. What I said in the second server did go to discord. Any ideas? Bare in mind it's a global chat that all goes to the same discord channel.

Not sure if this is worth a different issue.
Spoken to discord srv and they have just directed me back here lol

Also the second bot was picking up the (server has started) bot messages from the first bot and sending them to minecraft 
Discordsrv does have the ignore bot messages enabled but im guessing cch over rides this function 


Thanks!

**Comment by kangarko** [comment]
Reading this right now, sorry for a late reply and thanks to Banana and others for catching up! Going on this tomorrow!

**Comment by NoobcoreNetwork** [comment]
> Reading this right now, sorry for a late reply and thanks to Banana and others for catching up! Going on this tomorrow!

Awesome. Just to confirm it's not a config issue of mine and is in fact an issue? 
Edit: Im guessing you commented on the wrong issue because banana is in the previous issue not this one lol

**Comment by kangarko** [comment]
Okay so in the next version I added much faster native support for "require discord" and "ignore discord" operators, you should just have two rules as @gone-incognito explained using those.

Regarding the two bots, I am afraid I can't help here, no idea how to configure this with more than one bot, as a last resort you could find a dev to make an extension for chatcontrol or discordsrv to filter duplicate messages.

Just to be clear, in the next version, set Debug to [discord] in settings.yml to see if indeed ChatControl Red is sending multiple messages to your Discord or not. There will be a console message for every sent message.

**Comment by NoobcoreNetwork** [comment]
> Okay so in the next version I added much faster native support for "require discord" and "ignore discord" operators, you should just have two rules as @gone-incognito explained using those.
> 
> Regarding the two bots, I am afraid I can't help here, no idea how to configure this with more than one bot, as a last resort you could find a dev to make an extension for chatcontrol or discordsrv to filter duplicate messages.
> 
> Just to be clear, in the next version, set Debug to [discord] in settings.yml to see if indeed ChatControl Red is sending multiple messages to your Discord or not. There will be a console message for every sent message.

The issue regarding multiple bots isn't it duplicating. The issue is the second bot on the second server just doesn't send the messages Im not sure why it wouldn't work tbh

Setup 

Survival. Discordsrv installation with its own bot token and ccr hooked

Skyblock: Discordsrv installation with its own bot token: and ccr hooked.

This setup only works on whatever server loads first. In my case its survival. The last server doesn't work

Without using chatcontrol this discordsrv function works so I'm sure it could be implemented with ccr

Thanks :)

**Comment by kangarko** [comment]
Thanks for sharing. I'll look into it when I have time but adding support for multiple bots is not on our priority list right now. I recommend you can completely disable Integration.Discord.Enabled in settings.yml for ChatControl and use DiscordSRV's own integration temporarily.

**Comment by NoobcoreNetwork** [comment]
Completely understand, thanks for everything you do kangarko :)
