### ISSUE TITLE
Adding other plugins spy functions to the Spy "channel" of Chat Control - Red

### ISSUE THREAD

**Issue by dwebeklint** [kangarko/ChatControl#934]
Hello, and thank you for a great chat plugin!

I have a question if it is possible to add other plugins Spy functions to chat Control- Red. 
I have kingdomsx which have a command /k admin spy,
the command is spying on the kingdomsx different internal chat channels for kingdoms / nations / alias and so on. 

Is it possible to get that in to Chat Control - Red spy function?

Minecraft Version: 1.16.45 (paper 529)
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Thank you! Not right now, we're already supporting dozens of plugins and with every new hook there's overhead and maintenance, but if multiple people request it then I can reconsider this.
