### ISSUE TITLE
1.16.5: UltraPermissions prefixes won't work

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/ChatControl#935]
So my issue is that I can't seem to let my prefixes to work. What do I mean with this?
I have setup my chat format but it doesn't show my prefix from Ultra Permissions.
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6399684/debug.zip)

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> So my issue is that I can't seem to let my prefixes to work. What do I mean with this?
> I have setup my chat format but it doesn't show my prefix from Ultra Permissions.
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6399684/debug.zip)
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false

Hey!
From what I found on UltraPermissions wiki, the placeholder used to show ranks is `%uperms_prefix%`, so try with `{uperms_prefix}` in your chat format.

**Comment by kangarko** [comment]
Use {uperms_prefix} as Banana says and it should work. Thanks Banana! Closing, however if you still need help comment below.

**Comment by Greazi-Times** [comment]
Oke will do that thank you

**Comment by Greazi-Times** [comment]
> > So my issue is that I can't seem to let my prefixes to work. What do I mean with this?
> > I have setup my chat format but it doesn't show my prefix from Ultra Permissions.
> > [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6399684/debug.zip)
> > Minecraft Version: 1.16.5
> > MySQL: false
> > BungeeCord: false
> 
> Hey!
> From what I found on UltraPermissions wiki, the placeholder used to show ranks is `%uperms_prefix%`, so try with `{uperms_prefix}` in your chat format.

So I have tried this and it doesn't work. I have entered the prefix but I don't get the message with my prefix.

**Comment by kangarko** [comment]
Try installing PlaceholderAPI and downloading the right expansion. If that doesnt work then unfortunately it's incompatible.
