### ISSUE TITLE
1.16.5: Chc purge [player] [player] inconsistencies

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#937]
Having issue with #900.

Command used `/chc purge [player1] [player2]`
Outcome, i see 1 of the players messages still, the other was gone. On another account, they saw both player messages gone. On another account they saw 1 players messages all gone.

I think the async aspect of `/chc purge` is causing issues. Please let me know if you're able to reproduce this.

CHC Red 10.3.6 on paper 1.16.5 build 634

**Comment by kangarko** [comment]
Thanks, made this run sync when multiple players are specified.
