### ISSUE TITLE
1.16.5 - Allow Unicode Characters

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#939]
Just a quick question, I'm wandering how I could allow Unicode Characters on my server so they can be used in chat my players

Thanks! :D

**Comment by kangarko** [comment]
By default we're not blocking unicode. You can however, check if there's any rules such as the one below, in your rules/ folder (for example in the chat.rs file). Remove those.

<img width="782" alt="Screenshot 2021-05-01 at 15 53 12" src="https://user-images.githubusercontent.com/1918426/116784625-87324600-aa95-11eb-9b50-acef2a9af34f.png">
