### ISSUE TITLE
1.16.4 RedisBungee - duplications in chat

### ISSUE THREAD

**Issue by tomet123** [kangarko/ChatControl#94]
When specific combination of players on servers duplicate massages.

For example:
Bungeecords B1 and B2
Servers S1 and S2
Players P1,P2,P3

Player P1 are on B1 and server S1
Player P2 are on B1 and server S2
Player P3 are on B2 and server S2

When user P1 send message, user P2 get this message directly. Then message is forward from B1 to B2 and from this bungeecord to P2 and P3. User P2 get message from B1 and B2 bungeecords.

**Comment by kangarko** [comment]
Hey, I'll a have look shortly but I am not a Redis developer — if you could have a look too to see if there's anything obvious you could help me fix I would greatly appreciate it!

**Comment by tomet123** [comment]
This is not easy to fix. I tryed to fix this yesterday, but there is problem related to how redis implemented. When user send message to global chat, chatcontrol send this massage to bungeecord(1), bungeecord forward this to all servers where are any player. Target server broadcast it to any player who are connected. Problem start when bungeecord(1) publish  massage  to redis and bungeecord(2) subscribe it. When is player on bungeecord(2) connected to same server with player from bungeecord(1) server get this message more then one time.

In my opinion there is two way how to solve this .
1) (with minimal affort) at spigot side create deduplicator. Every msg has some identificator like curent timestamp in miliseconds and if server get more than one msg with same identificator drop it. 
you cannot know count of bungeeords connected together. If user has for example 3 bungeecord with players in specific constelation every msg is triplicated.
2) add option for users who has more than one bungeecord to not use bungeecord for sending msg betwen servers and use some 3rd party tool like pure redis,apache kafka or mysql that can be used with some latency.

**Comment by kangarko** [comment]
Thank you for your explanation, unfortunately I am unsure if I'll be able to implement this. The 1. proposal sounds pretty good, I can look into it.

**Comment by kangarko** [comment]
Added. However not tested since I lack an environment like this:

https://bitbucket.org/kangarko/chatcontrol-red/commits/3a4b9a47984decd8db600f40ff30ab01fc5871bf

**Comment by kangarko** [comment]
@tomet123 seems like the problem is back, are you please able to have a quick look into our source code for this? https://bitbucket.org/kangarko/bungeecontrol-red/src/master/
