### ISSUE TITLE
Groupmanager error

### ISSUE THREAD

**Issue by matthijspc** [kangarko/ChatControl#94]
I have added the permission nodes to the groupmanager groups file.
But it wont work.
How can I fix this?
https://gyazo.com/a1722d5c9b1c44b15037248dfdea4670

**Comment by kangarko** [comment]
What permission nodes do not work and what is the expected behaviour?

**Comment by kangarko** [comment]
Not a bug. Permission nodes has been well tested and it is a minor mistake on your side most probably. Bug me if I am wrong.
