### ISSUE TITLE
1.16.5: Translater on message

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/ChatControl#940]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Is it possible to get a link to translater with the message that has been send.
So the message for example
[Owner] Steve: Hey hello there I am steve.
The hover event above the message so "Hey hello there i am steve. will give a link to translate where than the message will be translated to the language he wants?

**Comment by kangarko** [comment]
Thank you, we're not planning on adding this feature right now.
