### ISSUE TITLE
1.16.5 Players get periodically kicked out of the channels even with the join permission

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#941]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

Attaching the debug output: [https://ufile.io/71hnueh7](https://ufile.io/71hnueh7)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: false
> 
> Attaching the debug output: https://ufile.io/71hnueh7

Hey!
I tried to reproduce this issue, but unfortunately, I wasn't able to. Please update your plugins (Especially luckperms) to the latest recommended version for your server version, update paper to the latest version, and also enable `Debug: [channel]` in chatcontrol's config file, so we can get more informations about what's happening when player's are getting kicked of the channels.
EDIT: Also update chatcontrol to the latest version.

**Comment by kangarko** [comment]
When are the players getting kicked out — on joining? In that case, there should be "Tip" messages in your console when that happens. Please wait for them and post them here.

**Comment by nikitushu2** [comment]
Luckperms and ChatcontrolRed have been updated. Paper has been updated. `Debug: [channel]` has been added.

Players get kicked out randomly, not on joining.

I'll wait for the kick and let you know. It's hard to tell when it happens as it happens on its own, and there is nothing I can do to cause this behavior (which might be wrong as we may find out later)

**Comment by nikitushu2** [comment]
Okay, I have just noticed that I am not longer in the local channel (plotchat), and that I am in the global in the write mode. Though before it I was in local with write mode and global with read mode, and I did not switch channels on my own.

Attaching the debug: [https://ufile.io/duegjsaz](https://ufile.io/duegjsaz)

**Comment by ElBananaa** [comment]
> Okay, I have just noticed that I am not longer in the local channel (plotchat), and that I am in the global in the write mode. Though before it I was in local with write mode and global with read mode, and I did not switch channels on my own.
> 
> Attaching the debug: https://ufile.io/duegjsaz

Hey!
Unfortunately, as said above, we can't provide you any support if you don't give us what we asked above. I wasn't able to reproduce your issue neither on my prod server nor on 2 different test servers. So we actually need the server logs when a channel switch happens with tips messages enabled.

In the meantime, the only suggestion I can give you is to make sure your permissions are correctly setup.

**Comment by nikitushu2** [comment]
Sorry, I didn't realize that the logs are needed.

Attaching the latest.log and the logs going before them (for the current day): [https://mega.nz/folder/ELAgRRwb#0PgEED_U8wYRQebVd7ZAhw](https://mega.nz/folder/ELAgRRwb#0PgEED_U8wYRQebVd7ZAhw)

**Comment by ElBananaa** [comment]
> Sorry, I didn't realize that the logs are needed.
> 
> Attaching the latest.log and the logs going before them (for the current day): https://mega.nz/folder/ELAgRRwb#0PgEED_U8wYRQebVd7ZAhw

Alright, so this is what I can see in your latest.log : 
```
[19:25:31] [Server thread/INFO]: [ChatControlRed] TIP: Joining player to his saved channel global in mode write
[19:25:31] [Server thread/INFO]: [ChatControlRed] TIP: Not joining Dr_Mmm to channel global because he left it manually
[19:25:31] [Server thread/INFO]: [ChatControlRed] TIP: Not joining Dr_Mmm to channel local because he left it manually
[19:25:31] [Server thread/INFO]: [ChatControlRed] TIP: Not joining Dr_Mmm to channel staffchat because he left it manually
[19:25:31] [Server thread/INFO]: [ChatControlRed] TIP: Not joining Dr_Mmm to channel helpop because he left it manually
```

Which just means you left the channels list above manually (It's literally written)
I can't personally do much about it. Once again, we would need to know exactly when this happens. So just ask your players to report you this issue everytime they notice it, with the date and the time, then send us the logs corresponding to this date/time.

**Comment by kangarko** [comment]
As Banana says, we don't join players to channels they manually left in the past. To fix this, set Channels.Ignore_Autojoin_If_Left to false in settings.yml

If you need any more help, simply comment below please!

**Comment by nikitushu2** [comment]
> Channels.Ignore_Autojoin_If_Left

Thanks this helps with my issue but it will only join players back on the next join. Meaning that they will stay "muted" (because kicked from the channels) unless they re-join, which is not a perfect fix.

After analyzing dozen of logs, here is the update of my issue:

Chatcontrol periodically kicks the players out of the channels **on their join of the server**. Chatcontrol says that they leave it manually but in fact, **they don't** (the kick happens milliseconds after the join, so it would be impossible for players to even type anything). Thus, I think there is some bug with the "kick problem on join". As I saw, this issue is addressed in the wiki but the offered solution (of setting the join perm to true) does not work for me.

What to do?

**Comment by kangarko** [comment]
@nikitushu2 so sorry for a late reply! There are the following console (see Lo.showTip) messages when we kick the player out of their channel on join:

_Note: There's two new messages that will start appearing from the next version just for you_

<img width="1178" alt="Screenshot 2021-05-17 at 17 51 02" src="https://user-images.githubusercontent.com/1918426/118518491-768dfb00-b738-11eb-9292-7c2f2eb5b04c.png">

<img width="1203" alt="Screenshot 2021-05-17 at 17 48 03" src="https://user-images.githubusercontent.com/1918426/118518040-0b442900-b738-11eb-8c30-3909687552d5.png">

Which one was that when they got kicked out please?

**Comment by nikitushu2** [comment]
"Not joining <player>to channel <channel> because he left it manually."

**Comment by kangarko** [comment]
That means you haven't turned Channels.Ignore_Autojoin_If_Left option off, which I thought you did?

> Thanks this helps with my issue but it will only join players back on the next join. Meaning that they will stay "muted" (because kicked from the channels) unless they re-join, which is not a perfect fix.

I don't understand on what occasion they get muted? If it's because of the kick on join, then ensure the option above is set off and re-post me your new console log message because it should be different now.

**Comment by nikitushu2** [comment]
> 
> 
> That means you haven't turned Channels.Ignore_Autojoin_If_Left option off, which I thought you did?
> 
> > Thanks this helps with my issue but it will only join players back on the next join. Meaning that they will stay "muted" (because kicked from the channels) unless they re-join, which is not a perfect fix.
> 
> I don't understand on what occasion they get muted? If it's because of the kick on join, then ensure the option above is set off and re-post me your new console log message because it should be different now.

It was already set off. Here is my updated debug: [https://ufile.io/2unsm26w](https://ufile.io/2unsm26w)

**Comment by kangarko** [comment]
Unfortunately I am going on an annual leave until July 2nd, will return back to your until then.
