### ISSUE TITLE
1.16.5: Sound Notify does not work with CMI

### ISSUE THREAD

**Issue by king-glitch** [kangarko/ChatControl#946]
Sound Notify feature sound does not work with CMI installed.
it said  https://pastebin.com/EhatVmvd

please add support this to cmi. Thank you.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Sound Notify feature sound does not work with CMI installed.
> it said https://pastebin.com/EhatVmvd
> 
> please add support this to cmi. Thank you.
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
As a temporary fix, you can try to disable CMI `/sound` command. It also seems pretty weird that this is currently blocking the plugin. This would probably mean that CMI is, for some reasons, blocking or modifying the vanilla sound system, which isn't a good thing, and in this case, you might want to report this issue on their github. I might be wrong tho, but you should definitely open an issue on their github to get more informations. In the meantime, let's wait for Kangarko :)

**Comment by kangarko** [comment]
Sorry this is incompatible with CMI.
