### ISSUE TITLE
1:16.5: Tab-Completion Feature doesn‘t work

### ISSUE THREAD

**Issue by masterhacka** [kangarko/ChatControl#948]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

No matter if I enable or disable the tab completion feature it doesn‘t work. Every player just can type a „/„ and press tab to see all commands. It should only be possible to players with the bypass permission. I hope you can help me.

**Comment by TheIntolerant** [comment]
Hey, can you send your ``Tab_Complete:`` part of the ``settings.yml`` file, thanks.

**Comment by masterhacka** [comment]
Here it is: https://pastebin.com/eiXZjL0W
I tried to enable it and also changed Whitelist to Blacklist

**Comment by ElBananaa** [comment]
> Here it is: https://pastebin.com/eiXZjL0W
> I tried to enable it and also changed Whitelist to Blacklist

Hey!
From what you send us, the tab-complete feature is disabled.
Also, could you please give us more informations about your environment? (or ideally, sending us your debug file)

**Comment by TheIntolerant** [comment]
Ohh, I think I know what their issue is. Basically '@blacklist' turns the commands listed there into a blacklist, thus only disabling the commands listed.

Since it seems you want to stop people from doing ￼/(tab) to see commands etc, you need to remove '@blacklist' and add the commands you want to to work with tab. Otherwise you will continue to have the issue where people can do /(tab), /a(tab) etc to see commands

**Comment by ElBananaa** [comment]
> Ohh, I think I know what their issue is. Basically '@Blacklist' turns the commands listed there into a blacklist, thus only disabling the commands listed.
> 
> Since it seems you want to stop people from doing ￼/(tab) to see commands etc, you need to remove '@Blacklist' and add the commands you want to to work with tab. Otherwise you will continue to have the issue where people can do /(tab), /a(tab) etc to see commands

That's right.
@masterhacka As gone-incognito said, try to remove the `@blacklist` line, and it'll turn the list into a whitelist, so basically, only commands listed here can be tab-completed.

**Comment by masterhacka** [comment]
> > Ohh, I think I know what their issue is. Basically '@Blacklist' turns the commands listed there into a blacklist, thus only disabling the commands listed.
> > Since it seems you want to stop people from doing ￼/(tab) to see commands etc, you need to remove '@Blacklist' and add the commands you want to to work with tab. Otherwise you will continue to have the issue where people can do /(tab), /a(tab) etc to see commands
> 
> That's right.
> @masterhacka As gone-incognito said, try to remove the `@blacklist` line, and it'll turn the list into a whitelist, so basically, only commands listed here can be tab-completed.

Great that works! Thank you so much.

**Comment by ElBananaa** [comment]
> > > Ohh, I think I know what their issue is. Basically '@Blacklist' turns the commands listed there into a blacklist, thus only disabling the commands listed.
> > > Since it seems you want to stop people from doing ￼/(tab) to see commands etc, you need to remove '@Blacklist' and add the commands you want to to work with tab. Otherwise you will continue to have the issue where people can do /(tab), /a(tab) etc to see commands
> > 
> > 
> > That's right.
> > @masterhacka As gone-incognito said, try to remove the `@blacklist` line, and it'll turn the list into a whitelist, so basically, only commands listed here can be tab-completed.
> 
> Great that works! Thank you so much.

Good to know!
Thanks again @gone-incognito :)
I'm closing this issue. Feel free to open a new one if you need anything else :D

**Comment by gone-incognito** [comment]
I might also add, genuinely speaking you can tell a command is registered if you can tab the command. One more final note, chatcontrol can actually replace this plugin used to create aliases, using rules in the commands.rs file.

**Comment by gone-incognito** [comment]
@AngellitoX  might also add, generally speaking you can tell a command is registered if you can tab the command. One more final note, chatcontrol can actually replace this plugin used to create aliases, using rules in the ``command.rs`` file.

For example, to create a ``/gamemode survival`` aliases, I would add this in the command.rs file in ``/plugins/ChatControl-red/rules``

```
match \/(gms)
require perm chatcontrol.aliases.gamemodesurvival {error_prefix} &cYou lack the ‘{permission}’ for this command.
then command gamemode survival
then deny
dont verbose
```
the perm ``chatcontrol.aliases.gamemodesurvival`` used in this example can be whatever you want

**Comment by Mattrolol** [comment]
I had the same exact issue but it wont disable tab complete on a bungee side Thank you.
