### ISSUE TITLE
Spy function

### ISSUE THREAD

**Issue by Okane84** [kangarko/ChatControl#95]
Hi, it seems that's missing this fundamental feature; admins need to read what players are writing in both local (when ranged chat is on) and private chats, with a permission like chatcontrol.chat.spy

**Comment by kangarko** [comment]
ChatControl does not have any private chat. If you want to listen to the private messages /pm or /tell and similar, use the Essentials feature called social spy. Enable by typing /socialspy and configure in essentials config.

I will be improving the permissions, soon.

**Comment by Okane84** [comment]
maybe i didn't explained or i miss something. 
for private messages (/tell etc) i already use essentials socialspy. my case is that i have to use ranged mode to make chat readable only in a certain range but enabling this in chatcontrol will make the local chats unreadable for admins until they are inside the range. to read local chat outside the range i have to install essentials chat and use his ranged mode and disable the chatcontrol's one. the collateral problem is that in logs we'll have the double the lines from both essentials chat and chatcontrol.
if i remove essentials chat i cannot spy the local chats using chatcontrol. I could provide you an example from my logs.

**Comment by kangarko** [comment]
In 5.0.8, if you give yourself chatcontrol.chat.spy permission you will see the messages outside the range.
