### ISSUE TITLE
1.16.5: Setting Colored Nicknames Does Not Work Well With Essentials Features

### ISSUE THREAD

**Issue by NoobcoreNetwork** [kangarko/ChatControl#950]
Hey! So I found a bug and pretty sure I know the reason why, I switched over to using chatcontrolreds nick feature (very handy btw) but I soon noticed an issue with essentials. When using color codes, chat control doesn't apply them in the correct format to the essentials userdata folder, (I'm aware chat control puts its nick inside essentials also to maintain the features) but it applies them like this inside essentials' 

Stored like this in essentials
nickname: &c&lEvident

When it should be like this inside essentials
nickname: §c§lEvident

This leads to messages by essentials showing the nickname being broken and showing the raw color codes aka '&c&lEvident is now afk'

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Thanks, will patch this.

**Comment by NoobcoreNetwork** [comment]
Thanks! looking forward to have this fixed as my players keep mocking me for being called &fJ&eO&fS&fH xD
