### ISSUE TITLE
Player NickName RGB gradient

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#951]
I hope my nickname supports RGB gradient support. If I use gradient ({#00e6ca>}player nickname{#e6cf00<}) for my <tag nick>, he will display <Picture 1>, but if I use CMI again (% cmi_user_display_name%) can be displayed, but it will cause Discord display problems <Picture 2, Picture 3>, I don’t know how I am going to fix it, and I hope that the management can adjust the tags of other players. Use it yourself.

This is a great feature for people who use the plug-in, and it can also synchronize nicknames across servers.

![image](https://user-images.githubusercontent.com/52900334/116845748-5418bf80-ac19-11eb-81c6-1ce53c6dbef8.png) ({NIck})
![image](https://user-images.githubusercontent.com/52900334/116846610-3c423b00-ac1b-11eb-950e-68de77350042.png) (Discord)
![image](https://user-images.githubusercontent.com/52900334/116846621-4401df80-ac1b-11eb-91ab-c42c1356659c.png) (%cmi_user_display_name%)

**Comment by BearLeonLight** [comment]
I found a way to cooperate with CMI.

**Comment by ElBananaa** [comment]
> I found a way to cooperate with CMI.

Hey!
Alright, good to know! :)
Closing this issue. Feel free to keep commenting down below if your need anything else.
