### ISSUE TITLE
Player Kick Event Error

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#952]
Hi, one of my test team were kicked from the server by Spartan Anti Cheats playerkickevent and ChatControlRed threw this Error

https://paste.helpch.at/ucitiwobod.sql

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

**Comment by ElBananaa** [comment]
> Hi, one of my test team were kicked from the server by Spartan Anti Cheats playerkickevent and ChatControlRed threw this Error
> 
> https://paste.helpch.at/ucitiwobod.sql
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: false

Hey!
You're used an outdated version from what I can see with in your error log. Please update to the latest version and try again.

**Comment by 00Hrtz** [comment]
Thank you, ill close this for now and get back to you if it happens again.
