### ISSUE TITLE
1:16.5: Tab-Completion wont work with bungee

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#954]
Minecraft Version: PaperMC 1.16.5 Build 647
MySQL: true
BungeeCord: true 

I enabled tab-complete in Chat Control settings.yml, and it works, but It still shows bungee commands,
I also tried installing Bungee Control and enabled the hook to Bungee Control.
What am I missing?

**Comment by TheIntolerant** [comment]
This is normal behaviour, unfortunately the tab-complete feature in Chatcontrol-red, can only control tab completion for commands on the backend server e.g. spigot/paper servers etc. not including proxy servers such as bungeecord/waterfall etc.

**Comment by TheIntolerant** [comment]
To control tab-completion for commands on a proxy server, you will need to either source a plugin specifically for this or get a developer to make such a plugin.

**Comment by kangarko** [comment]
As gone said, we cannot "see" what commands are on BungeeCord since ChatControl filters this downstream, it's like we can only control what's inside the room but the room is inside a bigger room which we have no control over.

**Comment by kangarko** [comment]
For now just get a BungeeCord plugin specifically for this. We may consider porting this upstream in the future
