### ISSUE TITLE
mention can Add title

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#956]
chat mention add title
![6736eca40ea7fcf12f5df08d9757759f9ff45395](https://user-images.githubusercontent.com/75075197/117466583-772ed080-af85-11eb-9a02-349c8ccaea00.png)

Minecraft Version: 1.16.5
MySQL:  false
BungeeCord: true

**Comment by kangarko** [comment]
ChatControl doesn't add any titles, this is coming from another plugin. We're not planning on adding titles to mention right now.
