### ISSUE TITLE
1.16.5: CHC Taking hundreds of MS to send messages

### ISSUE THREAD

**Issue by cades66** [kangarko/ChatControl#957]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, my CHC is on a bungee setup with chat. However, it takes around 100MS for a chat message to have enter hit on it before it appears in chat. Why's that?

[09:59:39 INFO]: [ChatControlRed 10.3.8] ChatListener listening to AsyncPlayerChatEvent at HIGH priority took 225.86 ms
[09:59:39 INFO]: [Global RedenDaFox] damn
[09:59:41 INFO]: [ChatControlRed 10.3.8] ChatListener listening to AsyncPlayerChatEvent at HIGH priority took 108.25 ms
[09:59:41 INFO]: [Global cayoten] ye

It may be worth clarifying the lag only comes from one server that has kind of a heavy load. Any way I can fix this?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, my CHC is on a bungee setup with chat. However, it takes around 100MS for a chat message to have enter hit on it before it appears in chat. Why's that?
> 
> [09:59:39 INFO]: [ChatControlRed 10.3.8] ChatListener listening to AsyncPlayerChatEvent at HIGH priority took 225.86 ms
> [09:59:39 INFO]: [Global RedenDaFox] damn
> [09:59:41 INFO]: [ChatControlRed 10.3.8] ChatListener listening to AsyncPlayerChatEvent at HIGH priority took 108.25 ms
> [09:59:41 INFO]: [Global cayoten] ye
> 
> It may be worth clarifying the lag only comes from one server that has kind of a heavy load. Any way I can fix this?

Hey!
There are multiple things you can give a shot to fix this.
First of all, make sure all your plugins and dependencies, are up to date. Same thing with your server software.
To reduce the plugin load on the main thread, in the plugin settings file, look for the `Async:` part.
Just add the following code under it : (Keep in mind that, as said on the comment above this part, this can break some parts of the plugin such as some javascripts and some variables).
```yaml
  Async:
  - 'join'
  - 'quit'
  - 'kick'
  - 'death'
  - 'timed'
```
You could also try to disable the plugin internal logging system, this could greatly help.
I also recommend you take a look at your other plugins, and make sure this isn't related to any of them.

**Comment by kangarko** [comment]
@ElBananaa the chat lag reports are unaffected by the Async option, since that option only controls player-related messages :)

@cayoten please see https://github.com/kangarko/ChatControl-Red/wiki/Performance ... try disabling the Log option as Banana suggested, if that still won't help then try going over your formats/, rules/ and variables/ folders and try using the default rules/ then default messages/ then finally default formats/ to narrow down where the hogging format/rule/variable is/are, and proceed from there to remove it.
