### ISSUE TITLE
Player has joined global channel

### ISSUE THREAD

**Issue by masterhacka** [kangarko/ChatControl#958]
Hi there,

is there a way or a permission to disable this message?

**Comment by ElBananaa** [comment]
> Hi there,
> 
> is there a way or a permission to disable this message?

Hey!
To do so, in your localization file (`/plugins/ChatControlRed/localization/messages_en.yml` as example), search for the `Notification: "&8[&2+&8] &7Player {player} has joined '{channel}' channel."` message, and replace it with : `Notification: ''`
It should disable this message :)
