### ISSUE TITLE
1.16.5 : KIck, Discord message

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#959]
Minecraft Version: 1.16.5
MySQL: true/
BungeeCord: true/

Please tell me how to set the original KIck kick message, because it will be replaced by the content of RS, I don't know how to display it, /kick reason.
How to make KIck show the reason, not just show the simple message in RS, want to show the message that he was kicked out.

In addition, DiscordSRV’s messages are all MC’s game IDs displayed through Link. Can it display the player’s name (nick, display name, original name) on Discord, and then give different displays by checking the identity group on Discord.
(More like the new Native Variables, you can get the user name and nickname from Discord)

This function is more like a new rule. If the message comes from DC, the authority is detected through body grouping, and the in-game authority is not applied. For example, the rule is that he needs to have body group A, then the message prefix is added. This is body group A.

**Comment by ElBananaa** [comment]
Hey!
Did you try to simply remove the content of the kick.rs file?
I'm not sure if chatcontrol currently broadcasts kick messages in chat tho. Let's wait for Kangarko if what I suggested above doesn't work.

Regarding DiscordSRV part, I don't really understand what you're trying to explain.

**Comment by BearLeonLight** [comment]
![image](https://user-images.githubusercontent.com/52900334/117562827-7ce6fc00-b0d4-11eb-8f41-7cf766b9b05c.png)
This is the message that he was kicked out on the DC, but the player who was kicked out will see [Kicked out: Reason]

**Comment by BearLeonLight** [comment]
Another problem is that when I restart the server, the player will not have a message to leave.

![image](https://user-images.githubusercontent.com/52900334/117564522-03a0d680-b0df-11eb-93eb-993d6a8b2d41.png)

Only showing the joining message cannot show the leaving message.

**Comment by kangarko** [comment]
Our kick controlled is barely supported by Spigot. You should installed a ban management plugin to control player kick messages.

**Comment by BearLeonLight** [comment]
> Our kick controlled is barely supported by Spigot. You should installed a ban management plugin to control player kick messages.

I know, but he will not show me the kicking message. I just want him to show the reason for the kick. There is no function to manage kicks.

**Comment by kangarko** [comment]
Install a ban management plugin and use it to show the kick message from there.

**Comment by BearLeonLight** [comment]
> Install a ban management plugin and use it to show the kick message from there.

But the problem still exists. If I use the CMI kick cause, the player will see the KICK cause, but the game and Discord will not show the cause, I just want a simple support (I don’t know the code is not clear, but it’s not simple) , Just read the reason for the kick, and then let the management show it, I used the original command to produce the same situation.

**Comment by kangarko** [comment]
As explained I am unable to hook and get the true kick reason from your ban management plugin... I recommend you remove "kick" from the list at Messages.Apply_On to stop ChatControl Red processing kicks messages completely.

**Comment by BearLeonLight** [comment]
> As explained I am unable to hook and get the true kick reason from your ban management plugin... I recommend you remove "kick" from the list at Messages.Apply_On to stop ChatControl Red processing kicks messages completely.

Sorry, can I ask the last one, can't I use the original command?

**Comment by kangarko** [comment]
Sorry I don't understand your question. If you won't use ChatControl for kick messages you can use any command you'd like.

**Comment by BearLeonLight** [comment]
> Sorry I don't understand your question. If you won't use ChatControl for kick messages you can use any command you'd like.

I use Minecraft:kick to kick out the player. But how do I show the reason for the kick? My kick is not handled through other plugins. Can this support showing the reason for the kick?

**Comment by kangarko** [comment]
Install a third party kick management plugin. Looks like Spigot is just not giving us the right info in the playerkickevent we use, there's nothing I can do about it unfortunately, sorry about that.
