### ISSUE TITLE
1.16.4 | Issue with spaces in nicks

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#96]
# **Environment**
### **ChatControl Version**: ChatControlRed-10.0.7

- When using a nick with a space in it, you can't remove it using `/chc tag nick <player nick> off` even tho this is the tabcomplete command. You need to use `/chc tag nick <player> off` or `/chc tag nick list` and click on the nick you'd like to remove.

**Comment by kangarko** [comment]
We're not supporting spaces in nicks for internal reasons. I'll disable that ability in the next release completely.
