### ISSUE TITLE
Private Messaging over Bungeecord

### ISSUE THREAD

**Issue by masterhacka** [kangarko/ChatControl#960]
Hi there,

is it possible to do private messaging via the whole network? I always get the message: player not found when I am on a different server. Global chat is working fine

**Comment by TheIntolerant** [comment]
I have private messaging that works over bungee, it might be worth uploading your debug file, just do

/chc debug

**Comment by masterhacka** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6446477/debug.zip)

**Comment by BearLeonLight** [comment]
Do you have the chat function of CMI enabled?
If so, you need to close it first.
Then you need to give the chat color the right to use it or it won't be displayed.
It is more likely to be related to CMI's settings (permissions).

**Comment by masterhacka** [comment]
Thats it thank you so much!

**Comment by ElBananaa** [comment]
Hey!
Great, closing this issue!
Open a new one if you need anything else.
