### ISSUE TITLE
Color formatting

### ISSUE THREAD

**Issue by masterhacka** [kangarko/ChatControl#961]
Hi,

I installed ChatControl on every server in my network + on the proxy. When using my BanSystem the message in the chat is unformatted: https://i.imgur.com/dmXFGqg.png

I am using global chat as a default. I hope you can help me.

**Comment by ElBananaa** [comment]
> Hi,
> 
> I installed ChatControl on every server in my network + on the proxy. When using my BanSystem the message in the chat is unformatted: https://i.imgur.com/dmXFGqg.png
> 
> I am using global chat as a default. I hope you can help me.

Hey!
Did you enable ChatControl's channel system? You must use it in order to format the chat.
If this is already done, try playing with the formatter priority in chatcontrol config file (Don't forget to restart your server everytime you change the formatter).
If both things above don't work, would you mind sending us your `/chc debug` output file?

**Comment by masterhacka** [comment]
I will try changing the priority.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6446478/debug.zip)

**Comment by masterhacka** [comment]
Changing priority didn't work unfortunately. When typing /ban the colors are formatted. Only the notify message is unformatted. In the BanSystem config everything looks fine

**Comment by masterhacka** [comment]
I needed to change the color codes for example from &6 to §6 then everything is working fine.

**Comment by ElBananaa** [comment]
> I needed to change the color codes for example from &6 to §6 then everything is working fine.

Hey!
Good to know. It looks like an issue on BanSystem end tho.
You should probably report it to them.

Closing this issue,
Feel free to open a new one if you need anything else! :)
