### ISSUE TITLE
1.16.5: I can send messages in vanish (PremiumVanish) without the / at the end

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/ChatControl#963]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

I have reported this before but than I got if fixed only now it happend again no idea how.
**What did I do to get this?**
So it worked all fine for a week or so but once I restarted my server it is now sending my message even when I am in vanish.
I have no idea what might have caused this issue and how it happens.

Both my chc and Pv config are default on the priority. (The same as a week ago)
[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/6446266/debug.1.zip)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> I have reported this before but than I got if fixed only now it happend again no idea how.
> **What did I do to get this?**
> So it worked all fine for a week or so but once I restarted my server it is now sending my message even when I am in vanish.
> I have no idea what might have caused this issue and how it happens.
> 
> Both my chc and Pv config are default on the priority. (The same as a week ago)
> [debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/6446266/debug.1.zip)

Hey,
Please update chatcontrol and all your other plugins/dependencies/server software, then try again.

**Comment by Greazi-Times** [comment]
> > Minecraft Version: 1.16.5
> 
> > MySQL: false
> 
> > BungeeCord: false
> 
> > 
> 
> > I have reported this before but than I got if fixed only now it happend again no idea how.
> 
> > **What did I do to get this?**
> 
> > So it worked all fine for a week or so but once I restarted my server it is now sending my message even when I am in vanish.
> 
> > I have no idea what might have caused this issue and how it happens.
> 
> > 
> 
> > Both my chc and Pv config are default on the priority. (The same as a week ago)
> 
> > [debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/6446266/debug.1.zip)
> 
> 
> 
> Hey,
> 
> Please update chatcontrol and all your other plugins/dependencies/server software, then try again.

Will updated them all today and see what it does.

**Comment by kangarko** [comment]
Assuming updating will fix this, closing.

**Comment by Greazi-Times** [comment]
Hi there I had the same issue again only this time I found out what the problem was.
Premium Vanish his priority of chat needs to be on `HIGH` 
The priority of chc needs to be on `HIGHEST` This has fixed my issue and I think this would be something to add to the wiki as well so people that may encounter the problem will find the solution quicker.

**Comment by ElBananaa** [comment]
> Hi there I had the same issue again only this time I found out what the problem was.
> Premium Vanish his priority of chat needs to be on `HIGH`
> The priority of chc needs to be on `HIGHEST` This has fixed my issue and I think this would be something to add to the wiki as well so people that may encounter the problem will find the solution quicker.

Hey,
Thanks for getting back to us.
The issue here is that the config depends on other plugins I guess. I dont have a such issue on my server with the default priorities in both plugins, and I guess it's the same for a few other users, so the best thing we could do is simply suggesting to play with the priorities of both plugins.
