### ISSUE TITLE
1.16.5: Over 160 players Payload may not be larger than 32767 bytes

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [kangarko/ChatControl#964]
Minecraft Version: 1.165
MySQL: true
BungeeCord: true

The problem is that when more than 160 players join bungeecord server all players above 160nr are beeing kicked from server with message like that:
[Rozgadany] disconnected with: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Payload may not be larger than 32767 bytes

So its like:
160 (up to 164) players
2 players join, 162 players
~~message/spy/sth arrives (probably)~~ After a while i think that its after player joining server
+/- 5 players (number of servers under bungee) are beeing kicked with this error

Im not 100% sure that it's caused by CCR, but kicks seems to be synced with messages, so I decided to paste it here. Also it started occuring, when I changed CCP to CCR, so thats why i think its it. There isnt any other stacktrace, only this error. I do not really have any other plugin that uses messaging channel (and it seems to be that) Maybe somthing with tabbing nicks?

Also (what is probably obvious) one player is beeing kicked from every server (who is probably packet carrier)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6446290/debug.zip)

**Comment by socksprox** [comment]
Same problem here :(

**Comment by Kryniowesegryderiusz** [comment]
I checked if its for 100% CCR and im sure, here are bytes of incoming messages:
08.05 21:51:51 [Server] INFO plugin:chcred|00000000-0000-0000-0000-000000000000||PLAYERS_SYNC_NAMES|28262
08.05 21:51:52 [Server] INFO plugin:chcred|00000000-0000-0000-0000-000000000000||PLAYERS_SYNC_NAMES|28464
08.05 21:51:53 [Server] INFO plugin:chcred|e9c63168-8118-3d7b-b391-fcb8420c9dc1|S1|SIMPLECOMPONENT_MESSAGE|3358
08.05 21:51:53 [Server] INFO plugin:chcred|e9c63168-8118-3d7b-b391-fcb8420c9dc1|S1|SOUND|115
08.05 21:51:53 [Server] INFO plugin:chcred|e9c63168-8118-3d7b-b391-fcb8420c9dc1|S1|REPLY_UPDATE|142
08.05 21:51:53 [Server] INFO plugin:chcred|e9c63168-8118-3d7b-b391-fcb8420c9dc1|S1|SPY|811
08.05 21:51:53 [Server] INFO plugin:chcred|00000000-0000-0000-0000-000000000000||PLAYERS_SYNC_NAMES|28464
08.05 21:51:54 [Server] INFO plugin:chcred|00000000-0000-0000-0000-000000000000||PLAYERS_SYNC_NAMES|28464
08.05 21:51:55 [Server] INFO plugin:chcred|00000000-0000-0000-0000-000000000000||PLAYERS_SYNC_NAMES|28464
08.05 21:51:56 [Server] INFO plugin:chcred|ed9dca92-d4e6-3638-bda7-a067f0dee8a1|S3|SIMPLECOMPONENT_MESSAGE|3350

If server has more than ~160 players SerializedMap with players data is too long for one bungee message chanel packet :/

**Comment by Kryniowesegryderiusz** [comment]
There is a problem:
08.05 21:39:07 [Server] INFO plugin:chcred|c5acff68-ad85-3a07-a015-6d50f7406f86|S2|3319
08.05 21:39:07 [Server] INFO plugin:chcred|c5acff68-ad85-3a07-a015-6d50f7406f86|S2|115
08.05 21:39:07 [Server] INFO plugin:chcred|c5acff68-ad85-3a07-a015-6d50f7406f86|S2|141
08.05 21:39:07 [Server] INFO plugin:chcred|c5acff68-ad85-3a07-a015-6d50f7406f86|S2|771
08.05 21:39:07 [Server] INFO plugin:chcred|00000000-0000-0000-0000-000000000000||28535
08.05 21:39:08 [Server] INFO plugin:chcred|c5acff68-ad85-3a07-a015-6d50f7406f86|S2|3338
08.05 21:39:08 [Server] INFO plugin:chcred|c5acff68-ad85-3a07-a015-6d50f7406f86|S2|115
08.05 21:39:08 [Server] INFO plugin:chcred|c5acff68-ad85-3a07-a015-6d50f7406f86|S2|141
08.05 21:39:08 [Server] INFO plugin:chcred|c5acff68-ad85-3a07-a015-6d50f7406f86|S2|813
08.05 21:39:08 [Server] INFO plugin:chcred|00000000-0000-0000-0000-000000000000||28535
08.05 21:39:09 [Server] INFO plugin:chcred|00000000-0000-0000-0000-000000000000||28535
08.05 21:39:10 [Server] INFO plugin:chcred|00000000-0000-0000-0000-000000000000||28732
08.05 21:39:11 [Server] INFO plugin:chcred|00000000-0000-0000-0000-000000000000||28732
08.05 21:39:12 [Server] INFO plugin:chcred|00000000-0000-0000-0000-000000000000||28732
08.05 21:39:13 [Server] INFO plugin:chcred|00000000-0000-0000-0000-000000000000||28732
08.05 21:39:14 [Server] INFO plugin:chcred|00000000-0000-0000-0000-000000000000||28732

Also subchanel is null, so there problably is some issue

**Comment by kangarko** [comment]
Thanks, investigating. Can confirm we do send that packet and 160 players may cause it to overflow since all of their names and data is put in an array. I can try splitting it into multiple parts.

**Comment by kangarko** [comment]
Reduced the payload size by 50% or more, should allow additional ~100 players, closing, but let me know below if you will experience any issues. If that happens, set your Debug key to [bungee-sync] and print console log from Spigot.

**Comment by socksprox** [comment]
Bug is not fixed yet ;(

[/5.146.197.133:15895]: <-> InitialHandler has pinged
[Taminator05]: disconnected with: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Payload may not be larger than 32767 bytes

Im running the newest version of Bungee/ChatControl-Red-3.4.1

**Comment by kangarko** [comment]
Did you restart the entire network including BungeeControl Red? Can you please provide the bytes from that message as @Kryniowesegryderiusz did? Chances are there's another packet now instead of the player sync one.

**Comment by socksprox** [comment]
Entire network restarted, i will send the debug

**Comment by socksprox** [comment]
Here my Logs, i forgot to debug with CCR, i hope this helps (Ips of users are changed)

[13:30:06] [Netty Worker IO Thread #10/INFO]: 
[13:30:06] [Netty Worker IO Thread #10/INFO]: TheGodlyLucas is not using a VPN or Proxy (Germany).
[13:30:06] [Netty Worker IO Thread #10/INFO]: [TheGodlyLucas|/87.122.223.223:53191] <-> ServerConnector [lobby1] has connected
[13:30:06] [Netty Worker IO Thread #15/INFO]: [/46.89.155.136:50840] <-> InitialHandler has pinged
[13:30:08] [Netty Worker IO Thread #29/INFO]: [Anjofija] disconnected with: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Payload may not be larger than 32767 bytes
[13:30:08] [Netty Worker IO Thread #29/INFO]: [/93.195.53.174:59625|Anjofija] -> UpstreamBridge has disconnected
[13:30:08] [Netty Worker IO Thread #29/INFO]: [/93.195.53.174:59625|Anjofija] <-> DownstreamBridge <-> [lobby1] has disconnected
[13:30:08] [Netty Worker IO Thread #19/INFO]: [Saint_Pi] disconnected with: [Proxy] Lost connection to server.
[13:30:08] [Netty Worker IO Thread #19/INFO]: [/83.219.62.4:51077|Saint_Pi] <-> DownstreamBridge <-> [oneblock] has disconnected
[13:30:08] [Netty Worker IO Thread #10/INFO]: [WarDuck771] disconnected with: [Proxy] Lost connection to server.
[13:30:08] [Netty Worker IO Thread #10/INFO]: [/188.101.159.100:59310|WarDuck771] <-> DownstreamBridge <-> [survival] has disconnected

**Comment by socksprox** [comment]
[https://mega.nz/file/kCwmwLrC#MnLOVuJGToZZeWH94GoJVVeF5j1C021LuMuSbcttuZU](url)

**Comment by socksprox** [comment]
Here is the debug! @kangarko

**Comment by TaminoPalm** [comment]
?

**Comment by socksprox** [comment]
How can I provide those bytes? I hope there are already in my debug file

**Comment by socksprox** [comment]
I paid for this Plugin, and want this bug to be fixed, my slots are always full, cause i cant go higher tahn 160, and really love chc red

**Comment by socksprox** [comment]
@kangarko Is this bug in ChatControl Pro? If not, i switch to chc pro :(

**Comment by socksprox** [comment]
I enabled bungee sync, but the server started lagging af, and i wasnt able to debug the problem-

**Comment by socksprox** [comment]
Here is the full log with bungee sync enabled on a server with almost no players, but a full bungee

https://pastebin.com/Hf1iGwaJ

**Comment by socksprox** [comment]
@ElBananaa  Are you able to fix this? Kangarko seems to be offline for a while now....

**Comment by ElBananaa** [comment]
> @ElBananaa Are you able to fix this? Kangarko seems to be offline for a while now....

Hey!
Unfortunately, no, I can't.
Please be patient, it's only been two days since the last time Kangarko answered you ^^. We understand that you paid for the plugin and I'm sure Kangarko will do his best to fix your issue, however we can't provide support 24/7. It might take a few days until you get a patch for this issue, so in the meantime, i'd suggest you disable bungee linking system, at least for now.

**Comment by socksprox** [comment]
Will disabling bungeecord in chatcontrol fix it?

**Comment by socksprox** [comment]
Sorry if i spammed a bit😅 But i was really cunfused...

**Comment by ElBananaa** [comment]
> Sorry if i spammed a bit😅 But i was really cunfused...

Haha no worries, it's an issue on our end, not yours, so apologies for the inconvenient. Disabling bungeecord should act as a temp fix I guess yes, since this packet seems to only be sent between servers.

**Comment by kangarko** [comment]
@Kryniowesegryderiusz how were you able to provide the bytes please?

@TaminoPalm I don't see any byte output there so I have no idea which packet this is, we have dozens of different packets... 

You can try setting Debug key to just [bungee] because this will not print so many laggy messages but still can give me a hint where this is coming from. Let this run until someone gets kicked then report the last messages or so. Thank you.

**Comment by socksprox** [comment]
I´ve done this extactly, runing it, until someone got kicked

**Comment by socksprox** [comment]
i'd suggest you disable bungee linking system, at least for now. @ElBananaa 

  BungeeCord:
 
    # Hook to BungeeCord? **Requires BungeeControl**: https://spigotmc.org/resources/13079
    # [IMPORTANT] Change your server-name key in server.properties first!
    Enabled: true
      
    # The optional prefix before all messages so that you know where they are coming from.
    Prefix: '&8[&dBungee/{bungee_server_name}] '


I think you mean this with "Bungeecord linking system right? I set it to false now"

**Comment by ElBananaa** [comment]
> i'd suggest you disable bungee linking system, at least for now. @ElBananaa
> 
> BungeeCord:
> 
> ```
> # Hook to BungeeCord? **Requires BungeeControl**: https://spigotmc.org/resources/13079
> # [IMPORTANT] Change your server-name key in server.properties first!
> Enabled: true
>   
> # The optional prefix before all messages so that you know where they are coming from.
> Prefix: '&8[&dBungee/{bungee_server_name}] '
> ```
> 
> I think you mean this with "Bungeecord linking system right? I set it to false now"

Hi,
Yes, that's what I meant. Disabling this will disable the packet sending between servers.

However, as Kangarko said, he doesn't know which packet is causing the issue, so while disabling this may be a temp fix, if you don't try what he asked, he won't be able to fix your issue.

So for now, I'd suggest you leave this feature enabled, and try this : 
>You can try setting Debug key to just [bungee] because this will not print so many laggy messages but still can give me a hint >where this is coming from. Let this run until someone gets kicked then report the last messages or so. Thank you.

EDIT: Reopening the issue so Kangarko doesn't forget to take a look at it in a few days ^^

**Comment by Kryniowesegryderiusz** [comment]
> @Kryniowesegryderiusz how were you able to provide the bytes please?

Tbh I checked the bungee channel name in plugin and made my own test plugin to listen all of incoming messages to make sure that it was CCR

**Comment by socksprox** [comment]
I fixed it by turning off bungeecord in settings.yml but thats not a nice fix... Please fix it

**Comment by kangarko** [comment]
@Kryniowesegryderiusz can you share that plugin with Tamino to save time? If not I'll make one. Seems like there's multiple packets being affected. Krynio are you still affected btw?

**Comment by Kryniowesegryderiusz** [comment]
> @Kryniowesegryderiusz can you share that plugin with Tamino to save time? If not I'll make one. Seems like there's multiple packets being affected. Krynio are you still affected btw?

Tbh it was temporary code in one of my debug plugins and I deleted it after investigation

**Comment by kangarko** [comment]
Just reviewed our code, as I told you @TaminoPalm set your Debug key to [bungee] in settings.yml of BungeeControl Red, it's gonna say different debug messages than what you have above, those are the one I need to read to see what packet it is causing that

**Comment by Kryniowesegryderiusz** [comment]
Oh, and I dont have 160 players anymore to have this problem again :P

**Comment by kangarko** [comment]
Just turn it on before your expected peak player count and let me know asap.

**Comment by kangarko** [comment]
Closing, let me know below if that happens again

**Comment by socksprox** [comment]
> Closing, let me know below if that happens again

The bug is still not fixed after a month, and debugging is no option for me, cause i would just lose to many players if it gets cut to 165, i think i need to make the decision, and jump back to CHC Pro ;(

If you are able to fix this you can ping me
PS: Why are you closing a ticket where the bug is not fixed?

**Comment by ElBananaa** [comment]
> > Closing, let me know below if that happens again
> 
> The bug is still not fixed after a month, and debugging is no option for me, cause i would just lose to many players if it gets cut to 165, i think i need to make the decision, and jump back to CHC Pro ;(
> 
> If you are able to fix this you can ping me
> PS: Why are you closing a ticket where the bug is not fixed?

Hey!
This is a way to keep tracks with active issues. If we don't get answers from you after a certain amount of time, we close the issue. Anyways, there's not much Kangarko can do about it without any debug informations. There's no way to reproduce the issue on our end since, you will understand, having more than 160 accounts is kinda expensive and hard to run on a single computer.
I'm reopening the issue, but I can't guarantee you anything without any informations.

**Comment by kangarko** [comment]
I understand, yes we do reply to all tickets even closed ones and monitor those needing extra help.

Go on ChatControl Pro for now, I am taking an annual leave (vacation) so will come back this in July.

**Comment by waiching514** [comment]
This bug will fix in future?

**Comment by kangarko** [comment]
It is taking longer than expected to solve this since I have to rewrite our packet synchronization, I am unfortunately not able to give you an ETA right now.

**Comment by kangarko** [comment]
@waiching514 getting this resolved asap, I fixed this by splitting the packet into 5 smaller packets so it should bare in theory at least 2-3X more players, I will notify everyone on this thread once a beta build is ready for testing

**Comment by kangarko** [comment]
Scheduled for release today, if there is anything please do comment below here and I will get a notification!
