### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by Parthurax** [kangarko/ChatControl#965]
Hello,
i think about buying CCRED.
But is Velocity already Supported ?

**Comment by Kryniowesegryderiusz** [comment]
It's not but it's going to be basing on information from their discord

**Comment by ElBananaa** [comment]
Hey!
Sorry for the delay.
Since the developer doesn't have a lot of time to learn the full velocity API, he's currently looking for a developer that could add support for velocity.

**Comment by UserDerezzed** [comment]
@kangarko, my community, SMPEarth, is in need of Velocity support for BungeeControl. Our developers would like to look into porting BungeeControl to Velocity if we would be able to get access to the source. Is this something you'd be interested in?

**Comment by ElBananaa** [comment]
> @kangarko, my community, SMPEarth, is in need of Velocity support for BungeeControl. Our developers would like to look into porting BungeeControl to Velocity if we would be able to get access to the source. Is this something you'd be interested in?

Hey!
Kangarko is currently on vacations until the 2nd of july. But afaik, he's still looking for a developer to help him porting BungeeControl to Velocity. As said on the discord, if you're interested, feel free to send him an email : matej@mineacademy.org with your portfolio and/or some past/actual work ^^

**Comment by kangarko** [comment]
@relavis contact me through matej@mineacademy.org so we can add your developers to our BungeeControl and ChatControl Red source code repositories so they can write it off of those. BungeeControl is a tiny plugin so porting it shouldn't take that long if they are experiences in both Paper/Velocity

**Comment by UserDerezzed** [comment]
Sent you an email @kangarko, looking forward to helping out!

**Comment by NoobcoreNetwork** [comment]
Looking forward to see if this is done. Wanting to move to velocity myself

**Comment by kangarko** [comment]
@relavis haven't heard back from you guys since, can you provide an update?

**Comment by UserDerezzed** [comment]
Still working on this. The process is more complicated than originally thought due to a port of BungeeFoundation being required.

**Comment by UserDerezzed** [comment]
Looks like we were able to circumvent having to port BungeeFoundation - we've got a (somewhat) working version on our network! PMs, channels, and announcements are all working perfectly. We're just having some issues with configuration files not generating on first run.

**Comment by kangarko** [comment]
That is awesome relavis! Let me know if there is anything I can help you with and feel free to comment below with a working test-version I can send to people using Velocity to test out :)
