### ISSUE TITLE
authme spy bug

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#966]
Minecraft Version: paper 1.16.5 651
MySQL: true
BungeeCord: true

you can see the all spy stuff with auto spy enable when the player is not logged with atuhme

**Comment by ElBananaa** [comment]
> Minecraft Version: paper 1.16.5 651
> MySQL: true
> BungeeCord: true
> 
> you can see the all spy stuff with auto spy enable when the player is not logged with atuhme

Hey!
Could you please explain the bug a bit further?

**Comment by FakEEE14** [comment]
i'm as owner of server have the * perm and have auto spy enabled
and i can access to all of the spys (command,messages, ...) wihout logging in by authme 
what will help you ?

**Comment by ElBananaa** [comment]
> i'm as owner of server have the * perm and have auto spy enabled
> and i can access to all of the spys (command,messages, ...) wihout logging in by authme
> what will help you ?

Alright, I understand now, thanks.
It looks like that's something @kangarko forgot to add. Definitely a major security issue. He'll probably have a look at it tomorrow or on tuesday ^^

**Comment by FakEEE14** [comment]
great i set the autospy perm to false for now

**Comment by kangarko** [comment]
Thanks, patched.
