### ISSUE TITLE
1.16.5: Odd nickname behaviour on bungeecord/mysql

### ISSUE THREAD

**Issue by NoobcoreNetwork** [kangarko/ChatControl#969]
Hi there, I seem to have very odd nickname behaviour with nicknames on my server/network and it happens ALOT more with my account (and im not sure why that would be) I did use to run chatcontrol pro and switched to red about 4 weeks ago. My admins nicknames have only removed themself once but mine does it every couple of days and sometimes I just cant apply a new nickname. 
![1](https://user-images.githubusercontent.com/62724418/117589970-16d69500-b125-11eb-8f96-bcbd09a01ba1.png)
![2](https://user-images.githubusercontent.com/62724418/117589973-1b02b280-b125-11eb-836b-55d043126b5c.png)

The two screenshots of the /chc tag list are taken from 2 different server on my bungeecord network, For some reason, My nicknames twice on one server and not existent on another. All the servers are on the same mysql and bungeecord is set up perfectly. Every other function of chc works for us.

I can only remove 1 of the nickname entries with the tag remove command. running it twice says you dont have a nickname even though one of them is still left inside the list, At this point, me and my admin decided to poke into the mysql and found this 
![3](https://user-images.githubusercontent.com/62724418/117590024-8482c100-b125-11eb-9577-1b1574f26580.png)

See the way I have 2 inputs? I'm unsure how this can happened. But removing one of them in the mysql allowed me to get things back to normal until it broke itself again, this happens to my account ALOT and very infrequent on other nicknamed accounts.

Thankyou :)

-->

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Hi there, I seem to have very odd nickname behaviour with nicknames on my server/network and it happens ALOT more with my account (and im not sure why that would be) I did use to run chatcontrol pro and switched to red about 4 weeks ago. My admins nicknames have only removed themself once but mine does it every couple of days and sometimes I just cant apply a new nickname.
> ![1](https://user-images.githubusercontent.com/62724418/117589970-16d69500-b125-11eb-8f96-bcbd09a01ba1.png)
> ![2](https://user-images.githubusercontent.com/62724418/117589973-1b02b280-b125-11eb-836b-55d043126b5c.png)
> 
> The two screenshots of the /chc tag list are taken from 2 different server on my bungeecord network, For some reason, My nicknames twice on one server and not existent on another. All the servers are on the same mysql and bungeecord is set up perfectly. Every other function of chc works for us.
> 
> I can only remove 1 of the nickname entries with the tag remove command. running it twice says you dont have a nickname even though one of them is still left inside the list, At this point, me and my admin decided to poke into the mysql and found this
> ![3](https://user-images.githubusercontent.com/62724418/117590024-8482c100-b125-11eb-9577-1b1574f26580.png)
> 
> See the way I have 2 inputs? I'm unsure how this can happened. But removing one of them in the mysql allowed me to get things back to normal until it broke itself again, this happens to my account ALOT and very infrequent on other nicknamed accounts.
> 
> Thankyou :)
> 
> -->
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
From what I can see on your last screenshot, it looks like you have two diferent uuids. Is your server running in offline mode? Did you recently change your mojang account name?
Would you mind providing us your `/chc debug` file?

**Comment by NoobcoreNetwork** [comment]
> > Hi there, I seem to have very odd nickname behaviour with nicknames on my server/network and it happens ALOT more with my account (and im not sure why that would be) I did use to run chatcontrol pro and switched to red about 4 weeks ago. My admins nicknames have only removed themself once but mine does it every couple of days and sometimes I just cant apply a new nickname.
> > ![1](https://user-images.githubusercontent.com/62724418/117589970-16d69500-b125-11eb-8f96-bcbd09a01ba1.png)
> > ![2](https://user-images.githubusercontent.com/62724418/117589973-1b02b280-b125-11eb-836b-55d043126b5c.png)
> > The two screenshots of the /chc tag list are taken from 2 different server on my bungeecord network, For some reason, My nicknames twice on one server and not existent on another. All the servers are on the same mysql and bungeecord is set up perfectly. Every other function of chc works for us.
> > I can only remove 1 of the nickname entries with the tag remove command. running it twice says you dont have a nickname even though one of them is still left inside the list, At this point, me and my admin decided to poke into the mysql and found this
> > ![3](https://user-images.githubusercontent.com/62724418/117590024-8482c100-b125-11eb-9577-1b1574f26580.png)
> > See the way I have 2 inputs? I'm unsure how this can happened. But removing one of them in the mysql allowed me to get things back to normal until it broke itself again, this happens to my account ALOT and very infrequent on other nicknamed accounts.
> > Thankyou :)
> > -->
> > Minecraft Version: 1.16.5
> > MySQL: true
> > BungeeCord: true
> 
> Hey!
> From what I can see on your last screenshot, it looks like you have two diferent uuids. Is your server running in offline mode? Did you recently change your mojang account name?
> Would you mind providing us your `/chc debug` file?

Hey hey. All my backend servers are offline mode yes as I'm running through bungeecord But it requires official none cracked accounts. I can provide the file tomorrow after work :)

Bit odd why my uuid would change

Thanks!

Edit: also never changed my MC name

**Comment by NoobcoreNetwork** [comment]
Debug file as requested: https://ufile.io/7vz4muqw

**Comment by kangarko** [comment]
Set UUID_Lookup to false in mysql.yml, that should patch this for offline-mode servers.
