### ISSUE TITLE
Add LiteBans Mute Support

### ISSUE THREAD

**Issue by UserDerezzed** [kangarko/ChatControl#97]
LiteBans has an integrated muting system that allows mutes to be tracked on a web page. It would be extremely beneficial to server owners to be able to track CHC mutes as well, through Litebans. Currently, CHC simply overrides LiteBan's mute command - however, CHC should:

1. Detect that Litebans is installed
2. When an admin makes a mute through ChatControl, use the API to call a LiteBans mute as well

**Comment by ElBananaa** [comment]
It would also be pretty cool to add a parameter to remove the messages of the muted player.
You would use:
- `/mute player <player> <duration> -r` with chatcontrol mute system
Then devs could hook into the plugin to use this feature in their plugins too.
(It seems a bit advanced tho, I think this would be something cool to add this after the plugin official release)

**Comment by kangarko** [comment]
Thanks! We will have a /chc purge command in the future to remove messages. I will add that API call though.

**Comment by kangarko** [comment]
Added.

**Comment by mav2020** [comment]
1.17.1
Bungee True
MySQL True
ChatControl-Red-10.8.0

Sorry for the necro, but how do I get this to work? Do I turn on mute in LiteBans? If so I do it on the bungee server, the backend server, or both? or is there a 'then LiteBans' type of thing?
Thanks

**Comment by kangarko** [comment]
We do it automatically right now. And I updated it right now to also work with BungeeCord (but you must have LiteBans installed on the sending server) in the next version.
