### ISSUE TITLE
Not able to enable auto-correct

### ISSUE THREAD

**Issue by MrBaconHawk** [kangarko/ChatControl#97]
Your plugin states it can auto-correct and fix punctuation.  I can't find an option for this anywhere no matter what.  Also, points are not working for swear words.  I can get it to block the swear word, but it doesn't give points like it should.

My main concern is that I can't enable auto-correct though, where is this option located?

**Comment by kangarko** [comment]
You can configure punctuation and inserting do at **Chat.Grammar **section in settings.yml.

Points are not implemented in the free version. If you are on premium, close this and write in the correct section
