### ISSUE TITLE
1.16.5: Huge server freeze RegionTool.getItem()

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [kangarko/ChatControl#970]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Sometimes huge freezes occur

Spark timings: https://spark.lucko.me/SMWPaefTEJ
Aikar Timings:  https://timings.aikar.co/?id=7dc442b6055d4aa3944e8687203825c4#timings
Screenshots in case pages no longer exist:  https://imgur.com/a/eUZ7c25

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Sometimes huge freezes occur
> 
> Spark timings: https://spark.lucko.me/SMWPaefTEJ
> Aikar Timings: https://timings.aikar.co/?id=7dc442b6055d4aa3944e8687203825c4#timings
> Screenshots in case pages no longer exist: https://imgur.com/a/eUZ7c25

Hey!
Could you please provide us the `general.txt` file generated in your chatcontrol-red folder when using `/chc debug`?
This could give us more informations about your environment.

**Comment by Kryniowesegryderiusz** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6454893/debug.zip)

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6454893/debug.zip)

Thanks.
It looks like a lot of your plugins (If not all your plugins) are outdated. Consider updating them all (Including dependencies and the server softwares such as ProtocolLib, paper and bungee, or whatever you are using).
Once this is done, if the issue persists, please upload updated versions of your timings.

**Comment by Kryniowesegryderiusz** [comment]
This problem occured to me once and it was today, so I dont think I'll be able to reproduce it that simply.

Also. im not that fluent in pure engines code, but I dont really see concatenation between PlayerInteractManager.handleBlockBreakAction() firing PlayerInteractEvent, which is listened by org.mineacademy.chatcontrol.lib.menu.tool.ToolsListener.onToolClick() method. All this stacktrace leads to org.mineacademy.chatcontrol.model.RegionTool.getItem(), so I do not really see connotation between this and other plugins.

I have one more question though. What is interact event used for in chat plugin and why is it launching rockets? Which part of CCR relies on it? I havent found any mentions about rockets or item tools in any wiki page.

**Comment by ElBananaa** [comment]
> This problem occured to me once and it was today, so I dont think I'll be able to reproduce it that simply.
> 
> Also. im not that fluent in pure engines code, but I dont really see concatenation between PlayerInteractManager.handleBlockBreakAction() firing PlayerInteractEvent, which is listened by org.mineacademy.chatcontrol.lib.menu.tool.ToolsListener.onToolClick() method. All this stacktrace leads to org.mineacademy.chatcontrol.model.RegionTool.getItem(), so I do not really see connotation between this and other plugins.
> 
> I have one more question though. What is interact event used for in chat plugin and why is it launching rockets? Which part of CCR relies on it? I havent found any mentions about rockets or item tools in any wiki page.

Poor performances from one plugin can lead to poor performances on other plugins, that's why I recommend updating all plugins each time.
Regarding the fireworks, I know they're used with the `/chc tour` command, and, I think, also when a player joins (with the default configs).
The tools thing, somehow relates (I guess) to the `/chc region` command. (Take a look at [this page](https://github.com/kangarko/ChatControl-Red/wiki/Commands#chc-region) for more informations)

Once again, you should really consider updating all your plugins, dependencies and server softwares. Even tho it can look useless, most of the time, performance issues are related to outdated plugins, dependencies and/or server softwares.

**Comment by Kryniowesegryderiusz** [comment]
I'll do that, but as you can see on spark timings its more like CCR affects performance on other plugins, than in the opposite direction. I'm just affraid that this ticket will land in trash and not even be looked on because of that and I'm not sure when the problem will happen again and its really harmfull.

**Comment by kangarko** [comment]
Thanks will patch this.

**Comment by kangarko** [comment]
@ElBananaa that is caused by some technical code always generating a new item every time ANYTHING is clicked, I simply made the item only generate on reload and then be reused, I appreciate your help though! Hoping the timings will improve significatnly.
