### ISSUE TITLE
1.16.5: Can I edit the {chat_line} variable

### ISSUE THREAD

**Issue by mav2020** [kangarko/ChatControl#971]
I know I can make my own variable and replace {chat_line} with that, but I was wondering if it was possible to edit that one directly. Same goes for chat_line_smooth I guess. Really I just want to reduce the number of dashes it makes. Like I said, it isn't a major thing but this is the only place I know to ask. Thanks for a great plugin.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

**Comment by TheIntolerant** [comment]
It seems you cannot edit it as I cannot find anything in the localization file. However, you should keep this ticket open, in case Kangarko decides to accept this suggestion and make this placeholder editable.

**Comment by mav2020** [comment]
Thank you. I looked in the same area. I appreciate the quick response on such a low priority item.

**Comment by ElBananaa** [comment]
Hey!
Thanks gone-incognito for answering.
I can confirm, you cannot edit this placeholder for now.
We're trying to answer people as quickly as possible, no matter the priority of the issue ^^

**Comment by kangarko** [comment]
No sorry that's not editable at the moment :)
