### ISSUE TITLE
1.16.5: Anti-Spam Rule not working as intended

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#972]
**Minecraft Version:** 1.16.5
**MySQL:** false
**BungeeCord:** false

---------------------------

**Info about server set-up**
```
!-----------------------------------------------------!
 Debug log generated 11.05.2021 04:26:36
!-----------------------------------------------------!
Plugin: ChatControlRed v10.3.8
Server Version: Paper v1_16_R3
Java: 11.0.9.1 (Oracle Corporation/Ubuntu)
OS: Linux 4.4.0-178-generic
Players Online: 1
Plugins: LuckPerms v5.3.37, Vault v1.7.3-b131, ChatControlRed v10.3.8
```

---------------------------

**Tested on fresh install!**
The only change I made was adding this to the ``chat.rs`` file.
```
# Restrict one characters to max. of five repeats
# example: aaaaaaaaaaaaaaaaaaaa to aaaaa etc.
match (.)(?=\1{5})
then replace


# Restrict two characters to max. of three repeats
# example: hahahahahahaha to hahaha
match (..)(?=\1{3})
then replace


# Restrict three characters to max. of two repeats
# example: lollollollollol to lollol
match (...)(?=\1{2})
then replace
```

---------------------------

**What is the issue?**
Basically, the rules listed above seem to only reduce messages of a certain length, for example, if I try to send
``aaaaaaaaaaaaaaaaaaaaaa`` in chat, that message would be reduced. However, if I sent the same message but make it much longer, for example ``aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`` the rule seems to behave differently, in that it would only partially deduce the size of the message.

**Comment by TheIntolerant** [comment]
I also tested the rule on [RegEx101](https://regex101.com/) to see if it was matching the message correctly and as shown below, the rule seems fine, as the highlighted section would be removed because of the ``then replace`` operator

![51516548451484844989292](https://user-images.githubusercontent.com/48093184/117785773-3df9a780-b288-11eb-9066-44c74bbe2191.JPG)

Any help to fix this issue would be greatly appreciated, thanks!

**Comment by ElBananaa** [comment]
Hey!
If I'm not wrong, this has been reported many times, but there's nothing kangarko can do about it. If it doesn't work with a high amount of characters, it's because this would cause lags.

Once again I'm not sure about that, so lets wait for him ^^

**Comment by kangarko** [comment]
Interesting, I must have missed this being reported since that's the first time! Will do a check in a few days.

**Comment by kangarko** [comment]
Yeah sorry, unfortunately we pause the loop after the char limit you've discovered so it won't hang up the server. For 90% user cases this won't be noticed, right now I simply don't have any better alternative.
 
Banana I almost forgot that haha, thanks!

**Comment by TheIntolerant** [comment]
That's fair enough :)
