### ISSUE TITLE
1.7.2 to 1.16.5: How message deleting system works?

### ISSUE THREAD

**Issue by HyperSetups** [kangarko/ChatControl#973]
Minecraft Version: 1.7.2 to 1.16.5

Hello.

How message deleting system works? I'm not buyer of the plugin. So you can think this is a pre-buy question.

Does system sends last 100 messages again to remove last message or did you find a way to really delete messages?
Also which versions does the system support

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.7.2 to 1.16.5
> 
> Hello.
> 
> How message deleting system works? I'm not buyer of the plugin. So you can think this is a pre-buy question.
> 
> Does system sends last 100 messages again to remove last message or did you find a way to really delete messages?
> Also which versions does the system support

Hey! I can't tell you how it works exactly, but I think the message truly gets removed, you would have to wait for Kangarko to be sure about it. The system should work from 1.10 to 1.16, for previous versions, I'm not sure, I'll try as soon as I get some free time, and I'll let you know about it. ^^

**Comment by kangarko** [comment]
Hey!

We use ProtocolLib to assign each message a unique ID and save all chat communication for each player. So yes, we do send 100 last messages WITHOUT the deleted message to create an illusion that it was deleted, when in fact we only pulled the last 101 messages minus the one deleted from chat history.

Should work to at least 1.8.8, haven't tested 1.7.10 but there's nothing in the way of it not to.
