### ISSUE TITLE
1.16.5: Gradient/Multiple Color items causing Interactive Elements to be removed

### ISSUE THREAD

**Issue by NiNjAiKoToBa** [kangarko/ChatControl#978]
Minecraft Version: 1.16.5
MySQL: true/
BungeeCord: true

I'm having an issue with the new update:
Improve | Avoid kicking players when format and chat message is too large, instead, send it as plain.

Ever since this patch, items posted to chat that have names with multiple colors or gradients are causing the new mechanism to trigger, removing the interactive elements of the item (The hover text, which is arguably important for us being a roleplay server), where this previous worked just fine in almost all cases, even if the item is the only thing posted on that chat line

![javaw_2021-05-12_16-43-17]

**Examples:**
(https://user-images.githubusercontent.com/5144099/118004558-78734b00-b341-11eb-9e11-a380a0fdcd8b.png)
![javaw_2021-05-12_16-45-07](https://user-images.githubusercontent.com/5144099/118004561-79a47800-b341-11eb-80ed-bd4a790cb31a.png)
![firefox_2021-05-12_16-45-18](https://user-images.githubusercontent.com/5144099/118004569-7b6e3b80-b341-11eb-8509-900d0228f0b9.png)

Is it possible for this feature to be toggled off? If not we may have to revert to an earlier version for the time being.

Thanks!

**Comment by kangarko** [comment]
It's a security feature, it prevents players from getting kicked out. Not all systems are affected but we can't track when a player is getting kicked out or not because of this overflow. This security feature will remain because it prevents players from not being able to relog back if they again see that chat message, being stuck in a loop.

**Comment by NiNjAiKoToBa** [comment]
Hello,

If this is a feature that's going to remain then i might be forced to move away from the plugin as unfortunatley this is preventing my players from sharing their items in chat. I'm not asking for it to be removed, moreso i need a way to bypass it if at all possible.

Kind Regards

**Comment by NiNjAiKoToBa** [comment]
Just an FYI, we have now rolled back to 10.3.6 and can no longer update the plugin without a fix for this issue.

**Comment by kangarko** [comment]
I'll see closed issues also :) Going to add a toggle option for this one.

**Comment by NiNjAiKoToBa** [comment]
Thankyou so much!

You are honestly the best <3
