### ISSUE TITLE
Suggestion: MMOCore Party Chat

### ISSUE THREAD

**Issue by Tanerx** [kangarko/ChatControl#979]
MMOCore party chat is so bad. 

Create auto channel for party make all party members join auto. Ignore all other channel except global.

**Comment by ElBananaa** [comment]
> MMOCore party chat is so bad.
> 
> Create auto channel for party make all party members join auto. Ignore all other channel except global.

Hey!
Why did you open this ticket? It doesn't respect any format, and doesn't mean anything.

EDIT : Sorry if I sounded rude, this wasn't my intention at all, I just didn't understood your issue at all ^^

**Comment by Tanerx** [comment]
Hello.
What format are you talking about ? MMOCore well know plugin doesn't need to put a url. 

This is just a "Improvement Suggest a new idea or a feature." 
https://i.imgur.com/50LSeqU.png

**Comment by kangarko** [comment]
Hey hey!

I am sorry but I don't understand your suggestion — what do you mean by "ignore all other channel except global" ?

**Comment by Tanerx** [comment]
> Hey hey!
> 
> I am sorry but I don't understand your suggestion — what do you mean by "ignore all other channel except global" ?

Hello!
I'll explain more. If you add support to MMOCore Party Chat, Party Members will auto join the party channel and everyting they write will go to party channel. Same time they can't ignore seeing default server channels. (like range and global).  Party channel auto delete if no user left in the channel.
I hope I explained well.

**Comment by ElBananaa** [comment]
> > Hey hey!
> > I am sorry but I don't understand your suggestion — what do you mean by "ignore all other channel except global" ?
> 
> Hello!
> I'll explain more. If you add support to MMOCore Party Chat, Party Members will auto join the party channel and everyting they write will go to party channel. Same time they can't ignore seeing default server channels. (like range and global). Party channel auto delete if no user left in the channel.
> I hope I explained well.

Hey!
You can already let users automatically join a specific channel with a specific mode using permissions. Take a look at this page, it could probably help you ^^ https://github.com/kangarko/ChatControl-Red/wiki/Channels#auto-join

You can also force them using the same permissions than above, to automatically join the default channel in read mode.
So let's say you want you users to automatically join the party chat named `party` in write mode, and the channel name `general` in read mode, you'll have to give them these permissions : 
`chatcontrol.channel.autojoin.party.write`, `chatcontrol.channel.autojoin.general.read`, `chatcontrol.channel.join.general.read` and `chatcontrol.channel.join.party.write`. Also keep in mind that if the users leave these channels manually, they won't rejoin them automatically, so you might want to deny the permission `chatcontrol.channel.leave.general` & `chatcontrol.channel.leave.party`.
Regarde the auto-deletion thing, I don't know if this is possible. I guess Kangarko could add a placeholder to show how many users are in a channel, and you could use the rule system to combine this placeholder, so, if there's only 1 player in the channel, it'll automatically switch you to the read mode for this channel, and to the write mode in the default channel.

**Comment by Tanerx** [comment]
> > > Hey hey!
> > > I am sorry but I don't understand your suggestion — what do you mean by "ignore all other channel except global" ?
> > 
> > 
> > Hello!
> > I'll explain more. If you add support to MMOCore Party Chat, Party Members will auto join the party channel and everyting they write will go to party channel. Same time they can't ignore seeing default server channels. (like range and global). Party channel auto delete if no user left in the channel.
> > I hope I explained well.
> 
> Hey!
> You can already let users automatically join a specific channel with a specific mode using permissions. Take a look at this page, it could probably help you ^^ https://github.com/kangarko/ChatControl-Red/wiki/Channels#auto-join
> 
> You can also force them using the same permissions than above, to automatically join the default channel in read mode.
> So let's say you want you users to automatically join the party chat named `party` in write mode, and the channel name `general` in read mode, you'll have to give them these permissions :
> `chatcontrol.channel.autojoin.party.write`, `chatcontrol.channel.autojoin.general.read`, `chatcontrol.channel.join.general.read` and `chatcontrol.channel.join.party.write`. Also keep in mind that if the users leave these channels manually, they won't rejoin them automatically, so you might want to deny the permission `chatcontrol.channel.leave.general` & `chatcontrol.channel.leave.party`.
> Regarde the auto-deletion thing, I don't know if this is possible. I guess Kangarko could add a placeholder to show how many users are in a channel, and you could use the rule system to combine this placeholder, so, if there's only 1 player in the channel, it'll automatically switch you to the read mode for this channel, and to the write mode in the default channel.

Hello.
You get me wrong. I did test the plugin i know how to permission work and force auto channel join read or write. I don't want to anyone join channel name "party"
I want to every time party created with mmocore ChatControl Red will create special channel for this party. For every party channel name will be different. (PartyChannel01, PartyChannel02, PartyChannel03....) More players join the party with mmocore, CCRed will make new player join same chat channel read and write perrmision. All Party channels will be temporary. If no user left or server reset they will be deleted.

**Comment by Tanerx** [comment]
This system can be improved to temporary channel support. 
Any group of players can create ther own temp channel.
Any other plugin can create temp channel and control using api.

**Comment by kangarko** [comment]
I understand, unfortunately we won't create channels on the fly, that is totally different from how our system has been designed right now.
