### ISSUE TITLE
Tour confirmation not working ?

### ISSUE THREAD

**Issue by Parthurax** [kangarko/ChatControl#980]
OK this plugin and the dev with his spam mails start to get annoying.

![image](https://user-images.githubusercontent.com/55805110/118024940-8df76d80-b35f-11eb-831e-04f8adde458c.png)

isnt that shitty confirm command /stop ?! 
just add a message - no support if you use that plugin on a server - and we are good.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

**Comment by ElBananaa** [comment]
> OK this plugin and the dev with his spam mails start to get annoying.
> 
> ![image](https://user-images.githubusercontent.com/55805110/118024940-8df76d80-b35f-11eb-831e-04f8adde458c.png)
> 
> isnt that shitty confirm command /stop ?!
> just add a message - no support if you use that plugin on a server - and we are good.
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: false

Hi!
I'm sorry, what are you talking about?
Regardin the spam mail thing, I have never received more than 1 or two emails in maybe 2 years with an account on Mineacademy...
Anyways, i'm glad you finally solved your "problem". If your need anything else, feel free to open a new issue.
Have a nice day.
