### ISSUE TITLE
1.16.5: Luckperms prefix wont show up

### ISSUE THREAD

**Issue by Parthurax** [kangarko/ChatControl#981]
For some reason red cant get my luckperms prefixes with the default chat format.
it dont display something.

im in the group owner
vault ist enabled
luckperms is working

only red having problems.
I cant find a line in the console  where red states that it hooked into vault...

Minecraft Version:1.16.5
MySQL: false
BungeeCord: false (Velocity)

**Comment by Parthurax** [comment]
Minecraft Version:1.16.5
MySQL: false
BungeeCord: false

**Comment by Parthurax** [comment]
Same with the {luckperms_prefix} placeholder

**Comment by ElBananaa** [comment]
> For some reason red cant get my luckperms prefixes with the default chat format.
> it dont display something.
> 
> im in the group owner
> vault ist enabled
> luckperms is working
> 
> only red having problems.
> I cant find a line in the console where red states that it hooked into vault...
> 
> Minecraft Version:1.16.5
> MySQL: false
> BungeeCord: false (Velocity)

Hi!
You need to enable the channel feature in order to use formats.
Also, as specified in your issue, you use Velocity. Keep in mind that, for now, the plugin doesn't support Velocity.
Finally, could you please provide us your `/chc debug` output file? I'll take a look at your configs to see if you're not missing anything.

**Comment by Parthurax** [comment]
> > For some reason red cant get my luckperms prefixes with the default chat format.
> > it dont display something.
> > im in the group owner
> > vault ist enabled
> > luckperms is working
> > only red having problems.
> > I cant find a line in the console where red states that it hooked into vault...
> > Minecraft Version:1.16.5
> > MySQL: false
> > BungeeCord: false (Velocity)
> 
> Hi!
> You need to enable the channel feature in order to use formats.
> Also, as specified in your issue, you use Velocity. Keep in mind that, for now, the plugin doesn't support Velocity.
> Finally, could you please provide us your `/chc debug` output file? I'll take a look at your configs to see if you're not missing anything.

Hi,
Since luckperms is local on the server the shouldnt make a difference, otherwise vault wouldnt get the information also.

I will provide the debug tommorow in the morning, thanks

**Comment by Parthurax** [comment]
https://ufile.io/7qwi1lwo

**Comment by ElBananaa** [comment]
> https://ufile.io/7qwi1lwo

Thanks.
In which file did you try to use the `{luckperms_prefix}` placeholder?

**Comment by Parthurax** [comment]
also in formats/chat
i just placed it before the username placeholder.
But im already tracking that bug i belive luckperms dont give out the prefix for some reason, its also not displayed on when i pull the group in luckperms, i belive this is a luckperms issue

**Comment by ElBananaa** [comment]
> also in formats/chat
> i just placed it before the username placeholder.
> But im already tracking that bug i belive luckperms dont give out the prefix for some reason, its also not displayed on when i pull the group in luckperms, i belive this is a luckperms issue

Update to luckperms v5.3.3 & chatcontrol v10.4.0, then try again, let me know if it fixes the issue.
Once this is done, don't forget to download luckperms PAPI expansion `/papi ecloud download LuckPerms` then `/papi reload`. And it should fix your issue

**Comment by Parthurax** [comment]
> > also in formats/chat
> > i just placed it before the username placeholder.
> > But im already tracking that bug i belive luckperms dont give out the prefix for some reason, its also not displayed on when i pull the group in luckperms, i belive this is a luckperms issue
> 
> Update to luckperms v5.3.3 & chatcontrol v10.4.0, then try again, let me know if it fixes the issue.
> Once this is done, don't forget to download luckperms PAPI expansion `/papi ecloud download LuckPerms` then `/papi reload`. And it should fix your issue

thank you man,
i found the issue it was on luckperms.
the syntax for the prefix string was wrong, thats why luckperms gave no informations about it.

But now im back at my Hex Gradients problem.

**Comment by ElBananaa** [comment]
> > > also in formats/chat
> > > i just placed it before the username placeholder.
> > > But im already tracking that bug i belive luckperms dont give out the prefix for some reason, its also not displayed on when i pull the group in luckperms, i belive this is a luckperms issue
> > 
> > 
> > Update to luckperms v5.3.3 & chatcontrol v10.4.0, then try again, let me know if it fixes the issue.
> > Once this is done, don't forget to download luckperms PAPI expansion `/papi ecloud download LuckPerms` then `/papi reload`. And it should fix your issue
> 
> thank you man,
> i found the issue it was on luckperms.
> the syntax for the prefix string was wrong, thats why luckperms gave no informations about it.
> 
> But now im back at my Hex Gradients problem.

As explained in your issue, there's nothing we can do about this issue since this isn't on our end, but on other plugins not supporting gradients.

**Comment by Parthurax** [comment]
> > > > also in formats/chat
> > > > i just placed it before the username placeholder.
> > > > But im already tracking that bug i belive luckperms dont give out the prefix for some reason, its also not displayed on when i pull the group in luckperms, i belive this is a luckperms issue
> > > 
> > > 
> > > Update to luckperms v5.3.3 & chatcontrol v10.4.0, then try again, let me know if it fixes the issue.
> > > Once this is done, don't forget to download luckperms PAPI expansion `/papi ecloud download LuckPerms` then `/papi reload`. And it should fix your issue
> > 
> > 
> > thank you man,
> > i found the issue it was on luckperms.
> > the syntax for the prefix string was wrong, thats why luckperms gave no informations about it.
> > But now im back at my Hex Gradients problem.
> 
> As explained in your issue, there's nothing we can do about this issue since this isn't on our end, but on other plugins not supporting gradients.

Other Plugins dont format the chat, the chat plugin read the code and translate it. 
In this example it would be luckperms, why should luckperms support gradients ^^ its the same when you as a player use color codes in the chat, the plugin has to read and translate this.

Since kangooro closed my issue without responding im afraid that a 30 Dollar plugin fails at the very basic.

**Comment by ElBananaa** [comment]
> > > > > also in formats/chat
> > > > > i just placed it before the username placeholder.
> > > > > But im already tracking that bug i belive luckperms dont give out the prefix for some reason, its also not displayed on when i pull the group in luckperms, i belive this is a luckperms issue
> > > > 
> > > > 
> > > > Update to luckperms v5.3.3 & chatcontrol v10.4.0, then try again, let me know if it fixes the issue.
> > > > Once this is done, don't forget to download luckperms PAPI expansion `/papi ecloud download LuckPerms` then `/papi reload`. And it should fix your issue
> > > 
> > > 
> > > thank you man,
> > > i found the issue it was on luckperms.
> > > the syntax for the prefix string was wrong, thats why luckperms gave no informations about it.
> > > But now im back at my Hex Gradients problem.
> > 
> > 
> > As explained in your issue, there's nothing we can do about this issue since this isn't on our end, but on other plugins not supporting gradients.
> 
> Other Plugins dont format the chat, the chat plugin read the code and translate it.
> In this example it would be luckperms, why should luckperms support gradients ^^ its the same when you as a player use color codes in the chat, the plugin has to read and translate this.
> 
> Since kangooro closed my issue without responding im afraid that a 30 Dollar plugin fails at the very basic.

Once again, that's not the plugin's work to support hex colors for other plugins.
You wonder why LuckPerms would have to support hex, then I wonder why would ChatControl handle hex for luckperms?
After all, chatcontrol is a chat management plugin, not a hex color implementation plugin/library.
ChatControl-Red doesn't fail at "the very basic" as you said, since it's never been written anywhere that the plugin does implement hex colors for other plugins. If the other plugins don't support it, then there's nothing Kangarko can do about it. He did answer your issue. Hex colors work perfectly when using them in chatcontrol, that's how it's supposed to be. If it doesn't work with your other plugins, contact their authors and ask them to implement hex colors in **their plugins**.
There's absolutely nothing "basic" about supporting hex colors. If this would be a basic feature, it would've been implemented in spigot the same way translateAlternateColorCodes was implemented, which is not the case...

EDIT: After taking a look at luckperms wiki, they actually support HEX colors : `{#RRGGBB}`.
Finally, regarding your hex color thing, if you'd like to use hex colors based on your rank, then simply use conditions in your formats.
Here's an example of how this looks on my prod server : 
```yaml
  player-nick-admin:
    Message: '{player_nick} '
    Sender_Permission: group.admin
    Hover:
    - '&c&nClick to send a DM'
    Suggest_Command: '/tell {player_name} '
    Gradient: red - yellow
  player-nick-no-island:
    Message: '{player_nick} '
    Sender_Permission: nick.default
    Sender_Condition: '''{superior_island_exists}'' == ''No'''
    Hover:
    - '&7First Join : &f{player_first_join_date}'
    - ''
    - '&c&nClick to send a DM'
    Suggest_Command: '/tell {player_name} '
```

**Comment by Parthurax** [comment]
> > > > > > also in formats/chat
> > > > > > i just placed it before the username placeholder.
> > > > > > But im already tracking that bug i belive luckperms dont give out the prefix for some reason, its also not displayed on when i pull the group in luckperms, i belive this is a luckperms issue
> > > > > 
> > > > > 
> > > > > Update to luckperms v5.3.3 & chatcontrol v10.4.0, then try again, let me know if it fixes the issue.
> > > > > Once this is done, don't forget to download luckperms PAPI expansion `/papi ecloud download LuckPerms` then `/papi reload`. And it should fix your issue
> > > > 
> > > > 
> > > > thank you man,
> > > > i found the issue it was on luckperms.
> > > > the syntax for the prefix string was wrong, thats why luckperms gave no informations about it.
> > > > But now im back at my Hex Gradients problem.
> > > 
> > > 
> > > As explained in your issue, there's nothing we can do about this issue since this isn't on our end, but on other plugins not supporting gradients.
> > 
> > 
> > Other Plugins dont format the chat, the chat plugin read the code and translate it.
> > In this example it would be luckperms, why should luckperms support gradients ^^ its the same when you as a player use color codes in the chat, the plugin has to read and translate this.
> > Since kangooro closed my issue without responding im afraid that a 30 Dollar plugin fails at the very basic.
> 
> Once again, that's not the plugin's work to support hex colors for other plugins.
> You wonder why LuckPerms would have to support hex, then I wonder why would ChatControl handle hex for luckperms?
> After all, chatcontrol is a chat management plugin, not a hex color implementation plugin/library.
> ChatControl-Red doesn't fail at "the very basic" as you said, since it's never been written anywhere that the plugin does implement hex colors for other plugins. If the other plugins don't support it, then there's nothing Kangarko can do about it. He did answer your issue. Hex colors work perfectly when using them in chatcontrol, that's how it's supposed to be. If it doesn't work with your other plugins, contact their authors and ask them to implement hex colors in **their plugins**.
> There's absolutely nothing "basic" about supporting hex colors. If this would be a basic feature, it would've been implemented in spigot the same way translateAlternateColorCodes was implemented, which is not the case...
> 
> EDIT: After taking a look at luckperms wiki, they actually support HEX colors : `{#RRGGBB}`.
> Finally, regarding your hex color thing, if you'd like to use hex colors based on your rank, then simply use conditions in your formats.
> Here's an example of how this looks on my prod server :
> 
> ```yaml
>   player-nick-admin:
>     Message: '{player_nick} '
>     Sender_Permission: group.admin
>     Hover:
>     - '&c&nClick to send a DM'
>     Suggest_Command: '/tell {player_name} '
>     Gradient: red - yellow
>   player-nick-no-island:
>     Message: '{player_nick} '
>     Sender_Permission: nick.default
>     Sender_Condition: '''{superior_island_exists}'' == ''No'''
>     Hover:
>     - '&7First Join : &f{player_first_join_date}'
>     - ''
>     - '&c&nClick to send a DM'
>     Suggest_Command: '/tell {player_name} '
> ```

![image](https://user-images.githubusercontent.com/55805110/118161004-5a7c1800-b41f-11eb-90a5-d607b09c0cb5.png)


Since every free Chat plugin no matter how less features it haves, supports this i would say yes it is a basic feature...

Yes i can add it to the formats, so chat control goes every time through all of my 20 ranks, checks the perms and add the prefix(for every player) instead of just getting a color code from LP and shows it. i dont need to be a dev to see a better way of handling this, or do you see that different ?

Indeed its not the first time i have the feeling that this plugin isnt well written.

However i really appreciate your help so far, maybe i find a solution for this.

**Comment by ElBananaa** [comment]
> > > > > > > also in formats/chat
> > > > > > > i just placed it before the username placeholder.
> > > > > > > But im already tracking that bug i belive luckperms dont give out the prefix for some reason, its also not displayed on when i pull the group in luckperms, i belive this is a luckperms issue
> > > > > > 
> > > > > > 
> > > > > > Update to luckperms v5.3.3 & chatcontrol v10.4.0, then try again, let me know if it fixes the issue.
> > > > > > Once this is done, don't forget to download luckperms PAPI expansion `/papi ecloud download LuckPerms` then `/papi reload`. And it should fix your issue
> > > > > 
> > > > > 
> > > > > thank you man,
> > > > > i found the issue it was on luckperms.
> > > > > the syntax for the prefix string was wrong, thats why luckperms gave no informations about it.
> > > > > But now im back at my Hex Gradients problem.
> > > > 
> > > > 
> > > > As explained in your issue, there's nothing we can do about this issue since this isn't on our end, but on other plugins not supporting gradients.
> > > 
> > > 
> > > Other Plugins dont format the chat, the chat plugin read the code and translate it.
> > > In this example it would be luckperms, why should luckperms support gradients ^^ its the same when you as a player use color codes in the chat, the plugin has to read and translate this.
> > > Since kangooro closed my issue without responding im afraid that a 30 Dollar plugin fails at the very basic.
> > 
> > 
> > Once again, that's not the plugin's work to support hex colors for other plugins.
> > You wonder why LuckPerms would have to support hex, then I wonder why would ChatControl handle hex for luckperms?
> > After all, chatcontrol is a chat management plugin, not a hex color implementation plugin/library.
> > ChatControl-Red doesn't fail at "the very basic" as you said, since it's never been written anywhere that the plugin does implement hex colors for other plugins. If the other plugins don't support it, then there's nothing Kangarko can do about it. He did answer your issue. Hex colors work perfectly when using them in chatcontrol, that's how it's supposed to be. If it doesn't work with your other plugins, contact their authors and ask them to implement hex colors in **their plugins**.
> > There's absolutely nothing "basic" about supporting hex colors. If this would be a basic feature, it would've been implemented in spigot the same way translateAlternateColorCodes was implemented, which is not the case...
> > EDIT: After taking a look at luckperms wiki, they actually support HEX colors : `{#RRGGBB}`.
> > Finally, regarding your hex color thing, if you'd like to use hex colors based on your rank, then simply use conditions in your formats.
> > Here's an example of how this looks on my prod server :
> > ```yaml
> >   player-nick-admin:
> >     Message: '{player_nick} '
> >     Sender_Permission: group.admin
> >     Hover:
> >     - '&c&nClick to send a DM'
> >     Suggest_Command: '/tell {player_name} '
> >     Gradient: red - yellow
> >   player-nick-no-island:
> >     Message: '{player_nick} '
> >     Sender_Permission: nick.default
> >     Sender_Condition: '''{superior_island_exists}'' == ''No'''
> >     Hover:
> >     - '&7First Join : &f{player_first_join_date}'
> >     - ''
> >     - '&c&nClick to send a DM'
> >     Suggest_Command: '/tell {player_name} '
> > ```
> 
> ![image](https://user-images.githubusercontent.com/55805110/118161004-5a7c1800-b41f-11eb-90a5-d607b09c0cb5.png)
> 
> Since every free Chat plugin no matter how less features it haves, supports this i would say yes it is a basic feature...
> 
> Yes i can add it to the formats, so chat control goes every time through all of my 20 ranks, checks the perms and add the prefix(for every player) instead of just getting a color code from LP and shows it. i dont need to be a dev to see a better way of handling this, or do you see that different ?
> 
> Indeed its not the first time i have the feeling that this plugin isnt well written.
> 
> However i really appreciate your help so far, maybe i find a solution for this.

Hey!
I can understand your concerns regarding performances, however, once again, I don't know if there's really something that could be done to fix this on the plugin side.
I'll reopen this issue so @kangarko could review it and give you a better and a final answer ^^

**Comment by kangarko** [comment]
Hey,

I just tested and can confirm that we support LuckPerms prefixes, including HEX colors, with the {player_prefix} placeholder you can use.

You'll however need to alter your HEX color syntax as you see on the screen:

<img width="567" alt="Screenshot 2021-05-17 at 18 17 53" src="https://user-images.githubusercontent.com/1918426/118522396-49dbe280-b73c-11eb-9794-bfb395f43b9e.png">

You will need to manually create a gradient though, we do not support automatic FROM-TO gradients from LuckPerms. You can use a site like this for example: https://rgb.birdflop.com/
