### ISSUE TITLE
1.16.4: Mail Autoresponder sends auto response to yourself

### ISSUE THREAD

**Issue by Seeroh** [kangarko/ChatControl#982]
When using `/mail autor` to set an auto responder, if anyone sends you mail after it has been set, you are the one that receives the auto response.

There are no error messages, and this is with (mostly) default configs. I've not touched anything related to mail, as I'm still in the process of testing all the plugin features, and setting up my configurations.

Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Funny! Thank you, I fixed that!
