### ISSUE TITLE
1.16.5: Hexcode in timed.rs JSON

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#983]
I tried replacing the color field, from for example ''gold'' to a hexcode in the #<hexcode> format, but this would not work and the plugin will error out. Tested it together with @ElBananaa and we feel like hexcodes are currently not supported in timed JSON messages.

Files:
[files.zip](https://github.com/kangarko/ChatControl-Red/files/6471891/files.zip)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Thanks will get patched!

**Comment by Sikatsu** [comment]
Thank you so much @kangarko 

Is this some leftover debug in console?

https://pastebin.com/wBtxPJhh

**Comment by kangarko** [comment]
Thanks, yes, will remove
