### ISSUE TITLE
1.16.5. What is the unmute command?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#988]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

I didnt manage to find it in the wiki. How do I unmute a player?

**Comment by TheIntolerant** [comment]
Hey,

I believe the command is /mute player <name> off
But you should be able to double check this by just running the command "/mute", assuming you haven't changed the default command for the mute feature of chatcontrol.

**Comment by kangarko** [comment]
Thanks for answering!

**Comment by nikitushu2** [comment]
Command /mute player off instead of unmuting, mutes the player permanently.

**Comment by nikitushu2** [comment]
The command conflicted with advancedban mutes. Solved, thanks!

**Comment by nikitushu2** [comment]
New issue: I have set mute:mute to mute in commands.yml but the chc still reacts only to mute:mute commands. How do I use mute command instead?

**Comment by kangarko** [comment]
It's incompatible, either use ChatControl or AdvancedBan. You can disable our mute feature completely.

**Comment by nikitushu2** [comment]
> 
> 
> It's incompatible, either use ChatControl or AdvancedBan. You can disable our mute feature completely.

I have disabled AdavancedBan, the chc still reacts to /mute:mute only. I want it to react to /mute.

**Comment by kangarko** [comment]
What if you change our Command_Alias to cmute for example? Will that work? I think you need to open AdvancedBan.jar file then open its plugin.yml and remove the mute command from its plugin.yml file hardcode

**Comment by nikitushu2** [comment]
I have removed the advancedban from the server completely but the mute is not working. Cmute does not work neither

**Comment by kangarko** [comment]
Clear up your commands.yml so you only use the default /mute from us. Ensure you have this in your settings.yml

```yaml
Mute: 

  # Should we enable this feature?
  Enabled: true

  # The commands that invoke the mute feature.
  # EDIT AS YOU WISH BUT DO NOT REMOVE THE FIRST ALIAS
  Command_Aliases: [mute]
```

If that still won't work, post me the screenshot when you type /mute what happens.

**Comment by nikitushu2** [comment]
> 
> 
> Clear up your commands.yml so you only use the default /mute from us. Ensure you have this in your settings.yml
> 
> ```yaml
> Mute: 
> 
>   # Should we enable this feature?
>   Enabled: true
> 
>   # The commands that invoke the mute feature.
>   # EDIT AS YOU WISH BUT DO NOT REMOVE THE FIRST ALIAS
>   Command_Aliases: [mute]
> ```
> 
> If that still won't work, post me the screenshot when you type /mute what happens.

I have put the `mute` word into brackets as you advised and it worked! In default configs, the word was not in brackets though.
