### ISSUE TITLE
Adversiting Ips

### ISSUE THREAD

**Issue by Zoiter7** [kangarko/ChatControl#99]
Hello, I use the free version of ChatControl.
I ask if there is a way to prevent this: 
When user spam ips, and put mc.games.net , the chatcontrol is block this
but when the user put mc gamesnet net , the chancontrol not block this

**Comment by EvilOlaf** [comment]
You could add the space character to the rule.

**Comment by Zoiter7** [comment]
I don't know how do it

**Comment by kangarko** [comment]
If the message is removed of dots (e.g. www.google.com changes to www google com), then visit the ChatControl's Wiki to read on how to fix it if using Essentials.

I don't master regex filters so I can't help you with that. Please write in the spigotmc forums as there are more folks experienced in regex.
