### ISSUE TITLE
1.16.5: "\" no longer converts metacharacters to literal characters.

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#990]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hey, this bug report is pretty straightforward but I will provide a rule below to help explain this issue.
(rule used in command.rs)
```
match ^\/test\b
then warn &cExample 1 - $0
then warn &cExample 2 - \$0
then console msg {player} \$0
then deny
```
The above should display two messages
``Example 1 - /test``
``Example 2 - $0``
and a message saying ``$0``

However, since ``\`` no longer converts metacharacters to literal characters, this is what I get instead
``Example 1 - /test``
``Example 2 - \/test``
and a message saying ``\/test``

**Comment by kangarko** [comment]
Sorry, this is unsupported for $ substitution. Adding a complicated negative lookbehind regex would just cause performance overhead, 99% users never use this.
