### ISSUE TITLE
1.16.5: Can you reset /ignore <player> after x amount of time?

### ISSUE THREAD

**Issue by GeleVla** [kangarko/ChatControl#991]
Can you reset /ignore <player> after x amount of time?

So that you don’t miss out any messages after like 1 hour of ignore?

**Comment by ElBananaa** [comment]
> Can you reset /ignore after x amount of time?
> 
> So that you don’t miss out any messages after like 1 hour of ignore?

Hey!
As far as I know, this isn't possible now, but I truly think that this would be a truly good idea. Let's wait for Kangarko to review this ^^

**Comment by kangarko** [comment]
Currently you can't, but I'll take that as a suggestion!
