### ISSUE TITLE
1.16.5: Ignore.Bidirectional cannot be enabled.

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#992]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**What is the bug?**

``Ignore.Bidirectional`` seems to no longer have any effect on how ``/ignore`` works, since still behaves as if ``Ignore.Bidirectional`` is set to ``false`` regardless of that setting.

--------------------------------

**An extra bug relating to ``Ignore.Bidirectional`` I was meant to report awhile ago**

I forgot to report an issue related to this a while ago but I'll mention it here, just so it's something that can be checked while looking into the above issue. Basically, when this was working it seemed the perm:

```yml
- "chatcontrol.bypass.reach" 
# Send messages and private messages to players who ignore you, or have PMs disabled.
```

Did not allow staff to send messages to players who have you ignored if ``Ignore.Bidirectional`` was enabled. However, this was not the case if ``Ignore.Bidirectional`` was disabled then that permission worked as intended.

**Comment by kangarko** [comment]
Thanks, we had to disable that option for now due to some other problems, I'll put a note to have a look later.
