### ISSUE TITLE
1.16.5: remove message error: Name cannot be null

### ISSUE THREAD

**Issue by GeleVla** [kangarko/ChatControl#993]
```
------------------------------------[ 14.05.2021 15:16:05 ]-----------------------------------
ChatControlRed 10.4.0 encountered an IllegalArgumentException
Running Purpur 1.16.5-R0.1-SNAPSHOT and Java 11.0.10
Plugins: PlaceholderAPI v2.10.9, Realistic_World v4.27.18, CraftingStore v2.6.4, LightAPI v3.4.6, LuckPerms v5.2.76, AutoBroadcast v3.1, SpigotGuard v6.2.0 BULLET-PROOF, Playtimes v1.3.10, ProtocolLib v4.6.0, ChatBrawl v2.0, PunishGUI v1.0.6, BeehivesPro v1.1.2, Vault v1.7.3-b131, eBackup v1.1.4, UltraCosmetics v2.5.10, Matrix v6.1.1, PerWorldInventory v2.3.2, HolographicDisplays v2.4.6, BungeeGuard v1.2-SNAPSHOT, MyCommand v5.7.1, dynmap v3.1-457, WorldEdit v7.2.4+5723-e3bfc64, Essentials v2.18.2.0, LiteBans v2.6.11, Multiverse-Core v4.2.2-b812, RocketPlaceholders v1.9.1-SNAPSHOT, TradeSystem v1.3.0, TimeIsMoney v1.9.6.18, TAB v2.8.10, WorldEditSelectionVisualizer v2.0.8, Chunky v1.2.54, InteractionVisualizer v1.14.10.7, WorldGuard v7.0.4+f7ff984, EssentialsProtect v2.18.2.0, GSit v[5.1.2.0], NexEngine v2.0.6, EssentialsSpawn v2.18.0.0, CoreProtect v19.5, WorldGuardExtraFlags v4.1.5-SNAPSHOT, Harbor v1.6.3, Skript v2.5.3, SkQuery v4.1.3, Citizens v2.0.27-SNAPSHOT (build 2307), DiscordSRV v1.22.0, Plan v5.3 build 1284, Minecord v1.7.14_2, Lands v5.7.4, GoldenCrates v3.11.0, QuantumShop v3.12.1, SmoothTimber v1.15.0, ChestProtect v3.8.4, ChatControlRed v10.4.0, DeluxeCombat v1.20.2, DeluxeCombat_Addon_WG v0.8
----------------------------------------------------------------------------------------------

More Information: 
Failed to execute scheduled task: java.lang.IllegalArgumentException: Name cannot be null
IllegalArgumentException Name cannot be null
	 at org.apache.commons.lang.Validate.notNull(Validate.java:192)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.getPlayerExact(CraftServer.java:563)
	 at org.bukkit.Bukkit.getPlayerExact(Bukkit.java:501)
	 at org.mineacademy.chatcontrol.model.Packets.removeMessage0(Packets.java:408)
	 at org.mineacademy.chatcontrol.model.Packets.lambda$removeMessage$0(Packets.java:397)
	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	 at java.base/java.lang.Thread.run(Thread.java:834)
----------------------------------------------------------------------------------------------
```

**Comment by ElBananaa** [comment]
> ```
> ------------------------------------[ 14.05.2021 15:16:05 ]-----------------------------------
> ChatControlRed 10.4.0 encountered an IllegalArgumentException
> Running Purpur 1.16.5-R0.1-SNAPSHOT and Java 11.0.10
> Plugins: PlaceholderAPI v2.10.9, Realistic_World v4.27.18, CraftingStore v2.6.4, LightAPI v3.4.6, LuckPerms v5.2.76, AutoBroadcast v3.1, SpigotGuard v6.2.0 BULLET-PROOF, Playtimes v1.3.10, ProtocolLib v4.6.0, ChatBrawl v2.0, PunishGUI v1.0.6, BeehivesPro v1.1.2, Vault v1.7.3-b131, eBackup v1.1.4, UltraCosmetics v2.5.10, Matrix v6.1.1, PerWorldInventory v2.3.2, HolographicDisplays v2.4.6, BungeeGuard v1.2-SNAPSHOT, MyCommand v5.7.1, dynmap v3.1-457, WorldEdit v7.2.4+5723-e3bfc64, Essentials v2.18.2.0, LiteBans v2.6.11, Multiverse-Core v4.2.2-b812, RocketPlaceholders v1.9.1-SNAPSHOT, TradeSystem v1.3.0, TimeIsMoney v1.9.6.18, TAB v2.8.10, WorldEditSelectionVisualizer v2.0.8, Chunky v1.2.54, InteractionVisualizer v1.14.10.7, WorldGuard v7.0.4+f7ff984, EssentialsProtect v2.18.2.0, GSit v[5.1.2.0], NexEngine v2.0.6, EssentialsSpawn v2.18.0.0, CoreProtect v19.5, WorldGuardExtraFlags v4.1.5-SNAPSHOT, Harbor v1.6.3, Skript v2.5.3, SkQuery v4.1.3, Citizens v2.0.27-SNAPSHOT (build 2307), DiscordSRV v1.22.0, Plan v5.3 build 1284, Minecord v1.7.14_2, Lands v5.7.4, GoldenCrates v3.11.0, QuantumShop v3.12.1, SmoothTimber v1.15.0, ChestProtect v3.8.4, ChatControlRed v10.4.0, DeluxeCombat v1.20.2, DeluxeCombat_Addon_WG v0.8
> ----------------------------------------------------------------------------------------------
> 
> More Information: 
> Failed to execute scheduled task: java.lang.IllegalArgumentException: Name cannot be null
> IllegalArgumentException Name cannot be null
> 	 at org.apache.commons.lang.Validate.notNull(Validate.java:192)
> 	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.getPlayerExact(CraftServer.java:563)
> 	 at org.bukkit.Bukkit.getPlayerExact(Bukkit.java:501)
> 	 at org.mineacademy.chatcontrol.model.Packets.removeMessage0(Packets.java:408)
> 	 at org.mineacademy.chatcontrol.model.Packets.lambda$removeMessage$0(Packets.java:397)
> 	 at org.mineacademy.chatcontrol.lib.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
> 	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
> 	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
> 	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> 	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	 at java.base/java.lang.Thread.run(Thread.java:834)
> ----------------------------------------------------------------------------------------------
> ```

Hey!
Could you please give us more informations?
Do you know when this happened? Was one of your players doing something special? Did you use a specific command?
Also, could you please make sure all your dependencies and your server software are up-to-date? In many situations, issues can be caused by outdated versions.
From what I understand, you were trying to remove a message using the remove feature?
If so, keep in mind that (I think), you can't remove private messages.

**Comment by kangarko** [comment]
Thanks will get patched.
