### ISSUE TITLE
1.16.5 How to disable join and leave messages of the channels?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#994]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

I either join or leave a particular chat channel and a personal msgs appears in the chat (either that i have joined or left the channel). How to disable these messages?

**Comment by kangarko** [comment]
You can find and set these messages to "none" in our localization:

https://github.com/kangarko/ChatControl-Red/wiki/Localization
