### ISSUE TITLE
Paper 1.16.5 | Issue with EternalTags placeholders

### ISSUE THREAD

**Issue by 6IXESSIVE** [kangarko/ChatControl#997]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6487589/debug.zip)

Placeholders for https://www.spigotmc.org/resources/eternaltags.91842/ do not work:
%eternaltags_tag% %eternaltags_tag+% {eternaltags_tag} etc.
%eternaltags_tag_formatted% 

But when parsing with PAPI they work perfectly

1.16.5 server - Latest CHC version
MySQL: false
BungeeCord: false

All dependencies are up to date

https://cdn.discordapp.com/attachments/838892553277407312/843131694890221609/unknown.png

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6487589/debug.zip)
> 
> Placeholders for https://www.spigotmc.org/resources/eternaltags.91842/ do not work:
> %eternaltags_tag% %eternaltags_tag+% {eternaltags_tag} etc.
> %eternaltags_tag_formatted%
> 
> But when parsing with PAPI they work perfectly
> 
> 1.16.5 server - Latest CHC version
> MySQL: false
> BungeeCord: false
> 
> All dependencies are up to date
> 
> https://cdn.discordapp.com/attachments/838892553277407312/843131694890221609/unknown.png

Hey!
From what I can see in you error.log, you used `%eternaltags_tag%`. Try using `{eternaltags_tag}` instead.
Also make sure to update to the latest CHC version (which is chc 10.4.1) ^^

**Comment by 6IXESSIVE** [comment]
we tried without the plus as well https://cdn.discordapp.com/attachments/838892553277407312/843178649518866483/unknown.png

**Comment by ElBananaa** [comment]
> we tried without the plus as well https://cdn.discordapp.com/attachments/838892553277407312/843178649518866483/unknown.png

Unfortunately, I can't do anything else regarding this, you should wait for Kangarko to have a look at your issue. ^^

**Comment by kangarko** [comment]
I don't believe we support placeholders inside placeholders for that one.

**Comment by Oribuin** [comment]
I am not entirely sure how you managed to mess up PAPI Placeholders but I digress.

Trying to find a solution with it but I have no clue, I don't register my placeholders any differently than anyone else does, I recommend actually looking into the issue instead of saying "guess we don't support it" The source code is public so if you can find anything let me know. https://github.com/Oribuin/EternalTags/ 

Edit: This was directed at kangarko

**Comment by Oribuin** [comment]
I found the solution, I switched it from onPlaceholderRequest to onRequest at the end. This is still a problem you should look into, Most other chat plugins work perfectly fine with EternalTags and for a 30 euro plugin that claims to be #1, kinda disappointed honestly.

**Comment by kangarko** [comment]
I don't practically have time to look into every single integration and its issues, sorry about that. I appreciated your fixing.
