### ISSUE TITLE
1.16.5: Using Formats for Bungeecord join/quit messages

### ISSUE THREAD

**Issue by Seeroh** [kangarko/ChatControl#998]
With the change to BungeeControl-Red allowing a rules file for Join/Quit/Switch messages on the bungeecord instance, I'm wondering if there is a way to support formats for those? Specifically, I'm looking to create a hover timestamp for join/quit messages for admins. As it stands, I don't think it works, but it's good to just ask and find out.

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: true

**Comment by kangarko** [comment]
We'd have to port our entire formatting system there and I don't want to maintain two systems that are close to similar right now due to complexity
